### ISSUE TITLE
Large Windowed Lumber Door doesn't open (7.8.0)

### ISSUE THREAD

**Issue by Haldorr** [StrangeLoopGames/EcoIssues#10006]
Game Version 7.8.0

The Large Windowed Lumber Door doesn't open. If hovering over it, it doesn't even list the ability to right-click it to open. When pressing "E" to "Use" only shows the authorization window and the status as "Turned Off".

Worked as intended before the patch at exactly the same location. Also noted, that patching the game up to 7.8 closed the door.

**Comment by Quadbro** [comment]
Any large door can't be open (tested)

**Comment by johnkslg** [comment]
Hotfix incoming!
