### ISSUE TITLE
USER ISSUE: Stockpile blocks interaction with surrounding objects

### ISSUE THREAD

**Issue by Sandflakes** [StrangeLoopGames/EcoIssues#10008]
**Version:** 0.7.8.0 beta

**Steps to Reproduce:**
1. Place a stockpile.
2. Fill up the stockpile.
3. Walk up as close as possible to the items in the stockpile.
4. Try to dig, mine or pick up an item from the ground beside the stockpile.

**Expected behavior:**
The object that you are aiming on should be targeted.

**Actual behavior:**
The stockpile is always targeted, preventing you from interacting.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by Deantwo** [comment]
Doesn't sound like a new issue, had that _issue in v7.7.2, or had it gotten worse?
At least in v7.7.2 it was very clear that you were gonna hit the stockpile since it was highlighted, so while it was annoying it was not a major issue.
