### ISSUE TITLE
7.8.0 server wont load

### ISSUE THREAD

**Issue by bleckman74** [StrangeLoopGames/EcoIssues#10005]
I was Told Just to LInk the World and dump File
https://drive.google.com/file/d/1KVKrQQjTt1Ylopq9OMhvRbrUOGPOazhW/view?usp=sharing
https://drive.google.com/file/d/1szSDZ_TrYC7sl7mFny7x3p2lTH8ctyGN/view?usp=sharing

please stop deleting my bug reports

**Comment by bleckman74** [comment]
no mods installed

**Comment by D3nnis3n** [comment]
Your issue is a duplicate issue of this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9997
It does not help at all to recreate closed issues. I made sure your map is on the respective issue.
