### ISSUE TITLE
Failed to connect - connection timed out

### ISSUE THREAD

**Issue by GriffIngalls** [StrangeLoopGames/EcoIssues#10004]
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2018.2.0f2 (787658998520)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   
    VRAM:     8088 MB
    Driver:   24.21.13.9836
Begin MonoManager ReloadAssembly
- Completed reload, in  0.095 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.341902 ms
Client version: 0.7.7.2 beta
Tuesday, September 11, 2018 12:08 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by D3nnis3n** [comment]
Could you elaborate a bit on the circumstances this happened? What server did you try to join? Was it your Singleplayer? A Multiplayer Server?

**Comment by GriffIngalls** [comment]
I tried to join this one:  104.247.203.243:3010

It's a multiplayer server.

**Comment by GriffIngalls** [comment]
I can connect fine using the + button.

**Comment by D3nnis3n** [comment]
Probably related to the master server.

**Comment by GriffIngalls** [comment]
Understand.  I only get the error when attempting to connect via my in-game Favorites list Join button.

**Comment by GriffIngalls** [comment]
This is resolved now, thank you!
