### ISSUE TITLE
7.8 Server Crash on ModKit load

### ISSUE THREAD

**Issue by mjrekich** [StrangeLoopGames/EcoIssues#10011]
--BEGIN DUMP--
Dump Time
11/14/2018 12:48:43

Exception
Exception: Exception
Message:Error in HousingTierDefinition at 15: Member 'Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])' cannot be accessed with an instance reference; qualify it with a type name instead (CS0176)

Source:Eco.ModKit

System.Exception: Error in HousingTierDefinition at 15: Member 'Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])' cannot be accessed with an instance reference; qualify it with a type name instead (CS0176)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(ManualResetEvent doneEvent)

--END DUMP--

No mods installed

Zip file: https://www.dropbox.com/s/up7mozhi8phxjaj/Eco%20Server.zip?dl=0

**Comment by pamduncan** [comment]
I believe I have another player with this issue:

--BEGIN DUMP--
Dump Time
01/05/2019 21:17:51

Exception
Exception: Exception
Message:Error in HousingTierDefinition at 15: Не удается получить доступ к члену "Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])" по ссылке на экземпляр; уточните имя типа (CS0176)

Source:Eco.ModKit

System.Exception: Error in HousingTierDefinition at 15: Не удается получить доступ к члену "Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])" по ссылке на экземпляр; уточните имя типа (CS0176)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done)

--END DUMP--

**Comment by pamduncan** [comment]
Update:  In the process of trying to see what would work and what would not, the server was taken back to 7.5.0 and installed and it worked so then taken  back to 7.8.8 and then the server built without issue

The only thing I can think is that Steam is missing installing a file or is not picking up on a bad file when verification is run and we have seen this happen before.  But in moving and installing different version the right file was installed eventually for 7.8.8 to work.  He previously had run a file verification which reported everything there and no bad files and he did do a reinstall just in case but that did not help.  Going back to a much older version did which is odd

**Comment by SlayksWood** [comment]
Can't reproduce for latest versions. If it happens again, please reopen.
