### ISSUE TITLE
co2 7.8.0

### ISSUE THREAD

**Issue by Zimgaha** [StrangeLoopGames/EcoIssues#10014]
co2 levels don't seem to be working since 7.8.0. Also the co2 reduction from plants ect is set to 0. 
![20181114190708_1](https://user-images.githubusercontent.com/44818253/48506144-ae064e80-e840-11e8-8e0e-b781429cb063.jpg)

**Comment by D3nnis3n** [comment]
Confirmed.

@BlazeGuy2 QA-Pass states nothing about testing CO2 functionality. Prrobably add this?

**Comment by Quadbro** [comment]
I don't have even this)) 
![image](https://user-images.githubusercontent.com/6802030/48931299-28615d80-ef28-11e8-8959-4335ac3cb773.png)

**Comment by elfl0rd** [comment]
Launch any process (you need smog in output)

**Comment by Quadbro** [comment]
i did, but result is the same)

**Comment by elfl0rd** [comment]
it looks as smog broken on 7.8.5 )))

**Comment by elfl0rd** [comment]
Hmm... My 0.7.8.5
![20181123161720_1](https://user-images.githubusercontent.com/4980243/48945511-bbf05980-ef3b-11e8-8d36-9f7a3165fcd1.jpg)
![Uploading 20181123162005_1.jpg…]()

**Comment by Quadbro** [comment]
That is strange...) I'll try to achieve same result, because now i steel have completely broken one)

**Comment by elfl0rd** [comment]
Hmm... In discord players reported as co2 fully broken...
![default](https://user-images.githubusercontent.com/4980243/48966788-c4529e00-efe8-11e8-8d3d-92ee0293daa0.png)

**Comment by Quadbro** [comment]
@johnkslg , @BlazeGuy2  can someone help me with that issue?
