### ISSUE TITLE
[7.8.1] Law: Unable to propose Add Demographic laws

### ISSUE THREAD

**Issue by TheKrush** [StrangeLoopGames/EcoIssues#10017]
As you can see in the screenshot there is no textbox for entering a demographic name. (I thought the name of the law was the same as the demographic name)

Chrome:
![image](https://user-images.githubusercontent.com/671500/48518079-425eba00-e81d-11e8-8be2-dee25fbc187b.png)

There is no name field, which results in a hidden 400 error:
![image](https://user-images.githubusercontent.com/671500/48518116-6ae6b400-e81d-11e8-9f84-b73b28014f7d.png)

This error is only visible in the console of the browser and no feedback is provided on to the user as to why the button for 'Propose Law' isn't working.

**No dump files generated, and no error on the website showing a end-user why the Propose Law button is seemingly not working.**

**Comment by TheKrush** [comment]
As you can see in the screenshot there is no textbox for entering a demographic name. (I thought the name of the law was the same as the demographic name)

**Comment by TheKrush** [comment]
Inspecting the resulting HTML the input field isn't added for chrome.

Microsoft Edge:
![image](https://user-images.githubusercontent.com/671500/48519763-e9922000-e822-11e8-9e58-4ccdc2a45219.png)

Chrome:
![image](https://user-images.githubusercontent.com/671500/48519773-f6167880-e822-11e8-8d9b-32c2ffd22548.png)

**Comment by TheKrush** [comment]
Microsoft Edge:
![image](https://user-images.githubusercontent.com/671500/48523464-62987400-e831-11e8-9c12-a0ff189e2ce2.png)

**Comment by Deantwo** [comment]
You don't happen to have any Chrome browser extensions that could be causing this?
I'll try it when i get home from work, but it is worth check out.

**Comment by D3nnis3n** [comment]
As in my QA-Pass i can still NOT reproduce this. This is what i get on Version Chrome 70.0.3538.102 (64-Bit)

<img width="484" alt="chrome" src="https://user-images.githubusercontent.com/25908592/48573913-0c4d3300-e90e-11e8-96ad-e2c6abb916a7.png">

**Comment by TheKrush** [comment]
Google Chrome is up to date
Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by TheKrush** [comment]
I do have extensions but I specifically disabled all of them to test and make sure they weren't affecting this.

**Comment by TheKrush** [comment]
Weird it seems to have stopped occurring today. At least on one of my machines, I'll check the others when I get home.

**Comment by TheKrush** [comment]
Seems to not be happening on any of my browsers now.

**Comment by D3nnis3n** [comment]
Alright, reopen if it happens again.
