### ISSUE TITLE
ServerCrash AggregateException

### ISSUE THREAD

**Issue by GriffIngalls** [StrangeLoopGames/EcoIssues#10013]
I'm getting an error on server launch.  This is after the update to 0.7.8.

Here's dump:

--BEGIN DUMP--
Dump Time
11/14/2018 10:48:00

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.PropertyManager.GetDeed(Guid deedId)
   at Eco.Gameplay.Utils.PickerProperty.get_Deed()
   at Eco.Gameplay.Utils.PickerProperty.OnDeserialized()

--END DUMP--

**Comment by BlazeGuy2** [comment]
@GriffIngalls Should be hotfixed out later today in 7.8.1.  Reopen if still crashing when that version releases.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9997

**Comment by D3nnis3n** [comment]
Urgh, too slow.
