### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by truGamer** [StrangeLoopGames/EcoIssues#10019]
**Version:** 0.7.8.1 beta

**Steps to Reproduce:**
Start new world- No collab- Generate new=true- GiveSkillpointsuponcrafting=true-

**Expected behavior:**
Created a brand new seed, and made a new planet

**Actual behavior:**
The following error message popped up:
```Connection Failed```
Connection Failed
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```Connection Failed```
Connection Failed
```

**Comment by truGamer** [comment]
{{Mods = ```false```}}

**Comment by truGamer** [comment]
Upon ```Loading SleepPlugin...```,
   ```Connection Lost```
               ``` < 1 person is on server```

**Comment by truGamer** [comment]
Make it so that ```< 1 online then initiate sleepplugin```
Says: ```≤ 1 online then initiate sleepplugin```. So that if the person that is alone can initiate fastforward.

**Comment by BlazeGuy2** [comment]
PR in for fixing this

**Comment by truGamer** [comment]
> PR in for fixing this

PR = Please report : in for fixing this?

**Comment by elfl0rd** [comment]
PreRelease - fix published in next hotfix.

**Comment by truGamer** [comment]
> PreRelease - fix published in next hotfix.

I already got the response via Discord, and it means "Pull Request"
