### ISSUE TITLE
USER ISSUE: No multiplayer

### ISSUE THREAD

**Issue by PrincessLiea** [StrangeLoopGames/EcoIssues#10010]
**Version:** 0.7.8.0 beta

**Steps to Reproduce:**
when open new game. there is no server listed.	

**Expected behavior:**
it should have all server listed.

**Actual behavior:**
The following error message popped up:
```
Failed to establish connection - no response from remote host
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Failed to establish connection - no response from remote host
```

**Comment by PrincessLiea** [comment]
i dont have mod installed

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9999

Known issue - we are working on it.
