### ISSUE TITLE
/unclaimabandon bug

### ISSUE THREAD

**Issue by Mitazaki** [StrangeLoopGames/EcoIssues#10015]
Using this command seems to have the opposite effect and will always un-claim the most active players and save claims for the most inactive based on the days you enter.

Maybe a < or > should be changed in the code or something?

> For example, I was looking to un-claim land from someone who had not been online for more than 5 days
> 
> I done:
> /unclaimabandon 4 ( assuming anyone with over 4 days inactivity would have their land unclaimed )
> 
> It saved his land and land of other players who were inactive more than 4 days and removed my claim and other active players claims and I was online and active at the time.

**Comment by johnkslg** [comment]
Fixing

**Comment by D3nnis3n** [comment]
Fixed in 7.8.4, at least in 7.8.5.
