### ISSUE TITLE
Error on change of districts

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10016]
See the screenshot. The blue ones were added:
<img width="1592" alt="districts" src="https://user-images.githubusercontent.com/25908592/48517727-7fe83500-e867-11e8-82a0-1af5bba6b23e.png">

**Comment by D3nnis3n** [comment]
Cannot reproduce this reliable. I used another browser to try again and it worked there after repainting the districts.

**Comment by Deantwo** [comment]
Before I passed requirement for Citizenship law, I was getting a simliar error message when attempting to run for office.

**Comment by D3nnis3n** [comment]
Closed, as Deantwo is right and one issue is enough.
