### ISSUE TITLE
"Report a bug" on "connect failed" error generate incorrect GH code.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10012]
**Version:** 0.7.8.0 beta
As i see, generated code gor GH incorrect, you can see result in many ussues.
e.g.
https://github.com/StrangeLoopGames/EcoIssues/issues/10010
![20181114205808_1](https://user-images.githubusercontent.com/4980243/48502417-8919d780-e850-11e8-8cad-0138d0b96bd6.jpg)
![20181114205812_1](https://user-images.githubusercontent.com/4980243/48502423-8b7c3180-e850-11e8-982d-79fa546db51e.jpg)
![default](https://user-images.githubusercontent.com/4980243/48502392-7e5f4280-e850-11e8-8a7f-9c61461069ea.png)
![default](https://user-images.githubusercontent.com/4980243/48502472-ababf080-e850-11e8-8025-e51ece23afeb.png)

**Comment by Quadbro** [comment]
Sorry, pushed that fix only to master, now it's in release too

**Comment by Deantwo** [comment]
Bump, something is till wrong.
For example see: #10497
