### ISSUE TITLE
Logging on to ECO hangs right after tree/logo does not go to menu (MacOS)

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10024]
Xoiiku says he can be contacted on discord if you have questions but he did not want to make a bug reports, so I apologize to those who don't like the bug reports from someone who is not the person having the  bug .  

He is the Mac user who can get as far as the tree animation and then the Eco logo and then it hands and does not log onto the menu screen.  This is 7.8.1 but he tried on 7.8.0 also and then rolled back to 7.7.2 where it had been working and does not now

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce.
Do you have this problem now?

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
