### ISSUE TITLE
7.8.1 /FastForward command start time running away immediately before player gets a bed

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10023]
SilentStorm wanted to know how to turn on 'sleep' so gave him the /fasrtforward command which I understood set the sleep to ture (or on) and then he could make a bed and go to sleep.  However when he used the chat command it immediately started fastforwarding the game and he had not even set up a bed, and it would not stop.  He has to leave the game to have it stop.  

Setting in 'true' in the config file and it worked fine, time did not speed up until he was in bed.  So looks like something with the chat command itself

**Comment by Deantwo** [comment]
Someone need to add the `/fasrtforward` command to the wiki so we know what it does and how to use it.
I can add it if you tell me what to write.
See: https://eco.gamepedia.com/Chat_Commands

**Comment by Deantwo** [comment]
https://ecoauth.strangeloopgames.com/changelog
```
/fastforward - Toggles the fast forward effect from sleep on and off.
```
It says it toggles the EFFECT of sleep on/off, not the option to sleep.
So tge command works, it is just written in a way that can be confused.

**Comment by D3nnis3n** [comment]
This is working as intended as an admin command to fast-forward time until you stop it again. (Use parameters 0 and 1)
You can activate sleep in the sleep.eco config file by setting `"AllowFastForward": true`.
