### ISSUE TITLE
Alpha 5.3 - Cannot interact (drop or take) blocs under water

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#1002]
Pre-requirement:
- In Alpha 5.3

**Scenario 1:**
-Step to reproduce:
1. Take your shovel and try to take a bloc (dirt, sand...) under water.

-Results:
Cannot take the bloc, there is no green lines around the bloc

-Expected Results:
Should be able to take a bloc of dirt, sand... under water.

**Scenario 2:**
-Step to reproduce:
1. Take your shovel with dirt on it and try to drop the dirt bloc under water.

-Results:
Cannot drop the bloc under water.

-Expected Results:
Should be able to drop the bloc of dirt under water.

********************************************
Note:
- All blocks that can be used by a tool will have the same issue. (hypothetical)
- Is it by design? 

Workaround:
- To put blocks under water, the player will have to elevate the ground near the water by one block and put a block of dirt (or any dropping block by gravitation) on the side of the elevated block and over the water, so the dirt block will fall in the water. So with the falling dirt, the player can fill a lake and remove the dirt to be able to reach the ground of the old lake.

**Comment by metachronism** [comment]
already fixed in internal builds, so this will be fixed in 5.4

**Comment by fillion07** [comment]
thanks metachronism :)
