### ISSUE TITLE
USER ISSUE: Can't create my own world.

### ISSUE THREAD

**Issue by Tichondria80** [StrangeLoopGames/EcoIssues#10021]
**Version:** 0.7.8.1 beta

**Steps to Reproduce:**
Try to create my own world. Can't get past loading SLeep.

**Expected behavior:**
Created a new world for me to play in

**Actual behavior:**
Failed to establish connection, no responce to remote hostn
**Do you have mods installed? Does issue happen when no mods are installed?:**
Failed to establish connection, no responce to remote host

Failed to establish connection - no response from remote host
[error issue.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2583359/error.issue.txt)

**Comment by BlazeGuy2** [comment]
PR in for fixing this, issue was trying to save to a config before it was initialized.

**Comment by Tichondria80** [comment]
Thank you!!!


Miranda fister

**Comment by Tichondria80** [comment]
Ok.. this is not fixed for me. I tried to find the line truGamer was talking about but I can't find where it's at to change it. I have verified integrity of game again. And still can not get past SleepPlugin. I can play in older worlds I have created without an issue. What do I need to do to fix  this because if they patched it.. it is still not fixed for me.

**Comment by BlazeGuy2** [comment]
Patch just released seconds ago, try using that.  Make sure that it says 7.8.2 in the bottom right corner of the esc menu.

**Comment by BlazeGuy2** [comment]
@Tichondria80

**Comment by Tichondria80** [comment]
@BlazeGuy2 EUREEKA!!! I can finally play it again. Thank you, thank you, thank you. :) I'm very very happy. Give the person who fixed it a huge hug and cookie they deserve it :)
