### ISSUE TITLE
WorkOrder should update ingredients and products with recipe changes

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#10028]
If for some reason recipe which used to create WorkOrder was changed (changes in efficiency, or changes in Recipe ingredients, or if it was modified by Mod) then in current implementation it will just ignore these changes. 
If some items become unavailable (if for exampe they was added by mod and then mod was disabled) then they will just disappear from WorkOrder leaving it with wrong ingredients or even for worst case without ingredients at all.
So it makes sense to redo WorkOrder to have a link to original Recipe. In this case on load we can recalculate all required ingredients. And also we can track changes in Recipe modifiers and also dynamically recalculate requirements.

**Comment by elfl0rd** [comment]
Hmm... Okay, you have 2 benches... One complete job, efficiency raised... Secondary cancel job? Not fair...
In addition as i see, in 0.8 you cannot lower efficiency, recalculate is better in this case.

**Comment by metachronism** [comment]
crafting scrap fixes this, stop doing bandaid changes!

**Comment by mirasrael** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9903
