### ISSUE TITLE
Login not returning error message from auth

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10034]
For example: Tried to login with use that does not own Eco.
error said username and password was wrong.
But auth was returning:
{"error":"Eco is currently open to alpha and beta backers only. Upgrade your account to join.","status":false}

**Comment by WeaselDog** [comment]
The error message is fixed now:
![NoAccount](https://user-images.githubusercontent.com/47330823/71788023-82f63580-2fd3-11ea-93f7-b66026ae1442.png)
