### ISSUE TITLE
New World stuck on "Entering World"

### ISSUE THREAD

**Issue by Zagamun** [StrangeLoopGames/EcoIssues#10039]
Version: 0.7.8.2 beta

Steps to Reproduce:
Try to start a new world

Expected behavior:
Server loads and game joined

Actual behavior:
Loading the server happens quickly but once it gets to "Entering World" it just sits there forever and never actually joins. The game isn't frozen at all. When I hit escape I go back to the menu. I've tried multiple servers and they all have the same issue. Single player works perfectly.

**Comment by BlazeGuy2** [comment]
@Zagamun are you using Steam or did you download from the Eco site?

**Comment by Zagamun** [comment]
I’m using Steam

**Comment by JAGGANOT** [comment]
hi i have the same issue ther is a log 
[Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2592122/Log.txt)

**Comment by beastyn** [comment]
Didn't meet in 0.8.14.
Please reopen if issue occures
