### ISSUE TITLE
Placement problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1003]
![image](https://cloud.githubusercontent.com/assets/3536496/21732479/87cdb9da-d40e-11e6-9306-5f90173c8d21.png)
- Placing is behaving strangely with plants
- Placing on ground will replace the ground

**Comment by metachronism** [comment]
looks like you havent synced SVN, resulting in these plants being tagged wrong

**Comment by metachronism** [comment]
working fine in master
