### ISSUE TITLE
7.8.1 Elk Mount has no texture?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10035]
![elk](https://user-images.githubusercontent.com/25908592/48586747-1c2a3e80-e931-11e8-8b89-d2d67dc076f1.png)

**Comment by BlazeGuy2** [comment]
@D3nnis3n What version is this happening on?

**Comment by D3nnis3n** [comment]
7.8.1

>

**Comment by craig-jong** [comment]
Still happening in 7.8.3

![image](https://user-images.githubusercontent.com/18184943/48665181-fc913400-ea5e-11e8-8b4b-323f15a9d240.png)

**Comment by Sandflakes** [comment]
Title is incorrect, the model is there but it is missing a texture.

**Comment by D3nnis3n** [comment]
Still happening on 7.8.4.

**Comment by elfl0rd** [comment]
Still on master 
![default](https://user-images.githubusercontent.com/4980243/49683196-9cc40100-fad1-11e8-9611-a2145217a2c9.png)

and latest release.

**Comment by keegan-o** [comment]
Fixed in master.
