### ISSUE TITLE
Mod Icons are a bit broken and other issues.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#10038]
With the new update(0.7.8 - 0.7.8) all modded icons are very big on the map.
![image](https://user-images.githubusercontent.com/17730996/48618087-e58c0c80-e9a0-11e8-885c-5451ff097b44.png)
Some modded object don't work at all and cant be placed.
Most modded object of mine have the following error but I'm gonna use BedroomChestObject / Item as an exmaple; it gives the following error when a player tries to place it and they also get kicked from there server when trying to do so.
[Error is here.](https://github.com/StrangeLoopGames/EcoIssues/files/2589038/error.txt)
Also the error ingame is just an empty text box and you can see it only if you press "Copy text...".
![image](https://user-images.githubusercontent.com/17730996/48618580-80d1b180-e9a2-11e8-8333-feb11f829310.png)

**Comment by D3nnis3n** [comment]
Are these issues still recent?

**Comment by SlayksWood** [comment]
If it happens again, please reopen.
