### ISSUE TITLE
USER ISSUE: large windowed lumber door broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10037]
**Version:** 0.7.8.2 beta
Ignore input and cannot be open.
![default](https://user-images.githubusercontent.com/4980243/48600846-b06ec280-e97e-11e8-86c8-77e7e8f50c3a.png)

**Comment by pamduncan** [comment]
Another door issue, this one apparent has permissions   
![largewindows](https://user-images.githubusercontent.com/26786843/48611900-3289c780-e93c-11e8-9601-475c8ba98120.png)

**Comment by D3nnis3n** [comment]
It was planned to be fixed for 7.8.1 and a fix was included but did not work - hence there is no note of it in the changelog.

**Comment by Quadbro** [comment]
I'll write here again, there was no info on the"doors" got fix. I only said in discord, that probably doors has the same problems, as a tractor (broken prefab). But it seems like it's not. And i'm working on the doors...

**Comment by D3nnis3n** [comment]
Probably John misunderstood this. I did not tell him those are being looked on, though, as i didn't even know. Also, only the tractor issue was marked fixed.

**Comment by BlazeGuy2** [comment]
Keegan and I updated their prefabs, should be out in the next hotfix.
