### ISSUE TITLE
admin /dump  command ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1004]
how do you get it to dump other players back packs someone like admin to dump some of stuff out form his backpack to clean it.

also is there under the give command you can give skill points is there way to take away skill points ?

**Comment by noblackthunder** [comment]
you need to use the forums for search. Only bug reports here please. Admin commands are been worked at. so they will in the future get a larger overhaul.

for current commands check out this here http://eco.gamepedia.com/Chat_Commands
