### ISSUE TITLE
Setting "Hide servers that don't share my language" confuses players.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10042]
It would make sense if the servers were multilingual... But not in the current conditions when only part of the translation depends on the server.

In addition, you get TWO settings for ignoring servers in other languages. That confuses players even more.
First - main menu. I believe that this setting is harmful and should be removed.
![default](https://user-images.githubusercontent.com/4980243/48626942-4d078380-e9c4-11e8-9c93-afa02d65895b.png)
Second - "filters". This is a logical location that can be saved.
![default](https://user-images.githubusercontent.com/4980243/48626969-5db7f980-e9c4-11e8-9321-4e9f67a69cd4.png)
Additionally, the issue can be fixed by replacing the current state of "two independent settings" with "two places to access the same setting".

This will be even more logical, because the setting in the main menu is saved, unlike the filter.

**Comment by D3nnis3n** [comment]
Funnily, just talked about this with John yesterday.

**Comment by elfl0rd** [comment]
A great indicator that it works really strange...
