### ISSUE TITLE
Layers in servers menu

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10045]
After "connection failed" main screen visible trough servers.
https://youtu.be/mdJcbF8U-uM

**Comment by BlazeGuy2** [comment]
@elfl0rd Which version is this occurring on?

**Comment by elfl0rd** [comment]
release 0.7.8.2

**Comment by Spydarlee** [comment]
This will be fixed by a related change (https://github.com/StrangeLoopGames/Eco/pull/3614) as soon as that's pulled across!

**Comment by elfl0rd** [comment]
nice
