### ISSUE TITLE
Give Players a hint that cactus are a tree

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10041]
In the tutorial you should mention that.

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/48659180-4af20300-ea5e-11e8-995f-617e92310a0f.png)
he who has eyes will see

**Comment by D3nnis3n** [comment]
Yeh, but will a new player as first thing he does move over a tooltip to find where an item is harvested from when he is just told to cut a tree, sitting in desert? I assume: No.

**Comment by elfl0rd** [comment]
Then it is worth solving a deeper problem by adding training in the use of hints.
Because laying the straw in every particular case is not a good solution.

**Comment by WeaselDog** [comment]
Saguaro was moved to tree in Ecopedia and it has a unique log type now.

**Comment by D3nnis3n** [comment]
Thanks for getting that old one out of the way.
