### ISSUE TITLE
USER ISSUE: Raum wird nicht als T2 erkannt und bleibt bei T1,6

### ISSUE THREAD

**Issue by Cycrashy** [StrangeLoopGames/EcoIssues#10040]
**Version:** 0.7.8.2 beta

**Steps to Reproduce:**
Großen keller bauen mit T2 Materialien (Bricks wände, und Bauholz Boden) und eine wand mit Stahlbeton T3

**Expected behavior:**
Raum Wird Als T2 Erkannt bzw über T2 wenn dann noch T3 Materialien dazu kommen (Stahlbeton)

**Actual behavior:**
Raum ist bei T1,6 und es verändert sich nichts.
Erst wenn ich 3 Blöcke in die decke mache 
und so den eingan verbaue ändert sich der Raum auf T1,81
Wenn ich nun eine Wand mit Stahlbeton T3 ersetze bleibt alles bei dem selben wert...
 verb verbaueeeen
**Do you have mods installed? Does issue happen when no mods are installed?:**
Raum ist bei T1,6 und es verändert sich nichts.
Erst wenn ich 3 Blöcke in die decke mache 
und so den eingan verbaue ändert sich der Raum auf T1,81
Wenn ich nun eine Wand mit Stahlbeton T3 ersetze bleibt alles bei dem selben wert...
 verb verbaueeee

**Comment by Cycrashy** [comment]
Version: 0.7.8.2 beta

Steps to Reproduce:
Large cellar build with T2 materials (brick walls, and timber floor) and a wall with reinforced concrete T3

Expected behavior:
Space is recognized as T2 or T2 if then still T3 materials are added (reinforced concrete)

Actual behavior:
Space is at T1.6 and nothing changes.
Only when I make 3 blocks in the ceiling
and so the eingan build the space changes to T1,81
If I now replace a wall with reinforced concrete T3 everything remains at the same value ...
verb buildeeen
Do you have mods installed? Does issue happen when no mods are installed ?:
Space is at T1.6 and nothing changes.
Only when I make 3 blocks in the ceiling
and so the eingan build the space changes to T1,81
If I now replace a wall with reinforced concrete T3 everything remains at the same value ...

**Comment by Cycrashy** [comment]
![20181116144306_1](https://user-images.githubusercontent.com/45098209/48624957-1fafdb00-e9ae-11e8-9968-24253c52c3ec.jpg)
![20181116144313_1](https://user-images.githubusercontent.com/45098209/48624958-1fafdb00-e9ae-11e8-89e0-890b5d18703f.jpg)
![20181116144321_1](https://user-images.githubusercontent.com/45098209/48624959-1fafdb00-e9ae-11e8-829b-68f204656f0d.jpg)
![20181116144342_1](https://user-images.githubusercontent.com/45098209/48624960-1fafdb00-e9ae-11e8-8831-109c3b51821d.jpg)
![20181116144350_1](https://user-images.githubusercontent.com/45098209/48624961-20487180-e9ae-11e8-99c1-c1c18f8d8efb.jpg)

**Comment by elfl0rd** [comment]
Borders counted in room too, you use tier 1 in borders, as result your room NOT from only tier 2 or above.

**Comment by Cycrashy** [comment]
ah okay thanks

**Comment by elfl0rd** [comment]
in addition, there are several errors associated with the borders...
https://github.com/StrangeLoopGames/EcoIssues/issues/9637
https://github.com/StrangeLoopGames/EcoIssues/issues/9636

**Comment by Cycrashy** [comment]
why can it be that my house is not recognized as a house?

**Comment by elfl0rd** [comment]
Holes in roof, or holes more than 2 block in walls?

**Comment by D3nnis3n** [comment]
Working as intended.
