### ISSUE TITLE
USER ISSUE: Wheelbarrow untrustworthy steering

### ISSUE THREAD

**Issue by NaNoXiDo** [StrangeLoopGames/EcoIssues#10051]
**Version:** 0.7.8.2 beta

**Steps to Reproduce:**
You need a Wheelbarrow and steer it.

**Expected behavior:**
When I "drive" forward it should drive forward.

**Actual behavior:**
It have a really untrustworthy steering/handling.
When I "drive" forward, it didn't work really.
I still dont understand the handling after trying to use it sometimes.
**Do you have mods installed? Does issue happen when no mods are installed?:**
It have a really untrustworthy steering/handling.
When I "drive" forward, it didn't work really.

**Comment by D3nnis3n** [comment]
Could you make a video? I cannot reproduce this, the wheelbarrow is very slow, but drives as expected.

**Comment by NaNoXiDo** [comment]
In Both Videos I only hold the "W"-Button!
#1: https://youtu.be/voNlSmniiqQ
#2: https://youtu.be/d9ULAOx80cM

**Comment by D3nnis3n** [comment]
Merged with: https://github.com/StrangeLoopGames/EcoIssues/issues/10051
