### ISSUE TITLE
Population Map Plant Name Missing

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10055]
Version: 7.8.3

The environment data tap of the map is missing the name of the plants on all population entries.

![image](https://user-images.githubusercontent.com/2676134/48660145-13cf2200-ea5d-11e8-8ebb-c88eeeb84d43.png)

**Comment by D3nnis3n** [comment]
Cannot reproduce. Anything special you did?

**Comment by Deantwo** [comment]
My Steam is set to English and so I think Eco just uses that.

I don't believe I did anything special, it just seems to be like this.

If you tell where to look I can get more information.

**Comment by D3nnis3n** [comment]
Server also running on english language?

**Comment by Deantwo** [comment]
I would assume so. But don't know how I would know for sure.

**Comment by D3nnis3n** [comment]
Items are named with their english name?

**Comment by SeanAtr0n** [comment]
This is happening for me in the master branch as well

**Comment by D3nnis3n** [comment]
Well, then assign someone looking into it. On 7.8.3 this does not occur for me and i cannot get it to occur.

**Comment by Deantwo** [comment]
Maybe it is some corrupt game files? Anything I should try to copy/upload or reinstall?
