### ISSUE TITLE
Server wont run

### ISSUE THREAD

**Issue by cyrus1087** [StrangeLoopGames/EcoIssues#10052]
Hey guys, this shows up every time i try to run my singleplayer game

Connection Failed

Log File:
Initialize engine version: 2018.2.15f1 (65e0713a5949)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 760 (ID=0x1187)
    Vendor:   
    VRAM:     1955 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.107 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.458860 ms
Client version: 0.7.8.3 beta
Friday, November 16, 2018 2:02 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

LocalServer -  Eco Server 0.7.8.3 beta
LocalServer -  Server Initialization... 
LocalServer -  Starting LocalizationPlugin... 
LocalServer -  Error when loading Mod string tables:
LocalServer - Exception: IOException
LocalServer - Message:The file or directory is corrupted and unreadable.
LocalServer - 
LocalServer - Source:mscorlib
LocalServer - 
LocalServer - System.IO.IOException: The file or directory is corrupted and unreadable.
LocalServer - 
LocalServer -    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
LocalServer -    at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
LocalServer -    at System.IO.FileSystemEnumerableIterator`1.MoveNext()
LocalServer -    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
LocalServer -    at System.IO.Directory.GetDirectories(String path, String searchPattern, SearchOption searchOption)
LocalServer -  Starting ModKitPlugin... 
LocalServer -  Loading mods... 
LocalServer -  Loading mods finished in 96.0ms
LocalServer -  Server Initialization finished in 8,619.1ms
Connecting to local host.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Connection complete.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by elfl0rd** [comment]
Hello! Try to fully reinstall game, with deleting it's folder.

**Comment by beastyn** [comment]
Please reopen if issue is actual for 0.8.1.0
