### ISSUE TITLE
Vertical ladders orientation bug

### ISSUE THREAD

**Issue by disfated** [StrangeLoopGames/EcoIssues#10059]
New vertical ladder (made of Hewn Logs) in some cases change its orientation right after being set up.
Video demostration
https://monosnap.com/file/Yli8jRqN701PHfUFMHUGBYrAIaQXt6
Eco 0.7.8.3

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9292
