### ISSUE TITLE
Demografic improvement

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10058]
Please add more info about it.

In "demografic description" - list of users.
![default](https://user-images.githubusercontent.com/4980243/48661217-a8e31280-ea7f-11e8-9566-cd6cb0049841.png)
In "user description" - list of applied demografics.
![default](https://user-images.githubusercontent.com/4980243/48661227-c6b07780-ea7f-11e8-9a61-f5eccb1972c9.png)

Additionally, you can add windowed interface, like economy viewer with scrolling and searching.

Thx!

**Comment by TemporalWolf** [comment]
This. Currently demographics are ham-stringed because the only info I have is whether I personally am in each demographic.

**Comment by Deantwo** [comment]
Would be nice if demographics also created tooltip links, so we can reference them in chat and see who is in them.

**Comment by msgerbs** [comment]
Would also be great if there was a list of demographics on the Laws page on the website. Once passed, they just vanish.

**Comment by johnkslg** [comment]
I will fix this with 9.0 update

**Comment by Deantwo** [comment]
This I know isn't fixed yet.
