### ISSUE TITLE
Excavator wheels swamp into surface near walls

### ISSUE THREAD

**Issue by disfated** [StrangeLoopGames/EcoIssues#10061]
It's an old bug. Just drive close to wall and wheels will fall through the floor.
![2018-11-17 22 29 13](https://user-images.githubusercontent.com/430542/48664074-f892ff80-eaba-11e8-821f-852cafe37226.png)

**Comment by disfated** [comment]
Here we go
![2019-01-05 08 36 20](https://user-images.githubusercontent.com/430542/50719905-31b41d00-10c5-11e9-8a36-9809ce06e83d.jpg)

**Comment by TwixterZ** [comment]
no longer fall thru the floor as of 0.9.3 
![image](https://user-images.githubusercontent.com/78054747/110120174-a72bed00-7df7-11eb-8eb1-71714a344bb1.png)
