### ISSUE TITLE
Pickup from stockpiles improvement

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10064]
I want more improvements, as part of @Quadbro inventory management.

If you (LMB) (Take) from stockpile with tool in hand, grab first _suitable_, not first _available_.

e.g.
In your hand - Shovel.
First suitable block in stockpile - dirt.
If you take from stockpile - you get dirt.
![default](https://user-images.githubusercontent.com/4980243/48672774-53743780-eb4b-11e8-8ee2-fab09c60f993.png)
not like now - hewn logs, and as a result, the tool will change to a hammer

e.g.
In your hand - Hammer.
First suitable block in stockpile - hewn logs.
If you take from stockpile - you get hewn logs.
![default](https://user-images.githubusercontent.com/4980243/48672817-c2ea2700-eb4b-11e8-97ae-232dcd02320c.png)
not like now - dirt, and as a result, the tool will change to a shovel.

**Comment by Deantwo** [comment]
Also using a hammer on a stockpile when it is almost empty seem to pickup the stockpile more often than it should.

**Comment by elfl0rd** [comment]
Axe prefer logs, pickaxe prefer ores and stones :)
If no one suitable blocks - grab first.
in addition, it may be useful to add a modifier (for example, shift) disabling filter. (With the button pressed will be the current behavior).

**Comment by Quadbro** [comment]
> Also using a hammer on a stockpile when it is almost empty seem to pickup the stockpile more often than it should.

Fixed that too, by adding modifier system (now can interact with "alt, shift, ctrl" to  provide more usability) So by default storage wont be removed, on last items transfer...

**Comment by D3nnis3n** [comment]
Implemented.

**Comment by Deantwo** [comment]
Well mostly at least. A hammer can't be used to take construction materials out of a stockpile, you just get the message that the stockpile has to be empty before you can pick it up.

**Comment by beastyn** [comment]
@Quadbro 
Mike, look at this one more time, pleae
[0.8.2 -staging 3]
I am taking Brick with axe even if I have logs and hewn logs in the stockpile

![bandicam 2019-05-06 16-29-42-315](https://user-images.githubusercontent.com/27898520/57222499-47f2cb00-701c-11e9-90bd-cc263b4dc81e.jpg)
![bandicam 2019-05-06 16-30-06-783](https://user-images.githubusercontent.com/27898520/57222501-488b6180-701c-11e9-8177-e1b8ea90389a.jpg)
