### ISSUE TITLE
Road Tool Destroys Trees

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10069]
Version: 7.8.3

I used the road tool on a middle aged (not a sprout but not yet mature) tree's dirt block and the tree vanished.

**Comment by Quadbro** [comment]
Oh, it was in 7.6 too, nice bug :D

**Comment by Deantwo** [comment]
A "the roots are too strong" error would likely be a good idea in this situation.

**Comment by elfl0rd** [comment]
Bump :D

**Comment by DurtyFree** [comment]
Duplicate
https://github.com/StrangeLoopGames/EcoIssues/issues/10550

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10550
