### ISSUE TITLE
USER ISSUE: Error Logging on to active servers

### ISSUE THREAD

**Issue by OhNo2** [StrangeLoopGames/EcoIssues#10067]
**Version:** 0.7.8.3 beta

**Steps to Reproduce:**
Try to log into a server	

**Expected behavior:**
connect to server, which is in your house, that you know is running, that you were on yesterday.

This also happened on all of the other favorited servers that i tried to log onto

**Actual behavior:**
The following error message popped up:
Failed to connect, connection timed out
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Failed to connect, connection timed out

I do have mods, but only on my server. the same error occurred on two mod-free servers as well

**Comment by mirasrael** [comment]
@OhNo2 Can you check if you still having this issue?
