### ISSUE TITLE
Server can get stuck - Joining gives "Loading World" forever

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10065]
I really don't know how to reproduce as ECO gives me zero information (Nothing in Dump or Console, Server doesn't crash, runs fine for a small amount of players) on this, but up to now we every day had an issue (which we didn't in any version before) that causes most (but not all!) players to get disconnected from the server and no longer be able to rejoin as of "permanent loading world". A restart fixes that. Unfortunatley, even i cannot be online 24/7 and so this caused a downtime of 4 hours today - very bad.

**Comment by elfl0rd** [comment]
Confirmed on multiple servers

**Comment by D3nnis3n** [comment]
Thank god other people have that too, maybe we can work together to find the reason why this happens?

**Comment by elfl0rd** [comment]
I can't even imagine, everything can work fine for a long time and then break.

**Comment by D3nnis3n** [comment]
We never had that occuring before 7.8, tbh. But now we got it 5x a day. It makes the game pretty unplayable.

**Comment by elfl0rd** [comment]
It seems that this problem existed, but met extremely rarely. Now Yes, at least once in 2 days but it will happen.

**Comment by D3nnis3n** [comment]
https://drive.google.com/file/d/1t2A3zjElehw2cv9x2vqMVORqn7clI3mI/view

Process Dump.

**Comment by mirasrael** [comment]
Can please every user who will have this issue make following:
1. Open a Task Manager  (ctrl-alt-del, ProcessManager)
2. Find an Exo executable (expand if necessary):
![image](https://user-images.githubusercontent.com/475445/48832762-fa92e200-ed8a-11e8-98cb-3c2f043aa48e.png)
3. Take a dump (right click on process, Create Dump File)
https://assist.biztalk360.com/support/solutions/articles/1000199668-how-to-take-memory-dump-of-a-running-process-with-windows-task-manager-
4. Attach .dmp to this issue

**Comment by D3nnis3n** [comment]
Do you mean if players tried to connect to the server while it was in this deadlock? That probably is a yes, considering the amount of our Players.

**Comment by D3nnis3n** [comment]
This has been fixed with the change mentioned above.
