### ISSUE TITLE
Missing green color on good match

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10074]
![default](https://user-images.githubusercontent.com/4980243/48736253-d71d4980-ec5b-11e8-8806-c5a38c9f526d.png)

**Comment by Quadbro** [comment]
Oh, style sheet is broken again, really?))

**Comment by elfl0rd** [comment]
Unfortunately I still cannot compile and run the master branch, it is possible that this has already been fixed :)

**Comment by D3nnis3n** [comment]
@Quadbro 
The fix for the green color in nutrition changes never managed it to get in the hotfixes, despite you have fixed it. So either it was not (correctly / completely) merged or it did not work.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9995

**Comment by Quadbro** [comment]
I'll push fixed stylesheet soon
