### ISSUE TITLE
USER ISSUE: issue with picking up crafted item(like fishery)

### ISSUE THREAD

**Issue by x-kaliber** [StrangeLoopGames/EcoIssues#10077]
**Version:** 0.7.8.3 beta

**Steps to Reproduce:**
Have the hammer out.
try to pick up  a crafted item you deployed.

**Expected behavior:**
I should be able to pick up items and have them in my inventory.

**Actual behavior:**
the item vanishes. As it has been destroyed.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
the item vanishes. As it has been destroyed.

**Comment by Deantwo** [comment]
Does this happen only to the **Fishery**? Or does it happen to all world objects you use a hammer on?

I am perfectly able to hammer furniture and other world objects, but I have not tried a **Fishery** specifically.

**Comment by x-kaliber** [comment]
To me it happened in fishery. Actually I will delete the currnlent world
and I will try again. To see if I can replicate it . In a different world.
Or it might have been a bug during the world construction.

**Comment by D3nnis3n** [comment]
Cannot reproduce this issue, please report back when you found a reproducable case.

**Comment by elfl0rd** [comment]
No answer for a long time, if you still have this issue and have additional info (logs, vodeo, etc) please open new issue.
