### ISSUE TITLE
[QoL] Prevent plants(w\o seeds) from accidental eating

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10076]
In current state, if you accidentally hover over an already planted plant and try to plant - you eat it.
it's terribe...
![20181120094403_1](https://user-images.githubusercontent.com/4980243/48756599-da8bf180-ecaa-11e8-80f1-6d414b84cb86.jpg)

**Comment by Deantwo** [comment]
I believe you can eat seeds too, so bad for those too.

Maybe "right-click to eat selected" is bad for all seed/plantable things. But then we get inconsistency between how to eat food items, so maybe the whole "right-click to eat selected" is just a bad idea in general.

The only reason we have "right-click to eat selected" is because that is how you eat in Minecraft, maybe just get rid of it. I don't believe we have any other items that you use on yourself by right-clicking with them selected.

**Comment by elfl0rd** [comment]
as I see, you don't eat seeds when you look at a plant.

**Comment by Deantwo** [comment]
Being about to "right-click to eat selected" also create confusion when carrying "carry items" or when right-clicking a storage to place the selected item into it.

**Comment by elfl0rd** [comment]
but how do you propose to eat? If you remove the eating from the plants on the right mouse button, it will make it impossible to start the game.

**Comment by elfl0rd** [comment]
However, fast eating without turning cursor on is quite convenient.
I think to start is to disable eating if the cursor is induced at something and see the result.

**Comment by Nicolausi113** [comment]
What about this: whenever an eatable food is selected in the hot-bar, the background of nutrition window is highlighted, meaning you can eat one peace of the selected object by left-click in nutrition window? A total new procedure, I know, but could bring back consistency with right-click.

**Comment by elfl0rd** [comment]
However, you will need to release the mouse cursor, hover mouse cursor to it and click. It's harder and less obvious than eating with a right click directly from a Hotbar.

**Comment by TemporalWolf** [comment]
Making it a long click (half a second maybe?) to eat would fix the problem... and even then gives an opportunity for an eating animation... if you don't hold it long enough, you don't it eat.

**Comment by elfl0rd** [comment]
> Making it a long click (half a second maybe?) to eat would fix the problem... and even then gives an opportunity for an eating animation... if you don't hold it long enough, you don't it eat.
Excellent idea!
You hold rmb, character (animation) grab food, brings to mouth and bites.
If you release rmb before bites - eating stops.

**Comment by Quadbro** [comment]
Sounds like a new QoL tweak?) ^_^

**Comment by elfl0rd** [comment]
This more QoL than issue as I believe :)

**Comment by Quadbro** [comment]
and it's harder, because now (if i'm right) there are no "hold button for X sec to do smth" mechanics in eco... Correct me if i'm wrong
