### ISSUE TITLE
Hosted World - Main menu in game, to join hosted world, image display bug

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#10070]
![image](https://user-images.githubusercontent.com/7343272/48690256-a2898f00-eb82-11e8-9af3-1f2d3f115a8d.png)

If world name is very long, The world icon might become very large.

**Comment by SlayksWood** [comment]
@gzatravkin I can't check for actualing. Ask @rainfarmer if you have any questions.
