### ISSUE TITLE
USER ISSUE: Waterfall bug

### ISSUE THREAD

**Issue by x-kaliber** [StrangeLoopGames/EcoIssues#10071]
**Version:** 0.7.8.3 beta

**Steps to Reproduce:**
1. create a waterway under a waterfall in order to manipulate the waterpath

**Expected behavior:**
expecting the water to follow the waterway i created.

**Actual behavior:**
it shows the water falling in the waterway. but it does not follow the waterway. it gives a a splash effect. but it stops there.

**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9971
#8514
