### ISSUE TITLE
Eco Forum Unsecure Login.

### ISSUE THREAD

**Issue by arcreigh** [StrangeLoopGames/EcoIssues#10081]
The official eco forum (http://ecoforum.strangeloopgames.com) uses insecure http for logging into the forum, Anyone who would be logging into the forum would be sending their username and password combination in cleartext over the internet allowing anyone sniffing traffic to steal an admin password for the forum. You can get a FREE SSL cert through lets encrypt.

**Comment by mirasrael** [comment]
Now it is https.
