### ISSUE TITLE
USER ISSUE: Butcher table Bug 

### ISSUE THREAD

**Issue by amokhase** [StrangeLoopGames/EcoIssues#10083]
**Version:** 0.7.8.3 beta

**Steps to Reproduce:**
each time if i start meat production table stop on about 67% and say not enough meat or corpse but thats wrong the table just lost them 

**Expected behavior:**

**Actual behavior:**
n
**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by D3nnis3n** [comment]
Could you probably provide a video or more description? I cannot reproduce this.

**Comment by D3nnis3n** [comment]
Closed because of no answer in two weeks.
