### ISSUE TITLE
USER ISSUE: Continue button on main menu does not connect

### ISSUE THREAD

**Issue by ThisFlynn** [StrangeLoopGames/EcoIssues#10086]
**Version:** 0.7.8.4 beta

**Steps to Reproduce:**
Application newly opened.
Correct server listed under "Continue"
Pressing button starts "Connecting..." window with wheel

Server accessible by directly entering IP 
no mods are installed
**Expected behavior:**
Connected to active server

**Actual behavior:**
The following error message popped up:
````
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by mirasrael** [comment]
Hi @ThisFlynn 
Can you check if you still having this issue? (Master server was updated)

**Comment by ThisFlynn** [comment]
Checked.
Issue persists.
Tried something different and entered the numeric server address - no change in results.

**Comment by mirasrael** [comment]
@ThisFlynn pleas try now

**Comment by mirasrael** [comment]
And can you give your server name?

**Comment by ThisFlynn** [comment]
BSG-GAMESERVER-
though it's not listed publicly if that makes a difference.

I just attempted to recreate the issue and did not get the same error.
Connected through "Continue" button without issue.
The difference from my attempt earlier this morning may be that I'm now on
the same LAN as the server.
I'll see if I can get one of the other players to try from their locations.
Not sure if anything else has changed.

**Comment by ThisFlynn** [comment]
Confirmed with remote players!

Thanks for YOUR help!!
Really impressed with how responsive you've been

**Comment by arcreigh** [comment]
This issue was related to #10080 and I can confirm that everything is working.
