### ISSUE TITLE
USER ISSUE: Grafik Bugs

### ISSUE THREAD

**Issue by kuxii2016** [StrangeLoopGames/EcoIssues#10082]
![hgfdhgf](https://user-images.githubusercontent.com/21268770/48798147-4189c480-ed04-11e8-8e04-753db3467aef.PNG)
![fsfsd](https://user-images.githubusercontent.com/21268770/48798155-4484b500-ed04-11e8-94a7-16ddc0c39f8e.PNG)
![20181120193516_1](https://user-images.githubusercontent.com/21268770/48798197-62521a00-ed04-11e8-906e-112bfd8fe6d2.jpg)
![20181120193523_1](https://user-images.githubusercontent.com/21268770/48798198-62521a00-ed04-11e8-881a-40eb253a2f75.jpg)
![20181120193544_1](https://user-images.githubusercontent.com/21268770/48798199-62521a00-ed04-11e8-8262-db0b14c25f07.jpg)
![20181120193253_1](https://user-images.githubusercontent.com/21268770/48798200-62eab080-ed04-11e8-861c-54627e55ab97.jpg)
![20181120193324_1](https://user-images.githubusercontent.com/21268770/48798201-62eab080-ed04-11e8-828c-04ba177a6198.jpg)
![20181120193445_1](https://user-images.githubusercontent.com/21268770/48798202-62eab080-ed04-11e8-911f-23f9af5778a1.jpg)

**Version:** 0.7.8.3 beta

**Steps to Reproduce:**
Single/Dual GPU tested, Other Driver

**Expected behavior:**
Nicht Spielbar wegen Extremen Grafikfehlern

**Actual behavior:**
Streifen Pixel im Spiel (Nur unter Windows/Linux nicht)n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Streifen Pixel im Spiel (Nur unter Windows/Linux nicht)

**Comment by D3nnis3n** [comment]
Which Graphics Card? Which driver version? Operating System? .NET? DirectX?

**Comment by kuxii2016** [comment]
0.7.8.5 same Problem

**Comment by kuxii2016** [comment]
nothing changed?!

**Comment by elfl0rd** [comment]
> DX12

But your card support 11.2...

> .net is 4.0

But Eco require >4.7...

You are one with this problem, i think this is something within your configuration.
Developers cannot fix issue without reproduction.
But wait, developers answers after holidays.

**Comment by kuxii2016** [comment]
I use Win7 and Have the Fucking Grafik Bugs.!! WIN 7 have only DX11.
I kann play this Game Under Linux whit no Grafik Bugs?! Uh Why???
![screenshot_2](https://user-images.githubusercontent.com/21268770/50577874-1da4bd00-0e32-11e9-9dc4-c39750c1a3a3.png)

**Comment by D3nnis3n** [comment]
Added video from the duplicate issue.

This most probably is a local problem with hard or software.

**Comment by kuxii2016** [comment]
Read the Steam Reviews.... More Users have Problems with the Grafik....

**Comment by kuxii2016** [comment]
![screenshot_1](https://user-images.githubusercontent.com/21268770/51084104-0795d700-1725-11e9-8a49-71271bde6bf1.png)

With the source access I could test now, The problem occurs as soon as GPU skinning is activated
And no i have the MSI version from the GPU and the bios is up to Date

**Comment by redwyre** [comment]
@kuxii2016 Is this still breaking for you in the latest 0.8.2 builds?

**Comment by D3nnis3n** [comment]
Can no longer contact the op who got refunded, closing for now. Feel free to reopen if this ever reoccurs.

**Comment by kuxii2016** [comment]
I can test it, When my Friend the Account daten from he shared, but not today the next days evtl.

**Comment by D3nnis3n** [comment]
Feel free to post your results.
