### ISSUE TITLE
Suggestion - Meteor fallout?

### ISSUE THREAD

**Issue by Ketrai** [StrangeLoopGames/EcoIssues#10099]
How about a 5 day fallout after the meteor hits? I'm hoping this isn't too difficult to implement. Just turn the sky colour to grey, and set all plants to no grow/recieve sunlight. So they all die within hours. Players can rebuild, but only if they kept seeds.

**Comment by elfl0rd** [comment]
Keep in mind, SLG have special section to suggestions :)
https://github.com/StrangeLoopGames/EcoSuggestions/issues

**Comment by Deantwo** [comment]
On that note, doesn't this already happen? In the form of a lot of air pollution and many smaller meteorites falling.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#633
