### ISSUE TITLE
Balance - Building materials

### ISSUE THREAD

**Issue by Ketrai** [StrangeLoopGames/EcoIssues#10093]
Currently the cost of certain building materials is exorbitantly high. The amount of effort one has to put in to construct a house is quite awful.

Instead I'd rather suggest buildings to facilitate new tiers of progression should be acquired differently. Similarly to how a crafting table always charges the full price to make logs into hewn wood, but how the carpenter table makes it more cheaply. Hence I suggest some kind of prototype machine for each station that can produce the material for the next stage. These still need the lower tier as they do currently, but always produce a material at a higher cost. (Whilst still being affected by professions, unlike the crafting table... to avoid wastage and more profession dumping)

Once the first building of a higher tier has been constructed, you can put in a non-prototype station, or simply... the prototype automatically gets upgraded into a fully functioning station. Where you can produce construction materials at a low cost, especially even very low with proper professions. This way people who love to build can easily get the materials en masse they desire for large projects without having to completely rely on the community to deliver them boatloads and boatloads of materials for just a single three story building. The skyscrapers and such look really nice on the splash arts in the game, but are actually quite unfeasible with the cost for building.

Especially higher tier materials should be easily achieved. Lumber easier than hewn logs. Where one simply requires a sawmill and some treating, with the other requiring someone to manually remove the bark from every log and cleaning them.

Bricks were designed in use to be easily amassed with the simple ingredient of clay, and oven, and workers to haul them. It should be easier than carefully chopping rocks into small pieces, producing much more mortar to fill in the irregular gaps between rocks. 

etc, etc

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#634
