### ISSUE TITLE
Staging: rolled "opening eyes" animation

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10091]
Before (correct)
![20181119162733_1](https://user-images.githubusercontent.com/4980243/48828469-d0d4bd80-ed80-11e8-8111-4dee42045096.jpg)

In staging
![20181119124913_1](https://user-images.githubusercontent.com/4980243/48828481-daf6bc00-ed80-11e8-894f-6244d548a9c7.jpg)

**Comment by Quadbro** [comment]
Hah, it looks like "abstract" open eye character is using new sleep system, and he is in bed, while you openning your game :D

**Comment by mirasrael** [comment]
@Quadbro please fix in staging

**Comment by Quadbro** [comment]
The issue is animation related (looks like Aperture scale it stretching along wrong axis, from some frames)

**Comment by elfl0rd** [comment]
@Quadbro @D3nnis3n now happens on release, lol

**Comment by seccombew** [comment]
Already fixed in master.
