### ISSUE TITLE
[QoL] prevent "reap" already mowed grass.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10092]
![20181121105838_1](https://user-images.githubusercontent.com/4980243/48829293-067aa600-ed83-11e8-83a9-32dc72d767d2.jpg)
In addition, to simplify the mowing, it would be nice to remove the selection from the already mowed grass.

**Comment by Quadbro** [comment]
But selection will be restored, when you'll try to move, or you are talking about "Do not highlight reaped glass at all"?)

**Comment by elfl0rd** [comment]
yep, like it's work with not growth plants.
