### ISSUE TITLE
Make the economy viewer observe permissions

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10098]
The economy viewer lists private stores that players can't use as they are not authorized. So does the information in tooltips. Either show that a store cannot be used by you or hide them if you got no permission on them. Showing the missing permission is probably the best way, considering you could still ask if you can get permission.

No information just get's people to drive there once again without any use and being frustrated afterwards.

**Comment by Deantwo** [comment]
Been noticing this on my server too.

I made a "Free Skill Scrolls" store that is only accessible to the Citizen demographic, but it seem to show up for everyone anyway.

**Comment by Quadbro** [comment]
Yeah, nice thing!

**Comment by Deantwo** [comment]
Could make some options on the page, to make the list show either: all, public, or accessible to me.

**Comment by elfl0rd** [comment]
(fixed)
![48993061-1e30a080-f16e-11e8-90e9-dbbd699975f3](https://user-images.githubusercontent.com/4980243/51071566-19fc0c00-1664-11e9-8918-beb52cfef04d.png)

**Comment by Deantwo** [comment]
Fun little follow up to this. Ehat if a law is preventing me from trading a a store? Much harder to detect, but if possible it would be nice.

**Comment by D3nnis3n** [comment]
Yeh, that probably would be something for suggestions.
