### ISSUE TITLE
Scything shrubs to root out not possible if not mature !?

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#10095]
Version: v0.7.8.3-beta

This functionality was meant to prevent harvesting/destroying farming-plants and get out no yield.
Using a scythe should be different considered, other reasons then yield may be intended and most farming-plants doesn’t trigger the scythe-action (reap).

![scythe2](https://user-images.githubusercontent.com/38510829/48847411-c4149180-eda1-11e8-8e25-abb692a16dbc.jpg)

**Comment by elfl0rd** [comment]
@D3nnis3n this is issue.
You not able to remove nonharvestable plant

**Comment by D3nnis3n** [comment]
Mh, until now i removed plants by digging them.

**Comment by Nicolausi113** [comment]
Proposal for a solution of this problem:
instead of preventing player-actions and leave them perplexed, we should give information about the object, to estimate the result of an action and what will be earned.
A little color bar in the interaction-hint for all plants and trees showing the state of maturity can do this: green 100%, yellow <100%, red <50% (can be more elaborated).

Also the notifications following each action is more disruptive then useful, that much information can not be processed. I normally look in the slots in hotbar and backpack for the result, since the notifications are fading out anyway.
