### ISSUE TITLE
Master: exception when generating new world.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10097]
![default](https://user-images.githubusercontent.com/4980243/48851819-06979780-edbd-11e8-833b-587fc09f01e2.png)

**Comment by BlazeGuy2** [comment]
Is this just happening on world gen?  Not when loading a save?

**Comment by elfl0rd** [comment]
I can't load the save because I don't have it :D

**Comment by elfl0rd** [comment]
Yes, launching+converting old save works fine
![default](https://user-images.githubusercontent.com/4980243/48864997-3eafd200-eddf-11e8-9fc2-1d99a98274de.png)

**Comment by mirasrael** [comment]
Result of bad merge...

**Comment by elfl0rd** [comment]
Fixed as i see.
