### ISSUE TITLE
Hosted worlds: server name silently not accert non-english character.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10106]
Non-english letters can be entered, but hit "ok" mark does nothing.
![default](https://user-images.githubusercontent.com/4980243/48899652-37310d00-ee61-11e8-97fc-c9a1c9de0b2d.png)

(It works before master broken)

**Comment by Tigran07** [comment]
https://github.com/StrangeLoopGames/Eco-Accounts/pull/69
