### ISSUE TITLE
Master: saving not work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10107]
![default](https://user-images.githubusercontent.com/4980243/48901044-3b5f2980-ee65-11e8-87dd-14d893be1748.png)
And no "newline" after fail message, it's make console output ugly.

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/48918686-551d6280-ee9f-11e8-927a-ac81dd3464d8.png)

**Comment by mirasrael** [comment]
Do you still have this issue on latest version?
