### ISSUE TITLE
Hosted worlds: if server name too long it cut, and "edit" icon is not visible.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10105]
Short name - all ok
![default](https://user-images.githubusercontent.com/4980243/48899514-dd304780-ee60-11e8-8679-dd08bfbd3cc9.png)

Long name - name cut, and "edit" icon is hidden.
![default](https://user-images.githubusercontent.com/4980243/48899549-f33e0800-ee60-11e8-8dd3-aa8b2abd4017.png)
![default](https://user-images.githubusercontent.com/4980243/48899575-04871480-ee61-11e8-8b7b-e89e0ba007f6.png)
(red mark - edit icon)

**Comment by Tigran07** [comment]
Pull Request is here
https://github.com/StrangeLoopGames/Eco-Accounts/pull/70
