### ISSUE TITLE
Art - Boockshelf and shelf cabinet have litle confusing icons

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10100]
Bookshelf on icon empty, but placed model contain books.
(and icon - 3 shelf, model 4)
![default](https://user-images.githubusercontent.com/4980243/48860896-3487d680-edd3-11e8-8f1a-2e48d2169504.png)

shelf cabinet on icon contain only two shelf, but model have shelfes and cabinet.
![default](https://user-images.githubusercontent.com/4980243/48860779-f38fc200-edd2-11e8-9a39-58fed14ad7e9.png)

I like the idea where the bookshelf will have two versions, with and without books (ofc, no books = no paper in recipe).

**Comment by elfl0rd** [comment]
For me, the more significant difference is bookshelf.
shelf cabinet is quite low issue.

**Comment by D3nnis3n** [comment]
To be honest i don't see this as issue at all, but would have the idea to change the art of those two when you put something in its storage, e.g. it only shows books on its model / textrue when some are in the storage.
