### ISSUE TITLE
Sleep overlay issue

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10102]
1) server w\o fastforward
2) launch manually /fastforward 1
3) go to bed, try sleep
Now... sleeping overlay with fixed and incorrect numbers. (Can be hidden by pressing esc, then tab)
![20181122000046_1](https://user-images.githubusercontent.com/4980243/48868184-ce5a7e00-ede9-11e8-957f-45c4097680c9.jpg)
![20181122000049_1](https://user-images.githubusercontent.com/4980243/48868190-d0244180-ede9-11e8-8599-11d646b8d437.jpg)

**Comment by D3nnis3n** [comment]
Nice find!

**Comment by SlayksWood** [comment]
0.8.1.0 staging-7.
Real-time passed: 
It should be:                            It really is:
10 minutes                              10 minutes
25 minutes                              25 minutes
50 minutes                              50 minutes
1 hours 25 minutes                 1 hours 25 minutes
When the time becomes 1 hour 30 minutes it starts to display incorrectly
It should be:                            It really is:
1 hours 30 minutes                 2 hours 30 minutes
1 hours 55 minutes                 2 hours 55 minutes
2 hours 08 minutes                 2 hours 08 minutes
2 hours 22 minutes                 2 hours 22 minutes
2 hours 38 minutes                 3 hours 38 minutes
2 hours 44 minutes                 3 hours 44 minutes
3 hours 29 minutes                 3 hours 29 minutes
3 hours 30 minutes                 4 hours 30 minutes
etc...

**Comment by SlayksWood** [comment]
move to #12031
