### ISSUE TITLE
USER ISSUE: Mint bug

### ISSUE THREAD

**Issue by Alexandre-Frei** [StrangeLoopGames/EcoIssues#10103]
**Version:** 0.7.8.4 beta

**Steps to Reproduce:**
1-Give yourself "Mint" as an admin.
2-Create currency from there.

**Expected behavior:**
It should just create a new currency.

**Actual behavior:**
It does create a new currency but, it renames every building of the person who got the Mint by give something like (ecoiconn
**Do you have mods installed? Does issue happen when no mods are installed?:**
It does create a new currency but, it renames every building of the person who got the Mint by give something like (ecoicon= ItemMint) etc.

**Comment by D3nnis3n** [comment]
Closed as Duplicate.
