### ISSUE TITLE
Alpha 5.3 - Cart & player are brought back from the underground to the surface when they reach level 49 (under sea level)

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#1010]
Pre-requirement:
- In Alpha 5.3
- Have a cart
- Have a road (dirt road) going under ground and reaching level 49 (under sea level)

Description:
When I go under ground with the cart, at the moment that I reach level 49 (under sea level), the cart and myself are brought back to surface.

Step:
1. Move your cart on an dirt road under ground and reach level 50 (height)
2. Go down with the cart a little bit more to go under level 50.

Results:
- The cart and the player are brought back to the surface from the cave.
![image](https://cloud.githubusercontent.com/assets/7052045/21770099/cabe6170-d64f-11e6-8c6c-298ccbb8e244.png)

Expected Results:
- The cart should be able to go under the sea level (level 50) when the cart is under ground without being brought back to the surface.

Note:
Ask if you want more details to how reproduce the bug.

**Comment by rozla41** [comment]
Getting similar bug but heights are different I can get my cart to 21 on a stone road inside a cave, any lower and it warps to the surface. then if i place the cart lower than height 21 the client will crash. sea level on  current server is 25.

**Comment by 616dustin** [comment]
May not be related to sea level, this is happening at level 40 on my server where the sea level is at 25.

**Comment by MarjieAVolk** [comment]
Fixed as of 5.5
