### ISSUE TITLE
[7.8.5] Modkit is broken

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10111]
Hotfix for 7.8.4 broke modkit.  @Quadbro can you take a look?

[ServerCrash_TargetInvocationException_11221807.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2608958/ServerCrash_TargetInvocationException_11221807.zip)

Add ceiling fan to mods folder in the server and invoke /give ceilingfan
https://github.com/StrangeLoopGames/EcoModKit/blob/staging/CeilingFanDistribution.zip

**Comment by Quadbro** [comment]
Yeah. probably it's Friendly name related changes, i'll look

**Comment by Quadbro** [comment]
@BlazeGuy2 Need to accept that PR in modkit. Updated tutorial files: https://github.com/StrangeLoopGames/EcoModKit/pull/8

**Comment by Quadbro** [comment]
Related, but he'll need to fix that by himself :(

**Comment by Deantwo** [comment]
I know, just felt it was a good idea to add a link between the two.

On that note, at least this issue is properly named.

**Comment by D3nnis3n** [comment]
Reopened as the staging version has not been replaced.

**Comment by seccombew** [comment]
modkit will be refreshed when 8.0 is released.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoModKit/blob/staging/CeilingFanDistribution.zip does not show a new modkit, not even the fixed one. Where is the one that does work for now?
