### ISSUE TITLE
Can't cut log on my property

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10114]
See the screenshot. Osafts property begins where the mortared stone is, the other one is mine.
<img width="1816" alt="property" src="https://user-images.githubusercontent.com/25908592/48921782-687dfd00-eea2-11e8-9841-eafdd2d814cd.png">

**Comment by elfl0rd** [comment]
Intended as i know, cutted trees save property tag from his start place.
It's prevent to steal down log.

**Comment by Deantwo** [comment]
Noticed this too, on logs that have been there a long time even.

**Comment by elfl0rd** [comment]
By the way, thanks to this feature, you can collect a tree fallen on someone else's land :)

**Comment by Deantwo** [comment]
I better error message would be nice though, and maybe a timeout to make it respect the underlying property owner.
Maybe:
```Log fallen Osaft23's property, will retain ownership for 2 hours.```

**Comment by D3nnis3n** [comment]
There must be a way that the ownership get’s removed. I have several of these lying around on my streets which i cannot remove as they are not cut into pieces yet and therefore can’t be targeted with the dev tool to remove.

**Comment by Deantwo** [comment]
So a second bug, Dev-Tool can't target uncut logs.

**Comment by elfl0rd** [comment]
> So a second bug, Dev-Tool can't target uncut logs.
> might wanna report that as well.

@Deantwo comment here https://github.com/StrangeLoopGames/EcoIssues/issues/9874

**Comment by BlazeGuy2** [comment]
PR merged in.
