### ISSUE TITLE
Treasury Infinite/NaN amounts.

### ISSUE THREAD

**Issue by TheKrush** [StrangeLoopGames/EcoIssues#10115]
First if you tax someone for their personal credit (all of their amount of it) it results in the Treasury having 'Infinite' of that credit.

Then if you try to allocate all of the Treasury's amount of that credit back to the person it becomes 'NaN' which still operates as 'Infinite' for allocation purposes.

![image](https://user-images.githubusercontent.com/671500/48933443-1eeadd80-eeb5-11e8-95bb-7a340ac5a553.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8368

**Comment by Deantwo** [comment]
The `NaN` value seem fun, how does that react to taxation or allocation?

**Comment by TheKrush** [comment]
It acts basically as if it's Infinity for allocating it out. I tried doing taxes to give some back but it doesn't seem to ever change off that value now.

**Comment by Quadbro** [comment]
oh man, how did you allocate it back with max 999 999 at a time?) seems like you did a lot of clicks?)

**Comment by elfl0rd** [comment]
just allocate by laws...
or\adn use Infinity as number

**Comment by Quadbro** [comment]
Not a fix, but added button there, to dump currency amount in treasure
