### ISSUE TITLE
Too many garbage blocks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10119]
Hm, strange.
Decay logic has been changed?
Before, from 1 trash block, you receive 1 garbage block, now you receive garbage blocks from all items in trash block...
e.g.
1 trash block, 4 item
![20181123144122_1](https://user-images.githubusercontent.com/4980243/48965791-fce87c80-efd4-11e8-832f-9fbf209c3e79.jpg)
now 4 garbage
![20181124095352_1](https://user-images.githubusercontent.com/4980243/48965794-04a82100-efd5-11e8-8a6b-1843886709f4.jpg)

This makes "trashing" items terribe, players return to store unneeded items in chests again :(

**Comment by Deantwo** [comment]
maybe number of garbage blocks created should depend on the total weight of the bag content.
That way a stack of 100 ingots create more garbage than a stack of 100 skill scrolls.
But I guess that would require all items to have a weight.

**Comment by elfl0rd** [comment]
> Maybe number of garbage blocks created should depend on the total weight of the bag content.
That way a stack of 100 ingots create more garbage than a stack of 100 skill scrolls.
But I guess that would require all items to have a weight.
1 chest, occupy 2 block. Can contain LOT of trash items w\o creating pollution.

**Comment by elfl0rd** [comment]
(fixed)

**Comment by elfl0rd** [comment]
Broken again.
Verified in 0.8.3 and master.
![изображение](https://user-images.githubusercontent.com/4980243/67598062-4b6a4200-f775-11e9-9654-0f2c38140af9.png)
![изображение](https://user-images.githubusercontent.com/4980243/67598407-1dd1c880-f776-11e9-8d6d-a8c8ede34034.png)
