### ISSUE TITLE
[QoL] allow use new district\demographics in same law.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10112]
At present, you need pass redefine disctrict law, and ONLY then you can use added district in law.
It make creation law like "add new district "tailings" + prevent place tailings outside" is really, really long (double time) and terribe (you need create 2 law, instead of one).

Please, allow using new proposed districts in same law!

**Comment by D3nnis3n** [comment]
And you need to wait double the time.

**Comment by Deantwo** [comment]
Same with demographics.

**Comment by johnkslg** [comment]
Will be in 9.0 update

**Comment by Deantwo** [comment]
Also not fixed/implemented yet. It is mentioned as planned for v0.9.0.0 though.

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11966. Has been fixed.
