### ISSUE TITLE
You can /give skill like item

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10117]
![20181123231239_1](https://user-images.githubusercontent.com/4980243/48959307-88cabc00-ef75-11e8-998b-6db7826f4104.jpg)
![20181123231246_1](https://user-images.githubusercontent.com/4980243/48959315-8ec09d00-ef75-11e8-89cf-02a385e0b048.jpg)

**Comment by D3nnis3n** [comment]
LOL, what can you do with it?

**Comment by elfl0rd** [comment]
Nothing :)

**Comment by D3nnis3n** [comment]
Then i'm giving it a low for now, is odd but doesn't do any harm.
