### ISSUE TITLE
USER ISSUE: connection error ignore esc

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10116]
**Version:** 0.7.8.5 beta
![20181123162221_1](https://user-images.githubusercontent.com/4980243/48945696-505abc00-ef3c-11e8-8dae-5ab796c8ff5c.jpg)
![20181123162224_1](https://user-images.githubusercontent.com/4980243/48945699-52247f80-ef3c-11e8-8a88-8b757a4e35dd.jpg)

**Comment by Deantwo** [comment]
Thought I saw a fix for this in #codestream.

**Comment by elfl0rd** [comment]
3666 fix for opening bug report screen after you hit esc.
https://github.com/StrangeLoopGames/EcoIssues/issues/10108

@Quadbro yor fix fixes that too?

**Comment by Quadbro** [comment]
idk ^_^, probably not, it seems like escape menu has higher priority for user input

**Comment by Quadbro** [comment]
Fixed in master, will test in release (after that fix)

**Comment by BlazeGuy2** [comment]
PR is merged in
