### ISSUE TITLE
Text on trucks is not resized anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10113]
See this screenshot. Earlier this would have been resized to fit the sign, i did it before.

<img width="1460" alt="resize" src="https://user-images.githubusercontent.com/25908592/48921500-703ca200-eea0-11e8-966a-c871fa87d959.png">

**Comment by Quadbro** [comment]
version?

**Comment by D3nnis3n** [comment]
7.8.5

Am Fr., 23. Nov. 2018, 04:00 hat Mike <notifications@github.com>
geschrieben:

**Comment by Quadbro** [comment]
That was only steam truck issue, fixed it and commited to svn
