### ISSUE TITLE
USER ISSUE: 1

### ISSUE THREAD

**Issue by Sergant1530** [StrangeLoopGames/EcoIssues#10128]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: D:/ECO v0.7.0.8/Eco_Data/Server/Storage\Serg1.eco already exists
```

**Comment by elfl0rd** [comment]
1) you cannot create new save with same name without manually delete existing.
2) Why you use pirate copy?

**Comment by D3nnis3n** [comment]
This version is way too old, please update to the most recent version as elfl0rd said and report back if the issue persists.
