### ISSUE TITLE
[Client] Chopping a tree and collecting it simultanously lets the whole tree dissapear

### ISSUE THREAD

**Issue by mmattes** [StrangeLoopGames/EcoIssues#10122]
**ECO-Version** 
Alpha 0.7.8.5

**Expected behavior**
Chopping a tree and collecting pieces at the same time should not let the whole tree disappears, it should only collect the new copped piece

**Current behavior** 
the whole tree and not only the part which was copped out of it disappears

**Steps to reproduce**
1. Chop a tree that it lays on the ground
2. left click to chop a piece out of it and immediately press E to collect the piece
3. the whole tree disappears

**OS**
Linux Mint

**Comment by Nicolausi113** [comment]
Confirm, happens also on windows7 for me – respawns after restarting game.
Releated #8823

**Comment by D3nnis3n** [comment]
Pretty much a duplicate of #8823
