### ISSUE TITLE
Tutorial does not detect that 10 logs were placed in stockpile

### ISSUE THREAD

**Issue by Kempeth** [StrangeLoopGames/EcoIssues#10125]
Have placed 10 logs in stockpile but tutorial does not continue.

**Comment by elfl0rd** [comment]
you use latest version?
if yes, it looks as https://github.com/StrangeLoopGames/EcoIssues/issues/9877 not fixed ;\

**Comment by Kempeth** [comment]
I've managed to switch my game to English only but the tutorial is still broken. (Tried it with the old world as well as after creating a new one.)

**Comment by elfl0rd** [comment]
Old issue - https://github.com/StrangeLoopGames/EcoIssues/issues/9877

**Comment by BlazeGuy2** [comment]
Set server to german on master and tested.  Fix should come out in a future release.
