### ISSUE TITLE
Admin unclaim commands doesn't give plot owner unclaim actions

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10121]
Split off from #9444.

The only way we have to count the number of claims a player has, is by counting the number of `Claim` and `Unclaim` actions they have, so we do `(Claim actions - Unclaim actions)` to calculate the number of claims the player has.

This becomes impossible to do the moment an admin starts doing maintenance with the [`/unclaim`](https://eco.gamepedia.com/Chat_Commands) command (and others), because unclaiming with those commands doesn't currently add an `unclaim` action to the statistics of the affected players.

Would love a way to count current number of claims rather than relying on action counts. But if the action counts can become more reliable it might not be necessary (yet).

**Comment by D3nnis3n** [comment]
@johnkslg Does /unclaimabandon trigger unclaim actions? Otherwise, i expand that issue to this command, too.

**Comment by Deantwo** [comment]
It can be argued that maybe this shouldn't be changed, since this is an action performed by someone else.
But then we instead need actual law options to get the number of claims a player has, so we don't need to rely on `(do - undo)` action counts.

**Comment by johnkslg** [comment]
Ill do something about this for 9.0 laws update.

**Comment by Deantwo** [comment]
Likely also an issue for the new "unclaim all property" and "seize all property' law actions added in v0.8.0.0.

Unless you mean you added a vetter __property count__ method.

**Comment by johnkslg** [comment]
Make sure the admin command calls the right actions for claim/unclaim @olegshegai

**Comment by olegshegai** [comment]
By the way, there's no need to calculate (do-undo) difference since there is an already implemented field for that.

Anyway, latest PR contains `ClaimOrUnclaimProperty` action triggering for `/claim`, `/unclaim` and `/unclaimabandoned` admin commands.

**Comment by Deantwo** [comment]
> By the way, there's no need to calculate (do-undo) difference since there is an already implemented field for that.

Yeah now that we have a "number of claims" value, this isn't really necessary anymore. I mentioned this above too.
