### ISSUE TITLE
Flat Steel ladder missing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10123]
This is really strange, you cannot use vertical ladders in houses more than 1 tier... or you get lowering skill points from it.
Yes I can understand the lack of brick,stone and concrete ladders (although they rarely exist in the real world) but where is the lumber ladders? metal ladders?
![20181124181158_1](https://user-images.githubusercontent.com/4980243/48969837-a3ed0880-f015-11e8-8c80-df82ddfe5d66.jpg)
![20181124181854_1](https://user-images.githubusercontent.com/4980243/48969831-8881fd80-f015-11e8-9f0c-8fd2af696884.jpg)

**Comment by SeanAtr0n** [comment]
Looks like lumber and Steel ladders just need to be added to the techtree

**Comment by elfl0rd** [comment]
No art for it as i know...

**Comment by BitsBytesGaming** [comment]
I agree - it's very clear that the higher-tier ladders should be made from those materials
(after all, ladders made of brick, glass, or concrete don't seem to make any sense).

**Comment by Deantwo** [comment]
but a brick ladder isn't that weird... it is just more something you carve into a wall then a real movable ladder... same for stone and concrete
for example: https://www.fotowalls.com/media/catalog/product/cache/1/image/1400x1867/17f82f742ffe127f42dca9de82fb58b1/f/w/fw-1162-wm-print.jpg

**Comment by elfl0rd** [comment]
All additional ladders require artists work... (and different animations!) It's main reason why i split priority on adding common ladders to all tiers and creating ladders from all materials.
In addition, in General, ladders from stone\bricks etc... are not so necessary.
I think - ladders availability on all tiers - issue
More ladders (bricks, concrete, stone, etc...) - suggestion

**Comment by BitsBytesGaming** [comment]
Let me be clear:
I'm not against having ladders made of materials such as those I mentioned above, I just don't think they should appear the same as ladders made of "normal" materials, such as wood or metal.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/51142442-da1e5b80-1800-11e9-97ac-22cd0f68bdfd.png)

I made steel and lumber variants originally when I made the block art for hewn log, and they are in master. Will look into making ladder forms for all materials where possible later.

**Comment by elfl0rd** [comment]
Flas Steel ladder is missing :(

**Comment by keegan-o** [comment]
Just checked in blocks and a skin for Flat Steel ladders-- @craig-jong , please add the ladder form to Flat Steel.

**Comment by elfl0rd** [comment]
Please add flat steel ladder before 0.8!

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/53210970-828bc080-35f4-11e9-9bae-3b9cbfb96950.png)

They'll be in master. They might in 8.0, but I'm not 100% sure.
