### ISSUE TITLE
overridding MTU will cause many packets to fail to reach destination

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#10138]
recently the MTU was changed from the default value to a much higher one.  This will result in packet loss to a lot of destinations, as the MTU is too high.

**Comment by Quadbro** [comment]
And what are the solutions?) Clamp server names and return old mtu value?)

**Comment by mirasrael** [comment]
@metachronism is it observed behavior or just a theory?
If increasing MTU isn't working then we have a few options:
- clamp server info, in this case we will lost a lot of information about servers and with growing server info it will become even worser;
- use server info compression (either with binary format or zip), it will add us some additional capacity, but it also will be consumed fast enough and also it will complexify server info pre-processing on Master Server side;
- switch to TCP. For me it seems as best alternative. It may be slower than UDP, but we shouldn't have much communication with MasterServer.

**Comment by mirasrael** [comment]
@inlife It only works with Connected messages, but I implemented fragmented message for non-connected messages before read your post :)

**Comment by inlife** [comment]
oh, i see the issue now, you are right 👍   
actually i think in that case using tcp, or even with http(s) on top for non-gameplay related data (master server) might be even more comfortable
