### ISSUE TITLE
Temp needs to be migrated

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#10134]
range changed from -10 - 30 -> 0 - 1, existing worlds will need their temp layers remapped to this range.

**Comment by BlazeGuy2** [comment]
BTW, this is needed for master.

**Comment by metachronism** [comment]
still think we should just require people to regenerate... all the block types will be missing in 8.0, cant really fix that anyway

**Comment by craig-jong** [comment]
The temperature world layer's range was changes, so we'll need something to migrate old versions to the new range.

**Comment by mirasrael** [comment]
@johnkslg gonna to work on this after https://github.com/StrangeLoopGames/Eco/pull/3806 merged, because it contains migration changes
