### ISSUE TITLE
USER ISSUE: Steam Tractor with plow will plow claims that do not belong to you

### ISSUE THREAD

**Issue by DumpsterDave** [StrangeLoopGames/EcoIssues#10130]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1.  Equip Steam Tractor with Plow Attachment.
2.  Lower plow.
3.  Drive across a claim that belongs to someone else that has not given you authorization.	

**Expected behavior:**
Plow does nothing to claims that do not belong to you.

**Actual behavior:**
Plows the claim regardless of authorization and kills any crops already growing on it.n

**Do you have mods installed? No
Does issue happen when no mods are installed?:  Yes

Plows the claim regardless of authorization and kills any crops already growing on it.

**Comment by elfl0rd** [comment]
Nice find!

**Comment by Quadbro** [comment]
Already seems to be fixed in 8.0.6

**Comment by elfl0rd** [comment]
no, but for repro you feel free to call @D3nnis3n

**Comment by elfl0rd** [comment]
verified, fixed.
