### ISSUE TITLE
Eco should display 'Downloading Mods' when downloading from a server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10139]
Currently it just spins this for a very long time and looks frozen. A percent finished would be amazing too.
![image](https://user-images.githubusercontent.com/3536496/49120767-db042980-f262-11e8-950c-b5348d6686d7.png)

**Comment by johnkslg** [comment]
On eco.greenleafserver.com:3010 this can take several minutes for example

**Comment by Phlo123** [comment]
eco.greenleafserver.com:3010 is a test server. Its usually online but it can happen to be off from time to time.
