### ISSUE TITLE
Jump from My Worlds to Browse All and back again

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10132]
Would it be possible to have the  a way, when you are in "My Worlds" to jump/link to "Browse All" or 'My Game' without having to go back to the main men every time and to do the reverse and go from "Browse All/New Game" to "My Worlds" , again without having to go back to the main page..  It does not seem to much of a deal to always have to jump back to the main window to then jump to the other page but many ask as this is what they think would be a smoother transition for them working in there main menu.  I have had the same thought many time when not being able to jump from one page to the other other without having to go to the main window first.

Also is it or is it not expected behavior that when you set the filers up a certain way that filter should remain as you set it even if moving between main, 'my worlds' and 'new game (or browse all) or enter into a world and then disconnect and come back to the main page.  I understand it not holding between client shut downs but in some cases if I jump from pages to page the filters I set when in "New Game" or "Browse All" do not hold between moving between pages and then jumping to "My Worlds". and other times they do.  I have not found out what I do different to get it to remember filter settings it just seems random whether it does or does not.  Many players have asked the same thing to - what is the expected behavior because it does both, randomly from what they can tell and they would just like it to be one way or the other - consistently.

**Comment by metachronism** [comment]
theres already a GDD for this
https://docs.google.com/document/d/1C_ioc-QGzcYjqG8MyKmXnPUUsZnj11dMPPJgRu01Nw0/edit#heading=h.fpa3wavstetd
