### ISSUE TITLE
[Win/Linux] Server Crash upon loading periodic law with demographics

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#10137]
**ISSUE:** 
When loading a 7.8.x world (world save included) and using a periodic law to tax people every 1 day a certain percentage of their minted currency balance depending on their 'tax bracket' demographic, the server will crash with a Null Reference Exception upon reboot.

**STEPS TO REPRODUCE**:
Boot up the included world save

**ADDITIONAL DETAILS**:
- _Initially_ created using a 7.8.3 save under Windows in order to keep mod compatibility.
- Removed all mods, extracted server files from a clean, vanilla 7.8.3 archive. Same issue persists
- Updated to 7.8.5; issue persists
- Tested Linux VM concurrently, using Mono 5.14 and Ubuntu 18.04; issue persists.
- Removed eco.db; issue persists

World save: 
https://1drv.ms/f/s!Ah1HP-nsGmcYies7ZYnsyiq4IM4wIQ
Crash dump:
[ServerCrash NullReferenceException 11274051.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2621096/ServerCrash.NullReferenceException.11274051.zip)

**Comment by Quadbro** [comment]
Your crash is related to some modded skills...

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/49134319-c5037100-f315-11e8-9b5e-e7056db7193e.png)

**Comment by DragonSupremacy** [comment]
Okay, thanks for letting me know. I haven't removed any mods but I'll let the mod author know there are bugs in the code.

**Comment by Quadbro** [comment]
Some fixes are incoming, after them you will be able to load your world, with no crashes ;)

**Comment by D3nnis3n** [comment]
Fixed.
