### ISSUE TITLE
[Master] Pump object should be able to be placed on top of liquid source

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10140]
A pump right now requires a water source beneath them to function, but I can't place a pump directly on top of them.  Setting it up to have a pipe connected to a water source feeding in would work too.

**Comment by SeanAtr0n** [comment]
Pumps now have input pipes so this isn't really necessary anymore. (also the new pumps look silly floating on water so I'll just close this to preserve artists well being)
