### ISSUE TITLE
USER ISSUE: Skid steer is picking up items from stockpiles through the ground

### ISSUE THREAD

**Issue by Sandflakes** [StrangeLoopGames/EcoIssues#10142]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Place a stockpile underground and fill it with dirt, stone, or ore.
2. Hollow out a room about 8-10 blocks above the stockpile with the skid steer.
3. Sometimes it will target the stockpile deep below through the ground when digging and pick up the items from that stockpile.

**Expected behavior:**
It should not pick up items from the stockpile through the ground

**Actual behavior:**
It will pick up items from a stockpile far away through multiple layers of stone.

**Comment by SlayksWood** [comment]
merged to #18731
