### ISSUE TITLE
Can’t start ECO Client after Auth Server breakdown

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#10145]
After giving username and password an endless “loading” screen appears, can only break with taskmgr. Deleting %appdata% > SLG folder doesn’t help either.
One time I got this message:
[fail.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2626964/fail.txt)

**Comment by Deantwo** [comment]
Duplicate of #10143
