### ISSUE TITLE
[7.9.1] Material Processing Tutorial not working

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10148]
If not reproducable, try german language for server.

Neither "click to order" nor picking up hewn log tasks are getting checked.

<img width="1920" alt="materialprocessing" src="https://user-images.githubusercontent.com/25908592/49205812-7656e500-f3b0-11e8-84b8-439e40b34f7a.png">

**Comment by elfl0rd** [comment]
It looks as https://github.com/StrangeLoopGames/EcoIssues/issues/9877 happens again.

**Comment by elfl0rd** [comment]
and new one... https://github.com/StrangeLoopGames/EcoIssues/issues/10125
