### ISSUE TITLE
Long delay when creating laws

### ISSUE THREAD

**Issue by Sandflakes** [StrangeLoopGames/EcoIssues#10144]
When creating laws there is a long delay between each action, between 2-4 seconds and if you change anything while it is waiting it will just switch it back. This is making law creation really time consuming and annoying. 

I have tested with both Google Chrome and Firefox, multiplayer and single player with same issue on both. Also noticed this issue in the trailer [https://youtu.be/ud_refZuQoA?t=142](url). 

Another issue is that if the server is restarted you have to redo all the work, even if you still have the tab open, and you get "Error: (Object object)".

**Comment by rainfarmer** [comment]
I'm not able to repeat this. I'm able to get up to a 2 second delay for changes to a long law.

Is the delay when you submit the law or while editing?

Probably some servers lag more than others.

**Comment by BitsBytesGaming** [comment]
Given that the tests above were done, at least in part, in singleplayer, it doesn't seem likely that any lag would be caused by any server connection issue (unless there was an insanely high ping, etc.). In my experience the web interface has been of particular issue, especially when using the law configuration category.

**Comment by rainfarmer** [comment]
@BitsBytesGaming @Sandflakes 
Could you send me a server that you experience this on and I can test? jeff@strangeloopgames.com

**Comment by ty1824** [comment]
I've been noticing a similar issue - the more clauses I added to the law the longer they would take to update.

Additionally, I find it odd that the law's state is maintained on the server and *only* on the server. It seems like it would be more ideal to allow the client to write a law given the various options (some of them requiring querying the server for information) and then submit the entire law to the server for validation.

**Comment by Reyalsorik** [comment]
The more clauses I add, the amount of delay between actions feels exponential. This deters my player base from creating laws. No one wants to spend 30+ minutes writing a law that would take 5 minutes without the delay. 

> Additionally, I find it odd that the law's state is maintained on the server and only on the server. It seems like it would be more ideal to allow the client to write a law given the various options (some of them requiring querying the server for information) and then submit the entire law to the server for validation.

+1

**Comment by D3nnis3n** [comment]
@rainfarmer This happens on any server, it just depends on how long the law is. The more clauses you add and the more complex it is, the laggier it gets. I have experienced up to 15 minutes delay for an select action in a dropdown to actually work on long laws.

**Comment by beastyn** [comment]
about 4 secs for me with 6 clauses and inner parameters are in long response too,

**Comment by rainfarmer** [comment]
laws being moved to in-game
