### ISSUE TITLE
[7.9.1] Work Order tutorial not functioning

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10147]
If not reproducable try on german language for server.

<img width="1758" alt="workorder" src="https://user-images.githubusercontent.com/25908592/49205652-f3358f00-f3af-11e8-8f6a-d561d2fe8da3.png">

**Comment by elfl0rd** [comment]
as https://github.com/StrangeLoopGames/EcoIssues/issues/10148
