### ISSUE TITLE
USER ISSUE: pourcentage

### ISSUE THREAD

**Issue by ALINORS** [StrangeLoopGames/EcoIssues#10157]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**

**Expected behavior:**
25%

**Actual behavior:**
25?n
**Do you have mods installed? Does issue happen when no mods are installed?:**
25?

**Comment by Deantwo** [comment]
What?
You'll have to explain what you mean and maybe add some screenshots.

**Comment by Deantwo** [comment]
The percentage symbol (`%`) appears as a question mark (`?`).

What language is your computer?
What language is your game client?
What language is the server?

**Comment by ALINORS** [comment]
the language of my computer is french and that of my server and my client

**Comment by beastyn** [comment]
@ALINORS please reopen if you still have this issue
Seems to be fine for 0.8.1.4

**Comment by Xandoria** [comment]
The bug is still here in 0.8.1.4 :
![e3456b25e24030ef037e566ff67a2d2b](https://user-images.githubusercontent.com/26251843/57216315-d2710580-6fef-11e9-8cef-211b4cdecceb.png)
I am using a French version of Windows and using an AZERTY keyboard. The bug occurs even if the server is set to English and the game set to English.

**Comment by Xandoria** [comment]
Please note that in French, typographic rules specify that there is a space between the number and the % sign.

**Comment by SlayksWood** [comment]
@Xandoria @ALINORS 
There were many changes in localization in 0.8.2.x. Do you still have this problem? I can't reproduce.
![image](https://user-images.githubusercontent.com/45708377/61036982-da279e80-a3d2-11e9-9f74-6990b8aee30b.png)

**Comment by D3nnis3n** [comment]
Closed for no response. Please open a new issue when this reoccurs and you have more information.
