### ISSUE TITLE
[7.9.1] Server Crash (ClientException) with Local Server while /fastforwarding

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10151]
[ClientUpdateException ArgumentException 11290223.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2628157/ClientUpdateException.ArgumentException.11290223.txt)

**Comment by D3nnis3n** [comment]
Cannot reliably reproduce. If the message itself doesn't help - feel free to close.

**Comment by SlayksWood** [comment]
Checked on 8.2.5. Wasn't able to reproduce, seems fixed.
