### ISSUE TITLE
5.3 Mini Map

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1015]
Mini Map when open due to how much stuff is being flooded to it, lags game so much that it is pretty useless to have open other then to mark you zone of control with the markers.

other whys there just to much stuff being uploaded to it and it just bogs the game down so that it is unplayable.

fix currently is just to keep mini map off completely.

**Comment by L33m4n123** [comment]
A little "workarround" for the minimap is to open the filters and then disable basicly everything except Player and Player Names. At least that seems to work fine on my machine. However the filter settings are not saved so you have to redo it everytime you restart the game

**Comment by midn8t** [comment]
the only thing any one really uses the mini map for is to see where they are at in the game world and find there borders when placing deeds.

I kind of wish they do a more hand drawn map and add exploration into the game

**Comment by MarjieAVolk** [comment]
Hm interesting, I can add saving of filter panel state

**Comment by stett** [comment]
That issue exists here: https://github.com/StrangeLoopGames/EcoIssues/issues/1253

**Comment by MarjieAVolk** [comment]
Oh, great I'll close this then.
