### ISSUE TITLE
[7.9.1] Object Picker on Contracts does not show icons for some objects

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10153]
See the screenshot, if not reproducable try to set the server to german language.

<img width="731" alt="missingicons" src="https://user-images.githubusercontent.com/25908592/49210207-cdfb4d80-f3bc-11e8-9595-0ff1c29790ab.png">

**Comment by Quadbro** [comment]
8.0.4 not reproduced ...

**Comment by D3nnis3n** [comment]
Reproduced on 8.0.5 - don't forget to set SERVER LANGUAGE to German or any other language but english.

![reproducable](https://user-images.githubusercontent.com/25908592/53735442-242dd000-3e87-11e9-88cb-94d214e8fe11.png)

**Comment by beastyn** [comment]
Was fixed for localization in 8.1
