### ISSUE TITLE
USER ISSUE: Minimap blanks and adds grayscale to world

### ISSUE THREAD

**Issue by Boartato** [StrangeLoopGames/EcoIssues#10158]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
Stay online long enough

"Fixed" by restarting.

**Expected behavior:**
Minimap continues to function, no overworld hue added

**Actual behavior:**
Minimap goes brown and adds a gray hue to the overworld mapn
**Do you have mods installed? Does issue happen when no mods are installed?:**
Minimap goes brown and adds a gray hue to the overworld map

**Comment by D3nnis3n** [comment]
Can you provide a Screenshot? Cannot reproduce this.

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
