### ISSUE TITLE
Propose Law - Error: [object Object]

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10154]
**Version:** beta 7.8.5

![image](https://user-images.githubusercontent.com/2676134/49278080-074ac080-f484-11e8-8e1e-e061a8402c0c.png)

![image](https://user-images.githubusercontent.com/2676134/49278089-0b76de00-f484-11e8-9f35-40065634e3db.png)

Unlike concluded in #10084, this error message does seem happen some times.
Even if it were another law preventing law proposals, it should give a better error message to the user.

It has been observed to happen when a law is preventing law proposals, but also when not logged in in-game. For example I got the error yesterday when the Auth server was down and the server kicked me from the game.

A short list of reasons for this error:

- Disconnected from the game (close webpage and open it again from in-game)
- The law name was used before already (name the law something else)
- Citizenship law blocking you (check if you are a citizen)

**Comment by D3nnis3n** [comment]
Probably missing error message for not being logged in correctly.

**Comment by Deantwo** [comment]
That could be. I haven't had the issue since, but I have not been disconnected from the server while editing laws either.

**Comment by garc1a** [comment]
well, Im using chrome with AdBlock. No issues so far

**Comment by whisper2shade** [comment]
I'm using "AdBlock Plus" if it helps.

**Comment by D3nnis3n** [comment]
This is fixed.
