### ISSUE TITLE
[7.9.1] World Layer Tick took around two minutes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10150]
Using the server UI doing one tick took around 2 minutes - goal was under 30 seconds. (Used my main world, though)

**Comment by SlayksWood** [comment]
8.2.0 staging-16-n:
1.96km World
![image](https://user-images.githubusercontent.com/45708377/58788576-d5faab00-85f4-11e9-9dd4-1ef56f3e0629.png)

0.52 km world: usually some less 30 sec
![image](https://user-images.githubusercontent.com/45708377/58791899-c29f0e00-85fb-11e9-89e3-99dd3921eb63.png)

**Comment by mirasrael** [comment]
It is fine until it takes under 10 minutes.
