### ISSUE TITLE
Invite to Game button is missing in steam

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10166]
![image](https://user-images.githubusercontent.com/3536496/49313020-d45ff700-f49a-11e8-83fa-bfdcdefb9deb.png)

**Comment by metachronism** [comment]
this looks like it broke with master server GUID id changes

**Comment by mirasrael** [comment]
@johnkslg Which version is it?

**Comment by mirasrael** [comment]
Checked on current release and on 7.9.1 version (which already have GUID ids) and in both cases I have 
```
Invite to Game (Пригласить в игру)
Eco
```
![image](https://user-images.githubusercontent.com/475445/49354464-1627b200-f6d4-11e8-9634-ebcbafce0f2a.png)

**Comment by mirasrael** [comment]
Issue related to Steam changes.
