### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by ElTyranos** [StrangeLoopGames/EcoIssues#10160]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
press continue
wait
can't connect to server - connection timed out	

**Expected behavior:**
join sur the server (working for other players)

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by Nicolausi113** [comment]
related #9680

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10321
