### ISSUE TITLE
USER ISSUE: Adding fuel to steam generator toggles it on/off

### ISSUE THREAD

**Issue by DumpsterDave** [StrangeLoopGames/EcoIssues#10162]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1.  Walk up to object that uses fuel and can be toggled on/off
2.  While carrying fuel, right click on object to add fuel

**Expected behavior:**
Can Accept Fuel | Carrying Fuel | Toggles Power
--------------- | ------------- | -------------
Yes | Yes | No
Yes | No | Yes
No | Yes | No
No | No | Yes

**Actual behavior:**
Turns the machine on/off, fuel is not added

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by Deantwo** [comment]
Same with all fueled devices that have an on/off toggel: Torch Stand, Stone Brazier, Brazier, etc.

**Comment by elfl0rd** [comment]
Dupe, https://github.com/StrangeLoopGames/EcoIssues/issues/7240 hard to fix.
This issue based on components loading order, and require remake lot of code to fix.

**Comment by D3nnis3n** [comment]
Duplicate
