### ISSUE TITLE
USER ISSUE: Bug: Destroying trash bags

### ISSUE THREAD

**Issue by Boartato** [StrangeLoopGames/EcoIssues#10164]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1)Drop items beside an empty stockpile creating garbage bags
2) Drop more garbage once the tiles around you have filled up, some of the bags will land on the stockpile despite the tile not being "free"
3) Fill the stockpile with items, when it fills the spot where the trash is sitting, the trash bag gets destroyed.

**Expected behavior:**
Not destroyed the trash bag, maybe generated a shovelable trash block inside the pile

**Actual behavior:**
Destroyed the garbage bag entirely.n
**Do you have mods installed? Does issue happen when no mods are installed?:**
Destroyed the garbage bag entirely.

**Comment by midn8t** [comment]
it be nice if trash and even industrial waste would bio degrade over time and get soaked into the land scape just like real life.

**Comment by Deantwo** [comment]
@midn8t, Items with a green background don't create garbage blocks because they are bio degradable.
See: https://eco.gamepedia.com/Garbage

That aside, garbage is not fully implemented yet. Also missing slag.
So plenty of changes to pollution are coming, but this is not the right place to discuss this.

**Comment by beastyn** [comment]
[0.8.1.3]
Still actual. Trash is getting into stockpile placement and will be destoyed with filling stockpile.

![bandicam 2019-04-19 09-35-01-363](https://user-images.githubusercontent.com/27898520/56405656-b39c1080-6286-11e9-93bd-41998137235a.jpg)
![bandicam 2019-04-19 09-35-41-580](https://user-images.githubusercontent.com/27898520/56405660-b565d400-6286-11e9-863b-c788102a70ed.jpg)
![bandicam 2019-04-19 09-36-22-406](https://user-images.githubusercontent.com/27898520/56405664-b6970100-6286-11e9-82df-e54b403251ca.jpg)

**Comment by TwixterZ** [comment]
Closing this issue as this is now fixed for the upcoming patch, apologies it takes awhile. =)
