### ISSUE TITLE
Tall grass gets me up close and personal with my avatar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10168]
Seems to be detecting collision but its just grass
![image](https://user-images.githubusercontent.com/3536496/49313663-cf9c4280-f49c-11e8-935f-6601aa3a7026.png)

![image](https://user-images.githubusercontent.com/3536496/49313665-d4f98d00-f49c-11e8-81d4-7df22d46cc80.png)

**Comment by SeanAtr0n** [comment]
There are a few plants that are invisible right now, you are most likely standing in one of them

**Comment by SeanAtr0n** [comment]
err misread this... plants colliders should be set to trigger

**Comment by keegan-o** [comment]
Fixed in master.
