### ISSUE TITLE
new singleplayer world does not work

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#10167]
crashes after the map gets made

**Comment by metachronism** [comment]
this is prevalent in the current release.

**Comment by BlazeGuy2** [comment]
So far I can play on a SP world for the first time on the build, but then I can't finish reloading into the world.

**Comment by elfl0rd** [comment]
I still cannot repro, not in release, not in master, not in branches.
Maybe close it?
