### ISSUE TITLE
Roof tiles don't lock properly

### ISSUE THREAD

**Issue by Magnetkay** [StrangeLoopGames/EcoIssues#10173]
![image](https://user-images.githubusercontent.com/45519359/49331297-09ec0980-f59b-11e8-9814-06a0bc9ba91a.png)

But, the moment you snap a roof block in between it, it will look like the following
![image](https://user-images.githubusercontent.com/45519359/49331312-3142d680-f59b-11e8-918e-65264a8e87b4.png)

Can this be fixed, my OCD is making overhours xD

**Comment by elfl0rd** [comment]
Try to place roof over roof, not over enother block,

**Comment by Magnetkay** [comment]
@elfl0rd  Thanks for the advise ^^

![image](https://user-images.githubusercontent.com/45519359/49331899-ae267e00-f5a4-11e8-98f7-a08052aa287f.png)

This problem had me stumped for a while!

**Comment by keegan-o** [comment]
Main issue resolved by advice, but also to further resolve this the plan to add new forms to old materials is also already another issue.
