### ISSUE TITLE
USER ISSUE: Can't start the game

### ISSUE THREAD

**Issue by htonus** [StrangeLoopGames/EcoIssues#10177]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Generate new world with all checkboxes ticked
2. After all steps passed it shows the gear and does nothing
3. Press ESC and it gives error message - connection lost

**Expected behavior:**
The game started

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection Failed
```

**Comment by htonus** [comment]
Not sure about thew issue. Found created worlds in saved list and managed to start the game.

**Comment by D3nnis3n** [comment]
Does this still happen?

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10321
