### ISSUE TITLE
Remove regional block from game

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10170]
I think it's a really bad "feature".
A lot, really a lot of non-English players can't see servers because the community is too small.
(e.g. german OS lng - game lng is german - no servers on german lng = 0 servers in list.)
They leave negative feedback, the community becomes even smaller. Death circle.

for example a very frequent question
![default](https://user-images.githubusercontent.com/4980243/49327140-4bb28b00-f56e-11e8-9452-c78eee750d5e.png)

In addition, I believed and believe that the forced division of the community is not a good solution.
Translation should not depend on the choice of the server, players playing in different languages - will be able to agree among themselves, as well as it happens in the real world.

**Comment by mirasrael** [comment]
I kept option, but now it doesn't override Language Match filter, but instead used as default.
