### ISSUE TITLE
USER ISSUE: Login Failure

### ISSUE THREAD

**Issue by bobertDobert** [StrangeLoopGames/EcoIssues#10176]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
Create an account
Download ECO
Attempt to log in using ECO credentials (both user name and user ID fail)
Stare at pop-up message in sadness

**Expected behavior:**
it should have logged the fuck on

**Actual behavior:**
The following error message popped up:
Invalid username or password
Invalid username or password.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Invalid username or password
Invalid username or password.
```

**Comment by elfl0rd** [comment]
no answer for a long time.
