### ISSUE TITLE
Hangs on Entering World

### ISSUE THREAD

**Issue by Boartato** [StrangeLoopGames/EcoIssues#10172]
Eco Atlas|server restart due to problem|2x skill points

Currently hangs on entering world. There's a tiny little frame freeze that normally is when the game boots into the world, but then the frames resume and the "Entering World" notification just sits there. Steam updated, files verified.

Not my server, not sure if this is something the server owner can work around.

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
