### ISSUE TITLE
USER ISSUE: Can't login because reasons

### ISSUE THREAD

**Issue by TheNerdPerson** [StrangeLoopGames/EcoIssues#10175]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
LOG INTO YOUR STRANGE LOOP ACCOUNT

**Expected behavior:**
LOGGING INTO THE GAME

**Actual behavior:**
The following error message popped up:
Cannot resolve destination host
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Cannot resolve destination host, and no mods installed
```

**Comment by SlayksWood** [comment]
Checked on 0.8.2.7. Wasn't able to reproduce. If it happens again, please reopen.
