### ISSUE TITLE
USER ISSUE: UI opening with fast typing   

### ISSUE THREAD

**Issue by Echtoplasma** [StrangeLoopGames/EcoIssues#10182]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
Opens at random without doing anything

**Expected behavior:**
Open at command

**Actual behavior:**
Opens sporadically every 20 seconds or son
**Do you have mods installed? Does issue happen when no mods are installed?:**
Opens sporadically every 20 seconds or so

**Comment by elfl0rd** [comment]
check your Z button on your keyboard.

**Comment by Deantwo** [comment]
Try rebinding the Skill Window hotkey to another key.
I suggest `K`, since thst is the default skills button in most other games. `Z` makes for a horrible hotkey.

**Comment by D3nnis3n** [comment]
This happens with several of the menus. Often when i chat and type in the hotkeys they open up.

**Comment by beastyn** [comment]
[0.8.3.1]
Actual with fast typing, when you press enter and hotkey in one moment

**Comment by SlayksWood** [comment]
dup #3522
