### ISSUE TITLE
USER ISSUE: wrong skill points calculation

### ISSUE THREAD

**Issue by InTheNameOfTheEMPEROR** [StrangeLoopGames/EcoIssues#10180]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Start the world in no collaboration mode
2. Learn each specialty step by step
3. Reached 22nd specialty, costs 700 points
(can't guarantee reproduction; haven't proofed on other worlds)

**Expected behavior:**
The cost should calculate like 0, 0, 5, 15, 50, 300, 700 according to eco.gamepedia.com/Specialities

**Actual behavior:**
22nd specialty cost 700 points.
**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed. 
**Screenshots:**
![2018-12-03 1](https://user-images.githubusercontent.com/45568218/49384824-28c5d980-f71c-11e8-9b8b-a60dbd9891b5.png)
![2018-12-03](https://user-images.githubusercontent.com/45568218/49384832-2c596080-f71c-11e8-9b46-e35d69e68c7f.png)

**Comment by InTheNameOfTheEMPEROR** [comment]
Yes but in no collaboration it suddenly shouldn't cost 700 points. My
friend hadn't  this issue. And it completely stagnated like this. I can't
pay 2100 points for my next 3 specialities.

Am Di., 4. Dez. 2018, 04:28 hat D3nnis3n <notifications@github.com>
geschrieben:

**Comment by D3nnis3n** [comment]
I'm not sure if i get the Problem - what did the 21 specialty cost?

**Comment by Deantwo** [comment]
As far as I know the skill point cost of learning a new speciality is a server config option.
Maybe something has changed the file, or maybe a bug in the default. So you need to show what the file contains.
It should be the [`Difficulty.eco`](https://eco.gamepedia.com/Server_Configuration#Difficulty.eco) config file.

**Comment by D3nnis3n** [comment]
Old issue.
