### ISSUE TITLE
[7.9.1 - Update 2] Targeting carved pumpkin is hard

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10189]
You can only target the pumpkin on top, not from the sides, therefore it can be hard to press "e" on it. (There really is no use to open it, but as you can, it should work)

**Comment by D3nnis3n** [comment]
Probably just remove the ability to open them alltogether - we have the desk that has no UI at all - or add a UI to desk, just somehow consistent.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/63576731-809bbd80-c595-11e9-81b6-a6c54a6556ef.png)

**Comment by beastyn** [comment]
Pumpkin fixed in svn. I will make another issue fot UI in some objects
