### ISSUE TITLE
[Master] Election System is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10195]
/leader tells you you were made leader, but you aren't.

Trying to run for election gives you this view:
![election](https://user-images.githubusercontent.com/25908592/49471763-01e7d000-f80e-11e8-9ef5-8ecd45df5502.jpg)

You can't run for office, getting the error seen on top.

Laws seem to work.

**Comment by Quadbro** [comment]
Can't reproduce, cleaned server typed  /leader and pressed run for office
![image](https://user-images.githubusercontent.com/6802030/49693346-9782b700-fba2-11e8-9d78-61155a9d9b18.png)

**Comment by D3nnis3n** [comment]
There was a pull request to fix that up lately.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/Eco/pull/3705

That one i believe.

**Comment by Quadbro** [comment]
yeap
