### ISSUE TITLE
[7.9.1 - Update 2] Mowing Contract does once again not recognize mown grass correctly (The third time!)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10191]
See title and this screenshot.
![grass](https://user-images.githubusercontent.com/25908592/49444319-16f13e80-f7cf-11e8-9c86-5459bbe87f2c.jpg)

**Comment by D3nnis3n** [comment]
"Not ripe enough to harvest"

**Comment by Nicolausi113** [comment]
Should not count as harvest - also #10095 – needs consistent solution

**Comment by Quadbro** [comment]
8.0.4 not reproduced

**Comment by D3nnis3n** [comment]
Cannot reproduce either, closing.
