### ISSUE TITLE
Error dialog is bad

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10196]
![image](https://user-images.githubusercontent.com/3536496/49473709-a8f54900-f7c7-11e8-9d49-5fc4f154d7cf.png)

There's no option to just 'ok' or close it
the buttons are long and look bad
Should look like a normal dialog box.

**Comment by elfl0rd** [comment]
In some cases woll be better removing\hiding report button...
e.g. "server shutting down" and some more connection errors...
