### ISSUE TITLE
sideways pipe ports are dumb 8.0

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10199]
![image](https://user-images.githubusercontent.com/774628/49477278-44d78280-f7d1-11e8-8bd3-29c1fef11034.png)

Previously we moved all chimneys to the top to help minimize sideways pipe port builder issues... we will need pipe port directional variations and an easy way to specify builder rules that change the rule block based on rotation

**Comment by SlayksWood** [comment]
#11838
