### ISSUE TITLE
[Linux] Spammed with LiteException

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#10200]
As per Pam's request - I am constantly being spammed by this message in the console while running on Linux. Ubuntu 18.04, Mono 5.14

Error writing to stat database: LiteException Cannot insert duplicate key in unique index '_id'. The duplicate value is '299061'.

Game.eco and game.db included here:
https://1drv.ms/u/s!Ah1HP-nsGmcYiewf1-5lpredLOCobQ

**Comment by DragonSupremacy** [comment]
Update: removing the db entry in question caused the next value being 299061 showing up as though it was 'duplicate'. I've since removed the entire db

**Comment by beastyn** [comment]
dupe #11882
