### ISSUE TITLE
[8.0.0] Can't launch SP from Client built with IL2CPP

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10209]
Can't launch single player from client built with IL2CPP.  When I attempt to generate new world with random landscape, I get this:
![il2cpp_error](https://user-images.githubusercontent.com/35509188/49543464-2df66600-f88d-11e8-9d74-74c88d7c5ec9.PNG)
Included link to the build.
https://drive.google.com/open?id=1WnOFYrWB6DcFyElFmtMSHmbwUNtfEDF2

**Comment by BlazeGuy2** [comment]
Also including link to IL2CPP built debug info:
https://drive.google.com/open?id=1wVbQOYseqx3CVJlAl2qYUvTlBS4iI7Qg

**Comment by mirasrael** [comment]
Fix for Il2CPP process was dropped in this merge "Merge from staging (#3627) Walker Mansfield* 11/16/2018 03:15"
