### ISSUE TITLE
USER ISSUE: truck fell through the ground and now I can not find it. It also had my skid steer in its inventory and I'm very upset

### ISSUE THREAD

**Issue by McFappington** [StrangeLoopGames/EcoIssues#10201]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
not sure

**Expected behavior:**
truck should not fall through the ground

**Actual behavior:**
truck fell through the ground
**Do you have mods installed? Does issue happen when no mods are installed?:**
I do not have any mods

**Comment by D3nnis3n** [comment]
Try to go to a Real Estate Desk and find it there, then going the the coordinates shown.

**Comment by beastyn** [comment]
We have this one #9248. Close as dupe
