### ISSUE TITLE
Stockpiles, possible trap (art, low prior, funny)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10203]
In current state, stockpiles contain floor without collision, it's allow to create traps. I will be prefer removing "floor" graphics part from stockpile.
![default](https://user-images.githubusercontent.com/4980243/49508139-05716a80-f893-11e8-91c1-ffd217879a2e.png)
![default](https://user-images.githubusercontent.com/4980243/49508151-0e623c00-f893-11e8-86a5-8fd4c6805172.png)

**Comment by elfl0rd** [comment]
@D3nnis3n this more low priority then middle... /unstuck still work and this case is rarely :)

**Comment by Quadbro** [comment]
and what i need to do?) remove floor graphics or add collision to it?)

**Comment by elfl0rd** [comment]
Note: Adding a collision will make using a stockpile painful in some configurations.

**Comment by Quadbro** [comment]
Stockpile bottom graphics is now hidden...

**Comment by Quadbro** [comment]
but now it will be looking strange, when you'll drop objects on air, in your screenshot case)

**Comment by Quadbro** [comment]
> Imo should have collision. That probably would also fix the bug with the grass looking through the floor?

Nope :D wouldn't ))))

**Comment by elfl0rd** [comment]
For me - it's looks better "in general"
![default](https://user-images.githubusercontent.com/4980243/49696377-4979ad80-fbba-11e8-91a1-bea5a90f0e3b.png)

Over hole
![default](https://user-images.githubusercontent.com/4980243/49696390-68783f80-fbba-11e8-84d5-b09a2dbceb99.png)
Approptiate.

Totally in air
![default](https://user-images.githubusercontent.com/4980243/49696433-c0af4180-fbba-11e8-984f-72caa25c3309.png)
![default](https://user-images.githubusercontent.com/4980243/49696447-da508900-fbba-11e8-9042-6d81d9b6e56f.png)
Appropriate, better then fake floor.

**Comment by D3nnis3n** [comment]
Seems okay. Flying stockpiles look bad in any case.

**Comment by elfl0rd** [comment]
> Flying stockpiles look bad in any case

Ofc, but while there are flying blocks, flying objects, etc., it makes no sense to change something specifically for the stockpile. Maybe in future...
