### ISSUE TITLE
[Master] Mint is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10208]
Shows a FakePlant Tab and nothing in its main tab.

![mint](https://user-images.githubusercontent.com/25908592/49541678-cb748880-f8d3-11e8-9aca-cefb928808f4.jpg)

**Comment by Quadbro** [comment]
@johnkslg Did you replace MintUI with AutoViewComponentUI on mint worldobject panel?
