### ISSUE TITLE
QoL: configs need to contain all variables by default.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10202]
In current state, configs looks "empty" untill target variable not changed.
This make config editing before server start, or\and editing configs on dedicaded servers really ugly.

Please, make changes, all configs need to be "filled" by default.

e.g.
"current" stock config.
```
{
  "PublicServer": false,
  "Password": "",
  "Description": "",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 10,
  "MaxConnections": -1
}
```
"full" config.
```
{
  "PublicServer": false,
  "Playtime": "",
  "DiscordAddress": "",
  "Password": "",
  "Description": "",
  "DetailedDescription": "",
  "ServerCategory": "Beginner",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 10,
  "MaxConnections": -1
}
```

**Comment by mirasrael** [comment]
We are trying to avoid default configs, because they produces a lot of head ache when changing locally during development with dev env specific values, but we can add template files for each config. So it will be easy enough to copy template and change everything if you want to pre-configure server manually.

**Comment by elfl0rd** [comment]
> template files
good solution too!

**Comment by beastyn** [comment]
As I see.
Templates files don't contain all fileds.
{
  "PublicServer": false,  
  "ServerCategory": "None",
  "IPAddress": "Any",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 20,
  "MaxConnections": -1,  
  "UPnPEnabled": true
}

As I understood, users should be able to fill .eco config with example from template file.

**Comment by mirasrael** [comment]
@beastyn can you check every template, find missing config values, add them and ensure they're working as expected when in the template? You can find all config keys in Plugin config objects.

**Comment by beastyn** [comment]
@mirasrael 
and while Im doing this I have a question.
Im an admin who wants to make some pre-changes in Difficulty. I have everything in template, but I shouldn't use template, but .eco. Thing is, I don' have a Difficulty.eco file
What should I do?
