### ISSUE TITLE
Wheelbarrow moves in X and Y axis according to the origin location when moving

### ISSUE THREAD

**Issue by ManuHeel** [StrangeLoopGames/EcoIssues#10211]
Hi Devs,

I'm using 7.8.5 with friends.
Once the wheelbarrow has been placed in the world, it looks like it's storing it's original location, then does not move forward and backward according to the direction it's facing butin the direction of the absolute X and Y axis. Here is a video I captured, only moving with W and S, forward and backward.

https://youtu.be/iB4v4_cSFdo

I moved backward then forward, but it only translates on the global X and Y axis, thus not moving on the wheelbarrow directions.

**Comment by Ruined1** [comment]
Can confirm identical behavior in 0.7.8.9 beta.

**Comment by SeanAtr0n** [comment]
fixed in svn, you can also now go up some blocks
![wheelbarrowop](https://user-images.githubusercontent.com/774628/52508895-fcf72200-2baa-11e9-8d9e-53ae8b0bad88.gif)
