### ISSUE TITLE
USER ISSUE: Everyone gets disconnected at the same time randomly and more... (VPS Server)

### ISSUE THREAD

**Issue by MrManvi** [StrangeLoopGames/EcoIssues#10216]
Hey so I'm having an issue for quite a while now. We bought a VPS to host a Eco Server with specs (for information):
**Intel Core Xeon X5670 @2.93GHz (8 Cores)
16GB RAM
Windows Server 2016
100mbps up and down speed. 
NOTE: We already have .NET 4.7.2 Framework installed. EcoServer Version: 0.7.8.5. NO MODS INSTALLED**
Now the main issue is that Players constantly get disconnected from the server at random intervals of time. and get disconnecting symbol (red wire) alot of times. Now after we monitored the Server PC (the vps) and Client PC for investigating into the random disconnections. It seems that Server PC is totally normal and has no crashes, no data surges, no CPU or Memory usage going up or down at all it stays the same. Whereas, the client gets a data surge when the disconnection happens, at times the surge can be critical by taking all of Client's RAM as well as Disk and may Freeze or Crash not only the Game but also the entire System (This has happened twice to me). Also a point to note, The ecoserver has never crashed whenever the disconnections have happened and we have no dump files to investigate... Also, when people gets disconnected, they can usually come back in a few seconds. But at times the server is hidden from the browser list as well as direct connect will not work for a few mins as if the ecoserver is down. But it is totally up and running. 
I've contacted Pam from the discord server She gave me a few tips and asked to run a 200x200 world along with some other tips, we've applied them and we have the same issue but the disconnections don't have so constantly anymore but they are still a thing and happen on an average around every 30-60 minutes. 
Another point that I've noticed today is that: The server stopped loading textures for me, I tried to go to another online user's location and server/game couldn't load any textures, animals beyond a point. Whereas we were able to use the chat and other stuff. Restarting helped this
Still stuck on this issue, sorry for making a huge long thread about this issue. I've been told that its mostly because its a VPS. I'd like to see some VPS optimizations being done in future updates since they're one of the affordable ways to run game servers all the time.

**Comment by mirasrael** [comment]
No response. Closed.
