### ISSUE TITLE
Master: strange pipes in Liquid Converter

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10227]
Pipes orientation static, and not changed by main object orientation)
![default](https://user-images.githubusercontent.com/4980243/49626884-e71f8200-f9ec-11e8-8746-9b6c327bd13b.png)

**Comment by elfl0rd** [comment]
maybe refers to this https://github.com/StrangeLoopGames/EcoIssues/issues/10199

**Comment by johnkslg** [comment]
@keegan-o can you remove the meshes from PipeSlotBlock?

**Comment by elfl0rd** [comment]
closing, looks as fixed.
![default](https://user-images.githubusercontent.com/4980243/49922629-53edbd00-fec2-11e8-9862-bed99be5665e.png)
