### ISSUE TITLE
Master: QoL pump (pipes) connection to water

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10221]
You cannot "just place and go" for now
![default](https://user-images.githubusercontent.com/4980243/49612626-5a59d180-f9b6-11e8-9671-a8049ce3b797.png)
Not work...

You need create some pipes structure...
![default](https://user-images.githubusercontent.com/4980243/49613306-6181df00-f9b8-11e8-80e0-be9d3f7454a0.png)

**Comment by elfl0rd** [comment]
I think adding a 90 degree turn as one of pipe form (shift) will be part of the solution.
Second part of the solution, replace "fixed linear" pump in point to "linear or 90" (in my thoughts) if no pipes connected and water source under in point part - in point part rotate 90 and connect to water source.

**Comment by johnkslg** [comment]
Just build the pipe down into the water :)  Closing for now

**Comment by elfl0rd** [comment]
> Just build the pipe down into the water :) Closing for now

Nice idea! But you get this:
![default](https://user-images.githubusercontent.com/4980243/49849034-e3bf3880-fde8-11e8-8e36-17b0c0fb2de0.png)
in some cases.

90 degree pipe form is ideal solution as i see.

**Comment by johnkslg** [comment]
Ah, because the water is only one layer deep. Makes sense. I could do an easy fix for that. Making water look nicer around pipes will be a tricky affair though.

**Comment by elfl0rd** [comment]
> Making water look nicer around pipes will be a tricky affair though.

I know this, this is why i want connection to water surface, heh :D

**Comment by elfl0rd** [comment]
Suggestion about pipe forms - https://github.com/StrangeLoopGames/EcoSuggestions/issues/647

**Comment by Deantwo** [comment]
A specific "water intake" pipe type (assuming StrangeLoopGames/EcoSuggestions#647) would likely make more sense than just a pipe pointing at the the water surface.

**Comment by johnkslg** [comment]
Closing this one, its not that hard to direct it to the water
