### ISSUE TITLE
Server not stored in recent list when direct join with IP and port

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#10223]
Server not stored in recent list when direct join with IP and port

Eco Version: v0.7.8.5-beta

Steps to reproduce:

1. Delete file: \AppData\LocalLow\Strange Loop Games\Eco\recentServers.eco
2. Main menu ->Your worlds -> + -> Enter IP and Port -> Join Server -> Leave Server -> Your worlds

Some things which I found out:
Class: Eco.Shared.Networking.NetworkClient
Around `Line 120`:

```
 if (this.client.ConnectionStatus != NetConnectionStatus.Connected)
                    throw new NetException();

 return true;
```

`this.client.ConnectionStatus` is None

In AddServerUI.cs

the `if (BehaviourSingleton<NetworkManager>.obj.Connect(text, num))` evaluates to false

which results in a log entry: `Invalid ip address`

I think this is a timing issue, because the connection is not established when checking the `ConnectionStatus`, because I got it randomly working when adding some breakpoints.

**Comment by mirasrael** [comment]
Both fixed in next version.

**Comment by lordmampf** [comment]
thanks!
