### ISSUE TITLE
Table requirements UI bug ? 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1023]
http://ecoforum.strangeloopgames.com:4567/topic/1318/5-3-bug-reports

**Comment by MarjieAVolk** [comment]
From the thread:
 ![image](https://cloud.githubusercontent.com/assets/23460210/24174561/79ab9e10-0e4e-11e7-89bd-11e3819674e6.png)

**Comment by Fank** [comment]
@MarjieAVolk haven't seen such issue in alpha.6

**Comment by metachronism** [comment]
long since fixed
