### ISSUE TITLE
Master: /spawnpipes broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10231]
after models change. Pipes not connected.
Looks same as https://github.com/StrangeLoopGames/EcoIssues/issues/10220

![unknown](https://user-images.githubusercontent.com/4980243/49675973-eb997880-fa88-11e8-9b10-3d9532209755.png)

**Comment by BlazeGuy2** [comment]
Yeah, pipes changed, I'd need to rewrite the tests.
