### ISSUE TITLE
Master: palm provide birch seeds.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10236]
https://github.com/StrangeLoopGames/Eco/pull/3727
![default](https://user-images.githubusercontent.com/4980243/49685797-25a36280-fafb-11e8-94b4-eff5c99b72d5.png)

Maybe this happens by "no redwood\palm seeds\saplings in game"

**Comment by elfl0rd** [comment]
@D3nnis3n merged, but for palm is not fixed.
![default](https://user-images.githubusercontent.com/4980243/49921792-c27d4b80-febf-11e8-9c16-048edb970cc0.png)

Redwood - fixed.
![default](https://user-images.githubusercontent.com/4980243/49921869-fe181580-febf-11e8-897b-85e64cb9883f.png)

**Comment by D3nnis3n** [comment]
Reopened and renamed.
