### ISSUE TITLE
Master: /testdistributionstation cause break

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10238]
> System.InvalidOperationException
>   HResult=0x80131509
>   Сообщение = Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
> Not enough room in inventory
> Not enough room in inventory
> Not enough room in inventory
>   Источник = Eco.Gameplay
>   Трассировка стека:
>    at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 702
>    at Eco.Gameplay.Items.InventoryChangeSet.Apply() in D:\DevelopECO\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 633
>    at Eco.Gameplay.Items.Inventory.AddItems(IEnumerable`1 stacks, User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Items\Inventory.cs:line 1224
>    at Eco.Gameplay.Items.InventoryUtils.ApplyRandomInventory(Inventory inv, Int32 itemTypes, Nullable`1 carried, Int32 maxCount) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Items\InventoryUtils.cs:line 23
>    at Eco.Gameplay.Components.ItemDistributionComponent.TestDistributionStation(User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Components\ItemDistributionComponent.cs:line 119

> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Сообщение = Адресат вызова создал исключение.
>   Источник = mscorlib
>   Трассировка стека:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 386
>    at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 263
>    at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 543
>    at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 517
>    at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, Int32 playerID) in D:\DevelopECO\Eco\Server\Eco.Gameplay\Systems\Chat\ChatManager.cs:line 511
> 
> Внутреннее исключение 1:
> InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
> Not enough room in inventory
> Not enough room in inventory
> Not enough room in inventory
>

**Comment by elfl0rd** [comment]
As i see Distribution Station no more accept lot of items.

**Comment by Quadbro** [comment]
Fake plant issue too.
