### ISSUE TITLE
[Master - Steam] Objects start fly when you look at them from above

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10249]
![flying](https://user-images.githubusercontent.com/25908592/49733477-ea7f6b80-fc81-11e8-8a86-275655170a42.jpg)

The higher you get the higher the objects fly - pipes stay where they are.

**Comment by elfl0rd** [comment]
Missed curved shader, hehe :D

**Comment by keegan-o** [comment]
Fixed in master.
