### ISSUE TITLE
[QoL] repair station: usability

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10248]
(if this fast - please, if not - low prior\mark as suggestion)
1) Expang "item for repair" accept zone, like inventory (Quadbro changes)
2) Add support "click to move" (in both cases, from inventory to repair slot and from repair slot to inventory), like inventory (Quadbro changes)
3) Add button like "Repair and pickup" - repair item and grab it back to inventory.

4) maybe not easy.
I believe that the cost of repair should be displayed by the player watching.
Not the player who put the instrument down.
(Current) if a player without efficiency puts the instrument on the table, but if another player fixes it with efficiency - efficiency will not be applied.
In my mind, next behavior is ok
Player 1) - no effectiveness.
Puts down the tool, sees the cost of repairing 8 bars and a footnote that the presence of a blacksmith's profession will reduce the cost of repair.
If he fixes it - 8 bars are consumed
Another player 2) - blacksmith, sees the cost of repairing 5 bars and a footnote that the repair without efficiency will cost 8)
If he fixes it, five bars are used.

**Comment by Deantwo** [comment]
And show skill benefiting the repair while an item is in the repair station, and its effect on material cost.
See: #10246

**Comment by elfl0rd** [comment]
> And show skill benefiting the repair while an item is in the repair station, and its effect on material cost.
It's 100% requie a lot more time :)

**Comment by elfl0rd** [comment]
Can this have some love? :)

**Comment by LWChris** [comment]
Copying over from #968:

> Since the table does nothing else, it would be even cooler to have a keyboard shortcut (e. g. "R" key) to repair the currently active tool while looking at the table without even having to open the table's interface. Press E to open, R to repair current tool for whatever it costs. Then you could just stand in front of the table, use the mouse wheel to scroll through the toolbar and press R when you want to repair that tool.

At least that would be my common use case for a long time early, when the repair cost is merely "5 stone" etc.

**Comment by WeaselDog** [comment]
Suggestion from linked issue:
> Tools and bench upgrades do not have the same shift+click functionality that most other resources have... Can it be changed so tools can be shift+clicked into the repair slot, and back to your backpack? Also is it possible to add the shift+click functionality to the upgrade slot?

I think this is the behavior we want, but to work with left-click. If it works with shift+click too, that is great.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 279
