### ISSUE TITLE
[Master - Steam] Skillsystem - UI misplaced

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10251]
When you open the skill UI it looks like this until you resize the window a little bit to get the view you should get.
![skillsystem](https://user-images.githubusercontent.com/25908592/49734860-e9e8d400-fc85-11e8-9be6-9ed9b841c25f.jpg)

**Comment by elfl0rd** [comment]
Addition to UI problems
"experience bar"
