### ISSUE TITLE
[Master - Steam] Bad Performance

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10254]
https://www.godsofwar.de/eco.mp4

Full HD, none of the features on the right side activated.
Medium settings on the left side for leaves and render distance.
Maxed out the rest

RTX 2080 + Ryzen 2700X on 64 GB of RAM. 
417.22 Drivers

~40 FPS. Nope, that won't work.

**Comment by elfl0rd** [comment]
video from game launched from RAM storage, you can see periodic freezes for short time.
https://www.dropbox.com/s/dnvblshoh4n33sy/20181210234212.ts?dl=0
no fps issues, no fps drop on external tracker, this is "ingame" problem.

**Comment by elfl0rd** [comment]
Maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10136

**Comment by D3nnis3n** [comment]
It does, but got even worse.

**Comment by SeanAtr0n** [comment]
I don't expect that would fix the skipped frames themselves though... maybe @metachronism has ideas

**Comment by metachronism** [comment]
lots of the graphics settings changed with higher maximums, specifically foliage quality and others.  you arent expected to run the game at max settings and max fps

**Comment by D3nnis3n** [comment]
It doesn't work either when you set the settings to ultra-low and see only pixel-mud - fps drops occur at the same frequency and lag is the same. In any case the mid-settings already are not that good looking, so they should be absolutely fine for a 2080 RTX. I already proposed on some other place to offer some default settings like "Low, Mid, High" as choosing a working graphics setting is very hard in this game.

But performance just got extremely worse and needs to be adressed in some way.

**Comment by metachronism** [comment]
too generic an issue.  we are always monitoring performance and making adjustments
