### ISSUE TITLE
USER ISSUE: Гладиатор ПВНЗ

### ISSUE THREAD

**Issue by 228vak** [StrangeLoopGames/EcoIssues#10256]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
10

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Access to the path "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\DefaultWorld" or "C:/Program Files (x86)/ Eco/Eco_Data\Server\Storage\Валера Гладиатор .eco" is denied.
```

**Comment by BlazeGuy2** [comment]
@228vak Please update to the latest version 7.8.5 either on http://www.strangeloopgames.com/eco/ or update from steam.
