### ISSUE TITLE
[Master - Steam] After reloading the world all tree branches and leaves are gone

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10252]
Everything is fine when you create the world. But as soon as you reload the world it looks like this:
![trees](https://user-images.githubusercontent.com/25908592/49735080-7bf0dc80-fc86-11e8-81d2-3c9e92bd1b19.jpg)

**Comment by BlazeGuy2** [comment]
@D3nnis3n Can't seem to reproduce this in Unity.  Can you narrow down what causes this?

**Comment by D3nnis3n** [comment]
Still happens on most recent master build for steam.

**Comment by elfl0rd** [comment]
I can confirm, this happens only in builded 0.8 branch in steam.
first login
![20181211092624_1](https://user-images.githubusercontent.com/4980243/49782552-c2e2de80-fd27-11e8-9328-9515122adab6.jpg)
second login
![20181211093157_1](https://user-images.githubusercontent.com/4980243/49782557-c8d8bf80-fd27-11e8-8230-4976512d4588.jpg)

logfile
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2666271/output_log.txt)

**Comment by D3nnis3n** [comment]
Thanks for reproducing GDragon. @BlazeGuy2 Probably only happens on the steam build.

**Comment by elfl0rd** [comment]
Mirasrael got this in unity :D

**Comment by elfl0rd** [comment]
As i see it fixed :)

**Comment by D3nnis3n** [comment]
Yep, does no longer happen for me, either.
