### ISSUE TITLE
[Master - Steam] Skillsystem - Tooltips and Art missing

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10250]
![skill](https://user-images.githubusercontent.com/25908592/49734781-bb6af900-fc85-11e8-801c-ced970376550.jpg)

**Comment by D3nnis3n** [comment]
Oh yeh, and it should neither be casting nor should it casting be where it is.

**Comment by elfl0rd** [comment]
And addition, as i know some skills removed from game, but persist in this interface.
Campfire, etc...

**Comment by johnkslg** [comment]
Fixed with PR #3845
Icon setup is tracked here. https://github.com/StrangeLoopGames/EcoIssues/issues/10698

**Comment by elfl0rd** [comment]
Fixed with PR https://github.com/StrangeLoopGames/Eco/pull/3845
