### ISSUE TITLE
USER ISSUE: Disconnected after putting stone into storage

### ISSUE THREAD

**Issue by iceman11a** [StrangeLoopGames/EcoIssues#10255]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
Mined some stone and tried to put it into storage and it just disconned for some reason	

**Expected behavior:**
It shouldn't have disconnected for any reason that I know of. 

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by BlazeGuy2** [comment]
@iceman11a Does this occur every time you put stone in storage?

**Comment by iceman11a** [comment]
No, as a matter of fact. I took some game time off and I log in later and it stopped. So I have no idea why it was doing this. I do play this game for long hours. 2 to 5 hours a day. This happen when I logged in when no one else was on. Game play seemed fine.

**Comment by SlayksWood** [comment]
Do you have this problem now?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Close as its not reproducable with 8.2
