### ISSUE TITLE
Need more info on XP popups

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10269]
I'd like to make this graphical, but in the meantime we can just improve the text here.  Should say which workorder youre advancing, what kind of XP youre gaining, and how much longer to the next level up, all with UILink tooltipable text.
![image](https://user-images.githubusercontent.com/3536496/49826730-79e95500-fd3c-11e8-9301-f06386df7c1d.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/49827626-9b4b4080-fd3e-11e8-919b-58ff1d0c8457.png)
These also get pretty spammy since they show everytime an order finishes one thing. Should just show when the order completes.

**Comment by craig-jong** [comment]
This was fixed (but also it's getting replaced anyway.)
