### ISSUE TITLE
Client Memory Slow Leak  A5.3

### ISSUE THREAD

**Issue by Imricdaelf** [StrangeLoopGames/EcoIssues#1026]
Alpha 5.3 x64 Client
Connected to a PingPerfect server
Windows 7 SP1

Problem:
RAM useage by ECO.exe slowly increases over time until all memory is in use by ECO and client eventually freezes requiring a process termination (if computer manages it, entire system becomes bogged down.)

Reproducible for me every time client runs in this patch.

Description:
Eco starts at 300 MB RAM useage, and sits at 2.2 GB RAM useage while idling after initial connection to server and has loaded 100%. Over time the commited memory will creep higher and higher until no memory is left to take. Approximately 2 GB of RAM increase per hour, culminating in a noticeable decrease in performance and noticeabl sluggishness after approximately four hours, nearing my systems hardcap of 12 GB. After approximately six hours of continuous play, no memory was left available and the client finally became unresponsive, requiring a force quit and process termination.

System Paging file was NOT used by Eco to my knowledge.

Unknown as to cause of increase, I will watch it as I play to find out.

**Comment by noblackthunder** [comment]
dub https://github.com/StrangeLoopGames/EcoIssues/issues/990 Just keep adding your info here so we dont have many of the exact same issues in several issue post . Github has a search function :)

**Comment by Linrox** [comment]
Is there any progress on fixing the leak?
