### ISSUE TITLE
Incorrect tool durability display when dropping icon on another

### ISSUE THREAD

**Issue by ayan4m1** [StrangeLoopGames/EcoIssues#10265]
When a tool with full durability is drag-dropped onto another tool with non-full durability, the durability value _appears_ to be "copied" onto the source item. If you then drag-drop the source item onto a blank inventory slot, the durability visually reverts back to its correct value. This also seems to be able to occur in reverse - that is, dropping an item with durability onto one with full durability causes the destination item to gain the durability of the source item.

Here is a short video showing this issue (both copy-to-source and copy-to-destination):
![test](https://user-images.githubusercontent.com/266545/49803005-9c6b7600-fd1c-11e8-9a64-8a9674ece391.gif)

If the user disconnects and reconnects, the durability values for all tools seem to be visually reverted back to their correct values. 

I am running Windows 10, version 0.7.8.5 beta. Please let me know if you need more information to diagnose or reproduce this issue.

**Comment by beastyn** [comment]
[0.8.1.3]
Still an issue. Actually broblem is only with tools without durability (soil sampler, land claim stake). Durability bar just stick to them, uts cosmetic.
Tools with durability behave fine,
