### ISSUE TITLE
Master: no info on screen about player movement speed penalty in large plants

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10262]
This is not critical but i think it is not very right not to display any information about speed is reduced (and why it happened)

**Comment by D3nnis3n** [comment]
When on roads a speed bonus is shown - why not show it on plants?

**Comment by SeanAtr0n** [comment]
Vehicles now display the speed reduction due to plants so you can drive a cart through plants if you really want this info.

I don't think we will be showing that info while walking around though as we already suffer from information overload.
