### ISSUE TITLE
5.3 Elk keep appearing and getting stuck on roof

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1027]
![20170110100653_1](https://cloud.githubusercontent.com/assets/15990789/21813701/baf8f75a-d71c-11e6-8994-55f52d727a28.jpg)

they go up there or they spawn up there and that is where they sit for ever been 3 days now and they just end up with more and more

they all end up pulling same head shake animation over and over and run around roof and cant get off.

**Comment by tbbw** [comment]
To add so animals cannot spawn ontop of player created blocks would solve this.
But then again some of the crazy acrobatics iwe seen the animals do the elks could probobly jump up there and then never jump down.
