### ISSUE TITLE
[8.0.0] Highlighting in stockpiles is incorrect

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10274]
![highlightwrong](https://user-images.githubusercontent.com/35509188/49839453-f17eaa80-fd63-11e8-8c96-fe63a8ee7c29.PNG)

**Comment by BlazeGuy2** [comment]
![2](https://user-images.githubusercontent.com/35509188/49839476-0f4c0f80-fd64-11e8-9e64-509ac3f42fd8.PNG)

**Comment by redwyre** [comment]
Rubble is incorrect in the large stockpile too 
![image](https://user-images.githubusercontent.com/431728/49839669-cf386b80-fdfb-11e8-9575-ccd6f901f783.png)

**Comment by redwyre** [comment]
The starter stockpile seems to be only highlighting one blocks worth
![image](https://user-images.githubusercontent.com/431728/49839826-859c5080-fdfc-11e8-8d1f-e59ebba1484c.png)

**Comment by BlazeGuy2** [comment]
Couldn't repro in unity at all, dropping pri for now.

**Comment by redwyre** [comment]
Been trying to repro this, here's what I've got:

Got messed up dirt in this tiny stockpile, here you can see the highlight showing off the decorator meshes
![image](https://user-images.githubusercontent.com/431728/50646509-00065d80-0fc2-11e9-9d94-a086a9afb359.png)

The generated mesh itself is just square edges:
![image](https://user-images.githubusercontent.com/431728/50646571-26c49400-0fc2-11e9-8f9f-25d091db4a71.png)

**Comment by redwyre** [comment]
The issue with the stockpile highlighting outside of itself was fixed a while ago.
The issue with mismatching highlighting for non-stone blocks is fixed with the pr.
The issue with stone blocks is yet unfixed, but I'll track that in another issue.
