### ISSUE TITLE
[8.0.0] Claimed land didn't update in client

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10276]
It's not highlighted, but when I try to claim it, it says I already have. (I may have claimed it while looking at the stockpile, not sure)

https://drive.google.com/file/d/1O6acq8j-MZpssQ_nHeZ5by_iDmuG2fDZ/view?usp=sharing

**Comment by redwyre** [comment]
Unclaiming it an then claiming it again had no visual effect, however re-logging into the server fixed it.

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/8827

**Comment by redwyre** [comment]
Also #9607

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10286
