### ISSUE TITLE
[8.0.0] Big trees fly off when chopped down

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10277]
https://drive.google.com/open?id=1NFIenBowh1u6-NfMA907ymWlgnwxJ9XK

**Comment by BlazeGuy2** [comment]
Couldn't get this to repro on master.

**Comment by redwyre** [comment]
They might have to be maximum maturity, I don't think it happens with the thinner ones.

**Comment by seccombew** [comment]
@redwyre Are you still able to repro?

**Comment by redwyre** [comment]
Looks like it https://drive.google.com/open?id=1PuzubVBdx31fYhuhOspCDZAT0C5tgj6U

**Comment by D3nnis3n** [comment]
From #10578

**Comment by seccombew** [comment]
Fixed by @metachronism
