### ISSUE TITLE
[8.0.0] Trees leaves spiral out when it rolls

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10275]
Difficult to see in the image
![image](https://user-images.githubusercontent.com/431728/49839611-939da180-fdfb-11e8-8ee4-6c3cb8a7bfa6.png)

https://drive.google.com/file/d/1sUz2pYaQCqzD1q07_rJhrNMTw9tFGKTt/view?usp=sharing

**Comment by BlazeGuy2** [comment]
Issue with fir tree spiral branch.

**Comment by BlazeGuy2** [comment]
https://youtu.be/HeGjBaD_zBo

**Comment by keegan-o** [comment]
We're going to be preventing the player from chopping off one branch at a time with the fir-- I added large trigger colliders to the leaves so they can explode when the tree dies, but we will need code to prevent you from cutting off branches.

**Comment by SeanAtr0n** [comment]
seems to behave fine w/ keegan's changes, chopping off branches is also reasonable
