### ISSUE TITLE
Master: broken plots

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10289]
After you make somethings, closest plots periodically corrupted. Still happens after relogin and server restart.
![default](https://user-images.githubusercontent.com/4980243/49863742-fc901400-fe11-11e8-8913-100143514dc6.png)
![default](https://user-images.githubusercontent.com/4980243/49863770-103b7a80-fe12-11e8-818e-f550ec1ad35e.png)
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2671515/Storage.zip)

**Comment by redwyre** [comment]
So looking into this, the blocks that are missing are part of a stockpile, and stockpiles have had a number of improvements so this may be already fixed.
Have you experienced it since then?

**Comment by elfl0rd** [comment]
no, this happens also with pipes constructions and with "free" from changes plots.

**Comment by elfl0rd** [comment]
got a repro, fresh master...
![default](https://user-images.githubusercontent.com/4980243/50738598-be0a3100-11e6-11e9-94cd-31bcd1879267.png)
![default](https://user-images.githubusercontent.com/4980243/50738620-0de8f800-11e7-11e9-9685-3f69882253a3.png)
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2730633/Storage.zip)

**Comment by redwyre** [comment]
Thanks, was able to repro from that, the work I did for stockpiles fixes it too.

**Comment by elfl0rd** [comment]
nice.

**Comment by elfl0rd** [comment]
Fresh master...
After i use `/spawn mint` i got corrupted plot.
![default](https://user-images.githubusercontent.com/4980243/50827176-d2693d80-134e-11e9-8bfb-8a95e982a5b0.png)
In unity console
```
Exception building chunk (17 7 79): System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at MeshData.RemoveUnusedVertices () [0x0004d] in D:\DevelopECO\Eco\Client\Assets\VoxelEngine\Core\MeshBuilder.cs:143 
  at ChunkBuilder.Build (ChunkRender chunk) [0x00a18] in D:\DevelopECO\Eco\Client\Assets\VoxelEngine\Core\ChunkBuilder.cs:612 
  at ChunkRenderer.Build () [0x00023] in D:\DevelopECO\Eco\Client\Assets\VoxelEngine\Core\ChunkRenderer.cs:407 
  at ChunkRenderer+ChunkJobQueue.WorkerThreadProc () [0x00047] in D:\DevelopECO\Eco\Client\Assets\VoxelEngine\Core\ChunkRenderer.cs:313 
UnityEngine.Debug:LogError(Object)
ChunkJobQueue:WorkerThreadProc() (at Assets/VoxelEngine/Core/ChunkRenderer.cs:338)
System.Threading.ThreadHelper:ThreadStart()
```

**Comment by elfl0rd** [comment]
Happens with `/spawnbuilding` too

**Comment by redwyre** [comment]
Looks like I accidentally reverted part of the fix I made for it, got a new fix waiting
