### ISSUE TITLE
5.3 bug tree stuck above cart - cart stuck - tree flying into space bug

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1028]
this all seem to happen at one time,

I cut down tree A which land above my ramp and my cart it also landed in anther tree call that tree B

I cut down tree B thinking that fix the tree A flying in air.

it did not

every time i try to chop  tree A that part flys off into space 

and my cart is stuck cant move it anywhere or pick it up.

in the picture you can see tree A 
Tree B is gone
and you can see part of tree A flying off into space
you can also see my cart where its stuck
![20170110114121_1](https://cloud.githubusercontent.com/assets/15990789/21817584/2f994012-d72a-11e6-8c9e-9b4e5f424f26.jpg)

**Comment by midn8t** [comment]
I figured out what caused this when i went back on to server i removed my ramp and under my ramp i had use dirt road blocks to put the dirt ramp on.
when i remove the dirt ramp and dirt road both the cart reappeared - the tree fell out of the sky and the log came crashing down on my house.

**Comment by SeanAtr0n** [comment]
Should be fixed in 5.5
