### ISSUE TITLE
No way to change talents

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10285]
For now, we can see 2 group of talents.
1) good for beginners, e,g, "Lowers the tier requirement of related tables"
2) good for "experienced" e.g. "Increases the tier requirement of tables by 0.2, but reduces the resources needed by 10 percent."

Without ability to change talents (maybe just drop specialization XP after change? e.g. -3 lvl...) group 1 used only by newbie players.

**Comment by BlazeGuy2** [comment]
@craig-jong ^

**Comment by craig-jong** [comment]
It's removed. I'm since a lot of stuff has had their requirements removed, I think it should be fine.

May re-evaluate as we test the system.

**Comment by elfl0rd** [comment]
@craig-jong In this case, you need to add an irreversibility warning to the confirmation window.
Otherwise you receive ALOT of whimpers after update.

**Comment by elfl0rd** [comment]
In addition... What about beginners? How to be with those who cultivate civilisation on the server from scratch?
They'll all just leave the servers... I do not find this change useful, it is harmful :(

**Comment by Deantwo** [comment]
I am not sure if talents will cost a star or not, but if they will it wouldn't be unreasonable to allow changing a talent at the cost of another star.

**Comment by elfl0rd** [comment]
edited, still actual.
In addition i see too many questions about it after 0.8 available for testing.

**Comment by D3nnis3n** [comment]
Removing Priority and adding suggestion label, this is intended behaviour, as Craig already stated.

**Comment by elfl0rd** [comment]
This is result of playtesting, users prefer t2 talents.

**Comment by craig-jong** [comment]
We'll consider a few options for talent changes in the future, but not for 8.1 Can expect them in 9.0, though.

**Comment by Deantwo** [comment]
Milestoned and not fixed/implemented.
