### ISSUE TITLE
[8.0.0] Scrolling or changing the content of the chat window results in icons flashing on the screen

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10283]
https://drive.google.com/file/d/1hEwlIsGTY82hpZMGFWAqXC-UQ7VN9UDH/view?usp=sharing

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/8290

**Comment by beastyn** [comment]
copy of #8290
actual in 0.8.1.3

**Comment by Spydarlee** [comment]
Can't reproduce this anymore - seems to have been fixed in one of the recent-ish chat UI overhauls.
