### ISSUE TITLE
[8.0.0] Invisible wood

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10281]
Has collision (steps on top of it)
![image](https://user-images.githubusercontent.com/431728/49847562-85ac4880-fe1c-11e8-861e-14abfec98853.png)

**Comment by redwyre** [comment]
Actually I think it was a stump, relogging removed it (net sync issue?).

**Comment by elfl0rd** [comment]
old issue. https://github.com/StrangeLoopGames/EcoIssues/issues/4107

**Comment by BlazeGuy2** [comment]
closing as dup
