### ISSUE TITLE
[8.0.0 and below] USER ISSUE: Land Claim Issues

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#10286]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1. Select your Land Claim Stake
2. Go stand on the plot of land you want to claim
3. Right click on the plot of land to claim it.

**Expected behavior:**
That it would go the same color that I have set which is red 
for that plot. 	

**Actual behavior:**
Instead it is staying the same ground color instead of going
red but it insists that I already own that plot if I try and own it a it again it 
it says that I already own that plot. But it refuses to go the same color as the rest
of my plots which I have set to red.

I don't know why and Yes I have tried to unown it and then reown it again with
the same results it won't turn red like the rest of my plots when I have 
my land stake tool selected and I don't know why. I believe this to be some kind of
bug with the game at this point because I have tried everything even unowning it
and then reowning it and it does the same thing!  It just won't turn red.

Now if I stand on the plot and look down and hit E it is listed as me owning it
but why isn't it red like the rest of my plots when  I have my land select tool 
selected. 

Now in the screenshot you can see that I am not standing on it and I did that
on purpose for the screenshot so it wasn't yellow and you can see that 
the plot is just the normal ground color and yes I have my Land Claim Stake
tool selected as you can see all the other ones around me are all red except that 
one.  This is maddening why is it doing this with this one spot. 

This is my own server FYI running on a machine that I have here 
as a test server that I play around with.  Never saw this before 
it has never done this in the past just with this version. 

A copy of the image can also be seen at https://ibb.co/1zy107k

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have no mods installed. 

![land claim issues eco dec 11 2018](https://user-images.githubusercontent.com/38896397/49851346-11cb5b00-fd9e-11e8-94af-fe38d6f1cd25.jpg)

**Comment by redwyre** [comment]
As a workaround, if you log out and back in the claims should appear correctly.

**Comment by D3nnis3n** [comment]
Happens on 8.0, too - just merged the duplicate issues into this as it has the best description.

**Comment by thereporter42** [comment]
Why did this ticket get closed? It appears that all the other ones #8827 and 10276 are also 
all closed but I don't believe the issue is resolved.

**Comment by D3nnis3n** [comment]
The issues have been merged.

**Comment by johnkslg** [comment]
@SeanAtr0n @Quadbro I think this is related to a bug I found where the minimap was caching view data sent from the client instead of setting it up, while some other system needed it. I fixed that awhile back, and it should be better now.  See if this still repros?

**Comment by elfl0rd** [comment]
:D nope! got it on a fresh master.
![default](https://user-images.githubusercontent.com/4980243/51517603-58e04d80-1e2c-11e9-9fc8-ab5da28a0b65.png)

**Comment by SeanAtr0n** [comment]
you seem very happy about this... if you get it to happen again can you upload your log file?

**Comment by SeanAtr0n** [comment]
Found the problem... looks like the

**Comment by elfl0rd** [comment]
ofc) client log?

**Comment by elfl0rd** [comment]
Staging
![20190123194902_1](https://user-images.githubusercontent.com/4980243/51622647-0b590300-1f48-11e9-99e8-31938f6c25f4.jpg)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2788294/output_log.txt)
