### ISSUE TITLE
[8.0.0] No Crimini mushrooms

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10288]
There are no Crimini mushrooms around, but they are required for the Farming skill book.

![image](https://user-images.githubusercontent.com/431728/49854789-0d06b580-fe37-11e8-9304-3afd4ef9997a.png)

> Craig Today at 17:52
> Its more of a bug that Wetlands doesn't exist anymore

**Comment by D3nnis3n** [comment]
Crosslinking https://github.com/StrangeLoopGames/EcoIssues/issues/9955

I couldn't test yet on master but on my QA tests it frequently happens on the current release versions with NO special settings.

**Comment by BlazeGuy2** [comment]
PR merged in
