### ISSUE TITLE
[8.0.0] Tomatoes mesh issue

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10282]
![image](https://user-images.githubusercontent.com/431728/49847807-b0e36780-fe1d-11e8-9903-8c6ae11af7d1.png)

**Comment by redwyre** [comment]
Changes with distance, related to LODing?
![image](https://user-images.githubusercontent.com/431728/49847879-120b3b00-fe1e-11e8-8f92-5a0a737dd134.png)

**Comment by elfl0rd** [comment]
yes, https://github.com/StrangeLoopGames/EcoIssues/issues/2825

**Comment by BlazeGuy2** [comment]
Closing as dup
