### ISSUE TITLE
HW: don't show HW server in recent if HW button provided

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10290]
![default](https://user-images.githubusercontent.com/4980243/49885542-91156900-fe48-11e8-88ad-5b6d01f4e0ea.png)
In this case, "Continue" target is same with HW button.

**Comment by mirasrael** [comment]
I don't see any real reason to now show it. Because you can connect to HW in any way - with direct connection or from Recommended Tab or from search search. So if it will only be shown in part of cases then it may be confusing to users.

**Comment by mirasrael** [comment]
Because not discussion was followed and no real reason for me to fix this I'm closing issue.
