### ISSUE TITLE
"Official Test Servers" need to be renamed to "Official server" and include new stable servers.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10292]
![20181212224721_1](https://user-images.githubusercontent.com/4980243/49894945-3e47ab80-fe60-11e8-98e6-a646aad936fc.jpg)
![20181212224930_1](https://user-images.githubusercontent.com/4980243/49894957-4b649a80-fe60-11e8-8ee3-d1fc87f571ab.jpg)
This server for "standart" player is "official" only by name, but everyone can name self server as "official"...

And i think need additional "official" marker here
![20181212225250_1](https://user-images.githubusercontent.com/4980243/49895168-d5acfe80-fe60-11e8-82c5-7f1d2384cec2.jpg)
or here. Ofc, unavailable for "standart" server creators.
![20181212225306_1](https://user-images.githubusercontent.com/4980243/49895183-dc3b7600-fe60-11e8-99fb-0e442de45022.jpg)

**Comment by D3nnis3n** [comment]
Afaik John wanted them to not show up there to not hurt other server owners. @johnkslg ?
