### ISSUE TITLE
USER ISSUE: Language is mixed up: German and English

### ISSUE THREAD

**Issue by LHMplus89** [StrangeLoopGames/EcoIssues#10291]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
1. Set Language in options menu to English
2. Set Server to English
3. Play the game: move one step, and the glitch occurs

**Expected behavior:**
Everything should be in English. Every object name, every action, every description.

**Actual behavior:**
The game uses English and German seemingly random. Objects and desriptions are referred to in English and German

**Do you have mods installed? Does issue happen when no mods are installed?:**
The game uses English and German seemingly random. Objects and desriptions are referred to in English and German

**Comment by elfl0rd** [comment]
you 

> Set Server to English

Using serverUI?
You restarted server after it?

Attach your server\configs\Localization.eco please

**Comment by D3nnis3n** [comment]
You need to restart the server after changing the server language.

**Comment by D3nnis3n** [comment]
Closed as it has not gotten an answer in the last 14 days.
