### ISSUE TITLE
Torch Stand accepts Torch as fuel

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10299]
![image](https://user-images.githubusercontent.com/3536496/49899909-f0a45200-fe11-11e8-9623-b90a5561dcc4.png)

**Comment by elfl0rd** [comment]
I always thought that was the plan, or didn't?

**Comment by D3nnis3n** [comment]
That seems intended. You put a torch into the stand until it burned out and you need a new one!?

**Comment by elfl0rd** [comment]
"Not fueled" torch allow users to create "free" light sources...
This appropriate only if torch stand is no more counts as housing item.

**Comment by metachronism** [comment]
this is intended
