### ISSUE TITLE
Shadows show no body

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10297]
![image](https://user-images.githubusercontent.com/3536496/49899618-0a916500-fe11-11e8-9637-d70d41a47649.png)
Two possible solutions:
- hide shadows from carried stuff
- make a blob of shadow for the body

**Comment by elfl0rd** [comment]
:D 
https://github.com/StrangeLoopGames/EcoIssues/issues/4809
https://github.com/StrangeLoopGames/EcoIssues/issues/6280
https://github.com/StrangeLoopGames/EcoIssues/issues/8791

**Comment by BlazeGuy2** [comment]
Closing as a dup of the previous issues.
