### ISSUE TITLE
Split chat and notification

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10295]
![image](https://user-images.githubusercontent.com/3536496/49898605-4e369f80-fe0e-11e8-8552-e69763ab2f56.png)
Right now, chat and notifications are mixed in the log, making less important stuff push out more important stuff.  With this feature, we will split those, so notifications will not push out chat.  Thinking we have the notifications or chat appear at the top while the other remains in place, and chat stays up longer, maybe permanently showing the last X results.
Please put together a design doc before starting on this feature. Thanks!

**Comment by SlayksWood** [comment]
Seems added.
