### ISSUE TITLE
Chat starts scrolled up partially

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10296]
![image](https://user-images.githubusercontent.com/3536496/49898775-c0a77f80-fe0e-11e8-8949-4f93f026484b.png)
Above is when I first open the chat menu.  Notice the scrollbar indicates its at the end of the scroll.  However, when I scroll down, more messages are revealed and the scroll bar changes:
![image](https://user-images.githubusercontent.com/3536496/49898821-dae15d80-fe0e-11e8-9e74-77cfcb148b6e.png)

**Comment by elfl0rd** [comment]
Maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/8248

**Comment by seccombew** [comment]
Fixed.
