### ISSUE TITLE
[8.0.0] Workbench UI not initialised properly

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10305]
The other tabs are fine, reconnecting didn't help. Even quitting the game didn't help.
![image](https://user-images.githubusercontent.com/431728/49910187-76d19e80-fecd-11e8-880e-03b5685ef48d.png)

**Comment by redwyre** [comment]
Placing another one and opening it fixed the UI for the first one.

**Comment by redwyre** [comment]
Seems to be something to do with the project missing items, I started a new job of making hewn logs, and when I came back it was broken again. The other workbench is fine.

**Comment by seccombew** [comment]
Does not repro.
