### ISSUE TITLE
Feature/suggestion: button (somewhere) to open eco profile folder

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10307]
It's really helpfull for supporting players, e.g. configs\logs showcase and configs editing.

**Comment by elfl0rd** [comment]
Do you think, this need to moving into suggestions in that case? @D3nnis3n

**Comment by D3nnis3n** [comment]
Keep it here, devs will move it if needed.

**Comment by elfl0rd** [comment]
This does not work like this, issues with the suggestion label are moved automatically :)
