### ISSUE TITLE
Master: ice dirt looks as stone

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10311]
(it's confuse me, heh)
![default](https://user-images.githubusercontent.com/4980243/49922281-4c79e400-fec1-11e8-82f0-50c4da2c8c4b.png)

Real stones marked
![default](https://user-images.githubusercontent.com/4980243/49922361-82b76380-fec1-11e8-9325-c58cb874872b.png)

**Comment by keegan-o** [comment]
Toned down the 'permafrost' frozen soil block a ton in generation, so you shouldn't see this anymore.

**Comment by elfl0rd** [comment]
This is in master already? I can not see changes...
![default](https://user-images.githubusercontent.com/4980243/50311417-30280980-04b6-11e9-843d-18c4f3b8c935.png)

**Comment by elfl0rd** [comment]
Yes, i agree - it looks cool in snow biome,
![default](https://user-images.githubusercontent.com/4980243/50311471-606fa800-04b6-11e9-93fb-35476b2ea150.png)
But not ok outside :(

**Comment by keegan-o** [comment]
Will make it only spawn in the 'ice' biome which is snow-covered for 8.0
