### ISSUE TITLE
Can't Open Skill Window

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10317]
Clickbait title, I know.
But the question is happening way too often on Discord.

This happens because the Skill Button is hidden and the hotkey disabled while the tutorial hasn't been completed or skipped.

A simple suggestion to fix this issue, or at least make new players wonder less. Make it so that when you click `K` to open the skill window, but haven't completed the tutorial yet, display an error message on the screen telling them to finish the tutorial or skip it before they can open it.

Simply doing nothing is causing more confusion than good, and it would be simple to just tell the user what is going on rather than do nothing.

**Comment by D3nnis3n** [comment]
That's probably the most asked question in support, lol.
