### ISSUE TITLE
[8.0.0] Replacing blocks under door made room not a room

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10316]
/testroom randomly says it's a room, or I think that there was a ceiling missing (there isn't).
Kiln in the room says it's not in a room.
Removing and placing a block from the floor inside fixed it.

See also https://github.com/StrangeLoopGames/EcoIssues/issues/9636

**Comment by SlayksWood** [comment]
0.8.1.2 and master 8.2
The room will break down If you put a block outside the room near the door, like this
![image](https://user-images.githubusercontent.com/45708377/56044125-3254f300-5d47-11e9-9b02-19ea6b8fe026.png)

The block can be put in any of 7 places.
![image](https://user-images.githubusercontent.com/45708377/56044082-22d5aa00-5d47-11e9-9752-3f74d501ca20.png)

**Comment by SlayksWood** [comment]
move to #12036, because there is more information in it
