### ISSUE TITLE
Failed to Clean backup

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#10329]
Version: 0.7.8.5 beta Server

Steps to Reproduce:

Just let the server run for a couple of days

Expected behavior:
That the server would properly cleanup the backups
and handle them properly

Actual behavior:

Ok well this is pretty intresting the server has been running now for 
a couple of days and I have not mucked or touched the backup files
in any way but on my console window on the server which is running
Windows 7 

I am getting the message 

[11:20:39] Removed backup - C:\Program Files (x86)\Eco Server\Storage\Backup\Game-2018-12-13-09-26-22

[11:20:39] Failed to clean backup: Could not find a part of the path 'C:\Program Files (x86)\Eco Server\Storage\Backup\Game-2018-12-13-09.26.22'

A screenshot of this error can also be seen at 
https://ibb.co/dGM3PL4

As the path exists i can see other backups in there so what the heck gives?

I checked the properties on the Backup directory and there isn't anything strange
there I thought maybe it got set read only or something goofy like
that but no everything is ok.  The user also has full admin rights 
as well on that machine so that should not be an issue either. 

I checked the security settings to make sure it has the right
permissions and they are fine as well. 

Do you have mods installed? Does issue happen when no mods are installed?:
I have no mods installed.

![eco failed to clean backup 0 7 8 5 server error](https://user-images.githubusercontent.com/38896397/50020775-3ee15e80-ff94-11e8-905b-755b89e67c53.jpg)

![eco failed to clean backup 0 7 8 5 server error 2](https://user-images.githubusercontent.com/38896397/50020976-cf1fa380-ff94-11e8-827b-a7ba622717c1.jpg)

**Comment by mirasrael** [comment]
Hi @thereporter42 Do you still have this issue? Looks like an OS level error. May be restart may help in this case.

**Comment by mirasrael** [comment]
No answer. Closed.
