### ISSUE TITLE
USER ISSUE: Server Connection 

### ISSUE THREAD

**Issue by JaeLotus** [StrangeLoopGames/EcoIssues#10321]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
Try to connect to a server

**Expected behavior:**
Connected to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by D3nnis3n** [comment]
Could you go a bit more into detail on which server this happened and if you managed to join later?

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
