### ISSUE TITLE
[8.0.0] Crash upon placing tent

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#10322]
See attached screenshot

![crash on placing tent](https://user-images.githubusercontent.com/841990/49972883-4d4b5e00-ff33-11e8-9aed-55f335b5f00f.JPG)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10185

**Comment by BlazeGuy2** [comment]
Haven't been able to repro this when I place a tent in 8.0.0.

**Comment by elfl0rd** [comment]
Yep, looks as fixed. master\steam 0.8

**Comment by Quadbro** [comment]
@elfl0rd yeah, i fixed it in that issue

**Comment by elfl0rd** [comment]
(fixed)
