### ISSUE TITLE
FromBsonIList calling functions that weren't compiled when using IL2CPP

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10326]
When compiled for Android, at least

System.ExecutionEngineException: Attempting to call method 'Eco.Shared.Utils.ListExtensions::FromBson<Eco.Shared.Localization.LocString>' for which no ahead of time (AOT) code was generated.

![image](https://user-images.githubusercontent.com/431728/49988445-66e7b680-ffc2-11e8-8909-73fffc9075f2.png)

**Comment by redwyre** [comment]
I have a hack in the webgl branch to compile this function statically, haven't had another crash since but not sure what triggered it in the first place

**Comment by mirasrael** [comment]
@redwyre how did you hack this?

**Comment by mirasrael** [comment]
—extra-types.file=»C:\Program Files\Unity\Editor\Data\il2cpp\il2cpp_default_extra_types.txt»
I think we should use this way to specify list of types which can't be found in code, but may be dynamically created.
