### ISSUE TITLE
Unloading a shovel should drop it vertically whichever direction youre facing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10325]
So it doesnt look funny when you try to let go of dirt from a shovel and it sticks.

**Comment by johnkslg** [comment]
Will be handy for throwing dirt in pits and such

**Comment by elfl0rd** [comment]
Like excavator\skidsteer work? :)

**Comment by elfl0rd** [comment]
Hah, yes, sounds like it.
