### ISSUE TITLE
[8.0.0] InvalidCastException when trying to remove bank account

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#10323]
Detailed description:
I opened a bank account and subsequently tried to remove the bank account. 

Expected behavior:
Bank account being removed from the list of active accounts

Actual behavior:
Server threw an InvalidCastException. See https://pastebin.com/pcu9hVes

Steps to reproduce
1. Place bank
2. Add bank account
3. Remove newly created bank account

**Comment by BlazeGuy2** [comment]
https://youtu.be/pDKLUF9A2HU

@DragonSupremacy Tried to repro, couldn't get it to happen.

**Comment by DragonSupremacy** [comment]
https://youtu.be/bq0lvX9adjs

@BlazeGuy2 Not sure if related, but I clicked on the newly created bank account once before trying to delete it and crashing.
