### ISSUE TITLE
File validation is removing saved games?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10320]
Please are letting us know that when they validate the files through system validate it is removing saved games.  It should not do that and has not in the past  Is this a new way Eco is handling saved games now and do we need to have people backup outside of the server directory before doing a validate or is steam doing something wonky?

**Comment by pamduncan** [comment]
Update,  Finally got told that this was not just a validate but that the steamcmd was run to update anbd validate so he ran  steamcmd, login anon, force_install_dir <dir>, app_update # valdiate.

I am now getting mixed results when running steamcmd  It has emptied the Storage folder of files 2 times out of 5 attempts

The player having the worst issue with this is "Blobby"

**Comment by D3nnis3n** [comment]
I have my Eco server on a VPS and using steamcmd does not remove my saved games.

**Comment by D3nnis3n** [comment]
Feel free to add more information when you get some.

**Comment by pamduncan** [comment]
I think we can close this.  The issue must have had some problem with environmental settings in a VM on Linux running windows.  Moving the game to a Folder (server/) instead of having it at root solved the issue.  I have never run a game application at root but I know of some that successfully install ecoserver to root and run the server without issue.  removing all the EcoServer files and creating a directory solved that

**Comment by D3nnis3n** [comment]
Alright.

**Comment by D3nnis3n** [comment]
I just experienced that too on the update fron 0.7.8.6 to the re-released 0.7.8.6 version. It deleted my savegame - not my backups though.

**Comment by D3nnis3n** [comment]
Another report: 
<img width="527" alt="report" src="https://user-images.githubusercontent.com/25908592/50034320-91eefc00-fffc-11e8-9485-bcd06f4a4e81.png">

**Comment by mirasrael** [comment]
Game saves was accidentally added to Server release on Steam... I re-uploaded version on Steam, now it should be OK. Sorry for all who get hurt.
