### ISSUE TITLE
Master: unowned waterfilter ignore linked storage

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10339]
![default](https://user-images.githubusercontent.com/4980243/50042524-1ed59c00-0075-11e9-861a-202a473f2979.png)
![default](https://user-images.githubusercontent.com/4980243/50042533-47f62c80-0075-11e9-846b-3705d4f48912.png)
![default](https://user-images.githubusercontent.com/4980243/50042535-50e6fe00-0075-11e9-9795-aa8e103ed585.png)

**Comment by johnkslg** [comment]
Good find.
