### ISSUE TITLE
Master: QoL: pipes in 2x1 tunnel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10338]
Problem with passage, character periodically stuck - unconfortable.
![default](https://user-images.githubusercontent.com/4980243/50042500-b38bca00-0074-11e9-8eff-a1958aa9bd2f.png)

**Comment by johnkslg** [comment]
Keegan, can you adjust collision of pipe blocks to make this case work better?  It will be a common case for installing plumbing.

**Comment by keegan-o** [comment]
I don't think this is really fixable without just adding a crouch that squishes your collider to one meter tall...

**Comment by SeanAtr0n** [comment]
Increasing the player collider height to better match the avatar... this means that this tunnel won't be usable anymore.

I did a quick hacked version of crouching that we could potentially use if we really want this to be accessible but it sounds like John is against that idea... it looks pretty silly
![dumbcrouch](https://user-images.githubusercontent.com/774628/51065825-bfa77080-15bb-11e9-912a-d6159b58c97a.gif)

**Comment by elfl0rd** [comment]
Looks funny, lol.
But, yes, require lot of new animations :(

**Comment by SeanAtr0n** [comment]
fixed player height, 2x1 tunnels won't work w/ pipes inside
