### ISSUE TITLE
Dead corn looks silly in 8.0

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10333]
![image](https://user-images.githubusercontent.com/774628/50033535-c7202d80-ffad-11e8-9142-12e54dc7d99a.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/2a8836f8-eef4-4240-aa3e-fe54caa1621a)
Was changed to brown instead of grey a while ago
