### ISSUE TITLE
Why is fast-forward disabled on my singleplayer world?

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10332]
User reported, @BlazeGuy2 investigate

**Comment by D3nnis3n** [comment]
FastForward = false in sleep.eco by default?

**Comment by johnkslg** [comment]
Its supposed to specifically enable it when you start single player, and default to false otherwise.

**Comment by D3nnis3n** [comment]
Then that's high priority. Cause that is not the case.

**Comment by pamduncan** [comment]
I have has several of these but in each case the player did pick to have friends join Several has been okaying single player games and sleep worked but they had not invited friends, when they made a new world and invited then fast forward was disabled.  Not sure is allowing friends to join therefore makes in no longer single player and the fast forward is turned off.  The hard part of this is that many playing on the SP server with fronds are a small enough cooperative group that they want to sleep and they coordinate their sleep times.  Its easy enough to tell them how to re start it back so its on but that is probably what is happening. I have been able to repro this a couple of times.  Also if the player started a game as tehir first game and choose friends to join the fast forward was off, however if they star another game and this time do not invite friends fast forward stays off - should it be expected to set fast forward to on if person plays another game and does not invite friends,  In a couple of cases it maybe player error as the said they had bot allowed friends to join but connections are set to -1 .  Its like it knows to change things if it goes from a sp game and no friends to one that allows friends but if the first game is set up as a game with friends  then it keeps those 'with friend settings' even if they said no in a second or third game, once open to the public it seems to want to stay configured like that.

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/51153293-6c842680-1824-11e9-9c06-c68c937edcf3.png)
Sleep is always enabled by default when any world is launched from the SP client, regardless of if playing with friends is selected as true or not.  On the latest build of 8.0.0, I checked the local server UI and confirmed it was set to true.  I'm gonna need more info for a repro case.

**Comment by BlazeGuy2** [comment]
Reopen if it is still occurring on 8.0.0 release.
