### ISSUE TITLE
USER ISSUE: Server I played on today vanished

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#10334]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
Not sure how

**Expected behavior:**
I should be able to rejoin my server

**Actual behavior:**
I can't seem to find it in my worlds or browsing all servers

**Do you have mods installed? Does issue happen when no mods are installed?:**
I can't seem to find it in my worlds or browsing all servers

**Comment by pamduncan** [comment]
There were problems with the links not keeping the info when a server was restarted.  Trry taking the server off of being a favorite and then search for it again and make a new connection to i.  If it does not show up in the browser in a search its possible that the server is down, you should talk to the owner as we have no way to locate a server that is not online

If it is your server and you have restarted it without following the steps in the discords #announcements and also reinstalled 7.8.6, that could be your issue

**Comment by amboo515** [comment]
Yes. To be honest, I just started over on a different server, but I appreciate the advice and will use it if it occurs again. Thank you.

**Comment by mirasrael** [comment]
Ok. @amboo515 thanks for answer. Closing this issue for now.
