### ISSUE TITLE
USER ISSUE: too many skillpoints

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10335]
**Version:** 0.8.0.0 beta master-e510ffa5
(standart settings, after start new fresh world)
![20181215125447_1](https://user-images.githubusercontent.com/4980243/50041648-22632600-0069-11e9-9c3e-e61f97f711a2.jpg)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10364 as of reasons mentioned there.
Thanks for your report GDragon.
