### ISSUE TITLE
Master: QoL "Permanent account cannot be deleted"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10349]
![default](https://user-images.githubusercontent.com/4980243/50144082-53d52f00-02bf-11e9-9f6d-d8b4f487b0b7.png)

I prefer remove "delete" button from permanent accounts, (and maybe show small lock icon) instead of showing error after attempt.

![default](https://user-images.githubusercontent.com/4980243/50144112-68192c00-02bf-11e9-9a51-fa598d1ac8f0.png)

**Comment by D3nnis3n** [comment]
That would make players ask why they can't remove it though, i'll give it low.
