### ISSUE TITLE
Users Issues (MacOS)

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10348]
Received a complaint about a Mac users issue present since last June and was unable to find any bug report dealing with this.  Was told to make a issue regarding it and to see what can be done: 
[![Screenshot from Gyazo](https://gyazo.com/1d52a72e0f0cb3343e48e84abe32d11a/raw)](https://gyazo.com/1d52a72e0f0cb3343e48e84abe32d11a)

[![Screenshot from Gyazo](https://gyazo.com/04d17c7244afba65ac90f5af43c07279/raw)](https://gyazo.com/04d17c7244afba65ac90f5af43c07279)

**Comment by redwyre** [comment]
Is the webpage problem an issue launching the browser, or that it doesn't load the page correctly?

**Comment by D3nnis3n** [comment]
We'll never know - the user left the discord.

**Comment by SlayksWood** [comment]
Checked on 8.2.5 with MacOS. Wasn't able to reproduce, seems fixed.
