### ISSUE TITLE
Pipes connect with pipes in stockpile

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10343]
![default](https://user-images.githubusercontent.com/4980243/50042660-18482400-0077-11e9-86f6-4af683de448e.png)

**Comment by johnkslg** [comment]
This is hard to fix, and cosmetic only, so reducing in priority and pushing to future milestone

**Comment by johnkslg** [comment]
@craig-jong can you force pipes to be crates in the stockpile? Is a setting in tech tree? 
Bigger problem is pipes look janky in stockpiles anyway

**Comment by craig-jong** [comment]
Creates are placed for non-block items. Pipes are block items.

I'm not really sure what we can easily do here.

**Comment by Deantwo** [comment]
Wouldn't it make more sense to make pipes function like construction materials? Have a nice stack of pipes when place normally, and require a hammer (or wrench?) to install them for function.
It would require a little artist work though.
