### ISSUE TITLE
SERVER ISSUE: Connecting users stuck on loading world.

### ISSUE THREAD

**Issue by Zhinj** [StrangeLoopGames/EcoIssues#10346]
Version: 7.8.6

I am seeing issues with at least two users (Cog, Knight_Fox) being unable to connect to a server they have previously had no issues connecting to.

The issue from the users side: They typically will get to the "Loading World" piece of the login and it will freeze entirely and eventually timeout and return to the main screen. Other times they will be able to login successfully but will crash shortly after (within 2-3 minutes typically)

I have been working with Pam a lead moderator in the discord to try and resolve the issue, but haven't had any luck. Her suggestion was possibly one of player profile corruption so that is what I had been looking at mostly.
To test this I loaded up a fresh gen world on the server and they could connect to that.

One suggestion to resolve this was removing their player profile from the game.eco file. However whenever I remove them from this file it will create a crash at server startup. I have tried with multiple archive applications (7zip and winrar) to delete the user entries.

In testing I was able to successfully remove my own profile (Zhinj) and it performed as expected, though testing further on another character (CaptKellix) that haven't had issues also caused the same crash on server startup.

Given the timing of the crash occuring during the "Loading Property", and the exception being a null reference I tested removing all of their property (Manually deleted every vehicle they had out on the map, and running the /ownall command) but it still crashed at the same time in the same manner when I tried removing their profile.

Here is a crashfile showing the exception at server startup, and the Game.eco file for the world I'm having issues with.
[Eco Server Startup Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2688185/Eco.Server.Startup.Crash.txt)
https://www.dropbox.com/s/eeseoed7jrrm29w/Game.eco

**Comment by SlayksWood** [comment]
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
