### ISSUE TITLE
Using full shops creates and error and kicks client 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1034]
http://ecoforum.strangeloopgames.com/topic/1359/kicked-from-server-if-shop-is-full-v5-3

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1678/bug-full-shop-causes-server-kick

**Comment by metachronism** [comment]
fixed in 5.5.1
