### ISSUE TITLE
[0.8.1.4] Teleport to Top

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#10345]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
1. Go down a ladder/mineshaft and stand next to a wall.
2. Place down a block or mine one out.

**Expected behavior:**
Just place the block or mine the block out

**Actual behavior:**
Places down the block or mines it but also teleports you to the top of that wall.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Places down the block or mines it but also teleports you to the top of that wall.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/56573656-42cc5f80-65ca-11e9-97cd-182e3584c583.png)
![image](https://user-images.githubusercontent.com/45708377/56573714-5d9ed400-65ca-11e9-82d8-d85a93dddcef.png)
You will be teleported to top.
![image](https://user-images.githubusercontent.com/45708377/56573739-6b545980-65ca-11e9-9402-ee1e6bf6c50b.png)

It may be necessary to add the impossibility of putting yourself under your feet if this leads to your getting stuck and teleporting to the free space.
