### ISSUE TITLE
Long errors make dialog box too big

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10347]
![image](https://user-images.githubusercontent.com/3536496/50122432-52e5c400-0211-11e9-856c-11488b5588c1.png)

**Comment by Spydarlee** [comment]
Do you have an example of something that triggers these sorts of errors, @johnkslg? I'm pretty sure it's the standard Popup dialog that is being used, but I can't find any examples in error handling code. 🤔

**Comment by elfl0rd** [comment]
@Spydarlee chop palm and try to pickup his log :D
