### ISSUE TITLE
Some species missing category

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10350]
As i see: Otter, Buttonbush, Pitcher Plant, Waterweed need assign to categories. (And some new incoming in 0.8 too.)
![default](https://user-images.githubusercontent.com/4980243/46556132-62ca5900-c8ee-11e8-86a4-f6e49b2da65a.png)

**Comment by redwyre** [comment]
This is actually based on what resource type the item gives, rather then the item itself. So no resource = no icon and dark blue text.

I'm going to close this as they'll change as resource types get added to the items.
