### ISSUE TITLE
Master: Can't select shovel while carrying clay

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10353]
**Version:** 0.8.0.0 beta master-d2f08330 debug
(you can pickup clay only by shovel)

![default](https://user-images.githubusercontent.com/4980243/50175922-18625100-030f-11e9-8cc3-a34929dc2f25.png)

**Comment by johnkslg** [comment]
Keegan can you add clay for shovels?

**Comment by elfl0rd** [comment]
@keegan-o commented 8 hours ago in https://github.com/StrangeLoopGames/EcoIssues/issues/10412

> fixed in master

You miss wooden shovel :P 
![default](https://user-images.githubusercontent.com/4980243/50537017-e1403b00-0b6b-11e9-9a21-23d630ceb4cf.png)

**Comment by Spydarlee** [comment]
Is that just the art that's missing@elfl0rd? The functionality is okay?

**Comment by elfl0rd** [comment]
yes, all fixed.
Art created too.
