### ISSUE TITLE
Master: clay - balance.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10355]
okay, largest clay vein i found - 112.
At maximum skill it is equal ~50 bricks...
Really? 0_o lower requiments or make veins bigger please.

**Comment by elfl0rd** [comment]
lot of clay deposits equal ~30 blocks...
15 bricks on max eff? srsly? not funny.

**Comment by metachronism** [comment]
this is intended.  clay is only more prevalent in specific biomes

**Comment by elfl0rd** [comment]
@metachronism Yes, I understand that - but its current quantities do not allow it to be used!
The amount of work to the result is simply incomparable, despite the fact that in the real world the resource to the result is about 1.25 to 1.

**Comment by craig-jong** [comment]
yea, the numbers were done with the assumption clay was split into 4 chunks (which it is not).

I changed it, but we can always tweak it more.

**Comment by craig-jong** [comment]
Plus shoveling is worse that pickaxing.
