### ISSUE TITLE
[8.0.0 Steam Beta] Balance skillpoints

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10364]
![image](https://user-images.githubusercontent.com/25908592/50229059-ba367c00-03a9-11e9-88bd-3f2d97d59925.png)
Look in the lower left - it's definately not supposed to be like that. Also the balance of gaining skillpoints seems way off. I assume you got me a developer version - i need one suitable for end users to test the new skillpoints system and balance. Also streamers (for those this version was) don't want to have everything unlocked.

**Comment by elfl0rd** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/10335

**Comment by D3nnis3n** [comment]
I'll merge your issue into this one, as i've already used this issue in numerous places, including DMs, as it needs to be fixed ASAP.

**Comment by D3nnis3n** [comment]
GDragons picture: https://user-images.githubusercontent.com/4980243/50041648-22632600-0069-11e9-9c3e-e61f97f711a2.jpg

**Comment by elfl0rd** [comment]
got it again, lol
![default](https://user-images.githubusercontent.com/4980243/51071577-53cd1280-1664-11e9-8fda-70c01f087f23.png)

**Comment by elfl0rd** [comment]
Try to repro with this server settings
![default](https://user-images.githubusercontent.com/4980243/51071816-3dc15100-1668-11e9-96d2-9cf28bc32fb6.png)
it's "No Collaboration" preset. (only preset, no other changes)

**Comment by Quadbro** [comment]
@craig-jong Hey, need your help, it's your part of code, added to skill system, Problem comes, when you setting SpecialityCostMultiplier to 0. Then 
![image](https://user-images.githubusercontent.com/6802030/51108254-23cc6d80-1824-11e9-9e24-868030222454.png)

**Comment by johnkslg** [comment]
No longer broken, but needs balancing. Closing and opening another one.
