### ISSUE TITLE
[8.0.0 Steam Beta] Treasury can only transfer money to the main account

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10367]
None of my other two accounts are listed: 
![image](https://user-images.githubusercontent.com/25908592/50230983-0d123280-03ae-11e9-9598-f3a0ca931f17.png)

**Comment by D3nnis3n** [comment]
If this is not possible, how am i supposed to make an account for several people where taxes can go?

**Comment by johnkslg** [comment]
Good find, this will be in 9.0 though
