### ISSUE TITLE
[8.0.0 Steam Beta] Give command spawns things into carriable slot

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10369]
/give hoe =
![image](https://user-images.githubusercontent.com/25908592/50233217-413c2200-03b3-11e9-8e2b-8d93c7aef6a0.png)

Comment from GDragon:
1. happens only if no space on toolbar. (you can have space in backpack, but it still happen.)
2. /give in this case can replace content of carried slot.

**Comment by elfl0rd** [comment]
1) happens only if no space on toolbar. (you can have space in backpack, but it still happen.)
2) /give in this case can replace content of carried slot.

**Comment by D3nnis3n** [comment]
Good catch, that's right!

**Comment by BlazeGuy2** [comment]
Still road for 8.1, just not a high pri fix.
