### ISSUE TITLE
[8.0.0 Steam Beta] Forage tutorial is a bit stuck

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10360]
See the screenshot, i gathered the required material with commands like we did in earlier builds but it was not checked. Moving the materials to the tent and back did check all but corn, after moving corn two more times that was also checked. Something probably not registering correctly?

![food](https://user-images.githubusercontent.com/25908592/50228575-96266b00-03a8-11e9-9f5c-031fe9182962.jpg)

**Comment by Quadbro** [comment]
hm, it supposed to work with WILD ones, not just to move it in inventory, heh :D

**Comment by Quadbro** [comment]
and also it works only when user inventory got changed, not some chests or smth

**Comment by Quadbro** [comment]
checked with commands, and with wild gathering, all works as intended
