### ISSUE TITLE
[8.0.0 Steam Beta] /give does not give you another item if you already have one

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10375]
Do /give hammer - now you got a hammer.
You want a second one, so use /give hammer again.
You don't get a second hammer.

**Comment by elfl0rd** [comment]
(silently, without any errors or messages. Maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10378 )
If you
/give paper,5
then
/give paper
You loose 4 paper from stack :D
