### ISSUE TITLE
[8.0.0 Steam Beta] Laws don't get converted correctly.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10371]
World convert correctly despite laws. It takes it 120 seconds to to do initialisation of legislation and all the laws are converted to laws with the correct description but only a "tax X" clause. Use this world to retry: https://download.godsofwar.de/eco/cycle-5.zip

<img width="826" alt="laws" src="https://user-images.githubusercontent.com/25908592/50234548-3df66580-03b6-11e9-8c05-a83631c1ecec.png">

**Comment by johnkslg** [comment]
@metachronism can you help with this migration issue? I dont think much has changed since last version related to laws.

**Comment by mirasrael** [comment]
Checked on @D3nnis3n save. It doesn't load, but it isn't related to migration. RepealableDemographicDropDown while instantiation fails. Created separate bug for this: https://github.com/StrangeLoopGames/EcoIssues/issues/10756

**Comment by mirasrael** [comment]
Another issue discovered for this save https://github.com/StrangeLoopGames/EcoIssues/issues/10795. This issue doesn't related to migration. Also presents on 8.0 generated world.

**Comment by mirasrael** [comment]
Fixed #10794 and #10795. Now all laws was migrated successfully except "Emission Permits Law: Step 2.5", but it contains Skill conditions which was removed from game. So no way to migrate this. Totally 22/23 was migrated.
