### ISSUE TITLE
[8.0.0 Steam Beta] Getting items with left click from vehicles or stockpiles doesnt work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10374]
See title.

**Comment by Quadbro** [comment]
Context?) what slot you used on hotbar?) (emty? iterm? tool?)

**Comment by Quadbro** [comment]
It works with empty slot, and with item to refill

**Comment by D3nnis3n** [comment]
Empty hotbar, empty carriable slot. Reproducable on the steam build i got.

**Comment by Quadbro** [comment]
@D3nnis3n does it happen on new steam build?)

**Comment by D3nnis3n** [comment]
Still on vacation, cannot try before i'm back.
