### ISSUE TITLE
[8.0.0 Steam Beta] dirt particles too shiny

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10379]
![20181219202017_1](https://user-images.githubusercontent.com/4980243/50236494-9c7a0e80-03cb-11e9-913f-8493501aa53d.jpg)

**Comment by D3nnis3n** [comment]
Is that intended @keegan-o?

**Comment by keegan-o** [comment]
Duplicate, closing.
