### ISSUE TITLE
[8.0.0 Steam Beta] Missing Icons

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10386]
Missing following icons: AdvancedBakingFocusedWorkflowTalentGroup, AdvancedBakingFrugalWorkspaceTalentGroup, AdvancedBakingLavishWorkspaceTalentGroup, AdvancedBakingParrallelProcessingTalentGroup, AdvancedCampfireCookingFocusedWorkflowTalentGroup, AdvancedCampfireCookingFrugalWorkspaceTalentGroup, AdvancedCampfireCookingLavishWorkspaceTalentGroup, AdvancedCampfireCookingParrallelProcessingTalentGroup, AdvancedCookingFocusedWorkflowTalentGroup, AdvancedCookingFrugalWorkspaceTalentGroup, AdvancedCookingLavishWorkspaceTalentGroup, AdvancedCookingParrallelProcessingTalentGroup, AdvancedSmeltingFocusedWorkflowTalentGroup, AdvancedSmeltingFrugalWorkspaceTalentGroup, AdvancedSmeltingLavishWorkspaceTalentGroup, AdvancedSmeltingParrallelProcessingTalentGroup, BakingFocusedWorkflowTalentGroup, BakingFrugalWorkspaceTalentGroup, BakingLavishWorkspaceTalentGroup, BakingParrallelProcessingTalentGroup, BasicEngineeringFocusedWorkflowTalentGroup, BasicEngineeringFrugalWorkspaceTalentGroup, BasicEngineeringLavishWorkspaceTalentGroup, BasicEngineeringParrallelProcessingTalentGroup, BricklayingFocusedWorkflowTalentGroup, BricklayingFrugalWorkspaceTalentGroup, BricklayingLavishWorkspaceTalentGroup, BricklayingParrallelProcessingTalentGroup, ButcheryFocusedWorkflowTalentGroup, ButcheryFrugalWorkspaceTalentGroup, ButcheryLavishWorkspaceTalentGroup, ButcheryParrallelProcessingTalentGroup, CampfireFocusedWorkflowTalentGroup, CampfireFrugalWorkspaceTalentGroup, CampfireLavishWorkspaceTalentGroup, CampfireParrallelProcessingTalentGroup, CementFocusedWorkflowTalentGroup, CementFrugalWorkspaceTalentGroup, CementLavishWorkspaceTalentGroup, CementParrallelProcessingTalentGroup, CookingFocusedWorkflowTalentGroup, CookingFrugalWorkspaceTalentGroup, CookingLavishWorkspaceTalentGroup, CookingParrallelProcessingTalentGroup, CuttingEdgeCookingFocusedWorkflowTalentGroup, CuttingEdgeCookingFrugalWorkspaceTalentGroup, CuttingEdgeCookingLavishWorkspaceTalentGroup, CuttingEdgeCookingParrallelProcessingTalentGroup, ElectronicsFocusedWorkflowTalentGroup, ElectronicsFrugalWorkspaceTalentGroup, ElectronicsLavishWorkspaceTalentGroup, ElectronicsParrallelProcessingTalentGroup, FertilizersFocusedWorkflowTalentGroup, FertilizersFrugalWorkspaceTalentGroup, FertilizersLavishWorkspaceTalentGroup, FertilizersParrallelProcessingTalentGroup, GatheringExperiencedFarmhandTalentGroup, GatheringNaturalGathererTalentGroup, GatheringToolEfficiencyTalentGroup, GatheringToolStrengthTalentGroup, GlassworkingFocusedWorkflowTalentGroup, GlassworkingFrugalWorkspaceTalentGroup, GlassworkingLavishWorkspaceTalentGroup, GlassworkingParrallelProcessingTalentGroup, HewingFocusedWorkflowTalentGroup, HewingFrugalWorkspaceTalentGroup, HewingLavishWorkspaceTalentGroup, HewingParrallelProcessingTalentGroup, HuntingAggressiveAnglerTalentGroup, HuntingArrowRecoveryTalentGroup, HuntingDeadeyeTalentGroup, HuntingFishermanTalentGroup, IndustryFocusedWorkflowTalentGroup, IndustryFrugalWorkspaceTalentGroup, IndustryLavishWorkspaceTalentGroup, IndustryParrallelProcessingTalentGroup, LoggingCleanupCrewTalentGroup, LoggingLoggersLuckTalentGroup, LoggingToolEfficiencyTalentGroup, LoggingToolStrengthTalentGroup, LumberFocusedWorkflowTalentGroup, LumberFrugalWorkspaceTalentGroup, LumberLavishWorkspaceTalentGroup, LumberParrallelProcessingTalentGroup, MechanicsFocusedWorkflowTalentGroup, MechanicsFrugalWorkspaceTalentGroup, MechanicsLavishWorkspaceTalentGroup, MechanicsParrallelProcessingTalentGroup, MetalConstructionFocusedWorkflowTalentGroup, MetalConstructionFrugalWorkspaceTalentGroup, MetalConstructionLavishWorkspaceTalentGroup, MetalConstructionParrallelProcessingTalentGroup, MillingFocusedWorkflowTalentGroup, MillingFrugalWorkspaceTalentGroup, MillingLavishWorkspaceTalentGroup, MillingParrallelProcessingTalentGroup, MiningLuckyBreakTalentGroup, MiningSweepingHandsTalentGroup, MiningToolEfficiencyTalentGroup, MiningToolStrengthTalentGroup, MortaringFocusedWorkflowTalentGroup, MortaringFrugalWorkspaceTalentGroup, MortaringLavishWorkspaceTalentGroup, MortaringParrallelProcessingTalentGroup, OilDrillingFocusedWorkflowTalentGroup, OilDrillingFrugalWorkspaceTalentGroup, OilDrillingLavishWorkspaceTalentGroup, OilDrillingParrallelProcessingTalentGroup, PaperMillingFocusedWorkflowTalentGroup, PaperMillingFrugalWorkspaceTalentGroup, PaperMillingLavishWorkspaceTalentGroup, PaperMillingParrallelProcessingTalentGroup, SelfImprovementDiverTalentGroup, SelfImprovementNatureAdventurerTalentGroup, SelfImprovementSprinterTalentGroup, SelfImprovementUrbanTravellerTalentGroup, SmeltingFocusedWorkflowTalentGroup, SmeltingFrugalWorkspaceTalentGroup, SmeltingLavishWorkspaceTalentGroup, SmeltingParrallelProcessingTalentGroup, TailoringFocusedWorkflowTalentGroup, TailoringFrugalWorkspaceTalentGroup, TailoringLavishWorkspaceTalentGroup, TailoringParrallelProcessingTalentGroup

**Comment by keegan-o** [comment]
These have all been in master for a while now, closing.
