### ISSUE TITLE
[8.0.0 Steam Beta] Recent Servers show no name

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10380]
<img width="1242" alt="recent" src="https://user-images.githubusercontent.com/25908592/50236549-faeac100-03ba-11e9-8c0e-eacdc2c54e46.png">
Some of then are online, some offline. Ususally it did save the name even of offline ones.

**Comment by mirasrael** [comment]
@D3nnis3n do you still have this issue on latest 8.0 build? After adding new servers to recent. It just shows servers with empty description (there was an issue with starting local server without name if no Network.eco was provided).

**Comment by Spydarlee** [comment]
I have had this issue before, but after clearing my recent servers list I haven't been able to reproduce it on latest. Are you still seeing this for newly/recently added servers, @D3nnis3n?

**Comment by D3nnis3n** [comment]
No, i'm not :)
