### ISSUE TITLE
Master: big bluestem - texture? missing.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10393]
![default](https://user-images.githubusercontent.com/4980243/50250612-600dd900-03f2-11e9-8a59-834a1468ba95.png)
![default](https://user-images.githubusercontent.com/4980243/50687614-14cf0980-1033-11e9-8a7c-a6d95aa85bfe.png)

**Comment by keegan-o** [comment]
I've never seen this and it's not like this in master atm, closing.
