### ISSUE TITLE
Seeds not invented

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#10396]
Version: v7.8.6 beta

Just started a new world and was setting up a quick store to get rid of junk.
It turns out that you can't sell **Tomato Seeds** and **Beet Seeds** at a store before the **Farming** skill has been researched.

This is the same old issue of not being able to add things to a store before they are invented.
Can we just please get a "show only invented items" checkbox on the item selection menu? Just leave it enabled by default, so us advanced players can disable it, but newbies can keep their simple list while having a clear indication about why not everything is on the list..

**Comment by johnkslg** [comment]
Add [StartsDiscovered] in the techtree to any seeds that you can get without skills.
