### ISSUE TITLE
Master: bank accounts loose color\icon. Maybe happens with registrar too.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10394]
like https://github.com/StrangeLoopGames/EcoIssues/issues/10228
![default](https://user-images.githubusercontent.com/4980243/50250998-7d8f7280-03f3-11e9-9521-a169482bb9fc.png)

**Comment by Quadbro** [comment]
Not localization related, original EN variant has no icon there too. Just because it uses name without markup in automatic field generator. I think now it's intended :)

**Comment by Quadbro** [comment]
@johnkslg We need some info, pls :)

**Comment by elfl0rd** [comment]
bump, i think colored lines looks better.

**Comment by johnkslg** [comment]
Yeah I think making them colored + icon is better Not a biggie though
