### ISSUE TITLE
USER ISSUE: Can't open in game broswer

### ISSUE THREAD

**Issue by yinghuaho** [StrangeLoopGames/EcoIssues#10397]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
Can't open in game broswer

**Expected behavior:**
web broswer opened when I clicked vote or law

**Actual behavior:**
it says this site can't reached

**Do you have mods installed? Does issue happen when no mods are installed?:**
it says this site can't reached

**Comment by Deantwo** [comment]
What kind of server are you playing on?
Are the webpage ports forwarded?
Is only you affected? Or everyone on the server?

**Comment by BlazeGuy2** [comment]
Reopen when @yinghuaho responds.

**Comment by yinghuaho** [comment]
I have fixed the problem. It is because I installed IIS 7 for my work development
