### ISSUE TITLE
Bisons should not parkour

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10404]
https://drive.google.com/file/d/1ShXFFlqVP4Okclnhy6-EhKiuwwKtKxqg/view?usp=sharing
Could tackle a few ways:
- Dont allow path finding transitions to go up/down unless there is are flat blocks within X units (so to pathfind up hills, theyll need a lower gradation)
- Consider path width when creating the graphs, dont create paths for one-wide blocks

**Comment by johnkslg** [comment]
The nice thing is that mountain goats CAN parkour and should.  Though leaping animations would be nice for them.

**Comment by Aatch** [comment]
Related to this: it would be nice if animals avoided player-constructed paths. A bison charging into a house or onto a bridge is frustrating. I don't think it should be impossible, but it would be nice if the local pathfinding weighted paths such that animals prefer running away from player constructions.

**Comment by elfl0rd** [comment]
Or remake vertical movement, current (instant jump) is really ugly... Jumping animations will be better!

**Comment by SlayksWood** [comment]
Seems fixed
