### ISSUE TITLE
USER ISSUE: Minimap detal setting destoys framerate

### ISSUE THREAD

**Issue by RealDuckSauce** [StrangeLoopGames/EcoIssues#10403]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
turn the minimap detail setting up at all

**Expected behavior:**
it  should not destroy my pc

**Actual behavior:**
its puts my frames from 50+ down to 15

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by D3nnis3n** [comment]
Is that issue still recent? Turning up the detail level of the minimap is causing more work to be done, so FPS dropping is expected when in minimap view.

**Comment by D3nnis3n** [comment]
Closing for now, reopen if you have more information.
