### ISSUE TITLE
Day and Night Cycles in deep caves? 

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#10405]
Version: 0.7.8.6 beta 

Steps to Reproduce:

1. Dig a deep cave really deep 
2. Make a room at the bottom of the entrance shaft
3. Wait for the day / night cycles to change it takes a while.

Expected behavior:

That when you are in a deep cave there 
should be no day / night cycle it should be a constant
darkness. 

Actual behavior:

Now this is kind of strange I have a mine which is dug way 
deep. It isn't just 1 or 2 squares down it is all the way
down to the mantle where you can't dig any deeper. 

This thing is pretty much an underground bunker. 

Now one thing that I am noticing is that it gets brighter
in the day time and then dark at night.

Really in a cave dug that deep there should be no 
day / night cycle and you should need a torch or Brazier 
or some light source once you get down past 7 - 8 deep. 

I believe this to be a huge bug and error in the
design of this game and is most definitely a flaw
and design issue. 

Why is there a day / night cycle when you are 
hundreds of feet under ground. 

This is area that I have is equivalent to a mine shaft
there is absolutely no light this deep.  As I said I am all the way
down to the mantle but yet I am still getting a day / night
cycle where it is going light and dark.

Once you get to a certain depth there should be no 
day / night cycle and more and it should just be 
darkness and you should require some kind of 
light source.

And to display the time in the screenshots I was doing
a /time and capturing it so you can see the in game times
when I was doing this.

I did not change my gamma or anything like that 
either while I was doing this. 

I do believe that this is a huge flaw in this game
that needs to be addressed and fixed. 

Do you have mods installed? Does issue happen when no mods are installed?:
I have no mods installed.

Oh look it is night in the cave .... this is how it should be all the time dark! 

![eco night and day cycle in caves ss 1](https://user-images.githubusercontent.com/38896397/50329648-51d4c100-04b5-11e9-8b8b-3425d402368b.jpg)

Oh now look it is day in a deep cave this isn't right!  I had a bloomery going
but the whole mine is now all bright because it is day time on the surface
the bloomery isn't causing this much light it is the day / night cycle.
The bloomery was also running when I took the night shot as well so 
it isn't affecting this screenshot.

![eco night and day cycle in caves ss 2](https://user-images.githubusercontent.com/38896397/50329947-85641b00-04b6-11e9-8401-4dfed34a9e59.jpg)

**Comment by thereporter42** [comment]
Issue still exists in 0.8.3.3 Beta not fixed

**Comment by keegan-o** [comment]
Fixed in 9.0, sun and moon lights now cast full shadows.
