### ISSUE TITLE
[Web] Trying to register an invite while logging in does not switch accounts

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10409]
1. Be logged in with an account
2. Send invite to an e-mail
3. Accept invite
4. Give your data and register your account.
5. Instead of now being logged in with the newly registered account you are still logged in with the one you sent the invite with.

**Comment by syuzan-yeranosyan** [comment]
Its fixed and the updates are in issue_10409 branch
