### ISSUE TITLE
Master: oil refinery - additional ghost pipe connector?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10400]
2 additional at back
![default](https://user-images.githubusercontent.com/4980243/50309675-bfcab980-04b0-11e9-9b03-1098b02a7e8f.png)
This connector not have collision and out from oil refinery collision block.
![default](https://user-images.githubusercontent.com/4980243/50310658-b55def00-04b3-11e9-81b3-5f6d0d43d98a.png)

@keegan-o ?

**Comment by elfl0rd** [comment]
Hmm... Maybe this connectors for water and sewage?

**Comment by johnkslg** [comment]
Sean can you help with this one?
