### ISSUE TITLE
[Web] Creation of new account throws a database error

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10406]
After creating an account and setting the username and password this appears:

> A Database Error Occurred
> Error Number: 1048
> 
> Column 'login_token' cannot be null
> 
> INSERT INTO `game_token` (`user_id`, `access_token`, `login_token`) VALUES ('144169', NULL, NULL)
> 
> Filename: modules/game/models/Gametoken.php
> 
> Line Number: 9

Pressing the back button leads me to the account page, logged in, though.

**Comment by rainfarmer** [comment]
I was able to recreate this error. Only when logging in this way:
Buy game without account, which sends user to registration. After registration is auto logs in and I got the error.

@syuzan-yeranosyan 
Only place I see using insert to game tokens is adminhelper.php:24

**Comment by syuzan-yeranosyan** [comment]
Its fixed and the updates are in issue_10406 branch
