### ISSUE TITLE
Master: machinery play animation while project halted or completed

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10402]
e.g. robotic assembly, oil refinery
![default](https://user-images.githubusercontent.com/4980243/50310804-3ddc8f80-04b4-11e9-941a-da004e3e320d.png)
![default](https://user-images.githubusercontent.com/4980243/50310839-5351b980-04b4-11e9-969e-d563a6de5539.png)
![default](https://user-images.githubusercontent.com/4980243/50310811-43d27080-04b4-11e9-9426-b38aa9f1244d.png)

**Comment by elfl0rd** [comment]
Maybe this is reason why enabled sink play sound...

**Comment by SeanAtr0n** [comment]
some tables have long animations that'll play if operating = true for a short time, I don't think we want to change how those work as it would be pretty ugly to have the animations reset whenever tables get blocked

making it so new recipies don't set operating=true if they have no ingredients

**Comment by elfl0rd** [comment]
For me - all animations play everytime, not in one cycle after break\stop :(

> some tables have long animations that'll play if operating = true for a short time, I don't think we want to change how those work as it would be pretty ugly to have the animations reset whenever tables get blocked

Theres no "pause" option for anim?
