### ISSUE TITLE
Source string: triilium

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10417]
https://crowdin.com/translate/eco-by-strange-loop-games/40/en-ru#67004

Triilium -> Trillium

**Comment by elfl0rd** [comment]
same on english

**Comment by Quadbro** [comment]
@craig-jong  techtreee related edit, and you're locking it everytime i want to change smth)

**Comment by craig-jong** [comment]
fixed in staging.

**Comment by elfl0rd** [comment]
@Quadbro fix at crowdin please.
https://crowdin.com/translate/eco-by-strange-loop-games/all/en-ru#90258
https://crowdin.com/translate/eco-by-strange-loop-games/all/en-ru#101280
