### ISSUE TITLE
[Web] Trying to link game to steam with unowned account not working as expected?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10410]
Instead of getting an error i get redirected to the page where i can buy eco on SLG site - is that correct?

Also: Why not simply not showing the Steam Link option until an account has bought the game!? This just seems odd.

**Comment by rainfarmer** [comment]
@Tigran07 if user trys to link to steam and does not own game on steam or eco website. It should send to buy page and display notification 'You must own Eco to link to Steam.'

@D3nnis3n you can link to steam -> website or website -> steam
Thus we show the steam link option even if you dont own the game on our website.

**Comment by Tigran07** [comment]
Completed and made a commit on branch steam_link
