### ISSUE TITLE
Client crash while ataching plot / claim plot 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1041]
http://ecoforum.strangeloopgames.com/topic/1381/client-bug-crash-upon-attaching-plot/4

**Comment by MarjieAVolk** [comment]
"when attempting to add a plot to my deed the game tried to look for a claim, found none and crashed" -- Was able to reproduce in 5.5.  Click "Attach Current Plot" button while not on a claimed area
