### ISSUE TITLE
klik

### ISSUE THREAD

**Issue by limon2233** [StrangeLoopGames/EcoIssues#10420]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10363
