### ISSUE TITLE
USER ISSUE: Tools do not break

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#10427]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
1. Use a tool to the point it becomes red
2. Keep using it endlessly

**Expected behavior:**
Tools should stop working a little time after they become highlighted in red

**Actual behavior:**
Instead it can be used forever

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it can be used forever

**Comment by elfl0rd** [comment]
Intended.
You loose lot of calories while you using damaged tool.

**Comment by D3nnis3n** [comment]
This is intended behaviour.
