### ISSUE TITLE
USER ISSUE: Multiple Tutorial messages are not deletable

### ISSUE THREAD

**Issue by Thorgrimm** [StrangeLoopGames/EcoIssues#10426]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
Restart Tutorial in Options Menu
- (do some tasks)
- restart Tutorial again while some tutorial tipps are still to be done
	

**Expected behavior:**
I guess you should be able to delete all tutorial messages with the red x	

**Actual behavior:**
The second tutorial messages can be deleted, the ones from the first tutorial not anymore, although the tasks are completed.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed
![unbenannt](https://user-images.githubusercontent.com/8145174/50395964-3690dc80-0767-11e9-9e65-63d43dd85d0c.JPG)

**Comment by BlazeGuy2** [comment]
Tutorials have been worked for me just on 8.0.0.  Reopen if occurs on next major release.
