### ISSUE TITLE
Infinte Logs

### ISSUE THREAD

**Issue by iflounder** [StrangeLoopGames/EcoIssues#1042]
So i found a bug if you place lumber than pick it up with an axe you get a raw log back. This is a problem because if you have efficiency you can make more than 1 lumber from a log ie creating infinite logs in the process and infinite pitch. Basically it makes it so you can have infinite wood products and fuel. Its kinda game breaking

**Comment by iflounder** [comment]
Same as the comment in issue #926

**Comment by craig-jong** [comment]
Fixed
