### ISSUE TITLE
0.7.8.6 tailings poluting vertically

### ISSUE THREAD

**Issue by ClaireRouge** [StrangeLoopGames/EcoIssues#10425]
The old issue about tailings is still the same even though you repeatedly have said in the releasenotes that it's fixed

the polution in the picture is from tailings at bedrock (about 50 blocks below) and it's the same as down there meaning tailings still polute everything in a chunk and isn't affected by being dug down as intended, last time it worked as intended was about 0.2 or 0.3 so you might want to look into the code of those versions to figure out what you changed that made the bug

![image](https://user-images.githubusercontent.com/43214154/50387326-8afd7300-06f9-11e9-93ff-0c17809589aa.png)

**Comment by Deantwo** [comment]
Tailings were totally changed, in v0.7 (?), so looking at code from v0.3 likely isn't very useful.

My guess is that pollution was there before and simply isn't dissipating currently?
It is intended that buried tailings still pollute, but it is supposed to take a long time before it reaches the surface. Many facts about tailings are still mostly rumors though.

**Comment by ClaireRouge** [comment]
The issue is not a question but a big report, I already tested the workings of tailings be the issue is the same as its been since v. 0.3 meaning it wasn't resolved any of the times it was claimed to be solved
And the code causing the error is likely the same as it was back then because I doubt the entire code regarding tailings was resolved

Additionally please refrain from sending messages intended to help players on git because that will likely cause people to disable the notifications making it hard for the devs to contact the author of they need additional information

**Comment by elfl0rd** [comment]
Attach a savefile.

**Comment by D3nnis3n** [comment]
How old is the world? Afaik tailings pollution is meant to reach the surface after a while no matter what you do. In any case, we indeed need the savefile, put it up on google drive or somewhere else and link it here, please.

**Comment by D3nnis3n** [comment]
Closing as this behaviour can no longer be observed and no savefile was provided. If this persists, open a new issue.
