### ISSUE TITLE
USER ISSUE: Stuck under Stockpile

### ISSUE THREAD

**Issue by GKNB1012** [StrangeLoopGames/EcoIssues#10428]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
1. Dig under stockpile, use shovel to dig dirt
2. accidentaly place dirt below yourself
3. Be stuck in a square of height 2 under stockpile, cant move any direction due to dirt
4. Can only interact with stockpile so cant dig myself out

**Expected behavior:**
Allowe me to dig out/dig dirt

**Actual behavior:**
I could only interact with the stockpile while below it

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods.

**Comment by BlazeGuy2** [comment]
Refer to elfl0rd's comment
