### ISSUE TITLE
(Suggestion or missing feature)Master: Wood debris doest not slow players

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10429]
Maybe it's missed...
But it's strange after plants slow players.

**Comment by elfl0rd** [comment]
It just seems weird.
Not slow
![default](https://user-images.githubusercontent.com/4980243/50442276-38959f80-090f-11e9-960e-ac34a9e2c8b1.png)

slow
![default](https://user-images.githubusercontent.com/4980243/50442301-4cd99c80-090f-11e9-8b92-3477463c7bd7.png)

:D @SeanAtr0n do you think?

**Comment by Nicolausi113** [comment]
This could be the missing motivation to remove debris, most players don’t care about stumps and wood pulp.

**Comment by BitsBytesGaming** [comment]
I'm sure players would care about stumps and wood pulp, considering that failure to remove them results in negative consequences for the ecosystem.

**Comment by RobertBrunhage** [comment]
New to the game here and my input may help. As a new player, I didn't care at all about them until I researched how to get new trees growing. So my opinion would be to give more obvious consequences about stumps and wood pulp such as being slowed which forces the player to remove them.
