### ISSUE TITLE
USER ISSUE: Unable to Play

### ISSUE THREAD

**Issue by FallingSkye** [StrangeLoopGames/EcoIssues#10422]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
open game, click continue

**Expected behavior:**
let me play non-server worlds

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by Deantwo** [comment]
As @elfl0rd mentioned, there were some changes that might have broken the Continue button in v0.7.8.6, so try just using the Load World option instead.
For more direct help you can ask in the #offical-support channel on the [official Eco Discord server](http://discord.gg/eco).

**Comment by BlazeGuy2** [comment]
Reopen if the suggested solutions don't help.
