### ISSUE TITLE
Server - 7.8.6 - Corrupted .eco File

### ISSUE THREAD

**Issue by Z0tt3l** [StrangeLoopGames/EcoIssues#10424]
Hey,
my girlfriend and me were playing ECO in a game wich was hosted at my machine. The game was hosted by starting the game with eco.exe (not ecoserver.exe). The game was shut down correctly from the ingame buttons. While we wanted to continue the game today, Steam expected the game in a wrong folder (I switched my Steam-Folder some months ago). Fixed this Issue by reinstalling the game in the correct folder after I saved the save files from the Server\Storage folder. But it was not possible to start the game. Unfortunately no backups.... (I know, my fault)

What I tried?
- Start the Game
- Continue the "Borwin" world

What happened?
- Exceptions were thrown and world file seems to be corrupted

What I expected
- a working world while the last days/weeks

No mods were installed

Error from client while resuming the game:
https://pastebin.com/rkkC2a0q

Error from server while resuming the game:
https://pastebin.com/TbYbaN70

Corrupted world:
https://drive.google.com/file/d/1Z9La7Kd-u5HN6f7E7eF08I1SzIjsi61-/view?usp=sharing

**Comment by beastyn** [comment]
Didn't meet in 8.1.
Make backups!
Please reopen if issue is actual.
