### ISSUE TITLE
USER ISSUE: Glitched/Stuck inside Campsite

### ISSUE THREAD

**Issue by Wyattagum** [StrangeLoopGames/EcoIssues#10438]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
1. Use the Wheelbarrow
2. Roll next to your campsite 
3. Unuse Wheelbarrow

**Expected behavior:**
Teleport me away from glitched area/outside of the camp

**Actual behavior:**
Got me stuck inside with no way out...

**Do you have mods installed? Does issue happen when no mods are installed?:**
No modpacks that I know of

**Comment by Wyattagum** [comment]
p.s
the wheel barrow was 10m away from the campsite!

**Comment by elfl0rd** [comment]
try /unstuck

**Comment by BlazeGuy2** [comment]
Couldn't get this to repro. Could you send me a clip of this occurring @Wyattagum?  /unstuck command should also take you out of the stuck position.

**Comment by Wyattagum** [comment]
I'll recreate it, I got out by picking up the camp and placing it back
down. Also I sometimes glitches through the terrain. I suppose that is one
factor in this glitch. The game probably tried to lplace my on solid ground
or I kept glitch ingredients through the terrain at random directions. Like
how energy escapes from the sun. Bouncing off of particles for decades,
centuries, millennials

**Comment by D3nnis3n** [comment]
Did you get the video?

**Comment by D3nnis3n** [comment]
Closing this for no response. Reopen if it reoccurs.
