### ISSUE TITLE
(partially suggestion) No "full" offline mode

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10437]
Eco does not support full offline mode when you can use the application without connecting to the Internet.
It is also quite embarrassing that the requirement of a connection at startup is not specified on the SLG site and is not specified as mandatory in Steam.

Some users want "full offline" using, i agree that this is necessary.

**Comment by elfl0rd** [comment]
The current protection is aimed more at authorization on servers rather than protection against piracy. Authorization is not needed for single player.

And this "protection" is not really protect from crackers.
![default](https://user-images.githubusercontent.com/4980243/50492273-cd8bbc00-0a27-11e9-8ee5-6235896e0ae1.png)

**Comment by Nicolausi113** [comment]
I strongly disregard piracy!
Do you think of distributing game on DVD with a protection code – would be a possibility if the game is in a more finish state.

**Comment by elfl0rd** [comment]
DVD is obsoleted format.

**Comment by D3nnis3n** [comment]
In fact studies have shown games without piracy protection get less piracy than the ones with protection. And funnily, the ones with piracy protection usually have issues that stop legit players from playing while pirating players are not stopped, in turn causing buyers to pirate it just so they can play it. I think a full offline mode is required and should be there.
