### ISSUE TITLE
When placing world objects on plants, some plants get destroyed and some don't

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1043]
I placed this chest on top of two wheats.  One got destroyed and one didn't.

![image](https://cloud.githubusercontent.com/assets/23460210/22449433/0e9cce56-e715-11e6-965d-ae2643bca636.png)

**Comment by iflounder** [comment]
this probably has to do with it not checking to see if it destroys the second block. Ie this is a bug in placing structures larger than 1 as the game doesnt check if it destroys something in the other spots
