### ISSUE TITLE
[Site] no system requiments on official SLG site

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10436]
It was quite strange not to find them, given some things like the need for an Internet connection to check the license.

**Comment by Nicolausi113** [comment]
Not on SLG site but in Wiki
![minsys2](https://user-images.githubusercontent.com/38510829/50491744-218ca580-0a14-11e9-8699-b3f6a5dcc1d8.jpg)

**Comment by elfl0rd** [comment]
And on steam, i know.
But wiki is secondary resource.

**Comment by BlazeGuy2** [comment]
Should have system requirements on website where we sell the game.

**Comment by rainfarmer** [comment]
its on the buy page now
