### ISSUE TITLE
USER ISSUE: huckleberries not growing

### ISSUE THREAD

**Issue by alt2035** [StrangeLoopGames/EcoIssues#10432]
**Version:** 0.7.8.6 beta

**Steps to Reproduce:**
none as they dont grow

**Expected behavior:**
should grow	

**Actual behavior:**
they dont

**Do you have mods installed? Does issue happen when no mods are installed?:**
they dont

**Comment by D3nnis3n** [comment]
Did you plant them in a area where they are good to grow? If yes, could you send us the savefile and tell us the coordinates where you tried to grow them?

**Comment by BlazeGuy2** [comment]
Reopen if more info is provided @alt2035.
