### ISSUE TITLE
The completion of the backpacks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10434]
### **No information about general backpacks differences ingame. What is "bearpack"? He better than "Work backpack" or not?**

- [ ] **1) Backpack need info about bonuses.**

In item (backpack) tooltip.
As i know

> Basic Backpack - +5 kg.
> Big Backpack - +10kg
> Bearpack - +15kg
> Light Backpack - +5kg +movement speed
> Work Backpack - +5kg +decreases calories consumption

This bonuses work in the master, but for players - only wiki can show information about bonuses.
![default](https://user-images.githubusercontent.com/4980243/50448247-05640800-0931-11e9-854e-a093d3244784.png)

### (_Low priority_ issue) - **All backpacks have same icon. It's confusing.**

- [ ] **2) Backpack icon need differences.**

![default](https://user-images.githubusercontent.com/4980243/50448264-24629a00-0931-11e9-80ac-2fc3f40f3f3d.png)
![default](https://user-images.githubusercontent.com/4980243/50448266-2a587b00-0931-11e9-9fc8-c3bfe652adb2.png)
![default](https://user-images.githubusercontent.com/4980243/50448274-380e0080-0931-11e9-9435-b7bbfdb49996.png)
![default](https://user-images.githubusercontent.com/4980243/50448281-43612c00-0931-11e9-9282-ab9434d0bcff.png)
![default](https://user-images.githubusercontent.com/4980243/50448287-4a883a00-0931-11e9-8ebd-4048e8e27b58.png)

I think adding icons would be enough...
_For example_
![default](https://user-images.githubusercontent.com/4980243/50448559-0e55d900-0933-11e9-816a-536b3f9e1b56.png)

**Comment by Deantwo** [comment]
Same with other clothing items that have bonuses.

**Comment by BitsBytesGaming** [comment]
(unrelated) Same with rivets and screws (same texture).
