### ISSUE TITLE
Public crafting tab of economy viewer shows wrong tables

### ISSUE THREAD

**Issue by alexarthur94** [StrangeLoopGames/EcoIssues#10441]
Since the update to 7.8.6, the Public Crafting Tables tab of the Economy Viewer doesn't just show public crafting tables. Rather, it shows each player any and all crafting tables they are authorized to use, whether the table is their own table, an unowned table, a table authorized for everyone, or a table that someone has specifically authorized them to use. It's not a huge problem, but it is a bit awkward and probably wasn't intended to work that way.

**Comment by elfl0rd** [comment]
I more like new behavior... But ofc, tab need to be renamed.
Option to swith behavior (or filter maybe?) will be nice too.

**Comment by alexarthur94** [comment]
I personally prefer the old behavior, although if you could see either that would be fine, too.

**Comment by elfl0rd** [comment]
nope, this is new issue about new behavior.

**Comment by beastyn** [comment]
I don't think its a bug, seems like it is intended behavior.
@Quadbro @johnkslg 
Is it intended?
Did you talk about this from design point of view, should it be remastered?

**Comment by Quadbro** [comment]
@beastyn yeah, that's an intended behavior, it's made in change of old one, and probably can be improved somehow in future, or not)
