### ISSUE TITLE
USER ISSUE: Campsite disappeared in multiplayer

### ISSUE THREAD

**Issue by Spuddow** [StrangeLoopGames/EcoIssues#10445]
**Version:** 0.7.8.7 beta

**Steps to Reproduce:**
1. Joined a multiplayer server
2. Went to a friend's claim to join him
3. Tried placing my camp but they hadn't given me access yet.
4. I moved across to the edge of the plot to put the camp down (I just tried placing on each square until it didn't say I was unauthorised to place)
5. When I tried placing one block out of the claim, the camp disappeared from my inventory but didn't appear in the world.

**Expected behaviour:**
Placed the camp down or told me it was in someone else's claim.

**Actual behaviour:**
Campsite was removed from my inventory but didn't appear in the game.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I'm not sure how mods work on multiplayer servers but I am on the gods of war EU server

**Comment by elfl0rd** [comment]
lol, confirmed.
![default](https://user-images.githubusercontent.com/4980243/50541829-1033cc80-0bbf-11e9-88e3-f6f08ccb85e2.png)
![default](https://user-images.githubusercontent.com/4980243/50541832-1c1f8e80-0bbf-11e9-8894-bb1036e20aa8.png)
![default](https://user-images.githubusercontent.com/4980243/50541835-25a8f680-0bbf-11e9-8bbd-d004e22f08ab.png)
![default](https://user-images.githubusercontent.com/4980243/50541836-2f325e80-0bbf-11e9-99d3-2d6d4a4cd964.png)

**Comment by elfl0rd** [comment]
Another user with same issue
![default](https://user-images.githubusercontent.com/4980243/51074120-31e78600-168c-11e9-9a32-b73909bde446.png)
