### ISSUE TITLE
Destroy anything

### ISSUE THREAD

**Issue by iflounder** [StrangeLoopGames/EcoIssues#1044]
So this is a glitch that is super useful yet kinda cheating all at ounce. You can destroy any object by using a wooden cart or really any thing with storage that can be picked up. Simply open its inventory make sure its empty click off the inventory and break down the object without closing the inventory. Now anything that is placed in that inventory is deleted. 

Uses:
Destroying tailings **** SUPER CHEATY****
Destroying stupid cart deeds *YAY*

**Comment by AkibaNiashomi** [comment]
Very useful if you have 20 deeds laying around (like me). Thanks!

**Comment by Syrkaz** [comment]
Thank you for this! Perfect way to get rid of those pesky deeds...
