### ISSUE TITLE
USER ISSUE: Bugs,Bugs,Bugs

### ISSUE THREAD

**Issue by kuxii2016** [StrangeLoopGames/EcoIssues#10452]
**Version:** 0.7.8.7 beta

**Steps to Reproduce:**

**Expected behavior:**
Pixel over Pixel in the Screen

**Actual behavior:**
Unplayable with the Nice Grafik Bugs.!!!

**Do you have mods installed? Does issue happen when no mods are installed?:**
Unplayable with the Nice Grafik Bugs.!!!

https://cdn.discordapp.com/attachments/393509686487285763/529689134684438528/VID-20190101-WA0006.mp4

**Comment by elfl0rd** [comment]
Duplicate of #10082
