### ISSUE TITLE
Player is always sprinting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10453]
Seems to be locked to 'on' somehow.
Skill/talent related?

**Comment by SeanAtr0n** [comment]
Looks like you aren't running, MovementSpeed is constantly getting updated to 5 now by view changes where it used to be 3

If we are actually going to use this functionality we should probably make it pass some sort of multiplier instead so we can apply it to run as well... currently run speed is 4.6 so you can now walk faster than you run

**Comment by craig-jong** [comment]
can pass a multiplier.

The problem right now is that talent values send 1 as a default if they dont have a base value set, so its sending 5 instead of 3. I fixed it, but we can get it to something better as well.
