### ISSUE TITLE
Server doesn't start, crashes immediately - Discord Report

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10450]
> --BEGIN DUMP--
> Dump Time
> 12/30/2018 20:38:12
> 
> Exception
> Exception: MissingMethodException
> Message:Method not found: '!!0[] System.Array.Empty()'.
> Source:EcoServer
> 
> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)
>    at Eco.Server.MainClass.Main(String[] args)
> 
> --END DUMP--
> 

![20181231_124742](https://user-images.githubusercontent.com/25908592/50568175-9599b700-0d4e-11e9-80d1-03b06268abd7.jpg)

What could be the cause?

Server is downloaded through steam - most recent version.

**Comment by elfl0rd** [comment]
looks as configs\mods issue... This happens with you?

**Comment by D3nnis3n** [comment]
Fresh Installation from a german discord user.

**Comment by elfl0rd** [comment]
He have eco installed on pc? Check .net version.
Maybe .net installation missed in server package, lol.

**Comment by D3nnis3n** [comment]
Yes, on his own computer.

**Comment by elfl0rd** [comment]
hm... server in game package work but not work server from server package? On one pc? correct?

**Comment by D3nnis3n** [comment]
Yes, on all of his computers.

**Comment by SlayksWood** [comment]
Can't reproduce for latest version. If it happens again, please reopen.
