### ISSUE TITLE
Master: Character movement animations broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10454]
(3rd view, can someone check fpv?)
![r](https://user-images.githubusercontent.com/4980243/50615218-9bc99800-0ef4-11e9-8f6f-0527c1c97126.gif)

**Comment by SeanAtr0n** [comment]
any errors in your log file / console? it's working fine for me

**Comment by elfl0rd** [comment]
> NullReferenceException: Object reference not set to an instance of an object
AvatarAnimationManager.UpdateState () (at Assets/Scripts/Utils/AvatarAnimationManager.cs:275)
AvatarAnimationManager.LateUpdate () (at Assets/Scripts/Utils/AvatarAnimationManager.cs:200)

**Comment by SeanAtr0n** [comment]
so that error was repeating?

how did you transition into thirdperson to make this happen?

**Comment by elfl0rd** [comment]
1) yes.
2) f5

**Comment by elfl0rd** [comment]
yes, fixed - thx!
