### ISSUE TITLE
0.5.3 [Wooden Cart, Realism] Speed keeps increasing downhill on ramps

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1045]
Wooden carts seems to be speeding seemingly endlessly during downhill decent on ramps. They appear to keep their speed when you reach flat ground, but decrease quickly again climbing a new ramp.

Easily reproducible.

Suggestion: If the speed is too high, the player will get knocked off the cart.

**Comment by SeanAtr0n** [comment]
fixed in 5.5
