### ISSUE TITLE
Frequent hitching

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10462]
While playing the game, lots of small pauses are happening.  This was happening for me both when I was travelling around the world and hanging out in one spot setting up camp. Hitches are about .3 seconds I would estimate.

**Comment by elfl0rd** [comment]
Maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10136
And maybe dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/10254

**Comment by metachronism** [comment]
too generic
lots of this was due to needless one-line "refactoring" that introduced lots of garbage
