### ISSUE TITLE
0.5.3 [Wooden Cart, Bug] Road efficiency on dirt/stone changed from 80% to 0% after being offline ~8h

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1046]
When I logged on this morning, I couldn't move the wooden carts, and saw that they both had road efficiency set to 0%.

Fixed the issue by emptying the carts, removing them and placing them down again.

UPDATE: This seems to be the case every time we've been offline for an extended period of time. May also have something to do with the server being stopped and started again, I have not checked that yet.

**Comment by SeanAtr0n** [comment]
should be fixed in 5.5
