### ISSUE TITLE
Brush sounds are too much

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10466]
Running around in the world, I heard these non-stop and they made me want to turn off sound effects.  Should either be much more subtle, or disabled.  I would suggest disabling, till we get a new sound guy and do a pass on sound, unless you want to find some quiet ones.

**Comment by elfl0rd** [comment]
haha, like me after working with a chainsaw! :dagger: 
https://github.com/StrangeLoopGames/EcoIssues/issues/10206
