### ISSUE TITLE
 Food tutorial not appearing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10465]
Appeared once I finished the forage tutorial, finally.

**Comment by johnkslg** [comment]
Should appear once I have any food in my inventory.

**Comment by Quadbro** [comment]
triggered any time i tested with wild food or just inventory trades, can't reproduce, even >=5 tutors on screen, still working 
![image](https://user-images.githubusercontent.com/6802030/51730726-2bed9e00-20ab-11e9-9938-a360e94cd4a5.png)
