### ISSUE TITLE
Confusing popup when learning a specialty

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10475]
![image](https://user-images.githubusercontent.com/3536496/50619605-ef18f780-0eae-11e9-9f54-5c5dc93438ef.png)
Lets show the cost on the 'learn specialty' button, instead of on the popup.
Also, what does it mean to lower specialty experience gain?

**Comment by elfl0rd** [comment]
In addition, there is no any information about unavailable unlearning...
https://github.com/StrangeLoopGames/EcoIssues/issues/10285
