### ISSUE TITLE
0.5.3 [Wooden Cart, Bug] Only one player can use carts at a time

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1047]
When playing as 2 people on a lan server, only I could move the carts, and the other player was not able to move them. I did not check the road efficiency as I was quite new to the game, but I will investigate further.

We tried multiple times, and at one point the other player managed to control a cart. When I tried to control it just afterwards, I got the same problem as him.

Suspicion: Carts are fixed to a client side position, and get bugged when multiple people try to move them before the position is stored on the server.

EDIT: Both players are marked as authorized by the deed items.

EDIT2: It seems the cart is usually fixed to the player who placed it, and can not be moved by another player until it "anchors" its position to the other player. This can apparently happen if the owner spends time offline, while another player is online or logs in.

**Comment by iflounder** [comment]
Ive used a cart that belonged to someone else on multiple occasions without be authorized to the deed. Im pretty sure this only happens if you click the locked button which locks to the owner only?

**Comment by AkibaNiashomi** [comment]
On further experience, it seems that when placed, the carts will align to the first person who logged onto the server at all times. If that person logs off, when a new cart is placed, it will align to the person who next logged onto the server (this has only been tested using 2 users). The already existing carts will still be aligned to the player who logged off. To fix this, the cart will either have to be replaced, or everyone needs to log off the server, so that the existing carts will align to the first player to login to the server again.

Addition: It seems that authorization is only meant for accessing the contents of the cart when it is locked. This makes the deed item useless if you do not want to restrict acess to the contents. It works exactly like chests. Any player, authorized or not should be able to move the cart, as far I know.

**Comment by SeanAtr0n** [comment]
Fixed in 5.5
