### ISSUE TITLE
Skills window broken or confusing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10474]
![image](https://user-images.githubusercontent.com/3536496/50619463-3357c800-0eae-11e9-96ee-6519b5e964b4.png)

Wasnt clear what I should do here or how it works.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/50619517-76b23680-0eae-11e9-8007-f4a9478b23f4.png)
Talents missing tooltips

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/50619524-7f0a7180-0eae-11e9-81b7-c21cc5417255.png)
Couldnt tell this was an XP bar, need some more indicators

**Comment by johnkslg** [comment]
Ah, closing and reopening fixed something:
![image](https://user-images.githubusercontent.com/3536496/50619595-de688180-0eae-11e9-9ef9-b1c131621750.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10250
https://github.com/StrangeLoopGames/EcoIssues/issues/10381
