### ISSUE TITLE
Demographic tooltip not showing 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10470]
![image](https://user-images.githubusercontent.com/3536496/50619317-677eb900-0ead-11e9-881a-2b6e446a6f93.png)
#

**Comment by mirasrael** [comment]
Can't reproduce on latest master
![image](https://user-images.githubusercontent.com/475445/50876909-75b66300-13e0-11e9-992a-b0f20b6416e4.png)
