### ISSUE TITLE
Funny highlighting on block

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10487]
![image](https://user-images.githubusercontent.com/3536496/50620101-6bf9a080-0eb2-11e9-8814-d57c2c30f912.png)
Sandstone?

**Comment by redwyre** [comment]
Right now I'm only getting it on GoldOre
![image](https://user-images.githubusercontent.com/431728/50699529-dcabe300-1093-11e9-9891-219cd7891728.png)

For some reason the CustomerRangeMeshBuilder doesn't render the rocks properly. I've fixed more subtle cases with variations and decorators, but this still remains a mystery.
