### ISSUE TITLE
Empty handed take doesn't do anything on mini stockpile

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10486]
![image](https://user-images.githubusercontent.com/431728/50620018-b9285180-0f48-11e9-90ec-aeaaff7e2e8c.png)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/10374?

**Comment by Quadbro** [comment]
yeah, see the problem with carried items only, and yes, its related to that issue
