### ISSUE TITLE
0.5.3 [Interface, Enhancement] No crosshair

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1048]
No crosshair or method of telling where you're pointing whatsoever. This makes for a very difficult building process when placing on thin wood for example.

It is however understandable as hunting for instance, becomes more difficult and realistic.

**Comment by Syrkaz** [comment]
This is huge!! This needs to get added ASAP, even if as an option...

**Comment by MarjieAVolk** [comment]
Craig, you added the crosshair for the bow, right?  Could we have a crosshair that is always on?  Could be an option on the settings menu to turn it off.

**Comment by craig-jong** [comment]
This was added by Eric, but the hunting crosshair is significantly too intrusive to use as a placement crosshair in my opinion. Having an option to turn something on, however, isn't the worst idea.

**Comment by metachronism** [comment]
highlighting and ghost placement should make this a non-issue

crosshair was added to the bow
