### ISSUE TITLE
Workbench making hammering noise with only finished job

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10488]
[Hammering noises]
![image](https://user-images.githubusercontent.com/431728/50620224-0bb63d80-0f4a-11e9-971b-9235b323614f.png)

**Comment by elfl0rd** [comment]
Duplicate of #10402

**Comment by SeanAtr0n** [comment]
separate issue

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/51280945-de2fb200-1995-11e9-9c81-0d5b2161975d.png)
seems related to ^

**Comment by johnkslg** [comment]
Can you help me sort this one out Sean? Since you were doing stuff with workorders recently.
