### ISSUE TITLE
Roof Builder Inner Corner piece issue

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10483]
![image](https://user-images.githubusercontent.com/3536496/50619871-e1647180-0eb0-11e9-871d-88c905df6156.png)

**Comment by keegan-o** [comment]
This was just a block building error unfortunately, not able to repro.

**Comment by elfl0rd** [comment]
Ez
![default](https://user-images.githubusercontent.com/4980243/51231821-db24c980-1975-11e9-82b9-48c60652693d.png)
![default](https://user-images.githubusercontent.com/4980243/51231843-f1cb2080-1975-11e9-90ea-635d15d46b0e.png)

**Comment by redwyre** [comment]
Looks like there's a problem with the roof builder:
![image](https://user-images.githubusercontent.com/431728/51258349-7e68f380-19f5-11e9-8b9e-9ca124785ffc.png)

This happens with all roof types

**Comment by keegan-o** [comment]
Aha, sure-- it's a builder problem, not a texture problem.

**Comment by keegan-o** [comment]
I will note you can also fix it by just putting roof blocks in the intuitive place there-- one way to help this issue will be to have flat roof forms for all building types, too.

**Comment by SlayksWood** [comment]
dup #3786
