### ISSUE TITLE
Can't turn this dirtblock into road

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#10494]
![toolbug](https://user-images.githubusercontent.com/35509188/50655833-30101b00-0f46-11e9-890a-db1cb45407a4.PNG)

Block highlighted wouldn't change to dirt road.

**Comment by BitsBytesGaming** [comment]
The block in question may be "rooted" by a tree stump, try the following:
1. Using the road tool on nearby blocks, to see if a pattern is present (consistent with former suspected examples of this that I've seen).
2. Using a shovel on the dirt block, which should quickly reveal if this is the issue (via a message in your chat box).

**Comment by craig-jong** [comment]
this is fixed
