### ISSUE TITLE
[7.8.8] ServerCrash InvalidDataException

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#10492]
See enclosed dump files.

Server version 7.8.8 under Windows, crashed hard this morning and I had to restore from a backup. The first dump is from the server log prior to crashing, the other 2 are from 2 boot attempts

https://pastebin.com/9hVQF92t

**Comment by SlayksWood** [comment]
If the crash repeats on the new version reopen please .
