### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by eco19** [StrangeLoopGames/EcoIssues#10497]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection Failed
```

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10321
