### ISSUE TITLE
Give better version error feedback to user in client

### ISSUE THREAD

**Issue by eco19** [StrangeLoopGames/EcoIssues#10493]
**Version:** 0.7.8.7 beta

**Steps to Reproduce:**
rr

**Expected behavior:**
o

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Incompatible version.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Incompatible version.
```

**Comment by Deantwo** [comment]
Beta version 7.8.8 was released yesterday. Please confirm with the server owner that it is running a different version then you, which it appears to be.

Devs, why doesn't the "Incompatible version" error say what version the server is running? Would help in identifing these issues faster.

**Comment by BlazeGuy2** [comment]
Updated error msg, should show up in 8.0.
