### ISSUE TITLE
0.5.3 [Items, Realism] Carrying a full stack of carry-only items on a spade

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1049]
If you place a full stack of dirt/stone/coal etc. from an inventory onto your "Carrying" slot, you will be able to carry up to a full stack of items while your shovel only shows you holding one.

This seems very unrealistic.

**Comment by XerWolf** [comment]
While this may be a bug, this shouldn't be fixed.  It's way to too tedious to have to carry 1 at a time.  I would suggest even allowing shovels to grab the largest stack available from a chest when interacting with it.

**Comment by MarjieAVolk** [comment]
Yep gonna close this as a duplicate
