### ISSUE TITLE
PipePortAttachment using incorrect material

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10490]
The prefab is using the "SuitMaterial" from realistic eye movement. There doesn't seem to be an existing material to use, but I'm not sure if this object should get revamped as part of the pipes split, or removed completely as part of @johnkslg pipe changes

**Comment by D3nnis3n** [comment]
Could you assign a more fitting label for this issue if it is still actual? The "needs information" label is for information by the issue creator.

**Comment by WeaselDog** [comment]
Please reopen if this is still an issue. Pipes seem to look okay and there will be more updates soon.
