### ISSUE TITLE
Inventory issues

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10508]
1. 
Trying to put an item in a container with right click that is full doesn't give a message.
If you have the interaction cursor down low enough, and are trying to put in seeds, you get the message "Cannot plan on an untilled block" so it looks like the interaction is falling though

2. interaction text doesn't always update after inserting:
![image](https://user-images.githubusercontent.com/431728/50673526-15af6d80-102a-11e9-9415-62db66239647.png)

![image](https://user-images.githubusercontent.com/431728/50673529-206a0280-102a-11e9-99d3-9b8d5c5c9267.png)

3. "Take" doesn't say what you'd be taking from eg a chest

4. Still says "Take" even though you don't have a free inventory slot selected

5. Can't put torches or meteorite fragment in containers with right click

**Comment by BitsBytesGaming** [comment]
The game probably checks the active item at the point where two factors are present:
1. You are close enough to the object in question to interact with it (duh).
2. Your character has its mouse cursor over/in-line with the given object.

If that is correct, then it would be advisable to check the active object both before and after an external interaction with an object has been completed (i.e. one that does not involve the inventory panel).

**Comment by Quadbro** [comment]
4. Still says "Take" even though you don't have a free inventory slot selected
It will try to refil selected item

3. "Take" doesn't say what you'd be taking from eg a chest
Predicting what you will take from a chest is painfull to implement, because server decides it deeply in inventory change sets
