### ISSUE TITLE
USER ISSUE: hm weird log issue

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#10500]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
Get a steam Truck
Crash steam truck into water

**Expected behavior:**
not effect gameplay

**Actual behavior:**
Causeing inability to access stores or chests and when relogging causes game to take 3 or more tries to log back in

**Do you have mods installed? Does issue happen when no mods are installed?:**
Causeing inability to access stores or chests and when relogging causes game to take 3 or more tries to log back in

**Comment by Spaceferret42** [comment]
No mods installed

**Comment by BlazeGuy2** [comment]
Crashed 2 steam trucks into water, can access stores and chests just fine.

**Comment by Spaceferret42** [comment]
interesting try going on a bridge with 90 degree turn and falling off the bridge at the turn that's how I crasher

**Comment by Spaceferret42** [comment]
just discovered it is actually related to another issue where the server thinks me and my steam truck are one place and the client shows me somewhere else and occasionally they disagree as to weather or not i am currently driving the steam truck

**Comment by D3nnis3n** [comment]
Then this has probably to do with this: https://github.com/StrangeLoopGames/EcoIssues/issues/9289
