### ISSUE TITLE
[0.8.0.0][Artwork] Sand looks horrible when digging lower

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10514]
**Version:** 0.8.0.0 beta master-375c24eb

![snap3617](https://user-images.githubusercontent.com/29383891/50698564-27e6d700-103d-11e9-856c-d302404489e4.png)

**Comment by elfl0rd** [comment]
same for clay - https://github.com/StrangeLoopGames/EcoIssues/issues/10501
