### ISSUE TITLE
Master: Profession benefits - incorrect numbers.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10517]
56% or 55%? :)
![default](https://user-images.githubusercontent.com/4980243/50703047-e7e71a80-1063-11e9-9d6e-5b9161764a09.png)

**Comment by BitsBytesGaming** [comment]
It might be an issue with rounding or some other math error, but I'm assuming the icon takes the value from the tooltip, and not vice versa.
