### ISSUE TITLE
Master: Self improvements have "shovel" (unavailable for players) in benefits.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10519]
![default](https://user-images.githubusercontent.com/4980243/50704351-1e269900-1068-11e9-9691-537a7304a7aa.png)

**Comment by BitsBytesGaming** [comment]
"Shovel" doesn't seem like it's even intended to be available to players. It looks like they just gave it no recipe in order to use it in the context of the tooltip menus.

**Comment by johnkslg** [comment]
Yes this should be marked category("hidden") to prevent it appearing.  Axe too.
