### ISSUE TITLE
Master: "Room Materials:" tooltip

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10513]
Cover only "room volume" please expand over "Tier" too.
![default](https://user-images.githubusercontent.com/4980243/50697565-9f276580-1053-11e9-9695-d736ee98eec4.png)

@Quadbro ?

**Comment by BitsBytesGaming** [comment]
The room materials tooltip should already appear when the tier/tier value is moused over.

**Comment by D3nnis3n** [comment]
Can reproduce.
