### ISSUE TITLE
0.5.3 [Tree, Mechanic] Chopping down a newly sprouted tree

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1052]
This teensy bit of log is apparently too big to pic up, and chopping it up gives me more than 10 logs. Chopping it down was also really difficult because of the little model.
![image](https://cloud.githubusercontent.com/assets/25452139/22458471/fd1a24e8-e79c-11e6-9cde-9736138fa483.png)

**Comment by XerWolf** [comment]
Tree should disappear or give you some wood pulp the same way using a shovel on certain plants

**Comment by craig-jong** [comment]
nevermind, you fixed this
