### ISSUE TITLE
tools require granite

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#10527]
granite why

**Comment by elfl0rd** [comment]
Yea granite needed to craft stone tools, but for repair used sandstone.
And you cannot gather granite using stone tools...
gathering plant fibers without scythe is painfull, lol

**Comment by BitsBytesGaming** [comment]
If you need plant fibers, just grab your steam tractor and harvester attachment and go to the nearest open field.

**Comment by elfl0rd** [comment]
facepalm...
Okay, steam tractor for user without research table...

**Comment by BitsBytesGaming** [comment]
...why can't people have a little humor sometimes...
