### ISSUE TITLE
UI should be draggable offscreen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10529]
![image](https://user-images.githubusercontent.com/3536496/50716835-5a420580-1038-11e9-8dae-08f97f59701a.png)
Right now you cant even drag it to the edge. You should be able to drag it to the edge and beyond.

**Comment by Spydarlee** [comment]
Are you getting this on master, @johnkslg? Dragging off screen seems to work fine for me. This gif is from the editor but I also tested on the latest 8.0 Steam Build and it's fine there, too.

![ecodragoffscreen](https://user-images.githubusercontent.com/553695/50772417-a0d86f80-1285-11e9-9cc0-ea9bd66c22ac.gif)

**Comment by redwyre** [comment]
If you let it go near the edge, it snaps away from the edge. I just checked on master

Let go here
![image](https://user-images.githubusercontent.com/431728/50774338-e5442980-12de-11e9-8d76-8f7376520c88.png)

Snaps to here
![image](https://user-images.githubusercontent.com/431728/50774353-ed03ce00-12de-11e9-8152-b202340fb319.png)

**Comment by elfl0rd** [comment]
I think that the restriction should be softer, not fully remove.
Just in any case, part of the window title should be visible.

**Comment by D3nnis3n** [comment]
Can also reproduce and would love to be able to drag those things to the end and over the screen in some cases when i need to get to another window but one is in the way.

**Comment by johnkslg** [comment]
Yeah its when you let it go off the edge, it shouldnt snap back.

**Comment by Spydarlee** [comment]
Thanks for the explanation, folks! I've changed this to be more lenient but it still snaps back somewhat to ensure you can't lose a window off screen completely.

I've set it to keep at least 25% of the window on screen (except when dragging off of the screen where the whole thing is kept visible to ensure you can still grab and drag the top bar).

Other than that you can drop a window anywhere you like. 👍 

![ecodragoffscreennew](https://user-images.githubusercontent.com/553695/50914634-e6846c00-142e-11e9-81a0-79dc6dce08a3.gif)
