### ISSUE TITLE
Placed Dirt will Not return or turn into Biome type

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10522]
**Version:** 0.7.8.8 beta

I deliberately Chose an area to live in with high sides, so i lived in like a valley, it took me awhile to do but all this has been built over with a single layer of Mortared Stone and then on top of that a Single layer of Dirt, so my Underground area is Hidden from View, **BUT** the problem is the Dirt that is there will **NOT** turn into what the biome should look like.
![snap3622](https://user-images.githubusercontent.com/29383891/50709725-a143f100-1060-11e9-85cf-609e9c4f69f9.png)
i know that ECO has a really long period of time for the Dirt to change what it looks like but this is never changing, and yes we had a couple of restarts, but its been online for days since it was done.
I also deliberately change my Deed Color to Black so that it **ONLY** shows natural Dirt, and building blocks in the minimap.
![snap3623](https://user-images.githubusercontent.com/29383891/50709878-2deeaf00-1061-11e9-948f-84797a907ac1.png)
this is the View Underneath i have since divided it into Large Rooms.

![snap3624](https://user-images.githubusercontent.com/29383891/50710050-cc7b1000-1061-11e9-9fe8-a2f144c8ae61.png)
it also has a river that ran underneath that i blocked off and Emptied of water.
![snap3625](https://user-images.githubusercontent.com/29383891/50710785-e1f13980-1063-11e9-90c7-f20625a91277.png)
Another View Angle showing a bit more of How big this is.

Is it natural for Eco to take so long to update dug/replaced Dirt?

**Comment by craig-jong** [comment]
Can you post a screenshot with the player activity overlay?

**Comment by Conchipedia** [comment]
![snap3626](https://user-images.githubusercontent.com/29383891/50714619-6ac2a200-1071-11e9-9cf0-bb78b99d00b8.png)
![snap3627](https://user-images.githubusercontent.com/29383891/50714620-6b5b3880-1071-11e9-9e10-72ff450de049.png)

it does look a bit Busy, but this is **above** where i'm walking

**Comment by Conchipedia** [comment]
so maybe i'm screwed with hoping that the above layer will change?

**Comment by BitsBytesGaming** [comment]
It seems this is acting similar to land claims, in that they apply to *all* blocks at the x, z coordinate, but extend "forever" in the y-axis. I suppose the game might be calculating the trample over *all* of the dirt blocks in the coordinate that is being trampled, and not specifically the blocks which are being walked over. Not sure about this because I haven't seen the code myself, would be interesting to hear from a more knowledgeable person on this specific topic.

**Comment by Conchipedia** [comment]
maybe have an Admin Command to reset Trample rate to 0 so that the world can refresh itself?

**Comment by craig-jong** [comment]
Yes, it's exactly as BitsBytes says. None of the layers are 3d so movement underground counts for trampled.

I can look into splitting this so we can just track aboveground movement, but it isn't something that will happen for 8.0.

Punting this.

**Comment by Conchipedia** [comment]
Would be a nice Improvement, but seeing as this can be a Major Adjustment of how the world layers are handled i will just be a patient **Ecoholic** and wait for when and if it appears 👍

**Comment by Conchipedia** [comment]
The ground turning back ti slightly improved in latest release 
![snap4219](https://user-images.githubusercontent.com/29383891/53541512-1b996a80-3b12-11e9-8977-c1283ae38ea4.png)
but still there are occasional patches of dirt that will not return to a near natural Biome state, at the moment it is slowly turning back ok, but no wild plants appearing in between deliberately planted Stuff
![snap4220](https://user-images.githubusercontent.com/29383891/53541667-cb6ed800-3b12-11e9-9ef0-c9f2138f5f8d.png)
natural on the right man made Filled in Land and planted stuff, still looking a bit bare
![snap4221](https://user-images.githubusercontent.com/29383891/53541722-0cff8300-3b13-11e9-8f29-fffc53aedc59.png)
also a weird thing with this **natural** appearing Palm it is saying very overcrowded but Eco naturally decided to grow it in this location, so not sure what is going on with the logic of things not growing if overcrowded but will grow naturally
![snap4223](https://user-images.githubusercontent.com/29383891/53541839-8f884280-3b13-11e9-9266-cad204e5ea87.png)

**Comment by redwyre** [comment]
That patch of dirt is tilled? Just dig it up an replace it for it to return to normal.

Are there natural plants on the edges of the area? Are they appearing from the sides?

**Comment by Conchipedia** [comment]
the Palm tree is on just dirt that had turned to natural Biome color it has not been tilled (which i would have expected to maybe give the message overcrowded as there are other palms nearby) the whole part of this is one block of dirt laid onto a roof of Hewn logs, most of the dirt has turned into Biome, maybe because it is still detecting trample from **underneath** is why the wild plants haven't started to appear to fill in the gaps between planted trees and plants, but the Update of the Biome itself is a whole lot quicker than it used to be, so that is a positive sign

**Comment by craig-jong** [comment]
I split the layers so this should no longer occur. It should be in 8.1, so I'm closing this issue.
