### ISSUE TITLE
0.5.3 [Nutrition, Realism] Placing items does not drain calories

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1053]
Placing wood and dirt all day, you would indeed have to break some sweat, don't you agree? :)

**Comment by craig-jong** [comment]
For sure, this is fairly important with the coming calorie changes.

**Comment by noblackthunder** [comment]
mhh though that could create a deadlock issue. Example You have 5 logs in hand and 0 calories .. you cant eat with logs in your hands but you cant just drop them on the ground ether . so you need first a method of dropping items some how first

**Comment by craig-jong** [comment]
Yea, this can't be added without a solution to that. ):
