### ISSUE TITLE
Master: reinforced concrete receipe broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10537]
![default](https://user-images.githubusercontent.com/4980243/50730380-1c8acd00-115d-11e9-821c-6ae8e45b41f4.png)

And what about rebalance? From reinforced rebars to reinforced concrete))
https://github.com/StrangeLoopGames/EcoIssues/issues/9761

**Comment by BitsBytesGaming** [comment]
I will agree that the ratios of the two ingredients of reinforced concrete are improper and should contain much more concrete per unit than rebar.

**Comment by elfl0rd** [comment]
lol, okay)) @craig-jong not fixed :D 
![default](https://user-images.githubusercontent.com/4980243/50829043-41956080-1354-11e9-988b-f84599fd1e79.png)

**Comment by elfl0rd** [comment]
(still not fixed)
