### ISSUE TITLE
Master: palm wood debris block - not all "targetable"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10532]
![default](https://user-images.githubusercontent.com/4980243/50717581-5c887c00-1099-11e9-9a05-3af825537400.png)
Can be targeted only over "own" block.
![default](https://user-images.githubusercontent.com/4980243/50717596-7fb32b80-1099-11e9-811f-00fa9ae047ea.png)
![default](https://user-images.githubusercontent.com/4980243/50717603-8772d000-1099-11e9-8587-48142b845333.png)

**Comment by keegan-o** [comment]
Fixed in master.

**Comment by elfl0rd** [comment]
nope.
![default](https://user-images.githubusercontent.com/4980243/50888454-bf19a900-1406-11e9-9822-66710a75e1b0.png)
![default](https://user-images.githubusercontent.com/4980243/50888494-d5c00000-1406-11e9-8277-7b5643947575.png)

**Comment by elfl0rd** [comment]
Okay, got svn update :D fine
