### ISSUE TITLE
Buying part of stores moving bar disappears

### ISSUE THREAD

**Issue by ShadowPauler** [StrangeLoopGames/EcoIssues#10539]
I just came across this today, and for the first time, that little bar on the right of my store disappeared no matter what I did so I couldn't move items up or down, nore remove them.

I don't know what causes this issue, but an easy solution is just to restart the game.

**Comment by D3nnis3n** [comment]
Is it related to this bug? 
https://github.com/StrangeLoopGames/EcoIssues/issues/9350

**Comment by BlazeGuy2** [comment]
@ShadowPauler Can you post pics/videos of this behavior?

**Comment by D3nnis3n** [comment]
Closing for no information, reopen when you can reproduce and can give a video or screenshot of the wrong behaviour.
