### ISSUE TITLE
USER ISSUE: Tool uses energy when holding broken.

### ISSUE THREAD

**Issue by Tindog33** [StrangeLoopGames/EcoIssues#10536]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
Holding a broken tool constantly uses Nutrition. I was holding Road Tool but noticed it with other tools as well.

**Expected behavior:**
Does nothing.

**Actual behavior:**
Holding a broken tool uses Nutrition like it was being constantly used.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Holding a broken tool uses Nutrition like it was being constantly used.

**Comment by elfl0rd** [comment]
You constantly use nutrition to generate skillpoints.
This is not refer to tools.

**Comment by D3nnis3n** [comment]
Tindog, is it already happening without holding a tool (see elfl0rds answer)?

**Comment by Tindog33** [comment]
No, so if you hold a broken tool your nutrition will go down as though your using the tool constantly, even if you're not using it. You keep getting little red marks going non-stop over the nutrition meter like -.075 and then it just keeps going until you switch tools. So holding a broken tool can drain all of your nutrition meter. I wish I had a picture, I would have to use up another tool again to reproduce it, it's happened several times.

**Comment by Deantwo** [comment]
> You keep getting little red marks going non-stop over the nutrition meter like -.075 and then it just keeps going until you switch tools.

How often is "non-stop"? Every hour? Every minut? Every second? Multiple times per second?

Have you tried reconnecting to the server? Restarted the server?

Do you have any mods installed on the server?

**Comment by D3nnis3n** [comment]
Yes, please answer these questions and add a video of it if possible.

**Comment by Tindog33** [comment]
So I don't know what happened, I haven't been able to replicate it again either. So you should probably close this post. If it comes up again. I will send a video. Yes, 0.075 is the amount that showed up. @Deantwo it was like 5 or so on the screen at the same time, every few seconds. We have restarted the server several times and updated it. I can't seem to replicate the problem either, it may have just been a glitch on our side, not to the game as a whole. I have no mods installed.

**Comment by Deantwo** [comment]
Thanks for the reply and attempt at replicating it @Tindog33.

You can close the issue yourself. If a mod closes it you won't be able to re-open it yourself, I think.

**Comment by elfl0rd** [comment]
yep, just use "close" button under comment field :)

**Comment by D3nnis3n** [comment]
He can reopen even if a contributor closed it, so i'll put the lock on it.
