### ISSUE TITLE
Review all colliders

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10546]
Use the chat commands to spawn all blocks and world objects. Check with Walker if you cant find these commands.
Make sure there's no insane colliders happening.

**Comment by elfl0rd** [comment]
@redwyre i can help if you explain me how, lol

**Comment by redwyre** [comment]
@elfl0rd Thanks for the offer but I'll handle this one ;)
@johnkslg Am I looking for mesh collider problems specifically? I'm not sure how to test occupancy.
