### ISSUE TITLE
"Reset Defaults" in graphics settings not reset sliders

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10541]
reset works only with check boxes, not sliders.
Same on release and master versions.
![default](https://user-images.githubusercontent.com/4980243/50733463-df472f00-119e-11e9-87eb-357a04bc56b2.png)

**Comment by BitsBytesGaming** [comment]
I suppose the "reset defaults" button only resets the toggleable settings shown, rather than all of them (as expected).

**Comment by elfl0rd** [comment]
what about FOV? Brightness? Interface Scale?
I think "reset defaults" return settings to playable, but in current state he revert only part of cosmetic settings!
