### ISSUE TITLE
Server/Player Desync's?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10543]
Players are complaining about suddenly being blocked by invisible trees sometimes after they have cut a tree down in that spot and other time when they just came to dig in that spot and no one else remembers having cut trees in that area or the player is in a single player game when no one else could have done so and they are positive they have not,   There are also complaints that they have just put a chest down and they stepped away and when they cam back the chest was no longer there.

It seems to be happening on every OS although more seem to be on windows 10 but that could be that just more play on windows 10.  I have not had anyone say this was happening on windows server, but again, that could just be that fewer are using one of the windows servers,

The problem is that the player goes to dig or build at a spot and gets a message that a tree is there when there is no tree seen and it will not let them dig or place a block to build in that spot.  Or they have placed a chest and started filling it and then the player steps away from it and when they come back its not there but if they try to put another chest down they are blocked by the chest they cannot see and they cannot interact with.

Player relog is sometimes all that is needed if its only one person with the issue.  If others on the server also say they are getting a message about a tree or have a chest that disappeared when placed (or both) then usually the server will need a restart,  Almost every time  a restart of the server solves this and about a third of the time just a player logging out and back in does so.

This seems like somehow the server has desync'ed with a player or players and this happens.  On questioning the players have either had no connection issues or were starting to see connection issues and noticed a good bit of lag about the time this starts happening,  

While the 'fix' for this is pretty easy - at most a server restart we have had a some server admins complain that they are getting requests every few hours from players with these invisible trees or missing chests to restart the servers,  They do not mind doing it but they may not always be there.   Some are solving this by making a scheduled task that restarts the server every 406 hours but they say that sort of breaks the immersion and since the save command is not reliably passed to the server every time they end up with a bit of a rollback also.

I am not sure what we could gather for you that would help look into this, like world saves or other information like a network log or if it would be worth looking into a admin command that would do a memory dump like some servers to resync

**Comment by metachronism** [comment]
fixed
