### ISSUE TITLE
0.5.3 [Cart/Interface, Bug] The map will not follow the player if it as been rotated, after moving again with a cart

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1054]
This is contrary to how it works on foot, where the map wil start following the player again if they move.

Workaround: Simply double click the "Follow Player" marker, or go out of the cart and move a little bit.

**Comment by MarjieAVolk** [comment]
Not seeing any problems with minimap follow player + cart as of 5.5
