### ISSUE TITLE
Fix orange text in tooltip

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10549]
![image](https://user-images.githubusercontent.com/3536496/50796676-332d4300-1287-11e9-84a6-0b776e2d796f.png)
Should be a nicer color.
This is defined in the ecostylesheet asset

**Comment by Quadbro** [comment]
@johnkslg On what color do you want me to change that?)

**Comment by elfl0rd** [comment]
Hmm... whats wrong with orange color? It's looks ok for me...
