### ISSUE TITLE
Picking pineapple does not yield fruit, but does destroy play.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#10559]
May be related to #9095. Not sure what maturity level the pineapple plant was at. 
![pineapple](https://user-images.githubusercontent.com/12839021/50804906-f07a6380-12a4-11e9-8bc4-7579fd659de7.png)

**Comment by craig-jong** [comment]
Yea, it shouldn't let you pick it up, but I also did recently add an override for this. So I'll check that out.

**Comment by keegan-o** [comment]
Pineapple revamp checked into master!
