### ISSUE TITLE
Placing ramps doesn't check occupancy?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10554]
![image](https://user-images.githubusercontent.com/774628/50801730-0d119e00-129b-11e9-8461-ba2bb405724f.png)
right ramp apparently didn't check for or kill the tree
left ramp on the left was placed intersecting w/ a block, then tried to place a 3rd to fix it but just ended up placing one piece

**Comment by D3nnis3n** [comment]
That's not necessarily a bad thing, though. We use that to quickly replace ramps. ;P

**Comment by elfl0rd** [comment]
partially refers to https://github.com/StrangeLoopGames/EcoIssues/issues/9669

**Comment by D3nnis3n** [comment]
Related to: https://www.youtube.com/watch?v=pDn_u7EgPxk&feature=youtu.be&t=3169

Just disallow placement of ramps in a way that would make them incomplete.
