### ISSUE TITLE
Need guidance with new stone types

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10553]
Game doesn't tell you anything about the different stone types or where to find them. Choosing a starting place where there isn't sandstone readily available makes it extremely difficult to progress.

Also can't make a fire without granite... requiring an iron pick axe??

**Comment by johnkslg** [comment]
Feature request: make a popup that tells you what mineral or species your pointer is looking at if you highlight it for awhile, and its a tooltip so you can mouse over it.

**Comment by seccombew** [comment]
Fixed
