### ISSUE TITLE
0.5.3 [Server] StackOverflowException at startup

### ISSUE THREAD

**Issue by darkdino** [StrangeLoopGames/EcoIssues#1055]
Trying to run Eco Server on a VPS machine and getting a StackOverflowException at "Initializing StorageManager..." step.

OS: Win Server 2012
Hardware: 2 vCores, 2 Gb RAM
Tried running as Administrator, tried with no world and with existing Game.eco file.

**Comment by metachronism** [comment]
.Net 4.6.2 sometimes will fix this for you, but otherwise it is fixed in 5.4

**Comment by darkdino** [comment]
At the end of the day updating to 2012R2 saved me
