### ISSUE TITLE
Mining tutorial mentions stone

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10552]
![image](https://user-images.githubusercontent.com/431728/50801677-8f4ca180-1331-11e9-88eb-d208256c0ce1.png)

**Comment by D3nnis3n** [comment]
Related to this? https://github.com/StrangeLoopGames/EcoIssues/issues/10362 Or this it already work but mentions the wrong thing?

**Comment by seccombew** [comment]
@craig-jong assign to @Quadbro if appropriate.
