### ISSUE TITLE
Pipe collider mesh has a lot of tris

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10555]
![image](https://user-images.githubusercontent.com/431728/50802510-5f51ce00-1332-11e9-9566-418da73ccc60.png)
This source collider mesh has more than 65k verts

This is causing meshes to generate with more than 65k verts pushing them to use 32bit indices.

**Comment by keegan-o** [comment]
Added meshes for all pipe colliders, in master.

![image](https://user-images.githubusercontent.com/14983165/51003923-6f61dd00-14ed-11e9-9ac7-31900c25cc88.png)
