### ISSUE TITLE
Master: Treasury issues

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10567]
1) no room requiment, work on "open space"
2) no allocate\tax(:P suggestion)\dump buttons
![default](https://user-images.githubusercontent.com/4980243/50826935-1c9def00-134e-11e9-808c-51a3f72fc862.png)

3) default currency field is not dunamic and not resizes in small window. (Also currencies menu ignore clicks outside and opens over all.)
![default](https://user-images.githubusercontent.com/4980243/50827636-16107700-1350-11e9-8bc9-fa60eecf9c93.png)
![default](https://user-images.githubusercontent.com/4980243/50827646-1dd01b80-1350-11e9-8495-bde8dad88dab.png)

4) incorrect removing plants while placing, wrong occupancy?
![default](https://user-images.githubusercontent.com/4980243/50826881-fbd59980-134d-11e9-92dd-651627a491c7.png)

5) strange position while placing
![default](https://user-images.githubusercontent.com/4980243/50826979-3b9c8100-134e-11e9-93ab-a09f03184481.png)

6) default currency field after pickup and place treasury is not available for edit.
![default](https://user-images.githubusercontent.com/4980243/50827691-3c361700-1350-11e9-83c4-49a3f583f17a.png)

**Comment by johnkslg** [comment]
Split this into multiple bugs and assigned them out:
https://github.com/StrangeLoopGames/EcoIssues/issues/10575
https://github.com/StrangeLoopGames/EcoIssues/issues/10574
https://github.com/StrangeLoopGames/EcoIssues/issues/10576
https://github.com/StrangeLoopGames/EcoIssues/issues/10577
Thank you!

**Comment by elfl0rd** [comment]
:D okay
