### ISSUE TITLE
Test recipes shown in game

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10561]
![image](https://user-images.githubusercontent.com/774628/50805039-78606d80-12a5-11e9-9036-0b556522c3f7.png)

Probably don't want that Crafted At listing for logs

**Comment by BlazeGuy2** [comment]
Different from https://github.com/StrangeLoopGames/EcoIssues/issues/10519, whose issues are caused when generating the benefits list.
