### ISSUE TITLE
Master: tools model displays under objects :D

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10569]
![default](https://user-images.githubusercontent.com/4980243/50830097-c3d35400-1357-11e9-8e99-709dcd0610ec.png)

**Comment by redwyre** [comment]
#10457

**Comment by elfl0rd** [comment]
No, pr merjed, bug still alive
![default](https://user-images.githubusercontent.com/4980243/51598496-b4830780-1f0e-11e9-85b8-8ce3b297aeae.png)

**Comment by redwyre** [comment]
Looks like the shaders aren't recompiling properly. You can fix it by reimporting the shaders under EcoModkit.
