### ISSUE TITLE
Disconnecting from server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10565]
Have a player unable to log into the servers he plays on and has not been able to get in since 7.8.6
He reports that people can see him  for a few minutes until he is disconnected but all he sees is the loading screen.  They report being able to drive through him so he obviously is not fully in the game.
He reports a ping of 60.
We have tried everything that we can possibly try without a server admin around to gather some information from.

This is his client output_log:

Initialize engine version: 2018.2.19f1 (06990f28ba00)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 Ti (ID=0x1b06)
    Vendor:   
    VRAM:     11127 MB
    Driver:   25.21.14.1735
Begin MonoManager ReloadAssembly
- Completed reload, in  0.336 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.269795 ms
Client version: 0.7.8.8 beta
Tuesday, January 1, 2019 1:43 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: TollItem
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Setting up 2 worker threads for Enlighten.
  Thread -> id: 16b4 -> priority: 1 
  Thread -> id: 2f08 -> priority: 1

**Comment by pamduncan** [comment]
Another new purchaser of the game, getting just a black windows when trying to enter a server:  

Initialize engine version: 2018.2.19f1 (06990f28ba00)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   
    VRAM:     8079 MB
    Driver:   25.21.14.1735
Begin MonoManager ReloadAssembly
- Completed reload, in  1.183 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.458900 ms
Client version: 0.7.8.8 beta
Tuesday, January 1, 2019 1:43 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: TollItem
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

NullReferenceException: Object reference not set to an instance of an object
  at GraphicsSettingVSync.Setup (GraphicSetting s) [0x00024] in <0ba4c88bccb94dc6bba533432da0bc5a>:0 
  at GraphicsSettingVSync.Start () [0x00021] in <0ba4c88bccb94dc6bba533432da0bc5a>:0 
 
(Filename: <0ba4c88bccb94dc6bba533432da0bc5a> Line: 0)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Can not play a disabled audio source
 
(Filename:  Line: 447)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Setting up 4 worker threads for Enlighten.
  Thread -> id: efc -> priority: 1 
  Thread -> id: 1388 -> priority: 1 
  Thread -> id: 19a4 -> priority: 1 
  Thread -> id: 3894 -> priority: 1

**Comment by pamduncan** [comment]
Update.  The work around I have for this now as even multiple attempts to get steam to run the game, is either have the roll back to 7.5 and run the server  then shut down and go back and opt out of beta and have it install 7.8.8.  About 3 out of 5 times that will nudge steam into installing correctly or installing all files.  

The second way is to just have then download the SLG client from SLG, unzip and drop it into a directory and run it from there and it works fine.

If you remember a few versions ago we had a similar problem that steam would not install all files and would not recognize the files not installed as missing bit they definitely were.  At that time it was only happening to people that had just bought the game and never played before and they either had a black screen or unable to connect even to their own single player game.  In that case multiple installs,  rolling back to older versions and the coming back did install all files or just going to the SLG copy.  We were in the process of trying to determine what was causing this but an update was done for other fixes and this issue stopped happening.  JohnK had said to let him know if this happened again and it seems to be the case, and only with people new to the game and installing Eco for the first time

**Comment by pamduncan** [comment]
**Another:**
<size=150%>Connexion échouée</size>

Connection timed out

Log File:
Initialize engine version: 2018.2.19f1 (06990f28ba00)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   
    VRAM:     4018 MB
    Driver:   25.21.14.1681
Begin MonoManager ReloadAssembly
- Completed reload, in  0.096 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.402233 ms
Client version: 0.7.8.8 beta
Tuesday, January 1, 2019 1:43 PM
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: TollItem
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by beastyn** [comment]
should be fixed. Users open new issues if needed
