### ISSUE TITLE
[Steam Master Build] - Microlags

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10566]
See this video: https://drive.google.com/open?id=1Z7kON-Kvt42yCgR0cpGk0zR9wQvJBk5H
Performance has improved quite a bit over the last builds, but microstuttering is still existing and still too frequent. (But better, so you did something that affects it.) Please note the FPS counter in the top left area to see that it's absolutely not a graphics card issue, though there are some 40 fps drops that i don't know why they happen. At least it never goes down to values that would cause problems.

Related to: https://github.com/StrangeLoopGames/EcoIssues/issues/10254 https://github.com/StrangeLoopGames/EcoIssues/issues/10136, probably also https://github.com/StrangeLoopGames/EcoIssues/issues/10462

Please do NOT close this for being too generic. It's a major issue making videos very hard and is one of the most-mentioned issues with Eco in social media, discord an on negative steam reviews.

You can also clearly see that chunks are loading way too slow and that the microlags probably have to do with chunkloading. (Even minecraft loads chunks faster ...)

System Specs:
Ryzen 2700
RTX 2080
32 GB DDR4-3000 RAM
NVME-SSD

Also, this is on Full HD with default graphics settings, Viewing Distance being 100, though. Higher and or lower viewing distance make no real difference, you'll still see those if you let load all of the surrounding area as soon as you move.

**Comment by johnkslg** [comment]
Garbage collection related?

**Comment by johnkslg** [comment]
Adding Alex to this one, if you guys can sync up for tackling this and other perf issues

**Comment by metachronism** [comment]
can leave this bug if you want, its never going to be ideal or "solved" fully.  it will always come back

**Comment by D3nnis3n** [comment]
That's sad. It seems to have improved a bit further now. I'll add it to my list as this is something that should be done regularily. We at least need to do our best to fix performance and lag issues.

**Comment by elfl0rd** [comment]
still freeze every ~30s :(

**Comment by D3nnis3n** [comment]
Seems a bit better for me now, but nowhere near good. "Ideal" or "solved" is far away.

**Comment by D3nnis3n** [comment]
@mirasrael Probably you got an idea?

**Comment by mirasrael** [comment]
@D3nnis3n can we reduce priority and move to 8.1?

**Comment by mirasrael** [comment]
@D3nnis3n are you still able to see such behavior on staging build?

**Comment by mirasrael** [comment]
Added @metachronism because seems related to his chunks rendering optimization work

**Comment by mirasrael** [comment]
FPS was greatly improved in 8.2. Re-open issue if issues will persist after 8.2 release.
