### ISSUE TITLE
Master: wooden shovel - incorrect name in tooltip

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10568]
![default](https://user-images.githubusercontent.com/4980243/50829909-1a8c5e00-1357-11e9-82e4-4dd5dc7e51ad.png)

**Comment by redwyre** [comment]
Shows up load this in chat too
![image](https://user-images.githubusercontent.com/431728/50871537-875f3100-1407-11e9-9fe7-5a32156d5dc1.png)

**Comment by Spydarlee** [comment]
Fixed in master.
