### ISSUE TITLE
USER ISSUE: Failed to connect - connection timed out.

### ISSUE THREAD

**Issue by Gr1nevsky** [StrangeLoopGames/EcoIssues#10572]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by wakka45** [comment]
I have Same probleme 0.7.8.8 beta server 


If you put ip: port on the address directly (on "your world") but after rebooting, the game does not work and you have to do the manipulation again.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11548
