### ISSUE TITLE
Master: room requirement broken on multiple tables.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10571]
e.g. butchery, wainwright, tailor...
![unknown](https://user-images.githubusercontent.com/4980243/50842116-2425be00-1377-11e9-8c90-75db669d8bde.png)

**Comment by elfl0rd** [comment]
It looks as something broken in this room, in new room tables work.
But needs investigate.

This is a save
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2737608/Storage.zip)

**Comment by elfl0rd** [comment]
Happens due to claimed land, requesting critical priority (deadlock in multiplayer)
w\o claim
![default](https://user-images.githubusercontent.com/4980243/50883661-c6868580-13f9-11e9-8c71-a1c0d3e77ae6.png)

with claim
![default](https://user-images.githubusercontent.com/4980243/50883691-daca8280-13f9-11e9-9d29-2e3b9aa373f6.png)

you can bupass if you place workbench, then claim but it's ugly!

**Comment by redwyre** [comment]
What does the room info say?

**Comment by elfl0rd** [comment]
![ss](https://user-images.githubusercontent.com/4980243/50883944-9a1f3900-13fa-11e9-838a-c785c7bde5d6.png)
no room changes, only unclaim and pickup\place table
![ss](https://user-images.githubusercontent.com/4980243/50883999-be7b1580-13fa-11e9-9223-a1ef19f8b05d.png)

**Comment by elfl0rd** [comment]
Video - https://youtu.be/uePx0pSa5cA (uploading now)
