### ISSUE TITLE
Treasury occupancy wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10576]
1) incorrect removing plants while placing, wrong occupancy?
![default](https://user-images.githubusercontent.com/4980243/50826881-fbd59980-134d-11e9-92dd-651627a491c7.png)

2) strange position while placing
![default](https://user-images.githubusercontent.com/4980243/50826979-3b9c8100-134e-11e9-93ab-a09f03184481.png)

**Comment by elfl0rd** [comment]
Occupancy is really uncorrect, just look.
![default](https://user-images.githubusercontent.com/4980243/51590811-49303a00-1efc-11e9-8072-e7a1013fad76.png)

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/51866841-143c4100-235b-11e9-84a0-702d0e5e0447.png)

**Comment by D3nnis3n** [comment]
![weird](https://user-images.githubusercontent.com/25908592/53250439-afa2a680-36ba-11e9-8d0c-41137da7216e.png)

**Comment by elfl0rd** [comment]
yea, same for bank.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/55193866-66d08880-5165-11e9-85af-777c980889b9.png)
Cannot repo on master or staging, someone must have fixed it-- I updated the occupancy on the prefabs and it made no changes to autogen, thus... someone updated it already.
