### ISSUE TITLE
Tree exploded when chopped down due to nearby trees

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10578]
When chopped down, it was colliding with the neighboring tree's foliage so it freaked out.
![image](https://user-images.githubusercontent.com/3536496/50869041-46174480-1367-11e9-8214-8f44c10db7d4.png)

A few ways we could address this:
- Make tree trunks not collide with branches
- Make tree trunks destroy any branches they collide with

**Comment by redwyre** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10277

**Comment by D3nnis3n** [comment]
I prefer the destroy option

> When chopped down, it was colliding with the neighboring tree's foliage so it freaked out.
> ![image](https://user-images.githubusercontent.com/3536496/50869041-46174480-1367-11e9-8214-8f44c10db7d4.png)
> 
> A few ways we could address this:
> 
> * Make tree trunks not collide with branches
> * Make tree trunks destroy any branches they collide with
