### ISSUE TITLE
Meteor is behind the moon

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10579]
![image](https://user-images.githubusercontent.com/3536496/50869106-88408600-1367-11e9-953f-87b3e723081a.png)
That would make it too big

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/41d08b84-256a-49a5-b906-d3101b3a9061)

Has been fixed for a while
