### ISSUE TITLE
Feature: soil sampler using directly on plant

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10570]
In some cases, ground is hard to reach... e.g. under oak.
Using soils sampler directly on plant is a better solution.

**Comment by D3nnis3n** [comment]
But the thing samples soil, not plants ;P

**Comment by elfl0rd** [comment]
yes, but as i descripted - is too hard reaching soil under large plants, like oak.

**Comment by eliotcougar** [comment]
Especially with Cekobia and Redwood, the tile they're growing on is completely unreachable, entirely covered by tree geometry, so there is no way to use a soil sampler to check the maturity level...
