### ISSUE TITLE
At max hewing skill, I can make 1000 hewn logs out of 1 log

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10580]
![image](https://user-images.githubusercontent.com/3536496/50869218-ea998680-1367-11e9-82ae-dfbf88479964.png)

**Comment by johnkslg** [comment]
But then trying that failed: 
![image](https://user-images.githubusercontent.com/3536496/50869268-19176180-1368-11e9-88dd-7f45507d9e16.png)

**Comment by craig-jong** [comment]
fixed
