### ISSUE TITLE
Repair station showing markup

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10586]
![image](https://user-images.githubusercontent.com/431728/50871334-fa1bdc80-1406-11e9-8c1d-396bcb44a191.png)

**Comment by Spydarlee** [comment]
We weren't passing tags in the required skills string.

![image](https://user-images.githubusercontent.com/553695/51258348-ac244d00-19a1-11e9-9136-5c6c51a1cc07.png)
