### ISSUE TITLE
Player position desync

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10585]
I was chopping a tree in the woods and got the disappearing tree bug then did a bunch of other things for 10 min... when I disconnected/reconnected I was back where I was standing when the tree disappeared.

During that time Craig couldn't see me when I was standing next to him, I didn't receive new chunks and I couldn't drive carts so it looks like my position server side was stuck. I was able to place objects and interact with the world though

**Comment by SeanAtr0n** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2739088/output_log.txt)

**Comment by elfl0rd** [comment]
> During that time Craig couldn't see me when I was standing next to him

https://github.com/StrangeLoopGames/EcoIssues/issues/10952#event-2110365946
