### ISSUE TITLE
0.5.3 [Plant, Simulation!!!] My world is on day 170 (day 4 in real life), and there are only 26 beans in the world

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1058]
I have not been gathering beans at all, there have simply never been many beans in this world and I don't know why. Check it out on the webpage of my server akicraft.net:3001 and see for yourself. Do you have an explanation, or is this a serious issue with the simulation?

**Comment by AkibaNiashomi** [comment]
Whew, creds for being quick on assigning this! :)

**Comment by iflounder** [comment]
Ive noticed that most worlds have this issue since beans grow only high on rivers.Which also happens to be where fiddle head and berries grow. Making a lot of competition for very little land space. I think this will be fixed as part of the farming update.

**Comment by metachronism** [comment]
tweaked lots in 5.5, should not longer be relevant
