### ISSUE TITLE
Remove Commongrass from plant population graphs

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#1059]
This is probably a good idea because its population dwarfs all others and it makes the graphs for everything itty-bitty.

**Comment by MarjieAVolk** [comment]
Were you picturing removing it just on the server web page?  Or elsewhere as well?

**Comment by craig-jong** [comment]
Just the server web page, I think.

**Comment by rainfarmer** [comment]
This needs to be updated in the /frontpage query

And also in the /graphs query if you want to remove camas from the premade graph for populations
