### ISSUE TITLE
Master: yellow? particles after pickup dirt

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10595]
It looks as waste, lol.
![default](https://user-images.githubusercontent.com/4980243/50902463-01091600-142c-11e9-971f-c72c577a2e34.png)

e.g. it happens after pickup "RockySoilBlock"

**Comment by D3nnis3n** [comment]
@keegan-o Intended? Does indeed look a bit ... ugly. Sorry :(

**Comment by keegan-o** [comment]
lol, it was set to the sewage one somehow. Fixed in master.
