### ISSUE TITLE
Need more GUI clamp fixes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10597]
Popup windows shouldnt show up off-screen
![image](https://user-images.githubusercontent.com/3536496/50922015-4282cc80-13fe-11e9-9f7c-98badf252f91.png)

I should be able to drag a window farther off screen if I like, just has to give me a smidge of a handle (20-50 pixels probably)
![image](https://user-images.githubusercontent.com/3536496/50922079-67773f80-13fe-11e9-8bbd-6a7981396309.png)

**Comment by elfl0rd** [comment]
In addition... If possible :P https://github.com/StrangeLoopGames/EcoSuggestions/issues/620

**Comment by Spydarlee** [comment]
I've changed the default ClampGui behahviour to allow 0% of a UI element to be off screen, and only enabled the new behaviour (with increased leniency of 95% allowed off-screen) when called by Draggable elements specifically.

![image](https://user-images.githubusercontent.com/553695/50980144-ea2bf780-14ef-11e9-846a-779ad463959d.png)
