### ISSUE TITLE
Master: wood debris (cedar) art with seeds missed?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10590]
![default](https://user-images.githubusercontent.com/4980243/50887965-904f0300-1405-11e9-82a1-3dd3bad88937.png)

**Comment by keegan-o** [comment]
This is because Cedar trees are getting a revamp soon as part of the biomes patch. These debris still give the right items so it's not a big deal, and we don't want to do the debris till we know for sure what the tree will look like.

**Comment by elfl0rd** [comment]
can be removed from 0.8?

**Comment by seccombew** [comment]
fixed in master
