### ISSUE TITLE
Master: in some cases full mature Taro is unawailable to pickup

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10593]
![default](https://user-images.githubusercontent.com/4980243/50901459-49730480-1429-11e9-9cc4-3493e686ad38.png)
![default](https://user-images.githubusercontent.com/4980243/50901469-51cb3f80-1429-11e9-9e87-65506adebdae.png)

**Comment by BlazeGuy2** [comment]
I could harvest all of the taro I came by.
