### ISSUE TITLE
Master: nickname (reputation) colors are broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10603]
![default](https://user-images.githubusercontent.com/4980243/50953149-91466a00-14c3-11e9-9ef1-965237e74b4b.png)

**Comment by D3nnis3n** [comment]
Thats the new intended behaviour: https://github.com/StrangeLoopGames/Eco/pull/3802/commits/81a99d668e6e5db247f700b72ce5296cda276ecc

**Comment by elfl0rd** [comment]
new behavior is non logic
![default](https://user-images.githubusercontent.com/4980243/50955289-c35aca80-14c9-11e9-91f9-df7eed5fcffd.png)

**Comment by elfl0rd** [comment]
yes, i agree new default color, but mixing low negative and high positive reputations is really bad.
