### ISSUE TITLE
Got stuck on "Loading world 88%"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10606]
Game isn't loading enough chunks to pass initial load count.

![image](https://user-images.githubusercontent.com/431728/50979209-bb3e7180-1541-11e9-95b3-eb30a85fa53d.png)

It's stuck on loading 44 chunks out of the initial 50 required

**Comment by redwyre** [comment]
![image](https://user-images.githubusercontent.com/431728/50980495-913a7e80-1544-11e9-90a0-e6aa033383a7.png)

lastSentViewPosition: "(348.3, 60.5, 1.2)"
currentViewRange: "(24, 0, -9)-(45, 8, 11)"

Here you can see the 44 chunks... is this just NumChunksForInitialLoad being too big @metachronism ?
Note this is a very flat and solid map so only one plane of chunks is getting rendered.

**Comment by metachronism** [comment]
if you have a really tiny world there isnt enough chunks.  dont use a tiny world?  or increase view distance

**Comment by redwyre** [comment]
It's a 1km by 1km world, there's plenty of chunks to load.
I suspect normally there are hills to include more vertical chunks, but it's not impossible for a user to flatten out an area and get this.
Ideally this would be solved by getting a list of all the chunks in the view cylinder and waiting for those to load.

**Comment by D3nnis3n** [comment]
@redwyre Is that issue still persisting? I see there is a mention in a pull request, but i can't find it on the pull request.

**Comment by redwyre** [comment]
I think this got fixed, let me generate a flat world and try again

**Comment by redwyre** [comment]
No longer an issue
