### ISSUE TITLE
Master: userUI corrupted

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10602]
![default](https://user-images.githubusercontent.com/4980243/50953092-68be7000-14c3-11e9-81ba-adebbdcdaf66.png)
![default](https://user-images.githubusercontent.com/4980243/51009500-6d396600-1561-11e9-8cdf-a5c3077c643a.png)

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/51174879-745ace00-18eb-11e9-960e-8ae587310490.png)

**Comment by johnkslg** [comment]
Fixed

**Comment by elfl0rd** [comment]
before tutorials completed
![default](https://user-images.githubusercontent.com/4980243/51516872-ea9a8b80-1e29-11e9-96a5-2d0fda7adac0.png)

**Comment by johnkslg** [comment]
Fixed
