### ISSUE TITLE
Master: elevator need model and\or description update

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10604]
After changes - https://github.com/StrangeLoopGames/EcoIssues/issues/9619

> Now the elevator's 'doorway' for sealing rooms is below the elevator and you must have an empty space there when placing it.

I think lowering elevator cabin by 1 block on placement preview, would be fine.

Otherwise it's really confusing
![default](https://user-images.githubusercontent.com/4980243/50954555-c785e880-14c7-11e9-83b3-0da3e969cf69.png)

**Comment by SeanAtr0n** [comment]
> I think lowering elevator cabin by 1 block on placement preview, would be fine.

good idea, will do
