### ISSUE TITLE
USER ISSUE: No pie chart for food and cant access skills menu

### ISSUE THREAD

**Issue by matwolf09** [StrangeLoopGames/EcoIssues#10601]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
Multiple worlds, will not show food pie chart and will not let me access skills menu

**Expected behavior:**

**Actual behavior:**
no food pie chart and cannot access skills menu

**Do you have mods installed? Does issue happen when no mods are installed?:**
no food pie chart and cannot access skills menu

**Comment by D3nnis3n** [comment]
Does elfl0rds suggestion work?

**Comment by pamduncan** [comment]
Most times this happens with people who have played before and expect it to be there and do not know it does not show until the food/skill part of the tutorial is done or the tutorial is completely skipped

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
