### ISSUE TITLE
Localization: missed space?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10607]
In strings
https://crowdin.com/translate/eco-by-strange-loop-games/40/en-ru#67942

> Profession Experience/Day:{0}\n

https://crowdin.com/translate/eco-by-strange-loop-games/40/en-ru#67944

> Specialty Experience Multiplier:{0}

https://crowdin.com/translate/eco-by-strange-loop-games/40/en-ru#67940

> Base Multiplier:{0}

**Comment by elfl0rd** [comment]
Space need for more "clear" at crowdin :)

**Comment by Spydarlee** [comment]
Ah okay, no problem! I'll do this in my next round of loc fixes once Mike's finished merging the Crowdin files, etc. :)

**Comment by elfl0rd** [comment]
(i remove from 0.8 milestone and change priority to low in this case)
