### ISSUE TITLE
Hammer shift + scroll to change block type doesn't work. (MacOS)

### ISSUE THREAD

**Issue by Merhex** [StrangeLoopGames/EcoIssues#10600]
Just bought the game.

I am playing on an iMac using a Steelseries Rival 300 mouse on the iMac, I am at the stage when I use the hewn logs, to start building a house at the very beginning.

The game sees that I am using the shift button. I am scrolling but it doesn't change the block.

I tried on a Windows pc and this worked. My girlfriend and I can't play together because of this.

**Comment by Merhex** [comment]
If I use the Magic Mouse that comes with apple, it does work.

**Comment by SlayksWood** [comment]
Still an issue 8.1.3

**Comment by SeanAtr0n** [comment]
does the map or toolbar respond to your scroll wheel on your steelseries mouse?

**Comment by Merhex** [comment]
Cannot remember. I refunded the game shortly after. Good luck

Op do 25 apr. 2019 19:07 schreef Sean Ater <notifications@github.com>:

**Comment by SeanAtr0n** [comment]
Looks like osx can have issues w/ some mice so I suspect it was an osx issue with this particular mouse.

I'll close this for now and see if anyone else reports it.

**Comment by SlayksWood** [comment]
You press shift and the drop-down list of blocks does not appear. You can build only one block.
![image](https://user-images.githubusercontent.com/45708377/56756438-7231c680-679a-11e9-861e-4144111bbea4.png)

**Comment by SeanAtr0n** [comment]
so you are on a mac?

the list doesn't appear until you scroll

**Comment by SeanAtr0n** [comment]
if it doesn't appear when you scroll then does the map or toolbar respond to your scroll wheel?

**Comment by SlayksWood** [comment]
I have the opportunity to check bugs on Mac. But at the moment I can't. I will write tomorrow.

**Comment by SlayksWood** [comment]
The map, toolbar, rope of crane respond to my scroll wheel. 
But when you take hammer(or use crane) and press Shift(it display pressed) then try to use Scroll Wheel. It hasn't any effect. The list doesn't appear.

**Comment by SeanAtr0n** [comment]
hmm... found this "Scroll Horizontally with a Mouse Wheel by Holding Shift in Mac OS X."

guess a temporary solution is to use a different key binding in the controls setting:
![image](https://user-images.githubusercontent.com/774628/56827697-671b7c80-6814-11e9-9b65-f92c4f7492f1.png)
