### ISSUE TITLE
Master / 7.8.8: "link" broken in /listunobtainable and in other places (Not for all items) 

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10616]
![default](https://user-images.githubusercontent.com/4980243/51010044-90651500-1563-11e9-8e64-b7e4639b2270.png)

**Comment by D3nnis3n** [comment]
Does this only happen there?

**Comment by elfl0rd** [comment]
yep

**Comment by D3nnis3n** [comment]
Nope. And it does happen in 7.8.8.

**Comment by D3nnis3n** [comment]
Hope you're fine with the edited title, feel free to make it more clear.

**Comment by elfl0rd** [comment]
hmm... maybe something broken in https://github.com/StrangeLoopGames/EcoIssues/issues/10636 ...

**Comment by elfl0rd** [comment]
> GetLinkTooltip(String linkId)

maybe has same root problem
https://github.com/StrangeLoopGames/EcoIssues/issues/10641
