### ISSUE TITLE
USER ISSUE: Invisible Terrain

### ISSUE THREAD

**Issue by derpyParticle113** [StrangeLoopGames/EcoIssues#10626]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
move large amounts of dirt into bin

**Expected behavior:**
only effect the block taken

**Actual behavior:**
reflected another part of the terrain and made some of the sides invisible

**Do you have mods installed? Does issue happen when no mods are installed?:**
reflected another part of the terrain and made some of the sides invisible

**Comment by elfl0rd** [comment]
> Bin

you cannot throw blocks to bin on unmodified client. Or maybe you used admin commands before? And screenshots please.

**Comment by BlazeGuy2** [comment]
@derpyParticle113 Please post screenshots

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
