### ISSUE TITLE
Feature: button to open profile folder

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10628]
Files from this folder regularry needs for support, playtime.eco need for first server configuration...
And finding this folder is not easy.

`%appdata%\..\LocalLow\Strange Loop Games\Eco`

**Comment by D3nnis3n** [comment]
Very good idea!

**Comment by elfl0rd** [comment]
woops, miss my old one, heh
https://github.com/StrangeLoopGames/EcoIssues/issues/10307
