### ISSUE TITLE
Moved a stack of Sandstone from a small stockpile to a big one, disappeared

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10625]
I moved a 12 stack of sandstone from the small stockpile to the first linked one, it disappeared. Then I dragged in the 4 I was carrying to see if it would update the number to include the 12 but it didn't.

![image](https://user-images.githubusercontent.com/431728/51012505-2a02e580-15a9-11e9-8dce-7b82bd771499.png)

**Comment by redwyre** [comment]
I just realised there's an 18 stack in there, could it have merged into that?

**Comment by elfl0rd** [comment]
yep, merging blocks if free space not available is requested and intended behavior.
@Quadbro :P

**Comment by redwyre** [comment]
There was free space though, where the 4 block of sandstone is

**Comment by redwyre** [comment]
Going to close this as I've never experienced it again, was probably just that I didn't see where it went
