### ISSUE TITLE
Feature: automated test to check occupancy removing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10624]
due to lot of object is not removes occupancy after pickup.

**Comment by elfl0rd** [comment]
(i found lot of objects with this issue, and i think it's really need.)
https://github.com/StrangeLoopGames/EcoIssues/issues/10622
https://github.com/StrangeLoopGames/EcoIssues/issues/10623
https://github.com/StrangeLoopGames/EcoIssues/issues/10608
https://github.com/StrangeLoopGames/EcoIssues/issues/10619
https://github.com/StrangeLoopGames/EcoIssues/issues/10327

**Comment by SeanAtr0n** [comment]
the root cause is the same for all, going to fix that instead of adding tests

**Comment by elfl0rd** [comment]
I think test need for future, but ofc, in this case it's low prior.
