### ISSUE TITLE
0.5.3 [Items, Logic] Items in the carry slot while maneuvering a wooden cart

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1062]
This seems like a pretty bold feat! I mean, pulling a 1500 kg heavy cart up a hill is a feat by itself, but carrying 300 kgs of wood at the same time..! I'm impressed :)

**Comment by AkibaNiashomi** [comment]
Please pass me a note if you think I'm opening way too many issues for trivial things!

**Comment by iflounder** [comment]
Ive been using this as a makeup for the poor cart behaviors lol

**Comment by MarjieAVolk** [comment]
Gonna call this working as intended
