### ISSUE TITLE
[7.8.8] Doubled Links to Items

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10636]
Don't know why this is, but it's super enerving. It adds the link in brackets automatically.

<img width="596" alt="report2" src="https://user-images.githubusercontent.com/25908592/51071795-262d9c80-1657-11e9-934c-3713ea554dfb.png">

**Comment by elfl0rd** [comment]
intended :D 
first - wheat item
second - wheat population

**Comment by D3nnis3n** [comment]
What happens when someone also has a Deed named Wheat? Wheat (Wheat) [Wheat]

@Quadbro That's enerving as hell, lol!

**Comment by elfl0rd** [comment]
it's better then you want to show deed and you link one another with same name

**Comment by elfl0rd** [comment]
Read pr, i linked it above.
This behavior can easilly disabled, but after - another users gor problem with linking, again.

**Comment by D3nnis3n** [comment]
I read the PR, but the solution at the moment is bad. Noone on my server likes it, i do neither. It's enerving and especially confusing to have two links, especially when they look the same.
