### ISSUE TITLE
If you close window using esc - you get two active cursor

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10639]
(mouse and interaction)
Video - https://youtu.be/r09KA__MuJQ (uploading now)

**Comment by D3nnis3n** [comment]
Any screenshot?

**Comment by elfl0rd** [comment]
my video record software broken, i attach video later.

**Comment by elfl0rd** [comment]
done

**Comment by D3nnis3n** [comment]
Ah, you mean both tab and non-tab behaviour are active at the same time.

**Comment by elfl0rd** [comment]
yep, it's terribe for me)

**Comment by johnkslg** [comment]
@BlazeGuy2 can you pass this to @BlazeGuy2 if it still repros

**Comment by Quadbro** [comment]
This thing is Unity Editor only, and it's unity related. I'll close it for now, because wasted too much time for it
