### ISSUE TITLE
Master: /skillpoints need rework

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10638]
In currents state /skillpoints add skillpoints rate, instead of points.
And you cannot remove unwanted points after bugs or something.

e,g, after - https://github.com/StrangeLoopGames/EcoIssues/issues/10364

![default](https://user-images.githubusercontent.com/4980243/51071577-53cd1280-1664-11e9-8fda-70c01f087f23.png)

**Comment by craig-jong** [comment]
Skillpoints were removed and the /skillpoints now gives EXP. I can rename it, but I checked and its functional now so I'm going to close this issue.
