### ISSUE TITLE
Pickup Bed while someone sleeping cause problems to sleeping user

### ISSUE THREAD

**Issue by Crawless** [StrangeLoopGames/EcoIssues#10637]
(0.7.8.8) On third-party server i lay down on the wooden fabric bed, then my friend take down this bed and now i cant join this server coz client crushes while login. Looks like it is treated by restart server but i have no access to server

**Comment by elfl0rd** [comment]
In master crash not happens, but send user into black nether. Restart fixed it.
![unknown](https://user-images.githubusercontent.com/4980243/51103623-86a61080-17f4-11e9-8de3-87cb8dd1cdb9.png)
I think it is necessary to force all players to detach when picking-up.

In addition, root problem is same with - https://github.com/StrangeLoopGames/EcoIssues/issues/8484

**Comment by johnkslg** [comment]
Thats just rude, theyre trying to sleep.

**Comment by SlayksWood** [comment]
still an issue 0.8.1.3
![image](https://user-images.githubusercontent.com/45708377/56356925-d379f880-61e2-11e9-8ff2-82334c90aa6a.png)

**Comment by johnkslg** [comment]
Wake up user when this happens.

**Comment by IcedForge** [comment]
Still an issue

**Comment by SlayksWood** [comment]
original issue was fixed, fix for exceptions here #18511
