### ISSUE TITLE
Can't find my server

### ISSUE THREAD

**Issue by FacelessGhost** [StrangeLoopGames/EcoIssues#10632]
Hi. I created my server, connected but even I can't see my server in "Browse all". Sometimes some players connect to my server, they say that find server when click on "New Game". I checked and didn't my server. What is it? How I can delete this problem, because online very lower than another servers for beginners?
P.S if i refresh list of servers 30-50 times I can see my server once. And if refresh again server disappear.

Server:[24/7] LOST PLANET {EU and RU} (4,67 km of World Size / Skillpoints for crafting / Friendly community) 
IP: 83.239.231.184:3000
![image](https://user-images.githubusercontent.com/46619622/51312552-9889ec80-1a5c-11e9-90ec-821fb774a4b2.png)
![image](https://user-images.githubusercontent.com/46619622/51312580-aa6b8f80-1a5c-11e9-8b11-bc10903d6b70.png)
![image](https://user-images.githubusercontent.com/46619622/51312587-afc8da00-1a5c-11e9-9829-b972d761da90.png)

**Comment by beastyn** [comment]
Should work fine in 0.8.1  if server is not private
Please reopen if issue is actual
