### ISSUE TITLE
USER ISSUE: Memory leak on good system

### ISSUE THREAD

**Issue by zeonyphus** [StrangeLoopGames/EcoIssues#10646]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
Let the game run for over 4 hours w/ i5 8400, 16gb ddr4, z370 chipset,  gtx 1060 6gb, installed on HDD

**Expected behavior:**
Not leak

**Actual behavior:**
Mem leak

**Do you have mods installed? Does issue happen when no mods are installed?:**
Mem leak

**Comment by D3nnis3n** [comment]
Any more information to this issue? Which circumstances? Screenshots of process list and RAM usage? World file?

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
