### ISSUE TITLE
Consider compost blocks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10645]
the "fertilizer blocks" that are created when you filter dirty water to clean water. Did i hear that right, that there will not be a purpose for them yet in 8.0? Cuz if that is indeed the case, then i think they should not be in 8.0 yet. Cuz if you cant use the "fertilizer blocks" then they will only stack, and stack, and be in the way really quick.

**Comment by johnkslg** [comment]
Can make these be fertilizer

**Comment by craig-jong** [comment]
compost can be turned into pretty decent fertilizer. Will need another pass at fertilizer in general, but not for 8.0
