### ISSUE TITLE
Master: mortared granite - floor form collision broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10640]
![default](https://user-images.githubusercontent.com/4980243/51074328-fef2c180-168e-11e9-9cdf-d38b6cbe182c.png)
![default](https://user-images.githubusercontent.com/4980243/51074331-074afc80-168f-11e9-8400-a8105bb4e124.png)

**Comment by redwyre** [comment]
No collision generated for this block:
![image](https://user-images.githubusercontent.com/431728/51134461-61acae80-1883-11e9-9147-fe1e92414c93.png)

**Comment by redwyre** [comment]
Fixed with svn update
