### ISSUE TITLE
Client Memory bloat

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1064]
5.4 has a huge memory leak again and keeps on growing over time

**Comment by metachronism** [comment]
debugging this is a huge PITA

**Comment by MarjieAVolk** [comment]
Forum discussions about this issue:
http://ecoforum.strangeloopgames.com/topic/1119/memory-leak-logging-into-server/2
http://ecoforum.strangeloopgames.com/topic/1159/alpha-5-performance-absolutely-worse

**Comment by metachronism** [comment]
closing as dupe of #392 #1026 #653
