### ISSUE TITLE
Master: tree saplings is not appears in pot

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10642]
As i think, decorative "saplings" will be good.
![default](https://user-images.githubusercontent.com/4980243/51077882-78090d80-16bd-11e9-8d6d-260f3c7dbab7.png)

**Comment by D3nnis3n** [comment]
Wasn't it meant to show the tree when you put in a sapling?

**Comment by D3nnis3n** [comment]
Probably only works when you only put one seed in? Did you try?

**Comment by elfl0rd** [comment]
> Wasn't it meant to show the tree when you put in a sapling?

Like this, not a big tree.
![20190113132430_1](https://user-images.githubusercontent.com/4980243/51084184-aa0a8600-1736-11e9-850c-ffde6a3cbded.jpg)
![20190112222251_1](https://user-images.githubusercontent.com/4980243/51084185-aa0a8600-1736-11e9-8e6c-ef0555be4fc7.jpg)

> Probably only works when you only put one seed in? Did you try?

nope
![default](https://user-images.githubusercontent.com/4980243/51084258-a1ff1600-1737-11e9-9b96-883752227c4d.png)
In addition in works with regular plants.
![default](https://user-images.githubusercontent.com/4980243/51084267-c0651180-1737-11e9-8f10-162b6cfbcfa3.png)
