### ISSUE TITLE
Configuration Option for Admin Command Notices in Chat

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10659]
Add the following configuration options, maybe call it "LogAdministrativeActions" or whatever suits you:

0 = No Logging
1 = Logging to File
2 = Logging to File and Broadcasting to Admins in the Chat only
3 = Logging to File and Broadcasting to Everyone in the Chat

Opened on Request by JohnK

**Comment by elfl0rd** [comment]
refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10308

**Comment by johnkslg** [comment]
Some requested extensions for your admin command broadcasting

**Comment by WeaselDog** [comment]
fixed
