### ISSUE TITLE
Painfully slow website

### ISSUE THREAD

**Issue by AndyClausen** [StrangeLoopGames/EcoIssues#10656]
I know there are other issues regarding the website open, but I'd like to start one where we can figure out how to optimize the website a bit.
I don't know how it's made, I think I saw something that looked like Angular in some files a while ago though.
So, first off, if you are using AngularJS (rather than 2+), could you look into upgrading the version? They have a guide for doing that in their docs.
Secondly, I noticed that various calls are made a lot of times. Look at my network here:
![image](https://user-images.githubusercontent.com/16802212/51087117-34f77a80-174f-11e9-9d9c-7f3f595e0bec.png)
It seems like different versions of the js for bootstrap are being loaded? Why?
Another thing is that this is not a SPA. This means you are reloading the page every time you do an action. By making it an SPA, you could optimize it _a lot_.
Another thing is the standalone call to `/isadmin`... This should be handled in the backend. If it's because you need more functionality in the frontend if it returns true, you should rather use local storage or something to store this, along with the other user info you store. Again, this would be less of a problem in a SPA.

Hope this is useful, if you need a hand with implementation of any of this then I could spend a weekend or two helping with coding.

**Comment by rainfarmer** [comment]
this is over a year old. and elections has been refactored
