### ISSUE TITLE
Mill crashes server when placed 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1065]
http://ecoforum.strangeloopgames.com/topic/1502/server-mill-crashes-server-when-placed

**Comment by DMoate** [comment]
Seems to be related to type of room it is placed in. Crash was happening when placing in a room made of wood and dirt, worked fine when placed in a room made of wood and mortared stone. Rooms were roughly same size.

**Comment by metachronism** [comment]
fixed in 5.5

**Comment by MarjieAVolk** [comment]
Closing as a duplicate of StrangeLoopGames/EcoIssues#875 - Thanks for the observation about the type of room, that could be very helpful
