### ISSUE TITLE
[Master] Map behaves strange when opened underwater

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10662]
<img width="1566" alt="mawa" src="https://user-images.githubusercontent.com/25908592/51108583-f61b0080-17f2-11e9-86df-089a1dc85166.png">

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10613 maybe not merjed :D @metachronism ?

**Comment by D3nnis3n** [comment]
That's why fixed but not merged-in issues should not be closed, as i won't find them easily when searching then.

**Comment by redwyre** [comment]
This is fixed in master, but a new steam build hasn't been made since
