### ISSUE TITLE
Master: inventory out of window

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10660]
![default](https://user-images.githubusercontent.com/4980243/51102876-a7b93200-17f1-11e9-9894-2562aa89a009.png)

**Comment by Spydarlee** [comment]
Fixed and pull requested.

![ecostorageinventoryresizenscroll](https://user-images.githubusercontent.com/553695/51188057-13c09680-18d5-11e9-9a73-2ebd1c3388d3.gif)
