### ISSUE TITLE
Master: should a river have a natural Dam in it? It seems these rocks would have stopped flow to the waterfall lower down

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10667]
**Version:** 0.8.0.0 beta master-e591b4a8

Just created a random world and thought i would have a look at the new river to maybe have a house near/in/on/under it (i can never decide 😄 ) anyway on looking up the river i came to a water fall

![snap3804](https://user-images.githubusercontent.com/29383891/51136324-17e8a780-1834-11e9-8a81-8359d7540595.png)
then i noticed the Rock formation ahead, thinking this was a bridge with maybe water flowing underneath i had a closer look, view of said rock from above
![snap3797](https://user-images.githubusercontent.com/29383891/51136562-b37a1800-1834-11e9-847a-7f24f6fb8bdf.png)

![snap3803](https://user-images.githubusercontent.com/29383891/51136428-626a2400-1834-11e9-8a4f-338c057e405a.png)
But as you can see from the following snapshots its right across the river, cutting it off from the supposed water source further up
![snap3798](https://user-images.githubusercontent.com/29383891/51136655-f5a35980-1834-11e9-9397-e2472c9e2006.png)
![snap3799](https://user-images.githubusercontent.com/29383891/51136656-f63bf000-1834-11e9-9b82-a0944b0ff905.png)
![snap3800](https://user-images.githubusercontent.com/29383891/51136657-f63bf000-1834-11e9-917c-34fa95c29f28.png)
![snap3801](https://user-images.githubusercontent.com/29383891/51136658-f63bf000-1834-11e9-9885-e77582eafe95.png)
![snap3802](https://user-images.githubusercontent.com/29383891/51136659-f63bf000-1834-11e9-8eae-c6819e011514.png)
this isn't the **only** dam type on the river, some are hidden just below the surface
![snap3805](https://user-images.githubusercontent.com/29383891/51136959-a14ca980-1835-11e9-9244-779be5e423c7.png)
![snap3806](https://user-images.githubusercontent.com/29383891/51136960-a14ca980-1835-11e9-8411-c3bcff11641a.png)
Wouldn't the water Naturally have Stopped at these **Natural** barrier and maybe flowed around them?
Uploading the Map (before i muck about with it)
[River with Natural Dam.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2756825/River.with.Natural.Dam.zip)

It looks as if Rivers are made **first** then rocks are added afterwards, shouldn't this be the other way round?
The Rocks are Harder than the water and would have come first with the water either stopping at these rocks and finding another way round them through the softer dirt material, or Wearing them away as well?

**Comment by Conchipedia** [comment]
Reason for this if the water has hit a natural dam there is no way it could continue with out  either eroding the dirt  around the dam and continuing or eroding the dirt and making a lake, with possibly the option of it still finding a natural way down to the sea.
it does seem a bit unnatural, but it does look great ❤️

**Comment by metachronism** [comment]
by design - water table can go around rocks

**Comment by Conchipedia** [comment]
so the water table is not the same as the visible water that **looks** as if blocked?
