### ISSUE TITLE
Camera locks to character creation mode permanently if escape menu used during creation!

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#10666]
![image](https://user-images.githubusercontent.com/14983165/51137216-37131500-17f3-11e9-9c5d-bc2353e49f25.png)

Camera sticks like this, frontal view-- after creation menu is done, with the view locked and the spotlight still there! (not playable). Would be a bad bug for someone new to the game to run into right away.

**Comment by elfl0rd** [comment]
Cannot repro in master or steam build.

**Comment by Quadbro** [comment]
@keegan-o Can't open escape menu here... and can't reproduce it at all (@elfl0rd can't too) So could you please provide more info??

**Comment by keegan-o** [comment]
Hah, when I tried to do this again on my own I ran into the same thing, couldn't open the menu. Not sure how I got it open the time this happened, it's vaguely possible it was related to having the game open in Unity, but I wasn't trying to do anything with UIs at the time. Might just be rare.
