### ISSUE TITLE
Error in WorldObjects

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#10664]
So, this happened when i restarted the server, had to rollback 1 day.

Exception
Exception: Exception
Message:Error(s) occurred when loading WorldObjects
Source:Eco.Core

System.Exception: Error(s) occurred when loading WorldObjects
   at Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   at Eco.Gameplay.Objects.WorldObjectManager..ctor()

--END DUMP--

You know the error, its about... you know...
[Storage Files](https://drive.google.com/open?id=1U3jlu0iF-hDMdRT3CL-o9NNyklO93M5l)

**Comment by SlayksWood** [comment]
Can't reproduce for latest versions. Have same troubles with Plants few month ago, but it was fixed. If it happens again, please reopen.
