### ISSUE TITLE
 Loads of Connection time outs

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10668]
**Version:** 0.8.0.0 beta master-e591b4a8

sort of general game play, trying to craft and make room, after a while in singleplayer getting 
![snap3807](https://user-images.githubusercontent.com/29383891/51141692-e4147e80-1841-11e9-9f4f-812e6908119d.png)
message after seeing red icon flashing and unable to select any tool on tool bar.

uploading Output log
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2757097/output_log.txt)

Loaded up Eco again after Backing up the previous output log, sat on Main screen pressed ESC to get up send Bug report window, closed Eco and finished off this report, noticed how **big** the output log gets so sending the **new** one as well
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2757111/output_log.txt)
just in case this is something else

**Comment by Conchipedia** [comment]
on latest version
![snap3808](https://user-images.githubusercontent.com/29383891/51186645-fdfda200-18d1-11e9-9403-9ac04d6a265a.png)
this world that i have built on fails to load showing this message
![snap3809](https://user-images.githubusercontent.com/29383891/51186670-0f46ae80-18d2-11e9-9fd8-84465ca6eb0b.png)
then i try to load it again and now get this message
![snap3810](https://user-images.githubusercontent.com/29383891/51186694-1ec5f780-18d2-11e9-9ee8-296514e359ea.png)
but if i quit eco and replace it with the **same** generated world that was created on previous version it will load with no problem at all.
[Failed World to Load.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2760024/Failed.World.to.Load.zip)
[Original Created world (Nothing done in at all).zip](https://github.com/StrangeLoopGames/EcoIssues/files/2760027/Original.Created.world.Nothing.done.in.at.all.zip)
This is just a Capture of me attempting to load the world in
https://www.dropbox.com/s/7xify64zyr0gofw/Eco%2015_01_2019%2014_21_10.mp4?dl=0

i am putting this here as it might have **ALL** been related to the same world.

**Comment by Conchipedia** [comment]
Now playing on this NEW world, got another timed out, this time i lost various items after reconnecting to it, i removed the Campsite to make way for a New building that i am attempting to build (i need the open space as am on a beach against a cliff) and now the Campsite has totally disappeared from the game, and the **only** way to remake this is with tailoring which will take ages to unlock, same as i lost 4 Charred tomato that i had crafted

**Comment by Conchipedia** [comment]
Now have been getting more and more Timeouts, and they were getting closer and closer in time, last one threw me back to Main menu 1 minute 22 seconds after getting into the world, the one previous to that was 4 minutes and 18 seconds till back in Main Menu, now world will **NOT LOAD** as getting a connection failed, i even bypassed steam and loaded Eco.exe from the installed Steam Directory (this asks me to give username and password, just like it does when you download a version from SLG website", i get all the loading information coming up then it sits with Connecting showing and Finally i get "Connection Failed"
Failed to connect - connection timed out.
Uploading output log and the World which now won't load
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2760966/output_log.txt)
[Failed World.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2760975/Failed.World.zip)

also included the Backups
https://www.dropbox.com/s/jd9w7vngf9zrssx/Backup.zip?dl=0

**Comment by Conchipedia** [comment]
**0.8.0.0 beta master-0d4ca997** 
Created a **NEW** world for Singleplayer, All i have been doing is following Tutorials and gathering Food, got as far as placing Campsite, got a couple of timeouts (one when i left game playing and went for a coffee) came back, placed Campsite, just about to drag the istone axe to toolbar for the next tutorial got another Timeout now world refuses to load., i think the world gets corrupted.
uploading Output_log.txt and World
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2772815/output_log.txt)
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2772817/Storage.zip)
now trying one of the Backup files to see if i can play them

**Comment by Conchipedia** [comment]
I Started trying a **NEW** method of playing Eco 8.0.0  this time I am running the server.exe found in the Eco_Data Directory and joining to it as LAN from a Steam launch of Eco, I'm still getting occasional connection timed out errors and also the **Server itself is closing down**, but so far i am not getting a corrupted world load, so it is **sort of  playable**.

So in conclusion i think that because Singleplayer is running the Server as an invisible background task that might be what  is causing the Timed out errors when the server closes as Eco Client Doesn't close it just go backs to Main menu with the Error Message.

**Comment by Conchipedia** [comment]
Now server refuses to load world and just closes.
Uploading **ALL** Dumps for today from 
"G:\STEAM\steamapps\common\Eco\Eco_Data\Server\Dump" Directory
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2773822/Dump.zip)
Hope something in here can explain what is happening

**Comment by mirasrael** [comment]
@Conchipedia wow, you find a lot of problems and made great investigation! Thanks you!

**Comment by Conchipedia** [comment]
I just enjoy playing the game 😄
