### ISSUE TITLE
Block collision: Brick stacks

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10665]
Stacks of 1 and 4 are fine, however stacks of 2 and 3 are offset.
![image](https://user-images.githubusercontent.com/431728/51133869-be0ece80-1881-11e9-853c-4cb1cec32629.png)

via https://github.com/StrangeLoopGames/EcoIssues/issues/10546

**Comment by redwyre** [comment]
via https://github.com/StrangeLoopGames/EcoIssues/issues/10546

**Comment by keegan-o** [comment]
Fixed in master.
