### ISSUE TITLE
Steam 0.8 build - web server failed to start

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10669]
```
[12:24:07] Failed to start webserver: Метод не найден: "Swashbuckle.Application.
SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.
EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.App
lication.SwaggerDocsConfig>)".
```

As result - all web-related things is unavailable.

(In sources - works fine, happens only on steam)

**Comment by D3nnis3n** [comment]
Can you add more information? I just tried the build, webserver starts without problem.

**Comment by elfl0rd** [comment]
I don't have any ideas from what it's happens.
Stable repro with clean installed steam build for me.

If you want some specific info - ask more concrete.

Win 7 x64. (Build from unity and visual studio work fine)

**Comment by elfl0rd** [comment]
For future - this happens from old "something" from IIS.
Don't know why this issue appears only now, i removed iis loooong time ago.

**Comment by elfl0rd** [comment]
@Rambo99 actual issue is #11128

**Comment by Rambo99** [comment]
[09:30:52.660] [1] [ Info] [Eco] Failed to start webserver (TargetInvocationException): Адресат вызова создал исключение.
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
   в Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
   в Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   в Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
   в Eco.Webserver.WebServer.Init(Int32 port)
Метод не найден: "Swashbuckle.Application.SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.Application.SwaggerDocsConfig>)".
   в Eco.Webserver.Web.Startup.ConfigureWebApi(IAppBuilder appBuilder)
   в Eco.Webserver.Web.Startup.Configuration(IAppBuilder appBuilder)
