### ISSUE TITLE
Run for office - Error: [object Object]

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10671]
![default](https://user-images.githubusercontent.com/4980243/51175293-f1c21680-18ca-11e9-8dc9-fde46f81c254.png)

(cannot violate citizen law)

As i think - same with https://github.com/StrangeLoopGames/EcoIssues/issues/10154 cases)

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/51272363-c6006880-197e-11e9-8139-8dd6d9d02c2e.png)
I ran for office and got this error msg on the 8.0.0 build.  What version did this occur in?

**Comment by elfl0rd** [comment]
In sources, master. I still have https://github.com/StrangeLoopGames/EcoIssues/issues/10669 without any ideas about fixing it.

**Comment by D3nnis3n** [comment]
Cannot reproduce, reopen if it still occurs on the current version.
