### ISSUE TITLE
[8.0.0 Steam Build] /leader broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10674]
![leader](https://user-images.githubusercontent.com/25908592/51175650-2fb73e80-18bb-11e9-86da-3f589d1da957.png)

**Comment by elfl0rd** [comment]
As i see demographics briken, not leader?

**Comment by D3nnis3n** [comment]
I could run for office and win after 24 hours with /fastforward, though. - Had no access to treasury then, though!?

**Comment by elfl0rd** [comment]
Treasury fixes in https://github.com/StrangeLoopGames/Eco/pull/3819 (buttons is a different issue)
and can you open web interface while you see ingame citizen law like this?
`if (0 < 0)`?

**Comment by D3nnis3n** [comment]
Yes, i can.

**Comment by Quadbro** [comment]
all seems to be okay with leader command, there are some problems with laws

**Comment by Quadbro** [comment]
merged with https://github.com/StrangeLoopGames/EcoIssues/issues/10690
