### ISSUE TITLE
[8.0.0 Steam Build] Cranes don't show control UIs / Can't eject from cranes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10676]
No controls at the bottom. Impossible to build walls or something with it.
![cranes](https://user-images.githubusercontent.com/25908592/51176408-2038f500-18bd-11e9-93ea-6f9762760bb3.png)

**Comment by D3nnis3n** [comment]
Also - can't get out of the crane when in it.

**Comment by johnkslg** [comment]
Can you help with this one if you have time
