### ISSUE TITLE
[8.0.0 Steam Build] Issue with button overlaying account balance

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10675]
![overlayissue](https://user-images.githubusercontent.com/25908592/51175778-83c22300-18bb-11e9-805d-1a2b175b61e4.png)

**Comment by elfl0rd** [comment]
And i think this "Make a Transfer" button need to be pinned to main window, not on scrollable layer.
+ maybe increase lower panel.

**Comment by johnkslg** [comment]
Should make the lower half bigger by default too.
