### ISSUE TITLE
Graphical issues with Granite(?) Ramp A(?)

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10681]
![image](https://user-images.githubusercontent.com/431728/51184753-f44f5b00-1920-11e9-8380-91484f91cb88.png)

![image](https://user-images.githubusercontent.com/431728/51184836-324c7f00-1921-11e9-9900-4bcd2f1c16b9.png)

![image](https://user-images.githubusercontent.com/431728/51184945-848da000-1921-11e9-8f4f-e615433c4e82.png)

![image](https://user-images.githubusercontent.com/431728/51184970-94a57f80-1921-11e9-941c-f4ac5caaa662.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/57164410-de1ebb00-6da8-11e9-8703-e3e4148a90f9.png)
![image](https://user-images.githubusercontent.com/14983165/57164554-54232200-6da9-11e9-9ba6-f53b02b72ea8.png)
Couldn't repro, I do remember tweaking these meshes a bit a while ago, whatever I did may have worked, might have been import settings as well. (Those faces certainly have never been missing in the FBXs)
