### ISSUE TITLE
Citizen accounts not displaying Continue button on menu

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10685]
If a citizen logs into eco for first time, there is no Continue button for them to login to their assigned server.

You can test a fresh eco install by deleting user data in \AppData\LocalLow\Strange Loop Games\Eco

**Comment by rainfarmer** [comment]
This isnt working again

**Comment by rainfarmer** [comment]
oh nevermind its working

**Comment by rainfarmer** [comment]
Not working for me on 8.0.5

**Comment by mirasrael** [comment]
Can't reproduce. Can you provide more details?
![image](https://user-images.githubusercontent.com/475445/54115721-1aafe500-43fe-11e9-80f6-4cedb53029ce.png)

**Comment by redwyre** [comment]
I had a player confirm it's working, the server was under Continue

**Comment by rainfarmer** [comment]
@mirasrael Did you delete the eco user data before loading the game, so its like first time use.

**Comment by mirasrael** [comment]
@rainfarmer yes, of course. You can provide me details about citizen account you're trying in Discord, so I can check on exact account and exact world.

**Comment by mirasrael** [comment]
@rainfarmer is this issue still actual? Had no response from you for awhile

**Comment by rainfarmer** [comment]
It is working now thank you!

One small detail, is it's displaying as a Continue option:
![image](https://user-images.githubusercontent.com/7343272/55052752-3da1e200-5017-11e9-8b05-4f36b0044c93.png)

But it is much nice when it looks like this:
![image](https://user-images.githubusercontent.com/7343272/55052761-485c7700-5017-11e9-85e7-cbf4366c1c9a.png)

That is how it looks for world owners

**Comment by rainfarmer** [comment]
Just tested again, and the Join World link shows up, but it doesnt connect to server, always returns connection error.
Direct connecting using serverID or continue works correctly.

**Comment by mirasrael** [comment]
Tested with test account @rainfarmer provided me in PM and it worked fine.
