### ISSUE TITLE
Levitating baby firs

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10705]
![image](https://user-images.githubusercontent.com/774628/51289907-ee0bbe00-19b6-11e9-8894-060ad3f2ed98.png)

**Comment by keegan-o** [comment]
@metachronism Please tone down the scaling and the height adjustments on trees-- Palms can have the most, others should have significantly less variation than them. (it's still a great thing to have some, though)
