### ISSUE TITLE
splitting rubble doesn't delete big rubble quickly enough

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10706]
![rubblesplitbug](https://user-images.githubusercontent.com/774628/51291028-98391500-19ba-11e9-9caa-8241050cc757.gif)
think this is new behavior

**Comment by elfl0rd** [comment]
This is old and odd behavior...

**Comment by SeanAtr0n** [comment]
behavior in release
![rubblesplitbugprev](https://user-images.githubusercontent.com/774628/51341949-6752f180-1a47-11e9-9186-062c801b942c.gif)
