### ISSUE TITLE
Master: "plan research" tutorial broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10718]
1) checking "show all" not counts, maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10702
2) "mouse over" - no tooltip, no complete :(

![default](https://user-images.githubusercontent.com/4980243/51320395-b2cdc580-1a70-11e9-9410-8851d1e60554.png)
![default](https://user-images.githubusercontent.com/4980243/51320511-266fd280-1a71-11e9-9e97-5db7642de520.png)

**Comment by craig-jong** [comment]
should be fixed in an earlier PR.
