### ISSUE TITLE
Master: Harvesting Huckleberries still shows them on plant 

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10713]
![default](https://user-images.githubusercontent.com/4980243/51318503-94b19680-1a6b-11e9-93c2-00b5a823428b.png)

**Comment by Quadbro** [comment]
@SeanAtr0n  @johnkslg Can somebody help me with that? the problem is that PlantGrowthComponent messes up his values of age and alpha after game launch (they are different from editor, and the ones server passes to them)/....

**Comment by metachronism** [comment]
verified fixed
