### ISSUE TITLE
Master: new tutorials icon missed or broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10716]
![default](https://user-images.githubusercontent.com/4980243/51318792-59fc2e00-1a6c-11e9-84e0-00968bbbd0aa.png)
![default](https://user-images.githubusercontent.com/4980243/51318855-8adc6300-1a6c-11e9-9eb5-dd434ce68b9f.png)
![default](https://user-images.githubusercontent.com/4980243/51319028-fc1c1600-1a6c-11e9-8a0c-57fa6eb6f168.png)

**Comment by johnkslg** [comment]
Dupe, filed another bug #10791
