### ISSUE TITLE
Master: invisible blocks in stockpile.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10717]
![default](https://user-images.githubusercontent.com/4980243/51319084-28d02d80-1a6d-11e9-9e04-9cfc915640c7.png)
contain
![default](https://user-images.githubusercontent.com/4980243/51319097-31286880-1a6d-11e9-9113-afd2fbdba9df.png)
if i remove 4 sandstone stack
![default](https://user-images.githubusercontent.com/4980243/51319122-4ac9b000-1a6d-11e9-983a-90ccdbb1d854.png)

**Comment by redwyre** [comment]
Specifically seems like a problem with the crates

**Comment by elfl0rd** [comment]
yep, looks fixed after shaders recompiling
