### ISSUE TITLE
Master: new skills window is too big, and cannot be resized.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10714]
(but can moved, lol)
![default](https://user-images.githubusercontent.com/4980243/51318914-b6f7e400-1a6c-11e9-8dbb-1efa06e934f0.png)

**Comment by Conchipedia** [comment]
i thought i checked all these are not duplicated, my bad

**Comment by johnkslg** [comment]
Fixed
