### ISSUE TITLE
Master: material processing tutorial broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10711]
![default](https://user-images.githubusercontent.com/4980243/51318259-db52c100-1a6a-11e9-997e-8624a2bfb326.png)

**Comment by BlazeGuy2** [comment]
Tut completed itself just fine for me on current master

**Comment by elfl0rd** [comment]
fresh master, fresh attempt...
![default](https://user-images.githubusercontent.com/4980243/51517942-6c3fe880-1e2d-11e9-90eb-aef1542f3b23.png)

**Comment by seccombew** [comment]
@elfl0rd What issue did you run into with the tutorial. What specifically is broken about it?

**Comment by elfl0rd** [comment]
I'll try to repro and send more info if it happens.
