### ISSUE TITLE
Converting world 0.7 -> 0.8 ground parts removed.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10719]
![20190117163019_1](https://user-images.githubusercontent.com/4980243/51322047-6933a980-1a75-11e9-8451-a5c77dce4b36.jpg)
![20190117163029_1](https://user-images.githubusercontent.com/4980243/51322048-6933a980-1a75-11e9-83be-c5e5f9f7d705.jpg)

**Comment by metachronism** [comment]
@craig-jong probably need to migrate Dirt into RockySoil, or @keegan-o needs to add dirt back as a block

**Comment by keegan-o** [comment]
Dirt is still a block type that we use for now, for all dug up topsoil.

**Comment by craig-jong** [comment]
Yea, dirt still exists. So I'm not exactly sure what block is every getting nuked here.

**Comment by craig-jong** [comment]
Going to close this; reopen if you have more info since I can't figure out what this is.

**Comment by elfl0rd** [comment]
you can create new world from "defaultworld" in 7.8 and convert it, if you want research :)

**Comment by elfl0rd** [comment]
7.8 world, all ok,
[0.7.8.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2821356/0.7.8.zip)
![20190201142636_1](https://user-images.githubusercontent.com/4980243/52120613-e5112280-262d-11e9-99ff-f0a595dbbe08.jpg)

converted to 0.8 - forestsoilblock removed.
[converted0.8.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2821390/converted0.8.zip)
![20190201143606_1](https://user-images.githubusercontent.com/4980243/52120947-09b9ca00-262f-11e9-9358-0d688dbedd87.jpg)

**Comment by metachronism** [comment]
@johnkslg @seccombew more reasons to not support migration - we havent tested it extensively and its not possible to win or progress as all the resources dont exist
