### ISSUE TITLE
Master: profession tooltip can be out of screen

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10715]
![default](https://user-images.githubusercontent.com/4980243/51318990-e4dd2880-1a6c-11e9-8ee2-78d3f519adea.png)

**Comment by Spydarlee** [comment]
Hey @elfl0rd are you still getting this on latest? Mine looks okay today:

![image](https://user-images.githubusercontent.com/553695/51541089-df5a5680-1e4f-11e9-9217-d9ff6681d074.png)

There was a tweak to the code in this area recently that could have fixed this, but just want to make sure!

**Comment by elfl0rd** [comment]
yep, it's fixed on fresh master, but after window resize - tooltips os too far away, heh. :D
