### ISSUE TITLE
Master: need info about "no currency in treasury"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10726]
Current behavior is confusing.
![default](https://user-images.githubusercontent.com/4980243/51345147-50de8180-1aab-11e9-92e7-e7243dc04d5a.png)
![default](https://user-images.githubusercontent.com/4980243/51345312-ad41a100-1aab-11e9-86d3-6290d4099d06.png)

**Comment by elfl0rd** [comment]
Not see any changes.

**Comment by Quadbro** [comment]
Seems like changes didn't get applied, probably i missed to commit, sorry -_-
