### ISSUE TITLE
Master: Otter provide meat instead of carcas.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10723]
In real life, otter skin used in many valuable products!

https://www.ebay.com/bhp/otter-fur

https://github.com/StrangeLoopGames/EcoIssues/issues/10615

**Comment by craig-jong** [comment]
fixed in master

**Comment by Sobaton** [comment]
Otter provide meat instead of carcas in 8.1.0 #61937788

**Comment by beastyn** [comment]
@craig-jong I can collect two carcasses from one otter.

**Comment by SlayksWood** [comment]
Can't reproduce in 0.8.2.0 staging-9-n. Seems fixed
