### ISSUE TITLE
Somehow cutting down a tree made debris 10m away

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10720]
Chopped down trees here
![image](https://user-images.githubusercontent.com/431728/51331090-a1aea400-1ac4-11e9-8cd6-3e6342fc22e6.png)

Debris ended up over there (and took out my poor huckleberry bushes :'( )
![image](https://user-images.githubusercontent.com/431728/51331120-b4c17400-1ac4-11e9-8490-d15da37b6f8e.png)

**Comment by SlayksWood** [comment]
I assume this related with #12553. It's never happen with alone tree.
