### ISSUE TITLE
After logging back into Stuffed elk I got a black screen and couldn't move

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10721]
![image](https://user-images.githubusercontent.com/431728/51335133-0bcb4700-1acd-11e9-9145-1d8a8a85ae2c.png)

Esc didn't do anything, so can't disconnect
Can move stuff around in inventory, and eat

**Comment by elfl0rd** [comment]
`/unstuck`?

**Comment by redwyre** [comment]
Did nothing

**Comment by elfl0rd** [comment]
Duplicate of #11226
