### ISSUE TITLE
Master: Treasury - can set only my own currency as world

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10728]
![default](https://user-images.githubusercontent.com/4980243/51345643-98194200-1aac-11e9-898e-d29b11183d4b.png)

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/51504338-49fa8c00-1d95-11e9-9e6a-60411fb581d6.png)
I can set the other currencies as the world default just fine.  Probably got fixed somewhere along the way.
