### ISSUE TITLE
Chat is inserting any second link after the first

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10737]
![image](https://user-images.githubusercontent.com/431728/51360966-89b53f80-1b19-11e9-87fe-b3844e4f602c.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10636

**Comment by redwyre** [comment]
To be clear, the typed text was:
redwyre: I'll sell you charred fish for 8 credits, and will buy scrolls and a fixed road tool :P
redwyre: well that was weird
redwyre: charred fish
redwyre: charred fish road tool
redwyre: charred fish charred pineapple
redwyre: charred fish charred fish

**Comment by redwyre** [comment]
Looks like this is related to your recent changes to TextLinkManager @Spydarlee

**Comment by Spydarlee** [comment]
Got a fix for this locally, but had trouble pushing today so will try again tomorrow.

**Comment by johnkslg** [comment]
Note that if I type Charred Fish in chat, or any phrase, it should only replace the text I wrote with an underlined link. It should never add an additional parenthetical section @Spydarlee

**Comment by D3nnis3n** [comment]
That's the confusing part i already critizised here: https://github.com/StrangeLoopGames/EcoIssues/issues/10636

**Comment by Spydarlee** [comment]
Oh, I thought that was intentional! That's from @Quadbro's original change here: https://github.com/StrangeLoopGames/Eco/pull/3635

Do we not want that behaviour in any scenario then? Not even if two things are named exactly the same? In that case I can just roll back the original change quick 'n easy.

Maybe to solve the original/separate issue, we should prevent deeds, etc. being named after existing items? Or have a different disambiguation solution. But both would be larger tasks.

**Comment by elfl0rd** [comment]
As i see, large problem is "wrong processing"

e.g. "charred fish, tomato" displayed as "Charred Fish (Tomato), tomato"

**Comment by Spydarlee** [comment]
Yeah, I have a local fix for that so it would show Charred Fish (Fish), Tomato. But sounds like we don't want that behaviour anyway so better to just roll back to original implementation for now maybe.

![ecotextlinksdisambiguationscreenshot](https://user-images.githubusercontent.com/553695/51543849-6f9b9a00-1e56-11e9-9c48-6e1cf58e6934.png)

Although Wheat is an interesting case as that's already a problem before anyone renames anything. 🤔

**Comment by elfl0rd** [comment]
old "single" style is bad too, you cannot link to what you want, and lot of problem if multiple items with same name...

**Comment by redwyre** [comment]
Shouldn't the extra stuff just be in the tooltip?

**Comment by elfl0rd** [comment]
> Shouldn't the extra stuff just be in the tooltip?

But what "main" stuff in this case? :D

**Comment by johnkslg** [comment]
A tooltip that pops up and links to everything that matches that name, when there are multiple, would be good. But for now we could roll it back and push something like that to 8.1
Mainly I dont want to have chat get spammed with parenthetical statements you dont want.

There's a lot of bugs and discussion on this that I havent read through, but it seems like it should be a minor problem. There arent that many things with the same name, and when they are (like an object/item/species) you can find the other meanings in the tooltip. Main issue is when its something user created like a law name or something.

**Comment by elfl0rd** [comment]
or districts\vechicles with same names as item. e.g. tailings :) demografics possible too, e.g. "Bank"
