### ISSUE TITLE
[Suggestion] Tier 3 Carpentry World Block

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#10731]
As of the moment the carpenter is only helpful in creation of Tier 1 and 2 blocks, leaving the mason to struggle with steel-infused T3-4 materials.

Instead of burning lumber for charcoal in the later stages, perhaps a new material (e.g. "fireproof composite boards"?) should be made - possibly through a mix of boards, wood pulp, and epoxy (an engineering product, roughly mirroring the steel and rebar of similar rank)?

And finally - we have light and dark brown, white, black, chrome silver, green, and brick red as our building palette. Perhaps we could use a new color in this new material - another red, or something blue could be in order?

EDIT: Just noticed that there's a suggestions board separate from the issues board. Please forward this to the correct sub-board.

**Comment by SatsukiShizuka** [comment]
After some discussion, "plastered drywall" was another suggestion - perhaps a new use for (watering down) the new lime block, plus boards and some kind of insulation (plant fiber or wood pulp in bags?). In any case, the new T3 block should involve some elementary processing by another profession (pref. mason or engineer).

**Comment by DragonSupremacy** [comment]
Alternatively create a use for paper besides currency, by using paper as an insulation between gypsum, which would be similar to limestone and thus become a collaboration between mason and carpenter for the drywall block

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#667
