### ISSUE TITLE
Selling tool tip says "Buy"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10736]
![image](https://user-images.githubusercontent.com/431728/51360794-e2380d00-1b18-11e9-824a-b8cf4489575d.png)

Buy it at XXX (999 available)

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/54108411-813cff00-440e-11e9-98ac-c9b8384955ca.png)
looks fine....

**Comment by Alteraner** [comment]
It is right. In Tooltipp it shows that you can sell pine apples in one shop. To do so, one shop needs to have it added to buy section. I don't see an issue, for me it is logic this way.
Tooltip is in view of who would like to have more informations on the item. you can buy the item in some shops, or you can sell it in some other shops.
