### ISSUE TITLE
Master: no descriptions\info\names for talents

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10730]
![default](https://user-images.githubusercontent.com/4980243/51346521-edeee980-1aae-11e9-8f4d-be97dd97ac83.png)

**Comment by elfl0rd** [comment]
From Conchipedia

**Version:** 0.8.0.0 beta master-0d4ca997

![snap3847](https://user-images.githubusercontent.com/29383891/51388464-655d6100-1b21-11e9-96ef-fd05e4c06c19.png)
the ❔ on Skill Menu not giving a tooltip, also the sub window for them where you can choose between two types are not giving any information so it's a bit of a random chance that you are getting something good or bad

**Comment by BlazeGuy2** [comment]
This is actively being worked on atm.

**Comment by craig-jong** [comment]
I put descriptions in the CSV, but I'm reassigning this to John.

**Comment by craig-jong** [comment]
these are in CSV and there's a PR to add the views. If it's still an issue in the 4pm build, I'll look into it again.
