### ISSUE TITLE
Placing clay doesn't empty shovel

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10738]
![image](https://user-images.githubusercontent.com/431728/51362078-d8fd6f00-1b1d-11e9-8bd2-6c9ef4964650.png)
All from digging one block of clay

Reconnected and it all went away

**Comment by elfl0rd** [comment]
In addition he ignore /dumpcarried

**Comment by BlazeGuy2** [comment]
Infinite clay, while fun, is a bug.

**Comment by redwyre** [comment]
I accidentally fixed this, removed some empty effects on the block, checked into SVN.
