### ISSUE TITLE
8.0.0 Mining Tutorial is a bit broken and a pain if you decide to live in an area with NO Sandstone

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10749]
**Version:** 0.8.0.0 beta master-0d4ca997

if you follow the tutorials and eventually place Campsite down the Mining Tutorial asks you to Target Sandstone then pick it up, that's ok if you are in an area with Sandstone, which i thought i was, but it turns out to be shale
![snap3843](https://user-images.githubusercontent.com/29383891/51386922-0f39ef00-1b1c-11e9-9e52-ba13362ea0d1.png)
but as you can see from the tutorial window it thinks i have mined Sandstone
![snap3840](https://user-images.githubusercontent.com/29383891/51386972-41e3e780-1b1c-11e9-999d-5d4415e5925e.png)
can we have that its **any** type of rock please?

**Comment by keegan-o** [comment]
We fixed this for 8.0 by allowing people to get generic stone out of all stones for now.

**Comment by Conchipedia** [comment]
it's working perfectly for the Stone now, as no matter what i mine , i can make the needed stone 🥇
