### ISSUE TITLE
[8.0.0 Steam Build] Leader does not gain access to treasury bank account

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10741]
Made myself leader, can set taxes but no access to treasury bank account.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51632325-e17ded00-1f03-11e9-8147-09de205083ca.png)
Wasnt able to repro this, I have access.  Add steps and reopen? Or send world?
