### ISSUE TITLE
8.0.0 When trying to Harvest Trillium Gives Error

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10745]
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3838](https://user-images.githubusercontent.com/29383891/51384297-d433bd80-1b13-11e9-9cc5-0371f279b99f.png)
![snap3837](https://user-images.githubusercontent.com/29383891/51384309-d9910800-1b13-11e9-8bb5-c726a476fd1e.png)
i get the seed 
![snap3839](https://user-images.githubusercontent.com/29383891/51384422-32f93700-1b14-11e9-87ae-fd756e0915fc.png)

and i think Fiber (didnt check number), but kicks you from Singleplayer game and leaves the plant still in the world

**Comment by BlazeGuy2** [comment]
Now will give plant fibers
