### ISSUE TITLE
Master: king fern provide only small amount of plant fibers?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10740]
1-2 plant fibers, it's strange for me.

**Comment by Conchipedia** [comment]
0.8.0.0 beta master-0d4ca997 is giving 4 Fiber for me

**Comment by elfl0rd** [comment]
Maybe, but 1-2 from full mature plant is really strange.

**Comment by Conchipedia** [comment]
maybe the graphic thinks the plant is mature when the information is thinking its still tiny 😄

**Comment by Conchipedia** [comment]
other than checking every plant with a soil sampler before harvesting there is only a visual clue to how old the plant is, so some might look more mature than they really are
