### ISSUE TITLE
Crack in water mesh

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10746]
![image](https://user-images.githubusercontent.com/431728/51386415-083bcc80-1b6e-11e9-890d-05a383e5f5e7.png)

![image](https://user-images.githubusercontent.com/431728/51386428-17227f00-1b6e-11e9-8949-213c7ef06e7f.png)

Also doesn't seem to like single dirt blocks
![image](https://user-images.githubusercontent.com/431728/51386465-2efa0300-1b6e-11e9-8b9d-78abbf34ba0f.png)

**Comment by metachronism** [comment]
not gonna fix / dupe

**Comment by redwyre** [comment]
What's the original issue? (So I can keep tabs on it)
