### ISSUE TITLE
Master: temporal antialiasing broken?

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10758]
https://github.com/StrangeLoopGames/Eco/pull/3846

No image, only ghost "menu" image...
![default](https://user-images.githubusercontent.com/4980243/51411872-9322c400-1b7a-11e9-9d83-5842c5ab369b.png)
![default](https://user-images.githubusercontent.com/4980243/51411913-bea5ae80-1b7a-11e9-8ac9-48a7a94ce5eb.png)

happens if "bloom" turned off.

**Comment by metachronism** [comment]
seems to work now, no idea what changed tho
