### ISSUE TITLE
USER ISSUE: cant load world from 7.8.8

### ISSUE THREAD

**Issue by Navaldig** [StrangeLoopGames/EcoIssues#10759]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
the error started to show up when the new verson came out

**Expected behavior:**
load the world normely

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by mirasrael** [comment]
Hi @Navaldig Do you still have a problem? Can you share your save file?

**Comment by mirasrael** [comment]
No answer. Closed.
