### ISSUE TITLE
8.0.0 Logging Skill won't Open

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10750]
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3845](https://user-images.githubusercontent.com/29383891/51387846-7efda900-1b1f-11e9-8abd-1286e145b4ab.png)
all the other skills seem to open and close, Logging will not do anything

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/51419039-4e783800-1b3c-11e9-8744-6a337e5a567d.png)
Logging skill opens just fine on master.

**Comment by Conchipedia** [comment]
maybe your master is slightly different from Steam release, but not a worry if yours works fine 😄
