### ISSUE TITLE
USER ISSUE: Vanishing Tree

### ISSUE THREAD

**Issue by Healingrains** [StrangeLoopGames/EcoIssues#10762]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Continuously chop a log while constantly pressing "E" to pick up the pieces.

**Expected behavior:**
Picking up the logs while constanlty chopping.

**Actual behavior:**
The Tree Vanishes
The End.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The Tree Vanishes
The End.

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/8544
