### ISSUE TITLE
transparentCart

### ISSUE THREAD

**Issue by xtreampb** [StrangeLoopGames/EcoIssues#10767]
so i just noticed this on my server but the main body of one of my players cart is transparent.  The wheels are fine and most of the handle is (you can see some transparency near the body).  You can even see where the sky is between 2 rocks in the distant terrain.
![transparrent cart](https://user-images.githubusercontent.com/1777628/51422475-11806580-1b7d-11e9-9381-127d28e680e5.PNG)

**Comment by beastyn** [comment]
Didn't meet in 0.8.1.4
