### ISSUE TITLE
After getting disconnected from an exception, I am unable to reconnect till restarting client.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10764]
Received unhandled library message ConnectResponse from 192.168.1.250:3000

UnityEngine.Debug:Log(Object)
UnityLogWriter:Write(String) (at Assets/Scripts/System/Settings.cs:20)
Eco.Shared.Utils.Log:WriteLine(LocString) (at C:/Eco/Server/Eco.Shared/Utils/Log.cs:32)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage) (at C:/Eco/Server/Eco.Shared/Networking/NetworkClient.cs:401)
Eco.Shared.Networking.NetworkClient:<Initialize>b__42_0() (at C:/Eco/Server/Eco.Shared/Networking/NetworkClient.cs:283)
System.Threading.ThreadHelper:ThreadStart()

**Comment by seccombew** [comment]
Need repro steps.

**Comment by elfl0rd** [comment]
umm, what?

**Comment by johnkslg** [comment]
Cant repro anymore
