### ISSUE TITLE
Gradients look like a box

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#10763]
![image](https://user-images.githubusercontent.com/18184943/51417799-b6c31b80-1b34-11e9-8d5e-813a77be4b04.png)

**Comment by SlayksWood** [comment]
0.8.1.4
![image](https://user-images.githubusercontent.com/45708377/56882658-e99e7900-6a6c-11e9-9e24-6695d7659cd2.png)
Seems fixed.
@craig-jong If It's fixed, can you close it?

**Comment by D3nnis3n** [comment]
Closing for now, reopen if needed.
