### ISSUE TITLE
Enhancement: Loading time for inventory management

### ISSUE THREAD

**Issue by Chojin666** [StrangeLoopGames/EcoIssues#10760]
It seems like I am not the only one. Imagine you have built very centrally and concentrated, maybe with a friend. Then you easily end up with 20+ storages nearby. So once you open a storage, it needs like up to 10 seconds to show all of the 20+ storages, the content and to sort them as you previously did manually. I have experienced this on several servers. On the long run it is very annoying when you make use of storages alot and it might be worth to be reported if not done already. Image you access such a storage twice in a minute > 20 seconds waiting time per minute.
Maybe there is a way to code an enhancement of the loading time for accessing storages somehow.

Kind regards

**Comment by WeaselDog** [comment]
Thank you for reporting this. Happy to say we have some significant optimization for this the upcoming 9.5 release.
