### ISSUE TITLE
0.8 2\3 new mortared stones is pretty useless.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10776]
In general, you cannot get 2 of 3 type before you have access to iron tools.
If you have access to iron tools - you can craft t2 or higher blocks, you still not want t1.

partially refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10783

I think complex change is not bad,
from current

> basalt - modern
> gneiss - steel
> granite - iron
> limestone - iron
> sandstone - stone

to

> basalt - steel
> gneiss - iron
> granite - iron
> limestone - stone
> sandstone - stone

save mortared limestone and mortared sandstone as t1 and move mortared granite to t2?
it looks less painfull for me...

**Comment by elfl0rd** [comment]
I think complex change is not bad,
from current

> basalt - modern
> gneiss - steel
> granite - iron
> limestone - iron
> sandstone - stone

to

> basalt - steel
> gneiss - iron
> granite - iron
> limestone - stone
> sandstone - stone

save mortared limestone and mortared sandstone as t1 and move mortared granite to t2?
it looks less painfull for me...

**Comment by craig-jong** [comment]
Mining changes - new mortared stones should now be accessible from the beginning albeit with a little bit of difficulty.
