### ISSUE TITLE
USER ISSUE: Vanishing ressources before complete harvesting

### ISSUE THREAD

**Issue by schorzz** [StrangeLoopGames/EcoIssues#10772]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Chop wood / mine stone

**Expected behavior:**
The ressources (logs/trees/stones) should not vanish until completely harvested

**Actual behavior:**
While chopping wood, the tree just vanishes, before it is completely harvested. Also the "no connection" symbol starts to flicker

**Do you have mods installed? Does issue happen when no mods are installed?:**
While chopping wood, the tree just vanishes, before it is completely harvested. Also the "no connection" symbol starts to flicker (not a network issue)

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/8544
