### ISSUE TITLE
Animal Graphical bug / stretching , artifacting

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1077]
i can confirm this issue since i have seen it several times my self especially near larger animal gathering 
http://ecoforum.strangeloopgames.com/topic/1570/texture-stretching-artifacting-and-flickering

**Comment by XerWolf** [comment]
Encountered this last night near a very large group of elk on top of a mountain

**Comment by Pradoxzon** [comment]
I've noticed this happen as well. For me it is more likely to occur the longer I've been playing.
