### ISSUE TITLE
[Server Bug | 0.5.4 ALPHA] Duplicate Tabs in Server GUI

### ISSUE THREAD

**Issue by Albee12** [StrangeLoopGames/EcoIssues#1078]
Server v.0.5.4 Alpha
Windows 10 x64 (Might be universal though)
Bug: The server GUI has two "Property Manager" and "Minimap" tabs (see image). Not really a serious issue, but it does clutter up the window a little.
![image](https://cloud.githubusercontent.com/assets/24682534/22765765/035acbba-ee40-11e6-85bf-550293926516.png)

**Comment by metachronism** [comment]
Found this in 5.5 as well, has been fixed
