### ISSUE TITLE
Eco, pollution

### ISSUE THREAD

**Issue by bagruj111** [StrangeLoopGames/EcoIssues#10785]
We made huge pollution, but the Sea level did not rise and same the temperature did not rise. PPM is 501 and sea level is 40,56. Default sea level on the map is 40. I think sea level have cap 40,56 and the water level does not grow any more. in this point pollution is negligible. 

![eco-bug](https://user-images.githubusercontent.com/46863035/51438253-2f97b400-1caa-11e9-83ec-f1c1e361a2d7.png)

**Comment by bagruj111** [comment]
1 Day later. The water level is rising very slowly

![image](https://user-images.githubusercontent.com/46863035/51468722-f295f500-1d6f-11e9-90a5-f484e9d6ee27.png)

**Comment by D3nnis3n** [comment]
Did the sea level rise further?

**Comment by D3nnis3n** [comment]
Closing for no response, couldn't reproduce it.
