### ISSUE TITLE
Stockpile highlighting different to world

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10788]
Probably related to #10787 

![image](https://user-images.githubusercontent.com/431728/51440636-f0eb1380-1d14-11e9-9d43-83dbe1885cc8.png)

After digging up a block nearby

![image](https://user-images.githubusercontent.com/431728/51440642-0c561e80-1d15-11e9-9b6f-753cea8e74a7.png)

**Comment by elfl0rd** [comment]
looks like https://github.com/StrangeLoopGames/EcoIssues/issues/10717

**Comment by BlazeGuy2** [comment]
Looks like a dup of #10717
