### ISSUE TITLE
0.8 basalt should not appear on top!

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10782]
So... how miner mine granite? gneiss? if he all covered by basalt, required modern tools to dig?
![default](https://user-images.githubusercontent.com/4980243/51432989-1a8f3680-1c52-11e9-8350-d07da2056305.png)
if he comes, he must be sites, leaving the possibility for the passage deeper.

**Comment by craig-jong** [comment]
tbh, as long as it isn't like this everywhere, I don't think its its necessarily bad for some areas to not be minable right away.

**Comment by elfl0rd** [comment]
agree, it's makes mining more interested.(you need mine from different biome\or return with HQ tools.)
Maybe close it?

**Comment by metachronism** [comment]
this is not a bug, this is intended behaviour
