### ISSUE TITLE
0.8 you cannot mine "soft" stones by stone tools, unlike a real life.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10783]
e.g. limestone, (https://en.wikipedia.org/wiki/Limestone#/media/File:Facade_Hagar_Qim.jpg tooooooo many years ago).

partially refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10776

**Comment by craig-jong** [comment]
mining hardness system is changing in https://github.com/StrangeLoopGames/Eco/pull/4023.

I'm going to close this for now since its possible to mine limestone with stone now.
