### ISSUE TITLE
Skid Steer missing when placed underground for first time

### ISSUE THREAD

**Issue by Fireboss4** [StrangeLoopGames/EcoIssues#10792]
Version: 0.7.8.9
Date: 01/20/2019

Upon placing skid steer, the skid steer did not place into the world and instead showed up as missing coordinates. See: http://prntscr.com/m9umlq

-Fireboss4

**Comment by DragonSupremacy** [comment]
World save:
https://1drv.ms/u/s!Ah1HP-nsGmcYifISSW96K_u3Djs0Qw

**Comment by SlayksWood** [comment]
There were a lot of fixes. I can't reproduce this issue in 8.2.8. Seems like fixed. Please reopen if it happen again.
