### ISSUE TITLE
when adding new item for sale in the store, comes up as "SOLD OUT"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10796]
![image](https://user-images.githubusercontent.com/431728/51476292-dd04e780-1dd0-11e9-8bf1-e08b3a351c0d.png)

After unlinking, then re-linking the inventory it shows the count correctly
![image](https://user-images.githubusercontent.com/431728/51476329-fc9c1000-1dd0-11e9-8af9-1c284c8f153a.png)

Regression of https://github.com/StrangeLoopGames/EcoIssues/issues/8410 perhaps?

**Comment by BlazeGuy2** [comment]
Items to buy is also broken, text ui gets in the way of me trying to update the number of things to sell at a store.
