### ISSUE TITLE
Webinterfaces causes high CPU load

### ISSUE THREAD

**Issue by KlaasT** [StrangeLoopGames/EcoIssues#1079]
I've noticed when accessing the web interface under linux using firefox the site causes quite some high CPU load and the interface is nearly unusable. When I try out Chrome and Chromium it isn't that bad.

When pausing the map it isn't that bad however it is still quite hungry on resources.

**Comment by rainfarmer** [comment]
Speeding up the eco government is on our todo list. Will be optimizing as we get closer to release.
