### ISSUE TITLE
New tutorial feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10791]
![image](https://user-images.githubusercontent.com/3536496/51446911-2409b480-1ccd-11e9-8864-480eb7fa8c57.png)
Ask Milenko for one. Specialty Level Info is also missing one. 
Also need to change this bar to the color that we're going to make it (still pending art fix)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51446934-629f6f00-1ccd-11e9-8a0f-6043ff88b61a.png)
Need to have an arrow point to the skill button (its changed now)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51446941-777c0280-1ccd-11e9-9494-9886e7ebda61.png)
Tutorial gets hidden when you open the dialog. Not sure what the best approach here is, probably want something that pops up and directs you, displaying in the bottom right where it doesnt cover stuff up.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51446959-a85c3780-1ccd-11e9-90d8-09b6b590f459.png)
This second item didnt go away after I moused over one.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51446975-e6595b80-1ccd-11e9-83b4-eab32ae28cf9.png)
Research tells you to mouse over specialities, which the specailty picker already did.
I feel like the research tutorial can probably be delayed till a research bench is put down? Or something.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51447019-6e3f6580-1cce-11e9-974f-2cdc09569b1d.png)
I would put the bread icon to the side of the player, along with a star, to denote a specialty

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/51447032-8f07bb00-1cce-11e9-8823-35ee264f4157.png)
Make these fade in one-by-one, and list their titles, so you can get an idea of what talents are like.  Also use the new talent frame, which starts with a question mark, so they understand what you're referring to.

**Comment by johnkslg** [comment]
Should add another page to the specialty panel highlighting the XP multiplier, which is here:
![image](https://user-images.githubusercontent.com/3536496/51447050-c24a4a00-1cce-11e9-8829-f818fdc19e70.png)

And showing this icon, which represents XP gained for skills:
![image](https://user-images.githubusercontent.com/3536496/51447054-d42bed00-1cce-11e9-9e22-a3395b2664bf.png)
(with a skill icon in it)

Nice work overall!

**Comment by johnkslg** [comment]
If you can fix the missing icons, we can push the rest to 8.1

**Comment by craig-jong** [comment]
Let me know if you need any help with this (like where things are, etc)

**Comment by Quadbro** [comment]
@craig-jong  oh, too many issues :D np, i already discovered how it works and what is where located)
