### ISSUE TITLE
[0.5.4] Animal spawning and dispersion

### ISSUE THREAD

**Issue by XerWolf** [StrangeLoopGames/EcoIssues#1080]
Animals currently are either repopulating beyond their environment support that should be possible or are graphically duplicating.  It seems that herds spawn continuously in certain locations and predation is not sufficient to quell their numbers.  The graphs also appear to be incorrect.  A large population of elk wolves rabbit and turkeys have taken residence on top of a mountain.  There is only snow on the mountain top and yet there are approx 200 elk that tend to lag the server when they all decide to flee from you. Server states that there are only 50. 
![](http://i.imgur.com/3ko05Hs.jpg)

**Comment by metachronism** [comment]
fixed in 5.5
