### ISSUE TITLE
Master: rmb on storage with empty selected slot - "Target storage is full!"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10808]
![default](https://user-images.githubusercontent.com/4980243/51518186-1e77b000-1e2e-11e9-9d8c-9069de39d7a9.png)

**Comment by redwyre** [comment]
Happens for pots in 0.8.0.2
![image](https://user-images.githubusercontent.com/431728/52832092-d133e900-3122-11e9-888a-9cc17acc35c6.png)
