### ISSUE TITLE
8.0.0 Saguaro Cactus No debris and so no way to get seeds and replant

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10801]
**Version:** 0.8.0.0 beta master-0d4ca997

![snap3862](https://user-images.githubusercontent.com/29383891/51490181-6224d800-1da2-11e9-8a11-6cb08dae5aa5.png)
We get the Sound like a normal Tree when chopping and it falls down, so Expected to get some debris on the floor so we have to clear up behind ourselves and that should also mean it should give a chance to produce seeds which can be collected and then **NEW** ones can be planted

**Comment by Conchipedia** [comment]
**Version:** 0.8.0.0 beta staging-74282bf1
Adding to this as this is still an **old** issue that doesn't look right and its related to Saguaro Cactus.
when targeting the Cactus it is **all** green in colour
![snap3872](https://user-images.githubusercontent.com/29383891/51643149-6815e700-1f63-11e9-8794-206dd2d8d122.png)
any chance of it looking like the way it does when targeting a Branch of the Cactus?
![snap3873](https://user-images.githubusercontent.com/29383891/51643191-87ad0f80-1f63-11e9-9df8-488da58ef294.png)
link to the **old** glowing green issue
[Art] Saguaro Cactus showing no info when looking at with axe, also goes bright green #3831

**Comment by Conchipedia** [comment]
I see we have Debris with **Some** Saguaro Cactus, but it cannot be picked up, all it does is slow you down when trying to walk through it.
![snap3876](https://user-images.githubusercontent.com/29383891/51643747-8977d280-1f65-11e9-91be-c31dfc4d815f.png)

**Comment by keegan-o** [comment]
Fixed again in master and staging now!
