### ISSUE TITLE
room calculation bug

### ISSUE THREAD

**Issue by FWerewolf** [StrangeLoopGames/EcoIssues#10802]
I found a possible bug in calculation of room tier value.
version : local eco server 0.7.8.9 beta, no mods

house:
one room : 10x10x3 (inside) build out of bricks including the ground with a door and some windows (no doors or glass, just a hole) means 407 bricks, acording to the rules marked as a house.
calculated room volume: 300 (correct)
calculated tier value: 2.0 (correct) since I only used bricks (tier 2)

reproduce the bug:
put a small stockpile just outside the house on the ground, no space between house and stockpile
=> tier value still 2.0
put 5 piles of stones (12 per pile) into the stockpile 
=> tier value still 2.0
put another pile of stones (now 6 piles or 6x12 = 72 stones in stockpile)
=> tier value drops to 1.98, saying 407 bricks (tier 2) and 4 stones (tier 0) in it ... yep 4 not 6 
=> this makes no sense
remove one pile of stones
=> tier value is 2.00 again

It doesn't happen if you place the small stockpile with 1 block space to the house.

using normal stockpile (5x5x5)
6 piles of stones (20) 
=> 2.0
7 piles of stones (20)
=> 1.98 AND room volume 301 saying 5 stones in the room

**Comment by jthill** [comment]
Guess I'll include my info with this bug as it's only a little different, running 7.8.9 with a clean local server (only difficulty, network and users show any diffs at all, they're the expected ones), `/testroom` says it's a room but the carpentry table in it says it's not when you put a storage chest in a doorway, not sure what's misbehaving but the inconsistency's got to mean something's misbehaving, right?

Build a minimal 27m^3 interior room, two doors in each wall like so:

![screenshot from 2019-01-22 10-59-11](https://user-images.githubusercontent.com/80352/51559291-63074980-1e36-11e9-8cc7-18cdd5867476.jpg)

Put a storage chest in a doorway with one of its blocks protruding, `/testroom` says it's still a room but the carpentry table shuts off, its status says it's not in a room. Reproducing it I sometimes have to place, pickup, place the chest; sometimes it happens the first time.  Putting the chest just outside the doorway also sometimes does the trick.  Picking up and replacing the carpentry table fixes it, there's easy workarounds for the symptom.

**Comment by tea** [comment]
> put another pile of stones (now 6 piles or 6x12 = 72 stones in stockpile)
> => tier value drops to 1.98, saying 407 bricks (tier 2) and 4 stones (tier 0) in it ... yep 4 not 6

I think stockpile (as an object) isn't being considered in room value calculation; its contents is. So let's say you place your stockpile right next to a window. Then window will still be a window for as long as stockpile's cell right next to the window is empty; as soon as that cell gets filled with block object, that object suddenly becomes part of the room's layout (window - being a hole - becomes part of the room, and 1 block consisting of 4 stone chunks becomes part of room wall).
This probably should be considered as a bug, but there's simple workaround to it - don't place your stockpiles next to your windows/doorways (or place actual window-block or door there).

**Comment by SlayksWood** [comment]
move to #9818
