### ISSUE TITLE
Parking excavator at 0 (zero) coord, cause strange things.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10819]
https://youtu.be/f3PgP7i4eXc

in addition... vechicle drop from ground, if you stay on another border side :P 

https://youtu.be/9Teigs7ZdP4

**Comment by SeanAtr0n** [comment]
similar things happen w/ rubble near 0

**Comment by metachronism** [comment]
never changed syncphysics, so this isnt new

**Comment by SeanAtr0n** [comment]
who said anything about syncphysics... the border issues are obviously related to terrain colliders not wrapping correctly
