### ISSUE TITLE
Master: cannot grab hewnlogs from stockpile using hammer.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10816]
![default](https://user-images.githubusercontent.com/4980243/51519490-246f9000-1e32-11e9-9ab4-26ccdc6811b5.png)
@Quadbro 

i think "if no blocks in stockpile - puckup stockpile, otherwise - gather building blocks by order" in this case.

**Comment by Conchipedia** [comment]
possibly in place to prevent the annoying part of picking up **last** stack of blocks in a stockpile with a Hammer and **always** removing the stockpile (lost count of how many times that has happened)
