### ISSUE TITLE
Master: oak looks strange.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10815]
vertical
![default](https://user-images.githubusercontent.com/4980243/51519160-343aa480-1e31-11e9-8bf9-82ebdccb2943.png)
horizontal
![default](https://user-images.githubusercontent.com/4980243/51519191-4e748280-1e31-11e9-8e3b-c4efbcd87a6c.png)

**Comment by keegan-o** [comment]
@craig-jong tone down the params in Oak.cs to maybe...
                
this.XZScaleRange = new Range(.8f, 1.2f);
this.YScaleRange = new Range(.8f, 1.2f);

**Comment by keegan-o** [comment]
(if you didn't already, these shots may not be reflecting the last changes to those parameters)
