### ISSUE TITLE
Master: "Gain Speciality XP" broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10813]
no tooltip on "research table link"
In addition, it's strange to see this part on this tutorial.
![default](https://user-images.githubusercontent.com/4980243/51518818-32241600-1e30-11e9-8246-ea8290d3c96a.png)

**Comment by johnkslg** [comment]
Elevating this to high because it looks particularly bad.  Follow up with Milenko for icons.

**Comment by D3nnis3n** [comment]
Reopened, still happens. Also the icon is still missing.

**Comment by D3nnis3n** [comment]
Reopening, icon still missing.

**Comment by Tedraic** [comment]
I am not able to mouse over the link in that quest also. Gain Specialty XP: Mouse over the text link of the Research table does not work. It acts as though there is no link at all there.
