### ISSUE TITLE
0.8 Need hotkey display on specialities button.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10810]
Like all other UI buttons on hud.
![default](https://user-images.githubusercontent.com/4980243/51518405-cc835a00-1e2e-11e9-909d-60770cec7a33.png)
"How to open skills?"
![default](https://user-images.githubusercontent.com/4980243/51518417-d7d68580-1e2e-11e9-9c86-9d541935bbe0.png)
![default](https://user-images.githubusercontent.com/4980243/51518443-f046a000-1e2e-11e9-9725-78110a59e761.png)

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/51964094-7d64a700-2476-11e9-9b2c-0b8a4d67ad59.png)

**Comment by johnkslg** [comment]
Make this appear only during mouseover since theres not much room
