### ISSUE TITLE
Master: "Vibrance" broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10814]
And does nothing.
with
![default](https://user-images.githubusercontent.com/4980243/51519133-153c1280-1e31-11e9-9193-62046c9edc57.png)

w\o
![default](https://user-images.githubusercontent.com/4980243/51519125-0ce3d780-1e31-11e9-835a-00015cae1376.png)

**Comment by metachronism** [comment]
this is a good thing :P  vibrance is going to be removed, too much saturation for artists likes

**Comment by elfl0rd** [comment]
Noooooo :( i love vibrance, it make graphics more "game" style and cool...
