### ISSUE TITLE
USER ISSUE: Token error?

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#10828]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Try to log onto server

**Expected behavior:**
Be able to join server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Steam is not responding.</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Steam is not responding.</size>
```

**Comment by D3nnis3n** [comment]
Restart steam. Closing as old issue, report back if it reoccurs.
