### ISSUE TITLE
Master: compost is not removing from shovel\hands after placing.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10837]
![default](https://user-images.githubusercontent.com/4980243/51592307-53ecce00-1f00-11e9-8df2-0c3f582d075c.png)
Like "Placing clay doesn't empty shovel" https://github.com/StrangeLoopGames/EcoIssues/issues/10738

**Comment by BlazeGuy2** [comment]
Fixed in SVN
