### ISSUE TITLE
Master: Sink and Waste Filter, play sounds everytime

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10836]
maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/10488

**Comment by elfl0rd** [comment]
Same for Water Filter

**Comment by elfl0rd** [comment]
Same for waste filter after model swap. (https://github.com/StrangeLoopGames/EcoIssues/issues/10851)

**Comment by keegan-o** [comment]
Fixed in 8.0, and in 8.1
