### ISSUE TITLE
Master: if connection after launch fail, you receive 2 error messages

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10844]
https://youtu.be/JgFOcW5OymY

**Comment by redwyre** [comment]
This is because when running in the editor it tries to connect at start up.

**Comment by elfl0rd** [comment]
what about steam invites? he have connect at startup too.

**Comment by redwyre** [comment]
I don't think it uses the same method, but if you can reproduce it with a steam invite reopen this issue.

**Comment by elfl0rd** [comment]
Absolutely same.
