### ISSUE TITLE
You cannot place fish trap underwater

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10849]
![20190123232720_1](https://user-images.githubusercontent.com/4980243/51634923-84675300-1f66-11e9-8c35-6199aac73799.jpg)

**Comment by Conchipedia** [comment]
you can **only** place a fishtrap underwater if you remove the water with blocks, then place the Fishtrap where the blocks were, sadly this is workaround not working as well as it used to as the water will Not fill the Holes so technically the Fishtrap is in air still (luckily the fish are being caught)
![snap4089](https://user-images.githubusercontent.com/29383891/52400612-8a594a00-2ab7-11e9-8d8d-3c8da8f6745b.png)
![snap4090](https://user-images.githubusercontent.com/29383891/52400613-8a594a00-2ab7-11e9-9306-41b9250a175b.png)
![snap4091](https://user-images.githubusercontent.com/29383891/52400614-8a594a00-2ab7-11e9-9a32-385193e1ef25.png)
![snap4092](https://user-images.githubusercontent.com/29383891/52400615-8af1e080-2ab7-11e9-9860-a9a1ab7c4f55.png)

**Comment by Conchipedia** [comment]
still an issue in 0.8.7
