### ISSUE TITLE
0.8: Old Growth Redwood make invisible wood debris

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10840]
(what about planting it?)

**Comment by elfl0rd** [comment]
UPD: he make occupancy space
![default](https://user-images.githubusercontent.com/4980243/51599028-c6b17580-1f0f-11e9-8ec1-327944ffd207.png)

**Comment by elfl0rd** [comment]
Changing milestone and priority, he CREATE debris, but debris field is invisible.
block terrain from plants\buildings\etc.

**Comment by craig-jong** [comment]
Fixed in staging and master
