### ISSUE TITLE
You can split available to pickup log part and get more resources.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10841]
(This happens before 0.8, but in master with Old Growth Redwood it's EASY to repro)
1) chop log to small parts.
if you pickup this part - you receive 5 log.
![default](https://user-images.githubusercontent.com/4980243/51599451-a46c2780-1f10-11e9-8717-f2591c878c32.png)

2) chop this part again.
Now, you have 2 part, both have 3 log - now you have 6 log instead of 5 :)
![default](https://user-images.githubusercontent.com/4980243/51599468-ad5cf900-1f10-11e9-9bb8-0c3886561a34.png)
![default](https://user-images.githubusercontent.com/4980243/51599478-b51c9d80-1f10-11e9-97ae-80fa933674b8.png)

**Comment by craig-jong** [comment]
We've decided to leave this as-is.

**Comment by elfl0rd** [comment]
Too hard to fix? :D
