### ISSUE TITLE
Master\staging - waste treatment in crafting but no model.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10851]
![default](https://user-images.githubusercontent.com/4980243/51639645-80d9c900-1f72-11e9-93c1-e1586016c170.png)

**Comment by BlazeGuy2** [comment]
Keegan mentioned that he'd fix this in discord.

**Comment by keegan-o** [comment]
Well, I already did the object re-name-- it needs to be fixed in the tech tree.

**Comment by craig-jong** [comment]
This should be fixed in staging.
