### ISSUE TITLE
0.8 deadlocks possible without ability to change\unlearn talents.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10853]
Easiest one - Assembly line, you can have bricks, no access to T3 blocks and assembly line with requirement 2.2

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/51646147-762a2e80-1f88-11e9-819c-37aacd950af4.png)
bricks\glass\lumber... mortaring +0.2 talent.

**Comment by gatno** [comment]
Maybe there should be a ability to reset all skills, but with an limit that you can only unlearn all skills every 168h (1 week)
Of course all levels are 0 then.

**Comment by feildmaster** [comment]
Recovering a star seems like more than enough of a penalty to me. You lose any and all progress, and then possibly add the ability for a law to be present for that action as well.

**Comment by craig-jong** [comment]
All of the "deadlocks" created by the talents have been removed (as far as I know), but reopen it if it its still the case.
