### ISSUE TITLE
Hunting does not give XP

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#10856]
@mirasrael Posting bug from your comments.

**Comment by Conchipedia** [comment]
nothing on killing these Animals (Otter, Tortoise, Hare, Bighorn Sheep, Bison) 
but is **giving XP** on Clean Salmon, Clean Trout, Clean Tuna, Clean Urchins, Crafting Fish Trap, Craftin Fishing Pole, Shred Kelp and Shuck Clams, So it looks like it is **ONLY** the Fishery that produces XP
