### ISSUE TITLE
Skill efficiency needs rebalancing to give the right efficiency 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1085]
http://ecoforum.strangeloopgames.com/topic/1643/efficiency-upgrades

**Comment by Salamaki** [comment]
So what is this here I don't understand, do you want me to clarify again what the problem is? I don't know what github is.

**Comment by noblackthunder** [comment]
we use this here as a bug tracker .. not intended for chatting .. we do that on the forums ;)

**Comment by Salamaki** [comment]
Okay but I already wrote the bug, sorry I am confused. The efficiency upgrades make me get less meat in the end. The example I am giving is that with lv 3 efficiency on Large butchery efficiency with 10 elks I get 98 meat. While without any efficiency levels I would get 100 meat.

**Comment by noblackthunder** [comment]
yea thats why i just linked to your forum post .. ;)

**Comment by Salamaki** [comment]
Thank you then :)
