### ISSUE TITLE
0.8: bricks deadlock (tailoring)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10859]
![default](https://user-images.githubusercontent.com/4980243/51644649-f4370700-1f81-11e9-8eca-3a97f87599c7.png)
![default](https://user-images.githubusercontent.com/4980243/51644635-d7023880-1f81-11e9-90ca-ef57743f0287.png)
or there is a new way to get t2?

**Comment by seccombew** [comment]
Fixed
