### ISSUE TITLE
Staging 0.8 "invisible" dirt road

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10861]
![default](https://user-images.githubusercontent.com/4980243/51645201-36614800-1f84-11e9-8755-69b78dd6965a.png)
maybe happens with master too.

**Comment by seccombew** [comment]
Needs repro steps, and context information.

**Comment by elfl0rd** [comment]
![20190125014017_1](https://user-images.githubusercontent.com/4980243/51713256-725ae280-2042-11e9-9517-c118e8831375.jpg)
![20190125014033_1](https://user-images.githubusercontent.com/4980243/51713255-71c24c00-2042-11e9-88a2-a1a670708a78.jpg)

**Comment by seccombew** [comment]
@elfl0rd Thanks for the info.
