### ISSUE TITLE
0.8 staging placement mesh incorrectly scaled

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10867]
Research table
![default](https://user-images.githubusercontent.com/4980243/51674991-6ab82100-1fe3-11e9-8292-4892ec5800ff.png)
Carpentry table
![default](https://user-images.githubusercontent.com/4980243/51675001-74da1f80-1fe3-11e9-8f54-621287a4169d.png)
Butchery table
![default](https://user-images.githubusercontent.com/4980243/51675029-8a4f4980-1fe3-11e9-9f6b-68255618e359.png)
and maybe more.

**Comment by SeanAtr0n** [comment]
fixed, will be in the build after today's build
