### ISSUE TITLE
0.8 hard to see skill benefits due empty space between skill window and tooltip.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10862]
![default](https://user-images.githubusercontent.com/4980243/51646542-0452e480-1f8a-11e9-844a-5872f395ed20.png)

**Comment by seccombew** [comment]
Can't mouse over tooltips.

**Comment by johnkslg** [comment]
Karn, can you help with this one when you have a moment? I added functionality for the skills window to put tooltips to hug the right edge of the screen, so they dont block the text youre looking at when you hover over stuff, for this specific dialog.  But here that's too far - maybe the better alternative is to make them appear at the rightmost edge of the text being displayed, or something. Anyway not urgent but would add to our polish.

**Comment by elfl0rd** [comment]
Not in release.\hotfixes.
![20190215215100_1](https://user-images.githubusercontent.com/4980243/52877712-d5382900-316b-11e9-8a1f-fe8d4df0ce99.jpg)
![20190215215055_1](https://user-images.githubusercontent.com/4980243/52877714-d5d0bf80-316b-11e9-8f85-83f22e423e21.jpg)
![20190215215132_1](https://user-images.githubusercontent.com/4980243/52877734-e5500880-316b-11e9-9a75-fc48c4c124cf.jpg)

**Comment by Spydarlee** [comment]
So this is fixed in master but priority wasn't high enough for a hotfix - do we want to keep it for 8.1 (if so we can close this again) or hotfix it based on the above GDragon's suggestion? @seccombew, @johnkslg?

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/11395
Can leave in 8.1, hotfixes are only for game breaking stuff.

**Comment by elfl0rd** [comment]
ok.
