### ISSUE TITLE
Law with "sell" allocation not working as intended?

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#10869]
So the other day I made a law to try and create a "government" store.  The concept is, via a law, someone would sell the store a product, and then get allocated the value of said product from the treasure.  This way the store owner should just act as a placeholder and not interact with the currency at all.
![image](https://user-images.githubusercontent.com/38095046/51688585-84913e00-1fba-11e9-9c0c-462caebf92be.png)

However, in testing this out last night, it appears that it is not working in this fashion.  We discovered that when somebody sold an item to the store, "I", the property owner, got the allocation.  As I'm technically the buyer, I am not the intended recipient.  Now I've managed to do a workaround where I'm just acting as the pass-through entity, but the it would have been better for the store to just act as intended.

**Comment by Deantwo** [comment]
Related to notes in #9412.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/67557347-98bac500-f71d-11e9-9ff9-38310e2a4e70.png)
Seems trigge don't work or something else break law

**Comment by Deantwo** [comment]
No options for what price the trade was conducted at? Or way to use the price of the trade to calculate the allocation? :worried:

**Comment by Deantwo** [comment]
This issue needs the `Laws` label.

**Comment by johnkslg** [comment]
This has been reworked for 9.0 and you have much more flexibility. You should be able to do what you need.

**Comment by beastyn** [comment]
It works with districts
