### ISSUE TITLE
0.8 Chasing animals is almost impossible through certain vegetation due to plants slowing you down (king fern i think are the worst)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10875]
**Version:** 0.8.0.0 beta staging-4705f5ae-1

Trying to chase animals through certain vegetation is almost impossible with the plants slowing you down, even Sprinting doesn't work at times, and when you can clearly see the animal through the vegetation the arrows just seem to collide with certain plants (not sure which) then the Bison i was chasing ran off the top of a block ran straight through Tree Foliage and then disappeared.
![snap3903](https://user-images.githubusercontent.com/29383891/51707115-44f93f00-2018-11e9-8ab9-9de4e42ae3a4.png)
![snap3904](https://user-images.githubusercontent.com/29383891/51707116-44f93f00-2018-11e9-8cee-ed9d589477c7.png)
Also the King Fern are so dense you cannot even look at base of the plant with a soilsampler as the foliage is too thick

**Comment by elfl0rd** [comment]
yes, you need change your strategy after hunting changed.

**Comment by Conchipedia** [comment]
if this is still going to be part of Eco, as it seems logical to have plants slowing you down, at least let it **also** effect the animals

**Comment by elfl0rd** [comment]
yep, plants slow animals too. Same as you.

**Comment by Conchipedia** [comment]
no noticeable effect with bison

**Comment by seccombew** [comment]
Intended.
