### ISSUE TITLE
0.8 Fish Trap work as storage

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10873]
1) you can place any items onto (not only fish)
2) if he have items (not fish) he display fish in model.
![20190124203247_1](https://user-images.githubusercontent.com/4980243/51703378-4120e900-2027-11e9-9de3-aab69fc10406.jpg)

**Comment by Conchipedia** [comment]
you could always store stuff in there , it was a real pain when cleaning fish as the raw fish always went into Fish Trap, so stopped New fish coming in

**Comment by elfl0rd** [comment]
Duplicate of #5145
