### ISSUE TITLE
USER ISSUE: Bloomery

### ISSUE THREAD

**Issue by emilrowland** [StrangeLoopGames/EcoIssues#10889]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**

**Expected behavior:**
Bloomery should be viseble

**Actual behavior:**
Bloomery gets inviseble. If you hower over it you will only get a green border around it. 
If you diconect and connect to the game it will be viseble again.

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/9263
