### ISSUE TITLE
Hidden MiniMap

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10881]
Had an issue today which might need a bit of checking.  New player with a new game could not see Minimap but did have the menu.  Nothing he could do would have it show the minimap.  I have him provide a screen shot as I could not understand what he meant about getting overlays but no map.  Normally you cannot move the left hand border all the way to the menu so that the map is totally hidden.  I asked him to mouse over that left hand border and if he got a double arrow or a hand try pulling it to the left since the border is usually there on the minimap and not there if the map is missing   He was able to pull the border to the left and get the map window top open.  He tried to make it hide again completely and it does what it usually does and it only closed the map art way.  His totally hidden map was like that since he started playing and even did a reinstalll to try an get the map back.  I am just posting this as the minimap should not complete hide from view so I something in the install cause it to be hidden like that and no one, like him. would thing to drag at the left border.  I only did because I know if the HUD is corrupt and the map is gone so is that border,
Dragging on the border where arrow is pointing pulled the mini map out of hiding
 
[![Screenshot from Gyazo](https://gyazo.com/73ee6ec0e6f1afdf6de49bb7760e72ea/raw)](https://gyazo.com/73ee6ec0e6f1afdf6de49bb7760e72ea)

Not ever seen this before and you cannot move that border to the right enough to hide the minimap behind the menu.  And it was like that from when he first loaded the game

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce at start game
The minimum size of the left side of the minimap is limited.
![image](https://user-images.githubusercontent.com/45708377/56880967-7f370a00-6a67-11e9-9384-fb3faacfd109.png)
Seems fixed.
If it happens again, please reopen and provide log file.
