### ISSUE TITLE
Hosted Worlds: no way to directly join using server url

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10880]
Before you could enter an IP into the game and directly join a world.

Now hosted worlds doesn't use IPs, and server URL does not work for directly entering.
If the world privacy is set to 'hidden' it makes it impossible to join.

To directly enter, go to Your Worlds > Plus icon

**Comment by mirasrael** [comment]
You can use server id instead of IP now.
