### ISSUE TITLE
Store not showing quantity buttons

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10894]
From store user's perspective:
![image](https://user-images.githubusercontent.com/431728/51775326-16c34e80-2141-11e9-8fea-b186c04c157d.png)

From the owner's perspective:
![image](https://user-images.githubusercontent.com/431728/51775269-e2e82900-2140-11e9-807b-54837b5028da.png)

**Comment by redwyre** [comment]
Happened to me after leaving and coming back to the table, removing the item then adding it again brought back the buttons but they did nothing, all quantities reset to 0.

**Comment by Arend90** [comment]
I also noticed the currency always switches back to Henry V's currency (think the world leader in The Big Eco World) 
![image](https://user-images.githubusercontent.com/31536813/51913633-43909380-23d7-11e9-8705-2e8988fd4d01.png)

**Comment by johnkslg** [comment]
Probably related to this pull request https://github.com/StrangeLoopGames/Eco/pull/3861
@BlazeGuy2

**Comment by Quadbro** [comment]
> I also noticed the currency always switches back to Henry V's currency (think the world leader in The Big Eco World)

That's because his currency is the default one on server, that can be set in treasury

**Comment by elfl0rd** [comment]
As i know, "default" currency change - should change it for NEW stores, not for all existing.

**Comment by Arend90** [comment]
because that is default i cant even have my own currency there :(

**Comment by Quadbro** [comment]
btw @BlazeGuy2 that method you choose for fix is not valid for that case

**Comment by seccombew** [comment]
Fixed
