### ISSUE TITLE
Can't click anywhere in economy viewer to see store location on map

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10892]
These don't work in Trades tab:
![image](https://user-images.githubusercontent.com/774628/51768464-43ba2780-2095-11e9-92ce-c591e2ffbd69.png)

The ones in contracts still seem to work
![image](https://user-images.githubusercontent.com/774628/51768513-62b8b980-2095-11e9-9ba9-60ab8e70bb89.png)

**Comment by johnkslg** [comment]
The 'click' action for the tooltip is supposed to open the location in the map.
