### ISSUE TITLE
Kiln need industrial

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10899]
I think it's strange, haves sawmill in your bedroom :)
![20190125200947_1](https://user-images.githubusercontent.com/4980243/51785107-f22c9e00-2163-11e9-94fc-04a8a21ebbed.jpg)

**Comment by Conchipedia** [comment]
Maybe it for people who snore (see below for various expressions of snoring) 😄 
1. SAW LOGS
To saw or cut logs is a snoring expression that’s widespread except in the Northeast. You could also say you’re sawing big logs or sawing logs and stacking them.
2. SAW WOOD
Variations include chop wood, cut timber, cut wood, and buzz wood. The use of these terms is widespread but less frequent in the South Atlantic, Inland South, and Lower Mississippi Valley.
3. SAW (OR CUT) GOURDS
Like sawing logs or wood, except with gourds. Chiefly used in the South and South Midland.

for the rest see here http://mentalfloss.com/article/93292/13-sonorous-terms-snoring-across-us

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/73054812-69daf900-3e9c-11ea-9c49-24006f76a464.png)
