### ISSUE TITLE
[8.0.0 Staging] Signs content vanishes when read from a specific angle and distance.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10897]
![sign3](https://user-images.githubusercontent.com/25908592/51784705-817a8700-214d-11e9-9610-630645ca8673.png)
![sign2](https://user-images.githubusercontent.com/25908592/51784706-817a8700-214d-11e9-895f-d94ac8aace44.png)
![sign1](https://user-images.githubusercontent.com/25908592/51784707-82131d80-214d-11e9-891c-cb2b88c07fcd.png)

**Comment by DragonSupremacy** [comment]
Have had this happen on 7.8.9 as well

**Comment by metachronism** [comment]
might be a dupe
