### ISSUE TITLE
Sometimes gov comments display quotations and /n

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10906]
On government webpage, in law or election comments.
sometimes a comment will display like this:

"Preventing running for office will restrict the amount of claim Papers in circulation, as they are only injected with new research learned & elections.\nThis is an easy No vote."

When it should be like this:

Preventing running for office will restrict the amount of claim Papers in circulation, as they are only injected with new research learned & elections.
This is an easy No vote.

This only happens 1/10 times or so

**Comment by SlayksWood** [comment]
When you write the name of any material(ex: Coal, brick, dirt, log, stone etc. In your ex: papers ) this error occurs. 
Post type:
Coal
Brick
Stone
Stone Hammer
Log
Dirt
Papers
It will look like this:
"Coal\nBrick\nStone\nStone Hammer\nLog\nDirt\nPapers"

**Comment by Tigran07** [comment]
Completed and made a commit on branch
comments_in_eco
