### ISSUE TITLE
0.8 Staging: Cedar Tree Planting, Natural Growth and Yield Potential (problems)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10907]
**Version:** 0.8.0.0 beta staging-4705f5ae-1

This is showing that i can grow Cedar here
![snap3913](https://user-images.githubusercontent.com/29383891/51792256-73a52000-21a6-11e9-9dde-a5984f5685e5.png)
but the 7 trees i have planted have all died (tree 2 spaces then a tree)
![snap3914](https://user-images.githubusercontent.com/29383891/51792273-b2d37100-21a6-11e9-8459-0c4062001c9a.png)
![snap3915](https://user-images.githubusercontent.com/29383891/51792285-dc8c9800-21a6-11e9-826e-0b6346303937.png)
and the Naturally growing trees (this one grew on its own when i chopped another one down) says this is a 0% match for the Tree
![snap3916](https://user-images.githubusercontent.com/29383891/51792296-03e36500-21a7-11e9-8df1-d355fda2c5da.png)

**Comment by beastyn** [comment]
Problem of dying was solved.
But still something wrong with matching. Overcrowded and moisture issue?
