### ISSUE TITLE
Staging: 0.8 Old redwood - hard to chop down.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10909]
his trunk don't fall, stayed on stump
![20190126213439_1](https://user-images.githubusercontent.com/4980243/51792791-a14e9100-21c7-11e9-9918-424afdee22dc.jpg)

**Comment by elfl0rd** [comment]
nope. fresh prerelease - same.
![20190206153729_1](https://user-images.githubusercontent.com/4980243/52350677-25134380-2a3a-11e9-8c29-9a978afb2565.jpg)

**Comment by SeanAtr0n** [comment]
Duplicate #11076

**Comment by elfl0rd** [comment]
Not duplicate, this issue about "old redwood" trunk is not falling after chop.

**Comment by FragStorm101** [comment]
Think this is the same issue I've had 3 or 4 times so far(8.1), tree just stays on stump and makes the creaking sound as if it's about to fall but doesn't. To make it fall I chop the the bottom of tree(not stump) and collect the chopped piece which causes tree to then fall.

**Comment by SeanAtr0n** [comment]
seems to be fixed
