### ISSUE TITLE
Fruit Salad have hulkberry icon

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10903]
![default](https://user-images.githubusercontent.com/4980243/51787433-f0260780-2182-11e9-9d58-da7f42aacabd.png)
just compare with basic salad!
![default](https://user-images.githubusercontent.com/4980243/51787425-e2708200-2182-11e9-8d65-a28652b0887e.png)

**Comment by SlayksWood** [comment]
move to #11981
