### ISSUE TITLE
Staging: Old chat history is enlarged

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#10905]
![20190126163159_1](https://user-images.githubusercontent.com/841990/51789402-cff94700-2188-11e9-891f-bb8ce06bb9a9.jpg)

**Comment by seccombew** [comment]
Two issues:
1 Chat window font sizes irregular. 
2. When at bottom of chat, scroll bar returns to the top and starts to scroll downwards again each time a new chat message is received.

**Comment by beastyn** [comment]
1 part is fixed in 0.8.1.3

**Comment by beastyn** [comment]
Problem with chat history is still here in 0.8.1.3

**Comment by WeaselDog** [comment]
@SlayksWood Can you confirm this is still an issue?

**Comment by Praefator** [comment]
Haven't seen this issue pop up at all recently, fairly sure it has been resolved at some point

**Comment by WeaselDog** [comment]
Thanks!
