### ISSUE TITLE
0.8 staging - too many tailings

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10917]
https://github.com/StrangeLoopGames/EcoIssues/issues/9867
![default](https://user-images.githubusercontent.com/4980243/51798973-4bf89b00-222c-11e9-8cd2-d0c51ad29213.png)
Blast 2 world block from one.
Same for bloomery
![default](https://user-images.githubusercontent.com/4980243/51798979-67fc3c80-222c-11e9-8268-fcc6fcfbb792.png)

**Comment by metachronism** [comment]
intended, passing to craig to confirm

**Comment by elfl0rd** [comment]
Work fine in 0.7.8.9, new(old) behavior is terribe for me.
![default](https://user-images.githubusercontent.com/4980243/51861832-44c9ae00-234e-11e9-8b64-13d5983400a7.png)
Blast max eff 1 world block of ores = 1 world block of tailings.
![default](https://user-images.githubusercontent.com/4980243/51861901-73478900-234e-11e9-958e-4247a3a5bad8.png)
Bloomery max eff 1 world block of ores = 1 world block of tailings.

**Comment by craig-jong** [comment]
Fixed in Staging.
