### ISSUE TITLE
0.8 staging: Round and Square Pots + Seeds (fake plants)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10914]
**Version:** 0.8.0.0 beta staging-4705f5ae-1

- [ ] 1. Storage Tab: Cannot see other storage and other Storage cannot see this one
![snap3922](https://user-images.githubusercontent.com/29383891/51795445-622a3b00-21db-11e9-9f72-19c641b2046e.png)
- [ ] 2. Fake Plant Tab: nothing Here
![snap3923](https://user-images.githubusercontent.com/29383891/51795446-622a3b00-21db-11e9-84e9-cb3a118d9754.png)

- [ ] 3. No Tree Seeds Work (Birch,Cedar,Fir,Palm,Redwood and Saguaro) 
Would Be nice to have Baby Trees in Pots (a little bit like a Bonzai tree)

- [ ] 4. **Now For Each Seed** and how they look in Pots(s)**

![snap3949](https://user-images.githubusercontent.com/29383891/51795764-ecc16900-21e0-11e9-8b0e-552f55cfa0a3.png)
![snap3950](https://user-images.githubusercontent.com/29383891/51795765-ecc16900-21e0-11e9-847d-1a54d0694dda.png)
![snap3951](https://user-images.githubusercontent.com/29383891/51795777-05ca1a00-21e1-11e9-9c61-1b7cc38d4a5c.png)
![snap3952](https://user-images.githubusercontent.com/29383891/51795778-05ca1a00-21e1-11e9-872d-c22c7b9b4943.png)
![snap3953](https://user-images.githubusercontent.com/29383891/51795788-2e521400-21e1-11e9-8903-13b8372b8bed.png)
![snap3954](https://user-images.githubusercontent.com/29383891/51795789-2e521400-21e1-11e9-92d5-8f6cbfc0aa25.png)
![snap3927](https://user-images.githubusercontent.com/29383891/51795538-9d793980-21dc-11e9-9e53-50d13c60baf5.png)
![snap3926](https://user-images.githubusercontent.com/29383891/51795540-9f42fd00-21dc-11e9-875c-93f4b9db1537.png)
![snap3928](https://user-images.githubusercontent.com/29383891/51795546-dd402100-21dc-11e9-959e-c1ed46bb2ea0.png)
![snap3929](https://user-images.githubusercontent.com/29383891/51795547-dd402100-21dc-11e9-8238-c8cbc71153b4.png)
![snap3930](https://user-images.githubusercontent.com/29383891/51795575-b504f200-21dd-11e9-8d7d-a4fad17aad0f.png)
![snap3931](https://user-images.githubusercontent.com/29383891/51795576-b504f200-21dd-11e9-9d29-adc95c86e280.png)
Sometimes when Adding more seeds (one by one) they look dead (first try was 12, this time it was 13)
![snap3932](https://user-images.githubusercontent.com/29383891/51795577-b504f200-21dd-11e9-9152-51d1b9a4f514.png)
![snap3933](https://user-images.githubusercontent.com/29383891/51795594-0ca35d80-21de-11e9-8cdd-8767808ae887.png)
![snap3934](https://user-images.githubusercontent.com/29383891/51795617-994e1b80-21de-11e9-9b49-e61fc35c898e.png)
![snap3935](https://user-images.githubusercontent.com/29383891/51795603-42484680-21de-11e9-8f0a-a6721d3fdff6.png)
![snap3936](https://user-images.githubusercontent.com/29383891/51795610-686de680-21de-11e9-8b74-2617aa9385c9.png)
![snap3937](https://user-images.githubusercontent.com/29383891/51795661-26917000-21df-11e9-8824-8365f0c248bf.png)
![snap3938](https://user-images.githubusercontent.com/29383891/51795662-26917000-21df-11e9-94f1-c393d705b726.png)
![snap3941](https://user-images.githubusercontent.com/29383891/51795697-e088dc00-21df-11e9-9626-a9b72b35994f.png)
![snap3942](https://user-images.githubusercontent.com/29383891/51795698-e4b4f980-21df-11e9-9cb3-a0661f6d378d.png)

- [x] 5. sometimes placing this gives a weird Plant type

![snap3939](https://user-images.githubusercontent.com/29383891/51795704-f39bac00-21df-11e9-9b94-62b8acf7d6cd.png)
![snap3940](https://user-images.githubusercontent.com/29383891/51795705-f39bac00-21df-11e9-9172-04112b0fece6.png)

**Comment by Conchipedia** [comment]
![snap3943](https://user-images.githubusercontent.com/29383891/51795713-1b8b0f80-21e0-11e9-9344-a0be5944f193.png)
![snap3944](https://user-images.githubusercontent.com/29383891/51795714-1b8b0f80-21e0-11e9-8a2f-443043c23d98.png)
![snap3945](https://user-images.githubusercontent.com/29383891/51795728-52f9bc00-21e0-11e9-8ef5-d58c844a96b5.png)
![snap3946](https://user-images.githubusercontent.com/29383891/51795729-52f9bc00-21e0-11e9-8224-51440d5457ab.png)
![snap3947](https://user-images.githubusercontent.com/29383891/51795736-9a804800-21e0-11e9-8bde-d796474227f7.png)
![snap3948](https://user-images.githubusercontent.com/29383891/51795737-9a804800-21e0-11e9-9015-3249a2593600.png)
![snap3949](https://user-images.githubusercontent.com/29383891/51795838-96a0f580-21e1-11e9-8956-d6f09721e7b2.png)
![snap3950](https://user-images.githubusercontent.com/29383891/51795839-96a0f580-21e1-11e9-9f1b-238040fd9f76.png)
![snap3951](https://user-images.githubusercontent.com/29383891/51795840-97398c00-21e1-11e9-9ad6-a3fc8bcff66f.png)
![snap3952](https://user-images.githubusercontent.com/29383891/51795841-97398c00-21e1-11e9-8e2c-9d2666cb9f54.png)
![snap3953](https://user-images.githubusercontent.com/29383891/51795842-97398c00-21e1-11e9-8541-14f458f966dc.png)
![snap3954](https://user-images.githubusercontent.com/29383891/51795843-97398c00-21e1-11e9-91ce-1a94a0db3b3f.png)
![snap3955](https://user-images.githubusercontent.com/29383891/51795879-28106780-21e2-11e9-9601-2da773d7ab2a.png)
![snap3956](https://user-images.githubusercontent.com/29383891/51795880-28106780-21e2-11e9-9bf5-b40e6e8722a3.png)
![snap3957](https://user-images.githubusercontent.com/29383891/51795883-3199cf80-21e2-11e9-8bd3-16ef4a617266.png)
![snap3958](https://user-images.githubusercontent.com/29383891/51795884-3199cf80-21e2-11e9-933a-391c1b0c7f81.png)
![snap3959](https://user-images.githubusercontent.com/29383891/51795885-3199cf80-21e2-11e9-85e7-35ea7e785936.png)
![snap3960](https://user-images.githubusercontent.com/29383891/51795886-3199cf80-21e2-11e9-9482-41abbc5693d8.png)

**Comment by Conchipedia** [comment]
![snap3961](https://user-images.githubusercontent.com/29383891/51795970-69eddd80-21e3-11e9-851a-a1f69c89d203.png)
![snap3962](https://user-images.githubusercontent.com/29383891/51795971-6a867400-21e3-11e9-96cd-e68cd35a060f.png)
![Uploading snap3963.png…]()
![Uploading snap3964.png…]()

**Comment by Conchipedia** [comment]
![snap3979](https://user-images.githubusercontent.com/29383891/51796054-850d1d00-21e4-11e9-86b5-7a448d0af1ab.png)
nothing appears in Pot for this one
![snap3980](https://user-images.githubusercontent.com/29383891/51796060-935b3900-21e4-11e9-8d8e-4d544f418878.png)
![snap3981](https://user-images.githubusercontent.com/29383891/51796135-1aa8ac80-21e5-11e9-96b7-611e0a5809d3.png)
![snap3982](https://user-images.githubusercontent.com/29383891/51796136-1aa8ac80-21e5-11e9-83f2-5013b4451ae4.png)
![snap3983](https://user-images.githubusercontent.com/29383891/51796137-1b414300-21e5-11e9-8846-372f576d16db.png)
![snap3984](https://user-images.githubusercontent.com/29383891/51796138-1b414300-21e5-11e9-906c-10ec6ded620c.png)

Some plants do look good the size they are, and some look awful with overlap or they are way too big.


The test was done outside, this Orchid is inside a room and will not disappear no matter what i try, it even added more to the pot, i even tried building over the place where the orchids are, they still are there even after disconnect and quitting game
![snap3985](https://user-images.githubusercontent.com/29383891/51796141-26946e80-21e5-11e9-9ed7-f6536935684b.png)

**Comment by Conchipedia** [comment]
might be just a glitch with singleplayer (cant always reproduce) but if i take a seed out and swap them over with the pot next to it i can have more than one plant growing visually in the same pot
![snap4005](https://user-images.githubusercontent.com/29383891/51804171-5c713b80-2255-11e9-8331-9d41f6e9a184.png)

**Comment by Conchipedia** [comment]
also the Papaya Seed When planted in a Pot creates such a Huge Plant it grows through the Ceiling of the Lower Floor and Appears upstairs
![snap4163](https://user-images.githubusercontent.com/29383891/52918685-c24f6100-32f1-11e9-8b8e-8b7050b62a39.png)
![snap4164](https://user-images.githubusercontent.com/29383891/52918686-c24f6100-32f1-11e9-8057-b41b90374399.png)

**Comment by SlayksWood** [comment]
I will create a separate issues for this one.
Point 1 - #17126
Point 2 - #17127
Point 3 - will here #17114
Point 5 - Seems fixed. I can't reproduce it.
Point 6, 8 - already fixed.
Point 4, 7  - created a separate issue for better displaying fake plants. #
