### ISSUE TITLE
0.8 Stuffed ELK have incorrect collision (+0.8 block)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10910]
![20190126183438_1](https://user-images.githubusercontent.com/4980243/51792802-c7743100-21c7-11e9-8a2c-fdab722133ae.jpg)

**Comment by SlayksWood** [comment]
Seems fixed with new stand.
![image](https://user-images.githubusercontent.com/45708377/73717654-7b898f80-472b-11ea-815a-c3918c6cc03a.png)
