### ISSUE TITLE
[SERVER BUG] No animal population graph

### ISSUE THREAD

**Issue by MrQuark** [StrangeLoopGames/EcoIssues#1091]
Server Issue

Universal Issue

In 4.3.0 the server used to have an animal population graph, as far as I know that is. Now there is no animal population graph. I have contacted Metachronism and he said they did not (at-least intentionally) remove the graph.

It is easy to reproduce.

Launch as far as I know 4.3.0+

4.3.0+

Gone by the how to report bugs thread on forums [here](http://ecoforum.strangeloopgames.com/topic/81/how-to-report-bugs)

**Comment by rainfarmer** [comment]
Does not display on fresh servers. Should be working on a server that has run for a day or so.
