### ISSUE TITLE
Wolf Whisperer Articles

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#10912]
If on the Wolf Whisperer - if you log out wearing the items you get with the tier and the server reboots while you are off line you then get another set of articles when you log back on.  This maybe why some people that obviously should not have wolf whisperer masks and shirt do have them.  I am not sure of the code checks for persons tier when they go to use those and is prevented which is what I though was what happened so they and Alpha awards could not just be spawned in by the admin but it appears they can use them.  Causing a bit of scamming as well as arguments over these and they are being used to get people to join certain servers and to stay on certain servers.

**Comment by WeaselDog** [comment]
No longer an issue
