### ISSUE TITLE
Wall blocks sitting in center of tiles, rather than edge

### ISSUE THREAD

**Issue by Ruined1** [StrangeLoopGames/EcoIssues#10918]
These wall blocks sit centered:
![image](https://user-images.githubusercontent.com/1514573/51799752-5cd8ea80-21f3-11e9-8c71-565e981c5acb.png)

Which causes the floor to stick out:
![image](https://user-images.githubusercontent.com/1514573/51799755-66fae900-21f3-11e9-888e-3713f2f1c010.png)

Was told to report this. Not sure if intended or what.

**Comment by elfl0rd** [comment]
Intended as i know.

**Comment by metachronism** [comment]
intended
