### ISSUE TITLE
[0.8.0] Sickle should not destroy grass on a second swing

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10913]
**Version:** 0.8.0.0 beta staging-4705f5ae-1
fully grown plant growing
![snap3919](https://user-images.githubusercontent.com/29383891/51793455-a9530480-21b8-11e9-8c7b-2d04e268599a.png)
info for growing plant, this can then be gathered by Scythe
![snap3917](https://user-images.githubusercontent.com/29383891/51793446-92acad80-21b8-11e9-87d9-f63973aa5c8d.png)
Smaller Plant Appears after Gathering mature plant
![snap3920](https://user-images.githubusercontent.com/29383891/51793466-d3a4c200-21b8-11e9-957c-aca060e26320.png)
![snap3918](https://user-images.githubusercontent.com/29383891/51793476-02229d00-21b9-11e9-9685-34d09034de2d.png)
this can then be gathered by Scythe but gives nothing as it is not a Mature plant and should not be able to be gathered,

**Comment by Conchipedia** [comment]
Same Happens for Big Bluestem
![snap4045](https://user-images.githubusercontent.com/29383891/52131093-d9285f00-2633-11e9-824f-0efb006acc6d.png)

**Comment by WeaselDog** [comment]
We can change this now that we have a machete

**Comment by Conchipedia** [comment]
still not sure what is going to happen with using a scythe (sickle). the old way was you gathered the plant fiber using the scythe (sickle)  (also got seeds of this plant as well if lucky) and that left a part of the plant behind so it could regrow, but at the moment in 0.9 u just gather it for the plant fiber (No seeds are dropping) and then you just use scythe (sickle) again and the plant gets destroyed.

the Machete does seem a bit of a useless tool it won't give you anything when using and just clears plants, i could do this just by placing a Block or rubble on a plant and it disappears and not use any calories

**Comment by WeaselDog** [comment]
The intended behavior should be that the sickle is used for harvesting, but as you pointed out it should not destroy the plant on a second swing. We can also re-look at the seed drop rate for the different grasses.

The machete is a tool for clearing wild plants to help with movement speed or to prevent overcrowding in agriculture. It should be faster than any other method of clearing plants.

**Comment by NN-Mike** [comment]
I would like to add that currently the iron scythe only chops the 1st hit of grass. The second swing still consumes calories, but does not provide plant fiber or destroy the plant
