### ISSUE TITLE
0.8 collaboration presets in client broken.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10929]
nocollab
```
{
  "CollaborationPreset": "MediumCollaboration",
  "UnlearnRefundRate": 0.5,
  "SpecialtyCostMultiplier": 0.0,
  "SkillGainMultiplier": 24.0,
  "SpecialtyExperienceDivisor": 20.0,
  "SpecialtyExperiencePerLevel": 25.0,
  "ExperiencePerAction": 0.0
}
```
lowcollab
```
{
  "CollaborationPreset": "MediumCollaboration",
  "UnlearnRefundRate": 0.5,
  "SpecialtyCostMultiplier": 0.0,
  "SkillGainMultiplier": 24.0,
  "SpecialtyExperienceDivisor": 20.0,
  "SpecialtyExperiencePerLevel": 25.0,
  "ExperiencePerAction": 0.0
}
```
medium - no changes
high - no changes

In addition, not bad if client read current settings from server config and select it in dropdown meny automatically.

**Comment by D3nnis3n** [comment]
![stars](https://user-images.githubusercontent.com/25908592/51982987-dee93d80-2497-11e9-8a61-f922618e699a.png)

GDragon might have already found this, but common search keywords didn't bring anything up.

**Comment by craig-jong** [comment]
Changed all the presets.
