### ISSUE TITLE
0.8 ores spread in biomes

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10926]
(one ore - 1-2 biomes, i know about split ores to biomes)
But as i think, need small deposits in additional 1-2 biomes.
e.g. copper - main is tundra and cold forest + 2 another biome have small deposits.

Same for ores layers,
e.g. coal.
He spawns only on one layer,

>                    "DepthRange": {
>                     "min": 13.0,
>                     "max": 16.0

I prefer multiple layers, for more vertical digging, instead of horizontal.
(e.g. after only layer spent, you can dig horizontal, or if you have good tools - vertical.)

In current implementation some machinery is little (excavator, skidsteer) and huge (elevator) useless.

In addition as i see, "grassland" contain all ores except copper... (Coal, iron, gold, and all stones.)

@metachronism @Conchipedia

**Comment by metachronism** [comment]
this is largely by design, based on common geology of the biomes in question

**Comment by elfl0rd** [comment]
only one "ores" layer in biome - too? :D
