### ISSUE TITLE
USER ISSUE: ilaysiti12345

### ISSUE THREAD

**Issue by ilaysiti12345** [StrangeLoopGames/EcoIssues#10927]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
1 i

**Expected behavior:**
noooo

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```

**Comment by elfl0rd** [comment]
What version you use? Steam? Slg?

Try to update to latest version, current one is 0.7.8.8

In addition, if you use pirate copy - you cannot play on regular servers.

**Comment by johnkslg** [comment]
Contact support, it looks like youre using wrong credentials.
