### ISSUE TITLE
Problem with french localization

### ISSUE THREAD

**Issue by Cdrix** [StrangeLoopGames/EcoIssues#10922]
Hello, lot of words are translated in french but ingame it's not the same thing. I think there is a problem no ? (even my game is in french version and also for the server).

**Comment by metachronism** [comment]
this is because localization is split between client/server.  Its common to have half the strings in one language and half in another.

**Comment by Cdrix** [comment]
thanks for the reply, but the server is in french, my game too... so there is a problem ? any possibility to fix this problem with the next update ?

**Comment by johnkslg** [comment]
No wont be fixed for the time being.

**Comment by johnkslg** [comment]
Perhaps in the future.
