### ISSUE TITLE
It's possible to get stuck in the tent and /unstuck doesn't help

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10923]
I've had it happen to me (luckily it was my tent so I could pick it up), and had to teleport someone else that got stuck in a tent they didn't have access to.

@keegan-o any ideas why this would be special?

**Comment by SeanAtr0n** [comment]
where in the tent were they stuck?

**Comment by SlayksWood** [comment]
Seems fixed with https://github.com/StrangeLoopGames/Eco/pull/5225
