### ISSUE TITLE
Staging: very slow load time on 300x300 world/cannot enter world

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#10932]
To elaborate on the title: while generation speed increased dramatically (~1 hour versus 2.5 hours before), loading a 300x300 (9 km2) world is taking over half an hour just to load, then kicks to main menu. Upon trying to reload a map, the enclosed dump is created, but isn't immediately visible.

Memory used climbed all the way to 12gb (97% total out of 16gb) just prior to entering world; roughly 90% during the loading process

Log: https://pastebin.com/LFHCsD98

**Comment by johnkslg** [comment]
Too big! We should institute a cap.

**Comment by elfl0rd** [comment]
nooo, not a cap please :( i love big worlds...

**Comment by metachronism** [comment]
wont fix, way above the recommended world size
