### ISSUE TITLE
0.8 Staging shower in crafting but not have model.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10935]
![default](https://user-images.githubusercontent.com/4980243/51866746-d17a6900-235a-11e9-9656-d2b4b52c9a55.png)

**Comment by johnkslg** [comment]
To my understanding the shower wasnt created, some other housing objects were.  @keegan-o and @craig-jong can you guys sync up and make sure all plumbing objects are in and working for 8.0, and any test plumbing objects are hidden and dont have recipes?

**Comment by elfl0rd** [comment]
And sink. Exists, have model (and have bug with endless working sound) but i cannot see any using of it. (no recipes, no dependencies etc...)

**Comment by craig-jong** [comment]
Shower does not exist. It's been removed. The rest of the pipe objects are getting a pass, but I'm closing this bug since it has to do with specifically the shower.
