### ISSUE TITLE
Some graph datasets not returning values from server

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10938]
Most of the datasets under "Humans" tab always return 0 values.

Some work like Remove Stump.

Also, specific users under Humans tab, display same data as the All tab.
For example, my user's data has same Remove Stump values as the All users data.

**Comment by McRegt** [comment]
Hey @rainfarmer 

This issue does not seem to be limited to some values. I cannot see any values on my current server, a few examples:

![image](https://user-images.githubusercontent.com/6177851/54547394-e8762880-49a5-11e9-9391-c29ac5e39436.png)

Nor can I see correct values on some other servers, for example the next one I haven't logged onto in the last week. Yet I have removed stumps?

![image](https://user-images.githubusercontent.com/6177851/54547454-080d5100-49a6-11e9-8b60-edd8509cf0fd.png)
