### ISSUE TITLE
0.8 Wooden Elevator Call Post still not have model.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10940]
![default](https://user-images.githubusercontent.com/4980243/51876525-e4506600-2379-11e9-8009-1b907eb469f1.png)
(or add curved shader to it, heh)
![default](https://user-images.githubusercontent.com/4980243/51876564-0944d900-237a-11e9-8350-b278049d61ff.png)

**Comment by seccombew** [comment]
Fixed
