### ISSUE TITLE
0.8 Treasury issues.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10942]
1) tax and allocate not work (but show message in chat)
![20190129122015_1](https://user-images.githubusercontent.com/4980243/51897872-c65a2400-23c0-11e9-81b4-fd1503db91bf.jpg)
![20190129122012_1](https://user-images.githubusercontent.com/4980243/51897874-c65a2400-23c0-11e9-90e8-bb03e1f0da97.jpg)

2) both actions (tax\allocate) show as tax.
![20190129122305_1](https://user-images.githubusercontent.com/4980243/51897920-d70a9a00-23c0-11e9-8f7f-a9f65c8230b6.jpg)

3) "taxed everyone" show everytime (even if no person to tax\allocate selected)
![20190129122041_1](https://user-images.githubusercontent.com/4980243/51897906-d07c2280-23c0-11e9-944d-74ea6e3da425.jpg)
![20190129122037_1](https://user-images.githubusercontent.com/4980243/51897908-d07c2280-23c0-11e9-8321-8f8b500b59da.jpg)

4) no button to show all money (e.g. for taxing)
5) "dump" require confirmation before execute.
6) Need to add "No currency in treasury" information to Treasury UI

**Comment by D3nnis3n** [comment]
It also shows "taxed EVERYONE" even if you only try to tax ONE person. Should show who has been taxed.

**Comment by Alteraner** [comment]
![image](https://user-images.githubusercontent.com/47274045/52168697-64d1e680-272d-11e9-9fc1-0c1c628cdbdd.png)
As well the value is counted wrong. it is shown as % but to have 10% you need to use 0.1 instead of 10. it might confuse some worldleaders.

**Comment by johnkslg** [comment]
Fixed
