### ISSUE TITLE
Staging: localized server failed if started from client, and show incorrect text.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10948]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2807580/output_log.txt)
![20190129150825_1](https://user-images.githubusercontent.com/4980243/51907528-260ff980-23d8-11e9-85ed-b2d907856bc1.jpg)
![20190129150829_1](https://user-images.githubusercontent.com/4980243/51907529-260ff980-23d8-11e9-8d3c-abd8ffa9c560.jpg)
![20190129150910_1](https://user-images.githubusercontent.com/4980243/51907530-26a89000-23d8-11e9-9c53-5a27ee779758.jpg)

**Comment by Spydarlee** [comment]
Hey @Quadbro could you please give me a shout when this is fixed and I'll take a look at this related issue if it's still a problem: https://github.com/StrangeLoopGames/EcoIssues/issues/11141
