### ISSUE TITLE
Duplicate items in stockpile

### ISSUE THREAD

**Issue by Daravus** [StrangeLoopGames/EcoIssues#10953]
Hello, wanted to share a bug we found. 
If you stand atop of your stockpile like this:
![screenshot 11](https://user-images.githubusercontent.com/47145011/51908838-92a9e900-2416-11e9-8967-f291b324e84c.png)
![screenshot 5](https://user-images.githubusercontent.com/47145011/51909114-86725b80-2417-11e9-9d6b-005616b15a2d.png)

In this example we are duplicating the only stack of stone in this stockpile
Then look down to your stockpile and try to get your cursor between the edge of the block you're standing on and the stones in the stockpile, just like this:
![screenshot 6](https://user-images.githubusercontent.com/47145011/51909005-2b406900-2417-11e9-95d3-682f2675cf9b.png)
The stones now will be highlighted instead of the whole stockpile being highlighted
Then, don't move your cursor at all and just hold "E" or the key for "Pick up" action
![screenshot 7](https://user-images.githubusercontent.com/47145011/51909271-f1239700-2417-11e9-9375-9ed3d7afefd0.png)
It seems that the stockpile is empty of stones, but in reality they are just not visible and also you have anothe stack in your hands
![screenshot 9](https://user-images.githubusercontent.com/47145011/51909480-77d87400-2418-11e9-995c-0bc1cb95b852.png)
If you update stockpile by changing something inside of it, the stones are visible again
![screenshot 10](https://user-images.githubusercontent.com/47145011/51909608-c84fd180-2418-11e9-92d4-f87989f2f8af.png)

We tried it in another place, works just fine
I believe it works only with stuff like stones, bricks, lumber and so on, not with items
Please patch this, it's breaking the game so much
Game version 0.7.8.9
Sorry for the lack of info, just wanted to get it out there quickly before 8.0

If this does go out to the game dev team, you are legends, best game 10/10

**Comment by johnkslg** [comment]
Nice find! Will take a look. Thanks for the super detailed writeup.
