### ISSUE TITLE
Cast Iron Stove Revamp

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#10959]
The old cast iron stove needs love, and a re-design to fit with the times and support an interesting use animation as well. Rob, do a new concept and design for the cast iron stove. Bonus points if you can make it fit in the same occupancy, but maybe figure that out after you do the design as the most important thing here is that it becomes a cooler looking object with more character and flair. Larger is totally finem and may be required in order to get it looking cool. Updating this will help with when we do more new cooking content.

When creating the animation, aim to have it match the audio that was already authored for the object (don't think that will be too hard, nothing needs to be 'exact', just make sure it fits still.

Old asset is 

- [x] Concept
- [x] Models and Texture
- [x] Prefab

Old asset:
Art\Player Built Objects\Cooking\Cast Iron Stove
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/41333f42-6e84-42dd-aab0-a856e766e982)

New asset should have some of the decorative design flair the new cast iron furniture has.

The one thing to remember is the asset does still need a chimney smoke output pipe connection that an iron pipe can attach to, centered in the meter space.

**Comment by Quadbro** [comment]
Audio part was added by Leonard (work indication)

**Comment by keegan-o** [comment]
@RobertMangano this object is ripe for revamping, it could be re-done as a larger stove, too. Evaluate and see if you can add an animation easily to it as it exists now, or if you think it should be re-created. However it is done, it can be done so that the audio that was added can still be used.

**Comment by RobertMangano** [comment]
![castironstove concept.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/ce9cb7be-ee6c-475d-82ae-d09274bd4d43)
