### ISSUE TITLE
0.8 big ghost object if you move close to world object

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10951]
![default](https://user-images.githubusercontent.com/4980243/51908210-3aed8c80-23da-11e9-8b2c-e8b170289fd3.png)

**Comment by elfl0rd** [comment]
yes, this is stable everytime :D more visible at starter camp.

**Comment by redwyre** [comment]
I'm able to reproduce this on the tent, it looks a problem with SEGI
![image](https://user-images.githubusercontent.com/431728/51915331-97769900-2426-11e9-946a-2bdfae8e2176.png)
