### ISSUE TITLE
0.8: players and vechicles often become invisible and intangible

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10952]
But his inventory still available trough linking. It's one of terribles issues at playtesting.

**Comment by SeanAtr0n** [comment]
when does this happen? I haven't seen it during our playtests

**Comment by redwyre** [comment]
"Carts have been consistently lost at the zero coordinate in our town but as I understand it there are other cart loss issues that crop up in a variety of locations
When I lost one crossing the zero coordinate my screen flickered black and blue and it appeared, based upon a waypoint that I was looking towards, that my altitude was rapidly bouncing to wildly different values."

Seems to be happening pretty regularly to players on the big eco server

**Comment by SeanAtr0n** [comment]
the cart thing sounds like a separate issue that should probably have its own bug... this says stockpiles are disappearing?

**Comment by elfl0rd** [comment]
no, no, not zero-related.

HAve this issue permanently at @mirasrael testing server.

**Comment by elfl0rd** [comment]
> "Carts have been consistently lost at the zero coordinate in our town but as I understand it there are other cart loss issues that crop up in a variety of locations
> When I lost one crossing the zero coordinate my screen flickered black and blue and it appeared, based upon a waypoint that I was looking towards, that my altitude was rapidly bouncing to wildly different values."

https://github.com/StrangeLoopGames/EcoIssues/issues/10661

> this says stockpiles are disappearing?

yes, stockpiles, players, vechicles, carts (often), chests, workbenches (periodically)

**Comment by SeanAtr0n** [comment]
sounds pretty vague, can you give a specific example and a client log file from when it happened?

**Comment by elfl0rd** [comment]
yep, i'll record video about it after next staging build appear.

**Comment by SeanAtr0n** [comment]
most likely related to @metachronism 's changes to wait for ground

**Comment by metachronism** [comment]
no repro, need a solid repro case

**Comment by elfl0rd** [comment]
Just look.
![unknown](https://user-images.githubusercontent.com/4980243/52073448-9cf3f080-2598-11e9-8bf4-29e8fb127004.png)
![20190131202823_1](https://user-images.githubusercontent.com/4980243/52073449-9cf3f080-2598-11e9-8c2c-4f419b6e76b2.jpg)

**Comment by SeanAtr0n** [comment]
Ive fixed the general issue that led to some objects not spawning or taking a very long time to spawn, but this bug is pretty general and might include other bugs so if this doesn't fix the cart thing in next build please file a new bug.

**Comment by elfl0rd** [comment]
still happens, you need 2+ players on server to see this issue.
more player - more problems.

**Comment by iForby** [comment]
Can confirm, this issue is still relevant. When going out of render range, and a player moves towards another location where another player is, they are sometimes invisible. IE: A cart looks like it is being pushed itself, due to the player being invisible.

Spooky carts, we're calling them on my server.
