### ISSUE TITLE
Title Tooltips don't work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10969]
In the screenshot you can see that the tooltip has no object and that if you write the title in the chat, it's not linked. Also, it would be great if the title was shown in the player overlay.
![bug2titles](https://user-images.githubusercontent.com/25908592/51982229-a8122800-2495-11e9-93d6-61a349a561ec.png)

**Comment by johnkslg** [comment]
Tooltips should work as normal on titles, can you see whats going on there?
