### ISSUE TITLE
Minting abuse

### ISSUE THREAD

**Issue by ludovi71** [StrangeLoopGames/EcoIssues#10965]
I've witnessed person who was minting his coal ore just because it was easier than storing it somewhere.
That looks like an abuse of a system to me. what do you think ?

**Comment by D3nnis3n** [comment]
I don't see any abuse there. What advantage would he have? Minting the coal into coins makes them vanish, he can't get the coal back.

**Comment by ludovi71** [comment]
Lets say he wants to dig an area for something underground, instead of dealing with the stuff he mined, he can just vanish it

**Comment by D3nnis3n** [comment]
I think that is rather a case for a law, cause this could be done with everything - we officially use gold ore for our global currency, which means people could just do the same. They could do it with pretty much any item for the currencies, i don't see any way to prevent this.

**Comment by ludovi71** [comment]
What if the minted item would become something else after being minted ?
It would be unusable but it would have to be stored somewhere.

**Comment by elfl0rd** [comment]
easiest way - just remove "natural" resources from mint.

**Comment by D3nnis3n** [comment]
No good idea, Gold ore is a very good thing to use as a backing item.

@ludovi71 You mean having the money as a carriable item? Wouldn't like that, bank accounts and all those things would no longer make any real sense.

**Comment by elfl0rd** [comment]
In real life you use smelted gold, not ore ;)

**Comment by D3nnis3n** [comment]
That doesn't matter.

**Comment by elfl0rd** [comment]
In any case you can modify mint settings in file :) 

> You mean having the money as a carriable item? Wouldn't like that, bank accounts and all those things would no longer make any real sense.

i think no, maybe like "garbage" after minting.

**Comment by D3nnis3n** [comment]
Which file? Server-Only mod? Not going to use client side mods.

Don't forget: There are a lot of other items that are processed that you cannot make coins out in real life, there are even machines ...

The only real options left would be clams (as people traded with them earlier) and the bars. That's very little options. Also stones - some people traded with stones way back.

**Comment by elfl0rd** [comment]
> Which file? Server-Only mod? Not going to use client side mods.
yep

> This is a case that should be handled by the server-admin, not the game.

Ofc, but minting to "magic disappears" is really not good, like olt tailings minting :D

**Comment by D3nnis3n** [comment]
That's not magic, it's now currency!

Which file is it? I've searched a long time how i can add land claim papers to the mint.

**Comment by elfl0rd** [comment]
> Which file is it?

Oops, i'm wrong :( all magic hidden in MintComponent.cs not in mod files :(

**Comment by ludovi71** [comment]
Or maybe the problem is that gold ore is so easily obtainable in this game, it doesn't represent value that gold has in real life, maybe if the items that are mintable , were harder to find in the game, it would make more sense.
Just like gold in real life.

**Comment by elfl0rd** [comment]
It's dramatically changed in 0.8, also stones have more usable.

**Comment by D3nnis3n** [comment]
@ludovi71 Every Server-Admin can adapt how rare ores are, so we changed gold ore to be more rare. Also we have a government controlled single currency, things like you say couldn't even happen on our server. That's why i deem this an issue that can easily be taken care of admins / by players with laws, without the need to restrict other servers that make heavy use of the features that would otherwise get removed.

**Comment by ludovi71** [comment]
Oh sorry, didnt know that can be changed in world gen.

**Comment by johnkslg** [comment]
@craig-jong your  call on how you want to handle this. I can see the points, its an infinite consumption thing. I'm of the mind that ore shouldnt be used as currency at all.

**Comment by D3nnis3n** [comment]
Keep it up to the admins, gold ore is one of the best choices for balanced
economies and widely used on servers. The game doesnt need to fix things
that can easily be tanken care of via laws or administration.

Am Do., 31. Jan. 2019, 16:15 hat John Krajewski <notifications@github.com>
geschrieben:

**Comment by ludovi71** [comment]
Lot of things can be handled with laws but i've never seen a law that would make it even close to real life "money creation process"
Servers usually set max amount of the money that can be minted or something similar.

**Comment by D3nnis3n** [comment]
I'd propose to have this configurable.
Add a config where admins can specifiy which items are able to be minted into currency and put a default on it that fixes this issue. This will allow EVERYONE to be happy - which is ever a good idea. Configurability makes games great.

Some reasons for why servers use gold ore for currency:
1. It's somewhat rare, especially when made more rare.
2. It has little use in the game.
3. It can easily be obtained by everyone - no skill requirements, newbie friendly.
4. Using ingots makes the economy have instabilitites, because of the tailings (we do one ore for 2 coins) and the efficiency that plays a role in smelting the ore. Value is fluctuating much because of the efficiency, not good for currencies.
5. Smelted Ingots causes only the smelters to have profits from creating currency - and they are already one of the richest people around on most server.

**Comment by ludovi71** [comment]
Is it possible to configure ore not to be found in those huge veins ? but rather like 20 blocks ?

**Comment by craig-jong** [comment]
There is already a tag in the game that allows/disallows specific items to be used as currency.

Any item can have the attribute [Currency] which is what determines if it can be minted. We're going to stick with the default list of items we've determined to be okay for minting, however would encourage anyone that feels it should be different to modify those attributes. We've already excludes most blocks that we feel people would want to get rid of.

It's possible we may look into moving currency into some sort of item/limits carrying capacity type thing, but for now I believe it's fine.

**Comment by Deantwo** [comment]
Removing the current "backing item" and allowing us to actually back a currency ourselves in a meaningful way would be nice.
The current version of "backing item" is stupid, you break the item. So it isn't "banking" it is using that material to craft the coins, which could be paper or wood or gold, could even be digital currency. What the coin is made of doesn't make sense if we can't convert the coins back into that source.

Instead just allow us to print money as we please, and then the mint owner will need to use a store to allow other to buy the currency, allowing that be the way of backing an item.
