### ISSUE TITLE
World Leader can be removed from treasury access, but has no effect

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10970]
When you become leader and get access to the treasury you can remove the "World Leader" from the managers. The access will be empty afterwards, but you'll still have access rights. Probably World leader should be non-removable.

**Comment by elfl0rd** [comment]
yea, like deed owner.

**Comment by johnkslg** [comment]
Can you add a special case check for this? There is an example when the player tries to remove themselves from their own currency, can do something similar.  Can specialy case Treasury and World Leader.

**Comment by elfl0rd** [comment]
maybe use deed way?
"owner not show in editable list."

**Comment by D3nnis3n** [comment]
Good idea.

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/52038608-5638d300-2565-11e9-9e71-724aa8aaec17.png)
I can manage treasury account in any way... i'm a leader, owned property.

**Comment by D3nnis3n** [comment]
Another bug, open an issue.

**Comment by D3nnis3n** [comment]
![leader](https://user-images.githubusercontent.com/25908592/52164634-bad66800-26f4-11e9-811a-effa2898c472.png)

**Comment by D3nnis3n** [comment]
<img width="1308" alt="bank" src="https://user-images.githubusercontent.com/25908592/52164636-c590fd00-26f4-11e9-957a-092cc9e5b28b.png">

**Comment by johnkslg** [comment]
Should be better after hotfix, but I think you can still remove access. Can you make it prevent this? Check out the code that prevents users from removing their access from their personal bank accounts, can use the same thing.

**Comment by D3nnis3n** [comment]
Noted as fixed in 8.0.4, but isn't. Can still remove world leader from treasury.

**Comment by Quadbro** [comment]
O_O

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/53314337-689df680-38f0-11e9-84c2-ff35ef7138ac.png)

**Comment by D3nnis3n** [comment]
That's not the behaviour in 8.0.4 in which this was mentioned, sorry.
