### ISSUE TITLE
Cause & Effect and Saved Discussions are missing from the Web UI

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10972]
![law](https://user-images.githubusercontent.com/25908592/51984505-c4b15e80-249b-11e9-9d70-b5cb2b6fd78b.png)

Should have been fixed, not removed: https://github.com/StrangeLoopGames/EcoIssues/issues/10370

**Comment by johnkslg** [comment]
Will be put back in a future version.

**Comment by metachronism** [comment]
intentionally removed, so closing this out
