### ISSUE TITLE
missing icons from output_log.txt

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10974]
https://gist.github.com/D3nnis3n/b23a44db7b41cb56ca9128c8f100baab

**Comment by D3nnis3n** [comment]
Missing following icons: AdvancedBakingFocusedWorkflowTalentGroup, AdvancedBakingFrugalWorkspaceTalentGroup, AdvancedBakingLavishWorkspaceTalentGroup, AdvancedBakingParallelProcessingTalentGroup, AdvancedCampfireCookingFocusedWorkflowTalentGroup, AdvancedCampfireCookingFrugalWorkspaceTalentGroup, AdvancedCampfireCookingLavishWorkspaceTalentGroup, AdvancedCampfireCookingParallelProcessingTalentGroup, AdvancedCookingFocusedWorkflowTalentGroup, AdvancedCookingFrugalWorkspaceTalentGroup, AdvancedCookingLavishWorkspaceTalentGroup, AdvancedCookingParallelProcessingTalentGroup, AdvancedSmeltingFocusedWorkflowTalentGroup, AdvancedSmeltingFrugalWorkspaceTalentGroup, AdvancedSmeltingLavishWorkspaceTalentGroup, AdvancedSmeltingParallelProcessingTalentGroup, BakingFocusedWorkflowTalentGroup, BakingFrugalWorkspaceTalentGroup, BakingLavishWorkspaceTalentGroup, BakingParallelProcessingTalentGroup, BasicEngineeringFocusedWorkflowTalentGroup, BasicEngineeringFrugalWorkspaceTalentGroup, BasicEngineeringLavishWorkspaceTalentGroup, BasicEngineeringParallelProcessingTalentGroup, BricklayingFocusedWorkflowTalentGroup, BricklayingFrugalWorkspaceTalentGroup, BricklayingLavishWorkspaceTalentGroup, BricklayingParallelProcessingTalentGroup, ButcheryFocusedWorkflowTalentGroup, ButcheryFrugalWorkspaceTalentGroup, ButcheryLavishWorkspaceTalentGroup, ButcheryParallelProcessingTalentGroup, CementFocusedWorkflowTalentGroup, CementFrugalWorkspaceTalentGroup, CementLavishWorkspaceTalentGroup, CementParallelProcessingTalentGroup, CookingFocusedWorkflowTalentGroup, CookingFrugalWorkspaceTalentGroup, CookingLavishWorkspaceTalentGroup, CookingParallelProcessingTalentGroup, CuttingEdgeCookingFocusedWorkflowTalentGroup, CuttingEdgeCookingFrugalWorkspaceTalentGroup, CuttingEdgeCookingLavishWorkspaceTalentGroup, CuttingEdgeCookingParallelProcessingTalentGroup, ElectronicsFocusedWorkflowTalentGroup, ElectronicsFrugalWorkspaceTalentGroup, ElectronicsLavishWorkspaceTalentGroup, ElectronicsParallelProcessingTalentGroup, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, FertilizersFocusedWorkflowTalentGroup, FertilizersFrugalWorkspaceTalentGroup, FertilizersLavishWorkspaceTalentGroup, FertilizersParallelProcessingTalentGroup, GatheringExperiencedFarmhandTalentGroup, GatheringNaturalGathererTalentGroup, GatheringToolEfficiencyTalentGroup, GatheringToolStrengthTalentGroup, GlassworkingFocusedWorkflowTalentGroup, GlassworkingFrugalWorkspaceTalentGroup, GlassworkingLavishWorkspaceTalentGroup, GlassworkingParallelProcessingTalentGroup, HewingFocusedWorkflowTalentGroup, HewingFrugalWorkspaceTalentGroup, HewingLavishWorkspaceTalentGroup, HewingParallelProcessingTalentGroup, HuntingAggressiveAnglerTalentGroup, HuntingArrowRecoveryTalentGroup, HuntingDeadeyeTalentGroup, HuntingFishermanTalentGroup, IndustryFocusedWorkflowTalentGroup, IndustryFrugalWorkspaceTalentGroup, IndustryLavishWorkspaceTalentGroup, IndustryParallelProcessingTalentGroup, LoggingCleanupCrewTalentGroup, LoggingLoggersLuckTalentGroup, LoggingToolEfficiencyTalentGroup, LoggingToolStrengthTalentGroup, LumberFocusedWorkflowTalentGroup, LumberFrugalWorkspaceTalentGroup, LumberLavishWorkspaceTalentGroup, LumberParallelProcessingTalentGroup, MechanicsFocusedWorkflowTalentGroup, MechanicsFrugalWorkspaceTalentGroup, MechanicsLavishWorkspaceTalentGroup, MechanicsParallelProcessingTalentGroup, MillingFocusedWorkflowTalentGroup, MillingFrugalWorkspaceTalentGroup, MillingLavishWorkspaceTalentGroup, MillingParallelProcessingTalentGroup, MiningLuckyBreakTalentGroup, MiningSweepingHandsTalentGroup, MiningToolEfficiencyTalentGroup, MiningToolStrengthTalentGroup, MortaringFocusedWorkflowTalentGroup, MortaringFrugalWorkspaceTalentGroup, MortaringLavishWorkspaceTalentGroup, MortaringParallelProcessingTalentGroup, OilDrillingFocusedWorkflowTalentGroup, OilDrillingFrugalWorkspaceTalentGroup, OilDrillingLavishWorkspaceTalentGroup, OilDrillingParallelProcessingTalentGroup, PaperMillingFocusedWorkflowTalentGroup, PaperMillingFrugalWorkspaceTalentGroup, PaperMillingLavishWorkspaceTalentGroup, PaperMillingParallelProcessingTalentGroup, SaguaroSeedPackItem, SelfImprovementDiverTalentGroup, SelfImprovementNatureAdventurerTalentGroup, SelfImprovementSprinterTalentGroup, SelfImprovementUrbanTravellerTalentGroup, SmeltingFocusedWorkflowTalentGroup, SmeltingFrugalWorkspaceTalentGroup, SmeltingLavishWorkspaceTalentGroup, SmeltingParallelProcessingTalentGroup, TailoringFocusedWorkflowTalentGroup, TailoringFrugalWorkspaceTalentGroup, TailoringLavishWorkspaceTalentGroup, TailoringParallelProcessingTalentGroup

-------------------

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, ShowerObject, SwitchObject, TollObject

**Comment by craig-jong** [comment]
These are definitely in the game - I'm not exactly sure why they aren't being picked up.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/52237608-dec5b500-287e-11e9-9045-35c72e726dd2.png)

Definitely some issue here...

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/52238973-36b1eb00-2882-11e9-90a9-6d0a3a3b4d65.png)
back in business.

**Comment by Quadbro** [comment]
8.0.4
Missing following icons:
CeibaSeedPackItem
SaguaroSeedPackItem
FarmingFocusedWorkflowTalentGroup
FarmingFrugalWorkspaceTalentGroup
FarmingLavishWorkspaceTalentGroup
FarmingParallelProcessingTalentGroup

**Comment by craig-jong** [comment]
FarmingFocusedWorkflowTalentGroup
FarmingFrugalWorkspaceTalentGroup
FarmingLavishWorkspaceTalentGroup
FarmingParallelProcessingTalentGroup

These are the relevant ones.

We should consider adding an ignore icon tag to developer items so they don't show up in this list.

**Comment by keegan-o** [comment]
Fixed those 4 in master.
