### ISSUE TITLE
Still can't convert 7.8 map to 8.0

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10975]
![laws](https://user-images.githubusercontent.com/25908592/51989932-4d35fc00-24a8-11e9-98c5-36663a130e96.png)

It says "the arithmetic operation caused an overflow"

https://download.godsofwar.de/eco/cycle-5.zip

Make sure to test WITH the DB.

**Comment by metachronism** [comment]
Its not even going to be feasible to play if it does port over, I dont think we should spend a lot of time figuring this out.

**Comment by mirasrael** [comment]
Lol. I found and fixed two issues during working on this one. And both wasn't related to migration.
