### ISSUE TITLE
Butchers Table Not Working Inside of Room Required Space

### ISSUE THREAD

**Issue by aceooooooooo** [StrangeLoopGames/EcoIssues#10979]
I have tried to research this and came  up empty handed. I have a larger room built with the Fishery and then Butchers Table. Both have the same room requirements. The fishery checks out good and works as it is supposed to. However the Butchers Table will not accept the the room. There is a X on the room requirement stating 0.86/ 0.8 average tier. This is the same requirement for the Fishery and it accepts these parameters just fine. I have removed everything from the room. Even created a new room, restarted the server and client. Only to receive the same results. I am not for sure if I am doing something incorrectly, or if this is a bug. I am using ECO Server 0.7.8.9, client side is am running ECO 0.7.8.9  also.
![20190130084955_1](https://user-images.githubusercontent.com/21304745/51999563-e694ec00-246f-11e9-9116-846f231d49de.jpg)
![20190130085021_1](https://user-images.githubusercontent.com/21304745/51999577-ebf23680-246f-11e9-9bb9-422a107b77d1.jpg)
![20190130085114_1](https://user-images.githubusercontent.com/21304745/51999592-f57b9e80-246f-11e9-84e5-14b847276b3d.jpg)

**Comment by aceooooooooo** [comment]
Here is Screen shots with the Butcher Table in the room by its self.
![20190130092052_1](https://user-images.githubusercontent.com/21304745/51999895-a6823900-2470-11e9-9263-76ed44885f90.jpg)
![20190130092129_1](https://user-images.githubusercontent.com/21304745/51999914-abdf8380-2470-11e9-8e39-5fc770b3df3e.jpg)

**Comment by elfl0rd** [comment]
Not same. You can see differency.
Fishery require 0.5 average tier.
Butchery require 0.8 average tier.
Your room - 0.68 average tier.

All works as intended, upgrade your room (e.g. replace dirt floor to hewn logs).

**Comment by aceooooooooo** [comment]
Yes that fixed my problem, thank you. Sry my screen resolution made the blue numbers look incorrect. After you stating Fishery require 0.5 average I zoomed in on the photo, and yep that's what it was. I was very sleep deprived when writing this. My brain was thinking 0.68 that is bigger then 0.8. Now that rested I realize my error. Butchery requires 0.80 my room was only 0.68.  There for need to upgrade to full 1 Tier.

**Comment by elfl0rd** [comment]
Glad for help! :)
