### ISSUE TITLE
Lasers don't target the meteor

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#10978]
Never had this happen before:
![lasertarget](https://user-images.githubusercontent.com/25908592/51992649-ace2d600-24ad-11e9-86bb-b730eace63ae.jpg)

**Comment by seccombew** [comment]
Is this still happening? @D3nnis3n

**Comment by SlayksWood** [comment]
[0.8.1.0 staging-7] Meteor collapses like this:
https://drive.google.com/file/d/1DpkEeIphipCyvB7T03eVGe17uXfUj6kz/view?usp=sharing

Lasers do not activate visually. Just goes the inscription that the meteorite will be shot down in 30 seconds. After 30 seconds, it destroyed.

**Comment by tuha263** [comment]
Seem it does not happen anymore 
![LaserShotMeteor.png](https://images.zenhubusercontent.com/5f38a110742cd7b96b103fdc/c7eb0cfb-f55f-4436-a5e8-53f843278a41)

**Comment by SlayksWood** [comment]
yeah, it's fixed:
![image](https://user-images.githubusercontent.com/45708377/99498578-c1e16f80-2988-11eb-990a-f94cd075ed7a.png)
