### ISSUE TITLE
Click on "no xp due no speciality" marker can open skills window instead of tutorial completed.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10989]
I think this marker should not be visible before skills button appear.
![default](https://user-images.githubusercontent.com/4980243/52062075-e0dafb80-2580-11e9-8e50-c125192de6b2.png)

**Comment by johnkslg** [comment]
Good point, yes hide that button if the tutorial hasnt happened yet.

**Comment by elfl0rd** [comment]
Also clicking in chat open this window too :D 
![20190131190532_1](https://user-images.githubusercontent.com/4980243/52067876-8e9fd780-258c-11e9-91e8-b732421d31c4.jpg)
