### ISSUE TITLE
USER ISSUE: Cannot log into any server 

### ISSUE THREAD

**Issue by keptin** [StrangeLoopGames/EcoIssues#10980]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Open in Steam
Try to Continue game on server, or log into a new server
Receiving error.

Looks like user authentication servers are down?

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User is offline</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User is offline</size>
```

**Comment by elfl0rd** [comment]
Steam auth issue, for now - it's work?

**Comment by keptin** [comment]
Yes, looks like it's working now. It may have been a server update issue.
After updating the server it worked. Still couldn't load into a few other
servers I tried, but maybe they needed to be updated too.

**Comment by johnkslg** [comment]
Fixed
