### ISSUE TITLE
"Join hosted world" button is not appear if game launched trough steam.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10988]
auth problem?

**Comment by johnkslg** [comment]
Follow up with @mirasrael and @rainfarmer if you need info on how hosted worlds works and provides special 'citizen' accounts.

**Comment by rainfarmer** [comment]
steam is not supported yet for hosted worlds, but will be soon

**Comment by elfl0rd** [comment]
It's not bad e.g. for HW owners.
