### ISSUE TITLE
previous elections link bug

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#10985]
From the main menu, previous elections are not linking correctly.

Like this:
http://localhost:3001/elections.html?election=[object%20Object]

**Comment by Tigran07** [comment]
http://prntscr.com/mgrcy8

**Comment by Tigran07** [comment]
I tried this on local ,  it worked
http://prntscr.com/mgrd80

**Comment by rainfarmer** [comment]
duplicate of this one: https://github.com/StrangeLoopGames/EcoIssues/issues/11051
