### ISSUE TITLE
0.8 Staging: XP Balancing is a bit unbalanced and unfair to Workers

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10981]
**Version:** 0.8.0.0 beta staging-4705f5ae-1

There will Probably be other(s) so making this so others can add to it.

**MINING**
Mining XP is very poor and hard to get to higher Levels I started On Server over 24 hours ago and took Mining as my **ONLY** Skill i have mined and mined as hard as i can and i just got to level 5
with a lot still to do. (as the only way to get XP is to mine which is **hard** work)
![snap4024](https://user-images.githubusercontent.com/29383891/52003222-d6a2f980-24bb-11e9-98e3-87a86461b7a2.png)
**MASONRY**
Today i took Masonry , played a couple of Hours and i'm MAX
![snap4023](https://user-images.githubusercontent.com/29383891/52003268-f0dcd780-24bb-11e9-8aae-8513784bf13e.png)
**DIGGING**
There is nothing for this as a skill, and we do **NEED** this as we have to dig out **Clay** (crafting bricks and pots etc), **Sand** (making Pitch and glass) and also **Dirt** (this being for landscaping, making dirt ramps,fertilizers etc.)

**Comment by DragonSupremacy** [comment]
For the sake of farmers and chefs in a healthy economy, I don't think removing generic calorie efficiency would be a bad thing. They already struggle with declining income as people upgrade tools and eventually reach the point where skids are available and/or pause playing around the time the meteor can be destroyed.

Instead, just allowing a more or less steady decline in calorie usage as the map matures gives much more of a steady income curve and thus allow food producers to anticipate declined demand well in advance and prepare accordingly.

**Comment by johnkslg** [comment]
@craig-jong if you have time some first-pass balancing for 8.0 would be great.  Sync up with conchita and other people playing

**Comment by WeaselDog** [comment]
This is actually backwards now. The EXP for workers is too much now that they can both craft and have additional exp gain from work. We will look into lowering exp per swing.

**Comment by WeaselDog** [comment]
Going to close for reasons above. We have a separate issue for balancing Logging & Mining exp.
