### ISSUE TITLE
0.8 Staging: Plant Names are missing in Population, makes it a bit confusing

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#10986]
**Version:** 0.8.0.0 beta staging-1785734b-2

![snap4025](https://user-images.githubusercontent.com/29383891/52025044-e4c43a80-24fa-11e9-8e8c-512e270053b3.png)

this happened a while a go so linking this one
Population Map Plant Name Missing #10055

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10055
