### ISSUE TITLE
Laws never get replaced when creating a new law for the same property / Can not replace law

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1099]
http://ecoforum.strangeloopgames.com/topic/1692/unable-to-replace-laws

**Comment by SeanAtr0n** [comment]
This should already be fixed in 5.4... are they sure the law passed?

**Comment by noblackthunder** [comment]
Yea just found out that they use an outdated version and still report bugs for that .. sorry :/
