### ISSUE TITLE
0.8 staging "Choose roles" and "Gain speciality XP" - missing icon.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10997]
![default](https://user-images.githubusercontent.com/4980243/52121514-e859dd80-2630-11e9-898e-4f725508a6d1.png)
![default](https://user-images.githubusercontent.com/4980243/52121517-ebed6480-2630-11e9-8ef6-7cd3c0654dd9.png)

**Comment by elfl0rd** [comment]
Next tutorial not have icon too.

**Comment by D3nnis3n** [comment]
Already fixed.
