### ISSUE TITLE
Birch tree has strange vertex normals

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11002]
![image](https://user-images.githubusercontent.com/431728/52079250-e2d4a700-25e0-11e9-9d8a-56be90f36050.png)

**Comment by keegan-o** [comment]
Set them to use unity generated normals instead
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/b0a25e3c-967b-41e7-a63c-342da0c286eb)
