### ISSUE TITLE
Null reference exception in AvatarEditingSafetyBubble.OnDisable()

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11007]
NullReferenceException: Object reference not set to an instance of an object
AvatarEditingSafetyBubble.OnDisable () (at Assets/Scripts/Avatar/AvatarEditingSafetyBubble.cs:38)

**Comment by SeanAtr0n** [comment]
while quitting the game? should be pretty harmless

**Comment by SlayksWood** [comment]
seems fixed
