### ISSUE TITLE
Plant already exists here

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11018]
Planted a sapling a short time ago, came back to just the trunk of it (I may have axed it or something, not sure).
Dug up block to get rid of it.
Replaced dirt.
Tilled dirt.
Tried to plant another seed:

![image](https://user-images.githubusercontent.com/431728/52130571-41a02c00-2686-11e9-9de9-6c0ab40629ba.png)

**Comment by elfl0rd** [comment]
Maybe root isse same with https://github.com/StrangeLoopGames/EcoIssues/issues/8367
(dead plant is not really removed before server restart.)

**Comment by redwyre** [comment]
Looks like it
![image](https://user-images.githubusercontent.com/431728/52132564-24ba2780-268b-11e9-9fe8-64379ecb0d7a.png)

**Comment by BlazeGuy2** [comment]
Closing as dup
