### ISSUE TITLE
Multiple Store Issues

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11010]
Issues reported by player oska#8208

- As buyer you only can buy if you already own an item of what you want to buy.
- If you edit buying list and add a new item, it says "no more wanted"
- If a product is really sold out, its not marked as "sold out"
- When listing an item in your store as something you will buy, takes a long time to update. Then after 7 minutes, says you are selling item rather than buying.

- See photos:
![image](https://user-images.githubusercontent.com/12839021/52115338-3afcb080-25c3-11e9-9a2f-ae91134eee95.png)

![image](https://user-images.githubusercontent.com/12839021/52115347-43ed8200-25c3-11e9-9da3-5721ee16ce47.png)

**Comment by seccombew** [comment]
Issues reported by player oska#8208
Additional issues:
- If you edit buying list and add a new item, it says "no more wanted"
- If a product is really sold out, its not marked as "sold old"

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/52237429-c62ebc80-28c9-11e9-9564-c0f60c6bee30.png)


the player silver had 20 logs in his hands and is able to sell 999

**Comment by johnkslg** [comment]
Fixed

**Comment by Arend90** [comment]
^^ my last issues that you can sell what ever you Number you want if you have 1 log in your hand is not fixed in last update

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/52327026-e1451d80-29ea-11e9-9610-5e15ebb2ea5c.png)
![image](https://user-images.githubusercontent.com/31536813/52327059-ffab1900-29ea-11e9-823e-1315d8cdd041.png)

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/52385531-59125700-2a82-11e9-9b7d-b4417565651d.png)

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/52385592-9545b780-2a82-11e9-861e-872d7dad9655.png)

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/52385610-b1e1ef80-2a82-11e9-8810-b01c7a3b4610.png)

**Comment by redwyre** [comment]
This is fixed in 0.8.0.1, which isn't released yet.
