### ISSUE TITLE
When mining limestone with the tier talent, there is a large delay

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11017]
I am using a stone pick to mine limestone. When I hit it, there is particle effects as if it has been mined, but the block stays solid for about a second before breaking.
When mining the ceiling the rubble starts to fall out of the block before it disappears so it seems to only be a problem with removing the block

Mining with an iron pick breaks it immediately.

**Comment by redwyre** [comment]
I'm not sure if it's related, but I'm also getting a lot of rubble falling through the ground, and sometimes seems to explode like #10706

**Comment by craig-jong** [comment]
This is due to the clientside prediction not working right with the talent. I'll look into fixing this.

**Comment by johnkslg** [comment]
Client side prediction related

**Comment by TwixterZ** [comment]
Tested this fix on 9.4 Staging 2009, while it does not happen 100% of the time I still see late break on stones at a rate of about 40%-60% of the time testing this

![mining4.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/237c688d-a74c-4e6c-9cde-a8b0173c8fa9)

**Comment by TwixterZ** [comment]
Re-upload gif from above comment
![mining4](https://user-images.githubusercontent.com/78054747/120917957-8ae46880-c6e4-11eb-8281-a0e105d835fb.gif)

**Comment by mirasrael** [comment]
@TwixterZ if you're talking about rubbles spawn - it is another issue. Fix was provided for block destroying lag. It should be now same as for simple one-hit blocks.
