### ISSUE TITLE
Chat channels don't show up on login

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11011]
![image](https://user-images.githubusercontent.com/431728/52116849-f4a85f80-265d-11e9-9e85-be31280a6579.png)

Shouldn't I be getting some offline history for channels?

Also I seem to be chatting in a random channel that I haven't used before.

**Comment by mirasrael** [comment]
@gzatravkin assigned because now you're working on chat. Can you check current state of this issue?

**Comment by gzatravkin** [comment]
Seems like it's already fixed. I got offline history and there are no strange channel on start.

Marking fixed, @SlayksWood can you check just in case?
