### ISSUE TITLE
Setting Up Camp Tutorial - Missing Arrow

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11027]
I'm quite sure several versions ago there was an arrow pointing at the starter camp in the inventory, that has long been gone but i think it could be quite useful.

**Comment by Quadbro** [comment]
we need to add extra task section for this in setting up camp tutorial, just like "find a starting camp item in backpack" + " drag in on toolbar" instead of just second one... and i don't thin that it makes sense...

**Comment by Quadbro** [comment]
closing for now, until there will not be extra info
