### ISSUE TITLE
Blocks can be placed on other existing blocks overwriting the original block

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1102]
I have  seen this happen you try to place a block in one spot but it just goes to another block space where there is already a block and overwrites it . That should not be possible

**Comment by MarjieAVolk** [comment]
We recently changed how placing blocks works a bit, with that shadow placement thing - @metachronism, were you the one who worked on that?  Do you know if that change would have fixed this issue?

**Comment by noblackthunder** [comment]
5.4 still has that issue, i have seen it on several videos from larger streamers and got confirmation from other users

**Comment by MarjieAVolk** [comment]
I was referring to upcoming 5.5 changes; but in either case, I just found a way to make this safer, which should hopefully fix this problem
