### ISSUE TITLE
Meteor crater is a tier 3 room

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11022]
![image](https://user-images.githubusercontent.com/431728/52154165-8056d600-26c8-11e9-9090-9946c13ab5eb.png)

Appears to be a destroyed building, didn't recalculate rooms after big boom?

**Comment by Conchipedia** [comment]
Sounds very similar to this issue (well it does involve Craters 😄 )
Room Detection NOT working properly after Meteor Hit #9501

**Comment by johnkslg** [comment]
Craters apply bulk-changes to the world, just need to queue room recalculation on the affected chunks afterwards.

**Comment by SlayksWood** [comment]
> is this always going to happen when meteors hit a bridge over water? it does look a bit weird to have a crater in water (just going through screenshots, and was just curious)
![snap2953](https://user-images.githubusercontent.com/45708377/67743860-02dead00-fa31-11e9-955c-2536fbdc381c.png)

**Comment by TwixterZ** [comment]
Fix tested and observed as of 0.9.5 Develop-305.

Rooms no longer function after hit by meteor and furniture inside are destroyed when hit
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9707d2a8-4914-4e90-873e-46e01f89f1f4)

bridges destroyed without leaving any floating blocks in the water.
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/3d4ad964-524d-441e-8945-a81f532f790b)
