### ISSUE TITLE
Researching sometimes is not show in skills

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11020]
(save at @mirasrael streaming server)
![20190202014122_1](https://user-images.githubusercontent.com/4980243/52153630-d22d3b00-268b-11e9-935b-e45f7f96b677.jpg)

**Comment by craig-jong** [comment]
I can't get a repro on this. Going to push this bug to 8.1 since its definitely not mission critical.

**Comment by elfl0rd** [comment]
this happens after server restart (maybe if your research get stop "missing resources")

1) before restart - all ok
![20190205014648_1](https://user-images.githubusercontent.com/4980243/52242610-35b3a480-28e8-11e9-9bf8-b585953bb86c.jpg)
![20190205014353_1](https://user-images.githubusercontent.com/4980243/52242611-35b3a480-28e8-11e9-8486-5f8617a23947.jpg)

2) after restart
![20190205014754_1](https://user-images.githubusercontent.com/4980243/52242620-39dfc200-28e8-11e9-976f-c7a05354fcc6.jpg)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2830085/output_log.txt)
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2830086/Storage.zip)

**Comment by johnkslg** [comment]
Good find and isolation to after-restart @elfl0rd

**Comment by elfl0rd** [comment]
Also additional problem, related to this - CANCELED research show as active (in this interface) but not display tooltip.
