### ISSUE TITLE
USER ISSUE: Disappearing trees issue still (SP - Bleeding Edge)

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#11024]
**Version:** 0.8.0.0 beta staging-1785734b-2

**Steps to Reproduce:**
Cut down a tree...after about a seemingly random amount of swings, tree disappears.  Only logging out and back in will respawn cut tree.

**Expected behavior:**
Cut tree still there after being cut down

**Actual behavior:**
Fallen tree dissappears (still).

**Do you have mods installed? Does issue happen when no mods are installed?:**
Fallen tree dissappears (still).

**Comment by hotowy** [comment]
In my case, the tree disappears when you try to collect chopped slices instantly. (Like holding left mouse click and fast tapping 'E' to collect.)

**Comment by SlayksWood** [comment]
merged with #11487
