### ISSUE TITLE
Can't delete bank accounts.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11030]
When hovering over a SELF-CREATED bank account no "x" appears anywhere - can't delete bank accounts.

**Comment by elfl0rd** [comment]
See some questions about it from staging players.
![default](https://user-images.githubusercontent.com/4980243/52229456-055b0e80-28c6-11e9-92f5-105e2b6b6ec1.png)

**Comment by johnkslg** [comment]
Fixed!
