### ISSUE TITLE
Registrar delete icon offset

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11031]
![registrar](https://user-images.githubusercontent.com/25908592/52163366-33cbc480-26e1-11e9-8de9-6b8aa0b2c614.png)

**Comment by seccombew** [comment]
@D3nnis3n are you talking about the X in the corner? 
![image](https://user-images.githubusercontent.com/12839021/52512163-4a2dc080-2bb8-11e9-804e-b0bd898f3d4c.png)

**Comment by D3nnis3n** [comment]
Yes.

Am Sa., 9. Feb. 2019, 00:43 hat Will <notifications@github.com> geschrieben:

**Comment by redwyre** [comment]
Is this still relevant @serpopov ?

**Comment by SlayksWood** [comment]
Still an issue with new UI:
![image](https://user-images.githubusercontent.com/45708377/72144599-c2dd6400-33a9-11ea-881b-f123b923e947.png)

**Comment by johnkslg** [comment]
2 second fix, keeping
