### ISSUE TITLE
Room test not working correctly?

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11038]
![image](https://user-images.githubusercontent.com/431728/52163545-3d7c1900-272f-11e9-86ed-9c94798144f0.png)

The position indicated is outside the room, so...
![image](https://user-images.githubusercontent.com/431728/52163554-5e446e80-272f-11e9-8b68-b966e70cfcb0.png)

There _is_ a hole in the floor that may be stopping it from being a room, though I'm sure it was fine before
![image](https://user-images.githubusercontent.com/431728/52163567-7fa55a80-272f-11e9-8ad0-47c53bb09304.png)

**Comment by redwyre** [comment]
Looks like the doorway being 3 blocks high was breaking it

**Comment by SlayksWood** [comment]
8.1.4 /testroom works. Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56897204-904b3f80-6a96-11e9-856e-e3e24a4fa4b6.png)
