### ISSUE TITLE
Graphical artefacting in the ocean

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11032]
![image](https://user-images.githubusercontent.com/431728/52163367-ae6e0180-272c-11e9-83fa-4e89e7e913b9.png)

**Comment by metachronism** [comment]
need repro steps?

**Comment by SeanAtr0n** [comment]
hold a torch, ride in a steam truck

**Comment by Conchipedia** [comment]
this is also happening on greenleaf server near my pyramid, not sure if its because of Braziers inside Pyramid, i have not torch or vehicles , maybe also campsite lights might be effecting light if place closed to water?

**Comment by Conchipedia** [comment]
rechecked this on latest version
![snap4081](https://user-images.githubusercontent.com/29383891/52349847-43b81100-2a1f-11e9-8ea7-d28d3977ca15.png)
![snap4079](https://user-images.githubusercontent.com/29383891/52349854-49155b80-2a1f-11e9-9f46-5d7098f0cb39.png)
![snap4080](https://user-images.githubusercontent.com/29383891/52349855-49155b80-2a1f-11e9-8cc2-855b2a09c730.png)

**Comment by D3nnis3n** [comment]
I haven't seen this recently and i can't even remember to have seen that two years ago either.

**Comment by ptitducanh** [comment]
I might be fixed at some point. 
I can't recreate that weird light.
