### ISSUE TITLE
Allocate and Tax is no longer possible in laws

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11034]
![allocate](https://user-images.githubusercontent.com/25908592/52163467-b43ef500-26e2-11e9-942e-1ad89f31a1e9.png)

**Comment by Alteraner** [comment]
option for tax and as well allocate is missing. since the update we cannot create any law for taxes. further laws for allocate some currency while players are login the first time to the server are as well not working any more.

**Comment by johnkslg** [comment]
Fixed!

**Comment by Deantwo** [comment]
My hero!
