### ISSUE TITLE
Transfer UI lags with many bank accounts

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11036]
Having 300 players the UI for transferring bank accounts is severely lagging, not coming up after even 5 - 10 seconds, misclicks causing the need to open it again. A search feature and improvement in performance would be good.

**Comment by mirasrael** [comment]
@D3nnis3n seems like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18573 ?

**Comment by D3nnis3n** [comment]
Yes, together with this: https://github.com/StrangeLoopGames/EcoIssues/issues/14356
