### ISSUE TITLE
[8.0.0 bleeding edge] World Leader does not get access to treasury account or demographic

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11048]
![image](https://user-images.githubusercontent.com/47274045/52169467-38bc6280-2739-11e9-865f-8077eec12537.png)

If you have been elected as World Leader or set yourself with admin command to World Leader, you do not get access to the Tresury account. It seams the demographic is although not set with the current world leader. I assume the tresury account is set to the demographic world leader but because you are not been set to the world leader with an election, you do not get access to it.

**Comment by johnkslg** [comment]
Alex there's a PR in for this, just need you to help with migration of existing 8.0 worlds, ignoring titles in old lists.
