### ISSUE TITLE
0.8 Elevator partially broken.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11049]
**Version:** 0.8.0.0 beta
![20190203020621_1](https://user-images.githubusercontent.com/4980243/52170267-6664d400-2758-11e9-9a12-c50d57763f83.jpg)
autostop if cannot move - broken.

Also periodically elevator totally stopped working. (you need pickup it and place again for work).
![20190203165736_1](https://user-images.githubusercontent.com/4980243/52177632-dd3fb280-27d4-11e9-8eee-39515b3bb34c.jpg)

also elevator ignores call post in any case.
https://github.com/StrangeLoopGames/EcoIssues/issues/11042

**Comment by elfl0rd** [comment]
Also periodically elevator totally stopped working.
![20190203165736_1](https://user-images.githubusercontent.com/4980243/52177632-dd3fb280-27d4-11e9-8eee-39515b3bb34c.jpg)

**Comment by metachronism** [comment]
@Quadbro recent changes may have broken?

**Comment by Quadbro** [comment]
@metachronism i just changed a render, no logic changes

**Comment by Spydarlee** [comment]
Hey @elfl0rd - this all seems to be working as expected for me on latest master build. Do you have any additional repro steps?

I've been using the _/testelevator_ admin command - does the elevator that creates work correctly for you?

**Comment by Spydarlee** [comment]
Hmm, just tried on Steam (Beta 8.0.0) and it works for fine for me on there as well 🤔

Not sure what else to try, I'm afraid, @elfl0rd!

**Comment by Spydarlee** [comment]
Hmm, just tried on Steam (Beta 8.0.0) and it works for fine for me on there as well 🤔

Could you send me a copy of a save where this happens for you, please, @elfl0rd?

**Comment by elfl0rd** [comment]
yep, and can show it on my server, you have discord? Touch me (GDragon#2299)

**Comment by elfl0rd** [comment]
[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2841724/Game.zip)
my save (theres only one elevator on world)
