### ISSUE TITLE
[8.0.0 bleeding edge]  Wooden Elevator Call Post

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#11042]
![grafik](https://user-images.githubusercontent.com/37456949/52165145-23294780-26fd-11e9-9666-7c0a10aec36c.png)

The Call Post dont find the Elevetor in the Block next to it

**Comment by Quadbro** [comment]
Seems like all is ok in 8.0
![ezgif-4-dcbd506e1765](https://user-images.githubusercontent.com/6802030/52325724-ad80ec80-2a18-11e9-8588-d8c4fb42c004.gif)

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/52336627-727db980-2a16-11e9-9871-d37bbc8f3b09.png)
