### ISSUE TITLE
[8.0.0 bleeding edge] World is too bright

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#11044]
It seems most of the world is far too bright. Shadows and godrays are still present, but overall lighting is way too bright, even when brightness setting is set to its lowest.

**Comment by redwyre** [comment]
Can you add a screenshot? Also try with GI disabled

**Comment by elfl0rd** [comment]
yes, i agree, daily lighting is really bright.

**Comment by Mosseman** [comment]
GI is already disabled.

Screenshot as an example: https://steamuserimages-a.akamaihd.net/ugc/951851312421068033/E4144079E55DC6FE826A3ABE61071AD2435DC120/

**Comment by metachronism** [comment]
intended, but I'll let keegan close

**Comment by beastyn** [comment]
Have new lightning issues for 0.9
