### ISSUE TITLE
Need a way to transfer ownership of a plot

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11047]
When a player has been offline for a while, the only option you have is to unclaim their land and take all their stuff. It would be good to have the option of moving their stuff somewhere else.

**Comment by Alteraner** [comment]
You can use the command: /addtodeed

**Comment by mirasrael** [comment]
You can use command /owner [playerName]

**Comment by Deantwo** [comment]
In v0.9.0.0 we will hopefully be able to make "Seize all property" laws. An admin command to seize the property you are standing on seems like a nice addition to that.

**Comment by D3nnis3n** [comment]
Implemented in 9.0.
