### ISSUE TITLE
USER ISSUE: Wheelbarrow Turning

### ISSUE THREAD

**Issue by Ratbouy** [StrangeLoopGames/EcoIssues#11053]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
1. Place a wheelbarrow
2. Try to move
3. Fail to go where you intended to go
4. Acheive permanently inverted controls

**Expected behavior:**
It should move and function like a wheelbarrow is supposed to

**Actual behavior:**
Instead it has no normal ability to go backwards and ends up getting its controls permanently inverted, even after picking up and placing it again

**Do you have mods installed? Does issue happen when no mods are installed?:**
We have no mods installed. Instead it has no normal ability to go backwards and ends up getting its controls permanently inverted, even after picking up and placing it again

**Comment by SeanAtr0n** [comment]
fixed in svn, you can also now go up some blocks
![wheelbarrowop](https://user-images.githubusercontent.com/774628/52508895-fcf72200-2baa-11e9-8d9e-53ae8b0bad88.gif)
