### ISSUE TITLE
[8.0.0 bleeding edge] Сommand duplication in localized help

### ISSUE THREAD

**Issue by WindDash** [StrangeLoopGames/EcoIssues#11056]
![image](https://user-images.githubusercontent.com/17976842/52176104-1c630900-27bf-11e9-8830-360f88c63baa.png)

**Comment by Spydarlee** [comment]
Which commands are these in English, do you know @WindDash? Having a bit of trouble tracking them down without knowing their English translations! 😅

**Comment by elfl0rd** [comment]
@Spydarlee all localized commands duplicated (for clarify)
on screenshot
/allworldobject
/allterrain
/applants
/allconstructed

**Comment by Spydarlee** [comment]
Ah perfect, thank you!

**Comment by Spydarlee** [comment]
This seems to be working as expected on master, are you still seeing this issue on latest@elfl0rd?

![image](https://user-images.githubusercontent.com/553695/52650237-c2aabf00-2ee1-11e9-8b10-e3acaae9dcbc.png)

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/52653606-55a72180-2f01-11e9-9e47-805803fdd08e.png)
