### ISSUE TITLE
Water makes water flow noise even after you removed the water

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1105]
http://ecoforum.strangeloopgames.com/topic/1704/waterfall-sound-issue

**Comment by RednoWCirabrab** [comment]
Anyone joining my server right now, no matter where they are, can hear the water flow noise

**Comment by RednoWCirabrab** [comment]
A possible explaination:

http://ecoforum.strangeloopgames.com/topic/1704/waterfall-sound-issue/9

**Comment by metachronism** [comment]
its tied to world layer sim which is on a 10 minute tick

**Comment by craig-jong** [comment]
It's not just that; for some reason layers aren't always being sent immediately causing issues with the water direction code on the client side. You'll see a bunch of layer get exceptions sometimes in editor.

**Comment by Nanders** [comment]
I would love to help find a better audio solution than worldlayers, but it probably will be a big task.

**Comment by knexer** [comment]
Presently there are no water sounds at all as per https://github.com/StrangeLoopGames/EcoIssues/issues/3246.  Resolving this since (hopefully) the old setup won't be making a return.
