### ISSUE TITLE
Improvements for transactoins history

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11059]
1. Make text not going into another field
2. Make the icon at buy and sell entries hoverable so you can see what item it is - at least i couldnt tell which item this little icon is.
![bankaccount](https://user-images.githubusercontent.com/25908592/52177368-19b4e380-27c0-11e9-8567-74cdc856a10a.png)

**Comment by johnkslg** [comment]
We need a way to have tables in tooltips easily.

**Comment by SlayksWood** [comment]
from #12855
> ![image](https://user-images.githubusercontent.com/45708377/62617727-2a831500-b91b-11e9-9323-5d680d6eb362.png)
> Also transaction UI has bad tooltip:
> ![image](https://user-images.githubusercontent.com/45708377/62617758-42f32f80-b91b-11e9-8849-49fcdfa9760b.png)
> 
> 1. It should be more width.
> 2. It repeats all from  transaction UI, nothing new.
>    May we need add button to display next 20(or more) transactions in UI? and delete tooltip at all.
> 3. First number (may be because it more 10000) absents:
>    ![image](https://user-images.githubusercontent.com/45708377/62618330-a3cf3780-b91c-11e9-9153-a084cd9860c9.png)
> 
> You can change the display order: first last

**Comment by SlayksWood** [comment]
From #13722
> it is annoying to scroll data in tooltip.
> And wtf? we already have window for this data, why we need cut?
> ![изображение](https://user-images.githubusercontent.com/4980243/68958631-87754d80-07dd-11ea-9993-5f3eb8e51dbf.png)
will be nice to see first 50 and button "show more" which add you another 50, without any tooltip.

**Comment by SlayksWood** [comment]
#16616
> ![image](https://user-images.githubusercontent.com/3536496/84309357-d6d1f100-ab14-11ea-9dab-03b5ca5e7824.png)
> Need to truncate probably
> Also, display transaction in reverse time order instead.

**Comment by elfl0rd** [comment]
Truncated strings loose icons.
I think icons should be in any case.
![изображение](https://user-images.githubusercontent.com/4980243/85209271-2ac3ad80-b33f-11ea-8f45-2e042a158732.png)

**Comment by SlayksWood** [comment]
- [ ] 1. Still overlap:
![image](https://user-images.githubusercontent.com/45708377/85696858-f86cd400-b6e1-11ea-833a-74b72277019e.png)

- [ ] 2. It's said that display Last 20, but seems it's displayed near 100
![image](https://user-images.githubusercontent.com/45708377/85697217-42ee5080-b6e2-11ea-8660-866a60f50d4f.png)

- [ ] I can't see more transactions:
![image](https://user-images.githubusercontent.com/45708377/85705570-01fa3a00-b6ea-11ea-9169-5bd8056c1f59.png)

**Comment by beastyn** [comment]
parted here #16940

**Comment by beastyn** [comment]
Will check with the new PR just in case
