### ISSUE TITLE
0.8 impossible to see gold ore from top and bottom side.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11057]
![20190203150638_1](https://user-images.githubusercontent.com/4980243/52176593-d65d7380-27c5-11e9-90a2-31309594212e.jpg)
![20190203150704_1](https://user-images.githubusercontent.com/4980243/52176592-d65d7380-27c5-11e9-93ac-4651a7525f4c.jpg)
Also gold ore hard to see from bottom side.
![20190203151119_1](https://user-images.githubusercontent.com/4980243/52176599-03118b00-27c6-11e9-90a5-f87a399df511.jpg)
![20190203151127_1](https://user-images.githubusercontent.com/4980243/52176600-03118b00-27c6-11e9-98b2-bf1a2b414e2b.jpg)

**Comment by johnkslg** [comment]
Intended?

**Comment by elfl0rd** [comment]
It's really painfull.
If grafics like this intended, please add something like geologist profession.

**Comment by keegan-o** [comment]
Made it more obvious for now with veins on the top texture and a very slight yellow tint overall, in 8.0 and 8.1.
