### ISSUE TITLE
0.8 as i see fix "vechicle fall from ground" broken.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11050]
![20190203023410_1](https://user-images.githubusercontent.com/4980243/52170486-5222d600-275c-11e9-95ef-fd1e6046c58e.jpg)
For now, carts\vechicles loads before ground, and fall trough it.

**Comment by SeanAtr0n** [comment]
i put in a few more fixes for this already but it can still rarely happen
