### ISSUE TITLE
[0.8.1.4] Soil sampler temperature readout broken

### ISSUE THREAD

**Issue by andrewsg** [StrangeLoopGames/EcoIssues#11063]
In 0.8 bleeding edge, my soil analyzer reports that every square of terrain is 0.6c. This is definitely a soil analyzer problem and not a terrain problem, as the soil analyzer also says that warm-weather plants are thriving in their respective biomes despite the temperature reading 0.6c. (overnight this changed to 0.7c everywhere, but it still doesn't vary between plots).

**Comment by Deantwo** [comment]
Can you please rename the issue to "Soil Sampler" so it is easier to find?

**Comment by andrewsg** [comment]
Done

**Comment by SlayksWood** [comment]
I assume that the temperature value that is shown is 0 ... 1.It is broken translation to degrees Celsius
![image](https://user-images.githubusercontent.com/45708377/56900583-d60c0600-6a9e-11e9-9473-45a6d4e713f9.png)

**Comment by SlayksWood** [comment]
dup #4410
