### ISSUE TITLE
[8.0 Bleeding Edge] Soil moisture is not being used

### ISSUE THREAD

**Issue by andrewsg** [StrangeLoopGames/EcoIssues#11064]
From this collection of screenshots it looks like the soil moisture variable isn't being used to determine crop success; instead, rainfall is used exclusively. https://photos.app.goo.gl/B15odRTUjHYXWKjL6

**Comment by craig-jong** [comment]
This is true, though growth still comes from soil moisture as a nutrient layer. This was done to allow for consistent spawning with the new world gen.

Farming in general needs a change to account for this, but its not something that will be in 8.1.

**Comment by Spoffy** [comment]
In the meantime - could the soil analyser be updated to convey this? It's far from obvious in the existing system. Perhaps this issue could also be reassigned or reopened, as it remains a problem, even if not fixed in 8.1?
