### ISSUE TITLE
USER ISSUE: see thru world

### ISSUE THREAD

**Issue by Coolmira12** [StrangeLoopGames/EcoIssues#11067]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
1.get dirt
2.place dirt

**Expected behavior:**
not to see thru the world

**Actual behavior:**
see thru wold and blind and invisible dirt

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods and yes

**Comment by beastyn** [comment]
can't repro this with last release.
