### ISSUE TITLE
[8.0 Bleeding Edge] redifine District forget precious districts

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11066]
![image](https://user-images.githubusercontent.com/47274045/52182141-48e84680-27fa-11e9-955a-843eaa751fe4.png)

If i would like to setup a new law to redifine districts, all previouse districts are gone. i have to setup all districts new.
This impacts a lot, because all other laws refering to older districts are not working any more and server is not able to start. while starting it stops and can only be fixed by deleting law file in game.eco file.

**Comment by Alteraner** [comment]
@metachronism, why it was downgraded? This is critical from my point of view. If you run a server with different citys, its a nightmare to redisign all districts. furhter the server is crashing if a law is refering to a disctrict not existing any more.
In my point of view, this bug is a showstopper for 8.0.

**Comment by johnkslg** [comment]
This is high priority as it basically breaks districts.

**Comment by SeanAtr0n** [comment]
not a task we can fix in a few hours

**Comment by SeanAtr0n** [comment]
not really sure what changed here... @rainfarmer were there any district changes recently?

**Comment by SeanAtr0n** [comment]
I misread the bug... probably something simple that could be fixed easily by whoever touched laws last. Looks like @mirasrael might also know what changed

**Comment by mirasrael** [comment]
Did it work for 7.8? Problem was on web part and there wasn't any code related to loading old districts.

**Comment by Alteraner** [comment]
In 7.8 it worked well. On our Server we create and delete at any time districts for city's. Time by time new cities are born or old are dying. Till now we didn't had this issue.

**Comment by rainfarmer** [comment]
merged https://github.com/StrangeLoopGames/Eco/pull/3961#event-2122036732

**Comment by Alteraner** [comment]
Hello, in actual bleding edge it is still not fixed. Please can you check again?

**Comment by elfl0rd** [comment]
agree

**Comment by elfl0rd** [comment]
Okay, found a workaround, @Alteraner - try to clean your browser cache.

**Comment by rainfarmer** [comment]
@Alteraner can you confirm clearing cache or maybe f5 refresh, fixes the issue now?

**Comment by mirasrael** [comment]
F5 will not help, because if you already started law then it stores variables in application local storage (in user's browser).
It seems like this in Google Chrome, you can just remove those 2 variables:
![image](https://user-images.githubusercontent.com/475445/52767816-a2434780-303c-11e9-8822-939f4431221c.png)

**Comment by Alteraner** [comment]
Hello, i can canfirm the issue is solved. I tried it several times and now all previously defined districts are still visible and keep stored.
So issue can be closed. Thanks for the fix.

**Comment by rainfarmer** [comment]
yay
