### ISSUE TITLE
0.8 face remover remove visible part of granite

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11065]
![20190203205950_1](https://user-images.githubusercontent.com/4980243/52180442-083afe00-27f7-11e9-9872-1fdb88f9f000.jpg)
![20190203210002_1](https://user-images.githubusercontent.com/4980243/52180444-0a04c180-27f7-11e9-8a34-8b8384713734.jpg)

**Comment by metachronism** [comment]
dupe of old builder bug

**Comment by elfl0rd** [comment]
Not mentioned in old bug + not happens with natural blocks before.

**Comment by elfl0rd** [comment]
![20190214230232_1](https://user-images.githubusercontent.com/4980243/52814420-2e8d5300-30ad-11e9-9aad-8c3fb783220e.jpg)

![20190214230229_1](https://user-images.githubusercontent.com/4980243/52814426-33520700-30ad-11e9-89da-e077ea886398.jpg)
