### ISSUE TITLE
Contracts don't reward funds after completion

### ISSUE THREAD

**Issue by iForby** [StrangeLoopGames/EcoIssues#11079]
Hope this helps, Developers:

When you create a contract and reward funds, the funds are never given to the contractor once they complete the job.

Find me on Discord as: Drewtiful or Forby if you need any other information.

**Comment by D3nnis3n** [comment]
Could not reproduce this on my build. Edited your post to only include new issues. We'll take a look.

**Comment by iForby** [comment]
Can confirm contracts are still doing this on our server. Had to remove all contracts.

**Comment by johnkslg** [comment]
@Quadbro can follow up with this user?
