### ISSUE TITLE
[8.0 Staging] - ChatCommandAttribute

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#11073]
Exception:
> `Failed to create ChatCommandHandler: DailyCommands because: Method not found: 'Void Eco.Gameplay.Systems.Chat.ChatCommandAttribute..ctor(System.String, System.String, Eco.Gameplay.Systems.Chat.ChatAuthorizationLevel, Boolean)'. . It likely has no default constructor.`

The Code was
> `[ChatCommand ( "daily", "Get a daily reward of tokens" )]`

Also tried
> `[ChatCommand("Get a free gift, once daily!")]`

And
> `[ChatCommand ( command: "daily", helpText: "Get a daily reward of tokens", level: ChatAuthorizationLevel.User, useInTestPlugin: false )]`

We tested this on 8.0 Staging, I can provide build number if really needed.

Due to this issue no Modkit commands can be added to the game, in short no mods.

**Comment by johnkslg** [comment]
Look at other chat commands in mods to see the syntax:
![image](https://user-images.githubusercontent.com/3536496/52222238-044bc200-2871-11e9-985b-173bd0b321d8.png)

**Comment by johnkslg** [comment]
you can omit most of those too

**Comment by metachronism** [comment]
this is annoying for modders, they have to replace all their attributes due to the CI commands

**Comment by ClayC90** [comment]
Well, I copied and pasted a chat attribute that there in the server solution and replaced just a couple of values, but the error still came up @johnkslg

**Comment by johnkslg** [comment]
Confused on this bug, I just tried this syntax and it compiled fine:
![image](https://user-images.githubusercontent.com/3536496/52238078-26593a80-2899-11e9-9407-c1f16dbf2e4e.png)
Cannot repro in master

**Comment by ClayC90** [comment]
Tested in 0.8.0.3 and this is still not fixed.

**Comment by redwyre** [comment]
@ClayC90 Can you explain how you tried to use the attribute?

**Comment by ClayC90** [comment]
verified to be working in 8.0.7
