### ISSUE TITLE
Stuck logging into server

### ISSUE THREAD

**Issue by TopSecretPorkChop** [StrangeLoopGames/EcoIssues#1107]
After experiencing symptoms similar to [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjFgpL9m5vSAhXG6oMKHTIAAn8QFgghMAE&url=http%3A%2F%2Fecoforum.strangeloopgames.com%2Ftopic%2F1506%2Fclient-stuck-on-loading-world-214748364852&usg=AFQjCNEhmj3gZ8YUlQsq68CwySfuFGuImA) (i.e. laggy fps, then black screen, then kicked to server lobby), i'm now unable to log into the server i was on (Chiggaland).  When I select the server and click 'connect', The game begins to load data but sticks on 'Loading Objects 100%'.  
I am able to log into other servers just fine.

It seems the issue mentioned in the post above was not quite fixed by 0.5.4.

**Comment by noblackthunder** [comment]
fixed in 5.5 . Its an invalid position bug. This can be resolved by an admin.

by downloading and applying this command plugin to the server http://ecoforum.strangeloopgames.com/topic/1563/100-object-loading-bug-workaround

and then having an admin using the /tpo UserNameIsCaSeSensitive command
