### ISSUE TITLE
[8.0 Bleeding Edge] No method for removing Papaya or Pineapple Trees

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#11077]
There is no way to remove Papaya or Pineapple trees. Axe, scythe, hammer, and pickaxe all do not work to remove them.,

**Comment by craig-jong** [comment]
I'm going to call pineapple good: similar to huckleberries you can dig under them to remove them.
![image](https://user-images.githubusercontent.com/18184943/52239495-788f6100-2883-11e9-8b2b-a757761ec006.png)

We'll update papaya to work in a similar way.

**Comment by keegan-o** [comment]
Fixed in master (8.1) and release (8.0)
