### ISSUE TITLE
USER ISSUE: The minimap is not here

### ISSUE THREAD

**Issue by Sigvi05** [StrangeLoopGames/EcoIssues#11078]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
1. "M"

Thats all. When i press m the map does not show up

**Expected behavior:**
Shoving the map

**Actual behavior:**
Showing map settings

**Do you have mods installed? Does issue happen when no mods are installed?:**
Showing map settings

**Comment by D3nnis3n** [comment]
Cannot reproduce, any additional info?

**Comment by D3nnis3n** [comment]
Closing because happening on a old version and no answer for information request in the last 14 days. Reopen if it reoccurs.
