### ISSUE TITLE
[8.0 Bleeding Edge] Redwood tree stumps invisible after chopping it.

### ISSUE THREAD

**Issue by theDeus** [StrangeLoopGames/EcoIssues#11076]
Started an 8.0 Bleeding Edge server. After chopping a giant redwood fully (tree + stump), the stump seems to still invisibly exist for collision purposes.
![20190204090015_1](https://user-images.githubusercontent.com/1639160/52223948-acef2700-285b-11e9-821f-8b8b40ee8dad.jpg)

**Comment by donald12999** [comment]
Server restart doesnt fix it

**Comment by zytukin** [comment]
A kinda solution.

/give devtool
Use the tool on the invisible stump to delete it.

**Comment by metachronism** [comment]
fixed svn
