### ISSUE TITLE
Campsite should not have credit tab

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11088]
![image](https://user-images.githubusercontent.com/3536496/52283446-7800d400-2930-11e9-8424-5b77345cf7a9.png)

**Comment by elfl0rd** [comment]
Why? it's crafting table, e.g. for workbench and campfire...

**Comment by craig-jong** [comment]
Yea, it has one because its a crafting table. Even though it only has a few recipes, it theoretically could have use for a credit tab.

**Comment by johnkslg** [comment]
Hmmmm I suppose.  Its a bit confusing for newbies.
