### ISSUE TITLE
0.8 Bank has no collision detection

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11081]
**Version:** 0.8.0.0 beta staging-1785734b-2

![snap4070](https://user-images.githubusercontent.com/29383891/52255504-ad92c680-290a-11e9-8fab-584cdd95e428.png)

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10544 ¯\_(ツ)_/¯

**Comment by beastyn** [comment]
can't repo in 0.8.1.4 Seems to be fixed.
