### ISSUE TITLE
Cant connect to Server - Loading Map problem

### ISSUE THREAD

**Issue by F3UR10** [StrangeLoopGames/EcoIssues#1108]
Hey guys,

some players on our server have problems joining the server.
Always same way: 
Click connect on server -> Loading Mods & Object okay -> Loading world then interupt at different progress % and thats it.

Happens to new players an also people which have played already on the server.
Some players like me didnt had this problem.

Game Version: 0.5.4

**Comment by metachronism** [comment]
fixed
