### ISSUE TITLE
[8.0 Bleeding Edge] Mining Sweeping Hands Talent will continue to try to pull even if you have reached holding capacity

### ISSUE THREAD

**Issue by theDeus** [StrangeLoopGames/EcoIssues#11080]
When attempting to gather rock chunks after breaking several at a time, the Sweeping Hands talent will attempt to pull all available chunks. However, after breaking 20 rocks, this spammed my screen with "Not enough room in inventory" when I hit 20 chunks on hand. 

Not sure if this is a bug or intentional due to multi-threading stuff, but wanted to call it out in case it is a bug.

![20190204183834_1](https://user-images.githubusercontent.com/1639160/52250319-26166a80-28ac-11e9-9716-eacb66730e00.jpg)

**Comment by theDeus** [comment]
Screenshot doesnt really showcase how crazy the spam can get. 

Also, not sure if this is possible, but it would be a nice to combine all these into 1 message, "You received X Stone", rather than "You received 1 Stone" X times.

**Comment by WeaselDog** [comment]
still a big problem. it makes chatting impossible while mining

**Comment by mirasrael** [comment]
Fixed in 8.1.
