### ISSUE TITLE
USER ISSUE: Password not supported

### ISSUE THREAD

**Issue by SickRed** [StrangeLoopGames/EcoIssues#11092]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Change Password to +0%^Z*2A/Tv2yUWS3>7>6m&B3-hFhVBG and try to login with it to the game

**Expected behavior:**
Login to the game

**Actual behavior:**
I can login with it on the website https://ecoauth.strangeloopgames.com but it's not working for ingame login

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

It's working with a more simple password

**Comment by D3nnis3n** [comment]
> User could log into his account on the website fine.
> 
> User couldn't log into the game ("Invalid username or password" error) until he changed his password to one with non-special characters (in this case, his previous password had a "%" and a "-").

**Comment by D3nnis3n** [comment]
% and "-" is working in my 16 digit password, so it's not these signs.
