### ISSUE TITLE
Logging Talent "Cleanup Crew" broken

### ISSUE THREAD

**Issue by Natotariq** [StrangeLoopGames/EcoIssues#11093]
The level 6 talent in the Logging Tree "Cleanup Crew" states that 'Destroying debris no longer costs additional calories'. However, It does the opposite. 
With an Iron Axe: 
Level 1 Logging, removing debris costs 14.57 calories.
Level 7 Logging, no talents selected removing debris costs 6.25 calories.
Level 7 Logging, with Cleanup Crew Talent, removing debris costs 18.75 Calories.

This is on 0.8.0.0 Bleeding Edge Staging

**Comment by craig-jong** [comment]
I fixed this in a previous version. Seems fine in master.

**Comment by SlayksWood** [comment]
8.2.0 staging-6
With an Modern Axe:
Level 1 Logging, removing debris costs 24 calories.
Level 7 Logging, no talents selected removing debris costs 15 calories.
Level 7 Logging, with Cleanup Crew Talent, removing debris costs 5 Calories.
