### ISSUE TITLE
USER ISSUE: Connection time out !  Connexion échouée !

### ISSUE THREAD

**Issue by Cl0ne1913** [StrangeLoopGames/EcoIssues#11095]
**Version:** 0.7.8.9 beta

**Steps to Reproduce:**
Can not resume a game in court!
A bug with the shovel just before this game or this one teleport in the air to fall back and an ejection of the players at the other end of the map

**Expected behavior:**

**Actual behavior:**
Failed to connect Connetion timed out

**Do you have mods installed? Does issue happen when no mods are installed?: no
Error:
Failed to connect Connetion timed out

**Comment by SlayksWood** [comment]
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
