### ISSUE TITLE
Player stuck in redwood tree.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11097]
https://cdn.discordapp.com/attachments/537354889169338368/542495516127264828/382310_20190205190242_1.png
User stuck in redwood tree.
User had to go into third person mode and chop tree in just the right angle an then tree disappeared.

**Comment by quantumdotdot** [comment]
(Feel free to ask me any follow-up questions you need here btw)

**Comment by redwyre** [comment]
This looks like it was because of old redwoods growing when they shouldn't have, which has since been fixed.
