### ISSUE TITLE
[8.0 Bleeding Edge] Iron ore not spawning reliably on map creation

### ISSUE THREAD

**Issue by andrewsg** [StrangeLoopGames/EcoIssues#11091]
Multiple servers such as GreenLeaf (point of contact: Arend#8549) and Planet of Agartha (Forby#9237) are reporting a lack of iron ore on their servers to such a point that progression is impossible. In GreenLeaf, players including the admin using admin tools searched for days and turned over dozens of sandstone deposits in the desert and grassland to find no substantial veins.

**Comment by elfl0rd** [comment]
Without saves it is difficult to say something specific. Can you provide saves?

**Comment by Phlo123** [comment]
GreenLeaf Save.
https://drive.google.com/open?id=1n0uz2uFkXf8mEzttME2VQLAUN4lo4m8o

**Comment by Deantwo** [comment]
No one seem to have mentioned this in the issue here, so just to clarify for others reading this.
As far as I have been told this is mainly an issue for worlds of the size 140x140. Somehow **Iron Ore** is very rare on huge worlds.

**Comment by xtreampb** [comment]
does this issue also affect copper and gold ore?

**Comment by DragonSupremacy** [comment]
Pitching in here as I've learned from previous worlds where adding mods would affect the balance of certain ores, to **always** tweak worldgen **prior** to generating a world. From what I understand, by default iron ore only has a 10% chance to appear in sandstone, and primarily in deserts at that.

I tweaked the worldgen to have a ~25% chance of having iron ore, and as expected iron ore is fairly plentiful regardless of where I dig into the sandstone, despite it being a 280x280 world. Although I haven't looked extensively for coal, copper ore or gold ore yet, I don't expect them to be too rare. More than anything it's "just" a matter of closing the distance to get to the respective biome.

Perhaps a ~20-25% chance of ores to appear across the board by default would help a lot of newly generated server worlds out?

**Comment by andrewsg** [comment]
The % chance does seem to be relevant, but that's strange, as the problem as observed by the original reporter wasn't a matter of half or one third of the expected value but nearly zero.

**Comment by DragonSupremacy** [comment]
Yes, quite. In addition, NumRiversRange does nothing – At most I’ve ever gotten 2 rivers to generate on the map me and one of my staff members settled for. All the others only generated with just a single one, despite the setting to generate anywhere from 10 to 20 (as the world is roughly quadruple from a 200x200 world)

**Comment by elfl0rd** [comment]
@DragonSupremacy can you start new issue about rivers generation?

**Comment by Deantwo** [comment]
So just to be sure, this was not fixed for existing worlds generated with v0.8.0.0, right? Got a solution for that other than re-generate?

**Comment by D3nnis3n** [comment]
Fixed for NEW worlds.

**Comment by Nuke21** [comment]
This game is shittier with every patch. I regret buying this trash.
