### ISSUE TITLE
players and vechicles often become invisible and intangible

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11108]
But his inventory still available trough linking.
https://github.com/StrangeLoopGames/EcoIssues/issues/10952
Just look.
![unknown](https://user-images.githubusercontent.com/4980243/52073448-9cf3f080-2598-11e9-8bf4-29e8fb127004.png)
![20190131202823_1](https://user-images.githubusercontent.com/4980243/52073449-9cf3f080-2598-11e9-8c2c-4f419b6e76b2.jpg)

**Comment by johnkslg** [comment]
Need fix today or hotfix asap

**Comment by WeaselDog** [comment]
This happened to me on a Small Cart when it was on top of a stockpile and then the stockpile was filled. I ended up finding the cart underground below the stockpile. I was able to dig it out.

**Comment by SeanAtr0n** [comment]
silently fixed by eric

**Comment by elfl0rd** [comment]
(fix in 0.8.1)

**Comment by redwyre** [comment]
That's 0.8.0.1 @elfl0rd ;)

**Comment by elfl0rd** [comment]
thx, lol

**Comment by elfl0rd** [comment]
Tested at 0.8.0.1 - not fixed, reopening.

**Comment by Shoe73** [comment]
We are witnessing this issue on our server ALOT!  We have recommended to players to empty their carts and store them when they log out.  That gets to be a pain.

**Comment by BlazeGuy2** [comment]
Another fix is merged in, should come out in 8.0.3
