### ISSUE TITLE
Survivalist skill

### ISSUE THREAD

**Issue by PawelGuzowski** [StrangeLoopGames/EcoIssues#11104]
My survivalist skill didn't work when I've installed the new version 8.0. Few days later I've changed the difficulty settings and when returning to the game my survivalist skill jumped from 1 to 7 on start before I did anything. Now I can use the shovel and hammer without any energy being taken away from my food. Playing in single player here. Took Sprinter and Nature adventurer talents.

**Comment by Deantwo** [comment]
Someone on Discord said that the **Self Improvement** speciality only gain XP when you level up other specialities. Don't know for sure though.

**Comment by D3nnis3n** [comment]
Fixed.
