### ISSUE TITLE
Pipe ports need arrows to show input/output

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11105]
![image](https://user-images.githubusercontent.com/3536496/52345712-dfc82500-29eb-11e9-9209-e2bd5dd4da48.png)
Symbols for the type of thing its inputting/outputting could also be helpful.

**Comment by elfl0rd** [comment]
i think "is there a valve - it output" is ok...

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/55360513-6f88cd80-5489-11e9-8055-a41fb4beb9c0.png)
Made it more explicit which is which with arrows.

![image](https://user-images.githubusercontent.com/14983165/55360572-a65ee380-5489-11e9-8f6a-546fad8f1692.png)

Fixed in master.
