### ISSUE TITLE
overlap of boxes onto item names in store

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11114]
**Version:** 0.8.0.0 beta

default size (as you can see ovelaps over names)
![snap4083](https://user-images.githubusercontent.com/29383891/52369241-2186b900-2a48-11e9-8967-9e1ac815baba.png)
can be resized to avoid overlap
![snap4084](https://user-images.githubusercontent.com/29383891/52369293-45e29580-2a48-11e9-8878-1ead9a36e5fc.png)
but if you take it back to smallest size, the boxes go back to overlapping the name of items for sale

**Comment by SlayksWood** [comment]
fixed in 9.0 with https://github.com/StrangeLoopGames/Eco/pull/4494
