### ISSUE TITLE
8.0 Gold Ore flying in the Air

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#11119]
![ecosever](https://user-images.githubusercontent.com/37456949/52378926-535c4780-2a69-11e9-8ebd-72f3ca228e55.gif)

**Comment by keegan-o** [comment]
was fixed in master and release

**Comment by elfl0rd** [comment]
refers to https://github.com/StrangeLoopGames/EcoIssues/issues/11224 ?
