### ISSUE TITLE
Need pipes setup on some objects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11110]
![image](https://user-images.githubusercontent.com/3536496/52356141-b619f880-2a01-11e9-8913-0d5b9ea76529.png)

LaboratoryObject, BlastFurnaceObject, and CombustionGeneratorObject need pipe setup, and need recipes that consume liquid.

**Comment by johnkslg** [comment]
This will be a hotfix, please leave in 8.0

**Comment by elfl0rd** [comment]
BlastFurnaceObject hmmm, maybe not _consume_ liquid? wtf?
blast furnace provide waste, but not consume water :)

**Comment by Sekor2600** [comment]
Maybe Cement Kiln better? And concrete need water.

**Comment by elfl0rd** [comment]
Also, "OilRefinery" - need sewage output as part of petroleum refining.
Washing machine - water input and sewage output (small quantity all time)

**Comment by Sekor2600** [comment]
maybe the Kitchen too? water for cooking?

**Comment by craig-jong** [comment]
I was told that I didn't need to add water to recipes. @johnkslg Please confirm this is the case so I can close this - the rest of the stuff should be good.

**Comment by johnkslg** [comment]
Correct, the design was changed so you no longer need to add water to recipes.
