### ISSUE TITLE
Axe should kill or fell papaya

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11116]
![image](https://user-images.githubusercontent.com/3536496/52370315-92b27600-2a20-11e9-9ec8-4f00f041c967.png)
Looks like it should, and its hard to clear otherwise.

**Comment by craig-jong** [comment]
This isn't an art problem - they're not trees and we don't have anything in place for plants to be destroyed by axe. Will add tho.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/11077
https://github.com/StrangeLoopGames/EcoSuggestions/issues/679
