### ISSUE TITLE
Let vehicles contain larger stacks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11117]
"You can build a skidsteer or escavator. These are awesome machines. You can carry 10 dirt in a stack... or 400 of anything besides dirt. So basically you get to use the machine for about 1 minute and 30 seconds before having to empty it. This is a major issue with these machines and makes them nearly unusable. "

From a review.
Crane has an override that allows carrying large quantities, can check how that works.

**Comment by elfl0rd** [comment]
Maybe better way is using "linking" to stockpiles?
If possible - i prefer this way.
