### ISSUE TITLE
0.8 Parallel Processing: OilDrilling icon still missing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11113]
![20190206212456_1](https://user-images.githubusercontent.com/4980243/52365591-e2149880-2a58-11e9-96ec-8c1be4132ece.jpg)

(but... talents FOR house, for speciality without house benches? Pumps work outside, refinery too.
Maybe we need talents special for oil? e.g. "oil refinery provide 25% less smog" vs "oil pumps work 10% faster but use 10% more energy." for 3 lvl and "lower energy consumption for all related tables at %" vs "increase oil layer capacity under your land by %" for 6 lvl

**Comment by keegan-o** [comment]
fixed in master
