### ISSUE TITLE
Lavish Workspace : Mortaring no benefits

### ISSUE THREAD

**Issue by akutamatata** [StrangeLoopGames/EcoIssues#11122]
Someone reported an issue about Lavish workplace similar to this, but they were reporting an intended feature.

Lavish workplace isn't altering the crafting recipe's cost, at least for mortaring.  

**Steps to reproduce:**
Default recipe 6 sandstone = 1 sand
100%
get up to level 7, pick lavish workplace

**expected result:**
90% reduction
recipe 0.6 sandstone = 1 sand

**Actual result:**
80% reduction
recipe 1.2 sandstone = 1 sand

**Comment by D3nnis3n** [comment]
Merged with #11330
