### ISSUE TITLE
USER ISSUE: Fish Traps Are Broken

### ISSUE THREAD

**Issue by nexusjarod** [StrangeLoopGames/EcoIssues#11123]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
1. Try to place a fish trap near your base in the water.
2.  Keep getting "Can't place, Blocked".
3.  After about 50 tries, in 50 different spots, the game crashes.	

**Expected behavior:**
Fish trap should deploy

**Actual behavior:**
"Can't place, item blocked". >>> CRASH

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nope....Pure Vanilla.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10849

**Comment by D3nnis3n** [comment]
Duplicate.
