### ISSUE TITLE
USER ISSUE: Invisible built items

### ISSUE THREAD

**Issue by MeestaRobata** [StrangeLoopGames/EcoIssues#11126]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Build any sort of item several times (dirt ramps in this case or even dirt blocks(spawned these items in)).

**Expected behavior:**
Show the object placed.

**Actual behavior:**
INVISIBLE but still functions as a placed block.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by SlayksWood** [comment]
The problem with rarely disappearing objects is still actual (but there is another task). The problem with missing items in versions 0.8.0.x has been resolved.
