### ISSUE TITLE
8.2 : Re-gen Default world

### ISSUE THREAD

**Issue by WhiteScholar** [StrangeLoopGames/EcoIssues#11120]
I'm noticing on all new generated worlds under 8.0, fox and turkey population drops to 1 or dies off completely within the first 24 hours. The new terrain generation appears to be extremely hostile to the fox, and turkey population. Tortoises seem to be surviving, but they spawn outside of the areas where the world map shows capacity.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9955

**Comment by SlayksWood** [comment]
merged with #11533.

**Comment by beastyn** [comment]
0.8.2 - staging - 5

@craig-jong Please, check this one

New DEFAULT world (without Generation from client)
World was converting
No turkeys, no new species....

- Agave:                54
- Amanita Mushroom:     0
- Arctic Willow:        2 640
- Barrel Cactus:        0
- Beans:                37
- Beets:                60
- Big Bluestem:         6 136
- BighornSheep:         15
- Birch:                563
- Bison:                4
- Bolete Mushroom:      43
- Bullrush:             0
- Bunchgrass:           100
- Buttonbush:           0
- Camas:                33
- Cedar:                435
- Ceiba:                470
- Clam:                 4 563
- Common Grass:         6 682
- Cookeina Mushroom:    48
- Corn:                 60
- Creosote Bush:        144
- Crimini Mushroom:     46
- Deer Lichen:          2 809
- Deer:                 65
- Desert Moss:          67
- Dwarf Willow:         240
- Elk:                  63
- Fern:                 524
- Filmy Fern:           1 078
- Fireweed:             216
- Fir:                  439
- Fox:                  9
- Hare:                 109
- Heliconia:            698
- Huckleberry:          38
- Jointfir:             0
- Joshua:               0
- Kelp:                 7 055
- King Fern:            735
- Lattice Mushroom:     18
- Lupine:               342
- MountainGoat:         70
- Oak:                  6
- Ocean Spray:          40
- Old Growth Redwood:   119
- Orchid:               57
- Otter:                166
- Palm:                 469
- Papaya:               185
- Peat Moss:            1 773
- Pineapple:            53
- Pitcher Plant:        0
- Prickly Pear:         18
- Pumpkin:              36
- Redwood:              78
- Rice:                 46
- Sagebrush:            0
- Saguaro Cactus:       102
- Salal:                22 000
- Salmon:               268
- Saxifrage:            308
- Seagrass:             0
- Spruce:               0
- Sunflower:            0
- Switchgrass:          7 375
- Taro:                 678
- Tomatoes:             53
- Tortoise:             19
- Trillium:             47
- Trout:                192
- Tuna:                 127
- Turkey:               0
- Urchin:               2 377
- Waterweed:            5 926
- Wheat:                58
- White Bursage:        0
- Wolf:                 86

**Comment by beastyn** [comment]
other part is there #11062
