### ISSUE TITLE
terrain edges act like quicksand (5.5 Staging)

### ISSUE THREAD

**Issue by 616dustin** [StrangeLoopGames/EcoIssues#1113]
While traversing terrain, player constantly gets stuck on edges and client ignores horizontal movement until player has slowly dropped to the tile below. This makes movement in uneven terrain a nightmare. The player will constantly catch on edges of blocks and have to wait for the character to settle to the level below before attempting to jump or move in a horizontal direction. If traversing very uneven terrain the player is also pushed off 1 tile wide blocks at times.

**Comment by metachronism** [comment]
fixed clambering fixes this
