### ISSUE TITLE
Download link from website not working for Linux and OSX version

### ISSUE THREAD

**Issue by mbodmer** [StrangeLoopGames/EcoIssues#11131]
Downloading from the website https://ecoauth.strangeloopgames.com/home does not work.
The links are not backed by a zip.

clicking on:
https://s3-us-west-2.amazonaws.com/eco-releases/EcoLinux_v0.8.0.0-beta.zip

does result in:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>EcoLinux_v0.8.0.0-beta.zip</Key><RequestId>D133C73244CD3C5F</RequestId><HostId>l8Mc8pFPfmOvQpE6di7mr8W1AYNIA8CF3+Fw1dO0gfdURxqxQnBFzJ3NwJ4wWuk5JnmtEwA0pLM=</HostId></Error>`

**Comment by D3nnis3n** [comment]
Fixed.
