### ISSUE TITLE
/unstuck seems to no longer work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11137]
See title.

**Comment by elfl0rd** [comment]
yep, unstuck need fixes. Also not bad if unstuck got improvements from #9390

**Comment by redwyre** [comment]
Still not working correctly in 0.8.0.5

**Comment by Spydarlee** [comment]
Not having any luck reproducing this. Seems to handle "normal" situations pretty well, so it's likely more complicated scenarios that fail? But I've not been able to imitate those locally.

@D3nnis3n - do you have any extra info, or examples of setups that cause trouble? Maybe a world/save file and particular area that you could upload for me to test?

**Comment by Spydarlee** [comment]
Okay, I've tried *real* hard to reproduce this but still no luck so I think I'm going to have to close as no repro for now. If someone does come across a reliable way to reproduce this please do reopen and let me know!
