### ISSUE TITLE
High Cpu Usage,

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#11144]
It seems in some places servers are run it uses a massive ammount of cpu power, and in some other machines it uses next to none,

this is on a machine with 4 cpus @2.40ghz and 8gb ram windows 2016 r2 server 100gb ssd

**Comment by TheKye** [comment]
![capture](https://user-images.githubusercontent.com/29281156/52416632-2463d580-2b3e-11e9-8cde-32e31a88d113.PNG)
See image for resource usage details

**Comment by redwyre** [comment]
4 cpus, or 4 cores? Do you know the CPU model?

Also can you include a screenshot of the plugins tab?

**Comment by TheKye** [comment]
oh, my bad, 4 cores, and its vanilla, but here you go

**Comment by redwyre** [comment]
I think you forgot to paste the image :P

**Comment by TheKye** [comment]
![capture1](https://user-images.githubusercontent.com/29281156/52420187-b02d3000-2b45-11e9-84f6-a87e1ba55be0.PNG)

**Comment by TheKye** [comment]
it was being difficult hahaha

**Comment by Zimeon-** [comment]
Was seeing the same issue on Windows Server 2016, Disabling Windows Defender seems to help somewhat.

**Comment by redwyre** [comment]
Hi @TheKye. we have released 8.1 which has a number of performance improvements, could you try it out and report back?

**Comment by redwyre** [comment]
@TheKye How is the performance for you on 0.8.3.0?

**Comment by TheKye** [comment]
@redwyre hey mate, have run 4 different servers off of a vps at the same time, as to be expected, the cpu usage spikes during server boot and world gen, 

as for over time with players and such, its much much better, thank you
