### ISSUE TITLE
The bottom block of corn is solid.  It's weird

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1114]
![image](https://cloud.githubusercontent.com/assets/23460210/23191595/5b9d96f0-f853-11e6-9282-f424374bd0ba.png)

**Comment by MarjieAVolk** [comment]
![image](https://cloud.githubusercontent.com/assets/23460210/25107143/629f827e-2382-11e7-8dfd-6295aec23dde.png)

**Comment by craig-jong** [comment]
I've discovered this has to do with the plants that are targetable. The ghost is clientside, so I'll look into that.
