### ISSUE TITLE
Goats can hover in the air - LOL

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11143]
![goatscanhover](https://user-images.githubusercontent.com/25908592/52410419-90abee00-2ad8-11e9-9a0c-1abc0d767489.png)

**Comment by metachronism** [comment]
totes m'goats

**Comment by metachronism** [comment]
Need repro steps / case, can't get this to happen regularly

**Comment by SeanAtr0n** [comment]
not sure how that one happened but if you fly around for a bit you will see an animal appear out of place and then teleport or lerp to the right spot

**Comment by D3nnis3n** [comment]
That's pretty much what i observed - minus the teleporting to the right spot, cause for me they stay there.

**Comment by redwyre** [comment]
If they're sleeping they'll stay there, if they're walking they'll either float back down to the ground, or up through the ground...

**Comment by D3nnis3n** [comment]
Fixed in starting.

**Comment by D3nnis3n** [comment]
Reopened because not fixed.
