### ISSUE TITLE
InteractionManager throws exceptions sometimes

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1115]
from InteractionManager line 169:
"else if (this.interaction != null)
            this.interaction.Hit = hit.hitInfo[queryResult.QueryIndex];"
 
Every once in a while there's an array index out of bounds on hit.hitInfo there, but once it happens once it will throw it a million times and break everything.

**Comment by metachronism** [comment]
not seeing this at all in 5.5

**Comment by MarjieAVolk** [comment]
idk I was seeing it all the time just a couple days ago, so I'm still
keeping my eyes open

**Comment by MarjieAVolk** [comment]
Well, I saw this yesterday, but haven't seen it since I synced Content... so maybe it was something to do with that after all
