### ISSUE TITLE
USER ISSUE: Blackscreen

### ISSUE THREAD

**Issue by SGRappid** [StrangeLoopGames/EcoIssues#11153]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**

**Expected behavior:**
i suppose i shouldve seen the game

**Actual behavior:**
i can hear that im moving in the background i can see the hud but the rest is black

**Do you have mods installed? Does issue happen when no mods are installed?:**
i can hear that im moving in the background i can see the hud but the rest is black

**Comment by D3nnis3n** [comment]
Duplicate.

**Comment by elfl0rd** [comment]
Duplicate of #11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
