### ISSUE TITLE
USER ISSUE: bug de poisson

### ISSUE THREAD

**Issue by scale68** [StrangeLoopGames/EcoIssues#11157]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Posez une nasse de poisson sur terre et des poissons sont pecher...

**Expected behavior:**
ne devrait pas pêcher de poissons sur terres avec la nasse ^^

**Actual behavior:**
des poissons sont pecher avec la nasse de poisso, alors qu'il est posez sur terre, voire empilé sur une autre nasse

**Do you have mods installed? Does issue happen when no mods are installed?:**
des poissons sont pecher avec la nasse de poisso, alors qu'il est posez sur terre, voire empilé sur une autre nasse

**Comment by BlazeGuy2** [comment]
Sounds like a dup of https://github.com/StrangeLoopGames/EcoIssues/issues/10849
