### ISSUE TITLE
Connection timed out on 0.8

### ISSUE THREAD

**Issue by Alyyyora** [StrangeLoopGames/EcoIssues#11158]
So.  a friend made up a Server on the new Update and we were playing on it for about 5 minutes. After this my friend got kicked of it and can't reconnect anymore. He's stuck in the loading screen on different percentages all the time. After this he get's the following error:
(Server is hosted by nitrado btw)

Connection timed out

Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 950 (ID=0x1402)
    Vendor:   
    VRAM:     1960 MB
    Driver:   24.21.14.1163
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.582801 ms
NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
  at Steamworks.NativeMethods.ISteamClient_SetWarningMessageHook (Steamworks.SteamAPIWarningMessageHook_t pFunction) [0x00000] in <00000000000000000000000000000000> 
  at SteamManager.OnEnable () [0x00000] in <00000000000000000000000000000000> 

(Filename: currently not available on il2cpp Line: -1)

Client version: 0.8

**Comment by mirasrael** [comment]
Hi @Alyyyora 
How you friend did start server? From game client or as dedicated server?

**Comment by Alyyyora** [comment]
@mirasrael The Server is being hosted by another friend through nitrado, but I think I'm not able to get content of dump directory through him.

The friend with the problem joining is connecting through everything possible, like the IP or joining on me etc.

**Comment by Alyyyora** [comment]
Whoops I didn't want to close, wrong button.

**Comment by Alyyyora** [comment]
It's not my server, so I'm not sure how I can get to the dump information on that one, I barely speak to the server owner.

but since my friend can't join any other server either, we're pretty hopeless.

If that helps, his server list is empty too, his search either. He can't find the servers i am able to find

**Comment by mirasrael** [comment]
Hi @Alyyyora Any improvements on 0.8.0.1?

**Comment by mirasrael** [comment]
No response. Closed.
