### ISSUE TITLE
Demand for food nonexistent due to self-improvement

### ISSUE THREAD

**Issue by andrewsg** [StrangeLoopGames/EcoIssues#11156]
Self-improvement, which is apparently granted for free without using a specialization star in 0.8 and levels up quickly, grants an 80% reduction in calorie consumption. On my server, because everyone is only consuming calories at 1/5 the normal rate, the entire food industry chain has bottomed out and there is zero economic demand for food of any kind.

**Comment by craig-jong** [comment]
Exp was reduced. 

The cap of calorie reduction from the skill should be the same cap as the skill before, so if its going all the way to 80% that's a bug and you should open an issue for that.
