### ISSUE TITLE
Trees frequently disappearing 

### ISSUE THREAD

**Issue by pizzlefank** [StrangeLoopGames/EcoIssues#11155]
In the server I am playing on people are complaining that trees are disappearing or flying into the sky once cut down. Most of the time they do seem to show up again eventually. The server passed a law that bans cutting down redwoods because they seem to always disappear and people think it may be a source of lag. 
About 90% of the redwoods disappear and 30% of all other trees. Is there any way to avoid this?
Is there any reason to think that these trees in "limbo" are causing lag for everyone?

**Comment by gjsmo** [comment]
Would like to add to this that redwoods are particularly problematic. Cutting them down usually leaves them standing upright, so you have to push them over (this is fine). Pushing them over however often results in a physics glitch where they will fly hundreds of meters. At that point, if they touch any water they seem to disappear. Regular trees will usually reappear if we just log out and immediately back in but redwoods do not.

**Comment by metachronism** [comment]
fixed
