### ISSUE TITLE
USER ISSUE: tree base / roots

### ISSUE THREAD

**Issue by DarkNAangel** [StrangeLoopGames/EcoIssues#11167]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
cut down one of the new trees in the rainforest biome ( palm tree and ceiba ) then try to get rid of the base

**Expected behavior:**
base of the tree is supposed to be disposed of and disapear, clearing the space.

**Actual behavior:**
when the base if cut off, it disapear but collision stay there like it is still there, unable to get rid of the collision. tried to cut it again to no avail.

**Do you have mods installed? Does issue happen when no mods are installed?:**
when the base if cut off, it disapear but collision stay there like it is still there, unable to get rid of the collision. tried to cut it again to no avail.

**Comment by donald12999** [comment]
I have the same issue, with a redwood stump.  Restarting the server did not clear issue.  Tried clearing stump again.  It shows wood chips and makes sound but didnt go away even after 150 hits, iron axe, lvl7 logging.

**Comment by metachronism** [comment]
fixed
