### ISSUE TITLE
reconnect requires hitting continue 3x

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11163]

**Comment by D3nnis3n** [comment]
Cannot reproduce, any more information?

**Comment by D3nnis3n** [comment]
Closing this, as i cannot reproduce.

**Comment by SeanAtr0n** [comment]
Connect to a server on the same LAN as you
hit disconnect 
then hit continue and you get an error msg
hit continue 2 more times and you reconnect

**Comment by D3nnis3n** [comment]
Not happening for me. I'm unassigning me therefore and assigning you.

**Comment by SeanAtr0n** [comment]
started happening after OpenNAT changes iirc

**Comment by D3nnis3n** [comment]
When i disconnect and reconnect i'm back on the server, so can't help with this.

**Comment by mirasrael** [comment]
@SeanAtr0n does anything change if you disable UPnP on the server?

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/54943892-8494b800-4eef-11e9-88cf-99033e84636d.png)

**Comment by mirasrael** [comment]
@SeanAtr0n do you have this issue with regular client or only within Unity editor?
