### ISSUE TITLE
sometimes sewage doesn't stop flowing

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11160]
![image](https://user-images.githubusercontent.com/774628/52451666-c3fc7600-2af4-11e9-8dfb-121ef0f8698c.png)

**Comment by johnkslg** [comment]
Need repro steps and more description of the problem.  In what case is it not stopping?  What does the status panel say?  Cannot repro here.

**Comment by johnkslg** [comment]
Managed to repro, when a recipe completes but it not yet collected.
