### ISSUE TITLE
USER ISSUE: wood cart disapearing

### ISSUE THREAD

**Issue by DarkNAangel** [StrangeLoopGames/EcoIssues#11166]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Simply have a wood cart with you

**Expected behavior:**
Cart is supposed to stay visible to all players

**Actual behavior:**
Some players on the server have their cart disapear from time to time, sometime it is only visible to themself, sometime it is completly invisible .

**Do you have mods installed? Does issue happen when no mods are installed?:**
Some players on the server have their cart disapear from time to time, sometime it is only visible to themself, sometime it is completly invisible .

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/11108
