### ISSUE TITLE
USER ISSUE: Infinite XP

### ISSUE THREAD

**Issue by avalonslight** [StrangeLoopGames/EcoIssues#11161]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
1. Set game to utilize action XP (our server is set to action XP = 0.05)
2. Equip a tool
3. Highlight something normally harvested by that tool
4. Hit 'E' to earn XP. Sometimes holding E will give an XP stream, othertimes you have to hit it repeatedly to get mulitple instances of XP

For instance, I have an ax equipped. Highlighting a stump like I'm about to harvest it and hitting E will grant me the amount of action XP I should get per swing, however I'm not actually swinging and no calories are being consumed, even though I'm still getting the XP for the action.

Multiple users on the server

 have reported this.

**Expected behavior:**
Nothing should have happened at all

**Actual behavior:**
It gives XP without the consumption of calories

**Do you have mods installed? Does issue happen when no mods are installed?:**
It gives XP without the consumption of calories

**Comment by avalonslight** [comment]
This remains an issue in 8.0.1

**Comment by craig-jong** [comment]
I'm replacing this option with a new option that grants player experience whenever a player receives specialty experience. In my opinion it serves the same purpose but is superior in most ways and can easily be maintained alongside the current skill system.

Hopefully that should be good for what you need it for!
