### ISSUE TITLE
Minimap is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11172]
![map](https://user-images.githubusercontent.com/25908592/52479340-9244e700-2ba8-11e9-8bd0-3e2894bfa79f.png)

**Comment by Roby1164** [comment]
No problem .....
![screenshot_9](https://user-images.githubusercontent.com/24955554/52489977-f923c980-2bc3-11e9-9cff-1104630da590.jpg)

**Comment by D3nnis3n** [comment]
Related to plumbing map.
