### ISSUE TITLE
Master (unity) tutorials broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11177]
> NullReferenceException: Object reference not set to an instance of an object
> UserTaskManagerUI.Update () (at Assets/UI/Scripts/UserTaskManagerUI.cs:33)

![unknown](https://user-images.githubusercontent.com/4980243/52485065-fa0b2a00-2bc8-11e9-8701-579d4ae52f3e.png)

**Comment by seccombew** [comment]
@elfl0rd still happening?

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/52888656-72c23700-3131-11e9-9d60-766cf5afb776.png)
Tutorials on master are fine, probably got fixed at some point.

**Comment by elfl0rd** [comment]
yes, all fine
