### ISSUE TITLE
USER ISSUE: Glitched Tree Chopping

### ISSUE THREAD

**Issue by The-Father** [StrangeLoopGames/EcoIssues#11174]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
1. Chop down a tree (Redwoods work best)
2. Chop the tree into smaller pieces

**Expected behavior:**
It should have just dropped the piece on the ground to pick up	

**Actual behavior:**
Instead, it teleports the piece directly above you, let's it fall, and then resets in the air again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Comment by The-Father** [comment]
Here is a gif of what I'm reporting:
https://gph.is/2SIfmMS

**Comment by metachronism** [comment]
fixed, logs had incorrect mass resulting in all manner of physics oddities
