### ISSUE TITLE
Chunks suddenly unloaded and didnt load again until reconnecting

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11170]
![chunkgone](https://user-images.githubusercontent.com/25908592/52477493-5e66c300-2ba2-11e9-8c97-d014f2564cf8.png)

**Comment by D3nnis3n** [comment]
![majorloadingissue](https://user-images.githubusercontent.com/25908592/52477707-2d3ac280-2ba3-11e9-9862-52b608c3f7d1.png)

**Comment by D3nnis3n** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2845040/output_log.txt)

**Comment by redwyre** [comment]
Which build is this?

**Comment by D3nnis3n** [comment]
Hotfix - release preview

Am Fr., 8. Feb. 2019, 19:58 hat Simon <notifications@github.com>
geschrieben:

**Comment by johnkslg** [comment]
Only happens on small worlds, closing for now.

**Comment by johnkslg** [comment]
Dennis has reproed this on regular worlds

**Comment by seccombew** [comment]
@D3nnis3n @elfl0rd Can you give repro steps for @metachronism

**Comment by elfl0rd** [comment]
cannot repro at fresh build

**Comment by D3nnis3n** [comment]
Neither for me.
