### ISSUE TITLE
Map glitch in 8.0

### ISSUE THREAD

**Issue by Rattoota** [StrangeLoopGames/EcoIssues#11184]
![screenshot 2](https://user-images.githubusercontent.com/47453771/52490413-50a54380-2b8a-11e9-9547-055701b73af7.png)
My game was fine not even 30 minutes ago but after it crashed i'm getting major lag spikes and for some reason my minimap is messed up. Its not showing the correct locations for me and markers. My graphics in this pic isnt a glitch btw. I just have my settings set that low to reduce the lag i shouldn't be getting in the first place considering i have 8gb of ram and the steam page says only 2gb is required.

**Comment by mirasrael** [comment]
Let's wait for 8.0.6 and 8.0.7 improvements

**Comment by mirasrael** [comment]
Do you still experience same issue on 0.8.0.6?

**Comment by BlazeGuy2** [comment]
Closing due to no response
