### ISSUE TITLE
USER ISSUE: Losing carts

### ISSUE THREAD

**Issue by banjoslaughter** [StrangeLoopGames/EcoIssues#11189]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
We are randomly losing carts when we walk away out or rendering distance from them.

**Expected behavior:**
It should have stayed put.....

**Actual behavior:**
Instead it David Copperfield itself.....

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it David Copperfield itself.....

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/11108
