### ISSUE TITLE
Game get sent to main menu when attempting to give reputation to someone with an unsupported text character

### ISSUE THREAD

**Issue by Noodalie** [StrangeLoopGames/EcoIssues#11188]
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Attempting to select while already selecting an object.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Assets.UI.Scripts.ChatUI:Deactivate()
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
TMPro.TMP_InputField:DeactivateInputField()
TMPro.TMP_InputField:OnDeselect(BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.EventSystem:SetSelectedGameObject(GameObject, BaseEventData)
UnityEngine.EventSystems.PointerInputModule:DeselectIfSelectionChanged(GameObject, BaseEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Disconnected from server.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Write(LocString)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at UI.ConnectionUI.InitTitleScene () [0x00000] in <00000000000000000000000000000000>:0 
  at UI.ConnectionUI.Start () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5355
