### ISSUE TITLE
USER ISSUE: Buggy Dirt

### ISSUE THREAD

**Issue by Niko-Ioannidis** [StrangeLoopGames/EcoIssues#11182]
**Version:** 0.7.8.8 beta

**Steps to Reproduce:**
I Tried to dig some Dirt whre no root is close and it wont work	

**Expected behavior:**
It should be removeable

**Actual behavior:**
it is not removeable and says the soil is too hard

**Do you have mods installed? Does issue happen when no mods are installed?:**
it is not removeable and says the soil is too hard

**Comment by elfl0rd** [comment]
Duplicate of #8367
