### ISSUE TITLE
You can hit granite big chunks with a stone pickaxe

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11180]
Granite requires at least iron, but you can split the large chunks into smaller ones with stone axes. players use this to save their tool durability.

**Comment by Roby1164** [comment]
![screenshot_6](https://user-images.githubusercontent.com/24955554/52489898-c083f000-2bc3-11e9-90df-4466096957a3.jpg)
![screenshot_8](https://user-images.githubusercontent.com/24955554/52489904-c5e13a80-2bc3-11e9-8672-07852e7020b0.jpg)

**Comment by D3nnis3n** [comment]
Doesnt have anything to do with this issue.
Break a granite block with an Iron pickaxe and then break the Big chunk with a stone pickaxe. This should not be possible.

**Comment by elfl0rd** [comment]
Agree, also for ores - you can break any ore by stone pickaxe =|

**Comment by Deantwo** [comment]
Might want to edit the title/post to say "Pickaxe" instead of "Axe".

**Comment by Deantwo** [comment]
I am not sure this is an issue that need fixing.
I will agree that it is a little weird, but could lead to some weird issues of people leaving big unbreakable chucks in mines that only the skilled person can remove.

**Comment by elfl0rd** [comment]
I agree, but about middle debris\tree trunk - https://github.com/StrangeLoopGames/EcoIssues/issues/11242

**Comment by mirasrael** [comment]
I think it is intended behavior. Especially with latest changes to mining (you can now break any stone with any kind of pickaxe, just need more hits). You can assume it was weakened by initial break and now you can break it with less effort.
