### ISSUE TITLE
Carved Pumpkin - incorrect collision

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11185]
(above object)
![20190208201022_1](https://user-images.githubusercontent.com/4980243/52493884-a1925780-2bdd-11e9-8733-4fff4290ce5d.jpg)
![20190208201025_1](https://user-images.githubusercontent.com/4980243/52493886-a3f4b180-2bdd-11e9-9b78-9f5ebfc5d7bc.jpg)

**Comment by craig-jong** [comment]
Reassigning to Keegan.
