### ISSUE TITLE
Player viewpoint is too low.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11187]
I really feel like a dwarf.
![20190208113329_1](https://user-images.githubusercontent.com/4980243/52494067-0948a280-2bde-11e9-8058-4d9383da132e.jpg)
![20190208113334_1](https://user-images.githubusercontent.com/4980243/52494077-0c439300-2bde-11e9-8622-3c62a5ef21d2.jpg)

**Comment by Demosthenexx** [comment]
My wife had the same problem, change your field of view to 90.

**Comment by elfl0rd** [comment]
I know, at 90 FOV you got distortions at the edges of the screen.
