### ISSUE TITLE
driving wheelbarrow

### ISSUE THREAD

**Issue by shade93** [StrangeLoopGames/EcoIssues#11193]
i can't drive properly the wheelbarrow, it doesn't go in the direction i want, the wasd controls work wrong

**Comment by SeanAtr0n** [comment]
fixed in svn, you can also now go up some blocks
![wheelbarrowop](https://user-images.githubusercontent.com/774628/52508895-fcf72200-2baa-11e9-8d9e-53ae8b0bad88.gif)
