### ISSUE TITLE
To mine copper from basalt, you need Modern/Steel Pickaxe. To get Modern/Steel Pickaxe, you need copper.

### ISSUE THREAD

**Issue by YoShIWoZ** [StrangeLoopGames/EcoIssues#11198]
So:
https://eco.gamepedia.com/Copper_Ore
> Copper Ore is a resource found in underground seams of Basalt. It must be mined with a tier 4 tool (Modern Pickaxe or Steel Pickaxe with Tool Strength perk). 
https://eco.gamepedia.com/Mechanics
As you can see you need copper to get Mechanics.

**Comment by elfl0rd** [comment]
copper is not in basalt, copper in granite.
If you have copper in basalt, please provide screenshots, save, worldgenerator.eco.

**Comment by Gudrud** [comment]
I can't show you a picture of copper in basalt, therefore I can't mine it, yet. But I can show You a screenshot of gold in basalt. 

![screenshot 2019-02-09 13 11 00](https://user-images.githubusercontent.com/37635977/52520767-9c7ce900-2c6d-11e9-80da-2cf59d284d8c.png)

**Comment by elfl0rd** [comment]
i cannot see gold in basalt at your screenshot. I see stockpile with iron and gold ores.
Also gold ore have texture like his ancestor, granite.

**Comment by Gudrud** [comment]
Nevertheless I mined it in granite. Unfortunately I didn't find another spot in the last few hours. If I find it, I will send the screenshot. Though I'm asking myself where gold should be found, when copper should be found in granite.
It will be unpossible for me to show you a screenshot of cooper in basalt beause I can not build the right tools to mine it, therefore I get no cooper.

**Comment by elfl0rd** [comment]
ofc, you cannot post screenshot of gold\copper in _basalt_ due no copper\gold in basalt.

also
![default](https://user-images.githubusercontent.com/4980243/52524091-29de2e80-2caa-11e9-83d7-7ce733c158b7.png)
![default](https://user-images.githubusercontent.com/4980243/52524097-3f535880-2caa-11e9-8cbe-f40284b0a3e5.png)

**Comment by Deantwo** [comment]
So this whole bug report started because of an error on the wiki?
The wiki is written by players, you can't use it as fact. Please test it in game and report back if there really is an issue.

Link to corrected wiki page diff: https://eco.gamepedia.com/index.php?title=Copper_Ore&diff=16602&oldid=16601

**Comment by elfl0rd** [comment]
I think this can be closed.

**Comment by YoShIWoZ** [comment]
No it was written based on what one of the dev wrote on discord. We asked
on discord if the wiki was right because we couldn't find any copper. And
the only info on how to find copper was on wiki.

søn. 10. feb. 2019 20.51 skrev Deantwo <notifications@github.com>:
