### ISSUE TITLE
USER ISSUE: Unable to connect to host after changing MaxStackSize

### ISSUE THREAD

**Issue by MLausch1** [StrangeLoopGames/EcoIssues#11194]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Change MaxStackSize from 10 to 20
Continue existing game or start new game

**Expected behavior:**
Load the existing world/start a new world

**Actual behavior:**
The following error message popped up:
```
Failed to establish connection - no response from remote host
```

**Do you have mods installed? Does issue happen when no mods are installed?:**

No Mods installed, however game files have been modified

The following error message popped up:
```
Failed to establish connection - no response from remote host
```

**Comment by redwyre** [comment]
I hope you were able to work this out, but my guess is there were a compilation error for the mods. You can run the server directly to make sure it loads correctly, or check the Logs folder.
