### ISSUE TITLE
Self improvements not provide calories and weight benefits.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11192]
+0 kg at any lvl
+0.8 calories at 7 lvl.
![20190208230207_1](https://user-images.githubusercontent.com/4980243/52503157-bd095c80-2bf5-11e9-95a3-11c5eee46f26.jpg)

**Comment by D3nnis3n** [comment]
No calorie Benefits? Players on our server need zero calories for anything with lvl7 plus work backpack and Boots xD

**Comment by elfl0rd** [comment]
it's about stomach capacity

**Comment by madolinn** [comment]
Definitely a missed order of operations in the formula.

**Comment by craig-jong** [comment]
this is fixed in master and probably 8.1
