### ISSUE TITLE
Test transport contract - not work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11206]
![default](https://user-images.githubusercontent.com/4980243/52518465-e1981f80-2c5b-11e9-9510-b679895d244a.png)
![default](https://user-images.githubusercontent.com/4980243/52518485-042a3880-2c5c-11e9-86dc-44d1e18ff66f.png)
![default](https://user-images.githubusercontent.com/4980243/52518483-fbd1fd80-2c5b-11e9-9b49-499127d25cf2.png)

**Comment by seccombew** [comment]
Related to #11207
