### ISSUE TITLE
0.8 Low quantity currency show as 0 and hard to manage.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11203]
![default](https://user-images.githubusercontent.com/4980243/52518292-7fd6b600-2c59-11e9-8225-c6398d64839c.png)
we need something to hard cut for too long fractions
e.g. dump all after 2 symbol after ,
or interface for display not shorted number... etc.

also can you add "all" button to this interface? like transfer.
![default](https://user-images.githubusercontent.com/4980243/52518296-a09f0b80-2c59-11e9-8a17-0b9cc4225df4.png)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11561
