### ISSUE TITLE
Test harvest contract - not work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11207]
![default](https://user-images.githubusercontent.com/4980243/52518555-18bb0080-2c5d-11e9-824e-45cc86105f02.png)

**Comment by D3nnis3n** [comment]
I'm quite wondering why this requires you to put the harvested things into a box? On my latest QA passes the harvest contract just wanted me to fell the tree, but not put the logs in somewhere, what version did i get? oO

**Comment by elfl0rd** [comment]
well, at least it's logical that you give the harvest to the customer and not leave with him.

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/53294956-733e8a00-3823-11e9-9c82-38788a72f16e.png)
all is ok, and any transfers, just tree cutoff

**Comment by Quadbro** [comment]
Looked at code => if Surface is checked it tests only 1 block on top of claim. if no => 5 blocks.... i think it's **VERY** unclear...
