### ISSUE TITLE
[8.0] RAM usage 8 GB right after starting a New World makes it unplayable

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#11208]
**v0.8.0.0-beta**
A locally generated new world as single player uses ~8GB and exceeds all system requirements. Thus the game becomes unplayable on my machine!
![sys require](https://user-images.githubusercontent.com/38510829/52518563-8d397380-2c4c-11e9-968f-41f8b0d545e3.jpg)
![v8 0 ram](https://user-images.githubusercontent.com/38510829/52518567-988c9f00-2c4c-11e9-996f-bc9a46efd607.jpg)
![data size](https://user-images.githubusercontent.com/38510829/52518569-a17d7080-2c4c-11e9-83a4-620e88184bed.jpg)

**Comment by Nicolausi113** [comment]
Additional Info:
If I start the local server directly, following errors show up (RAM usage was 2 GB)
![server](https://user-images.githubusercontent.com/38510829/52587403-38f3e680-2e3a-11e9-9fbe-bee6a425df09.jpg)

**Comment by mirasrael** [comment]
@johnkslg it seems too much, but also seems minimal system requirements underestimated (at least for client + server). It may be OK for just client. Also x86 and x64 probably should have different system requirements (for memory).

**Comment by Nicolausi113** [comment]
If I may do a remark on this problem:

1) is the high RAM usage possibly related to the server error I showed above?

2) for 32-bit x86 machines might it be an exclusion-criterion because of the 4 GB border which leaves ~3GB for aps. - RAM usage should drastically decrease.

**Comment by mirasrael** [comment]
No, this error isn't related. You can ignore it or disable UPnP support in server settings.

**Comment by johnkslg** [comment]
this is high priority due to hosted worlds needing it

**Comment by metachronism** [comment]
x86 server already handles this fine, if you want separate client issue for it (not really a bug though, client does actually use that much memory) you can open one
