### ISSUE TITLE
Contract clause blocks - not work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11204]
![default](https://user-images.githubusercontent.com/4980243/52518352-9e897c80-2c5a-11e9-87c5-7f86e1ff802d.png)
i have 9 compost, 4 clay and 10 mortared granite on property.
In contract counts only limit, 7 compost, 1 clay, 6 mortared granite, but want more.

**Comment by Quadbro** [comment]
Looked at code => if Surface is checked it tests only 1 block on top of claim. if no => 5 blocks.... i think it's **VERY** unclear...

**Comment by beastyn** [comment]
Looks like I foung it again in 8.1 preview release.

**Comment by beastyn** [comment]
My mistake, Thanks @Quadbro for explanation

It actually should work like that, When surface is checked deed will check only 1 block surface. This issue is more about why we need it and how to  make proper explanation for user.
