### ISSUE TITLE
8.0.1 too many compost from sewage.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11217]
1 full stockpile after ~5 min... This is not okay.
![default](https://user-images.githubusercontent.com/4980243/52519020-fc6f9180-2c65-11e9-873c-2853b291e09b.png)

**Comment by elfl0rd** [comment]
after 15m.
![20190217223654_1](https://user-images.githubusercontent.com/4980243/52918178-50811280-3305-11e9-9d64-b9c400bb9fbc.jpg)
i think compost rates from sevage need /10 lower! please fix it asap :(

**Comment by johnkslg** [comment]
@craig-jong  can you balance this?
