### ISSUE TITLE
8.0.1 after adding sewage to blast furnace, remove tailings from it recipes.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11214]
![default](https://user-images.githubusercontent.com/4980243/52518873-d7c5ea80-2c62-11e9-8b94-b13733316fab.png)

or maybe make 2 working mode, without water - tailings, with water - sewage.

**Comment by D3nnis3n** [comment]
This works as intended.

**Comment by elfl0rd** [comment]
sewage + tailings? Okay, i'll wait craig answer.

**Comment by D3nnis3n** [comment]
Please don't randomly reopen issues, this is not a bug, but works as intended. You can wait on Craig on a closed issue, if my statement is not enough for you. @craig-jong

**Comment by elfl0rd** [comment]
This is not "randomly reopen".
Craig make this system and i prefer his answer in this case.
Also please do not randomly close issues.

**Comment by elfl0rd** [comment]
Also if Craig miss this issue, i reopen it.

**Comment by elfl0rd** [comment]
okay, got answer from JohnK.
but i disagree this change, so much so that I will change this behavior in my single game.
