### ISSUE TITLE
Unstuck wont help in this case

### ISSUE THREAD

**Issue by ludovi71** [StrangeLoopGames/EcoIssues#11211]
This was pretty rare situation but anyway, i was stuck on a cave stairs because of piece of sandstone that was stuck there,
i was trying to /unstuck myself right under the sandstone, multiple times, unsuccessfully.
Photo attached.
![yrnz](https://user-images.githubusercontent.com/4980243/52522881-19bf5280-2c9c-11e9-972e-76d9bee8ddec.png)

**Comment by elfl0rd** [comment]
no screenshots.

**Comment by redwyre** [comment]
I fixed the link

**Comment by elfl0rd** [comment]
Duplicate of #9390
