### ISSUE TITLE
5.5 - Global Player Count is never updated and continues to add up.

### ISSUE THREAD

**Issue by KaneHart** [StrangeLoopGames/EcoIssues#1121]
So it seem and I checked multiple servers including my own that the player count only adds up rather then goes down.

So if you have a server and have 10 diff people connect without rebooting and all of them had left it would say 10 players online.

**Comment by metachronism** [comment]
It will go down eventually once a garbage collection occurs, but needs tweaking so player count is correct before then

**Comment by metachronism** [comment]
fixed
