### ISSUE TITLE
8.0 Otters stuck under Large Standing Hewn Log Sign

### ISSUE THREAD

**Issue by Ferchibald** [StrangeLoopGames/EcoIssues#11215]
Yesterday it was only one otter, now I have 4 otters trapped under it. It happens when the Sign is placed literally on the edge of water (sea). 
![image](https://user-images.githubusercontent.com/45064617/52518935-9c6fef80-2c53-11e9-8ded-8c114ea832c7.png)

**Comment by D3nnis3n** [comment]
lol.

**Comment by SeanAtr0n** [comment]
fixed a while back
