### ISSUE TITLE
8.0.1 disabled (by network) combustion generator provide sewage.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11213]
![default](https://user-images.githubusercontent.com/4980243/52518827-4e161d00-2c62-11e9-97f6-93be8ffd10e7.png)
![default](https://user-images.githubusercontent.com/4980243/52518887-2c696580-2c63-11e9-8234-baf27b7765e5.png)

**Comment by tobyhine** [comment]
This also applies to Blast Furnace when it is stalled by insufficient resources. No production, but sewage produced as normal.

**Comment by johnkslg** [comment]
This is per-design, otherwise you get into a loop where it turns off, then it has sufficient resource available and turns back on, repeat.
