### ISSUE TITLE
Goldoreblock - missed curved shader.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11224]
![default](https://user-images.githubusercontent.com/4980243/52523136-15e0ff80-2c9f-11e9-9eba-2e6b1c3c2d0c.png)
![default](https://user-images.githubusercontent.com/4980243/52523139-18435980-2c9f-11e9-8097-553d1434aa7b.png)

**Comment by elfl0rd** [comment]
Also from discord `EcoBuilder13#0699`
![20190209105732_1](https://user-images.githubusercontent.com/4980243/52523150-3c9f3600-2c9f-11e9-9e98-44192464cd28.jpg)
![20190209105745_1](https://user-images.githubusercontent.com/4980243/52523151-3e68f980-2c9f-11e9-855e-be16233bdb2f.jpg)

**Comment by keegan-o** [comment]
Was fixed in master and release.
