### ISSUE TITLE
Law Taxes don't work - they're not added to treasury

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11221]
This probably is because we were supposed to choose into which bank account taxes go in the law system - which seems to has been totally forgotten.

**Comment by Deantwo** [comment]
Yeah, getting more and reports of laws not taxing.

**Comment by DragonSupremacy** [comment]
Same here. It's showing up in chat as if people get taxed from cutting a tree (and from what I understand, people do need to actually have sufficient balance for it), but the treasury balance doesn't increase as a result. Allocation does work however

**Comment by Alteraner** [comment]
to fix it for the moment i would be fine if all tax are going into the treasury. To add a choice which account would be great, but is not critical.
Right now without working tax condition, its a showstopper for any collaboration servers.

**Comment by Quadbro** [comment]
that is fixed

**Comment by Alteraner** [comment]
@Quadbro, sorry, what do you  mean with fixed in last tax pr? yesterday it was still not working on our server...

**Comment by Quadbro** [comment]
okay,i'll recheck this tomorrow, but it thoughtit was fixed yesterday

**Comment by Deantwo** [comment]
@Quadbro, According to #codestream and #accouncements, the pull request was accepted after the v0.8.0.2 release.

**Comment by Sekor2600** [comment]
Yes with 8.0.2 The Taxlaw do not work. It is shown that "Player tax for 1 Credit. Tresury balance 1000. But it does not subtract from the account. Only show the Text in the Chat.

**Comment by D3nnis3n** [comment]
Fixed in 8.0.3.
