### ISSUE TITLE
FPS issue 8.0

### ISSUE THREAD

**Issue by Mahalathax** [StrangeLoopGames/EcoIssues#11225]
Some player have FPS issue without any idea why. There is a list of what we could see about that : 
- Relog on the server solve the problem bug FPS issue come back after some times
- More your view distance is big  and more the FPS issue come fast ( or instant ) 
- It's possible that can be done by the statue ( because we see that problem near it, we sill wait to test when the owner of the statue remove it )
- We got low FPS and our GPU Usage is slow ( less than 30 % ) When everythings is good GPU Usage is normal ( 50-100% )

**Comment by mirasrael** [comment]
Waiting for 8.0.6 (should bring performance improvements)
