### ISSUE TITLE
USER ISSUE: Dirt ramp visibility

### ISSUE THREAD

**Issue by slvn99** [StrangeLoopGames/EcoIssues#11228]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
play a game with 3 people in a server, have a small cart in game
Place dirt ramps up against 1 block high dirt, unclaimed ground

**Expected behavior:**
placed a dirt ramp, on which the small cart can be pushed

**Actual behavior:**
hitbox is sometimes there, but textures arent there which makes it invisible

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by D3nnis3n** [comment]
Cannot reproduce, could you attach a screenshot?

**Comment by slvn99** [comment]
Have not been able to reproduce anymore as well, might have been fixed
already.

Op zo 3 mrt. 2019 22:40 schreef Dennis Scholz <notifications@github.com>:
