### ISSUE TITLE
5.4 server crashing game client

### ISSUE THREAD

**Issue by Nenormalus** [StrangeLoopGames/EcoIssues#1122]
my server is crashing all clients who whants to concet on this server.
attaching client crash report.

http://pastebin.com/YbKxEi1f - error
http://pastebin.com/vTX7k3jz - output_log

**Comment by Nenormalus** [comment]
i attaching crash dump file at the same time.
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/801798/crash.zip)

**Comment by metachronism** [comment]
fixed in 5.5
