### ISSUE TITLE
USER ISSUE: no landscape only black view

### ISSUE THREAD

**Issue by KingNut** [StrangeLoopGames/EcoIssues#11226]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
start a new game, own world 1-3 players
no visible landscape, only black
all other windows visible.

**Expected behavior:**
visible landscape

**Actual behavior:**
black landscape

**Do you have mods installed? Does issue happen when no mods are installed?:**
black landscape without mods, fresh install of game.

**Comment by Nesnes04** [comment]
I've got the exact same problem

**Comment by KingNut** [comment]
This only happen with the first start of the game, a restart of the game fix it for me.

**Comment by D3nnis3n** [comment]
https://steamcommunity.com/app/382310/discussions/0/1778262124956545438/

**Comment by elfl0rd** [comment]
From redwyre

Happened to two players on my server
![85cac256-8bdc-47af-a444-1ca1c0177015](https://user-images.githubusercontent.com/431728/52825601-0c292300-3109-11e9-985e-44866ca81a94.png)

**Comment by marimbafarm** [comment]
This happened to 3 of 7 people in my group on a private server.

A workaround we found was to add the following as a launch option for the game via Steam:
-windowed

**Comment by D3nnis3n** [comment]
Would anyone of you that is affected be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053

**Comment by SeanAtr0n** [comment]
fixed next hotfix
