### ISSUE TITLE
USER ISSUE: Bank transfers: destination account resets when currency or source changes

### ISSUE THREAD

**Issue by Irawulf** [StrangeLoopGames/EcoIssues#11222]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
1. start a money transfer
2. select a destination account != Contract Escrow
3. change the type of currency or the sourve bank account

**Expected behavior:**
the destination account should not change

**Actual behavior:**
the destination account changes to Contract Escrow

**Do you have mods installed? Does issue happen when no mods are installed?:**
the problem occours when no mods are running

**Comment by Quadbro** [comment]
that's an intended reset, because of access and values recalculation.

**Comment by elfl0rd** [comment]
I find this TERRIBLE. Only appropriate if default value (for reset) is empty (transfer unavailable after reset).
