### ISSUE TITLE
[8.0.0] the wood cart becomes invisible

### ISSUE THREAD

**Issue by Drakeur** [StrangeLoopGames/EcoIssues#11229]
the big and small wood cart tend to become invisible to some players. For example I leave an area that will unload this, returning the wood cart is invisible, bitch real estate desk I know exactly his position but I can not see or interact with. Some players can see it and use it but not me. A server restart can solve the problem for a short time. The problem already affects 3 players of our server. I really think it's a problem of loading / unloading zone.

**Comment by elfl0rd** [comment]
Duplicate of #11108
