### ISSUE TITLE
1 fps Playing is more then not nice

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#11220]
there are some serious issues with fps.

i think the new plants, the amount of plants, buildings and housing are part of the issue

**Comment by F3UR10** [comment]
for that case the dev need more infomation:
Whats your hardware?
Single- or Multiplayer?
Playing on a server?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11248 as of better description.
