### ISSUE TITLE
Brick visual issues

### ISSUE THREAD

**Issue by Rokutaa** [StrangeLoopGames/EcoIssues#11227]
If you use the block "Brick floor" to make walls/columns, it has visual issues with other types of bricks placed next to it, causing transparency. 
Reproduction steps; Place Brick Floor block. Place any of the following brick variants adjacent to that. Brick Roof, Wall, Aquaduct, or Cube.

**Comment by elfl0rd** [comment]
this? https://github.com/StrangeLoopGames/EcoIssues/issues/4286

**Comment by Rokutaa** [comment]
almost identical! yes.

**Comment by elfl0rd** [comment]
okay, closing as dupe :D
