### ISSUE TITLE
USER ISSUE: Disappearing Objects

### ISSUE THREAD

**Issue by mkeire** [StrangeLoopGames/EcoIssues#11237]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**

**Expected behavior:**
Objects such as wood carts and steam trucks should not disappear.

**Actual behavior:**
Objects disappear and do not materialize. "click to show in minimap" function, however, provides a location to the lost object.

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by elfl0rd** [comment]
Duplicate of #11108
