### ISSUE TITLE
USER ISSUE: Water Ruining gameplay

### ISSUE THREAD

**Issue by DragianXOG** [StrangeLoopGames/EcoIssues#11234]
[**Version:**](url
<img width="895" alt="water bend" src="https://user-images.githubusercontent.com/38385034/52529943-94e72f80-2cc1-11e9-85dd-e4f70c13e203.PNG">
) 0.8.0.0 beta

**Steps to Reproduce:**
A Block, stone road, or any structure placed on top of water while touching the water, causs the water to bend around the structure, this effect is causing frame rate drop to go from 130 plus frames per second, to as low as 5 frames per second.  To correct this issue it is literally taking hours, and not changing effect on my PC.  Everyone is 100% experiencing this, anyone within 150 plus tiles of the effect experiences extreme lag.  it doesnt matter if structures that are moved, the effect continues.		

**Expected behavior:**
It should have not caused my video card to spin out of control.		

**Actual behavior:**
Melted my GPU.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Melted my GPU.

**Comment by DragianXOG** [comment]
No Mods installed

**Comment by D3nnis3n** [comment]
Can you upload your world and give coordinates? I'm  not able to reproduce this issue.

**Comment by seccombew** [comment]
Closing due to no response.

**Comment by DragianXOG** [comment]
I am not sure what you mean by upload your world?  My friends are hosting a public server under title Defcon1 gaming.  I can’t believe you’re not experiencing water flow issues?  This has been a constant struggle when any block of any type is placed touching the water.  We didn’t notice the bend in the water that is pictured above, until we started noticing our PCs bottoming our on FPS.  One gentleman ended up leaving the server who was housed nesr the bridge, but he was going all the way down to 5 frames per second.  This significant water bend has serious interrupted gameplay.  At any rate you may reach me on discord @ DragianX#1632. I will be on live-streaming to twitch tomorrow morning.  I’d be glad to help.  The challenging piece of this with my 2 other friends (and server hosts) and myself are playing with very high end gaming setups.  2 2080ti and myself with 1080ti.

Regards

**Comment by DragianXOG** [comment]
Apologies, i don't have time to mess with these things on a daily basis
however this is a publicly hosted and publicly accessed server I am playing
on and I son't think I can upload anything?  I am on the server names {US
Central} {DC1} DEFCON 1 Gaming - Active Discord - day 20.  I am sure I am
able to reproduce this at your leisure, but more or less any blck that
touches the water interacts poorly with the water.  Upon making a water
bridge where multiple blcks touched the surface of the water it caused the
bend in the water that I too a screenshot of and uploaded.

I have recreated another bend in the water at coordinates (1036, 59, 641)
It replicates easily.  Put down clcks touching water, remove them or adjust
them any way and poof, water is broke, GPU goes crazy.

**Comment by elfl0rd** [comment]
This issue is fixes after world reload (server restart), lol.
You cannot get save with this issue.

Рowever, I do not understand how you can not see that the water does not fill.
1) place block to water.
2) grab it back
3) you now have "hole" in the water.

**Comment by DragianXOG** [comment]
Yes the problem is, when doing this in multiple blocks, the player performance is severely taxed.  I understand you guys have a lot of optimization to complete, however when I have view distance of 100 turned on and I get within this range of the water anomaly, my FPS goes from 120+ FPS to 5.  As I said, in an area where this warped 30 blocks.  We had to rebuild elsewhere.  I am personal friends with server admin.  Maybe this fixed in latest micro update but when o filed this we had restarted server and it carried over restart.  This is not a low performance server (quad processor not quad core :)), and I am not on a low performance machine (Ryzen 2700x+1080ti nvme drives etc)

I am simply attempting to give you info into a serious performance hit this particular bug creates.  There is not a game created that should cause my rig to perform at 5 FPS, especially at 1080p.  My guess is the placing 4-5 of these anomalies on a world will render the server unplayable.

Good luck in your overall optimizations, look forward to seeing it develop!



Andrew

**Comment by D3nnis3n** [comment]
Well, i do see the holes in the water and i hate them as of asthetic reasons, but they cause me absolute no FPS lag. And i do have a lot of FPS lag in this game - but this is not one of the reasons for me.

**Comment by DragianXOG** [comment]
It wasn’t causing me lag with a couple, when we built that bridge, it was 50-60 blocks doing it, that’s where the lag was so far off

Andrew

**Comment by D3nnis3n** [comment]
I put the issue on investigate, but am unable to see any impact myself. We have a lot of way bigger bridges on my server, bridges that even have been removed as they are violating our server rules when they are placed in water, but it's nothing that affects my FPS - it does affect my asthetic sense, though. I hope another developer will be able to reproduce because it's definately in our interest to fix performance issues. It's just that it's hard to fix issues we cannot reproduce.
