### ISSUE TITLE
SpreadRate in ECOSIM.eco missing in 0.8.0

### ISSUE THREAD

**Issue by manson87** [StrangeLoopGames/EcoIssues#11238]
Before 0.8.0 there was an entry for each tree type names "SpreadRate".
But now in 0.8.0 this entry is missing.

Is it possible that this entry was moved in an other file?
In attachments you can see the old version before 0.8.0

thanks for helping
![spread1](https://user-images.githubusercontent.com/40967234/52534108-8a6a7b80-2d3d-11e9-835b-4ded982fc904.JPG)

**Comment by D3nnis3n** [comment]
The settings have been moved to /Mods/Organisms and split into a file for every single plant / tree.
