### ISSUE TITLE
Cannot cancel a project as Inventory does not contain the items requested to be removed

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11235]
**Version:** 0.8.0.0 beta

As seen below i have an order for Mortared limestone
![snap4149](https://user-images.githubusercontent.com/29383891/52531766-73626400-2d12-11e9-9169-b9baba5a6263.png)
i tried cancelling this as i want to move the tabel and got this message
![snap4148](https://user-images.githubusercontent.com/29383891/52531772-90973280-2d12-11e9-9083-ce2ee5aca107.png)
but if i place limestone in any attached Storage it will take for project, but the **only** way to cancel this project is to be carrying Limestone, and it cancels without any problem at all.

Linking this as it is the same problem we had in Version 0.7.0.0
USER ISSUE: unable to cancel a project until i had ingredient in inventory #3824

**Comment by Quadbro** [comment]
can't reproduce this in any way((

**Comment by elfl0rd** [comment]
This is really rare issue, but happens.

**Comment by Conchipedia** [comment]
only happen to notice this when i was moving my masonry Table due to redesign of a room and having to cancel orders that are on it, normally i very rarely cancel orders that are ongoing

**Comment by seccombew** [comment]
Please reopen if clear and consistent repro steps are found.

**Comment by Demosthenexx** [comment]
Just had this happen to me too, a workbench making 9999 orders of process limestone. Could not cancel with the same message. However based on the clue above, I picked up limestone and held it in my hands and it let me cancel.

I did notice that I originally had 4 limestone in my hands. When I hit cancel, suddenly I'm only holding 3. It consumed one limestone, and did not give me a stone or place it in a linked inventory.

Sounds like to me the code wants to consume one recipe worth during cancellation. Maybe an off by one error?

**Comment by bdavis-tc** [comment]
experiencing this issue with Kiln
i started 185 framed glass at level 6 glass making, in-case anyone sold me steel to make it before i leveled.
no i'm level 7 and can't cancel what was queued at level 6.

server has mods (including 2x stockpile size), so there is plenty of room for the 800 or so glass to come out for canceling.

I have 10 framed glass, i tried holding them in my hand as Demosthenexx said. but didn't help.
I tried holding coal too.
i tried both with the kiln having coal in the power and not.
i see there is a partial coal in the power,
ill burn that out on glass and try again...

nope still can't cancel.  :(
