### ISSUE TITLE
USER ISSUE: Invisable Stump

### ISSUE THREAD

**Issue by CoffinFaerie** [StrangeLoopGames/EcoIssues#11232]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Chop down grey spikey tree with red insides, use axe to chop stump, once it disappers it will still act as if one is there and block everything	

**Expected behavior:**
Created wood from stump or just disappered 	

**Actual behavior:**
acts like its still there even if you can't see it

**Do you have mods installed? Does issue happen when no mods are installed?:**
acts like its still there even if you can't see it

**Comment by CoffinFaerie** [comment]
No mods installed

**Comment by metachronism** [comment]
dupe, fixed
