### ISSUE TITLE
5x5 areas are blocked from building after removing stockpile: 8.0

### ISSUE THREAD

**Issue by iForby** [StrangeLoopGames/EcoIssues#11230]
When picking up a stockpile that has been placed, even after server restarting, you cannot build over location. Has happened multiple times. Message reads: "building blocked"

see attachment for example of attempting to build reported from my server.
![5x5block](https://user-images.githubusercontent.com/47337255/52526015-83316800-2c80-11e9-8e18-7c8593be53d7.png)

**Comment by elfl0rd** [comment]
Any special steps for it? I cannot repro in general.
![20190209235952_1](https://user-images.githubusercontent.com/4980243/52526260-02e22580-2cc7-11e9-8656-8d386f8e64ec.jpg)
![20190210000004_1](https://user-images.githubusercontent.com/4980243/52526261-04abe900-2cc7-11e9-8c96-35670ca90c2a.jpg)

**Comment by iForby** [comment]
Happens only half the time, as I'm finding. But; I confirmed it has happened to me on a few occasions. Especially if you try and lay a stockpile inside a big building, such as a "factory" - causes the roof to disappear sometimes as well.

**Comment by iForby** [comment]
We refreshed/regenerated server - fixed the issue. It may have been an issue just within our files.

**Comment by elfl0rd** [comment]
Okay, closing :)
