### ISSUE TITLE
USER ISSUE: Miracle tree

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#11233]
![2019-02-09](https://user-images.githubusercontent.com/35748070/52528268-1fb73280-2ca0-11e9-98cc-c38d61e6522d.png)
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**
Find a redwood that spawned next to a mountain
Chop it down

**Expected behavior:**
spawn a sapling in vicinity

**Actual behavior:**
disappears then while chopping it up for logs reappears with in 5 secs fully grown and ready for another 350+ logs

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed attached is a picture of the offending tree not really sure how I got this bug started but tree has done this twice

**Comment by Spaceferret42** [comment]
has now happened a total of three times

**Comment by metachronism** [comment]
should be fixed

**Comment by Spaceferret42** [comment]
The last time this happened was after the update to 8.0.1 are you saying another patch is in to works to fix this
