### ISSUE TITLE
"Double the speed of related table when alone" doesn't work for Chef skills

### ISSUE THREAD

**Issue by Keldoo** [StrangeLoopGames/EcoIssues#11236]
- Get to lvl 3
- Take the talent "Focus workflow : cooking",  "Double the speed of related table when alone"
- The speed of the craft isn't reduce. 

Tested for the following skills :  advanced campfire, cooking and advanced cooking

**Comment by Deantwo** [comment]
I imagine it doesn't work for campfires placed outside, but others surprise me.

**Comment by Nes112** [comment]
From what I've heard about others testing these talents, none of the crafting talents work. This includes Parallel Processing, Focused Workflow, Lavish Workspace, and Frugal Workspace. I haven't seen a github thread yet on this broader issue.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/53459639-7c7c5200-39ef-11e9-9a22-bc8b198a7162.png)
![image](https://user-images.githubusercontent.com/18184943/53459659-8aca6e00-39ef-11e9-8891-e54248a8178e.png)

It appears to be working on our current master branch, so there's a little bit more of an issue here.

**Comment by craig-jong** [comment]
oh, I see what it is. It's not updating the caches recipes timers. They're correct (or at least from my testing they are) but the timer on the crafting recipe doesn't change unless you change the crafting amount.

**Comment by craig-jong** [comment]
fixed in PR, this also revealed another bug that involved rooms refreshing themselves more than needed, so high fives all around.
