### ISSUE TITLE
Can (sometimes) remove players permissions from OTHERS property.

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#11249]
version: 8.0.0

A player just granted 3 players access to his property (none of which was me), and when i opened the property menu the 'x's near player names wasn't faded and I was able to click one to remove their permissions.

~~I've been trying to reproduce, but have yet to succeed.~~

### To reproduce:
If a third party has the property menu open when the owner adds some other player, that third party can remove the player that was just added.

Edited for clarity:

1) Player C opens property window for property owned by A
2) Player A adds Player B to said properties permissions list
3) Player C is able to remove player B (player C is not owner and does not have permissions on property)

**Comment by Quadbro** [comment]
Nice find!!!
