### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Mayana85** [StrangeLoopGames/EcoIssues#11243]
**Version:** 0.8.0.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Wood cart verschwindet dauernd und ist nicht mehr sichtbar. Über die Inventare kann man es noch ausräumen,mehr aber auch nicht. Relog und Neustart bringen nichts

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nein keine Mods installiert
Wood cart verschwindet dauernd und ist nicht mehr sichtbar. Über die Inventare kann man es noch ausräumen,mehr aber auch nicht. Relog und Neustart bringen nichts

**Comment by iForby** [comment]
@Dev team;
I can translate as I speak German.
This is another ticket reporting the invisible cart issue.
Duplicate of #11108
Just in german.

@Mayana85 

Dieses Problem wurde bereits gemeldet und wird vom Entwicklerteam bearbeitet. Siehe die Ausgabenummer oben. #11108
