### ISSUE TITLE
0.8.0 tools missing durability options on shop

### ISSUE THREAD

**Issue by FalkosTMB** [StrangeLoopGames/EcoIssues#11245]
I want to by defect tools, but i cant set durabilitys.

**Comment by Deantwo** [comment]
Missing this too. It is now impossible to make a tool repair shop.
Used to setup a store that sells tools with 100% durability, but buys tools with 0% durability for a price that are cheaper than unskilled repairs.

See also related issue #10246.

**Comment by FalkosTMB** [comment]
it is possibe if u use 2 Stores, but it worked perfect before

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1066. Wasn't able to reproduce. Seems fixed
![image](https://user-images.githubusercontent.com/45708377/62515026-bae12d00-b829-11e9-8f16-f58e2bb38801.png)
