### ISSUE TITLE
Octree Server crash

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1124]
http://ecoforum.strangeloopgames.com/topic/1778/octree-server-crash

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/903/server-crashing
http://ecoforum.strangeloopgames.com/topic/1679/server-issue-runs-for-3-or-so-hours-then-wont-work-ever-again-octree

**Comment by metachronism** [comment]
fixed in latest 5.5
