### ISSUE TITLE
Title Assignments - Add User Dropdown broken

### ISSUE THREAD

**Issue by Auranord** [StrangeLoopGames/EcoIssues#11251]
![](https://steamuserimages-a.akamaihd.net/ugc/937215510436332779/B964AAFF745EF4F7916A72FF1F73CF2357B107F7/)

**Comment by D3nnis3n** [comment]
Which version you were trying? Cannot reproduce.

**Comment by Auranord** [comment]
My current version is 8.0.0 steam edition on a multiplayer server and the error is occurring by all players i know

**Comment by Auranord** [comment]
Server is on 8.0.1 now but still same behavior

**Comment by D3nnis3n** [comment]
Still cant reproduce, please upload your world save.

Am Di., 12. Feb. 2019, 14:50 hat Auranord <notifications@github.com>
geschrieben:

**Comment by MikeW27** [comment]
We do have exactly the same issue...
![registrar](https://user-images.githubusercontent.com/19435029/52879341-2beb3600-315f-11e9-867e-037b940d91bb.jpg)

**Comment by MikeW27** [comment]
We do have exactly the same issue...
![registrar](https://user-images.githubusercontent.com/19435029/52879732-378b2c80-3160-11e9-9760-6d1f5809f2f2.jpg)

**Comment by LucasDomberg** [comment]
my savefile is too big for this site

**Comment by LucasDomberg** [comment]
https://www.dropbox.com/sh/akqd04nj8061fvw/AAA2YkZoLrJtYmRmdvVZBINWa?dl=0

**Comment by elfl0rd** [comment]
@D3nnis3n try at localized version, i got it too. (easy)
![20190217005853_1](https://user-images.githubusercontent.com/4980243/52905725-47ce0500-324f-11e9-88e6-8f5cd569665e.jpg)

**Comment by Quadbro** [comment]
8.1 master, **new** world - not reproducible (normal, localized)
8.1 master, **your** world - not reproducible (normal, localized)
![image](https://user-images.githubusercontent.com/6802030/53222840-c8529280-36a1-11e9-8d76-9487dd07b0d2.png)
