### ISSUE TITLE
Lvling up 8.0

### ISSUE THREAD

**Issue by ludovi71** [StrangeLoopGames/EcoIssues#11258]
I am either going crazy or I didnt get the lvlup star to pick another specialization
When i joined the server i had 1 star to pick new specialization.
I was lvl 1 and needed 20 xp to next lvl

at lvl 2 i should be able to pick 2nd specialization
its 50 xp to lvl 3

at lvl 3 i should be able to pick 3rd specialization
and its 100xp to lvl 4

Or am i wrong ?
![2019-02-11 3](https://user-images.githubusercontent.com/47178220/52580121-ffb27b00-2e27-11e9-964f-982b177a494f.png)
![2019-02-11 2](https://user-images.githubusercontent.com/47178220/52580123-ffb27b00-2e27-11e9-8a46-89c300678284.png)

**Comment by elfl0rd** [comment]
do not miss, you'll get self improvements automatically.

**Comment by ludovi71** [comment]
yeah but , i start with 1 star, than i lvled up 2 times, that would mean i didnt get the star for every lvlup

**Comment by elfl0rd** [comment]
your level - 3, you have 3 specialization.
Self improvement+mining+smelting, all ok.

**Comment by ludovi71** [comment]
yeah if you look at it from that side its ok,

**Comment by HetNeSS** [comment]
You gain a self-improvement point each time you  get a new speciality
