### ISSUE TITLE
USER ISSUE: Disappearing Trees

### ISSUE THREAD

**Issue by KartfahrerLP** [StrangeLoopGames/EcoIssues#11254]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
Just try to cut down a tree and they dissapear after one hit with the axe like it would be grass or something like that
World was generated in 0.8.0.0

**Expected behavior:**
Cut down trees

**Actual behavior:**
trees disappear and reappear after about 5 min at the same location

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods, yes it does

**Comment by metachronism** [comment]
fixed
