### ISSUE TITLE
Motion sickness on title screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11257]
We've had a number of complaints about it, lets change it to a more relaxed FOV and no zooming

**Comment by keegan-o** [comment]
fixed in master and release to be lower FOV and only pan-- no more movement.

**Comment by Moontsu** [comment]
Thank you very much for what you did with the title screen! I can cope with it now if I only look at the bottom of the screen- and that's doable.  :)
