### ISSUE TITLE
Deadlock: water pump require steel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11252]
(0.8.0.1)
But you cannot obtain steel without water pump.
![default](https://user-images.githubusercontent.com/4980243/52560464-7db35980-2e09-11e9-9288-5f16b021213b.png)

**Comment by Deantwo** [comment]
Catch-22.

**Steel** production require a **Water Pump**, but a **Water Pump** require **Steel**.

**Comment by wolare3** [comment]
the real problem are = how connect water to blast using gravity only ....  we have pipes and from bricks we can build "aquedickt"  ... but how exactly ???  Im testing this now

**Comment by Deantwo** [comment]
@wolare3, I simply don't think you can without a pump right now. But those might be interesting ideas for the future.

**Comment by craig-jong** [comment]
fixed by https://github.com/StrangeLoopGames/Eco/pull/3987
