### ISSUE TITLE
0.8.0.1 no login

### ISSUE THREAD

**Issue by Ebiline** [StrangeLoopGames/EcoIssues#11253]
came on a server on it and could only be 2-3 minutes on it but now it crashes already at the screen: world will enter ab.☹️☹️

**Comment by redwyre** [comment]
Do you have an Intel integrated gpu?

**Comment by redwyre** [comment]
Hi @Ebiline. we have release 8.1 which has a number of performance improvements, could you try it out and report back?

**Comment by D3nnis3n** [comment]
Closed for no response in over three weeks.
