### ISSUE TITLE
0.8.0.1 Right clicking fishing trap causes a crash

### ISSUE THREAD

**Issue by Hugines** [StrangeLoopGames/EcoIssues#11256]
When right clicking on a placed fishing trap I get this exception. 

![image](https://user-images.githubusercontent.com/9626946/52574804-52d30080-2e1d-11e9-9e9d-e33d2f1fb854.png)

 Tried this with a filled fishing trap and an empty one

**Comment by BlazeGuy2** [comment]
Booted up server on 8.0.1 and right clicked a fish trap, didn't get crash, just got a message that storage is full.  @Hugines how did you go about triggering this bug?  Can you post a clip to demonstrate it?

**Comment by Hugines** [comment]
Hey @BlazeGuy2 ,

Currently noticed that this happens when I put a fish back in the fishing trap and then right clicking again. 

![whatsappvideo20190213at16](https://user-images.githubusercontent.com/9626946/52721289-a2dece00-2fa9-11e9-9e48-17363b1c280d.gif)

Here you can see me right clicking while holding a fish. After that i right click again

**Comment by beastyn** [comment]
Founded and recreated. Will be fixed here #12059
