### ISSUE TITLE
[8.0.x] NumRiversRange does nothing

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#11267]
Since the 8.0 bleeding edge was released earlier, I iterated on worldgen with one of my staff members as mentioned in #11091. I found that NumRiversRange, which is supposed to govern how much rivers spawn, does nothing regardless of what the setting is set to. I had it to 10, 20 and anywhere in between, but at most I'm getting 1, *maybe* 2 rivers across the entire map.

**Comment by metachronism** [comment]
its not a _guaranteed_ number of rivers, but it does _try_ to make that many.  It could end up with less if the world size isnt large enough to support them all within the river avoidance range (among other factors)
