### ISSUE TITLE
Major issue with creating new world on 8.0.1 - ONE BIOME only

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11265]
The worldgenerator.eco that comes with 8.0.0. and 8.0.1 install is is the worldgenerator from 7.8  It had many errors when building worlds  with 8.0 and seems to build a mixture of the 7.8 worldgenrator and the new defaults form 8.0.0 that are not settings previously in the 7.8 config  To remedy this was to go to the serverUI and have it save a new worldgenerator.eco. make any changes like to size or spawn location and then you could build a world with decent ores and stones.

This is the file that comes in 8.0.0. and 8.0.1.  
[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2852808/WorldGenerator.zip)

When you use the serverUI and look at the worldgenerator it is much different and when you save it to the config files this is the world generator you get:
[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2852817/WorldGenerator.zip)

When 8.0.1 was released and you used the serverUI to get the uptodate WorldGenerator
 you get this which see=mes to be missing a lot of the code:  
[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2852825/WorldGenerator.zip)

In fact when you build a world with the serverUII worldgenerator files you get a world with what looks like one biome as seen on tthese 2 buiilds:  [![Screenshot from Gyazo](https://gyazo.com/0879dba0b60c56678fdbd596e4d4949e/raw)](https://gyazo.com/0879dba0b60c56678fdbd596e4d4949e)

[![Screenshot from Gyazo](https://gyazo.com/763e95f58cd1e1908852f50ad7146c95/raw)]
(https://gyazo.com/763e95f58cd1e1908852f50ad7146c95)

The world that was build with the config crearted by the serverUI for 8.0.0
[![Screenshot from Gyazo](https://gyazo.com/b715b69d78b8ae5b1a1fb9560346f163/raw)](https://gyazo.com/b715b69d78b8ae5b1a1fb9560346f163)

The worlds generated with the  8.0.1 worldgenerator is linked here:  https://www.dropbox.com/s/gae8nfuh8gv8hek/config0.8.0.1.eco?dl=0

The world generated with the 8..0.0. worldgenerator created by the serverUI  is linked here
https://www.dropbox.com/s/9g3y4bbybq4twxu/Config-8.0.0.eco?dl=0

I cannot tell if the webserver is bugged and displaying the serrver as one biome or it the world is building with one biome

most people are not seeing this I suspect as they are not creating new world for 8.0.1 and even though the config file they have back in the worldgenerator from the install is the one from, 7.8 since the load of a server does not get much from the world generator its probably  not popping up as an error.

**Comment by Bukk94** [comment]
Can confirm the issue. After the world generation, there is nothing but stone and water.

**Comment by elfl0rd** [comment]
Happens with FRESH steam installation, without old settings, etc.
Confirmed, increasing priority.

**Comment by metachronism** [comment]
if anything this is a steam-release build issue, all the files in repo are as expected.

**Comment by metachronism** [comment]
verified no repro on 8.0.2 either client version (singleplayer world) nor with the steam Eco Server tool, both worlds generate fine

**Comment by elfl0rd** [comment]
reproed some time (worldgen config i get from steam attached before), but after 3-4 attempt all fine...
Looks something broken at steam download\werification.

**Comment by Bukk94** [comment]
I've downloaded files from SLG, not the steam and this happened to me too. The WorldGenerator was just a few lines in version 8.0.1

**Comment by pamduncan** [comment]
I have downloaded 8.02 wwhich still contains the woirldgenerator,eco from 7.8.9 and is not really editable for ant 8.0 version and does not have the new biomes and other settings

I again went to the serverUi and saved a copy of the server and still do not get a complete worldgenerator that can be edited for the 8,0 series

[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2862484/WorldGenerator.zip)

**Comment by elfl0rd** [comment]
worldgen contain old settings without launch? you downloaded 8.02 from steam?

**Comment by elfl0rd** [comment]
Hah, agree :D Pam show 100% repro case.
1) download clean client.
2) launch server and go to worldgen settings.
3) file save (you don't need to change anything)
4) look at "new" ugly worldgen.

Also if it happens in this case, this can happens in another cases.

**Comment by vsysio** [comment]
Also reproducible by using steamcmd to download. 

1. Create empty directory
2. Download steamcmd
3. Run steamcmd with following commands:
login anonymous
app_update 739590 validate
quit

Pulls the old config each time.

**Comment by elfl0rd** [comment]
Still happens at 0.8.0.3 @D3nnis3n maybe need priority? - https://github.com/StrangeLoopGames/EcoIssues/issues/11480

**Comment by Rambo99** [comment]
I personally have such a situation with the "incorrect generation of the world" only when the server tries to generate a world whose size exceeds 256x256 (7.6 square kilometers). At smaller sizes (256x256 inclusive), the world is generated without errors.

**Comment by beastyn** [comment]
Can't reproduce with 0.8.1.4 With steam and slg copy
