### ISSUE TITLE
USER ISSUE: World size with no vegitation

### ISSUE THREAD

**Issue by ThisFlynn** [StrangeLoopGames/EcoIssues#11266]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
generate world with size 172,172

**Expected behavior:**
normal planet

**Actual behavior:**
Zero vegitation created upon generation

**Do you have mods installed? Does issue happen when no mods are installed?:**
Zero vegitation created upon generation

**Comment by ThisFlynn** [comment]
so I've regenerated the server world several times over and all sizes are generating without vegetation.
The only world that has been created with vegetation was the default when the server was initially started after deleting the entire eco folder and re-unzipping the files.

**Comment by ThisFlynn** [comment]
Ok - had to delete the entire folder again and change the world size in the config folder before initial world generation

**Comment by SlayksWood** [comment]
Do you have this problem now? If it happens again, please provide the save.
I was able to reproduce a world like this when I deleted the Ecosim.eco file. Did you reconfigure this file?

**Comment by ThisFlynn** [comment]
I haven't meddled with that file directly as far as I know.
We haven't recreated the planet on our server since I reported the issue,
but when we do, I'll be sure to keep you updated.

**Comment by SlayksWood** [comment]
I'll close the issue for now. If it happens again, please provide your save file.
