### ISSUE TITLE
8.0.1 Blast Furnace with idle job (no fuel) still uses water and emits sewage

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#11268]
The title is self explanatory.

![image](https://user-images.githubusercontent.com/12981415/52598075-6761c980-2e1a-11e9-8557-7fed3e64614a.png)
![image](https://user-images.githubusercontent.com/12981415/52598077-6af55080-2e1a-11e9-9d8d-0c9489580fe8.png)
![image](https://user-images.githubusercontent.com/12981415/52598098-76487c00-2e1a-11e9-8b1a-c6ecb8822101.png)

Showing the emission of waste without emitting smoke
![image](https://user-images.githubusercontent.com/12981415/52598058-5d3fcb00-2e1a-11e9-9d8f-a541a578f71b.png)

**Comment by MaxInertia** [comment]
This only happens when the water pump is on, perhaps this is intended behavior?

Although if nothing is smelting when the water pipe is on perhaps there shouldn't be waste output?

**Comment by johnkslg** [comment]
Whats the status tab says? If it says 'water is flowing but rate is too slow' then its by design, it will flow and make sewage but not be enough to craft. Reopen if it doesnt say that.

**Comment by elfl0rd** [comment]
@johnkslg what make sewage if no working?
I think in this case "no flow" or flow "water" (not sewage) will appripriate.
also
![default](https://user-images.githubusercontent.com/4980243/53495952-1278b100-3ab2-11e9-9df2-b439e152137c.png)

**Comment by MaxInertia** [comment]
I'm not currently playing and the world on which the furnace shown is gone, however I'm fairly certain the only X was on fuel, same as the status @elfl0rd posted.

I agree with Elf that if no job is running it shouldn't be outputting waste. However, ultimately that's up to you guys. Possibly have it output water when no job is running (I imagine this being the more difficult option), or automatically turn off pumps when no jobs exist on the connected furnace (easy, but may cause problems for a network of pipes connected to multiple furnaces, some with and without jobs).

**Comment by johnkslg** [comment]
I fixed a bunch of issues with pipes, may have fixed this. If you are able to reproduce it and send me the world file I will take a look though.
