### ISSUE TITLE
[EcoPC_v0.5.5-alpha-staging-e2853f91] On first Farming Client Crashed

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1126]
EcoServer_v0.5.5-alpha-staging-e2853f91
If i Restart the Server on first Farming a plant Client Crashed
Server Dump
--BEGIN DUMP--
Dump Time
02/26/2017 11:41:14
Exception
System.Exception: Caught exception invoking RPC PlayerInteract on Player!
Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
Stack:
   bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   bei Eco.Gameplay.Items.YieldAttribute.Get(Type type)
   bei Eco.Gameplay.Plants.PlantEntity.Harvest(Player player, Boolean picked)
   bei Eco.Gameplay.Plants.InteractablePlantBlock.OnActInteract(InteractionContext context)
   bei Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   bei Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()
--END DUMP--
EcoPC_v0.5.5-alpha-staging-e2853f91
Last entry Client --> output_log.txt
------------------------------------------------------
Failed to find ItemMap for: 538
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
Playing: Nocturne for grasslands
IndexOutOfRangeException: Array index is out of range.
  at InteractionManager.ProcessInteraction (Boolean force) [0x00000] in <filename unknown>:0 
  at InteractionManager.Update () [0x00000] in <filename unknown>:0 
 OR ....
--------------------------------------------------
Failed to find ItemMap for: 139
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
Failed to find ItemMap for: 139
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
Setting up 1 worker threads for Enlighten.
  Thread -> id: 4cfc -> priority: 1

**Comment by metachronism** [comment]
fixed
