### ISSUE TITLE
Update skillpoint command

### ISSUE THREAD

**Issue by feildmaster** [StrangeLoopGames/EcoIssues#11269]
There is currently no way to award stars (replacement to skill points) with server commands. Seeing as this is a new system, and I'm not 100% sure you can even *do* such a thing, I ask the command get updated or removed as required.

**Comment by McSassa** [comment]
you could use levelupuser command to give a star to another player

**Comment by feildmaster** [comment]
Good idea. How does the level up command work, add 100% of current level experience or just sets to 0 for next level? I wouldn't want to cheat people of their proper experience points

**Comment by BlazeGuy2** [comment]
levelupuser adds just enough xp to take you to the next level.

**Comment by feildmaster** [comment]
I don't see why this issue was closed. The game still has commands that need to be changed/removed. An alternative for my personal issue was found, that is all.
