### ISSUE TITLE
USER ISSUE: Cannot place carts on law with Tailing dumping is only allowed in designated District

### ISSUE THREAD

**Issue by ArranChase** [StrangeLoopGames/EcoIssues#11275]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
Create a law that prevents dumping tailings outside a designated district, and then try to place a cart outside designated area, this is not allowed.

**Expected behavior:**
Be able to place anything but Tailings outside designated area

**Actual behavior:**
Cannot place anything outside designated area

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed, Vanilla base game used

**Comment by elfl0rd** [comment]
law screenshot please.

**Comment by Deantwo** [comment]
Sounds like a messed up law more than a bug, so yes very much want to see the law in question.

**Comment by D3nnis3n** [comment]
I cannot get this reproduced, please provide your world or a law screenshot.

**Comment by D3nnis3n** [comment]
Due to no response i'm assuming this is caused by a wrong law, therefore closing. Reopen if you still have issues.

**Comment by Deantwo** [comment]
Has been reports of corrupt laws making weird things happen. But yes, can't tell without more information.

See: #11492
