### ISSUE TITLE
Interior of buildings are red on login

### ISSUE THREAD

**Issue by gjsmo** [StrangeLoopGames/EcoIssues#11270]
Only appears at certain times of the day, so this is somewhat difficult to nail down for the exact conditions. It seems to occur only when global illumination is on, though I haven't confirmed this.

![20190210130024_1](https://user-images.githubusercontent.com/12057767/52601828-41462480-2e2e-11e9-9ddc-0b3196b0e278.jpg)
![20190210130033_1](https://user-images.githubusercontent.com/12057767/52601829-41462480-2e2e-11e9-9a87-3565b8f5cf39.jpg)
![20190211184616_1](https://user-images.githubusercontent.com/12057767/52601830-41462480-2e2e-11e9-80c7-fb1743553641.jpg)
![20190211184622_1](https://user-images.githubusercontent.com/12057767/52601831-41462480-2e2e-11e9-9d0c-39c9988a63c7.jpg)

**Comment by keegan-o** [comment]
I would guess this would have been happening because a SEGI tint on one of the hewn log materials was set to red, but none of them are like that now. Can't repro.

**Comment by WeaselDog** [comment]
It looks like this is fixed in our latest version. Let us know if you experience this again. Thank you for your contribution.
