### ISSUE TITLE
8.0.1 Can generate steel with no water input or waste output

### ISSUE THREAD

**Issue by MaxInertia** [StrangeLoopGames/EcoIssues#11272]
#### Requirements
- One Blast Furnace
- Output connected to 3 **unpowered** Waste Filters
- Input connected to a powered Water Pump (**not turned on**)

This approach still generates air pollution, but there is no water input and no waste output.

### Pipe setup
![image](https://user-images.githubusercontent.com/12981415/52607237-2d54ef80-2e3b-11e9-82c2-f42850080387.png)

The Blast Furnace is to the right. Bottom pipes connected to Filters are connected to Blast Furnace waste output. Top pipe connected to pump and then Blast Furnace waster input.

The other end of both pipes is in water.

### Pipes tab on Blast Furnace
![image](https://user-images.githubusercontent.com/12981415/52607316-6a20e680-2e3b-11e9-809e-b44e41cab745.png)

This shows I have no water input or waste output.

### Crafting tab on Blast Furnace
![image](https://user-images.githubusercontent.com/12981415/52607321-73aa4e80-2e3b-11e9-9f34-845bd0571f44.png)

This shows that I am smelting steel

**Comment by MaxInertia** [comment]
### Status tabs for the Water Pump and Waste Filters

![image](https://user-images.githubusercontent.com/12981415/52607588-6346a380-2e3c-11e9-884e-af0508cc06a9.png)

![image](https://user-images.githubusercontent.com/12981415/52607596-6d68a200-2e3c-11e9-9dfe-71f84a9ca213.png)

**Comment by MaxInertia** [comment]
As far as I can tell, the problem (or part of it) may be that the furnace doesn't have a condition checking if the pump is on.

So it works when the pump is off.

Then waste output probably depends on water input (which is zero).

**Comment by johnkslg** [comment]
I cant repro this, it works properly for me. Can you send me your game.eco file and reopen?
