### ISSUE TITLE
USER ISSUE: Bugged inside a tree

### ISSUE THREAD

**Issue by HappyStunt** [StrangeLoopGames/EcoIssues#11278]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
walk inside a part of the world that isn't yet loaded.
Stand in the location of a tree.
wait until the tree spawns back in

**Expected behavior:**
not trapped me in a tree

**Actual behavior:**
trapped me making me unable to move

**Do you have mods installed? Does issue happen when no mods are installed?:**
no I don't have any mods installed

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11375
