### ISSUE TITLE
5.5-E2853f91: Propose a Law needs a big update it's list of Kill.

### ISSUE THREAD

**Issue by KaneHart** [StrangeLoopGames/EcoIssues#1127]
From what I understand you can manually inspect the elements of the page and add the correct things to the list but overall the list should be updated with all the current things in the game.

Example:
https://i.imgur.com/INFHdHr.png

**Comment by rainfarmer** [comment]
The list of law targets is hardcoded into the web side.

@MarjieAVolk Could you get me a current list of what we can make laws on?
Eventually we should probably create a new query that gives a list of what laws are allowed.

**Comment by MarjieAVolk** [comment]
Okay rainfarmer, I've added two queries that give valid targets for the two types of laws, it's now in master.
