### ISSUE TITLE
Make housing circle scale as subtotal increases

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11279]
The food circle in the status panel shrinks when you lose calories, but the housing panel doesnt change size.  Let's make this similar to the food panel, but with regards to housing points. As the subtotal of the housing panel rises (that is, not including the balance bonus), it should increase in size, capping at some housing value that will typically be reached mid-to-late game.  Smallest size should be not-miniscule, so its visible even for first level housing.  Find a good range that feels good, so that as you upgrade your house it gets bigger and more satisfying.

**Comment by Skasi** [comment]
I think it would make sense to use the Material Quality (aka Tier) Soft-Cap for the full sized circles (the cap after which a house value penalty kicks in).

Reason being that if House Value is the equivalent to Calories, then Stomach size is the equivalent to the House value Soft-cap and that means Material Quality is the equivalent to the Self Improvement Specialty.
In other words, the food circle radius is based on "Current Calories / Stomach size" and so for houses the equivalent would be "Current Value / Tier Soft-Cap". Stomach size (=calories cap) can be increased by leveling self improvement, while housing value cap can be increased by upgrading house tier.

Furthermore, house value softcap numers seem less arbitrary than _"some housing value that will typically be reached mid-to-late game"_.

**Comment by WeaselDog** [comment]
Implemented in 9.3
