### ISSUE TITLE
USER ISSUE: get no XP points after update 0.8.0.1

### ISSUE THREAD

**Issue by manson87** [StrangeLoopGames/EcoIssues#11285]
![20190212223702_1](https://user-images.githubusercontent.com/40967234/52669789-5185fe80-2f17-11e9-94ef-9b00f61b4e6d.jpg)
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
Doing anything to gain XP

**Expected behavior:**
It should gain XP

**Actual behavior:**
I get no XP if i work, different things tested

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed

**Comment by elfl0rd** [comment]
you already have max available level.
