### ISSUE TITLE
USER ISSUE: NullPointer on custom contract

### ISSUE THREAD

**Issue by MikevanLoe** [StrangeLoopGames/EcoIssues#11289]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
1. Let player 1 create a custom clause contract

2. Make player 2 accept it
3. Accept it, but change the contractor to yourself

**Expected behavior:**
Accepted the quest normally

**Actual behavior:**
It crashed to main menu and gave a nullpointer
[Eco Nullpointer.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2858752/Eco.Nullpointer.txt)

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have not installed any mods, nor does the server owner

**Comment by Quadbro** [comment]
Failed to reproduce it in any way....
