### ISSUE TITLE
Redwood (also Old Growth) - someting wrong with yield potential

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11286]
She start to die, immediately after creating new world.
Just compare layer and world parameters.
![20190213003151_1](https://user-images.githubusercontent.com/4980243/52670221-0c6ac800-2f29-11e9-9938-0fba953e2976.jpg)
![20190213003156_1](https://user-images.githubusercontent.com/4980243/52670226-0e348b80-2f29-11e9-8176-864d5beb5262.jpg)
![20190213003200_1](https://user-images.githubusercontent.com/4980243/52670233-12f93f80-2f29-11e9-9dff-6bd438dc58e9.jpg)
![20190213002852_1](https://user-images.githubusercontent.com/4980243/52670254-1c82a780-2f29-11e9-9db8-211df3cadf6e.jpg)

Also for standart redwoods
![20190213003006_1](https://user-images.githubusercontent.com/4980243/52670279-302e0e00-2f29-11e9-91bf-6519897a9f64.jpg)

**Comment by SlayksWood** [comment]
move to #11982
