### ISSUE TITLE
USER ISSUE: Road Tool problem

### ISSUE THREAD

**Issue by manson87** [StrangeLoopGames/EcoIssues#11281]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
1. build a road and use it with roadtool

**Expected behavior:**
can drive with small wood card easy over it

**Actual behavior:**
is stucks and stops completelly, just look at the picture

![20190212220454_1](https://user-images.githubusercontent.com/40967234/52667964-8e032b80-2f12-11e9-8caa-2ab45c5fda11.jpg)

**Comment by elfl0rd** [comment]
ramps are 4 long, you placed it to 3 long.
not an issue (but ofc, ramp need more polish)

**Comment by manson87** [comment]
oh, stupid O.o
i will check it

**Comment by manson87** [comment]
ok it works, thanks :) can be closed
