### ISSUE TITLE
Currency Exchange sets the currency to top of the list when either server restart or just sometimes randomly occurs

### ISSUE THREAD

**Issue by Noodalie** [StrangeLoopGames/EcoIssues#11283]
Changing the currency to anything else, it will just end up using the top of the list currency. I tried changing it live with someone that tried to use it 

so if we set it give 1 Gem for 10 Crowns
since crowns is lower alphabetically it comes out as
sell 1 crown for 10 crowns

Reproduce method?: Server restart most of the time.

This happens with loan contracts too.

EDIT: Its not just loan contracts its any sort of currency list inside contracts

**Comment by redwyre** [comment]
in 0.8.0.7 users only see the default currency when exchanging and nothing changes it, making the currency exchange completely broken
