### ISSUE TITLE
[8.0.X] Constant crashing (with Avast enabled)

### ISSUE THREAD

**Issue by asiantator** [StrangeLoopGames/EcoIssues#11280]
I continually crash no matter what situation I find myself in. Fresh server established server, singleplayer. Have uninstalled and reinstalled twice and double checked all my drivers. Including crash dump

https://pastebin.com/TBQNDt4Y

**Comment by mirasrael** [comment]
@asiantator can you try to temporary disable Avast Antivirus and try to run game?

**Comment by mirasrael** [comment]
Thanks for feedback! Seems you should create ticket in Avast support
