### ISSUE TITLE
Too much build spam in visual studio

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11299]
[BuildSpam.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2861469/BuildSpam.txt)
I cant find the errors and warnings in all this. Make it do everything silently and only display errors and warnings.

**Comment by BlazeGuy2** [comment]
Sent you a message on discord about getting the warning/error list.

**Comment by metachronism** [comment]
all warnings are errors.  looks like you added a file to the mods project again, resulting in a broken project.

**Comment by beastyn** [comment]
need actualization

**Comment by mirasrael** [comment]
@johnkslg You can change MSBuild verbosity level in VS:
![image](https://user-images.githubusercontent.com/475445/68671117-a23a8e80-055f-11ea-897c-6f6c4b6a8ac0.png)
https://blogs.msdn.microsoft.com/saraford/2008/10/07/did-you-know-you-can-configure-the-msbuild-verbosity-in-the-output-window-329/
