### ISSUE TITLE
USER SUGGESTIONE:  strawpoll

### ISSUE THREAD

**Issue by NortonDK** [StrangeLoopGames/EcoIssues#11298]
Add the possibility to make strawpolls via the server webpage system

**Comment by D3nnis3n** [comment]
Duplicate Suggestion.

**Comment by NortonDK** [comment]
@D3nnis3n Duplicate of what?

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9059

**Comment by D3nnis3n** [comment]
Suggestions Tracker is over here by the way, if you got any more suggestions: https://github.com/StrangeLoopGames/EcoSuggestions

**Comment by NortonDK** [comment]
ah thanks!

Den ons. 13. feb. 2019 kl. 16.19 skrev Dennis Scholz <
notifications@github.com>:
