### ISSUE TITLE
Work clothes remove food consumption.

### ISSUE THREAD

**Issue by PawelGuzowski** [StrangeLoopGames/EcoIssues#11293]
I've noticed that after I fully upgraded a work skill lie logging or mining and put work boots and work backpack on my food consumption went to zero. Even with a broken tool I can just work without any food/calories being used. Have this on a server I play on and tested it in single player with same effect. 
When I remove those 2 items consumption returns.

**Comment by craig-jong** [comment]
Fixed in a pr. Total reduction is now significantly lower. We may bump up calorie costs a bit, but I don't want to punish early gameplay so we'll see.
