### ISSUE TITLE
Adding Multipliers for Resources

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11297]
Several requests for being able to adjust gathering rates and crafting resource rates on the fly by a multiplier in the config. It's a common feature in survival games nowadays and could benefit Eco as well - it gives more ways for players to adjust the feel of the game to a pace they like.

- Resource Cost
- Crafting Time
- Gathering

**Comment by elfl0rd** [comment]
My old suggestion - https://github.com/StrangeLoopGames/EcoSuggestions/issues/458

**Comment by metachronism** [comment]
should be in eco suggestions, not a bug

**Comment by D3nnis3n** [comment]
All items of my list are on Bugs. This is a recurring steam review wish.

**Comment by D3nnis3n** [comment]
Implemented, but non-fuctioning: https://github.com/StrangeLoopGames/EcoIssues/issues/14429
