### ISSUE TITLE
SpecialtyExperienceDivisor does nothing

### ISSUE THREAD

**Issue by TheSpaceDad** [StrangeLoopGames/EcoIssues#11296]
The setting SpecialtyExperienceDivisor in Difficulty.eco does not to do anything. Looking in the source I can see that this only appears in two files, ViewAutogen.cs and DifficultySettingsPlugin.cs where it is just being set but the setting is not used. It is not referenced anywhere else and therefore has no effect on the game.

**Comment by elfl0rd** [comment]
Also can you take a look at `SpecialtyExperiencePerLevel`? as i see it uses "tier" in calculation, but tier everytime is 1...

**Comment by WeaselDog** [comment]
Bumping in priority because this also appears in Client UI
