### ISSUE TITLE
USER ISSUE: Wood Cart goes invisible

### ISSUE THREAD

**Issue by eawarich** [StrangeLoopGames/EcoIssues#11294]
**Version:** 0.8.0.1 beta

**Steps to Reproduce:**
1. Play online.
2. Put your Wood Cart down for 10 seconds or more

**Expected behavior:**
Stayed visible/interactable

**Actual behavior:**
It shows on the map, but in game it is invisible, and can't be interacted with. Reappears after a while/server restart.

**Do you have mods installed? Does issue happen when no mods are installed?:**
It shows on the map, but in game it is invisible, and can't be interacted with. Reappears after a while/server restart.

**Comment by elfl0rd** [comment]
Duplicate of #11108
