### ISSUE TITLE
default currency not applying to shops

### ISSUE THREAD

**Issue by xtreampb** [StrangeLoopGames/EcoIssues#11303]
this may be related to the bug: #8715 but i have the world default currency set to my minted currency.  When my players place a shop it is **displayed** as the currency used for the store, but they have to change it to another currency and then back for it to actually be used.

**Comment by D3nnis3n** [comment]
Confirmed, very confusing to players.

**Comment by Hydrohawk** [comment]
Also seeing this in Currency Exchanges:
![image](https://user-images.githubusercontent.com/38095046/53283120-0930c280-3707-11e9-9df3-73b96358398a.png)
(Should say 1 Sand Dollar for 1 Carrot / 1 Carrot for 1 Sand Dollar)
Seems to still function though.  Hope the repair fixes this as well.
