### ISSUE TITLE
No Menu Available in 8.02

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11304]
Loading 8.02 all that showed one the menu was the single player game, no other menu choices.  Was able to fix this by deleting the %appdata%/LocalLow/Strange Loop Games/Eco completely.  Tried putting back in the saved favorites and recent and playtime files so not to have to recreate them but that caused menu to be lost again but I do not understand as to why they would cause this

[![Screenshot from Gyazo](https://gyazo.com/576377f4e3ed429ae2425d81ec857740/raw)](https://gyazo.com/576377f4e3ed429ae2425d81ec857740)

**Comment by BlazeGuy2** [comment]
Couldn't get this to trigger in 8.0.3, let me know if it happens again.

**Comment by D3nnis3n** [comment]
Cannot reproduce, reopen if this reoccurs on 8.0.5 or newer versions.
