### ISSUE TITLE
Water pumps are missing in Master

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11301]
![image](https://user-images.githubusercontent.com/3536496/52739824-be44db80-2f9f-11e9-9739-ecaf9f5054ed.png)
They are placeable but dont appear.

**Comment by johnkslg** [comment]
Elevating to critical because I cant fix pipes further until this is fixed.

**Comment by keegan-o** [comment]
Committed art for electric and mechanical water pumps to master-- now water pumps should work fine, but the tech tree needs to be updated. The WaterPumpObject and WaterPumpItem has the art for ElectricWaterPumpObject and ElectricWaterPumpItem. Either that needs to be re-named everywhere, or we can just change the friendly name of WaterPumpItem from Water Pump to Electric Water Pump. 

And secondly, the Mechanical Water Pump needs to be added to the tech tree. MechanicalWaterPumpObject and MechanicalWaterPumpItem are ready to go in master.
