### ISSUE TITLE
Animals should be afraid of cars and areas with high activity of players.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11309]
(Because situations like this are really dumb.)
![20190213232403_1](https://user-images.githubusercontent.com/4980243/52777816-b8113680-3055-11e9-9941-c2c01d61650b.jpg)

Also not bad if you allow hit animals by a car...
For example, temporarily stun them and give the opportunity to drive.
Or kill, but not to able to pick-up carcass.

**Comment by D3nnis3n** [comment]
It's even worse, we see stockpiles of animals sleeping on the streets, around 50 to 70 animals in our capital total, 5 - 10 at specific places.

**Comment by D3nnis3n** [comment]
Fixed in 8.1
