### ISSUE TITLE
USER ISSUE: Duplication Glitch for land claim (Admin only)

### ISSUE THREAD

**Issue by FootsureQuincey** [StrangeLoopGames/EcoIssues#11305]
**Version:** 0.8.0.2 beta

**Steps to Reproduce:**
1. Learn a bunch of skills from books
2. Type "/noskills" in chat
3. Relearn the skills
4. Rinse and repeat

**Expected behavior:**
Not given the land claims for learning something that I had learned previously

**Actual behavior:**
Give the land claims indefinitly using described behaviour

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed on my server

**Comment by elfl0rd** [comment]
Intended behavior.
Also you can give land claim papers to itself, if you are admin (`/give land claim papers`, heh.)
