### ISSUE TITLE
5.5 - Staging-e9obb057 - Crossing border bug 

### ISSUE THREAD

**Issue by Tetramorium** [StrangeLoopGames/EcoIssues#1131]
Not getting teleported after crossing border. (Chunks not loading after doing this might be related)

How to reproduce:

Crossing the border many times quickly in a row on  a cart or on foot. First 10 times go fine, but after 10+ times the bug occurs.

**Comment by SeanAtr0n** [comment]
I can't seem to reproduce this, did this happen to you more than one time? Can you still reproduce it?

**Comment by Tetramorium** [comment]
Tried it again with the new migration tool on the latest staging. Crossing the border from 0-999 seems much smoother now. 

I can no longer reproduce it.

**Comment by SeanAtr0n** [comment]
seems resolved
