### ISSUE TITLE
Text window display staying to an old text position

### ISSUE THREAD

**Issue by Xandoria** [StrangeLoopGames/EcoIssues#11315]
Hello, I had a bug with my text window.
It appeared since I decided to increase the size of the UI in the graphics configuration to have bigger font size, I tried many sizes and finaly chose 100%.  I have also reduced the size of the text window.
And the problem was that I had to manually move the right side  cursor of the text window every time a new sentence appeared to be able to read it. The cursor kept going up to old texts.
I tried to unlog and relog in the game but that did not work.
It seems that pushing the C button to hide and display the text window again has corrected the problem.
So, maybe after the user resizes the window or resizes the UI, an automatic refresh of the window would be nice.

**Comment by Xandoria** [comment]
Sorry I was wrong. The bug remains. Pushing C solution is temporary.

**Comment by beastyn** [comment]
Seems to be ok in 0.8.1.4
