### ISSUE TITLE
Self Improvement Speciality - Level 3 -doesn't have description

### ISSUE THREAD

**Issue by trueslider** [StrangeLoopGames/EcoIssues#11310]
Self Improvement Speciality - Level 3 - doesn't have description

![2019-02-14_13-40-34](https://user-images.githubusercontent.com/4980243/52778989-51d9e300-3058-11e9-8168-1912903cf66d.png)

**Comment by redwyre** [comment]
Confirmed in 8.0.3

**Comment by SlayksWood** [comment]
merged to #11310
