### ISSUE TITLE
Tree bark Texture Improvements

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11314]
Looks like the texture has been highly compressed
![image](https://user-images.githubusercontent.com/431728/52788282-27b21080-30ac-11e9-9fbf-c47ee82e58f1.png)

**Comment by keegan-o** [comment]
I know off the top of my head that this is just how the texture was authored by Milenko, but I will make a note to revisit the texture.

**Comment by keegan-o** [comment]
I'll leave it up to Milenko whether he wants to revisit this texture.

**Comment by MilenkoTunjic** [comment]
Texture is 512x512 It can be rezzed up and touched up. Not sure if we ever did normals/shininess textures for trees, of not this should all be done in one go.
Will look into this one, as well as the other trees and make sure they are all on par.

**Comment by MilenkoTunjic** [comment]
Bark textures with normals and Metalness/roughness maps have been done.
Birch
Cedar
Fir
Oak
Redwood
Spruce
If there are any other let me know.
