### ISSUE TITLE
8.0.2 Default Citizen demographic broken

### ISSUE THREAD

**Issue by Cyborgmatt** [StrangeLoopGames/EcoIssues#11317]
On a fresh install of the 8.0.2 dedicated server, the citizen demographic is bugged.

Tested on two fresh installs.

![demographic](https://user-images.githubusercontent.com/3114217/52820723-adca5900-30a4-11e9-8674-9ac2370ca1c6.PNG)

**Comment by D3nnis3n** [comment]
Default World?

**Comment by Cyborgmatt** [comment]
@D3nnis3n Nope, this is on a freshly generated world on the dedicated server Steam tools package.

**Comment by D3nnis3n** [comment]
Try again with the upcoming 8.0.3 - i can't reproduce the issue and at least in 8.0.3 i'm very sure i didn't have the issue.

**Comment by Cyborgmatt** [comment]
Fixed in 8.0.3
