### ISSUE TITLE
No ground after passing 0

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11313]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2864831/output_log.txt)
![20190214144956_1](https://user-images.githubusercontent.com/4980243/52785268-9d948880-3068-11e9-86fb-a508ecca851a.jpg)
(just walk over 0 - if you on another side, you cannot see ground on previous side (and objects on your side)
If you walk back - all ok)

**Comment by SeanAtr0n** [comment]
Reducing priority, haven't been able to reproduce so far... I'm guessing you were driving a vehicle that got destroyed in a weird way? (would have been good info to include if that happened)

**Comment by SeanAtr0n** [comment]
tried doing a bunch of weird things to vehicles to make this happen and couldn't... only other oddity in the log file are a bunch of view exceptions, might be related to subscriptions that @mirasrael was working on?
