### ISSUE TITLE
Negative allocations (not taxes!) in the law system are able to reduce your account balance below zero

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11319]
See title.

**Comment by WeaselDog** [comment]
This issue has reappeared in 9.0 staging and affects both tax and pay now.

**Comment by johnkslg** [comment]
Made negative allocations/payments disallowed:
![image](https://user-images.githubusercontent.com/3536496/69990532-b50b0800-14fa-11ea-969b-d16b9443246e.png)

Since both allocate and pay exist as actions, you won't need negative amounts in there, you can jus use the other one. Makes for more explicit specification of funds going in/out.

**Comment by D3nnis3n** [comment]
Shouldn't it actually disallow to even put those numbers in? Having the law not working correctly after proposal is not the most user-friendly case?

**Comment by johnkslg** [comment]
It does, but you can still get negative cases with arithmetic and such (wealth - wealth * 2) that are hard to detect, so it needs a fail on activate too.

**Comment by beastyn** [comment]
@D3nnis3n waiting for you here )

**Comment by D3nnis3n** [comment]
Aye, we only test on weekends though.

**Comment by D3nnis3n** [comment]
Given my talk with john it seems correct though, as you can't insert negative amounts. If you can confirm that, you can close it.

**Comment by beastyn** [comment]
yeah, minus is not allowed.
But, actions is prevented with 0 numbers too.
![bandicam 2019-12-04 11-25-08-013](https://user-images.githubusercontent.com/27898520/70118002-bec27600-1688-11ea-928f-29b8a8ed6a24.jpg)

**Comment by D3nnis3n** [comment]
Zero should be acceptable @johnkslg

**Comment by johnkslg** [comment]
I made zero succeed and skip, while negative fails:
![image](https://user-images.githubusercontent.com/3536496/71132832-78ebce80-21ad-11ea-8e7f-8bb3b89d86d6.png)
