### ISSUE TITLE
Trade problem with a person involved that has nearly no dollars while selling and buying at the same time

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11318]
> Before the Trade:
> Vinshero got 311 dollar, I got like 0.7 dollar.
> He buys a Steam Truck and sells 22 Iron Ore (see screenshot).
> No dollar was transfered, I still got 0.7, he still got 311 dollar, no tax was paid.
> He manually transfered the dollar

![unknown](https://user-images.githubusercontent.com/25908592/52821638-b4120280-30af-11e9-85ba-9c8f3bc9423f.png)

(Trade failed was a SECOND try at trading that could not be fulfilled, not related!)

**Comment by mirasrael** [comment]
Needs more context.
Which tax was set?
What was expected trade result?

**Comment by mirasrael** [comment]
nvm, reproduced and fixed

**Comment by D3nnis3n** [comment]
Fixed.
