### ISSUE TITLE
Announced Feature for designating taxes into a specific bank account missing

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11312]

**Comment by D3nnis3n** [comment]
Obviously not a hot-fix, but i don't want it to be forgotten, considering it should have been in 8.0 as it was talked about quite some times.

**Comment by johnkslg** [comment]
Moving to 9

**Comment by johnkslg** [comment]
This should exist now.

**Comment by D3nnis3n** [comment]
It does.
