### ISSUE TITLE
Some first time users are met with a black screen, until restarting the game

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11322]
Happened to two players on my server
![85cac256-8bdc-47af-a444-1ca1c0177015](https://user-images.githubusercontent.com/431728/52825601-0c292300-3109-11e9-985e-44866ca81a94.png)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/11226

**Comment by elfl0rd** [comment]
Duplicate of #11226
