### ISSUE TITLE
User duplicated on minimap

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11326]
![image](https://user-images.githubusercontent.com/431728/52834818-5cb37700-312f-11e9-8cbc-017d724edbe3.png)

**Comment by SlayksWood** [comment]
Still an isuue 8.2.1. But it isn't clear how to reproduce it.
![unknown (2)](https://user-images.githubusercontent.com/45708377/60173351-36a58e00-9817-11e9-89c6-672e61c71b1b.png)

**Comment by SlayksWood** [comment]
Maybe It's also due to the zero point
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3329630/Player.log)
![image](https://user-images.githubusercontent.com/45708377/60174438-addc2180-9819-11e9-9d37-759012c05252.png)

**Comment by redwyre** [comment]
Did you exit the game cleanly, or did you kill it?

**Comment by gzatravkin** [comment]
@SlayksWood @beastyn 
Need some help on repro.

Can you grab video with repro? Also is duplication is only on minimap, or there are duplications of player models too? Is it possible to repro with user itself, or it always about other players?

**Comment by mirasrael** [comment]
@gzatravkin did you try to terminate game (non graceful shutdown)?

**Comment by gzatravkin** [comment]
@mirasrael yes, but still I wasn't able to reproduce it.

Anyway I added a line that ensures that player object will be destroyed after login.  
@SlayksWood Please let me know if you will see it again after PR 6057.

**Comment by SlayksWood** [comment]
Still an issue, just close game by Alt+F4:
![bandicam_2020-05-08_11-17-56-706](https://user-images.githubusercontent.com/45708377/81376821-f2f50380-910c-11ea-9e53-b176b25e406a.jpg)

**Comment by beastyn** [comment]
1554
appeared again
![bandicam 2020-05-19 17-16-19-804](https://user-images.githubusercontent.com/27898520/82326432-42351100-99f6-11ea-9976-df0c12404cb1.jpg)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4650387/Player.log)

**Comment by gzatravkin** [comment]
Not totally sure if this will solve the problem, but I added check to prevent one possible case of that issue in MinimapManager.cs
