### ISSUE TITLE
New patch causing MAJOR memory leaks

### ISSUE THREAD

**Issue by loglog7** [StrangeLoopGames/EcoIssues#11327]
Getting 5g [memory](https://imgur.com/42Gz4Bz) and 99% Cpu usage as soon as the game loads into a server. It can last from 10-30 minutes depending on who knows what. This needs to be fixed. The settings make no difference.

**Comment by elfl0rd** [comment]
also...
[Eco.gc.log](https://github.com/StrangeLoopGames/EcoIssues/files/2868267/Eco.gc.log)

**Comment by mirasrael** [comment]
Seems Aura related. @metachronism can you check it after switching to Aura 2?

**Comment by metachronism** [comment]
closing, memory was issue with 3rd party plugin.  CPU should be used 100%, thats what its for :P
