### ISSUE TITLE
Rubble frequently falling though ground and piling up on the surface

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11324]
Users are having performance issues which may be a cause, or a symptom
![image](https://user-images.githubusercontent.com/431728/52834518-fa0dab80-312d-11e9-83fe-706204bee8f6.png)

**Comment by elfl0rd** [comment]
hah... falling.
Just look at this rubble and mine position.
![default](https://user-images.githubusercontent.com/4980243/52845956-6fbb4c80-3119-11e9-8669-b39110ec3bc2.png)

**Comment by metachronism** [comment]
mostly fixed this with new method

**Comment by elfl0rd** [comment]
@metachronism in master? Checked, still happens.
