### ISSUE TITLE
[8.0.2] Wooden Elevator Call Post breaking room value

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#11320]
From Discord: 
I found the reason why rooms weren't getting recognized -- having a wooden elevator call post would treat the room as an industrial room, and negate all room value wherever the buttons are placed.

(OK - perhaps this may be a thing by design, but shouldn't it be fitted as general so that it doesn't break houses that use elevators?)

**Comment by Rakkeyal** [comment]
I am also having the same issue with Elevator Call Post removing all room value. I'd say that is not an intuitive problem.

**Comment by SlayksWood** [comment]
still an issue 8.1.3
![image](https://user-images.githubusercontent.com/45708377/56495450-7346c780-64fe-11e9-8574-5d5e99b6f6df.png)
![image](https://user-images.githubusercontent.com/45708377/56495471-88bbf180-64fe-11e9-87f0-bea559345d7f.png)

**Comment by SlayksWood** [comment]
8.2.6 Still an issue
Very uncomfortable given that the elevator doesn't change room to industry room

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/72144527-9b869700-33a9-11ea-848d-90577511521b.png)
