### ISSUE TITLE
Steam engine skinning bug-- static nut on rotating part.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11338]
![r](https://user-images.githubusercontent.com/4980243/52878622-234e2c00-316e-11e9-9c1d-e131c566b04c.gif)

**Comment by elfl0rd** [comment]
Still actual, lol

**Comment by keegan-o** [comment]
Check out this issue in the FBX @MilenkoTunjic ? Skinning/animation issues are tough across the maya/max gap.
