### ISSUE TITLE
Different speed bonuses on roads and ramps.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11337]
I thought that ramps=roads?

All ok

> Wheelbarrow, Small Wood Cart, Wood Cart, Skidsteer, Excavator
> dirt road - 1
> dirt ramp - 1
> 
> stone road - 1,2
> stone ramp - 1,2
> 
> asphalt road - 1,4
> asphalt ramp - 1,4

looks strange

> Steam Truck, Truck
> dirt road - 1
> dirt ramp - 1
> 
> stone road - 1,4
> stone ramp - 1,2
> 
> asphalt road - 1,8
> asphalt ramp - 1,4
> 
> Powered Cart
> dirt road - 1
> dirt ramp - 1
> 
> stone road - 1,3
> stone ramp - 1,2
> 
> asphalt road - 1,6
> asphalt ramp - 1,4

**Comment by SeanAtr0n** [comment]
some vehicles take advantage of smooth roads better than others

**Comment by SeanAtr0n** [comment]
misread
