### ISSUE TITLE
Lavish workspace: industry - broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11330]
increasing room requirements, but not decreasing resources consumption.

**Comment by jameshawkes** [comment]
It's also not clear from the description whether it is supposed to reduce the cost of the table, or the cost of recipes at the table.

**Comment by D3nnis3n** [comment]
Appliew to all lavish workspace talents.

**Comment by espoire** [comment]
Confirming that this applies to Milling too.

![image](https://user-images.githubusercontent.com/16272456/54410912-66db7d80-46bb-11e9-8aeb-a7ccb29518a0.png)
