### ISSUE TITLE
Electric planer description - "45m3 free volume in room" (de-facto - 150)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11335]
![default](https://user-images.githubusercontent.com/4980243/52876218-9902c980-3167-11e9-8029-cb27aed25195.png)
But de-facto, electric stamping press requiere 150! (5x6x5) free space in room only to place.
![20190215211646_1](https://user-images.githubusercontent.com/4980243/52876189-87212680-3167-11e9-865e-bd5379d8e361.jpg)
This situation is really painfull for new players.

**Comment by voyagebass** [comment]
I noticed this earlier on, but didn't see it as a bug. If you combine the Electric Planer with other tables that need much less room than they occupy (e.g. 25m3 for a 2-block table) then it will compensate the room requirement.
