### ISSUE TITLE
USER ISSUE: Bright light at end of long tunnel

### ISSUE THREAD

**Issue by botty05** [StrangeLoopGames/EcoIssues#11340]
**Version:** 0.8.0.2 beta

**Steps to Reproduce:**
Dig a long deep tunnel using ramps so 4 long then 1 deep. The tunnel is about 160 long

**Expected behavior:**
Just dark normal game

**Actual behavior:**
Bright white shining light 

**Do you have mods installed? Does issue happen when no mods are installed?:**
Bright white shining light

**Comment by redwyre** [comment]
This is just that chunks in the distance haven't loaded yet, and the skybox is bright during the day - even underground. If you wait the chunks should eventually load, but you can generally just ignore it.

I'm not sure what we can do to "fix" it, either modifying the skybox or having some kind of chunk placeholder around the edge of the loaded chunks.

**Comment by eliotcougar** [comment]
The way it can be done:
In addition to voxel terrain data, the server should also have some sort of rough "horizon elevation data" for every contact surface between chunks... This data will be much smaller in size, and can be transfered before the actual chunks are loaded...
Then the client just draws a set of opaque planes in the distance where the loaded and unloaded chunks meet...

Or it can all be done client side and cached to reduce the frequency of the issue...

**Comment by metachronism** [comment]
@SeanAtr0n did something for this
