### ISSUE TITLE
USER ISSUE: Connection Problem

### ISSUE THREAD

**Issue by Cryptogene** [StrangeLoopGames/EcoIssues#11342]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Not sure how to reproduce... 
8 re-connect's in just 1 hour =/

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? => No
Does issue happen when no mods are installed?:** => Yes
The following error message popped up:

Connection timed out

Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1ba1)
    Vendor:   
    VRAM:     8081 MB
    Driver:   25.21.14.1771
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.590768 ms
Client version: 0.8.0.3 beta
Thursday, February 14, 2019 5:45 PM
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Settings:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: CeibaSeedPackItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following icons: CeibaSeedPackItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_DirtPlace
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
BlockEffectsReceiver:SpawnBlockEffect(Vector3i, Int32, String)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
System.Func`3:Invoke(T1, T2)
Eco.Shared.Networking.RPCManager:TryInvoke(INetClient, Object, String, BSONObject, Object&)
Eco.Shared.Networking.RPCManager:InvokeOn(INetClient, BSONObject, Object, String)
Eco.Shared.Networking.RPCManager:HandleReceiveRPC(INetClient, BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_DirtRemove
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
BlockEffectsReceiver:SpawnBlockEffect(Vector3i, Int32, String)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
System.Func`3:Invoke(T1, T2)
Eco.Shared.Networking.RPCManager:TryInvoke(INetClient, Object, String, BSONObject, Object&)
Eco.Shared.Networking.RPCManager:InvokeOn(INetClient, BSONObject, Object, String)
Eco.Shared.Networking.RPCManager:HandleReceiveRPC(INetClient, BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_DirtDump
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
BlockEffectsReceiver:SpawnBlockEffect(Vector3i, Int32, String)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
System.Func`3:Invoke(T1, T2)
Eco.Shared.Networking.RPCManager:TryInvoke(INetClient, Object, String, BSONObject, Object&)
Eco.Shared.Networking.RPCManager:InvokeOn(INetClient, BSONObject, Object, String)
Eco.Shared.Networking.RPCManager:HandleReceiveRPC(INetClient, BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_SandRemove
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_SandPlace
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_BuildingPlace
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
World:SetBlock(Vector3i, UInt16, Byte, Boolean)
PredictBlockChange:SetBlock(Vector3i, UInt16, InteractionInfo, Byte)
InteractionManager:SendInteraction(InteractionMethod)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_BuildingDestroy
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
World:SetBlock(Vector3i, UInt16, Byte, Boolean)
PredictBlockChange:SetBlock(Vector3i, UInt16, InteractionInfo, Byte)
InteractionManager:SendInteraction(InteractionMethod)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: WoodBuildSfx
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
World:SetBlock(Vector3i, UInt16, Byte, Boolean)
PredictBlockChange:SetBlock(Vector3i, UInt16, InteractionInfo, Byte)
InteractionManager:SendInteraction(InteractionMethod)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: WoodDestroySfx
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
World:SetBlock(Vector3i, UInt16, Byte, Boolean)
PredictBlockChange:SetBlock(Vector3i, UInt16, InteractionInfo, Byte)
InteractionManager:SendInteraction(InteractionMethod)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_SalalPlantDelete
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_GrassPlantHarvest
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_GrassPlantDelete
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_PlantPlace
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_GrassRemove
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: BuildSfx
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: DestroySfx
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_StoneRemove
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_StonePlace
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NullReferenceException: Object reference not set to an instance of an object.
  at UnityEngine.GameObject.GetComponentInParent[T] () [0x00000] in <00000000000000000000000000000000>:0 
  at InteractionManager.SendInteraction (Eco.Shared.Items.InteractionMethod method) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Missing following icons: CeibaSeedPackItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Attempt to set pitch to a negative value in AudioSource::SetPitch ignored! This is only supported for AudioClips which are stored in an uncompressed format or will be decompressed at load time.
 
(Filename:  Line: 1392)

Block effects should have a pooled object component; please add it to the prefab: P_BigBlueStemDelete
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Block effects should have a pooled object component; please add it to the prefab: P_StonePlaceIronOre
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Block:BuildEffectsDictionary()
Block:HasEffect(String)
MapConfig:SpawnBlockEffect(Vector3i, UInt16, String)
MapConfig:BlockChanged(Vector3i, UInt16, UInt16)
ChunkGridView:UpdateChunks(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Connection timed out
```

**Comment by beastyn** [comment]
should br fixed 0.8.1.4. Please reopen if issue is actual
