### ISSUE TITLE
Server Crash On Login

### ISSUE THREAD

**Issue by Sephumbra** [StrangeLoopGames/EcoIssues#11348]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Having setup a private server, trying to connect to it crashes the server with the attached error message and the usual "EcoServer.exe has stopped working" message (No dump was generated, so I had to resort to taking a screenshot). The last thing that happened was that everyone was disconnected besides me (on the PC the server was being hosted from) while I was able to shovel dirt for about 5 minutes until it crashed with the same message. Since then no one (including me) was able to connect to the server.
The world can be downloaded here: https://drive.google.com/open?id=1n647KCyfVqFP2LTsqT4sRIY-59StuvdJ

![2019-02-16 00_57_37-d__steam library_steamapps_common_eco_eco_data_server_ecoserver exe](https://user-images.githubusercontent.com/33100859/52890747-cd39b280-3186-11e9-9934-4c3e75f53508.png)

**Expected behavior:**
Being able to log in without the server crashing.

**Actual behavior:**
See "Steps to Reproduce"

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by Rycoviac** [comment]
This was because of a downtime of the eco auth-servers. Our server did the same because of that.

**Comment by BlazeGuy2** [comment]
Auth server is back online, you should be able to run your server again.
