### ISSUE TITLE
Pipes fly over surface

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11341]
![default](https://user-images.githubusercontent.com/4980243/52883469-19cbc080-317c-11e9-88aa-7afa06e19cf5.png)

**Comment by keegan-o** [comment]
The closer to the ground they are the more awkward pipe ports have to be since they need some kind of rim/receiving part, which we don't want to be sticking into the ground or out of the meter space. So no plans to fix this.
