### ISSUE TITLE
USER ISSUE: Loading Eco 90%

### ISSUE THREAD

**Issue by jeezyrae** [StrangeLoopGames/EcoIssues#11343]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Load into any world

**Expected behavior:**
Loaded in

**Actual behavior:**
Stops at Loading Eco 90%

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by jeezyrae** [comment]
I tried emailing customer support and gave them all sorts of files but they just told me to report the issue in game.

**Comment by GophTheGreat** [comment]
Output log attached.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2883870/output_log.4.txt)

**Comment by beastyn** [comment]
Should be fixed. Please reopen is actual
