### ISSUE TITLE
USER ISSUE: server crashes during join attempt

### ISSUE THREAD

**Issue by codenox** [StrangeLoopGames/EcoIssues#11347]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
happend right after i got kicked out of the server due to invalid token?!:
I am trying to join my server

**Expected behavior:**
server password popup

**Actual behavior:**
server crashes with- 
system.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   at Eco.Plugins.Networking.Client.<Authorize>b__64_0(VerifyResult result, Exception error)

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by BlazeGuy2** [comment]
Our auth server is down at the moment, we are working to get it back up.

**Comment by codenox** [comment]
I see. Thank you for the fast response!
Will try it tomorrow again.
