### ISSUE TITLE
USER ISSUE: FPS drops after couple of mins

### ISSUE THREAD

**Issue by ArranChase** [StrangeLoopGames/EcoIssues#11357]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
 Running a Dedicated server on a i7 4820k CPU with 20GB ram and Nvidia 1050gti (4gb) and run also the client on the same PC, also my second PC (i7 6990) 8GB ram and Nvidia 1050gti(4gB) jave both after few mins a FPS drop from 60 FPS (vsync on) too below 30 fps after we do something like placing blocks, running around that makes chuncks load, do jobs on machines. 
After Reboot the FPS comes back at a 60 FPS again till couple mins of normal play and it tanks again.
Both PC's run Windows10 x64 SE Home edition (Europian editions).
The issue as stared with 0.8.0 as we didnt had this issue before the update.
Players connecting to my PC's (hosting a private game for friends) have different rigs with no FPS drops so it seems to be in my configuration of my PC, and not related to the dedicated server.
Also since i have the issue on 2 near identical PC's on where one does not run a dedicated server, it seems to be client related and not server related.

Also changing resolution or graphical settings does not seem to alter FPS, we tried 1980x1024 (native desktop resolution) with low/med/high and 1600x900 down too 1440 x 900 with each low/med/high setting and all have the same issue dropping from 60fps to sub 30.
vsync also does not seem to cause any differences in FPS rate once the drop appears.

Server with Client uses about on average 45% memory usage with 5 external clients and 1 local client, with an CPU usage of around 15%, while the GPU seems to be running around 50% usage with 80% of its memory used, what seems to be within its limits on 1980x1024 at high settings.
At lower settings these figures does not seem to change.

NVIDIA Systeeminformatierapport gecreëerd op: 02/16/2019 13:34:13
Systeemnaam: KELVINPC

[Beeldscherm]
Besturingssysteem:	Windows 10 Home, 64-bit
DirectX-versie:	12.0 
GPU-processor:		GeForce GTX 1050 Ti
Stuurprogrammaversie:	416.34
Driver Type:		Standard
Direct3D API versie:	12
Direct3D functieniveau:	12_1
CUDA-kernen:		768 
Kernklok:		1341 MHz 
Geheugengegevenssnelheid:	7008 MHz
Geheugeninterface:	128-bit 
Geheugenbandbreedte:	112.13 GB/s
Totaal beschikbaar grafisch geheugen:	14293 MB
Toegewezen videogeheugen:	4096 MB GDDR5
Videogeheugen systeem:	0 MB
Gedeeld systeemgeheugen:	10197 MB
Video BIOS-versie:	86.07.22.00.57
IRQ:			Not used
Bus:			PCI Express x16 Gen2
Apparaat-ID:		10DE 1C82 8C961462
Onderdeelnummer:	G210 0000

[Onderdelen]

nvui.dll		8.17.14.1634		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.14.1634		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.14.1634		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.14.1634		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.14.1634		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		25.21.14.1634		NVIDIA Workstation Server
nvWSS.dll		25.21.14.1634		NVIDIA Workstation Server
nvViTvSR.dll		25.21.14.1634		NVIDIA Video Server
nvViTvS.dll		25.21.14.1634		NVIDIA Video Server
NVSTVIEW.EXE		7.17.14.1634		NVIDIA 3D Vision Photo Viewer
NVSTTEST.EXE		7.17.14.1634		NVIDIA 3D Vision Test Application
NVSTRES.DLL		7.17.14.1634		NVIDIA 3D Vision Module
nvDispSR.dll		25.21.14.1634		NVIDIA Display Server
NVMCTRAY.DLL		25.21.14.1634		NVIDIA Media Center Library
nvDispS.dll		25.21.14.1634		NVIDIA Display Server
PhysX		09.18.0907		NVIDIA PhysX
NVCUDA.DLL		25.21.14.1634		NVIDIA CUDA 10.0.132 driver
nvGameSR.dll		25.21.14.1634		NVIDIA 3D Settings Server
nvGameS.dll		25.21.14.1634		NVIDIA 3D Settings Server

**Expected behavior:**
FPS drops is expected due too high graphical settings, lowering should raise FPS if the hardware woudnt be able to run those settings, yet lowering settings does not seem the have any effect, thus it seems to be caused by a other reason.

**Actual behavior:**
Regardless setting and resolution FPS keeps dropping after few minutes on both clients below 30 fps making the game very choppy and unpleasent to play

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by seccombew** [comment]
Closing as dupe
