### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by SKYMEE1** [StrangeLoopGames/EcoIssues#11358]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Click on Continue in the main menu.

**Expected behavior:**
Log in to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```
This is thee dump file.

--BEGIN DUMP--
Dump Time
01/15/2019 16:57:18

Exception
Exception: Exception
Message:Error in HousingTierDefinition at 15: Auf den Member 'Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])' kann nicht mit einem Instanzenverweis zugegriffen werden. Qualifizieren Sie ihn stattdessen mit einem Typnamen. (CS0176)

Source:Eco.ModKit

System.Exception: Error in HousingTierDefinition at 15: Auf den Member 'Eco.Gameplay.Housing.PlayerHousingManager.SetHousingTiers(Eco.Gameplay.Housing.HousingTier[])' kann nicht mit einem Instanzenverweis zugegriffen werden. Qualifizieren Sie ihn stattdessen mit einem Typnamen. (CS0176)

   at Eco.ModKit.RuntimeCompiler.HandleCompilerError(CompilerResults results)
   at Eco.ModKit.RuntimeCompiler.LoadOrCompileMods()
   at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done)

--END DUMP--

If this won't get fixed I will never play Eco again. It's the 3rd world not loading after an update. I am sick of doing everthing from scratch!

**Comment by D3nnis3n** [comment]
Was this loading up an old world? We made clear that we recommend a new world for 8.0, as there was no way to ensure migration works in every case.

**Comment by mirasrael** [comment]
Hi @SKYMEE1 
Is this issue still actual? Did you save your world backup before migration (just in case)? Can you upload your world save to Google Drive (or other file storage) and put link here?

**Comment by mirasrael** [comment]
Didn't have response on this issue for about 2 months and no similar reports. So closing it for now. Feel free to re-open if new details will appear.
