### ISSUE TITLE
No visible fireweed sappling after planting

### ISSUE THREAD

**Issue by GuyMonkey** [StrangeLoopGames/EcoIssues#11353]
After placing a fireweed seed on plowed ground there is no fireweed sapling shown. Ground looks empty until later plant growth state.

**Comment by beastyn** [comment]
8.2
Still an issue/
The model will appear at 13% maturity
![bandicam 2019-06-21 18-15-57-322](https://user-images.githubusercontent.com/27898520/59925133-d7c7c980-9450-11e9-9560-216d01a76535.jpg)

**Comment by keegan-o** [comment]
Was a weird scale problem in growth curve, fixed.
