### ISSUE TITLE
USER ISSUE: Invisible Stumps

### ISSUE THREAD

**Issue by Gromps** [StrangeLoopGames/EcoIssues#11359]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Chop down a tree.
2. Chop the stump.

**Expected behavior:**
The stump disappears and all is good with the world.

**Actual behavior:**
While the stump is 'gone', the collider or something seems to remain. I can place things where the stump was, but I cannot walk there. I can jump on top as though the stump is still there too. This is occurring for every single stump in my Single Player/private world. When I restart the world, the stump colliders do disappear and it 'fixes' the issue, however even after restarting the world and the game, and starting a new save, the issue persists. Every new stump chopped leaves an invisible stump that I can collide with and it's getting pretty frustrating :( I have not tried a world that I am not hosting myself though, so it may be *me hosting* my single player/private saves that causes the issue. I don't really want to join a public world though so ASAP when I have a friend available later tonight I will ask them to host and see what happens.

EDIT: I also wanted to add that this occurs with every type of tree that I've tried.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have no mods installed.

**Comment by SeanAtr0n** [comment]
Thought we fixed this on redwoods? @keegan-o

**Comment by SeanAtr0n** [comment]
confirmed this happens on firs

**Comment by keegan-o** [comment]
Palms, Firs, Spruce, Redwood fixed on master/staging.

**Comment by beastyn** [comment]
Oak and Saguaro cactus need the same fix, stump leaves collider.

**Comment by keegan-o** [comment]
Fixed at last for Saguaro and for Oak--

For the future, when fixing this first make sure the heirarchy has the collider for the roots under the bone_root gameobject, and also make sure that the Trunk component script it referencing it and not a collider placed elsewhere!
![image](https://user-images.githubusercontent.com/14983165/69097446-685c0300-0a0b-11ea-8bcf-282f11c3c522.png)

**Comment by keegan-o** [comment]
Fixed in staging.

**Comment by redwyre** [comment]
@keegan-o You should put this into on the Eco project wiki
