### ISSUE TITLE
USER ISSUE: House not valid

### ISSUE THREAD

**Issue by Mounk450** [StrangeLoopGames/EcoIssues#11350]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
me my friend play on a hosted server with pingserver.
we got some problem to log in since a few hours and now that we can, all of our building are suddenly become not valid. we have reseted it many time with no change

**Expected behavior:**
we have respected all criteria for our building since those work properly earlier today

**Actual behavior:**
we cant use any table inside them and have lost our skill point bonus from them

**Do you have mods installed? Does issue happen when no mods are installed?:**
we cant use any table inside them and have lost our skill point bonus from them : no mod installed !

**Comment by JamesTalon** [comment]
Simple fix, if you haven't figured out yet, is to remove a block from somewhere in the room and place it back. This should trigger the room check and fix the problem. Some times you may need to pick up a decoration and place it down, at least that is what happened to me.
