### ISSUE TITLE
USER ISSUE: Cart falling from the sky

### ISSUE THREAD

**Issue by GarbonYT** [StrangeLoopGames/EcoIssues#11356]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
(I don't know if this will happen every time)
1. Place a cart
2. Move away from the cart about 250 meters
3. Leave and rejoin
4. Walk back to your cart
**Expected behavior:**
The cart should stay where it was before.

**Actual behavior:**
The cart falls from the sky.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No there are no mods installed.

**Comment by elfl0rd** [comment]
refers to #11050

**Comment by beastyn** [comment]
Can't repo in 0.8.1.4
Sean have made some fixes.
