### ISSUE TITLE
Loosing Access to treasury - probably because of a new election?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11369]
I had access to treasury earlier (see left bottom part), but it's gone now. I don't know when exactly this happens, but it could be since the new election started. I should keep access to the treasury as long as i'm leader, it's hard to do any government contracts now.

![treasury](https://user-images.githubusercontent.com/25908592/52911584-f9982080-32a5-11e9-95bb-fc602b6755da.png)

**Comment by Quadbro** [comment]
tested that case, you do not loose leader's rights and access in any way connected with election...(

**Comment by D3nnis3n** [comment]
I'm not sure if it is because of the election, but don't have anymore hints either. But as you can see - despite i'm leader i'm not having treasury access, it's in the screenshot. Probably any other possible causes you could find?

**Comment by seccombew** [comment]
@D3nnis3n Please reopen if you can find reproduction steps,
