### ISSUE TITLE
[8.0.3] Iron pipes showing as boxes in a stockpile

### ISSUE THREAD

**Issue by DragonSupremacy** [StrangeLoopGames/EcoIssues#11366]
As seen in the screenshot, the stockpile is filled with iron pipes, yet the accompanying art in the stockpile shows crates (implying items being stored) instead of the pipe block shown pre-8.0

![20190217001112_1](https://user-images.githubusercontent.com/841990/52906281-ca9f9180-3248-11e9-9ba0-95b960799916.jpg)

**Comment by elfl0rd** [comment]
Intended behavior, this is temporary solution to prevent attach pipes from outside of stockpile.
