### ISSUE TITLE
USER ISSUE: stone doesn't break

### ISSUE THREAD

**Issue by Nuke21** [StrangeLoopGames/EcoIssues#11367]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
stone stairs that were places before your shit ass update no longer are breakable

**Expected behavior:**
fucking broke

**Actual behavior:**
doesn't fucking break

**Do you have mods installed? Does issue happen when no mods are installed?:**
doesn't fucking break

**Comment by elfl0rd** [comment]
"stone stairs"? or "stone"? lol.
attach screenshots.

**Comment by Deantwo** [comment]
Which patch? v0.8.0.0 or v0.8.0.3?

**Comment by BlazeGuy2** [comment]
@Nuke21 Need more info.  Refer to comments above.

**Comment by D3nnis3n** [comment]
Closing as of no information was given, reopen if it occurs again and you can provide further information.
