### ISSUE TITLE
EmptyBlocksCountAsWindows broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11368]
1) You would need to be able to craft a door at the Workbench when using this, as the Carpentry Table where you can craft doors needs to be in a room. Solution: Add a door to the workbench that is not effected by efficiency, just like the hewn logs.

2) If you activated this option it will correctly not recognize a room with holes. But as soon as you place something in there and have the room recognized once and then remove it again - you can remove **all** walls and it's still a room. So this seems to cause some mess. (Also housing point calculation no longer works correctly)

3) Pipes would need to be counted as not being a hole in the room - otherwise the room is not working either. (Solution: Make pipes acceptable for single holes, but not for complete structures)

4) Probably make missing walls directly in front of a store on height 2 not counting, so players could go on selling through walls. Or add some kind of shopfront wall where you can target the shop through, but counts as wall, that would be even cooler.

This feature is already in and should be fixed, as it's a great way to stop players from min-maxing their houses in a chessboard form like swiss cheese - which in turn increases trade and therefore boosts the economy.

OR at least remove it, but as long as it's there - it should work. It's a very useful feature. Don't forget that people that set this might just not really notice the bug. A perfect fix for a planned Bugfix and Performance Update.

**Comment by D3nnis3n** [comment]
Even worse: Once you activated that, even if deactivated afterwards - rooms stay broken, see this valid room:
![room](https://user-images.githubusercontent.com/25908592/52911855-03238780-32aa-11e9-8eb5-ba50070c0601.png)

**Comment by redwyre** [comment]
@D3nnis3n do we need a design decision on whether to keep or remove the option?

**Comment by D3nnis3n** [comment]
Should probably ask john, im not the right person to decide if there should be a Design decision.

**Comment by craig-jong** [comment]
You can go ahead and fix the option to get it working. There's a different discussion to be had about making it default to this behavior, though.
