### ISSUE TITLE
USER ISSUE: Connection Timeout an Webserver doesnt Work on Linux

### ISSUE THREAD

**Issue by mister-man** [StrangeLoopGames/EcoIssues#11364]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Start Server
Webserver doesnt work with Mono
Play some Time
Disconnect, but the server is still running

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by SlayksWood** [comment]
Do you have this problem now? Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information:
