### ISSUE TITLE
If Waste Filter fail - he block liquid.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11371]
As result - all production stopped.
Also if you use combustion generator with filter, you need hammer to fix network.

possible solution - add 3, "fallback" pipe from filter, sewage will flow to it if something fail.
Also option "block sewage\fallback sewage" will be nice.

**Comment by Splutty** [comment]
Having a similar issue. The Waste Filter being turned off because of blockage, or because it thinks it can't dump its compost (which half the time seems to be random, with plenty of space in connected storage), affects both the Blast Furnace and the Combustion Generator.

**Comment by tobyhine** [comment]
I had this problem - there is an on/off checkbox on the bottom right of the filter window, but it is far from obvious. If criteria are met to restart filter it should probably restart automatically, or at least be more obvious that the checkbox is the problem. Assume that button is the problem.
