### ISSUE TITLE
Wheelbarrow - unstable in tight places.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11379]
As far as I know - the Wheelbarrow is designed for bottlenecks, but can not be used in them.

![20190217204557_1](https://user-images.githubusercontent.com/4980243/52917801-94254d80-3300-11e9-8012-f822a603b8ee.jpg)
![20190217204154_1](https://user-images.githubusercontent.com/4980243/52917802-94254d80-3300-11e9-9793-cd7f74bbaa29.jpg)
![20190217204203_1](https://user-images.githubusercontent.com/4980243/52917804-94bde400-3300-11e9-8f02-80e6244b215e.jpg)
![20190217204311_1](https://user-images.githubusercontent.com/4980243/52917805-94bde400-3300-11e9-9ab2-2f433b7bc14b.jpg)

![r](https://user-images.githubusercontent.com/4980243/52922232-cd75b180-3330-11e9-92e1-54ae6459287c.gif)

https://youtu.be/w7Z5pF1N5BQ

**Comment by SeanAtr0n** [comment]
fixed in svn
