### ISSUE TITLE
USER ISSUE: Problem to renam title

### ISSUE THREAD

**Issue by Miaki22** [StrangeLoopGames/EcoIssues#11373]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1) create a title
2) Rename the title

**Expected behavior:**
Title is rename

**Actual behavior:**
The title keeps its original name

**Do you have mods installed? Does issue happen when no mods are installed?:**
The title keeps its original name

**Comment by Miaki22** [comment]
There aren't mods

**Comment by D3nnis3n** [comment]
Cannot reproduce. Could you upload a small gif / video?

**Comment by D3nnis3n** [comment]
Closing for no response in over 14 days.
