### ISSUE TITLE
Vechicles "stockpile" use old glass and framed glass model.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11370]
![20190217141427_1](https://user-images.githubusercontent.com/4980243/52912152-759e6280-32be-11e9-97a1-96eba7370fa6.jpg)

**Comment by elfl0rd** [comment]
Still actual.

**Comment by redwyre** [comment]
`StockpileMeshBuilder` only renders the first material of a block, needs to be updated to a `BlueprintRenderer`.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/8497
