### ISSUE TITLE
USER ISSUE: 2nd Time Stuck in Redwood in 2 Days

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#11375]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Chase a Bison to unrendered zone
2. Renders a tree where I'm standing
3./unstuck does not work and have to resort to cutting as much as I can and outside help.

**Expected behavior:**
Area where there is a redwood tree would push me out of it's space

**Actual behavior:**
traps me

**Do you have mods installed? Does issue happen when no mods are installed?:**
traps me

**Comment by SeanAtr0n** [comment]
seems like the real problem is chunk loading going slower than you can run
