### ISSUE TITLE
USER ISSUE: Bad ladder

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#11389]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Build a ladder out of lumber
2. Attempt to climb

**Expected behavior:**
Allow player to climb up like hewn log ladder

**Actual behavior:**
player cannot climb and instead falls down hole

**Do you have mods installed? Does issue happen when no mods are installed?:**
player cannot climb and instead falls down hole

**Comment by elfl0rd** [comment]
Work fine for me, you have video?

**Comment by Spaceferret42** [comment]
can get video this afternoon.
what it looked to me was happening was that the lumber ladder was being placed behind the desired block of air instead of in the same space.
try building the ladder going down from a house in the corner of the floor

**Comment by Spaceferret42** [comment]
Do you have an email i can send the video to the file is to big
but I have discovered that at times the ladder rather hewn log or lumber will instead of extending an existing ladder will instead place in the next block over

**Comment by elfl0rd** [comment]
You can upload it to any file or video hosting, e.g. Google Drive or YouTube.

**Comment by Spaceferret42** [comment]
https://youtu.be/Cp3BA5j8dAo

**Comment by Spaceferret42** [comment]
or https://drive.google.com/open?id=1I1b2hgIcLDHS7aO8NPoKdm15NzjjfXsC

**Comment by SlayksWood** [comment]
You need to bring aim point on the lower balk.
![image](https://user-images.githubusercontent.com/45708377/56563568-ad72a080-65b4-11e9-953e-d1581c299474.png)
I have no particular problems with the construction of ladder now. But when I first encountered the construction of ladder I had some problems.
Seems fixed.
