### ISSUE TITLE
You can pickup ramp using shovel.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11384]
But only one ramp, then you cannot select shovel.
Accidentally dug ramps... irritate.

**Comment by feildmaster** [comment]
How.... else are you wanting to pick up ramps? With a hammer? How in the world would that make sense?

**Comment by elfl0rd** [comment]
yes, with hammer, like roads.

**Comment by feildmaster** [comment]
That might make sense in the game, but how does that make sense in a realistic point of view? You're not gonna take a hammer to a stone/asphalt road in real life and try to move it. You're going to destroy it with a jackhammer and shovel it away to be recycled. (in the case of a stone road you're just going to shovel it out...)

**Comment by elfl0rd** [comment]
until you can install 1 ramp unit separately, accidentally digging up a ramp during ground work is extremely painful.

**Comment by feildmaster** [comment]
Why did you close this @elfl0rd? Am I missing some context?

**Comment by SlayksWood** [comment]
move to #11980
