### ISSUE TITLE
bridge building shows up as flooded in workbench

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1138]
![image](https://cloud.githubusercontent.com/assets/774628/23531134/c613630e-ff59-11e6-89f5-1a8bbf564c61.png)

**Comment by jscpowser** [comment]
I second this bug on 0.5.5.4 alpha. 

![eco-bridge-bug-1](https://cloud.githubusercontent.com/assets/14279517/26191668/b7f6fa5e-3ba6-11e7-88ef-c524197ce4c6.png)

![eco-bridge-bug-2](https://cloud.githubusercontent.com/assets/14279517/26191674/bafc852a-3ba6-11e7-98d4-b43299aca636.png)

**Comment by MarjieAVolk** [comment]
I'm not seeing this on staging right now
