### ISSUE TITLE
No tax when transferring to different accounts

### ISSUE THREAD

**Issue by JamesTalon** [StrangeLoopGames/EcoIssues#11388]
When attempting to transfer funds between accounts, if you click Transfer before clicking anywhere else after filling out the amount field, it will send the money tax-free (First image). Clicking elsewhere updates the taxes as expected otherwise (Second image).

This is the same issue, I think, as https://github.com/StrangeLoopGames/EcoIssues/issues/11271
![image](https://user-images.githubusercontent.com/38748529/52922298-53243d80-32ee-11e9-9266-cd995d334a03.png)
![image](https://user-images.githubusercontent.com/38748529/52922300-57505b00-32ee-11e9-9611-d79b94d29de6.png)
![image](https://user-images.githubusercontent.com/38748529/52922303-5b7c7880-32ee-11e9-99ee-d6bce4a11f2b.png)

**Comment by Quadbro** [comment]
Eco version?

**Comment by Quadbro** [comment]
and also the tax info in transfers are client-side only, you do not pass it to server, and it recalculates for you when you finished editing "Amount field"

**Comment by JamesTalon** [comment]
Sorry, newest version, 8.0.3, and I have full access to the target account. To avoid the tax, you need to keep the Amount field active, and then just click Yes, even though it is greyed out. This sends the money without paying the tax. The amount in the other account ends up the full untaxed amount

**Comment by Quadbro** [comment]
you have no tax between use/manage accounts
