### ISSUE TITLE
Bank and Registrar not have room requiments

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11387]
![default](https://user-images.githubusercontent.com/4980243/52921580-a4055780-3329-11e9-9a25-c15ca640a793.png)
![default](https://user-images.githubusercontent.com/4980243/52921582-af588300-3329-11e9-8717-87b6fff660bd.png)

**Comment by johnkslg** [comment]
Required modifying tech tree
