### ISSUE TITLE
Player stands and sits back down when choosing 3rd person view (even though they are seated all the time)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11382]
**Version:** 0.8.0.3 beta

to reproduce this, sit in a chair, and either press F5 or choose Third Person in Pullout for backpack

the following GIF shows me sitting down, rotating camera view, Pressing F5 (on/off) then finally choosing 3rd person from Pullout
![insta](https://user-images.githubusercontent.com/29383891/52918462-258bc400-32ef-11e9-867f-8984c9539670.gif)

Video if the Above Gif not clear enough
https://www.dropbox.com/s/a1yk571lfomzlei/Desktop%202019.02.17%20-%2019.52.00.02.mp4?dl=0

**Comment by SeanAtr0n** [comment]
fixed in 8.2
