### ISSUE TITLE
Amd Rx 580 8 GB Gpu and ram usage %100

### ISSUE THREAD

**Issue by TurkishPower92** [StrangeLoopGames/EcoIssues#11391]
When join game 2 or 5 minute's after gpu and ram usage rising %100 and playing slowly. if i do mining or logging game going more slowly. How i can fix that problem ?
System info:
İntel i7 8700 
20 gb ddr4 ram 2733 mhz
3x250 gb ssd raid 0
Rx 580 8 gb gpu
Win 10 pro lastest version.

**Comment by redwyre** [comment]
Can you attach a copy of your log file after experiencing the issue?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TurkishPower92** [comment]
i am attached you see admin ?

**Comment by redwyre** [comment]
@TurkishPower92 I don't see any attached log file

**Comment by TurkishPower92** [comment]
@redwyre because i am lost the file. i am copied here remember but is gone too :S

**Comment by redwyre** [comment]
Hi @TurkishPower92. we have release 8.1 which has a number of performance improvements, could you try it out and report back?

**Comment by mirasrael** [comment]
Closed due to no response and update to Aura 2 which should fix this issue.

**Comment by TurkishPower92** [comment]
i can try but not now thanks for help and answer's
