### ISSUE TITLE
Connection issue (connection timed out)

### ISSUE THREAD

**Issue by MineCraftael** [StrangeLoopGames/EcoIssues#11396]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Open the steam tab
2. Join a friends
3. Wait
4. Can't join they world

**Expected behavior:**
Join that world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Failed to connect - connection timed out.
```

**Comment by mirasrael** [comment]
Are you both behind NAT?

**Comment by mirasrael** [comment]
No response from user, closed
