### ISSUE TITLE
Laws: Unable to define a species

### ISSUE THREAD

**Issue by MikeW27** [StrangeLoopGames/EcoIssues#11407]
When I'd like to create a law for a specific species (or several), I can't select the species.
I assume it's due to the localization...
See screenshot, the species dropdown simply does not exist.
![image](https://user-images.githubusercontent.com/19435029/53008029-c4700780-3438-11e9-8c95-72ea0e70a4f1.png)

**Comment by Deantwo** [comment]
This trend to happen when you have added the trigger with a where statement, and then click the `+` to add a second trigger to the clause.

Can try to give reproductive steps if needed.
