### ISSUE TITLE
[Hosted Worlds] Constant Disconnects

### ISSUE THREAD

**Issue by ddrght12345** [StrangeLoopGames/EcoIssues#11404]
[Eco Disconnect Log.log](https://github.com/StrangeLoopGames/EcoIssues/files/2877941/Eco.Disconnect.Log.log)
Some worlds are seemingly unstable. No idea what to narrow in on, or a root cause.

Narrative:
- I spawned 1 world. Version 8.0.3. Constant disconnects (all players at once). Every 5-15 mins
Saw a post about someone else having disconnect issues also, so we figured it was an issue with the version.
- I downgraded the version to 8.0.2, and disconnects were gone. Hours with no interruptions (except an annoying issue with the login token changing for some reason... But that isnt for this report)
- Friends and I decide to reset the world. Given a new port, so I assume a new container (I assume you guys are even using containers at all) was used.
- New world, back to constant disconnects (still version 8.0.2). (Server ID: `29d76a99d68844888ca20f964e3afd8e` in case you want to check the exact instance)

---- -------------------------------------
Feedback: it would be nice if we could start/stop/restart the world. Not sure if that would actually fix anything in this case, but the IT part of me's first instinct is to restart it.

**Comment by mirasrael** [comment]
@ddrght12345 this problems seems related to 8.0.x, not 8.0.3 only.

**Comment by seccombew** [comment]
Fixed.
