### ISSUE TITLE
World Generation Problem on server

### ISSUE THREAD

**Issue by SpawnAuer** [StrangeLoopGames/EcoIssues#11400]
Since 8.0 i can't create a world larger then 100x100. every time it says" [18:49:26.614] [1] [ Info] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:World layer TunaCapacity voxels-per-entry (40) must evenly divide the world size ((2500, 2500))!
Source:Eco.Simulation

System.ArgumentException: World layer TunaCapacity voxels-per-entry (40) must evenly divide the world size ((2500, 2500))!
   at Eco.Simulation.WorldLayers.WorldLayerManager.InitLayers(LayerInitOperation operation)
   at Eco.Simulation.EcoSim.Regenerate() " 

how can i fix this?

P.s. no mods clean install

**Comment by elfl0rd** [comment]
do not use extremely low, or extremely high world height.

**Comment by SpawnAuer** [comment]
wich range can i use for larger maps?

**Comment by elfl0rd** [comment]
(this was my guess because you didn't attach your configuration file)
Also you can safely use standard (or slightly larger) height values even in large worlds.

**Comment by D3nnis3n** [comment]
You were using a world size of 250x250 which is not divisable by 4 without a remaining part. The values need to be equal and divisable by 4. 250/4 = 62.5. Working as intended.

**Comment by elfl0rd** [comment]
@D3nnis3n no, this is a different issue. But misconfigurstion, yes.

**Comment by SpawnAuer** [comment]
Ty it works.
