### ISSUE TITLE
[8.0.3] Indestructible block under water.

### ISSUE THREAD

**Issue by WindDash** [StrangeLoopGames/EcoIssues#11408]
![unknown](https://user-images.githubusercontent.com/17976842/53007894-3e0ff180-3449-11e9-804d-b36a5412d58b.png)
Coordinate: 188, 37, 736

World:
https://drive.google.com/open?id=1bf6kxgYxGLoVrLGPt-QCJntn-D_bL0UT

**Comment by seccombew** [comment]
Fixed.
