### ISSUE TITLE
Mousing over link in tutorials didnt work 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11418]
![image](https://user-images.githubusercontent.com/3536496/53035132-bde68d80-3442-11e9-9849-3c4da1b68ec8.png)
The workbench link, wouldnt display a tooltip (though the cursor did change)
Blocks the tutorial.

**Comment by D3nnis3n** [comment]
Can confirm, this tutorial is different since at least my last full QA pass.

**Comment by jthill** [comment]
It's happening for me in 8.0.6

**Comment by Spydarlee** [comment]
Still fixed for me as expected on master.

![Eco11418MasterCheck](https://user-images.githubusercontent.com/553695/54693875-3d897a00-4b1f-11e9-9282-45f4cb7d1d3b.gif)

**Comment by D3nnis3n** [comment]
Thought this should be in staging, cause master is now staging. Whatever.
