### ISSUE TITLE
/regenlayer having issues 8.0

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#11410]
Have had complains that /regenlayer is not regenning layers with 8.0.0 + but no one seems to have posted a bug on it.  i did try using it to regen an elk layer after my elk population suddenly crashed for some reason and the severer crashed and the world would not recover and I had to go to backup. I tried to regen the corn layer and although it did not crash nothing seemed to happen.  I expected to get corn back as it had been at creation but after running the command there was still 0 corn.  The same also happened when I tried Beans and Papaya.  I then tried a Redwood layer and it crashed the server again and it would not load again and I had to go back to backup again

**Comment by metachronism** [comment]
@craig-jong this command should be removed/deprecated probably, leaving to you...

**Comment by SlayksWood** [comment]
Command /regenlayer has been fixed here https://github.com/StrangeLoopGames/Eco/pull/4603
Regenerates a world layer, restoring it to the state it would be in if the world were newly generated.
