### ISSUE TITLE
Make crane usable

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11411]
Want this as fast as possible.
- [ ] 1) unlimited rope (for now - ~30 blocks, srsly? 1 stockpile range?)
- [ ] 2) change rope control from a mouse wheel for example on control and shift.
- [ ] 3) move 3rd view point to end of crane arrow (crane driver can see where hook!)

can implemented soon (usability\QoL improvements)
- [ ] 4) show "hook deep" indicator

- [ ] 5) realize crane vertical control (increase or decrease height)

**Comment by johnkslg** [comment]
@Quadbro want to give the crane some quality time?
