### ISSUE TITLE
Feature: discord game invites support

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11415]
![default](https://user-images.githubusercontent.com/4980243/53033631-87306780-3482-11e9-968c-5879bebb4eb4.png)
![default](https://user-images.githubusercontent.com/4980243/53033644-8f88a280-3482-11e9-896d-75c5b0284479.png)
![default](https://user-images.githubusercontent.com/4980243/53033654-96afb080-3482-11e9-9435-ded22fb783f8.png)

![default](https://user-images.githubusercontent.com/4980243/53033561-60723100-3482-11e9-9b48-24142f8d408e.png)

https://support.discordapp.com/hc/en-us/articles/115001557452-Game-Invites-and-Detailed-Status-Rich-Presence-

**Comment by johnkslg** [comment]
@redwyre investigate? Maybe its extra easy and can use the same codepath as steam invites.  We do have some discord integration already too.
