### ISSUE TITLE
USER ISSUE: no vision

### ISSUE THREAD

**Issue by NielsRoorda** [StrangeLoopGames/EcoIssues#11412]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Start new singleplayer game, wait for it to generate random world

**Expected behavior:**
show the character creation menu and the world

**Actual behavior:**
shows gui/hud with black background and a white dot that kind of looks like a star

**Do you have mods installed? Does issue happen when no mods are installed?:**
shows gui/hud with black background and a white dot that kind of looks like a star

**Comment by elfl0rd** [comment]
game restart is not help?

**Comment by NielsRoorda** [comment]
Yeah i restarted the game and that 'fixed' it

**Comment by elfl0rd** [comment]
Duplicate of #11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
