### ISSUE TITLE
Balance: Chainsaw costs the same as modern axe

### ISSUE THREAD

**Issue by SLaughterer** [StrangeLoopGames/EcoIssues#11414]
![image](https://user-images.githubusercontent.com/10670899/53033032-cc4f9c00-3478-11e9-93ba-6e8b3a84a161.png)

Client version 0.8.0.3

**Comment by elfl0rd** [comment]
Perhaps a chainsaw will require fuel when crafting?

**Comment by SLaughterer** [comment]
Chainsaw could use some more advanced materials, like circuits and maybe a steel gear? And fuel to repair maybe?
