### ISSUE TITLE
Hewing logs didn't give me any experience in my hewing specialty

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11421]
Also, it should say in the hewing recipe that I will get experience if I have the specific specialty.

**Comment by elfl0rd** [comment]
hm? https://github.com/StrangeLoopGames/EcoIssues/issues/11146

**Comment by craig-jong** [comment]
dupe https://github.com/StrangeLoopGames/EcoIssues/issues/11146
