### ISSUE TITLE
Users.eco changes all the time and causes a lot of annoyance

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11425]
![image](https://user-images.githubusercontent.com/3536496/53043990-c1d0da80-3457-11e9-952c-b23a96cc8535.png)
Let's add a new special config file which has stuff that will change on its own, and make this ignored by git. 

In this case, theres a few legit parameter that should be checked in, then the list of 'values' which should never be checked in. That value list can be moved to a new config (local config? something like that).

In that config, can also put a world size override, so we can have small worlds easily.

**Comment by metachronism** [comment]
server already supports this.  You can specify a different config directory with a command line parameter and then change the configs there to your liking.

**Comment by johnkslg** [comment]
Need it to be the default, so stuff that changes in normal development doesnt try to submit itself to git (same as all the .obj files and game.eco dont try to add themselves to git/svn)

**Comment by Spydarlee** [comment]
I think the default behaviour for this has changed now, @johnkslg? I used to get changes all the time but I haven't had anything recently?

**Comment by mirasrael** [comment]
Yes, it already fixed with templates.
