### ISSUE TITLE
Steam tractor exception 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11422]
[11:38:12] Exception when updating object SteamTractorObject: Sequence contains no elements
at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
at Eco.Mods.TechTree.SteamTractorSowerItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv)
at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved()
at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj)
at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action`1 action)
at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)

**Comment by konstantin90s** [comment]
There was unanswered issue with the same error before
https://github.com/StrangeLoopGames/EcoIssues/issues/8783#issuecomment-464483804
Wrote my report there recently

**Comment by D3nnis3n** [comment]
From konstantin90s;

> Met this problem now on 0.8.0.2 and 0.8.0.3 (haven't had this world and tractor before)
> When steam tractor with sower attached at first I got this in the log
> [02:15:31.835] [73] [ Info] [Eco] Exception when updating object SteamTractorObject: Object reference not set to an instance of an object.
> at Eco.Mods.TechTree.SteamTractorHarvesterItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv)
> at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved()
> at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj)
> at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
> at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
> at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)
> 
> and then every time you move a tractor log is flooded with exact same exception
> [02:24:04.956] [73] [ Info] [Eco] Exception when updating object SteamTractorObject: Sequence contains no elements
> at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at Eco.Mods.TechTree.SteamTractorSowerItem.BlockInteraction(Vector3i pos, Quaternion rot, VehicleComponent vehicle, Inventory inv) at Eco.Gameplay.Components.ModularVehicleComponent.OnVehicleMoved() at Eco.Gameplay.Components.VehicleComponent.ReceiveUpdate(BSONObject bsonObj) at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
> at Eco.Gameplay.Objects.WorldObject.ReceiveUpdate(BSONObject bsonObj)
> at Eco.Shared.Networking.NetObjectManager.UpdateObjects(BSONObject bsonRoot)
> 
> We tried to remove this tractor into inventory and place it again after this server seem to have entered half-crashed state and when you try to move this tractor red "disconnected" icon appears and after reconnection tractor stays in the same spot I placed it. After server restart it floods exceptions on movement again.
> 
> https://drive.google.com/open?id=1ouWvZlh4y6tIfzpIGNmcwq2QtM-AQz43 here's the world with this tractor if it helps to diagnose
> https://drive.google.com/open?id=1EbAKnYPLE77UKU1u0At8UyVJDicezrDn config files except network (default), actually everything that might be changed is world size and world tick cpu max set to 0,75 and parallel world object ticks enabled

**Comment by SeanAtr0n** [comment]
fixed & released

**Comment by SeanAtr0n** [comment]
why was this reopened?

**Comment by SeanAtr0n** [comment]
file a new issue if there is another problem, this exception was definitely fixed

**Comment by D3nnis3n** [comment]
Actually it seems not. Discord user reported having it, therefore reopened.

**Comment by SeanAtr0n** [comment]
where is that info then?

**Comment by D3nnis3n** [comment]
![Screenshot_20190329-010036_Discord](https://user-images.githubusercontent.com/25908592/55200389-2f41fa80-51be-11e9-8708-3d402e88ea9d.jpg)

**Comment by D3nnis3n** [comment]
![Screenshot_20190329-010305_Discord](https://user-images.githubusercontent.com/25908592/55200451-703a0f00-51be-11e9-9001-3652dee1e636.jpg)

**Comment by SeanAtr0n** [comment]
whoops, ok a different exception was fixed

**Comment by SeanAtr0n** [comment]
guess the exception is relatively harmless so we won't be hotfixing this, if you want to get rid of em before 8.1 edit Mods/Items/SteamTractorAttachment.cs to have:
```
                var stacks = inv.GroupedStacks.Where(x => x.Item is SeedItem);
                if (!stacks.Any())
                    return;
                SeedItem seed = stacks.First().Item as SeedItem;
```

**Comment by MrDKGE** [comment]
I will post it here as well and the link to the world.
https://dkge.nl/download/Game-2019-03-29-15.36.21.zip
![Capture](https://user-images.githubusercontent.com/32115695/55241553-9ce03c00-523b-11e9-9e77-7d589a52b3b1.PNG)
