### ISSUE TITLE
USER ISSUE: Webside is mixed in english and russia

### ISSUE THREAD

**Issue by FRITZ123456789** [StrangeLoopGames/EcoIssues#11426]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Open webside of server to propose a law, first everything will be in english, then propose a law and then half the website is in English the other half in Russia. Maybe it's important to say that infront of my username RU stands. I dont get that. I am from Germany

**Expected behavior:**
Website should be completly in English or much better will be a button where you can choose which language you want, if that is there already and I didn't saw it, forget that one

**Actual behavior:**
Parts of the site are in Russian. It makes it hard to propose a law

**Do you have mods installed? Does issue happen when no mods are installed?:**
Parts of the site are in Russian. It makes it hard to propose a law

**Comment by elfl0rd** [comment]
You are playing on server with russian lng selected?
