### ISSUE TITLE
Large tooltips with scroll bars dont widen like shorter ones

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11420]
This one doesn't make itself wide enough:
![image](https://user-images.githubusercontent.com/3536496/53035934-955f9300-3444-11e9-8bad-910be7fc8d6e.png)

Unlike this one, which doesn't need a scrollbar, and does make itself wide enough:
![image](https://user-images.githubusercontent.com/3536496/53035984-b7f1ac00-3444-11e9-9d12-ce1c711e0beb.png)

**Comment by johnkslg** [comment]
These would also benefit from a nice table formatter, but thats a larger task

**Comment by SlayksWood** [comment]
0.9.0 staging-1183
![image](https://user-images.githubusercontent.com/45708377/67564603-fce48580-f72b-11e9-80d0-59d467f94816.png)

**Comment by serpopov** [comment]
@SlayksWood looks like it is good now?
