### ISSUE TITLE
Issues with "pickup from stockpiles"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11423]
https://github.com/StrangeLoopGames/EcoIssues/issues/10064

1) you cannot grab building materials while holding hammer.

2) pickaxe grab wood instead of ores\stones
![default](https://user-images.githubusercontent.com/4980243/53040474-843d7300-3492-11e9-873f-13434ad21b5f.png)

**Comment by beastyn** [comment]
Axe is giving building blocks instead logs
![bandicam 2019-05-09 16-17-59-640](https://user-images.githubusercontent.com/27898520/57449777-37d62800-7276-11e9-830c-a606af373561.jpg)
