### ISSUE TITLE
[0.8.0.3] Issue with Baking/Advanced Baking

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#11439]
There is no link between Baking and Advanced Baking. It is not required to specialize in Baking to learn Advanced Baking and Baking provides no benefits to Advanced Baking as no recipes use products from Baking. Instead, Advanced Cooking is the prerequisite and all recipes require Yeast from Advanced Cooking. 

Here is a breakdown of all recipes to show. **Bold** means an additional specialization is required and _italics_ means an additional specialization provides efficiency benefits to the recipe: 

### Baking
Recipe to Learn Baking: **Advanced Campfire Cooking, Milling**, _Hewing, Bricklaying_
Flatbread: **Milling**	
Huckleberry Pie: **Milling,** _Butchering, Gathering_
Meat Pie: **Milling, Butchering**
Baked Roast: **Butchering**, _Gathering_
Baked Meat: **Butchering**
Baked Agave: _Gathering_
Camas Bulb Bake: _Gathering_

### Advanced Baking
Recipe to Learn Advanced Baking: **Advanced Cooking, Milling**, _Lumber, Bricklaying_
Bearclaw: **Advanced Cooking, Milling**
Bread: **Advanced Cooking, Milling**
Camas Bread: **Advanced Cooking, Milling**
Macaroons: **Advanced Cooking, Milling**
Elk Welling: **Advanced Cooking, Milling, Butchering**

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#724
