### ISSUE TITLE
Objectives Window Not showing All Players

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11432]
**Version:** 0.8.0.3 beta

Not sure why this is playing up, 
![snap4170](https://user-images.githubusercontent.com/29383891/53101682-2b1d2000-3522-11e9-8a22-d91fa4a808aa.png)
i thought it was just showing **online** players but that is not the case as /players works fine and the list is different
![snap4171](https://user-images.githubusercontent.com/29383891/53101857-7fc09b00-3522-11e9-8215-ede3a96db38c.png)

**Comment by SlayksWood** [comment]
From #14122
> (without players joined before restart?)
> ![изображение](https://user-images.githubusercontent.com/4980243/70625448-703a4c00-1c33-11ea-8982-cdad6375edf6.png)
> ![изображение](https://user-images.githubusercontent.com/4980243/70625536-a4ae0800-1c33-11ea-9195-0f02de4e1ed9.png)

**Comment by SlayksWood** [comment]
Seems fixed.
