### ISSUE TITLE
[8.0 Staging] - ChatCommandAttribute [Reopen]

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#11431]
This issue is still not fixed even though it's marked as fixed.

https://github.com/StrangeLoopGames/EcoIssues/issues/11073

**Comment by D3nnis3n** [comment]
Close for reopening of https://github.com/StrangeLoopGames/EcoIssues/issues/11073

**Comment by ClayC90** [comment]
Thanks
