### ISSUE TITLE
Opening Minimap quadruples network tick time

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1144]
~5ms -> 20ms on an fresh 100x100 world will add up quickly w/ multiple players

Should be room for improvement... ideally we just want to pull the last changes after a given time from a sorted list of changes

**Comment by metachronism** [comment]
bandwidth goes up by 4x too

**Comment by SeanAtr0n** [comment]
I reduced this a bit but we still need to have the main thread pack all the object updates into a queue clients can quickly pull from, pushing that to beta.

**Comment by SeanAtr0n** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/2523
