### ISSUE TITLE
8.0.3: Disconnect upon shift dragging resources

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#11442]
Disconnect log: https://pastebin.com/05TG5tt9

Had a disconnect just now. Player reported moving items between stockpiles with limestone, granite and gold ore in them to fill up a 2nd stockpile with. After the move, gold ore appeared not to have moved to the destination. Relevant lines in the log start at line 565 and onward

**Comment by SlayksWood** [comment]
Dragging objects with Shift has been changed in 8.2.0. If it happens again, reopen please
