### ISSUE TITLE
USER ISSUE: Dont see my person

### ISSUE THREAD

**Issue by digruberg** [StrangeLoopGames/EcoIssues#11440]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
First start the game
Enter to default game server

**Expected behavior:**
Black screen with blured land down

**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by elfl0rd** [comment]
game restart help for you.

**Comment by elfl0rd** [comment]
Duplicate of #11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
