### ISSUE TITLE
8.0.3: Server-wide disconnect upon entering vehicle

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#11447]
See included log: https://pastebin.com/zerAfHBi

Relevant log lines from 386 and onward; player reported entering a vehicle, server UI hung and proceeded to kick everyone off with packet parsing errors and mount spots for a vehicle (steam truck) failing

**Comment by SeanAtr0n** [comment]
fixed the vehicle errors, although I doubt they caused the disconnects
