### ISSUE TITLE
Balance: too many stone at mid\late game

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11444]
In mid\late game their consumption is low enough that the by-mined stone becomes a problem. For example, a lot of granite with gold mines.

**Comment by Conchipedia** [comment]
we need more things to be made from Excess stone, in my Mining, i have quite a few Workbenches that are making 1000's of stone but are never linked to any storage, so its just sitting in Limbo somewhere

**Comment by eliotcougar** [comment]
Maybe the upcoming change that makes loose stone turn into blocks again can alleviate the issue somehow... Don't know if it's gonna affect stone stored outside of a stockpile... If it does, you would be required to get rid of excess stone from your ore excavation business by piling it nearby in a huge mountain, like in the real world...

Bottomless void pocket dimension in workbenches will be abused if the whole crafting workflow is not changed...

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#723
