### ISSUE TITLE
All users gained experience got lost serverwide.

### ISSUE THREAD

**Issue by disfated** [StrangeLoopGames/EcoIssues#11446]
We installed a mod for tailings utilization (quite primitive craft transforming Tailings to Concrete) on our server. Some time after that all users lost their accumulated experience (needed to get next star). Had this occasion several times. After removing the mod experience stopped being gained. Somehow it got fixed soon afterwards.

Eco 8.0.1+
Save data: https://yadi.sk/d/RFw-itt38DSiIw
Mod: https://yadi.sk/d/MKLq4Mzx35VRwg

**Comment by Deantwo** [comment]
Has the issue happened without the mod?

Bugs caused by mods alone likely won't get any attention by devs. I suggest you ask the modder that made the mod.

**Comment by disfated** [comment]
This issue is intended for @mirasrael 
He's in touch with server owner.

**Comment by SlayksWood** [comment]
Could not reproduce. If it happens again, reopen please.
