### ISSUE TITLE
USER ISSUE: If waste filters run out of room to store compost, they will never turn back on after storage issue fixed

### ISSUE THREAD

**Issue by crusnak1** [StrangeLoopGames/EcoIssues#11449]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**

Attach 3 waste filters to output of blast furnace. Put tiny stockpile near waste filters and not have any other storage available to them. Run blast furnace until compost generated fills the tiny stockpile. At this point a message indicating no more room for waste filter output is available and will shut down the blast furnace. Clear the compost from the tiny stockpile and the process will not restart. The only way to currently fix the backup is to pick up each waste filter and place back.

**Expected behavior:**

As soon as there is available storage, the backed up process should start back up without external intervention.

**Actual behavior:**

Process does not automatically restart once available storage is fixed.

**Do you have mods installed? Does issue happen when no mods are installed?:**

No

**Comment by elfl0rd** [comment]
looks partially refer to #11371

**Comment by BlazeGuy2** [comment]
Fix should appear in 8.1.0 if PR is merged in.
