### ISSUE TITLE
USER ISSUE: Fish Trap not placeable under water

### ISSUE THREAD

**Issue by Irawulf** [StrangeLoopGames/EcoIssues#11452]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
try to place a fish trap in the ocean, a lake or river

**Expected behavior:**
you should be able to place it under water

**Actual behavior:**
an error message says "object can not be placed"

**Do you have mods installed? Does issue happen when no mods are installed?:**
an error message says "object can not be placed"

**Comment by elfl0rd** [comment]
Duplicate of #10849
