### ISSUE TITLE
0.5.5 alpha staging 0aef2823 - Crafting carpentry skill book requires carpentry

### ISSUE THREAD

**Issue by p3terl** [StrangeLoopGames/EcoIssues#1145]
Version: 0.5.5 alpha staging 0aef2823

![staging dilemma](https://cloud.githubusercontent.com/assets/13457101/23582455/be057ddc-012a-11e7-8e58-ee2a7be33e6c.jpg)

To craft the Carpentry skill book, you'll need a hammer.
A hammer requires boards, which can be crafted with woodworking, which is a carpentry skill.

So to craft the skill book, you need the actual skill already.

**Comment by daveSparhawk** [comment]
yeah i cant find anything that GRANTs th hammer. i cant get into a number of things without boards now.

**Comment by craig-jong** [comment]
This is, in fact, a bug. Nothing is going to grant a hammer anymore, so the recipe for hammer needs a change.

**Comment by craig-jong** [comment]
This is fixed in the latest staging
