### ISSUE TITLE
USER ISSUE: Fish traps catch fish when placed on land

### ISSUE THREAD

**Issue by Irawulf** [StrangeLoopGames/EcoIssues#11453]
![20190221225632_1](https://user-images.githubusercontent.com/47475999/53204619-5724c800-362c-11e9-9817-bda9a343674f.jpg)
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Place a fish trap on land. 
(Select a place where the map shows fish)

wait a couple of hours (or sleep)

**Expected behavior:**
there should not be any fish on land to be caught on land

**Actual behavior:**
the trap manages to catch fish

**Do you have mods installed? Does issue happen when no mods are installed?:**
the trap manages to catch fish

**Comment by elfl0rd** [comment]
Duplicate of #5818
