### ISSUE TITLE
[8.0.4] /leader doesn't work again

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11459]
![treasury](https://user-images.githubusercontent.com/25908592/53249895-82a1c400-36b9-11e9-83a2-cc4fb8019051.png)

**Comment by D3nnis3n** [comment]
Do have access to treasury though, totally weird:
![treasury](https://user-images.githubusercontent.com/25908592/53250312-75d1a000-36ba-11e9-8d0e-dbcf81aa04eb.png)

**Comment by seccombew** [comment]
@Quadbro  Hey Mike, @D3nnis3n ran QA on this fix and found that "/leader is fixed, but still has problems- can now set taxes again, but no longer have Access to treasury at all."
