### ISSUE TITLE
Water Input and Sewage output periodically not needed for table work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11456]
![unknown](https://user-images.githubusercontent.com/4980243/53214899-5ce7d100-365f-11e9-803e-6c29ff62e233.png)
![unknown](https://user-images.githubusercontent.com/4980243/53214904-63764880-365f-11e9-83e5-dc98cc6c6bdb.png)
Got it in unity after loading save, BUT periodically got it at release without server restarts.
https://www.dropbox.com/s/wz6wiwme5chbbv5/Storage.zip?dl=1

**Comment by MaxInertia** [comment]
Close relation to #11272

**Comment by elfl0rd** [comment]
no, it this case no any special set-ups.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/53457335-e3493d80-39e6-11e9-9544-0d306d0b6f1f.png)
I cant find this failing oil refinery @elfl0rd , what coords?
And in my local tests its working

**Comment by YoShIWoZ** [comment]
I have had this happen many times.
If you put a workbench near the pipeintake to a blast furnace, it will splash water from the pipe, even though it's not connected to the workbench (obviously). This will make the blast furnace say that it has no water, but it will still work properly. Thereby you can craft using a blast furnace without making any sewage pollution.

**Comment by elfl0rd** [comment]
there is one oil refinery in the world :D in desert.

**Comment by johnkslg** [comment]
Fixed!
