### ISSUE TITLE
USER ISSUE: Projects using tables requiring electric power still consuming power if halted

### ISSUE THREAD

**Issue by crusnak1** [StrangeLoopGames/EcoIssues#11450]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**

Setup an electric machinist table and combustion generator. Fuel the generator and choose a project on the table with insufficient material to complete. Ensure it begins the process with at least 1 item. Once halted, the table will still require power causing the generator to remain on and consume fuel until depleted.

**Expected behavior:**

Halted projects should not consume any power.

**Actual behavior:**

Halted projects consume power while doing nothing.

**Do you have mods installed? Does issue happen when no mods are installed?:**

No

**Comment by elfl0rd** [comment]
looks refer to #11213 and #11268

**Comment by beastyn** [comment]
Was tested in 0.8.1.3
When table is not working the generator is not consuming fuel. So closing.
