### ISSUE TITLE
USER ISSUE: Regular disconnect.

### ISSUE THREAD

**Issue by Pomega132** [StrangeLoopGames/EcoIssues#11451]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
I have a good connection, but any time, I'm disconnect from server without any reason. 

**Expected behavior:**
Not disconnect.

**Actual behavior:**
Regular disconnect.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No.

**Comment by D3nnis3n** [comment]
Should be fixed in 8.0.5.
