### ISSUE TITLE
Text about "newline" in server panel shows incorrectly.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11457]
(medium - confusing "new" server owners)
![default](https://user-images.githubusercontent.com/4980243/53245157-fe9e0b00-36bd-11e9-95f3-126cf84e8516.png)
![default](https://user-images.githubusercontent.com/4980243/53245164-05c51900-36be-11e9-8c22-f20a871784ae.png)

![default](https://user-images.githubusercontent.com/4980243/53245028-a23aeb80-36bd-11e9-9acb-147385729b92.png)
https://crowdin.com/translate/eco-by-strange-loop-games/25/en-ru#50446
`A long description of the server to display when selected in the server browser. Use \\n for line endings. Max 500 characters.`

**Comment by Quadbro** [comment]
@Spydarlee tested it, it seems like we loose some sort of backslash escaping mechanics by localization process, we could replace that text ('\n") to smth like "default new line separator" , etc, or we can debug and find where and why "\\n" is loosing it's escape power by operations on target string
