### ISSUE TITLE
USER ISSUE: Biksss

### ISSUE THREAD

**Issue by BIksss** [StrangeLoopGames/EcoIssues#11466]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Token is invalid.</size>
```

**Comment by elfl0rd** [comment]
License copy?
Steam or standalone version?
Can you login on the [SLG website](https://ecoauth.strangeloopgames.com/login)?

**Comment by D3nnis3n** [comment]
Please update to the latest version and report back if the issue persists.
