### ISSUE TITLE
Many repeated code blocks in User Management

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11463]
Didnt get to review this, but there are many functions in UserManager that have very similar code. 
 Refactor these function to avoid copy-pasted code.
Ban
Whitelist
Admin
RemoveAdmin

I would make each of these functions instead pass an Action or Func into a helper function.

**Comment by redwyre** [comment]
They're actually all different, I originally tried to combine them but it got messy
