### ISSUE TITLE
negative prices not possible in shops

### ISSUE THREAD

**Issue by xtreampb** [StrangeLoopGames/EcoIssues#11461]
I'm unable to set my shop price to be negative for my items.

applicable use case:

I offer to dispose of people's tailings for them.  People should pay me to give me tailings.  I should be able to set my price to -10, deducting from their account of choosing and depositing into the account setup by my store.  Was tested on vanilla server running version 0.8.0.3 in a vanilla client.  Can not type '-' key to set it to negative or press the minus (-) key in the UI to drop price lower than 0

**Comment by elfl0rd** [comment]
also not bad if we can have any additional "negative price" indicator.
