### ISSUE TITLE
USER ISSUE: FPS drop when reaping grass

### ISSUE THREAD

**Issue by AndyClausen** [StrangeLoopGames/EcoIssues#11473]
**Version:** 0.8.0.3 beta

This is while playing on a server hosted on my friend's computer. Note that only the player doing the reaping is getting big drops in MP. Other players seem to get minor drops, but nothing too annoying.

I noticed there's a slightly similar issue about FPS drops with grass in general, but this is specifically when you reap - otherwise it runs fine.

Some specs, in case it helps:
16GB DDR4
Ryzen 7 1700
GTX 1070 SC

**Steps to Reproduce:**
1. Equip a scythe
2. Cut any tall grass
3. Notice the FPS drop (in my case, 50\~60 to 20\~30)

**Expected behavior:**
It should've run the mediocre falling animation without lag in any way.

**Actual behavior:**
Instead it caused massive FPS drop for the player cutting.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I do not.

**Comment by johnkslg** [comment]
Boosted to high for perf focus

**Comment by seccombew** [comment]
@D3nnis3n Can verify and find repro case?

**Comment by D3nnis3n** [comment]
I can reproduce this in the jungle, where my fps are already as low as 25.
Reaping grass or plants there causes a drop to 15, especially on the last hit where the plant vanished, that one is clearly delayed.

**Comment by D3nnis3n** [comment]
On Grasslands it nearly not noticeable for me, though, especially when nothing is built there and i get "steady" 40 fps.
