### ISSUE TITLE
USER ISSUE: Unable to see anything

### ISSUE THREAD

**Issue by Kessah** [StrangeLoopGames/EcoIssues#11476]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Login to a server.	

**Expected behavior:**
Shown me an avatar, anything on screen other than the selection buttons.

**Actual behavior:**
Shows selection buttons, but no actual graphics.  No character, no terrain just a black screen.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Shows selection buttons, but no actual graphics.  No character, no terrain just a black screen.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/11226

**Comment by D3nnis3n** [comment]
Would you be able to contact me on discord so we could get a way to reproduce this issue? Add me on Discord via D3nnis3n#2053
