### ISSUE TITLE
USER ISSUE: disconnect or unable to connect to  a server

### ISSUE THREAD

**Issue by Elyndir** [StrangeLoopGames/EcoIssues#11474]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Bonjour,

J'ai pris un serveur privé sur 4netplayers j'y  est  jouer un tout petit petit avec quelque déco  reguliere et depuis je ne peux meme plus m'y  connecter ce me remonte une conexion time out

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Failed to connect - connection timed out.
```

**Comment by Elyndir** [comment]
voici l'erreur que je rencontre 👍 
<size=150%>Connexion échouée</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   
    VRAM:     4043 MB
    Driver:   23.21.13.9135
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.639037 ms
Client version: 0.8.0.3 beta
Thursday, February 14, 2019 5:45 PM
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Settings:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11548
