### ISSUE TITLE
Eco.Shared rebuilds everytime

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11477]
This happens due to the fast build check being disabled:
![image](https://user-images.githubusercontent.com/3536496/53309124-e7e0eb00-385a-11e9-8446-9d4be213d5b5.png)

It's especially problematic because it increases iterations when working on the server significantly, every build of the server requires a build of the client (while previously, I could quickly build the server and disconnect/reconnect the client without stopping it or building).

Let's move the version stamp process to another process? Or make it explicit in jenkins somehow? 
High priority because it affects build iteration time a lot.

**Comment by metachronism** [comment]
fixed
