### ISSUE TITLE
USER ISSUE: Connection timed out

### ISSUE THREAD

**Issue by isaiasteixeira** [StrangeLoopGames/EcoIssues#11472]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
Just  connecting to any server will causes me to disconnect

**Expected behavior:**
connection timed out

**Actual behavior:**
The following error message popped up:Connection timed out

```
<size=150%>Connection Failed</size>

Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:Connection timed out

```
<size=150%>Connection Failed</size>

Connection timed out
``` i have tried steam slg and fixing with fireawall nothing is helping

**Comment by isaiasteixeira** [comment]
Btw i have no mods installed

**Comment by beastyn** [comment]
Sometimes this is hapenning.
I will collect few scenarious here
1) Connect and play
2) Then quit with Quit button
3) Load client again
4) Try to connect to the world.
Connection failed

**Comment by beastyn** [comment]
@Dennis could;t connect to the servers hosted by me and Kirill

**Comment by mirasrael** [comment]
It may happen if no one has external IP and NAT allocates new pair of IP:Port for every connection, so NAT Punch Through fails in this case. It often happens with mobile internet.

**Comment by dennis** [comment]
@beastyn: Please dont use @dennis unless you mean to notify me

**Comment by SlayksWood** [comment]
@isaiasteixeira 
Relay server was added in 8.3.0. Which solves many connecting issues. If it happens again, please reopen.
