### ISSUE TITLE
Huge Performace issue with Law with Craft Condition and Play hours

### ISSUE THREAD

**Issue by manureini** [StrangeLoopGames/EcoIssues#11471]
Hello ;)

I debugged now some hours a server which had world object tick times from around 10000ms.
![capture](https://user-images.githubusercontent.com/1554111/53293305-9e988900-37d1-11e9-8e10-1f0c09de204a.PNG)

This Law is the reason of the extreme performace issue.

The craft event is called very often and lots of actions are created because in `CraftingComponent.ProcessWorkOrders` the property `order.AvailableWork` is creating all these  `this.CreateCraftOneAction().CanApply()` Actions.
These Actions are using `actionPreventers` which takes lots of performance if there is some data like Play hours which has to be read from the database.

There are no performace issues when the law only checks the Campfire Cooking Level.

This maybe relates to #11405 - High CPU Spikes.

**Comment by lordmampf** [comment]
tested with Version 0.8.0.3 and 0.8.1.0 beta master-46e4177e debug*

**Comment by beastyn** [comment]
Should ve fine in 9.0
