### ISSUE TITLE
USER ISSUE: Timed Out Disconnects sometimes create physical copies of the player

### ISSUE THREAD

**Issue by MrSpess** [StrangeLoopGames/EcoIssues#11475]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Get timed out (happens every 5-10 minutes)
2. Randomly there's a physical copy of the player, standing doing nothing. I also noticed that the copy/copies share the animations when you swing your axe, change tools etc.

**Expected behavior:**
Do nothing when you rejoin

**Actual behavior:**
Created a physical copy of the player. This happened to another player in our server too.
Screenshot of the copies is attached
![copies](https://user-images.githubusercontent.com/47948451/53302446-241e4680-386f-11e9-9c3e-3cbf1dfcb962.png)
. They appeared one by one randomly

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed. The game is vanilla. 
EDIT: We managed to fix the disconnect issue by increasing read timeout and write timeout from 1000 to 10 000.

**Comment by beastyn** [comment]
Should be fixed with 0.9
