### ISSUE TITLE
No "irreversibility warning" in specialization confirmation window.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11478]
My comment there - https://github.com/StrangeLoopGames/EcoIssues/issues/10285 is ignored.

> @craig-jong In this case, you need to add an irreversibility warning to the confirmation window.
Otherwise you receive ALOT of whimpers after update.

But as i see, "new" behavior, really confuse new and old players.
![default](https://user-images.githubusercontent.com/4980243/53321788-79e40480-38ea-11e9-9069-0787c366858c.png)

Especially those who have long played in Eco and used to the old behavior.
In addition, the network has a lot of manuals dedicated to <0.8, which brings additional confusion.

**Comment by Deantwo** [comment]
Manual? You mean the wiki?

**Comment by elfl0rd** [comment]
Steam guides, forums, etc.

**Comment by Deantwo** [comment]
The dialog could look a lot better too.
Have the skill's name be bold and colored, maybe even add the skill's icon appear on the dialog.
That should help preventing accidentally picking the wrong skill.
