### ISSUE TITLE
Store lists need headers for buying and selling

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11470]
![image](https://user-images.githubusercontent.com/3536496/53292105-a70da700-3772-11e9-9516-a9fa3da7dfea.png)

**Comment by johnkslg** [comment]
Not clear which is which anymore since they disappeared

**Comment by DragonSupremacy** [comment]
Will this include the option to re-enable durability in stores as reported in #11245? Setting up repair stores as a smith is a pain without it

**Comment by tehflambo** [comment]
@DragonSupremacy I've had success enabling durability in stores doing the following:
- add item <ie. iron pickaxe> to store, submit
- click icon for added item, opens box to select another item. change nothing, just click ok/submit
- durability field now visible and configurable, defaults to -1

I've had some of my store items not respond to this workflow, but I haven't tested why not. I have a sell order for iron pickaxes with a durability field visible, but a buy order for same with no field.

Other items with durability do respond to this workflow, ie. my steel pickaxe buy order does have a durability field using this workflow/workaround

**Comment by johnkslg** [comment]
Yes it should! @Quadbro two for one deal and fix that too?

**Comment by elfl0rd** [comment]
one @Quadbro for fix them all...

**Comment by johnkslg** [comment]
As prophecy has foretold.

**Comment by Quadbro** [comment]
Sure, that's just an init bug. np
