### ISSUE TITLE
Server throws exception on user connect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11485]
![image](https://user-images.githubusercontent.com/3536496/53375382-f3dab480-390f-11e9-80d6-4f9de690c323.png)
It recovers fine, but this disrupts debugging. Do you know what the cause is? Can we use non-excepting functions?

**Comment by metachronism** [comment]
just uncheck the box

**Comment by mirasrael** [comment]
Seems like an error during connection to eco auth server (it probably was temporary unavailable). And it is a part of how Web Core Framework is working. So nothing we can really change (except framework). So probably best way is to follow @metachronism solution :)

**Comment by johnkslg** [comment]
Ok, there was another one I couldnt uncheck the box on. Ill file a separate bug for that.
