### ISSUE TITLE
USER ISSUE: Chopping down trees bug. really annoying one

### ISSUE THREAD

**Issue by allexander53** [StrangeLoopGames/EcoIssues#11487]
**Version:** 0.8.0.3 beta

**Steps to Reproduce:**
1. Chop down tree
2. Interact while it is falling / chopping on separate parts (with each other, water, yourself - mainly movements +chopping making it bugged/freeze which require dc)
3. It is getting bugged and wont let you do anything
4. Trees disappear chopped ones after some time(green)

**Expected behavior:**
chop down cut collect

**Actual behavior:**
chop down, get bugged sometimes after taking every green bit to your hands and its getting bugged again and again. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
chop down, get bugged sometimes after taking every green bit to your hands and its getting bugged again and again.

**Comment by allexander53** [comment]
It happens all the time

**Comment by stbadreturns** [comment]
happens to my entire server it like you shop a tree down go to harvest it and it ether becomes uninterractable  or just vanishes.... if u disconnect and reconnect it will work again but can happen right on the next hit with your hatchet.

**Comment by Litonius** [comment]
I was searching for this bug because I've been experiencing it ever since the last 2-3 version (8.03-8.0.5?) and I stumbled upon this. I'm playing on a singleplayer world and as I cut down trees (Ceiba, in this case.) halfway through chopping them up, sometimes I come back to non-chopable parts being left until I close and reload my game, at which point I can chop the rest. It doesn't appear to happen to the "fully-chopped" slices that are green, but can happen if you leave yellow segments unchopped for any random interval where the physics have stopped and the log is laying still.

**Comment by SlayksWood** [comment]
@allexander53 @stbadreturns @Litonius 
Do you have this issue in the latest versions of the game? I remember that this issue was very irritable in one time, but now I don’t have it.

**Comment by beastyn** [comment]
@SlayksWood I`be met this one today with 0.8.1.4.

1. Chopping tree
2. One part was yellow but I can't chop it down
3. After sometime this part became untargetable.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3128658/output_log.txt)

![bandicam 2019-04-29 23-10-04-780](https://user-images.githubusercontent.com/27898520/56917554-374ecc00-6ad5-11e9-8f28-9de9c2b30109.jpg)

**Comment by SlayksWood** [comment]
0.8.2.0 staging-10-n
- chop tree
- tree disappear
- reload
- tree appears
https://drive.google.com/file/d/1U6jn-l3I4TX8StEZrUGslwwhaMX4PmJy/view?usp=sharing

**Comment by SlayksWood** [comment]
Step to reproduce:
- cut down a tree
- want to chop tree at small pieces
- start to chop tree: 1. Click LMB for starting chop. 2. Press E many times like crazy to pick up a piece immediately after the axe swing
- Tree can have glitch with highlight or disappears
https://drive.google.com/file/d/1DRzeYdZf83m5XkMEax8hdU_PyBhFtKsV/view?usp=sharing
