### ISSUE TITLE
USER ISSUE: World says it's unable to connect

### ISSUE THREAD

**Issue by FrumpyPants** [StrangeLoopGames/EcoIssues#11499]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**
1. try to load my world

**Expected behavior:**
It *should* load my world

**Actual behavior:**
The following error message popped up:
```failed to connect
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```failed to connect
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by Litonius** [comment]
Check your logs located at "Steam\steamapps\common\Eco\Eco_Data\Server\Logs" and if the last line relates to "[23:21:10.610] [1] [ Info] [Eco] Caught exception when trying to dump a prior exception: Exception of type 'System.OutOfMemoryException' was thrown." then it's the same issue as my bug report from a bit ago.

https://github.com/StrangeLoopGames/EcoIssues/issues/11498

**Comment by BlazeGuy2** [comment]
Try this out: https://github.com/StrangeLoopGames/EcoIssues/wiki/Work-around:-Converting-world-to-new-format-crashing-in-0.8.0.4
