### ISSUE TITLE
[0.8.0.4] Changing Steam Name Disables Voting

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#11497]
If you change your Steam name after joining a server for the first time, you are unable to vote or run for office until you change the name back in Steam. 

When launching Eco, it signs you in as your current Steam name. Any server you rejoin will use the Steam name from when you first joined. When you launch the Eco web interface, it uses the current Steam name you signed into Eco with.  If you have changed your Steam profile name, when you try to participate in government you will get an error message that the names does not match. Only by changing the name back & then closing and reopening Eco can you vote or run for office.

**Comment by Praefator** [comment]
To add to that, from what I noticed in the Network tab of the Server UI, there can be a mismatch in a player name between the name they first joined as, versus the name they subsequently join with if they change Steam names mid-map

**Comment by antimodes221** [comment]
We see this behaviour outside of steam name changes but also when switching between steam and SLG.

This also impacts if you are tagged as an admin or not. Flaged as an admin in steam -> switch to SLG client -> no longer and admin.

Also noticed this when you setup titles/groups.  If you gain permission / access through a  group and switch between clients it breaks your access.  switch back to the originating client and you regain access.
