### ISSUE TITLE
Make underwater shader have less distortion

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11493]
![image](https://user-images.githubusercontent.com/3536496/53456279-a7ac7480-39e2-11e9-966a-1bb1e243e50a.png)
Let's go for more of a Subnautica look
![image](https://user-images.githubusercontent.com/3536496/53456273-a3805700-39e2-11e9-988c-247256828b83.png)

**Comment by johnkslg** [comment]
Bonus points for tinting based on pollution, and under-surface of water rendering 
mega bonus points for caustics on sea floor

**Comment by SlayksWood** [comment]
without Fog:
![image](https://user-images.githubusercontent.com/45708377/67564873-a62b7b80-f72c-11e9-9056-247a83011d1e.png)

**Comment by redwyre** [comment]
I've added another task https://github.com/StrangeLoopGames/Eco/issues/5187 to update post effects which can include adding pollution as that needs a code change

**Comment by beastyn** [comment]
Got it, thanks
