### ISSUE TITLE
USER ISSUE: Skipping Tutorials

### ISSUE THREAD

**Issue by brandondes** [StrangeLoopGames/EcoIssues#11494]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**
Click red X on tutorial objective, skip task && || click skip all tutorials box... then click yes...

**Expected behavior:**
all tutorial objectives would be removed, or the single one I dismiss

**Actual behavior:**
nothing...

**Do you have mods installed? Does issue happen when no mods are installed?:**
nothing...

**Comment by D3nnis3n** [comment]
Cannot reproduce. Probably localised tutorials?

**Comment by elfl0rd** [comment]
this? https://github.com/StrangeLoopGames/EcoIssues/issues/10769

**Comment by brandondes** [comment]
Was running on a locally generated world yes. tutorial objectives were not present upon closing game and reopening.

**Comment by Spydarlee** [comment]
Not having any luck reproducing this either. @brandondes, would you mind answering a few more questions about how you reproduced, please? 

- Had you just completed a tutorial when you tried to skip, like is shown in the video in the bug elfl0rd linked to? (https://youtu.be/itSGbGjrfSE)
- Were you playing the game in English or another language?
- Which tutorial did you try to skip?
- When you say nothing happens, does that mean the tutorial UI stays in screen and you can select the skip option again? If so, does it not work the second time either?

Thanks!

![ecotutorialskipallworking](https://user-images.githubusercontent.com/553695/53499350-16033c80-3aa0-11e9-9cad-976e0d9e2a30.gif)

**Comment by brandondes** [comment]
- Had you just completed a tutorial when you tried to skip, like is
   shown in the video in the bug elfl0rd linked to? (
   https://youtu.be/itSGbGjrfSE) Multiple Tutorial objectives were present
   onscreen and could not skip any of them.
   - Were you playing the game in English or another language? English
   - Which tutorial did you try to skip? Cant recall.
   - When you say nothing happens, does that mean the tutorial UI stays in
   screen and you can select the skip option again? If so, does it not work
   the second time either? Correct or 3rd or 4th try...

**Comment by Spydarlee** [comment]
Thank you. Unfortunately I still haven't been able to reproduce this so I'm going to close for now. If it happens again please do re-open, and any extra info to help track it down would be much appreciated!
