### ISSUE TITLE
[0.8.0] Laws missing "where" act like "all"

### ISSUE THREAD

**Issue by feildmaster** [StrangeLoopGames/EcoIssues#11492]
Pretty straight forward, sometimes laws will forget the status of the clauses while building the law and when you submit them they end up missing the "where", which causes them to act like "all" was selected.

My personal example
![](https://i.imgur.com/mnoc72y.png) (raw) ![](https://i.imgur.com/cAYhMlz.png)

Another example someone else made (the first clause is broken)
![](https://cdn.discordapp.com/attachments/469297188909088789/550056825580552232/unknown.png)

**Comment by Deantwo** [comment]
And according to his other pictures, the error messages mentioned the Citizen demographic, even though it isn't used anywhere in the law.
https://cdn.discordapp.com/attachments/469297188909088789/550056775697694751/unknown.png

**Comment by Deantwo** [comment]
got another one from `@mambroz#8512` on Discord.
https://cdn.discordapp.com/attachments/469297188909088789/561236304776658953/unknown.png

Got a save file from him too.
Here: https://www.dropbox.com/s/p0dfglbo13frsmj/prevent-crafting-law.zip?dl=0

**Comment by D3nnis3n** [comment]
Irrelevant, law system is changing to ingame.
