### ISSUE TITLE
[0.8.0.4] Transferring money no longer works

### ISSUE THREAD

**Issue by feildmaster** [StrangeLoopGames/EcoIssues#11501]
Transferring money between accounts no longer works. There are no errors that pop up and the window always says "Transfer completed successfully". Shopping works as expected, it's simply the "make a transfer" window that no longer works.

**Comment by apnotix** [comment]
Yes I can confirm that 1+

**Comment by FalkosTMB** [comment]
same here

**Comment by redwyre** [comment]
Also it seems to tell everyone else that it succeeded, but I didn't get any message
![image](https://user-images.githubusercontent.com/431728/53639303-882c7a80-3c74-11e9-879c-07ac681d4551.png)

**Comment by gamerpaddy** [comment]
/pay user,amount,currency command is missing, may be related to that?
