### ISSUE TITLE
USER ISSUE: Many times projects will require one additional material than it asks for to complete

### ISSUE THREAD

**Issue by crusnak1** [StrangeLoopGames/EcoIssues#11509]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**

At level 7 Oil Drilling, it takes 16 iron bars to make 40 barrels at 0.4 iron per barrel. The UI indicates that it requires 16 iron bars. After setting up the project, if no iron bars are available, you are notified that you need 17 iron bars instead of 16. This clearly is floating point error. This bug did not exist in any previous 8.0 version.

**Expected behavior:**

40 barrels should require exactly 16 iron bars.

**Actual behavior:**

40 barrels currently requires 17 iron bars.

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by trevelmike** [comment]
same issue. It happens with a lot of mats.

**Comment by craig-jong** [comment]
The dynamic value is sent once to the client as a formula that is executed client-side and server-side independently. Presumably it was done to reduce network traffic when people are changing around crafting values.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/55657682-d242d780-57af-11e9-8b9b-b2a9bf7c459a.png)

I don't see this issue happening anymore. We've fixed a few rounding error like this in the past, so I'm going to guess that this is fixed in master.

Reopen this issue if it persists.

**Comment by D3nnis3n** [comment]
Persists, see #11948

**Comment by craig-jong** [comment]
I'm going to need specific recipes and specific skill levels to reproduce this bug. I'm having no rounding issues on any of the recipes I've been trying.

I'll continue to test through bricklaying 4-7 with shale bricks, but so far I've come up with nothing.

**Comment by craig-jong** [comment]
Yea, I can't get this to reproduce using shale bricks from skill levels 1 - 7.

I need an exact recipe, crafting count, and skill level to get this to reproduce.

**Comment by craig-jong** [comment]
I found an rounding issue with float -> double conversion that may have caused this. I'm going to close this under the assumption that the change will fix it.

If this issue occurs in 8.2, please reopen this bug.
