### ISSUE TITLE
USER ISSUE: Can't create campfire from workbench

### ISSUE THREAD

**Issue by johnnyvoruz** [StrangeLoopGames/EcoIssues#11508]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**
1. Go to workbench
2. No campfire craftable
3. Go to campsite
4. Campfire craftable

**Expected behavior:**
I should be able to create a campfire from my workbench	

**Actual behavior:**
I thought I lost my mind, had to go back and place campsite, which we replaced with a house.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I thought I lost my mind, had to go back and place campsite, which we replaced with a house.

**Comment by tehflambo** [comment]
You also can't create a workbench from a workbench. If you somehow lose your initial Campsite you're out of luck.
