### ISSUE TITLE
elections/ queries returning Authtoken to the users  

### ISSUE THREAD

**Issue by syuzan-yeranosyan** [StrangeLoopGames/EcoIssues#11504]
When logging in game server with the following parameters:
username  = testuser
authtoken = 123456
and try to start a new election  this query: /elections/current returns the following: 
![default](https://user-images.githubusercontent.com/15518344/53487307-b5c2c980-3aa4-11e9-8b8c-b41e75012203.png)
we have the same issue for the rest of the queries which should return username

**Comment by mirasrael** [comment]
Can't reproduce this issue. And also @syuzan-yeranosyan please don't post here auth info even for test users. Can you test on latest version?

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/54119574-b9d8da80-4406-11e9-9f90-d5be9dc4ee8d.png)

**Comment by mirasrael** [comment]
Not reproduced, no new details. Closed. Feel free to re-open with new details.
