### ISSUE TITLE
[0.8.0.4] Bank ownership requires relogging

### ISSUE THREAD

**Issue by feildmaster** [StrangeLoopGames/EcoIssues#11500]
Upon going to a bank and granting access to an account, the person granted access must relog in order to actually have access.

**Comment by Quadbro** [comment]
What access? user or manager?) "must relog in order to actually have access." where? in this ui or in general actions

**Comment by feildmaster** [comment]
I was unable to select any account I was given access to until I logged back in, be it in shop, or otherwise. I don't... really understand how to explain it any differently? It's pretty easy to replicate via what I said already...

**Comment by Quadbro** [comment]
@feildmaster  thanks for info, was confused a little, but it helped :)

**Comment by feildmaster** [comment]
Glad it helped

**Comment by D3nnis3n** [comment]
Reopened, not fixed in 8.1.0 Staging-1

**Comment by Quadbro** [comment]
so you need to provide more information ^_^, can't reproduce it(

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/54805989-4c9d3300-4cab-11e9-9f0b-b8687487e205.png)
![image](https://user-images.githubusercontent.com/6802030/54806052-76eef080-4cab-11e9-9569-10fa85f1be8e.png)

**Comment by Quadbro** [comment]
and i think you reoppened it because of a /testtreasury command wasn't working properly (use the way, provided on screenshots for testing bank accounts ownership)

**Comment by D3nnis3n** [comment]
Reopened. Treasury still does not show without relogging in 8.1.0-Staging-6.
