### ISSUE TITLE
CI test for garbage fail intermittently

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11513]
![image](https://user-images.githubusercontent.com/3536496/53517027-88fdba80-3a82-11e9-9758-9101a6165ae4.png)
This test needs to be fixed as it fails all the time, then succeeds after another 'run tests'

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/11416
