### ISSUE TITLE
USER ISSUE: Gathering Skill

### ISSUE THREAD

**Issue by Ezmiline** [StrangeLoopGames/EcoIssues#11511]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**
After 8.0.4 update gathering skill not affecting the number of seeds\plants collected (100% growth) 

**Expected behavior:**
5-6 Beans with max skill

**Actual behavior:**
1 Been with max skill

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Comment by eliotcougar** [comment]
Just tested on sea-otter... Can't confirm...
Getting 4-7 beans with max skill no problem...

**Comment by beastyn** [comment]
[0,8,1,3] Works fine for skill listed plants. Please reopen if you meet this issue again.
