### ISSUE TITLE
Removing Player is not possible - Please provide an command for that

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#11510]
Version: 0.8.0.4 beta

Pam posted yesterday in discord a guide how to remove a player from the server.

> 'REMOVING A PLAYER PROFILE:
> 
> To remove a player profile: Shutdown your server (or in singleplayer shut down the Eco client).   Go to your Storage folder (standalone would be in the server root/Storage and in client server it would be in steamapps/Eco/Eco_data/Server/Storage/)and save your <worldName> .eco file and the <worldname>.db in a separate place as backup.  Then take the current file  <worldName.eco>  and right click on it and in your zip program in the list pick 'open archive' .... DO NOT UNZIP.... if you unzip you may never get it compressed again correctly where the server will recognize it as a game file as the game uses a different compression algorithm than a normal zip program.... In that archive is a Users folder.  In that folder locate your profile by steam64ID and/or slgID and delete it (in a singleplayer game it would be the only profile in there)..  Close the archive and load the game
> 

After following this guide my server does no longer start with the following exception:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.UserAlias.GetHashCode()
   at System.Collections.Generic.GenericEqualityComparer'1.GetHashCode(T obj)
   at System.Collections.Immutable.ImmutableHashSet'1.Add(T item, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet'1.Add(T item)
   at Eco.Core.Utils.ThreadSafeHashSet'1.<>c__DisplayClass8_0.<Add>b__0(ImmutableHashSet'1 x)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func'2 apply)
   at Eco.Core.Utils.ThreadSafeHashSet'1.Add(T item)
   at Eco.Core.Utils.ControllerHashSet'1.<>c__DisplayClass9_0.<Add>b__0()
   at Eco.Core.Utils.ControllerHashSet'1.ApplyChange(Func'1 change) `

This issue is related to BankAccounts because when deserializing them the user does not exists.
I also can not find any useable solution to remove a player.

My suggestion is that you could provide and admin command to remove a user completely

**Comment by D3nnis3n** [comment]
Why are you deleting player profiles at all, is there any specific reason that would make this a bug at all?

**Comment by lordmampf** [comment]
Because I don't want to see their names in the online list and don't see the user in the authorization tab.
When you have a server which is running longer than 1 month it would be nice to be able to clean up some stuff.
When a user was online for 1 hour some month ago I want to remove all his objects and stuff.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#732
