### ISSUE TITLE
Exception everytime you run server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11517]
![image](https://user-images.githubusercontent.com/3536496/53518087-19d59580-3a85-11e9-9e77-1853044885ac.png)
I tried to add this one to the Exception list (it wasn't there to begin with) and uncheck it, but no luck. Perhaps there's some proper way to do that?

**Comment by redwyre** [comment]
"Enable Just My Code"
![image](https://user-images.githubusercontent.com/431728/53534891-659f4200-3b4c-11e9-8c72-8d5ba8e34b9f.png)

This will stop the debugger breaking on exceptions in third party dlls

**Comment by mirasrael** [comment]
@johnkslg Can you show full stack trace?

**Comment by mirasrael** [comment]
@johnkslg Can we close this issue? Seems it was solved during our Discord chat?

**Comment by seccombew** [comment]
Fixed.
