### ISSUE TITLE
GI bakes in the block cursor

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11523]
![image](https://user-images.githubusercontent.com/431728/53542332-b40f0980-3b69-11e9-9445-ecafe6032fdf.png)

the middle block was highlighted and then dug out

**Comment by metachronism** [comment]
need extremely low priority label :P

**Comment by redwyre** [comment]
:( It's been happening to me a lot in dark places, random yellow and green glows...

**Comment by redwyre** [comment]
![image](https://user-images.githubusercontent.com/431728/55600940-a6205a00-57a1-11e9-9327-2e7c1d7d208f.png)

**Comment by WeaselDog** [comment]
We have had lots of updates to lighting. Let me know if this is still an issue.
