### ISSUE TITLE
Trillium has a cluster of leaves off to the side

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11529]
![image](https://user-images.githubusercontent.com/431728/53579378-2c56e880-3bc5-11e9-8c31-56f0261a6ff6.png)

**Comment by MilenkoTunjic** [comment]
Is this a regular plant trying to be potted, or is this an actual asset for the pot?

**Comment by redwyre** [comment]
I believe the pots use the same asset

**Comment by MilenkoTunjic** [comment]
pots use terrain block asset?
