### ISSUE TITLE
No info about "Wolf Whisperer" unique ability is not realized.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11521]
https://ecoauth.strangeloopgames.com/home page is not contain any information about "implement later" for unique ability at "Wolf Whisperer" pack.
In some countries this can call some problems at law layer. "False or misleading advertising".

**Comment by BlazeGuy2** [comment]
Probably should add a "Coming Soon" or "Coming Later" line to it on the site
