### ISSUE TITLE
0.8.0.4. beta - Store ain't bueno with stone roads

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#11526]
1. Try to add stone road into the "buy" section of a store
2. Fail miserably
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2914369/output_log.txt)
https://youtu.be/n-YPyM2mk0s

In-game report thingy ain't seem to be opening browser tabs so i'll make a dump a classic way

**Comment by digruberg** [comment]
I can't reproduce this bug. 
Video how it going - https://www.youtube.com/watch?v=4KkhV6lyQZk&feature=youtu.be
Can you give me that saves for testing?

**Comment by HetNeSS** [comment]
Where can I find world saves for a multiplayer game?
Server owner claims that kind of a bug that only makes an appearance once in a hundred years, and can be fixed with a relocation of a store into the same place. Gonna talk up with him on the topic this evening
Same issue with road tool's had been happened earlier, can't get them into the bought of a store without a session crash

**Comment by HetNeSS** [comment]
> 
> 
> I can't reproduce this bug.
> Video how it going - https://www.youtube.com/watch?v=4KkhV6lyQZk&feature=youtu.be
> Can you give me that saves for testing?

https://drive.google.com/file/d/119NCQGqnqRq6TPVnR2Ct6bx-M9w28_jf/view?usp=sharing
Store is located at 178,76,323 . Please let me know as soon as you'll get this message, so I'll remove the link.

**Comment by digruberg** [comment]
I get it

**Comment by Quadbro** [comment]
mod confclicts with stone road
