### ISSUE TITLE
USER ISSUE: Some needed items don't spawn in random world

### ISSUE THREAD

**Issue by NicolasEMendez** [StrangeLoopGames/EcoIssues#11533]
**Version:** 0.8.0.4 beta

**Steps to Reproduce:**
1) Make a random world.
2) Try to find wild corn or wild beets using 'plants' pressing M.
3) There is none to find even on Corn plant or yield.	

**Expected behavior:**
You should be able to find the necessary plants to complete "Forage for food" quest	

**Actual behavior:**
Impossible to complete the tutorial.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods. Vanilla game

**Comment by SlayksWood** [comment]
If you will have same trouble in next time. Please do next: When you go to the server you have some information about him. Move mouse over on "more species". Check information about corn and beet.
![image](https://user-images.githubusercontent.com/45708377/56574472-ff72f080-65cb-11e9-987b-a39337942afd.png)
Sometimes It happen that some specie don't generate in a new world.

**Comment by johnkslg** [comment]
@D3nnis3n @SlayksWood @beastyn Can you guys keep an eye out for this in 8.2? It supposedly should be impossible.

**Comment by SlayksWood** [comment]
@johnkslg 
Amanitas mushroom, Bullrush, ButtonBush, Pitcher Plant, Sagebrush are always = 0.
Is Wetland Biome absent in 8.2?
Bison count for my 1km world is 7-12. Other species have good value.

**Comment by SlayksWood** [comment]
Bison count for 0.52km world is 1-3. Need a little more Bison.
![image](https://user-images.githubusercontent.com/45708377/57516971-7b846c80-731e-11e9-9934-5ec2b1bfba6b.png)

**Comment by SlayksWood** [comment]
0,52 km world: Bisons are absent
![image](https://user-images.githubusercontent.com/45708377/57529767-60c1f000-733e-11e9-864f-c47c87979988.png)

**Comment by SlayksWood** [comment]
From #12266:
"I did create 2 World with 4km² but did only have under 5 Bisons and under 40 Oaks."
![57587533-5ce0ca00-7506-11e9-87c2-e66e0cd3d0a5](https://user-images.githubusercontent.com/45708377/57597308-9130a680-7557-11e9-887b-20c4d24302f7.png)

**Comment by craig-jong** [comment]
The wetlands plants being 0 is a non-issue for progression (or it should be - let me know if that's not the case).

We can increase bison populations a bit.

**Comment by D3nnis3n** [comment]
I'm getting reports that some people need amanita mushrooms to progress which are not available, but looking in the game there is no research recipe that needs them, only crimini mushrooms which are available. Probably those people .cs files are messed up?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/57766567-3e4e1f00-7710-11e9-8f41-ecc2281f33bc.png)
White bursage absented second time.


Should I open a separate issue to fix count of White bursage and Bison? or It will be fix in this issue.

**Comment by D3nnis3n** [comment]
Keep it here, i changed assignments.

@craig-jong It's only about Bison and the new plant there (if that is expected to be there), the other things seem to be fine. Why some people still need amanita mushrooms for progress - no idea.

**Comment by craig-jong** [comment]
They don't, they just don't like the zero - which I understand. The plan was to reintroduce wetlands very soon, so it didn't seem necessary to fully remove them yet. If we don't get around to that, I'll remove them from the list.

I increased the bison count and changed the spawn parameters for white bursage, but white bursage just gives plantfiber and isn't necessary for anything. It's something we should tweak for 9.0 but its not important enough to block 8.2 from shipping.

**Comment by craig-jong** [comment]
https://github.com/StrangeLoopGames/Eco/pull/4465

**Comment by D3nnis3n** [comment]
Closing out.
