### ISSUE TITLE
USER ISSUE: Stockpile smoke effect displayed beyond render distance

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11539]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
go far away so the stockpile disappear
let someone take/put in stuff

**Expected behavior:**
no smoke effects, no lag spike

**Actual behavior:**
you will see smoke effects without seeing the stockpile
this also causes small lagspikes depending on the amount thats been put into

**Do you have mods installed? Does issue happen when no mods are installed?:**
you will see smoke effects without seeing the stockpile
this also causes small lagspikes depending on the amount thats been put into

**Comment by eliotcougar** [comment]
I confirm...
Often times some heavily developed areas of the map don't unload, and I can see terrain far beyond the set render distance... And even if the stockpile that just went beyond render distance, is not rendered anymore, the data about items going into the stockpile (from crafting or other players) still used by the game to render particle effects, and probably even to update the stockpile's mesh even if it's not visible...
That's probably why the performance that drops when you're in heavily developed area, does not improve when you leave that area...

**Comment by SlayksWood** [comment]
It should be already fixed.
