### ISSUE TITLE
Half Vanished Stockpile

### ISSUE THREAD

**Issue by SteelaCell** [StrangeLoopGames/EcoIssues#11532]
Stockpile is half vanished 
![vanished stockpile](https://user-images.githubusercontent.com/47764069/53603865-248e4880-3bb3-11e9-8979-7fc42ae6d27a.png)
![vanished stockpile 2](https://user-images.githubusercontent.com/47764069/53603868-26580c00-3bb3-11e9-8d64-b70f41e38c2f.png)

**Comment by redwyre** [comment]
If you place a block next to the vanished side, does it re-appear?

**Comment by redwyre** [comment]
[output_log - Copy (2).txt](https://github.com/StrangeLoopGames/EcoIssues/files/2919332/output_log.-.Copy.2.txt)

Had this also happen to me in 0.8.0.5, adding new things to the stockpile doesn't update the chunk mesh, but the stockpile highlight mesh is correct

**Comment by redwyre** [comment]
I haven't seen any recent issues with chunk generation so closing this, feel free to reopen if you experience it again.
