### ISSUE TITLE
Suggestion: Make claimed farms harder to grief

### ISSUE THREAD

**Issue by Rokutaa** [StrangeLoopGames/EcoIssues#11531]
As it is now I've had farms griefed so many times, sometimes on accident, by people chopping down trees nearby and killing the plants with pulp. This is a request to implement a system like when you try to hunt on someone's property that prevents the pulp from forming and sends the message "you are not authorized to do this on X's property". I'm not sure how plausible this would be though.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#733
