### ISSUE TITLE
8.0.5 - Entering world taking a very long time

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#11534]
In reference to #11405 - it was closed however if anything the performance worsened a great deal. Before I cleaned my DB of the NullReferenceExceptions it took one, maybe two minutes to enter the world. After the clean less than a minute, and with this update it's back up to the multi-minute mark.

See included screenshot
![capture-high cpu](https://user-images.githubusercontent.com/841990/53635057-466fe580-3c1c-11e9-90b3-d61ed82bbf0e.JPG)

**Comment by vsysio** [comment]
Confirmed, please reopen #11405.

Initial problem quoted in #11405 has reoccurred on a bare metal host running Windows Server 2016 and 8.0.5. It is NOT fixed.

**Comment by BlazeGuy2** [comment]
#11405 has been reopened, closing this one as convo is happening there.
