### ISSUE TITLE
Minor readability issue; Sugar and Flour look far too similar

### ISSUE THREAD

**Issue by Rokutaa** [StrangeLoopGames/EcoIssues#11530]
![bf6ac126e8c80841f54e208bca5e4505](https://user-images.githubusercontent.com/47484419/53586152-8e780500-3b55-11e9-9d48-375caa93d80a.png)
![b2e46591deae7f2fceb6999e341c2312](https://user-images.githubusercontent.com/47484419/53586155-9041c880-3b55-11e9-874e-ceeb00011ee0.png)
One of these is sugar, and the other is flour. In inventories it is very difficult to tell what you need to go 'shopping' for in it's current state.

**Comment by beastyn** [comment]
@keegan-o  will we redo these icons in 9.0?

**Comment by keegan-o** [comment]
Yeah, we'll do this.

**Comment by RobertMangano** [comment]
I've added a new icon for sugar
