### ISSUE TITLE
USER ISSUE: trees vanish

### ISSUE THREAD

**Issue by stbadreturns** [StrangeLoopGames/EcoIssues#11547]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
cut down tree try to harvest

**Expected behavior:**
tress shouldn't vanish

**Actual behavior:**
sometimes when harvesting a downed tree it will become uninteractable or just vanish. disconnecting and reconnecting  reconnecting

**Do you have mods installed? Does issue happen when no mods are installed?:**
sometimes when harvesting a downed tree it will become uninteractable or just vanish. disconnecting and reconnecting will allow you to continue to harvest but can happen again on the same tree!

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11622
