### ISSUE TITLE
USER ISSUE: Mass of heavy vehicles like steam tractor and truck is too low

### ISSUE THREAD

**Issue by crusnak1** [StrangeLoopGames/EcoIssues#11541]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**

Animals or even you can run into the truck or steam tractor and move it significantly, even knocking it upside down. This indicates the mass for these vehicles is too low as the amount of force needed to significantly move a vehicle like this is far too much for the player or animals to be able to generate.

**Expected behavior:**

Movement by bumping into a large vehicle should not be significant enough to overturn the vehicle. Small lateral movement is expected when bumped by the larger animals (i.e. bison or elk).

**Actual behavior:**

Animals have no trouble knocking these larger vehicles over causing you to have to recollect it to use again.

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by eliotcougar** [comment]
Is it the mass though... I guess it's more like movement interpolation issue... The game lets controlled objects and physics objects move into each other and intersect too much before physics kicks in... By that time two objects are partially inside each other, and force calculation goes haywire... By that time the mass of the object does not matter... Players and animals don't obey physics in the game - they are immovable and have infinite force in certain cases...

**Comment by SlayksWood** [comment]
This has been modified in version 8.1.0. Now vehicles don't collide with animals.
![image](https://user-images.githubusercontent.com/45708377/56882234-b5768880-6a6b-11e9-9d70-907bbd81968d.png)
