### ISSUE TITLE
0.8.0.5 Eco Server Error " Can't discover UPnP"

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#11546]
After start EcoServer send this error -

[19:19:56.780] [66] [ Info] [Eco] Can't discover UPnP NatDeviceThe response is invalid: GetExternalIPAddressResponse
   в Open.Nat.ResponseMessageBase.GetNode()
   в Open.Nat.GetExternalIPAddressResponseMessage..ctor(XmlDocument response, String serviceType)
   в Open.Nat.UpnpNatDevice.<GetExternalIPAsync>d__3.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Eco.Plugins.Networking.UPnPMapper.<DiscoverNatDeviceAsync>d__6.MoveNext()

This error message appears approximately 2-5 seconds after the server is fully started.

**Comment by Rambo99** [comment]
Это сообщение об ошибке появляется примерно через 2-5 секунд после полного запуска сервера.

**Comment by D3nnis3n** [comment]
This just tells you that the UPnP opening didn't work as of your configuration, no error in the software.

**Comment by Rambo99** [comment]
Unfortunately, I think that this is a mistake. This message appeared AFTER patch 0.8.0.5 was introduced. At 0.8.0.4 this didn’T (didn’t).
