### ISSUE TITLE
USER ISSUE: Failed to Connect

### ISSUE THREAD

**Issue by tenpigs** [StrangeLoopGames/EcoIssues#11544]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Start the game

**Expected behavior:**
It should connect to the game

**Actual behavior:**
I get the 'failed to connect' message

**Do you have mods installed? Does issue happen when no mods are installed?:**
I get the 'failed to connect' message

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11548
