### ISSUE TITLE
USER ISSUE: Can't connect

### ISSUE THREAD

**Issue by Necato** [StrangeLoopGames/EcoIssues#11548]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Try to connect by clicking continue or Your Worlds latest servers list

**Expected behavior:**
Connect me to the game	

**Actual behavior:**
Depending on the server :
1. Nothing at all. The gear keeps on working, no message, no errors

2. On an other server "Connection failed - connection timed out"

**Do you have mods installed? Does issue happen when no mods are installed?:**
Depending on the server :
1. Nothing at all. The gear keeps on working, no message, no errors

2. On an other server "Connection failed - connection timed out"

**Comment by mirasrael** [comment]
Hi @Necato Do you still have this issue?

**Comment by mirasrael** [comment]
Please, all who have similar issues (I see a lot of issues closed as duplicates) provide following information:
1. Connect to local/remote server
2. Server connection information if it remote (Name/ID/IP:Port)
3. Server log if it local (https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files)
4. Way how you do connect to it (Continue/Server browser list/Recent/Favorite/Direct connect)
5. Do you have problem with specific server or it happens to every server?
6. Do you know if other users of this server experiences same issue?
7. (Advanced) Do you have external IP and does server has external IP address?

**Comment by mirasrael** [comment]
Sorry, @Necato, but without your assist we can't help you. Fill free to re-open issue if you will have more details.
