### ISSUE TITLE
0.8.0.5 Contract board not owned.

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#11545]
If you set the "Contract board" on the land owned by the player, and then open it (enter it), then the error is displayed in the "Owned by ..." line. Screenshot attached.
![20190302162343_1](https://user-images.githubusercontent.com/1098421/53686635-cd1ae480-3d3a-11e9-9dcb-ea8cd4c8aeb5.jpg)

**Comment by SlayksWood** [comment]
0.8.1.4 still an issue.

**Comment by WeaselDog** [comment]
fixed
