### ISSUE TITLE
USER ISSUE: Elevator not synced in Multiplayer

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11551]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. get a friend/buddy to click the elevators buttons when he stands inside 

**Expected behavior:**
the elevator goes down/up with him

**Actual behavior:**
the elevator stands still but he moves, at his game, the elevator moves.  theres no synchronization going on

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

in addition, when i click the elevator button, the instance referes to my player instead of him, making him fall out of the elevator and the elevator glitches up and down very quickly.

**Comment by SeanAtr0n** [comment]
looks like this was already fixed at some point
