### ISSUE TITLE
USER ISSUE: Chunks stop loading, reconnect cause Vehicle to fly away

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11569]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
drive around until the map stops loading, mainly occurs on busy servers.
the chunks stop loading, even if you wait for a long time.

leave your vehicle
reconnect 

**Expected behavior:**
chunks will load again or you spawn near your vehicle after reconnect.

**Actual behavior:**
https://www.youtube.com/watch?v=SLI_L1kujIE

**Do you have mods installed? Does issue happen when no mods are installed?:**
no, vanilla server.

after reconnecting the second time (while youre flying around in your vehicle) you will sometimes spawn near your vehicle where you left it the first time  or in other cases, the vehicle went flying off somewhere and you gotta pull it out of the water

**In addition**, the server shows the Red connection issue sign every 5 seconds for a short moment.
after second reconnect everything works fine again.

**Comment by Rycoviac** [comment]
We have this in combination/related to https://github.com/StrangeLoopGames/EcoIssues/issues/11405
Chunks not loading, so player reconnecting. After that, trucks fall through the ground or flying together with the player, no matter how far you walk away from your truck before disconnecting.

**Comment by gamerpaddy** [comment]
some additional info that may be helpful:
i drove around with the Truck (not steam truck) for a while an never had this issue.
Now i drove with the steam truck after days of not having problems for the first time again, and the map stopped loading.  
falling since a few minutes now:
https://i.imgur.com/FxXURed.jpg

**Comment by mirasrael** [comment]
Chunk loading was improved since 8.2. It is still possible to interact with vehicle in uncommon way after loading, but it should be created as separate issue.
