### ISSUE TITLE
Gov website - russian translation wrong

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#11568]
![image](https://user-images.githubusercontent.com/7343272/53758636-2ab24c80-3e73-11e9-9bc8-716a725da16e.png)

translations include "--RU" 
should be removed

**Comment by D3nnis3n** [comment]
Checked the translation files, it does neither include "Winner" "Ended" or "Ago" nor any party with --RU. Seems to not be an issue in the translation, but underlying.

**Comment by beastyn** [comment]
Well, there is a problem with localization in WebBin\i18n\ru\WebClientStrings.csv
It has this incorrect strings.

**Comment by denysaw** [comment]
@beastyn So how should be correct? Ideal wrong translation issue template:
`Was` -> `Should be`

**Comment by rainfarmer** [comment]
the issue is all the words have "--RU" added to them

**Comment by rainfarmer** [comment]
![image](https://user-images.githubusercontent.com/7343272/80410426-64b48e00-887f-11ea-8f29-22ea193d8854.png)
The "--RU" is not in the translation csv.
so it seems to be added somewhere in code?

**Comment by denysaw** [comment]
Sorry, but totally can't reproduce on build-1520:
![image](https://user-images.githubusercontent.com/5720101/80425313-b2fb7880-88e3-11ea-8a4b-a7710990a0d2.png)

But noticed overall translation buggy behavior. Sometimes some labels are translated and on with another page refresh they aren't. E.g. same snap after F5:
![image](https://user-images.githubusercontent.com/5720101/80425421-e0e0bd00-88e3-11ea-8411-459629745966.png)

If you see same bug, please report it in separate issue ;)

**Comment by rainfarmer** [comment]
ok it fixed itself 👍
