### ISSUE TITLE
Crashing @ 90% Downloaded

### ISSUE THREAD

**Issue by papap0st** [StrangeLoopGames/EcoIssues#11562]
https://www.youtube.com/watch?v=gHerGpd-GXw&feature=youtu.be

I downloaded the game yesterday from Steam. I haven't yet gotten into a game.

There's no difference if I join a server, or try and create my own. I will get the same issue that is shown above. I have uninstalled the game and reinstalled the game. I have verified the game cache after a fresh installation both before and after launching the game.

You'll also notice I am playing the game on potato mode thinking it could be related. I get 12 FPS with everything off. I am running an i7 8700k, gtx 1070 and 16 gb of RAM.

**Comment by redwyre** [comment]
Can you make sure you have the latest graphics drivers (https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers) ?

**Comment by papap0st** [comment]
Good morning,

I did update my drivers, tried running the game. Same thing happened. Uninstalled, then reinstalled. Verified game files before running, same issue. Crashes at 90%.

**Comment by SlayksWood** [comment]
Do you have this problem now?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing for now, please open a new issue if this reoccurs.
