### ISSUE TITLE
Server 5.5 Staging - 516ceabd COD - Dump Files

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1156]
this is for our server crashes on and off

this is the server dump files 
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/833087/Dump.zip)

latest dump was at 11:00  on 3/9/2017 only me on server and i was chopping down wheat..
I would add my own client files but not sure where get them...

Cleaning my dump file catch.

added at 12:05 AM

Logged back into game and noticed mini map is no longer update my icon for example it is there but the facing for direction does not change..
the position moves around but it no longer orientates arrow point which direction I am looking correctly.

other weird thing is where I had just cut down full size trees before crash after the last save, in those spots where i removed the tree stomps there was small shrub trees at - which where not there after the last save my saves are set for ever 30 mins, so I was playing game cut down trees about 25 mins or so latter it COD when i am picking up wheat then I restart the server logged back on and there three trees started where there was no trees 25 mins after that save.  

so ether server had trees growing in those spots and it was not to clients or save file after crash magically got updated with trees that did not exist while server was shut down ?

also after crash and load of backup file the grass is magically reappeared as if i never cut down any trees its all complexing because i must cut down tree my house is there. 

MIni map update 12:22 AM I noticed that mini map does not work still even after logging out and back in, but a note - mini map does work fine if I turn off follow player as in i turn off follow player and my icon representing my guy works fine if I turn off follow player that no longer seem to work as talked about above.

**Comment by midn8t** [comment]
[Crash 03105433.zip](https://github.com/StrangeLoopGames/EcoIssues/files/835128/Crash.03105433.zip)


updated COD dump file

**Comment by metachronism** [comment]
These should all be fixed now
