### ISSUE TITLE
USER ISSUE: Tiny currency numbers

### ISSUE THREAD

**Issue by SnakeSolidNL** [StrangeLoopGames/EcoIssues#11561]
Version: 8.0.5

Reported this issue a while back, made a screenshot to clearify the issue. Tiny numbers are still an issue, resulting in not being able to transfer everything to another account.

![currency_bug_eco](https://user-images.githubusercontent.com/38540031/53703379-aaa7ca80-3e11-11e9-84a1-66835c635948.JPG)

**Comment by Alteraner** [comment]
Yes, please cut the currency after two digits. The currency report looks hell because of all these long numbers. Sometime users gets confused because they cannot transfer something because in background it was rounded up.

**Comment by D3nnis3n** [comment]
Also applies to treasury: > ![default](https://user-images.githubusercontent.com/4980243/52518292-7fd6b600-2c59-11e9-8225-c6398d64839c.png)
> we need something to hard cut for too long fractions
> e.g. dump all after 2 symbol after ,
> or interface for display not shorted number... etc.
> 
> also can you add "all" button to this interface? like transfer.
> ![default](https://user-images.githubusercontent.com/4980243/52518296-a09f0b80-2c59-11e9-8a17-0b9cc4225df4.png)
