### ISSUE TITLE
Sweeping hands causing connection issues?

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11564]
After using sweeping hands a number of times in an area I will sometimes get a long delay after using it where the disconnection icon will show, and after maybe 10 seconds I pick everything up and the game continues.

I also get times where it will pick up each stone with a second or two delay in between

**Comment by BlazeGuy2** [comment]
Sweeping hands?

**Comment by redwyre** [comment]
The mining talent that picks up everything in an area

**Comment by SlayksWood** [comment]
Checked on 8.2.0 staging-986. Wasn't able to reproduce, seems fixed.
