### ISSUE TITLE
[Client Bug] [Version 5.5 Staging 516ceabd] tooltips not closing

### ISSUE THREAD

**Issue by daveSparhawk** [StrangeLoopGames/EcoIssues#1157]
Tooltip dialogues are sometimes not closing when i have moved on.

They remain on screen (and on top) even after i disconnect and reconnect.

i must close client and open again to clear them.

not sure how to trigger/cause.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of StrangeLoopGames/EcoIssues#1196
