### ISSUE TITLE
UnderGround Blast Furnace

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#11571]
Every time i place blast furnace underground i always get the chimney error. I would rather not damm the entire region with tailings. I went to the trouble of making all these iron pipes just so i can use it underground. Let me place the blast furnace underground again. 

A non related issue at times when i close a pop up box i won't be able to move and have to tab to move again

**Comment by trevelmike** [comment]
![20190303001419_1](https://user-images.githubusercontent.com/42901466/53776365-75f04d80-3ebb-11e9-807a-75f54140a134.jpg)
![20190303001433_1](https://user-images.githubusercontent.com/42901466/53776373-7c7ec500-3ebb-11e9-982c-a390586710e3.jpg)

Pictures for a better look

**Comment by rbrangers** [comment]
If you run a pipe from the exhaust to the surface you won't get this error.

![ecopipebfexhaust](https://user-images.githubusercontent.com/4492732/53803164-db6f2900-3f11-11e9-988c-a68e24e899de.PNG)

I always pipe things away from the city anyway so I never got this error.

**Comment by redwyre** [comment]
You need to pipe the exhaust away. You mentioned iron pipes but it doesn't look like you're using them, if there's a problem with them reopen.
