### ISSUE TITLE
USER ISSUE: Linux Game loading stuck at 90%

### ISSUE THREAD

**Issue by itamarcps** [StrangeLoopGames/EcoIssues#11572]
So, I'm trying to run my game, it work flawless on the menu, but when I try to connect to a server when reaching 90% loading, the game starts to cut few frames and after few seconds it just freezes and starts to eat up the ram.

I have tried running with Proton, no success, Tried to run the game downloaded from website, no success.

Here is the Player.log for further info.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/2929001/Player.log)

Lastest drivers installed, here is the System Information output from steam

[SystemInfo.log](https://github.com/StrangeLoopGames/EcoIssues/files/2929007/SystemInfo.log)

PLUS:

When running the game via terminal, the following output is seen

Unable to preload the following plugins:
        ScreenSelector.so
        libCSteamworks.so
        libOni.so
        libsteam_api.so

(I checked and the files are available under Eco_Data/Plugins/)

Version 7.9.x works flawless

8.x versions works happens same error

**Comment by itamarcps** [comment]
Checked if any process is using 2999, 3000 and/or 3001 ports, Nothing

**Comment by SeanAtr0n** [comment]
I'm guessing those dlls are now 32bit, maybe this will help?

https://www.howtoforge.com/multiarch-how-to-use-32bit-packages-on-a-64bit-system-debian-7-wheezy

**Comment by itamarcps** [comment]
> I'm guessing those dlls are now 32bit, maybe this will help?
> 
> https://www.howtoforge.com/multiarch-how-to-use-32bit-packages-on-a-64bit-system-debian-7-wheezy

No success on both 32 bits and 64 bits binaries

**Comment by SeanAtr0n** [comment]
does the 32bit one break in the same way?

**Comment by itamarcps** [comment]
> does the 32bit one break in the same way?

Yes, stucks at 90%, I also lowered all the graphs to the minimal, nothing changed

**Comment by itamarcps** [comment]
I believe that is a Mono compatibility problem, I have searched the error System.Net.Sockets.SocketException
and all leads me to Mono, plus the game isn't loading the kernel libraries.

**Comment by SeanAtr0n** [comment]
Yeah looks like the linux build is pretty messed up, looking into it.

Although I just tried it in ubuntu and got the same issue as you, stuck at 90% of the initial load... but after leaving the window open for a long time (was probably ~10 minutes) it was able to connect & play

**Comment by itamarcps** [comment]
> Yeah looks like the linux build is pretty messed up, looking into it.
> 
> Although I just tried it in ubuntu and got the same issue as you, stuck at 90% of the initial load... but after leaving the window open for a long time (was probably ~10 minutes) it was able to connect & play

Waited about 20 minutes, The game is using about 8 GB of Ram, but it's working right now, please take a look for patching that on the next update, be free close the issue if needed

**Comment by redwyre** [comment]
The windows openglcore build does this too

**Comment by SeanAtr0n** [comment]
hmm, yeah seems to be opengl related...  just tried last night's build with -force-glcore on windows and it also froze at 90% so it looks like switching to aura 2 didn't fix this issue. 

maybe @metachronism knows what other changes in 8.0 could be silently breaking opengl

**Comment by SeanAtr0n** [comment]
Launching the editor with -force-glcore spams this exception:

```
ArgumentException: Kernel 'KEyeHistogram' not found.
UnityEngine.PostProcessing.EyeAdaptationComponent.Prepare (UnityEngine.RenderTexture source, UnityEngine.Material uberMaterial) (at Assets/Art/ThirdParty/PostProcessing/Runtime/Components/EyeAdaptationComponent.cs:112)
UnityEngine.PostProcessing.PostProcessingBehaviour.OnRenderImage (UnityEngine.RenderTexture source, UnityEngine.RenderTexture destination) (at Assets/Art/ThirdParty/PostProcessing/Runtime/PostProcessingBehaviour.cs:226)
```

Might need to go back to the old eye adaptation postfx

**Comment by jthill** [comment]
This happened on 0.8.0.5 for me as well, but the startup _eventually_ succeeded, and the delay happened only on that first time.

**Comment by BlazeGuy2** [comment]
@itamarcps Are you still having this issue?  jthill says it hasn't occurred since 8.0.6.

**Comment by itamarcps** [comment]
> @itamarcps Are you still having this issue? jthill says it hasn't occurred since 8.0.6.

Seems to work, no problem here

**Comment by D3nnis3n** [comment]
Closing, please feel free to open a new issue if this reoccurs.
