### ISSUE TITLE
USER ISSUE: Visualization Bug

### ISSUE THREAD

**Issue by eki-sheldor** [StrangeLoopGames/EcoIssues#11577]
[**Version:**](url) 0.8.0.5 beta

**Steps to Reproduce:**
1. Create a Stone Ramp and a Stone Road
2. Set the Stone Road on the floor (e.g. lvl 50 to lvl 51)
3. Set the Stone Ramp connected to the Stone Road, whereby the connection of the Stone Ramp to the Stone Road starts at lvl 50 (wrong direction)

**Expected behavior:**
The side of the Stone Road showd be shown

**Actual behavior:**
Nothing will be shown, or if there is a building in the ground floor it will be shown.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing will be shown, or if there is a building in the ground floor it will be shown.

![20190305_eco_bug](https://user-images.githubusercontent.com/48243998/53800679-8b0dc080-3f3d-11e9-8d9a-c297b492933b.png)

**Comment by SlayksWood** [comment]
Checked on 8.1.3. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56489897-01fe1900-64ec-11e9-920f-92d89aee3ee6.png)
