### ISSUE TITLE
USER ISSUE: FPS drops the more I travel

### ISSUE THREAD

**Issue by Madrawn** [StrangeLoopGames/EcoIssues#11579]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Log onto a server and walk 500m check fps before and after.	

**Expected behavior:**
FPS shouldn't just drop like that and stay bad.

**Actual behavior:**
If I log on I have 40 FPS, as soon as I walk around 500m it goes down to 12FPS and stays there. Even if I set render resolution to lowest setting fps remains low. Setting view distance lower also doesn't seem to affect it. Also eco.exe eats around 8.5 gb of RAM after traveling back and forth a bit. Chunk loading slows down too so I often have this effect. (See 
![20190305194921_1](https://user-images.githubusercontent.com/1095756/53829377-4c4d2a00-3f80-11e9-9b0b-5faf805920e8.jpg)
![20190305195035_1](https://user-images.githubusercontent.com/1095756/53829378-4c4d2a00-3f80-11e9-9409-77f21b848400.jpg)

)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by redwyre** [comment]
I've generally been having my usage around 3.5GB, but I realised that was because I stay in a relatively small area... walking around the world twice it ballooned out to 8GB. Also my 6GB GPU RAM usage was maxed. (I didn't notice an fps drop but maxing out video ram or main ram on systems with less would definitely be a killer)

**Comment by BitsBytesGaming** [comment]
Looks like something is maintaining the world loaded into memory when it shouldn't be. If that's true, then restarting the game would fix the issue temporarily.

**Comment by Madrawn** [comment]
Well it does fix it, for around 20 minutes. I do not seem to be the only one with this problem.
![image](https://user-images.githubusercontent.com/1095756/53923643-5acb3c80-4079-11e9-863e-991bcafa2add.png)

**Comment by espoire** [comment]
Confirmed that I personally experience this problem, and also have heard many players on my servers also discussing it.

**Comment by Madrawn** [comment]
The last patch seems to made it better, haven't played for more than 20 min yet, but it's better, fps hasn't dropped below 20... still RAM already is at 6gb and raising at about at around 2 mb/second while i write this. I'll add it here if FPS slows to a crawl and how long it took.

**Comment by mirasrael** [comment]
Hi @Madrawn 
Do you still have this problem after 8.1 release?

**Comment by exuvo** [comment]
I have this same problem on 8.1.2 and 8.1.3. FPS goes from a normal 60 FPS when im out in sparsely constructed land, but as soon as i go past the central city the FPS goes down to 10 and stays really low until i disconnect and rejoin. Memory usage also balloons but resets on disconnect (i have 32GB RAM so not really a problem for me). Playing with all graphics options enabled except vsync, shadow good, foliage 100%, draw distance 100, Antialiasing at High as Temporal has ghosting on tool movement. I get slower chunk loading but not usually not enough for me to outrun it.

Seems like a memory leak to me.

**Comment by mirasrael** [comment]
It may be related to non-released server views. Should be improved in 8.2 then, because we added GC for unused server resources.
