### ISSUE TITLE
USER ISSUE: Huckleberry visuals dont have berries on it when full grown

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11575]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
let some huckleberries grow

**Expected behavior:**
should have visible berries on it

**Actual behavior:**
doesnt have berries on it

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11288
