### ISSUE TITLE
USER ISSUE: Water deletes Plants

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11574]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Get a Pump and some Pipes
pump water along a pipe and add more pipes to the sides 
a puddle of water appears (very buggy water with lots of vertex stitching errors) 
do this near some plants

**Expected behavior:**
plants will be under water and die some day when soil moisture gets too high

**Actual behavior:**
they instantly disappear

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods vanilla server

before:
https://i.imgur.com/0I9vIIF.jpg

puddle of water forms:
https://i.imgur.com/uv6dhqP.jpg

plants are gone:
https://i.imgur.com/EvojtDO.jpg

Does not appear to happen on trees/cactus

**Comment by johnkslg** [comment]
Standing water should kill plants
