### ISSUE TITLE
Mining action can't be prevented by law

### ISSUE THREAD

**Issue by McSassa** [StrangeLoopGames/EcoIssues#11582]
There is no "Mining" action in law's screen, so we can't make a law to prevent mining in some areas and/or by some players.

**Comment by Sekor2600** [comment]
Currently, mining is under Pickup. We have a Law where Pickup from Basalt etc is forbidden in a District

**Comment by D3nnis3n** [comment]
That doesn't orevent the mining itself, though. Good idea!

**Comment by Sekor2600** [comment]
no, that's the strange thing. Pickup prevent Mining ,when you prevent pickup from stones.

**Comment by D3nnis3n** [comment]
Not working for me, it only prevents picking up the stones.

Sekor2600 <notifications@github.com> schrieb am Mi., 6. März 2019, 12:44:

**Comment by McSassa** [comment]
In fact I've just testing "Pick Up where Item is Limestone > Prevent" and I can't break Limestone...

**Comment by D3nnis3n** [comment]
Try with iron. Thats what i tried. Didnt work.

McSassa <notifications@github.com> schrieb am Mi., 6. März 2019, 13:54:

**Comment by redwyre** [comment]
Iron? Or Iron Ore?

**Comment by McSassa** [comment]
I tried with a steel Pickaxe, I could break granite but not limestone with a clear message that's because of the law. (Was in version 8.0.4, if it could help).

**Comment by D3nnis3n** [comment]
Iron Ore. We used that law to limit the amount of iron ore people could mine when we had to spawn in a big iron mountain as we had no ores in our world generated. It did not affect how many iron ore they could mine, only how many they can pick up. Considering it's called "harvest" i assumed that is working as intended.

**Comment by McSassa** [comment]
So I did a new test with Iron Ore and indeed mining action could be prevented :
![image](https://user-images.githubusercontent.com/47372214/53953588-02755880-40d4-11e9-9df6-e5e8c72ac9d1.png)

**Comment by WeaselDog** [comment]
It looks like the issue is Mining is under "Pick Up" while things like Cutting Trees are in "Harvest. It is more a linguistic issue than a game action issue. I agree they should add a section called "Mining" so it is more clear what to use in game.

**Comment by RylenWolf** [comment]
Hi! I just did some testing with this law and found out that dropping Iron Ores with right click and then picking them back up again with E triggers Pick Up, thus making a miners benefit impossible. I support separating Mining from Pick Up.

**Comment by johnkslg** [comment]
@olegshegai can you add a mining game action which refers to breaking rock

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13721
@johnkslg What about separate law "action" for grabbing ore|stone debris and tree trunks?

**Comment by beastyn** [comment]
Digging anbd Mining is fine, but won't work with selected block type. Related issue is here #13289

**Comment by beastyn** [comment]
And with 1259 we've lost condition part for Dig and Mine
![unknown (28)](https://user-images.githubusercontent.com/27898520/69219144-07136b80-0b94-11ea-9fa7-f9a5066514ac.png)
I think poke @johnkslg

**Comment by johnkslg** [comment]
Fixed a few problems that got in somehow. Working now:
![image](https://user-images.githubusercontent.com/3536496/69991773-2f3c8c00-14fd-11ea-9f23-1a69ea470f5e.png

**Comment by beastyn** [comment]
Don't see particular actions selector in the conditions yet...

![bandicam 2019-12-03 15-49-44-352](https://user-images.githubusercontent.com/27898520/70044637-8f5a2d80-15e4-11ea-9ef4-94445b483e0c.jpg)

**Comment by johnkslg** [comment]
Let me know what you're expecting to see there.

**Comment by D3nnis3n** [comment]
I assume she means specific blocks? Von: John KrajewskiGesendet: Dienstag, 3. Dezember 2019 21:25An: StrangeLoopGames/EcoIssuesCc: Dennis Scholz; CommentBetreff: Re: [StrangeLoopGames/EcoIssues] Mining action can't be prevented by law (#11582) Let me know what you're expecting to see there.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by olegshegai** [comment]
Conditions used to have clarification for the action type (if it's `digging` or `mining`)

**Comment by beastyn** [comment]
@olegshegai yeah, but this particular action can be triggered by checking a block or a tool type. A little bit confusing though.

**Comment by D3nnis3n** [comment]
Is your comment fixed now? oO

**Comment by beastyn** [comment]
Nope, its just intended.
But I don't actually like it, as I will have to use matching tools or blocks. And if I want to make a trigger for Dig (for every tool) I will have to choose all of the shovels in the Matching field. When in a standard way you could just distinguish it in the conditions part.

**Comment by Deantwo** [comment]
Why is mining and digging even related in this? The two actions don't seem like they have anything in common.

Digging picks up a dirt/sand/clay block and lets you place it again.

Mining has you irreversibly break a rock block to turn it into rock chunks. This is what we want a game action for.

I haven't had the time to test it myself, so excuse me if I am missing the bigger picture here.

**Comment by beastyn** [comment]
Digging and mining is just for picking with shovel or breaking blocks with pickaxe. For placing there is another action,
Similar in process actions where coupled (you actually just destroy blocks with these mining/digging actions).
