### ISSUE TITLE
Cart deed lost if inventory is full

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1158]
full inventory, place cart, cart's prev inventory slot is empty... deed lost

**Comment by metachronism** [comment]
pretty sure craig fixed this

**Comment by craig-jong** [comment]
address 5.6

**Comment by SeanAtr0n** [comment]
still issue in 5.6

**Comment by metachronism** [comment]
just verified this still happens

**Comment by MarjieAVolk** [comment]
I could have sworn this was fixed now

**Comment by MarjieAVolk** [comment]
Indeed, this bug seems to be fixed for me.  I remember specifically fixing this also.

**Comment by MarjieAVolk** [comment]
Yeah this is definitely working for me
