### ISSUE TITLE
Private server is displayed offline in favorites after each server restart

### ISSUE THREAD

**Issue by apnotix** [StrangeLoopGames/EcoIssues#11584]
We have a private server hosted at g-portal and after each reboot it will be displayed under Favorites as offline. We then have to add it every time and it will appear x times offline and one online.

**Comment by mirasrael** [comment]
Are you admin of this server? Can you check content of Configs/Network.eco - do you have same values after each restart for "ID" and "Passport"?

**Comment by apnotix** [comment]
There are no properties like id or passport.. Just description, publicserver, ipadress, gameserverport, webserverport

**Comment by mirasrael** [comment]
I suspects this file may be read-only for some reason, so server can't properly save its identifier and generates new for every restart.

**Comment by apnotix** [comment]
This issue can be closed. the problem was that in the web interface file these properties were not available and these were entered at restart without ID and passport in the network.eco. Have now entered this data into the web interface and ID and Passport remain. Thanks for your help
