### ISSUE TITLE
curved Sunrise / Sunset are... uninspiring

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11589]
I know you hate colors but this makes me sad

**Comment by BlazeGuy2** [comment]
what is the issue with curved sunrise/sunsets?

**Comment by SeanAtr0n** [comment]
you can't see them, by the time you can see the sun it's more like mid-morning

**Comment by SeanAtr0n** [comment]
so when you actually see the sun rise the sky is blue and all of the nice TOD colors are skipped

**Comment by metachronism** [comment]
sunrise is at 7am and has all the right settings - what is missing/wrong?

**Comment by SeanAtr0n** [comment]
what color should the sky be at sunrise/sunset? blue?

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/53985254-056e4a00-40d0-11e9-8402-f518b589028d.png)

The curving means the 'golden hour' all occurs when the sun is pulled down under the horizon

**Comment by metachronism** [comment]
![image](https://user-images.githubusercontent.com/3150561/54059004-68351380-41ac-11e9-8dcc-48e75c90aba9.png)

7am (which is sunrise) with sun right on horizon

**Comment by SeanAtr0n** [comment]
I know I don't have your amazing color sensibilities but it seems to be lacking something...
this is wikipedia's definition of sunrise 
https://upload.wikimedia.org/wikipedia/commons/e/e6/Hazy_Crazy_Sunrise.jpg

**Comment by metachronism** [comment]
the title of the bug makes it seem like its due to the curve, but the sunrise/set has always looked like this

**Comment by SeanAtr0n** [comment]
undo your curving to see that's not true
