### ISSUE TITLE
BUG: Server games cause my game to crash

### ISSUE THREAD

**Issue by Minihornet** [StrangeLoopGames/EcoIssues#11581]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2932737/output_log.txt)
Cannot post .DMP files so no crash log. sorry discord is Vinnnnny#3352 if you need it.

**Comment by mirasrael** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11125
