### ISSUE TITLE
Long delay after trading with store

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11585]
![2019-03-06](https://user-images.githubusercontent.com/431728/53863180-3483ad80-4035-11e9-87a3-37e8d8d9455a.png)

Took maybe 30 seconds for it to come back after clicking Trade

**Comment by D3nnis3n** [comment]
Likely related to performance issues with servers, db issue.

**Comment by Madrawn** [comment]
I noticed this too, on servers with only 8 guys online, but a population of 400.
