### ISSUE TITLE
USER ISSUE: Invalid Login Information

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#11599]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Playing the game
2.Got kicked out for changed log in token
3. Everytime I try to log back in it tells me invalid log in information

**Expected behavior:**
My account should remain in the game and no changes to my log in information

**Actual behavior:**
Connection Failed
Invalid Log in information

**Do you have mods installed? Does issue happen when no mods are installed?:**
Connection Failed
Invalid Log in information

**Comment by D3nnis3n** [comment]
Does this issue still occur?

**Comment by SlayksWood** [comment]
Wasn't able to reproduce.
If it happens again, please reopen and provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
