### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by SpaceFreakx** [StrangeLoopGames/EcoIssues#11598]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Comment by D3nnis3n** [comment]
Merged with #11548
