### ISSUE TITLE
USER ISSUE: cant connect

### ISSUE THREAD

**Issue by Mrc0de** [StrangeLoopGames/EcoIssues#11591]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
cant connect 

**Expected behavior:**
connecting 

**Actual behavior:**
The following error message popped up:
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11548
