### ISSUE TITLE
Tree fell on claimed land and now I can't chop it

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11593]
![image](https://user-images.githubusercontent.com/431728/53942058-8dbb1200-4105-11e9-93e2-db75b0076f98.png)

Chopped tree on unclaimed land (red x), managed to get one hit in while it was falling and collected that.
The trunk then fell onto claimed land (blue x), when I tried to shop it I'm told I'm unauthorised.

So I rolled the trunk off the claimed land, and I'm still getting told I can't because it's on someone's property.

This seems a bit weird, since if it's not just where it is when it's chopped then the trunk must be keeping track of where it fell... but why wouldn't it track the user that cut it down instead to let them pick it up? It also generated debris that I can't clean up

**Comment by redwyre** [comment]
Also, this piece is green but I can't pick it up
![image](https://user-images.githubusercontent.com/431728/53942458-8a745600-4106-11e9-9fb1-26becd5d6e9b.png)

As opposed to the debris next to it
![image](https://user-images.githubusercontent.com/431728/53942482-9d872600-4106-11e9-8140-0157aeaca05c.png)

**Comment by beastyn** [comment]
problem is only with the branches now

**Comment by WeaselDog** [comment]
Fix in 9.6
