### ISSUE TITLE
Crane spawned from testcrane fails to move

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11590]
Can't seem to move it in 8.0.6

**Comment by BlazeGuy2** [comment]
It was spawned on sandstone, QA command needs to be reworked to be put on leveled ground

**Comment by D3nnis3n** [comment]
Fixed in 8.1.0 Staging-1

**Comment by SlayksWood** [comment]
Crane doesn't show correctly in multiplayer. 
When I look from the side as someone works on a crane, the crane does not move at all, only constructed objects appear.

**Comment by SlayksWood** [comment]
8.1.0 Staging-6
Crane doesn't show correctly in multiplayer.
When I look from the side as someone works on a crane, the crane does not move at all, only constructed objects appear.

**Comment by D3nnis3n** [comment]
This is an entirely different issue, splitted: https://github.com/StrangeLoopGames/EcoIssues/issues/11810
