### ISSUE TITLE
USER ISSUE: WSU Student login

### ISSUE THREAD

**Issue by AlisonB319** [StrangeLoopGames/EcoIssues#11592]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Have a student account with WSU
2. Press Continue once Eco opens

**Expected behavior:**
You log in and play the game

**Actual behavior:**
The following error message popped up:
<size=150%>Connection Failed</size>
Wrong version of the game was given to us

Incompatible version.  User is 0.8.0.5 beta but server is 0.8.0.1 beta.

<size=60.00%></size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
<size=150%>Connection Failed</size>
Wrong version of the game was given to us

Incompatible version.  User is 0.8.0.5 beta but server is 0.8.0.1 beta.

<size=60.00%></size>
```

**Comment by rainfarmer** [comment]
updated server to 8.0.5
