### ISSUE TITLE
 exclusive fullscreen mode

### ISSUE THREAD

**Issue by apnotix** [StrangeLoopGames/EcoIssues#11595]
Is there a way to implement an exclusive full screen mode? My monitor has gsync but I have no effect on the game. Likewise, my monitor shows permanently 60fps but the game is at 20-30 fps. I think this mode would get some performance out of the game

My setup:
Nvidia Zotec 1080 AMP Extreme
Intel Core i7 5820K 6x 3.30GHz / PC 3.8GHz

**Comment by redwyre** [comment]
G-Sync isn't really going to improve your performance, it's more to eliminate tearing when the fps doesn't synchronise with the refresh rate.

However, you should be able to set your G-Sync settings to enable for (borderless) windowed mode.

I'm closing this but if you need anything else you can create suggestions in https://github.com/StrangeLoopGames/EcoSuggestions/issues
