### ISSUE TITLE
View system failing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#116]
When fueling a craft table, 'this.Changed("Enabled")' is called at StatusComponent.cs line 47.  
This should trigger the subscription on the client at StatusUIComponent line 38, however it does not.  

It appears that the view from the enclosing RequestView has a controller token attached that does not match the token that was queried.  

Possible causes:
- Multiple 'viewtypes' on the same controller making it return the wrong cached view?
- ContainerUI causing problems because it's being used as a component rather than a root?

**Comment by metachronism** [comment]
this seems to be working fine
