### ISSUE TITLE
Iron scythe's shadow is reversed 

### ISSUE THREAD

**Issue by Rokutaa** [StrangeLoopGames/EcoIssues#11603]
To reproduce in 8.0.5:
Equip iron scythe, it happened when the moon was high so wait til midnight ish, look at the scythe's shadow and slowly turn in a circle. Eventually the shadow will flip.

**Comment by BlazeGuy2** [comment]
@Rokutaa Can you provide a screenshot/video of this effect?

**Comment by Rokutaa** [comment]
https://steamcommunity.com/profiles/76561198044107747/screenshots/
I may have misjudged the time of day, these were taking in the "morning" hours, like around 3AM ingame time? The longer the night went the more noticable it became and it only happens when facing south.

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56883911-c1187e00-6a70-11e9-8e81-b9ba147e2c70.png)
The shadow of the iron scythe relative to the light source is displayed correctly.
