### ISSUE TITLE
You can eat seeds

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#11602]
![image](https://user-images.githubusercontent.com/18184943/54002404-45025980-4103-11e9-84a4-b61558685ff9.png)

Pretty sure there should be a check here that stops you from eating things that give exactly 0 calories. Amanita give negative, so it has to be exactly 0.

**Comment by Rokutaa** [comment]
please leave this in the game! I find myself overwhelmed with the amount of seeds made from pulp, even with planting a ton of trees and there's no way to remove them!

**Comment by redwyre** [comment]
I usually eat seeds to get rid of them, but throwing them away as trash works too

**Comment by HetNeSS** [comment]
A main way to dispose of pesky seeds in early game. I've thought it was intended to be so. You can't just drop them to ground since they'll transform into trash, like any non-food item

**Comment by WeaselDog** [comment]
I thought that it should not affect your nutrition score because it has 0 calories. For me it never has an effect.

**Comment by craig-jong** [comment]
It doesn't have an effect, that screenshot shows that because I also zeroed out my calories at the same time.

Seeds will appear in a garbage bag but turn into compost given time. We've been trying to reduce the number of seeds gained in general to push the importance of crafting them. I'll look into that as well.

**Comment by SlayksWood** [comment]
Seems it's intented behavior for now.
