### ISSUE TITLE
USER ISSUE: Store causes fps loss once opened

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11608]
**Version:** 0.8.0.5 beta
See video, notice frametime and fps.
https://youtu.be/cltxYOfoXcg

**Steps to Reproduce:**
Have a Store selling a lot (20-30 items)
Open it when the game runs fine

**Expected behavior:**
game runs fine when you close it again

**Actual behavior:**
fps drop to unplayable for a period of time. sometimes even have to restart to get good fps again.
its stuck at 20 no matter what i do.

**Do you have mods installed? Does issue happen when no mods are installed?:**
none

**Comment by gamerpaddy** [comment]
Additional information:
opening more shops lowers the fps every time.
But when going to bed and make the hud disappear, it revers to normal
after leaving the bed, it starts dropping the fps again as soon as the hud shows up

https://www.youtube.com/watch?v=pS2iqFn1ZDw

**Comment by espoire** [comment]
I have noticed that RAM usage also spikes in the period during, and for a short while after, (~10 minutes, or until a player restarts their client) accessing a shop dealing in many items.
