### ISSUE TITLE
USER ISSUE: Selling/Buying a lot in a Store lags the Server

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11607]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Have something in bulk like 1000 wheat
sell it to someone buying Wheat

**Expected behavior:**
it sells the 10x 100 stacks as a whole stack

**Actual behavior:**
seems like it sells every item one by one causing the server to lag that hard that the red connection warning pops up.

**Do you have mods installed? Does issue happen when no mods are installed?:**
none

**Comment by redwyre** [comment]
Duplicate of #11585
