### ISSUE TITLE
Allow disabling Web UI & punchthrough

### ISSUE THREAD

**Issue by bartico6** [StrangeLoopGames/EcoIssues#11609]
Server administrators should be able to disable the Web UI as well as punchthrough for firewalls.
The reason is, when starting the server in a non-elevated environment, I get asked to elevate the server to run `netsh` 3 times, and it's being somewhat annoying to close the elevation prompt multiple times when starting the server.
I also do *not* want the Web UI, but I see no option to disable it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#750
