### ISSUE TITLE
Friend tried to get in truck, now disembodied

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11605]
![image](https://user-images.githubusercontent.com/431728/54026241-eadbc400-41e8-11e9-8068-2018ad1524d6.png)

You can see his actual position by the player text.
His avatar was still in the car after I reloaded, only him logging out fixed it

**Comment by SeanAtr0n** [comment]
Couldn't reproduce so far so reducing priority... anything odd happen leading up to this? Could use log files

**Comment by seccombew** [comment]
Closing as no repro. Reopen if issue occurs again.
