### ISSUE TITLE
Water pumps complain about no Water connection randomly.

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11604]
Version 0.8.0.5 beta
_Does not allways happen._

See pic:
https://i.imgur.com/PJVCazo.png

1. Is my device that consumes water (Refinery)
2. are the pumps
3. is the water inlet

Ive had it many times now that the Refinery complains about too little water.
 When i walked to the Pumps i saw, only 1 of the 6 are running. ther other ones complained about no connection to water.

Then i have to update the pipe network by removing one pipe on the inlet side (doesnt matter which pipe) and putting it back on.

my pipe setup looks like this:
https://i.imgur.com/kbsEn7j.png

The upper 5 pumps are turning off, the 1 on the bottom keeps running and provides too little water.

Doesnt happen allways, mostly when being somewhere else and visiting the area later on.

**Comment by BlazeGuy2** [comment]
Pipes were tweaked on 8.0.6, reopen if this issue is still present after next hotfix.
