### ISSUE TITLE
Make the camp bed work for sleeping

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11613]
Few steps for this one:
- Make the camp bed selectable as independent from the rest of the campsite.  Follow the example of crats, which have selectable sub-parts
- Work with Keegan to change the model so the bed is more easily selectable (make the tent door-flap more open).
- Setup the bed to do the lie-down (copy settings from other bed)
- Create a new tutorial animation showing how to use it, and only display this tutorial in single player mode.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/54570854-6eda3c80-499d-11e9-8855-bb46312ebcca.png)

Committed to SVN updates to the StarterCamp and Campsite objects that open the door flaps more and adjust the colliders accordingly, separate the bed mesh, give it its own collider trigger, and copied over values for the sleeping position from one of the beds-- that'll need to be adjusted once you can actually sleep in it.
