### ISSUE TITLE
USER ISSUE: Chopping trees sometime loses the yellow border and is not harvestable

### ISSUE THREAD

**Issue by RaptorRaptures** [StrangeLoopGames/EcoIssues#11612]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Cut a tree down
2. Start chopping and gathering
3. Note that the tree loses its harvest object so its just a piece of wood with no yellow lines so you cant chop it
4. Disconnect, reconnect the log is now harvestable

**Expected behavior:**
Tree log should always be choppable until complete

**Actual behavior:**
The tree object loses its yellow border, a re-log is required to fix it. 

**Do you have mods installed? Does issue happen when no mods are installed?:**
The tree object loses its yellow border, a re-log is required to fix it.

**Comment by RaptorRaptures** [comment]
![image](https://user-images.githubusercontent.com/35458721/54041073-78121f00-41cf-11e9-9ac8-7f6561879665.png)

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/11024

**Comment by BlazeGuy2** [comment]
Closed wrong one as dup

**Comment by espoire** [comment]
I have experienced this bug a few times. I don't know exactly what causes it, but it is quite rare. I've encountered the problem 3 times in 74 hours of normal play.

**Comment by Quadbro** [comment]
@BlazeGuy2  why duplicates? It's different issues...
