### ISSUE TITLE
USER ISSUE: All stores periodically reassign their currency to a specific user's credit.

### ISSUE THREAD

**Issue by tehflambo** [StrangeLoopGames/EcoIssues#11616]
**Version: 8.0.5** 

**Steps to Reproduce:**
- Place a store. Store defaults to personal credit. 
- Wait a seemingly random amount of time
- store changes to specific other player's credit, same player every time
- change store back to desired currency
repeat previous 3 steps eternally

**Expected behavior:**
- store doesn't change currency ever, unless I change it

**Actual behavior:**
- store changes currency to a specific user's credit, randomly, persistently, forever.

**Do you have mods installed?** Does issue happen when no mods are installed?:
**yes we do.** I'll check with admin to see if server can be rebooted w/o mods.

------
appears to be a **reoccurence of #3921**, which was *fixed!* over a year ago.
This just started happening to us ~18 hrs ago. Server is ~24 hours old.

Other details:
- fresh world was created
- meteor was forced to hit planet
- server was opened to public for regular play
- a minted/backed currency was created by a player with admin privileges. this is (coincidentally?) the same player whose credit is now being switched to by stores. _note that the currency they created is NOT the same currency appearing randomly in stores_
- this happens to all stores, no matter who created them or when.

**Comment by D3nnis3n** [comment]
Please make sure to reproduce without any mods installed, we can't process bug reports from modded servers.

I did not see this behaviour occuring on our own unmodded server, so I'll set it to Investigate and Needs Information.

**Comment by redwyre** [comment]
This seems to happen to me on my HW server, I will look at my store and it is set to our world currency when it should be set to my own credit

**Comment by tehflambo** [comment]
I'm talking to the server owner to see if we could feasibly restart the server with mods removed

**Comment by Briland5** [comment]
I've noticed the following behavior relating to this:
1) Store is set to (My Credit) which is not the World Default
2) I open the currency tab in my store and the Currency field defaults to Server Default Currency
4) Don't click anything on the tab
3) My store now uses Server Default Currency

Experienced not using mods

**Comment by mirasrael** [comment]
Just to confirm. Do you have this issue on 8.0.6?

**Comment by mirasrael** [comment]
And can you provide a save with this problem (and say nick of your character)?

**Comment by vsysio** [comment]
We actually ended up abandoning the post-apocalypse concept because there was so many issues (such as elevators and ladders not working at all; this was my server). I will submit the save file when I get to it tomorrow.

**Comment by mirasrael** [comment]
Hi @vsysio Any updates?

**Comment by BlazeGuy2** [comment]
Reopen if user responds
