### ISSUE TITLE
USER ISSUE: Trees go missing after chopped down

### ISSUE THREAD

**Issue by RaptorRaptures** [StrangeLoopGames/EcoIssues#11610]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
1. Just chop down a tree
2. It does the falling down animation - Sometimes it just dissapears
3. Start chopping the tree into pisses, it dissapears.
4. Disconnect and reconnect to the game, the tree is then visible

**Expected behavior:**
Trees should not dissapear

**Actual behavior:**
Trees just dissapear

**Do you have mods installed? Does issue happen when no mods are installed?:**
Trees just dissapear

**Comment by RaptorRaptures** [comment]
I also find that this mostly happens when it falls on your house or stock pile

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/11024
