### ISSUE TITLE
[0.8.1.4] Bad message when clicking the 'you (didn't) get xp' icon

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11615]
Saw this in a stream, make sure it's not in latest.

**Comment by SlayksWood** [comment]
What is "line1"?
1. Don't take the skill, Click 'you didnt get xp' icon. The specialization window will open with red row "Line1"
![image](https://user-images.githubusercontent.com/45708377/56958042-ba156c80-6b51-11e9-9a7f-110e88215d85.png)
2. Take the skill, Click 'you get xp' icon. The specialization window will open with blue row "Line1"
![image](https://user-images.githubusercontent.com/45708377/56958197-4a53b180-6b52-11e9-9822-5c963c2e202a.png)
