### ISSUE TITLE
USER ISSUE: HUD bug down-left of the screen !

### ISSUE THREAD

**Issue by nakool** [StrangeLoopGames/EcoIssues#11618]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
I don't know

**Expected behavior:**
Blue windows with information(value of house, tier of house, district and other) on the top of food and value HUD on the down-left of the screen.

**Actual behavior:**
Blue windows with no text or information on the top of food and value HUD

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed, and don't work with no mods installed

**Comment by redwyre** [comment]
Could you add a screenshot?

**Comment by nakool** [comment]
Yes and like you see on the screen i'm on my territory but i don't have information of this or other !
![20190309193255_1](https://user-images.githubusercontent.com/15841124/54075708-ac0a4480-42a2-11e9-92c0-7ba635062861.jpg)

**Comment by SlayksWood** [comment]
Checked on 0.8.3.0 staging-1073. Wasn't able to reproduce. Seems fixed. If it happens again, please reopen.
