### ISSUE TITLE
USER ISSUE: Refill Hand from Stockpile/Cart Dupe Glitch

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11629]
**Version:** 0.8.0.5 beta
See video:
https://www.youtube.com/watch?v=Hj480qflx1A

**Steps to Reproduce:**
have something valueable in Slot 1 of your stockpile or cart.
Have a bit of stone in your hand
leftclick the stockpile to refill your stone if there is any

**Expected behavior:**
you will get stone or nothing if nothing is in there

**Actual behavior:**
you will get the item from slot 1 refilling and replacing the item in your hand. see video.

**Do you have mods installed? Does issue happen when no mods are installed?:**
none

**Comment by Quadbro** [comment]
Duplicate, same as https://github.com/StrangeLoopGames/EcoIssues/issues/11666, handled by Craig
