### ISSUE TITLE
USER ISSUE: Editing growth rate in configs

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#11624]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
I have a ECO server and want to edit the growth time of CommonGrass and maybe other plants.
I've tried looking for the right value to change in the config folder. (like I used to a year ago when i played last time)

So i kept lookin around and found this directory: "/Mods/Organisms/Plant"
In there the file "CommonGrass.cs"

I've tried changing the following numbers in row 30:

// Lifetime
this.MaturityAgeDays = 0.5f;

Then I tried firing up the server again, but nope..
it crashed.

Here a part of the log file:

Error in CommonGrass at 13: The namespace 'Eco.Mods.Organisms' already contains a definition for 'CommonGrass' (CS0101)
Error in CommonGrass at 18: The type 'Eco.Mods.Organisms.CommonGrass' already contains a definition for 'CommonGrassSpecies' (CS0102)
Error in CommonGrass at 74: The namespace 'Eco.Mods.Organisms' already contains a definition for 'CommonGrassBlock' (CS0101)

**Expected behavior:**
should change growth rate

**Actual behavior:**
server crashed

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed

**Comment by BlazeGuy2** [comment]
@PermanentEdding I think I have an idea of what the issue is: try moving Eco.IntegrationTests.dll out of the mods folder and try booting up the server again.  Lemme know if that works for ya.

**Comment by BlazeGuy2** [comment]
Closing due to no response.
