### ISSUE TITLE
[0.8.0.5 beta] Cutting trees - on dismemberment disappear completely when pickup button is being held

### ISSUE THREAD

**Issue by HetNeSS** [StrangeLoopGames/EcoIssues#11622]
If you're holding down the object pickup button (E by default), when dismembering a fallen tree to the pickup-able chunks, sometimes it can result in a remaining cuttable tree to completely disappear. Multiplayer-tested only, works with stone and iron axe, hadn't tested the rest of them (tools). Occured multiple times with the spiked trees

**Comment by SlayksWood** [comment]
Checked on 8.1.4. Wasn't able to reproduce.
Do you have this problem now?

**Comment by HetNeSS** [comment]
Can't say, it's been a long time since i've last played Eco. I guess they would patch something in any of the upcomed updates.

**Comment by D3nnis3n** [comment]
Closing for now, feel free to create a new issue if this reoccurs.

**Comment by Deantwo** [comment]
Duplicate of #11487
