### ISSUE TITLE
Elevator is visible at the bottom to me but is actually at the top for other players

### ISSUE THREAD

**Issue by rosareven** [StrangeLoopGames/EcoIssues#11621]
Version: 8.0.3

The elevator is at the top, which other players can see it at the top, but it's at the bottom for me and if I try to go up or down with the elevator, it doesn't move.

**Comment by Spydarlee** [comment]
This should be fixed on master, but I don't think it get ever got pulled over to release. So it should come with the 8.1 release now. Sorry for the delay!

https://github.com/StrangeLoopGames/Eco/commit/76418a1e442596c3d193e85391dbf3ca150e90ef
