### ISSUE TITLE
USER ISSUE: just wont load

### ISSUE THREAD

**Issue by The-Red-Ore** [StrangeLoopGames/EcoIssues#11628]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
try to load any game

**Expected behaviour:**
it should start the game

**Actual behaviour:**
it shows different messages: connection timed out, can't connect to host (even on a solo game) and the second time I try to load the game it just stops part way through loading

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i do not have mods installed

**Comment by BlazeGuy2** [comment]
@The-Red-Ore What OS are you running?  What are your comp's specs?

**Comment by The-Red-Ore** [comment]
Windows 10 Pro, 1.9-2.5 GHz 2 core processor, 8GB ram

**Comment by The-Red-Ore** [comment]
It used to work fine but one of the updates stopped me being able to load a
game.

**Comment by The-Red-Ore** [comment]
I can play games on all versions upto 0.8.0.0

**Comment by The-Red-Ore** [comment]
Somehow 8.0.6 works though, thanks for the quick updates
