### ISSUE TITLE
xray bug 

### ISSUE THREAD

**Issue by dankri2002** [StrangeLoopGames/EcoIssues#11625]
when you Place Down stone ramps the ground disappears 
![Desktop Screenshot 2019 03 10 - 17 44 47 05](https://user-images.githubusercontent.com/48413914/54088249-585c3180-435c-11e9-8853-cab145c0f3be.png)

**Comment by JyeGuru** [comment]
This is most noticeable with stone ramps, but similar things happen with other blocks (like Brick Floor) which have "cutouts" on the side - you can position them in a way you can see through them.

**Comment by SlayksWood** [comment]
dup #11577
