### ISSUE TITLE
Old pump isn't converting to new pump on server migration for 8.0.6

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11636]
![image](https://user-images.githubusercontent.com/35509188/54166093-ce29d100-4420-11e9-87f1-e10c5bdac1d6.png)

**Comment by BlazeGuy2** [comment]
![](https://cdn.discordapp.com/attachments/443828321529364500/554820431937404938/unknown.png)

**Comment by craig-jong** [comment]
looks like this was fixed with this https://github.com/StrangeLoopGames/Eco/pull/4088
