### ISSUE TITLE
sweeping hands : mining only collects 1 after patch

### ISSUE THREAD

**Issue by Falky870** [StrangeLoopGames/EcoIssues#11638]
Version: Hot-fix 0.8.0.6 
Steps to Reproduce:
try to collect anything with the perk
Expected behavior:
Picking up rocks also attemps to pick up similar rocks in an area 

Actual behavior:
only picks up one sandstone or anything else

Do you have mods installed? Does issue happen when no mods are installed?:
none

**Comment by Briland5** [comment]
I have a player on my server reporting this same issue.

**Comment by mirasrael** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11641
