### ISSUE TITLE
USER ISSUE: Dirt ramp over dirt ramp

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#11630]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
make a bridge wIth dirt ramps under the main ones

**Expected behavior:**
Only the upper one should affect walking

**Actual behavior:**
Go over a ramp over ramp and bug to the sky / fluctuation

**Do you have mods installed? Does issue happen when no mods are installed?:**
Go over a ramp over ramp and bug to the sky / fluctuation

**Comment by BlazeGuy2** [comment]
@criptonauta Can you post a video showing this behavior?

**Comment by criptonauta** [comment]
@BlazeGuy2 Unfortunately I can't. When I relogged today, the guys in my server had already continued the road and it was different.

**Comment by D3nnis3n** [comment]
I couldn't get this to reproduce, back to investigate. @beastyn Please close if you can't reproduce either.

**Comment by SlayksWood** [comment]
@criptonauta  Your issue is similar to this issue? #11577

**Comment by beastyn** [comment]
couldn't reproduce with different constructions. 
If you will meet this issue again please reopen

**Comment by criptonauta** [comment]
I could see the stack of ramps
Then when trying to walk over them, they glitched and I started to go upwards

I also couldn't reproduce it later, cause the road was different when I re logged in.

It was in an old version. It hasn't happened in later releases.
