### ISSUE TITLE
Tutorial images should not be loaded all the time

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11633]
They represent 60% of texture memory.

**Comment by SeanAtr0n** [comment]
Seems like they aren't in memory according to my tests so far...

It takes a long time to get these memory dumps but should have a more accurate picture soon.

**Comment by SeanAtr0n** [comment]
Here is a memory snapshot in-game after loading the world. Intro images are set to full res so they would show up in the circled area if they were loaded, they are not there.
![image](https://user-images.githubusercontent.com/774628/54328407-05d47c80-45cb-11e9-9167-cf08efa5d14a.png)

Taking these snapshots wastes a lot of time so I'm inclined to just leave it at that... in the most common case (logged in without viewing intro) these textures aren't in memory so we don't really need to worry about this.

**Comment by SeanAtr0n** [comment]
Guess they are present in the full IL2CPP build
