### ISSUE TITLE
MASSIVE memory leak on 8.0.6 dedicated server - BSODs server in 20-30 mins

### ISSUE THREAD

**Issue by vsysio** [StrangeLoopGames/EcoIssues#11639]
Video recorded of the user experience while this is happening (note odd physics clamping and ping-ponging): https://youtu.be/sLBPo48AjsY

Server would boot up and in about 30 minutes would consume ~ 20-30GB of RAM before either Windows Server reaps the server (1st case) or the server OS BSODs (2nd case).

Windows Server 2016
32 GB of RAM
2x450GB NVMe
Xeon CPU E3-1270 v6 @ 3.80 Ghz (4 core 8 threads)

Map is only 1k

Link to game save: https://vsysio.s3.amazonaws.com/Backup%20after%20oom.7z

**Comment by Reyalsorik** [comment]
My server has this problem as well.

Initially on 6GB of ram (8.0.5), increased memory due to 8.0.6, but the amount doesn't seem to matter. The leak continues to consume all resources and cause the instance to crash.

Windows Server 2019
4vCPU, SSD
The map is also 1k

This issue is not instant, I would estimate a similar timeframe to the opening user's issue.
Link to game save can be provided on request.

**Comment by vsysio** [comment]
Although I will say performance is freaking fantastic until it crashes.

**Comment by mirasrael** [comment]
Hi @vsysio Can you please make sever process dump just before server crash and attach here?

**Comment by vsysio** [comment]
We shut the server down for the night, the worry is the constant flapping will eventually corrupt the save.

If nobody else has provided a dump by this time tomorrow I'll see if I can get a few of us together tomorrow night to reproduce the problem and eventually provide a dump. I'm not strong with Windows desktop development; do I just right-click on the process in task manager and select Dump or is there like a tool I use to give more info? (you can instruct me as if I was well educated in the subject)

**Comment by espoire** [comment]
**I found a way to reproduce the memory leak.** I noticed this problem looming before the crash occurs and manually restarted my server a few times, which delays the problem. While watching my system's resource monitor, I linked permanent memory usage spikes to what my players were doing at the time. **Opening the UI window for anything that has a Storage tab -- that is, all containers and crafting stations -- takes a big bite out of server memory.** The size of the wasted memory seems to scale with how many storage and items are within range when the UI is opened.

There is also some kind of memory leak effecting the client. Some of this client memory can be reclaimed by disconnecting from a server and reconnecting, but some can only be reclaimed by restarting the client program. I'm unsure what causes this as yet.

Per the windows resource monitor, Eco's memory usage only very rarely decreases while running, but both the client and server tend to creep upwards while playing.

**Comment by mirasrael** [comment]
Can you please try with this executable?
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2955661/EcoServer.zip)

**Comment by mirasrael** [comment]
Version with fixed memory leak until hot-fix, hot-fix coming soon:
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2955715/EcoServer.zip)

**Comment by Shoe73** [comment]
Our server was locked up as well!!  Needs a FIX ASAP!

**Comment by espoire** [comment]
That .zip which mirasrael posted above worked for me. Bring it to the attention of your server admin.

**Comment by vsysio** [comment]
Confirming this released executable fixes the problem. Nice turnaround!! Thanks @mirasrael

**Comment by Reyalsorik** [comment]
This version appears to resolve my server issues as well. Thank you!

**Comment by ApophisUKP** [comment]
where do i install on a hosted server?
