### ISSUE TITLE
USER ISSUE: 8.0.6 Transfer Bug

### ISSUE THREAD

**Issue by Briland5** [StrangeLoopGames/EcoIssues#11635]
**Version:** 0.8.0.6 beta

**Steps to Reproduce:**
1. Log on to server
2. Transfer 1 currency to any other player's account with a public transfer tax enabled (works fine when tax is set to 0%)

**Expected behavior:**
The currency should have transferred

**Actual behavior:**
Crash to menu with stack trace

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods

Server encountered an exception:
Server encountered an exception:
 
<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay
 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Stats.PlayerActionManager`1.CreateTypedDefaultAction(User actor)
   at Eco.Gameplay.Stats.ConcretePlayerActions.PayTaxPlayerActionManager.CreateAtomicAction(User actor, Currency currency, Single amount)
   at Eco.Gameplay.Economy.Transfers.TransferWithTaxSeparate(BankAccount sourceAccount, BankAccount targetAccount, Currency currency, User source, User target, LocString description, LocString taxReason, Boolean notify, Single amount, Single taxRate, Single sellerTaxAmount, Single buyerTaxAmount, Boolean verify)
   at Eco.Gameplay.Economy.BankAccountManager.Transfer(Player player, BankAccount source, BankAccount target, Currency currency, Single amount)</size>
 
Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:  
    VRAM:     8079 MB
    Driver:   25.21.14.1891
<RI> Initializing input.
 
<RI.Hid> Failed to create device file:
 2 The system cannot find the file specified.
 
 
(Filename:  Line: 55)
 
<RI> Input initialized.
 
<RI> Initialized touch support.
 
UnloadTime: 0.432287 ms
Missing following icons: CeibaSeedPackItem, CompostablesItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem, WaterPumpItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)
 
Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject, WaterPumpObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)
 
Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2401)
 
Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
 
Unloading 12956 unused Assets to reduce memory usage. Loaded Objects now: 186654.
Total: 314.577190 ms (FindLiveObjects: 10.865699 ms CreateObjectMapping: 8.639877 ms MarkObjects: 277.683019 ms  DeleteObjects: 17.388593 ms)

**Comment by BlazeGuy2** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/11634
