### ISSUE TITLE
USER ISSUE: Get kicked out of the game every view minutes

### ISSUE THREAD

**Issue by ixolan** [StrangeLoopGames/EcoIssues#11647]
**Version:** 0.8.0.6 beta

**Steps to Reproduce:**
Try to play with several others on a server

**Expected behavior:**
You shouldnt get kicked all the time

**Actual behavior:**
Many players on the server get 
Connection timed out

```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Many players on the server get 
Connection timed out


```

**Comment by ixolan** [comment]
Connection timed out

Log File:
Initialize engine version: 2018.2.20f1 (cef3e6c0c622)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 750 Ti (ID=0x1380)
    Vendor:   
    VRAM:     2017 MB
    Driver:   23.21.13.8813
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.674440 ms
Missing following icons: CeibaSeedPackItem, CompostablesItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem, WaterPumpItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject, WaterPumpObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 14510 unused Assets to reduce memory usage. Loaded Objects now: 108924.
Total: 354.627450 ms (FindLiveObjects: 8.057365 ms CreateObjectMapping: 10.940599 ms MarkObjects: 310.293612 ms  DeleteObjects: 25.335140 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 108924.
Total: 334.901896 ms (FindLiveObjects: 6.889190 ms CreateObjectMapping: 9.112278 ms MarkObjects: 318.627718 ms  DeleteObjects: 0.272708 ms)

Missing following icons: CeibaSeedPackItem, CompostablesItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem, WaterPumpItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject, WaterPumpObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 14262 unused Assets to reduce memory usage. Loaded Objects now: 324877.
Total: 508.228724 ms (FindLiveObjects: 26.932904 ms CreateObjectMapping: 16.227260 ms MarkObjects: 431.091783 ms  DeleteObjects: 33.975676 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 324864.
Total: 462.173597 ms (FindLiveObjects: 31.806470 ms CreateObjectMapping: 12.180616 ms MarkObjects: 417.589776 ms  DeleteObjects: 0.596733 ms)

Missing following icons: CeibaSeedPackItem, CompostablesItem, FarmingFocusedWorkflowTalentGroup, FarmingFrugalWorkspaceTalentGroup, FarmingLavishWorkspaceTalentGroup, FarmingParallelProcessingTalentGroup, SaguaroSeedPackItem, WaterPumpItem
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<CreateMissingItems>c__Iterator3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>c__Iterator4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject, WaterPumpObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<BuildFromModKit>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>c__Iterator2:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 14728 unused Assets to reduce memory usage. Loaded Objects now: 344002.
Total: 597.724789 ms (FindLiveObjects: 33.598869 ms CreateObjectMapping: 14.383544 ms MarkObjects: 513.675565 ms  DeleteObjects: 36.066442 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 343984.
Total: 553.054097 ms (FindLiveObjects: 36.051047 ms CreateObjectMapping: 12.259423 ms MarkObjects: 504.060022 ms  DeleteObjects: 0.682871 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 343984.
Total: 537.946262 ms (FindLiveObjects: 27.512043 ms CreateObjectMapping: 11.219538 ms MarkObjects: 498.719479 ms  DeleteObjects: 0.494467 ms)

**Comment by espoire** [comment]
I can't be certain in your case, but I experienced similar problems related to https://github.com/StrangeLoopGames/EcoIssues/issues/11639 . Just before our server ran out of memory, users were disconnecting frequently. Restarting the server prevented this issue for an hour or two for us, and that like I posted has an updated server executable that doesn't have the problem (as far as I can tell from ~1 hour playtesting).

**Comment by BlazeGuy2** [comment]
Currently building new hotfix, should be out later today to hopefully address the issue.

**Comment by Naxos84** [comment]
We are experiencing the same problem.
red disconnect icon shows up for all players. and after 30 seconds (just a feeling) all players loose connection.

**Comment by BlazeGuy2** [comment]
@ixolan @Naxos84 Did the new hotfix fix your issue?

**Comment by Naxos84** [comment]
Didn't test this myself yet (maybe tomorrow)

But a friend of mine (playing on the same server) told me that he had this disconnect icon but did not get kicked...

I'm going to check that tomorrow myself.

**Comment by ixolan** [comment]
The hotfix fixed it for us - thanks
