### ISSUE TITLE
All House Items Work to Give House Value In Every Room

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#11642]
Every house item can be placed in every room for house value points, except General room. 

For example, a bed can placed in a Bathroom & Kitchen. A Latrine can be placed in a Bedroom & Kitchen. A Butchery Table can be placed in a Bathroom & Bedroom. All of these combinations give full house value to the room.

It does not work in a General room because it turns the room into whichever specialized object you place first.

This has been an issue since at least 0.8.0.5

**Comment by mirasrael** [comment]
This issue very old, at least since 0.7
