### ISSUE TITLE
USER ISSUE: Horrible Graphic quality

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#11648]
**Version:** 0.8.0.6 beta

I've just installed the newest update and have not changed a thing in the graphic settings. Everything is blurry af..
![20190312180145_1](https://user-images.githubusercontent.com/37971880/54220360-8626af00-44f1-11e9-807e-bd289d1cca45.jpg)
These were my setting all along but just like that the graphics look horrible.
If i change the global illimination to max, everything looks like it used to, but i only have 20 FPS :(

Highest graphic:
![20190312180132_1](https://user-images.githubusercontent.com/37971880/54220477-cb4ae100-44f1-11e9-9e75-658a6b013c0f.jpg)

Normal graphic:
![20190312180141_1](https://user-images.githubusercontent.com/37971880/54220503-d867d000-44f1-11e9-897c-3c2e39a62464.jpg)

**Comment by SeanAtr0n** [comment]
turn off bloom

**Comment by shark2222** [comment]
I confirm.

**Comment by shark2222** [comment]
Changing the global illumination value temporarily fixes this bug.
![20190314173556_1](https://user-images.githubusercontent.com/48383715/54494411-41fc2b80-48b0-11e9-9fbd-1a2e14f7ade4.jpg)
