### ISSUE TITLE
USER ISSUE: cant connect to world 

### ISSUE THREAD

**Issue by hintzsche** [StrangeLoopGames/EcoIssues#11644]
**Version:** 0.8.0.6 beta

**Steps to Reproduce:**
start game and continue game 

**Expected behavior:**
connectiong and starting the game 

**Actual behavior:**
The following error message popped up:
failed to connect
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
failed to connect
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

i dont use mods that not come with the game 
Server Error is invalid user trying to connect

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11548
