### ISSUE TITLE
USER ISSUE: Error when verifying login token: Error: TrustFailure (Authentication failed, see inner exception.)

### ISSUE THREAD

**Issue by eyvalon** [StrangeLoopGames/EcoIssues#11652]
**Version:** 0.8.0.6 beta
edit: same in 0.8.0.7 beta

**Steps to Reproduce:**
my eco server is on rootserver: ubuntu 16.04.6 LTS
(i know: you are not supported linux, but perhaps you can help, please)

- nobody can join the server when "RequireAuthentication": true
   (even if the firewall is off)
- ServerLogMessage: "Error when verifying login token: Error: TrustFailure (Authentication failed, see inner    exception.) Invalid user trying to connect"
- whitelist: true/false (both are not possible)
- user in whitelist: slgid
- ports (3000,3001) are open
- mods: no
- i can join on other servers, but i don´t know if they have auth:true

**Expected behavior:**
join on my ecoserver

**Actual behavior:**
- nobody / i can´t join the server!

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed!
and i have a legal version buy on strangeloopgames.com

**Comment by mirasrael** [comment]
All legal servers should run with RequireAuthentication true.
How do you run your server? With mono of which version?
We tested it with Mono 5.16.

**Comment by mirasrael** [comment]
Alternatively you can try run server within Docker image (available on DockerHub strangeloopgames/eco-game-server:0.8.0.7-beta)

**Comment by eyvalon** [comment]
@mirasrael:
I run the ecoserver with mono 5.18.

**Comment by mirasrael** [comment]
Can you try with mono 5.16? I remember we had problem with newer versions

**Comment by mirasrael** [comment]
You can install docker and just run: `docker run -it --rm -p 3000:3000/udp -p 3001:3001 strangeloopgames/eco-game-server:0.8.0.7-beta`

**Comment by eyvalon** [comment]
i removed mono 5.18, installed mono 5.16
and **_voilà_**
i can join :+1: 
**no authentication failed error!**
big thanks to you for help :1st_place_medal:

**Comment by eyvalon** [comment]
Solved!
