### ISSUE TITLE
Eco Server information

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#11650]
Version: 0.8.0.6 beta

Steps to Reproduce:

1. Just start the game 
2. Click on New game
3.  Click on a server to see the info about it.

Expected behavior:

That you should be able to see more information
about the server itself if skill on action is enabled.

What is the skill rate on the server. 

Actual behavior:

 Right now I think the game is really lacking a lot of the 
information when you start up the game. 

I would really like to see more information presented 
when you startup the game and are looking at the
servers. 

Now sometimes players put that they have an increased
skill rate but don't list what the skill rate is maybe 
make it so that shows up on the screen when you select
a server.

Also I would really like to see on there as well if skill points
per action is enabled on the server it could be a yes / no 
and if it is list what that rate is bellow it. 

Also maybe if they have mods installed or not and 
if they do then list the mod names that the
server is running. 

I mean you have the room on the screen there is a lot of space
that is just empty there anyways. I think it would really help improve
a players decision to play on a certain server.

Personally I like playing on servers where the skill point per action is
enabled. But unless they put it in the title you don't know if it is or
not and the server title can only be so long. 

The same would also apply with skill rate on craft as well 
I would really like to see if it is enabled yes / no and
if it is yes then what is the rate that it is set to. 

It would also be really good that if you added any of these
options that you make it searchable by that option as well
when you search for a server. 

can some one look into doing so work on the information screen
for the servers please?  I really do believe that the information
screen is lacking some information here. 

![Eco World information screen](https://user-images.githubusercontent.com/38896397/54235516-055ab980-44d7-11e9-8fac-3b5105276dc3.jpg)

**Comment by thereporter42** [comment]
This is more than just a "suggestion" this needs to be re tagged this is a legitimate issue. 
You are missing key pieces of information on the server information screen.

Please fix this issue immediately!

**Comment by D3nnis3n** [comment]
This is not a bug, but a feature request, therefore an suggestion.

**Comment by thereporter42** [comment]
Oh Bullshit... this isn't a feature request what so ever. .who the hell are you.. are you
even a developer for this project. If not get out of this thread.  This is BS I am not going to submit any more tickets since the devs clearly don't give a shit about anything the people who are playing this game
actually says.

This game is doomed for failure if they continue down this path.

**Comment by D3nnis3n** [comment]
Please keep calm. I'm moving your issue to suggestions and we'll take a look when we're working at it. But this is not a bug.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/758

**Comment by thereporter42** [comment]
What ever I am done with this game you won't take anything anyone is saying seriously
anyways.   Now you close my ticket... After you said you were going to look at it. 

Get me the lead developer for this project immediately! This matter is not resolved!

**Comment by D3nnis3n** [comment]
I once again ask you gently to calm down.

What you are requesting is an extension of an existing feature and not a bug - we track those on the suggestions tracker, like i said and where i moved your issue to. Issues on this Tracker are bugs in existing features. This is not the case here. We'll take a look on this matter when we come to it, it's not a high priority thing.
