### ISSUE TITLE
After update to 8.0.6 Skid Steer can not pick up stone or ore that has stopped moving.

### ISSUE THREAD

**Issue by braxton33** [StrangeLoopGames/EcoIssues#11654]
**Issue:** Skid steer can't pick up rock/ore that's broken and laying on the ground.
**Recreate:** Break a few rocks in front of the skid steer, let them rest on the ground, and then try to pick them up with the skid steer.

The skid steer is no longer able to pick up items from the ground after the most recent. The hotfix to 8.0.7 does not fix the issue.
Any rubble that has completely stopped moving is completely invulnerable to the skid steer and when too much has built up you've effectively got a 100 ton paperweight until you dig it out by hand.
It can still dig, and still pick up blocks that are falling, but after they've reached 0 velocity they can not be picked up.

**Comment by Leilakey** [comment]
I think slowly it is better for you to do less beta if you can not fix the stone mistake  Skid steer snd excavator fast! A lot of people are upset by that. I'm waiting for two days not much annoying for the game.

**Comment by Leilakey** [comment]
The CEO 8.0.7 beta is bad it would be time for a new one or it must be the frozen stone be heard now occur and make the game bad! So many servers have this going on and it has to be penetrated very much which is really bad!

**Comment by Rycoviac** [comment]
Yea, with the last few updates, something broke every time. Currency bugs in shops and exchange,, money transfers, and server issues and crashes as hell... we lost almost our whole playerbase. Even the hardcore-players now anoyed about that they cant use Skid Steers and Excavators now or just have problems to join the server. Maybe break the farmers job next and we call it a day if you really want get rid of all the players left =D
