### ISSUE TITLE
USER ISSUE: sand turns to dirt with shovle

### ISSUE THREAD

**Issue by cocoguy19** [StrangeLoopGames/EcoIssues#11658]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
shovel sand with wood shovel

**Expected behavior:**
pick up sand

**Actual behavior:**
it turns it into dirt

**Do you have mods installed? Does issue happen when no mods are installed?:** no modsinstalled

**Comment by D3nnis3n** [comment]
Are you trying to pick up actual sand. The yellow colored blocks in the desert are actually colored dirt, not sand.

**Comment by cocoguy19** [comment]
tried sand from desert and sand from side of river where am is supposed to get sand?

**Comment by cocoguy19** [comment]
im sorry to have wasted your time i found sand in beach that works
