### ISSUE TITLE
Passenger look rotation seems to be in world space

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11655]
player rotation, shouldn't be changing here
![passengerrotationbug](https://user-images.githubusercontent.com/774628/54238929-02f85f80-44d7-11e9-8bbf-5df5fe9ba349.gif)

**Comment by beastyn** [comment]
@SeanAtr0n 
I was cheсking this one after last update. Player rotation is a bit creepy. Tractor is not moving, just player trying to look back.
![bandicam 2019-04-04 09-36-05-780](https://user-images.githubusercontent.com/27898520/55529953-494b7380-56bd-11e9-983d-a3c143adaf96.jpg)

**Comment by SeanAtr0n** [comment]
fixed in release
made a new issue for the steam tractor, has more to do w/ IK, this bug was about network syncing other players
