### ISSUE TITLE
People act like others in chat

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#11659]
same issue as these 2 both closed sadly.
https://github.com/StrangeLoopGames/EcoIssues/issues/9494
https://github.com/StrangeLoopGames/EcoIssues/issues/9539

![image](https://user-images.githubusercontent.com/31536813/54258552-4a2c3200-4563-11e9-9622-d064f1053d18.png)
![image](https://user-images.githubusercontent.com/31536813/54258570-57492100-4563-11e9-9fa2-1c7810aab652
![image](https://user-images.githubusercontent.com/31536813/54258875-4816a300-4564-11e9-9ea7-98d76b6d4b4b.png)

![image](https://user-images.githubusercontent.com/31536813/54258598-6a5bf100-4563-11e9-961d-4d80392e4d2d.png)

![image](https://user-images.githubusercontent.com/31536813/54258620-81024800-4563-11e9-9cea-f582c1348b34.png)

![image](https://user-images.githubusercontent.com/31536813/54258647-92e3eb00-4563-11e9-911a-8e4aa7202d84.png)

![image](https://user-images.githubusercontent.com/31536813/54258680-a7c07e80-4563-11e9-9314-e836b10b43c7.png)

**Comment by Conchipedia** [comment]
![unknown](https://user-images.githubusercontent.com/29383891/54280745-17e4f980-4590-11e9-8295-ef80e45b7b83.png)
they seem to **know** that they have bypassed something!!

**Comment by Maxeman5126** [comment]
To clarify a little on this (I am the "i" user here) This is done by sending a carriage return without a line feed, which allows a user to type prior to their name being displayed. The chat starts at # in general so with the right spacing, including a mention of another users name (which links them and makes it look like they are saying it), you are able to appear to be another person. \r(carriage return)[8 spaces][username to impersonate]" :"[message]
to get just the carriage return you can copy it from an application like notepad++ where you can see "invisible" characters. so the following would "impersonate" Kill3rz33:
\r        Kill3rz33: message here
