### ISSUE TITLE
Sweeping hands picks up 8-15 but not full 20 after patch 0.8.0.7

### ISSUE THREAD

**Issue by braxton33** [StrangeLoopGames/EcoIssues#11656]
**Issue:** It won't pick up a full 20 even when you're inches from loose ore. It grabs a good bit, but not the full batch. 
**Recreate:** Break a ton of loose ore and try to pick it up.

After the first large batch it grabs, it's back to only grabbing one at the time, even when they're inches from your face.

**Comment by mirasrael** [comment]
Issue related to non-broken blocks which counted as eligible targets (counts to 20 blocks), but ignored on the server. Until fix as work around you can prefer to break blocks before grabbing them.
