### ISSUE TITLE
Removing Dirt Ramp makes Block removed but Model gets not removed

### ISSUE THREAD

**Issue by excedra** [StrangeLoopGames/EcoIssues#11653]
**Mention which version of Eco this bug is occurring in:** 
8+, using Windows Dedicated Server and Windows Client
**Add the steps to reproduce the bug:**
When removeing a dirt ramp (or other ramps) with a shovel, the game i likely to remove the block - but not the model. You can place any other block there, but the model / graphics stay and gets not replaced or removed. Reconnect fixes this issue. Somethimes, this also happens also with other blocks.

**Comment by BlazeGuy2** [comment]
@excedra can you post some pics to show this?

**Comment by excedra** [comment]
Currently (8.0.7), i did not have the issue again. Will post it, when it happens again.

**Comment by BlazeGuy2** [comment]
Alright, open another issue with pics if this occurs again.
