### ISSUE TITLE
USER ISSUE: CAN'T CONNECT (AGAIN)

### ISSUE THREAD

**Issue by AquaticMC** [StrangeLoopGames/EcoIssues#11657]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. open game
2. try to join friends game
3. fail to connect
4. says it couldn't connect to send error

**Expected behavior:**
joined friends game

**Actual behavior:**
didn't work

**Do you have mods installed? Does issue happen when no mods are installed?:**
didn't work

**Comment by mirasrael** [comment]
Hi @AquaticMC 
Is server running on external IP or this is private server?

**Comment by BlazeGuy2** [comment]
Closing due to no response.
