### ISSUE TITLE
Images on signs do not respect sign borders

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11661]
![malenkei](https://user-images.githubusercontent.com/25908592/54280176-28e53900-4597-11e9-86f9-5bd04c046e0d.png)
https://github.com/StrangeLoopGames/EcoSuggestions/issues/753

**Comment by WeaselDog** [comment]
Fixed as part of https://github.com/StrangeLoopGames/EcoIssues/issues/17527
