### ISSUE TITLE
USER ISSUE: Bugged water pump can still be craftet

### ISSUE THREAD

**Issue by Falky870** [StrangeLoopGames/EcoIssues#11663]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Idk if its a bug or not with 8.0.7 u can still craft the bugged (white block) water pumo at the assembly line and when u put that one it wont work 

**Expected behavior:**
-

**Actual behavior:**
u can still craft it , has no function , if u go some blocks and look at it it flys above the ground

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods used

**Comment by craig-jong** [comment]
fixed in master
