### ISSUE TITLE
Need ability to change meteor time

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11665]
1. Changing in Disaster tab:
![image](https://user-images.githubusercontent.com/3536496/54309792-1adeea80-458e-11e9-9a8b-b4a8f3e6f647.png)
2. Chat command, add hours.

**Comment by johnkslg** [comment]
1. Changing in Disaster tab:
![image](https://user-images.githubusercontent.com/3536496/54309792-1adeea80-458e-11e9-9a8b-b4a8f3e6f647.png)
2. Chat command, add hours.

**Comment by redwyre** [comment]
Setting the impact days does work, it overrides the current value (I thought it might be from server start, probably could make that clearer)
