### ISSUE TITLE
Performance dropping in specific level

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11664]
https://download.godsofwar.de/eco/cycle-7.zip
Performance failing at 1000,1000
Dennis reports 12FPS on a powerful rig

**Comment by johnkslg** [comment]
Disable meteor as it has only 15 min to impact

**Comment by D3nnis3n** [comment]
Go to the Waypoint "Royal Palace" and take a good look at it. That makes it lag. And it's beautiful!

**Comment by D3nnis3n** [comment]
Graphics Settings are default ("Reset"), WQHD (FHD doesn't make a noticeable difference), but with View Distance on 100.

RTX 2080
Ryzen 2700 @ 4,2 GHz
Samsung Evo Plus 970 1 TB
32 GB DDR4-3600 RAM

**Comment by mirasrael** [comment]
@metachronism can you test with your latest client optimizations?

**Comment by mirasrael** [comment]
Testing stand: GeForce 1060, Default Settings, Unity Editor
Tested on master. Seems greatly improved: ~70 fps. 
Tested on staging, improved over my last testing (was ~20 fps), now: ~40 fps 

Closing for now. Feel free to re-open if you will not see improvements after 8.2 release.

**Comment by D3nnis3n** [comment]
![1](https://user-images.githubusercontent.com/25908592/55185367-7e733580-5194-11e9-93d5-1c24d0b1d215.png)
![2](https://user-images.githubusercontent.com/25908592/55185368-7e733580-5194-11e9-9dad-de9e3ba3cd1b.png)
![3](https://user-images.githubusercontent.com/25908592/55185369-7e733580-5194-11e9-89df-2a52c6662d98.png)

Facts:
- Performance when standing still got much better, but could still be better.
- Performance mostly drops when in /record or moving, especially when chunks are being loaded. I can clarly see the connection between massive fps drops and chunk loading. They also load extremely slow.
- As you can see in my task manager screenshot i'm no longer limited by either CPU nor GPU.
- Position makes no difference, anywhere around the building you can experience the same. Okayish fps when standing, bad when moving.

**Comment by mirasrael** [comment]
Seems most FPS drops here is coming from chunk rendering. @metachronism can you look into this?

**Comment by metachronism** [comment]
Dennis is CPU limited in his posting.  You are always either GPU or CPU limited.  Its easiest to tell based on GPU since its generally just one load, it GPU is not maxed (100% usage) then you are CPU limited.

Unity does not use all CPUs on any given machine

**Comment by D3nnis3n** [comment]
I shouldn't be CPU limited, though. Hardware is powerful enough to support
any other game with way better results. Eco should at least perform
similar. Cannot Tell me Eco is so special, it doesnt work on a Ryzen, but
gets beaten by an older and weaker intel. Considering there are similar
issues with intel Hardware, too, i can't give into that.

Eric Anderson <notifications@github.com> schrieb am Di., 2. Apr. 2019,
03:13:

**Comment by mirasrael** [comment]
Tested (on Intel CPU) for this save, FPS seems high (up to 89 FPS), but I have constant disconnect sign and very slow chunks loading.
![image](https://user-images.githubusercontent.com/475445/56888323-58cf9980-6a7c-11e9-8a3e-32aa3d161389.png)

**Comment by D3nnis3n** [comment]
I do have very low FPS, slow chunk loading but no disconnect signs. Whenever chunk loading occurs, i get heavy fps drops in addition to the low general fps.

**Comment by mirasrael** [comment]
@D3nnis3n should we say it fixed with latest 8.2 changes?

**Comment by D3nnis3n** [comment]
I'd like to wait until Sean fixed the resolution problem. I want to see what my fps with full hd is. If that one does not drop below 40 as i expect, i'd close that out.

**Comment by D3nnis3n** [comment]
It does drop below 40 massively even with Full HD. You can close it anyway and wait for other users to open new performance issues. I've played a bit and while in empty areas fps is really good, it drains quickly in areas that have buildings, at least in the current build. It's still nowhere near optimal for video making, but for playing it got noticeably better. Let's see what the others say. For me personally performance is still too low, but that does not need to apply to others.

**Comment by mirasrael** [comment]
I reduce priority and move to 9.0. It seems like a good save for checking, probably we should just add it to pool of saves for optimization testing.

**Comment by johnkslg** [comment]
Closing this as its quite old
