### ISSUE TITLE
All room info gone, need to replace block in every room to reset it

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11662]
![image](https://user-images.githubusercontent.com/431728/54293835-65974b80-45fc-11e9-8b42-9883c81bbffe.png)

I see the property ownership, but not room details

**Comment by mirasrael** [comment]
Seems like was last during moving panel to right side...

**Comment by mirasrael** [comment]
Hmm. If you break the block in the room and place back then it will start working

**Comment by redwyre** [comment]
It seems that the problem is actually that all room info is gone and needs to be reset by changing a block

**Comment by mirasrael** [comment]
@redwyre Where did you get this issue? I'm not sure about mine, because I switched many times between staging, release and master, so my problem may be in result of reverse migration. I tried with official EU server save and it converted and working well (no room data was lost).

**Comment by redwyre** [comment]
My HW server, I updated from 0.8.0.5 to 0.8.0.7

**Comment by Reyalsorik** [comment]
After rebooting my server, we lost all room information.

I'm not sure if any sort of conversion took place, but on reboot I get the following in the startup log:
(this happens everytime, world was created on 8.0.5 ~10 days ago iirc)
```
[00:22:53.929] [8] [ Info] [Eco] Loading World...
[00:23:01.507] [8] [ Info] [Eco] Converting world to new format...
```

8.0.7 => 8.0.7 (no updates were done, just stopped the server, restarted it).

**Comment by mirasrael** [comment]
@Reyalsorik as you became fan of my custom builds there another one for you ;)
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2977571/EcoServer.zip)

It contains fix for rooms, so they shouldn't become broken again. Also I added admin command: `/repairallrooms` which you can use on existing save to repair all broken room.

**Comment by mirasrael** [comment]
@redwyre Thanks for your save, it helped me to reproduce an issue. It happens if you convert the world, then stop server in abnormal way (not graceful shutdown) and on next load it loose all rooms information. It was a problem with serialization.

**Comment by mirasrael** [comment]
@seccombew I think it should be a critical issue, it isn't so hard to reproduce and really breaks many things in game (all stores stops working, all rooms stops contributing skill points etc).

**Comment by Reyalsorik** [comment]
Thank you @mirasrael! I believe it worked. :)
