### ISSUE TITLE
[Server] 0.8.0.7 Upgrade failure upgraded from 0.7.8.6

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#11671]
Version: 0.8.0.7 beta server

Steps to Reproduce:

    1. install version 0.7.8.6 of the Eco server
    2. Start a world running this server and let the server start up  fully.
    3. backup the database directory (Storage) to another location
    4. Properly shut down the server and update to 0.8.0.7 of the Eco server
    4.  Now delete all your existing config files and everything in the directory
    5. Copy back over your storage directory to where Eco is installed
    6. Try and start ther server now

Expected behavior:

Expect that with the existing database that the game
would load correctly. 

Do you have mods installed? No

Actual behavior:

Well this is intresting I have been gone for a while and 
I upgraded from an older version of the server 0.7.8.6
and was updating to the new version of the server 0.8.0.7

Now I backed up just the database and copied it to
another location.  The database was fine and worked perfectly
and started up fine with 0.7.8.6 with no issues.

So I backed up the Storage directory I deleted everything
in the directory and downloaded the 0.8.0.7 zip file
from the website. I installed everything fresh and then 
copied back over the storage directory which I had backed up
in another location into the Eco server directory and by doing this 
really the server should start but instead I got this error. 

"Message: Error(s) occured when loading world 
Source: Eco.core
System.Exception: Error(s) occured when loading world
    at Eco.core.Serialization.Datastore.LoadAsync[T](String folder, Action `2 createFunc) 
    at Eco.World.PersistentChunkGrid.Load()
    at Eco.World.WorldPlugin..ctor()"

I mean I really didn't want to restart my world again and I mean I should be able to 
use an existing world on the new server there was nothing special about this world
it was just a randomly generated world on the old sever but it now looks like I can't
even use it.  What good is having a world when you can't upgrade to the latest 
version without having to start a new world.  I  really don't want to start a 
new world here. 

Please look into this and fix this issue please!  How can I get my world to load??

Like I said everything was deleted from the server directoy and was used right 
from the 0.8.0.7 zip file that I downloaded from the site.  The only thing put 
in there was just the DB that was copied back over and there were no mods 
installed before either it was a stock server. 

![Eco server update Error March 13 2019](https://user-images.githubusercontent.com/38896397/54334989-3f1de400-45ed-11e9-994e-bbd22b38fcc7.jpg)

**Comment by thereporter42** [comment]
What why do it again it is not going to change anything it is going to have the 
same results some one needs to fix this issue I do Not want to start a new
game. This is a valid bug I was running 0.7.8.6. 

This matter needs to be looked into immediately!

**Comment by thereporter42** [comment]
So I installed 0.7.8.6 again in a seperate directory installed the server fully. 

Then I shut it down properly and then updated to 0.8.0.7 Beta and now
it is throwing me new errors. I give up I mean you guys are not 
even investigating this anyways.  I am writting tickets for nothing. 


There are the logs if anyone cares to actually take the time to look
at this ticket. 

[log_190314013710.log](https://github.com/StrangeLoopGames/EcoIssues/files/2968210/log_190314013710.log)


![Eco Server Error March 14 2019](https://user-images.githubusercontent.com/38896397/54386625-028ad080-465f-11e9-967d-646bcad293ec.jpg)

**Comment by redwyre** [comment]
@thereporter42 please try upgrading from 0.7.8.6 to 0.7.8.9 first (to make sure it has the latest schema for that line), and let us know if there is a problem with that upgrade.
Then you can try to 0.8.0.0 or directly to 0.8.0.7

**Comment by thereporter42** [comment]
I don't have 0.7.8.9 I mean this is failing constantly you have your logs you need to look into this.  This
should not be occuring you have the logs! Please remove the Needs information I have provided you the logs!

**Comment by thereporter42** [comment]
Redwyre are you a dev on this project? if not then why you posting in this ticket I don't see any tag on your name to say that you are a dev on this project. Please don't post here requesting information if
you are not a developer on this project.

The logs have been attached on my previous post please remove the need information
tag as I have provided the logs needed.

Thank you.

**Comment by mirasrael** [comment]
@redwyre is dev on this project
![image](https://user-images.githubusercontent.com/475445/54410368-35cf6d00-46fc-11e9-9ee6-32009cb85ee5.png)
You can download 0.7.8.9 just like you downloaded 0.8.0.7 - just replace version in link.
https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v0.7.8.9-beta.zip

I asked you for world save file, not for logs. Log won't help much, but I can try to convert your save file and try to find an error.

**Comment by D3nnis3n** [comment]
Did you try the requested steps in the meanwhile?

**Comment by mirasrael** [comment]
Closed due to no response.

**Comment by thereporter42** [comment]
What do you mean closed due to no response this is bullshit .. I did respond 
and was responding. This is absolute BS who is the head developer for this
project I want to speak to them now you are closing off tickets when the issues
are not resolved and YES i was responding and I attached the needed logs 
and everything. 

Screw this the Eco development team is absolutely useless 
and don't give a damn what the people say on this game 

This project is doomed for failure as they just close off tickets
without fixing the issue. Absolutely horrible development 
team! 

Get me the lead developer now this matter is in NO way resolved!

**Comment by redwyre** [comment]
@thereporter42 You were asked to try a smaller upgrade, and to provide a copy of your save, neither of which you have done. We are _trying_ to help you here, and you are just being rude in return.

Unless you are wiling to provide a copy of the save, and/or try the smaller upgrade, there is nothing we can do for you.

**Comment by thereporter42** [comment]
wow you are the one being rude here redwyre I did respond and I added the
needed logs. 

I want to speak to the head developer now!  I am sick of people like redwyre
closing off tickets when they are not resolved. This is an absolutely horrible 
project.

**Comment by D3nnis3n** [comment]
I'm going to give you this last chance to understand that we don't need your logfiles but your savegame or that you try to do the suggested minor upgrade first. If your only intention is to be rude to our developers and causing disturbance, i'll lock the comments.

**Comment by Moor718** [comment]
Hello, I got the same problem as @thereporter42. I get the exact same log entries. I've already updated version by version from 0.7.8.7 to 0.7.8.9. But I can't get 0.8.0.0 or higher working. Here is a link to my save file (Had to upload it to a file-hoster since the archive exceeds the maximum upload size):

[https://www.file-upload.net/download-13554000/Game.zip.html](url)

**Comment by thereporter42** [comment]
Thank you Moor718 now maybe they will start taking the report seriously. 
See it isn't just me getting this error.

And by the way here is my game DB
http://www.filedropper.com/gamedb

**Comment by mirasrael** [comment]
@thereporter42 you archive is broken. Try to re-upload it.

**Comment by mirasrael** [comment]
@Moor718 thanks for your save! It helped to identify a problem and to fix it. Fix should be in 8.1 version (I was able to migrate your save with the fix). I fixed the original problem (posted in issue description). Another log with spam of `partial identifier` seems to be a problem with the installation, should be fixed by reinstall.

**Comment by mirasrael** [comment]
@thereporter42 no more need your save.

**Comment by thereporter42** [comment]
Wow no thanks for me and I was the one that found this bug first and Misrsreal I uploaded
it when I had time.  Wow you people are rude.

And here is my game DB anyways. 

https://gofile.io/?c=tkSGml

**Comment by mirasrael** [comment]
@thereporter42 thanks for founding and reporting this bug.

**Comment by Moor718** [comment]
Hey,
I just checked it with the same file as I provided with the newest version. As you can see, I get the same error as before. Can you please check if that bug still exists?
![image](https://user-images.githubusercontent.com/40657425/55345769-07e67880-54b1-11e9-9221-d3172b0e90a7.png)

Best regards

**Comment by mirasrael** [comment]
@Moor718 fix not yet deployed to Steam. You should expect it in 8.1-beta-8.

**Comment by mirasrael** [comment]
@Moor718 8.1-beta-8 released to steam (as bleeding_edge). Can you confirm your world is working now?
