### ISSUE TITLE
Items missing when being placed - Beta 0.8.0.7

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#11679]
Several items have just disappeared when placed: Jack o Lanterns, Hew Boards, etc

**Comment by ClayC90** [comment]
Taking Hew Boards as an example, you equip it and right click to place on ground, but it disappears?

**Comment by D3nnis3n** [comment]
I cannot reproduce this, could you make a little video for us?

**Comment by D3nnis3n** [comment]
Closed due to no further information.
