### ISSUE TITLE
No admin commands for bank accounts

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11672]
Several users removing their self by exident from bank account management and lossing access to their accounts. as an admin you cannot help in this case because there are no admin commands avaliable to get back access to these bank accounts.
In minimum following commands are needed:

/manageaccount [ID],[user]   will add user as manager to bank account with ID
/deleteaccount [ID]                will delete an account even if there is still currency on it. 

Commands like /changeowneraccount [ID],[newuser] would be great, but is not that important than the previous one.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#755
