### ISSUE TITLE
8.0.7 User cannot transfer money to own account when in treasury tax is set

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11673]
In actual version you can set in treasury two transfer tax. If you have set a transfer tax for own accounts grather than 0, you cannot transfer any money. You will get the message, transfer complete, but nothing happend and as well no chat log is shown.
When you set transfer tax for own accounts to 0, than it is again working fine.

Issue is not seen if you have transfers for public accounts and transfer tax is set in treasury for these transactions.

**Comment by BitsBytesGaming** [comment]
It's trying to tax an account with no money in it when you try to transfer to it. There might have to be an exclusion for this tax for an account with a balance of less than the value of the tax that's trying to be applied.

**Comment by Alteraner** [comment]
then i would recommend to change the sequence during the transfer. Instead of first do the tax and then do the transfer, if you turn around, you would not have this issue. If i would like to transfer from an group account to an personal account 10$ and 10% tax, only 9$ reached to the personal account. If you first try to tax the 1$ and then transfer the 10$ it would not work. Better would be transfer 10$ and than tax 1$.

**Comment by Alteraner** [comment]
Okay, i can confirm, it is caused of the tax is been calculated before the transfer. so if the target account is empty, it is not working. So if my account is empty i do not have a way to transfer some money to my account.
So users are in a dead lock situation.

**Comment by D3nnis3n** [comment]
Also applies to treasury.
