### ISSUE TITLE
ECO causing BSOD's

### ISSUE THREAD

**Issue by Bram-Boris** [StrangeLoopGames/EcoIssues#11674]
Hello,

I recently bought ECO but encountered an issue that prevents me from playing normally.

My PC is constantly crashing with a BSOD:  "video _scheduler_internal_error".
This is only happening with ECO, other games like CS:GO and Battlefield 5 do not have this issue.
I already updated drivers/downgraded drivers

Is there anything I can do?

System info:
Win 10 Pro 1803
Ryzen 2700X
RX580
16GB Ram @3200mhz

**Comment by BitsBytesGaming** [comment]
I've got a few things you might try:
1. Check for Windows updates.
2. Run "chkdsk /f /r" from cmd (as admin).
3. Remove any overclocks to the default clock speed.

**Comment by Bram-Boris** [comment]
Windows is updated, not running any OC. This happens everywhere, not a specific area. I have not tried different servers yet.

**Comment by redwyre** [comment]
Unfortunately that is an issue with your graphics driver, make sure it's the latest version.
If you are getting the issue with the latest driver you can report it to AMD at http://www.amd.com/report

**Comment by Bram-Boris** [comment]
@redwyre Yes, I do understand that, already switched drivers with DDU. But this is only happening to ECO.

**Comment by Bram-Boris** [comment]
I noticed some other things when testing.
When ECO is crashing, then I can still hear and talk to other people. After 10-15 seconds my system freezes and eventually BSOD's are there any logs I can share?

**Comment by redwyre** [comment]
Sorry @Bram-Boris didn't see your new reply. To grab the log files: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Also can you try 8.1 as it has a number of optimisations that may fix the issue for you.

**Comment by Bram-Boris** [comment]
After playing many more hours it did not crash again. I'm guessing it was just a issue on my end. Thanks for helping.
