### ISSUE TITLE
Great Red Oak lost forever in lake - Beta 0.8.0.7

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#11675]
I chopped one of that great red pine trees with a stone axe.... it took a life, but it would render A LOT of wood. When cut, it fell down inside the lake and it was with great surprise that a log of that size simply disappeared :(

I dived several times, but can't really find it. The point is it would be impossible to not find it, because its size is about the same size of the lake's diameter XD
Img https://pasteboard.co/I5qmYib.png

**Comment by Blanclour** [comment]
Re-logging may cause it to appear again.

**Comment by SlayksWood** [comment]
@criptonauta, @Blanclour  Do you have this issue in the latest versions of the game?
merged with #11487

**Comment by criptonauta** [comment]
> 
> 
> @criptonauta, @Blanclour Do you have this issue in the latest versions of the game?
> merged with #11487

@SlayksWood I still noticed some disappearing trees in 8.1.3. I'm not having the issue with 0.8.1.4
