### ISSUE TITLE
0.8.0.7 Focused Workflow: Milling has no effect.

### ISSUE THREAD

**Issue by espoire** [StrangeLoopGames/EcoIssues#11682]
The Mill is the only crafting station in the room, and thus the recipes in the screenshot below ought to take 30s, rather than 1m. It's possible that the talent description is unclear, and that the requirement is intended to be something other than "having its own room", but that's how I understood it.

![image](https://user-images.githubusercontent.com/16272456/54411040-e406f280-46bb-11e9-8d13-cd578d77e3bc.png)

Either, the talent should make all the craft time on these recipes half of what it currently is, or the talent description might need clarifying.

**Comment by Urbautz** [comment]
I can confirm, no change in craft time.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/54853628-a868bb80-4cad-11e9-8913-8f8fbf33d0d6.png)

![image](https://user-images.githubusercontent.com/18184943/54853642-b0c0f680-4cad-11e9-993e-3ceeb25d7f18.png)


This was an issue with many recipes spread out through different templates.
