### ISSUE TITLE
more transactions can not be clicked

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11686]
In Transaction Details for you account you only see the first day's till the list is full. the number below with more transactions cannot be clicked. Recommend to change the order of transactions and show the newest on top and make the number clickable again. 
![image](https://user-images.githubusercontent.com/47274045/54439871-ef006800-4739-11e9-814f-2564510f35c8.png)

**Comment by SlayksWood** [comment]
merged to #13722
