### ISSUE TITLE
USER ISSUE: Blast Furnaces pollute when out of power

### ISSUE THREAD

**Issue by SeruleBlue** [StrangeLoopGames/EcoIssues#11681]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1) Start a project at a Blast Furnace.
2) Let the Blast Furnace run out of fuel with the project still active.

**Expected behavior:**
The Blast Furnace's sewage should stop flowing.

**Actual behavior:**
The Blast Furnace's sewage continues to flow. I started a project and left for 2 hours. When I came back, the furnace was out of fuel, but it was still spewing sewage. The amount of ground pollution was massive.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods.

**Comment by BlazeGuy2** [comment]
@SeruleBlue can you post your world file where this is happening?

**Comment by SlayksWood** [comment]
0.8.1.0 staging-8:
When fuel runs out in the Blast Furnace, it stops working, but the waste water continues to flow. If you cancel the craft, nothing will change. The only way to stop: add fuel and put the craft, the craft must stop itself.
![image](https://user-images.githubusercontent.com/45708377/55403297-31111280-555e-11e9-8832-419e4c09123c.png)

![image](https://user-images.githubusercontent.com/45708377/55403319-40905b80-555e-11e9-824e-d3d46cc891c8.png)

**Comment by SlayksWood** [comment]
It is fixed in 8.2
