### ISSUE TITLE
USER ISSUE: problême avec les outils

### ISSUE THREAD

**Issue by Ripley2208** [StrangeLoopGames/EcoIssues#11693]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

**Expected behavior:**
aucun mouvement lorsque j'utilise les outils

**Actual behavior:**
les outils que j'utilsise me font tournoyer autour de la cible sans que je réussisse a frapper ou même a tirer ma cible.
Soit je tournoye autour ou je tombe car je bouge sans même le vouloir.  j'ai même désinstaller et rien n'y fait.
 tomb tombe ou je tournoye autour tombe  tombe ou

**Do you have mods installed? Does issue happen when no mods are installed?:**
les outils que j'utilsise me font tournoyer autour de la cible sans que je réussisse a frapper ou même a tirer ma cible.
Soit je tournoye autour ou je tombe car je bouge sans même le vouloir.  j'ai même désinstaller et rien n'y fait.
[eco_probleme.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2972953/eco_probleme.zip)

 tomb tombe ou je tournoye autour tombe  tombe ou

**Comment by BlazeGuy2** [comment]
Translation to English: 
Version: 0.8.0.7 beta

Steps to Reproduce:

Expected behavior:
no movement when I use the tools

Actual behavior:
the tools I use make me spin around the target without being able to hit or even shoot my target.
Either I spin around or I fall because I move without even wanting. I even uninstall and nothing helps.
falls falls or I spin around tomb falls or

Do you have mods installed? Does it happen when no mods are installed ?:
the tools I use make me spin around the target without being able to hit or even shoot my target.
Either I spin around or I fall because I move without even wanting. I even uninstall and nothing helps.
eco_probleme.zip

falls falls or I spin around tomb falls or

**Comment by BlazeGuy2** [comment]
@Ripley2208 Can you upload a video showing this issue?

**Comment by Ripley2208** [comment]
there is already a video attached to it (echo_probleme.zip)

**Comment by redwyre** [comment]
Hi @Ripley2208, the zip file contains a project file but not any actual video, you will need to export/render the video and upload that

**Comment by Ripley2208** [comment]
C'est compliqué, j'ai dû télécharger des software pour essayer de faire cet
supposé vidéo qui n'en n'est pas une selon toi,
 ALORS comment je dois faire c'est pas facile pour moi , je ne suis pas une
monteuse vidéo mais une gamer.

it's kinda complicated now , I had to download softwares to try making '
not a video' so  how should  I do something not that easy for me , Im not
the tech Im the gamer.

**Comment by Ripley2208** [comment]
voila je le renvoie , il est modifié comme le précédent.
[eco_probleme.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3005462/eco_probleme.zip)

**Comment by redwyre** [comment]
Hi @Ripley2208 , can upi try going into "%LOCALAPPDATA%Low/Strange Loop Games" and renaming the Eco folder (to something like Ecox) and running Eco again and see if it's still happening. If that fixes it for you can you please zip up that folder and email it to simon@strangeloopgames.com (it can contain personal information so better to not post it here)

**Comment by Ripley2208** [comment]
HI,
Nothing works, I move the same way as before.

**Comment by redwyre** [comment]
Hmm.. can you zip up and send that folder to me anyway?

**Comment by Ripley2208** [comment]
le voila complet
 eco_probleme.zip
<https://drive.google.com/file/d/1Ui7NcdU-fdub5CHqnKtA-oT9uX3VVzsR/view?usp=drive_web>

**Comment by redwyre** [comment]
@Ripley2208 it looks like you've renamed the wrong folder... type "%LOCALAPPDATA%Low/Strange Loop Games" into an explorer window (without the quotes) and you should see an Eco folder. If you open it the contents should look like this:
![image](https://user-images.githubusercontent.com/431728/55675958-eac90400-590d-11e9-8b29-93ee34932e58.png)

**Comment by D3nnis3n** [comment]
Closing, fixed.
