### ISSUE TITLE
Doesn’t receive skill points even when leveling up

### ISSUE THREAD

**Issue by Noddebo** [StrangeLoopGames/EcoIssues#11702]
I’ve got an issue where I doesn’t receice any skill points even when I’m leveling up.

**Comment by BlazeGuy2** [comment]
Are you playing singleplayer or multiplayer?

**Comment by Noddebo** [comment]
Multiplayer

**Comment by SlayksWood** [comment]
Are you having this problem lately?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide log file.
