### ISSUE TITLE
Can't skip tutorials

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11705]
See this video: https://drive.google.com/open?id=1HkCXxSJqbIo0PiAOPbA6Fiw-qLpLU1uA

Either that is caused by the massive lag on the official servers, or there is some kind of bug.

After i did the controls tutorial, all other tutorials vanished, e.g. i did not need to skip again, but it skipped them afterwards i did that.

**Comment by Quadbro** [comment]
@D3nnis3n  Worldsave?)

**Comment by Quadbro** [comment]
Probably can be fixed with latest mirasrael changes, can't reproduce it either...
