### ISSUE TITLE
USER ISSUE: Several plants dont show off in plant pots anymore

### ISSUE THREAD

**Issue by BiobrauseTV** [StrangeLoopGames/EcoIssues#11703]
Some plants dont show off in plant pots anymore, although they did a few days ago. I tried to see, if I have the same problems on other servers. On some servers plants like King Fern worked for me totally fine - but not on my own server. The Heliconia seed does not show off anymore on any server for me.

**Comment by Spydarlee** [comment]
Couldn't reproduce this on master (8.2) - is this still an issue that you're seeing @BiobrauseTV? Which version of the game were you running? 

![image](https://user-images.githubusercontent.com/553695/56966786-bedd1f00-6b57-11e9-844f-c42a701321e7.png)

**Comment by D3nnis3n** [comment]
Seems fixed, please reopen if this issue reoccurs.
