### ISSUE TITLE
Various problems

### ISSUE THREAD

**Issue by Roby1164** [StrangeLoopGames/EcoIssues#11708]
Why doesn't the game correctly use the potential of clients? It seems that you use only the hardware part of the server and not combined with that of the client, in particular for the graphic part, my Nvidia 970 is as if it didn't work, this affects performance, causing lag, and with the versions 0.8.0.0 and later , things got worse, today it is almost unplayable, in addition to the various bugs present, strange decisions made, like the last ones, to create a sort of freezing of mineral blocks, after a few seconds, making the use of excavators impossible, but also manual collection suffers, the problem with water and fishing, which I repeat worked very well, up to 0.7.8.9, contrary to what someone says, true SLG-Dennis? ..... etc ..
Now below some screenshots, for the water problem, started a new game with the 0.7.8.9, as seen digging the water fills the holes, even in the sea, placing a block of sand, then removing it, the water, shortly after fill the hole and restore the situation:
http://prntscr.com/myzhq3
http://prntscr.com/myzhur
http://prntscr.com/myzhyu
http://prntscr.com/myzi7l
http://prntscr.com/myzij5
http://prntscr.com/myzifa
While the same save game started with 0.8.0.7, this happens:
http://prntscr.com/myzjcf
http://prntscr.com/myzjen
http://prntscr.com/myzjhn
Even where I had dug before, creating a small lake, now it happens that the hole remains:
http://prntscr.com/myzjqx
As mentioned elsewhere, you need to take a step back, and restore certain settings, bringing the game back to functionality.

If I can, I'll try to make a video .....

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11747
