### ISSUE TITLE
Diminishing FPS

### ISSUE THREAD

**Issue by Burteman** [StrangeLoopGames/EcoIssues#11707]
Hi, I have an issue with my FPS slowly dropping from 60+ and down to 20- after maybe 5-10min. I cannot change this behavior in anyway by changing resolution or graphical settings. At worst it is down to around 12FPS, which is starting to be unplayable. If I restart the game, the FPS will again start out high and drop to low. 
I know this was an issue atleast 1 year ago, but I was hoping it had been fixed by now. My friends that I play with doesn't have the issue as bad as I have, 1 of them do get FPS drops, but nothing nowhere near as bad as I do. The wierd thing is they say that their FPS drops big time every time they get close to my character..

Gforce 1080TI, i7-7740X, M2 SSD disk, so hardware should not be the issue either.
Anyone who has the same issue? The game is fun, but the FPS drop makes it kinda unplayable.

**Comment by redwyre** [comment]
Does this happen after you have been accessing stores? Does rejoining the server fix it?

**Comment by Burteman** [comment]
It does not seem to be related to visiting shops no. If I quit the game and rejoin the server, then the FPS starts out being high(60+), and then it slowly drops down to around 20-. I have tested standing still and looking in 1 direction, and I can see the FPS just getting lower and lower. I have tried adding this to the launch options in Steam,  -screen-quality Fastest. This did have an effect for a couple of hours, gave me around 40 FPS which is playable. But this doesn't seem to do anything anymore.

Benjamin Berglund
Email: Benjamin.berglund@outlook.com<mailto:Benjamin.berglund@outlook.com>
Mobile: +47 90676350

**Comment by redwyre** [comment]
(I edited your comment to remove your personal information)

What are your graphics settings? What happens if you set your view distance to the lowest?

**Comment by Burteman** [comment]
3840*1080
View distance 130
Changing the view distance does almost nothing FPS wise. I have also tried turning all other settings to lowest, windowed mode and so on.
I am unable to change this FPS drop behavior by changing the graphics settings. I have seen many posts around this issue online, I have added links to some of them here.

https://steamcommunity.com/app/382310/discussions/4/1694914735998442719/
https://www.reddit.com/r/EcoGlobalSurvival/comments/5ny4o1/framerate_drop_after_minutes_of_gameplay/
https://github.com/StrangeLoopGames/EcoIssues/issues/7151

**Comment by ClayC90** [comment]
As per your links @Burteman especially the steam one, it seems that this might be a caching issue on the client side @redwyre .

Just gonna throw the idea out there, maybe @redwyre can verify this, when a player opens an inventory, be it chest, vehicle or whatever, will this data be retained and stored anywhere within the ram perhaps?

Could it be that perhaps even the sprites for items are causing this issue?

To be more specific, maybe when we open a UI the items are Instantiated but never destroyed?

I am only trying to give pointers and I could be totally wrong here, but please do take the time to run some debugging on the client to cover the above mentioned possibilities.

Thanks,

**Comment by Burteman** [comment]
I am not really sure how to run debugging on this, any suggestions?

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Clayton <notifications@github.com>
Sendt: Monday, March 18, 2019 5:41:39 PM
Til: StrangeLoopGames/EcoIssues
Kopi: Burteman; Mention
Emne: Re: [StrangeLoopGames/EcoIssues] Diminishing FPS (#11707)


As per your links @Burteman<https://github.com/Burteman> especially the steam one, it seems that this might be a caching issue on the client side @redwyre<https://github.com/redwyre> .

Just gonna throw the idea out there, maybe @redwyre<https://github.com/redwyre> can verify this, when a player opens an inventory, be it chest, vehicle or whatever, will this data be retained and stored anywhere within the ram perhaps?

Could it be that perhaps even the sprites for items are causing this issue?

To be more specific, maybe when we open a UI the items are Instantiated but never destroyed?

I am only trying to give pointers and I could be totally wrong here, but please do take the time to run some debugging on the client to cover the above mentioned possibilities.

Thanks,

**Comment by redwyre** [comment]
We have 0.8.1 is just around the corner, it should improve most (if not all) of those issues.

**Comment by faiith** [comment]
I have the same problems. After restarting the game I have stable 60 FPS for a short time. Even if I do not move, my FPS drops steadily to 8-10. Changes to the graphics settings have no effect. A new log on to the server does not solve the problem, just a complete restart of the game. I myself am a developer (application developer), and in my experience would argue that a memoryleak is one of the possible causes.

I have no ECO mods installed.
Computer Hardware: 16GB Ram, Intel i7 Cpu, Geforce GTX 1070, SSD Storage

**Comment by antimodes221** [comment]
We have the same issue with most clients on our server.  One common elements we have seen is it occurs faster if you are within any of the settlements with large amounts of stock piles.

From the server side resources we do not see an increase in memory or CPU utilization.  Client side sees an increase in utilization.

We are able to slightly reproduce this by spamming 20 stockpiles int he wilderness.  It speeds up the process but not as fast as the settlements.

**Comment by redwyre** [comment]
Should be fixed in 8.1, reopen if you are still having issues
