### ISSUE TITLE
Treasury broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11717]
Treasury is severely broken:
1. Doesn't recognize i'm the leader, though i am when i press L.-
2. Does not show any currencies but only currency name.

**Comment by Quadbro** [comment]
Any details?) world save?)

**Comment by D3nnis3n** [comment]
![bugged](https://user-images.githubusercontent.com/25908592/54756264-282c5280-4be8-11e9-9eb9-0991090ac1de.png)

8.1.0 Staging-1 (Version built yesterday)
