### ISSUE TITLE
Maps on world government webpage not working

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#11715]
Seems to be related to v8.0.8

For example: http://world177.eco.hw.fra1.do-slg.com/?

**Comment by mirasrael** [comment]
Starts working after first entering to the world. Doesn't seems 8.0.8 related.

**Comment by rainfarmer** [comment]
@mirasrael 

It did not use to have this issue with paused worlds.
Be nice to fix, cause it makes new hosted worlds look broken:
![image](https://user-images.githubusercontent.com/7343272/54782217-90c10280-4bdb-11e9-93e6-f76016480c03.png)

**Comment by mirasrael** [comment]
@rainfarmer  I fixed the issue with paused worlds in staging. Did you test on latest staging build?

**Comment by rainfarmer** [comment]
not working on 8.0.8

**Comment by mirasrael** [comment]
It fixed in staging (upcoming 8.1)

**Comment by mirasrael** [comment]
@rainfarmer can you check on 8.1 and close if it fixed

**Comment by rainfarmer** [comment]
working! thanks
