### ISSUE TITLE
Minimap performance issues on massive maps

### ISSUE THREAD

**Issue by jona8690** [StrangeLoopGames/EcoIssues#11711]
Firstly, I'm aware of the recommendations to not exceed 4sqkm, none the less, I did, and it's my understanding many others do too. The linked map is 400x400, making 16sqkm.

I came into casual conversation on the discord with JohnK, where he talked about some "lod" settings, for the minimap, though never got to ask him what he was specifically referring to.

He told me to make an issue, and link to the map, hence I have here, and a Sean would potentially be very helpful :D

All in all however, playing on a large map like this, I've yet to encounter any other specific issues, other than physical hardware, unrelated to the game, but now my server is thankfully back up.

Map (Please note, 300mb download):
https://mega.nz/#!kbQRxYRZ!JK8gUV8TtH7pXGoCUaYkRmkShy6MzuQCRx7Sr33d0XQ

**Comment by SeanAtr0n** [comment]
In the escape menu make sure minimap detail is to the left:
![image](https://user-images.githubusercontent.com/774628/54566619-9e357d00-498e-11e9-9f75-5ec222c814fc.png)

**Comment by jona8690** [comment]
With Minimap details on minimum, I still drop to around 12-13 FPS with it open.
Closed, I get 60.

**Comment by SeanAtr0n** [comment]
That's probably acceptable for such a large world, we will probably optimize it again some day but it's not very high priority
