### ISSUE TITLE
elevators not working

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#11714]
Elevators not responding to up down button presses. Multiple times this has happened. I usually have to exit and reenter game to get them working again.

**Comment by plobre** [comment]
Haven been having this issue as well, and definitely a problem. Simply picking the elevator up and place it back down again solves the issue if that will be faster than exiting and re-entering the game @trevelmike .

**Comment by SereneRebel** [comment]
Can also confirm this issue when re-entering multiplayer server.
When it's broken the external elevator call buttons still change the state of the elevator's buttons but the elevator still won't move.

Issue does not happen on single player games.
Restarting server does not fix issue.
Re-placing the elevator in only fix.

**Comment by SlayksWood** [comment]
Checked on 8.1.1. Wasn't able to reproduce, seems fixed.

**Comment by SlayksWood** [comment]
I tried to restart the server some times, restart the game and I confirm such result. That by pressing the button the elevator doesn't respond.
![image](https://user-images.githubusercontent.com/45708377/55861034-34b82100-5b7e-11e9-9561-84ce3489162f.png)
The elevator has no obstacles below
![image](https://user-images.githubusercontent.com/45708377/55861215-95475e00-5b7e-11e9-902c-1ce1aeeff495.png)
I can't say for sure why this happens.

**Comment by SlayksWood** [comment]
I add that the second elevator works well.

**Comment by SlayksWood** [comment]
After I left the elevator, so that he was out of sight. After some time I came back and found that 
It disappeared. And the rope leads to the side. 
![image](https://user-images.githubusercontent.com/45708377/55862291-d6407200-5b80-11e9-9de9-02f585415f44.png)
![image](https://user-images.githubusercontent.com/45708377/55862442-24ee0c00-5b81-11e9-9b30-bbafcee4e548.png)
The end of the rope can't be reached.

**Comment by SlayksWood** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3062808/output_log.txt)

**Comment by SlayksWood** [comment]
1. Start a new server.
2. Making an elevator
3. Run away from it. So that it doesn't load.
4. Reload.
5. Come back to the elevator.
6. Elevator doesn't respond to button presses
https://drive.google.com/file/d/1MfXR-6WPqkCKlgTGqGemlI3-sq55LmSO/view?usp=sharing

**Comment by faiith** [comment]
> 
> 
>     1. Start a new server.
> 
>     2. Making an elevator
> 
>     3. Run away from it. So that it doesn't load.
> 
>     4. Reload.
> 
>     5. Come back to the elevator.
> 
>     6. Elevator doesn't respond to button presses
>        https://drive.google.com/file/d/1MfXR-6WPqkCKlgTGqGemlI3-sq55LmSO/view?usp=sharing

I can confirm this issue oin our server, exactly the same behavior as @SlayksWood mentioned

Client-Log: [output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3080101/output_log.txt)
Server-Save: https://drive.google.com/file/d/1mjd2wX960cDhIXnB_aGGZ8EHz8wgLGuS/view?usp=sharing
