### ISSUE TITLE
USER ISSUE: Auflösung

### ISSUE THREAD

**Issue by Cypata** [StrangeLoopGames/EcoIssues#11718]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Keine Änderung die Auflösung zu ändern. 

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by D3nnis3n** [comment]
Mehr Details?

**Comment by D3nnis3n** [comment]
Closed due to no response.
