### ISSUE TITLE
[8.1.0 Staging-1] Gain Specialty XP Tutorial - Mousing over the Research Table link doesn't tick the objective

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11723]
Tooltip shows, but objective is not ticked.

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/55019912-04d02180-4fb3-11e9-8d7d-ce97000899de.png)
Worked for the current staging build-4
