### ISSUE TITLE
Trash piles do not convert to garbage blocks without server restart

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [StrangeLoopGames/EcoIssues#11728]
Version: 0.8.0.7

Step to Reproduce:

1) Drop any inorganic item on the floor. Trash pile is created.

2) Sleep in a bed to pass time. I tested 12, 24 and 48 game hours.

3) Trash pile will still be on floor. You can open it and the contents will be replaced with a trash icon but you can take item out and it will return to its original item. The pile/bags never convert to garbage block.  I even left the area and allowed the chunk to reload - same result.

4) Restart server - Instant garbage block created.

No mods installed.

**Comment by Quadbro** [comment]
Found problem GarbageManager.Obj.Tick(); returns too large walue between ticks.... and if there is fresh start (no garbage) it returns enourmous time between garbage ticks...

**Comment by mirasrael** [comment]
Seems nextTickTime evaluation should be moved out of `if`
