### ISSUE TITLE
[8.1.0 Staging-2] Changing claim color does not apply until restart

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11735]
On the world, the color of the claim no longer changes to the color chosen without a restart.
Look at the clain name color and the claim color.
![claim](https://user-images.githubusercontent.com/25908592/54833763-0225b180-4cbf-11e9-9664-71d72f35bfd8.png)

**Comment by SeanAtr0n** [comment]
subscriptions aren't working as expected here... most likely related to recent view changes

**Comment by mirasrael** [comment]
Should be fixed in staging-7
