### ISSUE TITLE
USER ISSUE: floating grass and floating tree's spawning

### ISSUE THREAD

**Issue by purpleypete** [StrangeLoopGames/EcoIssues#11738]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
use command /level **,**

**Expected behavior:**
clear the entire area expanding vert removing it all

**Actual behavior:**
when leveling a area, most of the time it leaves floating grass or weeds, sometimes after awhile floating baby tree's spawn in.

**Do you have mods installed? Does issue happen when no mods are installed?:**
when leveling a area, most of the time it leaves floating grass or weeds, sometimes after awhile floating baby tree's spawn in.

**Comment by purpleypete** [comment]
this happens with and without mods, single player and server

**Comment by redwyre** [comment]
Fixed in 0.8.1
