### ISSUE TITLE
[8.1.0 Staging-2] /listunobtainableitems broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11734]
Does not do anything, gives no text back.

**Comment by BlazeGuy2** [comment]
![image](https://user-images.githubusercontent.com/35509188/55019302-e158a700-4fb1-11e9-838c-dd1a319cfd62.png)
It's on current staging

**Comment by D3nnis3n** [comment]
Reopened, doesn't work for me on Staging-6. No output.

**Comment by D3nnis3n** [comment]
![listunobtainable](https://user-images.githubusercontent.com/25908592/55236017-3d7c2f00-522f-11e9-9601-69e271d038c9.png)

**Comment by D3nnis3n** [comment]
Try with german language, but also didnt work on english.
