### ISSUE TITLE
[8.1.0 Staging-2] Can't create new world with custom map

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11731]
If i want a custom map, the map is created and it loads fine, until the moment where i should be brought into the game. At that moment, the dialogs on the screen just disappear and i'm back to the main menu without any error message, just as if the server shuts down after generation. It's also not possible to try to connect to this world, as it tells me it's loading and then without error closes all dialogs and gets me back to the main menu.

Server Log:
[log_190322034357.log](https://github.com/StrangeLoopGames/EcoIssues/files/2997032/log_190322034357.log)

**Comment by Quadbro** [comment]
Sorry, tested all the configurations, even yours on editor and staging build... cant reproduce in any way((( probably need someone else help(

**Comment by D3nnis3n** [comment]
No longer happening in Staging-4 from yesterday.
