### ISSUE TITLE
Alpha Staging 6da56326 game balance hack Waterfall and Water bug ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1173]
![20170318024141_1](https://cloud.githubusercontent.com/assets/15990789/24070108/900446fc-0b84-11e7-9854-045504fa2e99.jpg)

well can hang out in water work underwater build underwater, but also can magic climb side of waterfalls under water like there conveyor belt - being able to almost teleport up side of a mountain is awesome combined with ability to build and work along with  living underwater.  it  makes life easier.

**Comment by MarjieAVolk** [comment]
This is working as intended.  We will likely add more underwater features and content later in development.
