### ISSUE TITLE
USER ISSUE: Verbindung fehlgeschlagen

### ISSUE THREAD

**Issue by KuschelPuschel** [StrangeLoopGames/EcoIssues#11746]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Beim erstellen/einloggen in einer Welt tritt der Fehler immer auf

**Expected behavior:**
Einloggen in die Welt	

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
Verbindung Fehlgeschlagen ( invalid login info)
<size=150%>Verbindung fehlgeschlagen</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**Nein
Die folgende Fehlermeldung trat auf:
Verbindung Fehlgeschlagen ( invalid login info)
<size=150%>Verbindung fehlgeschlagen</size>

Invalid login info.
```

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11548
