### ISSUE TITLE
Alpha Staging 6da56326 Game Balance Issue bug - crafting table and item stacking - room sizes dont matter.

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1174]
you can stack items on top of each other and even push items into each other when placing them making it so you dont need build room sizes dont matter.

![20170318120144_1](https://cloud.githubusercontent.com/assets/15990789/24074335/92400f1e-0bd4-11e7-9d27-5882ca5bcaf9.jpg)
![20170318120152_1](https://cloud.githubusercontent.com/assets/15990789/24074336/92416b84-0bd4-11e7-847d-4763908ef444.jpg)

**Comment by midn8t** [comment]
![20170319114619_1](https://cloud.githubusercontent.com/assets/15990789/24082832/c5fcae0a-0c99-11e7-88a3-8bbe1b7024b5.jpg)
![20170319114643_1](https://cloud.githubusercontent.com/assets/15990789/24082833/cacee038-0c99-11e7-98e0-ffa242cc854a.jpg)

**Comment by craig-jong** [comment]
the has to do with incorrect volume sizes which is mostly fixed.

Stacking tables isn't really a bug, although placing chairs inside of other objects is. They don't have collision and don't seem to respect their occupancy - not really a room related bug. I'm just going to close this and open one up specifically for chairs.
