### ISSUE TITLE
USER ISSUE: Cannot Change World Default Currency

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11743]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Open the Treasury window.
2. Attempt to click on the field next to where it says "World default currency:"

**Expected behavior:**
I should have the ability to set the field to a different currency.

**Actual behavior:**
The field does nothing as if it was a fixed setting.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The field does nothing as if it was a fixed setting.

**Comment by Quadbro** [comment]
you need to be a leader

**Comment by Blanclour** [comment]
I am indeed the world leader.
