### ISSUE TITLE
USER ISSUE: Water behavior

### ISSUE THREAD

**Issue by joelunder** [StrangeLoopGames/EcoIssues#11747]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Dig on the beach	

**Expected behavior:**
Water either doesn't flow at all or flows to fill in dug holes	

**Actual behavior:**
Water leaves odd holes in the beach and creates mini waterfalls that fall into nothing.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Yes, and yes.

![image](https://user-images.githubusercontent.com/5238345/54886476-a85bed80-4e5e-11e9-8c18-dcc388233ccd.png)

**Comment by redwyre** [comment]
Fixed in 0.8.1
