### ISSUE TITLE
USER ISSUE: Dual Monitor unplayable issue

### ISSUE THREAD

**Issue by Paxton1997** [StrangeLoopGames/EcoIssues#11744]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Have more than 1 monitor and playing the game, and look to either direction.

**Expected behavior:**
It should have locked the cursor to the game so it cant go onto the other monitors.

**Actual behavior:**
The mouse cursor doesnt lock to the primary monitor, so if i look too far to the right or left and click it tabs me out of the game and my cursor goes onto that monitor.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods, i just installed the game 10 minutes ago

**Comment by faiith** [comment]
I have a Tipple-Monitor-Setuo, and nhave one of your described issues. Your resolution is set to fullscreen (not windowed)?

**Comment by Paxton1997** [comment]
I have triple monitor aswell and my resolution is set to fullscreen, but it happens in both fullscreen and windowed mode, so far i was able to fix it with a program called "Dual Monitor Tools" and you can set a hotkey to lock your cursor to one monitor, thats what i did for the time being.

**Comment by SlayksWood** [comment]
0.8.1.3
Borderless fullscreen  works well
Windowed works as Borderless fullscreen identical
Exclusive fullscreen - The mouse cursor doesn't lock to the primary monitor
