### ISSUE TITLE
 Numbers instead of descriptions in the Law interface

### ISSUE THREAD

**Issue by Lars225** [StrangeLoopGames/EcoIssues#11740]
Hey guys. I have the Problem that in the Law Interface it shows only numbers not descriptions. The Server is massive lagging too.
![ecobuglaw](https://user-images.githubusercontent.com/41234245/54864885-abbb8000-4d5d-11e9-9505-6bb9a6725238.JPG)

**Comment by Lars225** [comment]
Version: 8.0.7

**Comment by mirasrael** [comment]
@Lars225 Can you attach the server save? It seems to be not reproduced on regular version.

**Comment by mirasrael** [comment]
Also which locale uses server?

**Comment by mirasrael** [comment]
nwm, found it related to locale

**Comment by Deantwo** [comment]
@Lars225, by the way that Law in your picture won't do anything. It is not possible to abandon specialities anymore, and a law that only say "Allow" will never do anything because by default everything is allowed.

**Comment by Lars225** [comment]
Deantwo you readed my post ?! I Think not. Not the Law is the Problem but i fixed mit already its a Bug in the Translation

**Comment by Deantwo** [comment]
@Lars225, I didn't say anything about the reported bug. The bug is supposedly fixed already in the dev build.

I was just saying that the law shown in the picture is useless and won't actually do anything.

**Comment by Lars225** [comment]
the law was a sample because i cleared all before to show if it work with new laws. Sorry for my comment it was not the right way
