### ISSUE TITLE
USER ISSUE: Currency Transfer Error

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11756]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1. Create a bank account and put all currency from a second newly minted currency in it.
2. Attempt to transfer some of the currency into the treasury. Using the transfer button in the Y menu.
* I am the world leader.
* I own the mint and all the bank accounts involved.
* A different currency was set as the world default currency.

**Expected behavior:**
It should have transferred the currency into the Treasury.

**Actual behavior:**
Instead, after the transfer is supposedly complete and I press the ok button, I find that no actual movement of currency happened at all. I have tried the transfer repeatedly to no avail. I tried to transfer it into my own personal account instead of the treasury, it still will not work. In the economy viewer it says that there is 0 of the currency in circulation even though the bank account im pulling from has 200,000 units of currency and is set to be owned only by the world leader position.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead, after the transfer is supposedly complete and I press the ok button, I find that no actual movement of currency happened at all. I have tried the transfer repeatedly to no avail. I tried to transfer it into my own personal account instead of the treasury, it still will not work. In the economy viewer it says that there is 0 of the currency in circulation even though the bank account im pulling from has 200,000 units of currency and is set to be owned only by the world leader position.

**Comment by D3nnis3n** [comment]
Is there any dort of direct transfer tax? If des, set them to 0% and try again. If it works then, its a duplicate.

**Comment by Blanclour** [comment]
It is indeed related to the direct transfer tax, I set it to 0 and now it's allowing me to do transfers. Thanks :)
