### ISSUE TITLE
Performance issues only when game is in focus (with workaround)

### ISSUE THREAD

**Issue by alexanderbock** [StrangeLoopGames/EcoIssues#11755]
There has been a regression in either 0.8.0.6 or 0.8.0.7 to this as it did not happen in 0.8.0.4.

When the game is in focus, the framerate drops considerably (to about 20 fps or so);  if the game is not in focus, it is at >=144fps regardless of graphics setting.  This even happens if only the menu is loaded.  Issue happens regardless of whether G-Sync is enabled or not

https://youtu.be/ivHiSGvqhQM
(see RTSS stats in top left)

System:
Intel Core i9-9900K overclocked  (not thermal throttled, already checked)
GeForce 2080
32 GiB RAM

Workaround:  I found a workaround by switching to single display mode (Windows + P) and then switching back to the dual monitor setup.

**Comment by SlayksWood** [comment]
Checked on 8.2.4. Wasn't able to reproduce, seems fixed.
If it happens again, please reopen
