### ISSUE TITLE
Harvest contract doesn't require to put items into a storage

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11757]
Contract tells me to harvest a palm and deposit it in stockpile X.
I harvest the palm, contract does not update in any way telling me to pick it up and bring it to the stockpile, instead i can just finish the contract and get my reward - all i did was to cut the tree and let it lie around.

(I actually never really noticed before, that the contracts are actually supposed to make you deliver the harvested goods somewhere, i'm ashamed)

**Comment by beastyn** [comment]
I just tested this one on 0.8.1.0-release-review and wasn`t able to close contract without deliver. I will close it for now.

**Comment by D3nnis3n** [comment]
Reproduced on release_preview, reopening.

@BlazeGuy2 Could it be the case this is caused by the spawned contract that wants me to harvest a stump which gives no resource back?

**Comment by beastyn** [comment]
Seems to be broken. Again
You can harvest and finish a contract without putting anything to a storage.

**Comment by beastyn** [comment]
Still don't have a marker after picking a contract.
It should be visible right after picking a contract.
