### ISSUE TITLE
Alpha Staging 6da56326 Spawning bug for animals

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1175]
![20170318124902_1](https://cloud.githubusercontent.com/assets/15990789/24078483/ce328728-0c3c-11e7-93e9-faf7ae4dd4e3.jpg)

the animals seem all spawn and congrats in one spot in locations on map, you can shoot them form distance they run and come back shoot them agin if you go near them they will run off but will come back also.
so best way to hunt is just find location like this and lob arrows up into air and down on them.

this was issue in version 4.5 also, but spawning location was on top of my house and they just appear on top and hang out in that version.

**Comment by craig-jong** [comment]
Steven since you did the wander, I thought you might know why they seem to group up on top of things...

**Comment by midn8t** [comment]
I have no idea i just notice that they - tend to stick on top of houses, on top of points like that they seem not really move around, also there seems to be borders that get stuck on invisible walls at times.

what is interesting in this picture if i went up to them they run off and then come back and stand there agin.

i figured it was spawn points.

currnetly in 5.5.1 animals seem to be appearing on top of houses sometimes and just getting stuck.

**Comment by SeanAtr0n** [comment]
Should be fixed in 5.6
