### ISSUE TITLE
House value not showing in tooltip

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11751]
Version: 0.8.7
Mods: No

House value is not showing in tooltip (tooltip pops up, but is empty). Bug occurs after building multiple houses on different properties.

![382310_20190325115815_1](https://user-images.githubusercontent.com/40213281/54914663-c0328080-4ef5-11e9-938a-b607ddb10e3c.png)

**Comment by faiith** [comment]
Forgot to mention, i'm playing with german localisation, don't know if this is cause of the issue

**Comment by Quadbro** [comment]
Failed to reproduce this issue by building different houses on different properties and by doing that on non-english locale too, can you provide a world-save?) (on some hosting like google drive, or any you want)

**Comment by faiith** [comment]
Requested World-Save: https://drive.google.com/file/d/1eINCuk4TX8LYVN8MKxxm_WfSWiL0li5A/view?usp=sharing

Meanwhile we have several players on the server having this issue

**Comment by Quadbro** [comment]
@faiith Thanks

**Comment by faiith** [comment]
In the meantime, we had started a new world to exclude various bugs. At first the tooltip worked perfectly, but not anymore. I currently only have 1 building with the declared room generating points, but the problem still occurs. Even with my teammate, the problem occurs, even though she has only 1 house. Maybe several rooms marked as "common" cause the problem (above link of worldsave is from new world)

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/55551838-e9c58600-5705-11e9-9717-dabfbba0576d.png)
owned all deeds on that save.... nothing that's interesting

**Comment by faiith** [comment]
That's weird...

Fresh screen:
![Faiith_Shiana](https://user-images.githubusercontent.com/40213281/55553806-7f025380-56e1-11e9-9be6-57c34f0f6568.jpg)

Client-Log (output_log.txt):

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3043302/output_log.txt)

Fresh server-save: https://drive.google.com/file/d/1PIWApDV2LZ0PKmZe0-F9dZu7tN12vuGL/view?usp=sharing

I can't give your more info/logs/saves. In any case, it is unfavorable that we are no longer able to see how the scores for the rooms are made up

**Comment by mirasrael** [comment]
@faiith Did you try on staging 8.1?

**Comment by faiith** [comment]
i did, issue occured also on different worlds (we startet all over 3 times in last 3 weeks, and issue always occured after reaching some progress in housebuilding. In the beginning on every world (and eco-version) everything worked fine

**Comment by mirasrael** [comment]
Hmm, probably one of items causing this problem? If you start house from scratch on the same world - will you have this issue?

**Comment by mirasrael** [comment]
https://github.com/StrangeLoopGames/Eco/pull/4210 highlight fix

**Comment by Quadbro** [comment]
UPD: Was able to reproduce it... the issue comes from TextMeshPro...

**Comment by Quadbro** [comment]
@faiith Thanks for fast responces and providing additional info! 👍

**Comment by Rakkeyal** [comment]
I am having this issue today after the newest update. I am in default english and have tried restarting both the client and the server.

![image](https://user-images.githubusercontent.com/49470647/55855437-e10ffc80-5baa-11e9-908d-eac8fd082629.png)

**Comment by beastyn** [comment]
Reopening, @Quadbro 
I wasn`t able reproduce it
@Rakkeyal can you provide save?

**Comment by Rakkeyal** [comment]
Yes, here is our server backup. Let me know what else you may need.
I will say that it worked fine for about 5 or 6 rooms, then it got mad when I used a ladder as a block saying the rooms were connected (doorway unrecognised) and when I replaced the ladder, it went blank and hasn't returned,

https://drive.google.com/open?id=1cLUHrqefrMfqNZLjXvRcP_7aa03LmWHq

**Comment by beastyn** [comment]
@Rakkeyal Thank you for provided information, this should be helpful

**Comment by Rakkeyal** [comment]
update: I replaced the whole building with a different material and replaced the areas with ladders with other blocks (walls, doors, etc) and my house info has returned. So I have to believe its linked to using ladders as blocks in rooms where the ladder is being considered against the "open" space rule for doors and windows.
I have this problem with Shop fronts sometimes using ladders for 2 wide windows as well.

**Comment by faiith** [comment]
> ...So I have to believe its linked to using ladders as blocks in rooms ...

Hm, i don't have ladders in rooms, but still have no house-info in tooltip
Latest server-backup: https://drive.google.com/file/d/1nx0eDsHBI7z59gqxmdG_gkq3s9dZcOj1/view?usp=sharing

**Comment by Rakkeyal** [comment]
have you tried remove the whole room, floor and roof, and replacing it? When I did that for the offending room it came back.

**Comment by faiith** [comment]
Seem's to be fixed (in my case at least) in 0.8.1.2
