### ISSUE TITLE
[QoL] Make the /level command usable for flattening

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11758]
Current behaviour:
/level replaces everything in the given radius with the specified item.

Better behaviour:
/level only removes all blocks up to the given coordinate, NOT changing the blocks below AND
/level only adds the specified blocks in empty air blocks up to the given height NOT changing the existing blocks to the specified blocks:

Use:
Easy flattening of areas for cool buildings projects that make you NOT loose the resources in the ground.

Could possibly add a second command for that, so people can use both.

**Comment by redwyre** [comment]
/Level starts from the top adds blocks down until it hits the first solid block and stops. It doesn't replace anything in the ground already.

**Comment by D3nnis3n** [comment]
Weird, last time i tested that it did not work like this.
