### ISSUE TITLE
Alpha Staging 6da56326 Game play balance campfires vs Storage chest

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1176]
on the 5.5 server we have people are no longer using storage chest but campfires putting them all over place because they hold more then the storage chest. so the campfire is just being spammed every where and storage chest are not being used.

**Comment by SeanAtr0n** [comment]
Food is pretty light... reduce the weight limit for campfires?

**Comment by craig-jong** [comment]
lowered weight on campfires; stockpiles are a more permanent fix for this.
