### ISSUE TITLE
Vehicle problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11768]
- Can't get out of vehicles
- Putting carried gas into excavator didnt put it in the fuel slot

**Comment by redwyre** [comment]
I can get out of my excavator that has fuel, when is unfueled

**Comment by D3nnis3n** [comment]
Partly duplicate of #11733

**Comment by D3nnis3n** [comment]
Actually the other part is duplicate of #11769
