### ISSUE TITLE
USER ISSUE: skid steer bug

### ISSUE THREAD

**Issue by mole3421** [StrangeLoopGames/EcoIssues#11761]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
skidsteer stops picking up rubble when not full. This has been happening snice update 8.0.6

**Expected behavior:**
should be picking up rubble

**Actual behavior:**
not picking any rubble up

**Do you have mods installed? Does issue happen when no mods are installed?:* 
no mods installed

**Comment by D3nnis3n** [comment]
Duplicate of #11654
