### ISSUE TITLE
USER ISSUE: Game running 8.0.5 but server need 8.0.7 WSU Honors 390 CLass

### ISSUE THREAD

**Issue by AlisonB319** [StrangeLoopGames/EcoIssues#11760]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Download the most reason version of eco sent to our teacher and the world server will not be corrrect. We recieved the link 

https://accounts.strangeloopgames.com/worlds

To update our world server but it just redirects to 

https://accounts.strangeloopgames.com/home

**Expected behavior:**
You can log in and play Eco

**Actual behavior:**
The following error message popped up:
``` 
<size=150%>Connection Failed</size>

Incompatible version.  User is 0.8.0.7 beta but server is 0.8.0.5 beta.

<size=60.00%></size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
``` 
<size=150%>Connection Failed</size>

Incompatible version.  User is 0.8.0.7 beta but server is 0.8.0.5 beta.

<size=60.00%></size>
```

**Comment by rainfarmer** [comment]
I think the server was updated.

If not, you can download 8.0.5 for windows here:
https://s3-us-west-2.amazonaws.com/eco-releases/EcoPC_v0.8.0.5-beta.zip
