### ISSUE TITLE
Can't exit skidsteer with e

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11769]
Only leave machine on disconnect

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/55104068-e63b5a80-5086-11e9-8b1b-79698cdd81cc.png)
Had same problem.
Also wasnt able to move the arms this time

**Comment by SeanAtr0n** [comment]
log files
