### ISSUE TITLE
Lighting Issues

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11763]
While making videos i occured weird lightning issues increasingly:

1. Very often, textures flicker weirdly in light. I found no way to stop that, none of the graphics settings have any influence on this.
2. More rarely but still happening, lighting updates very slow. I look at a building which is lightened by the sun, move a bit and suddenly the building gets very dark.

**Comment by SeanAtr0n** [comment]
Probably need some examples of the flickering

**Comment by D3nnis3n** [comment]
https://youtu.be/o1nTR4FygkE

0:22 Clip. Note the roofs of the building.

**Comment by SeanAtr0n** [comment]
1 is possibly fixed in 8.2, GI is now curved to correctly fit the world

2 reassigning for part 2, related to the SEGI update rate throttle @metachronism  added

**Comment by metachronism** [comment]
as @SeanAtr0n says, some of this is better with his curve fix, but we aren't really going to update the rate of GI updating, as its egregiously slow.  So closing this out
