### ISSUE TITLE
Vehicle controls need tuning

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11772]
Change excavator and skidsteer to be like the crane:
Excavator:
- Mouse wheel changes bucket angle
- Mouse movement freelooks
- WASD rotates arm 

Skidsteer
- Mouse wheel changes arm angle
- Mouse movement freelooks
- WASD moves vehicle

The controls UI is also confusing:
![image](https://user-images.githubusercontent.com/3536496/55103455-afb11000-5085-11e9-878f-659eba70471d.png)

Change this to instead have two options on excavator, Dig and Drive, and you have a radio button to choose between the two. Dont use the standard icons, make a new interface for this.

**Comment by johnkslg** [comment]
Boosting priority on this because its low hanging fruit

**Comment by SeanAtr0n** [comment]
don't think this would be an improvement.

**Comment by SeanAtr0n** [comment]
maybe we should ask the community if they would like other vehicles to control as great as the crane

**Comment by johnkslg** [comment]
@mike can you take a look at improving controls on vehicles for 8.2?

**Comment by Quadbro** [comment]
@johnkslg sure)

**Comment by beastyn** [comment]
[0.8.2]
When rotating arm with AD wheels are rotating too. And seems like if exca is in the position where wheels are blocked an arm will be blocked too.
https://drive.google.com/file/d/15aHRS1xGOLWmeztBDQEcRAOBb1oWh436/view?usp=sharing

**Comment by beastyn** [comment]
+ Now there is a sound of engine even without a fuel
+ How can I refuel now? If I have fuel in the exca storage and driving can I put fuel somehow without dismounting?

**Comment by mirasrael** [comment]
I'll take care of it

**Comment by Sekor2600** [comment]
In the Skid has confused Controls.
The R/F is Arm Up/down and ScrollWheel rotates the Shovel
But the Controls ingame are different
![grafik](https://user-images.githubusercontent.com/37456949/57480304-9ebc0700-729f-11e9-8af5-db58f94df144.png)

**Comment by Sekor2600** [comment]
The Skid interface is displaced
![grafik](https://user-images.githubusercontent.com/37456949/57558937-0b0e3780-7380-11e9-8ebd-bdda67d4c4d9.png)
And Scrollwheel is misspelled in Skid and Excavator
