### ISSUE TITLE
Alpha Staging 6da56326 Tooltips Huckleberry seeds Hightlighting over them Crashes

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1177]
so every thing was working fine then after 4 days or so into server game, one client started reporting crash when ever they highlight over Huckleseeds all of sudden

had give them admin rights so they could use /dump
and now anther client is reporting it, and then i got issue my self also.

**Comment by midn8t** [comment]
![20170319230736_1](https://cloud.githubusercontent.com/assets/15990789/24088505/1e7b702a-0cf9-11e7-99e8-cf2884f48390.jpg)

**Comment by metachronism** [comment]
fixed
