### ISSUE TITLE
Tent hitbox is blank in large areas of back wall

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11771]
![image](https://user-images.githubusercontent.com/12839021/55103153-2e597d80-5085-11e9-87a1-812356003807.png)

Notice dot disappear in next screenshot.

Cant open tent when looking at this section...
![image](https://user-images.githubusercontent.com/12839021/55103148-2994c980-5085-11e9-9ae6-9ebcd6f9ee82.png)

... to this section
![image](https://user-images.githubusercontent.com/12839021/55103198-403b2080-5085-11e9-9235-87ff8ab4d0c4.png)

**Comment by Quadbro** [comment]
too far away probably...
