### ISSUE TITLE
Placed my campsite on someone else's property & markers are wrong

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11774]
I'm authorized on Waves's property but my campsite is marked as his... probably shouldn't allow campsite placement on other people's property even if you are authorized
![image](https://user-images.githubusercontent.com/774628/55103655-1f26ff80-5086-11e9-96e6-89cacb8a6a69.png)

**Comment by D3nnis3n** [comment]
When you put something on other peoples ground its treaten as theres, so probably working as intended. Placement restriction would hinder playing together.

**Comment by SeanAtr0n** [comment]
Campsite is a special case, it would be a pretty awful first experience playing if you accidentally did this and then got un-authorized

**Comment by D3nnis3n** [comment]
It would also be awful if players that play their fifth round could no longer start out on property of someone else. Please find a way not involving me to need to search land a kilometre away first before  i can pick it up again and go back ...

**Comment by D3nnis3n** [comment]
Were actually doing this each cycle, working on property of someone else.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/55167867-cd17d400-5182-11e9-9d5b-9a0484b97be5.png)

**Comment by mirasrael** [comment]
I think we can have a compromise.
