### ISSUE TITLE
Joshua tree branches lod out early leaving floating leaves

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11775]
![image](https://user-images.githubusercontent.com/3536496/55103765-57c6d900-5086-11e9-96e7-4b5bfdee49ed.png)

**Comment by keegan-o** [comment]
This is a hard coded LOD setting for all tree branches, we need some kind of code solution to expose this for tweaking ideally per tree instead of as a universal setting for all tree branches as it currently is, or the tree will have to be re-structured if that is not possible.

**Comment by SeanAtr0n** [comment]
fixed in svn
