### ISSUE TITLE
Joshua tree leaves pop off instantly 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11778]
When you chop it down. They should pop off on impact or later or not at all. 
![image](https://user-images.githubusercontent.com/3536496/55104260-4af6b500-5087-11e9-88a2-39ee846920c2.png)

**Comment by keegan-o** [comment]
Can't really repro on staging or master... 
![image](https://user-images.githubusercontent.com/14983165/55193258-af874200-5163-11e9-9abd-0ec5e9d1bfb9.png)

**Comment by johnkslg** [comment]
Was happening with '/give axe', maybe its unique to that

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/55200487-8d012300-517b-11e9-8142-aefc4a6a8ef9.png)
Do you mean the branch with all the clumps detaches right when it's cut? Doesn't seem to differ for me whichever implement I use to cut it down.

**Comment by johnkslg** [comment]
I saw as soon as it started to fall, all the leaves disappeared. Looks like its not happening to you anymore for whatever reason, so I'll close. Thanks!
