### ISSUE TITLE
Law to allocate funds on pass, didn't

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11785]
http://74.85.92.174:3001/laws.html?lawid=2a340978-b8ae-43f9-bedb-a4ced563faca

I passed it with /passlaws

![image](https://user-images.githubusercontent.com/431728/55107500-3a911980-511d-11e9-8ff8-446935c6ed66.png)

**Comment by D3nnis3n** [comment]
Did treasury have that much bucks?

**Comment by D3nnis3n** [comment]
Cannot reproduce.

**Comment by redwyre** [comment]
I made a similar law previously, which must have accidentally been a tax, which output a whole bunch of logs that people didn't have enough money to pay.

This time, nothing.
