### ISSUE TITLE
Store filter lists "Tier 10" and "Tier 6"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11787]
Also not in the tiers section
![image](https://user-images.githubusercontent.com/431728/55108302-0fa7c500-511f-11e9-92c1-bdd2fa907db2.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/55158649-6e495f00-5170-11e9-9959-02a0e55daa3f.png)

**Comment by redwyre** [comment]
Your image has Tier 10 though? Or are you just saying that's a different issue?

**Comment by mirasrael** [comment]
@redwyre yes, you're right. Missed it because of ordering.
