### ISSUE TITLE
Error creating new law

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11784]
![image](https://user-images.githubusercontent.com/431728/55107298-b8a0f080-511c-11e9-96f8-4984e0c03bce.png)

**Comment by redwyre** [comment]
After refreshing the page I could fill in the name and reasoning again and create it

**Comment by D3nnis3n** [comment]
Also sometimes get this in complex laws WHILE editing, but can save just fine.

**Comment by mirasrael** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11742
Fixed in master. @redwyre during creation of the law did you switch to districts view?

**Comment by redwyre** [comment]
@mirasrael I believe the default action is to add a district, so it started on that

**Comment by mirasrael** [comment]
@johnkslg @seccombew Should we back port fix from master to the staging?

**Comment by mirasrael** [comment]
Fix backported from master.
