### ISSUE TITLE
[0.8.1.0-Staging 6] Escape while in a UI no longer closes the UI but opens the main menu.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11798]
Quite sure this behaviour was different earlier. In any way, that's not what it should do.

**Comment by mirasrael** [comment]
Which UI exactly do you mean? Tested with Wood Cart UI and with Economy Viewer UI - both working as expected - ESC closes UI.

**Comment by D3nnis3n** [comment]
It happens with most UIs for me. Map doesn't work, but did before. Also some of the objects it didnt work. 
Inventory doesn't work - but that one did never work for me, so maybe expected.

**Comment by D3nnis3n** [comment]
Do i need to search for each specific object? Won't manage that today, can do that monday. I used the command to spawn all world objects and most of them did not correctly close ui, but opened menu.

**Comment by D3nnis3n** [comment]
So i assumed it's broken in general.

**Comment by mirasrael** [comment]
Did you test with UI I mentioned above?

**Comment by mirasrael** [comment]
Map doesn't work, because it stays after going into movement mode. So I don't know if it should stay or not actually.

**Comment by SeanAtr0n** [comment]
please attach your log file if you see it not work on a worldobject UI

**Comment by D3nnis3n** [comment]
I've just gone through the world objects again in staging-7 and the issue didnt reoccur. The starter tent showed this behaviour (i actually pressed e on the new bed inside), but only on the first time opening. On the second time it closed the menu as expected. I attached my log (do no longer have the old one), but if there is nothing to see in there, feel free to close the issue. (I'd still like to actually close my map via ESC, though)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3028541/output_log.txt)

**Comment by SeanAtr0n** [comment]
sounds like it's working as expected, escape doesn't close the map because some people like to keep it open while walking around
