### ISSUE TITLE
Greatly improved Server-Performance, but strange new FPS drops

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11791]
Version: Stagion 0.8.1.0 e7012ee4
Mods: None

Server performance has been improved significantly in staging 0.8.1, we no longer have lags. Great work Guys!!!  But FPS burglaries have been added that are easy to reproduce and are common to all players on our server (regardless of client hardware).

The following causes massive FPS drops(down to 1 FPS):

Drive off with a cart
Pass another player, or another player passes by.

**Comment by mirasrael** [comment]
Hi @faiith I'm not sure I understand repro-case. Can you explain in more details, probably upload video to the Youtube?

**Comment by mirasrael** [comment]
Tried to reproduce issue with no success. Any additional info will be very helpful. Please attach client log and video also will be useful.

**Comment by faiith** [comment]
With Staging 8.1 - 6 not able to reproduce, neither on new world nor the backuped old one. As soon as i'm able to reproduce again i'll tell ya. Maybe allready fixed somehow

**Comment by mirasrael** [comment]
Thanks! Closing for now. Feel free to re-open issue if you will be able to reproduce this.

**Comment by faiith** [comment]
Okay, we can reproduce it now. In most cases the FPS-Drops occur if somebody near your position is using a cart, or if you're self using a cart. FPS drops down till 1 FPS. All clients on our server have this issue. Not occuring everytime u use a cart, but quiet often. Multiple players using a cart has of course massive impact.

Link to video where you can see the FPS drops: https://www.youtube.com/watch?v=z36nwMXosvw&feature=youtu.be

Server-Save:
[Game.eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3026536/Game.eco.zip)

Client log:
[Eco.gc.log](https://github.com/StrangeLoopGames/EcoIssues/files/3026533/Eco.gc.log)

**Comment by mirasrael** [comment]
@beastyn can you try to reproduce this issue together with @SlayksWood ?

**Comment by faiith** [comment]
Meanwhile i think the FPS-Drops are just a sideeffect of the issue, i believe it's more network related or something like that. Using the carts (in most case near other players, sometimes if you're alone in the area too) seems to produce lagspikes on the server (that's why most clients online are affected somehow)

**Comment by mirasrael** [comment]
@faiith Do you have big number of stockpiles or another containers around?

**Comment by faiith** [comment]
I don't think it's related to containers/stockpiles, it also occurs if you're quiete deep in the  nowhere. Certainly, near stockpiles or containers, there are always FPS drops, or the game feels 'lazy'. The performance problems tend to be more independent. It seems really strange, if you start with the cart, you will be stuck every second step shortly. It's like rubberbanding without being pulled backwards. If you just keep on running, the problem will resolve after 20-30 seconds

**Comment by mirasrael** [comment]
Can you please upload `output_log.txt` ?

**Comment by faiith** [comment]
Sure :)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3028806/output_log.txt)

And to be clearly, without using a cart there's no issue at all^^

**Comment by mirasrael** [comment]
@faiith Thanks for log. It helped. I think I found and fixed cause of this issue.
