### ISSUE TITLE
[0.8.1.0-Staging 6] Economy Viewer Sorting does no longer work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11799]
When pressing some of the buttons the list below does change, but not as expected.
E.g. if i try to sort for price, the list does move but i get something like:

5
7
3
2
29
1

Which is no sorting, sorted would be:
1
2
3
5
7
29

Or 

29
7
5
3
2
1

**Comment by mirasrael** [comment]
Wasn't able to reproduce. Anything in client log?
![image](https://user-images.githubusercontent.com/475445/55244332-0ec38000-5252-11e9-88d3-84d8254128d2.png)

**Comment by D3nnis3n** [comment]
Works correctly in staging-7.
