### ISSUE TITLE
Black bar growing during character selection screen (staging 8.1)

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11795]
![image](https://user-images.githubusercontent.com/12839021/55213311-2b0ee080-51b0-11e9-986a-1204945acd6c.png)

**Comment by seccombew** [comment]
![image](https://user-images.githubusercontent.com/12839021/55213430-77f2b700-51b0-11e9-9ffe-b10d9144407a.png)

Alt-tab'ed back into game to find this.

**Comment by seccombew** [comment]
Black spots were dripping down like ink.
Rotated camera, and now fully black.
![image](https://user-images.githubusercontent.com/12839021/55213494-a8d2ec00-51b0-11e9-9be1-31b814318df4.png)

**Comment by Quadbro** [comment]
did you able to reproduce it 2 times?

**Comment by seccombew** [comment]
Only occurred once for me.
@SeanAtr0n thought it might have to do with temporal anti-aliasing, which I did have turned on.

**Comment by Quadbro** [comment]
nah, tried to reproduce it with different specs and conditions (inc anti-aliasing)... nothing =(

**Comment by SeanAtr0n** [comment]
a bug we can't reproduce isn't critical priority

**Comment by SeanAtr0n** [comment]
if this happens again the log file might be useful `%APPDATA%\..\LocalLow\Strange Loop Games\ECO`

**Comment by johnkslg** [comment]
Reproducibilty doesnt affect priority.    This will break the game for people and is critical.
@seccombew work with Sean to find a repro case?

**Comment by seccombew** [comment]
Moving to milestone 8.2, will be attempting to reproduce.

**Comment by johnkslg** [comment]
Closing until its seen a second time.
