### ISSUE TITLE
[8.1.0 Staging-5] Rubble is not targetable

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11792]
![notarget](https://user-images.githubusercontent.com/25908592/55182821-cdb66780-518e-11e9-8718-e8b9bf1727a4.png)

**Comment by mirasrael** [comment]
@D3nnis3n can you provide more details. How can I reproduce this?

**Comment by D3nnis3n** [comment]
Staging-6 does no longer have this problem somehow.
