### ISSUE TITLE
[0.8.1.0 Staging-7] BackPack don't work.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11808]
Without Backpack:
![2019-03-30](https://user-images.githubusercontent.com/45708377/55273856-c2278580-52e1-11e9-9f1a-9086d65cc81a.png)
With Basic Backpack:
![image](https://user-images.githubusercontent.com/45708377/55273873-f56a1480-52e1-11e9-8412-fc95f0276824.png)
With Bearpack:
![image](https://user-images.githubusercontent.com/45708377/55273884-20ecff00-52e2-11e9-96fc-a04042db844e.png)
This is definitely not an incorrect display. When I change my pack I can't take anything else.
Also, calories reduction for the Work Backpack and Work shoes doesn't work.

**Comment by SlayksWood** [comment]
Small addition: doesn't work only on the new server.

**Comment by mirasrael** [comment]
1. Does it starts working after server restart?
2. Do you have some issue on last release (0.8.0.7)?

**Comment by mirasrael** [comment]
Additional info. This issue happens to **every new user** until server restart.
