### ISSUE TITLE
After proposing law, getting "This law does not exist"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11804]
![image](https://user-images.githubusercontent.com/431728/55262352-4dd8ec00-52b9-11e9-97b6-fa213e98276c.png)

You can see the law "dfsdf" on the left which was proposed. The address is http://127.0.0.1:3001/laws.html?lawid=null so it looks like something has dropped the law id

**Comment by johnkslg** [comment]
Why did you mark this low? Would break whole law system

**Comment by redwyre** [comment]
The law is there, you just don't get redirected to it properly, you can just click it on the left.

**Comment by rainfarmer** [comment]
Sometimes it redirects before the server api can create the new law. 
Needs to wait for confirmation from server api for new law, might need to add that to the api
