### ISSUE TITLE
[0.8.1.0-Staging 6] Popup for Talent choice not opening

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11800]
Version: 0.8.1.0-Staging 6
Mods: None

Popup for choosing a talent-choice is not opening anymore

**Comment by mirasrael** [comment]
Already fixed in upcoming staging build.

**Comment by beastyn** [comment]
0.8.1.0 staging 7
no mods

I suppose this one should work now on staging 7, but still can`t open talent popup. It works just one time and need to reset Skill UI

**Reproduce**
1. Open Skill window
2. Select Skill you have
3. Click on Spec you have
4. Check Talent popup
5. Click on other Sspec you have (or select Spec in other Skill you have)

**Expected result**
current Talent popup should close and Talent popup for currently selected Spec should  open.

**Actual result**
with first click on currently selected Spec nothing happens, last Talent popup stays. With second click on new Spec old Talent popup is closing but new Talent popup is never appearing. And now you can open Talent popup only after reseting Skill window.

**Comment by mirasrael** [comment]
@beastyn Seems your issue not about talent selector, but about switching between specs. You can't switch between specs even without touching talent popup. This issue actually fixed as part of this https://github.com/StrangeLoopGames/Eco/pull/4180
