### ISSUE TITLE
Vehicle Parking

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11802]
Parking would disable physics, tween the vehicle to the closest voxel-aligned rotation and add worldobject blocks. It would only occur when you explicitly hit a new button or key binding. Vehicles would need to define occupancy that is only used during placement & parking.

This would prevent trees growing through parked vehicles, animals walking through vehicles or any other events that might move your vehicle without your consent.

**Comment by redwyre** [comment]
Is there anything stopping a tree from growing through a moving vehicle?

**Comment by SeanAtr0n** [comment]
nope, it has happened to me before... fixing that would take more effort than it's worth though

**Comment by D3nnis3n** [comment]
For reference: https://github.com/StrangeLoopGames/EcoIssues/issues/11696

**Comment by johnkslg** [comment]
You could use @mirasrael 's new BlockContainerManager: https://github.com/StrangeLoopGames/Eco/pull/4154
I wouldn't move the vehicle automatically or place world object blocks, too much to get our of sync

**Comment by SeanAtr0n** [comment]
there would be nothing to get out of sync, it'd be a worldobject that doesn't move while parked
