### ISSUE TITLE
USER ISSUE: 4523

### ISSUE THREAD

**Issue by Sergant1530** [StrangeLoopGames/EcoIssues#11809]
**Version:** 0.7.8.5 beta

**Steps to Reproduce:**
4576у45нурн

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```n
**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```

**Comment by redwyre** [comment]
You are using a very old version, please update to the latest.

Вы используете очень старую версию, пожалуйста, обновите ее до последней версии.
