### ISSUE TITLE
"A law with this name already exists" when proposing law with no visible laws in proposed or active

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11805]
Not sure if this has something to do with "one-shot" laws that aren't visible in the interface

**Comment by D3nnis3n** [comment]
Afaik working as intended. Laws that were used only to repeal other laws, create or redefine districts or demographics were there, but are not visible. Not sure if that should be changed.

**Comment by D3nnis3n** [comment]
E.g. laws that names are used but you cannot see:
- All repealed laws
- All laws that create or redefine districts or demographics
- All laws that only do a thing once

**Comment by johnkslg** [comment]
Will work in 9.0

**Comment by Deantwo** [comment]
Yeah would definitely be nice if we could see all past laws.
Always hated that all the comments on a law becomes unreadable once the law is refused. Hard to make a better law if you can't see what people disagreed with.

By the way, would be nice if we could comment on laws even after they were passed or repealed and such. But that might be confusing.

**Comment by johnkslg** [comment]
Should be fine in 9
