### ISSUE TITLE
USER ISSUE: water pump

### ISSUE THREAD

**Issue by dmanning6522** [StrangeLoopGames/EcoIssues#11819]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
place sink and hook up to pipes

**Expected behavior:**
water to be used by the sink

**Actual behavior:**
water is hooked up but sink wont work status says no water even though there is

**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by johnkslg** [comment]
@dmanning6522 Can you attach your game.eco file so we can take a look?

**Comment by dmanning6522** [comment]
Is this something that is stored on my personal computer? Or that is on the
server files of the server I play on?

**Comment by Quadbro** [comment]
That stuff is not reproduced in upcoming 8.2, and probably user crossed water/sewage pipes somewhere
