### ISSUE TITLE
Incorrect Icon for skill efficiency and speed

### ISSUE THREAD

**Issue by Meerkats961** [StrangeLoopGames/EcoIssues#11817]
![Bugreport](https://user-images.githubusercontent.com/49105866/55281655-de411c00-530d-11e9-9da0-5c49c52c35ab.png)

This seems to happen with all the specialties. (When hovered over it displays correct information in tooltip)

**Comment by Meerkats961** [comment]
Version: 0.8.7 Beta

**Comment by SlayksWood** [comment]
0.8.1.0 staging-8 same
