### ISSUE TITLE
[Staging 8.1 -7]  Missing Receipes in all kinds of Workbenches

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11811]
Version 8.1-7
No Mods
German localisation

In all kinds of workbenches is something weird going on (see pictures below). it occurs from time to time, no clue what the cause is. If you pickup the workbenches and place it again, it works again for few minutes.

![382310_20190330151210_1](https://user-images.githubusercontent.com/40213281/55277291-c31ae000-52fe-11e9-807a-45c022f87d75.png)

![382310_20190330151310_1](https://user-images.githubusercontent.com/40213281/55277294-c746fd80-52fe-11e9-9723-351ffdda61a2.png)

**Comment by redwyre** [comment]
Was just discussing this with @mirasrael and he has a fix in https://github.com/StrangeLoopGames/Eco/pull/4180

**Comment by Sobaton** [comment]
sometimes when the table work is done, the normal interface comes back! Happens on all workingtables
