### ISSUE TITLE
[8.1.0-Staging-6] Crane can't be seen moving by a third player in multiplayer

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11810]
Quote from SlayksWood

8.1.0 Staging-6
Crane doesn't show correctly in multiplayer.
When I look from the side as someone works on a crane, the crane does not move at all, only constructed objects appear.

**Comment by mirasrael** [comment]
This issue isn't related to view sync. Actually it isn't even regression, it doesn't work in 8.0.7 (before any view sync changes).
