### ISSUE TITLE
Face Remover Needs more Optimization

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11814]
When you put 3 types of floor block (Corrugated Steel; Brick; Flat Steel) near the wall, they seem to shine through. As far as I know this bug isn't only in this version.
![image](https://user-images.githubusercontent.com/45708377/55278138-87d9da80-5319-11e9-837e-95d2ae85e6e8.png)

**Comment by johnkslg** [comment]
Related to sparkle PR?  Or Art bug?

**Comment by SeanAtr0n** [comment]
these blocks aren't truly 'solid' from an art perspective

**Comment by SlayksWood** [comment]
From #4286
1. Framed Glass with Road Dirt
![image](https://user-images.githubusercontent.com/45708377/56956636-69037980-6b4d-11e9-8375-9a787a62505a.png)
2. Lumber Floor with Lumber Wall
![image](https://user-images.githubusercontent.com/45708377/56957008-7bca7e00-6b4e-11e9-8ad2-f760e78e9e7c.png)

**Comment by keegan-o** [comment]
I don't suppose you ever got a chance to try the last idea you had for this Eric? Whether the problem can be fixed determines whether or not I will eventually need to go back and come up with a different solution for blocks that create holes. It definitely would cost us lots of fun and more unique shapes if so, but this has been in limbo for a long time.

**Comment by keegan-o** [comment]
This has been an issue for long enough that I'm going to assign sean as well in-case he has any other thoughts-- changing the holes to be covered by black geo has certainly helped the way this looks, but it's still somewhat glaring.

**Comment by keegan-o** [comment]
Also, the way faces are deleted on the lumber floor block as shown in the screenshot show how this can affect things other than just concave blocks against cube blocks.

**Comment by SeanAtr0n** [comment]
seems like these blocks shouldn't be marked as 'solid' client-side? (should rename that some day to avoid confusion)

**Comment by keegan-o** [comment]
I tried un-marking them as solid but the holes are still there, at least for brick floor.

**Comment by keegan-o** [comment]
(and of course that also breaks tool interaction which is I assume why you're saying it should just be client side)

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/57109390-3347c780-6cea-11e9-835f-988c9f578c6c.png)
you used this box?

**Comment by SeanAtr0n** [comment]
oh yeah, guess it doesn't do collision then >.<

**Comment by keegan-o** [comment]
When I did that I got solid black, not the other block working, sure that's a case where the hole would be?

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/57109824-57f06f00-6ceb-11e9-8930-e91cd1e8fd09.png)

**Comment by redwyre** [comment]
If the server thinks a chunk is fully encased by solid objects it wont send it. I made some changes a little while ago that allows you to specify if a block doesn't encase... but that's at the block level. If you're willing to set these blocks to not encase that could potentially make the server send more chunks.

On the client side we probably need to split "Solid" into a collision flag and a visual flag.

**Comment by SHiRaIK** [comment]
![Visual_Bug](https://user-images.githubusercontent.com/51791785/59441457-e54dd580-8df8-11e9-8481-609c5fc0ff4c.jpg)

**Comment by redwyre** [comment]
Downgrading to medium as the visual problem is fixed, but it's not as efficient as it could be.

**Comment by SlayksWood** [comment]
@redwyre 
Should it be reassigned to another milestone?

**Comment by SlayksWood** [comment]
Don't want to create another issue, so 
![image](https://user-images.githubusercontent.com/45708377/96441280-f2ab7900-1211-11eb-8dbc-f62c3da7306b.png)

**Comment by redwyre** [comment]
@SlayksWood can you reopen https://github.com/StrangeLoopGames/EcoIssues/issues/13940 and move this there?

**Comment by redwyre** [comment]
I'm closing this issue as the issues here are fixed and there are other issues for the optimisation
