### ISSUE TITLE
USER ISSUE: Unable to move camera around

### ISSUE THREAD

**Issue by SplattedRabbit** [StrangeLoopGames/EcoIssues#11822]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1.) Try to move the camera with my mouse	

**Expected behavior:**
Camera should be moving

**Actual behavior:**
Nothing Happens!

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing Happens!

**Comment by redwyre** [comment]
Hi @SplattedRabbit, do you see a mouse cursor while you are unable to move? Does pressing "Tab" help?

If not, can you post a screenshot?

**Comment by SplattedRabbit** [comment]
Sorry, was a bit ranty yesterday.

Mousemovement through the Menus and while holding tab is no problem at all but doesn't help with the problem. 
I reinstalled the game a few times, also with the last 4 earlier builds and a last 0.7.x.x. build but nothing seemed to help. 

Screenshot will come later.

**Comment by D3nnis3n** [comment]
Are you affe_mit_waffe from the steam reviews? I created another issue for that here: https://github.com/StrangeLoopGames/EcoIssues/issues/11824

If you are, please tell me, so that i can close that issue.

**Comment by SplattedRabbit** [comment]
Yep, this is me :)

**Comment by D3nnis3n** [comment]
Also attach your system specs, please.

**Comment by redwyre** [comment]
Are you able to attach your log as well?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

After you submit the log file, you can also try going into %LOCALAPPDATA%Low/Strange Loop Games and renaming the Eco folder (to something like Ecox) and running Eco again and see if it's still happening. If that fixes it please zip up that folder and email it to simon@strangeloopgames.com (it can contain personal information so better to not post it here)

**Comment by redwyre** [comment]
Hi @SplattedRabbit, we have released 8.1, could you try it out and report back?

**Comment by D3nnis3n** [comment]
Hey, is this issue still persisting?

**Comment by D3nnis3n** [comment]
Reopened.

**Comment by D3nnis3n** [comment]
![camera](https://user-images.githubusercontent.com/25908592/57128465-c8eb6180-6d93-11e9-966c-dd21fd6d4b21.png)

**Comment by alkarym** [comment]
Yup! That's me! Not near my laptop at the moment and going to work.  Will check again and fill in the gaps.  Basically,  when i press tab,  a cursor appears. When i click any mouse button or press tab again,  the cursor disappears but the camera stays fixed. I can move and navigate menu quite well but i can't move the camera. 

Also: when I chat,  every keystrokes on the keyboard,  while focused on the chat entry line,  still pops the appropriate windows... not sure if it's related but it sure is annoying as hell!

Up till now,  i tried;
    -uninstalling/reinstalling 3 times
    -running other versions on steam (off the top of my head: 0.8.0.0, 0.8.1.3 and the bleeding edge)
    -saw a post from 2018 about the same problem so i tried stopping my firewalls.
    -searched breifly for the folder in \roaming but couldn't find one.

**Comment by beastyn** [comment]
@alkarym 
Can you follow this instruction?

> Are you able to attach your log as well?
> https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> 
> After you submit the log file, you can also try going into %LOCALAPPDATA%Low/Strange Loop Games and renaming the Eco folder (to something like Ecox) and running Eco again and see if it's still happening. If that fixes it please zip up that folder and email it to simon@strangeloopgames.com (it can contain personal information so better to not post it here)


It will be really helpful, thank you.

**Comment by alkarym** [comment]
Okay!! Edit:

Yes! The folder was in appdata\locallow not roaming as I was first led to believe... 

This said, renaming the eco folder worked.  I was briefly home and will email the folder later tonight but this definitely fixed whatever problem was still present. 

As I said, I'm a returning player.  Chances are this folder has stuff going back maybe a year and,  since I guess not many players are returning from long leaves like me,  it's not that often that this problem arises. 

Anyway,  now working,  can't wait to come back from work!!

**Comment by redwyre** [comment]
Thanks @alkarym, your existing control config was corrupted which proves my hunch. Will look into how this could happen and hopefully stop it from happening again :)

**Comment by alkarym** [comment]
Glad i could help! Sure hope it allows you to squash that bug for good
