### ISSUE TITLE
Made a Discord for Server ads as owner and get banned

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#11826]
Made a Discord account to post Server ads and get banned in 5 min....

**Comment by Arend90** [comment]
Pam:
Rge server-ads rules are pinned in the channel and the ads may only be posted by the server owner .  Our knowledges is that Arenbds is teh server owner and he would need to post the ad

**Comment by D3nnis3n** [comment]
You are banned on the discord, circumventing a ban is against the rules. So you may not post ads.
