### ISSUE TITLE
USER ISSUE: Terrain not loading

### ISSUE THREAD

**Issue by zacharek** [StrangeLoopGames/EcoIssues#11828]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
Create custom world
Go to coordinates x=0
Face side where x is decreasing( into other side of the world)

**Expected behavior:**
Loaded the terrain

**Actual behavior:**
Loading only objects like trees, grass, animals, but not the terrain

**Do you have mods installed? Does issue happen when no mods are installed?:**
Loading only objects like trees, grass, animals, but not the terrain
![20190401195948_1](https://user-images.githubusercontent.com/23366276/55349427-f9508f00-54b9-11e9-88c2-0db15e7c3f9f.jpg)

**Comment by redwyre** [comment]
Can you upload the output log after this happens?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by zacharek** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3033452/output_log.txt)

**Comment by johnkslg** [comment]
This happens when the world is small. What size is your world?

**Comment by johnkslg** [comment]
@metachronism lets extend support for smaller worlds, probably is easy

**Comment by seccombew** [comment]
Closed as dupe
