### ISSUE TITLE
Title Chat Commands

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#11825]
Just learned that three chat commands exist to manage titles.
- `/titleset`
- `/titlelist`
- `/titleassign`

They do not appear to work correctly, but using the Registrar table works fine.

I am guessing these are actually developer test commands that aren't meant to be used by players? Since they weren't mentioned in any patch notes or anything.

**Comment by D3nnis3n** [comment]
/titlelist works, the rest are commands for upcoming 9.0, afaik.

**Comment by johnkslg** [comment]
should be all good now, theyve changed somewhat. Also
/objects <command> title
can do stuff
