### ISSUE TITLE
USER ISSUE: bs

### ISSUE THREAD

**Issue by DuckDGoose** [StrangeLoopGames/EcoIssues#11820]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
this is fucking bullshit

**Expected behavior:**
it should fuc king work

**Actual behavior:**
The following error message popped up:
``` FUCK U 
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
``` FUCK U 
<size=150%>Connection Failed</size>

Invalid login info.
```

**Comment by redwyre** [comment]
@DuckDGoose please be respectful to those that are here to help you

**Comment by redwyre** [comment]
Are you able to log in to the website at https://accounts.strangeloopgames.com/ ? Have you tried resetting your password?

**Comment by johnkslg** [comment]
Check password on strangeloopgames site
