### ISSUE TITLE
Laws: Place where item is Skid Steer or Truck or Excavator

### ISSUE THREAD

**Issue by Sobaton** [StrangeLoopGames/EcoIssues#11832]
making Laws like
![grafik](https://user-images.githubusercontent.com/48158779/55385016-7f0d2280-552c-11e9-9486-9210de02f834.png)
you cant pick as Item "Skid Steer", "Excavator" or "Truck" (all from skill Industry) for the laws
---
Version: 0.8.0.7 and 0.8.1.0 #0c12c40e

Steps to Reproduce:
1.) Try to make a Law whit "item is"

Expected behavior:
dropdown menue whit "Skid Steer", "Excavator", "Truck" ("Crane",  ..?)

Actual behavior:
"Skid Steer", "Excavator", "Truck", .. are missing in the dropdown menue 

Do you have mods installed? Does issue happen when no mods are installed?:
no mods, dont try mods to fix it

**Comment by SlayksWood** [comment]
Checked on 0.9.0 staging-1183. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/67566657-1c31e180-f731-11e9-8b0b-882ffc19e985.png)
