### ISSUE TITLE
[0.8.1.0 staging-8] Pipes want to connect from the wrong side.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11838]
If in the place where the pipe is connected to the object to bring the pipe to the other side, then the pipe will want to connect to the object from the other side.
The water supply from the wrong side will not work. But I suppose that it simply rests against the block, and therefore the exit of the pipe closes.
![image](https://user-images.githubusercontent.com/45708377/55404142-f60fde80-555f-11e9-96f3-84d10f909d56.png)
![image](https://user-images.githubusercontent.com/45708377/55404200-0d4ecc00-5560-11e9-8a51-ff5ca248a06f.png)

**Comment by johnkslg** [comment]
Cosmetic, but yes should be fixed.

**Comment by beastyn** [comment]
some addition is here #10199

**Comment by elfl0rd** [comment]
and old one - #6024

**Comment by keegan-o** [comment]
Duplicate
