### ISSUE TITLE
[0.8.1.0 staging-8] Empty tab "Pump" in Electric/Mechanical Water Pumps

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11839]
Electric Water Pump Menu differ from Mechanical Water Pump Menu (Pump and Pipes).
![image](https://user-images.githubusercontent.com/45708377/55406174-3e310000-5564-11e9-8acd-edcd51022819.png)
![image](https://user-images.githubusercontent.com/45708377/55406222-5b65ce80-5564-11e9-86be-bd91556f80ea.png)

**Comment by johnkslg** [comment]
breaks pipes, something wrong with the electric one's config.  @SlayksWood good find

**Comment by craig-jong** [comment]
I don't know what to say, but this is not reproducible for me.

![image](https://user-images.githubusercontent.com/18184943/55437613-2cdff780-5554-11e9-86ee-c1354d7b9831.png)

I'll take another look once the new staging build is out.

**Comment by SlayksWood** [comment]
I meant that the tabs of pumps and pipes in different pumps (Electrical and mechanical) are arranged in a different order:
Electric: PUMP - PIPES - power - status - autorization
Mechanikal: PIPES - PUMP - power - status - autorization
It is in this question that only this is implied.

**Comment by SlayksWood** [comment]
I meant that the tabs of pumps and pipes in different pumps (Electrical and mechanical) are arranged in a different order:
Electric: PUMP - PIPES - power - status - autorization
Mechanikal: PIPES - PUMP - power - status - autorization
In this issue I meant only that. It's not critical but when you test two pump together it's quite uncomfortable.
Sorry!  I will be more precise next time.

**Comment by beastyn** [comment]
Do we need pump?

**Comment by SlayksWood** [comment]
My issue was fixed in 0.9.0. But we still have question: Do we need pump?
![image](https://user-images.githubusercontent.com/45708377/71443680-7a714580-271d-11ea-8db7-2199e4131bc3.png)
![image](https://user-images.githubusercontent.com/45708377/71443684-7e04cc80-271d-11ea-82d6-832f077885a0.png)

**Comment by WeaselDog** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/5497
