### ISSUE TITLE
[0.8.1.0 staging-8] Incorrect in mining while work low level pickaxe

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11833]
1. To break a stone above the level of a pickaxe, you need to hit the required number of times in a row on one stone.
For example, take basalt:
To break the basalt, I need to hit a stone pickaxe 6 times. If I hit a stone pickaxe 5 times and then hit a nearby stone 1 time, then in order to destroy the first stone I need to hit it again 6 times.
If I hit a stone 5 times, and then I would do another job (not to mine, but let's cut down a tree, build a house and etc.), then when I take a stone pickaxe after a time (I checked for 5 minutes) and hit exactly the stone in which before I hit 5 times, then it would break.

2. Calories are removed only for the last hit. 5 hits I do for free and for 6 hit the usual quantity of calories is removed 

3. About the same as with calories. I do 5 hits and "User remaining" is not removed, but on 6 hit there is a decrease of "User remaining" by one.

**Comment by Sobaton** [comment]
same in 8.0.7

**Comment by johnkslg** [comment]
Could stand to be polished as described

**Comment by D3nnis3n** [comment]
Actually duplicate of #11667

**Comment by D3nnis3n** [comment]
As well as #11668
