### ISSUE TITLE
[0.8.1.0 staging-8] Create new Contract, Name of Deposits not showing

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11834]
Version: [0.8.1.0 staging-8]
Mods: None
Localisation: German

If i'm creating a new contract, and want to choose a deposit, the names of the deposits are not shown in the list:

![382310_20190402111024_1](https://user-images.githubusercontent.com/40213281/55390784-38252a00-5538-11e9-9304-3bca170a4b2b.png)

**Comment by mirasrael** [comment]
Hi @faiith I was able to reproduce issue with blank icons (fixed), but didn't get any problem with text. Can you attach output_log.txt please?

**Comment by faiith** [comment]
Requested log: 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3034680/output_log.txt)

:)

**Comment by johnkslg** [comment]
Fixed!
