### ISSUE TITLE
USER ISSUE: cant log in 

### ISSUE THREAD

**Issue by skylaralexander585** [StrangeLoopGames/EcoIssues#11840]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
wont let me log in, and i have double checked my password multiple times i know its correct 

**Expected behavior:**
to be logged in

**Actual behavior:**
The following error message popped up:
``` pasword and log in are invvalid
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
``` pasword and log in are invvalid
Invalid username or password.
```

**Comment by skylaralexander585** [comment]
no mods are installed

**Comment by johnkslg** [comment]
Steam is having trouble, you can download the game from our site in the meantime strangeloopgames.com

@mirasrael can you investigate giving error messages that place blame on steam when thats the case? This has happened a few times

**Comment by mirasrael** [comment]
@skylaralexander585 did you login with Steam or with SLG login?

**Comment by johnkslg** [comment]
This was a problem with steam failing for a lot of users the other day, was almost certainly steam

**Comment by mirasrael** [comment]
@johnkslg "Invalid username or password." only should show for non-Steam accounts.

**Comment by mirasrael** [comment]
@skylaralexander585 there was incorrect error message in case if account temporary blocked (i.e. in result of too many invalid login attempts). I fixed error message, but if you still experiencing problems then let us know - we can investigate issue with your account.
