### ISSUE TITLE
Title screen went crazy during loading of world

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11845]
![image](https://user-images.githubusercontent.com/3536496/55436684-d1146f00-5551-11e9-8842-e0d74e3bbdfe.png)
This was when hosting a new world in the staging build.

**Comment by johnkslg** [comment]
The lighting flipped to come from below.  Probably related to spawning in of lights?

**Comment by SlayksWood** [comment]
It always happens in the same place at the same time. Light appears approximately 69 seconds after the start of the download.

**Comment by SlayksWood** [comment]
Seems fixed
