### ISSUE TITLE
[0.8.1.0-release-preview] Holey pipes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11846]
When there is an object nearby, the pipe begins to "flow". Visually, it is displayed that is connected, but in fact the water goes in a straight line.
![image](https://user-images.githubusercontent.com/45708377/55457830-d3c7a080-55f3-11e9-9904-40a3d3e8d18d.png)

That works well:
![image](https://user-images.githubusercontent.com/45708377/55458125-bf37d800-55f4-11e9-9b73-c844b32f532d.png)

If I put a nearby object:
![image](https://user-images.githubusercontent.com/45708377/55458172-e1315a80-55f4-11e9-85e0-2307d9038a35.png)
And it is not cosmetic. the Blast Furnace stops working: water needed.
![image](https://user-images.githubusercontent.com/45708377/55458364-6e74af00-55f5-11e9-8e73-2c455500b400.png)

**Comment by johnkslg** [comment]
Something weird with 'open end' detection

**Comment by SlayksWood** [comment]
Steam Engine:
![image](https://user-images.githubusercontent.com/45708377/58401525-c6b0b600-8066-11e9-9853-22782082e027.png)
All objects with pipes need to remake: Waste Filter, Electric Water Pump, Mechanical Water Pump, Blast Furnace, Steam Engine, Oil Refinery, Combustion Generator, Sink, Laboratory.

**Comment by SlayksWood** [comment]
@johnkslg 
Steam engine has water connection. But does not require water connection. Do it not complete?

**Comment by DrRush12358** [comment]
![image](https://user-images.githubusercontent.com/16111056/59233771-dc21f600-8bb7-11e9-82d7-ecd37524890e.png)

Sewer pipes also leak but its almost random. I currently have a room full of piped generators laid out in a grid and a second story laid out in a near identical manner. And for whatever reason some of the sewer connections leak and some don't. Even if the arrangement of the pipes and nearby objects is identical.

**Comment by SlayksWood** [comment]
@DrRush12358 
Can you provide your save files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by DrRush12358** [comment]
This is on the official otter server

**Comment by elfl0rd** [comment]
A little more about leaks - https://github.com/StrangeLoopGames/EcoIssues/issues/11363

**Comment by SlayksWood** [comment]
#18344
> if you connect 2 machines consuming water in parallel, then when one of the machines is turned on, a fountain of dirty water gushes at the place where the second machine is connected to the sewage system.
> ![изображение](https://user-images.githubusercontent.com/13696708/93662288-b85e8880-fa67-11ea-98b6-0d4d0d8363f6.png)
> video with problem:
> https://youtu.be/c5CXIwZmGJA

**Comment by SlayksWood** [comment]
It became worst:
![image](https://user-images.githubusercontent.com/45708377/96082911-cc5da480-0ec4-11eb-8114-7fde0c0d68fd.png)
Now if there is pipe leaking, the craft station does not work

> ![pipe_leak](https://user-images.githubusercontent.com/8235842/96016772-70096f00-0e49-11eb-9da8-6f68d088b03a.png)
> 
> **Version:** 0.9.0.5 beta release-100
> 
> **Steps to Reproduce:**
> 
> 1. Place the pump
> 2. Place 2 Blast Furnaces
> 3. Connect furnaces to pump
> 4. Power up the pump
>    If the effect does not occur, try add more machinery.
> 
> **Expected behavior:**
> Water is not springling from the pipe and it should go into machinery.
> Machinery should work.
> 
> **Actual behavior:**
> Water is leaking from the pipe despite the pipe being closed.
> Machinery is ready and green, but turn red (missing water) when there is work to do.
