### ISSUE TITLE
USER ISSUE: There us no UI on boot

### ISSUE THREAD

**Issue by Vantropix** [StrangeLoopGames/EcoIssues#11854]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
start game
load world
have no ui
be scared

**Expected behavior:**
there would be a hotkey for it

**Actual behavior:**
it's just gone with no way to fix it

**Do you have mods installed? Does issue happen when no mods are installed?:**
i have no mods at all

**Comment by mirasrael** [comment]
Hi @Vantropix Thanks for report. Can you provide more information?

- Screenshots
- output_log.txt from %LocalAppData%Low\Strange Loop Games\Eco

BTW, there are hot-key Alt-Z to hide and show UI (usually for nice screenshots) if you're meaning something like this.

**Comment by mirasrael** [comment]
Seems like Alt - Z was accidentally pressed. @Vantropix If issue is different and you have any additional info, please, add comment and we will re-open issue.
