### ISSUE TITLE
[0.8.1.0 staging-8] Display-Bug Brick-Floor

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11855]
I've a weird display-bug, using brick-floors next to full blocks (regardless which material used)

![382310_20190403200930_1](https://user-images.githubusercontent.com/40213281/55502342-a5c27a80-564c-11e9-8fe0-593db8582ffe.png)

**Comment by SlayksWood** [comment]
duplicate #11814
