### ISSUE TITLE
[0.8.1.0-release-preview] No marker on deposit with in-game helper in Harvest Contract

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11853]
[0.8.1.0-release-preview]

After taking harvestin contract you can see a harvest marker (with in-game counter), but ehre is no marker for a deposit stockpile.

**Steps**
1.Take harvesting contract
2. Look at markers that should appear

**Expected result**
You can see markers for harvest place and deposit place with in-game object counter.

**Actual result**
You can see harvesting place but you can`t see deposit place. 

![bandicam 2019-04-03 18-47-22-600](https://user-images.githubusercontent.com/27898520/55484166-735f5000-5641-11e9-920e-e6bae786868d.jpg)

**Comment by D3nnis3n** [comment]
You don't need to deposit anyway, can just check the contract completed

**Comment by Quadbro** [comment]
@D3nnis3n  i can't do so, it requires to put stuf in container...

**Comment by beastyn** [comment]
somehow Dennis could close this contract without deposit. I can`t recreate )

**Comment by D3nnis3n** [comment]
Tested german / Mixed lang?

Anna <notifications@github.com> schrieb am Do., 4. Apr. 2019, 13:53:
