### ISSUE TITLE
[0.8.1.0-release-preview] Elevator broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11851]
1.I get on the elevator platform. I push the button down. The elevator starts to go down. I'm staying on top.
![image](https://user-images.githubusercontent.com/45708377/55478418-5ff1bc00-5624-11e9-8058-bfeff9e68116.png)
I can't fall into the hole (only if I dig under the side). And I run on an invisible platform.
In 0.8.1.0 staging-7 it works.

2. Incorrect display of the elevator for different users. (Such issues are started but described a little differently.)
For me he was somewhere in the center. I called @beastyn so she looked where he was displayed for her. For her, he was top. She pushed the button down, my version of the elevator was gone. Elevator drove from the top down.
https://drive.google.com/file/d/1qZzpWrJeoOmmRwG_UwPOkOUg9JE2TVsE/view?usp=sharing

**Comment by SeanAtr0n** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/11551

**Comment by SlayksWood** [comment]
It isn't a duplicate. Even if the behavior in multiplayer can be attributed to the same bug.
But the fact that I basically can't move on the elevator issue #11551 hasn't description (paragraph 1).
