### ISSUE TITLE
[8.1.0 Release Preview] Tree saplings do not appear in pots

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11857]
Put tree saplings into the pots to get a screenshot of the bonsai trees for the changelog and found out that nothing is displayed there even after fast forwarding two days.

![bonsai](https://user-images.githubusercontent.com/25908592/55518066-ea610c80-5672-11e9-840f-a526eb8307ef.png)

**Comment by Spydarlee** [comment]
This is fixed and working on master, discussing with @johnkslg whether we want to bump the priority up and get this working correctly on staging/release, too.

![image](https://user-images.githubusercontent.com/553695/55890340-71017680-5baa-11e9-9708-338cc7842064.png)

**Comment by johnkslg** [comment]
Can you push to master too since its a regression?

**Comment by johnkslg** [comment]
Elevating because although its cosmetic it breaks the city layouts people built

**Comment by Spydarlee** [comment]
Hmm, I just synced up to the release branch and this actually seems to be working fine there as well. Are you still seeing this, @D3nnis3n? Do you get any errors? Do you have a log you could upload?

![image](https://user-images.githubusercontent.com/553695/55961105-0877cf80-5c66-11e9-8e4f-8e105f4e860c.png)

**Comment by Spydarlee** [comment]
Ooh, I just ran the game in Japanese and got the bug. I see the original bug is in German so perhaps this is localization related. Don't see why it should be, but I have a lead to investigate now!

**Comment by D3nnis3n** [comment]
Yep, had the game running on german and can still see the issue. Weird that localization is causing this issue.

**Comment by Spydarlee** [comment]
Turns out it was because I was using the species name of the seed to determine the plant to show, but I was accidently using the localized species name for the lookup. Fix pending merge!
