### ISSUE TITLE
[0.8.1.0-release-preview] Can`t change currency for contract

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11852]
[0.8.1.0-release-preview]
no mod

After creating a contract an opening again you see that currency is always global. 

**Steps**
1. Create new contract with payment clause.
2. Set currency to something different from global
3. Close contract
4. Open created contract

**Expected result**
Currency should stay as it was installed

**Actual resul**
Currency became global

![bandicam 2019-04-03 18-20-48-032](https://user-images.githubusercontent.com/27898520/55482633-64c36980-563e-11e9-9b62-8d67c8cc5454.jpg)
![bandicam 2019-04-03 18-20-50-720](https://user-images.githubusercontent.com/27898520/55482637-668d2d00-563e-11e9-8791-4d6d1cdd4e4a.jpg)
![bandicam 2019-04-03 18-20-53-780](https://user-images.githubusercontent.com/27898520/55482643-67be5a00-563e-11e9-80ac-8f53790256ca.jpg)

**Comment by redwyre** [comment]
@Quadbro I believe you wished to be notified of issues like theses

@beastyn Can you confirm if the contract has changed or if it's just an issue with the UI displaying the wrong value?

**Comment by beastyn** [comment]
@redwyre I suppose it was changed, because after complitig payment was made in wrong currency, not that I implement in creation window but in global.
