### ISSUE TITLE
USER ISSUE: Invalid Login Info

### ISSUE THREAD

**Issue by gregoryl09** [StrangeLoopGames/EcoIssues#11850]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
1.) Kicked for Login Token Changed.
2.) Attempt to login

**Expected behavior:**
It should have asked for a server password and logged in or not have kicked me to begin with.

**Actual behavior:**
The password box never appears and a message pops up stating invalid login info.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed. Privately hosted server. Worked fine until this morning.

**Comment by johnkslg** [comment]
Steam was failing yesterday, should be better now
