### ISSUE TITLE
[8.1.0 Release Preview] Level Up symbol still hinders hunting

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11858]
Got several level up messages appearing directly at my cursor, no longer being able to see animals.

**Comment by johnkslg** [comment]
Should move the level up thing higher. This was done before but probably only got pushed to staging or release SVN.

**Comment by gzatravkin** [comment]
Can't reproduce it. Please attach a video

**Comment by SlayksWood** [comment]
I think this issue is about it:
![image](https://user-images.githubusercontent.com/45708377/67923103-d015ef80-fbbd-11e9-8d16-d8a64110c21a.png)
Perhaps related to resolution. Anna haven't this problem, but I have. I have monitor with resolution 1680x1050.

**Comment by beastyn** [comment]
![bandicam 2019-10-31 11-05-19-333](https://user-images.githubusercontent.com/27898520/67923296-3e16e280-fbcf-11e9-8bae-4c7a4c5e56f3.jpg)

**Comment by beastyn** [comment]
We don't have problems with animals. Just position for levelup.
