### ISSUE TITLE
[0.8.1.0-release-preview] Bad log with client launch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11866]
[0.8.1.0-release-preview]
no mods

Please, look at this log, First launch in new world. And it has exceptions
(nothing bad happens in client, but still)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3043461/output_log.txt)

**Comment by SeanAtr0n** [comment]
looks like these exceptions here result in issues described in https://github.com/StrangeLoopGames/EcoIssues/issues/11870 , going to close this bug as a duplicate just because several players commented in the other
