### ISSUE TITLE
DeerLichen blocks placement

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11868]
In master:
![DeerLichenBug](https://user-images.githubusercontent.com/774628/55581100-e237ba00-56d0-11e9-9390-eed4bf74e5b0.gif)

Think it's because its collider's center is at or below the voxel it occupies

**Comment by SlayksWood** [comment]
need to check in 8.2

**Comment by johnkslg** [comment]
Can do for 8.2? @keegan-o

**Comment by keegan-o** [comment]
Fixed in master/staging.
