### ISSUE TITLE
[0.8.1.0-release-preview] Broken repeated contracts 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11865]
[0.8.1.0-release-preview]
no mods

You can take few copies of repeated contracts in one time, but just one can be closed

**Steps**
1. Let someone make repeated contract for put item in container
2. Take it several times
3. Put item in container
4. Close contract
5. Put one more time item in container
6. Try to close contract

**Expected result**
You won`t be able to take more that one copie of repeated contract in one time. Ad every repeated part shouls close with success.

**Actual result**
You can take few copies of contracts but you can close just the first one.

**Comment by johnkslg** [comment]
Yes dont allow taking multiple copies of the same contracts
/testcontracts will help you here, youll need to make a simple contract with repetitions allowed. Then login with a different account and accept it.  Ask jeff for a second account if you need one
