### ISSUE TITLE
[0.8.1.0-release-preview] 3d person view tool animation tweaks

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11861]
[0.8.1.0-release-preview]
no mods

Now animation actually works, but scythe doesn`t show repeated action.

**Steps**
1. Go somewhere with bunch of grass
2. Toggle to 3d prson view
3. Take scythe and begin working

**Expected result**
Animation should be repeated. As it works in 1d person view
*Actual result*
Animation was shown just once and then grass was mowed without animation

![scythe_3d](https://user-images.githubusercontent.com/27898520/55531280-0ee4d500-56c3-11e9-9b8a-a03d6d730e7c.gif)

**Comment by SeanAtr0n** [comment]
fixed in svn
