### ISSUE TITLE
[0.8.1.0-release-preview] Can`t set authorization after reclaiming property

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11864]
[0.8.1.0-release-preview]
no mods

**Steps to reproduce**
1. Place stockpile with claiming
2. Check if you can authorize people in it
3. Unclaim it
4. Ask someone other to claim it
5. Unclaim it
6. Claim it yourself again
7. Check authorization

**Expected result**
You can choose user in authorization field
**Actual result**
Authorization field is not usable

It can be fixed with hammer collecting object and placing it again.

**Comment by johnkslg** [comment]
Probably something is not updating the authorization status on the server. This is done with the .Changed function which gets passed in the name of the parameters.

**Comment by seccombew** [comment]
Added High priority label, because feature is technically broken.

**Comment by mirasrael** [comment]
In 8.2 I fixed a problem with auth wasn't properly initialized on server load, may it was related. Can you re-check it on 8.2?
