### ISSUE TITLE
Elevators do not function

### ISSUE THREAD

**Issue by antimodes221** [StrangeLoopGames/EcoIssues#11873]
After upgrade to 8.1.0 elevators no longer appear to be able to carry players or carts.

When the elevator is in a neutral position (at the top) you cannot walk through them, its a solid block.  When you hit the call button it plays the animation for the lift going down however the floor remains solid.  

If you hit the call button at the bottom the lift goes up but the floor passes through the player or cart.

**Comment by BlazeGuy2** [comment]
Dup of #11870
