### ISSUE TITLE
USER ISSUE: Elevator

### ISSUE THREAD

**Issue by Aviator5811** [StrangeLoopGames/EcoIssues#11875]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Placing elevator.

**Expected behavior:**
Elevator moves character.

**Actual behavior:**
Elevator moves graphically, but the hitbox remains static and acts as if you didn't move the elevator.  Started as of last update.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Elevator moves graphically, but the hitbox remains static and acts as if you didn't move the elevator.  Started as of last update

**Comment by SlayksWood** [comment]
Dup of #11870
