### ISSUE TITLE
USER ISSUE: skills showen in the left bottom is buged

### ISSUE THREAD

**Issue by TOTRanger** [StrangeLoopGames/EcoIssues#11872]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
the spot down left used to show all my skills but now no mather how many i set it to in the setting's for the snamm menu it only shows 2 of my skill's. and both skill's are maxed out.

**Expected behavior:**
i used to be able to show all my skills so i could keep track of them

**Actual behavior:**
it only shows 2 skill's and not the once i want and im not able to change how many are showen beond 2

**Do you have mods installed? Does issue happen when no mods are installed?:**
it only shows 2 skill's and not the once i want and im not able to change how many are showen beond 2

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11891
