### ISSUE TITLE
USER ISSUE: Elevator Broken

### ISSUE THREAD

**Issue by TOTRanger** [StrangeLoopGames/EcoIssues#11870]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
use the elevator

**Expected behavior:**
you should be able to ride the elevator

**Actual behavior:**
you fall trough the floor of the leevator cart

**Do you have mods installed? Does issue happen when no mods are installed?:**
you fall trough the floor of the leevator cart

**Comment by SeanAtr0n** [comment]
Any other details you can give? This doesn't happen all of the time

**Comment by TOTRanger** [comment]
wood carts can use the elevator but player's can not we just testet 3 players and 2 re logs just in case

**Comment by SeanAtr0n** [comment]
hmm, looks like the fix for this isn't in the release build

**Comment by TOTRanger** [comment]
Anything we can do to help?

**Comment by ojemineh** [comment]
happens (everytime) in 0.8.0.7 too
see video
https://youtu.be/b1rPJ0RSgmY

**Comment by SeanAtr0n** [comment]
looks like the root cause is exceptions from https://github.com/StrangeLoopGames/EcoIssues/issues/11866

a prefab was somehow modified during the build process, @BlazeGuy2 is looking into it

**Comment by TOTRanger** [comment]
yeah its been working all day with no problems until tonight after the update

**Comment by SlayksWood** [comment]
If I use new preview-release client it works.

**Comment by D3nnis3n** [comment]
Fixed in release_preview, presumably via PR#4205
