### ISSUE TITLE
Butchery Table Bug/Issue

### ISSUE THREAD

**Issue by NiveusT** [StrangeLoopGames/EcoIssues#11878]
After today's update, it seems like the butchery table is having some issues for my game.

Normally, with level 7 butchery, you have one carcass, and you can put 5x the materials in the butchery table quantity that you craft, and you'd get 5x1 carcass in resources. I put a 5 carcass job up, and it says I'm missing carcasses, takes my carcass, and gives me barely any of the resources that I've asked for.

It's as if the 5 isn't actually how many I can get from it. It's 4 but the number is different.
Or maybe 3, I didn't calculate LOL, but the butchery table still gives the impression it's 5
Since 5 is where the quantity of used carcasses goes up to 2

Another issue: 

Seems like our calories for working have gone back up as well. So, it's as if our current skills are not working properly. Originally, we were getting something like 1.5? Calories lost for mining?

Now it's back up to 7+ with an iron axe. Mining level 7.

We have replaced the config files and updated everything.

So it seems like something isn't registering the skills that we have put in.

Other skills, however, seem to be fine, such as smelting.

**Comment by SlayksWood** [comment]
I did not quite understand what was meant. 
But I started checking and found that talent at level 6 doesn't work.

7 lvl butchery without talent Lavish Workspace: Butchery
![image](https://user-images.githubusercontent.com/45708377/55619953-6b6af180-57a2-11e9-8b97-fcc38a65c972.png)
If I take talent Lavish Workspace: Butchery I can't do anymore
![image](https://user-images.githubusercontent.com/45708377/55620131-cb619800-57a2-11e9-94b0-96b5ce130474.png)

**Comment by SlayksWood** [comment]
also talent don't add average toom tier by 0,2

**Comment by NiveusT** [comment]
I'm not sure how else to explain properly, and I don't have any more carcasses to take pictures with, but I'll try to get some pictures when I can.

Basically, I'm level 7 butchery. At level 7 butchery, originally, each carcass butchered gives 5x the amount of resources. (For example, 1 hare gives 5 meat at level 7 butchery, instead of just 1 single meat.)

Currently my level 7 butchery now gives me about 2.5-3x the amount of resources, not the original 5x. (For example, 1 hare gives 2 meat, instead of 5 like level 7 normally does). And it takes the carcass.

HOWEVER, in the butchery table... It *says* that I will get 5x the amount, but only gives me half of that.

Does this make more sense?

I apologize if not, my English isn't so great.
