### ISSUE TITLE
[0.8.1] Vehicles can`t move in a case

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11886]
[0.8.1]
no mods

Exca won`t move if fuel was put in storage first.

**Steps to reproduce**
1. Put fuel in excavator's storage
2. Drive
3. Drag and drop fuel from storage to fule supply
4. Try to move

**Expected result**
Excavator shoul move

**Actual result**
You can work with hand, but you can`t move excavator.

Everything will be fine after reuse excavator.

![bandicam 2019-04-05 16-28-02-510](https://user-images.githubusercontent.com/27898520/55625302-c6601100-57c1-11e9-9d3a-52aa224713ec.jpg)
![bandicam 2019-04-05 16-28-29-134](https://user-images.githubusercontent.com/27898520/55625341-e5f73980-57c1-11e9-83ad-66190201ff68.jpg)
![bandicam 2019-04-05 16-28-34-867](https://user-images.githubusercontent.com/27898520/55625344-e7c0fd00-57c1-11e9-893d-75ef3463b9cb.jpg)

**Comment by SlayksWood** [comment]
8.2.0 staging-15-d: It appears again
