### ISSUE TITLE
Vehicle UI

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#11881]
Originaly posted here https://github.com/StrangeLoopGames/EcoIssues/issues/11772
Just separated that part of issue.

The vehicle control UI is confusing:
![image](https://user-images.githubusercontent.com/3536496/55103455-afb11000-5085-11e9-878f-659eba70471d.png)

Change this to instead have two options on excavator, Dig and Drive, and you have a radio button to choose between the two. Dont use the standard icons, make a new interface for this.

**Comment by johnkslg** [comment]
Have hot keys that change it too
