### ISSUE TITLE
[0.8.1.0] Chainsaw has sound trouble.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11885]
1. Sometimes when using a chainsaw she lost sound.
https://drive.google.com/file/d/1EdF3QFIbqWemA0HeCd5WV7nArDV02brE/view?usp=sharing

2. Players don't hear the sound of someone else's chainsaw.
3. From #10206 : "Please make chainsaw sound quieter. 1\2 for me."

**Comment by beastyn** [comment]
1. Still here
3. Still here
@SlayksWood 
need to check 2.
https://drive.google.com/file/d/1hrGMSz8_4tbhkQPSMvKnU5IQ6JUIPVGP/view?usp=sharing

**Comment by SlayksWood** [comment]
Now when you start to cut tree chainsaw sound disappears.
He is still very loud.

**Comment by SlayksWood** [comment]
"Players don't hear the sound of someone else's chainsaw" didn't fixed. It will be added in separate issue.
