### ISSUE TITLE
[0.8.1.0] Elk and Bison Mount should take up more space.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11887]
I think bison mount shold be 2x2x1. Now it takes 2x1x1
![image](https://user-images.githubusercontent.com/45708377/55625515-b6403580-57b1-11e9-8a66-008b9462892f.png)
It is much harder with elk mount. Now it takes 3x1x1. But actually the Elk Mount takes 3x3x2. But size (3x3x2)(may be 3x3x1) it's very much for this
![image](https://user-images.githubusercontent.com/45708377/55625847-99583200-57b2-11e9-865b-e3fc39b88af0.png)
![image](https://user-images.githubusercontent.com/45708377/55625929-d15f7500-57b2-11e9-8365-062deb671772.png)

**Comment by keegan-o** [comment]
Fixed in staging.
