### ISSUE TITLE
USER ISSUE: Cannot Create Singleplayer World in Latest version

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#11894]
**Version:** 0.8.1.0 beta

Have tried over 5 Times to Create **New World** keep getting this Error
![snap4293](https://user-images.githubusercontent.com/29383891/55652283-f66bdc00-57e2-11e9-8b96-839923e32dd5.png)

Have tried Various ways, Meteor on/off and Random/seed Still Giving Error Window
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2018.3.11f1 (5063218e4ab8)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 980 (ID=0x13c0)
    Vendor:   
    VRAM:     4053 MB
    Driver:   25.21.14.1967
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.475466 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 85541.
Total: 172.427428 ms (FindLiveObjects: 7.093503 ms CreateObjectMapping: 6.301145 ms MarkObjects: 158.893449 ms  DeleteObjects: 0.139073 ms)

**Comment by Conchipedia** [comment]
it looks like it is possibly making The Worlds (as the names come up in the **load** option)

**Comment by Conchipedia** [comment]
**the names i tried are:-**
April 2019
Name
Testing Build
and here are THOSE files 
[April 2019.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3049388/April.2019.zip)
[Name.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3049389/Name.zip)
[Testing Build.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3049390/Testing.Build.zip)

NOTE: it is ONLY creating a .eco file and no .db file for the World (not sure if this makes any difference to why they won;t load)

What i see in Task Manager when trying to load a world
![snap4295](https://user-images.githubusercontent.com/29383891/55652870-b279d680-57e4-11e9-85fa-3de2ef1402e5.png)
then what i see after i get the Error
![snap4296](https://user-images.githubusercontent.com/29383891/55652877-bc9bd500-57e4-11e9-967b-c353301eee52.png)
so it **IS** loading the Server.exe when trying to load the world

for a second i do see another program being loaded
**Visual c# Command Line Compiler**
![snap4297](https://user-images.githubusercontent.com/29383891/55653040-2e741e80-57e5-11e9-8369-b49bd89db884.png)

**Comment by redwyre** [comment]
@Conchipedia can you upload the dump files in SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Dump?

**Comment by Conchipedia** [comment]
No folder called Dump (following Text file is a **FULL*** Directory Listing of ALL files in there
[Directory fo Eco in Steam.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3049454/Directory.fo.Eco.in.Steam.txt)
all i found are the Following Log Files:
[log_190405083056.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049462/log_190405083056.log)
[log_190405083406.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049463/log_190405083406.log)
[log_190405083451.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049464/log_190405083451.log)
[log_190405083530.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049465/log_190405083530.log)
[log_190405083804.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049466/log_190405083804.log)
[log_190405084234.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049468/log_190405084234.log)
[log_190405084312.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049469/log_190405084312.log)
[log_190405085101.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049470/log_190405085101.log)
[log_190405085332.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049471/log_190405085332.log)
[log_190405085359.log](https://github.com/StrangeLoopGames/EcoIssues/files/3049472/log_190405085359.log)
which All Show the **SAME ERROR** message in each time i attempted creating Singleplayer

**Comment by Conchipedia** [comment]
A Restart Of Windows Solved the problem for **NOT** allowing the file eco.mods.dll being written to 
**"C:\Users\USER\AppData\Local\Temp"**
