### ISSUE TITLE
Mint laws that reference mint action can cause lag

### ISSUE THREAD

**Issue by antimodes221** [StrangeLoopGames/EcoIssues#11896]
When creating a law that triggers on action count, a user who does not have a direct allow clause gets lagged off of the system when attempting to mint.

Example of the law and behaviour:
When attempting to Mint Coins where (currency is Rubble)
If (you are a Admin)
Then allow
Otherwise If (you are a World Leader)
Then allow
Otherwise If (your Mint Coins actions where (currency is Rubble) < 1,001)
Then allow
Otherwise prevent

If an admin or world leader attempts to mint, they do not have any issues.  If a user who is not either of those attempts to mint, they they will lag out (get the disconnect symbol). If its a stack or so they tend to recover in 20 seconds and be credited the funds.  When doing large stacks (the full 1000) the user tends to crash.  The funds then show up about an hour or so later.

Disabling the law caused the issue to go away.

For what its worth, I suspect that on each action it does a look up in the db for action count, and when you do 1000 of them at once it queues 1000 search queries up.  Might consider doing a sum and comparison  , then insert on the diff?

**Comment by mirasrael** [comment]
Supposed (implemented) solution
![image](https://user-images.githubusercontent.com/475445/55722168-23e89d80-5a0e-11e9-9a7f-5c998a2ed116.png)
