### ISSUE TITLE
Specialty display maxes at 4 specialties shown on the bottom left of the screen even when 10 is selected.

### ISSUE THREAD

**Issue by NaateeD** [StrangeLoopGames/EcoIssues#11891]
Specialty display maxes at 4 specialties shown on the bottom left of the screen even when 10 is selected. Used the gear and walked it up from 1 to 4 and it works fine, once hitting 5 the specialty doesn't show.
<img width="175" alt="Specialty Display Bug" src="https://user-images.githubusercontent.com/32089039/55635875-b7606b00-578f-11e9-9065-576342a583e3.png">

**Comment by NaateeD** [comment]
<img width="176" alt="Specialty Display Bug 2" src="https://user-images.githubusercontent.com/32089039/55636032-03abab00-5790-11e9-902d-0c7f2a3b7b9f.png">

**Comment by beastyn** [comment]
Which version do you use?
Was checked fot 0.8.1.0 and it worjs fine.

**Comment by NaateeD** [comment]
0.8.1.0 :( hehe

**Comment by beastyn** [comment]
Can you provide output_log file?

**Comment by NaateeD** [comment]
How do I do this, sorry :(

**Comment by beastyn** [comment]
My bad )
I should be there
%LocalAppData%Low\Strange Loop Games\Eco\output_log.txt

**Comment by beastyn** [comment]
And one more question, Did you migrate from 0.8.0.7?

**Comment by SlayksWood** [comment]
On the new server, everything works fine.
I went to the server that moved from 8.0.7. If you get experience for specialization then it is displayed in the list.

**Comment by johnkslg** [comment]
Thanks @NaateeD, this should be fixed on the new server.
