### ISSUE TITLE
USER ISSUE: Evelvator not working

### ISSUE THREAD

**Issue by Axedl** [StrangeLoopGames/EcoIssues#11901]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Place wooden elvevator, doesnt mater where as long as it is corectly palced
Use it

**Expected behavior:**
moved with the evelator

**Actual behavior:**
eveator moved down with cart on it, moving through me leaving me at the top. didnt work with other players ether

**Do you have mods installed? Does issue happen when no mods are installed?:**
eveator moved down with cart on it, moving through me leaving me at the top. didnt work with other players ether

**Comment by beastyn** [comment]
Duplicate of #11870. Issue fixed, on the way.
