### ISSUE TITLE
USER ISSUE: Invalid Login Info

### ISSUE THREAD

**Issue by jolbrown12** [StrangeLoopGames/EcoIssues#11906]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Hit Join Server and receive invalid login info

**Expected behavior:**
prompted me with a password box and then let me join

**Actual behavior:**
Invalid Login Information

**Do you have mods installed? Does issue happen when no mods are installed?:**
Connection Failed-Invalid Login Info

**Comment by beastyn** [comment]
Steam has issues. You should be able to log in with SLG copy.
