### ISSUE TITLE
USER ISSUE: Invalid Login Token

### ISSUE THREAD

**Issue by Royalogic** [StrangeLoopGames/EcoIssues#11907]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Attempt to log into server

**Expected behavior:**
Logged me into my server

**Actual behavior:**
Got invalid login - couldn't log in

**Do you have mods installed? Does issue happen when no mods are installed?:**
Got invalid login - couldn't log in

**Comment by beastyn** [comment]
Steam has issues. You should be able to log in with SLG copy.
