### ISSUE TITLE
USER ISSUE: Haus wird nicht erkannt

### ISSUE THREAD

**Issue by Cycrashy** [StrangeLoopGames/EcoIssues#11908]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Egal wie ich es baue, hab zur testzwecken jetzt eben noch mal ein 8x8 haus gebaut welches komplett quadratisch ist und alle ecken und kannten geschlossen sind ausser eine 2x1 tür denoch wird mein haus nicht als dieses erkannt und unten die nazeige fürs haus trotz vollständigem Haus passiert nichts, das haus ist auch im eigenen Gebiet gebaut...

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by D3nnis3n** [comment]
Steht denn auch ein Möbelstück drin?

**Comment by Cycrashy** [comment]
Achso es muss jetzt auch ein Möbelstück drinnen stehen?
Früher war das ja nicht so da wurde es erkannt sobald es fertig war
muss ich gleich mal ausprobieren ob es daran liegt ^^

**Comment by D3nnis3n** [comment]
Falls du meinst, dass es unten in der Housingleiste angezeigt werden soll, dann war da eigentlich schon immer ein Möbelstück für notwendig.

**Comment by D3nnis3n** [comment]
Screenshots wären vielleicht hilfreich, um zu verstehen, was du genau meinst.

**Comment by Cycrashy** [comment]
Achso es muss jetzt auch ein Möbelstück drinnen stehen?
Früher war das ja nicht so da wurde es erkannt sobald es fertig war
muss ich gleich mal ausprobieren ob es daran liegt ^^

**Comment by D3nnis3n** [comment]
Dann mach ich hier zu.
