### ISSUE TITLE
USER ISSUE: Screen settings ineffective

### ISSUE THREAD

**Issue by Mikerman50** [StrangeLoopGames/EcoIssues#11909]
**Version:** 0.8.1.0 beta staging-3ce3fe75-6

**Steps to Reproduce:**
Change the screen to windowed to a 800 x 600 applied and confirmed before time expired	

**Expected behavior:**
the current full screen game to resize into requested resolution	

**Actual behavior:**
had zero effect, for good measure let the confirmation timer expire and it went back to a random resolution not speccified by myself

**Do you have mods installed? Does issue happen when no mods are installed?:**
had zero effect, for good measure let the confirmation timer expire and it went back to a random resolution not speccified by myself

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/12067
