### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Dragonshold** [StrangeLoopGames/EcoIssues#11904]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Comment by beastyn** [comment]
Steam has login issues, if you use Steam you can have problem with connection.
