### ISSUE TITLE
USER ISSUE: Can't get on my Private World

### ISSUE THREAD

**Issue by DragonHalo99** [StrangeLoopGames/EcoIssues#11905]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Trying to load into my private world

**Expected behavior:**
getting on my private world

**Actual behavior:**
connection failed invalid log in info. this started after the game crashed when I tried putting a torch in a torch stand.

**Do you have mods installed? no Does issue happen when no mods are installed? yes:**
connection failed invalid log in info. this started after the game crashed when I tried putting a torch in a torch stand.

**Comment by beastyn** [comment]
Log in problem should be fixed. Tourch fix is on the way.
