### ISSUE TITLE
USER ISSUE: Login Error

### ISSUE THREAD

**Issue by vindekator** [StrangeLoopGames/EcoIssues#11916]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Start Client
Fill in user name and password
Click on Login button

**Expected behavior:**
Get logged in and client finishes loading.	

**Actual behavior:**
Failed to log in.  Unknown error

**Do you have mods installed? Does issue happen when no mods are installed?:**
Failed to log in.  Unknown error

**Comment by vindekator** [comment]
This is happening on a clean installation and on an existing one.  Two different machines.  So with and without mods.

**Comment by Nicolausi113** [comment]
Think this should be fixed now - see #11924
