### ISSUE TITLE
USER ISSUE: Orbital insertion

### ISSUE THREAD

**Issue by pwholmes** [StrangeLoopGames/EcoIssues#11917]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Mine some rocks while standing on them

**Expected behavior:**
Broken rocks

**Actual behavior:**
Being rocketed straight up so high that I could see the entire planet and then some.  Actually it was quite entertaining.  I wish I could reproduce this at will.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods.

**Comment by SlayksWood** [comment]
I have encountered such a issue. How to reproduce 100% hasn't yet found.

**Comment by SlayksWood** [comment]
most cases were fixed with #18805. I do not exclude that this can still happen but it is much less common
