### ISSUE TITLE
steam generator, combustion generator continuously working when there is no demand for power

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#11918]
It may be associated with either the refinery, pump jacks or sewage treatment but the steam generator and combustion engine will go on indefinitely with fuel even when there is no demand for power.

**Comment by faiith** [comment]
We have the same problem on our server. Initially, the generator is off, as soon as a consumer needs electricity it turns on. If the consumer is subsequently deactivated (or dismantled), the generator continues to run instead of switching off

**Comment by beastyn** [comment]
Well, even if generator is switched off it will still produce sewage. This is intended behaviour. If there is a waterflow there will be sewage.
Fuel consumption was checked. When there is no demand of power fuel consuming will be stopped.
If I get you wrong please reopen and correct me )
