### ISSUE TITLE
All Animals gone

### ISSUE THREAD

**Issue by PermanentEdding** [StrangeLoopGames/EcoIssues#11914]
I really dont know what happend but all animals are gone!
![image](https://user-images.githubusercontent.com/37971880/55683413-cd149280-593f-11e9-9816-8c184f0b6552.png)
Is there any solution? /noah  doesnt work at all... :(

**Comment by SlayksWood** [comment]
@PermanentEdding 
/spawnanimal Name, count
Do you still not know why it happened?

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide your save file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
