### ISSUE TITLE
USER ISSUE: Verbindungs-Fehler

### ISSUE THREAD

**Issue by justvader05** [StrangeLoopGames/EcoIssues#11911]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
Kann mich nicht verbinden

**Expected behavior:**
Kann mich nicht verbinden

**Actual behavior:**
Kann mich nicht verbinden!!! :C

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by Nicolausi113** [comment]
Es scheint ein Problem mit dem SLG Auth-Server zu bestehen. Ich kann den Client auch nicht starten noch mit SLG-Account verbinden.

( Seems to be a problem with the Auth Server. Can’t start the client nor connect to SLG account.)

**Comment by Nicolausi113** [comment]
The Problem seems to be fixed yet!

**Comment by D3nnis3n** [comment]
Should be fixed.
