### ISSUE TITLE
USER ISSUE: gui problem

### ISSUE THREAD

**Issue by LisKitty** [StrangeLoopGames/EcoIssues#11913]
**Version:** 0.8.1.0 beta

**Steps to Reproduce:**
I was gonna cook something at the campfire, I realized i had a skill point so I instantly pressed Z, nothing showed up and all of the gui's disappeared.

**Expected behavior:**
showed me the skill point screen

**Actual behavior:**
it made every gui disappear

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by D3nnis3n** [comment]
You probably accidently hit alt-z, which disables the UI.

**Comment by D3nnis3n** [comment]
I'm closing this for now, report back if you can reproduce this issue and are sure to not have pressed Alt at the same time.
