### ISSUE TITLE
[0.8.1.0] Disorientation after leaving the excavator

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11919]
1. Checked the work of the excavator. 
2. went out of it (was a first person view). The camera was very low. 
3. Switched to 3 person view. I was lying on my back but could move. (move on the back)
4. I went back to the excavator, and when I got into it and went out again, everything was fine.
I can't repeat it.
https://drive.google.com/file/d/1BTLXhyXfYdyUnke_TaJqHgUWslTiILQS/view?usp=sharing

**Comment by SlayksWood** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3053406/output_log.txt)

**Comment by SlayksWood** [comment]
It happened again after I went out of the excavator.
 
https://drive.google.com/file/d/15K3YgMLdugqMlG41JeU6YpyRu6umErHH/view?usp=sharing

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3069088/output_log.txt)

**Comment by SlayksWood** [comment]
8.2.0 staging-3
It happened again. And again with an excavator. I think the problem is in excavator.

**Comment by SlayksWood** [comment]
Step to reproduce:
- /fly
- use excavator.
- start to move (W or S), your camera should be 
![image](https://user-images.githubusercontent.com/45708377/57706655-dbf11200-766e-11e9-8cc5-57b1dd13245b.png)
or 
![image](https://user-images.githubusercontent.com/45708377/57706798-1b1f6300-766f-11e9-9b59-a567bd308373.png)
 - left excavator
I'm not sure that the bug exists without using /fly

**Comment by SlayksWood** [comment]
Sometimes when leaving the Excavator, a situation arises that you cannot overcome the height of 2 blocks. I think this is related to this issue. 
This problem appears if I jumped into the excavator on the go: you run to the excavator and jump up and press E.
See video: https://drive.google.com/file/d/1s558XBr-j7_EmJmUxiUJxFjOt-3Fa9Xt/view?usp=sharing
People also complain about It happens with carts. But so far I have not managed to reproduce it with cart.

**Comment by redwyre** [comment]
You can't climb 2 blocks if you don't have any calories available

**Comment by mirasrael** [comment]
@SlayksWood you was right about 2 blocks issue. It happens when player slightly rotated around axis, so instead of vertical jump it has diagonal jump.
