### ISSUE TITLE
garaj

### ISSUE THREAD

**Issue by KlaSSiKa0** [StrangeLoopGames/EcoIssues#11912]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to login

Unable to complete SSL connection
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Failed to login

Unable to complete SSL connection
```

**Comment by KlaSSiKa0** [comment]
ghgfhgfhfghfg

**Comment by D3nnis3n** [comment]
Should be fixed.
