### ISSUE TITLE
USER ISSUE: Unable to complete SSL connexion

### ISSUE THREAD

**Issue by Nyl000** [StrangeLoopGames/EcoIssues#11910]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**
try to log in

**Expected behavior:**
log me in..

**Actual behavior:**
The following error message popped up:
```
Unable to complete SSL connexion
Failed to login

Unable to complete SSL connection
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Unable to complete SSL connexion
Failed to login

Unable to complete SSL connection
```

**Comment by D3nnis3n** [comment]
Should be fixed.
