### ISSUE TITLE
[0.8.1.0]  Excavator is rock in digging mode

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11922]
While the excavator is in digging mode, it can't be moved. Even if you dig under it (if a person is sitting in it in a digging mode), it will hang in the air. 
Also, if you move at high speed and press on the digging mode, the excavator will immediately stop.
![image](https://user-images.githubusercontent.com/45708377/55725619-bb51ee80-5a16-11e9-9dd4-64318f5781f3.png)

**Comment by mirasrael** [comment]
Need to re-check on 8.2 (master). During my testing it falls into the caves.

**Comment by SlayksWood** [comment]
Still an issue 8.2.0 staging-3
![image](https://user-images.githubusercontent.com/45708377/57226121-e5e39700-7016-11e9-8207-559704081e87.png)

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/4710
