### ISSUE TITLE
Auth. Server down again? Can’t login

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#11924]
Can’t start game nor login to my SLG account

**Comment by eyvalon** [comment]
I can start the game but I can not log in! (but I can log on to the strangeloop website)

**Comment by mirasrael** [comment]
Should work now. I identified the problem, it happens when auth server can't determine your IP address.

**Comment by Nicolausi113** [comment]
Sorry, can no fully confirm. The client runs and login works, but I can not login to my SLG account. If I click ACCOUNT on SLG site, nothing happens!

**Comment by mirasrael** [comment]
@Nicolausi113 can you write me in Discord (can find in official Discord channel as mirasrael)? Want to check your account, but don't want to make this info public.

**Comment by mirasrael** [comment]
Fixed AuthServer to correctly determine users Remote IP. In next version error message also will be more descriptive (it will contain information if your account blocked or disabled instead of saying Invalid login or password if you used valid credentials).

**Comment by Nicolausi113** [comment]
@eyvalon – do you still encounter problems on this matter?
For me the game runs but still having strange problems with SLG site, button ACCOUNT and BYE ECO doesn't work as supposed.

**Comment by Nicolausi113** [comment]
Oh – now it looks good – all OK

**Comment by beastyn** [comment]
Great!

**Comment by eyvalon** [comment]
@Nicolausi113 - no, everything works fine again :)
