### ISSUE TITLE
Elevator can't be used

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11935]
Buttons are not highlighting when hovering on them.

**Comment by D3nnis3n** [comment]
Elevators also seem to have issues to be placed on holes, it's not wanting to place for some people. But with /testelevators the behaviour is that the buttons are not targettable.

**Comment by D3nnis3n** [comment]
![elevator](https://user-images.githubusercontent.com/25908592/55831812-4b299280-5b14-11e9-9337-9e908157e944.png)

**Comment by Quadbro** [comment]
not reproducable in editor, trying latest build now

**Comment by Quadbro** [comment]
8.1.1 steam => not reproduced

**Comment by D3nnis3n** [comment]
Can still reproduce with /testelevator 

Those weird issues make me angry.

**Comment by D3nnis3n** [comment]
@beastyn Try to reproduce and if you cant, close.

**Comment by SlayksWood** [comment]
Can't reproduce, so close.
Buttons work both on the elevator and separately
