### ISSUE TITLE
Need a 'Host your Own World' button in the main menu

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11936]
- This button should take the user to the signup page for hosted worlds, where it explains what a hosted world is, how citizen accounts work, and link to subscribe, on single page.
- If the user already has a hosted world, the link should say 'Hosted World Management'
- If the user has a steam account only, it should allow them to get to signup before asking them to link their steam account to a new SLG account.
- To start, we can only show this to dev-tier and above, and then later unlock for everyone.

**Comment by johnkslg** [comment]
Mockup of hosted worlds landing page: https://1drv.ms/w/s!AnNPKT4C9Ig9j2e5A9AAT_CGOS1o

**Comment by rainfarmer** [comment]
we already have these features. will update sales page from design specs

**Comment by johnkslg** [comment]
You dont have the in-game button.

**Comment by mirasrael** [comment]
User eligible for HW, but without HW:
![image](https://user-images.githubusercontent.com/475445/56203651-54ec5200-604e-11e9-9af9-1d47c4e0d17d.png)

User with HW:
![image](https://user-images.githubusercontent.com/475445/56203979-0ab7a080-604f-11e9-9db8-f474631dac10.png)

**Comment by johnkslg** [comment]
⚡️ !
