### ISSUE TITLE
Entering World takes ages at the first login after server restart

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#11938]
Since 0.8.0 we are facing the issue with a very long wait time at "Entering World". The time is escalating and takes longer and longer by the time the server is running.

What we have figured out is, that the "Entering World" takes very long only after the server was restarted and than for the first time to login. Once i have waited up to 15min. and i successfully logged in, any further login is quite quick till the time the server gets restarted the next time.

Unfortunatly this issue occures not for all players. 20 of 30 users are facing these issue on our server. the other do not have any issue. We tried to figure out, what is the different between these users to the one which have the issue. We were not able to find any pattern on HW, Operating System, Network Interface, Internet Providers or any which could help us comming down to the root cause.

Next step i did i used wireshark to sniffer, what is happening between the client and the server, which could help to find the root cause. I have attached two wireshark logs to this issue. One with successfully login within normal time and an other one with very long wait time. In the last one i have marked the package by the time the "Entering World" started and the Package once the loading world percentage is going to start. What you can see in these log is, that during these time, the client and the server is ping pong very small packages. Even i cannot view into the packages, i have the impression, the client is asking the server for data, but the server answers with incomplete packages. Once the download starts, you can see, the client is still requesting the same packages with only different, that the server is sending full packages.

I hope these logs and analysis results helps you to find the root cause of that issue. The issue is frustrating our users to wait such long time. 

https://1drv.ms/u/s!AqAvy5MYOuASwQoMwZ2j3ZU65ICp

**Comment by FalkosTMB** [comment]
On my system the long waiting could be at any time. But sometimes it conects in seconds.

**Comment by mirasrael** [comment]
Hi @Alteraner Thanks for report! Can you ask server admin to take a process dump when you're hanging on Entering World? Seems like the server just prepares data for you client and it takes very long time to complete, may be it locked by another processes. So process dump may help to understand what is going on the server side.

**Comment by mirasrael** [comment]
Also please ask for the server save and db file and attach them to this issue.

**Comment by Sekor2600** [comment]
@mirasrael  With Save & Db can i Help ;D   https://drive.google.com/drive/folders/1qSp54Ft8SKpLQLQO1FFB1bkSbHvaZ8gG?usp=sharing

**Comment by mirasrael** [comment]
@Sekor2600 cool, thanks!

**Comment by mirasrael** [comment]
oh, man, you db file is 5Gb :) It may describe this

**Comment by Sekor2600** [comment]
Yes, the size has really grown after some time. But have tried to turn off the stats and still the problem.

**Comment by mirasrael** [comment]
@Sekor2600 both reads and writes? Did you try to move db file out of Storage dir?

**Comment by Sekor2600** [comment]
both yes and delete the Stats.
Seems like this sometimes ;D 
![image](https://user-images.githubusercontent.com/37456949/55880702-9342c680-5ba1-11e9-9da3-aadf7683cf53.png)

**Comment by mirasrael** [comment]
What is your server id? Wanna try to join and see how it will work for me :)

**Comment by Sekor2600** [comment]
Server IP: 5.104.107.124:14001

**Comment by mirasrael** [comment]
With great help from @Sekor2600 and @Alteraner was able to identify and fix the issue. Thanks guys! 
In case if you don't want to wait until 8.1.2 hot-fix will be released there are custom build for 8.1.1
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3064755/EcoServer.zip)

**Comment by johnkslg** [comment]
@Alteraner and @FalkosTMB Thanks so much for this report and sending your world files! We squashed an important bug with your help. Much appreciated.

**Comment by D3nnis3n** [comment]
Thank you two, especially Alteran from Ecostasia, we already had a lot of work together.

**Comment by mirasrael** [comment]
Wait a bit and you will see whole team thanking you :-D

**Comment by mirasrael** [comment]
@Alteraner fix **wasn't included** in 0.8.1.2

**Comment by Sekor2600** [comment]
@mirasrael yes have read nothing in the patch notes about fix. and did see that fix is not merged .
no problem ;D
