### ISSUE TITLE
Master 8.2 Can't use tent when pressing e inside

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#11940]
![image](https://user-images.githubusercontent.com/35509188/55841401-d6d6fb00-5ae3-11e9-9b28-188c0f04172b.png)

**Comment by BlazeGuy2** [comment]
Probably due to making bed usable inside tent

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/56278912-53478a80-6131-11e9-91d4-11f1a8d877b5.png)
8.2 master, can interact from anywhere in an angle

**Comment by Quadbro** [comment]
but if you are talking on interactiing when you do not looking at smth - that's imposible(
