### ISSUE TITLE
Incorrect required item amounts 

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#11948]
The original post was here and yes it is continues to occur. Yesterday it was substrate today it was butchering table and bison and clay missing from kiln for shale bricks. I can only guess this is an issue with the new skill system and the required items need for a recipe. Again it at first says i have required materials then when crafting says i need one more of this item.

https://github.com/StrangeLoopGames/EcoIssues/issues/11509

version .8.1.1

**Comment by D3nnis3n** [comment]
Closed, reopened old issue.
