### ISSUE TITLE
Ansel crap showing up in release

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11941]
![image](https://user-images.githubusercontent.com/3536496/55841518-5369d980-5ae4-11e9-9dba-1f7f55f294e0.png)
Remove plz

**Comment by keegan-o** [comment]
That's the entire point, is for players to be able to use it! I just tested it and it works in master preview, allows people to get awesome super res screenshots etc. There may be a way to remove this notification, but it would be at the cost of people who know about ansel knowing they can use it in Eco.

**Comment by D3nnis3n** [comment]
I have no Problem with that notification. It only shows when you have NVIDIA experience, no?

**Comment by SeanAtr0n** [comment]
I found an alternative tool that lets us get these pictures in editor, will install that and remove ansel

**Comment by johnkslg** [comment]
Just dont like the notice, spoils the load-game experience ;) Ansel itself sounds cool.

**Comment by keegan-o** [comment]
BOOOOOOOOOO, this means no games photography people making cool content and sharing it about Eco-- people like that feature a lot and some games journalists and artists specialize in using it.  Can we consider one last time just including this? If that notification is the only thing... I mean, that's not even in the game, it's in the drivers of people playing the game. I agree it's kind of annoying, but for me it also pops up on most every other game I play too, and then never appears again. Obviously we want in-editor stuff, but in build is ultimately just as useful to have, for when we are actually playing built versions of the game etc.

**Comment by D3nnis3n** [comment]
I actually agree with keegan. This pretty much was implemented after my request for high-res screenshots. Is there no way to disable the Ansel popup?

**Comment by SeanAtr0n** [comment]
If you aren't running geforce 'experience' then you get this popup and Ansel works bug has crappy performance.

If you have geforce experience installed you don't seem to get the popup but also Ansel doesn't work because Nvidia distributes some sort of whitelist of officially approved games. I'm not sure how to get on that list, it will probably require a non-trivial amount of work/communication.

**Comment by D3nnis3n** [comment]
I actually have GeForce Experience installed and get the notice.
