### ISSUE TITLE
USER ISSUE: Excavator Can't be Picked Up

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#11944]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1.Try to pick up excavator.

**Expected behavior:**
It should have worked like it did in last patch.

**Actual behavior:**
It says theres not enough room in destination inventory even though i have emptied every single item from my inventory and hotbar.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods

**Comment by D3nnis3n** [comment]
The excavator actually is too heard to carry without backpack or self improvement Benefits. And those were nerfed a bit it seems.

**Comment by Blanclour** [comment]
Was wearing bearpack and had level 7 self improvement with no items on me except the hammer to pick it up and it still didn't work.

**Comment by D3nnis3n** [comment]
Can you Show a Screenshot of your weight limit? Hoher over the best on the right bottom side on the screen.

**Comment by Blanclour** [comment]
![20190410010534_1](https://user-images.githubusercontent.com/2582909/55855420-1c6be600-5b2d-11e9-993b-62a943fb1bd0.jpg)
![20190410010542_1](https://user-images.githubusercontent.com/2582909/55855421-1c6be600-5b2d-11e9-9281-a00bcb791359.jpg)
![20190410010552_1](https://user-images.githubusercontent.com/2582909/55855422-1c6be600-5b2d-11e9-8b46-7bc94282b6e6.jpg)

**Comment by Blanclour** [comment]
In fact it says the excavator is only 30kg in description, and I have 47.5kg.

**Comment by D3nnis3n** [comment]
Is there fuel in it that you cant carry?

**Comment by D3nnis3n** [comment]
Or anything else in its inventory?

**Comment by D3nnis3n** [comment]
You can only pick it up if its empty.

**Comment by Blanclour** [comment]
The bucket indeed had stuff in it, perhaps a more specific error description stating that the bucket is not empty would help avoid this in the future. I was able to pick it up afterwords. Thanks for the advice :)

**Comment by D3nnis3n** [comment]
Alright, great! Closed, as working as intended.
