### ISSUE TITLE
USER ISSUE: FOV Zoom-in

### ISSUE THREAD

**Issue by Villerger27** [StrangeLoopGames/EcoIssues#11947]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1. Replay the Meateor tutorial

**Expected behavior:**
It should have done nothing

**Actual behavior:**
Instead it zoomed in the FOV and won't zoom out

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by SlayksWood** [comment]
The problem occurs when a meteor is shot down. 
You want to watch the video. Go to Menu -> Tutorials -> The Meteor. After watching the video it zoomed in the FOV and won't zoom out.
https://drive.google.com/file/d/1yG0v4YM9E8HLGmcnQWjK2hpKcCO5T0wY/view?usp=sharing

**Comment by SlayksWood** [comment]
If there is no meteor then Tutorial "The meteor" anyway appears.

**Comment by johnkslg** [comment]
use chat commands to spawn/remove meteor
/help to see them in game
@danwheeler

**Comment by Villerger27** [comment]
There is a simple fix for this bug, which I should’ve probably put on here earlier. The (temporary) fix is to just restart the game.
