### ISSUE TITLE
Calorie bug or working as intended

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#11949]
version .8.1.1

I noticed our stomach has inc to a max of 5000 calories. However before hand when i used shovel pick axe etc it was below 7.5 calories. Now those tools are 7.5 calories per use and as you can imagine it depletes food rather quickly. If this is working as intended, please disregard.

**Comment by D3nnis3n** [comment]
Calorie consumption was increased and self improvement no longer give Benefits, so that is working as intended.
