### ISSUE TITLE
[8.1.1] Meteor tutorial improvement 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11957]
[8.1.1]
no mods

Its hard to make the meteor tutorial part.
**Steps**
1. Get a meteor task
2. Find meteor шn the sky

**Expected result**
watch a movie

**Actual result**
you need to make some wierd stuff like "head shaking" for a meteor to be find
https://drive.google.com/file/d/1sq72h4roF6fJLFKFxrWp--bgq-z-7Qb-/view?usp=sharing

It can be related to the wrong meteor position calculation (zoom-in misses the meteor) and to the issue StrangeLoopGames/EcoIssues#10978

**Comment by elfl0rd** [comment]
@SlayksWood metachronism is not a part of SLG, also this issue not have milestone :)

**Comment by SlayksWood** [comment]
> Camera didnt follow meteor.
> ![image](https://user-images.githubusercontent.com/3536496/63799947-f8cdf000-c8c1-11e9-8b0d-8b91d87c1e8b.png)
> 
> When the slideshow started, you could see the next frame behind the current frame.
> Text at bottom isnt centered and can go off screen.
> Fade box doesnt reach edges of screen in some resolutions.

**Comment by SlayksWood** [comment]
It's
