### ISSUE TITLE
[0.8.1.1]  Lock mouse click in UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11958]
1. Open Menu.
2. The "General" tab.
3. Open the list of languages.
![image](https://user-images.githubusercontent.com/45708377/55874926-6fc94d00-5b9c-11e9-8b52-61b3b28b1d45.png)
4. Press Escape.
5. You can no longer click in UI
6. Fixed by Alt+F4 only.
https://drive.google.com/file/d/1JWwll9YhxZBNn8b-AOnXxvMO7kdFH8uE/view?usp=sharing

**Comment by criptonauta** [comment]
Still happening in 8.1.3

**Comment by D3nnis3n** [comment]
Was merged to MASTER, despite being Critical.
