### ISSUE TITLE
USER ISSUE: Cant prevent craft tailings with law

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#11953]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1.Propose a new Law
2. When attempting craft where item is tailings
3. Condition if smelting > 0 allow otherwhise prevent

**Expected behavior:**
Nobody without to smelting skill should be able to start a iron/copper/gold bar project.

**Actual behavior:**
You get the message, that its not allowed but the craft starts no matter if you have smelting or not.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Yes but same happens in fresh vanilla install

**Comment by D3nnis3n** [comment]
This worked pre 8.0.

**Comment by johnkslg** [comment]
This ones pretty bad, worth looking at even though we're rewriting laws system.

**Comment by Quadbro** [comment]
you can't craft tailing without smelting skill  (by default) How did you be able to do it in vanilla?

**Comment by Quadbro** [comment]
if you do not have skill it treats it as 0 value

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/60147848-1f57a800-97f9-11e9-940c-153980d08a2e.png)
