### ISSUE TITLE
USER ISSUE: Can't cancel an order on the Research Table

### ISSUE THREAD

**Issue by David5788** [StrangeLoopGames/EcoIssues#11959]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1. The job in the Research Table cannot be deleted 
2. This is why i cant destroy the table

**Expected behavior:**
It should have deleted when i press the delete botton but its bugged	

**Actual behavior:**
Instead it of delete the job its stuck and cant be deleted even if i reconnect on my server 

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it of delete the job its stuck and cant be deleted even if i reconnect on my server

**Comment by SlayksWood** [comment]
Do you have a connected stockpile to the table? It should be possible to lay out items.

**Comment by D3nnis3n** [comment]
Issue closed due to no response. Feel free to reopen when it reoccurs and you can provide us with necessary information.
