### ISSUE TITLE
USER ISSUE: Speciality Laws not possible

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#11951]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1.Propose a new Law
2. Abandon Speciality/Learn Speciality

**Expected behavior:**
It should have "where speciality is" or at least the specialities under "skill is"

**Actual behavior:**
Instead it only has the professions like Carpenter, Engineer, ...

**Do you have mods installed? Does issue happen when no mods are installed?:**
Yes but its the same in new vanilla install

**Comment by D3nnis3n** [comment]
This also worked pre 8.0.

**Comment by Deantwo** [comment]
Will a law that prevent learning the Carpenter specialty prevent a player from learning Hewing though?

**Comment by johnkslg** [comment]
Will address with 9.0 laws

**Comment by Deantwo** [comment]
It would be a nice feature to have a `skill category is` where clause. So we can make laws that target all skills in a profession category.

PS: Also some confusion between the use of the word "skill" and "specialty" in this.

_Originally posted by @Deantwo in https://github.com/StrangeLoopGames/EcoIssues/issues/12955#issuecomment-524246585_

**Comment by SlayksWood** [comment]
new triggers for specializations in 0.9.0 have been added. Seems fixed. But so far everything has not been verified and everything has not been completed. If some problems will appears with this trigers, need to open new issues.
![image](https://user-images.githubusercontent.com/45708377/67390278-02fc2a00-f5a5-11e9-80e2-a1c779badd3d.png)
