### ISSUE TITLE
USER ISSUE: Sell/Buy Laws are buggy

### ISSUE THREAD

**Issue by hami88** [StrangeLoopGames/EcoIssues#11952]
**Version:** 0.8.1.1 beta

**Steps to Reproduce:**
1.Propose a new Law
2. When attempting to buy/sell on property X

**Expected behavior:**
Buy should not prevent selling and sell should not prevent buying

**Actual behavior:**
No matter what you choose, it always prevents buying and selling at a store (if thats how it should work please rename it and add the possibility for buying/selling laws)

**Do you have mods installed? Does issue happen when no mods are installed?:**
Yes but its the same on fresh vanilla install

**Comment by D3nnis3n** [comment]
Works as intended, see comments in this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9412

**Comment by D3nnis3n** [comment]
Well you know, i actually dislike this behaviour.

@johnkslg 
Let's actually give players the option to disallow selling buying separately for the store and the human.

**Comment by SlayksWood** [comment]
Seems added.
![image](https://user-images.githubusercontent.com/45708377/68663554-f76ea400-054f-11ea-9511-62eb2844dd83.png)
I can't buy, but I can sell.
![image](https://user-images.githubusercontent.com/45708377/68663445-b8405300-054f-11ea-9562-4d927d6c0869.png)
![image](https://user-images.githubusercontent.com/45708377/68663532-ecb40f00-054f-11ea-97a4-b35d8a79f43d.png)
