### ISSUE TITLE
[0.8.1.0] Elevator has no floor

### ISSUE THREAD

**Issue by faiith** [StrangeLoopGames/EcoIssues#11950]
Version: 0.8.1.0
Mods: None
Localization: German

Issue: Elevator has no floor / player is falling through floor

Videos:
https://www.youtube.com/watch?v=591kgVxDp_c&feature=youtu.be

https://www.youtube.com/watch?v=Y1s0uVx07m4&feature=youtu.be

**Comment by faiith** [comment]
Just checked again using 0.8.1.1, seems to be fixed in 0.8.1.1

**Comment by beastyn** [comment]
Yeap, indded, it was fixed. Thanks for observation )
Do you have any issues with elevator in 8.1.1?

**Comment by D3nnis3n** [comment]
Oh weil, when fixed, then close.
