### ISSUE TITLE
Incorrect docker server version

### ISSUE THREAD

**Issue by SnakeSolidNL** [StrangeLoopGames/EcoIssues#11955]
The latest docker container labeled (0.8.1.1-beta) is running server 0.8.1.0-beta (client reports incorrect version on connect).

![eco_server_incorrect_version](https://user-images.githubusercontent.com/38540031/55869175-4998b280-5b86-11e9-90f9-bb9debdc294b.JPG)

Edit: docker container labeled 0.8.1.2-beta is also running server 0.8.1.0-beta

**Comment by D3nnis3n** [comment]
Should be fixed with the newer versions, report back if it isn't.
