### ISSUE TITLE
Demographics don't show who is member of a demographic

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11967]
Copied from here: https://github.com/StrangeLoopGames/EcoIssues/issues/10058

**Comment by WeaselDog** [comment]
Looks good: 
![DemographicList](https://user-images.githubusercontent.com/47330823/70363075-db52df80-183b-11ea-82b5-e4d9c3838783.png)

**Comment by D3nnis3n** [comment]
Wonder how ist looking with 100+ users. Von: WeaselDogGesendet: Samstag, 7. Dezember 2019 00:20An: StrangeLoopGames/EcoIssuesCc: Dennis Scholz; AuthorBetreff: Re: [StrangeLoopGames/EcoIssues] Demographics don't show who is member of a demographic (#11967) Looks good:—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by WeaselDog** [comment]
Here is what it looks like with 400 users:

![DemographicListLarge](https://user-images.githubusercontent.com/47330823/70364591-f7597f80-1841-11ea-9ec1-a6a8580f92f5.png)


It is really easy to scroll up and down the list. Ideally the people who pass will be at the top, but right now it is just alphabetized

**Comment by WeaselDog** [comment]
To clarify on this one, the sort for the demographic should change before it is ready to close. There should be two sorts.

First sort people who passed the demographic check. (people who passed on top, people who failed at the bottom.
After that, sort the two groups to be alphabetized like it is now.

**Comment by johnkslg** [comment]
Sorting should be working, but change it to be foldouts
**X citizens passed**
