### ISSUE TITLE
Weird issues connecting to Stuffed Elk

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#11962]
Appearing as a different version when using Continue:
![image](https://user-images.githubusercontent.com/431728/55922650-81b2fa80-5c45-11e9-931c-35a10242fd10.png)

Version in your worlds:
![image](https://user-images.githubusercontent.com/431728/55922676-9ee7c900-5c45-11e9-9c7c-193a17a1bf8a.png)

But I now have another server called "Fran":
![image](https://user-images.githubusercontent.com/431728/55922774-07cf4100-5c46-11e9-9866-94af09feaac7.png)

**Comment by mirasrael** [comment]
Seems like Fran and Stuffed Elk shares same server id and password

**Comment by D3nnis3n** [comment]
Redwyre, hows the status?

**Comment by redwyre** [comment]
We generated a new server id, haven't seen it happen since
