### ISSUE TITLE
Creation of Districts and Demographics not possible in the law they are meant to be used in

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11966]
Copied from here: https://github.com/StrangeLoopGames/EcoIssues/issues/10112

**Comment by SlayksWood** [comment]
@johnkslg 
I think it will not be actual after the changes that are made in 0.9.0. or will you try to implement this?

**Comment by WeaselDog** [comment]
Has been added:
![ProposedDrafts](https://user-images.githubusercontent.com/47330823/69750078-bc986e80-1100-11ea-9ff1-99ed9ed94151.png)

Here is what happens to law containing proposed District passes when the District doesn't:
![DraftProposalFail](https://user-images.githubusercontent.com/47330823/69750198-097c4500-1101-11ea-9288-72bc8e2dbc72.png)

It is not possible to remake the district to make the law valid, but the law can easily be repealed if having an invalid law bothers people.
