### ISSUE TITLE
[0.8.1.1]  The ability to carry Dirt (or something like that) without a shovel

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11960]
1. Remove the shovel from the panel.
2. Take Dirt from the stockpile.
3. You carry dirt without a shovel.
![image](https://user-images.githubusercontent.com/45708377/55883443-06066e80-5baf-11e9-8ec6-a2bf44b956bc.png)

In my opinion a shovel should be. It shouldn't be possible to take Dirt from stockpile without a shovel.
![image](https://user-images.githubusercontent.com/45708377/55883308-c3dd2d00-5bae-11e9-95ca-098beb8cf6ea.png)

From issue #9176:
"Version: 0.7.6.3 beta
This Bug has crept back into the game again.
It's a shame that the Shovel is the ONLY tool that cannot be swapped while carrying anything."

In this issue, a person wants to carry dirt with hands without a shovel.
In any case, you need to decide how it should work.
I closed issue with a link to this.

**Comment by TwixterZ** [comment]
Tested on 9.4 develop 243 

Picking up dirt using a shovel now will cause game behave oddly (refer video below)
https://gyazo.com/d1fc3abbc2a55db0a758bc132b236f09
_Game went to select next non-shovel tool/space in the quickbar_ 

only when quickbar is filled with shovels it is working properly.
https://gyazo.com/39c40bbeec2f2a94f31750609d1dedec

**Comment by Quadbro** [comment]
Updated svn files, should be fixed now, probably was causing by pr accept order
