### ISSUE TITLE
Tooltips stuck on UI 5.5 alpha

### ISSUE THREAD

**Issue by Komogi** [StrangeLoopGames/EcoIssues#1196]
Occasionally when hovering a tooltip of any kind, the tooltip will stay on the UI, even after it's origin window has been closed. This has occured with multiple tool tips at the same time. Relogging does not get rid of it, and only reinstalling the game from fresh files will the tooltip disappear. 

Playing on Client, Windows OS.

**Comment by Komogi** [comment]
<img width="799" alt="tool tip ui bug" src="https://cloud.githubusercontent.com/assets/26584899/24176798/b0f0d5d6-0e74-11e7-91c3-f4b9d9f79262.png">

**Comment by MarjieAVolk** [comment]
Thanks for the information - I've been aware of this, but can't figure out the root cause.  Do you remember any more details of what you were doing when the tooltip got stuck?

**Comment by Komogi** [comment]
Hi MarjiAVolk,

I don't think I was doing anything else other than just hovering over the property claims while they were in my hotbar. Then the tooltip just stayed there. 
Some other times that I remember where the tooltip became stuck were looking through the tech tree and hovering over a skill, and hovering over the nutrition pie chart.

**Comment by Komogi** [comment]
<img width="797" alt="tool tip ui bug 2" src="https://cloud.githubusercontent.com/assets/26584899/24181584/2da7d422-0e92-11e7-93e4-1e5f05d85b2d.png">

Another example. Somehow this time relogging will cause it to go away, but the bug will still happen in the new session.

**Comment by Komogi** [comment]
<img width="797" alt="tool tip ui bug 2" src="https://cloud.githubusercontent.com/assets/26584899/24183373/5167e9d6-0e9e-11e7-8d29-ecdc527e925b.png">

Another example. However now upon relogging the tooltip disappears.

**Comment by noblackthunder** [comment]
Seeing allot more reports about this issues now

**Comment by noblackthunder** [comment]
Mail report from user : 

Hi!

Downloaded Eco 5.5 and tried it for some hours.. got some skill points and at the skill three i place the mouse pointer over woodworking, and the tooltip appear.. BUT.. It doesn't disipers.. what should i do? I logged out and logged in, and its still there.
Cant remove it??

![image](https://cloud.githubusercontent.com/assets/1668416/24198249/684be6f4-0f05-11e7-8762-268ea7458bf7.png)

**Comment by Komogi** [comment]
One possible solution that has been working (with a lot of success), was to shut down the game and to relaunch it. No idea why that is the case.

**Comment by daveSparhawk** [comment]
If it helps i first noticed this on "Staging 516ceabd", anyone see it on an earlier staging?
