### ISSUE TITLE
[0.8.1.2] Tallow Candle have same icon as Wall Candle

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11977]
Copied from here: #7066.
0.8.1.2 still an issue.
![image](https://user-images.githubusercontent.com/45708377/55954249-e0d53700-5c66-11e9-9219-38688c542449.png)

**Comment by keegan-o** [comment]
@RobertMangano We need a new icon for tallow candles without the mount part (tallow candle is just the candle alone).

**Comment by RobertMangano** [comment]
![candle](https://user-images.githubusercontent.com/26705633/84612903-555bd380-af05-11ea-8cb7-0a1e87dbf061.jpg)

candle, will add to icon sheet today

**Comment by RobertMangano** [comment]
tallow candle icon checked in
