### ISSUE TITLE
[0.8.1.2] UI issue with a lot of crafiting tables

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11973]
[0.8.1.2]
no mods

-Create a lot of public tables
-Open economy viewer - public crafting tables

**Expected result**
The list should be top lined
**Actual result**
The list move down

It appears only when a scroll is here with a lot of tables.
![bandicam 2019-04-11 12-40-45-381](https://user-images.githubusercontent.com/27898520/55939648-bb8cfc80-5c57-11e9-8f66-7420bb3ea9a8.jpg)

**Comment by SlayksWood** [comment]
same with contracts
![image](https://user-images.githubusercontent.com/45708377/56034624-78eb2300-5d30-11e9-897a-3290668a63db.png)
