### ISSUE TITLE
Cannot place fish trap underwater

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11971]
Copied from here: https://github.com/StrangeLoopGames/EcoIssues/issues/10849

**Comment by johnkslg** [comment]
@danwheeler
This is blocked by placement seeing the water block and disallowing it.  Youll need to a special flag to the item, can be stored in the item info, that lets the client know that its placeable in water, and probably check that on the server too.  Probably can go here:
![image](https://user-images.githubusercontent.com/3536496/56237448-dfc65000-6040-11e9-8406-548c81761cc7.png)
