### ISSUE TITLE
Can stuck in barrels

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11974]
Copied from here: #11515.
0.8.1.1 still an issue
![image](https://user-images.githubusercontent.com/45708377/55945914-571c6e00-5c54-11e9-97e6-be990a0016e0.png)
Unstuck helps very rarely.

**Comment by mirasrael** [comment]
On latest version /unstuck command moves you out of stockpile with barrels, but we can adjust barrel model to avoid dropping between barrels. Thoughts @keegan-o?

**Comment by keegan-o** [comment]
Sure thing, I can just expand the collider.
![image](https://user-images.githubusercontent.com/14983165/69103447-49b13880-0a1a-11ea-952d-9be6788848cb.png)

Fixed in staging for 9.0
