### ISSUE TITLE
[0.8.1.2] Skid Steer can't destroy wood pulp

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11975]
Copied from here: #11075.
0.8.1.2 still an issue.

**Comment by SeanAtr0n** [comment]
guess this was semi-intentional, at the time wood pulp was pretty useless so a way to destroy it easily was sort of a feature

**Comment by SlayksWood** [comment]
At 8.3.0 staging-1083 Skid Steer can't destroy wood pulp
