### ISSUE TITLE
[0.8.1.2] Fruit Salad has huckleberry icon

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11981]
Copied from here: StrangeLoopGames/EcoIssues#10903

0.8.1.2 still an issue.
![image](https://user-images.githubusercontent.com/45708377/55958547-99a07380-5c71-11e9-8f16-57cecd580cde.png)

**Comment by keegan-o** [comment]
Well, it's no longer huckleberries but it could still use improvement. @RobertMangano Do your best Fruit Salad for poor old FruitSaladIcon (or if you like, you could do a composite for it).

**Comment by RobertMangano** [comment]
![fruit salad](https://user-images.githubusercontent.com/26705633/84721574-53a51500-afc4-11ea-8f92-e56f66ad7681.jpg)
icon done will add to icon sheet soon

**Comment by RobertMangano** [comment]
fruit salad icon added
