### ISSUE TITLE
Frequent Server Crashes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11989]
> --BEGIN DUMP--
> Dump Time
> 04/12/2019 00:24:54
> 
> Exception
> Exception: ArgumentNullException
> Message:Der Wert darf nicht NULL sein.
> Parameter name: key
> Source:mscorlib
> 
> System.ArgumentNullException: Der Wert darf nicht NULL sein.
> Parameter name: key
>    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at Eco.Gameplay.Components.StoreComponent.CalculateStock(IEnumerable`1 stacks)
>    at Eco.Gameplay.Components.StoreComponent.UpdateStock(Boolean initializing)
>    at Eco.Gameplay.Components.StoreComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--
>

**Comment by mirasrael** [comment]
@D3nnis3n do you have it at server startup? Can you attach the save?

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/cycle-9.zip

The crash happens while the server is running and people playing. It actually happened 17 times this night when i was offline, that is in a timeframe of 8 hours at the time the least players are playing. This is critical.

**Comment by D3nnis3n** [comment]
I added some of the additional dumps to the save zip.

**Comment by D3nnis3n** [comment]
![issue](https://user-images.githubusercontent.com/25908592/56016079-728e8400-5cfb-11e9-9331-55e152225682.png)

**Comment by mirasrael** [comment]
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3072946/EcoServer.zip)
If you have same problem and can't wait for next hot-fix there are custom build for 8.1.2
