### ISSUE TITLE
Store stock: remove it in favor of storage?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1198]
Having two inventories on Stores - one for stock and one for regular storage - is confusing and has annoying consequences.  For example, right clicking on the store to place items into it will put them into the regular storage and not the store stock.

As far as I can tell, there is no reason for the store to have both, so I propose removing the store stock and just using the regular storage component as the store stock.

**Comment by johnkslg** [comment]
We will address this fully with the new stockpiles and shared inventories, and remove stores for that, so closing this for now.
