### ISSUE TITLE
Redwood (also Old Growth) - something wrong with yield potential 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11982]
Copied from here: #11286.

**Comment by craig-jong** [comment]
Should be fixed.

**Comment by SlayksWood** [comment]
Yield potential of all trees has white color.
![image](https://user-images.githubusercontent.com/45708377/57359138-9bc9f500-717f-11e9-9198-a06029294bd3.png)

**Comment by SlayksWood** [comment]
Yield potential of all trees has white color after this merge https://github.com/StrangeLoopGames/Eco/pull/4445
![image](https://user-images.githubusercontent.com/45708377/57830608-48792780-77bb-11e9-8451-9aa55802efe4.png)
![image](https://user-images.githubusercontent.com/45708377/57830618-50d16280-77bb-11e9-9892-348f15f8769e.png)
![image](https://user-images.githubusercontent.com/45708377/57830630-58910700-77bb-11e9-994f-35c10808b439.png)

**Comment by craig-jong** [comment]
This should have also been fixed this morning

**Comment by seccombew** [comment]
Fixed with Craig's PR 
https://github.com/StrangeLoopGames/Eco/pull/4465
