### ISSUE TITLE
GRAPHIC: Shadow regions too dark, especially during night

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#11983]
Version 8.1.0
Shadow quality FAST - daytime
![Schatten1](https://user-images.githubusercontent.com/38510829/55964698-74156900-5c75-11e9-8f36-483984244512.jpg)

Shadow quality FASTEST (off) – daytime
![Schatten2](https://user-images.githubusercontent.com/38510829/55964745-8abbc000-5c75-11e9-87e3-35af93881eaf.jpg)

Shadow quality FAST - nighttime
![Schatten4](https://user-images.githubusercontent.com/38510829/55964866-bdfe4f00-5c75-11e9-9df4-e22a25290e68.jpg)

Shadow quality FASTEST (off) – nighttime
![Schatten3](https://user-images.githubusercontent.com/38510829/55964914-d2dae280-5c75-11e9-8034-f5d4d3046de0.jpg)

my settings
![Settings](https://user-images.githubusercontent.com/38510829/55964964-edad5700-5c75-11e9-8a88-49f53a15b185.jpg)

**Comment by metachronism** [comment]
Your brightness value is set to 33%.  Default is 100%, and you can turn it up even higher which may be nescessary depending upon your specific display

**Comment by Nicolausi113** [comment]
here is one with brightness 100%, for me it looks a bit glaring during day and does not really brighten the shadows. 
![bright100%](https://user-images.githubusercontent.com/38510829/55984034-d6ce2b00-5c9c-11e9-95b0-0035f8e2e89f.jpg)
