### ISSUE TITLE
No "irreversibility warning" in specialization confirmation window

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#11984]
Copied from #11478.

> My comment there - #10285 is ignored.
> 
> > @craig-jong In this case, you need to add an irreversibility warning to the confirmation window.
> > Otherwise you receive ALOT of whimpers after update.
> 
> But as i see, "new" behavior, really confuse new and old players.
> ![default](https://user-images.githubusercontent.com/4980243/53321788-79e40480-38ea-11e9-9069-0787c366858c.png)
> 
> Especially those who have long played in Eco and used to the old behavior.
> In addition, the network has a lot of manuals dedicated to <0.8, which brings additional confusion.

> The dialog could look a lot better too.
> Have the skill's name be bold and colored, maybe even add the skill's icon on the dialog.
> That should help preventing accidentally picking the wrong skill.

**Comment by seccombew** [comment]
Not actually a bug, @craig-jong what do you think about this suggestion?

**Comment by D3nnis3n** [comment]
I only know what the players think. Nothing good. Easy change for a warning, should make it.

**Comment by johnkslg** [comment]
Yeah Craig should be a one-liner, check out the code for changing permissions in dual-permissions code, easy to do async confirms from user.  ping me if you need help finding it
