### ISSUE TITLE
Seeds dropped on the ground produced one garbage and one compost

### ISSUE THREAD

**Issue by Ramh5** [StrangeLoopGames/EcoIssues#11988]
According to the wiki I thought that green items cannot produce garbage.

**Comment by SlayksWood** [comment]
Seeds give only compost. Perhaps you threw something with the seeds that gave you garbage.
what version of the game are you using?

**Comment by D3nnis3n** [comment]
Closing this issue for missing information, feel free to open a new one when it reoccurs and you can give us more information.
