### ISSUE TITLE
[0.8.1.2] Sales tax is incorrectly displayed in the store.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11994]
1. When I buy the item tax is paid by the seller. But displayed as if I was paying the tax.
![image](https://user-images.githubusercontent.com/45708377/56020660-4df0d700-5d10-11e9-8a93-a94df32db0ce.png)
According to this data, I must pay the tax. However, when I buy in my account remains 879.19 TestClientDollars.
![image](https://user-images.githubusercontent.com/45708377/56020774-98725380-5d10-11e9-8f24-591fd25dca63.png)

904.69 - 879.19 = 25.5. This is the amount of TestClientDollarsthat is shown without tax.
I want to clarify that **everything works correctly**. I don't need to pay tax for buying of the item. 
**The tax in the picture should be 0.**

2. When I sell the item tax is paid by mine. But displayed as if buyer was paying the tax.
![image](https://user-images.githubusercontent.com/45708377/56021386-fa7f8880-5d11-11e9-984b-ddb301db9aed.png)
According to this data, I don't must to pay the tax. However, when I sell in my account remains 893.13 TestClientDollars.
![image](https://user-images.githubusercontent.com/45708377/56021501-3dd9f700-5d12-11e9-9ff1-f95c08dbfddb.png)
893.13 - 879.19 = 13.94. 
20.5 - 13.94 = 6.56.
I paid the tax in size of 6.56 (as displayed in chat).
I want to clarify that **everything works correctly**. I need to pay tax for sale of the item. 
**The tax in the picture should be 6.56.**

**Comment by Quadbro** [comment]
already fixed in 8.2
