### ISSUE TITLE
[0.8.1.2] Objectives UI needs update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11999]
[0.8.1.2]
no mods

If someone put contracts, objectives UI looks wierd. Especially if it is in a small scale.

In a small window you won't see objectives

![bandicam 2019-04-12 17-39-39-145](https://user-images.githubusercontent.com/27898520/56037945-0d15b400-5d4a-11e9-9c87-91a89a596b4f.jpg)

Actually there asre objectives

![bandicam 2019-04-12 17-39-51-458](https://user-images.githubusercontent.com/27898520/56037973-1f8fed80-5d4a-11e9-80e5-a4245f241c01.jpg)

**Comment by Gemji1990** [comment]
is it posible to add a horizontal scrollbar when there is text thats outside the window instead of this text squisch so the players see if there is something missing?
