### ISSUE TITLE
Credits Screen

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#11992]
Games have credits
Eco = game
Eco should have credits

**Comment by D3nnis3n** [comment]
That's impressive logic.

**Comment by redwyre** [comment]
I agree. Can my name have flashing lights?

**Comment by D3nnis3n** [comment]
Can my name be in it at all? That would be the second game in which credits i am, lol.

**Comment by D3nnis3n** [comment]
Where to show them? After meteor fall / destruction? XD

**Comment by WeaselDog** [comment]
It is a nice idea but many servers like to continue after the meteor and will not want their gameplay interrupted.

**Comment by elfl0rd** [comment]
How about an in-game memorial object (or something like that)? 
Ideally, it should be able to combine several objects into one (who wants - builds a single one, who wants a big one - builds several nearby).
The building should be expensive and accessible no sooner than the last third of the game, but at the same time the memorial built on the territory - should give the government a small bonus to the territory. 5 or so percent.
Ideally, I would like the credits to be "displayed" at the memorial without entering its interface, directly in the world (like on the signs).
![img-20171027162728-611](https://user-images.githubusercontent.com/4980243/82210894-923da600-9918-11ea-98a7-c662b5cfe88f.jpg)
