### ISSUE TITLE
Error when proposing law with a map

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1199]
When I submit a proposed law with a map, I get a [server error](https://gyazo.com/2ceb4847c572de97cba27d7fd1261944)

Submitting the proposed law sends this [query](https://gyazo.com/5c85649f1b227b3792328b88aa269366)

So I tried submitting a law with swagger. 
I copied the map parameters from the query above. [Like so](https://gyazo.com/fab377aaa20af82dae585c02a30e0260)

Swagger submits the law without error, but the law has no map data when [displaying](https://gyazo.com/596ea6fb01b6f860fa71e2e629063ef3).

**Comment by rainfarmer** [comment]
For testing, here is the map parameters:

{"layerSelected":"Terrain","frameNum":0,"timeStart":0,"timeEnd":146843.3399594656,"playSpeed":0.5,"currentTime":41021.63999999995,"flat":false,"pause":false,"camPos":{"x":0,"y":10599.99999860596,"z":2.7878004709795308}}

**Comment by MarjieAVolk** [comment]
Looks like the format of this is not right.  I can't remember how this used to be now >>  Where did this parameter json come from?

**Comment by MarjieAVolk** [comment]
This should work now, reopen if it still doesn't

**Comment by rainfarmer** [comment]
Pulled the newest version, still getting same error when submitting a law with map
https://gyazo.com/caa7e9971495cf93d6731035ff2048c7

**Comment by MarjieAVolk** [comment]
We tested this together and didn't see the error anymore
