### ISSUE TITLE
Other UIs Block the Chat Input UI

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#11990]
![image](https://user-images.githubusercontent.com/14983165/55997928-2565d000-5c71-11e9-8818-ddbbd70d4ad9.png)
This has always been super annoying as an admin trying to enter commands and having UIs pop up and then you can't see what you're typing-- I'm sure the same thing occurs for players trying to chat with UIs open-- you shouldn't have to move UIs around just to see what you're typing into chat.

**Comment by redwyre** [comment]
What actually makes this a real issue is that chat is used for feedback to the user, you might try to do something and get an error message that's hidden by the window.

**Comment by Quadbro** [comment]
how about sepparete notification-popups on the screen for game feedback stuff?)

**Comment by beastyn** [comment]
seems to be fixed

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/67567679-06bdb700-f733-11e9-8e69-4224f0253c32.png)
