### ISSUE TITLE
First Placed Stockpile and Campsite - Icons Haven't Removed

### ISSUE THREAD

**Issue by joeldowland** [StrangeLoopGames/EcoIssues#12009]
(Fix)  Move markers manually in map mode.  Select marker and select remove.  Not a bug.  

Day 1, Joined a Server.  Placed First Campsite and Stockpile.  This was in close proximity to another user but not within the boundaries of their owned property.  Removed campsite and stockpile and the placement ICONS did not remove.  They also did not apply to new location once placed.  Screenshot attached.  I did logout of the game.  Come back a day later, issue still persisted.  Left the game, came back a day later and issue still persists.   Thanks for reading.  
![Bugged Campsite - Stockpile](https://user-images.githubusercontent.com/44057424/56081918-64666380-5de0-11e9-8467-8daf8e85e6c6.png)

**Comment by Nicolausi113** [comment]
The two world markers are only generated once at first placement and are not removed automatically, must be done manually. This is since campsite is introduced, as I know, but may change

**Comment by joeldowland** [comment]
Thank you.
