### ISSUE TITLE
Logging VS Mining, Calorie Behaviour.

### ISSUE THREAD

**Issue by Ser-Geeves** [StrangeLoopGames/EcoIssues#12006]
I noticed this behaviour today on the server I play on:
Mining; For each swing 0 calories, Final swing: normal calorie cost.
Logging: Each swing costs calories.

Examples: 
Without logging, a palm tree takes ~7 hits, each costing calories, plus the stump removal costing another 7 hits and then the wood pulp.
Without mining, Gneiss cost 4 hits to clear, plus the large piece if you are unlucky. 

Question is: Is this intended behaviour? Or is this a bug or simply an oversight that needs re-balancing?

Additional information:
Public server, 8.1.2 patch, no mods.

**Comment by SlayksWood** [comment]
This is already fixed in master.
#11833
