### ISSUE TITLE
USER ISSUE

### ISSUE THREAD

**Issue by misha132432** [StrangeLoopGames/EcoIssues#12008]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by D3nnis3n** [comment]
Update to the most recent version and reopen if persists.
