### ISSUE TITLE
All shops despite my own show red in the economy viewer

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12001]
Despite i can buy at all of them just fine. I thought that feature was meant to tell me if i had access on the shops - i do. Still they're red. Sometimes, when i go near them, they suddenly become green. Weird.

![bug](https://user-images.githubusercontent.com/25908592/56067303-efad0e00-5d7a-11e9-9120-d7f9df6db85a.png)

**Comment by D3nnis3n** [comment]
Issue persists in 8.2.

**Comment by elfl0rd** [comment]
Maybe something broken, AfaIk this logic is "red - you cannot sell\buy on this store, green - can."
https://github.com/StrangeLoopGames/Eco/pull/3669

(If you own store - it red)

**Comment by SlayksWood** [comment]
> Currently - Store lists all goods for purchase / sale via mouse over and or in Y economy view window regardless of authorization to buy / sell items in it.
> 
> Expected behavior - If not authorized then don't list store listings in Y for individual that cannot buy from it to prevent someone to travel over and try to interact with a store that does not allow purchasing from other then X.

**Comment by elfl0rd** [comment]
>Showing the missing permission is probably the best way, considering you could still ask if you can get permission.

https://github.com/StrangeLoopGames/EcoIssues/issues/10098
