### ISSUE TITLE
USER ISSUE: New Game

### ISSUE THREAD

**Issue by Jaccob1** [StrangeLoopGames/EcoIssues#12002]
![ECO1](https://user-images.githubusercontent.com/4512731/56071602-91256700-5d5d-11e9-83fc-40d5b638c141.jpg)
![ECO2](https://user-images.githubusercontent.com/4512731/56071603-91256700-5d5d-11e9-9905-12554363fbae.jpg)
![ECO3](https://user-images.githubusercontent.com/4512731/56071604-91256700-5d5d-11e9-9ffb-fa95cd703326.jpg)
![ECO4](https://user-images.githubusercontent.com/4512731/56071605-91256700-5d5d-11e9-9a1e-1878dde0fce0.jpg)

**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
1. Create new game
2. Host private game
3. Click generate random

**Expected behavior:**
For it to load a generated world

**Actual behavior:**
It took about 30 seconds of "Connecting..." then it pops up with a error message and ask if i want to report a bug.

**Do you have mods installed? Does issue happen when no mods are installed?:**
It took about 30 seconds of "Connecting..." then it pops up with a error message and ask if i want to report a bug.

**Comment by beastyn** [comment]
@Jaccob1 Thank you for you report. Could you provide a server log file?
Here is an instruction https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by beastyn** [comment]
Well, I suppose this could be related to 32 bit issue. Should be fixed with next hotfix. Close for now, fill free to open if needed,
