### ISSUE TITLE
USER ISSUE: Server Verbindung timeout

### ISSUE THREAD

**Issue by kalvo11** [StrangeLoopGames/EcoIssues#12011]
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
Einfach auf Laden geklickt und Welt ausgewählt

**Expected behavior:**
Normalerweise sollte es einfach starten bzw. laden

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
Verbindung konnte nicht hergestellt werden. Zeitüberschreitung
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Die folgende Fehlermeldung trat auf:
Verbindung konnte nicht hergestellt werden. Zeitüberschreitung
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Comment by D3nnis3n** [comment]
Welche Größe hat die Welt?

**Comment by D3nnis3n** [comment]
Ich schließe den Issue, eröffne gerne einen neuen, sobald du uns weitere Informationen geben kannst.
