### ISSUE TITLE
8.1.2 Economy Viewer not displaying all items

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12018]
v8.1.2 beta

Problem: Economy viewer not filtering all items

Steps:

Press Y to go to E.V.
Search for Copper
Search for Wiring

Copper Wiring doesnt appear

There are others.

![image](https://user-images.githubusercontent.com/6478038/56089279-60792680-5e5e-11e9-8347-2e2efdbc24f9.png)

**Comment by Gemji1990** [comment]
cant confirm, i find copper wiring when i search wiring. it might be that items that are not craftable because of not researched skills are not shown.
this is only a theory on the server i play has the admin all skills learned.

**Comment by beastyn** [comment]
@criptonauta Did you discovered Mechanics?
You won`t see some items until some skills are researched.

**Comment by criptonauta** [comment]
> 
> 
> @criptonauta Did you discover Mechanics?
> You won`t see some items until some skills are researched.

Yup, I'm reaching Mech lvl 2 in some minutes now

![image](https://user-images.githubusercontent.com/6478038/56099643-9dd0c900-5edd-11e9-8f6e-2543a8b360cf.png)

**Comment by beastyn** [comment]
@criptonauta 
It seems that for this one you will also need Electronics Specialty. I will check if this is how is suppose to be.

**Comment by criptonauta** [comment]
Hi people

It shouldn't be needed to have the specialty to check items in economy viewer. If I was in server with a lot of players, the Economy Viewer would have the function to check which items are being traded for example, even if I don't have a given Skill Tree.

Or at least I first used it with that in mind: to check available items and their prices if being marketed in some store

If that is the case: items can't be seen until the skill tree is available -- could it be set to display all items, even if as togglable option?

**Comment by D3nnis3n** [comment]
SOMEONE on the server needs to have learned the scroll to discover the materials. Did someone have those discovered?

**Comment by beastyn** [comment]
Looks like a bug. Need review and fixing.

**Comment by criptonauta** [comment]
> 
> 
> SOMEONE on the server needs to have learned the scroll to discover the materials. Did someone have those discovered?

It makes sense, but even though, something is wrong. Pump Jack appears on the list, Copper Wiring does not and both are from Mechanics

![image](https://user-images.githubusercontent.com/6478038/56242517-79ecbf00-6066-11e9-97b3-f6fefb9f0c83.png)
![image](https://user-images.githubusercontent.com/6478038/56242702-d9e36580-6066-11e9-961e-081e9f086ae6.png)

Barrel does not appear on list - it's an Oil item, still not discovered by book/scroll

![image](https://user-images.githubusercontent.com/6478038/56242557-8e30bc00-6066-11e9-95de-9bb568825ae8.png)


![image](https://user-images.githubusercontent.com/6478038/56241647-693b4980-6064-11e9-9f23-9ca36aa3f0e1.png)

Mech Book discovered / scroll used
Electronics book not discovered/created
Assembly Line not created yet
Electric Machinist table not created yet

**Comment by criptonauta** [comment]
> 
> 
> @criptonauta
> It seems that for this one you will also need Electronics Specialty. I will check if this is how its suppose to be.

Although Copper Wiring is a Mechanics product, it's produced in an Industry Craft Table (Electric Machinist Table). Only when I got them, Ind book and EM table, Copper Wire became available.

I'm not sure if it was when reading the scroll or crafting the table though :/

**Comment by SlayksWood** [comment]
from #7185
> This is caused by the items not being invented yet. Iron Bar is not connected to Smelting while Copper Bar and Gold Bar are.
> Pre Smelting:
> ![NoSmelting](https://user-images.githubusercontent.com/47330823/68720476-33abff80-0564-11ea-95e5-0d8d7c520ab8.png)
> Post Smelting Discovery:
> ![WithSmelting](https://user-images.githubusercontent.com/47330823/68720488-3f97c180-0564-11ea-89f5-81e6b27d893a.png)
> 
> Framed Glass, Glass, & Steel also must be invented. For some reason Bricks & Lumber do not need to be researched first.



> This is caused by the items not being invented yet. Iron Bar is not connected to Smelting while Copper Bar and Gold Bar are.
> Pre Smelting:
> ![NoSmelting](https://user-images.githubusercontent.com/47330823/68720476-33abff80-0564-11ea-95e5-0d8d7c520ab8.png)
> Post Smelting Discovery:
> ![WithSmelting](https://user-images.githubusercontent.com/47330823/68720488-3f97c180-0564-11ea-89f5-81e6b27d893a.png)
> 
> Framed Glass, Glass, & Steel also must be invented. For some reason Bricks & Lumber do not need to be researched first.

**Comment by SlayksWood** [comment]
You can add item information in Ecopedia about its discovery.

**Comment by johnkslg** [comment]
There should be a 'show discovered' button in this dialog that shows them. @Hakuhonoo was recently working on that, any info?  Does it exist in 9.0? 

Ecopedia and tooltips do now display data.
I think everything is actually working properly now, can you verify @SlayksWood ?

**Comment by SlayksWood** [comment]
@johnkslg 
We will check later, after all changes.

**Comment by SlayksWood** [comment]
In any case "Show undiscovered" button  fixed this issue. Closed for now.
