### ISSUE TITLE
Earned 0 Credit when Buying Free

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12019]
When buying something that cost 0 (zero) currency/credit, the chat message will say that you "earned 0".

![image](https://user-images.githubusercontent.com/2676134/56091279-4fa3d180-5ead-11e9-911c-346e0f3d1b21.png)

This is likely an error from allowing negative prices in stores.
My guess:
```
if (price > 0)
    return "payed";
else
    return "earned";
```
Need a zero check in there to make it say "got for free" instead.

**Comment by redwyre** [comment]
Does that messed up bottom section have an issue too? :)

**Comment by Deantwo** [comment]
@redwyre, I hadn't actually noticed that, don't know why that is.
