### ISSUE TITLE
USER ISSUE: Unable to access graphs or laws

### ISSUE THREAD

**Issue by rebelscum16** [StrangeLoopGames/EcoIssues#12017]
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
1. Set up private world
2. Have Firefox as default browser
3. Click to open graphs or laws in browser

**Expected behavior:**
It should have opened the relevant pages in the browser.

**Actual behavior:**
Instead it opens up a page saying:
 "Unable to connect
Firefox can’t establish a connection to the server at 127.0.0.1:3001."

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed, freshly re-install of the game.

**Comment by beastyn** [comment]
@rebelscum16 
Thank you for your report.
Did you manage to solve the issue?
I suppose you have blocked port if FF.
Can you check it?
In FF opent the new tab
in adress put-  about:config
And try to find 3001
Will it find something?

**Comment by rebelscum16** [comment]
Haven't figured out a solution yet. In about:config in FF, searching for "3001" doesn't bring up any results.

**Comment by beastyn** [comment]
Did you try another browser?

**Comment by D3nnis3n** [comment]
What are your system specs? I've seen this issue happening when the system specs are too low for some reason.

**Comment by rebelscum16** [comment]
Didn't try another browser, but it appears to be funcitoning currently. I doubt my specs would've been an issue, I'm on an i7 3770 with a gtx 1070 and 16 GB ram. Perhaps a Windows or Firefox update helped to resolve it? Sorry for the lack of replies or useful info on the issue.
