### ISSUE TITLE
Compost is valid as type in Build Road Contract

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12012]
Version: 0.8.1.2

![image](https://user-images.githubusercontent.com/2676134/56084148-2d6b6e80-5e2f-11e9-9c3d-d299ac05df7d.png)

When making a **Build Road** contract I can select **Compost** as a possible road type.

**Comment by elfl0rd** [comment]
Still actual in 0.8.3 and in 0.9.
![20191109133851_1](https://user-images.githubusercontent.com/4980243/68542595-6799f000-03bf-11ea-988c-f9f06dda7df4.jpg)

Also what about adding sand there? E.g. if i want sand roadsides...

**Comment by SlayksWood** [comment]
Now only 3 types of ramps are available. Therefore, you can't build a road only from sand.  Fixed for now.
![image](https://user-images.githubusercontent.com/45708377/73053023-b839c900-3e97-11ea-88e3-c77d901c8063.png)
