### ISSUE TITLE
Human Drop Garbage Graphs Identical

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12013]
Version: 0.8.1.2

Selected different players, identical graph.
I assume that this is the graph for all "Drop Garbage" action done by everyone, rather than specific players like it was supposed to be.

![image](https://user-images.githubusercontent.com/2676134/56084719-690a3680-5e37-11e9-80c2-fe2c9471660e.png)

Link to election: http://95.216.39.195:3011/elections.html?election=29ffd1e063a844eb9e316b609d988c93

**Comment by mirasrael** [comment]
It shows incorrect graph data. Fixed in 8.2.
