### ISSUE TITLE
Unity crashed while in game (single player)

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12025]
v8.1.0
There was a short popup “Unity crashed ...” and then another asking for “Close Program”.
I copied output_log.txt from %appdata% to attach here:

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3077829/output_log.txt)

There was also a crash report generated containing 3 files (I saved the files).
If these files of interest, tell me please how to attach or upload the files, the crash.dmp has 206 KB.

![crash](https://user-images.githubusercontent.com/38510829/56098448-fcf40500-5f00-11e9-9073-5b640ed99787.jpg)

**Comment by D3nnis3n** [comment]
Put them in a zip and attach them here.

**Comment by Nicolausi113** [comment]
Okay – here is the hole folder as zip – I hope it worked.
[Crash_2019-04-14_192112498.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3077882/Crash_2019-04-14_192112498.zip)

**Comment by mirasrael** [comment]
@Nicolausi113 yes, seems like this issue related to memory and Unity. It may try to allocate extra memory, then didn't check it if was successful or not and try to access this memory and crash. We have some memory improvements for the client in 8.2, so hopefully client will use significantly less memory after that.

**Comment by mirasrael** [comment]
How often do you have this issue?

**Comment by Nicolausi113** [comment]
This was the first and only issue this kind since I try v8.1 a few days.

And yes, improving memory usage and performance will make many players happy :)

**Comment by mirasrael** [comment]
Thanks @Nicolausi113 
Closing it for now. Please keep us up-to-date after 8.2 release.
