### ISSUE TITLE
Two typos in description of Reinforced Concrete

### ISSUE THREAD

**Issue by Solly-W** [StrangeLoopGames/EcoIssues#12029]
There are two typos in the description of Reinforced Concrete:
"A **study** construction material poured around a **latice** of rebar."
![Screenshot of description](https://user-images.githubusercontent.com/37163416/56113720-071a1000-5fa2-11e9-9161-ac6f6536270e.png)

**Comment by SlayksWood** [comment]
"A sturdy construction material poured around a lattice of rebar."
