### ISSUE TITLE
mouseover infopanel often collapses

### ISSUE THREAD

**Issue by Gemji1990** [StrangeLoopGames/EcoIssues#12024]
the mouseover infopanel often collapses when you move your mouse to the next infopanel that you open from the first infopanel.
it happens for me on the third layer

**Comment by D3nnis3n** [comment]
Yep, that's actually very enerving.

**Comment by Quadbro** [comment]
are you talking about tooltips?

**Comment by D3nnis3n** [comment]
Yes. Try to hover over something to open a tooltip and then try to hover
over something in this tooltip to get another one, there is a very high
Chance the tooltips will wrongly close.

Mike <notifications@github.com> schrieb am Mi., 17. Apr. 2019, 07:31:

**Comment by trevelmike** [comment]
yep happens to me too i can not keep track of populations that way. I was also looking ahead for the materials needed for the laser and wind turbine and it kept collapsing

**Comment by D3nnis3n** [comment]
Same often happens when trying to use the scrollbar in a tooltip.
