### ISSUE TITLE
Check if   "ParallelWorldObjectTicks" is working correctly

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12026]
The issues
https://github.com/StrangeLoopGames/EcoIssues/issues/12004
https://github.com/StrangeLoopGames/EcoIssues/issues/11989

seem to be related to setting the option to true. This worked fine until update 8.1 (I'm actually using it since around update 7.5 without any problems, but benefits), actually quite some bigger server used it as it noticeably increased the performance. If that setting is broken, experimental or should no longer be used, please REMOVE it or give a clear notice to not use it. At the moment it's a normal option everyone can activate and servers that played around with it still know it's increasing performance and use it.

**Comment by mirasrael** [comment]
I identified issue which caused crashes and why it started happening recently. Actually those crashes also was possible before, but less less often. But regarding of this we still don't have good instruments and approaches to ensure parallel ticks stability. So I marked the option as experimental.
