### ISSUE TITLE
Animals seem to de-spawn beyond sight and can’t be chased.

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12028]
v8.1.0
I tried several times to chase animals which were hit and fleeing, if I reached the point where they are out of sight, no animal around and in the surrounding.
The view distance for animals is pretty close and has nothing to do with main setting View Distance!
I have not seen one hare since I try v8.x

**Comment by Nicolausi113** [comment]
They definitely despawn! I saw a bison in the marked area and hit it, then it disappeared.
Probably it became a whale :)

![bison](https://user-images.githubusercontent.com/38510829/56136553-4db43e00-5f93-11e9-8eec-02845a7d65e7.jpg)

**Comment by SeanAtr0n** [comment]
is your foliage setting turned way down? that setting really controls draw distance for most things, should probably be renamed

**Comment by Nicolausi113** [comment]
Yes, foliage is 52%, I’ll try to increase and look whether there is improvement – tanks.
![setting](https://user-images.githubusercontent.com/38510829/56174670-de226b00-5ff3-11e9-803e-b3c9ecc5d654.jpg)

**Comment by Nicolausi113** [comment]
With foliage set at least 100% is it ways better and doesn't have much impact on performance.
But a more meaningful name for this slider would be helpful, maybe “Object Range” or “Draw Distance”…?
