### ISSUE TITLE
USER ISSUE: hitbox fallen tree glitch

### ISSUE THREAD

**Issue by zombiepirate03** [StrangeLoopGames/EcoIssues#12022]
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
i dont really know what causes it but it looks luike your dot that indicates where you are striking at is stuck in the hitbox of the tree and after you turn away you cant cut the tree anymore after you fell it

**Expected behavior:**
you should be able to cut it

**Actual behavior:**
the hitbox doesnt show up and you cant cut it

**Do you have mods installed? Does issue happen when no mods are installed?:**
the hitbox doesnt show up and you cant cut it

**Comment by beastyn** [comment]
@zombiepirate03 Thank you for your report!
I have a few question if you don't mind as I can;t recreate it for now.
In what moment did you turn away? Is a dot was always on a tree?

Can you provise log file?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
In version 0.8.0.x when a fallen tree wasn't lying motionless on the ground, sometimes this happened. But in last version, I can't reproduce it.

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provise log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
