### ISSUE TITLE
[0.8.1.4] Empty slots tolltips

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12033]
[0.8.1.4]
no mods

Inventory shows first item's tooltip in empty slots.

*Steps* 
1. Place stockpile 1
2. Fill it with something
3. Place stockpile 2
4. Open stockpile 2
5. Make some sorting in stockpile 1
6. Hover over empty slots where was some item.
(or just /spawnfullstockpile and remove items from there
)
Sometimes it will show tolltip for item which was first time placed in the hovered slot. It works kind of awkward.
![empty_slot](https://user-images.githubusercontent.com/27898520/56125242-f366ad80-5f91-11e9-9258-7231d16e905d.gif)

**Comment by Nicolausi113** [comment]
as I said here #9344

**Comment by beastyn** [comment]
Yeap, indeed
