### ISSUE TITLE
Replacing blocks/items near door/window made room not a room

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12036]
v8.1.0
Without changing anything in the room or with tables, sometimes room counts invalid.
I have to remove a block and place it back to reestablish.

![room](https://user-images.githubusercontent.com/38510829/56132280-e1810c80-5f89-11e9-8796-38978e337bc9.jpg)

**Comment by CompactDisc** [comment]
Very often this happens to me in Bathrooms using a Latrine. Whenever I place another piece of furniture down, it becomes a general room until I place the Latrine back.

**Comment by CompactDisc** [comment]
Very often this happens to me in Bathrooms using a Latrine. Whenever I place another piece of furniture down, it becomes a general room until I place the Latrine back.

**Comment by BlazeGuy2** [comment]
@Nicolausi113 is this happening on 8.1.2 as well right now?

**Comment by Nicolausi113** [comment]
I’ve not migrated to v8.1.2 but will do now and report if it happens there again – please be patient.

**Comment by Nicolausi113** [comment]
I was now working a few hours with v8.1.2 and this issue happened again while I was working on a neighbor building 5 blocks apart.
Paradoxically it happens always with this ground floor shown below, where I have a double door inserted, don’t know whether this may be the reason, but I can not force the problem?

![ground floor](https://user-images.githubusercontent.com/38510829/56244721-e7681200-609d-11e9-80f2-670a8d199e66.jpg)

**Comment by SlayksWood** [comment]
The problem with double doors was before. I will recheck, but the last time was only this question #10316. 
You have blocks near the door. You have blocks near the door. In my opinion it is related to it.

**Comment by SlayksWood** [comment]
The problem with double doors was before. I will recheck, but the last time was only this question #10316.
You have blocks near the door. In my opinion it is related to it.

**Comment by Nicolausi113** [comment]
Okay, I rebuild that corner to a clean wall with double doors to see whether it happens again.

**Comment by CompactDisc** [comment]
Heh, all the rooms I had this issue with had double doors as well.

**Comment by Nicolausi113** [comment]
@CompactDisc 
You saying you had issues with all double doors! Did you now replace it with single doors and the issue is gone? This would be interesting.

**Comment by CompactDisc** [comment]
@Nicolausi113 Well, this is actually the case, yes. I can't test further than that though, since my server got reset due to another bug :P

**Comment by Nicolausi113** [comment]
@CompactDisc 
Thanks for that info – maybe it helps the devs

**Comment by CompactDisc** [comment]
@Nicolausi113 I sure hope so, this isn't the first time that double doors cause broken rooms :P

**Comment by Nicolausi113** [comment]
@SlayksWood
I think I can confirm now your opinion, since I changed the ground floor to a plane wall with double doors, the trouble is gone!
 It seems corners, edges, outside blocks have impact on calculation, but I see no systematic.
![room OK](https://user-images.githubusercontent.com/38510829/56370176-0f20bc80-61fb-11e9-8f4b-047506f64959.jpg)

**Comment by Nicolausi113** [comment]
Now I have evidence and can force breaking the room by removing one or both of the chests outside the room in front of an open window 1x2. If I fill the gap with windows, the effect can not be accomplished.
It seems the algorithm becomes unstable if gaps left open!
![chest breaks room](https://user-images.githubusercontent.com/38510829/56421147-5cf00000-62a1-11e9-8e3d-12dee5281555.jpg)

**Comment by SlayksWood** [comment]
Also see #10316
