### ISSUE TITLE
[0.8.1.3] Sleep timer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12031]
copy from #10102
Real-time passed:
It should be: It really is:
10 minutes 10 minutes
25 minutes 25 minutes
50 minutes 50 minutes
1 hours 25 minutes 1 hours 25 minutes
When the time becomes 1 hour 30 minutes it starts to display incorrectly
It should be: It really is:
1 hours 30 minutes 2 hours 30 minutes
1 hours 55 minutes 2 hours 55 minutes
2 hours 08 minutes 2 hours 08 minutes
2 hours 22 minutes 2 hours 22 minutes
2 hours 38 minutes 3 hours 38 minutes
2 hours 44 minutes 3 hours 44 minutes
3 hours 29 minutes 3 hours 29 minutes
3 hours 30 minutes 4 hours 30 minutes
etc...

**Comment by LWChris** [comment]
Hour number needs to be floored, not rounded.

**Comment by Deantwo** [comment]
Yeah it does indeed look like the Hours number is rounded instead of floored.
