### ISSUE TITLE
Various Minimap Fixes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1203]
![image](https://cloud.githubusercontent.com/assets/3536496/24222193/7e5f22d6-0f0e-11e7-93ee-d170e098b93d.png)
1. Set a max # of text fields to display, if there are more than that display none (unless you're at maximum zoom)
2. Minimap text should not overlap, make text push apart so that they don't overlap.

![image](https://cloud.githubusercontent.com/assets/3536496/24222229/a31255f8-0f0e-11e7-8ff6-d440c1b65315.png)
![image](https://cloud.githubusercontent.com/assets/3536496/24222235/a619c646-0f0e-11e7-80d9-6ed33702548c.png)
3. Make the filter panel buttons bigger and easier to click. Reduce the space between them.
4. Add categories for everything so they're not showing every type as a category.
5. Label the world layer box and the category list
6. Make the world layer box bigger and make the drop down selection box bigger
7. Add back all the world layers to the list and make the server only send them if they're being viewed.

**Comment by stett** [comment]
@johnkslg do you mind if i break this up into separate issues? Some of these are easy bugfixes and some of them are new features.

**Comment by stett** [comment]
I broke this up into a bunch of separate ones
