### ISSUE TITLE
First Inventory line was fixed at top and isn’t anymore

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12037]
v8.1
This was a useful function since v7.8 i think, dismissing it makes inventory management more painful!
![invent1+2](https://user-images.githubusercontent.com/38510829/56153402-5a965900-5fb6-11e9-915b-9849875317a9.jpg)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10860

Was removed to fix something, was meant to come back in 9.0, probably with feature of actively pin and unpin the storage.

**Comment by D3nnis3n** [comment]
Not necessarily a regression though, as this was removed pre 8.0.

**Comment by seccombew** [comment]
@D3nnis3n Do you know who worked on it previously?

**Comment by SlayksWood** [comment]
Fixed in 9.0
