### ISSUE TITLE
[0.8.1.3] Steam tractor plough not synced in multiplayer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12049]
When another player works on steam tractor and lowers a plough, I don’t see it.
https://drive.google.com/file/d/1ZaeZSWnVpRO2JS3cCFkzHS6N5vzd2daH/view?usp=sharing

**Comment by D3nnis3n** [comment]
Actually a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/9105, closing mine as you got a video. Lowering priority to low, though.
