### ISSUE TITLE
[0.8.1.3] Menu "Controls" doesn't contain the ability to change all setting

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12042]
The scroll wheel is used in control of the crane. But I can't change it.
![image](https://user-images.githubusercontent.com/45708377/56207476-80c00580-6057-11e9-863a-abca1f3ec523.png)
![image](https://user-images.githubusercontent.com/45708377/56207488-89184080-6057-11e9-9f96-cbd2ca00891d.png)
![image](https://user-images.githubusercontent.com/45708377/56207493-8d445e00-6057-11e9-8e1b-4aaa7c66624c.png)

**Comment by Nicolausi113** [comment]
I would like to have a choice between scroll wheel and left/right arrow-key. I have blocked my mouse wheel since it controls also tool-bar selection, for me enerving.

**Comment by SlayksWood** [comment]
Scroll Wheel - Crane, Excavator, Skid Steer.
F5 - for change avatar view
Q - in Excavator, Tractor ()
R,F - in Excavator
If you change Button it will be display in Controls
![image](https://user-images.githubusercontent.com/45708377/57759634-0096c980-7703-11e9-9dd6-f8d71c7a2154.png)

**Comment by SlayksWood** [comment]
ESC - if someone wants to change

**Comment by SlayksWood** [comment]
After 0.8.2.9 Fixes:
Scroll Wheal - Crane, when change block type with Shift
Esc - at least add the ability to assign secondary button

**Comment by SlayksWood** [comment]
Q - in Excavator, Tractor

**Comment by SlayksWood** [comment]
merged to #12496
