### ISSUE TITLE
[0.8.1.3] Mid chunk of stone bounces while mining

### ISSUE THREAD

**Issue by dgorham01** [StrangeLoopGames/EcoIssues#12044]
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
1. Mine a block of limestone
2. Mine the two pieces of limestone that are one

**Expected behavior:**
The limestone should come apart into two pieces and remain where it is.

**Actual behavior:**
Instead the limestone comes apart and sometimes falls through the world.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead the limestone comes apart and sometimes falls through the world.

**Comment by SlayksWood** [comment]
fixed in 0.8.2.8 with https://github.com/StrangeLoopGames/Eco/pull/4681
