### ISSUE TITLE
[0.8.1.3] Custom channel hiding glitches

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12048]
[0.8.1.3]
no mods

**Steps**
1. Create custom channel 1 (Test)
2. Create Custom channel 2 (Test2)
3. Activate channel 1
3. Hide channel 1 with right click

**Expected Result**
->Don'allow to hide active chat or
->hide it and activate #general
**Actual result**
channel 1 was not found in the hidden
If you activate channel 2 then channel 1 will appear

![bandicam 2019-04-17 17-03-54-139](https://user-images.githubusercontent.com/27898520/56286415-15e3fc80-6133-11e9-88f8-76bcda877ca4.jpg)
![bandicam 2019-04-17 17-03-58-479](https://user-images.githubusercontent.com/27898520/56286419-18465680-6133-11e9-87b0-7ce1ee719b57.jpg)
![bandicam 2019-04-17 17-04-02-185](https://user-images.githubusercontent.com/27898520/56286421-1a101a00-6133-11e9-84ae-c0a22e4cc877.jpg)
![bandicam 2019-04-17 17-04-10-044](https://user-images.githubusercontent.com/27898520/56286426-1bd9dd80-6133-11e9-837d-a21f67d2edd7.jpg)
![bandicam 2019-04-17 17-04-17-153](https://user-images.githubusercontent.com/27898520/56286428-1da3a100-6133-11e9-8549-eea59ebeaea8.jpg)

**Comment by beastyn** [comment]
Also problem with Hiding General channel.
1. Hide general
2. Doesn't appear in the Hidden section
3. Click any channel - General appears in the Hidden
4. Show general - it won't appear in channel list until make something with channels

**Comment by WeaselDog** [comment]
Will be fixed with chat refactor
