### ISSUE TITLE
[0.8.1.2] Error starting server under 0.8.1.2

### ISSUE THREAD

**Issue by FlorianMez** [StrangeLoopGames/EcoIssues#12052]
Failed to load server, Exception was Exception: Exception Message:Error(s) occured when loading Worldobjects Source:Eco.Core
System.Exception: Error(s) occured when loading Worldobjects at Eco.Core.Serialization.DataStore.LoadAsync(T)<String folder, Action'2 createFunc>
at Eco.Gameplay.Objects.WorldObjectManager..ctor()

**Comment by mirasrael** [comment]
Hi @FlorianMez 
Can you upload the server save and attach to issue?

**Comment by mirasrael** [comment]
Closed issue due to no response. Fill free to re-open issue if you can add more details.
