### ISSUE TITLE
USER ISSUE: Cant remove one Dirt block

### ISSUE THREAD

**Issue by apostol1322** [StrangeLoopGames/EcoIssues#12054]
**Version:** 0.8.1.2 beta

**Steps to Reproduce:**
1. I am digging one specific dirt block, that doesnt have anything around it, no trees, no grass, absolutely nothing

**Expected behavior:**
The dirt should be removed.

**Actual behavior:**
Instead it shows me a message saying that i cant remove the soil because it has strong roots.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it shows me a message saying that i cant remove the soil because it has strong roots.

**Comment by Nicolausi113** [comment]
If restarting game doesn’t help, you can try using devtool if you are admin or single player - “/give devtool” and use with left click – but it’s a cheat.

**Comment by apostol1322** [comment]
> If restarting game doesn’t help, you can try using devtool if you are admin or single player - “/give devtool” and use with left click – but it’s a cheat.

The problem is that, this happend in a MP server.

**Comment by beastyn** [comment]
@apostol1322 Thank you for your report! I think this is  Duplicate of #10550
