### ISSUE TITLE
Elevator NOT fixed

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#12055]
https://github.com/StrangeLoopGames/EcoIssues/issues/11714 Original post here. I don't know why you said fixed when it clearly is not. Same problem as before i put my wooden cart on elevator and goes down by itself. Buttons do not respond and i have to remove the elevator and put it back as the work around.

**Comment by D3nnis3n** [comment]
The fix is included in the NEXT hotfix, 8.1.4.
