### ISSUE TITLE
[0.8.1.3] Distribution station is working incorrect

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12057]
1. Value "Max days played for citizens to be eligible" reset to basic value "5".
Step to reproduce
- Set the value on "2".
- Leave the station and do something else (about 10 minutes)
- Go back to the station.
- Open tab "ItemDistribution"
- The value "Max days played for citizens to be eligible" is set to "5".
- Don't change the value and click Apply. The message says that the value "Max days played for citizens to be eligible" is set to "2".
![image](https://user-images.githubusercontent.com/45708377/56346036-dd433200-61c9-11e9-82d4-787f7f5904ed.png)
2. You can take more items than distributed. 
Step 1 to reproduce
- Using the command /testdistributionstation  many times.
- Find the distribution station where the number of distributed items indicated less than in it.
- Drag the item to your inventory.
- Very often you can take more items than indicated.
Step 2 to reproduce
- Another player spawn the distribution station
- Another player put 200 Log in distribution station
- Another player set item to distribute for citizen: Log 10
- You spawn stockpile near distribution station
- Drag Log from distribution station to your stockpile with Shift.
Repeat some times.
Every time you get a different amount of Log (I got 50max)
3. I'm not quite sure that it's a bug. But I think distribution station has the wrong behavior.
I can use items even if I'm not a new city citizen. 
- Another player makes a station when I am a new citizen.
- wait need time so that I don't fit the distributed station's requarements.
- While another player doesn't refresh at tab "ItemDistribution" with button "Apply" I can use the distributed station.
![image](https://user-images.githubusercontent.com/45708377/56345764-3494d280-61c9-11e9-8174-53d0602496df.png)
Day 10, 14:22

**Comment by SlayksWood** [comment]
1. Sometimes Value "Max days played for citizens to be eligible" reset to basic value "5".50/50
Small size of cell value I was added in separate issue #12187.
![image](https://user-images.githubusercontent.com/45708377/57352380-e2165880-716d-11e9-948f-5460fa3d54f9.png)
2. You can take more items than distributed when use LMB or Shift+LMB
![image](https://user-images.githubusercontent.com/45708377/57354370-f4939080-7173-11e9-9722-4c4d1d3a70ae.png)
![image](https://user-images.githubusercontent.com/45708377/57354416-0e34d800-7174-11e9-9e6e-93c8c92d560d.png)
3. When I try to use items even if I'm not a new city citizen-> Crash
Anna will add separate issue with crash crash #12215

**Comment by SlayksWood** [comment]
1. Value "Max days played for citizens to be eligible" reset to basic value "5". 50/50
2. You can take more items than distributed. 
 - Drag Item from distribution station to your stockpile with Shift. (return bug). Afrer #4308 it was fixed.
 - You can take more items than distributed when use LMB or Shift+LMB

**Comment by SlayksWood** [comment]
You can take more items than distributed.
- Drag Item from distribution station to your stockpile with Shift. (returned bug). Afrer #4308 it was fixed.
- You can take more items than distributed when use  only Ctrl+LMB

**Comment by Deantwo** [comment]
I am late to the party maybe, but wouldn't it be easier to just make the Distribution Station have an interface similar to a store? Showing you how much you can take and how much is there.
Instead of being able to access it like it is a container when you clearly don't have access to everything in it like a normal container.

Less confusing for new players, less bugs with weird limited inventory management, and likely less weird snowflake code.

**Comment by D3nnis3n** [comment]
Closing until someone reopen again, lol.

**Comment by D3nnis3n** [comment]
@Deantwo Open a suggestion.
