### ISSUE TITLE
[0.8.1.3] Broken highlighting for possible crafting at crane

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12051]
1. Put down crane from the inventory.
2. Mount crane.
3. Highlighting works.
![image](https://user-images.githubusercontent.com/45708377/56287754-df53b500-6125-11e9-9cdf-5d62168d578c.png)
4. Unmount crane.
5. Unclaim crane.
![image](https://user-images.githubusercontent.com/45708377/56287809-014d3780-6126-11e9-971c-17245734bd9d.png)
6. Mount crane.
7. Highlighting is broken.
![image](https://user-images.githubusercontent.com/45708377/56287844-1629cb00-6126-11e9-9e01-075be7d6c036.png)

**Comment by Quadbro** [comment]
can't reproduce this in master ;(

**Comment by SlayksWood** [comment]
Can't reproduse it in 8.2.0 staging-7. Seems fixed.
