### ISSUE TITLE
8.1.3 Can't select Brazilian Portuguese

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12063]
Problem: Can't select Brazilian Portuguese in Options Menu

In a local game and with  complete pt-BR translation files from crowdin

I tried to move the web client part to D:\Games\EcoPC_v0.8.1.3-beta\Eco_Data\Server\WebClient\WebBin\i18n\pt-BR\WebClientStrings.csv
Also moved the game part to D:\Games\EcoPC_v0.8.1.3-beta\Eco_Data\Server\Mods\Translations\defaultstrings.csv

When loading game, English prevails
When using option in ServerUI and setting it to Brazilian Portuguese, English still prevails

Header in localization file has BrazilianPortuguese wrongly written, with two 'l'.

**Comment by criptonauta** [comment]
Update

In a VPS Hosted World

![image](https://user-images.githubusercontent.com/6478038/56397062-fec70c80-620f-11e9-8ae7-e7401569cf27.png)


Although not being displayed in language list in General Menu, the change in Localization.eco to 

`{
  "Language": "BrazillianPortuguese"
}`

produced effect

**Comment by beastyn** [comment]
@criptonauta Thank you for your report. We will look through this one.

**Comment by beastyn** [comment]
@criptonauta 
I didn't have problems with choosing the language, though it has typo.
Can I get your files with translation if you don't mind?

**Comment by criptonauta** [comment]
> 
> 
> @criptonauta
> I didn't have problems with choosing the language, though it has typo.
> Can I get your files with translation if you don't mind?




[Eco Translation.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3109179/Eco.Translation.zip)

**Comment by criptonauta** [comment]
@beastyn is your webclient loading in pt-BR? Mine is still in English

**Comment by beastyn** [comment]
@criptonauta sorry for a long delay
I see the problem but I see that localization will be changed in 8.2 also bug with UI locking will bw fixed.
Let see how it will work then.
I will create separate issue for typo Brazillian if you don't mind.
