### ISSUE TITLE
Resurrect ability to see staging server in master build

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12065]
This used to work, not sure why its not. Players should be able to see the official test server in a separate test group, and when they click it they get a message about how to switch to staging.
![image](https://user-images.githubusercontent.com/3536496/56436078-8869ef00-628f-11e9-8584-95e4daf541fb.png)

![image](https://user-images.githubusercontent.com/3536496/56436112-a172a000-628f-11e9-9c19-4ffa0090bae0.png)

**Comment by metachronism** [comment]
because it doesnt work this way anymore.  The master server has a list of servers that are official, and it puts them in that category.

**Comment by mirasrael** [comment]
@johnkslg we just need to add server id to officalServer.txt on master server and it should work. It should be there already. I started server on Stuffed Elk and it works fine:
![image](https://user-images.githubusercontent.com/475445/56504182-6cc94780-6520-11e9-9f4f-17e2bfbdc881.png)
