### ISSUE TITLE
User's machine is running 18fps and not using all the GPU or CPU resources

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12069]
![image](https://user-images.githubusercontent.com/3536496/56447837-7dc74e00-62bf-11e9-9815-6b6b415a8148.png)
Getting 18FPS at this moment

User is TwistBurn on Discord and is able to help debug. 

His specs:
Intel Core i7-6700k 4.0ghz, memory ram 16gb,  grafic Nvidia Geforece GTX 980

Other games run very well he says. Dota 2 is getting 110FPS

**Comment by mirasrael** [comment]
Probably it is CPU bound... :) This CPU has 8 cores, 100/8 = 12.5% for single 100% loaded core. So it doesn't seems like a different problem from that we already have.

**Comment by johnkslg** [comment]
@BlazeGuy2 can you get the latest build to this person
