### ISSUE TITLE
USER ISSUE: Mine Sound is lost

### ISSUE THREAD

**Issue by MEGA3L** [StrangeLoopGames/EcoIssues#12064]
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**
1. Go to farm stone, the peak in action not destroy the material (basalt, granito, sandstone, etc.) give it several times for wreck it.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by beastyn** [comment]
@MEGA3L 
For some material you will need few hits. For granite you will need 2 hits with stone pickaxe. But it looks that we've lost some sounds there,
