### ISSUE TITLE
USER ISSUE: Stuck inside a RedWood tree

### ISSUE THREAD

**Issue by apostol1322** [StrangeLoopGames/EcoIssues#12061]
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**

**Expected behavior:**
ALREADY tried the unstuck command

**Actual behavior:**
The chunk wasnt load and when it did i was stuck inside the Redwood tree. I tried the unstuck command and nothing happend.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The chunk wasnt load and when it did i was stuck inside the Redwood tree. I tried the unstuck command and nothing happend.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/11375

**Comment by D3nnis3n** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/12053
