### ISSUE TITLE
Old Problem: Teleported Stones on surface after digging a tunnel

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12079]
v8.1.3 (single player)
- the stones are not easy to find, minimap does not show debris and grass is 2 meter tall,
- what impact does it have on performance?
- I found one open issue on this matter #7365
![teleport1](https://user-images.githubusercontent.com/38510829/56474408-9a0eea80-6479-11e9-9684-dcf2964807f0.jpg)
![teleport2](https://user-images.githubusercontent.com/38510829/56474409-a4c97f80-6479-11e9-97c4-5f0ff2f4dc4b.jpg)
![teleport3](https://user-images.githubusercontent.com/38510829/56474418-c591d500-6479-11e9-8d88-79769891129c.jpg)

**Comment by beastyn** [comment]
@Nicolausi113 
Thanks for report. The old issue has some additional info, so I will close this one.
Please, write your related thoughts in the old one. #7365
