### ISSUE TITLE
USER ISSUE: Stockpile in area but not

### ISSUE THREAD

**Issue by skoch98** [StrangeLoopGames/EcoIssues#12077]
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**
1. Create a large Landscape with the Land Marker Tool (8 or 10 Land Papers)
2. Build a Stockpile in one corner and the workbench or table saw in other

**Expected behavior:**
I get access to my storage :D

**Actual behavior:**
The storage is not listed in the storage tab

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nope I'm playing without mods.

**Comment by Gemji1990** [comment]
the conection has a limited range of about 10 blocks center to center of the object try to move the stockpile near the workbench or reverse.

**Comment by skoch98** [comment]
Ok thanks for this information. Then its very hard if you have a large landscape with multiple houses.
