### ISSUE TITLE
Avast thinks its bad

### ISSUE THREAD

**Issue by Gemji1990** [StrangeLoopGames/EcoIssues#12071]
just got a IDP.Generic warning for the Ece.exe
the exe got erased in the process. >.<
i run steam repair and try again.

Edit:
it works again, i think it happend bevause i started the eco server at the same time.

**Comment by D3nnis3n** [comment]
Avast is known to cause weird problems with the game, there is nothing we can do about - but you can mail their support and complain about that, if you like.
