### ISSUE TITLE
[8.1.3] FPS slowdown

### ISSUE THREAD

**Issue by Phozoh** [StrangeLoopGames/EcoIssues#12072]
I, and all other clients on my server, am experiencing this still in 8.1.3 after a previous update declared problem fixed.
Similarly described issues are #11225  and #12069 
I am locally hosting a dedicated server and playing on the same computer, as this was a non issue on my 6.0 play-through

After in-determined amount of time, FPS will tank, traveling away from homes abates problem but not for long.
A full game restart fixes it on all clients, but the performance loss scales on how good client hardware is to begin with. Adjusting graphics settings have no effect on FPS after slowdown has begun.

I have 4790K,GTX 1080,16GB RAM,860 EVO SSD, other clients have either same or worse hardware.
FPS after slowdown is 25-45 FPS with severe stuttering
CPU usage is balanced across all cores, GPU% is not going to 100%
After a restart, smooth as a babies bottom @ 100+ FPS

Please let me know if more details are required.

**Comment by Gemji1990** [comment]
sounds like a ramleak, check how much ram the client uses when you start it and when the game slows down.

**Comment by Phozoh** [comment]
> sounds like a ramleak, check how much ram the client uses when you start it and when the game slows down.

Ram is consistent,
On startup = 2400mb
After 1 hour gameplay and fps is slow, usage was 2800mb

**Comment by Phozoh** [comment]
![image](https://user-images.githubusercontent.com/41300876/56467648-eaf2f480-6421-11e9-9f05-b6162835097a.png)

New ram usage is 'high' during this new phase of FPS lag. (3520mb)

This is ram, cpu, gpu and fps data in one screenshot.
Please let me know if you need more data.

**Comment by metachronism** [comment]
@Phozoh GPU not being at 100% means you are CPU bound.  You can turn up a few, probably all really, of the graphics options and not have much if any effect on your framerate.  Really turn them all up till you reach 100% GPU utilization.

Your set view distance is pretty high, I would suggest turning it down to 120 or so.

**Comment by Phozoh** [comment]
Round 2 Testing begins, 
for consistency's sake, i have reset to defaults and turned vsync off to see real FPS.

GPU went to 100% for a few minutes.
I started randomly running doing, things, eating, making stuff opening inventories, GPU usage steadily decreased while average CPU usage decreased from 35%~ for the Eco process down to 22-26%.
FPS decreased to 15-25
Quitting the game the Eco process maintained a 17.5% CPU usage (exactly) for 2-3 minutes.

Starting the game was smooth, once loaded into server, FPS fluctuated with GPU usage 100% gpu = 66~ fps.
Moving around, fps goes down to 40~ and GPU @ 50% and standing still returns to 66~ FPS with GPU back to 100% 

So far normal... 
up until i start opening chests/containers.
I opened maybe 10 containers and returned to a mountain looking up and away from the planet.
GPU usage remained at 40% for 60-90 seconds before returning to 100%

I repeated the above 3 times, each time with the same results.

Opening a single container GPU usage instantly drops to 75-82%, GPU returns to 97-100% after 30~ seconds.
Opening two or more containers drops GPU usage to 60%~
Opening many containers increased GPU recovery time to 60-120 seconds
Server process CPU usage remains 1.5%~ while accessing containers.
Eco client process doesn't seem to be able to use more than 32%~ CPU

Testing on a single instance (no restarts) for approx 40 mins.
Please forgive the rambling, typed as i experienced it.

Please draw some conclusions (if you can from my rambling)
Please let me know if more information is required.

**Comment by mirasrael** [comment]
@Phozoh Thanks for detailed information! Before 8.2 (not released) we didn't have cleanup for old server views (like chests, stockpiles etc). So they was linked to the server and was continue receiving updates, so this may cause extra CPU load even after you stopped using those objects. It was fixed in 8.2 and we're expecting soon the staging server for 8.2. So we will very appreciate if you will be able to test the performance problem on new version when it will be available.

**Comment by seccombew** [comment]
@Phozoh @mirasrael 's work should make a big improvement here. Please reopen if the issue occurs again.
