### ISSUE TITLE
8.1.3 Hole in water

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12080]
Most of the time it doesn't happen. But there are still some holes when using pipes in water

![image](https://user-images.githubusercontent.com/6478038/56481826-f3cddf80-648e-11e9-8bdf-86ef5243f2ee.png)

**Comment by beastyn** [comment]
Also check refill with water after removing a block

**Comment by beastyn** [comment]
also its just windows in the water
![bandicam 2020-05-27 17-31-03-989](https://user-images.githubusercontent.com/27898520/83019139-e6930500-a03f-11ea-85f9-9f210e1d91c3.jpg)
![bandicam 2020-05-27 17-31-10-494](https://user-images.githubusercontent.com/27898520/83019160-eb57b900-a03f-11ea-8e42-5ee5f3253f12.jpg)

**Comment by beastyn** [comment]
#18532
At the edge of the pipe.

**Comment by SlayksWood** [comment]
Fixed issue with surface, other was merged to #12471
![image](https://user-images.githubusercontent.com/45708377/121478709-fb83d180-c9d1-11eb-8884-7457bbcc9c2d.png)
![image](https://user-images.githubusercontent.com/45708377/121478749-050d3980-c9d2-11eb-96d4-7e985cded546.png)
