### ISSUE TITLE
Stairs not working in 0.5.5.1

### ISSUE THREAD

**Issue by ThatHg** [StrangeLoopGames/EcoIssues#1208]
I am unable to climb stairs in this version. Stairs worked in 0.5.4, but since the 0.5.5 update stairs are no longer working.

Also please remove auto orientation and make orientation manual with Q and E as everything else, it will make lives so much easier.

**Comment by metachronism** [comment]
You need to turn clambering on in the options menu for now.  This will probably become the default but its in testing right now
