### ISSUE TITLE
Pumps works... strange

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12082]
copied from #11355.
Blast furnace cannot work 100% time.

**Comment by criptonauta** [comment]
It happens with me as well. No matter the numbers of pumps used, there is always a brief moment when the water flow is less than the required, making the furnace to stop and go live again.

One pump is enough for 1 blast furnace, so if adding more water to it though more pumps, the only result is more sewage

**Comment by johnkslg** [comment]
Give @mirasrael a high-five for this one.
