### ISSUE TITLE
Waste Filter Treats sewage even with no electricity

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12087]
8.1.3

Although not completely, Waste Filter treats sewage even when there are no generator to provide electricity for it.

![image](https://user-images.githubusercontent.com/6478038/56523426-74372380-6515-11e9-8844-c42ec2f5c9eb.png)

Also producing compost

![image](https://user-images.githubusercontent.com/6478038/56523557-a183d180-6515-11e9-9a10-f5a2e92e9d6c.png)

**Comment by beastyn** [comment]
It looks like this one #11213
If you have waterflow you will have sewage.
Even if you generator is off,
