### ISSUE TITLE
[0.8.1.3] Incorrect Icon for Farmer's Talents

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12081]
Only in Farmer specialty icons for talents Focused Workflow, Parallel Processing, Frugal Workspace, Lavish Workspace differ drom other specialties. 
For all of them the same icon:
![image](https://user-images.githubusercontent.com/45708377/56485968-c4df5a00-64de-11e9-996e-03f421d55aba.png)

**Comment by elfl0rd** [comment]
fixed
