### ISSUE TITLE
Can't see Claims while placing Campsite

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12084]
A big issue for newbies is that they can't see other players' claims. It is very hard to know where to place your starter camp when you can't see what land is claimed and what isn't.

On the SeaOtter server we have had many new players come in and set a camp down in the middle of someone else's area.

I have suggested it before, we need a way to see claims while not holding a Land Claim Stake, a hotkey to toggle it on and off maybe. Then you can make it automatically toggle on when you select the Land Claim Stake or the Campsite.

Being able to toggle claims view on while holding any item would just be useful in many cases, and it would solve issues like this.

**Comment by Deantwo** [comment]
I am still partly against the idea of campsites. They are awesome when you first start out as a new player on an empty world. But apart from that they only cause confusion and issues. Issues such as making new players think they can't up-and-move after placing the campsite, or not having access to any of their tools before they place it.

But that is a whole other issue that we don't need to get into here, just wanted to mention it.

**Comment by Nicolausi113** [comment]
Therefore I plead for having all tools in backpack for varies reasons and a hotkey to toggle or switch claim view will be awesome!

**Comment by D3nnis3n** [comment]
The tutorial is base around the starter camp and the starter camp is the only way to sleep for singleplayer players until they have a bed, so it's unlikely that will be changed. A compromise could be to actually show the claims when having the starter camp in hands - you only have that item once, so that should be no problem.
