### ISSUE TITLE
Sticky Tooltip/Info in Skill Menu

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12098]
v0.8.1.4
![skillmenu](https://user-images.githubusercontent.com/38510829/56659767-3e717680-669e-11e9-8b28-698286786393.jpg)

if clicking in Lumber above, this appears – but is not always the case. Looks kind of #10811
![sticky info3](https://user-images.githubusercontent.com/38510829/56659819-5a751800-669e-11e9-93ac-4bdd513e8fc8.jpg)

**Comment by seccombew** [comment]
@D3nnis3n could you gather more info please and add it to this issue?

**Comment by D3nnis3n** [comment]
I've already tasked Quadbro with that issue and we've talked about it.
The Skills Page has a consistent strange behaviour regarding to tooltips there.
Often when i hover any item a tooltip comes up at a very weird location and does not vanish until clicking somewhere else. It seems like Quadbro is already on it, but thinks it's quite a fuss to fix it.
