### ISSUE TITLE
[0.8.1.4] Wood cart teleporter

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12099]
[0.8.1.4]
No mods
**Steps**
1. Make a shaft and an elevator 
2. Get down.
3. Mine something
4. Put a wood cart in a wall
5. Mine further until a wood cart will be on the ground
6. Try to mount a cart
7. Teleport on top
![bandicam 2019-04-24 17-38-10-077](https://user-images.githubusercontent.com/27898520/56660383-de3bfe00-66b8-11e9-8a2e-587157d80902.jpg)
![bandicam 2019-04-24 17-38-39-268](https://user-images.githubusercontent.com/27898520/56660398-e300b200-66b8-11e9-94d9-6c8ae7baf862.jpg)
![bandicam 2019-04-24 17-41-56-222](https://user-images.githubusercontent.com/27898520/56660405-e4ca7580-66b8-11e9-8012-e357ffc981b7.jpg)
![cart_teleport](https://user-images.githubusercontent.com/27898520/56660411-e7c56600-66b8-11e9-8be9-e36683a9b788.gif)

**Comment by beastyn** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3112301/output_log.txt)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/9382
