### ISSUE TITLE
Stuck when closing game

### ISSUE THREAD

**Issue by Jone6552** [StrangeLoopGames/EcoIssues#12097]
When I go to the menu and click quit, the game basically freezes. It isn't that the game isn't responding, its just that it doesn't close. I've tried using Ctrl-Alt-Delete to open task manager and close it from there, but when task manager opens it wont let me leave the game screen, rendering task manager useless. So far the only temporary fix I've found is to disconnect from the server, then quit the game. I've been playing on the public server Sea Otter, if it's a server side issue.

**Comment by SlayksWood** [comment]
please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide log file.
