### ISSUE TITLE
USER ISSUE: Connection Timed Out - Any Server

### ISSUE THREAD

**Issue by thebarbarian09** [StrangeLoopGames/EcoIssues#12095]
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**
1. Log into a server.
2. Wait less than 5 minutes.
3. Lose Connection

**Expected behavior:**
Connection should be stable

**Actual behavior:**
The following error message popped up:
Connection timed out

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have yet to install any mods yet.

**Comment by thebarbarian09** [comment]
Connection timed out

Log File:
Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   
    VRAM:     8088 MB
    Driver:   25.21.14.1967
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.351085 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
Connecting to 172.106.174.80:15615...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
UnityEngine.SkinChangedDelegate:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
UnityEngine.SkinChangedDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Curved/Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mobile/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert' - Pass 'Meta' has no vertex shader
Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16470 unused Assets to reduce memory usage. Loaded Objects now: 262035.
Total: 323.540821 ms (FindLiveObjects: 14.563207 ms CreateObjectMapping: 11.151099 ms MarkObjects: 273.820579 ms  DeleteObjects: 24.005448 ms)

Connecting to 172.106.174.80:15615...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
UnityEngine.SkinChangedDelegate:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
UnityEngine.SkinChangedDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 17216 unused Assets to reduce memory usage. Loaded Objects now: 315768.
Total: 348.734350 ms (FindLiveObjects: 18.778424 ms CreateObjectMapping: 12.151691 ms MarkObjects: 296.276620 ms  DeleteObjects: 21.527128 ms)

Connecting to 172.106.174.80:15615...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
UnityEngine.SkinChangedDelegate:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
UnityEngine.SkinChangedDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Coroutine couldn't be started because the the game object 'MountSpot' is inactive!
MountSpot:Mount(PlayerBase)
OtherPlayer:set_Mount(MountSpot)
Mountable:Mount(Int32, PlayerBase)
Mountable:UpdateMounts()
Mountable:OnOtherPlayerSpawned(GameObject)
System.Action`1:Invoke(T)
OtherPlayer:ReceiveInitialState(BSONObject)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()

[ line 783] 
(Filename:  Line: 783)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16957 unused Assets to reduce memory usage. Loaded Objects now: 326734.
Total: 383.866759 ms (FindLiveObjects: 24.401394 ms CreateObjectMapping: 16.979844 ms MarkObjects: 320.503203 ms  DeleteObjects: 21.981832 ms)

**Comment by thebarbarian09** [comment]
I also want to add that I've already ruled out any issue with my internet connection and my computer as other games I play have been working just fine. I ran several tests using a server I've been playing just fine on for the last week or so, the Sea Otter Official test server, and a randomly picked public server. I was forcefully disconnected from them within the span of five minutes with the same or very similar error messages to the one above.

**Comment by mirasrael** [comment]
Which connection type are you using?

**Comment by thebarbarian09** [comment]
Update: Issue still present in 0.8.1.4 

Tried uninstalling and deleting all local files including those located in the AppData directory, and jumped on the Sea Otter server. I'm still getting disconnected for no reason.

Spectrum Wi-Fi Wireless 5 Ghz Connection, Approx. 35 Mbps Download, 5 Mbps Upload
I assume that's what you're asking about.

**Comment by thebarbarian09** [comment]
Connection timed out

Log File:
Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   
    VRAM:     8088 MB
    Driver:   25.21.14.1967
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.347916 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
Connecting to 95.216.39.195:3010...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Curved/Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mobile/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert' - Pass 'Meta' has no vertex shader
Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 20098 unused Assets to reduce memory usage. Loaded Objects now: 415962.
Total: 501.774565 ms (FindLiveObjects: 23.830393 ms CreateObjectMapping: 12.156811 ms MarkObjects: 435.105444 ms  DeleteObjects: 30.681673 ms)

Connecting to 95.216.39.195:3010...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 415935.
Total: 482.043335 ms (FindLiveObjects: 23.045327 ms CreateObjectMapping: 9.530987 ms MarkObjects: 449.096187 ms  DeleteObjects: 0.370590 ms)

Connecting to 95.216.39.195:3010...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Dimensions of color surface does not match dimensions of depth surface
 
(Filename:  Line: 2511)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 15557 unused Assets to reduce memory usage. Loaded Objects now: 420376.
Total: 610.058980 ms (FindLiveObjects: 30.700203 ms CreateObjectMapping: 16.353010 ms MarkObjects: 537.165412 ms  DeleteObjects: 25.839868 ms)

**Comment by thebarbarian09** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3115057/output_log.txt)

**Comment by thebarbarian09** [comment]
Let me know if there's anything you need to know or need me to test so we can find the source of this issue.

**Comment by thebarbarian09** [comment]
[Error Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3119389/Error.Log.txt)

Added recent error log

**Comment by thebarbarian09** [comment]
After doing some research, it turns out that this issue may be with Unity itself. I've seen a lot of Fortnite players complaining about similar Connection timing out issues. 

Also the issue has seemed to clear up a bit, I was able to play for a couple hours without being forcefully disconnected. Just had to look at my task manager and remove any extra processes using up network speed.

**Comment by beastyn** [comment]
@thebarbarian09 
How is your issues? Do you still have problems with connection timeout?

**Comment by thebarbarian09** [comment]
As it stands, the connection timeout has disappeared but I'm concerned that I can't tell what was different if anything at all.

You may close this ticket as I haven't had a timeout since approximately four days ago and I can always submit another ticket if it rears its ugly head again.

**Comment by beastyn** [comment]
@thebarbarian09 thanks for your report. Feel free to reopen if the issue will apeear again.
