### ISSUE TITLE
Books And Scrolls Not Working

### ISSUE THREAD

**Issue by FuckFaceBecauseSomeoneStoleMyUserhandle** [StrangeLoopGames/EcoIssues#12093]
I have a problem on server "Gaudsauce Gaming Breeish - Late Server Shift ^_^" When I try to use a scroll or book it doesn't work. The book doesn't produce a scroll and the scroll isn't consumed and I don't get the skill or the claim stake papers. Haven't tried single player or other servers so not sure if it's a problem with my files or the server. Other people don't seem to be having any problems using books and scrolls, only me so far from what I can tell. I tried validating game files but it said, no missing files.
I have room in my inventory as well so it's not that.

**Comment by SlayksWood** [comment]
Can you provide log file?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing for no response, feel free to reopen when you can provide us with the necessary information.
