### ISSUE TITLE
USER ISSUE: Cannot change world default currency

### ISSUE THREAD

**Issue by jammie19** [StrangeLoopGames/EcoIssues#12094]
**Version:** 0.8.1.3 beta

**Steps to Reproduce:**
1. Open the Treasury window.
2. Attempt to click on the field next to where it says "World default currency:"

I am both World Leader and a server admin. Same issue as #11743

**Expected behavior:**
I should have the ability to set the field to a different currency.

**Actual behavior:**
The field does nothing as if it was a fixed setting.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed
![20190423224239_1](https://user-images.githubusercontent.com/12836572/56618000-37eceb80-6619-11e9-9dfb-08d6c7264cab.jpg)

**Comment by beastyn** [comment]
@jammie19 
Thank you for your report.
Can you provide you output_log file?
Here is an instruction https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Can't reproduce it with 0.8.1.4. If you are a leader you can change the default currency.
Please, reopen if you still has an issue and provide additional info.
