### ISSUE TITLE
Research uses plenty resources without improvement – Issue or Intention?

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12103]
V0.8.1.4
There are insane amounts of material used in research and I can not recognize an improvement the more I research.
Self Improvement is fully exhausted and no way to improve research, the only benefit is calorie consumption.
Intention ???

![research](https://user-images.githubusercontent.com/38510829/56678133-4511e500-66c2-11e9-9e5d-2cfe000ca90b.jpg)

![selfimprov](https://user-images.githubusercontent.com/38510829/56678163-4d6a2000-66c2-11e9-9bb1-742374879121.jpg)

**Comment by D3nnis3n** [comment]
Yes, the research improvement were removed with 8.0, though i liked them actually. Giving it the design label for craig to comment and close as he desires.

**Comment by WeaselDog** [comment]
Thanks for the feedback. We have an entirely new system for research in 9.0 and different specialties do reserve benefits from contributing.
