### ISSUE TITLE
[0.8.1.4] The doors are layered on each other.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12108]
1. Take two doors
2. Set them like this
![image](https://user-images.githubusercontent.com/45708377/56730654-26166000-6761-11e9-869c-c4d54886a6bb.png)
3. Open the Doors
![image](https://user-images.githubusercontent.com/45708377/56730674-33cbe580-6761-11e9-89ec-c7ccae01766b.png)

**Comment by Phlo123** [comment]
Fixed in staging.
