### ISSUE TITLE
[0.8.1.4]  House value isn't updated when a room is broken / repaired

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12106]
Step to reproduce:
1. Create a room with some furniture
![image](https://user-images.githubusercontent.com/45708377/56718685-e5f6b380-6747-11e9-8225-de390a885b96.png)
2. Break the room
![image](https://user-images.githubusercontent.com/45708377/56718860-471e8700-6748-11e9-8e87-3a9e23be07de.png)
3. Place another furniture
![image](https://user-images.githubusercontent.com/45708377/56718984-877e0500-6748-11e9-9369-eac21faffd8a.png)
4. Repair room
![image](https://user-images.githubusercontent.com/45708377/56719108-bc8a5780-6748-11e9-8de8-3927f0cb7944.png)
5. Pick up any furniture
![image](https://user-images.githubusercontent.com/45708377/56719217-fa877b80-6748-11e9-8d73-ed85b820d7aa.png)

**Comment by D3nnis3n** [comment]
Gets my tag, long standing issue that makes players insane.
