### ISSUE TITLE
[Master] Issue with Unity/Server on Visual Studio

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12102]
Since some changes in the master build you can not start the server in Visual or the game in Unity.

In Visual Studio you have this Problem:

-Debug:
![grafik](https://user-images.githubusercontent.com/37456949/56669036-d1b3a780-66b0-11e9-8825-214b105a2658.png)

-Realease: 
![grafik](https://user-images.githubusercontent.com/37456949/56669170-07589080-66b1-11e9-8225-cfe8829640ce.png)

You can fix the problem by changing the decimal sign from comma to point in the control panel from Windows
Then the Eco server starts without problems.

In Unity you have this Problem
![grafik](https://user-images.githubusercontent.com/37456949/56669446-7209cc00-66b1-11e9-836c-29fb242b6c1b.png)
 and you only hear the Sound with black Screen.

Unfortunately no solution found yet

**Comment by redwyre** [comment]
Are you also updating SVN when you pull from git?

**Comment by Sekor2600** [comment]
Github and TortoseSVN newest Data.  Have also once completely deleted everything and downloaded new

**Comment by mirasrael** [comment]
Which language are you using?

**Comment by Sekor2600** [comment]
Server starts with English. My System is German. 
I can load the Server in Visual only when i change my System here:
![grafik](https://user-images.githubusercontent.com/37456949/56688230-785f6e80-66d8-11e9-847f-77dfa776ee5a.png)
But Unity is only black Screen with Sound and in the console comes the error as shown above

**Comment by Sekor2600** [comment]
@mirasrael 
I have a new Error in Unity with the Merge from the #4297 where sfx is added.
![grafik](https://user-images.githubusercontent.com/37456949/56772205-8c2ed180-67b9-11e9-99eb-0ddbd8ba8a46.png)

**Comment by mirasrael** [comment]
@Sekor2600 Did you rebuild a server and refresh Unity files? Part of Client dependencies is coming from Eco.Shared.dll which should be build by server.

**Comment by Sekor2600** [comment]
I did refresh Unity, but i can´t start Server without the changes in the decimal symbol system. And didnt change it in the night ;D. wihout the change decimal the server hangs in CSV Problem. See Above

**Comment by mirasrael** [comment]
Yeah, it should be enough just to build Eco.Shared.dll (no need to start server)
