### ISSUE TITLE
Write a tool to scan server configs for changes

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoIssues#12109]
I can run this to check github for file changes with the configs and report it in an official release.

**Comment by D3nnis3n** [comment]
Does that really help? The delivered configs are not up-to-date nor do they contain all the config variables, they get written by the UI. For people not using the UI like me this is actually a bad thing, configs (at least the new templates) should come with all settings in it and their default values.

**Comment by D3nnis3n** [comment]
So next to this, the templates should be changed to include all available config options with their defaults and possibly even comments on what they do.

**Comment by WeaselDog** [comment]
Replaced with templates
