### ISSUE TITLE
0.8.1.4 Unbalance - Gap between eras

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12110]
**Problem:** There is a big unbalance right now, related to Tier 3-4 materials
Actually it's related also to previous versions.  I don't know if it is an intended.

**Explanation:** After iron era, steel is more and more needed. By the time the Electric Machinist table is built, there is a need for a room with higher Tier, from T2 to T3 (2.7)

_Right now the only way to build a room that meets requisites is by jumping from Tier 2 Lumber to Tier 4 Framed Glass_

_The main reason is that Corrugated Steel is T3 - BUT - the machine needed for its production only comes much later in game._ 

Firstly, all the Steel Related Machinery need to be built, installed and working (in Tier 3 buildings) to produce a working Electronics Assembly wich will manufacture a Robotic Assembly Line which will finally produce a Rolling Mill ---- the player would need to advance in so many areas, even in Oil, to get a Rolling Mill...

**Possible Solutions:** There are several ways to deal with that, from inverting Tiers (FGlass T3 and CSteel T4) to other, more elegant ones;

**Comment by craig-jong** [comment]
We have a lot of changes coming to late game tech tiers planned for a future update. We'll look into the current tiers (specifically T3) as a faster, temp fix but we'll be making larger sweeping changes to address these issues.

**Comment by SlayksWood** [comment]
Seems fixed.
You can build T3 house from Reinforced Concrete. Also, a lot of balance changes are planned in future versions.
