### ISSUE TITLE
Another Server Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12113]
> --BEGIN DUMP--
> Dump Time
> 04/23/2019 07:50:55
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Pipes.PipeEmitterObject.EmitParticles(Ray ray, Item emissionItem, Int32 avgFlow, Double burstDuration)
>    at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
>    at Eco.Gameplay.Pipes.LiquidComponents.LiquidProducerComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--
>

**Comment by D3nnis3n** [comment]
Also:

> --BEGIN DUMP--
> Dump Time
> 04/23/2019 03:21:59
> 
> Exception
> Exception: NullReferenceException
> Message:Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    at Eco.Gameplay.Pipes.PipeEmitterObject.EmitParticles(Ray ray, Item emissionItem, Int32 avgFlow, Double burstDuration)
>    at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
>    at Eco.Gameplay.Pipes.LiquidComponents.LiquidConverterComponent.OnConsumed(Type type, Int32 amount)
>    at System.Action`2.Invoke(T1 arg1, T2 arg2)
>    at Eco.Gameplay.Pipes.LiquidComponents.LiquidConsumerComponent.OnReceive(ItemStack stack)
>    at Eco.Gameplay.Wires.WireOutput.SendItem(ItemStack item, Boolean divideAmongOutputs)
>    at Eco.Gameplay.Pipes.LiquidComponents.LiquidProducerComponent.Tick()
>    at Eco.Shared.Utils.ListExtensions.ForEach[T](IList`1 list, Action`1 action)
>    at Eco.Gameplay.Objects.WorldObject.Tick()
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
> 
> --END DUMP--

**Comment by D3nnis3n** [comment]
Copied from my dump folder, occured three days ago - i cannot give reproduction steps for those unfortunately, as they just happen when i'm not there. If you cannot find the cause for one of those (though you found all of them yet), feel free to just close.

**Comment by mirasrael** [comment]
Seems like a duplicate for https://github.com/StrangeLoopGames/EcoIssues/issues/11719
