### ISSUE TITLE
USER ISSUE: Stockpile tree

### ISSUE THREAD

**Issue by ddd365Rocks** [StrangeLoopGames/EcoIssues#12120]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. fill a stockpile with dirt.
2. wait for a tree to spread onto the dirt.
3. empty stockpile.

**Expected behavior:**
the tree should dissapear

**Actual behavior:**
it stays floating

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by D3nnis3n** [comment]
Duplicate of #6902
