### ISSUE TITLE
Bug that teleports you to the top

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12126]
I found an issue on a server i visited today where players that stand in a specific spot - mostly between two stockpiles are teleported up to the highest natural block. I could reprdouce this in a video with flying, but it's also possible when you just stand in the space and do not dive or fly into it. The complete mine there is full of such black hole spots. It's an enerving issue for the owner and should be fixed.

Video: https://drive.google.com/open?id=1d8Ri1u9Sjqfjk1rbR9K1FSF_VVoy_crq

**Comment by D3nnis3n** [comment]
The whole mine is full of teleport spots, very weird.

**Comment by SlayksWood** [comment]
@D3nnis3n 
You cross Zero point (depth). Nothing is lower. Therefore, you teleport to the top (in your case).

**Comment by SlayksWood** [comment]
It is necessary to clarify that It doesn't happen for the same reason as in this issue #10345.

**Comment by D3nnis3n** [comment]
@SlayksWood I wrote that this does not only happen when you fly there, but also when you walk there. And you don't cross zero when you walk there, still it ports you to the top. The player that built this occurs this all the time and cannot fly.

**Comment by SlayksWood** [comment]
I found only way
![2019 04 29 Teleport to top](https://user-images.githubusercontent.com/45708377/56891156-36da1500-6a84-11e9-9f53-6f75c54a3aaa.gif)
But It's dup #10345.

**Comment by D3nnis3n** [comment]
Actually, walk to the blocks between the two stockpiles. If i do that, i get teleported on top.

**Comment by SlayksWood** [comment]
@D3nnis3n 
I can't reproduce it while walk between two stockpiles.
Need some more information

**Comment by D3nnis3n** [comment]
Closing for now due to not being reproduceable.
