### ISSUE TITLE
Old growths appearing out of nowhere

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12125]
Heard this reported a few times but didnt see it as a bug, unless I missed it? @SeanAtr0n

Marking medium but we should fix this for 8.2

**Comment by craig-jong** [comment]
should be fixed, but we'll have to see.

**Comment by SlayksWood** [comment]
I was able to reproduce it with /level command.
I guess old growths don't have a small model. Therefore, if they begin to grow, they immediately appear large. But you can chop it as small tree.
See video:  https://drive.google.com/file/d/1m3hZrgJhLrK8KG2zvO7qXZDe-0PO5j29/view?usp=sharing

**Comment by Deantwo** [comment]
Sounds related to #11263.
Old Growth Redwood trees aren't supposed to grow anywhere at all.

**Comment by SlayksWood** [comment]
[0.8.2.0 staging-7]
Step to reproduce:
- Select tree to chop
![image](https://user-images.githubusercontent.com/45708377/57679734-bd6e2500-7634-11e9-920b-bd1b7d86f640.png)
 - Chop Tree
![image](https://user-images.githubusercontent.com/45708377/57679765-d1198b80-7634-11e9-9263-dbd97b957f9a.png)
 - Clear spot
 - Wait near ten minute
![image](https://user-images.githubusercontent.com/45708377/57680523-7da83d00-7636-11e9-8a78-aa7746d9310b.png)
 - New "small" Old Growth Redwood appears.
![2019 05 14 Redwood](https://user-images.githubusercontent.com/45708377/57680860-366e7c00-7637-11e9-9318-ef215f18133a.gif)

It doesn't alsways happen.

**Comment by craig-jong** [comment]
Okay, okay. There's a PR open to fix this (once again) and this time I went and triple checked it.

Fast forwarded 48 hours of time, waited 10 minutes real time, and nothing new grew. If it happens again I'll be somewhat upset.

**Comment by craig-jong** [comment]
On, I should note that they'll have a weird yield percentage, but it should be okay.

**Comment by SlayksWood** [comment]
0.8.2.0 staging-8-2 still an issue. I can reproduce it.

**Comment by craig-jong** [comment]
Merge went in this morning with a change I forgot to include in my last PR - they're fully excluded from the spawning so if its still reproducible it might be a different issue.
