### ISSUE TITLE
Unclaim all Properties is Spammy

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12122]
The SeaOtter server has 585 total player, the majority of which aren't active in the world anymore. We have a periodic law that unclaims the properties of all players that have been offline for more than 8 days.

This is what happens when the law triggers:
![2019-04-27 12_18_33-Window](https://user-images.githubusercontent.com/2676134/56848281-4c660800-68e7-11e9-9719-ad57d8216693.png)
It goes on for a long time while it cycle through each player that meet the law's condition. Like a few hundred players, and each action seem to take a few seconds.

The issue is that it doesn't seem to check if those players even have any properties before attempting to unclaiming them and it gives a notification rather they had anything unclaimed or not. Seeing this notification for players that don't have any properties is just annoying.

See also: #10121

**Comment by Deantwo** [comment]
Would be nice if this notification message was sent in the "Property" channel too, rather than the "Notification" channel.

**Comment by D3nnis3n** [comment]
Removing suggestion label, this is annoying behaviour that can take up to half an hour in occuring.

**Comment by WeaselDog** [comment]
This is fixed now:
![FixedLawSpam](https://user-images.githubusercontent.com/47330823/69577454-36a2e900-0f83-11ea-9b67-37a42709615b.png)

You can hold mouse over to see who was affected and the end result.

**Comment by D3nnis3n** [comment]
How that for taxes? Would make sense, too.

**Comment by WeaselDog** [comment]
Works for taxes too and gives you a notification who could afford to pay, but this is just on an executive actions. It actually still needs to be applied to laws based on a timer that use each citizen, so it is not ready to close:

![LawTimer](https://user-images.githubusercontent.com/47330823/69579574-9f8c6000-0f87-11ea-8ec6-db4d92c6d962.png)

**Comment by olegshegai** [comment]
Yeah, I was exploring this topic today and wanted to leave a feedback later
Civics-related stuff was refactored and greatly improved by @johnkslg 
I will reassign this issue since I am not the one who fixed this issue

**Comment by olegshegai** [comment]
RE: Taxes
Taxes have some problems at the moment. And it's a case for another issue I suppose.
