### ISSUE TITLE
USER ISSUE: Cleanup Crew: Logging

### ISSUE THREAD

**Issue by biotek7** [StrangeLoopGames/EcoIssues#12124]
![Cleanup Crew](https://user-images.githubusercontent.com/32723768/56872044-49077500-69ea-11e9-85f6-10f149ae04be.png)
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Use axe to clear trunks or debris. (haven't tested higher than iron)

**Expected behavior:**
Talent states cleaning up tree debris won't use calories.

**Actual behavior:**
Calories are used as if the talent isn't selected.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Calories are used as if the talent isn't selected.

**Comment by SlayksWood** [comment]
fixed in 8.2 #11093
