### ISSUE TITLE
USER ISSUE: road tool bug

### ISSUE THREAD

**Issue by ddd365Rocks** [StrangeLoopGames/EcoIssues#12121]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. grow a tree
2. use a road tool under the tree

**Expected behavior:**
it should not work

**Actual behavior:**
the tree dissapears and the road is made, however the roots from the tree are still present making the road under the tree invincible

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

**Comment by SlayksWood** [comment]
dup #10550
