### ISSUE TITLE
0.8.1.4 Login info could not be verified. Our auth servers may be down.

### ISSUE THREAD

**Issue by Angel2022** [StrangeLoopGames/EcoIssues#12136]
Not sure why unable to connect to any servers.  Username: Angel2020
User ID: slg129108

<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

Log File:
Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   
    VRAM:     8079 MB
    Driver:   25.21.14.2531
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.577600 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename:  Line: 275)

Connecting to 89.163.231.54:1001...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 101882.
Total: 288.061200 ms (FindLiveObjects: 10.598700 ms CreateObjectMapping: 6.785600 ms MarkObjects: 270.369000 ms  DeleteObjects: 0.307400 ms)

Connecting to 185.175.139.114:3020...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 102078.
Total: 291.899500 ms (FindLiveObjects: 10.980900 ms CreateObjectMapping: 9.766800 ms MarkObjects: 270.912000 ms  DeleteObjects: 0.239200 ms)

Connecting to 31.214.224.54:3500...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 102078.
Total: 336.709400 ms (FindLiveObjects: 9.618900 ms CreateObjectMapping: 6.628000 ms MarkObjects: 320.223800 ms  DeleteObjects: 0.238100 ms)

Connecting to 120.148.59.7:33001...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Curved/Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mobile/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert' - Pass 'Meta' has no vertex shader
Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Packet parsing error: Value cannot be null.
Parameter name: key from 120.148.59.7:33001
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteError(LocString)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 21856 unused Assets to reduce memory usage. Loaded Objects now: 86568.
Total: 320.632700 ms (FindLiveObjects: 9.593100 ms CreateObjectMapping: 13.285700 ms MarkObjects: 259.934500 ms  DeleteObjects: 37.819300 ms)

Connecting to 47.50.185.235:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 103828.
Total: 354.686000 ms (FindLiveObjects: 10.831100 ms CreateObjectMapping: 6.624900 ms MarkObjects: 336.937600 ms  DeleteObjects: 0.291800 ms)

Connecting to 97.84.4.67:33000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 105899.
Total: 434.012900 ms (FindLiveObjects: 7.167200 ms CreateObjectMapping: 5.448400 ms MarkObjects: 421.083300 ms  DeleteObjects: 0.313400 ms)

**Comment by Angel2022** [comment]
not anymore. had the link undone on eco account. fixed the problem.

**Comment by mirasrael** [comment]
Ok. Thanks!
