### ISSUE TITLE
FPS Degrading Issue

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12133]
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3129901/DxDiag.txt)
[output_log (2).txt](https://github.com/StrangeLoopGames/EcoIssues/files/3129902/output_log.2.txt)

Video: https://youtu.be/MSQo7Q53SRc
Video 45 Minutes later: https://youtu.be/jIuT6DACb1E

"The framerate is shown in the bottom left corner, via the Nvidia overlay. There are a couple of major drops though not nearly as bad or as frequent as an extended play session (1-2 hours). I've seen it drop all the way to 10 fps, though it's usually 15-25 fps. Restarting the game clears up performance issues for a short time in most cases.
Thanks for letting us submit info/experiences. Hope it helps."

This is an intel 6 core machine with a good 980 TI. It should manage better fps from the view of players that can reach fps numbers near the hundred in other recent major games.

**Comment by mirasrael** [comment]
Should be improved in 8.2
