### ISSUE TITLE
Meteor is invisible

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12146]
![image](https://user-images.githubusercontent.com/3536496/57037380-e68dbf00-6c0b-11e9-8501-e1c6081e9625.png)

![image](https://user-images.githubusercontent.com/3536496/57037358-d4ac1c00-6c0b-11e9-8bc5-2289b5c3daa8.png)
Used to be lots more visible, something changed with its rendering.

**Comment by keegan-o** [comment]
Upped the min alpha to make it more visible.
