### ISSUE TITLE
USER ISSUE: Create world

### ISSUE THREAD

**Issue by Goddessa39** [StrangeLoopGames/EcoIssues#12143]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
New game
Tried to play a personal server
8 minutes on loading stuff
bugged at what was supposed to be the end after a few "allow access" popups.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Comment by beastyn** [comment]
@Goddessa39 please, provide server log files. 
Here is an instruction https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

Thank you for your report.

**Comment by D3nnis3n** [comment]
Closing for no response, feel free to reopen when you can provide us with the necessary information.
