### ISSUE TITLE
[0.8.2 bleeding] Excavator digging is strange

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12142]
I don't even know how to explain.
Sometimes its hard to dig. Seems like the bucket is on the ground with a sharp edge, but even with left button holded its not digging, like.. more stucking.
https://drive.google.com/file/d/1ZchgkQiEXMiWeagkGdHWYqFE5R5AUwB5/view?usp=sharing
And it is still jangling
https://drive.google.com/file/d/15aHRS1xGOLWmeztBDQEcRAOBb1oWh436/view?usp=sharing

**Comment by Sekor2600** [comment]
Excavator is really strange trembling when you use digging mode.
Excavator fixes (#4413) included

**Comment by SlayksWood** [comment]
0.8.2.0 staging-5
Excavator shakes in digging mode
![2019 05 10 Excavator](https://user-images.githubusercontent.com/45708377/57510500-aadfad00-730f-11e9-8700-4bc9b4df8173.gif)

But it doesn't fixed:
![image](https://user-images.githubusercontent.com/45708377/57510356-3efd4480-730f-11e9-9c48-bbbf54537fba.png)

**Comment by mirasrael** [comment]
Flying excavator is part of another issue (which wasn't fixed). Trembling fixed.
