### ISSUE TITLE
Plants disappear after their collection effect happens.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12147]
![animx](https://user-images.githubusercontent.com/3536496/57037717-cad6e880-6c0c-11e9-9b47-9b705f23e799.gif)
They should disappear the same moment.

**Comment by SeanAtr0n** [comment]
seems like prefab builders should change more quickly

**Comment by johnkslg** [comment]
The same problem is noticed if you dig under a plant, it sits visible for a moment before disappearing.

**Comment by SlayksWood** [comment]
Seems fixed.
