### ISSUE TITLE
Broken tool background

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12149]
Sometimes after replacing it with another (repaired) tool - red background stays on tool slot:

![image](https://user-images.githubusercontent.com/3536496/57039569-df69af80-6c11-11e9-95ff-61b6a148b5a4.png)

**Comment by SlayksWood** [comment]
0.9.0 staging-1183 Still an issue
![image](https://user-images.githubusercontent.com/45708377/67568359-ae87b480-f734-11e9-95af-4e73a961b0c9.png)

**Comment by elfl0rd** [comment]
![error](https://user-images.githubusercontent.com/4980243/41867186-04129f04-78bb-11e8-82f9-e7b74230253d.gif)
e.g. these happens if you have tools in backpack and you change broken on the fly.

**Comment by SlayksWood** [comment]
Now it got worse. Another step to reproduce:
- take any tool:
![image](https://user-images.githubusercontent.com/45708377/79225218-13f76b00-7e65-11ea-9d45-a59a79460601.png)
- break it:
![image](https://user-images.githubusercontent.com/45708377/79225361-430ddc80-7e65-11ea-82b2-ef068b68a5d7.png)
- repair it:
![image](https://user-images.githubusercontent.com/45708377/79225409-515bf880-7e65-11ea-810e-55c01351bc86.png)
-move to slot 1(in the same slot):
![image](https://user-images.githubusercontent.com/45708377/79225465-69337c80-7e65-11ea-8783-015a8c197c9d.png)
- select slot 2:
![image](https://user-images.githubusercontent.com/45708377/79225484-70f32100-7e65-11ea-96b1-050ea79c853b.png)
- hoe with full durability has red background.
- if I use it one time it become blue but after selecting another slot it'll become red again.
So:
![image](https://user-images.githubusercontent.com/45708377/79225605-aa2b9100-7e65-11ea-9a02-82ac30d590bf.png)

**Comment by SlayksWood** [comment]
Seems 2 bugs with red highlight are fixed.
But still have wrong blue background in broken tool:
> When your inventory is full, and you drag a tool into it that has a red background due to being dead, it'll change it back to the normal blue background before placing it back in the chest you were dragging it from.
> 100% reproduceable.
> 
> Easy to replicate, I'm not currently in game. Drag a broken tool from a chest into your inventory when your inventory is full. The tool will return to the chest and now have a blue background, but still be broken.
> 
> The other reports all reference a healthy tool getting a red background. So the exact opposite :)
> 
> It's probably a similar cause, though, somehow losing the colour status when shifting things around.
> 
> Broken tool in Chest
> ![npnlkdh](https://user-images.githubusercontent.com/4980243/52897862-bb88f700-31e8-11e9-89a2-9c88f2055eee.png)
> 
> Inventory Full
> ![hb3fvk2](https://user-images.githubusercontent.com/4980243/52897875-bd52ba80-31e8-11e9-8686-138028d35272.png)
> 
> Broken tool in Chest with blue background after trying to drag into full inventory
> ![w2xevcy](https://user-images.githubusercontent.com/4980243/52897878-bfb51480-31e8-11e9-9d05-d6273c1a6785.png)

**Comment by SlayksWood** [comment]
Tool has right background, but you can broke another items background:
![image](https://user-images.githubusercontent.com/45708377/80452933-fe3b7880-892f-11ea-95b8-30befdfdc27d.png)
![2020 04 28 Item background](https://user-images.githubusercontent.com/45708377/80453123-51adc680-8930-11ea-9e1c-0c2eac825cb0.gif)

**Comment by SlayksWood** [comment]
Still has another way to broke item background (but sometimes it isn't work, try several times):
![2020 05 05 Broken tool background](https://user-images.githubusercontent.com/45708377/81037891-eecaab00-8eac-11ea-9c0d-e21a52491de5.gif)
If I move non-broken tool on broken tool then broken tool blinks like it just broken a few seconds ago.

**Comment by gzatravkin** [comment]
After #6044 it should not show pulsation on not borken tool. Stil shows pulsation when you selecting broken tool on broken tool (by design as I think, since it remarks that user can't use this tool)
