### ISSUE TITLE
Make spawn point change depending on nearby wild food 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12153]
- Every X minutes, check for nearby wild food on unauthed land near spawn within radius Y. If there is less than Z plants, move the spawn point.
- When moving, check for clusters of food and spawn near them.  
- Make this configurable via a config option, if servers want a static spawn point.

**Comment by johnkslg** [comment]
Some tips on this one:
- Check out EcoSim.PlantSim.PlantsWithinRange as a way to find nearby plants
- Add the code to do the nearby-food check to one of the threaded plugins.  
- If it cant find wild food, it can retry random land positions a few times. 
- Use PeriodicUpdate to make it check on a timer.
- For bonus points, make the 'match' score of the server drop when no food locations can be found, and display it in the server browser settings.

**Comment by D3nnis3n** [comment]
Implemented a while back.
