### ISSUE TITLE
Make leaves not visible till they pop in on minmalloader

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12154]
![image](https://user-images.githubusercontent.com/3536496/57046209-966f2680-6c24-11e9-8147-0fc6da2c09df.png)
Small thing but makes a big difference!

**Comment by redwyre** [comment]
Turns out this is actually in the black mask image, for some reason it's more visible here than looking at the image directly. I'll pass this on to art as I don't have the tools to fix this (I tried and made a mess of it)

**Comment by redwyre** [comment]
milenko has fixed the image and I've updated it from master
