### ISSUE TITLE
Stuck at Loading World 2% (5.5.1)

### ISSUE THREAD

**Issue by Komogi** [StrangeLoopGames/EcoIssues#1215]
Disconnected from the server I was playing on as I thought it was lagging. After attempting to reconnect, the loading screen got stuck at Loading World 2%. After disconnecting and trying again multiple times (all failed attempts), I tried closing and relaunching the game, which didn't fix the problem. I then got a fresh download of the game (deleted the old game files and extracted new ones) and that didn't solve the problem either. 
(At the time of writing this post, loading screen has been stuck at Loading World 2% for 5 minutes) 

<img width="799" alt="world loading 2 bug" src="https://cloud.githubusercontent.com/assets/26584899/24282860/709e8648-1038-11e7-91a8-9af3cad4cd35.png">

**Comment by Komogi** [comment]
Update 1: Still stuck on the Load World 2% after 15 minutes, decided to disconnect and connect again. Game froze and then somehow I managed to get into the server. However, the chat function was not working. (Empty chat box and unable to see anything typed)

<img width="798" alt="world loading 2 bug part 2" src="https://cloud.githubusercontent.com/assets/26584899/24283344/93852290-103b-11e7-9827-c6662e3d4b57.png">

**Comment by noblackthunder** [comment]
Question : could you try to delete your game data by going to C:\Users\USERNAME\AppData\LocalLow\Strange Loop Games and deleting the eco folder and then start the game and logging in again ? see if that resolves the chat issue?

**Comment by Komogi** [comment]
The chat issue has been fine ever since Update 3, game hasn't froze since then either.

**Comment by metachronism** [comment]
2% is after the first update from the server, which always takes longer than normal.  depending on connection speed to the server itself, you might be at 2% while it downloads the rest of the world
