### ISSUE TITLE
extend tree occupancy for new trees

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#12163]
tree occupancy currently assumes all trees are cedar or birch... could use an update and should handle giant redwoods
![image](https://user-images.githubusercontent.com/774628/57116613-196aac80-6d0b-11e9-9a37-c727294b304f.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/72498504-93fb3e00-3840-11ea-8985-d9052f99b3d7.png)
