### ISSUE TITLE
[0.8.2 staging2] Stone block mesh is not disappearing after mining

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12168]
[0.8.2] no mods
It gappens quite often.
1. Mine
2. See the rubbles but mesh is still there, untargetable
![stone_mesh](https://user-images.githubusercontent.com/27898520/57136181-6d39cc00-6dc5-11e9-8050-1d3e3819e691.gif)

**Comment by beastyn** [comment]
Mybe related to #11487

**Comment by mirasrael** [comment]
Seems like a problem related to chunk updates. Also happens with dirt and sand.

**Comment by SlayksWood** [comment]
Also happen with building blocks
![2019 05 06 Building block mesh](https://user-images.githubusercontent.com/45708377/57225128-1f66d300-7014-11e9-9268-ef44d27428c0.gif)

**Comment by mirasrael** [comment]
@metachronism it seems related to latest chunk builder changes

**Comment by D3nnis3n** [comment]
This is blocking QA progress, therefore giving critical until fixed.
