### ISSUE TITLE
[8.2.0 Bleeding Edge] Cannot load game

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12164]
1. Press Load Game
2. Try to load my cycle 7 Game.eco
3. Nothing happens, as if i didn't click anything.

**Comment by beastyn** [comment]
I've loaded cycle-7 from game menu without any problems.
Let's look at your logs @D3nnis3n ?

**Comment by D3nnis3n** [comment]
Works now, closing out.
