### ISSUE TITLE
USER ISSUE: lietajuca Budova

### ISSUE THREAD

**Issue by Fenix1984** [StrangeLoopGames/EcoIssues#12167]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Ked davam suroviny do skladu nieje ich vidiet zobrat sa daju aj vlozit len chyba pri animacii a ori bludeni svetom lietajuca budova :D

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by beastyn** [comment]
@Fenix1984 Thank you for your report.
Can you provide screenshots or video? I didn't quite get what problem is.

**Comment by beastyn** [comment]
Didn't get additional info, close for now.
Feel free to reopen if something comes up
