### ISSUE TITLE
[0.8.2 -bleeding] Scaling bug with crafting tables UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12162]
This is 93% Interface scale with Sawmill.
I can't see some numbers.
![bandicam 2019-05-02 14-34-18-303](https://user-images.githubusercontent.com/27898520/57067197-c16e7e80-6ce7-11e9-9579-c4df913fa461.jpg)

**Comment by redwyre** [comment]
@mirasrael possibly the same issue as the icon spacing you fixed?
