### ISSUE TITLE
[0.8.2 staging2] Seems to lose some languages

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12165]
Not sure, but I suppose there should be more languages? 
We need to use Gibberish for testing for example, and brazilian for example.
![bandicam 2019-05-03 14-41-47-875](https://user-images.githubusercontent.com/27898520/57130039-bb44d480-6db1-11e9-8c2c-bd5684672484.jpg)

**Comment by mirasrael** [comment]
Gibberish is only in Unity Editor and Debug mode.

**Comment by Spydarlee** [comment]
We were hoping to allow QA to use Gibberish mode to track down loc bugs. Any thoughts on how best to go about that, @mirasrael? And do you know why certain languages (such as Brazilian) are only enabled in Debug builds as well? Are they not officially supported yet?

**Comment by mirasrael** [comment]
@Spydarlee I don't know why. I guess you're right, they are not supported officially yet. I just seen than in code. Better to ask @johnkslg

**Comment by beastyn** [comment]
@johnkslg we need to decide something with hidden languages. For example Brasilian Portugues and maybe something else.
