### ISSUE TITLE
[0.8.2- staging2] Tab in text field in chat

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12166]
[0.8.2] no mods

When you first time type a command and then use Up arrow to repeat it, tab is appearing before text line
![bandicam 2019-05-03 15-41-39-606](https://user-images.githubusercontent.com/27898520/57132828-36aa8400-6dba-11e9-908e-ebd55062bdc6.jpg)
![bandicam 2019-05-03 15-42-26-586](https://user-images.githubusercontent.com/27898520/57132831-38744780-6dba-11e9-9589-bab2985d9b03.jpg)

**Comment by SlayksWood** [comment]
Seems fixed in 0.9.0.

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/70798612-73ab1000-1db8-11ea-9d5a-9fd9ebfbfc4f.png)

**Comment by madpingui** [comment]
Tested on unity editor develop branch
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/95987dad-b454-484e-90f9-844d384b3fed)

**Comment by TwixterZ** [comment]
fix tested and confirmed in 9.4 develop 252
