### ISSUE TITLE
[0.8.2 Staging] Strange Sealevel from Pollution

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12178]
The flooding looks very strange. 
Must say i did it in fastforward and with the AC Pollution objects
![flood](https://user-images.githubusercontent.com/37456949/57185717-d3f7dc00-6ed0-11e9-856d-58983a925f66.JPG)

**Comment by SlayksWood** [comment]
Flooding occurs strangely in places where places with hollows are formed.
At first, such places are filled, although they do not yet have access to water. They fill up immediately to the full depth and it looks strange.
https://drive.google.com/file/d/1ISCkozShrIo_ezLG4w8WLRo8-mE_8tUY/view?usp=sharing

**Comment by D3nnis3n** [comment]
This is a regression though as this did not happen in 7.6 when our world was flooded.

**Comment by mirasrael** [comment]
@SlayksWood Is it still and issue on latest?

**Comment by mirasrael** [comment]
Tied on 9.0. It has temporary level changes, but because of chunk loading. As soon as chunks loaded it has correct level. It may have steam affect after loading, but it is an another issue.
