### ISSUE TITLE
[0.8.2 Staging] Invisible Stores

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12175]
You can´t see the Stores. Spooky! Ghostshops 
![store](https://user-images.githubusercontent.com/37456949/57185688-5c29b180-6ed0-11e9-8ada-7429b9a85e39.JPG)
![store2](https://user-images.githubusercontent.com/37456949/57185689-5f24a200-6ed0-11e9-8c24-5b9bf7398bae.JPG)

**Comment by SlayksWood** [comment]
possibly merged with #12168

**Comment by beastyn** [comment]
@Sekor2600 Can you provide saves and logs for this one, please?

**Comment by Sekor2600** [comment]
https://drive.google.com/open?id=1RikQAwHSDBvV6U9gtEM9USU-f54BVbsD

here is the World. But where do i find the logs from the Unity version?

**Comment by beastyn** [comment]
Servers are in the same place in Unity folder-Server, but lets skip them for now. I think save will be enough.
Thank you, we can't repro with staging build.

**Comment by beastyn** [comment]
@Sekor2600 I see only db file there, can I get save too? )

**Comment by Sekor2600** [comment]
Ups xD sry https://drive.google.com/open?id=1D3b5ft32lw1j-xMTUVaVYkUfpjNATUop

**Comment by beastyn** [comment]
Great, thanks!

**Comment by beastyn** [comment]
@Sekor2600 Do you see the store after reloading?
I have the store in that building with last staging build.

**Comment by Sekor2600** [comment]
@beastyn no did restart Unity too with all reimport but Store stays invisible

**Comment by Sekor2600** [comment]
@beastyn have found the Error. The Store.meta data wouldn´t load. Did download the Art data new
