### ISSUE TITLE
Title Holder can't be a Title or Demographic

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12173]
I can add "World Leader" as title appointer, but I can't do it for title holder.

![image](https://user-images.githubusercontent.com/2676134/57178073-b8a6b580-6e6b-11e9-92e8-886d63c03ef8.png)
![image](https://user-images.githubusercontent.com/2676134/57178077-c4927780-6e6b-11e9-94e4-7332c7291690.png)

I guess this may prevent some circular logic, but with #12172 being an issue it might be an issue anyway.

**Comment by D3nnis3n** [comment]
Considering there is great use for titles that automatically hold other titles to make lawmaking easy, this should be possible.

**Comment by SlayksWood** [comment]
Need to check with the new civic system

**Comment by johnkslg** [comment]
@SlayksWood I believe works, can you check and close if so?

**Comment by SlayksWood** [comment]
Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/69054843-7fa3ec00-0a1d-11ea-8b58-6ef90388c414.png)
