### ISSUE TITLE
Vertex Normals on Tree Stump Don't Match Trunk

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12176]
Some from the Trees have strange stripes  (The Redwood, Fir and Spruce)

![Tree1](https://user-images.githubusercontent.com/37456949/57185701-84b1ab80-6ed0-11e9-88c9-801247c0e525.JPG)

**Comment by keegan-o** [comment]
fixed in develop for 9.1, also fixed Palm. ![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/65c9d398-e930-4ebb-b3d6-3892f7463858)
