### ISSUE TITLE
[0.8.2 Staging] Chattags are borken

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12177]
Chat is buggy and you don´t see any Chattags
![chat](https://user-images.githubusercontent.com/37456949/57185705-a448d400-6ed0-11e9-8beb-85d2737bac22.JPG)
![chattag](https://user-images.githubusercontent.com/37456949/57185706-a6ab2e00-6ed0-11e9-914e-8c20016279e0.JPG)

**Comment by beastyn** [comment]
@Sekor2600 do you have thie issue after art updating?

**Comment by Sekor2600** [comment]
@beastyn I will look later. Did not pay attention because of the time yesterday

**Comment by Sekor2600** [comment]
@beastyn The Chattags are now back there. Have now version staging a4ee734e-4. but the rest of the ui is still broken. #12211 this Error

**Comment by SlayksWood** [comment]
0.8.2.0 staging-5 still an issue.
1.  Step to reproduce:
 - Start new world
 - Welcome chat is absent.(It's one time of 15 happens).
 - Restart game is fixed it
![image](https://user-images.githubusercontent.com/45708377/57518824-a1137500-7322-11e9-9358-d9a8ac9111e6.png)
2. Dropdown button in hidden chat overlap
![image](https://user-images.githubusercontent.com/45708377/57519533-32371b80-7324-11e9-934a-df641ef7473a.png)

**Comment by SlayksWood** [comment]
0.8.1.4:
![image](https://user-images.githubusercontent.com/45708377/57838999-79af2300-77ce-11e9-9885-eaa34a74c879.png)
Hidden should be at left side
