### ISSUE TITLE
Title Appointers are also Title Holders

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12172]
![image](https://user-images.githubusercontent.com/2676134/57178004-a710de00-6e6a-11e9-93a5-38e98a8efaee.png)
![image](https://user-images.githubusercontent.com/2676134/57178013-b8f28100-6e6a-11e9-88e8-8398befa6295.png)

Even while I am only listed as a Title Appointer, I am still affected by this law. I am guessing this is a bug, because what else would the point be of me being able to add myself as both appointer and holder?

Alternative would be to make us able to check if people are "Appointer", "Holder" or "both" in laws, but that seems like overkill.

**Comment by D3nnis3n** [comment]
Actually, this breaks a feature, giving high.

**Comment by johnkslg** [comment]
@Quadbro currently all checks for 'holder' will include 'appointer'. Need to split this out so its not a strict subset.  Make sure it works for various cases.   Also do same for bank account.

**Comment by beastyn** [comment]
@johnkslg for consulting

**Comment by mirasrael** [comment]
Checked. Already fixed in 9.0.
