### ISSUE TITLE
Some times world gen makes weird strips of the wrong biome...

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#1217]
![image](https://cloud.githubusercontent.com/assets/5872141/24305979/1287c6b6-107c-11e7-95e3-63c3844ff79e.png)

This may just be a small-planet issue. That is where I tend to see it the most.

**Comment by metachronism** [comment]
I dont think this is worth spending any time on

**Comment by craig-jong** [comment]
I don't think this is worth it unless it start appearing on larger worlds.
