### ISSUE TITLE
[0.8.2 st 3] Can't use voice chat

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12185]
1. Voice chat is working with open mic
2. With V I have this window
![bandicam 2019-05-06 14-21-43-177](https://user-images.githubusercontent.com/27898520/57216813-5df79000-700a-11e9-92aa-2cd2c7eaf351.jpg)
3. I see an indicator when talking
4. But my partner does't hear me
5. If I you Push to talk mode indicator won' show anything when T is on,
6. Kirill has an empty window
I am using a steam auth, Kirill is using steam-slg auth

Log
[log_190506100547.log](https://github.com/StrangeLoopGames/EcoIssues/files/3147337/log_190506100547.log)
:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3147335/Player.log)

**Comment by redwyre** [comment]
This is fixed in the latest version
