### ISSUE TITLE
shards and alpha backer items being made available for sale and trade in larger numbers due to logout and log in replacing missing alpha backer items

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12183]

**Comment by pamduncan** [comment]
It's been reported that apparently shards are once again either spawned in by admins (as well as other alpha rewards) or being placed in shops for sale (which is fine) but when they log out with a shard gone and log back in they get a new shard (which should not happen as the supposedly if you give away the alpha items you get when you start a new world they are not given back to you again when you log out and back in again).  This is been reported as its being used to as high level sale and trade and upsetting a few communitie and that the stock is easily replenished by just a number log outs and in and placing the item up for trade or sale and then repeating that to increase stick.,.  Just asked to let you know

**Comment by TwixterZ** [comment]
This is now fixed as of 9.5 version. @pamduncan sincere apology it took us so late to get back to you on this.
