### ISSUE TITLE
[0.8.2.0 Staging-3] Cell values have small size.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12187]
Step to reproduce
1. Spawn mint or distribution station (maybe something else).
2. Use it. Displayed small size value.
![image](https://user-images.githubusercontent.com/45708377/57215107-a3a95e00-6ff4-11e9-996c-621059f78b34.png)
![image](https://user-images.githubusercontent.com/45708377/57215336-334f0c80-6ff5-11e9-8fc9-9bd3c765607e.png)

3. When you changed it, cell value are normal size.
![image](https://user-images.githubusercontent.com/45708377/57218594-5e8a2980-6ffe-11e9-8da4-7e1cf71d64a9.png)
![image](https://user-images.githubusercontent.com/45708377/57219359-7e225180-7000-11e9-9c88-beccb98dd1be.png)

4. After time it will be small again.
![image](https://user-images.githubusercontent.com/45708377/57218574-4f0ae080-6ffe-11e9-9168-ba4dd15a37ff.png)
![image](https://user-images.githubusercontent.com/45708377/57219411-ac079600-7000-11e9-9af6-5dc4180e44d9.png)

**Comment by SlayksWood** [comment]
0.8.2.0 staging-7 still an issue.
![image](https://user-images.githubusercontent.com/45708377/57679479-1a1d1000-7634-11e9-8a78-535a141ac840.png)
![image](https://user-images.githubusercontent.com/45708377/57679490-20ab8780-7634-11e9-82cb-39bcdee357ab.png)
![image](https://user-images.githubusercontent.com/45708377/57679503-2903c280-7634-11e9-82a2-5ac506c78b74.png)
![image](https://user-images.githubusercontent.com/45708377/57681483-75510180-7638-11e9-96f5-798a3faf4b79.png)

**Comment by beastyn** [comment]
and in contracts too
![bandicam 2019-05-14 16-12-33-560](https://user-images.githubusercontent.com/27898520/57693672-3a17f800-7663-11e9-90e0-54c97676316d.jpg)

**Comment by Quadbro** [comment]
Fixed that issue in editor => saved new prefabs, and all is okay in editor... Strongly think that  issue is TMP related, but probably that can a layout bug (cause if we call Layout rebuild on topm all will be fixed, but it's a heavy operation).... if someone played with layouts recently - please, let me know if you changed smth, cause i do not know how to make them work on actual builds, not only in editor...(

**Comment by Quadbro** [comment]
added spedial fix for all quantity selectors, hope it's enought. We'll see if unity  adds some fixes in next tmp updates
