### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by Xandoria** [StrangeLoopGames/EcoIssues#12184]
I participate in the French translation and I noticed that there were several words missing on Crowdin:

In Environment Data on the minimap:
Moisture
Nutrient
Plant group
Yield potential for every plants

In Parameters on the minimap:
Misc
Sign
Research
Lights

**Comment by Xandoria** [comment]
I don't mean that the translation has not been made, I mean that the translation is impossible to make because those words don't appear at all in the files.

**Comment by beastyn** [comment]
Minimap still missing:
![bandicam 2019-05-13 16-16-20-736](https://user-images.githubusercontent.com/27898520/57617551-7d5a6400-759a-11e9-8767-178e0a9b9ea5.jpg)
![bandicam 2019-05-13 16-24-21-952](https://user-images.githubusercontent.com/27898520/57617990-99123a00-759b-11e9-86b6-937e15cca823.jpg)
