### ISSUE TITLE
[0.8.2.0 Staging-3] Bug with the display of Wainwright Table

### ISSUE THREAD

**Issue by Xandoria** [StrangeLoopGames/EcoIssues#12186]
![f6a4750c8ff7ed0e31372d2b76acd231](https://user-images.githubusercontent.com/26251843/57218739-680f9380-6ff6-11e9-89f3-6934544ba53a.png)

The Wainwright Table icon display works if the serveur and client are in English.
When French is selected, the Wainwright Table icon display is bugged (see first sentence in the chatbox of this screenshot).

**Comment by Spydarlee** [comment]
Are you still seeing this on latest, @Xandoria? It seems to be working for me locally. Unless it's a more specific scenario that's failing than the one I'm testing..

![image](https://user-images.githubusercontent.com/553695/57530100-6e6f7980-732e-11e9-9b2f-8c55af7394c5.png)

**Comment by Xandoria** [comment]
Yes:

![eeb631a7b1fddfb4ccd22ae8137f44ea](https://user-images.githubusercontent.com/26251843/57582766-f6898680-74c8-11e9-8e65-61a1dd82b334.png)

 and it seems that it affects also the farmer table:

![c0728924ad271169fabde9122b9df04f](https://user-images.githubusercontent.com/26251843/57582769-fab5a400-74c8-11e9-8641-b37dd8a1aed9.png)
