### ISSUE TITLE
Suggestion: filtering box for items in the sales & purchase list window

### ISSUE THREAD

**Issue by Xandoria** [StrangeLoopGames/EcoIssues#12191]
Could you please add a filtering box in the Y window, so that I can find more easily the items I would like to purchase. That list can be very long.
(Could you localize the filtering box so that I can search the French name of the item?)

**Comment by Nicolausi113** [comment]
...or a sorted list by vendor and categories

**Comment by Ser-Geeves** [comment]
Made a suggestion about shop improvements over here: 
https://github.com/StrangeLoopGames/EcoSuggestions/issues/807
Maybe a good idea to link these two posts.

**Comment by D3nnis3n** [comment]
This already exists, click this button:
![filter](https://user-images.githubusercontent.com/25908592/57272373-bde64900-7093-11e9-8237-4edd0d3f87ed.png)
