### ISSUE TITLE
Players are replaced by hashes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12197]
We had that issue earlier, occured a few times in the last days with people:
https://cdn.discordapp.com/attachments/573468165565317130/573482550140600340/unknown.png
https://cdn.discordapp.com/attachments/573468165565317130/573482708274249728/unknown.png

World Save:
https://1drv.ms/u/s!AvwJCLbue_vMg90eMS-RiNQ9AaQqaw

I give it high priority, as it would have been one of these cases for semi-high. It destroys usability quite a bit.

**Comment by FlyNeko48** [comment]
Same issue https://drive.google.com/file/d/1ofz2HwExTfxBqd5G9mZFVy1MRuRmAdGv/view?usp=sharing

**Comment by mirasrael** [comment]
This issue happens when on server Require Authentication set to `False` and Steam user joins the server. I'm going to remove this option, it was never intended for end user usage.

**Comment by FlyNeko48** [comment]
Is it possible to fix it in existing save file?

**Comment by mirasrael** [comment]
Unfortunately I don't know a way. Probably we should add command for admins which removes the user (out of scope of this task).
