### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by haker9001** [StrangeLoopGames/EcoIssues#12193]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Comment by D3nnis3n** [comment]
Please update to the newest version of Eco and open a new issue if this reoccurs.
