### ISSUE TITLE
[0.8.2 staging 3] Missing Sleep tutorial icon

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12199]
![bandicam 2019-05-07 11-20-31-849](https://user-images.githubusercontent.com/27898520/57278548-2cd99700-70c0-11e9-8404-2abd9996c9e2.jpg)

**Comment by johnkslg** [comment]
@mirasrael you fixed this one didnt you? Maybe needs merging into staging branch

**Comment by SlayksWood** [comment]
0.8.2.0 staging-5 fixed.
![image](https://user-images.githubusercontent.com/45708377/57530039-070df580-733f-11e9-94a8-38e2448d5374.png)
