### ISSUE TITLE
Crash related to garbage

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12196]
This issue requires hotfixing (if 8.2 is not totally around the corner), as players that occur that can no longer drop garbage without crashing.

Player told me that he used Shift Click Moving to drop several stacks at once, this caused him to now have a item in the garbage can at all times that he can't take and whenever he tries to drop some item, he crashes.

Picture:
![2019-05-07_06_20_16-Eco](https://user-images.githubusercontent.com/25908592/57271750-ff292980-7090-11e9-98af-969b112ae3ba.png)

Logfile:
[Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3150791/Crash.txt)

**Comment by D3nnis3n** [comment]
Three people on the offical servers seem to have this issue as of now.

**Comment by mirasrael** [comment]
Problem is in clause `Drop Garbage where Item is Garbage`. You should remove `where Item is Garbage` and then it won't crash anymore. I'll fix this in staging because there are workaround.
