### ISSUE TITLE
Spooky Tooltips appear above chat window

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12194]
(v0.8.1.4)
If hovering with mouse in the marked area above chat window, spooky tooltips appear not belonging to any visible object, but only if chat window is active.

![spooky](https://user-images.githubusercontent.com/38510829/57238205-20562f80-7029-11e9-9951-8e4cbe6a23e1.jpg)

![spooky2](https://user-images.githubusercontent.com/38510829/57238214-28ae6a80-7029-11e9-9eff-0f96b39ff124.jpg)

**Comment by Quadbro** [comment]
Fixed in current master
