### ISSUE TITLE
USER ISSUE: Bugs..

### ISSUE THREAD

**Issue by NGaming** [StrangeLoopGames/EcoIssues#12202]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Wenn man mit dem Kran Erde zerstört, bleibt das Graß mitten in der Luft stehen und enfernt sich nicht automatisch.

**Expected behavior:**
Beim abbauen der Erde sollte das Graß sich automatisch mitenfernen.

**Actual behavior:**
Graß bleibt in der luft stehen

**Do you have mods installed? Does issue happen when no mods are installed?:**
Graß bleibt in der luft stehen

**Comment by SlayksWood** [comment]
Fixed in 8.2 #11660
