### ISSUE TITLE
Exception in RemoveUnusedVertices where vertex and normal arrays are different sizes

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12209]
![image](https://user-images.githubusercontent.com/431728/57316384-0572e080-7139-11e9-98c0-9ea8028d200b.png)

**Comment by mirasrael** [comment]
They should never be different size. Probably fixed in https://github.com/StrangeLoopGames/Eco/pull/4441. Fill free to re-open if it happen again.
