### ISSUE TITLE
[0.8.2.0 staging-3] Excavator takes items from stockpile without LMB

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12207]
Excavator takes items from stockpile when it start digging near stockpile.
![2019 05 07 Exca and stockpile](https://user-images.githubusercontent.com/45708377/57305413-b782bc00-70e9-11e9-9c6f-1f7e85ef009d.gif)

**Comment by mirasrael** [comment]
Not able to reproduce. Did you press LMB? If so then it is intended behavior, you can pick up from stockpile with LMB.

**Comment by SlayksWood** [comment]
No, I don't press LMB
