### ISSUE TITLE
[0.8.2.0 Staging-3] Small Oak - visual bug.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12200]
![image](https://user-images.githubusercontent.com/45708377/57288082-84c4cd80-70c1-11e9-82f6-33405cfb4abb.png)
![image](https://user-images.githubusercontent.com/45708377/57288141-9e661500-70c1-11e9-86fd-b01a76fbf1c9.png)

If you move a little It disappears.
![image](https://user-images.githubusercontent.com/45708377/57288178-ade55e00-70c1-11e9-9ae8-0fb8e370ac3c.png)

**Comment by keegan-o** [comment]
Please type /time 12 next time, so we can better see what's going on, thanks!

**Comment by SlayksWood** [comment]
@keegan-o 
![image](https://user-images.githubusercontent.com/45708377/57547080-7ea34b00-7366-11e9-8df4-c7d6e68281d7.png)

**Comment by keegan-o** [comment]
fixed in master (9.0) and staging for 8.2.
