### ISSUE TITLE
Eco 8.2 Staging-4 UI broken and stuck inside the ground

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12211]
With this Version you have no Chat (only the Chatwindow with c) or other Ui except the right one always has in the beginning.
![grafik](https://user-images.githubusercontent.com/37456949/57323028-3e915d80-7105-11e9-9f0b-aa958ca5a03a.png)
![grafik](https://user-images.githubusercontent.com/37456949/57326760-81573380-710d-11e9-869b-52f49beaab94.png)
![grafik](https://user-images.githubusercontent.com/37456949/57326945-ef9bf600-710d-11e9-8a3d-20669982dbff.png)

With a new World when you have no Toturials and you're frozen in place. no wdsa or other move,
Your stuck inside the ground
And no Character Creation Window.

Unity has this Error:
![grafik](https://user-images.githubusercontent.com/37456949/57321949-b4e09080-7102-11e9-9492-e08f3f960ffd.png)
![grafik](https://user-images.githubusercontent.com/37456949/57321963-bc079e80-7102-11e9-999b-599c6dfacfda.png)
![grafik](https://user-images.githubusercontent.com/37456949/57321977-c4f87000-7102-11e9-81a8-7b3f6d6332e9.png)
![grafik](https://user-images.githubusercontent.com/37456949/57322016-d772a980-7102-11e9-999a-2cf6f65ae448.png)
![grafik](https://user-images.githubusercontent.com/37456949/57322046-f07b5a80-7102-11e9-9c2b-e9e7a67c6201.png)

**Comment by beastyn** [comment]
@Sekor2600 did you have issue after updating the branch? Its OK for me in staging branch

**Comment by Sekor2600** [comment]
@beastyn Sry but i can´t test the current staging. https://github.com/StrangeLoopGames/Eco/pull/4390
did change the Auth. I did change the Auth back to normal in the Data but the Server crashed.
![grafik](https://user-images.githubusercontent.com/37456949/57463534-43781d80-727b-11e9-89bf-ca64e2801a77.png)
from Microsoft Visual 2017 
![grafik](https://user-images.githubusercontent.com/37456949/57463588-60acec00-727b-11e9-8098-b6922477dbd0.png)

cant test this till fix^^

**Comment by beastyn** [comment]
@Sekor2600 Are you rebuilding server first after updating the branch?

**Comment by Sekor2600** [comment]
@beastyn yes but whit the old Auth link in common.cs the server is crashing and with devauth i can´t log in

**Comment by beastyn** [comment]
@Sekor2600 can you login to Stuffed Elk?

**Comment by Sekor2600** [comment]
@beastyn don´t see the Stuffed Elk Server. Maybe you need the Devauth and then i can´t log in the Game^^

**Comment by beastyn** [comment]
@Sekor2600 don't thinks its the case. Well, make the new issue then. Don't see the Elk either. FYI It uses bleedeing _day version for now

**Comment by Sekor2600** [comment]
@beastyn so thanks to redwyre i can once again test ;D 

No Staging is in version -5 an Ui is back again!
