### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by kocty228** [StrangeLoopGames/EcoIssues#12214]
**Version:** 0.8.0.7 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Ошибка подключения
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Ошибка подключения
```

**Comment by SlayksWood** [comment]
@kocty228 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the newest game version and reopen if this reoccurs.
