### ISSUE TITLE
Ramp placement making Yogscast curse our name

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12213]
https://www.youtube.com/watch?v=pDn_u7EgPxk&feature=youtu.be&t=3169

**Comment by johnkslg** [comment]
Tagged 8.2 but thats probably optimistic...

**Comment by D3nnis3n** [comment]
You just need to prevent ramps being able to be placed partially.

**Comment by johnkslg** [comment]
That sounds quite easy!

**Comment by metachronism** [comment]
dupe of #10554

**Comment by D3nnis3n** [comment]
Copied issue state to the other issue, closing this for dup as mentioned by meta.
