### ISSUE TITLE
[0.8.2.0] Steel Shovel dissapered in 3d view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12217]
0.8.1.4:
![image](https://user-images.githubusercontent.com/45708377/57366852-83aea180-7190-11e9-8084-328d204c2f7f.png)

0.8.2.0 staging-3:
![image](https://user-images.githubusercontent.com/45708377/57367362-85c53000-7191-11e9-9748-6e58856af715.png)

**Comment by SeanAtr0n** [comment]
just tried and I see a shovel, do you have to do something specific to trigger the issue?

**Comment by SlayksWood** [comment]
@SeanAtr0n 
Shovel appeared in the new build 8.2.0 staging-4
There was nothing to do. Only one shovel did not show, and not only me.
Seems fixed.

**Comment by SlayksWood** [comment]
It's my bad. I confused Steel Shovel and Modern Shovel.
![image](https://user-images.githubusercontent.com/45708377/57430694-2cb0d700-7239-11e9-9532-a282ee31376b.png)

**Comment by SeanAtr0n** [comment]
fixed in svn for 8.2
