### ISSUE TITLE
Foliage quality option doesn't work as intended.

### ISSUE THREAD

**Issue by DaleTernes** [StrangeLoopGames/EcoIssues#12210]
In my case changing value of this slider leads to actual draw distance change of grass and other objects (animals and vehicles for example).

We have to do something with this behaviour. 
Or at least call this slider 'Objects draw distance and quality'.

Foliage quality 20
![20](https://user-images.githubusercontent.com/16364624/57317189-faa45580-7110-11e9-8ba5-64f0db858586.jpg)

Foliage quality 40
![40](https://user-images.githubusercontent.com/16364624/57317190-faa45580-7110-11e9-851c-73b281145cb7.jpg)

Foliage quality 90
![90](https://user-images.githubusercontent.com/16364624/57317191-fb3cec00-7110-11e9-8ebd-531315feb559.jpg)

Graphics settings page
![settings](https://user-images.githubusercontent.com/16364624/57317565-d39a5380-7111-11e9-8de1-4bd881834503.jpg)

**Comment by metachronism** [comment]
this is exactly intended.  it affects the quality of the foliage... keeping things at higher quality at longer range.  its not just draw distance

**Comment by DaleTernes** [comment]
A usual player doesn't care how QualitySettings.lodBias actually work.

He is seeing this: "Foliage quality".
If he has low-spec device he will try to move that slider down in order to increase fps.
But he might not notice that his render distance was shrunk too.
And even a tooltip on this slider is silent about the side effects.

Also, why foliage quiality affects animals? 
Intended too?

Eric, please, set your "Foliage quality" to a minimum value and try to hunt animals.

I was actively playing the game with this setting on minimal value for 2 weeks, because I didn't know how "Foliage quality" really works. 
And I want other players to avoid these sufferings.

**Comment by elfl0rd** [comment]
It also applies to animals, but no information about this behavior.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/68854725-b7452800-06ed-11ea-9438-7a04821ccc0a.png)
