### ISSUE TITLE
Stone Brazier takes quite a while to give out more light after being Fueled

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#12226]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Place a Stone Brazier Underground, Place 20 Logs into power tab, wait at least 10 seconds for more light to appear

**Expected behavior:**
expected to get the Full appearance of light

**Actual behavior:**
have to wait for the secondary light to appear

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods

![snap4379](https://user-images.githubusercontent.com/29383891/57383903-88328480-71a7-11e9-939f-8c6cc8b7f98a.png)
Above is placed Stone brazier before Putting in Fuel of 20 Logs
![snap4381](https://user-images.githubusercontent.com/29383891/57383985-a8624380-71a7-11e9-909f-88f2f5e3773e.png)
Logs Placed into Brazier as Power
![snap4382](https://user-images.githubusercontent.com/29383891/57384025-bca64080-71a7-11e9-9cd1-35c685dd9a32.png)
Finally After about 10 Seconds (this is varying in length of time have measured this up to 18 seconds till this light appears)

**Comment by Conchipedia** [comment]
also tried this above ground, the time till secondary light effect took 7 seconds, not sure if the deeper i go effects how long till i get Full lighting

**Comment by Conchipedia** [comment]
![snap4383](https://user-images.githubusercontent.com/29383891/57384452-8fa65d80-71a8-11e9-9c36-3c184ce352cc.png)
it doesn't matter on depth, the left Brazier took 7 seconds to light, the right 10 seconds.

Server Greenleaf  9 players online of a possible 162

**Comment by D3nnis3n** [comment]
I assume this has to do with the update rate of lighting, as here: https://github.com/StrangeLoopGames/EcoIssues/issues/11763

It was mentioned this won't be fixed, so i'm closing this out.

**Comment by Conchipedia** [comment]
yes that sounds the same problem, wasn't sure what i was specifically looking for in Githubs so as not to duplicate so understand the link and closure
