### ISSUE TITLE
multiple equips

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#12228]
![image](https://user-images.githubusercontent.com/774628/57413965-093f4b00-71ab-11e9-9443-38d9962ab23f.png)

no relevant errors in log file

**Comment by craig-jong** [comment]
I did it by dropping the items to garbage, but I managed to do it earlier without doing that by using the command /dump

**Comment by SeanAtr0n** [comment]
no, i just wanted a nice palette of colored tags

**Comment by SlayksWood** [comment]
0.8.2.0 staging-8-2 still an issue
![image](https://user-images.githubusercontent.com/45708377/57833163-1919e900-77c2-11e9-85eb-72b230843a7a.png)

**Comment by mirasrael** [comment]
лопотяпка

**Comment by SeanAtr0n** [comment]
how did you reproduce it?

**Comment by seccombew** [comment]
Please reopen with reproduction instructions.

**Comment by SlayksWood** [comment]
I wrote instruction here: #12219

**Comment by SlayksWood** [comment]
Step to reproduce:
- choose tool 1.
- take the tool from inventory and move to cell tool 1.
- get not displaying of tool.

When changing to another tool, tool will not be displayed.
If you move tool from inventory at toolbar, It will be fixed.
If you switch to the first-person mode during a glitch and then back to the third-person mode, the tool change animation will break.
Video: https://drive.google.com/file/d/12cETP-8MZVGlCJNp4CE651nBr28nbJOh/view?usp=sharing

**Comment by beastyn** [comment]
0.8.2 staging-12
with Kirill's steps. Firing from fish pole )
![multitool](https://user-images.githubusercontent.com/27898520/58168444-b1730a80-7ca7-11e9-95ad-8f062983e867.gif)
