### ISSUE TITLE
[0.8.2 staging -3] Mining sound glitching

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12220]
no mods

**Steps**
1. Hit granite stone with stone axe one time
2. Hit another stone with axe
3. Then hit the first one

With stone destruction there will be doubled sound.

https://drive.google.com/file/d/1PaIHkr2VhZRaUVjIbphFcImKPPSGQzM7/view?usp=sharing

**Comment by WeaselDog** [comment]
No longer an issue in 9.0 staging
