### ISSUE TITLE
[0.8.2.0 staging-4] Scroll Bar works incorrect in species tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12234]
1. In fact, he is in a different place.
![image](https://user-images.githubusercontent.com/45708377/57428940-27e92480-7233-11e9-8be5-615c1925cced.png)
2. Inverted axis. When you drag up, the scroll moves down; drag down - moves up.
![2019 05 09 Scroll Bar](https://user-images.githubusercontent.com/45708377/57429281-371ca200-7234-11e9-850a-0272eee83ca6.gif)

**Comment by D3nnis3n** [comment]
2. Should probably based on OS, given Mac Users are known to that.

**Comment by SlayksWood** [comment]
@D3nnis3n
I don't use scroll wheel, I use scroll bar. It's working incorrect in all OS

**Comment by SlayksWood** [comment]
Scroll bar doesn't work. But scrolling is implemented with the help of holding the LMB

**Comment by Quadbro** [comment]
was fixed already, closing
