### ISSUE TITLE
USER ISSUE: dirt roots

### ISSUE THREAD

**Issue by knightfall1300** [StrangeLoopGames/EcoIssues#12232]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**

**Expected behavior:**
the dirt should have came up

**Actual behavior:**
the dirt said the roots were to strong even though there are no stumps

**Do you have mods installed? Does issue happen when no mods are installed?:**
the dirt said the roots were to strong even though there are no stumps

**Comment by D3nnis3n** [comment]
Dup of https://github.com/StrangeLoopGames/EcoIssues/issues/10550 / https://github.com/StrangeLoopGames/EcoIssues/issues/11552
