### ISSUE TITLE
[0.8.2.0 staging-4] Overlap text in the store window

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12235]
When you open the store window first time Text overlay occurs.
![image](https://user-images.githubusercontent.com/45708377/57432392-689a6b00-723e-11e9-802c-279f18c30d89.png)
If you resize window it will be ok.
![image](https://user-images.githubusercontent.com/45708377/57432648-1574e800-723f-11e9-9bed-5c4537c0b509.png)

**Comment by beastyn** [comment]
[0.8.2 staging -6] 
Now the store UI looks like this
(currency description has gone out of the window)
![bandicam 2019-05-13 15-25-08-152](https://user-images.githubusercontent.com/27898520/57615007-12a62a00-7594-11e9-95fb-e027d9f99120.jpg)

**Comment by Quadbro** [comment]
Gibberish test mode breakes text layout... On usual translations without "_" all seems to be ok. Text-meshPro treats "_" as layout tags on plain text sometimes

**Comment by SlayksWood** [comment]
It's same in English with long name.
![image](https://user-images.githubusercontent.com/45708377/57688212-966c1f00-7645-11e9-8901-bc5aa1ad610b.png)
![image](https://user-images.githubusercontent.com/45708377/57688419-0da1b300-7646-11e9-895c-38c6c188b587.png)

**Comment by beastyn** [comment]
@Quadbro we still need some fix (
![bandicam 2019-05-20 13-57-47-584](https://user-images.githubusercontent.com/27898520/58009157-4559a080-7b07-11e9-8a56-5c428016f6ad.jpg)
