### ISSUE TITLE
Some needed items missing in game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12231]
![image](https://user-images.githubusercontent.com/3536496/57417213-72798b00-71b8-11e9-88de-53f82fc99050.png)

**Comment by johnkslg** [comment]
@D3nnis3n can you reach out to this user and see if they were playing in an old world? This should be impossible since v8.

**Comment by D3nnis3n** [comment]
Can you link me to the review? That review is not shown for me in the recent reviews or the review list, neither when "Only Your Languages" and "Steam-Buyer" is off. It's just not there. The only review on May 2 i can see is a turkish one liner i have answered.

**Comment by SlayksWood** [comment]
Sometimes worlds are generated without any species.
dup #11533
