### ISSUE TITLE
Solve Overlapping Minimap Text Issue

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#1223]
![](https://cloud.githubusercontent.com/assets/3536496/24222193/7e5f22d6-0f0e-11e7-93ee-d170e098b93d.png)

Set a max # of text fields to display, if there are more than that display none (unless you're at maximum zoom). Make text push apart so that they don't overlap.

**Comment by NafenX** [comment]
I feel as though the text labels aren't really necessary, if the map iconography is recognisable enough and the tooltip shows the name/owner of the thing you hover over anyway

**Comment by metachronism** [comment]
some ideas
- move text off to the sides, with lines from the text boxes going to the location of the thing on the map
- dont show text at all (icons still overlap quite a bit)
- group items together that are on the same property, then just show name of the property. show list on an expanded toolip

**Comment by MarjieAVolk** [comment]
Sweet; I'm all for no text, since tooltips give you all that info.  I like the idea of rooms having tooltips for crowded icons too

**Comment by SeanAtr0n** [comment]
guess this is fixed, no more text
