### ISSUE TITLE
Voice Chat UI feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12230]
![image](https://user-images.githubusercontent.com/3536496/57415165-009d4380-71b0-11e9-909d-769d6eba3fab.png)

- [ ] Make 'Voice Chat' a header
- [x] Make Voice Mode a radio button with labels and put it on the right side.  You might need to make a new control type for this.
- [x] Make a box labeled 'Voice Users' with a border and list the users there.  Make sure this box handles unlimited numbers of users properly.
- [ ] Move 'Voice Chat' to 'Voice Volume'. Rename Music and SFX to Music Volume and Sound Effects Volume.
- [x] Move speaker and microphone to be on top-right of screen. Make sure I can see the user speaking's name

Connect with @Quadbro if you need help with UI layout stuff it can be a bear.

**Comment by SlayksWood** [comment]
If you select "Off", then it will broke text changing
![2019 05 10 Voice mode](https://user-images.githubusercontent.com/45708377/57522786-c2c52a00-732b-11e9-952d-3746bb5fddb3.gif)

**Comment by redwyre** [comment]
Ah yeah, it breaks if you change it when not in a game
