### ISSUE TITLE
[0.8.2 staging-5] Tuna is in the rivers

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12247]
check PR 4265

Tuna is in the rivers

![bandicam 2019-05-10 15-08-03-073](https://user-images.githubusercontent.com/27898520/57519815-9f9f7800-7335-11e9-8652-68b268b6ef2f.jpg)

**Comment by SlayksWood** [comment]
Looks like a problem with the definition of rivers and lakes.
![image](https://user-images.githubusercontent.com/45708377/57920834-a897c880-78a4-11e9-8fce-6b9b17a77c6c.png)
Same world
![image](https://user-images.githubusercontent.com/45708377/57920796-9584f880-78a4-11e9-932c-99ef44271114.png)

**Comment by WeaselDog** [comment]
Fixed this awhile back when doing the fish populations
