### ISSUE TITLE
Meteor animation sequence problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12242]
- [ ] Bars visible on left and right of animation
- [ ] Zoom isnt centered on meteor
![image](https://user-images.githubusercontent.com/3536496/57477099-ca61d180-724c-11e9-8fcf-318540c1047d.png)
- [ ]  Pacing could be faster

**Comment by SlayksWood** [comment]
@johnkslg 
Meteor is located visually in wrong position.
merged with #10978, #11957

**Comment by WeaselDog** [comment]
@tuha263 Can you see if this is fixed with recent meteor tutorial improvements?

**Comment by tuha263** [comment]
@WeaselDog Yes, this is fixed in this PR https://github.com/StrangeLoopGames/Eco/pull/6893
