### ISSUE TITLE
String "Oil" used on 2 different position.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12248]
copied from #9555

**Comment by mirasrael** [comment]
It requires different string tables

**Comment by Sekor2600** [comment]
Maybe Petroleum? This is what you pumps with the Pumpjack.
Or oil resources?

**Comment by elfl0rd** [comment]
> Petroleum

Already exist as resource.
Also we have same issue with Lumber (block and speciality).

**Comment by Sekor2600** [comment]
Yes but but petroleum is what you get out too. 
You could use mineral oil

**Comment by elfl0rd** [comment]
Oilfield?
Maybe something really like "Mineral Oil"?
![изображение](https://user-images.githubusercontent.com/4980243/68808304-811a9080-067a-11ea-8470-ef5feff33c85.png)

@beastyn technically it is fixed... but...

**Comment by WeaselDog** [comment]
In my opinion Oil should be reverted back Oil and the oil for cooking should be renamed Cooking Oil

**Comment by beastyn** [comment]
we have our dear @craig-jong for it )
I think, Oil Filed(two words) is quite fitting here. Or Oil Deposit.
