### ISSUE TITLE
[0.8.2 Staging-6] Dirtramp pickup with vehicle

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12256]
You can pickup the Dirtramp with the Excavator or the Skid.
But the Excavator is dangerous with Autopickup from the new Controls.
You do not get a ramp back but 1 Dirt.

**Comment by Quadbro** [comment]
Do you mean new "all ramp at once" pickup?

**Comment by Sekor2600** [comment]
Yes the scoop pickup the complete ramp but you ony have 1 dirt baxk
