### ISSUE TITLE
[0.8.2.0 staging-6] Tutorial Improvement

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12259]
![image](https://user-images.githubusercontent.com/45708377/57566430-045ddf80-73d5-11e9-8ee5-57aee101ad9e.png)
If you move Starter Camp to another cell, then the arrow will still hang at the first cell.
![image](https://user-images.githubusercontent.com/45708377/57566434-193a7300-73d5-11e9-97db-0e91577b8270.png)
Tutorials need to fix: Setting Up Camp, Getting Equipped, Claiming Land, Construction,

**Comment by gabrielgindridev** [comment]
The player can also move the item to backpack (and the backpack can be hidden), so instead of the arrow follow item, we can just dismiss it if the player moves the item

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2024
