### ISSUE TITLE
hitting '/' to start typing a chat command no longer adds a '/'

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#12254]
in master, not sure about other branches

**Comment by DaleTernes** [comment]
Tested today. Can't reproduce.

**Comment by SeanAtr0n** [comment]
looks like its not an issue in staging, did you try master?

**Comment by DaleTernes** [comment]
Yes, I've tried master.
May be I'm missing some details? 
How excactly I can reproduce that? 
If I press 'Enter' and then press '/' - I see "/" printed.

**Comment by SeanAtr0n** [comment]
press '/' without pressing enter

**Comment by DaleTernes** [comment]
> press '/' without pressing enter

This had no effect on my laptop with external keyboard.
Fixed that too.
