### ISSUE TITLE
USER ISSUE: Failed to connect [Hosted Worlds]

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#12257]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
log into a running  world hosted through ECO Hosted Worlds
world223.eco.hw.sfo2.do-slg.com

**Expected behavior:**
connect

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by mirasrael** [comment]
Do you still have this issue? I was able to connect to the world.

**Comment by chopperprop** [comment]
Well I will try again this evening as I never have been able too  connect what is the world name you connect to
I have changed it from earth builders to earth sim several times but it keeps changing back to earth builders which is ok as I shut down the other server

On May 13, 2019, at 05:44, Alexander Bondarev <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you still have this issue? I was able to connect to the world.

**Comment by D3nnis3n** [comment]
Closing this out, if the issue reoccurs, feel free to open a new issue.
