### ISSUE TITLE
[0.8.2.0 staging-6] Foods Tutorials glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12260]
Forage for Food tutorial and Food tutorial.
1. When you harvest plant Tutorials don't appear. Reload fixes it.
![image](https://user-images.githubusercontent.com/45708377/57566850-b13a5b80-73d9-11e9-8b3b-3b6b1683b82c.png)
![image](https://user-images.githubusercontent.com/45708377/57566875-f6f72400-73d9-11e9-9adf-3445ffa0ad3b.png)
2. Forage for Foods tutorial doesn't apper after restart tutorials  when yoy hungry to work.
![image](https://user-images.githubusercontent.com/45708377/57566928-a633fb00-73da-11e9-8e0e-1aa12de0eb90.png)

**Comment by Quadbro** [comment]
Already fixed my mirasraels fix
