### ISSUE TITLE
Meteor Tutorial appear when you connect to world without Meteor.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12262]
You must add an alternative tutorial or remove it when you connect to world without Meteor. But if you remove You can't see video.

**Comment by D3nnis3n** [comment]
That's just the same kind of bug like it ever displays that the meteor will take 30 days to impact, no matter what is configured. Probably merge those issues together into an issue for "Context-Sensitive Tutorials" or something.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/9130
