### ISSUE TITLE
[Beta 8.1.4] Stone/Ore Rubble physics messed up when more than one player is nearby.

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12265]
It seems that physics calculation on every nearby client causes multiple physical inputs on rubble. They start to fly around magically. Likely enhances lag / server load.

**Comment by SeanAtr0n** [comment]
probably related to rubble centers being wrong

**Comment by SlayksWood** [comment]
Stones become better behaved, but sometimes there are still dances
