### ISSUE TITLE
USER ISSUE: Huckleberry Glitch

### ISSUE THREAD

**Issue by Junkyshell** [StrangeLoopGames/EcoIssues#12275]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Find a huckleberry bush
Collect the huckleberries

**Expected behavior:**
Given me huckleberry seeds around 45% of the time

**Actual behavior:**
Has given me huckleberry seeds once, in all 38 hours of play time.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Has given me huckleberry seeds once, in all 38 hours of play time.

**Comment by Nicolausi113** [comment]
I observed this too and it depends somehow on grad of maturity and not only for huckleberries.
Some plants can be harvested if not 100% mature but yield at least is one, in this case it will give no seeds. My experience is to wait for 100% mature and then wait some extra time.

**Comment by D3nnis3n** [comment]
Seems like working as intended, but make sure that its working on full grown plants.

**Comment by Junkyshell** [comment]
D3nnis3n how do I check if it's mature?

**Comment by Nicolausi113** [comment]
you need a Soilsampler

**Comment by SlayksWood** [comment]
8.2.0 staging-983
1.Plant 100 Huckleberries
![image](https://user-images.githubusercontent.com/45708377/59013736-6e866a80-8843-11e9-981e-c346dcfbfbf8.png)
2. Fastforward for 100% Maturity
3. Pick huckleberries with current yield = 2. I harvest 200 Huckleberries and only 7 Huckleberries Seed
4. Fastforward for 100% Maturity
5. Pick huckleberries with current yield = 3. I harvest 300 Huckleberries and 20 Huckleberries Seed (
always given 2from bush). 10% chance to harvest 2 seed from huckleberry bush. For the indestructible plants is enough.

Wild Huckleberries bush in new world have current yield = 3. So for craft Farming Skill book you need to harvest near 30 time.
I have 42 Huckleberries in new world. But you can harvest one huckleberry bush 30 times.

Let's compare with tomatoes:
Pick 100 tomatoes with current yield = 2. I harvest 200 Tomatoes and 14 tomato Seed.
Pick 100 tomatoes with current yield = 3. I harvest 300 Tomatoes and 24 tomato Seed.
I got tomato seeds a little more than huckleberries seeds.

I think it's invented behavior.
Seems fixed or you harvest huckleberries with current yield = 1. 
Even if you don’t have a soil sampler, it’s easy to understand: If you get 1 huckleberry when you pick it up, then current potential = 1
Closed for now. If it happens again please reopen.
