### ISSUE TITLE
[Localization] Status tab

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12270]
"Status" tab isn't translated anywhere
![image](https://user-images.githubusercontent.com/45708377/57615179-c521c100-7583-11e9-94b4-c7dc5acf9a23.png)
![image](https://user-images.githubusercontent.com/45708377/57615065-71af7300-7583-11e9-89df-9b3f80196c14.png)
![image](https://user-images.githubusercontent.com/45708377/57614984-43ca2e80-7583-11e9-9922-7b78ca85a0d7.png)

**Comment by Spydarlee** [comment]
Do you have the server set to Gibberish as well as the client, @SlayksWood? These appear to be translated correctly for me (testing on staging).

![image](https://user-images.githubusercontent.com/553695/57626127-2dc16b80-758d-11e9-9ba0-ab870de6fb5f.png)

**Comment by SlayksWood** [comment]
Start new server.
![image](https://user-images.githubusercontent.com/45708377/57626864-75e98980-759f-11e9-9263-5c9a8f452bc9.png)
Spawn Butchery table. Select Status tab.
![image](https://user-images.githubusercontent.com/45708377/57627560-dd540900-75a0-11e9-99ca-0eb2098c6464.png)

**Comment by Spydarlee** [comment]
Ahh, you have to restart the server once you select a new language to ensure everything is correctly translated. After doing that the Server config UI (in the first screenshot) should all appear translate as well.

I believe this is known/expected behaviour, but perhaps we should add an explanation to the Language option description in the Server UI to make it clearer..

**Comment by SlayksWood** [comment]
I didn't change the language. It immediately created in Gibberish.
Restart server and open Status tab
![image](https://user-images.githubusercontent.com/45708377/57628042-d5e12f80-75a1-11e9-987f-a0caf04c4d4f.png)
What translation string  does come from the server else?

**Comment by SlayksWood** [comment]
In Russian:
![image](https://user-images.githubusercontent.com/45708377/57630077-9ddbeb80-75a5-11e9-9641-2e9f2c31b6c9.png)
Don't display "_ _"
