### ISSUE TITLE
[0.8.2.0 staging-6] Number Position

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12271]
0.8.2.0 staging-6: Stockpile, Backpack - middle; Toolbar, In arms - right
![image](https://user-images.githubusercontent.com/45708377/57617740-36647280-758a-11e9-8e30-86c85f276841.png)
0.8.1.0: All was right
![bandicam_2019-05-13_16-09-47-409](https://user-images.githubusercontent.com/45708377/57617794-5300aa80-758a-11e9-9ee7-8c1fcc317c40.jpg)

**Comment by Quadbro** [comment]
TMP is crazy a bit after 2019 update))
