### ISSUE TITLE
Inverted normals on triplanar rocky dirt?

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12274]
![image](https://user-images.githubusercontent.com/431728/57648225-4327ab80-7608-11e9-88b3-a881d4b60883.png)

![image](https://user-images.githubusercontent.com/431728/57648271-5e92b680-7608-11e9-988a-d8c18c31536c.png)

**Comment by SeanAtr0n** [comment]
yeah looks like the shader is messing up, probably some internal assumption changed

**Comment by redwyre** [comment]
This would have got fixed with the tangets issue a while back
