### ISSUE TITLE
USER ISSUE: Spiel erstellen

### ISSUE THREAD

**Issue by Patty0083** [StrangeLoopGames/EcoIssues#12277]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Neues Spiel erstellen nicht möglich

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Comment by SlayksWood** [comment]
@Patty0083 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Welche Grösse hat die Welt?

**Comment by D3nnis3n** [comment]
Closed due to no response, please open a new issue if it persists.
