### ISSUE TITLE
[Localization] Auth tab missings

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12272]
![bandicam 2019-05-13 17-10-47-546](https://user-images.githubusercontent.com/27898520/57620476-4be59680-75a2-11e9-9616-12be4d37a871.jpg)
![bandicam 2019-05-13 17-11-47-561](https://user-images.githubusercontent.com/27898520/57620480-4daf5a00-75a2-11e9-93c5-15a67c1dd4c4.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/57632899-46407e80-75ab-11e9-9281-601a205c3d2f.png)
