### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Felix28L** [StrangeLoopGames/EcoIssues#12288]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```

**Comment by Felix28L** [comment]
What to do? how to fix?

**Comment by SlayksWood** [comment]
@Felix28L 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Felix28L** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3179118/output_log.txt)

**Comment by D3nnis3n** [comment]
Closing for now due to the fix of several database issues. If this issue persists, please open a new issue.
