### ISSUE TITLE
[0.8.2 staging-8-d] Contracts: construction post disappearing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12296]
In the video
**Steps**
1. Choose clear debris
2. Click on Pick
3. Don't close Pick
4. Choose Build Room
5. Click on Pick 

**Expects**
View construction side
**Actual**
Empty window

https://drive.google.com/file/d/1ucV2i0CvJLoMCJphxaN3Ac3EpciuaVn0/view?usp=sharing

**Comment by SlayksWood** [comment]
Click pick leads to Crash
![image](https://user-images.githubusercontent.com/45708377/57902374-86388780-7871-11e9-9b62-c345fb3df44f.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3189830/Player.log)

**Comment by SlayksWood** [comment]
@beastyn has no such problems.

**Comment by SlayksWood** [comment]
It's connect with Gibberish. It's fixed
