### ISSUE TITLE
[0.8.2 -staging -7-n] Vivox is not working

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12291]
Steam-slg account 
Nothing happens with push to talk (pressing T) nor with open mic
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3180860/Player.log)
[log_190515085225.log](https://github.com/StrangeLoopGames/EcoIssues/files/3180861/log_190515085225.log)

**Comment by redwyre** [comment]
Fixed with a config change on the auth server
