### ISSUE TITLE
[0.8.2 staging-8-d] Contracts:the owner sees Accept button

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12298]
1. Create Contract
2. See "Accept" button
When you click it the error message is poping "Contractor Bank account must be set".
![bandicam 2019-05-15 15-46-46-836](https://user-images.githubusercontent.com/27898520/57770111-01daed00-7729-11e9-8afe-a70b27d788f1.jpg)

**Comment by Quadbro** [comment]
Closing for now, devs can accept their own contracts
