### ISSUE TITLE
USER ISSUE: help with lags

### ISSUE THREAD

**Issue by voldaron** [StrangeLoopGames/EcoIssues#12295]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Problem with all items like stones or wood pulps on the ground to server lags some stones just random teleports on the surface can you add a great admin command to remove them we would be happy nobody will be sad cause for example there would be at 20PM removing trash and bum no lags anymore. Cause sometimes you dont even know there are stones or pulps or items cause they are stuccked out of sights.

**Expected behavior:**
Adding admin command to remove trash.

**Actual behavior:**
Low fps 5 minutes server lag

**Comment by D3nnis3n** [comment]
There already is such a command: /clearruble [radius]

**Comment by voldaron** [comment]
man you are god. Most people dont know those commands
