### ISSUE TITLE
[0.8.2.0 staging-8] Behavior of the Elevator when cross Zero Point

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12292]
Sometimes It happens when you cross Zero point.
![image](https://user-images.githubusercontent.com/45708377/57755862-9f6af800-76fa-11e9-995f-f171cfdd87b6.png)
I think it merged with #12101

**Comment by SeanAtr0n** [comment]
this can wait til 9.0, merging is a pain now so we should defer low impact issues

**Comment by mirasrael** [comment]
Can't reproduce on latest version. Seems fixed.
