### ISSUE TITLE
Lavis perk not being accounted for in crafting tables

### ISSUE THREAD

**Issue by dutchuss2016** [StrangeLoopGames/EcoIssues#12290]
level any crafting to lvl 7 pick lavish lvl 7 +lavish =90% but the table still shows and uses the 80%

**Comment by dutchuss2016** [comment]
![image](https://user-images.githubusercontent.com/32156904/57739602-d64cf980-7679-11e9-9ba6-a92ca8642d8f.png)
![image](https://user-images.githubusercontent.com/32156904/57739619-ee247d80-7679-11e9-8dfb-3226b6c7d370.png)

**Comment by dutchuss2016** [comment]
cooking 6 with lavish should be 85% not 75%
![image](https://user-images.githubusercontent.com/32156904/57739659-16ac7780-767a-11e9-856c-ce9709bec0b2.png)

**Comment by beastyn** [comment]
@dutchuss2016 thank you for your report.
Should be fixed in 8.2
