### ISSUE TITLE
[Beta 8.1.4] New untitled districts are added on Law page, when pressing enter

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12299]
I had this error multiple times now, when I create a (complex) Law.
A new untitled district is created in the background, whilst I am not working on district related laws.

it happens when I press "Enter" after writing a number for currency.
![District Bug](https://user-images.githubusercontent.com/5678451/57770573-ecf25f80-7710-11e9-9cd5-fe454e84aaa8.JPG)

**Comment by SlayksWood** [comment]
@otting 
fill the reason

**Comment by otting** [comment]
I didn't give a reason in case it goes through ( I cant see it otherwise) but here you go.
![District Bug](https://user-images.githubusercontent.com/5678451/57771258-7d7d6f80-7712-11e9-8e3b-71f98ba8b862.JPG)

**Comment by otting** [comment]
I can also manually remove the created districts when I add a point for redefining districts.

**Comment by SlayksWood** [comment]
8.2.0 staging-8 still an issue
![image](https://user-images.githubusercontent.com/45708377/57772561-65135200-771e-11e9-9300-b06a9d12e5a3.png)

**Comment by SlayksWood** [comment]
Step to reproduse:
 - propose new law
 - start to fill law
![image](https://user-images.githubusercontent.com/45708377/57773289-5a59bc80-7720-11e9-9fdd-be7e166809c7.png)
- change "in district" for "and"
- continue to fill law
![image](https://user-images.githubusercontent.com/45708377/57773407-a147b200-7720-11e9-9f5c-819512d0e7d0.png)
- change "in district" for "item is"
- finish to fill law
![image](https://user-images.githubusercontent.com/45708377/57773513-de13a900-7720-11e9-90cb-a582270b9adc.png)
- click Propose Law
Sometimes it happen

**Comment by WeaselDog** [comment]
Thanks for the report. We have a new system for districts coming in 9.0 which should address this.
