### ISSUE TITLE
Implement a warning when a "invalid login / credentials" error is likely caused by steam auth servers

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12309]
![john](https://user-images.githubusercontent.com/25908592/57797390-a1f53e00-774a-11e9-8f57-406f3e65884a.png)

**Comment by D3nnis3n** [comment]
Also, probably tell them to try again (later).

**Comment by johnkslg** [comment]
Bumping priority on this as its hitting steam China build which is a priority.
