### ISSUE TITLE
USER ISSUE: Can't made a boards.

### ISSUE THREAD

**Issue by wannalivelike** [StrangeLoopGames/EcoIssues#12301]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Doesn't start a time of work for the boards order. I have all resources but timer doesn't start.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by SlayksWood** [comment]
Can you provide some more information?
If you can provide some screenshots: "Crafting" Tab and "Storage" Tab of table

**Comment by D3nnis3n** [comment]
Closed due to no response, if the issue reoccurs, please open a new issue and provide sufficient information.
