### ISSUE TITLE
[0.8.2.0 staging-8] Collision absents between avatar and jib arm with scoop in Excavator

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12308]
0.8.1.4:
![image](https://user-images.githubusercontent.com/45708377/57788485-da434f00-773f-11e9-8a9c-8880cf4f7ea9.png)
![image](https://user-images.githubusercontent.com/45708377/57788514-e62f1100-773f-11e9-8943-47a7682d8d12.png)

0.8.2.0:
![image](https://user-images.githubusercontent.com/45708377/57788777-5b024b00-7740-11e9-8b8e-7ac7a8baa5c5.png)
![image](https://user-images.githubusercontent.com/45708377/57788799-62c1ef80-7740-11e9-81e1-e209204e4d28.png)

**Comment by mirasrael** [comment]
Fixed in SVN
