### ISSUE TITLE
[0.8.2.0 staging-8] Inverted move jib arm of crane

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12305]
When you use "W" Jib arm moves down (I think it should move up). 
When you use "S" Jib arm moves up (I think it should move down).

**Comment by Deantwo** [comment]
Isn't this a player preference? Control settings?

**Comment by SlayksWood** [comment]
@Deantwo 
for everything else W - up; S - down.
If everything was inverted, I would not have written this. And so it turns out that the part works as it should and the crane is inverted. It should be all the same, so that later it could invert everything in the settings.
