### ISSUE TITLE
[0.8.2.0] Filter Glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12303]
Step to reproduce:
- click New Game
- click left Filter
![image](https://user-images.githubusercontent.com/45708377/57775368-87f53480-7725-11e9-8e9f-daced51c7b7f.png)
- click Apply 
![image](https://user-images.githubusercontent.com/45708377/57775386-93e0f680-7725-11e9-9503-382b5a604a45.png)
- random server will open
![image](https://user-images.githubusercontent.com/45708377/57775415-a22f1280-7725-11e9-9516-d9fab9a8d7df.png)
- press Escape two times (Go to main menu)
![image](https://user-images.githubusercontent.com/45708377/57775454-bffc7780-7725-11e9-87fc-bfc399e1171a.png)
- one more random server will be open

Video: https://drive.google.com/file/d/1XTsV2L5AKQOuT_kFE0rhxIrWhRFU6PoH/view?usp=sharing

**Comment by johnkslg** [comment]
Click is going through dialog?
Might just need 'blocksraycast' checked on the background images.

**Comment by redwyre** [comment]
This is actually caused by a bug in ToggleGroup (which is what I was fighting against when I wrote an alternate control)

**Comment by SlayksWood** [comment]
It works well. Is it finished?
