### ISSUE TITLE
[0.8.2 staging-8-d] Contracts: scrolling-out-of-window numbers

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12300]
.1. Create a contracts with a lot of cluses
2, Scroll down.
Numbers are going up
![bandicam 2019-05-15 16-21-03-497](https://user-images.githubusercontent.com/27898520/57771946-a95a1e80-772d-11e9-8b67-c590a0fcf034.jpg)

**Comment by johnkslg** [comment]
Pushing to 9

**Comment by elfl0rd** [comment]
build road clause
![изображение](https://user-images.githubusercontent.com/4980243/68433283-322ab200-01c7-11ea-9c05-fef47661be5d.png)
![изображение](https://user-images.githubusercontent.com/4980243/68433297-3b1b8380-01c7-11ea-9122-a8a3e9a467b0.png)

same with "custom clause" content
![изображение](https://user-images.githubusercontent.com/4980243/68433347-56868e80-01c7-11ea-9175-b4b538dbd285.png)

payment and deposit numbers in payment on completion contract clause
![изображение](https://user-images.githubusercontent.com/4980243/68432317-4372bf00-01c5-11ea-9726-9ae8dace03e4.png)
![изображение](https://user-images.githubusercontent.com/4980243/68432348-52597180-01c5-11ea-829b-3da1bd3c5e12.png)
