### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by vorchun09** [StrangeLoopGames/EcoIssues#12310]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Steam initialization failed with message: Steamworks is not initialized.
It may be related to one of problems described here: https://partner.steamgames.com/doc/sdk/api#initialization_and_shutdown
You can also may try to close all other Steam apps and restart client
or login with SLG account.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Steam initialization failed with message: Steamworks is not initialized.
It may be related to one of problems described here: https://partner.steamgames.com/doc/sdk/api#initialization_and_shutdown
You can also may try to close all other Steam apps and restart client
or login with SLG account.
```

**Comment by beastyn** [comment]
@vorchun09 thank you for your report
Can you provide additional information& What did you do when get this message?

**Comment by D3nnis3n** [comment]
Try to restart steam, this should fix this issue.
