### ISSUE TITLE
[0.8.2 staging-8-2] Contracts: premission bug

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12318]
**Steps**
1. Create a contract for putting 50 bricks in the stockpile
2. Ask someone to make it
3. This Someone will drive a truck with 200 bricks in it.
4. Then this Someone will open the target stockpile and put there his bricks from the truck. With Shift holded.
**Expected**
50 bricks will go to the stockpile. 150 bricks will stay in the truck
**Actual**
All the bricks are going to the stockpile

**Comment by Quadbro** [comment]
probably something is wrong with items transfer using modifiers in general( Hope there will be general fix along with distribution station

**Comment by D3nnis3n** [comment]
Closing for fixed.
