### ISSUE TITLE
[0.8.2.0 staging-8-2] Value "Max days played for citizens to be eligible" reset to basic value

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12319]
Value "Max days played for citizens to be eligible" reset to basic value "5" at Distribution station.
Step to reproduce:
- Set the value on "2".
- Leave the station and do something else (about 10 minutes)
- Go back to the station.
- Open tab "ItemDistribution"
- The value "Max days played for citizens to be eligible" is set to "5".
Don't change the value and click Apply. The message says that the value "Max days played for citizens to be eligible" is set to "2".
![image](https://user-images.githubusercontent.com/45708377/57855282-f5bb6200-77f2-11e9-8e77-0d5736e1675f.png)

**Comment by SlayksWood** [comment]
Need check after fixes.

**Comment by SlayksWood** [comment]
Seems still an issue:
![image](https://user-images.githubusercontent.com/45708377/72329684-3e028b00-36c6-11ea-9028-86906c441a1a.png)

**Comment by beastyn** [comment]
still valid
![bandicam 2020-02-10 18-08-30-738](https://user-images.githubusercontent.com/27898520/74152823-ef96cc80-4c30-11ea-8e49-d116f60a066e.jpg)

![bandicam 2020-02-10 18-11-21-327](https://user-images.githubusercontent.com/27898520/74152826-f1609000-4c30-11ea-99c0-c4c9cc7dbe63.jpg)

**Comment by olegshegai** [comment]
Fixed in some of persistent data PRs
