### ISSUE TITLE
[0.8.2.0 staging-8-2] Garbage doesn't appear.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12322]
There are no 3 stages of transformation into garbage. When time has passed garbage does not appear.
Step to reproduce:
- sleep
- /fastforward 1
- wait 4 hours
- /fastforward 0 
- wake up 
- repeat 3 times
![image](https://user-images.githubusercontent.com/45708377/57859878-76329080-77fc-11e9-95d2-418bcb925d9f.png)
![image](https://user-images.githubusercontent.com/45708377/57860076-d9242780-77fc-11e9-9846-637d93ac87da.png)
![unknown](https://user-images.githubusercontent.com/45708377/57860349-68313f80-77fd-11e9-9d07-db25948637e5.png)
![image](https://user-images.githubusercontent.com/45708377/57860739-0cb38180-77fe-11e9-818e-94c89855c592.png)

**Comment by D3nnis3n** [comment]
Reopening for another investigation due to:
![garbage](https://user-images.githubusercontent.com/25908592/60387611-1808f680-9aa6-11e9-924a-08328687a150.png)

**Comment by SlayksWood** [comment]
@D3nnis3n 
I can't reproduce. I tried some times in several server. All works right. 
Need log and if possible saved files.
![image](https://user-images.githubusercontent.com/45708377/60570459-4c1c3a00-9d7a-11e9-8e3f-8c43f9ecae58.png)

**Comment by SlayksWood** [comment]
not reproduced, so closed
