### ISSUE TITLE
Server Crash from Sea-Otter

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12324]
> --BEGIN DUMP--
> Dump Time
> 05/05/2019 16:31:06
> 
> Exception
> Exception: ArgumentOutOfRangeException
> Message:Index and count must refer to a location within the buffer.
> Parameter name: bytes
> Source:mscorlib
> 
> System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
> Parameter name: bytes
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
>    at Eco.Shared.Networking.NetMessage.DecodePacket(NetIncomingMessage message)
>    at Eco.Plugins.Networking.NetworkServer.<Initialize>b__22_0()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

As ever, feel free to find the cause and fix it, if you can't, close it given i do not have any further information, just pasting it from the dump folder.

**Comment by D3nnis3n** [comment]
A similar one to this:

> --BEGIN DUMP--
> Dump Time
> 05/01/2019 17:15:15
> 
> Exception
> Exception: Exception
> Message:Don't know elementType = 27
> Source:Eco.Shared
> 
> System.Exception: Don't know elementType = 27
>    at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeElement(MemoryStream stream)
>    at Eco.Shared.Serialization.SimpleBSON.DecodeDocument(MemoryStream stream)
>    at Eco.Shared.Networking.NetMessage.DecodePacket(NetIncomingMessage message)
>    at Eco.Plugins.Networking.NetworkServer.<Initialize>b__22_0()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

**Comment by mirasrael** [comment]
It won't cause crash in 8.2.1 if client using incompatible binary protocol. So closing it as fixed.
