### ISSUE TITLE
[0.8.2 staging 8-2] Contracts: nested contracts are broken

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12321]
**Steps**
1. Create nested contracts with parameter ANY with adding blocks clause in putting in container clause
2. Let someone took this contract

![bandicam 2019-05-16 16-26-39-396](https://user-images.githubusercontent.com/27898520/57856850-518fe600-7807-11e9-807e-c99474f428d2.jpg)

 The problems start here

1) There is no mark for putting in container part, though the container will be accessable (green highlight) And you can't put the item there
 
![bandicam 2019-05-16 16-27-10-676](https://user-images.githubusercontent.com/27898520/57856860-55bc0380-7807-11e9-8c2e-5bc108c39397.jpg)

2) You can finish the contract without cumpliting any clause.

**Comment by johnkslg** [comment]
Pushing to 9

**Comment by beastyn** [comment]
still the same
no mark and can be finished instantly
