### ISSUE TITLE
USER ISSUE: Stockpiles goes away

### ISSUE THREAD

**Issue by UltraG33k** [StrangeLoopGames/EcoIssues#12326]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Place stockpile
2. put stuff in the stockpile
3. wait
4. The stockpile dissapears but the contents is still there

**Expected behavior:**
Not dissapeared

**Actual behavior:**
It dissapears

**Do you have mods installed? Does issue happen when no mods are installed?:**
It dissapears

**Comment by SlayksWood** [comment]
@UltraG33k 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing due to no response. Please reopen if the issue reoccurs.
