### ISSUE TITLE
shadows incorrect near sunset

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#12329]
The sun is casting shadows from the wrong position near sunset, making light appear to pass through terrain:
![image](https://user-images.githubusercontent.com/774628/57897845-800fc000-780b-11e9-9898-0dd27fbede09.png)
![image](https://user-images.githubusercontent.com/774628/57897916-be0ce400-780b-11e9-925a-343440c34219.png)

**Comment by redwyre** [comment]
I made a change to the sky which might have fixed this
