### ISSUE TITLE
contribution text wrong when overflowing from one project to the next

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1233]
![image](https://cloud.githubusercontent.com/assets/774628/24324916/37ef7842-114c-11e7-9c98-199984a33961.png)

**Comment by MarjieAVolk** [comment]
What exactly is the issue?  Did Stett actually contribute to both the Road Tool Project and the Quarry Project in this case?

**Comment by SeanAtr0n** [comment]
I put in 10 boards and got that msg

**Comment by SeanAtr0n** [comment]
Also Stett ordered the first project and I ordered the 2nd

**Comment by MarjieAVolk** [comment]
Okay, is this one fixed?  Did you test it?  Or have we changed this message?
