### ISSUE TITLE
[0.8.2.0 staging-9-n] Scroll bar glitch at skill window.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12333]
1. Scroll Bar always display even If it doesn't needed.
![image](https://user-images.githubusercontent.com/45708377/57910274-8fcfe880-788d-11e9-963e-0fbc41d6cd83.png)
2. When you set small window size You can't scroll to last profession.
![image](https://user-images.githubusercontent.com/45708377/57910419-ee956200-788d-11e9-8fd1-ed343f39bbc3.png)
![image](https://user-images.githubusercontent.com/45708377/57910495-1b497980-788e-11e9-9957-bdda8ff78fdc.png)
3. Click, for example, at Oil Drilling Specialty. Scroll Down.
![image](https://user-images.githubusercontent.com/45708377/57910595-56e44380-788e-11e9-8186-032a0f97671d.png)
Click at Tailoring Profession.
![image](https://user-images.githubusercontent.com/45708377/57910690-91e67700-788e-11e9-8655-f8e5ca30d7b6.png)
Scroll bar need to set to Up.

**Comment by SlayksWood** [comment]
It was fixed only third pointer

**Comment by beastyn** [comment]
its an issue even with the new UI )
![bandicam 2020-02-10 18-04-42-893](https://user-images.githubusercontent.com/27898520/74152323-e6f1c680-4c2f-11ea-927e-07dcc6fae640.jpg)
