### ISSUE TITLE
[0.8.2.0 staging-9-n] Skill rate doesn't update

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12335]
Change Skillrate with command /skillrate or in ServerUI. It doen't update in game without reload.
![image](https://user-images.githubusercontent.com/45708377/57916667-fd831100-789b-11e9-862d-60a34667a2dd.png)
![image](https://user-images.githubusercontent.com/45708377/57916700-14296800-789c-11e9-9823-102e8d3640ca.png)

**Comment by Quadbro** [comment]
need to add some subscription to value change
