### ISSUE TITLE
Version 0.8.1.4 Disappearing tool tips/ Unable to check plant animal population

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoIssues#12330]
So when i hover over the initial population of bison a tootip comes up and when i go over to that tool tip it disappears before i can check any other populations. Right now i can not check populations of plants and animals outisde the first page. Either the too tips need to stop disappearing or we need a new way of checking populations.

**Comment by SlayksWood** [comment]
@trevelmike
Do you mean species tooltip?
![image](https://user-images.githubusercontent.com/45708377/57900602-225e9080-786a-11e9-966f-fc6dc60aadf7.png)
Collapsing tooltip will be fixed in 8.2.

**Comment by D3nnis3n** [comment]
This is fixed in 8.2.
