### ISSUE TITLE
Make the client not rebuild when eco.shared doesnt change

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12348]
Currently it does, which slows down workflow a lot as you have to stop and restart the client with every single change of the server.

This was working properly for a hot minute, then someone broke it again.

**Comment by redwyre** [comment]
In master, or staging?

**Comment by redwyre** [comment]
Ok, I was getting it in master, looks like some kind of caching issue in vs or msbuild.

I fixed it by deleting `Server\Eco.Mods\Organisms\Plants`

Probably an issue with the way visual studio handles wildcards in the project, the solution would be to write the generated mods into the mods solution (which I have been thinking about how to do).

**Comment by johnkslg** [comment]
It started behaving. Ill reopen if I can track down what's causing eco.shared to be out of date.
