### ISSUE TITLE
Error joining hosted world

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12345]
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Not enough room in inventory
  at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal (System.Boolean throwOnInvalid) [0x00264] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Gameplay.Items.InventoryChangeSet.Apply () [0x00000] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Gameplay.Items.Inventory.AddItem (System.Type itemType, Eco.Gameplay.Players.User user) [0x00010] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Gameplay.Players.User.FirstLogin () [0x0002a] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Gameplay.Players.User.Login (Eco.Gameplay.Players.Player player, Eco.Shared.Networking.INetClient client) [0x000ea] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Gameplay.Players.Player..ctor (Eco.Gameplay.Players.User user, System.Single viewDistance, Eco.Shared.Networking.INetClient client) [0x00030] in <3898716144b44c0b84d2c83c9bb02aa7>:0 
  at Eco.Plugins.Networking.Client.SpawnPlayer (System.Single viewDistance, System.String language) [0x0002e] in <cd51488a7068412bae2b9560609e0aee>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <2943701620b54f86b436d3ffad010412>:0</size>

Log File:
Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 980 Ti (ID=0x17c8)
    Vendor:   
    VRAM:     6097 MB
    Driver:   26.21.14.3064
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.422200 ms
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
Connecting to 138.197.219.209:1044...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Curved/Triplanar' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Mobile/Diffuse' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard (Specular setup)' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert' - Pass 'Meta' has no vertex shader
Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 22431 unused Assets to reduce memory usage. Loaded Objects now: 88244.
Total: 233.515800 ms (FindLiveObjects: 8.184300 ms CreateObjectMapping: 9.979200 ms MarkObjects: 182.009500 ms  DeleteObjects: 33.342300 ms)

Connecting to 138.197.219.209:1044...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
LZ4.Action:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
LZ4.Action:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 22415 unused Assets to reduce memory usage. Loaded Objects now: 88242.
Total: 258.092700 ms (FindLiveObjects: 7.286700 ms CreateObjectMapping: 8.842900 ms MarkObjects: 201.626500 ms  DeleteObjects: 40.336000 ms)

**Comment by mirasrael** [comment]
Can't reproduce in latest version. Seems fixed.
