### ISSUE TITLE
Upgrade Object Finder to work with Registrars

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12341]
ObjectFinder is the code that lets users type in the name of something and it creates a linked object in chat.  Previously this worked with boilerplate that scanned each type.  In 9.0, we can do this generically for most objects by having it scan the registrar name dictionaries.

**Comment by gzatravkin** [comment]
This was already done
![image](https://user-images.githubusercontent.com/53317567/79390730-a3c11600-7f46-11ea-90d0-76ffd3bd2540.png)
