### ISSUE TITLE
USER ISSUE: Connection Issue Light In Solo

### ISSUE THREAD

**Issue by Aviator5811** [StrangeLoopGames/EcoIssues#12340]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
None, just started occuring today

**Expected behavior:**
In solo, connection shouldn't matter right?

**Actual behavior:**
I keep getting lag in single player and the connection lag icon appears.

**Do you have mods installed? Does issue happen when no mods are installed?:**
I keep getting lag in single player and the connection lag icon appears.

**Comment by Aviator5811** [comment]
Update, I looked at the logs in the Eco\Eco_Data\Server\Logs folder, and noticed that there were tons of index errors and those errors didn't exist around a month ago before this behavior started.

**Comment by D3nnis3n** [comment]
Could you upload that log please?

**Comment by Aviator5811** [comment]
[log_190520013245.log](https://github.com/StrangeLoopGames/EcoIssues/files/3204467/log_190520013245.log)

**Comment by Aviator5811** [comment]
That's the most recent log, the issue is pretty easily repeatable on my end so if you want screen grabs or anything, let me know.  The game acts fine till I try to make any change (break something, pick something up, put something away, etc.), then I get lag as if I was connected to a server with really bad ping.  This is all solo on my end.

**Comment by mirasrael** [comment]
Hi @Aviator5811 
How big is your .db file? Do you use SSD or HDD disk for Eco server?

**Comment by D3nnis3n** [comment]
Closed for no response. Please open a new issue when this reoccurs and you have more information.
