### ISSUE TITLE
5.5.1 Item Stacks cant split them ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1234]
I was not sure if this was implemented let or not some other on server said they had no issues with item stack splitting and some people said it was hit or miss, I having issue as shown below on all items I have tried to split make trade really hard.
![trade](https://cloud.githubusercontent.com/assets/15990789/24325206/d2f51404-1161-11e7-9655-7a55d2edfbb3.jpg)

**Comment by Komogi** [comment]
Try shift clicking the item without dragging the mouse. Then the item should appear in the box, and you can move the slider around to select the amount of items you want to move. After that, drag the items in the box to another slot. That should split stacks.

**Comment by midn8t** [comment]
yah that was thing, was trying to play it like other games where u hold shift key and drag item over to split
