### ISSUE TITLE
[0.8.2.0 staging-10-n] Performance.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12357]
New World: FPS 60-180, Load Chunk - middle. But much better than 0.8.1.4
https://drive.google.com/file/d/1DaDz2P-svvXMqHIS1tqJ-vepsdhQg6BC/view?usp=sharing
Cycle-7: FPS 20-80(Low FPS in loaded places). Load Chunk - middle. But much better than 0.8.1.4
https://drive.google.com/file/d/1bcd3odBiPC-LfZaTSH3PyQ8zA8UErAXs/view?usp=sharing

 I think that's enough for release 0.8.2.0. But further improvements are still needed.

**Comment by SlayksWood** [comment]
Old Issue #12053

**Comment by SlayksWood** [comment]
If server isn't mine: FPS 40-120. Load Chunk - fast.
https://drive.google.com/file/d/1kvuayJLYGQZEl-Q_1CitbSnOaEe9QO8x/view?usp=sharing
FPS got better. But still, over time, it becomes 25-40. After restart the game, FPS becomes at some basic value and decreases with time.

**Comment by beastyn** [comment]
After reloading and driving just after that its a bit slower 
https://drive.google.com/file/d/1Y9RJuLiSoejEef0YD4m-2nUSxg7K5G5X/view?usp=sharing

**Comment by SlayksWood** [comment]
merged to #13908
