### ISSUE TITLE
[0.8.2.0 staging-10-n] Fish traps don't catch fish

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12353]
At the weekend, the server was started about 18 hours. Sometimes I logged and checked fish traps. For all the time I didn't catch a single fish.

**Comment by Quadbro** [comment]
Autogen fishtrap has no AnimapTrap component.... probably we need to edit techTree file, @craig-jong

**Comment by craig-jong** [comment]
its in the partial - they only catch fish in the rivers. I'll update the status component.
