### ISSUE TITLE
Players Unable to Connect to Server Previously Logged Into/Player Unable to Reconnect

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12351]
This was happening a few versions ago and I guess it was resolved then as there has not been this issue until 8.1.4 but again we are getting players that have been on a server and either disconnect or are kicked due to an error.  I can understand the ones that get kicked this happening to but unsure why its happening to those that log out normally.

The player then tried to log back into the server and gets to about 6% or so and drops to the menu and they have found that they cannot gte in unless the server is restarted.  The other things that will get them back in is that they run a cache on the client files on steam or if the admin sees then still logged in in the Network display in the serverUI and does a kick command (which also works on some servers that teh admin does not have a server UI sometimes the kick command tried first is all that is needed)

Not every time is the player still shown as connected but it all appears to be the same issue as the server restarted would definitely drop any connections it still has and a file verification on local files has steam send a generic disconnect on that game to clear any connections before trying to validate the cache.  The validate cache usually finds no files that need to be acquired but it does get them in the server after it  is run  so it is handy when there is no server admin around to restart or when they don't want to keep restarting just to get a player able to log in.

**Comment by SlayksWood** [comment]
@pamduncan 
In 8.2.0 staging, a similar situations occurred. When we caught the crash and then could not connect to the server without restarting it. Several situations have been fixed that could lead to such an action.
Can you after the release of 8.2.0 provide information about such cases?

**Comment by SlayksWood** [comment]
If it happens again, please reopen and provide log file.
