### ISSUE TITLE
[0.8.2.0 staging-10-n] The sun disappears

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12358]
When sunrise (from 7 to 11 o'clock) or sunset (from 14 to 17 o'clock) The sun is disappears сompletely if part of the sun disappears from the screen
Step to reproduce:
- /time 8
- look at the sun
![image](https://user-images.githubusercontent.com/45708377/58018734-4d680f00-7b0c-11e9-8238-93714ee05af8.png)
- try to hide part of the sun
- the sun disappears.
![2019 05 20 Sun disappears](https://user-images.githubusercontent.com/45708377/58018929-e39c3500-7b0c-11e9-9a89-073fbd5bb9ff.gif)

**Comment by SlayksWood** [comment]
Same with Moon

**Comment by redwyre** [comment]
I made changes to the sky which may have fixed this
