### ISSUE TITLE
[0.8.2 stagin-10-n] Contracts: <None> is for contractor in the account by default  

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12359]
When you are accepting the contract there is no some default placement for the bank account.
Usually we have palyer account here,

![bandicam 2019-05-20 17-44-19-930](https://user-images.githubusercontent.com/27898520/58022565-25d27000-7b27-11e9-95f5-013090af782f.jpg)

**Comment by johnkslg** [comment]
Pushing to 9
