### ISSUE TITLE
[0.8.2.0 staging-11-n] Chunk updates.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12352]
Step to reproduce:
- Disconnect from server near fish traps.
- Restart Server
- Load to Server
- Not Detect Fish traps on their place. (Also on the shore)
- Move away to unload chunk
- Return to fish traps.
- Not Detect Fish trap at 993, 37, 39 (First time didn't detect two fish traps at 993, 37, 39; 8, 51,37)
- Place some block near fish trap. It will appears
Provide log and save files:
https://drive.google.com/file/d/1QeUJQ6r4E4EjK94q25L6jzh60qhpP4CT/view?usp=sharing
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3196457/Player.log)
Coordinate: 14, 57, 40

Also see video:
https://drive.google.com/file/d/1-XP2BELbCveJIYgslmCmjvVnCt0ABMa4/view?usp=sharing

It was another issue #6556. 
Perhaps there is the same problem at depth as I have.
Fish traps constantly disappear during playing

**Comment by SlayksWood** [comment]
Invisible Stockpiles:
![image](https://user-images.githubusercontent.com/45708377/58069974-f3188e00-7b9f-11e9-9267-4e9b95d1dd3f.png)
![image](https://user-images.githubusercontent.com/45708377/58069982-fad83280-7b9f-11e9-9f20-edb766f31dea.png)
Invisible Chest and Store:
![image](https://user-images.githubusercontent.com/45708377/58070033-2e1ac180-7ba0-11e9-921c-4eb5139eddb4.png)
- Move away to unload chunk and return to objects:

![image](https://user-images.githubusercontent.com/45708377/58070235-f52f1c80-7ba0-11e9-8b5d-37d30fdd4cb7.png)
![image](https://user-images.githubusercontent.com/45708377/58070151-ab463680-7ba0-11e9-8085-83c641b15a22.png)
![image](https://user-images.githubusercontent.com/45708377/58070242-fb24fd80-7ba0-11e9-8069-cf8d018505b6.png)

**Comment by SlayksWood** [comment]
Objects appears after 3-4 minutes.

**Comment by SlayksWood** [comment]
https://drive.google.com/file/d/133NHYa9AO_bExqyg91xf_FD7vlvn5nrx/view?usp=sharing
https://drive.google.com/file/d/1mVkTvIZ4DIq2xpZ-2pUe2-wLchHjnYE7/view?usp=sharing

**Comment by beastyn** [comment]
https://drive.google.com/file/d/1xVLiTkBdf1aicAJOGR7q8b74xBRX7Xn6/view?usp=sharing

**Comment by SeanAtr0n** [comment]
Fixed this in staging, still exists in master

@mirasrael can debug or apply the changes from #4488 to master

**Comment by SlayksWood** [comment]
It became much better. But sometimes there are three second delays like this:
![2019 05 24 Update Chunk](https://user-images.githubusercontent.com/45708377/58307842-8c49dd80-7e08-11e9-8ff6-3368259c46fb.gif)
I think this is not blocking the release at the moment.

**Comment by SlayksWood** [comment]
Sometimes it happens:
![image](https://user-images.githubusercontent.com/45708377/58455879-6f284e00-812b-11e9-8873-601ebd1e846b.png)
Chunks don't load. Reload or move away are fixes it
