### ISSUE TITLE
[0.8.2.0 staging-10-n] Can't catch Tuna with Fishing Pole

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12355]
Only Trout and Salmon.
![image](https://user-images.githubusercontent.com/45708377/58001550-71175f00-7ae4-11e9-9e1a-a6ee0f322f95.png)
You can catch Tuna in 0.8.1.4:
![image](https://user-images.githubusercontent.com/45708377/58001755-116d8380-7ae5-11e9-97c2-a11605c11c22.png)

**Comment by craig-jong** [comment]
new tuna weren't tagged as fish. Fixed in SVN, so there isn't a PR for this.
