### ISSUE TITLE
AuthServer deployment unable to deleted files

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12367]
SSH: EXEC: STDOUT/STDERR from command [cd /var/sites/auth-develop; test -L latest && unlink latest; ln -s 50d92c502b3420a2eaf7c0158682cd00c22d5c53 latest; rm -rf $(ls -t | grep -E "^[0-9a-f]{40}$" | tail -n +6); sudo ./post-deploy.sh] ...
rm: cannot remove 'cf13ecf5145d57040aa51a6cba24e827d2336819/AuthServer/bin/Debug/netcoreapp2.1/AuthServer.runtimeconfig.json': Permission denied
rm: cannot remove 'cf13ecf5145d57040aa51a6cba24e827d2336819/AuthServer/bin/Debug/netcoreapp2.1/AuthServer.deps.json': Permission denied
rm: cannot remove 'cf13ecf5145d57040aa51a6cba24e827d2336819/AuthServer/bin/Debug/netcoreapp2.1/AuthServer.dll': Permission denied
rm: cannot remove 'cf13ecf5145d57040aa51a6cba24e827d2336819/AuthServer/bin/Debug/netcoreapp2.1/AuthServer.runtimeconfig.dev.json': Permission denied

etc

**Comment by mirasrael** [comment]
Should be fixed
