### ISSUE TITLE
Players getting disconnected and stuck on Entering World afterwards.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#12364]
Players reported that they were disconnected after mining or chopping trees, right when they try to pickup stones or wood and can't reconnect. The server console is not showing any errors.

Game Save:
https://drive.google.com/file/d/1tsSiWkLfHUQnjHTh2SRORMQspOJnukNy/view?usp=sharing

An dump file I keep seeing, maybe the errors are related:
https://drive.google.com/file/d/18VHNtncfi9IjMa2m_jvGze2SZ7WoWJyS/view?usp=sharing

**Comment by Phlo123** [comment]
Found the issue, it was a law that made the clients crash.
The law was made to allow players to harvest carcasses off of someone else property. I'll leave the gamesave and error message uploaded on Drive in case someone is interested in seeing exactly whats happening with that law.

**Comment by D3nnis3n** [comment]
Afaik it's not possible to do such a law yet, it will just have no effect?

**Comment by Phlo123** [comment]
The law was made, and it a way it made sense how the players built it(cant remember the exact details), but when we removed that law the players were able to reconnect and play without errors.

**Comment by SlayksWood** [comment]
8.2.0 staging-983 still an issue.
Step to reproduce:
- propose law like
![image](https://user-images.githubusercontent.com/45708377/59037457-f9825780-8879-11e9-8134-7ccf9af0de0b.png)
- pass law
- try to mine ore
- crash
[Crash 8.2.0.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3261796/Crash.8.2.0.txt)
I think it problem with law. You can select pick up species with some manipulation.
Step to reproduce:
- start to write law
![image](https://user-images.githubusercontent.com/45708377/59037737-8a593300-887a-11e9-9ab5-07e31060d06f.png)
- select pick up,select where, open drop-down list 
![image](https://user-images.githubusercontent.com/45708377/59037908-d86e3680-887a-11e9-98c5-91e2d1df7d6c.png)
You can't select species here.
- but you can "pick up species" if you select action which have species (for example Harvest)
![image](https://user-images.githubusercontent.com/45708377/59038566-e2dd0000-887b-11e9-99aa-c972e469b900.png)
- now you can select species
![image](https://user-images.githubusercontent.com/45708377/59039002-a958c480-887c-11e9-9f7e-ac9d3805f4ea.png)

**Comment by beastyn** [comment]
[0.8.2 - 988] 
After the last merge I can't make a law as there is no allow-disallow option.
For example, I try to prevent bison harvesting.
![bandicam 2019-06-08 14-25-32-706](https://user-images.githubusercontent.com/27898520/59145149-5b1d0000-89f9-11e9-96f6-75c30a551e06.jpg)
