### ISSUE TITLE
Overuse of registry for per server saving various window size settings with unique identifyers

### ISSUE THREAD

**Issue by Neouni** [StrangeLoopGames/EcoIssues#1236]
[HKEY_CURRENT_USER\Software\Strange Loop Games\ECO]
Please store less stuff in there, and use %appdata%, documents or the game folder

Was actually searching for the hidden game settings to turn the frame limiter on, no need for this game to run faster then maybe 60 fps.

**Comment by Neouni** [comment]
Was actually searching for the hidden game settings to turn the frame limiter on, no need for this game to run faster then maybe 60 fps.

**Comment by metachronism** [comment]
this is due to your overuse of playerprefs for UI positions/sizes, which is stored in the registry

**Comment by metachronism** [comment]
basically we need to not use playerprefs in unity so much, and just have one json config file

**Comment by johnkslg** [comment]
Not sure why this is a problem?

**Comment by MarjieAVolk** [comment]
I'm not sure about that either, but really most of the stuff we're storing in playerprefs should be stored on eco accounts

**Comment by SeanAtr0n** [comment]
IIRC the problem is that our registry usage grows the more you play... we are using GUIDs as part of the keys so over time you can end up with thousands of keys in the registry.

At the very least we should group by table type and stop storing prefs based on GUIDs

**Comment by johnkslg** [comment]
This is not a game or feature breaking bug, removing priority tag.

**Comment by MarjieAVolk** [comment]
Oh I just went to look, and we are not using guids for world object ui player pref keys anymore, haven't been since shortly after this bug was created... so I think it is fixed
