### ISSUE TITLE
USER ISSUE: servers dont seem to be working

### ISSUE THREAD

**Issue by alt2035** [StrangeLoopGames/EcoIssues#12375]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
trying to log on

**Expected behavior:**
get on and play

**Actual behavior:**
servers down and dont load

**Do you have mods installed? Does issue happen when no mods are installed?:**
servers down and dont load

**Comment by xanat0s** [comment]
Same thing here. Was just playing not even 12 hours ago. But now, can't continue my previous game and can't even connect to a new one since not a single server is listed.

Tried deleting "Strange Loop Games" folder in AppData\LocalLow, tried reinstalling. Nothing.

**Comment by beastyn** [comment]
There were server issues yesterday. Should be fine now.
@alt2035 @xanat0s is it working fine now?

**Comment by xanat0s** [comment]
@beastyn Thanks, yes it's been working today. 

Isn't there any error detection in place for this particular issue? At the very least it would be helpful to get an error message letting us know if we're dealing with a client-side or server-side problem. After checking SLG's twitter feed to see if there were any messages about the servers being down (there were none,) I assumed it was client-side and spent about an hour trying to troubleshoot it.

**Comment by beastyn** [comment]
@xanat0s Thank you for patience.
Yes, this kind of feedback definetly will be useful. I know that there is a task for steam-side issues feedback, So I will add the issue as a task for adding all types of feedback that we can distinguish.

But for now you should recieve the error like on the picture when problem is on the server side.
![bandicam 2019-05-23 11-52-35-627](https://user-images.githubusercontent.com/27898520/58231863-7a593380-7d51-11e9-87f8-6e25cc3b6db9.jpg)

**Comment by D3nnis3n** [comment]
@xanat0s We publish issues on Discord.

**Comment by xanat0s** [comment]
@D3nnis3n Didn't know that, thanks.

@beastyn I'm not getting any such message. Same thing is happening again tonight, I'll post a screenshot of what I'm seeing when I click on 'Continue'. It gives no option to submit a bug report. (I can, however, direct connect to servers by going into 'My Worlds'.) Not sure if this is the same problem OP was facing, but it isn't a login issue.

![eco_bugrep](https://user-images.githubusercontent.com/4296222/58305485-deb1dc80-7dbd-11e9-98fc-51e4b2db7f33.jpg)
