### ISSUE TITLE
[0.8.2 staging-11-n] Steam update changes configs

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12370]
With todays build we have new configs .eco
But they shouldn't be changing at all.
@SlayksWood and me have the same config for network as example
id = d8e750db-8bf2-48d9-859e-6c2547e8c9fa
name = DESKTOP-M8J3M62

**Comment by redwyre** [comment]
This was caused by me running a server in the Jenkins workspace for the staging build. I've removed the config files.

@BlazeGuy2 is there anything we can do to stop this from happening again? It seems the files were ignored.

**Comment by BlazeGuy2** [comment]
Might need to write a tool to clean the configs prior to upload.
