### ISSUE TITLE
[0.8.2.0 staging-11-d-2] Tooltip doesn't appear if check one by one.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12372]
It appears through one, sometimes through 2.
https://drive.google.com/file/d/1Q1SWbhiPcEFnwtDJQ_EnYnACO_fFUEFP/view?usp=sharing

**Comment by SlayksWood** [comment]
0.8.2.0 staging-13-d still an issue.
may need to increase a bit of tooltips like in 8.1.4?

**Comment by Quadbro** [comment]
default scale works well too 
![Tooltips](https://user-images.githubusercontent.com/6802030/58301160-8d323d80-7e0f-11e9-9ba8-d4aa87233f21.gif)

**Comment by beastyn** [comment]
Its now working good for me too. 
![tooltip](https://user-images.githubusercontent.com/27898520/58306379-c620e100-7e14-11e9-88a0-307ad37db54b.gif)

**Comment by Quadbro** [comment]
-_- I'll check in build tomorrow

**Comment by beastyn** [comment]
Not helpiiiing

Comparison 0.8.1.4 and 0.8.2 staging 15
https://drive.google.com/file/d/1Gihbtq5sKVM07iEuJBJ5rU3izv2j55Xr/view?usp=sharing
