### ISSUE TITLE
[0.8.2.0 staging-12-d] Charred Meat doesn't give Experience.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12383]
![image](https://user-images.githubusercontent.com/45708377/58175056-f72fd300-7ca7-11e9-990a-32a147b95470.png)
I expect to get a crafting experience. Because Charred Meat recipe tied to Advanced Campfire.
A similar recipe Render Fat has ExperienceOnCraft = 0,5
![image](https://user-images.githubusercontent.com/45708377/58175199-44ac4000-7ca8-11e9-8f78-8dff2c5f3fd1.png)

**Comment by craig-jong** [comment]
this recipe had its required skill changed and therefore should be fine.
