### ISSUE TITLE
[0.8.2.0 staging-12-d] CO2 Canister

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12384]
CO2 Canister instead C O2 Canister
![image](https://user-images.githubusercontent.com/45708377/58182241-ec7c3a80-7cb5-11e9-82b2-38f8a27ab7b8.png)

**Comment by redwyre** [comment]
@Spydarlee can we add the proper character to the font and use that?
https://www.compart.com/en/unicode/U+2082

**Comment by IcedForge** [comment]
![Screenshot_254](https://user-images.githubusercontent.com/24981362/147479910-838caa61-35da-47ae-a9a1-6b6a5f870bc4.jpg)
Will close this issue as resolved from font changes.
