### ISSUE TITLE
[0.8.2.0 staging] Player name from voice chat overlap  at contracts

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12385]
![image](https://user-images.githubusercontent.com/45708377/58229275-e5970b80-7d39-11e9-99e0-0c24471f4380.png)

**Comment by redwyre** [comment]
@johnkslg was there any reason why we put the voice players on the right? I could move it to the left side

**Comment by beastyn** [comment]
and notifications
![bandicam 2019-09-10 15-09-31-907](https://user-images.githubusercontent.com/27898520/64605203-06649900-d3dd-11e9-966f-485ef86e7362.jpg)

Maybe review UI for this part?

**Comment by SlayksWood** [comment]
Overlap at notification icons.
![image](https://user-images.githubusercontent.com/45708377/71355292-a232a300-258f-11ea-862c-1dd0b97973cf.png)
