### ISSUE TITLE
[0.8.2 staging-12-d] Fishing pole missing line in 3d person view

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12380]
There is no fishing line in 3d person view
![bandicam 2019-05-22 15-11-07-396](https://user-images.githubusercontent.com/27898520/58166850-23495500-7ca4-11e9-9658-7c0016516aa0.jpg)

**Comment by keegan-o** [comment]
Assigning stas after my old investigation and knowing he's working on various fishing issues.

**Comment by MazonDel** [comment]
The FishingPoleAvatar prefab, used in the 3rd person view has no line-renderers attached to display the line. If the Fishing Controller script (in the FishingPole prefab) can be made aware of an end point in the FishingPoleAvatar prefab, and switch between them when switching view modes, that would at least provide the line from the rod to the lure.
