### ISSUE TITLE
[0.8.2 staging-13-d] Names for voice chat behave strange

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12386]
Im not sure what is intended behaviour, but...

1. Move to the other player
2. In one moment see his name at the right side
3. Name is still there while the player is near
4. Go away and name will disappear.
5. Go back to the player, see the name and ask for talking
6. When player is talking you can see the icon near the name.
7. Player stop talking and name is disappearing.
From this moment the name will appear when player is talking and disappear when he is not.

From the first sight I thought that intended behaviour is:
-Display all names for the players who are in the sound zone
- Add the icon when the player is talking
- Name will disappear when the player is moving away.

**Comment by redwyre** [comment]
The list on the game screen is just players who are talking, the full list is in the escape menu.

Did you notice when the name fades out the speaker icon goes away first? Would it help if that was clearer?

**Comment by beastyn** [comment]
Then there shouldn't be names when you are just coming near someone who is not talking. And actually if its just a mark for speaking people then the speaker icon and the name should have the same sequence (as the name doesn't have meaning without the speaker icon).
I will make some records in todays testing

**Comment by redwyre** [comment]
Yeah, that doesn't sounds right @beastyn, a video would be great.

**Comment by beastyn** [comment]
https://drive.google.com/file/d/1izLH17LROPFakmcyPjTJ2TMHbQai4GGZ/view?usp=sharing
