### ISSUE TITLE
[0.8.2 staging-13-d] World data contains animal data that shows nothing 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12392]
Why do we need animal's capacity in World data?
1- Animal data
![bandicam 2019-05-23 17-36-35-606](https://user-images.githubusercontent.com/27898520/58253392-cfad3900-7d81-11e9-94ff-f43dde185ebf.jpg)
2. World data
![bandicam 2019-05-23 17-36-50-255](https://user-images.githubusercontent.com/27898520/58253455-f1a6bb80-7d81-11e9-8b71-f29188e15597.jpg)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/85989538-53ac0880-b9f9-11ea-9c55-bba6de956230.png)
