### ISSUE TITLE
[0.8.2.0 staging-14-n] Steam Tractor Plough continues to work when module is deactivated

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12397]
Step to reproduce:
- drive tractor with steam tractor plough.
- press Q to activate module
- plow the land
- press Q to deactivate module
- steam tractor plough continues to work
Video: https://drive.google.com/file/d/1YmBLpPlpU55KuRdWZh6UUN5K_60t564Y/view?usp=sharing

**Comment by Quadbro** [comment]
Cant reproduce it in last staging, tried a lot of possible ways, even q spam, but failed...

**Comment by SlayksWood** [comment]
I can't reproduce it too in staging-14-n-2. Seems fixed. I will reopen if I repeat
