### ISSUE TITLE
Pump Jack not creating oil while sleeping

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12390]
From this steam forum post: https://steamcommunity.com/app/382310/discussions/0/2530372519570938613/

**Comment by beastyn** [comment]
Checked in 0.8.1.4 and 0.8.2
Oil was producing while sleeping. If I need 20 minutes for one barrel I get it after sleeping in few seconds.
Maybe there is some additional info? Maybe power lacks?
Getting logs, saves will be great.

https://drive.google.com/file/d/1-9QEGWwiXcjXrpzv9cRC9qaKWsNtM0ia/view?usp=sharing

**Comment by D3nnis3n** [comment]
Player reported it worked on second try, closing out.
