### ISSUE TITLE
[0.8.2.0 staging-14-n] Talent "Parallel processing" issues

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12407]
Talent "Parallel processing" doesn't work at "no room requirement" tables
"no room requirement" tables: Campfire, Blast Furnace, Bloomery, Workbench, Oil Refinery, Pump Jack.
If you put 2 tables Craft speed will not change.
Moreover, if instead of talent "Parallel processing" to take talent "Focused Workflow". You have established 2 tables, the talent "Focused Workflow" will work on two tables.
I think this is wrong behavior.
Tallent "Parallel Processing: AdvancedCampfireCooking" doesn't work at all. Because all recipes of this specialty craft at Campfire.

**Comment by Deantwo** [comment]
Could just remove both talents and make some new talents.

Personally I think specialization would be better than table bonuses that no one understands.
For example Hewing could have a choice between a material reduction in either the Hewn Logs recipe or all furniture recipes.

**Comment by SlayksWood** [comment]
> The description for the Parallel Processing perk reads "Increases the speed of related tables when they share a room with the same tables by 20 percent."
> Looking at the code - unless I'm missing something - what appears to be happening is the perk has a craft time modifier of 0.8f, and applies it multiplicatively when the number of tables is 2 or greater.
> 
> This seems to indicate a **craft time reduction** of 20%, not a **craft speed increase** of 20% as the description suggests. A craft time reduction of 20% is equivalent to a craft speed increase of 25%.
> 
> Perhaps more importantly, there is confusion about whether the perk adds further 20% bonuses when additional tables are added. It's clear from the code that this not the case (although it might be nice if it were), but it suggests the explanation for Parallel Processing is unclear as there's has been speculation about how this perk operates. This also means that Focused Workflow is easily the dominant choice between these two options.
> 
> These are only small points, but I wanted to highlight that this perk is not working as advertised, and appears to be clearly the weaker option, in case it is a candidate for future rebalancing.

**Comment by elfl0rd** [comment]
> For example Hewing could have a choice between a material reduction in either the Hewn Logs recipe or all furniture recipes.

Sorry, but this selection is without selection.
In any case you need hewn logs, but you can make building materials cheaper in first case.

**Comment by Daniel-Magulado** [comment]
>I was testing some Focused Workflow vs Parallel Processing on a Blast Furnace and an Anvil in light of #21941 . There is something weird going on.

>1) Anvil recognises another Anvil for Parallel Processing and Focused Workflow
> 2) Anvil doesn't recognise Blast furnace for Parallel Processing or Focused Workflow
> 3) Blast Furnace does recognise an Anvil and Blast Furnace for Parallel Processing, but not for Focused Workflow (Focused Workflow applies all the time, Parallel Processing applies if there is an Anvil present)

>I've tested this with Parallel Processing on Advanced Smelting and Focused Workflow on Smelting.

>To reproduce - place 1-2 blast furnaces and 1-2 anvils inside of the same building and see which times update (may need to increase and decreate recipe repetitions to update the ETAs).

#21943

**Comment by Deantwo** [comment]
I would say those talents should just be removed. The choice isn't fun. You either select a talent for your one crafting station and miss out on the advantage of multiple crafting stations in the future, or you play the long game and don't get anything out of your talent untill you are mass producing.

I still say that specializing in a path of the skill would be more interesting. For example a tailor choosing to specialize in either furniture or clothing.

**Comment by IcedForge** [comment]
After a lot of discussion back and forth i will be closing this issue in favor of a talent rework planned down the line as it stands right now paralell processing is as stated someone broken for tables that are missing room requirements since there is no detection radius vs room requirement.
