### ISSUE TITLE
[0.8.2.0 staging-14-n] Something wrong with harvesting farm plants

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12406]
All without Gathering Speciality.
When I harvest wild corn/beet/tomato I almost always get 3 things if Maturity is 100%. Sometimes i get 2 things.
If i plant corn/beet/tomato I always get 2 things if Maturity is 100%. 
![image](https://user-images.githubusercontent.com/45708377/58327576-9edc0b00-7e38-11e9-9988-1d31449c942b.png)
![image](https://user-images.githubusercontent.com/45708377/58327722-faa69400-7e38-11e9-9ec8-c592bb90da08.png)
Why do I get less when I plant myself? 
With 7 level Gathering without talent I get wild - 6 corn/beet/tomato; planting - 4 corn/beet/tomato.

**Comment by SlayksWood** [comment]
100% Maturity.
Without Gathering: 2 corn/tomato (+0% yield potential)
Gathering 1: 2 corn/tomato (+40% yield potential)
Gathering 2: 3 corn/tomato (+50% yield potential)
Gathering 3: 3 corn/tomato (+60% yield potential)
Gathering 4: 3 corn/tomato (+70% yield potential)
Gathering 5: 3 corn/tomato (+80% yield potential)
Gathering 6 without talent "Experienced Farmhand: Gathering": 3 corn/tomato (+90% yield potential)
Gathering 6 with talent: 3 corn/tomato (+90% yield potential+ 20% talent(apparently it doesn't work))
Gathering 7 without talent: 4 corn/tomato
Gathering 7 with talent: 4 corn/tomato
From these data it can be seen that the harvesting of plants has a fixed base number = 2.
Also  Talent "Experienced Farmhand: Gathering" is broken.

**Comment by D3nnis3n** [comment]
Raised priority. People don't like this. And it's actually an regression, isn't it?

**Comment by craig-jong** [comment]
This is sort of a balance thing that will need a harder pass in 9.0, but I've made some changes that should improve this behavior.

**Comment by SlayksWood** [comment]
Plant potential isn't always 1 or 2 now. Initial issue was fixed. I will open a new issue of the balance of gathering benefits
