### ISSUE TITLE
USER ISSUE: Environment disappears

### ISSUE THREAD

**Issue by Bankaifan** [StrangeLoopGames/EcoIssues#12412]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Go away abit and come back

**Expected behavior:**
My treasures should still be visible

**Actual behavior:**
I cant see my treasures. But they are reachable over the tables

**Do you have mods installed? Does issue happen when no mods are installed?:**
I cant see my treasures. But they are reachable over the tables

**Comment by SlayksWood** [comment]
Merged with the update chunks #12352 
Should be improved in 8.2.0.
