### ISSUE TITLE
5.5.1 how to delete tailings form the game world bug

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1241]
so this works on any crafting table u just put the tailings into private storage then hit it with hammer pooof no more issue of wast.  

infact you can remove anything and everything form game world with this, i accidentally made friends cook stove disappear thats how we found out about it, that was in his private storage on my crafting table that i did not know was there.

**Comment by metachronism** [comment]
with linked inventories coming in 5.6, this issue is no longer relevant
