### ISSUE TITLE
USER ISSUE: Opening "recipe windows" broken

### ISSUE THREAD

**Issue by HerrVincling** [StrangeLoopGames/EcoIssues#12411]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Put mouse on any item in any inventory.
-> a window pops up and shows things as usual.
2. Try to open multiple "recipe windows".
-> you can focus icons from the first windos through the second window

**Expected behavior:**
You should just be able to continuously open new "recipe windows" as you focus on icons in the previous window.

**Actual behavior:**
Your mouse "sees" through the window onto the previous windows/layers -> opens unwanted windows

**Do you have mods installed? Does issue happen when no mods are installed?:**
Your mouse "sees" through the window onto the previous windows/layers -> opens unwanted windows

**Comment by D3nnis3n** [comment]
This is already fixed in 8.2.

**Comment by HerrVincling** [comment]
I'm playing version 8.1.4. How can I switch to 8.2? It's not showing up at the beta versions. Or is 8.2 coming soon?

**Comment by D3nnis3n** [comment]
It's the next update.
