### ISSUE TITLE
USER ISSUE: yazan

### ISSUE THREAD

**Issue by fatmea** [StrangeLoopGames/EcoIssues#12410]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
slg158421

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by D3nnis3n** [comment]
Please update to the most recent version 8.1.4 and reopen if the issue persists.
