### ISSUE TITLE
[0.8.2.0 staging-14-n] Choose of Voice mode. Vissually bug

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12414]
You can remove the selection
Step to reproduce, for example:
- have "push to talk" mode
- choose "Open mic"
![image](https://user-images.githubusercontent.com/45708377/58405177-87d32e00-806f-11e9-8d51-2c49d84faf16.png)
- click Open Mic again
![image](https://user-images.githubusercontent.com/45708377/58405200-93265980-806f-11e9-9a6e-0bf1cfcb5040.png)
Voice chat works in Open Mic mode.

**Comment by redwyre** [comment]
nice catch
