### ISSUE TITLE
USER ISSUE: Won't create a new world

### ISSUE THREAD

**Issue by SystemSlayer525** [StrangeLoopGames/EcoIssues#12417]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Create a new world tab, set to randomize world, randomize thhe numbers and click to create world

**Expected behavior:**
Created a new world and put that world in the load tab through the main menu navigation

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by Deantwo** [comment]
Duplicate or related to #12418

**Comment by D3nnis3n** [comment]
It actually is.

**Comment by D3nnis3n** [comment]
Well, actually it is not.

**Comment by D3nnis3n** [comment]
The user had a log on steam that he unfortunately did not post here, it contains a nullreference exception, probably @mirasrael can fix that:

> <size=150%>Connection Failed</size>
> 
> Failed to connect - connection timed out.
> 
> 
> <RI> Initializing input.
> 
> <RI> Input initialized.
> 
> <RI> Initialized touch support.
> 
> UnloadTime: 1.648312 ms
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Legacy Shaders/Diffuse' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Avatar FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Pollutable Lambert FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Lambert FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Avatar' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/SpeedTree' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Cutout' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/StandardFade' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked Metalness' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Triplanar Masked FADE' - Pass 'Meta' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Curved/Standard (Vertex Color)' - Pass 'META' has no vertex shader
> Connecting to local host.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connecting to 127.0.0.1:3000...
> 
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> Eco.Shared.Utils.Log:WriteLine(LocString)
> Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
> Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connection complete.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
> 
> Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 85544.
> Total: 411.234893 ms (FindLiveObjects: 24.907449 ms CreateObjectMapping: 18.851098 ms MarkObjects: 366.852054 ms DeleteObjects: 0.622772 ms)
> 
> NullReferenceException: Object reference not set to an instance of an object.
> at UnityEngine.Component.GetComponentInParent (System.Type t) [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.Component.GetComponentInParent[T] () [0x00000] in <00000000000000000000000000000000>:0 
> at HostNewWorldUI+<>c__DisplayClass18_0.<DoSubmit>b__0 () [0x00000] in <00000000000000000000000000000000>:0 
> at LZ4.LZ4Codec+Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
> at PopupDialogUI.OnYesClick () [0x00000] in <00000000000000000000000000000000>:0 
> at LZ4.LZ4Codec+Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
> at System.ComponentModel.PropertyChangedEventHandler.Invoke (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
> at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
> UnityEngine.Logger:LogException(Exception, Object)
> UnityEngine.Debug:LogException(Exception)
> UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
> UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
> UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
> UnityEngine.EventSystems.StandaloneInputModule:Process()
> UnityEngine.EventSystems.EventSystem:Update()
> 
> (Filename: currently not available on il2cpp Line: -1)
> 
> Connecting to local host.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connecting to 127.0.0.1:3000...
> 
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> Eco.Shared.Utils.Log:WriteLine(LocString)
> Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
> Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Connection complete.
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:Log(Object)
> UI.ConnectionUI:ManualUpdate()
> UI.UIManager:Update()
> 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)
> 
> Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
> 
> Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 85543.
> Total: 439.658209 ms (FindLiveObjects: 25.797340 ms CreateObjectMapping: 17.203166 ms MarkObjects: 396.131444 ms DeleteObjects: 0.525879 ms)

**Comment by mirasrael** [comment]
Usually if you can't connect to the server then it is a server problem. So we need a server log (most probably he started server locally and had a crash).

**Comment by D3nnis3n** [comment]
Closed for no response. Please open a new issue when this reoccurs and you have more information.
