### ISSUE TITLE
[0.8.2.0 staging-14-n-2] Incorrect display tax in public crafting station

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12424]
Also see StrangeLoopGames/EcoIssues#12421
From me:
![image](https://user-images.githubusercontent.com/45708377/58466542-81fa4d00-8142-11e9-824a-54d54219fbea.png)
From Anna:
![image](https://user-images.githubusercontent.com/45708377/58470772-15d01700-814b-11e9-9951-898e6043f2fd.png)

I assume that the owner of the table must pay the tax.
I think it should be displayed as:
1. For me:
beastyn Paid fee for Project , paying you 100 beastynBucks.
You paid 10 beastynBucks in tax for Project. Treasury balance: 5085,44 beastynBucks.
For Anna:
Paid fee for Project , you pay 100 beastynBucks to Slayks.
Slayks paid 10 beastynBucks in tax for Project. Treasury balance: 5085,44 beastynBucks.

2.Or for all the same:
beastyn Paid fee for Project, beastyn pay 100 beastynBucks to Slayks.
Slayks paid 10 beastynBucks in tax for Project. Treasury balance: 5085,44 beastynBucks.

If you make these changes, you can remove the tax displayed on the table. Display only fee. This will increase the visibility.
![image](https://user-images.githubusercontent.com/45708377/58471583-e3bfb480-814c-11e9-9789-268fac1d3998.png)

**Comment by beastyn** [comment]
Won't touch until this https://github.com/StrangeLoopGames/Eco/pull/6890

**Comment by beastyn** [comment]
After refactoring looks great without changes.
For both parties message will be the same.
-Who paid what(what sum is taxed)-
![bandicam 2020-12-23 16-42-32-329](https://user-images.githubusercontent.com/27898520/102992913-09d25400-453e-11eb-9b4a-e06ca8cfe2a0.jpg)
