### ISSUE TITLE
[0.8.2.0 staging-14-n-2] Improvements for Skid Steer and Excavator 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12427]
After the release of 8.0 in the world has become a lot of different blocks. Because of this, digging on Skid Steer has become more difficult. For example:
I want to dig a tunnel. In the place where I dig there are 5 types of blocks (cells on toolbar 4): Clay, Dirt, Iron ore, Sandstone, Limestone. 
![image](https://user-images.githubusercontent.com/45708377/58480822-cf3ae680-8163-11e9-80fb-324731da7761.png)
I think it is worth adding additional cells (2 or more) on the toolbar. But you can limit (if you want) the things that can be transferred by adding the maximum weight (I assume the maximum weight = dirt weight * "Max value items that Skid Steer has in 8.1.4" = 30 * 80 = 2400 kg). This will allow you to dig a tunnel to the maximum load of Skid Steer. 
In 8.2.0 staging-14-n-2: if I stumble on 5 different block, then I can't  digging. I need move to stockpile.
The same can be done to improve the excavator.

**Comment by D3nnis3n** [comment]
Either label it feature OR suggestion.
Suggestions will be automatically moved to the suggestions tracker.

**Comment by D3nnis3n** [comment]
In this case i give it balance, given it's somewhat of an issue.

**Comment by ThePiachu** [comment]
This has become even a bigger issue in 0.9 with the crushed ore and crushed rock appearing as part of the world generation. We need a bigger skid inventory, while retaining the same weight limit.
