### ISSUE TITLE
[0.8.2.0 staging-15-d] Rear wheels don't spin at Steam Truck in multiplayer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12435]
![2019 05 29 Steam truck rear wheels](https://user-images.githubusercontent.com/45708377/58542585-8d16b100-8206-11e9-8232-e698ca6463b0.gif)

**Comment by keegan-o** [comment]
Assigning Stanislav, since he is taking over on vehicles from sean (I was never implementer for them).

**Comment by keegan-o** [comment]
@MazonDel You could check in with Stanislav to see if he has investigated it, and take a look at fixing it. Vehicles in Eco mostly use the asset store RCC vehicle controller, their documentation might be relevant.

**Comment by MazonDel** [comment]
Solved. The front wheels have a manually triggered SyncPhysics component on them that manages the spinning and other rotations. I implemented this on the rear wheels but locked it so that it only updates the X axis (the spinning axis).

These changes are in the "/trunk" branch of the SVN for 9.1.
