### ISSUE TITLE
[0.8.2.0 staging-15-n-2] Voice chat glitch near Zero Point

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12444]
1. You can't hear other players if You are on opposite sides regarding to zero.
2. Players doen't display in Voice Users if You are on opposite sides regarding to zero.
![2019 05 30 Voice chat glitch near Zero Point](https://user-images.githubusercontent.com/45708377/58613987-d24ae980-82bf-11e9-9dd7-88f8496e72f2.gif)
Mortared sandstone block is Zero point.

**Comment by D3nnis3n** [comment]
This zero point is some sort of black hole, uh?

**Comment by redwyre** [comment]
It's where the world space wraps around, so anything that's not wrapping properly will be just about as far away as possible :P

Unfortunately Viviox doesn't support wrapping speaker positions, but I'm working on a work around that should handle the majority of cases.
