### ISSUE TITLE
[0.8.2.0 staging-15-n-2] Version of the game is incorrect when creating default world

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12448]
Step to reproduce:
- Host your own World
- Generete default world
- Enter the world
- open Esc menu
![image](https://user-images.githubusercontent.com/45708377/58631131-34b8df80-82ea-11e9-9d3d-00f461e0bbcd.png)
If you go to main menu All right:
![image](https://user-images.githubusercontent.com/45708377/58631321-e7893d80-82ea-11e9-89dc-00c847d94eb2.png)

**Comment by SlayksWood** [comment]
"Logout" button also appears. When you click on it, nothing happens.
![image](https://user-images.githubusercontent.com/45708377/59347150-929eeb80-8d1c-11e9-9131-cf8285b96a2d.png)

**Comment by TwixterZ** [comment]
This issue have been fixed as of 9.4, closing
