### ISSUE TITLE
[0.8.2.0 staging-15-n-2] Another way to get more items from distribution station.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12446]
Step to reproduce
- spawn distribution station
- I can take 5 Laboratory
![image](https://user-images.githubusercontent.com/45708377/58615420-b6494700-82c3-11e9-96a3-79a39cae1400.png)
- open distribution station. Shift+LMB on Laboratory. Set value to maximum
![image](https://user-images.githubusercontent.com/45708377/58615500-e85aa900-82c3-11e9-939d-5d836e26c715.png)
- drag items
![2019 05 30 Another way to get more items from distribution station](https://user-images.githubusercontent.com/45708377/58616123-87cc6b80-82c5-11e9-96da-f3f31dc1360f.gif)
- I take all laboratories.
![image](https://user-images.githubusercontent.com/45708377/58615592-1fc95580-82c4-11e9-8696-d3c07dfb73fd.png)

**Comment by Deantwo** [comment]
Just... https://github.com/StrangeLoopGames/EcoSuggestions/issues/830... :roll_eyes:
