### ISSUE TITLE
Mini room of 1 cubic meter

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12441]
Building a room of 2x2x1 blocks and removing blocks afterwards leads to an enabled 1 that gives full points.
![roombug](https://user-images.githubusercontent.com/5678451/58557375-8a27ba80-821e-11e9-8e4c-852ddf3e4939.JPG)

**Comment by SlayksWood** [comment]
It's fixed in 8.2 #12106
