### ISSUE TITLE
[0.8.2.0 staging-15-n-2] Old Growth Redwood absents in 0.52km Worlds

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12449]
Generate 6 random worlds. Three time Old Growth Redwood = 0 in 0.52km worlds.
0.52 km world: 0, 0, 0
![image](https://user-images.githubusercontent.com/45708377/58631044-f7ece880-82e9-11e9-93ca-d10aab6e4ff7.png)
![image](https://user-images.githubusercontent.com/45708377/58632410-0c32e480-82ee-11e9-9910-01b9add94ca1.png)
![image](https://user-images.githubusercontent.com/45708377/58632603-b874cb00-82ee-11e9-8cf0-9b9352697dd7.png)

1 km world: 5, 33, 44
![image](https://user-images.githubusercontent.com/45708377/58631747-2bc90d80-82ec-11e9-85ee-5516de10d133.png)
![image](https://user-images.githubusercontent.com/45708377/58632082-4f408800-82ed-11e9-81d2-c517619e0561.png)
![image](https://user-images.githubusercontent.com/45708377/58632978-d8f15500-82ef-11e9-883e-c9b7398041d0.png)

**Comment by SlayksWood** [comment]
One of five times
![image](https://user-images.githubusercontent.com/45708377/59604189-1b01ff80-9114-11e9-82d9-283a64699a86.png)

**Comment by WeaselDog** [comment]
Sagebrush always has 0 population but Old Growth Redwood has been fine for me.
