### ISSUE TITLE
Changing a price affects random items in stores

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1244]

**Comment by johnkslg** [comment]
Seems to be related to the reuse of list elements when ones are added/removed, and then being unable to unsubscribe from changes.

We could force this to work by deleting and rebuilding the list of Trade Offers each time if it remains impenetrable to figure out.  Need your help on this one so passing to you.

**Comment by metachronism** [comment]
irrelevant with store refactor, closing.
