### ISSUE TITLE
[0.8.2.0 staging-16-n] Default World bad species.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12458]
staging-16-n:
![image](https://user-images.githubusercontent.com/45708377/58695652-963a8600-839e-11e9-8485-5df038a0fbb8.png)
Tortoise= 0 
BighornSheep = 1
Old Growth Reedwood = 0 . Absents in any 0.52km world

staging-16-d: all right.(without Old Growth Reedwood)
![image](https://user-images.githubusercontent.com/45708377/58696055-6f308400-839f-11e9-9a1b-e0d423c5290f.png)

Yesterday I tested generating new worlds. Was problem only with Old Growth Redwood. In the new build, the problem appeared when generating a new default world. But in day build it was all right.
In new build everything will be fine with a very high probability. But you need to see that this doesn't happen again.

**Comment by D3nnis3n** [comment]
That's a high one. We want people to be able to use all of our features and a unstable ecosystem is a pain in the ass for them.

**Comment by SlayksWood** [comment]
Checked on 8.2.0 staging-982:
We have 5 Zeros early and 75 species.
Now We have 0 Zeros and 71 species.
Sagebrush appeared in game. Is it right? If yes, then close this issue and I will open a new issue for sagebrush model.
![image](https://user-images.githubusercontent.com/45708377/58956552-421d1080-87a7-11e9-814d-87928386bf4d.png)
![2019 06 05 Sagebrush model](https://user-images.githubusercontent.com/45708377/58957903-59113200-87aa-11e9-9761-129add3116e9.gif)

**Comment by SlayksWood** [comment]
opened new issue for sagerbush model
