### ISSUE TITLE
[0.8.2.0 staging-16-n] Deed highlighting depends on light sources.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12459]
Highlight is very bad seen in midnight (near 22 - 02 o'clock) and in midday (10 - 14 o'clock)
7 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701555-f4219a80-83ab-11e9-97f4-9cddb8ea751f.png)
10 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701597-0a2f5b00-83ac-11e9-9c74-33d3da4dcdb9.png)
12 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701626-15828680-83ac-11e9-8631-b87ca2227180.png)
14 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701642-1ca99480-83ac-11e9-93bd-0095d5302760.png)
18 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701679-38149f80-83ac-11e9-8a10-4a0c4edc3041.png)
22 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701661-2df2a100-83ac-11e9-850f-887ca126c49d.png)
24 o'clock: almost invisible
![image](https://user-images.githubusercontent.com/45708377/58701697-4367cb00-83ac-11e9-9ebc-7da5940e1973.png)
02 o'clock:
![image](https://user-images.githubusercontent.com/45708377/58701715-54b0d780-83ac-11e9-9dc3-77dc524c960c.png)

**Comment by redwyre** [comment]
This should have been fixed a while ago
