### ISSUE TITLE
[0.8.2.0 staging-16-n] Skid Steer digs badly in the lower position of scoop

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12468]
![image](https://user-images.githubusercontent.com/45708377/58798670-e0746f00-860b-11e9-8db5-35477c0e98c7.png)
![2019 06 03 Skid Steer digs badly in the lower position of scoop](https://user-images.githubusercontent.com/45708377/58798649-d2bee980-860b-11e9-820c-3f78292980ee.gif)

**Comment by johnkslg** [comment]
@mirasrael did a lot of work on making excavator better, consult with him on this one

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/4700
