### ISSUE TITLE
[0.8.2.0 staging-16-n] Real Estate Desk is broken

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12461]
"List" button absents. I can't create sale.
![image](https://user-images.githubusercontent.com/45708377/58705476-073a6780-83b8-11e9-9a03-7206342f94d9.png)
![image](https://user-images.githubusercontent.com/45708377/58705255-503dec00-83b7-11e9-8dca-baa2db4ab5d9.png)

**Comment by beastyn** [comment]
@Quadbro CHeck please, I still can'see the button
![Uploading bandicam 2019-06-04 20-11-55-639.jpg…]()

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/58930014-fb69ef00-8783-11e9-9dca-073fe9c2f3a2.png)
