### ISSUE TITLE
USER ISSUE: Invalid Username Password

### ISSUE THREAD

**Issue by Shongeska** [StrangeLoopGames/EcoIssues#12465]
**Version:** 0.8.2.0 beta staging-965a3dbb*-17

**Steps to Reproduce:**
download EcoPC-v0.8.2.0-beta-staging-965a3dbb-17.zip from slg website
extract and run Eco.exe
try to login into slg account

**Expected behavior:**
Login to process normally

**Actual behavior:**
The following error message popped up:
Invalid username/password
reset username/password via slg website
try to log into slg account via game
Invalid username/password 
Too many failed attempts. Blocked for 2 hours.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods
```
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3244801/output_log.txt)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3244802/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3244803/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3244804/Player-prev.log)

**Comment by Shongeska** [comment]
Able to login and play normally via steam version.

**Comment by Shongeska** [comment]
Able to login Via v0.8.1.0-beta-staging-0c12c40e

**Comment by Shongeska** [comment]
Just downloaded EcoPC_v0.8.2.0-beta-staging-d436a54b-986 - same issue. even changed password. tried username both proper caps and all lowercase. still getting the same issue.
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3264692/output_log.txt)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3264693/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3264694/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3264695/Player-prev.log)

**Comment by Shongeska** [comment]
Backed up and change the %appdata%\LocalLow\Strange Loop Games\Eco folder same issue . 
this a fully update windows 10 box.

**Comment by mirasrael** [comment]
Hi @Shongeska. Can you contact me in Discord for troubleshooting? You can find me in official channel Eco developers list (mirasrael).

**Comment by mirasrael** [comment]
@Shongeska staging build now points to development auth server. It doesn't have all user accounts.

**Comment by Shongeska** [comment]
I dont have dicsord set up one sec

**Comment by Shongeska** [comment]
ok on Disc still waiting for the auth email

**Comment by Shongeska** [comment]
Just logged in EcoPC_v0.8.2.0-beta-staging-D436a54b-986 via steam

**Comment by Shongeska** [comment]
Issue is with Dev login auth db and not within the game itself.
