### ISSUE TITLE
Bug that causes mouse clicks to no longer work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12463]
Report from Discord:

> Bug report:
> * Press Y
> * Click Make a transfer
> * Click "Destination bank account" Dropdown
> * Press ESC
> 
> Result: You can't click on anything :stuck_out_tongue:
>

**Comment by SlayksWood** [comment]
I think it's dup #11958. I will recheck tommorow

**Comment by SlayksWood** [comment]
It's fixed in 8.2
