### ISSUE TITLE
[0.8.2.0 staging-16-n] Strange behavior of the arrow when hit in Old Growth Redwood.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12477]
When shoot at Old Growth Redwood at an angle Arrows very often roll over 180 degrees.
![image](https://user-images.githubusercontent.com/45708377/58873179-68bb4880-86ce-11e9-82ae-79b3fddc0d4f.png)
![image](https://user-images.githubusercontent.com/45708377/58873210-7a045500-86ce-11e9-817b-a73fb87ae7db.png)
![image](https://user-images.githubusercontent.com/45708377/58873245-8f797f00-86ce-11e9-9896-200897c7d809.png)

**Comment by TwixterZ** [comment]
Issue no longer prevalent as of 0.10.0.0 Develop-711
