### ISSUE TITLE
[0.8.2.0 staging-16-n]Blocks from different material don't connect between themselves 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12476]
If the block is non-rectangular, then it does not connect to the block from another material.
Floor blocks:
![image](https://user-images.githubusercontent.com/45708377/58871667-23494c00-86cb-11e9-9fc5-4a75921fd511.png)
Roof Blocks: It's corner from Lumber, Flat Steel, Mortared Granite. It should look like a neighbor corner from a brick.
![image](https://user-images.githubusercontent.com/45708377/58871879-7de2a800-86cb-11e9-83f2-d8118eab07a1.png)
![image](https://user-images.githubusercontent.com/45708377/58871914-95ba2c00-86cb-11e9-9f5b-58734d8c44ea.png)
All tier1 roof blocks:
![image](https://user-images.githubusercontent.com/45708377/58872095-fa758680-86cb-11e9-8b26-9f3281611a5c.png)

**Comment by SlayksWood** [comment]
With Ramp:
![image](https://user-images.githubusercontent.com/45708377/58872740-65738d00-86cd-11e9-9d09-3748f1641445.png)

**Comment by SlayksWood** [comment]
From #14515
> ![Roof](https://user-images.githubusercontent.com/4590597/73144133-1faa7100-4070-11ea-9e97-e586d69643b0.png)
> 
> **Version:** 0.8.3.2 beta
> 
> **Steps to Reproduce:**
> Create a 2 wide perimeter of mortared sandstone roof tiles around a 3x3 (or larger) section of mortared stone roof tiles, and the corners where they meet drop oddly.
> 
> **Expected behavior:**
> A solid roof.
> 
> **Actual behavior:**
> Corner connection drops two tiles in an odd manner.
> 
> **Do you have mods installed? Does issue happen when no mods are installed?:**
> Corner connection drops two tiles in an odd manner.

**Comment by keegan-o** [comment]
Roof forms now all have split individual forms to use, "fixing" the smart roof builder is not feasible.
