### ISSUE TITLE
Slow Chunkloading + Unstuck Issue

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12489]
Slow Chunkloading causes players to be able to walk in player farms like this one, without seeing it, then the trees pop in and /unstuck doesn't work for this case. Needed to manually port them out.

Possible suggestions:
1. Chunkloading that is fast enough for everyone, so this could never happen.
2. /unstuck managing this case and unstucking the player.
3. Trees not being able to be placed that near to each other.

If you ask me, all three should be done.

![unstuck](https://user-images.githubusercontent.com/25908592/59023565-5ec15300-8850-11e9-957f-dd47d009b4bf.png)

**Comment by mirasrael** [comment]
1. Chunk loading was improved and chance to get stuck in tree now reduced.
2. Unstuck command was improved to better handle such stuck scenarios.
