### ISSUE TITLE
[0.8.2.0 staging-982-d] Mixed Desert Moss and Sagebrush models

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12485]
![image](https://user-images.githubusercontent.com/45708377/58959403-ae027780-87ad-11e9-9711-558fb11f5b01.png)
![image](https://user-images.githubusercontent.com/45708377/58959423-bc509380-87ad-11e9-920e-c66b893e86c8.png)
When harvest Sagebrush:
![2019 06 05 Sagebrush model](https://user-images.githubusercontent.com/45708377/58959477-e013d980-87ad-11e9-925c-d14059b57533.gif)
When harvest Desert moss:
![2019 06 05 Desert moss model](https://user-images.githubusercontent.com/45708377/58960765-806afd80-87b0-11e9-8c56-653106b25b63.gif)

**Comment by D3nnis3n** [comment]
Seems like an art issue which would be @keegan-o, though i actually do not know who does the implementation. Feel free to reassign, if you were the wrong one.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/4665
