### ISSUE TITLE
[0.8.2.0 staging-983] Reseting tab when reopening minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12488]
Step to reproduce:
- open minimap
- open, for example, Environment data - Plant - Huckleberry yield potential.
![image](https://user-images.githubusercontent.com/45708377/59012957-8c52d000-8841-11e9-9db7-beeb60a38794.png)
- close and open minimap again. Tab "Markers" will open instead tab "Environment data"
![image](https://user-images.githubusercontent.com/45708377/59012996-9d034600-8841-11e9-8a3a-f2ec4607f10c.png)
- select Environment data. All setting saves.
![image](https://user-images.githubusercontent.com/45708377/59013081-cb812100-8841-11e9-8066-6c1a36bb116c.png)
For me tab "Markers" always open when I open minimap. Last tab should open when open minimap. So it was in previous version.

**Comment by Quadbro** [comment]
I think last tab openned wasn't done even in previous versions)
