### ISSUE TITLE
Selection problem when placing workbench in fresh world

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12486]
![animx](https://user-images.githubusercontent.com/3536496/58977793-459ca180-877f-11e9-9ab1-0052aa592bb0.gif)
Only some parts of it highlight, the metal part on the workbench.

It also does this weird thing where it can only highlight when it's occluded by something else like grass:
![animx](https://user-images.githubusercontent.com/3536496/58977929-9a401c80-877f-11e9-9d78-148406f7b389.gif)

This repros for me when generating a new world, spawning in, giving a workbench first thing and placing it.  Or, it may be related to connecting to a restarted server without stopping the client.

**Comment by johnkslg** [comment]
I believe it's in 8.2 as well

**Comment by SlayksWood** [comment]
I can't reproduce in 8.2

**Comment by beastyn** [comment]
didn't meet in 0.9
