### ISSUE TITLE
USER ISSUE: Loosing Xp (no know reason)

### ISSUE THREAD

**Issue by reggiew17** [StrangeLoopGames/EcoIssues#12493]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Unfortunatly I am unable to the issue presented itself this moringing I can submit log files 

**Expected behavior:**
Should gain Xp for skill point witha food multiplier of +150.9 and a home of +53.4. 

**Actual behavior:**
however i get about 30 xp and it reverts back to 0

**Do you have mods installed? Does issue happen when no mods are installed?:**
however i get about 30 xp and it reverts back to 0

**Comment by reggiew17** [comment]
There are no MODs installed

**Comment by beastyn** [comment]
@reggiew17 Thank you for the report.
We will be waiting for you logs.
Also save files with DB should be useful too https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by reggiew17** [comment]
https://drive.google.com/open?id=17XJtXhYtGKGwDl1EKYpNcErVBV8TD9r4

I think that is all you need. I could not find the .game file as described in the link you attached. If you need further information please let me know.

**Comment by reggiew17** [comment]
Update: It seems that anytime I am upgrading my mechanic's skill (using assembly line, press, lathe, etc) I lose the daily skill points.

**Comment by reggiew17** [comment]
Update: Based on what I have observed I lose my experience points when I touch any crafting table or machine. other than that I can gain when I am logging and such. Im not sure if this helps clear things up or not

**Comment by SlayksWood** [comment]
I still can not reproduce it (
All possible information is needed: from the level of a mechanic (or other specialization), to a specific craft recipe and in what sequence resources were added. If you can, just shoot the video. This will help me a lot.
Also provide new log file: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
After the release of 0.8.2.0 I follow my experience very carefully, and I ask the guys. No one had such a problem. Closed for now. If it happens again, please reopen and provide log and save files.
