### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Fradack** [StrangeLoopGames/EcoIssues#12495]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Invalid password.

<size=60.00%></size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Invalid password.

<size=60.00%></size>
```

**Comment by D3nnis3n** [comment]
This means your password is invalid. Please contact support@strangeloopgames.com if you have issues that require support.
