### ISSUE TITLE
[0.8.1.4] Allocate 0 divided by 0 by law breaks used currency to NaN

### ISSUE THREAD

**Issue by voyagebass** [StrangeLoopGames/EcoIssues#12498]
On our server we have an activity bonus law that allocates (your actions/everyone's actions). It's a bit more complicated but it breaks down to that division that can become a "0 divided by 0".
![image](https://user-images.githubusercontent.com/2228338/59144913-ee940800-89dc-11e9-9336-0171488f8c97.png)
After some time people didn't log in for more than a day and "your actions" as well as "everyone's actions" was 0. After that everyone's personal account and of course the whole currency used in the law had "NaN" as a value.

Steps to reproduce:
1. /clearlaws
2. build working mint (and treasury i think)
3. create "new currency"
4. propose law "When this law is passed for each player allocate (constant 0 / constant 0) new currency"
5. /passlaws

new currency is now NaN in your account and in the treasury.
(Could be the same issue as #2497)

**Comment by johnkslg** [comment]
Law system is getting rewritten for 9.0 and should address this.

**Comment by WeaselDog** [comment]
Still an issue when dividing 0/0

**Comment by beastyn** [comment]
And when something like that happens
![bandicam 2019-11-26 23-27-27-136](https://user-images.githubusercontent.com/27898520/69693063-fb74f700-10f5-11ea-9de0-a081e58055ff.jpg)
Your presonal account looks odd
![bandicam 2019-11-26 23-23-06-314](https://user-images.githubusercontent.com/27898520/69693079-0a5ba980-10f6-11ea-9967-40d3c0cff476.jpg)
(not a number)

**Comment by johnkslg** [comment]
@beastyn can we get updated repro instructions for current civics? Passing to @oleg

**Comment by beastyn** [comment]
NaN is gone.
