### ISSUE TITLE
USER ISSUE: Issues Connecting Since Steam Launch

### ISSUE THREAD

**Issue by daniellogerstedt** [StrangeLoopGames/EcoIssues#12501]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Open game via Steam
2. Attempt to connect to a server

**Expected behavior:**
It should connect to a server

**Actual behavior:**

This has been an issue that continues to occur for some of the community it seems but no one has found a fix. I've attempted resetting my password on my account and it still encounters it.

The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
No, I have just the base game installed.

**Comment by D3nnis3n** [comment]
This is caused by the steam auth servers, not ours. Nothing we could do about it but i'll let people investigate.

**Comment by SlayksWood** [comment]
@daniellogerstedt 
Do you have this problem now?
