### ISSUE TITLE
[0.8.2.0 staging-991] Tutorial "Forage for food" glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12507]
1. After restart tutorials sometimes You need to collect plants very far from your position.
![image](https://user-images.githubusercontent.com/45708377/59185526-60a15400-8b79-11e9-9346-b481d6c6726d.png)
2. Sometimes 1 plant appears. I think need minimum 3 plants for tutorial.
![image](https://user-images.githubusercontent.com/45708377/59185649-a65e1c80-8b79-11e9-99c3-1a469d3157ec.png).
3. When you hungry to work Tutorial "Forage for Food" appears but markers don't appear.
![image](https://user-images.githubusercontent.com/45708377/59185963-68adc380-8b7a-11e9-9d81-b63cf43c0678.png)
![image](https://user-images.githubusercontent.com/45708377/59186484-a4955880-8b7b-11e9-88ec-25d8f8e5dde9.png)

**Comment by SlayksWood** [comment]
0.9.0: When you harvest plants Tutorial doesn't appear.

**Comment by StanKryvenko** [comment]
It won’t appear anymore. Now we have a food tutorial only when you’ve got low calories count

**Comment by gzatravkin** [comment]
This tutorial should be already fixed
