### ISSUE TITLE
[0.8.2.0 staging-991] Glitch of skipping tutorials 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12504]
Step to reproduse:
- start tutorials
![image](https://user-images.githubusercontent.com/45708377/59177811-e6b39f80-8b65-11e9-8bc0-635a429c02cd.png)
- complete tutorial
![image](https://user-images.githubusercontent.com/45708377/59177937-385c2a00-8b66-11e9-9ab5-30f3b1993d32.png)
- skip tutorial when it has text "task complete".
![image](https://user-images.githubusercontent.com/45708377/59177970-56298f00-8b66-11e9-8dfa-63e9efca78ad.png)
- tutorials skiped, but next tutorial will appear.
![image](https://user-images.githubusercontent.com/45708377/59178044-84a76a00-8b66-11e9-9805-06011f38dada.png)
You can't do it, you can't skip by one, you can only close it with skip all tutorials.
![image](https://user-images.githubusercontent.com/45708377/59178115-b7e9f900-8b66-11e9-8237-2965cf5cd466.png)

**Comment by SlayksWood** [comment]
In 9.0 you can't skip all tutorials. Only reload help

**Comment by gzatravkin** [comment]
Stil occur? Can't reproduce, please attach a video

**Comment by SlayksWood** [comment]
https://drive.google.com/file/d/1qscCrRXBGcOcqaoZFszs78xHrRrtFnDY/view?usp=sharing
