### ISSUE TITLE
Leaky pipe

### ISSUE THREAD

**Issue by DrRush12358** [StrangeLoopGames/EcoIssues#12502]
![derpy water](https://user-images.githubusercontent.com/16111056/59167980-c94cea00-8b01-11e9-8f12-5b1a5e7c4f7a.png)

This connected pipe both displays a leak animation and is registered as such in status windows for every generator in this system. Picking it up and replacing it does not fix the issue.

**Comment by SlayksWood** [comment]
dup #11846
