### ISSUE TITLE
USER ISSUE: Login failure

### ISSUE THREAD

**Issue by Progamer1865** [StrangeLoopGames/EcoIssues#12512]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
I login with my account Ramzigmail and type my password and get the error for invalid credentials.

**Expected behavior:**
duh.. i should have been logged in..

error message:
Invalid username or password.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by SlayksWood** [comment]
Please update to the newest game version and reopen if this reoccurs.
