### ISSUE TITLE
USER ISSUE: Losing EXP

### ISSUE THREAD

**Issue by alt2035** [StrangeLoopGames/EcoIssues#12515]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
use any high tier machines and i lose my exp

**Expected behavior:**
should gain experience, not lose it

**Actual behavior:**
my bar goes back to 0

**Do you have mods installed? Does issue happen when no mods are installed?:**
my bar goes back to 0

**Comment by SlayksWood** [comment]
dup #12493
