### ISSUE TITLE
USER ISSUE: Elk carcass disapears upon pickup

### ISSUE THREAD

**Issue by tasinei** [StrangeLoopGames/EcoIssues#12514]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
shoot an elk and pick up the carcass

**Expected behavior:**
the carcass should be on my toolbar	

**Actual behavior:**
Disapears even if toolbar is completely empty

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing extra installed

**Comment by SlayksWood** [comment]
@tasinei 
Are you sure that deer carcass  did not appear on your toolbar?
I can't reproduce.

**Comment by tasinei** [comment]
@slayksWood

When I pick them up they don't appear anywhere. I said inventory but I meant toolbar. Edited to reflect this

**Comment by SlayksWood** [comment]
@tasinei 
Did it happen more than once?
Did you have a message that you picked up the carcass?

Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tasinei** [comment]
@SlayksWood It has happened with every elk carcass & yes I do get an error message. 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3298160/output_log.txt)

**Comment by SlayksWood** [comment]
@tasinei 
Maybe you have any changes with the release of a new version 8.2.4?

**Comment by mirasrael** [comment]
@tasinei In theory it also may be related to laws on your server. Do you have any laws related to animals?

**Comment by SlayksWood** [comment]
Checked on 8.2.x. Wasn't able to reproduce, seems fixed.
If it happens again, please reopen and provide log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
