### ISSUE TITLE
[0.8.2.0 staging-993] Can use Objects with "Red" Status

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12519]
Treasury:
![image](https://user-images.githubusercontent.com/45708377/59264808-995e2d80-8c4c-11e9-9eeb-2b8e5f7caf64.png)
![image](https://user-images.githubusercontent.com/45708377/59264820-9f540e80-8c4c-11e9-8a69-6f846e55d317.png)
Registrar:
![image](https://user-images.githubusercontent.com/45708377/59261475-349fd480-8c46-11e9-9b89-b51bdb0acce1.png)
![image](https://user-images.githubusercontent.com/45708377/59261506-41242d00-8c46-11e9-8fbb-9fb097d122e7.png)
Bank:
![image](https://user-images.githubusercontent.com/45708377/59261602-77fa4300-8c46-11e9-8302-7686afe54d74.png)
![image](https://user-images.githubusercontent.com/45708377/59261613-7a5c9d00-8c46-11e9-982e-a39b215ae27e.png)
Contract Board:
![image](https://user-images.githubusercontent.com/45708377/59262444-e390e000-8c47-11e9-9c9e-6b5c5911d91b.png)
![image](https://user-images.githubusercontent.com/45708377/59262453-e8ee2a80-8c47-11e9-8221-3b76dde1bc12.png)
Distribution Station:
![image](https://user-images.githubusercontent.com/45708377/59262594-2ce12f80-8c48-11e9-91d2-e51f9955ddbd.png)
![image](https://user-images.githubusercontent.com/45708377/59262601-2f438980-8c48-11e9-8015-a8763a1133a4.png)

**Comment by SlayksWood** [comment]
Real Estate Desk:
![image](https://user-images.githubusercontent.com/45708377/59336733-c3285a80-8d07-11e9-917b-329ce5add32e.png)
![image](https://user-images.githubusercontent.com/45708377/59336737-c6bbe180-8d07-11e9-8693-b811eb0593bf.png)

**Comment by mirasrael** [comment]
Tabs now non-interactable if table isn't enabled.

![image](https://user-images.githubusercontent.com/475445/69542611-db7df000-0f9c-11ea-997a-e93dd9f0d33b.png)
