### ISSUE TITLE
Inaccessible titles after deleting other titles

### ISSUE THREAD

**Issue by StrayWolfe** [StrangeLoopGames/EcoIssues#12523]
Version: 0.8.1.4 beta

In the Registrar GUI, deleting a title higher up in the list of titles causes all titles below the deleted title to disappear from the GUI and become inaccessible. These titles still exist as titles in /titlelist, law propositions, etc but do not appear in the registrar.

**Comment by SlayksWood** [comment]
@StrayWolfe 
Can you provide your log file?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and save files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Or tell a little more with screenshots. I can't reproduce it in 8.2.0 staging-996 and 8.1.4

**Comment by SlayksWood** [comment]
I found such glitch. Step to reproduce:
- spawn registrar.
- add some titles.
![image](https://user-images.githubusercontent.com/45708377/59328400-f4e3f600-8cf4-11e9-93cd-88245fbd59a9.png)
- delete last title (District Manager 2)
![image](https://user-images.githubusercontent.com/45708377/59328412-00372180-8cf5-11e9-971e-30f35017bb03.png)
- mouse over at new last title (Czar 2). You have delete icon.
![image](https://user-images.githubusercontent.com/45708377/59328448-147b1e80-8cf5-11e9-93f1-784b09df2ce1.png)
- mouse over at any pre-last title. Delete Icon is disappearing. It also dissarers at last tittle.
![image](https://user-images.githubusercontent.com/45708377/59328631-86ebfe80-8cf5-11e9-8837-07de63098397.png)
- Add new title fixed it

**Comment by StrayWolfe** [comment]
I am unable to provide a log as the error was occurring on a server I do not control. I can no longer replicate the bug on the server; however, there are still several titles that exist but do not appear in the registrar even though the titles were created at this registrar by me.

![image](https://user-images.githubusercontent.com/10152038/59334523-4d4cd080-8cc0-11e9-8f0e-68d91644a07c.png)

**Comment by SlayksWood** [comment]
8.2.0 staging-996 still an issue
![image](https://user-images.githubusercontent.com/45708377/59345534-0212dc00-8d19-11e9-8f5c-66d504cb1668.png)

**Comment by johnkslg** [comment]
Can you recheck this? @SlayksWood

**Comment by beastyn** [comment]
Couldn't reproduce
