### ISSUE TITLE
Disconnecting from server, logging in as different user, and reconnecting causes exception

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12525]
This happens in the initial update and causes lots of problems with the rest of the game.
In my case, I logged in as a non-authed user (by turning off require auth in both the client's debug tuner and the server), which may or may not be related.  This also happened in master, but I imagine it will occur in Staging too.   

ArgumentNullException: Value cannot be null.

Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
VoiceManager.IsPlayerSpeaking () (at Assets/Scripts/Voice/VoiceManager.cs:95)
Assets.UI.Scripts.Voice.VoiceChatPanelUI.OnEnable () (at Assets/UI/Scripts/Voice/VoiceChatPanelUI.cs:23)
UnityEngine.Object:Instantiate(GameObject)
UI.UIManager:Open(String, BSONObject, UILayer) (at Assets/UI/Scripts/Manager/UIManager.cs:351)
UI.UIManager:Open(String, UILayer) (at Assets/UI/Scripts/Manager/UIManager.cs:327)
Player:ReceiveInitialState(BSONObject) (at Assets/Scripts/Player/Player.cs:174)
NetObjComponent:OnReceiveInitialState(BSONObject) (at Assets/EcoModKitInternal/Scripts/NetObjComponentInternal.cs:89)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject) (at Assets/EcoModKitInternal/Scripts/NetObjComponentInternal.cs:150)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:206)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at Assets/Scripts/Networking/NetworkManager.cs:509)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObject.cs:71)
Eco.Shared.Networking.NetworkClient:Update() (at C:/Eco/Server/Eco.Shared/Networking/NetworkClient.cs:284)
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:432)

**Comment by johnkslg** [comment]
Got this with just logging out and in as the same user, too.

**Comment by redwyre** [comment]
This is because you don't have a user_id set in your login session. Not sure what disabling auth is doing but that shouldn't ever happen.

**Comment by mirasrael** [comment]
Seems related to dev env only situation with RequireAuth false, so pushed it to 9.0.

**Comment by johnkslg** [comment]
Old bug, debug only, havent seen it in awhile. Closing.
