### ISSUE TITLE
Some tooltips close when trying to view their recipe tooltip within

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12535]
Confirmed for Steel, Epoxy and Concrete.
https://drive.google.com/open?id=1ydSYk59neU2c_RJ7lLhDwP6jALU19X7h

Lumber and Hewn Logs work, for example.

**Comment by SlayksWood** [comment]
It isn't a regression. in 8.1.4 all tooltips are closing.
It happens when you open tooltip from chat. Not any items and not always.

**Comment by D3nnis3n** [comment]
I can actually open my custom concrete tailings recipe in 8.1.4 just fine, so for me that is a regression. Tooltips are bugged heavily in 8.1.4 but they work sometimes. The tooltips for those few items work never or me (if 25 tries are enough at least.)

**Comment by Quadbro** [comment]
unreproducible in editor, oh, that will be tricky to find(

**Comment by Quadbro** [comment]
Yeah, found a problem... fixing...
