### ISSUE TITLE
[0.8.2.0 staging-1001] cant place a ramp if you use a tool

### ISSUE THREAD

**Issue by Sobaton** [StrangeLoopGames/EcoIssues#12539]
cant place a dirt ramp, if u cut a new tree
Step to reproduce:
- cut a tree (i test it whit birch)
- wait until a new tree is created
- hold a dirt ramp
- switch to Stone Axe tool 
- cut the "new" tree 
- try to place the dirt ramp (somewhere)

or:
- hold a dirt ramp
- switch to an sign RMB
- try to place the dirt ramp (somewhere)

it only occur if you switch the to a other item in the toolbar and use it (RMB)
-> test it whit dirt, stone and asphalt ramp
-> fix: put the dirt ramp back into stockpile or cart and back into hands, place dirt ramp

**Comment by SlayksWood** [comment]
@Sobaton 
Can you provide a more detailed steps to reproduce or video? or screenshots where and when you are holding in hand.

**Comment by Sobaton** [comment]
![grafik](https://user-images.githubusercontent.com/48158779/59516930-adab6000-8ec2-11e9-87fc-18613aeeb6ed.png)
step 1 holding a ramp (status ok)
![grafik](https://user-images.githubusercontent.com/48158779/59517036-e9dec080-8ec2-11e9-835b-00f624547d3e.png)
step 2 switch to a sign 
place the sign by using RMB
![grafik](https://user-images.githubusercontent.com/48158779/59517099-18f53200-8ec3-11e9-9fce-912640297cef.png)
try to place next ramp -> dont work

**Comment by Sobaton** [comment]
if you start holding the sign (itembar slot 3) and pull the stoneramps from a stockpile, i cant place the ramp/sign, until i switch to a other item and back to 3(sign) then i can place the sign 
![grafik](https://user-images.githubusercontent.com/48158779/59517420-ded86000-8ec3-11e9-905d-cecdccedfb52.png)

**Comment by SlayksWood** [comment]
Maybe need to add the placement of "new" ramps only with a hammer?
or add posobility as with stone:
![image](https://user-images.githubusercontent.com/45708377/59517525-7477ed80-8ecc-11e9-9d7e-ee3af0d00eaf.png)
![image](https://user-images.githubusercontent.com/45708377/59517540-7e015580-8ecc-11e9-91d0-2a0392a0886e.png)
![image](https://user-images.githubusercontent.com/45708377/59517551-8194dc80-8ecc-11e9-8fc4-caa48c21fe16.png)
