### ISSUE TITLE
[0.8.2.0 staging-1001] Store causing large FPS drop

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12538]
Step to reproduce:
- have 60 FPS
- spawn store
![image](https://user-images.githubusercontent.com/45708377/59513638-f1eb3000-8ec3-11e9-9424-257ea99cb58c.png)
- learn all skills (/allskills)
- open store 
![image](https://user-images.githubusercontent.com/45708377/59513684-07f8f080-8ec4-11e9-8f54-e2402754904f.png)
- Edit buying list, select all, submit
![image](https://user-images.githubusercontent.com/45708377/59513717-17783980-8ec4-11e9-8c84-4bec017109b7.png)
- freeze near 1-2 min
- wait spam stopped in chat
- After that my FPS drop to 4-8. No matter where I am
![image](https://user-images.githubusercontent.com/45708377/59514027-bac94e80-8ec4-11e9-94f6-c95e9c6b0d43.png)
- only reload help.

**Comment by gzatravkin** [comment]
Have no such FPS drop, is it stil occur? @SlayksWood

**Comment by SlayksWood** [comment]
@gzatravkin need to check after fixes #14188

**Comment by gzatravkin** [comment]
@SlayksWood How exactly this issue is relevant? You can now do the steps of issue, no freeze occur. Attaching video https://im2.ezgif.com/tmp/ezgif-2-fefe288bafe2.gif
. can't see any perfomance problem (but yes some exception of server)

**Comment by gzatravkin** [comment]
![ezgif-2-fefe288bafe2](https://user-images.githubusercontent.com/53317567/72471825-24df0480-37c2-11ea-876c-fb91ff52fce1.gif)

**Comment by gzatravkin** [comment]
https://drive.google.com/open?id=1xaGSBuUqgzUX6r-nR0aM_AfwpOMe0hBA

**Comment by johnkslg** [comment]
Ok, dug into this and it ended up requiring a refactor of the store system.
![image](https://user-images.githubusercontent.com/3536496/73411268-9c7c5b80-42b9-11ea-9197-b2cf021cfeab.png)

I changed the lists to be 'on demand'. This means they dont build till they become visible. So, scrolling slower, but the initial selection is fast, and it shouldnt affect frame rate after close.  Once you view all the items, they should display faster. 

Fix in progress.
