### ISSUE TITLE
USER ISSUE: invisible plant

### ISSUE THREAD

**Issue by owghard** [StrangeLoopGames/EcoIssues#12544]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
https://i.vgy.me/ZJ9axg.jpg

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by SlayksWood** [comment]
Apparently It's tree

**Comment by SlayksWood** [comment]
Do you have this problem now in 8.2.4?
If it happens again, please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing due to no response. If the issue reoccurs, please open a new issue.
