### ISSUE TITLE
USER ISSUE: Server crash on making law.

### ISSUE THREAD

**Issue by spylor** [StrangeLoopGames/EcoIssues#12548]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Trying to make a new law.
Playing the game while the law refreshes every time you select a new step in the law.
Game gives disconnection problems and after some of those full disco.

**Expected behavior:**
It should update the law page a lot quicker and not give connection problems.

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by D3nnis3n** [comment]
Can you add your full logfile, like described here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by D3nnis3n** [comment]
Closing due to no response. If the issue reoccurs, please open a new issue.
