### ISSUE TITLE
[0.8.1.4] Room breaks when there is a gap and you place an object

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12542]
Placing an object can break an adjacent room if there is an open door gap. This can be prevented by using a door or closing the gap.  

This is a hard bug to describe and there are multiple ways to trigger it. It can even cause multiple rooms to break at once. I wanted to report it so it can get documented. I will try to get more variations of the reproduction steps later. 

**Working Room**
![Finished Room](https://user-images.githubusercontent.com/47330823/59535343-927e2780-8ea5-11e9-8b52-0102381544f7.png)

**Room Broken by Placing Storage Chest**
![Broken Room](https://user-images.githubusercontent.com/47330823/59535345-927e2780-8ea5-11e9-8ae4-6d08f5ea7eff.png)

**Repaired Room by Replacing Block**
![Fixed Room](https://user-images.githubusercontent.com/47330823/59535344-927e2780-8ea5-11e9-8bcc-f23a22624f3d.png)

**Storage Chest is placed but Door Prevents Breaking**
![Door Room](https://user-images.githubusercontent.com/47330823/59535342-927e2780-8ea5-11e9-92f7-a2f3d195cdc9.png)

**Comment by SlayksWood** [comment]
will be fixed in 8.2.0. #12036
