### ISSUE TITLE
Simulation Tick Stops Randomly

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12546]
Randomly the tick for simulation ceases.   Restart may or maynot restart the tick and after restart the tick ,ay continue with no issues or will stop again randomly with no error that was noticed

As requested world file is linked:  https://www.dropbox.com/s/9izitufd9awvadp/pamelad_EcoGS_2019-06-15_08-01.zip?dl=0

**Comment by pamduncan** [comment]
This has now started happening several times a day and not just on my server.  I have had several reports where animals stop moving and plants stop growing and restarting the server solves it but I don;t think the tick should stop this often

**Comment by SlayksWood** [comment]
merged with #12641
