### ISSUE TITLE
[0.8.2.0 release-preview] Can't pick up carcasses

### ISSUE THREAD

**Issue by PanthereaL** [StrangeLoopGames/EcoIssues#12545]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. kill an animal (hare or bighorn tried)
2. go over to the carcass

**Expected behavior:**
It should have given me a green "pick up" silhouette, and allowed me to pick them up

**Actual behavior:**
Instead it does not show a silhouette, and I cannot pick them up. No errors given.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by SlayksWood** [comment]
Step to reproduce:
- kill an animal
- can pick up
![image](https://user-images.githubusercontent.com/45708377/59594292-3d881e80-90fc-11e9-8e80-f7ba69301247.png)
- relog or reload chunk
- you can't pick up
![image](https://user-images.githubusercontent.com/45708377/59594376-67414580-90fc-11e9-8b7b-07b632e1cb98.png)
![image](https://user-images.githubusercontent.com/45708377/59594389-6b6d6300-90fc-11e9-830a-fbd66e97b333.png)
