### ISSUE TITLE
[0.8.1.4] Possible Typo in WorldGenerator.eco ? 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12547]
There is overlap in the depth ranges that determine what percent of Iron Ore spawns. It happens in the Desert Biome; Iron Ore spawns at 0.25 frequency at depth range 10-15 and spawns at 0.05 frequency at depth range 13-30.  I'm not sure if this is intentional but it is the only case of overlap like this I can find in the config file.

![ironoreconfig](https://user-images.githubusercontent.com/47330823/59552912-da528c80-8f41-11e9-92be-6485070d775d.png)

**Comment by SlayksWood** [comment]
@craig-jong 
Given that people complain about the lack of iron, you can increase it a little at the same time.

**Comment by mirasrael** [comment]
@WeaselDog thanks for you attention!

**Comment by beastyn** [comment]
Changed a little bit
