### ISSUE TITLE
[meta] Better document how to identify version of Eco

### ISSUE THREAD

**Issue by mgold** [StrangeLoopGames/EcoIssues#12552]
I'd like to file an issue here, but I can't determine with certainly what version I'm running. I've poked at every option in Steam, and there's nothing in the game itself either. If version is a property of the server, it's not shown in the "Your Worlds" table.

**Comment by SlayksWood** [comment]
@mgold open Esc Menu, lower left corner
![image](https://user-images.githubusercontent.com/45708377/59579880-a610d480-90d7-11e9-9202-7aa4e2d758c4.png)
