### ISSUE TITLE
USER ISSUE: Secondary (and subsequent) menus not openable

### ISSUE THREAD

**Issue by BitsBytesGaming** [StrangeLoopGames/EcoIssues#12551]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Mouse over an item in the inventory that has enough uses to generate the "and X more recipes" text.
2. Mouse over the "and X more recipes" text.
3. Try to mouse over one of the recipes in this menu.

**Expected behavior:**
The subsequent menu/recipe should be openable.

**Actual behavior:**
Both menus closed after moving the mouse to attempt step #3.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods.

**Comment by BitsBytesGaming** [comment]
Video of this issue
[https://youtu.be/9Z3T06-_bzY](https://youtu.be/9Z3T06-_bzY)

**Comment by SlayksWood** [comment]
It's fixed in 8.2.0. #12024
