### ISSUE TITLE
USER ISSUE: Cannot grab logs when they are in ocean

### ISSUE THREAD

**Issue by BitsBytesGaming** [StrangeLoopGames/EcoIssues#12550]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
1. Cut logs such that they fall into the ocean.
2. Try to pick them up

**Expected behavior:**
Pick up the logs when E is pressed on them

**Actual behavior:**
Does not pick up logs

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by SlayksWood** [comment]
@BitsBytesGaming 
Tell me please.
Do you have a greean or yellow highlight?
Does it happen all the time?

The problem with the cutting of trees exists. But not found a way to reproduce it. Sometimes when cutting trees, they haven't a highlight and you can no longer cut down a tree. Only relog helps.
If you are managing to constantly lead to this bug, could you describe your step in more detail. It is possible in the video.

**Comment by SlayksWood** [comment]
merged with #11487
