### ISSUE TITLE
[0.8.2.0 release-preview] Smal size of Current citizen objective

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12556]
Write long text without spaces:
![image](https://user-images.githubusercontent.com/45708377/59598138-29e0b600-9104-11e9-80de-0088ec79d662.png)

**Comment by WeaselDog** [comment]
@SlayksWood Is this fixed now?

**Comment by WeaselDog** [comment]
This is fixed, but there is a new issue that part of the objective gets cut off if it is too long.
