### ISSUE TITLE
[0.8.2.0 staging 1001] Rocket from Old Growth Redwood when collision occurs during a fall

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12553]
The upper part of the Old growth Reedwood flies away very far from the place of the fall (it can fly off further). Occurs when a upper part tree collides an obstruction during a fall (usually another tree).
![2019 06 17 Redwood rocket](https://user-images.githubusercontent.com/45708377/59582157-fa1fb700-90df-11e9-85ca-5a3ed01e30a1.gif)

**Comment by D3nnis3n** [comment]
That's hilarious.

**Comment by SlayksWood** [comment]
also see #10720

**Comment by SlayksWood** [comment]
> If a tree is logged it sometimes teleports 5-10 blocks away and falls from there.
We have no clue how and why this occurs. #14171

**Comment by SlayksWood** [comment]
> Trees that are cut down always behaved weird. It comes mostly from their branches interacting with neighbor trees resulting in the weirdest dances and space launches for tree trunks.
> 
> I am sure certain limits to the initial movement speed and rotation should be introduced for falling trunks preventing such stuff from happening.
> 
> As of now it is totally handled by Unity engine so the change in behavior (if one actually took place) could only come from Unity upgrades.
> 
> However I did not notice any unusual behavior, only common space launches. If you plant trees like I do (in every adjacent block) such launches would be pretty common for you as well.

**Comment by TwixterZ** [comment]
This behavior does no longer happens with old growth redwood in latest develop build
