### ISSUE TITLE
Eco Biome Generation Issues/Improvements

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#12559]
Gen:
- Cold forests should not spawn near coasts-- only warm forests should. This change will require a deeper world gen tweak.

Plants:
- Warm forests should not contain salal, only cold forests should. Common grass can be used as ground cover in warm forests until other plants are assigned to do so.
- Warm forests should not contain Spruce or Fir trees at all. 

Geology:
- In Deserts, remove rocky soil beneath desert sand, and replace with sand or with nothing.

**Comment by D3nnis3n** [comment]
Actual sand in the desert, anyone?

**Comment by beastyn** [comment]
- Dont see common grass in the Warm forests. They are actually quite bold now. If common grass will be able to coexist with wetland?
![bandicam 2020-02-06 12-53-39-284](https://user-images.githubusercontent.com/27898520/73916667-b7655600-48df-11ea-9d04-276d8ea4c5d0.jpg)

@keegan-o  If we OK with this one, then close it.

**Comment by D3nnis3n** [comment]
This forest definately has different, much bigger issues than common grass, lol. Looks like a death forest out of some scary movie. :D
