### ISSUE TITLE
USER ISSUE: God View

### ISSUE THREAD

**Issue by SirAlfee** [StrangeLoopGames/EcoIssues#12569]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
Launch game

**Expected behavior:**
To be in the person

**Actual behavior:**
Floating above the world looking down at myself frozen

**Do you have mods installed? Does issue happen when no mods are installed?:**
Floating above the world looking down at myself frozen

**Comment by johnkslg** [comment]
@SirAlfee are you on our discord?  Message me there @johnk

**Comment by SlayksWood** [comment]
@johnkslg 
I think It's dup #12402.
It was fixed in 8.2.0

**Comment by SirAlfee** [comment]
That’s it but I got it today

**Comment by Quadbro** [comment]
Any info on that one?
