### ISSUE TITLE
Server disconnects only for admin

### ISSUE THREAD

**Issue by Pados** [StrangeLoopGames/EcoIssues#12566]
Im playing with 3 friends on a dedicated server hosted by Nitrado.net.
I am admin and I often get the red disconnect symbol while playing with my friends. It usually happens around our "home base" where we built our house and stuff (267, 318). There is a mine underneath and it seems to be a little buggy (mined stone disappearing and showing up on the surface, carts turning around - sometimes disappearing). Maybe its connected to this?
But it also happens often when there are 2 people or more working together mining stone for example in other locations than our home base.
I get the disconnect symbol - my friends dont.
After relogging it usually works for me again.
The server doesnt crash and my friends can keep playing on the server without problems.

Im playing through steam on the current release. I also tried the StrangeLoopGames client but I got the same problems.
Ingame ping is 33ms.
I dont think its a network/firewall problem, because I can play sometimes normally in other map locations without disconnects.

I already reinstalled the game a few times, restarted server, etc. - still the same.

Maybe theres a bug in our map or my user is messed up?

User name is Pados (Steam ID 76561198083371853).

Map backup: [https://www.dropbox.com/sh/wss21wh174qbx9p/AAAOk7uztuN7QlaSwh1Sr3Mca?dl=0](https://www.dropbox.com/sh/wss21wh174qbx9p/AAAOk7uztuN7QlaSwh1Sr3Mca?dl=0)
There is no exception file created in the server dump folder, when I get disconnects.

**Comment by SlayksWood** [comment]
@Pados 
You need to play for a while so that your disconnects appear. And then provide your logs.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Pados** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3314528/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3314529/Player-prev.log)

**Comment by SlayksWood** [comment]
Please indicate your computer's specification.
Can you look the CPU load during the game?
Also try playing a little on any other server. Will you face a similar problem?

**Comment by Pados** [comment]
@SlayksWood 
CPU: Intel i5 7600K (@ 3.80 GHz)
GPU: NVIDIA GeForce GTX 1060 (6GB)
RAM: 16GB DDR4
Mainboard: MSI B250M Pro-VDH
256GB SSD
Win10 Pro

CPU load is at 30-50 %.

It happens almost every time when I mine a few stones and dont pick the pieces up immediately - my friends dont have these problems.
I tried this on an other server and the same happens.

**Comment by SlayksWood** [comment]
Sorry for not able to help in time.
This should work better after 8.3.0 release. If you still have this problem, please reopen.
