### ISSUE TITLE
Steam Player can neither create a world nor login to any server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12560]
Logs in attachment
[log_190617032101.log](https://github.com/StrangeLoopGames/EcoIssues/files/3299034/log_190617032101.log)
[output_log (3).txt](https://github.com/StrangeLoopGames/EcoIssues/files/3299035/output_log.3.txt)

**Comment by mirasrael** [comment]
Lets wait for 8.2 if problem still persists

**Comment by CuAnnan** [comment]
Why is this not a Critical issue? I can't play the game because it crashes.

**Comment by SlayksWood** [comment]
@CuAnnan 
Have you updated to version 8.2.1?

**Comment by D3nnis3n** [comment]
And do you have logfiles?

**Comment by mirasrael** [comment]
@CuAnnan any updates on this issue?
1. Do you still have this issue?
2. When it fails - which error you see?

**Comment by D3nnis3n** [comment]
Closing due to no response. If the issue reoccurs, please open a new issue.
