### ISSUE TITLE
[0.8.2.0 release-preview] Can't host your own world (MacOS)

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12567]
Step to reproduce:
- start game
- click Host your own world
![2019-06-18_19 10 28](https://user-images.githubusercontent.com/45708377/59701450-57118f00-91fe-11e9-9bf3-87737b612767.png)
- you must be transferred to the world creation tab. But this tab isn't present.
![2019-06-18_19 12 26](https://user-images.githubusercontent.com/45708377/59701536-845e3d00-91fe-11e9-9ab6-1c0cac29407a.png)
- Also, there is no tab for hosting the world if you go through a new game

This tab is missing:
![image](https://user-images.githubusercontent.com/45708377/59701642-ba9bbc80-91fe-11e9-98f2-b1cdc93853ed.png)

**Comment by mirasrael** [comment]
Removed menu entry on Mac and Linux. World hosting isn't working on these platforms yet.
