### ISSUE TITLE
[0.8.2.0 release-preview] One type of limestone block is offset in axis

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12565]
Because of this, holes appear when stones connect between themselves
![image](https://user-images.githubusercontent.com/45708377/59661425-7800c280-91b3-11e9-80bf-eb4a18ff6d3d.png)
![image](https://user-images.githubusercontent.com/45708377/59661605-d332b500-91b3-11e9-96f7-660a27c9849e.png)
![image](https://user-images.githubusercontent.com/45708377/59661696-037a5380-91b4-11e9-83ce-49611e5a1ddd.png)

**Comment by keegan-o** [comment]
fixed in staging
