### ISSUE TITLE
Converting staging map to release creates massive amount of redwoods anywhere, even in desterts

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12579]
Map BEFORE conversion to release: https://download.godsofwar.de/eco/before.zip

**Comment by beastyn** [comment]
Was this world created on staging?

**Comment by D3nnis3n** [comment]
Yes, that is what i mean with "staging map" converting to "release".

**Comment by beastyn** [comment]
Then fixed

**Comment by D3nnis3n** [comment]
When, where?

**Comment by SlayksWood** [comment]
@D3nnis3n 
was It create with #12278 bug? Then when converting the trees should remain

**Comment by D3nnis3n** [comment]
No! The trees only exist AFTER converting. They are not there BEFORE converting.

**Comment by D3nnis3n** [comment]
I worked on that map 7 days ago just fine - no redwoods to see. Today converted to release and everything is full of redwoods.
