### ISSUE TITLE
USER ISSUE: Farming: can't replant after harvest

### ISSUE THREAD

**Issue by antaeusdk** [StrangeLoopGames/EcoIssues#12576]
**Version:** 0.8.2.0 beta

**Steps to Reproduce:**
1. Harvest fx. wheat
2. Try and re-plant with seeds.

**Expected behavior:**
The wheat seeds will be planted.	

**Actual behavior:**
Plant is dead. Harvest.
Digging the dirt and replacing it, and using a hoe will still state the same "error". 

**Do you have mods installed? Does issue happen when no mods are installed?:**
Plant is dead. Harvest.
Digging the dirt and replacing it, and using a hoe will still state the same "error".

**Comment by SlayksWood** [comment]
You can't plant by hand:
![image](https://user-images.githubusercontent.com/45708377/59758683-2893c280-9297-11e9-9c58-864cca6ec913.png)
![image](https://user-images.githubusercontent.com/45708377/59758760-5416ad00-9297-11e9-9d9c-35a2599986f4.png)

But you can plant with steam tractor sower:
![image](https://user-images.githubusercontent.com/45708377/59758654-1b76d380-9297-11e9-88ef-564792a6778c.png)

**Comment by mirasrael** [comment]
If it prevents your normal gameplay you can update to this version (8.2.1 + hot-fixes) before 8.2.2:
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3306559/EcoServer.zip)

**Comment by antaeusdk** [comment]
Thank you for a quick response! 

Have a nice day!
