### ISSUE TITLE
[8.2.0] Numbers in graph Y axis not shown

### ISSUE THREAD

**Issue by ky0uraku** [StrangeLoopGames/EcoIssues#12572]
![изображение](https://user-images.githubusercontent.com/48658286/59745911-73eda700-927e-11e9-99b8-456d0cc655a0.png)

Reproduced on Firefox 67.0.3 and Edge 44.17763.1.0

**Comment by SlayksWood** [comment]
Wrong values

**Comment by mirasrael** [comment]
Values seems correct, but space isn't enough on Y axis

**Comment by ky0uraku** [comment]
No, values isn`t correct - after update to 8.2 everyting was multiplied by 100.

For example (in past we had 150 max pollution points):
![изображение](https://user-images.githubusercontent.com/48658286/59852026-abd81580-9376-11e9-9489-ff3f204e4bb2.png)

**Comment by mirasrael** [comment]
Hmm. I tested with Filmy Fern and it shows same values.

**Comment by mirasrael** [comment]
From Gods of Wars server, it shows reasonable values for Ground Pollution:
![image](https://user-images.githubusercontent.com/475445/59853464-987a7980-9379-11e9-9852-532016c5934b.png)

Can you provide your save?

**Comment by mirasrael** [comment]
Also it may be related to biomes.

**Comment by ky0uraku** [comment]
Sure, sent you a message in Discord.

**Comment by mirasrael** [comment]
Ok. Actually there previously was used sum for aggregation values for data points, now it switched to average.
