### ISSUE TITLE
[Beta 0.8.2] Clay Shader not working correctly

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12578]
used the skid steer to dig into dirt, somehow the clay looks odd. But only on some blocks (right part)
![clayshader](https://user-images.githubusercontent.com/5678451/59757337-d600d900-928b-11e9-93ac-66a8597eb562.png)

**Comment by keegan-o** [comment]
This was because of metalness/smoothness not working with the previous shader correctly, should be addressed now. (might also be the lack of full shadow which was also fixed)
