### ISSUE TITLE
Loan Contracts broken when using different account than your own and your own does not have the currency to offer

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12589]
![1](https://user-images.githubusercontent.com/25908592/59783727-1595e800-92c1-11e9-8b8f-cda696b10998.png)
![2](https://user-images.githubusercontent.com/25908592/59783728-1595e800-92c1-11e9-8aa1-8051ea0c45e2.png)

**Comment by D3nnis3n** [comment]
Okay, it works when i have a single dollar, dropping to low.

**Comment by WeaselDog** [comment]
Fixed so it checks the correct account:
![LoanMultipleAccounts](https://user-images.githubusercontent.com/47330823/70084942-25ca2700-15c4-11ea-850d-7f5c9e37398b.png)

**Comment by beastyn** [comment]
Hmm, it does not if there is no currency on your default account.
![bandicam 2019-12-04 10-43-32-193](https://user-images.githubusercontent.com/27898520/70115936-12ca5c00-1683-11ea-8653-4ff276a94003.jpg)

**Comment by WeaselDog** [comment]
@beastyn Sorry I meant the fix is in the PR that was submitted but not merged yet

**Comment by beastyn** [comment]
Ok, you just did it, Thanks )
