### ISSUE TITLE
Server does not start anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12582]
> [14:38:28.625] [1] [ Info] [Eco] Failed to load server, Exception was Exception: ArgumentException
> Message:An element with the same key but a different value already exists. Key: 2
> Source:System.Collections.Immutable
> 
> System.ArgumentException: An element with the same key but a different value already exists. Key: 2
>    at System.Collections.Immutable.ImmutableDictionary2.HashBucket.Add(TKey key, TValue value, IEqualityComparer1 keyOnlyComparer, IEqualityComparer1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
>    at System.Collections.Immutable.ImmutableDictionary2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
>    at System.Collections.Immutable.ImmutableDictionary2.Add(TKey key, TValue value)
>    at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func2 apply)
>    at Eco.Core.Utils.ControllerDictionary2.<>c__DisplayClass8_0.<Add>b__0()
>    at Eco.Core.Utils.ControllerDictionary2.ApplyChange(Action change)
>    at Eco.Core.Utils.IDDictionary`2.Add(INetObject player)
>    at Eco.Gameplay.Economy.BankAccountManager.TryCreateUserAccount(User user)
>    at Eco.Gameplay.Players.User.Initialize()
>    at Eco.Gameplay.Players.UserManager.Initialize(TimedTask timer)
>    at Eco.Server.PluginManager.InitializePlugins()
>    at Eco.Server.PluginManager..ctor()
>    at Eco.Server.Startup.Start(String[] args)"

https://download.godsofwar.de/eco/bug.zip

**Comment by D3nnis3n** [comment]
Happened after this crash: https://github.com/StrangeLoopGames/EcoIssues/issues/12581

**Comment by Young-Beans** [comment]
The error still persists and the status should not be marked as fixed. 

Received the same database corruption with a similar error:

[Error] [Eco] Failed to start the server. Exception was Exception: ArgumentException
Message:An element with the same key but a different value already exists. Key: 'Eco.Gameplay.Components.LinkComponent+SettingsKey'
Source:System.Collections.Immutable

System.ArgumentException: An element with the same key but a different value already exists. Key: 'Eco.Gameplay.Components.LinkComponent+SettingsKey'
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
Outer Exceptions:
Exception has been thrown by the target of an invocation.

**Comment by mirasrael** [comment]
@Young-Beans error you posted is a different error. While it may look similar there lot of different places in code which may throw  "An element with the same key but a different value already exists" error. If you read previous error you may notice it says about "Key: 2" while error you posted says about "Key: 'Eco.Gameplay.Components.LinkComponent+SettingsKey'".

**Comment by mirasrael** [comment]
It is nothing DB related. Error like that happens with base collection - Dictionary - which used in 1000s different places and different business workflows. In that particular case it seems like it expects to have Settings for linked inventory, but those doesn't present. There you may just add check if it missing or not and ignore error, but most important why it doesn't have settings when it expect to have these settings? Probably these settings not saved and if we just ignore an error then we will have another bug when you linked inventory settings will reset every time when you open inventory or something like that.
It may sound not critical, but there another places where you have mapping between user and his bank account. And if for some reason bank account disappear and won't be available for User and we just ignore missing key (User in that case) then it will be much more serious. So there reasons why we do not use approach "ignore-if-missing" everywhere. Better to get an error and fix it than let situations like described to go.
So for every such issue we need to have separate solution and separate ticket.
