### ISSUE TITLE
player report:  excavator kicks player out while driving

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12586]
player report:  excavator kicks player out while driving.  Player would not make a bug report

**Comment by SlayksWood** [comment]
I can only suggest that It happens when using /fly. Or when trying to reproduce /fly (jump in excavator, or jump from cliff into an excavator and press E). But then it turns out merged with #11919

**Comment by SlayksWood** [comment]
should be fixed with https://github.com/StrangeLoopGames/Eco/pull/5186
