### ISSUE TITLE
[0.8.2.3] Not all specializations are shown in "Specialties to show" window after migration.

### ISSUE THREAD

**Issue by Fradack** [StrangeLoopGames/EcoIssues#12595]
![Screenshot_259](https://user-images.githubusercontent.com/35646065/59800965-2d349700-92e8-11e9-91f4-f3186d13088a.png)
![Screenshot_260](https://user-images.githubusercontent.com/35646065/59800966-2d349700-92e8-11e9-8630-73439125d2f1.png)

**Version:** 0.8.2.1 beta

**Steps to Reproduce:**
Hello the trades we have basic are not all displayed in the bottom left (the experience)

Old version: 0.8.1.4
Current Version: 0.8.2.1

**Expected behavior:**
this should show all the chosen trades on the W key

**Actual behavior:**
It displays only 2 or 3 

**Do you have mods installed? Does issue happen when no mods are installed?:**
It displays only 2 or 3

**Comment by SlayksWood** [comment]
@Fradack 
you can customize skill display 
![image](https://user-images.githubusercontent.com/45708377/59822413-77436a00-9334-11e9-92b6-15c5a6937cc2.png)
Can you tell me the levels of the rest of your specializations?

**Comment by Fradack** [comment]
Hello 

Hewing level 4
Logging level 3
Bricklaying Level 1
Mining level 2
Survivalist level 3
![Screenshot_265](https://user-images.githubusercontent.com/35646065/59869416-8efe0b00-9393-11e9-8db8-283cffe7f9a7.png)

**Comment by SlayksWood** [comment]
Step to reproduce:
- create world 8.1.4 and take some specialization.
![image](https://user-images.githubusercontent.com/45708377/59917169-e2229d00-9429-11e9-8cf7-091494c6ab58.png)
- use other settings. Everything is displayed correctly
![image](https://user-images.githubusercontent.com/45708377/59917178-ea7ad800-9429-11e9-82c2-e3d7797ab171.png)
![image](https://user-images.githubusercontent.com/45708377/59917187-efd82280-9429-11e9-87bb-922df22a5f3b.png)
- Convert the world to a new version (in my case 8.2.3) Not all skills appear. (Hewing, Tailoring, Bricklaying, Mining are missing).
![image](https://user-images.githubusercontent.com/45708377/59917495-c23fa900-942a-11e9-83cd-c0c602066195.png)
- use other settings. Missing specializations are not returned.
![image](https://user-images.githubusercontent.com/45708377/59917656-2b272100-942b-11e9-80ce-386075e0291e.png)
![image](https://user-images.githubusercontent.com/45708377/59917662-2f533e80-942b-11e9-8513-7a00c53e4b4d.png)
- try to gain exp. Specializations will return which can get experience. Mining level 7 will not return.
![image](https://user-images.githubusercontent.com/45708377/59918151-90c7dd00-942c-11e9-9985-026af383ed1f.png)

**Comment by Fradack** [comment]
Hi,

I have no updates available from Steam
so for now I can not see if it works on my side

"create world 8.1.4 and take some specialization"

I'm on a server every time I update the server how do you want me to put the 0.8.1.4 and you're not available on steam

**Comment by SlayksWood** [comment]
This information is not for you. I wrote steps to reproduce to fix this problem.
@Fradack 
You can do next to see all the specializations. You need just get experience at each missing specializations and they should will display. If not, you can write here and provide logs.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Fradack** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3314397/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3314398/Player-prev.log)
I'm coming back to you once I've tried what you mentioned at the top

**Comment by Quadbro** [comment]
specialties status shows last gained exp
