### ISSUE TITLE
USER ISSUE: Stuck on "Work Orders" Tutorial

### ISSUE THREAD

**Issue by Rookie261** [StrangeLoopGames/EcoIssues#12596]
**Version:** 0.8.2.1 beta

**Steps to Reproduce:**
1. Do tutorials until you get the "Work Orders" Tutorial
2. Complete the first step (Opening the tent)
3. Attempt to skip the tutorials by clicking on the x on a different bubble, then hit the check box to skip all tutorials

**Expected behavior:**
Closed all tutorials including the "Work Orders" tutorial

**Actual behavior:**
All tutorials disappeared, except for the "Work Orders" bubble

**Do you have mods installed? Does issue happen when no mods are installed?:**
All tutorials disappeared, except for the "Work Orders" bubble

**Comment by Rookie261** [comment]
Can be fixed by re-launching the world (or rejoining the server)

**Comment by SlayksWood** [comment]
@Rookie261 
please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Rookie261** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3310735/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3310736/Player-prev.log)

**Comment by D3nnis3n** [comment]
Couldn't be reproduced. Please open a new issue if this happens again.
