### ISSUE TITLE
if clauses seem bugged

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12594]
First Example:
If you are a "demographics" a allocate 50 dollar
otherwise allocate 100 dollar

I'm in demographics a but getting 100 dollar.

Second example:
If you are world leader allocate 200 dollars
otherwise if your get elected actions > 0 allocate 100 dollars
otherwise tax 0 dollars

Everyone that is not a world leader or has no elected actions gets 200 dollars.

Something is wrong.

**Comment by D3nnis3n** [comment]
Added investigate, the first one was a report, the second one i have as law, but could not try further to reproduce, given i'm on vacation now.

**Comment by SlayksWood** [comment]
@D3nnis3n 
And you can find out the names of servers or screenshots of the laws?

**Comment by D3nnis3n** [comment]
Sure.

First law: https://cdn.discordapp.com/attachments/393509686487285763/591003012890361862/unknown.png

Second law:
![law2](https://user-images.githubusercontent.com/25908592/59829615-26387380-933e-11e9-97ba-be6c72c200aa.png)

(At least law 2 was the exact same in my last three cycles and worked there)

**Comment by D3nnis3n** [comment]
Player with law 1 reported it works after Hotfix 8.2.2 for some reason. I'm dropping priority to medium, cannot take a look if my law works.

**Comment by SlayksWood** [comment]
My law:
![unknown](https://user-images.githubusercontent.com/45708377/59845505-3ebc8400-9366-11e9-98e2-a38917889c48.png)
All citizen get money as world leader.
![image](https://user-images.githubusercontent.com/45708377/59845734-b9859f00-9366-11e9-8d02-88f97d1067cf.png)

**Comment by mirasrael** [comment]
Seems it should start working ok after server restart.

**Comment by SlayksWood** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/45708377/59907196-28203680-9413-11e9-9d33-b139d7d8e953.png)
