### ISSUE TITLE
[8.2.1] "Ask an Expert To Craft It" List No Longer Works

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12599]
The "Ask an Expert To Craft It:" list shows that no one gets benefits from skills. 
This is true for other players' skills as well as your own, I just have the screenshot for myself with Mortaring to show what I mean.

![mortaredstone](https://user-images.githubusercontent.com/47330823/59810934-6ce58980-92bc-11e9-87c0-4a3001b4c1b3.png)

**Comment by WeaselDog** [comment]
Here is a screenshot from 8.1.4 to show this is a new issue since 8.2

![mortaredstones](https://user-images.githubusercontent.com/47330823/59811394-93a4bf80-92be-11e9-99d8-4b31ab84a2b5.png)

**Comment by SlayksWood** [comment]
It doesn't work only when you mouseover at recipe.
It works if you mouse over at ingridients on craft table
![image](https://user-images.githubusercontent.com/45708377/59835227-f72bfd00-9351-11e9-8e7c-7e793ad47a08.png)

**Comment by SlayksWood** [comment]
It doesn't work only when you mouseover at recipe.
It works if you mouse over at ingridients on craft table
![image](https://user-images.githubusercontent.com/45708377/59835227-f72bfd00-9351-11e9-8e7c-7e793ad47a08.png)

**Comment by SlayksWood** [comment]
It doesn't work only when you mouseover at recipe.
It works if you mouse over at ingridients on craft table
![image](https://user-images.githubusercontent.com/45708377/59835227-f72bfd00-9351-11e9-8e7c-7e793ad47a08.png)

**Comment by SlayksWood** [comment]
It doesn't work only when you mouseover at recipe.
It works if you mouse over at ingridients on craft table
![image](https://user-images.githubusercontent.com/45708377/59835227-f72bfd00-9351-11e9-8e7c-7e793ad47a08.png)

**Comment by SlayksWood** [comment]
It doesn't work only when you mouseover at recipe.
It works if you mouse over at ingridients on craft table
![image](https://user-images.githubusercontent.com/45708377/59835227-f72bfd00-9351-11e9-8e7c-7e793ad47a08.png)

**Comment by mirasrael** [comment]
Fixed in 8.2.4
![image](https://user-images.githubusercontent.com/475445/59924685-f624c980-943e-11e9-96f6-c36de0d77a0f.png)
