### ISSUE TITLE
Make the item filter display categories like the dropdown selector

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12598]
This selector (on a ConstitutionalArticle in a bill or rights object):
![image](https://user-images.githubusercontent.com/3536496/59803463-5e897480-92a0-11e9-80ea-dc367b7d8822.png)

Should display categories and help text like this selector (in a law cause):
![image](https://user-images.githubusercontent.com/3536496/59804855-61866400-92a4-11e9-9a94-252cbe2c03d8.png)

In fact, make it use the exact same code.

**Comment by beastyn** [comment]
@johnkslg is it valid? I don't see this long lists on amendments anymore.

**Comment by johnkslg** [comment]
Its gone
