### ISSUE TITLE
Egyptian darkness

### ISSUE THREAD

**Issue by owghard** [StrangeLoopGames/EcoIssues#12590]
0.8.2.1
Light from firecamp in room but around Egyptian darkness.

https://streamable.com/zoem0
https://i.vgy.me/6qNcAk.png
https://i.vgy.me/b34LtM.png

**Comment by owghard** [comment]
Light from firecamp in room but around Egyptian darkness.

https://streamable.com/zoem0
https://i.vgy.me/6qNcAk.png
https://i.vgy.me/b34LtM.png

**Comment by D3nnis3n** [comment]
This actually cannot be fixed by brightness and also occurs in rooms, so i'm raising priority.

**Comment by beastyn** [comment]
Reflections cousing it. Switch it off and everything will be fine.

**Comment by beastyn** [comment]
Or switching it off-on

**Comment by beastyn** [comment]
My repro steps.
1. Check that "reflections" is" off
2. Make some tunnel and cavern
3. Make midnight
4. Turn on reflections

**Comment by Hexcodes** [comment]
Seems like the fixing of this bug leads to a new bug in 8.2.4 -> When I enter a room it's getting really dark and sometimes it seems like the dark is a little bit green. In 8.2.3 this wasn't the case.

**Comment by SlayksWood** [comment]
@Hexcodes 
It isn't fixed in 8.2.4. It will be fixed in 8.2.5.
