### ISSUE TITLE
Plant already exist here bug (worse than ever)

### ISSUE THREAD

**Issue by JPLab21** [StrangeLoopGames/EcoIssues#12593]
Hello, we can't seed anywhere, there is an error where it says Plant already exist here. I have a whole 10 by 10 Camas farm where I just can't reseed anywhere without having this error, but there is nothing! When I take the Soil Sampler, it says The Plant is Dead. Harvesting. Even if I relog it doesn't fix it, or taking a shovel and tilling it again also. Farming is pretty much dead since we can't reseed and regrow anything. Thank you.

**Comment by quequiere** [comment]
Hello, i confirm this problem apear on my server

**Comment by beastyn** [comment]
Have this here #12576 
Should be fixed with nex hotfix
