### ISSUE TITLE
USER ISSUE: Plant already exists there.

### ISSUE THREAD

**Issue by Fradack** [StrangeLoopGames/EcoIssues#12597]
**Version:** 0.8.2.1 beta

**Steps to Reproduce:**
remove the earth
put the land back
beak the earth
plant (without success)

**Expected behavior:**
the expected behavior is that the plant should be planted

**Actual behavior:**
the current behavior is that the plant does not plant because the game believes that there is already a plant already planted. (Even if we removed the earth, then put back) planted. (Even if we removed the earth, then put back)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

** other **
https://www.youtube.com/watch?v=fXAR361OHig&feature=youtu.be

before this bug we had no problem.
the server was in version: 0.8.1.4 on a pass the server in
Version: 0.8.2.1

**Comment by behdahh** [comment]
It also appears to be the case that since this 0.8.2.1 update the seeds drop rate from plants that needs to be re-planted (f. ex. beets) is extremely low compared to before, which may or me not be related.

**Comment by mgold** [comment]
I can confirm @behdahh's comment: I can't replant my mushrooms with the few spores I got from pulling up my field.

**Comment by SlayksWood** [comment]
dup #12576
