### ISSUE TITLE
Cement Kiln was polluting even though it wasn't running

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1259]
... At least according to the status tab.  It had a work order queued, but was out of fuel and so was not running.  We observed that the pollution value seemed to match the pollution value for a different table in the same room that was currently running

**Comment by voyagebass** [comment]
May I add something? Had a Blast Furnace in a room, running iron ingots. placed a Cement Kiln besides it. Cement Kiln showed lifetime pollution value growing the same values the Blast Furnace had. Removed the Cement Kiln. Same numbers in Blast Furnace as with the Kiln besides it. Placed the Kiln again. Now shows the lifetime pollution value of the Blast Furnace at the time the Cement Kiln was placed.
