### ISSUE TITLE
Mouse Wheel is inverted on linux

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12601]
Report from a Support-Ticket

**Comment by SlayksWood** [comment]
I think we can merged It with #12042.
If you add the setting of any control, then there will be no problem with inverting the mouse.

**Comment by D3nnis3n** [comment]
Well, this is a regression, it has not been like this in 8.1.4.

**Comment by redwyre** [comment]
Do you mean the mouse scroll wheel?

**Comment by radiantraptor** [comment]
The issue has been opened due to my report. Yes, it's the mouse wheel that behaves inverted everywhere within the game.

**Comment by D3nnis3n** [comment]
Sorry!

**Comment by Lafudoci** [comment]
I have the same issue on Manjaro 19.

**Comment by Mageas** [comment]
Same issue, i'm on Manjaro KDE 20

**Comment by radiantraptor** [comment]
It looks like the issue is currently fixed in the beta 9.0.5.

**Comment by D3nnis3n** [comment]
Great to know :)
