### ISSUE TITLE
Server is not writing new spawn coords to worldgenerator.eco

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12603]
update to 8.2.2,  Create a new world and log in.  Stop sever and check worldgenerator.eco and the spawn coords are still 0.0.0 and so when server restarts now players are spawning at 0,0,0  this was not happening before in previous versions when the server established coords for a server spawn location it was writing them to the worldgenerator.eco

**Comment by D3nnis3n** [comment]
Spawn coordinates are now saved in users.eco.

**Comment by D3nnis3n** [comment]
Well, not the default ones, only the ones for food it seems.
