### ISSUE TITLE
VSync might not work correctly [Performance]

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12602]
Over the past few weeks i got several people recommending me to tell players to disable VSync as that would increase fps by quite much. Actually, that is true for me too. As soon as i use the defaults my fps drop to 40 in crowded areas on a pretty fresh world, but when turning vsync off, i get to numbers of up to 140.

We should
a) disable VSync by default.
b) check what's wrong with it, given this does not work for everyone.
c) change it so that it is clear to people how it works.
(In other games i write my wanted fps limit into it, here i need to put some framesync times per second into it, which defaults to 1 for some reason? I don't understand what i have to type there. If i type in my monitor frequency of 144, like i would do in other games, my fps drops massively to 30.)

**Comment by mirasrael** [comment]
@D3nnis3n 
It is divider for you monitor frequency. So, 
- for default value 1 it will target FPS 144Hz (or 60Hz for 60Hz monitor).
- for value 2 it will target half of this (144Hz = 72 FPS, 60Hz = 30 FPS)

**Comment by mirasrael** [comment]
1. VSync now is disabled by default.
2. It prevents from setting VSync to wrong value. It now has valid label "syncs / frame", it may be not clear, but in most cases you shouldn't change it.

**Comment by D3nnis3n** [comment]
Default is 300 at current staging. I still don't understand it, lol.

**Comment by mirasrael** [comment]
It was changed to 120.

**Comment by redwyre** [comment]
Can we change the syncs/frame thing? It's too difficult to use

**Comment by D3nnis3n** [comment]
Feel free to take that on you ;P
