### ISSUE TITLE
Tailings Output on Recipes are doubled

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12608]
Bloomery 2:1
Blast Furnace 1:1

It should be:
Bloomery 1:1
Blast Furnace 0.5:1

This is a major issue hindering fun in the game and therefore critical. Not everyone has fun digging up half the world for placing tailings, especially when it is not intended to be that hard.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/59946224-cfef3180-941e-11e9-8a39-cf304db29bb9.png)

This is what mine looks like on release.

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/59946268-e7c6b580-941e-11e9-9e85-5ba8148a25a7.png)

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/59946968-e0081080-9420-11e9-8242-ec81964425ad.png)

this is a screenshot from 8.0.

**Comment by D3nnis3n** [comment]
Hey craig, i've investigated a bit more with people having the issue. The recipe shows correctly, but the actual output is wrong:
https://cdn.discordapp.com/attachments/312991502697627658/591207505816977408/unknown.png

**Comment by D3nnis3n** [comment]
At least that is what all the reports are i got.

**Comment by craig-jong** [comment]
Alright, thats a different issue. Probably a rounding one, actually though I swear we closed all those.

**Comment by D3nnis3n** [comment]
Yeh, we also had reports of issues like a recipe displaying you need 4 hares to craft meat but in the end it needs five.
