### ISSUE TITLE
USER ISSUE: gender keeps swiching to female

### ISSUE THREAD

**Issue by Navaldig** [StrangeLoopGames/EcoIssues#12600]
**Version:** 0.8.2.0 beta

**Steps to Reproduce:**
i dont know how i got it to work but it started at 6/19/20

**Expected behavior:**
i should be able to changed my gender without it switching back

**Actual behavior:**
when i set it to male it imediatly goes back to female

**Do you have mods installed? Does issue happen when no mods are installed?:**
when i set it to male it imediatly goes back to female

**Comment by SlayksWood** [comment]
dup #12561
