### ISSUE TITLE
[0.8.2.2] Can't connect to Sea Otter

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12604]
[connection.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3310175/connection.txt)

**Comment by D3nnis3n** [comment]
Sea Otter is going to reset in 8 hours, so probably this does no longer need a fix.

**Comment by SlayksWood** [comment]
Can't connect to old cycle. I can connect to the new.
If the information is not actual, close issue

**Comment by D3nnis3n** [comment]
@mirasrael Do you want to investigate why that happened? I'd close it for now though, as its no longer occuring, probably a lot of the tested biomed stuff fucked things up?
