### ISSUE TITLE
[0.8.2.2] Cannot harvest/scythe immature Salal

### ISSUE THREAD

**Issue by nitrofenix** [StrangeLoopGames/EcoIssues#12605]
Salal doesn't appear to be able to be scythed/harvested below 100% maturity anymore.

Using a Stone Scythe, error message is "This is not ripe enough to harvest yet":
![image](https://user-images.githubusercontent.com/50662839/59853454-3f7c0700-93b4-11e9-9c34-540ca6eded0f.png)

![image](https://user-images.githubusercontent.com/50662839/59853356-0ba0e180-93b4-11e9-94b9-c597c57e7ca7.png)

Salal with 100% maturity can be scythed/harvested as normal:
![image](https://user-images.githubusercontent.com/50662839/59853636-a13c7100-93b4-11e9-80da-8cb06a1694f0.png)

![image](https://user-images.githubusercontent.com/50662839/59853672-b0bbba00-93b4-11e9-91f9-3e8a24a26464.png)

**Comment by SlayksWood** [comment]
Isn't that intented behavior?

**Comment by nitrofenix** [comment]
I'm not sure it's intended behaviour for wild ground-cover like Salal / grasses -- since they're not farmed/harvested for food, their maturity is a little irrelevant, especially when the typical reason they are scythed is to clear a path or create a clearing. This behaviour would require players to wait for ground-cover to mature before removing it, defeating the purpose of creating a path or clearing in the first place.

**Comment by SlayksWood** [comment]
In 8.1.4, it was possible to clean the plants to maturity. 
![image](https://user-images.githubusercontent.com/45708377/59855923-9830ad00-937e-11e9-95bf-b7951ce1cedb.png)
![image](https://user-images.githubusercontent.com/45708377/59855959-a5e63280-937e-11e9-9cdd-dad80e6e4511.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/60005880-0a074000-9678-11e9-9bde-15bbee1863dd.png)
![image](https://user-images.githubusercontent.com/45708377/60005908-14293e80-9678-11e9-8c97-fb3be7c4cc24.png)
