### ISSUE TITLE
[8.2] All green grass disappear

### ISSUE THREAD

**Issue by quequiere** [StrangeLoopGames/EcoIssues#12609]
Since the update to 8.2 green grass disappear.
![Capture](https://user-images.githubusercontent.com/2946661/59867596-ebaaf700-938e-11e9-8dcc-144d4f49bc91.PNG)

**Comment by quequiere** [comment]
All biomes has disappear too

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12592
