### ISSUE TITLE
[0.8.2] Dirt Ramps, Stone Ramps, & Asphalt Ramps Have Wrong Color in Inventory

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12611]
Ramps have now been updated so they can only be stored in the Stockpile. They should have the beige background & text instead of the blue to indicate this.

![roadramps](https://user-images.githubusercontent.com/47330823/59869014-22f5b580-9347-11e9-98e6-25297876203d.png)

**Comment by beastyn** [comment]
still wrong color

**Comment by Sekor2600** [comment]
yes the Devs must change the Eco.Unity that is in the PR per SVN

**Comment by Sekor2600** [comment]
Craig did upload the newest Unity file in SVN.
