### ISSUE TITLE
When you open the map property is displayed despite the option is unchecked

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12613]
You need to check and then uncheck property to no longer see it. (Claims)

**Comment by SlayksWood** [comment]
Step to reproduce:
- unset property
![image](https://user-images.githubusercontent.com/45708377/59901706-be009500-9404-11e9-866e-ac7372d20e7c.png)
- disconnect (I tested with server from client).
- connect to server
- open minimap
![image](https://user-images.githubusercontent.com/45708377/59901691-b5a85a00-9404-11e9-977e-6612ffa3768d.png)

**Comment by beastyn** [comment]
seems to be fixed
