### ISSUE TITLE
[0.8.2.5] Not all servers are displayed in the search.

### ISSUE THREAD

**Issue by Rakkeyal** [StrangeLoopGames/EcoIssues#12617]
Our DS "Oceania - Dedicated! 24/7" is not showing properly in the server list for many of our players, myself included. 
We've tried disabling firewalls, AV software, restarts, validating files through steam and using SLG copies of the client and it still doesn't appear to be working.
The server appears fine for a small number of players, and notably appears fine for Pam in the Discord. 
The server appears fine in the Main Menu quick join, and if I wait some minutes it will show up in the "Your Worlds" Recent list with - ping.
It is able to be joined but simply is invisible to the serverlist in our clients.

**Comment by mirasrael** [comment]
Do you have external IP for the server? Did you try to set external IP explicitly in Network.eco?

**Comment by mirasrael** [comment]
btw I also can see it without problems

**Comment by Rakkeyal** [comment]
It is set explicitly with the IP:3000

**Comment by beastyn** [comment]
can be related to #9203, #9171

**Comment by Rakkeyal** [comment]
I just wanted to confirm we're still getting more regulars who are unable to find the server in the list.

**Comment by D3nnis3n** [comment]
Have no problems finding it :/

**Comment by D3nnis3n** [comment]
I had a similar issue when port 2999 was not opened - is that opened for you?

**Comment by SlayksWood** [comment]
Search options:
![image](https://user-images.githubusercontent.com/45708377/60183862-bfc8bf00-982f-11e9-8b96-317fa21356af.png)

Found worlds by me:
![image](https://user-images.githubusercontent.com/45708377/60183926-d8d17000-982f-11e9-9912-6e25f9d2948d.png)

Found Worlds by Anna:
![bandicam_2019-06-26_18-31-51-888](https://user-images.githubusercontent.com/45708377/60184043-06b6b480-9830-11e9-95b8-9e9196f3c83f.jpg)
![bandicam_2019-06-26_18-32-32-636](https://user-images.githubusercontent.com/45708377/60184080-1afab180-9830-11e9-9b70-d87a0a75e66f.jpg)

**Comment by Rakkeyal** [comment]
I wanted to confirm as well, I've fully reinstalled both my Client and the DS and still facing the same problem with some players, and myself.

**Comment by SlayksWood** [comment]
checked in 0.9.0 master. Seems fixed.
