### ISSUE TITLE
[0.8.2.3] Huckleberrys gone again

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12618]
After 0.8.2.0 Huckleberrys were shown correctly, now they are gone again.
![huckleberry](https://user-images.githubusercontent.com/5678451/59939012-e1543000-9456-11e9-9a55-3b437ed0d4b8.png)

**Comment by SlayksWood** [comment]
Model isn't updated at once.
Without Fastforward:
![image](https://user-images.githubusercontent.com/45708377/60074352-611a1d00-972b-11e9-814f-805f4c7edadf.png)
With Fastforward (Little model left, but over time everything was updated):
![image](https://user-images.githubusercontent.com/45708377/60074508-b5250180-972b-11e9-9bb0-dbf1a284d071.png)

![image](https://user-images.githubusercontent.com/45708377/60074336-56f81e80-972b-11e9-94ac-65b5b9a7b315.png)

After some time:
![image](https://user-images.githubusercontent.com/45708377/60074518-bce4a600-972b-11e9-9ace-614c8b740360.png)
![image](https://user-images.githubusercontent.com/45708377/60074572-e56ca000-972b-11e9-9832-cab141636777.png)

**Comment by SlayksWood** [comment]
unload chunk and go back and the berries lost 
![image](https://user-images.githubusercontent.com/45708377/60075506-2b2a6800-972e-11e9-89c8-13c3c5e56059.png)
![image](https://user-images.githubusercontent.com/45708377/60075513-2f568580-972e-11e9-9dd9-749827a168bf.png)

**Comment by keegan-o** [comment]
Alpha cutoff curve has been altered again so that the berries for sure show up at .8 age as they should. 
It probably was broken by a code change in the past, or perhaps a change to the shader.
