### ISSUE TITLE
Excavator polish

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12621]
- [x] Scoop was failing to collide
![animx](https://user-images.githubusercontent.com/3536496/59940535-d32ef100-940f-11e9-804e-b2a38c523fa0.gif)
- [x] Let's try a movement scheme as follows: 
* Up Arrow: extend both boom axis (so it pushes the scoop away and up)
* Down Arrow: retract both boom axis (so it pulls the scoop down and towards you)
These are the main ways players will use the arm.  Each axis will be tolerant, so for example if youre pushing Up Arrow but one of the axis can't move anymore because its blocked by something, that axis will relax while the other continues to move (think of the scoop being in a hole, and when you push forward it will actually bend the far axis towards you until it gets out of the hole).  Lets chat on this and tweak it till it feels good.

In addition, we'll have fine tune controls:
* Up/Down Arrow + Shift: move 'shoulder' joint only
* Up/Down Arrow + Elbow: move 'elbow' joint only
This will give us some leeway to let players do advanced moves with it.  
- [x] Need a controls panel that displays buttons on a UI
![image](https://user-images.githubusercontent.com/3536496/59941042-23f31980-9411-11e9-8df6-7ab34a7de751.png)
- [x] Inventory of excavator scoop should not be accessible: cant select or drag the contents, and thus it shouldnt look like a regular inventory either (it's read only).  The only way to get things out should be to right click to dump them.  
- [x] Remove 'place' highlight except for stockpiles.  
- [ ] It was very easy to get the arm stuck as in this gif:
![animx](https://user-images.githubusercontent.com/3536496/59941286-ac71ba00-9411-11e9-8ebf-598c53e943bc.gif)
I was pushing up, but it was stuck slightly on the far sand block.  It should relax its joints enough so that the elbow bends towards me, while the shoulder raises, allowing it to get out of that hole easily without having to manually fidget with it.

**Comment by SlayksWood** [comment]
@johnkslg 
1. Can you consider adding this issue to 9.0? #12427. Need to add more cells to storage.
2. We also have some issue for Excavator without milestone 9.0:
#12285, #11922

**Comment by Quadbro** [comment]
Added most of features, exept arm IK control

**Comment by IcedForge** [comment]
Can no longer use mouse binds in excavator controls as this is no longer locked to vehicle view on the Y axis.


Also needs to take a look at the boat movement which got worse from 9.1 now it feels like its pivoting on a single middle axis and rocks back and forth quite significant making its operational use almost sea sickness inducing.

It was improved from this issue somewhere along the line #12437
But in 9.2/9.3 this behavior is back in the same extreme way but just not floating above the ground

**Comment by SlayksWood** [comment]
> Can no longer use mouse binds in excavator controls as this is no longer locked to vehicle view on the Y axis.
 
added to this issue #20637
