### ISSUE TITLE
User experiences black screen and need to disconnect power line every hour

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12623]
> Since the recent update I have begun experiencing crashes every hour or so in ECO that results in a black screen and requires power cycling to reboot the machine. When closing ECO, it leaves the desktop frozen and non-responsive until restart, though the windows key still allows menu access. Attached are DxDiag and output_log. This issue persists on both the Steam version and the standalone client.

[output_log (6).txt](https://github.com/StrangeLoopGames/EcoIssues/files/3315930/output_log.6.txt)
[DxDiag (3).txt](https://github.com/StrangeLoopGames/EcoIssues/files/3315931/DxDiag.3.txt)

**Comment by mirasrael** [comment]
Seems memory leak related issue

**Comment by D3nnis3n** [comment]
Yeh, there is a severe leak somewhere causing fps drops and my 64 gb of ram to fill up after 8 hours, crashing eco without option to really remove the process from task manager, leading to me needing to restart the PC. It just takes a long time on my pc given the amount of RAM.

**Comment by mirasrael** [comment]
I did some memory usage improvements in 8.2.4. So please keep me up-to-date after release.

**Comment by mirasrael** [comment]
8.2.4 release. Can you please let me know if you have any improvements?

**Comment by SatsukiShizuka** [comment]
Concurring with same issue - at first I thought it's just the GPU overheating, but now it seems the whole server slowing down, and now this client-side RAM-guzzling is all linked..

How does one generate an error report on a machine freeze so hard, one needs to pull the power plug? (my power button itself actually cannot restart once it's off, not without cutting power first)

**Comment by D3nnis3n** [comment]
Still happens for the guy on support, too.

**Comment by redwyre** [comment]
Once your RAM usage goes over 80% windows will start paging memory out to disk, after freeing up RAM (by closing Eco in this case) it will take a long time for that memory to be restored while leaving the PC unresponsive.

If this is happening, closing Eco after you hit 80% memory usage will keep everything usable, while we look into the problems.

**Comment by mirasrael** [comment]
Memory consumption should be reduces in 8.3.
Please let us know if you see any improvements.
