### ISSUE TITLE
Let people move locked vehicles that are on their property

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1262]
(but not access their inventory)

**Comment by benjamin-willard** [comment]
I agree with this, or make it so that people cannot DRIVE on to someone's property who isn't authorized or something.  This could be expanded with permissions later?

**Comment by elfl0rd** [comment]
I want this, lol.

**Comment by WeaselDog** [comment]
This could cause issues if people move others' carts into an inaccessible area. With the admin ability to fix this with a dev tool the issue might already be solved.

**Comment by D3nnis3n** [comment]
In general there is no good way to do this without allowing someone else to drive the car to nowhere. Players that don't wish to have stuff on their property they can't move can easily build a fence around their property. Admins can help with the devtool.
