### ISSUE TITLE
USER ISSUE: connection timed out after 10 minutes of gameplay

### ISSUE THREAD

**Issue by exporta22** [StrangeLoopGames/EcoIssues#12628]
**Version:** 0.8.2.3 beta

**Steps to Reproduce:**
I play normally and every 10 minutes i got disconnected	

**Expected behavior:**
stay in game

**Actual behavior:**
The following error message popped up:
connection timed out
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
connection timed out
Connection timed out
```

**Comment by beastyn** [comment]
@exporta22 
Thank you for your report
Can you provide log file, if i occure again?
Instructions: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information: log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
