### ISSUE TITLE
Character Creation screen more improvements

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12625]
![create](https://user-images.githubusercontent.com/25908592/59966295-c945e480-951a-11e9-8010-3b304f3afe05.png)
Didn't experience myself, but had several reports in discord over the last few days.

**Comment by johnkslg** [comment]
Is this vegtation blocking or a shader problem? @beastyn 
If vegetation can you pass to sergey

**Comment by D3nnis3n** [comment]
I'm not sure, it's been over 9 Months since that occurance, but i believe it was actual vegetation.

**Comment by elfl0rd** [comment]
It's vegetation, I get that look from time to time.
Perhaps the mechanics like occlusion culling will be applicable? Hide vegetation in 2-3 blocks around when creating a character...

**Comment by johnkslg** [comment]
![anim](https://user-images.githubusercontent.com/3536496/78416595-a9ca0500-75de-11ea-831e-a3c64bc1239a.gif)
Step towards this, I made blocking vegetation hide itself.
Going to chat to Alex about making it fade instead.

**Comment by SlayksWood** [comment]
It looks better:
![2020 04 08 Character Creation in tree](https://user-images.githubusercontent.com/45708377/78773837-7996b380-799c-11ea-8032-7c6c3e005fbd.gif)
But you still have some problems with some plants(buttonbush):
![image](https://user-images.githubusercontent.com/45708377/78773948-9e8b2680-799c-11ea-8675-13972f656ceb.png)
You need to move down camera:
![image](https://user-images.githubusercontent.com/45708377/78773976-aa76e880-799c-11ea-9d27-2c4da603cd01.png)

And problem with blocks:
![image](https://user-images.githubusercontent.com/45708377/78774130-e4e08580-799c-11ea-9079-8f959f9c1664.png)
- press edit:
![image](https://user-images.githubusercontent.com/45708377/78774155-f1fd7480-799c-11ea-866f-10570b6fadda.png)
![image](https://user-images.githubusercontent.com/45708377/78774188-ff1a6380-799c-11ea-820d-a96293d400cd.png)

But we can push it to next milestones

**Comment by johnkslg** [comment]
Sure lets push. These issues might be acceptable to not fix

**Comment by SlayksWood** [comment]
#21548
> ![anim](https://user-images.githubusercontent.com/3536496/115937378-b4a34200-a44c-11eb-8710-4155fc7bda5a.gif)
> Its supposed to hide the plant when its in the way
> I think there is also code to clear plants from the spawn area.

**Comment by Daniel-Magulado** [comment]
Closing this as the main issue of avatar spawning on plants and being covered by tree branches and other plants has been fixed on ticket #18927.
