### ISSUE TITLE
Connection issue (Connection timed out)

### ISSUE THREAD

**Issue by YuukioFR** [StrangeLoopGames/EcoIssues#12631]
hello I can not play in multiplayer.

I tested to download the game directly on the site.

I also disable my anti virus and firewall.

but I can not always play in multiplayer

**Comment by D3nnis3n** [comment]
Please post the error message and your logs.
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by YuukioFR** [comment]
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX Vega (ID=0x687f)
    Vendor:   
    VRAM:     8121 MB
    Driver:   26.20.11015.1003
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.680200 ms
The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Logging in as 76561198119379494 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTMxMzkzOSwidnhhIjoibG9naW4iLCJ2eGkiOjkyNjgxLCJmIjoic2lwOi5zdHJhbmdlbG9vcGdhbWVzLWVjby43NjU2MTE5ODExOTM3OTQ5NC5AbXQxcC52aXZveC5jb20ifQ.YaSbp3Tp28eG35RnZ0B3JKFl3srLtLsKErfPtgxv0EQ
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
RootMotion.Dynamics.MuscleDelegate:Invoke(Muscle)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 87641.
Total: 131.117700 ms (FindLiveObjects: 4.292700 ms CreateObjectMapping: 3.513400 ms MarkObjects: 123.129100 ms  DeleteObjects: 0.182200 ms)

TimeSpan overflowed because the duration is too long.

  at System.TimeSpan.Interval (System.Double value, System.Int32 scale) [0x00000] in <00000000000000000000000000000000>:0 
  at ServerInfoUtils.GetDay (Eco.Shared.Networking.ServerInfo info) [0x00000] in <00000000000000000000000000000000>:0 
  at RecommendedTab.HandleServerDiscovered (Eco.Shared.Networking.ServerInfo info) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.HandleUnconnectedDataMessage (System.Net.IPEndPoint senderEndPoint, Lidgren.Network.NetBuffer buffer, System.Double receiveTime) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.HandleIncomingMessage (Lidgren.Network.NetIncomingMessage message) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.<Initialize>b__44_0 () [0x00000] in <00000000000000000000000000000000>:0 
  at Steamworks.ISteamMatchmakingPlayersResponse+PlayersRefreshComplete.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at DiscordRpc+OnJoinInfo.Invoke (System.String secret) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at Steamworks.ISteamMatchmakingPlayersResponse+PlayersRefreshComplete.Invoke () [0x00000] in <00000000000000000000000000000000>:0 

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteErrorLine(LocString)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
Steamworks.PlayersRefreshComplete:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 104622.
Total: 191.301600 ms (FindLiveObjects: 5.175000 ms CreateObjectMapping: 2.840800 ms MarkObjects: 183.106800 ms  DeleteObjects: 0.178700 ms)

Connecting to 176.57.153.81:28100...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
Steamworks.PlayersRefreshComplete:Invoke()
OnJoinInfo:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 107553.
Total: 195.621800 ms (FindLiveObjects: 5.433200 ms CreateObjectMapping: 2.913100 ms MarkObjects: 187.115600 ms  DeleteObjects: 0.159700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 87639.
Total: 142.318900 ms (FindLiveObjects: 3.876000 ms CreateObjectMapping: 2.488300 ms MarkObjects: 135.830500 ms  DeleteObjects: 0.123900 ms)

**Comment by mirasrael** [comment]
@YuukioFR please make sure you have correct system time (synchronized).

**Comment by mirasrael** [comment]
Also what is the language set on your client?

**Comment by mirasrael** [comment]
@YuukioFR did you try to use direct connect?

**Comment by mirasrael** [comment]
I provided fix for error from your log, but I'm not sure if it fixes all issues you have. So feel free to re-open this issue if you still have issues after 8.2.4.

**Comment by YuukioFR** [comment]
my language is french
my system time is sychronized

**Comment by mirasrael** [comment]
@YuukioFR Can you try set client language to English and see if it will start work?

**Comment by YuukioFR** [comment]
it work

**Comment by mirasrael** [comment]
👍 you can use English client as workaround until issue fixed with French client

**Comment by YuukioFR** [comment]
in the end it does not work anymore

**Comment by YuukioFR** [comment]
I managed to join 1 server then there nothing

**Comment by beastyn** [comment]
should be fixed with 8.2.4 release.
Please reopen if meet this one again.

**Comment by D3nnis3n** [comment]
Persisting.

**Comment by mirasrael** [comment]
@YuukioFR 
Are you trying to connect to specific server or having this issue with every server?

**Comment by YuukioFR** [comment]
to all the servers

**Comment by mirasrael** [comment]
@YuukioFR 
Can you see servers in list normally? With ping and server info?
Do you have Firewall or Antivirus enabled?

**Comment by YuukioFR** [comment]
I see all the servers. but I can not login my antivirus and my firewall are disabled

**Comment by mirasrael** [comment]
Which kind of internet connection are you using?

**Comment by YuukioFR** [comment]
I tried in 4g and wifi

**Comment by YuukioFR** [comment]
but the two do not work

**Comment by mirasrael** [comment]
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and attach client log?

**Comment by YuukioFR** [comment]
ok

**Comment by YuukioFR** [comment]
the loading is infinite

**Comment by mirasrael** [comment]
So did you login?
And what is your PC spec, btw?

**Comment by mirasrael** [comment]
And Internet speed

**Comment by YuukioFR** [comment]
ryzen 7 2700
vega 56 
16 go ram

**Comment by YuukioFR** [comment]
10 Mb/s

**Comment by mirasrael** [comment]
What about my first question? Was you able to login to official server? And if no can you provide client logs for it?

**Comment by YuukioFR** [comment]
I do not understand I can connect now

**Comment by mirasrael** [comment]
@YuukioFR can you confirm your problem is fixed now?

**Comment by mirasrael** [comment]
No response, seems fixed from prev message.
