### ISSUE TITLE
[0.8.2.3] Missing biomes

### ISSUE THREAD

**Issue by Urubaean** [StrangeLoopGames/EcoIssues#12638]
Hi,

It seems i've an issue with missing biomes. I just completly reinstalled the game for being sure to have the most updated files possible and i start creating a new world.

I check in the map biomes filter to see if everything is fine and i see that i'm missing temperate forest and swamp.

I joined my savegame and some config files that i think will help you to understand if i have made something wrong or if i really have a bug.
[biomes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3320298/biomes.zip)

**Comment by D3nnis3n** [comment]
Both these biomes are no longer available in release, not an issue.
