### ISSUE TITLE
Player Tooltip should list the players titles and demographics

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12632]
@johnkslg Took the liberty.

**Comment by johnkslg** [comment]
Assigning to Vsevolod.

To add to tooltips, put it in a function tagged [tooltip], or add a new one.
To find the titles and demos to display, use TitleManager.AssignedTitles and make a similar function in DemographicManager

Use 'MakeListLoc' to generate the list with all the proper linkages.

**Comment by MiroshnikovVA** [comment]
New player tooltip in Russian and English
![image](https://user-images.githubusercontent.com/4931021/63023520-7f043280-becf-11e9-8d7a-540acdf63c0c.png)
![image](https://user-images.githubusercontent.com/4931021/63023534-83305000-becf-11e9-8c5b-7a9279cdc479.png)
