### ISSUE TITLE
Mint defaults to currency account of whoever places the Mint. 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12637]
We like to use a public mint. In the past there has been no issue. Now when people try to mint, the currency defaults into the account of whoever placed the mint. This is true no matter who owns the Mint or who created the currency. All that matters is who placed the mint. Previously there was not an option to mint into another person's account, but now it is the default. 

**View after I place the mint:**
![MePlace](https://user-images.githubusercontent.com/47330823/59981919-9570ca80-95bf-11e9-8a8f-f18673d27c05.png)

**View after someone else places the mint:**
![LeafPlace](https://user-images.githubusercontent.com/47330823/59981923-a0c3f600-95bf-11e9-85bf-27081922f151.png)

**Comment by D3nnis3n** [comment]
@Quadbro Please implement the mentioned solution in the post above, that should make all sides happy.

**Comment by WeaselDog** [comment]
I am first server to report this, but I have played on many servers that use public mints. The currency is unbacked but they use a law that limits how much people are allowed to mint per day. Everyone comes with wood pulp or stone everyday. It is common on more casual servers and I have even seen it on Greenleaf. 
I would argue it is very rare for a server to have a mint to be used by multiple people for one account; normally with that type of currency is restricted to the World Leader.
I understand the logic with the change but I question changing the default account to being a shared account instead of just adding that as an option.

**Comment by WeaselDog** [comment]
I just bring it up again because the server we are on now is still having an adjustment period to the new method

**Comment by D3nnis3n** [comment]
I already wrote how it will work in the future, this fixes the issue. It's labeled for 9.0.

**Comment by beastyn** [comment]
1. I place mint. Can mint only to my personal account.

![bandicam 2019-07-04 09-30-05-557](https://user-images.githubusercontent.com/27898520/60640125-083f3880-9e3f-11e9-8ea2-edea6cb63ada.jpg)

2. Make myself leader
3. Place treasury
4. Go to the mint and want to mint to the treasury but there is no such an option

![bandicam 2019-07-04 09-30-42-818](https://user-images.githubusercontent.com/27898520/60640133-11300a00-9e3f-11e9-87f7-fe8db62e5804.jpg)

5. Take mint with the hammer and place it again
6. Now I can mint only to the treasury (and tooltip says that its my personal account, but it will mint to the treasury)

![bandicam 2019-07-04 09-31-03-809](https://user-images.githubusercontent.com/27898520/60640230-9a474100-9e3f-11e9-9b8d-f62a3c2034bc.jpg)

7. If i make the new mint I will only have the treasury in accounts (with niormal tooltip).

**Comment by beastyn** [comment]
If someone is a leader, not you
1. If you use public mint, you use your default account in it (thats right)
2. If you became a leader we wil see the default account and won't see the treasury. But if you will make full relog you will see only the treasury

Also, maybe we can add all users accounts to the options in mint? Not only default.

**Comment by D3nnis3n** [comment]
Okay, again, this should be the behaviour:
1. By default, the minting player gets displayed the account the owner of the mint set - this can be any account he owns or has access to. (Including treasury and shared accounts)
2. When the mint is set to public (authorized on everyone) the minting player gets displayed his personal account first and can choose between all other accounts he has access to or owns AND as last one sees the account the mint owner has specified.

Example 1:
I have account A, B and C. I set the mint and make account B the default account.
Player wants to mint and sees only account B to mint in.

Example 2:
I have account A, B and C. I set the mint and make account B the default account. I make the mint public.
Player wants to mint and sees his personal account as default, hovering over it he sees all other accounts he has access to or owns and as last account he sees the account the owner has specified.

Allowing all possible accounts there would make the drop down extremely laggy and i don't see enough use for that to take that disadvantage.

**Comment by mirasrael** [comment]
It doesn't have default account now. You can see all accounts you have access to. Actually, imho, you shouldn't be able to mint money to account you have no access to even if it is so called default mint account. So instead of making logic more complex it is now just allowed to select emission account from list of all available accounts.

**Comment by D3nnis3n** [comment]
It does NEED a default account. Otherwise government mints are no longer possible and i need to ban mints again - that should not happen.

**Comment by mirasrael** [comment]
Ok. Then it may be used as abuse to transfer money without taxes.

**Comment by D3nnis3n** [comment]
Just actually read my concept above. The complexity ensures the mint is easiily usable for different use cases, which it is not if there is no default account. All the servers with government mints are now fucked up.

**Comment by mirasrael** [comment]
Current logic is following.
Accounts always in alphabetical order and you have list of accessible accounts + mint account.
Mint private = The Mint account selected by default.
Mint public = User's account selected by default.
*Note: it will remember for few minutes last selected account. So if you open Mint, choose another account, close and re-open then you will see last selected account*
