### ISSUE TITLE
[8.2.3] Farming and picking berries with lag

### ISSUE THREAD

**Issue by Hexcodes** [StrangeLoopGames/EcoIssues#12642]
When I'm harversting berries or cutting down stuff there is always a lag.
This problem occured at the same time like the not moving animals - so I'm pretty sure it's not the system itself as it worked some hours before.

I'm playing 8.2.3 in single player. Already tried to restart the server and the game, but this didn't work.

**Comment by SlayksWood** [comment]
merged with #12641
