### ISSUE TITLE
[0.8.2.4 release-preview] Incorrect update of house value in house with 2 and more rooms

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12646]
Step to reproduce:  Very simplistic
First behavior
- have house with 2 rooms
![image](https://user-images.githubusercontent.com/45708377/60088688-bd8b3580-9747-11e9-8d8d-32911636d220.png)
- unite house to one room: I have house value as two rooms. It doesn't happen always that way.
![image](https://user-images.githubusercontent.com/45708377/60094075-bd913280-9753-11e9-8f44-2049bd731ca2.png)

Second behavior
- have house with two rooms
- unite house to one room: I have one bedroom
![image](https://user-images.githubusercontent.com/45708377/60094310-6475ce80-9754-11e9-83cd-7c7206835585.png)

- separaing house to two rooms: I have one bedroom with table and bed (should be 2 rooms). It happen because room work incorrect. #12105. 
![image](https://user-images.githubusercontent.com/45708377/60094354-76577180-9754-11e9-9aff-d2ef8ad59202.png)
- repair room. Bedroom value is not updated
![image](https://user-images.githubusercontent.com/45708377/60094451-c7fffc00-9754-11e9-9430-b2b674eb5472.png)

For a better check, a four-room house with a common crosshair is suitable. But I can't describe the behavior of the rooms and the house. Every time I have the slightest change, in one sequence, everything happens differently. But calculating the house value with a bug with room calculation are very annoying during the construction and renovation of the room.

**Comment by mirasrael** [comment]
@SlayksWood can you confirm if it is still an issue after room fixes? Otherwise, please, close the issue.

**Comment by SlayksWood** [comment]
fixed for now
