### ISSUE TITLE
[8.2.3] Simulation Tick Stops Randomly

### ISSUE THREAD

**Issue by Hexcodes** [StrangeLoopGames/EcoIssues#12641]
After playing for some hours now I have the problem, that animals aren't moving anymore.
Seems like the whole interaction with the just crashed for me.
-> They are not moving
-> They are not running away
-> I can kill them and eat them :P 

I'm playing 8.2.3 in single player. Already tried to restart the server and the game, but this didn't work.

**Comment by SlayksWood** [comment]
@Hexcodes 
please provide log and save files
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
"When I'm harversting berries or cutting down stuff there is always a lag.
This problem occured at the same time like the not moving animals - so I'm pretty sure it's not the system itself as it worked some hours before.

I'm playing 8.2.3 in single player. Already tried to restart the server and the game, but this didn't work."
©@Hexcodes

**Comment by Hexcodes** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3327521/Player.log)

https://1drv.ms/u/s!Aki_qcCH57oni9BImIxV7_PLB-aU6Q

**Comment by Hexcodes** [comment]
Are there more information needed?

**Comment by Hexcodes** [comment]
Got it working again by using an old Data Base File - now animals are working again.

**Comment by pamduncan** [comment]
I have had this issue happen a couple times a day, animals stop moving, plants and crops do not grow and its difficult to harvest.  In checking the world has stopped ticking.  A restart of the server usually fixes that

**Comment by beastyn** [comment]
@pamduncan With what world did you get that? Any chance to have a client and server logs?

**Comment by merlay** [comment]
Deleting the .db and loading from the .eco file seemed to have helped in my case. Animals are moving again. 

Server log from when it was broken:
[log_190723111904.log](https://github.com/StrangeLoopGames/EcoIssues/files/3423738/log_190723111904.log)

**Comment by beastyn** [comment]
Its resource PC problem, should be solved with 9.0 optimization
