### ISSUE TITLE
[0.8.2.3] Multiple Sagebrush issues

### ISSUE THREAD

**Issue by nitrofenix** [StrangeLoopGames/EcoIssues#12648]
To make the below screenshots make sense, issue #12485 is still present in 0.8.2.3, with the models for Desert Moss & Sagebrush still the wrong way around:
![image](https://user-images.githubusercontent.com/50662839/60109829-640a2180-97ae-11e9-8349-78cfe677c821.png)
![image](https://user-images.githubusercontent.com/50662839/60109904-8865fe00-97ae-11e9-9ae9-400eae2fa5e6.png)

Additionally, Sagebrush cannot be harvested with a scythe at 100% maturity, as the plant cannot be highlighted/selected:
![image](https://user-images.githubusercontent.com/50662839/60109757-4341cc00-97ae-11e9-9ddc-db6af56fe19a.png)
![image](https://user-images.githubusercontent.com/50662839/60109794-55236f00-97ae-11e9-8581-269fad5d1f7d.png)

**Comment by redwyre** [comment]
Are you referring to the green selection outline being on the block instead of the plant?

**Comment by nitrofenix** [comment]
No, the green selection outline appeared while using the soil sampler tool to show the species/maturity, which is expected behaviour. After switching to the scythe, it doesn't show up at all for mature Sagebrush, but does for anything else that can be harvested that way.

Additional example -- mature Agave plant sitting ~2 blocks away from mature Sagebrush gets the green plant outline as expected:
![image](https://user-images.githubusercontent.com/50662839/60133964-d21c0c00-97e1-11e9-9c4d-45d922861327.png)

Mature Sagebrush does not, no matter where you aim the cursor, meaning the LMB tooltip as displayed for the Agave (i.e., 'Reap') never appears and the plant cannot be harvested:
![image](https://user-images.githubusercontent.com/50662839/60134057-0394d780-97e2-11e9-9da3-00ece19b4880.png)

**Comment by SlayksWood** [comment]
I can reap it in one place, but I can't reap it at another place. Highlight missing

![image](https://user-images.githubusercontent.com/45708377/60157591-cb988f00-97f7-11e9-8a18-b48b331dfa64.png)
![image](https://user-images.githubusercontent.com/45708377/60157638-e79c3080-97f7-11e9-91d2-25a96550ce83.png)
green - can.
red - can't.
It looks like it depends on the height.
![image](https://user-images.githubusercontent.com/45708377/60157968-9f314280-97f8-11e9-885e-362568d2fd09.png)
You also can't reap it without maturity
![image](https://user-images.githubusercontent.com/45708377/60158186-4b732900-97f9-11e9-8ead-2f23fd1d7e54.png)

**Comment by nitrofenix** [comment]
I think I've figured it out, sort of -- if you look at the proper Sagebrush model (i.e., currently Desert Moss) it's a little bigger at 100% maturity, so maybe the hitbox for reaping it is larger?

I'm now able to highlight/harvest Sagebrush by counter-intuitively aiming above the plant instead of directly at it. Guessing that fixing issue #12485 in the future will also fix this issue.

**Comment by beastyn** [comment]
Harvesting with low maturity in other issue #12639
