### ISSUE TITLE
Disable citizen accounts if parent account is disabled

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#12643]
When an account has disabled = 1 in user table.
It should block any citizens they own from logging in.
If citizen logs into website or game auth, return error "Your account has been disabled."

@mirasrael if you could add that to auth.

and @anatoly-slg if you could add it to the website.

**Comment by mirasrael** [comment]
Added check to AuthServer. PR opened: https://github.com/StrangeLoopGames/AuthServer/pull/15

**Comment by rainfarmer** [comment]
PR merged, thanks!
