### ISSUE TITLE
8.2.3: Entering world takes a long time/becomes impossible

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#12649]
Had #11684 resurface today. 

Included is a vanilla copy of the world - people are able to join even after several minutes, however it takes a few minutes to do so. When I add mods back, people are able to join the first few minutes after the server has been rebooted, however after that they get stuck on 'Entering world'. Those lucky enough to join prior to that can see the character enter the world in a non-interactable fashion.

https://1drv.ms/u/s!Ah1HP-nsGmcYi7NsYGFCnQxjObKnQw?e=eBbtgo

Process dump of hanging connection screen incoming once it re-occurs. Seems to be the new version of 'just a cog spinning' of the 8.0 version of the bug.

Edit: @mirasrael since you asked for a process dump if it came back, see the next few replies, including a Canadian-based player who has had no issues, whereas the majority of Euro-based players (including myself connecting through a LAN of all things) have been having issues. I've since been able to rejoin again for a slightly longer time (~15-30 mins after reboot) even with the mods, although it takes a few minutes of 'entering world' before the Network tab shows anything beyond 0,02k/s being sent out. 

After the initial 15-30 minutes, I've spent multiple times waiting on 'entering world' for 5+ minutes to no avail.

**Comment by Praefator** [comment]
Dumpfile from the client side:
https://1drv.ms/u/s!Ah1HP-nsGmcYi7Nt-dbDCa07s6NejA?e=RYcvkM

**Comment by Praefator** [comment]
Server-side dump file:
https://1drv.ms/u/s!Ah1HP-nsGmcYi7Nu9HyJaK6_5hv-Gw?e=SdiY8y

**Comment by SatsukiShizuka** [comment]
Meanwhile, a player from Canada (here) can connect properly:
https://mega.nz/#!9ptgWa7Y!NtlbkfWZueps-quOWOSKgh05BW3-ukFQ2K-o2NJBHFU

**Comment by Praefator** [comment]
Not sure if relevant, but bootup time on the 'ticking' part appears to be way off whenever the issue appears, with it loading in roughly 2 minutes otherwise. With this issue, it takes upwards of 6 minutes.

**Comment by mirasrael** [comment]
@Praefator thanks for detailed report. Can you also provide player names who experiences this problem?

**Comment by Praefator** [comment]
Hello @mirasrael, thanks for the reply.

Affected players:
- Praefator
- Magana
- Shandess
- DEtimSTER
- belgareth1987
- TommyHilniger
- Dashed_Hopes
- Brume
- squishy-panda
- thiccat
- Wasbaas
- Ferchibald
- Chadshinshin
- Kjell

Unaffected player:
- Satsuki Shizuka 五月靜

**Comment by mirasrael** [comment]
Hi @Praefator 
Thanks for the list. I found the issue. It happens if you're using Citizen in your Deeds. For big db such demographic check is very expensive and it happens multiple times during player load. As workaround you can create a title, assign it to active players and use it instead. I'll try to find a way to hot-fix this, but until 9.0 we don't plan to make significant changes in Law system.

**Comment by mirasrael** [comment]
I added caching for Demographic checks (should be available in 8.2.9). Hopefully it will help.

**Comment by Praefator** [comment]
Thanks, we split up the roads into smaller deeds just now. Is there any chance a 'visitor mode' could be implemented in the 9.x update series to further reduce the amount of checks for demographics of people just checking out the server without any apparent intent to actually join/collab on the server? 

These so-called 'window shoppers' prove to be a challenge in needlessly bloating up player counts who will never return for the duration of the map.
