### ISSUE TITLE
Taxes on Loan Interest do not work correctly

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12659]
![loantax1](https://user-images.githubusercontent.com/25908592/60216117-7c8b4200-9869-11e9-8045-710535d1b5bd.jpg)
![loantax2](https://user-images.githubusercontent.com/25908592/60216118-7c8b4200-9869-11e9-8e2d-5f67701b27bd.png)

Paid an amount of tax that is more than loan + interest, leaving him with not only no interest but the total loss of the loaned money + more loss.

Also watch the two lines above the red marker. There also a debt was paid back and a tax was given, but "only" around 50% of the total loan, the second time it was more than 100%. In any case only the interest should be taxed.

Only when you forgive a loan the tax should apply to the whole loan - to stop abusing the feature for paying for goods without taxes, but even then the tax is 10%, not 50% or over 100%.

**Comment by D3nnis3n** [comment]
Either 8.2.5 or 8.3, however possbile.

**Comment by Quadbro** [comment]
yeah, my bad, it counts x100 🍭

**Comment by SlayksWood** [comment]
You need to add tax if you forgive Full the debt. Step to reproduce:
Step to reproduce:
- have 4900 TestClientDollars
![image](https://user-images.githubusercontent.com/45708377/60326036-71cbcc80-9991-11e9-9523-2df517f3acf1.png)
- take 1000 TestClientDollars in Debt
![image](https://user-images.githubusercontent.com/45708377/60326072-890aba00-9991-11e9-8af0-d0a27852e5e1.png)
- have 5900 TestClientDollars
![image](https://user-images.githubusercontent.com/45708377/60326110-9c1d8a00-9991-11e9-95bc-056a2fa02765.png)
- Anna forgives me ALL  the debt. I should pay tax as Direct tranfer tax (public).
![image](https://user-images.githubusercontent.com/45708377/60326147-b5bed180-9991-11e9-8197-f5e8456ecb2f.png)
- still have 5900 TestClientDollars
![image](https://user-images.githubusercontent.com/45708377/60326159-bce5df80-9991-11e9-988c-be7fa977a435.png)

If Anna forgives me a debt in part, then I will pay the tax. The problem arises if you forgive all debt at once.
