### ISSUE TITLE
USER ISSUE: Single player - Connection failed

### ISSUE THREAD

**Issue by bjarkekr** [StrangeLoopGames/EcoIssues#12656]
**Version:** 0.8.2.4 beta

**Steps to Reproduce:**
Load a game
error comes

**Expected behavior:**
Started game

**Actual behavior:**
The following error message popped up:
Connection failed
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Connection failed
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by bjarkekr** [comment]
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon R7 200 Series (ID=0x6658)
    Vendor:   
    VRAM:     2024 MB
    Driver:   22.19.677.257
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.661589 ms
The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

The character used for Ellipsis is not available in font asset [titlescreenfont].
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogWarning(Object, Object)
TMPro.TMP_Text:GetSpecialCharacters(TMP_FontAsset)
TMPro.TextMeshProUGUI:LoadFontAsset()
TMPro.TextMeshProUGUI:Awake()
UnityEngine.Object:Instantiate(T)
UI.UIManager:Open(String, BSONObject, UILayer)
UI.UIManager:Open(String, UILayer)
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Logging in as 76561197981839882 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTU3MzAzMiwidnhhIjoibG9naW4iLCJ2eGkiOjE0NDUwNiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTc5ODE4Mzk4ODIuQG10MXAudml2b3guY29tIn0.5Fkcn4hu2ovsJipdYwnI1BeWwEhU0NIaz1rL1UQZ3eE
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
TooltipHandler:Invoke(TooltipUI)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 87814.
Total: 137.675107 ms (FindLiveObjects: 4.517398 ms CreateObjectMapping: 6.431124 ms MarkObjects: 126.551759 ms  DeleteObjects: 0.174241 ms)

Logging in as 76561197981839882 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTU3MzA2OSwidnhhIjoibG9naW4iLCJ2eGkiOjE0NDUyMywiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTc5ODE4Mzk4ODIuQG10MXAudml2b3guY29tIn0.T8F2pfo-9Ek86moCPAiwO0R5L8Q-TzMOnJ7-kgk5PCw
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
TooltipHandler:Invoke(TooltipUI)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 87924.
Total: 152.185626 ms (FindLiveObjects: 5.678029 ms CreateObjectMapping: 6.350435 ms MarkObjects: 140.012156 ms  DeleteObjects: 0.144421 ms)

Logging in as 76561197981839882 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTU3NDI4OCwidnhhIjoibG9naW4iLCJ2eGkiOjE0NTAwOCwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTc5ODE4Mzk4ODIuQG10MXAudml2b3guY29tIn0.jfF37jeTUTNSBVBSsVF_Zd7qT5yy4AzGNqVe_jezs5w
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
TooltipHandler:Invoke(TooltipUI)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 90055.
Total: 154.526768 ms (FindLiveObjects: 4.201660 ms CreateObjectMapping: 5.566059 ms MarkObjects: 144.395365 ms  DeleteObjects: 0.363099 ms)

Logging in as 76561197981839882 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2MTU3NDY1NSwidnhhIjoibG9naW4iLCJ2eGkiOjE0NTE0NiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTc5ODE4Mzk4ODIuQG10MXAudml2b3guY29tIn0.VB4EC1wPG16XSojW9bN2nrWHb-SHamO2oiD6DGue_K0
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
TooltipHandler:Invoke(TooltipUI)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

**Comment by D3nnis3n** [comment]
Please attach your server logfiles: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by bjarkekr** [comment]
Hi,

I have not run the game through a server. I have just used the create game menu item. Saved the game and then try to load it again. 

So no server.

**Comment by SlayksWood** [comment]
@bjarkekr 
Even if you create a server from the game, you still have server logs and save files. Provide please server log and save files.
Instruction for server log:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files
Instruction for save files: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by bjarkekr** [comment]
[log_190626084137.log](https://github.com/StrangeLoopGames/EcoIssues/files/3335967/log_190626084137.log)

**Comment by SlayksWood** [comment]
This should work better after 8.3.0 release. If you still have this problem, please reopen.
