### ISSUE TITLE
Wolves don't flee from walking players anymore, only from carts

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12657]
![nope](https://user-images.githubusercontent.com/25908592/60207469-442e3880-9856-11e9-89f4-879159a50f82.png)

**Comment by D3nnis3n** [comment]
Only applies to wolves.

**Comment by SlayksWood** [comment]
I can't reproduce it. When wolves sleep, you can sneak up to them with high hunter skill. But wolves always run away.

**Comment by Sekor2600** [comment]
The animals react to a person very late. And I have not learned Hunter. Sometimes I can go to animals and only after an arrow do they react. but not always happens.

**Comment by beastyn** [comment]
@Sekor2600 is it possible to record a video for us? 
For me its pretty much the same speed like for other animals
https://drive.google.com/file/d/1U2t6jCpwJjaavDPnWMU84TO9oRpvfo_Y/view?usp=sharing
And which server has this issue? What ping it has for you?

**Comment by SlayksWood** [comment]
@Sekor2600  
react late and don't react at all, it differs. 
When you sleep, you also don't immediately react. A good hunter must kill the animal while it sleeps. But I didn't find any regression in animal's speed react for me.

**Comment by D3nnis3n** [comment]
They don't react to players walking at all. I was walking around those wolves for around 15 minutes, they just looked nicely at me, rolled and slept, they never moved at all. Probably this is linked to there being four of them - given they did also not wander, just sleep?

I then took a truck, drove to them, and they jumped up immediately (after getting up for some seconds).
Can reproduce reliably.

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/60295048-1531c880-9923-11e9-9cc5-aae7a6ad7112.png)
Sry no Video. But i could walk to the Wolf with my Scythe in the hand. But this is not always.

**Comment by SlayksWood** [comment]
Hunter lvl3.
![2019 06 28 Wolves don't flee from walking players anymore](https://user-images.githubusercontent.com/45708377/60320607-f19e6a80-9982-11e9-8160-4150636ebe06.gif)

**Comment by D3nnis3n** [comment]
I’ll make a Video when i see a Group of Wolves lying on my capital Streets the next time. I’m not a hunter, either.

Von: Kirill
Gesendet: Freitag, 28. Juni 2019 07:59
An: StrangeLoopGames/EcoIssues
Cc: Dennis Scholz; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Wolves don't flee from walkingplayers anymore, only from carts (#12657)

Hunter lvl3.

**Comment by D3nnis3n** [comment]
Here is a video: https://drive.google.com/open?id=1XA2cUEK7DODOpdRwbQ-s6CDmzDhF02bU

This is reproducable for me permanently.

**Comment by beastyn** [comment]
@D3nnis3n  thanks a lot.
Is it on GoW?

**Comment by D3nnis3n** [comment]
Yes

Anna <notifications@github.com> schrieb am Sa., 29. Juni 2019, 05:29:
