### ISSUE TITLE
Sea otter requires 250.000 ms to initialize rooms

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12653]
Seems odd. Happens since hotfix. Restarts before hotfix were definately faster, did not do a direct comparison test, though.

**Comment by SlayksWood** [comment]
New server of Hell of Wind: 11866,9 ms
server MMozg.net 8685,2 ms
Old server Sea Otter 3836,8 ms
I can't reproduce

**Comment by D3nnis3n** [comment]
I can neither.
Gods of War: 3000 ms
Giant Tortoise: 2500 ms

**Comment by johnkslg** [comment]
Excellent bug post
