### ISSUE TITLE
Treasury in "Your Accounts" on the Economy viewer displays ALL currencies

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12661]
Including those the treasury does not hold. Enerving, especially as those are not shown in the treasury nor in the circulation tab.

**Comment by SlayksWood** [comment]
Step to reproduce ( if your account doesn't display ALL currience.):
- Open treasury. Click at "Shown all curriencies". It will be display all curriencies in economy viewer:
![image](https://user-images.githubusercontent.com/45708377/60245982-665f9f00-98c6-11e9-909d-b372e2952db7.png)
- Click to "Hide empty curriencies". It should be hide all empty currience in Economy viewer. But It isn't.
![image](https://user-images.githubusercontent.com/45708377/60246090-a6bf1d00-98c6-11e9-8bc6-d7da9b320d41.png)

**Comment by D3nnis3n** [comment]
Thanks for adding repro steps to my issues while i'm on vacation, very much appreciated @SlayksWood :)
