### ISSUE TITLE
Can't select placed world objects reliably

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12662]
![animx](https://user-images.githubusercontent.com/3536496/60217272-3611f500-9821-11e9-96fb-0b00f77d14b1.gif)
To repro:
- Spawn new world (mine was 20x20)
- Give yourself a constitution and place it.  Preferably in shrubs.
- Try to highlight it to open it. Fail.
- Go into fly mode, drop into the ground a little. Now highlight it. Success.

**Comment by Quadbro** [comment]
This was fixed after look popup separation (not reproducible now)
