### ISSUE TITLE
[0.8.2.5 release-preview] Overlap "Contract Board" 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12668]
![image](https://user-images.githubusercontent.com/45708377/60328230-8494d000-9996-11e9-9d87-a2016012c8e5.png)

**Comment by Spydarlee** [comment]
This is fixed on master/9.0 with the new UI layout.

![image](https://user-images.githubusercontent.com/553695/60440773-756b8780-9c0d-11e9-8e32-8dd2b19c7a87.png)
