### ISSUE TITLE
Vehicles can still fall through loaded chunks

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12665]
Truck glitches through the ground, then fall from the top and land on our monument
![carsstillglitch](https://user-images.githubusercontent.com/25908592/60252557-b8a2bf00-98ca-11e9-90b8-d76a230f3f08.png)

**Comment by D3nnis3n** [comment]
I give it medium, would have been a case for semihigh. If there is an admin online, thats no problem, but if there is not ... well, your truck is permanently gone.

**Comment by D3nnis3n** [comment]
This happened a lot when issue that vehicles fall through loaded chunks issue was still there. Since this was fixed it happens way less often, but still can, as it seems.

**Comment by D3nnis3n** [comment]
Just happened again for a user:
Was just driving on a long road, falling through a loaded chunk. In this case a mine was under it, he was not teleported to the top of the world, but was in the mine instead.

For the user with the screenshot above:
He was driving from his house in capital, very near to the monument, so it was also fully loaded, into the monument driveway and before reaching the store, fell through the world, spawned on top of the world and fell down onto the roof.

Players report they still have this behaviour every now and then - Cavias seems to have dropped after 8.2.4 several times already.

**Comment by D3nnis3n** [comment]
For Cavias this happened twice today, e.g. after hotfix. In total we have four occurances since the hotfix dropped yesterday that i know of.

**Comment by pamduncan** [comment]
The problem I am having is that the chucks they tend to fall through are ones with structures underneath them such as mines or basements.  The problem now that you cannot see underground is unless they fall in a room that is open you cannot find the truck to get it even as an admin.  Our town hall has a very complex underground structure that runs under the parking are and the storage drop off area and we lose at least a truck a day to the underground.  If I am lucky we can find it in a sub-basement room or one of the areas they are mining out but about half of them endup in between the rooms in the terrain and there is no finding them as you cannot see them at all,  I understand the reason for the blackout but it sort of makes it a bit more important that they don't fall through as easily
