### ISSUE TITLE
[8.2.4] Missing change of language for shadow quality

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12669]
I changed the language from German to English, the shadow quality is still shown as "schön" 
![shadow](https://user-images.githubusercontent.com/5678451/60333482-7a280580-9999-11e9-8450-431c25c8492d.JPG)

**Comment by SlayksWood** [comment]
This string is translated at crowdin
![image](https://user-images.githubusercontent.com/45708377/60333949-07238c80-99a3-11e9-9c63-edfd290c74c3.png)
![image](https://user-images.githubusercontent.com/45708377/60334792-f70cac80-99a4-11e9-8cdf-ced07810b276.png)
