### ISSUE TITLE
Remove law clause "When attempting to Abandon Specialty"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12673]
Abandoning Specialties is no longer possible and the availability of this is confusing people that think with a "When attempting to Abandon Specialty = true" they can bring it back.

**Comment by Deantwo** [comment]
On the topic of confusing "Allow" laws. Could rename "Allow" to "Do Nothing", since that better reflect what the law outcome does.

**Comment by WeaselDog** [comment]
It is removed now.
