### ISSUE TITLE
[0.8.2.5 release-preview] Devtool lost skill to delete storage

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12671]
Step to reproduce:
- have truck/stockpile/chest with some items:
![image](https://user-images.githubusercontent.com/45708377/60342237-92a81800-99b9-11e9-982d-6c7bd6190a8b.png)
- try to smite it with dev tool. In 8.1.4 You can.
In 8.2.4 you can't, you take item from storage.
![image](https://user-images.githubusercontent.com/45708377/60342503-43aeb280-99ba-11e9-8f5e-ed4b13b7c62f.png)
![image](https://user-images.githubusercontent.com/45708377/60342504-43aeb280-99ba-11e9-8b55-add3722c4898.png)

**Comment by Praefator** [comment]
Found a workaround for that - if you carry something not present in the to-be-deleted container, e.g. a log while the stockpile contains stone, it deletes the stockpile just fine
