### ISSUE TITLE
USER ISSUE: Man is stuck

### ISSUE THREAD

**Issue by joliverinspects** [StrangeLoopGames/EcoIssues#12675]
**Version:** 0.8.2.4 beta

**Steps to Reproduce:**
Tried climb up on the wall to install roof fell off and got stuck in a hole by the wall.

**Expected behavior:**
I should have been able use w + space bar to jump out

**Actual behavior:**
Man is stuck in the hole

**Do you have mods installed? Does issue happen when no mods are installed?:**
Man is stuck in the hole

**Comment by D3nnis3n** [comment]
Can you provide a screenshot? Did you try /unstuck?

**Comment by joliverinspects** [comment]
I only got the game today so I am still learning it

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
That's no problem. You are not meant to ever get stuck, that command is only there to help when it happens nontheless. But we would need a screenshot to know what happened.

**Comment by joliverinspects** [comment]
Dennis can I send it tomorrow its 3am here and I should be sleeping. 😊

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
Of course you can :)

**Comment by joliverinspects** [comment]
Good morning Dennis I have attached 3 screen shots of the problem. I am also saving the game for now to help you out.

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
Hey joliver,
your screenshots unfortunately weren't attached. Attaching them via e-mail does not work, you need to attach them in the issue directly.

**Comment by joliverinspects** [comment]
Hopefully this time

Sent from Mail for Windows 10

**Comment by joliverinspects** [comment]
This might be a better screen shot

Sent from Mail for Windows 10

**Comment by joliverinspects** [comment]
Also how do you save a game so that you can start another game without losing the 1st game?

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
Sorry this does not work, you cannot attach screenshots via e-mail. You need to do it in the issue. It has no screenshots.

**Comment by joliverinspects** [comment]
Dennis I put them on steam cloud. That was the only way I know how to do a screen shot. It should be able to be viewed by the public. Let me know if that works.

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
For that i would know what your steam username is and be your friend.

**Comment by joliverinspects** [comment]
It’s joliverinspects send me a request and I’ll accept

Sent from Mail for Windows 10

**Comment by D3nnis3n** [comment]
I've added you on steam. SLG-Dennis

**Comment by D3nnis3n** [comment]
https://steamuserimages-a.akamaihd.net/ugc/785231626167214469/F94EAD0879F4BF960A758AF6AA6B8EDF4A04F79F/

**Comment by D3nnis3n** [comment]
Going to merge this with https://github.com/StrangeLoopGames/EcoIssues/issues/9390
