### ISSUE TITLE
Popup says I'm level 30 when I'm level 2

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12674]
![image](https://user-images.githubusercontent.com/3536496/60376508-457d7380-99c4-11e9-986b-ba2cbb2c7b90.png)

**Comment by SlayksWood** [comment]
@Quadbro 
The same happens in 8.2.4. Can you fix it in release at the same time?
![image](https://user-images.githubusercontent.com/45708377/60415220-3a545e80-9be3-11e9-9fa5-bac8be461d23.png)
