### ISSUE TITLE
[0.8.2.4] Bunchgrass is missing the [Reapable] attribute & cannot be harvested

### ISSUE THREAD

**Issue by nitrofenix** [StrangeLoopGames/EcoIssues#12672]
The Bunchgrass class definition lists resources that can be generated by harvesting the plant, but without the [Reapable] attribute, it cannot be scythed in game:
![image](https://user-images.githubusercontent.com/50662839/60344393-cacf4b00-99f9-11e9-8d6c-e997bbe62c0e.png)
![image](https://user-images.githubusercontent.com/50662839/60344404-d3278600-99f9-11e9-8377-fc2b32db5c27.png)

This prevents Bunchgrass Seeds from being harvested and re-planted.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/4682
