### ISSUE TITLE
Feature Request: put currency in store for buying

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1268]
Instead of having your store take from your main currency inventory when someone sells something to you, it would give players more peace of mind to put money into the store to use for buying.  This would let you cap your purchasing based on total monetary value rather than individual item type limits, and if you are saving money for some other reason (for example, I wanted to keep a couple dollars on hand to use for crafting table fees), you can be sure that won't get taken away.

**Comment by johnkslg** [comment]
Tis a good idea.  Perhaps new earnings at the table should go into the same pool.  Or maybe we offer them to link it to their full bank account.
