### ISSUE TITLE
Avst AV issues

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12684]
We are still having Avast issues where no matter what you do with settings on it it will block Eco.  The fee version apparently cannot be disabled and the paid version, even when disabled, still causes connection issues.  Uninstalling it solves the problems with connection issues completely.

This has been an issue off and on, pretty much on, since Eco was back in alpha and while they have occasionally changed something and then it will work but it only works until their next update and we are back with issues for some months until another users is stubborn enough player to get through to their support gets them to address the issue again.

Is there anyone from SLG that could reach out to them and see if there is a fix they could make that would work consistently and not block Eco in this manner?

**Comment by redwyre** [comment]
It's probably because of Costura...

**Comment by redwyre** [comment]
Made a submission to Avast, waiting for them to get back to me.

**Comment by redwyre** [comment]
@pamduncan I need details of which versions of Avast and which versions of Eco, for Avast support

**Comment by D3nnis3n** [comment]
Closing out for now.
