### ISSUE TITLE
Store auto connects to public chests

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#12699]
This should never happen, we made sure the chest was not connected to the store, later it was and people abused it to steal from us.

**Comment by SlayksWood** [comment]
@otting 
Can you provide more information? Whose store, authorization rights, where the chests stood. You can also provide save files and coordinates.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by otting** [comment]
It was mas my wifes store and it stood on her claim, the chest for authorized for everyone.
We believe it was automatically selected when the house around the store was rebuild.

As its not my server we dont have any save files i believe.

**Comment by SlayksWood** [comment]
@otting 
I can't reproduce the bug on the information received. Can you specify something in more detail? Some screenshots or something else. I just checked that when rebuilding the room (without picked up the store) the settings in the store were saved.
If the store was picked up, then it must be configured again.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
