### ISSUE TITLE
[8.2.4] General Chat

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12691]
![grafik](https://user-images.githubusercontent.com/37456949/60445669-f2076180-9c1f-11e9-9483-76fc0d4c3c7a.png)

We have 2 general chats. One German and one English. But you never see when someone else in the other chat has written something because only one can be selected. especially if you hide the chat window. That is confusing.

Should have same Chatid?? but only the name translated?

**Comment by D3nnis3n** [comment]
Actually this didn't happen prior 8.2 to me, but i lately saw it happen a lot.

**Comment by Praefator** [comment]
Can confirm it shows up for us as well for clients playing with French localization
