### ISSUE TITLE
USER ISSUE: House bugged after removing wall behind carpenter bench

### ISSUE THREAD

**Issue by namitsoo** [StrangeLoopGames/EcoIssues#12693]
**Version:** 0.8.2.4 beta

**Steps to Reproduce:**
Building carpenter bench and as we wanted to move some walls from behind the bench around the bench disappeared and it's no longer possible to build walls for that room/house.	

**Expected behavior:**
Carpenter bench should still be there but should not work as the room is not a full room with all fullfilled requirements

**Actual behavior:**
Bench disappeared,walls are invisible and cant be build anymore for that room

**Do you have mods installed? Does issue happen when no mods are installed?:**
Bench disappeared,walls are invisible and cant be build anymore for that room

**Comment by namitsoo** [comment]
Update: Both players relogged and house was no longer bugged and also the bench appeared in my backpack

**Comment by SlayksWood** [comment]
@namitsoo 
please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Maybe you have any screenshots?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information:
