### ISSUE TITLE
Crash when adding fuel (tallow) to a light object (wall candle).

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#12694]
![image](https://user-images.githubusercontent.com/14983165/60467343-3dfbdb80-9c0b-11e9-8214-e89421607d88.png)

Happening in master branch 7/1/2019.

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/60494843-d2cd0a80-9cd9-11e9-9bc1-46fcf64def3d.png)
