### ISSUE TITLE
[0.8.2.5] Crash with Ctrl+ RMB at stockpile

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12707]
Step to reproduce:
- Choose last (0) slot at toolbar (in my case it's tomatoes)
![image](https://user-images.githubusercontent.com/45708377/60575467-43c8fc80-9d84-11e9-896e-fcbadb4660eb.png)
- Ctrl + RMB to stockpile
- Crash
[Crash Ctrl+RMB.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3353940/Crash.Ctrl%2BRMB.txt)
You can't connect to server after crash without its restart

**Comment by mirasrael** [comment]
Can't reproduce with provided steps.

**Comment by SlayksWood** [comment]
Step to reproduce:
- create new world
- spawn stockpile (/give stockpile and place it), add all your items to stockpile
![image](https://user-images.githubusercontent.com/45708377/60577505-26962d00-9d88-11e9-820c-2229abea3b95.png)
- /give stone axe, wooden shovel, stone hammer, stone pickaxe, bow, wooden hoe, stone scythe, bighorn carcass, stake, tomatoes,200.
![image](https://user-images.githubusercontent.com/45708377/60577692-84c31000-9d88-11e9-93f2-fcb77a181480.png)
- select tomatoes at toolbar, Ctrl+RMB
![image](https://user-images.githubusercontent.com/45708377/60577708-8ab8f100-9d88-11e9-9062-3bb2e7cf0102.png)
- Crash
![image](https://user-images.githubusercontent.com/45708377/60577874-dff50280-9d88-11e9-82c5-de51554e0acb.png)

**Comment by SlayksWood** [comment]
It's necessary that the same item with the same quantity  was in inventory and on toolbar.
![image](https://user-images.githubusercontent.com/45708377/60578779-7d9d0180-9d8a-11e9-98f5-42f94da37c71.png)
