### ISSUE TITLE
[0.8.2.5] Vehicles launched up in the air while driving

### ISSUE THREAD

**Issue by Sandflakes** [StrangeLoopGames/EcoIssues#12704]
When driving through partially loaded areas the noise from wood pulp being created can often be heard, even when there are no wood pulp nearby. Sometimes the vehicle gets launched up in the air in locations where wood pulp has previously existed at the same time as the sound appears. The wood pulp as a block seems to remain as a ghost when the world is loading but has no visual appearance or physical effects apart from the catapulting.

I have only tested this on Dennis (GoW) server which is currently covered in redwood due to a bug.

EDIT: After further investigation it seems to be related to rubble in caves under the roads that seem to exist monetarily above ground while loading in causing vehicle to launch in to the air if loaded inside the same area as the vehicle. Noise seems to be from rubble colliding.

**Comment by SlayksWood** [comment]
The behavior of the stones was improved in 0.8.2.8. If you drive near the place where someone is mining ore, then you can still hear the noise. But the stones began to calm down faster. So fixed.
