### ISSUE TITLE
USER ISSUE: World won't start

### ISSUE THREAD

**Issue by joliverinspects** [StrangeLoopGames/EcoIssues#12703]
**Version:** 0.8.2.5 beta

**Steps to Reproduce:**
Continue game world (Canadian Way)

**Expected behavior:**
Game should have started up

**Actual behavior:**
Incompatable version User 0.8.2.5 beta. Server 0.8.2.4 bets

**Do you have mods installed? Does issue happen when no mods are installed?:**
Incompatable version User 0.8.2.5 beta. Server 0.8.2.4 bets

**Comment by D3nnis3n** [comment]
The server is on a old version. You need to go to steam and rightclick Eco, choose Properties, then tab Betas and choose version 8.2.4 or wait until the server owner updated the server.

**Comment by joliverinspects** [comment]
Thank you for your help Dennis
