### ISSUE TITLE
8.2.5: Currency Rounding erorrs

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#12708]
Tried transfering all my money from my personal account to a newly opened 'corporate' account in collab with one of my players. Found out that I have a very small (0.0092572) amount of currency I cannot transfer. Possibly related to #12540

![20190703105208_1](https://user-images.githubusercontent.com/841990/60577953-a6b89480-9d80-11e9-9d48-0e389347caaa.jpg)
![20190703105212_1](https://user-images.githubusercontent.com/841990/60577954-a7512b00-9d80-11e9-8619-06964f9d19b3.jpg)

**Comment by SlayksWood** [comment]
#dup 8466
