### ISSUE TITLE
Using a cart should use calories faster

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1271]
This used to be the case, code should still be there.

**Comment by NafenX** [comment]
When I started playing I had hoped pulling carts would use calories but I've never seen it use any at all. Is that a server setting? Or maybe it's a mod.

Either way, I think that pulling a cart should consume calories based on how much weight in the cart you're pulling and road efficiency could help you pull carts easier as well as making the cart faster.
