### ISSUE TITLE
USER ISSUE: Can't play multiplayer with game share

### ISSUE THREAD

**Issue by TheDarkMonster62** [StrangeLoopGames/EcoIssues#12715]
**Version:** 0.8.2.6 beta

**Steps to Reproduce:**
I play on my steam account , someone shared me their game library. I play on a shared copy of Eco

**Expected behavior:**
I should be able to connect to servers and play online

**Actual behavior:**
When i connect 
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed , fresh install of the game.

**Comment by SlayksWood** [comment]
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by mirasrael** [comment]
Family sharing not supported for Eco.
