### ISSUE TITLE
USER ISSUE: WF ID Theft!

### ISSUE THREAD

**Issue by gustable** [StrangeLoopGames/EcoIssues#12716]
**Version:** 0.8.2.6 beta

**Steps to Reproduce:**
1. Play
2. Have your login token stolen
3. Get kicked

**Expected behavior:**
It shouldnt have logged me out.

**Actual behavior:**
CONNECTION fAILED
Invalid Login

**Do you have mods installed? Does issue happen when no mods are installed?:**
CONNECTION fAILED
Invalid Login

**Comment by SlayksWood** [comment]
@gustable 
please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closed for no response. Please open a new issue when this reoccurs and you have more information.
