### ISSUE TITLE
USER ISSUE: No audio

### ISSUE THREAD

**Issue by Finie-Boi** [StrangeLoopGames/EcoIssues#12711]
**Version:** 0.8.2.5 beta

**Steps to Reproduce:**
I'm not sure. Just got no audio. Verified integrity of game cache. Reset all of my settings, I have no mods installed. No audio in menu either.

**Expected behavior:**
It should have audio

**Actual behavior:**
Instead it had no audio

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it had no audio

**Comment by Finie-Boi** [comment]
In the game it didn't ask me if I had any mods installed and I've just noticed that now after posting, and it used my answer to the previous question? Anyhow, there were no mods installed.

**Comment by beastyn** [comment]
Thank you for your report.
Do you have audio in other games, applications?
Please, provide log files with instruction
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information, log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
