### ISSUE TITLE
(Metal) Braziers do not recognize storages nearby

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#12710]
As titled, unlike most other lighting equipment (most notably stone brazier), the metal brazier cannot access nearby storages and divert objects.

**Comment by SlayksWood** [comment]
Brazier:
![image](https://user-images.githubusercontent.com/45708377/60645100-79cbb680-9e40-11e9-87b6-0e3179bbb511.png)
Stone Brazier:
![image](https://user-images.githubusercontent.com/45708377/60645109-7e906a80-9e40-11e9-83c8-76403c922830.png)
