### ISSUE TITLE
USER ISSUE: Blocks not updating.

### ISSUE THREAD

**Issue by Myth494** [StrangeLoopGames/EcoIssues#12719]
**Version:** 0.8.2.6 beta

**Steps to Reproduce:**
1 remove blocks (sand or stone) 
2 sometimes not visualy being removed or stays as physical until relog.	

When placing dirt ramps sometimes not there for others.

**Expected behavior:**
Blocks should be removed when they are mined (shovel on sand or stone with  pick)

**Actual behavior:**
doesnt update the block instance.

**Do you have mods installed? Does issue happen when no mods are installed?:**
doesnt update the block instance.

**Comment by SlayksWood** [comment]
@Myth494 
please provide log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
Сan you  describe your actions in more detail before this situation arises.

**Comment by SlayksWood** [comment]
Not found anything new on the described behavior. Closed for now. Please reopen if It happens again.
