### ISSUE TITLE
Can't Comment on Law Proposal

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#12722]
On the **Giant Tortoise** server a user by the name `ᛏᛚᛅᛋ` proposed a district change called `Tailings/garbage`.
We seem to be unable to comment on the proposal.

![image](https://user-images.githubusercontent.com/2676134/60761607-73118f00-a04c-11e9-81fd-8884e7445912.png)

One of the other users said he got an error about a comment having to start with a letter. But I did not see any error myself, instead the page just seemed to reload and the comment i wrote didn't get added.

Link to the law: http://95.217.35.61:3011/laws.html?lawid=b4a6a636-70fa-446b-ac17-d4d33898ec2b

@D3nnis3n, the law has 20 hours left on its voting right now. If you could make a backup of the save, the devs might be able to take a look at it directly. Assuming the proposal isn't deleted by the proposer.

**Comment by Deantwo** [comment]
Looks like the guy removed his proposal and created a new one.
http://95.217.35.61:3011/laws.html?lawid=a99ba0bf-0701-431b-81ad-4bd352bf6966
I can comment on this law proposal just fine.

So my best guess would be that it could be the name of the proposal that caused it? I can't test it on this server again because the name of the law has been used.

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/issue.zip is the save game.

**Comment by johnkslg** [comment]
Should be fine in 9.0, double check?
