### ISSUE TITLE
Farming by hand

### ISSUE THREAD

**Issue by duschott** [StrangeLoopGames/EcoIssues#12720]
When farming by hand, the plant u grab at is not the plant that gets picked, the block next to rather it be side of the block or corner block is what is picked, The block u tried to farm the plant stays but lose the green outline.  Have tried on rice, beans, camus, beats, and all seem to be having the issue.  A tractor can still pick up the plant that lost the green outline. Restarting game/server is not fixing the green outline.

**Comment by SlayksWood** [comment]
dup #12717
