### ISSUE TITLE
Steel production values don’t change 

### ISSUE THREAD

**Issue by Eragon10401** [StrangeLoopGames/EcoIssues#12728]
I’m currently level 5 in advanced smelting and my iron bar cost per steel is 2.4 but my quicklime and coal haven’t changed, sitting at 1 and 2 respectively. Is this a big or a feature, as it seems like an odd distinction to make, not to mention a costly one

**Comment by SlayksWood** [comment]
Tested in previous versions: it looks like a intended behavior.

**Comment by Praefator** [comment]
@Eragon10401 Most likely rounding due to how you're intending to make a single block - any time you make an item requiring a fraction of an item, it's rounded up. Try making 10 steel - it should show 24 iron bars and the quicklime/coal cost decrease as it's not or less of a fraction

**Comment by D3nnis3n** [comment]
This is intended behaviour. Advanced Smelting does not affect coal or quicklime recipes, as those have nothing to do with "smelting".
