### ISSUE TITLE
Players game crashes at 50% loading

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12729]
Savegame:
Game.db https://1drv.ms/u/s!AnKn1kbQzQiFiFwFUpqMIaoHKK5y
Game.eco https://1drv.ms/u/s!AnKn1kbQzQiFiF3g20DHtx8-gHwi

Username of the crashing person: Roko0815

**Comment by mirasrael** [comment]
Can't reproduce. I was able to login to the World with provided user.
![image](https://user-images.githubusercontent.com/475445/60953404-c5310980-a305-11e9-9702-047aa9440a69.png)

Client log may help. Also exact crash error message and PC spec.

**Comment by mirasrael** [comment]
Also if player used any mods and modified configs in any way.

**Comment by D3nnis3n** [comment]
Didn't get any further information by the user, therefore closing this.
