### ISSUE TITLE
[0.8.2.5] Elk Mount (decoration) skill points too high

### ISSUE THREAD

**Issue by El-Flex0r** [StrangeLoopGames/EcoIssues#12723]
The Elk Mount gives 10 skill points but needs only an Elk, a few boards and Tailoring 1. A Stuffed Elk needs more material, more space higher tailoring level and gives "only" 5 skill points. I just noticed it is the same for the Bison Mount. Still feels like a lot compared to other stuff made by tailoring.

**Comment by WeaselDog** [comment]
Good feedback. Elk Mount is having its skill points reduced.
