### ISSUE TITLE
USER ISSUE: Can't connect to Bio-Industrie Server

### ISSUE THREAD

**Issue by talamatur** [StrangeLoopGames/EcoIssues#12724]
**Version:** 0.8.2.7 beta

**Steps to Reproduce:**
try to login to server "Bio-Industrie" a home hosted server by a friend of me. After some seconds it will be displayed in the server list (all other server are loaded long time before). I see the description/player active but see no ping, just "-".
Connecting is not working and i get an error.

Sometimes i can connect to it! I also can connect to other servers. Other member of the server have the same issue.

**Expected behavior:**
In case the connect is not working, The user needs an readable error message (eg "Server is offline", ports not open, "slots are full" ...). 
BTW: In the Bug reporting view is this input field not scrollable and acts buggy

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by SlayksWood** [comment]
@talamatur 
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@talamatur 
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and attach client log?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. please provide your PC specification

**Comment by HyTopHauser** [comment]
Same issue for a home hosted server.
1. I am trying to connect to a server hosted on a friends computer to play in a LAN. I can connect to the official servers fine.
2. I can see ping and server info for other random public servers. I can also see server info for the LAN server i wish to join BUT I cant see the ping.
3. I have both installed but tried disabling both to try again, it had no effect.
4. I am on WiFi, but an extremely strong connection.
5. I use an HP ZBook with an intel i7-6700 HQ, 8gb ram, and a NVIDIA Quadro M600M

**Comment by beastyn** [comment]
Shouldn't be a problem with relay system
