### ISSUE TITLE
Docker container loads the incorrect version 0.8.2.7 -> 0.8.2.6

### ISSUE THREAD

**Issue by Reyalsorik** [StrangeLoopGames/EcoIssues#12721]
This happened on 0.8.2.3 as well, which was eventually corrected! (Thanks again for that)
It seems that the 0.8.2.7 version is reporting as 0.8.2.6 now.

Steps to replicate:
1. pull the latest image tag (0.8.2.7 Last update: 9 hours ago)
2. run the container
3. 0.8.2.6 is served, both noticeable in the web interface and in the head of the log file.

If this is a manual task, can this be automated to prevent the incorrect version from leaking into the latest container? 

Thanks!

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/60753803-c3530780-9fe0-11e9-870d-9df3a4652c74.png)

It should be correct version. First time I uploaded wrong version, but then in minute replaced it with correct. So you can try to force re-download Docker image
