### ISSUE TITLE
[0.8.2.7] Can't change authorization settings on wooden elevator call post.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12725]
From version 0.8.2.0 it has become possible to give access to the Elevator to another player. But you cann't  give acces to its additional buttons.
It's necessary to add the possibility of authorization in Wooden Elevator Call Post. Or that the buttons receive authorization rights from the Elevator. If I give access to the Elevator, then automatically I give access to the buttons attached to it.

**Comment by mirasrael** [comment]
It is implemented in non-ideal way (i.e. it doesn't highlight all buttons with hammer and shows hint for button, but will work as quick fix). Need another pass in 9.0
