### ISSUE TITLE
Cant place ramps in master

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12732]

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/60912980-440d4000-a23b-11e9-9e51-a3bc59b83678.png)
Also the tooltip says to put in toolbar, but ramps are carried. Fix for all carried things

**Comment by Quadbro** [comment]
Probably smth broken with block cursor
![image](https://user-images.githubusercontent.com/6802030/61934485-975ced80-afb2-11e9-80a3-a384f4303c4f.png)

**Comment by redwyre** [comment]
Working. This would have been fixed a while ago.
