### ISSUE TITLE
Also make civics objects confirm when picking up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12734]
![image](https://user-images.githubusercontent.com/3536496/60923831-9f97f780-a254-11e9-9ead-26f973e7b753.png)

Ideally this uses the async confirm function: await user.Player.ConfirmBoxLoc
Ping Alex for advice on that as it may not go in easy.

**Comment by SlayksWood** [comment]
@olegshegai @johnkslg 
Maybe should you  not display notifications if civic object is without any articles or drafts?
![image](https://user-images.githubusercontent.com/45708377/72874733-bd660f00-3d03-11ea-9335-44235457552b.png)
I place court, don't create article or draft. But when I pick up I have notification:
![image](https://user-images.githubusercontent.com/45708377/72874869-0ddd6c80-3d04-11ea-90ec-1217c998f3a7.png)

**Comment by SlayksWood** [comment]
If it's intented behavior then close.
