### ISSUE TITLE
Forage for Food tutorial came up when I picked up food

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12731]
![image](https://user-images.githubusercontent.com/3536496/60911582-5c2f9000-a238-11e9-8d74-f486ac3595f2.png)
The tutorial says I've run out of calories, but I still had calories. It seems to have been triggered by picking up some food.

**Comment by D3nnis3n** [comment]
Afaik Mike once changed this, as it was unreliable or we thought it would be a bit late to search for food when you are in slow-mode. I'd rather adapt the text of the tutorial.

**Comment by Quadbro** [comment]
Yeap, we just need to change tutorial text to "You **can** run ...." But my mater seems to be different, so maybe Stas will handle that
