### ISSUE TITLE
0.8.2.7 => 0.8.2.8 Startup hung up on "Loading Chat" < memory issues >

### ISSUE THREAD

**Issue by Reyalsorik** [StrangeLoopGames/EcoIssues#12743]
Originally a docker container, I've tried to convert the save file on Windows as well. It gets hung in the same place.

Seems to be related to some sort of memory leak.

**After waiting 10 minutes or so, I was able to have the new save converted on a Windows computer with 16GB of ram.**

This should still be reported and fixed IMO. So here I am! :)

---

Replication steps:

1) Download the unconverted storage files: https://drive.google.com/open?id=1Elj0wv1yGF2j4t8EPouhfFbw_vwp4FiL
2) Load the world
3) The world should attempt to convert to the new world format (due to a new version)
4) As it begins to load, it should start to hang around `Loading Chat`.

Thanks. :)

**Comment by mirasrael** [comment]
After optimization it now only takes 36 seconds to convert (instead of 18 minutes) and only used extra 800Mb during migration in my case (at top memory consumption was 2,95Gb).
