### ISSUE TITLE
[0.8.2.9 release-preview] Incorrect notification when canceling someone else's craft

### ISSUE THREAD

**Issue by mrbrown24** [StrangeLoopGames/EcoIssues#12741]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
Attempted to cancel project

**Expected behavior:**
Projects Cancel and Disappear from Queue	

**Actual behavior:**
Says "Remaining projects canceled" but doesn't cancel at all. Cannot pickup workbench or cancel projects

**Do you have mods installed? Does issue happen when no mods are installed?:**
Says "Remaining projects canceled" but doesn't cancel at all. Cannot pickup workbench or cancel projects

**Comment by SlayksWood** [comment]
@mrbrown24 
Does anyone have access to your craft table? You can't cancel project if it isn't your craft.

**Comment by SlayksWood** [comment]
You cancel project which another player craft at you table. But if project crafted anything, it will display project because another player need to take cradted item from craft table
![image](https://user-images.githubusercontent.com/45708377/61203912-6ba95000-a6f4-11e9-986f-fd0ca311e055.png)
