### ISSUE TITLE
USER ISSUE: Cart cant climb ramp

### ISSUE THREAD

**Issue by HaydenAlmeida** [StrangeLoopGames/EcoIssues#12740]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
i've build a L shape with Dirt ramps. The first ramp works fine but the second one my cart stop like there is something invisible in the path blocking. Yesterday was working fine, but today i cant climb up with the cart.

**Expected behavior:**
climb with no problems

**Actual behavior:**
cart can't climb the dirt ramp. Maybe something invisible blocking the path

**Do you have mods installed? Does issue happen when no mods are installed?:**
cart can't climb the dirt ramp. Maybe something invisible blocking the path

**Comment by SlayksWood** [comment]
@HaydenAlmeida 
Please provide log and save files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

If you can't provide save files you need to provide some screenshots to I can to reproduce your situation.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information: log and if possible saved files.
