### ISSUE TITLE
[0.8.2.9 release-preview] Highlight piece of tree doesn't appears without moving camera

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12747]
0.8.2.7:
![2019 07 12 Chop tree 0827](https://user-images.githubusercontent.com/45708377/61121492-06f9b580-a4a8-11e9-9bdc-14d895308a63.gif)
0.8.2.8/0.8.2.9 release-preview:
![2019 07 12 Chop tree 0828](https://user-images.githubusercontent.com/45708377/61121712-8c7d6580-a4a8-11e9-8d72-a1e461a13cff.gif)

**Comment by redwyre** [comment]
This may be related to the changes I've made to the interaction manager for multi-block tools

**Comment by redwyre** [comment]
Oh never mind, this is in release
