### ISSUE TITLE
Electric Machinist Table doesnt display requirements in german language

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12757]
German:
https://cdn.discordapp.com/attachments/324610765392969739/600327259232141360/6304508037F942EBAEC507B32808FF63.png

English:
![machinisttable](https://user-images.githubusercontent.com/25908592/61224222-7d9fe880-a71e-11e9-89bc-21237eca4431.png)

**Comment by D3nnis3n** [comment]
Log entries from the user:
> [12:21:19.996] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: SprucePopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:22.077] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: SunflowerPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:24.236] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: SwitchgrassPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:26.249] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TaroPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:28.248] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TomatoesPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:29.804] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TrilliumPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:30.809] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: UrchinPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:30.897] [71] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TrilliumPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:31.811] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: WaterweedPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:32.811] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: WheatPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:33.818] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: WhiteBursagePopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:34.823] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: BighornSheepPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:35.827] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: BisonPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:36.829] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: DeerPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:37.830] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: ElkPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:38.482] [81] [ Info] [Eco] WARN: UPnP mapping wasn't created due to an error. Server fallback to default connection settings.
> 
> [12:21:38.831] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: FoxPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:39.832] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: HarePopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:40.833] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: MountainGoatPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:41.834] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: OtterPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:42.835] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: SalmonPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:43.837] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TortoisePopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:44.839] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TroutPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:45.844] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TunaPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:46.845] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: TurkeyPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.
> 
> [12:21:47.845] [50] [ Info] [Eco] Fehler beim Versuch sicherzustellen, dass der Index in der Statistik-Datenbank existiert: WolfPopulation(TimeSeconds, Value): TimeoutException Timeout für den Vorgang wurde überschritten.

**Comment by SlayksWood** [comment]
It's not an Electric mashinist table but mashinist table
Can't reproduce
![image](https://user-images.githubusercontent.com/45708377/61434728-6b50c500-a93f-11e9-8ee8-265d32cea69a.png)

**Comment by D3nnis3n** [comment]
User still has this problem. What to do?

**Comment by SlayksWood** [comment]
@D3nnis3n
Can you take a save file or server name and coordinate?

**Comment by D3nnis3n** [comment]
I've requested one.
