### ISSUE TITLE
USER ISSUE: Movement speed buffs not working when running

### ISSUE THREAD

**Issue by Poro5298** [StrangeLoopGames/EcoIssues#12752]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
Running speed with Light Backpack and Running Shoes equipped is same as without them.

**Expected behavior:**
With Light Backpack and Running Shoes equiped I should run faster than without them. 

**Actual behavior:**
With Light Backpack and Running Shoes equiped I run same speed as without them. 
Walking speed is same as running speed with those items equiped

**Comment by johnkslg** [comment]
Assigning to Vsevolod.

Something wrong with the way buffs are applied. Craig created this system, ask him in Discord if you have questions. 
Use /help to find chat commands that give the items you need to test

**Comment by MiroshnikovVA** [comment]
in player prefab, PlayerMotorBehaviorKinematic, value field runSpeed is 4.6
![image](https://user-images.githubusercontent.com/4931021/62801472-04729600-bb10-11e9-9759-b7c6b1b2303b.png)
This variable is not assigned anywhere in the code, does not depend on any indicators. While MoveSpeed changes if you change shoes and backpack.

I propose to do:
runSpeed = moveSpeed * 1.53
or
runSpeed = moveSpeed + 1.6
--
moveSpeed works correctly

**Comment by johnkslg** [comment]
@craig-jong can you comment 
Would this affect buffs though?
