### ISSUE TITLE
[0.8.2.8] Soil Sampler inconsistencies

### ISSUE THREAD

**Issue by nitrofenix** [StrangeLoopGames/EcoIssues#12753]
Temperature units in the soil sampler results tooltip are currently displayed incorrectly in two different ways (also mentioned by @SlayksWood in #11063):
1) As "0.00 C" under the "Plant" section, when below/above optimum or minimum/maximum, where the number appears to be a 0-1 range float to 2 decimal places, and
2) As "0.0 degrees" under the "Land" section, where the number appears to be a 0-1 range float to 1 decimal place.

I believe both of these values are intended to be displayed as percentages.

![image](https://user-images.githubusercontent.com/50662839/61183551-04ed4d80-a686-11e9-8eb2-2c481dde7491.png)

It appears as though "Rainfall" is being used as the comparison layer for each plants IdealMoistureRange. Sagebrush has an IdealMoistureRange of 10% to 20%, however the following sample shows that the moisture of the measured location is 1% above the optimum (i.e., 21%), though the actual soil moisture is 17%:

![image](https://user-images.githubusercontent.com/50662839/61183647-0e2aea00-a687-11e9-9c5c-1154bf6e8834.png)

Additionally, match comparisons seem to be made before rounding is applied, leading to fringe cases where plants would otherwise match for ideal conditions, but are reported as "0% above/below optimum" -- in this case, the IdealMoistureRange for Desert Moss is 20% to 25%, meaning a "Rainfall" (see above) of 20% should be a 100% match, however it reports as 98% match since the "Rainfall" is more likely to be 19.6% (i.e., 98% of 20%):

![image](https://user-images.githubusercontent.com/50662839/61183694-a628d380-a687-11e9-9214-51a6f37544ff.png)

**Comment by SlayksWood** [comment]
dup #4410
