### ISSUE TITLE
USER ISSUE: Eco singelplayer

### ISSUE THREAD

**Issue by Dackelfrau** [StrangeLoopGames/EcoIssues#12750]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Verbindung fehlgeschlagen

**Do you have mods installed? Does issue happen when no mods are installed?:**
Verbindung fehlgeschlagen

**Comment by Dackelfrau** [comment]
Keine Mods installiert

**Comment by Dackelfrau** [comment]
No mods installed

**Comment by D3nnis3n** [comment]
Hallo Dackelfrau,
wir brauchen bitte die Logfiles, wie das geht, findest du hier: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by Dackelfrau** [comment]
[log_190713080529.log](https://github.com/StrangeLoopGames/EcoIssues/files/3389086/log_190713080529.log)

**Comment by D3nnis3n** [comment]
Der Eco Server darf nicht auf E:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server\Mods\ zugreifen. Bestehen irgendwelche Zugriffsbeschränkungen? Mal als Admin gestartet? Notfalls mal neuinstalliert?

**Comment by Dackelfrau** [comment]
Ja, ich habe es jetzt hinbekommen. Musste erst die Server exe ausführen und dann unter My World unter Lan suchen. Das wusste ich nicht. Dachte es geht auch völlig ohne server

**Comment by D3nnis3n** [comment]
Geht es auch über "Eine Welt erstellen" - so wie du es gemacht hast. Nur hat deine Eco.exe keine Berechtigung auf die Daten zuzugreifen.

**Comment by Dackelfrau** [comment]
Wie kann ich das ändern? Muss ich Eco.exe als Administrator ausführen?

**Comment by D3nnis3n** [comment]
Das könntest du mal versuchen. Warum genau bei dir der Zugriff gesperrt ist, weiß ich aber nicht - das ist Teil deiner Systemkonfiguration. (Deswegen mache ich hier auch zu)

**Comment by Dackelfrau** [comment]
Danke
