### ISSUE TITLE
Hammer placement should take calories

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12768]
Can tie to skills and forms too
Make sure to show the calorie cost in the form tooltip

**Comment by SlayksWood** [comment]
@johnkslg 
Hammer consumes calories in the release branch when placing items, but 10 times less than when you pick up.
Just yesterday I noticed one bug in the game. What if you don't have calories, then you can still place items.

**Comment by beastyn** [comment]
balance in #13021
