### ISSUE TITLE
Restore allskills command

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12766]
It's disappeared. Where did it go?  Restore plz.
Sync to an old version of git and do a search, then check history on the file where that is and see what it was removed and by who

**Comment by keegan-o** [comment]
Really it'd just be nice to have back /creative which also un-restricted the inventory-- but a /unrestrict would be acceptable as well.

**Comment by beastyn** [comment]
@johnkslg 
/allskills --> /skills all

@keegan-o 
/creative --> /skills creative

I will add /unrestrict command to my plan. I will make different issue fo this one

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/61349369-0e490680-a88e-11e9-8af6-9f13a91a2b34.png)
