### ISSUE TITLE
USER ISSUE: time out

### ISSUE THREAD

**Issue by kiri1117** [StrangeLoopGames/EcoIssues#12764]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
次のエラーメッセージがポップアップ表示されました：\ n``` \ n <size=150%>接続失敗</size>

接続に失敗しました - 接続がタイムアウトしました \ n```

**Do you have mods installed? Does issue happen when no mods are installed?:**
次のエラーメッセージがポップアップ表示されました：\ n``` \ n <size=150%>接続失敗</size>

接続に失敗しました - 接続がタイムアウトしました \ n```

**Comment by SlayksWood** [comment]
@kiri1117 
英語でコミュニケーションできますか？
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and attach client log?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. please provide your PC specification

**Comment by kiri1117** [comment]
Thx and Sorry

That's already been resolved.
