### ISSUE TITLE
Animal populations continually dropping

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1276]
hey slg, found an issue on our server and not sure whether this is a bug on our server or more common but since day 1 of 5.5 animal populations have been gradually dropping and it has gotten to a point where bison populations have dropped to 24 from a starting number of 256, because we can't place a ban on hunting them and players were well into farming so gathering was reduced so wild crops were regrowing however bison continued to drop. we loaded the files into a local server to explore a bit further and found there was an issue with bison, fox and turkey where there was no food sources registered.
![untitled](https://cloud.githubusercontent.com/assets/26527110/24387718/ab81f054-136e-11e7-9868-7ad6013d67ec.png)

**Comment by Stephenw92-git** [comment]
all the animal populations are severely suffering and i'm unsure whether this is because of an existing bug or if it's specific to our server. really trying to avoid a wipe but our co-owner is looking into a way to fix it.

for reference the map was generated on a local server before being uploaded onto a rented SSD cloud server, 130x130 in dimensions and i believe around the same in height.

**Comment by Stephenw92-git** [comment]
also keen to know of any way you can recommend to remedy the issue.

**Comment by craig-jong** [comment]
You can change the species change rate to 1. That should get around the issue. I'll have a fix out with the next staging, hopefully.
