### ISSUE TITLE
USER ISSUE: Disconnect

### ISSUE THREAD

**Issue by ahenningsson** [StrangeLoopGames/EcoIssues#12769]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
Just be online in a world.

**Expected behavior:**
Not disconnected

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by SlayksWood** [comment]
@ahenningsson 
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and attach client log?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification

**Comment by ahenningsson** [comment]
@SlayksWood 

1. I am just trying with 1, and it's my friends. We are playing together.

2. I have not tried to check after these.

3. I have a firewall and I am using Windows Defender as an antivirus protection.

4. 250/100 Mbit/s fiber connection, cable.

5. Let me know if there is something else I can provide you with:
OS: Windows 10
Processor: Intel Core i7-8700K
Ethernet: Realtek PCIe GbE Family Controller (Cardtype: Ethernet 802.3)
Graphics Card: Nvidia GTX 1060 6GB

Further problem explanation:
When I join the server, in some cases I get disconnected every 5 or 10 minutes. The weird thing is that in some cases I never get disconnected during a game session which could last at least 5 hours. So, we have "solved" it by resetting the server if we notice that I get disconnected. Sometimes it takes 2 resets, sometimes it takes only 1 reset.

**Comment by SlayksWood** [comment]
@ahenningsson 
Have you still  this problem with the release 8.3.0?

**Comment by ahenningsson** [comment]
@SlayksWood Hello! No, it works perfectly so far! Thanks
