### ISSUE TITLE
Replace pluralizer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12761]
It doesn't work for Localized languages, need another solution.

**Comment by Spydarlee** [comment]
Crowdin does support more complicated markup for pluralisation in different languages: https://support.crowdin.com/icu-message-syntax/

And there is a set of consistent rules for different languages: http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html

But we'd need to investigate how to integrate this smoothly into our localization pipeline!

**Comment by johnkslg** [comment]
This is addressed now right? @gabrielgindridev 
close if so

**Comment by gabrielgindridev** [comment]
> This is addressed now right? @gabrielgindridev
> close if so

@johnkslg nops, checked they are still in the code, somewhat disabled. But we don't need to just remove it, right? We also need to replace it. Will rename issue to Replace pluralizer. Ok?
