### ISSUE TITLE
Sunflower isn't always displayed.

### ISSUE THREAD

**Issue by GrayPanther** [StrangeLoopGames/EcoIssues#12777]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
Ernten und erneutes pflanzen.

**Expected behavior:**
Alle gepflanzten Sunflower sollten in den einzelnen Wachstumsphasen zu sehen sein!

**Actual behavior:**
Einige der Pflanzen sind unsichtbar, auch in den einzelnen Wachstumsphasen. Beim pflanzen kommt dann die Nachricht, das schon eine Sunflower da und später lassen sie sich ernten!

**Do you have mods installed? Does issue happen when no mods are installed?:**
Keine Mods installiert.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/61454033-65bba500-a968-11e9-9fd9-786b4c5b57ac.png)
![image](https://user-images.githubusercontent.com/45708377/61454488-b67fcd80-a969-11e9-8754-43d00a4428e8.png)
After reload some sunflowers may appear, others disappear
But sometimes display good:
![image](https://user-images.githubusercontent.com/45708377/61454602-0068b380-a96a-11e9-8505-d8b901b863ae.png)

**Comment by hami88** [comment]
I can confirm this issue. This is a fully planted field:

http://prntscr.com/poo4sl

**Comment by beastyn** [comment]
dup #12683
