### ISSUE TITLE
Button "Reset Defaults" doesn't update Controls without reopen window

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12773]
Step to reproduce:
- set your control button
![image](https://user-images.githubusercontent.com/45708377/61372387-a4d1f380-a89f-11e9-9a50-1abfb9c330c4.png)
- press "Reset Defaults"
![image](https://user-images.githubusercontent.com/45708377/61372387-a4d1f380-a89f-11e9-9a50-1abfb9c330c4.png)
- you need to reopen window to update control buttons.
![image](https://user-images.githubusercontent.com/45708377/61372512-faa69b80-a89f-11e9-9533-6e85b29ea639.png)

**Comment by mirasrael** [comment]
Was related to incorrect build.
