### ISSUE TITLE
USER ISSUE: Map Bug

### ISSUE THREAD

**Issue by Fliesche** [StrangeLoopGames/EcoIssues#12779]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
I dont see the map if i press "M" 
I reinstalled eco
I let steam the dates check
I tourned down the map detaills
Sorry for bad english.
XOXO

**Expected behavior:**
Ive done nothing wrong 

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by SlayksWood** [comment]
@Fliesche 
Please provide a screenshot of what happens when you open minimap.

**Comment by SlayksWood** [comment]
Сlosing for no response, reopen when you can provide us with necessary information
