### ISSUE TITLE
Bypassing storage capacity (by weight)

### ISSUE THREAD

**Issue by 0xE1** [StrangeLoopGames/EcoIssues#12784]
You can put more weight into storage with limited weight capacity by replacing item in storage with full stack of heavier item. Seems like no weight checks are applied when replacing items.

https://cdn.discordapp.com/attachments/312991502697627658/602462500851810315/unknown.png

In screenshot I had initially 1 limestone on each slot, which I then replaced with stack of coal, resulting in 4000 weight over capacity of 2000 of the cart.

Version: 0.8.2.4 beta staging-b885fe73*-1029
Monday, July 1, 2019 12:44 PM

**Comment by SlayksWood** [comment]
You need to upgrade to the latest version. Already fixed.
Why do you play on staging build? You need to change game version in Steam to actual (8.2.8 at this moment)
