### ISSUE TITLE
[0.8.2.9 release-preciew] illogical behavior of House Value

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12780]
Step to reproduce:
- spawn house with 4 rooms(kitchen, bedroom. bathroom, general ) with common corner like as:
![image](https://user-images.githubusercontent.com/45708377/61517231-6e1aeb00-aa0f-11e9-80f9-b08b92993084.png)
- start pickup/place common corner's blocks. See at behavior of House Value.
https://drive.google.com/file/d/1uZQstiStzvvHzw9wnX1XD6j0TED-7n_x/view?usp=sharing
Sometimes it happens when you place/pickup furniture:
https://drive.google.com/file/d/1b1UNdJfrpIcjHTwSyDQUUc-waETWnM4d/view?usp=sharing

**Comment by mirasrael** [comment]
@SlayksWood 
Is it still a case in 9.0?
Can you provide minimal steps-to-reproduce? (you can also attach save file with prepared room for the case)

**Comment by SlayksWood** [comment]
The value may change to incorrect value during rebuilding, but it seems to always return to the correct value:
https://drive.google.com/file/d/1zUp9XAmblUJ_XhT0lmuo3K4S7pa0u-br/view?usp=sharing
Seems fixed.
