### ISSUE TITLE
[0.8.2.9 release-preview] Can assign many actions to one button.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12786]
![image](https://user-images.githubusercontent.com/45708377/61620666-f8ff1e00-ac79-11e9-9150-ffd8b5208c93.png)
1. Alert user that this button is busy. If he still agrees to use this button, then you need to clear the previous action. 
But you need to be careful with the assign of the mouse wheel on the skid steer and excavator.
![image](https://user-images.githubusercontent.com/45708377/61621183-12549a00-ac7b-11e9-9072-c2aebcbdb889.png)
2. LMB at Toggle cursor. Set this settings and start play:
![image](https://user-images.githubusercontent.com/45708377/61621903-6d3ac100-ac7c-11e9-840d-e42073535641.png)
Open Esc Menu and try use Esc menu. You can't. Esc Menu uses Mouse0 instead my setting K1, but if you use Mouse0 your Esc menu will close. You need to close game with Alt+F4 and change controls in Main Menu.

**Comment by D3nnis3n** [comment]
Part 2 splitted to high prio issue.

**Comment by WeaselDog** [comment]
Taking care of this in next update
