### ISSUE TITLE
USER ISSUE: Stuck between walls and by try -- U shaped where open part is unstuck area.

### ISSUE THREAD

**Issue by otakuishi** [StrangeLoopGames/EcoIssues#12781]
![Untitled](https://user-images.githubusercontent.com/13478221/61572891-60df1a00-aa6a-11e9-8dc8-c072585a84a6.png)

**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
get trapped  while standing on one block between a wall in all but 1 direction with tree to the right of you thus putting you in corner. You get stuck and cannot move out.

**Expected behavior:**
ability to move away from corner and tree

**Actual behavior:**
can jump, spin and everything but cannot get unstuck out of the corner with tree and the walls are too high to climb.

**Do you have mods installed? Does issue happen when no mods are installed?:**
can jump, spin and everything but cannot get unstuck out of the corner with tree and the walls are too high to climb.

**Comment by SlayksWood** [comment]
@otakuishi 
Did you use the command /unstuck?

**Comment by otakuishi** [comment]
> @otakuishi
> Did you use the command /unstuck?

I later learned about that command existing. I never knew it did since the tutorial/tips I got never mentioned it. I had to ask others in unofficial servers what to do. I think it should be added within the tutorial/tips very early in the game.

**Comment by D3nnis3n** [comment]
Closing this as /unstuck works.
