### ISSUE TITLE
[0.8.2.9 release-preview] Glitch of ladder highlight  

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12787]
![2019 07 22 Ladder Highlight Glitch](https://user-images.githubusercontent.com/45708377/61627748-33bc8280-ac89-11e9-9294-7a3c82026b09.gif)

**Comment by redwyre** [comment]
That is odd... is it happening with any other blocks from the hammer?

**Comment by SlayksWood** [comment]
I haven't found any other blocks yet. I checked the previous versions up to 7.8.9. In all versions It happened. I think if there were more blocks, it would have been found much earlier.

**Comment by redwyre** [comment]
Are you still able to reproduce this? I tried with hew logs in master and didn't get it.

**Comment by SlayksWood** [comment]
Seems fixed.
