### ISSUE TITLE
[0.8.2.9 release-preview] "prevent to Claim Property" works incorrect

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12788]
If you simplify the law to a minimum, it will look like this:
![image](https://user-images.githubusercontent.com/45708377/61633711-5609cc80-ac98-11e9-808e-67c3b3dc05b3.png)
I think that I should not be able to claim the territory with this condition.
Example law when it can be used:
![unknown (2)](https://user-images.githubusercontent.com/45708377/61634533-2d82d200-ac9a-11e9-8a03-04b51c2251ba.png)

**Comment by WeaselDog** [comment]
This is no longer and issue with the new 9.0 system. On your own property has changed to "On Owned Land" to allow for people who share a property. When testing the equivalent law in 9.0 it worked correctly.
