### ISSUE TITLE
USER ISSUE: Repeatable contract

### ISSUE THREAD

**Issue by Zyrexo** [StrangeLoopGames/EcoIssues#12782]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
1. Create a contract
2. Enter that the contract may be executed 10x
3. Perform the contract several times

**Expected behavior:**
The contract should be executed several times by one and the same person.

**Actual behavior:**
At the moment the contract can only be executed once. The second time, the contracts can not be successfully completed asd again.

**Do you have mods installed? Does issue happen when no mods are installed?:**
At the moment the contract can only be executed once. The second time, the contracts can not be successfully completed again.

**Comment by SlayksWood** [comment]
dup #12518
