### ISSUE TITLE
[0.8.2.9 release-preview] Stockpile prevent to interact with blocks out of it.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12785]
Can pick up non-cube blocks:
![image](https://user-images.githubusercontent.com/45708377/61611111-9ac74080-ac63-11e9-85eb-5df41649ad3f.png)
Can't pick up cube blocks:
![image](https://user-images.githubusercontent.com/45708377/61611119-a155b800-ac63-11e9-95fc-6267ecbe65b2.png)
From the current position I can mine blocks with a green mark, with red I can't:
![image](https://user-images.githubusercontent.com/45708377/61611425-64d68c00-ac64-11e9-9e5b-62369b6969a6.png)

**Comment by SlayksWood** [comment]
It became worse in 0.9.0:
![image](https://user-images.githubusercontent.com/45708377/86207265-d4dcda00-bb76-11ea-9be7-e24352a6a874.png)

**Comment by redwyre** [comment]
If you are standing in a stockpile, it will be the selected object because we just use a big cube for selection. If you hit F2 and select the interaction manager for issues likes these it will show the targeting info.

A quick option is to lower the box to the maximum height of the stockpile, but that may seem a bit inconsistent...

I guess ideally we would want to combine the bounds of the stockpile with the world collision mesh to see if we are targeting a block inside the stockpile or not.

**Comment by mirasrael** [comment]
It was fixed in 8.3, but then broken again. For fix it checked if you're looking out of stockpile and prefer collision with object out of stockpile in this case.

**Comment by redwyre** [comment]
Ah yes, I remember now. Though there will still be issues looking through the empty space eg over a corner of the stockpile.

**Comment by mirasrael** [comment]
Actually not, it preferred other object if distance to center of stockpile is greater than distance to object outside of stockpile.

**Comment by SlayksWood** [comment]
It becames better in some ways, but have another problems:
- [ ] 1. Make undeground stockpile:
![image](https://user-images.githubusercontent.com/45708377/89760784-bf53bc00-daf5-11ea-9c64-7fe0084e6d7b.png)
 it's very hard to find point to pick up it:
![image](https://user-images.githubusercontent.com/45708377/89760820-ce3a6e80-daf5-11ea-9ac1-74c0c58fb707.png)

- [ ] 2. be in stockpile. The same problem - hard to open it:
![image](https://user-images.githubusercontent.com/45708377/89760890-ef9b5a80-daf5-11ea-91a5-01f6a1cf59ef.png)
- if I mouseover item in stockpile it says pick up, but I should open stockpile
