### ISSUE TITLE
[master-preview] Bad Highlight of Powered Cart

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12799]
8.2.9: Only Highlight when look at front wheel
![image](https://user-images.githubusercontent.com/45708377/61789399-4b2c7480-ae1d-11e9-99be-d38785311693.png)
![image](https://user-images.githubusercontent.com/45708377/61789382-410a7600-ae1d-11e9-97cc-b3c433198e97.png)
8.2.1:
![bandicam_2019-07-24_15-13-28-321](https://user-images.githubusercontent.com/45708377/61789493-7c0ca980-ae1d-11e9-8fe9-58c2a2b37da8.jpg)
![bandicam_2019-07-24_15-13-25-975](https://user-images.githubusercontent.com/45708377/61789503-862ea800-ae1d-11e9-8081-de367b11e954.jpg)

**Comment by beastyn** [comment]
fixed in svn

**Comment by SlayksWood** [comment]
reappeared in 9.0
