### ISSUE TITLE
Steam Family Sharing lack of support should be communicated

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12797]
Users who share with others then try to login to Steam should see a message that it's not supported for Steam.

**Comment by D3nnis3n** [comment]
Yep, it definately should, getting a lot of support requests regarding that.

**Comment by gzatravkin** [comment]
Please, can anyone response me:
1) Which message we have to show to the users?
2) Is neccesary to detect the use of family sharing? Thanks.

**Comment by WeaselDog** [comment]
I suggest to 2 tags on Steam:
One that says "Requires 3rd Party Account: SLG Account"
One that says "Requires agreement to a 3-rd party EULA: [ECO EULA] "
In the EULA it says you only get one Eco account per Steam purchase. There could also be a tag that says "Requires 3rd Party Account: SLG Account"

For reference you can look at the game Smite on Steam

**Comment by beastyn** [comment]
People still can't find relevant information on family sharing.
#16222

**Comment by elfl0rd** [comment]
game without family sharing support
![изображение](https://user-images.githubusercontent.com/4980243/81529576-cf79c500-9367-11ea-9379-eff76960e363.png)

Eco
![изображение](https://user-images.githubusercontent.com/4980243/81529598-da345a00-9367-11ea-8700-2957a1337d4c.png)

I think it is something in steam developer settings.

**Comment by trickenso** [comment]
Could this perhaps also be mentioned in the text on the store page?

**Comment by mirasrael** [comment]
@johnkslg I can't set Family Sharing option in Steam (doesn't have enough permissions). Can you do this? I assume it is in pricing.

**Comment by johnkslg** [comment]
Asked my steam contact.

**Comment by johnkslg** [comment]
Cant find this in settings and steam contact didnt reply.

**Comment by johnkslg** [comment]
Steam fixed it for me
![image](https://user-images.githubusercontent.com/3536496/82358732-cae28b80-99bb-11ea-8a32-9c6f8b2a5630.png)
