### ISSUE TITLE
[0.8.2.9 release-preview] Incorrect action of Road Tool and Shovel in the law.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12793]
Step to reproduce:
1. Create law like this:
![image](https://user-images.githubusercontent.com/45708377/61709225-5f0da300-ad57-11e9-82d5-00f7bd6fa06f.png)
2. Find or plant small tree.
3. Chop small tree with Axe. You don't pay money fo it. (I think it's right).
![2019 07 23 Chop small Tree with Axe](https://user-images.githubusercontent.com/45708377/61710559-8fa30c00-ad5a-11e9-8df2-25c0b5d8df00.gif)
4. Use Road Tool at small tree. You pay money. (I think it's wrong).
![2019 07 23 Chop small Tree with Road Tool](https://user-images.githubusercontent.com/45708377/61710459-684c3f00-ad5a-11e9-95b5-9d025dc5a818.gif)
I think you can do one of 2 behaviors:
1. When use Road Tool at small tree You don't need to pay money.
2. You can't chop small tree with Road Tool.

**Comment by D3nnis3n** [comment]
Afaik there iI'll link this with https://github.com/StrangeLoopGames/EcoIssues/issues/11552, as the road tool is causing possible invisible stump issues, so the best would probably be to not allow it to delete any type of tree.

**Comment by SlayksWood** [comment]
@D3nnis3n 
It has already been fixed. #10550
Small trees don't have such behavior as large ones. Small trees you can dig a shovel, large not. Same with the Road tool. Small trees are more like grass.

**Comment by SlayksWood** [comment]
Same with shovel

**Comment by Deantwo** [comment]
It is intended behavior to count as killing (harvest) a plant if you kill it with any tool or action. This was done in order to prevent players from circumvented preservation laws to make a wild plant species extinct.

It is however weird that it doesn't count when you use an axe on the little tree. Maybe it is because you are hitting its leaves?

**Comment by beastyn** [comment]
Close for now. Should check with working triggers lately.
