### ISSUE TITLE
[8.2.9] Very High Ram Usage on Server loading

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12796]
We are seeing issues where when the server is restarted after updating to 8.2.8 the RAM hits anywhere from 10-12 GB when it initially loads.  It does drop back to the average or about 3-4 GB after about a minute but with servers limited to 10GB this is causing start up crashes.  We can work around it by having the max ram rule ignored but that does not work for people who have servers that do not have enough RAM to spare the extra when Eco is first loading.

Reproduce:

Update to 8.2.9
Start Server 

or if already on 8.2.9

Stop server
restart server

**Comment by mirasrael** [comment]
It is already fixed in 8.3

**Comment by D3nnis3n** [comment]
Closing, then.
