### ISSUE TITLE
[0.8.2.9 release-preview] Left/Right Action description for tools and planting

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12794]
Not all tools have action descriptions: Land Claim Stake, Soil Sampler, Hoe, Road Tool. Also there is no description when planting seeds.
![image](https://user-images.githubusercontent.com/45708377/61711100-f248d780-ad5b-11e9-8f48-afad8a7a0e7c.png)
![image](https://user-images.githubusercontent.com/45708377/61711115-f83eb880-ad5b-11e9-863f-8bda259b291d.png)

**Comment by SlayksWood** [comment]
@redwyre 
why do you use noun in action? All old ones use only verbs
Land Claim Stake: Claim Land instead Claim / Unclaim Land instead Unclaim.
Soil Sampler: sample soil instead.... I think it can be named as Take.
Hoe: Hoe ground instead Hoe or maybe Cultivate.
Road Tool: Build road instead Build.
When translating into other languages, long action names may occur.

**Comment by redwyre** [comment]
@SlayksWood I just did what I thought sounded good, but you make a good point. Can you create a new issue with the names you think it should be and we can double check with john and keegan.
