### ISSUE TITLE
[0.8.2.9 release-preview] System.Exception: Error(s) occurred when loading Plants

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12791]
I can't reproduce exception when I repeat my actions which will lead me to this error, but i can describe it:
I have backup each hour. And the approximate my actions that were with the plants for this hour:
1. I plant 3 Saguaro seed and 5 Johua Seed. 
2. Use /fastforward 1 to grow tomatoes and trees
3. Have some relogs to update tomato/trees model after fastforward.
4. Use tractor with Harvester to harvest part of tomato.
5. Use /level 100,100 and use /spawnallplants. Harvest plants.
6. I use Skid Steer and Excavator, but I think it's never mind
7. After that I exit from server, foget to close it. Start new random server from client. Cancel starting new random server, open This server UI and close server (with exit).
I tried to reproduce all my actions yesterday but it didn't help.
Save and Log Files:
[log_190723080923.log](https://github.com/StrangeLoopGames/EcoIssues/files/3420412/log_190723080923.log)
https://drive.google.com/file/d/1iVKJSEJ7__ZEcrJijE6SfzIp2wIKP4gr/view?usp=sharing

**Comment by mirasrael** [comment]
Should be fixed with new Shutdown logic and Save System improvements.
