### ISSUE TITLE
USER ISSUE: Connection Timeouts

### ISSUE THREAD

**Issue by Maeyanie** [StrangeLoopGames/EcoIssues#12801]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
1. Click "Continue" from the main menu.

**Expected behavior:**
Connected to the server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```
However, if I join the server via "Your Worlds" and add the IP again, it works every time, so it's not actually a problem with server connectivity.
The log doesn't mention the IP/port where it's trying to connect, so not sure if it's saving the address wrong.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by SlayksWood** [comment]
@Maeyanie 
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the 0.8.2.9 or you had it before?

**Comment by Maeyanie** [comment]
1. Looks like it's just with my server, Giant Tortoise worked fine. Logfiles for all three cases attached.
[Continue to Tortoise](https://github.com/StrangeLoopGames/EcoIssues/files/3433288/Player.-.Tortoise.log) - 
[Continue and timeout to my server](https://github.com/StrangeLoopGames/EcoIssues/files/3433291/Player.-.Timeout.log) - 
[Connect by IP to my server](https://github.com/StrangeLoopGames/EcoIssues/files/3433294/Player.-.Connect.log)
2. Yes, it shows up in the list, with ping and server info. It also has the right number of active players under the "continue" button.
3. I have tried both with and without firewalls.
4. ADSL
5. Windows 10, i7 8700K, 32 GB RAM, GTX 1070.
6. Only since updating to 0.8.2.9.

I have restarted the server since the problem started just in case, but it didn't make any difference. I'm the one who runs the server, so if there's any useful log data on that, just let me know.
The server's overall load is fairly light, around 5% CPU and half the physical RAM. Eco is using 20-25% of one core and 6.1-6.3% of memory.

**Comment by lordmampf** [comment]
Hello ;)

I had the same issue like this.
Does your server also loads very slow in the serverlist and does not show a ping?

I could fix the problem with changing the port - really I only changed the port.

Ports which did not work for me.
Game: 20001
Web: 20002

Also I can reproduce it on my local machine. Just use an brand new server and change the port:
I can not join.

Changed to Port 3000: Everything is working again.

mampf

**Comment by Maeyanie** [comment]
Yes, it does take a while, so could be the same issue. I'm already using the default port 3000/3001, but will try changing it to something different tonight when all my other players are offline and see if that does anything.

**Comment by lordmampf** [comment]
rel #12792 
use "RemoteAddress" Config

**Comment by Maeyanie** [comment]
That does seem to be the same issue. Closing this as a duplicate.
