### ISSUE TITLE
[0.8.2.9] All stones go to Zero Point

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12809]
After all the changes, the stones began to disappear at times less. But now their loss behavior has changed. Previously, they appeared on top of the surface at the same coordinates. Now, some of them (not sure that all) appear on the surface at the zero point. I guess It started from 0.8.2.8.
Example from one of more population server at this moment:
![unknown (3)](https://user-images.githubusercontent.com/45708377/61939759-a5a00f00-af9c-11e9-8a5f-99bcff6a92fc.png)
This quantity stones formed in about a day and a half.

**Comment by mirasrael** [comment]
Still have no idea why it happens and too late for investigation. Push.

**Comment by SlayksWood** [comment]
Steps:
- /tp 200,200
- spawn alot of rubbles /land spawnrubble Sandstone,300
- wait a minute
-/tp 0,0
- wait for loading chunks
- /tp 200,200
- when you hear rubble sount use /tp 0,0.
