### ISSUE TITLE
Server config api: Eco Sim missing values and descriptions

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#12816]
Eco sim is missing descriptions and some values.

The Interactions > BiomeLayer
Needs some descriptions to be understandable.
![image](https://user-images.githubusercontent.com/7343272/61987985-5a472a00-afb7-11e9-9c8f-7097297d0379.png)

Also api seems to be sending empty biome layers
![image](https://user-images.githubusercontent.com/7343272/61987992-777bf880-afb7-11e9-8459-806bbca4137e.png)

**Comment by D3nnis3n** [comment]
That's a config people actually should not fiddle with. Instead of adding this one, rather remove it and allow people to use some other useful configs, like a seed in worldgen.

**Comment by j3fffff** [comment]
updated all config design and options since then
