### ISSUE TITLE
[0.8.2.9] Displaying different type of one tool on a backpack

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12810]
Step to reproduse:
- have wooden shovel, modern shovel at toolbar
- select other tool
![image](https://user-images.githubusercontent.com/45708377/61942209-9d969e00-afa1-11e9-82ec-e4b95eda80c3.png)

**Comment by SlayksWood** [comment]
The most trouble with 4 different shovels + 2 different road tools:
![image](https://user-images.githubusercontent.com/45708377/78126545-5a87a700-741b-11ea-8063-0681fee35547.png)

**Comment by SlayksWood** [comment]
Have some a small glith when take/put tool from storages. Step to reproduce:
- have 1. Wooden Shovel, 2. Iron shovel, 3. Steel shovel another cells are empty on toolbar. Select 5 cell:
![image](https://user-images.githubusercontent.com/45708377/89377166-ee36f000-d6f9-11ea-89ce-41f2dd17cf4c.png)
- I see Steel shovel on backpack. That's right.
- take Modern shovel from storage, It will go to 4 cell. But I still see Steel shovel on my backpack, but should see Modern shovel:
![image](https://user-images.githubusercontent.com/45708377/89377198-fd1da280-d6f9-11ea-8a16-a102a95adcd1.png)
- If I select another tool it will be fixed. So select Wooden shovel and empty 5 cell again. I see modern shovel:
![image](https://user-images.githubusercontent.com/45708377/89377212-03138380-d6fa-11ea-813d-f522916ed3c4.png)
- Now open storage and place Modern shovel in it. Close UI. I still see modern shovel, but I even don't have on toolbar it:
![image](https://user-images.githubusercontent.com/45708377/89377222-09096480-d6fa-11ea-8400-a3eb6de9fbc5.png)

**Comment by StanKryvenko** [comment]
Yeah, we don't have an implementation for updating backpack tools on inventory changes, only on drag&drop action.
@MazonDel could help, he's working on inventory updates now.

**Comment by beastyn** [comment]
Yeap, fixed. @MazonDel Thanks
