### ISSUE TITLE
Game causing PC to freeze

### ISSUE THREAD

**Issue by MeggidoMuneblaze** [StrangeLoopGames/EcoIssues#12814]
Ive been playing for a few weeks now, and starting over the weekend, the game will randomly cause my entire PC to freeze and become unresponsive. Nothing will work, and I will be forced to shut my computer down and restart it.

**Comment by D3nnis3n** [comment]
Whats your PC specs and temps? This could be overheating.
Can you attach your logfiles? See here how to do that: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by MeggidoMuneblaze** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3442860/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3442861/Player-prev.log)

i7 7700
GTX 1070ti
32gb Ram
Asus 170-A Motherboard
Seagate 120gb SSD for windows install
1TB HHD for game install
I have not noticed any overheating issues.

**Comment by beastyn** [comment]
Optimization is on the wat for 9.0
Should check there.
