### ISSUE TITLE
Game issue Digging

### ISSUE THREAD

**Issue by guardedki** [StrangeLoopGames/EcoIssues#12812]
Wondering if anyone has notice.... When you run a private server, if you dig down to bring water out to an area you are build, first off it's a pain in butt.. second it glitches out map to where we see blue under it, like where the ground should be.. We had to restart our server fresh because of it..

**Comment by SlayksWood** [comment]
@guardedki 
Can you provide a little more information? some screenshots and log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information: log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
