### ISSUE TITLE
Skid Steer Locked Camera issue

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12813]
> After a longer break I'm playing Eco again, and I'm trying to use the old skid steer controls, by using Mouse X and Y for "Skid Steer Scoop Rotate" and "Vehicle Swing Arm Up/Down". But if I do that, upon entering the skid steer, the camera is locked to the position in which I enter the skid steer, which in most cases is somewhere to the side or back, which makes it impossible to see forward and operating the skid steer properly.
> 
> Is it somehow possible to toggle between digging mode and driving mode, like you were able to do in older versions?

From: https://steamcommunity.com/app/382310/discussions/0/3428846977638815357/

**Comment by Aryathal** [comment]
Alternatively:
Is it possible to add a mapping for camera control, so that I can use Mouse X/Y for controlling the skid steer and some other keys to adjust the camera while sitting in a skid steer?

**Comment by mirasrael** [comment]
It was fixed in 8.3 as far as I remember, but need to check.

**Comment by mirasrael** [comment]
Added binding for Look Left/Right/Top/Down:
![image](https://user-images.githubusercontent.com/475445/80708256-0cd28d00-8af4-11ea-8a12-7f79461a00ba.png)
