### ISSUE TITLE
Minimap shows always Environment Data if something is marked

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12822]
v8.2.9-beta
Confusing!
Is it intended?

![minimap1](https://user-images.githubusercontent.com/38510829/62058397-aac1c000-b221-11e9-9017-56e487783b09.jpg)
![minimap2](https://user-images.githubusercontent.com/38510829/62058409-b0b7a100-b221-11e9-9b3d-c56d95e46922.jpg)

**Comment by SlayksWood** [comment]
I think It's intended behavior. Tabs for different created. And if you need to put a marker, then it is necessary.
@Quadbro 
Can you see and close if it's intended behavior?

**Comment by beastyn** [comment]
This is intended behavior. If you check something it will be shown until you uncheck it. In later versions we will rework map UI.
