### ISSUE TITLE
Planted young trees teleport to another place

### ISSUE THREAD

**Issue by Calura** [StrangeLoopGames/EcoIssues#12825]
**Type of Feedback?** Appears to be server AND client, not sure.

**OS/Web Browser?** Windows 10 (in-game)

**Detailed Description of Issue:** When planting trees in appropriate areas, the saplings disappear. They don't die. They aren't overcrowded. The map even shows them "appropriate" for the area. They just disappear. This is especially bad with Joshua trees, redwoods, and oak trees. But others will do it as well - just not as often.

**Reproducible? How difficult is it to reproduce?** Fairly easy. If I find the right spot in the game, I can make it disappear EVERY SINGLE TIME.

**Steps to reproduce bug/issue:** Clear area of trees and brush (or not, doesn't really matter). Use the hoe to till the area. Plant the tree. Walk away and come back between 2 and 10 minutes later.

**Additional Comments:** Happened on 198.23.145.254:3001 at coordinates 1491,72,931. Keeps happening. I am trying to plant an oak. I have screenshots as well, of the empty block. It shows up as a "hot spot" for oak trees. I've lost all acorns gathered for this project, so far. Oak trees are not very common in the game, and I'm planting them as a means to reproduce them, but it's failing.

![treeissue](https://user-images.githubusercontent.com/53465919/62108832-feabc380-b278-11e9-8290-c2604560a413.jpg)
![treeissue2](https://user-images.githubusercontent.com/53465919/62108834-ff445a00-b278-11e9-81bc-a17a2aacd014.jpg)

**Client Version? [Alpha .01 for example]** 0.8.2.9 (has been happening since 0.8.2)

**Include recent Crash dump** (does not crash)

**Comment by Femidahl** [comment]
**Server, Client or Website?** Atleast server since i know others on my server have same problem, could also be client.

**OS/Web Browser?** Windows 10

**Detailed Description of Issue:** Planted several Oak and Joshua trees that have dissapeared for no apparent reason. Trees of same sort have started growing around on unplanted area, but the ones i planted dissapeared. 

**Reproducible? How difficult is it to reproduce?** Easy, happens everytime at same spot. 

**Steps to reproduce bug/issue:** Clear area of trees and brush (or not, doesn't really matter). Use the hoe to till the area. Plant the tree. Walk away and come back between 2 and 10 minutes later. (taken from Calura's rapport above)

**Additional Comments:** 
Coordinates 1864,66,1101 and 1872,85,1012 on server 198.23.145.254:3001. Lost about 4 acorns already, trying to plant them to reproduce since there are not many in the world. The last coordinates are a hotspot of oak trees.

**Comment by johnkslg** [comment]
Find a way to quickly repro this, with something like fast forward (but that doesnt rebuild trees)

**Comment by Calura** [comment]
I haven't seen this happening in several months now.
--
Erica 

    On Sunday, January 12, 2020, 11:25:10 PM EST, John Krajewski <notifications@github.com> wrote:  
 
 
Find a way to quickly repro this, with something like fast forward (but that doesnt rebuild trees)

**Comment by SlayksWood** [comment]
> **Version:** 0.9.0.0 beta staging-1378
> 
> Newly created 1378 Single-player world (default with friends and meteor off)
> 
> Tested Planted The Following Seeds to make sure it was only Oak Tree doing this
> Birch Seed
> Cedar Seed
> Ceiba Seed
> Fir Seed
> Joshua Seed
> Acorn
> Palm Seed
> Redwood Seed
> Saguaro Seed
> Spruce Seed
> 
> Labelled screenshot for my benefit for each tree
> ![snap6114edited](https://user-images.githubusercontent.com/29383891/73575004-1275f380-446f-11ea-9aeb-6e91d4261aa5.png)
> 
> also after this test All but 3 Trees Disappeared (Birch, Joshua and Saguaro) which is fine as i am in the area where they grow
> ![snap6117](https://user-images.githubusercontent.com/29383891/73575191-8f08d200-446f-11ea-8ddb-94e9395de20a.png)
> 
> **BUT**
> 
> A wild Spruce and Oak Spawned here (i think after world tick and the original tress disappeared)
> ![snap6121edited](https://user-images.githubusercontent.com/29383891/73576301-0a6b8300-4472-11ea-9269-660f378e9e01.png)
> 
> ![snap6119](https://user-images.githubusercontent.com/29383891/73576393-3dae1200-4472-11ea-8234-c37c51308b98.png)
> ![snap6123](https://user-images.githubusercontent.com/29383891/73576410-49013d80-4472-11ea-93f7-e8219adb7ef6.png)
> 
> managed to get a Soil Sampler Reading of the Two Spruce but could not get anywhere near the bottom of the Wild Oak tree with Soil Sampler to get a reading, then accidentally hit it with a Devtool trying to remove some dirt.

**Comment by Calura** [comment]
In the tilled dirt plots where the trees disappeared after planting, were you able to plant another tree, or did it act like the sapling was still there? That was my problem - it acted like the sapling was still there.
--
Erica 

    On Friday, January 31, 2020, 08:07:55 PM EST, Kirill <notifications@github.com> wrote:  
 
 

Version: 0.9.0.0 beta staging-1378

Newly created 1378 Single-player world (default with friends and meteor off)

Tested Planted The Following Seeds to make sure it was only Oak Tree doing this
Birch Seed
Cedar Seed
Ceiba Seed
Fir Seed
Joshua Seed
Acorn
Palm Seed
Redwood Seed
Saguaro Seed
Spruce Seed

Labelled screenshot for my benefit for each tree


also after this test All but 3 Trees Disappeared (Birch, Joshua and Saguaro) which is fine as i am in the area where they grow


BUT

A wild Spruce and Oak Spawned here (i think after world tick and the original tress disappeared)





managed to get a Soil Sampler Reading of the Two Spruce but could not get anywhere near the bottom of the Wild Oak tree with Soil Sampler to get a reading, then accidentally hit it with a Devtool trying to remove some dirt.

**Comment by Conchipedia** [comment]
still a thing on 1383
on my little island it says i can plant Joshua trees here
![snap6160](https://user-images.githubusercontent.com/29383891/73778795-af909f00-4783-11ea-8043-5cb769beb8a0.png)
plated 10  all but 4 disappeared on next tick
![snap6161](https://user-images.githubusercontent.com/29383891/73778893-cfc05e00-4783-11ea-8a3d-3779a25f61ab.png)

and then i have New ones appeared on the hill above AFTER the others disappeared
![snap6162](https://user-images.githubusercontent.com/29383891/73778983-f2eb0d80-4783-11ea-889f-e673a365c642.png)
