### ISSUE TITLE
Actual Sand in the Desert

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12826]
We should rather have actual sand in the desert instead of colored dirt, given it's a freaking desert. People have to grind stone all day or remove one of the nice beaches to get their sand, despite living in a desert that should be full of it.

**Comment by SatsukiShizuka** [comment]
The "desert" biome featured in Eco isn't so much the extreme desert and sand dunes as we may see in scenic pictures, but rather the arid plains around the world. Scarcity of sand is indeed a real-life problem, and that scarcity is indeed being reflected ingame. If anything, this is a strength, not a shortcoming of our current worldgen information.

**Comment by D3nnis3n** [comment]
It doesnt need to be made out of sand completely, but there should at least be quite an amount of sand, as it's not intended to be a arid plain, but definately a desert.

**Comment by Deantwo** [comment]
Or make a new separate desert biome and rename the current desert to arid plains?
But yeah could also just make sand patches in the current deserts.

This is however mostly a Minecraft issue, players are used to finding sand in a Minecraft desert so they expect it here too. So maybe renaming it to something other than "desert" is the best solution.

**Comment by Sekor2600** [comment]
Something like this
![grafik](https://user-images.githubusercontent.com/37456949/64919610-4c3eaa00-d7ad-11e9-8f50-5432002f6663.png)
with small areas where plants grow like oases

**Comment by keegan-o** [comment]
Yes, more sand will be added to the desert-- the rocky soil patches underground will also be replaced with sand, and those deposits will be made larger. We have a lot of world gen updates, improvements, and changes to go still. 

As far as what deserts are supposed to be, they are a large category to which eventually we hope to add more sub-biomes. These would include things like the high desert, hot deserts, cold deserts, etc.

**Comment by elfl0rd** [comment]
yeah, i love more biome variations.

**Comment by keegan-o** [comment]
Sand deposits were expanded in 9.0, we can expand them more if needed, just let me know @D3nnis3n From here it would be a world gen balance issue.
