### ISSUE TITLE
Same name for all credits in French

### ISSUE THREAD

**Issue by Zehir** [StrangeLoopGames/EcoIssues#12823]
All credit have the same name for all  players.

Using version 0.8.2.9

Link to image : https://cdn.discordapp.com/attachments/115067354399899655/605509535259688995/unknown.png

Just play in multiplayer to reproduce.

No mod used. The server is hosted on nitrado.net

**Comment by Deantwo** [comment]
What language is your client?
What language is your server?
Since this isn't an issue for the default English client/server, it might be a localization issue.

**Comment by Zehir** [comment]
The language of my client is French
The language of the server is French
I have the same issue with the client in English

**Comment by SlayksWood** [comment]
@Zehir 
Please provide log and save files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
If you can't provide save files, please give me server name or server ID.

**Comment by Zehir** [comment]
Hi @SlayksWood 
there is Player.log : https://pastebin.com/HiskBkEK
and Player.log.copy.txt : https://pastebin.com/9J5CR4zk

The servername is "France Multigaming | 2.96km2 | discord.gg/6Zwrhex"

**Comment by SlayksWood** [comment]
It starts from 8.2.0. This string was not localized In 8.1.4 or It was not localized to French.
8.1.4:
![image](https://user-images.githubusercontent.com/45708377/62195040-ca70f980-b383-11e9-8e64-c33b3fd4044b.png)
The problem is only with French. We checked Russian and German. They are all good.

Step to reproduce:
- create server in French.

**Comment by Zehir** [comment]
The [legacy file on crowding](https://crowdin.com/translate/eco-by-strange-loop-games/50/en-fr#96482) is correct but I can't find it on the defaultstrings.csv. I tried to add this line to a csv file in Mods/Translations :
`","({0} Credit)","","({0} Crédit)","({0} Crédito)",`
This correct the name for new games but not for existing saves

**Comment by Sekor2600** [comment]
This ist a Problem in the Defaultsring.csv
![grafik](https://user-images.githubusercontent.com/37456949/63229932-39fd3a80-c206-11e9-8c9a-097a0688e15f.png)
