### ISSUE TITLE
[0.8.3.0 staging-1063] Tortoises are still make troubles

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12838]
Step to reproduce:
- spawn truck
- spawnanimal tortoise
- place ramp at tortoise
![image](https://user-images.githubusercontent.com/45708377/62365752-8c173e00-b52d-11e9-9071-018302ee3f49.png)
- try to move through tortoise. You can. Tortoise rest against the bumper.
![image](https://user-images.githubusercontent.com/45708377/62365722-73a72380-b52d-11e9-91b3-a35eb192fd10.png)

**Comment by WeaselDog** [comment]
@SlayksWood Can you confirm this is still an issue?

**Comment by SlayksWood** [comment]
Seems tortoise is not collide with vehicles anymore.
