### ISSUE TITLE
[0.8.3.0 staging-1061] Tooltip at Truck

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12836]
Step to reproduce:
- spawn truck, add 10 gasoline. 
- can put something in storage.
- start to drive. Tooltip should appear after some time. I drive in 3d person view.
![image](https://user-images.githubusercontent.com/45708377/62353753-033fd880-b514-11e9-9a72-aba6aaea97cd.png)
![image](https://user-images.githubusercontent.com/45708377/62354034-9ed14900-b514-11e9-9cb2-036004462b98.png)
![image](https://user-images.githubusercontent.com/45708377/62354453-96c5d900-b515-11e9-96c0-08ab0f36bfea.png)
Can't reproduce it in 8.2.9 so I think it's regression. Can't reproduce it for another vehicle (apart from Excavator, but we have another bug for it #12304.)

**Comment by mirasrael** [comment]
Can't reproduce on version 9.0. Can you @SlayksWood ?

**Comment by SlayksWood** [comment]
Seems fixed.
