### ISSUE TITLE
[0.8.3.0 staging-1061] Scroll wheel sensitivity in skid steer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12837]
Since 8.2.9 scroll wheel sensitivity in skid steer became less. Now it's very hard to use. But if you set controls to keys it will be good. In excavator it's good as in 8.2.8.
It will be nice to add Scroll wheel sensitivity like mouse sensitivity:
![image](https://user-images.githubusercontent.com/45708377/62356014-cde9b980-b518-11e9-8cca-5b2dc22f7a27.png)

**Comment by beastyn** [comment]
Fixed with max speed teaking.

**Comment by SlayksWood** [comment]
It's very fast now if you use keys

**Comment by beastyn** [comment]
More difficult logic requires more complex changes. I will just tweak speed for now and move issue to the 0.9

**Comment by TwixterZ** [comment]
Issue fixed as of 9.4 develop 243 

![image](https://user-images.githubusercontent.com/78054747/113985847-2c834100-987f-11eb-8682-17aae0201ccc.png)
