### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by python48** [StrangeLoopGames/EcoIssues#12835]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
grab dirt from  under a dirt ramp

**Expected behavior:**
picked it and keep playing. now I got kicked and cant rejoin

**Actual behavior:**
The following error message popped up:
```
<size=150%>Fallo de Conexión</size>

Login info could not be verified. Our auth servers may be down.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Fallo de Conexión</size>

Login info could not be verified. Our auth servers may be down.
```

**Comment by SlayksWood** [comment]
@python48
Please provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file.
Can you describe your actions more detailed? Can provide some screenshots?
If you still have problem with connection to server then you need to ask your admin to restart server. It should help.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
