### ISSUE TITLE
Few Seed dropping for Tomato and Huckleberry

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#12833]
v0.8.2.9-beta
I started a test-game because of missing seeds and this is the result:
(plant seeds/fruits)
tomato 2/114
huckleberry 0/43
corn 2/31
pumpkin 2/18
beats 7/58
![seed](https://user-images.githubusercontent.com/38510829/62287686-d8457e00-b45a-11e9-9e56-f61e49f661fd.jpg)

**Comment by D3nnis3n** [comment]
At least for huckleberries this is a big issue, given you need the seeds for farming skill scroll.

**Comment by Nicolausi113** [comment]
Yes, it’s not really pleasant. I further try what it could depend on.
For other worlds I generated it locked different, sometimes good, sometimes bad. And the question is, how much influence does maturity and growth have on it?
To be sure all plants are mature, first take a sleep for 3 days -:)

**Comment by Nicolausi113** [comment]
Another strangely situation happened:
I started my main game twice after a short period (few minutes) and each time the 5 cacti were mature and I could harvest fruits - looks like a server update problem?
I saved the game in this state, in case devs were interested to examine.
![everfruit](https://user-images.githubusercontent.com/38510829/62312452-80c10580-b48e-11e9-9a7a-7f29571de0e8.jpg)

**Comment by beastyn** [comment]
@Nicolausi113 Whould be great to have your save for checking.

**Comment by Nicolausi113** [comment]
@beastyn Okay, here is game and outputlog as zip
[savegame.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3458139/savegame.zip)

**Comment by SlayksWood** [comment]
@Nicolausi113  
You can use Soil Sampler to check maturity of plants. Thank you for save files. But we have another log's name file  starting from 8.2.0. 
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Nicolausi113** [comment]
here the new log-files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3460353/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3460354/Player-prev.log)

**Comment by WeaselDog** [comment]
This should be a non-issue in 9.0 Seed drop % is same but it won't hinder Farming research

**Comment by craig-jong** [comment]
The seeds having low drop rate is intentional since the plants are not destroyed when harvested.

We'll look at the balance of this, but as Weasel stated at least it no longer blocks research.
