### ISSUE TITLE
[master] Weird rendering issues around 0 line

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12831]
![image](https://user-images.githubusercontent.com/431728/62250833-5856ee00-b431-11e9-8254-d07d3f942a35.png)

Stepping over the line fixes the rendering

![image](https://user-images.githubusercontent.com/431728/62250858-6c9aeb00-b431-11e9-9ee1-a2867a1137b7.png)

**Comment by mirasrael** [comment]
@redwyre how much is the world size?

**Comment by redwyre** [comment]
Would have just been default world

**Comment by mirasrael** [comment]
Can you reproduce this on default sized world? (0.56)

**Comment by WeaselDog** [comment]
@redwyre Is this still an issue? It has been marked as "Needs Information" for some time.

**Comment by SlayksWood** [comment]
It is very rare to meet a problem with stopping the loading of a chunk for a short time. But it's not related with border line.
Closed for now, we will start a new issue if it became worst.
