### ISSUE TITLE
Real Estate Desk Confusal with authed people

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12840]
![desk](https://user-images.githubusercontent.com/25908592/62373859-f7b3d800-b53a-11e9-976d-1020ab890b6e.png)

This happens when:
- The deed owner is not yourself, but you are authed.
- You place the real estate desk on it. For the owner now automatically your account is set for sales, not his.
- This leads to the above error when trying to buy something.

**Comment by WeaselDog** [comment]
This happens even if the Real Estate Desk is placed on unclaimed property.
