### ISSUE TITLE
Logging Skill - Cleanup Crew broken

### ISSUE THREAD

**Issue by grelgen** [StrangeLoopGames/EcoIssues#12847]
hitting tree debris with a Stone axe costs 10 calories at level 7 logging with Cleanup Crew skill chosen.

software version 8.2.9

**Comment by SlayksWood** [comment]
@grelgen 
without talent it costs 30 calories. Talent works.
![image](https://user-images.githubusercontent.com/45708377/62440398-99644080-b758-11e9-970f-ae8702f6125e.png)
Hitting tree costs 10 calories at 7 level Logging with stone axe.
Hitting tree debris costs 30 calories at 7 level Logging with stone axe without talent.
Additional calories is difference between them.
