### ISSUE TITLE
no feedback on how to fuel a powered cart 

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1284]
We should provide some sort of feedback to indicate allowed fuel types. Putting that info in the item tooltip would also be helpful.

**Comment by NafenX** [comment]
Something like 'Requires **Solid Fuel/Liquid Fuel**' and when you hover over the Solid Fuel/Liquid Fuel text, a tooltip would show you all the different types.

**Comment by metachronism** [comment]
dupe of #751
