### ISSUE TITLE
USER ISSUE: Connection Timed Out

### ISSUE THREAD

**Issue by NullyTheNuggat** [StrangeLoopGames/EcoIssues#12844]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
Joining friend's server hosted on a static IP Address with ports forwarded

**Expected behavior:**
Joined

**Actual behavior:**
The following error message popped up:
Connection Timed Out
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Connection Timed Out
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by mirasrael** [comment]
Your friend can try to set RemoteAddress in Network config to his public address and port.

**Comment by NullyTheNuggat** [comment]
> 
> 
> Your friend can try to set RemoteAddress in Network config to his public address and port.

The static IP is his public IP

**Comment by NullyTheNuggat** [comment]
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   
    VRAM:     8079 MB
    Driver:   26.21.14.3160
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.378800 ms
Logging in as 76561198017151128 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2NDkxNjk3NSwidnhhIjoibG9naW4iLCJ2eGkiOjk2MDEzNCwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTcxNTExMjguQG10MXAudml2b3guY29tIn0.6inU9beDyUj-u12wupQ-mDDLHjQgU-AoTWtbemmZvt8
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
Assets.Scripts.Tutorial.TutorialItemHandler:Invoke(TutorialItem)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 87079.
Total: 91.806100 ms (FindLiveObjects: 2.883100 ms CreateObjectMapping: 3.959000 ms MarkObjects: 84.829500 ms  DeleteObjects: 0.134100 ms)

Logging in as 76561198017151128 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2NDkxNzAyNSwidnhhIjoibG9naW4iLCJ2eGkiOjk2MDE1MiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTcxNTExMjguQG10MXAudml2b3guY29tIn0.l46DLbMAe3ywEEfxjaRI-rXzv-EwqD6V8fqTxpmhtp8
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
Assets.Scripts.Tutorial.TutorialItemHandler:Invoke(TutorialItem)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 5.104.108.184:24001...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__44_0()
System.Threading.ThreadStart:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadStart:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 86924.
Total: 92.282200 ms (FindLiveObjects: 3.053500 ms CreateObjectMapping: 3.745900 ms MarkObjects: 85.383000 ms  DeleteObjects: 0.099200 ms)

Logging in as 76561198017151128 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2NDkxNzA2OCwidnhhIjoibG9naW4iLCJ2eGkiOjk2MDE2NywiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTcxNTExMjguQG10MXAudml2b3guY29tIn0.Eyzt9IT4ndaDwY3nK3pJdmGjKxiwrQj6lX08vghofNI
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
Assets.Scripts.Tutorial.TutorialItemHandler:Invoke(TutorialItem)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 87084.
Total: 92.304300 ms (FindLiveObjects: 3.484000 ms CreateObjectMapping: 3.545300 ms MarkObjects: 85.186900 ms  DeleteObjects: 0.087900 ms)

Logging in as 76561198017151128 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU2NDkxNzA5MywidnhhIjoibG9naW4iLCJ2eGkiOjk2MDE3MywiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTcxNTExMjguQG10MXAudml2b3guY29tIn0.synpJ39TyZHvjtu0V8Tcw3DttQzd7sRbb13GCMeyjFQ
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__44:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
Assets.Scripts.Tutorial.TutorialItemHandler:Invoke(TutorialItem)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_tlsctx_free_t:Invoke(unitytls_tlsctx*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

**Comment by SlayksWood** [comment]
@NullyTheNuggat 
Did your friend add Remote Address?

**Comment by beastyn** [comment]
Shouldn't be a problem after 0.8.3
