### ISSUE TITLE
Modkit errors

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#12841]
```
Shader error in 'Curved/Standard': failed to open source file: '../../Shaders/FpvUnityShaderVariables.cginc' at Assets/EcoModKit/Shaders/UnityShaderVariables.cginc(1) (on d3d11)

Assets\EcoModKit\Scripts\WorldObject.cs(26,36): error CS0246: The type or namespace name 'SubscribableBehavior' could not be found (are you missing a using directive or an assembly reference?)
```

If I remove the reference to SubscribableBehavior I get:
```
Assets\EcoModKit\Scripts\EcoLight.cs(17,9): error CS0103: The name 'SEGI' does not exist in the current context

Assets\EcoModKit\Scripts\Animation\StateMachineFleeFromPlayer.cs(14,13): error CS0103: The name 'Player' does not exist in the current context
```

**Comment by mirasrael** [comment]
@Phlo123 can you help with ModKit package testing?

**Comment by mirasrael** [comment]
I uploaded 8.3 compatible version to https://github.com/StrangeLoopGames/EcoModKit/tree/staging

**Comment by Phlo123** [comment]
There was a problem with the Git files for the modkit which prevented the package from being imported in the unity project, @mirasrael knows about the issue.
After @mirasrael gave me another file to import for the modkit, there is an issue with the Curved Shader.
Error message:
Shader error in 'Curved/StandardFade': failed to open source file: '../../Shaders/FpvUnityShaderVariables.cginc' at Assets/EcoModKit/Shaders/UnityShaderVariables.cginc(1) (on d3d11)

Compiling Vertex program with UNITY_PASS_SHADOWCASTER SHADOWS_DEPTH
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by mirasrael** [comment]
Fixed
