### ISSUE TITLE
quality: "save" button in avatar creation\edit screen

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12858]
Please provide more space for translation
![изображение](https://user-images.githubusercontent.com/4980243/62620288-9ec0b700-b921-11e9-9b97-d4418ee2a035.png)![изображение](https://user-images.githubusercontent.com/4980243/62620327-b861fe80-b921-11e9-9006-9e11922d0b1c.png)

.

**Comment by SlayksWood** [comment]
May be like this:
![image](https://user-images.githubusercontent.com/45708377/62620843-ff9cbf00-b922-11e9-884a-2111e1cf1815.png)

**Comment by elfl0rd** [comment]
Yea, good variant.
Or something like this
![depositphotos_29009097-stock-illustration-check-mark](https://user-images.githubusercontent.com/4980243/62621261-1d1e5880-b924-11e9-832c-80ceb7c78904.jpg)

**Comment by D3nnis3n** [comment]
We actually have plans for a character editor in the main menu.
