### ISSUE TITLE
TUTORIAL - no string

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12859]
![изображение](https://user-images.githubusercontent.com/4980243/62620635-80a78680-b922-11e9-8300-cf305ba0ba5e.png)

**Comment by johnkslg** [comment]
Hm if this is in the image we'll need to change it. @serpopov

**Comment by elfl0rd** [comment]
![изображение](https://user-images.githubusercontent.com/4980243/62931711-76c0d000-bdc7-11e9-86ca-1e609a4edce3.png)

**Comment by johnkslg** [comment]
Easy loc fix
