### ISSUE TITLE
Missing loc strings in server control panel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12857]
Voice Manager
Server Voice Identifier
Debug Statistic Tracker
Most notified properties (last 10 updates):
No notifications
New Stats
Stats Display Text
![изображение](https://user-images.githubusercontent.com/4980243/62619723-1db4f000-b920-11e9-8267-1b0893c60f1c.png)
![изображение](https://user-images.githubusercontent.com/4980243/62619736-286f8500-b920-11e9-818f-f427f4a3b125.png)
![изображение](https://user-images.githubusercontent.com/4980243/62619748-2e656600-b920-11e9-9a7e-13fd45e108c6.png)

**Comment by johnkslg** [comment]
StringExtractor should be finding these names, theyre probably not calling localize.
