### ISSUE TITLE
Incorrect string in bugreport button and title at RU loc.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12854]
"Нет" (no)
![изображение](https://user-images.githubusercontent.com/4980243/62615492-04a74180-b916-11e9-87d4-6da41b70c8b8.png)
![изображение](https://user-images.githubusercontent.com/4980243/62616014-3076f700-b917-11e9-8b5f-2c2326708525.png)

(I cannot found loc files in project, where is it now?)

**Comment by elfl0rd** [comment]
(found)
`,"Report a Bug",,"Non","Notificar un Error","Einen Bug melden","버그 제보","Reportar um erro","否","Нет","Segnala un Bug",,"Hiba jelentése","いいえ","Rapporter en bug","Zgłoś błąd","Сообщить об ошибке",,,"Nahlásit chybu","Rapportera en bugg","Повідомити про помилку",,,`
Looks as incorrect merge result.

**Comment by Quadbro** [comment]
Was already fixed
