### ISSUE TITLE
USER ISSUE: Compost creation is broken

### ISSUE THREAD

**Issue by CrazyfaceMurderguts** [StrangeLoopGames/EcoIssues#12851]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
add green items to garbage bin icon,
wait for compost
most of it turns into garbage even though everything is a green item

**Expected behavior:**
turned into compost

**Actual behavior:**
turned into garbage

**Do you have mods installed? Does issue happen when no mods are installed?:**
no

**Comment by SlayksWood** [comment]
@CrazyfaceMurderguts 
Can you tell me what items you try to create to compost? If a part create to compost, a part doesn't, then may be a specific item doesn't create compost.

**Comment by CrazyfaceMurderguts** [comment]
Unfortunately I don't recall specifics, I know it was a lot of tomatoes,
tomatoes seed and a lot of random tree and grass type seeds.

**Comment by CrazyfaceMurderguts** [comment]
I should also note that some of the bags that I put compost items in tube
had items added at different times or we're not as full as other ones

**Comment by hodldeeznuts** [comment]
I can confirm this bug. I did a test with only green items as described in the wiki. 5/6 created compost while one did create garbage. I will attempt to narrow it down.

**Comment by SlayksWood** [comment]
@hodldeeznuts 
@CrazyfaceMurderguts 
It isn't necessary to speak a specific item. It is enough to say what items you put and that one of them didn't become compost.
I tried some green items yesterday and all gave me compost.

**Comment by beastyn** [comment]
not ebough information. Reopen if appears
