### ISSUE TITLE
Forage For Food tutorial is not check "nutrients" in the proposed plants

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12862]
**Version:** 0.8.3.0 beta staging-2e9cc473*-1073
I love new behavior, but look at this screenshot
![изображение](https://user-images.githubusercontent.com/4980243/62639340-feca5400-b947-11e9-8f0f-055abb142537.png)
There is no fat source, as result - player cannot complete next stage, "Food"
![изображение](https://user-images.githubusercontent.com/4980243/62639441-2e795c00-b948-11e9-947b-690bc1e4355d.png)

As i think this requires changes, add "nutrient check" onto FFF tutorial, or little extend text in food tutorial.

**Comment by WeaselDog** [comment]
@Quadbro Can you confirm this is still an issue and if so fix it as part of other food tutorial issue?
