### ISSUE TITLE
master: something wrong with commands

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12866]
/allworldobjects - "not found"
/forcegive - "not found"

as i see, it happens as result of moving some command to sublevel.
But /help is not fixed.
![изображение](https://user-images.githubusercontent.com/4980243/62740368-50560a00-ba40-11e9-912a-d7fb57a31793.png)

Or maybe i dont understand the logic...
In this case - need to remove / from subsection help.
(/allworldobjects looks as "fine" command)

**Comment by beastyn** [comment]
Hmm, pretty strange
When Im typing /help I get this

![bandicam 2019-08-09 09-35-45-493](https://user-images.githubusercontent.com/27898520/62754561-c5016680-ba89-11e9-95e7-f402b9e987af.jpg)

This is category list.
For full commands list use /helpful (that was changed but.. seems to be back again)

Admin commands:
/build --- Performs commands for building and tech tree manipulation
/cheat --- List of cheating commands
/civics --- Performs a variety of government operations.
/contracts --- Performs commands for contracts.
/districts --- Commands related to user-defined districts.
/food --- List of commands for food manipulations
/inventory --- List of inventory related commands
/land --- List of commands for land manipulations
/manage --- Performs commands for users administration.
/meteor --- Performs commands for manipulations with meteor.
/money --- A set of commands for manipulating money.
/objects --- Manage the various things in the game.
/pollute --- Performs commands for world pollution.
/property --- Performs commands for property manipulations.
/qa --- Preforms debugging and hard testing commands.
/rooms --- Performs commands for rooms manipulations.
/sim --- List of commands for simulations
/skills --- Performs commands for skills
/teleport --- Lists of different teleportation commands
/time --- List of commands for time operating
/titles --- View and manipulate player titles.
/util --- List of some helping commands

Developer commands:
/avatar --- Performs avatars manipulation commands.
/build --- Performs commands for building and tech tree manipulation
/civics --- Performs a variety of government operations.
/contracts --- Performs commands for contracts.
/craft --- Performs commands for crafting process.
/districts --- Commands related to user-defined districts.
/food --- List of commands for food manipulations
/inventory --- List of inventory related commands
/meteor --- Performs commands for manipulations with meteor.
/money --- A set of commands for manipulating money.
/objects --- Manage the various things in the game.
/preset --- Spawns a storage with predefined set of items in the game
/qa --- Preforms debugging and hard testing commands.
/sim --- List of commands for simulations
/skills --- Performs commands for skills
/teleport --- Lists of different teleportation commands
/test --- Performs commands for common testing scenarios.
/time --- List of commands for time operating
/titles --- View and manipulate player titles.
/tutorials --- Performs commands for tutorials.
/voice --- Performs commands for voice chat.

User commands:
/avatar --- Performs avatars manipulation commands.
/civics --- Performs a variety of government operations.
/economy --- A set of commands related to the economy.
/emote --- Perform an animated emote.
/help --- Displays all the commands available with hidden subcommands. Accepts a string to filter commands to a search string.
/helpful --- Shows all help, including sub commands.
/land --- List of commands for land manipulations
/manage --- Performs commands for users administration.
/money --- A set of commands for manipulating money.
/rooms --- Performs commands for rooms manipulations.
/sim --- List of commands for simulations
/time --- List of commands for time operating
/titles --- View and manipulate player titles.
/util --- List of some helping commands

**Comment by elfl0rd** [comment]
yes, this is /qa subcategory, but current behavior is confusing.
Some commands from subcategories work as is - e.g. /give.
Some - not.

**Comment by beastyn** [comment]
So, do you have problems with help and helpful? I can't catch your issue. For me these lists are loooking fine.
This is how it works on master.
Every command has its category. To call the command you should write < /category command>
Buuuut, some of commands have shortcuts. For example /cheat give = /give
If you type /helpful you will get the full list of the commands with shortcuts in ().
I will change the view later.

**Comment by elfl0rd** [comment]
Showing subcategories command not as /allworldobjects, e.g. /qa allworldobjects or allworldobjects (no /) is more logic behavior.

**Comment by beastyn** [comment]
Thats what Im asking about. With /helpful you should see this:
![bandicam 2019-08-09 19-48-17-871](https://user-images.githubusercontent.com/27898520/62787720-bf823b80-bade-11e9-9aa1-1854e50f81b3.jpg)

With /help you should not see this command at all.
Are you sure your master is clearly updated?

**Comment by elfl0rd** [comment]
Yes, i am about /? qa
You see "fine" commands in this way, (e.g. /allworldobjects) but some commands not work if you try it as displayed.
