### ISSUE TITLE
Vehicles Have No Specified Experience For Crafting

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12865]
Almost every item has EXP value assigned for crafting, even if the EXP value is 1. This is not true for vehicles. The default condition without specification is 1 exp. 

This line of code is missing from all the vehicles' .cs files:
"this.ExperienceOnCraft = 1; "  

As a result all of the following items have the same exp value: Small Wood Cart, Iron Plate, Steam Truck, Steel Plate, and Excavator.

I suggest to assign exp values to these, especially Steam Truck & Excavator. Mechanics & Industry grind is slow and it should have more benefit to craft vehicles.

For comparison, a Portable Steam Engine gives 10 exp and a Gearbox gives 2 exp.

**Comment by johnkslg** [comment]
Created as bug

**Comment by D3nnis3n** [comment]
> I looked at the data below and based on my playtime as Mechanics I have suggested values for the Mechanics vehicles:
> 
> * Steam Truck - 25 EXP
> * Wooden Elevator - 10 EXP
> 
> Both currently have no assigned experience value as mentioned in [StrangeLoopGames/EcoIssues#12865](https://github.com/StrangeLoopGames/EcoIssues/issues/12865)
> 
> **Mechanics Experience Data**
> 
> * Machinist Tables - 5 EXP
> * Lathe - 20 EXP
> * Assembly Line - 40 EXP
> * Steam Engine - 25 EXP
> * Portable Steam Engine - 10 EXP
> * Boiler - 3 EXP
> * Gearbox - 2 EXP
> * Most intermediate goods - 1 EXP

**Comment by beastyn** [comment]
@craig-jong 
I will leave issue for balance part.
For now experience is still 0.5 - 2. its too small
