### ISSUE TITLE
[8.2.9] Keymapper doesn't save all keys to config file

### ISSUE THREAD

**Issue by Sevinz** [StrangeLoopGames/EcoIssues#12868]
Steps to reproduce:
- Change keymap for movement (WASD)
- Restart game
- Movement keys come back to default WASD as primary and arrows as secondary

it also takes a long time to open the "control options" compared to [8.2.8]

I have checked in the "\AppData\LocalLow\Strange Loop Games\Eco\inputManager.cfg" and I see no reference to the movement keys.

Other remapped keys are saved correctly.

Comparing this file with the one created in [8.2.8], it looks like there is missing the two main axis "vertical" and "horizontal", as the file starts with the "jump" keymap just after the mouse invert on [8.2.9] instead of the two movement axis in [8.2.8]

(Had to rename the file to .txt because github doesn't accept .cfg files for some reason)

[inputManager.cfg.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3483891/inputManager.cfg.txt)

**Comment by SlayksWood** [comment]
dup #12819
