### ISSUE TITLE
Pc Shutdown + Log included (crash dump available) 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1286]
http://ecoforum.strangeloopgames.com/topic/2024/client-bug-pc-shutdown-log-included-crash-dump-available

Eric can you help this customer her ?

**Comment by UrbanSkurken** [comment]
Thank you kindly for posting this for me, now I just eagerly await for a response well known that you are busy of course. 
Just weird to me that this happens with ECO Global solely, and not anything else.

**Comment by metachronism** [comment]
hopefully unity upgrade has fixed some of these issues
