### ISSUE TITLE
USER ISSUE: conection failed on singleplayer world

### ISSUE THREAD

**Issue by Kcmouse** [StrangeLoopGames/EcoIssues#12877]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
1. host your own world 
2. name 
3. start game 
4. starts to load then crashes

**Expected behavior:**
makes world new world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by D3nnis3n** [comment]
Duplicate
