### ISSUE TITLE
[0.8.3.0 staging-1075] Crash to Desktop

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12873]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3485174/Player-prev.log)
![image](https://user-images.githubusercontent.com/45708377/62762648-452bca00-ba92-11e9-84a8-d13a58cbd784.png)
Fisrt same crash I got at staging-1073.
Step to reproduce:if you want to fast reproduce you can use dev tool, but it also appeares with shovel.
- you can dig Sand/Dirt in Deep Ocean Biome or Ocean Biome
![image](https://user-images.githubusercontent.com/45708377/62761545-9b4b3e00-ba8f-11e9-8cca-664e98c55dbf.png)
- you can dig Dirt in Desert Biome
![image](https://user-images.githubusercontent.com/45708377/62762545-0a299680-ba92-11e9-8035-fad16a456459.png)

**Comment by mirasrael** [comment]
Seems related to bug in Unity 2019.2. Reported. Waiting for hot fix, otherwise probably have to downgrade Unity version or use another particle effect.

**Comment by mirasrael** [comment]
https://issuetracker.unity3d.com/issues/worldcollision-crashes-when-spawning-particles-with-world-collision-enabled

**Comment by mirasrael** [comment]
Moved this to 9.0, because it is fixed in 8.3 with Unity downgrade, but we should ensure it will be fixed in 9.0 (hopefully with Unity 2019.2.2+ release).

**Comment by mirasrael** [comment]
Fixed in Unity 2019.2.6, master switched to this Unity version.
