### ISSUE TITLE
[0.8.3-staging - 1083] Falling down into the <hell pit> chunk

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12883]
Just drive video + bonus video (endless infernal fall cycle)
(falling down is usually happens on a ramp )

https://drive.google.com/file/d/1zNUVMf99AOmjFMoVZKqLkv-OJ89ILDdN/view?usp=sharing
https://drive.google.com/file/d/1MoEyJt2u46SQP3oKrmU74BxTa_Jn6qrS/view?usp=sharing

**Comment by D3nnis3n** [comment]
We have that every five minutes. All i'm doing is rescuing cars and people. Haha.
