### ISSUE TITLE
master: "slope flat" form not work as intended

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12882]
**Version:** 0.9.0.0 beta master-debug
![изображение](https://user-images.githubusercontent.com/4980243/62931424-074ae080-bdc7-11e9-8053-eae19c549e59.png)
Full block in any case

**Comment by keegan-o** [comment]
For sure, on the list to fix! I was having second thoughts about it but am adding other forms so I can allow it to work as originally intended.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/67184596-c554a100-f3ec-11e9-97db-6db879681a13.png)

**Comment by elfl0rd** [comment]
Still not work.
1399
![изображение](https://user-images.githubusercontent.com/4980243/74552870-3a814e80-4f67-11ea-859e-866a6f75ebe5.png)

**Comment by elfl0rd** [comment]
Я так понимаю в тонкие крыши таки "нишмагла"? xD
