### ISSUE TITLE
Master: repairing is not available

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12885]
Due to repair station changed to "tool bench" but tool bench is not contain "repair" tab.
![изображение](https://user-images.githubusercontent.com/4980243/62934547-7deadc80-bdcd-11e9-8211-a6e07a3afe18.png)

**Comment by elfl0rd** [comment]
One month pass... Nothing changed.
You want to release with it? lol.

**Comment by SlayksWood** [comment]
merged to #13214
