### ISSUE TITLE
[0.8.3-staging-1099] Invalid contracts acceptance 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12899]
Steps
1. Cut a tree.
2. Claim some deed with debris and stump.
3. Create contract for debris clearing on this deed.
4. Remove some rects on this deed and forget about recalculating debris in contract.
5. Let someone take this contract.

Expects:
Someone can't take this contract as it wasn't updated after deed changes

Actual:
Someone can take it and finish it instantly

**Comment by olegshegai** [comment]
Unclaiming now triggers recalculation of contracts related to the deed:
https://drive.google.com/open?id=1WPkP54hGlKM55jakad_T8tH4SToVvKMO

Will be added after (or maybe with) this PR:
https://github.com/StrangeLoopGames/Eco/pull/5145

**Comment by beastyn** [comment]
If I've got you right:
1) Unclaim the deed
2) Get contract's window if contract is connected to this deed

Few things that we need to change:
1) Show contracts window when you unclaim deed and CLAIM additional rectangles.
There is a situation when I was claiming new rectangles with debris and I didn't get contract window.
2) I was getting contracts even if they are not connected to this deed. And even closed ones
this is my board:
![bandicam 2019-11-14 16-06-04-977](https://user-images.githubusercontent.com/27898520/68852047-ead97f80-06f8-11ea-8e55-0b7821c1415b.jpg)

And when I was unclaiming Debris deed, Screen become black and I've got a lot of contracts
![ac33100503ae12e33e6aa23c11484c47](https://user-images.githubusercontent.com/27898520/68852192-39871980-06f9-11ea-9f00-b4e5f1e98d2c.gif)

I should get only active contracts and only connected to this deed.

**Comment by beastyn** [comment]
So, what I see
1) If you've made a contract but no one accepted it:
- If you add a claim, you will get a notification about recalculation(without opnening contract UI)
- removing claim -  you don't get a notification.
2) If someone has accepted a contract? you will get contract UI in the both cases.
Actually case 2) kind of annoying.

How do you think about recalculating on the background like in 1) always?
But there is an issue.
It will notify you about recalculating, but when you are opening a contract you will see the old numbers. And a contracter will see the wrong numbers too. But actual counting will be the new one.
![bandicam 2019-11-20 12-35-32-791](https://user-images.githubusercontent.com/27898520/69218447-99b30b00-0b92-11ea-85fc-9d7c50b3b11f.jpg)
![bandicam 2019-11-20 12-35-49-132](https://user-images.githubusercontent.com/27898520/69218452-9ae43800-0b92-11ea-886b-8fbb611e16b9.jpg)
![bandicam 2019-11-20 12-36-06-896](https://user-images.githubusercontent.com/27898520/69218456-9b7cce80-0b92-11ea-96ad-492fe4bfb2e6.jpg)
![bandicam 2019-11-20 12-37-29-049](https://user-images.githubusercontent.com/27898520/69218458-9d469200-0b92-11ea-9754-e58e52937d96.jpg)



Then I will make separate issue about notification changes in Work Notification panel for this with low pri. I think this will be just enough.

**Comment by beastyn** [comment]
Wrong recalculating.
1. Have 12 debris
![bandicam 2019-11-29 11-55-24-800](https://user-images.githubusercontent.com/27898520/69849935-dd4afa80-129f-11ea-842a-319b8d88671c.jpg)
2. Remove one claim
3. Have 0 debris
![bandicam 2019-11-29 11-55-44-420](https://user-images.githubusercontent.com/27898520/69849944-e2a84500-129f-11ea-8cb3-6a93b775f734.jpg)
Its obviously not 0
![bandicam 2019-11-29 11-56-08-302](https://user-images.githubusercontent.com/27898520/69849952-e50a9f00-129f-11ea-8603-4396312e5dc8.jpg)
4. Contractor sees 0 debris and can finish the job
![bandicam 2019-11-29 11-58-57-722](https://user-images.githubusercontent.com/27898520/69849955-e8058f80-129f-11ea-896e-247d44fca2a2.jpg)
