### ISSUE TITLE
[0.8.3.0 staging-1097] Planted young trees teleport to another place

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12893]
![2019 08 15 Trees teleport](https://user-images.githubusercontent.com/45708377/63094508-50d72f00-bf71-11e9-8a40-2a3dfc455b35.gif)
Red - planted trees
Blue - teleported trees from previous try
![image](https://user-images.githubusercontent.com/45708377/63094412-fc33b400-bf70-11e9-9b18-6f9ecb13af69.png)
Green - teleported trees in GIF
![image](https://user-images.githubusercontent.com/45708377/63094681-bd522e00-bf71-11e9-9a19-735f59c6a3ba.png)
Screenshot shows that 5 trees have moved and the remaining 6 trees have disappeared. Perhaps the part of them  didn't get into screenshoot. But at least 3-4 trees are definitely gone. Maybe they were teleporting to the floor of house and just disappeared

**Comment by beastyn** [comment]
dup #12825
