### ISSUE TITLE
[0.8.3.0 staging-1099] Highlight from Land Claim Stake in Excavator

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12898]
Step to reproduce:
- spawn excavator
- select Land Claim Stake in toolbar
- mount excavator and go to Digging mode
- try to Dig, you will see highlight from Land Claim Stake (like you want to claim this plot)
![image](https://user-images.githubusercontent.com/45708377/63163993-a8d46b00-c02f-11e9-959e-2b6c9ac2063d.png)

**Comment by IcedForge** [comment]
I liked this "feature" XD Made digging along claims very easy :D.
Now we got the property overlay we can use ingame though so thats possible to use instead.

**Comment by TwixterZ** [comment]
on 0.9.3.0 beta staging-1945, this no longer highlight the ground as shared above, however its showing "claiming property plots" on ui 

![image](https://user-images.githubusercontent.com/78054747/110120874-95971500-7df8-11eb-90d9-dac37238946a.png)
