### ISSUE TITLE
Glassworking Level 6 Talent Issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12909]
For Glassworking, the talent Frugal Workspace has no effect and the talent Lavish Workspace has no penalty. 

The Kiln is classified as Mortaring for the Frugal Workspace/Lavish Workspace room requirement check. Meanwhile Glass & Reinforced Glass gain the benefit from Glassworking Lavish Workspace talent. The Kiln is unaffected by Glassworking Frugal Workspace talent

**Comment by SlayksWood** [comment]
dup #12408
