### ISSUE TITLE
/mute command

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12906]
To mute people in the chat. + Unmute command.

(Admin Command = Global Mute with Time and Reason in the best case)

**Comment by D3nnis3n** [comment]
Reopened, beastyns fix was for #12906

**Comment by beastyn** [comment]
@D3nnis3n  Mute is working but:
1) There is no timer
2) The reason is visible for the muted person only. Should it be global announced?

**Comment by D3nnis3n** [comment]
A systems for timers would be great in general, as bans should get them as well as of talk with Todd. (Like Bans should get a reason as well)

So yes, depending on how much work it is, being able to set a time for them would be great.

**Comment by IcedForge** [comment]
Giving attention to this as well since they both are in the same spectrum of functionality https://github.com/StrangeLoopGames/EcoIssues/issues/18715

**Comment by SlayksWood** [comment]
Tested it in last week, It works, but need some improvements for server ui here #20725
