### ISSUE TITLE
Eco (night\day) staging - failed to launch, "Failed to load il2cpp"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12908]
![изображение](https://user-images.githubusercontent.com/4980243/63224244-0a304180-c1ca-11e9-9876-ea867ff2bd0d.png)

**Comment by beastyn** [comment]
win 7?

**Comment by elfl0rd** [comment]
yes, w7 x64
no client log was generated.

**Comment by beastyn** [comment]
Can you check please if this will help you:  install/update visual studio runtimes from 2017 onwards

**Comment by redwyre** [comment]
Also make sure you're running Win7 SP1 at least (this is the current minimum requirement of Unity).
But to be clear, Windows 7 isn't supported by Eco, so it could stop working at any point.

**Comment by elfl0rd** [comment]
![изображение](https://user-images.githubusercontent.com/4980243/63283005-bf412780-c2b8-11e9-8dc9-852a5addaea3.png)
This is fresh staging build from dev access. As you can see - all ok.

![изображение](https://user-images.githubusercontent.com/4980243/63283132-26f77280-c2b9-11e9-8416-80da82ac53dd.png)
This is my installed VSr

Also about "Windows 7 isn't supported by Eco, so it could stop working at any point."

Yes, ofc. But 20% of steam users use w7, i recommended to you keep Eco working at W7 (at general).

Keep in mind, users who bought Eco before sys req changed - can easy return money trough steam support.
And negative reviews... comments... etc.

**Comment by haykazkotanjyanslg** [comment]
It is unity 2019.1.8 issue 
It is resolved with Unity  2019.1.6
