### ISSUE TITLE
Daily Chatlog

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12905]
Next to a global admin command log, an easily accessible daily chatlog would be very helpful.

**Comment by elfl0rd** [comment]
Something same for 'AA' log?

**Comment by D3nnis3n** [comment]
What do you mean?

**Comment by elfl0rd** [comment]
daily admin actions log

**Comment by MonzUn** [comment]
@D3nnis3n this one should be possible to close now right?
Just found it while checking for issues with the current implementation :)

**Comment by D3nnis3n** [comment]
Indeed.
