### ISSUE TITLE
5.5.1 StoneWellItem tooltip crashes client

### ISSUE THREAD

**Issue by Neouni** [StrangeLoopGames/EcoIssues#1290]
Browsing through the available items caused me to view the tooltip on the stonewell crashing the client.
_Checked the item.cs only thing missing seems description, odd_

**Comment by MarjieAVolk** [comment]
Apparently this is happening because StoneWell is all placeholder and not set up to be crafted, so not sure how you saw it at all, but I've made some changes to handle this without crashing, although it's tooltip is not attractive due to it's strange configuration.

**Comment by Neouni** [comment]
I saw it in the Shop wanted item window, Since it even lists things like bodyparts and devtools.

**Comment by MarjieAVolk** [comment]
Aha -- I'll add an issue to hide things like that in the shop.  Thanks.  If you see crashes for tooltips elsewhere, file another issue to let me know which objects are causing it!
