### ISSUE TITLE
[master-preview] Host a world (and load loacal world) doesn't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12912]
Steps:
1. Launch client (no server is working)
2. Press "Host a Wprld"
3. Put name and press start

Expected:
Local world is created and you are in the game

Actual:
World is created but you can't connect.
 
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3514406/log.txt)

**Comment by mirasrael** [comment]
WWise related errors in log
