### ISSUE TITLE
[0.8.3.0  staging-1106] Bank account selection for public tables

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12924]
We should give users a possibility to choose bank account when they are crafting on public tables with fee (like in store)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/69328290-0b0cbf80-0c60-11ea-8764-b289701dd49a.png)
in 0.9.0 staging-1262 it display in Repair Tab.
