### ISSUE TITLE
Need view system upgrade

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12922]
Users are often shared through the view system, but there are properties on users that constantly get updated, and when there are hundreds of users we don't want to update all the calories of every user many times a second, it will kill performance.

We'll need to handle this one of two ways:
- Add an attribute to the view system that prevents parameters from going to everyone, only to a special subset.
- Move the frequent updating parameters off User into something more private for the client.

We should also provide a way to detect when specific properties are updating more than they should with metrics.

**Comment by johnkslg** [comment]
Something to consider if view system is slow.

**Comment by mirasrael** [comment]
Seems like already implemented with SyncFlags.MustRequest and view updates tracking in Server UI.
@johnkslg anything else?
