### ISSUE TITLE
USER ISSUE: Can't place roads directly taken from the table

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#12923]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
1. Craft some stone roads in the wainwright table
2. Unlink any storage, while the roads are being built
3. Take the finished roads directly from the table.
4. Try to place the road in the world

**Expected behavior:**
The roads should be placed as normal

**Actual behavior:**
The roads are not placed. If you put them in any storage and take them from it then they can be placed

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods that I know

**Comment by SlayksWood** [comment]
@LoBlanc 
Can't reproduce in 8.2.9 and in 8.3.0 staging-1106. Can you repeat it and provide log files? Also, please provide some more information to reproduce it.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@LoBlanc 
Closing for no response, reopen when you can provide us with necessary information
