### ISSUE TITLE
Hammer placement feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12920]
Cursor positioning changes:
![animx](https://user-images.githubusercontent.com/3536496/63293359-d104d980-c27c-11e9-9706-dbea50a1e778.gif)
![animx](https://user-images.githubusercontent.com/3536496/63293535-22ad6400-c27d-11e9-8f1f-613d0bd8a02c.gif)
I'd like to change the positioning to work as follows:
- Once you click a starting position, the faded outline will always display (no matter how far you get away from it), and the popup control text will always display too saying the status
- The entire shape should have the outline on it, not just the final block:
![image](https://user-images.githubusercontent.com/3536496/63293642-63a57880-c27d-11e9-9b0e-56c50d22a7b7.png)
This is how cranes worked
- The distance you can make a line will cap out at the max blocks you have, and the popup text will inform you when you're trying to stretch it too far, and the highlight will turn red.   Highlight should always be white when you can place at the current position, and always be red when there is anything preventing it, and the control popup text should always say the status.  

Ie, say you have 4 blocks and start a line and highlight 7 blocks away. You should see the line stop at 4 blocks, going towards the selected position, with status text explaining you dont have enough blocks over the last block in the line. 

 - There should be a way to clear the line, communicated in the popup text (left click?)

**Comment by redwyre** [comment]
The selection was a prefab issue, all working now, so the two remaining issues are:
 [ ] Fix issue with line shifting away from starting point when you moving the end point perpendicular.
 [ ] Add a way to clear the line, communicated in the popup text (left click?)

**Comment by redwyre** [comment]
I'm moving these smaller issues to a separate tracking issue: https://github.com/StrangeLoopGames/EcoIssues/issues/12926
