### ISSUE TITLE
[master-preview] Property rights transfer feedback

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12936]
- [ ] Somehow Kirill couldn't give rights to me on his deed. But I could on my deed. We were testing on my server.
![2019 08 21_Change_deed_owner_](https://user-images.githubusercontent.com/27898520/63433514-c1cc8a00-c43c-11e9-9061-919f76d6eb90.gif)
[Player (8).log](https://github.com/StrangeLoopGames/EcoIssues/files/3525396/Player.8.log)

- [ ] There is no highlight after clicking on the name (only with cursor)

**Comment by johnkslg** [comment]
I cant read the text. Whats happening there, youre trying to apply a change but its not taking?

**Comment by beastyn** [comment]
I tells "You don't have permission to change this owner."

So, Kirill was trying to give me owner rights for his deed, by clicking on my name and applying, but he was getting this message.
