### ISSUE TITLE
[master-preview] Strange mesh for grass

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12937]
![unknown (1)](https://user-images.githubusercontent.com/27898520/63437306-b892eb80-c443-11e9-976d-56b8dc4919e2.png)

**Comment by mirasrael** [comment]
Problem was with mask texture, it hadn't Alpha Source set to Input Texture Alpha.
Fixed in SVN.
![image](https://user-images.githubusercontent.com/475445/64532120-92ad8800-d319-11e9-8383-b6b0d6684502.png)
