### ISSUE TITLE
[master preview] Tutorial has two meteor tasks

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12930]
on the pic
![bandicam 2019-08-21 09-05-40-951](https://user-images.githubusercontent.com/27898520/63402098-62965780-c3f3-11e9-8b6d-291adbb7239b.jpg)

**Comment by beastyn** [comment]
From John
Got double tutorials after disconnecting and reconnecting

**Comment by gzatravkin** [comment]
Can't reproduce. Any specific actions? Please attach a video

**Comment by SlayksWood** [comment]
There are no specific actions. But it happened to me again the day before yesterday. Still an issue, but I can't say to you 100% steps to reproduce

**Comment by beastyn** [comment]
Yeap, happend in playtest too, look at 13455, John got it. We don;t have actual steps, it just happens.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/68577970-2ddded80-0482-11ea-9f8e-2e88e8af5ffe.png)
