### ISSUE TITLE
[master-preview] Work orders tutorial should be remastered

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12931]
Its a great place to tell about tagged crafting a little and also art should be changed
![bandicam 2019-08-21 09-15-20-454](https://user-images.githubusercontent.com/27898520/63402288-39c29200-c3f4-11e9-93ee-902599b58542.jpg)

**Comment by beastyn** [comment]
+ about calories

**Comment by johnkslg** [comment]
@serpopov want to take a stab at this? @RobertMangano can hook you up with any art you need.

**Comment by gzatravkin** [comment]
Attaching order tutorial update from Anna
[Order_tutorial_update_v2.pdf](https://github.com/StrangeLoopGames/EcoIssues/files/4512667/Order_tutorial_update_v2.pdf)

**Comment by beastyn** [comment]
Slide 2
![bandicam 2020-04-28 12-06-00-146](https://user-images.githubusercontent.com/27898520/80457465-cbea4500-8948-11ea-90e5-54a85d85784c.jpg)

- acept typo - should be "accept"
- Animation:  Cursor should go to the log icon and then tooltip appears

Slide 3
![bandicam 2020-04-28 12-24-46-468](https://user-images.githubusercontent.com/27898520/80459119-503dc780-894b-11ea-9055-7c8f323484e2.jpg)
- Need a dot at the end of the "Work order also need labor to complete."
- Seems like font on this slide doesn't have bold. Looks differently.
- Animation: Cursor should go to the center of the "Work" button
- Art: @keegan-o  can you help with an order picture? It would be great to have a campfire order here (as for the first slide) with the correct labor bar (top yellow).

**Comment by gzatravkin** [comment]
no need for additional art, I will copy from interface

**Comment by trickenso** [comment]
Small typo: should read "Work orders also need labor to complete" for noun agreement.

**Comment by beastyn** [comment]
Thanks, added
