### ISSUE TITLE
Remove too many logins ban from auth

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#12940]
It is a problem for students who cant enter in the right password.

**Comment by redwyre** [comment]
Rather than straight up removing it, you could change it to something like an exponential delay, each wrong attempt doubles the time until the next try. This severely limits brute force attacks.

**Comment by rainfarmer** [comment]
ok, but give them a good 30 or 50 trys first. 
It's still a recurring problem with students.

**Comment by denysaw** [comment]
Increased attempts number to 150. PR: https://github.com/StrangeLoopGames/AuthServer/pull/13
