### ISSUE TITLE
[master-preview] Stone hammer hard times

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12944]
Steps:
1. Take 15 hewn logs.
2. Place them in the floor form with STONE hammer.
3. Try to pickup one block back with STONE hammer.

Expected:
Pick up this one already.

Actual:
You will get all 15 hewn logs in your hands, but meshes will stay on the ground. After relog meshes will dissapear and hewn logs will be in your hands.
Other tiers are fine
If blocks were placed with 2+ tier hammer, then they are taken with stone hammer correctly.

https://drive.google.com/file/d/1sMEIbFQdABo9Ag8674B05DtPIaj9mWqV/view?usp=sharing

**Comment by redwyre** [comment]
Fixed in SVN
