### ISSUE TITLE
Digging soil under trees should not destroy the tree

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1294]
http://ecoforum.strangeloopgames.com/topic/2049/planted-trees-bug/5

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2068/bugged-trees

**Comment by NafenX** [comment]
Also using an Axe to remove a tree stump will not cause the rest of the tree to despawn like it does when using the Shovel.

**Comment by metachronism** [comment]
additionally, some area around the tree roots should not even be diggable with basic starter tools
