### ISSUE TITLE
Purchase form broken at site

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12953]
https://accounts.strangeloopgames.com/products/upgrades and https://accounts.strangeloopgames.com/home

If you are not logged in - site show "e-mail" form.
If you are logged in - nothing happens after click.

![изображение](https://user-images.githubusercontent.com/4980243/63561567-166a2500-c563-11e9-9820-9ec604b0f611.png)

`jquery.min.js:4 POST https://accounts.strangeloopgames.com/products/buyproduct/9 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
(anonymous) @ Payment.js:71
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
x @ jquery.min.js:4
b @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
Payment.submit @ Payment.js:46
(anonymous) @ upgrades:420
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3`

Mention this user after fix please. Daemonwolf#3291

@johnkslg @rainfarmer

**Comment by anatoly-slg** [comment]
resolved
