### ISSUE TITLE
Mousing over work order UI should show tooltip

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12952]
![image](https://user-images.githubusercontent.com/3536496/63557149-65c93a80-c4fc-11e9-8209-25b2a64855a1.png)

Use the HasViewTooltip component, slap a WorkOrder view in it during initialize, setup mouse blocking, and you're good to go.

**Comment by SlayksWood** [comment]
seems fixed
![image](https://user-images.githubusercontent.com/45708377/74314304-45c95400-4d86-11ea-876b-bde66441b8ea.png)
