### ISSUE TITLE
USER ISSUE: connection fail

### ISSUE THREAD

**Issue by thedirtypanda** [StrangeLoopGames/EcoIssues#12958]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
trying to connect to "host your own world"

**Expected behavior:**
It should have logged in

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by SlayksWood** [comment]
@thedirtypanda 
1. Are you having this issue with every server?
Can you try to connect to official servers and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the "latest build" or you had it before?
7. Do you have external IP address and did you use it in config file?

**Comment by mirasrael** [comment]
Hi @thedirtypanda!
It seems you're trying to run local world. Usually you have such error when local server fails to start. 
You can get logs following these instructions and attach to issue:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by SlayksWood** [comment]
@thedirtypanda 
Closing for no response, reopen when you can provide us with necessary information
