### ISSUE TITLE
[8.3.0 Release-Preview] Client - Fatal Error

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#12959]
Downloaded the bleeding edge 8.3.0 client version from SLG website account page. Upon attempting to run Eco.exe it results in a Fatal Error with the message 'Failed to load il2cpp'.

I redownloaded it to ensure it wasn't a download or unzip error.

After further chat in discord I believe this is a Windows 7 issue.

**Comment by mirasrael** [comment]
We updated version on web-site. Please, try with new version.

**Comment by Yorkforce** [comment]
Yep it launches now, thanks! :)
