### ISSUE TITLE
Issue in modded recipes.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#12956]
If an item or object has a recipe, unless its perfectly defined with ingredient and product, it won't let the server boot.
Example:
- This doesn't let the server load.
[BarnDoor.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3534127/BarnDoor.txt)
  But removing the entire recipe entry in the .cs file will work, as seen below.
[BarnDoorNoRec.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3534132/BarnDoor.txt)

**Comment by redwyre** [comment]
What error are you getting from the server? Also is this with 8.2.9 or master?

**Comment by WeaselDog** [comment]
@Phlo123 Is this still an issue?

**Comment by Phlo123** [comment]
Probably not. Did not test since.
