### ISSUE TITLE
Invalid login info

### ISSUE THREAD

**Issue by Thesam1798** [StrangeLoopGames/EcoIssues#12960]
**Version**: 0.8.2.9 beta

**Steps to Reproduce**:
trying to connect to any server with a steam account that has shared the games in family mode

**Expected behavior**:
connect to the server

**Actual behavior**:
[Eco Login Faild Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3537025/Eco.Login.Faild.txt)

**Do you have mods installed? Does issue happen when no mods are installed?**:
No mods

for information I have the same mistake from almost 1 year ago

**Comment by elfl0rd** [comment]
> Family sharing not supported for Eco.
Bug returned? https://github.com/StrangeLoopGames/EcoIssues/issues/12797
@D3nnis3n

**Comment by SlayksWood** [comment]
It didn't return. It will be fixed in 0.9.0.0
