### ISSUE TITLE
addcomment/ auth not working

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1296]
User cant comment on elections or laws, 
even with proper authtoken, username and in swagger.
  
Receive this response from addcomment query:
"Message": "User testalpha does not exist."

**Comment by MarjieAVolk** [comment]
This is intended behavior; the issue is that the user doesn't exist on THIS server - they need to become a user of this server by logging in to the server (users generated in generatetestdata are also automatically made users of the server)
