### ISSUE TITLE
Crash with hammer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12966]
Got a crash while the game was trying to serialize BoxFill:
![image](https://user-images.githubusercontent.com/3536496/63729193-522f1400-c81b-11e9-89ec-37bc21628d5d.png)

Looks like the problem is that BoxFill derives from Item, this shouldnt be an item and should not be serializable.  

I see this was made an item a few days ago, presumably to get some functionality of items. Unfortunately it got too much, and should be refactored to have shared interfaces/baseclasses with Item but not derive directly from it.

**Comment by redwyre** [comment]
Why should it derive from Item? I figured if talents do, it should be fine...

What specifically functionality should they have/not have?

**Comment by redwyre** [comment]
How about renaming Item to InventoryItem (which makes it clear the intended use) and creating a new base class Item that has those few things?

**Comment by redwyre** [comment]
This should be fixed now as they don't derive from Item anymore
