### ISSUE TITLE
[0.8.3.0 release-preview] Meshes don't disappear

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12967]
Step to reproduce:
- spawn skid steer or Exca.
- start to mine ore with skid steer or exca
- sometimes meshes don't disappear. See video:
https://drive.google.com/file/d/16ZO_PVEN93LSb7tiFNnmx9MfxAzW-Wmg/view?usp=sharing
It doesn't always happen.
- If you then start mining with pickaxe It also happens:
https://drive.google.com/file/d/1P9FsYuFhK1ScRA2NrPdLsPZaK1QV_HMk/view?usp=sharing

**Comment by TootleBrush** [comment]
This exact same issue happens for me still. But it also include the excavator, and both leave behind the mesh of the dug/mined blocks. One don't even have to spawn a skid steer / excavator. 
1. jump in to one of the two mentioned vehicles.
2. hold down the dig button for the skid steer and charge at blocks to dig them. Blocks react as shown in above film.
2.5 go in to digging mode for excavator. dig with teh bucket and the blocks will react exactly as on the above film, for both dirt and stone blocks.
