### ISSUE TITLE
Internet connection drops then issue reconnecting

### ISSUE THREAD

**Issue by mattkennedynz** [StrangeLoopGames/EcoIssues#12961]
**Version**: 0.8.2.9 beta

Hey all, so I have annoyingly spotty wifi at my place which sometimes results in my connection dropping once every hour or so. 

The issue is, when my internet connection drops and I reconnect to the wifi again (manually), Eco seems to have an issue realising it has internet again. When attempting to rejoin the Eco server the connecting loader modal will spin for a bit, then the game will crash. The only solution seems to be a full restart of Eco.

**Comment by mirasrael** [comment]
Hi @mattkennedynz 
Sorry, for very loooong answer. We did lot of improvements for network communication (including switching to another network lib in 9.0). So let us know if it still an issue (if you're still playing).

**Comment by mattkennedynz** [comment]
Hey @mirasrael, I have since changed locations and don't have the same wifi issues—so I'm not sure I'll be able to confirm if it's still happening. Someone else might report it down the line if it's still an issue.

**Comment by mirasrael** [comment]
Thanks @mattkennedynz for response! I'll close issue for now. If somebody have similar issue he/she can comment here or open new issue.
