### ISSUE TITLE
Hammer Feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12963]
- [x] Wasnt able to drop this Copper Ore block while holding hammer, probably because it has no forms
![image](https://user-images.githubusercontent.com/3536496/63730229-3a598f00-c81f-11e9-9c9f-749fc530e84d.png)
- [x] Holding shift displayed the hammer UI off screen. Need to fix anchors for various resolutions, and clamp the ui
![image](https://user-images.githubusercontent.com/3536496/63712583-d28d4f00-c7f2-11e9-8cee-63ac8f2913d4.png)
- [ ] Selection has a number of problems still. It needs to work off a projection, so it can place second selection even in midair.  IE, once you start drawing a line it should always display that line no matter where you're looking.
![animx](https://user-images.githubusercontent.com/3536496/63712790-42033e80-c7f3-11e9-99f7-658d28a28834.gif)
- [x] Popup text should say how many you need. 'Not enough materials (5 needed)' 
![image](https://user-images.githubusercontent.com/3536496/63712859-63642a80-c7f3-11e9-89bf-1e9d4b382528.png)
- [x] After placing a block, there's a delay before you see it. Notice in the gif how it blinks away for a second. Prediction should be handling this.
![animx](https://user-images.githubusercontent.com/3536496/63713052-bccc5980-c7f3-11e9-8ba6-88219e1edf23.gif)
- [x] Text for placing first point in a shape should be more descriptive.  Ie: 'Place first floor corner' or 'Place line starting position'
- [x] 'Material' section needs to be hidden of setup properly
![image](https://user-images.githubusercontent.com/3536496/63713193-07e66c80-c7f4-11e9-95a4-c8e3990fd76d.png)
- [x] Text should still have controls for rotation, Q/R
![image](https://user-images.githubusercontent.com/3536496/63713236-1765b580-c7f4-11e9-89ac-2afae195920e.png)
- [x] Clicking these brought up the hammer selection dialog, which is good, but they also stayed highlighted
![image](https://user-images.githubusercontent.com/3536496/63713523-aecb0880-c7f4-11e9-9302-e07860e77715.png)
Perhaps shift should be on the 'point' and 'ladder' icons instead.
- [x] Got this client exception at one point not sure when:
![image](https://user-images.githubusercontent.com/3536496/63730251-59f0b780-c81f-11e9-9c3a-7d032c42ce71.png)

**Comment by redwyre** [comment]
@johnkslg 
"Wasn't able to drop this Copper Ore block while holding hammer, probably because it has no forms"
If the hammer doesn't do anything, the interaction is passed to the carried item (this isn't a change in behaviour).

"After placing a block, there's a delay before you see it. Notice in the gif how it blinks away for a second. Prediction should be handling this."
It is using block prediction, is it a problem if they all use the same ID?
Actually, on second look, I think the lag you are seeing might be in the chunk renderer/combiner.

"Got this client exception at one point not sure when:"
Easy fix, will get that in next PR

**Comment by redwyre** [comment]
> Selection has a number of problems still. It needs to work off a projection, so it can place second selection even in midair. IE, once you start drawing a line it should always display that line no matter where you're looking.
There was actually a bug with placing carried items while an item is selected in the toolbar was restricting the placement distance, now placement for carried items is fixed to the standard placement distance.

**Comment by redwyre** [comment]
Can you re-review the hammer selection?

Also if we want to do something about the occasional lag, can you make that a new issue as it's not specifically a hammer issue.

**Comment by SlayksWood** [comment]
Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/75133901-8a8dad00-56ed-11ea-8fd1-b30cc7f838ad.png)
