### ISSUE TITLE
Master: mouse cursor hides after "delete all marker - yes"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#12970]
![изображение](https://user-images.githubusercontent.com/4980243/63775923-0a76be00-c8e9-11e9-8123-0095f17e0642.png)
Not very usefull.

**Comment by SlayksWood** [comment]
same in 8.3.0, same if you delete only one marker. Is it intented behabior or not?
@serpopov 
Do it as you wish. But I think It's conceived so earlier.

**Comment by beastyn** [comment]
nope, still is disappearing
![0cc294cfa630794414878833b99c47fa](https://user-images.githubusercontent.com/27898520/69796001-05c6ec00-11ef-11ea-89cd-1401c883f274.gif)
