### ISSUE TITLE
Meteor Tutorial problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12977]
Camera didnt follow meteor.
![image](https://user-images.githubusercontent.com/3536496/63799947-f8cdf000-c8c1-11e9-8b0d-8b91d87c1e8b.png)

When the slideshow started, you could see the next frame behind the current frame.
Text at bottom isnt centered and can go off screen.
Fade box doesnt reach edges of screen in some resolutions.

**Comment by elfl0rd** [comment]
And... There planet is not "sphere"
![20190826103601_1](https://user-images.githubusercontent.com/4980243/63812460-1e471200-c933-11e9-8462-1548ee152571.jpg)

**Comment by SlayksWood** [comment]
dup #11957
