### ISSUE TITLE
[master-preview] Civics: Objects

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12985]
- [ ] World objects for civics should have name, not WorldObject as name

![bandicam 2019-08-28 13-04-12-676](https://user-images.githubusercontent.com/27898520/63837176-677b7e00-c994-11e9-927d-80966e8a5099.jpg)

- [ ] All new civics world objects have size 1x1x1, so placement for them is wrong. We should fix this.
![bandicam 2019-08-28 16-59-09-380](https://user-images.githubusercontent.com/27898520/63853970-79214d80-c9b5-11e9-9b4f-2de05d3199ed.jpg)
![unknown (5)](https://user-images.githubusercontent.com/27898520/63853975-7c1c3e00-c9b5-11e9-9f88-e6fc2f636167.png)
- [ ] Objects don't have any room requirements, I suppose there should be some
- [ ] Objects has missed Authorization tab
- [ ] Even if you claim a deed with object it is still shows unowned (but you actually an owner)

![bandicam 2019-08-29 12-53-34-962](https://user-images.githubusercontent.com/27898520/63921513-5e55e400-ca5c-11e9-9f25-4dfb1a8395c2.jpg)

**Comment by beastyn** [comment]
- [ ] What dependencies Civics objects have?
For now I can place court and make laws without any active constitution.
There is no requirements about it in objects.

**Comment by WeaselDog** [comment]
All of these seem fixed except the room requirements which is included in a separate issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/13980

![CivicBuildingAuto](https://user-images.githubusercontent.com/47330823/70382175-102e6780-190c-11ea-9dae-26e206590a95.png)
