### ISSUE TITLE
USER ISSUE: idk im not the dev

### ISSUE THREAD

**Issue by Drugsnix** [StrangeLoopGames/EcoIssues#12988]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
idk i just start my game.. 

**Expected behavior:**
startet my load of my game

**Actual behavior:**
The following error message popped up:
```you should develop it to do this automatic and not rely on my remembering..
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```you should develop it to do this automatic and not rely on my remembering..
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by SlayksWood** [comment]
please provide game and server log files
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
