### ISSUE TITLE
USER ISSUE: hosted own world don't load

### ISSUE THREAD

**Issue by michi22b** [StrangeLoopGames/EcoIssues#12982]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
create a new "host new own world" or load a previusly created one doesn't work.

**Expected behavior:**
enter the saved/new game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```
no mods

**Comment by michi22b** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3550055/Player.log)
[log_190828105323.log](https://github.com/StrangeLoopGames/EcoIssues/files/3550056/log_190828105323.log)

**Comment by beastyn** [comment]
@michi22b Thanks you for your report.
Looks like port is busy with something,
You can try this.
1. Reboot your PC
2. Launch server seperatly (for steam:  \Steam\steamapps\common\Eco\Eco_Data\Server)

Can you connect to the other server fron server list?

**Comment by michi22b** [comment]
2. it worked and created a new world, not sure for the saved one since i cannot find a way for selecting them to load.

other server in internet are working fine

**Comment by michi22b** [comment]
when it was loading noticed this message in the ecoserver.exe

[12:02:51] Server Initialization finished in 9'967.8ms
[12:03:11] WARN: UPnP mapping wasn't created due to an error. Server fallback to default connection settings.

**Comment by mirasrael** [comment]
You can ignore this warning. As workaround you can start EcoServer.exe with "-loadSave <your_save_name>" argument.

**Comment by beastyn** [comment]
Hope it worked
