### ISSUE TITLE
[master-preview] Civics: Capitol feedback

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12986]
Constitution:

- [ ]  Missing objects name with /civics spawngov ?
![bandicam 2019-08-28 13-12-28-712](https://user-images.githubusercontent.com/27898520/63837829-a1994f80-c995-11e9-951e-5c6be10b8450.jpg)

- [ ] Why we can't rename Constitution?  
Its just Constitution 1 (2, 3)

- [ ] What is this thing? It has nothing in the tooltip. Is it BillOfRights?
![bandicam 2019-08-28 13-15-51-669](https://user-images.githubusercontent.com/27898520/63838101-25ebd280-c996-11e9-8187-bc2a6b16e39c.jpg)

- [ ] We need to change logic for Capitol placement and constitution containing.
How it works:
1. Place Capitol (constitution 1), make civics
2. Place other  Capitol (constitution 2) in a room with the greater value, nake civics
3. Now constitution 1 doesn't work, constitution 2 works.
4. Now we are picking up Capitol with constitution 2 (atricles should be deleted).
5. But constitution 1 still sees constitution 2 and can't be ratified
Even if you destroy room for constitution 2, constitution1 won't see any changes.
(capitol with constitution 6 was picked up)
![bandicam 2019-08-28 16-17-35-442](https://user-images.githubusercontent.com/27898520/63852362-889e9780-c9b1-11e9-8059-e4c8eacae0f4.jpg)

But the most sad part here is that your articles from constitution 2 was lost. 

So, the ideas:
-1- Renaming for constitutions
-2- Each capitol should be able to create few constitutions wth their articles 
-3- Picking up capitol should save constitutions on it
-4- After placing Capitol you can Ratify any of constitutions (you can choose constitution and see articles for it)
-5- All capitols should sees other capitols statuses correctly
-6- We need to make some time lag for updating room value and replacement for capitols.
If you want to update the room around your capitol there can be a moment when room value will be lower than room value for other capitols.
And if you want to move your capitol in the other room it should stay with old values for some time and updated after placement (or be removed if time limit is off)

**Comment by beastyn** [comment]
testt is still in progress

**Comment by johnkslg** [comment]
**Missing objects name with /civics spawngov ?**
Bug added: https://github.com/StrangeLoopGames/EcoIssues/issues/13017

**Why we can't rename Constitution?**  
There's not actually anything on the constitution at the moment. This will become a thing with towns and cities, lets change it then.

**What is this thing? It has nothing in the tooltip. Is it BillOfRights?**
Added bug for making ecopedia help: https://github.com/StrangeLoopGames/EcoIssues/issues/13014
Added bug for tutorial creation: https://github.com/StrangeLoopGames/EcoIssues/issues/13018

**We need to change logic for Capitol placement and constitution containing.
How it works:
1. Place Capitol (constitution 1), make civics
2. Place other  Capitol (constitution 2) in a room with the greater value, nake civics
3. Now constitution 1 doesn't work, constitution 2 works.
4. Now we are picking up Capitol with constitution 2 (atricles should be deleted).
5. But constitution 1 still sees constitution 2 and can't be ratified
Even if you destroy room for constitution 2, constitution1 won't see any changes.
(capitol with constitution 6 was picked up)**
Added bug for moving civics objects: https://github.com/StrangeLoopGames/EcoIssues/issues/13015

Constitution 1 should become ratifiable if constitution 2 gets disabled, if that doesnt happen can you open a separate bug? 

**But the most sad part here is that your articles from constitution 2 was lost.** 
- Capitol should not be able to be picked up if you have articles on it, thats a bug if so.  Were you picking up with hammer? I got this:
![image](https://user-images.githubusercontent.com/3536496/63995085-fcbd6600-caab-11e9-9cdb-4a52388c4431.png)


**We need to make some time lag for updating room value and replacement for capitols.
If you want to update the room around your capitol there can be a moment when room value will be lower than room value for other capitols.
And if you want to move your capitol in the other room it should stay with old values for some time and updated after placement (or be removed if time limit is off)**
Added separate bug for this: https://github.com/StrangeLoopGames/EcoIssues/issues/13016
