### ISSUE TITLE
[master-preview] Alligators don't know how to die

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12980]
![2019 08 28 Alligators don't know how to die](https://user-images.githubusercontent.com/45708377/63836128-a522db80-c981-11e9-80ad-7e242e4c8ca5.gif)

**Comment by StanKryvenko** [comment]
Oh that's pretty fun bug

**Comment by SlayksWood** [comment]
when alligator die Tail always broken
![image](https://user-images.githubusercontent.com/45708377/64093504-50a4a500-cd61-11e9-879b-88d3587c48b5.png)

**Comment by StanKryvenko** [comment]
Check out last svn chages, added rigidbody on alligator

**Comment by SlayksWood** [comment]
Strange behavior of Alligator when another player kill them.
https://drive.google.com/file/d/1ZPBGyyEAKBm0xjRZo4jkfzYmPJNFRY2k/view?usp=sharing
