### ISSUE TITLE
Unity console cleanup: News exception

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12993]
Received this when starting the game

News response contains urlimage false which is not a valid url
UnityEngine.Debug:LogError(Object)
News.<>c__DisplayClass2_0:<SetNews>b__0(APINewsObject) (at Assets/UI/Scripts/News/NewsLoader.cs:43)
System.Collections.Generic.List`1:ForEach(Action`1)
News.<SetNews>d__2:MoveNext() (at Assets/UI/Scripts/News/NewsLoader.cs:38)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by gzatravkin** [comment]
Fixed
