### ISSUE TITLE
USER ISSUE: emess74

### ISSUE THREAD

**Issue by emess74** [StrangeLoopGames/EcoIssues#12995]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by emess74** [comment]
ok

**Comment by beastyn** [comment]
Did you buy the game?

**Comment by D3nnis3n** [comment]
The account named like your github account has not bought Eco. You can only play Eco when you buy it.
