### ISSUE TITLE
[master-preview] Capitol: Constitution articles feedback

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12999]
- [ ]  You can't just read the article. Every opening of the article will create new version of it. But I think players should have a way to read it.

- [ ] We need to fix UI for name editing
![bandicam 2019-08-29 17-03-06-939](https://user-images.githubusercontent.com/27898520/63938733-f49b0180-ca7e-11e9-888e-d5af297c3bde.jpg)

- [ ] I can't find the way to know which Amendment is connected to this Capitol and read its articles

- [ ] So, you can have only one active Capitol with ratified Constitution. But you can make only three articles. So, you MUST place Amend to create more articles?

**Comment by johnkslg** [comment]
1. You can mouse over it to read it, it describes it in the tooltip.  
2. Sergey is working on new UI for laws which will have fixed title.
3. All constitutional articles anywhere in the world are connected to the constitution. You can see everything in the goverment by clicking the government menu (the gavel in the action bar)
4. That's right.

**Comment by beastyn** [comment]
Then we should make everywhere linjs to the government. There is no mention of it anywhere in UIs.

**Comment by johnkslg** [comment]
I made some bugs for connecting ecopedia help to these things, and making a tutorial. Hopefully that will help cover it.

**Comment by johnkslg** [comment]
Can you reevaluate this now with new systems
