### ISSUE TITLE
Unity console cleanup: WWise warnings/errors in Unity

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12994]
Can you fix these to cleanup our console panel:

"DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
UnityEngine.Object:DontDestroyOnLoad(Object)
AkInitializer:Awake() (at Assets/Wwise/Deployment/Components/AkInitializer.cs:43)"

"There are menu items registered under Edit/Project Settings: Wwise Initialization Settings
Consider using [SettingsProvider] attribute to register in the Unified Settings Window.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()"

**Comment by kwazema** [comment]
I have the same problem, how did you solve it?

Thanks!
