### ISSUE TITLE
[master-preview] Crash when creating the law

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12998]
Step to reproduce:
- spawn goverment object (capitol and court)
- start to add new law
![image](https://user-images.githubusercontent.com/45708377/63937903-3a9a9a00-ca6c-11e9-9e4f-266ea79360a7.png)
- press all property and select all property
![image](https://user-images.githubusercontent.com/45708377/63937939-53a34b00-ca6c-11e9-9cf3-4429c8969a19.png)
- Crash
[Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3555389/Crash.txt)

**Comment by johnkslg** [comment]
Fixed! Thank you
