### ISSUE TITLE
Unity console cleanup: Unknown errors in Unity

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12990]
![image](https://user-images.githubusercontent.com/3536496/63882736-77409580-c987-11e9-91ce-6afa5ac02e81.png)

Some errors had a callstack:
Unknown error occurred while loading 'library/metadata/a8/a83f32161dad6d542b91e928fe64c840'.
UnityEngine.Material:GetTexture(Int32)
VoxelEngine.Materials.MaterialCombiner:GetTextureInfos(Material, IReadOnlyList`1) (at Assets/VoxelEngine/Materials/MaterialCombiner.cs:231)
VoxelEngine.Materials.MaterialCombiner:Add(MaterialInfo) (at Assets/VoxelEngine/Materials/MaterialCombiner.cs:136)
MaterialMapper:GetMappedMaterialInfo(Material, Boolean) (at Assets/Scripts/Utils/MaterialMapper.cs:53)
MapConfig:CreateBlockMapping(String[], UInt16[], IEnumerable`1) (at Assets/VoxelEngine/Core/MapConfig.cs:276)
VoxelEngine.Core.NetMapConfig:CreateBlockMapping(BSONObject) (at Assets/VoxelEngine/Core/NetMapConfig.cs:41)
RenderedChunkGrid:ReceiveInitialState(BSONObject) (at Assets/VoxelEngine/Core/MapConfig.cs:158)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:209)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at Assets/Scripts/Networking/NetworkManager.cs:526)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObject.cs:65)
Eco.Shared.Networking.NetworkClient:Update() (at C:/Eco/Server/Eco.Shared/Networking/NetworkClient.cs:299)
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:446)

Another one:
Unknown error occurred while loading 'library/metadata/a8/a83ad784dbb30c54ca3943d5d886bd1d'.
UnityEngine.Object:op_Equality(Object, Object)
ThreadSafeMeshCopy:GetCopyOf(GameObject, Matrix4x4) (at Assets/VoxelEngine/Core/ThreadSafeMeshCopy.cs:148)
MeshUsageCase:GenerateRotationCase(CustomBuilder, Matrix4x4&, Matrix4x4&) (at Assets/EcoModKitInternal/VoxelEngine/CustomBuilderInternal.cs:138)
MeshUsageCase:Build(CustomBuilder, Matrix4x4) (at Assets/EcoModKitInternal/VoxelEngine/CustomBuilderInternal.cs:112)
CustomBuilder:RebuildUsageCases() (at Assets/EcoModKitInternal/VoxelEngine/CustomBuilderInternal.cs:207)
CustomBuilder:Initialize() (at Assets/EcoModKitInternal/VoxelEngine/CustomBuilderInternal.cs:281)
CustomBuilder:Initialize() (at Assets/EcoModKitInternal/VoxelEngine/CustomBuilderInternal.cs:230)
MapConfig:CreateBlockMapping(String[], UInt16[], IEnumerable`1) (at Assets/VoxelEngine/Core/MapConfig.cs:306)
VoxelEngine.Core.NetMapConfig:CreateBlockMapping(BSONObject) (at Assets/VoxelEngine/Core/NetMapConfig.cs:41)
RenderedChunkGrid:ReceiveInitialState(BSONObject) (at Assets/VoxelEngine/Core/MapConfig.cs:158)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:209)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at Assets/Scripts/Networking/NetworkManager.cs:526)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObject.cs:65)
Eco.Shared.Networking.NetworkClient:Update() (at C:/Eco/Server/Eco.Shared/Networking/NetworkClient.cs:299)
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:446)

**Comment by mirasrael** [comment]
@johnkslg Do you still have this error?

**Comment by mirasrael** [comment]
Didn't see this error for long time. Seems fixed.
