### ISSUE TITLE
[0.8.3.0] Cannot select marker on screen

### ISSUE THREAD

**Issue by jthill** [StrangeLoopGames/EcoIssues#12997]
Tab to leave mouselook, click on marker arrow does not select marker in 0.8.3.0 Linux client, it does nothing but reenter mouselook mode.

**Comment by SlayksWood** [comment]
I really didn't know that it's possibly. Added to QA plan to check it.
8.2.9:
![image](https://user-images.githubusercontent.com/45708377/63934020-14243100-ca63-11e9-8fad-168a9d795971.png)
8.3.0:
![image](https://user-images.githubusercontent.com/45708377/63934155-61080780-ca63-11e9-8d40-76e19c40f1ab.png)

**Comment by SlayksWood** [comment]
merged to #16080
