### ISSUE TITLE
Unity console cleanup: Vivox errors when no mic found

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12991]
Shouldnt be an error, can you fix this to clean up our unity console

VivoxMediaVxa::VxaDeviceFactory::GetDefaultCaptureDevice(91)vxa_list_capture_devices->num_devices == 0
UnityEngine.Debug:LogError(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
SWIGLogHelper:Vx_Log_Event(vx_log_level, String, String)

**Comment by redwyre** [comment]
I need that vixox stuff in the log to be able to know what's going on if there's an error. At least until I can do a pass over current issues that people are having.

**Comment by redwyre** [comment]
Well, except the mic one.
There is a new SDK so I can try updating and see if they've changed it.
