### ISSUE TITLE
Slow FPS since update 8.3.0

### ISSUE THREAD

**Issue by Hexcodes** [StrangeLoopGames/EcoIssues#13002]
Before the update eco was playable for me, but after the update to 8.3.0 I don't get any FPS over 15 and everything seems to be very laggy...

GPU: nvidia Gefore GTX 1060 with 6GB RAM
CPU: Intel Core i7 7700HQ

Game is running on dedicated GPU not on the internal... 
Even setting every setting down (except from resolution 3840x1600) doesn't change a lot (except from rendering scale)

**Comment by mirasrael** [comment]
Hi @Hexcodes 
Currently game doesn't work good with big resolutions. Did you use same resolution before 8.2.9?

**Comment by Hexcodes** [comment]
Yep - I mean I had low fps before, but now it's even worse.

**Comment by Hexcodes** [comment]
Forget it... the old driver was the issue -> new driver 50fps now :P

**Comment by mirasrael** [comment]
@Hexcodes Glad to know you're fine!
