### ISSUE TITLE
[master-preview] Civics: drafts for every draftable object shouldn't...

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13003]
.. be visible in dropdowns. I can be in process of creating Election Title  and see this draft in Titles.
![bandicam 2019-08-29 17-53-36-969](https://user-images.githubusercontent.com/27898520/63941889-f7e5bb80-ca85-11e9-8835-c2650cd144c4.jpg)

**Comment by johnkslg** [comment]
That's by design, so you could have an election process and an elected title in election at the same time.  

If you specify a draft, whatever is pointing to it will be invalid until if/when the draft changes to active.
