### ISSUE TITLE
[master-preview] Constitution Room max Value

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13004]
The value of Constitution's Room include only one room where Capitol places.  Without "Towns and Nations" You need to build room with 27 house value and nobody can ratify new constitution, because Max Room value = 40. 
Maybe we need to include all room at same property or maybe district?
![image](https://user-images.githubusercontent.com/45708377/63944589-7b99ab00-ca7a-11e9-9ab7-1c2824025d4e.png)

**Comment by johnkslg** [comment]
Added bug here: https://github.com/StrangeLoopGames/EcoIssues/issues/13016
