### ISSUE TITLE
Civics: Improve 'Civic Duties'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13009]
I would like to change all civics objects to have text and tooltips explaining what things are, how they work, and why you can or can't do them. 
![image](https://user-images.githubusercontent.com/3536496/63981076-78022600-ca72-11e9-83ee-d4eaea89102d.png)

There are several objects that allow you to perform civicactions, these objects should have code added that gives you more details on what you can do.   In the image above for example:
- Each option should be greyed out if its unavailable.  
- Tooltip should describe why its available or unavailable

This can be created by creating a new array on CivicDuties that maintains details about each civic action, rebuilding them when needed (as CivicDuties currently are) and syncing them to the client. Then, in the Civic Actions Component UI, you can add code that looks at the civic duty for each button type and enables/disables it as needed and sets the tooltip.

Details about how each civic action's availability is determined for a user:

**Vote**
- Must be an active election they are classified as a 'voter' in

**Veto**
- Must be an active election they are classified as a 'vetoer' in.

**StartElection**
- There must exist an elected title that can have an election started (paying attention to term limits and delays between elections) and on which the player is included as being able to start the election.

**EnterElection**
- Must be an active election which the player is eligible as a candidate.

**WithdrawFromElection**
- Player must be a candidate in an active election.

**ExecutiveAction**
- Player must have rights granted by a constitutional article given executive action rights, or be listed as someone who can propose an election for an executive action.

**ResignFromOffice**
- Must be an occupant of an elected title.

**RemoveFromOffice**  
- Must be listed as able to remove from office on an elected title, and that elected title must have an occupant. 

The tooltips explaining why you can/cant do something need to be very detailed, listing via UILinks the various objects that dictate the rules affecting it (same as how the other civic duty descriptions are calculated).

**Comment by beastyn** [comment]
We will revisit it if something feek off
