### ISSUE TITLE
No biome textures on world map.

### ISSUE THREAD

**Issue by Tom212** [StrangeLoopGames/EcoIssues#13008]
Context:

We're hosting a server through GTX-Gaming. When trying to run the server and generate a world, server-log would report this error and continuously retry this step: 

`Newtonsoft.Json.JsonSerializationException: Could not find type 'Eco.WorldGenerator.SimpleTerrainModule' in assembly 'Eco.WorldGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)`

I found this post on the steam discussions: https://steamcommunity.com/app/382310/discussions/4/1778262124936935789/

As a result of these findings, I deleted the WorldGenerator.eco file from the server config folder and uploaded one taken from my client-side Eco Server build. 

Following this, the error disappeared, and a world was generated. But upon entering the server it was clear something was wrong, the world map was showing all biomes as having a white texture with the exception of sand.

Map overlays seemed to work for plants and animals, however biomes showed no results. We tried rebuilding the world twice with no avail and tried running the server for at least 15-20 mins to see if it would go away.

An image of this bug is attached.

Hope someone can shed some light on this, thank you for your time.

Tom

![20190829222341_1](https://user-images.githubusercontent.com/11068373/63980336-2a59dd80-cab3-11e9-8a48-2bc477051567.jpg)

**Comment by Tom212** [comment]
Turns out I was wrong. There isn't a lack of textures, but rather the white texture represents the tundra biome. The entire map has the same tundra ground texture, even though there are distinct biomes separated by types of trees etc. For some reason, during world generation its applying one layer to all biomes.

**Comment by D3nnis3n** [comment]
Try removing EcoSim.eco. If that doesn't work please completely reinstall your eco server installation, it seems like your server files are corrupted.
