### ISSUE TITLE
[master-preview] Amendments: feedback

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13001]
- [ ] There is no way to choose with wich capitol (constitution?) this item should be connected.
Id it work somehow by default?

- [ ] It seems like anyone can place an Amend and create articles for active Capitol. Is it right?

**Comment by johnkslg** [comment]
Theres only one constitution, the active one, right now.  Later there will be multiple.

On that constitution you can set ConstitutionalArticles that controls who can change ConstitutionalArticles.

I agree its dangerous though, so I added this issue to make constitutions require elections for all government actions by default. https://github.com/StrangeLoopGames/EcoIssues/issues/13012

**Comment by beastyn** [comment]
So, How will it work:
Someone place Capitol, I place Amend. My articles are working for that Capitol's constitution. (my articles where elected).
Another person make new capitol in the room with greater value and Ratify it. My Amend shouldn't work for this capitol from now on? I should place the new one?

**Comment by johnkslg** [comment]
When a constitution is overthrown, everything in the government should get disabled, pushed back to 'draft'.  Do you see this happening?

**Comment by johnkslg** [comment]
I've redone how this works, let me know if this bug still applies.
