### ISSUE TITLE
/datasets/get not working in swagger

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1300]
When using the query /datasets/get in swagger
With this dataset: Animal/Population/Hare
Also tried: Animal%2FPopulation%2FHare

Get this error in VS: https://gyazo.com/c98f37298994bfd34b6484bee9789389

And this response in swagger:
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Value cannot be null.\r\nParameter name: source",
  "ExceptionType": "System.ArgumentNullException",
  "StackTrace": "   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Eco.Stats.StatInfoTree.Get(String[] key)\r\n   at Eco.Stats.SimStats.HasStat(String[] key)\r\n   at Eco.Stats.SimStats.GetStatData(String[] keyName)\r\n   at Eco.Webserver.Web.Controllers.StatsController.GetDatasetValues(String[] key, Double startDay, Double endDay)\r\n   at Eco.Webserver.Web.Controllers.StatsController.Get(String[] dataset, Double time_start, Double time_end)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by MarjieAVolk** [comment]
Seems likely you are not formatting it correctly.  The correct format for the dataset field is now:
["Animal", "Population", "Hare"]

If you aren't sure what key to use anymore, you can reference dataset/flatlist; use the values of the "Key" fields as dataset keys everywhere.
