### ISSUE TITLE
Trying to "continue" on a server that is not updated to the most recent version does not give an informative error message about that

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13010]
Either have the error say it is incompatible version or show it before even pressing continue.

**Comment by SlayksWood** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/4933
![unknown](https://user-images.githubusercontent.com/45708377/64019692-86b31080-cb38-11e9-9f7e-9330e844ead5.png)
