### ISSUE TITLE
"Ask and expert to craft..." missing related skills

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#1301]
always says no related skills (on slg server)

**Comment by MarjieAVolk** [comment]
It only shows efficiency skills there; all users shown in the list have any skills required to craft the item.  Is that what you're seeing?  It is a bit confusing.  Maybe it should say "no efficiency skills"

**Comment by craig-jong** [comment]
I have the efficiency skills, they just weren't showing up in the tooltip

**Comment by MarjieAVolk** [comment]
Okay; which items was this happening with?  I've definitely seen it working on the slg server in some cases too.
