### ISSUE TITLE
[master-preview] Civics: Laws feedback

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13023]
1. We've lost a bunch of stuff for creating laws. For example
   - we can't make periodic laws (call in time, not by action), like this one  
https://eco.gamepedia.com/File:Citizen_Wage_and_Wealth_Tax.png

   - we can't make pretty simple law with checking crafting stuff
![unknown (7)](https://user-images.githubusercontent.com/27898520/64034801-cabe0980-cb68-11e9-9227-c318a5eeff94.png)

How this one should work? I want to check the item which I attend to craft.  
![bandicam 2019-08-30 21-00-10-855](https://user-images.githubusercontent.com/27898520/64035045-3902cc00-cb69-11e9-8b51-d2e82dba37a9.jpg)

- I can't find actions like:

Claim Deed
Unclaim Deed - its actually different actions
Harvest
Harvest Leaves
Offer contract (we won't have them in 9.0?)
Place
Pickup (they should be in different actions)

- Sometimes law have different effect for different conditions.

if (condition 1)
then effect 1
else if (condition 2)
then effect 2
else effect 3

Like here
https://eco.gamepedia.com/File:Abandonment_Tax_Inactivity_Demographics.png

Or should i make different law?

- I'm not quite get what is Categories in Conditions.

![bandicam 2019-08-30 21-12-14-792](https://user-images.githubusercontent.com/27898520/64035734-f80bb700-cb6a-11e9-8a87-91cb02b016f5.jpg)

2. Conditions UI should be reworked as its really hard to understand that firstly you should place LOGIC operator and then you should fill left and right part (what is left and right part for average person?)
![bandicam 2019-08-30 21-10-18-635](https://user-images.githubusercontent.com/27898520/64035590-9e0af180-cb6a-11e9-84b3-450f6c38f38d.jpg)

Its just some basic stuff and we can dig deeper only after resolving these ones.

**Comment by johnkslg** [comment]
Added periodic executive actions which handles the first point:
https://github.com/StrangeLoopGames/Eco/pull/4952

**Comment by beastyn** [comment]
I will close it for now as we are in duscussion mode.(in googleDoc)
