### ISSUE TITLE
[Client Bug] Constant Disconnects from hosted Game 

### ISSUE THREAD

**Issue by QuimiQ** [StrangeLoopGames/EcoIssues#13027]
Windows 10 Version: 0.8.3.0 beta
My friend is hosting a game on his PC with the option for his friends to join. We are 4 people playing on this server (including him). Me and one other friend are having a problem that we lose connection constantly. After about 10 minutes of playing we get disconnected. We can reconnect immediately and continue playing but after another 10 minutes or so, we both lose connection again.

Since it's a connection issue I've tried to look at my firewall (none of us are in the same LAN) and noticed that at the exact moment I lose connection some UDP packages from my friends IP get forwarded through my firewall (see screenshot). The IP 192.168.4.112 is not pingable in my network. No idea what that's supposed to be.

I have played this game for 18 hours now and I'm sick of having to logon every 10 minutes. I've also spent a good ammount of googling and there is not really a lot of useful information.

![Firewall](https://user-images.githubusercontent.com/12738450/64047610-91d56300-cb6f-11e9-9002-ac0b027fbfac.png)
[ErrorLog.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3561287/ErrorLog.txt)

**Comment by mirasrael** [comment]
Hi @QuimiQ 
Sorry for long answer. Was you able to solve your issue?

**Comment by QuimiQ** [comment]
No, the problem still persists.

**Comment by mirasrael** [comment]
Seems like a bug in UDP library. In 9.0 we switched to another UPD library so hopefully it will fix your problem. We can provide you access to development version of 9.0. It is completely unplayable in it's current state, but you can check if it fixes your networking problem.

**Comment by mirasrael** [comment]
@QuimiQ I didn't get answer for you. Did you solve your issue or do you wanna to test 9.0 version? (it is now much more playable)

**Comment by mirasrael** [comment]
Closed due to no response for long time.
