### ISSUE TITLE
[8.3.0 Linux server] `install.sh` tries to install wrong package dependencies on arch

### ISSUE THREAD

**Issue by jthill** [StrangeLoopGames/EcoIssues#13026]
I'm responding to the header comment in `Eco_Data/Server/install.sh`:

```sh
# While the linux build of Eco Server is unsupported, please report any 
# issues to https://github.com/StrangeLoopGames/EcoIssues/issues
```

On arch, the dependencies are wrong, I think the package names should be `mono aspnet-runtime libcanberra`.  btw, there's no need to demand root if the dependencies are already there, 

```
    needed=`pacman -T mono aspnet-runtime libcanberra` || pacman -S --noconfirm $needed
```

will do the check without needing root, and complain about needing root itself if necessary.

While I'm picking nits, you don't have to grep & awk through os-release.  Hm.  Here's a first-draft that doesn't alter the behavior on other os's

```
#!/bin/bash
# Install prerequisites for Eco Server on Linux

# While the linux build of Eco Server is unsupported, please report any 
# issues to https://github.com/StrangeLoopGames/EcoIssues/issues

check_root() {
	if [[ $EUID -ne 0 ]]; then
		echo "This script must be run as root"
		exit 1
	fi
}

test -r /etc/os-release && . /etc/os-release || . /usr/lib/os-release

case $ID in
ubuntu | debian | raspbian)
  check_root
  apt -y install mono-complete libcanberra-gtk-module
  ;;

centos | rhel)
  check_root
  yum -y install mono-complete libcanberra-gtk-module
  ;;

fedora)
  check_root
  dnf -y install mono-complete libcanberra-gtk-module
  ;;

arch)
  needed=`pacman -T mono aspnet-runtime libcanberra` || {
	  check_root &&
	  pacman --noconfirm -S $needed
  }
  ;;

*)
  echo "Unable to determine your operating system type."
  echo "You can try to install the following packages manually"
  echo " * mono-complete"
  echo " * libcanberra-gtk-module"
  exit 1
  ;;
esac
```

**Comment by redwyre** [comment]
> I'm responding to the header comment in `Eco_Data/Server/install.sh`:
> 
> ```shell
> # While the linux build of Eco Server is unsupported, please report any 
> # issues to https://github.com/StrangeLoopGames/EcoIssues/issues
> ```
Thanks!

> On arch, the dependencies are wrong, I think the package names should be `mono aspnet-runtime libcanberra`. btw, there's no need to demand root if the dependencies are already there,

* mono looks like it contains everything on arch
* aspnet-runtime isn't relevant (we're not using .net core yet)
* also looks like on arch libcanberra contains libcanberra-gtk-module so that should be good.

Are you able the run the server now?

> ```
>     needed=`pacman -T mono aspnet-runtime libcanberra` || pacman -S --noconfirm $needed
> ```
> 
> will do the check without needing root, and complain about needing root itself if necessary.
> 
> While I'm picking nits, you don't have to grep & awk through os-release. Hm. Here's a first-draft that doesn't alter the behavior on other os's
> 
I appreciate the effort, but I am trying to keep this file as simple as possible (it's a low priority) so you can just type sudo before it ;)
Also os-release looked like the most reliable method to get the OS name across the different architectures and shells. If you can point me to some docs that shows this isn't the case I'll have a look.

**Comment by jthill** [comment]
The server runs fine.   `os-release` has its own manpage, it's defined to be shell-compatible assignments so you can just source it and use the results rather than oneliner-ing a lexer.  Say `man os-release`, it says how to properly deal with the file. I didn't know `/usr/lib/os-release` was the template/default for it until I read that page myself today.  Different shells isn't a problem, you've got `#!/bin/bash` up front so that's the shell.

**Comment by redwyre** [comment]
I've read arguments against sourcing it, so better safe than sorry.

`mono` is a .net framework runtime which runs the server.  `dotnet-runtime` is for .net core which we aren't using atm.

should be just `pacman -S --needed --noconfirm mono libcanberra`

**Comment by redwyre** [comment]
Updated in 9.0
