### ISSUE TITLE
Inventory breaks and rejects new contents, saying it's full, when there is nothing in the carried inventory.  [master branch/9.0]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13028]
![image](https://user-images.githubusercontent.com/14983165/64051151-063be200-cb2f-11e9-9268-9dfd2dda9995.png)
Often times I'll give myself a block, place it down, then try to give myself another and it will say my inventory is full.

The only way to fix it that I've found is using /dump then giving myself the item again.

**Comment by beastyn** [comment]
duplicate #12942
