### ISSUE TITLE
USER ISSUE: Can't move cart with elevator

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#13031]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
place an elevator. place a cart in the elevator

**Expected behavior:**
the vehicle should stay in the elevator

**Actual behavior:**
the vehicle moves slowly in the elevator, and it can even fall from it

**Do you have mods installed? Does issue happen when no mods are installed?:**
the vehicle moves in the elevator, and it can even fall from it

**Comment by WeaselDog** [comment]
Related to this: https://github.com/StrangeLoopGames/EcoIssues/issues/9391

**Comment by beastyn** [comment]
So,I think we want to move a cart in an elevator. Should we work with models?
Should we add some new elevator types?
https://github.com/StrangeLoopGames/EcoSuggestions/issues/557

**Comment by keegan-o** [comment]
A new larger elevator will be added with 9.1, so this old one can be used with small carts and regular carts (I was able to use it with a regular cart, but it's not easy I agree) and for just people.
