### ISSUE TITLE
[master-preview] Fearless wolves

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13038]
My riding wolf (they don't fear from people at all):
![2019 09 02 Fearless wolves](https://user-images.githubusercontent.com/45708377/64093907-af1e5300-cd62-11e9-847a-3479213bfe80.gif)
Wolf runs a very short distance after reacting to arrow
![2019 09 02 Wolf runs a very short distance after reacting to arrow](https://user-images.githubusercontent.com/45708377/64094163-88ace780-cd63-11e9-97cf-962188ad27e4.gif)
:

**Comment by StanKryvenko** [comment]
This was disabled until next PR, not a bug.
It was discussed on Friday
