### ISSUE TITLE
[master-preview] Animal's strange behavior in water

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13037]
When the Alligator falls into the water, then after a while it begins to constantly attack the void
![2019 02 09 Alligator's strange behavior in water](https://user-images.githubusercontent.com/45708377/64092471-9bbcb900-cd5d-11e9-9bb3-36e8444a2680.gif)

**Comment by SlayksWood** [comment]
It seems like all water animal (Tuna, Otter, Trout, Salmon) have strange behavior  in water.

**Comment by beastyn** [comment]
Alligators seems to be better. but some fish can be cranky
https://drive.google.com/file/d/1vFYKOr43hx5vVevqWi8Gj6d6JOo8hOJ-/view?usp=sharing
