### ISSUE TITLE
Commenting on election errors

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1303]
**From in game,** 
trying to comment on Election (user is from /generatetestdata/ query)
I get this error: https://gyazo.com/9b4a3cf45cd4ea7ad16df19aa75d681b

**When using swagger,** 
I'm not sure the proper formatting for the data parameter.

I tried this parameter format:
`{
  "Username": "Test User 2",
  "Text": "testsetsetsetsetse"
}`

Which gets this CS error: https://gyazo.com/49dbb6aac2a93974d3ab1d618b0a6f97
And this query response:
`{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Object reference not set to an instance of an object.",
  "ExceptionType": "System.NullReferenceException",
  "StackTrace": "   at Eco.Gameplay.ChatManager.SendChat(String text, User user, Graph graph, Map map)\r\n   at Eco.Gameplay.VotingItem.AddComment(String text, User user, Graph graph, Map map)\r\n   at Eco.Webserver.Web.Controllers.VotingHelper.AddComment(VotingItem item, ChatMessage commentData, String username, String authtoken)\r\n   at Eco.Webserver.Web.Controllers.ElectionController.AddComment(ChatMessage comment, String username, String authtoken)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}`

I tried this parameter format:
`{
  "Username": "Test User 2",
  "Text": "testsetsetsetsetse",
  "Graph": {
  },
  "Map": {
},
  "Timestamp": 1,
  "Tag": "test"
}`

Which gives this VS error:
https://gyazo.com/a65586aa51e699543a55d09c9915c24f
And this query response:
`{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Object reference not set to an instance of an object.",
  "ExceptionType": "System.NullReferenceException",
  "StackTrace": "   at Eco.Webserver.DataTransferObjects.Map.Convert()\r\n   at Eco.Webserver.Web.Controllers.VotingHelper.AddComment(VotingItem item, ChatMessage commentData, String username, String authtoken)\r\n   at Eco.Webserver.Web.Controllers.ElectionController.AddComment(ChatMessage comment, String username, String authtoken)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}`

Then I tried this parameter format:
`{
  "Username": "Test User 2",
  "Text": "testsetsetsetsetse",
  "Graph": {
  },
  "Map": {
    "WorldLayer": "string",
    "Frame": 0,
    "TimeStartSeconds": 0,
    "TimeEndSeconds": 1,
    "PlaySpeed": 0,
    "CurrentTimeSeconds": 0,
    "Flat": true,
    "Pause": true,
    "CameraPosition": "{"x":0,"y":11157.894727837833,"z":17.98875885459532}"
  },
  "Timestamp": 1,
  "Tag": "test"
}`

Gets no VS error, and the query gives this response:
`{
  "Message": "Missing comment or comment malformed."
}`

**Comment by MarjieAVolk** [comment]
K I put a bandaid on this

**Comment by rainfarmer** [comment]
Thanks for the bandaid.
There is another bug now:

Posting comment on current election gives this error:
https://gyazo.com/a36442a75f407ec1dfbf535e0ccda9ff

Since it seemed to be breaking on the world layer selection, I tried including a map with a layer selected, which gave this error:
https://gyazo.com/82ff7d41cba19660b2fe046806ce1728

**Comment by rainfarmer** [comment]
Also getting that layer selection error, for various other actions.
For example, using GET /api/v1/elections/previous causes it
