### ISSUE TITLE
[master-preview] Chat:  help is in the right container

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13039]
When I write /help (and everything related to the chat commands) it should be in the main chat window. Now they are in the right container which has a really small font-size.
![bandicam 2019-09-02 11-38-36-479](https://user-images.githubusercontent.com/27898520/64094797-4c36b700-cd76-11e9-9d5e-9b2a0f2739c6.jpg)

**Comment by gzatravkin** [comment]
Fixed
