### ISSUE TITLE
Farming skill

### ISSUE THREAD

**Issue by SolaceAdenya** [StrangeLoopGames/EcoIssues#13030]
My husband is not receiving skill ups for his specialized farming skill when using a hoe despite tool tip saying using the hoe should grant them. Also wondering if he should've received an iron hoe when he specialized farming like the other tool-related skills do.

Thanks!

**Comment by Quadbro** [comment]
just need to add some tech tree changes, and all the code will autogenerate needed item gains

**Comment by Quadbro** [comment]
Added exp gain to all hoes, configurable through eco tech tree

**Comment by beastyn** [comment]
Can you check a trigger for exp gain without profession?
If you are plowing without profession it should show it like that
![unknown (48)](https://user-images.githubusercontent.com/27898520/73428045-ed439100-4359-11ea-846e-ea030d8a0318.png)

**Comment by Quadbro** [comment]
yeah, makes sence, acced

**Comment by johnkslg** [comment]
Thanks @SolaceAdenya this finally got fixed!

**Comment by SlayksWood** [comment]
Icon appeared, but if you click on it then Skill UI should open. But now nothing happens.
For example Mining:
![image](https://user-images.githubusercontent.com/45708377/74005117-f26f9400-4988-11ea-92df-d74431053ddc.png)
Skills UI open and have red notidication

It works if you gain exp:
![image](https://user-images.githubusercontent.com/45708377/74005210-34003f00-4989-11ea-914f-9011b359c088.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/79328356-9132e680-7f1e-11ea-8716-c2279cc0cf3a.png)
