### ISSUE TITLE
Butchery table running out of resources mid-production

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#13043]
I've seen this issue a few times - I'd run the Butchery Table at high skill, queue up a good amount of carcasses to be processed (all that I had, making say, a run of 35 out of 7 carcasses), and then towards the end of the job, the table would say it's missing resources, despite having everything it needed when the job started. Haven't seen this happen to other crafting stations.

**Comment by SlayksWood** [comment]
I do not know if this will be actual in 9.0.
If not, please close

**Comment by craig-jong** [comment]
I can't get this to reproduce in 9.0

Reopen it if it happens.
