### ISSUE TITLE
[0.8.3.0] Admin command "/levelup cooking" broken again 

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#13042]
Game Version - 0.8.3.0
Skills - Cooking and Advanced Campfire Cooking

If the admin enters the chat command "/levelup Cooking" instead of increasing the Cooking skill, the Advanced Campfire Cooking skill goes up. Which leads to the impossibility of raising the "Cooking" skill by this command (if the specified skill was previously pumped to any level, then after entering the specified command it decreases to level 2 and it is necessary to pump it again).

Screenshots of the problem are attached. For denostration, cooking and Electric skills were used.
![Cooking_Skill_after](https://user-images.githubusercontent.com/1098421/64127444-61353980-cdba-11e9-9897-4dfa83b2f8fe.jpg)
![Cooking_Skill_before](https://user-images.githubusercontent.com/1098421/64127445-61353980-cdba-11e9-899f-a4e1dc3e40a1.jpg)
![Electronic_ Skill_ before](https://user-images.githubusercontent.com/1098421/64127446-61cdd000-cdba-11e9-9cfb-ec42736c9a2c.jpg)
![Electronic_Skill_after](https://user-images.githubusercontent.com/1098421/64127447-61cdd000-cdba-11e9-9c43-ce2346b165d6.jpg)

**Comment by SlayksWood** [comment]
It will fixed in 9.0
