### ISSUE TITLE
USER ISSUE: Can't Connect

### ISSUE THREAD

**Issue by Zenathillia** [StrangeLoopGames/EcoIssues#13045]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
1. host server on this PC
2. Try to connect
3. see it on list
4. unable to connect

**Expected behavior:**
connected or at least let me choose join

**Actual behavior:**
greyed out no option to connect

**Do you have mods installed? Does issue happen when no mods are installed?:**
greyed out no option to connect

**Comment by mirasrael** [comment]
Can you post screenshot? Do you have same version of server and client?

**Comment by Zenathillia** [comment]
Launched it using steam and the issue was resolved thanks anyway
