### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by GrilleGustav** [StrangeLoopGames/EcoIssues#13044]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Grow Hackleberrys.

**Expected behavior:**
See blue berries

**Actual behavior:**
Didn't see blue berrys

**Do you have mods installed? Does issue happen when no mods are installed?:**
Didn't see blue berrys

**Comment by SlayksWood** [comment]
dup #12618
