### ISSUE TITLE
A host of bugs in 5.5.2 stable

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1304]
i think the release of 5.5.2 stable might have been a tiny bit premature, Launched it in our test server to get quite a shock lol
![image](https://cloud.githubusercontent.com/assets/26527110/24547542/452d942e-1608-11e7-829d-95f84a208d9e.png)

Water pump, ice melter, storage tank, steam generator and depot are both "the matrix" style cube, 
The pumpjack is turned 90 degrees onto its side,
computer Lab has no impact, you walk straight through it,
pretty exhausted right now but i'll let you know if i find more :)

**Comment by Neouni** [comment]
5.5.4
New placeholders for Waterpump, icemelter, steamgenerator, depot

pumpjack and computerlab seem fine

**Comment by craig-jong** [comment]
The placeholders shouldn't be an issue - although power itself needs a good look at.
