### ISSUE TITLE
USER ISSUE: cant connect to server

### ISSUE THREAD

**Issue by alt2035** [StrangeLoopGames/EcoIssues#13041]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
try to log on

**Expected behavior:**
log in

**Actual behavior:**
fails to connect. server is hosted and paid to date

**Do you have mods installed? Does issue happen when no mods are installed?:**
fails to connect. server is hosted and paid to date

**Comment by SlayksWood** [comment]
@alt2035 
1. Are you trying to connect to specific server or having this issue with every server? Could you tell the name of the server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the "latest build" or you had it before?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
