### ISSUE TITLE
Store tells you YOUR inventory is full when the STORE'S inventory is full D:

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#1305]
An easy (I'd hope?) bug for someone's list on this fine Bug Friday. 

YOUR INVENTORY IS FULL

YOUR INVENTORY IS FULL!!!!!!!

**Comment by johnkslg** [comment]
Are you adding trade offers, stock, or to the public storage?

**Comment by MarjieAVolk** [comment]
Not seeing this one anymore
