### ISSUE TITLE
Objective window causing complete game crash

### ISSUE THREAD

**Issue by Belgareth1987** [StrangeLoopGames/EcoIssues#13059]
Whenever i attempt to resize the objective window it immediately causes a complete crash back to windows.

**Comment by D3nnis3n** [comment]
Hello,
please provide us with the logs directly after the crash happened: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Belgareth1987** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3582743/Player-prev.log)

**Comment by Belgareth1987** [comment]
There ya go

**Comment by SlayksWood** [comment]
it should be fixed in 0.8.3.2.

**Comment by D3nnis3n** [comment]
Nope, just recently had new issues with that and am waiting on dump files.
