### ISSUE TITLE
[0.8.3.0] First election when it's just you used to complete immediately, now it's 24h wait

### ISSUE THREAD

**Issue by jthill** [StrangeLoopGames/EcoIssues#13052]
Fire up a new server and sign in as the only user to set things up, in 0.8.2.9 you could delete the sample citizenship law, elect yourself leader and go about your business.  Now you have to wait 24 hours, which, it seems to me, benefits exactly nobody and substantially inconveniences the people setting up a server.

**Comment by SlayksWood** [comment]
I can delete citizienship law with non-dev account. In any cause to become citizienship you need to play near 2 hours.
![image](https://user-images.githubusercontent.com/45708377/64235112-58e71680-cf00-11e9-91be-4a9ec0822b25.png)
![image](https://user-images.githubusercontent.com/45708377/64235175-79af6c00-cf00-11e9-850e-cdb26f6cb8e5.png)

This issue will not actual with new civics system in 0.9.0.0. I close it and merge with same issue #12663

**Comment by jthill** [comment]
The problem isn't the deleting the citizenship law, the problem is the delay before the election completes.  It used to happen as soon as you voted.  Now it takes hours.

**Comment by redwyre** [comment]
@jthill as an admin you can use /passlaws to immediately pass laws

**Comment by redwyre** [comment]
Or /leader to set the world leader directly
