### ISSUE TITLE
8.3.0, no stats on webinterface

### ISSUE THREAD

**Issue by BurtGummer** [StrangeLoopGames/EcoIssues#13054]
Hello,

I'v run a 8.3.0 Eco server under Debian 10 with Mono 6.0.0.327. The server was installed with steamcmd and if i click on any stats, there are only "Load":

![image](https://user-images.githubusercontent.com/1249295/64311062-f1ce6e00-cfa2-11e9-9135-ef2244f1776e.png)

If I reload the side and click a user who played a lot:

![image](https://user-images.githubusercontent.com/1249295/64311138-36f2a000-cfa3-11e9-923c-8867b57fb9ac.png)

There are no errors in my log (only remove backup).

I have try it with Google Chrome and Vivaldi, I have also clear my cache complete.

Any ideas?

**Comment by jthill** [comment]
Does not happen for me on Arch with an install from the website, `mono EcoServer.exe` from the command line, mono version 6.0.0, everything shows up properly.

**Comment by BurtGummer** [comment]
OK, interesting, just the per-user-stats are empty. If i klick on "Voreingestellte Gr...":

![image](https://user-images.githubusercontent.com/1249295/64510663-ff596000-d2e2-11e9-832a-fb4937efa307.png)

I have stats. I have also copy the stats.eco.templete to stats.eco.

**Comment by beastyn** [comment]
Should be fixed  in 8.3.1 and 0.9
