### ISSUE TITLE
[master-preview] No shadow placement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13069]
Take some logs and try to place them down. You won't see shadow placement.
 
![bandicam 2019-09-09 11-40-34-395](https://user-images.githubusercontent.com/27898520/64508723-8d3f4600-d2f7-11e9-89ed-a1ed2471aa63.jpg)

**Comment by redwyre** [comment]
Is this still a problem?

**Comment by beastyn** [comment]
seems fine
