### ISSUE TITLE
Can't access AccountLevel while player is logged out

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1306]
On the teacher tools branch, it's now possible for users to chat via the web interface, and thus chat without being logged in.  ChatManager sets the icon for a chat message via the AccountLevel field on INetClient, which can't be accessed while a user is logged out.

**Comment by metachronism** [comment]
we dont really have a way to handle this, unless you want to store the account level in the user.  But that value is always going to be out of date with the master accounts system
