### ISSUE TITLE
[9.0.0-master] Some of the new objects are not linked in chat.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13060]
![chatlinking](https://user-images.githubusercontent.com/25908592/64386521-a1eeb600-d039-11e9-8b0a-95419f03df33.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/75315619-40830380-5874-11ea-9c0f-3921a1d56340.png)
