### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by matheuslarcher20** [StrangeLoopGames/EcoIssues#13066]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

You have been banned from this server
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

You have been banned from this server
```

**Comment by SlayksWood** [comment]
"You have been banned from this server"
Contact the server administration to unban you.
