### ISSUE TITLE
[master-preview] Recipes display in crafting table

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13070]
When you open the crafting table for the first time, very little count of recipes are displayed:
![image](https://user-images.githubusercontent.com/45708377/64509723-02574f00-d2e9-11e9-93e7-d857a2be19f0.png)
After reopen it will be display more. And if you constantly reopen crafting table, then in the end you can get all the recipes. First reopen:
![image](https://user-images.githubusercontent.com/45708377/64509732-05523f80-d2e9-11e9-9c06-d530eb9403e1.png)
second:
![image](https://user-images.githubusercontent.com/45708377/64509736-084d3000-d2e9-11e9-9775-ed267a640e1e.png)
third:
![image](https://user-images.githubusercontent.com/45708377/64509740-0be0b700-d2e9-11e9-8a09-c62f2096dad5.png)

**Comment by redwyre** [comment]
This happens when something throws while populating the list, eg the ones with messed up text. I thought this problem was fixed though...

**Comment by SlayksWood** [comment]
I didn't observe this problem in the latest builds. Seems fixed.
