### ISSUE TITLE
[master-preview] Can't do contract at another's property 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13072]
Step to reproduce:
- take contract
![image](https://user-images.githubusercontent.com/45708377/64528936-5aef1200-d312-11e9-9a31-2ca7d3b3185b.png)
- try to do it. You can't because you haven't autorized to this Deed. But Highlighting is green
![image](https://user-images.githubusercontent.com/45708377/64528915-4b6fc900-d312-11e9-80f1-c493eb479118.png)

**Comment by SlayksWood** [comment]
I assume that something is wrong with authorization.
For example another contract: Build Room. I try to build room. All time I have notifixation you are not authorizwd to that property. But blocks appeares. But after reload my building will dissapear.

**Comment by beastyn** [comment]
and distribution station has the same problem. You can't take things from the claimed station. And you should be able to
