### ISSUE TITLE
Tooltip for crafting ingredients should describe more details

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13079]
![image](https://user-images.githubusercontent.com/3536496/64567303-cc2bc680-d30c-11e9-885e-2c7d07c49e8c.png)
Should tell me:
- The fact that this is a needed ingredient in which recipe
- What does 10/2 refer to? 
- Text explaining something along the lines of 'Any Item tagged 'Log' is accepted in this recipe.  Items with Log tag:'

**Comment by beastyn** [comment]
Still no count explanation and child recipes unformation

**Comment by SlayksWood** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/45708377/75238666-72438e00-57d2-11ea-9a8e-c067d4968bff.png)
