### ISSUE TITLE
Carried Slot Gone / Un-reliable (master 9.0)

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13075]
While carrying logs for instance, no carried slot UI appears and thus it is not possible to drag into stockpiles or know for sure what you're carrying.

![image](https://user-images.githubusercontent.com/14983165/64557656-e22e8c80-d2f6-11e9-9f22-215090ebff30.png)

The carried slot appears while dragging items from a stockpile, but does not reliably stay around as you switch between hammer and no hammer, often meaning you don't know how many you're carrying.

**Comment by beastyn** [comment]
dup #13068
