### ISSUE TITLE
Eco spams appdata/Local/Temp with countless files and folders and no cleanup

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#13073]
I have put two of the files in this zip-archive, they originate from eco.
[scrap.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3590455/scrap.zip)

Meanwhile the Temp folder contains 4880 files and uses 324 MB, I don’t know how to clean that.
Here’s a short list from the Temp folder:
![temp1](https://user-images.githubusercontent.com/38510829/64530983-b28b7e80-d30e-11e9-8ec8-e982448cc94b.jpg)
![temp2](https://user-images.githubusercontent.com/38510829/64530992-b8815f80-d30e-11e9-82c5-2f30eb3e2008.jpg)

**Comment by mirasrael** [comment]
Hi @Nicolausi113. Which version of Eco are you using? In log it says 7.7.2

**Comment by Nicolausi113** [comment]
I used last days v7.7.2 (I have a saved version), but I also try now with v8.3.0
The files seam to be accumulated over long time.

**Comment by Nicolausi113** [comment]
I have now cleaned the hole Temp folder and can say:
eco v8.3.0 generates empty folders each start and older versions i.e. v7.7.2 generate 4 log files.

![temp3](https://user-images.githubusercontent.com/38510829/64544103-baefb380-d326-11e9-8f08-fa5401a6cb5b.jpg)

**Comment by D3nnis3n** [comment]
The folders are for compiled mods, afaik, assigned redwyre.

**Comment by redwyre** [comment]
As of 9.0 it's all done in memory.
