### ISSUE TITLE
Bug that teleports player when removing/setting ground

### ISSUE THREAD

**Issue by ahsid** [StrangeLoopGames/EcoIssues#13074]
When removing the ground under ones feet or placing something on a tile the player is standing in, while below a block, the player is sometimes teleported upwards. Works relatively inconsistently, should however be able to be reproduced within 6 attempts without any specific setup. See this recording of the bug for reference:
[Bug Recording.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3591505/Bug.Recording.zip)

Works on version 0.8.3.0

**Comment by SlayksWood** [comment]
When you put a block under you, your character throws up. Due to the fact that the house has a height of 3 blocks, he does not have enough space and throws it higher so as not to get stuck.
merged with #10345
