### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13078]
![image](https://user-images.githubusercontent.com/3536496/64567263-b1595200-d30c-11e9-97b9-4dc27a25be56.png)
1. This tooltip doesnt let me mouse-over it, even though it has mouse-over things in it.
2. Not a fan of the background color of the tooltip, so different from the other ones. Can we make them all have similar backgrounds after all?

**Comment by MilenkoTunjic** [comment]
I will change the look of the sprite, but this sprite background was specifically made for non interactive info. so if the tooltip has interactive info, it should not use this sprite

**Comment by MilenkoTunjic** [comment]
And also, can we set the spacing between the text lines to be a bit better specifically spacing between the subtitle and the list
