### ISSUE TITLE
[master preview] Efficiency benefits icons is missing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13084]
In all specialties. Only speed.
![image](https://user-images.githubusercontent.com/45708377/64591710-20898180-d3b3-11e9-9c92-4eb2c8de8fa7.png)

**Comment by SlayksWood** [comment]
Check after changing Craft

**Comment by beastyn** [comment]
have modules now. Professions won't have efficiency anymore (on the modules now)
