### ISSUE TITLE
Crafting issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13080]
Had 3 logs, started an order for 2 hewn logs (requiring 4 logs):
- [ ] After the first log finished, the project stopped here with resources set to 100%. The next workorder should be started with resources at 0% I would think:
![image](https://user-images.githubusercontent.com/3536496/64569153-7574bb80-d311-11e9-9ea2-a4feae261a45.png)

- [ ] Tooltip is showing weird status:
![image](https://user-images.githubusercontent.com/3536496/64569209-99380180-d311-11e9-9524-ed1ceeeedd87.png)
It should say what the problem is as the first thing.  'Needs 1 more log to proceed'.  'Currently crafting, 30 seconds remaining'. Etc.  

- [ ] I then exited the workbench and tried to right click in my one remaining log. Got this error:
![image](https://user-images.githubusercontent.com/3536496/64569253-b8cf2a00-d311-11e9-97ee-b12d8fcc1173.png)

- [ ] Opened workbench back up and tried to add log by dragging, got this:
NullReferenceException: Object reference not set to an instance of an object
WorkOrderContributeListener.GetRelevantTarget (Draggable draggable) (at Assets/UI/Scripts/ItemOrSlot/WorkOrderContributeListener.cs:15)
DragListener`1[T].DragEnd (Draggable draggable) (at Assets/UI/Scripts/Utilities/ReorderOnDrag/DragListener.cs:61)
Draggable.OnEndDrag (UnityEngine.EventSystems.PointerEventData eventData) (at Assets/UI/Scripts/ItemSlotComponent/Draggable.cs:161)

**Comment by beastyn** [comment]
these are fixed
