### ISSUE TITLE
AdminOnLine in GetServerInfo() returns wrong value

### ISSUE THREAD

**Issue by cemeceme** [StrangeLoopGames/EcoIssues#13089]
Verison: 0.8.3.0 Beta

The GetServerInfo() method uses the wrong value to determine if an admin is online.
Instead of returning true when an admin is online, it instead returns true if an admin player has logged in at least once, even if they are currently not logged in.

Instead of checking if "UserManager.Users.Any(...)" it should be checking for "UserManager.OnlineUsers.Any(...)".

**Comment by mirasrael** [comment]
Fixed in 9.0
