### ISSUE TITLE
Push master builds to docker for hosted worlds testing

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13091]
Follow build push instructions here:
https://docs.google.com/document/d/1Eb9-9rI1v40YiQfQ7X-AWVPNWxfJ_xumazjiLMqUJ0E/edit#heading=h.vyxl4tyxosv9

Should push with version title like 9.0.0.0-beta-staging-12345798

Push to Release folder as described in instructions.

If this can be something we just activate as needed that would be better.
But if its easier to make it automatic, that works too.

**Comment by redwyre** [comment]
Master build is now pushed to docker automatically (probably need someone to go in and remove older versions periodically)
