### ISSUE TITLE
USER ISSUE: material processing not completing

### ISSUE THREAD

**Issue by maximus2155** [StrangeLoopGames/EcoIssues#13093]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
do the tutorial for material processing tutorial

**Expected behavior:**
complete the tutorial

**Actual behavior:**
all the boxes are checked but it still wants me to do the second thing, even if I already don that.

**Do you have mods installed? Does issue happen when no mods are installed?:**
all the boxes are checked but it still wants me to do the second thing, even if I already don that.

**Comment by gzatravkin** [comment]
CNR (tested at Develop since it's 9.3)

https://user-images.githubusercontent.com/53317567/104503350-b2188d00-55bf-11eb-861e-42d2fbf6de99.mp4

**Comment by Daniel-Magulado** [comment]
Build: 0.9.3 develop 174


Issue: Unable to reproduce.
