### ISSUE TITLE
Annoying close button is teasing me

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13099]
![anim](https://user-images.githubusercontent.com/3536496/64923791-5a082580-d7d5-11e9-9ef1-b59cbffe9a4c.gif)
This is controlled in WatchMouseOver

**Comment by elfl0rd** [comment]
asked for a long time ago, please add mmb click on tutorial icon, works as skip(close) button.
Same behavior as in browsers.
