### ISSUE TITLE
Server always crashes/doesn't load

### ISSUE THREAD

**Issue by Startbrass** [StrangeLoopGames/EcoIssues#13104]
When trying to start a server it always crashes and I get the message that errors ocurred loading users. Already tried to deinstall both Eco and Eco Server as well as restart multiple times. Nothing seems to help, can't play on the server with my friends at the moment.
The log with error message is attached. Might need some help!
[log_190915072601.log](https://github.com/StrangeLoopGames/EcoIssues/files/3615405/log_190915072601.log)

**Comment by SlayksWood** [comment]
@Startbrass 
please provide saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Startbrass** [comment]
https://drive.google.com/open?id=1hTvOdm3e6vVKhT4MGSqeQeAi1z1J5vCS

**Comment by mirasrael** [comment]
@Startbrass Hmm, just started your save without any errors. Can you ask you friend to start the save? Also can you provide more details about your environment (OS, bitness etc).

**Comment by Startbrass** [comment]
I'm using Windows 10, 64 bit. And I'm sorry I might have uploaded the save file from Eco not Eco Server.
But I'm able to start the world in Eco in Singleplayer, but I can't run it as a server.
Here are the server ones:
https://drive.google.com/open?id=1EY9tKEN0se3q8ts17hmDpI7VjSg1Y7kW

**Comment by mirasrael** [comment]
Ok. Now I have the error. But do you want to use your SP world to play with your friend or the different world from Eco Server?

**Comment by mirasrael** [comment]
As I can see your server world is very old. It has version before 8.0. If you absolutely sure you want to use this very old world then you can try to start it first on 8.0 version and then re-saved world you can try to run on 8.3 version.

**Comment by mirasrael** [comment]
It seems something like 0.7.3.1-beta... I highly recommend to just remove this Game.eco and generate a new world. Or if you want to use your local world then you can just copy it to the server dir.

**Comment by Startbrass** [comment]
Is it possible to remove the server file and replace it with the sp one?
Because we played on that one a few days ago and created it via server and the next day it didn't work any longer. So I'm quite suprised the server world is on an 7. something version due to the fact I just created it 2-3 days ago in 8.3.

**Comment by Startbrass** [comment]
Nevermind my first question, didn't read thoroughly.
But thanks a lot!

**Comment by mirasrael** [comment]
You have a server copy into your client. So probably you created it with this server :)
\SteamLibrary\steamapps\common\Eco Server
\SteamLibrary\steamapps\common\Eco\Eco_Data\Server
those two dirs both contains a server copy, and actually you can just use 
\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Server.exe to start a server and then it will use same file as you're using for your local world

**Comment by Startbrass** [comment]
Alright, thank you very much for your help, it seems to work!
