### ISSUE TITLE
Possible Real Estate Desk Bug - Money going into owners account

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13100]
![realestate](https://user-images.githubusercontent.com/25908592/64932965-cc631f00-d842-11e9-8f97-41bf9260ff30.png)

I'm not sure if that is related to the other quirk the desk has, but in this case the table is owned by me, a third player added a deed to sell on my table, he sold it to a third player and the money has gone to my specified account. In earlier versions this did not happen, the money did go to the correct account of the actual seller, not the desk owner.

I assume the default account of people opening the real estate desk that do not own it, are not set correctly.

**Comment by WeaselDog** [comment]
These two issues are related: https://github.com/StrangeLoopGames/EcoIssues/issues/12840
The money will go into the account of who places the Real Estate Desk.

**Comment by beastyn** [comment]
I can't place deed sale at all/
1. First person has a desk on property 
![bandicam 2019-11-28 10-29-45-290](https://user-images.githubusercontent.com/27898520/69779495-08631a80-11ca-11ea-9cda-b3a1977d39f3.jpg)
2. Second person try to place a deed for a sale on this desk. And can't with error
![bandicam 2019-11-28 10-31-01-758](https://user-images.githubusercontent.com/27898520/69779568-3ea09a00-11ca-11ea-802c-87a7f2bfeaa9.jpg)

But I should be able to(like in 8.3)
![bandicam 2019-11-28 10-42-47-487](https://user-images.githubusercontent.com/27898520/69780050-f3878680-11cb-11ea-80c4-be7599e55553.jpg)

**Comment by mirasrael** [comment]
@beastyn In 8.3 it worked in wrong way, because with current logic all money goes to account configured on Credit tab, but if it has selected account which isn't accessible to seller then you effectively trying to sell your property benefiting another person. It doesn't seems logical for me, so I fixed it this way.

**Comment by D3nnis3n** [comment]
Like with a contract board a registrar should be a object that is usable by anyone.
That means that each person sets its own Destination account and all deeds posted by that person when sold get the money to the set destination account of that person. I know for sure that this was the case earlier as that is the way we used it on White-Tiger for ages.

Why? Because there is servers that limit the creation of Real Estate Desk to be a government object, only available in government facilities - as this fits the goal of a real government. Typically, you can't just sell your deeds in my country, you'll have to get a governmental stamp when doing so.

We do the same with banks, that are only available at banks. Or with registrars.

The bug that all money did go to the creator of the Real Estate Desk was a thing only present in 8.3, in versions before it worked exactly like i described. How that comes - no idea.

**Comment by beastyn** [comment]
Well, it wasn't intended for selling part originally. Bank account was meant only for the buying part.
I wil make separate issue for some UI and logic changes for estate desk.
