### ISSUE TITLE
USER ISSUE: Teleporting through ceiling when mining down

### ISSUE THREAD

**Issue by RedManning** [StrangeLoopGames/EcoIssues#13108]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. Jump into a spot where you are standing on a block that can only be mined with a pickaxe with a solid block directly above you.
2. While still standing on the block, break it with a pickaxe so it splits into 4 or 3 chunks.

**Expected behavior:**
It should have slightly moved the player so they don't get stuck in the middle of 3 or 4 chunks of rock.

**Actual behavior:**
Instead, it often teleports the player (and sometimes a chunk of the rock) on top of the next standable surface above them, like the surface or another hole. This happens without mods.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead, it often teleports the player (and sometimes a chunk of the rock) on top of the next standable surface above them, like the surface or another hole. This happens without mods.

**Comment by SlayksWood** [comment]
dup #10345
