### ISSUE TITLE
Connecting issue to server is impossible after an unknown error 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1311]
I have gotten several reports ( though i have not seen any mentioning about that on the forums etc yet) where people get kicked and cant rejoin servers. The only solution so far seems to delete eco, The appdata folder and clearing the registry. It also seems that there is no error log created when this issue happens.

This here is something that definitely needs more investigation and if anyone has some more info on the issue that might help please do not hesitate to pm me or add a comment here

**Comment by pamduncan** [comment]
All I know about it is as much as you do.  In some cases when a person can't rejoin a restart of the server fixes it - like the server still thought they were there after they were kicked/dropped.  If a restart does not solve it then having them delete the appdata folder and clearing the registry has - in all accounts I have run into - fixed the issue.  I does seem to be happening less with 5.5.1 and on - not sure if something has changed that would effect this or not.

**Comment by metachronism** [comment]
this is likely the deadlocking issue
