### ISSUE TITLE
[master-preview] Can't use stockpile when Steel or Modern Machete in hands

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13114]
and chest
![image](https://user-images.githubusercontent.com/45708377/65036286-c90b8880-d953-11e9-9bf2-0f872035a2f6.png)

**Comment by SlayksWood** [comment]
I can’t take with all the machetes, scythes, axes and etc. after fix.
Steps to reproduce:
- spawn stockpile and place brick
- /gat 4
- Can't take items if tool doesn't suitable. In 8.3.0 You can take any item and it should change tool.

**Comment by redwyre** [comment]
I've added the check to hoe, machete, road tool, scythe, and sickles.
You need to press control to take whatever you can hold (existing functionality, changing this is a separate issue)

**Comment by SlayksWood** [comment]
open separate issue: #13612.
