### ISSUE TITLE
[master-preview] Shovels glithes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13112]
New Crushed items is very similar to Sand and Dirt. But I can’t take it with shovel from the stockpile. If it in carried, then I can’t switch to the shovel. But if I put it on the ground I can only take it with a shovel(Caution, unity can crash).
![image](https://user-images.githubusercontent.com/45708377/65032021-01f32f80-d94b-11e9-8202-4768542e6f9a.png)
![image](https://user-images.githubusercontent.com/45708377/65032542-05d38180-d94c-11e9-9992-57660791b561.png)

**Comment by SlayksWood** [comment]
You can't take a shovel too when you dirt carried:
![image](https://user-images.githubusercontent.com/45708377/65116757-daa36d80-d9f1-11e9-8f0d-c1e9473489e6.png)

**Comment by SlayksWood** [comment]
For all shovels "users remaining" is now х2 consumption for one action.

**Comment by redwyre** [comment]
Double durability use is fixed.
I think shovels block you from changing tools because you're carrying the item on the shovel.
Not being able to take from stockpile is a shared issue with other tools.

**Comment by redwyre** [comment]
I've fixed the issue with not being able to carry crushed or concentrate blocks, which now lets you take them from a stockpile with the shovel.
