### ISSUE TITLE
[master-preview] Hard to build blocks at top.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13110]
To build ladder you need to point top:
![image](https://user-images.githubusercontent.com/45708377/65022231-41b11b80-d939-11e9-9d31-6aa9f860ea8f.png)
In 8.3.0 you need to point upper stage:
![image](https://user-images.githubusercontent.com/45708377/65022273-568daf00-d939-11e9-9975-cae949946e0c.png)

I tried to build stairs but it  placed to wrong position:
![image](https://user-images.githubusercontent.com/45708377/65022536-d3208d80-d939-11e9-8dc6-fb5edc72ff11.png)

**Comment by SlayksWood** [comment]
The same with any top blocks. Previously, it would place the block on top:
![image](https://user-images.githubusercontent.com/45708377/66110634-dcfbef00-e5cf-11e9-8135-ed798b429276.png)
In 8.3.0:
![image](https://user-images.githubusercontent.com/45708377/66110238-0b2cff00-e5cf-11e9-9784-3447dec9e1c8.png)
![image](https://user-images.githubusercontent.com/45708377/66110255-16802a80-e5cf-11e9-8ef2-c451ac890b6d.png)

**Comment by SlayksWood** [comment]
There are still problems. Shadowplacement is now correct, but the block is placed in wrong place.
![image](https://user-images.githubusercontent.com/45708377/68201741-66d61800-ffd3-11e9-915a-12c717729655.png)
![image](https://user-images.githubusercontent.com/45708377/68201749-69387200-ffd3-11e9-8a98-809c899ec2d9.png)
Ladder will appear at the back.

**Comment by redwyre** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/13174
I'm not sure if something broke the `SelectedOffsetPosition` in the `InteractionManager`, or it's just having a tough time trying to work out the block normal with more complex geometry.

**Comment by SlayksWood** [comment]
Need check building in 3d person view.

**Comment by SlayksWood** [comment]
- [ ] 1. Still having problems with ladder:
![2020 01 22 build ladder](https://user-images.githubusercontent.com/45708377/72868768-0746f900-3cf4-11ea-85e6-126406476e64.gif)

- [ ] 2. There is a new functionality in stairs building. But it's very hard to place it diagonally. If you can add some improvements it will be great:
https://drive.google.com/file/d/1tQ2HFy8KmsRON5IuE1M4D_hRzw3RJSuy/view?usp=sharing
![image](https://user-images.githubusercontent.com/45708377/72869024-e8953200-3cf4-11ea-822f-c514d639d004.png)

- [ ] 3. Can't place top block:
![image](https://user-images.githubusercontent.com/45708377/72869895-a9b4ab80-3cf7-11ea-8084-cf695d390005.png)
It tries to place in red zone:
![image](https://user-images.githubusercontent.com/45708377/72869925-be913f00-3cf7-11ea-8e80-3d215919c4e5.png)
![image](https://user-images.githubusercontent.com/45708377/72869929-c3ee8980-3cf7-11ea-8d00-d199be349654.png)
If I try place top block not in corner:
![image](https://user-images.githubusercontent.com/45708377/72869982-e84a6600-3cf7-11ea-8d6b-c269568b0483.png)
![image](https://user-images.githubusercontent.com/45708377/72870020-04e69e00-3cf8-11ea-8e6b-8799789f5363.png)

**Comment by Quadbro** [comment]
3) you can't build like so, it's unnatural, build a stairs to the top and build there))

**Comment by SlayksWood** [comment]
@Quadbro 
Yes. It isn't natural, but it worked in 0.8.3. Then it will be necessary to explain for people  why it is impossible to build with same way. 
Then it need to limit building in height. If I can't place corner block at 5 height:
![image](https://user-images.githubusercontent.com/45708377/72959539-b0a4f200-3dbb-11ea-86fa-2dbfa116af54.png)
Than I shoudn't place blocks like this with another binding:
![image](https://user-images.githubusercontent.com/45708377/72959581-d631fb80-3dbb-11ea-8ae7-b444754c1614.png)
Also need to change shadowplacement.
@D3nnis3n need your opinion.

**Comment by D3nnis3n** [comment]
Generally i don't want to set if it should be possible or not, but as long as a player gets the shadowplacement he should be able to place it as the shadowplacement has shown. If you dont want people to be able to place that high, don't show a shadow. It's very fiddley already though, could be improved. I don't really mind if they build high, but i leave that to others to decide.

**Comment by beastyn** [comment]
Ladders also a big issue still.
https://github.com/StrangeLoopGames/EcoIssues/issues/14916

**Comment by SlayksWood** [comment]
From #15411
> **1. Version:** 0.9.0 Staging 1489
> **2. Steps to reproduce:** Stand on ladder, try to extend it upwards
> **3. Expected behavior:** Ladder is built where the "ghost item" is displayed
> **4. Actual behavior:** Ladder is built behind your player
> **5. Providing Log files:** N/A
> 
> **Trying to build ladder:**
> ![image](https://user-images.githubusercontent.com/982322/77877469-27e08180-7256-11ea-85e1-8c3bbc9d0e2f.png)
> **Actual placement:**
> ![image](https://user-images.githubusercontent.com/982322/77877478-2e6ef900-7256-11ea-9e0b-9b6750000356.png)
