### ISSUE TITLE
[master-preview] Too fast modern hammer

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13115]
Seems that modern hammer is tooooo fast.
Maybe its better to make speed like
stone = 1
iron = 1.1
steel = 1.2
modern = 1.3

**Comment by keegan-o** [comment]
The modern hammer is the top tier hand building tool, I'd like removing blocks with it to be rather expedient, considering how fast you can lay them down now. @redwyre What do we think about allowing people to use 'remove blocks' with the fill types? The fill types are so much faster than one by one placing that it's not even really a comparison. For now I can tweak it down to 1.5 (it's at 1.8 currently). But yeah, that 1.8 speed is still slow compared to using fill types.
