### ISSUE TITLE
[master] Tutorials don't skip correctly-- either with first attempt or second set.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13119]
When attempting to skip all tutorials by clicking the check box, often the first tutorial closes, and then... the next ones appear anyways!

And then, when this happens, you can't skip them at all:
![tutorialsbug](https://user-images.githubusercontent.com/14983165/65068319-4c6daf80-d93d-11e9-9232-fa1014412997.gif)
Nothing happens when you choose to skip and click yes they just stay there.

**Comment by SlayksWood** [comment]
dup #12504
