### ISSUE TITLE
[master-preview] Work Party: feedback

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13117]
1. Step to reproduce:
- Create new! server
- spawn (for example) Workbench
- add (for example) Arrastra to order
- start Work Party. Don't post! and close it(don't cancel). You haven't Icon to reopen this Work Party and you can't create new:
![image](https://user-images.githubusercontent.com/45708377/65038433-9fa12b80-d958-11e9-9015-5739dbac04b5.png)
- reload. Icon should appear:
![image](https://user-images.githubusercontent.com/45708377/65038614-07577680-d959-11e9-9e0d-c18fbdb8bf5a.png)
2. John's Work Party as template sometimes appears:
![unknown](https://user-images.githubusercontent.com/45708377/65038702-37067e80-d959-11e9-85cd-c5766aacef98.png)

**Comment by beastyn** [comment]
3.Also, I think we should open the table automatically for thouse who is taking party in the work parties.

**Comment by beastyn** [comment]
4. Can't change Bank account, currency and amount in Payment.
5. Something wrong with localization. I have english server and engligh client but see russian phrase in thr Progress cell
![bandicam 2019-09-19 16-44-10-623](https://user-images.githubusercontent.com/27898520/65241349-bf715480-dafc-11e9-9adc-1160d84161ca.jpg)
6. What should meand Role cell? Should it list ingridients? For now I can see only start of the phrase and no ingridients at all
![bandicam 2019-09-19 16-46-42-704](https://user-images.githubusercontent.com/27898520/65241497-16772980-dafd-11e9-8d4d-972679c5af5b.jpg)
7. We will have problems with long names
![bandicam 2019-09-19 16-47-46-243](https://user-images.githubusercontent.com/27898520/65241550-373f7f00-dafd-11e9-9569-75d889125b5c.jpg)
8. @johnkslg  In general, what concept do we have with work parties? If we just want someone to help us with some resources, we just can place a store near the crafting table and buy ingridients.

**Comment by johnkslg** [comment]
Work parties will be for sharing all kinds of jobs, and tracking percents and rewarding accordingly.  Theres a special feature for skillbooks where it shares the knowledge if youre crafting over a certain percent.

**Comment by beastyn** [comment]
Still have a bunch of issues here
3.Also, I think we should open the table automatically for thouse who is taking party in the work parties.
5. Something wrong with localization. I have english server and engligh client but see russian phrase in thr Progress cell
6. What should meand Role cell? Should it list ingridients? For now I can see only start of the phrase and no ingridients at all

**Comment by johnkslg** [comment]
@serpopov Can you make work parties exist instead on contract boards, alongside contracts?
