### ISSUE TITLE
Chat Feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13124]
**Top Notifications**
- [x] I would like to change the logic for how this is displayed, it's a bit fiddly right now.
- When ever you activate the mouse cursor and move it in the top 20% of the screen, the notification bar should lerp down slightly from the top of the screen:
![image](https://user-images.githubusercontent.com/3536496/65084182-530d1e80-d95f-11e9-82b4-62f99c89e346.png)
- If you click that bar, it should pull all the way down, showing lots of notifications:
![image](https://user-images.githubusercontent.com/3536496/65084206-68824880-d95f-11e9-8e0e-6bf730d2ea07.png)
- If you click the bar again it should then go back up.
- Use EaseInBack, this will give it that nice pull-feeling that you get with blinds.
- Make the bar have a little texture, so it looks more clickable. 
- The bar should hide itself when the mouse cursor is hidden always (so when youre just running around, its not up there taking up space.

- [ ] This separator bar:
![image](https://user-images.githubusercontent.com/3536496/65084412-f9592400-d95f-11e9-9999-6a2e6bd03c6e.png)
Can we change it so each individual notification doesnt have a separate background, and instead there's just a very faint line between them?  So it seems like theyre all on the same 'scroll'. Having lots of panels feels extra busy to me.  

- [x] Categories:
![image](https://user-images.githubusercontent.com/3536496/65084487-31f8fd80-d960-11e9-9e6d-fb74c6271f34.png)
It is hard to tell which messages correspond to which categories.  Perhaps we have a little bit of faded text in the bottom right of each notification that says the category type? 

- [x] Looks like the right side of this box is cutoff, and the X button is a different size and uses a different color to the other checkboxes. 
![image](https://user-images.githubusercontent.com/3536496/65084550-67055000-d960-11e9-8fb6-55dcacff57cb.png)

**Error Display**
- [x] Type /give pie, notice that an error is displayed, but then it immediately disappears.
- [x] Type /give meatpie,1 then /give meatpie 2.  Notice that you cant actually see the right notification, I see '1' when I send '2'.  
- [x] Errors overlap chat text and look very bad:
![image](https://user-images.githubusercontent.com/3536496/65084789-35d94f80-d961-11e9-8a47-ae183431a9cb.png)
When an error and chat are both displayed, they should be made to never overlap. You can either push chat up, or push the error down.   Also take care that they never overlap GUI elements either (like the carrying icon)
- [x] Errors should display on top of tooltips.

**Important Messages**
- [x] There are too many types of messages that appear here, and most are not important.  Let's change it so that by default, 'direct to player' server messages appear in the regular chat. Then, we will pick and choose what is important. Here is a list of ones that should be important:
- My demographic changing
- Someone buying/selling at my store (but not myself buying or selling at a store)
- Taxes changing
- Civic duties changing
- Elections starting or ending 
- Civic duties like vetoing, creating a new demographic, etc (but not voting).
- Winning an election
- Lots more to be figured out.
- [x] A newline should always be appended to messages. In this case you see two separate messages, 'bad elk meat?' and the next one, which wasnt separated by a new line. 
![image](https://user-images.githubusercontent.com/3536496/65085629-99647c80-d963-11e9-8e1e-813bf108a7b3.png)
- [x] Sprite for important messages is too chunky and doesnt look like a message. How about something that looks more like an envelope with an icon on it:
![image](https://user-images.githubusercontent.com/3536496/65085914-b2216200-d964-11e9-9c95-90760ac32029.png)
- [x] Important messages no longer appear in the chat log. They still should.
- [x] Right now, when you get an important notification, it appears for awhile, then fades out forever.  It should appear for a bit, then minimize to the icon, where I can reopen it and review it, or I can close it. (I realize I said something different before but it doesnt feel good as is)

**Chat Log**
- [x] There are some chat messages that should be tagged temporary and go away after awhile. Ie, after doing a few chat command tests, it was totally spammed with junk:
![image](https://user-images.githubusercontent.com/3536496/65085087-12fb6b00-d962-11e9-92cb-f18bba7cf10c.png)
On the other hand, sometimes I want to take a good long look at the chat commands.  Can you remove that bottom text 'when calling a command with etc', and only display that when getting help on a specific function that takes one of those things, and then only displaying that thing instead of the full list (ie, if the chat command takes a user, only mention 'user', omit the rest of the list).
- [x] Chat text is too large, lets shrink it some.

**Comment by elfl0rd** [comment]
"Error Display"
Also i request permanent chat channel for all errors.
Where errors is not disappear.

**Comment by SlayksWood** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13136#issue-495117645

**Comment by elfl0rd** [comment]
> Top Notifications

Latest notification cannot be seen.
(I give first - tool bench, second - research table, you can see 2 pixel of row which research table.)
![изображение](https://user-images.githubusercontent.com/4980243/65172709-2c7ddf00-da56-11e9-8a3b-e1f6d7aa7a5f.png)

**Comment by elfl0rd** [comment]
> Top Notifications

Settings displayed only for collapsed notifications chat.
![изображение](https://user-images.githubusercontent.com/4980243/65173384-4d92ff80-da57-11e9-9f0b-ccf65be46bd5.png)
![изображение](https://user-images.githubusercontent.com/4980243/65173363-44099780-da57-11e9-9b9d-cb0945b0ca7c.png)

**Comment by SlayksWood** [comment]
I got an invisible last line due to a doublestring.
![image](https://user-images.githubusercontent.com/45708377/65305301-816f4180-db8b-11e9-8cc3-716d1aad8719.png)

@johnkslg 
Top side chat:
1. It is necessary to give the opportunity to change the chat in height! Both: collapsed chat and expanded chat. I should be able to customize how many lines I want to see.
2. It's necessary to give the opportunity to change the chat in width!
![image](https://user-images.githubusercontent.com/45708377/65306684-a87b4280-db8e-11e9-8da8-85de71f42cac.png)
Even if there is a long message, then it’s okay if it is displayed in 2 lines. You can leave the centering.
3. Add the ability to completely hide the chat
![image](https://user-images.githubusercontent.com/45708377/65308491-d95d7680-db92-11e9-8c52-d1b56b1ff5c6.png)
4. Is it possible not to remove the separation? It looks pretty good.

**Comment by SlayksWood** [comment]
Right Chat:
1. If two chat appear at same time They will overlap.
![image](https://user-images.githubusercontent.com/45708377/65312560-71f7f480-db9b-11e9-9196-5dad54a0df76.png)
2. We Have hide "X" button at UI but when you mouseover another button appears:
![image](https://user-images.githubusercontent.com/45708377/65312796-e59a0180-db9b-11e9-8cec-a6b399b4702a.png)

@johnkslg 
3. Can we add possibility to change window size? If you change one window size then All window will change too. For example: add the ability to resize with window left corner.
4. Add possibility to open any chat in any time. Something like the top chat.

**Comment by SlayksWood** [comment]
After last PR https://github.com/StrangeLoopGames/Eco/pull/5005
1. All Channels disapear besides notification:
![image](https://user-images.githubusercontent.com/45708377/65320077-c609d580-dba9-11e9-96fb-1f1ec256fafd.png)
2. Top side chat have new glith. You have empty chat while you until you fill the entire list.
![image](https://user-images.githubusercontent.com/45708377/65320180-fc475500-dba9-11e9-851d-86498e599ee9.png)
3. You need scroll down in expanded chat when new message appears.

**Comment by beastyn** [comment]
Something strange with error notifications when you are trying to dig with excavator or skidsteer on the not authorized property.

You don't get error notification if you do this. It will appear after sometime like blinking message.

https://drive.google.com/file/d/1OY3tNTw529cfGjaSAPRTlq9UDQxfhD9k/view?usp=sharing
