### ISSUE TITLE
Eco Tree Feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13126]
- [ ] Key:
![image](https://user-images.githubusercontent.com/3536496/65086473-c2d2d780-d966-11e9-974f-f52b2b1a9a99.png)
Raise this guy up so its just under the surface.  Also need to change the text:
green: active gameplay feature
brown: active foundational feature
yellow: feature currently being worked on 
grey: future feature

- [ ] Add text shown here to right: https://onedrive.live.com/view.aspx?resid=3D88F4023E294F73!2122&ithint=file%2cdocx&wdo=2&authkey=!AE6vpKbhe-xw3-E
- [ ] Make working parties animate sunbeams onto the leaves theyre on, add all team members in (ask them what nodes theyre on).
- [ ] Bios should be clickable
- [ ] When clicking a node to open the right-window, it opens to the last page that you viewed, then fades to the new one.  It should only fade in if it's already opened, otherwise it should be there when it pulls out.
- [ ] The fade when you click a new page feels sluggish, can make it much faster
- [ ] Need tabs when selecting a feature group.  Saw a bunch of text missing:
![image](https://user-images.githubusercontent.com/3536496/65086629-5c01ee00-d967-11e9-806a-0ad6971d13cb.png)
- [ ] Make all nodes color coded:
![image](https://user-images.githubusercontent.com/3536496/65086642-68864680-d967-11e9-9d91-563d4afd448f.png)
Looks like only yellow is color coded now

**Comment by rainfarmer** [comment]
complete on ecotree branch
