### ISSUE TITLE
Master: no highlight of "target" plot from claim stake.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13129]
![изображение](https://user-images.githubusercontent.com/4980243/65136302-02093300-da10-11e9-8ed6-f753e93250b9.png)

**Comment by WeaselDog** [comment]
Looks fixed now:
![LandClaimPlot](https://user-images.githubusercontent.com/47330823/69748594-8f968c80-10fd-11ea-8aef-6d622c8e11d0.png)

**Comment by elfl0rd** [comment]
+ looks fixed.
