### ISSUE TITLE
Master: can't craft many objects

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13128]
Reciepe require "log" for crafting, but you cannot obtain "log" without cheating.
![изображение](https://user-images.githubusercontent.com/4980243/65135576-d9346e00-da0e-11e9-95c9-a8140445f52e.png)

**Comment by SlayksWood** [comment]
> the lines go beyond the window (crafting)
> ![изображение](https://user-images.githubusercontent.com/4980243/65135705-0d0f9380-da0f-11e9-997e-6bc9864e1d5d.png)
> Also scrollbar overlap content
> ![изображение](https://user-images.githubusercontent.com/4980243/65137883-c1f77f80-da12-11e9-8f89-e723f92b59b5.png)
> 
> Closing buttons displayed, but wont work.
> ![изображение](https://user-images.githubusercontent.com/4980243/65138164-3500f600-da13-11e9-8d57-3402b6fa39f3.png)

**Comment by SlayksWood** [comment]
> Master: cannot start "basic" hewn logs, in any selection start "softwood"
> ![65139091-b86f1700-da14-11e9-86a0-bac925a9db0b](https://user-images.githubusercontent.com/45708377/65141232-e0f91000-da18-11e9-9ef7-017ff29649ce.png)
> ![65139102-bdcc6180-da14-11e9-930a-25a079bb2f3c](https://user-images.githubusercontent.com/45708377/65141257-eb1b0e80-da18-11e9-8f01-aab25da2427c.png)
