### ISSUE TITLE
Master: cannot start "basic" hewn logs, in any selection start "softwood"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13139]
![изображение](https://user-images.githubusercontent.com/4980243/65139091-b86f1700-da14-11e9-86a0-bac925a9db0b.png)
![изображение](https://user-images.githubusercontent.com/4980243/65139102-bdcc6180-da14-11e9-930a-25a079bb2f3c.png)

**Comment by SlayksWood** [comment]
merged to #13128
