### ISSUE TITLE
Master: if "list" project halted, requiment dont show.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13136]
e.g. "Softwood hewn log project halted. needs ."
![изображение](https://user-images.githubusercontent.com/4980243/65138244-55c94b80-da13-11e9-99bf-bba12a83b8e6.png)

Also this errors window show for a really small time, then disappear.
No "permanent" channel to see all messages like this.

**Comment by SlayksWood** [comment]
merged to #13124

**Comment by elfl0rd** [comment]
as i see, this is not chat issue, this is general issue, game cannot display "list" requirements.
