### ISSUE TITLE
Master: "error with hint" show for a too small time

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13130]
e.g. "/give cam" (if you miss correct name)
you see tooltip with mathing names for a second, this is absolutely useless.
![изображение](https://user-images.githubusercontent.com/4980243/65136663-a8553880-da10-11e9-8a84-f82d33849855.png)

I think we need something permanent, like chat channel for errors.

**Comment by SlayksWood** [comment]
dup #13124
