### ISSUE TITLE
Master: UI issues. (quality)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13132]
the lines go beyond the window (crafting)
![изображение](https://user-images.githubusercontent.com/4980243/65135705-0d0f9380-da0f-11e9-997e-6bc9864e1d5d.png)
Also scrollbar overlap content
![изображение](https://user-images.githubusercontent.com/4980243/65137883-c1f77f80-da12-11e9-8f89-e723f92b59b5.png)

Closing buttons displayed, but wont work.
![изображение](https://user-images.githubusercontent.com/4980243/65138164-3500f600-da13-11e9-8d57-3402b6fa39f3.png)

the window is bigger than the contents (DEED)
![изображение](https://user-images.githubusercontent.com/4980243/65135810-3c260500-da0f-11e9-91b3-12a7a1b7a65b.png)

ESC not close large map, not easy to understand what buton close it.
![изображение](https://user-images.githubusercontent.com/4980243/65135887-611a7800-da0f-11e9-81a1-4c471783b227.png)

2D map mode not work as intended.
![изображение](https://user-images.githubusercontent.com/4980243/65135980-80b1a080-da0f-11e9-932f-73e85ecb11fd.png)
![изображение](https://user-images.githubusercontent.com/4980243/65135988-85765480-da0f-11e9-947c-67c3a398084b.png)
![изображение](https://user-images.githubusercontent.com/4980243/65136004-8c04cc00-da0f-11e9-8952-f78d7b6e9530.png)

Also i really want 2 things.
1) M shortcut for minimap.
2) ability to CLOSE map, without saving it on screen.

Map settings...
"New district" outside of all menus and not working
"title" misaligned.
apply\cancel button placement non-logic (why ABOVE section?)
![изображение](https://user-images.githubusercontent.com/4980243/65136973-2fa2ac00-da11-11e9-866b-fc082b36ca49.png)

environment data...
![изображение](https://user-images.githubusercontent.com/4980243/65137084-62e53b00-da11-11e9-8175-7894732b89ef.png)
"None" - dropdown? But empty.
"Beans" in root category.
"Show in world" setting in the general list of categories

**Comment by SlayksWood** [comment]
The minimap is dup #13097
Crafts have not yet been completed yet, but you can make a new issue about UI and functionality or attach it to your #13128

**Comment by elfl0rd** [comment]
@SlayksWood and you totally lost "deed" issue.
