### ISSUE TITLE
Master: building meny opens under chat and tutorial

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13142]
![изображение](https://user-images.githubusercontent.com/4980243/65167965-37337680-da4c-11e9-9751-0f31a4ac6610.png)

**Comment by SlayksWood** [comment]
and markers
![image](https://user-images.githubusercontent.com/45708377/65311438-00b74200-db99-11e9-8995-b919d0632cf0.png)
