### ISSUE TITLE
Master: Logging Balance

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13148]

**Comment by SlayksWood** [comment]
> 1. removing strumps still not provide logging experience.
2. You gain exp for each chopping. It's very nice but you gain x5 exp. In 8.3.0 you gain so much exp for cutting down tree.
It will be nice if you gain exp for damage done.

**Comment by SlayksWood** [comment]
from #12092
> You get the same amount of experience regardless of the felled tree. You also get no experience while cutting wood into pieces. It turns out that the only difference is the difference in the number of wood pulp.
> ![image](https://user-images.githubusercontent.com/45708377/56576857-30eeba80-65d2-11e9-85c2-b3af1dd42742.png)
> 
> Experience for the сhopping of the tree gets the one who dealt the last blow to it.
> It would be better if the experience was given for each blow to the tree (in smaller quantities).

**Comment by SlayksWood** [comment]
From #12003
> Version: 0.8.1.2 beta
> 
> Problem: Calories cost to chop wood
> 
> Steps to reproduce: To chop a tree log and to chop a wood pulp. After that, to compare calorie costs
> 
> Current calorie cost to chop a log with an Iron Axe is 15.3 (using working boots)
> Current calorie cost to chop a Wood Pulp is 45.9
> 
> Considering wood pulp is softwr than the tree log, shouldn't the wood pulp be much lower?

and 

> Moving the Logging talent "Cleanup Crew" to Level 3 instead of Level 6 would help a lot in the short term. Cleaning up Wood Pulp is what makes Logging a viable specialization right now. This is especially true for tree farms.
> 
> I like to think it of as anyone can cut a tree easily, but it takes a specialized logger to cut trees in an environmentally friendly way.

**Comment by Sekor2600** [comment]
Experience in felling trees after the damagenumber done
Example: tree has 6 Hitpoints, axe make with each swing 2,5 Damage. for the first 2 swing you have full Experience, for the rest 1 Hitpoints you have only 0,4 of the full Experience.

Treestump needs variable in Health. all the Treestumps havs same health

Treehealth should grow with Tree.(Example Birch)
Seedling has 0,1 Hitpoint, as young tree 50% and 100% (10 Hitpoint) when mature

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5649
