### ISSUE TITLE
Master: crafting lists not calculate available resources.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13140]
![изображение](https://user-images.githubusercontent.com/4980243/65139209-e81e1f00-da14-11e9-9a05-312159e054bb.png)
![изображение](https://user-images.githubusercontent.com/4980243/65139225-ef452d00-da14-11e9-94df-be17faa21eda.png)

**Comment by beastyn** [comment]
fixed
