### ISSUE TITLE
Master: after change active block, blocks placed, not builded.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13144]
1) select any form, e.g. "wall" and point for hewn log.
2) place all hewn logs you carry.
3) grab another block, e.g. softwood hewn log.
Now you have active "wall" and hammer, but you place blocks instead of building.

To fix you need select "wall" form again.
![изображение](https://user-images.githubusercontent.com/4980243/65168329-ecfec500-da4c-11e9-9d41-7bc35d747663.png)

**Comment by SlayksWood** [comment]
dup #13106
