### ISSUE TITLE
Master: forage for food markers ignore changes.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13145]
i chop this tree. After it i try to chop wood debris.
I'm hungry now...
And tutorial show marker where beet placed BEFORE tree fall.
![изображение](https://user-images.githubusercontent.com/4980243/65169494-4c5dd480-da4f-11e9-9e3d-a3354c3c2b76.png)

Also if you complete this tutorial by gathering non-marked plants (e.g. another beet) plant markers not disappear.
![изображение](https://user-images.githubusercontent.com/4980243/65170324-1ae60880-da51-11e9-8fc4-ef366df0e9b7.png)

**Comment by SlayksWood** [comment]
Can't reproduce first part.
Markers should dissapear when you or another player will harvest plant or plant will be destroyed.

**Comment by beastyn** [comment]
Well, I think that markers which was called with tutorial should disappear when tutorial is done. It wasn't placed by player.

**Comment by elfl0rd** [comment]
Yes, can be easy "bugged".
Any unwanted (different from "gather resource") action breaks the logic.

In my mind, tutorial need to check marked resource state and replace marker onto an existing if something happens.
![изображение](https://user-images.githubusercontent.com/4980243/66247730-efd60700-e728-11e9-8689-7c7a765f1b80.png)

**Comment by WeaselDog** [comment]
The food tutorial has been updated since this point. The markers appear after calories run out.
