### ISSUE TITLE
Master: "Gain specialty XP" - "link" not have tooltip.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13149]
![изображение](https://user-images.githubusercontent.com/4980243/65172419-87630680-da55-11e9-8b6d-2d4637f0f272.png)

https://github.com/StrangeLoopGames/EcoIssues/issues/10813
¯\_(ツ)_/¯

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/76074709-d32a4d80-5fac-11ea-8691-6c22d72c4be8.png)

**Comment by BlackEye2k** [comment]
How is this fixed? I'm still blocked by this issue.
