### ISSUE TITLE
[master-preview] Axe/Chainsaw Glitches

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13152]
1. For all tools "uses remaining" is now х2 consumption for one action.
2. Tools don't break if you chop tree or stump. Tools only breaks if you chop debris. 
3. See #13148

**Comment by WeaselDog** [comment]
Using Axe on Wood Pulp durability use is x4 per hit

**Comment by redwyre** [comment]
Durability is fixed in https://github.com/StrangeLoopGames/Eco/pull/5129
