### ISSUE TITLE
Computer Lab has no collision and can't interact with it

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1315]
Found on a local server with a freshly generated world, not a copy of our live server (that will be in a few hours). If i find more, i'll comment below.

Computer Lab has no collision and can't interact with it.

Depot and non implemented items (such as the water pump, ice melter etc.) is a solid white block but you can interact with it
![image](https://cloud.githubusercontent.com/assets/26527110/24575550/2cb60d1a-16a1-11e7-92af-95b883495b47.png)

HOWEVER... i am loving being able to drive across 0 with a powered cart, the water pump (although now just a block) still pumps water and really love the animation on the pumpjack, keep up the great work slg!

**Comment by MarjieAVolk** [comment]
Non implemented items being rendered as white boxes is (new) intended behavior.

The computer lab is an issue though.  Updating the issue title to reflect that

**Comment by MarjieAVolk** [comment]
Fixed the computer lab hit box problem
