### ISSUE TITLE
Master: (balance) stone hammer break too fast.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13150]
After hammer durability used while PLACE blocks, you need full hammer to made 1 small room.
e.g. 3x3x3 space inside.
it is 5x5x5 external space.
5x5 foundation - 25, + roof - 25 = 50
walls 3x16 = 48
your hammer broken now.

**Comment by SlayksWood** [comment]
You can say same about any stone / wooden tool.

**Comment by SlayksWood** [comment]
Fixed
![image](https://user-images.githubusercontent.com/45708377/72981044-e3b3a980-3dec-11ea-86c9-9a45578fe112.png)
