### ISSUE TITLE
[master-preview] Machete/Scythe flaws

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13154]
1. Tools don't break.
2. Find plant with currient yield = 0. You can't harvest plant with Stone Sickle(same in 8.3.0). But you can harcest it when use Iron, Steel or Modern Scythe. In 8.3.0 you can't.
![image](https://user-images.githubusercontent.com/45708377/65234676-b02ede80-dadd-11e9-8521-439643353237.png) 
You also can destroy perennial plants.
For better visibility, fill  inventory and try to mow the grass with a modern scythe. Only selected grass will be destroyed, not all square site:
![2019 09 19 Scythe flaw](https://user-images.githubusercontent.com/45708377/65235583-91c9e280-dadf-11e9-9e42-3b59441f5948.gif)
3. Mechete destroy all plant. I think it intented behavior.

**Comment by redwyre** [comment]
1. Fixed
2. Seems fixed
3. Correct, machete destroys all plants except trees.

**Comment by redwyre** [comment]
Oh yeah, I want to make it so sythe/sickle can't harvest already harvested grass. Not sure about perennials like tomatoes, if you swing a scythe at tomatoes the whole plant is going to get cut... Also it gives a downside to the larger area of these tools - you have to be careful nothing else is in the way.
@keegan-o @craig-jong thoughts?

**Comment by redwyre** [comment]
I've changed it so the scythe wont destroy grass, but it may still destroy some plants. If you think that is a problem you can open a separate balance issue.

**Comment by SlayksWood** [comment]
After this fix we need to add lawn grass)
Sometimes I can't Harvest plant. I think it connect with low maturity Plant (Corn). I tried to harvest 100% Grass, but can't.
![image](https://user-images.githubusercontent.com/45708377/67943902-28fc7c80-fbec-11e9-9a0e-e5a66e86bf97.png)

**Comment by beastyn** [comment]
recheck

**Comment by beastyn** [comment]
Machete still doesm't destroy all the plants (corn, tomatos, taro).

**Comment by WeaselDog** [comment]
I will take care of the machete not destroying all plants.

**Comment by SlayksWood** [comment]
Machete fixed. Scythe flaw I move to another issue #15480
