### ISSUE TITLE
[master-preview] Stone Sickle instead Stone Scythe?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13156]
![image](https://user-images.githubusercontent.com/45708377/65241933-81b8ff80-daed-11e9-97e8-dcdafe3b7964.png)
In 0.9.0 we have stone sickle instead stone scythe. 
Because of this, the model of tool disappeared. The icon is used from a stone scythe.
Is this a mistake with renaming the instrument? Or stone scythe will be deleted and a sickle will really be added instead?

**Comment by keegan-o** [comment]
fixed in staging.
