### ISSUE TITLE
[master-preview] Pickaxe glithes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13155]
1. For all tools "uses remaining" is now х2 consumption for one action.
2. Increased calorie consumption: 400/289/225/100 for each hit instead 20/17/15/10(or something like that) in 8.3.0. Without Mining Skill
3. I will go from far. In 8.3.0, we had four tool Tier: 1 - Stone Pickaxe, 2 - Iron Pickaxe, 4 - Steel Pickaxe and 6 - Modern Pickaxe. In 9.0.0, we also have four tool Tier: 1 - Stone Pickaxe, 2 - Iron Pickaxe, 3 - Steel Pickaxe and 4 - Modern Pickaxe. Now we have no missed tool tier. They go in a row.
However, the number of hits to each stone is tied to tool tier. Those ModernPickaxe in 0.9.0 = SteelPickaxe from 8.3.0
![image](https://user-images.githubusercontent.com/45708377/65240254-854a8780-dae9-11e9-86ca-4fe4846642bd.png)
It's without talent "Tool Strength: Mining". Now we haven't tool which can destroy Basalt with 1 hit.
It is necessary to remake the parameters of tools. Make Tier 3 like Tier 4. And make Tier 4 like old Tier 6.
If you do so, then issue #12371 will not be relevant.

**Comment by redwyre** [comment]
I've fixed the double durability bug, but the other stuff is more design related.
