### ISSUE TITLE
Normal map details do not function on X axis of world for blocks.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13165]
![image](https://user-images.githubusercontent.com/14983165/65346626-f80f3d80-db91-11e9-9b69-502120f48d10.png)

The wood surfaces here all have normal maps which catch the light from sources such as a torch or the sun.

But on the other axis of the same mesh, the normal map does not have any effect.

![image](https://user-images.githubusercontent.com/14983165/65346681-1e34dd80-db92-11e9-8758-c635769a8ddd.png)

**Comment by keegan-o** [comment]
Scene view of the problem:![image](https://user-images.githubusercontent.com/14983165/65346798-6bb14a80-db92-11e9-9235-3b09ec6ff77a.png)
![image](https://user-images.githubusercontent.com/14983165/65346815-77047600-db92-11e9-98bd-5cf487efa25f.png)

**Comment by keegan-o** [comment]
The shader is the Curved> Triplanar Masked shader. ![image](https://user-images.githubusercontent.com/14983165/65346881-a6b37e00-db92-11e9-88fe-407437df9245.png)

**Comment by keegan-o** [comment]
Oh, update..... in the scene view the shader seems to apply normals to all sides of a dragged in model. So this might be something larger scale than the shader...

![image](https://user-images.githubusercontent.com/14983165/65360552-2c482580-dbb5-11e9-986f-3b6d1cd31205.png)
![image](https://user-images.githubusercontent.com/14983165/65360557-34a06080-dbb5-11e9-87b2-19c92210cde2.png)

**Comment by keegan-o** [comment]
I'm making this a high priority bug because I'd like a good chunk of time to fix up block art after this is fixed *before* 9.0 is released.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/69106027-f8a54280-0a21-11ea-9a41-763a33483297.png)
Here's a fun example, since for ashlar it relies entirely on the normals for the brick part of the texture

**Comment by redwyre** [comment]
The problem was that tangents were getting dropped and never recalculated.

**Comment by beastyn** [comment]
How cam  have I have this light effect from tourch? It looks like this in game
![bandicam 2020-01-24 16-42-44-424](https://user-images.githubusercontent.com/27898520/73066727-960c6f00-3ec8-11ea-89c2-e3da93a352b1.jpg)

**Comment by redwyre** [comment]
Torches rely on GI to light up things... it would be good to fix but that's a separate issue for now
