### ISSUE TITLE
[master-preview[ Audio: no sound on tables

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13163]
https://drive.google.com/file/d/1cQsF_oHdigJln7LjA9KPFVc1Bln8HWgM/view?usp=sharing

**Comment by beastyn** [comment]
@Quadbro so, its Arastra. If you put it on and launch it will make this sound. And if you remove it, sound is still there.

**Comment by Quadbro** [comment]
there are lot's to do there, do not hurry to list all the audio bugs, cause it's in progress)

**Comment by beastyn** [comment]
For all tables can appear the dame problem.

**Comment by WeaselDog** [comment]
fixed in latest staging build

**Comment by beastyn** [comment]
I would say all tables have lost tjeir sounds
