### ISSUE TITLE
Building meny feedback\suggestion

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13164]
In the current state, I personally find the construction window far from being the most convenient to use.
Apart from the old problems, several new ones appeared at once.
You need to reassign the Shift button, because otherwise you cannot run with a hammer in your hand.
And the inconvenience of choosing forms in general.

I suggest the following few things:

You should be able to add forms to favorites.
For example, through an star next to a form or the ability to drag and drop forms into a favorite cell.

Correspondingly, it is desirable to return scrolling of the selected forms by "hot key %1 + hot key %2/%3" which is adjustable in settings.
For example, the mouse wheel up\down or the arrows (at the discretion of the user, even ctrl+l/r.)

The most convenient way to see the window with the list of forms is to switch its visibility by "hot key %4 adjustable in settings" and\or by clicking the mouse cursor on forms near the carried building materials.

It is also desirable to allow the user to move this window and change its size.

It is desirable to change the design of the window for selection of forms and type of construction, for example, turning it into a "book" style to match other window forms.
![изображение](https://user-images.githubusercontent.com/4980243/65324662-8c3ecc00-dbb5-11e9-8bea-56185a3b373b.png)

**Comment by SlayksWood** [comment]
> You need to reassign the Shift button

You can reasign it in controls
![image](https://user-images.githubusercontent.com/45708377/65330600-97005d80-dbc3-11e9-9623-c43c0ee1df0e.png)

**Comment by elfl0rd** [comment]
> You can reasign it in controls

Yes, i got it.
But "default" settings is not optimal for me.

**Comment by SlayksWood** [comment]
The block selection window has been redesigned but not yet completed. Seems not actual.

**Comment by elfl0rd** [comment]
Still actual, redesign not fix shift issue, and not contain ability to easy swith blocks.

**Comment by elfl0rd** [comment]
@SlayksWood
