### ISSUE TITLE
Master: particles highlighting looks ugly.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13168]
![изображение](https://user-images.githubusercontent.com/4980243/65360180-92f62f00-dc07-11e9-89c3-b9b6eacbee53.png)

**Comment by SlayksWood** [comment]
It's dust highlighting. But looks strange

**Comment by elfl0rd** [comment]
Same at campfire
![изображение](https://user-images.githubusercontent.com/4980243/66648760-0acade80-ec35-11e9-81cd-e36a3eaba3ac.png)
I think need highlight only "interactable object", not "effects"

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/70364753-b746cc80-1842-11ea-94fe-3f57945b3c91.png)
fixed in staging.

**Comment by elfl0rd** [comment]
Great

**Comment by elfl0rd** [comment]
But... merged?
![изображение](https://user-images.githubusercontent.com/4980243/70369545-59f75d80-18cc-11ea-91a8-f0c9319e6cc3.png)
@keegan-o

**Comment by beastyn** [comment]
looks fint in the last build
