### ISSUE TITLE
[master-preview] Tutorial's icon displacement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13160]
Seems like line is too long in the beginning. It was shorter.
![unknown (15)](https://user-images.githubusercontent.com/27898520/65307769-f8173980-dba1-11e9-93e9-d483d272b225.png)

**Comment by Quadbro** [comment]
@gzatravkin Comes after your hierarchy transfers, please check it out
![image](https://user-images.githubusercontent.com/6802030/65491856-13ec4980-deda-11e9-8b5d-45bb06b619de.png)
Top notification panel must not conflict with this
