### ISSUE TITLE
Web page feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13166]
**Elections**
- [x] The table explaining the change is missing its header:
![image](https://user-images.githubusercontent.com/3536496/65350630-f9913380-db9a-11e9-93a0-88c27fe9ab78.png)
You can see in swagger that the first row is there, its not being displayed for some reason.
![image](https://user-images.githubusercontent.com/3536496/65350623-f5651600-db9a-11e9-8ea9-fe0afe7c4b5c.png)

- [x] This layout needs to be changed to make the election more clear:
![image](https://user-images.githubusercontent.com/3536496/65350667-1168b780-db9b-11e9-8ffc-d9ae1d8b8efc.png)

IE, the first thing you should see is the Election title. "Modify Constitutional Article". This should be a big header at the top, showing you what youre looking at.

Then you should see the details about what the election concerns. Show this table:
![image](https://user-images.githubusercontent.com/3536496/65351386-d10a3900-db9c-11e9-8a8e-337a046bc0cc.png)
The table needs a better description at the top. I've added a PropertyTableHeader parameter that gets sent with the query, display that at the top (and make sure the first row displays, as described above).  It will describe what exactly the table is.  For bonus points, in elections that are showing a modification, highlight the entries in columns 3 and 4 that are different, as these are the important parts. You can do a string compare. 

Then the call-to-action, the voting buttons.    'Election Title, Yes or No buttons.
![image](https://user-images.githubusercontent.com/3536496/65350793-6278ab80-db9b-11e9-814d-a8a2f97787fd.png)

And the final results displayed to the right as is currently. You can move the 'Election Info' (which is currently at the top of the page) to be a footnote in the results section, it shouldnt take top-billing like that.

Then, the discussion at the bottom.   

- [x] Clicking 'View All Votes' put a popup in the top left. Can this be centered?
- [x] When clicking the election process, add a header that describes what you're seeing to the table.  "These are the settings which determine how this election is run."
- [x] After voting once, I wasnt able to click 'update vote' to change it. 
- [x] If I've already voted, it should highlight which vote I made when I arrive at the page. Currently it doesn't highlight.  Also, make the highlight more explicit, like a bright yellow selection + glow instead of a slightly different shade of green.

- [x] The results with rounds should not be displayed for yes/no elections. It should just be a pie graph with numbers.
![image](https://user-images.githubusercontent.com/3536496/65355454-cfde0980-dba6-11e9-8621-fb7e7f73872e.png)

**Title Elections**
- [ ] I like that you grey-out options already selected here, but the color difference is so subtle I could barely tell. 
![image](https://user-images.githubusercontent.com/3536496/65355361-9a392080-dba6-11e9-85b6-5f5a099cabc0.png)
- [x] Compress this:
![image](https://user-images.githubusercontent.com/3536496/65355408-b341d180-dba6-11e9-876a-e58e62389891.png)
- Dont display speech if it's blank. 
- Less margins

- [x] Results is confusing: 
![image](https://user-images.githubusercontent.com/3536496/65355472-dc626200-dba6-11e9-979e-15631fa236ae.png)
Imagine you're a player that has never come across instant-runoff-voting before, this is going to be super confusing.  Lets do this to make it easier:
- Sort by the winners, in fact this is already delivered to you by the ordering of the ChoiceRanks field inside Results.
- Add a description in tiny text under the table: This election is conducted with Instant Runoff Voting. This means that if a citizen's first choice candidate doesn't have enough votes to win, their vote goes instead to their second choice candidate, then third choice, and so on.  This table shows each round of removal and how many votes each candidate has. For more info, see here <link to wikipedia article>
- [x] Same as for bool elections, change the layout to make more sense. The top should say what the election is, and the 'election info' should be tucked away under results somewhere. It also needs to display the PositionForWinner table that's sent in the query:
![image](https://user-images.githubusercontent.com/3536496/65355742-7d511d00-dba7-11e9-8e7f-deda207503f3.png)

**Comment by beastyn** [comment]
Election for Modifying an Article has row with Proposers like ths
![bandicam 2019-11-12 10-34-11-192](https://user-images.githubusercontent.com/27898520/68645726-b750f680-053a-11ea-984a-97a94656546b.jpg)

There should be Demographics, titles or users

**Comment by beastyn** [comment]
I still can't tell wich number was used already in rank voting.
Here is: num 1 was used. But its almost the same color. We should highlight somehow this already-in-use numbers.
![bandicam 2019-11-12 12-46-01-070](https://user-images.githubusercontent.com/27898520/68652405-30f0e080-054b-11ea-9dd7-637a7b966f6c.jpg)

**Comment by rainfarmer** [comment]
- [ ] On scientific page, bar graphs are not displaying correctly. I dont see any bars. Line graphs work correctly.
- [ ] Premade graphs are empty
