### ISSUE TITLE
[master-preview] Several flaws in Minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13170]
- [x] 1. Hotkey "M" work wrong(?).
John told to tie Hotkey to full-size Map, but if you open small map and then press "M" you will swith besides full-size map/ small map. Is it intented behavior?
![image](https://user-images.githubusercontent.com/45708377/65405501-0b661700-dde5-11e9-850e-5e76b7d1b355.png)
I would prefer another option. If you press "1" you will be switch between full-size/ rightMap untill you press "2" then you will switch between smallMap/rightMap. 
Or It will return to previous Minimap version. For example: 
- by default in first connect it should open Full-size Map.
- Have minimap in right bottom corner. 
- Press "M" it should open full-size Map
- Press "M" - right bottom corner Map (previous open). New previous open will be full-size Map
- Press "M"- full-size Map.  New previous open-  right bottom corner
- use mouse to change to small map. New previous open - full-size Map.
- Press "M" - full-size Map. New previous open- small map.
- Press "M" - small map. New previous open - full-size map
- use mouse to hide map at right bottom corner.  New previous open- small map.
- Press "M" - small map. New previous open - right bottom corner.
It will allow you to choose the most suitable option for you. Now I can’t make the hotkey switch between Small map and lower right corner map.

- [x] 2. Left and Right of  Small Map, about 5 mm, an strange texture is located.
![image](https://user-images.githubusercontent.com/45708377/65406716-115df700-dde9-11e9-861d-56c3a635d68a.png)

- [x] 3. Map should go behind Tutorial, Work party, Craft Icon , Contract Icon
![image](https://user-images.githubusercontent.com/45708377/65407449-39e6f080-ddeb-11e9-8ccb-d4e33648f029.png)
![image](https://user-images.githubusercontent.com/45708377/65407532-7dd9f580-ddeb-11e9-9a71-044ef5a8296c.png)

- [x] 4. Increase the minimum width(and maybe height) in small Map:
![image](https://user-images.githubusercontent.com/45708377/65407634-db6e4200-ddeb-11e9-8f5a-c4b8310daa98.png)
Make the square in which the right panel fits. Something like that:
![image](https://user-images.githubusercontent.com/45708377/65407715-0e183a80-ddec-11e9-8f4f-383910269243.png)

- [x] 5. When opening the map, the cursor should always appear (AutoTab)

- [ ] 6. After fixing 5 number It will be less actual, but still the bug will remain:
- open Full-size Map
- remove cursor (exit Tabmode)
- press ESC. Minimap will close but Esc Menu will open. If Tabmode is enabled in the minimap, everything will work fine.

- [x] 7. Add memory to opened / closed right panel. If I close Map and right panell was open then when I open another time It should be open.

- [x] 8. Large font size "Markers". Visually looks more than in "Settings" and "Enviroment Data"
![image](https://user-images.githubusercontent.com/45708377/65408563-39038e00-ddee-11e9-9f35-6ffd1bdd5a4c.png)

Also different design in "Settings" and "Enviroment Data" tabs.
![image](https://user-images.githubusercontent.com/45708377/65408729-b4653f80-ddee-11e9-9282-72fb0a4c1887.png)
Also a very large font for "Environment Data" list.

- [x] 9. 2D Minimap doesn't work at a large distance
![image](https://user-images.githubusercontent.com/45708377/65409018-5ab14500-ddef-11e9-98b1-aeac2a41b7de.png)
![image](https://user-images.githubusercontent.com/45708377/65409133-977d3c00-ddef-11e9-902e-7524aa3bdeca.png)

- [ ] @johnkslg 
10. It's more suggestion. Add a button to open / close the right panel on the minimap. For Example Shift+RMB at Minimap or any other Mouse combination.

**Comment by SlayksWood** [comment]
@johnkslg 
How to determine the time of day in 9.0? Previously, it was at right bottom corner of current minimap.
![image](https://user-images.githubusercontent.com/45708377/65424306-e50ba000-de13-11e9-9084-824c49e1c445.png)

**Comment by elfl0rd** [comment]
You can loose map forever if you move it under UI.
Also map screen is not pop-back to screen if you drag it off.
![изображение](https://user-images.githubusercontent.com/4980243/67598976-95542780-f777-11e9-99aa-852eaffa24fa.png)

**Comment by elfl0rd** [comment]
2) After editing the marker, the cursor does not remain free.
In my opinion, the choice should be left to the player, maybe he wants to put or change another marker, etc.
Besides, the control if you blind (map cover all screen)...Is strange. I would prefer always to have a free cursor in full map mode.

3) "Max Distance To Show" - need add next to it "Min Distance To Show".
I don't need a marker at home if I'm in it, but if I'm far away, it's convenient if I start seeing it without switching the marker visibility.
In addition, if used correctly, it will reduce the number of displayed markers, while maintaining full comfort for the player.

**Comment by elfl0rd** [comment]
Maybe there this is better - https://github.com/StrangeLoopGames/EcoIssues/issues/13637

**Comment by elfl0rd** [comment]
Map -> Environment data -> World contain a lot of dead switches.
![изображение](https://user-images.githubusercontent.com/4980243/68544548-4fcd6680-03d5-11ea-93fe-c8592ddd421f.png)

As i think, "Markers" should be collapsed by default?
![изображение](https://user-images.githubusercontent.com/4980243/68544560-78edf700-03d5-11ea-95b6-b8354696bbeb.png)

**Comment by WeaselDog** [comment]
Tab is enabled by default now in full size map but it was confusing for me. At first I thought that it was bug that we couldn't move with map open. If tab is always enabled when opening map the right panel should open by default as well.
