### ISSUE TITLE
[master-preview] Hard to place several composite lumber ThinBlocks

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13174]
1. WinwowWall, Window, WindowGrilles, Fence, SideFence at corner:
![2019 09 23 Hard to place several composite lumber ThinBlocks](https://user-images.githubusercontent.com/45708377/65419792-1e3e1300-de08-11e9-8403-88f45b2790ea.gif)
Video:
https://drive.google.com/file/d/1XIZzTaZc_HSxDEnEktHt_AAdA8JTFfna/view?usp=sharing
2. WinwowWall, Window, WindowGrilles, Fence, SideFence at top or side:
![image](https://user-images.githubusercontent.com/45708377/65420045-d8357f00-de08-11e9-8e35-21ad2866099f.png)

**Comment by redwyre** [comment]
No simple fix for this, as the block collision is used for targeting. @keegan-o when you get back can we play around with expanding the collision on these blocks?

**Comment by keegan-o** [comment]
I will try expanding the collision, sure!

**Comment by keegan-o** [comment]
These ones are fixed in staging, but will wait to close until I check out some other big problems like this with stairs and roof things.

**Comment by keegan-o** [comment]
Closing this, will be too annoying to track sub-issues possibly related to this so they can just be their own new issues as needed.
