### ISSUE TITLE
Aspect ratio and positioning is off for introduction video art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13175]
![image](https://user-images.githubusercontent.com/14983165/65473737-e0ec7c00-de2d-11e9-8ef7-5029e9cc4548.png)
![image](https://user-images.githubusercontent.com/14983165/65473744-e9dd4d80-de2d-11e9-9f58-c32ba8669689.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/79328862-64330380-7f1f-11ea-91b0-8461476be2f2.png)
