### ISSUE TITLE
[master-preview] Hammer filled type glitch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13173]
Steps:
1) Take material
2) Take iron hammer
3) Take point fill and some form
4) Build
5) Press ctrl
6) Build

It should still build with point, but after Ctrl was pressed fill type became rectangle without any changes in the UI (Ctrl is for Crouch in the Controls).

https://drive.google.com/file/d/1HFtc-phduveU39zmcDi4UjG-ChFjsJ7j/view?usp=sharing

**Comment by redwyre** [comment]
I was using ctrl as a debug key to change fill, I thought I removed it but I guess not!
