### ISSUE TITLE
USER ISSUE: bad connection issue today 

### ISSUE THREAD

**Issue by Deygus** [StrangeLoopGames/EcoIssues#13186]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
play game for awhile
get kicked off today 3 times in a row now WTF

**Expected behavior:**
let me stay logged in and keep playing	

**Actual behavior:**
play game for awhile and it just logs out saying steam login token or connection error... IM SO FED UP that this keeps happening...

**Do you have mods installed? Does issue happen when no mods are installed?:**
play game for awhile and it just logs out saying steam login token or connection error... IM SO FED UP that this keeps happening, is this connection crap ever gonna end???????????

**Comment by SlayksWood** [comment]
Did it happen just yesterday? Was everything all right on other days?
Which server were you trying to connect?
Please provide your PC specification (include Operating System) and log files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Deygus** [comment]
> Did it happen just yesterday? Was everything all right on other days?
> Which server were you trying to connect?
> Please provide your PC specification (include Operating System) and log files:
> Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

It's been fairly okay for the most part but I still lose connection to the server at least once maybe every couple of days but that was at least somewhat tolerable. Yesterday was the worst though and I have no idea why other than seeing something about" Steam User ID Key Changed " or whatever it's called said something about that changing. It's been mostly fine before that. I really like this game but some days when it does this stuff I just want to quit playing it. I did that before for a long time it made me stop playing and I just waited for some updates before trying again as of about 3 weeks ago. I don't really think it's my computer because I can spend hours and hours on games like Battlefield V, GR Wildlands, World of Warcraft, Elderscrolls Online for like ever and I never have any connection problems...

**Server:**
US NOOBS BUILDER PARADISE


**System Specs:**
- Acer Predator G17
- Windows 10
- Nvidia GeForce 970 gtx
- 3 gb vram
- 250 ssd, 1 tb hd
- 16 gb ram


**Requested Log Files:**
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3652752/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3652753/Player.log)

**Comment by mirasrael** [comment]
Hi @Deygus At which time (GMT) it happened and did it happen after that? Yesterday we updated auth server, so for some short period it may cause auth problems.

**Comment by Deygus** [comment]
@mirasrael Ah okay, that might be what happened then since I recall seeing some sort of Steam Auth ID Key message when I got kicked off the game server.

I got online right about 5:30pm EST roughly and it happened maybe 30 minutes later or somewhere around there.

**Comment by mirasrael** [comment]
Ok. Please let us know if you will continue experience this problem. And please attach screenshot with error if it happens.

**Comment by Deygus** [comment]
Sure @mirasrael I will be playing this evening and if something happens I will take a screenshot so you all can see the exact issue if anything occurs though obviously I would hope not.
