### ISSUE TITLE
Unknown-5.6(92888c9b): Picking up with big shovel, jumps to any shovel with lowest slotnumber

### ISSUE THREAD

**Issue by Neouni** [StrangeLoopGames/EcoIssues#1318]
Picking up a stack of dirt, jumps to lowest quickbar number equipped with a shovel.

shovel 1, big shovel 2 = shovel 1 holding 10 dirt
big shovel 1, shovel 2 = big shovel 1 holding 10 dirt

Minor bug, probably shows up on other tools too with pickup.
But you notice it when you want to pickup the next batch.

**Comment by MarjieAVolk** [comment]
Fixed
