### ISSUE TITLE
Composite lumber clad wall builder issue

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#13182]
![image](https://user-images.githubusercontent.com/431728/65513032-c85b8f00-df1d-11e9-8ce9-edba97559235.png)

If you place a composite lumber piece in the middle, the unattached corners will turn into 4-way pieces

![image](https://user-images.githubusercontent.com/431728/65519398-322d6600-df29-11e9-9207-834759ae0fe8.png)

**Comment by keegan-o** [comment]
Fixed in master.
