### ISSUE TITLE
[master-preview] stuffed elk texture 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13181]
missing grass and pink fence 
![image](https://user-images.githubusercontent.com/45708377/65505605-42662680-ded2-11e9-8b65-c27290e1b096.png)
![image](https://user-images.githubusercontent.com/45708377/65506032-50687700-ded3-11e9-9d21-1846144fa5fa.png)

**Comment by elfl0rd** [comment]
Grass still missed, it is intended?
