### ISSUE TITLE
[master-preview] Storage UI 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13180]
String"Linked inventories" shouldn't move and differ from other string. How it was in 7.8.9:
![unknown (12)](https://user-images.githubusercontent.com/45708377/65494715-f9a47280-debd-11e9-8812-970dba82abca.png)
It's moving now in 0.9.0 if you start scroll:
![image](https://user-images.githubusercontent.com/45708377/65494775-222c6c80-debe-11e9-8795-83e394da7b46.png)

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/75670211-643bb480-5c8d-11ea-86d1-78a0a91e0357.png)

**Comment by beastyn** [comment]
We kind of got it wrong.
Kirill was asking to stick Linked Invenories header along with active storage UI.
![bandicam 2020-04-20 11-26-14-947](https://user-images.githubusercontent.com/27898520/79720371-df1e6480-82f9-11ea-8089-3ba9f9e7ceb0.jpg)

This part should always stay at the top when scrolling

**Comment by elfl0rd** [comment]
it SHOULD be pinned, but with ability to OPTIONAL unpin or collapse.
