### ISSUE TITLE
Advanced Masonry table can fly

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13197]
Step to reproduce:
- place Advanced Masonry table
![image](https://user-images.githubusercontent.com/45708377/65664129-55e3cf80-e041-11e9-81ac-23ee07d26884.png)
- Move away. It flies
![image](https://user-images.githubusercontent.com/45708377/65664162-698f3600-e041-11e9-9341-10985f4e4d3a.png)

**Comment by mirasrael** [comment]
Seems like it uses non-curved shader.

**Comment by keegan-o** [comment]
fixed in master
