### ISSUE TITLE
[master-preview] Framed Glass and Glass Blocks

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13191]
![image](https://user-images.githubusercontent.com/45708377/65595877-61ca8580-df9e-11e9-8a2f-46e16ec56454.png)
Cube = Floor
Window = Wall.
Need to make the blocks different. 
If it will not add in 9.0, then you need to leave only one block of two (Cube and Window) and delete other(Floor and Wall)

**Comment by SlayksWood** [comment]
> As I think, glass should be changed.
> 
> Current "window" form rename to "wall" (without model changes)
> And add new form as "Window" with frame, like cube
> ![изображение](https://user-images.githubusercontent.com/4980243/81670467-56a26800-9450-11ea-8bd1-eb87b452c097.png)

> Alternatively, remove 'window' entirely. It's possibly a bit redundant. How is a glass window different from a glass wall?

> Glass window - glass panel with wood frame, like cube.
> Glass wall - just glass panel.

**Comment by keegan-o** [comment]
Revamping this whole set is covered now in an epic for 9.1
