### ISSUE TITLE
[master-preview] game.db size is very big

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13202]
My test server is running for about 32 hours (with breaks) and it has a database whose size is almost 850Mb. I'm not doing anything, but the size of the database is growing  very fast.
Anna's test server is running about 29 hours - 220 Mb. Her world is very poor to world objects and items.
Looking at the latest backups, It's around 40 Mb in half an hour.

**Comment by mirasrael** [comment]
Top tables:
PolluteAir (98% of test db)
BuildOrRemove
InventoryAction

When I dropped Pollute Air:
346M -> 4.8M
