### ISSUE TITLE
USER ISSUE: Blocks won't vanish after digging/mining

### ISSUE THREAD

**Issue by TootleBrush** [StrangeLoopGames/EcoIssues#13207]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
get a skid steer or excavator.
Dig in to dirt, ore or stone.

**Expected behavior:**
mined the block and made it vanish leeving behind the mined item in the mashinerys inventory

**Actual behavior:**
It mined the block, left the items in the machines inventory but left behind the visual of the block.

**Do you have mods installed? no

Does issue happen when no mods are installed? yes:**

It mined the block, left the items in the machines inventory but left behind the visual of the block. but mechanic of blocking for passage through it is still in place so machinery or avatar can't move through it. 
Only seem to happen on my client as other on server don't see the same error
![20190926214807_1](https://user-images.githubusercontent.com/55036355/65720456-42b81a80-e0a8-11e9-87ce-d924d4f570c9.jpg)

**Comment by TootleBrush** [comment]
a note.
This issue had never happened to me before patch 8.3.0. So all previous patches had none of these issues with digging/excavating.

**Comment by redwyre** [comment]
If you disconnect and reconnect to the server do the blocks update? Also can you attach your log file: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TootleBrush** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3664071/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3664072/Player-prev.log)

The issue vanish if I disconnect and reconnect. But the problem have never happened before the latest patch. So its a new thing for me at 8.3.0

**Comment by TootleBrush** [comment]
Anything new on this issue?
Its starting to become very frustrating as the economy of a server is based 80% on gettint recourses from the ground, either by shovel or pickaxe. 
And when the whole server is on a industrial level, being set back to shoveling then its no longer a interesting game when you hit a bump like this all the time.

**Comment by SlayksWood** [comment]
@TootleBrush 
Sorry for the long wait. We can't reproduce your bug at the moment. We have a lot of changes in 0.9.0, including digging with Excavator and Skid Steer. I hope it will help you in future. 
You can help us when public staging appears (soon). You can check this bug in 0.9.0 before the release so we can fix it. 
Sorry again, but we can’t help you until 0.9.0 will release.
Please provide your PC specification (include Operating System).
