### ISSUE TITLE
[8.3]Styled text commands on truck crashes game

### ISSUE THREAD

**Issue by Sepishow** [StrangeLoopGames/EcoIssues#13204]
Bug crashes everyone's games that are in render distance to the truck. Only wait to fix it is to delete truck from server files. 
Bug:
Write in Steam Truck text field: 
`<size=100>text<br><br><br><br><br><br><br><br><br><br><br><br></size>`

If it does not crash game, add more `<br>`.

**Comment by SlayksWood** [comment]
Unity crash

**Comment by Quadbro** [comment]
Tested in latest staging - cant repro this...

**Comment by SlayksWood** [comment]
@Quadbro 
still an issue. checked on Steam Truck?

**Comment by Quadbro** [comment]
Yeap, steam truck catched the issue, fixing....

**Comment by Quadbro** [comment]
Fixed in svn

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/68591714-6988af80-04a2-11ea-9d31-b94e175e7476.png)
Seems fixed
