### ISSUE TITLE
[master-preview] Lumber Door Offset

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13218]
In 8.3.0 we have #12108. But in 9.0 Lumber doors are offset in one side.
![image](https://user-images.githubusercontent.com/45708377/65762176-109acd00-e129-11e9-81c3-bacca59c68cf.png)
![image](https://user-images.githubusercontent.com/45708377/65762197-20b2ac80-e129-11e9-8cfb-8bc6c72ccebc.png)
Rest Doors open like in 8.3.0

**Comment by keegan-o** [comment]
This is a perfect little bug for @Phlo123 to try his hand at correcting.

**Comment by Phlo123** [comment]
Fixed in staging.
