### ISSUE TITLE
[master-preview] You have empty tab in Registrar

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13214]
1. Missing "Store" tab in Store 
![image](https://user-images.githubusercontent.com/45708377/65746516-ba696200-e107-11e9-8c34-e83847a9fa65.png)
2. Missing "Exchange" tab in Currency Excahnge
![image](https://user-images.githubusercontent.com/45708377/65761175-fcee6700-e126-11e9-8ceb-d5ec5eba82f3.png)
3. Missing "Repair" tab in Tool Bench
![image](https://user-images.githubusercontent.com/45708377/65761401-63738500-e127-11e9-84d1-35bd4a5a58c0.png)
4. In Registrar you have empty tab
![image](https://user-images.githubusercontent.com/45708377/65761451-771eeb80-e127-11e9-8823-3468e78c1b93.png)

**Comment by SlayksWood** [comment]
At this moment only point 4. In Registrar you have empty tab.

**Comment by beastyn** [comment]
Still empty.
![bandicam 2019-11-15 11-00-01-459](https://user-images.githubusercontent.com/27898520/68920463-1b6ff680-0797-11ea-994e-35deed4de42e.jpg)
