### ISSUE TITLE
[0.8.3] Deleting a title can remove all access to a bank account

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13213]
Steps to reproduce:

1.) Create a bank account with only a title as a manager:
![BankAccount](https://user-images.githubusercontent.com/47330823/65734954-2a390780-e08a-11e9-9e5d-c8f0b724bebf.png)

2.) Delete the title

3.) The account now has no manager or authorized users:
![NoManager](https://user-images.githubusercontent.com/47330823/65734979-48066c80-e08a-11e9-9177-a6ca3d93f678.png)

Attempting to delete the title should result in failure with an error message similar to this:
![ExpectedMessage](https://user-images.githubusercontent.com/47330823/65735016-653b3b00-e08a-11e9-98b7-1d829bca2239.png)

**Comment by mirasrael** [comment]
Fixed in 9.0

**Comment by WeaselDog** [comment]
It is still possible to remove access in 9.0, but it is much harder to do by accident:
![RemovedAccount](https://user-images.githubusercontent.com/47330823/69303468-f97cd680-0bd1-11ea-8a6c-6163b450da72.png)
