### ISSUE TITLE
[master-preview] Calorie powered crafting Feedback

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13215]
- [ ] 1. It's a very bad idea to limit labor to resources. Basic action from everyday playing:
- you place store and start to buy Logs and to sell Hewn Logs.
- you place Carpentry table and add orders (at 7 level always same) to 9999 Hewn Logs. 
- At 8.3.0 People came to sell me Logs and in return received Hewn Logs (without my participation). Now I can’t do this, after each sale of resources I will need to add work. 
On the one hand, you can say It will increase the interaction of people. But on the other hand, I can say that you have to sleep, work IRL and just the opportunity to leave for a couple of days without leaving people without a specific profession. And I think that Working Party will not solve this problem.
Therefore, if I could add calories to the whole craft immediately it would be very good.

- [ ] 2. Add another button to add all calories at once. This button will add resources to the maximum possible. Now: for craft 1000 hewn Logs I need 130000 calories(may be it will balance, but as example.) 130000/50 = 2600 clicks. It's crazy number. If you want to build Room from Composite Lumber I think you need more than 5000 Hewn Logs.

- [ ] 3. "Progress doesn't stand still".
At the late stage of the game, I will produce Ashlar Stone, Composite Lumber and other objects on CraftTables that will not consume calories. But I will make materials for them as a "caveman". I will spend calories. This system looks a little absurd. 
First, you will need to add the Hewn Logs (as example) recipe to a calorie-free CraftTable. Why can I do Lumber without calories but can't Hewn Logs? It isn't necessary to transfer all items, because they are actual only at the beginning. But the items that are used in the late stages of the game should be able to produce without calories, too.
Second, Even in the modern world, any assembly operation requires human effort. Yes, this process can be automated. But to make 100% assembly isn't possible on the assembly line. There will in any case be human intervention. Therefore, I suggest adding calories to all recipes such as cars, crafttables and etc. All items which are difficult to manufacture.

- [ ] 4. No Effect of food quality on calorie cost.
It can be done like as gaining experience. You need to allow 1000 units of labor to craft. Calorie Cost = 1000 / XP Nutrition. Then it will be important to use quality food. One caveat! it is important to use pure XPnutrition, without skill rate on the server.

- [ ] 5. Link calories to skill benefits. Decreases calorie consumption by 50% at 7 level It will be nice.

**Comment by johnkslg** [comment]
> if I could add calories to the whole craft immediately it would be very good.
1. That's the way it should work yes.  

> Add another button to add all calories at once. 
2. Reasonable, how about shift-click? And the tooltip on the labor button explains this.  And make shift click eat all of a given food stack that you can, too.  

3. You can have a recipe for hewn logs on a later-game table that doesnt require labor, this makes sense.

> No Effect of food quality on calorie cost.
4. Actually the food you eat stays in your stomach for 24 hours, so you are affected by the quality and nutrition.

**Comment by SlayksWood** [comment]
2. We can use Ctrl-click as x10 or x5 Calorie (500/250) and shift-click to full labor.
4. Food affects me 24 hours, but it still doesn't mean anything.
As I understand it, first of all, this should increase the demand for farmers and cooks. Only if you don't introduce the effect of food quality on labor is it will be limited by cooking at campfire. If you will eat better food Your product will be more expensive. What makes you in the end eat less quality food. Therefore, linking labor with food quality (nutrition experience coefficient) we can increase the possibility of eating better food.

**Comment by johnkslg** [comment]
It is linked though, the food you eat affects you for 24 hours regardless of if you use all your calories / eat more (its been digested)
