### ISSUE TITLE
(Linux) Tomatoes and potentially other plants not rendering

### ISSUE THREAD

**Issue by sashapony** [StrangeLoopGames/EcoIssues#13225]
I just got the game and discovered quickly that Tomatoes and maybe other plants do not render on the linux client. while they do exist in the world and if i happen to be lucky enough to find one, i do get the option to press e to harvest but the plant im looking at litterally cannot be seen. while hosting a linux server and having a windows player come look at the same plant i was.. they were able to see the tomato just fine and that led me to believe this to be a linux graphical bug. With help by Pam from the discord server we also came to that conclusion together that it is a bug

**Comment by SlayksWood** [comment]
merged to #13226
