### ISSUE TITLE
my eco for mac will not start and i dont know what to do. i opend my eco and it took me to the page and it kicked me out plase help. my version is 8.3.0

### ISSUE THREAD

**Issue by aesopPT** [StrangeLoopGames/EcoIssues#13228]

**Comment by beastyn** [comment]
Thank you for your report. Can you provide additional information? 
1. How did you open ECO
2. What page did you see? Please, provide screenshots.

**Comment by aesopPT** [comment]
i opened it by downloading the mac version of Eco and unzipping the file then opening it
i would give a screenshot but it closes to quickly to take one
the furthest i ever gotten in is all black with a tree logo in the bottom left corner

**Comment by SlayksWood** [comment]
Mac support will be improved with 0.9.0 release. If you still have this problem, please reopen.
