### ISSUE TITLE
USER ISSUE: No Servers

### ISSUE THREAD

**Issue by gustable** [StrangeLoopGames/EcoIssues#13224]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. Install ECO
2. Play ECO
3. Look for servers
4. See no Servers

**Expected behavior:**
Shown me a list of servers

**Actual behavior:**
TImeout

**Do you have mods installed? Does issue happen when no mods are installed?:**
TImeout

**Comment by SlayksWood** [comment]
1. Can you provide some screenshots?
2. Can you provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Can you try to connect to official servers (Sea Otter and White Tigger) and provide log files? You can find them in Your Worlds (Official Test Servers).
4. Do you have Firewall or Antivirus enabled?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the 0.8.3.0 or you had it before?

**Comment by gustable** [comment]
No luck connecting to official servers.

Firewall has given permission to ECO.

Steam, WIN10, Intel i7, Nvidia 1030, 1GbSSD

Encountered issue only recently after update.

[image: image.png]

**Comment by SlayksWood** [comment]
1. I can't see you screenshot. Can you upload srcreenshot to providers that provide free accounts are: [OneDrive](https://onedrive.live.com/), [Google Drive](https://www.google.com/drive/), and [Dropbox](https://www.dropbox.com/individual)
2. Can you provide log files?
    Open an explorer window
    Paste this into the address bar:  `%LOCALAPPDATA%Low/Strange Loop Games/Eco`
    and press enter
    Drag "Player.log" and "Player-prev.log" into the issue text box to upload to github

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
