### ISSUE TITLE
USER ISSUE: Low FPS on I7-4790K and GTX 1080ti

### ISSUE THREAD

**Issue by MrYoshii** [StrangeLoopGames/EcoIssues#13227]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
After a longer playing time the FPS become less and less. Partially below 25 FPS

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by SlayksWood** [comment]
merged to #11248
