### ISSUE TITLE
USER ISSUE: Error when using steam family

### ISSUE THREAD

**Issue by Crafter213** [StrangeLoopGames/EcoIssues#13222]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. Share access to steam games with the family share function
2. Let anybody else login

**Expected behavior:**
The game should work, as this is intended by Steam.

**Actual behavior:**
Error: User does not own Eco (or something like that)

**Do you have mods installed? Does issue happen when no mods are installed?:**
Error: User does not own Eco (or something like that)

**Comment by WeaselDog** [comment]
I suggest to a tag on Steam that says "Requires agreement to a 3-rd party EULA: [ECO EULA] and in the EULA it says you only get one SLG account per Steam purchase.

**Comment by SlayksWood** [comment]
@Crafter213 This notification will be added in 0.9.0
![image](https://user-images.githubusercontent.com/45708377/65864363-6b773300-e37a-11e9-9c4e-af9bbd08d6e3.png)

**Comment by Crafter213** [comment]
You definitely need to put a big information on the steam shop. Everything else is messing around with your users.
What about people who buy the game together? It makes sense, so everybody has to pay only half the price (but can play only half the time of course).

So why do you not allow family sharing? Because of that stupid old bug where the shared game could be transformed to a owned one? I've read about it when I googled my error.

Please, do not make Eco bad because of that. Instead, go and fix that bug.
