### ISSUE TITLE
export hosed world and getting error: "File does not exists."

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13229]
Hey, this teacher is trying to export world and getting error: "File does not exists."
ecogamingclub
c1b5dd97525446fa82fd79e2c58ef953

I see the files on s3 bucket. In the hosted-worlds-backups-us-west-1 bucket
Can't seem to download from there, unless i download each file individually.

**Comment by mirasrael** [comment]
Seems like a problem on Accounts Site side.

**Comment by rainfarmer** [comment]
resolved
