### ISSUE TITLE
[8.3] High Memory Usage with Laws

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13237]
We have the following Laws:
![grafik](https://user-images.githubusercontent.com/37456949/66076431-15fb7b80-e55e-11e9-8d27-350bd3599a61.png)
![grafik](https://user-images.githubusercontent.com/37456949/66076455-1f84e380-e55e-11e9-9630-5ef745b90545.png)
and a few more

This seem like this then:
![grafik](https://user-images.githubusercontent.com/37456949/66076632-86a29800-e55e-11e9-9319-5159ca9dc045.png)
with many more entries and Server has to calculate everything

When many People are crafting or Place Streets the Server have a High useage on Memory and the Red Plug comes.

Don´t know whether that has anything to do with the LiteDb

**Comment by D3nnis3n** [comment]
Law System will change completely in 9.0, therefore we won't address this issue in specific anymore. Even if it's a litedb issue, there is another issue open for that - but that's a long-term change anyway.
