### ISSUE TITLE
Accounts: Reset password flaws

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13231]
1. Add possibility to double enter password or see password. Because you can make a mistake when entering the password. Something like that:
![image](https://user-images.githubusercontent.com/45708377/65942554-303a3a00-e436-11e9-8ac3-2d82e283eb3e.png)
2. Make password recovery links temporary. Today I was able to recover the password using the link dated January 19, 2019. It's not very safe.
3. Cyrillic and  some special symbols don't processed in Email
![image](https://user-images.githubusercontent.com/45708377/65943318-d9cdfb00-e437-11e9-9fa6-e3328eea2d93.png)
4. If you enter as Email only "Space" you will be redirected to Account Login and write "reset instructions sent"
![image](https://user-images.githubusercontent.com/45708377/65943596-801a0080-e438-11e9-90e4-0a9c0bc87b8d.png)

**Comment by rainfarmer** [comment]
Also some users report that password reset link sent to email does not work.
It works in my tests, but see if you can figure out why it doesnt work sometimes or for some users.

**Comment by denysaw** [comment]
Done. Could be tested on developland. Also added password weakness check (same as on sign up) during reset, successful pass change notification and more.
