### ISSUE TITLE
Change recipes to have specialized labor.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13238]
With the labor-based crafting system, we can now allow anyone to create a work order regardless of the skills they have, but then only a worked with the needed skills can apply the labor.
- Remove the check for the required skill on recipes in order to start a work order.
- If a user tries to start a craft order requiring a skill they dont have, popup a ConfirmBox that asks 'You don't have <skill X>, so someone else will need to perform the labor on this work order. Do you still want to start it?'
- If a user tries to perform labor on a craft project they dont have the needed skill for, pop up an error explaining what they need.
- Turn the labor-needed-highlight (that white ring) to light-red when they dont have the needed skill, so the user knows labor is needed but they cant apply it.

Also as part of this task, add calorie requirements to all recipes that need it.  For powered stuff that still requires skilled labor, we will need to make at least a small calorie requirement, so that the skill requirement stays around.

**Comment by beastyn** [comment]
Not everything ready

**Comment by Hakuhonoo** [comment]
Test this, I guess it's done already.
If not - specify what is not, please.

**Comment by elfl0rd** [comment]
I don't understand why this is necessary, bonus from the specialty will not get such an assignment.
The resources will be spent as "without specialty".

**Comment by beastyn** [comment]
@Hakuhonoo I don't see that it works like its intended
I don't have Butchery skill and I can't place the order.
![bandicam 2019-12-03 14-01-43-581](https://user-images.githubusercontent.com/27898520/70035829-74cc8800-15d5-11ea-9779-6bf620288d3a.jpg)
@johnkslg  @craig-jong 
What is a benefit from placing an order when you don't have a skill? It still will work without bonuses even if someone add a labor for it.

**Comment by Hakuhonoo** [comment]
@beastyn It is intended behavior. You can place order even if you don't have a skill for it if there is a labor cost for it. This will allow other people make a work for you, someone who have the skill.
But if you don't have right skill and recipe doesn't require a labor - then you cannot order it.

**Comment by elfl0rd** [comment]
It's a very strange and confusing process.
Besides, I still don't understand what the benefit to the owner is.

**Comment by SlayksWood** [comment]
I add craft without Butchery. Ican't add Labor, but I don't see why? Need tooltip or some notification.
![image](https://user-images.githubusercontent.com/45708377/71169863-ff1a1a80-226a-11ea-8bbd-5d5c13f7d910.png)

**Comment by Hakuhonoo** [comment]
Tooltip added in https://github.com/StrangeLoopGames/Eco/pull/5539
