### ISSUE TITLE
[master-preview] Tool bench glitch with repair

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13232]
Step to reproduce:
- reconnect to server
- open repair tab. It will be empty.
![image](https://user-images.githubusercontent.com/45708377/65953645-15bf8b00-e44d-11e9-84a5-2fa6b8557f27.png)
- select another tab
- select repair tab. You can repair tool, but it also display Bank account.
![image](https://user-images.githubusercontent.com/45708377/65953724-3ab3fe00-e44d-11e9-8599-51bf7b7a1424.png)

**Comment by Conchipedia** [comment]
still in 1377

**Comment by Conchipedia** [comment]
still happens in 1385
