### ISSUE TITLE
Labor feedback 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13235]
![image](https://user-images.githubusercontent.com/3536496/66071225-9fcc2a00-e507-11e9-804f-f8e9ba7ed34a.png)
- [x] I started two work orders, the second didnt seem to appear, just had a little blank icon below it.
- [ ] When labor is required, make that outer ring pulse (use PulseObject component). This outer ring should also disappear when there is no labor required.  
Players will come to recognize 'white border means I need to go apply labor', and we'll later make work parties where you go to people's workbenches and apply labor. 
![image](https://user-images.githubusercontent.com/3536496/66078276-8e3e4e80-e516-11e9-964c-91b0c5a4e0cd.png)
 - [x] This icon isnt quite right, it depicts someone mining, which is a totally different activity than crafting.  Can we change it to someone building something, ideally at a workbench?  (If we want to get fancy we can have separate ones for cooking, etc.)

**Expansion sequence**
![image](https://user-images.githubusercontent.com/3536496/66071421-f6396880-e507-11e9-98e0-b1dabb4fc1e8.png)
- [x] The green circle is aliased when you zoom in.  It should look smooth
- [x] When you apply labor, you should see the additional labor fill up as a different color (yellow, to highlight it) on top of the existing green bar. Then the green bar will lerp to cover the highlight. This is to indicate how much youve added. If you click multiple times, it should keep adding to this highlighted bar, waiting until there havent been clicks before lerping the green bar.
- [x] Give a nice shaded background that covers the text. Currently the text overlaps the game which makes it look busy.  Disable the pop-up notification behind it ('press right mouse to add labor') while the sequence is running.
- [x] The laboring-animation looks cool, but should only be shown when youre appplying labor, during the labor sequence. On the recipe listing, it should just be a static image. 
- [x] Add more elements to the sequence:
- Wait until the marker is zoomed in before starting the sequence counting up the calories added
- Add a '+50 Calories of Labor' each time you right click that fades in and floats up, then fades out. These should stack if you click rapidly.
- When the max labor is reached, pop up a similar notice 'Labor Complete' in a different color text

**World Marker**
![image](https://user-images.githubusercontent.com/3536496/66077134-31419900-e514-11e9-9fc9-a6daac8d6ef9.png)
- [ ] The in-world work order and the docked work order look quite different now. Can they made to look visually the same?  They should both have the labor highlight, etc.  Ideally theyre the same exact asset, perhaps with that top attach-piece missing for the in-world one.
The in-game one has a big space for writing, but really thats communicated by the glowing border. I think that space should be taken by the icon.

**Comment by Hakuhonoo** [comment]
> When labor is required, make that outer ring pulse (use PulseObject component). This outer ring should also disappear when there is no labor required.
Players will come to recognize 'white border means I need to go apply labor', and we'll later make work parties where you go to people's workbenches and apply labor.

But outer ring is for time, not labor. I suppose you've meant inner green?

**Comment by Hakuhonoo** [comment]
> When you apply labor, you should see the additional labor fill up as a different color (yellow, to highlight it) on top of the existing green bar. Then the green bar will lerp to cover the highlight. This is to indicate how much youve added. If you click multiple times, it should keep adding to this highlighted bar, waiting until there havent been clicks before lerping the green bar.

Did by more greenish color, coz yellow is resources
