### ISSUE TITLE
[master-preview] Offset Table position

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13234]
![image](https://user-images.githubusercontent.com/45708377/66041554-ca77ac00-e522-11e9-8df2-59633eaf2c43.png)
![image](https://user-images.githubusercontent.com/45708377/66041564-cfd4f680-e522-11e9-83de-f2d56d5916c8.png)

**Comment by keegan-o** [comment]
fixed in staging for 9.0
