### ISSUE TITLE
Select staging builds that are for public release

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13230]
![image](https://user-images.githubusercontent.com/45708377/65938527-de8cb200-e42b-11e9-8b6f-c73f6aa73247.png)
1. Game version is incorrect.
2. Now you can take staging from bleeding_edge_staging_night. Night version generate automatically every day. 
3. Now you can take release-preview from release_preview - Beta 8.2.0 (incorrect version in steam) 
4. Mixed up descriptions: Staging - unstable version. Release-preview - test the next version.

**Comment by rainfarmer** [comment]
1. develop server has outdated db, so expected behavior
@mirasrael do we want to use those version for public ^

**Comment by mirasrael** [comment]
Yes, but usually only before releases. So probably good to have some logic to hide these versions when necessary.

**Comment by denysaw** [comment]
1. Updated `develop` and `staging` to have latest versions from prod.
2, 3: can someone gimme endpoints where could I retrieve those versions? =)
4. Can you tell me precisely which version name replace with which text? :) Thanx

**Comment by rainfarmer** [comment]
Jeff: during build process, builds are uploaded to hosted worlds docker and to S3 for website.

We do want all build going to hosted worlds docker.
And just public builds to S3

Eugene:
we can just upload staging to its own bucket
and set acl to authenticate the user first via its aws token
this way if we want to let people access certain staging version acl on that archive can be set to public access
others will stay private

Simon:
or just generate authenticated links

**Comment by j3fffff** [comment]
doesnt seem like we want to offer stable staging verison, so hid from website
