### ISSUE TITLE
[master-preview] Craft: quantity for child recipes

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13244]
How do I see quantity for items to in the child recipes?
1. I want to craft 3 hardwood hewn logs.
2. I put 3 for hewn log recipe
![bandicam 2019-10-03 13-07-18-231](https://user-images.githubusercontent.com/27898520/66110976-4df7d280-e5e1-11e9-9747-4a3a882a0c77.jpg)
3. I open gear for picking Hardwood recipe
![bandicam 2019-10-03 13-07-37-224](https://user-images.githubusercontent.com/27898520/66111251-eb530680-e5e1-11e9-85a6-97d9d9a03f0c.jpg)
4. I can't see how many items were selected as the number is 1 again.

We need to make quantity selection in the child recipe UI or do not reset the number with child recipe UI opening (I prefer a separate field)

**Comment by elfl0rd** [comment]
> We need to make quantity selection in the child recipe UI

Agree, like this
![изображение](https://user-images.githubusercontent.com/4980243/66324267-cc2fde00-e92d-11e9-9f8c-9269d850c0dd.png)

**Comment by SlayksWood** [comment]
merged with #14333 and closed for same reason.
