### ISSUE TITLE
[master-preview] Can delete own personal account

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13245]
![image](https://user-images.githubusercontent.com/45708377/66120952-bb593280-e5e4-11e9-9bfc-51aecf780879.png)

**Comment by WeaselDog** [comment]
I believe there is an issue with Special Accounts because there should already be a check to prevent deleting personal accounts. Can someone try to delete the treasury account? I can't get it to spawn.
