### ISSUE TITLE
[master-preview] Placing Block already in the placed Block

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13243]
![image](https://user-images.githubusercontent.com/45708377/66109570-a329e900-e5cd-11e9-8ba5-e89b2df7f90a.png)
![image](https://user-images.githubusercontent.com/45708377/66109706-ebe1a200-e5cd-11e9-8d49-4af24a272724.png)

**Comment by redwyre** [comment]
What happened?

**Comment by SlayksWood** [comment]
ShadowPlacement is already located in an existing block.

**Comment by SlayksWood** [comment]
Still happening with another placement
![image](https://user-images.githubusercontent.com/45708377/68192398-4e113680-ffc2-11e9-9ae3-e7bb205c925c.png)

**Comment by beastyn** [comment]
recheck

**Comment by redwyre** [comment]
Not really sure, probably just a case in the `InteractionManager` that isn't being handled properly

**Comment by SlayksWood** [comment]
@StanKryvenko 
Check it please too, after fixing building

**Comment by SlayksWood** [comment]
Seems fixed.
