### ISSUE TITLE
Clambering too aggressive

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1324]
If I press forward towards a store, I climb up and over the counter like I'm gonna rob the place.

**Comment by NafenX** [comment]
Agreed, when I started playing the game I put the clambering option on and simply loved it but when woodcutting (especially with your cart nearby too) you'd just end up climbing up all over everything and not interacting with what you meant to use a tool on. Much easier to turn clambering off and just jump manually
