### ISSUE TITLE
USER ISSUE: campfire disappears

### ISSUE THREAD

**Issue by ckaroun** [StrangeLoopGames/EcoIssues#13240]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
I just started the game and finished all the initial tutorials (those that pop up automatically (up to skills level up) and also for mining and shoveling. I mine and process stone and then build a campfire with the work bench. IT completes building and then when I go to pick it up from the tent or stockpile it disappears completely	

**Expected behavior:**
I am new but I thought it would go into my inventory so that I could place it somewhere. 

**Actual behavior:**
It never goes in my inventory. No sign of it on the minimap. IN the list of existing campfires it also doesn't show up.

**Do you have mods installed? Does issue happen when no mods are installed?:**
It never goes in my inventory. No sign of it on the minimap. IN the list of existing campfires it also doesn't show up.

**Comment by SlayksWood** [comment]
@ckaroun 
Check for a campfire on the toolbar. If you took him with LMB, then most likely he will there.

**Comment by ckaroun** [comment]
Wow, thanks for the quick reply!

I expected the campfire to be on the toolbar at the bottom of my screen after I took it from the stockpile/tent, but both times it wasn't (when I created it at the workbench). After I submitted this bug I created a campfire with the tent and it successfully went into my toolbar and I was able to place it and use it. Still no sign of the other two campfires even though I got a confirmation that they were complete in the chat box and I saw them in the stockpile. Anyways, just hopes this helps debug in the future if others are having the same problem.

 Amazing game by the way.

**Comment by ckaroun** [comment]
I am having a similar problem as before with items disappearing when they should be going to my toolbar but while harvesting plants ( plant fibers, pineapple, heart of palm). It also seems to be accompanied by a lag between me completing an action ( i.e. picking up a fern or taking a pineapple) and the animation playing.  This has been happening for 2 days now. I turned down the graphics couple days ago and frame rate is good now.  I think it must be a network problem. Yet my internet has a ping of 9 ms, download speed of 60 mb/s and upload speed of 6 mb/s. Could it be the server I am on? I should be gaining developer's access soon so I can try to investigate more. Let me know if this is an existing issue or if I should open another issue. This seems more important of a bug than I originally thought.
