### ISSUE TITLE
[master-preview] Double Error notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13241]
Step to reproduce:
- take Land Claim Stake. Don't have Land Claim Papers in inventory.
- try to claim Land.
![image](https://user-images.githubusercontent.com/45708377/66102142-f42fe200-e5b9-11e9-9000-f0400204112c.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/66109456-580fd600-e5cd-11e9-929e-41f11eea6be2.png)

**Comment by WeaselDog** [comment]
In both of these examples, the double error notification is fixed but the error message still appears twice in chat.
