### ISSUE TITLE
Master: "fuel" dont know about new things.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13258]
![изображение](https://user-images.githubusercontent.com/4980243/66248179-7b9d6280-e72c-11e9-92a9-a10c8a47488b.png)

**Comment by elfl0rd** [comment]
Maybe something like "Accepts {flammable}"?
Flammable
-Logs
-Coal
-etc...

Or
Maybe something like "Accepts {log}, {coal}, {Another flammables}"?
{Log} - standart new log list.
{Coal} - contain charcoal and coal (and maybe more, in future...
{Another flammables} - boards, arrows, housing items, clothing... etc.

**Comment by Nicolausi113** [comment]
...please add Pulp too (and possibly plant fibers)

**Comment by SlayksWood** [comment]
can add tagged fuel items. Something like: Wood fuel, Coal Fuel, Oil Fuel

**Comment by elfl0rd** [comment]
> can add tagged fuel items. Something like: Wood fuel, Coal Fuel, Oil Fuel

I think we need another type of things (as fuel for campfires and low-power stoves) including furniture, arrows, clothes, etc.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/68470386-06421780-022d-11ea-8333-d2c4585f6fec.png)
But you forgot about Board and Arrow. And may be add tagged Pitch:
![image](https://user-images.githubusercontent.com/45708377/68470592-68028180-022d-11ea-9abd-aa9d8eeeb990.png)
And also missing icons for tagged items in Fuel.It will be nice to have all wooden furniture as Fuel in future.

**Comment by elfl0rd** [comment]
And as suggestion - all wooden furniture :D 
doors\tables, etc.
