### ISSUE TITLE
Master: Add all new Logs and Constructed Materials to Falls List

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13255]
(Oak log on screenshot)
![изображение](https://user-images.githubusercontent.com/4980243/66248056-214fd200-e72b-11e9-8260-77a6f0318a8b.png)

**Comment by SlayksWood** [comment]
same in 8.3.0. You can't place new logs in air without support (for example another log at same height).
Seems as intended behavior.
8.3.0:
![image](https://user-images.githubusercontent.com/45708377/66292371-d5e52180-e8ec-11e9-8fad-30e28efa5e5c.png)

**Comment by elfl0rd** [comment]
in 0.8.3 you CANT place log in air.
in master - you CAN.

**Comment by SlayksWood** [comment]
Also see #9170.
