### ISSUE TITLE
If/then cleanup 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13254]
Updates: do what Kirill says below

**Comment by SlayksWood** [comment]
Actual:

- [ ] Change the trash cans to all be minuses.

- [ ] Figure out good positions for these, some of them are confusing and overlap buttons, like in this case it overlaps the advanced property button. Ideally it should highlight the thing thats going to get deleted when you mouse over the delete button.

- [ ] Make a confirmation on the delete button if there's something being deleted (ie, its not null)
