### ISSUE TITLE
[0.8.3] Oil Drilling in a Mine

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13259]
This doesn't cause any game play issues, but it seems really strange:
![OilMine](https://user-images.githubusercontent.com/47330823/66259623-e91ab480-e767-11e9-80a2-33f7e16bbbe4.png)

**Comment by elfl0rd** [comment]
why not?
But ofc, i think this machinery need 10+ SOLID surface under for working.

**Comment by WeaselDog** [comment]
I do not mind if the issue is closed, but this is definition of a pumpjack: "A pumpjack is the overground drive for a reciprocating piston pump in an oil well."  By definition it is above ground. It does not make sense for them to be underground or to pump directly into stone.

**Comment by Sekor2600** [comment]
Is this not the Same Problem with the windturbine / Solarpanel, Windmill and Waterwheel? Where you can place they in the Mine or Air(Waterwheel)

**Comment by elfl0rd** [comment]
In fact, I don't see any physical reasons why a drill rig can't work in a mine.
At the same time, I find that the opportunity to put it on a 1-block depth platform... It looks ugly.

And I agree, we need to rework the wind turbines\mills and the water wheel.
