### ISSUE TITLE
Update textmeshpro to fix prefab variant nutiness

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13253]
Unity detects overrides in textmeshpro components even when nothing's changed, but apparently this is fixed in latest version of plugin. 
https://issuetracker.unity3d.com/issues/text-mesh-pro-components-inside-prefabs-remain-in-the-overrides-drop-down-menu-even-after-applying-their-changes

**Comment by beastyn** [comment]
Updated to 2.1.0
