### ISSUE TITLE
Master: crafting "hardwood hewn log" provide "standart" hewn log.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13256]
(also crafting hardwood\softwood hewnlogs is not require calories)

**Comment by SlayksWood** [comment]
Checked on 0.9.0 staging-1206. Wasn't able to reproduce, seems fixed, but have another issue. Calories will add in future.

**Comment by Deantwo** [comment]
This is still an issue at Carpentry table.

Version: 0.9.0.0 staging-1278.
