### ISSUE TITLE
[master-preview] Client can't be built

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13264]
After this one https://github.com/StrangeLoopGames/Eco/pull/5052/commits/487b3921a763dd6e49d6335822f23668d12e850a

client can't be built with error
Step Compile scripts  Depth: 1 Time: 00:00:28.8135835
E: Assets\Scripts\Utils\UnityUtils.cs(86,16): error CS0103: The name 'PrefabUtility' does not exist in the current context
E: Assets\Scripts\Utils\UnityUtils.cs(86,56): error CS0103: The name 'PrefabAssetType' does not exist in the current context
E: Error building Player because scripts had compiler errors

But "play" work in the Unity as PrefabUtility works in the UnityEditor namespace.

**Comment by johnkslg** [comment]
Fixed
