### ISSUE TITLE
USER ISSUE: Items vanishing

### ISSUE THREAD

**Issue by TootleBrush** [StrangeLoopGames/EcoIssues#13260]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
when servers are resetting, if you have placed, gathered or done anything with items or recourses right before the server resets.
they vanish.
So plan a reset of server, and gather right up toward it, or place a item.

**Expected behavior:**
That the recourse or item would either be gathered or placed and stay in place or in inventory

**Actual behavior:**
They just stop being, and vanish.

**Do you have mods installed? Does issue happen when no mods are installed?:**
They just stop being, and vanish.

**Comment by SlayksWood** [comment]
@TootleBrush 
This can happen if the server reboots incorrectly. Do you play on your server? Or on someone else’s?

**Comment by TootleBrush** [comment]
On someone elses server.
And ots unmodded etc.
Just plain vanilla game

man. 7. okt. 2019 09.32 skrev Kirill <notifications@github.com>:

**Comment by Nicolausi113** [comment]
Possibly “Flush To Disk” or “Start Backup” should be done before killing server process. There are no means for soft-reset.

**Comment by D3nnis3n** [comment]
That's not a bug. The server needs to exited gracefully or /save needs to be executed before killing the process, so this is a misconfiguration, not a bug.
