### ISSUE TITLE
Builder handling of SolidWorldObjectBlocks wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1326]
![image](https://cloud.githubusercontent.com/assets/3536496/24638396/e9e38938-189c-11e7-97fe-ee56cc781fe0.png)
This empty space beneath the door has a block, but its not rendering because there's a SolidWorldObjectBlock above it

**Comment by metachronism** [comment]
I dont think this is a builder problem, as the default cube does not use a builder at all

**Comment by metachronism** [comment]
this is working as intended actually
