### ISSUE TITLE
[Craft] Position while moving projects are misaligned

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13268]
![изображение](https://user-images.githubusercontent.com/4980243/66324729-abb45380-e92e-11e9-89f4-ddc9f5baa2e9.png)
As result, you can only move projects to end of the list, but moving in order is terrible.

**Comment by Hakuhonoo** [comment]
![image](https://user-images.githubusercontent.com/11686660/71447920-d350d600-273d-11ea-98dd-cf3b51347da8.png)
