### ISSUE TITLE
[Craft] Not full items out of crafting

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13265]
You don't get all the items listed in the recipe.

1. Order Butcher Animal with Bighorn carcass
![bandicam 2019-10-07 17-09-29-035](https://user-images.githubusercontent.com/27898520/66313496-e9fc4380-e92b-11e9-8222-2da46366cfda.jpg)

2. It says that I will get 6 Raw meat and one Leather Hide

3. But after order is finished I've got only one Raw Meat.
![bandicam 2019-10-07 17-09-44-736](https://user-images.githubusercontent.com/27898520/66313492-e7015300-e92b-11e9-8a30-0775a6a39630.jpg)

**Comment by beastyn** [comment]
and like that (i suppose it sees parent recipe result from tech tree)
![unknown (21)](https://user-images.githubusercontent.com/27898520/68002680-cfe42580-fc8b-11e9-8021-2c9ce05d3cf5.png)

**Comment by craig-jong** [comment]
I believe this should be fixed after a change earlier. I'll double check.
