### ISSUE TITLE
[master-preview] Tooltip differ for tagged items.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13261]
![image](https://user-images.githubusercontent.com/45708377/66293217-d7174e00-e8ee-11e9-96c3-c7516540f64e.png)
1. Missing Ecopedia Link in tagged items tooltip
2. Missing Skill benefits in just item tooltip.
3. Missing "Used in:" string in tooltip for tagged items and non-carry items (blue). In 8.3.0:
![image](https://user-images.githubusercontent.com/45708377/66293359-1e054380-e8ef-11e9-8f6f-0b0410f1141d.png)

**Comment by SlayksWood** [comment]
Skill benefit is lost after changes, but should I see Used in?
![image](https://user-images.githubusercontent.com/45708377/75240385-5097d600-57d5-11ea-9975-f39f9b9dcc6a.png)
![image](https://user-images.githubusercontent.com/45708377/75240391-5392c680-57d5-11ea-8ad1-58708b5da7db.png)

**Comment by johnkslg** [comment]
@Quadbro also related to displaying skill benefits, passing your way

**Comment by johnkslg** [comment]
@Quadbro also related to displaying skill benefits, passing your way

**Comment by SlayksWood** [comment]
Seems okay for me now:
![image](https://user-images.githubusercontent.com/45708377/79329709-f25bb980-7f20-11ea-9275-1b70337b9309.png)
