### ISSUE TITLE
[master-preview] Report a Bug UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13263]
![image](https://user-images.githubusercontent.com/45708377/66297750-ef8c6600-e8f8-11e9-9db3-a6c5ebd8bc81.png)

**Comment by beastyn** [comment]
still briken
![bandicam 2019-11-29 11-30-31-765](https://user-images.githubusercontent.com/27898520/69848344-aecb2080-129b-11ea-8c6a-7f65578b6f38.jpg)

**Comment by beastyn** [comment]
still the same
