### ISSUE TITLE
[master-preview] Civics: can't calculate percent from currency wealth

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13275]
I need to calculate tax as 10 percent from particular currency amount for all the players.
0.1* Coins_amout_for_player

But when Im trying to count percent from wealth I need to point a User. 
![bandicam 2019-10-08 12-51-44-496](https://user-images.githubusercontent.com/27898520/66377407-f84d6c80-e9ca-11e9-8d34-4006224f1101.jpg)

**Comment by johnkslg** [comment]
I've added a new option, currency in circulation:
![image](https://user-images.githubusercontent.com/3536496/69012104-d975ba80-0926-11ea-9c64-ea4fd912b1d6.png)

![image](https://user-images.githubusercontent.com/3536496/69012098-c4009080-0926-11ea-90af-cfcc97e97344.png)

**Comment by D3nnis3n** [comment]
What she probably meant was the wealth tax issue Weasel and me described here: https://github.com/StrangeLoopGames/EcoIssues/issues/13778
