### ISSUE TITLE
Add persistent data for items/objects that need it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13279]
See https://github.com/StrangeLoopGames/Eco/pull/5079 which added support for PersistentItemData, data stored and recreated as objects go from items -> world objects and back again.

Add support for other components that need it:

- [x] Stores

- [x] Real Estate Desks

- [x] Item Distribution Station

- [x] Credit Components

- [x] Contract board?

Others @D3nnis3n 

Setup migration so existing objects will continue to work (pasting how to do this for stores below).

Also, there's a limitation in this system as its currently implemented that will need to be improved: Right now world object only stores a single PersistentData for all its components, no matter how many there are. 
- [x] This will need to be extended to support multiple components having persistent data. 

- [x] Vehicles?

**Comment by johnkslg** [comment]
Migration example for stores:
```// first add data migration for Store class
this.AddDataMigration("StoreClassName", dm =>
            {
               // get data inputs for migrated members
                var sellOffers = dm.Member("RawSellOffers");
                var buyOffers = dm.Member("RawBuyOffers");
                // add placeholder for SubObject member (there're no currently a way to add a member with specific type, so using a kind of hack, but easy to add). Skip if you already have SubObject
                dm.AddMember("SubObject", () => "");
                // change member type to the target type
                dm.ChangeMemberSchemaType("SubObject", SchemaUtils.GetClassSchemaType("SubObjectType"));
                // add migration for new SubObject member
                dm.AddMemberDataMigration("SubObject", soDm =>
                {
                    // add members to SubOject and pass member data input from parent object as dependency, then return dependency value as added member value (in binary form)
                    soDm.AddMember("RawSellOffers", new IDataInput[] { sellOffers }, deps => deps[0]);
                    soDm.AddMember("RawBuyOffers", new IDataInput[] { buyOffers }, deps => deps[0]);
                });
            });```

**Comment by elfl0rd** [comment]
mmm, vechicles!
Save owner, autorized users, text, fuel (and pollution) stats...

**Comment by D3nnis3n** [comment]
In that case the data would need to reset when the item is sold - noone wants to buy something that still has authorisation on it, probably without even noticing.

**Comment by elfl0rd** [comment]
> 
> 
> In that case the data would need to reset when the item is sold - noone wants to buy something that still has authorisation on it, probably without even noticing.

I think only authorization data. (like deed trading!)
Text, name, fuel and pollution statistics need to be saved.

**Comment by D3nnis3n** [comment]
Ye, thats fine.

**Comment by johnkslg** [comment]
Change of plans: dont worry about migration.

**Comment by elfl0rd** [comment]
@johnkslg what about persistent storage for inserted module?
e.g. steam tractor or upgrade modules for work tables.

**Comment by elfl0rd** [comment]
Hmm, i ask again about modules in persistent storage.
As i think it's usefull if we can move workbenches without detaching module.

But yes, "erasing data" should detach module to the inventory, not destroy it.

**Comment by mirasrael** [comment]
I don't like the idea to put modules into persistent data.

1. It allows you to magically compact items (you have same weight table with the module and it only takes one slot instead of two).
2. You should care about workflows when data erased or item sold to other player (with auto-erase).

We should avoid adding container-like behavior to persistence storage.

**Comment by elfl0rd** [comment]
Vehicles still not contain persistent storage
