### ISSUE TITLE
[master-preview] Civics: can't check spec for the level

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13273]
For some laws we need to check the level for a speciality. For now we can just check if it exists or not (seems like its checking learned state even if its level 0).
![bandicam 2019-10-08 11-54-49-563](https://user-images.githubusercontent.com/27898520/66375373-b3bfd200-e9c6-11e9-8617-a2dbce4bc06f.jpg)

So, we need in condition something like:
if Smelting has level 1

**Comment by johnkslg** [comment]
You can, it was an adavanced param.
I've made it a normal parma.
