### ISSUE TITLE
[master-preview] Civics: laws UI are quite slow in opening 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13277]
Laws UI can open pretty long.
![law-delay](https://user-images.githubusercontent.com/27898520/66383645-d659e700-e9d6-11e9-86e5-ed3521837594.gif)
And court UI too.

**Comment by johnkslg** [comment]
They're pretty fast on mine, could it be other issues in the server slowing it down?  How is it on a default server? 
@olegshegai can you profile this

**Comment by johnkslg** [comment]
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/15297
