### ISSUE TITLE
[master-preview] Mint working and UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13271]
1. Doesn't take resourses to craft. So you can craft infinity money.
2. Small font of currency name
![image](https://user-images.githubusercontent.com/45708377/66374141-ff688080-e9b2-11e9-933e-fffeaded703f.png)
3. Currency report window size always open with this size:
![image](https://user-images.githubusercontent.com/45708377/66374470-c2e95480-e9b3-11e9-926f-fd27f9a0081b.png)

**Comment by beastyn** [comment]
2. Small font of currency name

still actual

**Comment by beastyn** [comment]
Yes, but Target account trying to run away from the bottom
![bandicam 2019-11-21 10-48-09-851](https://user-images.githubusercontent.com/27898520/69307512-a72ccb80-0c4c-11ea-8c3c-bfd67f802f06.jpg)

**Comment by beastyn** [comment]
Also can't change Target Account

**Comment by beastyn** [comment]
Still have
3.Currency report window size always open with this size (it is always small, even if I cange it):
![bandicam 2019-11-29 10-49-33-924](https://user-images.githubusercontent.com/27898520/69846483-f8b10800-1295-11ea-947e-dacf3cec9f69.jpg)

Also bank account should be called Target account.

Logic for target account was broken a little.
Should be like in 8,3
1. I have two accounts
![bandicam 2019-11-29 11-10-26-181](https://user-images.githubusercontent.com/27898520/69847636-82160980-1299-11ea-8a73-5c1045595bae.jpg)
2. I place a mint, make it for Everyone and place my second account as the default one
![bandicam 2019-11-29 11-12-04-122](https://user-images.githubusercontent.com/27898520/69847658-8e9a6200-1299-11ea-95e0-d0bb75e75a8c.jpg)
3. When someone try to use this mint, he could see his accounts and my defaulted account
![bandicam 2019-11-29 11-14-50-382](https://user-images.githubusercontent.com/27898520/69847663-95c17000-1299-11ea-80dd-8318cfc47e64.jpg)

For now other player won't see the account that was choosen by an owner, only owner personal account.
![bandicam 2019-11-29 11-25-11-996](https://user-images.githubusercontent.com/27898520/69848226-4a0fc600-129b-11ea-80f7-ed868e4a7e18.jpg)
![bandicam 2019-11-29 11-27-33-003](https://user-images.githubusercontent.com/27898520/69848230-4b40f300-129b-11ea-8a6b-82a475e4c408.jpg)

Also, selected account will reset to the default after reconnect, can be related to it.

**Comment by WeaselDog** [comment]
There is a different issue now. The target account list is blank so it will always mint into the account of the person who the person who places the mint:
![MintTargetAccount](https://user-images.githubusercontent.com/47330823/70006274-691f8980-1521-11ea-9565-27490f48232b.png)

**Comment by WeaselDog** [comment]
Many parts are fixed. Here is still what needs fixing from original report:

- When someone try to use the mint, he should see his accounts and the default account selected by the person who places the mint. Currently the person minting won't see the account that was chosen by the mint owner but instead the owner's personal account.
- The selected default account switches back to the owner's personal account after reconnecting
- UI Text "Target Account" was switched back to "Bank Account" in latest PR

**Comment by olegshegai** [comment]
For me it's currently crashing the client.
Seems like CoinsPerItem property in MintComponent on the server side doesn't have a setter.

**Comment by SlayksWood** [comment]
```
InvalidOperationException: Failed to parse result from bson with type: System.Void. Error: Cannot convert value: True to type: System.Void
  at Eco.Shared.Networking.RPCManager.HandleQueryResponse (Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at NetworkManager.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent (Eco.Shared.Networking.INetClient client, Eco.Shared.Networking.NetworkEvent netEvent, Eco.Shared.Serialization.BSONObject bson) [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.NetworkClient.TryReceivePacket () [0x00000] in <00000000000000000000000000000000>:0 
  at Eco.Shared.Networking.ClientPacketHandler.ReceiveWhile (Eco.Shared.Networking.NetworkClient client, System.Func`1[TResult] condition) [0x00000] in <00000000000000000000000000000000>:0 
  at FramePlanner.FramePlannerSystem.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.InternalUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystemGroup.OnUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Entities.ComponentSystem.InternalUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Unity.Entities.ComponentSystemGroup:OnUpdate()
Unity.Entities.ComponentSystem:InternalUpdate()
System.Threading.ThreadStart:Invoke()
 
(Filename: currently not available on il2cpp Line: -1)
```

**Comment by SlayksWood** [comment]
- [ ] 1. When you first open Mint you have "Amount to craft" = 0, should be 1.
![image](https://user-images.githubusercontent.com/45708377/72784301-8dead000-3c39-11ea-9f66-f5a4e29fec92.png)

- [ ] 2. The bank account is reset after renaming. Step to reproduce:
- open Mint and select "Craft Here" in Target Account account:
![image](https://user-images.githubusercontent.com/45708377/72784351-abb83500-3c39-11ea-9e66-a3f33a827465.png)
- go to bank and rename it:
![image](https://user-images.githubusercontent.com/45708377/72784389-c7234000-3c39-11ea-832b-5eac049bfadc.png)
- open MInt again:
![image](https://user-images.githubusercontent.com/45708377/72784402-cf7b7b00-3c39-11ea-96ef-954fddd00867.png)
- I have "Slayks Personal Account" in target bank, it should be "Craft here !!!!".

- [ ] 3. Sometimes Coins per item vissually reset to default. Step to reproduce:
- place Mint, change "Coins per item" = 1000.
- Craft 20 times.
- walking, placing another MInt... after 10 minutes. I have vissually "Coins per item" = 10:
![image](https://user-images.githubusercontent.com/45708377/72785485-69442780-3c3c-11ea-8156-c25cd81e2f59.png)

- [ ] 4. Another player see wrong default account. Step to reproduce:
- I place Mint and select default account for other players. I select "Craft here !!!!":
![image](https://user-images.githubusercontent.com/45708377/72784756-8d066e00-3c3a-11ea-8d7d-452534aa47b5.png)
- Another player (Anna) opens Mint and should see "Craft here !!!!" in list of bank account, but she see "Slayks Personal Account" instead it:
![bandicam_2020-01-21_12-27-13-183](https://user-images.githubusercontent.com/45708377/72785052-51b86f00-3c3b-11ea-857e-5bfee177609a.jpg)

- [ ] 5. Another player can't craft at my Mint:
- place Mint, claim territory and add "Everyone" to Mint Autorization.
- Another player (Anna) try to craft, she can't:
![bandicam_2020-01-21_12-28-30-274](https://user-images.githubusercontent.com/45708377/72785230-cbe8f380-3c3b-11ea-8b0d-31b3af693ae4.jpg)

- [ ] Player doesn't save his account choice after reconnect. Step to reproduce:
- select "Craft here !!!!":
![image](https://user-images.githubusercontent.com/45708377/72785703-de176180-3c3c-11ea-8e3d-6bbeac2ac193.png)
- reconnect and open Mint. I have my personal account, but should "Craft here !!!!":
![image](https://user-images.githubusercontent.com/45708377/72785765-fedfb700-3c3c-11ea-97c4-9e6137c0772e.png)

**Comment by SlayksWood** [comment]
- [ ] 7. Currency report window should save my settings

**Comment by SlayksWood** [comment]
Still have a little problem, but I will open a sepparate issue.
