### ISSUE TITLE
[9.0 master preview] Blank Menu

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13270]
![version](https://user-images.githubusercontent.com/25908592/66337052-ae1ea980-e93e-11e9-8910-7822b026c237.png)
![screeen](https://user-images.githubusercontent.com/25908592/66337054-ae1ea980-e93e-11e9-8dfa-26bea20a2afd.png)

Pressing buttons, clicking with mouse, nothing happens. Menu and news don't come up.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3698850/Player.log)

**Comment by beastyn** [comment]
@D3nnis3n 
Can you update on steam and look for this problem? If you have it, please attach you log.

**Comment by SlayksWood** [comment]
News is Missing 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3755393/Player.log)
![image](https://user-images.githubusercontent.com/45708377/67283327-27d89a80-f4dc-11e9-911a-20905c553a5b.png)

**Comment by gzatravkin** [comment]
News are not missing any longer

**Comment by gzatravkin** [comment]
Reopened for case in some investigation of empty menu is needed. Anyway as I see is not reproducible any longer

**Comment by beastyn** [comment]
Kirill doesn't have news. They are here sometimes, sometimes not

**Comment by beastyn** [comment]
Didn't see lately. Reopen if appears
