### ISSUE TITLE
[master-preview] Civics: Аccess to all bank accounts in Pay

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13284]
I should see all bank account
![image](https://user-images.githubusercontent.com/45708377/66457517-4325bd80-ea79-11e9-90a1-140b5cb73c47.png)

**Comment by johnkslg** [comment]
This is the source where the money comes from.  It only shows accounts you have access to take money out of, otherwise you could siphon money from accounts you don't own.  This seemed overpowered to me so I disallowed it.

**Comment by SlayksWood** [comment]
@johnkslg 
I couldn't reselect Treasury second time. But now I can't select my account I see all others account without mine:
![image](https://user-images.githubusercontent.com/45708377/69055489-ed9ce300-0a1e-11ea-89b6-6051f71c0054.png)
I should see my account and Treasury.

**Comment by WeaselDog** [comment]
I made a treasury and elected myself to a title with access to it. I can't select Treasury as a pay account. In addition, I can't select my non-personal bank accounts I don't have access to.

**Comment by johnkslg** [comment]
Now it only displays accounts tagged 'Government Accounts', which can be set by users with the Government Banking Privilige (assigned on elected titles) in the Bank object:

![image](https://user-images.githubusercontent.com/3536496/69384165-69da3500-0c70-11ea-8b4b-3122b3f158b3.png)
![image](https://user-images.githubusercontent.com/3536496/69383638-10bdd180-0c6f-11ea-8aeb-0d675eeb5aa5.png)

Treasury has this by default.

**Comment by beastyn** [comment]
Can try to work with that
