### ISSUE TITLE
Master: click on crossed profession exp marker does nothing.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13287]
Afaik, before completing tutorial clicking on this marker show error message.
But in current state - nothing happens.
![3](https://user-images.githubusercontent.com/4980243/66468965-b0444d80-ea8f-11e9-9a2b-0f5208a40952.gif)

**Comment by SlayksWood** [comment]
You can add a notification as if you pressing key "Z".
![image](https://user-images.githubusercontent.com/45708377/66469904-68262a80-ea91-11e9-9643-c0ff100c5f2c.png)
