### ISSUE TITLE
[master-preview] Civics: Remove-build block trigger bug

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13289]
This trigger seems to be not working with filter.
1. Create a law with preventing block building-removing. For any type.
![bandicam 2019-10-09 14-33-17-314](https://user-images.githubusercontent.com/27898520/66471795-66666200-eaa5-11e9-980e-eff293bee83b.jpg)
2. Try to build with a brick. You can't
![bandicam 2019-10-09 14-52-08-517](https://user-images.githubusercontent.com/27898520/66471811-71b98d80-eaa5-11e9-8580-2812caa432ec.jpg)
3. Choose a brick for the filter in the law
![bandicam 2019-10-09 14-52-54-167](https://user-images.githubusercontent.com/27898520/66471838-7e3de600-eaa5-11e9-85ce-c73bfabc9f53.jpg)
4. Try to build with brick. You can. But you should not.
![bandicam 2019-10-09 14-54-15-392](https://user-images.githubusercontent.com/27898520/66471991-c2c98180-eaa5-11e9-9479-c866d1c5ec91.jpg)

**Comment by beastyn** [comment]
Still here. 
TheLaw:
![bandicam 2019-11-15 12-04-50-995](https://user-images.githubusercontent.com/27898520/68923490-4579e680-07a0-11ea-9557-e68fe896f99e.jpg)

But I can build btick's blocks
![bandicam 2019-11-15 12-05-12-418](https://user-images.githubusercontent.com/27898520/68923545-604c5b00-07a0-11ea-821f-57165c17c6ef.jpg)
![bandicam 2019-11-15 12-05-15-480](https://user-images.githubusercontent.com/27898520/68923549-617d8800-07a0-11ea-8448-bb6b37642332.jpg)

**Comment by johnkslg** [comment]
I cant repro this, the law is working for me:
![image](https://user-images.githubusercontent.com/3536496/68974061-a7d4e600-07a4-11ea-9324-e21591601a7e.png)

You may need to remake the law, if the law migrated it could be buggy.
Can you try again in next build and if its still a problem grab me on discord.

**Comment by beastyn** [comment]
Checked with Dig and Mine trigger, Had the same issue, it won't work if block type is selected.

**Comment by johnkslg** [comment]
Havent been able to repro this still, but in my new PR I made a bunch of changes to actions, that may affect it regardless. Can you try again in a build with that change, and if its still failing, send me the game.eco.

**Comment by SlayksWood** [comment]
@johnkslg 
Create law:
![image](https://user-images.githubusercontent.com/45708377/69238590-6fb91300-0ba9-11ea-98f2-00064be6faf5.png)
It prevent to construct, but it place block at ground:
![image](https://user-images.githubusercontent.com/45708377/69238755-cc1c3280-0ba9-11ea-9367-f55b8dd8c6b5.png)
Can you fix this too?

**Comment by johnkslg** [comment]
Surrrre I can do that!

**Comment by johnkslg** [comment]
The fix makes interactions that 'fail' stop trying to do the follow up action.
This could affect other types of interactions: putting stuff in inventories, etc.  Keep an eye out for unexpected stuff like that.

**Comment by beastyn** [comment]
Looks fine now. Will make deeper tests later on. Thanks.
