### ISSUE TITLE
Code review follow up 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13292]
https://github.com/StrangeLoopGames/Eco/pull/5076

Couple remaining items post-merge:

For floating text, instead of duplicating fade code, you can put a float and a fader on it. I had a look, and there's actually already a prefab FloatingText, which is used for calories now. Can you refactor to use this same prefab and component?   Create a prefab variant if you want different settings for the labor floating text.  

![image](https://user-images.githubusercontent.com/3536496/66511123-37db8d80-ea8b-11e9-8819-b4d37f538bd1.png)

**Comment by Hakuhonoo** [comment]
Fixed using floating text variant
