### ISSUE TITLE
Labor feedback 2

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13296]
From old feedback:
- [x] 1. When labor is required, make that outer ring pulse (use PulseObject component). This outer ring should also disappear when there is no labor required.
Players will come to recognize 'white border means I need to go apply labor', and we'll later make work parties where you go to people's workbenches and apply labor.

- [x] 2. ![66078276-8e3e4e80-e516-11e9-964c-91b0c5a4e0cd](https://user-images.githubusercontent.com/45708377/66552092-69b72780-eb51-11e9-971e-d18f34e0995e.png)
This icon isnt quite right, it depicts someone mining, which is a totally different activity than crafting. Can we change it to someone building something, ideally at a workbench? (If we want to get fancy we can have separate ones for cooking, etc.)

- [x] 3. The in-world work order and the docked work order look quite different now. Can they made to look visually the same? They should both have the labor highlight, etc. Ideally theyre the same exact asset, perhaps with that top attach-piece missing for the in-world one.
The in-game one has a big space for writing, but really thats communicated by the glowing border. I think that space should be taken by the icon.

New feedback:
- [ ] 4. I want to add a little to 3 point. Not only circles are different. But circles works differently than stripes:
![image](https://user-images.githubusercontent.com/45708377/66553003-04643600-eb53-11e9-8c88-275a0e4a406e.png)
So I think it's necessary to remake the filling of the circle as stripes.
![image](https://user-images.githubusercontent.com/45708377/66555491-72aaf780-eb57-11e9-8f2f-051352277a51.png)
Also, the necessary resources will be indicated inside the circle, not below. Labor better can be shown as icon than shown with text.

- [x] 5. Another player can't add labor. 
![image](https://user-images.githubusercontent.com/45708377/66556462-f74a4580-eb58-11e9-9b15-5076d9f780b7.png)

- [x] 6. When adding a resource, the strip is not always filled. 2 Logs were add. But strip is empty.
![image](https://user-images.githubusercontent.com/45708377/66556645-51e3a180-eb59-11e9-80e4-c24eb0782154.png)

- [ ] 7. Display the order that is currently crafting. If nothing is crafting, then display the first in the list.
![image](https://user-images.githubusercontent.com/45708377/66557214-2f05bd00-eb5a-11e9-8b24-6b36060ba5fa.png)

**Comment by Hakuhonoo** [comment]
> 5. Another player can't add labor.

Yes, stranger cannot. Only owner or someone from work party:
`public bool CanContribute(User user)      => this.Owner == user || (this.WorkParty?.HasLaborer(user) ?? false);`

**Comment by Hakuhonoo** [comment]
> Also, the necessary resources will be indicated inside the circle, not below. Labor better can be shown as icon than shown with text.

We have new design for it already, there will not be a place for any text inside
![WorkProgressPopup](https://user-images.githubusercontent.com/11686660/66650509-7747dc80-ec39-11e9-8a8e-365ac1c13d75.png)

**Comment by johnkslg** [comment]
Strangers should be able to add work if the table is accessible to them.

**Comment by SlayksWood** [comment]
Seems fixed. Not fixed issue was add to #14015
