### ISSUE TITLE
[master-preview] Craft: work order screen  icon update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13297]
Steps:
1. Place resourses into someone's work order.
2. Get the screen icon for this work order
3. Wait for the work order to be finished
4. Screen icon is still there

Actually, icon should disappear ad work order was finished
![icon](https://user-images.githubusercontent.com/27898520/66563493-4e5f1300-eb77-11e9-9694-7b5e14aa8894.png)

**Comment by Quadbro** [comment]
It will dissapear after you remove the work order, no?

**Comment by SlayksWood** [comment]
Work order completed but icon remains

**Comment by Hakuhonoo** [comment]
Cannot replicate it anymore.
I guess, it was fixed in one of my previous bug fixes
