### ISSUE TITLE
Admin Law removal

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1329]
It seems that laws have become a way of griefing people. An admin needs to be able to actively and directly delete laws when this happens.

https://cdn.discordapp.com/attachments/258375026435162112/298697714684788736/unknown.png

In future it would be nice if only people that have logged in to the server once and are not on the ban list / only people that are on whitelist that can create and vote for laws

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2091/voting-ingame-time-requirment

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2161/voting-ideas

**Comment by rainfarmer** [comment]
@MarjieAVolk @johnkslg 
To fix this, we could add a login query, that check that the user is not banned / whitelisted, and maybe has been on the server for x time, and maybe has x amount of skill?

Also allow admin users to use query  /api/v1/laws/cancellaw

**Comment by MarjieAVolk** [comment]
I believe some of this has been changed / added on the teacher tools branch... so I'm going to wait until that branch gets merged in to work on this issue.  Mostly for conflict reasons.  That's almost there though, right?

**Comment by rainfarmer** [comment]
Hey @MarjieAVolk did you add any checks for users trying to propose laws?

Like add a login query, that check that the user is not banned / whitelisted, and maybe has been on the server for x time, and maybe has x amount of skill?

**Comment by MarjieAVolk** [comment]
I have been adding blacklist/whitelist checking and such to many of the web api queries, including laws (as stated in the PR linked above).

As for the other suggested requirements, with the new law system players will be able to pass laws about who can vote/propose laws, to implement those restrictions how they want.
