### ISSUE TITLE
Add ability to backup, restore, rename and delete save games

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13294]

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/816 ;)

**Comment by johnkslg** [comment]
and the ability to rename it

**Comment by johnkslg** [comment]
Suggestion getting done!

**Comment by elfl0rd** [comment]
Maybe + manual backup?

**Comment by Deantwo** [comment]
> Maybe + manual backup?

Or just a "copy world" option, makes more since than a "backup" button.
