### ISSUE TITLE
Master: if you carry placable block and select "usable" item, you see wrong hint

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13291]
log+tree seeds="plant" but real action is place log.
![изображение](https://user-images.githubusercontent.com/4980243/66472845-c275ba00-ea96-11e9-8357-ea4ab5a7fe08.png)
![изображение](https://user-images.githubusercontent.com/4980243/66472855-c86b9b00-ea96-11e9-9138-a884d8abc1ef.png)

**Comment by redwyre** [comment]
This might just be a general problem with carried items that are intractable, I don't think the `InteractionManager` understands that carried items and toolbar items are different.

**Comment by SlayksWood** [comment]
#14574, #13968, #14493

**Comment by SlayksWood** [comment]
Tooltip is right. But I can't place Log. It tryes to plant seed:
![image](https://user-images.githubusercontent.com/45708377/74004374-a7ed1800-4986-11ea-9814-b80c79e5f33e.png)
