### ISSUE TITLE
[master-preview] Drill Feedback

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13307]
- [x] 1. it's possible to display non-empty blocks as Hollow. Step to reproduce:
1.  Find plant(beet) and try to drill
![image](https://user-images.githubusercontent.com/45708377/66638637-fb8c6680-ec1d-11e9-822e-b6e677eea976.png)
2. Place Steel bar or Iron bar and try drill through it:
![image](https://user-images.githubusercontent.com/45708377/66638714-22e33380-ec1e-11e9-8c08-3c18f1854c33.png)

- [x] 2. Blocks with plants isn't Hollow block. Dirt with pumpkin (for example) = Hollow
![image](https://user-images.githubusercontent.com/45708377/66638783-47d7a680-ec1e-11e9-8c95-000b9e56f5c5.png)

- [x] 3. Hollow below zero point. Need display as Core and may be finish drilling.
![image](https://user-images.githubusercontent.com/45708377/66639110-e8c66180-ec1e-11e9-8c10-a2bdd45ec732.png)

- [x] 4. The arrow doesn't move until you drill 1 block. Give first position in zero and add move from 0 to 1.
![image](https://user-images.githubusercontent.com/45708377/66639404-73a75c00-ec1f-11e9-9317-98fd6f38c5d0.png)

- [x] 5. Window position "Prospecting" doesn't save. from StrangeLoopGames/EcoIssues#13283

- [ ] 6. Prospecting drill rotate to incorrect direction. All suggestions seee here StrangeLoopGames/EcoIssues#13286

- [x] 7. Increase UI width or do hyphenation full word or add possibility change UI width by myself. It's necessary to take into account the increase in words after localization.
![image](https://user-images.githubusercontent.com/45708377/66640335-7440f200-ec21-11e9-83d2-83471fd337d7.png)
 
- [ ] 8. Created blocks are drilled at the same speed. There is no difference between Ashlar stone or Lumber. There is also no difference in drilling between a stack of 4 Iron bars and Dirt or 4 basalt as a stack.
![image](https://user-images.githubusercontent.com/45708377/66640405-9a669200-ec21-11e9-9523-a2e810d8f174.png)

- [x] 9. 3d person view as shovel:
![image](https://user-images.githubusercontent.com/45708377/66640859-5d4ecf80-ec22-11e9-98c0-a98700b72bfa.png)

- [x] 10. Icons as shovel.

**Comment by SlayksWood** [comment]
7 point didn't fixed
![image](https://user-images.githubusercontent.com/45708377/75134135-6a122280-56ee-11ea-9869-f9b4d0652566.png)

**Comment by SlayksWood** [comment]
@WeaselDog @Sekor2600 
I and not only I assume that we need to increase speed drilling and add more blocks to Iron Rock Drill.
What you think about it?

**Comment by SlayksWood** [comment]
added sepaarte issue for balance #14839

**Comment by elfl0rd** [comment]
Additional suggestion (maybe after 0.9)
In real life, small "resource" veins can be found outside of deposit.
Maube we can have something like this?
![изображение](https://user-images.githubusercontent.com/4980243/75150081-9b9de480-5714-11ea-806c-8be8d5b1c3eb.png)
red ! mark indicate resource close to this block. (in any of 8 blocks)

Also modern prospecting tool, should display ore in 2x size of sides (8 area + 16 area) and display direction to detected ore (up\forward, left, right, down\back)
![изображение](https://user-images.githubusercontent.com/4980243/75155174-7ca54f80-5720-11ea-90fe-d584a8a4611d.png)


p.s.
Prospecting interface should be closed after pressing esc.

**Comment by Quadbro** [comment]
@SlayksWood 
 6. Prospecting drill rotate to incorrect direction.
- Can you please make a separate issue for art team?

8. Created blocks are drilled at the same speed. There is no difference between Ashlar stone or Lumber. There is also no difference in drilling between a stack of 4 Iron bars and Dirt or 4 basalt as a stack.
- This deserves a separate issue and 9.x milestone, cause it has lots of work for balance team

7. Refixed
other issues checked and fixed.

**Comment by elfl0rd** [comment]
> 6. Prospecting drill rotate to incorrect direction.
    Can you please make a separate issue for art team?

It is funny, but you can reopen my issue - https://github.com/StrangeLoopGames/EcoIssues/issues/13286
that Sliayks has put together here.
