### ISSUE TITLE
[master-preview] Simultaneous editing for civics objects

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13300]
If someone is already editing some civic's object, like atricle ot law, other people should see some mark on this object and should not be able to edit it. It causes some glitches. For examnple, if someome is creating district map and you will open it at the same time, district will disappear for the creator.

**Comment by johnkslg** [comment]
for laws it should work well, district maps yes this will be an issue.  
Drop a ZoningOffice and check it out, this is where district maps are created.  Will need to make a 'singly editable' option on civic objects, and then track when users are editing something to prevent others from messing with it
