### ISSUE TITLE
Master: craft counters corrupted (count are doubled)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13304]
1) start project x20 hewnlog
![изображение](https://user-images.githubusercontent.com/4980243/66580855-ba497780-eb87-11e9-82cf-f21bab48ad40.png)
![изображение](https://user-images.githubusercontent.com/4980243/66580893-ccc3b100-eb87-11e9-8df3-63b8c04c8dad.png)
2) wait
3) you see 9 hewnlog... But crafting counter is x18 complete.
![изображение](https://user-images.githubusercontent.com/4980243/66581268-7efb7880-eb88-11e9-871b-5443ff9edc30.png)
![изображение](https://user-images.githubusercontent.com/4980243/66581248-760aa700-eb88-11e9-81a8-9a8270a4ab3d.png)

**Comment by SlayksWood** [comment]
Checked on 0.9.0 stasging-1206. Wasn't able to reproduce, seems fixed.
