### ISSUE TITLE
New animals feedback

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13303]
Alligator - nothing to pickup and no reciepes.
Coyote - no fear after hit, no "dead" animation and pose, nothing to pickup and no reciepes.
Jaguar -  no "dead" animation and pose, nothing to pickup and no reciepes.
Agouti -  no "dead" animation and pose, nothing to pickup and no reciepes.

**Comment by SlayksWood** [comment]
It doesn't complete yet

**Comment by SlayksWood** [comment]
Need add new recipes to Butchery table and Campfire.
