### ISSUE TITLE
Master: local world delete\copy buttons

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13314]
Maybe better using standart icons instead of +-?
![FOOMtbR20rk](https://user-images.githubusercontent.com/4980243/66696945-7fefef80-ecd9-11e9-9a2a-39f9d1234559.jpg)
like this...
![delete-icon-image-28](https://user-images.githubusercontent.com/4980243/66696980-deb56900-ecd9-11e9-98e2-04690344098d.png)
![copy-512](https://user-images.githubusercontent.com/4980243/66696981-df4dff80-ecd9-11e9-8466-9d2bf81a8a80.png)

**Comment by SlayksWood** [comment]
I think it's necessary to make "delete" bigger and red. Just in case.
![image](https://user-images.githubusercontent.com/45708377/66730928-3cbe8980-ee5d-11e9-8013-9a0a553517ec.png)

**Comment by elfl0rd** [comment]
> And you need to add the server name. User can miss and delete the wrong world.

This is why i prefer select - than click button in fixed outside block.
I descripted it there - https://github.com/StrangeLoopGames/EcoIssues/issues/13316

And yes, i agree about changes in delete confirmation message.
for local world
Are you sure you want to delete world "%world name%"?
(For server - Are you sure you want to delete server "%server name%"?)

**Comment by johnkslg** [comment]
Fixed!

**Comment by SlayksWood** [comment]
delete should be RED
Icons still are "+/-" ,is it intented?

**Comment by WeaselDog** [comment]
@MrAnonymous110 Let me know if you have any questions about implementing
