### ISSUE TITLE
Master: deed authorization lost after restart

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13319]
My actions stop working, than i restarted server...
But after loading i got this strange behavior.
Tooltip show me as "authorized" but deed "unowned" and i cannot use\modify objects on it.
![unknown](https://user-images.githubusercontent.com/4980243/66738294-c62e8580-ee76-11e9-8d71-6b924b184d2c.png)
![изображение](https://user-images.githubusercontent.com/4980243/66740185-30492980-ee7b-11e9-9532-81e0bc9221cc.png)

https://www.dropbox.com/s/f127xfmfhk9fmxr/Storagedeedlost.zip?dl=1

I dont know what happens (no errors) but if it happens at live servers after release...

**Comment by beastyn** [comment]
Thanks.
Can be related to #13344 
Can't reproduce now. Close, but will take attention.
