### ISSUE TITLE
Master: need delete button for servers

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13316]
@johnkslg can we got it before 0.9? :D 
![изображение](https://user-images.githubusercontent.com/4980243/66700748-f0f4ce80-ecfc-11e9-8f8b-fdc808b4b87c.png)
![изображение](https://user-images.githubusercontent.com/4980243/66701234-be4dd480-ed02-11e9-9876-dcbf6a2344d4.png)
Also feedback about buttons...
If it possible, i prefer one buttons block (right side from refresh and add), not on every line.
delete for network servers and local worlds
copy\rename for local worlds.
Like this
![изображение](https://user-images.githubusercontent.com/4980243/66701313-c5c1ad80-ed03-11e9-982e-205329c3a966.png)
1 - delete, active if you select server or local world
2 - copy, active if you select local world (othervise gray)
3 - rename, active if you select local world (othervise gray)
(Byt yes, instead of load on click, need add "select" like servers to local worlds.
Also in this case in description field you can show local world stats\etc.
And for local world, instead of server "Connect" button, something like "Launch"

**Comment by SlayksWood** [comment]
also see #13314

**Comment by beastyn** [comment]
We can't tell "Are you want to delete athe world" with pressing red mibus button.
We are deleting the server from the list, not the world itself.
![unknown (61)](https://user-images.githubusercontent.com/27898520/75345682-01c66b00-58bf-11ea-913a-74e51c9ca0bb.png)

**Comment by mirasrael** [comment]
Either remove button in every line or move this button to another lines. It is very confusing now.

**Comment by mirasrael** [comment]
Also what "+" means for local worlds? Copy?

**Comment by elfl0rd** [comment]
> Either remove button in every line or move this button to another lines. It is very confusing now.

Agree, look at my suggestion in first post :)

> Also what "+" means for local worlds? Copy?

Yes, icon change suggestion there - https://github.com/StrangeLoopGames/EcoIssues/issues/13314

**Comment by SlayksWood** [comment]
I still can remove Official Server from...official test servers list? and I can remove my server from LAN, but you can't do it. It just remove world from "Recent".
So if you select LAN or Official Test servers list then you should not have  red "-".
