### ISSUE TITLE
[master-preview] Take/Put items in storages with hammer glithes.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13311]
1. Can't place with RMB at stockpile or other storages. Step to reproduce:
- spawn stockpile.
- put brick in it.
- select hammer (in my case modern hammer)
- take brick from stockpile with hammer
- at once try to put it in stockpile. You can't. You need to move camera and select stockpile again.

2. Can't take all items. Step to reproduce.
- spawn stockpile.
- put Tallow or another non-building block in it.
- select hammer (in my case modern hammer).
- you haven't tooltip about taking Tallow from stockpile. try to pick up. It's try to pick up stockpile, but can't because stockpile isn't empty.
![image](https://user-images.githubusercontent.com/45708377/66649551-2505bc00-ec37-11e9-99e5-d3c7749d97ca.png)

**Comment by SlayksWood** [comment]
Second part isn't fixed:
![image](https://user-images.githubusercontent.com/45708377/67457946-a9940980-f63d-11e9-8244-a117a87f3978.png)

**Comment by redwyre** [comment]
You need to hold control (the controls popup should change to say take)

**Comment by SlayksWood** [comment]
If my hand isn't empty then I can't take non-carrying items from stockpile with Ctrl or without Ctrl, no difference.
Why do I need to hold Ctrl? If Ctrl is held, then it should take all possible items from stockpile. 
I can only put brick, but can't take charcoal and tomato (with Ctrl too):
![image](https://user-images.githubusercontent.com/45708377/71461871-7814f700-27c2-11ea-9ac6-a7d247ee1aef.png)
If you place brick at stockpile you have wrong tooltip:
![image](https://user-images.githubusercontent.com/45708377/71462665-0db18600-27c5-11ea-88c2-15d748848e42.png)
But you will take Brick.
If you place brick in stockpile and take items with Ctrl whan it works.
