### ISSUE TITLE
[0.8.3] Ceiba & Palm tree IdealTemperatureRange have typos

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13317]
Ceiba & Palm Tree max ideal temperature is 75 instead of 0.75

**Comment by Sekor2600** [comment]
the temperature display of the Soilsampler is generally very strange with 0. numbers

**Comment by WeaselDog** [comment]
This information is not from the Soil Sampler but the game files.

**Comment by Sekor2600** [comment]
Then the data are all generally faulty. because every plant has something with 0.

**Comment by craig-jong** [comment]
This is actually true of a bunch of plants. Not sure why this isn't messing with the game more. I'll do some test worlds to make sure.
