### ISSUE TITLE
[8.3] Redefining Demographics has no effect

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13321]
Demographics before: 
![deserter1](https://user-images.githubusercontent.com/25908592/66745542-87e99400-ee7f-11e9-8535-06e30e817285.png)

Law that is changing it:
![deserter2](https://user-images.githubusercontent.com/25908592/66745545-8a4bee00-ee7f-11e9-8bb9-f6133f567fb5.png)

Demographics after:
![deserter3](https://user-images.githubusercontent.com/25908592/66745547-8cae4800-ee7f-11e9-88ed-7459e4fcff80.png)

Did not change.

**Comment by SlayksWood** [comment]
@D3nnis3n 
I'm not sure how it's actual for 0.9.0

**Comment by WeaselDog** [comment]
Looks good now:

Demographic:
![RichDemographic](https://user-images.githubusercontent.com/47330823/69686503-d0968e80-1074-11ea-884f-58e09e8e410d.png)

Demographicv2:
![RichV2Demographic](https://user-images.githubusercontent.com/47330823/69686517-dab88d00-1074-11ea-9755-4b63991e7272.png)

**Comment by beastyn** [comment]
Well, yeah, we can't change it with law now, but we have census for this.
