### ISSUE TITLE
[8.3]: Remote Address/Web Server URL issues

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#13323]
Ever since I started using a 'friendly name' for my server's connection info, there's been issues related to the game server's ability to pick up on that. 

- Explicitly listing "eco.praefator.nl:2053" as the Remote Address in Network.eco does not allow players to connect, but using my IP (84.25.113.245:2053) does.
- Explicitly listing "https://eco.praefator.nl" (with web server port on 2052) prevents people from opening the webpage from in-game, but the page is reachable from a browser
- Listing neither Remote Address nor Web Server URL allows people to connect via eco.praefator.nl:2053, however people are unable to interact with any of the webpages when launched from in-game, exposing the token in the process. 
- Additionally, despite DNS settings stating otherwise, launching the webpage from in-game insists on using IP rather than the "friendly name"

Additional info:
- Using Windows Server 2019 Standard in a VM, using Proxmox (Debian Buster-based hypervisor)
- Nginx is running in a LXC container on the same machine and set to listen on ports 80 and 443 and directed at the internal IP for the Eco VM
- Using Cloudflare's "DNS only" mode to redirect all traffic intended for eco.praefator.nl to 84.25.113.245
- Port forwarding is configured to accept traffic intended for UDP port 2053 for the gameserver
- Port forwarding is configured to accept traffic intended for TCP port 2052 for the webserver

**Comment by mirasrael** [comment]
@Praefator Can you resolve eco.praefator.nl to correct IP address from server's host?

**Comment by Praefator** [comment]
@mirasrael Yes, both https://eco.praefator.nl/ and http://eco.praefator.nl/ resolve fine when I go there from out-of-game, however from in-game I am redirected to the HTTP variant, and players from outside the network see the IP rather than the domain

**Comment by mirasrael** [comment]
@Praefator I'm interested in the result from the machine which is running the server. Because when the server start it resolves URL to IP address and so it will register IP address which was discovered on the machine which is running the server.
Some data centers either may not resolve DNS to IP within network or may resolve this address to local IP address.

**Comment by Praefator** [comment]
I'm not sure what exactly you're asking @mirasrael - from what I understand you wish to know whether I can ping between the Eco Server VM on the same physical machine as the nginx server? I don't host either of them remotely - they're hosted from home in a dedicated server.

**Comment by mirasrael** [comment]
May be problem with IPv6.
When I'm doing `nslookup` for this name I have following response from default DNS:
```
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  2001:4860:4860::8888
```

**Comment by Praefator** [comment]
Interesting. Based on earlier testing I don’t even have an IPv6 IP yet as the Dutch ISPs are notoriously slow with that (among other things). I’m assuming I would need to add an AAAA record?

**Comment by dutch2005** [comment]
> @Praefator I'm interested in the result from the machine which is running the server. Because when the server start it resolves URL to IP address and so it will register IP address which was discovered on the machine which is running the server.
> Some data centers either may not resolve DNS to IP within network or may resolve this address to local IP address.

Are you saying only the server would check and get its own LAN ip? and what about the clients? do they then just copy the data by wich the server and its local-lan is reachable? or do they do DNS queries to get the Public IP adres on wich the server is configured to run?

Not every server is run on the public IPv4 address... esp those with an load/reverse proxy in front of it will not be direct public facing, both for security and for (caching) performance reasons

**Comment by mirasrael** [comment]
I guess you can use IP address as RemoteAddress on the server side and then from client side (if they are using DNS name) it should be resolved to valid IP.

**Comment by mirasrael** [comment]
https://eco.praefator.nl is HTTPS url, but Web Server is listening HTTP. If you setup HTTPS proxy for your server then you can use WebServerUrl with https, but if it uses non default port (443) then you have to specify it in URL (i.e. https://eco.praefator.nl:2052), but if you don't have HTTPS proxy then you should use http://eco.praefator.nl:2052 instead.

**Comment by Praefator** [comment]
Yes, that's what I listed in the initial post. If I explicitly specify https://eco.praefator.nl:2052 in the WebServerUrl, the webpage won't open from in-game.

**Comment by Praefator** [comment]
@mirasrael closing this as it was a misconfiguration on my end. 
- Reinstalled nginx on Ubuntu 18.04 rather than 19.04
- Made sure port 443 was actively being listened on by nginx
- Explicitly configured the webport to point to https://eco.praefator.nl
