### ISSUE TITLE
[8.3]: Ramping up difficulty prevents initial star from being handed out on first login

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#13324]
As of 8.0, I've been experimenting with the difficulty in Eco, particularly to get the "high collab" feel where you **need** to have multiple people of each profession working together in order for players to both have their own 'niche' they cover all map long, as well as provide meaningful profession choices. Something vanilla High collab sorely lacks with how relatively easy it is to get a lot of stars over the course of a month. Given how I run 60 day maps, that's far from ideal.

As such, I've increased the SpecialtyExperienceDivisor up to 30, and SpecialtyExperiencePerLevel up to 50, which is a net increase of ~3-4x the amount of experience needed to level up. All well and good so far, as that required people to use high-end foods and work on their housing score. 

However, where the issues start to appear is when the **SpecialtyCostMultiplier** is raised. By default it's set to 2 with High collab, and me raising it to 3 as of our previous map, making sure that it took an average of 45 days to reach the relatively smooth 8 stars before the sharp dropoff in star acquisition kicked in. Still good there. 

This map, we wanted to raise it up to 4, to make sure that by the end of the 60 day cycle, people would have their 8 stars. It is here that people started telling us that they **had to wait an hour for their first specialty star to become available** rather than upon first login. Something seems off there.

**Comment by SlayksWood** [comment]
Yep, I observed this behavior. But I didn't think that It was a mistake. I will try to investigate it.

**Comment by Sekor2600** [comment]
I do not know if it depends on it.

Skillset.cs 
public static readonly int[] SpecialtyCosts = { 1, 1, 20, 50, 100, 200, 400, 800, 1600 };

you can´t config this String. This determines the distance of the stars

1 = Survialskill , 1= First Star, etc

The harder you make the conditions, the harder it will be to get the first star

**Comment by Praefator** [comment]
I concur, would be nice to expose the SpecialtyCosts directly and be able to modify the values as needed to fix these sort of early game issues or dynamically adjust the length of the various stages in a map's cycle

**Comment by Sekor2600** [comment]
Yes you could determine if it is difficult in the beginning and come to stars slower if you want a long-term map

**Comment by D3nnis3n** [comment]
That's a bug. No matter the difficulty a player should start with a star to be able to do something. Probably there is some calculation, that shouldn't be there. Did you ever try if using an especially low value for that give you more than one star to start?

**Comment by Sekor2600** [comment]
That did i test with 8.0 or was ist 8.1. Dont know anymore. ;) Did use 1 but you did not have more than 1 Star. 

The 2nd was only very fast next.

**Comment by SlayksWood** [comment]
fixed, but add separate issue #13689 about the possibility of changing the distance from the Stars.
