### ISSUE TITLE
EcoServer_v0.5.5.3-alpha crash during Initializing StorageManager when trying to load v0.5.4 game.eco

### ISSUE THREAD

**Issue by OmegaTou** [StrangeLoopGames/EcoIssues#1332]
Server launches and runs fine with a newly generated game.eco file, but when I try to load my 0.5.4 game.eco I get a JSON serialization Exception during Initializing StorageManager. See text file.

[game.eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/895064/game.eco.zip)

[Crash 04040528.txt](https://github.com/StrangeLoopGames/EcoIssues/files/895061/Crash.04040528.txt)

**Comment by metachronism** [comment]
This is intended.  There is a migration tool (check discord announcements channel) you can use to port from 5.4 -> 5.5+
