### ISSUE TITLE
[master-preview] Creation Avatar feedback

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13338]
- [ ] 1. When the selecting gender changes, UI moves. Let UI change below, but the top should be at the same level.
![2019 10 15 Avatar creation](https://user-images.githubusercontent.com/45708377/66803651-e9197200-ef28-11e9-9b48-03e8dd85228a.gif)
![image](https://user-images.githubusercontent.com/45708377/66804154-609bd100-ef2a-11e9-9e04-7388582d23d7.png)

- [ ] 2. Shirts mixed up. On the icon are short sleeves, on the body are long sleeves. On the icon are long sleeves, on the body are short sleeves.
![image](https://user-images.githubusercontent.com/45708377/66804814-26cbca00-ef2c-11e9-95cc-ca4f61f90b4b.png)

- [ ] 3. When changing the belt, nothing happens. Same was in 8.3.0. But now it looks more strange.

- [ ] 4. Pants mixed up as shirt.
![image](https://user-images.githubusercontent.com/45708377/66803920-c0de4300-ef29-11e9-9320-2f0ef7a73036.png)

- [ ] 5. More as suggestion. Make all tabs with a color window. So you can copy colors using the eyedropper.
![image](https://user-images.githubusercontent.com/45708377/66804769-08fe6500-ef2c-11e9-9a48-4fe5a7eb4f68.png)
I could have done so before:
![image](https://user-images.githubusercontent.com/45708377/66805344-75c62f00-ef2d-11e9-9164-d888a8518888.png)
Now I can't.

**Comment by SlayksWood** [comment]
After fixes:
- [ ] Wrong position
![image](https://user-images.githubusercontent.com/45708377/66891149-0580e180-eff1-11e9-8cea-c4de386c5e8a.png)

**Comment by SlayksWood** [comment]
- [ ] Hair Icon in Facial Hair:
![image](https://user-images.githubusercontent.com/45708377/66980551-f154e700-f0b9-11e9-9d6c-20e3d4537179.png)

**Comment by SlayksWood** [comment]
> ![character](https://user-images.githubusercontent.com/26705633/67729931-e2b5ea80-fa3e-11e9-99aa-dc4e33b59d1e.jpg)
> Hair colour was stuck on a single colour.

**Comment by serpopov** [comment]
Some clothes has wrong models, not icons

**Comment by beastyn** [comment]
still actual

**Comment by elfl0rd** [comment]
When you create an avatar, the items you've already worn are not really selected (only visual).
In fact, you need to do 2 clicks to change anything.

After join
![изображение](https://user-images.githubusercontent.com/4980243/68544206-c700fb80-03d1-11ea-8254-111bb092c2f7.png)

Now i click on gigot.
![изображение](https://user-images.githubusercontent.com/4980243/68544214-f1eb4f80-03d1-11ea-9c4c-f09061563a21.png)

**Comment by beastyn** [comment]
3. When changing the belt, nothing happens. Same was in 8.3.0. But now it looks more strange.
still an isuue

And Pants are wrong too,

**Comment by elfl0rd** [comment]
Also my comment are ignored :(

**Comment by SlayksWood** [comment]
Still an issue. Selected item s(without any selecting) are wrong. Just load to new world and open avatar. Basic avatar has Normal hair, but selected No Hair.
![image](https://user-images.githubusercontent.com/45708377/82292236-32e0a400-99b3-11ea-9de9-af7d77fafff1.png)
Same with T-shirt:
![image](https://user-images.githubusercontent.com/45708377/82292489-af738280-99b3-11ea-83ee-c242d18a2cc3.png)
 if I reselect:
![image](https://user-images.githubusercontent.com/45708377/82292514-ba2e1780-99b3-11ea-9280-970ac4c68d6c.png)
and etc.
