### ISSUE TITLE
Master: skills loose "effeciency" benefit from profession.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13333]
Only speed there
![изображение](https://user-images.githubusercontent.com/4980243/66785431-e5b0c700-eee5-11e9-9481-e736927e5133.png)

**Comment by SlayksWood** [comment]
dup #13084

**Comment by elfl0rd** [comment]
@SlayksWood problem is deeper, no effeciency affected to receipes!
This is not only missing _icon_!
