### ISSUE TITLE
[master-preview] Tutorial skipping glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13339]
Step to reproduce:
- start client
- connect first time to server or restart tutorials
- for greater effect: complete Controls tutorial, take shovel and pickaxe for tutorials will appear.
![image](https://user-images.githubusercontent.com/45708377/66811701-37833c80-ef3a-11e9-8863-f5cc9a02e238.png)
- disconect! and connect to server (without closing client)
- try to skip tutorials.
![2019 10 15 Tutorial skipping glitch](https://user-images.githubusercontent.com/45708377/66812074-df006f00-ef3a-11e9-807a-79126731a691.gif)
- They were skipped, but duplicates remained. You can't complete or skip them. The only way is to restart the game.

See also old bug with skipping #12504

**Comment by SlayksWood** [comment]
This glitch seems to happen with all the Icons: Work Parties, Work Orders. The problem is common with UI

**Comment by gzatravkin** [comment]
Can't reproduce with described passes. Please attach a full video of reproduction (from start to getting duplicated)

**Comment by SlayksWood** [comment]
It was some kind of global problem, it isn't reproducing now.
