### ISSUE TITLE
Drill feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13331]
- [x] When clicking mouse button for drill, drill dialog appears, disappears, then fades in:
![anim](https://user-images.githubusercontent.com/3536496/66778887-caac6b80-ee81-11e9-9584-1c44ccb32be6.gif)

- [x] Drilling happens to fast.  By the time the dialog has opened, I've already drilled through serveral layers.  Make a delay when you initially start drilling of several seconds, then make it much slower to drill (it currently drills 5 meters within a second or 2, that should take 5x as long)

- [x] Drilling should consume calories for each depth you go to

- [x] If I stop drilling and then continue, it should continue at the depth I last left it at (and make sure that tapping left mouse doesnt speed it up/slow it down more than clicking and holding would)

- [x] Drill should be mounted to the side of the screen rather than a draggable window.  Work with Milenko to get a UI design for this.

- [x] Make the camera look to the drill when starting, but then you can give back screen lock.  

- [x] Change the drill animation so it doesnt keep pulling the drill in and out while drilling.  It should just be held steady.

- [x] Add sounds to the drill, work with Leonard to get them.

**Comment by Quadbro** [comment]
> When starting the drill process, make the drill rotate to be perpendicular to the targeted surface. When drilling stops, rotate it back to normal. Make the camera look to the drill when starting, but then you can give back screen lock.

Will be painfull with third-party animation, due to different frilling normals, it works preatty well with smal interact radius

> If I stop drilling and then continue, it should continue at the depth I last left it at (and make sure that tapping left mouse doesnt speed it up/slow it down more than clicking and holding would)

It will require lot's of server pings, due to per block requests, do we really need this?
