### ISSUE TITLE
[master-preview] Craft is broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13344]
More importantly, the game is broken.
The most common case:
- connect to server
- start craft without resourses.
- disconnect and reconnect to server(without closing client)
- game broken. I don't see Anna (only the icon above her head) I don't see myself in 3d person view! I can't interact with anything.
![image](https://user-images.githubusercontent.com/45708377/66816925-94cfbb80-ef43-11e9-96f4-c0396c3f7681.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3728346/Player.log)
[Player2.log](https://github.com/StrangeLoopGames/EcoIssues/files/3729007/Player.log)
This is a 100% case. 
But besides it, strange consequences appear like:
![image](https://user-images.githubusercontent.com/45708377/66827780-1af5fd00-ef58-11e9-9cc2-4582d952243a.png)
It appears without reload.
Work order icon untie from crafting table.
![image](https://user-images.githubusercontent.com/45708377/66828012-ae2f3280-ef58-11e9-9bd2-1747f729d76e.png)
To craft any item I should probably hope for luck. Because something strange happens to craft. And I can't to say why this happens, because anything can happen.
Added both @Hakuhonoo and @serpopov. And Critical issue because I think I have many new bugs due to this issue

**Comment by elfl0rd** [comment]
Got this without second players and world reloading =|

**Comment by SlayksWood** [comment]
Seems fixed with https://github.com/StrangeLoopGames/Eco/pull/5112
