### ISSUE TITLE
aquaduct broken again 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1334]
http://ecoforum.strangeloopgames.com/topic/1286/river-diversion-how-to-divert-the-water

**Comment by noblackthunder** [comment]
sort of apparently =P

**Comment by metachronism** [comment]
Aqueduct is watertight, so something else must be going on

**Comment by Stephenw92-git** [comment]
i find the aqueducts work fine for transporting water on our server however it's pure luck whether the water will spread from the aqueduct through the ground or whether the only part affected by water is directly under the outlet pipe of a pump

**Comment by Neouni** [comment]
I seem to have better luck getting it from a waterfall then a river that has been flat for 40 blocks already.

note: no leakage diagonally

and offcourse ~~aque~~ aquAductitem

**Comment by Conroy1988** [comment]
I notice that the aquaduct will stream the water so far, then it will stop, blocking and then removing a aqua block before it dies down seems to increase its flow, but the water leakage is still there, on a raised aqua strip 20 blocks above the land the waterspread still effects everything underneath the aqua flow, no matter how high or low.
