### ISSUE TITLE
[master-preview] Crash when press Draft Law

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13341]
![image](https://user-images.githubusercontent.com/45708377/66818354-e11bfb00-ef45-11e9-988a-8abb80240c03.png)
It happened one time for me. And I can't reproduce it second time. I will try to get steps to reproduce. But for now I'll post an exception:
```
<size=60,00%>Exception: NullReferenceException
Message:Ссылка на объект не указывает на экземпляр объекта.
Source:Eco.Gameplay

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   at Eco.Gameplay.Systems.ViewEditor.Init(User user, ViewEditor editor, Action`1 onSubmit)
   at Eco.Gameplay.Components.CivicObjectComponent.Edit(Player player, Int32 index)</size>
```

**Comment by johnkslg** [comment]
Ill add a couple null checks that could have caused it.  Let me know if you can repro it again.  Can we drop in priority?
