### ISSUE TITLE
Elections Web Feedback (server code)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13347]
Elections are interacted with via a webpage, and access to those is controlled via our web api.  To see the webapi, with the server running locally browse to http://localhost:3001/swagger

To repro these issues, generate election test data by running that api command in swagger: 
![image](https://user-images.githubusercontent.com/3536496/66861072-30146100-ef43-11e9-8230-196dc4ea358c.png)

**Issues**
- [x] There's a header missing in the table here. It should be the name of the prior object that is getting changed in the election.
![image](https://user-images.githubusercontent.com/3536496/66860990-fd6a6880-ef42-11e9-8814-6abea34aa90e.png)
Check out the elections query in the api returning the table, and then go find that in the code (search for that name) and see why its not including the name of the object being changed. 
![image](https://user-images.githubusercontent.com/3536496/66860980-f8a5b480-ef42-11e9-8157-bffdf457fc09.png)

Similarly, see why this text is missing the original object being changed:
![image](https://user-images.githubusercontent.com/3536496/66861312-a1541400-ef43-11e9-95ac-f862ae1415ee.png)

- [x] Clicking submit in the discussion did nothing:
![image](https://user-images.githubusercontent.com/3536496/66861389-ce082b80-ef43-11e9-84c2-b186de9ce252.png)

- [ ] Add a new Description member for elections, that describes them better:
![image](https://user-images.githubusercontent.com/3536496/66861604-2dfed200-ef44-11e9-906f-a5306764e76b.png)
IE, this elecetion should have a block of text in the description below it that describes the election in more detail: '<User name> has proposed that the following changes are made to Consitutional Article 2.  Do you agree?'

And this one:
![image](https://user-images.githubusercontent.com/3536496/66861718-5d154380-ef44-11e9-85cc-16c84eaa767e.png)
'<User Name> has proposed we should add a new elected title with the following properties.  Do you agree?'

And this one, electing a leader for Title 2:
![image](https://user-images.githubusercontent.com/3536496/66861765-761df480-ef44-11e9-9b00-94cfbd66af22.png)
'<User Name> has started an election to determine who should occupy the office of 'Title 2'.  Vote with your candidate rankings below.  It is currently occupied by <occupant name, or 'nobody'>.
Details of this position:

**Comment by beastyn** [comment]
Dob't see the ladt pointed changes

> Add a new Description member for elections, that describes them better:
> 
> IE, this elecetion should have a block of text in the description below it that describes the election in more detail: ' has proposed that the following changes are made to Consitutional Article 2. Do you agree?'
