### ISSUE TITLE
[master-preview] Craft: labor in the table UI with shift doesn't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13356]
You can add the hole bunch of calories on the table with shift+rmb when you are not in the table UI. 
But you can't do this in the table UI when holding shift and clicking on the Work button. I suppose we need this too.

**Comment by SlayksWood** [comment]
Checked on 0.9.0 staging-1206. Wasn't able to reproduce, seems fixed.
