### ISSUE TITLE
Species list difficult to use due to auto-refresh scrolling to the top every few seconds.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#13354]
![image](https://user-images.githubusercontent.com/14983165/66872131-14688500-ef5a-11e9-8cdc-5fb0c6a7f544.png)

The species list in the Simulation tab is quite difficult to read because it auto-scrolls to the top of the list every few seconds.

**Comment by redwyre** [comment]
Unfortunately I don't think there's much I can do as the plugin sets the entire panel contents every update...

**Comment by redwyre** [comment]
I'm going to bump this down to low priority, but let me know if it's blocking work and I'll do something about it
