### ISSUE TITLE
Master: you can stuck at "too hungry" but without tutorial\ui

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13351]
Found additional way to it, need additional check for "you are too hungry for that" (byt you still have some calories!).
You can got this message e.g. while mining, etc.
![изображение](https://user-images.githubusercontent.com/4980243/66867552-3a1a7c00-efa4-11e9-80c4-67a8a5dd01de.png)

**Comment by SlayksWood** [comment]
It's due to the increased calorie consumption of the pickaxe. Merged to #13155
