### ISSUE TITLE
[master-preview] Work party: doesn't pay a penny!

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13362]
1. Create a workparty
2. Let someone take it
![bandicam 2019-10-16 16-02-56-716](https://user-images.githubusercontent.com/27898520/66914790-00dc1d80-f031-11e9-9bb8-e56519f7e186.jpg)
(you need to make auth for a table as it doesn't work for work party by default)
3. Let someone finish it.
![bandicam 2019-10-16 16-05-44-176](https://user-images.githubusercontent.com/27898520/66915398-5e249e80-f032-11e9-82fb-ac9e6e909ef6.jpg)

4. Work Party seems to be Active. Someone didint' get money. Someone didn't get 100% for the work. And if you cancel finished work party Someone still got nothing as payment.

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/71345103-70144780-2575-11ea-9ac4-d591fa365128.png)

**Comment by SlayksWood** [comment]
It doesn't give Skill scrolls too.

**Comment by johnkslg** [comment]
Greedy workparty creators refusing to pay a cent has been fixed:

![image](https://user-images.githubusercontent.com/3536496/71606046-9f512880-2b22-11ea-857c-7fd6d32d2036.png)

And when cancelling:
![image](https://user-images.githubusercontent.com/3536496/71606107-0a9afa80-2b23-11ea-9d85-ca3c7d9bedae.png)

viva la revolucion!
