### ISSUE TITLE
[master-preview] Work party: it doesn't count labor

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13365]
We should count labor too as someone can provide labor without resources.
to @Hakuhonoo  for labor help

**Comment by SlayksWood** [comment]
You can add string for labor estimation as percentage. Because it's difficult to automatically estimation labor.

**Comment by Hakuhonoo** [comment]
You can get labor percentage of work order by `yourWorkOrderView.LaborPercentage` property
