### ISSUE TITLE
Master: project provide different products in one queue if multiple resources privided.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13360]
e.g. if you just "order" some hewnlogs at workbench, and you have cedar logs and birch logs, you receive: "standart" hewn logs, hardwood hewn logs, and softwood hewnlogs.

**Comment by Hakuhonoo** [comment]
@elfl0rd 

What is expected behavior?
1) Make from cedar & birch logs "standard" hewn logs
2) Don't show (and don't use) cedar & birch logs as available for the craft recipe

**Comment by elfl0rd** [comment]
@Hakuhonoo 

I prefer 1 as "fast" fix

But how do i think, logic needed to be like this:

only one type per project.
e.g. "Selection" order - Soft log, hard log, standart.

you have resources for 50 soft log, for 70 hard log (120 total)
In order, first - soft log
If you order 40 hewn logs by "just" order - you got 40 soft logs (due soft logs first in priority)
If you order 60 hewn logs by "just" order - you got 60 hard logs (due soft logs (first in priority) cannot be crafted as single type output product)
If you order 80 hewn logs by "just" order -  standart logs (due you cannot craft one type per project)

Also i think you need internal discussion about suggested logic ;)
Tell me about the results.

**Comment by elfl0rd** [comment]
And additional small thing.
Some recipes do not have to contain a "simple" order button.
For example, tools.

**Comment by craig-jong** [comment]
I'm not 100% clear on what you're asking so I'm just going to clarify:

the default order button *should* take the first items from the linked inventories that satisfy the tag and then it determines what, if any, specific recipes it satisfies. I'm guessing the problem that occurs is when you have mixed hard and softwoods, it will (usually) make at least one generic hewn log in between.

I think (if the goal is to turn a large pile of mish-mash logs into hewn logs) then it doing the above is alright. If the goal is to have all of the exact same items the "advanced" order can be used. That said, I totally understand where you're coming from. We'll have a talk about this and see what everyone else thinks.

**Comment by elfl0rd** [comment]
>I'm guessing the problem that occurs is when you have mixed hard and softwoods, it will (usually) make at least one generic hewn log in between.

yes,
For me, the expected behavior is to get one type of item from the entire order (project).
Otherwise, there are a lot of small but very uncomfortable problems.
**Several stacks instead of one**, **problems with transportation**, problems with "beauty", etc.

I tried to think through the proposed logic in such a way that new logs would be made, but if it is impossible, old logs would be automatically created.

This is for quality of life.

**Comment by Hakuhonoo** [comment]
Let's just hide unavailable quantity of resources for selected craft and it will use only selected recipe. Soft logs for soft hewn logs, hard - for hard, "standard" for "standard".

**Comment by elfl0rd** [comment]
> Let's just hide unavailable quantity of resources for selected craft and it will use only selected recipe. Soft logs for soft hewn logs, hard - for hard, "standard" for "standard".

I think it's gonna be a problem for novice players

**Comment by Hakuhonoo** [comment]
So we are going to have:
Soft from soft
Hard from hard
Standard from anything?

**Comment by elfl0rd** [comment]
yep

**Comment by craig-jong** [comment]
I've fixed a but related where the "Standard" was not crafting properly. I'm going to close this issue as it should be covered by specific crafting options (if thats what the player wants).

**Comment by elfl0rd** [comment]
this behavior still annoying...

**Comment by elfl0rd** [comment]
For example, in the worst case, you will get three stacks of hewn log instead of one when ordering 15 pieces.
You would expect one, or not?

**Comment by elfl0rd** [comment]
Okay, lol.
Another example
"Charred Food"
descripted as 400 cal, 2\2\2\2 nutrients.
but...
You can receive a lot of different foods.
Like
Charred Heart of palm
450, 7\3\1\2
Charred tomato
510, 8\1\0\4
Charred papaya
460, 6\1\0\6
Charred Mushrooms
450, 3\6\2\2

This
is
annoying.
@D3nnis3n, @johnkslg, @craig-jong
