### ISSUE TITLE
[master-preview] Work Party: failed parties in the Economy viewer

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13363]
Do we need to show failed parties in the Economy viewer UI? Maybe we can separate them somehow for history like in hidable list
![bandicam 2019-10-16 16-44-19-496](https://user-images.githubusercontent.com/27898520/66916221-37fffe00-f034-11e9-9a8d-1a11ba017b16.jpg)
.

**Comment by johnkslg** [comment]
Yes they should hide, same as failed contracts hide.

**Comment by johnkslg** [comment]
They no longer show.

**Comment by johnkslg** [comment]
Man that UI looks ugly now.
