### ISSUE TITLE
[master-preview] Work Party: taking party in the Work Party

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13364]
For now you can take party in a work party only when you click on the Active in the Economy viewer. It should be more useful to click on icon or name too, I think

**Comment by beastyn** [comment]
Also we should provide more info in the Economy viewer about parties. Where do you take a part, what was you providing and in what percent.

**Comment by johnkslg** [comment]
@serpopov can you make work parties accepted at a contract board, like contracts? Generalize the code so either can be accepted, and they use the same code paths/generate the same actions for offering/accepting.  Chat to @olegshegai who is working on GameActions for contracts.

**Comment by johnkslg** [comment]
I've got them on contract boards now which is where you can accept them, so you have to go to a place to accept them.
