### ISSUE TITLE
[master-preview] Can't place block under myself

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13361]
My avatar also prevent building when using other forms.
0.9.0:
![image](https://user-images.githubusercontent.com/45708377/66914101-bc478680-f01e-11e9-9573-ed7a6b1109c7.png)
![image](https://user-images.githubusercontent.com/45708377/66915008-b18df100-f020-11e9-89b9-949d58524c7f.png)
In 8.3.0 there was  another behavior:
![image](https://user-images.githubusercontent.com/45708377/66914409-6de6b780-f01f-11e9-8a8a-9387102f2d57.png)
![2019 10 16 Can't place block under myself](https://user-images.githubusercontent.com/45708377/66915194-19dcd280-f021-11e9-9f3a-b72faeee373a.gif)

**Comment by redwyre** [comment]
I'm going to say this is correct behaviour, it doesn't make much sense to be able to place a block where you are standing.
