### ISSUE TITLE
Master: blocks ignore objects occypancy\collision.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13368]
Treasury
![изображение](https://user-images.githubusercontent.com/4980243/66927561-aba40a00-f038-11e9-9579-85b53c9cabf8.png)
Oil refinery
![изображение](https://user-images.githubusercontent.com/4980243/66928108-8ebc0680-f039-11e9-8392-0b3b14c42e06.png)
(also there is invisible connector...)

it is not bad if we can place some objects IN another, but too many errors with current behavior.
E.g. if you pickup object with another blocks inside - these blocks just disappear.

**Comment by SlayksWood** [comment]
merge to #13572

**Comment by elfl0rd** [comment]
lol
