### ISSUE TITLE
Top Bar Improvements

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13375]
![image](https://user-images.githubusercontent.com/3536496/67045739-bbc4f380-f0e3-11e9-9f80-376ef69e1dfd.png)
Make the top bar (says dirt in the screenshot here) improved:
- It should say the species being looked at
- It should clamp to the top of the screen, scooting down only when the notification bar is active, and hiding if the notification bar is expanded.

**Comment by johnkslg** [comment]
Consult @Quadbro he made this one

**Comment by elfl0rd** [comment]
> It should clamp to the top of the screen, scooting down only when the notification bar is active, and hiding if the notification bar is expanded.
I prefer this window movable, is possible.

**Comment by beastyn** [comment]
Also check situations with tools like Stone Machette which shows Plant Fibers (machete destroys a  plant)

**Comment by beastyn** [comment]
also here about stones ##14478

**Comment by Conchipedia** [comment]
Stone Machete still destroying Plants and not giving Plant Fibers [Staging 1378]
have to admit its nice just for clearing an area 😆

**Comment by elfl0rd** [comment]
> 
> 
> Stone Machete still destroying Plants and not giving Plant Fibers [Staging 1378]
> have to admit its nice just for clearing an area laughing

Machete designed to destroy, not gather.

**Comment by Conchipedia** [comment]
then it should say that on tooltip as it does give same info as Scythe
