### ISSUE TITLE
[master] Real estate desk makes endless crafting sound

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13379]
To reproduce, just spawn a Real Estate Desk and interact with it.

It starts to make a crafting sound that never stops. If you interact with it multiple times the sound spam gets really intense. The sound can be heard from up to 90m away by all players. The sound persists after a server restart.

**Comment by WeaselDog** [comment]
The sound also persists if you pick up the Real Estate Desk so there is no way to stop it at all.

**Comment by Sekor2600** [comment]
This Sound is with Tables like Workbench or Sawmill too

**Comment by beastyn** [comment]
dup #13163
