### ISSUE TITLE
Giant Cactus Fruit?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13378]
change the recipe or UI
![image](https://user-images.githubusercontent.com/45708377/67092707-98b84380-f1b8-11e9-8302-12723f76916f.png)

**Comment by WeaselDog** [comment]
Looks good. Tested on smaller resolutions:
![CharredFood](https://user-images.githubusercontent.com/47330823/70363576-c5461e80-183d-11ea-9449-73bff06b7b4f.png)

**Comment by beastyn** [comment]
Hm, still the same for me
![bandicam 2019-12-09 11-04-00-782](https://user-images.githubusercontent.com/27898520/70411319-ac26b300-1a73-11ea-819b-91874c67f86c.jpg)

**Comment by SlayksWood** [comment]
@Sekor2600 
Discussed today about separating this recipe to Fruits and Vegetables.

**Comment by SlayksWood** [comment]
Some flaws:
1. You can add another recipe as Charred Greens.
Fruit: Giant Cactus Fruit, Huckleberries, Papaya, Pineapple, Prickly Pear Fruit, Pumpkin.
Vegetable: Beans, Beet, Camas Bulb, Corn, Heart of Palm, Taro Root, Tomato.
Greens: Beet Greens, FiddleHeads., Agave. Fireweed shoots.
And we have more balance in ingredients for Campfire Salad which uses for reseaching.
2. Seems you forgot to changeparent recipe for many items:
![image](https://user-images.githubusercontent.com/45708377/72049093-4f672400-32cf-11ea-84da-88c9709f6305.png)
![image](https://user-images.githubusercontent.com/45708377/72049106-542bd800-32cf-11ea-82f5-6b8baabc7174.png)

**Comment by SlayksWood** [comment]
in Fruit we have Giant Cactus Fruit which have icon from Prickly Pear Fruit. And i don't know where I can harvests it.
@keegan-o 
We had plans to add new plants in 0.9.0 or this is a mistake?
