### ISSUE TITLE
[Master] Soilsampler Window

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13374]
The Soilsampler window ist in the moment always small
![grafik](https://user-images.githubusercontent.com/37456949/67034310-bbdee680-f117-11e9-9c23-208558738928.png)

You can change the size only a little irritating

**Comment by WeaselDog** [comment]
Would like to add that temperature is displayed differently than other entries. It should be a percent instead of 0.* degrees

**Comment by SlayksWood** [comment]
#dup13111
