### ISSUE TITLE
[master-preview] Can build on top of a plant

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13386]
And when Im soing so a block can float in the air. When you try to place a block on top of a plant - 
plant should be destroyed.
![bandicam 2019-10-21 11-49-38-118](https://user-images.githubusercontent.com/27898520/67183841-d8bb3880-f3fb-11e9-9853-529b503424e2.jpg)

**Comment by elfl0rd** [comment]
maybe this issue has same root? https://github.com/StrangeLoopGames/EcoIssues/issues/10538

**Comment by beastyn** [comment]
don't think so, its a regression, Its ok in 8.3.

**Comment by redwyre** [comment]
@beastyn I think this is fixed

**Comment by beastyn** [comment]
Still here
![bandicam 2019-11-13 14-19-42-389](https://user-images.githubusercontent.com/27898520/68749857-bf836180-0620-11ea-8f26-c7ed8f1adbd9.jpg)
![bandicam 2019-11-13 14-19-58-099](https://user-images.githubusercontent.com/27898520/68749862-c0b48e80-0620-11ea-8fb1-4cccecf0d962.jpg)

**Comment by redwyre** [comment]
This only happens with that specific plant, @keegan-o do you know what it is? It says "Plant fibers" in game...

**Comment by elfl0rd** [comment]
afaik it is Filmy Fern

**Comment by beastyn** [comment]
Fern, yes

**Comment by redwyre** [comment]
This one must have something to do with the plant block, I'm not sure why though. Hammer might be ignoring "BlockPlacedAtOffset" (which is false)?

**Comment by SlayksWood** [comment]
I can't place block to another block. Place to ground:
![image](https://user-images.githubusercontent.com/45708377/78968522-871f7b00-7b0d-11ea-9a5b-6b8be4ed6419.png)
try to place to another block:
![image](https://user-images.githubusercontent.com/45708377/78968543-90a8e300-7b0d-11ea-982f-37198202392d.png)
 I can't

**Comment by SlayksWood** [comment]
I can't place block to something that I can select.
