### ISSUE TITLE
USER ISSUE: Server not found

### ISSUE THREAD

**Issue by Hansinsan** [StrangeLoopGames/EcoIssues#13382]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by Hansinsan** [comment]
found no Server, Single player ok

**Comment by D3nnis3n** [comment]
Hallo,
es handelte sich um eine temporäre Fehlfunktion unserer Master-Server, sollte alles wieder funktionieren.
