### ISSUE TITLE
[master-preview] Ashlar Conclave Blocks display

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13388]
Fence:
![image](https://user-images.githubusercontent.com/45708377/67187337-a78a3a80-f3f2-11e9-8023-8783cc7c6555.png)
SlopePoint: 
![image](https://user-images.githubusercontent.com/45708377/67187398-c7b9f980-f3f2-11e9-9d52-9f61f5f552a3.png)
Brace:
![image](https://user-images.githubusercontent.com/45708377/67187425-d86a6f80-f3f2-11e9-8cb4-2aea9ceafac4.png)
Ladder:
![image](https://user-images.githubusercontent.com/45708377/67187446-e15b4100-f3f2-11e9-922b-6a231ac27df3.png)

**Comment by SlayksWood** [comment]
as #11814

**Comment by redwyre** [comment]
@SlayksWood this should all be fixed with https://github.com/StrangeLoopGames/Eco/pull/5197
