### ISSUE TITLE
USER ISSUE: Found no Server

### ISSUE THREAD

**Issue by Hansinsan** [StrangeLoopGames/EcoIssues#13383]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Fehler beim Verbinden - Verbindungszeit überschritten.
```

**Comment by SlayksWood** [comment]
dup #13382
