### ISSUE TITLE
Missing Ashlar Forms: Wall, DoubleWindow, FLoor.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13387]
![image](https://user-images.githubusercontent.com/45708377/67186759-69404b80-f3f1-11e9-85e7-4889e99a1eea.png)
![image](https://user-images.githubusercontent.com/45708377/67186769-6cd3d280-f3f1-11e9-9f25-eb7460b98779.png)
![image](https://user-images.githubusercontent.com/45708377/67186781-70fff000-f3f1-11e9-8f5c-5e581d27c710.png)

**Comment by SlayksWood** [comment]
Can you add SideBrace as in Composite Lumber?

**Comment by keegan-o** [comment]
Fixed in staging, added content for all these. Also added side braces.
