### ISSUE TITLE
0.8 and master - removeaccountmanager have "add" in description.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13397]
![изображение](https://user-images.githubusercontent.com/4980243/67223659-5ac95280-f438-11e9-8466-279c01327845.png)

**Comment by elfl0rd** [comment]
@beastyn i think it is fixed incorrect...
"Removes user as manager to bank account with ID."?
I think it's looks ugly =|

**Comment by Sekor2600** [comment]
@elfl0rd 
hm maybe "Remove user as manager from bank account with ID" ?

**Comment by elfl0rd** [comment]
Agree, looks better.

**Comment by elfl0rd** [comment]
@Sekor2600 Agree, looks better.
