### ISSUE TITLE
[master-preview] Ramp type blocks placing strange

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13394]
It works for composite lumber materials. When you try to place different type of materials as ramp type blocks, the smallest one seems to be displaced and textures are messy.
![bandicam 2019-10-21 16-04-40-068](https://user-images.githubusercontent.com/27898520/67200183-83dbea00-f41c-11e9-9979-ada74276159a.jpg)

**Comment by keegan-o** [comment]
Fixed in staging for 9.0
