### ISSUE TITLE
[master-preview] PeatRoof in Softwood and Hardwood Hewn Log

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13391]
Is this a mistake or not? Because there is no such block in Hewn Log.
![image](https://user-images.githubusercontent.com/45708377/67198604-fdb5a880-f407-11e9-9f31-34614bbd5097.png)
![image](https://user-images.githubusercontent.com/45708377/67198629-0ad29780-f408-11e9-95bb-78cc6e5926c4.png)
If It isn't a mistake, then you need to add them to the Hewn log and add  form.

**Comment by SlayksWood** [comment]
Also There are empty WindowGrilles and Fence with Hewn log, but it's missing in Hardwood and SoftWood Hewn Log.

**Comment by SlayksWood** [comment]
See #13562
> Afaik, BASIC hewn logs have model...
> But form is not added to selection :D

**Comment by redwyre** [comment]
peat roof removed, grills fixed on lumber types

**Comment by elfl0rd** [comment]
> peat roof removed

Why? It's cool form, idk :(

**Comment by beastyn** [comment]
No Fence for hardwood and softoows hewn log?
Also Fence for Hewn Log still doesn't have a model.

**Comment by SlayksWood** [comment]
We had form for PeatRoof in 8.3.0:
![image](https://user-images.githubusercontent.com/45708377/70983800-66e52f80-20ca-11ea-81e0-49ab6939331c.png)
You can't select it with hammer but can see it if you use command "/allconstructed" in 0.8.3.
It would be nice to add it too.

**Comment by elfl0rd** [comment]
yes, i love it :) looks cool.

**Comment by keegan-o** [comment]
Fixed in staging, at last. We will get peat roofs eventually, but it will only be when we get another pass on ecosystem materials, such as for glacial ice and real peat in wetlands, etc.
