### ISSUE TITLE
[master-preview] Tangling in Softwood, Hardwood, Lumber.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13390]
1. Lumber color on the icon remained from 8.3. But Lumber color was changed (presumably).
![image](https://user-images.githubusercontent.com/45708377/67196780-276cd080-f404-11e9-82f4-e1c20ef961c0.png)
Color should be as at Hardwood/Softwood Lumber.
![image](https://user-images.githubusercontent.com/45708377/67196983-8599b380-f404-11e9-9866-220140c67bbd.png)
2. Lumber texture color is wrong. In Stair, Ladder, Window, Fence It takes color from Hardwood. In partially Сolumn, Roof, Wall and Cube(different look, but one color) It takes color from Softwood. Only Floor looks like a mixture of Softwood and Hardwood. But I'm not sure that this is also correct.
3. Tangling in Window and WindowGrilles blocks.
For Hardwood: Window block look like WindowGrilles. WindowGrilles is missing.
![image](https://user-images.githubusercontent.com/45708377/67197783-3c4a6380-f406-11e9-8be3-512d00e6a50b.png)
For Softwood: WindowGrilles is called as WindowT2 and looks like Window. Window looks like WindowGrilles:
![image](https://user-images.githubusercontent.com/45708377/67197891-74ea3d00-f406-11e9-8bb9-70b3780eea44.png)

**Comment by keegan-o** [comment]
It's an open question as to whether we might want to make the generic lumber have its own look-- for now, in my mind, it makes sense to have it as a mix of hardwood and softwood, as that is what it almost certainly is in terms of what players are adding to the crafting table to make it. 

The icons are fixed now in staging and I fixed the window grilles block bugs as well as made the generic lumber have a mix of wood types for the window grilles block. 
![image](https://user-images.githubusercontent.com/14983165/70105308-4b235900-15f5-11ea-9cd3-b734277bef22.png)
