### ISSUE TITLE
USER ISSUE: Online Timeout Bug

### ISSUE THREAD

**Issue by RedstoneBoy0509** [StrangeLoopGames/EcoIssues#13396]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
I don't know what this means.

**Expected behavior:**
Let me play my world.

**Actual behavior:**
Showed the message Connection Timed Out.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Showed the message Connection Timed Out.

**Comment by beastyn** [comment]
not enough information. Will be fixed with actual task
