### ISSUE TITLE
[master-preview] Need check for composite ceiba lumber texture

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13392]
For some blocks I can see that texture doesn't have darker part for some sides.

1. Top view for composite ceiba lumber floor - texture has darker left and right edge.
![bandicam 2019-10-21 13-39-10-488](https://user-images.githubusercontent.com/27898520/67198706-f34fda80-f418-11e9-8dd7-30196f6a9101.jpg)
2. But from the front and back point of view it has all the same color.
![bandicam 2019-10-21 13-39-38-659](https://user-images.githubusercontent.com/27898520/67198750-0fec1280-f419-11e9-9609-307225e5efd7.jpg)

For comparison - floor blocks from the different composite materials. Only ceiba doesn't have this fancy edging.
![bandicam 2019-10-21 13-36-44-090](https://user-images.githubusercontent.com/27898520/67198869-52155400-f419-11e9-8e7d-59f2006a0fa3.jpg)

**Comment by SlayksWood** [comment]
fixed with new floor block
![image](https://user-images.githubusercontent.com/45708377/75675965-57bd5900-5c99-11ea-9486-8b64e99b31cc.png)
