### ISSUE TITLE
[master-preview] Missing New Blocks in Hammer UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13393]
Perhaps, It was lost before changing the hammer UI. Composite Lumber blocks at the moment:
![image](https://user-images.githubusercontent.com/45708377/67199608-5be38b00-f40a-11e9-8022-33e1dd80df9f.png)
But @keegan-o added BasicSlopeBlocks and CornerStairsBlocks:
![65287236-43284280-daf7-11e9-97d0-73f658b76c31](https://user-images.githubusercontent.com/45708377/67199748-b67ce700-f40a-11e9-9c6e-e5c22c1fbbae.png)
I remember that they were added. And I have some screenshots:
![image](https://user-images.githubusercontent.com/45708377/67199850-ed52fd00-f40a-11e9-80be-be6d13754c99.png)
![image](https://user-images.githubusercontent.com/45708377/67199888-fd6adc80-f40a-11e9-8ab8-1db72b36d77b.png)
Screenshots taken September, 23

**Comment by beastyn** [comment]
Added @craig-jong as I can't find them in BlockFormTypeTemplate

**Comment by redwyre** [comment]
@craig-jong They're missing from the BlockFormTypeTemplate list, and also need to be added to the FormsTemplate list.

@keegan-o Which block types should they be added to?

**Comment by Quadbro** [comment]
yeap, hammer code just pulls from BlockFormTypeTemplate  list, so just add them there)

**Comment by craig-jong** [comment]
I'm adding the block forms to Composite lumbers (all types). They'll also be in there if we need to add them to other types.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/69105309-b975f200-0a1f-11ea-89c1-51d2c430fd5f.png)
Fixed in staging for composite lumber materials.
