### ISSUE TITLE
Worldgenerator.eco raised every time while generates new world

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13400]
Just look my worldgen...
[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3752402/WorldGenerator.zip)
And fresh one...
[WorldGenerator_fresh.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3752411/WorldGenerator_fresh.zip)
@mirasrael ?

**Comment by D3nnis3n** [comment]
This seems to happen when changing something in the orespawn / biome brackets, not for all general configuration, though.
