### ISSUE TITLE
[master-preview] Chat issues

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13404]
- [x] "Hide tutorial text when opening chat, it overlaps to make it unreadable"
or darken the icon too, or just hide tutorial text
![image](https://user-images.githubusercontent.com/45708377/67266219-56447e80-f4b8-11e9-9c34-f56f76ffdaf2.png)
![image](https://user-images.githubusercontent.com/45708377/67266230-6197aa00-f4b8-11e9-8367-8bdf584bfae7.png)

- [x] Make the minimum chat width smaller.
![image](https://user-images.githubusercontent.com/45708377/67267380-d2d85c80-f4ba-11e9-90a8-c34fb8eefcd8.png)

- [x] Top Chat settings window missing lines
![image](https://user-images.githubusercontent.com/45708377/67267136-6198a980-f4ba-11e9-859d-7987cc8d9f7f.png)
Сonsider the possibility of long localization "Set notification to display" = "Установить уведомление для отображения" for example.

- [x] Over time, Top chat stops hide and stays in that position.
![image](https://user-images.githubusercontent.com/45708377/67267558-36fb2080-f4bb-11e9-946b-ae6ea1a80cdb.png)

- [x] Top chat still disappears quickly.

- [x] "Allow people to view important notifications". How can I view it? Seems nothing changed

**Comment by gzatravkin** [comment]
>  "Hide tutorial text when opening chat, it overlaps to make it unreadable"
> or darken the icon too, or just hide tutorial text

Screenshot have not tutorial text. It's suppose to autohide it and desactivate when notifications is expanded. Is not working in this way now? 

>  "Allow people to view important notifications". How can I view it? Seems nothing changed
Now it's guaranted that all important notifications are not temporal messages. So they always will be in chat log. 

Don't think it will be right to leave them premamently in right panel - usually they are requiered to be read once, not to be always visible. I.e. they are important but to be read right now and then dismiss, not all the time.

**Comment by SlayksWood** [comment]
1. Or both transparent or both not.
![image](https://user-images.githubusercontent.com/45708377/67387809-486a2880-f5a0-11e9-975c-f92265f1825b.png)
2. It is strange for me to have a separate chat for important messages, then to look for this important information in chat log.

**Comment by SlayksWood** [comment]
- [ ] The last lines in the right chats are partially cropped.
![image](https://user-images.githubusercontent.com/45708377/67388161-d3e3b980-f5a0-11e9-95fb-027d8252a300.png)

**Comment by gzatravkin** [comment]
All issues by this one were fixed. 
" "Allow people to view important notifications". How can I view it? Seems nothing changed"'
This will be managed as part of rework of important notifications
https://github.com/StrangeLoopGames/EcoIssues/issues/13432
