### ISSUE TITLE
Filter selector should not fall behind other UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13403]
![image](https://user-images.githubusercontent.com/3536496/67254026-a4616f80-f42f-11e9-8dc9-309909806d30.png)

- Open court, open law
- Make trigger for harvest, select species
- Click law while selector box is open
- Selector box will go behind law and become un-retreivable until law window is closed and reopened.

Filter should be either modal, or behave like the dropdowns in that it auto-closes when clicking away.

**Comment by beastyn** [comment]
dup #13885
