### ISSUE TITLE
Add icons for all species

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13402]
Need to make icons for each species and name them '<speciesname>Species' in the icon table. This will make them work in searchable lists, and we can remove the hack used in chat icons that uses the resourcetype for their icon. 

Right now species selector looks like this
![image](https://user-images.githubusercontent.com/3536496/67253879-e938d680-f42e-11e9-8fa4-b0ba886b2f02.png)

**Comment by SlayksWood** [comment]
You have this icons if you use display with String:
![image](https://user-images.githubusercontent.com/45708377/71173095-f0376600-2272-11ea-8f03-0da61a5d52fa.png)

**Comment by keegan-o** [comment]
Added all species icons into eco.unity, the chat thing can now be removed to finish this bug off!

**Comment by keegan-o** [comment]
May require testing, it is hard to test when none of the laws spawning commands work (they all cause server exceptions)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/73326759-2bc93680-4208-11ea-8d4b-14bfb52a6a29.png)
Assigning to 9.0 since it will be good to have these proper icons for species with things like the ecopedia.

**Comment by keegan-o** [comment]
has been done in staging for a while now though the code part might be broken as far as linking them up
