### ISSUE TITLE
Optimize chat link composition

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13412]
Run /qa chattest to make this one happen. Youll see it takes a long time in this function:
![image](https://user-images.githubusercontent.com/3536496/67437004-a8fb6480-f5a4-11e9-8d4e-49b2180c6f18.png)

Optimize string processing to make this better.

**Comment by gzatravkin** [comment]
Investigated. String processing is not a problem in that case, it's slow because of Linq lazy operations.
Perfoms slowly to find links to ignore in lazy ienumerable
Fixed by adding .ToList(). (From 15000ms to 3000ms)
