### ISSUE TITLE
[master-preview] Machete can destroy grass 2 times per 1 animation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13423]
![2019 10 24 Machete can destroy grass 2 times per 1 animation](https://user-images.githubusercontent.com/45708377/67468896-013d6f80-f654-11e9-884a-b9df7e09fec5.gif)
It cost "uses remaining" and calories for 2 times. But it's look a little wrong.

**Comment by redwyre** [comment]
Weird, I'm not sure how that works

**Comment by elfl0rd** [comment]
I love this feature :D

**Comment by Quadbro** [comment]
tweaked callories use and animation, so now you can use 2 hit feature of machete with no loses
