### ISSUE TITLE
Something causes all animals to die

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#1342]
http://ecoforum.strangeloopgames.com/topic/2177/animal-wipeout-the-rabbit-turkey-conspiracy-bug/6

**Comment by MGrand3** [comment]
The user had also mentioned seeing some animals "reappear", could mean it's an issue with the wrong number of animals showing?

**Comment by metachronism** [comment]
this still happens, most notably with wolves in a6

**Comment by craig-jong** [comment]
I don't think they're "dying off", they just aren't around at all.
