### ISSUE TITLE
web not displaying laws

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13427]
Active and proposed laws are not being displayed
![image](https://user-images.githubusercontent.com/3536496/67518834-698f4f80-f65a-11e9-8f85-abde73034985.png)

However there are active ones, as the query shows:
![image](https://user-images.githubusercontent.com/3536496/67518842-6f853080-f65a-11e9-8f2d-5d2dc2f40d12.png)

**Comment by beastyn** [comment]
still here

**Comment by beastyn** [comment]
We have Active Laws now in the list. But Proposed (in the election state) are not showing.
