### ISSUE TITLE
0.8 joshua debris display distance is too small

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13430]
checked in master, still actual
![20191024203849_1](https://user-images.githubusercontent.com/4980243/67523557-9887de80-f6b7-11e9-8ef5-6996de5251c1.jpg)
![20191024203846_1](https://user-images.githubusercontent.com/4980243/67523561-9aea3880-f6b7-11e9-9bab-6db3c865cbec.jpg)

**Comment by keegan-o** [comment]
fixed in 9.0
