### ISSUE TITLE
[[0.9.0 staging-1183] no shadow placement after login

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13439]
1, Login
2. Your toolbar should be empty
3. Take something in carried
4. Try to put it down
5. No shadow placement
6. Take hammer. Shadow placement will appear. And will be fine even with empty tool.
![bandicam 2019-10-25 13-04-41-506](https://user-images.githubusercontent.com/27898520/67554571-1e903d80-f729-11e9-9f44-e72a6256b880.jpg)

**Comment by redwyre** [comment]
Seems to be working fine, previous changes may have fixed it?

**Comment by beastyn** [comment]
Nope, still here.
But in a strange way. When you are logging in, you don't see shadow placement. But some movement around triggers it.
https://i.gyazo.com/a0b4fe36f6d53232b1521a3b514b1fc9.gif

**Comment by redwyre** [comment]
Not sure what's up with this one, probably something not getting initialised properly in the `InteractionManager`

**Comment by beastyn** [comment]
fine now
