### ISSUE TITLE
Master: store interface size issue

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13431]
If you resize store window to smaller one...
Buttons overlap and fields look sick.
![изображение](https://user-images.githubusercontent.com/4980243/67524104-c3befd80-f6b8-11e9-9461-7fd19c767de4.png)

**Comment by SlayksWood** [comment]
It works fine almost with all items:
![image](https://user-images.githubusercontent.com/45708377/69037459-fb3f7200-09f8-11ea-860b-9159ef15a505.png)
But when you buy/sell Tools you have additional cell:
![image](https://user-images.githubusercontent.com/45708377/69037888-c849ae00-09f9-11ea-8862-a0c30eb06627.png)

**Comment by beastyn** [comment]
Nope, still here
![bandicam 2019-11-21 10-35-09-209](https://user-images.githubusercontent.com/27898520/69306842-b27ef780-0c4a-11ea-9b67-5511906fedcc.jpg)
