### ISSUE TITLE
EcoServer.sh needs to point elsewhere, EcoServer32.sh might be removed

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13434]
EcoServer.sh still starts the server via mono, despite dotnet EcoServer.dll --nogui available.
EcoServer32.sh tries to work with EcoServer32.exe which doesnt exist anymore - not sure if that is intended, either.

**Comment by mirasrael** [comment]
@jaskes We need custom build for Linux instead (you can publish it in the same way as Win executable, but with -p:RuntimeIdentifier=linux-x64). Also need to update Steam upload to use slightly different distributive (without windows executable, but with Linux executable instead). Then we can remove .sh files.

**Comment by D3nnis3n** [comment]
Has the build already been made that @mirasrael mentioned? The commit doesn't mention that.

**Comment by redwyre** [comment]
We're still refining the new server, but these scripts wont be needed
