### ISSUE TITLE
Fix spawning buildings for new material types

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13436]
/bt 4 yields the broken one:
![image](https://user-images.githubusercontent.com/3536496/67537302-9e69c980-f68f-11e9-9c1d-6fe122ccdb27.png)

**Comment by SlayksWood** [comment]
The problem arises from blocks missing: #13387. 
When all the blocks will be present, the house will be built, but there will be no roof, because in new blocks there is no Roof block.
Now I use for t4 building command: /bm Flat Steel,10,5,10,1,1 for example.

**Comment by beastyn** [comment]
should work fint now
