### ISSUE TITLE
[0.8.3.0] After crash, server does not start

### ISSUE THREAD

**Issue by BurtGummer** [StrangeLoopGames/EcoIssues#13437]
Hello,

I have restart my Server without stopping eco. Now, eco does not start. I have attach the log. Any ideas how I can start the server again?

https://dlsz.de/s/log_191025075023.log

**Comment by SlayksWood** [comment]
@BurtGummer 
Are you tried to run the last backup?

**Comment by D3nnis3n** [comment]
Your save has corrupted. Never restart the server without stopping Eco first.
You'll have to restore one of the latest backups before the crash to get it to work again.

Generally, this is not a bug.
