### ISSUE TITLE
Economy viewer resize issue.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13445]
Actual for 0.8.3 and fresh master
- [ ] Resize work uncorrect.
- [ ] Scrolling in right area is not working
![изображение](https://user-images.githubusercontent.com/4980243/67596181-d432af00-f770-11e9-8862-73537672d996.png)

**Comment by beastyn** [comment]
Now text can be on the scroll
![Uploading bandicam 2019-10-30 14-05-39-949.jpg…]()
