### ISSUE TITLE
[0.9.0 staging-1183] Wrong shadowplacement for Stones.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13440]
It looks rotated 180 degrees. If good shadowplacement appears, then hover over the stone again.
![image](https://user-images.githubusercontent.com/45708377/67556009-13361580-f71b-11e9-8532-2b1d0112e84e.png)
![image](https://user-images.githubusercontent.com/45708377/67556019-16310600-f71b-11e9-9036-7fed8e173650.png)
![image](https://user-images.githubusercontent.com/45708377/67556022-17623300-f71b-11e9-81e6-f1ec6c6af72c.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/78781541-1fe8b600-79a9-11ea-999b-40237fc47817.png)
