### ISSUE TITLE
[5.5.4] Issue with tree's being planted to close together

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1345]
We have a number of players who thought it was a smart idea to plant a hundred trees directly beside each other. When a tree is cut down it bugs out so much the nearby players' frame rate drops to next to nothing, can cause client crash or cause a player to be fired across the map by the log.
Also seems to make the server as a whole suffer.

A bug that's been existing since mass tree farming was an option from 5.5.0.

**Comment by benjamin-willard** [comment]
You should make it so that trees cannot be planted no more than like 2 tiles from each other or something or they die within an instant....

**Comment by metachronism** [comment]
craig fixed for 5.6
