### ISSUE TITLE
no hat

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13453]
Could not don my hat, whole panel turned green when i tried to drag
![image](https://user-images.githubusercontent.com/3536496/67727615-53a9c380-f9a7-11e9-8a8f-e68a1114278b.png)

**Comment by gzatravkin** [comment]
Can't reproduce it. Stil occur? Please attach a video of reproduction

**Comment by beastyn** [comment]
I can place a  hat, but I see this green backgorund
It seems like kind of intended. You can discuss it with Sergey.

**Comment by gzatravkin** [comment]
"it works now!" From John
