### ISSUE TITLE
Character Creation issues

### ISSUE THREAD

**Issue by RobertMangano** [StrangeLoopGames/EcoIssues#13469]
![character](https://user-images.githubusercontent.com/26705633/67729931-e2b5ea80-fa3e-11e9-99aa-dc4e33b59d1e.jpg)
Hair colour was stuck on a single colour, and the belt would not change when cycling between the two options. Also in the facial hair category, there was a head hair icon displaying. 

It was also difficult to see my character with plants and bushes in the way, perhaps anything that gets in between the character and camera should be clipped during character creation.

**Comment by SlayksWood** [comment]
dup #13338
