### ISSUE TITLE
[5.5.4] Game engine seems to struggle with large volumes of work orders and land claims

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#1346]
Our server is currently planning a wipe as a result of this,
Our server is on day 17, 315 citizens and up to 30 players online at any one time.
Each player queuing up to 48 hours of crafting, whether it has all resources or just a percentage of them on dozens of tables as well as a large volume of land claims has made all processes come to next to a complete halt. 10+ minute wait on carts when you interact with them to move, crafting is delayed by a few minutes and the timer just stops and start on the crafting and fuel consumption.

My suspicion is that the game engine is cycling through the workbenches etc to see if all required items have been added, processing the large number of orders etc is what is bringing the progress to a halt

**Comment by Stephenw92-git** [comment]
http://ecoforum.strangeloopgames.com/topic/2174/new-bugs

**Comment by metachronism** [comment]
this may or may not have been largely caused by the deadlock issue, will leave open for a bit after 5.6 is out

**Comment by metachronism** [comment]
inventory refactor for alpha 6 fixes this
