### ISSUE TITLE
Minimap 2D mode shows trees on empty space

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#13464]
![image](https://user-images.githubusercontent.com/53317567/67728328-a1382780-f9cb-11e9-9f32-9ac843274d77.png)
When minimap is in 2D fullworld mode it shows some trees on empty space

**Comment by SlayksWood** [comment]
Maybe it needs to add a limit to scrolling the 2D map? so that it was tied to the sides:
![image](https://user-images.githubusercontent.com/45708377/67741030-dde63c00-fa28-11e9-881f-b6629aa6415b.png)

**Comment by SlayksWood** [comment]
Trees not only shows in empty space, they are absent in another part of the map
![image](https://user-images.githubusercontent.com/45708377/67741251-92805d80-fa29-11e9-9f13-6687a0c5a598.png)
