### ISSUE TITLE
Voice in-game issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13461]
- [x] Push to talk needs to be selected by default
- [x] Key needed to 'push to talk' should be displayed alongside the 'push to talk' selection option
- [x] There should be indication that  I am broadcasting when I hold push to talk, or have an open mic broadcastsing.
- [x] The audio menu should show me which mic is selected, if its setup correctly, give me the option to change mics.  I had a mic setup and working, but no mics were displayed in the menu
- [x] Couldnt tell what radius the chat worked at (is adjustable by client?)
- [x] Milenko was unable to use push to talk, test with him

**Comment by redwyre** [comment]
Indicator icon fixed in SVN
