### ISSUE TITLE
Some icons are missed on minimap

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#13463]
![image](https://user-images.githubusercontent.com/53317567/67728269-62a26d00-f9cb-11e9-8462-1a431f35a352.png)
When you move it will hide them 
![image](https://user-images.githubusercontent.com/53317567/67728280-71891f80-f9cb-11e9-9084-fd50e940d957.png)

**Comment by SlayksWood** [comment]
Not all world objects are displayed. I am 100% sure that most of the new Civics objects are not displayed

**Comment by serpopov** [comment]
@SlayksWood looks like it is good now?

**Comment by beastyn** [comment]
Nope, 1526 still here.
You can see it when moving the map.
![bandicam 2020-04-24 16-22-17-837](https://user-images.githubusercontent.com/27898520/80207600-ddc9a080-8647-11ea-8b46-b65035a9de9f.jpg)
![bandicam 2020-04-24 16-22-22-066](https://user-images.githubusercontent.com/27898520/80207602-defacd80-8647-11ea-96d9-ce53caacbc3c.jpg)

**Comment by beastyn** [comment]
Seems we have disappering case with this black circles. Icons will disappear under them.
![bandicam 2020-05-07 11-52-22-840](https://user-images.githubusercontent.com/27898520/81263590-5f162f80-9059-11ea-8128-c12481d5def3.jpg)
![bandicam 2020-05-07 11-52-34-541](https://user-images.githubusercontent.com/27898520/81263593-60475c80-9059-11ea-9cdb-d4f83a14cc3b.jpg)

**Comment by SlayksWood** [comment]
It became worse. Now they are visible only in small circle:
![image](https://user-images.githubusercontent.com/45708377/83228824-962abd00-a18f-11ea-9eb4-77b00ac725e0.png)
Also need check this one #16338 after fixing

**Comment by SlayksWood** [comment]
Still haven't icons in red corners. But it's not critical now, so we can push it.
![image](https://user-images.githubusercontent.com/45708377/84359929-04c93b00-abd2-11ea-9d30-aaf2991cdd9c.png)

**Comment by SlayksWood** [comment]
It good work for player icons:
![image](https://user-images.githubusercontent.com/45708377/84738278-4b43de80-afb2-11ea-995f-ab522fd4c94d.png)
But I can see, for example, civics icon only in small circle:
![image](https://user-images.githubusercontent.com/45708377/84738359-762e3280-afb2-11ea-9896-056191fe79cf.png)
Perhaps it was in the previous version too.
