### ISSUE TITLE
Some images at Eco steam page contain black lines.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13479]
(because of the wrong aspect ratio)
e.g.
![изображение](https://user-images.githubusercontent.com/4980243/67789052-65ad6400-fa84-11e9-9495-bb8b19a6c93b.png)

![изображение](https://user-images.githubusercontent.com/4980243/67789120-7b228e00-fa84-11e9-9328-7eb80a91cafb.png)
etc.

**Comment by elfl0rd** [comment]
i crop two images to 1.777 (16:9) aspect ratio, if someone want to fix it, i can crop another 7 =|
https://www.dropbox.com/s/u6x8ggfxkkmfuig/goat.jpg?dl=1
https://www.dropbox.com/s/u3hwl04lkn4anq2/Coyote.jpg?dl=1

**Comment by elfl0rd** [comment]
@D3nnis3n @johnkslg

**Comment by D3nnis3n** [comment]
Post the others, i'll put them in.

**Comment by elfl0rd** [comment]
Check a couple before you replace all
(and maybe you want to rename it :D)

https://www.dropbox.com/s/eddyn2ppoq382xo/3.jpg?dl=1
https://www.dropbox.com/s/ztqyey9bq4770wd/4.jpg?dl=1
https://www.dropbox.com/s/z6emraoyvhfz4nm/5.jpg?dl=1
https://www.dropbox.com/s/m1ugvkd9v8yna8c/6.jpg?dl=1
https://www.dropbox.com/s/2u85zztsa4rbuuz/7.jpg?dl=1
https://www.dropbox.com/s/d7kbwhxpkqhdz7q/8.jpg?dl=1
https://www.dropbox.com/s/oy6yzoalvvxq82a/9.jpg?dl=1

**Comment by D3nnis3n** [comment]
Thanks for your help, the aesthetical issue should be fixed now. :)
