### ISSUE TITLE
[0.9.0 staging-1189] Remove tools from profession tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13475]
I should get Iron Axe, Iron Pickaxe, Bow, Iron Scythe when I take Logging, Mining, Hunting, Farmer.
![image](https://user-images.githubusercontent.com/45708377/67746587-c9f60680-fa37-11e9-8c9e-4a8c564d963f.png)

**Comment by beastyn** [comment]
So, It was decided to remove them, need to clear tooltip with techtree.
