### ISSUE TITLE
[0.9.0 staging-1189]Overlap text in small UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13476]
![image](https://user-images.githubusercontent.com/45708377/67747500-e5faa780-fa39-11e9-8188-105d5c3a2d45.png)

**Comment by beastyn** [comment]
still an issue
![bandicam 2019-11-18 10-06-25-056](https://user-images.githubusercontent.com/27898520/69026049-27ec8d00-09eb-11ea-8f71-504a6107f134.jpg)
