### ISSUE TITLE
Map Layers over time does not work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13484]
The web ui should display changes in layers over time, just like it does for the surface of the world (players building stuff). It doesn't do, the map stays black / grayish. (Edge + Chrome tested)

**Comment by j3fffff** [comment]
@D3nnis3n more important the showing layers over time, why is the map all black? think thats fixed right?

can you explain this a little more?

**Comment by D3nnis3n** [comment]
I tested layers that do not exist on day one. There is no trample, hence its black. Over time trample builds up, but isnt shown in the timeshift.

**Comment by j3fffff** [comment]
so maps over time isnt working at all. just displays one map, but layer gif is not playing

**Comment by denysaw** [comment]
@gzatravkin I get there's at least symbiosis with server needed changes. Re-assigned on you ;)

**Comment by keegan-o** [comment]
I couldn't get the maps to show things being built/changed at all over time, either-- so no changes over time working for me currently.

**Comment by beastyn** [comment]
Objects are showing the changes as layers. Thank you!

**Comment by j3fffff** [comment]
https://github.com/StrangeLoopGames/Eco/pull/6743
