### ISSUE TITLE
Advanced crafting button not visible if you not have requied skill

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13482]
Version: 0.9.0.0 beta staging-debug
As result, no way to see what items inside this crafting group.
Maybe disabling "craft" button inside is better?
![изображение](https://user-images.githubusercontent.com/4980243/67799330-34d62a80-fa96-11e9-8d60-7e9950041c16.png)
![изображение](https://user-images.githubusercontent.com/4980243/67799351-3a337500-fa96-11e9-8080-09fa518f3ded.png)

**Comment by SlayksWood** [comment]
dup #13238
