### ISSUE TITLE
0.9 some reciepes not show all results.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13483]
Version: 0.9.0.0 beta staging-debug
There is no "by-product" in receipe results.
But you get it, and can see in subwindow
![изображение](https://user-images.githubusercontent.com/4980243/67895084-e9418080-fb6a-11e9-8f9c-47c4616df7e3.png)

![изображение](https://user-images.githubusercontent.com/4980243/67895159-08401280-fb6b-11e9-9bac-0c2b658b9f4c.png)
![изображение](https://user-images.githubusercontent.com/4980243/67895183-10984d80-fb6b-11e9-8e60-b9e32a12791e.png)

![изображение](https://user-images.githubusercontent.com/4980243/67895215-21e15a00-fb6b-11e9-8f98-c0f542992824.png)

etc.

**Comment by WeaselDog** [comment]
Thanks for the report!

I double checked all the examples and they are fixed. I believe this was an issue with parent recipes that are no longer there.

Please let us know if this is still an issue with any other recipes.
