### ISSUE TITLE
[0.9.0 staging-1206] Slow UI for tables

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13486]
It takes about 1.5 sec to switch between tabs. Shouldn't be so slow.
![cbc5a70bf4f44962de774538a9536098](https://user-images.githubusercontent.com/27898520/67847331-7f9e8380-fb24-11e9-867a-69fea040f595.gif)

Ad fps in this moment is dropping too, Fro, 20 to 10

**Comment by mirasrael** [comment]
Returned to 9.0, because it may significantly affect player experience.

**Comment by beastyn** [comment]
It still somehow laggy.
For Storage, Crafting tabs especially.
![ddb0ffde6b981c5e94350da311d03201](https://user-images.githubusercontent.com/27898520/85289265-9416fe00-b4b0-11ea-8904-e2c7a11d4ad0.gif)
