### ISSUE TITLE
[0.9.0 staging-1206] Snapping door handles with tree fall

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13487]
Just cut the tree and hear how hundreds of doors open.

**Comment by Quadbro** [comment]
:D

**Comment by SlayksWood** [comment]
from #13727
> To reproduce chop a tree into logs and then walk into the logs on the ground. Every time the logs move it makes the sound of a door opening. Chopping down a tree will make the same sound, so it is anytime logs move.

**Comment by Quadbro** [comment]
problem found and pushed to Leonard, waiting for him to fix brocken switches in wwise editor
