### ISSUE TITLE
[0.9.0 staging-1206] Contracts: can't cut stump

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13496]
If you have contract for debris clearing, you can cut debris but you can't clear stump
![unknown (18)](https://user-images.githubusercontent.com/27898520/67860030-c4371880-fb3e-11e9-8e4a-5a0d973dac6c.png)

**Comment by olegshegai** [comment]
Unclaiming now triggers recalculation of contracts related to the deed:
https://drive.google.com/open?id=1WPkP54hGlKM55jakad_T8tH4SToVvKMO

Will be added after (or maybe with) this PR:
https://github.com/StrangeLoopGames/Eco/pull/5145
