### ISSUE TITLE
0.9 balance, too many tailings

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13495]
if bloomery
(1 world block of iron ore=)4 iron ore->2 Crushed Ore+2 Crushed Stone->10 Ore Concentrate+10 tailings->50 Iron Bar+50 Slag=Total 65 world blocks.

if blast
(1 world block of iron ore=)4 iron ore->2 Crushed Ore+2 Crushed Stone->10 Ore Concentrate+10 tailings->50 Iron Bar+100 Tailings=Total 113 world blocks.

World of Tailings.

As i think it's totally kill advanced smelting and metall smelting in blast.

p.s.
Slayks, it's still a gameplay issue, not suggestion.

**Comment by beastyn** [comment]
balance is in progress. Need to check after basic fixing. Thank you for attention
