### ISSUE TITLE
Missing XP against recipe

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13499]
Version: 0.8.3.0 beta

Steps to Reproduce:
Crafting "Saw Boards" at the Sawmill

Expected behavior:
Should give XP against "Hewing" speciality (as per Carpentry Table)

Actual behavior:
Doesnt give XP against "Hewing" specialty

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by elfl0rd** [comment]
It's different reciepes.
You can see it in reciepes hints.
Carpentry reciepe at carpentry table, and receipe from lumber speciality at sawmill

You cannot get carpentry experience by making lumber reciepe.

**Comment by CarlB258** [comment]
In almost all other cases the recipe title and the item title are the same. The recipe title normally refers to the item being crafted. A degree of consistency would improve the game-play.
