### ISSUE TITLE
0.9 metal visual balance.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13493]
Just look.
4 metal block.
![unknown](https://user-images.githubusercontent.com/4980243/67858109-6f3cd780-fb29-11e9-8d24-5eddb837d35a.png)
Just... one... cubic meter...

But with max smelting skill we got 30 rivet from it.
![изображение](https://user-images.githubusercontent.com/4980243/67858167-9f847600-fb29-11e9-95a5-cf3854e23510.png)

In real life...
500 rivets...
![700](https://user-images.githubusercontent.com/4980243/67858280-e70b0200-fb29-11e9-9a07-f3727b52dc56.jpg)
 16sm × 12sm × 5sm

Also weight is really more funny.
From 4x2.5kg we got 30x2kg.
Magic!

**Comment by SlayksWood** [comment]
weight balanсe it's dup #13278. 
You can leave all your wishes regarding crafting improvements and what should be crafted in Craft Table in Suggestions.

**Comment by elfl0rd** [comment]
Lack of visual balance is one of the most frequently mentioned problems in Eco. It is not a suggestion, it is an issue.
Besides, this error is exacerbated in the version that has not yet been released.

@johnkslg @D3nnis3n
