### ISSUE TITLE
Incorrect Title

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13498]
Version: 0.8.3.0 beta

Steps to Reproduce:
Open crafting screen at Sawmill

Expected behavior:
Recipe to create boards should be called "Board" (as at the Carpentry Table)

Actual behavior:
Recipe to create boards is called "Saw Boards"

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by elfl0rd** [comment]
It's different reciepes.
You can see it in reciepes hints.
Carpentry reciepe at carpentry table, and receipe from lumber speciality at sawmill

**Comment by elfl0rd** [comment]
All other cases have one reciepe per item.
