### ISSUE TITLE
Random Blocks Appearing

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13502]
Version: 0.8.3.0 beta

Steps to Reproduce:
Start game

Expected behavior:
Everything should be where it was left

Actual behavior:
Each time the game is started there appears random blocks throughout the world that don't follow the laws of physics i.e blocks of Sandstone hanging in the middle of the air

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
will be updated in 0.9+
