### ISSUE TITLE
Wrong Title For Recipe

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13500]
Version: 0.8.3.0 beta

Steps to Reproduce:
Crafting "Hew Logs" at the Carpentry Table

Expected behavior:
Should be called "Hewn Logs" (as per Workbench)

Actual behavior:
Is called "Hew Logs"

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by elfl0rd** [comment]
it's a different reciepes, lol.
You made bugreports, but ddnt read tooltips|hints in game.
Hewn Logs is basic reciepe.
Hew Logs is carpentry reciepe.

**Comment by CarlB258** [comment]
In almost all other cases the recipe title and the item title are the same. The recipe title normally refers to the item being crafted. A degree of consistency would improve the game-play.
