### ISSUE TITLE
Unrealistic Physics

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13509]
Version: 0.8.3.0 beta

Steps to Reproduce:
Place any pollution e.g. Tailings

Expected behavior:
Any pollution should have a half-life and it's effect should decay accordingly

Actual behavior:
Effect of pollution is permanent

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by elfl0rd** [comment]
effect of pollution is not permanent, but after pollution source removed, need REAL weeks, to full disappear.

**Comment by elfl0rd** [comment]
After a lot of years (50+).
In eco we play for ~5-10 years as 30d cycle.
