### ISSUE TITLE
Wrong Image

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13505]
Version: 0.8.3.0 beta

Steps to Reproduce:
Crafting "Wooden Elevator Call Post" at the Sawmill

Expected behavior:
Should be representative and consistent

Actual behavior:
Image used in crafting list, hover-over description and elsewhere are different and not representative

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by MilenkoTunjic** [comment]
Can you post a screen-grab?
It will help a lot.

**Comment by beastyn** [comment]
@MilenkoTunjic 
![bandicam 2020-06-09 17-38-26-076](https://user-images.githubusercontent.com/27898520/84148225-1ac2e880-aa78-11ea-8c37-39c03924c635.jpg)

**Comment by MilenkoTunjic** [comment]
thankyou!

**Comment by RobertMangano** [comment]
Icon has been changed to new one

**Comment by beastyn** [comment]
Don't see any changes

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/4b7f0dc0-d224-498c-9d83-df9723623170) It should appear as the second last icon on that page, I did change an elevator post icon, so maybe I changed the wrong one?

**Comment by RobertMangano** [comment]
icon updated again, it must have been reverted at some point.

**Comment by SlayksWood** [comment]
We still have old icon:
![image](https://user-images.githubusercontent.com/45708377/87424223-47709f80-c5e4-11ea-934f-0028387e996f.png)

**Comment by RobertMangano** [comment]
my changes must be reverted or overwritten ![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/41c72967-44eb-47a1-8fa5-d98dbb6aa884)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/7b06d1af-0d16-4986-bb41-f3e7efb192cc)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/87659254-f8eb0e80-c765-11ea-8f17-13de9d6ab94e.png)
fixed.

**Comment by SlayksWood** [comment]
Hm, icon was returned to old. @RobertMangano Can you change it again?
![image](https://user-images.githubusercontent.com/45708377/90475150-95bb1600-e12f-11ea-8f6d-6ed8f84c9883.png)

**Comment by SlayksWood** [comment]
I thimk that you could merge it in develop build, but I have old icon in develop build too:
![image](https://user-images.githubusercontent.com/45708377/90475792-debf9a00-e130-11ea-88f6-9a43ab04d490.png)
