### ISSUE TITLE
Poor Physics

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13508]
Version: 0.8.3.0 beta

Steps to Reproduce:
Walk behind any hanging item e.g. small hanging sign

Expected behavior:
Should not allow behind hanging objects

Actual behavior:
Allowed to walk behind hanging objects only to get stuck

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
Can you show screens or something? Can't reproduce stucking situation.

**Comment by CarlB258** [comment]
![2019-10-31](https://user-images.githubusercontent.com/57011151/67933228-4bc36c80-fbbd-11e9-8cd5-ee87a0ecf7c1.png)

**Comment by CarlB258** [comment]
Player doesn't get permanently stuck, just cant walk through or past and have to turn around to come out (sorry if i misled)

**Comment by SlayksWood** [comment]
It's intended behavior for now. You should change glass to another cube block if you don't want this space.
