### ISSUE TITLE
Inconsistent Function

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13507]
Version: 0.8.3.0 beta

Steps to Reproduce:
Placing Stone Road block

Expected behavior:
Should be able to be placed with "E" as well as Hammer

Actual behavior:
Can only be placed with the Hammer

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by redwyre** [comment]
@beastyn is this still relevant? Don't you need hammer to place road now?
