### ISSUE TITLE
Incorrect physics

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13501]
Version: 0.8.3.0 beta

Steps to Reproduce:
Remove block directly underneath Dirt

Expected behavior:
Should follow laws of physics and fall to next solid block

Actual behavior:
doesn't fall

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
Known issue. Intended for now
