### ISSUE TITLE
Poor Title

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13515]
Version: 0.8.3.0 beta

Steps to Reproduce:
Open crafting screen at Electronics Assembly

Expected behavior:
Item should be called "Solar Panel"

Actual behavior:
Item is called "Solar Generator" on crafting screen and "SolarPanels" on hover-over description

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
Solar Generator - recipe

SolarPanel - item which you will make with this recipe. Tooltip shows you an item.

**Comment by CarlB258** [comment]
In almost all other cases the recipe title and the item title are the same. the recipe title normally refers to the item being crafted.
