### ISSUE TITLE
Poor Rounding

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13514]
Version: 0.8.3.0 beta

Steps to Reproduce:
All crafting screens

Expected behavior:
The amount of ingredients required should turn red when you don't have enough

Actual behavior:
The amount of ingredients required stays white even if you don't have the ingredients (probably a rounding issue)

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
Ui will be rewarked in 0.9. Will check this one too. Rounding is known issue #12540
