### ISSUE TITLE
Unrealistic Physics

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13510]
Version: 0.8.3.0 beta

Steps to Reproduce:
Place any pollution e.g. Tailings

Expected behavior:
The effect of pollution should be able to be contained

Actual behavior:
Effect of pollution cannot be contained

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by elfl0rd** [comment]
No, tailings can be contained safety.
You need 40 or more solid blocks above tailings to safe store it.

**Comment by beastyn** [comment]
@elfl0rd Thank you
Yeap. balance part for pollution will be updated in time

**Comment by elfl0rd** [comment]
player crafted blocks - yes, idk about dirt.
