### ISSUE TITLE
Crane Storage

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13516]
Version: 0.8.3.0 beta

Steps to Reproduce:
Open Storage screen at the Crane

Expected behavior:
Should see nearby storage

Actual behavior:
No storage available

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
crane doesn't have or need storage. Have plans for updating this one.

**Comment by CarlB258** [comment]
then there should be no "Storage" page/button.
