### ISSUE TITLE
Incorrect Recipe

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13513]
Version: 0.8.3.0 beta

Steps to Reproduce:
Craft Gear at the Electric Machinist Table

Expected behavior:
Ingredient should be Iron

Actual behavior:
Ingredient is Steel to create an Iron Gear?

Do you have mods installed? Does issue happen when no mods are installed?:
No mods installed

**Comment by beastyn** [comment]
Will be reworked in 0.9
