### ISSUE TITLE
[0.9.0 staging-1215] Uncomfortable to drop markers

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13526]
1. Non-fixed tabs in Minimap(Regression). It's uncomfortable to drop markers now. See video:
https://drive.google.com/file/d/1AyEHcWke23bCBFAa3QCk5VOezYYJZPeY/view?usp=sharing
How it was in 8.3.0: https://drive.google.com/file/d/1IcR2BgvfnuOfeskBg1JLwjhG-Pa2sY2V/view?usp=sharing
2. Most Suggestion: Can you add some kind of shadow where the marker will drop? Because I drop all markers approximately.

**Comment by elfl0rd** [comment]
also one big regression.
You cannot drop markers to mark 3d position. (only to surface).
It's annoying if you want something inside mine or large house.

https://github.com/StrangeLoopGames/EcoIssues/issues/8512

**Comment by SlayksWood** [comment]
It works, but it works bad. I will open new issue, because this issue fixed.
