### ISSUE TITLE
[0.9.0 staging-1215] Always use 2D Minimap after relog

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13525]
Step to reproduce:
- Enter game. Set 3d Minimap
- reload. Will set 3D Minimap but display 2D
![image](https://user-images.githubusercontent.com/45708377/67927003-8bdc1c80-fbc8-11e9-8601-8c7801e1e640.png)

**Comment by Sekor2600** [comment]
the Problem is that the 2D Version is in the UI too
![grafik](https://user-images.githubusercontent.com/37456949/68338490-de469d00-00e2-11ea-974b-84e5624d5eab.png)
There should always 3D
