### ISSUE TITLE
USER ISSUE: Wiki

### ISSUE THREAD

**Issue by CarlB258** [StrangeLoopGames/EcoIssues#13521]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
open most Wiki pages

**Expected behavior:**
The Wiki should be correct and up to date

**Actual behavior:**
Lots of incorrect and outdated information e.g. power use and output in Joules instead of Watts etc.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods installed

**Comment by elfl0rd** [comment]
Wiki maintained by volonteers and players, not slg.

**Comment by beastyn** [comment]
Thank you for your attention. We will think about more prosuctive way of wiki update. But FYI, we also will have in-game wiki with 0.9.
