### ISSUE TITLE
[0.9.0 staging-1215] Chat text still may be not in right position

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13529]
This happens due to large messages.
![image](https://user-images.githubusercontent.com/45708377/67932825-af599400-fbd5-11e9-82b3-ea0cab64401d.png)

**Comment by beastyn** [comment]
Still displaced
![bandicam 2019-11-28 15-05-26-665](https://user-images.githubusercontent.com/27898520/69796875-9b16b000-11f0-11ea-8b37-62e5ec800890.jpg)

**Comment by SlayksWood** [comment]
Lines were removed, but now it has become unreadable. Previously, it was possible to navigate with lines. But we have a strange line spacing in this chat after fixes.
![image](https://user-images.githubusercontent.com/45708377/70597250-f1c0b880-1bf8-11ea-8167-2ce28efd9c64.png)
![image](https://user-images.githubusercontent.com/45708377/70597817-60524600-1bfa-11ea-8c31-2631a0f8cdb0.png)

**Comment by SlayksWood** [comment]
merged to #14101
