### ISSUE TITLE
[0.9.0 stageing-1215] Change Top chat width with another UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13528]
Top UI should be remake. 
1. Need to limit the number of orders at top UI
![image](https://user-images.githubusercontent.com/45708377/67931739-8df7a880-fbd3-11e9-8e23-df476a96916a.png)
2. If you change Chat width, then it should be centered relative to the screen, and not move right to left when adding orders or a tutorial. Start moving chat only when the Order UI starts to overlap chat.
Step to reproduce: 
- Change Chat width to minimum (I asked in another issue, but almost all chat issues are already closed: Make minimum chat less)
![image](https://user-images.githubusercontent.com/45708377/67932359-d19ee200-fbd4-11e9-9656-23d97956cf3f.png)
- add 2 new order at workbench. Chat will change, why? Nothing overlap it.
![image](https://user-images.githubusercontent.com/45708377/67932389-e11e2b00-fbd4-11e9-96da-bdc79c900c5d.png)
It causes a strange effect with many orders. Orders began to move to the right side
![image](https://user-images.githubusercontent.com/45708377/67932572-34907900-fbd5-11e9-8b5e-bfd52f0cb97c.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/72782312-8248da80-3c34-11ea-848e-915f76b0fe64.png)
And I can't change width now.

**Comment by beastyn** [comment]
notification window is still crowling away even if there is no overlapping with orders
![bandicam 2020-01-29 17-17-48-836](https://user-images.githubusercontent.com/27898520/73356070-51634800-42bb-11ea-8f12-9250b85ca08c.jpg)
.
