### ISSUE TITLE
[0.9.0 staging-1215] Missing button "Show in world"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13538]
8.3.0:
![image](https://user-images.githubusercontent.com/45708377/67949383-af1ec000-fbf8-11e9-9123-8105cddba875.png)

**Comment by gzatravkin** [comment]
What for is this button? @SlayksWood

**Comment by SlayksWood** [comment]
It's highlighting world.
![image](https://user-images.githubusercontent.com/45708377/68180155-a71da200-ffa3-11e9-9f01-8f8dfd086e83.png)

**Comment by gzatravkin** [comment]
@SlayksWood not sure if I understand, before for show some layer of environment data you needed
1) select Layer
2) set toggle=true ShowWorld?

Looks like 2) is innecesary click if so. Or it had another propose?

**Comment by elfl0rd** [comment]
@gzatravkin no way to see heatmap at world, like in 0.8
This is current master, where is "show in world" button?
![изображение](https://user-images.githubusercontent.com/4980243/68544514-041abd00-03d5-11ea-92e8-8285d3bc043a.png)

**Comment by gzatravkin** [comment]
@elfl0rd heatmap of what? As I see in your screenshot, you have heatmap enabled (so this way you have yellow and orange colors instead of world texture). Isn't heatmap?

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13538#issuecomment-549665339
this.
Now show screenshot from 0.9 with heatmap enabled not only at minimap.

**Comment by SlayksWood** [comment]
You need to fixcate this button in Enviroment Data.
![image](https://user-images.githubusercontent.com/45708377/68748816-2b100380-060e-11ea-9649-072a2272c78b.png)
![image](https://user-images.githubusercontent.com/45708377/68748987-893ce680-060e-11ea-8b41-334cbcbeb120.png)
You can see this UI in 8.3.0. It works better than now.
