### ISSUE TITLE
[0.9.0 staging-1215] no sliver effect when cutting trees

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13539]
https://i.gyazo.com/438f6638d514f971dfffb80f2c70c509.gif

**Comment by redwyre** [comment]
Do you mean the effect of little wood chips when you hit it?

**Comment by beastyn** [comment]
yeap, that one. Not sure if this is for you )

**Comment by beastyn** [comment]
Thanks, Mike!
