### ISSUE TITLE
[0.9.0 staging-1215] Artic Willow start fly

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13533]
![image](https://user-images.githubusercontent.com/45708377/67942450-e4231680-fbe8-11e9-8c6a-dd53ae0b7f59.png)
It didn't fly at 0.8.3:
![bandicam_2019-10-31_16-07-23-094](https://user-images.githubusercontent.com/45708377/67942500-03ba3f00-fbe9-11e9-82bc-a7ae9fac1a27.jpg)

**Comment by beastyn** [comment]
Simon refrebced PR in this #13608
