### ISSUE TITLE
[0.9.0 staging-1215] Work order creates empty marker

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13531]
It was broken somehow.
When you place work otder you should see info about it with marker.
Something like that #12522

Now its empty

**Comment by beastyn** [comment]
Nope, still here
https://drive.google.com/file/d/14LMOqNAJqQVSAtA-pR254fgbuD04HJ7a/view?usp=sharing

**Comment by Hakuhonoo** [comment]
Ah, yes. I used to misunderstand the issue. Added marker text now in the PR
