### ISSUE TITLE
[0.9.0 staging-1225] No update for ecotechtree

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13544]
Somehow we can't get updates for the eco tech tree (in svn xls is a new one).  But after building the project csv doesn't get update.

**Comment by redwyre** [comment]
The CSV is exported manually from the excel file, it doesn't automatically update. Is that what you're referring to?

**Comment by craig-jong** [comment]
There were some merge issues with an old CSV. I'm not sure if that's what this is refering to or not.

As Simon said, the CSV is created using a macro on the XLSM and merged into staging so building the project won't update the CSV.
