### ISSUE TITLE
Icons response in auth

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13541]
We've updated the icon system on eco accounts. Now a user can select their preferred icon from their account page. Their selected icon should be passed in auth.

Auth needs to be updated to return 'selected_icon' from the accounts database. And also 'reward' but i think that is working correctly already.
It currently returns 'icon', but that is not needed - remove it.

It should return 'selected_icon' and 'reward' in these cases:
1 slg user logs in via /responsev4
2 slg user logs in with login token via /verifytokenv3
3 steam user that has linked slg account logs in via /verifytokenv3

If a steam user logs in and does not have linked slg account, they will receive default icon.
Game side will assume default icon if 'selected_icon' is null or empty.

**Comment by rainfarmer** [comment]
this has not been updated

**Comment by rainfarmer** [comment]
we have staging auth now to test this https://github.com/StrangeLoopGames/AuthServer/pull/18
message you the url

**Comment by redwyre** [comment]
Icons are in game
![image](https://user-images.githubusercontent.com/431728/83792698-c0740180-a6de-11ea-82fa-e9319f25f1d1.png)

however it seems the auth server hasn't been updated

**Comment by beastyn** [comment]
Yeap, only default icons now.

@rainfarmer what about auth server update?

**Comment by redwyre** [comment]
I've checked in a fix for the offsets into SVN

**Comment by redwyre** [comment]
Fixed in staging auth server

**Comment by rainfarmer** [comment]
going to update account db so all users have their icons.
