### ISSUE TITLE
[0.9.0 staging-1225] Can't harvest Tortoise

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13543]
![image](https://user-images.githubusercontent.com/45708377/68008245-4fbfbf00-fc8f-11e9-816e-c58c80494dfc.png)

**Comment by StanKryvenko** [comment]
You haven't killed it

**Comment by StanKryvenko** [comment]
![image](https://user-images.githubusercontent.com/10034044/68030049-30ef1600-fceb-11e9-8352-63470a53237e.png)
Death one looks like this
@SlayksWood

**Comment by StanKryvenko** [comment]
Fixed
