### ISSUE TITLE
Sleep animation work uncorrect at 3rd person mode

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13547]
![3](https://user-images.githubusercontent.com/4980243/68070807-36e50580-fd84-11e9-93e1-a5d6c6173c1b.gif)

**Comment by SlayksWood** [comment]
dup #9996

**Comment by elfl0rd** [comment]
not dup.
As you can see, in 3rd person mode, animation moved avay and clip trough walls.
@SlayksWood

**Comment by elfl0rd** [comment]
@beastyn

**Comment by elfl0rd** [comment]
`¯\_(ツ)_/¯`
@D3nnis3n as you can see, it is different issue.
In "dupe" is a description of the remaining avatar, in this issue - incorrect camera position during animation playback.
