### ISSUE TITLE
0.8-0.9 transactions window resize issues.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13550]
Not have dunamic layout.
Not have "size" limits.
Columns overlap
Layout broken in some cases.

![изображение](https://user-images.githubusercontent.com/4980243/68076458-cf4faa00-fdc5-11e9-91bc-21977e164d01.png)
![изображение](https://user-images.githubusercontent.com/4980243/68076462-decef300-fdc5-11e9-924e-8b6083d6d1a2.png)

![20191102214101_1](https://user-images.githubusercontent.com/4980243/68076479-0756ed00-fdc6-11e9-91e3-18d82cafbcac.jpg)

**Comment by SlayksWood** [comment]
Window doesn't save user settings. Step to reproduce:
- open transaction window:
![image](https://user-images.githubusercontent.com/45708377/72783391-58dd7e00-3c37-11ea-828e-1985322aadd5.png)
- change size and move it:
![image](https://user-images.githubusercontent.com/45708377/72783441-7dd1f100-3c37-11ea-8217-f0e8e76a786b.png)
- close and open again:
![image](https://user-images.githubusercontent.com/45708377/72783447-83c7d200-3c37-11ea-9e26-9db2d2e38a8a.png)
- I should have my window size in my position.

**Comment by SlayksWood** [comment]
Add limit by width to have possibility see all tabs:
![image](https://user-images.githubusercontent.com/45708377/72783538-be316f00-3c37-11ea-9762-3d227f5c86f4.png)

**Comment by SlayksWood** [comment]
fixed for 0.9.0, another problems should be fixed with #14861
