### ISSUE TITLE
Usability\suggestion - reciepe name should have hint too.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13553]
You know, some reciepes have ingredients like 1,25.
In this case, in requirements, we see 2.
So... we want to see reciepe hint.
But... Instead of hover over reciepe name
![изображение](https://user-images.githubusercontent.com/4980243/68076720-9a455680-fdc9-11e9-8758-cb45f04a4c94.png)

we need to do this...
![изображение](https://user-images.githubusercontent.com/4980243/68076732-bd700600-fdc9-11e9-9120-96bece6942ad.png)

Usability...
Ecopedia a little help, but not ideal.
@D3nnis3n i want your opinion :P

**Comment by SlayksWood** [comment]
merged to #13334
