### ISSUE TITLE
0.8.3 ap gen not hidden.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13551]
![20191101185130_1](https://user-images.githubusercontent.com/4980243/68076497-3705f500-fdc6-11e9-927c-7645c9b943d3.jpg)

**Comment by beastyn** [comment]
Nope. still here. Maybe it should go for Item, not object?
![bandicam 2019-11-07 13-23-46-479](https://user-images.githubusercontent.com/27898520/68372164-2062f380-0162-11ea-9682-885acbfbad22.jpg)

**Comment by redwyre** [comment]
@craig-jong can you add APGen to the "Hidden" list in WorldObjectLists?
