### ISSUE TITLE
[9 Staging]Not accepting Tree Logs in Campfire Power Tab

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#13555]
**Version:** 0.9.0.0 beta staging-5047bdc7

**Steps to Reproduce:**
Campfire will not accept Palm Log or Cedar Log in Power tab, but does want **Log**

**Expected behavior:**
should let me use for power

**Actual behavior:**
will not let me place as a power source

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Comment by SlayksWood** [comment]
dup #13258
