### ISSUE TITLE
QoL: Moving store goods by drag, not buttons

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13558]
This is just quality of life request.
Rearranging store goods by clicking at up\down buttons is annoying...
Please add "draggable" region, where store owner can grab row and drag onto new position.

![e752272a004b062313848ed82a2d8796](https://user-images.githubusercontent.com/4980243/67595005-49e94b80-f76e-11e9-9894-34d8564ef7d0.gif)

**Comment by D3nnis3n** [comment]
Agreed.

**Comment by elfl0rd** [comment]
ofc

**Comment by ReadyPlayerEmma** [comment]
I would also really like to see this. It's also a pain if you want to move the store and keep the buy/sell list. It would be nice if that would persist in the block form so when you put it back nothing changed.

**Comment by SlayksWood** [comment]
add i to #20331

**Comment by WeaselDog** [comment]
Reopen this as a separate issue

**Comment by WeaselDog** [comment]
Coming in 9.5
