### ISSUE TITLE
USER ISSUE: Cannot load/create local worlds

### ISSUE THREAD

**Issue by TheSuperGamer20578** [StrangeLoopGames/EcoIssues#13556]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. load or create a local world

**Expected behavior:**
it should have loaded the world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by redwyre** [comment]
Can you follow the instructions at https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world and add the log files?

**Comment by TheSuperGamer20578** [comment]
[log_191127043054.log](https://github.com/StrangeLoopGames/EcoIssues/files/3895287/log_191127043054.log)

**Comment by TheSuperGamer20578** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3895295/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3895296/Player-prev.log)

**Comment by D3nnis3n** [comment]
You can fix this by saving your storage and configs folder, uninstall Eco, then remove the whole Eco folder in steamapps/common/, reinstall the game and move your storage and configs folder over again.
