### ISSUE TITLE
USER ISSUE: Ramps to surface makes the wheel barrow stuck

### ISSUE THREAD

**Issue by atomroflman** [StrangeLoopGames/EcoIssues#13567]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Build a ramp, build a wheel barrow, run up the ramp, get stuck

**Expected behavior:**
Build a ramp, build a wheel barrow, run up the ramp, get over the ramp

**Actual behavior:**
U are stuck at the corner

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by SlayksWood** [comment]
merged to #9668
