### ISSUE TITLE
[0.9.0 staging-1233] Joshua log has Palm shadowplacement and groundplacement

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13568]
![image](https://user-images.githubusercontent.com/45708377/68180795-1c8a7200-ffa6-11e9-9b8e-9f5648b110b6.png)
![image](https://user-images.githubusercontent.com/45708377/68180874-696e4880-ffa6-11e9-99ea-1dd57fe79888.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/70099979-422a8b80-15e5-11ea-9435-699f7e147129.png)
fixed in staging
