### ISSUE TITLE
Master: Hewn logs and peat roof

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13562]
Softwood and hardwood hewn logs have peatroof form.
But not have model for it, etc.
![изображение](https://user-images.githubusercontent.com/4980243/68123116-2025e680-ff1d-11e9-9317-bedee6150f94.png)
![изображение](https://user-images.githubusercontent.com/4980243/68123163-43e92c80-ff1d-11e9-96e5-b20893a2a816.png)

Afaik, BASIC hewn logs have model...
But form is not added to selection :D
![изображение](https://user-images.githubusercontent.com/4980243/68122752-210a4880-ff1c-11e9-9402-ae2bf3fc3faf.png)
![fZkcwJ0wIIc](https://user-images.githubusercontent.com/4980243/68123056-fcfb3700-ff1c-11e9-9fb6-4fef664f05aa.jpg)
![qUcTULwAMfc](https://user-images.githubusercontent.com/4980243/68123058-fd93cd80-ff1c-11e9-9904-8b5f8ffc0729.jpg)

**Comment by SlayksWood** [comment]
dup #13391
