### ISSUE TITLE
Seperate law from owned land since that can cause issues for farming for an example

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1357]
The issue is that there might be a law to save the some plants. The issue is that this also applies to farms as an example. 

This is an issue that is coming over and over again that player tell me that they cant really make laws because it affects other thinks to much .. This should be mostly for plants as an example. or a way to exclude people from some specific laws

**Comment by rainfarmer** [comment]
Zoning should fix this.
Is that correct @SeanAtr0n ?
