### ISSUE TITLE
[0.9.0 staging-1234] Need an icon for the "new notifications" notification

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13576]
The idea is:

When you are opening the top notifications (for exploring) it won't scroll down if you've got some new notifications. Its ok, so people won't be disturbed by auto- scrolling.
But we need some way to tell them, that they can find the new notifications if they scroll down (maybe count them.)
![bandicam 2019-11-05 14-44-52-722](https://user-images.githubusercontent.com/27898520/68196791-e74c4700-ffda-11e9-8f46-dd1e667e050b.jpg)
).

**Comment by gzatravkin** [comment]
It have a scrollbar on right side. If there are new notifications it will have empty space on bottom. Is not enough?

**Comment by beastyn** [comment]
Its really not obvious, I prefer some additional little indication. I will ask for advice from Milenko.

**Comment by MilenkoTunjic** [comment]
how about little bubble with number of new notifications and arrow pointing down?
