### ISSUE TITLE
[0.9.0 staging-1234] Highlight doesn't turn during construction

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13575]
![image](https://user-images.githubusercontent.com/45708377/68193642-6da95e80-ffc4-11e9-9db0-6721ebfbc8fe.png)
![2019 05 11 Highlight doesn't turn during construction](https://user-images.githubusercontent.com/45708377/68193871-00e29400-ffc5-11e9-8df2-4770fb58a711.gif)

**Comment by redwyre** [comment]
If you look at another block then back again does it fix it?

**Comment by SlayksWood** [comment]
yes, it will fix, but in 8.3.0 it turned  at once

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/74005885-34013e80-498b-11ea-87b4-39ff108b0d21.png)
![image](https://user-images.githubusercontent.com/45708377/74005909-3d8aa680-498b-11ea-82fc-5ef2c5581cd9.png)
![image](https://user-images.githubusercontent.com/45708377/74005913-411e2d80-498b-11ea-8295-c2b4d496a26d.png)

**Comment by SlayksWood** [comment]
Still an issue when aim cursor doesn't move and still aiming this block after placing:
![image](https://user-images.githubusercontent.com/45708377/94527906-5e687a80-0240-11eb-86c8-cac9ba94e9fa.png)

**Comment by IcedForge** [comment]
https://i.gyazo.com/0453ef7187a2cf61f93b2d8a2c168fd8.mp4
Yeah, my bad i wasnt noticing it was happening after testing it a bit; it detects a block initially then checks if there is space in the left cell, then right cell and if there is no space it goes back to original spot and clips. It should detect a block in place after placing the left / right block and state, cant place here. ( this is all without moving the mouse )
