### ISSUE TITLE
[0.9.0 staging-1234] Can't cancel work order with cross

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13574]
This one doesn't work
![bandicam 2019-11-05 13-34-16-055](https://user-images.githubusercontent.com/27898520/68191656-d21eea80-ffd1-11e9-8652-12e4d66da45e.jpg)

**Comment by Hakuhonoo** [comment]
@beastyn 
Currently it remove the task from watch list as it does on top right corner of the screen.
Is expected behavior to remove it from current context instead?
Like:
- if clicked on top-right of the screen - remove from watch list
- if clicked in crafting window - cancel the task
