### ISSUE TITLE
[0.9.0] Items disappear after reload game

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13570]
Items began to disappear more often recently. We happen to almost reproduce this problem. Step to reproduce, as example, it doesn't work 100% but it works often:
- place some objects (workbench, camfire, campsite as markers)
- place excavator
- First disconnect from server
- Second - quit game
- start game
- press continue
- excavator should dissapear with high chance
![image](https://user-images.githubusercontent.com/45708377/68186362-0637e280-ffb5-11e9-82f7-4528a5b4a5b7.png)

**Comment by mirasrael** [comment]
Tried 10 cycles without success.

**Comment by WeaselDog** [comment]
I am able to reproduce this with almost 100% consistency. I do not have to quit the client, but just disconnect and relog. Here is how I am able to do it:

- Place 5 contract boards
- Disconnect and reconnect
- ~50% of the contract boards have disappeared. Each time you relog it changes which ones appear and disappear

**Comment by beastyn** [comment]
@WeaselDog  didn'r work for me. Did you check with the latest version?

**Comment by SlayksWood** [comment]
Seems fixed. I think item may disappear sometimes as in 8.3.0. But it isn't connected with reload game.

**Comment by WeaselDog** [comment]
It doesn't seem fixed to me. This just happened to me today with a carpentry table:
![missingtable](https://user-images.githubusercontent.com/47330823/68892136-23686180-06d7-11ea-9b14-9fe953923a47.png)

It seems to happen more if you switch accounts.
