### ISSUE TITLE
[0.9.0 staging-1234] Can place block in world objects

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13572]
![image](https://user-images.githubusercontent.com/45708377/68189734-1358cf80-ffbd-11e9-806a-248ee47cdcc6.png)

**Comment by SlayksWood** [comment]
It has the right size.

**Comment by redwyre** [comment]
> It has the right size.

Do you mean the table has correct occupancy?

This is also the same underlying issue as https://github.com/StrangeLoopGames/Eco/issues/5049 but I'll close that one as it's in Eco not EcoIssues

**Comment by redwyre** [comment]
What happened in 0.8.3?

**Comment by SlayksWood** [comment]
Can't place a block there
![image](https://user-images.githubusercontent.com/45708377/68235084-a15fa500-0013-11ea-9cc4-978cccaa6384.png)

**Comment by redwyre** [comment]
Ok, I've made a fix that does that, but it would be better if it didn't let you in the first place...
