### ISSUE TITLE
USER ISSUE: Rocker box not working

### ISSUE THREAD

**Issue by FWerewolf** [StrangeLoopGames/EcoIssues#13582]
**Version:** 0.9.0.0 beta staging-5047bdc7

**Steps to Reproduce:**
I crushed ore in an arrastra and got crushedore. I added a job in the rocker box, but it needs crushed ore (notice the missing space in crushedore)	

**Expected behavior:**
rocker box should except crushedore or arrastra should create crushed ore

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Comment by SlayksWood** [comment]
Arrastra should give Crushed Copper/Iron/Gold Ore

**Comment by Hakuhonoo** [comment]
Depends on this https://github.com/StrangeLoopGames/EcoIssues/issues/13360

**Comment by SlayksWood** [comment]
Checked on 0.9.0 staging-1254 . Wasn't able to reproduce. Seems fixed.
