### ISSUE TITLE
Hosted Worlds not taking config edits

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13586]
v8.3.0 and v8.2 are not letting user edit configs. Returns error 'something is wrong'
Tested on website UI and Postman.

It does work for v9.0 staging and v8.3.1
Both of these use a different default world that adds strange admin users, so we thought that was issue. 
But after creating v8.3 with empty default world (0.8.3.0-beta-preview). It has same config editing error.

Need v8.3.0 with configs editable. 
Blocking classroom usage so critical priority.

**Comment by rainfarmer** [comment]
related issue: https://github.com/StrangeLoopGames/EcoIssues/issues/13587

**Comment by mirasrael** [comment]
I tested with idle-1573002211 world with PauseConfig (which I guess was started from 0.8.3.0-beta-preview) and everything is working. It seems 8.3.0 contains broken DefaultWorld.

**Comment by mirasrael** [comment]
I updated Docker image with fixed DefaultWorld. So for new 8.3.0 worlds it should be fine.
