### ISSUE TITLE
[0.9.0 staging-1234] Flat Roof block of Composite Lumber isn't full colliding

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13589]
![image](https://user-images.githubusercontent.com/45708377/68278858-449bd300-0083-11ea-9bf3-f8d695432f39.png)
![image](https://user-images.githubusercontent.com/45708377/68278870-49608700-0083-11ea-9cae-bdc60b9a211c.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/70099495-cd0a8680-15e3-11ea-9e6d-0a4d42f9d05b.png)
Fixed in staging
