### ISSUE TITLE
cant set orders

### ISSUE THREAD

**Issue by Undea1** [StrangeLoopGames/EcoIssues#13585]
cant set an order.
i did try to order something a few times in my workbench,farmingtable and ervery other table.
but i cant set an order. in my claim or outside.
everyone else on the server can...
on other servers i can set an order...
the server was restartet and it still dont work...
i did reinstall eco too.
i did set everything to default nothing.
ah and its the only thing i cant do.
i can put the tables on the ground take them with me ... plant plants ... fill my stockpile how are in range.

i was thinking about changing my player id, there maybe there is something broken in my user file on the server. But i dont think the admin know how to edit something like this or even cant do it.

the version is the steam version, i think it was 0.8.3.0

please help

**Comment by SlayksWood** [comment]
1. Please provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Please provide your PC specification (include Operating System).
3. Please provide server ID.
4. Are there any laws on server which blocking start orders?
5. Can you describe in more detail at what point you can't start orders? The best way would be to record  video.

**Comment by Undea1** [comment]
1. [Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3822812/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3822814/Player-prev.log)

2. Omen by HP Desktop PC 880-p0xx
intel(R) Core(TM i7-7700K CPU @ 4.20 GHz 
RAM 32,0 GB
Sytem 64bit
Win 10
Geforce 1070 TI

3. Server i know only the name [DE] ECO-GAMING.DE - WELT # 5 I HOSTED BY WE-LOVE-GAMING.EU 

player ID 16

4. When it did start there was no law.

5. I go on lets say campfire and want to make charred corn, then move with my mouse over order and do a left click. it clicks, but nothing happens.

**Comment by Undea1** [comment]
ok we just did try to reset me.
i did come to the world as a new player and it still didnt work . :(

i also did notice that i cant buy things.
when i want to buy something i cant choose a bank acc.
there is just an emty box, how drops down.
and again it works on other servers.

![20191109221458_1](https://user-images.githubusercontent.com/57422729/68535380-04b64380-0342-11ea-9837-6bdc60e174ca.jpg)

**Comment by beastyn** [comment]
Thank you for information, we are in further investigation process.

**Comment by mirasrael** [comment]
If you can provide server save (you can ask server admin) and your nickname then we can try to reproduce the issue in dev environment.

**Comment by beastyn** [comment]
Closing for no response, reopen when you can provide us with necessary information

**Comment by Undea1** [comment]
ok yeah i cant provide the server admin did not come online anymore. :/
and i dont have the problem on other servers so its good.  🙂

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
