### ISSUE TITLE
Default hosted world creates many strange admin users for world.

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13587]
The default world save for v8.3.0 is supposed to add certain devs as admins to all worlds.
But it is adding long list of users that are not devs.

Should just add slg154238

**Comment by mirasrael** [comment]
It is just has broken DefaultWorld. I updated Docker image with fixed DefaultWorld version.

**Comment by mirasrael** [comment]
I updated Docker image with fixed DefaultWorld.

**Comment by rainfarmer** [comment]
@mirasrael could you update this. and remove slg24954 
and replace with 154238

**Comment by mirasrael** [comment]
Added slg154238 to default admins lists for HW in 9.0.
