### ISSUE TITLE
[0.9.0 staging-1234] Voice doesn't work sometimes

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13588]
from John
- Had to disconnect and reconnect to get voice to work. This happened a couple times
@johnkslg Simon has asked the log from you

**Comment by D3nnis3n** [comment]
Have the same issue every now and then. No idea how to reproduce.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/14753 same issue?

**Comment by redwyre** [comment]
Logs or it didn't happen 😉

**Comment by elfl0rd** [comment]
ofc, but maybe same root problem

**Comment by SlayksWood** [comment]
> So far I have received several messages that this is happening, (licensed game), voice chat "just stops working".
> I will supplement the ticket with log files when I "catch" a player with a fresh bug.
> latest, report from admins of different servers.
> after game relaunch chat work again.

**Comment by redwyre** [comment]
Is this breaking for just a single player? Everyone else is fine?
