### ISSUE TITLE
Disabling hyperthreading dramaticaly increase performance

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13594]
Disabling hyperthreading on a customer's machine VERY greatly improves performance in the case of most weak and all medium and strong machines.

Like something I can't stop laughing at...

> CPU: i9 9900k
> MB: GIGABYTE Z390 AORUS ULTRA, LGA 1151v2
> RAM: DIMM DDR4, 32GB (4x8GB), Corsair Vengeance LPX black
> Video: Gigabyte AOURUS GTX 1080ti 11gb
> Storage:
> SSD 512GB Intel 760 m2
> 2x1tb WD Raptor in RAID-0

37 fps with hyperthreading 108 without...

At the moment, I have feedback from 23 people who have taken this advice.
It didn't help to only one... The person playing on the graphics integrated into the processor.
5 players reported "small performance improvement".
The other 17 players noticed a "significant increase in performance".

Besides, our community found another trick.
If you single core to an eco (not 0 or 1) by prohibiting the use of the rest, you will notice a performance gain even with hyperthreading in most situations. Not as big as when disabling, but up to 50%

I think you really should pay some attention to this moment. @mirasrael

**Comment by D3nnis3n** [comment]
I only knew this trick for ryzen of the first two generations with more than 8 cores. But it actually boosts performance massively on third generation with 8 cores, too. Very interesting. Unfortunately Performance in most other games goes down.

**Comment by redwyre** [comment]
The only reason I can think of is windows is shifting the game process a lot which is causing lots of context switches. If you can change the affinity (I assume that's what you're talking about), to at least two even numbered cores (skipping 0), I'd be interested to see what the performance is like.

Also make sure you have turbo boost set up and enabled, it could make a big difference.

**Comment by douglasg14b** [comment]
I wonder if this explains my ~20FPS on a new world with a Ryzen 7 2700x with an RTX 580...

**Comment by mirasrael** [comment]
Need more tests after 9.0 release. Postponing this for now.

**Comment by WeaselDog** [comment]
@mirasrael Please let me know what you think know that we are post 9.0.

**Comment by mirasrael** [comment]
Tested on 9.3. No noticeable difference in FPS when I use two non-HT cores. When using single core it drops in FPS by ~20%. So seems this issue not actual for latest Eco version (probably something fixed in Unity).

**Comment by Daniel-Magulado** [comment]
Tested in 0.9.3 Develop-175

System:
i7-6700k
32GB DDR4
Vega 64
Nvme SSD

- FPS drastically drops to 40 to 50 fps at 1440p when the game is set to single core, leaving 1 core checked and unchecking the rest) (Core 1) from the usual 70 frames per second at max settings.
- There was no difference in FPS when Hyperthreading is enabled or disabled.
- The game uses more processor resources when HT is disabled. From 19 to 23% usage at idle when HT enabled to 30 to 39% usage at HT disabled with no in-game fps improvement.

**Comment by IcedForge** [comment]
Tested in 0.9.4.0 (0.9.3.0 staging )Develop-180

AMD FX-8350 (8cpus~4.0GHZ)
16gb DDR3
SSD
(while generating terrain and moving)
Using 1 core
View distance 200 (13fps)
View distance 100 (30fps)

Using 2 cores
View distance 200 (24-28fps)
view distance 100 (44-57fps)

Using all available cores
View disance 200 (30-35fps some spikes down to 23 )
view distance 100 (45-64fps)

Using the following settings to test range and movement

![Screenshot_18.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/333992a6-e7e2-41ef-9ad6-048e4886b37f)
