### ISSUE TITLE
Computerlab work orders are broken 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1359]
http://ecoforum.strangeloopgames.com/topic/2137/computer-lab/2

**Comment by Fireboss4** [comment]
This is still an issue in 0.5.6.1

**Comment by Mogdu** [comment]
Still an issue in 0.6. staging

The problem comes from the PowerGridNetworkComponent. If removed, then the computer lab can do researches just fine, But then it can't fire the lasers.

**Comment by Mogdu** [comment]
I'm probably not learning anybody anything. But the PowerGridNetworkComponent and CraftingComponent both use the Enabled attribute of the ComputerLabObject. So they disable each other.

It looks like a nightmare to fix. Maybe simply put the two function in two different objects? It would be cool to be able to win the game without admin commands or other cheats.

**Comment by craig-jong** [comment]
Should move the recipes off of the computer lab entirely.

**Comment by craig-jong** [comment]
this was fixed earlier (6.0)
