### ISSUE TITLE
[0.9.0 staging-1234] Bank account selection in a bank glitch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13591]
in 8.3 it was like that (just click on the name for switching)
![f4e3229d59fc40918fac70f4589bbcf4](https://user-images.githubusercontent.com/27898520/68285545-45dbf880-00a1-11ea-8c60-7dd158840171.gif)

But now you will get history window with that.
![4947c54f87a08fa78619ba7b0c19ebeb](https://user-images.githubusercontent.com/27898520/68286283-ac154b00-00a2-11ea-9dde-8f4031a9ed36.gif)

It should just switch accounts,

**Comment by elfl0rd** [comment]
I think it's a good idea to be able to open the story from here.
After all, you can still click on the line itself, right?

However, a button or an additional area from where you can open the history is also a good option.

**Comment by beastyn** [comment]
@elfl0rd  It will have question mark for this
![bandicam 2019-11-15 11-07-33-463](https://user-images.githubusercontent.com/27898520/68920776-2f682800-0798-11ea-919f-5cf83e758a68.jpg)
