### ISSUE TITLE
USER ISSUE: Basic Engineering Scroll

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#13595]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Producing a Basic Engineering Scroll out of a Basic Engineering Book

**Expected behavior:**
With right clicking on the book the scroll should appear

**Actual behavior:**
While rightclicking the book, it doesn`t happen anything..

**Do you have mods installed? Does issue happen when no mods are installed?:**
I dont have any mods installed

**Comment by SlayksWood** [comment]
1. Please provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you provide video with opened inventory? or some more details with screenshoots

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information: log and if possible saved files.
