### ISSUE TITLE
0.9 Devtool lost power at another players property.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13596]
I think it's high, due to admins loose some power.

You cant control vechicles, you cant destroy or build something at another players property.
![изображение](https://user-images.githubusercontent.com/4980243/68292615-4ecacb00-009d-11ea-8a23-319095ef0289.png)
![изображение](https://user-images.githubusercontent.com/4980243/68292679-6b670300-009d-11ea-9802-e4585e38c907.png)

**Comment by WeaselDog** [comment]
We still get this error message in 8.3 when using Dev Tool on others' property, but it does allow us to access it.

**Comment by SlayksWood** [comment]
Still can't build at anothers territory, can't open craft table.
