### ISSUE TITLE
[0.9.0 staging-1234] Need some light improvements

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13593]
From Milenko.

basically, at night, it mostly feels unlit and brings daylight in contrast, it is like playing game on lower settings
so if a quick fix is possible, I would tint light to a colder hue drop overall brightness (compared to daytime) to 80 percent, and still have moonlight casting shadows

@redwyre I will leave it for 0.9 if quick fix is possible. If not we will push it for later.

**Comment by redwyre** [comment]
Looks like the Bloom, "Eye Adaption" and Tonemapper components have been disabled. Will look more into it later

**Comment by SlayksWood** [comment]
After the last changes it became very bright, I even had to reduce brightness a bit.

**Comment by SlayksWood** [comment]
The hardest time is when Sun has gone but Moon hasn't yet risen.

**Comment by beastyn** [comment]
Lets use this one for important light changes track.
So, after https://github.com/StrangeLoopGames/Eco/pull/5843 
with /time set 8
we have very sharp edges
![bandicam 2020-04-01 11-34-26-817](https://user-images.githubusercontent.com/27898520/78106446-d75f5480-740c-11ea-8d39-13fe58fd10eb.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/78106877-08d02400-73fd-11ea-8560-061fe2b31497.png)
Staging-1495:
/time set 6:
![image](https://user-images.githubusercontent.com/45708377/78106965-3cab4980-73fd-11ea-8d0d-2f68faa61c2a.png)
/time set 8:
![image](https://user-images.githubusercontent.com/45708377/78106922-21403e80-73fd-11ea-8a91-143d6623fea7.png)

**Comment by beastyn** [comment]
Definetly need to tweak contrast more
![bandicam 2020-04-01 14-44-38-151](https://user-images.githubusercontent.com/27898520/78133557-0dfe9480-7438-11ea-916d-d870db132af9.jpg)

**Comment by redwyre** [comment]
The problems where triangles show disjointed lighting is a separate issue, they need the mesh to be fixed (the same problem as the triangles that were showing on the sides.

**Comment by keegan-o** [comment]
I honestly don't get how you guys get such dark results.... here's /time set 6 for me, GI set to off:
![image](https://user-images.githubusercontent.com/14983165/78300603-99d1f880-74ec-11ea-93a0-feb348e93fe5.png)

**Comment by keegan-o** [comment]
time 18:
![image](https://user-images.githubusercontent.com/14983165/78300694-bf5f0200-74ec-11ea-8f7f-5b14efa9894f.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/78300718-cc7bf100-74ec-11ea-850c-9782d89fd63d.png)

**Comment by keegan-o** [comment]
time 12:
![image](https://user-images.githubusercontent.com/14983165/78300930-2e3c5b00-74ed-11ea-8525-5aee51b349c2.png)

**Comment by keegan-o** [comment]
Set settings to match yours exactly, 
![image](https://user-images.githubusercontent.com/14983165/78301536-0e596700-74ee-11ea-83a1-9fa57e0447b8.png)

time 12:
![image](https://user-images.githubusercontent.com/14983165/78301780-7314c180-74ee-11ea-805b-44e82a546787.png)
![image](https://user-images.githubusercontent.com/14983165/78301786-76a84880-74ee-11ea-9bb0-f660f342d7c7.png)

**Comment by keegan-o** [comment]
time 6:
![image](https://user-images.githubusercontent.com/14983165/78301985-d1da3b00-74ee-11ea-8475-f9379e30257f.png)

**Comment by keegan-o** [comment]
time 6
![image](https://user-images.githubusercontent.com/14983165/78302076-ff26e900-74ee-11ea-868b-6d3b2da54a76.png)

**Comment by keegan-o** [comment]
time 4:
![image](https://user-images.githubusercontent.com/14983165/78302272-50cf7380-74ef-11ea-8320-4b99e6d174e8.png)
with fog:
![image](https://user-images.githubusercontent.com/14983165/78302290-5af17200-74ef-11ea-83ca-52ba4a2a927f.png)

**Comment by keegan-o** [comment]
Anyways, to combat the pretty dark interior at 12 (any other time is brighter since light will come from the side more), toning down the relfection probe updater even more
![image](https://user-images.githubusercontent.com/14983165/78304616-fa186880-74f3-11ea-90bd-952a58a5bed6.png)

**Comment by keegan-o** [comment]
Gonna go ahead and make a PR that tones down the gamma adjustment I did with my last PR to hopefully help the washed out look Kirill posted in those first two shots. Of course, this will make it a bit darker. I will compensate a bit by just adding some more ambient at dusk and dawn. 
![image](https://user-images.githubusercontent.com/14983165/78307767-8a0de080-74fb-11ea-804e-2a6b7ccc6df6.png)

**Comment by keegan-o** [comment]
Realized the light color dipping at dusk/dawn was also contributing to darker dusk/dawns, jacked it up to be a bit brighter at night with light color and ambient as well. 
![image](https://user-images.githubusercontent.com/14983165/78308263-e7566180-74fc-11ea-9708-41727ffdd96c.png)

**Comment by keegan-o** [comment]
All this has been pretty radically changed now with my last updates to lighting. Darkness should more or less be a thing of the past. New issues with the new lighting can be opened with specifics, all this would just distract from it.
