### ISSUE TITLE
"All" button work not as intended.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13606]
As far as I can see, the logic of this button was broken.
It shouldn't just "substitute" a number, it should send "everything" of the selected (e.g. currency).
In my view, the number should be represented as "All" after it has been pressed.

Just look how it not work in some cases now.
If you have a number with a very large number of decimal places, you will not be able to do anything with it, even using this button.
![изображение](https://user-images.githubusercontent.com/4980243/68302248-ae7fa100-00b2-11ea-919b-1d376800d317.png)
looks as 0.9, but...
All -> 0,8999989
![изображение](https://user-images.githubusercontent.com/4980243/68302300-c48d6180-00b2-11ea-9bd4-41ed7d94dd6d.png)
and... Fail.
![изображение](https://user-images.githubusercontent.com/4980243/68302319-d1aa5080-00b2-11ea-93ee-f6448962abcd.png)

**Comment by beastyn** [comment]
About numbers - we have rounded issue here #8466
Or do you mean something else?

**Comment by elfl0rd** [comment]
Yes, because the original logic of this button is that it translates "everything" instead of trying to substitute a number.

**Comment by beastyn** [comment]
merged with #8466
Will add your comments there, thanks
