### ISSUE TITLE
[0.9.0 staging-1239] Backgorund stratching fixing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13603]
When you are resizing some UIs background for text block doesn't look good
![back1](https://user-images.githubusercontent.com/27898520/68298825-2ef6cf80-00bc-11ea-80ce-dface3de59ab.png)
![back2](https://user-images.githubusercontent.com/27898520/68298826-2f8f6600-00bc-11ea-8de4-c1d28f25e4d8.png)

**Comment by redwyre** [comment]
Also background is attached to the bottom and scrolls when you resize vertically
