### ISSUE TITLE
[0.9.0 staging-1239] Craft broken after last PR

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13601]
Can add resourses, can add labor, but craft doesn't start. This didn't happen immediately, after some time. It was broken for Research table immediately.
![unknown](https://user-images.githubusercontent.com/45708377/68298477-7e340480-00aa-11ea-995e-1a954433cb25.png)

In the end recipes broke in workbench:
![image](https://user-images.githubusercontent.com/45708377/68298201-d585a500-00a9-11ea-97b5-94806b185e30.png)
It's old bug, but we can't repro it.(Spam started in the log file)
```
NullReferenceException: Object reference not set to an instance of an object.
  at UI.RecipeUI.UpdateQuantities () [0x00000] in <00000000000000000000000000000000>:0 
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3814373/Player.log)

**Comment by mirasrael** [comment]
Problem seems only happen when server is running in Docker container. Will investigate this.
