### ISSUE TITLE
[9.0 staging ] The plants believe they can fly 

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13608]
Curved Shader Problem?

![grafik](https://user-images.githubusercontent.com/37456949/68338601-1f3eb180-00e3-11ea-9e6c-4b49f6a87945.png)
Agave

![grafik](https://user-images.githubusercontent.com/37456949/68338673-4eedb980-00e3-11ea-81c8-9c6a58e03012.png)
Arctic Willow

**Comment by redwyre** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/5201

**Comment by SlayksWood** [comment]
Got worse:
![image](https://user-images.githubusercontent.com/45708377/68454331-560ee780-0209-11ea-9725-21eee174cabd.png)
![image](https://user-images.githubusercontent.com/45708377/68454366-6cb53e80-0209-11ea-81ad-99381aa44dbc.png)

**Comment by beastyn** [comment]
and flying again (build 1248)
![bandicam 2019-11-13 16-41-22-308](https://user-images.githubusercontent.com/27898520/68760813-88b74680-0634-11ea-8dfc-3830ae25e666.jpg)
![bandicam 2019-11-13 16-40-07-421](https://user-images.githubusercontent.com/27898520/68760814-894fdd00-0634-11ea-913f-99e8dffc9806.jpg)

**Comment by keegan-o** [comment]
fixed again in staging
