### ISSUE TITLE
Undiscovered speciality should contain reciepe for discover.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13619]
There, as I think.
![изображение](https://user-images.githubusercontent.com/4980243/68392768-96278900-017b-11ea-95e9-93795852531b.png)

Or made this screen more like not studied.
![изображение](https://user-images.githubusercontent.com/4980243/68392854-c838eb00-017b-11ea-9ab8-f37fab789573.png)
like this...
instead of "A player can research it at a Research table to unlock it."
Use "A player can research "profession skillbook reciepe" at a Research Table to unlock it."

**Comment by madpingui** [comment]
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/7712a73d-0b29-4733-99dc-db9dace1d0a8)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-286.

Closing. Undiscovered specialties now have a clear indication of how to unlock and discover the skills.
