### ISSUE TITLE
[0.9.0 staging-1240] Transfer window UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13613]
![image](https://user-images.githubusercontent.com/45708377/68380332-ad0cb200-0160-11ea-8976-aa23b4595c29.png)

**Comment by beastyn** [comment]
Can we review this a little?
Tax and Result seems to be little displaced. Can we make them like Overall result, similar to 8.3?
Would be great if you discuss it with Milenko.
![bandicam 2019-11-18 15-36-28-916](https://user-images.githubusercontent.com/27898520/69045988-cee81d80-0a19-11ea-8e82-a93d720bd7c7.jpg)

**Comment by beastyn** [comment]
Also, for this one, there is no tooltips on bank accounts and currency

**Comment by beastyn** [comment]
Sorry but... First - Tax.. Then - Result )
![bandicam 2019-11-29 10-36-43-916](https://user-images.githubusercontent.com/27898520/69845940-3876f000-1294-11ea-962a-d0d16933f2b7.jpg)
