### ISSUE TITLE
Width number in build road clause out of window

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13622]
![изображение](https://user-images.githubusercontent.com/4980243/68433283-322ab200-01c7-11ea-9c05-fef47661be5d.png)
![изображение](https://user-images.githubusercontent.com/4980243/68433297-3b1b8380-01c7-11ea-9122-a8a3e9a467b0.png)

**Comment by elfl0rd** [comment]
same with "custom clause" content
![изображение](https://user-images.githubusercontent.com/4980243/68433347-56868e80-01c7-11ea-9175-b4b538dbd285.png)

**Comment by beastyn** [comment]
dup #12300
