### ISSUE TITLE
[0.9.0 staging-1241] Skip tutorial window is overlaping skipping tutorial.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13627]
Step to reproduce:
- try to skip Meteor tutorial:
![image](https://user-images.githubusercontent.com/45708377/68462675-0d155e00-021e-11ea-891e-30f73b67c7c9.png)
Need make some lower.
0.8.3.0:
![59178115-b7e9f900-8b66-11e9-8237-2965cf5cd466](https://user-images.githubusercontent.com/45708377/68462625-f242e980-021d-11ea-9a3f-5e4571b5f93d.png)

**Comment by beastyn** [comment]
Nope, you still can't get what are you skipping
It should be below the task.
![bandicam 2020-01-05 15-05-52-731](https://user-images.githubusercontent.com/27898520/71778236-fd6f8700-2fcc-11ea-8f8d-80b7bd433c96.jpg)

**Comment by beastyn** [comment]
![3ed23b06902949a27f08d99ce111f486](https://user-images.githubusercontent.com/27898520/71817254-13ea1100-30a7-11ea-82ad-ed0523cf5e96.gif)
