### ISSUE TITLE
Number out of window in payment on completion contract clayse

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13621]
look on payment and deposit numbers
![изображение](https://user-images.githubusercontent.com/4980243/68432317-4372bf00-01c5-11ea-9726-9ae8dace03e4.png)
![изображение](https://user-images.githubusercontent.com/4980243/68432348-52597180-01c5-11ea-829b-3da1bd3c5e12.png)

**Comment by beastyn** [comment]
the same issue #12300
