### ISSUE TITLE
Current Events tool display events outside of timerange

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1362]
I proposed and passed 3 laws at different times.
The current events query returns 3 active laws, even if they are outside the time range of the query.

After looking into the query   /discussions/suggest
I noticed that the Event Data, does not include the name or guid of the law its reporting on.
Not sure if that is on purpose or not.

**Comment by MarjieAVolk** [comment]
Are you checking this on swagger?  Because as I mentioned before, the behavior seems fine on swagger, but the web client implementation of the slider is not working correctly

**Comment by rainfarmer** [comment]
I did use swagger

**Comment by MarjieAVolk** [comment]
Okay well I'm seeing correct behavior in swagger; tried adding a law, waited ~40 min, added another law, looked at discussion suggestion output in swagger with various time ranges, and it looked correct.  I looked at the behavior on the website and it did not look correct.

As for not having the law guid, that is expected.  This is a very unofficial version of this discussion template & the current event, so the final one will probably be more clear (in the text) as to what law it was, etc, but the discussion isn't intended to support linking to elsewhere on the site or anything (that sounds like it would be a complex feature to support) so the guid will likely never be there.

**Comment by rainfarmer** [comment]
I see, I was using seconds on accident.
