### ISSUE TITLE
[0.9.0 staging-1241] Markers vibration

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13626]
It's better to reproduce in 3d view person
![2019 11 08 Markers vibration](https://user-images.githubusercontent.com/45708377/68462258-3bdf0480-021d-11ea-949f-fbf6514c0e5a.gif)

**Comment by SlayksWood** [comment]
It's overlapping now.
![image](https://user-images.githubusercontent.com/45708377/70598426-e458fd80-1bfb-11ea-99ec-4e984d5929e4.png)

**Comment by SlayksWood** [comment]
still overlaping
![image](https://user-images.githubusercontent.com/45708377/70882024-818eaa00-1fdf-11ea-9af8-465b8138d1e3.png)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 277

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c4164a6b-0fcc-4b27-862c-64501eac4fdd)
