### ISSUE TITLE
[0.9.0 staging-1240] Localization trouble in minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13623]
Step to reproduce:
- open minimap
![image](https://user-images.githubusercontent.com/45708377/68452630-290c0600-0204-11ea-96f7-8ff0c9eb319a.png)
- change language to Russian:
![image](https://user-images.githubusercontent.com/45708377/68452718-725c5580-0204-11ea-8f37-b57ed5abf3af.png)
- change language to English:
![image](https://user-images.githubusercontent.com/45708377/68453123-bef46080-0205-11ea-843a-57ca562382e0.png)

**Comment by beastyn** [comment]
@Quadbro or @serpopov can help with localization part
