### ISSUE TITLE
Viewing angle 120 with an extension of 3840x2160

### ISSUE THREAD

**Issue by Pro100Zigmun** [StrangeLoopGames/EcoIssues#13632]
A game with an extension of 3840x2160, set the viewing angle to 120, the view of the picture has changed as if you were looking through a lens.
![5enPjoocEnI](https://user-images.githubusercontent.com/57272807/68527919-2db8e300-0306-11ea-8785-411e6a87de07.jpg)
![EekuEjzSXu4](https://user-images.githubusercontent.com/57272807/68527920-2e517980-0306-11ea-9b6f-cd28dad63f73.jpg)
![ZmBD77S4a_A](https://user-images.githubusercontent.com/57272807/68527921-2e517980-0306-11ea-8349-81e6c89d243c.jpg)

**Comment by redwyre** [comment]
Unless you are sitting 30cm away from a 55" TV, a FOV of 120 isn't realistic. Try 90.

**Comment by Pro100Zigmun** [comment]
Set the viewing angle to 90. I am sitting at a distance of 50 cm, with 40 diagonals.

![1](https://user-images.githubusercontent.com/57272807/68534119-24516a00-034a-11ea-8f73-e2b01cefadba.jpg)
![2](https://user-images.githubusercontent.com/57272807/68534273-0553d780-034c-11ea-8495-8e6cc3aa23b4.jpg)
![3](https://user-images.githubusercontent.com/57272807/68534274-0553d780-034c-11ea-8c06-db6afd8d19f5.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-192

I can confirm that at 120FOV, the view becomes like fisheye or looking through a lens. I tested this on various display setups such as UHD 4K, 3840x2160, 1440p, and Ultrawide 1080 by 2560. A 120 Field of view doesn't feel right and look right. Furthermore, it triggers my motion sickness.

![120fov.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/227db4a3-4a17-45e6-9d9b-25a0200b34de)

**Comment by redwyre** [comment]
For 120 degrees you would need to have your eye a few cm from a 24" screen for it to make sense. Eco also has world curvature which large FOVs especially looking down are going to make more prominent. This doesn't seem like an actual issue to me, other than if we allow such a ludicrous FOV.

**Comment by Quadbro** [comment]
Probably we just need to cut max fow a bit? @WeaselDog

**Comment by TwixterZ** [comment]
FOV is currently limited to 100 in FPV and 75 in TPV in latest update. hence this bug no longer reproduceable.
