### ISSUE TITLE
Goats dance too much

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13631]
![anim](https://user-images.githubusercontent.com/3536496/68519478-292cf580-0246-11ea-9fa8-ec1a049eb130.gif)
He's been standing there rocking out continously
They shouldnt dance at all

**Comment by D3nnis3n** [comment]
Hyper, Hyper!

**Comment by redwyre** [comment]
> They shouldnt dance at all

![image](https://user-images.githubusercontent.com/431728/68525262-98c0e480-031b-11ea-8abc-53111bcb9c6c.png)
They can dance if they want to
