### ISSUE TITLE
Remove Contract Escrow as possible target for transfers

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13633]
Player accidentally transfered money there and can't get it out in any way, it cant be taxed, is owned by noone and therefore no backtransfer is possible. (Without admin commands)

**Resolution: Remove Contract Escrow from possible target destinations in the transfer money dialog.**

**Comment by beastyn** [comment]
Need to add Contract Escrow to source accounts

**Comment by D3nnis3n** [comment]
Noone owns that though.

**Comment by D3nnis3n** [comment]
People should not be able to Transfer from or to it, its an automatic account, so do not add it to source!
