### ISSUE TITLE
German Chat Issues 8.3.0

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13634]
If the server is on german, chat has massive issues:
When server is on german, you get multiple "General" chats
you can only type a sentence when you add a space in before the first word, if you don't, it won't appear.
And each space in your sentence will be replaced with a "*"

![bild](https://user-images.githubusercontent.com/25908592/68536350-b5780f00-0351-11ea-9da5-42aa9cba6236.png)

You also cannot vote for world leaders, as spaces are converted to "*" and that means the name is not the same, which makes you unable to vote.

**Comment by beastyn** [comment]
@mirasrael I should ask you to help with localization part here. Issue for Gti.

**Comment by D3nnis3n** [comment]
Oh, and whispering also doesnt work, as you can see i can see the red whispers.

**Comment by gzatravkin** [comment]
Can't reproduce it. 
![image](https://user-images.githubusercontent.com/53317567/68807790-37648280-0647-11ea-8a16-135bfc2192ab.png)
If there are any specific steps could you please find them? @SlayksWood

**Comment by D3nnis3n** [comment]
Closed, issue was emptying of Profanity.eco but leaving a space in there. We should have some failsave for that.
