### ISSUE TITLE
Carts and borders still make carts disappear ( those dam borders !!! ) 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1364]
http://ecoforum.strangeloopgames.com/topic/2206/5-5-4-powered-carts-bug

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2199/maybe-a-temporary-solution-to-the-cart-ordeal

**Comment by SeanAtr0n** [comment]
fixed in 5.6
