### ISSUE TITLE
Staging sources: housing broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13645]
Room ok, but not counts as any tupe of room.
![изображение](https://user-images.githubusercontent.com/4980243/68547284-d93e6200-03f0-11ea-8d2b-81f1d243bddf.png)

**Comment by SlayksWood** [comment]
I can't reproduce. Can you provide more information?

**Comment by elfl0rd** [comment]
Save?
idk what happens, it is fresh world - claim some place, build house, put furniture in and nothing, room ok, but no points.

**Comment by mirasrael** [comment]
Seems like a have locally similar problem.
