### ISSUE TITLE
0.8 maybe 0.9 Treasury - Manage funds, no scrolling

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13646]
As i think, this window need scrollbar.
![20191109191633_1](https://user-images.githubusercontent.com/4980243/68542823-65389580-03c1-11ea-8483-505a0fc7a385.jpg)

**Comment by elfl0rd** [comment]
*No scrollbar.
You can scroll, but you cannot see position or you cannot jump.

**Comment by SlayksWood** [comment]
UI is broken now:
![image](https://user-images.githubusercontent.com/45708377/77880801-27e87d80-7266-11ea-94b9-2436d452b4e8.png)
