### ISSUE TITLE
Staging sources: no "allow" action in laws

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13642]
![изображение](https://user-images.githubusercontent.com/4980243/68545931-db012900-03e2-11ea-9487-7dcc0279a724.png)

**Comment by Praefator** [comment]
As you're allowed everything by default (when no laws are in place), I'd imagine 'allow' to be pretty redundant. Same thing with the current 'tax 0 credit' clauses that essentially mean 'do nothing'. 

In my opinion, neither of those two really add anything, and at best just make laws more convoluted.

**Comment by elfl0rd** [comment]
No.
There are a lot of situations in which it is necessary to restrict all and allow someone.
At the same time, we can't "just" allow it, it's stupid. We have to do it through a tax or a payment of 0.

**Comment by elfl0rd** [comment]
For example, prohibiting the use of chat by anyone other than administrators...
If you are an administrator, allow...
Oops, we do not have the option to allow it.
If you are an administrator - tax 0.
If you are not an administrator, ban it.

It looks stupid and causes a lot of questions and sarcastic comments.

**Comment by johnkslg** [comment]
You can use the 'Not' clause to get that case. 
![image](https://user-images.githubusercontent.com/3536496/68907006-18bfc380-06fb-11ea-8052-d77d241c4bb4.png)

**Comment by elfl0rd** [comment]
okay :D

**Comment by johnkslg** [comment]
Adding the Not clause
And the 'none' clause for sets too just to be extra
![image](https://user-images.githubusercontent.com/3536496/68907661-6fc69800-06fd-11ea-97a9-a4ba8ac9fd8f.png)
