### ISSUE TITLE
0.8 - 0.9 tool hint not contain durability info

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13643]
E.g. look at axe...
Af you try to see hint trough reciepes, or links... etc.
![изображение](https://user-images.githubusercontent.com/4980243/68545967-34695800-03e3-11ea-8719-902bd43bb643.png)

But if you have it...
![изображение](https://user-images.githubusercontent.com/4980243/68545979-5531ad80-03e3-11ea-8040-a7b79dbae8fa.png)

**Comment by redwyre** [comment]
It doesn't make sense to tell you the uses remaining in recipes, but I can probably add a max durability.

**Comment by elfl0rd** [comment]
Yeah, that's exactly what's needed.
Thank you!

I regularly see problems with players who can't understand what the "best" tool is better.
It is stronger... But how much?
