### ISSUE TITLE
[0.9.0 staging-1244] Web election is dropping FPS.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13649]
Step to reproduce:
- Spawn some civics objects. Add several Laws to vote. Have FPS= 60:
![image](https://user-images.githubusercontent.com/45708377/68582526-02f89700-048c-11ea-8fcf-3acaf023dcec.png)

- open Government -> Legislation -> Vote -> "Open in your browser"-> Yes.
![image](https://user-images.githubusercontent.com/45708377/68582557-17d52a80-048c-11ea-890f-2053b6b8e2a4.png)
- in browser select yes or no and submite vote. Don't close website and don't change tab in browser and open game. I have FPS = 20 max:
![image](https://user-images.githubusercontent.com/45708377/68582957-11937e00-048d-11ea-8b0a-7cf461878df2.png)
It seems like special limit was added.

**Comment by johnkslg** [comment]
Need more info on this. 
My guess is this is what's going on:
When you switch so the game is no longer focused, it runs at a reduced frame rate. When you switch back to the game, frame rate returns. Is that what's happening?

If frame rate is still slow when returning, can you do this:
- If you disconnect and reconnect client is it still slow?
- If you restart client is it still slow?

**Comment by SlayksWood** [comment]
When I switch to browser to vote and without closing Vote page return to game I have large FPS drop. After restart  game or reconnect (in this case) my FPS will be basic. It looked like when game is no focused my FPS dropped to 20 and when I switched back FPS doesn't return back.

But for example today I haven't this problem. And I can't it reproduce at all.
Maybe I have a local problem due to the second monitor (I had small problems with it a couple of days). I’ll put it for investigation. if I can't reproduce it, I’ll close it.

**Comment by SlayksWood** [comment]
Can't reproduce another time. Closing for now.
