### ISSUE TITLE
[0.9.0 staging-1244] Can select same rank for different candidates in game election

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13651]
@johnkslg in website I should select different rank for all candidates.
How I vote in game:
![image](https://user-images.githubusercontent.com/45708377/68584625-26721080-0491-11ea-9549-9867ad65bfa8.png)
1. beastyn
3. TC5, TC6, TC10
4. TC4, TC7, TC8
5. TC1, TC3
6. TC2,TC9

How it display in website:
![8b162216bed3774f928e8fff8ef5d110](https://user-images.githubusercontent.com/45708377/68584733-7a7cf500-0491-11ea-82f9-108f1b3cbc3d.png)
1. beastyn 
2,3,4. Random TC which I gave 3 Rank.
5,6,7. Ramdom TC which I gave 4 Rank.
8,9. Ranmdom TC which I gave 5 Rank.
10,11. Random TC which I gave 6 Rank.

**Comment by olegshegai** [comment]
Reverted the fix. Will wait for the UI to be fixed first.

**Comment by johnkslg** [comment]
Voting in game is not allowed, you must be taken to the webpage.
This is to encourage disucssions and use of the web features like graphs, etc. 
Closing.
