### ISSUE TITLE
Linux CPU Overusage

### ISSUE THREAD

**Issue by exp131** [StrangeLoopGames/EcoIssues#13655]
Hi,
I'm trying to run my ECO server 0.8.3.0 on Debian Linux under Mono, version 5.20.1.34
But after player count gets more 15, it starts to lag dramatically. Several seconds lag, unable to make a single action, and disconnects make the game unplayable. The server is quite powerful: Intel Core i7-7700, 64 Gb RAM, 512 SSD. When I looking into CPU stat I see over 300% load.
Is the issue caused by Mono, or the game engine itself?

**Comment by mirasrael** [comment]
@exp131 Thanks for report!
Eco Server isn't officially supported for Linux hosts. We have improvements for Linux support in 9.0 though (we switched to .NET Core, so it will run native on non-Windows platforms). 
Windows servers is running stable with such number of players, so I may suspect issue is coming from Mono. Mono is considerably slower than .NET Framework (and .NET Core considerably faster than .NET framework, so we expect to have significant boost for Linux hosted servers after 9.0 release).
I'll keep this issue open to re-check it after 9.0 release.

**Comment by redwyre** [comment]
@exp131 Have you tried Eco 9.0?

**Comment by redwyre** [comment]
Many improvements with 9.0 and 9.1, reopen if still having issues after upgrading.
