### ISSUE TITLE
Player icon on map not updating ( icons on map are not working / updating) 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1365]
https://www.youtube.com/watch?v=gvQf2SYRxHI

http://ecoforum.strangeloopgames.com/topic/2112/bugs-reports-in-videos

**Comment by benjamin-willard** [comment]
I've seen this happen a couple of times in 5.5.2

**Comment by stett** [comment]
The original bug was posted just before a bunch of minimap updates... I'm not sure it's an issue anymore (wasn't able to reproduce it) but it might be, so I'll leave this here for now.

**Comment by MarjieAVolk** [comment]
I've never seen this, so assuming this is fixed
