### ISSUE TITLE
[0.9.0 staging-1244] I can enter election for adding a law or title

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13652]
And I can even leave a speech.

@johnkslg I assume I should be able to enter election for the elected title only

![bandicam 2019-11-11 16-47-05-083](https://user-images.githubusercontent.com/27898520/68585200-5d512200-04a3-11ea-959e-b2b70ded3a97.jpg)

**Comment by johnkslg** [comment]
Hah, youll need to add a new type of filter. Follow the lead for existing 'active only' and similar filters.
