### ISSUE TITLE
[0.9.0 staging-1244] Server failure

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13653]
![bandicam 2019-11-11 17-00-45-133](https://user-images.githubusercontent.com/27898520/68586679-fdf51100-04a6-11ea-8600-459228448641.jpg)

**Comment by beastyn** [comment]
nope, still here
But didn't make a screenshot

**Comment by mirasrael** [comment]
Steps to reproduce?
I tried to comment election and everything worked fine.

**Comment by beastyn** [comment]
Will try to fins a trigger

**Comment by beastyn** [comment]
Well, I got this somewhere in the process of testing sea level and updating Sea Level graph on the site (/ff was enabled)
![bandicam 2019-11-13 16-31-39-270](https://user-images.githubusercontent.com/27898520/68760195-23af2100-0633-11ea-9660-03c0fe5c4034.jpg)

**Comment by beastyn** [comment]
will make other issue as its other error
