### ISSUE TITLE
[0.9.0 staging-1245] Missing bank account tooltip at contract board.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13663]
![image](https://user-images.githubusercontent.com/45708377/68666744-8af6a380-0555-11ea-9312-513578e40e86.png)
8.3.0:
![62200192-900c5a00-b38d-11e9-8395-d7a6852eb17c](https://user-images.githubusercontent.com/45708377/68666886-cd1fe500-0555-11ea-83e5-c693db8864f1.png)

**Comment by SlayksWood** [comment]
also see Currency exchange.

**Comment by serpopov** [comment]
also see this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/14448
