### ISSUE TITLE
[0.9.0 staging-1245] Web-elections: strange button

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13662]
On a page with an active law we don't need this button, I assume
![bandicam 2019-11-12 15-59-03-748](https://user-images.githubusercontent.com/27898520/68666417-b71a2080-0565-11ea-87ae-747bd97cb5e2.jpg)

**Comment by elfl0rd** [comment]
afaik, this button available at all laws for all admins.
