### ISSUE TITLE
[0.9.0 staging-1245] "Everyone" visually doesn't disappear in Authorization tab

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13660]
Step to reproduce:
- spawn store
- select autorization tab. Try to delete Everyone:
![image](https://user-images.githubusercontent.com/45708377/68665481-2cc8c100-0553-11ea-8c38-4b661456b373.png)
- you can't. You can change tab, can reopen store "Everyone" will not dissapear. But when you try to add another Citizens "Everyone" will dissapear. It also work if you added new Citizens and then try to delete "Everyone".
![image](https://user-images.githubusercontent.com/45708377/68665782-bf696000-0553-11ea-8ff5-e38fd2f2405e.png)

**Comment by SlayksWood** [comment]
Not just for store.

**Comment by olegshegai** [comment]
Thanks for the detailed description, fixed
