### ISSUE TITLE
Cant import hosted world save to hosted world in different region

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13669]
For example, can't export save from world in sfo2, then import to world in fra1

Also cannot start world from save file if regions are different.

This will be required feature for sharing saves among all users.

**Comment by mirasrael** [comment]
Tried to start world in fra1 with save from us-west-2 and everything works fine. Need more information for reproduction. @rainfarmer Can you provide it in private message?

**Comment by mirasrael** [comment]
I investigated this issue and it looks like Accounts Site problem. Everything works fine with REST API.

**Comment by rainfarmer** [comment]
fixed
