### ISSUE TITLE
[9.0] Work Order cancel vanish Ressource

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13668]
If you cancel a job you will not get the resources back from the order currently running.

Cancel with the rightclick on Workorder. Because the cross is not working right now.

Like 1 Barrel is vanish after cancel Petroleum Work Order.

Or charred meat cancel and you lose the meat

They are just gone. Neither in the inventory nor anywhere else.

**Comment by WeaselDog** [comment]
Refund works now with multiple queue at same time and prevents canceling when inventory is full.
