### ISSUE TITLE
[0.9.0 staging-1248] Civics: In-game comments for election look wrong

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13676]
1. Add a comment on the web page
![bandicam 2019-11-13 09-24-32-527](https://user-images.githubusercontent.com/27898520/68756946-eb0c4900-062c-11ea-8b84-463aca290622.jpg)
2. Check incoming comment in game chat
![bandicam 2019-11-13 09-23-34-614](https://user-images.githubusercontent.com/27898520/68757046-142cd980-062d-11ea-8f6e-02f2dd354558.jpg)

@anatoly-slg can help with web part

**Comment by SlayksWood** [comment]
@johnkslg @olegshegai 
I think it's wrong behavior to duplicate comment in important notifications? 
![image](https://user-images.githubusercontent.com/45708377/69315133-e2c49700-0c46-11ea-8e83-947124eeffe1.png)
And I can't discuss now in separate chat this law. Earlier when somebody comment law in website separate chat appeared.

**Comment by beastyn** [comment]
Kirill was talking about a chat tag for a law.
It was looking like that in 8.3
![bandicam 2019-12-03 12-14-18-558](https://user-images.githubusercontent.com/27898520/70028538-b6a20200-15c6-11ea-9124-133327bc273b.jpg)

**Comment by beastyn** [comment]
We were talking about it with Den. It shou 

> Comments are rarely used - i don't think they warrant a tag per law. Having the comment streamed to the elections channel seems okay for me.

So, let it be with one channel for now.
