### ISSUE TITLE
[0.9.0 staging-1248] Dropping Markers glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13672]
![image](https://user-images.githubusercontent.com/45708377/68749485-5f37f400-060f-11ea-9f69-87a61e27a05a.png)
Step to reproduce:
- drop first marker:
![image](https://user-images.githubusercontent.com/45708377/68749551-737bf100-060f-11ea-8d3b-e99a50ee2d2a.png)
- drop second marker:
![image](https://user-images.githubusercontent.com/45708377/68749590-87275780-060f-11ea-8486-9dd29e79df10.png)
- drop more marker
![image](https://user-images.githubusercontent.com/45708377/68749640-a0c89f00-060f-11ea-9670-d2494b198fd1.png)
You can see minimap panel UI in 8.3.0. And need to pay attention to #13170 - 8 point.

**Comment by WeaselDog** [comment]
![MarkerSpam](https://user-images.githubusercontent.com/47330823/71772000-646f3c00-2ef8-11ea-9218-e23e449a6828.png)
