### ISSUE TITLE
[0.9.0 staging-1245] Fix tooltip activation for work order icons

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13670]
1. Put cursor in the center of the work order screen icon. Work order tooltip won't show itself
![bandicam 2019-11-13 09-50-53-004](https://user-images.githubusercontent.com/27898520/68734384-0448d180-05fc-11ea-909c-9f6103100ffd.jpg)

2. Put cursor on the bars side of icon. Tooltip will show up.
![bandicam 2019-11-13 09-50-55-322](https://user-images.githubusercontent.com/27898520/68734408-13c81a80-05fc-11ea-9ed8-ad271adb47e4.jpg)

Tooltip should work if cursor is anywhere on the icon

3. Add tooltip to the table work order icon
![bandicam 2019-11-13 10-07-05-330](https://user-images.githubusercontent.com/27898520/68734802-77067c80-05fd-11ea-987b-98794155d105.jpg)

**Comment by beastyn** [comment]
Still no tooltip on the table icon.

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/75677167-e29f5300-5c9b-11ea-8409-8707b966a527.png)
