### ISSUE TITLE
[0.9.0 staging-1248] Important notification UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13677]
1. Shadow?
![image](https://user-images.githubusercontent.com/45708377/68756945-27837900-061c-11ea-8f03-afb74cc7efa9.png)
2. Delete all doesn't work.
![image](https://user-images.githubusercontent.com/45708377/68757019-46820b00-061c-11ea-85bf-7773ffdcbc99.png)
3. @johnkslg, Why did you decide to remake UI? I prefer 2 icons it's better than "big" panel that is always shown. This UI much better:
![image](https://user-images.githubusercontent.com/45708377/68758045-1cc9e380-061e-11ea-943c-3c4a37e1ea31.png)
Can we remake it less "big". like:
![image](https://user-images.githubusercontent.com/45708377/68758121-3ff49300-061e-11ea-97de-77e565f39f68.png)
or maybe leave only 2 icons.

**Comment by johnkslg** [comment]
I agree the panel is too big and needs to be docked somewhere

**Comment by johnkslg** [comment]
Created a specific task list here: https://github.com/StrangeLoopGames/EcoIssues/issues/13745
Can close thise one.
