### ISSUE TITLE
[0.9.0 staging-1248] Web elections: can't add graph to the comment

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13675]
1. Add a comment to the election
2. Press Add Graph
3. Choose a graph
4. Press Submit
![bandicam 2019-11-13 15-39-20-140](https://user-images.githubusercontent.com/27898520/68756729-7b965980-062c-11ea-9ded-bb3702a7c0f8.jpg)

Nothing happens

Should take the comment with graph

**Comment by SlayksWood** [comment]
Also missing button delete Graphs near Remove Map:
![image](https://user-images.githubusercontent.com/45708377/72966192-53b33700-3dcf-11ea-8456-1dff451fea1d.png)

**Comment by denysaw** [comment]
Will be fixed when this one: https://github.com/StrangeLoopGames/EcoIssues/issues/15046 gets fixed.

**Comment by denysaw** [comment]
RemoveGraph button also fixed in: https://github.com/StrangeLoopGames/Eco/pull/5775
