### ISSUE TITLE
Error on discussion save query

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1367]
Using swagger to save a discussion.

I get this error in VS:
https://gyazo.com/b61fbe9a6f9fa12801cf6d8d003fcb59

After continue pass error, the discussion seems to save correctly.

I used these parameters:
`{
      "Guid": "1239b7c6-52ff-439f-b894-ae2406dd6734",
      "Title": "Law Passed",
      "Description": "Discuss the ramifications of passing or failing a law.",
      "Activities": [
        {
          "Format": "Data",
          "Title": "Data",
          "Description": "Consider the following data, which was referenced by class members while discussing how to vote on this law.",
          "Data": {
             "ChatLogSnippets": [
          [
            {
              "TimeSeconds": 0,
              "Sender": "string",
              "SenderUILink": "string",
              "Text": "string",
              "Icon": 0,
              "Temporary": true,
              "Graph": {
                "Keys": [
                  [
                    "string"
                  ]
                ],
                "TimeMin": 0,
                "TimeMax": 0
              },
              "Map": {
                "WorldLayer": "string",
                "Frame": 0,
                "TimeStartSeconds": 0,
                "TimeEndSeconds": 0,
                "PlaySpeed": 0,
                "CurrentTimeSeconds": 0,
                "Flat": true,
                "Pause": true,
                "CameraPosition": "string"
              },
              "Category": "default",
              "UsersWithVisibility": [
                "string"
              ],
              "Tag": "string"
            }
          ]
        ],
        "Graphs": [
          {
            "Keys": [
              [
                "string"
              ]
            ],
            "TimeMin": 0,
            "TimeMax": 0
          }
        ],
            "Maps": [
              {
                "WorldLayer": "SaltWater",
                "Frame": 1,
                "TimeStartSeconds": 0,
                "TimeEndSeconds": 99875.70584625383,
                "PlaySpeed": 0.5,
                "CurrentTimeSeconds": 98554.32000000021,
                "Flat": false,
                "Pause": false,
                "CameraPosition": {
                  "x": 0,
                  "y": 57600.5859,
                  "z": 171.33017
                }
              }
            ]
          }
        }
      ]
    }`

**Comment by rainfarmer** [comment]
Also using the default parameters gives same error

**Comment by MarjieAVolk** [comment]
Ohhh, I guess the Discussion class was using the wrong version of the Map class... working on a fix, you'll get/have to use the same format for maps as the rest of the code does now.

**Comment by MarjieAVolk** [comment]
K fix is pushed
