### ISSUE TITLE
Construction post not have bottom texture.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13684]
I also think it should be longer... To go underground on the slopes.

![изображение](https://user-images.githubusercontent.com/4980243/68809911-fe93d000-067d-11ea-800b-7f3cf616bed4.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/2c49e851-aeea-4eb9-9681-e60bc7eb6806)
