### ISSUE TITLE
Ecopedia should not contain "cuts"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13683]
Like this
![изображение](https://user-images.githubusercontent.com/4980243/68808499-ec646280-067a-11ea-842c-18bb9ec6a479.png)

As i think, in ecopedia we can see full info without "mouse hover hints".

**Comment by SlayksWood** [comment]
seems fixed:
![image](https://user-images.githubusercontent.com/45708377/75677317-3c078200-5c9c-11ea-9ebe-135b991f1109.png)

**Comment by elfl0rd** [comment]
srsly?
not.
![изображение](https://user-images.githubusercontent.com/4980243/75691215-07ec8b00-5cb5-11ea-988a-3990ecc4d5a7.png)

**Comment by SlayksWood** [comment]
Still an issue for components.
![image](https://user-images.githubusercontent.com/45708377/83627284-57d23b00-a59f-11ea-910c-c1ce38e3a38d.png)
