### ISSUE TITLE
[0.9.0 staging-1248] Something wrong with LOD

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13680]
If you are moving toward some models (tomato, sunflower, pumpkin) we can see the process of LODs changing. and on the far distance they seems big, static and strange.
https://drive.google.com/file/d/1Cu1hT_EMATQlHDFkpuRxUnucUAoWsRqc/view?usp=sharing
https://drive.google.com/file/d/1ca0PBSuRlVdqhHmdtzbHaIJpElYVXSdF/view?usp=sharing

(on the video Foliage Quality 114%)

**Comment by keegan-o** [comment]
This is a matter of settings tweaks, I just turned down all the impostor LODs to appear less agressively-- was 15%, now is 10%. May tone down even further, but it looks at lot better at 100% quality setting now.

**Comment by keegan-o** [comment]
After fixing various problems with the impostor lods and tweaking settings a bit, I'm going to close this. At this point there are just a few minor shading errors in the shader to polish and at 100% the settings are if anything too conservative, though at lowest settings things may be too aggressive. From here I'll assume it'll be a matter of tweaking the range available to players since 100% and above is good.

**Comment by SlayksWood** [comment]
0.9.0 Staging-1287:
I have 130% but this effect stiil very visible. For example:
- I see Corn:
![image](https://user-images.githubusercontent.com/45708377/70318077-3a125c00-1830-11ea-9c15-1a3177776c39.png)
- I start moving to it. Corn dissapears:
![image](https://user-images.githubusercontent.com/45708377/70318144-6c23be00-1830-11ea-8018-68cc970b7a3a.png)
- When i get close Corn should appear, but it's very close.
![image](https://user-images.githubusercontent.com/45708377/70318231-9d03f300-1830-11ea-848a-62ca7367b7e1.png)
![2019 12 06 Something wrong with LOD-Corn](https://user-images.githubusercontent.com/45708377/70318413-0edc3c80-1831-11ea-945c-152e13ed1324.gif)

Another Example - Tomatoes. It doesn't disappear, but a noticeable change in the model:
![2019 12 06 Something wrong with LOD - Tomato](https://user-images.githubusercontent.com/45708377/70318772-e0129600-1831-11ea-884d-1fdb632b7942.gif)

**Comment by keegan-o** [comment]
The corn was a bug where the LOD 1 renderer was disabled, and I just pushed out the tomatoes LOD to minimize how noticeable the change is, so closing this again. Also fixed huckleberries which had a similar bug and tweaked jointfir to look better with LODs.
