### ISSUE TITLE
Elections: test election data bug

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13688]
when i run /api/v1/elections/generatetestdata in swagger, i get this error:
{
  "Message": "Failed to start election adding an elected title: Change Civic Element complete: \nThis action is not allowed, by article: Constitutional Article 1..",
  "StatusCode": 500
}

This is on brand new server

**Comment by johnkslg** [comment]
@StanKryvenko Got your fix, can you also make this part of CI?  Just add [CITest] to it to make it run.
