### ISSUE TITLE
Allow Devs (not admins!) to /give wolf whisperer tier items

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13681]
I've been doing that on streamer servers for a long time and am tired to make my character naked to leave some little presents that only persist for that world. People love wolf-ears. Increases sales.

**Comment by elfl0rd** [comment]
Also additional note.
As I think dump shouldn't remove "bonus" items.

**Comment by WeaselDog** [comment]
It is worth noting that all admins have access to developer level commands. I just tested on my non-dev tier account.

**Comment by elfl0rd** [comment]
There are multiple auth levels.
"Devpack" and "SLG Developer"

**Comment by WeaselDog** [comment]
I believe you are talking about the icons players get in their chat handle. If you are talking of just chat commands, there are 4 authorization levels: User, Moderator, Admin, & Developer. 

Currently Admin have access to to the Developer commands. A normal admin can use the game breaking QA commands.

**Comment by beastyn** [comment]
@WeaselDog thanks for pointing. Access issue will be fixed with PR 5252.  Actually even users could use dev's commands.
I wil have to check access for subcommands additionally in the spare time.
@johnkslg what do you think about Den's suggestion?

**Comment by elfl0rd** [comment]
And...
As I remember, the restriction on giving items from pack`s came after some administrators who give them to themselves and their friends.
Personally, I don't see a problem with that.
This "protection" against honest people. Everyone who want it, can still get them in a bunch of ways (save edit, mod, editing server memory, editing server sources (if have), etc...).
This request is a request to add "check" to the "check".
https://github.com/StrangeLoopGames/Eco/pull/3963

Perhaps the best option would be just to allow these items to be given?
Smaller code, less verifications, less problems.
¯\_(ツ)_/¯

**Comment by beastyn** [comment]
So, as we have new restriction system, I think we can widen the list.
Now devs won't  have any commands on non-local servers.
So, How about to make a bunch of commands that can be used by the devs anywhere. But really some basic and really useful.
/fly
/record
/give whisperer

@johnkslg 
@D3nnis3n

**Comment by beastyn** [comment]
@John @D3nnis3n @WeaselDog 

As we still need to process this issue I need confirmation form you that we can allow developers take specific items like wolf whisperer.

**Comment by D3nnis3n** [comment]
My permission is implicit by creating this issue.

**Comment by WeaselDog** [comment]
We have this issue now: https://github.com/StrangeLoopGames/EcoIssues/issues/20261
