### ISSUE TITLE
[0.9.0 staging-1249] Underwater Darkness

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13695]
Step to reproduce:
- /noon
On Ground:
![image](https://user-images.githubusercontent.com/45708377/68850655-7e08ba00-06e5-11ea-988f-93fabf682cb2.png)
Underwater:
![image](https://user-images.githubusercontent.com/45708377/68850750-b6a89380-06e5-11ea-9f81-bbee85c69ad0.png)

**Comment by D3nnis3n** [comment]
Not sure if this is a bug, given light will not penetrate water indefinately. Hasn't been like this before, though.

**Comment by SlayksWood** [comment]
At night:
![image](https://user-images.githubusercontent.com/45708377/68940127-6b5cb680-07b3-11ea-97a0-f6c0622f3c8d.png)

**Comment by redwyre** [comment]
This is definitely broken, water is activating a darker tone mapping...

**Comment by SlayksWood** [comment]
Didn't it brightly? Everything is very well visible in midnight.
![image](https://user-images.githubusercontent.com/45708377/69312891-2fa56f00-0c41-11ea-8124-5ddb91bdc454.png)
![image](https://user-images.githubusercontent.com/45708377/69312802-fd940d00-0c40-11ea-80e4-cdf86c41f7a2.png)

**Comment by redwyre** [comment]
First it's too dark, then it's too bright, you're never happy are you :P

**Comment by D3nnis3n** [comment]
Try a game-adapted realistic brightness. One that allows you to see okayish but not easily at day and pretty hard, but possible at night.

**Comment by redwyre** [comment]
The underlying issue of why it was too dark is fixed, now it just needs some tweaking for the eye adaption

**Comment by redwyre** [comment]
Day
![image](https://user-images.githubusercontent.com/431728/69825695-d7332a80-125b-11ea-99a2-1eec407b13a6.png)

Night
![image](https://user-images.githubusercontent.com/431728/69825710-e4501980-125b-11ea-8343-69f4c5addafd.png)

**Comment by redwyre** [comment]
I'm not sure I can do much better _right now_ because fixing it properly would require updates to code that's waiting on a major update and possibly art changes too.
