### ISSUE TITLE
[0.9.0 staging-1249] Update message about duties preventing statuses

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13693]
![image](https://user-images.githubusercontent.com/45708377/68838759-52c7a000-06d0-11ea-992b-fc31aad03295.png)
In new world without any dev command (like /civics spawngov)

**Comment by johnkslg** [comment]
It says at the top that you have no rights to change things here, due to the constitution.
Let me know how I could make this more clear.

**Comment by johnkslg** [comment]
I could add something like 'You must be a member of the 'Active' demographic to change laws here'
or
'Laws cannot be changed until a constitution is ratified'

**Comment by beastyn** [comment]
Yeah, we need to make some kind of attention on the top, which will tell that Constitution is not Ratified and other preventing statuses.
![bandicam 2019-11-15 10-23-46-902](https://user-images.githubusercontent.com/27898520/68918982-23796780-0792-11ea-8fdd-962a1e62c4d5.jpg)

Will leave issue for this

**Comment by johnkslg** [comment]
Adding more details.

When no constitution:
![image](https://user-images.githubusercontent.com/3536496/69013080-0d55dd80-0931-11ea-8ea8-4d733db699e3.png)

When constitution doens't give rights:
![image](https://user-images.githubusercontent.com/3536496/69013410-3deb4680-0934-11ea-9be7-1be8f18a3a10.png)

When constitution gives rights, but you're not in the privileged group:
![image](https://user-images.githubusercontent.com/3536496/69013437-915d9480-0934-11ea-915b-6d1ef142cd94.png)

When the constitution is invalid:
![image](https://user-images.githubusercontent.com/3536496/69013470-28c2e780-0935-11ea-951e-32fdb288618c.png)
