### ISSUE TITLE
[0.9.0 staging-1249] Empty work notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13696]
Perhaps It's noted not only adding a contract, but also deleting contract after its completion.
Step to reproduce:
- no work notification.
![image](https://user-images.githubusercontent.com/45708377/68851421-fb80fa00-06e6-11ea-9911-88c55694f54f.png)
- take contract. Have 1 notification:
![image](https://user-images.githubusercontent.com/45708377/68851504-210e0380-06e7-11ea-9df5-14bfcd2ba656.png)
- read notification to reset "1" to "0"
- complete contract. I have 1 notification:
![image](https://user-images.githubusercontent.com/45708377/68851680-5fa3be00-06e7-11ea-9613-abd0dab691c5.png)
- but it's empty.Empty notifications constantly appear when working with contracts. Sometimes It appear when another player accepts your work, or takes your contract.
![2019 11 14 Empty work notification](https://user-images.githubusercontent.com/45708377/68851981-fc665b80-06e7-11ea-973c-c494a482553e.gif)

**Comment by beastyn** [comment]
Nope, still something wrong with counting.
After completing a contract I have 1 notification which I can't even open
![bandicam 2019-11-28 15-03-27-497](https://user-images.githubusercontent.com/27898520/69796694-44a97180-11f0-11ea-8a4e-c840d02c56f5.jpg)

**Comment by SlayksWood** [comment]
Still an issue. Step to reproduce:
- press create contract
![image](https://user-images.githubusercontent.com/45708377/70599320-e91eb100-1bfd-11ea-8d41-f64d4d1a94d4.png)
- don't post contract, delete contract:
![image](https://user-images.githubusercontent.com/45708377/70599354-081d4300-1bfe-11ea-841b-91f4232c1529.png)
- repeat it. You can see that number is growing.
![image](https://user-images.githubusercontent.com/45708377/70599500-52062900-1bfe-11ea-90ec-d29e7113f49f.png)
