### ISSUE TITLE
Map starts too zoomed in, also can zoom through the planet

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1369]
imo the map starts too zoomed in, it might be confusing at first for a new user.

Also the zoom through the planet thing:
https://gyazo.com/ef4541b0be67197b1e6255cee091dfb0

**Comment by rainfarmer** [comment]
Queries still giving y = 0

**Comment by MarjieAVolk** [comment]
I fixed this yesterday
