### ISSUE TITLE
[0.9.0 staging-1249] Ratio side of Minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13692]
When width is alot bigger than height some glitch appears. In 3D view:
![image](https://user-images.githubusercontent.com/45708377/68837757-51957380-06ce-11ea-8408-cfae8c042861.png)
in 2d view:
![image](https://user-images.githubusercontent.com/45708377/68837855-8f929780-06ce-11ea-9fa8-6ccf62d9a2ac.png)
8.3.0:
![unknown (3)](https://user-images.githubusercontent.com/45708377/68837414-894feb80-06cd-11ea-8936-07f3318f9568.png)

**Comment by beastyn** [comment]
still have glitches
![38a95eabb1484805c5e84de8f2404d2d](https://user-images.githubusercontent.com/27898520/69781389-ce951280-11cf-11ea-902b-4cafd0c4ac6d.gif)

**Comment by SlayksWood** [comment]
There is a slight flaw:
1. Make minimap with the smallest height and width. 
![image](https://user-images.githubusercontent.com/45708377/70969368-85d4c900-20ac-11ea-8fc8-31aeb240f4f2.png)
Start to increase height:
![image](https://user-images.githubusercontent.com/45708377/70969415-a13fd400-20ac-11ea-9c0b-8c671a6ff0fa.png)
It's better to see in 2D view:
![image](https://user-images.githubusercontent.com/45708377/70969446-b583d100-20ac-11ea-8ef1-c1a72f1f0c45.png)
2. You can flatten planet. Step to reproduce:
- select 3D, max width, min height:
![image](https://user-images.githubusercontent.com/45708377/70969562-0e536980-20ad-11ea-904c-aed33bd1ea1a.png)
- move out most of minimap per screen:
![image](https://user-images.githubusercontent.com/45708377/70969661-612d2100-20ad-11ea-8485-fc58a40b13db.png)
- increase width again:
![image](https://user-images.githubusercontent.com/45708377/70969772-b49f6f00-20ad-11ea-9186-cb7f85b4f6d8.png)
- try to move. Planet will flatten:
![image](https://user-images.githubusercontent.com/45708377/70969789-c1bc5e00-20ad-11ea-9cae-f552cc989004.png)

I change milistone to hotfix.

**Comment by TwixterZ** [comment]
Checked in 0.9.3.5 Release-235 & 0.9.4 Staging-2057 issue no longer present, closing ticket
