### ISSUE TITLE
my server is asking for a password that I dont remember ever havingUSER ISSUE: 

### ISSUE THREAD

**Issue by davthon** [StrangeLoopGames/EcoIssues#13694]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```you need a password to proceed
<size=150%>Connection Failed</size>

Invalid password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```you need a password to proceed
<size=150%>Connection Failed</size>

Invalid password.
```

**Comment by davthon** [comment]
not sure what mods are, the game just stopped while I was playing and would not let me play again without a password how do I GET BACK INTO THE GAME

**Comment by D3nnis3n** [comment]
Hello Davthon,
as i told you via support ticket, the Northern Lights server is not administrated by us and this is not a bug. I can understand this feels bad, but the only person that can set a password on that server is the administrator of that server and he or she is the one you need to contact to get to know the password. We have no influence on third party servers.
