### ISSUE TITLE
[0.9.0 staging-1249] Add possibility to place Starter Camp without Papers.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13690]
I will describe a very controversial case:
- I'm new player and start play in ECO. I login to my first server and Idk what I need to do. I have in inventory onle Starter Camp and 4 Papers.
![image](https://user-images.githubusercontent.com/45708377/68833519-b5b33a00-06c4-11ea-9f80-ee17a0fd9205.png)
- For a reason difficult to describe, I lost 4 Papers (deceived by other players, my own stupidity or just the desire to throw in the trash)
![image](https://user-images.githubusercontent.com/45708377/68833528-b9df5780-06c4-11ea-9b88-0918d7ee4cef.png)
- Now I can't Place Starter Camp. My game is over.
![image](https://user-images.githubusercontent.com/45708377/68833582-e5624200-06c4-11ea-8d05-e7b8df4d5ae4.png)
You need to change the way setting up your Starter Camp without using Papers, but with claiming Deed. You must still have a total 10 Papers.

**Comment by elfl0rd** [comment]
It looks work before, without papers you just not claim land...

**Comment by WeaselDog** [comment]
A player needs 2 Land Claim Papers to place Starter Camp. The Starter Camp contains 6 Land Claim Papers.
A simple fix is to reduce the Land Claim Papers in the Starter Camp by 2 but not require Land Claim Papers to place.

**Comment by elfl0rd** [comment]
> A player needs 2 Land Claim Papers to place Starter Camp. The Starter Camp contains 6 Land Claim Papers.
No, you can place SC to 2 or to 4 plots.
