### ISSUE TITLE
curve shader performance

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#137]
GPU Perf is being seriously tested with the minimap shader... curve functions are called most frequently and are not optimized (for example, 2 extra matrix transforms)

**Comment by stett** [comment]
perhaps there's a way we could get rid of the trig functions... islerp? is that possible?

**Comment by metachronism** [comment]
why was this closed?

**Comment by johnkslg** [comment]
Sean, did you get a chance to address this with your recent changes?  
Pushable to beta.

**Comment by SeanAtr0n** [comment]
I eliminated one extra matrix operation, didn't really make a measurable difference so it might not be worth pursuing further.
