### ISSUE TITLE
Original commands not ewerytime work if server and client at non-english lng.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13703]
e.g. my player cannot use "/unstuck", but can "/освободить"
For me - unstuck work, but "/time set" - not, only "/время задать"
intended behavior - in any case English commands work, if another server language is selected, then the "translated" command will also work.

**Comment by beastyn** [comment]
should be fixes by mirasrael

**Comment by elfl0rd** [comment]
nope.
![изображение](https://user-images.githubusercontent.com/4980243/86502279-1b664a80-bdaa-11ea-8b99-105be7d7d2e9.png)

**Comment by mirasrael** [comment]
It isn't clear from screenshot what you're trying to enter.
If entered command was /util then you see correct output, because it requires additional argument. If entered command was /утил, then the original issue is about being able to enter English commands when server has non-English local.

**Comment by elfl0rd** [comment]
I entered /утил топливо and should see "no target" error.

Also again, server should support both commands languages at same time, selected and english.

**Comment by mirasrael** [comment]
Btw I didn't do anything to fix it :)

**Comment by beastyn** [comment]
Hmm. Something not right here.
I have some mix from english-russian commands
Server - Ru
Client - Ru
![bandicam 2020-08-04 12-25-15-725](https://user-images.githubusercontent.com/27898520/89265334-bf634000-d64d-11ea-8312-295dc985f2eb.jpg)

I can't call /эмоция no more.
![bandicam 2020-08-04 12-27-48-414](https://user-images.githubusercontent.com/27898520/89265453-f0437500-d64d-11ea-83fe-31720b3e6309.jpg)

**Comment by mirasrael** [comment]
Because not all commands localized.

**Comment by elfl0rd** [comment]
эмоция localized

**Comment by mirasrael** [comment]
yeah. I found a problem. It was because localization string was "emote", but in code it tried to localize "Emote" (capitalized).
