### ISSUE TITLE
[0.9.0 staging] Unable to edit contracts that have not been posted

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13704]
If you close a contract before posting it there is no way to reopen it, preventing any contracts from being posted. The edit contract buttons that previously available are no longer visible.

![contractmessage](https://user-images.githubusercontent.com/47330823/68885873-d8485180-06ca-11ea-84e6-9d16fa84e04a.png)

**Comment by WeaselDog** [comment]
The work tab actually has some issues. An unposted contract is not showing up consistently in work tab. In addition other users can edit contracts not started by them. I will investigate more and repost.

**Comment by beastyn** [comment]
Yeah reopening for 0.9 fixes. Quite annoying thing.

**Comment by WeaselDog** [comment]
Not an issue with how contracts are posted now
