### ISSUE TITLE
Elections not working 8.3.0

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13707]
We had this one before. Election page is blank, noone can be elected, see No Winner last election and current one is empty again. Laws work. Probably a no-fix given 9.0 changes, still would be good to find out why this happens and to prevent it on 9.0. I'm getting the save file.

![election](https://user-images.githubusercontent.com/25908592/68905055-277c9980-0740-11ea-8662-e4db944f1499.png)

**Comment by D3nnis3n** [comment]
https://mega.nz/#!4dJzhYRY!r5oeRSW4OOpTa6BxIYMrMmeqPKV3U8WmukuaFHZVYAw

**Comment by D3nnis3n** [comment]
This happens when a player with weird characters takes part in the election. We'll need to make sure that characters like "'" do not cause issues. It's the same for comments, if you use some special signs, announcement on the server looks extremely weird.

**Comment by johnkslg** [comment]
This is fixed in 9.0, unfortunately we'll need to live with it for awhile in 8.3.

**Comment by redwyre** [comment]
I've make a quick fix to Election.js here: https://drive.google.com/file/d/1dIvKNms70VwhhrOfFkBvuDWmoO1aBOyW/view?usp=sharing

Go into `WebClient\WebBin\inc\js` and back up the existing Election.js and replace it with this one.
