### ISSUE TITLE
[0.9.0 staging] Contracts have negative time counter in Work Tab

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13705]
When creating contracts, there is an issue with the time due in the new work tab. It constantly counts from -1s to -59s and then resets back to -1. If you have multiple contracts offered, they will all be on the same counter. If you accept a contract, the time due works correctly.

Expected Behavior: There should be no time due for contracts that are not accepted.

Actual Behavior: 
![NegativeCounter](https://user-images.githubusercontent.com/47330823/68889770-66740600-06d2-11ea-8aff-d3841f0a7262.png)

**Comment by SlayksWood** [comment]
Also time is same at all completed notification.
![image](https://user-images.githubusercontent.com/45708377/68924640-56bbf680-0792-11ea-8147-d8700e70c816.png)
