### ISSUE TITLE
Building panels shouldnt be displayed when carrying something with no build options

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13708]
![image](https://user-images.githubusercontent.com/3536496/68905835-591d4280-06f7-11ea-9ad4-7e21bc4e578d.png)
IE, Gasoline shouldnt show that 'point' panel at all, cause all you can do is put it down.

**Comment by redwyre** [comment]
Dulicate of https://github.com/StrangeLoopGames/EcoIssues/issues/13826
