### ISSUE TITLE
[0.9.0 staging-1249] Big FPS drop at big depths

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13700]
Step to reproduce:
- create new world.
- make  deep hole to zero point (use /test elevator and delete elevator)
- look down from top position. I have FPS near 90-100:
![image](https://user-images.githubusercontent.com/45708377/68859638-c7aed000-06f8-11ea-820f-04eb2c35e369.png)
- look up from zero point.  I have FPS near 15-20:
![image](https://user-images.githubusercontent.com/45708377/68859729-f3ca5100-06f8-11ea-8333-11be51ee9aa9.png)
For bigger FPS drop you can make hole wider.
In 8.3.0 I had slight FPS drop from 100 to 70.

**Comment by redwyre** [comment]
To test, if you fly in the wall I expect you will see a lot of stuff that's on the surface. This require a new visibility system to fix so it's unlikely to happen for 9.0.

**Comment by SlayksWood** [comment]
I would say another, it's should happen in 0.9.0. Because I built a similar structure in 0.8.x versions with elevator. I usually kept Tailings here, something like underground tailings conservation (and I'm not one  who is doing this). Now I don't need to look into the tunnel for big FPS drop. I can start placing, for example, stockpiles here. But as soon as my camera is turned to top position instead down position, the FPS drops to 15.  I think that with such problem it will be very hard to mine various ores.

**Comment by mirasrael** [comment]
Tested on my local version. Can't reproduce. I have FPS difference between looking up and down, but it is something like 90 FPS vs 80 FPS. May be your world save will help.

**Comment by SlayksWood** [comment]
https://drive.google.com/file/d/1UYnnLroXYxdtL6gwIH4kHF0c7SxAu0Pt/view?usp=sharing
436,1,666

**Comment by SlayksWood** [comment]
It become much better for me.
