### ISSUE TITLE
[0.9.0 staging-1250] Add possibility to use Treasury bank Account for elected titles.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13709]
3 point is still here.
"It's in another table, but It's directly connected to Treasury: The description in the elected title that you can set the tax. But I think it’s need to describe not only the tax but also Treasury itself."
I still can't use Treasury as bank Account. You can add new point, for example, like "Can use Treasury bank account".
![image](https://user-images.githubusercontent.com/45708377/68931222-2891e300-07a1-11ea-99ef-10096c480427.png)

_Originally posted by @SlayksWood in https://github.com/StrangeLoopGames/EcoIssues/issues/13046#issuecomment-554277049_

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/68931744-3e53d800-07a2-11ea-8118-ebf180292c26.png)

**Comment by johnkslg** [comment]
@Quadbro can you help with this one? Can add as Kirill says, giving special access to the treasury account if a bool is checked.  Follow the pattern for how the other two special permissions work.
