### ISSUE TITLE
[0.9.0 staging-1250] Notification: Too small font for election notification

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13714]
Its just unreadable 
![bandicam 2019-11-15 15-30-00-116](https://user-images.githubusercontent.com/27898520/68936648-d2329d80-07bc-11ea-9d6f-b8ad9a134170.jpg)
Its global problem. For example I can have long-long law name and it will try to fit an UI.
![bandicam 2019-11-15 15-39-06-232](https://user-images.githubusercontent.com/27898520/68937439-33a73c00-07be-11ea-82d6-d1141ab39652.jpg)

**Comment by elfl0rd** [comment]
Tax notification
**![изображение](https://user-images.githubusercontent.com/4980243/69775555-1f921000-11aa-11ea-9b97-3c9eb0b2e847.png)**

**Comment by beastyn** [comment]
still here
![bandicam 2019-12-19 16-33-42-971](https://user-images.githubusercontent.com/27898520/71170666-9be5b380-227d-11ea-9d37-0e06a769b226.jpg)

**Comment by beastyn** [comment]
still actual
![bandicam 2020-01-05 22-16-42-591](https://user-images.githubusercontent.com/27898520/71783473-1ac24680-3009-11ea-90b5-40c6c0ac4f13.jpg)
