### ISSUE TITLE
[0.9.0 staging-1250] Web election: Need improvement for constitution election

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13712]
Election for constitution ratification looks a bit odd. Need to change the table to show info about articles.
![bandicam 2019-11-15 10-00-39-072](https://user-images.githubusercontent.com/27898520/68935698-ce058080-07ba-11ea-86e2-616656b39756.jpg)

**Comment by johnkslg** [comment]
Fixing this code side, anatoly as long as you update the header as described in discord it will work for this (and constitutional amendments too)

**Comment by johnkslg** [comment]
Fixed this to use the new ActionOnCompleteFullDescription and not supply a table. Anatoly passing to you to finish up setup.

**Comment by beastyn** [comment]
Still need to make it more readable

**Comment by SlayksWood** [comment]
It's pretty good now:
![image](https://user-images.githubusercontent.com/45708377/72965828-5b261080-3dce-11ea-98d9-9bbb3dcd28bd.png)
But if you add several lines. It will be better:
![image](https://user-images.githubusercontent.com/45708377/72965917-97f20780-3dce-11ea-8789-0a23a111155a.png)
