### ISSUE TITLE
[0.9.0 staging-1250] Ramp glitches.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13713]
1. You can't take more than 1 Ramp from ground (Dirt behavior).
![image](https://user-images.githubusercontent.com/45708377/68935248-5f6bf700-07a9-11ea-9f2d-11ae82d8b82d.png)
But you still can take 10 Ramp from storages.
2. Hard or Can't place Ramp with some tools:
- Hoe - you can't place Ramp on ground. But can place at construction blocks. But you can always  place in 0.8.3
Can't:
![image](https://user-images.githubusercontent.com/45708377/68935736-1c5e5380-07aa-11ea-9ef8-8f7eea523da4.png)
Can:
![image](https://user-images.githubusercontent.com/45708377/68935748-22eccb00-07aa-11ea-8748-e98665e9a2dc.png)
- Road Tool, Dev tool, Soil Sampler. You can't place at all. But can place in 0.8.3
- Fishing Pole. You can't place and can't place in 0.8.3.

**Comment by redwyre** [comment]
In your "Can't" picture, what is the shadow placement off in the distance?

**Comment by SlayksWood** [comment]
It's shadow placement from another tool (It's located in one place after changing tool to Hoe), nothing happens when you press RMB. I can't place Ramp with Hoe only at Dirt Block.

**Comment by redwyre** [comment]
1. You can pick up multiple of the same ramp, but you can't mix ramp types.
2. Definitely a problem

**Comment by beastyn** [comment]
@redwyre Fishing pole still won't work with ramp placement, is it intended?

**Comment by redwyre** [comment]
Do we want it to work with the fishing pole? I'm pretty sure there are other tools it doesn't work with.

**Comment by SlayksWood** [comment]
In any case if I try to place it with Fishing pole then it should be any notification.
![image](https://user-images.githubusercontent.com/45708377/77909348-e1ab1280-7295-11ea-84fc-bb2e10b5cd0a.png)

**Comment by mirasrael** [comment]
Fishing pole fixed in SVN.

**Comment by mirasrael** [comment]
After discussion and with player feedback decided to show neither ramp nor block shadow with tool which doesn't support block interaction.
