### ISSUE TITLE
[0.9.0 staging-1250] Civics: Don't have trash can for entitites

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13719]
Some objects has entities that you can add and remove (with trash can icon).
Like in Laws
![bandicam 2019-11-15 16-45-44-123](https://user-images.githubusercontent.com/27898520/68941577-0bbcd600-07c8-11ea-9c0e-98859324f4cd.jpg)

But we've lost this icon on some objects.
1. Census (dempgraphics)
![bandicam 2019-11-15 16-47-33-324](https://user-images.githubusercontent.com/27898520/68941629-3dce3800-07c8-11ea-8daf-a1d6a93a07b9.jpg)
2. Goverment Office (elected titles)
![bandicam 2019-11-15 16-53-30-527](https://user-images.githubusercontent.com/27898520/68941727-7b32c580-07c8-11ea-9b6c-b146bf197c35.jpg)
3. Amendments (articles)
![bandicam 2019-11-15 16-52-56-689](https://user-images.githubusercontent.com/27898520/68941746-8554c400-07c8-11ea-870b-96486c873270.jpg)

**Comment by johnkslg** [comment]
Serg, can you address this when you get to cleanup this UI? 
Lets remove the green garbage can entirely, and replace it with the red minus, so it matches the green plus.  Check that it appears in the right position on all entries.

**Comment by SlayksWood** [comment]
All trash can should be changed at "-".

**Comment by SlayksWood** [comment]
Still hard to press some "-", for example census:
![image](https://user-images.githubusercontent.com/45708377/85284797-750c7200-b498-11ea-8e2b-8595bd791781.png)
the green zone is the zone when hovering over which “-” appears. So it's very hard to select "-" when you try to move mouse from green zone to it. In most cases, "-" will disappear.

**Comment by serpopov** [comment]
this will be fixed within #16816
