### ISSUE TITLE
[0.9.0 staging-bleeding-edge] Typo in Abandoned Demographic

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13723]
Citizen is spelled wrong in the Abandoned Demographic. It is spelled correctly in the other demographics.

![AbandonedTypo](https://user-images.githubusercontent.com/47330823/68960112-5583cd00-0784-11ea-9a4c-3e52018c9068.png)

**Comment by WeaselDog** [comment]
I didn't underline it, but all special demographics have a comma instead of a period for the "Online hours"

**Comment by D3nnis3n** [comment]
"I didn't underline it, but all special demographics have a comma instead of a period for the "Online hours"

That should be language specific. In Europe it's a comma where you use a point and the other way round.

US: 1,000.00
EU: 1.000,00

**Comment by WeaselDog** [comment]
Typo is fixed. That is really good info about the comma vs. period. I will close this issue as that is a bigger discussion.
