### ISSUE TITLE
[0.9.0 staging-bleeding edge]  Logs moving on ground makes a door opening sound

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13727]
To reproduce chop a tree into logs and then walk into the logs on the ground. Every time the logs move it makes the sound of a door opening. Chopping down a tree will make the same sound, so it is anytime logs move.

**Comment by WeaselDog** [comment]
Sound also happens when you chop a tree

**Comment by SlayksWood** [comment]
dup #13487
