### ISSUE TITLE
Transactions window should not contain "cut"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13722]
it is annoying to scroll data in tooltip.
And wtf? we already have window for this data, why we need cut?
![изображение](https://user-images.githubusercontent.com/4980243/68958631-87754d80-07dd-11ea-9993-5f3eb8e51dbf.png)

**Comment by SlayksWood** [comment]
will be nice to see first 50 and button "show more" which add you another 50, without any tooltip.

**Comment by SlayksWood** [comment]
merged to #11059
