### ISSUE TITLE
Currency exchange interface issues

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13728]
1) you cannot change "owner currency" every time it reset to your.
![1](https://user-images.githubusercontent.com/4980243/68962797-7977fa80-07e6-11ea-844e-29a37b6a2f14.gif)

2) currency tooltop opens too fast and opens under menu.
![2](https://user-images.githubusercontent.com/4980243/68962808-7d0b8180-07e6-11ea-8bd7-4ad053a58b8a.gif)

**Comment by SlayksWood** [comment]
dup #13246 #13663

**Comment by elfl0rd** [comment]
2 isnt dup.
Tooltip appear too fast.
@SlayksWood
