### ISSUE TITLE
[0.9.0 staging] Tool Sound Issues in Staging

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13726]
It will be easier to keep a list. Most tools are fixed now. I will cross out ones that are fixed.

- [x] No Land Claim Stake sound
- [x] No Drill sound
- [x] No Fishing Pole sound
- [ ] No Soil Sampler sound (Will be added after animation and models)
- [x] All machetes have pickaxe sound
- [x] No sound for placing dirt from shovel
- [x] Steel Sickle, Steel Scythe, and Iron Scythe sound like pickaxe.
- [x] Stone Sickle & Modern Scythe has an added "wood chop" sound~~
- [x] No Machete sound
- [x] No Road Tool sound
- [x] Hammer sounds the same as pickaxe
- [x] Hoe sounds strange
- [x] No bow sound
- [x] No Chainsaw sound
- [x] Shovel the same as Hoe

**Comment by beastyn** [comment]
no sounds for all to0ls

**Comment by beastyn** [comment]
I will leave this issue for all tools checking. Not all of them has souns still.

Hammer sounds the same as pickaxe
No drill sound
Hoe is pretty strange, there should be ground sound, i suppose
No Machete sound (modern one has hoe sound)
No road tool sound
Scythe sounds like pickaxe
Shovel the same as Hoe
No bow sound
No soil sampler sound
No fishpole sound
No  Chainsaw sound
No claim stake sound

**Comment by WeaselDog** [comment]
@beastyn I edited the issue to include your list and crossed out ones that are working now.

**Comment by SlayksWood** [comment]
no sound for placing Dirt from  shovel

**Comment by SlayksWood** [comment]
all machetes has pickaxe sound

**Comment by Quadbro** [comment]
Please, do separate audio issues next time)

**Comment by Quadbro** [comment]
Sounds mostly are in, but need some tweaks from leonard, you can open extra issues, if found bugs

**Comment by SlayksWood** [comment]
All sound problems will be opened in a separate issues.
