### ISSUE TITLE
"Mine" block is "pickup block"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13721]
(I dont know, this more suggestion or issue, if you move it - pls, ping me)
Currently, "pickup blocks", manages mining of stones and ores.
It would be very good if we had separate options in 0.9.
"mine resource" (mine stone\ore block)
"pickup resource" - grab mined stones, ores, logs from ground
"dig" - dig sand, dirt, etc...

@johnkslg @D3nnis3n

**Comment by beastyn** [comment]
So we have
- Construct or Deconstruct (for building process)
- Dig or Mine 
- Drop or Pickup (for blocks placing on the ground)
- Place or Pickup for objects
