### ISSUE TITLE
Add Ecopedia to tabs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13733]
![image](https://user-images.githubusercontent.com/3536496/68969115-13b15180-0799-11ea-83d9-eb4ef1957db0.png)
Each of these tabs should have a question mark you can click that will take you to a wikipedia page on the topic, with the same icon shown there.  Make ecopedia stubs.

Do the same for all types of components that can be on world objects.
Once you got stubs I can go in and write up text for them

**Comment by johnkslg** [comment]
Also do for these guys: 
![image](https://user-images.githubusercontent.com/3536496/68969347-963a1100-0799-11ea-97de-a46388d99e50.png)

**Comment by johnkslg** [comment]
Probably just make them appear when you mouse over the tab? or maybe clicking the icon does it

**Comment by MilenkoTunjic** [comment]
can we make font in the "item, type, sale price..." smaller to match the tabs font size

**Comment by beastyn** [comment]
1. Civics actions - > move to the Authorization page
![c76fd437cd8765afff581bd6ee142f2f](https://user-images.githubusercontent.com/27898520/70209471-27295a00-1752-11ea-9b83-fe08713ba763.gif)
2. Pipes and Pump - to Authorization

**Comment by beastyn** [comment]
Still pipes leads on Government overview

**Comment by beastyn** [comment]
@johnkslg who is ob the linking task?
We still don't have some componetns pages, so links can be missed

**Comment by beastyn** [comment]
1. From Economy viewer:
Public crafting stations => Contracts
2. From Government
Popultation -> Laws )_ shpuld be Demographic maybe&)
Civics Duties -> Laws

**Comment by beastyn** [comment]
Public crafting stations => Item distribution
Why?

**Comment by serpopov** [comment]
Should lead to "Crafting" now
