### ISSUE TITLE
Laws Web Issue: Difference between two laws is "No Data"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13738]
![changesdontworkyet](https://user-images.githubusercontent.com/25908592/68974046-0ecbbc80-07f0-11ea-91f8-8ba60cfce727.png)

Given neither old or new law is at least displayed, this is high priority, cause what i am voting on?

**Comment by johnkslg** [comment]
Fixed
The data exists now, but is unreadable :) 

![image](https://user-images.githubusercontent.com/3536496/69011580-fc04d500-0920-11ea-9197-a6daa22885b3.png)
Anatoly will be fixing that issue.

**Comment by SlayksWood** [comment]
It duplicates information about proposed law:
![image](https://user-images.githubusercontent.com/45708377/72965000-52ccd600-3dcc-11ea-895c-8230f9fdba4a.png)

**Comment by beastyn** [comment]
merge #14888
