### ISSUE TITLE
Law UI feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13730]
![image](https://user-images.githubusercontent.com/3536496/68964459-4bff6280-078e-11ea-8df6-a437ee0f3ac8.png)

- Can we make the entries look like laws? A piece of fancy paper background perhaps.
- The one on the left should be official looking, stamp of approval. The one on the right should have the dashed line around it, and look more like a draft
- Dashed line should be around only the draft one.

**Comment by beastyn** [comment]
-and Header editining is quite mwssy now
![bandicam 2019-11-25 11-20-15-374](https://user-images.githubusercontent.com/27898520/69530539-01eb5d80-0f94-11ea-8240-aa0f4376268f.jpg)
