### ISSUE TITLE
[0.9.0 staging] Law issue when using "Values from Trade"

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13749]
When proposing laws that use variables from "Values from Trade" as a condition, they seem to not save properly. I believe the laws do not function as a result.

**Example using "Values from Trade"**
Proposed Law: 
![ProposedLaw](https://user-images.githubusercontent.com/47330823/69000261-a1686c00-0881-11ea-8372-c094c288c459.png)
Proposed Amendment:
![Ammendment](https://user-images.githubusercontent.com/47330823/69000265-b04f1e80-0881-11ea-9d72-4e3555770719.png)

**Example using static conditions:**
Proposed Law:
![proposedlaw2](https://user-images.githubusercontent.com/47330823/69000277-c65cdf00-0881-11ea-9461-e5ddc80b3c01.png)
Propsed Amendment:
![Ammendment2](https://user-images.githubusercontent.com/47330823/69000281-ce1c8380-0881-11ea-9382-2cd2bb090ee0.png)

**Comment by WeaselDog** [comment]
Here is another law that shows the issue better:
![ValuesFromTrade1](https://user-images.githubusercontent.com/47330823/69012932-b7cd0100-092f-11ea-8374-479d28d524a4.png)

Amendment:
![ValuesFromTrade2](https://user-images.githubusercontent.com/47330823/69012936-c0bdd280-092f-11ea-97a5-888f78bcbb4c.png)

**Comment by johnkslg** [comment]
I didnt see problems with them saving properly, but when revised the law the copy into the new law would fail for all context settings. Fixed.

**Comment by WeaselDog** [comment]
Fixed in latest staging
