### ISSUE TITLE
Chat system feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13745]
**Visuals**
![image](https://user-images.githubusercontent.com/3536496/68986912-1895f580-07d9-11ea-9ffd-4ca293192d3d.png)
- [x] Icons have a lot less detail than other icons in the game, bell especially.
- [x] Chunky side bar is too obtrusive, and looks scaled-up compared to the panels below it.  I think we should remove the side panel and just make the two buttons dock to the side of the window.

![image](https://user-images.githubusercontent.com/3536496/68987001-d7eaac00-07d9-11ea-9e6a-9c1f5a008207.png)
- [x] When folding out, it doesnt look like its running as smooth as it should, not changing every frame. Can you verify its moving every frame?  Also, use a lerptype of some kind like quad-out to give a better feel.
- [x] The icons are way bigger than they should be in this window, they are blown out and pixely.  The text could be smaller too. Compare to the size of the text below in the property panel.  Icons should be half the dimensions. Text size of date should be same or smaller as that of the message. Messages should be 50% wider and 50% less tall.  I should be able to see probably 6 messages at once. 
- [x] When closing a message, it should rapidly fade out and the ones below it move up (with lerp quad out or some such as always)
- [x] Notifications text at top is in contact with its frame.
- [x] Scroll bar wasn't visible.
- [ ] Messages could use a nicer frame than a plain rectangle
- [x] Delete All button has uneven margins (left and right are wider than top and bottom).  Text is contacting its frame.
- [x] When clicking between the work and notifications tabs, sometimes it would pop instead of expand. 
![image](https://user-images.githubusercontent.com/3536496/68987066-d53c8680-07da-11ea-8e52-7d07726a09c6.png)
- [x] Need better masking, a frame that contains it better ^ 
- [x] When a new notification arrives, it should show only that new notification. Currently it's showing the whole list. It doesnt need to show the panel with the 'notifications' header, just the new mail can appear for a moment. 

**Content**
This will be ongoing as we tune the messaging of the game and fix it up.
![image](https://user-images.githubusercontent.com/3536496/68987025-4d567c80-07da-11ea-8e73-496f2dad07d7.png)
- [x] Notifications of elections are happening twice.  
- [x] Delete All button wasnt working
![image](https://user-images.githubusercontent.com/3536496/68987098-32d0d300-07db-11ea-842b-47c51330d316.png)
- [x] Completed election didnt give me a message.
- [x] When someone buys or sells at my store it should notify me 

**Chat topbar**
![image](https://user-images.githubusercontent.com/3536496/68987161-f5207a00-07db-11ea-848f-8599e19616d1.png)
- [x] Lines intersecting messages
![image](https://user-images.githubusercontent.com/3536496/68987167-05d0f000-07dc-11ea-9c58-e2436e09cdfb.png)
- [x] This large black rectangle should never be visible when the cursor isnt visible, it's only to be clicked to move the notification on or off screen
![image](https://user-images.githubusercontent.com/3536496/68987212-8132a180-07dc-11ea-952f-aea3da81d086.png)
- [x] Make the notifications panel go down more. I could only see 1 and a half notifications. I should see 4-5 lines of text.  Also, reduce the empty space between messages, theres a lot there, make them pretty compact. 
![image](https://user-images.githubusercontent.com/3536496/68987202-5a746b00-07dc-11ea-9ccf-75d89993c34a.png)
- [x] This panel looks janky. Sprites have non-uniform scaling, border on message types looks bad

**Comment by MilenkoTunjic** [comment]
Indeed
