### ISSUE TITLE
No fishing sounds

### ISSUE THREAD

**Issue by shakey2** [StrangeLoopGames/EcoIssues#13746]
There are no fishing sounds when using a fishing pole. Was this never added or is it bugged? I need to hear that beautiful plop of the bobber hitting the water, the sound of the fish struggling and the line reeling :(

I'm running v8.3.0 beta

**Comment by beastyn** [comment]
Still no atmospheric enough.
I hear just reel sound when casting a fish rod (great backswing sound btw).
And one time snap sound when you real it back.
Steel need:
1)  Plop of the bobber hitting the water.
2) Fish stuggling sound (water-air).
3) Back reel sound.
4) Fish picking sound (when you take it from a rod)

**Comment by Quadbro** [comment]
Added pick sound
Added struggle sound (will be changed on toggle instead of one shot in future)
Added water hit sound
