### ISSUE TITLE
Make dropdowns that give more options more obvious to use

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13742]
As it's been complicated for me, and i don't think i'm especially dumb, i feel this could affect quite some players too:
![clear](https://user-images.githubusercontent.com/25908592/68979651-63763400-07fe-11ea-859b-45f6d7397169.png)
The dropdown markers could be hard to understand in the current form, you can easily oversee them, there is a lot of them under each other and you can easily mix them. They should at least get a tooltip like "Extended Options", if not better visibility or a better design idea in general.

**Comment by SlayksWood** [comment]
@D3nnis3n 
Did it fix with new UI?
![image](https://user-images.githubusercontent.com/45708377/77911475-85e28880-7299-11ea-8551-0219f5bfe338.png)

**Comment by beastyn** [comment]
UI was changes, should be fine
