### ISSUE TITLE
Demographics Issue: No actions available, comparison working weird

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13740]
1. Demographics can't be created based on actions and comparison of them.
For example:
You are a Statesman if your getting elected count > 5.
You are a Killing Machine if your harvest action where item is deer in the last 7 days > 7.

2. Comparison seems to work odd, when choosing it i can type in a number on the left and on the right side. Why would i want to compare two fixed numbers? That makes no sense, but there is no possibility to actually compare a variable (e.g. action count) against a value i set.

This was partly possible in 8.3.

**Comment by johnkslg** [comment]
There was an issue with stat count that was fixed
The other issues just need better UI to be discoverable
