### ISSUE TITLE
[staging-bleeding-edge] Server browser issue with map size

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13743]
The map size in the Server Browser has a question mark.
![mapsize](https://user-images.githubusercontent.com/47330823/68984558-9bad5080-07c5-11ea-86fe-3aa3ede55032.png)

**Comment by redwyre** [comment]
that should be km²

**Comment by gzatravkin** [comment]
Fixed by SVN changes
