### ISSUE TITLE
USER ISSUE: Cant login

### ISSUE THREAD

**Issue by VseOdbornik** [StrangeLoopGames/EcoIssues#13750]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
i installed Eco, it worked, everything was fine until today.

Log in to your SL account.

But i dont have account!!! I was logged as SucháVoda ( my Steam name ) please can you somehoaw help me I dont know that email so I cant reset the password. And steam E-mail does not work. Please help!!! I love this game. But i have only few days to destroy the asteroid!!!

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by VseOdbornik** [comment]
No mods. btw

**Comment by VseOdbornik** [comment]
Some developer could find that email :c

**Comment by beastyn** [comment]
Did you launch Eco from Steam or from folder?

**Comment by VseOdbornik** [comment]
I had to launch Eco from Steam ( you dont need login when its trough Steam.

**Comment by mirasrael** [comment]
@VseOdbornik glad to know you able can keep saving the World :) You can create new account on the SLG site and link it to Steam account. Then you will be able to use both Steam (when run with Steam client) and SLG credentials when run standalone client (which one you use when register on site).
