### ISSUE TITLE
[0.9.0 staging] Unable to remove Wages when drafting a title.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13756]
After adding a Wage to a title draft there is no way to remove it. This is especially problematic if you press the "+" button multiple times. 

![wagesissue](https://user-images.githubusercontent.com/47330823/69013399-2f049400-0934-11ea-850a-d2df4a3fe04b.png)

**Comment by johnkslg** [comment]
This is a problem with the UI, the close button is off to the right. Should be fixed along with the other UI bugs you got.

**Comment by beastyn** [comment]
Yeah, have it here #13719
