### ISSUE TITLE
New Law Trigger: Container

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13759]
Put into container
Pull from container 

(Possibly with options of the containers: small, medium, large container, bookshelf, chest, cart, etc.)

When trying to put into container where item is tailings, if in district National Park, prevent.

**Comment by johnkslg** [comment]
This is now part of InventoryAction

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/70109436-bd4d6b00-1600-11ea-873e-65e66a9ff1c8.png)
![image](https://user-images.githubusercontent.com/3536496/70109451-c6d6d300-1600-11ea-8ef9-9d1ee07f83fb.png)
![image](https://user-images.githubusercontent.com/3536496/70109787-db679b00-1601-11ea-9164-a2e769e082f5.png)

**Comment by johnkslg** [comment]
'Matching Objects' determines the storage container (and added a bug to allow naming overrides to describe this better)

**Comment by beastyn** [comment]
yeah, seems matching object filtration doesn't work yet. Without it you can use a law

![bandicam 2019-12-04 16-15-51-413](https://user-images.githubusercontent.com/27898520/70139340-15917500-16b4-11ea-982f-3539e2f2e696.jpg)

**Comment by beastyn** [comment]
@D3nnis3n leave for you to test too
