### ISSUE TITLE
[8.3.0] Webserver doesn't start

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13758]
> [00:41:56.814] [1] [ Info] [Eco] Starten des Webservers fehlgeschlagen (TargetInvocationException): Ein Aufrufziel hat einen Ausnahmefehler verursacht.
> bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> bei Owin.Loader.DefaultLoader.<>cDisplayClass12.<MakeDelegate>bb(IAppBuilder builder)
> bei Owin.Loader.DefaultLoader.<>cDisplayClass1.<LoadImplementation>b0(IAppBuilder builder)
> bei Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
> bei Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
> bei Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
> bei Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
> bei Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
> bei Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
> bei Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
> bei Eco.Webserver.WebServer.Init(Int32 port)
> Methode nicht gefunden: "Swashbuckle.Application.SwaggerEnabledConfiguration Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(System.Web.Http.HttpConfiguration, System.Action`1<Swashbuckle.Application.SwaggerDocsConfig>)".
> bei Eco.Webserver.Web.OwinStartup.ConfigureWebApi(IAppBuilder appBuilder)
> bei Eco.Webserver.Web.OwinStartup.Configuration(IAppBuilder appBuilder)

**Comment by redwyre** [comment]
What OS, version of the game?

**Comment by D3nnis3n** [comment]
8.3.0. Windows.

**Comment by redwyre** [comment]
32 bit or 64bit? And is there a corresponding .config file? Eg EcoServer32.exe.config or EcoServer.exe.config

**Comment by redwyre** [comment]
It looks like EcoServer32.exe is missing it's config in steam. You can copy the other one and rename it appropriately if that's what you're using.

**Comment by D3nnis3n** [comment]
Not my issue, actually. Support issue.

Simon <notifications@github.com> schrieb am Mi., 20. Nov. 2019, 17:41:

**Comment by redwyre** [comment]
Closing this as it wont be an issue in 9.0 as there aren't config files anymore
