### ISSUE TITLE
[0.9.0 staging-1254] Shadowplacement glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13763]
Step to reproduce:
- select any world objects at toolbar (Blast)
- look at ground and see shadowplacement
![image](https://user-images.githubusercontent.com/45708377/69048506-aad30f00-0a0e-11ea-852f-748e00826a0c.png)
- start to move camera to up. when you will not select any block then Shadowplacement should dissapear, but it isn't.
![image](https://user-images.githubusercontent.com/45708377/69048599-eff74100-0a0e-11ea-9dd0-ae54d9b4096a.png)
- start go away:
![image](https://user-images.githubusercontent.com/45708377/69048644-069d9800-0a0f-11ea-9ac5-acda21db1ac8.png)
![2019 11 18 Shadowplacement glitch](https://user-images.githubusercontent.com/45708377/69048657-0d2c0f80-0a0f-11ea-8dda-6f00de13fd7d.gif)

**Comment by redwyre** [comment]
This is might be something like the `InteractionManager` not clearing a selected block position, or the `PlayerHeldObject` not hiding the `ShadowPlacement` when the block position is invalid
