### ISSUE TITLE
[0.9.0 staging-1254] Lost Pollution Component on transport

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13767]
I didn't find vehicles in the filter fot Pollution Air trigger.
I've checked exca.
Seems like we've lost pollution component for vehicles
![bandicam 2019-11-18 18-58-02-841](https://user-images.githubusercontent.com/27898520/69058394-660e9e80-0a35-11ea-8203-7a109bac1433.jpg)
![bandicam 2019-11-18 18-57-41-923](https://user-images.githubusercontent.com/27898520/69058395-660e9e80-0a35-11ea-8849-64ad2cd17ae3.jpg)

**Comment by Sekor2600** [comment]
I noticed that the pollution is not shown until you have driven with it
