### ISSUE TITLE
[0.9.0 staging-1254] Pipes UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13761]
1. ConvertorOut instead Smog output:
![image](https://user-images.githubusercontent.com/45708377/69040304-a9014f80-09fe-11ea-8a70-9aae2598c9d9.png)
![65763480-f79c1700-e13c-11e9-80b2-7ac44ac7550c](https://user-images.githubusercontent.com/45708377/69040489-f1207200-09fe-11ea-8313-d93461a0082d.jpg)
2. Icons glitches. Step to reproduce:

- spawn blast. Has empty icons:
![image](https://user-images.githubusercontent.com/45708377/69040668-3b095800-09ff-11ea-83b0-f47fd7ac7741.png)
- add order ( or /test sewage). Icons missing. 
![image](https://user-images.githubusercontent.com/45708377/69040747-5f653480-09ff-11ea-8048-db5a6b6a74c9.png)
- reload. Icons will appear:
![image](https://user-images.githubusercontent.com/45708377/69040820-87ed2e80-09ff-11ea-8001-f419b6b340ae.png)
- wait until crafting will finish. Icons are still here.
![image](https://user-images.githubusercontent.com/45708377/69040998-d4d10500-09ff-11ea-9f2e-f93b07ab3f93.png)
- reload or wait some time. Icons will dissapears:
![image](https://user-images.githubusercontent.com/45708377/69041077-f3370080-09ff-11ea-8de4-1ed586e4cc35.png)

**Comment by beastyn** [comment]
@mirasrael are empty slots for pipes in idle mode are intended?
