### ISSUE TITLE
Update the control info

### ISSUE THREAD

**Issue by Hakuhonoo** [StrangeLoopGames/EcoIssues#13765]
Update the control info to allow mouse button icons with modifiers (shift, ctrl, alt?)
![image](https://user-images.githubusercontent.com/11686660/69056976-b7a93000-0a19-11ea-9e67-0e6fa2a89ab8.png)

**Comment by SlayksWood** [comment]
need review this

**Comment by johnkslg** [comment]
Was fixed by Oleg today
