### ISSUE TITLE
Last durability point work as "broken"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13769]
Just look.
We have durability for 1 hit.
![изображение](https://user-images.githubusercontent.com/4980243/69078221-70866380-0a48-11ea-8b28-f80c0c64122a.png)

But... calories cost as for broken tool.
![изображение](https://user-images.githubusercontent.com/4980243/69078257-88f67e00-0a48-11ea-8fd4-9ba76ed1261d.png)

**Comment by SlayksWood** [comment]
dup #12756
