### ISSUE TITLE
[staging] Civics: Confusing setup when using if/then statements

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13779]
~~In staging it is no longer possible to branch laws into sub-conditions with different effects. Below is a basic wealth tax in staging. More common versions of the wealth tax would have many sections to the law.~~ See explanation in comments:

Here is a basic wealth tax in 8.3. When you add in sub-conditions with their own sub-conditions, longer laws can be easier to write in the 8.0 system.
![releasewealthtax](https://user-images.githubusercontent.com/47330823/69113127-ef72a080-0a36-11ea-9b67-4621c1770405.png)

To address this issue, there should be some way to have if/then Conditions that result in different Effects so the entire law in not crammed into the Effects section.

**Comment by beastyn** [comment]
@johnkslg promised to us to look into this one., I will just leave it here

oh i see, so each condition block has its on effects block. interesting
hmmm yeah makes sense
will take a bit of work
probably need to make it clear the conditions block corresponds to the effects block

[Condition-effect-connection.pdf](https://github.com/StrangeLoopGames/EcoIssues/files/3862004/Condition-effect-connection.pdf)

**Comment by WeaselDog** [comment]
My apologies but it turns out it actually is possible in Staging. There is an "if/then" comparison in the Effects and it is possible to have branches. I'm not sure if this issue should be closed or just moved to lower priority. The actual issue is most of the law will be written in the effect section while the conditions section is left blank.

![wealthtax2](https://user-images.githubusercontent.com/47330823/69178660-e4635300-0abe-11ea-8282-bd6af1d2b6de.png)

**Comment by johnkslg** [comment]
Yeah this could be better.  Lets drop it in priority though.

**Comment by beastyn** [comment]
Yesh, that why we wanted to expand  this condition-effect logic. Logic should be in conditions.

**Comment by johnkslg** [comment]
Main issue is how to link the logic in the condition to the action, if theyre in separate boxes.  
But I'm sure we can design something.

**Comment by johnkslg** [comment]
Gave this some more love, check it out and let me know.

**Comment by beastyn** [comment]
Well, I like it. Will leave for @WeaselDog to test too before closing
This example was working fine
![bandicam 2019-12-02 13-41-56-452](https://user-images.githubusercontent.com/27898520/69944815-fbb42e80-1509-11ea-8e49-459344b0d82b.jpg)

**Comment by WeaselDog** [comment]
Looks great. Here is a longer version of wealth tax with an allocation included. Very clean:
![WealthTaxNew](https://user-images.githubusercontent.com/47330823/69993904-98260300-1501-11ea-92f4-272435ba92cb.png)
