### ISSUE TITLE
Query still adds comments to laws that are active

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1377]
After a law is active, commenting is no longer accepted.
But a cunning user could use the query to add comments to active laws.

Not really a big deal, but could be politically mischievous for a user, so as to seem like they knew a law was a bad idea from the get go, when really it was an after-thought. or something like that.

**Comment by MarjieAVolk** [comment]
Now law comment threads are chat channels, so it will be easy for people to continue using them.  I don't think there is really a problem with this; I might even suggest allowing further commenting via the web page as well.

Do we actually have a way to get rid of laws, other than forced removal by admins?  We totally need a vote to remove laws
