### ISSUE TITLE
Make saving more atomic

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13771]
If the server halts without properly saving, there's a likelihood it will fail to load next, because references between datastores are corrupted (one datastore references another that didnt get saved, and the link is then null on next execution).  

I think the solution would be a system that only creates the save when all the datastores have been saved with regards to references to make this safe.

This will be assisted by #13753, which will make systems more tolerant of missing references.

**Comment by mirasrael** [comment]
@johnkslg It shouldn't happen in current system with guaranteed save order. If you have concrete cases when it doesn't work then please attach them to issue for investigation.

**Comment by mirasrael** [comment]
I improved save system to either save everything after startup or save nothing. It was possible before to have partial saves on startup.
