### ISSUE TITLE
0.9 - currency hint appear too fast and under menu.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13773]
![2](https://user-images.githubusercontent.com/4980243/68962808-7d0b8180-07e6-11ea-8bd7-4ad053a58b8a.gif)

my comment there ignored - https://github.com/StrangeLoopGames/EcoIssues/issues/13728#event-2806230705

**Comment by SlayksWood** [comment]
Can't see currency tooltip at all:
![image](https://user-images.githubusercontent.com/45708377/81038849-15d6ac00-8eb0-11ea-880f-f5d2a4777458.png)
