### ISSUE TITLE
[staging] Issues with comparisons on periodic laws

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13778]
When using a periodic law, there is no condition that targets each player individually. You are only allowed to target individual users. This prevents many commonly used laws, such as a wealth tax.

Comparing Citizen Age:
![CitizenAge](https://user-images.githubusercontent.com/47330823/69110833-b1727e00-0a30-11ea-9af3-86b1d3d0a418.png)

Comparing Wealth:
![WealthComparison](https://user-images.githubusercontent.com/47330823/69110848-b8998c00-0a30-11ea-81f5-ec3012de375e.png)

Tax targets:
![TaxTargets](https://user-images.githubusercontent.com/47330823/69111216-b257df80-0a31-11ea-8f41-4cbac3cbfa67.png)

**Comment by D3nnis3n** [comment]
Both parts need the ability to use the user that is checked by the law. E.g. the law is done for every single player, the conditions are checked for every user, then if the conditions are met, the very same user is taxed. (Or something else done with him, this should work for every law type)

Wealth should be calculated by adding the balance of all accounts where the checked user is a manager of. Then, the calculated tax should be automatically taken by all of his accounts recursiveley. If a wealth tax calculation results in a tax of 1200 to be paid and the user only has 200 on his main account, it should take 200 from that, then go on to the next account he is manager on, take it there and so on. This is extremely important to not have people evading taxes by moving their money on other accounts.

**Comment by WeaselDog** [comment]
I believe the best way to address this is if one of the primary Conditions is "For each player". This will allow the "Citizen" user selection to appear in the options for both Conditions & Effects. The Citizen would be the target of the comparison.

In this scenario a law trigger would cause the effect for each player the condition was satisfied for. Players can have the effect target the Citizen the condition was satisfied for. This change will allow laws like Wealth Tax and other creative options.

**Comment by johnkslg** [comment]
I've added a clause that comes with the Timer trigger to repeat it for users in a demographic:
![image](https://user-images.githubusercontent.com/3536496/69198867-0f639c00-0aeb-11ea-918a-10867a0391d6.png)

Then you can just use the 'Citizen' context as with other laws:
![image](https://user-images.githubusercontent.com/3536496/69198882-18ed0400-0aeb-11ea-9e95-9a242e248c7a.png)

With 'everyone' so it runs on me and test users:
![image](https://user-images.githubusercontent.com/3536496/69198761-b3991300-0aea-11ea-8f95-fbd489df2955.png)

With admins, so it's just me:
![image](https://user-images.githubusercontent.com/3536496/69198795-d75c5900-0aea-11ea-8071-6cc0b9818fb2.png)

With 'Everyone' for a demographic, but then a filter in 'conditions' that cuts it down further:
![image](https://user-images.githubusercontent.com/3536496/69198930-3f12a400-0aeb-11ea-9724-cb427ff7ade1.png)

![image](https://user-images.githubusercontent.com/3536496/69198922-36ba6900-0aeb-11ea-985e-25b19432414c.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/69205820-e7cafe80-0aff-11ea-97fa-edb4d926a6e9.png)
Cleaned up display text some

**Comment by D3nnis3n** [comment]
Does it work as suggested when tax is higher than amount on the main account?

**Comment by WeaselDog** [comment]
I'll double check the wealth issue and create issue if needed. The Citizen variable functions correctly
