### ISSUE TITLE
Last (one) durability point work as "broken"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13772]
Just look.
We have durability for 1 hit.
![изображение](https://user-images.githubusercontent.com/4980243/69078221-70866380-0a48-11ea-8b28-f80c0c64122a.png)

But... calories cost as for broken tool.
![изображение](https://user-images.githubusercontent.com/4980243/69078257-88f67e00-0a48-11ea-8fd4-9ba76ed1261d.png)

This is not duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/12756 - https://github.com/StrangeLoopGames/EcoIssues/issues/13769
This is not "background at 0 durability".

**Comment by SlayksWood** [comment]
I can't reproduce this bugs (mine and yours) in 0.9.0 staging-1254. Seems fixed.
![image](https://user-images.githubusercontent.com/45708377/69127505-66ea1380-0abb-11ea-92d0-fab4d6a7a5fb.png)

**Comment by elfl0rd** [comment]
-50.
If you use tool with 1 durability, it's issue.
