### ISSUE TITLE
[staging] Not possible to create a law with a one-time effect.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13777]
In 8.3 it is possible to write a law that has a one-time effect when passed. In staging it is possible to create a law with a timer, but it is no longer possible to create a law with a one-time effect.

**Comment by johnkslg** [comment]
I've created a new type for this, executive actions, which are performed at an Executive Office.

**Comment by johnkslg** [comment]
Looks like that object needs some fixin's

**Comment by johnkslg** [comment]
Ok fixins applied

**Comment by WeaselDog** [comment]
Fixed
