### ISSUE TITLE
[0.9.0 staging-1254] Tutorial: Material Processing need update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13784]
1. We need to add a point about adding calories for this tutorial
2."Find the Hewn Log Recipe" point doesn't count crafted Hewn Log, maybe because of craft changes (its new parent recipe)
![bandicam 2019-11-19 12-18-52-214](https://user-images.githubusercontent.com/27898520/69125065-c39efb80-0ac6-11ea-82b3-a0816e854b02.jpg)

@Hakuhonoo can help with calories and craft part

**Comment by SlayksWood** [comment]
It doesn't work as it was in 8.3.0

**Comment by beastyn** [comment]
We will redo this one after finishink with craft systems.
We should explain Labor part more accurate.
Maybe make separate tutorial for it.

**Comment by SlayksWood** [comment]
arrow indicates Hardwood hew log instead Hewn log.
![image](https://user-images.githubusercontent.com/45708377/80367175-49ec1480-8893-11ea-9e92-63b7ccab2247.png)
