### ISSUE TITLE
[0.9.0 staging-1245] Civics: Laws- can't choose number amount for mint trigger

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13788]
1. Make a law
2. Choose trigger - Mint Currency
3. Choose effect - Tax
4. Try to choose Amount like Enter a Number. 
You will still have Currency Amount value in the Amount field.
But you should be able to put a number there

**Comment by olegshegai** [comment]
Outdated one, I suppose 
![image](https://user-images.githubusercontent.com/56091594/72219318-e0e7c780-3555-11ea-919a-aace4bde2f22.png)

**Comment by SlayksWood** [comment]
Seems fixed.
