### ISSUE TITLE
[0.9.0 staging-1254] Don't swing tools when no calories

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13783]
1. Make yourself hungry
2. Try to swing your axe
3. You will swing it
But - You should have error message, that you are hungry and don't swing.

Like it was in 8.3
![unknown (27)](https://user-images.githubusercontent.com/27898520/69120241-ef1be900-0aba-11ea-8480-8f19289d94de.png)

**Comment by redwyre** [comment]
The problem with this is the client doesn't know how many calories the tool needs, so it only checks if you have 0 calories. This means you can swing a tool when you have between 0 and the amount needed even though it will fail. Can probably provide the default calories through ItemInfo but it's a dynamic value.

See `ToolItem.NeededCalories` on the server and `PlayerHeldObject.ProcessInput` and `Player.obj.UserView.CanWork` on the client.

**Comment by WeaselDog** [comment]
I tested with every tool in 0.9.0 staging-1297. It is fixed, they don't swing now
