### ISSUE TITLE
Chat messages with newlines overlap each other

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13794]
![image](https://user-images.githubusercontent.com/3536496/69183216-6fe0e200-0ac7-11ea-95da-eb292ceda11b.png)

To repro: turn on civics debug with /civics debug
/civics spawngov true
Add a law that affects Harvest or Hunt action
Use a scythe

Youll see the debug spam over the law results.

**Comment by SlayksWood** [comment]
Seems fixed:
![Uploading image.png…]()
