### ISSUE TITLE
[staging] Can break laws with stack Court

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13792]
To replicate, you need a court placed with active laws on it. Pick up the court and then type /give court. The courts will be in a stack:
![court1](https://user-images.githubusercontent.com/47330823/69177084-bfb9ac00-0abb-11ea-8aea-c4ce04ac2c43.png)

- Place the two courts; law becomes active again. 
- Pickup the courts; law is inactive again. Looks like this: 
![court2](https://user-images.githubusercontent.com/47330823/69177323-28a12400-0abc-11ea-85e8-de998f116488.png)
- Place the courts; law remains inactive with no way to access the law.

**Comment by SlayksWood** [comment]
You can do it without /give command. Pick up court with Laws and place it to stockpile. 
![image](https://user-images.githubusercontent.com/45708377/69213360-e0920800-0b74-11ea-82c8-fb10c9bd2e67.png)
Crafting another court to this stockpile. Other steps same.
![image](https://user-images.githubusercontent.com/45708377/69213389-fa334f80-0b74-11ea-93da-3553197124fb.png)

**Comment by johnkslg** [comment]
Fixed this by making all unique items force a stack count of 1, which is how it used to work.
Looks like theres a problem with that though, too many items flagged as unique.
Ill need to fix that too.

**Comment by johnkslg** [comment]
OK fixed, and fixed unique objects all over from stacking.
