### ISSUE TITLE
Self Hosted citizens not working

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#13798]
Some users have citizens, but not a hosted world. They can manually set an IP address that the citizen is assigned to.

Auth should return that IP address, and the in-game menu should give them a shortcut to join their assigned world (same shortcut that is displayed for hosted worlds)

This shortcut is not displaying for 8.3.0

I see that /verifytokenv3 is not correctly returning the self-hosted IP address. It returns:
{
    "error": "Assigned world unavailable.",
    "status": false
}
/responsev4 is returning the self-hosted IP address correctly.

Update /verifytokenv3 so it returns the IP the same way /responsev4 does.
Hopefully this will fix the issue, but its also possible there is a game server bug too.

You can test with citizenqa user

Set this as critical because there are schools currently trying to use this feature.

**Comment by mirasrael** [comment]
Fix provided in PR: https://github.com/StrangeLoopGames/EcoIssues/issues/13798
It won't require any Eco client/server updates, so will start working right after AuthServer update.

Two options available now:
- specify externally available Server IP or IP:Port
- specify Server ID (for local servers or just as alternative to IP) - this will be faster and more robust.
