### ISSUE TITLE
[0.9.0 staging-1261] Can't Vote for Constitution from Ballot.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13799]
Step to reproduce:
- spawn first constitution, press ratify.
- place ballot and try to vote for Constitution from Ballot. You can select rank but when you press Perform action:
![image](https://user-images.githubusercontent.com/45708377/69212366-24cfd900-0b72-11ea-83d2-ed35989ec0f6.png)
Need to add possibility to Vote without Ratify Constitution.

**Comment by elfl0rd** [comment]
I'm not sure if there's any sense in voting for the constitution at all, because it turns the new system into an old one "needs a majority of votes".

**Comment by johnkslg** [comment]
Ballot box shouldnt open voting window in game, it should direct you to the webpage (voting takes place there so you can use the other features with voting: discussions, graphs, etc).  
I've changed the ballot box to not open the vote editor and instead go to the webpage.

**Comment by elfl0rd** [comment]
I hate webpages, too many issues with them =|

**Comment by beastyn** [comment]
Erm, it was kind a useful to vote in-game if you don't want to write ot discuss anything. Thats why I wanted to show comments in the Government and asked to change the boolean voting type in the Ballot. Why don't we make alternative?

**Comment by johnkslg** [comment]
Too easy to bypass a big part of the game: examining graphs and maps people have made, easily posting comments, etc.   If we ever bring that stuff all over into the game then it could be in game, but I dont want to have an easy-bypass.

**Comment by johnkslg** [comment]
@elfl0rd post those issues and they shall be fixed!

**Comment by elfl0rd** [comment]
> post those issues and they shall be fixed!

First, you need access to server directly, if you want to do something in web interface.
Opening ports, setup redirects, etc.
It's annoying for "game with friends".

Also web interface is really laggy :(

Ingame interface not have this problems. If you have access to game, you can use interface.

**Comment by elfl0rd** [comment]
@beastyn Idk, why we can not have "basic" things ingame? Okay, no grafs, no chart or maps...
Byt why we cannot vote and discuss from game?

It is one of most wanted things... :(

**Comment by beastyn** [comment]
@elfl0rd John's position is about - think, then vote.
So, you have to have arguments (like graphs, maps) to make an useful comment.
We have the Election channel where all comments for elections will be placed (need some work there too though).

So, we will think it through and make other issue if there is a fast option.

**Comment by D3nnis3n** [comment]
We talked about having this stuff ingame only, as i like the idea of people having to actually walk to their vote, it fits my server concepts. But i agree with John that this should happen in a later patch, when we can actually move all voting-relevant stuff to ingame. The voting also was complicated in regards that the normal user will not understand that ugly UI and that he needs to rank his votes in a yes and no votes with 0 being the best. (User types in 1 to yes, as that seems logic -> Voted no.)
