### ISSUE TITLE
Composite species names must contain a space

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13802]
BlueShark -> Blue Shark
BigBluestem -> Big Bluestem

etc.

**Comment by beastyn** [comment]
They are in tooltip for exmple. What exactly do you mean?
![bandicam 2019-11-20 14-56-18-761](https://user-images.githubusercontent.com/27898520/69228740-f10ea680-0ba5-11ea-8cdf-218ea469357e.jpg)

**Comment by elfl0rd** [comment]
e.g. map layers, stats data, etc.
![изображение](https://user-images.githubusercontent.com/4980243/69242743-99c30300-0bb2-11ea-82e5-0e7f7565d9c6.png)
![изображение](https://user-images.githubusercontent.com/4980243/69242766-a2b3d480-0bb2-11ea-96e9-f81512842970.png)
