### ISSUE TITLE
Long text in settings should use a smaller font size.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13805]
![изображение](https://user-images.githubusercontent.com/4980243/69225387-560ad200-0b8f-11ea-9e02-e7cb6981fd81.png)

**Comment by beastyn** [comment]
It should not. It will look awful.
1. We should translate with shorter string. Why not "Курсор наведения"?
2. Its a common problem when we are making font smaller for long strings and it looks unreadable.

**Comment by elfl0rd** [comment]
not ewerywhere you can translate short :)
e.g. nutrient, heh.

**Comment by gzatravkin** [comment]
What about truncate with hint on mouse overlap? 
Like "Непрямое затемнен..."

**Comment by elfl0rd** [comment]
In most cases, it is enough to reduce font size by 10-15%, it will remain readable but fit.
But, yeah, as a "emergency" case to "if it didn't fit in anyway," the trimming's fine.

**Comment by beastyn** [comment]
Still the same problem
![bandicam 2019-11-28 15-07-21-950](https://user-images.githubusercontent.com/27898520/69797018-d31df300-11f0-11ea-9134-7a4b70a3073c.jpg)

**Comment by SlayksWood** [comment]
A minor flaw:
![image](https://user-images.githubusercontent.com/45708377/70599700-da84c980-1bfe-11ea-98fd-3b324368bea5.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/71810325-2fdbbb80-3083-11ea-9da2-48f9fbc8f62c.png)
