### ISSUE TITLE
No strings for reputation

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13811]
"Reputation Title:"
"Reputation Total:"
"Relative Reputation:"

"Player opinions:"
"None yet."
"Network Multiplier:"
"(Relative reputation only counts the opinions from people you like, and people they like, etc.)"
![изображение](https://user-images.githubusercontent.com/4980243/69228394-8bfe8500-0b94-11ea-9e38-3efce8326e6d.png)

**Comment by SlayksWood** [comment]
still an issue
![image](https://user-images.githubusercontent.com/45708377/73335772-51deed00-4281-11ea-8bc5-750f169cce88.png)

**Comment by Quadbro** [comment]
Client + server in gibberish + restart for both
![image](https://user-images.githubusercontent.com/6802030/73631975-08314080-468d-11ea-9318-ba7a2dba022f.png)
