### ISSUE TITLE
[0.9.0 staging-1261] Put down action problem.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13812]
Seems after this changes https://github.com/StrangeLoopGames/Eco/pull/5265
Step to reproduce:
- take any item in hands (1 Limestone)
![image](https://user-images.githubusercontent.com/45708377/69232982-1c40c800-0b9d-11ea-8bf4-7da3e16c2c64.png)
- place it at ground
![image](https://user-images.githubusercontent.com/45708377/69232994-219e1280-0b9d-11ea-8dc7-cf7ddb0be885.png)
- pick up from ground 1 Limestone. But you will have 2 Limestone
![image](https://user-images.githubusercontent.com/45708377/69233003-25ca3000-0b9d-11ea-9e75-c62dff50573b.png)
- place it, pick up, have 4 and etc. You hands doesn't  lose item. If you place all item to ground you will still have all this item at hands, but visually it doesn't.
![image](https://user-images.githubusercontent.com/45708377/69233016-295db700-0b9d-11ea-8849-cfbeafccef60.png)

**Comment by johnkslg** [comment]
Was result of previous PR most likely, fixed. Nice quick find.

**Comment by beastyn** [comment]
@johnkslg  Im not sure if its fixed, but issue is still here with new build

**Comment by johnkslg** [comment]
PR didnt get merged in till now

**Comment by beastyn** [comment]
Fixed. Will be aware of other actions
