### ISSUE TITLE
Quality suggestion - main menu should contain "settings" button.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13818]
I get regular feedback from people who can't find the settings.

**Comment by SlayksWood** [comment]
@D3nnis3n

**Comment by D3nnis3n** [comment]
We could have a text  "Press ESC" for Settings, but i've not yet had seen people having issues with that. Can keep as suggestion.

**Comment by D3nnis3n** [comment]
What do you think, @SlayksWood?

**Comment by SlayksWood** [comment]
I think same.

**Comment by elfl0rd** [comment]
Okay, move to suggestion :)
But as I think, adding one button is not hard, and maybe it help some players.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/7217
