### ISSUE TITLE
Select a target to transfer ownership to. window have too small button for translate

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13817]
Can buttons have more space?
![изображение](https://user-images.githubusercontent.com/4980243/69245720-671c0900-0bb8-11ea-9c38-20b22fa328a2.png)

**Comment by SlayksWood** [comment]
All is broken
![image](https://user-images.githubusercontent.com/45708377/72789960-b24ca980-3c45-11ea-9550-3a02a5e5b5dc.png)

**Comment by SlayksWood** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/45708377/77909729-83cafa80-7296-11ea-8684-cb2f2c750df7.png)
