### ISSUE TITLE
[0.9.0 staging-1261] Civics: Tax doesn't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13814]
Looks like Tax doesn't work anymore. I've tried this law
![bandicam 2019-11-20 17-58-40-171](https://user-images.githubusercontent.com/27898520/69241286-4e175600-0bc0-11ea-9b76-83cf89a82aad.jpg)
![bandicam 2019-11-20 17-58-58-111](https://user-images.githubusercontent.com/27898520/69241291-51124680-0bc0-11ea-8002-162591e074ed.jpg)
![bandicam 2019-11-20 17-59-00-576](https://user-images.githubusercontent.com/27898520/69241294-52437380-0bc0-11ea-8f6d-7892aa0c0c03.jpg)

**Comment by johnkslg** [comment]
Fixed! Good find.
![image](https://user-images.githubusercontent.com/3536496/69289678-2b7e4080-0bb2-11ea-8d31-6b713e34baec.png)
