### ISSUE TITLE
user report / Laws not working / John is leader 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1381]
https://www.youtube.com/watch?v=MdWakoLjhYE&feature=youtu.be

**Comment by Neouni** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/1314

Basically still an issue

**Comment by MarjieAVolk** [comment]
Can't access the video - but this is an old bug and the law system has gone through several changes and fixes at this point, so gonna call this out of date.
