### ISSUE TITLE
0.9 new recipes lost products in hint

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13819]
![изображение](https://user-images.githubusercontent.com/4980243/69251987-5624c500-0bc3-11ea-8033-09293062c3ed.png)

Also there no "uses" in ingredients.
![изображение](https://user-images.githubusercontent.com/4980243/69252046-75bbed80-0bc3-11ea-834c-f6f8e663ec1c.png)

p.s.
fuel? 5000?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/69326911-b5cfae80-0c5d-11ea-9cd1-68811cfaf42c.png)

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/74308573-9c7c6100-4d79-11ea-8bff-e221a1171c39.png)
