### ISSUE TITLE
Extend generated elections

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13827]
Anatoly needs to be able to generate test data that will give examples to satisfy these cases:

https://github.com/StrangeLoopGames/EcoIssues/issues/13712
https://github.com/StrangeLoopGames/EcoIssues/issues/13656
https://github.com/StrangeLoopGames/EcoIssues/issues/13755
https://github.com/StrangeLoopGames/EcoIssues/issues/13738
https://github.com/StrangeLoopGames/EcoIssues/issues/13707

Extend the generatetestdata api to create more elections that match these qualities.

**Comment by gzatravkin** [comment]
All of that issues are already solved, so looks like no nee in any additional data.

**Comment by beastyn** [comment]
Nope. We need to adjust /civics spawnelection command and spawn with this:
1) Election for elected title candidates with some candidates in it (10 test users for example)
2) Election yes-no type for every object: law, district map, demographic, elected title, election process, amendment

**Comment by StanKryvenko** [comment]
@gzatravkin are you going to go through this issue?

**Comment by gzatravkin** [comment]
@StanKryvenko yes
