### ISSUE TITLE
Translation work, part 20.11.2019

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13822]
Missing strings for ecopedia
Lists
![изображение](https://user-images.githubusercontent.com/4980243/69228524-c7994f00-0b94-11ea-9fcb-f15aee5af4f3.png)

Recipe Variations
Select a specific recipe to craft.
Ingredients - exist, but not used - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#94844
Products - exist, but not used - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#94846
Craft - exist, but not used - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#97332
Show All - exist, but not used - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#152954

typo in bricklaying
"Bricklaying is an **advanAdvancedMasonry** in masonry and can provide an excellent building material for communities. Level by crafting related recipes."

skills - profession and speciality uses original names.
![изображение](https://user-images.githubusercontent.com/4980243/69267306-ec65e480-0bdd-11ea-9404-7bfb1d3f8427.png)

**Comment by Quadbro** [comment]
Nice catches, fixed
