### ISSUE TITLE
Civics: Contract & Mint Laws that involve a specific currency do not get triggered

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13823]
When creating a law with a trigger involving a contract using a specific currency, the law does not function. This is true for all of the contract related triggers. When using "Any" currency the laws work fine.

Law tested:
![ContractLaw](https://user-images.githubusercontent.com/47330823/69260674-1afba500-0b75-11ea-9dbc-249a8b305d9e.png)

Posted Contract afterwards:
![PostedContract](https://user-images.githubusercontent.com/47330823/69260694-218a1c80-0b75-11ea-9b35-b30fd7415067.png)

**Comment by johnkslg** [comment]
Had a peek at the code, from what I could see you're passing the currency in on the action, so seems like it should work.  Enable civics debug with /civics debug true
then check whats coming through on the action

**Comment by WeaselDog** [comment]
Here is the debug image:
![ContractCurrencyDebug](https://user-images.githubusercontent.com/47330823/69454221-8763d900-0d1a-11ea-8b0e-dcf6fa45ae47.png)

**Comment by WeaselDog** [comment]
It is also true for Minting:
![MintCurrencyTrigger](https://user-images.githubusercontent.com/47330823/69474093-29aeab80-0d71-11ea-8ce1-c34244e54502.png)

**Comment by olegshegai** [comment]
Reproduced and debugged this one, need to talk with @serpopov

**Comment by WeaselDog** [comment]
It is still an issue for both contracts & minting. The trigger is actually detecting it is using the currency, but for some reason the trigger is failing:

![ContractCurrencyDebug](https://user-images.githubusercontent.com/47330823/70063920-74b09600-159d-11ea-896e-ea6d978c354f.png)

**Comment by johnkslg** [comment]
@olegshegai can you finish up this one? chat to me in discord if you need help
