### ISSUE TITLE
0.9 tagged items not have hint in tooltip

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13824]
In marked section, links not have hints.
![изображение](https://user-images.githubusercontent.com/4980243/69264903-4dd78480-0bd9-11ea-81f4-f46d13f81f70.png)

**Comment by beastyn** [comment]
yeah, because of this #13007

**Comment by elfl0rd** [comment]
Hm. Removing cut is good for me, removing hints - is bad :(
