### ISSUE TITLE
[0.9.0 staging-1262] Tagged item icons missing in Repair tab of Tool bench.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13839]
![image](https://user-images.githubusercontent.com/45708377/69330208-9045a380-0c63-11ea-8ec6-8d5647d40672.png)
![image](https://user-images.githubusercontent.com/45708377/69330249-a3f10a00-0c63-11ea-9428-c12c175a74c9.png)

**Comment by beastyn** [comment]
And add tooltips for resources here too (tool has a tooltip and resource does not)

**Comment by SlayksWood** [comment]
no tooltip, no icon:
![image](https://user-images.githubusercontent.com/45708377/79107515-29916580-7d7d-11ea-84e3-358440f7feb4.png)
