### ISSUE TITLE
RuntimeGraphicsInfo issues

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#13831]
1. Have error from the package:
```
EntryPointNotFoundException: GetDedicatedSystemMemory
RuntimeGraphicsInfo.GetDedicatedVideoMemory () (at Library/PackageCache/com.strangeloopgames.runtimegraphicsinfo@d645de19fb6701e9bd19196ed9acbe199802a903/Runtime/RuntimeGraphicsInfo.cs:20)
DebugTuner.Awake () (at Assets/Debug/DebugTuner.cs:31)
```
![image](https://user-images.githubusercontent.com/475445/69315774-62069a80-0c48-11ea-8f8a-590007e04974.png)

2. Need to ensure it doesn't fail for Linux and MacOSX (because it is using DirectX API).

**Comment by redwyre** [comment]
All fixed in updated package, returns -1 for linux/mac or if there is an error
