### ISSUE TITLE
[0.9.0 staging-1262] Icons offset in crafting tables.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13834]
It's very easy to see it with the Carcass icon.
![image](https://user-images.githubusercontent.com/45708377/69326553-0abef500-0c5d-11ea-81cf-5a80ecad0faf.png)

**Comment by Dmittry62** [comment]
I didn't notice any problem with other recepies and since "resepie variations" winodow is no longer available for butchery table there's nothing left for me to do.
