### ISSUE TITLE
[0.9.0 staging-1262] Tagged item icons missing in tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13838]
![image](https://user-images.githubusercontent.com/45708377/69329028-5b385180-0c61-11ea-9eff-d71d6c3ca646.png)
![image](https://user-images.githubusercontent.com/45708377/69329635-82dbe980-0c62-11ea-8d69-25844317be6e.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/75240287-25ad8200-57d5-11ea-8895-55d43239ce1c.png)

**Comment by serpopov** [comment]
I'll take it

**Comment by SlayksWood** [comment]
Seems fixed, but it missing icon in ingredient tooltip. For example tagged and non-tagged:
![image](https://user-images.githubusercontent.com/45708377/79107335-de775280-7d7c-11ea-85b5-802e78abd42d.png)
![image](https://user-images.githubusercontent.com/45708377/79107360-e931e780-7d7c-11ea-8a27-6a059e284e86.png)
Should be icon before Wood tag.
