### ISSUE TITLE
[0.5.5.4] Sometime get stuck on loading world 2%

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#1383]
I'm currently a player at Desmondclarkes's server "Theminingcolony", but I often get stuck on the world loading screen at 2%. After a couple of minutes it throws me out to the server screen again.

**Comment by Neouni** [comment]
I've noticed on servers with a limited upload bandwidth speed it waits a bit at 2%.
Might be related.

**Comment by metachronism** [comment]
believe this was a deadlock issue with 5.5 - 5.6 should have this fixed.
