### ISSUE TITLE
[0.9.0 staging-1262] Audio: Stones fall without sound

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13836]
We've lost a sound for the falling rubbles.

**Comment by WeaselDog** [comment]
Makes a sound again

**Comment by beastyn** [comment]
Its not, what I've expected.
For comparison.
8.3
https://drive.google.com/file/d/1V4NSzex4BACPKwlmWiiwOgDJ-ioDY-5L/view?usp=sharing
9.0
https://drive.google.com/file/d/1sXM_RjmjgiSO6aQa-ZU2vLC81DLChqyV/view?usp=sharing

**Comment by beastyn** [comment]
Nope, still no falling-rolling sound

**Comment by Quadbro** [comment]
yeah, there were some internal missunderstandings on problem, added wwise rubble collision sounds

**Comment by Quadbro** [comment]
currently rubble collide sound is same as pickup rubble one, but it will be replaced by leonard asap
