### ISSUE TITLE
[0,9,0 staging-1262] Incorrect recipe display in tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13843]
It's always display Parent Recipe, so I can't see how can I make this item:
![image](https://user-images.githubusercontent.com/45708377/69335089-2af6b000-0c6d-11ea-8a88-ebdce370209b.png)
![image](https://user-images.githubusercontent.com/45708377/69335106-3a75f900-0c6d-11ea-8599-0abb7d9925f6.png)
From this tooltip I can see from what I can make Raw meat, but I don't know how much i will get.
But sometimes I can see wrong Ingredient. I need 10 Steel Bar for Steel Saw Blade:
![image](https://user-images.githubusercontent.com/45708377/69335243-888afc80-0c6d-11ea-9a85-7b3aa50e7ec0.png)
But tooltip say that I need 10 FerrousBar:
![image](https://user-images.githubusercontent.com/45708377/69335333-c4be5d00-0c6d-11ea-84e9-0a83e144a054.png)
People can confusion.

**Comment by Sekor2600** [comment]
hm yes in the Metalsawblade Parentrecipe is normaly the ironsawbladerecipe too. Both use the FerrousBar Tag for Steel/iron bars.

**Comment by Hakuhonoo** [comment]
Done in https://github.com/StrangeLoopGames/Eco/pull/5499
