### ISSUE TITLE
USER ISSUE: bdxbxbdx

### ISSUE THREAD

**Issue by Klklat** [StrangeLoopGames/EcoIssues#13846]
**Version:** 0.8.1.4 beta

**Steps to Reproduce:**
dbxzb

**Expected behavior:**
xcfghxfh

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.
```

**Comment by SlayksWood** [comment]
Please update to the latest version and reopen if It happens again.
