### ISSUE TITLE
[0.9.0 staging] Civics: Not possible to unclaim property with laws

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13851]
Right now it is not possible to unclaim with laws because there is no "None" option in Change Property Owner effect for the new owner.

![ChangePropertyOwner](https://user-images.githubusercontent.com/47330823/69375194-94ba8e00-0c5c-11ea-813f-bc3342e83db3.png)

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/69464392-17158180-0d33-11ea-982a-432b27c93270.png)
