### ISSUE TITLE
[0.9.0 staging-1266] Trade: can't delete item for bying

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13855]
1. Place store
2. Add something to the buy list
3. Try to delet this item with cross "x"
- Nothing will happen
+ Item should be deleted
![bandicam 2019-11-22 15-39-44-296](https://user-images.githubusercontent.com/27898520/69419827-213d7d00-0d3f-11ea-9548-609b54163d72.jpg)

**Comment by beastyn** [comment]
Seems like its deleting from Sale list

**Comment by SlayksWood** [comment]
Can't use moving/deleting item at all.
![image](https://user-images.githubusercontent.com/45708377/71149565-05df6800-2240-11ea-808b-7f1292944de8.png)
