### ISSUE TITLE
[0.9.0 staging-1266] Bank: names issue

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13854]
1. Open Bank
2. See "Create Title" with plus
! Should see "Create Bank Acount"
![bandicam 2019-11-22 15-22-49-679](https://user-images.githubusercontent.com/27898520/69418183-fa317c00-0d3b-11ea-92a9-04dbf242eca3.jpg)

**Comment by beastyn** [comment]
Nope, still title

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/70078251-332ce480-15b7-11ea-81be-4feccf5c87a0.png)
Says account for me?
