### ISSUE TITLE
[WIN 7] EcoServer Crash on Bootup

### ISSUE THREAD

**Issue by RuddRulez** [StrangeLoopGames/EcoIssues#1385]
--BEGIN DUMP--
Dump Time
04/17/2017 09:00:47

Exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

**Comment by metachronism** [comment]
you need .net 4.6
