### ISSUE TITLE
[0.9.0 staging-1262] Civics notifications: double notifications for laws

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13853]
1. Create a law for taxing after dropping something
![bandicam 2019-11-22 10-44-17-820](https://user-images.githubusercontent.com/27898520/69401331-9ea0c780-0d16-11ea-9060-89e4eea50d3a.jpg)
![bandicam 2019-11-22 10-44-36-274](https://user-images.githubusercontent.com/27898520/69401341-a95b5c80-0d16-11ea-80ed-75fabf816c38.jpg)
2. Drop something
3. Get two notifications about taxing
![bandicam 2019-11-22 10-45-23-760](https://user-images.githubusercontent.com/27898520/69401361-b8420f00-0d16-11ea-8381-94f9f79dd5ce.jpg)
4. But tax was right actually (10 TestClientDollars)
![bandicam 2019-11-22 10-45-35-296](https://user-images.githubusercontent.com/27898520/69401399-d27bed00-0d16-11ea-8ff2-5f138637d260.jpg)

Need to check, where action sends double notification.

**Comment by SlayksWood** [comment]
Still has two notification, but they are different:
![image](https://user-images.githubusercontent.com/45708377/75679048-f0ef6e00-5c9f-11ea-99c8-f19b3f856eec.png)

**Comment by SlayksWood** [comment]
Seems fixed.
