### ISSUE TITLE
[0.9.0 staging-1266] Hewn Logs calories cost between tables

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#13863]
The labor cost of Hewn Logs at a Workbench is 20, and the labor cost of Hewn Logs  at the Carpentry Table is 130.

Not sure if intentional, but it does make Hewing very hard to level up for a new player, making Hewn Logs at a Workbench cost more logs, but cost so much less labor.

**Comment by WeaselDog** [comment]
Looks good. Both at 20 now.
