### ISSUE TITLE
Not able to craft "standart" hewn logs.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13869]
1) place workbench and stockpile, place cedar log into stockpile.
2) open advanced hewn log crafting, select "hewn log"
![изображение](https://user-images.githubusercontent.com/4980243/69497480-871c3700-0eee-11ea-8225-9445ec188ed9.png)
3) click craft...
![изображение](https://user-images.githubusercontent.com/4980243/69497492-9ac79d80-0eee-11ea-8d79-5be865b23ae5.png)

aaand... you receive "softwood hewn log"
![изображение](https://user-images.githubusercontent.com/4980243/69497498-b16df480-0eee-11ea-8d8e-ee8195ac5858.png)

Maybe other tagged recipes have same issue too.

**Comment by Sekor2600** [comment]
the Problem is that the Recipe has 3 Tags. Softwood, Hardwood & Logs. the Recipe use Soft or hard always to the right Block. 
Use the old logs an you craft Hewnlog. Maybe Split the Recipe @craig-jong ?

**Comment by elfl0rd** [comment]
In my opinion, when choosing a specific recipe, the chosen result should be crafted.
Otherwise, the behavior is not logical.

Separation of recipes, what wanted to avoid when introducing this system.

**Comment by elfl0rd** [comment]
Also maybe refers to this issue - https://github.com/StrangeLoopGames/EcoIssues/issues/13360

**Comment by craig-jong** [comment]
Yea, choosing a specific should lock it to the that recipe. I'll fix this.
