### ISSUE TITLE
[0.9.0 staging - 1266] Notifications get transferred between servers 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13861]
I have been using my own builds created in Unity. Today I switched to the staging server using a different client & server. My notifications from my private game are included in the notifications for this public game:

![WrongNotifications](https://user-images.githubusercontent.com/47330823/69482803-b474c200-0dd4-11ea-9174-87662a2d31d8.png)

**Comment by beastyn** [comment]
dup #13716
