### ISSUE TITLE
[staging] Civics: Missing math operators on laws

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13860]
Most of the math operators are missing from conditions and effects. They are needed for a variety of reasons, usually whenever percent is needed. 

If we want to tax people for creating tailings, currently we can only tax them 1 each. We would need a product of the Item Count to tax them a set amount per tailing:
![MissingMathOperators](https://user-images.githubusercontent.com/47330823/69474424-dab74500-0d75-11ea-9181-1d2ec4990e25.png)

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/69484067-b5612000-0de3-11ea-8e6b-9c5168c6a3dc.png)

**Comment by WeaselDog** [comment]
Nice
