### ISSUE TITLE
[0.9.0 staging-1266] World Object size does not match tooltip description

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13864]
Edit: This issue applies to anything with an offset. It calculates the tooltip info from a combination of the occupancy offset & size. It should just calculate the size.

The capitol size appears to be 3x3x4 (X,Z,Y). The tooltip says it is 3x1x3:
![CapitolTooptip](https://user-images.githubusercontent.com/47330823/69484575-96fe2300-0de9-11ea-877f-838a965f455a.png)

**Comment by beastyn** [comment]
Its 2x2x3 now, Why?
Looks like 4x3x3
![bandicam 2019-11-28 16-23-12-286](https://user-images.githubusercontent.com/27898520/69802512-8f7cb680-11fb-11ea-80eb-6dfa620a2b9a.jpg)

**Comment by WeaselDog** [comment]
Court also has issue:
![CourtTooltip](https://user-images.githubusercontent.com/47330823/70382161-d52c3400-190b-11ea-8ee0-b7099a098185.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/73506440-71157180-438a-11ea-82ca-7496baec56f6.png)
The court occupancy and such were fixed a while ago, but the tooltip is broken. Un-assigning myself, I'm not sure where this would be fixed but perhaps it's in the tech tree?

**Comment by WeaselDog** [comment]
@johnkslg I need to pass this one off. 

It is an issue with how the dimensions are calculated in WorldObjectItem.cs. in the ToolTipSection.

**Comment by WeaselDog** [comment]
The source of this issue the interaction between object occupancy and occupancy offset. It subtracts the offset from the occupancy which is used to calculate the tooltip.

**Comment by SlayksWood** [comment]
Calculation fixed, but we have some items with wrong occupancy. Like #15006
Closed.
