### ISSUE TITLE
Trees dont fell after cutting them down.

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1386]
http://ecoforum.strangeloopgames.com/topic/2238/5-5-4-my-know-bugs

I have seen also a video and other reports about this .. Though i cant sadly find it on the forums anymore

**Comment by craig-jong** [comment]
Does this mean that the tree doesn't fall or isn't cut at all?

I could use a bit of clarification on this issue.

**Comment by MarjieAVolk** [comment]
I think this is the same as StrangeLoopGames/EcoIssues#1452
