### ISSUE TITLE
[8.3.0] Logging out in a car will catapult you to space when you login back

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13871]
Enter car, leave the server. Join the server. Have a good ride to moon.

**Comment by beastyn** [comment]
Can't repro in 0.9. Can you check for 0.9?

**Comment by elfl0rd** [comment]
tested.

spaaaaaaaaaaaace
![20191125185909_1](https://user-images.githubusercontent.com/4980243/69556421-b6e24200-0fb5-11ea-86b1-a650e3def08b.jpg)

You need move\rotate your vehicle, or stay over ramp.

**Comment by beastyn** [comment]
still have it after client launching.
https://drive.google.com/file/d/14Tc0iRl8mJqXKYPLooVbLON_hh7NvxYC/view?usp=sharing

**Comment by mirasrael** [comment]
@beastyn I see you logged out on the garbage block. Do you have same issue when log out without vehicle overlapping with other objects?

**Comment by beastyn** [comment]
Nope, can happen on clear snd too

**Comment by beastyn** [comment]
Fine for me now. Reopen if meet again.
