### ISSUE TITLE
Translation work, part 24.11.2019

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13873]
No string for "Current Bank Accounts"
![изображение](https://user-images.githubusercontent.com/4980243/69499743-9313f300-0f06-11ea-8260-26ff0f2c16d7.png)

Typo? Too many spaces - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#166484
![изображение](https://user-images.githubusercontent.com/4980243/69499801-0ddd0e00-0f07-11ea-8157-d759f7c40fb6.png)

Ecopedia, how tags works?
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#166484 this way? `"text"[string]`
Or this https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#166488 `"[string]"`

**Comment by SlayksWood** [comment]
This strings were remoced and many spaces were fixed.
