### ISSUE TITLE
[0.9.0 staging-1270] Economy viewer: hard to watch acoount tooltips

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13877]
Its pretty hard to look at you accounts' tooltips.
Sometimes it appears, sometimes does not.
![bee821dcea988cd8e7e44a7aecbe55bc](https://user-images.githubusercontent.com/27898520/69534347-6958db80-0f9b-11ea-853d-2f1323c98ff0.gif)

**Comment by SlayksWood** [comment]
Seems fixed.
