### ISSUE TITLE
[0.9.0 staging-1270] Biome(generation): something strange with wetland or trees

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13879]
So, we have a world for playtest.
I've choosen rainforest for settlement.
But on the next day of playtest I couldn't find trees.
Seems like they all were dead, because it was not only rainforest but wetland too.
I don't feel its right. Can we balance it somehow?
![bandicam 2019-11-22 17-05-24-561](https://user-images.githubusercontent.com/27898520/69542675-c9587d80-0fad-11ea-8721-5b62ec7540f5.jpg)
![bandicam 2019-11-22 17-06-35-738](https://user-images.githubusercontent.com/27898520/69542676-ca89aa80-0fad-11ea-9790-f5a19db06a56.jpg)
![bandicam 2019-11-22 17-04-56-059](https://user-images.githubusercontent.com/27898520/69542686-d07f8b80-0fad-11ea-832f-60a3f0cd649c.jpg)

**Comment by elfl0rd** [comment]
I got all trees disappear in my world, looks like "geberic" problem, not biome.
But new saplings are appear...

[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3891161/Storage.zip)
![20191126125353_1](https://user-images.githubusercontent.com/4980243/69619054-02dfc600-104c-11ea-935f-d8e6ee3d780b.jpg)

**Comment by beastyn** [comment]
some sdditions here #14056

**Comment by elfl0rd** [comment]
Yield potential for all trees...
![20191212110834_1](https://user-images.githubusercontent.com/4980243/70694100-dd9bba80-1ccf-11ea-9bbc-9cc910f07d4d.jpg)
![20191212110840_1](https://user-images.githubusercontent.com/4980243/70694101-de345100-1ccf-11ea-9dc9-190e0e6ad4e1.jpg)
Etc...

**Comment by SlayksWood** [comment]
Yield potential was remove to separate issue
