### ISSUE TITLE
Ladders ! 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1388]
Ladders is a feature that is requested over and over again =P

**Comment by lightdrawn** [comment]
The ladder of the Blast Furnace is already working in 0.7.3.3, wonderful. :D

**Comment by elfl0rd** [comment]
as model, not as climbable ladder.

**Comment by lightdrawn** [comment]
Okay, not climbable like in Minecraft, but almost, you jump and stand on the ladder steps. :)

**Comment by elfl0rd** [comment]
And crane have ladder but they not working @johnkslg

**Comment by D3nnis3n** [comment]
Ladders have been added to the game in 7.8.
