### ISSUE TITLE
0.9 Ugly chest placement preview

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13882]
![20191125194016_1](https://user-images.githubusercontent.com/4980243/69559796-a92fbb00-0fbb-11ea-85dc-7cafe0194609.jpg)

**Comment by beastyn** [comment]
Can be related to the current shadowplacement problem #13763

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/70481071-c008fe00-1ae1-11ea-9fb1-e08100483524.png)
Think it has something to do with the LOD system
![grafik](https://user-images.githubusercontent.com/37456949/70481128-e75fcb00-1ae1-11ea-9455-7f65622afd2e.png)

**Comment by elfl0rd** [comment]
Also some objects have problem with layers at middle distance.
~5 claim
![изображение](https://user-images.githubusercontent.com/4980243/74275047-3c0f0480-4d24-11ea-8795-b102cf5499ee.png)

**Comment by mirasrael** [comment]
Original issue fixed. Wasn't able to reproduce issue with layers at middle distance, probably this issue was already fixed. If it still happens then please create separate issue, because original issue was fixed.
