### ISSUE TITLE
Existing deed search distance is too big 

### ISSUE THREAD

**Issue by olegshegai** [StrangeLoopGames/EcoIssues#13886]
A plot being claimed will attach to an existing deed even if there is a gap between them.
**[Here](https://drive.google.com/open?id=1WVtcZuNul-LtBt-oPkCfx0xwglkm4Cmx)** is a video.

**Comment by beastyn** [comment]
Im not sure if we want to change this. Its intended to save deed if its less that two plots between.
@johnkslg can you look at this one?

**Comment by johnkslg** [comment]
Yeah it's meant to pick something relatively close.

**Comment by elfl0rd** [comment]
I prefer modifier, like "hold ctrl to create new deed".
If possible.
Creating marketplace with deed's trading is annoying.

**Comment by beastyn** [comment]
Its just ga,eplaying perfection. Thank you. I mean it.
Can we add modification descriptions when looking on a claim? Like one from stockpile and labor hints (hint is changing when modificator is pressed).
 ![bandicam 2020-01-15 12-32-56-556](https://user-images.githubusercontent.com/27898520/72414317-bbe09800-3793-11ea-9bbc-16405e43d443.jpg)
Wicth ctrl pressed
![bandicam 2020-01-15 12-36-43-575](https://user-images.githubusercontent.com/27898520/72414322-c26f0f80-3793-11ea-9e12-d16666eb4776.jpg)
