### ISSUE TITLE
[0.9.0 staging-1271] Craft: canceled work order icon

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13889]
If work order was cancelled (but wasn't removed as there is no place for resources) we need to mark icon as Cancel (Removed) maybe with yellowish blinking alpha (like for invalid orders).
![bandicam 2019-11-26 14-11-03-709](https://user-images.githubusercontent.com/27898520/69615983-a387b300-1057-11ea-8202-a9a9431c911c.jpg)

**Comment by SlayksWood** [comment]
merged to #14702
