### ISSUE TITLE
[0.9.0 staging-1270] Civics: can't use district in a law

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13880]
Did I miss something?
1. Create a map with a district and pass it in the election (Public Store)
![bandicam 2019-11-25 19-11-23-854](https://user-images.githubusercontent.com/27898520/69547996-56a0cf80-0fb8-11ea-8439-4070e2c230b7.jpg)
2. Try to create a law where I will check if an action is on the district
But District has an error
![bandicam 2019-11-25 19-12-11-033](https://user-images.githubusercontent.com/27898520/69548198-b7300c80-0fb8-11ea-853d-f939eca12b35.jpg)

**Comment by WeaselDog** [comment]
I have same error.  Districts used to work in laws.

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/69585970-07e23e00-0f96-11ea-8652-deab85bc6674.png)

Also fixed SpawnGov which was making invalid districts
