### ISSUE TITLE
Districts are sent as expensive array of BSONValues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13892]
![image](https://user-images.githubusercontent.com/3536496/69667214-6bc24080-1042-11ea-9108-59066f930bb5.png)
They need to be sent like world layers and other 2d arrays, as a block of bytes.

**Comment by mirasrael** [comment]
After compression:
![image](https://user-images.githubusercontent.com/475445/69822387-463a6000-1217-11ea-83fe-9519ad4e0690.png)
