### ISSUE TITLE
[0.9.0 staging-1274] Can't load the world (old save or new generated)

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13899]
1. Generate New World
2. Try to login

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0()</size>

**Comment by D3nnis3n** [comment]
Haven't seen a critical issue for a year lol.
