### ISSUE TITLE
[9.0] Joining Server exception 

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#13896]
You can join the Server only in Debug Mode. In the Release Mode you have a Server exception when you would like to join.

Message:Object reference not set to an instance of an object.
Source:Eco.Plugins

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.Client.Update() in J:\Eco-Github\Server\Eco.Plugins\Networking\Client.cs:line 349
   at Eco.Plugins.Networking.Client.<.ctor>b__61_0() in J:\Eco-Github\Server\Eco.Plugins\Networking\Client.cs:line 97
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String) (at Assets/Scripts/Networking/NetworkManager.cs:135)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
Eco.Networking.ENet.ENetUdpPeer:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleDisconnect(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
Eco.Shared.Networking.NetworkClient:Service(Int32)
ServiceJob:Execute() (at Assets/Scripts/Networking/NetworkManager.cs:578)
Unity.Jobs.JobStruct`1:Execute(ServiceJob&, IntPtr, IntPtr, JobRanges&, Int32) (at C:/buildslave/unity/build/Runtime/Jobs/Managed/IJob.cs:30)

**Comment by WeaselDog** [comment]
When I first did the build I had the same issue. After running in Visual Studio debug mode, it did some migrations and my .exe worked fine & can rebuild without issue.
