### ISSUE TITLE
Server crash on startup at ModKit

### ISSUE THREAD

**Issue by DanHCraft** [StrangeLoopGames/EcoIssues#13898]
As I wrote in the title the server crashes on startup.
Important to know is that the server run on Linux. I know it is not official supported, but I don't know how to fix it.

Console Output: https://gist.github.com/DanHCraft/b4e5aa823423e2f865fde0adab7dfcf8
OS: Linux Debian 9.11 amd64
Mono: 6.4.0.198 (mono-complete)
Start-Command:
```
mono EcoServer.exe -nogui
```

**Comment by redwyre** [comment]
Mono 6 isn't supported. How did you install it?

**Comment by D3nnis3n** [comment]
Not an issue either, as mono is no longer required on the next version.
You can go on trying to fix the issue for now in this issue, but i'll close it.
