### ISSUE TITLE
[0.9.0 staging] Chat: Sales result message is backwards

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13907]
When selling an item at a store, the result message is backwards. This is only a chat issue, the currency is exchanged correctly.

![SellMessage](https://user-images.githubusercontent.com/47330823/69745653-7a1e6400-10f7-11ea-92b2-b181efd76e0c.png)

**Comment by SlayksWood** [comment]
can't check. Need check after #14091 fixes.
