### ISSUE TITLE
0.9 "sit" is difficult to target for chair\bench.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13906]
![изображение](https://user-images.githubusercontent.com/4980243/69743265-36574900-114f-11ea-91dc-769dd560c705.png)

**Comment by keegan-o** [comment]
Padded Chair I can get to more or less work and be tweakable--
it's .cs file looks like this:
![image](https://user-images.githubusercontent.com/14983165/70097812-1b695680-15df-11ea-8fa9-a0bf8b3edbe5.png)

CompositeLumberChair, meanwhile, when I remove the collider for basic interaction, the sit collider still just opens the world object UI. The prefabs are setup the exact same way, so it's something in the tech tree I think @craig-jong.

For comparison CompositeLumberChair looks like this:
![image](https://user-images.githubusercontent.com/14983165/70097868-43f15080-15df-11ea-91d0-48fecc617f6d.png)

**Comment by Sekor2600** [comment]
Reopen it because the Sit is difficult to target.
