### ISSUE TITLE
[0.9.0 staging-1273] Civics: need fix for spammy tax notification

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13902]
Need fix similar to #12122
List of taxed people looks fine but after that you will see notification about everyone who was taxed.
It can be quite spammy for the big srevers.
![bandicam 2019-11-27 16-55-18-593](https://user-images.githubusercontent.com/27898520/69721899-aa85f280-1137-11ea-9318-c398315757d6.jpg)

**Comment by WeaselDog** [comment]
Similar to other issue, this is just an issue for laws based on a timer. Executive actions work great and it it is what timer laws should look like when using "Repeat For Each User"

Here is view of executive action:
![ExecutiveActionTax](https://user-images.githubusercontent.com/47330823/69730134-61548500-10dc-11ea-9385-217d7c19c74c.png)

**Comment by SlayksWood** [comment]
still spam in top notification chat:
![image](https://user-images.githubusercontent.com/45708377/79718468-cf485580-82e4-11ea-9926-08d9b7dcea18.png)

**Comment by SlayksWood** [comment]
still spam if you create executive action and players don't have enough money:
![image](https://user-images.githubusercontent.com/45708377/79718784-8fce3900-82e5-11ea-9201-1f595c31f9b5.png)

**Comment by olegshegai** [comment]
![image](https://user-images.githubusercontent.com/56091594/79768444-77850b00-8333-11ea-92cf-64b64c7dfc52.png)
Can't reproduce

**Comment by olegshegai** [comment]
Top-bar situation fixed

**Comment by SlayksWood** [comment]
If you create executive action by "Action to run once" then it'll spam.
- create executive acction like:
![image](https://user-images.githubusercontent.com/45708377/79970874-41af6600-849c-11ea-9e11-0d382946237b.png)
- /civics winelection:
![image](https://user-images.githubusercontent.com/45708377/79970921-54c23600-849c-11ea-8b06-21fbf78541b6.png)

But if you create executive action like:
![image](https://user-images.githubusercontent.com/45708377/79970996-6d325080-849c-11ea-92f9-89efac5e9200.png)
It will work fine:
![image](https://user-images.githubusercontent.com/45708377/79971044-7c190300-849c-11ea-9a1c-c5e511072ddf.png)
