### ISSUE TITLE
0.9 (same as 0.8) main menu mirror after failed connection

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13900]
![20191127124011_1](https://user-images.githubusercontent.com/4980243/69712038-2d488680-1113-11ea-879a-f0dcd2563fe8.jpg)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/75314624-54793600-5871-11ea-873a-bffbc3a20ce1.png)

**Comment by SlayksWood** [comment]
Now I move to main menu after Failed Connection. I need to open Your world or browser again:
![image](https://user-images.githubusercontent.com/45708377/75324107-3dddd980-5887-11ea-803c-42bfb9b78651.png)
Can this be easily changed so that the last menu opens? If it's hard to change close it.

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/77308831-9e3c2b80-6d0c-11ea-8055-91f77bdfa5e5.png)
