### ISSUE TITLE
Clickable lInks

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#1390]
Make it possible for links to be shared and be clickable and open automatically in the user's browser, for security reasons you may add the following functionality.

CTRL + Shift + Click will auto open the link
CTRL + Click will open a confirmation dialog box which the user must click open link

**Comment by MarjieAVolk** [comment]
To clarify, you want to be able to share URLs in the chat, and let people open them by clicking instead of having to copy and paste?

**Comment by ClayC90** [comment]
copy and paste is not even possible right now unless they have the chat window open, and yes, clickable links ;)

**Comment by MarjieAVolk** [comment]
Another related problem is sometimes people need to copy paste their ids from /whoami

**Comment by ClayC90** [comment]
/whoami should automatically save the id to clipboard for the player to paste where ever they need.

**Comment by WeaselDog** [comment]
This is a great idea, but it could potentially create problems with people sending links in a public server. The host has the option now to add links via the Ecopedia.
