### ISSUE TITLE
[0.9.0 staging-1273] Missed icons

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13904]
Bed on tab
Civics actions in Governmant office, Ballot
Real Estate Desk - My Deeds

**Comment by beastyn** [comment]
bed is still empty
![bandicam 2019-12-05 11-21-08-459](https://user-images.githubusercontent.com/27898520/70209218-77ec8300-1751-11ea-9ba0-9f247a45eb4f.jpg)

**Comment by elfl0rd** [comment]
Pipes tab
![изображение](https://user-images.githubusercontent.com/4980243/70259983-68e0f180-17a0-11ea-88aa-7912944d7d5b.png)

Pump tab
![изображение](https://user-images.githubusercontent.com/4980243/70259999-71d1c300-17a0-11ea-8964-0ea8dcb4bbb7.png)
(it's really needed for?)

Power (electric?)
![изображение](https://user-images.githubusercontent.com/4980243/70259461-48646780-179f-11ea-98a0-71d1a29a03da.png)

**Comment by SlayksWood** [comment]
Seems fixed, but I'll continue to check this.

**Comment by elfl0rd** [comment]
(vehicle) Modules tab still not have icon
![изображение](https://user-images.githubusercontent.com/4980243/79117381-a4fe1180-7d93-11ea-9896-c6c1e5155e7f.png)
