### ISSUE TITLE
Improve performance such that this review wouldnt happen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13908]
https://steamcommunity.com/id/asafteirobert/recommended/382310/

From Dennis, top perf issues
- Memoryleak (FPS drops in an hour to near-zero while ram filling up, restart required)
- Big Citites / Many objects (Persistent very low fps so people try to stay out of cities)
- Server lags due to database (The more laws and economy is used, the more players on it, the more often you see the cool connection sign, and on profiling mirasrael ever found db as issue, lol)

Follow up with this user on Discord, see if he will verify fixes. 

I'm ok with delaying 9.0 until performance is improved

**Comment by johnkslg** [comment]
From Twinsen
![image](https://user-images.githubusercontent.com/3536496/69826424-e5d00200-11c7-11ea-93dd-791a60af5c62.png)

**Comment by johnkslg** [comment]
His specs
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3902763/DxDiag.txt)

**Comment by BartBruininks** [comment]
I have a similar issue with degrading performance over time. The weird thing is that my friend who has almost the same computer build as me seems to be doing fine. Specs can be uploaded if extra info is needed but all are AMD  Ryzen 5 + NVIDIA 2070GTX + 16 GB RAM (friend has 8  GB) and isntalled on SSD via sata. My game starts to lag way before I run out of memory. I go from 60 fps to 15 fps mainly during traveling it seems.

Game version 8.3.0

**Comment by BartBruininks** [comment]
After checking out what is causing it, it appears graphical settings have minor influence, however, opening a workbench/device (and storage?) results in long term heavy fps loss (65 --> 25-30, dipping to <10). This seems to restore after idling for a long amount of time (1-5 minutes). I hope this will help finding the issue.

Cheers

**Comment by BartBruininks** [comment]
Performance is also still steadily declining over time for me, what is causing this is unclear to me.

**Comment by johnkslg** [comment]
Here's a migrated large world for testing 
https://drive.google.com/file/d/1Nclb5OeSvWxEnAaaHvd-kLv5U7G0E7Lc/view?usp=sharing
@redwyre

**Comment by johnkslg** [comment]
Thanks for the notes @BartBruininks !

**Comment by elfl0rd** [comment]
so, empty world in latest 8.
~120 fps
same settings, fresh generated empty world in latest BE 9
~ 20 fps

**Comment by elfl0rd** [comment]
As i see, max performance inpact from level of detail.

**Comment by johnkslg** [comment]
Removing this bug as we have more specific ones now.
