### ISSUE TITLE
0.9 animation play every time when you reselect project

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13910]
![demo](https://user-images.githubusercontent.com/4980243/69775182-0e94cf00-11a9-11ea-83a0-6eda546ec907.gif)

**Comment by beastyn** [comment]
Talk about design part with Milenko.
Its quite annoying with this animation.

**Comment by johnkslg** [comment]
Just removed the animation, its not needed.
