### ISSUE TITLE
Habituation with food

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13918]
As you can see, many servers do not use all the variety of food.
Only 2-3 kinds of food are created at each level.
For example, Simmered meat+Basic salad at adv. cooking.

I suggest adding a divider to the food experience formula. Which starts to work if you have already eaten a lot of such food and which cuts off the experience you get. The farther - the more.

As a result, all food becomes popular and cooking will become more diverse.

@D3nnis3n @craig-jong

**Comment by johnkslg** [comment]
Adding this! https://github.com/StrangeLoopGames/EcoIssues/issues/16851
