### ISSUE TITLE
0.9 hard to read "resources" and "labor" if your time bar filled.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13911]
e.g.
![изображение](https://user-images.githubusercontent.com/4980243/69775329-7a773780-11a9-11ea-83a4-61282055aae0.png)

Maybe 3 different bar better instead of combination?

**Comment by beastyn** [comment]
@Hakuhonoo Need to talk about it with Milenko.
John  has aked to review this design

**Comment by elfl0rd** [comment]
Also with https://github.com/StrangeLoopGames/EcoIssues/issues/13910 this UI section looks ugly in general =|

**Comment by Hakuhonoo** [comment]
@MilenkoTunjic Could you make new design for this bar?

**Comment by mirasrael** [comment]
We are going to remake this UI, so can live with this for now.
