### ISSUE TITLE
[0.9.0 staging-1277] Runtests: checking contract tests

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13924]
Can you please checj this error?
Launch /qa runtests from the client
![bandicam 2019-11-28 18-23-02-873](https://user-images.githubusercontent.com/27898520/69809729-2487ab80-120c-11ea-8c26-3f4fd1e37fad.jpg)

**Comment by SlayksWood** [comment]
still an issue.
![unknown (5)](https://user-images.githubusercontent.com/45708377/70893419-1dc6aa00-1ffc-11ea-83b8-c78807607199.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/71397040-4ae31000-262d-11ea-9b50-e3a91ac5956f.png)

**Comment by olegshegai** [comment]
`/civics testgameactions` fixed, for other tests we can proceed to https://github.com/StrangeLoopGames/EcoIssues/issues/14205

**Comment by beastyn** [comment]
I have exception with /civics testgameactions
![bandicam 2020-01-14 11-50-03-874](https://user-images.githubusercontent.com/27898520/72320691-0b579300-36c4-11ea-9a87-5a858e1e9a3c.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/72876256-21d69d80-3d07-11ea-971d-c2392b561ce0.png)

**Comment by beastyn** [comment]
This time everything was great, but server has crashed at the end
```
--BEGIN DUMP--
Dump Time
01/29/2020 15:51:09

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--
```
[AutomatedRESULTSONLYTestReport.log](https://github.com/StrangeLoopGames/EcoIssues/files/4127545/AutomatedRESULTSONLYTestReport.log)
[AutomatedFULLTestReport.log](https://github.com/StrangeLoopGames/EcoIssues/files/4127546/AutomatedFULLTestReport.log)

**Comment by SlayksWood** [comment]
Don't have it anymore.
![image](https://user-images.githubusercontent.com/45708377/96115084-1bb8ca80-0eef-11eb-8fbc-6ec0ef0aa895.png)
