### ISSUE TITLE
[0.9.0 staging] UI: Unable to forgive or repay debt for loans

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13927]
In the Economy Viewer the Forgive button does not work. The forgive button also appears to the borrower so they cannot repay. For both it shows the default string with Joe Bucks.

![RepayUI](https://user-images.githubusercontent.com/47330823/69842833-a8946000-1219-11ea-8ab1-e8889bdc32e3.png)

**Comment by beastyn** [comment]
@WeaselDog thank you for help. )
Can you provide a save?
Its pretty hard to catch this issue.
Also do you have some other UI btoken? Maybe store or ItemName in item placements?

**Comment by WeaselDog** [comment]
@beastyn It is just since this morning that loans work again. I can replicate it 100% of time. I am happy to upload a save though.

**Comment by beastyn** [comment]
No, I think it fine them. Will check with the new build anyways. Thanks.

**Comment by beastyn** [comment]
Also bank list is broken too
![bandicam 2019-11-29 11-45-39-728](https://user-images.githubusercontent.com/27898520/69851906-b0e5ad00-12a4-11ea-94e7-6b2897c12fe3.jpg)

**Comment by olegshegai** [comment]
@serpopov Will you take it since it's in an Economy Viewer?

**Comment by beastyn** [comment]
It happens after accepting Loan Contract

**Comment by beastyn** [comment]
Still here after second person has taken a loan contract
![bandicam 2019-12-12 14-29-41-369](https://user-images.githubusercontent.com/27898520/70700027-dd111d00-1ceb-11ea-8265-1db445122c01.jpg)

**Comment by olegshegai** [comment]
My changes were overridden by some other PR, should be okay now (repeated it here: https://github.com/StrangeLoopGames/Eco/pull/5359)

**Comment by WeaselDog** [comment]
Tested with repaying & forgiving for loans and bonds and it works nice now.
![CompletedLoans](https://user-images.githubusercontent.com/47330823/70865535-9f8ed880-1f13-11ea-9a73-25c10b27c48c.png)
