### ISSUE TITLE
[0.9.0 staging-1278] UI: bring back contract's UI from Economy Viewer

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13937]
In 8.3 contract's UI was available from Economy Viewer from any part by name clicking.
![bandicam 2019-11-29 16-07-24-075](https://user-images.githubusercontent.com/27898520/69865784-02516480-12c4-11ea-8652-4fb38a8f3941.jpg)

Bring it back, please

**Comment by WeaselDog** [comment]
For the contract list in the Economy Viewer, the pointer changes to the click icon when you hover over the contract symbol but clicking the symbol does not bring up the contract.

![ContractUI](https://user-images.githubusercontent.com/47330823/70354467-7049de80-1824-11ea-9478-37842411e5af.png)

**Comment by beastyn** [comment]
They have dissaperaed
Again
![bandicam 2020-02-05 13-27-57-636](https://user-images.githubusercontent.com/27898520/73824156-7e63ad80-481b-11ea-9591-ff1d06838768.jpg)
![bandicam 2020-02-05 13-28-02-237](https://user-images.githubusercontent.com/27898520/73824195-8de2f680-481b-11ea-8626-151e976bfc8a.jpg)

**Comment by serpopov** [comment]
also fixed distance button
