### ISSUE TITLE
[0.9.0 staging-1278] UI: messy contracts

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13935]
We should use one style for selection, fileds, fonts etc
![bandicam 2019-11-29 12-07-22-884](https://user-images.githubusercontent.com/27898520/69850449-1899f900-12a1-11ea-8e92-8709a4381b19.jpg)

**Comment by D3nnis3n** [comment]
And i actually prefer the Font used at Bank Account. 😊
