### ISSUE TITLE
[0.9.0 staging-1278] UI: changing name glitch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13931]
I was changing the name for my property

I was typing a lot of "T" in the end, but couldn't see them in the field.

They have appeared after saving the name.

![bandicam 2019-11-29 11-37-17-004](https://user-images.githubusercontent.com/27898520/69848823-e71f2e80-129c-11ea-9ae0-2f60f52b74ef.jpg)
![bandicam 2019-11-29 11-37-42-077](https://user-images.githubusercontent.com/27898520/69848829-e8e8f200-129c-11ea-9674-57188d5da074.jpg)

**Comment by beastyn** [comment]
Don't you think 20 symbols is too less?
@johnkslg do we have aby standarts for names length?
I think for German, for exampleб its too short.

**Comment by serpopov** [comment]
Removed text decoration for this window
