### ISSUE TITLE
0.9 currency report subwindow opens up smaller than the minimum size

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13948]
Fresh opened
![изображение](https://user-images.githubusercontent.com/4980243/69895510-310e2000-1342-11ea-9243-057e521fee80.png)
Min size (while resize)
![изображение](https://user-images.githubusercontent.com/4980243/69895512-3ff4d280-1342-11ea-8042-40acd664b18a.png)

**Comment by beastyn** [comment]
should be fixed with this #13271
