### ISSUE TITLE
0.9 strange position for crafting party remove icon.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13946]
Maybe (1) is better?
![изображение](https://user-images.githubusercontent.com/4980243/69895371-2900b100-133f-11ea-84af-059250e20be0.png)

**Comment by beastyn** [comment]
Also in al thel intefaces with new style we need to check this trash cans (in all civics objects, for example)

**Comment by SlayksWood** [comment]
Seems fixed for work party:
![image](https://user-images.githubusercontent.com/45708377/75679535-de296900-5ca0-11ea-9515-5d70b2835928.png)
