### ISSUE TITLE
0.9 Glass plates is not merge

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13940]
![20191129184158_1](https://user-images.githubusercontent.com/4980243/69879255-07201380-12d8-11ea-95ee-0dc81e3d63c3.jpg)

**Comment by redwyre** [comment]
@keegan-o this will be a side effect of the changes I made to the face remover, the edges aren't getting removed between panes.

**Comment by keegan-o** [comment]
This is something that if I want to fix via the builder, I will have to dramatically increase complexity in the builder and add in a lot of new meshes.

**Comment by keegan-o** [comment]
I think perhaps the easier solution will be simply making the meshes thicker and seeing if the face remover can work on those, instead.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/c214e56c-50ac-422c-ba8a-656ee136982b)

Guess that did not do it....

**Comment by keegan-o** [comment]
I made geometry on the edges match perfectly with an X on each edge, still no dice.

**Comment by keegan-o** [comment]
@redwyre I updated develop SVN with new meshes and a material I think works better, with the matching geo- the problem is still there. If it's something I have to fix via rules/builders, that sucks, but let me know if so.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/96220230-04cab480-0f91-11eb-9bc7-797ae42e031e.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/96500885-66df2000-1204-11eb-9b72-57d72db8236e.png)
Alas, the old behavior is back on the face remover (though, I'm sure it's more performant this way :( )

**Comment by IcedForge** [comment]
Seems like it has caused some weird side effects, this bar line happens every 10 tiles and follow claim borders by a factor of 2 ( not related to 0 line
![Screenshot_29](https://user-images.githubusercontent.com/24981362/97284860-d75bf180-1841-11eb-969a-0073b723ee84.jpg)

The glass looks a bit odd and is very visible when its dark / night time where it has some weird texture lines on top of it.
![Screenshot_25](https://user-images.githubusercontent.com/24981362/97284991-fce8fb00-1841-11eb-8eb6-d66afc751aab.jpg)

**Comment by redwyre** [comment]
I dunno what the littlec crosses are, perhaps @keegan-o has an idea
the black strips is likely https://github.com/StrangeLoopGames/EcoIssues/issues/18617

**Comment by WeaselDog** [comment]
The reopen will be dealt with in issue @redwyre linked.
