### ISSUE TITLE
0.9 Broken windows. vol2

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13944]
deed color picker
![изображение](https://user-images.githubusercontent.com/4980243/69895275-a88d8080-133d-11ea-9b4f-0dd7f3c8b471.png)

talent selection
![изображение](https://user-images.githubusercontent.com/4980243/69897390-89521b80-135c-11ea-84a5-3e4f23c8854e.png)

**Comment by SlayksWood** [comment]
Change text to DeedName color.
![image](https://user-images.githubusercontent.com/45708377/70602780-3d2d9380-1c06-11ea-8e1c-d1f20e8943c3.png)
