### ISSUE TITLE
0.9 item name under ecopedia button

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13949]
As i think, if item name are long, hint should be resized to add space for ecopedia button.
![изображение](https://user-images.githubusercontent.com/4980243/69895596-6287eb00-1344-11ea-8649-16d34b8cfda9.png)
![изображение](https://user-images.githubusercontent.com/4980243/69895612-c7434580-1344-11ea-8df6-0600920d260c.png)

**Comment by beastyn** [comment]
did we decide to remove help from the tooltip?
![bandicam 2020-02-10 14-45-46-076](https://user-images.githubusercontent.com/27898520/74138875-2b6f6900-4c14-11ea-9ab8-cb4b21bb6201.jpg)
