### ISSUE TITLE
0.9 strange "red" error marker for projects.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13945]
![изображение](https://user-images.githubusercontent.com/4980243/69895362-f5be2200-133e-11ea-9a82-78da2f4cdbf9.png)

**Comment by elfl0rd** [comment]
Same in workbench
![изображение](https://user-images.githubusercontent.com/4980243/69895456-d922e980-1340-11ea-9763-99984aa2885c.png)

**Comment by beastyn** [comment]
dup #13925
Will add table icon there
