### ISSUE TITLE
cant connect to specifik server

### ISSUE THREAD

**Issue by mossytiger** [StrangeLoopGames/EcoIssues#13959]
having my one pc not able to connect to a specific server (85.10.231.142:3010) tried different internet providing and got no issue with any other pc. tried reinstalling game and a second time with wiping all files related to eco still having this issue i got no issue with any  other server only this specific one

<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2070 SUPER (ID=0x1e84)
    Vendor:   
    VRAM:     8011 MB
    Driver:   26.21.14.3630
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.430100 ms
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 275)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 275)

Logging in as 76561198011082840 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NTEzMDA0NywidnhhIjoibG9naW4iLCJ2eGkiOjE0NzU2NCwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTEwODI4NDAuQG10MXAudml2b3guY29tIn0.PZ2tL-g9HYSX1srvhuUPFf9ChSDnYWsx5hUZvS7Lu3Q
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 85.10.231.142:3010...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
AddServerUI:OnAddServer()
RootMotion.FinalIK.GrounderDelegate:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to connect - connection timed out.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to establish connection - no response from remote host
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
Unity.Entities.F_C`1:Invoke(T0)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 89050.
Total: 102.865000 ms (FindLiveObjects: 3.304600 ms CreateObjectMapping: 4.839100 ms MarkObjects: 94.601800 ms  DeleteObjects: 0.119100 ms)

Logging in as 76561198011082840 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NTEzMDExMiwidnhhIjoibG9naW4iLCJ2eGkiOjE0NzU4NiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwMTEwODI4NDAuQG10MXAudml2b3guY29tIn0.FILP3tUkWnovMkmf_AZFPP2uraaCY7dwLOfHAiIEMl4
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

**Comment by D3nnis3n** [comment]
Seems like a connection issue, like a banned IP range on the servers end?

**Comment by mossytiger** [comment]
spoken with server owner and had him check if my ip were banned on server but it isnt

**Comment by beastyn** [comment]
@mossytiger 
WE have some questions for you for problem localization, if you don't mind

1. Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the "latest build" or you had it before?
7. Do you have external IP address and did you use it in config file?

**Comment by mossytiger** [comment]
1. 
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/3936025/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3936026/Player-prev.log)
2. yes i can see ping and server info without issue
3. i do have firewall protection and antivirus protection software enabled. have tried turning it off but didnt fix issue
4. dial up connection also tried network over phone no clue which type that is
5.windows 10
Intel Core i7-CPU 4ghz
32gb ram
Z170A Gaming Pro (MS-7984)
GeForce RTX 2070 SUPER 
6. havent had the issue before last time i played were in updates before 8.0
7. i dont use an vpn and no sure what is meant with config file

**Comment by beastyn** [comment]
Can't connect to this server too.
Are you sure the server is working?

**Comment by mossytiger** [comment]
i can log onto the server on other computers and alot of people are playing on the server. the server is us based

**Comment by mirasrael** [comment]
@mossytiger Can you ask server admin to set Remote Address explicitly? 
![image](https://user-images.githubusercontent.com/475445/70517455-ac917d80-1b49-11ea-805f-d98bab118b39.png)

**Comment by mossytiger** [comment]
i asked admin and he said he updated the connection port

**Comment by mirasrael** [comment]
@mossytiger can you confirm that issue fixed for you?

**Comment by mossytiger** [comment]
Yes the issue has been resolved

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Alexander Bondarev <notifications@github.com>
Sendt: Monday, April 20, 2020 11:13:13 AM
Til: StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc: mossytiger <jonsol@live.dk>; Mention <mention@noreply.github.com>
Emne: Re: [StrangeLoopGames/EcoIssues] cant connect to specifik server (#13959)


@mossytiger<https://github.com/mossytiger> can you confirm that issue fixed for you?

**Comment by mirasrael** [comment]
Cool! Thanks for letting us know!
