### ISSUE TITLE
Balance: Need some balance for adv. campfire cooking

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13951]
It's just too few recipes.
Perhaps it would be better if all the recipes of campfire give experience for it?

**Comment by WeaselDog** [comment]
In my opinion this is only issue for 8.3 but not in staging.

8.3 is very dependent on specific ingredients: Wheat, Huckleberries, Corn, Beet, etc...
In staging you have much more flexibility with Grains, Vegetables, and Fruit.

**Comment by elfl0rd** [comment]
just try it at staging.

**Comment by WeaselDog** [comment]
Oh it is a more serious issue. The meat recipes from Advanced Campfire Cooking are missing like Campfire Roast and Charred Sausage. Raw Roast & Raw sausage still exist but have no purpose.

**Comment by SlayksWood** [comment]
May be add recipes like CharredFood with StaticIngredients? and change it name to Campfire Cooking? Because we still haven't campfire cooking but have advanced campfire cooking.

**Comment by SlayksWood** [comment]
We can rename it now to Campfire Cooking. And Still need some improvements. Will be opened as a reminder

**Comment by WeaselDog** [comment]
We are up to 19 recipes from 8. All charred food now provides exp with static ingredients.
Just need to decide if we change name to Campfire Cooking to close issue.
