### ISSUE TITLE
[STATE: 1278] Make Building great for thin Blocks

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#13956]
Left only code tasks here (Mike)

- [x] Rebind the block choosing key from Shift to F for people upgrading from 8.3.0 - they still get Shift.
- [x] There is a minor issue with the devtool: When hitting e to pick dirt, then hit e to pick a building material it resets the building form selection. This is obviously low priority, but for creative builds it should be fixed nontheless. They look good.
- [x] Another issue with the devtool is that it doesn't seem to support the multi-block placement options of the hammer despite them being available. On choosing the first point to place it just "blinks", then doesn't allow to place blocks via moving the cursor, not even the first one. Only the "single block" placement option works. Should be fixed for creative building. (https://1drv.ms/u/s!Ah1HP-nsGmcYjJMDizviLfd66C4S2w?e=Cs6nTy)
- [x] Block targeting is too easy to slip to the next tile accidentally (sides or up).

**Comment by beastyn** [comment]
I have F by default

**Comment by D3nnis3n** [comment]
Got Shift as well as our testers on the the mentioned build.

**Comment by redwyre** [comment]
Looks like default is F, but it wont change existing key bindings. Reset keybindings to get it to change.

**Comment by D3nnis3n** [comment]
Should that happen to players that never played staging before? Keybind
hasnt been there before?

Simon <notifications@github.com> schrieb am Sa., 30. Nov. 2019, 15:52:

**Comment by WeaselDog** [comment]
So I deleted inputManager.cfg and boot 9.0 and it is fine, "F" is default.
When I deleted inputManager.cfg and boot 8.3 then boot 9.0 it has "Shift" as default instead.

**Comment by D3nnis3n** [comment]
Given most people will upgrade from 8.3, they all will have the wrong key until pressing defaults. This means there is still an issue that needs to be fixed.

**Comment by elfl0rd** [comment]
I'm not sure that's relevant to this task, but...
Some blocks are very difficult to install.
For example, stairs or glasses.
Or roofs, at 0.9 they have really gotten worse.
You really need to aim for a pixel...

**Comment by D3nnis3n** [comment]
I believe that's included in "Block targeting is too easy to slip to the next tile accidentally (sides or up)."

**Comment by beastyn** [comment]
Mike is on the building process now. Have this too #13395
@redwyre  for help

**Comment by redwyre** [comment]
> Rebind the block choosing key from Shift to F for people upgrading from 8.3.0 - they still get Shift.
I have a fix for this one in my next PR
> There is a minor issue with the devtool: When hitting e to pick dirt, then hit e to pick a building material it resets the building form selection. This is obviously low priority, but for creative builds it should be fixed nontheless. They look good.
@D3nnis3n  Can you try this again, as I recently changed how fills/forms work internally, which might fix this.

**Comment by SlayksWood** [comment]
- [ ] "Block targeting is too easy to slip to the next tile accidentally (sides or up)."
Still need improvements, it's hard to build thin blocks. The glass has 4 different positions, but difference is only a couple of pixels.
![image](https://user-images.githubusercontent.com/45708377/72871726-a7a11b80-3cfc-11ea-982b-f7d868cadf2c.png)
![image](https://user-images.githubusercontent.com/45708377/72871731-ab34a280-3cfc-11ea-9e14-660cd5042697.png)
![image](https://user-images.githubusercontent.com/45708377/72871738-ae2f9300-3cfc-11ea-89cb-8c8a11f0fcbf.png)
![image](https://user-images.githubusercontent.com/45708377/72871753-b5ef3780-3cfc-11ea-9189-d7b0350c811a.png)

**Comment by Quadbro** [comment]
Yeah, as i said in pr, we need to make smth with collision bounds for thin blokcs, we'll try to make it better later, for now i'll make it mid prioriity

**Comment by Knigge** [comment]
Since the issue #15867 got closed, i think its important to note that this is not only for thin blocks. It is also difficult to place regular building blocks.

**Comment by StanKryvenko** [comment]
Thin blocks placement is improved. There are problems with glass placement because of collider problems on it, @keegan-o

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81604053-2ee5ce00-9384-11ea-9bc1-e5f12bfe9c24.png)
updated glass window (and flat roof) colliders to be thicker.

**Comment by keegan-o** [comment]
@SlayksWood If you could check to evaluate if this could be closed now, that'd be great. Hopefully it can be.

**Comment by elfl0rd** [comment]
@keegan-o I'm not Slayks, but i tested.
Glass now fine. (0.9-1547)
![изображение](https://user-images.githubusercontent.com/4980243/81669329-bdbf1d00-944e-11ea-9492-f6734778548b.png)

Also this change fix movement over glass plates.

**Comment by SlayksWood** [comment]
yea, seems thin blocks were fixed. We will create a separate issue for certain block if we find any bug.

**Comment by trickenso** [comment]
Note that this isn't working when you're using floor fill type: https://github.com/StrangeLoopGames/EcoIssues/issues/15955#issuecomment-625738629

Should I file a separate ticket about this specific case?
