### ISSUE TITLE
0.9 "Skills" progressbar show only "full" levels

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13952]
![изображение](https://user-images.githubusercontent.com/4980243/69896326-3f166d80-134f-11ea-8335-ee1c0ce8f800.png)

**Comment by beastyn** [comment]
in 8.3 it was showing the progree like that
![bandicam 2019-12-02 10-21-33-815](https://user-images.githubusercontent.com/27898520/69932987-ee3d7b00-14ee-11ea-8bc5-e79460e6bfb4.jpg)
 And now it won't show you the mid-experience

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/75679852-77587f80-5ca1-11ea-8049-21809b1ec45d.png)
Also wrong tooltip background.
