### ISSUE TITLE
0.9 generate landscape (client-new world) - wetland from gneis

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13950]
![изображение](https://user-images.githubusercontent.com/4980243/69895683-d2e33c00-1345-11ea-8dda-1bf4105d6d5c.png)

**Comment by beastyn** [comment]
I've met this issue few times, but its not common for me. 
@elfl0rd  Do you have special steps to reproduce?

**Comment by elfl0rd** [comment]
I think it's result of update 0.8.3 version to _staging_ 0.9.
Maybe something happens with wg config.

**Comment by mirasrael** [comment]
@beastyn was you able to reproduce it?

**Comment by beastyn** [comment]
@mirasrael yeap
For me it was:
1. Delete worldgenerator config
2. Update to 8.3
3. Start server
4. Update to 0.9
5. Make fresh world
have a nice trip to the wetland
![bandicam 2019-12-02 20-13-27-220](https://user-images.githubusercontent.com/27898520/69970713-83b52b00-1540-11ea-889c-f4510e0d1ad2.jpg)

**Comment by beastyn** [comment]
It can bw cures with worldgen deleting

**Comment by elfl0rd** [comment]
it's same issue as previous from 0.7 to 0.8 migration.

**Comment by mirasrael** [comment]
Added versioning support for WorldGenerator config. If version differs from latest version then config will reset to default.
