### ISSUE TITLE
[0.9.0 staging-1281] Civics: Stat recording

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13969]
@johnkslg How should it work?
For exanple, I want ti record the stats for Chat using.

So I've created a law like this
![bandicam 2019-12-02 17-16-38-167](https://user-images.githubusercontent.com/27898520/69958872-86efed00-1527-11ea-8b2e-40340529fd48.jpg)

But when I try to write something, I have an error
![bandicam 2019-12-02 17-19-07-934](https://user-images.githubusercontent.com/27898520/69958990-e0581c00-1527-11ea-88af-1a3e6541e969.jpg)

**Comment by johnkslg** [comment]
This is happening because theres a space in the specified name.  Added a check for invalid names that will make the law invalid and not submittable: 
![image](https://user-images.githubusercontent.com/3536496/69989227-082f8b80-14f8-11ea-88b7-0bdfee451803.png)

**Comment by beastyn** [comment]
Still can't create collection and blocking the action.
![bandicam 2019-12-03 15-26-53-671](https://user-images.githubusercontent.com/27898520/70042883-7b60fc80-15e1-11ea-878a-cf4024dd1630.jpg)
![bandicam 2019-12-03 15-27-46-788](https://user-images.githubusercontent.com/27898520/70042886-7c922980-15e1-11ea-9e91-61e095ecb9e2.jpg)

**Comment by johnkslg** [comment]
I cant repro this: 
![image](https://user-images.githubusercontent.com/3536496/70077363-86059c80-15b5-11ea-8c2e-9f53a8ad7348.png)
![image](https://user-images.githubusercontent.com/3536496/70077383-961d7c00-15b5-11ea-9a1b-fcb59588ae89.png)

Try playing on fresh generation?

**Comment by beastyn** [comment]
Yeah, fine with the fresh one.
Now I can pay for the chat actions, Yay for spammers!
