### ISSUE TITLE
[0.9.0 staging-1281] Inventory: placement in chest with carried

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13968]
Situation is:
1, I have a chest
2. My hand is full with some log
3. My toolbar has the acorns (they are selected)
4. I want to place the acorns to the chest with the right button
It won't allow me to do that.
I should be able to.
Oh, and it has strange hint on the chest "Plant Oak". Funny )
related to #13291

![bandicam 2019-12-02 17-01-31-920](https://user-images.githubusercontent.com/27898520/69958362-7723d900-1526-11ea-8e5f-bc8d230cc829.jpg)

**Comment by SlayksWood** [comment]
#14574, #13291, #14493
