### ISSUE TITLE
[0.9.0 staging-1278] Hewn Log crafting at Carpentry Table doesn't make Hardwood/Softwood

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#13962]
The **Hewn Log** crafting at **Carpentry Table** doesn't make **Hardwood Hewn Log** or **Softwood Hewn Log**, instead it makes (standard) **Hewn Log**.

Version: 0.9.0.0 staging-1278

**Comment by beastyn** [comment]
@Deantwo Thank you for the report.
Can you place a screenshot? What do you have in your storage.
And I suppose you are crafting from parent recipe without choosing specific hewn log type.

**Comment by beastyn** [comment]
Just checked.
Yeas, with Cedar log and parent recipe I've got only Hewn Log.
Table doesn't even show me the variations
![bandicam 2019-12-02 16-54-02-521](https://user-images.githubusercontent.com/27898520/69957398-6a05ea80-1524-11ea-901d-0ff418d0b8cf.jpg)
