### ISSUE TITLE
[0.9.0 staging-1281] Districts: see the name from deleted maps

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13965]
1. I've created a map with a district named Testing Ground
2. I've deleted that map completely
3. Now on the other map I want to add a district with this name
![bandicam 2019-12-02 14-25-18-505](https://user-images.githubusercontent.com/27898520/69947526-a2e79480-150f-11ea-9b18-1d4acecb019b.jpg)
![bandicam 2019-12-02 14-25-36-669](https://user-images.githubusercontent.com/27898520/69947527-a3802b00-150f-11ea-98c6-ee2007de7851.jpg)

So it tells me that I have this name already, but I actually don't have it

We should clear the names when we are deleting the map.

**Comment by beastyn** [comment]
Nope, still the same
![bandicam 2019-12-11 12-23-12-425](https://user-images.githubusercontent.com/27898520/70600376-54be4980-1c11-11ea-99cb-92cf08d6a3bc.jpg)
![bandicam 2019-12-11 12-23-27-819](https://user-images.githubusercontent.com/27898520/70600381-55ef7680-1c11-11ea-9bed-73fcaadeacc6.jpg)

**Comment by johnkslg** [comment]
This is actually by design, the deleted one stays around so that you can see history. IE, what election got it into place, etc.  Lots of data there to preserver.

However, we DO permanently delete them if theyre just drafts and never made it into action.  If that is the case, then reopen.
