### ISSUE TITLE
USER ISSUE: Wheels on truck don't rotate

### ISSUE THREAD

**Issue by Gab-Bryan** [StrangeLoopGames/EcoIssues#13977]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. Grab a truck
2. make someone else look the wheels while driving
3. The back wheels don't roll, they are static

**Expected behavior:**
they should rotate along with the front wheels	

**Actual behavior:**
stays static like inanimated

**Do you have mods installed? Does issue happen when no mods are installed?:**
stays static like inanimated

**Comment by D3nnis3n** [comment]
Haven't seen that, but when you drive and stop driving when rolling only the front two wheels spin, the back ones do no longer, despite i'm still moving.

**Comment by SlayksWood** [comment]
@Gab-Bryan 
I think you tell not about Truck but about Steam TrucK?
Seems dup #12435
