### ISSUE TITLE
Case sensitive whisper messages

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13975]
Sending @johnk didnt work, sending @Johnk did
![image](https://user-images.githubusercontent.com/3536496/69999945-b2b2a900-150e-11ea-8c6d-c2b83c43db78.png)

**Comment by redwyre** [comment]
Github ate your capitalisation, us backtick on the names

**Comment by johnkslg** [comment]
One had a capital J :)

**Comment by beastyn** [comment]
Still the same
![bandicam 2019-12-11 12-11-20-966](https://user-images.githubusercontent.com/27898520/70599637-6ef72800-1c0f-11ea-9716-447528912966.jpg)
![bandicam 2019-12-11 12-11-10-320](https://user-images.githubusercontent.com/27898520/70599638-6ef72800-1c0f-11ea-9397-4d0602817450.jpg)

**Comment by SlayksWood** [comment]
2 chat open if you whisper from wrong Case sensitive. Step to reproduce:
- Anna join to my server with nickname "Beastyn"
- I send to her message "@beastyn hello! how are you?"
![unknown (2)](https://user-images.githubusercontent.com/45708377/70892870-03d89780-1ffb-11ea-9c8a-ef5faaa319b4.png)
- new chat appears: 
![unknown (3)](https://user-images.githubusercontent.com/45708377/70893072-63cf3e00-1ffb-11ea-967e-502f0057f060.png)
- Anna also have new chat with my nickname.
- If Anna sends me message in this chat then I have to chat: first - beastyn, second- Beastyn.
![unknown (4)](https://user-images.githubusercontent.com/45708377/70893170-9e38db00-1ffb-11ea-9b85-3e9181d38437.png)
it should be one chat.
