### ISSUE TITLE
[0.8.3] Problem with show plants / Проблема с отображением расстений

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#13985]
Добрый день!

Некоторые растения не отображаются в игре. Например:
- помидоры
- ананасы
и некоторые другие.

Тестировалось на:
- Windows 10 x64 (видеокарта NVidia GTS250)
- Kubuntu 19.04/19.10 (видеокарта NVidia GTX1050Ti)

Версия игры:
- 0.8.3 steam
- 0.8.3 клиент с сайта

======================================

Good day!

Some plants are not displayed in the game. For example:

     tomatoes
     pineapples
     and some others.

Tested for:

     Windows 10 x64 (NVidia GTS250 Graphics Card)
     Kubuntu 19.04 / 19.10 (NVidia GTX1050Ti graphics card)

Game version:

     0.8.3 steam
     0.8.3 client from the site

**Comment by beastyn** [comment]
Добрый. Спасибо за репорт. 
Не могли бы вы предоставить скриншот?
По возможности также файлы сохранения с координатами невидимых растений.
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
(.eco и .db)

**Comment by Astrija** [comment]
файл с сохранением не получится отправить, так как это было на сервере, а не в локально.

скриншоты прикрепляю (качеством не блещут
![Brr5ysilubw](https://user-images.githubusercontent.com/13696708/70028566-03311180-15b6-11ea-8355-1ee5fb0ca03f.jpg)
![1vJWVU7y8eQ](https://user-images.githubusercontent.com/13696708/70028568-03311180-15b6-11ea-9f6a-9a52d91f1431.jpg)
![4G1PCU_JjfU](https://user-images.githubusercontent.com/13696708/70028569-03311180-15b6-11ea-844b-6c8f2aa955d2.jpg)


)

**Comment by Astrija** [comment]
Проблема наблюдается на обеих платформах на разных компьютерах в разных операционных системах. Но возможно проблема в какой-то технологии: так как на Windows используется старая видеокарта, а в linux - новая, однако что-то может не использоваться.

**Comment by Astrija** [comment]
создала новую игру

ссылка на storage:
[https://cloud.mail.ru/public/4r7S/4W8Po7psM](url)

координаты:
271, 718

прикрепляю скриншоты
![photo_2019-12-03_10-40-25 (2)](https://user-images.githubusercontent.com/13696708/70029972-450f8700-15b9-11ea-9b63-4a64183d4826.jpg)
![photo_2019-12-03_10-40-25](https://user-images.githubusercontent.com/13696708/70029973-450f8700-15b9-11ea-8c59-cc5fb7c0550c.jpg)

**Comment by Astrija** [comment]
Hello. After update to 0.8.3.1 this is problem is right.
