### ISSUE TITLE
/Warn command update + /announce

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13983]
Need some improvements here

For /warn update
1.Yellow notification, looking like the Error Block with bigger timer (about 10 sec).  
2. It should appear in right important notifications too (so people can close it or leave as they want).
3. Also place in the main chat in Notification tag
3. Working just for the pointed person,

Add /announce (string for parameter)
All the same. just should be send for all the players.

**Comment by beastyn** [comment]
1. Warnuser and announce messages are doubled in the main chat.

2. Its about 5 sec now, can we make it 10?
3. Make them permanent in the main chat. Let them stay there for the history.

**Comment by D3nnis3n** [comment]
@beastyn Been rechecked?

**Comment by SlayksWood** [comment]
When you give announce it appear 3 times in main chat.
![image](https://user-images.githubusercontent.com/45708377/70889728-4cd91d80-1ff4-11ea-86fb-8565b6453f59.png)
After time it will left one.
![image](https://user-images.githubusercontent.com/45708377/70889820-827e0680-1ff4-11ea-972b-fc0e54fc8e97.png)

**Comment by SlayksWood** [comment]
wrong name in /manage warnuser.
![image](https://user-images.githubusercontent.com/45708377/70895458-0db0c980-2000-11ea-94ab-2faccd0e5ec7.png)

**Comment by beastyn** [comment]
1. Now we don't have these messgaes in the main chat
2. Now we don't have these messages on the screem (attention rectangle)
3. These messages now are only in the right notifictions panel and they are cutted after a comma
![bandicam 2020-01-06 16-27-47-371](https://user-images.githubusercontent.com/27898520/71815531-9374e180-30a1-11ea-8fa9-89029c60d2da.jpg)
![bandicam 2020-01-06 16-28-07-186](https://user-images.githubusercontent.com/27898520/71815532-953ea500-30a1-11ea-9288-ecb12aa12ddb.jpg)
