### ISSUE TITLE
[0.9.0 staging] UI: Missing currency tooltip in Your Accounts in Economy Viewer

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13989]
For the Your Accounts UI, we are no longer able to get a currency report from highlighting the currency names:
![YourAccountsTagIssue](https://user-images.githubusercontent.com/47330823/70073790-628b2380-15ae-11ea-9673-7287c89fb497.png)
 
As mentioned in this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/13271 , the currency report screen also has an issue where it loads too small:
![CurrencyReportUI](https://user-images.githubusercontent.com/47330823/70168421-b0bb2800-167d-11ea-9493-a4d38a3b896b.png)

**Comment by SlayksWood** [comment]
merged to #15285
