### ISSUE TITLE
New recipe hint contains wrong benefit info

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13986]
Just look at new hint...
![20191203095643_1](https://user-images.githubusercontent.com/4980243/70027540-6c635580-15b3-11ea-834a-82be15d36883.jpg)
And compare with old.
![изображение](https://user-images.githubusercontent.com/4980243/66808549-2afbe580-ef34-11e9-9d8b-bebbbbab21fb.png)
https://github.com/StrangeLoopGames/EcoIssues/issues/13334
How experience you get after craft it?

Additional issue, as i see - "benefit from skills" shown incorrectly, as you can see, i have hewing, but "no benefit from skills"

**Comment by beastyn** [comment]
experience in here #13334
Will leave it for benefits issue

**Comment by mirasrael** [comment]
Benefits info fixed. XP is in separate issue.

**Comment by mirasrael** [comment]
Ok. Actually XP already in recipe.
