### ISSUE TITLE
0.9 Visual spam from work orders.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13987]
It's not cool. Every time you need to remove jobs from displaying, to prevent visual spam.
![20191203100003_1](https://user-images.githubusercontent.com/4980243/70027782-f4e1f600-15b3-11ea-85cb-72eda6f42468.jpg)
![20191203100035_1](https://user-images.githubusercontent.com/4980243/70027783-f4e1f600-15b3-11ea-90a1-ea27bff829aa.jpg)
![20191130092207_1](https://user-images.githubusercontent.com/4980243/70027786-f7445000-15b3-11ea-8e59-59703c088b70.jpg)
In areas of high machine density, project icons cover the entire screen.

**Comment by beastyn** [comment]
You have setting for markers "Max distance to show"
Try put 2 for it.
We can make smaller number by default.

**Comment by elfl0rd** [comment]
I believe the behavior should be inverted.
From "show all, remove unnecessary manually" to " do not show, turn on the manual display of the necessary ones".

**Comment by beastyn** [comment]
Then we can do this.
For table markers we will make distance 1 (it won't show icon mostly. Need to check).
Then we should tell about sidtance on markers in tutorial AND in order tooltip somewhere.
For markers we need to make a possibility to change a distance for bunch of them in one go.
@johnkslg what do you think?

**Comment by johnkslg** [comment]
Reducing distance it shows from 10 to 2.  Let me know how this feels. Hopefully we dont need an option.

**Comment by elfl0rd** [comment]
> Reducing distance it shows from 10 to 3. Let me know how this feels. Hopefully we don't need an option.

What about map marker and right top panel?
I really dont want them :)
