### ISSUE TITLE
Need Balance for Labor

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13981]
Still some that dont

**Comment by SlayksWood** [comment]
need more Balance

**Comment by SlayksWood** [comment]
1 Rivet from Iron bar = 35 Labor
3 Rivet from Steel bar =  20 LAbor. I think you wanted to add as 20 Labor per one. So you can increase it to 60
![image](https://user-images.githubusercontent.com/45708377/71074264-03730480-2193-11ea-911e-88781b466fc8.png)
