### ISSUE TITLE
[0.9.0 staging] Client crash during currency selection

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13982]
At the currency selection drop down, if you change the currency off the selected currency then back it will crash the client. This crash will happen at stores, public crafting stations, or anywhere with currency selection.

**How to replicate:**

- Pull up the currency drop-down menu
- Change to another currency
- Change back to the original currency 

**Additional way to replicate:**

- Pull up the currency drop-down menu
- Change to second currency
- Change to a third currency
- Change back to the second currency

![CurrencyDropDown](https://user-images.githubusercontent.com/47330823/70013770-8e19f980-152d-11ea-8dab-ab37f616246e.png)

I have the same crash when selecting bank accounts. This is the error:
Assertion failed: Subscription was added twice: BankAccountView.MarkedUpName for AutoGenSelector. Please, use SubscribeUnique!

**Comment by WeaselDog** [comment]
Currency selection drop down for laws is not affected by this.

**Comment by beastyn** [comment]
Can't reproduce with the last build. Check it please

**Comment by WeaselDog** [comment]
It was fixed for me with change to subscriptions in referenced PR

**Comment by WeaselDog** [comment]
Does this also fix https://github.com/StrangeLoopGames/EcoIssues/issues/6593?
