### ISSUE TITLE
Add support for C# 6.0 (.NET 4.6.2) in mods

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#1399]
Hi as a programmer I got used to the C# 6.0 features too quickly and when I am writing code for ECO I have to stop and think of how it used to be. for instance I just love the new shorthand string formatter and the object initializer.

Please add these features in the compiler so we can start using them!

**Comment by metachronism** [comment]
this is already supported.  You can pre-compile mods into dlls, and the modkit will load them.

its not possible to support this for the *.cs files that are compiled at runtime however.  the CodeDom does not support this.
