### ISSUE TITLE
Research papers level with roman numerals is awkward for tooltips

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13998]
![image](https://user-images.githubusercontent.com/3536496/70104688-a8b6a600-15f3-11ea-9195-d341e653c26e.png)

Probably want to call them '... Research Papers Tier 2' etc

**Comment by SlayksWood** [comment]
Forgot to change Agriculture Research Paper I and II:
![image](https://user-images.githubusercontent.com/45708377/72052185-b7b90400-32d5-11ea-8efa-e6a1ed408e87.png)
