### ISSUE TITLE
Make this font work in localized regions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13990]
![image](https://user-images.githubusercontent.com/3536496/70078536-b51d0d80-15b7-11ea-8aec-71f7a710f461.png)
Find a backup font to use for unicode that is fancy like this one (but keep using this one for English)

**Comment by elfl0rd** [comment]
please, can you change this font? My eyes are bleeding :(
I understand you want a handwritten font, but damn it, it's unreadable!

**Comment by beastyn** [comment]
@johnkslg I like the idea of something authentiс, but I don't think that it fits for the UI in general.
@MilenkoTunjic for consultation maybe?
