### ISSUE TITLE
Change direct messages that are a result of a user action to be OkBox's instead of messages

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13999]
![image](https://user-images.githubusercontent.com/3536496/70104761-e287ac80-15f3-11ea-958e-04ee12dcecfb.png)
As a rule of thumb, any message like an error, confirmation, etc that results from user interaction on a UI should show as a popup box. A lot of them go to the chat and are really easy to miss.  

In this case, the direct to user message on the contract should be a popup box.
Use OkBoxLoc and OkBoxLocStr

Go through all the places you can think of where this is the case.

**Comment by SlayksWood** [comment]
When you take any contract, you have double notification.
![image](https://user-images.githubusercontent.com/45708377/72235219-f1de1a80-35e1-11ea-8048-ce60fdcbd5ad.png)
