### ISSUE TITLE
[0.9.0 staging] Civics - Title creation condition "Ineligible Candidates"

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14006]
I was hoping to have separate elected titles, senators and a president. In order to prevent someone from holding both offices, there should be something like "Ineligible Candidates" as a condition for a title. 

![Candidates](https://user-images.githubusercontent.com/47330823/70109474-dce49380-1600-11ea-8394-798ee5fd249d.png)

**Comment by johnkslg** [comment]
Added a feature that will give this + more power, 'Candidate Conditions':
![image](https://user-images.githubusercontent.com/3536496/70186583-0ce37380-16a1-11ea-9f8b-b71a28429703.png)

You can set arbitrary conditions needed for a player to be a candidate.
![image](https://user-images.githubusercontent.com/3536496/70187024-220cd200-16a2-11ea-9c5c-91042a050dc3.png)

![image](https://user-images.githubusercontent.com/3536496/70187032-26d18600-16a2-11ea-8b8a-955ead489e0a.png)

![image](https://user-images.githubusercontent.com/3536496/70187057-33ee7500-16a2-11ea-8ee7-9c1e1db33060.png)

You can make the check have a list of conditions and set demographics you want to forbid.

**Comment by beastyn** [comment]
looks fine
Added this #14040

**Comment by WeaselDog** [comment]
Nice! This is much better than "ineligible candidates". You can get creative with the "Set of Conditions" requirement.
![TitleRequirements](https://user-images.githubusercontent.com/47330823/70337216-7da0a200-17ff-11ea-931a-6bccaa56f9b3.png)

**Comment by johnkslg** [comment]
exactly!
