### ISSUE TITLE
Server is ticking and compressing when loading an existing save

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14007]
![image](https://user-images.githubusercontent.com/3536496/70109746-ba9f4580-1601-11ea-9ce6-4f9721e110dc.png)
Before init is finished, it shouldnt be doing this except on generation.

**Comment by mirasrael** [comment]
It is intended as part of World Initialization process. It tick active chunks (while they active) and then compress frozen chunks for the memory save. I made messages more informative.
