### ISSUE TITLE
Web Scientific data - graphs not working in russian localization (server-side)

### ISSUE THREAD

**Issue by AlexALX** [StrangeLoopGames/EcoIssues#14004]
Hi, i have major problem when using server localization as russian - almost any graphs not working at all. No co2 level/sea level/human stats/animal populations etc, just don't show anything except titles (with no line in graphs itself). Happens always even single player or on dedicated server. Because of this - people can't see what happens with world. If chose english localization server-side - everything start to work as expected.

Also sometimes web ui gets messed with half english + half russian titles, happens not always but often.

Here is screenshot of both issues: https://i.imgur.com/9A7LIa8.png

**Comment by beastyn** [comment]
Thank you fot your report.
With 0.9 should be fixed graph problem,
![bandicam 2019-12-04 18-18-48-857](https://user-images.githubusercontent.com/27898520/70145715-8cce0580-16c2-11ea-8dab-dfac7945c8c2.jpg)
I will make separate issue for localization.

**Comment by AlexALX** [comment]
Is there fix via plugin possible to do until 9.0 released? Its pretty game breaking thing.

**Comment by AlexALX** [comment]
Ok i did able to "fix" that myself. Just edited file WebClient\WebBin\graph_composer\script\init.js replaced all ".DisplayName" with ".KeyFragment" (5 places). Now it displaying in graph as half english but at least work. Tried to make proper localization by modifying more functions but it seems way more complex so just will use that solution now. Thanks.

**Comment by beastyn** [comment]
Thanks for patient. 0.9 version should be much better )

**Comment by AlexALX** [comment]
I even did complete fix with localization support. If someone needs fix for current version: https://pastebin.com/9dM8ngP7

I did edited functions createDatasetList, createObjByDataset and loop part inside updateDatasetList.

Works really good. Waiting for 0.9 now) Also you should consider to rework localization module - it should be independent from server language like in other games...

**Comment by mirasrael** [comment]
Thanks @AlexALX 
Yes, we already have localization system which allows to use client localization for server data and it even works in some places (like tutorial), but there still lot of things to redo with new system. But eventually we will make almost everything working in client language.
