### ISSUE TITLE
[0.9.0 staging] Civics: Clearing tree debris does not trigger a law action

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14012]
There is no law trigger for clearing tree debris. Normally it should say something like pickup/chop when viewing the /civics debug message, but now there is nothing: 
![WoodPulpTrigger](https://user-images.githubusercontent.com/47330823/70173484-c3d2f580-1687-11ea-92a4-553ed9c00a05.png)

In 8.3 clearing wood pulp is covered by pickup wood pulp.

**Comment by johnkslg** [comment]
Fixed with custom action 
![image](https://user-images.githubusercontent.com/3536496/70360301-e6edd880-1832-11ea-91b2-5f45c24dcae9.png)
![image](https://user-images.githubusercontent.com/3536496/70360308-ece3b980-1832-11ea-8bec-6221b1e67b64.png)
