### ISSUE TITLE
Ecopedia feedback: The reboot

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14013]
![image](https://user-images.githubusercontent.com/3536496/70178060-668f7200-1690-11ea-9e12-1ea14d568fa4.png)
- [x] Make this name properly localized and have spaces.  Name it 'Components'. Change icon to a workbench. 
![image](https://user-images.githubusercontent.com/3536496/70178171-a48c9600-1690-11ea-9b64-f86ad3a97123.png)
- [x] Question mark would look better in upper right side of the tab there (but check with Milenko)
![image](https://user-images.githubusercontent.com/3536496/70178221-bf5f0a80-1690-11ea-95d7-63fc4a22f176.png)
- [x] Names are not getting localized here, using the code name instead of display name. 
![image](https://user-images.githubusercontent.com/3536496/70178306-e3bae700-1690-11ea-801a-53464a1905f2.png)
- [ ] Work with Rob to get all missing icons in ecopedia
![image](https://user-images.githubusercontent.com/3536496/70178355-fdf4c500-1690-11ea-8146-2240da05b2b9.png)
- [x] Need to do something about labels, the different sizes and overlapping the image isnt looking so great. Maybe a plaque below? Work with Milenko to find a solution
- [ ] Need different icon for rooms and housing here. Make sure no duplicate icons.
![image](https://user-images.githubusercontent.com/3536496/70178441-2a104600-1691-11ea-8100-6cdae1f418fc.png)
- [ ] Duplicate icons, and contract board icon is bad and needs redoing.  Use different icon for transport too, a truck or cart 
![image](https://user-images.githubusercontent.com/3536496/70178560-5e840200-1691-11ea-904b-222446e23156.png)
- [x] Make clicking the constitution link open the ecopedia page.  Add icons for missing types here (laws)

![image](https://user-images.githubusercontent.com/3536496/70178726-9c812600-1691-11ea-9c41-8be0bb88df0a.png)
- [x] Lots of things under food that shouldn't be. Reorganize these to make sense, make some new tabs. 

![image](https://user-images.githubusercontent.com/3536496/70178761-af93f600-1691-11ea-8186-ec707134fb51.png)
- [x] This many subobjects breaks scrolling. Make subobjects top out at 3 rows and then give it a separate scroll bar. 
- [ ] Bunch of missing icons here. 

- [x] Under skills tab, have each profession as a category, with the specialties as subpages under each. 

![image](https://user-images.githubusercontent.com/3536496/70179016-1d402200-1692-11ea-8e2f-f3a6ad6bd238.png)
- [x] Add a popup confirmation when you click this that its cleared them (all user actions should have acknowledgement)

- [x] After closing ecopedia with escape, entered weird state where my cursor was visible but was still controlling camera. This shouldnt be possible, it should just go back to cursor invisible. Make sure no other UIs have this issue too. 
- [ ] If I opened the ecopedia from a table or economy viewer, closing it by clicking the X would take me to the previous window, but pushing escape would close all windows. Lets make escape close the current one and take you back up one level.

![image](https://user-images.githubusercontent.com/3536496/70179178-71e39d00-1692-11ea-933a-675c9ede0fac.png)
- [x] Rig up this panel to be ecopedia friendly. Each type of tooltip should have a question mark to take you to the ecopedia page about it:
- Nutrition
- Housing
- Experience
- Each specialty that can be displayed
- Skills button to skills page

![image](https://user-images.githubusercontent.com/3536496/70179395-d56dca80-1692-11ea-93e7-87e2aadc297f.png)
- [x] All items should have a question mark that takes you to the most relevant ecopedia page. This one should take you to property, for example.  Others can take you to the item subpage that they have.  Skillbooks and skill scrolls and can take you to their specialty page.

**Comment by serpopov** [comment]
Can we make separate issues for icons and UI behaviour?

**Comment by beastyn** [comment]
yeap, but we still have this one

If I opened the ecopedia from a table or economy viewer, closing it by clicking the X would take me to the previous window, but pushing escape would close all windows. Lets make escape close the current one and take you back up one level
