### ISSUE TITLE
Too many new laws with graphs at once causes lag

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#14016]
Teacher said: 
"One new issue I found was when they discovered the laws and added graphs with too many things, that absolutely lagged the server while it tried to draw them, then they didn't think it was working so they spammed the submit law button, which resulted in 6 copies and just to load one of them would take ~3 minutes before I could delete them, if multiple kids accessed these laws at the same time it started lagging the server and disconnected a few kids.   For now I've told them to talk to me before making a law with a graph, but I think it might be wise to limit the amount of things that are allowed into a graph to less then 5 for a single law or else it will likely start lagging things."

**Comment by mirasrael** [comment]
Unfortunately we're not going to fix law system in 8.3. It is known issue that it is very laggy and buggy in last released version. It is reason why it was completely reworked in 9.0. Hopefully it will be fixed in 9.0 with law system updates.

**Comment by beastyn** [comment]
Should be fine with new system.
