### ISSUE TITLE
Labor feedback 3

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14015]
![image](https://user-images.githubusercontent.com/3536496/70180036-13b7b980-1694-11ea-86ef-42b33ebf2468.png)
- [x] Need a popup on the labor icon explaining the labor needs.  
'This recipe requires X calories of <specialty> labor (You [have/do not have] this specialty)'
'Users with this specialty'
'<list> [or] None.'

![image](https://user-images.githubusercontent.com/3536496/70180189-5ed1cc80-1694-11ea-92e5-296ab54eac12.png)
- [x] Tooltip needs to explain the numbers you see there, and if this a tag the fact that any of the items can be accepted:
'Requires 30 Fiber to craft. You have 0.'
'Items that can be used as Fiber:'
<list>

![image](https://user-images.githubusercontent.com/3536496/70180294-917bc500-1694-11ea-84c0-81fffc3c5be2.png)
- [ ] Lets move this time to be another icon, a clock, with 5 minutes written on it, instead of this separate display. 

![image](https://user-images.githubusercontent.com/3536496/70180337-a8bab280-1694-11ea-9dd2-2536b1f0a271.png)
- [ ] I started a recipe with no ingredients, but the display says 'labor needed', it should say 'ingredients needed' since you need the ingredients before the labor can be added.

![image](https://user-images.githubusercontent.com/3536496/70180425-d7d12400-1694-11ea-8c38-97b60d3da057.png)
- [x] I was able to perform the labor despite having no ingredients. Should never be able to do more labor percent than you have ingredients. 

![image](https://user-images.githubusercontent.com/3536496/70180390-c2f49080-1694-11ea-8e65-20b5fae5c9be.png)
- [ ]  Mousing over the work button popped up a tooltip preventing me from clicking it. Same for 'collect' button.

![image](https://user-images.githubusercontent.com/3536496/70180465-f0413e80-1694-11ea-831a-06b90ffd5c56.png)
- [ ] Need to display ingredients needed. This is displayed on the marker:
![image](https://user-images.githubusercontent.com/3536496/70181313-86299900-1696-11ea-8f96-3884f71c5b9c.png)
Display on both. Marker and top thing should always show same data. Also ask Milenko to make an extension to the graphics for a tray to hold the needed ingredients, which gets hidden when they get added. 
- [ ] It's possible both labor and ingredients are needed, can display both.

![image](https://user-images.githubusercontent.com/3536496/70180565-2252a080-1695-11ea-845a-5e529e54d398.png)
- [x] This said I had 10 logs available, but I had no logs
- [x] Title of tooltip should be 'Stockpile Work Order' not just 'Stockpile'
- [x] Needed ingredients (10 logs) are listed twice in the tooltips
- [x] Make the percent completion numbers colored (Text.StyledNum) and make them aligned vertically (Text.Pos)

![image](https://user-images.githubusercontent.com/3536496/70181020-f683ea80-1695-11ea-86af-36aee13e1401.png)
- [ ] Resources are not represented as a bar. Should look like this:
![image](https://user-images.githubusercontent.com/3536496/70181048-03a0d980-1696-11ea-8b9a-b3da137d9e4e.png)

![image](https://user-images.githubusercontent.com/3536496/70181219-5b3f4500-1696-11ea-9333-aa219de2b7f9.png)
- [x] Enlarge sequence didnt happen when I added labor or ingredients. It should happen for both.

![image](https://user-images.githubusercontent.com/3536496/70181404-aeb19300-1696-11ea-98da-5d58e8c114b8.png)
- [ ] Labor marker was glowing yellow for some reason.  Glow should only be visible when I'm able to perform labor there (and I have the needed skill to do so).   Make glow more prominent, so you can see from a far that tables are waiting for you to go click them.

![image](https://user-images.githubusercontent.com/3536496/70181535-eddfe400-1696-11ea-91f9-bf74591d6e15.png)
- [ ] These two objects need to be virtually identical. They should use the same code, the same UI objects, and always display the same data.  They should be the same object, with perhaps a slightly different background (using prefab inheritance) on the top one to give it a different frame.  

- [ ] Marker was disappearing if I looked away from it slightly. It should always display if it's on screen and in a specific radius (shouldn't need to be looking directly at the table)

**Comment by SlayksWood** [comment]
> * I started a recipe with no ingredients, but the display says 'labor needed', it should say 'ingredients needed' since you need the ingredients before the labor can be added.

I think we decided to change this system because it very hard to add every time labor after adding resources. Isn't it?
We add possibility to add a lot of calories, add calories before resourses to make game more easy. 

> * Resources are not represented as a bar. Should look like this:
>   ![image](https://user-images.githubusercontent.com/3536496/70181048-03a0d980-1696-11ea-8b9a-b3da137d9e4e.png)

This need only if we leave system with separate adding Labor without checking resourses. We have a lot of changes to it:
- posibility to add a lot calories,
- changing bar for separate resourses and calories:
![image](https://user-images.githubusercontent.com/45708377/70425091-991adf80-1a81-11ea-8295-ed1eda2eabc7.png)
When we change Bar I add issue to change this Order icon.

**Comment by elfl0rd** [comment]
> I started a recipe with no ingredients, but the display says 'labor needed', it should say 'ingredients needed' since you need the ingredients before the labor can be added.

How it work with large order?
For now, order is not "lock" resources...
Or you need separate "labor" for every things in large order? Not usefull.

**Comment by johnkslg** [comment]
I refactored this, so closing this. Please open a new issue with new feedback.
