### ISSUE TITLE
0.9 "Edit List" button in store

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14021]
Now it is tied to the lowest position of both lists, which is inconvenient if buying and selling differ significantly in length.
![20191205102203_1](https://user-images.githubusercontent.com/4980243/70212856-23450a00-1749-11ea-9cc3-c2a648bf8523.jpg)
![20191205102205_1](https://user-images.githubusercontent.com/4980243/70212857-23dda080-1749-11ea-94ff-72e1b2208f89.jpg)

**Comment by beastyn** [comment]
Don't create the new one. Please, put your suggestion there #14021

**Comment by elfl0rd** [comment]
from end of list to this position maybe?
![70212856-23450a00-1749-11ea-9cc3-c2a648bf8523](https://user-images.githubusercontent.com/4980243/70230636-cc9bf800-1769-11ea-8ce1-69e8782867b1.jpg)

(Scrolling the list is annoying if you have a lot of items in the store)
