### ISSUE TITLE
8.3.0: HTML Input can crash any server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14028]
`<size="4">MENU<br><br></size><size="2>Elk Wellington<br><br>Macaroons<br><br>Camas Bread`

Adding this to a sign / truck or anything else will crash every client around the sign, forever. The area can never be entered again.

**Comment by WeaselDog** [comment]
Related to this: https://github.com/StrangeLoopGames/EcoIssues/issues/13204

**Comment by beastyn** [comment]
So, it was fixed for 0.9, but seems need to fix for 8.3 too
Write in Steam Truck text field:
<size=100>text<br><br><br><br><br><br><br><br><br><br><br><br></size>

Also was able to reproduce for wood cart
<size=4>MENU<br><br></size>
<size=4>MENU<br><br></size>
<size=4>MENU<br><br></size>
<size=4>MENU<br><br></size>
<size=4>MENU<br><br></size>
<size=2>Elk Wellington<br><br>Macaroons<br><br>Camas Bread
