### ISSUE TITLE
suggestion\qol: "edit list" button position (in store)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14024]
from end of list to this position maybe?
![70212856-23450a00-1749-11ea-9cc3-c2a648bf8523](https://user-images.githubusercontent.com/4980243/70230636-cc9bf800-1769-11ea-8ce1-69e8782867b1.jpg)

(Scrolling the list is annoying if you have a lot of items in the store)

**Comment by beastyn** [comment]
Please, put your suggestion here #14021
Don't need to create the new one
