### ISSUE TITLE
0.9 staging - rotation not work

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14022]
Q\R no more rotate forms.
![20191205102425_1](https://user-images.githubusercontent.com/4980243/70213018-76b75800-1749-11ea-8dd0-1f1da313002b.jpg)

**Comment by beastyn** [comment]
@redwyre for advice

**Comment by redwyre** [comment]
might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/14020 ?

**Comment by beastyn** [comment]
Don't think so, You can be in the normal hammer mode, choose stairs, for example, but it won't rotate with Q/R

**Comment by redwyre** [comment]
This was my fault
