### ISSUE TITLE
[0.9.0 staging-1286] Audio: no grass sound during walking

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14026]
in 8.3
https://drive.google.com/file/d/1agb-kQNqUtIVV_aZPZ5danHcXmIKa3A5/view?usp=sharing

Now
https://drive.google.com/file/d/1q3APhcHQr0_pK83im2ICoGqyfGpQ1Qoc/view?usp=sharing

**Comment by beastyn** [comment]
Addition: also No sound of movement through plants (on the video too.)

**Comment by beastyn** [comment]
Still no plants sound and footsteps toooo silent (I can't hear them at all)

**Comment by SlayksWood** [comment]
I haven't grass sound during walking, but niw I have Footsteps sound, but a little quiet.

**Comment by Quadbro** [comment]
Yes, found the problem in code, Leonard's side was ok

**Comment by beastyn** [comment]
still don't hear it

**Comment by beastyn** [comment]
So grass is here.
But I hear it even if i don't move, sometimws quite loud for the small grass.
https://drive.google.com/file/d/1Ryn4uPDxgJ1mBpb4XP2lyqQAv2dm6eoi/view?usp=sharing
