### ISSUE TITLE
[0.9.0 staging-1287] Edit Avatar deletes my Clothes.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14038]
Step to reproduce:
- join to new server. Create this avatar: Body - Normal Hair, Shord Beard, Shirt - Heanly, Pants - Capris, Boots - Tall Boots. Hat - No. 
![image](https://user-images.githubusercontent.com/45708377/70301215-d3c71280-180a-11ea-9952-2d1d49cde52b.png)
- start play. Equip Alpha hat, Alpha googles,  Work Boots, Camo Shirt, Camo Pants.
![image](https://user-images.githubusercontent.com/45708377/70301432-6962a200-180b-11ea-84c0-6a10cce7b259.png)
- want to change my clothes color. Press Edit 
![image](https://user-images.githubusercontent.com/45708377/70301500-8b5c2480-180b-11ea-9ebf-61f7cf5fc56c.png)
- If you accidentally change cloth (for example Hat) and press "Save" than you lose your Alpha hat
![image](https://user-images.githubusercontent.com/45708377/70301711-2b19b280-180c-11ea-8e57-144cb29771fc.png)
- you can lose Hat, Pants, Shirt, Boots.

Maybe you should think about impossibility of rechanging clothes? Can you change the appearance only with wearing a new  crafted clothes.

**Comment by elfl0rd** [comment]
afaIk, at 0.8.3, you can't change clothings after avatar creation, only color.

**Comment by johnkslg** [comment]
@beastyn @SlayksWood thinking we dont allow editing avatar after creation, its weird that you can change your whole appearance/skin color/change clothes or colors.  

Especially since new types of clothes and outfits will be a thing later, youll have to craft them etc, shouldnt be able to magically change them.

**Comment by elfl0rd** [comment]
Editing colors are ok (because we cannot have ability to repaint in game)
But like 8 - ability to change clothes should be unavailable.

**Comment by beastyn** [comment]
Sergey is on changing this logic. This issue is for him.

**Comment by SlayksWood** [comment]
fixed, open separate task for changaing clothes color #16386
