### ISSUE TITLE
[0.9.0 staging] Recipe: Missing Advanced Campfire Cooking Recipes

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14036]
The Advanced Campfire Cooking recipes "Campfire Roast" and "Charred Sausage" are missing right now with no substitute recipe.

![CampfireRoast](https://user-images.githubusercontent.com/47330823/70268654-c3089500-1755-11ea-9d86-d11177799ec3.png)

**Comment by SlayksWood** [comment]
Change requires for Campfire Roast to 2(same was in 8.3.0)
Also Fat isn't ingredient it' product.
