### ISSUE TITLE
[0.9.0 staging] Crafting: Recipe hints are missing information

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14034]
To check this easily, just spawn a butchery table and check the meat tooltips.  None of the recipes are linked to the respective ingredients, with the exception of Baked Meat. Most of the recipes still work if you have the ingredients.  @Sekor2600 provides more information below.
![PreparedMeatIssue](https://user-images.githubusercontent.com/47330823/70262225-d19c7f80-1748-11ea-86cb-6e81b963357a.png)

Another recipe hint related issue: https://github.com/StrangeLoopGames/EcoIssues/issues/13986

**Comment by Sekor2600** [comment]
To point 1 only hints are displayed if a TagRecipe is used. Like MeatTag. Bakedmeat is in the moment the only Recipe with Meat Recipe.
But it should also be displayed when using normal recipes. 
![grafik](https://user-images.githubusercontent.com/37456949/70265118-07b61f80-179a-11ea-8180-482540cc629c.png) 
IronAxle has no Tag and shows not that it can be used in Steamtruck or other Recipe.

**Comment by WeaselDog** [comment]
Good info. Probably this should be split into two different issues if the first one is related to all recipes.

**Comment by SlayksWood** [comment]
#13819
