### ISSUE TITLE
[0.9.0 staging] Civics: Law condition for "Performed on Property"

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14033]
In 8.3 there is a condition that checks if an action is performed on a specific property. It is used often on the white-tiger server.  Right now there is no substitute for it in staging:

![LawLocationspng](https://user-images.githubusercontent.com/47330823/70260772-dad81d00-1745-11ea-9690-fad0a2452ea5.png)
![LawPropertyRequirements](https://user-images.githubusercontent.com/47330823/70260780-dd3a7700-1745-11ea-9c74-a48591eba3be.png)

**Comment by johnkslg** [comment]
What kind of specification are you thinking? Choosing the specific deed itself?

**Comment by johnkslg** [comment]
Reccomend push for 9.0 since we can use districts.
In a later release we can make property specifiable like districts, but its a bigger change to allow that.

**Comment by johnkslg** [comment]
Recommend drop in priority and rename too since its avoidable

**Comment by WeaselDog** [comment]
Maybe move this to suggestion even. After seeing how the districts play out can reopen if needed.
