### ISSUE TITLE
frontpage/ query giving wrong graph data

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1403]
Supposed to be giving data for two graphs.
But the first graph's many variables are broken up into many graphs.

The populations graph is sending correctly, as one graph with many variables.

{
  "Info": {
    "GamePort": 3000,
    "WebPort": 3001,
    "Description": "OLDFRIEND",
    "Ping": 0,
    "OnlinePlayers": 0,
    "TotalPlayers": 1,
    "TimeSinceStart": 177569.49412384562,
    "TimeLeft": 2414430.5058757267,
    "Animals": 1687,
    "Plants": 191396,
    "Laws": 2,
    "WorldSize": "1km²",
    "Version": "0.5.6 alpha marjie-teachertools-ca333482"
  },
  "Graphs": [
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Cooking"
          ]
        ],
        "TimeMin": 2.0552024766172092,
        "TimeMax": 2.0552024766172092
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Engineering"
          ]
        ],
        "TimeMin": 2.0552024766617563,
        "TimeMax": 2.0552024766617563
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Agriculture"
          ]
        ],
        "TimeMin": 2.0552024766716555,
        "TimeMax": 2.0552024766716555
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Carpentry"
          ]
        ],
        "TimeMin": 2.0552024766815546,
        "TimeMax": 2.0552024766815546
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Smithing"
          ]
        ],
        "TimeMin": 2.0552024766914543,
        "TimeMax": 2.0552024766914543
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Masonry"
          ]
        ],
        "TimeMin": 2.0552024767013535,
        "TimeMax": 2.0552024767013535
      }
    },
    {
      "Category": "Humans",
      "Name": "GainSkill",
      "Graph": {
        "Keys": [
          [
            "Humans",
            "All",
            "GainSkill",
            "Civics"
          ]
        ],
        "TimeMin": 2.0552024767162025,
        "TimeMax": 2.0552024767162025
      }
    },
    {
      "Category": "Ecosystem",
      "Name": "Populations",
      "Graph": {
        "Keys": [
          [
            "Animal",
            "Population",
            "Hare"
          ],
          [
            "Animal",
            "Population",
            "Elk"
          ],
          [
            "Animal",
            "Population",
            "Wolf"
          ],
          [
            "Animal",
            "Population",
            "Bison"
          ],
          [
            "Animal",
            "Population",
            "Turkey"
          ],
          [
            "Animal",
            "Population",
            "Fox"
          ],
          [
            "Plant",
            "Population",
            "Camas"
          ],
          [
            "Plant",
            "Population",
            "Birch"
          ],
          [
            "Plant",
            "Population",
            "Cedar"
          ],
          [
            "Plant",
            "Population",
            "Bunchgrass"
          ],
          [
            "Plant",
            "Population",
            "Fern"
          ],
          [
            "Plant",
            "Population",
            "Huckleberry"
          ],
          [
            "Plant",
            "Population",
            "CommonGrass"
          ],
          [
            "Plant",
            "Population",
            "Wheat"
          ],
          [
            "Plant",
            "Population",
            "Beets"
          ],
          [
            "Plant",
            "Population",
            "Corn"
          ],
          [
            "Plant",
            "Population",
            "Fireweed"
          ],
          [
            "Plant",
            "Population",
            "CreosoteBush"
          ],
          [
            "Plant",
            "Population",
            "Sagebrush"
          ],
          [
            "Plant",
            "Population",
            "PricklyPear"
          ],
          [
            "Plant",
            "Population",
            "Beans"
          ],
          [
            "Plant",
            "Population",
            "Bullrush"
          ]
        ],
        "TimeMin": 2.0552024776813895,
        "TimeMax": 2.0552024776813895
      }
    }
  ]
}

**Comment by MarjieAVolk** [comment]
Fixed - I also synced from master, so you will need to sync both master and svn
