### ISSUE TITLE
[0.9.0 staging-1287] UI: wrong bank account position on a tool bench

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14045]
Bank accouunt to Pay Craft Fee should be on the Crafting tab, but its on the Repair one
![bandicam 2019-12-06 14-18-34-134](https://user-images.githubusercontent.com/27898520/70311777-21a44080-1834-11ea-96be-41712da96bda.jpg)

**Comment by beastyn** [comment]
And don't forget to make it looks fine (add margins), please/ From ##14483

**Comment by WeaselDog** [comment]
It is on both Repair Tab & Credit Tab. Changing one does not change the other.
