### ISSUE TITLE
[0.9.0 staging] Civics: Law condition “When Matching Object” included in wrong triggers

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14049]
The “When Matching Object” trigger condition is included in triggers it shouldn’t be, resulting in the trigger failing if it is used. The debug message says the reason it failed is “< Missing >”. 

Here is an example law and resulting debug message:
![LawDroporPickup](https://user-images.githubusercontent.com/47330823/70346830-0fb2a580-1814-11ea-8bb1-d28c97a8b628.png)
![DropDebug](https://user-images.githubusercontent.com/47330823/70347964-8486df00-1816-11ea-82eb-cf5744f9c6a3.png)

Here is the list of laws that needs to be adjusted sorted by category that have all been tested with /civics debug:

**Construction:**
- Construct or Deconstruct
- Dig or Mine
- Drop or Pickup
- Plow
- Tamp Road (Also true for Matching Block)

**Contract:**
- Completed contract
- Failed Contract
- Joined Contract
- Posted Contract

**Economy:**
- Create Currency
- Inventory Action
- Mint Currency
- Trade

**Finance**
- Accepted Loan or Bond
- Defaulted on Loan or Bond
- Offered Loan or Bond
- Repaid Loan or Bond

**Harvesting** 
- Chop Stump
- Chop Tree
- Harvest or Hunt

**Work Party**
- Completed Work Party
- Joined Work Party
- Left Work Party
- Posted Work Party
- Worked For Work Party

**Comment by johnkslg** [comment]
Should be working in latest
![image](https://user-images.githubusercontent.com/3536496/70468389-db412280-1a7b-11ea-86c9-786edf9d3802.png)

**Comment by beastyn** [comment]
Hm, I think its about Workbench which should not be in the filter for this trigger at all. 
@WeaselDog correct me if Im wrong.

**Comment by WeaselDog** [comment]
Funny enough, the entire list is working now except Drop or Pickup. 
"When Matching Items" should not be included in that trigger because it is covered by Place or Pickup Object.

**Comment by beastyn** [comment]
Still here
![bandicam 2019-12-12 15-11-23-719](https://user-images.githubusercontent.com/27898520/70703323-ad651380-1cf1-11ea-9374-a6e70951ca1d.jpg)

**Comment by WeaselDog** [comment]
Main issue is fixed. The reopen will be addressed in https://github.com/StrangeLoopGames/EcoIssues/issues/14226
