### ISSUE TITLE
[0.9.0 staging-1287] Command "/civics spawngov" breaks election

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14043]
- start new server and use /civics spawngov. I have active consitution with election articles.
![image](https://user-images.githubusercontent.com/45708377/70307192-a9308600-1819-11ea-9e53-167c9d78ef37.png)
- try to add any new law: 
![image](https://user-images.githubusercontent.com/45708377/70307244-c8c7ae80-1819-11ea-9b27-5daa761c8b26.png)
- propose law. Law will actice without election.
![image](https://user-images.githubusercontent.com/45708377/70307318-f01e7b80-1819-11ea-82ee-e2961501f162.png)

**Comment by WeaselDog** [comment]
It was changed a couple days ago. Type "/civics spawngov true" to require elections.

**Comment by johnkslg** [comment]
^

**Comment by johnkslg** [comment]
the 'everyone can do so immediately' clause supercedes the election requirement, so it doesnt need an election.
