### ISSUE TITLE
[0.9.0 staging-1287] Sound of using tools when you select the wrong item

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14044]
Step for reproduce (for example):
- select axe
- highlight corn
- try to chop. You hear tree chopping sound.
![image](https://user-images.githubusercontent.com/45708377/70311262-5b6c4b80-1822-11ea-9a29-2770390b051a.png)
In 8.3.0 you heard "missing" sound.

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/72129328-df1bd980-3386-11ea-80ff-966cc897064b.png)

**Comment by beastyn** [comment]
Actually, it was about swing sound when interact with objects with any inappropriate took.
The idea with some default item sound is fun. (plant sound for plants, stone sound for rubbles)
But:
1.  Original problem is still here for world objects like tables. Workbench will use tool sound
2. Sound seems strange for objects like carved pumpkin ot doors. Its rather like stone hit kind.
3. For rubbles: machete has axe sound, sickle, scythe hoe - plant sound,

**Comment by Quadbro** [comment]
You move tool - you get swing sound, that's quite ok

**Comment by Quadbro** [comment]
For worldobjects we need to add "HitObjectType" to each world object prefab, and we can specify "ObjectType" there, that is used as audio descriptor. I definately need to handle thatm but it's a large pile of work

**Comment by Quadbro** [comment]
And about diff tools on diff objects - this is still wip, so i'll track this issue and add fixed label when it will be mostly ready
