### ISSUE TITLE
 [Staging-1287] Tool Bench Occupancy is Broken

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14058]
**Version:** 0.9.0.0 beta staging-1287

![snap5601](https://user-images.githubusercontent.com/29383891/70367463-1c78dd00-1898-11ea-8dc6-87eae85039fd.png)
![snap5602](https://user-images.githubusercontent.com/29383891/70367464-1c78dd00-1898-11ea-9c4b-a3e2babe7004.png)
![snap5603](https://user-images.githubusercontent.com/29383891/70367465-1d117380-1898-11ea-84b2-559617d77671.png)
![snap5604](https://user-images.githubusercontent.com/29383891/70367466-1d117380-1898-11ea-8c7f-b58cee1d8f3f.png)

**Comment by Conchipedia** [comment]
still doing this in [Staging 1355]

**Comment by Conchipedia** [comment]
still doing this in [Staging 1377]

**Comment by keegan-o** [comment]
fixed by https://github.com/StrangeLoopGames/Eco/pull/5639
