### ISSUE TITLE
[Staging-1287] Newly Created Singleplayer world No Trees are visible at all on First Load

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14056]
**Version:** 0.9.0.0 beta staging-1287

**Steps to Reproduce:**
Create a Singlplayer world, and enter, no Trees are Visible, after a short period (not sure exactly how long) baby trees will appear at 1% growth, Disconnecct and continue this world Trees are now mature and visible

**Expected behavior:**
Trees should be there at the start

**The following Two snapshots have Palms selected under Plant/Environment data and show in world)**
this Snapshot show First Creation
![snap5594](https://user-images.githubusercontent.com/29383891/70365854-82129c80-188b-11ea-8e5c-e85df5c7a083.png)

this snapshot shows Full mature Trees after disconnecting then clicking Continue
![snap5595](https://user-images.githubusercontent.com/29383891/70365875-9bb3e400-188b-11ea-86bd-f9b158f40802.png)

This shows what i see when checking a couple baby trees with soil sampler that appears before i disconnect and reload the world (for the first time this happened)
![snap5591](https://user-images.githubusercontent.com/29383891/70365962-0533f280-188c-11ea-9aeb-ae897a5a4fe9.png)
![snap5592](https://user-images.githubusercontent.com/29383891/70365964-07964c80-188c-11ea-9653-8bc56304642e.png)

reproduced this on another newly created world using this setting (same as i did for the first world)
![snap5596](https://user-images.githubusercontent.com/29383891/70366009-39a7ae80-188c-11ea-8898-8fe316a30ed3.png)

linking to this one as it does show sort of same thing
[0.9.0 staging-1287] Need to check trees models #14047

not sure if this is a Graphic bug with the trees as the **only** trees visible in the whole World are at 1% growth

**Comment by beastyn** [comment]
merge with this #14056

**Comment by Conchipedia** [comment]
did notice this again happened on 1st time on a new  Single player world, and fixing itself after Disconnect and then reloading world
[Staging 1309]
