### ISSUE TITLE
[0.9.0 staging] UI: Long property name string after seizing property

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14054]
Very low priority issue: After seizing property with either a law or executive action there is a long string for the property name. The property can be renamed by the new owner.

![SeizeExecutiveAction](https://user-images.githubusercontent.com/47330823/70362473-ed338300-1839-11ea-9e6a-e21d5a8b5f4b.png)
![SeizeLaw](https://user-images.githubusercontent.com/47330823/70362475-eefd4680-1839-11ea-9938-0d593eff53e9.png)

**Comment by serpopov** [comment]
Probably already fixed, could not reproduce
