### ISSUE TITLE
[Staging-1287] Stone machette doesn't gather Plant Fibers

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14057]
**Version:** 0.9.0.0 beta staging-1287

**Steps to Reproduce:**
Craft Stone machete, equip it and  use on Plant that shows Plant Fibers when looking at it
![snap5600](https://user-images.githubusercontent.com/29383891/70367229-f0f4f300-1895-11ea-847f-e8b4ece5d634.png)
**Expected behavior:**
expect it to gather plant Fibers

**Actual behavior:**
Destroys whatever plant you use it on and Both Durability and Calorie Usage Decrease as expected, just does not gather anything

**Comment by redwyre** [comment]
Machete destroys and doesn't collect.

I'm not sure what the screen tip is supposed to be in this case, @Quadbro ?

**Comment by beastyn** [comment]
merge with this one #13375
