### ISSUE TITLE
Support long user descriptions in laws

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14053]
![image](https://user-images.githubusercontent.com/3536496/70361981-3da9e100-1838-11ea-931b-f4cbe0d5a53f.png)
This dialog inherits the general layout which makes it hard to make the top frame expand to fit a long description.  I've got some changes coming in my latest PR to allow the entry of long text and have no blocks in the law, this is for 'custom text' laws that players could create.

**Comment by SlayksWood** [comment]
need to add the ability to complete text input.
For example:
Enter- complete input
Shift + Enter - move cursor to another line

**Comment by SlayksWood** [comment]
Issue fixed, i will add my comment as suggestion.
