### ISSUE TITLE
[0.9.0 staging-1290] Missing ParentRecipe for sign

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14069]
All the same recipes should in one:
1. Large Handing Sign:
![image](https://user-images.githubusercontent.com/45708377/70420527-fa8a8080-1a78-11ea-8249-9b9b1a441585.png)
2. Large Standing Sign:
![image](https://user-images.githubusercontent.com/45708377/70420772-78e72280-1a79-11ea-939b-009a0d105125.png)
3. Small Handing Sign.
4. Small Standing Sign.

**Comment by SlayksWood** [comment]
We haven't model for Wood Sign so delete possibility to craft it.

**Comment by Sekor2600** [comment]
It should not possible to craft this Signs. Function is missing. But will come later

**Comment by SlayksWood** [comment]
merged to #14203
