### ISSUE TITLE
[Staging-1287] Database Error Spam

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14068]
[log_191206084723.log](https://github.com/StrangeLoopGames/EcoIssues/files/3937057/log_191206084723.log)

**Comment by mirasrael** [comment]
@johnkslg Seems related to issue we discussed about maximum collection space size with custom stats.

**Comment by johnkslg** [comment]
@mirasrael I've seen this happen with migration, somehow the db gets flooded with names, I dont think its the new custom stat feature.  @D3nnis3n did you have any laws recording custom stats? can you attach your .db file?

**Comment by Deantwo** [comment]
No idea what "custom stats" are, so I doubt it.

I only made a few random test civics to try something.
See: http://95.217.35.61:3031/

**Comment by mirasrael** [comment]
@johnkslg yes, it happens after migration, because of changed action names (it has old stats + all new stats). So we can't use old database after migration. @D3nnis3n is this a case?

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/stuffed.zip

Please note that joining the server with that DB doesn't work due to this bug:
https://github.com/StrangeLoopGames/EcoIssues/issues/14066

The world has indeed been migrated from a prior staging version. (And for the first time that was actually "successful")

**Comment by D3nnis3n** [comment]
@mirasrael 
The world was created on staging-1278 and migrated to 1287. (If that is what you mean. It's not a migration from a non-staging version)

**Comment by johnkslg** [comment]
@mirasrael Can you help investigate this one?

**Comment by mirasrael** [comment]
@D3nnis3n do we still have this issue on latest builds?

**Comment by mirasrael** [comment]
Seems fixed.
