### ISSUE TITLE
0.9 tagged crafting provide unpredictable result

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14067]
My comment at https://github.com/StrangeLoopGames/EcoIssues/issues/13360#event-2833931336 ignored.

For example, in the worst case, you will get three stacks of hewn log instead of one when ordering 15 pieces.
You would expect one, or not?

Another example
"Charred Food"
descripted as 400 cal, 2\2\2\2 nutrients.
but...
You can receive a lot of different foods.
Like
Charred Heart of palm
450, 7\3\1\2
Charred tomato
510, 8\1\0\4
Charred papaya
460, 6\1\0\6
Charred Mushrooms
450, 3\6\2\2

This
is
annoying.

**Comment by SlayksWood** [comment]
Better delete CharredFood as item.

**Comment by elfl0rd** [comment]
> Better delete CharredFood as item.

In any case, this does not solve the problem with the unpredictable result of "simple" сraft.
