### ISSUE TITLE
Crops do not update their model as they grow.

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#1406]
As the plant grows, it doesn't usually update the model. However, when harvesting a nearby plant (fully grown, but still with a juvenile model), lots of nearby plant models will suddenly update to the correct model.

**Comment by SeanAtr0n** [comment]
confirmed still an issue in 5.6 staging

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2742/plant-growth

**Comment by elfl0rd** [comment]
@D3nnis3n looks fixed :D
