### ISSUE TITLE
[0.9.0 staging-1287] Empty Demographic

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#14064]
It is seemingly possible to propose a new demographic that is empty. This makes little sense.

![image](https://user-images.githubusercontent.com/2676134/70389751-e3d62200-19c3-11ea-93d6-350dadcbb7bc.png)
http://95.217.35.61:3031/elections.html?election=2

**Comment by johnkslg** [comment]
It now is invalid if you leave it blank:
![image](https://user-images.githubusercontent.com/3536496/70481388-4a784000-1a97-11ea-953f-f718aff51b72.png)
