### ISSUE TITLE
Ramps should have connection to ground.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14076]
Just look at this nasty things...
![изображение](https://user-images.githubusercontent.com/4980243/70460286-000eb780-1ac7-11ea-981d-e4bc3f7b251d.png)
![изображение](https://user-images.githubusercontent.com/4980243/70460301-07ce5c00-1ac7-11ea-8520-059bd2fff118.png)
![изображение](https://user-images.githubusercontent.com/4980243/70460325-1452b480-1ac7-11ea-80a7-daeb1845fb25.png)

This is not vital, but will significantly improve both perception (in many cases) and quality of life.

**Comment by SlayksWood** [comment]
dup #9668
