### ISSUE TITLE
0.9 some "tagged craft"s not usefull

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14077]
E.g. "craft basic Tool", this reciepe not have "order", in any case you need select tool from list.
I prefer old way, all recipes in main list in this case.
![изображение](https://user-images.githubusercontent.com/4980243/70460959-95f71200-1ac8-11ea-83d1-2d132175f476.png)
![изображение](https://user-images.githubusercontent.com/4980243/70460968-9b545c80-1ac8-11ea-98c9-1ed321ac4e0d.png)
Because it just adds an extra step.

In addition, the consolidation of recipes produces too much confusion.
https://github.com/StrangeLoopGames/EcoIssues/issues/14061
https://github.com/StrangeLoopGames/EcoIssues/issues/14067
https://github.com/StrangeLoopGames/EcoIssues/issues/13378
etc...

I'm trying to figure out a solution, but even if it does, i think you cannot make it at 0.9.

**Comment by mirasrael** [comment]
@Sekor2600 @WeaselDog can you split this into separate recipes as part of your tools refactoring?

**Comment by WeaselDog** [comment]
Stone tools separated, Recurve Bow removed from Steel Tools
