### ISSUE TITLE
[0.9.0 staging-1290] Should we delete Small Table, Table, Chair?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14072]
![image](https://user-images.githubusercontent.com/45708377/70425813-eba8cb80-1a82-11ea-8612-093fbe848338.png)

**Comment by elfl0rd** [comment]
afaik old table, chair, etc are deprecated, they are replaced by new (e.g. hewn table)

**Comment by SlayksWood** [comment]
@craig-jong 
Can we lower skill Value for old furniture like Small table, table and chair and add possibility to craft it without Hewing? Or we should delete it?

**Comment by WeaselDog** [comment]
Table has always been able be made by everyone. It was recently changed to require Hewing.
