### ISSUE TITLE
[0.9.0 staging-1291] Tomato is used both in Vegetable and Fruit

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14083]
![image](https://user-images.githubusercontent.com/45708377/70500677-2cf5b580-1b2d-11ea-9a0e-f23d0b91790a.png)
![image](https://user-images.githubusercontent.com/45708377/70500711-40a11c00-1b2d-11ea-94df-dcc3cf94087e.png)

**Comment by WeaselDog** [comment]
Heh technically it is a fruit but for culinary purpose it is used like a vegetable.
