### ISSUE TITLE
[0.9.0 staging-1291] Wrong recipes in Bakery Oven.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14084]
- [x] 1. Baked Meat use 10 tagged items (t.i.) "Meat" instead 5 Raw Meat in 8.3.0:

![image](https://user-images.githubusercontent.com/45708377/70504261-6da5fc80-1b36-11ea-89c0-25016e830e66.png)
If you decide to increase the cost of the recipe and use more expensive meat, you should not combine in t.i. "Meat" meat with different values. You must use only Prepared Meat or only Prime Cut. The difference in their crafting is almost 4 times.
![image](https://user-images.githubusercontent.com/45708377/70504408-ca091c00-1b36-11ea-8ce3-1a0a29dd2d92.png)
For crafting Baked Meat you used only Meat, but Nutriens we have with Carbs and Vitamins:
![image](https://user-images.githubusercontent.com/45708377/70504632-2b30ef80-1b37-11ea-9103-9c0f08c0b91d.png)
In 8.3.0 we have only Fat and Protein:
![image](https://user-images.githubusercontent.com/45708377/70504728-60d5d880-1b37-11ea-9ed1-b15ff6bfb6b2.png)
Or Add some Vegatable to craft or change Nutriens.

- [x] 2. Baked Roast. We have another recipe in 0.9.0 staging-1291. The recipe contains only meat:
![image](https://user-images.githubusercontent.com/45708377/70504901-c1fdac00-1b37-11ea-983b-75e89875b28b.png)
I think we should return something like old recipe:
![image](https://user-images.githubusercontent.com/45708377/70504992-f2dde100-1b37-11ea-8b18-a38f46925647.png)
You can use t.i "Vegetable", "Greens" inseat Fiddleheads, Corn.

- [x] 3. Many new Baked Vegatable recipes have been added. But the nutrients in new recipes are used as in Baked Agave (Carbs:12, Protein:2, Fat:6, Vitamins:8.). It is necessary to change nutrients for Baked Vegatable, Baked Beet, Baked Corn, Baked Heart of Palm, Baked Taro, Baked Tomato.

- [x] 4. Same for Fruit Muffin. The Nutriens used as in Huckleberry Muffin (Carbs:10, Protein:5, Fat:4, Vitamins:11.). It is necessary to change nutrients for Fruit Muffin, Papaya Muffin, Pumpkin Muffin.

- [x] 5. Huckleberry Pie. Use t.i "Fat" instead Tallow.

- [x] 6. You add new recipe Leavened Dough but it's never used. I suppose that you plan to use it in recipes like Bread, Camas Bread, may be Elk Wellington and Macaroons, and may be for new recipes in future. I think it needs to move it to Advanced Baking. Because all recipes where it can be used in Advanced Baking. 
With this in mind, you need to review the ingredients for these recipes: Bread, Camas Bread, Elk Wellington and Macaroons.

- [x] 7. Meat Pie. Use t.i "Fat" instead Tallow.

- [x] 8. Change nutriens for Pastry, Fruit Tart and Pirozhki (It is in the plural. Better use as "Pirozhok"). Now it used Bearclaw nutriens.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/71083452-1d691300-21a4-11ea-8d04-9aa1654a14e6.png)
Still need to increase Fat and Protein

**Comment by Sekor2600** [comment]
merge with https://github.com/StrangeLoopGames/EcoIssues/issues/14088
