### ISSUE TITLE
[5.5.4] Standard shovel can pick up 2 dirt from units with 2 inventories

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#1408]
A shortcut to get dirt from a container is to left-click on it while holding a shovel. However, if you do this with a storage item with two inventories, such as a workbench, while you have a piece of dirt in both the private and public inventories, both pieces of dirt will be placed on the shovel as a 2-stack.

**Comment by metachronism** [comment]
no longer relevant with 5.6 link component changes.
