### ISSUE TITLE
[0.9.0 staging-1291] Civics: Ui is broken 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14085]
in Government Office ans Executive office
![bandicam 2019-12-10 13-58-40-789](https://user-images.githubusercontent.com/27898520/70517281-26316780-1b5a-11ea-91b9-e4df9b7957d0.jpg)
![bandicam 2019-12-10 13-10-30-796](https://user-images.githubusercontent.com/27898520/70517282-26316780-1b5a-11ea-9d9a-c2a42a485e9f.jpg)

@johnkslg may know the cause

**Comment by serpopov** [comment]
hotfix, further changes via StrangeLoopGames/EcoIssues/issues/14082

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/70603257-29cef800-1c07-11ea-8e4f-6021820d71e2.png)
Title isn't centered

**Comment by SlayksWood** [comment]
merged to #14082
