### ISSUE TITLE
0.9 audio: "wood chop" sound while sickle using

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14093]

**Comment by elfl0rd** [comment]
when you use a sickle, you hear two sounds in order, a "wood chop" and a "sickle sound".

**Comment by WeaselDog** [comment]
This is an issue for Stone Sickle & Modern Scythe.
Steel Sickle, Steel Scythe, and Iron Scythe all sound like pickaxe.
I can update this list: https://github.com/StrangeLoopGames/EcoIssues/issues/13726
