### ISSUE TITLE
Skill points per day resets to 0.0 on re log 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1409]
http://ecoforum.strangeloopgames.com/topic/2266/skill-points-per-day-resets-to-0-0-on-re-log

**Comment by MarjieAVolk** [comment]
Sounds like this might be related to the big stomach skill

**Comment by MarjieAVolk** [comment]
FWIW, just encountered this.  Didn't have the big stomach skill
