### ISSUE TITLE
Lot of aliasing on minimap globe

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14098]
![image](https://user-images.githubusercontent.com/3536496/70577278-cd64cd80-1b5f-11ea-9017-b466fa7a725b.png)
@redwyre perhaps have ideas for fixing?

**Comment by redwyre** [comment]
on the ring around it, or the map itself?

**Comment by johnkslg** [comment]
@redwyre on the globe
Pulling this back because its just a matter of propagating the anti-alias settings to the minimap camera

**Comment by redwyre** [comment]
It might be possible to just always use AA on the minimap now because it's forward rendered, but another option would be to just render it at 2x and scale it down though I don't think @mirasrael was a fan of that idea...

**Comment by mirasrael** [comment]
I'm ok if it won't affect performance in any way.
