### ISSUE TITLE
Generated Sound Banks keeps wanting to check in

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14097]
![image](https://user-images.githubusercontent.com/3536496/70576978-19fbd900-1b5f-11ea-9000-2c629b7de249.png)

Figure out a solution so this doesnt appear if you're not working on sound (perhaps .gitignore)

**Comment by redwyre** [comment]
I checked in the meta files and ignored the folders, _but_ the entire contents of the StreamingAssets folder ends up in the final build, so we'll have to change that.
