### ISSUE TITLE
Imposters a little mushy

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14103]
![image](https://user-images.githubusercontent.com/3536496/70579712-4830e700-1b66-11ea-894e-ef69d1131751.png)
Issue with configuration? They were looking much more convincing in your examples with chests

**Comment by keegan-o** [comment]
I went through and toned down the distances at which they all switch to 7% or 6% in some cases, so they're less aggressive. They'll never look good up close, as they're specifically designed to be seen only far away. I think the new settings I have them on in staging are better. Also fixed some missing renderers.

**Comment by keegan-o** [comment]
I went through and massively pushed out LODs so that the game looks acceptable at the lowest LOD setting, this should be much less of an issue now.
