### ISSUE TITLE
Chat + tutorial feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14101]
Looking great! Some minor points:
- [x] Make open and close faster by 2x - 3x
- [x] Make the delete message 'x' button appear only when mousing over. 
![image](https://user-images.githubusercontent.com/3536496/70578688-621cfa80-1b63-11ea-8e55-33ea41a64f05.png)
- [x] Make margins on all sides match
- [x] When expanding notifications, make it come out of the bell
![image](https://user-images.githubusercontent.com/3536496/70578732-752fca80-1b63-11ea-91bc-041fb9ef0f91.png)
- [x] Clicking a tutorial icon while another is open should close that old one and open the new one simultaneously. Currently you have to click it twice. 
- [x] When switching between work and notification views, start the lerp for the other one while the old one is closing. 

![image](https://user-images.githubusercontent.com/3536496/70578890-dfe10600-1b63-11ea-9862-c6f100998c82.png)
- [x] Fix margins, bottom is too large.

![image](https://user-images.githubusercontent.com/3536496/70578927-f4bd9980-1b63-11ea-9b38-54a054478592.png)
- [ ] Art change: can the sliding piece come out of this top corner, so the corner itself moves?  That will reflect this other part of the UI that unfolds:
![image](https://user-images.githubusercontent.com/3536496/70578950-09019680-1b64-11ea-83ab-77d84f040c02.png)
![image](https://user-images.githubusercontent.com/3536496/70578962-11f26800-1b64-11ea-81f2-b449c5c4c081.png)

![image](https://user-images.githubusercontent.com/3536496/70579022-3c442580-1b64-11ea-9e6a-254968406ecd.png)
- [x] Margins still too big, and I can only see one notification when its shrunk.  Make them lined right on top of each other, and it should show 5 lines of notifications at the top.
- [x] Chat at top is missing categories. Should show the categories when you mouse over them.

**Comment by johnkslg** [comment]
(dont worry about funny color, I use screen dimmer which reflects in screenshots)

**Comment by SlayksWood** [comment]
see #13101 when you will rework sliding piece.

**Comment by SlayksWood** [comment]
and #14184
