### ISSUE TITLE
Ecopedia strobe effect works on sub pages but not pages or categories

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14104]
Make it share the same code for all three and do the cool highlighting (and cool sound which we'll add).  
![animx22](https://user-images.githubusercontent.com/3536496/70580029-4156a400-1b67-11ea-903a-2e0f2fa4d61e.gif)

**Comment by beastyn** [comment]
Not sure if its related, but will add here.
When you are choosing subcatgory, effect is working on the items too.
(eg. choosing material in Block will make running highlight on items too)
![994b244d65c2467cec5bd5ac45bdc72b (1)](https://user-images.githubusercontent.com/27898520/71611686-d6741800-2bbc-11ea-8157-d8083f97815f.gif)
And selection is running from the empty part.
![bandicam 2019-12-31 11-02-15-004](https://user-images.githubusercontent.com/27898520/71611702-07ece380-2bbd-11ea-838b-6e4dab5ea514.jpg)
