### ISSUE TITLE
[0.9.0] ExportServer.bat broken

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14118]
The ExportServer.bat is broken.

It exports the Mods,Webclient and Config but no Exe or sh File

Same with the ExportDebugServer

**Comment by beastyn** [comment]
still not there

**Comment by gzatravkin** [comment]
Spoke with @redwyre 
This file needs to me in this way for jenkins to build.
To run it locally you need to publish project by doing 

msbuild /restore /t:Publish /p:Configuration=Release /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:TargetFramework=netcoreapp3.0 ./Server/Eco.Server

**Comment by gzatravkin** [comment]
What for you tried to used it locally? Is it for devs?

**Comment by Sekor2600** [comment]
Hi this is new then In the Past the ExportServer did create the Serverfile local. Sometimes I tried to 
 startcreate servers with small changes. Instead of creating serverfilesagain and again with Visual

**Comment by redwyre** [comment]
@Sekor2600 This file is used as part of the build process, which is a bit more complicated than 0.8.3 because of the new single exe packaging. Why are you running this script locally? Are you just trying to package up the server for your own use?

**Comment by Sekor2600** [comment]
Ok 8.3 always started the server with it. Always starting Visual just because of changes in Modfolder was a bit troblesome. When this is changed there is no problem. Only new this with 8.3 or before version.

**Comment by gzatravkin** [comment]
@mirasrael what you think, is it worth to add another .bat? So it will work with current local version. https://github.com/StrangeLoopGames/Eco/blob/acf47b460242ce03ef06ef4315d460f3b1ac2bff/Server/ExportServer.bat here is a version of .bat which should work

**Comment by beastyn** [comment]
@mirasrael need your opinion

**Comment by redwyre** [comment]
This change broke the build. I've updated Tools\Build_EcoServer.ps1 and added Tools\Build_ExportServer.ps1 to allow the server to be built and exported locally.

**Comment by beastyn** [comment]
hmhm, still won't work for me.
@redwyre something with routes maybe? I don't have \win-x86\publish\ folders

**Comment by redwyre** [comment]
You'll need to run Tools\Build_EcoServer.ps1 first

**Comment by redwyre** [comment]
@beastyn did you try again?

**Comment by beastyn** [comment]
@redwyre 
Still doesn't work for me

**Comment by mirasrael** [comment]
Works for me. @beastyn you need to have "MSBuild.ex" in your PATH environment variable.
