### ISSUE TITLE
[0.9.0 standing-1292] Animals: Speed and animation synchronization

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14119]
![2019 12 11 Bison walks strange](https://user-images.githubusercontent.com/45708377/70619222-9953e000-1c25-11ea-8c70-9852d1462094.gif)

**Comment by beastyn** [comment]
Saw it again.
[0.9.0 staging-1183]
https://i.gyazo.com/7f9c23fbe8e428d5169e8827bb5f9aa3.gif

**Comment by SlayksWood** [comment]
It got a lot better. But still an issue.
When moving, the supporting leg should be in place, but it makes a small shift back. We have the effect of "stomping on spot"
![image](https://user-images.githubusercontent.com/45708377/73914211-dc4ece80-48c9-11ea-80ad-511545af70e5.png)
![2020 02 06 Bison walk](https://user-images.githubusercontent.com/45708377/73915703-f342f000-48cc-11ea-8c09-b53dba0d5d6d.gif)

**Comment by elfl0rd** [comment]
It's especially ugly for fast animals.

https://youtu.be/7F8ZPTgHxx0
