### ISSUE TITLE
[0.9.0 staging-1292] Top Notification: can't read the last message

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14116]
Just won't show the last message properly.
![bandicam 2019-12-11 11-29-27-003](https://user-images.githubusercontent.com/27898520/70608423-edf55c00-1c21-11ea-8bd8-8c67bced4d88.jpg)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/71816022-61a84e80-3092-11ea-9e21-3025c41567c8.png)
