### ISSUE TITLE
[0.9.0 staging] Tags: Item selection filter includes Specialties & Professions

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14124]
When pulling up the item selection for things like stores & laws, the list includes includes specialties when it shouldn't. This example is a store’s sale list:
![ItemFilterSelection](https://user-images.githubusercontent.com/47330823/70636153-e74af280-1be9-11ea-8cb1-f60bbe1f698f.png)

 When you click “Show Undiscovered”, other odd selections appear like hidden items, avatar body parts, & UI elements (Chat Log)

**Comment by elfl0rd** [comment]
old issue...

**Comment by beastyn** [comment]
dup #13682
