### ISSUE TITLE
Cant select workbench

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14128]
Drop a workbench among some plants after starting a world, cant select it:
![image](https://user-images.githubusercontent.com/3536496/70680994-b6e96f80-1c4e-11ea-8ba0-aee20a1d9f07.png)

If I get under it I can:
![image](https://user-images.githubusercontent.com/3536496/70681000-c10b6e00-1c4e-11ea-8360-7fc8a5821d73.png)

Probably something weird with collision.

**Comment by SlayksWood** [comment]
For me It can happen only at new server if you join and place workbech at once.

**Comment by johnkslg** [comment]
Havent noticed in awhile. I think it's fixed.
