### ISSUE TITLE
Ecopedia page 'viewed' state should not be shown or tracked for sub-pages

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14126]
The role of highlighting unread ecopedia pages is to advise the player on things they havent viewed yet. However, for the items in the game, it doesnt make sense that they would read each one, so the 'viewed' state just serves as a distraction and clutters up the visuals (and sets off OCD when some are scattered around viewed and others not).  Only display viewed state on pages.

**Comment by beastyn** [comment]
"Lists" category won't mark viewed pages
![3acd391f6cf6b95b8a01b8f8e24a8e41](https://user-images.githubusercontent.com/27898520/71645072-581a9180-2cf4-11ea-86e1-91c8ab2d7147.gif)
