### ISSUE TITLE
[0.8.3] Chat: Allocation message goes into wrong channel

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14125]
There is an issue the allocations message for the player receiving the allocation goes into #General chat channel. A popular law is to reward for clearing tree debris, but it creates unavoidable spam for the logger in the general channel. The allocation message should go into "MyTrades", "Government", or "Transfers".

It is still an issue in 0.9.0 staging:
![GeneralChat](https://user-images.githubusercontent.com/47330823/70638562-f5027700-1bed-11ea-853d-ace3454c3b58.png)

**Comment by beastyn** [comment]
Now you can see this message only in Finance
![bandicam 2020-12-24 17-39-49-092](https://user-images.githubusercontent.com/27898520/103089258-4f128680-460f-11eb-8df0-d1997eb18efd.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop-176

Tested logs for finance, government, and tax. All are appearing only to their respective channels including notifications. 

Closing.
