### ISSUE TITLE
[0.9.0 staging] Chat: Avatar parts included in message for starting items

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14123]
The avatar body parts, like Rounded Face, are now included in the starter message when joining a server.

![StartingItems](https://user-images.githubusercontent.com/47330823/70632364-84565d00-1be3-11ea-8409-4b0b23062052.png)

**Comment by SlayksWood** [comment]
Can't check it, starter message is missing at all 
![image](https://user-images.githubusercontent.com/45708377/107741076-85ba7280-6d1d-11eb-9c0d-704570f108e6.png)

**Comment by WeaselDog** [comment]
It is not a tech tree issue

**Comment by SlayksWood** [comment]
was merged to 9.4

**Comment by TwixterZ** [comment]
fixed as of 9.4 develop 243

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/beb7bf6a-4adf-496d-821b-ebc032363757)
