### ISSUE TITLE
0.9 objectives show not all players 

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14122]
(without players joined before restart?)
![изображение](https://user-images.githubusercontent.com/4980243/70625448-703a4c00-1c33-11ea-8982-cdad6375edf6.png)
![изображение](https://user-images.githubusercontent.com/4980243/70625536-a4ae0800-1c33-11ea-9195-0f02de4e1ed9.png)

**Comment by SlayksWood** [comment]
> (without players joined before restart?)
> ![изображение](https://user-images.githubusercontent.com/4980243/70625448-703a4c00-1c33-11ea-8982-cdad6375edf6.png)
> ![изображение](https://user-images.githubusercontent.com/4980243/70625536-a4ae0800-1c33-11ea-9195-0f02de4e1ed9.png)

**Comment by SlayksWood** [comment]
dup #11432
