### ISSUE TITLE
[0.9.0 staging-1293] Can't vote for candidate with nickname like !"#$%&'()

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14132]
- change name to **!"#$%&'()**
- start game, join to server (first time)
- check your nickname in game:
![image](https://user-images.githubusercontent.com/45708377/70707004-32e3c600-1ce8-11ea-9b58-8739d88786ec.png)
- spawn civics. add elected title, start election, enter election.
- Press vote. Try to vote for !"#$%&'() candidate. You can't:
![image](https://user-images.githubusercontent.com/45708377/70707120-7cccac00-1ce8-11ea-9505-83afce907637.png)
In error write wrong name: without **()** 
![image](https://user-images.githubusercontent.com/45708377/70707250-c9b08280-1ce8-11ea-80c3-9785989d93a3.png)

**Comment by SlayksWood** [comment]
if you write /civics winelection Client will crash.

**Comment by SlayksWood** [comment]
From 14241
> [WEB]
> At current elections screen if a player has special characters in name, the data tag is enclosed the wrong way
> For example "Ceviel D'Ark" gets broken up at the apostrophe, resulting in a javascript error and the voting page does displayed
> 
> ![image](https://user-images.githubusercontent.com/6756505/71467347-db9f2480-27c2-11ea-80ea-de0cb2516bc4.png)
> 
> ECO version - Alpha 0.8.3.1
> Expected behavior - A "current election" page displayed, where we can vote for elections
> Actual behavior - The current election" page is blank, javascript error on console (screenshot)
> Steps to Reproduce - Have a player with an apostrophe in name "run for office"
> Operating system or web browser - Google Chrome 79.0.3945.88

**Comment by beastyn** [comment]
@johnkslg  Not sure if its OK just cut the, off, as some languages use them.
@D3nnis3n  what do you think

**Comment by SlayksWood** [comment]
I can't vote anymore with any nickname.

**Comment by SlayksWood** [comment]
from #15517
> js console output:
> `Error: Syntax error, unrecognized expression: .current-rankings table tr[data-voter='Mrs.Pron'ka'] td`
> Place: Election.js:1009
> Code line: `$(".current-rankings table tr[data-voter='" + data[i].Voter + "'] td").each(function(){`
> 
> Need escape quotesymbol in player nickname.
> 
> Screenshot: https://i.imgur.com/NZNN5au.png
> 
> Eco version: 8.3.3

**Comment by SlayksWood** [comment]
> ![image](https://user-images.githubusercontent.com/40701885/81873267-5fc33000-9549-11ea-8ed8-8415425b493c.png)
> 
> This users Steam name has a comma in it, and it isn't escaped, causing the page to break.
> 
> Edit: To clarify, this is on the "Current Elections" page.

**Comment by beastyn** [comment]
Well, I was testing with !"#$%&'() name
And I  do not exist!

![unknown (24)](https://user-images.githubusercontent.com/27898520/88904525-9e29da80-d26e-11ea-8aa3-83e3d34748f4.png)

**Comment by denysaw** [comment]
@gzatravkin Hey! Don't you wanna take over this one? Seems also server interaction. Would be a nice help!
