### ISSUE TITLE
[0.9.0 staging-1293] Civics: District map amendment drafts break the districts

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14138]
When making an amendment to a district map, the draft will replace the original district before it is even proposed. If you delete the draft without proposing, it will delete all the districts in the original map. The deleted districts also show up in the law filter for districts.

To replicate this:

- Pass any district map
- Open draft for amendment to District Map and close draft. At this point the active districts are replaced with a draft
![DraftAmmendment](https://user-images.githubusercontent.com/47330823/70766348-53c11100-1d12-11ea-89aa-88a6da8e800e.png)

- Delete the draft. All the districts are now deleted.
![DistrictMiniMap](https://user-images.githubusercontent.com/47330823/70766147-b665dd00-1d11-11ea-938c-563273ff07d0.png)
![DistrictsDeleted](https://user-images.githubusercontent.com/47330823/70766151-b8c83700-1d11-11ea-8e47-ff8f726c1ef0.png)
![DistrictFilter](https://user-images.githubusercontent.com/47330823/70766156-bd8ceb00-1d11-11ea-9949-9f86c56223a3.png)

**Comment by johnkslg** [comment]
Good find!
Fixed this and added a bunch of extra niceties.

Civics elements now track their history so you can see how they got put there and what they revise:
![image](https://user-images.githubusercontent.com/3536496/71860902-557bbb80-30a9-11ea-8160-029514b4ad92.png)

You can now view civic objects read-only, and this is available to anyone, so if you dont have permission to edit something you can still look:
![image](https://user-images.githubusercontent.com/3536496/71860971-80fea600-30a9-11ea-9ece-9137a1330c63.png)
![image](https://user-images.githubusercontent.com/3536496/71860994-9542a300-30a9-11ea-8aee-c845abe012b7.png)
Clicking the magnifying glass will open a read-only view:
![image](https://user-images.githubusercontent.com/3536496/71860983-8c51d180-30a9-11ea-8f6d-abecca12ed39.png)
Also implemented this for other civics objects, not just districts:
![image](https://user-images.githubusercontent.com/3536496/71861009-a2f82880-30a9-11ea-96ba-b6fda1c439c6.png)
![image](https://user-images.githubusercontent.com/3536496/71861019-ae4b5400-30a9-11ea-9b59-0765186141d7.png)
(theres a bug in that still ill fix next, garbage can still clickable)

**Comment by johnkslg** [comment]
Good find!
Fixed this and added a bunch of extra niceties.

Civics elements now track their history so you can see how they got put there and what they revise:
![image](https://user-images.githubusercontent.com/3536496/71860902-557bbb80-30a9-11ea-8160-029514b4ad92.png)

You can now view civic objects read-only, and this is available to anyone, so if you dont have permission to edit something you can still look:
![image](https://user-images.githubusercontent.com/3536496/71860971-80fea600-30a9-11ea-9ece-9137a1330c63.png)
![image](https://user-images.githubusercontent.com/3536496/71860994-9542a300-30a9-11ea-8aee-c845abe012b7.png)
Clicking the magnifying glass will open a read-only view:
![image](https://user-images.githubusercontent.com/3536496/71860983-8c51d180-30a9-11ea-8f6d-abecca12ed39.png)
Also implemented this for other civics objects, not just districts:
![image](https://user-images.githubusercontent.com/3536496/71861009-a2f82880-30a9-11ea-96ba-b6fda1c439c6.png)
![image](https://user-images.githubusercontent.com/3536496/71861019-ae4b5400-30a9-11ea-9b59-0765186141d7.png)
(theres a bug in that still ill fix next, garbage can still clickable)

**Comment by beastyn** [comment]
@johnkslg  If someone in edit mode, should I see the map in read-only with the view button?
It writes for me the same error, that I can't open a map.
![46b9f6e2fc62bb94e9925b5ddc5a116a](https://user-images.githubusercontent.com/27898520/71973142-f4cabb00-322f-11ea-9493-65caa15b16f0.gif)

**Comment by WeaselDog** [comment]
You should not be able to see another player's draft before it is proposed. Currently you can even delete a draft someone else is working on before it is proposed.

**Comment by beastyn** [comment]
Ok. I think I will make separate issue with some functinality questions
