### ISSUE TITLE
[0.9.0 staging-1293] Civics: Inventory Action trigger issues

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14136]
- [x] The law is only triggered when you "Put" items into a storage container. It is not triggered by "Take" actions and there is no /civics debug message for those actions.

- [x] There is no longer a way to restrict the Inventory Action law trigger to a particular item, like Tailings.  This issue is just related to law creation because the /civics debug message recognizes the item that moved. The trigger should have a "When Matching Items" condition so it can be used as intended.

![InventoryActionLaw](https://user-images.githubusercontent.com/47330823/70738792-4ed86f00-1cca-11ea-9eab-213c5483a76f.png)
Debug Message:
![InventoryActionItem](https://user-images.githubusercontent.com/47330823/70738802-526bf600-1cca-11ea-84fb-a7ed2cdff89e.png)

**Comment by johnkslg** [comment]
Fixed both
![image](https://user-images.githubusercontent.com/3536496/71922749-66c3d700-3140-11ea-823b-60e0ecc54532.png)
![image](https://user-images.githubusercontent.com/3536496/71922811-86f39600-3140-11ea-9afc-1b97180f4261.png)
![image](https://user-images.githubusercontent.com/3536496/71922829-92df5800-3140-11ea-8868-187ca1aac073.png)
![image](https://user-images.githubusercontent.com/3536496/71922886-aee2f980-3140-11ea-8d25-105e92589901.png)

**Comment by SlayksWood** [comment]
1. You can select specialty in Item moved:
![image](https://user-images.githubusercontent.com/45708377/71958282-f6c95580-3200-11ea-854c-87f9e12a16f3.png)
2. Target inventory seems doesn;t work or I don't right understand how ot should work:
![image](https://user-images.githubusercontent.com/45708377/71958430-59baec80-3201-11ea-8a52-938b801c4ee4.png)

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/72020219-263b8a80-3220-11ea-894f-fbb3a947a8ff.png)

Trade action also had this problem, fixed that too.
![image](https://user-images.githubusercontent.com/3536496/72020250-39e6f100-3220-11ea-9ee2-3d1431b85f54.png)
