### ISSUE TITLE
Need query to get admin usernames

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1413]
we need it to hide classroom discussions from non-admins
plus probably other features will need it.

**Comment by MarjieAVolk** [comment]
Related question - do you want me to change the analysis queries so that you need to authenticate in order to get response?  i.e. add username and auth token as parameters?  Or is that just going to mess you up at this point?

**Comment by MarjieAVolk** [comment]
Done on teacher tools branch

**Comment by MarjieAVolk** [comment]
the query is in Root: /isadmin/{username}
