### ISSUE TITLE
0.9 markers menu out from screen

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14131]
As result - you cannot disable markers if you have more than 3.
3
![изображение](https://user-images.githubusercontent.com/4980243/70694222-25224680-1cd0-11ea-9b41-901eb09fab61.png)
and 4
buttons and next markers totally unavailable
![изображение](https://user-images.githubusercontent.com/4980243/70694265-3c613400-1cd0-11ea-8aff-e8aceb6cd7cb.png)

Maybe just move markers menu to settings menu?

**Comment by SlayksWood** [comment]
dup #13672
