### ISSUE TITLE
[0.9.0 staging-1295] UI: Map filter includes nonexistent "Forest" biome

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14144]
The map filter for Environment Data includes "Forest Biome" but this is not a biome. It should be removed from the list.

![ForestBiome](https://user-images.githubusercontent.com/47330823/70826680-641dce00-1d9c-11ea-8298-171e24af7b6e.png)

**Comment by SlayksWood** [comment]
Forest biome is left from earlier versions. People can play in eco for a long time. And after migrate their world should have Forest biome. In 0.9.0 we have same thing like Log. You can't get it in 0.9.0 but you still can use it because you can have it from 0.8.3.
I think this intented behavior.

**Comment by WeaselDog** [comment]
There was no Forest biome in 0.8.3 either. Maybe it was last used in 0.7.x

**Comment by SlayksWood** [comment]
Start server at 0.7.8.9:
![image](https://user-images.githubusercontent.com/45708377/71248565-300e5400-232c-11ea-95e5-e247722a3a39.png)
Migrate to 0.8.0.7. Still have Forest biome:
![image](https://user-images.githubusercontent.com/45708377/71249204-ae1f2a80-232d-11ea-8a64-b6a7c827c695.png)
Migrate to 0.8.3.1:
![image](https://user-images.githubusercontent.com/45708377/71249423-2685eb80-232e-11ea-9b65-37d565b78ea7.png)
Migrate to 0.9.0.0 staging-1304:
![image](https://user-images.githubusercontent.com/45708377/71250017-aa8ca300-232f-11ea-8b0f-3184e10bfecf.png)
While we support migration, this biome should be displayed. Closed for now.
