### ISSUE TITLE
[8.3.0] Changing Toogle Mouse Option to leftclick makes the game unplayable

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14146]
> Hey there,
> Just started up the game on my computer and went about adjusting my controls like I do with any game. Only issue was that I accidentally set the Toggle Mouse option and bound it to left click. When I then tried to click to change it back, it force quit the pause menu. Since my left click is now the toggle mouse button I cannot access any menus for changing settings or controls, nor can I play the game. I tried uninstalling and reinstalling the game but the controls didn't reset. I am currently unable to play the game at all because of this seemingly small but gamebreaking bug, which is disappointing since I have enjoyed watching the game on youtube and playing it for the little time that I was able before it broke.
> Hoping someone could help me out in fixing this problem so I can go back to playing the game, and I highly suggest working a fix to this issue so it doesn't happen to others in the future.

**Comment by SlayksWood** [comment]
dup #12786

**Comment by WeaselDog** [comment]
In the short term they can be advised to delete inputManager.cfg from Users/[accountname]/AppData/LocalLow/Strange Loop Games/Eco

**Comment by SlayksWood** [comment]
merged with #12786

**Comment by D3nnis3n** [comment]
But both are open? lol
