### ISSUE TITLE
[0.9.0 staging-1297] Civics: Tax effect is doubled

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14149]
1. Make a law like this
![bandicam 2019-12-16 15-54-55-911](https://user-images.githubusercontent.com/27898520/70902196-13b5a300-201e-11ea-891b-53c4c4492dc5.jpg)
2. Claim one rect.
Tax will be collected two times.
![bandicam 2019-12-16 16-09-46-171](https://user-images.githubusercontent.com/27898520/70902399-81fa6580-201e-11ea-9c1d-ee48dcd39e27.jpg)

Was checked with Construct trigger. Effect is the same.

**Comment by WeaselDog** [comment]
It also happens with simple Send Chat tax so it seems all taxes are affected
