### ISSUE TITLE
[0.9.0 staging-1293] Notifications don't tell you about needing in Labor.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14142]
Step to reproduce:
- spawn Workbench, Stockpile. Add 16 Birch Log to stockpile.
- start Bow order. See notification:
![image](https://user-images.githubusercontent.com/45708377/70796948-76a40180-1db4-11ea-95b0-36e38205b2b5.png)
But first of all I need Labor.
Another problem if you have all resourses but no labor you can't see any notifications about it.
Step to reproduce:
- spawn Workbench, Stockpile. Add all ingredients for Bow projects (16 Birch Log and 30 Plant Fiber).
![image](https://user-images.githubusercontent.com/45708377/70797082-cb477c80-1db4-11ea-9bad-db3df914da5e.png)
- Start Bow order. I don't see any notification about Project halted.
![image](https://user-images.githubusercontent.com/45708377/70797130-eca86880-1db4-11ea-84a8-d95be188ce9c.png)

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/71815916-037b6b80-3092-11ea-89f2-4b3da453f30e.png)

**Comment by beastyn** [comment]
There were a lot of changes, so move issue to the @Hakuhonoo 
The idea is - if you are launching the order or adding something to it, you should get notifications about What amount of resources and labor you still need for it.

**Comment by SlayksWood** [comment]
I still haven't correct notification:
- Start Wooden Bow order - "I need 16 Woods and 30 Natural Fiber". I haven't notification that I need labor (I assume it happen because I can't add Labor)
- add 16 Birch log to order - "I need 10 units of labor". But I still need 30 Natural Fiber. It should tell me about it too.
![image](https://user-images.githubusercontent.com/45708377/75131084-611b5400-56e2-11ea-90dd-3c8e8ad553f4.png)
