### ISSUE TITLE
[0.9.0 staging-1298] Civics: "Citizen age in hours" value rarely updates

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14155]
The "Citizen age in hours" value does not update properly. The "Hours Played" value works fine. 

I have tried reconnecting and restarting the server to get the Citizen age in hours to update but neither does it. Normally the value gets stuck at zero. It is unusual that it got stuck at 0.01 instead of 0 this test.

Here is a law I used to test and the results:
![AgeTestLaw](https://user-images.githubusercontent.com/47330823/70935764-ca515d80-1ff5-11ea-947f-2eeac71f1e72.png)
![AgeInHours](https://user-images.githubusercontent.com/47330823/70935768-cde4e480-1ff5-11ea-9afa-b3d3f8bae43f.png)
![AgeInHours2](https://user-images.githubusercontent.com/47330823/70936060-709d6300-1ff6-11ea-83b3-6bf5961431ee.png)

**Comment by SlayksWood** [comment]
Perhaps it update with Demographic ticks - every 5 minutes.
![image](https://user-images.githubusercontent.com/45708377/70997191-7cb41e00-20e5-11ea-97dc-f1ed1a40071a.png)

**Comment by WeaselDog** [comment]
In this example it went over an hour without updating, so there is some other issue.

**Comment by johnkslg** [comment]
Good find! Fixed.
