### ISSUE TITLE
Water Plants should be able to require more water blocks above them

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14154]
![image](https://user-images.githubusercontent.com/14983165/70933769-6462d700-1ff1-11ea-9507-bfd92aae4937.png)

Plants like waterweed and kelp are designed to be ~2 or even 3 meters tall under the water, and constantly poke out of the water because they aren't yet able to detect if there is enough water above them. They should check every now and then, and die if they do not have enough water above them. Ideally they should check when spawning, too. Perhaps when planting underwater, there could be a message like 'There is not enough water depth for this plant to grow!'

Both of these plants should require 2 water blocks above them, thus they need 3 total meters high of water.
![image](https://user-images.githubusercontent.com/14983165/70934159-2914d800-1ff2-11ea-8a9b-64533f41a955.png)

![image](https://user-images.githubusercontent.com/14983165/70933976-c3c0e700-1ff1-11ea-9256-4b1d3685d6eb.png)

**Comment by beastyn** [comment]
Now ot looks very strange. They are all growing in a center line. Looks very unnatural. All the shores are empty. I think they can  be just under the water? Without this additional water blocks above?
![bandicam 2020-01-27 14-07-32-064](https://user-images.githubusercontent.com/27898520/73162583-eaedf680-410f-11ea-8e7f-c275e84b578c.jpg)
![bandicam 2020-01-27 14-11-24-478](https://user-images.githubusercontent.com/27898520/73162584-ec1f2380-410f-11ea-879f-07447c8fe5f6.jpg)

And also sea shores are empty too
![unknown (46)](https://user-images.githubusercontent.com/27898520/73166812-6bb0f080-4118-11ea-9446-eec7d7d7808c.png)

**Comment by beastyn** [comment]
Found this int he sea. Still need some work here
![Uploading bandicam 2020-02-12 12-39-58-027.jpg…]()

**Comment by beastyn** [comment]
Need to think about it. Its not so ugly, but it doesn't look natural.

**Comment by SlayksWood** [comment]
Will check after fixing this #17143
