### ISSUE TITLE
Resizing Objectives Window Crashes Client

### ISSUE THREAD

**Issue by gregoryl09** [StrangeLoopGames/EcoIssues#14157]
As stated in title, when you resize the objectives window, since it does not have readable text for individual objectives in default state, it crashes the client immediately. This occurs 100% of the time. I am on Borderless Window on my 1920x1080 resolution.

**Comment by beastyn** [comment]
Thank you for you report.
1.  What game version do you use?
2. Can you provise game log?
Instruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by gregoryl09** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3995917/Player.log)

version 8.3.0

**Comment by gregoryl09** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3995920/Player-prev.log)

**Comment by SlayksWood** [comment]
Thank you for report. Can't reproduce in 0.9.0 staging-1311. Seems fixed. If it happens again in next version please let us know.
