### ISSUE TITLE
'UniqueKey' strips case for registrar stored items

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14168]
![image](https://user-images.githubusercontent.com/3536496/71046117-1bdc1400-20ec-11ea-8aa6-6de668c88ea0.png)
The top is a unique generated name, the lower a regular work party.
I was going to go in and add 'ToLower()' on all the uses in UniqueKey but I didnt want to break your performance improvements you added there. 

The issue is that objects can have names with specific case, but they're always looked up in the registrar to ensure case insensitivity in referencing and name uniqueness.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/74532954-83261100-4f41-11ea-9672-15d53de6eea7.png)
