### ISSUE TITLE
[Piping] World Objects need to be able to have a water input and no sewage output

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14167]
Many industrial world objects need water for cooling or steam creation to function, but should not output sewage, like the Steam Engine, Solar Generator, Cement Kiln, etc.

**Comment by D3nnis3n** [comment]
Wouldn't it need at least a backflow? I've never heard of machines where water pumped in simply gets lost, at least if its not a vaporizer.

**Comment by keegan-o** [comment]
They *could* be required to have an output, but in the case of the steam engine and solar generator, they definitely should not output sewage. Cement Kiln it might be argued that it would output sewage since the water used to cool that machine would likely go to dirty parts. I think ideally we don't require them to have a pipe port output, but later we can use the utilities system to add whatever inputs and outputs we like without requiring more giant ports sticking off them.

**Comment by keegan-o** [comment]
For now, just getting them to require water input is what would at least make them make sense.

**Comment by Quadbro** [comment]
@MazonDel Took this one, cause i have 3 related ones for water inputs
