### ISSUE TITLE
I can't open my own server since it once crashed and I shut down my PC (Help me plz...)

### ISSUE THREAD

**Issue by nopigom** [StrangeLoopGames/EcoIssues#14165]
It was just a normal late night and I played Eco.
Suddenly, it just crashed and didn't move anything so I shut down my PC.
After that, the Eco server(my server) didn't open at all.
![File](https://user-images.githubusercontent.com/58993354/71028328-6db68580-2150-11ea-993e-e62dcdc60fd8.png)

Is there anything that I can fix this problem or use back up map data and open another server?

the ver. is the most recent ver. and no mod at all.
just original steam recent version. (2019-12-18 4:46 at GMT +9 <Korea> for now.)
I will be really happy that you guys give me some help.

**Comment by D3nnis3n** [comment]
You can see a backups folder there, just move the files of the last backup into the main storage folder and you should be good to go.
