### ISSUE TITLE
[0.9.0 staging-1299] Client hangs up first time connecting to a server

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14164]
The first time a user connects to a server, the client will get stuck on either "Entering world" or "Loading world". Pressing escape and trying to reconnect will result in a hangup like this:
![ClientHangup](https://user-images.githubusercontent.com/47330823/71018771-f4feed00-20ad-11ea-8066-b33f50dbf971.png)

This can only be fixed by quitting the client and reopening. It is likely directly related to this chat issue: https://github.com/StrangeLoopGames/EcoIssues/issues/14163

**Comment by beastyn** [comment]
I don't have problems with the first connection, but after spontaneous disconnects it happens.

**Comment by mirasrael** [comment]
From my observations it happens after client error.

**Comment by SlayksWood** [comment]
It happens when you try to host a world from Client.

**Comment by WeaselDog** [comment]
On my end, I can reproduce it 100% of times on the first connection. It happens for each user that connects to the server for the first time.

**Comment by WeaselDog** [comment]
No longer an issue in the latest build
