### ISSUE TITLE
[0.9.0 staging-1302] Command "/civics spawngov" need improvements.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14173]
Governmen office and executive office breaks room. 
![image](https://user-images.githubusercontent.com/45708377/71071233-416d2a00-218d-11ea-987f-1c702b1f0294.png)
And after Size fix Court will break room too.
![image](https://user-images.githubusercontent.com/45708377/71071248-48943800-218d-11ea-9749-0598ae0f9636.png)

**Comment by WeaselDog** [comment]
Could it just be one giant building instead?

**Comment by SlayksWood** [comment]
> civics spawngov spawn additional court house 
> ![изображение](https://user-images.githubusercontent.com/4980243/75679426-a6222600-5ca0-11ea-8b33-db3dd12f1719.png)
