### ISSUE TITLE
Eco does not start

### ISSUE THREAD

**Issue by GamerKy4a** [StrangeLoopGames/EcoIssues#14177]
Downloading. Sound appears, but the screen remains black. After a few seconds, the game crashes without a description of the error. win 8.1 i5-3450 gtx970 ram 16Gb
![382310_20191219012102_1](https://user-images.githubusercontent.com/59002390/71112383-efb0b800-21fd-11ea-9b58-93402054c195.png)
![Desktop Screenshot 2019 12 19 - 01 21 11 67](https://user-images.githubusercontent.com/59002390/71112409-fccda700-21fd-11ea-9c21-20bc39471863.png)

**Comment by D3nnis3n** [comment]
Can you attach your client log?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GamerKy4a** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3981083/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/3981084/Player-prev.log)

**Comment by GamerKy4a** [comment]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/3981089/error.log)

**Comment by mirasrael** [comment]
@GamerKy4a can you please check this dir:
C:/Users/kycha/AppData/Local/Temp/Strange Loop Games/Eco/Crashes
Zip and send content for us.

**Comment by GamerKy4a** [comment]
I work. after 7 hours I’ll add.

**Comment by mirasrael** [comment]
I noticed you're using Windows 8.1. It isn't supported and not tested do compatibility. We highly recommend to upgrade to Windows 10:

![image](https://user-images.githubusercontent.com/475445/71168709-62567d80-2268-11ea-9546-27621cd90af0.png)

You still can attach your crash log though.

**Comment by GamerKy4a** [comment]
played on win 8.1 for over 100 hours on version 8.3.1 of the game
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3983930/Crashes.zip)

**Comment by mirasrael** [comment]
Please ensure you have latest graphics card drivers. Also can you GPU load before crash?

In log I can see:
nvwgf2umx.dll caused an Access Violation (0xc0000005)
  in module nvwgf2umx.dll at 0033:88a4f46f.

It refers tp problem with Nvidia GPU driver.

**Comment by GamerKy4a** [comment]
Did not do anything. installed, launched, played. FIXED. launched on another monitor 1024 * 768. returned to the old monitor. set 1920 * 1080. the game has been running stably 10 times already.

**Comment by mirasrael** [comment]
Glad to know it is working now. Thanks for response.
