### ISSUE TITLE
[0.9.0 staging-1302] Overlapping with long name in Recipe Variation UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14175]
![image](https://user-images.githubusercontent.com/45708377/71081566-83ec3200-21a0-11ea-8d85-376485e4fd4d.png)
this is rarely seen in english. But there will be a big problem for localization.

**Comment by SlayksWood** [comment]
> No space for a long texts.
> Need more space at button
> need more space at checkbox
> ![изображение](https://user-images.githubusercontent.com/4980243/73520357-80d99800-4414-11ea-9025-164f3c9c3245.png)

**Comment by elfl0rd** [comment]
need more space at ecopedia reset button.
![изображение](https://user-images.githubusercontent.com/4980243/73522927-c305d800-441a-11ea-846c-51d53b190a77.png)
