### ISSUE TITLE
Night vs Day lighting is weird

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14181]
Night:
![image](https://user-images.githubusercontent.com/3536496/71134220-3bd60b00-21b2-11ea-8bf7-eb9bb8b68a80.png)
Day:
![image](https://user-images.githubusercontent.com/3536496/71134223-42648280-21b2-11ea-8ae3-1bc1e12b1743.png)
Cant see during the day!

**Comment by johnkslg** [comment]
What we need is some way for those huge windows to be letting in tons of light.

**Comment by johnkslg** [comment]
Things improved with GI turned on:
![image](https://user-images.githubusercontent.com/3536496/71134274-7475e480-21b2-11ea-8a40-cd59d0d5d0c0.png)


But we should do something about GI set to off, thats the default and it looks quite bad.
(Separate question; should it be off by default?  On would be better)

**Comment by johnkslg** [comment]
Raising this to high because it really affects the quality of the game. At sunset the world is plain invisible.

**Comment by beastyn** [comment]
![unknown (44)](https://user-images.githubusercontent.com/27898520/72720656-45310980-3b9c-11ea-8165-2200e5558942.png)

**Comment by keegan-o** [comment]
Big problems are solved, we have new issues for the last little fixes to make things in good shape for 9.0
