### ISSUE TITLE
[0.9.0 staging-1303] Can stack items in store

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14188]
Step to reproduce:
- best way to reproduce it's trying to add all item to selection:
![image](https://user-images.githubusercontent.com/45708377/71172612-bca80c00-2271-11ea-9397-599f720304c4.png)
But sometimes it happen when you add 5-10 items:
![image](https://user-images.githubusercontent.com/45708377/71172668-dfd2bb80-2271-11ea-9571-f8114c9b854f.png)

**Comment by SlayksWood** [comment]
need to fix it to check High issue #12538

**Comment by serpopov** [comment]
fixed via SVN
