### ISSUE TITLE
[0.9.0 staging-1302] UI: No way to see move speed reduction

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14184]
The part of the bottom right UI that shows the movement speed is missing.

0.8.3 view:
![WoodCartInGrass](https://user-images.githubusercontent.com/47330823/71142666-ec510880-21cc-11ea-9baa-c2313668eddf.png)

0.9.0 view:
![MissingMoveSpeed](https://user-images.githubusercontent.com/47330823/71142798-51a4f980-21cd-11ea-8882-ca808d3a3ed4.png)

**Comment by beastyn** [comment]
still nothing

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/77309587-f4f63500-6d0d-11ea-9f98-7d9c31605c42.png)
