### ISSUE TITLE
[0.9.0 staging-1302] Civics: Titles "Who Can Remove From Office" has wrong description.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14183]
The title condition "Who Can Remove From Office" has the same text description as "Successor"

![WhoCanRemoveOffice](https://user-images.githubusercontent.com/47330823/71142365-09d1a280-21cc-11ea-99ee-c74c898ced36.png)

**Comment by johnkslg** [comment]
Updated
