### ISSUE TITLE
Multiple comments with maps have layer error

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1419]
Add a few maps and I see a map layer error like this:
https://gyazo.com/f7fc45f21d916ce1c4d66fced7acabfb

Also for maps that don't have a selected layer, they display this error sometimes (with many comment maps):
https://gyazo.com/4af9ccac4c4c5f09a904e9381ce978ee

**Comment by SeanAtr0n** [comment]
looks like your world didn't finish its first tick, does it look normal now?

**Comment by rainfarmer** [comment]
still happening after fully ticked

**Comment by SeanAtr0n** [comment]
any errors in the console? looks like you are missing the ramp texture

**Comment by rainfarmer** [comment]
No errors in console.
https://gyazo.com/30fe10e15e7f8bf4d7d5d2cb34248d6a

Here is another example. just make two maps and the color of one of them changes.
https://gyazo.com/cf7aa57ed1ebc0c49c6b800f42573734

**Comment by SeanAtr0n** [comment]
i'm not seeing this behavior on master

**Comment by SeanAtr0n** [comment]
think this is resolved
