### ISSUE TITLE
[0.9.0 staging-1304] Civics: Population comparison counts all species.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14198]
When using the Population comparison to check species population, it counts all species population combined (both plants & animals). 

Law to replicate:
![PopulationCheck](https://user-images.githubusercontent.com/47330823/71304293-953c6680-2379-11ea-94e0-9278071a977c.png)

Civics debug message:
![PopulationCheckDebug](https://user-images.githubusercontent.com/47330823/71304294-98cfed80-2379-11ea-9430-3e58ea13e394.png)

If you leave the Species Type as "Any", it returns 0 for the population count. This should be replaced with the value currently returned when you select a species to count.

**Comment by johnkslg** [comment]
Fixed!
