### ISSUE TITLE
[0.9.0 staging-1303] Recipe: Possible to make Crushed Coal which has no use

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14190]
In the Arrastra you are able to make Crushed Stone from Rock. Here is the rock list:
![RockList](https://user-images.githubusercontent.com/47330823/71230020-b9764580-229c-11ea-8feb-2b7696456d65.png)

Even though Coal is not on the list, you are able to turn Coal into Crushed Coal.
![CrushedCoal](https://user-images.githubusercontent.com/47330823/71230047-ce52d900-229c-11ea-8507-d7dfd2171d34.png)

Crushed Coal has no use. It can't be used as fuel and it can't be used in place of CrushedRock. This recipe should be disabled for now so people don't accidentally waste coal.

**Comment by SlayksWood** [comment]
We can use Cruched Coal in Steel recipe.

**Comment by WeaselDog** [comment]
I am not able to use Crushed Coal for Steel Bars either. In this picture I am holding Crushed Coal and it won't let me add to project.
![SteelBar](https://user-images.githubusercontent.com/47330823/71270912-946aec80-2307-11ea-8a0b-cae7e2b8b9e1.png)

**Comment by elfl0rd** [comment]
as i think - only crushed coal can should be used in recipes\as fuel.

**Comment by WeaselDog** [comment]
I would be careful about nerfing Coal at this time. Charcoal has a huge incoming buff and Coal will be will be used less as a result of that.
