### ISSUE TITLE
[0.9.0 staging-1304] Delete game.db file during migration.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14196]
For migration from 0.8.3.1 to 0.9.0 you should delete game.db file.
You need to make this an automatic process during migration because you have error if you don't delete this file.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/74541939-ab1e7000-4f53-11ea-96e6-17ca675f2f05.png)
