### ISSUE TITLE
Fix invalid shaders

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14204]
[Curved/Standard 2] 9 incompatible material(s) detected: Basalt Decoration and Rubble (mapped), Gneiss Decoration Material (mapped), Gold Ore Granite Simple (mapped), Granite Decoration Material (mapped), Iron Ore Top Simple (mapped), Limestone Simple Material (mapped), SandStone Rubble (mapped), Shale Simple (mapped), Impenatrable Gneiss Decoration Material (mapped) (reference sample material: Crate (mapped)).

[Curved/Standard 3] 1 incompatible material(s) detected: Window Glass (mapped) (reference sample material: Crate (mapped)).
[Curved/Standard 4] 1 incompatible material(s) detected: Saguaro Debris Material (mapped) (reference sample material: Crate (mapped)).
[Curved/Standard 5] 1 incompatible material(s) detected: DefaultMaterial (mapped) (reference sample material: Crate (mapped)).
[Curved/Triplanar Masked Metalness Cutout 2] 1 incompatible material(s) detected: CL1 Redwood Clad Walls (mapped) (reference sample material: Compost Blending (mapped)).
[Curved/Triplanar Masked Pollutable Cutout 2] 1 incompatible material(s) detected: GrassBlockEdges (mapped) (reference sample material: Clay Blending (mapped)).
[Curved/Triplanar Masked Pollutable Cutout 3] 1 incompatible material(s) detected: TilledDirt_BLENDING (mapped) (reference sample material: Clay Blending (mapped)).

**Comment by keegan-o** [comment]
These are all materials that need to use the alpha cutout functionality in the shader getting matched to materials whose texture settings are different because they don't need to use the alpha cutout functionality in the shader @mirasrael -- I could use your eyes to see if there is a way to preserve that functionality and stop the errors from occurring.

**Comment by keegan-o** [comment]
basically the albedo in the saguaro tree debris, and all the other cutout materials needs to input alpha to use with alpha cutout, so it ends up as DTXT 5, and the albedos for materials that don't need alpha don't import it, and end up as DTXT 1.

**Comment by keegan-o** [comment]
With redwood slats and compost blending mats for instance, the textures within the shader that use cutout are different, even though both use cutout. Compost blending needs cutout for the mask, but not the albedo. Redwood slats needs cutout for the detail albedo, but not the mask.

**Comment by keegan-o** [comment]
(and I've never seen a way to import alpha and force textures to compress into DTXT 1, I think that's self-contradictory)

**Comment by redwyre** [comment]
The runtime texture format is set (perhaps indirectly) in the texture import settings

**Comment by keegan-o** [comment]
Right, if someone can magic the import settings to be DTXT1 *and* have alpha imported (needed for one of the materials in all these miss-matches), I've yet to see it.
