### ISSUE TITLE
Add missing icons

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14202]
Missing following UI icons (need sorting and descriptions):
Here is reference for how to set them up: https://sites.google.com/strangeloopgames.com/team/tools/icons

**Civic Icons**
These are created in the style shown here:
![image](https://user-images.githubusercontent.com/14983165/71941150-9806cc00-316d-11ea-837d-508493b90382.png)

I think these are pretty self explanatory so just ask me if any lacking an explanation are unclear still.  Also, feel free to use existing icons for these rather than creating a new one (in fact, prefer to do that if possible to reduce work load). 

- [x] AcceptedLoanOrBond
- [x] AddToWorkOrderAction
- [x] ChangePropertyOwner_LegalAction
- [x] CharacterLevelUp
- [x] ChopStump
- [x] CivicAction_EnterElection
- [x] CivicAction_PerformExecutiveAction
- [x] CivicAction_RemoveFromOffice
- [x] CivicAction_ResignFromOffice
- [x] CivicAction_StartElection
- [x] CivicAction_Veto
- [x] CivicAction_WithdrawFromElection
- [x] CleanupTreeDebris
- [x] CompletedContract
- [x] CompletedWorkParty
- [x] ConstitutionalAmendment - **isn't it a proposable like election?**
- [x] ConstructOrDeconstruct
- [x] DefaultedOnLoanOrBond
- [x] DigOrMine
- [x] DropOrPickup**Block**
- [x] FailedContract
- [x] JoinedContract
- [x] JoinedWorkParty
- [x] LaborWorkOrderAction
- [x] LeftWorkParty
- [x] LostElection
- [x] OfferedLoanOrBond
- [x] OpenAction
- [x] Pay_LegalAction
- [x] PlaceOrPickUpObject - **this one exist, but failed to edit**
- [x] Plow
- [x] PostedContract
- [x] PostedWorkParty
- [x] PropertyTransfer
- [x] RecordCustomStat
- [x] RepaidLoanOrBond
- [x] SendNotice - Send a message to a set of users
- [x] TampRoad
- [x] Timer - A timer went off, triggering a law
- [x] TransferMoney
- [x] Vote
- [x] WonElection (exists already?)
- [x] WorkedForWorkParty

**Icon types**  These need icons that show up in chat, like this: 
![image](https://user-images.githubusercontent.com/3536496/71852020-ac26cc80-308c-11ea-90ef-ed2520125b63.png)

They will be tiny icons next to text, so should be recognizable at small sizes.  
![image](https://user-images.githubusercontent.com/3536496/71852080-c6f94100-308c-11ea-8e18-0e2fafcb5b11.png)

However they do show up larger sometimes too:
![image](https://user-images.githubusercontent.com/3536496/71852101-ce204f00-308c-11ea-958c-97086b496aa9.png)

- [x] WorkOrder
- [x] WorkParty
- [x] DistrictMap
- [x] Contract
- [x] Law (I think this exists, not sure why its in here, check existing) **- no, it doesn't**

**Actual Object Icons:**

- [x] Advanced Masonry Table
- [x] Advanced Carpentry Table
- [x] Injection Mold Machine
- [x] Executive Office
- [x] All Taxidermy Animals
- [x] Pulp (for paper making)
- [x] Blank Book (for skillbook etc crafting)
- [x] Printing Press (once object is done)

Research Paper Icons: These research papers will be crated with the printing press, and will be needed to apply towards research goals to advance technology (which will also then in turn unlock the ability to craft skill scrolls and books). 
The icons for these should be composite, with a blank research paper icon, and then various stamps/images/symbols to go on top of the paper, so that we end up with:

- [x] Culinary Research Paper
- [x] Gathering Research Paper
- [x] Dendrology Research Paper
- [x] Engineering Research Paper
- [x] Geology Research Paper
- [x] Metallurgy Research Paper
- [x] Agriculture Research Paper

**Updates to old Object Icons:**
- [x] Bed Objects
- [x] Garage Door
- [x] Wood Lamps (Desk, Ceiling, and Standing)

**Comment by johnkslg** [comment]
I think the code side should be covered so removing @olegshegai

**Comment by keegan-o** [comment]
these are all done
