### ISSUE TITLE
[0.9.0 staging-1307] Civics: some filters won't work (no objects to select)

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14209]
Just can't choose speciality, filter is empty (census, work parties were checked)

![bandicam 2019-12-23 13-28-51-396](https://user-images.githubusercontent.com/27898520/71345816-2b45dc00-2588-11ea-968b-382014f82156.jpg)

**Comment by beastyn** [comment]
Also blocks for construct-deconstruct
![bandicam 2019-12-25 12-39-01-467](https://user-images.githubusercontent.com/27898520/71437432-8952fa80-2713-11ea-9b52-6855b1f54c3b.jpg)

**Comment by johnkslg** [comment]
Good find, fixed:
![image](https://user-images.githubusercontent.com/3536496/71534880-99570f80-28b6-11ea-8640-c6a3db4d2ee7.png)

![image](https://user-images.githubusercontent.com/3536496/71536722-4b96d300-28c7-11ea-9adc-80959838464b.png)
