### ISSUE TITLE
[0.9.0 staging-1307] Work party: can see invalid requirements for the role

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14210]
If requirements are invalid, you won'r figure it out from UI. No signs about it on the table
Like here - Skills field is empty, but requirement field looks normal.
![bandicam 2019-12-23 13-33-12-294](https://user-images.githubusercontent.com/27898520/71346066-d191e180-2588-11ea-935b-58d86351123b.jpg)
![bandicam 2019-12-23 13-33-27-039](https://user-images.githubusercontent.com/27898520/71346068-d35ba500-2588-11ea-8d3f-3ceee4876ff5.jpg)

**Comment by johnkslg** [comment]
Changed how this works, now you have to click 'submit' to apply changes and its greyed out if invalid, with error icon and tooltip explaining problem:
![image](https://user-images.githubusercontent.com/3536496/71690596-073d8400-2d5a-11ea-871d-9153690e226e.png)
