### ISSUE TITLE
[0.9.0 staging-1307] Wrong tabs in Government menu

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14213]
Tabs in Constitution, Legislation and Your Civic Duties same. In Population we have excess tabs.
![image](https://user-images.githubusercontent.com/45708377/71352682-fdf92e00-2587-11ea-9f6e-02eaef70fe19.png)
![image](https://user-images.githubusercontent.com/45708377/71352687-005b8800-2588-11ea-9daf-51483312d892.png)
![image](https://user-images.githubusercontent.com/45708377/71352691-02bde200-2588-11ea-988f-504d999f6034.png)
![image](https://user-images.githubusercontent.com/45708377/71352695-05203c00-2588-11ea-9941-5d1c9101f24a.png)

**Comment by beastyn** [comment]
Population and Duties are empty now. Not sure if its yours, maybe calling for @olegshegai
