### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by Siesma** [StrangeLoopGames/EcoIssues#14215]
Hopefully this is also "fine" to do.
A friend of mine and me made a list of all bugs we encountered.

1)
Running into one another straight will sometime cause the player to "stick" to the other one, even though he already left the area.
For example:
He runs into me and then goes behind me.
In my vision he sticks onto me and blocks me so I cant move forward. (even though he, in his POV, is already far away)
Steps to reproduce:
Host a server and run into one anothre (?). I'm not sure if this is a problem with the server or really a bug.

2)
If the friend of mine mines rock the physic of these rocks are very weird. But only for me. In his vision everything is normal.
The broken physics also affects my FPS alot. If he doesn't mine anything I maybe get around 80FPS. If he starts to mine (in the same area) I loose like 30-40FPS.
Steps to reproduce:
Have a friend join your server and let him mine something.
I'm not sure, but I think we encountered this bug for the first time when we had the level6 mining ability.

3)
When you run to the edge of a ramp and the following block is on the same height level as the highest part of the ramp, you can get stuck between the two connecting blocks.

4)
We're not sure how to reproduce. But:
Sometimes, if you run into a skid-steer / truck / excavator (we haven't checked the other vehicles), the vehicle will sometime be pushed away in stupid positions. Once he ran into my skid-steer and flipped it completely.
Steps to reproduce:
Have someone place a vehicle and run into the front of it.

5)
If a tree is logged it sometimes teleports 5-10 blocks away and falls from there.
We have no clue how and why this occurs.

6)
Casting light onto ramps from a vehicle will only light up the bottom part of the ramp.
We have only checked the truck and we're unsure wether this happens with all vehicles.

7)
When you are driving the truck and the "front-seat-passenger" leaves and re-enters, the trucks peak velocity will drastically decrease.
Sometimes it also happens when you just leave the passenger-seat (and you don'tt reenter).

8)
If player A places an excavator and player B enters it and then changes the mode to "dig-mode" player A is unable to move with "W" or "S". Sometimes it also happens to player A even player B has placed the excavator.

Sorry if one of these is already reported (and maybe already fixed in the upcomming updates).

**Comment by SlayksWood** [comment]
@Siesma
Thank you for you report.
1. Perhaps this is due to this issue #12438. moved your comment.
2. We know about this issue. It is temporary fixed this way . I add new issue #14215 for future fixes.
4. I merged to #12528. moved your comment.
5. I assume this related with #12553. 
6.
7. Known issue. but there is no issue for it. Made separate issue #14217.
8. Similar issue #12895, moved your comment.

I still have a couple of unclear points:

3. Can you provide some screenshoots or video, or describe in more detail which type of block interacts with ramp. Do you mean that you can stuck in place like here:
![image](https://user-images.githubusercontent.com/45708377/71358792-39e9be80-259b-11ea-8b8d-eefdd48d6704.png)
This is issue with the wrong connection of blocks.
6. I haven't same problems:
![image](https://user-images.githubusercontent.com/45708377/71359061-2723b980-259c-11ea-8ac0-618758b64714.png)
![image](https://user-images.githubusercontent.com/45708377/71359070-2be86d80-259c-11ea-9323-70bf1074c17e.png)

**Comment by Siesma** [comment]
3.
Yes I do mean that collision.
But it also sometimes happens with player-placed blocks like hewn-log, although that is very rare and I don't know wether it was a bug of the game or something else blocked me.
And I also remember, that I forgot to add, that if you run on wall-placed blocks (hewn log, hammer - wall) you cant completely run onto it. If you run in a slight angle at the connection of two walls, you can also get stuck.

4.

I will see if I am able to record a video today evening, but till then:

With the truck its a bit more complicated to explain. But:
If someone is getting pushed by the truck, the truck wont be able to turn in the direction that the player model is more than 50% (?, not 100% certain).
And with the skid-steer: You can simply lower the arm to around 20° and then run (from the front) onto the "shovel" and jump again (in the moment you touch the "shovel"). Then you will be launched in the air and the skid-steer will bounce back.

**Comment by Siesma** [comment]
Well as I am currently by myself, I can't show everything. But I can show the bugs I have with the skid-steer.
https://www.dropbox.com/s/g1sp3i5szf97gup/eco-videos.zip?dl=0
I hope, that dropbox as a file sharing tool is acceptable ^^'.
There should be two "mp4" files in there, that show two bugs. The jump right before the video ends is the bug I wanted to share.

**Comment by Siesma** [comment]
Now we were able to reproduce the issue with the truck.

https://www.dropbox.com/s/skazxkj2e32y3v9/eco-videos-two.zip?dl=0

**Comment by SlayksWood** [comment]
We have separate issues for that.
