### ISSUE TITLE
[0.9.0 staging-1307]  Work Party: hard to find UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14214]
1. If someone has created a work party I don't have a place for taking a role in it.
UI won't appear in the Work or Economy Viewer.
It will only be accessable through the link in the main chat.
- the one, who has created a party sees it in the Work panel
![bandicam 2019-12-23 15-35-51-020](https://user-images.githubusercontent.com/27898520/71354794-d95c8080-259e-11ea-815e-5268c6659b32.jpg)
- others can't see it
![unknown (34)](https://user-images.githubusercontent.com/27898520/71355623-6dc7e280-25a1-11ea-9d01-5e5a577cbb82.png)
- Economy is empty too,
![bandicam 2019-12-23 12-35-43-700](https://user-images.githubusercontent.com/27898520/71355756-dc0ca500-25a1-11ea-974f-6e5c835f9806.jpg)

2. It doesn't appear when a role is taken either
3. Notifications won't update properly when labor is added

![unknown (34)](https://user-images.githubusercontent.com/27898520/71356026-c0ee6500-25a2-11ea-85cd-71ac3c3592d2.png)

**Comment by SlayksWood** [comment]
Now it display at Contract Board. But economy viewer still empty.
![image](https://user-images.githubusercontent.com/45708377/71541509-28bdfa80-296b-11ea-989a-e778b95bced6.png)

**Comment by johnkslg** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/3536496/71634113-1263a900-2bce-11ea-9cb5-5878ab05e4ed.png)

Also fixed the other economy viewer tabs which weren't showing.
