### ISSUE TITLE
USER ISSUE: User version differs from server

### ISSUE THREAD

**Issue by MacKenzieTStout** [StrangeLoopGames/EcoIssues#14218]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Continue game.

**Expected behavior:**
Start the game

**Actual behavior:**
Unable to connect: User is 8.3.2 and server is 8.3.1beta

**Do you have mods installed? Does issue happen when no mods are installed?:**
Unable to connect: User is 8.3.2 and server is 8.3.1beta

**Comment by SlayksWood** [comment]
@MacKenzieTStout 
The server administrator didn't upgrade the server to the new version.
For now, you can change the version of the game in Steam to 8.3.1 or download it from our website.

**Comment by MacKenzieTStout** [comment]
How do I change the version of the game in Steam?
