### ISSUE TITLE
[0.9.0 staging-1307] Work party UI feedback

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14211]
- [x] 1. Rename:
![image](https://user-images.githubusercontent.com/45708377/71347039-70fba800-257a-11ea-93a2-36d644f926b5.png)

- [x] 2. Description font size and can't change it. I tshould be like here:
![image](https://user-images.githubusercontent.com/45708377/71347119-a43e3700-257a-11ea-8940-3152b9eb223b.png)

- [ ] 3. Excess trash can:
![image](https://user-images.githubusercontent.com/45708377/71347145-b4561680-257a-11ea-8a80-80ade568a207.png)

- [x] 4. After changing 2point delete Role string from set requirements:
![image](https://user-images.githubusercontent.com/45708377/71347288-13b42680-257b-11ea-88aa-b5269d3e4361.png)

**Comment by SlayksWood** [comment]
Can we change "trash can" to red "minus" like in contract:
![image](https://user-images.githubusercontent.com/45708377/71347651-c5ebee00-257b-11ea-85fd-f568424399c0.png)

**Comment by johnkslg** [comment]
Can I pass this one to you @serpopov

**Comment by SlayksWood** [comment]
Staging-1494 I have only Excess trash can. Other points were fixed.

**Comment by SlayksWood** [comment]
merged to #16842
