### ISSUE TITLE
[0.9.0 staging-1307] Missing error notification "can't place a block there"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14216]
Step to reproduce:
- select place where you can't to place block:
![image](https://user-images.githubusercontent.com/45708377/71356683-06effc80-2594-11ea-8460-bc5d24fd644f.png)
- try to place. I haven't notification.

8.3.2:
![image](https://user-images.githubusercontent.com/45708377/71356889-a8774e00-2594-11ea-9b3e-5917a63fcc65.png)

**Comment by beastyn** [comment]
Still doesn't work for all situations.
Pass to @Quadbro as he is on the interactions now.
Don't have notification in this position
![bandicam 2020-02-05 11-17-31-025](https://user-images.githubusercontent.com/27898520/73815928-32a80880-4809-11ea-95e6-6e56a41c8e4a.jpg)

**Comment by Quadbro** [comment]
Added info through description
![image](https://user-images.githubusercontent.com/6802030/74808434-690f7880-531d-11ea-8d4f-521f05b25b20.png)
