### ISSUE TITLE
[0.9.0 staging-1308] Default world generation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14224]
We need to have it properly generated with builds and be actual.
It seems to be old and have some issues for now
- no trees with start from client
- wrong yield potential

the old one #11062

**Comment by SlayksWood** [comment]
> **Version:** 0.9.0.0 beta staging-1375
> 
> ![snap6079](https://user-images.githubusercontent.com/29383891/73370701-8a47f080-42ac-11ea-8b72-e2517cc67627.png)
> 
> Could this be due to the Version of the **DefaultWorld** file found in Server directory?
> ![snap6078edited](https://user-images.githubusercontent.com/29383891/73370743-99c73980-42ac-11ea-9a14-74ec00a4e56a.png)
> it does seem to be a much older File than the others



> which to me is weird as in the latest 8.3.2 Version of Eco from Steam is a Newer File than in 9.0 Staging
> ![snap6089edited](https://user-images.githubusercontent.com/29383891/73377560-24ad3180-42b7-11ea-8837-8c4d12a1ca95.png)

**Comment by Conchipedia** [comment]
![snap6201](https://user-images.githubusercontent.com/29383891/74067991-672ae880-49f2-11ea-856a-8c172d8a7e37.png)

still saying this in [0.9.0 Staging 1387]
and version of DefaultWorld is the same  (30th October 2019)

**Comment by SlayksWood** [comment]
still an issue.
