### ISSUE TITLE
[0.9.0 staging-1309] Wrong Occupancy for some civics objects.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14228]
1. Executive office. It occupies 4x4 plot:
![image](https://user-images.githubusercontent.com/45708377/71444414-14d38800-2722-11ea-8906-2f1efe88bb4f.png)
But it has empty space with half block in right and left. Also it has empy space with full block behind
![image](https://user-images.githubusercontent.com/45708377/71444468-6e3bb700-2722-11ea-8e80-ccdefc72f22e.png)
So it should occupy 3x3 plot.

2. Capitol. It occupies 3x4 plot: 
![image](https://user-images.githubusercontent.com/45708377/71444494-b5c24300-2722-11ea-9436-c61810866f32.png)
But it offsets in right. Also it has empy space with full block infront:
![image](https://user-images.githubusercontent.com/45708377/71444508-dd191000-2722-11ea-8888-5033ea27c68e.png)
It should occupy 3x3 plot and doesn't overlap other blocks.

3. Court. It isn't in center position. Court haven't space in left:
![image](https://user-images.githubusercontent.com/45708377/71444556-3a14c600-2723-11ea-987c-a9bd396fa8c8.png)
But have some space in right:
![image](https://user-images.githubusercontent.com/45708377/71444559-426d0100-2723-11ea-99fc-121c647e15b8.png)

**Comment by keegan-o** [comment]
I fixed all the prefabs and models to alleviate these issues, but when I tried to update the occupancy in code it exploded. We still do not seem to have a reliable way to update all occupancy at once, so I will try again with applying the occupancy updates one at a time from each individual object.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/71939699-6a6b5400-3168-11ea-9cf8-26af8f86f18c.png)

**Comment by keegan-o** [comment]
https://github.com/StrangeLoopGames/Eco/pull/5426
