### ISSUE TITLE
[Staging 1309] Weird Negative Percentage for Total Soil Moisture showing on some Blocks using Soil Sampler

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14234]
**Version:** 0.9.0.0 beta staging-1309

![snap5688](https://user-images.githubusercontent.com/29383891/71452025-0dd76480-2778-11ea-8055-2039a149552a.png)
![snap5689](https://user-images.githubusercontent.com/29383891/71452026-0dd76480-2778-11ea-9bda-fb36fc4f39eb.png)
![snap5690](https://user-images.githubusercontent.com/29383891/71452027-0dd76480-2778-11ea-8cb7-e62e3ccdd75a.png)
![snap5691](https://user-images.githubusercontent.com/29383891/71452028-0e6ffb00-2778-11ea-9e7f-94c48ae432ea.png)

**Comment by SlayksWood** [comment]
Seems fixed.
