### ISSUE TITLE
[0.9.0] Mining and Logging exp

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14232]
The Exp for mining would need a Change. You have for each Hit exp. When you use this System the more diffucult Stone give lot of exp till they break.

There would be different experience points depending on the different rock hardness.

And Logging would need to give exp with each hit on the tree, when you cut it in parts for Logs.

**Comment by WeaselDog** [comment]
Logging exp has an issue right now: https://github.com/StrangeLoopGames/EcoIssues/issues/13148

**Comment by Sekor2600** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13148
https://github.com/StrangeLoopGames/EcoIssues/issues/10981
related
