### ISSUE TITLE
Hoe ground no more remove unwanted plant from tile.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14231]
(if you try to hoe already prepared ground)
![изображение](https://user-images.githubusercontent.com/4980243/71447853-11052d00-2745-11ea-8e9b-cb17eb010dc4.png)

**Comment by SlayksWood** [comment]
So we have a really fun bug:
- hoe dirt:
![image](https://user-images.githubusercontent.com/45708377/79419915-731dc280-7fc0-11ea-914c-e21741552fcc.png)
- plant something:
![image](https://user-images.githubusercontent.com/45708377/79419938-7dd85780-7fc0-11ea-890c-ff29aae465fd.png)
- hoe this block second time:
![image](https://user-images.githubusercontent.com/45708377/79419964-90529100-7fc0-11ea-98f3-e756cd82bbdf.png)
- I have another tilled block
- pick up it with shovel. I have tilled first block too:
![image](https://user-images.githubusercontent.com/45708377/79420050-c132c600-7fc0-11ea-90e4-9536198be17a.png)
