### ISSUE TITLE
[0.9.0 staging-1310] The world is polluted very fast

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14239]
Step to reproduce:
- create new world
- place Blast furnace and connect it with water
- add to order some Rebars(or anything else). I assume that it's enough 1 Rebar.
- finish order and use fastforward (or continue play)
Some graphics:
![image](https://user-images.githubusercontent.com/45708377/71464766-a0edba00-27cb-11ea-8ffc-84b29b176304.png)
![image](https://user-images.githubusercontent.com/45708377/71464795-b8c53e00-27cb-11ea-97d4-abaa7686c452.png)
![image](https://user-images.githubusercontent.com/45708377/71464823-d5fa0c80-27cb-11ea-94cb-4fa938657602.png)
![image](https://user-images.githubusercontent.com/45708377/71464898-1c4f6b80-27cc-11ea-8f20-d688ac5ef283.png)
Temperature graphic doesn't work:
![image](https://user-images.githubusercontent.com/45708377/71464931-34bf8600-27cc-11ea-9ab1-93df4476a4a6.png)

**Comment by WeaselDog** [comment]
I was concerned this might happen. Pollution output has increased while CO2 absorption was decreased significantly. 
https://github.com/StrangeLoopGames/EcoIssues/issues/11397#issuecomment-544435868

**Comment by WeaselDog** [comment]
I will collect data on the plant CO2 absorption at World Generation. Changing the biomes could have had made less total trees which would seriously impact the CO2 absorption from plants.

**Comment by WeaselDog** [comment]
At world generation for 0.5km^2 world, the starting plant absorption was decreased by ~50%.  This is not counting the change to how CO2 absorption is calculated for trees.  The most significant change in my tests was the initial Ceiba population decreasing from ~500 to ~35. All tree populations have decreased, with the exception of a slight increase in Oak population.

There are likely other factors at play but this will have a significant impact on CO2 levels.

Here is data from a random world generation in 9.0 & 8.3: 
[PlantAbsorbtionStaging.xlsx](https://github.com/StrangeLoopGames/EcoIssues/files/4007306/PlantAbsorbtionStaging.xlsx)

**Comment by beastyn** [comment]
Alex has made some fixes, need toi check with playtest (as /ff will screw things up)
