### ISSUE TITLE
WEB Apostrophe in user names

### ISSUE THREAD

**Issue by csandazoltan** [StrangeLoopGames/EcoIssues#14241]
[WEB]
At current elections screen if a player has special characters in name, the data tag is enclosed the wrong way
For example "Ceviel D'Ark" gets broken up at the apostrophe, resulting in a javascript error and the voting page does displayed

![image](https://user-images.githubusercontent.com/6756505/71467347-db9f2480-27c2-11ea-80ea-de0cb2516bc4.png)

ECO version - Alpha 0.8.3.1
Expected behavior - A "current election" page displayed, where we can vote for elections
Actual behavior - The current election" page is blank, javascript error on console (screenshot)
Steps to Reproduce - Have a player with an apostrophe in name "run for office"
Operating system or web browser - Google Chrome 79.0.3945.88

**Comment by SlayksWood** [comment]
Thanks for the post we know about this issue. And try to fix it in the next major patches.
dup #14132
