### ISSUE TITLE
Create work order and contract cards

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14245]
https://1drv.ms/w/s!AnNPKT4C9Ig9okLmi6g-073gOKn0?e=1b7qDE

**Comment by madpingui** [comment]
In staging its very different now:
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/a42094c7-73fa-4095-9904-3bf1eca37680)
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/ac0ced85-267b-427a-96d4-a963cbc41d8e)
