### ISSUE TITLE
[0.9.0 staging-1310] World Object: Reduce room requirement for Ballot Box

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14243]
The ballot box only occupies 1x1x2 of space, but it requires 45m^2 of room space. This should be reduced to 25m^2, but I suggest the room requirement is removed completely.

The ballot box is not like other government objects. It must be used by players on a regular basis and it does not contain any civics. There will likely be multiple ballot boxes in various locations. It would be nice if we can have ballot boxes in open spaces like the middle of a town square.

![BallotBox](https://user-images.githubusercontent.com/47330823/71484626-28363000-27c2-11ea-9157-575b6ba91643.png)

**Comment by elfl0rd** [comment]
> I suggest the room requirement is removed completely.

I suggest 6m3 in 0.5 tier room.
