### ISSUE TITLE
0.9 Butcher animal not usefull

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14248]
It allow to set large order, but if you have different animals, you cannot buther them all.
e.g. i have 1 elk. (And some bisons, turkeys, etc)
i can set 11 butcher.
![изображение](https://user-images.githubusercontent.com/4980243/71510324-8f75e200-289f-11ea-9679-743613601e40.png)
i add a lot of labor.
![изображение](https://user-images.githubusercontent.com/4980243/71510336-9a307700-289f-11ea-9556-1335586b10f1.png)
but order stop due no ingredient.
![изображение](https://user-images.githubusercontent.com/4980243/71510376-c0eead80-289f-11ea-97d7-7ecda7384353.png)

**Comment by elfl0rd** [comment]
Also same issue for a lot of collapsed reciepes, e.g. charred food.
I want to char fish, but adding number of resources is annouing.

**Comment by mirasrael** [comment]
Butchering was redesigned.

**Comment by elfl0rd** [comment]
Still have this issue.
![изображение](https://user-images.githubusercontent.com/4980243/74375224-0126d280-4df1-11ea-90a8-eaace7302fd6.png)

**Comment by elfl0rd** [comment]
As i think, if "subreciepe" is identical, they should start without selection.
If not - no subcategory.

Also butchery really need boost, maybe some tallow from butchery?
