### ISSUE TITLE
[0.9.0 staging-1311] Can't migrate from 8.3.2

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14247]
Loading is stucking somewhere in the process (can be Loading garbage or later steps)
![unknown (36)](https://user-images.githubusercontent.com/27898520/71506116-779f5d80-28a1-11ea-87e8-0d8ef9131660.png)

**Comment by mirasrael** [comment]
Seems like the same issue as https://github.com/StrangeLoopGames/EcoIssues/issues/14238
(You can see not finished EconomyPlugin in log).
