### ISSUE TITLE
USER ISSUE: Tools consume extra calories on their last use

### ISSUE THREAD

**Issue by msgerbs** [StrangeLoopGames/EcoIssues#14258]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Get a tool with 1 use remaining. Use the tool.

**Expected behavior:**
It should use the normal amount of calories, for example 20 calories for chopping a tree. It will show be broken, and use extra calories, for example 100 calories for chopping a tree.

**Actual behavior:**
The last use, when the tool still shows as being "good" with 1 use remaining, will use the extra calories that a broken tool uses.

**Do you have mods installed? Does issue happen when no mods are installed?:**
The last use, when the tool still shows as being "good" with 1 use remaining, will use the extra calories that a broken tool uses.

**Comment by SlayksWood** [comment]
Fixed in 0.9.0 #12756
