### ISSUE TITLE
0.9 effeciency broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14251]
Just look. It's like you can craft 15 seeds from 9 fireweed shots.
![изображение](https://user-images.githubusercontent.com/4980243/71513668-55f7a380-28ac-11ea-926b-66165acdde9c.png)
![изображение](https://user-images.githubusercontent.com/4980243/71513674-5f810b80-28ac-11ea-851e-f2b7499e153f.png)

But... you can craft only 9 seeds.
![изображение](https://user-images.githubusercontent.com/4980243/71513723-96efb800-28ac-11ea-9214-d18623bf4f9a.png)

Every order tick, grab full resource.
Scraps - not work.

**Comment by SlayksWood** [comment]
dup #14170
