### ISSUE TITLE
0.9 Plants periodically not load

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14252]
(It appear if you make changes at plot, dig\plant\gather, etc)
first look
![20191227114432_1](https://user-images.githubusercontent.com/4980243/71513822-09f92e80-28ad-11ea-876a-cbd82b34cdfa.jpg)

after gather
![20191227114436_1](https://user-images.githubusercontent.com/4980243/71513824-0bc2f200-28ad-11ea-964c-4f555cdb9ed9.jpg)

first look
![20191227114612_1](https://user-images.githubusercontent.com/4980243/71513827-0e254c00-28ad-11ea-8a2c-cc2665652265.jpg)

after dig
![20191227114615_1](https://user-images.githubusercontent.com/4980243/71513829-0fef0f80-28ad-11ea-8b95-74f6ca64f654.jpg)

is most commonly observed on farms, but is also found in the world.

**Comment by WeaselDog** [comment]
This likely fixes https://github.com/StrangeLoopGames/EcoIssues/issues/3170 as well
