### ISSUE TITLE
[0.9.0 staging-1314] Add paper at contract board when you create Work Party.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14266]
like with contracts. Now contract board is empty.
![image](https://user-images.githubusercontent.com/45708377/71541517-4f7c3100-296b-11ea-82b7-c4b4b6d80d50.png)

**Comment by johnkslg** [comment]
Fixed!

**Comment by beastyn** [comment]
And now paper won't disappear after deleting a party
![bandicam 2020-01-01 22-59-15-360](https://user-images.githubusercontent.com/27898520/71644456-6c599100-2cea-11ea-8a29-f8e587f664c5.jpg)
![bandicam 2020-01-01 22-59-17-572](https://user-images.githubusercontent.com/27898520/71644459-724f7200-2cea-11ea-8019-cda6c1fce35b.jpg)

**Comment by johnkslg** [comment]
Annnnd fixed.
