### ISSUE TITLE
[0.9.0 staging-1314] Glitch with changing Role description and rename Work Party.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14268]
![image](https://user-images.githubusercontent.com/45708377/71542037-5eb2ad00-2972-11ea-9456-ee6cefff6a30.png)
![image](https://user-images.githubusercontent.com/45708377/71542040-72f6aa00-2972-11ea-965d-364c4e0fea3e.png)
Also you can't finish to rename role description by enter. The cursor moves to another line:
![image](https://user-images.githubusercontent.com/45708377/71542058-b51feb80-2972-11ea-8354-a2471039fd49.png)

**Comment by johnkslg** [comment]
This affects all editable titles, fix it in the root prefab and it will fix them all.

**Comment by beastyn** [comment]
The last onw is still actual

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79334325-c3494600-7f28-11ea-9c56-bae61d30bc49.png)
description should be align left

**Comment by johnkslg** [comment]
Easy fix for editing and its super ugly when it fails
