### ISSUE TITLE
[5.5.4] Connection failure: Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#1426]
![bild](https://cloud.githubusercontent.com/assets/27635053/25578162/4c38ef12-2e6c-11e7-8f17-7968cff7f368.png)

**Comment by Limelill** [comment]
Tried with restarting server, game client and computer (Even tried another one). I can log onto other servers but not the one in favorites. Seems to be related to my character files on that server.

**Comment by MarjieAVolk** [comment]
Could you attach any error logs from Eco you can find on your machine?

**Comment by MarjieAVolk** [comment]
Not enough information here to identify the issue
