### ISSUE TITLE
[0.9.0 staging-1314] All orders display when you start to create Work Party

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14263]
If you have a lot of orders it costs many time to delete unnecessary orders.
![image](https://user-images.githubusercontent.com/45708377/71540947-9fa2c580-2962-11ea-8910-11cb274c820a.png)
Can you make this field empty or may be display only last order?
It's more simple to add 1 or 2 order from list:
![image](https://user-images.githubusercontent.com/45708377/71540989-40918080-2963-11ea-99ab-a61ffe359914.png)

**Comment by johnkslg** [comment]
Limited to latest 2:
![image](https://user-images.githubusercontent.com/3536496/71632655-6a95ad80-2bc4-11ea-9c6a-85660eaaac35.png)

**Comment by beastyn** [comment]
Arrow - bow - campfire - carpentry table.
![bandicam 2020-01-01 23-51-38-168](https://user-images.githubusercontent.com/27898520/71644903-eb9e9300-2cf1-11ea-84fb-3fb903340696.jpg)

Will take: bow and carpentry table
Shoulkd take: campfire and carpentry table
(if the latest two)
![bandicam 2020-01-01 23-52-14-347](https://user-images.githubusercontent.com/27898520/71644908-f48f6480-2cf1-11ea-920f-fea3cc3c80d8.jpg)

**Comment by johnkslg** [comment]
Thanks, fixed!
