### ISSUE TITLE
USER ISSUE: Nothinness

### ISSUE THREAD

**Issue by Frostfled** [StrangeLoopGames/EcoIssues#14277]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. Click Continue
.......
2. Click Load
3. Click the world you've been playing
....

**Expected behavior:**
I expect it to load my world... Im already an hour past being able to refund and cant even play

**Actual behavior:**
Nothing loads. When I click continue it just lags for a split second then nothing. When I try to load it from the Load option I get the same thing. Nothing loads. I've restarted my computer, ive closed and reopened the game notjliufuhd Cant actually see what im writing at this point.... it doesnt scroll with the chat for some reason.... Anywasy I cant do anything. How do you even submit this shit only button I see is create in github...

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing loads. When I click continue it just lags for a split second then nothing. When I try to load it from the Load option I get the same thing. Nothing loads. I've restarted my computer, ive closed and reopened the game notjliufuhd Cant actually see what im writing at this point.... it doesnt scroll with the chat for some reason.... Anywasy I cant do anything. How do you even submit this shit only button I see is create in github...

**Comment by Frostfled** [comment]
It seems however I can create a new world... Which means I just lost my 4 hours of gameplay? My save must be corrupt

**Comment by redwyre** [comment]
Hi @Frostfled,
Can you follow the instructions at https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world to get the logs files and https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save to upload a save for us to look at?

**Comment by Frostfled** [comment]
Hey Simon

I apologize. Seems my kid failed to mention that the computer has been acting up. We’ve been getting a WHEA UNCORRECTABLE ERROR from windows this past week. I believe our C:\ drive may be corrupt and what Dante forgot to mention when he had me fill that out was before he relaunched the game the computer had crashed with the above error while he was exiting the game. Seems it happens every time he closes the game which I believe may have corrupted the save files. I am currently waiting in queue with windows support to see if they can help me reinstall windows to a different drive. I did notice however there is no way to delete worlds in the game. Is it  possible I can just delete them in the files? And it would go away in game so he doesn’t try to open them?

Ill pop the files up there anyways.

Cheers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Frostfled** [comment]
[log_191228022628.log](https://github.com/StrangeLoopGames/EcoIssues/files/4008030/log_191228022628.log)
[log_191228044910.log](https://github.com/StrangeLoopGames/EcoIssues/files/4008031/log_191228044910.log)
[log_191228083220.log](https://github.com/StrangeLoopGames/EcoIssues/files/4008032/log_191228083220.log)


[NewfieLand.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4008033/NewfieLand.zip)

**Comment by beastyn** [comment]
@Frostfled 
You can delete save files from the Storage folder.
Also, you have Backup folder there, maybe some saves there can be useful.

**Comment by WeaselDog** [comment]
Hi @Frostfled. I just wanted to follow up and see if have experienced any more issues. Thanks for the detailed report and all the info you provided.

**Comment by Frostfled** [comment]
Hi Todd

Yes we managed to figure it out afterwards. We ended up calling Microsoft and after a reinstall of windows it still wasn't working. After a few more attempts trying things and speaking to other representatives one of them  realized that when my computer shuts down it never fully shut off. For some reason the motherboard wasn't shutting down the bios properly and so it would never shut down all the way. They explained how to reset it and the game has worked ever since. Thanks for checking in.

Cheers
Mitch

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by redwyre** [comment]
@Frostfled I edited your posts because it was including some of your personal information, it's probably best to use the site to respond instead of email.

**Comment by WeaselDog** [comment]
Great glad to hear it is working now!
