### ISSUE TITLE
[0.9.0 staging-1314] Joshua Tree initial population is very low.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14274]
The starting Joshua Tree population is always very low, often lower than Old Growth Redwood.
On a default sized world the population is always single digits. It is usually less than 5 and in my most recent world generation it was 2.

This issue also discusses issues with Old Growth Redwood & Sagebrush populations: https://github.com/StrangeLoopGames/EcoIssues/issues/12449

**Comment by SlayksWood** [comment]
Still need more Joshua and less Saquaro Cactus:
![image](https://user-images.githubusercontent.com/45708377/76284394-3b7b7680-62ae-11ea-807c-73af6f566bad.png)
![image](https://user-images.githubusercontent.com/45708377/76284409-47ffcf00-62ae-11ea-9e62-d1369bcf6f20.png)

**Comment by WeaselDog** [comment]
I will intentionally have the Joshua significantly lower than the Saguaro Cactus, but yeah this is way too extreme. It makes a big difference the world gen (sometimes the desert is divided into small sections and other times it is on solid chunk)
