### ISSUE TITLE
USER ISSUE: Browser - wrong server

### ISSUE THREAD

**Issue by Rajaylia** [StrangeLoopGames/EcoIssues#14271]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Open browser:
Press "L"
Viwe Law

**Expected behavior:**
Open the browser of the current server, log on and view the law

**Actual behavior:**
Every now and then:
Open the browser of an other Server ([SLG] GIANT PANDA - OFFICIAL ECO SERVER (2019-12-27 TO 2020-01-16)) with Errormessage "This law does not exist", and doesnt log on. 

Otherwise:
Expected behavior

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by msgerbs** [comment]
What was the server you were trying to view laws for? This sounds like multiple servers at the same IP.

**Comment by Rajaylia** [comment]
I tried to connect the server http://185.244.192.27:3001 and got http://95.217.35.61:3001

There are no multiple servers at this IP (185.244.192.27) and I dont play on the other server at all (95.217.35.61)

**Comment by mirasrael** [comment]
@Rajaylia you should check Network.eco to see if it has WebServerUrl set

**Comment by Rajaylia** [comment]
@mirasrael WebServerUrl is not set. The key dosent exist in my "Network.eco" and "Network.eco.template"

The server website I get instead of mine is almost always "[SLG] Giant Panda", so maybe it defaults to an official server when something goes wrong?

**Comment by mirasrael** [comment]
I just entered the server and tried to go to web and it correctly directed me to http://185.244.192.27:3001/index.html?

**Comment by mirasrael** [comment]
Can you record a video for repro case?

**Comment by mirasrael** [comment]
Also, can you attach client log? And did you try to connect directly by IP address?

**Comment by Rajaylia** [comment]
The issue only occures sporatic. I normaly connect by name.

**Comment by Rajaylia** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4010947/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4010948/Player-prev.log)

**Comment by Rajaylia** [comment]
[2019-12-30_Video_.mp4.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4010963/2019-12-30_Video_.mp4.zip)

**Comment by mirasrael** [comment]
As I suspect problem in this line:
```
Connecting with relay 95.217.35.61:3300 to e03006a6-93cd-44b3-983d-06bbd9612a80...
```
For some reason it can't connect directly and fallback to relay server, but in current implementation it uses same IP which was used to connect to the server for web url. And EU relay server located on the same machine as the official server Giant Panda.
To avoid this I can recommend you to set RemoteAddress explicitly on your server (to your server external IP).

**Comment by Rajaylia** [comment]
After about two weeks with the RemoteAdress set I can report the following:

1. The game now always connects to the correct web server, but in rare cases (<1%)  I'm not recognized as citizen. In that case I cannot vote or propose laws

2. Connecting to the server often does not work (Connection times out). Sometimes the game has to be restarted. This only happens when the RemoteAdress is set.

Could this be an IPv4/IPv6 issue? The server is configured for both and our ISP also supports IPv6, but as far as I know Eco only supports IPv4?

**Comment by mirasrael** [comment]
@Rajaylia it may be problem with server's firewall which may block or throttle connections (or it may be high packet lose rate), because when RemoteAddress set it connects directly to the server using it's IP address.
You can try to ping the server to collect dropped packets statistic with low ping delay.

**Comment by mirasrael** [comment]
Now web server url always opened for server's original IP (ignoring relay).
