### ISSUE TITLE
[0.9.0 staging-1314] Lumber tag has incorrect plural form

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14275]
The noun lumber has the same singular & plural form. The Lumber tag currently has the plural form as "Lumbers" so it should be changed.

![Lumbers](https://user-images.githubusercontent.com/47330823/71548493-db8a5a80-2963-11ea-9f24-03100413cfe2.png)

**Comment by WeaselDog** [comment]
This is an issue with many tags. We do not have a way to set a custom plural name.

**Comment by redwyre** [comment]
@Quadbro check out the tech tree stuff for form type and form groups
