### ISSUE TITLE
[0.9.0 staging-1314] Visual issue with Bakery Oven pipe inputs

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14276]
The Bakery Oven has two places where pipes can intersect that aren’t the chimney. This is just a visual issue. The pipes do not treat it as an opening, and it can’t be used for the oven exhaust.

One in front:
![BakeryPipe1](https://user-images.githubusercontent.com/47330823/71549465-bf41ea00-2972-11ea-81d6-ee549976708b.png)
One in back:
![BakeryPipe2](https://user-images.githubusercontent.com/47330823/71549466-c10bad80-2972-11ea-97c6-7d8580291dd6.png)

**Comment by keegan-o** [comment]
Duplicate of #6024
