### ISSUE TITLE
[0.9.0 staging-1314] New fish have long text string for a name

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14272]
The following fish all have a long text string where the icon should be:
Blue Shark, Bass, Cod, Pacific Sardine.

![FishChat](https://user-images.githubusercontent.com/47330823/71547555-53ea1f00-2956-11ea-9390-fe22dcb0c4c8.png)
![BassTooltip](https://user-images.githubusercontent.com/47330823/71547559-5e0c1d80-2956-11ea-9d0b-453d188dbde8.png)

**Comment by keegan-o** [comment]
fixed in staging
