### ISSUE TITLE
[0.9.0 staging-1317] Craft: wrong resources counting after server restart

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14284]
1. Create an order withour resources
![bandicam 2019-12-31 10-44-01-857](https://user-images.githubusercontent.com/27898520/71611551-a415eb00-2bbb-11ea-9390-53780143d3db.jpg)
2. Restart server
![bandicam 2019-12-31 10-50-19-392](https://user-images.githubusercontent.com/27898520/71611555-aa0bcc00-2bbb-11ea-8665-ce18c44d992d.jpg)

**Comment by Hakuhonoo** [comment]
It seams fixed
