### ISSUE TITLE
Vivox exception on client during connection

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14289]
Occurs when using a test login with Skip Authentication in the debug tunder

ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <567df3e0919241ba98db88bec4c6696f>:0)
VoiceManager.IsPlayerSpeaking () (at Assets/Scripts/Voice/VoiceManager.cs:95)
Assets.UI.Scripts.Voice.VoiceChatPanelUI.OnEnable () (at Assets/UI/Scripts/Voice/VoiceChatPanelUI.cs:23)
UnityEngine.Object:Instantiate(GameObject)
UI.UIManager:Open(String, BSONObject, UILayer) (at Assets/UI/Scripts/Manager/UIManager.cs:421)
UI.UIManager:Open(String, UILayer) (at Assets/UI/Scripts/Manager/UIManager.cs:379)
Player:ReceiveInitialState(BSONObject) (at Assets/Scripts/Player/Player.cs:173)
NetObjComponent:OnReceiveInitialState(BSONObject) (at Assets/EcoModKitInternal/Scripts/NetObjComponentInternal.cs:116)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject) (at Assets/EcoModKitInternal/Scripts/NetObjComponentInternal.cs:181)
Eco.Shared.Networking.NetObjectManager:HandleNewObject(BSONObject) (at C:/Eco/Server/Eco.Shared/Networking/NetObjectManager.cs:208)
Eco.Shared.Networking.ClientPacketHandler:ProcessItem(BSONValue) (at C:/Eco/Server/Eco.Shared/Networking/ClientPacketHandler.cs:83)
Eco.Shared.Networking.ClientPacketHandler:ProcessItemsWhile(Func`1) (at C:/Eco/Server/Eco.Shared/Networking/ClientPacketHandler.cs:69)
Eco.Shared.Networking.ClientPacketHandler:ReceiveWhile(NetworkClient, Func`1) (at C:/Eco/Server/Eco.Shared/Networking/ClientPacketHandler.cs:37)
NetworkManager:OnTimeLimitedUpdate(TimeLimit) (at Assets/Scripts/Networking/NetworkManager.cs:605)
FramePlanner.FramePlannerSystem:OnUpdate() (at Assets/Scripts/FramePlanner/FramePlannerSystem.cs:35)
Unity.Entities.ComponentSystem:InternalUpdate() (at Library/PackageCache/com.unity.entities@0.1.1-preview/Unity.Entities/ComponentSystem.cs:800)
Unity.Entities.ComponentSystemBase:Update() (at Library/PackageCache/com.unity.entities@0.1.1-preview/Unity.Entities/ComponentSystem.cs:284)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.1.1-preview/Unity.Entities/ComponentSystemGroup.cs:602)

**Comment by redwyre** [comment]
Looks like this has already been fixed
