### ISSUE TITLE
[0.9.0] Crash in craft submenu when try to see ingredient tooltips.

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14285]
My Client flies from the server when I open recipes with the Selection Option. sometimes it takes a little

Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Cannot convert value: 8037 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Source:Eco.Shared

System.InvalidOperationException: Cannot convert value: 8037 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
   at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type) in G:\Eco-Github\Server\Eco.Shared\Serialization\AutoBsonSerializer.cs:line 158
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod method, Object target) in G:\Eco-Github\Server\Eco.Shared\Networking\RPCManager.cs:line 494
   at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod[] methods, Object target, RPCMethod& targetMethod) in G:\Eco-Github\Server\Eco.Shared\Networking\RPCManager.cs:line 513</size>

![grafik](https://user-images.githubusercontent.com/37456949/71634314-44e7c300-2c1b-11ea-8106-bf0337f74adf.png)

https://drive.google.com/open?id=1tOqLbYz1ecwl17g-3hxVgcEzd2KKxNsw

**Comment by SlayksWood** [comment]
> Step to reproduce:
> 
> * place anvil (for example)
> * open craft iron tool submenu:
>   ![image](https://user-images.githubusercontent.com/45708377/71877585-8b1cb500-313a-11ea-9b4e-ed85fa2fda12.png)
> * try to see tooltip at any ingredients:
>   ![image](https://user-images.githubusercontent.com/45708377/71877629-bacbbd00-313a-11ea-9cea-be8736caaa4b.png)
> * crash:
> 
> ```
> <size=60,00%>Exception: InvalidOperationException
> Message:Cannot convert value: 4496 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
> Source:Eco.Shared
> 
> System.InvalidOperationException: Cannot convert value: 4496 to type: System.Collections.Generic.List`1[[Eco.Core.Controller.IController, Eco.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
>    at Eco.Shared.Serialization.BsonManipulator.FromBson(BSONValue value, Type type)
>    at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod method, Object target)
>    at Eco.Shared.Networking.RPCManager.UnpackArgs(INetClient client, BSONArray bsonArray, RPCMethod[] methods, Object target, RPCMethod& targetMethod)</size>
> ```
> 
> Log file: [Rhfi.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4029404/Rhfi.txt)

**Comment by Conchipedia** [comment]
still happening [Staging 1329]
