### ISSUE TITLE
[0.9.0 staging-1320] Contract board does not visual update after contracts are finished

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14287]
The papers that visualize a contract or a work party on a Contract Board do not disappear after the contract is finished. There are two ways replicate this:
1.) Create a draft of a contract or a work party. Delete the draft. The paper remains.
2.) Post a contract or work party and complete it. The paper remains. If you post multiple contracts at the same time it will create papers for each one.

Below is an image of a contract board that has 3 completed contract and 1 deleted draft. This contract board has no active contracts. Drafting a contract will replace an existing paper, so the board only has 3 papers instead of 4. It is fixed by a server restart.

Contract Board View:
![ContractBoard](https://user-images.githubusercontent.com/47330823/71685268-9e9bda80-2d4c-11ea-80c3-c935e1a94320.png)

**Comment by johnkslg** [comment]
Good find, fixed
