### ISSUE TITLE
[0.9.0 staging-1320] Unable to accept multiple contracts

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14295]
After accepting a contract, it is not possible to accept anymore contracts. It does not matter if it is a contract from the same client or a new client. Each citizen can accept one contract each. You need two users to replicate this.

View of second contract acceptance screen:
![SecondContract](https://user-images.githubusercontent.com/47330823/71704223-de36e680-2d8d-11ea-88e8-ca785fd8e835.png)

**Comment by johnkslg** [comment]
Fixed!
