### ISSUE TITLE
Icons in preview hover-UI and chat and tooltips and Ecopedia do not use scaling and positioning, and break in other ways

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14291]
Overall, icons everywhere in-game should look like they do when they are on the toolbar or in the backpack-- but they look different in all different places. Previously this problem has been phrased as 'need inline gameobjects rather than inline sprites', I imagine so that they can inheirit all the scaling and positioning in the original gameobject setup in eco.unity.' So we may need to make all icons into a prefab or something.

![image](https://user-images.githubusercontent.com/14983165/71696899-2e508180-2d6b-11ea-9f3b-d7dbf12d626a.png)
In the 'what you are looking at' hover UI, the icon is not positioned over the center of its background, it is several pixels down from the center.
![image](https://user-images.githubusercontent.com/14983165/71696970-5dff8980-2d6b-11ea-9dc9-f31d4b782271.png)

Scaling of any sub-icon is also broken, when it should be inherited from the Icon gameobject in eco.unity.

In the chat UI, there are the same problems-- we want scale and positioning inherited from the Icon gameobject in Eco.unity if we can. 

![image](https://user-images.githubusercontent.com/14983165/71697080-b9ca1280-2d6b-11ea-8a5e-e3ad6cf9371b.png)
Similar issues in the tooltip icon, no scaling or positioning. Also some icons seem to not display all their sub-icons.
![image](https://user-images.githubusercontent.com/14983165/71697110-d0706980-2d6b-11ea-9098-8f5ec63d96d1.png)

**Comment by keegan-o** [comment]
This is a big problem for the ecopedia in 9.0 as well! They only grab a single sprite which is even worse than the wrong positioning.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/77037222-2e6c2f00-69f4-11ea-98cc-378e0156df46.png)
Also noticed that the icon should be a bit bigger, lining up to the top and bottom of the text line.
