### ISSUE TITLE
[0.9.0 staging-1321] Picking up a contract board deletes all contracts attached to it

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14294]
Picking up a contract board deletes all the attached contracts with no way to get them back. This causes the payment to stay locked in Contract Escrow and the deposit to remain with the client who posted the contract.. Perhaps contract boards should become unique objects like civic objects.

Contract to replicate:
![ContractDeposit](https://user-images.githubusercontent.com/47330823/71703849-cc544400-2d8b-11ea-9b79-398608128296.png)

Tooltip of contract after replacing contract board:
![ContractNotFound](https://user-images.githubusercontent.com/47330823/71703856-dfffaa80-2d8b-11ea-8677-6594a391db4e.png)

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/71747499-aaf36680-2e24-11ea-95c1-734e27e7a403.png)

![image](https://user-images.githubusercontent.com/3536496/71747509-b0e94780-2e24-11ea-850a-d23319789e79.png)

**Comment by WeaselDog** [comment]
There is still an issue with accepted contracts getting deleted. It is fixed for proposed contracts & work party.

Before pickup:
![ContractBefore](https://user-images.githubusercontent.com/47330823/71771349-4e5c7e00-2eee-11ea-91ea-f0f4306e2e5b.png)
After pickup:
![ContractAfter](https://user-images.githubusercontent.com/47330823/71771350-51f00500-2eee-11ea-9fae-ef04b28c6cd4.png)

**Comment by johnkslg** [comment]
Contracts should be taken off when active (unlike work parties). Fixed this so it happens immediately.
