### ISSUE TITLE
[0.9.0 staging-1321] Accepting a contract causes it to become disabled

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14293]
After a accepting a contract, it starts the Civic countdown to make the contract invalid. This was not an issue in staging-1320.

![ContractInvalid](https://user-images.githubusercontent.com/47330823/71703540-fb69b600-2d89-11ea-9d33-47e23fa94205.png)

**Comment by johnkslg** [comment]
Fixed!
