### ISSUE TITLE
[0.9.0 staging-1322] Contract, work party: board's draft issue

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14296]
1) Party draft
1. Press plus on the contract board to create a party
2. Don't post it
![bandicam 2020-01-03 11-34-42-242](https://user-images.githubusercontent.com/27898520/71711130-65816a00-2e21-11ea-9bc8-9f0674078efd.jpg)
3. Let other pesron to look at the board
Other person can even take a role in a draft party.
![bandicam 2020-01-03 11-34-57-306](https://user-images.githubusercontent.com/27898520/71711138-6fa36880-2e21-11ea-9bcb-d7471d79ffb0.jpg)
2) Contract draft.
Other person can see your contracts drafts.
![bandicam 2020-01-03 11-52-48-533](https://user-images.githubusercontent.com/27898520/71711148-7b8f2a80-2e21-11ea-868c-c2570254935b.jpg)

Suggestion:
1) Don't place drafts for other people on the board (you don't see drafts in the Economy viewer)
2) Mark better unposted parties as drafts on your board and in your work notifications (maybe "Draft" should be red colored or an icon with the reddish background).

![bandicam 2020-01-03 12-00-41-838](https://user-images.githubusercontent.com/27898520/71711194-b6915e00-2e21-11ea-9c5b-9acb76dd1cfa.jpg)

![bandicam 2020-01-03 12-01-53-152](https://user-images.githubusercontent.com/27898520/71711183-a7121500-2e21-11ea-86fa-5abfd748d9ee.jpg)

**Comment by beastyn** [comment]
Also, why do we keep Removed contracts on the board (which will disappear after server restart)?
Lets keep just active things on it

**Comment by johnkslg** [comment]
Fixed all of the above
![image](https://user-images.githubusercontent.com/3536496/71744464-2b619980-2e1c-11ea-9b5f-19adbf090d6f.png)
![image](https://user-images.githubusercontent.com/3536496/71744483-387e8880-2e1c-11ea-86a8-63191dd7026b.png)
![image](https://user-images.githubusercontent.com/3536496/71744494-46340e00-2e1c-11ea-8b7d-5d3061b39c9a.png)

**Comment by WeaselDog** [comment]
Everything in the original issue is fixed. Removed (finished) contracts still stay on the contract board until a new contract is proposed by anyone or a server restart. It does not cause any gameplay issues.

**Comment by beastyn** [comment]
Yeaj, will ,ake separate issue for removed contracts
