### ISSUE TITLE
[0.9.0 staging-1322] Ecopedia: icons troubles

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14298]
Separated from the old issue #14013
[] Work with Rob to get all missing icons in ecopedia
[] Need different icon for rooms and housing here. Make sure no duplicate icons.
[] Duplicate icons, and contract board icon is bad and needs redoing. Use different icon for transport too, a truck or cart
[]  Add icons for missing types in laws

**Comment by keegan-o** [comment]
finished in staging once my pr for the ecosystem section goes in.
