### ISSUE TITLE
Districts have funny settings

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14304]
District display bad in the minimap settings
![image](https://user-images.githubusercontent.com/3536496/71758855-c6c52f80-2e59-11ea-8e89-ebbbc793eb98.png)
- Vertical margins messed up 
- Artifacts to the right of each district.
- Clicking a district goes into the color selector. You should not be able to change district colors here.  

There should be **one checkbox per active district map in the game**, and you can check which maps to render, and then they all render on top of each other.   The individual district names should be visible when you center on them (or mouse over/click them).

**Comment by SlayksWood** [comment]
Seems fixed.
