### ISSUE TITLE
 [STAGING 1322] Kicked from Server with Exception when in Basic Tool Selection Window and hovering over a tool to choose to craft

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14303]
**Version:** 0.9.0.0 beta staging-1322

![snap5741](https://user-images.githubusercontent.com/29383891/71758051-14aa5980-2e93-11ea-9775-a62369068f5d.png)
![snap5742](https://user-images.githubusercontent.com/29383891/71758169-6dc6bd00-2e94-11ea-8447-0c51c7c04bd7.png)

when Opening this window (either manually Choosing it or clicking Craft Basic Tool and Eco opens it itself) as soon as you Hover the pointer over a Tool it kicks you with the Following Exception
![snap5740edited](https://user-images.githubusercontent.com/29383891/71758072-491e1580-2e93-11ea-8982-83f63f27f5c6.png)

the Circled Number appears to change depending on the Tool you hover over (didnt check them all but i got two different numbers 5023 + 4807)

uploading Player log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4021421/Player.log)

and this is on a Singleplayer World

**Comment by Conchipedia** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/14285
also linking it to this ONE as that seems to say sort of the same thing about
**cannot Convert value**

**Comment by beastyn** [comment]
yeah, its the same, thanks
