### ISSUE TITLE
Players can spawn inside blocks on their first spawn.

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1430]
[5.5.4]

Created a test world to test how the world border works, got stuck inside a wall when I joined. World was done generating and doesn't seem to have any other issues. 

Unclear as to whether this is an issue that can be fixed, but I felt it was worthy of its own issue as I did not see another one for it.

Relevant world file attached, haven't been able to test if the bug happens for other players. 50x50 world, otherwise default worldgen settings.

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/970326/Game.zip)

**Comment by craig-jong** [comment]
set spawn location
