### ISSUE TITLE
USER ISSUE: Not able to walk (use w + s) if someone is using excavator in dig mode

### ISSUE THREAD

**Issue by konradmoesch** [StrangeLoopGames/EcoIssues#14308]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
One player uses excavator in dig mode
Other player tries to walk

**Expected behavior:**
Other players should be able to walk

**Actual behavior:**
Other players not able to walk (w + s key locked, but a + d working)

**Comment by SlayksWood** [comment]
dup #12895
