### ISSUE TITLE
Hosted worlds may display server website in russian

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14316]
One hosted worlds customer experiences the server website to be in russian.
In his web ui he has no access to localisation.eco, but only localisation.eco.template (which he should NOT be able to edit), and that one contains "english", which is correct. There must be some sort of issue.

**Comment by D3nnis3n** [comment]
Detail:
Newly setup server on hosted worlds by default start with "Russian" as language.

**Comment by j3fffff** [comment]
havent seen this with all our test worlds. think the bug has crawled back to whence it came.
