### ISSUE TITLE
Hosted Worlds can't be set public

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14315]
This is what the hosted world user sees in his web ui:
![hostedworlds](https://user-images.githubusercontent.com/25908592/71870869-9dd1c280-3117-11ea-8780-7741a42f6d16.jpg)

This is what is saved in the config:
{  "PublicServer": false,  "Playtime": "",  "Password": "",  "Description": "Ecocracy Test",  "DetailedDescription": "Ecocracy Test",  }

(PublicServer = false; it does not work!)

**Comment by mirasrael** [comment]
Is it still an issue?

**Comment by denysaw** [comment]
As I remember we've solved it long time ago in trello. Please, re-test.

**Comment by D3nnis3n** [comment]
The player that had the issue no longer has a hosted world.
