### ISSUE TITLE
[0.9.0 staging-1326] Small time for Butcher animal recipes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14323]
6 sec.
![image](https://user-images.githubusercontent.com/45708377/71890340-1c992080-3155-11ea-81c7-6dddc3043758.png)

**Comment by WeaselDog** [comment]
It is a visual issue with the parent recipe, the individual recipe have the correct time. Should change the craft time for ButcherAnimal to 2 minutes.

**Comment by SlayksWood** [comment]
Iadd separate issue because it always uses craft time from parent recipe. #14355
MountainGoat time seems wrong.
![image](https://user-images.githubusercontent.com/45708377/72044338-98fe4180-32c4-11ea-9a5a-fcbb066c244e.png)
But I still have some suggestion:
Take as basic Bison time = 6 minutes or 360 sec. I get 10 Raw Meat + 2 LeatherHide =  12 items per order => 1 item = 30 sec.
So:
Bighorn = (6+1)*30 = 210 sec or 3,5 min.
Deer, Elk, MountainGoat = (5+1)*30 =  180 sec or 3 min.
Fox, Wolf = (2+2)*30= 120 sec or 2 min.
Hare, Otter, Turkey = (1+1)*30 = 60 sec or 1 min.
It's look more logical. You can use 

Don't want to make separate issue add to this: add LeahterHide and FurPelt to parent recipe. And need to add new Animal.

**Comment by SlayksWood** [comment]
After discussing in balance party we can reduce bighorn to 5 Raw meat and add it to Deer/ELk/Goat Group.

**Comment by SlayksWood** [comment]
Close this issue and add separate because it another problem
