### ISSUE TITLE
[0.9.0 staging-1327] The first district is highlighted when viewing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14328]
![image](https://user-images.githubusercontent.com/45708377/71896959-355e0200-3166-11ea-8331-d879e550d541.png)

**Comment by johnkslg** [comment]
Make the setreadonly function clear this selection

**Comment by SlayksWood** [comment]
Still an issue, but now I can change highlighting district.
![image](https://user-images.githubusercontent.com/45708377/72781258-eddd7880-3c31-11ea-8d67-f3dba8961b81.png)
