### ISSUE TITLE
[0.9.0] New Bows need Tool System

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14329]
The 3 Bows need a System like the other Tools.

different damage
durability
etc.

in the moment all use the same BowItem.cs from tools and are Items not tools

**Comment by johnkslg** [comment]
Not sure if this is still relevant, they derive from Item:
![image](https://user-images.githubusercontent.com/3536496/72233029-be67a580-3579-11ea-9105-420524e4dadd.png)

But I thought they were meant to derive from Weapon
@StanKryvenko Can you investigate and follow up with @Sekor2600
