### ISSUE TITLE
[0.9.0 staging-1326] Piece of meat has wrong position on Butchery table

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14324]
![image](https://user-images.githubusercontent.com/45708377/71890509-7d285d80-3155-11ea-8d20-61f22634a344.png)
Also animation absences.

**Comment by SlayksWood** [comment]
position is correct, but animation is still missing:
![image](https://user-images.githubusercontent.com/45708377/81802502-e1519880-951e-11ea-82ef-fcb79472b823.png)

**Comment by RobertMangano** [comment]
started to investigate this, can find no errors in the fbx file so must be something in unity.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/3d5f3d17-6fd9-43fa-aa44-299e9e5ddb7f)

Fixed in develop, just had to re-drag the model into the prefab in unity and delete the old model/structure.
