### ISSUE TITLE
[0.9.0 staging-1326] Can't change volume sound of main menu

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14326]
I set all to 0 but I still have sound at main menu:
![image](https://user-images.githubusercontent.com/45708377/71892010-f7a6ac80-3158-11ea-9d5c-36652e165298.png)

**Comment by SlayksWood** [comment]
still an issue

**Comment by Quadbro** [comment]
SFX bar disables completely all backgrounds sounds in main menu, can't reproduce

**Comment by SlayksWood** [comment]
Seems fixed.
