### ISSUE TITLE
Add possibility to change reputation by laws

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14325]
You add it for Work Party. And it will be nice to have it as effects in Laws.
For example You can add laws that prevent you to kill any animals if you have bad reputation. So You need to get this reputation from another player. 
If it will realease together with this issue #7253 It can be as alternative currency.

**Comment by johnkslg** [comment]
Great idea! Added.
![image](https://user-images.githubusercontent.com/3536496/71919099-ac7ca180-3138-11ea-98e2-5e3da6ccdde6.png)
![image](https://user-images.githubusercontent.com/3536496/71919199-eea5e300-3138-11ea-8491-4db02d3b0d20.png)
 
![image](https://user-images.githubusercontent.com/3536496/71919211-f5345a80-3138-11ea-9c97-bca27ca5ad79.png)
![image](https://user-images.githubusercontent.com/3536496/71919226-00878600-3139-11ea-8eb1-44d541618b9a.png)
![image](https://user-images.githubusercontent.com/3536496/71921208-447c8a00-313d-11ea-815f-9de69abe6d74.png)

![image](https://user-images.githubusercontent.com/3536496/71921256-5d853b00-313d-11ea-9a69-7a69632aef78.png)
![image](https://user-images.githubusercontent.com/3536496/71921271-637b1c00-313d-11ea-8333-c312424ea0db.png)

Fixed number entry to allow negatives too.

**Comment by johnkslg** [comment]
(only took an hour so I went ahead and did it for 9.0)

**Comment by johnkslg** [comment]
Also added a reputation value for players
![image](https://user-images.githubusercontent.com/3536496/71922038-fff1ee00-313e-11ea-93dd-004948156c71.png)
