### ISSUE TITLE
New [Laws] and [Chat] groups of icons should import into Eco.unity through the ItemDump from the Server

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14337]
Icons in eco.unity are imported from the ItemDump folder, and then populate lists under 'Items' where we can hook up icons.
![image](https://user-images.githubusercontent.com/14983165/71950956-107d8500-318e-11ea-8339-2c266cd2a3ce.png)
There should be more items in the [Laws] category than are there at the moment-- but when I do an import, done by clicking this button on the 'Items' game object:
![image](https://user-images.githubusercontent.com/14983165/71951001-3440cb00-318e-11ea-9937-50b6f94518e4.png)
Nothing new populates-- somewhere, the new law actions need to be set to export using the menu option on the server which updates the ItemDump folder:
![image](https://user-images.githubusercontent.com/14983165/71951015-4cb0e580-318e-11ea-9468-556ce1afe36d.png)

**Comment by johnkslg** [comment]
Fixed!
