### ISSUE TITLE
After removing workparty button, missing top connector piece

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14330]
![image](https://user-images.githubusercontent.com/3536496/71916087-fd3ccc00-3131-11ea-951e-82f999747025.png)
There should be a little UI piece connecting the work order here to the top of the screen.

**Comment by beastyn** [comment]
Nope, still is hanging in the air.
![bandicam 2020-02-19 14-40-12-958](https://user-images.githubusercontent.com/27898520/74821706-d45d4880-5325-11ea-9262-3b657c670120.jpg)

**Comment by beastyn** [comment]
Do we really need this huge element there? Can we connect to the top with this metal-like element?
![bandicam 2020-03-06 11-55-13-570](https://user-images.githubusercontent.com/27898520/76059695-5fcf0e80-5fa1-11ea-8682-e46870aaf26a.jpg)

**Comment by johnkslg** [comment]
@serpopov up to you and milenko
