### ISSUE TITLE
Stockpile Ate My House :'(

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1433]
I tried to place a stockpile inside my house, where it overlapped with the wall.  It got placed, and took all the blocks from my house - including the roof above it - and put them in it's storage :(  I would expect it not to get placed.  Especially since it's hard to tell how tall it needs to be and whether the roof is tall enough.

Then after this happened, KeyNotFound exceptions started getting thrown in ControllerManager.PackageMember, line 381 (memberName == "CurrentRoom")

![image](https://cloud.githubusercontent.com/assets/23460210/25631363/09d836a0-2f25-11e7-957d-f49b4fa55d38.png)

**Comment by MarjieAVolk** [comment]
Also, the stockpile seems to count as a wall, for it's max volume, even if it is empty

**Comment by MarjieAVolk** [comment]
This time, the stockpile ate my house without giving me the wood back

**Comment by metachronism** [comment]
nom nom nom

**Comment by MarjieAVolk** [comment]
Stockpiles also shouldn't be able to get placed over trees

**Comment by metachronism** [comment]
this should be fixed, aside from the tree issue
