### ISSUE TITLE
[0.9.0 staging-1329]Need to limit max District count in Userstatus UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14338]
May be show 3 max and other districts in tooltip. Or something else:
![unknown (1)](https://user-images.githubusercontent.com/45708377/71953610-d8109200-31f3-11ea-8de5-f99318ef13f6.png)
Also need to use all free space:
![image](https://user-images.githubusercontent.com/45708377/71953675-068e6d00-31f4-11ea-8758-6d266cdbc781.png)
Districts can be with long name.

**Comment by beastyn** [comment]
Can we replace Details... with 
and X more districts (X number has a tooltip with districts list)
![bandicam 2020-01-21 12-14-22-385](https://user-images.githubusercontent.com/27898520/72783263-d14c3b00-3c47-11ea-8565-46bb1b455f95.jpg)
![bandicam 2020-01-21 12-13-58-861](https://user-images.githubusercontent.com/27898520/72783266-d27d6800-3c47-11ea-9f2e-8ac11b30b253.jpg)

**Comment by beastyn** [comment]
for checking nee this #14542 to be fixed

**Comment by beastyn** [comment]
This list should display ALL the disttricts.
