### ISSUE TITLE
Eco.exe has Stopped working as Eco loads

### ISSUE THREAD

**Issue by tomcampbell1993** [StrangeLoopGames/EcoIssues#14334]
Every time I launch the game, it loads the little tree at the bottom right succesfully, but once its done, it freezes briefly and I get the error message "Eco.exe has stopped working". This occurs just before I would usually see the main Menu. The game closes and the PC runs fine afterwards.

I have been able to play ECO normally for months until December 2020.

**Comment by beastyn** [comment]
Thank you for your report.
We need some additional info for issue processing.
1.Which ECO version do you use for playing?
2. Please, provide your PC specification (include Operating System).
3. Do you try to launch from steam or standalone version(from folder)?

**Comment by tomcampbell1993** [comment]
I am launching the Game from Steam, I have it set to keep this game up to date, so whatever is the latest version on 8th Jan 2020. I believe it is 0.8.3.1 .

I tried launching the game on the beta 8.0.7 and the game started fine and i was able to start a solo player game.

Im using MSI Windows 8.1 Intel(R) Core(TM) i7-4700HQ CPU @2.40GHz 2.40 GHz
8.00 GB Ram 64bit os

**Comment by mirasrael** [comment]
@tomcampbell1993 we had fixes for Unity crash in 8.3.2 (8.3.3) long time ago. Can you confirm issue fixed for you (and re-open issue otherwise)?
