### ISSUE TITLE
[0.9.0 staging-1327] Crafting: No way to see crafting times of child recipes 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14333]
At the crafting table, you only see the crafting time of the parent recipe. When you go to craft the child recipes, you do not see any variations in crafting times.  This is an issue for many parent recipes, including BoiledGrains, ButcherAnimal, CharFish, and CharAnimal.

![ButcheryTimes](https://user-images.githubusercontent.com/47330823/71916755-81dc1a00-3133-11ea-803c-2bf1b9223e7f.png)

**Comment by Sekor2600** [comment]
Number of products created is also adjusted to the previously specified quantity.
Exsample you only see that Bison gives 10 Meat/ 2 Leather. 
But you have 10 Bisons to craft. It should display 100 Meat 20 Leather in the Menu.

**Comment by WeaselDog** [comment]
@beastyn Need to reassign

**Comment by mirasrael** [comment]
Time for child recipes always same as for parent recipe. Even if it is different in tech tree temple - it will be ignored in code.

**Comment by WeaselDog** [comment]
Closing this and adding note in balance project
