### ISSUE TITLE
Ecopedia Categories Updates

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14341]
**Blocks:**
- _Natural Resources_
         -things like dirt, ore, logs, tree debris, rocks, crushed rock (crushed rock will spawn naturally)
- _Building Materials_
         - any block that has hammer forms
- _Crafted_
         - any block made by players that doesn't fit elsewhere, like fuels.
- _Byproducts_
         - any waste or byproduct blocks like garbage, tailings, compost

**Economy, Food, Government, and Housing** all look ok for now, I'll work on icons for them when I get back from vacation on the 21st.

**Ecosystem:**
- _Plants_
- _Plant Products_
     - all the different items you can get from plants, including trees
- _Animals_
- _Animal Products_
    - carcasses, also things like tallow, hides, skins, etc
(more will be added later, like _Biomes_ For 9.0 lets try to not require ourselves to make 1000 icons)

**Items:**
- _Tools_
- _Products_
             - anything crafted at a craft table that must be used to craft something else. We can split 
                this category up more later, perhaps make it into its own section split by profession.
- _Research Papers_
- _Fuels_

Re-name '**World Objects**' to: **Crafted Objects:**
keep all the current categories, and add:
- _Vehicles_

Re-name **'Lists'** to **This World** (and move tags to new glossary category)
- _Citizens_
- _Laws_
- _Civic Actions_
- _Work Orders_

Re-name **'Skills'** to **'Professions'**

**Glossary:**
- _Tags_

**Comment by beastyn** [comment]
- Blocks 
    still has fuels
