### ISSUE TITLE
USER ISSUE: erfahrung 

### ISSUE THREAD

**Issue by superstalker111** [StrangeLoopGames/EcoIssues#14348]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
bekomme keine erfahrung bei lagerfeuer level 

**Expected behavior:**
bekomme erfahrung

**Actual behavior:**
bekomme keine erfahrung

**Do you have mods installed? Does issue happen when no mods are installed?:**
bekomme keine erfahrung

**Comment by SlayksWood** [comment]
It's intented behavior in 0.8.3.2. You don't gain expirience from all recipes at Campfire.
