### ISSUE TITLE
[0.9.0 staging-1329] Civics: no Ciziten for user choosing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14347]
Founded in some cases. It can be placed by default but you don't see it in selection,
1. Execution office
2. In pay/tax effects
![bandicam 2020-01-08 16-47-07-947](https://user-images.githubusercontent.com/27898520/71975846-cef4e480-3236-11ea-91ec-fbe97faf0e68.jpg)
![bandicam 2020-01-08 16-48-38-614](https://user-images.githubusercontent.com/27898520/71975848-d0261180-3236-11ea-8b9e-6ff2e1747727.jpg)

**Comment by johnkslg** [comment]
Good find, fixed
![image](https://user-images.githubusercontent.com/3536496/72013861-9394ee80-3213-11ea-84dc-1e96dccc7f61.png)
