### ISSUE TITLE
[0.9.0 staging-1329] Civics: strange doubled ratification 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14346]
1. Place Capitol
2. Press Ratify
3. It will popup two OK boxes and make two notifications about voting started
![bandicam 2020-01-08 16-38-48-768](https://user-images.githubusercontent.com/27898520/71975401-afa98780-3235-11ea-940b-56319e3efb08.jpg)
![bandicam 2020-01-08 16-39-12-915](https://user-images.githubusercontent.com/27898520/71975402-b1734b00-3235-11ea-866c-2be3d3df075e.jpg)
![bandicam 2020-01-08 16-39-18-766](https://user-images.githubusercontent.com/27898520/71975407-b46e3b80-3235-11ea-81b3-310fd88634a5.jpg)

**Comment by johnkslg** [comment]
Oof, this is actually high priority because its creating two refactoring elections
![image](https://user-images.githubusercontent.com/3536496/72015082-f2f3fe00-3215-11ea-8f80-d6986785364e.png)
Fixed
