### ISSUE TITLE
Map coordinate of world objects placed at 0,x,0 do not show.

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1434]
![signbug2](https://cloud.githubusercontent.com/assets/26904637/25641767/3a3f6f86-2f96-11e7-9f73-ccf74f0f08c9.png)
![signbug1](https://cloud.githubusercontent.com/assets/26904637/25641886/d471183e-2f96-11e7-840d-5813ddcc36de.png)

The coordinate 0 does not seem to show up on the minimap when hovering over a world object to see its location.

**Comment by metachronism** [comment]
not reproable on 5.6, likely been fixed
