### ISSUE TITLE
[0.9.0 staging-1329] Contracts: remove contract from board after finishing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14345]
1. Create a contract
2. Let someone finish it
3. Look at the board
![bandicam 2020-01-03 12-11-20-932](https://user-images.githubusercontent.com/27898520/71974295-fb0e6680-3232-11ea-9b6e-b082b13f1aae.jpg)
A contract is marked as removed. It just shoud disapper from the board.
It will disapper after server restart only.

**Comment by olegshegai** [comment]
New UI seems to be not fully implemented. 
Related issues:
- repeated contracts do not appear on the board (sometimes the completed one can appear there instead)
- deleted contract stays on the board until you refresh it (e.g. by clicking Create Contract)
