### ISSUE TITLE
Add a search bar to every single dropdown in the game.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14356]

**Comment by D3nnis3n** [comment]
For money transfers:
>Minted currencies should be separate from IOUs and on top of the list (most people will use those!)
>Created accounts should be separate from personal accounts and also on top of the list (for consistency)
>Search would let you find what you are looking for easily
>
>Bonus - IOU currencies should only be displayed when you actually search for them (so if you only have "Dollar" and "ThePiachu IOU" in your wallet, your list by default only has those until you start searching for "Den" and then it reveals that there is also "Dennis IOU" or the like) to make the list only contain what's useful to you - you can't make a transfer in an IOU you don't own, so why display it? If you want to transfer something, first select a proper account that has a balance!

**Comment by WeaselDog** [comment]
This has been added. Please open a new issue for any specific UI you think should have a search but doesn't.
