### ISSUE TITLE
Missing localization mega issue

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14352]
Anything without brackets
- [x] ![image](https://user-images.githubusercontent.com/3536496/72028912-21cf9b80-3239-11ea-98df-fe820d5c878a.png)
- [x] ![image](https://user-images.githubusercontent.com/3536496/72029092-aae6d280-3239-11ea-8649-baf9c7e0a206.png)
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] v

**Comment by beastyn** [comment]
#13807
#13808
#13809
#13810
#13811
#13822

**Comment by mirasrael** [comment]
Be aware about "Sever Initialization..." and "...Sever Initialization..." because client now using it to identify server startup finished.
