### ISSUE TITLE
USER ISSUE: asdsa

### ISSUE THREAD

**Issue by matvejw3** [StrangeLoopGames/EcoIssues#14357]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
sddsadadas

**Expected behavior:**
ddadasaa

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Comment by SlayksWood** [comment]
Check username and password, if you are sure this is correct, please reopen.
