### ISSUE TITLE
[0.9.0 staging-1329] Civics: "Currency used" for law needs "not" option

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14351]
I am trying to write a law that prevents trading Land Claim Papers unless you use a specific currency. This law is taken from white-tiger where you must use Dollars. It is currently not possible because the Currency Used trigger can only select currencies, not exclude currencies other than the one selected.

One option could be adding a "Not" option to the item filters for triggers. Another option could be including Currency Used as one of the conditions in the comparison box.

This is also an issue with Mint Currency & Tax laws.

![TradeTrigger](https://user-images.githubusercontent.com/47330823/72027386-a9b2a700-3233-11ea-9bbb-37f9a0cf7e72.png)

**Comment by WeaselDog** [comment]
This is a related issue for testing this:
https://github.com/StrangeLoopGames/EcoIssues/issues/13823

**Comment by johnkslg** [comment]
I dont want to add 'not' clauses under the trigger, I want it to be super simple.  But I have a solution that can work:

![image](https://user-images.githubusercontent.com/3536496/72112980-fa89d480-32f3-11ea-8362-325092993133.png)

Added a 'Currency Requirements' option that appears in conditions, if the action has a currency in it. You can then nest this within a 'not' clause to get what you want.

**Comment by WeaselDog** [comment]
Nice fix
