### ISSUE TITLE
[0.9.0 staging-1330] Fish. Balance, weight and some inconsistencies in recipes.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14359]
1. Weght.
- It is necessary to consider fish weight relative to animals. The biggest fish is sharp. It is similar in size to Wolf. So it's should weight 2 kg (I take my calculation from #14358). Other fish should less:
BlueShark = 2 kg
Tuna = 1,25 kg
Cod, Salmon  = 1 kg.
Bass, Trout = 0,8 kg
PacificSardine = 0,15 kg. It's very small fish:
![image](https://user-images.githubusercontent.com/45708377/72064886-efcc4100-32ed-11ea-8410-0046b5a0a3af.png)
With a decrease in fish weight, you can also slightly balance  maximum weight of fish trap.

- **Suggestion:** Change Raw Fish weight to 0,1 kg. (like Raw Meat)
- **Suggestion:** Maybe add efficiency from Hunting to Clean Fish.

2. Fishery recipes
I will not take into account the possible Hunting effect, so the final result will be divided by 2 (Because in new system we want max 50% effeciency). Also I will subtract 20,25%,33%(1/3) as waste products. Because Fish haven't products like LeatherHide or PurPelt.
So Fishery recipe should be like:
Blue Shark = ((2 - 0,2x2)/0,1)/2 = 8 Raw Fish
Tuna = ((1,25 - 0,2x1,25)/0,1)/2 = 5 Raw Fish
Cod, Calmon = ((1 - 0,2x1)/0,1)/2 = 4 Raw Fish
Bass, Trout = ((0,8 - 0,25x0,8)/0,1)/2 = 3 Raw Fish
PacificSardine = ((0,15 - 0,33x0,15)/0,1)/2 = 0,5 Raw Fish => You need add 2 PacificSardine to one Raw Fish.
3. Campfire recipes.
Campfire recipes should lost near 20+% so
Blue Shark = 6 Charred Fish
Tuna = 4 Charred Fish
Cod, Calmon and  Bass, Trout = 2 Charred Fish
Need 3 or 4 PacificSardine to one Charred Fish

You can use other numbers, but PacificSardine needs to be fixed.

**Comment by WeaselDog** [comment]
Pacific sardine is not the same as European sardine. They grow up to 40 cm.
https://en.wikipedia.org/wiki/Sardinops

**Comment by SlayksWood** [comment]
@WeaselDog use "/animal PacificSardine,100" and look at it in game.

**Comment by WeaselDog** [comment]
Oh I see what you mean. The model should probably be made bigger; it looks like the type of sardine you find in a can.
