### ISSUE TITLE
[0.9.0 staging-1330] Orders use craft time from parent recipe.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14355]
![image](https://user-images.githubusercontent.com/45708377/72043490-63585900-32c2-11ea-9610-da23f922dfb3.png)
It should be: 6 min; 1,5 min; 1 min; 1 min; 2 min

**Comment by mirasrael** [comment]
Craft Time can't be different for recipes within same parent recipe. It is intended behavior. Butcher recipes reworked to be more logical.
