### ISSUE TITLE
USER ISSUE: Hole in ocean water

### ISSUE THREAD

**Issue by nailfoot** [StrangeLoopGames/EcoIssues#14354]
![Water texture missing](https://user-images.githubusercontent.com/59676561/72035401-c2d44b80-3265-11ea-9d6c-74cfff140b2f.jpg)
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
N/A. Can see through several blocks of water where the surface texture is missing. Also the water appears to be trying to create waves. It is not level with the surrounding water. Screenshot included.

**Expected behavior:**
N/A

**Actual behavior:**
N/A

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods
![Water texture missing](https://user-images.githubusercontent.com/59676561/72035422-d7184880-3265-11ea-87e2-8b186bacdee1.jpg)

**Comment by beastyn** [comment]
dupe #12080
