### ISSUE TITLE
[0.9.0 staging-1332] Unable to delete deeds that contain claims

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14368]
Previously we were able to delete deeds from the Real Estate Desk or by interacting with the deed using a Land Claim Stake. It would refund our land claim papers. Now there is an incorrect error message when we try to do this:

![TestDeed](https://user-images.githubusercontent.com/47330823/72199837-9f8cd600-33f6-11ea-9670-b804b1d9ca5e.png)

We are still able to delete deeds with no claims attached. We can still unclaim property the normal way.

**Comment by beastyn** [comment]
@WeaselDog was it your desk or someone's else?

**Comment by beastyn** [comment]
Oh, I've got it. I was deleting claims. not the deed itself.
