### ISSUE TITLE
Update Description for Amanita Mushroom

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14361]
Amanita Mushrooms are poisonous and when eaten raw they causes you to lose calories. Currently they have the Fungus tag so they can be used to make Charred Mushrooms.

**Comment by SlayksWood** [comment]
@WeaselDog 
You can use for food Amanita mushrooms with proper heat treatment (charring, baking). Maybe we should not remove them? I don't eat it by myself, but at least, I knew the people who ate it.

**Comment by WeaselDog** [comment]
Interesting I did not know that. I read that toxin is water-soluble so you have to parboil first before you eat. Instead of removing them, we can update the description to educate people on this. It gives a use to the mushrooms too.

**Comment by SlayksWood** [comment]
We can add "requires Advanced Campfire lvl 2 or 3" to cook Amanita mushrooms. So we will show that people need skill for their cooking.

**Comment by WeaselDog** [comment]
I'll take over this one. The best solution seems to be to edit the description of raw Amanita Mushroom.
