### ISSUE TITLE
[0.9.0 staging-1333] Wheel Recipe Issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14372]
Rubber Wheel costs 20 Synthetic Rubber & 1 Rubber tagged ingredient. Synthetic Rubber is the only ingredient in the Rubber tag.

**Comment by SlayksWood** [comment]
Add StaticIngredient "Iron Wheel" to recipe or maybe add new Steel Wheel as ingredient for Rubber Wheel, you can't build rubber wheel without Steel or Iron.
Also have troubles with Wheel Recipe:
![image](https://user-images.githubusercontent.com/45708377/72318922-af364400-36ae-11ea-943a-db2019c9562f.png)
You craft Iron Wheel from 10 Iron wheel. I think it should be Iron bar:
![image](https://user-images.githubusercontent.com/45708377/72319014-f7edfd00-36ae-11ea-8c47-2287eb897dbe.png)

**Comment by SlayksWood** [comment]
still an issue.
![image](https://user-images.githubusercontent.com/45708377/73354302-700b1400-42a6-11ea-9bef-ea4d1013e37e.png)
