### ISSUE TITLE
[0.9.0 staging-1334] Contracts transport issues

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14378]
1. Don't have items to move when creating a transport contract
(To Move: position)
We had this list of items previously
![bandicam 2020-01-13 16-03-35-325](https://user-images.githubusercontent.com/27898520/72250797-44d5c300-361e-11ea-8a5a-db14aa237511.jpg)
2. Contractor won't see markers on the storages from a contract.
![unknown (38)](https://user-images.githubusercontent.com/27898520/72251276-62eff300-361f-11ea-9056-351ee9ce6883.png)
3. Contract can be finished without full transportation
This contract was for 20 Bricks and 20 Logs transportation.
![unknown (39)](https://user-images.githubusercontent.com/27898520/72252516-3937cb80-3621-11ea-8c1b-5213b95df04d.png)

Kirill has moved my 20 logs into his small stockpile and added 20 more logs there.
![unknown (40)](https://user-images.githubusercontent.com/27898520/72252530-3f2dac80-3621-11ea-8d15-6d75a8185203.png)

Then he moved these 40 logs to the destination stockpile.
![unknown (41)](https://user-images.githubusercontent.com/27898520/72252542-43f26080-3621-11ea-8c06-8aabbf330f43.png)

Contract was finished without bricks
![unknown (42)](https://user-images.githubusercontent.com/27898520/72252587-58cef400-3621-11ea-81c8-962dfaa8aed7.png)

**Comment by johnkslg** [comment]
Fixed markers not appearing.

The 'To Move' display was working for me, couldn't repro problem with it: 
![image](https://user-images.githubusercontent.com/3536496/74477876-ff94f300-4e60-11ea-83ce-81f295b68ba8.png)

Being able to complete the contract without transporting all resources I couldn't repro:
![Uploading image.png…]()

For moving all items: The way contract clause works, it asks the contractor to move EVERYTHING in the storage. So the user doesnt get to decide what to move out of storage, it defaults to everything. And if you change what's in that storage before the contract is accepted, then it will change whats needed to be moved in the contract. I did it this way to simplify the contract (you need to make everything you want to be moved in a single storage), perhaps someday we have an advanced transport that lets you pick and choose - but we should wait on that till we move this and other contract clauses over to work parties.
