### ISSUE TITLE
[0.9.0 staging-1333] Remove/remake Fiber tag.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14371]
There only two items in Fiber tag, Plant Fibers & Cellulose Fiber. Cellulose Fiber is a made from 30 Plant Fibers and 14 Wood Pulp.

To make a Bow with Cellulose Fiber it would take 900 Plant Fibers. To make a Bow with the normal recipe it is 30 Plant Fibers.

There is already another tag called "Natural Fibers". I suggest the "Fiber" tag is removed completely.

**Comment by SlayksWood** [comment]
or we can add Kelp to "Fiber" and delete recipe from Fishery

**Comment by WeaselDog** [comment]
Natural Fibers tag will still be there. I think this was the original goal of Fiber tag.
