### ISSUE TITLE
USER ISSUE: RequireAuthentication false does not work

### ISSUE THREAD

**Issue by caltheon** [StrangeLoopGames/EcoIssues#14374]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Run Steam in Offline Mode
Start Local Server
Attempt to connect to local server and login fails
Option to set RequireAuthentication appears to have been removed		

**Expected behavior:**
Should be able to connect to local server

**Actual behavior:**
The following error message popped up:
```Invalid Login Info
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User is offline</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```Invalid Login Info
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User is offline</size>
```

**Comment by SlayksWood** [comment]
To play, you need a network connection. This is indicated in the minimum system requirements for the game:
![bandicam_2020-01-13_15-41-13-919](https://user-images.githubusercontent.com/45708377/72249680-e94e0a00-360a-11ea-9e30-114b3325e90b.jpg)

**Comment by caltheon** [comment]
That requirement wasn't there when I originally purchased the game several years ago.

**Comment by Higgs1** [comment]
I am also expiercing this issue and will not be purchasing this game until multiplayer functionality has been restored. If any one has any ideas on fixing this issue, please contact me, thank you.
