### ISSUE TITLE
[0.9.0 staging-1334] Highlight doesn't move with plants.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14377]
In many case:
![image](https://user-images.githubusercontent.com/45708377/72248583-9410f900-3608-11ea-88ab-2da2542f11d4.png)

**Comment by SlayksWood** [comment]
and not working all the time

**Comment by SlayksWood** [comment]
> Happens if you look trough another plant.
> 
> ![20200307171151_1](https://user-images.githubusercontent.com/4980243/76145085-47412000-6097-11ea-9ff3-2a12c034bd3a.jpg)
> ![20200307171927_1](https://user-images.githubusercontent.com/4980243/76145140-e0703680-6097-11ea-8b88-921cdd32a738.jpg)

**Comment by mirasrael** [comment]
Fixed in SVN
