### ISSUE TITLE
[0.9.0 staging-1333] Remove Log & Burnable Fuel tags from Log block

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14370]
Normal logs are now a legacy item. It is nice to be able to use them for testing purposes, but they show up in the tooltips for players. At some point the tags should be removed. Adding them to the hidden category still causes them to show up.

**Comment by WeaselDog** [comment]
It is also an issue for Stone & Rock tag. Both Log & Stone should be added to hidden category as well.

**Comment by WeaselDog** [comment]
Almost everything is fixed. Stone still has Rock tag.

**Comment by SlayksWood** [comment]
I don't understand where should people remove Stones and Logs from 0.8.3?
Or we need to add it again Or we should replace it with another Block during migration.
I think we can't delete Stone and Log as non-tagged item(but can hide), so we have some troubles they have same name:
![image](https://user-images.githubusercontent.com/45708377/72316821-654a5f80-36a8-11ea-9e09-4b6c287847b0.png)

**Comment by WeaselDog** [comment]
Yes it needs to be reverted for migration unless we have a new block
