### ISSUE TITLE
Server high RAM Usage

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14388]
Save: https://drive.google.com/open?id=1RQ60Gv6z0Y6xLUT4SEfJofTLm9Qs0XDR
Graph: 
![unknown](https://user-images.githubusercontent.com/25908592/72392714-fe24bd80-3730-11ea-9375-3f873ac97f5a.png)

5-20 Players, 1,96 km² Map.

**Comment by johnkslg** [comment]
@redwyre can you take this off alex's plate and investigate?

**Comment by johnkslg** [comment]
@mirasrael could this be fixed by your fix to https://github.com/StrangeLoopGames/EcoIssues/issues/14447?

**Comment by mirasrael** [comment]
Seems to be fixed.

Data for this save:
No players:
![image](https://user-images.githubusercontent.com/475445/88527893-8d772b80-d006-11ea-862d-7ec3328a2b0e.png)

After awhile and when 1 player logged in:
![image](https://user-images.githubusercontent.com/475445/88532096-a1259080-d00c-11ea-90f3-c1ddd2c3c7f6.png)
