### ISSUE TITLE
Possible Windows 8.1 bug since 8.3.2

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14380]
Players get "Eco.exe stopped working" when starting the game. A player.log is not created.

One of the people did indeed get the same error, also on Windows 8.1 and since 8.3.2 but for him a log was created that links somewhere to NVIDIA, but drivers are recent and were reinstalled serveral times correctly as he says. That guy got a log, which you have attached.

His specs:
Windows 8.1 Pro
AMD FX(tm)-6300 Six-Core 3,5 GHz
8 GB RAM
GTX 960

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4054163/Player.log)

**Comment by D3nnis3n** [comment]
Event Log from a french user that does not get a player.log:
[eventlog.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4054211/eventlog.txt)

**Comment by redwyre** [comment]
Fullscreen issues

**Comment by mirasrael** [comment]
Exclusive Full Screen removed from available modes (until this issue fixed in Unity).
