### ISSUE TITLE
[0.9.0 staging-1336] Electric Wall Lamp: Change PowerModule

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14389]
ElectricWallLamp needs its PowerModule changed to ElectricLamp so it doesn't consume too much power.

**Comment by Sekor2600** [comment]
Streetlamp and Electric Walllamp are both 100W. For me this are "Outdoor"lamps.

**Comment by WeaselDog** [comment]
Sounds good. Closing this as intended
