### ISSUE TITLE
USER ISSUE: Olenka420

### ISSUE THREAD

**Issue by Olenka420** [StrangeLoopGames/EcoIssues#14383]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Comment by redwyre** [comment]
Are you able to log in to https://accounts.strangeloopgames.com/ ?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
