### ISSUE TITLE
[0.9.0 staging-1336] Rebalance professions for 9.0

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14390]
Most professions still need their recipes rebalanced for 9.0
- [x] Advanced Mortaring
- [x] Advanced Smelting
- [x] Basic Engineering
- [x] Bricklaying
- [x] Composites
- [x] Electronics
- [x] Farming
- [x] Fertilizer
- [x] Glassworking
- [x] Hewing
- [x] Industry
- [x] Mechanics
- [x] Mortaring
- [x] Oil Drilling
- [x] Sawyer
- [x] Smelting
- [x] Tailoring

**Comment by WeaselDog** [comment]
@Sekor2600 Will add in Carpentry & Basic Engineering on his PR

**Comment by SlayksWood** [comment]
Other changes will be in another issues.
