### ISSUE TITLE
Player Feedback: Sticky PopUps

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14403]
> 1. the description of items that pop up when you hover over items tend to stick, at least for me, making it difficult to move things around between storages, since it blocks the items behind it. It might be due to lag? One way might be to make the popup moveable, so you could place it in a corner instead of directly over the item itself.

**Comment by WeaselDog** [comment]
Haven't been able to reproduce this recently. Going to close for now.
