### ISSUE TITLE
Remove SLG accounts getting admin + dev access on third party servers

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14407]
Too abuseable and we're too big to risk it now.

**Comment by D3nnis3n** [comment]
Consider keeping /fly, /teleport (only oneself, not others) and /record (probably only on my account) for getting promotional material, those commands are safe.

**Comment by beastyn** [comment]
Soooo, we have a problem, here.
I am not a  devtier.
I am creating a world from the client (Im not aware about server stuff and so on).
I don't have admins rights in my new world (anhd I can't open server UI to add myself).
In my opinion I should have admins rights in my own world automatically.
For now I should launch server from floder and add myself to the admin list

**Comment by redwyre** [comment]
What commands do you want to use?

**Comment by Quadbro** [comment]
The problem is she can't get admin on local server through client with default account so probably smth is wrong, Can someone give me not-dev acc to test?)))

**Comment by Conchipedia** [comment]
Only way to test that this doesn't effect non developers is to have a USER account, and seeing as i am just a USER this effected me on Singleplayer, and nothing shows but USER commands, a lot of players use Singleplayer as a test world for stuff so they do need the Admin and Dev commands for a variety of things

**Comment by beastyn** [comment]
well, /fly, or /serverui

**Comment by Conchipedia** [comment]
i like using
 /eat /give /fly /durability + plus a few others on occasion

**Comment by Conchipedia** [comment]
maybe have a Tick box for Single player world when creating Admin on/off ?

**Comment by Conchipedia** [comment]
still happening in [Staging 1360] loaded up previous single player world i was Admin in and now back to a user again, This is Effecting **USER** accounts as i am Not Anything but tha.

**Comment by Quadbro** [comment]
yeah, there was local user check problem after dev access changes, fixed

**Comment by Conchipedia** [comment]
loading a world in [Staging 1375] still makes me a User not Admin

**Comment by beastyn** [comment]
Admin is fine now. I will make other issue with logic update.
