### ISSUE TITLE
[0.9.0 staging-1338] No error notification when throw out garbage on claimed property

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14405]
We do not get an error message saying we are not authorized when trying to place world objects or drop garbage on claimed property. We do get an error message when trying to place blocks. The action is still prevented in all cases

To replicate:

- Player 1 claims land
- Player 2 tries to place any world object or drop garbage on their property
- The action is prevented but no error

**Comment by beastyn** [comment]
Need to add a screen error too.
And it doesn't look like error in the main chat too.
No trash error still.

Passing to the @Quadbro as he is "Interaction Man" )

**Comment by Quadbro** [comment]
That is not an interaction problem))) But i'll take a look

**Comment by beastyn** [comment]
@Quadbro if its notification pronlem, you can pass it to Gri again. Thanks.

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/78022661-04086300-735e-11ea-9759-821c39ff6355.png)
![image](https://user-images.githubusercontent.com/45708377/78022680-0b2f7100-735e-11ea-9fdf-26843902512b.png)

**Comment by SlayksWood** [comment]
create

**Comment by gzatravkin** [comment]
Seems to be fixed for me. 
Any specific repro steps?
@SlayksWood 

I tried with /give garbage and put it at claimed territory
![image](https://user-images.githubusercontent.com/53317567/79403021-08d73480-7f64-11ea-8bac-e0f88ea62592.png)

**Comment by beastyn** [comment]
Do not take a block.

/give acorn
Then place it to the garbage can.

Blocks are working fine.

**Comment by gzatravkin** [comment]
ok, added fix in https://github.com/StrangeLoopGames/EcoIssues/issues/14405

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/80065833-74f90000-8543-11ea-8e5d-3fc6c64442f9.png)
