### ISSUE TITLE
[0.9.0 satging-1337] Web Election: no candidates for title election

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14400]
1. Create title
2. Start Election for title
![bandicam 2020-01-15 15-09-01-891](https://user-images.githubusercontent.com/27898520/72426637-edfdf400-37ab-11ea-9a22-211186b0fd73.jpg)
3. Enter the election like a candidate
![bandicam 2020-01-15 15-09-11-504](https://user-images.githubusercontent.com/27898520/72426658-fa824c80-37ab-11ea-8eea-12400ae5b77f.jpg)
![bandicam 2020-01-15 15-09-13-198](https://user-images.githubusercontent.com/27898520/72426659-fc4c1000-37ab-11ea-907c-ec2441d0a77e.jpg)
4. Open site for voting
No candidates
![bandicam 2020-01-15 15-09-38-593](https://user-images.githubusercontent.com/27898520/72426683-0a019580-37ac-11ea-9f6d-39d7f0dd73f4.jpg)

**Comment by SlayksWood** [comment]
It is missing if you click "Vote" immideately:
![image](https://user-images.githubusercontent.com/45708377/72963390-3b8be980-3dc8-11ea-801f-93df4b4617f3.png)
But it will appear after tick:
![image](https://user-images.githubusercontent.com/45708377/72963532-a4736180-3dc8-11ea-90e7-d89a956785f6.png)
@johnkslg  Is it intented for now? or we should improvement for that? Or maybe add some notification in web "waiting few minutes to update information".
In any case it's not High.

**Comment by beastyn** [comment]
So it seems to be not intentional, so high and for @Quadbro

**Comment by johnkslg** [comment]
Yes not intentional it should appear immediately.
