### ISSUE TITLE
Player Feedback: Allowing to "click" items into and out of repair stations

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14404]
> 4. Minor issue, but still. It would be great if you could place/ return tools to and from the repair station like you can with stockpiles (simply clicking it). Now you have to draw there and back. Not a deal-breaker, but perhaps easily implemented?

**Comment by SlayksWood** [comment]
With new craft system we can change it. We can add it as tagged craft:
1. Repair Wood Tool.
2. Repair Stone Tool.
3. Repair Iron Tool.
4. Repair Steel tool.
5. Repair Modern Tool.
6. Repair Chainsaw. 
This will allow a little process automation. Now If I'm smelter and I need to repair tools to the whole server .... I hate it.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/10248
