### ISSUE TITLE
[0.9.0 staging-1341] Missing swing sound for Scythe, Machete, Sickle.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14413]
There must be a specific sound for the scythe, which is different from others. Because when the scythe swings, it touches the mowed grass and makes a special sound. ANd it should different from sickle and machete.

**Comment by SlayksWood** [comment]
Swing sound occurs when I mowing grass too. They occur in one time. Either leave only grass mowing sound when mowing the grass or make a swing sound before. Also swing sound it's more missing sound. So I think it needs to make 1 option

**Comment by Quadbro** [comment]
Probably we can make such fine tunes later, but for now when tool swings - it has swing sound, if it's used on a proper block - the block interaction sound triggered independently from tool, swing  sounds for machete and scythe are adapted to animation
