### ISSUE TITLE
[0.9.0 staging-1341] Fishing: fish is running from the hook

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14410]
1. Catch a fish
2. You won't see it on the hook, but it will run away from the hook periodically in the air too
3. But you still can collect it
https://drive.google.com/file/d/1dxn0SL6ARgSk8YIYP0fLaj6bnd4srqeT/view?usp=sharing

and don't forget for 9.1
https://github.com/StrangeLoopGames/EcoIssues/issues/11931

**Comment by beastyn** [comment]
Check after fixing
Version 0.8.3.3 beta, Windows 10.

Steps to reproduce:

Fill up inventory.
Try to catch a fish.
At the point fish would've been "caught" it will freeze in midair.

**Comment by SlayksWood** [comment]
> **Version:** 0.9.0.0 beta staging-1542
> 
> **Steps to Reproduce:**
> while having a fish on the hook, reel in the fish.
> 
> **Expected behavior:**
> fish dancing around on the hook while being reeled in.
> 
> **Actual behavior:**
> fish is either not visable at all or is off to the far edge of my view.
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> no mods

**Comment by SlayksWood** [comment]
We have another strange behaviour in staging-1592:
https://drive.google.com/file/d/1K3zAxU3XXISieIF-7E2ALGIPi4oksB_4/view?usp=sharing
