### ISSUE TITLE
[0.9.0 staging-1341] Hammer sound troubles.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14412]
1. Sound of hammer picking up is very similar to pickaxe sound:
2. Sound of hammer placing is missing.
3. Missing swing sound.
https://drive.google.com/file/d/1W2mOSu_UUQwPA32ig-5hQ6PP9V_eoxaX/view?usp=sharing

**Comment by Quadbro** [comment]
Swing fixed

**Comment by Quadbro** [comment]
Placement is fixed
