### ISSUE TITLE
[0.9.0 staging-1341] Audio: Pickaxe new sound

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14415]
1. We have different sounds for breaking a stone and part-stone (yellow part). It sounds like trying-to-brake rubble part. But why? Process and material is the same (we had this issue in the 8.3 too)
https://drive.google.com/file/d/1LZXDdyuXa7RgfsZVcLmT7yMIfaJnSZx5/view?usp=sharing
2. For rubble the sound is quite... too metallic. It was smoother in 8.3
https://drive.google.com/file/d/10ZNH3g2XlogDHaSkfYnN_DyYXLHmmqCs/view?usp=sharing
3. For a rock the sound is strange (I think its because it has two parts. One is metal-stone. and one is more muffle - from stone). Or its like old sound + new sound
in 8.3 it was like just muffle one
https://drive.google.com/file/d/1PJ-6RGyy5eN8BNp5fEEpXiEOkg-3jcTV/view?usp=sharing

**Comment by Quadbro** [comment]
block and tool sounds are separeate now, we always have tool sound on a block, and actual block sound on tool impact

**Comment by Quadbro** [comment]
1. Fixed
