### ISSUE TITLE
games crashes when scrolling down in store list

### ISSUE THREAD

**Issue by d4nlo3008** [StrangeLoopGames/EcoIssues#1442]
when scrolling down in the store list, the game crashes and you are receiving this message:

http://prntscr.com/f4rurh

**Comment by MarjieAVolk** [comment]
This sounds a lot like a bug that we fixed a while ago.  If you are not on the most recent version, then try updating to the most recent version.

The issue that was fixed is that tooltips throw exceptions for items that have listings in a store somewhere, but are out of stock.  I believe that's what it was.

**Comment by d4nlo3008** [comment]
@MarjieAVolk Alpha 5.5.4

**Comment by MarjieAVolk** [comment]
Hm okay so maybe it is a new bug.  I am going to put some safe guards around tooltips so they stop crashing things.

So this looks like it is caused by hovering over a particular item.  Could you figure out which item you are hovering over when this happens?

**Comment by d4nlo3008** [comment]
@MarjieAVolk Its in the "for sale-section", down below the item right next to the "stone brazier" that causes the crash.

**Comment by MarjieAVolk** [comment]
I can't really tell which item is below Stone Brazier, because you can have different content in the window depending on the game state, and you can change the width of the window, etc.

**Comment by d4nlo3008** [comment]
@MarjieAVolk 

its the item, right next to the stone brazier, that is causing the game crash:

![screenshot_34](https://cloud.githubusercontent.com/assets/20752682/26320693/15ae3830-3f24-11e7-8da1-56e38a7d30de.jpg)
![screenshot_36](https://cloud.githubusercontent.com/assets/20752682/26320695/18037c3a-3f24-11e7-9ce9-bc6257afe004.jpg)

crash message:
![screenshot_35](https://cloud.githubusercontent.com/assets/20752682/26320698/1cc09ba4-3f24-11e7-9650-571c9215e227.jpg)

**Comment by MarjieAVolk** [comment]
Thank you, that's very helpful -- I will work on this now

**Comment by d4nlo3008** [comment]
@MarjieAVolk I really appreciate that!
