### ISSUE TITLE
 [Staging 1341] Burnable Fuel Shows Tooltip, but unlike other tooltips you cannot move mouse down to see info on items shown

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14424]
**Version:** 0.9.0.0 beta staging-1341

![snap5952](https://user-images.githubusercontent.com/29383891/72655840-2f9ac480-398f-11ea-82b6-5aca68bc6783.png)
as you can see above, if you hover mouse over Burnable Fuel it shows what can be used, but as soon as you try and move mouse down to see info about one of the items shown the window closes

**Comment by WeaselDog** [comment]
I have the same issue with Liquid Fuel and Fat
