### ISSUE TITLE
Crafting Time and Resources Multiplier not functioning

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14429]
As of Sekoris:
- Crafting Time Multiplier seems to generally work, but not with all recipes
- Crafting Cost Multiplier doesn't work at all

This is a long advertised and countless times promised feature to ease the strain for singleplayer people and easily allow multiplayer servers to adapt their values, too.

**Comment by Sekor2600** [comment]
Some Recipe like HewnLogs are not higher in Crafttime. Same with Boards or charred Mortar.
I only see the context that this recipe only has seconds by default.
And ParentRecipe have no higher Crafttime

**Comment by SlayksWood** [comment]
Seems work, but you need server restart.
