### ISSUE TITLE
Hosted Worlds and Website Review

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14422]
![image](https://user-images.githubusercontent.com/3536496/72648825-df8d1500-3930-11ea-82f2-fb80186e20ec.png)
- [x] Text is compressing when you up the size (ctrl + mousewheel)

![image](https://user-images.githubusercontent.com/3536496/72652898-8081cd00-393d-11ea-8d9d-a700767dd4b9.png)
- [x] This learn more button didnt do anything. And I'd change the headline to be something like 'Host your own Eco World 24/7' sounds a little sales-y as is

- [x] Site is missing content:
https://accounts.developland.strangeloopgames.com/hostedworlds

![image](https://user-images.githubusercontent.com/3536496/72654612-25ec6f00-3945-11ea-8911-c6f9d0f790e2.png)
- [x] On this main page, right under 'download game', add 'Your hosted worlds' and a 'View' button that will take you to the page to view them, and act as communication that the feature exists for those that dont, allowing them to sign up on the resulting page. 

![image](https://user-images.githubusercontent.com/3536496/72655458-909fa980-3949-11ea-8f3e-23fee26ff75b.png)
- [x] After purchasing, a note came up at the bottom (missed it at first) that newly bought items were processing. This should be front and center, and prevent any other activity from happening (I can still mess with stuff while it's processing)

![image](https://user-images.githubusercontent.com/3536496/72655483-bf1d8480-3949-11ea-8336-f6443c547d31.png)
- [x] While waiting for them to process, it was taking a long time, I tabbed over to strangeloopgames.com/worlds and refreshed, and there was my world.  The processing label didnt go away even though the world got setup. We should never leave the user hanging like that, even (and ESPECIALLY) if there is an error.  Can you handle all cases that would result in them sitting staring at this 'processing' label 

![image](https://user-images.githubusercontent.com/3536496/72655532-0146c600-394a-11ea-875e-27e4c23d31d0.png)
- [x] This list of worlds needs a header, showing me what I'm looking at.  'Worlds You're Hosting'. 

![image](https://user-images.githubusercontent.com/3536496/72655558-29cec000-394a-11ea-9361-547de8a529ab.png)
- [x] There are other relevant options in this menu, but its buried in with the rest of the options that take me all over the place (like back to the SLG homepage, etc).  These options need to be specially displayed and called out, probably as major tabs on the screen.  We need a sense of hierarchy, so when youre in the hosted worlds you can clearly see what are the other hosted world pages you can go to. When theyre mixed in with dozens of pages its unclear.

In general I dont like all these shortcuts showing up.  We dont need this menu at all for example: 
![image](https://user-images.githubusercontent.com/3536496/72655587-613d6c80-394a-11ea-85c8-bc5923ceb042.png)

It's just confusing people about the flow and what they need to do. If they want to get that info, they can go over to the Eco homepage and then find it. I want to reduce the set of selectable options to the feature set for the section youre in (hosted worlds), and then if they want others they can just go back to the Eco homepage and find it elsewhere. 

![image](https://user-images.githubusercontent.com/3536496/72655621-8c27c080-394a-11ea-9c0f-66d061fb9183.png)
- [x] World image was not showing, just a missing link.  If its loading still, it needs to explain that.  

- [x] Add the age of the world and a list of users currently playing to this main dashboard. 

- [ ] Once the map loaded, it wasnt displaying water where it should have, lots of ugly dirt

- [x] Server options panel that expands looks awesome!  Check to confirm awesomeness.

![image](https://user-images.githubusercontent.com/3536496/72655701-15d78e00-394b-11ea-93fd-8ad1d5bdbaf4.png)
- [x] This dialog is drunk. 

- [x] Explain things on the panel somehow like 'pending', what does it mean? And options (hidden, public, etc, whats the difference)

- [x] How do you view citizen passwords? I could only reset it, then it would show it.  If so thats fine, but make the reset dialog be a popup box. 

![image](https://user-images.githubusercontent.com/3536496/72655753-82528d00-394b-11ea-8a76-9f4eec2baf28.png)
- [x] Add a description for what 'citizens' means here

![image](https://user-images.githubusercontent.com/3536496/72655771-9ac2a780-394b-11ea-9b88-45a50a5b3e61.png)
- [x] I clicked 'Add More Accounts' and it took me to this page with this weird disabled area at the bottom 

- [x] I couldnt change my subscription to be more than 1 world.

**Comment by rainfarmer** [comment]
@denysaw I checked the ones I updated or am working on. can you look into the rest? ask me any questions you have on them.

**Comment by denysaw** [comment]
Ok, sure.

**Comment by denysaw** [comment]
Done my checkboxes, except: 

`Once the map loaded, it wasnt displaying water where it should have, lots of ugly dirt`. We're just loading this image from world's server. So it's the world side, which generated it. Couldn't be solved on this side.

`How do you view citizen passwords?` oh, I've already changed same as we decided to change on `staging` version: now it's not generate, but manually `set`. You click on `Set new password`, enter it, unfocus input and it'll be saved.

`While waiting for them to process, it was taking a long time, I tabbed over to strangeloopgames.com/worlds and refreshed, and there was my world.`
Yeah, we had just 1 7sec. timer to refresh a page and if payment went well later user was just stuck with this message forever until manual page reload. Now I've removed timer and each 3 seconds I'm ajax-calling the server to know did it go or still going. After it finish to process I'm reload the page (it'll be already without notification).
