### ISSUE TITLE
server

### ISSUE THREAD

**Issue by shtempelksp** [StrangeLoopGames/EcoIssues#14437]
Я хочу играть в соло. На серваках у меня баг их вообще нет. создать свой мир не дает, пишет ошибка, играть нет возможности, вчера купил

<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.

Log File:
SETUP - COM already setup - threaded VI might not be possible
 
(Filename: C:\buildslave\unity\build\External\videoInput\videoInput.cpp Line: 1352)

Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path I:/Program Files/1/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
d3d11: QueryInterface(IDXGIFactory5) failed (80004002).
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD FirePro W7100 (ID=0x692b)
    Vendor:   
    VRAM:     8165 MB
    Driver:   26.20.11018.6
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.143035 ms
Curl error 7: Failed to connect to config.uca.cloud.unity3d.com port 443: Timed out

 
(Filename: C:\buildslave\unity\build\Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

Curl error 7: Failed to connect to auth.strangeloopgames.com port 443: Timed out

 
(Filename: C:\buildslave\unity\build\Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

Error requesting voice login token: Network error
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Curl error 7: Failed to connect to cdp.cloud.unity3d.com port 443: Timed out

 
(Filename: C:\buildslave\unity\build\Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

Curl error 7: Failed to connect to cdp.cloud.unity3d.com port 443: Timed out

 
(Filename: C:\buildslave\unity\build\Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

Curl error 7: Failed to connect to cdp.cloud.unity3d.com port 443: Timed out

 
(Filename: C:\buildslave\unity\build\Modules/UnityWebRequest/Implementations/TransportCurl.cpp Line: 799)

Connecting to 85.113.60.30:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
AddServerUI:OnAddServer()
Steamworks.PlayersRefreshComplete:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.EventHandler`1:Invoke(Object, TEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Не удалось подключиться - время соединения истекло.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 88963.
Total: 187.581304 ms (FindLiveObjects: 5.695887 ms CreateObjectMapping: 6.324871 ms MarkObjects: 175.211416 ms  DeleteObjects: 0.348736 ms)

**Comment by beastyn** [comment]
Добрый день.
Если ли у вас интернет-соединение? Запускаете ли вы игру через Steam или из папки?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
