### ISSUE TITLE
Wrong Web UI opening

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14438]
I had quite some reports of people that for some unknown reason got to the Web UI of a different server (often one of the official servers), when trying to open the Web UI via ingame on a different server (their own, other peoples or singleplayer).

**Comment by johnkslg** [comment]
I wonder if it happens when you disconnect and reconnect to other servers.

**Comment by D3nnis3n** [comment]
User says he has never been on the server that he is linked to.

**Comment by beastyn** [comment]
the same issue. Alex is on it #14271

**Comment by D3nnis3n** [comment]
Indeed, can close this one.
