### ISSUE TITLE
[0.9.0 staging-1342] Charred Food has wrong ingredients.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14431]
![image](https://user-images.githubusercontent.com/45708377/72720834-d77ce180-3b8b-11ea-8c41-a13765b1033c.png)

**Comment by WeaselDog** [comment]
Charred Food has been replaced with Charred Vegetable, Charred Fruit, and Charred Greens.

**Comment by SlayksWood** [comment]
No charredFood recipe was replaced, but you can add tagged ingredient. or need to change recipe. Instead 20xCharredFood add 10 CharredFruit and 10xCharredVegetable

**Comment by WeaselDog** [comment]
It is changed on the PR I submitted to use Charred Vegetable x 10; I just rechecked. I can make it  Charred Fruit x5 and Charred Vegetable x5 instead.

**Comment by WeaselDog** [comment]
I notice in the screenshot it is all the old costs and Wilted Fiddleheads is still there. Maybe it didn't make the build?
