### ISSUE TITLE
Just can't play.

### ISSUE THREAD

**Issue by Mirrani0163** [StrangeLoopGames/EcoIssues#1443]
I know, that is a horrible leading line, but there are multiple issues that I am having... Firstly, I can't join any server that I was previously playing on. I can start on a NEW server, but once I log off, the next time I log in again after closing the game the game loads to 2% and no farther. No problems when starting a new server.

HOWEVER, once I get on to a server, I can't use any items. I'm told you still right click to get access to say, a workbench, but when I right click nothing happens. I can drop dirt or wood or whatever into a table, but I can't get it out, can't activate crafting... etc. Basically if you need to right click to do anything, it's not happening. I have managed to pick up dirt and chop logs, then put them down again.

I have uninstalled, I have done the wipe, I have reinstalled...Twice, I still can't play the game. ANY help would be greatly appreciated because I really would like to be able to play again.

Toshiba Satelite C75D-C
AMD A6-7310 APU with AMD Radeon R4 Graphics 2.00 GHz
64-bit OS, x64 based processor
Running Windows 10

**Comment by MarjieAVolk** [comment]
You don't right click to access tables; you press 'E'

As for your issue with logging in though, we've had that issue reported by a couple of people.

**Comment by Mirrani0163** [comment]
Okay. I had been told by numerous people that it was right clicking in this update. Thanks for clarifying. 


It is difficult to answer when one does not understand the question. - Sarak**************************As pefa pu tet en setem. (Behold that which is said to the listeners.) **************************What a wonderful day we've had. You have learned something, and I have learned something. Too bad we didn't learn it sooner. We could have gone to the movies instead. - Balki Bartokomous

-------- Original message --------
