### ISSUE TITLE
[0.9.0 staging-1350] 32-Bit Server OOM

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14447]
I can't use a default sized world that is generated (e.g. 0,52 km² but not "the" default world) with the 32-Bit server, as it throws an OOM error when finishing initialisation. The server stays up for about one minute in which you can play on it, then shuts down. Log attached.
[log_200121011532.log](https://github.com/StrangeLoopGames/EcoIssues/files/4093136/log_200121011532.log)

This should work on release, otherwise the 32-Bit server is obsolete.

**Comment by redwyre** [comment]
Looks like the server is running out of memory trying to save the world.

**Comment by johnkslg** [comment]
This one will be pretty high priority as we need to have efficient memory usage for hosted worlds.

**Comment by mirasrael** [comment]
Can't reproduce on latest build.
Max memory consumption is about 1.1Gb:
![image](https://user-images.githubusercontent.com/475445/73943273-8564eb80-4901-11ea-8ed6-786fbe59ff63.png)

Tries both new world generation and starting existing world.

**Comment by mirasrael** [comment]
@D3nnis3n can you check on last version and also provide more details on reproduction steps and environment if you still have this issue.

**Comment by mirasrael** [comment]
Seems to be related to AMD Ryzen 3950X
