### ISSUE TITLE
[0.9.0 staging-1352] Hotkeys glitches

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14454]
It was yesterday but I wanted to investigate more (Need to look for PR after staging-1340):
- [ ] Seems Hotkeys doesn't work if I use Gibberish language.

- [ ] Sometimes I have doubleclicking. I want to open backpack, I press "B" => backpack should appear, but backpack appear at one moment and then dissapear:
I wanted to make Gif, but you can see backpack in Gif.

- [ ] Sometimes hotkeys stop working and I need to restart client. It seems that It stops working after Alt+Tab.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4096600/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4096601/Player.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4096752/Player.log)

**Comment by gzatravkin** [comment]
Can't reproduce it. Attaching video of hotkeys after alt tab in Gibberish without doubleclicking. 
https://drive.google.com/open?id=15B5HteSKqwLRvttIasUKvqO3SvMBzfsn
Can you sumbit video with reproduction of issue?

**Comment by beastyn** [comment]
Just reproduced like that:
1. Cleint - Gibberish. Server - English.
2. Start server. Enter the game. Everything is fine
3. Log out. Don't close the client. Restart server. Enter the game - no hotkeys.

I had problems yesterday even with English-English after every server restart.
And as i see the main step for me - log out, but don't close the client. And restart server.

**Comment by Conchipedia** [comment]
still a problem in [Staging 1355] on single player world that when pressing z b etc the windows open and close with a juddering motion sometimes they open no problem, sometimes they wont stay open and if you close UI and reopen it no hotkeys work at all and disconnecting does nothing ONLY a total quit of Client will solve the issue of making hot keys work again on next load

**Comment by Conchipedia** [comment]
Still happening in [Staging 1360]

**Comment by SlayksWood** [comment]
Still "doubleclicking" for me. @Conchipedia do you have it in staging-1375?

**Comment by Conchipedia** [comment]
still doing the same in [Staging 1375]

**Comment by Conchipedia** [comment]
also in 1378

**Comment by Conchipedia** [comment]
[Staging 1380]
Serious problem when Hotkeys go when trying to build, you get stuck with the choose building form window open, it will not close
![snap6142](https://user-images.githubusercontent.com/29383891/73594299-f3c23c00-4504-11ea-9e95-0ca0e73d5349.png)

And you can still Access A table and storage with it open
![snap6143](https://user-images.githubusercontent.com/29383891/73594315-1bb19f80-4505-11ea-8a3e-df3fe30fed6a.png)

nothing seems to force it to close, i can craft with it stuck open, i can even open the Ecopedia and i would have thought that opening another window would override the Build one, but it still is still open

only thing that makes the Window close is disconnecting
