### ISSUE TITLE
Servers do not show up on server list

### ISSUE THREAD

**Issue by Pingperfect** [StrangeLoopGames/EcoIssues#1445]
Eco does not appear to like multiple IP's on the same box or multiple servers using differing ports for some reason. You can connect to them fine using the IP/Port but only some show up on the serverlist.

Our current workaround is simply to move services to IP's and find one that shows up on the serverlist.

**Comment by metachronism** [comment]
Jeff, is the listing service not handling pings from the same IP/different port properly?

**Comment by rainfarmer** [comment]
Needs to be updated, will do soon.

**Comment by metachronism** [comment]
closing as dupe of #1096
