### ISSUE TITLE
[0.9.0 staging-1352] Glitch when drawing district.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14456]
Step to reproduce:
- place Zoning Office and start to create district. Add 5 districts(for example):
![image](https://user-images.githubusercontent.com/45708377/72890248-8d7a3400-3d22-11ea-8eb8-6711650dbc47.png)
- Select District 18 and move mouse to Green Zone:
![image](https://user-images.githubusercontent.com/45708377/72890344-b7cbf180-3d22-11ea-8260-c6bbaf3d6f2e.png)
- Hold RMB and draw some District 18. Without Releasing RMB move cursor to Red Zone and release RMB.
- select Another District and doen't press RMB move cursor in Greeen zone. You can draw without pressing RMB.
https://drive.google.com/file/d/1VpAx6Km4lo1AyQfgcRJvB80KbJasYWj_/view?usp=sharing

**Comment by IcedForge** [comment]
Fixed in map refactoring on 0.9.2.0 develop 111
