### ISSUE TITLE
[0.9.0 staging-1354] Glitch of selecting subcategory  in Ecopedia.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14457]
Step to reproduce:
- open Ecopedia:
![image](https://user-images.githubusercontent.com/45708377/72892645-1b0c5280-3d28-11ea-814b-8863ec095104.png)
- You can change category. For example select Economics components:
![image](https://user-images.githubusercontent.com/45708377/72892676-2d868c00-3d28-11ea-94e5-065ef02f80a5.png)
- hide all Categories:
![image](https://user-images.githubusercontent.com/45708377/72892687-337c6d00-3d28-11ea-8e1e-a01d95b2b4f5.png)
- Press "Show only discovered items"
![image](https://user-images.githubusercontent.com/45708377/72892732-573fb300-3d28-11ea-8160-5a48664dfaab.png)
- expand all Categories and try to change subcategory. You can't:
![image](https://user-images.githubusercontent.com/45708377/72892840-9cfc7b80-3d28-11ea-8e31-8fc16af53c9b.png)
It's highlighting, but doesn't select.

**Comment by johnkslg** [comment]
Fixed! Nice find.
Some selection highlighting stuff will be fixed when #14470 is fixed.
