### ISSUE TITLE
[0.9.0 staging-1354] Sound disappears in Ecopedia

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14458]
Step to reproduce:
- open Ecopedia. You have sound when you switch category and subcategory.
- Press "Show only discovered items". Sound will disappear.

**Comment by SlayksWood** [comment]
Still an issue:
- open ECOpedia:
![image](https://user-images.githubusercontent.com/45708377/74583866-f2047800-4fdc-11ea-886d-29bcdb9555ce.png)
- change Government to Housing:
![image](https://user-images.githubusercontent.com/45708377/74583876-00eb2a80-4fdd-11ea-955f-a4bb232af50f.png)
- You have click sound.
- change Show only discovered items:
![image](https://user-images.githubusercontent.com/45708377/74583914-81aa2680-4fdd-11ea-99dd-e49bff65c019.png)
- change Housing to another category. I haven't sound

**Comment by Quadbro** [comment]
Delayed this task a bit when ecopedia will be more in finished state
