### ISSUE TITLE
[0.9.0 staging-1355] Wetland ans Rainforest overlapping eachother

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14465]
That is what we have on the fresh worlds.
![bandicam 2020-01-23 17-37-45-740](https://user-images.githubusercontent.com/27898520/72985151-24202100-3e07-11ea-9df6-27e690d60569.jpg)
![bandicam 2020-01-23 17-37-55-165](https://user-images.githubusercontent.com/27898520/72985156-25514e00-3e07-11ea-829b-6be36f6dd1fa.jpg)

Wetland is overlapping with rainforest. Ceiba and other plants are feeling quite bad there.
We need to find a place for the wetlands somewhere near rivers and lakes. And leave our gorgeous rainforests for themselves.

**Comment by WeaselDog** [comment]
This is still an issue on playtest server. It is also happened with grasslands & forest. 

It is likely the cause of this: https://github.com/StrangeLoopGames/EcoIssues/issues/14669

**Comment by beastyn** [comment]
Its the Default World probem
