### ISSUE TITLE
[0.9.0 staging-1355] Missing "Experience" in recipe tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14463]
0.9.0:
![image](https://user-images.githubusercontent.com/45708377/72982007-270f1780-3def-11ea-8c79-3325d1e59bf9.png)
0.8.3:
![image](https://user-images.githubusercontent.com/45708377/72982289-caf8c300-3def-11ea-9651-f501529b030c.png)

**Comment by beastyn** [comment]
1377 can't see
![bandicam 2020-01-30 16-40-19-892](https://user-images.githubusercontent.com/27898520/73446979-994ba300-437f-11ea-921f-589460269da1.jpg)
