### ISSUE TITLE
[0.9.0 staging-1355] Web graph: need fix for Bars info

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14467]
1. Pick some species from the Data in graph
2. Click bars
![bandicam 2020-01-23 18-08-36-787](https://user-images.githubusercontent.com/27898520/72987051-62b7da80-3e0b-11ea-94de-261553c46188.jpg)
It won't show you the info
![bandicam 2020-01-23 18-08-36-787](https://user-images.githubusercontent.com/27898520/72987241-cc37e900-3e0b-11ea-86b0-c40a508e5e18.jpg)
3. Move slider a little. At some point it will shoe tehe info. And then empty again.
![bandicam 2020-01-23 18-12-58-686](https://user-images.githubusercontent.com/27898520/72987348-02756880-3e0c-11ea-908d-8ad7ca5662ae.jpg)
Lines for comparison
![bandicam 2020-01-23 18-15-01-629](https://user-images.githubusercontent.com/27898520/72987487-508a6c00-3e0c-11ea-8088-850fb96b33fe.jpg)

**Comment by johnkslg** [comment]
@StanKryvenko this is related to another of your bugs, can you follow up with Denys?

**Comment by beastyn** [comment]
@denysaw 
I still can't get it
Here I have numbers for the graphs on the 1.6 Day
![bandicam 2020-04-02 11-30-27-045](https://user-images.githubusercontent.com/27898520/78217508-b0b92080-74d5-11ea-88bc-4c5fbab95d1a.jpg)
![bandicam 2020-04-02 11-30-31-973](https://user-images.githubusercontent.com/27898520/78217513-b1ea4d80-74d5-11ea-92c9-c9bc25835daa.jpg)

Why bars are empty for this day?
Last Bar Data is before 1.1 Day
