### ISSUE TITLE
tutorial boxes in wrong place?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1446]
![image](https://cloud.githubusercontent.com/assets/774628/25830492/19e30718-3412-11e7-98b9-4b5a79afc8f4.png)

**Comment by SeanAtr0n** [comment]
that's how the window opened for me first time, looks like the skill is scrolled offscreen

**Comment by MarjieAVolk** [comment]
Oh, yeah I totally knew about this *ashamed*

**Comment by MarjieAVolk** [comment]
Putting this in the beta milestone even though I have absolutely no idea how to fix this
