### ISSUE TITLE
Ecopedia banner images

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14472]
![image](https://user-images.githubusercontent.com/3536496/73022328-3df93e00-3dde-11ea-9040-38228f5eb863.png)
I've created these placeholders for banners in the ecopedia, only a few are used.  Add each to the page that suits it, by adding the needed code to the xml ecopedia pages:

```<section type="banner" image="EcopediaEconomy"/>```

Ecopedia pages are located here: Eco\Server\Mods\Ecopedia

Also go through all the other pages and add illustrations where it makes sense to. I'd like to make this a really rich resource to get to know the game, and each page is visually compelling and deepens the experience of the game. Feel free to tap Milenko and Rob for help on this.

**Comment by WeaselDog** [comment]
The images look great. The screenshots of the UI seem to be blurry though. Can we get one that is not in low resolution?

![Registrar](https://user-images.githubusercontent.com/47330823/89080072-c2ec8380-d33c-11ea-978c-e8dd3e99bb98.png)

**Comment by RobertMangano** [comment]
I was told that it is unity crunching them down, If you look at the asset itself it is not blurry.

**Comment by RobertMangano** [comment]
added the last of the banner images for the concepts section.
