### ISSUE TITLE
Make banner images in Ecopedia stretch nicely

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14471]
For sections with banners (like Ecopedia Overview), make the EcopediaBanner section properly stretch the size of the image across the full width, expanding the height to suit the proper aspect ratio. Had a hard time getting this to work and need some UI help here.  Make sure to make it an independent component (using the existing ones I created AspectRatioAutoFit that is meant to do this). 
![image](https://user-images.githubusercontent.com/3536496/73022208-f1adfe00-3ddd-11ea-9720-3fb64a9a3068.png)

**Comment by beastyn** [comment]
bow they seem to be stretched vertically for me)
Attention on the wheels
 ![bandicam 2020-02-10 13-59-58-625](https://user-images.githubusercontent.com/27898520/74135175-a7b27e00-4c0d-11ea-983a-68043313e204.jpg)
1920x1080
