### ISSUE TITLE
Ecopedia Ecosystem section

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14473]
Can you do a first-pass on these pages:
![image](https://user-images.githubusercontent.com/3536496/73023429-5b2f0c00-3de0-11ea-8063-cbc0d2d6e4b4.png)
Then can pass to me with anything you'd like me to fill in, like details of the simulation.
Can add illustrations too.
I've got the overview filled out so far but the rest are placeholder.  Can likely reuse text from the eco tree.

**Comment by Conchipedia** [comment]
will Species or changes
![snap6036](https://user-images.githubusercontent.com/29383891/73034731-af1c0e00-3e3d-11ea-8da7-1513fcac8cae.png)
![snap6035](https://user-images.githubusercontent.com/29383891/73034739-b4795880-3e3d-11ea-8663-84cba6d0a952.png)
be part of this section?
or will this still go on a button? 🤞

**Comment by keegan-o** [comment]
First pass complete, will continue to add more images and links and such as we go.
