### ISSUE TITLE
[Staging 1355] looking at Iron ore Doesn't show what it is like other blocks

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14478]
if i look at sandstone i see this
![snap6040](https://user-images.githubusercontent.com/29383891/73038097-17bcb800-3e49-11ea-918b-6cab4b8d2a93.png)
but if i look at Iron ore next to it, it doesn't show me what it is
![snap6041](https://user-images.githubusercontent.com/29383891/73038112-273c0100-3e49-11ea-956e-697b954e299f.png)

and this looking at stuff to get a description of it is very cool ❤️ 

haven't checked with other ores and coal as haven't found any yet

**Comment by beastyn** [comment]
merged with #13375
