### ISSUE TITLE
[Staging 1355] Tool Bench not showing anything in Tool repair tab until switching tabs

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14476]
**Version:** 0.9.0.0 beta staging-1355

Build a Tool Table, Place tool table, open tool table with E
the 1st window you see is this one
![snap6032](https://user-images.githubusercontent.com/29383891/73031684-bd196100-3e34-11ea-8384-3cd2ec29c43c.png)
now go to repair tab and nothing is showing
![snap6030](https://user-images.githubusercontent.com/29383891/73031719-d02c3100-3e34-11ea-87c3-e54a8edb8a83.png)
go to any tab and come back to repair tab and it shows contents
![snap6033](https://user-images.githubusercontent.com/29383891/73031766-eb973c00-3e34-11ea-98e0-a28c4d125a23.png)

bug can be repeated, either make a new too Bench or pick up the old one and place down

**Comment by Conchipedia** [comment]
linking to this one as its both to do with Tool Bench
https://github.com/StrangeLoopGames/EcoIssues/issues/14058

**Comment by Conchipedia** [comment]
sometimes this will happen again if not been to the table for awhile, not sure for how long and if you have been to another table first (can't quite duplicate this second happening)

**Comment by beastyn** [comment]
dup #13232
