### ISSUE TITLE
[0.9.0 staging-1355] Pump component Ecopedia issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14484]
The pump component display will not be fully implemented until 9.1 It should be hidden from the Ecopedia tabs or the component tab should be temporarily disabled.

![PumpComponent](https://user-images.githubusercontent.com/47330823/73041948-3eacc700-3e14-11ea-9f47-7066a7a7f422.png)

See https://github.com/StrangeLoopGames/EcoIssues/issues/11839 for more details

**Comment by johnkslg** [comment]
Removed pump component display
