### ISSUE TITLE
[0.9.0 staging-1355] Tool Bench: Repair Component tab vertical spacing issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14483]
For the Repair Component, there should some vertical space at the top before the drop-down menu.

![RepairComponent](https://user-images.githubusercontent.com/47330823/73040681-6cdbd800-3e0f-11ea-99ba-bfbc4e6f9429.png)

**Comment by beastyn** [comment]
mergerd here #14045
