### ISSUE TITLE
[0.9.0 staging-1355] Registrar component not functioning

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14486]
Similar to the bank in issue https://github.com/StrangeLoopGames/EcoIssues/issues/14481, the Registrar component is not functioning.

Here is a view of the tab:
![RegistrarComponent](https://user-images.githubusercontent.com/47330823/73042561-6dc43800-3e16-11ea-9acc-eaf523341246.png)

**Comment by johnkslg** [comment]
Fixed, though help button is broken temporarily.
