### ISSUE TITLE
[0.9.0 staging-1355] Revisit ore weights

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14487]
Iron Ore - 20 Kg
Crushed Iron Ore - 30 Kg
Iron Concentrate - 18 Kg

Max Carry Weight: 35 Kg. We can only carry 1 ore at a time.

**Comment by SlayksWood** [comment]
@WeaselDog 
Max Carry Weight = 35 kg It's your backpack max weight. Ore and stone you carry in hands.
We have issue with this problem #14427. 
Of course it’s strange to carry 600kg. But if you make the opportunity to carry only one stone, then it will be unplayable.

**Comment by WeaselDog** [comment]
I can't replicate it now. I had Iron Ore in my backpack somehow from using admin commands.

**Comment by SlayksWood** [comment]
@WeaselDog it can happen if you use /creative
