### ISSUE TITLE
[8.3] Dev Tool does not have full access to storage

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14480]
With the Dev Tool an admin is able to access storage to view inventory but they do not have access to add or remove items from the storage. There are many times an admin would want to do this, but it is especially important with the introduction of more unique items.

This issue must be fixed first before this feature can be added: https://github.com/StrangeLoopGames/EcoIssues/issues/13596

**Comment by beastyn** [comment]
@Quadbro  for help

**Comment by Quadbro** [comment]
Checked, was fixed in https://github.com/StrangeLoopGames/Eco/pull/6806
