### ISSUE TITLE
[0.9.0 staging-1355] Distribution Station: ItemDistribution Component text issue

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14482]
In the text for the ItemDistribution component, the word "eligible" is cut off by the button to change max days played for citizens to be eligible. In addition, it would be nice if there some space between the border and the text on the left.

![DistributionComponentText](https://user-images.githubusercontent.com/47330823/73039989-d4dcef00-3e0c-11ea-9f8a-15d31b73c83a.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/75341533-b8b5ed00-58a5-11ea-971f-23a9ff30c064.png)
