### ISSUE TITLE
IVA

### ISSUE THREAD

**Issue by IvanRolgejzer** [StrangeLoopGames/EcoIssues#14495]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Invalid parameter</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Invalid login info.

<size=60.00%>Invalid parameter</size>
```

**Comment by beastyn** [comment]
Where did you buy game? On steam ot through SLG site?

**Comment by D3nnis3n** [comment]
Hey there,
this just means that your login credentials are wrong.

Please contact support via support@strangeloopgames.com to get this sorted out.
