### ISSUE TITLE
[0.9.0 staging-1357] No authorization on vehicles 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14499]
After placing a vehicle we do not have access to them. This is true of all vehicles. The easiest way to replicate is to place a Wood Cart and try to access.
![VehicleAuthorizationIssue](https://user-images.githubusercontent.com/47330823/73093087-ac97d380-3e92-11ea-805a-bb866c00cd0b.png)

**Comment by SlayksWood** [comment]
I'm fine with vehicles:
![image](https://user-images.githubusercontent.com/45708377/73153018-39d16700-40e3-11ea-8346-84b02e43bcf4.png)
But still have troubles with claiming.
@Oleg

**Comment by olegshegai** [comment]
Yeah, it was broken for non-admins. The fix is here: https://github.com/StrangeLoopGames/Eco/pull/5493
