### ISSUE TITLE
[0.9.0 staging-1356] Crash in Ecopedia.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14490]
I understand that Ecopedia is not completed yet, but when you select from this list, Сrash occurs:
![image](https://user-images.githubusercontent.com/45708377/73049338-51171700-3e8d-11ea-90da-758caa0611fc.png)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Utils.ClientSetViewExtensions.SetClassOfProperty(Object container, Player player, String newClassName, String propertyName, Int32 listIndex)</size>
```
[crash ECOPedia.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4107098/crash.ECOPedia.txt)

**Comment by johnkslg** [comment]
Fixed yesterday 
![image](https://user-images.githubusercontent.com/3536496/73098958-4a919b00-3e9f-11ea-8f49-f7564f15deec.png)
