### ISSUE TITLE
[0.9.0 staging-1357] Currency Exchange: Client disconnect when re-ordering balance restrictions

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14498]
In the Currency Exchange, the buttons that control the order for "restrictions" actually control the order for "exchanges". This can cause the client to disconnect with a null exception. There is a related bug that impacts testing this: https://github.com/StrangeLoopGames/EcoIssues/issues/14419

**To replicate re-ordering bug:**
Setup the following situation in Currency Exchange and click the indicated button. It will reorder the exchanges on top instead of the restrictions.
![ExchangeBug1](https://user-images.githubusercontent.com/47330823/73090149-a1da4000-3e8c-11ea-9422-a52a0c7560ee.png)

**To replicate client disconnect**:
Setup Currency Exchange with restrictions but no exchanges. It will cause an exception when trying to reorder the restrictions.
![ExchangeBug2](https://user-images.githubusercontent.com/47330823/73090484-51171700-3e8d-11ea-8ffd-bc69394faef3.png)

**Log:**
```
Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.<>c__DisplayClass40_0.<Move>b__0(ImmutableList`1 x)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Gameplay.Utils.RPCListExtensions.Move(IHasClientControlledContainers hasContainers, Player player, String listName, Int32 iEntry, Int32 newIndex)
```

**Comment by johnkslg** [comment]
Fixed, thanks!

**Comment by beastyn** [comment]
Can't check, it has empty tab
![bandicam 2020-01-30 16-48-32-040](https://user-images.githubusercontent.com/27898520/73447357-5e963a80-4380-11ea-9271-629aaaae3ca3.jpg)

**Comment by johnkslg** [comment]
Fixed broken prefab
