### ISSUE TITLE
[0.8.3.2] Money transfers stops working

### ISSUE THREAD

**Issue by exp131** [StrangeLoopGames/EcoIssues#14497]
After playing 19 days with more than 300 personal accounts, about 50 additional accounts created through the bank,  and about 15 currencies are mint by the players, money transfers stop working. No error displayed, but nothing happens when a player tries to transfer the money to another player, nor another bank account, nor his accounts. Shops are working fine, but personal transfers are not.

**Comment by SlayksWood** [comment]
@exp131 
Can you provide save files?
Instruction is here:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by exp131** [comment]
@SlayksWood sure,
here is: https://drive.google.com/file/d/1JW-8vHET8MTp4u3bzV6NFmdNobeg1_aW/view?usp=sharing

**Comment by beastyn** [comment]
This save has a problem with transferring in 8,3,2.
Need to check in 9.0 after fixing  #14518

**Comment by beastyn** [comment]
From Den
World attached. Worked for the first three days, since then transfers are no longer executed. UI can be opened, transfer button "send" can be pressed, but nothing happens. UI doesn't close, no money is transferred.

https://drive.google.com/open?id=10aW_g-SXTb5-EbV5KF0DOKTINSilJhpu - DB
https://drive.google.com/open?id=142a43lqBLe-ph4bjOP32ANPFnVQw06Ib - Eco

**Comment by Elsygame** [comment]
verified, special letters break the transfers system.
![Screenshot_5](https://user-images.githubusercontent.com/53664488/73791533-ce525e00-47a2-11ea-85e9-4b9258b467b6.png)
![Screenshot_6](https://user-images.githubusercontent.com/53664488/73791534-ceeaf480-47a2-11ea-8a7d-dbbf22778a7f.png)

**Comment by Elsygame** [comment]
Test №2
![Screenshot_7](https://user-images.githubusercontent.com/53664488/73793349-7f0e2c80-47a6-11ea-920f-2b1928f82c87.png)
![Screenshot_8](https://user-images.githubusercontent.com/53664488/73793351-7f0e2c80-47a6-11ea-9cca-efd2afb5f3b9.png)
![Screenshot_9](https://user-images.githubusercontent.com/53664488/73793352-7fa6c300-47a6-11ea-9a90-a596a9d84374.png)

**Comment by Astrija** [comment]
in 0.9 too
![unknown](https://user-images.githubusercontent.com/13696708/73833542-2f1d7d00-481b-11ea-87bd-247afe6cb2bd.png)

**Comment by D3nnis3n** [comment]
Raised priority to high, as this is also occuring in 9.0.
