### ISSUE TITLE
[0.9.0 staging-1357] Ecopedia missing illustrations

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14500]
In the latest build, the Ecopedia has no illustrations. They are not being recognized in Unity.

![EcopediaIllustrations](https://user-images.githubusercontent.com/47330823/73115931-fc05f000-3ee2-11ea-8565-fe18f9fc9372.png)

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/73116614-1ee9d180-3eee-11ea-84e3-9b065b552038.png)
