### ISSUE TITLE
[9.0] Ecopedia blocks UI

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14507]
Ecopedia always opens when you only want to move items(click item to Drag and Ecoedia is open). 
This blocks the game to put things in a stockpile, for example.
Because the Ecopedia interface covers everything.

**Comment by johnkslg** [comment]
Shoot, I fixed this in my branch

**Comment by Conchipedia** [comment]
did try to search for this so not to duplicate, but glad its in the right place now 👍
