### ISSUE TITLE
[Staging 1357] loaded in Singleplayer World and Now not Admin

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14504]
**Version:** 0.9.0.0 beta staging-1357

Previously was Admin in my Singleplayer world (which is default status) loaded in the same world with this staging Version and now I cannot do anything other than **USER** commands
tried to /eat and got this
![snap6051](https://user-images.githubusercontent.com/29383891/73125352-bc500e80-3f9d-11ea-917d-b1dc756c2403.png)

Any Idea HOW to get back being Admin for a singleplayer world?

when loading in this world it came up with Converting to new format
also here is my player.log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4112375/Player.log)

**Comment by Conchipedia** [comment]
Only way i knew how to get back being an admin was to rename my world.eco and world.db files back to came.eco and game.db Load up Server which then will auto load this world and then edit Admin with my Slgid exit the server and either rename the game.eco and game.db to what it was or just load Game up from Local Worlds

**Comment by SlayksWood** [comment]
merged to #14407
