### ISSUE TITLE
[9.0] Art Error with Woodenlamp

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14514]
Only small problem.
![grafik](https://user-images.githubusercontent.com/37456949/73141904-5b9e0000-4089-11ea-86db-fab22b0dd5a7.png)
![grafik](https://user-images.githubusercontent.com/37456949/73141906-5e98f080-4089-11ea-9e9a-9270f6551db2.png)

**Comment by keegan-o** [comment]
fixed in staging
