### ISSUE TITLE
USER ISSUE: Sound of Steam Truck cuts out

### ISSUE THREAD

**Issue by nailfoot** [StrangeLoopGames/EcoIssues#14512]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
After cutting a few cebia trees with an iron axe, then driving the truck, the truck has no sound effects. A quit-and-restart fixes it. Note, I don't have to restart the entire game, just rejoin that world.

**Expected behavior:**
Sound effects of the steam truck should not cut out.	

**Actual behavior:**
After cutting trees, the steam truck has no sound.

**Do you have mods installed? Does issue happen when no mods are installed?:**
After cutting trees, the steam truck has no sound.

**Comment by SlayksWood** [comment]
After cut tree and place some log in Steam Truck storage I have good sound and haven't this issue #14421. Seems something wrong.
@Quadbro  See it please after fixing #14421.
