### ISSUE TITLE
[8.3.2] Transfer of Currency stops working arbitarily

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14519]
World attached. Worked for the first three days, since then transfers are no longer executed. UI can be opened, transfer button "send" can be pressed, but nothing happens. UI doesn't close, no money is transferred.

https://drive.google.com/open?id=10aW_g-SXTb5-EbV5KF0DOKTINSilJhpu - DB
https://drive.google.com/open?id=142a43lqBLe-ph4bjOP32ANPFnVQw06Ib - Eco

**Comment by beastyn** [comment]
merged to #14497
