### ISSUE TITLE
USER ISSUE: Mixing Roof Materials Causing Graphical Oddities

### ISSUE THREAD

**Issue by Drift3r** [StrangeLoopGames/EcoIssues#14515]
![Roof](https://user-images.githubusercontent.com/4590597/73144133-1faa7100-4070-11ea-9e97-e586d69643b0.png)

**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Create a 2 wide perimeter of mortared sandstone roof tiles around a 3x3 (or larger) section of mortared stone roof tiles, and the corners where they meet drop oddly.

**Expected behavior:**
A solid roof.

**Actual behavior:**
Corner connection drops two tiles in an odd manner.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Corner connection drops two tiles in an odd manner.

**Comment by SlayksWood** [comment]
dup #12476
