### ISSUE TITLE
[0.9.0 staging-1360] Best way to hide/expand category in EcoPedia.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14516]
Now you need to click in small square:
![image](https://user-images.githubusercontent.com/45708377/73153690-cda43280-40e5-11ea-9b36-1ca1d4491e3d.png)
But you can change it to full string as in Minimap:
![image](https://user-images.githubusercontent.com/45708377/73153736-093efc80-40e6-11ea-8de2-9f3f1b148fc4.png)

**Comment by johnkslg** [comment]
Make it play nice with the expandable button (link to another box to listen to?)
