### ISSUE TITLE
USER ISSUE: Brennofen brennt keine ziegel

### ISSUE THREAD

**Issue by Drakonos** [StrangeLoopGames/EcoIssues#14527]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. Brennofen auftrag erteilen zum ziegel brennen aus Lehm
2. Lehm sammeln
3. Lehm mit dem Handkarren zum Brennofen bringen
4. Im Brennofen Karren als Lager auswählen

**Expected behavior:**
Sollte Lehm in Ziegel brennen.

**Actual behavior:**
brennt keinen ziegel, zeit läuft ab, auftrag verringert sich nicht, lehm ist verschwunden auch nach abbruch

**Do you have mods installed? Does issue happen when no mods are installed?:**
Keine Mods

**Comment by SlayksWood** [comment]
@Drakonos can you provide log files and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Can't reproduce. Closing for no response, reopen when you can provide us with necessary information
