### ISSUE TITLE
Experience on craft without required skills

### ISSUE THREAD

**Issue by Hakuhonoo** [StrangeLoopGames/EcoIssues#14523]
Many recipes have some ExperienceOnCraft, but no required skills. What skill will gain experience on craft them?
![image](https://user-images.githubusercontent.com/11686660/73225954-0e985780-4177-11ea-878f-4341416592c1.png)

![image](https://user-images.githubusercontent.com/11686660/73226258-0f7db900-4178-11ea-8cde-318dd75b8ce0.png)
Here we have it:
![image](https://user-images.githubusercontent.com/11686660/73226275-23c1b600-4178-11ea-95cf-332d19a08e1f.png)

**Comment by Hakuhonoo** [comment]
Resolved

**Comment by beastyn** [comment]
I don't see experience info at all
![bandicam 2020-01-30 16-40-19-892](https://user-images.githubusercontent.com/27898520/73446809-4a9e0900-437f-11ea-909e-332079e2e8cd.jpg)

**Comment by beastyn** [comment]
https://github.com/StrangeLoopGames/Eco/pull/5499
