### ISSUE TITLE
[Staging 1360] Tooltip(s) not working properly on Workorder(s)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14528]
**Version:** 0.9.0.0 beta staging-1360

Example:
When you hover the mouse over the ingredient(s) required for a Bricklaying Skill book you get a tool-tip and then you can find out where to make this part from by moving mouse over the tool-tip itself for extra information
![snap6071](https://user-images.githubusercontent.com/29383891/73277895-b303b380-41e2-11ea-9527-2bc6482a1cf8.png)

**BUT**
if you try and hover the mouse over the tool-tip in a work-order you cannot use the tool-tip to show information of where to craft these as it just closes
![snap6072](https://user-images.githubusercontent.com/29383891/73278019-dcbcda80-41e2-11ea-8df8-9c5962c892e1.png)

it really should do the same thing, as it is really annoying going back and forth to original recipe and work-order  to find out where to craft something required for work-order

**Comment by beastyn** [comment]
We've lost normal tooltips on ingredients.
![bandicam 2020-02-24 16-07-44-354](https://user-images.githubusercontent.com/27898520/75147743-dc4f2b00-571f-11ea-89b6-f174355e20ee.jpg)

**Comment by mirasrael** [comment]
It didn't work only for items and Fixed now.
