### ISSUE TITLE
[8.3.2] Interface Size Problem

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14525]
> Hello,
> First, I LOVE your game. There are a few issues, I would expect that from early access. But the one that I would like to tell you about is the interface size. I am using the version that lets you scale the interface as I am visually impaired. It works great, but every time I start the game I have to go in and change the setting and then change it back. I keep it on 80% and it says 80% but it is show a lot bigger. So I move the slider down to 79 and back to 80 and it is back to the right size. Really I don't even need to move the slider, usually as soon as I click on the slider it rights itself. Not a huge problem just one I wanted to share with you as this is something you are working on for a later release.

**Comment by elfl0rd** [comment]
maybe this user not have rights to write config?

**Comment by WeaselDog** [comment]
We haven't had reports of this recently so I am going to close for now. We will keep an eye out for this.
