### ISSUE TITLE
[0.9.0 staging-1360] HW controlling issues

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14526]
1. Open fresh client
2, Connect to the playtest
3. Can't move
4. Disconnect and connect to the local server
5. Move
6. Disconnect and connect to the playtest
7. Move

Problem was detected only with HW

**Comment by johnkslg** [comment]
@redwyre I'd like to get your help on making hosted worlds work great.  Can you investigate this one with high priority?

**Comment by redwyre** [comment]
I need a player log for this. Looks like there's a bunch of code that runs on startup that if not completed (due to an exception somewhere) you can't move.

**Comment by johnkslg** [comment]
@beastyn

**Comment by beastyn** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4193867/Player.log)

**Comment by beastyn** [comment]
Never had this issue locally.

**Comment by redwyre** [comment]
that log is chock full of errors 😅
