### ISSUE TITLE
Tree wouldn't fall

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1452]
We cut down a tree, but it wouldn't fall over.  We removed the stump but it still wouldn't move.  When we dug out from under it, it disappeared, as if it were still alive

**Comment by FluxFaraday** [comment]
I've seen this twice in my 5.5.4 world.  Same symptoms, including the digging result.

**Comment by SeanAtr0n** [comment]
whoops just saw this is closed... did we change anything?

**Comment by MarjieAVolk** [comment]
No this is open - there's a duplicate bug that is closed.

**Comment by NafenX** [comment]
Sometimes you can run into the tree to make it fall over, jumping around etc too. It seems more effective if it's somebody other than the person who first chopped it.

**Comment by Nanders** [comment]
#1802

Sounds like a similar issue

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2771/whats-up-with-the-trees
