### ISSUE TITLE
[Staging 1360] Trying to move ANY item in storage just opens Ecopedia for that item

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14529]
**Version:** 0.9.0.0 beta staging-1360

![snap6073](https://user-images.githubusercontent.com/29383891/73280766-e8120500-41e6-11ea-9d92-ddede8d2cf40.png)

above image shows the carried item still in my hand but Ecopedia window is open, no way to close this and keep object in hand, this is happening on a single left click or just grabbing the item (if item is grabbed it shows up as that icon and not pointer)

**Comment by Conchipedia** [comment]
Thought this might be an Issue from loading up a previous world, so created a **new** single player world and now i am totally unable to play, 
I took the Campsite out of my Backpack placed it into Toolbar and place it on Ground, it looks like this is **only** effecting anything accessed by storage tab as backpack and Toolbar let me move stuff normally.
but there is a weird thing i can do that shouldn't even work if i try and drag the item from storage but do not let go of the mouse button the ecopedia window opens it is still in my hand and now if i press B i can place this in my backpack

**Comment by Sekor2600** [comment]
dup https://github.com/StrangeLoopGames/EcoIssues/issues/14507
