### ISSUE TITLE
USER ISSUE: glitch

### ISSUE THREAD

**Issue by polo588** [StrangeLoopGames/EcoIssues#14524]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
   my house xp and engineer xp is glitched and does not go up

**Expected behavior:**
i built a full house with rooms, and ive used the road tool and built a bunch of roads 

**Actual behavior:**
i dont get any xp for building house or roads my house xp is at 0 and enineer is still lvl 1 and a empty bar 

**Do you have mods installed? Does issue happen when no mods are installed?:**
i dont get any xp for building house or roads my house xp is at 0 and enineer is still lvl 1 and a empty bar

**Comment by D3nnis3n** [comment]
Did you claim your house? I'm not sure if using the road tool is supposed to give XP, it's not part of engineering afaik.

**Comment by SlayksWood** [comment]
Can't reproduce. Closing for no response, reopen when you can provide us with necessary information
