### ISSUE TITLE
[0.9.0 staging-1373] Change Stake description

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14539]
@olegshegai added new functions with Ctrl and Shift, so we need to change discription about it.
![72349439-98fba880-36ed-11ea-88b7-67dd7a61fba5](https://user-images.githubusercontent.com/45708377/73332214-15a68f00-4277-11ea-8e59-d0a1f360cc72.png)
Used to claim, unclaim, and examine property.
When claiming:
 -hold Ctrl to create a new deed.
 -hold Shift to choose from existing deed nearby.
When unclaiming:
 -hold Ctrl to move to nearby deed.
 -hold Shift to delete wholly deed.

**Comment by WeaselDog** [comment]
We should switch the order for unclaiming so the system is the same for swapping deeds and creating/deleting deeds.
