### ISSUE TITLE
USER ISSUE: /unstuck doesn't free you from being trapped in a repair station

### ISSUE THREAD

**Issue by ProsperCraft** [StrangeLoopGames/EcoIssues#14531]
**Version:** 0.8.3.2 beta
![image](https://user-images.githubusercontent.com/4427684/73293700-9e62f380-41c1-11ea-8fd5-3ed91e2b4b16.png)

**Steps to Reproduce:**
1. Walk in to a chunk that has not loaded yet that has a repair station
2. repair station materializes around you
3. unable to move
4. unstuck doesn't move me	

**Expected behavior:**
/unstuck moves the player
or 
Being stuck in a repair station moves the player on top of it or away from it.

or...

if a player is unable to move for a period of time, move them.

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**
No

**Comment by SlayksWood** [comment]
@ProsperCraft 
/unstuck has improvement in 0.9.0
Closed for now
