### ISSUE TITLE
[0.9.0 staging-1360] Fuel component tab says "Power"

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14532]
The Fuel component says "Power" for the tab. The Fuel component and the Power component are actually two separate components in Ecopedia.

![FuelComponent](https://user-images.githubusercontent.com/47330823/73294418-a66b6500-41ba-11ea-834a-7b6c02f55592.png)

**Edit:** For the Combustion Generator it has both components in one tab. If you click the Ecopedia help button it will take you to Power Component. There are two good options: Combine Power & Fuel component in Ecopedia or separate them in-game
![PowerComponent](https://user-images.githubusercontent.com/47330823/73296527-ba18ca80-41be-11ea-96fc-d812d689aafe.png)

**Comment by johnkslg** [comment]
I think they work well together, fuel is what provides power. Can just leave them combined? @beastyn @SlayksWood thoughts

**Comment by WeaselDog** [comment]
Yes no problem to keep them combined. We would just delete fuel tab from Ecopedia and merge the content with Power.

**Comment by WeaselDog** [comment]
The fuel component has been merged with the power component in Ecopedia
