### ISSUE TITLE
Corrupted claim name, when naming with ASCII

### ISSUE THREAD

**Issue by Sepishow** [StrangeLoopGames/EcoIssues#14534]
Name claim with this: ☺
This character works in chat and on text field on truck. But only ☺ (ALT+1) works, most others symbols just shows up as "?".

**Comment by Sepishow** [comment]
I was wrong, If you copy that symbol to chat, and send it, it brakes chat, chat window becomes empty and does not show anything, unless you turn of General tab.

**Comment by Conchipedia** [comment]
and it looks like it effects everyone's chat on server as i was wondering i was getting blank Chat window

**Comment by IcedForge** [comment]
![Screenshot_54.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8b7ec8c2-bf02-4925-9fa8-a4a067845105)

![Screenshot_55.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/482b6e3c-5d9c-4a3a-a3be-eb007d720eb4)
Confirmed working properly in 9.3, symbols that are not available should show up as ? will close for now.
