### ISSUE TITLE
[Staging 1360] [QoL] Please put something in Game about sharing tables and linking Storage

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14530]
nearly everyday someone in Discord or other chat are asking how to destroy a table that a shared player has ordered something on.
At the moment there is **nothing** in game telling people about sharing a table that every player **must** link storage before crafting otherwise a table is locked to more orders, only way round this if a Player has left that placed an order and not linked storage is to Smite it with a **DevTool**

Tutorial?
EcoPedia?
or extra Power of an Admin?

**Comment by beastyn** [comment]
Yeap, thanks, we will. Merged here #12931
