### ISSUE TITLE
Web Review

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14547]
![image](https://user-images.githubusercontent.com/3536496/73402874-148b5700-42a3-11ea-8e96-9ac5cb6a250f.png)
- [x] I'd like to clean up the menus here.  Imagine youre a new user who is just learning Eco exists, and you want to see about education, all these options are just going to confuse manners.  We should make it be a single button, education, and it takes you to the education page. 

- [x] The options 'upgrade' and 'my account' can be combined.  On the account page:
![image](https://user-images.githubusercontent.com/3536496/73403099-97acad00-42a3-11ea-9a66-54df02e5a0c3.png)
List the user's tier and description in that box, and have a button to 'upgrade tier' there.

- [x] Remove 'Logout' button, put it at the bottom of the account page. 

![image](https://user-images.githubusercontent.com/3536496/73403228-e4908380-42a3-11ea-8bec-a425c4161231.png)
- [x] I dont think we need this info box, its just navigation links to things that are right below.  Lets cull it entirely, and have top level navigation for 'wiki' 'education' and 'team' 

- [x] Add some nice faded boxes for the top level options so they look like buttons 

![image](https://user-images.githubusercontent.com/3536496/73403723-ed358980-42a4-11ea-9e97-5d4aace1da8e.png)
- [x] Describe hosted worlds in this box here.  'Host your own Eco world in the cloud'.  Add a 'More Info' button if they dont have any hosted worlds that takes them to the sales page. 
- [x] There should only ever be one button on here: 'More Info' if they dont have a subscription, and 'My Worlds' if they do.  From there, they can navigate to subscription/citizens.

![image](https://user-images.githubusercontent.com/3536496/73403408-3802d180-42a4-11ea-924c-11afda354b54.png)
- [x] Upgrade page looks funny. It should show all the tiers and show me where I'm at.  Then make the ones that I can upgrade to clickable and look like buttons (not obvious theyre buttons).  Add some text above that says 'Your current tier is X.  You may select an upgrade below'.  
Also remove the hosted worlds ad, dont need it here.

**Comment by rainfarmer** [comment]
if i remove hosted worlds sales page from menu and from buy page. 
The only place for users to find out about them is on account page.
That is ok?

**Comment by rainfarmer** [comment]
complete
