### ISSUE TITLE
[Staging 1375] When creating a Default Singleplayer world it comes up with Converting world to NEW format

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14545]
**Version:** 0.9.0.0 beta staging-1375

![snap6079](https://user-images.githubusercontent.com/29383891/73370701-8a47f080-42ac-11ea-8b72-e2517cc67627.png)

Could this be due to the Version of the **DefaultWorld** file found in Server directory?
![snap6078edited](https://user-images.githubusercontent.com/29383891/73370743-99c73980-42ac-11ea-9a14-74ec00a4e56a.png)
it does seem to be a much older File than the others

**Comment by Conchipedia** [comment]
which to me is weird as in the latest 8.3.2 Version of Eco from Steam is a Newer File than in 9.0 Staging
![snap6089edited](https://user-images.githubusercontent.com/29383891/73377560-24ad3180-42b7-11ea-8837-8c4d12a1ca95.png)

**Comment by SlayksWood** [comment]
dup #14224
