### ISSUE TITLE
[Staging 1375] opening Map window gives instant Exception when pointer is Over my name

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14546]
**Version:** 0.9.0.0 beta staging-1375

As soon as i Open Map window with M key i see it for a Fraction of a second and get the Following Exception
![snap6082](https://user-images.githubusercontent.com/29383891/73373806-1c51f800-42b1-11ea-86da-2f2cfcc0f38f.png)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4129095/Player-prev.log)

it looks like it is ON Player that the Exception happens, because as soon as you open map window the Pointer is set directly over my Name in the window, did try and move pointer as i open a window but no luck

**Comment by Conchipedia** [comment]
will also cause same Exception when hovering pointer over my name in the smaller Map
![snap6085](https://user-images.githubusercontent.com/29383891/73374767-ab134480-42b2-11ea-9c60-fb36b485d633.png)
But no problem when i hover mouse over my name in Objectives window or chat window
![snap6086](https://user-images.githubusercontent.com/29383891/73374831-c8481300-42b2-11ea-9bcd-6e20965bb6c4.png)
![snap6087](https://user-images.githubusercontent.com/29383891/73374840-caaa6d00-42b2-11ea-9fb0-ccfc6cee1d74.png)

**Comment by SlayksWood** [comment]
dup #14542
