### ISSUE TITLE
cycling backpack kicks you from server

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1454]
--BEGIN DUMP--
Dump Time
05/11/2017 13:56:18

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC CycleBack on ClothingInventory!

Could not apply inventory changes! You try to affix this item to your back, but it just slides off.

**Comment by MarjieAVolk** [comment]
Oh well.  Just fixed this today ironically
