### ISSUE TITLE
[0.9.0 staging-1376] Truck and Powered Cart sound is only for standing car.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14552]

**Comment by Quadbro** [comment]
@SlayksWood Can you tell more about the issue? what sound exactly, etc?

**Comment by SlayksWood** [comment]
Powered cart has new sound now. So fixed
Truck... has another sound too. But it's hard to hear difference between standing car and car at max speed.
https://drive.google.com/file/d/1h3IaITyDfAP2ZWxvUv1Sw1ALtImVTYqq/view?usp=sharing
