### ISSUE TITLE
[Staging-1377] Error when creating world via "Create game" ingame

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14558]
> --BEGIN DUMP--
> Dump Time
> 01/30/2020 10:53:04
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Shared
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Shared.Utils.EnumerableExtensions.ForEachReverse[T](IList`1 list, Action`1 action)
>    at Eco.Server.PluginManager.Shutdown()
>    at Eco.Server.Startup.StopAsync()
>    at Eco.Server.Startup.<>c.<<CloseWithParent>b__5_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
>    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> 
> --END DUMP--

64-Bit server started directly works.
32-Bit server started directly throws OOM which is detailed in a different issue, but does not throw this error.

**Comment by redwyre** [comment]
Do you have the log file for this? It looks like the error is when it's already decided to shutdown

**Comment by D3nnis3n** [comment]
Yes, i do. But the logfile does not show any errors:

> [10:53:32.693] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [10:53:32.706] [1] [ Info] [Eco] [Eco Server 0.9.0.0 beta staging-1377]
>  
> [10:53:32.771] [4] [ Info] [Eco] [Server Initialization]...  
> [10:53:33.015] [4] [ Info] [Eco] Starting LocalizationPlugin...  
> [10:53:33.015] [4] [ Info] [Eco] Loading mods...  
> [10:53:36.899] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
>  
> [10:53:36.924] [4] [ Info] [Eco] Loading mods... Finished in 3.904,5ms
>  
> [10:53:36.924] [4] [ Info] [Eco] Starting ModKitPlugin...  
> [10:53:36.924] [4] [ Info] [Eco] Initializing Simulation Types...  
> [10:53:36.952] [4] [ Info] [Eco] Starting NetworkManager...  
> [10:53:36.952] [4] [ Info] [Eco] Starting BackupPlugin...  
> [10:53:37.132] [4] [ Info] [Eco] Starting WorldGeneratorPlugin...  
> [10:53:37.142] [4] [ Info] [Eco] Initializing items...  
> [10:53:38.467] [4] [ Info] [Eco] Starting StorageManager...  
> [10:53:38.467] [4] [ Info] [Eco] Starting GameDataPlugin...  
> [10:53:38.467] [4] [ Info] [Eco] Starting PausePlugin...  
> [10:53:38.482] [4] [ Info] [Eco] Starting DifficultySettings...  
> [10:53:38.537] [4] [ Info] [Eco] Starting Stats...  
> [10:53:39.859] [4] [ Info] [Eco] Initializing skills...  
> [10:53:39.898] [4] [ Info] [Eco] Initializing world...  
> [10:53:39.898] [4] [ Info] [Eco] Starting WorldPlugin...  
> [10:53:39.898] [4] [ Info] [Eco] Starting TimePlugin...  
> [10:53:39.898] [4] [ Info] [Eco] Starting ReputationPlugin...  
> [10:53:39.898] [4] [ Info] [Eco] Starting PlayerHousingManager...  
> [10:53:39.945] [4] [ Info] [Eco] Initializing inventories...  
> [10:53:39.968] [4] [ Info] [Eco] Starting UserManager...  
> [10:53:39.968] [4] [ Info] [Eco] Starting EcoObjectManager...  
> [10:53:39.968] [4] [ Info] [Eco] Starting DataExporter...  
> [10:53:39.968] [4] [ Info] [Eco] Starting EconomyPlugin...  
> [10:53:39.968] [4] [ Info] [Eco] Starting GarbagePlugin...  
> [10:53:39.968] [4] [ Info] [Eco] Starting VoiceManager...  
> [10:53:39.968] [4] [ Info] [Eco] Starting PropertyManager...  
> [10:53:39.968] [4] [ Info] [Eco] Starting DisasterPlugin...  
> [10:53:39.968] [4] [ Info] [Eco] Starting MinimapManager...  
> [10:53:39.993] [4] [ Info] [Eco] Starting ChatServer...  
> [10:53:40.005] [4] [ Info] [Eco] Initializing plants...  
> [10:53:40.026] [4] [ Info] [Eco] Starting EcoSim...  
> [10:53:40.026] [4] [ Info] [Eco] Starting RouteProbingPlugin...  
> [10:53:40.038] [4] [ Info] [Eco] Starting WorldLayerManager...  
> [10:53:40.038] [4] [ Info] [Eco] Starting EconomyTracker...  
> [10:53:40.038] [4] [ Info] [Eco] Starting UserTracker...  
> [10:53:40.167] [4] [ Info] [Eco] Starting WorldObjectManager...  
> [10:53:40.175] [4] [ Info] [Eco] Starting RoomPlugin...  
> [10:53:40.175] [4] [ Info] [Eco] Starting ObjectivePlugin...  
> [10:53:40.175] [4] [ Info] [Eco] Starting SleepPlugin...  
> [10:53:40.196] [4] [ Info] [Eco] Starting CivicsPlugin...  
> [10:53:41.670] [4] [ Info] [Eco] Starting ControllerManager...  
> [10:53:41.670] [4] [ Info] [Eco] Starting WebServerPlugin...  
> [10:53:41.670] [4] [ Info] [Eco] Starting IntegrationTestsPlugin...  
> [10:53:41.696] [4] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
> [10:53:41.696] [4] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
> [10:53:41.710] [4] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
> [10:53:41.740] [4] [ Info] [Eco] Initializing LocalizationPlugin...  
> [10:53:41.769] [4] [ Info] [Eco] Initializing ModKitPlugin...  
> [10:53:42.027] [4] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
> [10:53:42.036] [4] [ Info] [Eco] Generating world 0,52km²...  
> [10:53:43.064] [4] [ Info] [Eco] Generating terrain...  
> [10:54:22.324] [4] [ Info] [Eco] Caching world data...  
> [10:54:25.811] [4] [ Info] [Eco] Placing water...  
> [10:54:26.654] [4] [ Info] [Eco] Generating special features...  
> [10:54:26.692] [4] [ Info] [Eco] Extruding cliffs...  
> [10:54:28.684] [4] [ Info] [Eco] Ticking (Pass 1)...  
> [10:54:47.663] [4] [ Info] [Eco] Initializing world layers...  
> [10:54:48.807] [4] [ Info] [Eco] Ticking world layers...  
> [10:54:54.530] [4] [ Info] [Eco] Ticking (Pass 2)...  
> [10:54:55.432] [4] [ Info] [Eco] Computing stats...  
> [10:54:55.849] [4] [ Info] [Eco] Determining visibility...  
> [10:54:55.946] [4] [ Info] [Eco] Compressing...  
> [10:55:00.498] [4] [ Info] [Eco] Generating world 0,52km²... Finished in 78.462,1ms
>  
> [10:55:00.498] [4] [ Info] [Eco] Initializing TimePlugin...  
> [10:55:00.498] [4] [ Info] [Eco] Initializing UserManager...  
> [10:55:00.670] [4] [ Info] [Eco] Initializing EconomyPlugin...  
> [10:55:00.670] [4] [ Info] [Eco] Initializing GarbagePlugin...  
> [10:55:00.687] [4] [ Info] [Eco] Initializing PropertyManager...  
> [10:55:00.687] [4] [ Info] [Eco] Initializing MinimapManager...  
> [10:55:00.715] [4] [ Info] [Eco] Initializing EcoSim...  
> [10:55:00.777] [4] [ Info] [Eco] Initializing UserTracker...  
> [10:55:00.777] [4] [ Info] [Eco] Initializing WorldObjectManager...  
> [10:55:00.829] [4] [ Info] [Eco] Initializing RoomPlugin...  
> [10:55:00.829] [4] [ Info] [Eco] Initializing SleepPlugin...  
> [10:55:00.829] [4] [ Info] [Eco] Initializing CivicsPlugin...  
> [10:55:00.858] [4] [ Info] [Eco] Initializing WorldPlugin...  
> [10:55:00.858] [4] [ Info] [Eco] Ticking...  
> [10:55:00.858] [4] [ Info] [Eco] Compressing...  
> [10:55:01.063] [4] [ Info] [Eco] Initializing ObjectivePlugin...  
> [10:55:01.063] [4] [ Info] [Eco] Initializing NetworkManager...  
> [10:55:01.083] [4] [ Info] [Eco] Initializing WorldLayerManager...  
> [10:55:01.083] [4] [ Info] [Eco] Initializing WebServerPlugin...  
> [10:55:01.699] [28] [ Info] [Eco] Web Server now listening on: http://[::]:3001
>  
> [10:55:01.702] [4] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
> [10:55:02.090] [4] [ Info] [Eco] Saving world...  
> [10:55:09.473] [4] [ Info] [Eco] [Server Initialization]... Finished in 96.701,5ms
>  
> [10:55:22.454] [308] [Error] [Eco] WARN: UPnP mapping wasn't created due to an error. Server fallback to default connection settings.
>  
> [10:55:32.416] [4] [ Info] [Eco] Saving...  
> [10:55:33.136] [309] [ Info] [Eco] Shutdown finished

**Comment by redwyre** [comment]
I can't see any reason for this to happen except when there is a crash during startup. And it looks like that log is after the crash dump according to the timestamps. Are you able to find the corresponding log file?

Also I can't reproduce this, was it happening every time or did it just happen once for you?

**Comment by D3nnis3n** [comment]
It happens every time.

Last log:
> [18:12:14.215] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [18:12:14.228] [1] [ Info] [Eco] [Eco Server 0.9.0.0 beta staging-1386]
>  
> [18:12:14.298] [5] [ Info] [Eco] [Server Initialization]...  
> [18:12:14.541] [5] [ Info] [Eco] Starting LocalizationPlugin...  
> [18:12:14.541] [5] [ Info] [Eco] Loading mods...  
> [18:12:18.629] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
>  
> [18:12:18.655] [5] [ Info] [Eco] Loading mods... Finished in 4.107,1ms
>  
> [18:12:18.655] [5] [ Info] [Eco] Starting ModKitPlugin...  
> [18:12:18.655] [5] [ Info] [Eco] Initializing Simulation Types...  
> [18:12:18.692] [5] [ Info] [Eco] Starting NetworkManager...  
> [18:12:18.692] [5] [ Info] [Eco] Starting BackupPlugin...  
> [18:12:18.870] [5] [ Info] [Eco] Starting WorldGeneratorPlugin...  
> [18:12:18.878] [5] [ Info] [Eco] Initializing items...  
> [18:12:20.025] [5] [ Info] [Eco] Starting StorageManager...  
> [18:12:20.025] [5] [ Info] [Eco] Starting GameDataPlugin...  
> [18:12:20.040] [5] [ Info] [Eco] Starting PausePlugin...  
> [18:12:20.058] [5] [ Info] [Eco] Starting DifficultySettings...  
> [18:12:20.095] [5] [ Info] [Eco] Starting Stats...  
> [18:12:21.442] [5] [ Info] [Eco] Initializing skills...  
> [18:12:21.488] [5] [ Info] [Eco] Initializing world...  
> [18:12:21.488] [5] [ Info] [Eco] Starting WorldPlugin...  
> [18:12:21.488] [5] [ Info] [Eco] Starting TimePlugin...  
> [18:12:21.488] [5] [ Info] [Eco] Starting ReputationPlugin...  
> [18:12:21.488] [5] [ Info] [Eco] Starting PlayerHousingManager...  
> [18:12:21.524] [5] [ Info] [Eco] Initializing inventories...  
> [18:12:21.556] [5] [ Info] [Eco] Starting UserManager...  
> [18:12:21.556] [5] [ Info] [Eco] Starting EcoObjectManager...  
> [18:12:21.556] [5] [ Info] [Eco] Starting DataExporter...  
> [18:12:21.556] [5] [ Info] [Eco] Starting EconomyPlugin...  
> [18:12:21.556] [5] [ Info] [Eco] Starting GarbagePlugin...  
> [18:12:21.556] [5] [ Info] [Eco] Starting PropertyManager...  
> [18:12:21.556] [5] [ Info] [Eco] Starting VoiceManager...  
> [18:12:21.565] [5] [ Info] [Eco] Starting MinimapManager...  
> [18:12:21.565] [5] [ Info] [Eco] Starting DisasterPlugin...  
> [18:12:21.565] [5] [ Info] [Eco] Starting ChatServer...  
> [18:12:21.599] [5] [ Info] [Eco] Initializing plants...  
> [18:12:21.613] [5] [ Info] [Eco] Starting EcoSim...  
> [18:12:21.613] [5] [ Info] [Eco] Starting RouteProbingPlugin...  
> [18:12:21.629] [5] [ Info] [Eco] Starting WorldLayerManager...  
> [18:12:21.629] [5] [ Info] [Eco] Starting EconomyTracker...  
> [18:12:21.629] [5] [ Info] [Eco] Starting UserTracker...  
> [18:12:21.815] [5] [ Info] [Eco] Starting WorldObjectManager...  
> [18:12:21.815] [5] [ Info] [Eco] Starting RoomPlugin...  
> [18:12:21.815] [5] [ Info] [Eco] Starting ObjectivePlugin...  
> [18:12:21.831] [5] [ Info] [Eco] Starting SleepPlugin...  
> [18:12:21.831] [5] [ Info] [Eco] Starting CivicsPlugin...  
> [18:12:24.234] [5] [ Info] [Eco] Starting ControllerManager...  
> [18:12:24.234] [5] [ Info] [Eco] Starting WebServerPlugin...  
> [18:12:24.239] [5] [ Info] [Eco] Starting IntegrationTestsPlugin...  
> [18:12:24.262] [5] [ Info] [Eco] Initializing registrars for GameDataPlugin...  
> [18:12:24.267] [5] [ Info] [Eco] Initializing registrars for EconomyPlugin...  
> [18:12:24.302] [5] [ Info] [Eco] Initializing registrars for CivicsPlugin...  
> [18:12:24.329] [5] [ Info] [Eco] Initializing LocalizationPlugin...  
> [18:12:24.363] [5] [ Info] [Eco] Initializing ModKitPlugin...  
> [18:12:24.663] [5] [ Info] [Eco] Initializing WorldGeneratorPlugin...  
> [18:12:24.663] [5] [ Info] [Eco] Generating world 0,52km²...  
> [18:12:26.285] [5] [ Info] [Eco] Generating terrain...  
> [18:13:20.042] [5] [ Info] [Eco] Caching world data...  
> [18:13:25.778] [5] [ Info] [Eco] Placing water...  
> [18:13:26.782] [5] [ Info] [Eco] Generating special features...  
> [18:13:26.822] [5] [ Info] [Eco] Extruding cliffs...  
> [18:13:29.470] [5] [ Info] [Eco] Ticking (Pass 1)...  
> [18:14:11.290] [5] [ Info] [Eco] Initializing world layers...  
> [18:14:16.467] [5] [ Info] [Eco] Ticking world layers...  
> [18:15:51.837] [5] [ Info] [Eco] Generating world 0,52km²... Finished in 207.165,1ms
>  
> [18:15:51.837] [5] [ Info] [Eco] [Server Initialization]... Finished in 217.539,5ms
>  
> [18:15:51.837] [19] [Error] [Eco] Failed to load server, Exception was Exception: OutOfMemoryException
> Message:Exception of type 'System.OutOfMemoryException' was thrown.
> Source:Eco.Shared
> 
> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at Eco.Shared.Utils.LockUtils.EnterDisposableReadLock(ReaderWriterLockSlim l)
>    at Eco.Shared.Voxel.ChunkGrid`1.GetChunk(Vector3i chunkPos)
>    at Eco.Simulation.RouteProbing.RouteManager.GetWalkableWorldBlock(WorldPosition3i pos)
>    at Eco.Simulation.RouteProbing.RouteManager.GetConnectedWorldBlock(WorldPosition3i fromWalkable, Vector3i dir)
>    at Eco.Simulation.RouteProbing.Flooding.TryMove(Func`2 checkVisited, WorldPosition3i from, Vector3i dir)
>    at Eco.Simulation.RouteProbing.Flooding.FloodFill(WorldPosition3i start, Func`2 checkVisited, Action`1 visit)
>    at Eco.Simulation.RouteProbing.RouteManager.InitRouteCache(Boolean quick)
>    at Eco.Simulation.RouteProbing.RouteProbingPlugin.<>c.<.ctor>b__1_0()

Looks like it is linked to the out of memory error then.

**Comment by D3nnis3n** [comment]
Merging with this: https://github.com/StrangeLoopGames/EcoIssues/issues/14447
