### ISSUE TITLE
[0.9.0 staging-1377] Store lost tool durability.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14559]
![image](https://user-images.githubusercontent.com/45708377/73443566-fdfb0380-4367-11ea-8107-e9e757e70ad4.png)

**Comment by johnkslg** [comment]
Working in latest
![image](https://user-images.githubusercontent.com/3536496/74107998-52517080-4b2a-11ea-9f60-ef1c2476b7dd.png)

**Comment by beastyn** [comment]
No column name for durability after adding a tool 
![bandicam 2020-02-10 17-02-07-964](https://user-images.githubusercontent.com/27898520/74148355-14864200-4c27-11ea-9bf3-21bc5033cac1.jpg)

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/74383323-d7938a00-4da3-11ea-8891-d9930c5d3965.png)
