### ISSUE TITLE
Extending Meteor time works weird

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14557]
White Tiger had the default setting of 30 days until meteor hits. Step by Step:

1. Extending Meteor time by 3 days via command on day 29, this did work, but only until restart of the server. (This is fixed by now by WeaselDog afaik)
2. Noticing the world blew up due to restart, so i changed impact time in the config to 33 days from 30 days after i restored a backup.
3. Expected behaviour: Meteor hitting on day 33, 3 days from then.
4. What actually happened: Meteor hitting on day 63, 33 days from then. (Setting config to 33 days did prolongue impact time for 33 days, instead of setting it to day 33)
5. Now, 1 day before scheduled hit time i wanted to prolongue it again via command. The command now does no longer work at all, not even until restart.
6. What will now happen if i change the meteor time in disaster.eco again? Will it blow up immediately when i set the days to impact to 15 because my 33 day prolonguing is reverted to 15? Will it be extended by 15 days again? Will it be set back to day 15? This works really badly and is totally unexpectable, especially if i think about wanting to prolongue the meteor by exactly 33 days again - that day is already in the config, so would i need to type 32, restart, then set 1 to get 33 additional days? It doesn't seem to prolongue several times by 33 days, only on the first restart.

The behaviour it should have is that no matter what is in disaster.eco, that should be the day from the beginning, when the meteor hits. So if it's day 29 and i set the config to day 35, it explodes on day 35. If it's day 35 and i revert the meteor time to day 30, it will explode on startup of the server, as the scheduled time is over.

**Comment by SlayksWood** [comment]
Didn't this #14278 fix this problem?

**Comment by D3nnis3n** [comment]
No, thats a different issue. (Point 1)

Kirill <notifications@github.com> schrieb am Do., 30. Jan. 2020, 13:41:

**Comment by SlayksWood** [comment]
- create a world with meteor = 5 days:
![image](https://user-images.githubusercontent.com/45708377/116871803-84625d00-ac1d-11eb-9510-db71f9099cdf.png)
- fastforward 4 days:
![image](https://user-images.githubusercontent.com/45708377/116872846-554ceb00-ac1f-11eb-9612-4153ff0c7e3f.png)
- Use /meteor addhours 72 nothing changes. Restart server, was added 3 days:
![image](https://user-images.githubusercontent.com/45708377/116873169-e3c16c80-ac1f-11eb-84bd-70a549ea63db.png)
- but serverUI still have 5 days:
![image](https://user-images.githubusercontent.com/45708377/116873270-110e1a80-ac20-11eb-9306-7ee89c7e4dfd.png)
- change Meteor Impact Days from 5 to 10:
![image](https://user-images.githubusercontent.com/45708377/116873316-22efbd80-ac20-11eb-9e0a-e0c851820300.png)
- nothing changes:
![image](https://user-images.githubusercontent.com/45708377/116873347-313dd980-ac20-11eb-9b58-c0b49044dbcd.png)
- restart server. Meteor time was change correctly:
![image](https://user-images.githubusercontent.com/45708377/116873538-87ab1800-ac20-11eb-8830-cfb6744fe021.png)
- use /meteor addhours 96 and restart server, 4 days was added.
![image](https://user-images.githubusercontent.com/45708377/116873916-26377900-ac21-11eb-8ae9-92a62f90048b.png)
- fastforward 10 days to check time when meteor will impact. Meteor impacts in day 14:
![image](https://user-images.githubusercontent.com/45708377/116876777-ab249180-ac25-11eb-80f9-088be08be7ca.png)
That's right.

So seems this is work fine, but we have 2 flaws.
- to update time you need to restart server
- Meteor Impact Days is not updated in ServerUI and Config.

@D3nnis3n Can you also take a look if it suits you or is it worth improving?

**Comment by D3nnis3n** [comment]
Yes, this definitely needs to change the config value, otherwise stuff becomes out of sync, as you are supposed to be able to change the meteor time via config as well, so what will happen when you used the command once is that changing the config value will be confusing and not lead to what was expected.

**Comment by Moritur** [comment]
If I remember correctly restarting server is not necessary, but client won't see changes unless they leave server and join again

**Comment by TwixterZ** [comment]
Tested this issue on 0.9.5 Develop-305, using command /meteor addhours now reflected in server UI immediately without restart, but client restart is still required.

**Comment by TwixterZ** [comment]
Closing this issue as fixed, new issue created for timer to update client side in game under [#22309](https://github.com/StrangeLoopGames/EcoIssues/issues/22309)
