### ISSUE TITLE
USER ISSUE: failure to authenticate

### ISSUE THREAD

**Issue by aldruith** [StrangeLoopGames/EcoIssues#14562]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
launch game from steam. click continue at title screen. 

**Expected behavior:**
should have connected me to EcoStraz

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Failed to authenticate user ticket with Steam</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Failed to authenticate user ticket with Steam</size>
```

**Comment by MeirionHughes** [comment]
same, can't login with the standalone client either. 

Failed to login

Unknown Error

Curl error 51: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_NOT_TRUSTED

**Comment by D3nnis3n** [comment]
Steam had technical issues, so login wasn't possible.

**Comment by redwyre** [comment]
@MeirionHughes your issue is different, please follow https://github.com/StrangeLoopGames/EcoIssues/issues/14579
