### ISSUE TITLE
Voice users are not showing up in my settings

### ISSUE THREAD

**Issue by airwolf39** [StrangeLoopGames/EcoIssues#14564]
Hi,

When i approach my friends they dont show up under 'voice users' in settings. No one can hear me in proximity voice. But i know my mic works because we are talking in discord and they can hear eachother in game. I have my mic set to 'open' mic. I have tried reinstalling the game, using push to talk, turn mic on/off, etc. no luck. Thanks.

Brian
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4135292/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4135293/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4135294/Player.log)

**Comment by redwyre** [comment]
this was caused by the certificate issue (it needs to access the auth server)
