### ISSUE TITLE
Eco 0.8.3.2, crash immediately after launch

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14561]
win 10 x 64
cpu amd A10
video amd radeon HD 7600M + 7660G

![0Qauv0UoeLo](https://user-images.githubusercontent.com/4980243/73451782-74543180-4379-11ea-9359-4db11d8c7825.jpg)

initialization not finished as i see (look at registry)

![HkGTRzbznHc](https://user-images.githubusercontent.com/4980243/73451811-846c1100-4379-11ea-95c5-be1edc103e4a.jpg)

log&dmp
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4134046/Player.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4134047/error.log)
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4134048/crash.zip)

changing\adding fullscreen keys is not helped.

Same issue at 0.9 version.

**Comment by mirasrael** [comment]
Problems with AMD GPU driver:
```
aticfx64.dll caused an Access Violation (0xc0000005)
  in module aticfx64.dll at 0033:8e9b898e.
```

**Comment by redwyre** [comment]
@elfl0rd What driver are you currently using? Try checking for a updated driver: https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers

**Comment by elfl0rd** [comment]
last available for this card, https://www.amd.com/en/support/apu/amd-series-processors/amd-a10-series-apu-for-laptops/a10-4600m-radeon-hd-7660g

Release Date
7/29/2015

Release Date
3/1/2016

![rn-Nth3bevg](https://user-images.githubusercontent.com/4980243/73467244-1e40b780-4394-11ea-9f3e-9f874f976c55.jpg)
![3J_assSoeFI](https://user-images.githubusercontent.com/4980243/73467245-1ed94e00-4394-11ea-9990-9d99a363fb38.jpg)
![YovXz610I60](https://user-images.githubusercontent.com/4980243/73467246-1ed94e00-4394-11ea-9010-6106ba91bbd0.jpg)
![Uploading W7IE9-Gz5Uw.jpg…]()

**Comment by D3nnis3n** [comment]
I had a similar case where no newer drivers were available, we were unable to get it to run on that laptop. On his desktop it was fine. Hopefully there is some way to make it run nontheless.

**Comment by elfl0rd** [comment]
Same there, it looks as this laptop totally unsupport new unity.

**Comment by mirasrael** [comment]
Unity report created. Not much we can do on our side unfortunately, because it crashes even with simplest Unity application.

https://fogbugz.unity3d.com/default.asp?1217204_hcj7e9851vm637jn

**Comment by elfl0rd** [comment]
https://www.techpowerup.com/gpu-specs/radeon-hd-7660g-igp.c688

> DirectX    11.2 (11_0)
> OpenGL    4.4
> OpenCL    1.2
> Vulkan    N/A
> Shader Model    5.0

**Comment by mirasrael** [comment]
@elfl0rd 
Answer from Unity:
```
Hi,

Thank you for reaching out to us.

Did the issue start after upgrading drivers by any chance? Could the user try downgrading them just in case the issue is caused by drivers?

Currently, we're getting a lot of similar issues and according to the stacktrace it's likely to be caused by faulty drivers from AMD's side. If it turns out that older drivers work just fine, could you please report this issue to AMD so they'd know it's there?

You could also try reinstalling DirectX or GPU drivers. If after trying these suggestions the issue still reproduces, please respond to this message with additional information and I will continue the investigation.

Cheers,
Edvardas
Customer QA Team
```

**Comment by elfl0rd** [comment]
No, only one video driver available for this system.
Reinstalling drivers\directx not helped.

Another Unity game (Beholder) work fine.

Found solution, swithing from "max performance" to "energy saving" in catalyst profiles helped.

**Comment by IcedForge** [comment]
Will close as resolved per user description solving the issue.
