### ISSUE TITLE
Username: Disallow players that have only a space as name.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14560]
You can imagine how the chat looks, i assume ...

![lol](https://user-images.githubusercontent.com/25908592/73444642-4ced6c80-4359-11ea-9d4a-dafc16d3fdb5.png)

**Comment by elfl0rd** [comment]
need better names detection, lol

**Comment by SlayksWood** [comment]
> A user just joined our server with their steam name set to nothing ("") or maybe some odd unicode character. Seems to be someone trolling the server.
> What happens now, is that every chat message anyone sends has this person referenced in it any time they use punctuation. There also seems to be no way to remove a player from a server, so for the rest of the game we are going to have to live with this issue.
> 
> Can you add some checks to names in 9.0, or at least for when they are inserted into the chat so it isn't pickup up empty names. And maybe a command to rename users would be helpful as well.
