### ISSUE TITLE
USER ISSUE: cant join to game

### ISSUE THREAD

**Issue by lifetimenq** [StrangeLoopGames/EcoIssues#14566]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
press "Continue"		

**Expected behavior:**
join to game

**Actual behavior:**
The following error message popped up:
<size=150%>Connection Failed</size>

Неверная информация авторизации.

<size=60,00%>Failed to authenticate user ticket with Steam</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
<size=150%>Connection Failed</size>

Неверная информация авторизации.

<size=60,00%>Failed to authenticate user ticket with Steam</size>
```

**Comment by D3nnis3n** [comment]
Steam had technical issues, so login wasn't possible.
