### ISSUE TITLE
[0.9.0 staging-1378] Can place waterwheel in other blocks.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14577]
can reproduce in 0.8.3.2 too:
![image](https://user-images.githubusercontent.com/45708377/73524445-2e04de00-441e-11ea-8885-9ce32352e8e2.png)
#2105

**Comment by keegan-o** [comment]
https://github.com/StrangeLoopGames/Eco/pull/5521

**Comment by SlayksWood** [comment]
I can't place waterwheel in water after changes:
![image](https://user-images.githubusercontent.com/45708377/73628314-f89c0280-4660-11ea-9948-42f4a84188ba.png)

**Comment by keegan-o** [comment]
fixed by https://github.com/StrangeLoopGames/Eco/pull/5639
