### ISSUE TITLE
Certificate issues with auth.strangeloopgames.com

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14579]
Failed to login

Unknown Error

Curl error 51: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_NOT_TRUSTED

_Originally posted by @MeirionHughes in https://github.com/StrangeLoopGames/EcoIssues/issues/14562#issuecomment-580357042_

**Comment by redwyre** [comment]
From my tests the certificate looks fine, but there may be some regional issues or issues with operating systems not having the full certificate chain.

**Comment by D3nnis3n** [comment]
Oops, overlooked that. But yah, that is something that'll fix itself or can be fixed by deleting the old certificate from the certificate store.

**Comment by redwyre** [comment]
Solution:
1. Press windows key, type "certificates" and click on "Manage user certificates"
2. Select "Intermediate Certificate Authorities" then "Certificates"
![image](https://user-images.githubusercontent.com/431728/73595264-54339680-4562-11ea-88a7-6f796556067e.png)
3. Find "Let's Encrypt Authority X1", right click on it, and select delete
4. Restart your computer

**Comment by redwyre** [comment]
@MeirionHughes give that a go if you're still having the problem.

**Comment by D3nnis3n** [comment]
Not a "bug" that we can fix, though, as of mirasrael.
You could make a wiki entry for that fix, but otherwise i'll close this.
