### ISSUE TITLE
Incorrect tooltip (plant seeds onto existing plant)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14574]
(if you looking to plant and have selected seeds)
![20200131104233_1](https://user-images.githubusercontent.com/4980243/73521197-715b4e80-4416-11ea-8ebd-3c63abcebf5b.jpg)

**Comment by SlayksWood** [comment]
It seems to me that such issue was, but I can't find it.

**Comment by SlayksWood** [comment]
#14493, #13968, #13291
