### ISSUE TITLE
Localization work 31.01.2020

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14573]
- [x] Sleep

(exists, not used) - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#152766

![изображение](https://user-images.githubusercontent.com/4980243/73518393-39044200-440f-11ea-90a9-488915ebb247.png)

- [x] Citizens

(exists, not used) - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#165636

![изображение](https://user-images.githubusercontent.com/4980243/73518510-926c7100-440f-11ea-8f2c-30159cb5147a.png)

- [x] bug? - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#169296

- [x] "Camera mode" - maybe something like "map mode" or "map view" or "map camera" is better? - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#169336

- [x] Currency Report

(exists, not used) - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#148030

![изображение](https://user-images.githubusercontent.com/4980243/73519262-95686100-4411-11ea-9b81-14109818fd61.png)

- [x] Specialized

(not exists)
![изображение](https://user-images.githubusercontent.com/4980243/73519752-ecbb0100-4412-11ea-8c1a-e215312430cd.png)

- [x] Learned

(not exists)
![изображение](https://user-images.githubusercontent.com/4980243/73519794-0c522980-4413-11ea-900b-27757aec1208.png)

**Comment by elfl0rd** [comment]
seconds\minutes\hours looks not used too
![изображение](https://user-images.githubusercontent.com/4980243/73520064-c0ec4b00-4413-11ea-9f24-edea1271087e.png)

**Comment by elfl0rd** [comment]
No space for a long texts.
Need more space at button
need more space at checkbox
![изображение](https://user-images.githubusercontent.com/4980243/73520357-80d99800-4414-11ea-9025-164f3c9c3245.png)

**Comment by SlayksWood** [comment]
Last comment added to #14175

**Comment by elfl0rd** [comment]
"Music Volume" duplicated
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#170761
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#163284

**Comment by elfl0rd** [comment]
vehicle boom, vehicle swing and skid steer strings exists but missing.
![изображение](https://user-images.githubusercontent.com/4980243/73522221-e596f180-4418-11ea-994d-3d8bf7149503.png)

**Comment by elfl0rd** [comment]
"Center:" string exists but not used.
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#152324
![изображение](https://user-images.githubusercontent.com/4980243/73522888-a073bf00-441a-11ea-8670-43514f6a5126.png)
