### ISSUE TITLE
[0.9.0 staging-1378] Hard to see recipes at Advanced Carpentry table

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14576]
Step to reproduce:
- place Advanced Carpentry table:
- open it. I have 1 recipe:
![image](https://user-images.githubusercontent.com/45708377/73523147-41fb1080-441b-11ea-9295-388e853e349a.png)
- close and reopen:
![image](https://user-images.githubusercontent.com/45708377/73523162-48898800-441b-11ea-8fb7-313c9ca64c29.png)
- again and again and again:
![image](https://user-images.githubusercontent.com/45708377/73523171-4d4e3c00-441b-11ea-8a50-f28e5225adfb.png)
![image](https://user-images.githubusercontent.com/45708377/73523176-52ab8680-441b-11ea-9e94-7b10982424b6.png)
![image](https://user-images.githubusercontent.com/45708377/73523185-550de080-441b-11ea-896f-2236f2a340df.png)

**Comment by mirasrael** [comment]
Fixed to not fail, but it fails because missing Link component. Already asked Balance team to fix.
