### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by fox1418** [StrangeLoopGames/EcoIssues#14586]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Échec de la connexion - Délais dépassé (timed out).
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Échec de la connexion - Délais dépassé (timed out).
```

**Comment by Deantwo** [comment]
Why does the game client even suggest making a bug report for a simple "Connection Failed" error?
Some of the basic connection errors should be excluded from the general error popup and get some more fitting error messages for the user.

**Comment by D3nnis3n** [comment]
Please contact our support at support@strangeloopgames.com if this issue is persisting.
