### ISSUE TITLE
 [Staging 1378] Planting an Acorn gives a gap on Baby Oak Tree

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14582]
**Version:** 0.9.0.0 beta staging-1378

Newly created 1378 Single-player world (default with friends and meteor off)

Tested Planted The Following Seeds to make sure it was only Oak Tree doing this
Birch Seed
Cedar Seed
Ceiba Seed
Fir Seed
Joshua Seed
Acorn
Palm Seed
Redwood Seed
Saguaro Seed
Spruce Seed

Labelled screenshot for my benefit for each tree 
![snap6114edited](https://user-images.githubusercontent.com/29383891/73575004-1275f380-446f-11ea-9aeb-6e91d4261aa5.png)

also after this test All but 3 Trees Disappeared  (Birch, Joshua and Saguaro) which is fine as i am in the area where they grow 
![snap6117](https://user-images.githubusercontent.com/29383891/73575191-8f08d200-446f-11ea-8ddb-94e9395de20a.png)

**BUT**

A wild Spruce and Oak Spawned here (i think after world tick and the original tress disappeared)
![snap6121edited](https://user-images.githubusercontent.com/29383891/73576301-0a6b8300-4472-11ea-9269-660f378e9e01.png)

![snap6119](https://user-images.githubusercontent.com/29383891/73576393-3dae1200-4472-11ea-8234-c37c51308b98.png)
![snap6123](https://user-images.githubusercontent.com/29383891/73576410-49013d80-4472-11ea-93f7-e8219adb7ef6.png)

managed to get a Soil Sampler Reading of the Two Spruce but could not get anywhere near the bottom of the Wild Oak tree with Soil Sampler to get a reading, then accidentally hit it with a Devtool trying to remove some dirt.

**Comment by SlayksWood** [comment]
gap merged to #14046
Regarding teleported trees: They died, but because you planted seed, they are trying to grow again but in another place. And it happens in one tick. We have issue #12825. I added you information to it.
