### ISSUE TITLE
 [Staging 1378] Intended Change when Learning Mining, Logging, Hunting and Gathering Skills?

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14580]
**Version:** 0.9.0.0 beta staging-1378

I see that when these skills are learned now they do not give the Following FREE items:

Mining = Iron Pickaxe
Logging = Iron Axe
Hunting = Wooden Bow and 100 Arrows
Gathering = Iron Scythe

is this **new** 0.9 Intentional Behavior or a Bug?

**Comment by D3nnis3n** [comment]
Intentional.

**Comment by Conchipedia** [comment]
i had a feeling it was going to be the NEW system, just wanted to make sure it was intentional,
