### ISSUE TITLE
Icons for Upgrade Modules

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14584]
These are items (no meshes related to them at least not for 9.0) that get plugged into crafting world objects to increase their effectiveness by decreasing the cost and crafting time of crafting things on that world object.

There are three sets of them, each with 4 tiers of power. Each of the three sets will apply to a different set of crafting tables. The tier power is a simple increase in efficiency corresponding to the number tier, so a 'Basic Upgrade Module 1' will decrease cost and time to craft by 10%, and a 'Basic Upgrade Module 2' will be 20%, etc.

Each of these modules will be created by a different profession, but not locked to that type of profession's tables-- this represents cross-pollination of improving technology, where a stone part might be of use for a farmer, or a wooden machine part might be more useful for a smith). Thus, ideally the icons are created to show machine parts of different materials highlighted, based on the professions that make them, which is shown here.

Here is the list of these base 12 modules:

- [x] Basic Upgrade Module 1 - Masonry 2 (a stone machine part)
- [x] Basic Upgrade Module 2 - Carpentry 4 (a wooden machine part)
- [x] Basic Upgrade Module 3 - Basic Engineer 5 (a more complex set of machine parts)
- [x] Basic Upgrade Module 4 - Carpentry 6 (a more impressive wooden machine part)
__
- [x] Advanced Upgrade Module 1 - Smelting 2 (an iron or steel machine part)
- [x] Advanced Upgrade Module 2 - Glass Working 4 (A machine part with glass gauge or something)
- [x] Advanced Upgrade Module 3 - Pottery 5 (a ceramic machine part)
- [x] Advanced Upgrade Module 4 - Mechanics 6 (a more complex set of machine parts)
__
- [x] Modern Upgrade Module 1 - Advanced Smelting 2 (a metal modern machine part)
- [x] Modern Upgrade Module 2 - Composites 4 (a wooden modern machine part)
- [x] Modern Upgrade Module 3 - Industry 5 (a set of modern machine parts)
- [x] Modern Upgrade Module 4 - Electric 6 (an electronic machine part)

_____________________

We also need one icon to be used in the world object component list UI that symbolizes all upgrade modules.

- [ ] Upgrade Module Component UI Icon

**Comment by Sekor2600** [comment]
BasicUpgrade1
BasicUpgrade2
BasicUpgrade3
BasicUpgrade4
AdvancedCarpentryUpgrade
CarpentryUpgrade
AdvancedUpgrade1
AdvancedUpgrade2
AdvancedUpgrade3
AdvancedUpgrade4
ModernUpgrade1
ModernUpgrade2
ModernUpgrade3
ModernUpgrade4
LoggingUpgrade
ModernMasonryUpgrade
MasonryUpgrade
AdvancedMasonryUpgrade
GlassworkingUpgrade
PotteryUpgrade
MiningUpgrade
CompositesUpgrade
SmeltingUpgrade
AdvancedSmeltingUpgrade
AdvancedBakingUpgrade
BakingUpgrade
AdvancedCookingUpgrade
CookingUpgrade
CampfireCookingUpgrade
OilDrillingUpgrade
TailoringUpgrade
ButcheryUpgrade
FarmingUpgrade
MillingUpgrade
FertilizersUpgrade
CuttingEdgeCookingUpgrade
BasicEngineeringUpgrade
MechanicsUpgrade
IndustryUpgrade
ElectronicsUpgrade
PaperMillingUpgrade

Here complete List @keegan-o

**Comment by mirasrael** [comment]
As releasing going close it raises in priority. Because we need these icons for release.

**Comment by keegan-o** [comment]
Alrighty, the updated plan for Specialty Upgrade Modules:

New Icon needs:

- [ ] Specialty Upgrade Module Basic
- [ ] Specialty Upgrade Module Improved
- [ ] Specialty Upgrade Module Modern

These three are the actual machine part icons like the previous ones done for upgrade modules which sit inside the frame (thus these icons should be sized to sit inside the frame like them, not take up the whole 64x64 space). For these, make the 'basic' one a nice looking metal part-- the 'improved' part should be a nice looking advanced machine part, perhaps with more components to it. The 'modern' part should have some kind of electronic component to it probably; it is the most advanced upgrade module in the game.

**Specialty Indicator Bars Icons**:

These icons are going to be little bars that replace the tier bars or dots or whatever you want to call them:

![image](https://user-images.githubusercontent.com/14983165/81368751-71b65600-90a5-11ea-8bdd-6839135a6673.png)

These bars will go in that location, on top of the bottom part of the icon frame for upgrade modules.
This is going to be a bit tough/possibly a bit weird, but what we need is little bar icons that fit in this space, 64x15 pixels, that indicate each of the specialties in the game. 

Handily, we just finished making icons for each specialty, so the obvious thing to do is to take each of those and figure out how to get the most recongnizable part of it into a 64x15 pixel space. Here is the list; it is a list of all the specialties in Eco:

- [ ] Logging Specialty Indicator 64x15px bar
- [ ] Carpentry Specialty Indicator 64x15px bar
- [ ] Composites Specialty Indicator 64x15px bar
- [ ] Paper Milling Specialty Indicator 64x15px bar
- [ ] Campfire Cooking Specialty Indicator 64x15px bar
- [ ] Cooking Specialty Indicator 64x15px bar
- [ ] Baking Specialty Indicator 64x15px bar
- [ ] Advanced Cooking Specialty Indicator 64x15px bar
- [ ] Advanced Baking Specialty Indicator 64x15px bar
- [ ] Basic Engineering Specialty Indicator 64x15px bar
- [ ] Mechanics Specialty Indicator 64x15px bar
- [ ] Industry Specialty Indicator 64x15px bar
- [ ] Oil Drilling Specialty Indicator 64x15px bar
- [ ] Electronics Specialty Indicator 64x15px bar
- [ ] Farming Specialty Indicator 64x15px bar
- [ ] Fertilizers Specialty Indicator 64x15px bar
- [ ] Gathering Specialty Indicator 64x15px bar
- [ ] Milling Specialty Indicator 64x15px bar
- [ ] Butchery Specialty Indicator 64x15px bar
- [ ] Hunting Specialty Indicator 64x15px bar
- [ ] Mining Specialty Indicator 64x15px bar
- [ ] Masonry Specialty Indicator 64x15px bar
- [ ] Pottery Specialty Indicator 64x15px bar
- [ ] Glassworking Specialty Indicator 64x15px bar
- [ ] Advanced Masonry Specialty Indicator 64x15px bar
- [ ] Smelting Specialty Indicator 64x15px bar
- [ ] Advanced Smelting Specialty Indicator 64x15px bar
- [ ] Self Improvement Specialty Indicator 64x15px bar
- [ ] Tailoring Specialty Indicator 64x15px bar

**Comment by WeaselDog** [comment]
List of specialty upgrade. All upgrades start with their specialty name, not the module tier (FYI for advanced upgrades).

- [ ] Advanced Baking Upgrade 
- [ ] Advanced Cooking Upgrade
- [ ] Advanced Masonry Upgrade
- [ ] Advanced Smelting Upgrade
- [ ] Baking Upgrade
- [ ] Basic Engineering Upgrade
- [ ] Butchery Upgrade
- [ ] Campfire Cooking Upgrade
- [ ] Carpentry Upgrade (Basic)
- [ ] Carpentry Upgrade (Advanced)
- [ ] Composites Upgrade
- [ ] Cooking Upgrade
- [ ] Cutting Edge Cooking Upgrade
- [ ] Electronics Upgrade
- [ ] Farming Upgrade
- [ ] Fertilizers Upgrade
- [ ] Glassworking Upgrade (Advanced)
- [ ] Glassworking Upgrade (Modern)
- [ ] Industry Upgrade
- [ ] Logging Upgrade (Advanced)
- [ ] Logging Upgrade (Basic)
- [ ] Masonry Upgrade (Basic)
- [ ] Masonry Upgrade (Modern) [ For Cement]
- [ ] Mechanics Upgrade (Advanced)
- [ ] Mechanics Upgrade (Modern)
- [ ] Milling Upgrade
- [ ] Mining Upgrade (Basic)
- [ ] Mining Upgrade (Advanced)
- [ ] Mining Upgrade (Modern)
- [ ] Oil Drilling Upgrade
- [ ] Paper Milling Upgrade
- [ ] Pottery Upgrade
- [ ] Smelting Upgrade
- [ ] Tailoring Upgrade

**Comment by RobertMangano** [comment]
added these icons to UI_icons_04, in the same order as Tods most recent list
