### ISSUE TITLE
[Staging 1378] +[Staging 1392]  [Artwork] Something Weird happened to dirt and sand placement 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14585]
**Version:** 0.9.0.0 beta staging-1378

![snap6137](https://user-images.githubusercontent.com/29383891/73585565-3d297180-449a-11ea-81dd-229707390286.png)
![snap6138](https://user-images.githubusercontent.com/29383891/73585566-3d297180-449a-11ea-9221-98d7a39aae27.png)
![snap6139](https://user-images.githubusercontent.com/29383891/73585567-3d297180-449a-11ea-96b3-86510543b36f.png)

Just was covering my stairs to a mine and using up dirt instead of other blocks

**Comment by Conchipedia** [comment]
same also for sand, just started digging out some and it looks horrible with how its left
![snap6241](https://user-images.githubusercontent.com/29383891/74272749-14f60a00-4d07-11ea-8f31-696f283f5c3b.png)
![snap6242](https://user-images.githubusercontent.com/29383891/74272755-19222780-4d07-11ea-92b2-f550a2c5567d.png)

**Comment by Conchipedia** [comment]
the dirt looks like this as well when stacked in a stockpile

**Comment by keegan-o** [comment]
The worse one of these two cases is fixed, investigating the other....

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/79bd575d-b87e-4221-9cb8-1e5f999337f2)
Fixed in staging! Had to add a new piece to the builder that transitions between a cube on the bottom and corner on the top.
