### ISSUE TITLE
USER ISSUE: Failed to authenticate user ticket with Steam

### ISSUE THREAD

**Issue by dav793** [StrangeLoopGames/EcoIssues#14587]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Try to join previously working server

**Expected behavior:**
It should log in

**Actual behavior:**
Shows error message: Failed to authenticate user ticket with Steam

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by D3nnis3n** [comment]
Steam was down.
