### ISSUE TITLE
 [Staging 1380] Researching flaws

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14588]
- [x] Impossible to create Farming Skill Book because it needs Farming skill to create Agricultural Research Paper Advance

**Version:** 0.9.0.0 beta staging-1380

I am a Mason so wanted to just unblock masonry stuff

Found out this problem as my next skill book i wanted to make was Bricklaying or Glassworking which needs for some unknown reason **Agriculture Research Paper Advance** 
what has farming to do with Brick or glass? (but i understand that you need more players to work together to supply each other)

![snap6147](https://user-images.githubusercontent.com/29383891/73598902-82e74800-4535-11ea-9b94-606a27a8351c.png)
![snap6149](https://user-images.githubusercontent.com/29383891/73598904-8da1dd00-4535-11ea-86c6-bfda08a42a3f.png)

now to create this **Agriculture Research Paper Advance**
![snap6150](https://user-images.githubusercontent.com/29383891/73598861-300d9080-4535-11ea-8151-8d88a32b6819.png)
Which as you can see is Crafted at a **Farmers Table**
![snap6146](https://user-images.githubusercontent.com/29383891/73599024-f63d8980-4536-11ea-841a-3afbe6637109.png)
now to craft a **Farmers Table** at a workbench i Need Farming Skill
![snap6145](https://user-images.githubusercontent.com/29383891/73599056-2553fb00-4537-11ea-85c8-bac3fe297306.png)

**BUT** to get Farming Skill i need to craft a Farming Skill Book 
![snap6148](https://user-images.githubusercontent.com/29383891/73599066-3c92e880-4537-11ea-8458-9ebf4132b5fc.png)
and That  Needs **Agriculture Research Paper Advance**
which Needs Farming Skill to craft

**Comment by beastyn** [comment]
Still need farming skill for farming skill book (in AgricultureResearchPaperAdvanced)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/74214712-902bd180-4caf-11ea-841d-9b5e473855f9.png)

**Comment by SlayksWood** [comment]
it will change after updates to all researching recipes.
https://github.com/StrangeLoopGames/Eco/issues/5550
