### ISSUE TITLE
USER ISSUE: Plants do not break on emptying dirt stockpiles

### ISSUE THREAD

**Issue by Pasimega** [StrangeLoopGames/EcoIssues#14590]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. fill a stockpile with dirt
2. let wildlife grow on it
3. take the dirt out of the stockpile

**Expected behavior:**
Break the plants growing on the dirt upon removing it

**Actual behavior:**
Plants stay floating in the air not recognizing the dirt being removed

**Do you have mods installed? Does issue happen when no mods are installed?:**
Plants stay floating in the air not recognizing the dirt being removed

**Comment by SlayksWood** [comment]
dup #6902
