### ISSUE TITLE
[0.9.0 staging-1382] Markers overlap with 'Specialization to show' UI and under it.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14595]
Step to reproduce:
- add many markers and hide skill ui:
![image](https://user-images.githubusercontent.com/45708377/73636039-e4aecb80-4675-11ea-95b0-b5771ce90e40.png)
- open 'Specialization to show' UI. All markers in left side overlap:
![image](https://user-images.githubusercontent.com/45708377/73636075-0314c700-4676-11ea-82a4-62ed07bf58de.png)
- select Show always and take many specialties:
![image](https://user-images.githubusercontent.com/45708377/73636187-6141aa00-4676-11ea-939e-c8a9dce29732.png)
- it also can be under it(easy to repro with 2-3 specialties):
![image](https://user-images.githubusercontent.com/45708377/73636321-a6fe7280-4676-11ea-8fc8-eb9f52b664b2.png)

**Comment by johnkslg** [comment]
Moving to oleg as he's been working on this

**Comment by gzatravkin** [comment]
This was already fixed here https://github.com/StrangeLoopGames/Eco/pull/6133

And improoved perfomance here 
https://github.com/StrangeLoopGames/Eco/pull/6154
