### ISSUE TITLE
World layers does not handle worlds of some sizes

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1459]
Here is a crash report from a 141X141 world that would make it through to 'finishing' and then crash - it is a default build with just the world size changed.  WE tried many times to get the world to generate - deleting the one that was crashing and regenerating but it would not work:  https://www.dropbox.com/s/h7hx1vx6fewfx0k/Crash%2005111044.ecodmp?dl=0  I am sorry I don't have a copy of that world.  But here is another example of a default files with only the world size changed to 125X125  both the world as far as it generated and the crash logs are in this zip:  https://www.dropbox.com/s/fqff271r5i1n1eq/Toxic%20World.zip?dl=0  these were both on 5.5.4 on a server with 6GB RAM - RAM never exceeded 2GB during the generation process and both seemed to make it as far as "finishing" before the game crashed and started building terrain again.  Just so you know I worked on both these instances for many hours yesterday and nothing would build these worlds except going back to 100X100 sized worlds built just fine.  Its very odd.  If there is anything you would like me to try please let me know

**Comment by Magnusvik** [comment]
Tried to generate a 141x141 world aswell wich failed. I tried to change cpu priority to Realtime but that did not help either
Here you have game.eco and crash log
https://drive.google.com/file/d/0B6Pv5T5Ha34hZHBlcWFScVUxQXc/view?usp=sharing

**Comment by Ravnster** [comment]
Had no issues generating world size 140x140 and 142x142

**Comment by pamduncan** [comment]
I actually think you may have discovered whats happening.  I was able to create a 140X140 world without any issues this morning on the server where 141X141 crashed every time we tried.  Apparently odd numbers don't work although those were the numbers given to us for world sizes so i guess we should change that to 2x 140X140  3X 174X174 and 4X 200X200 ?   Maybe the devs can tell us if the world will not build with odd numbers at all?

**Comment by Ravnster** [comment]
Generating world size
101x101 CRASH
102x102 OK
103x103 CRASH
104x104 OK

Odd numbers will crash world generation on the last part were its "finishing"

**Comment by pamduncan** [comment]
Yes.  I have built a  120X120, 140X140, 174X174 and 200X200 that were all successful.  125X125, 141X141, 173X173, and 201X201 all failed during "finishing.

have a very nice 140X140 world up now called Killservers Private Test Server if anyone wants to check it out.  It did take 45 minutes (2731205ms) to complete - the freezing part took the longest

Unless there is a reason to make the world build in odd sizes, perhaps just having the configuration force even number worlds would be a good solution.

**Comment by noblackthunder** [comment]
so anything that cant be divided by 2 with whole numbers will crash the server. Good to know ;)

**Comment by pamduncan** [comment]
Sould we just make it an instruction that world size should be even numbers or is this something that is going to get addressed as a bug so any sized world can be built?

**Comment by metachronism** [comment]
World layers creates layers of incorrect size.  

For example, making a world of 175x175 chunks, the resulting size is 1750x1750 voxels.
The player activity layer uses a voxels per entry of 4, 1750/4 => 437

but accessing at x = 1748, a valid position, gives you an x-index into the layer of 438, which is outside the array

**Comment by knexer** [comment]
Resolving this in favor of https://github.com/StrangeLoopGames/EcoIssues/issues/2510.  We're going to disallow the creation of worlds that aren't an integer multiple of world layer patch sizes, and at the same time regulate the allowed set of world layer patch sizes so that that's a reasonable thing to do.
