### ISSUE TITLE
minimap objects frequently intersect and are hard to read

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#146]
![image](https://cloud.githubusercontent.com/assets/3150561/15758895/677fac7c-28c1-11e6-9292-2001d139b070.png)

**Comment by stett** [comment]
@johnkslg This isn't as much of a problem anymore without structure names showing up on the map. Do you think we still need to do anything further about this issue? It does get crowded still if a bunch of people are close to each other.
