### ISSUE TITLE
[0.9.0 staging-1383] "Allow Laws to Prevent Login or Play = False" doesn't work for First login.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14608]
Step to reproduce:
- set 'Allow Laws to Prevent Login or Play' = False:
![image](https://user-images.githubusercontent.com/45708377/73741395-341af780-475b-11ea-8dcc-417baaf0b01e.png)
- create law for Play prevent:
![image](https://user-images.githubusercontent.com/45708377/73741418-4301aa00-475b-11ea-855e-6c20d5244dfb.png)
- create law for First Login prevent:
![image](https://user-images.githubusercontent.com/45708377/73741447-5280f300-475b-11ea-996c-a1fcd2b749e7.png)
- I can play and have notification that this law doesn't work:
![image](https://user-images.githubusercontent.com/45708377/73741487-62003c00-475b-11ea-8720-dd71e824490c.png)
- but it's many spam in chat. May be add this information to law tooltip with red color?
![image](https://user-images.githubusercontent.com/45708377/73741595-9aa01580-475b-11ea-9db6-8562cc6652e6.png)
- another player can't connect First time. So this doesn't work for login.
![bandicam_2020-02-04_16-30-18-973](https://user-images.githubusercontent.com/45708377/73741721-db982a00-475b-11ea-9f72-fefcf0c77813.jpg)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/74068548-c2d48200-49b0-11ea-978d-97d339eb496e.png)
Now these events are invalid if the setting is set.

However, if you change the setting after the law already exists, youll get the spam, which I think is ok, the admin can force remove the law.

**Comment by SlayksWood** [comment]
It's good notification for Play. But it still doesn't work for first login:
![image](https://user-images.githubusercontent.com/45708377/74141289-b1d17e00-4c07-11ea-9a0f-17d2529916bd.png)

**Comment by johnkslg** [comment]
Not sure what the issue is, can you explain more? It looks like its working in your screen shot.

**Comment by SlayksWood** [comment]
Step to reproduce:
- Create new world.
- open server UI. Set "Allow Laws to Prevent Login or Play = False":
![image](https://user-images.githubusercontent.com/45708377/76056792-8cc2f780-5f88-11ea-98f3-595c2e368037.png)

- This should allow me to join to server even if there are laws prevent it.
- join from first account to server. place capitol and court. Create law like First login prevent:
![image](https://user-images.githubusercontent.com/45708377/76056564-04445700-5f88-11ea-9f31-afced1c43d7b.png)
- Use second account to first login to server. I can’t join to the server by law:
![image](https://user-images.githubusercontent.com/45708377/76056724-69984800-5f88-11ea-91d0-643739ae17e8.png)
- But this law shouldn't work! I should join to the server because "Allow Laws to Prevent Login or Play = False" is set in the server settings.

**Comment by johnkslg** [comment]
This is working in staging: 
![image](https://user-images.githubusercontent.com/3536496/76199235-79cf5200-622a-11ea-9850-66bc10cfdeb0.png)

If youre talking about the case where the server setting is changed *after* the law is created, that's expected behavior. They have to manually remove the law.

**Comment by beastyn** [comment]
Login should be with an error too, as the property says: prevent LOGING or PLAY
But you can make a law with Login

![bandicam 2020-03-10 17-07-10-805](https://user-images.githubusercontent.com/27898520/76311029-d8133800-62f1-11ea-8ca4-c229c0d4e335.jpg)

**Comment by johnkslg** [comment]
Ah now I get it. Fixed for FirstLogin.
