### ISSUE TITLE
[0.9.0 staging-1383] Removed player from Elected title with wages lose money.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14607]
Step to reproduce:
- Create any Elected title with Pages.
- I set 'Wage Frequency Minutes' to 3 min:
![image](https://user-images.githubusercontent.com/45708377/73740054-75f66e80-4758-11ea-84d5-405d2b9d39cd.png)
- I win election for this title and start to get wages.
- Start new election. Another player should win.
- When wages should pay only new elected player get money:
![unknown (4)](https://user-images.githubusercontent.com/45708377/73740195-c66dcc00-4758-11ea-824c-189b018dd69f.png)
I worked 2 min 21 sec and Beastyn worked 39 sec. But I didn't get money. It will be a shame if the payment is once a day.

**Comment by johnkslg** [comment]
Sounds like a workplace complaint, should file a claim with HR ;)

**Comment by johnkslg** [comment]
Wage dispute resolved.
![image](https://user-images.githubusercontent.com/3536496/74070944-472a0380-49b7-11ea-92ae-c74c6e8e38df.png)
