### ISSUE TITLE
[0.9.0 staging-1383] Can duplicate civics oblects.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14604]
Step to reproduce:
- place civics object (zoning office):
![image](https://user-images.githubusercontent.com/45708377/73720783-d8894380-4733-11ea-8ae9-1a16b0a25a20.png)
- try to pick up. You see confirm box, but you already have zoning office in your toolbar:
![image](https://user-images.githubusercontent.com/45708377/73720831-eccd4080-4733-11ea-8b2c-d91405e8e58c.png)
- press NO. You didn't pick up Zonning office but you have new at toolbar:
![image](https://user-images.githubusercontent.com/45708377/73720874-0a9aa580-4734-11ea-8fc9-23dae91f47d3.png)

**Comment by olegshegai** [comment]
Hm... strange... I used to fix that
