### ISSUE TITLE
[0.9.0 staging] Change header for Smog Output in Pipes Component

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14602]
The header for smog output currently says "ConvertorOut". It would be nice if this was changed to "Smog Output" or something similar. It also might be nice to change Water Input to Water Intake, but that is a matter of opinion.
![SmogOutput](https://user-images.githubusercontent.com/47330823/73701707-47688d00-469f-11ea-85d8-6988b523cc1c.png)

**Comment by SlayksWood** [comment]
dup #13761
