### ISSUE TITLE
[0.9.0 staging-1384] Powered cart collision

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14618]
![image](https://user-images.githubusercontent.com/45708377/73824942-1eb1d600-480c-11ea-99cf-be24edec6763.png)

**Comment by mirasrael** [comment]
What should we see on this screenshot? I don't understand.

**Comment by SlayksWood** [comment]
I am in powered cart
![image](https://user-images.githubusercontent.com/45708377/76753851-388ef300-6792-11ea-98e6-83d311c8bd7f.png)

**Comment by keegan-o** [comment]
fixed in staging
