### ISSUE TITLE
[0.9.0 staging] Text Component missing from Ecopedia

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14614]
The Text Component for things like signs and vehicles does not have a help page in Ecopedia.  If you click the help button on this tab it takes you to the front page of the Ecopedia.

![TextComponent](https://user-images.githubusercontent.com/47330823/73796794-13ef3680-4763-11ea-8110-94a09a6d5be8.png)

**Comment by johnkslg** [comment]
Can you add the necessary ecopedia files for these? Just need to add matching the name, "Text Component.xml".

**Comment by WeaselDog** [comment]
No problem. I add a component for "My Deeds" in Real Estate Desk and remove unnecessary components as well.
