### ISSUE TITLE
Проблема с соединением на серверах

### ISSUE THREAD

**Issue by Amirok228** [StrangeLoopGames/EcoIssues#14612]
Запускаю на сервер появляется красный значок снизу с право,минуты через 2-3 всё нормально,потом опять проблема с соединение и так каждый раз.Что делать?

**Comment by beastyn** [comment]
@Amirok228 спасибо за репорт.
Простите за долгий ответ. Если это ещё актуально, скажите пожалуйста, разрешилась ли проблема? Такое бывает в некоторых ситуациях  из-за интернет подключения и решается перезагрузкой роутера.

Также некоторым игрокам помогают вот такие шаги: 
Сохраните вашу папку Storage в /Steam/steamapps/common/Eco/Eco_Data/Server/ и удалите игру. После этого, пожалуйста, полностью удалите папку /Eco, по пути, указанному выше, и переустановите игру.

**Comment by beastyn** [comment]
Closed due no information. Please provide information if its still actual.
