### ISSUE TITLE
USER ISSUE: Can't stop sleeping

### ISSUE THREAD

**Issue by elnitsu** [StrangeLoopGames/EcoIssues#14611]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. Try to sleep pressing E in the bed inside the starting tent
(happens randomly)

**Expected behavior:**
Let me Wake up

**Actual behavior:**
2. For whatever reason it keeps jumping days and won't let me press Wake up. It's stuck in "real-time passed: 2 hours" but I can

**Do you have mods installed? Does issue happen when no mods are installed?:**
2. For whatever reason it keeps jumping days and won't let me press Wake up. It's stuck in "real-time passed: 2 hours" but I can

**Comment by beastyn** [comment]
Thank you for your report.
Did you press tab?
Did cursor appear?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
