### ISSUE TITLE
[0.9.0 staging-1383] Skills: recipes names on the benefits

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14610]
I  suppose we should have "Recipe" for all of the recipes everywhere on the tooltips.

![bandicam 2020-02-04 17-53-37-479](https://user-images.githubusercontent.com/27898520/73746721-a7cafd80-4777-11ea-83fa-a0bb1add3c99.jpg)

We have Char Animal Recipe but Topped Porridge.

Should be Topped Porridge Recipe. (for all recipes and all prefessions)

**Comment by mirasrael** [comment]
Just need to update TechTreeTemplates to use " Recipe" in display name.
