### ISSUE TITLE
[V8.3.2] Game crashing while using vehicles (intermittent)

### ISSUE THREAD

**Issue by TheVegMan** [StrangeLoopGames/EcoIssues#14619]
This only seems to affect me on our community server, this repeatedly happens everytime i'm on at somepoint. 

Video 1: https://streamable.com/bp14x
Video 2: https://streamable.com/av2ia

My specs:

Ryzen 7 3700x
X570 Aorus Pro
EVGA RTX 2070 super
Corsair Vengeance RGB Pro 32GB @ 3200Mhz (XMP)
Installed on: Crucial MX500 1TB SSD

![20200203215656_2](https://user-images.githubusercontent.com/60703448/73853620-17e58c00-4829-11ea-9bf9-822e09e73a90.jpg)

Please advise,

Cheers!

**Comment by TheVegMan** [comment]
I'll attach my log files after one of these crashes, to date this has happened at least 10 times. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4160221/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4160222/Player-prev.log)

**Comment by TheVegMan** [comment]
Just crashed while using a cart on the same road =/

I'll attach the dump file via wetransfer - https://we.tl/t-OyRJ0xD86W

**Comment by IcedForge** [comment]
This should be remedied in post 9.0 please reopen this issue if you have encountered it after.
