### ISSUE TITLE
USER ISSUE: Эмммм

### ISSUE THREAD

**Issue by NITDroid1995** [StrangeLoopGames/EcoIssues#14613]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Ломал дерево потом тыкнул по телеге правой кнопкой с пустой рукой

**Expected behavior:**
Ничего

**Actual behavior:**
Было получено следующее сообщение об ошибке:
Логин пользователя изменен
```
Токен входа изменён.

<size=60,00%>User is offline</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
Логин пользователя изменен
```
Токен входа изменён.

<size=60,00%>User is offline</size>
```

**Comment by beastyn** [comment]
Добрый день. Обычно такая ошибка возникает, если логин был использован на другом клиенте. 
Не запускался ли второй клиент?
Получается ли присоединиться после перезагрузки?
Вход был совершен через Steam или локально (из папки)?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
