### ISSUE TITLE
placeholder from big backpack

### ISSUE THREAD

**Issue by d4nlo3008** [StrangeLoopGames/EcoIssues#1461]
after buying the big backpack I received this white-placeholder (showing in the corner down right). 
no function. just blocks one space for the backpack. 
![screenshot_14](https://cloud.githubusercontent.com/assets/20752682/26024874/aa505c48-37db-11e7-87f8-c320c4db29da.jpg)

**Comment by keegan-o** [comment]
Could not reproduce, the big backpack works fine for me.
