### ISSUE TITLE
USER ISSUE: Cannot remap middle scroll wheel on mouse for build menu

### ISSUE THREAD

**Issue by hypothermiagames** [StrangeLoopGames/EcoIssues#14628]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Use trackball for accessibility reasons, and thus have no middle scroll wheel (repetitive strain injury)
Attempt to build anything other than default block
Rage in frustration that there is no option to remap this action

**Expected behavior:**
Ability to change the default shift + scroll to something else

**Actual behavior:**
No ability to change the default shift + scroll to something 

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by D3nnis3n** [comment]
In 9.0 you can choose the building block via mouse in a UI, so this is no longer applicable.
I'm sorry but we won't have a fix for the current version any more.
