### ISSUE TITLE
[0.9.0 staging-1386] Lost possibility in store to sort items.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14629]
![image](https://user-images.githubusercontent.com/45708377/73910954-cb01c400-48c1-11ea-8dbb-fe51e0ea5707.png)

**Comment by johnkslg** [comment]
They are now forced to be alphabetical by design

**Comment by SlayksWood** [comment]
It isn't correct! But what is about marketing?
I will have in top useless, for example, Ashlar..... bench, chair and etc. But to buy useful Steel Bar I need scrolling to the end?
I should have possibility to change positions.
Suppose I am a smelter. Here's an example of a list of my sales:
![image](https://user-images.githubusercontent.com/45708377/74148510-aa65a100-4c16-11ea-9cb1-2b0a116ad2f2.png)
But if I want to sell something else in this store (rarely) I will add it to end of my list.
For example they are brick and Coal:
![image](https://user-images.githubusercontent.com/45708377/74148599-e00a8a00-4c16-11ea-8cd5-924242136a02.png)
But now Brick and COal will be in top:
![image](https://user-images.githubusercontent.com/45708377/74148640-fc0e2b80-4c16-11ea-9e7e-da5124f6944c.png)
This is not very correct.

**Comment by johnkslg** [comment]
Allllright you convinced me
![image](https://user-images.githubusercontent.com/3536496/74382507-6a332980-4da2-11ea-94ef-73d38f170aa0.png)

When you add new ones, it keeps the old sorting and adds the new ones to the end.
