### ISSUE TITLE
[0.9.0 staging-1386] "Apocalyptic mode"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14631]
![image](https://user-images.githubusercontent.com/45708377/73912376-647ea500-48c5-11ea-95e9-6e1c980509df.png)
![image](https://user-images.githubusercontent.com/45708377/73912383-69dbef80-48c5-11ea-8385-379c1d44750d.png)
![image](https://user-images.githubusercontent.com/45708377/73912389-6fd1d080-48c5-11ea-9026-dc047c9aad1f.png)

**Comment by Conchipedia** [comment]
![snap6186](https://user-images.githubusercontent.com/29383891/73942518-1aa6b680-48e7-11ea-8372-4abcf6ee01b2.png)
![snap6187](https://user-images.githubusercontent.com/29383891/73942533-20040100-48e7-11ea-8baa-dea10a247aab.png)
![snap6188](https://user-images.githubusercontent.com/29383891/73942547-25f9e200-48e7-11ea-9695-f8f79e5ccffa.png)
![snap6189](https://user-images.githubusercontent.com/29383891/73942558-2befc300-48e7-11ea-87ce-91adfe4bae2f.png)
![snap6190](https://user-images.githubusercontent.com/29383891/73942574-31e5a400-48e7-11ea-871a-858b3514ab48.png)
![snap6191](https://user-images.githubusercontent.com/29383891/73942594-37db8500-48e7-11ea-889c-57e60773276a.png)
![snap6192](https://user-images.githubusercontent.com/29383891/73942604-3d38cf80-48e7-11ea-8f2e-8d81d0e2c79c.png)
![snap6193](https://user-images.githubusercontent.com/29383891/73942617-42961a00-48e7-11ea-9580-e5795ac96d0a.png)

Now i know why i say no to Drugs 😄

**Comment by mirasrael** [comment]
Link to Render Doc capture:
https://drive.google.com/file/d/1MjZe0BPEXjlZRIBOjiSSB3vwFkyWM0ur/view?usp=sharing
