### ISSUE TITLE
Upgrade template engine to avoid code duplication

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#14633]
Now we have lot of duplicate code for templates (especially for recipes). We need to find a solution how to avoid code duplication:

Possible solutions:
- Add support for partials (parameterized sub templates);
- Switch to third-party template engine with partial and many other features support (like Velocity).

**Comment by redwyre** [comment]
I would suggest t4 as a well supported template engine
Also, moving to  data driven items instead of class based, but that would be a huge amount of work...
