### ISSUE TITLE
Map editing cleanup

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14637]
Need help with a few issues after refactor of districts.
![image](https://user-images.githubusercontent.com/3536496/73976899-1de97480-48de-11ea-822f-0643631eebd7.png)
- [x] Make this text not overlap badly in property edit.

![image](https://user-images.githubusercontent.com/3536496/73981514-327e3a80-48e7-11ea-98b2-9586f69dbe7a.png)
- [x] Text at the bottom should show the district (as a LinkText displaying district.MarkedUpName) that is currently under focus, above the position text.   Also do this for property. 

- [ ] Type /civics spawngov true, then /civics spawnzoning office.  Open minimap and view some of the districts. Youll see that some of the maps didnt send their data through, see why that is.  

- [x] Click Add District.  Selection changes, but it shouldnt. And despite showing a new selection, you cant draw now.
![image](https://user-images.githubusercontent.com/3536496/73983354-154b6b00-48eb-11ea-8d46-63f66944d046.png)

- [x] Edit a color in a district map, press escape, notice the color window doesnt close but the district one does. The color one should cancel on escape.

**Comment by SlayksWood** [comment]
Need to aline UI
![image](https://user-images.githubusercontent.com/45708377/74014711-49349800-49a0-11ea-8315-290c2a6e53b5.png)

**Comment by beastyn** [comment]
Make a draft with some districts. Leave the lats district as the highlighted one.
![bandicam 2020-02-07 14-43-35-593](https://user-images.githubusercontent.com/27898520/74019101-dbe13100-49b8-11ea-953c-32e159ec8c0a.jpg)

Open draft for editing. The last district is highlighted but you are drawing with the color from the first one.
![bandicam 2020-02-07 14-43-58-038](https://user-images.githubusercontent.com/27898520/74019118-e6032f80-49b8-11ea-89db-bc44da4db904.jpg)

**Comment by beastyn** [comment]
@gzatravkin after the last changes ecoicon tag is here
![bandicam 2020-02-19 15-47-54-691](https://user-images.githubusercontent.com/27898520/74827659-949b5e80-532f-11ea-96e2-fe7abb793637.jpg)

**Comment by SlayksWood** [comment]
- [ ] 1. Overlap:
![image](https://user-images.githubusercontent.com/45708377/74919586-db469280-53db-11ea-8613-105958da4c3e.png)
- [ ] 2. Add the same left/right margin for the buttons, for example:
![image](https://user-images.githubusercontent.com/45708377/74920165-c3234300-53dc-11ea-9cb8-ce3808f01d14.png)
![image](https://user-images.githubusercontent.com/45708377/74920202-d59d7c80-53dc-11ea-8b24-a86f7e37b189.png)
![image](https://user-images.githubusercontent.com/45708377/74920237-e77f1f80-53dc-11ea-8df9-98c9b0f8b38d.png)
![image](https://user-images.githubusercontent.com/45708377/74920277-f796ff00-53dc-11ea-8b98-1dd5a873bbe0.png)

It should be all between two lines:
![image](https://user-images.githubusercontent.com/45708377/74920474-42187b80-53dd-11ea-9c24-f185c69155bc.png)

- [ ] 3. "Add new district" in bottom again:
![image](https://user-images.githubusercontent.com/45708377/74919850-48f2be80-53dc-11ea-8c36-1f8584f8d586.png)

**Comment by beastyn** [comment]
Also need to fix Input for long names in editing districts name (string is on color)
![bandicam 2020-02-20 14-27-01-956](https://user-images.githubusercontent.com/27898520/74929477-65ebb980-53fd-11ea-906f-caf19ad36043.jpg)

**Comment by gzatravkin** [comment]
I think that "Add new district" suits better in the bottom (like in right panel for markers, by example). It allows to don't scroll to add new district when there are a lot of districts. Also it allows add many districts in easy way with clicking in the same pos.

**Comment by SlayksWood** [comment]
@gzatravkin Okay
