### ISSUE TITLE
[0.9.0 staging-1386] Biomes and species: need balance

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14635]
In the 0.52 km world I have usually pretty small rainforest with pretty small ceiba counts
Like this one.
![bandicam 2020-02-06 12-18-30-034](https://user-images.githubusercontent.com/27898520/73925459-e8e61d80-48ef-11ea-9b11-dad18feb3060.jpg)

And its only 16 ceiba
![bandicam 2020-02-06 12-44-21-863](https://user-images.githubusercontent.com/27898520/73925500-f8656680-48ef-11ea-8ee7-09bbc5012c3c.jpg)
Cedar for comparison 333
![bandicam 2020-02-06 12-44-28-770](https://user-images.githubusercontent.com/27898520/73925541-06b38280-48f0-11ea-8294-f2a094cb2f6e.jpg)

Actually rainforest needs to be quite wide and heavy. 
Is it intentional or maybe need some more tweaks?

**Comment by beastyn** [comment]
For the comparison, in the newly generated world from 8.3.3.
0.53 km
Ceiba is just like the other trees - 300+ in numbers.
![bandicam 2020-02-07 17-24-10-337](https://user-images.githubusercontent.com/27898520/74029543-ba8b3f80-49ce-11ea-8a67-ac795891b4e1.jpg)
![bandicam 2020-02-07 17-24-14-407](https://user-images.githubusercontent.com/27898520/74029546-bb23d600-49ce-11ea-897b-9dfa555d5db9.jpg)
![bandicam 2020-02-07 17-24-25-444](https://user-images.githubusercontent.com/27898520/74029547-bc550300-49ce-11ea-81dc-c294600e66e0.jpg)

In genereal, it seems like we have a huge decrease for all the species

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/75584152-f80a4800-5a23-11ea-9081-afdade26a557.png)
Common Grass, Deer Lichen, Big Bluestem, Salal-- these types of species are overwhelming the biomes I think, and we need to find a way to maintain their 'ground cover' status while allowing more of the other plants to grow through. 

Huckleberries, Corn, Crimini Mushrooms, Camas-- these type of plants need to be significantly increased to well above 100, probably ~200 minimum starting population is a good goal for **all** plant species.

**Comment by StanKryvenko** [comment]
@keegan-o @beastyn how is it going now?

**Comment by WeaselDog** [comment]
I think it is safe to drop this in priority. It still needs work but is not causing significant issues in public playtesting. Rainforest biome has increased in size and it has Ceiba now, Food numbers are increased. Grass is still an issue but not nearly as bad and it will have another fix on Monday.

Going forward it might be easier to open specific issues We have these issues to solve for 9.0:
- https://github.com/StrangeLoopGames/EcoIssues/issues/14274
- https://github.com/StrangeLoopGames/EcoIssues/issues/14387
- Water plants are too densely packed (Might be fixed on Monday with change to initial population)

**Comment by SlayksWood** [comment]
Check pls this issue too #6906

**Comment by WeaselDog** [comment]
Marking this as fixed because we solved all the original issues. If you notice further issues with biome generation or species it would be much appreciated to open issues for those so they can be solved individually.
