### ISSUE TITLE
[0.9.0 staging-1387] Can't see District in Minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14646]
![image](https://user-images.githubusercontent.com/45708377/74009667-c528e300-4994-11ea-8727-2c7d323271cb.png)
update: You need reconnect to see it:
![image](https://user-images.githubusercontent.com/45708377/74009860-2e105b00-4995-11ea-92fd-0a047a597270.png)

**Comment by johnkslg** [comment]
Repro steps?
