### ISSUE TITLE
[0.9.0 staging-1387] "Place block" sound when dig or block changing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14647]
When you dig:
When block change to another block type. The best way to reproduce:
- /level 50,50 (not in Grassland Biome)
- wait when Crassblock start to change to another block:
![image](https://user-images.githubusercontent.com/45708377/74011881-f821a580-4999-11ea-8e94-45a44e193bf3.png)
![image](https://user-images.githubusercontent.com/45708377/74013744-3620c880-499e-11ea-890b-e3344edebcef.png)
My computer is lagging in that moment so only sound:
https://drive.google.com/file/d/1pbF5GxszzU-sjLWrTlhT2RSuapwtKwxZ/view?usp=sharing

**Comment by SlayksWood** [comment]
This sound happen when you place Objects too

**Comment by SlayksWood** [comment]
When I pick up item too:
![image](https://user-images.githubusercontent.com/45708377/74015116-12ab4d00-49a1-11ea-889e-56552cc29e1e.png)
It seems everywhere)

**Comment by beastyn** [comment]
And again, this placing block sound I hear with every action, like digging, mowing, mining.

**Comment by beastyn** [comment]
1458(7?) confirmed

**Comment by Quadbro** [comment]
yeap,  shame on me, messed two values order)
