### ISSUE TITLE
[0.9.0 staging-1387] Audio: drill sound

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14645]
1. Modern drill doesn't have a sound
2. Iron drill has a sound from a modern drill
3. Iron drill should have a sound for manual work (it doesn't have a motor)
4. When you are prospecting with iron drill, after fast LMB clicking (don't hold it) a sound will hang)

**Comment by Quadbro** [comment]
Manual sound will be swapped a bit later, other issues fixed

**Comment by beastyn** [comment]
Will close it, but im watching youuuuuu
>_>
