### ISSUE TITLE
Speaking icon missing sprite

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14658]
![image](https://user-images.githubusercontent.com/3536496/74107980-0dc5d500-4b2a-11ea-8dcf-bef4ee2c66ed.png)

Got this exception:
Wwise: Voice Starvation
UnityEngine.Debug:LogError(Object)
AkCallbackManager:PostCallbacks() (at Assets/Wwise/Deployment/API/Handwritten/Common/AkCallbackManager.cs:336)
AkSoundEngineController:LateUpdate() (at Assets/Wwise/Deployment/Components/AkSoundEngineController.cs:71)
AkInitializer:LateUpdate() (at Assets/Wwise/Deployment/Components/AkInitializer.cs:90)

**Comment by redwyre** [comment]
The voice starvation is unrelated (and I think it safe to ignore in the editor)
