### ISSUE TITLE
 [0.9.0 Staging 1388] Crafting Needs to take ALL items when placing an Order

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14656]
**Version:** 0.9.0.0 beta staging-1388

This seems to be the same for **ALL** orders 
1st Example
I order 16 Tomatoes as i have them in my Backpack, **i expect them ALL to be taken** as i have enough for the order
![snap6205](https://user-images.githubusercontent.com/29383891/74088616-3600f580-4a90-11ea-8363-f1690dbd5801.png)
![snap6206](https://user-images.githubusercontent.com/29383891/74088642-6f396580-4a90-11ea-96d5-e67022fe03b1.png)
but it will only take enough to make ONE Charred tomato, now because they are in my Backpack it will just sit on waiting for tomatoes until i physically place them in storage 
![snap6207](https://user-images.githubusercontent.com/29383891/74088685-c3dce080-4a90-11ea-9d31-1b7059da4e19.png)

BUT it will only take another one when the 1st one has crafted

2nd Example
I order Hewn logs on a Workbench
same thing happens it takes enough to start crafting ONE of them but will NOT take any more untill that one has crafted
![snap6208](https://user-images.githubusercontent.com/29383891/74088702-0e5e5d00-4a91-11ea-96e6-ef0895e0eb1a.png)

Now when you are playing you don;t have an infinite amount of storage so when this fills up because Crafting refuses to take All it needs for the order, so if you craft another order that **also** requires logs it will NOT take those either so you have to sit and wait also if you are sharing tables and deeds who is to know if those Logs are waiting to go in an order or actually are free to use?

Sometimes you can add ALL the Work calories to an order and sometimes you cannot, it doesn't seem to be balanced of when and how it decides to let you add them

**Comment by D3nnis3n** [comment]
This is intended, therefore closing.
