### ISSUE TITLE
USER ISSUE: Server Timeouts

### ISSUE THREAD

**Issue by ZockerBoysHD** [StrangeLoopGames/EcoIssues#14655]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Startup a server on Debian 10 
Join existing World (copied from singleplayer)
Craft something

**Expected behavior:**
it should timeout and work fine with near no delay (3ms ping!!)

**Actual behavior:**
it gets a temporarly timeout and im not able to do anything for 2-3 minutes

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed, default game configs

more information is actually in my reddit post for this issue: https://www.reddit.com/r/EcoGlobalSurvival/comments/ey9ek8/server_timeouts/

**Comment by beastyn** [comment]
Thanks you for the repory.
Please, provide logs from the client and the server 
(indtructions are here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world)

**Comment by ZockerBoysHD** [comment]
Server Log:
https://cdn.egopvp.com/notes/?bd098edb644457f8#cs/Ci8HiHeDAq7Tz3a2UHu3s53K5W75G5R9MLkQpOqc=

Player.Log:
https://cdn.egopvp.com/notes/?d72a59ece98782fa#8iJr+QNdQaIeA8nUzR6DOzOZNUHMt80sMI4miZEmHI4=

player-Prev.log
https://cdn.egopvp.com/notes/?71fe81a1eae69da0#/5aeIgO8DFQE1H4b5QG7NI+bHOXxzRiBoiMNIADcppE=

**Comment by mirasrael** [comment]
We are not supporting Linux servers officially. It seems like your server is very slow for requests processing and it is known problem that Linux servers has problems with performance. In 9.0 performance for Linux servers will be improved.

**Comment by ZockerBoysHD** [comment]
Yeah but i alredy tryed it running on a windows 10 server with the same results. 
The Server is has ~1.6Gbit/s read & write to nvme ssd, 10gbit/s network connection, 16 cores, 64gb of ram. dont think its that slow.

**Comment by ZockerBoysHD** [comment]
but ill test again when 0.9 is realeased :)

**Comment by mirasrael** [comment]
Ok. Thanks for report. Let us know if you still have issues after 9.0 release. I'll keep this open until that.

**Comment by redwyre** [comment]
@ZockerBoysHD Have you tried a 0.9 build?

**Comment by ZockerBoysHD** [comment]
nope, not yet.  I kinda stopped playing ECO but will try when i have the time for it in a few days.

**Comment by SlayksWood** [comment]
@ZockerBoysHD haven't tried it?

**Comment by SlayksWood** [comment]
Closed for now, reopen if you still have thi issue.

**Comment by ZockerBoysHD** [comment]
Now, some time Later,

Playing on a Windows 10 64Bit Server, latest version (0.9.2.4 beta release-156) 

World age: arround 10-15 real time days

we all are getting 300+ ms by default!  (5 players) with all other services like teamspeak have 10-20ms at max!
Nothing changed on the simulation speed etc. 
Worked when world was arround 5 days old, then sometime started being a problem

tick time:
https://screens.egopvp.com/files/2021/02/12/AnyDesk_MZRmIgJeaS.png

player ping:
https://screens.egopvp.com/files/2021/02/12/AnyDesk_6wRnCp5x8Y.png
