### ISSUE TITLE
Block changed models before my eyes

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1465]
I placed a log block near a dirt block, and the dirt block kind of turned into a log block

![image](https://cloud.githubusercontent.com/assets/23460210/26085002/9798bb8e-3995-11e7-9d0f-f08235455714.png)

**Comment by sr3ka** [comment]
I've experienced this a lot throughout 5.5.

**Comment by metachronism** [comment]
fixed
