### ISSUE TITLE
[0.9.0] Stuck on Login

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14654]
You are stuck at the point when you log in.
the only thing that helps is to move you briefly with "fly". then the problem no longer exists

**Comment by SlayksWood** [comment]
@Sekor2600 
Did it happen in Hosted World server?

**Comment by Sekor2600** [comment]
in my local Unity Test

**Comment by Conchipedia** [comment]
[0.9.0 Staging 1388]
same happens in a single player world when you log in

**Comment by Sekor2600** [comment]
fixed
