### ISSUE TITLE
[0.9.0 staging-1391] Underwater Distortion seems doesn't work and causes FPS drop.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14664]
Step to reproduce:
- dive under water. Have 50-70 FPS:
![image](https://user-images.githubusercontent.com/45708377/74136217-b5143c00-4bfe-11ea-9582-6ea7e5087025.png)
- set Underwater Distortion on. I have max 20 FPS:
![image](https://user-images.githubusercontent.com/45708377/74136236-bcd3e080-4bfe-11ea-85f1-8f5f52da7740.png)
my graphic settings:
![image](https://user-images.githubusercontent.com/45708377/74136403-0290a900-4bff-11ea-83a6-6787ecdf33d7.png)
To return my FPS i need to reconnect.

**Comment by SlayksWood** [comment]
Very strange effect xD:
![image](https://user-images.githubusercontent.com/45708377/74307198-d8adc280-4d75-11ea-8e6f-799685519d16.png)

**Comment by redwyre** [comment]
updated the underwater settings which didn't get saved last time

**Comment by SlayksWood** [comment]
Still an issue, but it isn't so crazy:
https://drive.google.com/file/d/1gb8xBoPKwwgGz24dWqHPvYuhU2fj2HqV/view?usp=sharing

**Comment by redwyre** [comment]
That's the current underwater effect. It works and doesn't drop FPS so this bug should be closed.
If you don't like effect that is separate issue ;) (I don't like it, but it's good enough for now)

**Comment by redwyre** [comment]
@SlayksWood are there still any fps issues?

**Comment by SlayksWood** [comment]
no, seems fixed
