### ISSUE TITLE
[0.9.0 staging-1391] Problems with quickly hiding  top chat 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14662]
- [ ]  It's more suggestion, but it's hard to read big notifications in top chat. So for me I want slight to increase time. But maybe another player doesn't need it. So If it's not hard then can you add possibility to set time as Height or width:
![image](https://user-images.githubusercontent.com/45708377/74132855-6b285780-4bf8-11ea-8f3e-2f78018b7f42.png)

- [ ] Time doesn't refresh if you have another notification. Step to reproduce:
- Chat display time is (according to my feelings) 4 seconds now.
- press order. top notification chat will appear. Time start: 4...3...2....
- ...1. Add another order. You have new notification, but chat will close after 1 sec. Time should be refreshed.

**Comment by gzatravkin** [comment]
Increased time, made refresh time by reciving notification. Didn't made configuration for display time, I think it would be too busy for interface to put so much settings
