### ISSUE TITLE
[0.9] Dying World?

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#14669]
Current Staging from Github

After some time the many mature Trees disappear and many new seedlings spawn in the world in a new World. (stupid for the lumberjack)
![grafik](https://user-images.githubusercontent.com/37456949/74173227-0be73900-4c32-11ea-8c00-fe149aa9e8bf.png)
with Fast Forward
![grafik](https://user-images.githubusercontent.com/37456949/74173307-3507c980-4c32-11ea-9315-2ff206d3a97c.png)

heavy Pollution from some Wood farming
![grafik](https://user-images.githubusercontent.com/37456949/74173395-54065b80-4c32-11ea-93ad-a3fbf074fbeb.png)
![grafik](https://user-images.githubusercontent.com/37456949/74173568-9c257e00-4c32-11ea-963d-c0afef4c6aeb.png)

Tree disappear and spawn anew
![grafik](https://user-images.githubusercontent.com/37456949/74173772-00484200-4c33-11ea-8d8b-6fad754f6f9e.png)

Oak disappear almost completely from 178 to 22

![grafik](https://user-images.githubusercontent.com/37456949/74173813-1950f300-4c33-11ea-97ca-f8aa6e959aed.png)

More Photos
New World
![grafik](https://user-images.githubusercontent.com/37456949/74174862-00e1d800-4c35-11ea-9eb7-34e0a0d54233.png)

old despawn new spawn with dying plants
![grafik](https://user-images.githubusercontent.com/37456949/74174913-21aa2d80-4c35-11ea-9284-3ba344df00b7.png)

Worlddata

[Game-2020-02-10-22.39.49.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4183453/Game-2020-02-10-22.39.49.zip)

**Comment by FalkosTMB** [comment]
![die](https://user-images.githubusercontent.com/43608607/74267215-f0e5f900-4d05-11ea-83cd-cd3d1b570f65.jpg)

**Comment by Sekor2600** [comment]
Ok after 2 Days Playtime (where Server was not always on)
Tortoise & Turkey are extinct
Any many Plants

**Comment by D3nnis3n** [comment]
Raising priority. World dying out is not "medium".

**Comment by FalkosTMB** [comment]
created a new world in 1403 ..... first login stats
![stats1](https://user-images.githubusercontent.com/43608607/74586618-91c80300-4fe9-11ea-989a-44f67882bdd9.jpg)
![stats2](https://user-images.githubusercontent.com/43608607/74586620-9391c680-4fe9-11ea-801c-0f023b54cee9.jpg)

**Comment by johnkslg** [comment]
@StanKryvenko can you take a look, and ill come help after my tasks

**Comment by StanKryvenko** [comment]
> @StanKryvenko can you take a look, and ill come help after my tasks

sure
