### ISSUE TITLE
[0.9.0 staging-1391] Exchanger: can't change a currency

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14668]
Just can't select other currencies except upir personal 
![bandicam 2020-02-10 16-43-08-460](https://user-images.githubusercontent.com/27898520/74147172-8741ee00-4c24-11ea-8c28-ef3b093fc229.jpg)

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/74393484-1e42ad80-4dbf-11ea-8401-e6865295f8ea.png)
