### ISSUE TITLE
[0.9.0 staging-1391] Claims: don't see claims in day time at all

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14667]
or like dark rectangles sometime
In the night
![bandicam 2020-02-10 16-35-53-398](https://user-images.githubusercontent.com/27898520/74146695-8066ab80-4c23-11ea-83f2-ff4071b0d544.jpg)

In the day
![bandicam 2020-02-10 16-36-45-619](https://user-images.githubusercontent.com/27898520/74146719-8e1c3100-4c23-11ea-86be-4bfc6b646949.jpg)

**Comment by keegan-o** [comment]
@redwyre Sean originally setup this view if I recall correctly, not sure how it works.. but maybe something with post processing is affecting it?

**Comment by keegan-o** [comment]
un-assigning self as there is not really anything I can do to help on the issue.

**Comment by redwyre** [comment]
Night
![image](https://user-images.githubusercontent.com/431728/86621424-88275200-c001-11ea-977f-8df2d7e8b012.png)

Day
![image](https://user-images.githubusercontent.com/431728/86621449-91b0ba00-c001-11ea-8941-4751b85c4779.png)

**Comment by beastyn** [comment]
Waiting for ##17031
