### ISSUE TITLE
USER ISSUE: server version not compatible

### ISSUE THREAD

**Issue by fleshburrito** [StrangeLoopGames/EcoIssues#14675]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
attempt login to server

**Expected behavior:**
launch server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Incompatible version.  User is 0.8.3.3 beta but server is 0.8.3.2 beta.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
no mods installed**
```
<size=150%>Connection Failed</size>

Incompatible version.  User is 0.8.3.3 beta but server is 0.8.3.2 beta.
```

**Comment by beastyn** [comment]
Server wasn't updated. You can ask as owner to update it.
