### ISSUE TITLE
Set up civic action icons

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14677]
![image](https://user-images.githubusercontent.com/3536496/74196725-ad5e9280-4c12-11ea-81fc-fe1460a57c1d.png)

Rob created icons for all these, plug them in to the Civic Action component. Make sure to use the View icon system to reference them, dont manually enter the names on the client. Ask me if questions, and check out Has View Icon component on client.

**Comment by serpopov** [comment]
Need to fix layout

**Comment by johnkslg** [comment]
This is working now!
