### ISSUE TITLE
Time of Day skybox ground color and lighting ambient color should be separated into two different settings

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14678]
This ambient color gradient in Time of Day settings controls ambient light/color, which is great:

![image](https://user-images.githubusercontent.com/14983165/74199798-109ff300-4c1a-11ea-97af-e667f7c94e52.png)
![image](https://user-images.githubusercontent.com/14983165/74199864-39c08380-4c1a-11ea-9692-b89c42a5fe1d.png)

But, this setting also controls the bottom half of the skybox.
![image](https://user-images.githubusercontent.com/14983165/74199942-6e343f80-4c1a-11ea-93ba-74df8545cee9.png)
![image](https://user-images.githubusercontent.com/14983165/74199969-7be9c500-4c1a-11ea-8058-89279a096aec.png)

This is the 'explanation' from the TOD documentation:
![image](https://user-images.githubusercontent.com/14983165/74199997-92901c00-4c1a-11ea-8d9d-34a2a3b1fd89.png)

My goal is to have the sliders be at 0 % alpha (totally see through) as far as how they affect the skybox's ground, and to be 100 % alpha for the ambient light itself. 

If we need to break the ambient out of TOD and put it somewhere else that might be easier than trying to override the 'ground' color. Then the TOD settings can just be put to 0 alpha. (But then we'll also have to re-create the gradient blending for the ambient color). Otherwise, it might be possible to stop TOD from affecting the 'ground color' directly, which *may* correspond to these locked (automatically get over-written, I imagine by TOD) settings in lighting:
![image](https://user-images.githubusercontent.com/14983165/74200493-f6ffab00-4c1b-11ea-9326-b854744f4338.png)

**Comment by ptitducanh** [comment]
I change the TOD_Scattering.cginc a bit to stop Ambient Setting from affecting the bottom half of the skybox.

**BEFORE**
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/83543372-013a-4439-adc0-e0e3da24f273)

**AFTER**
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/df30e380-2731-4bdf-80f8-da9726be59a2)
