### ISSUE TITLE
0.9 labor periodically not loaded correctrly.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14672]
As you can see - labor bar and labor indicator are full.
But order still need 1000 labor.
![20200210204427_1](https://user-images.githubusercontent.com/4980243/74175136-422eb380-4c46-11ea-9683-d795768761b1.jpg)

**Comment by elfl0rd** [comment]
repeatable, happens every time if you add multiple orders at one time.

**Comment by johnkslg** [comment]
Try in latest, it no longer uses tweens and I couldnt get it to happen anymore.

**Comment by elfl0rd** [comment]
yep, can't saw that in last versions.
