### ISSUE TITLE
[0.9.0 staging-1392] Audio: strange grass-walking sound

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14686]
It sounds like you have a lot of legs or you are stepping really fast.
https://drive.google.com/file/d/1xmpxByEzWemuHHOfPxEcquVdwI89Wtk0/view?usp=sharing

**Comment by beastyn** [comment]
No grass sound now at all.
And its still  making strange repetitions
https://drive.google.com/file/d/1FMXVXMRNtY9YRENrt3pPVT0AK9oj5H68/view?usp=sharing

**Comment by Quadbro** [comment]
that was repetative foot step sounds, they are fixed.
strange repetitions - it's block sound, that triggered in wrong places. not related to this
