### ISSUE TITLE
Ecopedia Content Todos

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14683]
- [x] Make images more square so they fit better
- [x] Pictures in Treasury component and registrar component
- [x] Change housing components icon to be a housing component (bed perhaps)
- [x] Add description of the advanced product selection to the Crafting Component section
- [x] Status component: (Update illustration to include pollution production)

**Comment by WeaselDog** [comment]
Going to leave off the pollution status component. It looks a little off but let me know if you would like me to include: 
![PollutionStatus](https://user-images.githubusercontent.com/47330823/77273203-389a6180-6c70-11ea-9ea4-53d3df350bb9.png)

**Comment by beastyn** [comment]
I think we need pollution component.
I there a way to see pollution?
