### ISSUE TITLE
USER ISSUE: Login Token Changed

### ISSUE THREAD

**Issue by mms84** [StrangeLoopGames/EcoIssues#14689]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I login into my server, and about 30 min later it kicks me out saying my login token has changed.

**Expected behavior:**
Not kicked me out

**Actual behavior:**

Login token changed. Possible login elsewhere.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**

Login token changed. Possible login elsewhere.
```

**Comment by beastyn** [comment]
Thank you for the report. Did you try to launch other client at the same time? This error can appear if another client was used with the same login.

**Comment by mms84** [comment]
I was in the game when it happened and hadn’t launched anything during that
time. I did have a browser open but I wouldn’t think that would effect it?

**Comment by WeaselDog** [comment]
@mms84 This error should only happen when there are two instances of a login, even if it is on the same computer.  I am not sure what caused it in this case, but it should not be from opening the browser. Have you experienced this issue again?

Thanks again for reporting this.

**Comment by mirasrael** [comment]
It may happen if you login to Eco site (in browser). But if you didn't then it probably issue with Steam (which eventually happens unfortunately).

**Comment by beastyn** [comment]
This also can be steam issue.
Log out from steam
Reboot you PC
Log in

That should help
