### ISSUE TITLE
Implement a '/remove _____block, 50, 50' Dev command (for worldgen visual debug)

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14681]
To visually debug and inspect what is going on with world generation and blocks that are spawned underground, a new dev command to remove all block types of a named type within a specified area would be extremely useful.

So if I typed "/remove GrassBlock, 50,50", it would remove all GrassBlock blocks in that area. Sort of like /level but to remove only particular blocks instead of replace/add. 

The point is to be able to see through soils and plants to the rocks underneath, so an additional command to do this quicker by removing all these block types in the specified area would be great:
"/remove soil, 50,50" would remove all these block types in the defined area:
GrassBlock
RockySoilBlock
DirtBlock
WetlandsSoilBlock
SandBlock
RiverSandBlock
CharredEarthBlock
SnowBlock
TilledDirtBlock
DesertSandBlock
OceanSandBlock
RainforestSoilBlock
ColdForestSoilBlock
WarmForestSoilBlock
TaigaSoilBlock
ClayBlock
FrozenSoilBlock
TundraSoilBlock

**Comment by SlayksWood** [comment]
Move this command to Developer.
![image](https://user-images.githubusercontent.com/45708377/75424038-fc196580-5950-11ea-8de9-236b2957999c.png)
