### ISSUE TITLE
0.9 iron/gold/copper concentrate req hammer to pickup but carried with shovel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14680]
![изображение](https://user-images.githubusercontent.com/4980243/74200683-a36f7a80-4c78-11ea-953a-813b8d79ce37.png)

**Comment by SlayksWood** [comment]
This was already fixed, but it's broken again. #13112

**Comment by SlayksWood** [comment]
I can't pick up it with exca/skidsteer too.

**Comment by SlayksWood** [comment]
Gold concentrate is missing in shovel:
![image](https://user-images.githubusercontent.com/45708377/74407536-41af3c00-4e43-11ea-9c3a-135839054a9a.png)

**Comment by SlayksWood** [comment]
Hammer take first concentrate from stockpile instead construction blocks:
![image](https://user-images.githubusercontent.com/45708377/77302642-b3ac5800-6d02-11ea-847e-528fd843314e.png)
I should take Mortared sandstone with a hammer, but i take Copper Concentrate:
![image](https://user-images.githubusercontent.com/45708377/77302719-ce7ecc80-6d02-11ea-9977-e9a0a001d932.png)
