### ISSUE TITLE
8,3,3 Контракты счет получателя

### ISSUE THREAD

**Issue by Elsygame** [StrangeLoopGames/EcoIssues#14696]
Обрисую ситуацию вместе с скринами
Скрин моей валюты
![Screenshot_2](https://user-images.githubusercontent.com/53664488/74282634-c8b7c380-4d20-11ea-8b8d-e1d110a9776a.png)
Я (Elsion) создаю контракт "Сделать работу"
![Screenshot_1](https://user-images.githubusercontent.com/53664488/74282500-8aba9f80-4d20-11ea-80ec-f7fc4a70872d.png)
приходит игрок №1 (Andrix) открывает доску контрактов ,открывает контракт и выставляет в строке счет получателя свой счет, НО не принимает контракт.
![Screenshot_3](https://user-images.githubusercontent.com/53664488/74282803-0b799b80-4d21-11ea-8593-35176401e015.png)
Приходит игрок №2 (ЕкарныйБабай) открывает доску контрактов, выбирает контракт , абсолютно ничего не меняет принимает контракт
![20200212003810_1](https://user-images.githubusercontent.com/53664488/74282936-4da2dd00-4d21-11ea-8284-847389319ffe.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/53664488/74282964-5b586280-4d21-11ea-98da-5d941c3d02ff.png)
Потом игрок №2 выполняет работу и нажимает кнопку работа выполнена
![Screenshot_5](https://user-images.githubusercontent.com/53664488/74283027-788d3100-4d21-11ea-8bbc-88cc8a61c23e.png)
![Screenshot_6](https://user-images.githubusercontent.com/53664488/74283044-82169900-4d21-11ea-9d03-d04360b381e7.png)
я как создатель контракта подтверждаю работу
![Screenshot_7](https://user-images.githubusercontent.com/53664488/74283089-98245980-4d21-11ea-91d8-4250c8926eea.png)
А деньги уходят игроку №1 который выставил свой счет в начале
![Screenshot_8](https://user-images.githubusercontent.com/53664488/74283142-ad00ed00-4d21-11ea-8c97-6b9f62b58a0b.png)

**Comment by Elsygame** [comment]
Если создать контракт с повторением
![Screenshot_10](https://user-images.githubusercontent.com/53664488/74283885-06b5e700-4d23-11ea-8936-56474dc55070.png) то счет первого выполнившего контракт будет стоять по умолчанию для остальных

**Comment by beastyn** [comment]
Спасибо за информацию.
Уже  исправлено для  0,9.
Часть с повторением проверить (после #14704)
