### ISSUE TITLE
0.9 wrong number of materials for smelting.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14694]
without modules
![изображение](https://user-images.githubusercontent.com/4980243/74276061-1125b000-4d26-11ea-9fbe-e946e1b0c780.png)

but really ask...
![изображение](https://user-images.githubusercontent.com/4980243/74276119-2d295180-4d26-11ea-9477-f685180a70dc.png)

3>2>1 (with 50% modules for arrastra and rocker)
24>16>8
24 ore for 1 ingot.

12>4>1 (no modules)
96>32>8
96 ores for 1 ingot.
Srsly?

**Comment by WeaselDog** [comment]
Thank you for pointing this out. We have already reduced the amount of Iron Concentrate required and we will continue to adjust the numbers.
