### ISSUE TITLE
0.9 regression - cannot add holded materials by RMB

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14690]
As i see, it result of conflict with labor system
![изображение](https://user-images.githubusercontent.com/4980243/74241659-89bc4a80-4ced-11ea-8aad-ed619230cd70.png)

![изображение](https://user-images.githubusercontent.com/4980243/74241695-98a2fd00-4ced-11ea-8af8-d802b05cf987.png)

**Comment by beastyn** [comment]
Fixed in the latest staging #14543
