### ISSUE TITLE
[0.9.0 Staging 1392] Occasionally when joining world for First Time hard to see Player to Edit Properly

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14691]
**Version:** 0.9.0.0 beta staging-1392

![snap6222](https://user-images.githubusercontent.com/29383891/74251938-d0597700-4ce4-11ea-8448-d80939a2db3c.png)

this has been happening on Previous Versions, but this one seemed the worse so far on being hidden

**Comment by beastyn** [comment]
dup #12625
