### ISSUE TITLE
 [0.9.0 Staging 1392] Size at bottom of Tooltip is wrong for Stockpiles, maybe this is also incorrect for other items

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#14693]
**Version:** 0.9.0.0 beta staging-1392

Stockpile is 5x5x5 but at the bottom of Tool tip says different size (did the rest of the stockpiles to make sure it wasn't just on One type
![snap6237](https://user-images.githubusercontent.com/29383891/74268995-b29a0b00-4d00-11ea-8296-48f86c973071.png)
![snap6238](https://user-images.githubusercontent.com/29383891/74268996-b3cb3800-4d00-11ea-9150-74727134c94d.png)
![snap6239](https://user-images.githubusercontent.com/29383891/74268998-b3cb3800-4d00-11ea-9207-87931dfb6f6d.png)

are the bottom sizes in what ratio? (which order?)
how high
how wide
how deep
remember not everyone reads 3D items in x,y,z co-ordinates maybe have a section in Ecopedia explaining the order of them?

**Comment by SlayksWood** [comment]
merged #13864
