### ISSUE TITLE
Various rendering issues while moving camera around (shadows/sunlight in particular)

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14700]
In the past, shadows would move as you ran through the world, which was weird enough and a problem of its own. But now they can wildly move while just moving the camera around.
![movingshadow2](https://user-images.githubusercontent.com/14983165/74294469-d5252780-4cf2-11ea-93c7-83bbe38ae146.gif)

So can the meteor!
![movingmeteor](https://user-images.githubusercontent.com/14983165/74294483-dfdfbc80-4cf2-11ea-9b1e-5b49b3453634.gif)

![sunmovingwithcamera](https://user-images.githubusercontent.com/14983165/74294423-ad35c400-4cf2-11ea-96a1-328e9f650dfd.gif)

**Comment by keegan-o** [comment]
![sunmovingwithcamera2](https://user-images.githubusercontent.com/14983165/74480465-cdd25b00-4e65-11ea-95c5-93edabaedef4.gif)
Weeeee

**Comment by keegan-o** [comment]
This bug also wildly breaks one of the very first tutorials with the meteor, since the meteor dances around as you look for it and then when the camera zooms into the meteor, it just careens off somewhere else into the sky (the camera does, quite nauseating)

**Comment by SlayksWood** [comment]
> https://youtu.be/p0mmEKWaWEU
> https://youtu.be/JjYuoyxIAEk

**Comment by johnkslg** [comment]
Keeping this as it breaks the meteor intro tutorial / new user experience. 
Shadows we can push if needed.

**Comment by keegan-o** [comment]
![brokenlighting9](https://user-images.githubusercontent.com/14983165/81621481-5c8e3f80-93a3-11ea-965a-30e35a343002.gif)

breaks end-game experience as well, and when the meteor is up near noon it is just ridiculous if you try to look at it.

This also makes it so we can't improve the look of the meteor with any trail effects.

... But more than any of that, the shadows thing is just really gross and janks out the entire look of the game imo. Shadows are a pretty important fundamental part of the lighting and look...

**Comment by keegan-o** [comment]
Upping this to high because it does more or less prevent getting good promotional videos of 9.0, and I do find it extremely annoying in-game. But I see it has week task now, which is exciting :)

**Comment by redwyre** [comment]
this is fixed in SVN

**Comment by beastyn** [comment]
Lasers have a different issue 
#10978
