### ISSUE TITLE
[0.9.0 Staging 1399] Contracts: repetitions don't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14704]
1. Create contract with repetitions
2. Someone take it 
![unknown (50)](https://user-images.githubusercontent.com/27898520/74308202-68a93780-4d89-11ea-810b-27958b473ae5.png)
![unknown (51)](https://user-images.githubusercontent.com/27898520/74308216-6e9f1880-4d89-11ea-96ff-565b6e03f78b.png)
3. Contract will disappear from the board
![unknown (52)](https://user-images.githubusercontent.com/27898520/74308226-79f24400-4d89-11ea-9660-3b14f7c2062c.png)

**Comment by beastyn** [comment]
Now it creates a new contract, when you are taking the one with repetitions (and decreasing repetition number).
And as result one person can have a lot of similar contracts without any possability to finish them.
![unknown (55)](https://user-images.githubusercontent.com/27898520/74434080-7ba03280-4e83-11ea-8604-b7b47c1eecfa.png)
![unknown (56)](https://user-images.githubusercontent.com/27898520/74434087-7e028c80-4e83-11ea-86bb-8755dca6c6c9.png)
![unknown (57)](https://user-images.githubusercontent.com/27898520/74434091-7fcc5000-4e83-11ea-8402-8b91de18839b.png)

**Comment by johnkslg** [comment]
Fixed, accept button doesn't appear now if you have a copy.

**Comment by beastyn** [comment]
Why do we create a new contract with the different name?
I've created a contract with the name "Repetition"
But after it was accepted by a person, I have another contract with the name "Contract 21" on a board. Its frustrating.
![bandicam 2020-02-14 12-04-03-843](https://user-images.githubusercontent.com/27898520/74508933-1ea78980-4f22-11ea-8f06-012d4b8bf1ed.jpg)

**Comment by beastyn** [comment]
And also repetition doesn't work now (checked with put in container). It the same person will take a contract again there is now way to finish it.
It was fixed before #12518
maybe @olegshegai can look at this one.

**Comment by johnkslg** [comment]
Fixed naming and made items in container work on repetitions. Thanks!

**Comment by beastyn** [comment]
Nope, still renaming and not doable for repeated ones
Putin quest is original
Contract 2 was created after accepting
![bandicam 2020-02-20 16-30-32-244](https://user-images.githubusercontent.com/27898520/74930159-d21aed00-53fe-11ea-9180-95e666f6820f.jpg)
