### ISSUE TITLE
Giant cactus fruit have same icon as Prickly pear fruit

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14709]
![изображение](https://user-images.githubusercontent.com/4980243/74313428-b8d1cb00-4d84-11ea-9e1a-f3e366fcb86f.png)

![изображение](https://user-images.githubusercontent.com/4980243/74313448-c0916f80-4d84-11ea-8f5a-6133e7db3677.png)

**Comment by elfl0rd** [comment]
technicaly its fixed

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82958630-a44bc400-9f6a-11ea-8add-11cf90eff2ff.png)
Too similar still, create a new icon for the 'giant cactus fruit' item @RobertMangano. The giant cactus is based on a Saguaro, which has fruits that look like this:
![image](https://user-images.githubusercontent.com/14983165/82958698-d2310880-9f6a-11ea-9839-f157f5d7fa6a.png)
in-game we actually do have some representation of the fruits in the tree debris spawned by saguaros on cut-down:
![image](https://user-images.githubusercontent.com/14983165/82958746-f987d580-9f6a-11ea-82b3-0a59534d752d.png)

**Comment by keegan-o** [comment]
I'd say one of the biggest differences between saguaro and prickly pear is the saguaro fruits are a lot bigger so it could be like the papaya icon

**Comment by RobertMangano** [comment]
new icon is on icon sheet 04, I assigned it to the item in the unity eco scene.
