### ISSUE TITLE
Weird visions through door window

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1471]
![image](https://cloud.githubusercontent.com/assets/23460210/26168482/0ee54a5e-3aef-11e7-9e0e-28f192ff0fbb.png)

**Comment by SeanAtr0n** [comment]
is your svn all up to date?

**Comment by MarjieAVolk** [comment]
Yep, just updated everything again to be sure, and I'm still seeing it, 100% of the time

**Comment by metachronism** [comment]
are you still seeing this?  cant repro

**Comment by MarjieAVolk** [comment]
I'm still seeing it 100% of the time on my local client, but it's fine when I run the staging client

**Comment by metachronism** [comment]
might need to reimport shaders, if its working on staging I'm gonna close this out
