### ISSUE TITLE
[0.9.0 staging-1399] Resources progress in work party always show 0%.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14715]
Step to reproduce:
- create work party and add some resources and labor:
![image](https://user-images.githubusercontent.com/45708377/74333024-24795f80-4da8-11ea-9d19-4e185d53b6f0.png)

**Comment by mirasrael** [comment]
Just started order which has pre-allocated resources (5%):

![image](https://user-images.githubusercontent.com/475445/74339641-8ab8af00-4db5-11ea-9cb1-24fc5917bdfd.png)

Added 20 Logs directly to order (some of them go to stockpile):

![image](https://user-images.githubusercontent.com/475445/74339775-c9e70000-4db5-11ea-88e1-73976cab8a8f.png)

Joined work party and added as DevQA user:
![image](https://user-images.githubusercontent.com/475445/74340234-9bb5f000-4db6-11ea-8f7e-bf5369cfe2bf.png)

Everything works as expected.

**Comment by SlayksWood** [comment]
It doesn't work for me and Anna.
![image](https://user-images.githubusercontent.com/45708377/74412739-2ba77880-4e4f-11ea-985b-1036e22ecdc0.png)

**Comment by beastyn** [comment]
Looks like its counting resources but doesn't update bars and numbers

**Comment by johnkslg** [comment]
I went ahead and fixed this, can review @mirasrael

**Comment by SlayksWood** [comment]
fixed 
![image](https://user-images.githubusercontent.com/45708377/74508463-22caab80-4f10-11ea-9f6a-eea86887c257.png)
