### ISSUE TITLE
Mortared Fireplace texture fitting in with Mortared Walls

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14719]
![изображение](https://user-images.githubusercontent.com/4980243/74348246-724f9100-4dc3-11ea-812b-f0d8a2eadc69.png)

**Comment by keegan-o** [comment]
Phlo see if you can either add some kind of rim/border to these assets, perhaps just a thin layer of mortar, or alternately investigate the results of putting the triplanar material on the world object (that would be an interesting thing to test, might not work)

**Comment by Phlo123** [comment]
![1](https://user-images.githubusercontent.com/17730996/90109021-d4c62180-dd53-11ea-8c35-554e3aeccfe5.gif)
Haven't modified the prefab's or materials in unity. Uploaded the new textures to Working.

**Comment by keegan-o** [comment]
Priority changed to high since the hard work is done and the easy work needs doing.

**Comment by Phlo123** [comment]
Task complete.
![image](https://user-images.githubusercontent.com/17730996/97320551-95996e00-1876-11eb-8bdb-c8591c343811.png)
