### ISSUE TITLE
[0.9.0 staging-1399] Work party doesn't add to Work notification.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14713]
Step to reproduce:
- place workbench and start order:
![image](https://user-images.githubusercontent.com/45708377/74330861-85526900-4da3-11ea-9bfe-69f6c02d86b1.png)
- place contract board and open it:
![image](https://user-images.githubusercontent.com/45708377/74330877-900cfe00-4da3-11ea-9bbd-88f8a1b7b799.png)
- press create work party:
![image](https://user-images.githubusercontent.com/45708377/74330909-9c915680-4da3-11ea-9e0e-17a4c0ceb417.png)
- press ESC, you should see your workparty draft in work notification:
![image](https://user-images.githubusercontent.com/45708377/74330951-b3d04400-4da3-11ea-8e11-ba0c8690c20f.png)
- you can't open this workparty and can't create new workparty in this contract board:
![image](https://user-images.githubusercontent.com/45708377/74331023-d82c2080-4da3-11ea-95bc-a59e157c2847.png)

**Comment by johnkslg** [comment]
Was an exception in the work list. Fixed.
