### ISSUE TITLE
[0.9.0 staging-1399] Wrong icons for some Lumber furniture.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14716]
If I understood star logic right then all lumber furniture should have 2 stars.
![image](https://user-images.githubusercontent.com/45708377/74334268-9d79b680-4daa-11ea-9bc0-f5eb8c3000c1.png)
So Hardwood Lumber Table(3stars),  Lumber Table(1star), Lumber Chair(3stars), Softwood Lumber chair(3stars) have wrong star number.

**Comment by keegan-o** [comment]
fixed in staging
