### ISSUE TITLE
Selection dead zones

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14722]
Notice this on a lot of objects. Here it is on the Government Office. 
Note that the top text stays, but the selection highlight doesn't. 
![anim](https://user-images.githubusercontent.com/3536496/74384081-5c32d800-4da5-11ea-98df-e707448b4459.gif)

**Comment by SlayksWood** [comment]
> Like on this court. whats going on here?
> Generated with /civics spawngov if you want to repro the same scene
> ![anim](https://user-images.githubusercontent.com/3536496/78720449-95d21c00-78da-11ea-866c-ba89fc600007.gif)

**Comment by johnkslg** [comment]
Pulling back to 9 because its very annoying

**Comment by beastyn** [comment]
I would say it is still valid.
https://drive.google.com/file/d/1iEMNralL6sgfgWiNeFENO7827NcDJEJo/view?usp=sharing
