### ISSUE TITLE
Minimap can vanish

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14723]
![image](https://user-images.githubusercontent.com/3536496/74394102-c311ba80-4dc0-11ea-8b72-d25fd444bd80.png)
I tried to popout the minimap, it seemed to disappear entirely with no way to get it back.
Turns out it was compressed real tiny on the side.
Minimap should have functionality that forces it to be a minimum size and on screen, no matter what settings say

**Comment by SlayksWood** [comment]
I moved my minimap to second monitor by third try(. First 2 times it was returned, but third time It didn't return:
![image](https://user-images.githubusercontent.com/45708377/78129356-2662b500-7420-11ea-8069-1aebfd495337.png)

**Comment by beastyn** [comment]
Still need to bring map back after resizing (its appearing back after moving, but can vanish with resizing)

https://i.gyazo.com/483caa38154536a7182065c8b436bead.gif
