### ISSUE TITLE
Balance|Suggestion: plow lands should not be permanent

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14726]
As i think, plow should disappear after planting a plant|tree.

Why?
1st - you can "cool" plant trees and decorative plants, without ugly plow block under it
2nd - farmers really need plough, every time, not only one.

**Comment by Grisu11225** [comment]
if the plowed bottles disappear, how does it work with farming talent farming helpers?

**Comment by elfl0rd** [comment]
The plant is still a farm plant, not a wild one.

**Comment by Grisu11225** [comment]
ok thanks for the information, i still have a question, what time interval should the recovery have? not that you have to plow again and again in very large fields and before you have sown the plowed fields disappear.

**Comment by elfl0rd** [comment]
no interval, like real world - after you gather plant, you need plow field again.

**Comment by Grisu11225** [comment]
ok, then it will probably be a bug, many of the plowed fields will reset themselves before the seeds have been planted.

**Comment by IcedForge** [comment]
I do like this idea, and there was a lot of appreciation as it added some layering into farming skill in general and also opens up for more frequent use of machinery (plowing) maybe tie it into on harvest revert block? Still wouldnt fix OP's point of planting stuff without the tilled ground look but it would resolve the concern on the non need of ever plowing again?

**Comment by WeaselDog** [comment]
> The ground should require tilling every cycle with with tilling calories impacted by farming

**Comment by WeaselDog** [comment]
When doing a harvest by hand, scythe, or shovel, it should check if the harvested block is tilled and restore it to regular dirt if so.

**Comment by TwixterZ** [comment]
changes tested and confirmed working as of 9.4 develop 255

https://images.zenhubusercontent.com/47210472/4e1ad80e-2ee3-4332-acc8-e277ee65738e/747ff1a628c4690f4a33baf9b013bf28.mp4
