### ISSUE TITLE
[0.9.0 staging-1400] Work party: need hints on tables

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14729]
When you've taken workparty and go to the table yoiu need to see some hints avout what and where you can add.
1. Red highlight is making you thinks that you can't do anything.
If its possible to make table with green highlight and openable. But you can interact only with your party order.
2. Need to make a hint about putting resources and calories with targeted table (like with normal crafting) Now it tells nothing about your ability to add something
![unknown (53)](https://user-images.githubusercontent.com/27898520/74423038-6ae6c100-4e71-11ea-9342-0eabf76b0c81.png)
3. When linkled stockpile is full and you are trying to add resources, it tells you that you can't add labor. It should tell you that storage is full.
![unknown (54)](https://user-images.githubusercontent.com/27898520/74423851-bea5da00-4e72-11ea-8b8e-0f9e3381e567.png)

**Comment by johnkslg** [comment]
@mirasrael can you take #2, I'll take #1

**Comment by mirasrael** [comment]
#3 should be already fixed.

**Comment by johnkslg** [comment]
Fixed 1: made it highlight blue when you have a contract or workparty that is affecting permissions somehow:
![image](https://user-images.githubusercontent.com/3536496/74614277-6e758480-50cb-11ea-982c-3c90f8b97949.png)

**Comment by johnkslg** [comment]
Fixed #2 with a special note in the popup text:
![image](https://user-images.githubusercontent.com/3536496/74617626-fe72f880-50e2-11ea-99d5-d4113577b5a6.png)


It will also show you actions you could do as if you had full permissions. This might not be 100%: the workbench could have full storage, you might only have limited permissions, etc, so not every option shown will actually be possible (its really hard to tell that without actually performing the action, running it through the crafting system, law system, etc), but I think this will be sufficient, let me know what you think.

**Comment by johnkslg** [comment]
Also added to distribution station and contracts which have special access.
![image](https://user-images.githubusercontent.com/3536496/74617877-3d557e00-50e4-11ea-899c-3aa8b8b20e3e.png)
Removed 'Use' popping up on things you couldnt use. 

And removed

**Comment by beastyn** [comment]
2. Its unreadable now
![unknown (58)](https://user-images.githubusercontent.com/27898520/74645704-3e48e700-519a-11ea-91f2-6087ebc82b5a.png)
3. Now its taking the resources, the calories, And tells nothing if space is not enough
(order wants 170 logs. I have ten. But there is no place in the stockpile. Im trying to give my logs and don't see any message)
![bandicam 2020-02-17 15-32-26-566](https://user-images.githubusercontent.com/27898520/74646107-055d4200-519b-11ea-994e-7667fc998538.jpg)
![bandicam 2020-02-17 15-25-12-959](https://user-images.githubusercontent.com/27898520/74646113-068e6f00-519b-11ea-9ace-8d1d19f31327.jpg)

**Comment by johnkslg** [comment]
Moved the marker up to its more readable. Still not perfect, but should do for 9
![image](https://user-images.githubusercontent.com/3536496/74684635-43e60300-5181-11ea-96bd-38eee8b95930.png)

**Comment by johnkslg** [comment]
Also put labor on shift + right click, and made it display:
![image](https://user-images.githubusercontent.com/3536496/74794852-4035a780-5279-11ea-9bc0-6fb3d8c21850.png)

**Comment by redwyre** [comment]
How did you add the shift action? I have an old half-finished branch for adding support for modifiers.

**Comment by johnkslg** [comment]
A big ol refactor...

**Comment by johnkslg** [comment]
Still polishing up for PR

**Comment by johnkslg** [comment]
Some more progress on this. Here are two attempts to put into a storage, first one goes through, second its too full.
![image](https://user-images.githubusercontent.com/3536496/74884624-767e3000-5328-11ea-82b0-9f880c559411.png)
