### ISSUE TITLE
Contract board and other icons not appearing on minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14724]
![image](https://user-images.githubusercontent.com/3536496/74394210-fbb19400-4dc0-11ea-81b9-c34d72e00757.png)
Check other objects too.

**Comment by WeaselDog** [comment]
This is true for many more objects than Contract Board. It also does not appear in the world map or cause the map filter list to grow. I don't have a complete list, but it does not affect a Store which is also in the "Economy" map category.

**Comment by johnkslg** [comment]
Boosting because finding these boards is critical to workparties feature.

**Comment by johnkslg** [comment]
Also do a full pass on getting icons to show in the minimap that should be displayed.  @WeaselDog can you help on this issue to decide which icons are on by default, and which can be toggled by the menu?  Todd can help tag the items.

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/77309439-b791a780-6d0d-11ea-92f0-400635d00738.png)
