### ISSUE TITLE
Log hit boxes make building hard

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1472]
I feel like all blocks should have their hitbox be the whole box, but logs seem to have their hitbox be the shape of the model.  It makes it really hard to place another block along the "cut" end of a placed log.

**Comment by metachronism** [comment]
I think this is because of the changes sean did for bridge building - before it would treat everything as a box

**Comment by SeanAtr0n** [comment]
treating everything as a box would be ideal but that'll take some work. previously it made other silly assumptions, it definitely did not treat things as boxes

**Comment by knexer** [comment]
It doesn't seem to be just using the model as the hitbox.  See the last two images in [this album](http://imgur.com/a/OdeFT) for an example where I wasn't able to place a on top of a log even when there's a fairly large surface available for placing on.

**Comment by metachronism** [comment]
fwiw
https://github.com/StrangeLoopGames/Eco/pull/1278
seems to be the offending change, I think its better before too

**Comment by SeanAtr0n** [comment]
Guess i can spend some more time on this one now... it wasn't better before though
