### ISSUE TITLE
[0.9.0 staging-1400] Civics, Laws: lost Citizen with few triggers

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14731]
1. Create a law with two triggers
2. Try to check if Citizen is an Admin
![bandicam 2020-02-13 15-37-38-269](https://user-images.githubusercontent.com/27898520/74426526-56a5c280-4e77-11ea-84ae-22bc5af835a9.jpg)
3, The law is invalid because its trying to find who should be checked for condition

**Comment by johnkslg** [comment]
Fixed. When a context is available in all the triggers selected, it will show up. If it's only available in some of the triggers, it won't.

Known issue: it will display the help for the first trigger.  Let's live with this one and we'll fix it later, its not an easy fix. 
![image](https://user-images.githubusercontent.com/3536496/74483772-fa897100-4e6b-11ea-82f0-16b83ea55d06.png)
