### ISSUE TITLE
[0.9.0 staging-1400] Civics: no Citizen in titles requirements

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14730]
I'm trying to create an elected title with requiremetns with hours played for candidated.
But I can choose only specific person for checking.
![bandicam 2020-02-13 14-38-37-987](https://user-images.githubusercontent.com/27898520/74424453-cd40c100-4e73-11ea-8f13-36228fb99d1c.jpg)

It can be done with demographic but this option in titles seems to be frustrating for players

**Comment by WeaselDog** [comment]
This is also true for title at registrar

**Comment by johnkslg** [comment]
Fixed elected title
![image](https://user-images.githubusercontent.com/3536496/74484351-3ec94100-4e6d-11ea-9cab-b48fa4e8da07.png)
