### ISSUE TITLE
USER ISSUE: Can't access server browser

### ISSUE THREAD

**Issue by shadowstrider2** [StrangeLoopGames/EcoIssues#14739]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. open server browser via in game legal or graph menu ("L" or "G" then click "Yes")

**Expected behavior:**
It should have opened the server browser and shown the map and graphs, etc.		

**Actual behavior:**
Instead it opened the browser and said "refused to connect".
I just used it on a different server, but then this server doesn't work

**Do you have mods installed? Does issue happen when no mods are installed?:**
Instead it opened the browser and said "refused to connect".
I just used it on a different server, but then this server doesn't work

**Comment by shadowstrider2** [comment]
No mods installed, completely vanilla and issue persists.

**Comment by SlayksWood** [comment]
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and, if you have same problems, provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Which kind of internet connection are you using?
3. Did you meet this issue after updating to the 0.8.3.3 or you had it before?
4. Does Server have external IP address and did server admin use it in config file? (try to find out it if possible)

**Comment by shadowstrider2** [comment]
1. Specific server --> local hosted server. Issue does not persist on
official servers or other servers, just locally hosted servers

2. My internet is cable (~500mb/s download)

3. This issue has persisted before and after update 8.3.3

4. No, it is locally hosted so localhost:3001. I never messed with any of
the network or server configs coding except to adjust the world generation
to better suit larger worlds.

Thanks for your help!
James

**Comment by SlayksWood** [comment]
closed for now. There are a lot of changes and can't reproduce it in newest versions and don't have such feedback now. we create a new issue if it happens again.
