### ISSUE TITLE
GI 'low' setting is too bright

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14738]
There may be some kind of scaling per setting we could create, but for now the 'low' setting on Global Illumination is just way too bright, and it should simply be disabled/skipped over. Other settings don't need to be re-named (unless that's easier), just de-activate the 'low' setting as an option. 

(Decreasing GI brightness defeats the point of having it as an option for the higher quality settings)

**Comment by Quadbro** [comment]
Added ignore for low (had  value = 1, shifted to 2) but "low" setting still existst

**Comment by beastyn** [comment]
Looks like Low is still here.
Also looks like at the some point I can't switch quality (seems like nothing changes)
https://drive.google.com/file/d/1WQJ1QNlOwnRHbYLNla0wOpnesd8ycSv6/view?usp=sharing

**Comment by keegan-o** [comment]
fixed again by https://github.com/StrangeLoopGames/Eco/pull/6268

**Comment by keegan-o** [comment]
gonna just close this one and let the other duplicate anna made be closed by QA when confirmed
