### ISSUE TITLE
Elections: When changing selections, 'Loading Layer' didnt disappear after the layer was loaded. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14741]
![image](https://user-images.githubusercontent.com/3536496/74495589-118c8b00-4e8d-11ea-89b6-a7a3588db984.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/74495694-66c89c80-4e8d-11ea-89a6-ed93fb1084d7.png)
Also, when this is dragged all the way to the left, it says day 0, but scrolling ahead jumps to 'day 1'

**Comment by gzatravkin** [comment]
1. CNR, looks be already fixed (loading layer text). If not, please provide repro steps.
2. Fixed (also with comments, they also starts with day 0).
