### ISSUE TITLE
[0.9.0 staging-1402] Work party: markers on table and work party  won't disappear

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14747]
1. Create 3 orders
![bandicam 2020-02-14 15-01-37-291](https://user-images.githubusercontent.com/27898520/74521520-55d66480-4f3b-11ea-9a30-2b1d0bb6963d.jpg)

2. Create three work parties for them
![bandicam 2020-02-14 15-02-35-727](https://user-images.githubusercontent.com/27898520/74521535-5969eb80-4f3b-11ea-9dfd-da1ed11cb4a5.jpg)

3. Delete orders.
markers and parties are still here
![bandicam 2020-02-14 15-02-55-692](https://user-images.githubusercontent.com/27898520/74521608-71da0600-4f3b-11ea-8642-546226e6a93a.jpg)
![bandicam 2020-02-14 15-02-57-666](https://user-images.githubusercontent.com/27898520/74521612-730b3300-4f3b-11ea-840c-2dc276ad48dd.jpg)

**Comment by johnkslg** [comment]
Fixed!

**Comment by beastyn** [comment]
We also should clear contract board from invalid parties.
I don't have order, but party from it is still on the board and list.
![bandicam 2020-02-17 14-25-54-124](https://user-images.githubusercontent.com/27898520/74641595-63862700-5193-11ea-9b7a-e8c1d0a4aeaa.jpg)
![bandicam 2020-02-17 14-25-58-648](https://user-images.githubusercontent.com/27898520/74641602-64b75400-5193-11ea-9a3b-31251954acde.jpg)
![bandicam 2020-02-17 14-26-13-495](https://user-images.githubusercontent.com/27898520/74641604-65e88100-5193-11ea-9801-3ec50c447bed.jpg)

**Comment by johnkslg** [comment]
@olegshegai when deleting work from a work party, detect if there's no more work left, then delete the workparty too.
