### ISSUE TITLE
[0.9.0 staging-1402] Work party: need correct list in economy viewer

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14746]
It looks like this right now (you cant open work party from there too, should be able to)
![bandicam 2020-02-14 14-38-30-938](https://user-images.githubusercontent.com/27898520/74520005-9385be00-4f38-11ea-969b-60d3f7132720.jpg)
![bandicam 2020-02-14 14-38-36-206](https://user-images.githubusercontent.com/27898520/74520008-954f8180-4f38-11ea-870b-2d9dbee55822.jpg)

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/74567754-5535d200-4f2b-11ea-9a20-b461f4cd9bb3.png)
