### ISSUE TITLE
[0.9.0 staging-1402] Work party: empty OKbox

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14748]
1. Make three orders
2. Start to create workparty
3. Press "+" in Work table, submit.
You will see an empty OKbox
![bandicam 2020-02-14 15-07-35-989](https://user-images.githubusercontent.com/27898520/74521864-f2990200-4f3b-11ea-8539-2bb44cd58717.jpg)

**Comment by johnkslg** [comment]
oh goodness

**Comment by johnkslg** [comment]
Fixed
