### ISSUE TITLE
Voice chat not work for some players after a time, before game restart.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14753]
So far I have received several messages that this is happening, (licensed game), voice chat "just stops working".
I will supplement the ticket with log files when I "catch" a player with a fresh bug.

**Comment by SlayksWood** [comment]
game version?

**Comment by elfl0rd** [comment]
latest, report from admins of different servers.
after game relaunch chat work again.

**Comment by SlayksWood** [comment]
merged to #13588
