### ISSUE TITLE
mods -> registrar.cs contain not all data

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14769]
Only registrar.cs can be found in mods folder.
But this file isnt contain room req data.
It looks like some data "hardcoded"

It's ok?

Maybe some another files have same issue.

Actual for 0.8 and 0.9

**Comment by WeaselDog** [comment]
Thanks for catching this. Some of the economy objects have their room requirements in different files. We can fix this at some point to make life easier for modders.

**Comment by elfl0rd** [comment]
> Some of the economy objects have their room requirements in different files

Yes, some. But not registrar.
Or can you explain what file contain this data?

**Comment by WeaselDog** [comment]
I meant to say some of the data is embedded into the object components, in this case the Registrar component. We can change this so it appears in the Mods folder.

**Comment by elfl0rd** [comment]
same for PoweredCartObject

**Comment by WeaselDog** [comment]
@elfl0rd Powered cart seems to be fine. Is this still an issue?

**Comment by elfl0rd** [comment]
@WeaselDog yes, now "poweredcart.cs" contain PoweredCartObject too.

**Comment by WeaselDog** [comment]
Going to mark this as fixed because we fixed the hard-coded issues. Vehicles will likely get refactored but the files are available to modders.

**Comment by elfl0rd** [comment]
hmm, registrar still not appear.

**Comment by WeaselDog** [comment]
@elfl0rd Can you double check? The PR that fixed missed the Steam build for that day but should be fixed now.

**Comment by elfl0rd** [comment]
yep, fine now
