### ISSUE TITLE
0.9 after plugins, .cs files still contain obsolete data

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14768]
talents, skill lvl, etc.

**Comment by mirasrael** [comment]
@elfl0rd What do you mean exactly? Can you provide some samples.

**Comment by elfl0rd** [comment]
>             this.Ingredients = new CraftingElement[]
>             {
>                 new CraftingElement<BrickItem>(typeof(SmeltingSkill), 20, SmeltingSkill.MultiplicativeStrategy, typeof(SmeltingLavishResourcesTalent)),
>                 new CraftingElement<IronPlateItem>(typeof(SmeltingSkill), 30, SmeltingSkill.MultiplicativeStrategy, typeof(SmeltingLavishResourcesTalent)),
>                 new CraftingElement<ScrewsItem>(typeof(SmeltingSkill), 30, SmeltingSkill.MultiplicativeStrategy, typeof(SmeltingLavishResourcesTalent)),
>                 new CraftingElement<IronPipeItem>(typeof(SmeltingSkill), 20, SmeltingSkill.MultiplicativeStrategy, typeof(SmeltingLavishResourcesTalent)),          
>             };
>             this.ExperienceOnCraft = 20;  
>             this.CraftMinutes = CreateCraftTimeValue(typeof(BlastFurnaceRecipe), Item.Get<BlastFurnaceItem>().UILink(), 60, typeof(SmeltingSkill), typeof(SmeltingFocusedSpeedTalent), typeof(SmeltingParallelSpeedTalent));    
>             this.Initialize(Localizer.DoStr("Blast Furnace"), typeof(BlastFurnaceRecipe));
>             CraftingComponent.AddRecipe(typeof(AssemblyLineObject), this);

**Comment by Sekor2600** [comment]
LavishResourcesTalent etc?
They have function in 9.0

**Comment by mirasrael** [comment]
1. Skills used by modules to determine if module should be applied to this ingredient. I.e. Mining module will only reduce ingredients with MiningSkill.
2. Talents still in effect. We don't plant to change them in 9.0. They will be applied from **order owner**. It is a small benefit for leveled professions who makes orders by their own.

**Comment by elfl0rd** [comment]
What about **SmeltingSkill.MultiplicativeStrategy** ?

**Comment by mirasrael** [comment]
Yes, it isn't used anymore and may be removed.

**Comment by IcedForge** [comment]
Will close this as with changes to the templating in 9.4 this is obsolete and has been fixed.
