### ISSUE TITLE
[0.9.0 staging-1403] can´t find storages

### ISSUE THREAD

**Issue by FalkosTMB** [StrangeLoopGames/EcoIssues#14762]
![workbench](https://user-images.githubusercontent.com/43608607/74586562-18301500-4fe9-11ea-8779-c52753202c7a.jpg)
here is all ok
![tent](https://user-images.githubusercontent.com/43608607/74586563-267e3100-4fe9-11ea-8864-8f283162b658.jpg)
![campfire](https://user-images.githubusercontent.com/43608607/74586566-2a11b800-4fe9-11ea-91b3-bafb456471f8.jpg)
here not

**Comment by FalkosTMB** [comment]
from the Stockpile the same ... no storages listet

**Comment by Conchipedia** [comment]
All on Same Claim as can be seen from this
![snap6278](https://user-images.githubusercontent.com/29383891/74589773-263d6000-5000-11ea-9817-1dac517b4e7f.png)
![snap6279](https://user-images.githubusercontent.com/29383891/74589774-28072380-5000-11ea-9869-9b7bae42cf4c.png)




Workbench sees ALL Possible Storage as normal, Others Won't
![snap6271](https://user-images.githubusercontent.com/29383891/74589703-710aa800-4fff-11ea-9fda-290318022679.png)
![snap6272](https://user-images.githubusercontent.com/29383891/74589705-72d46b80-4fff-11ea-98a3-424435060277.png)
![snap6273](https://user-images.githubusercontent.com/29383891/74589706-74059880-4fff-11ea-95fe-72c85f0b7d1d.png)
![snap6274](https://user-images.githubusercontent.com/29383891/74589707-7536c580-4fff-11ea-97fa-7807a8d04ee5.png)
![snap6275](https://user-images.githubusercontent.com/29383891/74589709-77008900-4fff-11ea-9990-7e59d55a3e0b.png)

**Comment by Conchipedia** [comment]
Still an issue in [0.9.0 Staging 1404]
Makes Cooking Really Awkward as u have to **Manually** add food to order

**Comment by Conchipedia** [comment]
still the dame in [0.9.0 Staging 1411]
