### ISSUE TITLE
USER ISSUE: Ошибка

### ISSUE THREAD

**Issue by Keksik217** [StrangeLoopGames/EcoIssues#14763]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
При авторизации в игре,выдает ошибку,мол мне нужно обновить аккаунт

**Expected behavior:**
Стабильная игра

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by SlayksWood** [comment]
@Keksik217 
купил?
