### ISSUE TITLE
[0.9.0 staging-1409] Work party: open from economy viewer with name click

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14774]
We should be able to open the party UI with clicking by the name of the party in the Economy Viewer
![bandicam 2020-02-17 14-26-13-495](https://user-images.githubusercontent.com/27898520/74649388-3f314700-51a1-11ea-885a-0209d6469c08.jpg)

**Comment by johnkslg** [comment]
Make name display using MarkedUpName, add LinkText component to text object.
