### ISSUE TITLE
[0.9.0 staging-1409] Distribution station: broken

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14772]
1. Create a distribution items list in a distribution station
2. Apply
3. Nothing happens
Other person doesn't see item list and doesn't have an access to take them.
(Earlier you could see chat message if the list was saved properly) 
Maybe was broken after https://github.com/StrangeLoopGames/Eco/pull/5616

**Comment by olegshegai** [comment]
![image](https://user-images.githubusercontent.com/56091594/74637836-d4214980-517b-11ea-98c4-40d23cc6cd43.png)
Can't reproduce on latest staging. 
The only problem I see is about markers not being removed.

**Comment by beastyn** [comment]
Well.
Then it just doesn't save anything.
And I don't think that saving-in-process is a good Idea. When a marker with a hint will be updated? Every time Im changing something there?
This is what I've done:
![bandicam 2020-02-17 16-47-14-880](https://user-images.githubusercontent.com/27898520/74651236-2e82d000-51a5-11ea-8de4-a9929a22eaff.jpg)
![bandicam 2020-02-17 16-47-12-896](https://user-images.githubusercontent.com/27898520/74651239-2fb3fd00-51a5-11ea-91aa-5353ea08f456.jpg)

This is what other person sees:
![unknown (58)](https://user-images.githubusercontent.com/27898520/74651349-70ac1180-51a5-11ea-9438-68570354801c.png)
