### ISSUE TITLE
[0.9.0 staging-1409] Transfer window with empty fields

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14776]
Bank accounts are empty
![bandicam 2020-02-17 17-00-38-696](https://user-images.githubusercontent.com/27898520/74652070-0eeca700-51a7-11ea-95a6-b59689727592.jpg)

**Comment by serpopov** [comment]
![image](https://user-images.githubusercontent.com/4238643/75585550-f2a11200-5aa4-11ea-8a3a-baeb306e3c3d.png)
