### ISSUE TITLE
[0.9.0 staging-1413] Blast Furnace lost pipes info

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14783]
In the Pipes component there is only smog now
![bandicam 2020-02-18 14-18-27-681](https://user-images.githubusercontent.com/27898520/74721656-8da21c80-5259-11ea-9236-c81e7625c9c0.jpg)

**Comment by WeaselDog** [comment]
Related: https://github.com/StrangeLoopGames/EcoIssues/issues/14767
Like this as well: https://github.com/StrangeLoopGames/EcoIssues/issues/14762
