### ISSUE TITLE
USER ISSUE: Fail to log in while logged into Steam

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#14786]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Log In
2. Fail

**Expected behavior:**
Logged in successfully

**Actual behavior:**
Error parsing voice login reponse

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods

**Comment by redwyre** [comment]
Are you getting this as a pop up dialog?

**Comment by beastyn** [comment]
Pleasr, provide a log file.
Instruction is here  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
