### ISSUE TITLE
Hosted Worlds Feedback round 2

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14780]
![image](https://user-images.githubusercontent.com/3536496/74695160-ced9f400-51a7-11ea-8409-cac083c7628d.png)
- [x] Make this fade in, the bounce-lerp I'm not a fan of

![image](https://user-images.githubusercontent.com/3536496/74695210-02b51980-51a8-11ea-939e-1a3ce206381e.png)
- [x] Bottom right number cut off

![image](https://user-images.githubusercontent.com/3536496/74695271-398b2f80-51a8-11ea-9994-5cfebc2ff241.png)
- [x] We'll need to hide this option from the menu till its ready

![image](https://user-images.githubusercontent.com/3536496/74695312-68a1a100-51a8-11ea-9160-b409a2ed92cd.png)
- [x] Can these be navigation items up top?  I would add like this diagram:
![image](https://user-images.githubusercontent.com/3536496/74695442-dd74db00-51a8-11ea-9029-01b03204a3e4.png)

- [x] I upgraded my account to have 4 worlds. When I went to the My Worlds page, I only saw 1.  It should have a big 'Processing changes, please wait' notice there, and auto-refresh when it's finished processing. 

![image](https://user-images.githubusercontent.com/3536496/74695527-22990d00-51a9-11ea-8991-98d3829977a6.png)

- [x] I clicked pause and hit refresh. Pause was no longer toggled after refresh.

- [x] Worlds that are loading should display a 'Loading' notice when the world image is missing.

- [ ] World image needs to have water in it. Please drive this issue forward even though it's not in your area of the code.  

![image](https://user-images.githubusercontent.com/3536496/74695673-a7842680-51a9-11ea-86e2-9864021e76d7.png)
- [x] Immediately after subscribing I was taken to this page. It doesn't seem to be a page I can navigate to any other way, and seems to be a duplicate of the Subscription Management page fuctionality.  In any case, I should be taken directly to My Worlds. I suggest removing this page in the image, as it seems to use the old style of specifying worlds to remove.

**Comment by denysaw** [comment]
`Can these be navigation items up top? I would add like this diagram`
Here I made only Logo URL, cuzz as Jeff said other gonna be discussed more.

**Comment by johnkslg** [comment]
looking good! will make a new bug
