### ISSUE TITLE
Make Elevator Prefab not trigger Unity rebuilds all the time

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14788]
@keegan-o can you add repro steps

**Comment by keegan-o** [comment]
Sorry, this still happens to me but I have no idea how to repro it on another computer. It's not a big issue, and throughout dev history what usually happens is in different builds of unity over time it's different random assets that it happens with. I think for now this doesn't need to be an issue here, as it's just a few seconds delay.
