### ISSUE TITLE
Performance: Minimap rendering

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14789]
- [x] Compare performance for GPU for different LOD levels (before and after)
- [x] Compare performance for CPU for different LOD levels (before and after)
- [x] Compare visual appearance for different LOD levels (before and after)

**Comment by mirasrael** [comment]
# Max level, right bottom angle
## Before (), FPS ~20:
![image](https://user-images.githubusercontent.com/475445/83133079-fe739300-a0ea-11ea-9605-81289971524a.png)

### GPU profile (total render time 62.55ms, color 11.92, shadows 6.29, water 44.28ms):
![image](https://user-images.githubusercontent.com/475445/83134124-8efea300-a0ec-11ea-9b17-ebc58cbc70b5.png)
![image](https://user-images.githubusercontent.com/475445/83134288-ccfbc700-a0ec-11ea-812c-51336715de51.png)

## After, FPS ~70:
![image](https://user-images.githubusercontent.com/475445/83133183-2531c980-a0eb-11ea-8948-9bf1156af055.png)

### GPU profile (total minimap render time 0.42ms, color 0.23, shadows 0.07, water is in color):
![image](https://user-images.githubusercontent.com/475445/83133920-3f1fdc00-a0ec-11ea-8f50-0b808db0cc89.png)
![image](https://user-images.githubusercontent.com/475445/83133937-4646ea00-a0ec-11ea-9eac-d8d0ce20322c.png)

**Comment by mirasrael** [comment]
# Min level, right bottom angle
## Before, FPS ~57:
![image](https://user-images.githubusercontent.com/475445/83134568-3a0f5c80-a0ed-11ea-9cea-ca5ca4e42a3a.png)

### GPU profile (total render time 7.75ms, color 1.34, shadows 0.88, water 5.47ms):
![image](https://user-images.githubusercontent.com/475445/83134804-91adc800-a0ed-11ea-84cf-3210512a7cb2.png)

## After, FPS ~70-75:
![image](https://user-images.githubusercontent.com/475445/83134862-a4280180-a0ed-11ea-9b17-a8e1ba207b63.png)

### GPU profile (total minimap render time 0.15ms, color 0.06, shadows 0.04, water is in color):

![image](https://user-images.githubusercontent.com/475445/83135098-097bf280-a0ee-11ea-858e-b0cb4fc257f2.png)

**Comment by mirasrael** [comment]
# Full screen map, max details:

## Before, FPS ~24:

![image](https://user-images.githubusercontent.com/475445/83135252-392afa80-a0ee-11ea-82de-8e4ea832f299.png)

### GPU profile (total render time 39.36ms, color 14.02, shadows 5.04, water 25.34ms):

![image](https://user-images.githubusercontent.com/475445/83135797-0f260800-a0ef-11ea-9963-e503c16617af.png)

## After, FPS ~120:

![image](https://user-images.githubusercontent.com/475445/83135316-5364d880-a0ee-11ea-8571-773ed3fb78f9.png)

### GPU profile (total minimap render time 3.64ms, color 1.67, shadows 0.92, water is in color):

![image](https://user-images.githubusercontent.com/475445/83135614-bbb3ba00-a0ee-11ea-85d1-1fd9bab88829.png)

**Comment by mirasrael** [comment]
# Full screen map, min details:

## Before, FPS ~117:

![image](https://user-images.githubusercontent.com/475445/83135976-5c09de80-a0ef-11ea-8f97-63e7883a9943.png)

### GPU profile (total render time 4.49ms, color 0.77, shadows 0.77, water 2.48ms):

![image](https://user-images.githubusercontent.com/475445/83136373-08e45b80-a0f0-11ea-9212-3ab683a9049c.png)

## After, FPS ~117 (more details for new minimap):

![image](https://user-images.githubusercontent.com/475445/83136413-1d285880-a0f0-11ea-8b47-6cb7a90166ba.png)

### GPU profile (total minimap render time 3.6ms, color 1.65, shadows 0.92, water is in color):

![image](https://user-images.githubusercontent.com/475445/83136765-b3f51500-a0f0-11ea-9265-0295c551a6d3.png)

**Comment by mirasrael** [comment]
# Summary:

New minimap has significantly better performance. It is almost free for CPU, Camera.Render almost same for both versions and only insignificantly varies. 
It especially boost performance for high level details and even with high level details it works faster than the current low settings minimap. Also for low minimap level it has significantly more details than the old minimap with better performance. 
Also in the right bottom corner mode it renders in less than 0.5ms on GPU even it high level details mode and less than 0.2ms in low details mode.
