### ISSUE TITLE
[0.9.0 staging-1416] Reseaching typo/flaws.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14794]
- [x] 1. Reduce Labor for Carpentry/Masonry/Farming Skill Book recipes to 500 Labor.

- [x] 2. Reduce Labor from 5000 to 4000; 15000 to 10000. We haven't any benefit for this recipes and Now it's really a lot, need to reduce for playtest. 

- [x] 3. Carpentry Skill Book recipe: delete Basic Research. SHould be 3 Dendrology RP Basic:
![image](https://user-images.githubusercontent.com/45708377/74912156-21492980-53cf-11ea-8a4e-41eff9c0ef4c.png)

- [x] 4. Change requires for Baking and Cooking. They both should have same requires. I prefer Farming for it.

- [x] 5. Mechanics Skill Book recipe: Should be 10x Engineering Research Paper Basic:
![image](https://user-images.githubusercontent.com/45708377/74914136-f365e400-53d2-11ea-8b10-a509289457f1.png)
recipe: Basic Research,20;Advanced Research,5; EngineeringResearchPaperBasic,10; EngineeringResearchPaperAdvanced,5; MetallurgyResearchPaperAdvanced,10.

- [x] 6. Need change recipes for:
- AgricultureResearchPaperAdvanced
- AgricultureResearchPaperModern
- CulinaryResearchPaperAdvanced
- CulinaryResearchPaperModern
- DendrologyResearchPaperAdvanced
- DendrologyResearchPaperBasic
- EngineeringResearchPaperModern. Craft table to Assembly line.
- EngineeringResearchPaperAdvanced. Craft table to Wainwright table.
- GatheringResearchPaperBasic
- GeologyResearchPaperAdvanced
- GeologyResearchPaperBasic
- GeologyResearchPaperModern
- MetallurgyResearchPaperAdvanced
- MetallurgyResearchPaperBasic
![image](https://user-images.githubusercontent.com/45708377/74918265-e3053780-53d9-11ea-952b-2b2c21369be0.png)

These are almost all recipes for research papers.

**Comment by WeaselDog** [comment]
Most of the recipe costs will be redone. Everything is too expensive now

**Comment by SlayksWood** [comment]
@WeaselDog 
We can always recalculate it, but now we have wrong ingredient.

**Comment by elfl0rd** [comment]
in addition, "bottleneck" in culinary researches.
you need bakery 1 for creating culinary research paper advanced.
It gets even weirder when I look at a recipe that requires salad as an ingredient.

but for bakery, you need culinary research paper advanced...

Only one way, craft "culinary research paper advanced meat".

Are you sure it's not a mistake?

**Comment by WeaselDog** [comment]
@SlayksWood Looks good. I see what you mean now.

**Comment by SlayksWood** [comment]
moved discussion to https://github.com/StrangeLoopGames/Eco/issues/5675
