### ISSUE TITLE
[0.9.0 staging-1416] Civics: losing persistent data

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14796]
1. Place a government office
2. Create a title
![bandicam 2020-02-20 15-14-36-865](https://user-images.githubusercontent.com/27898520/74924386-2b315380-53f4-11ea-8a6d-bbcf99ad31f7.jpg)
3. Pickup  government office
4. Title was missed.  
![bandicam 2020-02-20 15-16-14-946](https://user-images.githubusercontent.com/27898520/74924397-35535200-53f4-11ea-921f-096cb72b0eef.jpg)
![bandicam 2020-02-20 15-16-52-506](https://user-images.githubusercontent.com/27898520/74924405-38e6d900-53f4-11ea-867b-0d42e659e263.jpg)

As I remeber, we've made persistent data for all the civics objects already?

**Comment by olegshegai** [comment]
[**Here**](https://drive.google.com/open?id=1aL2z-Cib0ivmD-s6WjZiQychkGwEWl-0) is a video from https://github.com/StrangeLoopGames/Eco/pull/5615 updated to latest staging.
The latest staging itself is pretty much the same. Differences fixed in the mentioned PR.

**Comment by beastyn** [comment]
There is a problem.
The data on the civics objects should be properly stored with picking. And ve vack with placement.
Its not now.
Like here
https://drive.google.com/file/d/1WQJ1QNlOwnRHbYLNla0wOpnesd8ycSv6/view?usp=sharing

**Comment by beastyn** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4243391/Player.log)
