### ISSUE TITLE
[0.9.0 staging-1416] Civics: picking capitol will break it

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14795]
1. Place capitol
2. Ratify.
3. Everything seems to be fine
4. Pikup capitol and place it again
5. Consitution tab is empty, capitol is still counting as picked.
![bandicam 2020-02-20 14-41-38-802](https://user-images.githubusercontent.com/27898520/74921167-30d86a80-53ef-11ea-944a-dd4011df379d.jpg)
![bandicam 2020-02-20 14-41-50-611](https://user-images.githubusercontent.com/27898520/74921300-6b420780-53ef-11ea-8bf1-49c97d8b651b.jpg)

6. Try to pickup it with hammer and got the server error
![bandicam 2020-02-20 14-42-01-793](https://user-images.githubusercontent.com/27898520/74921178-35048800-53ef-11ea-973e-67e9701a5f23.jpg)

For the first time it was tested, after placing a capitol owner of the deed was changed. But it looks like the problem will occur wvwn if property owner stays the same.
UPD: yeah, you don't even need to Ratify. picking up will break capitol anyway.

**Comment by beastyn** [comment]
Still the same error, and the same problem.
Also I see that whem Im picking a capitol the doubled item is appearing in my toolbar
I had only one capitol at the beggining
![bandicam 2020-02-24 11-42-51-236](https://user-images.githubusercontent.com/27898520/75133011-ead71b80-56fa-11ea-8504-b2636f733545.jpg)

**Comment by beastyn** [comment]
s,miting with devtool will crash server
![Uploading unknown (52).png…]()

[crash (3).txt](https://github.com/StrangeLoopGames/EcoIssues/files/4265315/crash.3.txt)

**Comment by mirasrael** [comment]
Seems the issue only happens when Capitol spawned with command (like /spawn capitol). I didn't have such problem when manually created Capitol (after /give Capitol).

**Comment by SlayksWood** [comment]
nope, place capitol, pick up, place again and you have this bug.
