### ISSUE TITLE
Workbench crafting tab is not invalid when not placed on solid ground

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14799]
![image](https://user-images.githubusercontent.com/3536496/74964884-12f80f00-53c9-11ea-9b7a-e41260971712.png)

Should be disabled and tinted red

**Comment by mirasrael** [comment]
Not sure if it is good, because some players may want to check recipes on non-working table. It may be easily disabled with 
[WorldObjectUIPanel("Crafting", ComponentPriorities.Crafting, **, InactiveWhenDisabled = true**)]
but I didn't do it at first place for usability reasons.

**Comment by SlayksWood** [comment]
@johnkslg 
Could it be closed?

**Comment by johnkslg** [comment]
Ok thats fine
