### ISSUE TITLE
0.9 tonns of useless crushed stone

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14793]
After changes, we cannot more grind crushed sandstone|granite into sand.
Only (not crushed) sandstone|granite can be grinded.
What exactly is the intended use for crushed sandstone?
Roads? Cement? It's totally after a lot of time after first smelting.

As i think we need something like
Arrastra
Grind stone|ore = grinded sandstone, grinded granite
Masonry Table
Process sand - (from crushed sandstone or stone)
Grind stone (granite or sandstone) x5 longer and req more labor than arrastra.

**Comment by SlayksWood** [comment]
![Uploading image.png…]()
