### ISSUE TITLE
[0.9.0 staging-1418] Hard to read Block name

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14803]
Scaling set to 100%. 
![image](https://user-images.githubusercontent.com/45708377/75013715-e5c56280-5495-11ea-9c54-4920416724d1.png)
I always play with 80% and it's very hard. It’s also very difficult to imagine how it will look in any other languages.

**Comment by SlayksWood** [comment]
Cropped titles look ugly:
![image](https://user-images.githubusercontent.com/45708377/94011004-60998780-fdaf-11ea-930c-bd904786fa70.png)
@keegan-o @MilenkoTunjic 
We have tooltip so can we delete it at all?

**Comment by johnkslg** [comment]
Yes lets remove the names
