### ISSUE TITLE
Improvement for /qa allconstructed

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14804]
Hard to check block, beecause we have a lot of new blocks and not enough space for this command in small worlds.
Need more space between blocks and maybe make it like a spiral.
![image](https://user-images.githubusercontent.com/45708377/75014963-93d20c00-5498-11ea-9e38-b6d2aa34eac4.png)

**Comment by SlayksWood** [comment]
or make ir only for one material. So /qa allcontructed, hewnlog; /qa allcontructed, hardwoodhewnlog and etc.

**Comment by tuha263** [comment]
it will be:  /qa allcontructed hewnlog (without ",")

**Comment by SlayksWood** [comment]
- [ ] 1. Still don't enough space for tier4 material:
it takes 15 blocks to check one block type if block doesn't rotate, and 60 blocks for rotated blocks:
![image](https://user-images.githubusercontent.com/45708377/94004630-ab160680-fda5-11ea-9ae6-250db0890a7f.png)
Take, for example composite lumber: it has 47 block types, and 28 of them are rotating. So I need to have at least (47-28)x15+28x60 = 1965 Blocks, so I need to create 4km² world. Not very convenient and this number will increase over time

- [ ] 2. /qa allconstructed Hewn Log doesn't work, but if I use /qa allconstructed HewnLog it spawn softwood and hardwood hewn logs too:
![image](https://user-images.githubusercontent.com/45708377/94006193-25e02100-fda8-11ea-9e2c-228cf4a7856d.png)
