### ISSUE TITLE
[0.9.0 staging-1417] Triangle textures

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14801]
![unknown (60)](https://user-images.githubusercontent.com/27898520/75008539-18715a00-549a-11ea-9800-7b08eca201b6.png)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/78024695-7b8bc180-7361-11ea-9396-c330b04f95e5.png)
