### ISSUE TITLE
[0.9.0 staging-1418] Wrong Aqueduct icon

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14805]
Aqueduct icon has brick color, but it should have gray color like another Basic blocks.
![image](https://user-images.githubusercontent.com/45708377/75015733-60907c80-549a-11ea-9f7e-4155e0b99c59.png)
All other block icons has form like this block, but Aqueduct hasn't.

**Comment by keegan-o** [comment]
@RobertMangano Lets get a new icon for the 'Aqueduct' building form! This is one that will likely be added to ashlar stone and such as well.
