### ISSUE TITLE
[0.9.0 staging-1418] Dev tool remove restriction for carried items

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14802]
Step to reproduce:
- take dev tool. RMB at it:
![image](https://user-images.githubusercontent.com/45708377/75008330-d68be800-5488-11ea-8efe-5f031baf7fb2.png)
- select several blocks:
![image](https://user-images.githubusercontent.com/45708377/75008349-e0ade680-5488-11ea-8ce3-8ad2df8e3aa2.png)
- submit
- take pickaxe and start mine and pick up stones. I have stones at my toolbar:
![image](https://user-images.githubusercontent.com/45708377/75008506-400bf680-5489-11ea-916c-16f3f11096c8.png)
- Also can break weight if you add more than you can carry blocks at toolbar (for example add all composite blocks)
![image](https://user-images.githubusercontent.com/45708377/75008590-7d708400-5489-11ea-9c6e-83d33cadbac0.png)

**Comment by elfl0rd** [comment]
Intended? https://github.com/StrangeLoopGames/Eco/pull/5657

**Comment by johnkslg** [comment]
Intended. You can disable it by /carryall false
