### ISSUE TITLE
[0.9.0 staging-1418] Change access to commands /preset food and /preset economy

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14807]
They should be developer commands:
![image](https://user-images.githubusercontent.com/45708377/75031116-98a5b880-54b6-11ea-8233-713ea1d737c5.png)

**Comment by beastyn** [comment]
![bandicam 2020-03-31 17-10-47-720](https://user-images.githubusercontent.com/27898520/78024961-a92d3680-7372-11ea-83f8-03f295d92f90.jpg)
![bandicam 2020-03-31 17-10-50-682](https://user-images.githubusercontent.com/27898520/78024965-aaf6fa00-7372-11ea-86f4-0dc185c16226.jpg)
