### ISSUE TITLE
Server error on placing a 'Large Hanging Redwood Sign'

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14800]
![image](https://user-images.githubusercontent.com/14983165/74971302-ba2e7380-53d4-11ea-8982-f561b836e46a.png)
On 9.0 Staging @ 2/20/2020 11:33AM.

**Comment by Quadbro** [comment]
@keegan-o 
"World object has components that need persistent data, but item does not inherit from IPersistentData."

**Comment by Quadbro** [comment]
So the erros is:
""World object has components that need persistent data, but item does not inherit from IPersistentData."

@Sekor2600 Can you help me with that?
All signs require such derived stuff
![image](https://user-images.githubusercontent.com/6802030/75010256-4b721880-54af-11ea-80f2-d2700bda68e1.png)
