### ISSUE TITLE
[0.9.0 staging-1418] Hard to build with Slope Blocks

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14806]
If you have hammer in you hands It's very hard to find point to build block near slopeBlocks:
![image](https://user-images.githubusercontent.com/45708377/75016759-c120b900-549c-11ea-82d4-dc7e02dc5359.png)

But if you take Dev tool in hads you can see whu it happens, because it tries to place block in wrong position: 
![image](https://user-images.githubusercontent.com/45708377/75016562-55d6e700-549c-11ea-9ee7-2e323aeb93ff.png)
![image](https://user-images.githubusercontent.com/45708377/75016573-5c655e80-549c-11ea-9506-4dfe48a8ed2e.png)

**Comment by keegan-o** [comment]
These blocks as of this morning are all deprecated and no longer exist-- in their place we have slope blocks that have bottoms, and upside down slope blocks which can be placed manually to make undersides of slopes. We also have new roof blocks. I think I will close this issue, but if building with the new blocks is also hard, it could be re-opened, or a new more accurate issue could be made.

**Comment by SlayksWood** [comment]
The blocks have changed. The problem remains.
Stairs, Basic Slope, new Roof block and i think many else.

**Comment by elfl0rd** [comment]
> These blocks as of this morning are all deprecated and no longer exist-- in their place we have slope blocks that have bottoms, and upside down slope blocks which can be placed manually to make undersides of slopes. We also have new roof blocks. I think I will close this issue, but if building with the new blocks is also hard, it could be re-opened, or a new more accurate issue could be made.

This is very bad, as thin blocks provided the opportunity to build beautiful buildings without visual overload.

**Comment by elfl0rd** [comment]
Totally dislike new roof.
![изображение](https://user-images.githubusercontent.com/4980243/79767329-db0e3900-8331-11ea-8c2b-046dbe322544.png)

just look at "thin"
![KQU33sAtnWo](https://user-images.githubusercontent.com/4980243/79767344-dfd2ed00-8331-11ea-85ec-f3120c7368c8.jpg)

**Comment by WiseProjects** [comment]
Agree with Dragon - replacement is ugly. IMHO hard to place doesnt mean impossible so no reason to remove it...
