### ISSUE TITLE
[0.9.0 staging-1418] Rooms: can't detect doubled ashlar doors

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14808]
Room with doubled composite doors is detected fine.
But new ashlar doors don't want to wark in pair.
![bandicam 2020-02-21 16-57-18-281](https://user-images.githubusercontent.com/27898520/75034101-45d7fb00-54ce-11ea-9f96-a16eb5e36d5f.jpg)
![bandicam 2020-02-21 16-51-55-326](https://user-images.githubusercontent.com/27898520/75034102-46709180-54ce-11ea-8578-ad6e5ca449cd.jpg)

**Comment by keegan-o** [comment]
I'm not seeing anything wrong in the prefab, which was copied from the composite lumber doors. @Sekor2600 @WeaselDog Anything in the tech tree regarding worldobjectblock occupancy things? Might also be a regular occupancy problem.

**Comment by WeaselDog** [comment]
They look to be identical in the tech tree. There was an issue with normal Ashlar Stone Door not functioning as a door, but that is fixed now and does not affect Ashlar Limestone Door. I will keep looking into it to see if I can spot any differences

**Comment by beastyn** [comment]
@WeaselDog from Den also

The first lumber doors you can craft don't work.

**Comment by keegan-o** [comment]
If things are identical in the prefab and tech tree then we will need someone looking into it in code. @StanKryvenko can help!

**Comment by WeaselDog** [comment]
It looks like we do have a fix in the tech tree. Will get it in soon.

**Comment by WeaselDog** [comment]
@keegan-o So the fix went through and it turns out it was a combination of occupancy and tech tree.

Here is what it looks like now:
![AshlarStoneDoor](https://user-images.githubusercontent.com/47330823/75739541-f659b200-5cb9-11ea-9fd1-c4ec0c1b879f.png)
