### ISSUE TITLE
0.9 staging-1415 screening machine cannot concentrate gold and copper

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14817]
only iron

**Comment by Sekor2600** [comment]
Yes, that's the way it should be

**Comment by WeaselDog** [comment]
Thanks for posting this. It is intentional that it only concentrates iron, but we will make this more clear through descriptions and other methods.

**Comment by elfl0rd** [comment]
Okay, i agree your position about effecience.
But...
Maybe you just add reciepes?
e.g.
screening and rocker have copper\gold reciepe with same effeciency
and Froth Cell+Sensorbelt too.
In current behavior you need to use two machines at one time, screening+rocker and Froth Cell+Sensorbelt
