### ISSUE TITLE
CW auto update not working

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#14812]
In build release, it should be uploading to hosted worlds. and then calling api to auto update hosted worlds.
This was working, but 8.3.3 did not upload.

**Comment by jaskes** [comment]
<img width="494" alt="1" src="https://user-images.githubusercontent.com/748590/75181799-16382580-5750-11ea-9576-1382591da63c.png">

8.3.3 should be available now. Let me know if you need any HW instances updated to that version.

**Comment by johnkslg** [comment]
Can we also get a way to easily have staging servers in there? For testing

**Comment by j3fffff** [comment]
auto update not working
