### ISSUE TITLE
Balance : 0.9 staging, kitchen workbenches produce too many smog

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14816]
just look... cast iron stove provide 0.8 smog\s
blast furnace produce 1!

as i think it should be like
Cast iron stove - 0.1 SpS
Bakery Oven - 0.1 SpS
Stove - 0.05 SpS

**Comment by WeaselDog** [comment]
Thanks for the catch and the data. Going to bump this up in priority and we will fix it in the next update.
