### ISSUE TITLE
Staging-1415 shadow background still active after interface closing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14811]
![20200222005531_1](https://user-images.githubusercontent.com/4980243/75075118-2f519400-550e-11ea-8b78-0e3c31e41883.jpg)

**Comment by beastyn** [comment]
didn'e meet. Can you attach a log file?

**Comment by elfl0rd** [comment]
after 3d? log already owerwrited.

**Comment by SlayksWood** [comment]
It can happen if you have some lags when you try to close UI, but it's very rarely. You can reproduce it with other player. Step to reproduce:
- 1st player open any craft table:
![image](https://user-images.githubusercontent.com/45708377/78107974-1edee400-73ff-11ea-8514-db09c6c13727.png)
- 2nd player pick up this craft table.
- 1st player have shadow background without UI:
![image](https://user-images.githubusercontent.com/45708377/78108122-6bc2ba80-73ff-11ea-89d3-769d527ba811.png)
