### ISSUE TITLE
USER ISSUE: just a test game

### ISSUE THREAD

**Issue by dalycat** [StrangeLoopGames/EcoIssues#14814]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**
have fun

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by elfl0rd** [comment]
unlicensed copy bugged? oh wait...
