### ISSUE TITLE
Inventory out of sync

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1482]
After playing for a while I started harvesting fireweed and it didn't show up in my backpack until I restarted the game

**Comment by MarjieAVolk** [comment]
Actually, think this is related to StrangeLoopGames/EcoIssues#1503?  Maybe our server was just messed up?

**Comment by SeanAtr0n** [comment]
IIRC at the time crafting was working fine, the server stayed up for a few hours after this... i restarted the client
