### ISSUE TITLE
[0.9.0-1415] Uncorrect decrease weight

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#14824]
If you start craft from transport, then the weight occupied by this item will increase:
Before cradfting:
![изображение](https://user-images.githubusercontent.com/13696708/75110437-35935d80-563f-11ea-9f3d-b03b3b47b3f2.png)
During crafting:
![изображение](https://user-images.githubusercontent.com/13696708/75110452-5d82c100-563f-11ea-8a83-fc1376e0b1e4.png)
After crafting:
![изображение](https://user-images.githubusercontent.com/13696708/75110551-7e97e180-5640-11ea-9271-a4af1390d84b.png)

**Comment by Astrija** [comment]
Finished:
![изображение](https://user-images.githubusercontent.com/13696708/75110615-58267600-5641-11ea-9d22-3d6884f9d999.png)

second mistake: when the fence is in, he continues to reserve the weight in the cart and after the crafting he performs an action with the weight, which is uncorrect, first you need to subtract and then start crafting

**Comment by mirasrael** [comment]
@johnkslg seems related to craft. While you are there.

**Comment by Sekor2600** [comment]
Same Problem is in Backpack 
![grafik](https://user-images.githubusercontent.com/37456949/75375812-29bdca80-58cf-11ea-9139-fdf2f1774e52.png)
