### ISSUE TITLE
0.9 beet greens lost from craft.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14826]
as i see, all salads (excl campfire one) not use it.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/75137786-954e3f00-56f9-11ea-90be-465a26a93782.png)
![image](https://user-images.githubusercontent.com/45708377/75137791-98e1c600-56f9-11ea-9e45-6c3770c374bf.png)
![image](https://user-images.githubusercontent.com/45708377/75137814-ad25c300-56f9-11ea-8ab6-1041d0bd5506.png)

**Comment by elfl0rd** [comment]
i said it, for me - using only in campfire, is bad.

**Comment by WeaselDog** [comment]
This is a great point but it requires a pretty significant re-balance of salads. This is something we want to do so will include it in the Chef re-balance we have planned

**Comment by WeaselDog** [comment]
Beet Greens has been changed in 9.5 so it is only used as a tagged ingredient.
