### ISSUE TITLE
0.9 Typo? "Pirozhoki"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14827]
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#171241
![изображение](https://user-images.githubusercontent.com/4980243/75115954-b28cfa00-5674-11ea-9b48-658463bb649e.png)
as i think only "pirozhki" ok

**Comment by SlayksWood** [comment]
pirozhok
pluralform - pirozhki

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/75220500-a0b07180-57b0-11ea-9f90-f59cc7b40029.png)
