### ISSUE TITLE
[0.9.0 staging-1421] Rename all scythe to sickle except modern scythe

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14836]
Now they are same. For me Steel sickle should be faster and without AoE.

**Comment by keegan-o** [comment]
There should be no steel scythe for now, only a steel sickle... do you mean the modern scythe?

**Comment by SlayksWood** [comment]
We have both now with same model, same icon, same functional.
![image](https://user-images.githubusercontent.com/45708377/75184594-b17fc980-5755-11ea-9340-da4c9c5eb0f3.png)
![image](https://user-images.githubusercontent.com/45708377/75184604-b47aba00-5755-11ea-8275-62f59666f9c1.png)

**Comment by keegan-o** [comment]
Yep, steel scythe should be removed since the object is a sickle. (the old naming was wrong)

**Comment by WeaselDog** [comment]
Going to add myself as this requires tech tree changes
