### ISSUE TITLE
[0.9.0-1415] remove Farming and Fertilized Upgrade

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#14832]
Can't insert modules Farming Upgrade and Fertilized Upgrade in Farmers Table, because not accept this.
![изображение](https://user-images.githubusercontent.com/13696708/75130075-6c1fb580-56dd-11ea-8f46-652f1a4e8156.png)

**Comment by WeaselDog** [comment]
Thanks so much for the catch. It will be fixed in the next update.
