### ISSUE TITLE
Stacking Deeds disconnect

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1483]
I created 2 land deeds then dropped one on top of the other (intending to swap positions), didn't see an exception but eventually got disconnected due to inactivity

**Comment by SeanAtr0n** [comment]
can't reconnect after doing this... no error msgs appear

**Comment by SeanAtr0n** [comment]
Thread was stuck w/ maxToMove=0 minToMove=1 reverting Marjie's change in InventoryChangeSet that set minToMove=1 fixes the issue but I'm not sure why that change was made so reassigning.

**Comment by MarjieAVolk** [comment]
Hmmm Yeah it seems setting minToMove = 1 didn't have the effect I wanted (but setting it back to 0 fixes the crash but still doesn't allow swapping those stacks, it just does nothing).  I'll have it swap stacks if it finishes the loop and finds minToMove is 0.
