### ISSUE TITLE
latest notification is cut off

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14831]
![image](https://user-images.githubusercontent.com/3536496/75119570-eb0ee280-5638-11ea-8b85-01d6e4e63537.png)
you can just see the top of the text.

**Comment by beastyn** [comment]
Still here
![bandicam 2020-02-26 13-41-28-411](https://user-images.githubusercontent.com/27898520/75327215-ccf5ec00-589d-11ea-86e1-8495e288c1a6.jpg)

**Comment by SlayksWood** [comment]
I hope it's fixed. Can't reproduce now, but I'll check it.
