### ISSUE TITLE
[0.9.0-1415] Butchery Table: any carcass

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#14838]
When you want to make a carcass butchering, 
![изображение](https://user-images.githubusercontent.com/13696708/75135900-0854b700-56f4-11ea-9220-e1902a4abdac.png)

there is no choice to use any suitable carcass, you only need to select a particular carcass.

![изображение](https://user-images.githubusercontent.com/13696708/75135938-228e9500-56f4-11ea-8e96-e95ad1247550.png)

The carcass icon comes out of the blue frame.

The recipe in the main menu and when choosing the type of carcass do not match (there is no fat).
![изображение](https://user-images.githubusercontent.com/13696708/75137054-9ed6a780-56f7-11ea-842f-8547538719e7.png)

**Comment by mirasrael** [comment]
Need default recipe with tagged ingredient.

**Comment by SlayksWood** [comment]
Should give 3
![image](https://user-images.githubusercontent.com/45708377/75145206-8f605a00-5709-11ea-94e2-eae29c6fa730.png)
