### ISSUE TITLE
increase speed drilling and add more blocks

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14839]
@WeaselDog @Sekor2600 
I and not only I assume that we need to increase speed drilling and add more blocks to Iron Rock Drill.
What you think about it?

_Originally posted by @SlayksWood in https://github.com/StrangeLoopGames/EcoIssues/issues/13307#issuecomment-590193337_

**Comment by mirasrael** [comment]
Suggested numbers:
Iron:
Max Range: 5 -> 10
Speed: 0.8 -> 2

Modern:
Max Range: 10 -> 15
Speed: 1.7 -> 3

**Comment by elfl0rd** [comment]
Additional suggestion (maybe after 0.9)
In real life, small "resource" veins can be found outside of deposit.
Maube we can have something like this?
![изображение](https://user-images.githubusercontent.com/4980243/75150081-9b9de480-5714-11ea-806c-8be8d5b1c3eb.png)
red ! mark indicate resource close to this block. (in any of 8 blocks)

p.s.
Prospecting interface should be closed after pressing esc.
