### ISSUE TITLE
0.9 Dropdown list overlap

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14843]
Users and managers
![изображение](https://user-images.githubusercontent.com/4980243/75153503-96449800-571c-11ea-8fec-c68d4ad0b95a.png)

Also menu overlap users.
![изображение](https://user-images.githubusercontent.com/4980243/75153477-8af16c80-571c-11ea-80d6-1e192bbfd90f.png)

**Comment by SlayksWood** [comment]
overlap fixed:
![image](https://user-images.githubusercontent.com/45708377/80100050-139f5400-8578-11ea-971f-4136bca32a06.png)
out of screen in another issue
