### ISSUE TITLE
electronics assembly has ugly and not animated model.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14846]
Also no sound...
![изображение](https://user-images.githubusercontent.com/4980243/75166778-7a012500-5735-11ea-8ec2-e3a67641ed5d.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/79166978-30c76c00-7d9b-11ea-8aa2-5e263b92073e.png)
Fixed!

**Comment by elfl0rd** [comment]
Cool!
