### ISSUE TITLE
[0.9.0 staging-1415] Not open browser when need vote.

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#14840]
After click button "yes" not open browser for voting.
System: 
OS Linux (Ubuntu 19.10)
Proton 5.0-3

![изображение](https://user-images.githubusercontent.com/13696708/75146720-b53b2e00-570c-11ea-8601-5cadce1d1778.png)

**Comment by elfl0rd** [comment]
As side fix... can you add link+token onto this window? With ability to copy it.

**Comment by Astrija** [comment]
Now all work. Close
