### ISSUE TITLE
Ashlar Stone Cubes and Reinforced Concrete Floor Don't connect to Terrain

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14849]
![изображение](https://user-images.githubusercontent.com/4980243/75184559-a331ad80-5755-11ea-803e-f4da9400eddc.png)

**Comment by keegan-o** [comment]
The floor blocks do connect with the ground. I'm wary about making the cube and full wall blocks connect as well, but I could....

**Comment by trickenso** [comment]
>I'm wary about making the cube and full wall blocks connect

Could this at least be consistent? Cube connects with ground when you're building with other materials, and has in previous versions - does not really matter which you choose, but it would be preferable if it were the same for all similar block forms.
Full wall *looks* like it should connect, but it certainly doesn't have to, as it's a wall.

**Comment by SlayksWood** [comment]
> Reinforced Concrete Floor does not connect with dirt

**Comment by Sekor2600** [comment]
fixed in Svn
