### ISSUE TITLE
[0.9.0 staging-1422] Craft: Hints information

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14842]
1. Make two orders on a workbench. For 1 Hewn logs and 1 construction post
2. Take some birch logs and look at the table
![bandicam 2020-02-24 17-27-27-439](https://user-images.githubusercontent.com/27898520/75152989-17575b80-572c-11ea-9242-1005ee5bba10.jpg)
It tells me to put 20 Logs into the first order, but it actually needs 2
![bandicam 2020-02-24 17-27-30-596](https://user-images.githubusercontent.com/27898520/75153023-2b02c200-572c-11ea-95cf-f76645434439.jpg)
And after that tells me to put 18 into the second one. Well, it needs 1.

Then, when Im trying to put in some calories, it tells me that no order needs it.
![bandicam 2020-02-24 17-28-08-897](https://user-images.githubusercontent.com/27898520/75153086-4e2d7180-572c-11ea-8ce9-97a7f33bb6a0.jpg)
But it needs, I just don't have calories.

I think, hint and error should tell you if you lack of something.

**Comment by johnkslg** [comment]
Updated these, let me know if any other issues. Should be better but might be some changes needed still.

**Comment by beastyn** [comment]
1) Can we not show Ctrl modification hint until a plyer holds it?
(Like replace Shift + RMB on Ctrl + RMB with Ctrl holded)
2) Create some order without resources
If you look at the tyable, it will tell you to put a labor first.
I suppose that because I don't have resources on me, but its still strange, as it won't tale my labor.
Don't show hint then, I think?

**Comment by redwyre** [comment]
If you don't show the hint, how would the player know they can press ctrl or shift to change it? ;)

**Comment by johnkslg** [comment]
1. I made it show ctrl always, otherwise there's no way to know you can hold ctrl.  
2. Did that purposefully, so you know it needs labor, but you cant give it yet, and it gives a reason why.  Hoping that's more useful than not showing labor and having the user confused why it's not appearing. This is the mechanism by which they learn the labor-ingredient restriction. 
Tossing back to you

**Comment by SlayksWood** [comment]
This behavior was a little changed. Closed for now.
