### ISSUE TITLE
0.9 mass building feedback\suggestion.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14845]
1) if you have 1 block, you should place it in "point" mode.
2) please allow fill "partially occupied" area like
![unknown](https://user-images.githubusercontent.com/4980243/75154471-c12feb80-571e-11ea-9802-8ea0f9f58cf9.png)
ofc, occupied blocks should be ignored (not replaced).
3) if selected zone large than available blocks, should place available blocks in area.

**Comment by johnkslg** [comment]
Good ideas

**Comment by SlayksWood** [comment]
The first point has its flaw. But let's leave it that way for now, after the feedback from users.
