### ISSUE TITLE
Ladders do not allow you to actually climb over the top of the ladder...

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14853]
This is frustrating when placing a ladder on the outside of a building to scale the side-- it just doesn't work.
![image](https://user-images.githubusercontent.com/14983165/75203689-a90e9b00-5723-11ea-996a-f44ac7622df7.png)

**Comment by SlayksWood** [comment]
@keegan-o Are you sure that it should be in 0.9.0?
dup#9908
