### ISSUE TITLE
[0.9.0 staging-1424] Executive Office is not protected by Constitution

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14858]
While all other governance objects are protected by constitution, executive office is not. Means, if you have an constitution without any regulations (empty) you cannot use the zoning office or any other as it is not covered by any constitution. Only executiv office can be used by anybody if executive power is not regulated by constitution.
I would recommend to do the same like all the other offices.
below there is an error message which i would expect on executive offices as well:
![image](https://user-images.githubusercontent.com/47274045/75265691-8f3b8980-57f1-11ea-9982-d5f415d856f2.png)

**Comment by SlayksWood** [comment]
I have Basic Arcticle for Executive Office. Maybe someone who ratify constitution delete it?

**Comment by Alteraner** [comment]
yes, for sure, if you have it mentioned in the constitution, its protected. But if you delete it, or no constitution is yet ratified, you already can use the executive office.

**Comment by johnkslg** [comment]
Can you investigate?  Executive actions should follow the same rule as other civic objects if the constitution gives no powers (which is to not allow them)

**Comment by SlayksWood** [comment]
Now I have this notification when I try to perform action:
![image](https://user-images.githubusercontent.com/45708377/76047751-c8ec5d00-5f74-11ea-9317-f2efe6ed86f8.png)
It should appear when I press button 'Executive Action':
![image](https://user-images.githubusercontent.com/45708377/76047837-0650ea80-5f75-11ea-852b-9dd9cdfb2ca9.png)
