### ISSUE TITLE
Web issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14854]
Purchasing flow seems busted if I try to register an account, then 'upgrade' from nothing:
- [x] Registered new account, it should say somewhere that I dont own Eco.  After purchasing, it didnt say I did own Eco.  Should not show the icon if you dont own it. 
- [x] Upgraded account to 1 Eco license.  Paypal returned me to the account page, and SLG didnt complete my purchase. Once I went back to the Upgrade page, then the 'complete purchase' button showed up. I think paypal is redirecting back to wrong address after purchase.  
- [x] Even after completing the purchase, I dont think I had the license applied to my account (it didnt say 'you own this tier' in the upgrade section.

![image](https://user-images.githubusercontent.com/3536496/75222400-053fe200-5759-11ea-86d4-04c7cae75d6b.png)
- [x] All the icons are the same 

- [x] On hosted worlds, clicking this:
![image](https://user-images.githubusercontent.com/3536496/75222912-2ce37a00-575a-11ea-96f1-ea5f008d7d5b.png)
took me here: 
![image](https://user-images.githubusercontent.com/3536496/75222928-3371f180-575a-11ea-93bd-bed4ea951c5a.png)
Clicking *that* took me back to the starting page.

**Comment by denysaw** [comment]
Fixed. Take a lot of time merging oldest IconsAndRewards and finding and fixing FailedTierBuy issue.
