### ISSUE TITLE
The new Craft Resource and Craft Time difficulty multipliers should be added to the other multipliers in custom difficulty settings on hosting a new server

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14851]
![image](https://user-images.githubusercontent.com/14983165/75194421-f03d6180-570c-11ea-9d20-639b9a09171d.png)
The Craft Resource Multiplier/Modifier
and the Craft Time Multiplier/Modifier should be added to these other multiplier options for all players to easily access under the custom settings when hosting a new world.

**Comment by WeaselDog** [comment]
We need to update difficulty.eco.template to include the new values as well
