### ISSUE TITLE
[0.9.0 staging-1424] Notification overlapping

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14855]
First notification is from a work party
![bandicam 2020-02-25 11-51-30-752](https://user-images.githubusercontent.com/27898520/75226725-aa48d200-57ce-11ea-94f0-0704e8697cfa.jpg)

**Comment by SlayksWood** [comment]
Seems still an issue:
![image](https://user-images.githubusercontent.com/45708377/75418869-94115200-5945-11ea-8d0d-b643a84e5790.png)

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/76075656-7039b600-5fae-11ea-957b-2736043d3f68.png)
