### ISSUE TITLE
[0.9.0 staging-1423] District and Claim not visible next to map

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14850]
Closed to the minimap the district and the claim is not visible any more. They are existing, so if you move over with the mouse, you can click on them, but you cannot see them:
![image](https://user-images.githubusercontent.com/47274045/75185074-c48a9d80-5745-11ea-95c0-4c45723e67ac.png)

**Comment by beastyn** [comment]
I there a way to get a log from that session?

**Comment by beastyn** [comment]
dup #14428
