### ISSUE TITLE
In crafting UI, not specifying/distinguishing 'specialty' from just knowing the skill is confusing

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14862]
![image](https://user-images.githubusercontent.com/14983165/75297303-5ba63280-57e4-11ea-8a4c-9963eaa01d2f.png)

A basic thing here-- it's non-intuitive to research and learn carpentry, and then still not be able to craft things which require 'Carpentry 1'. It'd be good to specifically say 'Carpentry Specialty 1'.

**Comment by WeaselDog** [comment]
I can do it; it requires changing the code not the tech tree.
