### ISSUE TITLE
[0.9.0 staging-1424] transaction log lates on top of list

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14861]
As transactions with buy and sell is becomming more and more important in the game, it is essential to change the order of the transaction list. the newest have to be on top, as after two weeks with hundreds of transactions it is painfull to scoll down to the last entry just to check what happened in the last hours.
PLEASE, assume it's just a change of DESC to ASC or the otherway around, but having tons for quality for live. 

![image](https://user-images.githubusercontent.com/47274045/75292138-e8241580-5823-11ea-8fce-bfa64e3815ec.png)

**Comment by Sekor2600** [comment]
Maybe Add Filter / Sorting System?

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/6275
