### ISSUE TITLE
Hook up species icons to the viewer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14865]
![image](https://user-images.githubusercontent.com/3536496/75308035-26a8d880-5802-11ea-9e87-3dfae3fed614.png)
All species should have icons associated with their view, display them in the viewer here.

Check out HasViewIcon for how to get the icon associated with a view.   Each species has a SpeciesView on the client.  

The tooltip should show it too. Currently it's showing plant fibers, the resource it yields, which it shouldn't.
![image](https://user-images.githubusercontent.com/3536496/75308116-6243a280-5802-11ea-9fc7-1e678f06fc67.png)

Here's what the icon should be:
![image](https://user-images.githubusercontent.com/3536496/75308190-a3d44d80-5802-11ea-974a-8ae60cb6685e.png)

Ask me if you have any questions.

**Comment by gzatravkin** [comment]
Was fixed in https://github.com/StrangeLoopGames/Eco/pull/5684
