### ISSUE TITLE
World objects placement doesnt ignore / replace grass

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14873]
![bug1](https://user-images.githubusercontent.com/25908592/75330124-04a26b00-5881-11ea-9e4b-fb7f154b33a1.png)
![bug2](https://user-images.githubusercontent.com/25908592/75330157-066c2e80-5881-11ea-8807-a214e90c0458.png)

**Comment by SlayksWood** [comment]
Still hard to place:
![image](https://user-images.githubusercontent.com/45708377/75417269-a6898c80-5941-11ea-9be5-80253a267957.png)
Now it can delete grass, but I need find special place to do it.

**Comment by SlayksWood** [comment]
Can't hoe block with grass too.
