### ISSUE TITLE
[0.9.0 staging-1427] Store: Can't buy or sell

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14877]
Can't change quantity
![bandicam 2020-02-26 14-21-52-229](https://user-images.githubusercontent.com/27898520/75334404-9e7e0e00-58a9-11ea-91b5-3db6953cfe15.jpg)

**Comment by johnkslg** [comment]
Something happened with the prefab where the edit box got set non-interactable? There was a similar problem inside trade offers earlier.
