### ISSUE TITLE
[0.9.0 staging-1427] wrong labor rounding in Craft UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14879]
![image](https://user-images.githubusercontent.com/45708377/75338480-d1230900-589f-11ea-8437-927e3bba8d4f.png)

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/75422492-c45cee80-594d-11ea-8ab8-d49842b821ec.png)

**Comment by mirasrael** [comment]
Can't reproduce locally in Unity... Probably problem with il2cpp client.

**Comment by SlayksWood** [comment]
fixed
![image](https://user-images.githubusercontent.com/45708377/75676956-673da180-5c9b-11ea-9e6c-6280fa7449fe.png)
