### ISSUE TITLE
[0.9.0 staging-1427] Minimap tabs UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14870]
- [x] 1. We have useless scroll bar:
![image](https://user-images.githubusercontent.com/45708377/75321690-5b5c7480-5882-11ea-9859-cdfb36f3411b.png)
All tabs have internal scroll bar. So this scrollbar you need to delete and make tabs more width.

- [ ] 2. We have different style for Enviroment Data, Markers and for Settings and District Maps:
![image](https://user-images.githubusercontent.com/45708377/75321954-ed647d00-5882-11ea-9fd4-dbbff965acc2.png)
![image](https://user-images.githubusercontent.com/45708377/75321960-f05f6d80-5882-11ea-8cfa-9b51123c96c7.png)

**Comment by SlayksWood** [comment]
The text must disappear earlier:
![image](https://user-images.githubusercontent.com/45708377/76075128-81ce8e00-5fad-11ea-83b6-bcbe901ba39f.png)
![image](https://user-images.githubusercontent.com/45708377/76075305-d1ad5500-5fad-11ea-972a-d65a42284791.png)

**Comment by beastyn** [comment]
We still have different style (font size) for 3-d level entried. 
Can we make it similar or is there a reason for that?
![bandicam 2020-05-18 13-48-35-035](https://user-images.githubusercontent.com/27898520/82193193-7f25d880-990e-11ea-9efd-18d0fbd84b71.jpg)
![bandicam 2020-05-18 13-49-13-431](https://user-images.githubusercontent.com/27898520/82193197-80ef9c00-990e-11ea-8eff-f2fa4d7c6a6d.jpg)
