### ISSUE TITLE
[0.9.0 staging-1427] Top Notifications: Can't open tooltip in the last lines

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14876]
There is no pointer cursor and no tooltip, if you are hovering over any object in the last line
![bandicam 2020-02-26 15-05-19-287](https://user-images.githubusercontent.com/27898520/75334309-6aa2e880-58a9-11ea-99e7-86a6a5ff3ee8.jpg)

**Comment by SlayksWood** [comment]
still an issue.

**Comment by SlayksWood** [comment]
Seems fixed if I haven't cutting last notification, but it's another issue #14831
