### ISSUE TITLE
[0.9.0 staging-1427] Distribution station: wrong hint

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14883]
Im looking to the distribution.
It offers me to take an item with RMB which is not in the distribution list, but just stored inside this station.
![bandicam 2020-02-26 17-04-37-171](https://user-images.githubusercontent.com/27898520/75343352-1e13d900-58ba-11ea-924f-52b1a92bdbd8.jpg)
![bandicam 2020-02-26 17-05-13-627](https://user-images.githubusercontent.com/27898520/75343379-2b30c800-58ba-11ea-9381-cdc49ab95fa3.jpg)

It should offer me to take only items from the list

**Comment by johnkslg** [comment]
@olegshegai May need to update this to use the new interaction description system I made. It used to work this way, so just make sure its hooked up correctly. It's likely an issue of the storage object supplying an interaction description when it should be the item distribution component that supplies it only.

**Comment by beastyn** [comment]
1. Now for everyone we have a strange interaction logic.
With only LMB you will take everything you can. Actually, this kind of logic we use with CTRL modificator.
Did we change it intentionally?
Even if you are an owner you will take everything without modificators (and the hint here shows you how it should work - take a brick, but you actually will take everything you can).
![unknown (4)](https://user-images.githubusercontent.com/27898520/76392513-84592b00-6393-11ea-8010-874483114059.png)
![unknown (5)](https://user-images.githubusercontent.com/27898520/76392516-8622ee80-6393-11ea-92fe-33667e532082.png)

At least, if you are an owner you should work with a station like with stockpile. But its ok to make it like that for everyone.

2. This mouse button icon's position depends on resources amount  
![bandicam 2020-03-11 12-11-54-290](https://user-images.githubusercontent.com/27898520/76392630-c2564f00-6393-11ea-9162-84d47b2e3753.jpg)
