### ISSUE TITLE
[0.9.0 staging-1427] Meteor is invisible in day, brights in night

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14882]
![image](https://user-images.githubusercontent.com/45708377/75342622-d2f0ca80-58a7-11ea-9a44-af0480fed9ff.png)
![image](https://user-images.githubusercontent.com/45708377/75342665-e865f480-58a7-11ea-86b0-2b103caed050.png)

![image](https://user-images.githubusercontent.com/45708377/75342834-3f6bc980-58a8-11ea-956e-82d6a48a1ebf.png)

appears over the horizon like a shadow (/meteor makevisible):
![image](https://user-images.githubusercontent.com/45708377/75342782-282cdc00-58a8-11ea-9b8d-e83af2f7420c.png)
![image](https://user-images.githubusercontent.com/45708377/75343016-9f627000-58a8-11ea-97bd-4bdfec2cb147.png)
![image](https://user-images.githubusercontent.com/45708377/75342787-2bc06300-58a8-11ea-8aba-0ed87651d051.png)

**Comment by keegan-o** [comment]
@redwyre I need your help to get a shader to use for the meteor--

There are a couple options, any of which could work.

Probably most useful would be a version of the curved standard shader that has no fog applied to it-- of course, ideally, it would also supercede volumetric fog but that might be a lot harder.

If that is not relatively easily doable, then a curved version of the unlit shader would actually be acceptable. 

Currently, there are a few shaders in the project that say they do things that they do not, like this one, which is unfortunately affected by fog:
![image](https://user-images.githubusercontent.com/14983165/81734463-65851c80-9448-11ea-822c-41bdde6790ab.png)

**Comment by redwyre** [comment]
This may have swung a bit too much the other way, but we can tweak it

![image](https://user-images.githubusercontent.com/431728/85865603-7f689c00-b809-11ea-8025-9c38f348e6ac.png)

![image](https://user-images.githubusercontent.com/431728/85865649-91e2d580-b809-11ea-8d0b-e8430fa1021e.png)

**Comment by SlayksWood** [comment]
#16902. I Closed this one
