### ISSUE TITLE
[0.9.0 staging-1427] Craft: info banner issue

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14880]
When you are adding some resources from a hand to the project you see an info banner with white background
![bandicam 2020-02-26 13-23-19-656](https://user-images.githubusercontent.com/27898520/75339448-5e6f5900-58b2-11ea-8412-0561f99d81ad.jpg)

**Comment by johnkslg** [comment]
forgot to check in, fixed.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/75420218-988b3a00-5948-11ea-8f67-2ad432d9f00f.png)

**Comment by SlayksWood** [comment]
Seems same 
Announcement -> Eye Cancer
![eyecancer](https://user-images.githubusercontent.com/25908592/75418814-afc02c80-5934-11ea-89a3-2693bfe82497.png)
#14896
