### ISSUE TITLE
[0.9.0 staging-1429] Double law description in Legislation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14899]
![image](https://user-images.githubusercontent.com/45708377/75444630-d4d48f80-5974-11ea-9925-3cf720207649.png)

**Comment by beastyn** [comment]
can reproduce if im staying on my claim, without room, after rebooting client.

**Comment by Dmittry62** [comment]
Can't reproduce. Maybe it was fixed?
