### ISSUE TITLE
0.9 lot of missing or not used strings (server)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14907]
world - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#95936
tim - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#146870
rep - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#146872
us - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#95944
garb - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#99064
Disasters - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#95948
Property - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#147772
chat - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#95952
layers - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#99926
rooms - https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#95924
objectives - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#145364
sleep - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#152766

Missing string - EconomyManager, ViewtypeData, Plants (exists only for webclient), UserTracker, WorldObjects, CivicsPlugin, GameDataPlugin,

Also "Initializing" localization is not used for some strings.

![изображение](https://user-images.githubusercontent.com/4980243/75463833-635a0880-5997-11ea-8f50-91130cdeb0d5.png)
![изображение](https://user-images.githubusercontent.com/4980243/75473245-dc605c80-59a5-11ea-8f34-2c871861048d.png)

**Comment by elfl0rd** [comment]
@Quadbro "WorldObjects" isn't appear.

**Comment by SlayksWood** [comment]
hm strange it localizate in gibberish.
@Quadbro 
check it pls again.

**Comment by SlayksWood** [comment]
@elfl0rd 
everything is translated in gibberish. Reopen if something isn't used
