### ISSUE TITLE
Need more migration for 8.3 - > 9.0

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14908]
Logs & Stone are now legacy items. In the tech tree they are in some places but not others. We need to decide if we want them to keep them in all recipes or convert them to a specific type of Log/Stone on migration.

**Comment by WeaselDog** [comment]
It sounds like there is a planned solution to migrate to specific types. I will just double check it is ready in tech tree and close

**Comment by beastyn** [comment]
@mirasrael was making something with these already as I reckon. Like replacing with some existing items.

**Comment by WeaselDog** [comment]
I looked into this more and migration does need work
