### ISSUE TITLE
[0.9.0 staging-1429] Civics: notification for everyone from ballot

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14900]
WIth a Title setting Im not able to enter the election for a Title
When Im trying to enter an election fot such a Title I've got my OK Box with information and notification. Thats ok.

But the other players get that notification too! They didn't even try to enter the election.

![unknown (62)](https://user-images.githubusercontent.com/27898520/75445413-2ab23300-5987-11ea-845a-f279e04c05e2.png)

**Comment by johnkslg** [comment]
Can you give a look over various notifications and make sure they're acting correctly?
