### ISSUE TITLE
0.9 Missing strings with "relay" (server)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14902]
Relay Server Address
And description
![изображение](https://user-images.githubusercontent.com/4980243/75458644-44577880-598f-11ea-8c29-f65e2247bb4a.png)

**Comment by Quadbro** [comment]
Description is on crowdin
![image](https://user-images.githubusercontent.com/6802030/77295498-a732fa00-6d18-11ea-8f16-02bfcf82f7fd.png)

**Comment by Quadbro** [comment]
other added in update
