### ISSUE TITLE
 Storage Chest link to Workbench

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1490]
Stupid beginning ? Issure ? (5.6)
Drop  Storage Chest somewhere
On an other Place Build House with Workbench (You can start Project's) but
Project: Hammer --> Can only Store in Storage Chest
Project: Storage Chest -> Storage Chest can only Store in Storage Chest
Solution ---> Stockpile should be able for TOOLS / Storage Chest's
TO move the Storage Chest you need the Hammer

**Comment by Uniphix** [comment]
Sounds like something I would have done in 5.6 lol

**Comment by MarjieAVolk** [comment]
This is why we should give the hammer as an early skill unlock

**Comment by REPOSEECO** [comment]
But at the momet you get no Hammer. If you set 2 Skilpoints & have no Storage Chest

**Comment by REPOSEECO** [comment]
UPpss wrong Button Soory

**Comment by craig-jong** [comment]
There aren't any skills that can support it (that make sense) right now. Can probably make room for it somewhere - but also you should be able to take crafted items from the workbenches without a chest.

**Comment by craig-jong** [comment]
I'm adding it to the basic crafting skill

**Comment by Uniphix** [comment]
You mean adding the hammer as part of the basic crafting skill along with workbench?

**Comment by craig-jong** [comment]
yes
