### ISSUE TITLE
[0.9.0 staging-1429] Web elections: need some feedback for submit button

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14901]
When you are clicking Submit button there should be a message, like
Your voute is counted

Or reason if you can't vote due some election process reasons for example.
Here I am not able to vote as I do not have President title.
Im choosing a candidate and clicking submit. And nothing happens.

![bandicam 2020-02-27 18-16-28-495](https://user-images.githubusercontent.com/27898520/75449214-6b617a80-598e-11ea-84c9-959641081831.jpg)

Im not sure if information for this error message is in Api.
ask @john here, please

**Comment by beastyn** [comment]
Fix this first
#15890

**Comment by denysaw** [comment]
@beastyn What?! =)
1. How they are related at all? 
2. That is not Web issue, that's in-game bug as I understood.
:/

**Comment by beastyn** [comment]
@denysaw its mark for me. I can't just test it yet )
