### ISSUE TITLE
UIs don't close when pressing ESC

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14918]
Needing to click the button to close them drives me insane.

**Comment by beastyn** [comment]
Action bar's UI, tables, stocks, contracts - everything is closing with ESC in 1435. Something specific?

**Comment by D3nnis3n** [comment]
Tables (Stockpiles) do not close for me.

**Comment by D3nnis3n** [comment]
Yap, fixed in 1435.
