### ISSUE TITLE
Minimap draws a massive amount of resources for some people

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14915]
Caralias with 13 fps was able to fix his fps by sliding down the map details to very bottom and gets 50 fps now. He was able to get 50 fps with high details in 8.3.X though.

**Comment by redwyre** [comment]
Well that's what the slider is there for :P
What are the video card stats? Also, was worlds?

**Comment by D3nnis3n** [comment]
Well, the slider is broken if the same setting gave triple fps before.
RX480, i5-6500, 16GB, Windows 10

**Comment by elfl0rd** [comment]
Yes, this issue exists for a long time, but before - we can totally disable minimap.

**Comment by mirasrael** [comment]
Fixed (details here https://github.com/StrangeLoopGames/EcoIssues/issues/14789)
