### ISSUE TITLE
Shovel is put in the cart when carried dirt cannot be placed in cart anymore due to being full

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14911]
https://media.discordapp.net/attachments/680068515658596364/682538395741847565/unknown.png?width=960&height=270

**Comment by mirasrael** [comment]
I don't know when it was changed, but I guess it shouldn't try to put selected item from bar if you're holding something in carried slot. It is very confusing in many cases.
