### ISSUE TITLE
Login issues on playtest

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14910]
Several people reported having occasional issues on login, being stuck on somewhere between 90 to 98% with either nothing happening forever or it taking a very long time to finally login.

**Comment by beastyn** [comment]
some information from people. like scpecs and logs?

**Comment by D3nnis3n** [comment]
Logs from one player:
https://www.dropbox.com/s/yiwfkl8ljvrjcvv/Player-prev.log?dl=0
https://www.dropbox.com/s/j9a0ud4epfoa4mb/Player.log?dl=0

**Comment by D3nnis3n** [comment]
Player.log

Loading the world got stuck at 80%, 91%, 96% for a total of 29 minutes

**Comment by D3nnis3n** [comment]
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4301923/Player.log)

**Comment by D3nnis3n** [comment]
> player-prev.log is more then 50mb, so too large
> Dropbox link: [https://www.dropbox.com/s/lhklemflbf76zmx/Player-prev.log?dl=0](url)

**Comment by revtje** [comment]
![20200308033903_1](https://user-images.githubusercontent.com/39825431/76155589-5f905980-60ee-11ea-83f4-7819eb78d138.jpg)

Adding screenshot of in game network diagnostic overlay

**Comment by revtje** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4303643/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4303644/Player-prev.log)
![20200308190953_1](https://user-images.githubusercontent.com/39825431/76168487-8ee7aa80-6170-11ea-9653-20837cea4e45.jpg)

Got the issue again this time it took 10 minutes
I5-9600, 16GB RAM, SSD, GeForce GTX1060Ti

**Comment by revtje** [comment]
[eco_loading_world_capture.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4313331/eco_loading_world_capture.zip)

Attaching wireshark log from just before I pressed "Continue" button in the world.
Stopped the capture when I got into the game

Some notes:
It loaded 0-91% then stuck for a couple of minutes
92% stuck again for a couple of minutes. longer than 0-91%
around packet ~77000 loading world changed to 93%
around packet ~79000 loading world changed to 94% then 95% a couple seconds after
around packet ~82000 loading world changed to 96%
around packet ~93000 loading world changed to 97%
around packet ~125000 i got into the game
Total time to login ~20 minutes

**Comment by Knigge** [comment]
Second time login on after updating Nvida drivers experiencing some stuttering I get stuck at 99%

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4340437/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4340438/Player-prev.log)

**Comment by revtje** [comment]
I have found the problem. Set view distance to lowest and the loading will be slow. Reset defaults and it will load fast again. Reproduced it 3 times and have had other users confirm it too.
