### ISSUE TITLE
[0.9.0 staging-1437] Work party trouble after server resrart.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14929]
Step to reproduce:
- start order. In my case it's order for 5xBasicupgrade2
![image](https://user-images.githubusercontent.com/45708377/75545739-2a25a500-5a38-11ea-8580-70a10d841660.png)
- start to create workparty:
![image](https://user-images.githubusercontent.com/45708377/75545760-37db2a80-5a38-11ea-837a-d4e03086c855.png)
- I need only labor(because I haven't masonry4), so I delete resources:
![image](https://user-images.githubusercontent.com/45708377/75545774-3e69a200-5a38-11ea-8412-746c171f0604.png)
- another player add labor to my workparty. Workparty should finish:
![image](https://user-images.githubusercontent.com/45708377/75546016-c0f26180-5a38-11ea-8069-08508dc453ca.png)
- I add 2 Boards at order. I have good notification:
![image](https://user-images.githubusercontent.com/45708377/75546758-5cd09d00-5a3a-11ea-9e42-9efc319f4a11.png)
- restart server and try to add anoter one board:
![image](https://user-images.githubusercontent.com/45708377/75546850-930e1c80-5a3a-11ea-814a-9d13fc0180b6.png)
- I have notification about removed WorkParty.

**Comment by johnkslg** [comment]
Verified that the server is setting WorkOrder.WorkParty to null, and the WorkOrder registry is being set to dirty, but for some reason it doesnt save when the server is shutdown normally. Something going on with the save system here. @mirasrael can you take a look as time permits

**Comment by johnkslg** [comment]
Nevermind, it was being reset on load. Fixed!
