### ISSUE TITLE
[0.9.0 staging-1435] UI can't be closed

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14927]
Step to reproduce:
- select hammer and take some block in hands:
![image](https://user-images.githubusercontent.com/45708377/75517694-5b8a7a80-5a10-11ea-848e-7128b4361fde.png)
- open any UI
![image](https://user-images.githubusercontent.com/45708377/75517811-a73d2400-5a10-11ea-95b9-7bb8993a9a68.png)
- press F:
![image](https://user-images.githubusercontent.com/45708377/75517718-6ba25a00-5a10-11ea-9c5a-23e0dc01fb51.png)
- when you hold F press ESC:
![image](https://user-images.githubusercontent.com/45708377/75517733-78bf4900-5a10-11ea-81bb-34331e65290f.png)
- you can't close this UI. Only reload can help.
https://drive.google.com/file/d/1UrPjfVgg1fUL43HP4tVqFOUfif4ddjgO/view?usp=sharing

**Comment by mirasrael** [comment]
Raised to High, because prevents normal gameplay and easy to reproduce occasionally.

**Comment by WiseProjects** [comment]
It's also reproducing by scrolling mouse wheel holding F (or changing tool another way)
