### ISSUE TITLE
Text limit for speeches is way too small

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14928]
That's all i can type there, can't type any more.

![limit](https://user-images.githubusercontent.com/25908592/75518997-88379580-5a02-11ea-885f-3643962a7e3e.png)

**Comment by johnkslg** [comment]
Make it an extra tall box too.

**Comment by SlayksWood** [comment]
Scrollbar appears if it doesn't need:
![image](https://user-images.githubusercontent.com/45708377/80480435-5175f100-8959-11ea-9f74-6e282d64caf7.png)
SHould be hide until you add 6+ strings.
