### ISSUE TITLE
Table retaining "requirements" after being moved 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1492]
If a table is placed in a room where it meets requirements and is later picked up and moved elsewhere its status stays "meets requirements" even if moved to someplace that does not meet requirements.

**Comment by craig-jong** [comment]
I cannot repo this. If someone can give me steps to repo this, that would be awesome.

**Comment by MarjieAVolk** [comment]
It's possible this is a misinterpretation of the generally bizarre and inexplicable rooms behavior.  Guess we never asked, which version did you see this on?

**Comment by pamduncan** [comment]
They tell me this happened in both 5.5.4 when they were playing it and is still happening in current versions of 5.6.  They are hopeful it gets left like this because it solves the problem of having to build large many roomed bases.  they just get the table to meet requirements and then move it to one big workroom where it shares space with every other table in the game

**Comment by craig-jong** [comment]
Room requirements and room detection was changed, so hopefully this is no longer an issue.

I cannot reproduce this bug anymore (not that I could in the first place either ]: )
