### ISSUE TITLE
[0.9.0 staging-1429] Civics: description is running away from UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14926]
![bandicam 2020-02-28 11-20-43-177](https://user-images.githubusercontent.com/27898520/75515942-16207a00-5a1d-11ea-981a-971b131bfec5.jpg)

**Comment by SlayksWood** [comment]
Should be align left:
![image](https://user-images.githubusercontent.com/45708377/75659118-8415ad00-5c7a-11ea-8d59-d761a10eac96.png)
