### ISSUE TITLE
0.9 (server) no correct description for Spawn nearby food location

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14922]
base text is too short :) as i think we need a better description.
![изображение](https://user-images.githubusercontent.com/4980243/75489585-95815f80-59c3-11ea-97d4-7682b3fdc3d0.png)

**Comment by SlayksWood** [comment]
@elfl0rd 
What description do you want?

**Comment by WeaselDog** [comment]
Thanks for reporting this. There is no more config for Spawn Nearby Food location and it has been combined with Spawn Location.
