### ISSUE TITLE
[0.9.0 staging-1437] Civics: amendment issue for Laws

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14931]
I wanted to make a separate article for Laws with Prevent Action type.
And I couldn't.

1. You create an article in the Amendment for the Law with prevent action type (here with Veto Test election process) Don't delete the original article, we don't want to ruin main election logic for laws.
![bandicam 2020-02-28 16-56-43-885](https://user-images.githubusercontent.com/27898520/75550066-deccc000-5a52-11ea-9fe9-4beeeb52aa14.jpg)

2. Pass the article
3. Try to create a law with prevent action and check its election process. It will be basic process.
![bandicam 2020-02-28 16-58-11-346](https://user-images.githubusercontent.com/27898520/75550081-e4c2a100-5a52-11ea-9304-e4b399c64a0a.jpg)

This amendment's article will work only if I delete the main article from the  Constitution.
We need to find a way to make amendment logic for Law more flexible.

**Comment by johnkslg** [comment]
Good point. Came up with a solution where the more specific one is used  (whichever states more properties):
![image](https://user-images.githubusercontent.com/3536496/76287434-7944c300-62df-11ea-841d-49aec6656427.png)

We could also let the user set a specificity value, but hopefully this will be enough.
