### ISSUE TITLE
not accept english-like word when used localization server

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#14935]
When used localization (non-English) server and use command "/give" server not accept english-like items 

![изображение](https://user-images.githubusercontent.com/13696708/75567481-adf48700-5a62-11ea-847b-d7bd78210c47.png)

When using command: /give MasonryTable
Server answer
![изображение](https://user-images.githubusercontent.com/13696708/75567752-15123b80-5a63-11ea-9427-c07554150669.png)

**Comment by SlayksWood** [comment]
It was fixed for localization. But "/give masonrytable" doesn't give you  in english too. You should write "/give Masonry table". Same for carpentry table.
