### ISSUE TITLE
[0.9.0 staging-1437] Civics: no tooltips for drafts

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14930]
We miss tooltips in draft section with new design.
![bandicam 2020-02-28 16-57-55-636](https://user-images.githubusercontent.com/27898520/75549757-39b1e780-5a52-11ea-9d76-3ea3c055dcb6.jpg)

**Comment by SlayksWood** [comment]
Still missing tooltip here:
![image](https://user-images.githubusercontent.com/45708377/75658981-4b75d380-5c7a-11ea-97ab-37dac26990bb.png)

**Comment by beastyn** [comment]
1460 working fine
