### ISSUE TITLE
New minimap meshes for trees

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14946]
Existing:
 - [x] Birch
 - [x] Cedar
 - [x] Ceiba
 - [x] Fir
 - [x] Oak
 - [x] OldGrowthRedwood
 - [x] Palm
 - [x] SaguaroCactus
 - [x] Redwood

Doesn't currently have a mesh (?):
 - [x] Joshua
 - [x] Spruce

All meshes need to share the same material, as we have done with the test assets. Keeping the meshes extremely low poly is recommended.

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13408
Spruce?

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/75726148-ac130980-5c96-11ea-8b3d-cde8c0025175.png)
Just committed these, it would be nice if you could hook them up @redwyre  so we can use descriptive names rather than MapCube1, etc etc.

**Comment by beastyn** [comment]
Im note sure if this is fixed, buuuut
1) No trees at all on the map
2) Now, with Trees checked, we have this strange whire rectabgle
![bandicam 2020-03-06 11-13-59-301](https://user-images.githubusercontent.com/27898520/76057540-ab7eb980-5f9b-11ea-92e7-29d11c176e30.jpg)
![bandicam 2020-03-06 11-14-10-224](https://user-images.githubusercontent.com/27898520/76057547-ad487d00-5f9b-11ea-8ee0-5b111a295ace.jpg)

**Comment by Sekor2600** [comment]
![Ecosever (2)](https://user-images.githubusercontent.com/37456949/76164676-0574b000-6151-11ea-9adf-5ad576cd5f01.gif)

**Comment by elfl0rd** [comment]
Hmm... Not bad if we have marker at map center.

**Comment by redwyre** [comment]
Should be fixed now

**Comment by elfl0rd** [comment]
old trees looks better :(
