### ISSUE TITLE
Ecopedia art polish/feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14945]
![image](https://user-images.githubusercontent.com/3536496/75621578-2b3e0a00-5bd1-11ea-94d3-d207b566ff4e.png)
- [ ] Icon is too small to read. I'd just make this a tree

![image](https://user-images.githubusercontent.com/3536496/75621584-3f820700-5bd1-11ea-90f9-597520ee8c1b.png)
- [ ] Need different icons for each of these

![image](https://user-images.githubusercontent.com/3536496/75621592-532d6d80-5bd1-11ea-8779-dd1ae5fc7ec0.png)
- [ ] Icon is off-center (maybe because its a tutorial icon not a regular icon?) 

![image](https://user-images.githubusercontent.com/3536496/75621596-64767a00-5bd1-11ea-93fb-0fd4fcc27bab.png)
- [ ] This would look way better if it was isometric like other icons. 

![image](https://user-images.githubusercontent.com/3536496/75621598-6fc9a580-5bd1-11ea-9969-df10ce2ea1be.png)
- [ ] A power generator, or electrical pole, would fit better here. 

![image](https://user-images.githubusercontent.com/3536496/75621613-88d25680-5bd1-11ea-97c2-f1ae3fd476b6.png)
- [ ] Icon is aliased

![image](https://user-images.githubusercontent.com/3536496/75621623-a43d6180-5bd1-11ea-9873-861e07df822a.png)
- [ ] Ecosystem and Economy images are way taller than other banners. Lets make them the same height.  

![image](https://user-images.githubusercontent.com/3536496/75621629-b6b79b00-5bd1-11ea-862f-6d3afd6b762a.png)
- [ ] Also too small to read, I'd just make one animal with lines coming off probably

![image](https://user-images.githubusercontent.com/3536496/75621642-c931d480-5bd1-11ea-9c77-459cce6abcb3.png)
-[ ] Would look better if tree had its trunk

**Comment by RobertMangano** [comment]
new icons were made for most of these
