### ISSUE TITLE
0.9 you cannot break connection

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14940]
pressing esc does nothing
![20200229104055_1](https://user-images.githubusercontent.com/4980243/75603499-fbfba000-5adf-11ea-9097-6609bb747608.jpg)

**Comment by SlayksWood** [comment]
It happens when you only have "Connecting".
Best step to reproduce:
- join to server.
- disconect.
- close server.
- press "Continue".
- you have long "Connecting" and can't break it.
