### ISSUE TITLE
Trees not displaying in species selector now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14943]
![image](https://user-images.githubusercontent.com/3536496/75621455-7eaf5880-5bcf-11ea-887c-8c67d5a1c6e3.png)
Was working a few days ago

**Comment by SlayksWood** [comment]
It works if you use axe:
![image](https://user-images.githubusercontent.com/45708377/75652558-6b9e9600-5c6c-11ea-9ce1-d15aebdab83b.png)
May be it will intented?
