### ISSUE TITLE
Ecopedia is missing content

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14947]
All vechicles, carts, trucks, etc.
99% of tools (except torch and land claim stake)
Live animals ? (idk about it, but ecopedia is not contain info about animals, only about carcasses.)

**Comment by WeaselDog** [comment]
The following content is missing from Ecopedia:
- All Economic components except Credit & Store component
- All Government Components except Civic Action & Civic Object
- Bed Component
- Vehicle Component

**Comment by serpopov** [comment]
bed and vehicle component not missing, please be sure you are have already discovered them

also, you can use this toggle:
![image](https://user-images.githubusercontent.com/4238643/75725486-22ede800-5d13-11ea-8b3b-7a54f8540273.png)

**Comment by WeaselDog** [comment]
Thanks for the heads up on the live animals but going to include that is a separate addition.  The process is not the same for tools and vehicles but it is something we want to add.
