### ISSUE TITLE
[0.9.0 staging-1441] Missing notification when you try to pickup craftTable with order

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14952]
Step to reproduce:
- place workbench.
- add order, add 1 ress, add labor:
![image](https://user-images.githubusercontent.com/45708377/75673462-09598b80-5c94-11ea-8283-0a1376629aaf.png)
- try to pickup. I haven't any notification why I can't to pickup:
![image](https://user-images.githubusercontent.com/45708377/75673512-2b530e00-5c94-11ea-8923-4a62f97e2eec.png)

**Comment by olegshegai** [comment]
![image](https://user-images.githubusercontent.com/56091594/76747866-e4ccdb80-678a-11ea-967e-afda829f9209.png)

**Comment by mirasrael** [comment]
Fixed as part of other issue fix.
