### ISSUE TITLE
[0.9.0 staging-1441] Tutorial: forage for food: shows one plant

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14953]
Sometimes 1 plant appears. I think need minimum 3 plants for tutorial.

from StrangeLoopGames/EcoIssues#12507

**Comment by tuha263** [comment]
We will set up 4 (maximum) species in this tutorial. In we can't find any plant nearby, the player will have another option that collects food from any source (maybe from another player). I already double the searching range so it's will easier to find 4 species.
