### ISSUE TITLE
[0.9.0 staging] Planted Fireweed Seeds are invisible

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14967]
To replicate:
- /give wooden hoe and plow land
- /give fireweed seed and plant
- It is invisible but the Soil Sampler indicates it has been planted

**Comment by Sekor2600** [comment]
Seems like same problem https://github.com/StrangeLoopGames/EcoIssues/issues/12683

**Comment by SlayksWood** [comment]
@Sekor2600 It looks like Small model for Fireweed was lost or never been exist.

**Comment by SlayksWood** [comment]
dup #11353
