### ISSUE TITLE
ecopedia, after change tab, selection stay at last position

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14964]
e.g.
![изображение](https://user-images.githubusercontent.com/4980243/75692110-1c7d5300-5cb6-11ea-958d-91abd96aba31.png)

change
![изображение](https://user-images.githubusercontent.com/4980243/75692144-2737e800-5cb6-11ea-8261-7a587ed88487.png)

happens at first visit.

**Comment by WeaselDog** [comment]
@serpopov For the intended behavior, we want it to select the first item when switching tabs in reference.

**Comment by beastyn** [comment]
We've decided:
If page is empty - select the first subpage for opening
