### ISSUE TITLE
ecopedia now miss tools

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14962]
Pickaxes? Bows? hammers? etc, etc, etc.
![изображение](https://user-images.githubusercontent.com/4980243/75691638-6285e700-5cb5-11ea-9f14-09e987a9166d.png)

https://github.com/StrangeLoopGames/EcoIssues/issues/14956

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/14947
