### ISSUE TITLE
"client" in contracts confusing

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14978]
https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#102096
`All grass tiles on specified property must be cut with a scythe or other mower. \n\nClient will be given rights to mow only on the specified property.`

client or contractor?

as i think, client - who post contract
contractor - who accept contract and work
right?

also https://crowdin.com/translate/eco-by-strange-loop-games/50/en-ru#102078

**Comment by beastyn** [comment]
Yeap, good call.
Contractor - who is working for a contract and getting rights
Client - who is givins a contract.

So, we need to check all descriptions:
Clear Tree Stumps and Debris
Harvest
Mow
Plow
