### ISSUE TITLE
[0.9.0 staging-1443] UI: Esc won't work after error notification

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14977]
1. Place workbench
2. Make big hewn log order (1000)
3. Add one birch log, and then start to add a labor
4. Stop. when you see srrer message
![bandicam 2020-03-03 16-05-44-482](https://user-images.githubusercontent.com/27898520/75769972-de8d3700-5d68-11ea-8817-327b01771e22.jpg)
5. Then try to close a workbench UI with ESC
It will open main menu.
It should close UI.
It seems to be really annoying for the players, so medium.

**Comment by gzatravkin** [comment]
Now it should close only error message on escape. Then if you press ESC again it will close UI (and at third time show main menu)
