### ISSUE TITLE
USER ISSUE: Singleplayer timed out

### ISSUE THREAD

**Issue by MrSeem** [StrangeLoopGames/EcoIssues#14973]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. New Game
2. Start a new game
3. Wait for it to load
4. Connection timed out

**Expected behavior:**
Should've started a new game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by SlayksWood** [comment]
@MrSeem 
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the 0.8.3.3 or you had it before?
