### ISSUE TITLE
Error in PlayTest Server Logs

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14970]
> [16:17:13.385] [22] [Error] [Eco] System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Type,System.Object]' to type 'Eco.Gameplay.Items.ItemPersistentData'.
>    at Eco.Gameplay.Items.IPersistentData.Pickup(WorldObject placedObject)
>    at Eco.Gameplay.Items.WorldObjectItem.OnPickup(WorldObject placedObject)
>    at Eco.Gameplay.Objects.WorldObject.<>c__DisplayClass109_0.<TryPickUp>b__1()
>    at Eco.Gameplay.GameActions.GameActionPack.<>c__DisplayClass13_0.<AddPostEffect>b__0()
>    at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, List`1 actions, IEnumerable`1 preTests, IEnumerable`1 postEffects)
>    at Eco.Gameplay.GameActions.GameActionManager.TryPerformActions(User user, GameActionPack actionPack, Boolean notify)
>    at Eco.Gameplay.GameActions.GameActionManager.TryPerform(GameActionPack pack, Boolean notify)
>    at Eco.Gameplay.Objects.WorldObject.TryPickUp(Player player, Single caloriesNeeded)
>    at HammerItem.PickupDialog(WorldObject obj, InteractionContext context) in D:\Servers\Eco\Stuffed Elk\Mods\Tools\HammerItem.cs:line 118

Change priority accordingly, i have no idea how serious they are.

**Comment by mirasrael** [comment]
Save was corrupted. Save fixed. It also shouldn't happen on latest version.
