### ISSUE TITLE
USER ISSUE: kiln not working in multiplayer

### ISSUE THREAD

**Issue by heshtur** [StrangeLoopGames/EcoIssues#14974]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Put down a kiln (or a few)
create a project of 1000 Shale Bricks
Try selecting a Small Stockpile as storage output
Manually input materials by hand.

**Expected behavior:**
Update storage to all players

**Actual behavior:**
Only updates for me and the kiln does not output to the small stockpile,
Project continues running, counts down timer, but project remains at 1000 bricks (as if it wasn't creating them)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by heshtur** [comment]
Update: We were led to think that the kiln had their materials, but they were not being "Blocked" despite missing materials to proceed, and thus burning fuel.

1. Set down a kiln and place down a small stockpile, put in mortar and clay but set up recipe for Shale bricks.
2. Kiln will begin burning fuel as if it had all the materials but is not stopping despite missing the shale. (gif of issue below)
3. Friend cannot alter the storage (he is on the deed), I can't see his changes and he can't see mine.

>friend: "changes only show up for me, server seems to ignore them"

https://i.imgur.com/KkWzmOq.gifv

**Comment by LeiserGeist** [comment]
Kilns seem to have some strange and unique issues.
I'll add that I can't directly insert items into them, as I can with other crafting stations ("Not able to move any item", despite the item being listed as missing).
As well as the seemingly desynced storage settings and infinitely looping crafting mentioned above.

**Comment by beastyn** [comment]
Logic for orders was changed in 9.0, should work better.
Also you can't cancel an order from another player, but it will be changed a little in 9.0 too.
