### ISSUE TITLE
Optimization: DataStore is using a lot of CPU time

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14982]
Alex has suggested this may be because the Registrars save the entire contents with any change.

**Comment by johnkslg** [comment]
Could investigate cases that cause frequent saves:
- Calories changing on players
- Animal positions
- Work order timer

**Comment by johnkslg** [comment]
ProgressSeconds++++
CompletionTime

AnimalPosition
AnimalDestination (pos and time)

CaloriesReachZeroTime

**Comment by johnkslg** [comment]
First step: see how impactful it is
