### ISSUE TITLE
Optimization: Chat using a lot of memory

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14980]
Chat seems to be using 100s of megs or memory.

**Comment by johnkslg** [comment]
Paged saving?
Introduce appended saving?

**Comment by mirasrael** [comment]
After investigation seems like it requires big refactoring and because for small servers it isn't big issue, but for big servers they usually have enough RAM and HW launch delayed post-9.0 I guess it may be pushed for later.

**Comment by WeaselDog** [comment]
> All chat messages are kept in memory all the time, forever. Over time this grows to a massive amount of messages when 99% of them are never accessed or used.
> 
> optionally also change chat to be saved in the db, instead of in storage

**Comment by j3fffff** [comment]
repeat of https://github.com/StrangeLoopGames/EcoIssues/issues/19739
