### ISSUE TITLE
[0.9.0 staging-1444] Money doesn't return from Contract Escrow if you cancel WorkParty.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14988]
Step to reproduce:
- I have 900 TestCoins:
![image](https://user-images.githubusercontent.com/45708377/75857620-8eb17d00-5e07-11ea-809e-9afa2df20c56.png)
- create work party. Add for payment 100 Testcoins:
![image](https://user-images.githubusercontent.com/45708377/75857747-c1f40c00-5e07-11ea-8895-7143a864fa34.png)
- Now I have 800 Testcoins:
![image](https://user-images.githubusercontent.com/45708377/75857778-d46e4580-5e07-11ea-90d9-ec466c83e4f1.png)
- delete work party. It should return me money, but it doesn't work. I still have 800 Testcoins:
![image](https://user-images.githubusercontent.com/45708377/75857868-0d0e1f00-5e08-11ea-83f1-0730f1567447.png)

**Comment by johnkslg** [comment]
Fixed! Good bug. 
![image](https://user-images.githubusercontent.com/3536496/76063264-5609d300-5fc2-11ea-80fc-16884c2b2d95.png)
