### ISSUE TITLE
0.9 worldgen config version

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14983]
by default, "new" config has 0 version.
But "last" start from 1.
![изображение](https://user-images.githubusercontent.com/4980243/75782931-b43f7780-5d70-11ea-9484-0c94a4860b72.png)

As result, a freshly created worldgen is removed.
![изображение](https://user-images.githubusercontent.com/4980243/75782963-c6b9b100-5d70-11ea-8da9-a97e8e07e250.png)

**Comment by redwyre** [comment]
This is on purpose, though the error message could be better.

**Comment by elfl0rd** [comment]
> This is on purpose,

It's not logic, i open server panel, edit config, press save, restart server ang my config got deleted.
It's NOT intended behavior.

**Comment by mirasrael** [comment]
In template it should be "1" (latest version). It will use template value as default unless config exists without ConfigVersion key or with ConfigVersion = 0. Also version shouldn't be editable from GUI.
