### ISSUE TITLE
[0.9.0 Staging] Recipe & Crafting UI needs a way to indicate static ingredeints

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14986]
We have significantly more recipes with static ingredients (recipes that do not receive material reduction from modules). We need some way to indicate this to players.

To replicate:
- /give Arrastra and place
- /give MiningUpgrade and place in Arrastra
- Look at recipes. The costs for Crushed Stone is not adjusted with no explanation why.

**Comment by johnkslg** [comment]
Can give these a special border and tooltip

**Comment by mirasrael** [comment]
Yeah, my suggestion is to show static with yellow border, affected by bonus with green border and unaffected with white border.

**Comment by WeaselDog** [comment]
That sounds like a good solution

**Comment by SlayksWood** [comment]
still need fix #15085
