### ISSUE TITLE
0.9 strange strings at crowdin

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14995]
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#167826
A complete meal **replaAdvancedMasonry** solution.
![изображение](https://user-images.githubusercontent.com/4980243/75902859-c5ac8080-5e51-11ea-9492-c53a376933db.png)

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#167408
A superior **replaAdvancedMasonry** for the bloomery that can produce steel.

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#167568
Bricklaying is an **advanAdvancedMasonry** in masonry and can provide an excellent building material for communities. Level by crafting related recipes.

--- Maybe correction needed

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#167738
A material made from AdvancedMasonry and an aggregate like crushed stone. In order to be usable it needs to be reinforced.

advanced masonry + aggregate? hm
![изображение](https://user-images.githubusercontent.com/4980243/75902771-9dbd1d00-5e51-11ea-83cd-95397bd42ed7.png)

As i see, main issue at ctrl+f "cement" then replace all.

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#171071
Advanced masonry grants improvements to to higher stonefurniture and material for houses. Level by crafting related recipes.

maybe stone furniture?

**Comment by elfl0rd** [comment]
Not fixed - crowdin isn't updated.

**Comment by SlayksWood** [comment]
Bug is fixed. Crowdin strings will change with the next update.

**Comment by elfl0rd** [comment]
all noted strings still exists at crowdin :)

**Comment by elfl0rd** [comment]
Closed 4d ago, strings still exists at crowdin... :D

**Comment by elfl0rd** [comment]
Closed 9d ago, strings still exists at crowdin... :D
