### ISSUE TITLE
Need to clamp this floatingtext UI to stay inside the screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14997]
![image](https://user-images.githubusercontent.com/3536496/75944002-8aea2d00-5ed1-11ea-9d94-943732a7928f.png)

Ideally it just calls a 'ClampToScreen' util function and nudges it inside the screen.  I thought we had something like that but couldnt find it.  Can you help? Thanks!

Code is on FloatingText

**Comment by beastyn** [comment]
still off screen
![bandicam 2020-04-20 11-46-14-466](https://user-images.githubusercontent.com/27898520/79721907-94eab280-82fc-11ea-9494-390e643ef306.jpg)
