### ISSUE TITLE
Mortared Stone Door Needs Limestone, Sandstone, Granite Skins

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15005]
as a mason i can craft the following in the four Main Blocks (Basic Mortared Stone, Granite, Limestone and Sandstone)
![snap6406](https://user-images.githubusercontent.com/29383891/75998488-d401a780-5ef8-11ea-9524-92a64b263ff6.png)
![snap6399](https://user-images.githubusercontent.com/29383891/75998517-dcf27900-5ef8-11ea-975d-463350fe83a8.png)
![snap6400](https://user-images.githubusercontent.com/29383891/75998521-de23a600-5ef8-11ea-9bac-8ffb35104d26.png)
![snap6401](https://user-images.githubusercontent.com/29383891/75998524-de23a600-5ef8-11ea-8522-a12ac774f617.png)
![snap6402](https://user-images.githubusercontent.com/29383891/75998525-debc3c80-5ef8-11ea-9dd5-d6e39e119886.png)
![snap6403](https://user-images.githubusercontent.com/29383891/75998528-debc3c80-5ef8-11ea-91ed-87c36841cd0a.png)
![snap6404](https://user-images.githubusercontent.com/29383891/75998529-df54d300-5ef8-11ea-8cc5-94049b3de39a.png)

but the Mortared Stone Door is the base Mortared stoner which when designing your house looks out of place
![snap6407](https://user-images.githubusercontent.com/29383891/75998705-217e1480-5ef9-11ea-82b1-7f8ee37741f1.png)
as it has the same icon of the other objects just hoping this was an oversight and can have Granite, Limestone and Sandstone Textures

the door looks Great just hard to match in like the Other Blocks and furniture
![snap6405](https://user-images.githubusercontent.com/29383891/75998915-6efa8180-5ef9-11ea-846c-9a848cfc77ea.png)

**Comment by keegan-o** [comment]
Phlo, see if you can do the limestone, granite, and sandstone versions of this asset!

**Comment by Phlo123** [comment]
Added Limestone, Granite and Sandstone Albedo's in Working folder (Working\World Objects\Housing Objects\Mortared Stone Doors). In the asset folder these is a .psd that contains all wood/stone types in case someone wants another material combination.
![1](https://user-images.githubusercontent.com/17730996/90112446-aac32e00-dd58-11ea-9b05-6b16917a84f2.gif)
