### ISSUE TITLE
[0.9.0-1445] Recipe sand - static

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#15007]
Recipe sand of rocker box - static.
![изображение](https://user-images.githubusercontent.com/13696708/76008712-2787eb80-5f21-11ea-99e4-76a246ac31bf.png)

**Comment by WeaselDog** [comment]
Thanks for catching this. It will be fixed in next update.

**Comment by SlayksWood** [comment]
Seems still static
