### ISSUE TITLE
0.9 (feedback) components in tooltip

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15003]
This section considerably increases the size of the hint, but at the same time it practically does not carry valuable or easily perceived information. In my opinion, it needs to be removed.

![изображение](https://user-images.githubusercontent.com/4980243/75994147-8e9aa580-5f0b-11ea-9562-f94cb58e50cb.png)

**Comment by johnkslg** [comment]
Hm probably right.
