### ISSUE TITLE
New Lumber Stockpile and Large Lumber Stockpile need code support to implement

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15009]
We have our new stockpile object prefabs and they're even in the tech tree-- now we just need them to function correctly as 8x8x8 and 10x10x10 size stockpiles. I set the numbers I saw exposed on the prefab to those but I am not sure what that controls. I believe they are also set correctly in the tech tree to be those sizes, but clearly more is taken care of in custom code for the stockpiles, which needs to be setup.

![image](https://user-images.githubusercontent.com/14983165/76026202-2c2daf00-5ee3-11ea-8943-7607835d7399.png)

For any support needed with art or tech tree check in with @WeaselDog @Sekor2600 , and @keegan-o

**Comment by mirasrael** [comment]
Added support for outline and vertical offset.
