### ISSUE TITLE
Room requirements still have weird behavior

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1500]
I'm unable to take screenshots in game right now, which is unfortunate; but say a wall of my room from top down looked like this, with x's being wood and o's being windows, and the d being a door:

```
xoxdxox
x     x
```

The room was not considered valid.  I filled in both windows and then it was considered valid.  Then I tried cutting out the window on the left again, and the room was still considered valid.  I cut out the window on the right, and then the room broke.  I filled back in the window on the right (a setup which had just been considered valid), and the room was still invalid.

So the same exact room can be considered valid or invalid depending on the construction order.  Maybe a matter of not refreshing the rooms in all the necessary circumstances?

**Comment by craig-jong** [comment]
should be fixed already - will see with new build

**Comment by craig-jong** [comment]
Now they don't play very well with world object blocks; I shall investigate this
