### ISSUE TITLE
[0.9.0] Wrong collision for new animal statues and stuffed animals.

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#15006]
If you install a statue of a bison near the wall, then the edges of the bison come out.

![изображение](https://user-images.githubusercontent.com/13696708/76005718-7a12d900-5f1c-11ea-83e5-00337bc9a5fc.png)

**Comment by SlayksWood** [comment]
> ![изображение](https://user-images.githubusercontent.com/4980243/76907392-265aa500-68b7-11ea-91d3-147da054d786.png)
