### ISSUE TITLE
[0.9.0 staging-1447] Craft UI: need to check icons' size

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15014]
1. Now this order icons look like eggs with pixels. We need to make them with proper size
![bandicam 2020-03-06 12-12-02-112](https://user-images.githubusercontent.com/27898520/76061032-6f9c2200-5fa4-11ea-93bb-b51e74cd9d72.jpg)
![bandicam 2020-03-06 12-12-17-682](https://user-images.githubusercontent.com/27898520/76061034-70cd4f00-5fa4-11ea-9b96-8386a8c607bf.jpg)
2. There is somw artifact
![bandicam 2020-03-06 12-12-17-682](https://user-images.githubusercontent.com/27898520/76061317-0ff24680-5fa5-11ea-8df4-2e49093639dd.jpg)
3. Can we change this effect for selected order?
Maybe some border effect, its too much like this
![bandicam 2020-03-06 12-34-47-350](https://user-images.githubusercontent.com/27898520/76062141-e5a18880-5fa6-11ea-88c6-4fef840dbaba.jpg)

**Comment by johnkslg** [comment]
We can probably either shrink the graphic used, or turn on mipmaps of some kind.
(it no longer zooms, though maybe some day we will want that still)

**Comment by johnkslg** [comment]
Fixed all!
