### ISSUE TITLE
[0.9.0-1445] Can't insert module Campfire cooking upgrade

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#15010]
Campfire Can't accept plugin module Campfire cooking upgrade.
![изображение](https://user-images.githubusercontent.com/13696708/76026171-52813800-5f3f-11ea-8873-909df01d5323.png)

**Comment by WeaselDog** [comment]
Thanks for your report. We have a fix in place that will be in the next build.
