### ISSUE TITLE
Recipe name should have tooltip

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15016]
For now, _recipe_ hind available at 3rd nesting lvl
![изображение](https://user-images.githubusercontent.com/4980243/66808549-2afbe580-ef34-11e9-9d8b-bebbbbab21fb.png)
Can we have it directly at recipe name in interface?
![Безымянный](https://user-images.githubusercontent.com/4980243/76061393-7ae75180-5f94-11ea-9917-abb432298d9a.png)

**Comment by SlayksWood** [comment]
merged to #13334
