### ISSUE TITLE
[0.9.0 staging-1447] Can't cancel project With RMB by icon

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15013]
Step to reproduce:
- start orders:
![image](https://user-images.githubusercontent.com/45708377/76059228-53da5100-5f8f-11ea-96a3-44dade24aaf7.png)
- try to cancel it. I haven't any way.

**Comment by Astrija** [comment]
Maybe can add button "pause" for project? Not only button "cancel"

**Comment by johnkslg** [comment]
Fixed!
