### ISSUE TITLE
[Playtest] [0.9.0.0 beta staging-1445] Stuck for 20-30 minutes on loading world

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#15026]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4301872/Player.log)

Loading the world got stuck at 80%, 91%, 96% for a total of 29 minutes

**Comment by Zoneman81** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4301923/Player.log)

**Comment by Zoneman81** [comment]
player-prev.log is more then 50mb, so too large
Dropbox link: [https://www.dropbox.com/s/lhklemflbf76zmx/Player-prev.log?dl=0](url)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/14910
