### ISSUE TITLE
0.9 ecopedia background make text hard to read.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15029]
![изображение](https://user-images.githubusercontent.com/4980243/76145072-28428e00-6097-11ea-88e4-a98486cb60f5.png)

**Comment by MilenkoTunjic** [comment]
Sergey, Can we try to drop opacity of the diagonal tiled background down to about 20 percent of what it is now, so it is much more subtle?
Alternatively, I can always change that sprite to something else (different pattern or whatnot) but it is used in other places so it will affect it across its use

**Comment by MilenkoTunjic** [comment]
OK, I tweaked the sprite, perhaps that is the easiest solution, and I can continue tweaking it until it looks right

**Comment by johnkslg** [comment]
Fixex

**Comment by elfl0rd** [comment]
Already at staging?
