### ISSUE TITLE
USER ISSUE: Grass changed to biome-related blocks

### ISSUE THREAD

**Issue by Villerger27** [StrangeLoopGames/EcoIssues#15020]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Go to a biome that has sand or a different grass/dirt texture
2. Type in /level above the ocean level 
3. Wait

**Expected behavior:**
it should've done nothing

**Actual behavior:**
Instead it changed the grass to a different block. E.g. in an ocean it changed grass to sand

**Do you have mods installed? Does issue happen when no mods are installed?: "I have one mod installed but I will try it out without the mod"**
Instead it changed the grass to a different block. E.g. in an ocean it changed grass to sand or stone.

**Comment by Villerger27** [comment]
I am on 0.8.3.3

**Comment by SlayksWood** [comment]
Seems it's intended behavior for now.
@mirasrael 
Is this intended behavior?

**Comment by mirasrael** [comment]
Yes  it is intended
