### ISSUE TITLE
0.9 no icon for "misc"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15027]
**Version:** 0.9.0.0 beta staging-1449
(how close you can approach animals, maybe this perk can have own icon?)
![изображение](https://user-images.githubusercontent.com/4980243/76144897-aa31b780-6095-11ea-9662-ad0f5bdd4670.png)

**Comment by SlayksWood** [comment]
Seems this icon looks wrong for Survivalist Misc or we should separate this skill to 2 different.
Also 0,25 kg bigger than icon.
![image](https://user-images.githubusercontent.com/45708377/79108475-17b0c200-7d7f-11ea-97f2-2aab97d64e6e.png)

**Comment by mirasrael** [comment]
@keegan-o we need to have an icon for "Misc" which doesn't match any specific bonus or professions. Any ideas?

**Comment by elfl0rd** [comment]
Maybe better - split this misc into separate icons?

**Comment by keegan-o** [comment]
Rob we need this icon, it represents a lot of different possible upgrades to yourself you can pick from in the skill tree. Eventually we'll get unique icons per choice but considering how much talents and such need renovation from the ground up, let's just do the 'Misc' one for 9.0.

**Comment by RobertMangano** [comment]
Icon is made on icon sheet 04, however I cannot find it on the list in the eco scene items

**Comment by WeaselDog** [comment]
@serpopov Now that we have an icon, can you plug this in?
