### ISSUE TITLE
Linux server: no docker image tagged as latest

### ISSUE THREAD

**Issue by mwander** [StrangeLoopGames/EcoIssues#15025]
[This guide](https://github.com/StrangeLoopGames/EcoIssues/wiki/EcoServer-on-Linux) tells me to use the following command to download a docker image:
`docker pull strangeloopgames/eco-game-server`

This command does not work:

> $ sudo docker pull strangeloopgames/eco-game-server
Using default tag: latest
Error response from daemon: manifest for strangeloopgames/eco-game-server:latest not found

**Comment by mirasrael** [comment]
Added tag `latest` for 0.8.3.3-beta. @redwyre we should create separate task in Jenkins for publishing release which will include `latest` tag creation. We can't do it together with release build, because usually we have pre-test for release before publishing it.

**Comment by redwyre** [comment]
I'll mark this one as done as it's working in the deploy script
