### ISSUE TITLE
[0.9.0-staging-1445] Menu screen bird whistling/background noise not playing

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15022]
The bird whistling and generic background noise on the main menu screen is non existent in 0.9.0 Staging 1445, is present in 8.3.3

**Comment by MishkaFur** [comment]
Oddly seemed the music started after around 2 hours of being ingame.

**Comment by SlayksWood** [comment]
Can you add some video? and please provide your Audio Settings.

**Comment by MishkaFur** [comment]
It is working now, audio settings were all 100% other than UI which was 50%.

Will test on a different computer this evening UK time.

This PC is Win 10, Ryzen CPU and Realtek audio card
