### ISSUE TITLE
[0.9.0-staging-1445] Web elections: title election won't disappear

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15023]
1. Create elected title
2. Create an election process, where you can be a vetoer
3. Start election for title
4. Veto it,

Election will be vetoed but wou still can see it on the web 
![bandicam 2020-03-07 02-51-36-076](https://user-images.githubusercontent.com/27898520/76125698-2f2dba00-601f-11ea-93f9-c49c2c72c0de.jpg)
![bandicam 2020-03-07 02-51-56-751](https://user-images.githubusercontent.com/27898520/76125702-30f77d80-601f-11ea-935c-70786a1a4925.jpg)
![bandicam 2020-03-07 02-55-46-242](https://user-images.githubusercontent.com/27898520/76125705-31901400-601f-11ea-827a-9224e0c6d11a.jpg)

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/76210381-fcfaa300-623e-11ea-9b5d-1ecc22f963b9.png)

Also made elections say when they were vetoed, and displayed votes while I was in there (including anonymous names if set in election process)
![image](https://user-images.githubusercontent.com/3536496/76210337-e2282e80-623e-11ea-8e2b-7760638c7a18.png)
