### ISSUE TITLE
(Balance) Headshot should provide x2.5 experience than regular hit

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15032]
For now, hit and headshot provide same experience.

**Comment by SlayksWood** [comment]
Experience must be given for the damage done like for chopping trees.

**Comment by ThePiachu** [comment]
The UI doesn't seem to display the XP gain to be bigger. Whether you hit the animal normally or headshot, you still get a popup saying +1:
![image](https://user-images.githubusercontent.com/964559/95932744-89df7f00-0d81-11eb-886e-337f4b174aca.png)

Tested it a little, got the same amount of XP from a turtle body shot and a jaguar headshot. Something doesn't appear to be working from what I can see...
