### ISSUE TITLE
0.9 new interface lost "turn on" checkbox at any object with enabled\disabled state

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15039]
0.8
option there
![изображение](https://user-images.githubusercontent.com/4980243/76160523-e7508500-613b-11ea-9767-1afb61c845bf.png)

0.9
no option
![изображение](https://user-images.githubusercontent.com/4980243/76160686-59759980-613d-11ea-93c6-828c4f79a604.png)

**Comment by MishkaFur** [comment]
I believe it has moved to the red dot top left but this is a known issue with it not working at the moment, affects lighting

**Comment by mirasrael** [comment]
Applies only to world objects with OnOffComponent

**Comment by mirasrael** [comment]
Let on/off with click on light (red/green)

**Comment by mirasrael** [comment]
@keegan-o do you have any ideas about may be something like like switch or another kind of switch for this?

**Comment by SlayksWood** [comment]
Overlap, need position in UI for this button:
![image](https://user-images.githubusercontent.com/45708377/81039416-9ea21780-8eb1-11ea-8cfc-efb8103b37e7.png)
May be just add button in Status tab?
![image](https://user-images.githubusercontent.com/45708377/81039308-58e54f00-8eb1-11ea-8ae2-d365fef64f69.png)
or we can add special window near bulb:
![image](https://user-images.githubusercontent.com/45708377/81039377-87632a00-8eb1-11ea-980b-c65cb31775b4.png)
But need to take in account that we have different UI for different type of table (wood, metalic, brick and etc.)
![image](https://user-images.githubusercontent.com/45708377/81039531-fb053700-8eb1-11ea-8b80-c59197c38a29.png)

**Comment by elfl0rd** [comment]
Or maybe there
![изображение](https://user-images.githubusercontent.com/4980243/81040368-e2961c00-8eb3-11ea-9200-bd48b3bd7491.png)

**Comment by gzatravkin** [comment]
moved below right/green light

**Comment by SlayksWood** [comment]
It is displayed on all crafted tables now, even where it isn't needed:
![image](https://user-images.githubusercontent.com/45708377/81258430-53693f80-903e-11ea-9213-c73cec43461b.png)

**Comment by elfl0rd** [comment]
> even where it isn't needed

I believe that the ability to shut down any machine would be in great demand.
So instead of removing this option from mechanisms without the ability to turn off, please modify it to shutdown everything where it exists.

**Comment by gzatravkin** [comment]
@elfl0rd this sounds like feature. 
I will fix this issue with 8 behavior. Shudowning of everything may lead to another problems, so I prefer to have it as another issues

**Comment by trickenso** [comment]
> I believe that the ability to shut down any machine would be in great demand.

Would be interested in the use case for this feature.

What benefit also being able to shut it down? When would you want to pause a task that has resources and labor? If it doesn't have those things it is functionally shut down anyway, and if it does you presumably want it to be functional.

**Comment by beastyn** [comment]
@gzatravkin yeap, just remove from the objects without onoff component.
