### ISSUE TITLE
[0.9.00 beta staging-1449] Enter Election not possible in ballot box

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#15036]
While joining an election as candidate the field "speech" is not accessable to enter any text, therefore you cannot enter the election.
![image](https://user-images.githubusercontent.com/47274045/76152688-a9634a80-60c2-11ea-963f-c3fc4668fc19.png)

**Comment by johnkslg** [comment]
Fixed via direct checkin to staging (need for stream)
