### ISSUE TITLE
0.9 static highlight for moving plants.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15030]
Happens if you look trough another plant.

![20200307171151_1](https://user-images.githubusercontent.com/4980243/76145085-47412000-6097-11ea-9ff3-2a12c034bd3a.jpg)
![20200307171927_1](https://user-images.githubusercontent.com/4980243/76145140-e0703680-6097-11ea-8b88-921cdd32a738.jpg)

**Comment by SlayksWood** [comment]
dup #14377
