### ISSUE TITLE
USER ISSUE: error 500

### ISSUE THREAD

**Issue by darksise** [StrangeLoopGames/EcoIssues#15037]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
connecte to a serveur

**Expected behavior:**
i can't join all serveur

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connexion échouée</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Comment by beastyn** [comment]
@darksise did you manage to connect?

**Comment by darksise** [comment]
no

**Comment by beastyn** [comment]
@darksise 
Lets start with some wuestions then.
1. Can you see servers in list normally? With ping and server info?
2. Do you have Firewall or Antivirus enabled?
3. Which kind of internet connection are you using?
4. Please provide your PC specification (include Operating System).
5. Did you meet this issue after updating to the "latest build" or you had it before?
6. How do you launch you client: from Steam ot from a folder?

**Comment by darksise** [comment]
1 je peux voir les serveur normalement avec ping ...
2 j'utilise windows defender je vien d'essayer d'enlever le firewall et sa ne marche pas
3 je suis chez bouygue avec un router
4 https://www.driverscloud.com/fr/configuration/62458468-1/resume
5 I had this problem on my old pc and on the new one 6 months ago
6 I start my game from steam

**Comment by darksise** [comment]
1 I can see the server normally with ping ...
2 I use windows defender I just tried to remove the firewall and it does not work
3 I'm at bouygue with a router

**Comment by D3nnis3n** [comment]
Can you send me your SLG username?

**Comment by darksise** [comment]
my pseudo steam is darksisex

**Comment by darksise** [comment]
and my pseudo eco is darksise

**Comment by D3nnis3n** [comment]
You had an issue in the account database, the issue should be fixed.

**Comment by darksise** [comment]
thank you very much i love this game thank you
