### ISSUE TITLE
[0.9.00 beta staging-1445]  odd text on removal of Amendment notice

### ISSUE THREAD

**Issue by rsdworker** [StrangeLoopGames/EcoIssues#15035]
when i removed the amendment from amendent because my mistake and noticed this notice popped up with very odd texts on it

its shouldnt not show odd text just show the Amendment 1 removed on popup

![issue](https://user-images.githubusercontent.com/6688223/76152414-37d1cf00-60b7-11ea-82c4-61894f6095fa.png)

**Comment by SlayksWood** [comment]
Step to reproduce:
create Сonsitutional Amendments article that you can add/remove Articles immediately: 
![image](https://user-images.githubusercontent.com/45708377/76158233-c3ce1000-6124-11ea-9665-bc83f4ecba02.png)
- add another any another article and delete it:
![image](https://user-images.githubusercontent.com/45708377/76158248-e06a4800-6124-11ea-99c2-5919ea3a9598.png)
- press  "Yes":
![image](https://user-images.githubusercontent.com/45708377/76158253-ec560a00-6124-11ea-9ced-9330b693bb6a.png)
