### ISSUE TITLE
[Minor] 9.0: Items put into almost full storage instead of carried stuff

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15031]
**Version:** 0.9.0.0 beta staging-1445

**Steps to Reproduce:**
Fill Cart so no more stone will fit in
select an item in your toolbar
pick up a stack of stone (not from the cart ;))
try to put the stones into the cart

**Expected behavior:**
Error for full storage

**Actual behavior:**
Selected item is stored instead

**Comment by SlayksWood** [comment]
dup #14911
