### ISSUE TITLE
0.9 work order timer issue

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15034]
staging-1449

if you have multiple workorders, timers at workorders next at active, tick with active one.
![20200307210336_1](https://user-images.githubusercontent.com/4980243/76150065-4d46f900-60b7-11ea-8e37-9e81cde08ee0.jpg)
![20200307210347_1](https://user-images.githubusercontent.com/4980243/76150066-4f10bc80-60b7-11ea-989d-ab7790e2e536.jpg)
![20200307210351_1](https://user-images.githubusercontent.com/4980243/76150068-5041e980-60b7-11ea-87dc-dedf80cfe562.jpg)

https://youtu.be/OJonLnscg5g

**Comment by johnkslg** [comment]
Fixed, thanks!
