### ISSUE TITLE
0.9 clay no more "sticky"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15043]
![20200308143116_1](https://user-images.githubusercontent.com/4980243/76162047-5f25ac00-614a-11ea-8732-8abd4c7c768d.jpg)
![20200308143118_1](https://user-images.githubusercontent.com/4980243/76162048-60ef6f80-614a-11ea-8844-1427ff5a5b7c.jpg)

**Comment by MishkaFur** [comment]
Adding more information

Clay does not stick to other blocks anymore and it falls to the ground like dirt does, unsure if this is an intended bugfix or not.

**Comment by Sekor2600** [comment]
intended

**Comment by elfl0rd** [comment]
why's intended? At 0.8 clay was sticky on purpose, just look at her model.
What reason for change that?

**Comment by mirasrael** [comment]
Because it is not much different from Dirt as substance. So no reason to behave differently.

**Comment by mirasrael** [comment]
Ah. I see what you mean. Just hard to get it from description. You mean connection to other blocks.

**Comment by mirasrael** [comment]
Checked, works as intended.
