### ISSUE TITLE
Graphs not showing lines

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15045]
![image](https://user-images.githubusercontent.com/3536496/76163311-f35e3600-617f-11ea-88da-674bd90e353a.png)

**Comment by denysaw** [comment]
Need more info to reproduce. Can you please give me world save to test with? Cuzz for my world lines are working:
![image](https://user-images.githubusercontent.com/5720101/76430010-1bcc7700-63b0-11ea-82d9-392988f989ec.png)

**Comment by johnkslg** [comment]
Oh maybe there was just one data point...  It should be setting a datapoint on load, perhaps its not.  Quadbro can you take a look?
