### ISSUE TITLE
[0.9.0 Staging-1445] New government items incorrect sizes shown

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15041]
Capitol says it is 3x1x3 but it is actually 3x3x3, though model looks like it is only 2 high it will not fit into a 2 high room

Zoning office says it is 1x1x2 though the top of it is just over 1 block
Ballot box correctly says it is 1x1x2 though and visually has same height as zoning office

Court says it is 1x1x3 but is 6 wide, 3 high and 6 deep
Government Office should be 4x3x4
Executive office should be 3x2x3
Board of elections should be 4x3x2
Census Bureau should be 3x2x3
Amendments should be 3x3x3

**Comment by beastyn** [comment]
megers #13864
