### ISSUE TITLE
Was swimming and got booted from the server

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15049]
[error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4303320/error.txt)

**Comment by beastyn** [comment]
@Zoneman81
1. What game version do you use?
2. Was you able to reconnect?
3. Was this error repeated or just happened once?

**Comment by Zoneman81** [comment]
1. ver 9 - playtest server
2. Yes
3. only happend this once

**Comment by beastyn** [comment]
@Zoneman81 
Thank you for the additional info.
Did you do something special? Was you underwater or on top?

**Comment by Zoneman81** [comment]
I was under water, hunting fish with a bow and arrows

**Comment by SlayksWood** [comment]
closed as not reproducible. If it happens again please reopen and provide log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
