### ISSUE TITLE
Graph failed to attach when adding comment

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15046]
![image](https://user-images.githubusercontent.com/3536496/76163345-34564a80-6180-11ea-8e28-6775b90d83eb.png)
This comment had both a map and a graph, but only one showed.

**Comment by denysaw** [comment]
There was JS error of showing server error. Now we can see server error clearly:
https://media.discordapp.net/attachments/660199489340178433/687307578182467675/unknown.png?width=725&height=102

Such error appears for any graph category/data used.
Please, pull above request to see errors normally. And switching issue into serverSide one.

**Comment by denysaw** [comment]
Thanx @Quadbro for finding out about wrong Graph Key data format. Created PR: https://github.com/StrangeLoopGames/Eco/pull/5775

**Comment by beastyn** [comment]
Graph was saved with ibcorrect data
Created like this
![bandicam 2020-03-19 11-16-51-525](https://user-images.githubusercontent.com/27898520/77037521-61ea9180-69d3-11ea-85ac-231fc8867c37.jpg)

After submitting like this
![bandicam 2020-03-19 11-17-59-568](https://user-images.githubusercontent.com/27898520/77037540-6a42cc80-69d3-11ea-9c99-fe2a1eb9f59e.jpg)

@Quadbro is it what you are fixing?

**Comment by SlayksWood** [comment]
so it's still an issue. It adds only one line of species

**Comment by Quadbro** [comment]
Seems like on posting it sends only one first graph values, @denysaw can  you look?

**Comment by denysaw** [comment]
@Quadbro Yep, really. Fixed here: https://github.com/StrangeLoopGames/Eco/pull/5842
