### ISSUE TITLE
0.9 X more needed calculated incorrect

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15050]
just look, 34 craft req 12 carcasses.
But in work order tooltip, you see "a little" different information.
![20200308184246_1](https://user-images.githubusercontent.com/4980243/76166076-c9e7df00-616c-11ea-8809-5a4841e941ff.jpg)

**Comment by johnkslg** [comment]
Is that from modules added?
@olegshegai can you make it consider module contribution in these numbers

**Comment by elfl0rd** [comment]
yep, module and used "craft resource modifier"
