### ISSUE TITLE
[0.9.0 staging 1445] Brightness control only works during daylight

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15055]
Brightness slider only works during the sunlight/daytime hours, overnight it does not change at all

**Comment by elfl0rd** [comment]
afaik it's intended, use light sources at night.

**Comment by MishkaFur** [comment]
brightness should still be able to be adjusted via the game settings regardless of day or night cycle, it's a graphics setting .
