### ISSUE TITLE
USER ISSUE: vfeskocxz,cipmwel[ 

### ISSUE THREAD

**Issue by daniel324324** [StrangeLoopGames/EcoIssues#15058]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
M, CSHK\WDWM 0OEM,EW SJP][K RG0IACSKAP=WA;cvso-92ea7c]PSN3G54Y3BWAW,\o- 9cj

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Comment by elfl0rd** [comment]
Buy license copy.
