### ISSUE TITLE
[0.9.0 staging-1445] Repairing tool doesnt show actual item needed

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15052]
Repairing a tool in tool bench does not say what is actually needed to repair it, hovering over does not say anything though can see a number

![image](https://user-images.githubusercontent.com/61889138/76168145-aae54f00-6164-11ea-9bc5-6913c8198ce7.png)

**Comment by elfl0rd** [comment]
Duplicate of #13839

**Comment by MishkaFur** [comment]
Closing as duplicate by mistake
