### ISSUE TITLE
Thank you for your Korean support, but I have another request.

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#15064]
If you enter a terminal vowel, 

???????
There's a phenomenon that comes out.

In the game, for example, 

This is what happens when you chat.

ㅋㅋㅋㅋㅋㅋㅋ -> ???????
ㅎㅎㅎㅎㅎㅎㅎ -> ???????
감사합니다ㅋㅋ -> 감사합니다 ??
안녕하세요ㅎㅎ -> 안녕하세요 ??

Please check it out!

**Comment by SlayksWood** [comment]
It seems the font doesn't support all korean characters.
@gzatravkin 
If you have any question ask @Quadbro

**Comment by SlayksWood** [comment]
@StoryNine 
Does It happen only with chat?

**Comment by StoryNine** [comment]
> @StoryNine
> Does It happen only with chat?

The other word is fine.

Only the letters that look like this are problematic.

ㅋ,ㅎ,ㅅ,ㅠ,ㅜ,ㅇ,ㅍ

I think it would be nice if you could add the fonts I write.

ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.

ㅏ, ㅐ, ㅑ, ㅒ, ㅓ, ㅔ, ㅕ, ㅖ, ㅗ, ㅘ, ㅙ, ㅚ, ㅛ, ㅜ, ㅝ, ㅞ, ㅟ, ㅠ, ㅡ, ㅢ, ㅣ.

ㄱ, ㄲ, ㄴ, ㄷ, ㄸ, ㄹ, ㅁ, ㅂ, ㅃ, ㅅ, ㅆ, ㅇ, ㅈ, ㅉ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ.

**Comment by gzatravkin** [comment]
Fixed by SVN changes

**Comment by StoryNine** [comment]
> Fixed by SVN changes

Is it applied immediately?
if not
Does it apply to the 9.0 patch?

**Comment by gzatravkin** [comment]
It will appear at 9.0, no immediate fix for previos versions
