### ISSUE TITLE
[0.9.0 staging-1455] Creating Work Party with nonexistent order

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15069]
Step to reproduce:
- create 2 order:
![image](https://user-images.githubusercontent.com/45708377/76309123-2964fc80-62dd-11ea-92ef-f05ab87726d5.png)
- start to create WorkParty:
![image](https://user-images.githubusercontent.com/45708377/76309144-3550be80-62dd-11ea-9be9-9b256eab26f3.png)
- I have draft with 2 orders.
- delete one of two order:
![image](https://user-images.githubusercontent.com/45708377/76309204-544f5080-62dd-11ea-814a-de7f6943c595.png)
- I have one order Icon in top right corner. 
- Open WorkParty Draft:
![image](https://user-images.githubusercontent.com/45708377/76309264-7fd23b00-62dd-11ea-8b50-eab5c138bcf2.png)
- I still have Capitol Projects here. It should be deleted with cancelling order.
- press post:
![image](https://user-images.githubusercontent.com/45708377/76309347-adb77f80-62dd-11ea-975b-9034e153d6a2.png)
- I have WorkParty wit nonexesting order. I also has icon fo nonexesting order in top right corner.

**Comment by johnkslg** [comment]
Should be fixed but double check.
