### ISSUE TITLE
0.9 multiple recipes in one is still annoying

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15062]
like previous version of butchery... #14248 
just look.
I have 4 charred meat and 8 charred mushrooms.
![изображение](https://user-images.githubusercontent.com/4980243/76212534-be062680-6219-11ea-8a9c-cfe811ef9037.png)

game show me a lot of craftable stew's.
![изображение](https://user-images.githubusercontent.com/4980243/76212642-fb6ab400-6219-11ea-8d68-3192fe6fa0de.png)
(43 in this case)

Ok, let's try craft 10...

![изображение](https://user-images.githubusercontent.com/4980243/76212737-3371f700-621a-11ea-9f2f-5fd53f19ae5b.png)
huh... i dont have ingridients... but what if i miss my ingridients quantity?
lets select one.
![изображение](https://user-images.githubusercontent.com/4980243/76212765-3ff64f80-621a-11ea-9e8c-952def12c65e.png)

No ingridients.
![изображение](https://user-images.githubusercontent.com/4980243/76212861-746a0b80-621a-11ea-9ab5-d37eaec66a0e.png)

Annoying.

**Comment by elfl0rd** [comment]
As i think, all "compacted" recipes, should be expanded back.

As normal solution - filters, search and checkbox "can be crafted" please :)

**Comment by MishkaFur** [comment]
What could be good on the multiple option recipes is a quantity field on the popup rather than having to do it on the first screen THEN hit the cog

**Comment by elfl0rd** [comment]
> What could be good on the multiple option recipes is a quantity field on the popup rather than having to do it on the first screen THEN hit the cog

In this case, you need open submenu to see how many you can craft.

**Comment by WeaselDog** [comment]
I am fixing this as part of https://github.com/StrangeLoopGames/EcoIssues/issues/14852
