### ISSUE TITLE
[0.9.0 Staging 1445] Mortared Stone Door Lets Water in

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15063]
**Version:** 0.9.0.0 beta staging-1445

![snap6431](https://user-images.githubusercontent.com/29383891/76243757-bef68280-6230-11ea-8220-7b6c2737cf1a.png)

Old Stone doors used to keep water out, so not sure if this intended Behavior now
couldnt test Hewn Log Door as only have Masonry

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1455:
![image](https://user-images.githubusercontent.com/45708377/76296126-cc5e4c00-62c6-11ea-834a-28265c5a5022.png)
![image](https://user-images.githubusercontent.com/45708377/76296157-d3855a00-62c6-11ea-8ee1-f00cc2db0060.png)

**Comment by SlayksWood** [comment]
And we have wrong occupancy with dirt:
![image](https://user-images.githubusercontent.com/45708377/76302215-a5a51300-62d0-11ea-8f92-addffb968fed.png)
Maybe related with #14808

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/78215613-9294f580-74c0-11ea-94d3-0e204217f4f3.png)
