### ISSUE TITLE
0.9 "Done" workorder icon stay at table for long time after crafting finished.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15065]
**Version:** 0.9.0.0 beta staging-1455
![20200310100504_1](https://user-images.githubusercontent.com/4980243/76288002-c8c2c900-62b6-11ea-940e-d6ad5ec1b05e.jpg)
![20200310100510_1](https://user-images.githubusercontent.com/4980243/76288006-cceee680-62b6-11ea-9e4c-c7dbd2d6cecf.jpg)

**Comment by SlayksWood** [comment]
Step to reproduce:
- Start 2 same order:
![image](https://user-images.githubusercontent.com/45708377/76292056-7d60e880-62bf-11ea-97e7-f3dc18046d3b.png)
- add labor and resources to them:
![image](https://user-images.githubusercontent.com/45708377/76292096-949fd600-62bf-11ea-88a3-a08073f676b5.png)
- wait when first order will finish. It should change icon for second order but I see icon for first as Done:
![image](https://user-images.githubusercontent.com/45708377/76292227-db8dcb80-62bf-11ea-941f-0cab07e51d0f.png)

**Comment by johnkslg** [comment]
Fixed both issues here:
- Work Orders only stay as 'done' if they're waiting to be collected now. If they go straight into storage, it removes it immediately.
- The marker shown now prefers the active work order.
