### ISSUE TITLE
[0.9.0 staging-1455] Craft: need a cross for an order cancelling

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15068]
Somewhere here shoud be a cross for cancelling
![bandicam 2020-03-10 16-44-36-561](https://user-images.githubusercontent.com/27898520/76309420-90d77800-62ee-11ea-8f60-44c45baf0790.jpg)

**Comment by elfl0rd** [comment]
and pause button! please :P
