### ISSUE TITLE
Character progress lost

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15061]
Zoneman reported loosing character progress (XP, learned skills) on the playtest server, effectively loosing the progress from sunday. Server was neither rollbacked, no backup restored, everything built is still there. No errors in the logs.

**Comment by Zoneman81** [comment]
Logged out around 2am(GMT+1), i had food sp 59,1, house sp 35,6 - I had 3 skills taken, Campfire Cooking at lvl 6, Farming at lvl 6 and Gathering at lvl 4.
Logged in again at 7am(GMT+1), noticed that my food sp was at 26,2 and almost running out of calories, house sp unchanged, work that had been queued before i logged out was made.
Noticed that i no longer had Gathering as a skill, Campfire cooking was at lvl 4 and so was Farming
I checked my XP status for next star and it said 1 hour, last time it said 1 hour left was sunday at 8pm(GMT+1).
My waypoints are also lost, i had quite alot when i logged out, about 20

**Comment by mirasrael** [comment]
@Zoneman81 did you or someone else have such problem in last few weeks?

**Comment by Zoneman81** [comment]
No issues in the last weeks

**Comment by mirasrael** [comment]
Closed it for now then. Let us know if problem re-appear. Thanks for report!
