### ISSUE TITLE
[0.9.0 staging-1455] Marker information in WorkParty is wrong upgrade when you delete order.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15067]
Step to reproduce:
- create Work Party with Hewn Chair, Distribution Station and Contract Board.
- add some resources and labor and cancel 2 projects:
![image](https://user-images.githubusercontent.com/45708377/76306746-8316f800-62d8-11ea-913e-356af6113b3b.png)
- For Hewn chair I need 30 NaturalFiber and 10 Hewnlog, but marker info said that I need 30NaturalFibers and 5 HewnLog, 5 WoodBoard (this 2 Items we didn't add to Distribution station project). Also I only need labor for Hewn Chair project, but it said that I need labor for cancelled projects too:
![image](https://user-images.githubusercontent.com/45708377/76308462-e6eef000-62db-11ea-9005-cfee4c2a163c.png)

**Comment by johnkslg** [comment]
Fixed!
