### ISSUE TITLE
[0.9.0 staging-1456] Icons displacement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15073]
Everywhere with the title icon seems to be on the wrong position
![bandicam 2020-03-11 11-06-00-501](https://user-images.githubusercontent.com/27898520/76390824-f0399480-638f-11ea-8974-1ee6c3537638.jpg)
![unknown (3)](https://user-images.githubusercontent.com/27898520/76390861-ffb8dd80-638f-11ea-80b8-eab1529314d6.png)
![bandicam 2020-03-11 12-01-56-492](https://user-images.githubusercontent.com/27898520/76390922-20813300-6390-11ea-9dd9-4f1ae9b6017a.jpg)

**Comment by SlayksWood** [comment]
Seems it's everywhere:
![image](https://user-images.githubusercontent.com/45708377/76395137-b8c6ea00-6387-11ea-94ec-26ab563ba478.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/76396041-8ddd9580-6389-11ea-8f23-72568dc392d3.png)

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/77916149-47e96280-72a1-11ea-942d-bd2b419f5f27.png)
