### ISSUE TITLE
Proposal that have already been voted on can be changed

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15075]
> Regarding propositions such as election process. Currently the initiator can edit it in the last few minutes without any penalty to the vote end time or cancelation of yes votes - this could be abused

This should not be possible and is highly abusable. A proposal should not be able to be changed when it already has votes.

**Comment by johnkslg** [comment]
Fixed, button removed when in election
![image](https://user-images.githubusercontent.com/3536496/76399277-4f5fcf00-63b9-11ea-95b0-4d92c22d12be.png)
