### ISSUE TITLE
Store can´t sell Clothing

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#15071]
In the Filter from Store nothing from Clothing techtree is displayed and not selectable

Example here Bearbackpack
![grafik](https://user-images.githubusercontent.com/37456949/76350414-ff76fe80-630b-11ea-9b92-df741651bce3.png)

**Comment by WeaselDog** [comment]
it is likely related to this https://github.com/StrangeLoopGames/EcoIssues/issues/14906
