### ISSUE TITLE
[0.9.0 staging-1456] Workparty markers overlap.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15076]
Create a few workparty in one Crafttable:
![image](https://user-images.githubusercontent.com/45708377/76395357-2e32ba80-6388-11ea-9d56-b684cdd18662.png)

**Comment by SlayksWood** [comment]
Maybe change it to 1 line?
![image](https://user-images.githubusercontent.com/45708377/78220842-f3293000-74ca-11ea-9024-0486848311df.png)
or maybe 2:
![image](https://user-images.githubusercontent.com/45708377/78221020-44d1ba80-74cb-11ea-9549-d2394136ce2d.png)
Currently it takes a lot of space:
![image](https://user-images.githubusercontent.com/45708377/78220930-19e76680-74cb-11ea-9ed0-2077a0891222.png)

**Comment by SlayksWood** [comment]
And it still overlap if you see in another side: 
![image](https://user-images.githubusercontent.com/45708377/78222546-199c9a80-74ce-11ea-916e-8d4171957948.png)

**Comment by SlayksWood** [comment]
Also overlap at big distance 2 workParty markers at 2 different craft tables
![image](https://user-images.githubusercontent.com/45708377/78240755-1b735780-74e8-11ea-9a7f-1a2edd1777ec.png)

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/15076, make a solution that can handle both cases
