### ISSUE TITLE
[0.9.0 staging-1445] Phantom "Done" workorder appears belonging to someone else after manually dropping in materials

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15081]
Another player creates a workorder and fulfils labour.
You open the workbench when authorised to use it and drop items from inventory/hand onto the order shown at the bottom.
Item completes and is sent to 'other players' linked storage.

Top right hand corner shows an invalid work order and the icon appears over the workbench requiring manual clearing with X in top right

Photograph shows the item and view on UI:
![phantom order](https://user-images.githubusercontent.com/54982803/76422252-cdfa4380-639c-11ea-8d1d-36983f6b75fa.png)

**Comment by SlayksWood** [comment]
Step to reproduce:
- first player place workbench, add any order and link storage:
![image](https://user-images.githubusercontent.com/45708377/76516355-55fb4e80-646c-11ea-891e-53d79681814f.png)
- second player add any resources or any labor.
- complete order.
- Order icon for first player (owner) will disapear:
![image](https://user-images.githubusercontent.com/45708377/76516783-1c771300-646d-11ea-8b89-524976a23100.png)
- Second player have Done icon.
![image](https://user-images.githubusercontent.com/45708377/76516919-5ba56400-646d-11ea-8e3f-901767fa4412.png)
