### ISSUE TITLE
Hide some icons from icon export utilitiy

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15088]
Make an attribute to stop some icons from exporting via the icon export tool.
QueryAction is the first one that can use that, it shouldnt have an icon as its an internal action.

**Comment by serpopov** [comment]
Missing icons full list:

FitTorsoItem
HumanLimbsItem
WideHipsItem
RoofsFormGroup
CrushedOilShaleItem
MortaredBasaltItem
MortaredGneissItem
MortaredShaleItem
AcornPackItem
AgaveSeedPackItem
AmanitaMushroomSporesPackItem
ArcticWillowSeedPackItem
BarrelCactusSeedPackItem
BeansPackItem
BeetSeedPackItem
BigBluestemSeedPackItem
BirchSeedPackItem
BoleteMushroomSporesPackItem
BullrushSeedPackItem
BunchgrassSeedPackItem
CamasBulbPackItem
CedarSeedPackItem
CeibaSeedPackItem
CookeinaMushroomSporesPackItem
CornSeedPackItem
CreosoteBushSeedPackItem
CriminiMushroomSporesPackItem
DwarfWillowSeedPackItem
FernSporePackItem
FilmyFernSporePackItem
FirSeedPackItem
FireweedSeedPackItem
GrassSeedPackItem
HeliconiaSeedPackItem
HuckleberrySeedPackItem
JointfirSeedPackItem
JoshuaSeedPackItem
KelpSeedPackItem
KingFernSporePackItem
LatticeMushroomSporesPackItem
LupineSeedPackItem
OceanSpraySeedPackItem
OrchidSeedPackItem
PalmSeedPackItem
PapayaSeedPackItem
PineappleSeedPackItem
PricklyPearSeedPackItem
PumpkinSeedPackItem
RedwoodSeedPackItem
RicePackItem
SaguaroSeedPackItem
SaxifrageSeedPackItem
SeagrassSeedPackItem
SpruceSeedPackItem
SugarcanePackItem
SunflowerSeedPackItem
TaroSeedPackItem
TomatoSeedPackItem
TrilliumSeedPackItem
VehicleToolItem
WaterweedSeedPackItem
WheatSeedPackItem
WhiteBursageSeedPackItem
LargeHangingWoodSignItem
LargeStandingWoodSignItem
SmallHangingWoodSignItem
SmallStandingWoodSignItem
AsphaltConcreteRampItem
Chef Specialty
Engineer Specialty
Excavation
Farmer Specialty
Mason Specialty
NotInBrowser
Product
Smith Specialty
Survivalist Specialty
Tailor Specialty
Clothes
NotAllowedInInventories
Climate
Liquid
Metal
Research
Constructable
AxeItem
BlastingChargeItem
BowItem
DrillItem
HoeItem
PickaxeItem
ShovelItem
User
ButtonItem
LiquidCrafterItem
LogicGateItem
SwitchItem
TollItem
AirPollutionGeneratorItem
Demographics
Trade
BarterTrade
CurrencyTrade
DidntVote
AdvancedBakingUpgradeItem
AdvancedCookingUpgradeItem
AdvancedMasonryUpgradeItem
AdvancedSmeltingUpgradeItem
AdvancedUpgradeLvl1Item
AdvancedUpgradeLvl2Item
AdvancedUpgradeLvl3Item
AdvancedUpgradeLvl4Item
BakingUpgradeItem
BasicEngineeringUpgradeItem
BasicUpgradeLvl1Item
BasicUpgradeLvl2Item
BasicUpgradeLvl3Item
BasicUpgradeLvl4Item
ButcheryUpgradeItem
CampfireCookingUpgradeItem
CarpentryAdvancedUpgradeItem
CarpentryBasicUpgradeItem
CompositesUpgradeItem
CookingUpgradeItem
CuttingEdgeCookingUpgradeItem
ElectronicsUpgradeItem
FarmingUpgradeItem
FertilizersUpgradeItem
GlassworkingAdvancedUpgradeItem
GlassworkingModernUpgradeItem
IndustryUpgradeItem
LoggingAdvancedUpgradeItem
LoggingBasicUpgradeItem
MasonryAdvancedUpgradeItem
MasonryBasicUpgradeItem
MechanicsAdvancedUpgradeItem
MechanicsModernUpgradeItem
MillingUpgradeItem
MiningAdvancedUpgradeItem
MiningBasicUpgradeItem
MiningModernUpgradeItem
ModernUpgradeLvl1Item
ModernUpgradeLvl2Item
ModernUpgradeLvl3Item
ModernUpgradeLvl4Item
OilDrillingUpgradeItem
PaperMillingUpgradeItem
PotteryUpgradeItem
SmeltingUpgradeItem
TailoringUpgradeItem
