### ISSUE TITLE
9.0 1459 Popup every spend 100 Labor 

### ISSUE THREAD

**Issue by FalkosTMB** [StrangeLoopGames/EcoIssues#15084]
![Unbenannt-1](https://user-images.githubusercontent.com/43608607/76463886-8697a580-63e4-11ea-8f28-1bde7a1f0d9f.jpg)
If 1 have an order with 100 Sand i must confirm this Popup 20 times :-(

**Comment by johnkslg** [comment]
Whoops, wrong box. Fixed.

**Comment by otting** [comment]
use the ctrl + click for ease of pain

**Comment by SlayksWood** [comment]
@johnkslg 
Do we really need 3 notifications?
![image](https://user-images.githubusercontent.com/45708377/76595376-809ce400-650c-11ea-866f-7ba41a12ca73.png)

**Comment by beastyn** [comment]
@otting Alt+click for max calorie laboring
