### ISSUE TITLE
0.9 -1445: Swapping stacks between Stockpiles

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15080]
**Version:** 0.9.0.0 beta staging-1445

**Steps to Reproduce:**
Have two Stockpiles
First has Tailings
Second has stack of rock
drag n drop rocks on tailings

**Expected behavior:**
Switch rocks and tailings slot

**Actual behavior:**
"Target inventory cant accept the item"
(Works the other way around when dropping tailings on rocks)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/76409515-82956480-639f-11ea-9ea1-3413216e309b.png)
It happens when you drag "non-shovel" items and drop to "shovel items"(Shovel items are Dirt, Tailings, Crushed stonesa & etc.)

**Comment by NN-Mike** [comment]
Also effects items from carried

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/79732851-739abe00-831e-11ea-9410-e48059dbd77d.png)
