### ISSUE TITLE
0.9 static\dynamic ingredients indicator periodically not displayed.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15085]
As i see, it happens at "tagged" sections, easy to see - fishery, "fish trap" and lavish workspace talent in carpentry.
No green highlight
![изображение](https://user-images.githubusercontent.com/4980243/76471080-cbcad000-6402-11ea-84cc-a1e10481b75a.png)

boo! appear.
![изображение](https://user-images.githubusercontent.com/4980243/76471102-d7b69200-6402-11ea-9004-599da615c266.png)

**Comment by WiseProjects** [comment]
All non-static recipes in campfire are also broken with same issue

![unknown](https://user-images.githubusercontent.com/58177535/76572814-27ad5b80-64cc-11ea-8b45-2b406ced0c4a.png)
![unknown2](https://user-images.githubusercontent.com/58177535/76572815-2845f200-64cc-11ea-8aee-16b1b102d8f7.png)
![unknown3](https://user-images.githubusercontent.com/58177535/76572816-2845f200-64cc-11ea-8297-84be5844aea2.png)

**Comment by SlayksWood** [comment]
Yellow-static should be always shown.
Green should be shown if you have any effects by module.

**Comment by SlayksWood** [comment]
delete resource benefit for static ingredient from tooltip:
![image](https://user-images.githubusercontent.com/45708377/76608153-3d4f6f00-6526-11ea-97ff-fb6badc4a980.png)

**Comment by johnkslg** [comment]
Also add explanation what the colored border means inside the tooltip for folks that don't know

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/81046587-63a7e000-8ec1-11ea-9165-c3e3851d8d5a.png)

**Comment by elfl0rd** [comment]
> Ingredient's green highlight is appearing only if the amount is better than the basic one (without any bonuses).

**Comment by SlayksWood** [comment]
@elfl0rd Thank you, I can read

**Comment by elfl0rd** [comment]
but in the same time you mark "work as intended" as bug for reopen... 🤔

**Comment by SlayksWood** [comment]
I think I have a reason for this.

**Comment by elfl0rd** [comment]
> I think I have a reason for this.

But what do you want in fix result?
