### ISSUE TITLE
Storage chest always says 'Public' for itself

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1508]
![image](https://cloud.githubusercontent.com/assets/774628/26331897/54b24f24-3f08-11e7-8875-4db8392872e0.png)
Could say its name or show private when locked

**Comment by MarjieAVolk** [comment]
Yeah I didn't realize at the time that private inventories are gone.  Inventories don't themselves have names, so I wasn't sure if or how we wanted to handle the case where something has multiple inventories.  But it's kind of looking like we don't need to care about that case?  Or are there some vehicles that have multiple, what with their toolbars?

**Comment by SeanAtr0n** [comment]
Modular vehicles will probably have a max of 2 inventories... one toolbar and one (public?) storage that could inherit the vehicle name. The toolbar doesn't really need to show up in linked inventories

**Comment by MarjieAVolk** [comment]
Already changed this to say "Storage"
