### ISSUE TITLE
0.9 boiled grains (split or little change)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15093]
![изображение](https://user-images.githubusercontent.com/4980243/76516940-665ff900-646d-11ea-9e42-e41503ccb5f7.png)

As you can see - proteins and vitamins values is different.
And "tagged" ingredient is dynamic, but fixed - is static.

Also idk why in rice sludge displayed harvesting benefit, lol.
![изображение](https://user-images.githubusercontent.com/4980243/76516953-6e1f9d80-646d-11ea-85c4-d00892987039.png)
![изображение](https://user-images.githubusercontent.com/4980243/76516964-74ae1500-646d-11ea-9ac5-8ab4e38d3701.png)
![изображение](https://user-images.githubusercontent.com/4980243/76516976-7972c900-646d-11ea-8789-5071447f9d21.png)

**Comment by SlayksWood** [comment]
Should be static or increase basic ingredients by 2 times.
![image](https://user-images.githubusercontent.com/45708377/76731529-afb29000-676e-11ea-8c56-4de103886e08.png)

**Comment by elfl0rd** [comment]
I don't agree, in real life you use much less cereal than you get porridge.

**Comment by WeaselDog** [comment]
@SlayksWood Can you re-test? This was changed at same time we added static tagged ingredients

**Comment by elfl0rd** [comment]
Rice Sludge and Wheat Sludge got deleted?
