### ISSUE TITLE
0.9 - 1460: Order of orders can no longer be changed

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15091]
**Version:** 0.9.0.0 beta staging-1460

**Steps to Reproduce:**
Make two order, try to put the second in front

**Expected behavior:**
drag n drop as usual	

**Actual behavior:**
nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Comment by SlayksWood** [comment]
dup #14991
