### ISSUE TITLE
[0.9.0 Staging 1460] Civics: Default Constitution in capitol flaws

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15097]
-1-
1. Place a capitol in the fresh world
![bandicam 2020-03-12 16-48-28-185](https://user-images.githubusercontent.com/27898520/76518783-8b5e6700-6481-11ea-8da4-1c003f782047.jpg)
2. Change Any Laws (In Law article) to the Law Preventing actions
![bandicam 2020-03-12 16-48-32-490](https://user-images.githubusercontent.com/27898520/76518868-b648bb00-6481-11ea-810e-46fb9dc62935.jpg)
3.  Ratify
![bandicam 2020-03-12 16-48-50-377](https://user-images.githubusercontent.com/27898520/76519022-00ca3780-6482-11ea-8b52-32fdb0d9dd9f.jpg)

As you can see Any Laws option was coming back,
It should show changed options after ratification.
Its ok in tootip though
![bandicam 2020-03-12 16-54-46-300](https://user-images.githubusercontent.com/27898520/76519176-4f77d180-6482-11ea-8a05-b6b063c28b6d.jpg)

after ratification its still the same
![bandicam 2020-03-12 16-56-23-536](https://user-images.githubusercontent.com/27898520/76519280-7fbf7000-6482-11ea-9063-59476d7ee0b3.jpg)

**Comment by johnkslg** [comment]
Fixed!
