### ISSUE TITLE
0.9 -1460 : Pickup sound for everything is irritating

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15099]
**Version:** 0.9.0.0 beta staging-1460

**Steps to Reproduce:**
pick something up

**Expected behavior:**
no sound or sound suitable for the item

**Actual behavior:**
sounds a bit like knocking on wood, it is irritating especially if you are farming

**Comment by SlayksWood** [comment]
dup #14647

**Comment by otting** [comment]
I swear I don't do dups on purpose i am always looking for something similar :(
