### ISSUE TITLE
0.9 campfire animal and campfire bison

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15094]
campfire animal - static, campfire bison - dynamic :)
![изображение](https://user-images.githubusercontent.com/4980243/76517400-4ed54000-646e-11ea-85ba-3ef821cae18d.png)

also description confuse me, benefit or static?
![изображение](https://user-images.githubusercontent.com/4980243/76517418-55fc4e00-646e-11ea-9c13-7276590df326.png)

**Comment by SlayksWood** [comment]
fixed, confusing description here #15085
