### ISSUE TITLE
0.9 empty error message if you chop tree at wrong position.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15092]
![20200312141747_1](https://user-images.githubusercontent.com/4980243/76516407-6f9c9600-646c-11ea-81c5-73ae9760300b.jpg)

**Comment by SlayksWood** [comment]
This error also happen when you try to chop small piece:
![image](https://user-images.githubusercontent.com/45708377/76517143-ce164400-646d-11ea-966e-e30171b01ad3.png)
