### ISSUE TITLE
Cursor shows up with no item selected

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#151]
it should only appear for tools that can place or remove blocks

**Comment by metachronism** [comment]
it should also behave like before where if you were placing a world object it also should not appear

**Comment by johnkslg** [comment]
Pushing to alpha 5, I want to add a new system that communicates to the client the block and object types that an item can interact with

**Comment by metachronism** [comment]
this is really infuriating right now though, the stupid white cube takes up a huge part of the screen

**Comment by metachronism** [comment]
fixed
