### ISSUE TITLE
0.9 move "Rubber Wheel" recipe from wainwright, or add support "mechanics" modules.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15102]
for now - max eff for iron wheels is 40%

**Comment by elfl0rd** [comment]
or another fine solution, change speciality "iron wheel" from mechanics to basic engineer.

**Comment by SlayksWood** [comment]
Same problem with Rubber wheel:
![image](https://user-images.githubusercontent.com/45708377/76727225-7bd26d00-6764-11ea-88e0-b0ef1ce22032.png)
I think we need to move this wheel to another table.

**Comment by mirasrael** [comment]
May be move Rubber Wheel to Assembly Line?
