### ISSUE TITLE
0.9 workorder should display available resources

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15105]
![изображение](https://user-images.githubusercontent.com/4980243/76548633-1ea69500-64a0-11ea-940a-590e822d3a96.png)

what about "available resources"?

**Comment by johnkslg** [comment]
Requires more work that could cause performance issues. 
Or maybe @mirasrael has a good idea

**Comment by elfl0rd** [comment]
for me - fine solution if this tooltip use same technology as ingredient icon in recipe.
Heavy calculation is not needed.

**Comment by mirasrael** [comment]
Yes, tooltip only is enough.

**Comment by johnkslg** [comment]
@gzatravkin can you make this use whatever the ingredient tooltip does to calculate available resources (refactor to use the same code path too)

**Comment by johnkslg** [comment]
Make it say something like (x available in storage) after the other numbers, if there are stored ones around

**Comment by SlayksWood** [comment]
Nothing:
![image](https://user-images.githubusercontent.com/45708377/79198820-c404ae00-7e3c-11ea-964a-9539f9001f22.png)

**Comment by mirasrael** [comment]
Can collect total items and tag using this code
```csharp
var availableItems = this.DefaultInventory.NonEmptyStacks.ToDict();
            var availableTags = new Dictionary<Tag, int>();
            foreach (var entry in availableItems)
            {
                foreach (var tag in Item.Get(entry.Key).Tags())
                {
                    availableTags.AddOrUpdate(tag, entry.Value, (oldVal, newVal) => oldVal + newVal);
                }
            }
```

**Comment by mirasrael** [comment]
Use something like this to describe ingredients
```
if (missingIngredient != null)
                    "[X:red] [Item] missing (Y total remaining)";
                else
                    "Y [Item] total remaining ([Z:yellow if Z < Y:green otherwise] available in storage)";
```

**Comment by SlayksWood** [comment]
Now I can't see how much I need.
![image](https://user-images.githubusercontent.com/45708377/80073892-1cc8fa80-8551-11ea-9eb1-9b1c0fa64d78.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/80096970-26635a00-8573-11ea-9d82-326170cb66e2.png)
![image](https://user-images.githubusercontent.com/475445/80096986-32e7b280-8573-11ea-897c-814e07d6cb90.png)
