### ISSUE TITLE
[0.9.0 staging 1460] unable to pickup or place cart on another players property

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15109]
As per subject, probably also applies to other items such as steam truck

![image](https://user-images.githubusercontent.com/61889138/76561076-7b9f4c80-649a-11ea-915b-f10e5cb3bc4a.png)

**Comment by SlayksWood** [comment]
You should only pickup vehicles on another player property. placing works as intented.
