### ISSUE TITLE
[0.9.0 staging-1461] Can see only first same labor information near Order Icon

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15113]
Step to reproduce:
- add work order with much Labor (Capitol) and add 1 res:
![image](https://user-images.githubusercontent.com/45708377/76595836-bee6d300-650d-11ea-9dcf-71c1e2a0233e.png)
- add labor with LMB 1 time. I see notification.
![image](https://user-images.githubusercontent.com/45708377/76596025-34eb3a00-650e-11ea-841e-ad3c6eb77858.png)
- wait while this notification will hide and add another one 100 Labor:
![image](https://user-images.githubusercontent.com/45708377/76595991-24d35a80-650e-11ea-846e-bf0f9c39d16a.png)
- I haven't this notification anymore.

**Comment by beastyn** [comment]
nope, stll; here
![bandicam 2020-03-17 10-55-24-459](https://user-images.githubusercontent.com/27898520/76826374-28345200-683e-11ea-9e51-0c36852a6e73.jpg)
![bandicam 2020-03-17 10-55-34-897](https://user-images.githubusercontent.com/27898520/76826376-29657f00-683e-11ea-9386-7879e6a2d749.jpg)

**Comment by johnkslg** [comment]
try once more!

**Comment by johnkslg** [comment]
after my pr goes in
