### ISSUE TITLE
[0.9.0 staging-1461] Unable to delete/move "Else"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15115]
![image](https://user-images.githubusercontent.com/45708377/76603017-3839f200-651d-11ea-855f-bd43d94e2e6a.png)

**Comment by johnkslg** [comment]
- Highlight whats going to get deleted when you mouse-over the delete button
- Replace all garbage cans with minus buttons
- Experiment with frames (bonus option)
