### ISSUE TITLE
[0.9.0 staging-1461] Need to hide from filter

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15114]
![image](https://user-images.githubusercontent.com/45708377/76596754-ff475080-650f-11ea-83c3-2d4349677a99.png)
![image](https://user-images.githubusercontent.com/45708377/76597086-b9d75300-6510-11ea-91a4-63008a30902f.png)
![image](https://user-images.githubusercontent.com/45708377/76597217-f5721d00-6510-11ea-97eb-f041372a96fb.png)

**Comment by WeaselDog** [comment]
We want to remove both Stuffed Animal and Animal Mount completely. They are a non-default parent recipe

**Comment by SlayksWood** [comment]
yea, I forgot.
Meteor Shard should be hidden too.
![image](https://user-images.githubusercontent.com/45708377/76602510-20ae3980-651c-11ea-95a9-142e16bb7404.png)

**Comment by Sekor2600** [comment]
Wolfmask etc then too?

**Comment by SlayksWood** [comment]
@Sekor2600 
I don't find it in filter. If it isn't hidden, yes

**Comment by elfl0rd** [comment]
idk why owner cannot sell items (wolf mask, etc.) trough store :(

**Comment by WeaselDog** [comment]
All reward items are already hidden except Meteor Shard. We can hide this one too.
