### ISSUE TITLE
[0.9.0 staging-1461] Softwood and Hardwood lumber: can't rotate fence

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15119]
Fence element from softwood lumber won't connect in a line
![bandicam 2020-03-13 17-14-21-465](https://user-images.githubusercontent.com/27898520/76626254-a7820700-655a-11ea-95d6-6e0dd5952435.jpg)

**Comment by beastyn** [comment]
hardwood too

**Comment by keegan-o** [comment]
fixed in staging
![image](https://user-images.githubusercontent.com/14983165/81450160-b76f2f00-9136-11ea-8a5d-57dc720eb794.png)
