### ISSUE TITLE
Baking reciepe problem

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15126]
Look at the screenshot out of the 3 Muffins you can make, 1 of them costs 10 flour to make where the 2 others only cost 4 flour
![20200313213106_1](https://user-images.githubusercontent.com/38038590/76657440-2fbfd680-6572-11ea-82ea-269752077096.jpg)

**Comment by Zoneman81** [comment]
Also the papaya needed is higher then the other recipes

**Comment by WeaselDog** [comment]
Thanks for the catch. We are moving towards having tagged ingredients so any fruit maybe be used to make Fruit Muffins. For now we will remove Huckleberry Muffin and Papaya Muffin, but they may return in a future update.
