### ISSUE TITLE
0.9 "labor added" info window intercepts esc button

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15123]
as i think, it should not.
(If i want to close window after adding labor, this info message disappear, confusing.)
![изображение](https://user-images.githubusercontent.com/4980243/76630659-73561880-6551-11ea-9c15-1d806c725df3.png)

**Comment by WiseProjects** [comment]
It's not only about info message. Any error message blocks ESC button too. Missing calories or ingredients, full labor and so on.

**Comment by SlayksWood** [comment]
#14977 It was made so:
"Now it should close only error message on escape. Then if you press ESC again it will close UI (and at third time show main menu)"

**Comment by elfl0rd** [comment]
Perhaps this option would be better?
"If the interface is open, we close both the interface and the message."
"if we only see the message, we close the message."

**Comment by Engimage** [comment]
Popup wil disappear anyways after short period but a player most of time expects closing an UI window with Esc.
For me personally it is always a pain when Esc does not effectively close UI window when I hit it.
