### ISSUE TITLE
[0.9.0 staging 1464] Map water/sand blocks flicker

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15128]
on the map the map the water/sand blocks further on the edges flicker when moving map around, did not seem to happen prior to 1464 build

https://i.imgur.com/C3Aw7Pz.gifv

**Comment by SlayksWood** [comment]
@MishkaFur 
please, provide your graphic settings.

**Comment by MishkaFur** [comment]
@SlayksWood 

![image](https://user-images.githubusercontent.com/61889138/76750701-9e6d8180-6776-11ea-9d89-2779c23c853a.png)

**Comment by redwyre** [comment]
afaik it's always been like that, but I am planning on looking at the minimap some more

**Comment by SlayksWood** [comment]
Seems it was fixed with new minimap.
@MishkaFur Can you check it too, please?

**Comment by MishkaFur** [comment]
Yea doesnt seem to flicker anymore so doing a close and comment :)
