### ISSUE TITLE
0.9 if you move too fast and enter onto not loaded chunk - your shaders is broken until game restart

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15129]
easy to see - fly to not loaded chunks.

happens with server lags, driving vehicle at asphalt, etc.

![20200314150559_1](https://user-images.githubusercontent.com/4980243/76681594-af4ab580-6605-11ea-885b-b1c7eb67b516.jpg)
![20200314150603_1](https://user-images.githubusercontent.com/4980243/76681595-b07be280-6605-11ea-8b00-4b0e863ff725.jpg)
![20200314150606_1](https://user-images.githubusercontent.com/4980243/76681596-b1ad0f80-6605-11ea-821e-a6c78b7b6516.jpg)
![20200314150612_1](https://user-images.githubusercontent.com/4980243/76681597-b245a600-6605-11ea-8ee2-4e1b4e92a705.jpg)
![20200314150626_1](https://user-images.githubusercontent.com/4980243/76681599-b2de3c80-6605-11ea-9fc7-1c5b89909f92.jpg)

**Comment by SlayksWood** [comment]
merged to #14042
