### ISSUE TITLE
Can't connect to servers (including official servers)

### ISSUE THREAD

**Issue by DarkPlaymo** [StrangeLoopGames/EcoIssues#15122]
Eco-Version: 0.8.3.3

Dear Team,

sadly, I can't connect to foreign servers (including official servers). If i try, a loading screen is displayed but nothing happens (even after 30+ minutes). I can stop the loading screen by pressing ESC. I reinstalled Eco 4 times, restartet my computer, but this error still retains. 
Altough I can create a own Server and join it without problems.
There are no crash/error files in my "Appdata/Locallow/StrangeLoopGames/Eco"-directory. The Log-Files are referencing the connection to my own Server.
I hope you can help me.

Loading Screen (the thing in the middle rotates) - trying to connect to "[SLG] Giant Panda"
![Eco_loading_screen](https://user-images.githubusercontent.com/43245070/76627651-ab526100-653b-11ea-83f7-a2aabbc9b13c.PNG)

My "Appdata/Locallow/StrangeLoopGames/Eco"-directory
![Eco_directory](https://user-images.githubusercontent.com/43245070/76627757-de94f000-653b-11ea-8eb6-1cf2e00be088.PNG)

**Comment by beastyn** [comment]
Thank you for your report. Please, answer some questions

1. Can you see servers in list normally? With ping and server info?
2. Do you have Firewall or Antivirus enabled?
3. Which kind of internet connection are you using?
4. Please provide your PC specification (include Operating System).
5. Did you meet this issue after updating to the "latest build" or you had it before?

**Comment by DarkPlaymo** [comment]
1) Yes (see the picture in my first post). If I click on "New Game", the servers show up with all the Information (day, citizens, online, match score, ping) 
2) I turned Firewall and Antivirus off, but the problem still exists
3) LAN - Download: 15,66Mbps | Upload: 0,94Mbps
4)
- Operating System: Windows 8.1
- Processor: AMD FX - 8350 Eight Core Processor (4GHz)
- Graphiccard: AMD Radeon R9 200 Series
- System Type: 64-bit operating system, x64-based Processor
- RAM: 16GB
5) I buyed and installed Eco on that day on Steam. I don't know, what the latest Build is. In Eco it says "0.8.3.3 beta" in the bottom left corner. If I go to Steam>Eco>Properties>Local Data there stands "Current Content-BuildID: 4651439"

**Comment by beastyn** [comment]
@DarkPlaymo 
Thank you for your answer and patience. We are in the investigation process for this issue. We will inform you if we have additional wuestions ot a solution for you.

**Comment by DarkPlaymo** [comment]
I have moved my PC to another location and suddenly eco is running perfectly. Otherwise I haven't changed anything. I don't know why it works now, but I am quite happy about it. :smile:
