### ISSUE TITLE
0.9 Contract Frozen in Limbo

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#15127]
As Discussed in the #playtest discord, a bug occurs when deleting the last clause from an entire contract with "Receive Permissions" - which results in the contract becoming "stuck" neither responding to "Delete" nor allowing it to complete as a full contract, it remains stuck as an "invalid draft".
![20200313180315_1](https://user-images.githubusercontent.com/28554657/76663347-0e9dbc80-6557-11ea-9489-f414b095428f.jpg)
![20200313173806_1](https://user-images.githubusercontent.com/28554657/76663350-13627080-6557-11ea-9dd1-391cfe7e6c3f.jpg)

**Comment by SlayksWood** [comment]
- Press "create contract":
![image](https://user-images.githubusercontent.com/45708377/76749408-881ef000-678d-11ea-99b7-ea15215b4139.png)
- select "Receive permissions":
![image](https://user-images.githubusercontent.com/45708377/76750138-c668df00-678e-11ea-9214-4147aef3c93a.png)
- delete "payment on completition":
![image](https://user-images.githubusercontent.com/45708377/76750199-e39dad80-678e-11ea-8b21-5cfe331eb901.png)
- close UI: 
![image](https://user-images.githubusercontent.com/45708377/76750232-f3b58d00-678e-11ea-8124-b0ea34874bac.png)
- opened contract from "Work" notification:
![image](https://user-images.githubusercontent.com/45708377/76749763-1c895280-678e-11ea-9424-3bf0df896b78.png)
- a bug.

**Comment by johnkslg** [comment]
Got it, fixed!
