### ISSUE TITLE
[0.9.0 staging-1464] Starter clothing starts undiscovered

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15134]
All of the starter clothing starts undiscovered. This is not a big deal, but they should start discovered if they can be obtained without research.

While fixing this, edit the descriptions of the backpacks to specify the increase in weight of different backpacks.

**Comment by SlayksWood** [comment]
Wrong backpack description.
Without backpack and with self Improvement =1 you can carry 30 kg. So:
Basic backpack give you +5kg, Big Backpack - +10kg, bearpack - +15kg.
And may be add certain calorie consumption  to work backpack? It's 10%.

**Comment by WeaselDog** [comment]
It is based on basic backpack because we do not have a situation with no backpack, but I can update to say this.
