### ISSUE TITLE
Filesystem Limitation crash as soon as DB reached 5,9 GB

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15132]
> --BEGIN DUMP--
> Dump Time
> 03/14/2020 17:54:35
> 
> Exception
> Exception: IOException
> Message:The requested operation could not be completed due to a file system limitation
> 
> Source:mscorlib
> 
> System.IO.IOException: The requested operation could not be completed due to a file system limitation
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at Eco.Stats.PendingWritesDiskService.DoPendingAction(Int64 transactionId, PendingAction action)
>    at Eco.Stats.PendingWritesDiskService.DoPendingWrites()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> --END DUMP--

White-Tiger is not amused.

**Comment by redwyre** [comment]
I believe @johnkslg did some work on reducing db load

**Comment by D3nnis3n** [comment]
I move the milestone, but ultimately we will likely manage to get the same size with the optimisations to saving as well, so it needs to be fixed at some point.

**Comment by mirasrael** [comment]
We updated to new LiteDB version. Probably this issues fixed. Need to check.

**Comment by beastyn** [comment]
Do we have a proper way to test it?

**Comment by D3nnis3n** [comment]
I believe this will mostly be fixed by the DB requiring much less space, not reaching 5.9 GB anymore. I can tell you at the end of the White-Tiger playtest if it reached 5.9 GB + 2 GB (new file) again, or if it was way below that, so this issue is unlikely to reappear.

**Comment by beastyn** [comment]
Yes please, give us some numbers after this cycle. Thank you.

**Comment by D3nnis3n** [comment]
White-Tiger reached 1,9 GB after a full cycle that is somewhat comparable to a live-server. Panda is at 900 MB right now with massive user count, but i don't expect this issue to come up again as we're far away from the limit. Closing :)

**Comment by Sarah-Graesyn** [comment]
I had some thoughts on this issue after helping Mishka run a server on 9.0 both during the playtest and after full release.

first a question though: is the DB file all in one DB or is it split into separate DBs?

my thought: if it is not already separated into separate DBs take the file and separate it out so that you have a playerdata DB, a transactions DB, a plant DB, etc for anything that needs to be stored in the DB rather than having it all in one massive DB, that way the game doesn't just build one massive DB that then causes a crash because it gets too big to handle

**Comment by mirasrael** [comment]
@Sarah-Graesyn good suggestion, but it doesn't seems like a problem anymore. But if we face it again then we can use your solution :)

**Comment by D3nnis3n** [comment]
Tiger managed to get to 5,5 GB, but it's reset time, so we won't see if the limitation kicks in.
