### ISSUE TITLE
[0.9.0 staging1464] powered cart handling/steering VERY poor

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15131]
Powered cart steering is very poor, in reverse it is fine.

Will be used alot more in 9.0 due to the balancing and currently is very difficult to get round corners without doing a 10 point turn every time

**Comment by elfl0rd** [comment]
known, cannot be easy fixed.
one available fixing way - removing from game, but i against it, untill we not have a replace. (A cart with a tame animal, a bicycle cart, etc.)

**Comment by MishkaFur** [comment]
If its known then it should be marked down as an issue..... what makes it "cannot be easy fixed"?

Turning is incredibly poor its as if it is only turning about a quarter of that of a steam truck which are quite maneuverable

**Comment by beastyn** [comment]
We won't make any changes for it noe. We have some plans but for later realeases/
https://github.com/StrangeLoopGames/EcoSuggestions/issues/924
