### ISSUE TITLE
[0.9.0 staging-1464] Items with icon issues in Ecopedia

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15139]
The following items all have a white square for an icon in Ecopedia:
- Lumber
- All signs except Lumber signs
- Meat stock
- Huckleberry Pie
- Turkey Carcass

These have icons in game so there is something needs to be fixed.

**Comment by SlayksWood** [comment]
Incorrect icon for Cellulose fiber:
![image](https://user-images.githubusercontent.com/45708377/77729285-56b8e680-700f-11ea-9b26-067421178a09.png)
Also missing Upgrade icons (was added in game)

**Comment by WeaselDog** [comment]
Issue with new furniture:
> Lots of icons are just white, hovering over and clicking seems tos how the correct item.
> 
> ![image](https://user-images.githubusercontent.com/61889138/77960082-944b9700-72cf-11ea-8889-d71b1b44d38a.png)
