### ISSUE TITLE
[0.9.0 staging-1464] Metallurgy Research Paper Modern needs icon

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15138]
We need to setup the icon in Unity. For now we are using the same as icon as the other Metallurgy Research Papers so just need to hook it up.

**Comment by SlayksWood** [comment]
It has wrong color:
![image](https://user-images.githubusercontent.com/45708377/76824681-e8af3b00-6828-11ea-83d0-7a1677aece52.png)
all modern icons should be green. Now it has color like basic.
