### ISSUE TITLE
[0.9.0 straging 1464] District map text not fitting

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15135]
![image](https://user-images.githubusercontent.com/61889138/76689154-fa2af400-662a-11ea-8dce-f97272dedfdc.png)

![image](https://user-images.githubusercontent.com/61889138/76689170-1d55a380-662b-11ea-9a67-c593fdd256de.png)
![image](https://user-images.githubusercontent.com/61889138/76689192-4e35d880-662b-11ea-8eaa-6ae9916fe954.png)

step to reproduce.
Be in a district and start pulling a cart, the "Dirt road x1" or whose property it is kind of message is then blocked by the district map info

**Comment by SlayksWood** [comment]
merged to #14428
