### ISSUE TITLE
0.9 - 1464: Error when trying to view a district

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15130]
**Version:** 0.9.0.0 beta staging-1464

**Steps to Reproduce:**
Link District in Chat
Click on the link

**Expected behavior:**
Show DIstrict

**Actual behavior:**
Error district is currently edited by *myusername* ( I did no editing on it at all)
![image](https://user-images.githubusercontent.com/5678451/76682598-bec60080-65fd-11ea-9946-0e2971280f34.png)

**Comment by SlayksWood** [comment]
It seems that you can't view it when someone else views it in this time. Step toreproduce:
- create district and link it in chat(or you can try to open somewhere else).
- first player open district view:
![image](https://user-images.githubusercontent.com/45708377/76752569-2bbdcf80-6791-11ea-95ab-7364141ef116.png)
- second player try to view this district. he has error:
![bandicam_2020-03-16_16-19-55-652](https://user-images.githubusercontent.com/45708377/76753061-822b0e00-6791-11ea-806d-ed7ce419ce56.jpg)

- but all players should view this at same time. We have limit for creating district, but bot for view.
