### ISSUE TITLE
Progress bar on work party has no frame

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15149]
![image](https://user-images.githubusercontent.com/3536496/76741113-f376bb00-67a9-11ea-8d03-f5f14a2dfa57.png)
Looks like a bug when its at 0 %

**Comment by SlayksWood** [comment]
Still an issue. Also a little overlap is:
![image](https://user-images.githubusercontent.com/45708377/77309281-6bdefe00-6d0d-11ea-9945-93399dd144a1.png)

**Comment by SlayksWood** [comment]
missing frame:
![image](https://user-images.githubusercontent.com/45708377/80074219-86490900-8551-11ea-8d17-118e25b16549.png)

**Comment by SlayksWood** [comment]
missing frame:
![image](https://user-images.githubusercontent.com/45708377/80074364-b1cbf380-8551-11ea-9cd0-aa4d3bad13ea.png)
