### ISSUE TITLE
Server Star/Level Limit Confusing

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#15142]
**Version:** 0.8.3.3 beta

Just had a player ask on Discord why he wasn't getting more levels after level 12. This is supposedly a server setting, but it is confusing for players.
See: https://discordapp.com/channels/254025510651297802/448531486313021459/688671393478606867

I suggest changing it to actually say something like: "Server settings prevent further levels/stars."
But making it so players actually know there is a limit configured on the server before they reach the limit would be a good idea too. For example could detail server settings in the new Ecopedia in v9.0.

**Comment by elfl0rd** [comment]
afaik, there is no any option to do that.
maybe bug, but in this case need save and player log/
maybe user mistake - if regular xp gain small, user not eat and not have house...

**Comment by Deantwo** [comment]
If there isn't such an option, then I don't know. I just thought I had heard about an option like that before.

If someone else can confirm that the option doesn't exist, I will close this.

**Comment by beastyn** [comment]
So, originally not getting wxp is a bug.
Is there a way to get server logs folder?
Or client loп from that session?

**Comment by Deantwo** [comment]
> So, originally not getting exp is a bug.
> Is there a way to get server logs folder?
> Or client log from that session?

Doesn't sound like it as it was through a player and not the server owner.
Just gonna close this then, since the report was about something else that was seemingly just a misunderstanding.
