### ISSUE TITLE
When is the localization applied?

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#15147]
I made 100% work rate!
When is it applied?

And! I've been writing on the missing part of the Korean language
When does that apply?

**Comment by beastyn** [comment]
Thank for for your report.
Localization will be updated in a few days, but it will work only for upcoming versions (9.0 for now).
8.3.3 version will operate as it is now.

**Comment by StoryNine** [comment]
> Thank for for your report.
> Localization will be updated in a few days, but it will work only for upcoming versions (9.0 for now).
> 8.3.3 version will operate as it is now.

When you enter a terminal vowel, does the phenomenon that comes out as a question mark also update from 9.0?

ㅂㅈㄷㄱㅅㅁㄴㅇㄹㅎㅋㅌㅊㅍㅛㅕㅑㅐㅔㅗㅓㅏㅣㅠㅜㅡ

If you enter the above information 

   ????????????????????
This is what happens.
