### ISSUE TITLE
0.9 - 1464 Steel Sickle and Modern Scythe uses too much calories and durability

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15141]
When using the steel scythe you always use the same calories as a iron scythe would do when hitting 4 times, even if you only farm 1 or 2 plants with this hit, this combined with the odd hitting area makes it burn my calories way too fast and the iron scythe much more efficient.

**Comment by SlayksWood** [comment]
they should use only fo reaping Grass like AoE machetes and hoes

**Comment by SlayksWood** [comment]
It also consumes 4 durability per each hit.

**Comment by Quadbro** [comment]
@WeaselDog @Sekor2600 We changed such tools to use per block calories and durability
So the value in tech tree is multiplied by amount of blocks in area (applied blocks only, so usage is dynamic a bit)

**Comment by WeaselDog** [comment]
There seems to be a bug with this that it consumes calories regardless and it will still destroy grass that is unripe. My understanding was the AoE sickle will not destroy grass.

**Comment by Quadbro** [comment]
oj got it, will fix callories usage if block is not harvested by this action, but that can be tricky

**Comment by Quadbro** [comment]
@Sekor2600 @WeaselDog Fixed plant tools blocks havest, now it uses callories only if it did smth. So if calories consumption is correct in techtree - issue should be fixed.

**Comment by SlayksWood** [comment]
Steel sickle still use x4 calories and x4 durability with every hit even if you mow 1 grass.
Modern scythe is fixed.

**Comment by Quadbro** [comment]
changed sickle to behave like scythe
