### ISSUE TITLE
Custom Builder Variant Mesh Selection Not Really Random

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#1514]
![image](https://cloud.githubusercontent.com/assets/14983165/26379257/1476dd4c-3fcd-11e7-8a4b-3514a3d9276e.png)

Puts tons in one area at the moment even if it's supposedly one out of 8 choices of meshes to choose from.

The best update would be controlling rough percentages that appear if possible, or just more random would probably be fine too.

**Comment by metachronism** [comment]
this should be fixed now, but if we really want random weights that will be a bit more work
