### ISSUE TITLE
0.9 - 1464: Concrete costs are way too high

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15143]
![image](https://user-images.githubusercontent.com/5678451/76703209-45e3a900-66d0-11ea-91ec-58fa4af17f08.png)

1152 rocks for 10(!!!) Concrete is absolutely ridiculous
this is enough for 17 Asphalt roads which need another 486 rocks
this does reduce about 400 block down to 17 blocks, that is in no relation!

**Comment by WeaselDog** [comment]
Thanks for the catch. This is not the intended cost and will be adjusted

**Comment by elfl0rd** [comment]
quicklime in cement recipe is closer to real life.
Also it's a perfect way to utilise limestone.

**Comment by WeaselDog** [comment]
For now we have fixed the recipe to the intended costs, but we are still considering adding limestone

**Comment by otting** [comment]
there is plenty of limestone in the recipe, in the form of quicklime
