### ISSUE TITLE
USER ISSUE: BouBou

### ISSUE THREAD

**Issue by boubou69** [StrangeLoopGames/EcoIssues#15146]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by beastyn** [comment]
Buy the game and everything will be fine
