### ISSUE TITLE
0.9 Large Corrugated Steel Door price is too high

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15158]
48 steel bar with 50% module? 0_o

**Comment by WeaselDog** [comment]
Thanks for catch. We are aware of the issue and have been in discussion how to fix.

**Comment by elfl0rd** [comment]
i think its ok if door cost 1.1 (with 50% module) as same amount of wall blocks.
(craft door with 50% mod ~= 22 wall blocks)
