### ISSUE TITLE
Trees in minimap seem to be missing lighting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15156]
![image](https://user-images.githubusercontent.com/3536496/76772919-a2cc8580-67dc-11ea-94e3-c1c038a0fbbc.png)

**Comment by redwyre** [comment]
@johnkslg do you mean that they're not casting shadows?

**Comment by johnkslg** [comment]
@redwyre theyre not lit, theyre flat shaded
and no shadows

**Comment by johnkslg** [comment]
Compare to 8.3 to see difference

**Comment by redwyre** [comment]
@keegan-o can you re-export these with normals (but not tangents)?

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/8b18b953-f7a3-4378-8d2a-ce5fa2933fc9)
No longer an issue?

**Comment by keegan-o** [comment]
@johnkslg @redwyre Can this issue just be closed?

**Comment by redwyre** [comment]
@keegan-o  Afaict, they are lit flatly, since there are no normals. They should be darker on the shadow side.

**Comment by keegan-o** [comment]
Ah it's because they all had normals set to straight up I think. They'll look a bit crappier in some circumstances now potentially since you'll be able to see more edges, but yeah. Maybe we can afford slightly more tris in them?

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/de7da70b-1c79-45a9-b874-caee9588adad)

Normals unlocked for all meshes, palm trees do look better this way. Saguaro look a bit worse, but overall good to have lighting consistent with terrain. Closing this for now, but @redwyre or @mirasrael maybe let me know if we can make these meshes a bit prettier with more tris each.

**Comment by mirasrael** [comment]
I think we should avoid tris increasing as much as possible, because... you see how much trees we have on the map?:)

**Comment by redwyre** [comment]
They used to be much more, and afaik it wasn't the bottleneck of the map. Worst case we could have low and high poly LODs.
