### ISSUE TITLE
Mask is incorrect on world object ui

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15157]
![image](https://user-images.githubusercontent.com/3536496/76773057-d7404180-67dc-11ea-899b-dc0f5827c550.png)
Cuts off bottom

**Comment by beastyn** [comment]
Still cutting the same
![bandicam 2020-04-20 11-55-06-535](https://user-images.githubusercontent.com/27898520/79723104-a765eb80-82fe-11ea-98b2-1cccfd862afe.jpg)

**Comment by serpopov** [comment]
![image](https://user-images.githubusercontent.com/4238643/79952047-fac56e80-84a3-11ea-85ae-efff48f94c78.png)
dunno, works fine to me
