### ISSUE TITLE
The settings on district map need fixing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15155]
![image](https://user-images.githubusercontent.com/3536496/76772689-4d907400-67dc-11ea-87d8-dbed201034d4.png)
- Settings should be hidden to start
- Unchecking the district map in settings did nothing. Not sure what should happen here, I suppose you can switch to other district maps just to see them but as soon as you start drawing it should switch to the current one?

**Comment by johnkslg** [comment]
Also, pressing escape on the district view closes the worldobject ui beneath it too.

**Comment by beastyn** [comment]
Settings are op
