### ISSUE TITLE
[0.9.0 staging-1468] Civics: Amendments won't update UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15152]
1. Place a capitol and ratify it
![bandicam 2020-03-16 17-26-36-415](https://user-images.githubusercontent.com/27898520/76759124-e4453c80-67ac-11ea-86b2-51b754bc7bd1.jpg)

2. Place Amendments
3. Let say, we want to remove default law article and make the custom one
![bandicam 2020-03-16 17-27-59-446](https://user-images.githubusercontent.com/27898520/76759108-d8f21100-67ac-11ea-90d7-a5c2f8a5167a.jpg)
4. Let say we want to edit this amendment
5. Edit created amendment. Try to delete removed an existed article and add a new article
When you are deleting Remove Existing Article - nothing happens
When you are trying to delete a new article, you will get an error. Try to add something somewhene - nothing.
![bandicam 2020-03-16 17-39-47-109](https://user-images.githubusercontent.com/27898520/76759263-240c2400-67ad-11ea-9bba-1ebb038ea4b9.jpg)
6. Reconnect and look into editedamendment
Remove Existing Article is empty.
New article is added

It should work without reconnection

**Comment by johnkslg** [comment]
Nice find, fixed. 
Changing districts was also busted, fixed that too.
