### ISSUE TITLE
Mac OS version performance issues

### ISSUE THREAD

**Issue by Gammeth** [StrangeLoopGames/EcoIssues#1515]
Just downloaded the mac version of the game and there are lots of issues.
The lighting is horrible. I can't see anything except shadows unless it's noon and I'm outside. The performance is incredibly laggy. No matter what graphics setting I use. Every movement is jumpy and the controls are klunky. Having a very hard time just moving around. Could really use some help or a refund.

**Comment by SeanAtr0n** [comment]
Sorry about that, could you send us some screenshots and some info about your computer? (macbook version or cpu/gpu/ram info)

**Comment by Gammeth** [comment]
Here are some screenshots in game and also a screenshot of my mac and OS info.
![screen shot 2017-05-23 at 9 24 15 pm](https://cloud.githubusercontent.com/assets/28911267/26383434/a158f3c0-4000-11e7-9928-5868db8ad12a.png)
![screen shot 2017-05-23 at 9 25 43 pm](https://cloud.githubusercontent.com/assets/28911267/26383437/a6a5209c-4000-11e7-98a5-8ac28d7a308e.png)
![screen shot 2017-05-23 at 9 29 28 pm](https://cloud.githubusercontent.com/assets/28911267/26383438/aa07bf88-4000-11e7-89d4-6a77a70c6880.png)
![screen shot 2017-05-23 at 9 30 34 pm](https://cloud.githubusercontent.com/assets/28911267/26383442/ae12a750-4000-11e7-9a6d-648fc1b7fc28.png)

**Comment by noblackthunder** [comment]
@Gammeth did you mean to comment and close this issue?

**Comment by SeanAtr0n** [comment]
Do the higher graphics quality settings also look black for you?

**Comment by Gammeth** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yes and it also really slows down rendering


Sent from Yahoo Mail for iPad


On Wednesday, May 24, 2017, 2:14 PM, Sean Ater <notifications@github.com> wrote:


Do the higher graphics quality settings also look black for you?

**Comment by Gammeth** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hey Sean, I haven't heard back from you in a while. I'm not sure why my case was closed because I didn't close it. So the FPS is really dragging essentially making the game unplayable. My two biggest issues are the FPS lag and the lighting. My question is this: are these areas in which you are working on at the moment and if so will we be seeing the improvements in future updates? Of so, I am willing to wait for future updates to see if there is indeed a fix.I know it's not my computer because I can run other open world games like minecraft, Albion and even Eve online without any problems.I am really excited about your game and was really looking forward to playing it. I have spent more than a few hours online watching videos of some of the youtubers who are playing the game and they don't have the issues I am having. 
Thanks for your attention and I am looking forward to being able to play Eco.


Sent from Yahoo Mail for iPad


On Wednesday, May 24, 2017, 2:14 PM, Sean Ater <notifications@github.com> wrote:


Do the higher graphics quality settings also look black for you?

**Comment by Gammeth** [comment]
Okay, so since I haven't heard anything In a while I just want a refund please.

**Comment by SeanAtr0n** [comment]
I'll be adding a menu for 5.6 to toggle graphics settings so we can debug this issue better. Hopefully one of those toggles will make the game playable for you in 5.6

**Comment by Gammeth** [comment]
Okay, so I will wait for the update then. Can you send me a notice when it is available for download?

**Comment by noblackthunder** [comment]
@Gammeth Could you please mail me on support@strangeloopgames.com ?

**Comment by SeanAtr0n** [comment]
Think most of these are resolved
