### ISSUE TITLE
[0.9.0 staging-1468] Civics: UI update for civics actions

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15150]
In some offices we don't have information about civics duties.
For comparison:

this is Government office
![bandicam 2020-03-16 15-08-29-549](https://user-images.githubusercontent.com/27898520/76745637-04b6cc00-6798-11ea-960b-c87a67815ff2.jpg)
In Civics component we have civics duties. And if I will delete Elected Title article it will tell me, that its not in my power anymore
![bandicam 2020-03-16 15-11-54-125](https://user-images.githubusercontent.com/27898520/76745948-8149aa80-6798-11ea-87ef-9e39effe0c1b.jpg)

But in executive office I won't see any feedback about my duties.
Can we add some here?
Ballot too.

Actually, I still won't be able to create an executive action AFTER i will prupose it
![bandicam 2020-03-16 15-22-12-326](https://user-images.githubusercontent.com/27898520/76746817-eeaa0b00-6799-11ea-8dcf-b90e4ce7a46b.jpg)

But there is no early state feedback from the object.

**Comment by SlayksWood** [comment]
There's definitely something wrong with ballot box:
![image](https://user-images.githubusercontent.com/45708377/102062973-7c3c8900-3e06-11eb-8330-4963840e893d.png)

**Comment by IcedForge** [comment]
The ballot box is still not fully working properly.
![Screenshot_3.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f804992d-4008-40d4-af26-591071ddaf41)
I should have permissions to both vote for things and start elections for titles as well.

![Screenshot_7.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/6d812c11-08ff-4aa6-ad0a-a9b1ff42cd5e)

**Comment by SlayksWood** [comment]
need to check after fixing #20099
