### ISSUE TITLE
[0.9.0 staging-1469] Imposter for tomatoes is very big and always show tomatoes.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15161]
![image](https://user-images.githubusercontent.com/45708377/76828513-354b4400-6832-11ea-9e45-9e5c39e8331e.png)
![image](https://user-images.githubusercontent.com/45708377/76828531-3ed4ac00-6832-11ea-8bca-3f0d55d31111.png)

**Comment by Sekor2600** [comment]
Imposter shows always the 100% Yield Plan. Same with Huckleberrys

**Comment by SlayksWood** [comment]
@Sekor2600 it's ok for me but imposter has bigger at 50% model than lod

**Comment by keegan-o** [comment]
fixed to never show the tomato fruit on the impostor.
