### ISSUE TITLE
[staging] The referenced script on this Behaviour XXX is missing

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#15165]
The referenced script (ImportantNotificationsListController) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Camera') is missing!
The referenced script on this Behaviour (Game Object 'Important notifications') is missing!
The referenced script on this Behaviour (Game Object 'Products') is missing!
The referenced script on this Behaviour (Game Object 'Ingredients') is missing!
The referenced script on this Behaviour (Game Object 'Table') is missing!

**Comment by olegshegai** [comment]
I got less information on latest staging and updated SVN (console messages do not reffer any object)
![image](https://user-images.githubusercontent.com/56091594/77049703-9cefc380-69d9-11ea-8da2-0f2f2cd8598b.png)
Checked prefabs folder and objects in both scenes with http://wiki.unity3d.com/index.php?title=FindMissingScripts 
Didn't find anything but `ClothingObjectMap` and obsolet post-processing profiles.

**Comment by johnkslg** [comment]
Error messages with no perceivable customer impact shouldnt be marked high

**Comment by redwyre** [comment]
Unless you know what these are from then the impact is completely unknown

**Comment by gzatravkin** [comment]
After some investigation I saw what the problem was in Chainsawtool in Eco.scene. After reserelization (by deleting and putting ChainsawTool) warnings were gone. So I assume that the reason was unity error on serealization of scene by some reason.

Should be fixed by changes in SVN I made

**Comment by redwyre** [comment]
It could have been an issue with prefab overrides in the scene?
