### ISSUE TITLE
[0.9.0 staging-1469] Contract board loses data

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15164]
1. Create a contract
![bandicam 2020-03-17 17-32-25-051](https://user-images.githubusercontent.com/27898520/76856829-f0490100-6875-11ea-83b1-d78b1db74970.jpg)
2. Restart server
3. Contract is no longer on a board but still in the Wok panel
![bandicam 2020-03-17 17-36-35-029](https://user-images.githubusercontent.com/27898520/76856870-0b1b7580-6876-11ea-81c8-53ec594354e1.jpg)

**Comment by SlayksWood** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/45708377/77140687-67a3ae00-6a8b-11ea-9925-07ba2b4d4b4e.png)
![image](https://user-images.githubusercontent.com/45708377/77140702-712d1600-6a8b-11ea-850c-b811b14bde64.png)
