### ISSUE TITLE
0.9 - 1464: Sound sometimes suddenly seems distant

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15160]
It feels like the Audiolistener is suddenly stuck or something, which is most prominent when driving arround in a steam truck, leading to much more quiet noises.
 I don't know how to reproduce it but it seems to happen regularly.

**Comment by TwixterZ** [comment]
@otting I will close with this issue for now.

If you still facing this issue in current version of ECO please raise a new ticket with all the details
