### ISSUE TITLE
Baking vs Cooking

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15162]
I can get around 78 food sp with baking only vs cooking at about 85 food sp.
Any chance to level those to skills out so they are equal or else we get the same issue as in v7 and 8, noone wants to do baking because cooking just is better

**Comment by Engimage** [comment]
I want to add that some baking recipes require cooking products but not other way around. Zoneman can probably elaborate which exactly

**Comment by Zoneman81** [comment]
I might have missunderstood, you want to add to baking reciepes that you need items from the skill cooking to balance out baking?

**Comment by Zoneman81** [comment]
now makaroons needs simple sirup and huckleberry extract to make, which is from adv. cooking and also stuffed turkey needs vegetable medley from an adv. cooking skill

**Comment by Zoneman81** [comment]
so status now is that baking gives less food sp, also in adv baking it gives less, a baker has to rely on a miller and a butcher, where cooking only needs a butcher.
Its not so balanced yet and will end up with people only taking cooking, imo

**Comment by Zoneman81** [comment]
Also the skill cooking and adv. cooking needs nothing from a baker.
Which it should be, most of the times in ECO cycles 1 person dont have cooking and baking, but they do compete for marked shares in ECO, and with the current balance, cooking will is the clear winner.
