### ISSUE TITLE
0.9 Multiple labor added hints cover itself

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15179]
![20200317210109_1](https://user-images.githubusercontent.com/4980243/76886935-89861080-6892-11ea-8fd9-c2bbebbddb6e.jpg)

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/77393902-2246ef80-6daf-11ea-916b-3486fb442166.png)
![image](https://user-images.githubusercontent.com/45708377/77393924-2d9a1b00-6daf-11ea-8706-c1efb96188b2.png)

**Comment by elfl0rd** [comment]
try 4 or more
