### ISSUE TITLE
0.9 all plants invisible while driving (but not trees)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15173]
occlusing culling? lol.
![20200317183041_1](https://user-images.githubusercontent.com/4980243/76872420-7288f380-687d-11ea-890c-f63891242ea4.jpg)
![20200317183045_1](https://user-images.githubusercontent.com/4980243/76872423-73ba2080-687d-11ea-9551-fc0c628f4b7e.jpg)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/76939202-06ec6800-6909-11ea-8e17-3163f821f747.png)
![image](https://user-images.githubusercontent.com/45708377/76939212-094ec200-6909-11ea-82d5-b7111e4d980e.png)

**Comment by mirasrael** [comment]
Was mislead by issue description first time
