### ISSUE TITLE
Invite button missing on steam 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15171]
![image](https://user-images.githubusercontent.com/3536496/76865197-51d09600-689d-11ea-8e70-d673550092e6.png)

**Comment by beastyn** [comment]
Alex said that Invite to Lobby is working like that. Can you check it, please?

**Comment by johnkslg** [comment]
It should say invite to game, not to lobby then

**Comment by johnkslg** [comment]
Passing to :quaddamage:

**Comment by mirasrael** [comment]
@johnkslg as far as I know Steam removed this function.

**Comment by mirasrael** [comment]
https://steamcommunity.com/discussions/forum/0/1661194916744170152/

**Comment by beastyn** [comment]
'Invite to lobby' is working as invitation to the game
You will ve auto connected to the friend's server
