### ISSUE TITLE
When can I add Korean language support to Steam?

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#15183]
When can I add Korean language support to Steam?

Korean users basically come to see more phrases in support of Korean language.

Even though eco games are already supported in Korean, people don't know.
So I want to ask when it will be added.

I want to promote it to many people because I have great eco-game skills, but everyone often says that Korean is not supported.
I'm so sad
Korean is supported, but the store page says that it is not, so people do not know.

**Comment by D3nnis3n** [comment]
Hello StoryNine,
this is a place for bug reports, your request would be better suited for dennis@strangeloopgames.com.

Please note that the Korean translation is only proofread to 60% and that it would need to be steadily updated with all future changes for us to be able to actually advertise it. Please get in touch with me via mail to discuss that.
