### ISSUE TITLE
[0.9.0 staging-1970] If I don't have any resource in order, I shouldn't see hint that I can add labor.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15186]
Step to reproduce:
- place some craft table and stert order. Don't add any resource:
![image](https://user-images.githubusercontent.com/45708377/76935890-02bd4c00-6903-11ea-8a05-ae67055a7ce1.png)
- close UI and see hint. It say that I can add labor:
![image](https://user-images.githubusercontent.com/45708377/76935924-12d52b80-6903-11ea-8c3f-8cc09dc8fb5a.png)
- but I can't:
![image](https://user-images.githubusercontent.com/45708377/76935950-1c5e9380-6903-11ea-864f-a5fee83c3434.png)

**Comment by johnkslg** [comment]
This was intentional to prevent players not understanding why they cant add labor.  But perhaps we dont do that, if it feels buggy.
