### ISSUE TITLE
Can't see error notification with /give fountain

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15185]
can see only in chat:
![image](https://user-images.githubusercontent.com/45708377/76934646-90e40300-6900-11ea-8fa0-d4ccef36c808.png)
For example /give modern:
![image](https://user-images.githubusercontent.com/45708377/76934683-a48f6980-6900-11ea-919c-8f72400d0d7b.png)

**Comment by madpingui** [comment]
Tested on unity editor develop branch
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/498d58e7-ff16-43ef-a1df-0d2f76b0adcd)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3.1 Release-207.
![image](https://user-images.githubusercontent.com/77248866/115533901-cc05f200-a2c9-11eb-80ec-ab4d282c8869.png)
Closing.
