### ISSUE TITLE
9.0 Pump Jack Crafttime

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#15199]
The oil field has too much inclusion in the time for petroleum
You can craft it with 2 Sec with best Field.
And when you change it to 3 Miniten normal you have 6 Ses in best Field all wihtout Modules

**Comment by SlayksWood** [comment]
with one of the best oilfield:
![image](https://user-images.githubusercontent.com/45708377/77295592-4cd57180-6cf7-11ea-9591-2edde8e6ca2d.png)
