### ISSUE TITLE
Website and tree feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15192]
![image](https://user-images.githubusercontent.com/3536496/76941084-5c8b3980-6936-11ea-8404-16d4af6c98d2.png)
- [x] Jeff: Let's remove this section, since we have 'recent updates' as a button in the eco tree its no longer needed.  Will let users get to the tree faster too.

![image](https://user-images.githubusercontent.com/3536496/76941111-6c0a8280-6936-11ea-8bb7-b00804a32d0f.png)
- [x] Denys When scrolling down this page, the texts fade in nicely, can you make the Eco Tree text fade in as you arrive too, the same way?

![image](https://user-images.githubusercontent.com/3536496/76941183-8a707e00-6936-11ea-804d-47bf5335ac37.png)
- [x] Jeff: Tooltips are not appearing next to the user. It should also say what they do on Eco, and their bio right there.  Should be nice and small text.    Also, a tooltip hung around after I moved off of it.

- [x] Denys: add logic for new dev labels

- [x] Denys: Clicking Leonard opened https://accounts.developland.strangeloopgames.com/team#Ipaul, but it did not scroll down to Leonard's bio. 

![image](https://user-images.githubusercontent.com/3536496/76941884-c1935f00-6937-11ea-881f-20893acfe577.png)
- [x] Denys: Something wrong with text, and headers too small. 

- [x] Jeff: Replace the old company bio with this one:
(Header:)**We believe games have the potential to change worlds.**
At Strange Loop, our goal is to build games that go beyond fun, creating experiences that give our players a new perspective on the world, connect communities together, and redefine what it means to ‘play’.   Through our flagship title Eco we aim to bridge the gap between games and education, building worlds that challenge players to solve the same global challenges that our real world faces, working in economies, governments, and scientific simulation that mirror our own. We believe games can provide a hugely important role in the world beyond entertainment, giving players context into the deeper systems of the real world, and asking them to navigate the challenges and change the world for the better. 

![image](https://user-images.githubusercontent.com/3536496/76942696-1daab300-6939-11ea-84d3-13664c10fe86.png)
- [x] Jeff: HTML/CSS part of next bullet.
- [x] Denys: When there are recent updates, display the number next to them here.  The number should also be present on the features on the tree that have updates since their last visit. Make this number remember the user (with cookies or whatever) so its accurate for their last visit. The number should clear when they view the update.   This feature is important for making this not just a place to learn about the game, but to follow its progress and discuss with others the changes coming in. 

- [x] Todd: Bios here have a lot of grammatical errors from non native english speakers. 
 Ask Todd or someone else to do an editing pass. https://accounts.developland.strangeloopgames.com/team

**Comment by rainfarmer** [comment]
https://cdn.discordapp.com/attachments/606260434156388352/689975432887795741/unknown.png
https://cdn.discordapp.com/attachments/606260434156388352/689975927782113333/unknown.png

@johnkslg how does this look for update notificaitons.
In mockup, we are lumping notifications to the parent categories. not the individual nodes. I think that would be too messy looking and the nodes don't have titles anyway.

Then on sidebar, the tabs with new updates are color coded. Instead of adding numbers in the already cramped menu area.

Can you confirm?

**Comment by johnkslg** [comment]
Generally looks good, but needs some art that will match the tree and not be too obtrusive.
![image](https://user-images.githubusercontent.com/3536496/77023303-d7039a00-69c6-11ea-8f16-624657a775f8.png)

Can use a little bubble like this with a number to show updates since last visit, and can put that both on the tree and on the tabs.  When you click the tab, it clears the bubble from both the tree and the tab.

On feature groups is ok, on the features themselves would be better.  It could even put the number inside the feature circle perhaps.

These can appear only when you click the tree (like when the developers appear).

**Comment by johnkslg** [comment]
Also note: you can move what is currently in that 'news' section into a 'marketing' root, or feature under 'community' perhaps, for stuff like the Playing for the Planet Alliance.  That kind of stuff is great to have still, and I think we can find a place for it in the tree based on the content.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/77185119-11843a00-6a8e-11ea-9eff-294282ffaf4f.png)
- [ ] @D3nnis3n supply a better world map image to be used here, this one is unlit and doesnt look good.

**Comment by denysaw** [comment]
@johnkslg Just don't re-test everything yet, please. It's not on `developland` only on local (as we have no auto-deployment to dev right now). We'll inform you after everything is finished and manually deployed to `developland`. Tx

**Comment by johnkslg** [comment]
Ok thanks for the heads up

**Comment by D3nnis3n** [comment]
I moved all stuff posted since release of 8.0 over but the stuff that was already used in the opening posts for features, as some blogs have been used like that. I opened a issue for some backend issues for formatting and for some stuff there is not really a fitting point, so i put it into Community.

**Comment by rainfarmer** [comment]
complete :)

**Comment by johnkslg** [comment]
Some of these are missing still

**Comment by denysaw** [comment]
> 
> 
> Some of these are missing still

Could you tell which exact, pls?
