### ISSUE TITLE
0.9 lumber stockpiles - hard to place

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15195]
(due "placing" point close to it center)
![изображение](https://user-images.githubusercontent.com/4980243/76962657-ae30c580-6930-11ea-9365-0819518939de.png)

**Comment by WeaselDog** [comment]
This is what Lumber Stockpile placement looks like for me. It works if you do a 180 after pulling out the Stockpile.
![LumberStockpilePlacement](https://user-images.githubusercontent.com/47330823/77863734-3e94c300-71d9-11ea-82ef-d4667591829f.png)

**Comment by elfl0rd** [comment]
If possible, can you make "max placement distance" dinamic, and based on object horizontal size?
(E.g. x2 or x3)
e.g. workbench (2 blocks) you can place at max 4 or 6 blocks.
Lumber stockpile (10) you can place at 20-30 blocks.

**Comment by keegan-o** [comment]
@StanKryvenko Do you think you could look into the solution Gdragon/elfl0rd mentions? We need either something like that or another way to prevent the player from getting stuck inside the large stockpiles on placement. Of course, if you just change the max placement that still allows players to get themselves stuck, so ideally a solution for automatically moving players out of the space occupied by world objects they just placed would be good.

**Comment by elfl0rd** [comment]
I'll explain a little bit why I want dynamic placement distance.
There's a problem when you can't properly place large objects, refineries, new stockpiles, advanced workbenches.
You prepare the space, but putting them there is pain.
With a dynamic distance, you can confidently place them by looking at the whole site, not standing close.

> a solution for automatically moving players out

The easiest thing is to disable object collision if a player is inside.
At first, it is not very difficult at the level of logic.
Secondly, it will not cause problems with "shoving" players in the wrong place after placement.
The third is... This will solve the old problem when a player log out, then someone place object at him position.

**Comment by elfl0rd** [comment]
still not implemented?

**Comment by beastyn** [comment]
Not yet

**Comment by StanKryvenko** [comment]
Lumber Stockpiles fixed in SVN
Need more investigation for other World Objects. Better to create a new task for them (with a list of objects which need to support pushing player from an object).

**Comment by elfl0rd** [comment]
> Need more investigation for other World Objects. Better to create a new task for them (with a list of objects which need to support pushing player from an object).

maybe better resolve it trough another way?
https://github.com/StrangeLoopGames/EcoIssues/issues/15195#issuecomment-626978197

>The easiest thing is to disable object collision if a player is inside.
At first, it is not very difficult at the level of logic.
Secondly, it will not cause problems with "shoving" players in the wrong place after placement.
The third is... This will solve the old problem when a player log out, then someone place object at him position.

**Comment by SlayksWood** [comment]
fixed for 0.9.0

**Comment by StanKryvenko** [comment]
> > Need more investigation for other World Objects. Better to create a new task for them (with a list of objects which need to support pushing player from an object).
> 
> maybe better resolve it trough another way?
> [#15195 (comment)](https://github.com/StrangeLoopGames/EcoIssues/issues/15195#issuecomment-626978197)
> 
> > The easiest thing is to disable object collision if a player is inside.
> > At first, it is not very difficult at the level of logic.
> > Secondly, it will not cause problems with "shoving" players in the wrong place after placement.
> > The third is... This will solve the old problem when a player log out, then someone place object at him position.

Disabling collision for an object enables cheating, where a player could go through any world object if he's inside. It could be used in a wrong way for a bad purpose.
Adding minimal distance for different world objects is another feature, not an issue.

**Comment by elfl0rd** [comment]
> 
> 
> > > Need more investigation for other World Objects. Better to create a new task for them (with a list of objects which need to support pushing player from an object).
> > 
> > 
> > maybe better resolve it trough another way?
> > [#15195 (comment)](https://github.com/StrangeLoopGames/EcoIssues/issues/15195#issuecomment-626978197)
> > > The easiest thing is to disable object collision if a player is inside.
> > > At first, it is not very difficult at the level of logic.
> > > Secondly, it will not cause problems with "shoving" players in the wrong place after placement.
> > > The third is... This will solve the old problem when a player log out, then someone place object at him position.
> 
> Disabling collision for an object enables cheating, where a player could go through any world object if he's inside. It could be used in a wrong way for a bad purpose.
> Well designed colliders should solve other issues with players inside

I do not see a problem in behavior where player can leave from world object e.g. after joining to the server and spawn inside of object, or placing object over self.
I do not propose to disable the collision of all objects, only one conflicting.
