### ISSUE TITLE
Unacceptable content from WordPress (api.slg)

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#15198]
EcoTree updates are full of messed up WP formatting. Ending up even EDITABLE block (you could simply edit in browser (not in inspector) update (see content on right and code on left)):
![image](https://user-images.githubusercontent.com/5720101/77007277-3aa8ab80-6964-11ea-9a1e-da8cbfd123a9.png)

We (web team) will be 100% unable to wipe off all this mess on our end, so content-manager, please, check everything you're copy-pasting to EcoTree content page, fix formatting, get rid of redundant styles and modes (by re-checking everything in WYSIWYG html-mode), produce only clean, plain, useful content. Thank you ;)

You could always check what content WP returns for that page here: https://api.strangeloopgames.com/wp-json/acf/v3/pages/2380

So if you see plain text with some small html tags like `<strong`, `<h1`, `<em` etc without deep nesting it's ok. If you see strange picture like this one, you've messed that up:
![image](https://user-images.githubusercontent.com/5720101/77008783-1ac6b700-6967-11ea-87a2-27c272b02a44.png)

P.S. I dunno whom to assign, so assigning John to choose proper assignee.
P.P.S. Issue partly fixes: https://github.com/StrangeLoopGames/EcoIssues/issues/15192

**Comment by rainfarmer** [comment]
So issue is wherever you are copying the blog from (mailer lite? google docs?). It's pasting the content as an editable field. That the user can edit from browser :)

If you need help figuring out good copy paste solutions, pass us where your copying from.
I think in past we copied from mailerlite preview email. but that might have its own issues.

**Comment by D3nnis3n** [comment]
I copy them from the other wordpress. It's not a user fault when the software doesnt strip such stuff, btw.

**Comment by denysaw** [comment]
Are you copying them from WP front-page or from back-end page WYSIWYG?
I'm sorry to hear that, but we also can't use such content. It's almost the same as without any content. Doesn't get our job done :/

**Comment by D3nnis3n** [comment]
A correctly implemented WYSIWG Editor only copies browser visible and
editor compliant basic formatting, not the whole underlying HTML. I've
never seen an editor doing this, it's a massive security risk, no matter if
i copy from somewhere else in the future. That's just a bad workaround.

Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 22:53:

**Comment by denysaw** [comment]
Which workaround? We didn't try to fix this on our side. Editable WYSIWYG is coming INSIDE the content from WP API. Check 2nd snapshot.

**Comment by D3nnis3n** [comment]
Yes, and that content it should NOT accept, otherwise its just badly
implemented. I can copy the stuff to e.g. redactor without that issue.
Clear fault in the WYSIWG on api wordpress.

I don't want to know what else can be copied in there if it doesnt care for
whatever is copied into it.

Workaround = Copying in from elsewhere, e.g. Steam. Mailerlite consists of
editable fields which the editor errorneously accepts.

Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 22:59:

**Comment by denysaw** [comment]
Aha.. So you think WP's WYSIWYG messing everything up, yep? Need to check. Can you gimme some part of content you are copy-pasting (maybe link to past from. Let it be latest update of `Work Parties` feature, cuzz we have that on the snapshot) in it and I'll check how it messes it up.

**Comment by denysaw** [comment]
Checked WP. This is how content of bad updates looks like even before WYSIWYG initialization:
![image](https://user-images.githubusercontent.com/5720101/77012249-ea364b80-696d-11ea-8150-33d712064690.png)

**Comment by D3nnis3n** [comment]
I'll look into that tomorrow, too late for today.

The WYSIWG should only accept the normal formatting, not the HTML stuff,
which should be an easy fix. Typically they come presetup with such
restrictions.

Alternatively we could use the editor that is used on the production wp for
news. You can try to copy stuff from there into it. (play.eco/wp-admin) I
dont think you have access to mailerlite.



Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 23:06:

**Comment by D3nnis3n** [comment]
Yah, it does not strip the stuff i copy from the WP or Mailerlite which
both are written in editable fields, a normal WYSIWG (like Redactor, which
i use) would only leave the markup, nothing else.

I can copy from Steam and edit a fourth time, but that costs time and as i
see it, the editor on API probably would accept anything, probably even
JavaScript. It shouldnt.

Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 23:12:

**Comment by denysaw** [comment]
Aha, gotcha. Will check those configs tomorrow. WYSIWYG itself uses html for markup, but maybe there's really some feature for stripping html tags during pasting. Will research. Ok, thanx ;)

**Comment by D3nnis3n** [comment]
Try to copy the wp backend stuff or mailerlite to any forums editor, you
will see that this will not happen, as the editor removes everything that
shouldnt be in there, like JavaScript, editable fields, nested shitcode and
probably even php.

Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 23:18:

**Comment by denysaw** [comment]
Yeah, great! Googled about TinyMCE in WP. And seems pasting could be easily configured! =) Go to sleep ;) Gnite! I'll look into that.

**Comment by D3nnis3n** [comment]
For the time being i copy from Steam.

Good nicht!

Denysaw <notifications@github.com> schrieb am Mi., 18. März 2020, 23:23:

**Comment by denysaw** [comment]
@D3nnis3n Solved =) I researched and the re-wrote TinyMCE plugin, where I stripping tags and their attributes by whiteList of both. So now you could paste code from wherever you wish ;)
If you need me to whitelist some tags or attribs - tell me, I'll add them in sec.
Thank you for showing research direction ;) Helped! =)
