### ISSUE TITLE
[0.9.0 staging-1470] Composite blocks are overgrown with grass

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15191]
![image](https://user-images.githubusercontent.com/45708377/76940384-31d7bb80-690b-11ea-8df9-29990e690b39.png)
For example Lumber:
![image](https://user-images.githubusercontent.com/45708377/76940420-49af3f80-690b-11ea-9591-6c1f2fdfa1bd.png)

**Comment by keegan-o** [comment]
Ah right, this is due to the blend priority in the blockset being set too low, should be more like lumber which is 90.

**Comment by Sekor2600** [comment]
fixed in Svn
