### ISSUE TITLE
Tooltips should persist when spawned from temp dialog

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15208]
![image](https://user-images.githubusercontent.com/3536496/77038849-0f6f9c00-69f8-11ea-932a-28cdfd79a964.png)
If I'm viewing a tooltip on a temporary dialog, the tooltip should survive even if that temporary dialog closes.  Like here, I'm trying to read the tooltip on the law and when the dialog goes away so does my tooltip.

**Comment by cemeceme** [comment]
I hope I'm not overstepping here, but can I suggest that the dialog itself won't disappear while being moused over or has a tooltip getting displayed?
