### ISSUE TITLE
make authorization and access control great again

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1520]
improve auth components like so:

1) anything with an auth component should have configurable access control to be one of the following modes:
 - Public, usable by anyone.  This is the default for all craft tables.
 - Restricted, usable only by a specific set of players.
 - Inherited, use same auth as that of the property it is on.  This is the default for non craft tables, eg stockpiles, chests, doors.

Only players with access to the property the object is on can remove the object.  anything on unowned property can be taken/used by anyone.

2) Auth components only function when on owned property.  If an object is on unowned property, it is always public and can not be changed.

3) Deeds will still use their own, separate auth with the same functionality as now, just with additional 'public' option (instead of manually having to add everyone as having access).  Deeds will be used for property and movable objects such as vehicles.

add the UI to configure this to the worldobject UI (use same layout as the deed UI / combine them to use the same)

**Comment by SeanAtr0n** [comment]
re: 2... except for vehicles?

**Comment by metachronism** [comment]
noted in item 3

**Comment by MarjieAVolk** [comment]
Vehicles can already be set public with a check box, so seems that should stay the same

**Comment by MarjieAVolk** [comment]
Just for the record, this is not something I would describe as "simplifying" :P
