### ISSUE TITLE
[0.9.0 staging-1472] Skills UI: Don't show scroll if pade doesn't need it

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15202]
I don't need scroll here
![bandicam 2020-03-19 10-52-00-772](https://user-images.githubusercontent.com/27898520/77035912-abd17880-69cf-11ea-9403-361e33cc3701.jpg)

**Comment by SlayksWood** [comment]
Still an issue.
Need to reduce this empty space:
![image](https://user-images.githubusercontent.com/45708377/78750087-30cd0380-7978-11ea-9ecb-d1289d1b3897.png)
