### ISSUE TITLE
Unplayable framerate!

### ISSUE THREAD

**Issue by Kezali** [StrangeLoopGames/EcoIssues#15200]
My frame rate was so incredibly low in the playtest server that I was struggling to enjoy it or want to walk anywhere, much less do anything else. I turned on steam FPS counter to compare just how much of a difference I am getting. On the live version, my fps varies depending on location or task, but is overall consistently between 28-40 FPS, usually hovering in the mid 30's range. On the playtest server, my fps while just standing in place and moving my camera only, was a consistent 6-8 fps! **_SIX to EIGHT fps!_** This is what steam overlay tells me, despite the in-game menu telling me I was at 12.5 fps. It was a tremendous chore just to walk to a few shops, and find a building location to get started.  T.T

Here is a couple screenshots of my settings for both live version and beta version. As you can see, there really isn't much difference, if any.

![20200318202613_1](https://user-images.githubusercontent.com/62364417/77022427-99b3f380-6957-11ea-8e10-4fe99d028773.jpg)
![20200318195440_1](https://user-images.githubusercontent.com/62364417/77022440-9f113e00-6957-11ea-86f7-b93345880688.jpg)

**Comment by beastyn** [comment]
@Kezali 
Thank you for your report.
Our team is currently working on the performance issue.
As a temporary measure try to put Minimap Details setting to the minimum.

Can you also provide your PC spec and which build version we were plting with this screenshots?

**Comment by Kezali** [comment]
pc specs? Sorry, it's just marked "potato."


AMD Radeon HD 5800 series

AMD Phenom II x4 945   3.00 GHz
8 GB RAM
64-bit os, x64 based processor


Windows 10 home  (version 1903  build  18362.720)

**Comment by Kezali** [comment]
I turned down the minimap detail to the lowest possible, and my fps is now in the 18-22 range consistently while looking around or walking.

It occurs to me also that when playing the current version, my frame rate plummets if I leave the map open while I play. I have to leave it closed for the most part, and just open it if I need to check something. 

A settings option to toggle the minimap off altogether might be helpful, but at the very least the listed performance impact should be changed from 'average' to 'very high'

**Comment by D3nnis3n** [comment]
You are not even meeting the minimum required specs for Eco, so please don't expect too much.

**Comment by mirasrael** [comment]
@Kezali can you provide any updates on your performance? We did some optimizations since this, let us now if things improved after that.

**Comment by mirasrael** [comment]
Closed due to no response for more than 2 weeks.
