### ISSUE TITLE
[0.9.0 staging-1472] Skills UI: losing highlight with some clicking

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15201]
1.Go to Carpenter profession
2. Pick the Carpentry
![bandicam 2020-03-19 10-34-12-722](https://user-images.githubusercontent.com/27898520/77035384-5e084080-69ce-11ea-983a-eb257966a786.jpg)
3. Click on the star in the right side
4. Carpentry Icon highlight will disappear.
![bandicam 2020-03-19 10-34-30-640](https://user-images.githubusercontent.com/27898520/77035649-0d451780-69cf-11ea-8940-40abc41bf917.jpg)

**Comment by SlayksWood** [comment]
Still an issue
Select gathering. I have another background and white highlight for icon: 
![image](https://user-images.githubusercontent.com/45708377/78748982-f3677680-7975-11ea-9f0e-a0cc60893b78.png)
Click in empty space in left side or in any place in right side. White highlight will disappear:
![image](https://user-images.githubusercontent.com/45708377/78749128-4ccfa580-7976-11ea-8aeb-a0ba7790750b.png)
But I still select Gathering.
