### ISSUE TITLE
Did offline food consumption rate change?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1521]
I invested in big stomach and 4000 calories didn't even last a day?

**Comment by SeanAtr0n** [comment]
Looks like it's ticking at 0.11/s now which would require 9500 calories/day?

**Comment by craig-jong** [comment]
Yea, it was doubled along with every other calorie cost. At least I think it was.

double check with when the new build is out.

**Comment by SeanAtr0n** [comment]
Looks like it's 0.06 in master now (5184/day), shouldn't it be low enough that you can go for a day w/o logging in?

**Comment by craig-jong** [comment]
Just tested this fast forwarding and it seems to be working correctly a ~20 hours to run out of calories.
