### ISSUE TITLE
[0.9.0 staging-1464] Tutorial: Colorie UI not coming back after tutorial is restarted

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#15215]
STR:
1. Join as a fresh player so that the tutorial triggers.
2. Do or skip the whole tutorial.
3. Go into the tutorial menu and restart the Tutorial.
4. Open each individual tutorial item and press skip (Do not press skip all)
5. When you are through skipping all tutorials, notice that the calorie UI is gone

Workaround:
Restart the tutorial and check the "skip all" checkbox. This will bring the calorie UI back.

![EcoCalBug](https://user-images.githubusercontent.com/11805935/77059847-e808d700-69d7-11ea-879f-c76f17b4006b.PNG)

**Comment by SlayksWood** [comment]
You don't need step to skip all tutorials.
It seems intended behavior, but it's very strange. Trigger for food tutorials is empty stomach. If you continue to spend calories tutorial will appear. But if you just skip tutorial one by one it willnot appear.
If UI display didn't depend on this, then it would be possible to leave it same like a shovel or mining tutorials, but here apparently some additional trigger needs to be done.
@johnkslg what do you think?

**Comment by johnkslg** [comment]
We can make the food tutorial appear if some other tutorial gets skipped (in addition to appearing if youre hungry)
