### ISSUE TITLE
0.9 - 1464: Transaction history sorted the wrong way

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#15214]
I am sure nobody really is interested in his day 2 trades when looking up transactions, therefore please sort it from newest to oldest, as looking things up in the "more transactions popup" is a pain

![image](https://user-images.githubusercontent.com/5678451/77058564-e9d19b00-69d5-11ea-8581-f541a8bbabcc.png)

**Comment by SlayksWood** [comment]
dup #14861
