### ISSUE TITLE
Skills feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15211]
Looking awesome!  Some more polish:
![image](https://user-images.githubusercontent.com/3536496/77041286-f6b5b500-69fc-11ea-9b09-c29d427c023d.png)

- [ ] Give a nice separation between profession and specialty, so the flow of it is easier to understand. Right now profession and specialty are mixed together on the left and right.  Something like this that divides them and makes it more clear:
![image](https://user-images.githubusercontent.com/3536496/77042089-709a6e00-69fe-11ea-9b3a-da13a26081cb.png)

- [ ] Add descriptive Manual Tooltips to everything that could use explanation here. The Level and Specialties text, explaining what Levels and Specialties are for the uninitiated.  

![image](https://user-images.githubusercontent.com/3536496/77042306-cff87e00-69fe-11ea-9850-89083d2baf78.png)
- [ ] Need a tooltip on these stars explaining what they are.

- [ ] Add a help button on this screen that takes you to the ecopedia page on skills

![image](https://user-images.githubusercontent.com/3536496/77042192-9a539500-69fe-11ea-996e-ff14c8fa452b.png)
- [ ] This tooltip is wrong, it says Chef Specialty but is Chef Profession.  It's going to be confusing for users the difference between a profession and a specialty, and not clear that a profession _contains_ specialties. We need to make this as clear as we can with the visuals.  Perhaps we give professions a fancier icon or a different style to them. @MilenkoTunjic 
Also, profession tooltips need to explain what a profession even is, and same for specialty.

![image](https://user-images.githubusercontent.com/3536496/77042393-f0283d00-69fe-11ea-9109-0cfdac5018c6.png)
- [ ] This tooltip makes no sense.   It should say 'Logging Level 7 Bonus: Calorie Reduction' or something like that. Then the first line should explain what a level bonus is. Then have a title for the list, 'Recipes given a calorie bonus:'
- [ ] Make 'level' scroll to the bottom to start if you dont have any upgrades for it. 

In general try to look at this with fresh eyes, pretending you know nothing about the game, and let it explain the concepts for you with the layout and tooltips and images.

**Comment by WeaselDog** [comment]
https://docs.google.com/document/d/14G8387OtKX90eMaPttuAZAXcR3U5Qk9sgWZ5AfODHrQ/edit

Some text for tooltips. Let me know if you want any edits or need more content.
