### ISSUE TITLE
[0.9.0 staging-1472] Can open 2 different window in main menu at one time

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15219]
Step to reproduce:
- mouse over Host a world
- hold LMB
- move mouse cursor to Your Worlds
- double click LMB:
![image](https://user-images.githubusercontent.com/45708377/77066535-66737200-69f4-11ea-8120-e29da979c8a4.png)
same in 0.8.3.

**Comment by SlayksWood** [comment]
need to reproduce in steam version to don't have this window:
![image](https://user-images.githubusercontent.com/45708377/107006278-f4d61b00-67a1-11eb-9ab2-a267b565358b.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.2.4 Release-156 and 0.9.3 Develop-177

Issue: Can also happen when clicking New Game and Host World button in quick succession.

Note:
- Issue doesn't happen with Your World button and Settings button.
- Triggers fixed for #20024 when clicking Continue in quick succession for 0.9.3 Develop-177
- Related #15219 

Repro for Server Crash:
1. Launch the game.
2. Click Continue in quick succession.
3. Observe.

Repro for multiple UI prompt:
1. Launch the game.
2. Click either New Game or Host World in quick succession.
3. Observe and try to navigate through.

Video Repro of server crash:
https://images.zenhubusercontent.com/42199084/28fc5e62-90a3-441b-8fcf-90218245e5cd/ddd.mp4

Log file of server crash:
[https://app.zenhub.com/files/42199084/bec62abf-5754-42e5-9dc9-77a7327f2e59/download]
(https://app.zenhub.com/files/42199084/bec62abf-5754-42e5-9dc9-77a7327f2e59/download)

Screenshot for 0.9.3 Develop-177
![Develop](https://user-images.githubusercontent.com/77248866/107008926-506acd80-67cf-11eb-907a-3fb18ddaa1d6.jpg)

Once this occurs, players are unable to go back to the lobby and are stuck in this UI.

**Comment by madpingui** [comment]
I can't replicate the issue, i can in the actual steam version, but i tried to replicate the problem in editor, and i even made a build of develop branch and i still can't replicate it.

**Comment by TwixterZ** [comment]
tested on 9.4 Develop 243, issue still persist:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/2ec4a66a-b05e-4e55-bb05-977f5183e71d)

https://gyazo.com/5cca6c4595a4b3ac915b0c690d189d89

**Comment by TwixterZ** [comment]
fix tested and confirmed for 9.4 develop 261
