### ISSUE TITLE
Where are my Hair and Belt!?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15221]
You can equip it, but you don't have any slot to see it. I have long wondered this question. I think that it's necessary to provide 2 additional slots for a belt and hair:
![image](https://user-images.githubusercontent.com/45708377/77069999-827a1200-69fa-11ea-87f8-c39675e9f30f.png)

**Comment by elfl0rd** [comment]
i think hair should be removed from items, lol.

**Comment by serpopov** [comment]
Hair is removed from recipies

**Comment by serpopov** [comment]
No icon for face slot yet

**Comment by SlayksWood** [comment]
I will close it when icon is changed.
