### ISSUE TITLE
[0.9.0 staging-1473] Minimap doesn't load.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15227]
![image](https://user-images.githubusercontent.com/45708377/77139222-31affb00-6a86-11ea-9f6b-044159c9b17b.png)
![image](https://user-images.githubusercontent.com/45708377/77139290-789df080-6a86-11ea-8feb-044309db152f.png)
![image](https://user-images.githubusercontent.com/45708377/77139302-82bfef00-6a86-11ea-8d1c-c18346caf1c7.png)

**Comment by D3nnis3n** [comment]
When fixed, please merge and create a new build for playtest, all the last builds had some serious issues that made them unusable for playtest.
