### ISSUE TITLE
Construction Tutorial - Beta 9.0 play test server

### ISSUE THREAD

**Issue by Taeila** [StrangeLoopGames/EcoIssues#15223]
When trying to complete the Construction Tutorial, the 'Select the block form you want to build the logs in by selecting it on the toolbar as shown' can not be completed.  When I try to shift + mouse scroll, that just moves my cursor to a different position on the toolbar and not change the form of the hewn logs.  With the new form system, you have to press F to change the building type. Possibly the tutorial needs to be updated to support this?

![constructiontutorial](https://user-images.githubusercontent.com/1370215/77092906-a6c8f500-69e0-11ea-9886-df302851b726.PNG)

**Comment by SlayksWood** [comment]
From #15447
> Bonus fix:
> ![image](https://user-images.githubusercontent.com/3536496/77976653-699f1580-72b2-11ea-9f0f-b84b7c742eec.png)
> 
> Text should be reworded, 'Change the form type in the building menu by pressing F while holding a hammer.'

> ![image](https://user-images.githubusercontent.com/3536496/77976710-8cc9c500-72b2-11ea-9b80-57deb17f9953.png)
> And 'Change the fill type in the building menu by pressing F while holding a hammer.'

**Comment by SlayksWood** [comment]
I just have tutorial with completed step, but I didn't do it. I pressed F with hammer before tutorial restart:
![image](https://user-images.githubusercontent.com/45708377/78219665-a6dcf080-74c8-11ea-8ea2-0ba2c8607561.png)
Text doesn't change.

**Comment by beastyn** [comment]
1. Надо написать 
Open construction menu by pressing and holding 'F'
