### ISSUE TITLE
[0.9.0 staging-1472] Work Party include the order which I removed from it

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15220]
Step to reproduce:
- place Carpentry table and start 2 order (Butchery table and Farmers table for example)
![image](https://user-images.githubusercontent.com/45708377/77069207-07fcc280-69f9-11ea-8aab-8f0cb0666f55.png)
- start to create WorkParty:
![image](https://user-images.githubusercontent.com/45708377/77069224-11862a80-69f9-11ea-8798-0f1904e1a35d.png)
- it suggests me to create one Work Party, but I want to split it to 2 Work Parties
- so I delete from WorkParty Butchery table:
![image](https://user-images.githubusercontent.com/45708377/77069329-45615000-69f9-11ea-8d80-d8397461f422.png)
![image](https://user-images.githubusercontent.com/45708377/77069340-48f4d700-69f9-11ea-8c09-c59b23a81169.png)
- press submit. Rename WorkParty and Post it:
![image](https://user-images.githubusercontent.com/45708377/77069392-6629a580-69f9-11ea-94ab-0d31f57c3d80.png)
- try to add another workparty for butchery table project. I can't:
![image](https://user-images.githubusercontent.com/45708377/77069436-79d50c00-69f9-11ea-94f0-cd890305da0a.png)
- if I try to delete order for Butchery table it says that this work order is part of my Farmers workparty, but I delete this order from it:
![image](https://user-images.githubusercontent.com/45708377/77069512-9bce8e80-69f9-11ea-8670-7117e598e0d7.png)

**Comment by johnkslg** [comment]
Good find. Fixed.
