### ISSUE TITLE
Adv. Baking - lvl 3 double speed is not added to all items

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#15225]
Adv. baking items that normally takes 1min to make, now with the lvl 3 double speed takes 54sec... :-)

**Comment by SlayksWood** [comment]
without talent:
![image](https://user-images.githubusercontent.com/45708377/77141152-f95feb00-6a8c-11ea-9e3b-a8bab1d43b0a.png)
with talent:
![image](https://user-images.githubusercontent.com/45708377/77141199-1bf20400-6a8d-11ea-9e4d-1c013cf44195.png)
Talent seems work correct.
Can you name certain recipes?

**Comment by Zoneman81** [comment]
![20200320105056_1](https://user-images.githubusercontent.com/38038590/77152765-dd624680-6a98-11ea-8f70-d05af597ee5d.jpg)
Took me 1min to make without the talent, and now it takes me 54sec with the talent

**Comment by SlayksWood** [comment]
1 minute or 1 minute 48 sec? check it in tooltip:
![image](https://user-images.githubusercontent.com/45708377/77153884-b19c8c00-6aab-11ea-92f0-68de0aa8a46e.png)
I aasume it related with #15228

**Comment by Zoneman81** [comment]
ye, UI problem
