### ISSUE TITLE
Laws UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15234]
![image](https://user-images.githubusercontent.com/3536496/77188582-74c49b00-6a93-11ea-8ae5-303b95b75e27.png)
- [ ] These buttons to move/delete a block arent selectable
- [ ] Make the trigger/if/else text bigger, since theyre headers
- [ ] Remove the garbage can icon from the game, use the red minus everywhere instead. Make it drop below the thing its deleting like above.
- [ ] Notice that when you mouse over something to delete it, the highlight is behind the thing.  Make it lightly over the top, so you can see what would be deleted.

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/15115

**Comment by SlayksWood** [comment]
You can delete last section, you can't press this "-":
![image](https://user-images.githubusercontent.com/45708377/85270136-87c77c80-b481-11ea-82ab-727a6a431475.png)
But you can delete it if you add second section, but this "-" will overlap expand from another section:
![image](https://user-images.githubusercontent.com/45708377/85270278-bcd3cf00-b481-11ea-9f31-adafe17f1d0b.png)
May be change it position and we can always display this "-" as delete full section:
![image](https://user-images.githubusercontent.com/45708377/85270475-02909780-b482-11ea-96ea-99990de102c5.png)
So you can delete section when it's collapsed:
![image](https://user-images.githubusercontent.com/45708377/85270713-674bf200-b482-11ea-99ca-5f357d6edfdd.png)
