### ISSUE TITLE
Editable text needs polish everywhere

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15233]
When editing the section title, its all buggy:
![image](https://user-images.githubusercontent.com/3536496/77187871-5ca04c00-6a92-11ea-8d67-d18605fbbad6.png)

![image](https://user-images.githubusercontent.com/3536496/77187840-5316e400-6a92-11ea-8673-f3ba13d1304b.png)
![image](https://user-images.githubusercontent.com/3536496/77187860-58742e80-6a92-11ea-9d03-13e8c991b1f4.png)
- The cursor is placed wrong
- The text size is wrong.

We'll need to fix this with all text edit boxes.
Solving this in a systematic way would be preferred. IE, instead of manually going through and setting the size of each text editor, make the text editor prefab automatically query the size of the display text and force itself to those settings.

**Comment by johnkslg** [comment]
Also, the description text in laws is not left aligned
![image](https://user-images.githubusercontent.com/3536496/77188261-ef40eb00-6a92-11ea-96ff-37977a2abe99.png)

**Comment by SlayksWood** [comment]
> (![image](https://user-images.githubusercontent.com/45708377/76936390-f2f23780-6903-11ea-9db6-da6e2bcd0b67.png)`)
> ![image](https://user-images.githubusercontent.com/45708377/76936423-fe456300-6903-11ea-8ebd-65af03772729.png)
> ![image](https://user-images.githubusercontent.com/45708377/76936475-11583300-6904-11ea-84c5-21619facdaa3.png)

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/14926
