### ISSUE TITLE
Hosted World feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15237]
![image](https://user-images.githubusercontent.com/3536496/77203143-fa087980-6aac-11ea-880e-78f18494cf14.png)
- [x] Remove the text next to eco that says 'subscription' here, and likewise for similar pages.  Now that there are just three options, and the one you pick stays highlighted, its not longer needed. 

![image](https://user-images.githubusercontent.com/3536496/77203220-215f4680-6aad-11ea-8b5e-f1e9b789bf89.png)
- [x] My world started 'paused', is that correct? We should make it more clear they need to unpause it to make it start, a big banner at the top of the world or something saying Currently Paused. Also what happens if you try to login to a paused world? It should explain its paused. 
- [x] Also make 'Pending' appear in bold and blink. Should probably say 'loading' which is more clear.

**Comment by rainfarmer** [comment]
first login to paused world will unpause world

**Comment by johnkslg** [comment]
ah, can you make that clear in the hosted world page?

**Comment by denysaw** [comment]
@johnkslg `Remove the text next to eco that says 'subscription' here, and likewise for similar pages.`
Remove that only for HostedWorlds menu or for usual menu also?
