### ISSUE TITLE
Hosted World errors not being displayed

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15238]
I get this when trying to unpause:
![image](https://user-images.githubusercontent.com/3536496/77210012-1d3b2500-6abd-11ea-89ed-88d5a05592a7.png)

- [x] Denys: All errors should have a 'details' section that will allow the user (and dev) to see what is wrong right there in the API
- [x] Denys: All errors should be logged in an accessible place, and that log should be monitored and issues created when problems hit users.
- [x] Denys: Any error which does not return an explanation (anywhere in all of Eco, server, devops, etc) is a bug, and an issue must be filed
- [x] Jeff: Add text explaining at the top of the worlds page how you connect to a world.  Include links to client somewhere (I see them on the citizen page)
- [x] Denys: Add a header at the top of the list that says Your Worlds

**Comment by rainfarmer** [comment]
![image](https://user-images.githubusercontent.com/7343272/78085742-ac272780-7370-11ea-8bc5-476b97424088.png)

kinda convoluted instructions, but as concise as i can get it
