### ISSUE TITLE
Slowdown after 30 minutes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15236]
Steps:
1. /civics spawngov
2. go open a few UIs.  District office, edit a district, etc.
3. Wait 20 minutes
4. Perf drops to 12fps. 

Profiler looks like this, something weird with UIs:
![image](https://user-images.githubusercontent.com/3536496/77197202-02a78280-6aa2-11ea-83e1-1d35f35f4f74.png)

Profile data saved here:
https://drive.google.com/open?id=1BtHB3eyR7MALPcB1u2J8tvsfeZEdY18q

**Comment by mirasrael** [comment]
Waiting for this fix: https://github.com/StrangeLoopGames/EcoIssues/issues/15825

**Comment by revtje** [comment]
Had ~40 fps. Went to the carpenters place (Engimage) on the playtest server and it went down to ~19
[40fps_EcoProfilingData-2020-06-16T12-46-47.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4786109/40fps_EcoProfilingData-2020-06-16T12-46-47.zip)
[19fps_EcoProfilingData-2020-06-16T12-47-13.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4786110/19fps_EcoProfilingData-2020-06-16T12-47-13.zip)

**Comment by Engimage** [comment]
[EcoProfilingData-2020-06-17T00-19-02.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4789174/EcoProfilingData-2020-06-17T00-19-02.zip)
At my place, FPS degraded from 40+ to 13

**Comment by SlayksWood** [comment]
After time FPS drop to 15-20. New world, just some UI tests and afk near 30 minutes.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4884429/Player.log)
![image](https://user-images.githubusercontent.com/45708377/86772138-25af6f80-c05c-11ea-85b0-e69577cf26ec.png)
https://drive.google.com/file/d/17eCcExJkPjrnCXTUQ0MyIQo779wvx4tk/view?usp=sharing

**Comment by SlayksWood** [comment]
Will recheck after fixing #17225

**Comment by mirasrael** [comment]
It was improved with multiple performance fixes, we still have this issue, but less noticeable and not so fast as before (by user reports). So it may be renamed to "Slowdown after 30 minutes" :) There still lot of work, but we can do it after 9.0.

**Comment by johnkslg** [comment]
Gonna close this to start a fresh epic
