### ISSUE TITLE
Something wrong with Component icon displaying.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15248]
![image](https://user-images.githubusercontent.com/3536496/77232503-a7879580-6b5e-11ea-8cea-cb740ff6fba1.png)

**Comment by SlayksWood** [comment]
It's more global problem. Sometimes icon can missing in one crafttable, all's right in other crafttable, in third icon is wrong: 
![image](https://user-images.githubusercontent.com/45708377/77296617-0c76f300-6cf9-11ea-88ab-b7e712a5ff45.png)
Seems we have all component icons, but it doesn't always display correct.

**Comment by SlayksWood** [comment]
> Power should have another icon, but it's missing in game yet:
> ![image](https://user-images.githubusercontent.com/45708377/72781969-a7891900-3c33-11ea-9bb2-1c16cea8dc85.png)
> For example Sawmill:
> ![image](https://user-images.githubusercontent.com/45708377/72782020-cb4c5f00-3c33-11ea-82fe-7316b90b26c2.png)
