### ISSUE TITLE
0.9 lumber stockpiles have bug again

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15244]
![изображение](https://user-images.githubusercontent.com/4980243/77223986-6c8f5d00-6b72-11ea-9235-856f736929ac.png)

**Comment by Sekor2600** [comment]
Yeah but the Lumberstockpiles are not finished.

**Comment by SlayksWood** [comment]
Seem should be fixed with #15009
![image](https://user-images.githubusercontent.com/45708377/77399049-a9996080-6db9-11ea-83e1-79394e991461.png)
