### ISSUE TITLE
Minimap detail slider has no effect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15249]
Low:
![image](https://user-images.githubusercontent.com/3536496/77233343-259a6b00-6b64-11ea-8d10-87739aa468e8.png)

High:
![image](https://user-images.githubusercontent.com/3536496/77233351-31862d00-6b64-11ea-94f9-02397b9a975f.png)

Only difference seems to be a massive drop in performance.

**Comment by redwyre** [comment]
You're incredibly zoomed in so it will be selecting a higher LOD already. If you zoom out you should be able to see the difference. But yeah I'm trying to completely change how this works.
