### ISSUE TITLE
Eco Tree Backend Issues

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15243]
- [x] Quotes are displayed weirdly in Multi-Lines (Community -> Events for example)
- [x] Using center on images only works in the editor but not on frontend (Life -> Invertebrates for example)
- [x] Blogs are not sorted by date but by order in backend (which cannot be changed but via switching content manually), which is bad for adding older stuff. (Operations -> Constitution for example)

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/15243 potentially

**Comment by denysaw** [comment]
Could be re-checked on `developland`.
