### ISSUE TITLE
Royal Otter - ClientReceiveExceptions

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15242]
I have a lot of these in the dumps folder:

> --BEGIN DUMP--
> Dump Time
> 03/21/2020 04:51:50
> 
> Exception
> Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Components.MountComponent.<>c__DisplayClass10_0.<Dismount>b__0(Player occupant)
>    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
>    at Eco.Gameplay.Components.MountComponent.Dismount(Int32 playerID)
> 
> --END DUMP--

No crash.

**Comment by SlayksWood** [comment]
@D3nnis3n Check it please after updating playtest to new staging. I assume it should be fixed with Vehicle crash fixes.

**Comment by SlayksWood** [comment]
Seems fixed.
