### ISSUE TITLE
0.9 Disconnected from any server after 10-20seconds of playing.

### ISSUE THREAD

**Issue by JambaPlays** [StrangeLoopGames/EcoIssues#15252]
Hey guys, I just start facing some issues with my lovely Eco game a couple days ago. I shoot the video about it, it's like 3 minutes but it shows everything what I'm having trouble with. 
https://youtu.be/6S-IrDuVko4
I played ECO for like 2 maybe 3 months and everything was fine. But now it's that disconnecting failure that really bothers me. I was in the middle of my streaming season on one server and now can't end it because of that, wich is sucks. Let me know if you need any more files or something else. 
Thanks, Jamba Pays.

LOG files:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4363953/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4363954/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4363955/Player-prev.log)

**Comment by JambaPlays** [comment]
By the way, if I start local solo game I don't have that problem at all and can play game as usualy.

**Comment by JambaPlays** [comment]
![image](https://user-images.githubusercontent.com/62482090/77275727-69d65a00-6c8f-11ea-83a5-2f91383c4ff3.png)

**Comment by SlayksWood** [comment]
@JambaPlays 
write to me in discord Kirill (Slayks)#6251 , можешь на русском.

**Comment by JambaPlays** [comment]
So we tried with 0.9 version, the same issue. Here are the logs:
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4369279/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4369280/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4369281/Player.log)

**Comment by mirasrael** [comment]
@JambaPlays did you try to connect to USA servers?

**Comment by JambaPlays** [comment]
Yes, I connected to 2 US located servers and the same issue, I had ping about 30-40ms on those.

**Comment by JambaPlays** [comment]
I want to try to delete all the game files, including those in the AppData, maybe...

**Comment by JambaPlays** [comment]
I deleted all the game files and all the files in Appdata folder, after that I use CCleaner to finesse everything. After that I reinstall the game, I connectd to vanilla server with no mods and it still has the same issue. Also I did the test, I played random youtube video while I'm trying to play the game, and I noticed when I have that red icon on, I'm still getting internet packages from the internet. So I assume it's not the internet/provider problem. 

I have COMODO firewall and Avast antivirus installed, but I run the game with those programs closed and it didn't help. I'm running out of ideas guys...
@mirasrael @SlayksWood

**Comment by JambaPlays** [comment]
I fixed this issue. I tried so many different options but the only solution that helped was a manually reboot of my router. That’s kinda weird because all the other online games worked well, but it really helped Eco. 4 hours after that with no disconnects.

**Comment by mirasrael** [comment]
@JambaPlays I really glad you was able to fix your issue. I think we should add this to troubleshooting wiki. Thanks for info! Probably your router for some reason identified Eco traffic as DDoS.

**Comment by mirasrael** [comment]
Updated [wiki](https://github.com/StrangeLoopGames/EcoIssues/wiki/Troubleshooting:-Can't-connect-to-the-server#router-may-recognize-eco-traffic-as-ddos-or-drop-packets-for-other-reasons)
