### ISSUE TITLE
[0.9.0 1464] Tree icons cover claims in the map

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15259]
![image](https://user-images.githubusercontent.com/61889138/77246800-8ee0b380-6c22-11ea-8b6c-755772e194fa.png)

![image](https://user-images.githubusercontent.com/61889138/77246801-956f2b00-6c22-11ea-851b-4bdcb4e92234.png)

Should be "layered" the other way around? so the tree's faintly appear through the claim

**Comment by Engimage** [comment]
I do agree. With current implementation many claims are effectively consealed under the trees especially if those are tree farms.

**Comment by SlayksWood** [comment]
This was so in 0.8.3 too, but now I assume it should be changed.
