### ISSUE TITLE
Cleanup icons on minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15250]
![image](https://user-images.githubusercontent.com/3536496/77234252-19191100-6b6a-11ea-9896-62156a6be895.png)
Minimap should only show things that are a destination. That means no signs, light posts, chests, chairs, furniture, beds, etc. Just tables really.

**Comment by WeaselDog** [comment]
Categories we want hidden by default: Housing, Lights, Power, Sign, Storage
