### ISSUE TITLE
Deed tooltip should not show plot list

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15257]
![image](https://user-images.githubusercontent.com/3536496/77243961-303d1a80-6bcd-11ea-83fc-f18e0167a399.png)
Dont show this anywhere, its useless. Just show number of plots and sq m
see if theres other places its getting shown

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/77417930-31da2e80-6dd7-11ea-81db-9584c36867dd.png)
