### ISSUE TITLE
Database Exception

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15258]
> [03:30:48.632] [41] [Error] [Eco] Error inserting stat of type LostElection into databaseLiteDB.LiteException: This database exceeded the maximum limit of collection names size: 3000 bytes
>    at LiteDB.CollectionService.Add(String name)
>    at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
>    at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
>    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
>    at LiteDB.LiteCollection`1.Insert(T document)
>    at Eco.Stats.Stats.<>c__DisplayClass22_2.<Record>b__1()
>    at Eco.Stats.PendingWritesDiskService.WithTransaction(Action action, Int32 timeout)
>    at Eco.Stats.Stats.Record(IStat obj)
>  
> [03:30:48.632] [41] [Error] [Eco] Error inserting stat of type LostElection into databaseLiteDB.LiteException: This database exceeded the maximum limit of collection names size: 3000 bytes
>    at LiteDB.CollectionService.Add(String name)
>    at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
>    at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
>    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
>    at LiteDB.LiteCollection`1.Insert(T document)
>    at Eco.Stats.Stats.<>c__DisplayClass22_2.<Record>b__1()
>    at Eco.Stats.PendingWritesDiskService.WithTransaction(Action action, Int32 timeout)
>    at Eco.Stats.Stats.Record(IStat obj)

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/dbexception.zip

**Comment by johnkslg** [comment]
Compressing our names down: 
![image](https://user-images.githubusercontent.com/3536496/77701722-2e2fde80-6f74-11ea-8d75-bb39f35e8c7c.png)

This should buy us some time, but we will have to move to a new DB system at some point, or have multiple DBs.

**Comment by johnkslg** [comment]
Putting fix on hold till we update litedb versions

**Comment by johnkslg** [comment]
Checking in fix from https://github.com/StrangeLoopGames/Eco/pull/5814 until LiteDB upgrade
