### ISSUE TITLE
Contract Board: Contracts

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15256]
When setting up a contract it properly takes the money to be paid to contractors from the person setting the contract up, however when the contract is marked as complete by them the payment does not go to the correct person that accepted the contract and fulfilled it.

Example: I contracted Player X to build a workshop for me. They come, I supply them the materials, food, etc, as promised and then they build the workshop (1 room say 25x25 blocks) and once its complete I mark the contract as finished. Money goes to Player Z instead of Player X when they were not even on the contract.

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1540. Closed for now. Reopen please if it happens again.
