### ISSUE TITLE
Powered Cart Skidding

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15253]
After dismounting the Powered Cart and attempting to access its inventory or leaving it unattended I will find that it is either in the process of just randomly skidding itself to the side or has already done so to the point that it is half stuck in a wall and with its crappy turn radius it is difficult to manuever out of that position, it also does not like to respond to /freecar when it is half in the wall so I generally have to manually manuever it back to a place where it is within range of the storage I park it near.

**Comment by SlayksWood** [comment]
Can you provide some video or screenshots?

**Comment by Daelmaron** [comment]
I will see what I can do to grab some today.

**Comment by TwixterZ** [comment]
@Sarah-Graesyn as this issue was raised a year ago without further update, i will proceed to close this now.

If you still facing this issue in the latest version of ECO, please raise a new issue.
