### ISSUE TITLE
Every time I try to run a server on my computer I get the "Failed to connect - connection timed out" message. Any ideas as to why this might be happening?

### ISSUE THREAD

**Issue by sekulica88** [StrangeLoopGames/EcoIssues#15255]
[EcoCrashReport.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4364647/EcoCrashReport.txt)

**Comment by D3nnis3n** [comment]
Please attach your latest logs from /Steam/steamapps/common/Eco/Eco_Data/Server/logs

**Comment by sekulica88** [comment]
[log_200321112404.log](https://github.com/StrangeLoopGames/EcoIssues/files/4366301/log_200321112404.log)

**Comment by D3nnis3n** [comment]
Corrupted Installation.

Please try removing the mods folder from Eco_Data/ and then repair the game.

If this doesn't work, please backup your /Storage/ folder, then uninstall Eco, then delete the whole /Steam/steamapps/common/Eco/ folder and reinstall the game.
