### ISSUE TITLE
Wood Cart shown as full, yet nothing is in it.

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15251]
![WoodCart](https://user-images.githubusercontent.com/8851259/77234411-82227800-6bae-11ea-9a83-a9ad37f7a976.jpg)

**Comment by Knigge** [comment]
Can not add items to it either because of weight restriction - items weighing less than 50kg is possible to add (eg. shovel when trying to add dirt)

**Comment by BennoHase** [comment]
I had the same issue. I used the hammer to take the cart back to the inventory and the bug is gone after placing it again.

**Comment by Engimage** [comment]
This issue is solved in the new build
https://github.com/StrangeLoopGames/EcoIssues/issues/14824
