### ISSUE TITLE
Planted seeds appear out of nowhere when harvesting

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#15260]
Seen it 3 times now. Once when harvesting Wheat, once when harvesting Corn and once when harvesting Beets
The seeds that automatically appear will eventually just die in a couple of hours (maybe minutes?)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4365071/Player-prev.log)
[Player - Copy.log](https://github.com/StrangeLoopGames/EcoIssues/files/4365072/Player.-.Copy.log)
![20200322115848_1](https://user-images.githubusercontent.com/39825431/77247818-f4d63680-6c34-11ea-90f5-a0a62ad69912.jpg)

Found on 0.9.0.0 beta staging-1464

**Comment by SlayksWood** [comment]
Staging 1478:
I collected 81 Corn and 7 new corn appeared:
![image](https://user-images.githubusercontent.com/45708377/77405362-203b5b80-6dc4-11ea-89ce-4de6b2a167ab.png)
But after a few minute they died:
![image](https://user-images.githubusercontent.com/45708377/77405390-2c271d80-6dc4-11ea-8101-7bc416cbff30.png)

**Comment by trickenso** [comment]
This happens to me often when felling trees or clearing land for farm or building - not just when harvesting crops. It can be any plant that's in the area that spreads into the cleared land.
This can be especially surprising when a recently-cleared area is suddenly covered in many tree saplings all at once, or if it happens just after you have cleared a plant.

Some kind of cooldown between player clearing an area and plants repopulating might be helpful.
