### ISSUE TITLE
[9.0] UI windows minimum width

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15267]
In 9.0 UI windows such as stockpile inventory have a very large minimum width, which is bigger than 8.3 default window size. After switching from 8.3 to 9.0 this resulted in a lot of confusion for me as you can't downsize the window to desired size and it is almost a full screen for me playing in 1080p.

**Comment by johnkslg** [comment]
Should make windows auto clamp size if theyre off screen
