### ISSUE TITLE
Equipping Big Backpack Gets Overwritten by Regular Backpack

### ISSUE THREAD

**Issue by clairmont32** [StrangeLoopGames/EcoIssues#15262]
Hi,
Version 0.8.3.3

I went to equip a big backpack I created from the tailor table. I noticed the inventory slot size didnt increase so hovered over the backpack tile to verify it was equipped. It stated Backpack, not the Big Backpack. I had another to spare in storage so I tried it again to verify its a bug. The same thing happened a second time but then I noticed the crafting update dialog stated I equipped a Big Backpack.

Screenshot attached. Please let me know if there's any additional information, repro, or fix confirmations I can help with.
![image](https://user-images.githubusercontent.com/6239004/77275893-bfab0200-6c8f-11ea-8e33-6eeee1f8e4d1.png)

**Comment by SlayksWood** [comment]
@clairmont32 
Thank you for report.
1. Another BackPack don't add new slots.
2. It should add more weight. You can check it here:
![image](https://user-images.githubusercontent.com/45708377/77402566-e7998300-6dbf-11ea-8afc-e5d765678ace.png)
3. we also have bug with tooltip (it can show wrong tooltip), this can confuse you. More detailed you can read here #9344.

So if you have another problem, then please provide more information, step be step. And don't forget to provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by clairmont32** [comment]
The added weight was it. Thanks for the information.
