### ISSUE TITLE
[0.9.0 staging-1477] Iron/modern Rock drill in 3d view differ from 1st view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15263]
Iron:
![image](https://user-images.githubusercontent.com/45708377/77291548-899d6a80-6cef-11ea-9d38-3ceffa529684.png)
![image](https://user-images.githubusercontent.com/45708377/77291879-23651780-6cf0-11ea-8122-99ac967b3651.png)
Modern:
![image](https://user-images.githubusercontent.com/45708377/77291739-e567f380-6cef-11ea-9e25-7642372886bc.png)

**Comment by StanKryvenko** [comment]
Fixed in SVN
