### ISSUE TITLE
[9.0 Staging-1477] Masonry Table not correctly querying and pulling resources

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15269]
![20200323082052_1](https://user-images.githubusercontent.com/1329717/77321026-9023e600-6cdf-11ea-98d1-d09fbbdf0fe2.jpg)
![20200323082056_1](https://user-images.githubusercontent.com/1329717/77321030-90bc7c80-6cdf-11ea-843c-acd1d3c67348.jpg)
![20200323082046_1](https://user-images.githubusercontent.com/1329717/77321031-90bc7c80-6cdf-11ea-955f-19a90e220a7c.jpg)

There is clearly mortar available in the storage attached to the Masonry table but it is not reading and pulling it out of the chests, it does pull it if I take it out of the chest and put it in the attached stockpile instead however.

**Comment by Daelmaron** [comment]
So now my masonry table just straight is refusing to craft period. I have unregistered it from the storage and re-registered it. I have emptied everything and put it back in. It just isn't crafting.

The only thing I haven't done is remove it and replace it as it has several very high work orders on it.

![20200323125854_1](https://user-images.githubusercontent.com/1329717/77347836-70ec7f00-6d06-11ea-8b20-8a21ca047c3f.jpg)
![20200323125901_1](https://user-images.githubusercontent.com/1329717/77347844-74800600-6d06-11ea-9fb1-f11551600c93.jpg)
![20200323125904_1](https://user-images.githubusercontent.com/1329717/77347846-75189c80-6d06-11ea-9fff-1d15412936c5.jpg)

**Comment by mirasrael** [comment]
I see work order started by another person? Every player has own linked storages, so you're controlling only source storages for own orders. In this case work order owner should connect storage chest.

**Comment by SlayksWood** [comment]
@Daelmaron 
Do you have this problems with your orders?

**Comment by Daelmaron** [comment]
@SlayksWood even with me having placed the order under myself it doesn't seem to want to pull out of chests. My other tables seem to do so just fine its just my masonry table that isn't

**Comment by IcedForge** [comment]
Will close this since we are post several patches with no re occuring similar issue, please reopen with new commentary if there is still an issue with workbenches not taking materials properly.
