### ISSUE TITLE
[9.0 Staging-1477] FPS Drop

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15276]
Just after the update today I was the first to log in and had a solid 140 FPS connected to the server, looking at it now I am down to just 60. 

**Note:** this is a marked improvement from before the update still but rather confusing.

**Comment by SlayksWood** [comment]
Yes, there is a problem with FPS dropping over time. First of all now solving the problem of low FPS, then this problem.
In any case dup #11248
