### ISSUE TITLE
Lumber Stockpile graphics are off

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15270]
the graphics for the lumber stockpile are offset really badly.

loaded this up on a single player while waiting for the server to come back up and snapped a screenshot of that real quick

![20200323092718_1](https://user-images.githubusercontent.com/1329717/77326962-9074af00-6ce8-11ea-8bb9-38678d4df2f9.jpg)

**Comment by SlayksWood** [comment]
dup #15009
