### ISSUE TITLE
[0.9.0 staging 1477] Any player can remove for sale/purchase items from a store

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15278]
Tested with NNMike.

I can remove items from his store for sale section and also purchase section (Red Remove button) cannot re-order them nor adjust prices, I do not have any auth to his claim nor store. store has the default "everyone" auth

Could be related to https://github.com/StrangeLoopGames/EcoIssues/issues/15274

**Comment by beastyn** [comment]
@MishkaFur 
1. Was it an old one store, from the previous version?
2. Did you give this store to NNMike at some point?
I mean we've owned it for some time before Mike has it

**Comment by SlayksWood** [comment]
you can look at #15282. If you had this steps than we found your problem. If not than we continue to investigate it.

**Comment by MishkaFur** [comment]
@beastyn This was an old store, NNMike did not pick it up and place it back down though due to it storing data this may not work?
2) Nope i have never owned this store.

**Comment by SlayksWood** [comment]
@MishkaFur 
We need to wait, if it didn't related with migration, it should repeat. We'll continue investigation. If you will have this bug another time, tell us please.

**Comment by MishkaFur** [comment]
@SlayksWood Checked this on stores that were recently crafted and placed by Shalrak and Racerand, unable to delete things so think you can close this.

Mishka

**Comment by mirasrael** [comment]
@MishkaFur thanks for report.
