### ISSUE TITLE
website feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15277]
![image](https://user-images.githubusercontent.com/3536496/77360845-55d03e00-6d0b-11ea-895c-5c1dc72ac574.png)
- [x] Tooltips for team members should display their title and bio (perhaps with a 'more...' button if the bio is long).  Tooltip should be something like this: 
Eco Dev: John Krajewski
Currently working on 'Biomes'  <web link to feature ideally>
Eco Designer, Strange Loop CEO
<bio here>

- [x] Can you make the venture beat review link go directly to the section on Eco on that page?

![image](https://user-images.githubusercontent.com/3536496/77360909-74363980-6d0b-11ea-832f-ff6805352bd7.png)
- [x] Lists are a too-small font

- [x] Change color of notification bubbles to yellow

**Comment by rainfarmer** [comment]
Tooltips for team members should display their title and bio (perhaps with a 'more...' button if the bio is long). Tooltip should be something like this:
Eco Dev: John Krajewski
Eco Designer, Strange Loop CEO

bios dont support this cause of limitations with wordpress. their user api wont pass custom fields, like job title. we would have to go in and customize wordpress api. dont think its worth it.

**Comment by rainfarmer** [comment]
> Can you make the venture beat review link go directly to the section on Eco on that page?

Don't think so. no id tags near it. @denysaw do you know a hack for it?

**Comment by denysaw** [comment]
@rainfarmer @johnkslg 
As there're no anchors in page content, yeah, we could just open a separate page (our url) with iframe, where loaded venturebeat and scrolled to Eco's position (in top pixels offset).

**Comment by johnkslg** [comment]
Any way around the wordpress limitation?  There should be someway. Could move the bios to a shared location where both tree + bio page can access them.  

Mainly we want the title, bio might not be needed...

**Comment by rainfarmer** [comment]
@johnkslg we can open up wordpress and find a solution. 
But seems a lot for adding job titles. considering you can click the user to get all that info. And everyones title will be about the same except you :)

**Comment by johnkslg** [comment]
hm yeah would just like somthing that personalizes it a bit more, somehow
