### ISSUE TITLE
[0.9.0 Staging 1477] digging Under Arrastra, when trying to place a flooring block there is something from the Underneath of the Arrastra blocking it 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15271]
**Version:** 0.9.0.0 beta staging-1477

i have 5 Arrastra sitting on the Natural Rock, i now removed the Floor **UNDER** them to make more space (also some were crafting so didn't want to cancel any orders) but when i try and place Mortared Limestone back underneath to give them a Floor there is **something in the Center underneath** that stops me placing a block
![snap6492](https://user-images.githubusercontent.com/29383891/77338115-ca15dc00-6d21-11ea-987d-ef2e25eb59e3.png)
![snap6493](https://user-images.githubusercontent.com/29383891/77338202-eade3180-6d21-11ea-9547-a7c46ba33f72.png)
![snap6494](https://user-images.githubusercontent.com/29383891/77338211-ef0a4f00-6d21-11ea-99cd-b47c963a95b9.png)
![snap6495](https://user-images.githubusercontent.com/29383891/77338225-f3366c80-6d21-11ea-8b48-6b4def76eb6e.png)

this is for **every** Arrastra placed (as i thought it might just be an invisible block under one of them)

![snap6498](https://user-images.githubusercontent.com/29383891/77338502-5cb67b00-6d22-11ea-913d-f9c3dd696367.png)

Also noticed that you cannot walk under the Central part as something is physically blocking you

to Duplicate:

place Arrastra on Floor Dig 2 blocks out underneath try and fill back with a block or even try walking underneath, everything but central dark patch is ok

**Comment by Conchipedia** [comment]
![snap6499](https://user-images.githubusercontent.com/29383891/77339586-e87cd700-6d23-11ea-8380-37b5f95c804b.png)
![snap6502](https://user-images.githubusercontent.com/29383891/77339730-237f0a80-6d24-11ea-8ab5-81dfb42f1e0f.png)

this is what i see AFTER i removed the Arrastra the dead center holes i could not fill in and then another shot showing that they **will** fill in if Arrastra is NOT there

**Comment by Conchipedia** [comment]
not sure why the Arrastra will Place on the floor if removing the floor detects a central underneath block that prevents placing a block

**Comment by Sekor2600** [comment]
fixed in SVN
