### ISSUE TITLE
[9.0 Staging-1477] Noone can connect to server after restart

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15280]
nobody is able to reconnect after the regular server restart, the _first_ server restart since the update earlier today.

![20200323213506_1](https://user-images.githubusercontent.com/1329717/77382435-6bb32280-6d4e-11ea-8d9e-d47a3d744862.jpg)

[connection failed.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4372849/connection.failed.txt)

**Comment by SlayksWood** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.CivicAction_AddElement.Description()
   at Eco.Gameplay.Civics.Election.Description()</size>
```
[crash_playtest1477.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4373482/crash_playtest1477.txt)

**Comment by mirasrael** [comment]
Fixed in code and also fixed save on publictest.
