### ISSUE TITLE
[0.9.0 staging-1477] Add "reset button" for objects with persistent data.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15283]
So we should have some problem (for example with store #15282, #15274) when you add to another player you object with persistent data. And we should have button which will reset this objects to default.
This will be like a fallback. If something broke during the migration or just broke, then the Player can always reset it and start over. Instead of throwing out object and crafting a new one.

**Comment by MishkaFur** [comment]
A reset option would be very handy or just a timeout of the item not being placed causes it to reset ie its in an inventory for 30min and its data gets reset
