### ISSUE TITLE
Fish will freeze in mid-air if no space in inventory

### ISSUE THREAD

**Issue by gjsmo** [StrangeLoopGames/EcoIssues#15281]
Version 0.8.3.3 beta, Windows 10.

Steps to reproduce:

1. Fill up inventory.
2. Try to catch a fish.
3. At the point fish would've been "caught" it will freeze in midair.

**Comment by gjsmo** [comment]
[Screenshot](https://imgur.com/9708raB)

**Comment by beastyn** [comment]
Check after fixing this #14410, so merge.

Don't see anything likw that in 9.0, just error message

There is no some normal fish model on the hook right now.
