### ISSUE TITLE
[9.0 Staging-1480] Voting Web UI is broken in  Firefox/IE/Edge

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15284]
The voting Web UI, while people can still vote does not show any sort of good information except for the following screenshot above the actual vote button.

![Web UI issue](https://user-images.githubusercontent.com/1329717/77417667-ae4b1e00-6d93-11ea-93f3-dcf26dc1b784.png)

**Comment by Daelmaron** [comment]
![Web UI issue](https://user-images.githubusercontent.com/1329717/77417883-113cb500-6d94-11ea-8355-e181029871b7.png)

**Comment by Daelmaron** [comment]
![Web UI issue](https://user-images.githubusercontent.com/1329717/77417954-2d405680-6d94-11ea-8d8a-6557da72f10c.png)

**Comment by henrikolsson** [comment]
It works in Chrome, but not in Firefox/IE it seems.

**Comment by Daelmaron** [comment]
![Web UI issue](https://user-images.githubusercontent.com/1329717/77418054-5a8d0480-6d94-11ea-8d40-fd24c71a6cd4.png)

**Comment by Daelmaron** [comment]
Can confirm, loads properly on Chrome for me.

![Web UI issue](https://user-images.githubusercontent.com/1329717/77418288-b061ac80-6d94-11ea-9479-e4f23e5b0e11.png)

**Comment by denysaw** [comment]
Hm... Can't reproduce. Maybe it's some part-case of Election. Please, provide me with Game data (saves) of problematic election, which doesn't work on FF/Edge (IE we don't support a priori).

For me, usual election, FF:
![image](https://user-images.githubusercontent.com/5720101/79397221-e3572480-7f7d-11ea-900e-15db22ce57f6.png)

Edge:
![image](https://user-images.githubusercontent.com/5720101/79397254-f0741380-7f7d-11ea-8711-54158f0286ec.png)

**Comment by denysaw** [comment]
@beastyn @SlayksWood

**Comment by MishkaFur** [comment]
@denysaw this was on the Royal Otter world which had Wolf city which I now host.

@Sarah-Graesyn can you test this again and let me know if I need to zip up a copy of the world file please.

**Comment by Sarah-Graesyn** [comment]
yeh, will test in the morning

**Comment by WeaselDog** [comment]
Hi @Sarah-Graesyn.

Were you able to get a save for this? We are not able to reproduce this on our end but would like to look into it more if it is a problem.

**Comment by beastyn** [comment]
Should be fine after redesign
