### ISSUE TITLE
[9.0 Staging - 1480] Weird FPS Drops when driving Steam Truck

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15286]
**1. Version:** 9.0 Staging 1477
**2. Steps to reproduce:** Driving a steam truck around
**3. Expected behavior:** Reasonably smooth drive from point A to point B
**4. Actual behavior:** Mostly smooth, however at points (I want to say I was passing areas that had alot of fireplaces/campfires but I'm not sure at this point) my Frame Rate dropped from a consistent and stable 80 FPS down to 2 and then stuttered for a moment before climbing to 15, back down to 2 and then stabilizing around 30 before fully stabilizing back to my default 80 FPS
**5. Providing Log files:**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4375064/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4375067/Player-prev.log)

**_NOTE_**: I am not sure if the logs will be helpful here but provided them anyway.

**Comment by Daelmaron** [comment]
Adding some screenshots of what is right at one of the points that this happened at. 

![20200324070319_1](https://user-images.githubusercontent.com/1329717/77423693-caec5380-6d9d-11ea-9cce-b1c668872cdf.jpg)
![20200324070330_1](https://user-images.githubusercontent.com/1329717/77423694-cb84ea00-6d9d-11ea-965c-fa2f01c578e0.jpg)
![20200324070202_1](https://user-images.githubusercontent.com/1329717/77423697-ccb61700-6d9d-11ea-9429-2264d2fa874a.jpg)
![20200324070250_1](https://user-images.githubusercontent.com/1329717/77423699-cd4ead80-6d9d-11ea-8116-6a4a15ce28cd.jpg)
![20200324070301_1](https://user-images.githubusercontent.com/1329717/77423702-cde74400-6d9d-11ea-82f4-73f1e11239ae.jpg)

**Comment by Daelmaron** [comment]
On a further note, it has something to do with the client visually loading chunks ahead as well. This may be somewhat unavoidable but if for whatever reason there are only partially loaded or even fully unloaded chunks within view distance (currently set to like 100) the FPS tanks while driving the steam truck.

**Comment by mirasrael** [comment]
Suppose this related to FuelSupplyComponent issue I fixed in linked PR.
