### ISSUE TITLE
[0.9.0 Staging-1480] Hewn Log Pattern

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15295]
**Steps to reproduce:** Attempt to craft Hewn Log on two different tables.
**Expected behavior:** Hewn Log recipe being able to be done at a baseline regardless of table
**Actual behavior:** Recipe is different: On a straight workbench the Hewn Log recipe takes 2 items with WoodTag and creates 1 Hewn Log with no skill requirement. If you try to do the same pattern on a carpentry table the same recipe _Hewn Log_ takes 2 items with WoodTag and creates 1 Hewn Log however it requires Logging 1 on the Carpentry Table
**Providing Log files:** 

![20200324123309_1](https://user-images.githubusercontent.com/1329717/77458519-4f55cb00-6dcc-11ea-818b-405c8c59eaf5.jpg)
![20200324123013_1](https://user-images.githubusercontent.com/1329717/77458521-4fee6180-6dcc-11ea-9917-6ca1babbf9d5.jpg)
![20200324123210_1](https://user-images.githubusercontent.com/1329717/77458523-4fee6180-6dcc-11ea-87c3-ae9da246e145.jpg)

**Comment by Sekor2600** [comment]
Yeah because the Recipe in CarpentryTable is for Profession Logging where you have later the Module Bonus

**Comment by elfl0rd** [comment]
Yes, it's intended behavior.
