### ISSUE TITLE
Unknown Crash at Random Intervals

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#15296]
Version: 9.0 (I think - I'm on Royal Otter at 3/24/2020)
Steps to Reproduce: Unknown - Presumably Play the game - Recommend Digging in the provided logs to find out more - as devs you will understand them better than me
Expected Behavior: No Crashing, atleast not until I close the game myself.
Actual Behavior: Crash Every So Often (No Exact Time-frame/Known Cause)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377202/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4377203/Player.log)

Also I'm not sure if this file is neccessary for debugging but I'm including it as a precaution:

(A Full Zip of my %appdata%\..\LocalLow\StrangeLoopGames\Eco Folder since Git won't let us upload .eco)
[Eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4377212/Eco.zip)

**Comment by MystLeissa** [comment]
Update: I believe these crashes are somehow linked to extremely laggy enviroments, they tended to get worse around my home where a large amount of trees were felled simulationously; This resulted in extreme lag for me and other players in the vicinity but it seems that it only effected those with certain hardware worse (note: My PC is middle-of-the-road in specs and is neither a potato nor a state of the art nanomachine)

**Comment by Conchipedia** [comment]
had a couple of crashes as well
player.log and player-prev.log in this ZIP
[player log and Prev log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4378533/player.log.and.Prev.log.zip)
+ 2 Crash Logs
[Crash_2020-03-25_003953935.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4378536/Crash_2020-03-25_003953935.zip)
[Crash_2020-03-25_012400168.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4378537/Crash_2020-03-25_012400168.zip)

**Comment by SlayksWood** [comment]
dup #15272
