### ISSUE TITLE
USER ISSUE: Cannot connect to own (hosted) world

### ISSUE THREAD

**Issue by Quantum2707** [StrangeLoopGames/EcoIssues#15294]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Just start eco and press Continue or Load -> Click world name
Wait for "Connecting"-Phrase and see the "failed to connect" error

**Expected behavior:**
Should be no problem connecting to my localhost world

**Actual behavior:**
 Kicked me out due to connection establishment problems (port 3000 was not blocked, i checked)

**Do you have mods installed? Does issue happen when no mods are installed?:**
I have no mods installed

**Comment by SlayksWood** [comment]
Thank you for report.
1. Can you try to connect to official servers and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the "latest build" or you had it before?
7. Do you have external IP address and did you use it in config file?

**Comment by redwyre** [comment]
Is anyone else able to connect? Does it look like it's working correctly in the hosted world dashboard?

**Comment by Quantum2707** [comment]
Hey there,

this problem disappeared as I restarted Eco and created a new world, all worlds except of one are working, the one world that is not was created a long time ago, I guess longer than 7 months ago.

I could see everything as usual, nothing was different from then on.
I am using Windows NT10, I have an extended Firewall setup but it would notify about everything trying to use or block a port.

Cheers.

**Comment by mirasrael** [comment]
Hi @Quantum2707 
When you starting local world and can't connect it usually means the server not able to start. You can check this by running the server as standalone process or by checking logs in %GAME_DIRECTORY%/AppData/Server/Logs
