### ISSUE TITLE
[0.9.0 Staging-1480] Client stops responding after hitting the quit button in game.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15291]
**Steps to reproduce:** Click the quit button when connected to a server
**Expected behavior:** Game quits out without issue after a moment
**Actual behavior:** Client locked up and then my computer froze for about 5 minutes before I could get anything at all to respond
**Providing Log files:**
![lockup bmp](https://user-images.githubusercontent.com/1329717/77432776-8320f880-6dac-11ea-9fed-b4f7678f92b3.png)

**Comment by revtje** [comment]
Got the same issue. Also Player.log and Player-prev.log have become huge so I had to zip them
[Player_logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4375769/Player_logs.zip)

**Comment by BennoHase** [comment]
Version: 0.9.0 Staging-1515 still there

**Comment by mirasrael** [comment]
Can't reproduce on latest version. Seems fixed.
