### ISSUE TITLE
[0.9.0 Staging - 1480] Vehicle bugged after crash.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15293]
**Version:** 9.0
**Steps to reproduce:** Unknown. I crashed and then restarted my game see ticket #15272 
**Expected behavior:** Expected to be able to drive my vehicle
**Actual behavior:** When pressing E to drive it opens the inventory no matter what angle I approach the vehicle from or how I interact it, even when the drive hint is displayed
**Providing Log files:**

![20200324094239_1](https://user-images.githubusercontent.com/1329717/77438882-5c66c000-6db4-11ea-9cf3-2fd6c9a80633.jpg)

**Comment by SlayksWood** [comment]
@Daelmaron 
1. reload
2. pickup vehicle
3. use /freecar
Something helped?

**Comment by Daelmaron** [comment]
@SlayksWood yes, picking it up and placing it back down fixed it, though relogging from the server and logging back in did not. I did not attempt freecar as I didn't think of it, but it automatically going to menu when drive hint is displayed seems like a bug

**Comment by mirasrael** [comment]
Thanks, I missed the issue to assign to my fix :-D
