### ISSUE TITLE
need in localization some controls?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15290]
or all should be localization or not.
![image](https://user-images.githubusercontent.com/45708377/77428712-9a320b80-6de9-11ea-9e5f-3c623217d6c9.png)
Also need to check mouse wheel in one case it localizates in another not:
![image](https://user-images.githubusercontent.com/45708377/77428850-cea5c780-6de9-11ea-8261-d3b579d821f7.png)

**Comment by elfl0rd** [comment]
exists
Tab - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#166382
Mouse Wheel - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#171483
Ctrl - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#171506
Shift - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#145776

But yes, NumLock string is missed.

**Comment by Quadbro** [comment]
controll keys localizing is bad idea in general

**Comment by Quadbro** [comment]
@johnkslg Do we really need key names to be localized? I thing name "Shift" for keybind is an international standart, and it should be "shift" in any language, What do you think?

**Comment by elfl0rd** [comment]
![1490272035283492746](https://user-images.githubusercontent.com/4980243/82548602-3d8e6b00-9b64-11ea-8c80-cdddd9293e4a.jpg)

Also what about "space" (ru - пробел) "alt" (ru альт) it is more used as translated.

I think this translation should be available, and translators can select appropriate way.
