### ISSUE TITLE
Customer Support Issue Help Request, Login issues 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1529]
**Customer:**
I can’t seem to find the server I’ve been playing on for the last few days, is there any reason this could be happening?

**CS:** 
Howdy Customer! 

Maybe the server host has stopped hosting the server. All Eco servers are hosted by players right now.

-Florian

**Customer:**
Hi,

I'm stuck on "loading object 100%" it did it once before but I managed to get in after restarting my router.

I can't get in at all this time, but I can get in to more local servers (I'm Australian and the server Eco Terrarium is american based.

Any way I can fix this? Admin has tried a few things already.

**CS:**

Howdy Customer! 

Are you the only one that has issues login into the server? if so could you try the following : 

While stuck at 100% object loading could you hit your esc button and change the view range or some other settings? 

-Florian 

**Customer:**
I'm the only one that can't login. I've tried that, still nothing. I get in sometimes but not other times.

**Any idea why he might get this issue?**

**Comment by metachronism** [comment]
pretty sure the underlying issue here has been fixed for 5.6 (deadlock)
