### ISSUE TITLE
[0.9.0 Staging-1480] Steam Engine not connecting to pipes despite having an input.

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15307]
**Steps to reproduce:** Place a steam engine and pipes
**Expected behavior:** Expected the steam engine to require and connect to a water pipe, you know... since its a **STEAM** Engine
**Actual behavior:** Engine does not connect to pipe and the UI for the engine does not even show that it requires one, though it visually has a input location for water
**Providing Log files**
![20200324200646_1](https://user-images.githubusercontent.com/1329717/77491367-8e574100-6e0b-11ea-93d8-280c8cf73ab6.jpg)
![20200324200651_1](https://user-images.githubusercontent.com/1329717/77491368-8f886e00-6e0b-11ea-82ac-68f788a64978.jpg)
![20200324200723_1](https://user-images.githubusercontent.com/1329717/77491371-90210480-6e0b-11ea-9a31-9de019d1f016.jpg)
![20200324200725_1](https://user-images.githubusercontent.com/1329717/77491372-91523180-6e0b-11ea-94df-e26f40564b21.jpg)

**Comment by SlayksWood** [comment]
dup #11385
