### ISSUE TITLE
Refactor room requirements / remove chimney requirements

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1530]
- refactor room requirements as a pre-set list of conditions that must be met
- list all of these requirements out on the status page of the object, with green checkmarks for those satisfied, and X's for those not
- this may also be a good time to refactor the status page into a generalized list of requirements

**Comment by craig-jong** [comment]
chimney requirements don't exist anymore/aren't used.

All the bad stuff is place into the tanks/pipes now which handles the world object being enabled.

**Comment by MarjieAVolk** [comment]
Since when did chimney requirements get removed?  Wait so that's how you fixed chimneys so fast? :P

**Comment by MarjieAVolk** [comment]
No one has claimed this yet, so I'm going to claim it :)

**Comment by MarjieAVolk** [comment]
Guess this is done now
