### ISSUE TITLE
[0.9.0.0 beta staging-1480] Strange Effect with FillType on WorldBorder 

### ISSUE THREAD

**Issue by ScottEco** [StrangeLoopGames/EcoIssues#15309]
Version: 0.9.0.0 beta staging-1480

Steps to Reproduce:
Using the hammer at the border of a map with the "line" tool

Expected behavior:
On playtest server (1000x1000) when trying to build a line between 990 to 005 on the map, line tool should propose a line with 15 blocks

Actual behavior:
The hammer shows a line going through the entire world for 985 blocks

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods. playing on playtest

**Comment by SlayksWood** [comment]
> Use the Fillform on the Worldborder and it changes Direction (completely around the world) and you can see unter Water
> 
> https://drive.google.com/open?id=1GoochUouDBCEx5H5A-XiFDwTHELvawFW
