### ISSUE TITLE
USER ISSUE: Getting stuck in a wall

### ISSUE THREAD

**Issue by LWChris** [StrangeLoopGames/EcoIssues#15301]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Put a door in a wall, next to a perpendicular wall, such that the door will open towards that wall.
2. Walk to the door from the side the door will open to.
3. Stand next to the door in the corner (next to the door hinges), so the opening door will "squash" you between itself and the wall next to you.
4. Activate/Open the door.

**Expected behavior:**
The opening door should push you away, but as you hit the wall, push you backwards or "port" you to the other side of the door into the door frame.

**Actual behavior:**
The door pushes you into the perpendicular wall, leaving you stuck inside it. 100% reproduction rate using a Wooden Door and Mortared Limestone walls. The only possible way out is to demolish a part of the wall, which will port you on top of the building.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by SlayksWood** [comment]
@LWChris 
Stucking/Unstucking system was improvment in 0.9.0. Seems I can't stuck this way in 0.9.0.
Do I reproduce it right?
![image](https://user-images.githubusercontent.com/45708377/77515265-44ad3b80-6e89-11ea-9769-a4eff3fdb2ee.png)
![2020 03 25 Getting stuck in a wall](https://user-images.githubusercontent.com/45708377/77515372-79b98e00-6e89-11ea-9be5-b848219a744e.gif)

**Comment by LWChris** [comment]
My wall setup is slightly different, because the wall to the left is also a thin wall:

![grafik](https://user-images.githubusercontent.com/845152/77795480-dbd2e880-706d-11ea-8e99-03b267be6542.png)

The position from which I get stuck is this:

![grafik](https://user-images.githubusercontent.com/845152/77795524-f4430300-706d-11ea-92cb-64f07e177e14.png)

I have a whole series of screenshots if that helps.

**Comment by beastyn** [comment]
Was experiment with the similar setup. With some doors you can stuck between door and wall, you just need to close a door and open a door appropriate.
Close for now, will reopen if meet it in some vreaking way.

**Comment by LWChris** [comment]
> you just need to close a door and open a door appropriate

Are you actually telling me "To not run into the bug, do not run into the bug."?!
