### ISSUE TITLE
Adjust room volume needs for govt objects?

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15300]
![image](https://user-images.githubusercontent.com/3536496/77472032-8a59fd80-6dd0-11ea-9649-201349a5b318.png)
Theres a crazy amount of stuff jam packed in a single room here

**Comment by MishkaFur** [comment]
Government ones seem to be fine, the issue is you can pack a room full of furniture to increase the skill value, tables, chairs etc all need to have a M3 requirement ie a table being 6m3 (1 wide, 2 long and 2 high) but with space around it, chair 2m3 due to space around it etc

**Comment by johnkslg** [comment]
Balance changes are low-risk and this is a new feature, keeping

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/80001893-36b9fd00-84bf-11ea-9525-e2014b8093bb.png)
