### ISSUE TITLE
USER ISSUE: cannot connect to playtest server

### ISSUE THREAD

**Issue by ScottEco** [StrangeLoopGames/EcoIssues#15308]
**Version:** 0.9.0.0 beta staging-1480

**Steps to Reproduce:**
Trying to connect to Royal Otter playtest server

**Expected behavior:**
Should have started loading world

**Actual behavior:**
connection failed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. playing on playtest

**Comment by SlayksWood** [comment]
seems related with #15273

**Comment by johnkslg** [comment]
Should be fixed then
