### ISSUE TITLE
[0.9.0 staging-1483] Minimap started spam in log and hard to close.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15314]
Step to reproduce:
- start new world.
- join to world and open minimap in full size:
```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
```
- The longer the minimap is open, the more it will lag at closing. The game may even crash:
![image](https://user-images.githubusercontent.com/45708377/77537149-a633d100-6eae-11ea-896e-7e9e7e022f4a.png)
provide log file. Minimap was opened a few second:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4380888/Player.log)

**Comment by Sarah-Graesyn** [comment]
![lockup bmp](https://user-images.githubusercontent.com/1329717/78453274-36fc7080-7656-11ea-8a78-0b012ba6736b.png)

**Comment by MishkaFur** [comment]
I found if I leave the "eco is not responding" window open, eco drops its ram usage to almost nothing before coming back alive, as if something reloaded in the background

![image](https://user-images.githubusercontent.com/61889138/78583810-3b2fb600-782f-11ea-91f3-1028cf599640.png)

**Comment by MishkaFur** [comment]
Just repeated the same as previous post, Eco was using 5.5GB ram and had map open for ages, try to close map, leave it on "Eco is not responding" and it comes back alive with 700MB of ram usage which slowly creeps back up to normal kind of levels.

Will try to test later on a fresh load of my client so the log files are not huge
