### ISSUE TITLE
[0.9.0.0 beta -1480] Minimap and map issue

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15313]
Version: 0.9.0.0 beta staging-1480

Steps to Reproduce:
Open map and click on the boxes

Expected behavior:
Not reduce fps by more than 50%,and require a game restart

Actual behavior:
Reduce fps by more then 50% (marked with red color)

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods. playing on playtest

![Untitled](https://user-images.githubusercontent.com/62566059/77536812-a380ae00-6ea5-11ea-807d-a42523e64429.jpg)

The ones circled with yellow slightly reduce fps alltho reopening map and moving around fixes the issue
The one circled with red cause gigantic fps drop from 55 to 20 in my case.It can be fixed by restarting the game(close the entire game)

**Comment by SlayksWood** [comment]
Interesting effect if you turn off Trees:
![2020 03 25 Minimap trees issue](https://user-images.githubusercontent.com/45708377/77538263-7ede0380-6eb0-11ea-8e4a-d4ba9a109820.gif)

**Comment by Engimage** [comment]
Map is really hard to close now on 1480 on test server. It looks like it uses quite a lot of excess resources and has a hard time freeing them.

**Comment by SlayksWood** [comment]
@Engimage I created another issue for hard closing #15314

**Comment by redwyre** [comment]
The trees being left behind will be fixed with https://github.com/StrangeLoopGames/Eco/pull/5837
