### ISSUE TITLE
[0.9.0 staging-1483] Ecopedia: update illustrations

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15311]
After fixed for UIs and Icons we need to make new illustrations with them.

**Comment by WeaselDog** [comment]
All illustrations with UI or Icon fixes are updated. If there are any blank icons remaining it should be created as a separate issue for Art team. If you see any pages that don't have illustrations that you think should, it would be much appreciated if you opened an issue for this.
