### ISSUE TITLE
[9.0 Staging 1480] Large amount of chat commands locked out even when admin

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15315]
Version Staging 1480
Steps to reproduce) Try to spawn a tree for example with /spawn redwood
Expected Behaviour) It should spawn a tree
Actual behaviour 
![image](https://user-images.githubusercontent.com/61889138/77540765-952d9480-6e9b-11ea-94b0-28e676c912a7.png)

Is also quite a few other commands that seem to no longer work due to them being locked down

**Comment by SlayksWood** [comment]
Yes it's intended behavior for now. This commands(QA) designed for testing and can break your world, so this commands are used only devtier.
