### ISSUE TITLE
[0.9.0 staging-1483] Mystical Black Tower on the map

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15312]
![bandicam 2020-03-25 15-10-07-044](https://user-images.githubusercontent.com/27898520/77525719-44259c80-6eab-11ea-9d75-4cf6d970a82c.jpg)
Save is here

https://drive.google.com/file/d/10flqUO2XuxAAYzuiM6WSfeve4O0Plm5R/view?usp=sharing

**Comment by SlayksWood** [comment]
Seems it happened in every new generated map in one position 360,360 (for 0,52km world), but it should in water.
New first world:
![image](https://user-images.githubusercontent.com/45708377/77532960-00309880-6ea7-11ea-8892-aaaa129c51eb.png)
new second random world :
![image](https://user-images.githubusercontent.com/45708377/77535845-610e9f80-6eac-11ea-86ed-73cee5bbe579.png)
new third random world. 360,360 at land:
![image](https://user-images.githubusercontent.com/45708377/77536750-e9da0b00-6ead-11ea-9059-9556e72e7450.png)

**Comment by Engimage** [comment]
There is one on test server at 500,500

**Comment by elfl0rd** [comment]
0.9-1513 still actual

https://youtu.be/1NHbFBaCqxA

**Comment by mirasrael** [comment]
Doesn't have this effect with new minimap.
