### ISSUE TITLE
Economy view doesn't open

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1532]

**Comment by MarjieAVolk** [comment]
Happening on marmot, but not on a fresh local save

**Comment by sr3ka** [comment]
I'm unsure if this is a server issue or client side issue but it normally crashes the game when attempting to open it on the server I play.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of StrangeLoopGames/EcoIssues#1444
