### ISSUE TITLE
0.9 Localization: "Hidden" lost or missed.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15323]
![изображение](https://user-images.githubusercontent.com/4980243/77562689-629e8e80-6ed1-11ea-96fe-9e24a31ea802.png)

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#146582

**Comment by SlayksWood** [comment]
Seems still an issue:
![image](https://user-images.githubusercontent.com/45708377/82653411-d639ef00-9c27-11ea-91a1-cc5a53fdec47.png)

**Comment by Quadbro** [comment]
yeah, found external text replacer, fixed
