### ISSUE TITLE
0.9 ecopedia help pages for "your civic duties" and "Population" missed

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15328]
(just open root page)
![изображение](https://user-images.githubusercontent.com/4980243/77564675-2882bc00-6ed4-11ea-9972-341101532e38.png)

**Comment by WeaselDog** [comment]
To replicate, press "L" to access open Government UI. 

- For "Your Civic Duties" we have a clear page to link to. 
- For "Population" it contains a list of both Demographics & Districts. I learn towards having it link to Demographics. @johnkslg Do you have any thoughts on this?
![PopulationTab](https://user-images.githubusercontent.com/47330823/77585514-d88b0180-6ea1-11ea-80f0-b3a241c0db02.png)
