### ISSUE TITLE
[0.9.0 staging-1485] Missing District when you start draft District Map

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15337]
Step to reproduce:
- ratify constitution, place zoning office and start to draft Distric map:
![image](https://user-images.githubusercontent.com/45708377/77635215-4b0fe600-6f63-11ea-9389-0aee34f3a9e2.png)
- first district should be auto created.

**Comment by beastyn** [comment]
dup #15205
