### ISSUE TITLE
USER ISSUE: Account

### ISSUE THREAD

**Issue by zakibenaissa** [StrangeLoopGames/EcoIssues#15338]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by MishkaFur** [comment]
Eco is currently version 8.3.3 please update.
