### ISSUE TITLE
About icons!

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#15339]
You can't see the numbers because the money icon that comes out when you put your mouse in the store overlaps.

[https://cdn.discordapp.com/attachments/689261529367183575/692699123069222982/20200322224257_1.jpg](url)

the money mark on the right 

Look at the icon on the left.

The language is Korean.

**Comment by elfl0rd** [comment]
![20200322224257_1](https://user-images.githubusercontent.com/4980243/77645732-469ff900-6f74-11ea-8dd6-08d8f8a7ac64.jpg)
