### ISSUE TITLE
[0.9 staging 1480] Screen flickers when going across border to coord 0

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15330]
1. Staging 1480
2. Go across the border from block 1000 to 0 and screen flickers, happens when going across the "border" 
3. Expected behavior. - Not flicker?
4. Actual behavior. - Flickers

Engimage was able to replicate the issue with me

**Comment by Engimage** [comment]
Confirming this minor bug.
When crossing "0" coordinate both X or Y, in any direction, your screen briefly flickers. You can move back and forth through this line to repeat the effect

**Comment by SlayksWood** [comment]
dup #9664
