### ISSUE TITLE
[0.9 staging 1483] can´t move after login 

### ISSUE THREAD

**Issue by FalkosTMB** [StrangeLoopGames/EcoIssues#15332]
stuck in ground
Unstuck don´t work

**Comment by FalkosTMB** [comment]
same like this:
https://github.com/StrangeLoopGames/EcoIssues/issues/14654

**Comment by beastyn** [comment]
@FalkosTMB where did you get this build?
Any additionak info, logs? how did you start a server?

**Comment by FalkosTMB** [comment]
with 1485 the bug is gone
-- close --
