### ISSUE TITLE
Ecopedia, after selecting subcategory, main category description is unavailable

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15343]
e.g. engineer
I select root category, and i see their description.
![изображение](https://user-images.githubusercontent.com/4980243/77649383-d34db580-6f7a-11ea-9add-ebcd5fcbe563.png)

After i select any subcategory, no way to see root category description.
![изображение](https://user-images.githubusercontent.com/4980243/77649437-eb253980-6f7a-11ea-9871-6f2857c26d48.png)

**Comment by SlayksWood** [comment]
Need to delete frame from subpage
![image](https://user-images.githubusercontent.com/45708377/79103404-272b0d80-7d75-11ea-8911-12c5bf5e2212.png)

**Comment by SlayksWood** [comment]
Still an issue now after changes here #16753, point 3.

**Comment by WeaselDog** [comment]
When reviewing, please make sure this new setup seems good to you. I tested on a few resolutions, but I am aware the text is rather long.

**Comment by SlayksWood** [comment]
Can you add link to all professions to professions overview page? Currently professions don't have any link:
![image](https://user-images.githubusercontent.com/45708377/89867596-10c57f00-dbba-11ea-9f6f-723074e12423.png)
Let the rest remains so

**Comment by WeaselDog** [comment]
Going to close this and make a separate issue for 9.1
