### ISSUE TITLE
0.9 localization: ecopedia have a lot missed strings

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15341]
e.g. "concepts", "reference" and "development"
![изображение](https://user-images.githubusercontent.com/4980243/77648450-38081080-6f79-11ea-8148-3e713e92414e.png)

Getting Started
Economic Components
Government Components
Housing Components
Industry Components
![изображение](https://user-images.githubusercontent.com/4980243/77648746-b2d12b80-6f79-11ea-958d-16a48a91282d.png)
Show Only Discovered Items

lot of pages is not presented at crowdin, etc.

**Comment by Quadbro** [comment]
Fixed all string on ecopedia, but on crowdin they will be avaliable later (on stable ecopedia state)
