### ISSUE TITLE
Blocks taking forever to appear after placement

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15349]
We had a prediction system previously that would make them appear instantly, something seems to have broken that.

I recently changed HammerController to be event driven instead of polling driven, I dont think that had an effect (and changed it back to poll driven temporarily to test) but its worth noting.  @Quadbro can you help look into this one?

**Comment by elfl0rd** [comment]
same behavior with pickup and smite blocks.
