### ISSUE TITLE
[0.9 Staging-1485] Password screen UI improvements

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15352]
The password screen could use a few small UI improvements:

![image](https://user-images.githubusercontent.com/964559/77712457-0ef37a00-6f91-11ea-8160-62b1b2513ba6.png)

1) The typing indicator is currently very dark and narrow. It might be nice for it to be a bit bolder and brighter, perhaps matching the text above it?
2) When you actually type in the password, the asterisks that pop up are dark, matching the temp "password" that was shown before. It would be nicer if those asterisks were actually bright to indicate that you have actually put something in, rather than it being the default text.
3) Give an option to see the password - some people might want to see the password as they type it in. It would be nice for that to be an option.

**Comment by SlayksWood** [comment]
From #15351
> 4. Give an option to save server password locally.
> Currently playing on the 0.9 test server that requires a password. It would be nice if there was an option to store the server password locally so you wouldn't have to re-type it each time you want to join the server.

**Comment by SlayksWood** [comment]
From #15021
> password prompt when joining server text misaligned
> When typing in the password to join a server the text is misaligned, text prompt is flashing in the correct location
> ![image](https://user-images.githubusercontent.com/61889138/76124407-7fdaee00-5ff2-11ea-8148-cf0c4331a36c.png)

**Comment by ThePiachu** [comment]
Another UX improvement - when a password screen pops up, it would be nice if it auto-focued and let you type in straight away. It removes that extra mouse click you have to do.

From UI side of things, the screen could also use some buttons for accepting / cancelling - even if you can do that with keyboard buttons, it might be more intuitive for some people to use clear buttons.

**Comment by SlayksWood** [comment]
> This is annoying issue for all non-english players.
> You cannot see windows lng panel in fulscreen application, and you cannot see text you enter.
> 
> p.s.
> Password visibility selector can be nice addition and temporary solution.
> ![1490793853-user-interface15_82360](https://user-images.githubusercontent.com/4980243/78918704-79c8a900-7a99-11ea-9bc1-625b166a0cdd.png)
> ![1490793864-user-interface16_82335](https://user-images.githubusercontent.com/4980243/78918701-79c8a900-7a99-11ea-80c6-1020eaa6f4a8.png)

**Comment by SlayksWood** [comment]
> **Version:** 0.8.3.3 beta
> 
> **Steps to Reproduce:**
> Try to login to a password protected server
> 
> **Expected behavior:**
> a flashing bar, or something indicating the password text box is active
> 
> **Actual behavior:**
> it's not active, and shows no visual difference after clicking on it, resulting in having to retype password
> 
> **Do you have mods installed? Does issue happen when no mods are installed?:**
> no custom mods

**Comment by SlayksWood** [comment]
> When trying to connect to a server with a password, you have to click on the input before being able to write it.
> It would be better if the input would be auto focus.

**Comment by SlayksWood** [comment]
Possibility to save password, maybe for not a long time #17991

**Comment by IcedForge** [comment]
It is not updating the password on changes & changing bool checkbox status as well as not saving its state.

When "Remember me" checkbox is set to true, it should save this so when you start the game again it stays checked.
And when unchecking it should NOT remember password anymore  ( there is no way to do this now ) also
it does not update the password when changing.

Create server, set password "pewpew123,.-" connect client and save password
log out from server, change server password to "pewpew123,.-123" and connect with client and save password
when leaving server and trying to connect again it will not update new password and autofill old saved password.

**Comment by SlayksWood** [comment]
make this text non-bold and maybe in 1 string (possibly expandable window so that the localization also contains)
![image](https://user-images.githubusercontent.com/45708377/94259308-eeec4580-ff36-11ea-8785-c326156f8b18.png)

**Comment by SlayksWood** [comment]
- [ ] I need to have possibility to use Submit button by enter. Just write you password and press Enter and you should join to server

- [ ] Closing by ESC. Now I press ESC and it just make password field inactive. I need to select field and press ESC second time to close it.

- [ ] Password frame is a little broken now:
![image](https://user-images.githubusercontent.com/45708377/94661850-43fdd200-0310-11eb-8e36-af43c237e586.png)

@MrAnonymous110 Does it save one passworld for all servers or it save all passwords for each server?

**Comment by MinhNHGearInc** [comment]
> @MrAnonymous110 Does it save one password for all servers or it saves all passwords for each server?
Hi, it saves one per each server, if you do not save anymore, we clear the current server password.

**Comment by MrAnonymous110** [comment]
> * [ ]  I need to have possibility to use Submit button by enter. Just write you password and press Enter and you should join to server
> * [ ]  Closing by ESC. Now I press ESC and it just make password field inactive. I need to select field and press ESC second time to close it.
> * [ ]  Password frame is a little broken now:
>   ![image](https://user-images.githubusercontent.com/45708377/94661850-43fdd200-0310-11eb-8e36-af43c237e586.png)
> 
> @MrAnonymous110 Does it save one passworld for all servers or it save all passwords for each server?

Hi, I fixed the 2 first issue, the last one I don't see it happen, this is my screen, could you check it again
![image](https://user-images.githubusercontent.com/3883524/94938069-94d11e80-04fa-11eb-9ae7-e5a227e13b9c.png)

**Comment by MrAnonymous110** [comment]
Based on QA's feedbacks and comments in PR. I used the generic popup system for password UI and tweak it to keep the desire function work. Could you check it again, thanks!.

**Comment by SlayksWood** [comment]
It got much better. But there are a couple of glitches, but I will create separate issues.
