### ISSUE TITLE
[0.9 Staging-1485] Show item tags

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15357]
The tag system in 0.9 is very useful. However, it would be nice to see item tags at a glance when looking at something:

![image](https://user-images.githubusercontent.com/964559/77713991-2d5b7480-6f95-11ea-9394-a7584dcf8dd2.png)

While some things are obvious like what is wood, etc., others can be a bit more complicated - you might think Wood Pulp is Natural Fiber, but nope! Seeing item tags would clear this confusion up.

**Comment by gzatravkin** [comment]
@ThePiachu Thanks for your feedabck. It was implementing, and this is how it will looks like after merge of https://github.com/StrangeLoopGames/Eco/pull/6158 .

![image](https://user-images.githubusercontent.com/53317567/83233175-b42ef800-a164-11ea-9c4c-6f42445a15dc.png)
