### ISSUE TITLE
Informational Pop-ups "Stuck"

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#15356]
Version: 9.0 Play test

Actual Result:
 the Informational Popups have an infinite disappear delay and persist through relogs.
Expected Result: 
 Able to Manually Close the popups and/or Automatically fade after a few seconds.
Steps to Reproduce: 
 Unable to Test as the system has become permanently mangled
Additional Information Logs:
 
![20200326220303_1](https://user-images.githubusercontent.com/28554657/77713875-f34a9c80-6fad-11ea-880a-5ea42fc515f0.jpg)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4391030/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4391031/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4391032/Player.log)

**Comment by MystLeissa** [comment]
I should note this is just conjecture but in an attempt to track down a method to reproduce I will note the work party that originally created these popups occured in a particularly severe lag spike with multiple clicks on the workbench in quick succession.

**Comment by MystLeissa** [comment]
Also would like to mention storing the popups for redisplay on relog is probably not the wisest course of action, as any other title this method would allow you to "force" clear popups.

**Comment by gzatravkin** [comment]
CNR. 
Tried by gettings error message at moment of disconected via 
Civis spawngov

Escape menu
Chat 

Got error of chat blocked
Disconect
Connect

Maybe it was already fixed

**Comment by beastyn** [comment]
Looks like fixed
