### ISSUE TITLE
Information Inconsistancy/Minor Bug: Work Parties Invalid because of "Lack" of reputation

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#15350]
Nature of Issue/Actual Result: On the contract Page of the Work Parties if the issuer has insufficent reputation to fullfill their work party the contract is confusingly reported as "Invalid because <owner name> doesn't have enough currency in <bank account> to complete the transaction" even though if you actually DO the work all it is missing is the Reputation for the daily limit.
Version: 9.0 Beta
Expected Result/Suggested Remedy: Tell the player WHICH currency/reputation is missing from an account to complete the contract/work party OR store all that in "Contract Escrow" when Issuing the Party like advertised. 

Log Files: Unfortunately I don't possess the server that this occured on however it was an Official Server so the logs for activity should be stored on Royal Otter at/around 3/26/2020 9:20 - 9:25 PM EST. If I had the work party still I'd attach a screenshot however this particular party was already completed.

Note to Sarah: Feel free to contribute your side of the story to this issue - I have included only what information I have personally been able to gain and this is a multiplayer player interaction oriented issue.

**Comment by MystLeissa** [comment]
I should also mention that work parties listed as invalid in this manner still payout the currencies that are still "stocked" but not the ones that are insufficent.

**Comment by Daelmaron** [comment]
Additionally on this matter when you create a work party/contract it withdraws money from your account and deposits it into an Escrow account yet when the work is done it shows as the money coming out of the originator account that has **_already_** paid for the contract reward price.

![20200326200824_1](https://user-images.githubusercontent.com/1329717/77716045-38b99a80-6fab-11ea-8e85-bb7b771d141a.jpg)
![20200326200832_1](https://user-images.githubusercontent.com/1329717/77716046-39523100-6fab-11ea-8a20-edf71eea20b3.jpg)
![20200326201238_1](https://user-images.githubusercontent.com/1329717/77716048-39523100-6fab-11ea-85cc-35b3dbc8805e.jpg)

**Comment by SlayksWood** [comment]
@MystLeissa @Daelmaron 
Can you describe it more detail how to reproduce your problem step by step.
Which orders to place, how much currency should be, payment and other details. If you attach more screenshots, then it will be cool.

**Comment by Daelmaron** [comment]
@SlayksWood I will set a new one up tonight and see if I can get it to go through the full process and I'll take screenshots as I work.

**Comment by SlayksWood** [comment]
Can't reproduce it in last staging. Please reopen if it happens again
