### ISSUE TITLE
[0.9 Staging-1485] Add an option to disable other players' notifications

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15358]
Related to StrangeLoopGames/EcoIssues#3067

The notifications can be useful, but at times you might just not care about what other players are doing:

![image](https://user-images.githubusercontent.com/964559/77714938-84fadf80-6f97-11ea-8508-efba557926b8.png)

It would be nice to have an option to disable other players' notifications, or limit them to say, your local neighbourhood or something.

**Comment by johnkslg** [comment]
An easy solution will be to tag these global craft notifications as temporary, so they go away faster.
I want to keep them visible so people can see activity in the server as a feed going through.

**Comment by johnkslg** [comment]
Rethinking how we should approach this:
- We make other-player notifications temporary so they disappear rapidly
- We make all chat go to the screen
I dont want to disable them because I want the feeling of liveliness to be active all the time.  Better to just configure the notifications so they arent bothersome.

**Comment by gzatravkin** [comment]
> Rethinking how we should approach this:
> 
> * We make other-player notifications temporary so they disappear rapidly
> * We make all chat go to the screen
>   I dont want to disable them because I want the feeling of liveliness to be active all the time.  Better to just configure the notifications so they arent bothersome.

Top panel now don't have temporary messages at all and don't support it (and issue is about top panel). 
If so, these "not related to player notifications" could go to middle screen instead of top panel for quick disappearing, is this is what you mean?

**Comment by Mattprass** [comment]
What is the status of this ticket? Does it no longer need a task plan if we're just making all other player notifications temporary?

**Comment by johnkslg** [comment]
Closing this in favor of the chat rework
