### ISSUE TITLE
[0.9 Staging-1485] The bloom can be a bit intensive at times

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15354]
I started a 0.9 game and I think my graphics setting from a previous version carried over, or maybe the bloom was really just this bright:

![image](https://user-images.githubusercontent.com/964559/77712892-4878b500-6f92-11ea-9150-b8e2e36430b5.png)

It would be nice to tone it down a bit by default perhaps. I guess some players might want to boost the brightness at night for easier gaming while not burning their eyes during the day.

**Comment by SlayksWood** [comment]
@ThePiachu provide please your graphics settings.

**Comment by ThePiachu** [comment]
I think it was Brightness in the 200-250 range, bloom on, looking towards the Sun, etc. Unfortunately, I have reset the settings since...

**Comment by SlayksWood** [comment]
@keegan-o Can you take a look? is it intented with such brightness?

**Comment by redwyre** [comment]
If you set brightness to 200% things are going to be really bright...

**Comment by redwyre** [comment]
That said, adaptive exposure will help with the darker parts if it makes it into 9.0

**Comment by keegan-o** [comment]
With the big changes in 9.0 we've made, it should no longer ne neccesary for people to be turning up brightness like this. I did tone down bloom a little bit, as well.
