### ISSUE TITLE
/objects remove tooltip conditions is lacking

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15365]
No matter what i type it asks me to specifiy a type, even if i did via

/objects remove districtmaps XYZ
/objects remove district maps XYZ
/objects remove districtmap XYZ
/objects remove district map XYZ
/objects remove DistrictMaps XYZ

None of the other types works for me either.

**Comment by D3nnis3n** [comment]
/objects removeall district maps works, but removes all of them.

**Comment by johnkslg** [comment]
Make the selection of the type a little more flexible, and give examples when failures happen. Make the base help give a nice guide.

**Comment by johnkslg** [comment]
actually, you can use the new selector popups I made as an alternative to naming them, if the name is left off it can pop that up

**Comment by SlayksWood** [comment]
The command is working now, but it must be written correctly. The tooltip is still bad.
@D3nnis3n Can you check it?

**Comment by IcedForge** [comment]
./objects gives you full tooltip
but if you use a combination that does not result in action taken it does not tell you anything this should give you a correction or at least the same default tooltip.

**Comment by D3nnis3n** [comment]
Yeh, we need info for edit and remove as well.

**Comment by SlayksWood** [comment]
We have the one example for different commands:
![image](https://user-images.githubusercontent.com/45708377/104287567-b1043480-54c7-11eb-8679-542b19ccd501.png)
And clear will not be used like in this example. It will be used like /objects clear Law.
