### ISSUE TITLE
[0.9.0 staging-1488] Missing hints for Many actions

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15360]
Land claim stake: LMB Claim/RMB unclaim + modificators.
![image](https://user-images.githubusercontent.com/45708377/77733424-e9f61a00-7017-11ea-8824-e5e9994ef63b.png)

**Comment by SlayksWood** [comment]
Placing rubles:
![image](https://user-images.githubusercontent.com/45708377/78018213-2bf3c880-7356-11ea-83d7-5e8e8929eb00.png)

**Comment by SlayksWood** [comment]
From #15446
> ![image](https://user-images.githubusercontent.com/3536496/77976435-d1a12c00-72b1-11ea-8843-f6d5312a9133.png)
> Should have a right click for placing, and q/r to rotate.

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/15051
