### ISSUE TITLE
[0.9 Staging-1485] Describe Economy viewer in ECOpedia

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15363]
I wanted to buy a particular item on the server. Normally, when you have the workbenches needed to craft the item, you can hover over the item and see where it is being sold and bought. However, I was too low level to be able to get the workbench that produced that item. I tried searching it on Ecopedia in hopes that it would display where the items are being sold, but no luck. So unless I could get my hands on the item, I wouldn't know where it could be bought or sold, which is a shame.

It would be nice if there was a way for players to search for what items are being bought and sold on a more global level. Be able to find any item in the game and see its availability and demand, as well as being able to view a list of stores and their wares remotely. This would make the economy work a lot more smoothly!

**Comment by SlayksWood** [comment]
@ThePiachu 
Economy viewer?
![image](https://user-images.githubusercontent.com/45708377/77749138-90e7af80-7032-11ea-934f-07b40cd27339.png)

**Comment by Daelmaron** [comment]
@ThePiachu you can also type the item you are looking for into chat and hover over its name there, should pull a list of stores selling/buying it that way as well.

**Comment by elfl0rd** [comment]
Also you can use * (gear) icon next than "Item" text to filter.

**Comment by ThePiachu** [comment]
@SlayksWood Gah, yes. I guess it should be more prominent in the Ecopedia, since currently the Economy Viewer doesn't seem to be mentioned in the Economy page:

![image](https://user-images.githubusercontent.com/964559/77799687-89c0a180-7032-11ea-8392-c7de1c9a7942.png)
