### ISSUE TITLE
0.9 at modules tab, "modules tag" no more have tooltip.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15368]
(no hover hint)
![изображение](https://user-images.githubusercontent.com/4980243/77751357-98a95300-7036-11ea-9159-c085c37500af.png)

**Comment by WeaselDog** [comment]
Look to be an issue in the UI. The tags are setup correctly in tech tree and you can get a hover hint in the "Reference" section of Ecopedia

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5839
