### ISSUE TITLE
0.9 localization: "COMMUNICATIONS BY" missed

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15366]
![изображение](https://user-images.githubusercontent.com/4980243/77749828-c214af80-7033-11ea-89bb-e1aedf19ccd1.png)

**Comment by SlayksWood** [comment]
This is a picture
https://www.vivox.com/assets/image/vivox-w-icons.png

**Comment by elfl0rd** [comment]
This cane be text, like previous changes with discord icon.

**Comment by elfl0rd** [comment]
@D3nnis3n what do you think?

**Comment by redwyre** [comment]
No it can't, it's supplied by Vivox and has to be displayed as is.

**Comment by elfl0rd** [comment]
ok
