### ISSUE TITLE
DB Inserting Issues

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15364]
> [03:30:52.927] [43] [Error] [Eco] Error inserting stat of type LostElection into databaseLiteDB.LiteException: This database exceeded the maximum limit of collection names size: 3000 bytes
>    at LiteDB.CollectionService.Add(String name)
>    at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action)
>    at LiteDB.LiteEngine.Insert(String collection, IEnumerable1 docs, BsonType autoId)
>    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
>    at LiteDB.LiteCollection`1.Insert(T document)
>    at Eco.Stats.Stats.<>cDisplayClass22_2.<Record>b1()
>    at Eco.Stats.PendingWritesDiskService.WithTransaction(Action action, Int32 timeout)
>    at Eco.Stats.Stats.Record(IStat obj)
> 
> [09:13:32.674] [44] [Error] [Eco] Error inserting stat of type PropertyTransfer into databaseLiteDB.LiteException: This database exceeded the maximum limit of collection names size: 3000 bytes
>    at LiteDB.CollectionService.Add(String name)
>    at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action)
>    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
>    at LiteDB.LiteCollection1.Insert(T document)
>    at Eco.Stats.Stats.<>cDisplayClass22_2.<Record>b1()
>    at Eco.Stats.PendingWritesDiskService.WithTransaction(Action action, Int32 timeout)
>    at Eco.Stats.Stats.Record(IStat obj)
>  
> [09:13:59.417] [44] [Error] [Eco] Error inserting stat of type PropertyTransfer into databaseLiteDB.LiteException: This database exceeded the maximum limit of collection names size: 3000 bytes
>    at LiteDB.CollectionService.Add(String name)
>    at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
>    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action)
>    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
>    at LiteDB.LiteCollection1.Insert(T document)
>    at Eco.Stats.Stats.<>cDisplayClass22_2.<Record>b1()
>    at Eco.Stats.PendingWritesDiskService.WithTransaction(Action action, Int32 timeout)
>    at Eco.Stats.Stats.Record(IStat obj)

**Comment by johnkslg** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/5814
Full fix will hopefully be updating LiteDB version
