### ISSUE TITLE
[0.9.0 staging-1485] sound delay or missing

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15373]
Version: 0.9.0.0 beta staging-1485

Steps to Reproduce:
Play

Expected behavior:
Sound not be delayed or missing

Actual behavior:
Sound is delayed or somethimes missing at all

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods. playing on playtest

**Comment by VokrugShum** [comment]
the sound disappeared altogether, only the birds sing on the start page, but when loading into the world there is no music or sounds

**Comment by VokrugShum** [comment]
the sound disappeared altogether, only the birds sing on the start page, but when loading into the world there is no music or sounds
