### ISSUE TITLE
0.9 marker settings out from form

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15375]
![изображение](https://user-images.githubusercontent.com/4980243/77762235-42dea600-704a-11ea-96cd-a05e689073d2.png)

**Comment by beastyn** [comment]
Still not in the box
![bandicam 2020-04-14 12-40-16-041](https://user-images.githubusercontent.com/27898520/79198557-1bab1580-7e4d-11ea-9211-8a9d8df1ee90.jpg)
