### ISSUE TITLE
[0.9.0 staging-1485] Game close itself

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15377]
Version: 0.9.0.0 beta staging-1485

Steps to Reproduce:
Game just quits itself(like a crash but no notification at all),this happends like twice a day or more

Expected behavior:
Game should not quit himself

Actual behavior:
Game just quits itself(like a crash but no notification at all),this happends like twice a day or more

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods. playing on playtest

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4394142/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4394144/Player-prev.log)

**Comment by SlayksWood** [comment]
dup #15272
