### ISSUE TITLE
[0.9.0 staging-1485] game stop responding

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15374]
Version: 0.9.0.0 beta staging-1485

Steps to Reproduce:
Quit the game while play on server or alt+f4

Expected behavior:
Game should not stop responding

Actual behavior:
Games stops responding(rarely has no issue)

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods. playing on playtest

**Comment by SlayksWood** [comment]
dup #15291
