### ISSUE TITLE
USER ISSUE: login failed

### ISSUE THREAD

**Issue by robertwtf** [StrangeLoopGames/EcoIssues#15384]
**Version:** 0.9.0.0 beta staging-1485

**Steps to Reproduce:**
login to server. Write password, wait for world loading. crashes right before map should appear (entering world)

**Expected behavior:**
after "Entering world", I expect the map to start.

**Actual behavior:**
The following error message popped up
'''
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Private.CoreLib

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Civics.CivicAction_ChangeElement.Description()
   at Eco.Gameplay.Civics.Election.Description()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no.

**Comment by D3nnis3n** [comment]
This should be fixed in the meanwhile.
