### ISSUE TITLE
0.9 localization, seed (tag) should use different string than seed (world generation parameter)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15389]
![изображение](https://user-images.githubusercontent.com/4980243/77822352-da073480-7102-11ea-9a52-bf28a72ff3b1.png)

**Comment by Quadbro** [comment]
Can you change that in tech tree? @Sekor2600

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/82538530-1771c680-9b76-11ea-9bee-da6c1819178a.png)
