### ISSUE TITLE
parameter help no longer appears for chat commands

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15382]
Previously when you made a chat command without proper parameters, it would display a line of help explaining what the parameters were.  This no longer is appearing.

Instead, its showing a list of other commands that match the given string.  This should _not_ be displayed if the user has issued a valid command with invalid parameters.

**Comment by elfl0rd** [comment]
also https://github.com/StrangeLoopGames/EcoIssues/issues/13398 actual too.
