### ISSUE TITLE
[0.9 Staging-1485] Make sure Trade window sizes itself properly

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15381]
I play ECO on a 4k monitor, so I use Interface Scale 75%. During my first day of playing, I was unable to figure out why I wasn't able to sell anything to any store:

![image](https://user-images.githubusercontent.com/964559/77801696-9515cc00-7036-11ea-973a-b5a8024eb383.png)

I asked about it on Discord under general help, and didn't get a good answer. Only after posting the screenshot I was told I need to resize my UI, which fixed the issue. Up to that point I tried clicking on the item and dragging an item from my backpack onto the item in the store to no avail.

So I would appreciate two things:
1) The UI scaling to show the entire window by default
2) A (horizontal) scrollbar being present in case the window doesn't fit entirely on the screen

**Comment by SlayksWood** [comment]
merged to #14733
