### ISSUE TITLE
[0.9.0 Staging - 1489] Crashing when interacting with Government Stations

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15393]
**Steps to reproduce:** Interact with the Government Stations repeatedly.
**Expected behavior:** Ability to make/propose changes to Government Legislature/Demographics etc.
**Actual behavior:** After an extended time (+10 minutes) interacting with and working in one of the Government stations my game crashes to Desktop with no splat messages or anything, it just simply closes itself.
**Providing Log files:** 
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4398233/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4398234/Player.log)

**Comment by Daelmaron** [comment]
#15394 is likely related to this, may be worth porting everything over and merging the two issues.

**Comment by beastyn** [comment]
Can't reproduce with playtest save
