### ISSUE TITLE
[0.9.0 Staging - 1489] Ashlar Chimney not working properly

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15399]
**Steps to reproduce:** build room with Ashlar Chimey, pipe smoke to just under the chimney
**Expected behavior:** Chimney block vents smoke as though it was a pipe
**Actual behavior:** Smoke/Pollution backs up into the room with the smoke producing machine, creates a big cloud of pollution around the entire building
**Providing Log files:**
![20200329055815_1](https://user-images.githubusercontent.com/1329717/77847461-c3a0bd80-7182-11ea-8c22-4e627186fa6f.jpg)
![20200329055800_1](https://user-images.githubusercontent.com/1329717/77847462-c4395400-7182-11ea-8212-45a0721e8e87.jpg)

**Comment by beastyn** [comment]
merged #13561
