### ISSUE TITLE
[0.9 Staging-1489] Fly command uses "c" instead of "crouch" for flying down

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15398]
I have my crouch tied to Ctrl, and "c" brings up the chat window. When I use the `/fly` command, it doesn't use my crouch keybinding, instead defaulting to "c". The controls are fine while swimming in water, but not while flying with this command.

**Comment by SlayksWood** [comment]
merged to #9665
