### ISSUE TITLE
[0.9.0 Staging - 1489] Desync after going through a player built area.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15395]
**Steps to reproduce:** Drive through Scott's player built area.
**Expected behavior:** Drive through and be about my way home.
**Actual behavior:** Experience massive and extreme lag while within a 50 claim radius of Scott's area on the map. (I suspect it may be due to an overcrowding of workbenches/crafting tables and a large amount of smog put out by some of them but cannot confirm as I have no access to the area). 

Shortly after arriving back at my area I experience a desynchronization with the server where my stockpiles and other storage were not registering with a vehicle a foot from them and I could not interact with anything without my game entirely locking up and dropping to 1-3 FPS.

Attempted to disconnect and then reconnect only to get seemingly permanently stuck on the Entering World screen with no progress over the span of 15-30 minutes of waiting.

The area being referenced is Owl City on the map, this issue with desyncs and massive lag also existed in Wolf City before Scott moved his base but was just assumed to be due to a large amount of objects in the area which was for the most part lessened greatly.

**Comment by Daelmaron** [comment]
My game black screened and I had to force close it through task manager as it was completely locked up and would not interact after attempting to reconnect after awhile.

**Comment by beastyn** [comment]
Thank you for the report. Its known issue. we will test it further with performance update.
What is you PC specification and Graphic settings?

**Comment by Daelmaron** [comment]
**System Specs:** 
[System Specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4405986/System.Specs.txt)

**Graphics Settings:**
![20200330185613_1](https://user-images.githubusercontent.com/1329717/77972867-32cbfe00-72b8-11ea-989f-70bb54f0263a.jpg)

**Comment by beastyn** [comment]
@Sarah-Graesyn Thank you for the information. Switching off the Minimap Details option completely should help for now.
