### ISSUE TITLE
[0.9 Staging-1489] Viewing Legislation crashes your game

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15394]
On the test server, I clicked to the Government screen from my UI, then when I clicked "Legislature", the game crashed.

![image](https://user-images.githubusercontent.com/964559/77842609-34c37f00-7149-11ea-8ed9-b4771ff3f182.png)

There is no crash log in the LocalLow\Strange Loop Games\ECO\Crashes folder. My Player.log:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4398372/Player.log)

Steps to reproduce:
- Load game
- Log into the server
- Open up the Government screen
- Click Legislature
- Crash

**Comment by beastyn** [comment]
Can't reproduce with playtest save

**Comment by WeaselDog** [comment]
Hi @ThePiachu. Are you still having this issue in 9.0.4?

**Comment by ThePiachu** [comment]
Tested and the game did not crash.

**Comment by IcedForge** [comment]
Confirmed by issue author as fixed.
