### ISSUE TITLE
Errolo LiteDB from log

### ISSUE THREAD

**Issue by Zeliaf** [StrangeLoopGames/EcoIssues#15397]
some time ago, errors began to appear in the server logs of the type (Error when writing statistics in the DB: InvalidCastException failed to specify the object type " LiteDB.EmptyPage "to type" LiteDB.HeaderPage".) The error only appears when the world statistics are running

**Comment by D3nnis3n** [comment]
That is due to a corruption of the database, which likely happened at a crash. In such cases a working DB needs to be restored from backups immediately.
