### ISSUE TITLE
Avatar rendering breaks at 1000 position

### ISSUE THREAD

**Issue by mrzacharycook** [StrangeLoopGames/EcoIssues#1539]
5.5.4 client and server on Windows Server 2016 with default server worldgen settings

**Reproduce:**
Have one character stand at position 995
Have one character stand at position 5

Begin your character at position 995.  You will see character 995 but not character 5.
Move your character from position 995 to position 5.  As you cross the 1000 mark, you will see character 995 disappear and character 5 appear.

**Comment by metachronism** [comment]
this is fixed in 5.6
