### ISSUE TITLE
Auto walk

### ISSUE THREAD

**Issue by Ravnster** [StrangeLoopGames/EcoIssues#1540]
First a quick video so you can see whats happening(sorry for audio/Watchin a stream)
https://www.youtube.com/watch?v=1mG3EmoxviY

First this happens both with and without a cart. Multiple servers and after server/game restart.
With cart i can adjust the speed by clicking "W" to increase speed(Little by little)
And "S" to decrease speed.

When im walking i only have "slow" speed

**Comment by metachronism** [comment]
looks like something wonky with vehicle efficiency/maxspeed

**Comment by SeanAtr0n** [comment]
Can't seem to reproduce this, please reopen if it still happens for you in a recent release
