### ISSUE TITLE
Under Ground bunker Room Issues and Ramps

### ISSUE THREAD

**Issue by thereporter42** [StrangeLoopGames/EcoIssues#15409]
So this is very 0.8.3.3 Beta

This is a private server I run here with no mods
or anything like that it is totally stock. 

What is happening is I have built an under ground bunker room. 
Now this is all the way down to the core I can not go any lower.
I am using a Stone Ramp and it is all properly placed all the way
down.

Now the issue is the door clearance when you are using a ramp 
and it actually considering my room an actual room. 

Now if I have door at the height it is at right now 
it considers the area to be a room  as you can see
in the picture 

![image](https://user-images.githubusercontent.com/38896397/77873465-4b301000-7207-11ea-985e-0871d2286e35.png)

But the problem is I can't get OUT though the door at this point I hit my head
on the door on the way out because of the angle of the stone ramp. 

![image](https://user-images.githubusercontent.com/38896397/77873504-68fd7500-7207-11ea-9668-a6d33b89b456.png)

Now you would think the simple solution would be to remove two of the 
wall blocks above the door but that won't work either because soon
as I remove those two blocks above the door it now doesn't consider it
to be a room any more and nothing I put in that room will work any more. 

![image](https://user-images.githubusercontent.com/38896397/77873566-977b5000-7207-11ea-8d0e-78bf544d6f92.png)

Now you can see that it is reporting that the room is too big and it 
is no longer recognizing it as a room any longer  to verify that I went
to one of the machines in the room 

![image](https://user-images.githubusercontent.com/38896397/77873606-acf07a00-7207-11ea-8dff-5903fd54bd40.png)

Yes I can get out of the room now with those two blocks missing but it is 
no longer considered a room any longer and nothing works any more
that I put in the room! 

The walls are all made out of flat steel.  The ramp coming down are
stone ramps. 

It is the angle of the ramp that is the issue and the height you have to have 
to be able to get out of the door. You need to adjust this to allow for higher 
doorways so when people use ramps for under ground buildings like this 
you can leave those two extra spots above the doorway open
so that you can actually get out of the door. 

Again there isn't anything I can do to fix this it is the angle of the 
Stone Ramp which is the issue and me trying to get back up the
ramp and the number of blocks I am allowed to have open  for a 
doorway. 

This isn't going to work because of the angle of the ramp
and needs to be fixed.  This is most definitely a bug!  Please
make it so we can leave those two extra blocks above the door 
off and still have it considered to be a room that would be the fix 
here. 

The ramps are kinda an issue because you have to go 4 our each 
time to be able to go one down on the next ramp and it is 
the angles of the ramp here. 

Can you please fix this! Thank you!

**Comment by SlayksWood** [comment]
@thereporter42 
![image](https://user-images.githubusercontent.com/45708377/77904991-29c63700-728e-11ea-840e-b7490d4c2a2f.png)
All works fine for me.

**Comment by thereporter42** [comment]
It doesn't work! You can see the ramp and the door is NOT high enough this matter
is NOT resolved!  It is the angle of the ramp and the lack of height on the door.

This matter isn't resolved it is easily reproduced you did a LONG 
ramp under ground using a stone ramp and then dig a room like
I did and then  Steel walls 

This is BS now I know why I stopped playing this game the staff are
a bunch of amateurs who won't take the reports made by the people beta
testing this for you seriously. 

This matter isn't resolved take this investigate tag off this post and 
the "not reproduced" because you didn't even try to reproduce it. 

This is a 2 wide ramp there are TWO ramps next to each other
as well they are stone ramps. 

The issue is the angle that the ramp has to go down at and the lack
of the door height. 

Fix this issue immediately this is BS wow the staff are a bunch
of amateurs who won't take reports seriously and just dismiss
them immediately like you have just done. 

Wow just horrible get me the head developer for this game now
this matter isn't resolved!

**Comment by elfl0rd** [comment]
You have two blocks space. The height of the character is 1.9. Ramp occupies 1\4 block, as a result for the passage remains 1.8.
All within the limits of the intended game mechanics.

**Comment by thereporter42** [comment]
Clearly you don't because I am all the way down to the mantle I can't go
any lower and you can't get though the door so this is absolutely incorrect. 

You can't get out the door unless you remove the two blocks above it 
but then it doesn't consider the area to be a room any more.  It is due to
the angle of the RAMP so either you have to fix the angle of the
ramp or you have to allow the one extra block high on the door
so you can get out of the door when trying to go up and down
a stone ramp.

**Comment by elfl0rd** [comment]
I specifically attached a screenshot of one of the solutions.
The fact that an opening in 4 blocks is not considered a "door" or a "window" and breaks the room - the intended behavior.
The fact that the character can not pass in the aperture 1.8 blocks high - too.

Rudeness towards the developers is not going to help you.

**Comment by thereporter42** [comment]
Elfl0rd if you are not a dev then keep out of the thread and go away I don't 
need you in here.  I am sick of the devs just simply dismissing tickets and 
not taking them seriously.  Again read what I said above! Your setup is
totally different!

**Comment by elfl0rd** [comment]
> Your setup is totally different!

Srsly?
![изображение](https://user-images.githubusercontent.com/4980243/77940494-6f502780-72c1-11ea-9abf-48a3ac537df6.png)
2x3, as at your screenshots.
Can be passed, room saved.

**Comment by thereporter42** [comment]
Nope it isn't stop posting here because your setup is totally different 
my doors look different and the ramp is totally different. Your doors are 
also setting high Sure if I do that it will work too but it won't consider it a 
room in the room any more until I put two blocks over the door again. 

That is the issue once again Elfl0rd  if you are not a dev then stop 
posting here your setup is totally different than mine and the ramp 
doesn't run straight down like a mine shaft like mine and is built
totally different. 

Stop spamming this ticket Elfl0rd  if you are not a dev then you
should not be posting on other peoples tickets.  Please stop posting
here Elfl0rd

**Comment by elfl0rd** [comment]
Facepalm.
Okay, attach your save.

**Comment by SlayksWood** [comment]
@thereporter42 What should I reproduce? You ignore game mechanics. You should have only **2** blocks as empty space. You have 4 blocks:
![image](https://user-images.githubusercontent.com/45708377/77941779-5f394780-72c3-11ea-9f20-1cb02bae156a.png)
![image](https://user-images.githubusercontent.com/45708377/77941814-695b4600-72c3-11ea-973e-ab29bf1d6f93.png)
It isn't a room, because I have 4 empty blocks:
![image](https://user-images.githubusercontent.com/45708377/77941933-9a3b7b00-72c3-11ea-96a4-5364978c66d9.png)
But you can place door:
![image](https://user-images.githubusercontent.com/45708377/77942019-b7704980-72c3-11ea-9404-b1bd7eee52ba.png)
Or you can place for example ladder. So I recomend to you use construction like this:
![image](https://user-images.githubusercontent.com/45708377/77942184-f30b1380-72c3-11ea-8064-930a17cf9480.png)
Or you should use Large door:
![image](https://user-images.githubusercontent.com/45708377/77942395-36fe1880-72c4-11ea-9f15-dd3d9ceb082c.png)
What am I wrong about? Provide save file or clearer screenshots or videos.

**Comment by thereporter42** [comment]
Look if you are not a dev STOP posting here. I clearly have said what the issue is
the door is NOT tall enough when you are coming down a ramp to get 
though the door due to the ANGLE of the ramp Now if you remove the two blocks
above the door you can get though the door but then the room you
are going into is not considered to be a room any long every screenshot
I have seen you guys are flooding this ticket with is absolutely different
than the situation I am describing. 

I am NOT ignoring game mechanics either! 
I have built a ramp going downwards until I hit
the mantle and it was done to game mechanics being
the ramp goes 4 out and then one down. 

Unless you are a dev STOP posting here or I am going
to start reporting people I am sick of trolls

**Comment by thereporter42** [comment]
And there is no "saved" either I am running the server on a 2nd computer
here.

**Comment by SlayksWood** [comment]
@ you still didn't provide any needed information

**Comment by SlayksWood** [comment]
Instruction for uploading game save is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by thereporter42** [comment]
Yes I have provided all the information required.  SlayksWood are you a dev if not why are you 
requesting anything?

**Comment by thereporter42** [comment]
Forget it I am going to close this ticket since when you open a ticket all you get is 
harassed by non-devs I will never submit any more tickets and this game will
never be successful if the devs are not going to listen to the people beta testing
this for them.  Best of luck but I don't expect this project to last if you continue
this way.

**Comment by elfl0rd** [comment]
Hint, regular users can't do this:
![изображение](https://user-images.githubusercontent.com/4980243/77945783-e38ec900-72c9-11ea-8ef6-1e4e9393cc5c.png)

Besides saying that we "do everything wrong and check wrong" - and ignore the request to attach a save is quite strange.
It's more like trying a fat trolling.

p.s.
> or I am going to start reporting people I am sick of trolls

GL.

**Comment by thereporter42** [comment]
Elfl0rd you are NOT a dev go to hell you idiot and stop trolling tickets 
I am sick of peoplme like you.. It is idiots like you who are going to cause
this project to fail. 

I can read the rules and I have followed the rules you are a compete 
idiot and I don't need this abuse coming from an idiot like you
Elf0rd. 

Stop trolling tickets you should be banned from 
github immediately.

**Comment by elfl0rd** [comment]
Dude, I'll tell you again.
What I wrote to you was repeated to you by the developer, Slayks.
You claim "it's not like that," but you ignore the save request while continuing to rude to the developers.

Calm down and read what we wrote to you again.
If it's really "it's not like that," then attach the save.

Developers have many other tasks besides reading rudeness.

**Comment by thereporter42** [comment]
elfl0rd go away and stop replying on this ticket! You are not a dev you are sabotaging 
this ticket and harassing me you best follow your old suggestions.

Now stop replying here I have no intrest in dealing with a troll 
like you who intentionally tries to sabotage tickets here 

You have absolutely NO right to be posting here you are NOT a
developer on the project and are just harassing people. 

Stop replying here before I file a formal complaint with github.com
about you!

**Comment by D3nnis3n** [comment]
This is your third time being absolutely disrespectful to other people, including developers here, that's enough. Take a 30 day break and think about who is the one a complaint should be filed for.
