### ISSUE TITLE
[9.0 staging-1489] queue stops although resources are in inventory

### ISSUE THREAD

**Issue by BennoHase** [StrangeLoopGames/EcoIssues#15406]
I went to a Farmers Table with 60 corn in my inventory. I queued building 60 corn seeds and added  labor needed. It started crafting and built one corn seed. Then the queue stopped saying missing resources although I still am in front of the table. I had to put all the corn in a connected storage to continue building.

**Comment by SlayksWood** [comment]
@BennoHase It's intented behavior for now. You need either place item to storage or constantly add this by hand.
@WeaselDog 
Can you look at this issue? Maybe we should add some description to ECOpedia. or maybe some notification in tooltip or add announce notification when you start order, that shoud tell players if some resources from backpack or toolbar were added that they should place it to storage.

**Comment by BennoHase** [comment]
yeah fine for me if this is intended. Adding some description to clarify this would be great.
