### ISSUE TITLE
Players can't connect to Playtest server

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15401]
Nothing in the logs on server side, server is running. Player.log empty.

**Comment by D3nnis3n** [comment]
Oh, it's just

--BEGIN DUMP--
Dump Time
03/28/2020 13:12:43

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Private.CoreLib

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Eco.Gameplay.Civics.CivicAction_ChangeElement.Description()
   at Eco.Gameplay.Civics.Election.Description()

--END DUMP--


again.

**Comment by MishkaFur** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4398946/Player.log)

player-prev did not change at all

**Comment by MishkaFur** [comment]
Gets stuck on "Entering world" for ages, if hitting escape it goes to the below screenshot

![image](https://user-images.githubusercontent.com/61889138/77850453-a55eb000-71ca-11ea-863b-0859895ed5a6.png)

Then goes to this screenshot and have to Alt F4 the game
![image](https://user-images.githubusercontent.com/61889138/77850464-b27b9f00-71ca-11ea-8d4c-28fd6619a1c3.png)

Ram usage also goes straight up to maxing out the PC, have to then Force quit Steam through task manager as Eco.exe does not respond, Additional log attached

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4398975/Player.log)

**Comment by VokrugShum** [comment]
[Uploading message (2).txt…]()

**Comment by ThePiachu** [comment]
I was able to connect to the server, and then disconnected some 10-15 minutes later. Here is my log

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4399792/Player.log)

**Comment by ThePiachu** [comment]
By the way, the game using 26GB of memory is normal, right? Maybe that's the reason I was able to connect and others couldn't - because I had some good amount of RAM. It could also point to why the game has been lagging in the last few days - maybe something is using a lot of memory?

**Comment by ThePiachu** [comment]
I was able to connect to the server earlier today, but currently I can't. At least I'm getting a proper error:

[text and log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4400385/text.and.log.txt)
