### ISSUE TITLE
[0.9 Staging-1489] Unable to clear some food plants with the machete

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15408]
I tried clearing some food plants from my plot with the machete and it didn't seem to work. Tested it on a few plants. The tool doesn't work on things like:

- Tomatoes
- Corn
- Beets
- Huckleberry

But it does work on:

- Papaya
- Wheat

It should work on all non-tree plants probably.

**Comment by WeaselDog** [comment]
Thanks for the feedback. We will make some changes here.

Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/13154
