### ISSUE TITLE
Eco Tree dev features

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15407]
![image](https://user-images.githubusercontent.com/3536496/77865858-49555500-71e5-11ea-8a7f-718f1cffa304.png)
I'd like to expand the role of the dev icons here and make it part of our daily updates.  The idea is that we make this a center for public development and personal connection between the team and community. 

- [x] Jeff: add HTML code and styles for all the improvements of Tooltip, so Denys would just filled them with logic afterwards. Like `status`, `title`, `bio` and `email` links.
- [x] Denys: Add the ability to set a 'status' for each developer of what they're working on, with the date that the status was applied. Display this status in the tooltip.
- [x] Denys: Display a title for each dev (mentioned this before but would like to do it).  Programmer, designer, artist, QA.
- [x] Jeff: Have two links in the tooltip that can be clicked, bio and email (not all devs have slg email, some signed up to wordpress with their private email. we dont want to publish private emails, so create new user field for email. should be optional).
- [x] Denys: Have an easy way for the team to set their status. They will be doing this everyday, so make sure it's easy.  Ideally they can just open a page, click the node they're working on, and type a short status.  

Bonus:
- [ ] Have 'recent updates' for each user, that links to the last few posts they made in the eco tree somewhere.

**Comment by denysaw** [comment]
Bonus is totally dedicated hard task. If that's really needed, it should be ripped off into separate Github issue and preferably w/o `Beta 9.0` milestone :)

**Comment by rainfarmer** [comment]
For labels, I left out email and bio. if you click on dev it will go to their bio and email

**Comment by rainfarmer** [comment]
Goal: Make it easy for devs to update the eco tree. And display daily changing dev info to keep the fans happy.

Setup a new shortcut area for tree updates.
Ideally this is a discord bot, or on wordpress.

They can input
1 their custom 'status',
2 the feature node they are working on (from a drop down),
3 And have the option to create a tree update post for a particular node (should support pictures and basic text formatting)

When a dev updates their current feature node, we need to auto remove them from the old node they were working on. So they can only be assigned to one node at a time.

and also auto toggle the 'in progress now' label for the features (see description in comment below)
We added a custom input for job title to user page, but the wordpress api does not pass it. Update wordpress api to pass custom user variables. Specifically the job title of users.

1 wondering if you could do that from db using sql command

Currently each node has these choices:
Active Feature 1
Active Feature 2
Active Feature 3
Active Feature 4
Active Feature 5
Active Feature 6
Active Feature 7
Active Feature 8
Active Feature 9
Active Feature 10
In Progress 1
In Progress 2
In Progress 3
In Progress 4
In Progress 5
In Progress 6
In Progress 7
In Progress 8
In Progress 9
In Progress 10
Future Feature

Need to update that to
1 - Foundations
2 - Partially Implemented
3 - Implemented
4 - Features Complete
5 - Polished
1 - Foundations (In Progress Now)
2 - Partially Implemented (In Progress Now)
3 - Implemented (In Progress Now)
4 - Features Complete (In Progress Now)
5 - Polished (In Progress Now)
0 - Not started
