### ISSUE TITLE
[0.9 Staging-1489] Show item durability in shops

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15405]
Shops not displaying item durability could lead to people selling broken tools for the price of fixed ones. For example, I tried buying a road tool, only to get a broken road tool:

![image](https://user-images.githubusercontent.com/964559/77860920-bad1db00-71c6-11ea-83c7-0bb123fc45ba.png)

Maybe display something along the lines of "highest available quality: 0%" next to the items and colour it accordingly - green for good quality, red for bad quality, etc.

**Comment by beastyn** [comment]
The third colum "Min Durability" is not helpful?
But we will need to change it a bit for information in %, not in the numbers.
Or it was incorrect for you?

**Comment by ThePiachu** [comment]
Is that the minimal durability it can sell, or will sell? I'm guessing it would be the former - telling you that you get something of "at least quality X".

One way or another, if you're an idiot in a hurry like me, you might miss it - the status of the item as displayed is removed far from the item visually. It would perhaps be nice to make that connection clearer. Sure, the information might be there, but it's easy to miss at a glance...

**Comment by beastyn** [comment]
Its min durability it will sell. 
So, don't buy a tool with 0 in min durability column (these sales are usually for those who repair the tools).
I will make separate issue for durability info in %, lets see how it will work

**Comment by SlayksWood** [comment]
#15419
