### ISSUE TITLE
some skills need masonry

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#1541]
what

**Comment by MGrand3** [comment]
Is this relevant? http://ecoforum.strangeloopgames.com/topic/2422/cement-processing-broken-in-staging-alpha-5-6-9727af80

**Comment by REPOSEECO** [comment]
Example Skill is Level 4 but you can't create the Brick Chimney Top (Yellow Text --> Masonry 3 needed )

**Comment by craig-jong** [comment]
Yes, those are all related.
