### ISSUE TITLE
[0.9.0 Staging 1489] Trying to build ladder upwards places it behind you 

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#15411]
**1. Version:** 0.9.0 Staging 1489
**2. Steps to reproduce:** Stand on ladder, try to extend it upwards
**3. Expected behavior:** Ladder is built where the "ghost item" is displayed
**4. Actual behavior:** Ladder is built behind your player
**5. Providing Log files:** N/A

**Trying to build ladder:**
![image](https://user-images.githubusercontent.com/982322/77877469-27e08180-7256-11ea-85e1-8c3bbc9d0e2f.png)
**Actual placement:**
![image](https://user-images.githubusercontent.com/982322/77877478-2e6ef900-7256-11ea-9e0b-9b6750000356.png)

**Comment by SlayksWood** [comment]
merged to #13110
