### ISSUE TITLE
[0.9.0 staging-1491] Can't open Objective Window

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15413]
![image](https://user-images.githubusercontent.com/45708377/77881952-a5ad8880-7268-11ea-8dde-f3be16298ab6.png)
Seems broken after this https://github.com/StrangeLoopGames/Eco/pull/5818

**Comment by johnkslg** [comment]
Bad merge, fixed via direct checkin to staging.
