### ISSUE TITLE
[0.9.0 staging-1491] Can't see tooltip in Chat

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15418]
![image](https://user-images.githubusercontent.com/45708377/77902120-5deb2900-7289-11ea-8361-d348f2f2526d.png)
BUt I can see it if I open chat:
![image](https://user-images.githubusercontent.com/45708377/77902209-7fe4ab80-7289-11ea-8045-0ebdd3e2764b.png)

**Comment by MishkaFur** [comment]
This started happening on 1489 if it helps, was fine before then I believe.

**Comment by SlayksWood** [comment]
fixed with #https://github.com/StrangeLoopGames/Eco/pull/5839
