### ISSUE TITLE
[0.9.0 staging-1491] Authorization from Registrar, Treasury, Bank reset with server restart

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15412]
- step to reproduce:
- place bank, Treasury and registrar. Delete Everyone in authorization and add some demographic or player:
![image](https://user-images.githubusercontent.com/45708377/77878841-ee157800-7261-11ea-8fee-19cf3298cb68.png)
![image](https://user-images.githubusercontent.com/45708377/77878853-f7064980-7261-11ea-8aaa-ee32411e0e0b.png)
![image](https://user-images.githubusercontent.com/45708377/77878869-01284800-7262-11ea-8321-221cbd6ebd89.png)
- restart server. check it again. All of this objects have Everyone again:
![image](https://user-images.githubusercontent.com/45708377/77879116-65e3a280-7262-11ea-89d4-c51cdf8caf63.png)
![image](https://user-images.githubusercontent.com/45708377/77879161-7136ce00-7262-11ea-9e53-9f1c7ec2053e.png)
![image](https://user-images.githubusercontent.com/45708377/77879185-7b58cc80-7262-11ea-98e0-0d94fd78f35b.png)

**Comment by WeaselDog** [comment]
Is it only these 3 objects? Does store or civic buildings reset?

**Comment by SlayksWood** [comment]
only these 3 objects. I closed your issue  with adding Everyone to other civics objects, it works right to them.
