### ISSUE TITLE
[9.0 Staging 1489] Ecopedia - Storage component incorrect screenshot

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15428]
is using an old screenshot showing logs and stone which are not patr of the new system.

![image](https://user-images.githubusercontent.com/61889138/77959110-fc997900-72cd-11ea-9788-44ec0de9ced6.png)

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/15311
