### ISSUE TITLE
[9.0 Staging 1489] Ecopedia Blocks not all grouped together in some sections

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15429]
Logically items should be grouped together in Byproducts, Crafted, Material and Natural resourcesunder Building materials they are grouped.

![image](https://user-images.githubusercontent.com/61889138/77959714-f952bd00-72ce-11ea-8400-968a55a935a0.png)

Should be for example Iron Bar, Copper Bar, Gold Bar, Steel bar, Iron Pipe, Copper Pipe, steel Pipe, Stone Road, Asphalt Road, Barrel, Petroleum

![image](https://user-images.githubusercontent.com/61889138/77959856-33bc5a00-72cf-11ea-9d63-4936ed105ca8.png)
Stone should be grouped together, ores together then logs.

**Comment by beastyn** [comment]
@johnkslg need your vision here

**Comment by johnkslg** [comment]
Makes sense.  Giving to Todd
