### ISSUE TITLE
[9.0 Staging 1489] Ecopedia - Repair Component incorrect screenshot

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15427]
Screenshot shows Enhancements which is not in the build. (also text is wrapped if it was coming later)

![image](https://user-images.githubusercontent.com/61889138/77958936-bc39fb00-72cd-11ea-8d18-588667d92c41.png)

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/15311
