### ISSUE TITLE
[21f43d75] Tailoring Table is Broken

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1542]
"It was also broken in the previous staging, it basically places, but cannot be selected and you can walk through it, also using everything i could , trying to use the admin command level to get rid of it didnt work also. This is a pretty big bug as it makes tailoring inaccessible, though i imagine something this big is already known. But thought i would mention it none the less. :) Also any idea on how to get rid of these ghost tailoring tables would be great :P"

Reference: http://ecoforum.strangeloopgames.com/topic/2423/tailoring-table-in-staging-build-21f43d75-broken

**Comment by MarjieAVolk** [comment]
>> I don't think this object is supposed to be in the game?  @keegan-o ?

**Comment by craig-jong** [comment]
the object just doesn't have a collider; it's been added now in SVN.
