### ISSUE TITLE
[9.0 Staging 1489] Server fails to load on non desktop OS

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15424]
1. 9.0 staging 1489
2. try loading ecoserver on a non desktop OS (I only have access to Win 10)
3. Server Loads?
4. Server errors with dll not found exception, happens on Server 2016 and Server 2019, Several installs of Win 10 are fine

Error mentions Mirasrael for some reason, not sure if that is ominous
![image](https://user-images.githubusercontent.com/61889138/77954587-bf7db880-72c6-11ea-9a2b-bbf49aab1d1c.png)

**Comment by redwyre** [comment]
Are you running 32bit or 64bit? Does it happen for both?

**Comment by MishkaFur** [comment]
64 Bit on both, did not seemingly get an email to say this got responded to, I will spin up a few VM's over the next day or two to test Server 2012.

Windows 10 Build 1903 (two machines)
Server 2019 Build 1809
Server 2016, Unknown build Number

**Comment by MishkaFur** [comment]
Server 2016 and Windows 10 1909 with all updates, .net framework all installed

![image](https://user-images.githubusercontent.com/61889138/78811124-4b779a80-79c1-11ea-8c50-a8d4fffc34ed.png)

Server 2012 R2
![image](https://user-images.githubusercontent.com/61889138/78812635-a27e6f00-79c3-11ea-8002-e4136f3519e6.png)

The server 2012 popup gave me a useful error message which I do not know why but does not appear on Server 2016, Server 2019 or Windows 10

It appears Visual C++ 2015 Redistributable was not installed but required for running a server, Soon as I installed it via https://www.microsoft.com/en-in/download/details.aspx?id=48145 link, the server has started and is connectable.

This is on now staging 1501 for the above screenshots, Do you want any other logs or info?

FYI no where can I see it mentions that C++ Visual Studio 2015 distributable needs to be installed for the server to run, it was probably fluke that the other Win 10 machines I originally tried it on had it installed.

**Comment by mirasrael** [comment]
@MishkaFur thanks for detailed error info and your investigation!
Added VC Redist to Steam components and also added more informative message when failed to load ENet library.
