### ISSUE TITLE
[0.9 Staging-1489] Arrastra ore cost doesn't benefit from Modules

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15420]
I was trying to compare how Arrastra performs in comparison to the T2 replacement when I noticed that the Modules don't seem to affect ore price on that machine. No modules, 120 copper ore makes 20 crushed ore:

![image](https://user-images.githubusercontent.com/964559/77909049-76cfec00-7241-11ea-89b0-74f598a5b366.png)

Level 5 Module, 120 copper ore makes 20 crushed ore:

![image](https://user-images.githubusercontent.com/964559/77909098-923af700-7241-11ea-90b5-3f05b6f71a28.png)

I tried with a Level 4 Module, still nothing. Hammered the machine and placed it again, still nothing. You can see the machine recognises the Module though with the reduction in time. It would probably be worth checking all of the new ore recipes for similar bugs...

**Comment by SlayksWood** [comment]
It's intended bahavior:
![image](https://user-images.githubusercontent.com/45708377/77910486-dfe24e80-7297-11ea-8fb8-df59eed5eae7.png)
We have issue about deleting benefit in tooltip #15085 for this recipes.
