### ISSUE TITLE
[9.0 Staging 1489] Ashlar balance

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15425]
Ashlar seems a little unbalanced compared to resource usage needed for Masonry

Ashlar stone door is 10
Ashlar Stone chair is 20
Ashlar stone bench is 20
Ashlar Stone table is 20
Ashlar stone fireplace is 20

Masonry for comparison is Door, 10, Chair 8, Bench 20, table 20 and Fireplace 30.

Ashlar should probably follow the same kind of resource requirements, a chair and bench costing same amount seems odd how the bench is double the size, Signs seem about right due to the physically extra material they have on show.

**Comment by WeaselDog** [comment]
Thanks for the report. We will be reworking these numbers.

**Comment by beastyn** [comment]
Asking for revision
Now (without modules)

Ashlar Stone Fireplace - 24 stones
Mortared Stone Fireplace - 60 Stones.

Why difference is so big?
And for bench:
Ashlar - 12
Mortared - 40

**Comment by WeaselDog** [comment]
@beastyn We talked about this and it is intentionally because of the large price difference between Ashlar Stone & Mortared Stone. Ashlar Stone also gives 3x the experience of Mortared Stone, which is consistent with these price differences.
