### ISSUE TITLE
[9.0 Staging 1489] Store Component in Ecopedia shows incorrect screenshot

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15426]
![image](https://user-images.githubusercontent.com/61889138/77958555-1edec700-72cd-11ea-9eee-de3449644bbe.png)

Shows the old log system which no longer exists

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/15311
