### ISSUE TITLE
[0.9.0 staging 1489] Advanced Carpentry table needs iron  saw blade/bars not steel ones

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15435]
1. Staging 1489
2. Build Advanced Carpentryt able
3. Should have same resource requirement as Advanced Masonry table
4. Only needs iron saw blade and Iron bar whereas Advanced Masonry table needs Steel saw blade and steel bars

**Comment by WeaselDog** [comment]
Yes I see what you mean. We will get this fixed, thanks again!

**Comment by ScottEco** [comment]
WeaselDog ? That is only Mishka's opinion... not necessarily something to do. Both tables need industry anyway to be crafted, so iron or steel doesn't change the balance of the game, and I personnaly think that this difference is better... cutting wood or cutting stones, in real life, do not need the same blades.

**Comment by MishkaFur** [comment]
https://www.quora.com/What-type-of-steel-are-circular-saw-blades-made-of

https://www.google.com/search?client=firefox-b-d&q=What+are+circular+saw+blades+made+from

Circular saw blades are made from steel, with the tips being made from other material depending on what is being cut ie diamond tips

If Steel is not used ingame then the resource requirements of iron saw blades should be higher so both tables are balanced resource wise to make them.

**Comment by WeaselDog** [comment]
Thanks for the feedback all. We will be changing both tables to cost Steel, but the costs will not be identical in terms of Saw Blades needed.
