### ISSUE TITLE
[9.0 Staging 1489] Ecopedia - Eco development page - URL is unpleasant visually

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15434]
![image](https://user-images.githubusercontent.com/61889138/77961752-3cfaf600-72d2-11ea-9c1f-51ad099c0c31.png)

URL should just be www.play.eco and ideally not underlined

**Comment by WeaselDog** [comment]
Thanks for the feedback.

This also causes a warning in server initialization so something has to change here.

**Comment by WeaselDog** [comment]
@Quadbro Need help with this. Changing the text or removing the code for this does not work.

It probably has to do with brackets, but here is the code that won't change. This following block of code is in Server\Mods\Ecopedia\Eco Development\Eco Development

`<![CDATA[<style="InfoLight><u>http://play.eco/</u></style>]]>`

**Comment by Quadbro** [comment]
@WeaselDog What do you want to change there?)
