### ISSUE TITLE
Hosted worlds: online players should list whos online

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15438]
![image](https://user-images.githubusercontent.com/3536496/77975473-ff38a600-72ae-11ea-84b7-c8876b98feae.png)

**Comment by denysaw** [comment]
Hey Mike. Can you gimme please server's API endpoint for getting an online players list?
Cuzz I was taking those nums from `/info` and this improvement gets rid of such simplicity :) Thanx ;)

**Comment by beastyn** [comment]
@gzatravkin I assume that question  ^^ is for you now.

**Comment by denysaw** [comment]
@gzatravkin Hey =) Any news about this? :)

**Comment by gzatravkin** [comment]
@denysaw No. It's low priority of milestone 0.9.1, gonna be fixed after all isues of 0.9. Do you need escalation of priority?

**Comment by denysaw** [comment]
Hehe ) There was no need to develop :) Only to answer are there some endpoints for that or just planned to be implemented ;)
No hurry, sure ) Ok, kinda adding Postpone/Waiting label here :) Thanx for info ;)

**Comment by denysaw** [comment]
@gzatravkin Hey ;) Seems priorities changed now. Please, inform me when your side is done, so I'll start mine ;)

**Comment by gzatravkin** [comment]
Added to serverinfo in https://github.com/StrangeLoopGames/Eco/pull/6843 as OnlinePlayersNames

**Comment by denysaw** [comment]
@beastyn Could be tested on `stagingland`, but mind, that online users could be shown only on world version 9.0.2-beta-develop-66+ (will be available on staging versions after gameDevs will merge `develop` into it (maybe it has already happened, but I cannot be sure), anyway it's just a question of time).
