### ISSUE TITLE
[9.0 Staging 1489] Ecopedia Crafted Objects Furniture lots of icons missing

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15430]
Lots of icons are just white, hovering over and clicking seems tos how the correct item.

![image](https://user-images.githubusercontent.com/61889138/77960082-944b9700-72cf-11ea-8889-d71b1b44d38a.png)

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/15139
