### ISSUE TITLE
Icon Updates and New Icons

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15436]
This is a list of icons to begin tackling the backlog of placeholder icons that need replacements/original art, and to also begin fleshing out some item groups where refinements in the tech tree will require new icons in the near future as well.

_Plastic Items_
These are icons for plastic products that are created for various crafting uses. Basically these are more industrial products that will be made by big machines from the raw preto-chemical ingredients for plastic, and then they can be used to craft all sorts of things that need plastic ingredients or components. 

- [x] **Plastic Block**
- [x] **Plastic Sheet**
- [x] **Plastic Pellets**

- [x] **Fiberglass Item**
currently uses the glass icon, should have its own. Fiberglass is a very important and useful material, I think the icon can try to represent a little bit how it's made by having a sheet of fiberglass, and then on the edge there can either be a woven pattern coming out from it, or just a series of glass fibers coming out. 

- [x] **Synthetic Rubber Item**
This is our manufactured rubber item, kind of a weird name but the idea is we might eventually have a rubber tree plant or something from which a natural rubber is derived. This is rubber made from petrochemicals. This _may_ eventually be a block item, but that's pretty low priority. This is an ingredient in things like rubber tires, a rolled sheet or tubing would be good like this image:
![image](https://user-images.githubusercontent.com/14983165/77968679-cabbee80-729c-11ea-9c7d-1d1590dcbcc1.png)

- [x] **Rubber Wheel Item**
We have lots of wheel icons already, for this one I think the easiest would be to just make a copy and revamp the 'vehicle tag' icon so that it is not transparent-- so it's done in the style of a regular item, that is:
![image](https://user-images.githubusercontent.com/14983165/77951525-0fd12800-727f-11ea-8caa-653a7c4121a4.png)

- [x] **Radiator Item**
This item is used in the construction of things like advanced combustion engines. Here is the item description:
A heat sink that uses liquid running through copper fins to disperse heat build-up.

- [x] **Heat Sink Item**
Used in crafting the radiator item, here is the item description:
A copper plate to draw and disperse heat.

- [x] **Servo Item**
Item description: A rotary actuator that allows for control over angular position. Used as an ingredient for the advanced combustion engine, etc.
(currently it's just a placeholder set of gears)

- [x] **Portable Steam Engine Item**
This item is used as an ingredient for the steam truck and tractor. Currently it is using a placeholder of a more advanced engine than it should be. Make this more like what you see in the steam truck vehicle. 
![image](https://user-images.githubusercontent.com/14983165/77956238-6857f380-7286-11ea-9084-9805682241da.png)
![image](https://user-images.githubusercontent.com/14983165/77956380-a05f3680-7286-11ea-9d31-b7e5f0125ea7.png)

- [x] **Advanced Combustion Engine**
Currently we have an icon for a combustion engine, which looks like this: 
![image](https://user-images.githubusercontent.com/14983165/77966272-88dc7980-7297-11ea-91ff-4bd6c5336557.png)
For the advanced Combustion engine icon, just make a new copy of that icon that is more advanced or upgraded in some way, even just with a color shift or some new element, perhaps wiring coming out of it.

_Various Chemical Elements_
We need icons for the elements important in soil nutrients, which are:
- [x] **Oxygen**
- [x] **Nitrogen**
- [x] **Phosphorus**
These could be done as elemental table symbols, or with physical indications of one of their states of matter plus their elemental designation. Could even be depictions of the actual molecule structure.

_____________________

_Concrete Items and Icons_

This is a great image to keep in mind as an overview of the things we're going to be representing with cement and concrete:
![image](https://user-images.githubusercontent.com/14983165/77965962-ffc54280-7296-11ea-84a0-adf64dde0390.png)

- [x] **Cement Item**: This is a powdery mix that is an ingredient needed to craft concrete. It will be stored in paper/synthetic bags and eventually in Eco it will be a block item, meaning it will have mesh art and sit in the world. So the icon should be cement stored in bags, perhaps with a little pile of the powder in the foreground (or not).

- [x] **Bitumen Item**: This is a naturally occurring form of asphalt that is a shiny black rock-- it will be part of what you get when you mine oil shale and other physical sources of petroleum. It can also be manufactured from oil at the oil distillery (manufactured bitumen looks pretty much the same as naturally occurring. Bitumen in the key ingredient in making asphalt concrete.
![image](https://user-images.githubusercontent.com/14983165/77965467-e7a0f380-7295-11ea-8415-6f076f3bd338.png)

- [x] **"Concrete Craft Icon"**
We should have an icon that depicts water and aggregate (crushed rock) being poured together with cement. This can be used for an item if we make concrete a generic transportable item, or as a UI button for a concrete-mixing vehicle.
- [x] **"Asphalt Craft Icon"**
This should be much like the concrete craft icon only it should show bitumen entering the mix.

- [x] **Concrete Block Item**
A crafted big block of concrete. 

- [x] **Asphalt Block Item**
A crafted block of asphalt concrete. This will be for roads or sidewalks, and will likely start out as an item and then change into being a function on the mixing vehicle that designates you are laying down a block of asphalt.

- [x] **Concrete Mixer Item**
This will be a mixer that could be in a stationary world object or a module for a truck, that can mix concrete together for use in building or road-building.

_____________________

- [x] **Charcoal Item**
Charcoal currently uses the coal icon in a weird way, make an icon for charcoal that is more clearly manufactured brisket shapes in a pile. Could be inside of a bag, but I think if it is it should be a top down or 3/4 view where you can see the charcoal, not just a labeled bag.

- [x] **Compostables Item**
These is an item representing things which **can** be composted but have not been composted yet-- so vegetable scraps, bits of soiled paper/cardboard, bones, etc. No dirt should be included in the icon. (currently it is just using the compost icon)

_Fabric Icons_
As we get into tailoring content we'll need icons for different fabric materials.

- [x] **Wool Fabric Item**
Wool fabric is made from mountain goat and other animal furs/hair.

- [x] **Cotton Fabric Item**
Cotton fabric will be made from the cotton plant.

- [x] **Nylon Fabric Item**
Nylon fabric will be made at a spin melter machine that creates filament fibers of plastic.

- [x] **Screw Item**
We have a rivet icon but not a screw icon. (screws are using the rivet icon)

- [x] **Dirt Road Block**
Icon for dirt road blocks. 
______________
Direct Icon Updates for World Objects:
These are icons that should be edited directly in the sprite sheet to replace an old outdated icon, because the world object for the item has changed in appearance or it was a placeholder. Give yourself the item in-game to see what the new objects are:

![image](https://user-images.githubusercontent.com/14983165/77970081-2c318c80-72a0-11ea-8692-7e75a96b21c1.png)
- [x] **Coin Mint** -- this is the world object you just finished making the art for, need an icon update for it as well!
- [x] **Lumber Stockpile**
- [x] **Large Lumber Stockpile**
These are located in ui_icons_03

**Comment by RobertMangano** [comment]
Icons have been created and put on icon sheets
