### ISSUE TITLE
[0.9.0 Staging 1489] Temporal Anti aliasing causes Small hanging Wood signs to flicker

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15437]
1. Staging 1489
2. Place a Small hanging wood sign (doesnt matter what one), move away around 10 blocks at a 45 degree angle
3. Not flicker?
4. Sign flickers

Only seems to affect the small hanging signs, large signs are okay, soon as Anti aliasing is not temporal it stops, also happens for @Daelmaron

I am on a Nvidia 1660, Windows 10, both fully updated

https://i.imgur.com/rrqDlfx.gif

**Comment by Daelmaron** [comment]
[System Specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4406020/System.Specs.txt)

Theres my system specs, nVidia 2060 EVGA, Windows 10, both fully updated.

**Comment by redwyre** [comment]
I don't recommend using temporal anti-aliasing, I might just remove it. (Despite being last on the list, it's not the "best" which is probably misleading)

**Comment by redwyre** [comment]
replaced with https://github.com/StrangeLoopGames/EcoIssues/issues/16332
