### ISSUE TITLE
[9.0 Staging 1489] Ecopedia - Upgrade Modules have no icons

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15433]
![image](https://user-images.githubusercontent.com/61889138/77961328-93b40000-72d1-11ea-82cd-30720fcb12da.png)

upgrade modules have no icons, text seems to be corrcet though

**Comment by WeaselDog** [comment]
Really appreciate all the detailed reports! I will be merging many of these into existing issues so we can tackle them all at the same time.

Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/15139
