### ISSUE TITLE
[9.0 staging 1489] Ecopedia Fuel missing

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15432]
Charcoal is missing from Blocks > Fuel

Items > Fuels only shows charcoal?

**Comment by WeaselDog** [comment]
Thanks for the report. Charcoal is not actually a block, but there should not be a fuel page in items for only one item. We will improve the categorization.

**Comment by MishkaFur** [comment]
Biodiesel and Gasoline should not be in it either as they are not "a block" or do you mean block as in placement style?

**Comment by WeaselDog** [comment]
Yes, those are considered blocks because of how they are placed. Charcoal is an item that can go in inventory or storage chests.
