### ISSUE TITLE
Map tutorial needs updating

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15443]
![image](https://user-images.githubusercontent.com/3536496/77976059-bf72be00-72b0-11ea-98b2-0952aabb8d4a.png)
The first entry, 'Open the map', starts checked, because the map is always docked now. Change it to 'Open the full-screen map.' and have an error that points to the button to do that (using the arrow system other tutorials use). 
Configure the tutorial to require this step before the others complete (there should be support in there already for this).

**Comment by SlayksWood** [comment]
Need to add a second arrow if the player accidentally misclicks or he has previously had a small minimap open:
![image](https://user-images.githubusercontent.com/45708377/79098791-63f20700-7d6b-11ea-8e72-c92bd01d7fd9.png)

**Comment by MrAnonymous110** [comment]
For now, the tutorial can complete by open minimap in both windowed mode or full-screen mode. If the map already open,  the tutorial task will auto-completed when showing up.

**Comment by SlayksWood** [comment]
completed when I have minimap in corner, i don't open full-screen or windowed:
![image](https://user-images.githubusercontent.com/45708377/98918448-ae448d80-24de-11eb-9050-d90bd64f4c53.png)

**Comment by SlayksWood** [comment]
3rd point still doesn't work:
![image](https://user-images.githubusercontent.com/45708377/101450676-f74ffc00-393b-11eb-87ff-8ae4c3a3d298.png)

Others were fixed.

**Comment by SlayksWood** [comment]
I have problem with Open the map again in staging-1869

**Comment by MrAnonymous110** [comment]
The issue may be happening again after merging the issue or some other fixes make the function break. I fixed it all.

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/103123162-6ba4d200-4694-11eb-8a5f-9ea16576bc4c.png)
and fixed:
![image](https://user-images.githubusercontent.com/45708377/103123182-82e3bf80-4694-11eb-8411-2c2ecb82a68a.png)
