### ISSUE TITLE
Claiming land tutorial needs change

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15447]
![image](https://user-images.githubusercontent.com/3536496/77976555-2c3a8800-72b2-11ea-947b-3b2f85dcf54e.png)
The first element about getting land claim papers is no longer relevant because you start with them in your backpack (I think?)
Remove it

**Comment by johnkslg** [comment]
Bonus fix:
![image](https://user-images.githubusercontent.com/3536496/77976653-699f1580-72b2-11ea-9f0f-b84b7c742eec.png)

Text should be reworded, 'Change the form type in the building menu by pressing F while holding a hammer.'

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/77976710-8cc9c500-72b2-11ea-9b80-57deb17f9953.png)
And 'Change the fill type in the building menu by pressing F while holding a hammer.'

**Comment by SlayksWood** [comment]
@johnkslg 
You have basic 4 Land Claim Papers, but when you place your tent you can spend 2-4  (depends on Campsite location). So in some case you need to take Papers from your tent. Also We need some changes in this behavior #13690 to avoid unpleasant situations, so this string needs.

Bonus fixes moved to construction tutorial #15223. So I close this issue as not actual.

**Comment by SlayksWood** [comment]
@olegshegai Can you add your claiming changes to the tutorial?

**Comment by olegshegai** [comment]
Hm... adding actions will make the tutorial too complicated, I'll just add some tips at the end like with markers tutorial
