### ISSUE TITLE
Meteor tutorial sequence problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15442]
- [x] When looking at the meteor to trigger the tutorial, it's supposed to show a title 'Meteor spotted' and zoom in on it. This didnt happen, it skipped right into the slides.  
- [x] The first slide had the next slide visible behind it.  
![image](https://user-images.githubusercontent.com/3536496/77975964-7de21300-72b0-11ea-8b84-1a240f253a85.png)

**Comment by olegshegai** [comment]
Seems to be okay in latest staging
