### ISSUE TITLE
Remove/change layout so there are no question mark blocks in the hammer menu

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15448]
![image](https://user-images.githubusercontent.com/3536496/77976782-c4d10800-72b2-11ea-9ba1-2766f8daa111.png)
I think we dont need icons for these categories, a title alone should do.

**Comment by keegan-o** [comment]
Indeed, it takes up a slot for no real reason (have been asking for a long time if they could be removed)
