### ISSUE TITLE
Map UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15444]
![image](https://user-images.githubusercontent.com/3536496/77976182-0f518500-72b1-11ea-9a9d-30aa20992970.png)
Map settings should be closed on first open.
On subsequent opens, it should remember its position.

**Comment by SlayksWood** [comment]
@johnkslg 
It would be logical to leave it as it is now. If you open a full-sized map, then you definitely want to check some environment data or districts. This I asked to do this behavior.

**Comment by johnkslg** [comment]
Not necessarily, I like the feeling of seeing the giant globe in the screen without distraction, at least once.
