### ISSUE TITLE
UserStatus is no longer tooltipable or clickable 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15455]
![image](https://user-images.githubusercontent.com/3536496/77980710-cef80400-72bc-11ea-9f66-be41e06e2134.png)

**Comment by SlayksWood** [comment]
It isn't clickable if you have one thing(or room or deed). But if you have Room and Deed at once I can click it.
I assume It happens in one time: #15418, #15368.

**Comment by SlayksWood** [comment]
Can't click here too:
![image](https://user-images.githubusercontent.com/45708377/78115764-f27d9480-740b-11ea-977e-dd149702b92b.png)
Don't want to create separate issue I think It's a one problem.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5839
