### ISSUE TITLE
Long contract name causes client/payment text overlap

### ISSUE THREAD

**Issue by TemporalWolf** [StrangeLoopGames/EcoIssues#15458]
Version: 0.8.3.3 beta

If you put in a long contract name (doesn't need to be anywhere near this length, just more than one line worth for the given UI box) it causes the client and payment columns to overlap/split strangely, see the right side of the attached image:

It says Client: TemporalWolf Payment: 5 Greenleafs, but those are totally mangled.

![image](https://user-images.githubusercontent.com/34265614/77996695-f4980400-72e2-11ea-8e98-0f3bc5740d81.png)

**Comment by beastyn** [comment]
Contract name will have limit for symbols in 9.0
