### ISSUE TITLE
Food tutorial broken

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15452]
Says I need to collect Wild Beet at a marker, but no marker exists.

**Comment by SlayksWood** [comment]
How exactly did you get hungry?
![image](https://user-images.githubusercontent.com/45708377/78001150-f7741280-733d-11ea-8b0a-30f068d85890.png)

**Comment by johnkslg** [comment]
hm maybe there was just nothing around for me.  @StanKryvenko I think covered that case though

**Comment by SlayksWood** [comment]
I didn't have that. Always at least 1 appears. But it should be at least 3 minimum #14953

**Comment by WeaselDog** [comment]
Check as part of linked issue
