### ISSUE TITLE
Tutorial for housing objects has missing sprites

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15454]
![image](https://user-images.githubusercontent.com/3536496/77980288-c7842b00-72bb-11ea-8c7c-3f9ebd3ee517.png)
should be an arrow of some kind

Also, this background for the tutorial is only used here. Can you propagate the same background to all the tutorials?

**Comment by johnkslg** [comment]
Also reword this:
![image](https://user-images.githubusercontent.com/3536496/77980462-319cd000-72bc-11ea-9375-80a7df53dc96.png)
'Learning a specialty gives you bonuses, and each specialty can be leveled-up itself.'

**Comment by SlayksWood** [comment]
Arrows were fixed. Second comment is another tutorial, I will create another issue for that.
