### ISSUE TITLE
[0.9.0 staging-1494] Can't change Bandana color.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15468]
If I try to change hat color it will change my hair color,but should change bandana color.
![image](https://user-images.githubusercontent.com/45708377/78019470-6d857300-7358-11ea-9f1d-75c7ca8e6df5.png)
![image](https://user-images.githubusercontent.com/45708377/78019484-737b5400-7358-11ea-821d-3f1091859950.png)
Look wonderful, but works incorrect.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/83196697-341b7a80-a0f1-11ea-826b-8a2619a837f6.png)
![image](https://user-images.githubusercontent.com/14983165/83196709-38479800-a0f1-11ea-8584-b69f09e62705.png)
fixed in staging
