### ISSUE TITLE
[9.0 Staging 1494] Coal opens up Coal Tag not coal itself

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15464]
1. Staging 1494
2. Type coal ingame
3. Coal shows Coal tooltip and prices
4. Shows CoalTag
![image](https://user-images.githubusercontent.com/61889138/78013508-7ff2b300-733e-11ea-8aeb-5ab541e7ca9f.png)

**Comment by beastyn** [comment]
Can't reproduce.
If you type Coal you will see coal
Can you show the full screenshot?

**Comment by Xao22** [comment]
when i type something in chat and hover over it nothing hapends

**Comment by Xao22** [comment]
same as mishka coal tag appear
![2](https://user-images.githubusercontent.com/62566059/78027600-4afa5680-7366-11ea-9c52-5106a5183001.jpg)

**Comment by SlayksWood** [comment]
IDK how it works:
![image](https://user-images.githubusercontent.com/45708377/78029509-66b32c00-7369-11ea-94f0-bfc8ed1cce9a.png)

**Comment by elfl0rd** [comment]
this issue based on initialization order maybe
