### ISSUE TITLE
[0.9 Staging 1494] - "Could not find matching method FireArrow on type StonePickaxeItem taking 3 parameters."

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15465]
Updated to the newest staging version, went onto the test server, drew my bow, aimed it, then I think I changed an item to something else to cancel the shot and crashed:

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4408273/Player-prev.log)
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4408275/log.txt)

**Comment by beastyn** [comment]
Thsanks for the report.
Seems to be hapenning in the lag,

**Comment by SlayksWood** [comment]
Pretty hard to reproduce:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find matching method FireArrow on type BallotBoxItem taking 3 parameters.
Source:Eco.Shared

System.Exception: Could not find matching method FireArrow on type BallotBoxItem taking 3 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)</size>
```
[Crash with bow.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4408504/Crash.with.bow.txt)

**Comment by ThePiachu** [comment]
Yeah, probably related to lag. Was hunting for about an hour or two before I got the crash again

Large log file: https://mega.nz/#!xUo13KSS!CEwQBbywazWEy45t6Ine4bz6RiKnoSB3d764-DGdB4Y

**Comment by beastyn** [comment]
Seems to be fixed
@ThePiachu if you meet this issue in higher version, reopen,please
