### ISSUE TITLE
0.9 balance: Stove should use electricity, instead of burnable fuel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15469]
![изображение](https://user-images.githubusercontent.com/4980243/78019476-6eb6a000-7358-11ea-9132-64b3f0ecc79b.png)
As you can see there
1) electric lamp
2) electric heating spiral

But stove use burnable fuel, coal, etc.
As i think, electricity is better.
It's already available at this stage.

**Comment by Xao22** [comment]
agree

**Comment by SlayksWood** [comment]
100W is cheap, need 250W
