### ISSUE TITLE
[0.9.0 staging-1494] Cloth Cape delete my body

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15467]
![image](https://user-images.githubusercontent.com/45708377/78018922-70339880-7357-11ea-9e9c-4e202bbdeb6f.png)
![image](https://user-images.githubusercontent.com/45708377/78019197-eb954a00-7357-11ea-814c-9e841ac279d0.png)

**Comment by SlayksWood** [comment]
From discord discussion, from @MilenkoTunjic :
I am pretty sure the cape was a version of backpack
(with invisible tools)
But I can not remember any more, it was 2 years ago when I did last work on the avatars
cloth around the waist is a version of belt

So the way it should be
if I remember
if you equip the cape, it is a version of backpack, so it goes in that slot
and when wearing the cape, tools are hidden (you can still pull them from beneath the cape) but they are not visible otherwise
Also, if I remember, both of those assets were made to test cloth physics

**Comment by WeaselDog** [comment]
Cape is now assigned to back but need to double check the art.

**Comment by beastyn** [comment]
still need to hide the tools with cape

**Comment by SlayksWood** [comment]
merged to #15937
