### ISSUE TITLE
[0.9.0 staging-1489] Oil Drilling Upgrade

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15461]
Version [0.9.0 staging-1489]

Oil Drilling Upgrade require advanced upgrade4 instead of modern upgrade4

**Comment by ThePiachu** [comment]
Similarly, Smelting Upgrade requires Advanced Upgrade 4, instead of Basic Upgrade 4.

**Comment by WeaselDog** [comment]
Thanks for the feedback. This will be fixed in the next update.

**Comment by beastyn** [comment]
Smelting Upgrade works as intended
