### ISSUE TITLE
[0.9 Staging-1489] Dirst doesn't flush with Reinforced Concrete

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15463]
Recently upgraded my house into Reinforced Concrete. With previous tiers of rooms (Hewn Logs, Lumber) the dirt would flush right against it, however, it doesn't do that with Reinforced Concrete:

![image](https://user-images.githubusercontent.com/964559/78005118-f4eacc00-72ef-11ea-9c3d-a1be1543e69c.png)

It ruins the aesthetics a bit.

**Comment by MishkaFur** [comment]
Also the same for Ashlar stone, Composites seem fine.

**Comment by beastyn** [comment]
merge #14849
