### ISSUE TITLE
[0.9.0 staging-1494] No tooltip if chat window is closed

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15471]
Version [0.9.0 staging-1494]

No description or tooltip apear if you type something in chat(first close it with C)
![3](https://user-images.githubusercontent.com/62566059/78027897-cd831600-7366-11ea-96df-8dc85a2c7b79.jpg)

**Comment by SlayksWood** [comment]
dup #15418
