### ISSUE TITLE
[0.9 Staging 1494] Oak saplings don't have trunks

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15479]
I planted a few oak saplings on the test server and this is how they looked:

![image](https://user-images.githubusercontent.com/964559/78097369-fa4c2300-7390-11ea-9f79-c47d379d5ad3.png)

Seems the saplings are missing trunks for some reason.

**Comment by SlayksWood** [comment]
dup #14046
