### ISSUE TITLE
Fix active laws section on webpage

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15474]
Not showing active laws. May need updates on server side, let me know.
Use the generatetestdata commands in swagger:
![image](https://user-images.githubusercontent.com/3536496/78058530-49686880-733d-11ea-93f3-23f4ca477771.png)

Proposed laws section can be removed since those are showed in the elections now.

**Comment by denysaw** [comment]
Hm... Can't generate test data. Swagger says should be no parameters, but there's error anyway:
![image](https://user-images.githubusercontent.com/5720101/79396672-bc4c2300-7f7c-11ea-840f-029b173f33ce.png)

**Comment by denysaw** [comment]
If it's not easy solving thing with that method, could you @johnkslg provide me just Game data or World with active laws, please? Thanx ;)

**Comment by johnkslg** [comment]
Fixed, command works now in empty world.
