### ISSUE TITLE
Staging Alpha 5.6 #21f43d75 - Animal Path finding Bug

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1547]
add screen shoots show issue all animals just seem to go to highest points and hang out not moving from those locations, so to hunt all u have to do is stand close as u can get with out running them and lob areas into that point kill stuff all day. and they will always go back and just stand around at highest points not really moving from those locations.

they go up and down few tiles but not far not unless u chase them and then like i said they will just move back to those same locations and hang out.

if roof of your house happen be highest point in area they will just hang out on your roof of your house also.

![20170527030818_1](https://cloud.githubusercontent.com/assets/15990789/26523201/11383262-42d8-11e7-8173-99c003926136.jpg)
![20170527122508_1](https://cloud.githubusercontent.com/assets/15990789/26523202/1279ee54-42d8-11e7-95b1-8920fb775dc6.jpg)

**Comment by SeanAtr0n** [comment]
Mostly fixed in 5.6 and 6.0 should get rid of the last few roof animals
