### ISSUE TITLE
[0.9.0 staging-1494] Transmission Pole 

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15489]
Version [0.9.0 staging-1494]

Transmission pole is twice the price of wind turbine which is way to expensive

**Comment by SlayksWood** [comment]
it should cost like street lamp

**Comment by WeaselDog** [comment]
I agree about cost being similar to Street Lamp. Instead of Glass & Lightbulb it should cost Lumber
