### ISSUE TITLE
0.9-1495 balance: wood pulp filler - too few wood pulp

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15487]
As i see, this problem appers after removing wood pulp from lumber processing.
maybe we can add wood pulp to hewn log processing?

**Comment by SlayksWood** [comment]
disagree, but we should change pulp filler recipe like fiber filler:
![image](https://user-images.githubusercontent.com/45708377/78134435-d2a89980-7428-11ea-9ef3-633c317cb4fd.png)

**Comment by SlayksWood** [comment]
also check a few seems worng recipe in Farmers table:
![image](https://user-images.githubusercontent.com/45708377/78134622-1dc2ac80-7429-11ea-8f36-9a7bf3e6048d.png)
They was not changed from 8.3

**Comment by elfl0rd** [comment]
> disagree, but we should change pulp filler recipe like fiber filler:

Anyway, now the only way to get wood pulp is to cut the trees as bad as possible, that's wrong.

**Comment by elfl0rd** [comment]
Or another option, wood pulp as a result of shrub gathering.

**Comment by WeaselDog** [comment]
Hey all. After review we will keep most things the same. We can lower the price of Pulp Filler.
The seed costs are intentional as the higher costs are from plants that can be re-harvested.

**Comment by SlayksWood** [comment]
pulp filler = 1 Dirt, 15 Wood pulp
