### ISSUE TITLE
[0.9 Staging 1494] 3d person view has wrong Steel pickaxe model

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15482]
Steel pickaxe looks like  stone pickaxe
![bandicam 2020-04-01 14-22-34-890](https://user-images.githubusercontent.com/27898520/78122516-4d23ea00-7426-11ea-9e52-79d4e641b5fb.jpg)

**Comment by keegan-o** [comment]
fixed in staging
