### ISSUE TITLE
0.9-1495 damage bonus from hunter profession is not work for recurved and modern bows

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15484]

**Comment by SlayksWood** [comment]
without Hunting:
![image](https://user-images.githubusercontent.com/45708377/78130463-0502c880-7422-11ea-8a8c-1151da277cf4.png)
![image](https://user-images.githubusercontent.com/45708377/78130478-0af8a980-7422-11ea-979d-dbde38601efb.png)
with Hunting 7:
![image](https://user-images.githubusercontent.com/45708377/78130539-282d7800-7422-11ea-93a2-6b70fcce81d7.png)
![image](https://user-images.githubusercontent.com/45708377/78130549-2d8ac280-7422-11ea-87a1-ba6676387a64.png)
Damage with Deadeye talent, Hunting 7 and Modern bow:
![image](https://user-images.githubusercontent.com/45708377/78130598-45624680-7422-11ea-8d8a-743e9b449458.png)
All works fine for me.
Any steps?

**Comment by elfl0rd** [comment]
verified files and now all fine, maybe my bad :)
