### ISSUE TITLE
[0.9 Staging 1494] Web server has two Capacity variables for each animal

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15481]
When browsing map layers, you can see things like "TortoiseCapacity" and "Tortoise Capacity" as separate entries. It seems only one of them displays data though:

![image](https://user-images.githubusercontent.com/964559/78118499-f1bd1200-73bb-11ea-933b-9dd92c1e3ec1.png)

**Comment by gzatravkin** [comment]
Looks be fixed
