### ISSUE TITLE
Staging Alpha 5.6 #21f43d75 - Doorways Bug or issue ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1548]
doorways with out doors no longer separate rooms  -
doorways with out doors do not always count as a closed off room. - i have to sometimes put a block in place to shut room tight and then remove it. when i want access out.  - same applys for multiple rooms inside house.

picture below of doorway example dos n0t always work as a doorway wont work to separate rooms

![20170527125844_1](https://cloud.githubusercontent.com/assets/15990789/26523396/47a1a898-42dc-11e7-8fef-37836e6e48f9.jpg)

my current fix is use log as door

![20170527125856_1](https://cloud.githubusercontent.com/assets/15990789/26523401/698b2042-42dc-11e7-9fa3-66fbf6b73b5e.jpg)

**Comment by midn8t** [comment]
Update to this if you put a door on like in pic below that does not always count as a closed room ether.

![20170527164905_1](https://cloud.githubusercontent.com/assets/15990789/26524562/7e61cc76-42fc-11e7-9a8d-28419ef4b078.jpg)

**Comment by MarjieAVolk** [comment]
@craig-jong, I assume this is fixed now?
