### ISSUE TITLE
[0.9.0 staging-1494] Waste filter - Compost

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15490]
Version [0.9.0 staging-1494]

Waste filter doesn't produce enough compost,you get 1 every 10 hours of continue smelting or so

**Comment by SlayksWood** [comment]
5% for 500 Iron bar 
![image](https://user-images.githubusercontent.com/45708377/78243501-8cb50980-74ec-11ea-9957-798c0dc4d82e.png)
