### ISSUE TITLE
Staging Alpha 5.6 #21f43d75 - stock piles issue not really bug

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1549]
stock piles have to be redonklessly close to tables and buildings that there being connected to pretty much right on top of them.

in screen shoot below if i move any of those craft tables to any other wall in house it loses connection to stock pile out side - that means i would have to make stock pile inside the house to get use of whole house.

![20170527125447_1](https://cloud.githubusercontent.com/assets/15990789/26523373/e51be3a0-42db-11e7-8b3d-1f72a0b7a13e.jpg)

the stock pile is eye sore be nice if i could move it way away form my house.  instead of it having be right next to wall that the craft tables are on...

**Comment by sr3ka** [comment]
Agreed. If you line the stockpile adjacent to your building and begin adding things to the stockpile the blocks of said building will change. Kind of an aesthetic problem.

**Comment by Uniphix** [comment]
Something to keep in mind, and I can be corrected.  From the actual code, tables can reach into Stockpiles up to 8 tiles away (interesting fact, it used to be 25 but I think that was for testing)  I don't know if I like that idea of it being that small now, because the idea would be to have "Stockpile Buildings" and now with it being that small you cannot have that.  Whereas for Chests, and other tables I believe that is only up to 5 tiles away.

**Comment by sr3ka** [comment]
25 sure would be nice for, as you say "Stockpile Buildings." I would definitely implement that into my gameplay. Both those numbers still seem slightly small. Although, I guess we'll see when 5.6 is released.

**Comment by sr3ka** [comment]
That being said, any idea if stores will have a larger stock option because of the linked inventories? That would be cool, because the current stock slots don't seem like enough.

**Comment by midn8t** [comment]
well its a game play issue also,. if those tables are moved to other wall ahll way just one box away they stop link with the stock pile.

**Comment by midn8t** [comment]
I re read what i wrote and looked at it and thought of it, as a game player more i like idea of stock piles just being used as a place to storage large amounts of certain resources like a wood stock pile  a lumber stock pile so forth near where those thing happen, then be able to take those resources as need to cargo storage large containers that can be placed inside and outside for tables to use. 

so like more storage type like chest are small a medium and a large and maybe a huge then stock piles as not really a linked inventory item but as a dumping ground area for resources u dig up...

**Comment by Uniphix** [comment]
I think tables should be able to access stockpiles from at least a good distance (25 seemed very reasonable, that would allow you to have quite a bit of stockpiles in an area next to each other in a building like concept).  Whereas stockpiles CANNOT reach into tables and should be shorter distance.

This is what I think would be better.

Tables to Stockpile (at least 25)
Stockpile to Tables (8 seemed reasonable)
Tables to Tables (8 seemed reasonable)

**Comment by Uniphix** [comment]
If you have to create a room volume of 45 let's say that means some tables might have a hard time touching these stockpiles.  Stockpiles are also already 5x5x5.  I am not sure if the link is directed to the center of that stockpile or if it is based on the end of the stockpile edge.  If it is from the center of the stockpile then well that means 2 tiles, + 1 tile of space + another for the wall, then another for the table, well if you look at that it means about 4-5 tiles, if you have a table on the other side of a room that is 45 volume side, that means it won't touch that stockpile as it'll be greater than 8 tiles.  Just my thoughts

**Comment by metachronism** [comment]
craig, take a pass at linked distances - they are probably too short right now
