### ISSUE TITLE
Meteor Show Occured the moment CreateMeteor changed to true

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15497]
**version** 0.8.2.9 beta (the latest I can actually sign into)
**OS:** Windows 10 Professional 64-bit

In a server I am testing, I created it initially with disasters.eco :

```
{
  "CreateMeteor": false,
  "MeteorImpactDays": 120.0
}
```

And after making sure it was stable, I changed from false to true and then reloaded it with the pause.eco setting:

{
  "Paused": true,
  "UnpauseAtFirstLogin": true
}

So that the server would not resume until I actually logged in. Then, Immediately after logging again, I saw an explosion immediately overhead followed by a meteor shower! No meteor though. I investigated impact sites, and the meteors were destroying entire areas of trees rapidly.

I quickly signed out, shut down the server, retested from a backup (again, manually making sure that pause was set to true which I wish was a default always on setting when starting the server) and... No meteor shower. The meteor was in the sky though. 

I don't know why restoring the backup fixed it. Maybe there's a random bug that can occasionally cause the meteor to impact early? I know in much older versions of the game I encountered an early meteor impact before.

**Steps to reproduce:**

To be clear, the meteor was never generated at the start of the world. It was simply changed from false to true. So you'd generate a server, login to it, log out, shut down the server, then turn on the meteor by changing false to try and then sign in.

Restoring from a backup made prior to changing the configuration files, but leaving the configuration files intact appeared to have fixed it, but I don't know why.

I'd have tested this on later versions of Eco before reporting, but unfortunately this is the latest version I can actually play on due to another bug.

**Comment by beastyn** [comment]
Thank you for the report, we will investigate it

**Comment by SlayksWood** [comment]
Can't reproduce anymore, we  improved meteor timer https://github.com/StrangeLoopGames/Eco/pull/8652, so if we had bug it was fixed. In any case behavior was changed. So if we still have any bug with meteor impact the reason will be another.
closed for now.
