### ISSUE TITLE
[0.9.0 Staging-1494] Unable to build ramps underwater

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15499]
today my car fell off a bridge and into the water. It was full of stuff and I didn't want to unload and reload it. Luckily, I was close to the shore, so I figured I'd try building some ramps. Unfortunately, you can't build ramps underwater, so I wasn't able to get my truck out this way:

![image](https://user-images.githubusercontent.com/964559/78213995-fd1a4700-7468-11ea-92fe-df3b9e4f30a2.png)

It would be nice if you were able to add those in for just such an occasion...

**Comment by beastyn** [comment]
Its intended for now. Have some in the Suggestions
https://github.com/StrangeLoopGames/EcoSuggestions/issues/196
