### ISSUE TITLE
[0.9.0 staging-1494] Shovel and cart bug

### ISSUE THREAD

**Issue by XDMounir** [StrangeLoopGames/EcoIssues#15496]
1. Version
0.9.0 staging-1494
2. Steps to reproduce.
Full a wood cart of dirt, right click on wood cart while holding dirt and selecting shovel.
3. Expected behavior.
Warning saying cart is full and still holding shovel.
4. Actual behavior.
Dropping the shovel in the cart and still holding dirt.

**Comment by SlayksWood** [comment]
dup #14911
