### ISSUE TITLE
[0.9.0 Staging - 1494] Turning Master Volume slider to 0 does not disable all sound

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15492]
**Steps to reproduce:** Turn down master volume slider to 0
**Expected behavior:** stops all volume and sound
**Actual behavior:** doesn't seem to stop any sound whatsoever, seemed to have no effect on sound at all.

**Comment by SlayksWood** [comment]
Need to check after fixes #15272 and #15373
