### ISSUE TITLE
USER ISSUE: Ahmet

### ISSUE THREAD

**Issue by aha-sys** [StrangeLoopGames/EcoIssues#15494]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Invalid username or password.
```

**Comment by elfl0rd** [comment]
use license copy.
