### ISSUE TITLE
[0.9.0 Staging-1494] Work parties / labour needs its own dedicated UI

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15500]
I tried doing the work party today, and the experience was a bit bad.

First of all, when I went to the job board, I missed the tiny button for applying for a job in it. It's tiny and doesn't draw attention to itself. So I thought I had to go to the destination to do the work, but then I was unauthorised to do anything. A quick jog back I managed to sign up and I got a big pointer to where I was supposed to go - good start. However, when I got there, by instinct I started pressing "E" to interact with the machine, which I was unauthorised to do (understandably). It took us a minute to figure out what was wrong with this mess:

![image](https://user-images.githubusercontent.com/964559/78214925-3784e380-746b-11ea-89d4-31b5087be15b.png)

The screen clutter is from a work party working as intended, which is not great. Ideally, you'd use the machine the same way you'd interact with other machines ("e"), or have a better UI that doesn't overlap with other messages. In general, having a dedicated screen for it would be nice. Maybe that screen would also let you sign up for the work party from the machine itself in case you missed the signup on the job board.

**Comment by SlayksWood** [comment]
Sometimes it could happen, And if you create more than 1 it will happen more:
![image](https://user-images.githubusercontent.com/45708377/78239130-07c6f180-74e6-11ea-867b-60cd3e0ce143.png)
![image](https://user-images.githubusercontent.com/45708377/78239173-10b7c300-74e6-11ea-9843-d08879bb0820.png)
Need complex fix with # 15076
