### ISSUE TITLE
Unable to update Ecopedia entries

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15502]
After latest localization updates I am unable to implement any edits to Ecopedia. In addition, the summary for pages is included at the bottom of the entry.

![EcopediaEntry](https://user-images.githubusercontent.com/47330823/78215842-600ddd00-746d-11ea-978b-076a4f7a5ba0.png)

**Comment by Quadbro** [comment]
yeah, my bad, it was translating even "en" locale

**Comment by WeaselDog** [comment]
Nice looks good.
