### ISSUE TITLE
Staging Alpha 5.6 #21f43d75 - Carts and Ramp Bug are some what back again.

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1550]
so issue is this

you can build a cart before you can build roads, and u can build dirt ramp before you can build roads now problem that this causes is shown in picture below  - the landscape does not from up to the ramps properly and the carts get stuck and bug out when trying to cross between landscape and the ramp.

![20170527221717_1](https://cloud.githubusercontent.com/assets/15990789/26525873/891dc484-432a-11e7-9917-babb413c8b96.jpg)

**Comment by MGrand3** [comment]
Not an issue with ramps specifically, this is an issue with blocks of one type not connecting to blocks of a different type. Very much a known issue and something they've loosely said that they want to fix in the future.

**Comment by MarjieAVolk** [comment]
This has been bothering me a lot more in the most recent builds though too - has anything changed?

**Comment by SeanAtr0n** [comment]
Ideally the terrain should be fixed somehow (reassigning), in the meantime I made small wood cart tolerate even more ridiculous terrain gaps.

**Comment by keegan-o** [comment]
Added beta milestone as this will be part of landscape polish.

**Comment by keegan-o** [comment]
This issue has been here since May of last year and hasn't prevented any builds going out, and in all my play-testing it has never been cause for that much frustration. It is absolutely an issue to solve with refinement of roads and I will gladly keep in on my list, but shouldn't be high priority for 6.4

**Comment by MarjieAVolk** [comment]
That is true that it hasn't blocked any released before.  However it is probably one of my biggest pain points in the game, so IMO it's a high medium

**Comment by keegan-o** [comment]
With new ramps and roads this is mostly fixed.
