### ISSUE TITLE
Pollution output should display before polluting

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15507]

**Comment by WeaselDog** [comment]
To get it to appear you must first pollute with the vehicle:
![VehiclePollution](https://user-images.githubusercontent.com/47330823/78308245-d73e8200-74fc-11ea-870c-d1b6baadba16.png)

I have an old suggestion we should look into implementing: https://github.com/StrangeLoopGames/EcoSuggestions/issues/950

Either way it should show the pollution status before polluting so will look into fixing this.

**Comment by elfl0rd** [comment]
> To get it to appear you must first pollute with the vehicle:

Huh, no - i have steam truck without this info for a days.

**Comment by WeaselDog** [comment]
I am able to get it to appear. Is this a picture after restarting the server or it won't appear at all?

**Comment by elfl0rd** [comment]
restarting, driving, etc - not appear.
staging-1496

**Comment by elfl0rd** [comment]
appear at steam truck in 1499 but steam tractor still empty
https://youtu.be/FPTdExJZzOc

**Comment by WeaselDog** [comment]
Thanks for the video!

Will look at issue with vehicle pollution display not appearing and crafting pollution issue at same time.

**Comment by mirasrael** [comment]
Steam tractor doesn't have Air Pollution. @WeaselDog can you add some reasonable to this?

**Comment by mirasrael** [comment]
Pollution now always show now matter if you use or not vehicle or table.
