### ISSUE TITLE
Election does not work if a player with a single quote in a nickname has voted.

### ISSUE THREAD

**Issue by KirillAshikhmin** [StrangeLoopGames/EcoIssues#15517]
js console output:
`Error: Syntax error, unrecognized expression: .current-rankings table tr[data-voter='Mrs.Pron'ka'] td`
Place: Election.js:1009
Code line: `$(".current-rankings table tr[data-voter='" + data[i].Voter + "'] td").each(function(){`

Need escape quotesymbol in player nickname.

Screenshot: https://i.imgur.com/NZNN5au.png

Eco version: 8.3.3

**Comment by SlayksWood** [comment]
merged to #14132
