### ISSUE TITLE
Staging Alpha 5.6 #21f43d75 - crafting tables and rooms not working right

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1551]
so - besides door ways not separating  rooms any more the total number of crafting tables being reported is wrong half time

this pic shows a count of 5 crafting tables in that room when there is only a research table and one other table

![20170529111537_1](https://cloud.githubusercontent.com/assets/15990789/26556483/5cf6af1a-4460-11e7-9d85-0ff1b093cf58.jpg)

**Comment by MarjieAVolk** [comment]
This issue is now being tracked in StrangeLoopGames/EcoIssues#1562
