### ISSUE TITLE
[0.9.0 staging-1494] Difficulty leveling up Industry

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15511]
Version [0.9.0 staging-1494]

Industry is 2 times slower to level then Electronics,too many mechanics recipes in electric machinist table

**Comment by SlayksWood** [comment]
Can your provide more detailed information like certain recipe has many or a little experience, second recipe is imbalance and etc.

**Comment by Xao22** [comment]
the sp is not the problem,there are to few recipes that you can lvl it,for exemple at robotics assembly only vehicles give xp and refrigerator, washingmachine the rest require high lvl or they are electronics.To sum it up you can only lvl it with trucks and stamping press products,washing machine and refrigerator are ultra expensive at the begining.The  problem is that too many recipes at E machinist are mechanics,some of them makes no sense like wires

**Comment by WeaselDog** [comment]
Thanks for the detailed information Xao! We will look into this more.
