### ISSUE TITLE
[0.9.0 Staging - 1494] Eco using a massive amount of RAM

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15516]
apologies for not using the proper requested format here but I have noticed that ECO is consistently using 70-80, even bumping into 90-95% of the RAM on my system which it definitely should not be doing.

More graphics intensive games are running at lower RAM usage on my rig.

Attaching my system specs for you here.
[System Specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4423764/System.Specs.txt)

I average 250-300 FPS on much more graphics intensive games than ECO, often got better FPS than the 60-70 I average on the test builds (I know there is optimization being done, but I figure these things will help you guys)

**Comment by Xao22** [comment]
I cant get above 52 fps no matter settings i use,game eats 8-10gb,the more you travel the higher it gets
System spec rx580 8gb,ryzen 5 1400 3.2 baseclock 3.7 oc,12 gb of ram 2133 base 2666 oc ,windows 10

**Comment by Xao22** [comment]
if you alt tab the game and open chrome the game is unplayable after that lots and lots of shuttering

**Comment by Daelmaron** [comment]
Additionally, after I have been in game for about 65-70 minutes my game starts stuttering and becomes completely unplayable until I force close it using task manager and begin with a fresh instance, then it is good for about 65-70 minutes until I have to repeat the process.

**Comment by SlayksWood** [comment]
This problem appeared with a bigger effect with a broken minimap #15314. Freeze, lags, increased RAM consumption (almost in 1,5 times). Seems all happened when minimap was broken.

**Comment by mirasrael** [comment]
Eco still uses noticeable amount of RAM, but original issue should be fixed. Also hopefully memory leaks also mostly fixed.

**Comment by SlayksWood** [comment]
Closed for now in 0.9.0. We can return to this question with specific conditions if they appear.
