### ISSUE TITLE
Eco tree feature colors arent distinguishable

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15518]
![image](https://user-images.githubusercontent.com/3536496/78303893-78740b00-74f2-11ea-85d8-02d1a14d1ba0.png)
- Make a more distinguishable palette, either with fewer gradations or different colors for each step. You should be able to see that what the feature status is just by looking at it.
- Make the key a little more explicit, giving labels for each gradation. We can do:
'Not started, foundations, partially implemented, implemented, feature complete, polished'
These could be tooltips that show up when you mouse over the key, or just add text in the key.
- The in-progress highlight is too subtle, make it easier to pick out (its a special one to see that and should draw the eye a bit more)

**Comment by rainfarmer** [comment]
complete
