### ISSUE TITLE
[0.9.0 Staging-1494] Double "Take X from (Steam) Truck" message

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15510]
I had one item on my Steam Truck. I climbed onto it and looked down and got a prompt to "Take Blast Furnace From Steam Truck", twice:

![image](https://user-images.githubusercontent.com/964559/78241649-995a4300-7495-11ea-9e28-a30dfdab0e07.png)

**Comment by SlayksWood** [comment]
dup #15051
