### ISSUE TITLE
Workbanch UI improve for Labor

### ISSUE THREAD

**Issue by KirillAshikhmin** [StrangeLoopGames/EcoIssues#15519]
I suggest moving the item with the work required for crafting to the end of the list of resources.
This will make the interface cleaner. It will also work as an anchor and the user will immediately know where to look for the number of calories required.
Original: https://i.imgur.com/8fqrOTs.png
How should be: https://i.imgur.com/sipevzd.png

**Comment by SlayksWood** [comment]
merged to #13334
