### ISSUE TITLE
[0.9.0 Staging - 1494] Closing map locks up the game.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15515]
**Steps to reproduce:** Open and Close map
**Expected behavior:** the map opens, I look around for what I need, the map closes without issue
**Actual behavior:** the game stutters and locks up for a long minute, occasionally I have to force it to close because it stops responding.
**Logs:**
I don't have screenshots or logs at this time, will submit as I collect them

**Comment by Sarah-Graesyn** [comment]
![lockup bmp](https://user-images.githubusercontent.com/1329717/78325625-c5310380-753d-11ea-9d77-b5688dc355fa.png)
caught the screenshot of it fully

**Comment by SlayksWood** [comment]
dup #15314
