### ISSUE TITLE
[0.9.0 staging-1494] Wet Taillings

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15512]
Version [0.9.0 staging-1494]

Tailing and wet tailing can be contained in wood cart with 0 pollution,i didn't test the other vehicles

**Comment by SlayksWood** [comment]
All vehicle give me ground polution:
![image](https://user-images.githubusercontent.com/45708377/78243700-e1f11b00-74ec-11ea-8c04-dd969e5dc35c.png)

**Comment by SlayksWood** [comment]
@Xao22 Can you provide any additional information?

**Comment by mirasrael** [comment]
Please take into account that world layers update may take up to 10 minutes.

**Comment by Xao22** [comment]
i left them in a cart over night

**Comment by Xao22** [comment]
i will test further and come back with results later

**Comment by SlayksWood** [comment]
It seems that tailings don't have problem, but Wet tailings don't give any pollution in vehicles. And it less polute as Tailings.
@Sekor2600 can you check it?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/78249004-4c5a8900-74f6-11ea-9514-185908edc79f.png)

**Comment by SlayksWood** [comment]
After several days:
![image](https://user-images.githubusercontent.com/45708377/78250238-3b127c00-74f8-11ea-8dc4-5d289ee5cf45.png)

**Comment by Xao22** [comment]
Wet taillings dont polute in a wood cart didn't test the rest,if you have half dry and half wet in a cart polution exist i think cause of the dry

**Comment by mirasrael** [comment]
Tailings was hardcoded for vehicles. Fixed. It now creates pollution for all block items which has PolluteGround (Garbage, Tailings and Wet Tailings) and also uses Amount from attribute.

**Comment by Daelmaron** [comment]
so... they definitely give me pollution... horrible amounts of it. 
![20200402184212_1](https://user-images.githubusercontent.com/1329717/78309816-ae74b780-7511-11ea-9048-0e2835f987d4.jpg)

temporarily storing tailings in wood carts while I rearrange storage for them on Royal Otter. the area around my mine is radioactive me thinks
