### ISSUE TITLE
[0.9.0 Staging - 1494] Active Demographic Bugged: Demographics, Government, Titles

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15526]
**Steps to reproduce:** Set up a title to require the active demographic
**Expected behavior:** active player is elected to title, maintains title until voted out or becomes inactive.
**Actual behavior:** I won election for the title of Executive Infrastructure Director on Royal Otter Playtest Server and then less than 12 hours later (while maintaining active status) I was removed for not being active while having just been online within the last 12 hours for several hours straight
**Providing Log files:**
![20200402230814_1](https://user-images.githubusercontent.com/1329717/78323417-623c6e00-7537-11ea-85b7-40708ca3887e.jpg)
![election bmp](https://user-images.githubusercontent.com/1329717/78323561-d414b780-7537-11ea-9bf9-9531d2d9217a.png)
![20200402231800_1](https://user-images.githubusercontent.com/1329717/78323732-5604e080-7538-11ea-810c-3906e504aded.jpg)

**Comment by Daelmaron** [comment]
![20200402231800_1](https://user-images.githubusercontent.com/1329717/78323769-7df44400-7538-11ea-95f7-7b5317a15fe0.jpg)

**Comment by Daelmaron** [comment]
as you can see in the screenshots above, I quite clearly qualify for being active with 27.64 hours online in the last 2 days, my in game name is Sarah Graesyn

**Comment by Sarah-Graesyn** [comment]
![20200404053005_1](https://user-images.githubusercontent.com/1329717/78424841-a746ca00-7635-11ea-9817-e19936611bec.jpg)
![20200404053025_1](https://user-images.githubusercontent.com/1329717/78424842-a7df6080-7635-11ea-8e47-367bccb9f2af.jpg)

Have done another election to see if it was just a fluke, it was not. 

Election ran, won the election, it almost immediately booted me out of the position despite me having the active demographic.

**Comment by Sarah-Graesyn** [comment]
**on a side note:** due to the laws that we set up on Royal Otter this is preventing people from functioning properly.

**Comment by Sarah-Graesyn** [comment]
![20200404083856_1](https://user-images.githubusercontent.com/1329717/78452252-e3872400-764f-11ea-831b-4ae3a2afe747.jpg)

not just the one title, looks like its every title that requires the active demographics

**Comment by Sarah-Graesyn** [comment]
![20200405170511_1](https://user-images.githubusercontent.com/1329717/78511172-4c5dc180-7760-11ea-9b12-494046746ff5.jpg)
![20200405170530_1](https://user-images.githubusercontent.com/1329717/78511175-4cf65800-7760-11ea-9a72-a007fa170fef.jpg)
![20200405170541_1](https://user-images.githubusercontent.com/1329717/78511176-4d8eee80-7760-11ea-8ea3-c0c54411d655.jpg)
![20200405170547_1](https://user-images.githubusercontent.com/1329717/78511178-4d8eee80-7760-11ea-92a2-8148e9090221.jpg)


Active Demographic also seems to be affecting other demographics that rely on it. 

On a side note, the action count thing doesn't seem to be actually counting actions at all, all of the people that are in the screenshots above are active currently and have been manually mining nonstop for the last 24-30 hours in sprints of 2-3 hours at a time and yet the mining count is showing at 0 blocks mined.

**Comment by Sarah-Graesyn** [comment]
We also just had a player become active randomly with no login notification and who was not registering as online in the objectives window and then about 5-10 minutes after the screenshotted notification of them becoming active they were suddenly online with no notification of a login.

![20200405182300_1](https://user-images.githubusercontent.com/1329717/78512532-fb06ff80-776a-11ea-9dec-46e7946c5fd2.jpg)

**Comment by johnkslg** [comment]
Did some digging, couldn't repro this but found what may be a cause.  
The demographic's cached list of users was clearing then setting in two steps (non atomically).  Another thread could check status during that time and get empty for a split second.  This was reflected in the fact that nowhere in chat did sarah become 'no longer a member of active'.  Fixed this assignment to be atomic.
 
Also noticed a strange issue, throughout the chat log there was a record 'Active is now valid'.  It should never go invalid, and there were no notices about it going invalid. Probably related to this race condition, but added more info about why it was previously invalid if this does occur again.  If you see that let me know.

**Comment by johnkslg** [comment]
Made a separate issue for stat counts not working.
