### ISSUE TITLE
[0.9.0 Staging-1494] Can't easily drag and drop items into Vehicles with Fuel inventory

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15525]
For most inventories, you can drag and drop items into the background space of it and it will sort everything out - very useful! However, when I open up the Steam Truck and drop items into the background, nothing happens:

![image](https://user-images.githubusercontent.com/964559/78317306-cac72300-7516-11ea-8d8a-0f1dc6a20934.png)

At the same time I can open up another inventory and drop items into the Steam Truck's inventory just fine that way.

Steps to reproduce:
1) Park Steam Truck next to a Stockpile filled with stuff
2) Open Steam Truck's storage, drag items from Stockpile and drop them in the inventory's background - nothing happens.
3) Open Stockpile's inventory, drag items from the Stockpile and drop them in the Steam Truck's inventory, items transfer properly.

**Comment by SlayksWood** [comment]
It happens because it tries to put this items in Fuel storage, so it happens for all vehicles with fuel.

**Comment by Quadbro** [comment]
most items have one inventory, when you have fuel component - it has higher priority. So if you want to move items - drag mouse to needed inventory at least
