### ISSUE TITLE
Stockpiles are hard to place

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1552]
When placing stockpiles in the grass for example, it's very hard to see the green outline of it, with both the color and the grass physically blocking it.  It would be nice if the outline thing were taller, i.e. showing the maximum height of the stockpile.

Also it seems if I place the stockpile intersecting my character, it will say that the stockpile is blocked, which is confusing.

**Comment by craig-jong** [comment]
To add to this, there appears to be some sort of rotation thing where rotating a stockpile in place will let me place it sometimes... which shouldn't be the case. Might have to test this more to confirm.

**Comment by knexer** [comment]
I've been unable to place a stockpile even when the space is clear of both voxels and my avatar.

I've also been able to place a stockpile in a space that was not clear of voxels, and they were replaced with the stockpile.

**Comment by craig-jong** [comment]
I'm going to look into this.

**Comment by craig-jong** [comment]
Alright, this is because all occupancy is defined from the placement point and, for most objects, this is a corner. But for the stockpile its the center so the occupancy is offset and is very, very incorrect.

**Comment by craig-jong** [comment]
feeexed
