### ISSUE TITLE
[0.9.0 Staging-1494] Powered Cart, Steam Truck lack a back plate

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15521]
Most vehicles in the game have a back plate you can customise - it's a fun way to show off. However, the Powered Cart and the Steam Truck lack these:

![image](https://user-images.githubusercontent.com/964559/78304572-e240e480-74f3-11ea-82c2-c38395de9af8.png)

It would be nice if they had them, given that they might be what a lot of people will be using through a good chunk of the game. If you can have those on Wood Carts and the small Wood Carts, the mid-tier vehicles should also have them.

**Comment by Daelmaron** [comment]
pretty sure you can input text for the steam truck, never tried for the powered cart.

Visually having some sort of plate on the back would be nice though...

**Comment by elfl0rd** [comment]
you can
![изображение](https://user-images.githubusercontent.com/4980243/78305715-4a221a00-754a-11ea-86ba-b97ae82bca1b.png)

**Comment by SlayksWood** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/45708377/78327634-01885200-7586-11ea-9f32-3a167fab367e.png)
DOn't need to start new issue for powered cart text, we already have it #5602
Closed.
