### ISSUE TITLE
[0.9.0 Staging-1494] Steel Pickaxe looks like a Rock Pickaxe in third person mode

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15524]
First person:

![image](https://user-images.githubusercontent.com/964559/78316409-715df480-7514-11ea-9a65-6a636be5d36f.png)

Third person:

![image](https://user-images.githubusercontent.com/964559/78316434-80dd3d80-7514-11ea-9d50-08cc3a08bfe0.png)

Doesn't seem to affect other tools from what I can see, just this one.

**Comment by SlayksWood** [comment]
dup #15482
