### ISSUE TITLE
[0.9.0 Staging - 1494] Re-examine costs of Modern Drill

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15523]
_not following format because its not something that I can necessarily reproduce easily._

On Royal Otter someone was looking at the Modern Rock Drill which shows that I can craft it as a Advanced Smelting level 6, however it requires the use of an Assembly Line **{not advanced smelting}** and steel gears and a combustion engine **{not advanced smelting}**

either the tooltip is wrong or this recipe is grossly incorrect and needs to be adjusted.
![20200402210326_1](https://user-images.githubusercontent.com/1329717/78316643-ca825400-7525-11ea-9e3b-cec5985b2d76.jpg)

**Comment by WeaselDog** [comment]
Thanks for the feedback. All modern tools are made on an assembly line and it is common for specialties to require ingredients from other specialties. We can take another look at the costs but there is not a bug with the tooltip.

**Comment by Sarah-Graesyn** [comment]
@WeaselDog issue I was pointing out is that it says it is made on the assembly line which is correct but that it only requires advanced smelting which I think doesn't sound right because advanced smelting should have zero reason to touch an assembly line as its not a machine that we should use for anything else, especially since advanced smelting does not use gearboxes and the like for anything else nor can they make it themselves without specializing into... I think its mechanics

**Comment by SlayksWood** [comment]
We can think about changing Chainsaw and Modern rock drill to Industry 1. And increase this exp too. So it'll first items for Industry.

**Comment by WeaselDog** [comment]
We have made some changes to costs so I am going to lower in priority, but this is something we are continuing to look at.

**Comment by ThePiachu** [comment]
It would be nice to make that drill available a bit early on. As it stands that one single gear makes you need to create the whole industry setup just to get to that one item that produces these.

**Comment by Sarah-Graesyn** [comment]
There is a drill available early on.
