### ISSUE TITLE
UI logic broken in crafting with tags

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15520]
after fix - https://github.com/StrangeLoopGames/EcoIssues/issues/13954

> One way to do this, we can make it always take static ingredients before it takes tagged ingredients. This will solve the above issue

But in the logic of the whole other game, the ingredients are filled from left to right.
I think the "tag" ingredients should be last.

@mirasrael @WeaselDog

**Comment by SlayksWood** [comment]
more important that when you add items first will take non-tagged resources. FOr example:
- start tailoring skill book:
![image](https://user-images.githubusercontent.com/45708377/78346241-6d2ee700-75a7-11ea-8997-34e0160cf772.png)
- try to add Gathering research paper basic:
![image](https://user-images.githubusercontent.com/45708377/78346267-7a4bd600-75a7-11ea-9a5f-ce9391419c0d.png)
- it go to Gathering research paper basic:
![image](https://user-images.githubusercontent.com/45708377/78346324-92235a00-75a7-11ea-96b4-619d1d69e5c0.png)

So merged to #13334
