### ISSUE TITLE
[0.9.0 Staging-1494] Can't break down payments / weights per-item in work party

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15538]
Currently there is no way to break down payments / weights in a work party on a per-item basis.

So for example when I'm making Basic Upgrade 3, it requires 80 natural fibers and 20 beards. If I pay $100 for the materials, I'm guessing the work party will pay $1 for a natural fiber and $1 for a board. Those two are not worth the same, and yet there is no way to balance this out, other than for one person to supply everything.

Additionally, if I have some items myself, there is no way to add those in automatically and reduce what the work party requires - I'd have to create the work party and then add those items in to pay myself afterwards.

Also, if I want to chain some work parties together (say, Basic Upgrades 1->4), I'm guessing I might have to be present to move the items between them. The only way around this would be to have a store right next to it and let people buy the modules to put into the work party as they come off the assembly line. Not an ideal solution.

I'm still testing some of these things, so I might have a few details off...

**Comment by SlayksWood** [comment]
@johnkslg 
Maybe we need to add it in next update?
> Currently there is no way to break down payments / weights in a work party on a per-item basis.
> 
> So for example when I'm making Basic Upgrade 3, it requires 80 natural fibers and 20 beards. If I pay $100 for the materials, I'm guessing the work party will pay $1 for a natural fiber and $1 for a board. Those two are not worth the same, and yet there is no way to balance this out, other than for one person to supply everything.

You can add resouces before start work party. I create separate issue #15576 for that :
> Additionally, if I have some items myself, there is no way to add those in automatically and reduce what the work party requires - I'd have to create the work party and then add those items in to pay myself afterwards.

**Comment by SlayksWood** [comment]
> Also, if I want to chain some work parties together (say, Basic Upgrades 1->4), I'm guessing I might have to be present to move the items between them. The only way around this would be to have a store right next to it and let people buy the modules to put into the work party as they come off the assembly line. Not an ideal solution.

Don't full understand this. I haven't this problem
Create 1 workparty for 1,2,3 level modules. Another player add all Labor and Resourses (without Basic module 1 and Basic module 2):
![image](https://user-images.githubusercontent.com/45708377/78559073-6c52bb00-781c-11ea-8a3e-d8b5691eeebc.png)
So if my Masonry table and Carpentry table link in one stockpile than I my orders will finish successful:
![image](https://user-images.githubusercontent.com/45708377/78559148-8b514d00-781c-11ea-92d2-fad8b5926a1f.png)
Yea, Beastyn lost some money:
![image](https://user-images.githubusercontent.com/45708377/78559457-15011a80-781d-11ea-96ca-0ed7c7bcb77f.png)
But if we change your first suggestion than I should delete this modules from craft.

**Comment by SlayksWood** [comment]
@johnkslg 
Can you look at this?

**Comment by johnkslg** [comment]
- Weighting per item: good idea, lets do it for post 9 though.
- Adding own objects: should be covered by #15576
- Chaining together, seems like it works as Kirill describes, let us know if thats not what youre thinking @ThePiachu 

@SlayksWood can you break this into separate issues and push the item-weights to 9.1?

**Comment by ThePiachu** [comment]
It's been awhile, hmm... I think it had something to do with output from one part of the work party being used in the same work party, so probably eliminating individual inputs from some work. Like, "add hewn logs to make BU1, add mortared stone and mortar to turn it into BU2, don't add another BU1 since it's already covered". So sort of like breaking things down by weight but also being able to eliminate specific inputs.

**Comment by SlayksWood** [comment]
So we have 2 issue #16009 and #15576. I close this one.
