### ISSUE TITLE
[0.9.0 Staging-1494] Cleanup Crew Logging doesn't do anything

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15534]
Seems the Cleanup Crew Logging talent doesn't do anything - after taking it you still use up calories cleaning up tree debris.

**Comment by SlayksWood** [comment]
without talent it costs x3 calories. Talent works.
![image](https://user-images.githubusercontent.com/45708377/62440398-99644080-b758-11e9-970f-ae8702f6125e.png)
Hitting tree costs 10 calories at 7 level Logging with stone axe.
Hitting tree debris costs 30 calories at 7 level Logging with stone axe without talent.
Additional calories is difference between them.
