### ISSUE TITLE
[0.9.0 Staging-1494] People appear twice on maps, offline people appear on map

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15532]
I've seen this a few times - people seem to appear twice on the maps at times:

![image](https://user-images.githubusercontent.com/964559/78403282-f860aa80-75b0-11ea-8ad7-60ad1819cd92.png)

It might be related to logging in and out, since the maps also like to display logged out people, I'm guessing in the location they logged off at:

![image](https://user-images.githubusercontent.com/964559/78403518-568d8d80-75b1-11ea-9e0c-8e8bbd9561c0.png)

**Comment by SlayksWood** [comment]
dup #10614
