### ISSUE TITLE
osx mouse isn't working in 5.6 staging

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1553]
wasd work fine, can't rotate though

**Comment by SeanAtr0n** [comment]
I removed various local eco cache dirs and now it works... guess it's not as high priority if it was just a problem on my machine.

**Comment by MarjieAVolk** [comment]
So should we close this issue?

**Comment by SeanAtr0n** [comment]
guess someone can open a new bug if they hit it
