### ISSUE TITLE
Frotch Floatation cell have 2 output pipe

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15542]
(one - nonfunctional)
![изображение](https://user-images.githubusercontent.com/4980243/78420561-e33f5680-7658-11ea-9e3a-f4a7dac8e530.png)

**Comment by SlayksWood** [comment]
@keegan-o 
If it's planned for the future, Can you somehow identify it differently visually? I must distinguish for what each output.

**Comment by keegan-o** [comment]
Ah yes, this is for when wet tailings are pipable-- we'll come up with a visual indicator for tailings outputs. For 9.0 I can just disable it visually though.

**Comment by Sekor2600** [comment]
seems to be fixed. 3rd Pipe is disabled
