### ISSUE TITLE
Froth floatation cell - animation bugged

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15543]
As you can see, animation is not 360, and "marker" just flickering
Made animation 360 or remove marker from rotating part.
https://youtu.be/9QlvmMXpXn0

**Comment by MilenkoTunjic** [comment]
It is not in the asset, exported animation contains full 360 circle. It could be the animation speed, or some sort of optimization that causes it dropping frames. Check the asset setup in unity.
