### ISSUE TITLE
[0.9.0 Staging-1494] Project incorrectly identified as being part of another work party

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15540]
I tried chaining together some work parties on the test server. Basic Upgrade 3 and 4. When I created the first work party, it auto-populated with both of those upgrades. I deleted the BU4 and kept only work relating to BU3:

![image](https://user-images.githubusercontent.com/964559/78419818-418b1b80-75fe-11ea-9a4b-37ecc6831130.png)

However, when it came time to creating a posting for BU4, I got this error:

![image](https://user-images.githubusercontent.com/964559/78419824-5071ce00-75fe-11ea-97bb-7f4019e27fac.png)

Which was an odd bug.

**Comment by SlayksWood** [comment]
Need to delete with trash can:
![image](https://user-images.githubusercontent.com/45708377/78529875-44972f00-77eb-11ea-87c0-dc696a8b81b0.png)
![image](https://user-images.githubusercontent.com/45708377/78529908-52e54b00-77eb-11ea-9f45-1be70453707e.png)
![image](https://user-images.githubusercontent.com/45708377/78529923-5bd61c80-77eb-11ea-8fcb-ea6993a3b2ce.png)
If you delete with "plus" then all works fine:
![image](https://user-images.githubusercontent.com/45708377/78529970-73ada080-77eb-11ea-9cb8-49240847d489.png)

**Comment by johnkslg** [comment]
Good find, the distinction was key to getting it fixed thanks both!
