### ISSUE TITLE
[0.9.0 Staging-1494]Game crashed after accesing workparty table. Can't load game since then.

### ISSUE THREAD

**Issue by nLavanor** [StrangeLoopGames/EcoIssues#15546]
I wanted to open a workparty table panel belonging to another player. After pressing the E key, the game crashed with a server error message. I can't enter the world since then.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4431079/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4431080/Player-prev.log)

**Comment by beastyn** [comment]
dup #15528
