### ISSUE TITLE
0.9 blocks periodically builded as placed.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15553]
https://youtu.be/AQ7Bq8A0tVQ

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4432287/Player.log)

This error apperars rarely, and fixes after restart. (solo game, idk how it work in multiplayer)

**Comment by NN-Mike** [comment]
I think this is caused after you were using a block with a new type, E.g. Ashlar stone chimney type

Then pick up a T1 block like hewn log that does not have this form, it reverts to cube form, but doesn't actually place cubes, it puts down the material on the floor. 
To correct it, you have to change the form to something like floor block, re-selecting cube does not work
