### ISSUE TITLE
[0.9.0 Staging-1494] Dropdown list can out from screen

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15558]
When I tried authorising some users from the end of the alphabet, I ran into a problem where the authorisation list dropdown didn't respect the end of my screen:

![image](https://user-images.githubusercontent.com/964559/78464500-31774880-769f-11ea-92e3-05549a7e34e1.png)

So I was unable to authorise the given person because I couldn't scroll far enough down. I'm guessing it might have something to do with my Render Scale of 85% (for a 4k monitor). It would be nice if the dropdown respected screen boundaries and you could scroll all the way down.

**Comment by ThePiachu** [comment]
Another issue with the list of people in a law - the list takes up the entire screen and it still clips from the top:

![image](https://user-images.githubusercontent.com/964559/79674515-c185b980-8198-11ea-9685-94aaf7cb9f0c.png)

**Comment by SlayksWood** [comment]
#14843
