### ISSUE TITLE
[0.9.0 Staging - 1494] Registrar does not function properly for anyone besides the owner

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15551]
**Steps to reproduce:** Place registrar, authorize everyone, other player makes titles but they can't assign them
**Expected behavior:** everyone is able to make their own titles and hand them out
**Actual behavior:** creating a title for anybody but the owner it is impossible to hand the title out because the green + arrow does not show up
**Providing Log files:**
![20200404131604_1](https://user-images.githubusercontent.com/1329717/78458422-d0d41580-7676-11ea-8836-24686414617c.jpg)
![20200404131344_1](https://user-images.githubusercontent.com/1329717/78458424-d16cac00-7676-11ea-91cc-e230e02bd089.jpg)

**Comment by NN-Mike** [comment]
![image](https://user-images.githubusercontent.com/54982803/78458453-6092b780-76a9-11ea-9777-c39bfdfbda0e.png)
Also would like to add that members of titles do not have land claim permissions, they need to be Title Managers to have authorisation
