### ISSUE TITLE
[0.9.0 Staging - 1494] Rock filter doesn't include all stones.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15565]
**Steps to reproduce:** Create a contract to add/remove blocks on a contract board.
**Expected behavior:** Able to select all stone types
**Actual behavior:** Only sandstone is selectable, _granite, limestone, basalt, etc_ are unselectable, in fact they don't even show up in the list of selectable blocks.
**Providing Log files:**
![20200405101410_1](https://user-images.githubusercontent.com/1329717/78502491-05070f00-7727-11ea-8f89-0dc1795963e3.jpg)
![20200405101344_1](https://user-images.githubusercontent.com/1329717/78502493-059fa580-7727-11ea-85ad-65bb7db98405.jpg)
![20200405101351_1](https://user-images.githubusercontent.com/1329717/78502494-06383c00-7727-11ea-9cc5-5b6ddde68a6a.jpg)
![20200405101355_1](https://user-images.githubusercontent.com/1329717/78502495-06383c00-7727-11ea-8d39-7e4b0d0ba7f7.jpg)
![20200405101404_1](https://user-images.githubusercontent.com/1329717/78502496-06383c00-7727-11ea-90fd-0a143f5cdcbd.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/78533133-1f0d2400-77f1-11ea-9234-099223d0de42.png)

**Comment by WeaselDog** [comment]
I can't replicate this in latest version. Can you double check it is still an issue?
![StoreFilter](https://user-images.githubusercontent.com/47330823/78864516-9c52b780-79f0-11ea-8972-e6740617fae0.png)
![ContractFilter](https://user-images.githubusercontent.com/47330823/78864565-b42a3b80-79f0-11ea-84eb-e8f79e2c62ef.png)

**Comment by SlayksWood** [comment]
seems fixed.
