### ISSUE TITLE
Lots of WWise exception spam in client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15569]
![image](https://user-images.githubusercontent.com/3536496/78511953-81184b80-7755-11ea-95e6-3a5881631816.png)
Can you make these flag as something other than exceptions? Hides other exceptions.

**Comment by Quadbro** [comment]
can you provide more info? can't repro this in new worlds

**Comment by mirasrael** [comment]
@johnkslg you can disable WWise logging in WWise settings.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/78535178-6c3ec500-77f4-11ea-97b3-6352db744e28.png)

**Comment by Quadbro** [comment]
Changed logging level in svn
