### ISSUE TITLE
[0.9.0 Staging - 1494] Unity Crash when editing the District Maps

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15567]
**Steps to reproduce:** Edit District Maps on the Zoning Table (time spent on it may be related but not sure if its a factor or not in this; just in case I was in game for approx 45-50 minutes the entirety of it being spent in the zoning table editing the district map) and then submit the map
**Expected behavior:** Edit the District Map, submit it, go back to playing or modifying other government things.
**Actual behavior:** Edited the map and immediately got a unity crash
5. Providing Log files.
log files were massive so they are compressed into a zip file
[unity crash districts.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4434954/unity.crash.districts.zip)

**Comment by SlayksWood** [comment]
merged to #15314
