### ISSUE TITLE
Web / Elections / Empty votes

### ISSUE THREAD

**Issue by olegshegai** [StrangeLoopGames/EcoIssues#15562]
It's currently possible to press "submit vote" without selecting anything.
Server side will be handling this case soon and show an error (screenshot), but it's better to hide the button until the user makes a choice. Bonus points: show only if the user changes current choice (i.e. after submiting "no", the button should be hidden and shown only if "yes" selected).
![image](https://user-images.githubusercontent.com/56091594/78498865-c9376e00-7755-11ea-8b83-19453c63ed5d.png)

**Comment by Sarah-Graesyn** [comment]
I approve of this thought process @olegshegai

**Comment by j3fffff** [comment]
removed submit button, now you just click yes or no. nice and simple
