### ISSUE TITLE
[0.9.0 Staging - 1494] Pressing Tab when in a storage/work table closes out everything

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15566]
**Steps to reproduce:** Open Inventory of Vehicle or other Storage, or a workbench and then press tab like you are trying to free your mouse
**Expected behavior:** use inventory normally.
**Actual behavior:** all open interactable windows close and leave me staring at the wall or chest, etc.
**Providing Log files:**

**Comment by SlayksWood** [comment]
It's intented behavior. Inventory and other UI can't be opened without TabMode.(
exceptions - Minimap, Backpack and Tutorial). Closed for now.
