### ISSUE TITLE
USER ISSUE: Kopf auf dem Asteroid

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#15564]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
baue einen hohen Turm

**Expected behavior:**
Asteroid per nahem sehen

**Actual behavior:**
Asteroid mit Bild drauf gesehen. Kopf einer Person

**Do you have mods installed? Does issue happen when no mods are installed?:**
Asteroid mit Bild drauf gesehen. Kopf einer Person

**Comment by elfl0rd** [comment]
intended, it is easter egg.

**Comment by TimoNuernberg** [comment]
> intended, it is easter egg.

thanks

**Comment by SlayksWood** [comment]
yea, this is intented 👍
