### ISSUE TITLE
Investigate mesh colliders being used

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15578]
Super detailed mesh collider on lumber stockpile causing user to fall into the cracks.
See if these colliders on this object and others are a performance concern and if so remove them. 
Even if they're not a performance concern, in this case it causes a collision issue so should probably be removed in favor of simple boxes.

**Comment by keegan-o** [comment]
Perhaps this got fixed by sekoris when he was trouble shooting the stockpiles or something, because I investigated and both lumber and large lumber stockpiles have good simple colliders
![image](https://user-images.githubusercontent.com/14983165/81367277-9b6d7e00-90a1-11ea-8341-60a95325fbcc.png)
