### ISSUE TITLE
[0.8.3.3] You can instantly repeal some laws without a vote

### ISSUE THREAD

**Issue by ojacobson** [StrangeLoopGames/EcoIssues#15572]
**Steps to reproduce**

1. Create a new single-player game.
2. Go to the law editor.
3. Open the Citizenship law under Active Laws.
4. Click the Delete Proposal button.
5. Propose any new law. (I used "When attempting to Play, allow" as a dummy testing law.)

Do this within the first two hours, when the Citizenship law would prevent votes.

**Expected outcome**

* The Citizenship law is not repealed.
* The Citizenship law prevents the proposal of a new law.

**Actual outcome**

* The Citizenship law is repealed without a vote.
* Voting begins on the proposed new law, with the submitting player voting Yes.

**Remarks**

This also works on a dedicated server, as I found out to my chagrin. I discovered this by accident when I lost track of which page I had open in the web view. I was _very_ surprised when deleting the "Citizenship" law worked. I also can't pass a new law named "Citizenship", almost as if the law still exists somewhere, but it doesn't seem to be in force.

I'm not sure how urgent this is; on the one hand, instant repeal without a vote has obvious potential for abuse. On the other hand, I have to assume that the vote validation system is getting gutted as part of the Con Law system in 9.0, so this might be irrelevant by then.

I have a test case brewing to verify whether this works on laws passed by other people or not.

**Comment by SlayksWood** [comment]
Thank you for a report.
The system of laws and civics objects will be changed in 0.9.0, such situation can't arise. Closed.
