### ISSUE TITLE
[0.9.0 staging-1500] Rounding problem in WorkParty

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15574]
Step to reproduce:
1. create 1000 new Currency "Aniki", you can use basic credit if it absent in Contract Ecsrow, if I have Slayks Credit = 0, then I should create another currency:
![image](https://user-images.githubusercontent.com/45708377/78552191-b5e8d900-780f-11ea-8352-b8003acb33cc.png)
2. add new order for 10 Hewn log at workbench. You can use another recipe, but there is important that you have fractional division, In my case if I'll add labor by 100 then I have payment like 50/3 = 16,67. Create work party, set Pay as you go:
![image](https://user-images.githubusercontent.com/45708377/78552636-84244200-7810-11ea-8db0-1c74dfebe8d9.png)
3. check currency, seems all's right:
![image](https://user-images.githubusercontent.com/45708377/78552700-9f8f4d00-7810-11ea-826a-aed086809f2d.png)
4. another player take work party and start add 10 birch log, another 10 birch log, 100 Labor, 100 Labor. Seems all's right:
![image](https://user-images.githubusercontent.com/45708377/78553355-c26e3100-7811-11ea-9ffd-231e0ad6afef.png)
5. check currency:
![image](https://user-images.githubusercontent.com/45708377/78553379-d0bc4d00-7811-11ea-8754-22cda6529146.png)
6. another player add last 100 Labor:
![image](https://user-images.githubusercontent.com/45708377/78553452-edf11b80-7811-11ea-8fc9-84f6ed852b9e.png)
7. The remaining money transferred to workparty owner:
![image](https://user-images.githubusercontent.com/45708377/78553481-fba6a100-7811-11ea-8d99-9be12633b4a1.png)

I assume it happens because we have some troubles with float numbers.
If you add some "Aniki" in COntract Escrow (for example start another workparty) before 6 point then another player will get money, but we'll have this problem in another workparty.

**Comment by johnkslg** [comment]
Fixed, I made transfers look for 'close enough' values, and also default to 'Transfer as much as possible' informing when they cant (in case, say, someone is owed $10 from escrow but escrow has been raided somehow and only has $5, they will still get $5). 

![image](https://user-images.githubusercontent.com/3536496/78732020-4568b780-78f6-11ea-91d3-594b6bd1934b.png)

![image](https://user-images.githubusercontent.com/3536496/78732029-4ac60200-78f6-11ea-94c0-04d63513a177.png)

Chad got his money.
