### ISSUE TITLE
[0.9.0 staging-1500] Strange calculation in contract escrow with Work Party.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15576]
Step to reproduce:
- Constarct escrow has 0 Aniki:
![image](https://user-images.githubusercontent.com/45708377/78557110-e1bc8c80-7818-11ea-929f-c17c3f11a514.png)
- start order Dendology research paper basic and add 10 Birch log (25% of work future workparty):
![image](https://user-images.githubusercontent.com/45708377/78557217-0b75b380-7819-11ea-97c9-370062d786fc.png)
- start work party for this order, it's still said that I need 20 Wood, but I already add 10. Change payment to 100 Aniki:
![image](https://user-images.githubusercontent.com/45708377/78557339-45df5080-7819-11ea-97b5-723a38219b94.png)
- post it. Contract Escrow has 100 Aniki, but work Party complete on 25%:
![image](https://user-images.githubusercontent.com/45708377/78557462-82ab4780-7819-11ea-9a79-a3ca7d791f6e.png)
![image](https://user-images.githubusercontent.com/45708377/78557510-96ef4480-7819-11ea-8bbf-afd778bf4214.png)
- But this percentage was not added to anyone:
- add another 10 Birch log and 50 Logging Labor to Workparty:
![image](https://user-images.githubusercontent.com/45708377/78557721-f51c2780-7819-11ea-801c-064d87d43a64.png)
- All money was returned back to me, but these 25 Aniki returned at the end looks strange. Maybe we can change it? We will lose some more money if it's had taxes.
For example:
1. Don't take money for completed %
2. Display in Work Party only needed resources and labor for order.

**Comment by johnkslg** [comment]
Fixed
