### ISSUE TITLE
[0.9.0 Staging - 1494] Sensor based belt sorter

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#15579]
Version [0.9.0 Staging - 1494] 

Sorter has the same recipe as froth for iron,everything is the same except time and labor and is almost twice the price not worth makeing it

**Comment by elfl0rd** [comment]
Different tailings.
But i agree, SBBS should have more benefit.

**Comment by WeaselDog** [comment]
Thanks for the catch. We will be adjusting the costs of Sensor Based Belt Sorter.

**Comment by WeaselDog** [comment]
Taking over this one
