### ISSUE TITLE
[0.9.0 staging-1500] Animal strange behavior.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15571]
Step to reproduce:
- build construction like this:
![image](https://user-images.githubusercontent.com/45708377/78527728-617d3380-77e6-11ea-9cc1-a5a79f35ce92.png)
![image](https://user-images.githubusercontent.com/45708377/78527736-680bab00-77e6-11ea-9528-3b5644c06a06.png)
- I have 1 empty blocks under bricks.
- spawn animal near this place.  See how they move around this brick floor:
![image](https://user-images.githubusercontent.com/45708377/78527933-dbadb800-77e6-11ea-874c-893ecc54d12f.png)

and my favorite:
![image](https://user-images.githubusercontent.com/45708377/78527871-b751db80-77e6-11ea-87b5-0be84ca44ceb.png)
![image](https://user-images.githubusercontent.com/45708377/78527973-f3853c00-77e6-11ea-8a31-225a09f79509.png)

**Comment by mirasrael** [comment]
It may be related to delay for world route update. But actually I think it may be pushed to next release unless it is something new comparing to 8.3 (regression).

**Comment by SlayksWood** [comment]
It's regression. 0.8.3:
![image](https://user-images.githubusercontent.com/45708377/78544400-c21a6980-7802-11ea-9a86-22ddfd27feb4.png)

**Comment by MishkaFur** [comment]
Has been happening in staging for a while if it helps, since at least 1484 when I spotted it but just assumed it was due to the animal being on a bridge above water
