### ISSUE TITLE
[0.9.0 staging-1494] Typing "Food" in chat causes a tag to appear with 185 entries

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15586]
The word "food" is used very often in game. The tag associated with it should not be link-able in chat.  It also shows up in reference section of Ecopedia when it shouldn't as this tag is not useful.

![FoodTag](https://user-images.githubusercontent.com/47330823/78642782-1ad01d80-7868-11ea-8889-b58c8cc18480.png)

Related issues : 
https://github.com/StrangeLoopGames/EcoIssues/issues/14781
https://github.com/StrangeLoopGames/EcoIssues/issues/15357

**Comment by mirasrael** [comment]
We need support for tag exclude lists for:
- Chat links parser
- Ecopedia auto-tags articles
- Item Tooltips

**Comment by mirasrael** [comment]
Added concept of Tag Definition. They now may be defined in `Eco.Mods\Systems\TagDefinitions.cs` like this:
```csharp
public class TagDefinitions : IModInit
    {
        private static readonly TagDefinition[] Definitions =
        {
            new TagDefinition("Wood")            { ShowInFilter = true },
            new TagDefinition("Ore")             { ShowInFilter = true },
            new TagDefinition("Food")            { ShowInFilter = true, AutoHighlight = false, ShowInEcopedia = false }
        };
}
```
also updated RegistrarFinder and EcopediaRegistrarList for Tag Definitions support.

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/80367372-a5b69d80-8893-11ea-84be-04f9f42b73bf.png)
![image](https://user-images.githubusercontent.com/475445/80367420-b9620400-8893-11ea-8e4b-51e2688b28db.png)
