### ISSUE TITLE
[0.9.0 Staging - 1494] Crash when dropping garbage

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#15581]
Got a crash when trying to drop 4 plant fibers on the ground
The crash window disappeared before I managed to click on "report a bug" but I got a screenshot of it atleast.

**Version**: 0.9.0.0 beta staging-1494
**Steps To Reproduce**: 1. Drop 4 plant fibers on the ground. I was just outside a very large farm field with newly planted cookeina & bolete mushrooms when trying to drop them.
**Expected behavior**: No crash
**Actual behavior**: Crash
[PlayerLogs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4440618/PlayerLogs.zip)
![crash_droppingplantfibers](https://user-images.githubusercontent.com/39825431/78601472-1cdcb100-7855-11ea-94fa-5e87f1434cb5.png)

**Comment by revtje** [comment]
When I logged in after the crash the plant fibers were gone from inventory and they were not dropped on the ground. Seems to have disappeared.
Tried to drop 100 Agave leaves and the 4 plant fibers from earlier briefly appeared in the inventory and then the game crashed again.

**Comment by Engimage** [comment]
Same issue.
Interestingly enough if you drop something else after relog, the previous item returns to inventory.

**Comment by MishkaFur** [comment]
This issue could be related to Sarah doing a law to prevent garbage being dropped if not on your own property

**Comment by beastyn** [comment]
Yes, its in the law.
Because you are trying to prevent ant tax at the same time
This law will make a crash
![bandicam 2020-04-07 12-09-13-360](https://user-images.githubusercontent.com/27898520/78640112-9e215b80-78c8-11ea-9512-4540929913c0.jpg)

**Comment by johnkslg** [comment]
Couldn't repro this:
![image](https://user-images.githubusercontent.com/3536496/78732284-16067a80-78f7-11ea-8c2f-0076715856b3.png)

![image](https://user-images.githubusercontent.com/3536496/78732269-0d15a900-78f7-11ea-826d-7dce7073fcee.png)

Can you tell me steps to repro in a fresh world, or link the world where it can be reproed?

**Comment by beastyn** [comment]
Actually, repro just fine with steps:
1. /bt 4,20,6,20
2. Claim this building
3. Place a capitol and ratify
4. Place a court and make the law
![bandicam 2020-04-07 12-09-13-360](https://user-images.githubusercontent.com/27898520/78745900-eb600480-797e-11ea-9905-a2983a15bb2b.jpg)
with tax in personal currency
5. Accept the law
6. /give plant fibers,10
7. Go out from you deed and try to drop garbage with fibers.
Crash.
Here is a save
https://drive.google.com/file/d/1O407rSx_WKJkeH77xXrTWCVZ20YsXMyh/view?usp=sharing

**Comment by johnkslg** [comment]
Thanks, that did it. Fixed!
