### ISSUE TITLE
[0.9.0 staging-1494] Icons with layers have a layer missing in Store

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15588]
Modern research papers have a green color. This color does not show up in a store. Also it looks like there is some text overlap, but maybe this is separate issue.

![ResearchPaperColor](https://user-images.githubusercontent.com/47330823/78644287-7dc2b400-786a-11ea-9805-87b4ca42e383.png)

**Comment by WeaselDog** [comment]
It is also true for all furniture with a tier icon but a little worse because it is blank icon:

![HardwoodDoorIcon](https://user-images.githubusercontent.com/47330823/78646661-3dfdcb80-786e-11ea-8b91-166fbe41dc90.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/79951122-cab8a400-8480-11ea-81df-9b5d37950ffe.png)
