### ISSUE TITLE
[0.9.0 staging-1494] Removing election process breaks titles

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15585]
If you remove the election process tied to an elected title the title becomes invalid and all laws related to it stop working. Maybe we don't want people to be able to have a elected title with no election process, but it did cause some titles to break on playtest that had to be fixed with follow up elections.

![RemovedElectionProcess](https://user-images.githubusercontent.com/47330823/78642105-09d2dc80-7867-11ea-8685-c0578ced8c23.png)

**Comment by johnkslg** [comment]
Fixed, now elected titles wont become invalid if their associated Election Process does, but it **will** prevent an election from being started for that position, and notify you as such.
