### ISSUE TITLE
[0.9.0 Staging-1494] Not able to drag and drop items into the empty space of Steam Truck

### ISSUE THREAD

**Issue by racerand** [StrangeLoopGames/EcoIssues#15595]
**Version:** 0.9.0.0 beta staging-1494

**Steps to Reproduce:**
1. Go into inventory of steam truck with other stockpile with another inventory available
2. Drag item from other inventory onto the blanck area to the bottom right of the trucks inventory as shown in the screenshot
![drag-and-drop](https://user-images.githubusercontent.com/16125637/78666381-91583400-78d7-11ea-9953-ec66674bdbc7.png)
3. Release
(Only tested with sand and concentrated Iron)

**Expected behavior:**
Item will be put in to the inventory as with other inventories

**Actual behavior:**
Item goes back to where it came from

**Comment by SlayksWood** [comment]
dup #15525
