### ISSUE TITLE
iron saw blade has no using

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15591]
after https://github.com/StrangeLoopGames/Eco/pull/5877
before we use steel saw blade for sawmill and advanced masonry table, and iron saw blade for adv carpentry

As i think we can use tag "saw blade" includes steel and iron for sawmill and adv carpentry.

**Comment by SlayksWood** [comment]
Sawmill?

**Comment by elfl0rd** [comment]
oh, my bad, thx :)
