### ISSUE TITLE
USER ISSUE: Edit character overwrites crafted clothing items

### ISSUE THREAD

**Issue by KaxeDK** [StrangeLoopGames/EcoIssues#15594]
**Version:** 0.9.0.0 beta staging-1494

**Steps to Reproduce:**
1. Craft a clothing item that is not available in the standard edit person menu, such as work boots or camo pants. In this example I use work boots.
2. Equip the work boots, thus putting the already worn standard tall boots into your inventory.
3. Click "edit" in the character menu.
4. Choose tall boots, or any other standard shoe type, and save your character.

**Expected behavior:**
The work boots should be put into your inventory, just like the original tall boots were when you equipped the work boots.

**Actual behavior:**
The work boots are replaced by tall boots and thus are lost. This bug can remove a lot of crafted items and spawn an equal amount of standard clothing into the world instead.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Comment by SlayksWood** [comment]
dup #14038
