### ISSUE TITLE
[0.9.0.0 beta staging-1501] on web adding graph to comment submit not working

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#15596]
If you want to submit a comment on the webpage with an graph been added, submit button is not working. For adding map it is working fine. 
![image](https://user-images.githubusercontent.com/47274045/78666810-307d2b80-78d8-11ea-8bfe-8506ad491515.png)

**Comment by beastyn** [comment]
Yeap, it has happened, again
![bandicam 2020-04-07 17-40-15-645](https://user-images.githubusercontent.com/27898520/78670239-e35c8200-78f6-11ea-8d91-78b7fb1021ba.jpg)

**Comment by denysaw** [comment]
PR: https://github.com/StrangeLoopGames/Eco/pull/5939
