### ISSUE TITLE
0.9 Barrel crafting

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15593]
barrel crafted at electric machinist table, but electric machinist table is not support oil drilling module.

For me - we can change barrel recipe to mechanics (or industry) and all fine.

**Comment by WeaselDog** [comment]
Fix for now is to add support for Oil Drilling module. We can look at changing skill requirement as we rebalance Oil Drilling & Industry, but we need to look at how this will impact leveling up more.

**Comment by Engimage** [comment]
I can definitely say that Barrels were the main source of leveling Oil Drilling experience. But I can also say that leveling Oil Drilling was too fast.

With the recyclable barrels being a thing now I would just move Barrels to Mechanics and forget about them. Those will never be produced in large amounts any more.

**Comment by elfl0rd** [comment]
agree, this is why i ask about moving barrel crafting into another speciality.

**Comment by SlayksWood** [comment]
We are discussed this, but not in 0.9.0
