### ISSUE TITLE
Parts of Hud missing

### ISSUE THREAD

**Issue by daim86** [StrangeLoopGames/EcoIssues#15598]
Hi,
my problem is tha i can´t see the left part of the hud where u can see how much i need to eat or my specialisations. 
I already did:
-restart the game
-reinstall the game
-host new map
-controlled is nvidia is hiding the hud
nothing worked.
The rest of the Hud/ui works normal.

Sorry for my bad english :)
hope u guys can help.

Daim

**Comment by SlayksWood** [comment]
@daim86 
Can you provide some screenshots? And log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by elfl0rd** [comment]
complete or skip tutorial. (left top angle)

**Comment by elfl0rd** [comment]
As I think this issue can be closed :)

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
