### ISSUE TITLE
0.9-1501 basic "Ashlar stone" produce crushed granite.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15592]
As you can see...
![изображение](https://user-images.githubusercontent.com/4980243/78655034-19394080-78ce-11ea-95e9-85d3762bfccd.png)
![изображение](https://user-images.githubusercontent.com/4980243/78655073-29e9b680-78ce-11ea-910c-8b582b278de3.png)

there i spend 8 limestone and receive 3 crushed granite.
![изображение](https://user-images.githubusercontent.com/4980243/78655166-4be33900-78ce-11ea-9c8b-efcf0e7a03fc.png)

**Comment by SlayksWood** [comment]
dup #15042
