### ISSUE TITLE
[0.9.0 staging 1501] Transmission poles make it very easy to steal power

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15605]
Transmission poles do not follow auth, so if you place one near someones base you can steal the power they have even if it is consuming fuel ie steam or combustion generator.

This was possible in 8.3 but the comparative high cost resource wise and also due to the power loss of 100w per streetlamp to do so

Way to replicate
Place a claim, place a power source in it
Have another player place a transmission pole within 25 blocks and they will get your power.

**Comment by D3nnis3n** [comment]
This works as intended.

**Comment by D3nnis3n** [comment]
See more info here: https://github.com/StrangeLoopGames/EcoIssues/issues/12483
It will be dealt with at a later day but for now it's kept as-is, as Power Transmission is meant to be a collaborative thing for public power plants.
