### ISSUE TITLE
[0.9.0 Staging-1494] Land authorisation, Real Estate Desk, etc.

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15609]
I wanted to figure out how to authorise someone on my property. The process is not intuitive:

- I don't think the land claim stake tool prompts you to open the land settings if you aim it at your property. A tool tip would be nice
- I don't think you can click on your land name to open the menu either. It would be nice to be able to do that
- The Real Estate Desk also doesn't let you change the lang authorisation:

![image](https://user-images.githubusercontent.com/964559/78726095-f7e44e80-78e5-11ea-9e0c-7f029b1d3221.png)

In general, it would be nice to make that process a bit clearer and easier to access.

**Comment by beastyn** [comment]
1. You have action hint
![bandicam 2020-04-08 16-38-35-618](https://user-images.githubusercontent.com/27898520/78780033-6e04b600-79b7-11ea-8a45-b3b203572763.jpg)
2. You have tooltip advice at the bottom
3. It should not for not. You can make suggestion here https://github.com/StrangeLoopGames/EcoSuggestions
