### ISSUE TITLE
minimap needs fallback shader

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1560]
For cards that cant handle geometry shaders

**Comment by metachronism** [comment]
I think we should just get rid of the geo-shader method and use a vfetch+instanced shader

**Comment by metachronism** [comment]
if we have a base mesh with verts at y=0 and y=1, we should be able to just scale the y by the voxel height with vfetch, which them means we can draw the full world in an instance shader

**Comment by SeanAtr0n** [comment]
Not sure what you mean, but the web map uses instancing so converting that to unity wouldn't be too hard. Although we might still need a fallback for that even.
