### ISSUE TITLE
[0.9.0 Staging 1501] Legislation page shows Voted no but I voted yes

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15600]
1. Version - Staging 1501
2. Steps to Reproduce Er, Vote on a Law and look at your vote in Legislation
3. Expected behavior. - Votes show correctly,they were in 1484

Shows Voted No
![image](https://user-images.githubusercontent.com/61889138/78709473-a058d980-790b-11ea-8217-fa6d76f77200.png)

Shows Voted Yes
![image](https://user-images.githubusercontent.com/61889138/78709512-ad75c880-790b-11ea-8402-ba40fdddda9f.png)

**Comment by MishkaFur** [comment]
Racerand is also having the same.

**Comment by SlayksWood** [comment]
dup #13616
