### ISSUE TITLE
[0.9.0 Staging-1494] Crushed Coal is useless

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15611]
Stumbled upon this thing for the first time:

![image](https://user-images.githubusercontent.com/964559/78726461-e94a6700-78e6-11ea-860a-3b0ea3363626.png)

It was a bit confusing that you couldn't use it for anything, not even burning. You'd think crushed coal would still be burnable.

It might be an interesting production item too. Say, if you could stamp mill Coal into crushed coal to turn it from a rock into "dirt-like" object with similar energy density (20 rock coal to 5 crushed coal), but lighter and so on. Would make it easier to transport on trucks, similar to crushed ore.

**Comment by elfl0rd** [comment]
I agree, as I think only crushed coal should be an ingredient or fuel.

**Comment by ThePiachu** [comment]
It's nice to have options. I like that Charcoal stacks to 100 and can be put into chests, but takes awhile to craft. I like Coal because you can straight up mine it and use it. Crushed Coal could fill the niche between the two of being easier to transport than Coal, but not as easy as Charcoal.

**Comment by WeaselDog** [comment]
It should not be obtainable in game at this time. Did you find some while mining?

**Comment by ThePiachu** [comment]
I stumbled upon it in a stockpile by Xao's building on the test server. Not sure how it got there.

**Comment by ThePiachu** [comment]
Talked with people a little, Xao said Scott gave him the crushed coal and Lavanor says "there is a lot of crushed coal near his house":

![image](https://user-images.githubusercontent.com/964559/78826324-2b7eb180-7996-11ea-9a1d-3e34423f0d39.png)

**Comment by nLavanor** [comment]
Is spawned around coal veins, 2-3 block under surface.

**Comment by SlayksWood** [comment]
You have old generation in playtest world. In the new generation, Crushed Coal has been removed. It will not be used in 0.9.0, but post 0.9.0 it will be added.
Closed for now.
