### ISSUE TITLE
[0.9.0 Staging-1494] Recipe tooltip should show inputs and outputs, not just inputs

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15613]
I have been trying to compare various recipes of crafting crushed / concentrated ore before I had a given building. I hovered over the tooltips and they showed how many inputs they take, but not how much they output:

![image](https://user-images.githubusercontent.com/964559/78727490-a8a01d00-78e9-11ea-9c05-65a3637c7641.png)

That information would be nice to know, especially for items relating to mining / smelting and other recipes that produce more than one output.

**Comment by Engimage** [comment]
This is especially useful for recipes outputting multiples of an item such as Nails etc. Looking at the recipe currently you can't see it will output 4 nails from 1 Iron Bar which is confusing.

**Comment by mirasrael** [comment]
Already fixed.

**Comment by mirasrael** [comment]
https://user-images.githubusercontent.com/475445/78675817-44338c80-78ee-11ea-9bc5-10861c4edd33.png
