### ISSUE TITLE
[0.9.0 Staging-1494] Large amount of lag while mining / mass producing

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15615]
Less of a bug and more of a general feedback that would be nice to have addressed - server lag. It's been a frequent thing on the server, even with 2-3 people online. I think we narrowed it down to two big sources - mining and crafting.

We're guessing the chunk generation while mining is at fault for some of the lag. Give Skids to 2-3 people and things can lag out.

Other big source of lag might be the inventory juggling during some production. I think the biggest case of this I could find was doing Ore -> Crushed Ore -> Concentrated Ore -> Smelting -> Slag Crushing -> Concrete.

It would be nice to have those areas looked into to try mitigate the lag problem.

**Comment by ThePiachu** [comment]
There might also be some lag with tree cutting, but it's probably similar to mining - physics objects and creating stuff on the floor.

**Comment by mirasrael** [comment]
Waiting for this fix https://github.com/StrangeLoopGames/EcoIssues/issues/15825

**Comment by mirasrael** [comment]
@ThePiachu need to confirm if it is still an issue on latest version.

**Comment by ThePiachu** [comment]
Unfortunately I haven't been playing recently, and I think the test server reset recently, so I won't be able to verify whether or not the issue was fixed. Best ask some other prolific testers ;).

**Comment by mirasrael** [comment]
From latest playtest feedback it doesn't seems anymore an issue.

**Comment by Chris-85** [comment]
Can´t verify the Issue. No matter who much is minded, crushed, smelted or produced. Even shifting whole stockpiles while doing so is working fine. No Lag or "hickups" seen.
