### ISSUE TITLE
[0.9.0 Staging-1494] Skid can reach beneath itself, but can't dig there

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15612]
I was working on a road with a skid. I wanted to remove a layer of dirt on the same level as the road to have space for the Skid. It could reach beneath itself, however, it was unable to dig there:

![image](https://user-images.githubusercontent.com/964559/78726735-96bd7a80-78e7-11ea-8bb7-e45c75f83914.png)

It's a bit of a shame, being able to dig 1 below yourself would make it easier for some road work, etc. Alternatively, the Skid shouldn't be able to reach that low - it's already clipping itself a bit.

**Comment by elfl0rd** [comment]
Personally for me, the fact that the skidsteer can't dig underneath itself is an feature.
You can use an excavator for that.

**Comment by beastyn** [comment]
Intended. You can place a suggestion here https://github.com/StrangeLoopGames/EcoSuggestions
