### ISSUE TITLE
[0.9.0 Staging-1494] Notification incorrectly stating a store is sold out

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15610]
I noticed this notification a few times:

![image](https://user-images.githubusercontent.com/964559/78726338-8c4eb100-78e6-11ea-9621-14d0430e2544.png)

Someone bought a large amount of iron from my store, got a notification that the store was sold out, however the place still had a stockpile+ worth of it. Something might be up with that.

**Comment by Engimage** [comment]
Actually it says "now is sold out of "[here should be the item] but the item is not there.

**Comment by SlayksWood** [comment]
dup #15472
