### ISSUE TITLE
Second tooltip in a chat message cant be hovered over

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15628]
![image](https://user-images.githubusercontent.com/3536496/78733740-228cd200-78fb-11ea-8540-cb50ece7d2ca.png)
Cant hover 'the dude' in this one.

**Comment by johnkslg** [comment]
Actually sometimes it works and sometimes it doesnt, and seems to happen on chat lines with only one tooltip. Not sure what's going on.

**Comment by SlayksWood** [comment]
still an issue:
https://drive.google.com/file/d/19u0013s0-iUZJ8wanUNVBu2uUo9SB2Pk/view?usp=sharing

**Comment by mirasrael** [comment]
Seems fixed on last staging.
