### ISSUE TITLE
Offset doomsay clock so its below the meteor, not blocking it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15620]
![image](https://user-images.githubusercontent.com/3536496/78731495-beffa600-78f4-11ea-9a45-7371ba3f7585.png)
This used to work and it somehow got broke.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/80076164-70891300-8554-11ea-80e0-9eb762e89ffa.png)
