### ISSUE TITLE
[0.9.0 staging-1503] Labor requirements for specialty in some tooltips can confused players

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15639]
Step to reproduce:
- take masonry specialty.
- so I have Masonry 1. Look at labor tooltip in available recipe, for example, Mortared stone:
![image](https://user-images.githubusercontent.com/45708377/78755160-64f8f200-7981-11ea-92c3-5b90c9d92419.png)
- seems all right, but now look at labor tooltip in locked recipe, for example, Mortared stone bench. It requires Masonry 3:
![image](https://user-images.githubusercontent.com/45708377/78755385-b903d680-7981-11ea-9847-7fc6e928a888.png)
- So this tooltip said that I need Masonry to add labor, and that I don't have Masonry. But it's wrong.
We need to slight change this tooltip:
![image](https://user-images.githubusercontent.com/45708377/78755744-57903780-7982-11ea-8051-338591c27084.png)

We also need to change recipe tooltip with same way:
![image](https://user-images.githubusercontent.com/45708377/78756310-4136ab80-7983-11ea-8c8a-4229814f1b31.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/78772492-7e5a6800-799a-11ea-825e-e7ad2eae2119.png)
![image](https://user-images.githubusercontent.com/475445/78772528-8b775700-799a-11ea-9319-3bc7b285b11d.png)
