### ISSUE TITLE
[0.9.0 staging-1503] Missing tooltip for players with a specialty

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15637]
![image](https://user-images.githubusercontent.com/45708377/63585094-ffe5bd00-c5a6-11e9-9f98-b2ab080b266d.png)
see this #12509

**Comment by trickenso** [comment]
Confirming run into this in 9.0 Staging-1538

**Comment by MarkZaytsev** [comment]
Seems it is already fixed
![ss (2020-05-13 at 06 42 42)](https://user-images.githubusercontent.com/50739566/81808238-9ef18100-9549-11ea-8c6f-4d665acbae33.jpg)

**Comment by trickenso** [comment]
It's working in 1542, but only when you hover over the title, not over the player icons.

Title hover:
![image](https://user-images.githubusercontent.com/48172405/81814406-a94b5500-9520-11ea-8c12-d1377b800b0d.png)

Icon hover:
![image](https://user-images.githubusercontent.com/48172405/81814578-db5cb700-9520-11ea-9419-9c57e67285dd.png)


I suspect this is what Slayks means - in 8.3 tooltip happens when you hover over the icons, too.

**Comment by serpopov** [comment]
I think it would be better to remove tooltip from the title then? @SlayksWood

**Comment by trickenso** [comment]
It is useful to be able to see information about the specialties from this screen, as well as which players have taken them - it aids in decision-making. Exactly how it is presented is a design question, and the current tooltip shows all the useful information.

It is just a bit disorientating if you are used to hovering over the player icons in 8.3, or if you hover over them to see what they mean, and have no tooltip.

**Comment by SlayksWood** [comment]
This 2 tooltips were merged to 1. So I  should to see this tooltip if I mouseover in any green zone, not only icon or specialty name:
![image](https://user-images.githubusercontent.com/45708377/81902993-b5d7b800-95c9-11ea-9f79-29785412c649.png)

**Comment by MarkZaytsev** [comment]
Aligned to the right side to provide option have clear look on everything that is written in the specialty slot. For example 7 different user icons with players amount for each level in this specialty.
Also keep in mind that localized titles might be longer.
Also it fits overall style in dialog - professions have tooltip to the right too.
![ss (2020-05-14 at 05 57 22)](https://user-images.githubusercontent.com/50739566/81926679-8302e380-960c-11ea-8082-dd1d34ac9aef.jpg)
