### ISSUE TITLE
[0.9.0 Staging-1501] Can't rearrange production queue

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15633]
It's a feature a number of people have been talking about - it would be really beneficial to be able to rearrange the production queue. For example, you might have a large production order in a Jaw Crusher but get some small amount of new ore you want to crush right away. You can't pause existing orders and if you cancel the orders you'll lose your calories that you already laboured. Same if you need to make some one-off item during a large production run. It would be nice to be able to rearrange the production queue to address such issues.

**Comment by SlayksWood** [comment]
dup #14991
