### ISSUE TITLE
[0.9.0 Staging-1501] Blast furnace can't fetch quicklime from a storage chest

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15644]
I put my quicklime into a storage chest to save some stockpile space. However, my blast furnace was unable to fetch the quicklime from that chest, even though it was its top priority.

**Comment by elfl0rd** [comment]
Work for me.
Video? Screenshots? Save?
![20200408115722_1](https://user-images.githubusercontent.com/4980243/78765135-40584680-7990-11ea-8bf7-8c0a1e3e7cdc.jpg)
![20200408115736_1](https://user-images.githubusercontent.com/4980243/78765138-40f0dd00-7990-11ea-9846-5960833fae18.jpg)
![20200408115803_1](https://user-images.githubusercontent.com/4980243/78765146-42baa080-7990-11ea-89cb-886972e25e38.jpg)

**Comment by ThePiachu** [comment]
Test server. It also had problems fethching coal. It might have something to do with:
- Blast furnace is on my property, another player was authed to access thing on the land, they started the job
- I think it may have something to do with linked inventories - I think by default all inventories are turned off when you're using something on another player's property, so they have to be re-linked?

**Comment by Engimage** [comment]
Piachu every table has linked inventories unique to every player. So the player who started the order does specify inventories that are linked to it. If you change links it will only effect orders that you own.

**Comment by ThePiachu** [comment]
Yeah, I think it's working as intended now that I think about it with that feedback.
