### ISSUE TITLE
[0.9.0 Staging-1501] Can't hide tasks from the toolbar

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15648]
I tried dismissing / hiding a task from the toolbar by pressing the lower "x":

![image](https://user-images.githubusercontent.com/964559/78765785-51c43300-793d-11ea-9f61-e0f5bc767c0a.png)

That just made my character rotate their view to face where the job was being performed. The "x" on the top is for cancelling the job remotely. I can't find a way to hide those.

**Comment by SlayksWood** [comment]
dup #15587
