### ISSUE TITLE
0.9 Multiplication of barrels in epoxy\plastic, etc.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15646]
The output does not take into consideration the presence of the module (and talent).
![изображение](https://user-images.githubusercontent.com/4980243/78764190-dbe8b780-798e-11ea-9a7b-08999edae6be.png)

**Comment by SlayksWood** [comment]
Only talent, with module all's right.
With oildrilling Upgrade and talent
![image](https://user-images.githubusercontent.com/45708377/78772061-d6dd3580-7999-11ea-94d6-c566fdfa8868.png)

Without module:
![image](https://user-images.githubusercontent.com/45708377/78771707-4acb0e00-7999-11ea-9b08-98959d4ba159.png)
modern upgrade1:
![image](https://user-images.githubusercontent.com/45708377/78771774-62a29200-7999-11ea-8699-e5730af3fdc3.png)
modern upgrade3:
![image](https://user-images.githubusercontent.com/45708377/78771832-7948e900-7999-11ea-9beb-11e499a068bf.png)
oildrilling Upgrade:
![image](https://user-images.githubusercontent.com/45708377/78771895-92519a00-7999-11ea-8521-8caeda146f9d.png)

**Comment by elfl0rd** [comment]
lol, my bad :) it's mirasrael "Craft Resource Modifier" setting. But yes, talent should be fixed too.

@mirasrael can you look? As i think we need something to support this.

**Comment by mirasrael** [comment]
Now Resource Modifier and Talent applies to dynamic output values (like Tailings and Barrels).
