### ISSUE TITLE
[0.9.0 staging 1501] Doors going missing after update

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15655]
It seems some doors have gone missing after the latest update, I had 2 mortared stone doors in my base on a claim go missing, Sunlight also mentioned a door had gone missing.

Other doors that were placed at around the same time have not gone missing.

**Comment by zajcom** [comment]
Hewn log doors also missing. One was created 1 day, few of them week ago. Doors was located on my farm.

**Comment by SlayksWood** [comment]
Intented behavior for Hewn log door, we rename it to Hewn door and it should be deleted after migration(we will take this into account when people will migrate their world from 0.8.3)
But we don't change Mortared stone doors.
@MishkaFur 
Did you have 2 Mortared stone door? or maybe you had 2 Hewn log doors?
Did you have 2 Mortared stone door? or maybe you had 2 Hewn log doors?

**Comment by MishkaFur** [comment]
It was for sure Mortared stone door due to myself being masonry.

**Comment by SlayksWood** [comment]
@MishkaFur Can you provide some screenshots? where were these doors located? Maybe they were overlap with something? We fixed Occupancy for mortared stone door, so if you place something in their position they can be deleted.

**Comment by WeaselDog** [comment]
We made some changes to doors earlier in the playtest that likely caused this. It should no longer be an issue now but please let us know if it happens again.
