### ISSUE TITLE
[0.9.0 staging-1503] Avatar and environment can disappear in 3rd person view.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15656]
![2020 04 08 Avatar can disappear in 3rd person view](https://user-images.githubusercontent.com/45708377/78785623-22024300-79b0-11ea-941e-1587ae4861ba.gif)
after this changes https://github.com/StrangeLoopGames/Eco/pull/5867

**Comment by johnkslg** [comment]
Cant repro this, can you attach level?

**Comment by SlayksWood** [comment]
> Elements of the player/truck occasionally seem to vanish, was not happening pre 1504, game has been restarted and cache verified.
> 
> is VERY dependant on where camera angle is looking
> 
> ![image](https://user-images.githubusercontent.com/61889138/78934381-bbaa1d00-7aa2-11ea-97dd-6108518d7372.png)
> 
> Shovel vanishes
> ![image](https://user-images.githubusercontent.com/61889138/78934416-c8c70c00-7aa2-11ea-82a2-db1d46a87924.png)
> 
> Shoes vanish
> ![image](https://user-images.githubusercontent.com/61889138/78934433-d41a3780-7aa2-11ea-96cd-12c77752f52f.png)
> 
> All items in truck vanish (its mostly got stone roads and some food in it (crates)
> ![image](https://user-images.githubusercontent.com/61889138/78934504-f14f0600-7aa2-11ea-95c5-b035250d7bf9.png)
> 
> Body of truck vanishes
> ![image](https://user-images.githubusercontent.com/61889138/78934525-ff048b80-7aa2-11ea-850f-30839008c513.png)
> 
> ??? my hips vanish (Am guessing it is just the shorts texture)
> ![image](https://user-images.githubusercontent.com/61889138/78934575-13488880-7aa3-11ea-9954-1073293f75d6.png)
> 
> Log file as a .zip because it was 8MB
> [invisible bits.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4458317/invisible.bits.zip)

**Comment by SlayksWood** [comment]
> Perhaps @elfl0rd but it was not my entire body only shovel, shoes and the shorts texture it seems n then bits of the truck, also does same on the steam truck with bits of it vanishing.
> 
> Seems to mostly happen if you are in third person view, go into a vehicle, move the vehicle then get out.
> 
> ![image](https://user-images.githubusercontent.com/61889138/78936160-f19cd080-7aa5-11ea-8ebc-a893a750d43a.png)

**Comment by SlayksWood** [comment]
So I find reprosteps for avatar:
- should be in 1st person view.
- place truck:
![image](https://user-images.githubusercontent.com/45708377/79145981-41dba180-7dca-11ea-813d-8e55db8713bf.png)
- sit in truck:
![image](https://user-images.githubusercontent.com/45708377/79145998-46a05580-7dca-11ea-8eb2-118d743ea381.png)
- change view to 3rd person:
![image](https://user-images.githubusercontent.com/45708377/79146005-4bfda000-7dca-11ea-99d3-7b9c5a2088d1.png)
- exit from truck:
![image](https://user-images.githubusercontent.com/45708377/79146018-528c1780-7dca-11ea-99f7-aecad75423a9.png)

**Comment by johnkslg** [comment]
@mirasrael could this be related to culling changes? My avatar creations should only affect things with foliage tag, so I think it's something else.

**Comment by SlayksWood** [comment]
Second way to reproduce:
- take drill in 1st person view.
- start drilling, during drilling press F5(3rd person view)

**Comment by mirasrael** [comment]
@johnkslg culling does nothing with avatar parts. It only affects plants for now.

**Comment by mirasrael** [comment]
Seems like CameraFOVFudge did't work correctly for some reason.
