### ISSUE TITLE
0.9-1503 "Hide project" button float without targeting

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15650]
![изображение](https://user-images.githubusercontent.com/4980243/78768841-308f3100-7995-11ea-8358-59180556d48f.png)
![изображение](https://user-images.githubusercontent.com/4980243/78768867-36851200-7995-11ea-909f-3cd594d5e196.png)

**Comment by SlayksWood** [comment]
you lost part of UI:
![image](https://user-images.githubusercontent.com/45708377/80940649-15bfa900-8de9-11ea-950c-3e04e5896782.png)
