### ISSUE TITLE
Targeting stuff across borders doesn't give wrapped location

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1565]
![image](https://cloud.githubusercontent.com/assets/774628/26737392/c2b25504-477e-11e7-95fa-6255c109f730.png)
should say 2, not 1002

**Comment by MarjieAVolk** [comment]
Waaaait, that display shows the targeting position and not your own position?

**Comment by NafenX** [comment]
When you're not targeting anything it's white and shows your position. Whenever you're targeting something it's blue and shows target position

**Comment by MarjieAVolk** [comment]
TIL
