### ISSUE TITLE
0.9 broken logic for "stars" marker at doors

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15654]
Just look
T1 door (e.g. hewn door) - 1 star
T2 door (e.g. lumber) - 2 star
no T3 door with markers. (corrugated steel door is garage, and not use this layout).
T4 door (ashlar, framed glass, etc) - 3 star.
![изображение](https://user-images.githubusercontent.com/4980243/78774735-c62ebe80-799d-11ea-904b-5215882a49a1.png)

**Comment by SlayksWood** [comment]
Stars should not mean material tier.
For other furniture
mortared, hewn - 1 star
lumber - 2 star
ashlar, composite - 3 star
adorned ashlar  - 4 star.
Seems intented.
can see here #14716

**Comment by elfl0rd** [comment]
for other furniture maybe, but absolytely not for doors.
Remove stars from doors or change stars number.

**Comment by elfl0rd** [comment]
@keegan-o this is intended behavior for doors?
t-1 = 1 star, t2 = 2 star, t4 = 3 star?

**Comment by SlayksWood** [comment]
I gave you sense:
> Stars should not mean material tier.
For composite it's 3 stars.

**Comment by elfl0rd** [comment]
but doors is not furniture, doors _have_ tiers.

**Comment by keegan-o** [comment]
Lots of updates to tier designations of world object icons for doors and signs. Doors now follow a 0 star = t1, 1 star = t2, 2 stars = t3, 3 stars = t4 which makes them consistent with themselves and matches them up with high tier ashlar/composite world object tier designations. Also means we have room for another higher tier later on which is something I wanted to preserve particularly in the case of doors and building materials which contribute to building tier.
