### ISSUE TITLE
0.9 Crushed slag is not displayed on shovel

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15652]
![изображение](https://user-images.githubusercontent.com/4980243/78771856-836ae780-7999-11ea-9c86-dc8bc6c80173.png)

**Comment by beastyn** [comment]
Stiil an issue in 1554
![bandicam 2020-05-19 16-41-22-329](https://user-images.githubusercontent.com/27898520/82322537-1adb4580-99f0-11ea-8eab-1ff44d4204af.jpg)

**Comment by keegan-o** [comment]
fixed in staging
![image](https://user-images.githubusercontent.com/14983165/82954834-5f239400-9f62-11ea-97fa-763c8c18b1cd.png)
