### ISSUE TITLE
Missing icons: Dirt Road & Executive Actions

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15667]
We need two different icons:
- Dirt Road for "Look at block description"
- Executive Actions for Ecopedia tab

Related issue: https://github.com/StrangeLoopGames/EcoIssues/issues/15661

**Comment by RobertMangano** [comment]
dirt road icon is on Ui_icons_03 icon sheet

**Comment by RobertMangano** [comment]
and we can probably reuse performexecutive action icon for executive actions
![performexecutiveaction](https://user-images.githubusercontent.com/26705633/81263105-6dc50c80-9082-11ea-8577-bafcb991e49d.jpg)

**Comment by RobertMangano** [comment]
Icon is made but I cannot see it in the unity eco scene in items

**Comment by beastyn** [comment]
1555
Don't see the changes for the dirt road icon. Can you check if SVN was updated correctly?
![bandicam 2020-05-20 10-23-47-038](https://user-images.githubusercontent.com/27898520/82408239-a6061b00-9a84-11ea-868d-182a521b551f.jpg)
![Uploading bandicam 2020-05-20 10-23-48-120.jpg…]()

**Comment by RobertMangano** [comment]
dirt road icon looks like the top of the road in the those screenshots, I can edit it to have more contrast, I will update the icon sheet

**Comment by WeaselDog** [comment]
@RobertMangano Thanks but it is fine. It just wasn't implemented properly in code.
