### ISSUE TITLE
[0.9.0 staging-1504] Can't close command line if server didn't start successful.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15669]
I need to use Task Manager:
![image](https://user-images.githubusercontent.com/45708377/78860783-b82f7b00-7a3b-11ea-9b7c-c9c401a35c3b.png)
I also can't break  server starting if I started it by misclick.

**Comment by mirasrael** [comment]
Now server will auto-close on exception.
If you started server by miss click then there is still risk of data corruption if you terminate it during startup. Many applications works with way - preventing you from shutdown until they go into safe phase and allow to graceful shutdown. So it is working as intended.
