### ISSUE TITLE
[0.9.0 Staging-1501] First person view with an empty hand makes your third person items on backpack disappear

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15665]
When you are in first person view with an empty hand and switch over to third person view, items don't display on your backpack until you switch over to a non-empty hand.

1) Version
[0.9.0 Staging-1501]

2) Steps to reproduce
- Have items in your toolbar that appear on the backpack
- Check in third person view - they do appear
- Switch to first person view, select empty hand
- Go to third person view
- There are no items displayed on your backpack until you switch away from your empty hand

Video: https://youtu.be/oQsCCkq209c

3) Expected behaviour
Items should display in third person view regardless of an empty hand.

4) Actual behaviour
Backpack appears empty in third person view, despite there being items in the toolbar.

**Comment by SlayksWood** [comment]
dup #12690
