### ISSUE TITLE
[0.9.0 staging 1504] Elements occasionally disappear if near a truck

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15679]
Elements of the player/truck occasionally seem to vanish, was not happening pre 1504, game has been restarted and cache verified.

is VERY dependant on where camera angle is looking

![image](https://user-images.githubusercontent.com/61889138/78934381-bbaa1d00-7aa2-11ea-97dd-6108518d7372.png)

Shovel vanishes
![image](https://user-images.githubusercontent.com/61889138/78934416-c8c70c00-7aa2-11ea-82a2-db1d46a87924.png)

Shoes vanish
![image](https://user-images.githubusercontent.com/61889138/78934433-d41a3780-7aa2-11ea-96cd-12c77752f52f.png)

All items in truck vanish (its mostly got stone roads and some food in it (crates)
![image](https://user-images.githubusercontent.com/61889138/78934504-f14f0600-7aa2-11ea-95c5-b035250d7bf9.png)

Body of truck vanishes
![image](https://user-images.githubusercontent.com/61889138/78934525-ff048b80-7aa2-11ea-850f-30839008c513.png)

??? my hips vanish (Am guessing it is just the shorts texture)
![image](https://user-images.githubusercontent.com/61889138/78934575-13488880-7aa3-11ea-9954-1073293f75d6.png)

Log file as a .zip because it was 8MB
[invisible bits.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4458317/invisible.bits.zip)

**Comment by elfl0rd** [comment]
maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/15656

**Comment by MishkaFur** [comment]
Does not seem to do it instantly, something appears to trigger it and once its triggered happens even if not near a truck but I believe truck IS the cause (happens with anything that makes the camera zoom in/move)

GPU settings just incase, Nvidia GTX 1660 and Windows 10
![image](https://user-images.githubusercontent.com/61889138/78935328-725acd00-7aa4-11ea-82b3-f1700b0e3eb7.png)

**Comment by MishkaFur** [comment]
Perhaps @elfl0rd but it was not my entire body only shovel, shoes and the shorts texture it seems n then bits of the truck, also does same on the steam truck with bits of it vanishing.

Seems to mostly happen if you are in third person view, go into a vehicle, move the vehicle then get out.

![image](https://user-images.githubusercontent.com/61889138/78936160-f19cd080-7aa5-11ea-8ebc-a893a750d43a.png)

**Comment by SlayksWood** [comment]
merged to #15656
