### ISSUE TITLE
Password input field should display selected input language

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15677]
This is annoying issue for all non-english players.
You cannot see windows lng panel in fulscreen application, and you cannot see text you enter.

p.s.
Password visibility selector can be nice addition and temporary solution.
![1490793853-user-interface15_82360](https://user-images.githubusercontent.com/4980243/78918704-79c8a900-7a99-11ea-9bc1-625b166a0cdd.png)
![1490793864-user-interface16_82335](https://user-images.githubusercontent.com/4980243/78918701-79c8a900-7a99-11ea-80c6-1020eaa6f4a8.png)

**Comment by SlayksWood** [comment]
dup #15352
