### ISSUE TITLE
[0.9.0 Staging-1501] Can't host a world

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#15676]
Version [0.9.0 Staging-1501]

Tried to host a world couple of times and it gets stuck here for ever
![Untitled](https://user-images.githubusercontent.com/62566059/78914624-5864be80-7a93-11ea-9cd1-4ab7011c4b0b.jpg)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4457244/Player.log)

**Comment by MishkaFur** [comment]
Can you manually load ecoserver.exe via a cmd prompt and see if it shows an error

It will be in your steamapps folder under the Eco folder, hold shift and right click open cmd prompt (or powershell if so type in cmd) then type ecoserver.exe

**Comment by Xao22** [comment]
looks like if i start a server from ecoserver it work and i can connect to it

**Comment by beastyn** [comment]
I didn't have problems with creating the world from the client. 
Can you check if you can launch the world after cleaning and redownloading Config folder?

**Comment by Xao22** [comment]
i deleted the entire game plus files from locallow couple a times,i have no ideea why it doesn't work from client

**Comment by IcedForge** [comment]
Are you still having this problem?
If so you can reopen this issue and post fresh player logs and server logs after trying to start it.
Also include a directx diagnostic file if possible by using windows key + r ( to run) dxdiag and save information and upload the saved .txt file here.
