### ISSUE TITLE
(source text) - Togggle

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15689]
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#169328

Typo or intended?

**Comment by beastyn** [comment]
@gzatravkin 
seems to be from you
![unknown (12)](https://user-images.githubusercontent.com/27898520/79827773-a4c7cc80-83b8-11ea-8827-f5f3d5292483.png)
