### ISSUE TITLE
Vehicles should save vertical coordinate at not-loaded chunks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15688]
Just look at the difference in behavior between player and vehicles in not-loaded chunks.
The player continues to move on the flat.

Please take a look at whether it is possible to give vehicles a similar behaviour.

@mirasrael (debated in discord).

**Comment by IcedForge** [comment]
This is still a pretty rampant issue (29/7) - 0.9.0.0 beta staging-stable-8
vehicles keeps "spawning" in mines/caves randomly on logging in / loading in areas.

**Comment by SlayksWood** [comment]
> I decided to build my house on the ocean not to have to deal with digging up dirt or levelling the ground. However, I still have to park my truck on solid ground, otherwise I'd have to fish it out from the bottom of the ocean on regular basis. It seems that when vehicles are loaded into an area (possibly after server restart or what have you) they have a tendency to clip downwards through the floor. I've even seen this happen on solid ground, but in that case the vehicle just looped back around from the bottom of the map back on top.
> This is also an issue in the mines where carts would randomly teleport to different levels and so on.
> It would be nice for the vehicles to be a bit more stable in the game.

**Comment by TwixterZ** [comment]
Tested this fix in 9.4 Staging 2008 by putting vehicles in a building on the ocean

No problem observed

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

Closing as fixed.
