### ISSUE TITLE
[0.9 Staging-1504] Government items marked Invalid don't allow preview of tabs

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15694]
1. Version
0.9 Staging-1504
2. Steps to reproduce.
Place a Government item that has active elements in an invalid room
3. Expected behavior.
Be able to see the \invalid> laws, demographics etc.
4. Actual behavior.
Denied access to these tabs (Civics not clickable in below example)
The same applies to tables with pipes etc. that are invalid due to fuel or rooms etc.
![image](https://user-images.githubusercontent.com/54982803/79010904-d213af80-7b5a-11ea-87a3-abdc9e832b69.png)

**Comment by beastyn** [comment]
Its intended, as you can't work with objects while a room is invalid.
You can see all relevant information in the Government (L)
Do you need this tab for some particular reason?
