### ISSUE TITLE
[0.9.0.0 beta staging-1506] Admin Commands for civic

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#15695]
Hello,
 as the civic is become quite heavily and it can be very quick to do some missconfiguration, it is very important for server admins to be able to have admin commands removing laws without destroying the whole constitution. right now the only way to disable a law by admin is to destroy the constitution or pick up the cort and wait the 20min. by doing this you would lose as well the other laws in the court. 
I would recommend to add several admin commands to be able to remove all civic objects like laws, elections, titles and so on by admin command.
I have created by exident a law which prefent me to change it again, so i was lost.

**Comment by Alteraner** [comment]
by the way, remove the cort and wait 20min wont work, as it only disable the law, till the court is been placed again, so there is currently no way to remove an existing law if you are not able to access the court by law.

**Comment by beastyn** [comment]
Actually, you can delete a law in the court. And then admin can use /civics winelection ElectiomID for finishing the process without election.

Or do you want to remove all of them at once? All the objects and so on?
I don't actually understand the reason.
If you need to remove a law, or any civic object, vote for it (or what do you have in your government logic for it).

I don't think that anyone should have power to delete all the civics objects at once on the LIVE server with some Government structure which was created by some reason, with voting and so on.

If you want admin to be able to acces the court by law, you should add this condition to the government processes.

@johnkslg What do you think?

**Comment by Alteraner** [comment]
Hello,
 what I'm looking for is an admin command like "/civic removelaw ID". 
In my point this is essential. Let me try to explain it.

The new law system is very powerfull. I realy like it. But for users not realy expiriance in it, it is although some riski to do something which cannot be reverted. Typically once you have established a governance you are going to protect the system to be destroyed. For example you are going to create a law which can only be changed by a person, group or what ever. if you do not setup this law carefully you can end up it, that no one can change a law any more. then you need the admin power to remove this "wrong" law to get back access.
Right now you only can temporarry deactivate these "wrong" law, by pick up the court, but you cannot delete the respective law as by when you place the court, the law becomes active again imidiatly.
i expect several demands in these enviroment by the admin to remove an existing law with admin command.

hope i was able to describe the issue well and why in my point this is not quite low priority. anyway i assume the implementation is quite easy and can be done within minutes instead of hours.

**Comment by johnkslg** [comment]
This command exists! It's under /objects.
I've added a more detailed description to the objects command to make this clear:

![image](https://user-images.githubusercontent.com/3536496/79286368-33968f80-7e75-11ea-8980-522c5562a8f9.png)

Made some subcommands admin accessible which were previously dev.

**Comment by Alteraner** [comment]
working fine. thanks.
