### ISSUE TITLE
[0.9 Staging-1504] Work party with a skill reward doesn't give you claims 

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15690]
Normally, when you learn a skill, you get 5 claim papers. However, when you learn a skill through a work party, you learn the skill but don't get the claims.

1) Version
0.9 Staging-1504

2) Steps to reproduce
- Start Research at the table
- Put up a Work Party on the Contract Board for completing the Research, awarding the skill on contribution
- Contribute to the project yourself?
- Let others contribute to the project?
- When the Work Party is complete, you learn the skill, but don't get the claim papers

3) Expected behaviour
You should get claim papers along with the learned skill, regardless where it comes from.

4) Actual behaviour
Learning a skill through a Work Party gives you the skill, but not the claim papers.

PS: Can an admin on the test server give me like, 20-25 claim papers I missed out on, 5 to Scott, and not sure who else was affected.

**Comment by ThePiachu** [comment]
Rev mentioned he got the papers as a contributor. I searched all my inventories and I couldn't find them.

Also - apparently the person that initiated the work party is not credited as the person that discovered the skill. One of the contributors got it. Is this intentional behaviour? Would be nice to have a deterministic order of who learns those skills - whether it would be the highest contributor, or the person that started it.

**Comment by ThePiachu** [comment]
Scott mentioned he didn't get the claims for contributing to Smelting research.

**Comment by johnkslg** [comment]
When learning a skill through the workparty, it now gives you the claims when you learn a skill.
Also, if your inventory is full then it gives them to your void storage. This is temporary till we do a rework of how property works in a future version.  

Made the gaining of knowledge sort by the person who created the work order, so they become the discoverer.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/79279058-02f92a80-7e62-11ea-9686-4d62850bf84c.png)
