### ISSUE TITLE
Verify no allocations per-frame from TransparencyManager

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15691]
Use Unity profiler to examine allocations, marking before/after with tags to see it in visualizer: https://docs.unity3d.com/ScriptReference/Unity.Profiling.ProfilerMarker.html

If there are allocations, can narrow them down with additional markers.  
Use plugin tools to detect allocations (Rider, or a tool Simon has)
Ask alex if you need help identifying/removing any allocations

**Comment by johnkslg** [comment]
If youre going to replace Linq, use one of the linq libs posted in Eco code (Simon has some links)

**Comment by johnkslg** [comment]
Cratesmith is a friend who made one

**Comment by olegshegai** [comment]
Here is a gif:
![0420-transp-allocs](https://user-images.githubusercontent.com/56091594/79753619-e2781700-831e-11ea-8dea-f8a2e3469730.gif)

Frame with the both loops:
![frame 52](https://user-images.githubusercontent.com/56091594/79753705-05a2c680-831f-11ea-807a-8b628b1c9dc4.png)

The only realtime allocations are `List` reszing, but the lists are static and the change is semi-permanent (utill the user adds more markers beyond the current cap), thanks to @mirasrael for the explanations
![frame 29](https://user-images.githubusercontent.com/56091594/79753667-f6237d80-831e-11ea-8aee-ec269da4e7f1.png)
