### ISSUE TITLE
All characters allowed in fields

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#15699]
We need webcode that permits any username
much of it dies when the user has a restricted character in its name

Seems all fields dont support all characters (like Cyrillic characters). For example: email field in password reset, login.

Login form with Cyrillic characters goes to this error: https://gyazo.com/4d1ecb51c2bfc82a459af426b567f415

**Comment by denysaw** [comment]
Em... R U sure all fields should support Cyrillic?! Email?! Password? =))) I'll see that for the first time in my life... Only name (even not login) may be Cyrillic. Login should be translited to latin. This is how all the world does in web. No russian logins in DB, and surely not russian email and passwords :D We could translit russian on the fly on login attempts, but on account page he'll see his translitted latin login. For storing russian username we should use another, less important field.

**Comment by rainfarmer** [comment]
OK sounds good. i think you know better then me the standard on web for this. youre call
