### ISSUE TITLE
[0.9 Staging-1504] Executive Actions have no details

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15692]
1. Version
0.9 Staging-1504
2. Steps to reproduce.
Place Executive Office, draft a new Action on Each Citizen and Perform Action
3. Expected behavior.
Be able to view the details of the action proposed to make a decision about voting
4. Actual behavior.
Nothing on website:
![image](https://user-images.githubusercontent.com/54982803/79008879-35e7a980-7b56-11ea-8f7a-1a02cfbcacc8.png)
Notifications might have details in the [Perform 1 actions], but this does not rollover:
![image](https://user-images.githubusercontent.com/54982803/79008943-557ed200-7b56-11ea-9866-f40cce870b11.png)
Nothing shown in Government (L) tab:
![image](https://user-images.githubusercontent.com/54982803/79008975-6fb8b000-7b56-11ea-9a75-218f6b010210.png)

**Comment by beastyn** [comment]
Lets check if we have info in API. Maybe its just a web part. Tell if not, please

**Comment by beastyn** [comment]
I actually have
![bandicam 2020-04-13 09-47-48-512](https://user-images.githubusercontent.com/27898520/79092913-e1b61280-7d6b-11ea-8d84-ee1ac1741211.jpg)
@NN-Mike what browser do you use?

**Comment by beastyn** [comment]
Also, check please with new update

**Comment by beastyn** [comment]
Reopen if happens again
