### ISSUE TITLE
Support contact form bug

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#15706]
support form is not giving notification after sending and may not be sending email

**Comment by beastyn** [comment]
Still nothing about sending on user ui side
It just stays
![bandicam 2020-04-22 09-57-09-945](https://user-images.githubusercontent.com/27898520/79942188-b1632800-847f-11ea-872f-2a6f16291860.jpg)
 like this

**Comment by rainfarmer** [comment]
it says 'Sending' on the submit button.
we can add a notification too

**Comment by denysaw** [comment]
Hm, I was fixing that. `Sending...` was changed to a la `Sent successfully`. Will check again.

**Comment by denysaw** [comment]
Totally refactored.
