### ISSUE TITLE
Invites not working

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#15705]
QA not receiving invites or success email.

**Comment by beastyn** [comment]
Please, check the link in the email with invitation.
I was using mailinator and it could not form the correct link.
For the phrase
"Click here to setup your account (or you can register normally using the same email address)."
Click here has
https://www.mailinator.com/user/registration/invitation_registration/b75ea690ca4c755dad896f93fead3395

**Comment by denysaw** [comment]
@SlayksWood Done, could be tested on developland.

**Comment by beastyn** [comment]
I have got invites but something is strange with the links
1) If user already has an account a link in the invitation letter will be broken (so does not lead me anywhere)
2) If user do not have an account a registration link will lead me to this strange page
![bandicam 2020-07-28 17-04-31-679](https://user-images.githubusercontent.com/27898520/88664050-e8d41700-d0f5-11ea-8d28-26467f75bae3.jpg)

**Comment by denysaw** [comment]
`1st point (broken link)` fixed. Now just 2nd left (will be made by @j3fffff).

**Comment by j3fffff** [comment]
added styling.
can you update it to also require the checkboxes and captcha that normal registration has:

- [ ] captcha
- [ ] over age of 13
- [ ] eco newsletter
![image](https://user-images.githubusercontent.com/7343272/92520799-0904f480-f1d1-11ea-9c65-33177b23298a.png)

**Comment by beastyn** [comment]
Then its not for review for now.

**Comment by denysaw** [comment]
@beastyn Ah, this one is also for test on `staging`.
