### ISSUE TITLE
[0.9 Staging-1506] Skid steer block preview cached from hammer

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15708]
1. Version
0.9 Staging-1506
2. Steps to reproduce.
i.Pick up a block that has a hammer form, use it/place it into stockpile.
ii.Have a block that has a form in the skid bucket
iii.Get into a skid steer
3. Expected behavior.
Skid steer should show the block type in the bucket for preview to place
4. Actual behavior.
Skid steer preview shows the block that was in the players hand
![image](https://user-images.githubusercontent.com/54982803/79044959-566c3e00-7c00-11ea-89f7-3b3ab7134f5d.png)

**Comment by olegshegai** [comment]
Both skid steer issues fixed 
Thanks, @NN-Mike

**Comment by beastyn** [comment]
Don't see shadowplacement anymore for normal dirt

**Comment by SlayksWood** [comment]
If I place Brick and dirt im Skid Steer thrn I have shadowplacement for brick.
![image](https://user-images.githubusercontent.com/45708377/80942178-d4c99380-8dec-11ea-9c2f-306ca84b4227.png)
I try to place Brick(I assume I should not place it) but I cab't and I don't know why. Maybe add error notification that I can't place this item from skid steer?
