### ISSUE TITLE
0.9-1508 strange behavior while creating save with russian name

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15716]
See.
I enter "Временный" as world name.
And i get this, look at time tab!
![изображение](https://user-images.githubusercontent.com/4980243/79049075-0609d600-7c2a-11ea-9e0d-916a097c4eee.png)
![изображение](https://user-images.githubusercontent.com/4980243/79049082-0dc97a80-7c2a-11ea-80f7-63640d76c09d.png)

**Comment by SlayksWood** [comment]
dup #14174
