### ISSUE TITLE
GI + borders + fire is weird

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1571]
![image](https://cloud.githubusercontent.com/assets/774628/26738756/3594aaea-4784-11e7-9d03-dcd5daa87051.png)
![image](https://cloud.githubusercontent.com/assets/774628/26738765/440ccce2-4784-11e7-9c3d-db4c7f974aef.png)

**Comment by SeanAtr0n** [comment]
behaves as expected when i enter through side door that doesn't cross border

**Comment by metachronism** [comment]
Don't think this is GI - might be the light position of the campfire  (GI doesnt use point lights)
