### ISSUE TITLE
[0.9 Staging-1506] Revising a District resets names to default + incremented number

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15712]
1. Version
0.9 Staging-1506
2. Steps to reproduce.
Create and pass a District at the zoning office
Create a new draft on the existing district
3. Expected behaviour.
Previously assigned names on the original district should remain (with a new number appended to this name to make it unique)
4. Actual behaviour.
All existing districts are renamed to District # and have to be renamed, along with the District Map name: District Map #
![image](https://user-images.githubusercontent.com/54982803/79045699-4f472f00-7c04-11ea-80b4-2043187be5ac.png)

**Comment by beastyn** [comment]
dup #15334
