### ISSUE TITLE
0.9-1508 no specialized error message looks ugly

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15717]
![изображение](https://user-images.githubusercontent.com/4980243/79049219-ec1cc300-7c2a-11ea-8ec5-da7d31b46b29.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79097240-dfea5000-7d67-11ea-97e9-3631dc14b67f.png)

**Comment by beastyn** [comment]
Still need some love here
![bandicam 2020-04-27 14-31-53-262](https://user-images.githubusercontent.com/27898520/80358079-507b8b80-8895-11ea-92c6-85d1b748d06b.jpg)

**Comment by MarkZaytsev** [comment]
Fixed, should be like this
![image](https://user-images.githubusercontent.com/50739566/80378352-bc2a1c80-88c6-11ea-8910-7d5e4211fa72.jpg)

**Comment by beastyn** [comment]
Let's add some paddings on the rop and bottom, please. It's too tight right now.
![bandicam 2020-04-28 15-08-52-648](https://user-images.githubusercontent.com/27898520/80475381-39ef3600-8962-11ea-8856-ac2010b923cf.jpg)

**Comment by MarkZaytsev** [comment]
Added padding. I also increased width to support bigger text size. No reason to keep it short in this position, but bigger text will be easier to read.

![Image](https://user-images.githubusercontent.com/50739566/80564147-37024d00-8a17-11ea-9028-1da38862c753.jpg)

**Comment by johnkslg** [comment]
Looks like its not centered

**Comment by MarkZaytsev** [comment]
I centered it relative to the pages...
![ss+(2020-05-01+at+10 34 31)](https://user-images.githubusercontent.com/50739566/80784094-0bfa3380-8ba6-11ea-9319-642520c785ea.jpg)

Well, I guess you want it to be centered relative to title (window)
![ss+(2020-05-01+at+11 00 39)](https://user-images.githubusercontent.com/50739566/80784098-0dc3f700-8ba6-11ea-888a-7a808dd034e4.jpg)

Done.

**Comment by elfl0rd** [comment]
Maybe better center all relative to pages?
