### ISSUE TITLE
[0.9 Staging-1506]Executive Actions have no option to add a custom description/title

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15710]
1. Version
0.9 Staging-1506
2. Steps to reproduce.
Place executive office, perform new executive action
3. Expected behavior.
Can create a title description for the new action
4. Actual behavior.
Action is automatically assigned a name "Executive Action Election #" with incrementing numbers

![image](https://user-images.githubusercontent.com/54982803/79045229-e78fe480-7c01-11ea-9fcf-a8fbaeb11ebc.png)
![image](https://user-images.githubusercontent.com/54982803/79045290-3fc6e680-7c02-11ea-8547-5bfe321356f9.png)

**Comment by beastyn** [comment]
Yeah, its reasinable to have title and description here too, as we can still vote for it.
@johnkslg what do you think?

**Comment by johnkslg** [comment]
Added a title field to Executive Actions, and made the election title use it.

**Comment by johnkslg** [comment]
Thanks for the suggestion @NN-Mike !
