### ISSUE TITLE
[0.9 Staging-1506] Previous districts remain within the game even when deleted inflating district filter for laws

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#15711]
1. Version
0.9 Staging-1506
2. Steps to reproduce.
Continue creating new districts, or modifying existing ones, the district list continues to grow exponentially.
The worst example is to create a draft on an existing district with several zones, then cancel the draft:
![image](https://user-images.githubusercontent.com/54982803/79045418-e7dcaf80-7c02-11ea-90b1-eef103988baa.png)
![image](https://user-images.githubusercontent.com/54982803/79045454-1eb2c580-7c03-11ea-9e67-088982b6a0d1.png)
3. Expected behavior.
The no longer used districts shouldn't be visible anymore if they are not reference by anything
4. Actual behavior.
When creating a law that references a district, the list continues to display irrelevant districts:
![image](https://user-images.githubusercontent.com/54982803/79045350-8583af00-7c02-11ea-9ffa-13c749fc7624.png)

**Comment by beastyn** [comment]
Steps:
1) Create new district map
![bandicam 2020-04-13 15-47-31-778](https://user-images.githubusercontent.com/27898520/79115078-59049a00-7d9e-11ea-9f23-02a766ca3799.jpg)
2) Create few districts, don't submit
3) Delete draft
4) Create a law and choose condition with districts. Check filter
![bandicam 2020-04-13 15-49-07-015](https://user-images.githubusercontent.com/27898520/79115102-6a4da680-7d9e-11ea-8395-720069835ae5.jpg)

**Comment by johnkslg** [comment]
Fixed a number of issues with this. 
- Districts weren't displaying their suffix (draft, removed, etc) properly.
- Made the world index show entries in ALL states, so you can see drafts/proposed/removed/failed entries in there too.  It always sorts active to be at the top.
- Filter panel should only be showing Active, Proposed, or Draft entries (no removed). 
- If you remove a draft before its become active, it erases the district map and all districts from existence (they will not be listed as 'removed'), UNLESS something else references it, like a law referencing a draft district.  
- If you remove a district that was ever active, it will still be in the record books as 'removed'.
- Fixed this for drafts of civic articles in constitutional amendments, which would have had the same problem. 

![image](https://user-images.githubusercontent.com/3536496/79168977-07f5a580-7da0-11ea-99b0-346943a9cc4d.png)
![image](https://user-images.githubusercontent.com/3536496/79169007-1c39a280-7da0-11ea-9bcf-5d2fdf69fc39.png)


https://github.com/StrangeLoopGames/EcoIssues/issues/15755
