### ISSUE TITLE
[Contracts] If any number is placed in "Depost" it cannot be changed back to zero

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15729]
Version: 0.8.3.3

I'm trying to work around a limitation of the store system. Basically, in an economy I try to base the prices of different items around each other and one item basically has to cost 0.002 each, but of course it can't go that low so I used the contract board to create a contract to put 100 wood pulp into a chest in exchange for 0.2 currency. 

I accidentally clicked + next to deposit, which changed the zero to a 1, but could not change it back down to zero. However, by clicking the item on the contract board, I changed the clause to anything else then back to Payment on completion and that allowed me to have deposit set to zero by not touching anything around it.

**Comment by beastyn** [comment]
Fixed in 0.9
