### ISSUE TITLE
USER ISSUE: Water surface can be distorted

### ISSUE THREAD

**Issue by rhuarc0** [StrangeLoopGames/EcoIssues#15726]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. Construct a road on the surface of water.
2. Dismount it.

**Expected behavior:**
The surface must restore it initial state.

**Actual behavior:**
Instead it creates the Moses effect.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No.

**Comment by beastyn** [comment]
Please provide screenshots

**Comment by NN-Mike** [comment]
I think he means if you replace a water block on the surface with a building material, when you remove the building material the water stays removed. Less visible for single blocks, but 4x4 is quite significant. There is no water refill like other popular voxel games :-P

You need admin commands to refill water blocks at the surface level

**Comment by beastyn** [comment]
In that case I will merge it with #12080

**Comment by redwyre** [comment]
0.9 (I think?) actually has a slightly better water flowing mechanic, so this should be fixed...
