### ISSUE TITLE
0.9-1508 chopping fallen branches show empty message

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15720]
![20200411224331_1](https://user-images.githubusercontent.com/4980243/79053433-fb5d3a00-7c45-11ea-8b65-017b38da3911.jpg)

**Comment by beastyn** [comment]
check with merged PR https://github.com/StrangeLoopGames/Eco/pull/5911
Can be fixed

**Comment by elfl0rd** [comment]
I'm not sure that removing the error message is a good thing.
Maybe it's better to have some kind of "no resources to collect"?
