### ISSUE TITLE
USER ISSUE: pickaxe

### ISSUE THREAD

**Issue by JOSHUASAMPSON** [StrangeLoopGames/EcoIssues#15724]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
hit any rock 

**Expected behavior:**
destroyed the rock

**Actual behavior:**
just keep hitting it and nothing happen

**Do you have mods installed? Does issue happen when no mods are installed?:**
just keep hitting it and nothing happen

**Comment by beastyn** [comment]
Thank you for the report

Please provide log file
Istruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.

**Comment by JOSHUASAMPSON** [comment]
I don't ever remember messaging you guys
