### ISSUE TITLE
[0.9 Staging-1506] Contract Board can only create 18 posts EVER

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15723]
I have been using the Contract Board quite a lot. However, I ran into a weird issue - apparently, I can only create 18 posts ever on a single Contract Board:

![image](https://user-images.githubusercontent.com/964559/79058888-45372780-7c28-11ea-992c-879dbb0afaaf.png)

I'm guessing that's to make sure the contracts are visually represented and so on and you shouldn't have more than 18 of them at the same time, but as it is currently, you can only use it 18 times and then you have to throw it out and get a new one.

1) Version
0.9 Staging-1506

2) Steps to reproduce
- Set up a Contract Board
- Do 18 contracts / work parties on it, complete them
- Try making another contract / work party - get the error

3) Expected behaviour
You should be able to make contracts / work parties if there are less than 18 active posts on the Contract Board.

4) Actual behaviour
You can't make new posts on a Contract Board if you have created 18 of them ever.

**Comment by olegshegai** [comment]
Can't reproduce in latest staging
![image](https://user-images.githubusercontent.com/56091594/79126000-c2d57180-7da7-11ea-8042-93e48c6a4e33.png)

**Comment by olegshegai** [comment]
Oh, found a way to reproduce
