### ISSUE TITLE
Contract: 'unnamed contract' is invalid.

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15728]
Version: 0.8.3.3
Issue: When trying to create contract I get the following error:

Contract: 'unnamed contract' is invalid, must fix or delete before posting another one.

Steps to reproduce: If you place a Question board, and click "Create Contract" but then X out before actually creating it the board is basically broken. Clicking Create contract after will result in the above mentioned error. The only workaround is to remove the board and place it back down, which only the owner can do.

**Comment by beastyn** [comment]
Thank you for your report.
You can look for your unfinished contracts at the right part of the interface. It should have yellow color.
You can open it and delete ot finish

If you don't see it on the right part, you shouls reconnect and it will appera
It will be changed in 9.0
