### ISSUE TITLE
[0.9.0 Staging-1506] Can't chat / tab and do stuff while auto-running in a Truck / Cart

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15732]
When you auto-run in a Truck or a Wood Cart, it stops when you try to chat or tab into inventory. I can't be a reckless driver that texts and drives ;).

1) Version
0.9.0 Staging-1506

2) Steps to reproduce
- Enter Truck
- Auto-run
- Tab - truck stops
- Untab - truck resumes
- Start typing in chat - truck stops
- Send message in chat - truck resumes
- Open chat window - everything is fine
Video: https://youtu.be/3zk5_qUHP34

3) Expected behavior
Truck should continue to drive while you text and drive

4) Actual behavior
Truck stops when you tab or when you're typing in chat

5) Providing Log files
https://mega.nz/file/8EQQFITL#O1JgcSDXX2RX-7NIM3F6u1mCSy8vr1u2dkYX--0NCh4

**Comment by Daniel-Magulado** [comment]
Tested on 9.3 Staging 1929

Appears to be implemented.

Players can now type in chat and check inventory without interrupting the auto drive or autorun.
