### ISSUE TITLE
[0.9.0 staging-1510] Some icon links are broken

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15738]
In districts and 
![bandicam 2020-04-13 14-25-34-589](https://user-images.githubusercontent.com/27898520/79110291-8dbf2400-7d93-11ea-8f19-c27215ab62b5.jpg)

in deed property
![bandicam 2020-04-13 14-32-20-244](https://user-images.githubusercontent.com/27898520/79110318-97e12280-7d93-11ea-9684-85f0da7593c7.jpg)

in court
![bandicam 2020-04-13 14-34-44-278](https://user-images.githubusercontent.com/27898520/79110491-f73f3280-7d93-11ea-9008-9573c32ec2d7.jpg)

Maybe somewhere else

**Comment by SlayksWood** [comment]
> There are some unformatted strings around the Electric Machinist Table modules:
> 
> ![image](https://user-images.githubusercontent.com/964559/79548915-07346c00-804b-11ea-8f47-721d8ee26433.png)
> 
> ![image](https://user-images.githubusercontent.com/964559/79548951-19aea580-804b-11ea-8c06-fc30197ef6df.png)

**Comment by ThePiachu** [comment]
![image](https://user-images.githubusercontent.com/964559/79674489-897e7680-8198-11ea-961f-08a627d79cd2.png)
