### ISSUE TITLE
[0.9.0 staging-1510] Troubles with icons.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15737]
/preset housing:
![image](https://user-images.githubusercontent.com/45708377/79109833-d372f100-7d81-11ea-9158-6470a9054a93.png)
Also strange icon for huckleberry extract:
![image](https://user-images.githubusercontent.com/45708377/79109886-ee456580-7d81-11ea-96f2-2a35cc8def50.png)

**Comment by elfl0rd** [comment]
Also devtool lost their animated icon. (And have strange background too)

**Comment by SlayksWood** [comment]
Fiberglass icon in Filter
![image](https://user-images.githubusercontent.com/45708377/79248162-21701d80-7e84-11ea-85c0-956b75d707c5.png)

**Comment by keegan-o** [comment]
there seem to be some problems with the item baker recently, added
![image](https://user-images.githubusercontent.com/14983165/79504423-b93a4c80-7fe7-11ea-9480-e42dca288455.png)
![image](https://user-images.githubusercontent.com/14983165/79504450-c3f4e180-7fe7-11ea-9b7a-188ce683f0c3.png)

**Comment by keegan-o** [comment]
regarding the doubles in the sheet-- it seems that in many cases the doubles which are not assigned look more correct (have the right background) than the one with the _baked suffix (though they are both baked of course)
![image](https://user-images.githubusercontent.com/14983165/79505645-8bee9e00-7fe9-11ea-82e4-15760c9388b0.png)
![image](https://user-images.githubusercontent.com/14983165/79505658-927d1580-7fe9-11ea-8102-8e4f08ebf395.png)

**Comment by keegan-o** [comment]
Some of the other errors/artifacts are either fixed or different looking in the baked sprites with no _baked suffix as well!

![image](https://user-images.githubusercontent.com/14983165/79505811-d112d000-7fe9-11ea-8187-3c415618cc16.png)
![image](https://user-images.githubusercontent.com/14983165/79505963-0c150380-7fea-11ea-86ee-1070301ae4b8.png)

**Comment by keegan-o** [comment]
Those would be correct I think if not for the grey image of clouds in the background of the entire baked sheet

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/79623201-bb77d600-80cf-11ea-91ed-4c74c45c40d6.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/79623212-cd597900-80cf-11ea-8f5e-548fc8712fba.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/79623238-f5e17300-80cf-11ea-999f-ec225945462d.png)
Got these errors when trying to bake again,

@serpopov We need thorough documentation about how to add new icons, how the whole process is supposed to work now, etc.

For now this has thrown a wrench in all icons for 9.0, and I cannot fix or add things on my own anymore.

**Comment by beastyn** [comment]
@serpopov 
Pipes in Ecopedia have the same icon
And in filter they have copper icon
![bandicam 2020-04-21 15-31-38-535](https://user-images.githubusercontent.com/27898520/79857062-a6a88480-83e6-11ea-9d2f-995b13e00d2c.jpg)
![bandicam 2020-04-21 15-41-42-503](https://user-images.githubusercontent.com/27898520/79857065-a7d9b180-83e6-11ea-9446-a40b6f67da01.jpg)

**Comment by SlayksWood** [comment]
I'll close this issue. After global fixing we will create separate issue for each icon groups.
