### ISSUE TITLE
[0.9.0 staging-1510] "Show only discovered items" button in ECOpedia doesn't work

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15735]
Seems it works only with Election processes.
create new world:
![image](https://user-images.githubusercontent.com/45708377/79106249-cf8fa080-7d7a-11ea-957e-91c4e88c2ae9.png)
![image](https://user-images.githubusercontent.com/45708377/79106265-d4545480-7d7a-11ea-9f14-cbd7a02bec21.png)

**Comment by SlayksWood** [comment]
"Show undiscovered" button doesn't work in Filter too.
- create new world
- place store, press edit sale list:
![image](https://user-images.githubusercontent.com/45708377/79838454-b3fc4980-83bb-11ea-897e-442fcd1a6597.png)
- Show undiscovered off, press add all to selection:
![image](https://user-images.githubusercontent.com/45708377/79838510-cc6c6400-83bb-11ea-922c-ffa615293fc9.png)
- clear
- show undiscovered on:
![image](https://user-images.githubusercontent.com/45708377/79838574-e6a64200-83bb-11ea-98cb-e948f604d610.png)
I assume it has same problem

**Comment by johnkslg** [comment]
Fixed all of the above
