### ISSUE TITLE
0.9-1509 stresstest server crashed with exception

### ISSUE THREAD

**Issue by jaskes** [StrangeLoopGames/EcoIssues#15730]
During stress test server instance crashed with 

`Exception
Exception: AccessViolationException
Message:User attempting to remove district from non-draft district map.
Source:Eco.Gameplay`

Game save and logs are available in attachment.
[Game-2020-04-12-15.24.34.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4467859/Game-2020-04-12-15.24.34.zip)

**Comment by johnkslg** [comment]
A live district could get changed if the user keeps the window open while it changes state. Added some checks for this.
