### ISSUE TITLE
version Newest [Client] Flowerpot Visual Bugs

### ISSUE THREAD

**Issue by JkbcAndArgonSplit** [StrangeLoopGames/EcoIssues#15747]
The Flowers in The Flowerpots somtimes are multipled and stackt makin gthe Frame rate drop and somtimese when you move the flowerpot the Flowers Just stay and dont go away for no reason Those also still have somtimes an hitbox

![20200413170404_1](https://user-images.githubusercontent.com/63599516/79131424-ddf4b100-7da8-11ea-83e9-c5e93e969c99.jpg)
![20200413170522_1](https://user-images.githubusercontent.com/63599516/79131488-fcf34300-7da8-11ea-93f5-10da7540986a.jpg)

**Comment by SlayksWood** [comment]
merged to #12014
