### ISSUE TITLE
[0.9.0 staging-1511] Legislation: icon logic for the laws

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15744]
![bandicam 2020-04-13 15-23-56-893](https://user-images.githubusercontent.com/27898520/79122713-e1406a80-7db1-11ea-9283-e02a9cb518e7.jpg)

So, I have 3 sections. 
I see that I have action-effect icons for all the sections
But only the last one section has only action icon and doesn't have effect icon.

What logic here was intended?
Is there a point to make icons like that but not for all sections near the law title?

**Comment by johnkslg** [comment]
It caps to five icons if there are more than 5 needed.  Maybe we let it go higher? What do you think

**Comment by beastyn** [comment]
@johnkslg 
Is there a reason to show some number of icons if you don't actually show every of them?
If you have 4 sections then you will have like 8 icons?

Im for the first section action icon. Maybe action-effect icon.
