### ISSUE TITLE
[0.9.0 Staging 1506] Adding/Editing districts issues

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15748]
Unable to see the existing districts whilst adding a district, kind of annoying now we can have several district maps going, if I hover over an area with cursor it does say if it is in a district or not though.

It should let me select the districts in the right and I see them on the map I am currently editing nor player property so cannot ensure that a road does not go through someones base.

![image](https://user-images.githubusercontent.com/61889138/79138357-4abd7a80-7dac-11ea-92b1-1802f1e424e7.png)

**Comment by MishkaFur** [comment]
Update........if you select another map whilst editing one, its districts get imported into your one but you cannot tell it has done this until you do Submit.

Waterworks does not have B Road or Otterville in it but they were selected whilst adding the waterworks.

![image](https://user-images.githubusercontent.com/61889138/79151394-3edcb300-7dc2-11ea-830c-5980d42c551b.png)

**Comment by SlayksWood** [comment]
link with #15206

**Comment by gzatravkin** [comment]
It had missing header (which is another issue). It says: press cntr to see selected districts.
So basicly you can switch between editing map and whatever you have selected in right panel.

Works properly last time I check @SlayksWood can you check it?

**Comment by MishkaFur** [comment]
So we can see say player property whilst doing districts now? :D

**Comment by gzatravkin** [comment]
You can draw districts, press cntr (and see properties), realease cntr and continue with drawing districts

**Comment by MishkaFur** [comment]
Nope @gzatravkin holding control whilst in the edit districts does not show me player property

**Comment by gzatravkin** [comment]
Yeah, you right. It worked only for selected for view districts, but not property. I am adding support for it in this PR, soon should be at playtest. 
https://github.com/StrangeLoopGames/Eco/pull/5957
