### ISSUE TITLE
[0.9.0 staging-1511] Missing block description for CharredDeathBlock

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15743]
![image](https://user-images.githubusercontent.com/45708377/79120352-5785a280-7d9b-11ea-9fe3-16738c3cc419.png)

**Comment by SlayksWood** [comment]
also typo in blovk name charreDdeathblock

**Comment by elfl0rd** [comment]
Duplicate of #15661

**Comment by elfl0rd** [comment]
Also not Charred Death, it is Charred Earth
