### ISSUE TITLE
0.9-1511 working water pump interface broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15740]
"personnamehere"
![изображение](https://user-images.githubusercontent.com/4980243/79117632-4e450780-7d94-11ea-8f8a-8cd6c6570702.png)
(need green status, if something red - all ok)
![изображение](https://user-images.githubusercontent.com/4980243/79117657-5dc45080-7d94-11ea-9894-dbcade16a07e.png)
![изображение](https://user-images.githubusercontent.com/4980243/79117676-6cab0300-7d94-11ea-8ffa-2d7ff15e1316.png)

**Comment by elfl0rd** [comment]
Same with electric.
![изображение](https://user-images.githubusercontent.com/4980243/79117776-b562bc00-7d94-11ea-9264-8e8386c0303e.png)

"how to easy repro"
prepare location - input and output.
![изображение](https://user-images.githubusercontent.com/4980243/79117810-ca3f4f80-7d94-11ea-8f09-e9639718ec82.png)
And place pump.

**Comment by SlayksWood** [comment]
Sink too:
![unknown](https://user-images.githubusercontent.com/45708377/79549197-57d5b480-809f-11ea-9d51-6ffc00821aac.png)

**Comment by SlayksWood** [comment]
need to check #15829 after fixing
