### ISSUE TITLE
Change the icon background for civic actions to yellow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15758]
![image](https://user-images.githubusercontent.com/3536496/79168234-2e1a4600-7d9e-11ea-8bee-a84baba40802.png)
Make the icons for legal actions (the things currently with a grey background) have a yellow background instead (looks better, blue is cause yellow is action).
Other color schemes are fine too just not grey.

**Comment by keegan-o** [comment]
@johnkslg The civic action section in eco.unity is not corresponding to these icons in-game, I set them to yellow and baked the sheet etc, but they do not apply to the in-game UIs.

**Comment by keegan-o** [comment]
Oh, I see, it's not civic actions you wanted changed, it's legal actions

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/83203137-a2663a00-a0fd-11ea-8b48-aaeeea894052.png)
fixed in staging, but in the course of this I also changed civic actions icon backgrounds to yellow, if that's a problem let me know @johnkslg .

**Comment by johnkslg** [comment]
works!
