### ISSUE TITLE
[0.9.0 staging-1511] Huckleberry Extract icon is very small

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15750]
The icon for Huckleberry Extract is much smaller than all other icons.

![HuckleberryExtract](https://user-images.githubusercontent.com/47330823/79152586-53e52200-7d81-11ea-8093-b967b5327f27.png)

**Comment by SlayksWood** [comment]
merged to #15737

**Comment by SlayksWood** [comment]
reopen as a separate issue.
