### ISSUE TITLE
[0.9.0 Staging - 1506] T4 walls not connecting

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15754]
**Steps to reproduce:** Build a house using T4 (Ashlar and Composite)
**Expected behavior:** the different types of walls connect to one another
**Actual behavior:** the Ashlar Full Wall block type does not connect properly to other types of walls.
**Providing Log files:**
![20200413161546_1](https://user-images.githubusercontent.com/1329717/79162196-78052b00-7da2-11ea-81db-8242cb12c853.jpg)
![20200413161922_1](https://user-images.githubusercontent.com/1329717/79162241-8a7f6480-7da2-11ea-9660-27c5b09c8645.jpg)
![20200413161949_1](https://user-images.githubusercontent.com/1329717/79162271-9b2fda80-7da2-11ea-8f7c-b9abff3ede1a.jpg)
![20200413162015_1](https://user-images.githubusercontent.com/1329717/79162300-aa168d00-7da2-11ea-8717-be708dfd0af0.jpg)

**Comment by SlayksWood** [comment]
dup #4601
