### ISSUE TITLE
Remove internal faces from stockpiles

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15752]
Stockpile present a massive impact on the number of triangles, and given that they are a major part of most settlements there will often be many of them in view at a time.  We need to optimize the rendering of these.  There are a few cases we can consider.  

For dirt, it actually works great, because the chunk builder detects when internal blocks are hidden and doesn't build them. You can see here the inside of this stockpile has minimal polys:
![image](https://user-images.githubusercontent.com/3536496/79160334-75003f80-7d8e-11ea-8704-00472821d36c.png)
![image](https://user-images.githubusercontent.com/3536496/79160354-7c274d80-7d8e-11ea-8a26-20d73e6ca703.png)

For boxes, this can easily be the case too, we just need to tag the boxes as opaque, should be a one-line fix that will drop millions of polys from rendering in most Eco cities, because right now all those internal boxes are getting built and rendered:
![image](https://user-images.githubusercontent.com/3536496/79160245-4f733600-7d8e-11ea-9315-893ef962b3e1.png)
![image](https://user-images.githubusercontent.com/3536496/79160973-8d248e80-7d8f-11ea-82ff-ef10da76a250.png)

The harder test is when there are mostly-opaque contents, like these hewn logs:
![image](https://user-images.githubusercontent.com/3536496/79160160-310d3a80-7d8e-11ea-91ac-dbafdf42c0c1.png)
You can still see through the cracks, viewing internal faces legitimately.  However, the value this adds to the visuals is so minor in comparison to its cost.  An ideas how we could alleviate this:
- Mark block types that are 'mostly opaque'.  Then, when there is a block that is surrounded by 'mostly opaque' neighbors is being built, instead of creating that block it creates a single poly that covers the gaps.

Thoughts?

**Comment by redwyre** [comment]
As the total number of blocks doesn't change with the new stockpiles, this can probably wait until after 9.0 (unless it's specifically showing up in profiling)

**Comment by mirasrael** [comment]
Stockpile content is just regular chunk. So no need to specifically optimize stockpiles. And yes, we don't see chunk rendering in the top of profiling results, so can be pushed. Actually, most problems for stockpiles is coming not from rendering, but from regular updates (it changes stockpile content every time when it's inventory changes). So if we really wanna to optimize stockpiles we should replace them with opaque containers (with higher capacity than stockpiles so they will be preferred by players).

**Comment by johnkslg** [comment]
If we're trying to get poly count down (given that we're pursuing LODed world objects, this seems to be the case), this could be a way to significantly reduce GPU load, especially with the addition of the new giant stockpile. 

Most large cities have quite a few stockpiles and it will blow out our GPU budgets very quick.

**Comment by elfl0rd** [comment]
In my opinion, appropriate solution is to "cover the stockpile with cloth."
![images](https://user-images.githubusercontent.com/4980243/79360444-99097f80-7f4c-11ea-9821-ef98e950b759.jpg)
Maybe as a separate option or based on selected image quality settings.

(And yes, i agree idea with covering internal blocks in dark shadow, like underground space.)

**Comment by mirasrael** [comment]
@keegan-o can we adjust block builder to use simplified connected shape for closely placed blocks (with some dark texture between them)?

**Comment by keegan-o** [comment]
Blocks can be updated with fallback rules that detect when they are surrounded by solid blocks, and then use a cube mesh in that case. I can look at setting this up for all the most commonly stored/used materials that players use. Actually what we could do as well for things commonly in stockpiles is make a generic crate cube that shows up, that way we could set all the things that would be hard to make fallback cube art for just use that, and it won't be super noticable since the crates will only appear between/inside other things.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81452464-d45a3100-913b-11ea-8e55-a6e5ba0cdbc0.png)
I will try to make fallbacks like this, in most cases the texture may be hard to come up with using the same material as the rest of the blocks, but we'll see! I'll aim to just get it done quickly.

**Comment by johnkslg** [comment]
Nice solution!

**Comment by trickenso** [comment]
I'm sure you've already thought of this, but could this also apply to stacks that aren't in stockpiles? 

There's nothing stopping you making identical piles of resources that aren't in a stockpile - particularly waste rock chunks from mining.

**Comment by keegan-o** [comment]
oh yeah, stockpiles are the same as everywhere else. these are block changes that will be fallbacks wherever the blocks appear

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81457984-20fa3800-914d-11ea-8641-0f14727563a7.png)
Almost done with these now, for now the rules will be like this-- pretty strict, which is better than having these ugly cubes appear too often when you're just moving stuff around in small piles I think.

**Comment by keegan-o** [comment]
finished these for all main building materials, as well as metal products, and the crate, and barrels. From here if you see a high poly block that does appear to have a fallback, that can be its own little issue to have me make one for it. 

![image](https://user-images.githubusercontent.com/14983165/81458675-6ff59c80-9150-11ea-8aa1-0bccae9b7e38.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81459148-3ffbc880-9153-11ea-949e-67d06cc966fa.png)
Here you can see the birch log cube appearing inside the others

**Comment by redwyre** [comment]
Oh damn, I didn't see this, nice work!
