### ISSUE TITLE
[0.9.0 Staging - 1506] Spruce Seed doesn't show up in Pots

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15757]
**Steps to reproduce:** Plant a spruce seed in a planter pot (I used round pot for this)
**Expected behavior:** Tiny Spruce tree shows up in the pot
**Actual behavior:** No tree is visible
**Providing Log files:**
![20200413163023_1](https://user-images.githubusercontent.com/1329717/79163232-47be8c00-7da4-11ea-9465-246b71853b90.jpg)

**Comment by MonzUn** [comment]
This applies to Oak seeds as well according to a player on my server.

**Comment by MazonDel** [comment]
@SlayksWood @MonzUn I've added the Joshua, Oak, and Spruce trees to the "Fake Tree" system for the potted plants, so these trees should work now. However this change was entirely in the SVN, no code changes required. So you'll have to run an update on that and give it a try.
