### ISSUE TITLE
[0.9.0 staging-1512] Wood Cart: Shovel into wood cart when it´s full

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#15769]
If the wood cart is full of dirt and you try to insert more dirt, the shovel runs into wood cart and you still have the dirt in your hands.

**Steps to reproduce:**
Full a wood cart of dirt, right click on wood cart while holding dirt and selecting shovel.
**Expected behavior:**
Warning saying cart is full and still holding shovel.
**Actual behavior:**
Dropping the shovel in the cart and still holding dirt.

**Previous reports all closed but bug still exist.**

**Comment by SlayksWood** [comment]
dup #14911
