### ISSUE TITLE
0.9-1512 backpack and hotbar under shadow background

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15765]
(Backpack - only if backpack opened before interface.)
It makes moving modules and resources much more inconvenient.
![изображение](https://user-images.githubusercontent.com/4980243/79206914-b2c19e80-7e48-11ea-8b87-633a94cb7ec6.png)

(Carry slot under shadow too.)

**Comment by elfl0rd** [comment]
For me. this shadow provide only issues, maybe just remove it?

**Comment by Engimage** [comment]
It is fine to shadow game world but UI should not be effected
