### ISSUE TITLE
[0.9.0 staging-1512] Resetting Contract board

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15760]
When you reset contract board then you should delete its work parties and contracts.
Step to reproduce:
- place workbench and contract board:
![image](https://user-images.githubusercontent.com/45708377/79190577-51400680-7e2d-11ea-88bf-b628d962f230.png)
- start any order and create workparty:
![image](https://user-images.githubusercontent.com/45708377/79190608-674dc700-7e2d-11ea-8632-cdd9928cf95f.png)
![image](https://user-images.githubusercontent.com/45708377/79190626-72085c00-7e2d-11ea-84b2-bd98d2d9b39b.png)
- start any contract:
![image](https://user-images.githubusercontent.com/45708377/79190686-906e5780-7e2d-11ea-83bf-728ee8422262.png)
![image](https://user-images.githubusercontent.com/45708377/79190711-99f7bf80-7e2d-11ea-976e-aa4cc9d0093b.png)
- pick up Contract board
- reset persistent data:
![image](https://user-images.githubusercontent.com/45708377/79190752-b72c8e00-7e2d-11ea-9a46-475225bf5dfa.png)
![image](https://user-images.githubusercontent.com/45708377/79190843-efcc6780-7e2d-11ea-90de-b7b32b92190b.png)
- But I still have my Work Party and Contract in Economy viewer:
![image](https://user-images.githubusercontent.com/45708377/79190909-14284400-7e2e-11ea-909e-b8e3e051ae29.png)
![image](https://user-images.githubusercontent.com/45708377/79190932-1e4a4280-7e2e-11ea-9377-ebaf92eea37a.png)
- but I have't any way to take it.

So when I "click here" to delete object data I should have ConfirmBox that asking me about deleting all contracts and Workparty from this board. And if I press "Yes" it should delete all workparties and Contracts, not only mine.

You can do other behavior. This is only 1 option. But something needs to be done with this.
@johnkslg maybe you have better solution?

**Comment by SlayksWood** [comment]
I can cancell Work Party by deleting Order, but I don't found any way to delete contract.

**Comment by SlayksWood** [comment]
May be delete possibility to reset persistent data for contract boardin 0.9.0?

**Comment by johnkslg** [comment]
I suppose it can cancel the work orders and contracts that are there as per normal (just like cancelling them in their regular UI, it will confirm you want to do it, then payback the required amounts), so it should use the same codepath. 

Problems: there can be contract and work parties that you dont own on the board, and shouldn't have the ability to remove.  So maybe in that case, you cant clear data on contract boards. And we just remove the ability to do so. 

Oleg will leave this to you.
