### ISSUE TITLE
[0.9.0 staging-1512] Redwood Tree: 0% but map shows would be ok

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#15770]
With soil sampler:
![20200414142620_1](https://user-images.githubusercontent.com/63646359/79225940-d17e6000-7e5d-11ea-8af9-53a17f732514.jpg)

but map filtered on redwood tree shows:
![20200414142844_1](https://user-images.githubusercontent.com/63646359/79225966-dcd18b80-7e5d-11ea-88da-f1d1593e393f.jpg)

**Comment by beastyn** [comment]
Thank you for your report.
This can happen because of the heat map interpolation. On the block with your tree sapling can be bad temperature.
We will make heat map better in the later versions.
