### ISSUE TITLE
[9.0 staging 1511] Code is appearing instead of icons sometimes

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15776]
Looks like code is appearing sometimes instead of icons, was working fine before build 1511

![image](https://user-images.githubusercontent.com/61889138/79230724-f0302700-7e5c-11ea-9185-3346681e4eb7.png)

![image](https://user-images.githubusercontent.com/61889138/79230751-fb835280-7e5c-11ea-86b2-ea62466b96c9.png)

**Comment by SlayksWood** [comment]
dup #15738
