### ISSUE TITLE
Chopped a tree, when fell to ground tossed me into space. Cant log back into the world

### ISSUE THREAD

**Issue by Kimrian** [StrangeLoopGames/EcoIssues#15777]
I chopped a tree,  might hav been standing a bit Close, but when it fell to the ground, it tossed my character upp into the air and furter into Space, until the game logged me out With a error Message. getting the same error Message when i try to logg in. see below. Would love to be able to get back into the server =)

![image](https://user-images.githubusercontent.com/38511246/79238459-b0bf0600-7e6f-11ea-9127-92dcb23c6660.png)

**Comment by SlayksWood** [comment]
fixed with #https://github.com/StrangeLoopGames/Eco/pull/5926
