### ISSUE TITLE
[0.9-1511] Pulp Mortar recipe not adjusted

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15779]
Pulp Mortar recipe (Masonry Table) still requires 15 Wood Pulp while all other recipes were tweaked to require 5 Wood Pulp.

**Comment by SlayksWood** [comment]
> Mortar recipes changes from discord:
> 1. Pulp Mortar from Wood Pulp on Masonry table (Mortar = 15 WoodPulp without module)
> Delete this recipe. It seems incorrect and part duplicates recipe on Campfire.
> 3. Charred Mortar from WoodPulp and Plantfibers on Campfire (Mortar = static 5 Pitch)
> Add Kelp to Pitch Tag

**Comment by Engimage** [comment]
Slayks recipe on a Masonry Table was effected by Mason's calorie reduction so it is needed still as the campfire one costs a ton and calories can not be rediced..
Another recipe is in Bakery Oven but it requires twice less calories so it makes sense as well.
