### ISSUE TITLE
USER ISSUE: Error opening wainwright table

### ISSUE THREAD

**Issue by MiquelRoan** [StrangeLoopGames/EcoIssues#15778]
**Version:** 0.9.0.0 beta staging-1511

**Steps to Reproduce:**
1. open wainwright table	

**Expected behavior:**
It should show all recipes

**Actual behavior:**
Showing few recipes. Everytime I enter the table there's one recipe more loaded correctly
![Captura](https://user-images.githubusercontent.com/61141964/79254217-b2df8f80-7e84-11ea-84d5-9428d8609d2a.JPG)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no. I'm playing in Royal Otter

**Comment by SlayksWood** [comment]
Can you provide log files when have this issue?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
such bugs were easily reproduced, possibly fixed in staging-1513. 
@MiquelRoan 
Check it again after updating playtest to new staging.

**Comment by SlayksWood** [comment]
@MiquelRoan 
Do you have this issue in new staging?

**Comment by LoBlanc** [comment]
It didn't reproduce again to me

**Comment by WeaselDog** [comment]
Thanks for your report. We are not able to reproduce this in the latest version and it appears to be fixed. Please let us know if experience this issue again.
