### ISSUE TITLE
0.9 localization: "performance" module is not localized

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15771]
![изображение](https://user-images.githubusercontent.com/4980243/79227215-3939a880-7e68-11ea-8c32-db32a6838ba0.png)

**Comment by SlayksWood** [comment]
Need to localizate "notify":
![image](https://user-images.githubusercontent.com/45708377/82650998-39c21d80-9c24-11ea-8222-3e65eb0f7b9e.png)
