### ISSUE TITLE
Setup Eco news

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15783]
![image](https://user-images.githubusercontent.com/3536496/79276851-911ee200-7e5d-11ea-836a-874bcb8e7d83.png)
Eco news will be Dennis land, can you setup our first news, talking about playtesting for 9.0?  Make it include both an image and links to test those.

Any problems with the interface to create news, file bugs to Jeff and Denys

**Comment by Alteraner** [comment]
HTML formating is not working fine. Its not been parsed. You can see the html tags instead of e.g. bold text in the news.

**Comment by johnkslg** [comment]
@gzatravkin can you take a look?

**Comment by gzatravkin** [comment]
Notifications are using Text mesh pro rich format. 
You can find description and samples here: http://digitalnativestudios.com/textmeshpro/docs/rich-text/

**Comment by D3nnis3n** [comment]
That's not compatible with WYISWG of Wordpress. For ease of use, either the WYISWG should put that format in or the notifications should support the normal formatting. At the very least a link to that formatting site needs to be placed easily viewable below the insert fields, so i can remember how to type that stuff.

**Comment by D3nnis3n** [comment]
https://cdn.discordapp.com/attachments/680068515658596364/699861988347609088/2.jpg

**Comment by D3nnis3n** [comment]
Also note the issue with the "don't", where the "'" is being transformed into weird stuff.

**Comment by D3nnis3n** [comment]
Also, i personally cannot see the news ingame at all, while others on playtest can see them:
![cantsee](https://user-images.githubusercontent.com/25908592/79375435-eb509d80-7f58-11ea-85b8-ed79b0bd52e0.png)

**Comment by denysaw** [comment]
> 
> 
> Notifications are using Text mesh pro rich format.
> You can find description and samples here: http://digitalnativestudios.com/textmeshpro/docs/rich-text/

That's cool, but WP doesn't support that:
![image](https://user-images.githubusercontent.com/5720101/79376634-bc3b2b80-7f5a-11ea-895c-f8866ee45668.png)

Common standard for WYSIWYG's is HTML.
Why just not to use https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser?view=netframework-4.8 or WebView?

Anyway, current solution is to switch current WYSIWYG in HTML mode and put those textmeshsplash tags manually.

**Comment by denysaw** [comment]
Or I can switch back NewsContent field from WYSIWYG mode to usual text mode, where textmesh tags could be also typed manually. There's no so big deal to type. Those tags was invented for typing in text, rather to click the buttons. Same as MardDown format. So tell me should I switch it back to text or nope. Thanx

**Comment by D3nnis3n** [comment]
The preferred solution is that i can use the full power of the WYISWG without having to learn a new formatting language.

The workaround solution can be switching it back, but adding a link below to that manual, as i WILL forget how to use these, as i never use them.

Given that switching to a different format later will invalidate the older news, we should find a decisions soon, though.

**Comment by denysaw** [comment]
Yep. So we have few options here: learn to type those tags manually, to use WebView or WebBrowser instead of TextMesh Pro, code HTML->TextMesh converter (https://forum.unity.com/threads/html-to-text-mesh-pro.565672/  it'll take about 2-3 weeks minimum I guess and never will convert everything of html ideally), to code Chrome Extension of integration TextMesh RichText panel to every text-area on a page (will take also few weeks). Unfortunately there's no ready TextMesh Pro plugin nor for WP, nor for Chrome. Probably @johnkslg will need to choose which way we gonna go. Thanx.

**Comment by D3nnis3n** [comment]
Well, that's not worth it. Using WebView might be faster. Otherwise just put a link to that manual below the input field, and i'll use that.

**Comment by denysaw** [comment]
Yep. Ah, forgot to mention 1 more option:
You could install Unity with TextMesh Pro, type News there and copy-paste in WP's textarea ;)

**Comment by D3nnis3n** [comment]
I'd prefer to not install Unity for simple news, haha.

When the news were implemented, that stuff should already have been thought about :D

**Comment by johnkslg** [comment]
We can just use the text mesh pro tags
Cant do a general html editor

**Comment by denysaw** [comment]
WP has general HTML Editor - famous/common TinyMCE. Problem is not in editor, but in viewer. You are using TextMesh Pro in-game (which has own untraditional text formatting) and not WebView WebBrowser to be able to render HTML.

**Comment by denysaw** [comment]
So we are asking what to do: to type those TextMesh tags manually in text w/o any preview? Or to code some converter/plugin, but waste a lot of time on it.... Or to change TextMesh with WebView: 
https://github.com/gree/unity-webview
https://uniwebview.com/
etc

**Comment by johnkslg** [comment]
Code without preview. Then Dennis can set news to 'dev only', verify it looks ok, and then change it.

**Comment by D3nnis3n** [comment]
It looks like the TextMesh stuff doesn't support links. I can't check though, because of this issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/15806

**Comment by denysaw** [comment]
Seems Dennis right. Text*esh supports only `links` to a text block (kinda jumpers):
http://digitalnativestudios.com/textmeshpro/docs/rich-text/#link

Will you (GameDev team) be able to extend it via parsing usual `<a href` tags, which Dennis will put in content manually?

**Comment by denysaw** [comment]
If you are able to call usual shell command out of game, then it's technically real. You should just parse `<a` and then:
```
chrome.exe $1
```
Where $1 is anchor's href (parsed).

**Comment by gzatravkin** [comment]
For preview I sumbited simple webgl app. You can past text with text mesh pro standart, and check how it will looks like 
https://simmer.io/@GrigorGri/~dd9e39cd-9fac-4fe6-65a5-28903a720351

**Comment by denysaw** [comment]
WoW. Nice. And external link support extend, would you be able to do that? =)

**Comment by D3nnis3n** [comment]
Yep, doesn't support external links in the preview, we'll need that.

**Comment by denysaw** [comment]
Btw, if you would actually replace TextMarrakesh with WebView, user could have opened those external links in-game (inside save WebView), w/o exiting FullScreen and switching to browser. But anyway I bet executing shell command to open browser is probably a lot more lightweight for game and easier to implement.

**Comment by D3nnis3n** [comment]
Clickable links would be great, yeh. Probably using WebView is the better solution for flexibility.

**Comment by D3nnis3n** [comment]
Closing for https://github.com/StrangeLoopGames/EcoIssues/issues/15838
