### ISSUE TITLE
Wall behind contract Board can trap players

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15780]
**Version:** 0.8.3.3
**Issue:** A specific building setup can trap a player forever as /unstuck does not get them out

**Details:**

I built a contract board and placed a mortared stone wall behind it and to either side. While doing this I fell in, but /unstuck didn't get me out. I had to remove the wall then put it back up. The next day another player fell in, but since they didn't own it they had to ask me to come and help them.

While this bug with /unstuck can be worked around, it's bad in that a player could troll a server by building traps for other players to fall into. Unless the owning player helps them or authorizes them, the only way they can escape is with the help of an admin either using the dev tool to destroy the blocks or via a teleport. Lacking that intervention, they will be stuck there unable to do anything to get out.

**Comment by elfl0rd** [comment]
screenshot?

**Comment by Elliander** [comment]
I neglected to take a screenshot when another player fell in, so I just took two. One of the overall build, and the other showing me stuck behind it. I can't screenshot /unstuck action, but doing it causes the avatar to jump up 3/4 up the wall then drop back down to where it was.

As you can see, the trap requires a board in front, and wall segments in the back. The left side is a mortared stone block.

![board_trap](https://user-images.githubusercontent.com/15022396/79274193-ce896c80-7e69-11ea-9133-f20a87d5baf8.jpg)

If the user falls in the space between the board and the wall they cannot jump out, since it's two blocks high, cannot walk around the sign because the wall is up against it, and they cannot remove the blocks if it belongs to someone else, and they cannot get out with /unstuck

I see potential for abuse here. 

![board_trap_2](https://user-images.githubusercontent.com/15022396/79274304-fa0c5700-7e69-11ea-96b7-87030b66289e.jpg)

**Comment by TwixterZ** [comment]
While this still can happen as of 9.3 staging-1964, I have tested that players are able to escape from behind the box by jumping onto one of the board's leg at the back then proceed to jump out from there.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/95d06398-fec4-4f7f-930a-521db38b5d7d)

below is a short gif of how player can escape : 
https://gyazo.com/ae101f1635a9fea5d9a0416fca3a1f0f

While this does open possibilities for trolling, the impact on gameplay is actually minor if not zero. 

As such, I will close this ticket.

Thank you for bringing this up to us @Elliander
