### ISSUE TITLE
Make the labor icon in craft tables be the type of the skilled labor required

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15788]
![image](https://user-images.githubusercontent.com/3536496/79280556-77819880-7e65-11ea-8b80-a41ea4470b41.png)
Right now its a generic hammer, it should match the skill of the labor required. 

Ask @serpopov if help needed

**Comment by mirasrael** [comment]
@johnkslg can't it wait for post-9.0?

**Comment by johnkslg** [comment]
Would be a nice easy polish addition for a new feature
