### ISSUE TITLE
Full inventory collect items exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1578]
![image](https://cloud.githubusercontent.com/assets/774628/26744439/c449edac-479a-11e7-854b-668d8ed0781b.png)

**Comment by SeanAtr0n** [comment]
![image](https://cloud.githubusercontent.com/assets/774628/26744594/6a7b7ab0-479b-11e7-9725-bb8a015047e5.png)
Not sure if its related to the exception, but after making room and hitting collect I see the work order is still present

**Comment by SeanAtr0n** [comment]
I already have the book in the picture above

**Comment by MarjieAVolk** [comment]
Yeah that's a bug caused by the other bug I just fixed >> lol - not related
