### ISSUE TITLE
Can't use /teleport atob

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15787]
/teleport atob Kimrian SLG-Dennis - No permissions
My account is admin, dev-tier and slg-admin, it should work.

![noperms](https://user-images.githubusercontent.com/25908592/79278472-087b6280-7eac-11ea-8508-a16c96212d6d.png)

I assume this issue exists for all those commands.

**Comment by D3nnis3n** [comment]
This happens with all dev commands.

For clarification:
Normal admin commands should be usable by any admin.
Developer commands should be usable by any admin that is at least dev tier - which my slg account should include.

**Comment by beastyn** [comment]
Nope
We've duscussed it already
1. You can use admin commands if you are an admin.
2. Server owner is an admin by default
3. Devtier can use dev commands ONLY locally
4. Devtier will have dev commands on the third-party servers after this https://github.com/StrangeLoopGames/Eco/issues/5527
So, for now:
1. We can revisit commands and make admin for what you need. Give us a list. But remember, we didn't want to give admin for commands which can break the game.
2. If you don't have dev commands locally, make sure that you use account with dev rights.

**Comment by beastyn** [comment]
teleport commands were mobed
StrangeLoopGames/Eco/pull/5938

**Comment by D3nnis3n** [comment]
Well, then ALL devcommands that are required by admins need to be moved asap.

**Comment by beastyn** [comment]
Thats up to you, just give a list in a separate issue )

**Comment by D3nnis3n** [comment]
Well, teleport commands were never dangerous.

**Comment by Deantwo** [comment]
Also a quick version for summoning a player to your location would be useful.
A short version shortcut could me `/summon`
So I can use `/summon SLG-Dennis` to quickly move Dennis to my location.

**Comment by D3nnis3n** [comment]
Acceptable, please close when in.
