### ISSUE TITLE
Transparencey manager exceptions in client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15789]
Got these after disconnecting/reconnecting and opening a workbench, not sure what caused it. 

MissingReferenceException: The object of type 'RectTransform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.RectTransform.get_rect () <0x175a75d4d90 + 0x00072> in <b80225b357c64115895f5655e67db547>:0
UnityEngine.RectTransform.GetLocalCorners (UnityEngine.Vector3[] fourCornersArray) (at C:/buildslave/unity/build/Runtime/Transform/ScriptBindings/RectTransform.bindings.cs:178)
UnityEngine.RectTransform.GetWorldCorners (UnityEngine.Vector3[] fourCornersArray) (at C:/buildslave/unity/build/Runtime/Transform/ScriptBindings/RectTransform.bindings.cs:198)
UnityUtils.GetScreenRect (UnityEngine.RectTransform rect) (at Assets/Scripts/Utils/UnityUtils.cs:182)
OverlapingRectBase.get_OverlappingRect () (at Assets/UI/Scripts/WorldMarkers/OverlapingRectBase.cs:11)
WorldMarkerManager+<OverlapseLoop>d__30.MoveNext () (at Assets/UI/Scripts/WorldMarkers/WorldMarkerManager.Rects.cs:76)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

**Comment by mirasrael** [comment]
@johnkslg can't we disable TransparentManager in 9.0 and fix it after 9.0? We already had feature freeze months ago and it seems like a new functionality which requires additional attention.

**Comment by johnkslg** [comment]
The mess you get with work parties + popups is too much:
![image](https://user-images.githubusercontent.com/3536496/79360422-c0cef800-7ef8-11ea-862a-0cb33088d657.png)

Need to keep this one
