### ISSUE TITLE
USER ISSUE: Colored name on own Steam Truck affects how other are viewed

### ISSUE THREAD

**Issue by MKVangen** [StrangeLoopGames/EcoIssues#15798]
**Version:** 0.9.0.0 beta staging-1512

**Steps to Reproduce:**
Name your steam truck with <color=red>Steam Truck

(I don't know if this only affects me or other players)

**Expected behavior:**
Only your stream truck should show up with colored text

**Actual behavior:**
All steam trucks names gets the same color as my own

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mod. Issue happens without mods

**Comment by MKVangen** [comment]
![20200415133934_1](https://user-images.githubusercontent.com/37910364/79333776-64cb9a00-7f1f-11ea-936a-049e4f98b7a4.jpg)
![20200415133941_1](https://user-images.githubusercontent.com/37910364/79333781-65fcc700-7f1f-11ea-81ef-cead944296c2.jpg)
![20200415133950_1](https://user-images.githubusercontent.com/37910364/79333787-67c68a80-7f1f-11ea-9758-09fc67fd3016.jpg)
![20200415133958_1](https://user-images.githubusercontent.com/37910364/79333799-6d23d500-7f1f-11ea-9349-33edc3a2572b.jpg)

**Comment by elfl0rd** [comment]
Lol. Looks like "end" tag is not applied automatically.
And as result - all list is colored, lol.

**Comment by johnkslg** [comment]
Check out textmesh pro docs and talk to  sergey for a generic solution
