### ISSUE TITLE
USER ISSUE: Inventory connections reset in store

### ISSUE THREAD

**Issue by MKVangen** [StrangeLoopGames/EcoIssues#15797]
![20200415131816_1](https://user-images.githubusercontent.com/37910364/79332045-71022800-7f1c-11ea-9561-892acac1067c.jpg)
![20200415131819_1](https://user-images.githubusercontent.com/37910364/79332049-72cbeb80-7f1c-11ea-989e-67d987719f0d.jpg)
![20200415131822_1](https://user-images.githubusercontent.com/37910364/79332057-752e4580-7f1c-11ea-8c80-614ea2a8fa10.jpg)

**Version:** 0.9.0.0 beta staging-1512

**Steps to Reproduce:**
Go to the store. Access it. Go to the storage screen. Disconnect/deselect steam truck fuel as an accesible storage for the store. Go back to the store page, and then back to the storage page. The connection has reset.
Having the store auto-connect to the truck storage is nice. But it shouldn't default to connect to the truck fuel also. You can easily sell your fuel to the store if you don't pay attention. I have also heard about stores outputting items to the fuel storage, but I cannot confirm this.

**Expected behavior:**
Selections for which storages accessed by the store should be saved and not reset

**Actual behavior:**
Selections for which storages accessed by the store resets

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Issue happens without mods.

**Comment by johnkslg** [comment]
The store will auto-link your vehicles when you open it by design, though it shouldn't do that to your fuel. I've prevented that with a code change. Thank you!
