### ISSUE TITLE
[0.9 Staging-1511] Editing claims has a visual glitch and might eat claim papers...

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15793]
I played around with editing claims. First of all, the highlight on the map is off-centre from the cursor. This problem is minor, maybe it has something to do with the 4k resolution and UI scaling? Secondly, I think there is a bug that eats the papers that relates to editing claims. I removed a claim entirely with it and it didn't give me my papers back, losing about 10 of them. Couldn't reproduce this bug though...

1) Version
0.9 Staging-1511

2) Steps to reproduce
- Claim some land
- Edit the claim with the stake by pressing "e"
- The map highlight will be off-centre from the mouse cursor
- Remove claims, remove a claim entirely, maybe add / remove parts of it first?
- Claim will be gone, but you won't get your papers back

Video (of the first part, couldn't repo the second one):
https://youtu.be/ZnFfQkpI42M

3) Expected behaviour
Map highlights should be underneath the mouse cursor. Editing claims with the edit shouldn't let players lose their claim papers...

4) Actual behaviour
Map highlight is offset from the cursor, a player can lose their claims.

5) Providing Log files
(I think it's this one...)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4479126/Player.log)

PS: I think I'm down 30+ claims on this test server already :D. Would appreciate getting some back ;)

**Comment by SlayksWood** [comment]
merged to #15086
