### ISSUE TITLE
Project with multiple output displayed only one (e.g. "tailings project", lol)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15796]
![изображение](https://user-images.githubusercontent.com/4980243/79330407-2388b980-7f22-11ea-8c5d-f9d50028fcd0.png)

And as you can see - "result" in project tooltip is only tailings, lol.
![изображение](https://user-images.githubusercontent.com/4980243/79330501-55018500-7f22-11ea-8702-026b828f4155.png)

same behavior with plastic\rubber\epoxy
Displayed only one result, not all. (Barrels missed)
![изображение](https://user-images.githubusercontent.com/4980243/79330653-96923000-7f22-11ea-9071-7ef24023778a.png)

**Comment by mirasrael** [comment]
Fix tailings order for 9.0 and push other to 9.1 (when order UI will be redesigned).

**Comment by mirasrael** [comment]
@SlayksWood @beastyn fixed main issue with displaying Tailings as default product. As I commented above we can add to new Crafting UI requirement to show all products.

**Comment by SlayksWood** [comment]
added to #13334
