### ISSUE TITLE
[Server Configuration] Can't set spawn

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15808]
Version: 0.8.3.3

I'd like to be able to set the spawn on my server, but everything I do is ignored. With this in Users.eco

```
"DelayNearbyFoodCheckMinutes": 4.0,
  "NearbyFoodSpawnLocationRadius": 20.0,
  "NearbyFoodSpawnCount": 5,
  "UseExactSpawnLocation": true,
  "SpawnNearbyFoodLocation": {
    "x": 65,
    "y": 1818,
    "z": 48
  },
```

I would expect that the player would spawn at:

`/teleport 65,1818,48`

However, instead the player spawns at:

`/teleport 1017,143,48`

I compared the Users.config between 0.7.3.3 (where it worked) and 0.8.3.3 (where it doesn't) and noticed that "SpawnLocation" was replaced with "Spawn NearbyFoodLocation" so manually added this in:
```

    "SpawnLocation": {
    "x": 65,
    "y": 1818,
    "z": 48
  },
```

But that didn't help either.

Then I tried changing the Z coordinate really high, thinking maybe the position at 48 was occupied, but no, didn't work.

I also tried using the admin command /setspawn , but that didn't make any difference.

I asked on the discord in case anyone knew if I was doing something wrong, but no one seemed to know, so I'm thinking of this as a bug, though I wish I knew where it was getting it's current coordinates from.

On the last server, the game periodically changed the spawn location on it's own and ignored all attempts to get it under control resulting in a fracturing of town setups, so on this new server I'd like to be able to control this if at all possible.

Here's a link to the server files: (upload in progress at time of posting this)

https://drive.google.com/open?id=1NFKwUMBJhdYZG2AYTIzrkoM-Y3UV5T8f

It has no users yet, and each time a user tried to get in they always end up at 1017,143 despite what is in the configuration files or anything I try to do. If this isn't a bug I'd love to know what is wrong, and if something has to be manually added to fix it then I'd still think of it as a bug.

**Comment by Elliander** [comment]
I'm not sure why, but the admin command

/setspawn 

started to work on the new server, so I can at least work around the issue by going to where I want players to spawn and use it each time the server boots up, but the configurations still don't work.

**Comment by Elliander** [comment]
I figured out what is causing the problem and where the game is getting it's spawn coordinates from. Basically, SpawnLocation is now in WorldGenerator.eco and the coordinates the game keeps picking happen to match what is there.

 Changing it here does allow me to set the spawn location as the game now ignores anything related to spawn in Users.eco

**Comment by WeaselDog** [comment]
Thanks for reporting this and providing detailed information.

This is now fixed in our staging build.
