### ISSUE TITLE
trees grow on stockpiles

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1580]

**Comment by metachronism** [comment]
is that bad?

**Comment by SeanAtr0n** [comment]
yes?

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/26945386-6ed0f78a-4c40-11e7-9d4e-27b52b86074e.png)

**Comment by metachronism** [comment]
I mean, if the dirt is there, why shouldn't trees grow on it?

**Comment by SeanAtr0n** [comment]
because the dirt will eventually disappear and you get flying trees?

**Comment by REPOSEECO** [comment]
You can't cut the tree.

**Comment by vp-benwillard** [comment]
Honestly I don't see why Meta isn't right.  I mean if you have dirt sitting there for a long time to where a nearby tree sprouts a new seed/tree.  Well...  You know the rest.  However if you cannot CUT the tree down then that might be a problem.  ALSO if the dirt below the tree no longer there it should cause the tree to fall or disappear etc. 

Just my two cents.

**Comment by Uniphix** [comment]
Honestly I don't see why Meta isn't right.  I mean if you have dirt sitting there for a long time to where a nearby tree sprouts a new seed/tree.  Well...  You know the rest.  However if you cannot CUT the tree down then that might be a problem.  ALSO if the dirt below the tree no longer there it should cause the tree to fall or disappear etc. 

Just my two cents.

**Comment by REPOSEECO** [comment]
Why shoud i dig unter my stockpile ?

**Comment by Uniphix** [comment]
Never said about digging.  I am saying that as soon as the dirt disappears (being used or taken out) it should destroy the tree or cause it to fall over.

**Comment by REPOSEECO** [comment]
Upps soory my english is not the best. I will check it. If next time a tree grows up in my sockpile

**Comment by SeanAtr0n** [comment]
http://ecoforum.strangeloopgames.com/topic/2530/5-6-tree-growing-on-stockpile

**Comment by metachronism** [comment]
punting to beta

**Comment by metachronism** [comment]
stockpiles fill with spacer blocks now, so this should no longer be an issue
