### ISSUE TITLE
Can't see news ingame

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15806]
https://user-images.githubusercontent.com/25908592/79375435-eb509d80-7f58-11ea-85b8-ed79b0bd52e0.png

Build 1512, as of playtest channel others can see the news.

What are possible causes for this?

**Comment by gzatravkin** [comment]
Most proabably it's because of tier of news and of your account. 

The client only parses server respnose (with your account token), so for check it somebody from server side is needed.

**Comment by D3nnis3n** [comment]
I can neither see it with my SLG admin account with tier 516
nor with my dev tier account 11.

Something is wrong.

**Comment by D3nnis3n** [comment]
Tier for the news i want to see is Minimum: Beta.
I should be able to see it.

Probably a different cause?

**Comment by D3nnis3n** [comment]
Present on build 1513 (latest), 1512 (playtest).

**Comment by gzatravkin** [comment]
As far I know it's not exactly minimum right now.
You should belong to group to see that news.
![image](https://user-images.githubusercontent.com/53317567/79387180-981f2080-7f41-11ea-9c9e-6bc1dfbdf86a.png)

Anyway it server part and I dont really sure how it works right now

**Comment by D3nnis3n** [comment]
Well, that needs to be changed. But server should rather be redwyre or mirasrael?

**Comment by gzatravkin** [comment]
not sure. 
@redwyre @mirasrael

**Comment by mirasrael** [comment]
It is web site issue. Not Eco Server. On client side it just makes request for news and then Accounts side decides what show to user.
@denysaw @rainfarmer

**Comment by denysaw** [comment]
Hotfixed on production:
![image](https://user-images.githubusercontent.com/5720101/79569290-a68f4880-80b7-11ea-9d28-7a06e89a5642.png)

@rainfarmer , problem was... `min_tier` really meant Minimal Tier and not strict equalness (this was the question I was re-asking).

**Comment by D3nnis3n** [comment]
I explicitly requested the behaviour to be changed.

Works now, closing.
