### ISSUE TITLE
[0.9.0 staging-1513] Districts: Missing colors with ESC closing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15801]
1. Open a new district map
2. Make some districts
3. Draw couple of them,
4. Press Esc 
5. Draft will be created
6. Open a draft

There is no any drawn districts, they are all empty.

Everything will be fine if you close with 'cross' button

**Comment by SlayksWood** [comment]
@gzatravkin 
Seems fixed with https://github.com/StrangeLoopGames/Eco/pull/5948
