### ISSUE TITLE
Civic object UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15809]
![image](https://user-images.githubusercontent.com/3536496/79384246-58ddd900-7f1b-11ea-8ab5-ef233492c717.png)
- [ ] Revise button blocks the Eco stamp

![image](https://user-images.githubusercontent.com/3536496/79384386-a2c6bf00-7f1b-11ea-9b93-501e71745f87.png)
- [ ] Bad text here

**Comment by serpopov** [comment]
first part would be fixed in #15231
