### ISSUE TITLE
Review Admin & Developer Commands 

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15804]
We want to review all the developer commands now that they are protected. All commands that are useful for admins and not game breaking should now be categorized as admin commands.

**Comment by D3nnis3n** [comment]
I skimmed through them, it looks fine for me, the teleport commands must have been an oversight.
Feel free to do another pass.

**Comment by WeaselDog** [comment]
I am going to close this because after review nothing needs to changed.
