### ISSUE TITLE
[0.9.0 staging-1513] Pipe Component does not contain information

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15807]
This picture is taken from a running Blast Furnace. It should have information displayed for Water, Smog, and Sewage. Right now it is just Smog Output with no information.
![PipeComponent](https://user-images.githubusercontent.com/47330823/79380903-f6cea500-7f15-11ea-998b-f2607ecef37d.png)

**Comment by MarkZaytsev** [comment]
Seems fixed already by someone else
![ss (2020-05-18 at 01 33 52)](https://user-images.githubusercontent.com/50739566/82184371-c19ce480-9911-11ea-9d11-4c3cc6383bb7.jpg)
