### ISSUE TITLE
[0.9-1512] UI hyperlinks not working

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15802]
There are several occurances of this bug but I am sure they are related.

1. Chat hyperlinks. You can type an item name to get an active hyperlink for it. However when the chat scrolls or sometimes even if not the link stops working. This is true for both "C" chat window and non-C emerging chat lines.
Expected behavior:
- Cursor changes to a finger
- Hint will appear after a certain time or after a click
Actual behavior:
- Cursor remains arrow
- No interaction with hyperlink. No hint, no click reaction.
2. Almost the same with accessing hyperlinks in Work Parties such as contract board name. Tried to Ctrl-click on it dozens of times .

For both cases it seems there is an invisible hint or hint part which will obscure the hyperlink in terms of click-through but is still invisible to the user. It might be related to the hint appearing previously but not being destroyed properly.

3. In your backpack move an item from one slot to another. Hover over the old (empty) slot and the hint for an item will appear. Not sure if it persists if you close/open backpack can't test this now.

**Comment by olegshegai** [comment]
May be related: 
https://github.com/StrangeLoopGames/EcoIssues/issues/15628
https://github.com/StrangeLoopGames/EcoIssues/issues/15619

**Comment by mirasrael** [comment]
I recently optimized raycasts for links, so it may be related to this. It is why I assigned issue to myself.

**Comment by SlayksWood** [comment]
Problems remained, but for all this there are separate issues.
