### ISSUE TITLE
FuelSupplyComponent optimization

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#15800]
I refactored the component to only be available on client side when player in a vehicle or opens UI to reduce number of unwanted updates, but it still generates lot of updates even for single Fuel Supply Component (like 44 updates for 5 seconds).
But because it now only happens with active UI it becomes lower priority and can wait till 9.1.

**Comment by mirasrael** [comment]
Suggested optimization: Instead of spamming Enabled and Energy updates just send CurrentValue, ServerTime and Consumption Rate.

**Comment by johnkslg** [comment]
This can use the 'must use request' feature I created, and update way less frequently (may have already been fixed)

**Comment by mirasrael** [comment]
This optimization isn't about sending data when not needed (this optimization already implemented), but more about only syncing value when it can't be predicted (like we did refactoring for CraftingTime which now only updated when estimation changed).

**Comment by mirasrael** [comment]
Reviewed code and tested. Seems like already implemented fix for Energy to be on-request only is enough, because it only sends updates when UI opened.
