### ISSUE TITLE
[0.9.0 staging-1514] Work Party: no notification about getting specialty or claims

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15816]
After finishing qork party with skill as payment, Im not getting notification about payment.
It should tell me that I've kearnt a skill and got my claims
![bandicam 2020-04-16 14-04-17-930](https://user-images.githubusercontent.com/27898520/79439132-e558cc00-7fed-11ea-948b-ed7611387472.jpg)
![bandicam 2020-04-16 14-09-42-236](https://user-images.githubusercontent.com/27898520/79439154-ebe74380-7fed-11ea-9ddc-3885232150c8.jpg)

**Comment by johnkslg** [comment]
This is working from what I could see:
![image](https://user-images.githubusercontent.com/3536496/79492440-e03b5300-7fd4-11ea-9070-37d45b3bf81b.png)

Couple things:
- If you create the work party with a knowledge-share payment while holding the book, that payment will be made the moment  a laborer passes the work percentage (shown in screenshot above)
- If the knowledge share is made WITHOUT a book, instead relying on the crafted book being completed, that payment will be made when the book finishes AND is placed into storage (so while it's waiting to be collected, the payment will not be made).  

Can you verify it's working like this?
