### ISSUE TITLE
[0.9.0 Staging 1511] LAN servers do not appear in "LAN" section unless they are on default ports

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15812]
LAN Servers do not appear unless they are on the default ports of 3000 and 3001.

I have tow servers running on the same server, ports 3000/1 and 5000/1 but only the server on ports 3000/1 is appearing.

Other server will show in recent though

**Comment by mirasrael** [comment]
It is intended behavior. We can't scan and spam all ports to identify servers on all possible ports. So it only requests specific port. If you're using custom port then you need to connect to this directly.
