### ISSUE TITLE
[0.9 Staging-1514] Contract time wording - "7:03AM left"

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15828]
Created a contract, someone took it up and marked it as finished, but we had a verbal agreement as to some changes to the contract. I wanted to fail the contract so I can pay them out directly and then I noticed a weird wording on the contract error. Because there is still time to complete a contract, the warning lets you know how much time there still is to complete the work. However, it doesn't list hours / minutes, but instead it's formatted like a time format - "7:03AM left". The "AM" part should probably be changed to "hours" or something.

![image](https://user-images.githubusercontent.com/964559/79522209-f31f4900-800f-11ea-82f7-3196ee947bc3.png)

1) Version
0.9 Staging-1514

2) Steps to reproduce
- Create a contract without auto-accept
- Have someone accept it, mark it as finished
- Try to fail a contract before the timer is up, see the weird error

3) Expected behaviour
- Time should be displayed in "hours remaining", or "time when the contract expires"

4) Actual behaviour
- Time is displayed in "date format AM/PM remaining", which is neither

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79553701-8e163280-80a5-11ea-9bae-372d2fc55893.png)

**Comment by johnkslg** [comment]
TimefFormatter is what you want
