### ISSUE TITLE
Asphalt Migration

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#15824]
We need Migration for the Old AsphaltRoads & Ramps to the new Forms

Now Asphalt use the BuildingBlock and Road would be AsphaltCube. And all the Ramps are now 4 seperate Blocks

**Comment by elfl0rd** [comment]
You might be interested in my suggestion. https://github.com/StrangeLoopGames/EcoSuggestions/issues/908

**Comment by mirasrael** [comment]
I tried you migrated world and seems everything was migrated (even without any migration code):
![image](https://user-images.githubusercontent.com/475445/79580234-63da6a00-80d1-11ea-88e4-c916c5688aaa.png)
![image](https://user-images.githubusercontent.com/475445/79580251-6c32a500-80d1-11ea-8a27-651d0a1546d1.png)
![image](https://user-images.githubusercontent.com/475445/79580311-7ce31b00-80d1-11ea-8d15-da8b2fc5223f.png)

**Comment by mirasrael** [comment]
Discussed. We need to add migration from AsphaltRampItem to 4 AsphaltRoadItem

**Comment by beastyn** [comment]
looks like road block won't migrate
1. 8.3.3
![bandicam 2020-04-22 13-22-44-027](https://user-images.githubusercontent.com/27898520/79959561-b636d480-849d-11ea-9198-b854a70cf29c.jpg)
2. 9.0
![bandicam 2020-04-22 13-31-00-661](https://user-images.githubusercontent.com/27898520/79959578-ba62f200-849d-11ea-92bf-38b7fbf487ca.jpg)

**Comment by elfl0rd** [comment]
because need mogration to asphaltconcrete and correct form, haha :D

**Comment by mirasrael** [comment]
@beastyn please attach save
