### ISSUE TITLE
Server crashing on restart. Unable to boot to crash log.

### ISSUE THREAD

**Issue by Lusafar** [StrangeLoopGames/EcoIssues#1582]
Recently had an issue where the server would instantly crash after a scheduled restart. Was unable to pull a crash log as the server would not generate one. Had to revert to a back up made 12 hours before the restart. The mods in support recommended i put a copy of my game folder on here so devs can check it over if they wish. Game file can be found on the link below. []https://1drv.ms/f/s!As96KLAcLoKJgZoMTO8vcEH5tqkfkw

**Comment by pamduncan** [comment]
I worked with Lusafar on this one.  His server was only producing ClientException logs that were just the usual NullReferences that we see (https://pastebin.com/TQAFpmHx)  - It appeared the server was crashing before it could even write a crash log.  This is a PingPerfect server and interestingling the reason they had to go back to a backup 12 hours old is that somehow the default backup.eco was set to a frequency of 360 minutes between backups and to save 10 backups.  He says he did not change it that it came configured like that when he rented the server.  Not sure if the host is making that change and not aware that 360=6hours or not. (I had him change it to 60 minutes).  This is a 5.5.4  - have not seen a server crashing this hard and fast on 5.5.4 and so asked him to post it for you as it might be something you wanted to see in case it was something that needed to be addressed

**Comment by metachronism** [comment]
I've checked this save in 5.6, and its working fine (after fixing some other misc stuff) - so going to close this out as likely fixed
