### ISSUE TITLE
[0.9.0 staging-1514] Balance Issue: not enough wood pulp

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#15826]
Like #15487 but we still have the problem:

At the moment we are running out of wood pulp on the testserver, its used in many recipes and realy needed for fertilizers, tailor,  paper milling and mason.

Over 4000 are asked in shops, i get ~30-40 per tree = 100 Trees = ~5000 logs and i dont need the logs.
Actually we cant make enough fertilizers for our farm.

There should be a way to make new wood pulp out ouf logs or something from the Logging / Carpenter speciality.

**Comment by elfl0rd** [comment]
I agree, in my opinion it would be nice to get wood pulp when processing logs and lumber.

**Comment by SlayksWood** [comment]
@mepHy86 
But the price has only now increased to 0.1. But it’s still more profitable for me to produce mortar from wood pulp and sell it, mortar price 0,5-1. Why should people sell pulps for you?

**Comment by mepHy86** [comment]
@SlayksWood 
True, but this is not about profatibility, actuall wood pulp is needed in 4 specialities and there is no way except cutting trees to get it and you dont get that much but have tons of logs.

today what we do to fertilize our fields is to use fillers without wood pulp requirements and arrange with it that we get for example nitrogen over 100% what seems to be okay for now.

**Comment by mirasrael** [comment]
Only problem for me now is in player mentality who continue to think about wood pulp as about something very cheap and useless. So using it as fuel, for mortar producing etc which may be easily replaced with other materials. To fix this you should just set good price for wood pulp, so people will prefer to sell it to you.

**Comment by mirasrael** [comment]
In which specialties wood pulp can't be replaced?

**Comment by mepHy86** [comment]
in 3 of 4:
Tailor - Cellulose Fibers
Paper Milling - Paper
Fertilizer if you want the right one that is neded

**Comment by mirasrael** [comment]
We are planning changes to Paper Milling and Tailoring crafts. Paper will be created from Cellulose Fibers and Cellulose Fibers will be created from Natural Fibers (Wood Pulp, Plant Fibers and Kelp). So Paper won't need Wood Pulp anymore (but will be coupled to Tailoring, probably we will move Cellulose production to Paper later after re-balance). For Tailoring Wood Pulp will be replaceable with other raw materials. So it is only unavoidable for Fertilizer what is fine.

**Comment by mepHy86** [comment]
Okay, should be fine  👍 

Can be closed from my side with that information.
