### ISSUE TITLE
QoL - ability to collapse pinned inventories.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15823]
Here you can see how vehicles inventory takes up all the space in the window and cannot be scrolled. Please add the ability to collapse, like the linked inventories.

![изображение](https://user-images.githubusercontent.com/4980243/79501527-dc401d00-8036-11ea-8164-571de340e92d.png)

**Comment by SlayksWood** [comment]
Can you provide full screen?

**Comment by serpopov** [comment]
dup #13180

**Comment by elfl0rd** [comment]
> dup #13180

no, there is about two top inventories, your mention is about "linked inventories" string.

> Can you provide full screen?

It happens with small resolution and with large UI size, but fix is not hard as I think.
