### ISSUE TITLE
[0.9 Staging-1514] Multiple inputs and outputs confuse pipes

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15829]
I have problem with piping water over long distances. Here is my setup. First, 5 water pipes by the shore:

![image](https://user-images.githubusercontent.com/964559/79534461-84ea7e80-802f-11ea-85f6-79479727897d.png)

(5 pumps each taking a separate water input and all connecting to one pipe on the output)

Then, a long single pipe:

![image](https://user-images.githubusercontent.com/964559/79534566-c24f0c00-802f-11ea-86f5-22728878144f.png)

And then my water consumers - two blast furnaces and 3 sinks:

![image](https://user-images.githubusercontent.com/964559/79534624-ed396000-802f-11ea-95f6-8ecb9fd6cfae.png)

(yes, I know a pipe is disconnected in the screenshot)

Sometimes all 5 of these get water and work. Sometimes some of them don't get water and stop working:
![image](https://user-images.githubusercontent.com/964559/79534915-cd566c00-8030-11ea-92d3-e523ec4a4130.png)

There is no way to tell how or why. The sinks at the far end of the connection recognise the water pumps:

![image](https://user-images.githubusercontent.com/964559/79534700-21ad1c00-8030-11ea-988d-20a14906d044.png)

So I'm not sure how to handle it. On top of that, it's hard to debug these things:
- Water pumps don't say how much water they pipe
- Blast furnaces only say how much water is available, not how much they want
- Can't check the pipes for how much water they are actually piping
etc.

It would be nice to have better insight into it for further debugging...

Maybe it's somehow due to pipes having some internal capacity / throughput? If so, it's not clear where to find that information...

1) Version
0.9 Staging-1514

2) Steps to reproduce
- Connect multiple water pumps together into 1 pipe
- Run the pipe over a long distance (100+ meters)
- Connect the pipe into multiple water consumers - 2 blast furnaces, 3 sinks
- Sometimes some of them won't work because of lack of access to water

3) Expected behaviour
- Pipes should work regardless of distance and how many input / output machines are connected, provided enough water is supplied

4) Actual behaviour
- Sometimes some machines won't have water to consume for no apparent reason

**Comment by MishkaFur** [comment]
Seems to be working for me in 1514

2 Water in pipes which go to two sets of 3 pumps which then goes a long distance to what needs the water (two oil refineries))

**Comment by SlayksWood** [comment]
@ThePiachu 
water pump UI is broken #15740
1 water pump give 1 liter per second
1 object consume 0,3 liter per second.


Yea I have this issue too, my blasts stop working. Seems that it works only 1 Water pump.
![image](https://user-images.githubusercontent.com/45708377/79550231-bb141680-80a0-11ea-806c-0ee10ff291a5.png)
![image](https://user-images.githubusercontent.com/45708377/79550387-ef87d280-80a0-11ea-9279-3914551c3729.png)
I also have this problem if I use water pumps near blasts and sinks:
![image](https://user-images.githubusercontent.com/45708377/79551407-493ccc80-80a2-11ea-9044-134184e24fd7.png)

Need check after fixing #15740

**Comment by NN-Mike** [comment]
Maybe we could also have some kind of notification about polluted water being collected also?
Our last playtest found that pollution affected water so much that it stopped producing water input to the nearby furnaces with no real reason why.
After long troubleshooting, putting the input pipe further away into water got it working again.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79731307-c6627e80-82fa-11ea-87f9-6e94462a925f.png)
Work only 1 Sink. Water pump have confusing behavior. If only one Sink works. Only one pump should work. But works 3/4:
![image](https://user-images.githubusercontent.com/45708377/79731328-cebab980-82fa-11ea-8453-1f9f0d45e143.png)
![image](https://user-images.githubusercontent.com/45708377/79731362-daa67b80-82fa-11ea-9fe3-682a50acc258.png)
![image](https://user-images.githubusercontent.com/45708377/79731377-df6b2f80-82fa-11ea-88a9-28045ea79644.png)
![image](https://user-images.githubusercontent.com/45708377/79731383-e2feb680-82fa-11ea-963a-a3f4e682a24f.png)

**Comment by johnkslg** [comment]
I dont think it actually registers if the water being collected is polluted, probably just needed to have the pipe all the way in the water?
It does look like we'll want to display lots more info to users in these cases.

**Comment by mirasrael** [comment]
Yes, problem wasn't with polluted water. It was issue with migration from 1000 units to 1 unit flow.
