### ISSUE TITLE
[8.3.3] [Linux] [Mono 6.8] Unable to start Server (Compile mods)

### ISSUE THREAD

**Issue by pehala** [StrangeLoopGames/EcoIssues#15834]
System: Ubuntu 19.10
Mono: 6.8.0.105

https://pastebin.com/BVUzMY8E

It seems like Mono 6 brought some breaking changes to `System.Range` and `System.Index` but I could be wrong.

**Comment by mirasrael** [comment]
Linux isn't officially supported in 8.3. We have .NET Core and improved Linux support in 9.0.
