### ISSUE TITLE
[0.9 Staging-1514] Some unformatted strings in Electric Machinist Table modules

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15833]
There are some unformatted strings around the Electric Machinist Table modules:

![image](https://user-images.githubusercontent.com/964559/79548915-07346c00-804b-11ea-8f47-721d8ee26433.png)

![image](https://user-images.githubusercontent.com/964559/79548951-19aea580-804b-11ea-8c06-fc30197ef6df.png)

**Comment by SlayksWood** [comment]
dup #15738
