### ISSUE TITLE
[0.9 Staging-1514] You shouldn't deposit tools into a cart if you have blocks in your hand

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15837]
I've been frustrated by this many times while mining. I put ores into a truck / cart and then when the truck is too full to accept any more ores but not 100% full, I will deposit my pickaxe by right-clicking, trying to deposit ores. While I understand why this is happening, from UX perspective, it shouldn't be. Most of the times you won't want to deposit your tools...

1) Version
0.9 Staging-1514

2) Steps to reproduce
- Take a cart
- Fill it with mixed ore so it had 5kg to spare or so (not enough for an ore / rock, but enough for a tool)
- Try to right click to deposit ore
- Deposit tool instead

3) Expected behaviour
- Tool shouldn't be deposited as long as you have ore / rock / whatever in your hands

4) Actual behaviour
- Tool gets deposited, miner is annoyed

**Comment by SlayksWood** [comment]
dup #14911
