### ISSUE TITLE
[0.9.0 staging-1514] Plant Yield : Current Yield does not increase

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#15830]
I made some testfields with like ideal conditions and still get 2 current yield instead of 3 or maybe 4.

Fertilizer was filled before planting Corn and Beets and it was waited for the "server tick" to recognize it.

Tested for Corn and Beets.
![20200417082432_1](https://user-images.githubusercontent.com/63646359/79538679-189a6a00-8085-11ea-8c58-a69c500fda35.jpg)

![20200417082425_1](https://user-images.githubusercontent.com/63646359/79538682-19cb9700-8085-11ea-96a8-f93e49456c9b.jpg)

**Comment by SlayksWood** [comment]
merged to #15163
