### ISSUE TITLE
USER ISSUE: Constant timeout from session

### ISSUE THREAD

**Issue by Gery92** [StrangeLoopGames/EcoIssues#15842]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Connect to a server of your friend
Just wait for 5-10-15 minutes on server

Repeat.

**Expected behavior:**
The red connection lost marker appears on the bottom right, then disconnects.

**Actual behavior:**
The following error message popped up:
```
Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Connection timed out
```

**Comment by SlayksWood** [comment]
@Gery92 Sorry for the wait. Can you help us and provide some information?
1. Are you having this issue with every server?
Can you try to connect to official servers and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. How long do you have this problem? Did you meet this issue after updating to the "latest build" or you had it before?
7. Do you have external IP address? and did your friend use external IP in server config file?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
