### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by furkangt** [StrangeLoopGames/EcoIssues#15840]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>User does not own Eco</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>User does not own Eco</size>
```

**Comment by elfl0rd** [comment]
License? :)

**Comment by D3nnis3n** [comment]
Please use a licensed version of Eco.
