### ISSUE TITLE
Gold Bars not always an option in the Mint

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15841]
In my last server the Gold bar was an option in the mind to back the currency, but in the new server it isn't. Both were on 0.8.3.3. I have no idea why.

As you can see from the following screenshot, a Gold Bar is in the inventory, and I searched for Gold. Gold Ore is an option, but Gold Bar is not. If I search for bar, Iron Bar is the only option.

![gold_bar_not_in_mint](https://user-images.githubusercontent.com/15022396/79594472-ae90bd80-80a2-11ea-9398-8094f55ed297.jpg)

**Comment by elfl0rd** [comment]
any smelter at server?

**Comment by Elliander** [comment]
Users asked me to pre-create the coins to start with a simple currency prior to official launch time with the admin account, so the only objects made would be the mint, treasury, and a single chest to store collateral. That, and the materials for the room itself, set so only the elected world leader can access.

 So if there is no smelter, gold cannot be used as collateral? but iron bars can? That's weird.

**Comment by elfl0rd** [comment]
yes, because it is "undiscovered"
this mechanics changed in 0.9

**Comment by D3nnis3n** [comment]
This works as intended. Only discovered items are visible. If you want to precreate the coins, you'd need to learn the respective skills via scroll to be able to choose it.
