### ISSUE TITLE
Staging Server have no Ground ? Normal oder Bug on creation? (145,10,80)

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1584]

**Comment by MarjieAVolk** [comment]
I can't understand what you mean by this bug

**Comment by REPOSEECO** [comment]
You fall throgh the World no massive Block at 145,09,80

**Comment by MarjieAVolk** [comment]
Yeah there's definitely falling through the world issues - I've seen some on the staging server as well at various times.  Don't see anything at that particular location right now though.

@metachronism is working on this right now apparently

**Comment by metachronism** [comment]
this is something wierd with the world gen, cant repro it anymore
