### ISSUE TITLE
Breakage of the trading table

### ISSUE THREAD

**Issue by aisrog13** [StrangeLoopGames/EcoIssues#15850]
1. Version 0.9
2. After installing the update, the trading table stopped responding to various actions with adding or removing a product. When trying to reinstall it, the problem did not fix, the table is located on the roof of my store. There were also attempts to interact with another player with a similar result. At this time, this error has not been repeated.

**Comment by SlayksWood** [comment]
@aisrog13 
Try to reset persistent data and reproduce it again:
![image](https://user-images.githubusercontent.com/45708377/79744416-f6b41800-830e-11ea-8520-0f4f4b82bace.png)
after that provide log file.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
