### ISSUE TITLE
USER ISSUE: Wrong label on bug report button in french

### ISSUE THREAD

**Issue by Dremor** [StrangeLoopGames/EcoIssues#15858]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Put the game in french
2. Locate the bug report button (current name is "Non")

**Expected behavior:**
Label should be "Rapporter un bogue" or something like that.

**Actual behavior:**
The button shows "Non" ("No" in French) as label.

**Comment by D3nnis3n** [comment]
Translations are handled by the community over at https://crowdin.com/project/eco-by-strange-loop-games.

If you want, you can correct the issue yourself there, but this is the wrong tracker for it.
