### ISSUE TITLE
09-1517 incorrect (lumber) stockpiles highlight and interaction.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15856]
Maybe interfere with https://github.com/StrangeLoopGames/EcoIssues/issues/10771

there you can see incorrect highlight at large lumber stockpile
![изображение](https://user-images.githubusercontent.com/4980243/79640432-40c7bd00-819a-11ea-80e7-58b54829256d.png)

Also i can iteract with blocks inside (all stones, etc) (1st level)
There is unavailable to pickup, but highlighted.
![изображение](https://user-images.githubusercontent.com/4980243/79640454-63f26c80-819a-11ea-9cf5-8edfefed012f.png)

same with lumber stockpile
![изображение](https://user-images.githubusercontent.com/4980243/79640517-ae73e900-819a-11ea-8d26-265d3fceb470.png)

![изображение](https://user-images.githubusercontent.com/4980243/79640500-9b611900-819a-11ea-8a8f-e7f64c788021.png)

**Comment by mirasrael** [comment]
Fixed in SVN.

**Comment by elfl0rd** [comment]
@WeaselDog as i see, after this fix - no problems with t2 stockpiles.
Can you add it back to crafting?
