### ISSUE TITLE
0.9-1517 "Static" storage no more pinned on top.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15855]
![изображение](https://user-images.githubusercontent.com/4980243/79639957-8cc53280-8197-11ea-98df-95898216a228.png)

it SHOULD be pinned, but with ability to OPTIONAL unpin or collapse.

**Comment by D3nnis3n** [comment]
Lost again? :(

**Comment by beastyn** [comment]
because of this #13180
will be fixed
