### ISSUE TITLE
Compost needs an explanation how to make

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#15857]
We need an explanation of how compost works. Most likely in the description of item, but maybe the Ecopedia as well.

**Comment by elfl0rd** [comment]
Also i request something like "compost pit" to compost items without dropping to ground.
![unnamed](https://user-images.githubusercontent.com/4980243/79645270-f30d7d80-81b6-11ea-8c26-6428945d74cf.jpg)
