### ISSUE TITLE
[0.9 Staging-1515] Web graphs don't work

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15861]
Today on the test server we had some pollution issues. A few people have tried going to the web graphs to check things like CO2 levels or sea levels, but it seems the graphs don't work:

![image](https://user-images.githubusercontent.com/964559/79673838-1eca3c80-8192-11ea-9fdf-6ac713c57962.png)

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Go to game's web interface
- Add some data to graphs
- Nothing is shown on the graphs

3) Expected behaviour
- Graphs should show properly

4) Actual behaviour
- Graphs are blank

**Comment by D3nnis3n** [comment]
Prevents understanding of CO2 and therefore any useful measures, leading to unplayable game states.

**Comment by mirasrael** [comment]
It was bug in code. Unfortunately old starts can't be recovered.
