### ISSUE TITLE
Minor authorization dropdown menu bug

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15866]
Staging 1515
Try and add new people to an already somewhat filled auth list for a claim,
dropdown menu selection is interfered by aleady added names.

![20200419021038_1](https://user-images.githubusercontent.com/8851259/79674474-d63b6f00-81e3-11ea-9cb4-51702751a673.jpg)

**Comment by SlayksWood** [comment]
dup #14843
