### ISSUE TITLE
[0.9 Staging-1515] Pollution display is inconsistently shown

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15863]
We tried checking some pollution production on some machines, and it seems the information about how much CO2 pollution something creates is inconsitently shown. For example, this blast furnace displays it:

![image](https://user-images.githubusercontent.com/964559/79674214-af564c00-8195-11ea-92c2-b225fde05122.png)

While this one doesn't:

![image](https://user-images.githubusercontent.com/964559/79674245-fcd2b900-8195-11ea-8174-6dbe86eb3d36.png)

You also don't get the pollution information from the machine's tooltips / ECOpedia entries and such:

![image](https://user-images.githubusercontent.com/964559/79674294-79659780-8196-11ea-85ea-306791572abe.png)

In general, it would be nice to:
- Have a clear information on how much CO2 / polluted water a machine is producing when operating on its Status screen, always displayed
- Have the same information displayed in ECOpedia / tooltip overview of the machines

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Build a few blast furnaces, let them run and stop
- Some of them will have the pollution information, some won't

3) Expected behaviour
- All pollution creating machines should have the information

4) Actual behaviour
- Sometimes the information is not displayed

**Comment by Knigge** [comment]
Added; If this is the goto source for information about how the world is at a glance - this tooltip should give some basic calculation result to show what amount of pollution you can sustain without increasing ppm.

![yodog](https://user-images.githubusercontent.com/8851259/79676152-ece2c580-81e5-11ea-9f8a-1f14718e2d2f.png)

**Comment by mirasrael** [comment]
Fixed to always show pollution info and always it now displays correct info about Air Pollution instead of CO2:

![image](https://user-images.githubusercontent.com/475445/79989006-04f16800-84b8-11ea-848f-37fbe9cb6af1.png)

**Comment by mirasrael** [comment]
Added air pollution info to vehicles and tables:

![image](https://user-images.githubusercontent.com/475445/79994588-d9be4700-84be-11ea-823f-65dadf826d38.png)
