### ISSUE TITLE
Placing blocks when building

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15867]
Staging 1515, but present in all iterations of 9.0 since march.

When attempting to place building-blocks, like glass/bricks and the like, very few pixels are allocated to the spot you actually want to place the block, making building materials to hard to place correctly. They will often be placed in nearby blocks.

Reproduce by placing for instance glass in window config in a single straight row.

**Comment by SlayksWood** [comment]
dup #13956
