### ISSUE TITLE
Queued tasks on a worktable - accessed storage

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15873]
Staging 1515
Que a project on a worktable, view order with another player.

If an order is queued on a worktable, which stockpiles or chests that order can pull from is defined by the person who orders the project.  This causes problems if you are not the initiator of the project, but want to fuel the task, this is especially relevant now that materials needs to be stored before processing. Also an issue if a stockpile that was enabled in the project gets removed and replaced. suddenly an order has no viable inputs or outputs.

Ideally a queued project should show which storage its linked to when selected, and allow any person with access to the claim ability to change which stockpiles the project should be able to pull and push items to.

**Comment by D3nnis3n** [comment]
That's working as intended due to the ability for public use of other peoples worktables via credit payment. It's not a bug at least.
