### ISSUE TITLE
Disparition de mon ATH

### ISSUE THREAD

**Issue by Zayrrix** [StrangeLoopGames/EcoIssues#15879]
A des moments randoms mon ATH disparait et donc je ne peut plus changer d'outil dans ma main par contre je peux encore interagir avec des objets comme le feu de camp ou bien la table de crraft mais je ne vois pas l'interface donc les seules choses que je peux encore faire son bouger casser et poser ce qui limite grandement mon gameplay

Ci joint: un screen du bug

![image](https://user-images.githubusercontent.com/63956811/79686824-78d70a80-8243-11ea-9085-ef82886f8f54.png)

**Comment by elfl0rd** [comment]
alt+z hides UI.

**Comment by Zayrrix** [comment]
merci infiniment j'avais tellement envie de jouer a ce jeu et j'été dégouté de ne pas pouvoir merci encore

**Comment by SlayksWood** [comment]
closed, we have issue #14479 to prevent this problem in future.
