### ISSUE TITLE
Cutting trees bounce around

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15871]
staging 1515
reproduce by chopping wood.

When logs are cut and turned into the object that falls down, they will more often than previously react with physics that are not expected.

**Comment by SlayksWood** [comment]
@Knigge Describe the problem in more detail. Can you provide screenshoots or video?

**Comment by Engimage** [comment]
Trees that are cut down always behaved weird. It comes mostly from their branches interacting with neighbor trees resulting in the weirdest dances and space launches for tree trunks.

I am sure certain limits to the initial movement speed and rotation should be introduced for falling trunks preventing such stuff from happening.

As of now it is totally handled by Unity engine so the change in behavior (if one actually took place) could only come from Unity upgrades.

However I did not notice any unusual behavior, only common space launches. If you plant trees like I do (in every adjacent block) such launches would be pretty common for you as well.

**Comment by SlayksWood** [comment]
merged to #12553
