### ISSUE TITLE
Pollution tooltip needs fix

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#15875]
https://user-images.githubusercontent.com/8851259/79676152-ece2c580-81e5-11ea-9f8a-1f14718e2d2f.png

Seems like the plants do not decrease the pollution, but are a limit at which sealevel starts to rise. The "-" suggests a decrease and not a limit, though.

Actually a change of the mechanic would be even more preferable.

**Comment by mirasrael** [comment]
Actually plants shouldn't reduce pollution. They only consumes CO2, but pollution results in more CO2 in atmosphere. We are now using basic formula for conversion pollution into CO2 where for every ton of pollution in atmosphere it creates 1 ppm of CO2 per tick. At the same time trees consumes Co2 (not air pollution). So until you have enough trees to consume CO2 which is emitting by pollution you're fine (at least with climate changes). Air pollution decay over time so start producing less CO2 until expire. But you can create new air pollution faster than it decays, so it aggregates in atmosphere and so emits more CO2.

**Comment by mirasrael** [comment]
Also 325 CO2 is minimal concentration in atmosphere. You can't go bellow this number.

**Comment by mirasrael** [comment]
Tooltip info now provides more information (also available for non-active Smog Output) and distinguish now between air pollution tons and CO2 ppm.

![image](https://user-images.githubusercontent.com/475445/79988056-de7efd00-84b6-11ea-9d71-abfcc542c34d.png)
