### ISSUE TITLE
[0.9 Staging-1515] Skill books and scrolls not listed in ECOpedia

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15872]
I like using ECOpedia for checking item recipes and availability (much less annoying than typing it in chat for everyone to see). However, it seems the skill books and scrolls as items are not listed in ECOpedia:

![image](https://user-images.githubusercontent.com/964559/79676580-5807aa00-819c-11ea-947a-7e7284bb7fdc.png)

It would be nice to have those items listed, maybe in their own section, somewhere close to the research papers.

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Search for a skill in ECOpedia
- Can't find the skill book or scroll as an item, only professions, modules and such

3) Expected behaviour
- You should be able to find the skill item descriptions, recipes, availability, etc. in ECOpedia

4) Actual behaviour
- You can't find skill scrolls or books in ECOpedia

**Comment by WeaselDog** [comment]
Great feedback. We will get those in there.

**Comment by WeaselDog** [comment]
I ended up only adding the Skill Books as these are the important part for the Ecopedia. The skill scrolls did not provide any meaningful information and were rather boilerplate.

Thanks again for the feedback.
