### ISSUE TITLE
[0.9.0 staging-1519] Civics description in one line can break tooltip

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15889]
Law is like this
![bandicam 2020-04-20 12-23-48-537](https://user-images.githubusercontent.com/27898520/79724944-d598fa80-8301-11ea-8d20-b432efa8fac2.jpg)

Tooltip will look like this
![bandicam 2020-04-20 12-23-56-274](https://user-images.githubusercontent.com/27898520/79724961-dd589f00-8301-11ea-916c-7f1ca1face4a.jpg)

**Comment by serpopov** [comment]
bad looking scroll in other issue
