### ISSUE TITLE
Law - Actions within this day

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#15883]
Version: 9.0 staging-1515

Testing a little bit I wanted to try and make a law that limited an action to x number per day, reset at server's midnight.

In the old law system this was possible like this:
```
where (time preformed > (current time - (current time % 1)))
```
But if the modulus function has been removed, this will be impossible.
See: #15882 

![image](https://user-images.githubusercontent.com/2676134/79693468-1e51a480-826b-11ea-845d-c37676551c2e.png)
It might be useful if the "within hours #" could be changed to "within this day".

**Comment by Deantwo** [comment]
Current workaround, assuming #15882 is fixed:
```
within hours [arithmetic](
left number [world age in hours]
operation [modulus]
right number [number]([24]))
```

**Comment by johnkslg** [comment]
Added new option to Action count, should cover this case and a number of others
![image](https://user-images.githubusercontent.com/3536496/80252327-f2983b00-862b-11ea-8ed6-b0250a8c7145.png)
