### ISSUE TITLE
Law - Missing Math Fuctions: MIN, MAX, FLOOR and CEILING

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#15881]
Version: Version: 9.0 staging-1515

![image](https://user-images.githubusercontent.com/2676134/79692130-ca8f8d00-8263-11ea-80ed-12725228fe9b.png)

We are missing some basic math functions in the law system.

- Min
- Max
- Floor
- Ceiling

Floor and Ceiling only take one value, so maybe need to be different then arithmetic.
Other possibly useful math functions: 

- Abs
- Round (to two, one or zero decimals. rounding up or down)

**Comment by Deantwo** [comment]
Current workaround for `FLOOR`:
```
current time - (current time % 1)
```
Assuming the modulus operator exist.
See: #15882

**Comment by johnkslg** [comment]
Good idea, these will be useful for taxes and other such calculations.
- Added 'Round' which handles min, max, and rounding to nearest, including multiples.
- Added absolute value
- Added floor and ceiling as operations in comparison (at most, at least)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/80046560-d2e40400-84bf-11ea-8f0c-1c479759649b.png)
![image](https://user-images.githubusercontent.com/3536496/80046619-fc049480-84bf-11ea-8067-90d5c32eb496.png)
![image](https://user-images.githubusercontent.com/3536496/80046672-19396300-84c0-11ea-8bcb-60510f67d56d.png)

**Comment by Deantwo** [comment]
How many decimals does `Round` round to? Unsure if we should be able to specify number of decimals. Option between zero, one or two is likely fine.
Rounding down to zero decimals is technically the same as `floor`, and rounding up to zero decimals is the same as `ceiling`.

**Comment by Deantwo** [comment]
> * Added 'Round' which handles min, max, and rounding to nearest, including multiples.
> * Added floor and ceiling as operations in comparison (at most, at least)

I think you confused `min` and `max` with `floor` and `ceilimg`. Took me a while to what you meant.

**Comment by johnkslg** [comment]
Round has an advanced property where you can round to whatever multiple you want.  1 is default, but can do .1, .01, 10, 50, 123213.55, whatever.

And yep misspoke about floor and ceiling, those are handled in round by choosing round up/round down.

**Comment by Deantwo** [comment]
Not totally sure I like the names `at most` and `at least`. Makes it seems a little confusing.
`Max` and `Min` just seem easier, but if you want to have it be more explainatory, you could use `highest` and `lowest` maybe.
