### ISSUE TITLE
Law - Modulo operation missing

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#15882]
Version: Version: 9.0 staging-1515

It looks like the `modulus` function is gone.
![image](https://user-images.githubusercontent.com/2676134/79693132-39231980-8269-11ea-9862-50b1b5f14de7.png)

**Comment by Deantwo** [comment]
As long as the option is called "Modulus" instead of "%", it should cause no issue for it existing

**Comment by johnkslg** [comment]
Added, thanks!
