### ISSUE TITLE
Old links to ecoforum broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15887]
it is redirected to `https://forum.play.ecotopic/958/door-orientation-broke`
`forum.play.ecotopic` ?

**Comment by denysaw** [comment]
What `it`? Give me, please, initial link, which is now wrongly redirects to ecotopic ))

**Comment by elfl0rd** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/568

**Comment by denysaw** [comment]
Tx.

**Comment by D3nnis3n** [comment]
The stuff from the old forums wasn't taken over to the new forums and that is not on the future forums software yet, either. The old links are simply dead.

**Comment by elfl0rd** [comment]
it is not about dead links.
It as about convertation to not-exists address. - forum.play.ecotopic
correct is forum.play.eco/topic

**Comment by denysaw** [comment]
@D3nnis3n Maybe @elfl0rd means, that we could forward users at least to a correct new forum (we could even send them just to a root page). Anyway assigning on @D3nnis3n as it his private server no one has access to. And you further decide to proceed with that or nope :)

**Comment by elfl0rd** [comment]
Yes, in any case redirecting to new forum is better, than redirecting onto void.

**Comment by D3nnis3n** [comment]
That's already fixed.

**Comment by elfl0rd** [comment]
Not.
I see old link - http://ecoforum.strangeloopgames.com/topic/958/door-orientation-broke (at https://github.com/StrangeLoopGames/EcoIssues/issues/568)
If i try to open it, i rederected to non-existent site - https://forum.play.ecotopic/958/door-orientation-broke
![изображение](https://user-images.githubusercontent.com/4980243/79773221-d5b4ec80-8339-11ea-811a-7037020f443e.png)

Because the slash is missed.
Redirecting result must be https://forum.play.eco/topic/958/door-orientation-broke
Not current https://forum.play.ecotopic/958/door-orientation-broke

The content may not be available, but the redirection to a non-existent site - very, VERY bad practice.

**Comment by D3nnis3n** [comment]
Refresh your cache, the link is working fine for me.

GDragon <notifications@github.com> schrieb am Mo., 20. Apr. 2020, 18:07:

**Comment by elfl0rd** [comment]
Ok, fine now.

**Comment by D3nnis3n** [comment]
It's been since i closed the issue ;)

**Comment by denysaw** [comment]
Hehe ) I hate that stupid 301 redirect cache ))
