### ISSUE TITLE
'Continue' button appears in title screen menu even when there is no world to continue

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15885]

**Comment by johnkslg** [comment]
Also while youre in there fix these guys:
![image](https://user-images.githubusercontent.com/3536496/79695256-c09d6800-822a-11ea-934c-113657ae13c8.png)

Minus is off center
copy icon is stretched

**Comment by elfl0rd** [comment]
Also, perhaps the trash can icon would be best for the delete button?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79720003-6a8efa00-82e8-11ea-9845-65ee46003802.png)

**Comment by johnkslg** [comment]
Keeping in 9.0 since its an ugly one for new players

**Comment by SlayksWood** [comment]
I can't see "Continue" button anymore.
I join to server, press disconect:
![image](https://user-images.githubusercontent.com/45708377/80455438-6be9a380-8934-11ea-9865-b67899bb9a68.png)
 I should see Continue, but I don't see:
![image](https://user-images.githubusercontent.com/45708377/80455334-39d84180-8934-11ea-8976-82df5680c8d5.png)

**Comment by gzatravkin** [comment]
Seems work for me. Maybe any specific repro steps? @SlayksWood  https://drive.google.com/open?id=1hmY9w9mo-awYknr9nCwnz5WNc-ndF58C
