### ISSUE TITLE
Yup, thats a table

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1589]
![image](https://cloud.githubusercontent.com/assets/3150561/26797329/69d35dec-49e1-11e7-8a4c-3b34c08a8e92.png)

**Comment by craig-jong** [comment]
Is that a tailoring table? Or a regular table?

**Comment by Nanders** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/1636
