### ISSUE TITLE
Eco Tree: assign progress level to all eco tree features

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#15898]
Each feature on the eco tree needs to have its progress level (1-6  options as seen in key)

@johnkslg you can write this out in a doc and ill input into wordpress. or i can show you how to set it in wordpress (on tree page)

![image](https://user-images.githubusercontent.com/7343272/79806924-6aa9ec80-831e-11ea-8f60-02d60a5e3f64.png)

**Comment by johnkslg** [comment]
@WeaselDog want to take a first shot at this? 
And let me know branches that are thin and need some more writing.

**Comment by WeaselDog** [comment]
Updated them all except Tailoring. It is marked as a future feature but it should be Implemented (In Progress)
