### ISSUE TITLE
[0.9.0 staging-1519] Civics: timer law will work in invalid state 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15892]
1) Make a law like this
![bandicam 2020-04-20 16-41-29-077](https://user-images.githubusercontent.com/27898520/79751316-d6df1d00-832b-11ea-8fdf-ca65d330bd09.jpg)
2) Check if it works
![bandicam 2020-04-20 16-57-31-658](https://user-images.githubusercontent.com/27898520/79751359-e6f6fc80-832b-11ea-8dc7-f1dfabc31837.jpg)
3. Pickup the Court and wait for the Law to become invalid
![bandicam 2020-04-20 17-04-45-163](https://user-images.githubusercontent.com/27898520/79751416-fbd39000-832b-11ea-86ba-6e7d3ff7ece5.jpg)
4. In time the Law will still take an effect
![bandicam 2020-04-20 17-27-17-873](https://user-images.githubusercontent.com/27898520/79751541-33dad300-832c-11ea-891e-250623b20a8d.jpg)

**Comment by johnkslg** [comment]
Found a number of cases where validitiy wasnt being checked for a civics object, this was one of them. Fixed.
