### ISSUE TITLE
[0.9.0 staging-1515] Currencies In Use tab seems borked on the test server

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15899]
When checking the Currencies In Use tab on the test server, it seems borked:

![image](https://user-images.githubusercontent.com/964559/79807622-5a930c80-8320-11ea-9447-0c7121035863.png)

I think this issue was around for about a week+ now. I noticed it when we first shifted the government focus towards a centralised currency, complete with taxes and so on.

1) Version
0.9.0 staging-1515 (and before)

2) Steps to reproduce
- Mint a currency?
- Set taxes?
- ...?
- Check Currencies In Use tab - it only has one currency instead of all the IOUs and currencies

3) Expected behaviour
The tab should display all currencies used

4) Actual behaviour
The tab only displays one currency that's not even used.

**Comment by SlayksWood** [comment]
Need to investigate it.
![image](https://user-images.githubusercontent.com/45708377/79832566-5d3e4200-83b2-11ea-9d46-77f34780f931.png)

**Comment by Engimage** [comment]
For me its the same as ThePiachu. The tab did not contain any used currencies.

**Comment by IcedForge** [comment]
Closing this after verifying no further issues after 9.0 release.
