### ISSUE TITLE
0.9-1519 Some tabs lost icons

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15893]
pump pipes and power
![изображение](https://user-images.githubusercontent.com/4980243/79752796-8365d280-831d-11ea-8fba-bafe1f334c95.png)

filter power and storage
![изображение](https://user-images.githubusercontent.com/4980243/79752766-7c3ec480-831d-11ea-811c-204a93f68c7a.png)

blast furnace pipes
![изображение](https://user-images.githubusercontent.com/4980243/79752826-91b3ee80-831d-11ea-95ae-bc35519eddc0.png)

**Comment by SlayksWood** [comment]
Still some craftable could have wrong icon.
For example Campfire has Powericon for storage:
![image](https://user-images.githubusercontent.com/45708377/79950386-b1632800-847f-11ea-8ac8-5e2979832d74.png)

**Comment by SlayksWood** [comment]
can you check module icon too:
![image](https://user-images.githubusercontent.com/45708377/79950762-377f6e80-8480-11ea-8ee8-46e8be26f072.png)
Seems it's very far.

**Comment by serpopov** [comment]
For campfire: it is good for me, because this is not storage, it is tab about "campfire's power resources"

**Comment by SlayksWood** [comment]
Disagree, you open storage to see linked inventories in campfire, so it should have storage icon. If you want to place power like Coals or logs, you can open Power tab.
In any case Truck has power icon in storage tab:
![image](https://user-images.githubusercontent.com/45708377/80093268-d6819480-856c-11ea-8419-63a6a7982bc5.png)

**Comment by REPOSEECO** [comment]
[0.9.0 beta staging -1526] The campfire storage icon is still Icon the same as the power symbol

**Comment by SlayksWood** [comment]
Missing Autorization and Text now.
Storage didn't have icon

**Comment by SlayksWood** [comment]
Missing contract board icon
![image](https://user-images.githubusercontent.com/45708377/82531631-6bfe4d00-9b48-11ea-99b0-5d219ee7e298.png)
