### ISSUE TITLE
[0.9.0 staging-1519] Civics: broken election process

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15890]
So, what we have:
1. Create Elected title (Mayor for me). Do not elect anyone
![bandicam 2020-04-20 16-02-17-842](https://user-images.githubusercontent.com/27898520/79745245-4dc2e880-8321-11ea-9340-70fb9609229c.jpg)
2. Create an Election Process where only Mayor can Vote (Restricted)
![bandicam 2020-04-20 16-02-14-335](https://user-images.githubusercontent.com/27898520/79745267-63381280-8321-11ea-9673-c282fe04bd14.jpg)
3. Now, lets make an amendment for Districts where election process for changing Districts will be our new one (Restricted)
![bandicam 2020-04-20 16-13-15-774](https://user-images.githubusercontent.com/27898520/79745642-20c30580-8322-11ea-949e-2902d74da63f.jpg)
4. Let's make a district map
![bandicam 2020-04-20 16-03-57-188](https://user-images.githubusercontent.com/27898520/79745701-33d5d580-8322-11ea-8435-52b592e0e83e.jpg)
We can see that election process is the right one
5. And here I will try to vote for it

Expected: I can't vote as I'm not the Mayor
Actual: my vote was accepted

**Comment by johnkslg** [comment]
Good find, fixed!
![image](https://user-images.githubusercontent.com/3536496/79826947-e4a79900-8351-11ea-835a-47f496ec72d2.png)
