### ISSUE TITLE
Composite Lumber Slope surface texture doesn't tile

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15895]
Slope blocks
![20200420190741_1](https://user-images.githubusercontent.com/4980243/79773567-4956f980-833a-11ea-9b71-02badc5248b9.jpg)
![20200420190744_1](https://user-images.githubusercontent.com/4980243/79773561-4825cc80-833a-11ea-962a-ccc3df2d36b2.jpg)

underInnerPeak block to slope
![20200420190747_1](https://user-images.githubusercontent.com/4980243/79773584-4d831700-833a-11ea-8ee6-7c6d300e4ee2.jpg)

**Comment by elfl0rd** [comment]
In my opinion, need a splitter, or a proper merge.

**Comment by keegan-o** [comment]
This is fixed now for slopes with the new forms/materials/textures.
