### ISSUE TITLE
Large Elevator World Object Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15908]
Art for a much larger elevator world object, this will be able to move up and down an interior space of about 6x5x10, big enough to hold any land vehicle.

**Comment by MilenkoTunjic** [comment]
mesh and textures are finished, and the asset is checked in SVN. Needs to be hooked up and set to work.

**Comment by MilenkoTunjic** [comment]
Mesh textures and animations are done, the asset is checked in SVN. Needs to be set up with code in order to work.
