### ISSUE TITLE
[0.9.0 staging-1515] Authorisation list interferes with authorisation dropdown

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15903]
I tried adding someone to my truck authorisation:

![image](https://user-images.githubusercontent.com/964559/79817193-c59d0d00-8339-11ea-8f48-e9df0e1ff5dc.png)

However, I had problems clicking on their name because the list of authorised people behind that screen kept interfering with that dropdown. Had to remove the current authorisations to be able to add someone new.

1) Version
0.9.0 staging-1515

2) Steps to reproduce
- Have a list of people authorised to use your truck
- Try to add someone new
- Try to click on their name in the dropdown
- Have problems because of the names of already authorised people behind them

3) Expected behaviour
The dropdown should reserve that part of the screen to itself

4) Actual behaviour
You can sort of click behind the dropdown and have problems clicking on the actual names in the dropdown

**Comment by SlayksWood** [comment]
dup #14843
