### ISSUE TITLE
Fishing Industry World Object Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15909]
Working through this list of world objects for expanding the fishing industry in a future Eco patch:
Making concepts, checking in with them with Milenko, and working with Phlo to divy up creation of models/final assets.

Fishing Industry World Objects -
- [x] Advanced Fishery Table: This would be the center for endgame small scale fishing products-- the highest tier fishing pole, tackle, baits, lures, etc. This can be thought of as a clean and modern table but more oriented around fishing by hand, with an ice chest and place to process by hand. Sushi and other high end fish food products (or at least their raw ingredients) etc, could be made here.
- [ ] Canning Assembly Line: This is a world object used to can food that would be part of a fishing 
cannery but also could be part of a different type of food factory or processing facility.
- [ ] Automatic Knives Fillet Machine: A machine specifically oriented towards large scale industrial processing of incoming big batches of fish
- [ ] Industrial Smoker: A big smoker for smoking fish and other meats in large batches.
- [x] Crab Pot: A trap for catching crabs, placed in the world.

**Comment by RobertMangano** [comment]
Advanced Fishery is done
