### ISSUE TITLE
Add a Max button to all Crafting stations.

### ISSUE THREAD

**Issue by oct42** [StrangeLoopGames/EcoIssues#15901]
I've gotten so used to it, but on every crafting station when making a bunch of stuff that you have material for you often punch in a rough amount, then single click the counter until it goes red. What if there was just a "Max" button that did the work for you. Like if you have 503 Logs and it takes 6 to make a Hewn Log. 503 / 6 = 83.83... Max 83. If you were in a room full of Eco players you would be able to tell when they were crafting. Just listen for the rapid single clicks of mice as they raise or lower the crafting quantity. Here is a ugly Paint snip.
![ECOMAX](https://user-images.githubusercontent.com/45360573/79811872-31d13e00-8345-11ea-99d5-681035c8549e.png)

**Comment by SlayksWood** [comment]
merged #13334
