### ISSUE TITLE
[0.9.0 staging-1515] Work parties need better defaults

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15904]
I've been using work parties extensively on the test server. While they are great, there are some things I keep having to adjust every time.

First of all, the markers. Sure, they are great if you take up the work party and want to know where to go, not so much when you're the creator. The fact that they display on screen and display when you're not even looking in that direction makes it worse. What's even more annoying is that the markers re-enable themselves whenever the work party gets updated. Not much of an issue if it's just labour, very much an issue if it's a research project that people contribute little bits and pieces to.

Secondly, the reputation payment. Sure, it's great that you pay reputation by default, but giving out your max daily reputation is a bit much. Would be nice if the default was smaller (maybe a 1?), or the default remembered how much you gave out last time.

Thirdly, the payment defaults. It is fine on day 1 or 2, but a week in when there is an actual currency in use it starts to get annoying. You have to go into that default, re-select the payment to have the actual dropdown for paying, select the one currency you want to use out of 100 IOUs, then select your account. It would be nicer if the work parties defaulted to whatever currency and account was used last. At least the process should be: "full payment details are unlocked from the start, then you select your account from a small list (default your personal account you wo't deselect 90% of the time), then you select the currency from the currencies you actually have in your account". More straightforward, less scrolling and selecting things.

Fourthly, the naming. Default naming is pretty great and informative. However, what's not so great is when you change away from the default jobs, select something like "Cooking Research" and you still have the name "Cement party". The default names should update based on the work selected and not update if the user changed the name already.

Fifthly, discoverability. Sure, people can find the work parties in the economy tab, but often you have to ask people to work anyway. It would be nice if the notifications of available work party would display to all applicable users when they log in perhaps - "hey, there is a Glassworking job available. You have the skill, would you like to view it?".

With these improvements the work parties would be a lot more user-friendly.

**Comment by ThePiachu** [comment]
Also, would be nice to be able to change the name of the work party after it's been posted. Maybe up until someone takes it up at least. Sometimes you post a complicated work party and then forget that you misnamed it and either you end up sticking with the name or have to delete the old posting and create a new one just to have a proper name...

**Comment by johnkslg** [comment]
Ill take a pass on some of these, may not get them all for 9 though. Thanks!

**Comment by johnkslg** [comment]
- Defaulted to world markers off screen
- Defaulted to default currency, or personal currency if there is none
- Defaulted to 5 reputation instead of 10

The others will have to wait till after 9, though I definitely want to improve discoverability.

**Comment by SlayksWood** [comment]
I can't check default currency, it's broken now. 
Need to recheck after fixing #16045

**Comment by SlayksWood** [comment]
Seems default currency fixed too:
![image](https://user-images.githubusercontent.com/45708377/82315081-6d5a3900-99d3-11ea-8a5b-443cd638a901.png)
