### ISSUE TITLE
Ability to have  Workbench Making both Softwood and Hardwood Hewn Logs

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#15900]
**Version:** 0.9.0.0 beta staging-1515

As was Mentioned by @johnkslg at the end of the Last Live Stream
**Eco Development Log: Demographics and Wages**
the idea of being able to craft both type of hewn Log to so that players can build the different types depending on the Biome they settled in.
At the Moment ONLY Carpentry table (which requires a room can craft different types) having them being crafted on Workbench will give this option that was mentioned

as of now the Workbench will craft a basic Hewn Log that gives NO XP, so they can craft their first house, maybe add both types of Hewn Logs to this and also give them NO XP as well

**Comment by WeaselDog** [comment]
Great feedback! We are adding these to the workbench.
