### ISSUE TITLE
[0.9.0 staging-1520] Biomes disbalance

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15919]
"Seed": 1383642256. 0,52 world
I have small Biomes(especial Rainforest and Desert) and only 1 big Grassland.
![unknown](https://user-images.githubusercontent.com/45708377/79843612-24f32f80-83c3-11ea-8be6-ddacf19176b9.png)
![unknown (1)](https://user-images.githubusercontent.com/45708377/79843647-31778800-83c3-11ea-97bb-cc93d268117b.png)
![unknown (2)](https://user-images.githubusercontent.com/45708377/79843678-3d634a00-83c3-11ea-8fc8-75e38b556af6.png)

**Comment by mirasrael** [comment]
I'm not sure if we have to perfectly balance all biomes, because we may have completely different worlds and different economy on top of this.

**Comment by WeaselDog** [comment]
There is an issue where sometimes the worlds don't generate correctly and a biome will only be less than 1% of the map when it is supposed to be 10%. Some biomes are more affected than others.

**Comment by WeaselDog** [comment]
@StanKryvenko Need some assistance on this one with the size of the grassland biomes.

**Comment by StanKryvenko** [comment]
> @StanKryvenko Need some assistance on this one with the size of the grassland biomes.

will check

**Comment by SlayksWood** [comment]
Balance is better: Grasland is biggest biome but not in 6 times, something x1,5-x1,8.
