### ISSUE TITLE
plants on other people's property show up as harvestable

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1591]
![image](https://cloud.githubusercontent.com/assets/774628/26797616/4355ef44-49e2-11e7-91e3-b14996070d2d.png)

**Comment by MarjieAVolk** [comment]
Can you actually harvest them?  Or is it just the outline that's green?

**Comment by SeanAtr0n** [comment]
can't harvest, the outline is just green

**Comment by metachronism** [comment]
dupe of #1535
