### ISSUE TITLE
[0.9.0 staging-1520] Civics UI buggies

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15917]
1. Some displacement here
![bandicam 2020-04-21 12-30-45-034](https://user-images.githubusercontent.com/27898520/79839212-9f28b180-83cd-11ea-904c-df211fecdc06.jpg)
2) Some icons issue here and there
![bandicam 2020-04-21 12-41-22-446](https://user-images.githubusercontent.com/27898520/79839241-a8b21980-83cd-11ea-86ff-b497965a6efe.jpg)
![bandicam 2020-04-21 12-42-44-667](https://user-images.githubusercontent.com/27898520/79839244-aa7bdd00-83cd-11ea-9588-3699df0ef64e.jpg)

**Comment by SlayksWood** [comment]
Icons will remain if you delete law:
![image](https://user-images.githubusercontent.com/45708377/79968189-715c6f00-8498-11ea-8a17-670ef19d2087.png)
![image](https://user-images.githubusercontent.com/45708377/79968268-89cc8980-8498-11ea-812d-1293cef1311a.png)

**Comment by beastyn** [comment]
Active law still with displacement
Empty slot has disappeared
Icons are not decided yet
![bandicam 2020-06-26 14-06-01-019](https://user-images.githubusercontent.com/27898520/85840641-43f0b200-b7b6-11ea-83b9-dc04e5f5a511.jpg)

**Comment by SlayksWood** [comment]
Still an issue for empty slot.
