### ISSUE TITLE
Conveyor Belt Animations for Belt Sorter and Coin Mint

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15912]
Hook up and figure out how to get conveyor belts animating properly on coin mint and belt sorter objects.

**Comment by keegan-o** [comment]
Simon is helping out with shader needs, will take care of once we have those locked down

**Comment by elfl0rd** [comment]
Also have not-animated belt
steam engine
machinist table (not have animation at all - https://github.com/StrangeLoopGames/EcoIssues/issues/16744)
assembly line
stamp mill
screening machine
jaw crusher

(maybe i miss smtng)

**Comment by redwyre** [comment]
This should be added to `MaterialEvents` as a standard UV offset (https://docs.unity3d.com/ScriptReference/Material.SetTextureOffset.html) with a configurable amount of u/v movement per second (so you could eg set it to (0,0.1) to only scroll v once every 10 seconds)

**Comment by SlayksWood** [comment]
Seems belt in sorter doesn't rotate, only pulleys https://drive.google.com/file/d/11EfYIfYryFHveKWLtpraiek773zGDEXq/view?usp=sharing

**Comment by redwyre** [comment]
@keegan-o does belt sorter have a belt material?

**Comment by gamer09cod** [comment]
Added texture scrolling to SensorBeltSorter.

**Comment by beastyn** [comment]
Don't see changes
https://drive.google.com/file/d/1xJg6ZR8Fy3w-lY5TyH6EaqTaqILCCmJK/view?usp=sharing

**Comment by keegan-o** [comment]
@redwyre I'm going through the list of objects to add scrolling to and making the needed mesh and texture changes to support the new script being added, but so far I don't see an example of it actually working.
Belt Sorter has it setup but it does not seem to work:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/1b46ecdf-71c4-4172-b30e-b106f6305777)

**Comment by keegan-o** [comment]
Nvm, I see it working on the coin mint! Will setup others to be like it.

**Comment by keegan-o** [comment]
Added scrolling to All objects mentioned by Gdragon (and fixed sensor belt sorter).
