### ISSUE TITLE
[0.9.0 staging-1520] Wood Signs issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15918]
So in any case I have issue for this. I have 2 way to fix it:
1. Fix icons. 
I assume that these signs were planned to be made from composite lumber. Therefore, they all have 3 stars on icons. If we want to create it from hewn log we should change icons with 1 star like hewn door, hewn bench, hewn table and hewn chair.
![image](https://user-images.githubusercontent.com/45708377/79841279-ddb76f80-83bf-11ea-8b15-8b73fcceb784.png)
But I don't like this way. Because you have a lot of wondeful different wood signs from t1 material and you don't need other (lumber signs). So...
2. Move this Signs to Advanced Carpentry table. Change hewn log to Composite lumber(can reduce cost) and we need to add basic Hewn Sign, Hardwood/Softwood Hewn Sign instead this signs.

**Comment by WeaselDog** [comment]
For now we are going with solution 1. Signs will be getting more attention soon.

**Comment by WeaselDog** [comment]
Separate issue for the Lumber signs: https://github.com/StrangeLoopGames/EcoIssues/issues/16129
