### ISSUE TITLE
Icons Art 4/20/2020

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15910]
Icons for new world objects that are missing them so far, specifically:

**9.0 Objects:**
- [x] Stop Sign
- [x] Street Sign
- [x] Modern Street Light
- [x] Double Modern Street Light

**WIP Objects:**
- [ ] Advanced Tailoring Table
- [ ] Loom
- [ ] Garbage, Recyclables, and Compost Dumpster
- [ ] Wooden Barge Boat
- [ ] Modern Barge Boat
- [ ] Shipping Container

**Comment by RobertMangano** [comment]
Street lights are on icon sheet 03, and street signs are on icon sheet 04
