### ISSUE TITLE
0.9 chat blinking

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15929]
https://youtu.be/yCIXlqD1OpU

**Comment by beastyn** [comment]
still blinking on screen
/helpful was used

https://i.gyazo.com/7895e9fe3af8a048c58dda1cba20f9d3.gif

**Comment by SlayksWood** [comment]
my settings to check
/helpful + interface scale 65%
![image](https://user-images.githubusercontent.com/45708377/83496206-6fd38d00-a4c1-11ea-8856-12786fb9c44b.png)

**Comment by Dmittry62** [comment]
Can't reproduce.

**Comment by SlayksWood** [comment]
I can't too, but want to investigate it a little more
