### ISSUE TITLE
0.9 Asphalt conctrete - no connection to ground

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15927]
![изображение](https://user-images.githubusercontent.com/4980243/79891804-2bf16080-840a-11ea-9789-84996189206c.png)

(Happens with all forms)

**Comment by ThePiachu** [comment]
#14849 ?

**Comment by elfl0rd** [comment]
> 
> 
> #14849 ?

?
It is different blocks. Asphalt basically in the ground and space between asphalt and dirt looks ugly.

**Comment by keegan-o** [comment]
fixed in staging
