### ISSUE TITLE
Ashlar Stone Window Builder needs new meshes and rules to fix common cases

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15925]
Should be in every position without top window block like:
![image](https://user-images.githubusercontent.com/45708377/79861782-93dd8200-83dd-11ea-9fe1-cef10a4688a7.png)
If nearby another window block:
![image](https://user-images.githubusercontent.com/45708377/79861732-845e3900-83dd-11ea-804b-1edcccf7591a.png)
I assume it was always, I saw my december's video and find this bug in it.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79861973-f9317300-83dd-11ea-9184-7223147c15e8.png)

**Comment by keegan-o** [comment]
Revamped this whole builder to allow for all 'border' shapes! Hopefully set up rules so that most common side cases are acceptable as well. In staging.
![image](https://user-images.githubusercontent.com/14983165/81366705-29486980-90a0-11ea-8bf3-7773e2a34675.png)
