### ISSUE TITLE
Felled logs disappear?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1592]
Twice in a row, I cut down a tree, went to do something else for a minute, then turned around and it was gone.  I wouldn't expect a tree I cut down to disappear that quickly - maybe in like half an hour, but not in 2-5 minutes.

**Comment by metachronism** [comment]
you sure someone didn't harvest the tree?  trees never disappear until collected

**Comment by MarjieAVolk** [comment]
That's what I thought at first, but I'm pretty sure not the second time, as it was on my property and I stayed very close to it the whole time.  It might have flown away because of physics though, as it was kind of stuck in the wall

**Comment by MarjieAVolk** [comment]
Okay I think I know what's up - they are disappearing when I remove their stumps.  Which I did not expect.

**Comment by SeanAtr0n** [comment]
The logs stick around now after the stump is destroyed, but disappear if you dig under where the stump was located. (Plant gets destroyed at that point)

Think we need to convert felled logs into some sort of world object when their stumps get removed so we can destroy the plant and something else can grow there.
