### ISSUE TITLE
[0.9.0 staging-1515] The Currency Exchange UI needs to be more user friendly

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15920]
I recently had a look at the Currency Exchange in the game and it was rather confusing to try using:

![image](https://user-images.githubusercontent.com/964559/79846431-4b897a00-8373-11ea-9c73-d4b7571396c2.png)

At the first glance - am I selling, or buying owner currency? Is the number in the middle the amount or price? Is it a price expressed in the right or the left currency? What are the two numbers on the right side of the restrictions? What are restrictions even? I did check ECOpedia and was still rather confused.

Ideally, you'd simplify things a little drawing from more traditional exchanges:

![image](https://user-images.githubusercontent.com/964559/79847006-fc901480-8373-11ea-9e0e-0a4d1b1fa39c.png)

First, select account. Then, a clear statement of intent - "I want to buy X GBP for Y USD, exchange rate Z". Set two, third one gets calculated. Post order. Ideally, all currency exchanges would operate on the same global market for currency pairs. Anyone else can come in and see posted orders and take them up or post their own. Sort the orders based on on their exchange rate, converging from both sides

![image](https://user-images.githubusercontent.com/964559/79847522-b4252680-8374-11ea-8a14-873ded73c3eb.png)

**Comment by SlayksWood** [comment]
dup #14419. 
This you can add to suggestion:

> ![image](https://user-images.githubusercontent.com/964559/79847006-fc901480-8373-11ea-9e0e-0a4d1b1fa39c.png)
> 
> First, select account. Then, a clear statement of intent - "I want to buy X GBP for Y USD, exchange rate Z". Set two, third one gets calculated. Post order. Ideally, all currency exchanges would operate on the same global market for currency pairs. Anyone else can come in and see posted orders and take them up or post their own. Sort the orders based on on their exchange rate, converging from both sides
> 
> ![image](https://user-images.githubusercontent.com/964559/79847522-b4252680-8374-11ea-8a14-873ded73c3eb.png)
