### ISSUE TITLE
USER ISSUE: Wrong camera orientation when entering Vehicles

### ISSUE THREAD

**Issue by MKVangen** [StrangeLoopGames/EcoIssues#15923]
**Version:** 0.9.0.0 beta staging-1515

**Steps to Reproduce:**
Sometimes it happens, sometimes it does not. I haven't see any correlations to anything when the bug is there and when it's not

**Expected behavior:**
The camera should face the same direction as before you enter the steam truck

**Actual behavior:**
The camera is flipped about 180 degrees when you enter the steam truck

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. The problem is there without mods.

**Comment by MKVangen** [comment]
![20200421122044_1](https://user-images.githubusercontent.com/37910364/79855354-24f72d80-83cb-11ea-93bc-dff138a93192.jpg)
![20200421122046_1](https://user-images.githubusercontent.com/37910364/79855357-26285a80-83cb-11ea-8597-8e0e93a7caec.jpg)

**Comment by SlayksWood** [comment]
So it happens during placing vehicle. If you place truck and rotate it from default position by Q/R then when you start to drive vehicle you camera will be rotated by this angle.
In 0.8.3 in any case your camera view after starting to drive to vehicle doesn't change.

So we can return this behavior. or just always turn camera to forward
