### ISSUE TITLE
Add documentation or source-controlled settings to prevent setup problem Mark had

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15931]
Regarding setting the compression import settings

**Comment by MarkZaytsev** [comment]
Step added to the Dev Tutorial:

> ![image](https://user-images.githubusercontent.com/50739566/79947320-f6955300-849b-11ea-9092-5e1febb5a252.jpg)

Section in the Troubleshooting Guide:

> ![image](https://user-images.githubusercontent.com/50739566/79947313-f301cc00-849b-11ea-8c81-26b40a5eee36.png)
