### ISSUE TITLE
0.9 Alphalt conctrete - OVER priced.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15930]
recipe with 50% module req 1 crushed + 1.5 concrete.
Concrete with 50% module - 10 crushed.

So, ~16 crushed (80 stones) for ONE asphalt concrete block?
Or 160 stones without modules. lol.

Guys, PLEASE, stop mistaking stone and crushed stone in recipes. 1 crushed stone cost 5 (6) stones.

**Comment by Engimage** [comment]
So it is more about Cement being overpriced not the roads themselves. I have mentioned this as well on the previous test server run.

**Comment by SlayksWood** [comment]
Calculation without talent:
083 max efficiency
Asphalt road = 0,5 cement + 2 stone = (0,5x10stone)+2 stone = **7 stone**.
0.9.0 max modules + jaw crusher
Asphalt concrete  = 1 crushed rock + 0.5 cement = 4 stone + 0.5x5 crushed rock = 4 stone + 10 stone = **14 stone.**
