### ISSUE TITLE
Make staging server build use staging account system 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15932]
Account server is https://auth.develop.strangeloopgames.com/, need to use this instead of the normal account server for staging builds.  
- Find or add a compile flag to the staging build process (talk to Eugene aka Jaskes about this)
- Make the server check for this during compilation

**Comment by johnkslg** [comment]
Sounds like a regex changing the code file before build + comment in code is way to go

**Comment by redwyre** [comment]
This has been done with auth.stagingland.strangeloopgames, and is checked into code so everyone working with staging is using the correct server
