### ISSUE TITLE
Cape item should hide third person tools when equipped

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15937]
When the cape item is equiped in the backpack slot, the third person tools that appear attached to backpack slots should all be disabled-- I think we will want a new kind of flag or class for back items that disable tools from appearing-- this will be useful in the future for more clothing options like dresses, big coats, etc.

**Comment by SlayksWood** [comment]
@StanKryvenko 
Can you hide it if avatar hasn't backpack? #12382
