### ISSUE TITLE
Teacher issue

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#15933]
Also, I have a strange problem still.  I can login, and I can see my subscriptions, but I can't actually set them to 0 for worlds or accounts, they are stuck at 1 and 8, and while I can go up, I can't take them down.  At the top of my screen its saying "Newly bought Items are processing".  guessing there's something going on behind the scenes that's causing it to be confused.

**Comment by denysaw** [comment]
Need his/her login to test it myself from his/her account. It's proper, that he can't decrease world/citizen field. For that thing we had Remove World/Citizen buttons below. Need credentials to check.

**Comment by rainfarmer** [comment]
db editing error
