### ISSUE TITLE
Reinforced Concrete art (texture) need to be updated

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15936]
This is noticed by many users, and now after the remake of the other blocks - the only "bad" is him.

**Comment by keegan-o** [comment]
The texture is now updated, and as far as forms go, it's highest on the list for additional forms to match the new sets-- they'll happen for the first decent sized patch after 9.0 (or may even get into 9.0 if it stretches out longer than we think it will)

**Comment by elfl0rd** [comment]
but bad "cyan-green" color is still exists :(
and reinforced concrete blocks still looks bad.

**Comment by keegan-o** [comment]
where is the cyan green color?
Reinforced Concrete is the set that got the texture update-- there are many things to improve about the set, and I intend to add tons of forms and probably new mesh art/replacements for the weird old metal on it, but the texture is now more or less fixed.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81333574-aa304280-9059-11ea-9302-99d9078a055a.png)
Are there other blocks than reinforced concrete that are still using the old texture or something?

**Comment by elfl0rd** [comment]
Okay, sorry :) it is a global illumination issue. (my house is a near ocean).
