### ISSUE TITLE
[0.9.0 staging-1515] Cast Gear is a weird recipe...

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15944]
In the Electric Machinist Table, you can use the Cast Gear recipe:

![image](https://user-images.githubusercontent.com/964559/79952205-ea26e100-842e-11ea-98df-9a256344aa8d.png)

It takes a steel bar and turns it into two iron gears. This seems to be an upgrade of the Shaper's Iron Gear recipe:

![image](https://user-images.githubusercontent.com/964559/79952371-2eb27c80-842f-11ea-9cda-a1a2ff3681ff.png)

First of all, the materials seem a bit mismatched - you're turning steel back into iron.

Secondly, cost-wise, it's not that great of savings if you consider having to smelt iron into steel.

Thirdly, the Electric Machinist Table doesn't really use Iron Gears by itself, so it's a very strange recipe to have there. You mostly use it in conjunction with other iron parts:

![image](https://user-images.githubusercontent.com/964559/79952533-6d483700-842f-11ea-9d4c-0400e26ddbd9.png)

So really, the recipe could be removed without impacting anything...

Maybe instead we could have the higher tier electric machines producing the iron parts as well but at a higher efficiency instead...

**Comment by WeaselDog** [comment]
Thanks for the feedback. We will be removing this recipe as we have the new Steel Gear now.
