### ISSUE TITLE
logging yield doesn't seem to do anything

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1594]
Guess we didn't have an official issue for this, not sure if anyone was working on it

**Comment by metachronism** [comment]
looks like craig broke this?  I kind of think this skill shouldn't exist though...

**Comment by SeanAtr0n** [comment]
last week we thought you might have broken it when you made it so logs can't be cut too small

**Comment by craig-jong** [comment]
The skill is absolutely, ridiculously bonkers.

It was broken all of last week and I'm pretty sure I fixed it... It's a tech tree gen issue.

**Comment by craig-jong** [comment]
It does work so I'm going to close this - if you're testing this on your own builds you might want to try rebuilding the tech tree generator.
