### ISSUE TITLE
Didnt have permissions to /spawn store 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15941]
![image](https://user-images.githubusercontent.com/3536496/79923718-0143df80-83eb-11ea-95e7-def9045a6bc4.png)

**Comment by mirasrael** [comment]
It is not admin command. It is only for QA (devs). So you can only run this in local development environment.

**Comment by WeaselDog** [comment]
Do we want to change this behavior so that dev-tier can use these commands if they are also an admin? I think the original issue we wanted to solve not having admin access on all servers.

**Comment by WeaselDog** [comment]
@johnkslg Follow up on this one. This can happen if you are hosting a server on a different computer you can connect with, even if it is the same network.

Was this the case here and do we want to change the behavior?

**Comment by mirasrael** [comment]
@johnkslg said we can close it.
