### ISSUE TITLE
New UI Icons: Low Durability Effect Overlay, and Face Equipment Slot Icon

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#15940]
Face Equipment Slot matching this style:
![image](https://user-images.githubusercontent.com/14983165/79920460-043bd180-83e5-11ea-8c54-2883c26e9be5.png)

For the Low Durability Effect Overlay, we want a 64x64 size sprite that is a solid glowy looking border, with perhaps a mostly transparent layer filling in the inside space. Do it in white so that it could be potentially used for other effects, but to test how it looks, tint it red and put it on top of a tool icon, and imagine it is fading in and out.  This will be applied on top of tools that are low durability so the player knows they are about to break. It will probably pulse very slowly so it's not annoying if the player doesn't intend to fix them anytime soon.

**Comment by keegan-o** [comment]
@serpopov  Milenko: Ok checked it in, it is in UI_elements sprite sheet, top row last sprite on the right

**Comment by MilenkoTunjic** [comment]
Done :)

**Comment by WeaselDog** [comment]
@keegan-o Closing as it looks complete, but reopen if needed.
