### ISSUE TITLE
[0.9.0 staging-1515] Government wages are taxed

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15949]
When paying out wages, the government taxes them:

![image](https://user-images.githubusercontent.com/964559/79969021-c7ec8d80-8445-11ea-8b85-d45dcefaea8a.png)

Which is a silly thing of moving the money from Treasury and taking a part of it back to the Treasury. There are our taxes:

![image](https://user-images.githubusercontent.com/964559/79969223-0d10bf80-8446-11ea-87c4-b4aa92a449a8.png)

Either the flag for government accounts doesn't work, or in general government transactions shouldn't be taxed.

1) Version
0.9.0 staging-1515

2) Steps to reproduce
- Set taxes
- Set wages
- Whenever a wage is paid out, it is taxed

3) Expected behaviour
Government spending shouldn't be taxed

4) Actual behaviour
Tax is applied on wages provided by the government

**Comment by trickenso** [comment]
As a counter to this:

- You might wish income tax revenue and government wages to be paid into/out of different accounts.
- It is more difficult to compare government and non-government wages if one has income tax attached and the other doesn't. Much more clarity if they are equivalent (or at least if they display both before- and after-tax figures clearly)
- Government wages are almost-universally taxed in real life. I would certainly not expect my government job to be exempt from income tax by default.

On some level I agree that it's just numbers moving around arbitrarily, so make it an option, maybe, but making this mandatory sounds odd to my ear. Doubly so if it makes it harder to compare easily a government wage with a private work party, or similar.

**Comment by beastyn** [comment]
@johnkslg This can be reasonable to distinguish taxes for wages and sales. What do you think?

**Comment by IcedForge** [comment]
This should no longer be the case after 9.0 release as well as rework to wage system.
