### ISSUE TITLE
[0.9-1515] Item transfer number bug

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15951]
Start my having 2 stacks of items. One stack is 100, another 20. Drag and drop the 100 stack on top of 20.
Expected - 20 becomes 100, old 100 is returned to its place as 20.
Actual - 20 becomes 40 (doubles its number), 100 returns as 80.

**Comment by SlayksWood** [comment]
it will change in next staging build, but we already have some bugs, so you can test it (after staging update) and add your ffedback here #15954
