### ISSUE TITLE
[0.9-1515] bitten by animal overlay when using hammer and pressing f 

### ISSUE THREAD

**Issue by BennoHase** [StrangeLoopGames/EcoIssues#15958]
I was bitten by a wolf and this black "overlay" was activated. The one you get when the wolf bites you. These black points in the middle, sorry, I don't know the exact expression for it.

From then on, it always happened when I used a hammer and changed the shape with F. The black overlay came every time, although no wolf bit me again. Press F => overlay.

**Comment by Engimage** [comment]
I can confirm this being an issue. Will use that bite screen every time until game client restart.
