### ISSUE TITLE
[0.9.0 staging-1515] Skid sometimes has problems loading onto a (Steam) Truck

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15950]
I've ran into this problem a few times - the skid sometimes has problems loading items onto a Truck / Steam Truck:

https://youtu.be/gLJE9C0r2yI

The Truck just doesn't register until you exit the Skid, enter the Truck, exit the Truck and enter the Skid again. Then it usually works.

On a related note - the Truck loading geometry is a little iffy for a Skid. You'd think you can easily load items onto the back of the Truck, but as it turns out the front is a lot more reliable. It would be nice if that got touched up, perhaps generally givign a Skid a longer deposit range (so it doesn't get flung off when loading) and the Truck's trunk could have a better coverage on that front.

1) Version
0.9.0 staging-1515

2) Steps to reproduce
- Have a truck
- Enter a skid
- Mine
- Try to deposit onto the truck, sometimes it won't register
- Exit skid, enter truck, exit truck, enter skid
- Now you can deposit from the skid

https://youtu.be/gLJE9C0r2yI

3) Expected behaviour
You should always have the option to deposit from the skid onto the truck as long as you are close enough

4) Actual behaviour
Sometimes the truck doesn't register as a valid deposit location for the skid

**Comment by TwixterZ** [comment]
Able to reproduce issue in current 9.3.5 Release 231 

https://youtu.be/BYtX0nP83Ls

Reproduction steps as above

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in 9.6
