### ISSUE TITLE
[0.9-1515] Roof Block placement with a hammer targetting issues

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15955]
When building the white outline with an item ghost should define the spot where theblock is placed. However this is not the case at the moment. Most of times the ghost actually "lags" behind the real pointer and very often the block gets placed in a wrong position.

This might contain several issues.
First one can be easily reproduced if you try to place a ladder upwards when you are climbing one and try to extend it. Most probably the ghost is in correct position (extending the ladder) but the block will be placed behind your back.

The second symptom is when you pick a block and move your cursor through existing block, starting from one side of it ending with another. The ghost will remain attached to the first side even if you hover another one. You will have to move your cursor away from the block and move it in so that the desired side is the first which the cursor meets.

The third issue - not so long ago I was able to jump and put a block on top of another one during the jump (to build a building first wall as you can't do it in a sane way by pointing to the block's edge). But now with this ghost "lag" the task is impossible to do.

This might be related to mirasrael's fix for object outline flickering.

**Comment by NN-Mike** [comment]
Regarding jump block placing, I noted this and found some more info in testing:

Stand in the center of a block
Look down and place a block, you now have an error an object blocks path (you) Look away and look back down you can't place it.
Jump up while looking away from under your feet, as long as you look down before you land, you can place the new block (also possible twice if you're super fast - resulting in getting stuck in the block)

Stand at the edge of a block, you can place freely as much as you like jump placing


The floating stairs form in new materials is impossible to place a new block ontop of and results in placing them sporadically all around it instead

**Comment by SlayksWood** [comment]
@Engimage @NN-Mike 
It was changed in latest staging
Can you provide your opinion after update playtest version to staging-1528+

**Comment by trickenso** [comment]
Placing blocks against roof blocks is a bit unintuitive still:

This situation works well - targeting the edge of a block tries to place a block to the side:
![image](https://user-images.githubusercontent.com/48172405/81019212-18a8b100-8e5e-11ea-9f07-a9c4a902278a.png)
No change needed here.

This doesn't work so well - trying to place a block directly on the side tries to place it below, which feels odd:
![image](https://user-images.githubusercontent.com/48172405/81019440-92409f00-8e5e-11ea-8435-21449989383f.png)
It would make more sense if this placed the block to the side - the narrow edge of the roof block seems to be the problem. Maybe the 'edge' should be proportional to the size of the side of the block?

This is very weird - Moving very slightly down moves the ghost block to the next roof block along:
![image](https://user-images.githubusercontent.com/48172405/81019366-6ae9d200-8e5e-11ea-8f14-764cd5efc859.png)
Wouldn't expect this to happen at all - should still be placing blocks adjacent to the targeted roof.

**Comment by trickenso** [comment]
Another example:

This looks good:
![image](https://user-images.githubusercontent.com/48172405/81027772-d6d83480-8e76-11ea-9a0d-59d7ed7c6ca1.png)

This is not so good - expect to build adjacent block at the same height as the roof, not below:
![image](https://user-images.githubusercontent.com/48172405/81027804-f96a4d80-8e76-11ea-80ee-ffaeb21ab21b.png)

This is very weird indeed - in this position the block flickers between two positions:
![image](https://user-images.githubusercontent.com/48172405/81027831-1272fe80-8e77-11ea-84a8-0f7782ea783a.png)

Then this is back to being ok:
![image](https://user-images.githubusercontent.com/48172405/81027867-333b5400-8e77-11ea-8080-0f03ef60c1d0.png)

**Comment by trickenso** [comment]
These would preferably target the top of the wall:
![image](https://user-images.githubusercontent.com/48172405/81393722-bdeeae00-9118-11ea-88a8-602eebb55839.png)

![image](https://user-images.githubusercontent.com/48172405/81393836-e4ace480-9118-11ea-85a2-d9533e3cf9e5.png)

Some composite lumber flat roof examples:
![image](https://user-images.githubusercontent.com/48172405/81394533-f773e900-9119-11ea-83f0-41b610ce6530.png)

![image](https://user-images.githubusercontent.com/48172405/81394682-3bff8480-911a-11ea-9ed0-01e97089c502.png)

![image](https://user-images.githubusercontent.com/48172405/81394713-4caffa80-911a-11ea-87f6-0004918521a5.png)

![image](https://user-images.githubusercontent.com/48172405/81394754-5a658000-911a-11ea-9c91-42d4bfb3487f.png)

**Comment by SlayksWood** [comment]
Roof need to fix.
Another fill types is intended behavior. Improvements planned but not in 0.9.0
