### ISSUE TITLE
Pollution tooltip improvements

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15957]
As detailed here:
https://github.com/StrangeLoopGames/Eco/pull/5978

**Comment by mirasrael** [comment]
For Smog output:

![image](https://user-images.githubusercontent.com/475445/80082520-2bb5aa00-855d-11ea-9ccc-ad8dfb54b264.png)

**Comment by Engimage** [comment]
We have met a problem that this crucial info is not available anywhere outside smog output of machines, and those have to be working at that moment. And when the machines are disabled by law this info is not available by any means.

There should be a way for everyone to easily see this information on demand. Graphs on the site (even if those were actually working) will not help as the info here is much more detailed.

It makes sense to create a smart hint for some keywords like "Pollution", "Smog" or "CO2" to display the global CO2 statistics.

**Comment by mirasrael** [comment]
It will be added to Ecopedia

**Comment by mirasrael** [comment]
For status tab:
![image](https://user-images.githubusercontent.com/475445/80089494-b4851380-8566-11ea-9179-878a37991999.png)
