### ISSUE TITLE
Windmills can be in the ground

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1595]
This is valid, it rotates and produces power for the mill:
![image](https://cloud.githubusercontent.com/assets/23460210/26802488/8579e07a-49f5-11e7-8742-da1f71a5c42d.png)

**Comment by Uniphix** [comment]
I do noticed that one time I saw a player put a watermill on a spot where there was no water somehow and was able to still provide power?  Has this already been fixed with 5.6?

**Comment by MarjieAVolk** [comment]
I'm not sure - that should be in a separate bug
