### ISSUE TITLE
USER ISSUE: Version built 1521 No Movement, No Worktables

### ISSUE THREAD

**Issue by Lauterna** [StrangeLoopGames/EcoIssues#15956]
**Version:** 0.9.0.0 beta staging-1521

**Steps to Reproduce:**
Relog after update to server Stresstest
![image](https://user-images.githubusercontent.com/63421534/80012576-ccf51f80-84cd-11ea-8d29-4914604c1efb.png)

**Expected behavior:**
normal use

**Actual behavior:**
all i can use is without any personalty and withour any usage.
The same is happen to Caracter Reyman, Superfretchen, Möbi, Sonduku (he had solve it with complet reinstall incl. erase all app data).
![image](https://user-images.githubusercontent.com/63421534/80012458-a800ac80-84cd-11ea-9b30-b15048f277a1.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Comment by Lauterna** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4517905/Player.log)
my log to the issue

**Comment by Lauterna** [comment]
@jaskes

**Comment by jaskes** [comment]
Game save from the server https://eco-public-files.s3-us-west-2.amazonaws.com/Game-2020-04-23.zip

**Comment by johnkslg** [comment]
Loaded the linked save and moved and crafted fine. Maybe fixed since then? Kicking off staging build.

**Comment by Sekor2600** [comment]
Search is up in the Corner
![grafik](https://user-images.githubusercontent.com/37456949/80149431-f2118d00-85b6-11ea-9b39-529336bcaa49.png)

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/80156075-50446d00-85c3-11ea-9114-36e212e57cb9.png)


-Open a CraftingTable and you have a starnge Crafting Component that you can´t remove or finish.
You can not start a other Project.

-Owned by PersonNameHere
- Search from Credit is in the Corner 
![grafik](https://user-images.githubusercontent.com/37456949/80156205-9ef20700-85c3-11ea-898e-7d6b12162f48.png)

**Comment by Lauterna** [comment]
Good Morning from Germany,
yes sinse last update my Eco is back to use^^

Thanks for Help, we look for, if all known user are able too Play again.

![image](https://user-images.githubusercontent.com/63421534/80173632-beebef80-85f0-11ea-996c-d135022508c3.png)

**Comment by beastyn** [comment]
@Sekor2600 
Did you have it on playtest with 1524?

**Comment by beastyn** [comment]
Still have it. Can't reproduce locally nor with playtest. Need some help here. Looks like a lot of refrences were just lost

**Comment by SlayksWood** [comment]
> Open Avatarmenu in Backback or create new World
> ![grafik](https://user-images.githubusercontent.com/37456949/80157267-13c64080-85c6-11ea-9175-1faa438aa372.png)
> 
> -You don´t see your Avatar and only have Hair in the Options.
> 
> * Back, Shirt, belt etc have only 1 Hair as Option
>   ![grafik](https://user-images.githubusercontent.com/37456949/80157331-39ebe080-85c6-11ea-88b4-5819a15c2e19.png)
> 
> You can not close the menu with Save/Cancel and ESC. You're stuck in the menu

**Comment by SlayksWood** [comment]
@ThePiachu
> After the recent update, I'm unable to move on the test server:
> 
> https://www.youtube.com/watch?v=sWR7M_H5Q38
> (this is a video of me mashing the movement keys with no avail)
> 
> 1. Version
>    0.9 Staging-1524
> 2. Steps to reproduce
> 
> * Log onto the test server?
> * Be unable to move?
> 
> 1. Expected behaviour
>    You should be able to move.
> 2. Actual behaviour
>    I can't...
> 3. Providing Log files
>    [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4525175/Player.log)

@MishkaFur
> Seems to be affecting Shadowrider too, /unstuck moves the char for him but I was not affected somehow, only difference being I was on my own server before connecting to Royal otter after the 1515 build
> 
> I can dig the ground out below him so can he but his char does not fall back to ground level, if i place dirt under him it lifts him up and his feet are level with the ground but soon as I remove the dirt he drops down to hovering about half a block above the ground
> 
> ![image](https://user-images.githubusercontent.com/61889138/80156464-e2e10e00-85bb-11ea-836b-2b9986dad46a.png)

@Shadowrider0
> Yep, tried joining another 9.0 server with Mishka's help and got stuck in character creation. All icons in creation showed hair. In the picture I have boots selected yet shows hair still. Same on all buttons, hair. Also Save and Cancel just click, but no action.
> ![image](https://user-images.githubusercontent.com/64047782/80157398-1b6cf180-8594-11ea-9ccc-dea1cc031a4b.png)

> Just had SammieJade login and she has the same issue. Can't move and appears to be floating

**Comment by SlayksWood** [comment]
> Not sure what is wrong with the list of people on line on the test server, but it got borked with the last update:
> 
> ![image](https://user-images.githubusercontent.com/964559/80148083-59a0eb80-8569-11ea-8d49-c187cd6bbd2c.png)
> 
> 1. Version
>    0.9 Staging-1524
> 2. Steps to reproduce
> 
> * Check the objectives tab
> * List of people online is a placeholder
> 
> 1. Expected behaviour
>    People's online status should display as normal
> 2. Actual behaviour
>    It does not
> 3. Providing Log files
>    [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4525153/Player.log)

**Comment by mirasrael** [comment]
It was crash on player entering the world, so many things wasn't initialized as they should. If you will see any of these problems after fix applied please make an another issue.
