### ISSUE TITLE
Web EcoMap: `Districts` layer returns Error 400

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#15959]
![image](https://user-images.githubusercontent.com/5720101/80033730-831c3180-84ed-11ea-9d56-95707d2f3552.png)

Should return a layer :)

Mention @beastyn here just for her to know :)

**Comment by beastyn** [comment]
I can't find Districts layer anymore.
Did you decide to remove it?

**Comment by gzatravkin** [comment]
@beastyn it shows district maps instead. Proabably you had no any active district map if you didn't have it

**Comment by gzatravkin** [comment]
![image](https://user-images.githubusercontent.com/53317567/83148164-0291b780-a0cf-11ea-9ae5-73d060326f49.png)

**Comment by gzatravkin** [comment]
https://github.com/StrangeLoopGames/Eco/pull/6158 - fix for not updating districts list (now it updates every 40s)
