### ISSUE TITLE
[0.9.0 staging-1522] Civics: law without votes can' be activated

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#15967]
1. Create a law
![bandicam 2020-04-23 11-34-22-620](https://user-images.githubusercontent.com/27898520/80068378-f444fe80-8558-11ea-978f-e29116d8c521.jpg)

2. Do not vote
![bandicam 2020-04-23 11-34-28-752](https://user-images.githubusercontent.com/27898520/80068397-fb6c0c80-8558-11ea-9817-edecf35f5e7a.jpg)
3. Use /ff
![bandicam 2020-04-23 11-53-14-405](https://user-images.githubusercontent.com/27898520/80068427-0de64600-8559-11ea-805a-f56cd4de759e.jpg)

Expected: Law shoud be failed in 24 hours (by default).
Actual: Law was activated

**Comment by johnkslg** [comment]
Good find, fixed:
![image](https://user-images.githubusercontent.com/3536496/80153931-590d5280-8573-11ea-8bbd-2c0124d3201d.png)


Some repro tips: you can use /civics ticknow to force an election to update, otherwise its on a 5 minute timer. I made a short election process for testing this.
