### ISSUE TITLE
/help --> command is faulty

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1596]
**see also #472
this will be major overhauled soon (from 21.03.2016)** 

Example
/level [x(default=10)],[y(default=10)],[BlockType(default=GrassBlock)] — Levels the ground from the player position to x,y blocks away with the specified block.
Is no Chatcommand
&
is missing • /players — display online players names

**Comment by metachronism** [comment]
closing, this system is under overhaul, and this bug is no longer relevant
