### ISSUE TITLE
0.9-1524 modern street lamp and doubled modern street lamp need new icons

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15974]
![изображение](https://user-images.githubusercontent.com/4980243/80131514-077cbc00-85a3-11ea-8096-2d1f54fdbf03.png)

**Comment by Sekor2600** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/15910

**Comment by elfl0rd** [comment]
thx
