### ISSUE TITLE
Chopping tree trunk into logs causes longer and longer game freeze.

### ISSUE THREAD

**Issue by NafenX** [StrangeLoopGames/EcoIssues#1597]
After chopping only one or two trees, suddenly each 'chop' of the axe will cause the game to freeze. First it's only a second, but each time I make another chop it will result in a longer and longer freeze until eventually the freeze is so long that I'm kicked from the server for inactivity.

If my friend is nearby at the time this happens, he also freezes every time I chop. If I restart the game and come back and start chopping, it's fine again BUT my friend will still freeze longer and longer each time I chop until he also restarts. We believe it may be something to do with being near the world border, but I swear I've chopped trees around 60 blocks away from the border and it's still frozen like this.

**Comment by metachronism** [comment]
Is this still occurring for you on latest 5.6 staging builds?

**Comment by NafenX** [comment]
We'll be moving over to 5.6 staging to test it within the next day or so, when we do should I build near the world border again?

**Comment by metachronism** [comment]
closing pending performance improvements in a6
