### ISSUE TITLE
0.9-1524 stuffed wolf have 3 benefit than others stuffed animals (4)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15975]
Wolf - 3
![изображение](https://user-images.githubusercontent.com/4980243/80131664-3dba3b80-85a3-11ea-88b9-ef19f8099a33.png)

All others - 4
![изображение](https://user-images.githubusercontent.com/4980243/80131692-4579e000-85a3-11ea-8aca-92c1f4168476.png)

**Comment by SlayksWood** [comment]
It's intented behavior. It has less repeat yield.

**Comment by elfl0rd** [comment]
It's very strange, in that case the recipe should be cheaper. It's the same now and it looks bad.

**Comment by elfl0rd** [comment]
I guess as a result of this, stuffed wolves just won't be crafted.

**Comment by elfl0rd** [comment]
> It's intented behavior. It has less repeat yield.

wolf 80, others 90
srsly? difference lower than one point from.

**Comment by SlayksWood** [comment]
1st jaguar = 4 house point, second 0,4
1st wolf  = 3< second 0,6

**Comment by elfl0rd** [comment]
And like I said, there's no point in making wolves.
With an equal crafting value, 1 another stuffed animal brings in more points than a two wolf.

**Comment by SlayksWood** [comment]
2 stuffed jaguar = 4,4
1 stuffed jaguar + 1 stuffed wolf = 4,6

**Comment by elfl0rd** [comment]
The difference is still too small.
Besides the wolf _one_ stuffed animal with different settings.

**Comment by mirasrael** [comment]
@WeaselDog can you confirm it is intended?
