### ISSUE TITLE
[9.0 1524] Ashlar stone roof using basalt texture

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15973]
Appears Ashlar stone roof side, peak etc (other than cube) is using the basalt texture not the same texture as Cube or Ashlar stone cube

![image](https://user-images.githubusercontent.com/61889138/80129404-ead68900-858e-11ea-98b3-391f4c19aabe.png)

**Comment by keegan-o** [comment]
fixed in staging
