### ISSUE TITLE
0.9-1524 modern street lights have not usefull occupancy

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15976]
![изображение](https://user-images.githubusercontent.com/4980243/80131937-a5708680-85a3-11ea-8375-f1ad0c5aa780.png)
![изображение](https://user-images.githubusercontent.com/4980243/80131960-af928500-85a3-11ea-826e-708f3a8cd291.png)

Also you can target it only at ground.
![изображение](https://user-images.githubusercontent.com/4980243/80132027-c3d68200-85a3-11ea-8b64-7fbbc2a4ed5b.png)
![изображение](https://user-images.githubusercontent.com/4980243/80132047-c9cc6300-85a3-11ea-8738-398215e8ff48.png)

**Comment by SlayksWood** [comment]
dup #15971
