### ISSUE TITLE
[9.0 staging 1524] Streetsign - Unable to place blocks under overhanging part also incorrect icon

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15972]
1. 9.0 1524
2. Steps to reproduce. try to place something small under the street sign
3. Expected behavior. able to place something ie a chest
4. Actual behavior. It is blocked, as if the sign is 3 wide and 1 deep

Also has a incorrect icon, makes it look like it is a wooden sign

![image](https://user-images.githubusercontent.com/61889138/80125496-a399c980-8589-11ea-93fd-e49271a310c6.png)

**Comment by SlayksWood** [comment]
for icon we have another issue #15910
haven't any problem with under block and occupancy:
![image](https://user-images.githubusercontent.com/45708377/80180278-15febe00-860b-11ea-8b3b-4220e356ae39.png)
![image](https://user-images.githubusercontent.com/45708377/80180323-2fa00580-860b-11ea-8ab8-77c56c1e110e.png)

Can you provide some screenshots?

**Comment by MishkaFur** [comment]
Hmmmmmmm cant seem to do it again, I wonder if it was coincidentally due to me placing the sign too close to the lamp with its overhang issues, will close this as it looks to be fine :)
