### ISSUE TITLE
[0.9.0 staging-1522] typo "CTRL"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15970]
![image](https://user-images.githubusercontent.com/45708377/80081389-8ea64180-855b-11ea-830e-4017f8e81f80.png)

**Comment by MishkaFur** [comment]
Should probably also not say "taked position" but perhaps "Click at an area already in a district to erase"

**Comment by trickenso** [comment]
"click at" also reads oddly to me, and it's unclear whether it's a left- or right-click that erases. You don't need more suggestions, but how about something like:

Define District Area
Hold right-click and drag to draw district. Right-click highlighted area to erase. Press CTRL to switch between view and edit modes.

**Comment by SlayksWood** [comment]
Change "Right-click highlighted area to erase" to "Right-click an existing district to erase".
