### ISSUE TITLE
0.9-1524 modern street lights on|off has no difference (not working)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15977]

**Comment by MishkaFur** [comment]
1525 they have a difference unless you have global illumination enabled, further info is useful.

**Comment by WeaselDog** [comment]
Hi. I am not able to reproduce this in the latest staging. When I turn it on and off it does change the lighting. Are you still experiencing this?

**Comment by SlayksWood** [comment]
They shine poorly, but is it a lighting problem? This is a another issue

**Comment by MishkaFur** [comment]
@WeaselDog 

If you have GI on and a modern streetlamp on it does not light up the area, Soon as you turn off GI you can tell when the light is or or off.

Light is on, GI on

**Comment by MishkaFur** [comment]
![Untitled](https://user-images.githubusercontent.com/61889138/82665579-fe2b5180-9c2b-11ea-8843-82d73431557a.jpg)

**Comment by MishkaFur** [comment]
GI off, light on

![GI OFF light on](https://user-images.githubusercontent.com/61889138/82665766-64b06f80-9c2c-11ea-9ea5-7fcca903b1eb.jpg)
