### ISSUE TITLE
[9.0 staging 1524] unable to place blocks under overhanging part of the new street lamps

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15971]
1. 9.0 1524
2. Steps to reproduce. try to place a block under the overhanging part of the new streetlamps
3. Expected behavior. you can place the block
4. Actual behavior. it is blocked despite it having physically alot of space, it is acting like the whole base is 5 wide and 1 deep for the double and 3 wide n 1 deep for the single

Also all the lamps have same icon

**Comment by MishkaFur** [comment]
Update, also the entire "base" of the lamp needs to be solid, you cannot have them overhanging something as it needs solid ground, these two lamps will not power on due to no solid floor

![image](https://user-images.githubusercontent.com/61889138/80134406-a0590a80-8596-11ea-9c7b-4b01547a1a68.png)

**Comment by MishkaFur** [comment]
Also seems the collision box is too big, cannot move under the "framework" of the lamps, can move under the bronzey bit that has the lamp in it but not the silvery metal structure

Happens on foot or in a vehicle

![image](https://user-images.githubusercontent.com/61889138/80143840-5592bf00-85a5-11ea-895b-c1fa204dea24.png)

**Comment by SlayksWood** [comment]
![изображение](https://user-images.githubusercontent.com/4980243/80131937-a5708680-85a3-11ea-8375-f1ad0c5aa780.png)
![изображение](https://user-images.githubusercontent.com/4980243/80131960-af928500-85a3-11ea-826e-708f3a8cd291.png)

Also you can target it only at ground.
![изображение](https://user-images.githubusercontent.com/4980243/80132027-c3d68200-85a3-11ea-8b64-7fbbc2a4ed5b.png)
![изображение](https://user-images.githubusercontent.com/4980243/80132047-c9cc6300-85a3-11ea-8738-398215e8ff48.png)

**Comment by SlayksWood** [comment]
for icon we have another issue #15910
