### ISSUE TITLE
[0.9 Staging-1524] Unable to move on the test server

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15982]
After the recent update, I'm unable to move on the test server:

https://www.youtube.com/watch?v=sWR7M_H5Q38
(this is a video of me mashing the movement keys with no avail)

1) Version
0.9 Staging-1524

2) Steps to reproduce
- Log onto the test server?
- Be unable to move?

3) Expected behaviour
You should be able to move.

4) Actual behaviour
I can't...

5) Providing Log files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4525175/Player.log)

**Comment by MishkaFur** [comment]
Seems to be affecting Shadowrider too, /unstuck moves the char for him but I was not affected somehow, only difference being I was on my own server before connecting to Royal otter after the 1515 build

I can dig the ground out below him so can he but his char does not fall back to ground level, if i place dirt under him it lifts him up and his feet are level with the ground but soon as I remove the dirt he drops down to hovering about half a block above the ground

![image](https://user-images.githubusercontent.com/61889138/80156464-e2e10e00-85bb-11ea-836b-2b9986dad46a.png)

**Comment by Shadowrider0** [comment]
Yep, tried joining another 9.0 server with Mishka's help and got stuck in character creation. All icons in creation showed hair.  In the picture I have boots selected yet shows hair still.  Same on all buttons, hair.  Also Accept and Cancel just click, but no action.
![image](https://user-images.githubusercontent.com/64047782/80157398-1b6cf180-8594-11ea-9ccc-dea1cc031a4b.png)

**Comment by Shadowrider0** [comment]
Hey Look the meteor is back. Is the meteor shard in third person while I am stuck :).
![image](https://user-images.githubusercontent.com/64047782/80157702-bc5bac80-8594-11ea-9bf1-a2cfdd0b3f8a.png)

**Comment by Shadowrider0** [comment]
Just had SammieJade login and she has the same issue.  Can't move and appears to be floating

**Comment by SlayksWood** [comment]
merged #15956
