### ISSUE TITLE
Timestamp on staging build is 1912

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15985]
![image](https://user-images.githubusercontent.com/3536496/80154707-046ad700-8575-11ea-9b67-ba0f555cba1e.png)

**Comment by mirasrael** [comment]
It was an issue with deterministic compilation in .NET Core (read more [here](https://stackoverflow.com/questions/1600962/displaying-the-build-date) in comments). I replaced it with just current build date, doesn't makes much sense to use version assembly compilation time.
