### ISSUE TITLE
[0.9 Staging-1524] List of people online is borked on the test server

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15981]
Not sure what is wrong with the list of people on line on the test server, but it got borked with the last update:

![image](https://user-images.githubusercontent.com/964559/80148083-59a0eb80-8569-11ea-8d49-c187cd6bbd2c.png)

1) Version
0.9 Staging-1524

2) Steps to reproduce
- Check the objectives tab
- List of people online is a placeholder

3) Expected behaviour
People's online status should display as normal

4) Actual behaviour
It does not

5) Providing Log files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4525153/Player.log)

**Comment by MishkaFur** [comment]
This might be related to your inability to move, Mephy was having things go weird for them once they did manage to move.

![image](https://user-images.githubusercontent.com/61889138/80155680-220e5f80-85ba-11ea-91aa-ae442bdad787.png)

**Comment by SlayksWood** [comment]
merged to #15956
