### ISSUE TITLE
[Staging 9.0 1525] Create Avatar broken

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#15987]
Open Avatarmenu in Backback or create new World
![grafik](https://user-images.githubusercontent.com/37456949/80157267-13c64080-85c6-11ea-9175-1faa438aa372.png)

-You don´t see your Avatar and only have Hair in the Options.
- Back, Shirt, belt etc have only 1 Hair as Option
![grafik](https://user-images.githubusercontent.com/37456949/80157331-39ebe080-85c6-11ea-88b4-5819a15c2e19.png)

You can not close the menu with Save/Cancel and ESC. You're stuck in the menu

**Comment by SlayksWood** [comment]
merged to #15956
