### ISSUE TITLE
[0.9-1524] small wood cart not working

### ISSUE THREAD

**Issue by BennoHase** [StrangeLoopGames/EcoIssues#15991]
Small wood cart isn't working anymore. 

If I use a small wood cart, I pick up the drawbar and automatically release it immediately.
the normal wood cart works.

**Comment by beastyn** [comment]
Thank you for the report. Please, provide a log file and video (if possible)
Indtruction is here
<https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file>

**Comment by SlayksWood** [comment]
Can't reproduce it. Please reopen when you can provide us with necessary information
