### ISSUE TITLE
[0.9] Fake plants disappear when you cross Zero point

### ISSUE THREAD

**Issue by dylanMz** [StrangeLoopGames/EcoIssues#15992]
Hello,
error display of flower pots mainly (causes lag) 
when the players pass the end of coordinates (0; 720)

![20200424095828_1](https://user-images.githubusercontent.com/44091507/80189803-90334080-8613-11ea-8080-d81a722fd7dd.jpg)
![20200424095835_1](https://user-images.githubusercontent.com/44091507/80189806-92959a80-8613-11ea-8874-ca264a6ffb18.jpg)

**Comment by Engimage** [comment]
On the latest test server zero point went right near my house. Every time you cross it screen flickers massively. There is an issue for this but I could not find it.
