### ISSUE TITLE
[0.9.0 staging-1525] Double placement marker delete its name.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15993]
Step to reproduce:
- open minimap, markers tab:
![image](https://user-images.githubusercontent.com/45708377/80196349-f7f28700-8625-11ea-9bab-38648542f6fe.png)
- don't move minimap.
- drop marker, change it color and name:
![image](https://user-images.githubusercontent.com/45708377/80196407-1062a180-8626-11ea-98c4-c1328a32acd9.png)
- press drop marker another time. Marker name will be deleted, but color will be remained:
![image](https://user-images.githubusercontent.com/45708377/80196483-283a2580-8626-11ea-9499-870ee321380a.png)

**Comment by IcedForge** [comment]
Function works but it has an odd description from a user point of view.
![Screenshot_4.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/75ee191f-c338-427f-a20b-fca3081a542c)

This should be:
-"There is already a marker on this position?"
or
-"There is a marker at this location already"

**Comment by tuha263** [comment]
@IcedForge  thank you, I will change it.
