### ISSUE TITLE
[0.9.0 staging-1526] UserStatusBar glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15998]
![image](https://user-images.githubusercontent.com/45708377/80205379-2e82ce80-8633-11ea-95c2-1a0da5def8f8.png)

Step to reproduce:
- claim some property:
![image](https://user-images.githubusercontent.com/45708377/80205481-5a05b900-8633-11ea-9f02-80e82e0252eb.png)
- start to drill outside from this property:
![image](https://user-images.githubusercontent.com/45708377/80205533-70ac1000-8633-11ea-84a0-07d42d689da3.png)
- when Drill UI is opened, move to property:
![image](https://user-images.githubusercontent.com/45708377/80205638-a3ee9f00-8633-11ea-9f2e-054d8d49f811.png)
- close drill UI:
![image](https://user-images.githubusercontent.com/45708377/80205673-aea93400-8633-11ea-80dd-825e0c65e795.png)

**Comment by SlayksWood** [comment]
UserStatusbar is unclickable now . I need to change it to click on it. do previous steps. Now Toolbar is visible, but I can't click on it:
![image](https://user-images.githubusercontent.com/45708377/80451838-7e141380-892d-11ea-94d8-e8cf279666a0.png)
I should change this tooltip then I can click on it again. For example I can enter in room:
![image](https://user-images.githubusercontent.com/45708377/80451889-a26ff000-892d-11ea-812c-4f8f98727ce1.png)
or go out , go in this property.

**Comment by johnkslg** [comment]
Make sure theres not multiple tweens being called
Change to use DOTween instead of iTween

**Comment by gzatravkin** [comment]
I can't to repro it at last staging (video).
Any specific repro steps? Please attach video of repro with grabbing of cursor 
https://drive.google.com/open?id=1z6RbL3Ni1tfDtvNQe6Kr8D14QHAPFnn8

**Comment by SlayksWood** [comment]
Don't Use Esc, close it by "X"
https://drive.google.com/file/d/1Gc7UFdEZ_8kxF9IqJvTv6TQKuTHPKZpW/view?usp=sharing
