### ISSUE TITLE
[Balance Issue] Compost and Sewage

### ISSUE THREAD

**Issue by Elliander** [StrangeLoopGames/EcoIssues#15990]
When operating a smelting business, I took great care in preventing ground pollution via a carefully crafted tailing pit. I then worked towards getting the blast furnace thinking that it would be better since it produces less tailing pollution. 

1st Problem: In order to built a filter you first have to have steel which means that dumping sewage is a requirement of the game, yet there are no mechanics in place for cleaning up this pollution. The water does begin to clear up after two days, but I should be able to, say, use a pump directly attached to a filter to clean up the initial pollution. Environmental cleanup is a thing, after all.

 Now, once the filters were up and running I assumed that the resulting compost would be safe to handle, just like in real life.

2nd Problem: Compost has the same ground pollution spread as tailings, but is worse in that the description makes no mention of this! Compare the entry for compost to the entry for tailings:

Compost: Delicious decomposed organic matter.

Tailings: Waste product from smelting. When left on soil the runoff will create pollution (etc)

I only found out because when looking at the scientific data the pollution was so much worse where I set out for farmers to take for free than I ever produced before. In effect, it ended up being worse than tailings  in that there's no indication of the dangers in game. 

Compost should NOT be treated as nuclear waste. The end result will be to discourage it's intended purpose of being turned into fertilizer because I cannot store it safely above ground and because I cannot entrust it to another player who will then bring it to their farmland and destroy their ability to produce food if they store it anywhere near their farms.

At worst, compost should be mildly polluting. A single solid block surrounding the stockpile room should be sufficient to prevent the spread at worst, and I should be able to bury it under a single block thick of dirt and expect it to not only be safe, but turn into dirt eventually just like in real life. 

There's nothing intuitive about the way the compost works in this game, and in fact I'd go so far as to say that the pollution from sewage was not nearly as bad as the pollution from compost, especially when you factor in the air pollution generated by running the generator to run the filters. All compost production does is increase the amount of ground pollution spread produced in temporary storage near the surface at a faster rate.

 Now, if for whatever reason it IS intended for compost to be the source of the biggest ecological disaster the world has ever seen, it should be made clear to the players and there needs to be tools for the player to not only observe the ground pollution spread, but the reversal of ground pollution so the player can know that they are cleaning up or not.

**Comment by SlayksWood** [comment]
Thank you for your feedback. What game version do you play?

Compost doesn't give any pollution: neither air, nor ground.
Place compost on grond, in wood cart, stockpile and steam truck:
![image](https://user-images.githubusercontent.com/45708377/80183783-21091c80-8612-11ea-9401-4ae1b29df1c5.png)
Wait a several days:
![image](https://user-images.githubusercontent.com/45708377/80183988-7fce9600-8612-11ea-9e49-04d5ce7e0ab0.png)
![image](https://user-images.githubusercontent.com/45708377/80183998-8230f000-8612-11ea-86e8-dd352de2ff63.png)
I don't have any polution.

> In order to built a filter you first have to have steel which means that dumping sewage is a requirement of the game

I assume it's intended for now that you can't start to use Waste filter in same time with Blast Furnace.
@mirasrael @WeaselDog 
Is it right?

**Comment by D3nnis3n** [comment]
Given Discord, his pollution was caused by air pollution dropping to the ground as ground pollution via rainfall, Compost wasn't involved.

**Comment by mirasrael** [comment]
Compost doesn't create any pollution and seems it was demystified now. Yes, it is intended you can't start using ecological machines at beginning. You can't fully avoid impact on environment, but can try to minimize it.
