### ISSUE TITLE
[0.9.0 staging-1525] Not all vehicle has air pollution in Ecopedia.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15995]
![image](https://user-images.githubusercontent.com/45708377/80197246-10af6c80-8627-11ea-9b7f-4b395e1ae707.png)
![image](https://user-images.githubusercontent.com/45708377/80197259-13aa5d00-8627-11ea-912e-bf0b1058875d.png)
![image](https://user-images.githubusercontent.com/45708377/80197268-160cb700-8627-11ea-95e7-2493bf40a0f0.png)

**Comment by mirasrael** [comment]
@WeaselDog you need to fill Pollution in tech tree for these vehicles. So they will generate [AirPollution()] attribute.
