### ISSUE TITLE
[0.9.0 staging-1525] Skill UI doesn't remember last open specialty

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15994]
It always open 1st specialty in 1st profession. Step to reproduce:
- open butchery specialty in Skill UI:
![image](https://user-images.githubusercontent.com/45708377/80196901-a0a0e680-8626-11ea-8685-90648dc68d22.png)
- close and reopen Skill UI. Now it has opened Logging in Carpenter:
![image](https://user-images.githubusercontent.com/45708377/80196968-b44c4d00-8626-11ea-9394-d700d5f5cdf3.png)

**Comment by mirasrael** [comment]
1. Check if it has cacheDestroyDelay > 0.
2. If it has then check if on open it doesn't reset selected values.

**Comment by gzatravkin** [comment]
added cache time (180)
