### ISSUE TITLE
Alpha 5.5 - Cannot remove a claim having a locked chest on it without crashing with an exception

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#1599]
**Pre-requirement:**
- In Alpha 5.5.4

**Description:**
When I unclaimed one of my claim section using my deed, the game crashes with an exception if the claim section was containing a locked chest.

**Steps:**
1. Claim one section of land;
2. Put a chest on that claimed section of land;
3. Locked that chest;
4. Remove the claimed section of land (unclaim).

**Result:**
    The game crashed with an exception.

**Expected Result:**
    The claim should be removed and the lock on the chest should be removed automatically.

**Workaround:**
If you unlock the chest and after remove the claimed section of land, it will remove claim without producing an exception.

**Note:**
A print screen of the exception is coming soon.

**Comment by MarjieAVolk** [comment]
This seems to be fixed after extensive auth changes in the current version
