### ISSUE TITLE
Hosted Worlds: account was deleted after purchasing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16002]
1. Purchase a world and citizens with the new account
2. Try to purchase some new citizens
3. Account is deleted

**Comment by denysaw** [comment]
Will be on `developland` in 5 minutes (deployment).

**Comment by D3nnis3n** [comment]
Haha, nice one.

**Comment by denysaw** [comment]
@D3nnis3n The funniest thing, it was like that on Production from 2017 year ;)

**Comment by D3nnis3n** [comment]
So our customers deleted themselves when they wanted to purchase from us? That's satirical in itself.

**Comment by denysaw** [comment]
Maybe not always, but it could have happened, sure :) yep ) Self-destructive kamikadze-customers )
