### ISSUE TITLE
USER ISSUE: Lower CPU maximum improves performance, higher decreases

### ISSUE THREAD

**Issue by legendddhgf** [StrangeLoopGames/EcoIssues#16006]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I ran into some random slowness issues, which sometimes resulted in everyone being kicked from the server. I tried to increase max CPU per tick to 50% (World.eco), and while I thought this might help, long term it made things worse. Then I set it to 20% (below the default) and it became better. I don't understand how this can be but this sounds like some sort of game bug so I thought I should mention it

**Expected behavior:**
Increasing maximum CPU usage should result in better/equivalent performance, not worse?

**Actual behavior:**
increasing maximum CPU caused excessive lag spikes while also increasing CPU usage

**Do you have mods installed? Does issue happen when no mods are installed?:**
No special mods, just some minor configuration changes

**Comment by mirasrael** [comment]
In 9.0 lot of improvements for performance (including better multi-core utilization). Need to re-check if this is still an issue on latest version.
