### ISSUE TITLE
USER ISSUE: Difficulty.eco Collaboration setting does nothing

### ISSUE THREAD

**Issue by legendddhgf** [StrangeLoopGames/EcoIssues#16005]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Attempt to change collaboration setting and nothing else from Difficulty.eco, observe that the eco game server will end up with the default collaboration setting regardless

**Expected behavior:**
It should have changed the collaboration setting

**Actual behavior:**
It did nothing, I had to change specialtycostmultiplier from 1 to 0.25 to get to very low collaboration

**Do you have mods installed? Does issue happen when no mods are installed?:**
No special mods, just vanilla besides changing various configuration options

**Comment by D3nnis3n** [comment]
Works as intended, the Collaboration setting just sets the other values when using the GUI.
