### ISSUE TITLE
[0.9.0 staging-1515] Updates to chat mess up scrolling

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16007]
Sometimes you want to see what has been said in chat earlier but you're having problems because people keep talking and that keeps resetting your scrolling. It would be nice if when you scroll up in the chat new messages coming in wouldn't make you lose your place.

1) Version
0.9.0 staging-1515

2) Steps to reproduce
- Scroll up in chat
- Have someone else say something in chat
- You will lose your place in the scroll and reset back to the bottom of the chat

3) Expected behaviour
Once you scroll away from the bottom of the screen the window shouldn't reset you down to the bottom when a new message appears.

4) Actual behaviour
Whenever a new message appears your scroll resets to the bottom.

**Comment by mirasrael** [comment]
When chat scrolled to the bottom you should auto-scroll. Otherwise just keep current scroll position.
