### ISSUE TITLE
[0.9.0 staging-1526] Can't see the time of day or date when Sleeping

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#16003]
Version: 9.0 staging-1526

When sleeping it is impossible to see what time of day it is and what date it is.

I am able to write the `/time now` command while sleeping, but I cannot see the chat while in the bed.

![image](https://user-images.githubusercontent.com/2676134/80234349-4f114f80-8658-11ea-8120-2625757a0777.png)

Simply add something similar to the `/time now` command's output to the window.
Example:
```
Day 12, 13:52
```

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-261.

Sleeping modal now shows current in-game time.
Closing.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8a1c1bc7-f67d-44f9-9754-fc03474520bf)

**Comment by Deantwo** [comment]
You don't have to replace the current _time passed_ text, having both would be fine.
