### ISSUE TITLE
[0.8.3.3 beta] NaN Currency and Tax on Infinite

### ISSUE THREAD

**Issue by lagonnebula** [StrangeLoopGames/EcoIssues#16019]
Hello,

We found an issue with tax and players currencies (not minted currency).
A law as been passed that tax all player to 1% but one had Infinite Crédit ( because it was his money) and the game send Infinite credits to the Treasury and put the player to NaN

cf : Screenshot
https://files.meuhmeuh.fr/images/Eco_RJYe3ECl4x.png

We tried to do the same thing, the treasury gave again 1% of his balance to the player and the player and the treasury was put to NaN. 

One other issue is the money stiil existed but was not visible from the Money tab of the economy UI.

**Comment by SlayksWood** [comment]
Can't reproduce in 0.9.0. Create law like:
![image](https://user-images.githubusercontent.com/45708377/80342409-d0413000-886c-11ea-9eeb-2321dfbf6d58.png)
try to mine:
![image](https://user-images.githubusercontent.com/45708377/80342462-e4852d00-886c-11ea-8d65-45c449ee2891.png)

@lagonnebula 
Can you provide example of your law?

**Comment by lagonnebula** [comment]
Is there a way to get deleted law ?
Otherwise I ll try to recreate it.

**Comment by lagonnebula** [comment]
If you want i have the saved world with the issue

**Comment by SlayksWood** [comment]
@lagonnebula thank you, I'll investigate it to complete fixing in 0.9.0

**Comment by SlayksWood** [comment]
Staging-1577 I still can't find any way to reproduce in 0.9.0. So closed for now.
![image](https://user-images.githubusercontent.com/45708377/83631452-388adc00-a5a6-11ea-923f-9b2d4816e4e5.png)
