### ISSUE TITLE
[0.9.0 staging-1526] Trying to vote for constitution: error: No constitution found, cannot execute civic actions until one is formed.

### ISSUE THREAD

**Issue by BarikSHL** [StrangeLoopGames/EcoIssues#16012]
What we do for this situation:
Player B crafted Capitol.
Player A builded a house, claim the territory and place Capitol, Player A gave autorization for player B.
Player A made a house bigger.
Player A and B added and delete 3 articles.
Player B changed Everyone on Active in all options.
Player B send constitution to ratification.
After trying to vote for constitution it's:
Error: No constitution found, cannot execute civic actions until one is formed.
![2020-04-25_19-57-15 (2)](https://user-images.githubusercontent.com/64322204/80285899-c61a1700-8730-11ea-90c5-d9125c3b6776.png)

**Comment by beastyn** [comment]
@johnkslg 
Seems like ratification election is broken,
Just place a Capitol and Ratify.
Try to vote and you will have this error.

Can we add CI test with this voting simulation?

**Comment by johnkslg** [comment]
Fixed, and added test to CI covering ratification elections (part of SpawnGov now, it now makes the constitution ratify instead of just dropping it into that state).
