### ISSUE TITLE
0.9 Contract Board

### ISSUE THREAD

**Issue by Cakdom** [StrangeLoopGames/EcoIssues#16011]
0.9 10 person test server
Attempt to make new contract or work party after having started a contract then clicked the "x" to close the contract creation window. 
Expect to be able to make contracts and work parties but get error that I have to finish posting the incomplete contract which I have no way of accessing. Tried deleting all current work parties and hammering the board and re-placing it in different spot still same error. 
![20200425001424_1](https://user-images.githubusercontent.com/64107215/80285831-3acb6200-86ed-11ea-88db-38127501e1ab.jpg)

**Comment by Cakdom** [comment]
Well I just found the draft contract in the economy viewing and was able to delete it from there and now it is working!

**Comment by trickenso** [comment]
Might be useful if drafts were visible from the contracts board, so this isn't so mysterious.
