### ISSUE TITLE
[8.3.3beta] Putting a ladder one block behind entrance reduce house tiers

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#16014]
![image](https://user-images.githubusercontent.com/339611/80292218-3d61a200-8755-11ea-8d0c-0a824ef005e7.png)

The house is built with only tier 1 material but the room is at 0,96 tiers. However, removing the ladder behind the highlighted in red block make it back to 1. This only happen if the ladder is one block behind entrance. If it's in the house or at the entrance it doesn't reduce tier.

edit : same issue with stairs

**Comment by SlayksWood** [comment]
It's intented behavior.
You increase room volume. this space now part of room do you need to fix empty corners.
You have room with 95 volume:
![image](https://user-images.githubusercontent.com/45708377/80340627-a5a1a800-8869-11ea-9d2c-12b72a25d06f.png)
You place laddder (or any another block) here. Now you have 96 volume:
![image](https://user-images.githubusercontent.com/45708377/80340711-cff36580-8869-11ea-8966-7f8f77d38665.png)
You should fill empty corners.
@mirasrael is it intented?

**Comment by matheod** [comment]
Shouldn't the ladder be in a new room ?

**Comment by WeaselDog** [comment]
This is indeed intended behavior. There is a solution for this where you can place a door and it will not expand the size of the room.

Thanks for your contribution.
