### ISSUE TITLE
[0.9 Staging-1526] Removing a law makes its icons linger in the empty slot

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16010]
I was messing around with laws. I created a law forbidding a placement of an item, which came with the appropriate icon. Then when I removed it with an instant removal, the icons lingered in the empty space it left behind:

![image](https://user-images.githubusercontent.com/964559/80278724-780fff80-86ad-11ea-94e9-3894224baa5f.png)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Have the power to instantly pass a law?
- Create a law with icons
- Remove that law
- The space left behind will still have the icons the law had

3) Expected behaviour
The icons should clear when the law is removed.

4) Actual behaviour
The icons persist after the law is gone.

**Comment by trickenso** [comment]
This is already reported [here](https://github.com/StrangeLoopGames/EcoIssues/issues/15917#issuecomment-617678274)

**Comment by SlayksWood** [comment]
dup #15917
