### ISSUE TITLE
1526 Server Crash (Linux Server)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16015]
From Log, as no dump generated:

> [00:44:09.380] [23] [Error] [Eco] System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'arrayIndex'))
> 
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
>    at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
>    at System.Collections.Immutable.ImmutableList`1.Node.CopyTo(T[] array, Int32 arrayIndex)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at Eco.Simulation.RouteProbing.RouteManager.UpdateRegions() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Simulation\RouteProbing\RouteManager.cs:line 288
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Plugins\PluginTickTimer.cs:line 30
>    at Eco.Simulation.RouteProbing.RouteManager.Update() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Simulation\RouteProbing\RouteManager.cs:line 319
>    at Eco.Core.Serialization.StorageExtensions.Modify[T](T storage, Action`1 action) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Serialization\StorageExtensions.cs:line 15
>    at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\PeriodicWorkerFactory.cs:line 17
>    at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\RepeatableActionWorker.cs:line 20
>    at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\RepeatableWorkerBase.cs:line 23
>  
> [00:44:09.384] [5] [ Info] [Eco] Saving...  
> [00:44:12.527] [5] [ Info] [Eco] Saving... Finished in 3,142.8ms
>  
> [00:44:12.571] [21] [Error] [Eco] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
>    at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
>    at System.Collections.Immutable.ImmutableList`1.Node.CopyTo(T[] array, Int32 arrayIndex)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at Eco.Simulation.RouteProbing.RouteManager.UpdateRegions() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Simulation\RouteProbing\RouteManager.cs:line 288
>    at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Plugins\PluginTickTimer.cs:line 30
>    at Eco.Simulation.RouteProbing.RouteManager.Update() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Simulation\RouteProbing\RouteManager.cs:line 319
>    at Eco.Core.Serialization.StorageExtensions.Modify[T](T storage, Action`1 action) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Serialization\StorageExtensions.cs:line 15
>    at Eco.Core.Utils.Threading.PeriodicWorkerFactory.<>c__DisplayClass0_0.<Create>b__0(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\PeriodicWorkerFactory.cs:line 17
>    at Eco.Core.Utils.Threading.RepeatableActionWorker.DoRepeatableWork(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\RepeatableActionWorker.cs:line 20
>    at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\RepeatableWorkerBase.cs:line 23
>    at Eco.Core.Utils.Threading.WorkerBase.ShutdownAsync() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\WorkerBase.cs:line 45
>    at Eco.Core.Utils.Threading.WorkerExtensions.Shutdown(IWorker worker) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Core\Utils\Threading\WorkerExtensions.cs:line 8
>    at Eco.Simulation.RouteProbing.RouteProbingPlugin.Shutdown() in C:\Jenkins\workspace\Eco Staging\Server\Eco.Simulation\RouteProbing\RouteProbingPlugin.cs:line 51
>    at Eco.Server.PluginManager.<>c.<Shutdown>b__35_0(PluginRegistration reg) in C:\Jenkins\workspace\Eco Staging\Server\Eco.Server\PluginManager.cs:line 289
>  
> [00:44:12.706] [21] [ Info] [Eco] Shutdown finished

**Comment by mirasrael** [comment]
Issue was related to non-atomic ToArray for ThreadSafeList.

**Comment by D3nnis3n** [comment]
Master of Crashes.
