### ISSUE TITLE
[9.0 1526] Steel Saw Blade : is not in Adv. Smelting

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#16025]
The only thing with Steel, not in Adv Smelting is the Steel Blade.

It is in Smelting and gives Smelting exp.

Is that right ?

![20200427065214_1](https://user-images.githubusercontent.com/63646359/80335155-bcd59b00-8853-11ea-9abd-71a66d03cca0.jpg)

**Comment by WeaselDog** [comment]
Good catch! We will change this to Advanced Smelting.
