### ISSUE TITLE
[9.0 1526] Single and Double Streetlamp have same resource usage

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16022]
![image](https://user-images.githubusercontent.com/61889138/80317803-c6ccaf00-87fd-11ea-9853-ba19eda58326.png)

The double should logically be 2 light bulbs, double the amount of glass and say 2 steel more due to the extra support needed.

**Comment by trickenso** [comment]
Should the double streetlamp also produce more light than the single?

**Comment by MishkaFur** [comment]
@trickenso Yea I believe it does but havent checked in depth, it should probably also use more power, dont think it'd be balanced to just be double the power usage but say 150w instead of 100w ?

**Comment by SlayksWood** [comment]
Labor for Double streetlamp should be difference too.  maybe 110-120)
