### ISSUE TITLE
[0.9.0.0 beta staging-1526] cannot revise elected title with same name

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16023]
While revising an elected title the same name as before cannot been used. An messeage comes up which states, the title already exist. This is in general right, but this one will be revised as son the new tilte becomes active. 
This check makes sense for a new title to ensure, it is not using a name which already exist, but not for revising.

**Comment by MishkaFur** [comment]
The same is for districts and such, means if you revise a district you have to then revise the law every time

**Comment by SlayksWood** [comment]
Now it added number. For example Law 1 will change to Law 2. But previous it will change to Law 1 v2.
For example if I create Road map 3. It will change to Road map 4. 
I like our old system more.
@olegshegai Can you take a look?

**Comment by SlayksWood** [comment]
> Expected behaviour: After deleting an element, I should be able to create another with the same name, even if this means the deleted map is renamed to distinguish it from the live version.
> 
> Actual behaviour: Error shows indicating the name is already in use, when it isn't - the element with the same name has been deleted.

**Comment by johnkslg** [comment]
We prevent naming from matching even deleted items, because those deleted items are stored permanently to allow viewing the full history of the game. You can see the deleted ones in the ecopedia.

For the numbering scheme, we could return to changing the number post 'v', should be easy enough @olegshegai

**Comment by trickenso** [comment]
Could the deleted versions maybe be renamed to something that allows new laws to take the name you want? Like appending an 'archived' or 'deleted' tag, with a number if needed?

This way the names would be unique, but you wouldn't risk having to try multiple names before you find one someone else hasn't already used for something.

**Comment by johnkslg** [comment]
Its not a bad idea, but lets push it for now.

**Comment by Alteraner** [comment]
Hello @johnkslg,
 in regards to this topic an issue came up in my yesterday's testing which might increase the priority. 

In my example, I had an elected title or demographics. Both have been referred by the constitution amendment, who is allowed to change laws for example. Now I have changed one of the elected titles or the demographic as the logic has changed, but the expectation was, the relation set in the constitutional amendment stays to the new demographic or elected title, but it wasn't. so the reference was still toward the old one which now has been "removed". So the amendment didn't work anymore. So what I had to do is, to update the amendment as well.

To fix this unexpected behavior I would recommend following the @trickenso s idea, to keep the existing one and create a copy with something archive prefix or suffix, so the references in the governance system stay and do not get invalid.

**Comment by Uniphix** [comment]
I second this notion.  Couldn't you create a unique tag that is to that specific demographic, district, law etc.   So basically we the user either A) Generate one based off the name upon submission OR B) Allow us to specify it, after it has been specified it cannot be changed.  

Example:

Elected Title: "Supreme Commander"
Elected Key: "leader"

So we have a KEY/Title Variation, the KEY is unique to that specific Title

**Comment by Alteraner** [comment]
Hello,
 sorry, need to reopen it. It is fixed for all law type of usage, but within bank accounts and manual titles, the old one is been used and will not be replaced with the new one. Please change bank accounts and titles as well using the news / replaced demographic or elected title.
thanks.

**Comment by beastyn** [comment]
@Alteraner I can't actually get you. Bank accounts and appointed titles do not have a revisions. Can you make a screenshot or video?

**Comment by Alteraner** [comment]
No that was not, what i meant by. Let's try to be more precise. For example, I have a bank account and give manager role to that bank account by an elected title. Let's use "president" as an example. Now I change the "president" title which ends up, I have "president 2" and "president" is deactivated "president (removed)". The Bank account is still linked to "president (removed)" and no one has access any more to it, because it was not automatically replaced by "president 2". I need admin power to add "president 2" to the bank account manager.

As this issue is occurring in several areas, not only on bank accounts (e.G. claims, deeds, bank accounts, titles, ....) my recommendation is still to make it easy and future prove, to keep "president" and create a copy of it with new ID once it is changed. So you want run into similar issues any time, the elected title is been used.

And I can see on our server, the most players are confused seeing a "president 15" after a while with lot of government changes. 

Hope it is now a bit clear what issue I'm facing.

**Comment by IcedForge** [comment]
This was reworked in 9.1 and should no longer an issue, any revisions will replace current and archive it.

**Comment by Alteraner** [comment]
@IcedForge I'm sorry, i cannot confirm that the issue is been solved. If you look at below screenshot in the ammendment you can see, the (removed) title and it was not replaced by the new title version

![image](https://user-images.githubusercontent.com/47274045/96043752-bd003c00-0e6f-11eb-9341-66894240e944.png)
