### ISSUE TITLE
USER ISSUE: Cant start my singleplayer world or make a new one

### ISSUE THREAD

**Issue by Ryumidori** [StrangeLoopGames/EcoIssues#16020]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Trying to start a offline world and it just wont connect

**Expected behavior:**
It should have just connected to my SP world

**Actual behavior:**
The following error message popped up:
Connection failed, Timed out
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Connection failed, Timed out
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by beastyn** [comment]
@Ryumidori Thank you for your report.
What do you mean by "offline world"?
Do you have internet connection when starting a world?

**Comment by Ryumidori** [comment]
Hi Anna,

Yes I do have internet on. I am still unable to load an older world but after deleting my mods.dll file I have been able to make a new singleplayer world.
I don’t have any mods installed as far as I know so I have no idea what would block it.

Greetings,

Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by beastyn** [comment]
Its a known issue for some players, we are investigating it.
Thank you for attention.

Usually steps for fixing it is like that:

Please save your Storage folder in /Steam/steamapps/common/Eco/Eco_Data/Server/ and uninstall the game. Afterwards, please remove the complete /Eco folder mentioned above, then reinstall the game. This should fix this issue.
Kirill (Slayks)27.04.2020
