### ISSUE TITLE
[0.9 Staging-1526] Sometimes objects appear transparent / not load in multiplayer

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16027]
Not sure what exactly is causing this, but sometimes when playing multiplayer some objects either don't load or appear transparent:

![image](https://user-images.githubusercontent.com/964559/80342395-f3da8b00-8818-11ea-8d8c-a2140aa39c47.png)
![image](https://user-images.githubusercontent.com/964559/80342406-fc32c600-8818-11ea-9767-202725437235.png)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Have someone else host a server (by running the Steam client directly rather than a server?)
- Play around, run around the map
- Eventually some workstations or doors will fail to load or appear transparent?
- Disconnect, reconnect, everything is fine

3) Expected behaviour
Things should load properly and fully.

4) Actual behaviour
Some things don't fully load for no apparent reason.

**Comment by beastyn** [comment]
any logs, please? )

**Comment by ThePiachu** [comment]
If I stumble on this again I'll add the logs for sure.

**Comment by ThePiachu** [comment]
It happened again on 0.9.0.5 br-100, on White Tiger

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5448759/Player.log)

![image](https://user-images.githubusercontent.com/964559/97375368-e2ca0f80-1877-11eb-9089-3e91930ba01a.png)

**Comment by ThePiachu** [comment]
And on Hosted World:

![image](https://user-images.githubusercontent.com/964559/100964427-77f69e80-34dd-11eb-83ca-07a7d24ffac2.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5633677/Player.log)

**Comment by SlayksWood** [comment]
merge to #20414
