### ISSUE TITLE
[0.9 Staging-1526] Crafted Tables don't sort items by craftable after getting skill or level up.

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16028]
Most work stations sort items by whether you can craft them or not:

![image](https://user-images.githubusercontent.com/964559/80342718-7d8a5880-8819-11ea-844d-70b2dea71c85.png)
![image](https://user-images.githubusercontent.com/964559/80342770-972ba000-8819-11ea-880a-47da943311a7.png)

However, it appears the Tailoring Table does not follow this rule:

![image](https://user-images.githubusercontent.com/964559/80342809-a90d4300-8819-11ea-914d-5891ebba9fd8.png)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Get Tailoring 1
- Open up the Tailoring Table
- You will be able to see some items you can't craft in between items you can craft

3) Expected behaviour
Work stations should order items based on whether you can craft them or not.

4) Actual behaviour
The Tailoring Table does not respect that rule.

**Comment by SlayksWood** [comment]
It could happen with any table. If you just get skill or get new level. It fixes with reconnect or after some time:
![image](https://user-images.githubusercontent.com/45708377/80343314-5447e780-886e-11ea-85af-ea680eb1487e.png)
