### ISSUE TITLE
Unnamed Person in 8.3.3

### ISSUE THREAD

**Issue by OnlyJoe33** [StrangeLoopGames/EcoIssues#16024]
A user just joined our server with their steam name set to nothing ("") or maybe some odd unicode character. Seems to be someone trolling the server.
What happens now, is that every chat message anyone sends has this person referenced in it any time they use punctuation. There also seems to be no way to remove a player from a server, so for the rest of the game we are going to have to live with this issue.
 
Can you add some checks to names in 9.0, or at least for when they are inserted into the chat so it isn't pickup up empty names. And maybe a command to rename users would be helpful as well.

**Comment by SlayksWood** [comment]
dup #14560
