### ISSUE TITLE
[5.6 #67e68b2d] Server browser does not appear

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1602]
https://gyazo.com/6e4300617aa147822c850d3fd1f434a1

Server browser does not appear upon loading up the game.

**Comment by Blueduckraider50** [comment]
Having the same issue. https://i.imgur.com/obIE466.jpg

**Comment by metachronism** [comment]
Fixed in next build.

**Comment by REPOSEECO** [comment]
Grrr please let it open until a newer Version is out before i press the submit buton i found it here :-(
