### ISSUE TITLE
USER ISSUE:  

### ISSUE THREAD

**Issue by Dylon041030** [StrangeLoopGames/EcoIssues#16035]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
i cant make a world

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>User does not own Eco</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>User does not own Eco</size>
```

**Comment by SlayksWood** [comment]
@Dylon041030 
Did you buy game?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
