### ISSUE TITLE
Powered + unpowered Storage Silo and Liquid Tank Concept Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16036]
The dry storage silo is powered to control climate, and does not need any ports. These should look good as large arrays, so nothing super complicated. If there's a control panel of any sort it should be minimalist. These will be used to store farm and food products that can be stored en masse like grains, cereals, and other products that might be sensitive to extreme temperatures or humidity requirements.

The unpowered dry silo is for industrial products and non temperature sensitive goods like plastic pellets. It should be much like the powered storage silo but without anything indicating that it requires electricity. 

The liquid storage tank is for storing crude oil, refined oil, water, and other chemicals for industry. It should have an input and output pipe port. We also may want it to have a larger port for a pipe that takes up the full meter space, so it should be designed with a spot for that as well.

**Comment by RobertMangano** [comment]
done and given to phlo and posted in concept channel
