### ISSUE TITLE
Carts/objects that can contain tailings need to contribute to pollution

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1603]
Last remaining loophole in tailings storage -

Objects such as carts need to contribute to the ground pollution source of the world layer

**Comment by REPOSEECO** [comment]
#1610

**Comment by MarjieAVolk** [comment]
So, about project storage as a tailings loophole - should we have items in project storage contribute to pollution as well?  Could convert it into a regular inventory in there (internally, not displayed to the user) to make that easier.

**Comment by SeanAtr0n** [comment]
craig fixed
