### ISSUE TITLE
[0.9.0 staging-1527] Need to change icon for some specialties

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16032]
Smelting and advanced smelting:
I can see a little difference in skill UI:
![image](https://user-images.githubusercontent.com/45708377/80359063-f9ba8580-8885-11ea-8725-9bb89d26ee9c.png)
But i don't have any difference in labor icon:
![image](https://user-images.githubusercontent.com/45708377/80359144-18b91780-8886-11ea-8782-e70ab79908dc.png)

Cooking, Adcanced Cooking and Cutting Edge Cooking:
![image](https://user-images.githubusercontent.com/45708377/80360438-03dd8380-8888-11ea-92e4-c89476de9941.png)

**Comment by keegan-o** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/16124

folded this into a larger issue with specialty icons
