### ISSUE TITLE
[0.9.0 staging-1528] Work party: strange template for the first party 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16044]
1. Make a new server
2. Place a workbench and make 10 hewn log order
3. Place a contract board and start to create workparty

You will see this strange template
![bandicam 2020-04-28 14-24-17-858](https://user-images.githubusercontent.com/27898520/80470998-3789dd80-895c-11ea-87e9-c1ed6fb87f25.jpg)

**Comment by SlayksWood** [comment]
It doesn’t always happen, but I had this problem too.

**Comment by johnkslg** [comment]
Cant get this to happen, can you get me a log on the client when it does?

**Comment by beastyn** [comment]
Had it today on a second try
log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4549847/Player.log)

**Comment by johnkslg** [comment]
The bug is a view getting used before its sent to client, which Alex fixed yesterday in https://github.com/StrangeLoopGames/Eco/pull/6023

I havent been able to repro it after syncing to that (was able to previously), so I think it's fixed now. See if it happens anymore after Alex's fix.
