### ISSUE TITLE
USER ISSUE: Unable to connect

### ISSUE THREAD

**Issue by FabledJunkyard** [StrangeLoopGames/EcoIssues#16041]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Open the game
2. Click on "Continue" in the menu (this is local game, not a server)

**Expected behavior:**
It should have loaded my game. I cannot even start a new game or a new world.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Vanilla game.

The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Comment by SlayksWood** [comment]
@FabledJunkyard Hi, thank your for the report.
Please provide your latest logs from /Steam/steamapps/common/Eco/Eco_Data/Server/Logs.

**Comment by FabledJunkyard** [comment]
[log_200427092405.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546681/log_200427092405.log)
[log_200427092432.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546682/log_200427092432.log)
[log_200427092623.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546683/log_200427092623.log)
[log_200427092955.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546684/log_200427092955.log)
[log_200427093104.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546685/log_200427093104.log)
[log_200427101604.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546686/log_200427101604.log)
[log_200427101745.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546687/log_200427101745.log)
[log_200427102302.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546688/log_200427102302.log)
[log_200427113151.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546689/log_200427113151.log)
[log_200427113332.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546690/log_200427113332.log)
[log_200427114334.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546691/log_200427114334.log)
[log_200427115754.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546692/log_200427115754.log)
[log_200427121003.log](https://github.com/StrangeLoopGames/EcoIssues/files/4546693/log_200427121003.log)

**Comment by FabledJunkyard** [comment]
Those are the logs for yesterday (The day that I started having the issue).

**Comment by SlayksWood** [comment]
@FabledJunkyard 
Please save your Storage folder in /Steam/steamapps/common/Eco/Eco_Data/Server/ and uninstall the game. Afterwards, please remove the complete /Eco folder mentioned above, then reinstall the game. This should fix this issue.

**Comment by FabledJunkyard** [comment]
Great! I will try that today.

**Comment by FabledJunkyard** [comment]
It works. Thank you!
