### ISSUE TITLE
[0.9.0 staging-1528] Wrong notification when you should collect item.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16042]
Wrong notification when you should collect item from crafte table. Step to reproduce:
- start work order:
![image](https://user-images.githubusercontent.com/45708377/80459674-6479c880-893b-11ea-8220-118bad734be7.png)
- add 50 labor:
![image](https://user-images.githubusercontent.com/45708377/80459705-7196b780-893b-11ea-94c6-8d56984b810e.png)
- add 20 Birch log:
![image](https://user-images.githubusercontent.com/45708377/80459826-a145bf80-893b-11ea-9aa6-b79575d91acd.png)
- wait order finishing:
![image](https://user-images.githubusercontent.com/45708377/80460499-99d2e600-893c-11ea-8c0b-351ca14645f8.png)

**Comment by gzatravkin** [comment]
Added notification about inventory space
