### ISSUE TITLE
[0.9 Staging-1526] Hovering over some items gives a tooltip of items previously in that spot

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16046]
I think there is some weird caching going on that generally gives you tooltips for items that used to be in a given spot, rather than the items that are in that spot now:

![image](https://user-images.githubusercontent.com/964559/80484737-11891c80-890d-11ea-9063-c19803856d20.png)

![image](https://user-images.githubusercontent.com/964559/80484902-5614b800-890d-11ea-9598-b35f2a882f0b.png)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Have an item in an inventory slot
- Move the item or replace the item in the slot with something else
- Hover over the old item's slot
- You will get a tooltip for the old item, rather than a blank or the new item's tooltip

3) Expected behaviour
Tooltips should display for items that are in the spot, not the items that were in the spot.

4) Actual behaviour
Tooltips for an old item are displayed instead.

**Comment by SlayksWood** [comment]
dup #9344
