### ISSUE TITLE
Better Small Boat (Concept) Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16040]
Our old small boats at this point are pretty lackluster and would be mismatched to implement alongside the newer big boats. Lets get some striking new small boats with a few different varieties of size and material options.

- [ ] Small Wooden Rowboat or Canoe - should be able to seat 2 people
- [ ] Small Metal Motorboat - could be a rowboat style boat that also has a little outboard motor

Both small boats should have a small area on the floor of the boat with a little hatch indicating a small place one could store some ice + fish.

- [ ] Large Wooden Canoe - should be able to seat up to 6 people and have a bigger storage hatch.
- [ ] Metal Motorboat - a larger rowboat style boat that can seat up to 4 people and has a little area for storage. Motor could be outboard or enclosed.

Potential variants for these would be different wood types and different painted colors for the metal boats. For the metal boat it should be set up to be a tintable paint like the truck. 

The large boats we should think about possible mount points for people to fish from (or if they would be different than the in-transit points).

We probably want concepts for these unless they are all on Milenko's plate.

**Comment by elfl0rd** [comment]
If possible, I would like to request the system as in an elevator, when a player can move around on a moving object without moving out of it.
