### ISSUE TITLE
[0.9.0 staging-1528] Can't set default currency.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16045]
Step to reproduce:
- create World title with treasury privileges and be occupant:
![image](https://user-images.githubusercontent.com/45708377/80479276-723d4700-8957-11ea-8bff-cf731654376e.png)
![image](https://user-images.githubusercontent.com/45708377/80479290-76696480-8957-11ea-906b-cb690e64b22f.png)
- place Treasury, place Mint and create new "Test coin":
![image](https://user-images.githubusercontent.com/45708377/80479306-7e290900-8957-11ea-86c6-f0c3fda9ba44.png)
- open treasury and set "Test coin" as default
![image](https://user-images.githubusercontent.com/45708377/80479323-86814400-8957-11ea-83c9-2d047208e464.png)
- place new store. It should use default "Test coin" by default. But it isn't.
![image](https://user-images.githubusercontent.com/45708377/80479365-96008d00-8957-11ea-8d42-e0bf3a3b0fce.png)
- after time (or you can restart server) default currency:
![image](https://user-images.githubusercontent.com/45708377/80479382-9dc03180-8957-11ea-8449-1db71a45d6fe.png)

**Comment by SlayksWood** [comment]
In 0.8.3 first non-personal currency will be defaulted currency, but i think it will be bad for 0.9.0.
Need to check #15904 after fixing

**Comment by beastyn** [comment]
Somewhere in this logic default currency was getting back to my private

1. Create a title with treasury access and occupy it
2. Place a mint and make the TestCoin1
![bandicam 2020-05-08 10-35-51-006](https://user-images.githubusercontent.com/27898520/81374447-b4fddc80-9118-11ea-8530-20272d2fe606.jpg)
3. Place a treasury and pick TestCoin1 as default
![bandicam 2020-05-08 10-35-59-941](https://user-images.githubusercontent.com/27898520/81374493-d068e780-9118-11ea-82d7-f1c1da7d0484.jpg)
4. Place a store and check its default currency. Should be TestCoin1
![bandicam 2020-05-08 10-36-31-266](https://user-images.githubusercontent.com/27898520/81374584-0312e000-9119-11ea-85aa-798f8d1399ed.jpg)
5. Place a second store and check, just in case
6. Place a mint(yws, one more time) and craft some niew TestCoin2
![bandicam 2020-05-08 10-37-48-661](https://user-images.githubusercontent.com/27898520/81374627-22aa0880-9119-11ea-9bf1-7da757387c72.jpg)
7. Place a store and check its currency

Its not default, its personal
![bandicam 2020-05-08 10-38-12-862](https://user-images.githubusercontent.com/27898520/81374685-41a89a80-9119-11ea-9f20-8cbcc23ddcbb.jpg)

8. Check treasury. Default currency was back to the personal
![bandicam 2020-05-08 10-38-24-561](https://user-images.githubusercontent.com/27898520/81374739-656be080-9119-11ea-9a55-02bfad3dc8f7.jpg)

**Comment by beastyn** [comment]
Well, stores are fine, but treasury will show me (only show, maybe?) my personal currency.

With all the same steps, check number 8. please
After minting the SECOND currency, check treasury, and you will see personal currency there.
So its seems to be only visual (store will use the first minted and treasury placed currency) its still quite annoying.
