### ISSUE TITLE
[0.9.0 staging-1530] Broken icons and UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16050]
a lot of them
![bandicam 2020-04-29 10-06-22-423](https://user-images.githubusercontent.com/27898520/80562903-a15cc280-8a02-11ea-8e8e-5b0a94f8e459.jpg)

**Comment by SlayksWood** [comment]
Still missing some icons:
Laws, demographics, Articles, bank accounts and etc.
![image](https://user-images.githubusercontent.com/45708377/80582553-982a2080-8a17-11ea-8a5e-79a14c1e7421.png)
![image](https://user-images.githubusercontent.com/45708377/80582574-a0825b80-8a17-11ea-802a-73d55ad4991b.png)
![image](https://user-images.githubusercontent.com/45708377/80582581-a2e4b580-8a17-11ea-9866-24cbff0ef5d3.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/80585287-bf82ec80-8a1b-11ea-8daf-724d68ad159c.png)

**Comment by SlayksWood** [comment]
all that we diligently did, today suddenly broke:
![image](https://user-images.githubusercontent.com/45708377/80587510-5b622780-8a1f-11ea-9b07-ac3f6ee05d45.png)
![image](https://user-images.githubusercontent.com/45708377/80587524-60bf7200-8a1f-11ea-909b-e507cac3fae6.png)

**Comment by SlayksWood** [comment]
chat #16051
