### ISSUE TITLE
[0.9.0 staging-1532] Important notification improvement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16058]
![unknown (15)](https://user-images.githubusercontent.com/27898520/80676338-f7e40280-8acf-11ea-91ed-7a9a01e8cb5c.png)

1. Icon should be on top
2. Icon should be wrapped by text
3. There is no icon for party completion

**Comment by johnkslg** [comment]
For long text ones like this: update it to use a foldout list to have the extra details
