### ISSUE TITLE
Improve skill highlight

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16055]
![image](https://user-images.githubusercontent.com/3536496/80630610-56927900-8a09-11ea-80b7-4b7ca7479b0d.png)
Green color clashes now and looks bad, should be behind icon

![image](https://user-images.githubusercontent.com/3536496/80630655-6742ef00-8a09-11ea-910a-ffdc33e7c47a.png)
Add the selected specialty icon to the left of the specialty description (right side) to match the profession icon on the profession description. Make the specialty icon nice and big.

**Comment by MilenkoTunjic** [comment]
Sergei, I think we did (or at least discussed this one) at some point. Let me know if it is still an issue.

**Comment by serpopov** [comment]
icons moved to other task
