### ISSUE TITLE
USER ISSUE: Bug loading

### ISSUE THREAD

**Issue by Alleverloren** [StrangeLoopGames/EcoIssues#16053]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Click to continue or load

**Expected behavior:**
Loading		

**Actual behavior:**
Nothing happens

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing happens

**Comment by SlayksWood** [comment]
@Alleverloren 
Please provide your latest logs from /Steam/steamapps/common/Eco/Eco_Data/Server/Logs.

**Comment by Alleverloren** [comment]
Sorry deleted it all.
As soon as it happens again. I will send

**Comment by Alleverloren** [comment]
[log_200429090136.log](https://github.com/StrangeLoopGames/EcoIssues/files/4557954/log_200429090136.log)
[log_200429075932.log](https://github.com/StrangeLoopGames/EcoIssues/files/4557955/log_200429075932.log)

**Comment by beastyn** [comment]
Try to delete .db file for your world in the folder \Eco\Eco_Data\Server\Storage

**Comment by Alleverloren** [comment]
Thank you. Had no more problems
