### ISSUE TITLE
Stat issues (code side)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16068]
![image](https://user-images.githubusercontent.com/3536496/80754937-c7f32a00-8ae4-11ea-9aab-24b7a6da4a6e.png)
![image](https://user-images.githubusercontent.com/3536496/80754997-dd685400-8ae4-11ea-83c1-12c55a1b79c3.png)
- [x] Some actions should not show up in the graphs, like QueryAction. It's marked [NoStats], use that to determine if it should appear.

![image](https://user-images.githubusercontent.com/3536496/80755033-ef49f700-8ae4-11ea-809a-9d3cfd644116.png)
![image](https://user-images.githubusercontent.com/3536496/80755083-0852a800-8ae5-11ea-8dd1-a52b8fc01ead.png)
- [x] Add sub-categories for all the player actions, same as the dropdowns in game.  Use the LocCategory tag, which is used in game.

- [ ] Revive the FrontPage query and make it better. This query will return a number of graphs that should be displayed by default when the user goes to an Eco server web page.   We can make the graphs that are shown related to the three pillars: economy, ecosystem, and government.  Some ideas for graphs we can have:
- CO2, showing pollution sources and sinks, and effects: sea level and temperature rise
- Economy, showing total transactions in the top 1 or 2 currencies per volume (Ie, GDP, might need to add new stats for tracking this),  workparties completed, and total number of specialties for all users.
- Government, showing number of laws, elected titles, office holders, elections, civic actions performed

- [x] Graphs are no longer showing player actions properly. 

![image](https://user-images.githubusercontent.com/3536496/80755973-967b5e00-8ae6-11ea-8560-c2f519c0e99c.png)
- [x] Selecting 'Labor Work Order Action' in this [db file](https://eco-public-files.s3-us-west-2.amazonaws.com/stresstest-4-29.zip) caused this exception:
![image](https://user-images.githubusercontent.com/3536496/80756096-cb87b080-8ae6-11ea-9f95-19bcf0ea2585.png)
There seems to be trouble displaying any player actions in the graph

**Comment by beastyn** [comment]
ask @Quadbro for help
also from #14009
 I had problems with actions:
Demographic change
Claim or Unclaim
Vote
Start Election
Character Level up
Contstruct ot deconstruct
Place or pickup
Play
First Login

**Comment by MarkZaytsev** [comment]
Part of the sub-categories and Front Page is moved to the separate issue. I and @denysaw will fix it together. https://github.com/StrangeLoopGames/EcoIssues/issues/16185

**Comment by johnkslg** [comment]
Closing this and remaking front page thing

**Comment by johnkslg** [comment]
- [ ]
