### ISSUE TITLE
Strange population changes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16069]
![image](https://user-images.githubusercontent.com/3536496/80755879-721f8180-8ae6-11ea-9309-74f1bee95337.png)
Deer population jumped from 62 to 160 instantly, for example. There are lots of these occurring.

**Comment by johnkslg** [comment]
@SlayksWood can you guys watch for this and try to get a world save attached to this bug from right before a jump happens? Ie, grab the most recent backup before the jump, then we can watch the jump happen in real time.

**Comment by SlayksWood** [comment]
There were a lot of changes with population. Currently in release it's better. I have this graphs:
![image](https://user-images.githubusercontent.com/45708377/100218034-38e8ac00-2f25-11eb-9c39-a66d9f0a8000.png)
Closed for now. I will open another issue if we have the problem.
