### ISSUE TITLE
USER ISSUE: Takes too long to farm Huckleberry Seeds

### ISSUE THREAD

**Issue by tylerrit545** [StrangeLoopGames/EcoIssues#16061]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
me and my buddy spent 3+ hours farming 300 huckleberry seeds for the farming perk. He is done with the game after that so please fix it

**Expected behavior:**
It should be about a 20% drop rate

**Actual behavior:**
it was a 3% which is just crazy

**Do you have mods installed? Does issue happen when no mods are installed?:**
it was a 3% which is just crazy, no mods, just installed the game and played it

**Comment by SlayksWood** [comment]
Thank you for the report.
Should be partily fixed in 0.9.0:
https://github.com/StrangeLoopGames/EcoIssues/issues/12833#issuecomment-558527640
Another bug should be fixed later #12718
