### ISSUE TITLE
[0.9.0 staging-1533] Bighorn sheep has lost its piece

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16064]
![bandicam_2020-02-04_14-21-18-900](https://user-images.githubusercontent.com/27898520/80707651-c2590c80-8b03-11ea-9d33-88a7f34cac8a.jpg)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/81130424-8c999680-8efc-11ea-95d6-b7ad5aada44e.png)
Fixed in staging
