### ISSUE TITLE
Skyrocketing CO2

### ISSUE THREAD

**Issue by theDrunkenArchitect** [StrangeLoopGames/EcoIssues#16066]
![20200430203400_1](https://user-images.githubusercontent.com/64610214/80749037-2ab8e580-8b26-11ea-9d86-7bd1de17bfc7.jpg)

Just this one refinery ist running for some minutes - maybe 5-10 - and the total CO2 just skyrocketed to above +420ppm/day.

For some days now we completly stopped our workshops, but the sea level rised for three meters although the blast furnaces (3) and kilns/stoves (2) never worked for more than 4 hours a day.

**Comment by jaskes** [comment]
save from the game https://eco-public-files.s3-us-west-2.amazonaws.com/stresstest-4-29.zip

**Comment by johnkslg** [comment]
@WeaselDog can you do some tests to see if CO2 numbers are correct? IE, create a polluting object, let it run for awhile, ensure that the graph matches expected amounts (and that expected amounts are clear)

**Comment by jaskes** [comment]
The world became unplayable because of the raised sea level so I wiped it, last save is here https://eco-public-files.s3-us-west-2.amazonaws.com/stresstest-4-30.zip

**Comment by beastyn** [comment]
Did third world was created on the  older version and you had update somewhere?

**Comment by jaskes** [comment]
I think it was there for the couple of weeks, the server gets updates daily on the same rate as the bleeding_edge,

**Comment by WeaselDog** [comment]
The current PPM/hour for Oil Refinery is now 5.04 PPM. It was reduced by 10x, but we are continuing to investigate the impact of pollution.

**Comment by beastyn** [comment]
After some investigating.
For example, here we have 0.52 world with 3 oil refineries which are running for about 5 hours (with some switching off moments)

Pollution from refineries
![bandicam 2020-05-05 10-25-20-537](https://user-images.githubusercontent.com/27898520/81037086-f002d480-8eba-11ea-979a-49b21db7eaa0.jpg)

Here we can see when I was launching three of them, so we have a pollution jump here with right numbers. Also you can see moments when some of them were switching off and then they where stopped.

Global pollution for that time
![bandicam 2020-05-05 10-25-13-664](https://user-images.githubusercontent.com/27898520/81039702-32c8aa80-8ec3-11ea-8928-a4bfc611e1ce.jpg)

Also looks pretty fine without any jumps.

I suppose from the mathematical point of view pollution is fine. Stresstest could have some problems after updates, as some calculations were changed in the process.

Anyway we will make some calculations and modelling for balancing, like with pollution numbers and sea-level temperature changes.
