### ISSUE TITLE
Profile hosted worlds

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16071]
Hosted worlds is slower than other hosting systems, maybe related to Docker.  High priority because it breaks this shipping feature.

**Comment by lagonnebula** [comment]
If I can help, i use docker to host my server and I don't have issue with it.
Maybe sometime some cpu usage spike. 
This graph is with a 0.5km map and 7 players online. 
https://files.meuhmeuh.fr/images/chrome_1mtgw3Bjo3.png

My players doesn't complained about lags of thinks like this.

**Comment by mirasrael** [comment]
I added script and updated Docker Container to allow profiling for local Docker Containers and containers running in Kubernetes (https://github.com/StrangeLoopGames/EcoIssues/issues/16071).
After this PR merged we can update our staging build to use SDK distribution (with profiling support) and use some real servers having issues for profiling.
