### ISSUE TITLE
Improve news

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16074]
![image](https://user-images.githubusercontent.com/3536496/80760210-64212f00-8aed-11ea-893f-0537d13bc28d.png)
- [ ] Green text at top looks crummy
- [ ] Text should be smaller than the header (enlarge header)
- [ ] Image needs a border and more margins
Any other visual improvements @MilenkoTunjic ? First thing users see.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/80763557-a188bb00-8af3-11ea-905a-85f67143bc0e.png)
Image is missing sometimes

**Comment by SlayksWood** [comment]
Image missing when it just loads. Image should display after few second.

**Comment by beastyn** [comment]
@MilenkoTunjic 
Need your help here.
It looks messy with two-column style and scroll.

Im trying to read the second column, but I actually need to scroll first.
![bandicam 2020-05-07 10-56-53-624](https://user-images.githubusercontent.com/27898520/81259490-7ea95a00-9051-11ea-8820-f10f477444bc.jpg)

And its too tight with scroll too

**Comment by MilenkoTunjic** [comment]
Yeah, that is not good.
if you have scrolling then keep text in one column. Make sure font size is not too big and definitely move edges of the text wrap 4-5 pixels further away from the edges of the paper. Give more breathing space between image and text on the left and scroll bar on the right. Everything needs to breathe in harmony. Also, **remove shadow or whatever effect the title font has**. Just use black and bold for titles and make sure it uses no more than two lines regardless of how much text is in the title. so Make fint auto scale to fill the two line text box. so shorter titles will have bigger font filling the space and longer titles will have smaller font text and once it fills two lines it srhinks until all the title text fills two lines. 
EZPZ
PS, if anything is confusing, feel free to ping me. We will get it there, it is not too hard :)

**Comment by beastyn** [comment]
Its better, but beed somw space after the header and after the image/
Also, picture is seems to be stretched,
![bandicam 2020-05-11 15-20-13-801](https://user-images.githubusercontent.com/27898520/81552261-a32c6b80-939c-11ea-945c-b02df9bb3a35.jpg)
