### ISSUE TITLE
Election Web issues 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16070]
![image](https://user-images.githubusercontent.com/3536496/80754393-cc6b1300-8ae3-11ea-964d-839a1003b0b5.png)
- [x] Make the info boxes styled better, so they dont wrap (top right)

![image](https://user-images.githubusercontent.com/3536496/80754528-089e7380-8ae4-11ea-9b68-94eca3e0dff3.png)
- [x] Clear categories didnt clear all the categories on first click, when displaying a large graph (those premade ones)

![image](https://user-images.githubusercontent.com/3536496/80754599-2370e800-8ae4-11ea-8870-ba8fe692fecb.png)
- [x] After fiddling around with the graph for awhile, the bottom right time box disappeared
- [x] Changing graph from 'lines' to 'bars' and then back: time range shown is no longer applied, lines are missing.

![image](https://user-images.githubusercontent.com/3536496/80755227-4cde4380-8ae5-11ea-8911-9ddc19615fe7.png)
- [x] Categories are not alphabetical
- [ ] Categories need sub-categories  (see #16068)

![image](https://user-images.githubusercontent.com/3536496/80755750-38e71180-8ae6-11ea-891a-2c60952f6305.png)
- [ ] Jeff: Make the 'Data' panel collapsible and resizable

**Comment by denysaw** [comment]
@johnkslg Please, re-test these two bullets after clearing browser's cache (refresh page with Ctrl+F5):
`After fiddling around with the graph for awhile, the bottom right time box disappeared`
`Changing graph from 'lines' to 'bars' and then back: time range shown is no longer applied, lines are missing.`
As these are old bugs I should have fixed before, but you may still have old cache. Btw, idea, I should code anti-cache algorithm of requiring local resources, cuzz same thing was with Anna. I'll add build version to resource urls. Great 👍

**Comment by denysaw** [comment]
@rainfarmer Tagged you in the last bullet.

**Comment by denysaw** [comment]
Finished all bullets except `Categories need sub-categories (see #16068)` cuzz it waits for server changes and very gladly if it'll be rip to separate task and Jeff's Data panel re-design.

**Comment by SlayksWood** [comment]
- [ ] It's look strange (resolution 1680x1050):
![image](https://user-images.githubusercontent.com/45708377/82017464-e7b15300-968b-11ea-993e-17a677a4d203.png)

- [ ] categories were lost 
![image](https://user-images.githubusercontent.com/45708377/82017554-14656a80-968c-11ea-8972-48c55ade2a41.png)

- [ ] time box will dissapear if you press "Clear Categories" button:
![image](https://user-images.githubusercontent.com/45708377/82017752-8938a480-968c-11ea-8439-3e106e68b9bd.png)

**Comment by SlayksWood** [comment]
Closed for now, unfixed points moved to #16395
