### ISSUE TITLE
Bird and wind sounds no longer start on black loading screens

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16073]
![image](https://user-images.githubusercontent.com/3536496/80760023-186e8580-8aed-11ea-9b50-de1115ef9aa8.png)

They should start immediately in this scene and seamlessly continue in the new scene.
Previously there was a game object in the MinimalLoader that would start the sounds, and another in the title screen that would start the sounds unless the minmal loader already had.

**Comment by beastyn** [comment]
@johnkslg It was the fast fix for the sound initialization issue.
Can we push it on the later build, if its hard to fix?

**Comment by Quadbro** [comment]
Yes it will be hard to fix now

**Comment by SlayksWood** [comment]
I don't have any sound in main menu now.

**Comment by SlayksWood** [comment]
recheck this #16608 after fixing
