### ISSUE TITLE
Can no longer click world markers to bring up their properties

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16080]
![image](https://user-images.githubusercontent.com/3536496/80764182-fa0c8800-8af4-11ea-9f04-6f821dac5bda.png)

**Comment by SlayksWood** [comment]
When you click it minimap will open.
![image](https://user-images.githubusercontent.com/45708377/81376000-51b97d80-910b-11ea-9e33-bf2523ae2921.png)
![image](https://user-images.githubusercontent.com/45708377/81376064-70b80f80-910b-11ea-8ead-a9d25ad84c10.png)
