### ISSUE TITLE
USER ISSUE: getting logged out constantly

### ISSUE THREAD

**Issue by Stuferus** [StrangeLoopGames/EcoIssues#16087]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
dont know.. happens over and over on "[GER] AT-Gaming" Server.. and i dont know why.. restarted steam, changed my steam passwort in case its related to being hacked, tryed reconnecting internet, steam and game.. no use.. help?

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Login token changed. Possible login elsewhere.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Its on a server i dont own.. i guess they may use mods.. but it worked befor without problem.

Die folgende Fehlermeldung trat auf:
```
Login token changed. Possible login elsewhere.
```

**Comment by SlayksWood** [comment]
@Stuferus sorry for waiting. I need some information to investigate your problems.
1. Does it happen in other servers? Try to use another server and if problem repeats then provide log files
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Do you have account on  https://www.play.eco which linked with steam? If yes then try to change this account password too.

**Comment by Stuferus** [comment]
no it does not.. i changed server with my friends and that solved it.. i guess its the specific server..
i do not own an account on play.eco becouse i got the game on steam as a gift..
i will post a new again if it happens again.. then with logfile :) - thank you so far :)
