### ISSUE TITLE
[0.9.0 staging-1534] Markers are under UI again

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16084]
![image](https://user-images.githubusercontent.com/45708377/80799253-048b5800-8baf-11ea-9146-4cd41a5b8e52.png)

**Comment by gzatravkin** [comment]
Wasn't able to reproduce it at last staging (video).

If it's stil reproducible please attach a video with moving camera and change of ui scaling, so Ican have more clues how to fix it. 

https://drive.google.com/open?id=1GIIoLmnNmDa6NMxFFfRDHqjO1FWi6mDC

**Comment by SlayksWood** [comment]
You don't very high. Use /fly or go up the hill
![image](https://user-images.githubusercontent.com/45708377/81277258-d26d7080-905c-11ea-8e71-45199c8879c8.png)

**Comment by SlayksWood** [comment]
Hm, seems If I add second marker then all is right. So You need to delete all markers, restart game add 1 marker
