### ISSUE TITLE
[EU] Playtest Server #1 (Max Connections: 10) HW Server Down

### ISSUE THREAD

**Issue by Shadowrider0** [StrangeLoopGames/EcoIssues#16088]
Some time around 2pm EST yesterday (4/30) I could no longer access [EU] Playtest Server #1 (Max Connections: 10) HW. Spoke with members of the staff in trying to resolve the situation. We found if I ran a VPN in germany I could get connected.  Then around 4pm est, the 3 of us online got kicked off and could no longer get online. The server now appears online but you can't connect to it.  It shows 3 users online yet I think those numbers are us still.  Spoke with Dennis on the issue but he said he doesn't have access to this HW server to reboot it.  Any assistance would be appreciated.

**Comment by Shadowrider0** [comment]
Still show down.  In US currently.
![image](https://user-images.githubusercontent.com/64047782/80864968-3276a800-8c54-11ea-94b3-ff750ff17996.png)

**Comment by Shadowrider0** [comment]
Connected to Germany you see it online but can't connect.
![image](https://user-images.githubusercontent.com/64047782/80864992-5803b180-8c54-11ea-8b0d-1b238b2fc1a5.png)
![image](https://user-images.githubusercontent.com/64047782/80865006-749fe980-8c54-11ea-924e-7e00bd2efd9d.png)

**Comment by Shadowrider0** [comment]
The part I find strange is I reported this 3 days ago.  I am pretty sure if you check logs no one has logged into the server since then but no one will look into this issue. As an IT Manager myself but in the medical field this is alarming.  3 days of a server being down without a tech checking into it isn't good.  With 3 days going by very unlikely the few people that did play will still play if you fix it now. So kind of a useless test of a server when you don't support it.

**Comment by beastyn** [comment]
Seems like they should be offline. We will ask about current plans for playtest.
Thank you for attention.

**Comment by Shadowrider0** [comment]
TY Beastyn apricate the help
