### ISSUE TITLE
[0.9.0 staging-1534] Freezes in game

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16086]
look on grass: https://drive.google.com/file/d/15JKcINrJzRsdFKgZ8Ozj3Zoemn-mP-3o/view?usp=sharing
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4563842/Player.log)
and I have mini freezes when just play. It was fixed afret relog.

**Comment by SlayksWood** [comment]
And freezes return after 30 min playing:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4564040/Player.log)

**Comment by johnkslg** [comment]
Probably related to object destruction happening on UI close. Good menu to cache.
