### ISSUE TITLE
Eco tree feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16091]
- [x] The 'in progress now' marker (the +) should only appear when a user has selected it as their current task.
- [x] The yellow numbers should only appear on sections where there's a new addition, not their parents.
- [x] Team member icons should only appear after youve clicked on any feature section.

![image](https://user-images.githubusercontent.com/3536496/80832398-7361b480-8ba1-11ea-907e-efb8385df9cc.png)
- [x] This share button isn't clickable
- [x] Add full-screen button that lets you read a section in a new tab.

![image](https://user-images.githubusercontent.com/3536496/80832583-c63b6c00-8ba1-11ea-9845-e4377ed246b2.png)
- [x] If you click Eco Discussion here, it takes you to an overview where you can see all comments on all articles.  Make a nice link to this at the root level somewhere, probably next to 'latest updates' on the main page.

![image](https://user-images.githubusercontent.com/3536496/80832700-013d9f80-8ba2-11ea-88ac-e46c6e2d64c0.png)
- [x] A notification value was negative somehow

![image](https://user-images.githubusercontent.com/3536496/80833141-d56ee980-8ba2-11ea-8c92-263111889490.png)
- [x] Can Recent Update give a summary of what's updated? Its a long scroll list.  Also state what the date is from when you're tracking updates.

- [x] On the tooltip for the user portraits, state which feature theyre working on. 
- [x] When clicking on a user portrait, go to the feature they're working on, rather than the bio.
- [x] On that feature which they're working, add the images of the users currently working on it, and clicking on that will take you to the bio.

![image](https://user-images.githubusercontent.com/3536496/80833321-28e13780-8ba3-11ea-8e31-110ec06264f6.png)
- [x] Jeff: Change 'In Progress' get to be a plus without a colored node. Looks like its the end of a spectrum, when really it's a different axis (ie, any color can have a plus). Find a good way to communicate this. 

![image](https://user-images.githubusercontent.com/3536496/80834564-d35a5a00-8ba5-11ea-99a7-e7c08b5a8501.png)
- [x] Restrict access to creating news posts, this should only be available to Dennis and myself

![image](https://user-images.githubusercontent.com/3536496/81128180-5f95b580-8ef5-11ea-8435-03bb29a9d972.png)
- [x] Make this tooltip also show 'Working on feature <selected feature>:' And then the status text below.

**Comment by denysaw** [comment]
@rainfarmer Added you also here (to think of where to put a link and how to style it, you could copy link from button on a snapshot):
`If you click Eco Discussion here, it takes you to an overview where you can see all comments on all articles. Make a nice link to this at the root level somewhere, probably next to 'latest updates' on the main page.`

**Comment by rainfarmer** [comment]
added button

**Comment by denysaw** [comment]
Yep, I saw ;) Thanx
