### ISSUE TITLE
USER ISSUE: presidential candidates with long speaches at disadvantage

### ISSUE THREAD

**Issue by legendddhgf** [StrangeLoopGames/EcoIssues#16098]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
write long speech

**Expected behavior:**
shown the speech in it's entirety after at least clicking "read more"

**Actual behavior:**
This should have a much larger maximum number of characters or at least inform you of your progress towards the maximum before submitting the speech.

cut-off speech example (it would have been glorious D=):

"Why are you running?" Asks the African man. "Because I am guilty!" Says the guilty man. "Because I am late to work!" Exclaims the tardy man. When I was asked this question, I thought long and hard. Why was I running? And then I remembered. I had a duty to you. I promised you that I would help brin

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods installed here

**Comment by beastyn** [comment]
Should be fine in 9.0
![bandicam 2020-05-04 11-11-35-374](https://user-images.githubusercontent.com/27898520/80940103-23305f80-8df8-11ea-84b0-260fa85dc351.jpg)
![bandicam 2020-05-04 11-08-15-779](https://user-images.githubusercontent.com/27898520/80940107-24fa2300-8df8-11ea-95c5-f9540ac6d7b2.jpg)

**Comment by legendddhgf** [comment]
lol, I appreciate your addition to the speech XD

Thanks for verifying, I at least wanted to document it as an issue since I had observed it.
