### ISSUE TITLE
USER ISSUE: apostrophes incorrectly displayed in web browser

### ISSUE THREAD

**Issue by legendddhgf** [StrangeLoopGames/EcoIssues#16099]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
make a comment on a law with an apostrophe (e.g: containing "it's"

**Expected behavior:**
shows apostrophe

**Actual behavior:**
e.g: "it's" showed as "It&#039;s"

**Do you have mods installed? Does issue happen when no mods are installed?:**
no custom mods

**Comment by beastyn** [comment]
Thank you for the report.
Seems to be fine for 9.0
Please tell me if I got you wrong

![bandicam 2020-05-04 11-18-52-131](https://user-images.githubusercontent.com/27898520/80940476-51fb0580-8df9-11ea-9d9b-6e09ef09d9ba.jpg)

**Comment by legendddhgf** [comment]
looks good. thanks. Just wanted to make sure it was documented =D
