### ISSUE TITLE
USER ISSUE: highlighting active text bar with password servers

### ISSUE THREAD

**Issue by legendddhgf** [StrangeLoopGames/EcoIssues#16095]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Try to login to a password protected server

**Expected behavior:**
a flashing bar, or something indicating the password text box is active

**Actual behavior:**
it's not active, and shows no visual difference after clicking on it, resulting in having to retype password

**Do you have mods installed? Does issue happen when no mods are installed?:**
no custom mods

**Comment by SlayksWood** [comment]
thank your for the report.
merged to #15352
