### ISSUE TITLE
[0.9 Staging-1526] Minor recipe / icon errors

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16096]
I've noticed a few errors with some recipes:

- Crushed Gold (level 2 at least) produces crushed sandstone, instead of crushed granite (which I'd assume would be the correct rock based on what usually surrounds gold):
![image](https://user-images.githubusercontent.com/964559/80898762-19a1dd00-8cbc-11ea-8764-683bc68a536e.png)
- Crushed Slag (level 2) icon in the production queue / top toolbar is that of crushed iron. I think there might be some other icons around the level 2 processing that might also be off (dry iron from the shaker is a dry tailings icon AFAIR?)
- Rivets use iron instead of steel, despite being an Advanced Smelting recipe

**Comment by Sekor2600** [comment]
Point 1&3 fixed

**Comment by WeaselDog** [comment]
@keegan-o Going to add you on to this one as we need a new sprite to solve point 2.

**Comment by SlayksWood** [comment]
Still an issue for Slag:
![image](https://user-images.githubusercontent.com/45708377/82191243-e6d22880-98fa-11ea-97ac-aa3687265550.png)
