### ISSUE TITLE
[8.3.3] Rotate platform on excavator doesn't use keybinding

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#16093]
Rotate platform use A/D and can't be configured in keybinding section.

This is especially an issue for AZERTY keyboard player.

Slightly related to #9665

**Comment by SlayksWood** [comment]
Thank your for the report, Excavator controls should be fixed in 0.9.0. Now it uses Move controls:
![image](https://user-images.githubusercontent.com/45708377/80937969-ebb5b900-8ddf-11ea-9abd-1e1a40e46000.png)
