### ISSUE TITLE
Several Problems with own world on 9.0

### ISSUE THREAD

**Issue by xShoura** [StrangeLoopGames/EcoIssues#16094]
I started my own server using the 9.0 beta version.
I am using the current version (newest update).
I did not use Eco Server but Eco itself.
Everything worked fine so far, so it was/is possible to play 9.0 beta on your own world.
A few days ago (29. or 30. of april) some problems appeared.

### Problems:
1. Hotkeys (like b, c, o... /next to the minimap) don't work anymore
   You can still use your mouse to click on the icons. (All icons show 1 as a hotkey)
2. If you want to harvest stone, you can only pick up the small stones (if broken into 3 pieces). The big one has no hitbox and can't be broken into small ones.
3. The skill menu is broken. Only self-improvement is available
4. If you dig dirt with your shovel, your can't see any dirt on your shovel. And you can keep on digging until you have 10 dirt in your inventory.

### I tried to fix it several times. Those are my tries:
1. Waiting for an update
   -> same problems
2. Repair via Steam
   -> same problems
3. Playing on the official 9.0 test server
   -> no problems
4. Starting a new own world 
   -> same problems
5. Uninstall Eco and re-install again
   -> same problems
6. Uninstall Eco, delete all Eco folders, re-install again
   -> same problems
7. Sending my world files to a friend. He hosted my world and I joined.
   -> NO PROBLEMS
8. After some time he send those files back. I hosted the world.
   -> same problems
9. Uninstall Eco, re-install again, Using the new files of my world I got from my friend
   -> same problems

### My files:
[log_200502104436.log](https://github.com/StrangeLoopGames/EcoIssues/files/4568879/log_200502104436.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4568895/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4568896/Player-prev.log)

**Comment by beastyn** [comment]
@xShoura thank you for the report.
Can you also tell us about your PC spec (OS, hardware)?

**Comment by xShoura** [comment]
@beastyn sure.

CPU: AMD Ryzen 5 1600x (6 cores) 3.60 GHz
GPU: NVIDIA GeForce GTX 1080
RAM: 16 GB
OS: Win10

Small update:
I tried to start my world again and recognized an error in the loading screen. Don't know if this is a critical one.
![eco error](https://user-images.githubusercontent.com/64707256/80955944-7efee680-8e00-11ea-84ee-65b58f8e5968.png)

**Comment by mirasrael** [comment]
@xShoura Can you send your Eco game save and Eco server config files?

**Comment by xShoura** [comment]
@mirasrael 
Eco game save is located in ...\Steam\steamapps\common\Eco\Eco_Data\Server\Storage? 
Eco server config files located in ...\Steam\steamapps\common\Eco\Eco_Data\Server\Configs? Do you need all of them?

**Comment by xShoura** [comment]
[config.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4586801/config.zip)
[9.0 2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4586805/9.0.2.zip)

**Comment by mirasrael** [comment]
Did you friend use same config files?

**Comment by xShoura** [comment]
No.
I just sent him both files you can find in the "9.0 2.zip".
He put both files into \Server\Storage folder, started Eco and started/continued my world.

**Comment by mirasrael** [comment]
@xShoura at least hot keys not working for me on your save and config :)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/81193624-4ad42300-8fc4-11ea-8c91-68857e4af4ea.png)
skill menu broken as well :)

**Comment by mirasrael** [comment]
To fix this I think you can try set language to English or/and reset all configs to defaults. But I'll investigate your issue.

**Comment by xShoura** [comment]
Yes, the skills are broken too. Did I forget to say that? :/
I allready reinstalled the game.
So, deinstalled it, deleted ALL Eco folders (so configs as well) and installed it again via steam. So i should have all default configs. The only thing I am using is german as a language. But I could try to set it to english.

**Comment by xShoura** [comment]
Ah and I just changed setting in 2 config files (WorldGenerator and WorldGenerator.eco)

**Comment by xShoura** [comment]
Ok, actually I can't even start my world anymore Oo
I reinstalled the game again, deleted all folders/files (even in the AppData Section).
And if I put my gamefiles back into Storage, I can't start the game:

![20200506182240_1](https://user-images.githubusercontent.com/64707256/81202252-9d164380-8fc6-11ea-8874-87295321eaac.jpg)

**Comment by xShoura** [comment]
He uses the default config files.
He sent me his config files a few minutes ago. I replaced mine with his files. The problem is, that I can't load a world atm.

I tried the language "solution". If I create a new world with English as a language, there are no problems - everything is fine. If I create a world in German, I have those problems.
But I still can't load a world. Just create a new one or press continue. The Load Button doesn't work (my friend tested this too - load button is also broken).

**Comment by mirasrael** [comment]
May be problem with `(` ?

**Comment by xShoura** [comment]
I changed this allready back to "9.0 2". Same issue.
As I said, the load button seems to be broken. 
I created a new world ("test"). Works fine. If I quit the game, I can click on continue to start "test" again. If I go to "my worlds" instead, select any world (doesn't matter if "9.0 2" or "test"), the load button doesn't work. Doesn't work for my friend too.
Same with the "Quit" button on the main screen. Does not work.

**Comment by mirasrael** [comment]
Ok. It is different bug with Load button then. Can you create a separate issue for tracking? As workaround you can start your game with standalone server.

**Comment by mirasrael** [comment]
I fixed original issue (which was related to non-English language and good translation :)).

**Comment by xShoura** [comment]
Ok, so the languages different to English are bugged right now, right?
I guess this will be fixed at least after 9.0 is official?
Yes, I can create a separate issue :)

**Comment by xShoura** [comment]
Update:
You guys are pretty fast :D I wanted to create some screenshots for the new issues but it seems you allready fixed that button problem in the last few hours :D
So thank you very much for your help :) 👍 
Hopefully other languages will be available again someday :D

**Comment by mirasrael** [comment]
@xShoura I already fixed this language issue. You just need to wait until my PR merged and version updated ;)

**Comment by xShoura** [comment]
Amazing :)
I will reply here after testing it :)

**Comment by beastyn** [comment]
@xShoura 
PR is merges, you azrte free to test.

**Comment by xShoura** [comment]
Tested - works for me :)
Thank you for your help :)
