### ISSUE TITLE
USER ISSUE: connection timed out

### ISSUE THREAD

**Issue by yun2005** [StrangeLoopGames/EcoIssues#16104]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
ı cannot play because of this error connection timed out

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Connection timed out
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Connection timed out
```

**Comment by yun2005** [comment]
No I Hav enot modes insatalled

**Comment by beastyn** [comment]
1. Please provide your latest logs from /Steam/steamapps/common/Eco/Eco_Data/Server/Logs.

2. Please save your Storage folder in /Steam/steamapps/common/Eco/Eco_Data/Server/ and uninstall the game. Afterwards, please remove the complete /Eco folder mentioned above, then reinstall the game. This should fix this issue.

**Comment by yun2005** [comment]
Hi,
Thank you very much for your reply, I followed the steps you said. I can
now play again successfully. But when I want to start one world in the game
generating terrain is loading very slowly but it is not problem and in the
game my player is going or moving slowly. Thanks again.

4 May 2020 Pzt 07:37 tarihinde Anna <notifications@github.com> şunu yazdı:

**Comment by SlayksWood** [comment]
@yun2005 it generate new world. It's should take some time. Closed.
