### ISSUE TITLE
[0.9 Staging-1526] Work Order tooltip isn't helpful in determining if you have enough materials for the whole order

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16103]
The Work Order tooltip is not very helpful in determining if you have enough materials to complete the order. It has all the information, but it doesn't display it at all times.

When you have materials, you see how many materials you have available:

![image](https://user-images.githubusercontent.com/964559/80913923-12e78a00-8cfd-11ea-8995-478efc815e30.png)

If you don't have the materials but don't need more for completing the current single item of the Work Order, you just see zeroes:

![image](https://user-images.githubusercontent.com/964559/80913947-30b4ef00-8cfd-11ea-9541-272854c4827d.png)

When you don't have enough materials for the current single item, that's when you start seeing how much materials you'd need for the entire Work Order:

![image](https://user-images.githubusercontent.com/964559/80913965-517d4480-8cfd-11ea-8895-cb9587f50695.png)

It would be nice if the information from the third screenshot was available along with the information from the first screenshot. Something like "0 Iron Ore total remaining (60 available in storage out of the needed 200".

This would lower the amount of guesstimating how many items you need to craft to complete a complex order if you don't or can't plan ahead.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/5992
