### ISSUE TITLE
[0.9 Staging-1526] Excavator digs without mouse input

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16102]
After playing around with the Excavator I noticed it digs even when I'm not pressing the left mouse button, which I don't think is the proper behaviour:

https://youtu.be/86QvKmHGc0U
(I didn't touch my mouse at all and yet the Excavator dug on its own)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Spawn Excavator
- Move its arm so its bucket would be in the position to dig a block, press into that block, don't press LMB
- Excavator will dig that block up (or pick up the rubble) even though LMB was not pressed

3) Expected behaviour
The Excavator should only dig blocks when the correct button is pressed (like the Skid).

4) Actual behaviour
The Excavator digs without the correct button being pressed.

5) Providing Log files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4570206/Player.log)

**Comment by beastyn** [comment]
It's intended.
Made by @mirasrael

**Comment by mirasrael** [comment]
Requested by @johnkslg :-D
