### ISSUE TITLE
[0.9.0 staging-1526] - Parallel Processing calculation doesn't match description

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16107]
The description for the Parallel Processing perk reads "Increases the speed of related tables when they share a room with the same tables by 20 percent."
Looking at the code - unless I'm missing something - what appears to be happening is the perk has a craft time modifier of 0.8f, and applies it multiplicatively when the number of tables is 2 or greater.

This seems to indicate a **craft time reduction** of 20%, not a **craft speed increase** of 20% as the description suggests. A craft time reduction of 20% is equivalent to a craft speed increase of 25%.

Perhaps more importantly, there is confusion about whether the perk adds further 20% bonuses when additional tables are added. It's clear from the code that this not the case (although it might be nice if it were), but it suggests the explanation for Parallel Processing is unclear as there's has been speculation about how this perk operates. This also means that Focused Workflow is easily the dominant choice between these two options.

These are only small points, but I wanted to highlight that this perk is not working as advertised, and appears to be clearly the weaker option, in case it is a candidate for future rebalancing.

**Comment by SlayksWood** [comment]
Thank you for the report, this talent should be reworked in 9.1.
merged with #12407
