### ISSUE TITLE
[0.9 Staging-1526] Unable to log into servers

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16100]
Out of the blue I seem to be having problems logging into servers:

![image](https://user-images.githubusercontent.com/964559/80909047-dfdfcf00-8cd9-11ea-80a2-cfffb8f20935.png)

When I try logging into a friend's hosted world, I get stuck on Entering World. When I try joining Royal Otter, I get the above error. Tried restarting the game, Steam and the computer, still nothing.

Log:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4569785/Player.log)

**Comment by ThePiachu** [comment]
So in the end I was able to log into the testing server, I'm still getting the same Connection Failed errors on Royal Otter, and logging onto my friend's game required them to restart their server. Not sure what was wrong with their game, but detecting if something goes wrong and displaying a proper error might be good for that case regardless.

**Comment by beastyn** [comment]
@ThePiachu 
So, do you have problems with Otter now or you do not? It was disables when you've created an issue.

**Comment by ThePiachu** [comment]
I wan log onto Royal Otter now, I was unable to earlier, even though it appeared online.

**Comment by beastyn** [comment]
May be auth problems. Not actual.
