### ISSUE TITLE
[0.9.0 Staging-1538] Third person view not available

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16119]
Steps to reproduce - Click the 'third person' checkbox from the backpack menu

Expected behavior - Toggle third person view

Actual behavior - Nothing happens

Log files -
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4577070/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4577071/Player.log)

**Comment by trickenso** [comment]
I can now access third person view. Unsure what has changed - will update if anything changes, but feel free to close if necessary.

**Comment by SlayksWood** [comment]
Closed for now, like not reproducable.
