### ISSUE TITLE
Anti-cache for Web UI

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#16116]
A lot of time we and QA waste on testing something, that was just cached by browser.
I want to make anti-cache algorithm so we won't happen to be fooled by cache again.
I'll add build version to JS resources require urls, so cache will be cleared with each build.

**Comment by lagonnebula** [comment]
There is the same issue on live server when you change the website user have cached version, this isn't a real issue if you tell your user to remove the cache but ... It's kind of annoying when people don't really know how to do this huhu

**Comment by denysaw** [comment]
@lagonnebula Exactly ) Lets completely get rid of this problems )

**Comment by lagonnebula** [comment]
Maybe a simple fix would be to add a timestamp to each resource at server restart. So you would have only one cached version by server start ?

**Comment by denysaw** [comment]
It would be harder I guess ) Standard anti-cache is adding a random number each time ) But that way we won't have cache at all. And with our huge JS code, better to have it ))

**Comment by lagonnebula** [comment]
Yeah if you had each time a timestamp. But if you let the server generate a timestamp at start and write it on resource and keep this one ? (I don't know how is handled the webserver in the game)
