### ISSUE TITLE
[0.8.3.3] Multiple eco server on the same machine

### ISSUE THREAD

**Issue by lagonnebula** [StrangeLoopGames/EcoIssues#16115]
Hello,

Im using docker to run 2 servers on the same machine. 
One with the 3000:3000 and 3001:3001 bind and the second with the 4000:3000 and 4001:3001 on the docker network. 
I have 2 issues the link for the Webpage are automaticly bind to IP:3001 and I can't change it since I put the second server to a bind to 4001:4001 (running the webservice on port 4001).
And the 2nd issue is on the server listing only one server appear on the list and it's the last started server , maybe because the 2 are on the port 2999 but I don't see some option about it :/

**Comment by mirasrael** [comment]
Hi @lagonnebula 
You have at least two options:
1. You can change RemoteAddress and WebServerUrl in Network.eco. They will override default addresses.
2. You can change GameServerPort and WebServerPort in Network.eco to use different ports for two containers.

**Comment by lagonnebula** [comment]
Hello, thanks for the answer. I tried the 1st Option.
``` Network.eco
{
"RemoteAddress": "IP:4000",
 "WebServerUrl": "IP:4001",
}
```
But with this, I can't open the Webserver from the game. 
And the Server Listing is always messing up the 2 server. It's always display the last serveur to open. And Even if you add them in favorite the 2 show the same name :/ 

With the options 2 I have the Webserver working correctly but the issue with the server listing

**Comment by mirasrael** [comment]
You definitely should have different Server ID and Passport, because otherwise they are same for Master Server and it will report last registered (they re-registers every minute or something like this).

**Comment by lagonnebula** [comment]
I finally make it to work, I'have deleted ID and passport and it make a new one and I've put the protocol in the webserverUrl ! @mirasrael Thanks for the help :D

**Comment by mirasrael** [comment]
@lagonnebula you're welcome ;)
