### ISSUE TITLE
[0.9.0 staging-1538] Expandable Error notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16110]
Make error notification like Okbox, Because sometimes it looks strange:
![image](https://user-images.githubusercontent.com/45708377/80942284-13f7e480-8ded-11ea-8de1-230b62841fd4.png)
It will look better if it will be in 1 string.
But you can make it bigger but not almost full screen

**Comment by johnkslg** [comment]
What do you mean 1 string? Its already one string "you already own this property"

**Comment by johnkslg** [comment]
I think it looks fine as a popup like that
