### ISSUE TITLE
[0.9.0 staging-1538] Can't collapse inventory by clicking its name and also havent sound 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16111]
I can collapse inventory only in green zone, but I assume it should be any place in red zone like for linked inventories. Also I haven't sound when I collapse inventory. When I collapse linked inventory i have sound, i assume it should be same sound here too:
![image](https://user-images.githubusercontent.com/45708377/80953858-ff274b00-8e04-11ea-9a76-0fc4aea0b071.png)

**Comment by beastyn** [comment]
If you collapse inventory intraction will be missed in around arrow
Only in collapsed state
