### ISSUE TITLE
[0.9.0 staging-1538] Recipe names use class names instead of display name

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16118]
Recently the item filter and Ecopedia were fixed to use display names instead of class names. This same fix needs to happen for recipe names.
![RecipeNameIssue](https://user-images.githubusercontent.com/47330823/80984506-cd9d8800-8de2-11ea-9009-d38148b7777a.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/81167777-7d6b2500-8f9e-11ea-947c-56aed2a09ba8.png)
