### ISSUE TITLE
[0.9.0 Staging-1538] - Moon disappearing near edge of screen

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16126]
Steps to reproduce: Pan around with the moon on screen.

Expected behavior: The moon would remain visible until it is entirely offscreen.

Actual behavior: It pops in and out in full view

Moon in view:
![image](https://user-images.githubusercontent.com/48172405/81030230-f9228000-8e7f-11ea-9b69-9bb2ee21a6c9.png)

And immediately afterwards with a tiny camera move:
![image](https://user-images.githubusercontent.com/48172405/81030235-fe7fca80-8e7f-11ea-8e37-82043e662550.png)

Log files:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578676/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578675/Player-prev.log)

**Comment by SlayksWood** [comment]
dup #12358

**Comment by trickenso** [comment]
Thanks @SlayksWood - didn't spot this dupe.
