### ISSUE TITLE
[0.9.0 Staging-1538] -  Rogue objects in 'Housing Objects' category

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16122]
Steps to reproduce - Filter trades by 'Housing Objects'

Expected behavior - Filtered objects would be furniture suitable for placement in a house.

Actual behavior - List contains the industrial buildings arrastra, bloomery, carpentry table, kiln, masonry table, rocker box, tailoring table, wainwright table, windmill, and waterwheel, which are not appropriate for use as furniture.

**Comment by SlayksWood** [comment]
Almost all crafted tables are Housing Objects too:
![image](https://user-images.githubusercontent.com/45708377/81056922-1ed97480-8ed4-11ea-9d96-44b1a9cfe511.png)
It's intented behavior for now.
@WeaselDog 
Can you confirm this?

**Comment by elfl0rd** [comment]
as far as I know - "industrial" items still housing objects.
But industrial item, reset room points to zero.

**Comment by trickenso** [comment]
The gameplay result is that the 'Housing Objects' category is cluttered when you use it as a trade filter for buying furniture.
The crafting tables are already contained in the 'Crafting Tables' category, so from a trade perspective it's a bit redundant.

**Comment by WeaselDog** [comment]
Working on the item filter today. I will get these cleaned up.
