### ISSUE TITLE
Icons for Specialties

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16124]
We need new updated icons for specialties

![image](https://user-images.githubusercontent.com/14983165/81027598-4298ae00-8e33-11ea-8ff2-c46b9f18e72b.png)

- [x] Composites Specialty Icon: This can show a couple layers of wood and plastic coming together
- [x] Paper Milling Specialty Icon: This should show paper making in some form, perhaps a water bath with a sheet of paper coming out of it, or a paper on drying racks, or wood pulp being poured into a bath.

![image](https://user-images.githubusercontent.com/14983165/81027690-8c819400-8e33-11ea-838f-ba7975e501c1.png)

- [x] Advanced Baking Specialty Icon
- [x] Advanced Cooking Specialty Icon
- [x] Campfire Cooking Specialty Icon
- [x] Cutting Edge Cooking Specialty Icon

![image](https://user-images.githubusercontent.com/14983165/81027750-b9ce4200-8e33-11ea-8554-f8e2d2f8dbea.png)

- [x] Basic Engineering Specialty Icon
- [x] Industry Specialty Icon
- [x] Mechanics Specialty Icon
- [x] Oil Drilling Specialty Icon

![image](https://user-images.githubusercontent.com/14983165/81027814-f601a280-8e33-11ea-83af-a822c58fb7c0.png)

- [x] Gathering Specialty Icon
- [x] Milling Specialty Icon: This one should be made to be in color to match other specialty icons, otherwise could be the same
- [x] Fertilizers Specialty Icon: It'd be better to have an icon showing the fertilizer can being used for this icon than just the same icon as the can item.

![image](https://user-images.githubusercontent.com/14983165/81027915-4c6ee100-8e34-11ea-88a7-86867e10393f.png)

- [x] Glassworking Specialty Icon: show glass being blown or something
- [x] Pottery Specialty Icon: Can show things being fired, just shouldn't be same icon as kiln item. Could show things being spun on a wheel
- [x] Masonry Specialty Icon
- [x] Advanced Masonry Specialty Icon

![image](https://user-images.githubusercontent.com/14983165/81027980-8a6c0500-8e34-11ea-987d-56f976ede995.png)

- [x] Advanced Smelting Specialty Icon

![image](https://user-images.githubusercontent.com/14983165/81028001-9a83e480-8e34-11ea-912a-e2f92012ff11.png)

- [x] Self Improvement Specialty Icon

![image](https://user-images.githubusercontent.com/14983165/81028014-a8396a00-8e34-11ea-867d-fd82c7e0ec07.png)

- [x] Tailoring Specialty Icon

**Comment by RobertMangano** [comment]
icons are created, they just need to be placed on the icon sheet

**Comment by RobertMangano** [comment]
icons on icon sheet 04

**Comment by RobertMangano** [comment]
keegan and I are plugging these in but the task is complete
