### ISSUE TITLE
Optimize quad tree 'GetRelevantObjects'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16121]
Found this as one of the main bottlenecks on the server.
Eco.Plugins.Networking.QuadTreeNetObjectCollection.GetRelevantObjects(INetObjectViewer, INetObjectContainer)

**Comment by mirasrael** [comment]
Can you please cover all cases with unit tests before refactoring to ensure everything is working after refactoring?

**Comment by johnkslg** [comment]
Didnt touch any logic in the quad tree itself, just made it track and send new objects.  
Tests the netobject update system would be a good add, but also a big job as theres no tests for them yet, lots of mocks need to be created.  The optimizations ended up being pretty minor, we can leave that for later.
