### ISSUE TITLE
[0.9 Staging-1538] Unable to turn off the Cement Kiln

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16127]
With the new Staging release, I think we lost the ability to turn off the Cement Kiln:

![image](https://user-images.githubusercontent.com/964559/81031026-b6d94e80-8e3f-11ea-92e4-d11b6c3de982.png)

I'm guessing that's due to the game thinking I'm trying to put my tool into the Cement Kiln and not accepting it. This wasn't an issue in the previous Staging release that was available to the testers.

1) Version
0.9 Staging-1538

2) Steps to reproduce
- Go to Cement Kiln (holding a tool?)
- Try to turn it off
- Be unable to

3) Expected behaviour
You should be able to turn off the Cement Kiln.

4) Actual behaviour
You can't.

**Comment by SlayksWood** [comment]
it tries to place tool in Fuel supply.
I asssume It's related with possibility to put Tools by RMB in stockpile. We should to prevent it (like in 0.8.3)
