### ISSUE TITLE
server browser polish

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1612]
now that we have more servers, we need some more organization tools

- add locale option to server config (network tab)
- sort by ping/playercount/server day/locale
- Never hide a favorite entry. If the favorite is being pinged for a response, show some sort of spinning icon denoting that
- Even if a favorite is whitelisted, and we are not on the whitelist, still show the favorite in the server listing. (consider displaying whitelisted servers in a different fashion, instead of silently not showing them)

**Comment by Uniphix** [comment]
Ability to search servers would also be nice!  And the ability to keep track of your recent servers that you have played on.  Maybe restrict it to like last 3 servers you we're on that are online of course.

**Comment by metachronism** [comment]
handing this off since you are already working on it @MarjieAVolk

**Comment by MarjieAVolk** [comment]
All of these things should be implemented in 7.4
