### ISSUE TITLE
[0.9.0 Staging-1538] - Raw Food tag doesn't include all raw foods

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16120]
Steps to reproduce: Craft any recipe with Raw Food tag
Expected behavior: Should be able to add fireweed shoots, cookeina mushrooms, and perhaps others. Beet greens?
Actual behavior: Not all raw foods included in this tag.

**Comment by WeaselDog** [comment]
Thanks for the feedback. We will be adding to this tag to all produce except Amanita Mushrooms which are poisonous when raw.
