### ISSUE TITLE
[0.9.0 Staging-1538] - Credit amounts in Store don't update

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16128]
Steps to reproduce: Make a trade in a store.

Expected behaviour: 'Trade result' value would update dynamically as you adjust planned trade. After a sale, currency amounts 'you have' would update.

Actual behaviour: 'Trade result' remains 0 throughout process. 'You have' credit figure stays the same until you exit and re-enter store.

Logs:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578711/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578715/Player-prev.log)'

**Comment by trickenso** [comment]
Note: This is only happening intermittently - Tried multiple times to confirm the problem was happening initially, but I just traded again at a different store and didn't have the same issue.

First time was trading raw food, and second was logs, in case that makes a difference.

Updated logs:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578742/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4578749/Player-prev.log)

**Comment by SlayksWood** [comment]
I have a few times this issue on playtest, but I can't reproduce it in my local world.

**Comment by SlayksWood** [comment]
@olegshegai 
can you try to check this?

**Comment by trickenso** [comment]
Just happened to me again:

After selling some items, shows 0 Xao credit:
![image](https://user-images.githubusercontent.com/48172405/81147241-cd7fc280-8f71-11ea-8012-11d36f5374ed.png)

Closing and opening the store shows the correct amount - 20 credit:
![image](https://user-images.githubusercontent.com/48172405/81147255-d6709400-8f71-11ea-8691-281f15861bb6.png)

Logs in case they might be useful - taken as soon as I could after I noticed the same thing recurring:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4585268/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4585269/Player-prev.log)

**Comment by trickenso** [comment]
Related, but let me know if its should be a separate ticket. The 'Trade Result' number doesn't update dynamically as you type, which I recall it doing in 8.3. It all adds to the sensation that the store isn't responding, when the trade result in general is working just fine.

**Comment by johnkslg** [comment]
Need to make the display for these subscribe to the correct account holding so they update properly.  And the subscription needs to update when the selected bank account changes.

**Comment by SlayksWood** [comment]
It works fine for me in local world. I assume it was fixed, I will reopen it if it happens again.

**Comment by SlayksWood** [comment]
@trickenso can you approving it on the playtest? (after upgrading to staging-1607 and later)

**Comment by trickenso** [comment]
@SlayksWood I'll keep a lookout for this one - thanks!
