### ISSUE TITLE
[0.9.0 staging-1539] Animal: deers should visit a doctor

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16137]
They have problems with legs. Their knees are pointing in the different directions.
![bandicam 2020-05-05 15-57-59-370](https://user-images.githubusercontent.com/27898520/81059251-89e17600-8ee9-11ea-9f26-ddabe5f7ba17.jpg)

![bandicam 2020-05-05 16-02-07-059](https://user-images.githubusercontent.com/27898520/81059424-d462f280-8ee9-11ea-8f27-8ead44cadd8f.jpg)

**Comment by StanKryvenko** [comment]
updated in svn
