### ISSUE TITLE
Info Window not working after joining Royal Otter

### ISSUE THREAD

**Issue by m-r-Gamez** [StrangeLoopGames/EcoIssues#16133]
Version: public_test_9.0

Expected: Info window (login panel, chat, channels, etc) should show welcome after logging into a game.

Actual behavior: Info window is not showing anything until closed or redimensioned.

Steps to reproduce:
1. Join Royal Otter in public_test_9.0 branch.

**Comment by trickenso** [comment]
I had this one as well.

On login the chat window is blank:
![image](https://user-images.githubusercontent.com/48172405/81023906-c3729c80-8e69-11ea-9f59-4397de96fbcb.png)

After adjusting chat window size:
![image](https://user-images.githubusercontent.com/48172405/81023960-d7b69980-8e69-11ea-8f02-946065afff54.png)

**Comment by TwixterZ** [comment]
@m-r-Gamez & @trickenso

Thank you both for your report, I have tested this in the current version of ECO and did not see this issue. 

Considering the age of this report, I will close this issue for now. If any of you facing this issue again please let us know by raising a new issue.

**Comment by TwixterZ** [comment]
@m-r-Gamez & @trickenso

Thank you both for your report, I have tested this in the current version of ECO and did not see this issue. 

Considering the age of this report, I will close this issue for now. If any of you facing this issue again please let us know by raising a new issue.
