### ISSUE TITLE
[0.9.0 staging-1539] Sleep doesn't finish the order and multiply pollution

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16134]
1. Place a blast and make an oeder for 1 hour
![bandicam 2020-05-05 14-26-42-842](https://user-images.githubusercontent.com/27898520/81052785-81833e00-8edd-11ea-8744-c89a8a3e9360.jpg)

So we know, that our blast will make 3.6 ppm for that hour
2. Go to sleep for an hour or little more
![bandicam 2020-05-05 14-26-59-948](https://user-images.githubusercontent.com/27898520/81052890-b2fc0980-8edd-11ea-99a8-44d9fffba6cf.jpg)

3. Wake up and see what you have on your blast

Expected: order is finished and pollution is +3.6 ppm

Actual:

1) Order is not finished visually, it still have timer on and looks like it's trying to finish itself very fast, though time bar will show complited status

![bandicam 2020-05-05 14-47-18-208](https://user-images.githubusercontent.com/27898520/81053996-6adde680-8edf-11ea-95b0-2aeb1c851128.jpg)

2) Pollution is > 10 ppm

![bandicam 2020-05-05 14-27-43-356](https://user-images.githubusercontent.com/27898520/81054089-95c83a80-8edf-11ea-9811-f2d6e97b1abb.jpg)

**Comment by mirasrael** [comment]
@johnkslg you last changed pollution and the work order behavior probably related to your 
ContributedCraftTime optimization.

**Comment by johnkslg** [comment]
Fixed pollution responding to sleep.
![image](https://user-images.githubusercontent.com/3536496/81242859-12801500-8fc3-11ea-9cae-ca0baddba4fc.png)

Also fixed work orders responding to sleep.

**Comment by beastyn** [comment]
I was checking it with sleeping today.
Craft was finished just fine, but pollution is counting wrong, from the UI.
![bandicam 2020-05-21 10-26-06-998](https://user-images.githubusercontent.com/27898520/82526523-ac13fe80-9b4d-11ea-8825-6328efe78faa.jpg)

It was making an order for one hour, and everything was crafted. 
Pollution from the blast should be 3.6, but it shows 0.18

**Comment by johnkslg** [comment]
@beastyn thanks for your persistence in getting this solid, really makes a big difference for our players!

Fixed:
![image](https://user-images.githubusercontent.com/3536496/82602102-6b27e400-9b65-11ea-9484-8038315a4dcf.png)

**Comment by beastyn** [comment]
@johnkslg Purrrfect, thank you!
