### ISSUE TITLE
[0.9.0 staging-1540] Delete Camas Paste from RawFood tag

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16149]
![image](https://user-images.githubusercontent.com/45708377/81141909-b099be00-8f76-11ea-98f4-2578113937dd.png)
![image](https://user-images.githubusercontent.com/45708377/81141946-ce672300-8f76-11ea-8d24-886ee3efb280.png)

**Comment by WeaselDog** [comment]
Is already fixed in next PR.
