### ISSUE TITLE
USER ISSUE: Excesivo consumo CPU y GPU 

### ISSUE THREAD

**Issue by aestevezn** [StrangeLoopGames/EcoIssues#16142]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
- Arrancar el juego
- Consumo de la CPU y de la GPU por encima del 50% con los graficos al minimo. RTX2060

**Expected behavior:**
- FPS por encima de 60

**Actual behavior:**
- FPS que no llegan a 10

**Do you have mods installed? Does issue happen when no mods are installed?:**
- FPS que no llegan a 10

**Comment by SlayksWood** [comment]
@aestevezn Thank you for the report. Can you provide some information?
1. Please provide your PC specification (include Operating System).
2. Provide graphics settings (It could be a screenshot.)
3. Provide information from task manager (processes and performance tab) when you have 10 FPS

**Comment by aestevezn** [comment]
Hi!

1.  Specifications
CPU i5-4670K
GPU RTX 2060
RAM 16G
SO Windows 10 Pro

2.a. Full
3.a. 
14 fps 
45% CPU
4.2 GB Ram
100% GPU
![image](https://user-images.githubusercontent.com/63251217/81211074-2469b400-8fd3-11ea-87ff-b447198fd3e5.png)

2.b.Minimun
3.b
36 FPS
35% CPU
4.2 GB Ram
8,7% GPU

![image](https://user-images.githubusercontent.com/63251217/81211202-524ef880-8fd3-11ea-9bad-0777c24022e8.png)


Please I really want to play the game but is imposible on this way, I play other games in ultra quality without those problems and with a normal fps ratio, as you can see the specifications been enough

**Comment by SlayksWood** [comment]
> This is only one instance i have captured out of the 3 times this has happened,
> 
> My ram usage for eco has hit a total of 19,000MB
> This current image shows eco using 10GB of ram after only 10 minutes of gameplay,
> 
> 1 other user has reported high usage as well,
> This image also shows my graphics settings
> 
> PC Specs,
> i7-8700k @ 4.7ghz
> 32GB 3200Mhz GSkill Ram
> 1070TI
> Currently stored on a HDD not a SSD
> ![high memory usage](https://user-images.githubusercontent.com/29281156/82033247-ced28d00-96df-11ea-85bd-d6ad42ad65b1.PNG)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4633489/Player.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4633491/Player-prev.log)

**Comment by SlayksWood** [comment]
> Here is a snap from another player with the same issue
> ![other user](https://user-images.githubusercontent.com/29281156/82033626-55876a00-96e0-11ea-9676-7e02b0c5e97e.png)

**Comment by aestevezn** [comment]
I am not sure if this clue can help but seems in all cases we have 2 gps and 2 monitors with borderless option active.

In my case i can confirm ECO is using the correct GPU (RTX 2060)

**Comment by SlayksWood** [comment]
#16421
> Since the last update I cannot get over 38 fps no matter what I do in the graphics settings. In the main menu I get 90 fps and GPU load at 96% but when loading into the server I only get 38 fps. GPU load about 30%
> Turning all graphics sliders to the minimum or maximum does not matter I still only get 38 fps.
> 
> I have tried reinstalling (+ deleting all settings from appdata). Tried different GPU drivers.
> 
> I have an i5-9600K, 32GB RAM and RTX 2070 Super
> CPU load is at 40%
> 
> This happened in this version: [0.9.0 Staging-1554]
> It was good in: [0.9.0 Staging-1542]
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4659561/Player-prev.log)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4659562/Player.log)

**Comment by revtje** [comment]
> #16421
> 
> > Since the last update I cannot get over 38 fps no matter what I do in the graphics settings. In the main menu I get 90 fps and GPU load at 96% but when loading into the server I only get 38 fps. GPU load about 30%
> > Turning all graphics sliders to the minimum or maximum does not matter I still only get 38 fps.
> > I have tried reinstalling (+ deleting all settings from appdata). Tried different GPU drivers.
> > I have an i5-9600K, 32GB RAM and RTX 2070 Super
> > CPU load is at 40%
> > This happened in this version: [0.9.0 Staging-1554]
> > It was good in: [0.9.0 Staging-1542]
> > [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4659561/Player-prev.log)
> > [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4659562/Player.log)

^ This was my comment in another ticket I have got the game to 47 FPS and 67% GPU load now. Enabled XMP in BIOS, changed power plan in windows to high performance and set Power management mode to Prefer maximum performance in NVIDIA Control Panel. Still not good enough for and not even close to the fps I get in the main menu or build 0.9.0 Staging-1542 where I got 90 FPS.

Main menu VSYNC ON (I have 75Hz monitor so it caps at 75:
![main_menu_vsync_on](https://user-images.githubusercontent.com/39825431/82545454-ff3e7f00-9b56-11ea-9095-7fb9208c24d5.jpg)

Main menu VSYNC OFF
![main_menu_vsync_off](https://user-images.githubusercontent.com/39825431/82545473-05346000-9b57-11ea-9411-f7ac4db0964f.jpg)

In game: 
![ingame](https://user-images.githubusercontent.com/39825431/82545497-10878b80-9b57-11ea-9209-7475d8ed340f.jpg)

Load:
![ecogpuload](https://user-images.githubusercontent.com/39825431/82545506-154c3f80-9b57-11ea-88a4-5ee1fe613bba.png)

**Comment by revtje** [comment]
Removing all global markers gives an 5-10 fps increase

**Comment by henrikolsson** [comment]
Around 45 FPS with everything on lowest settings in an unpopulated area on Royal Otter:
![image](https://user-images.githubusercontent.com/982322/82570959-95d46580-9b82-11ea-9555-80c8d7b6a57d.png)

Hardware: Core I7 5820k, RTX 2060.  ~20-30% load on gpu, ~30% load on CPU. No single core over ~60% load.

**Comment by revtje** [comment]
Started version 8.3.3 just because I was curious. Getting 150 fps with GI on high and AA on high and everything else maxed out. So smooth.

**Comment by revtje** [comment]
**Update**: Have 90 fps in single player with same build. If I log into Royal Otter at a busy place the FPS will be bad. If I log out in the middle of nowhere and log back in the FPS is at 57 until I go to my place and open a storage chest then its bad again.

So the issue seems to be that it's loading too much stuff when I login to Royal Otter.

**Comment by mirasrael** [comment]
@revtje can you comment if you have improvements with latest build 1594+?

**Comment by WeaselDog** [comment]
@revtje Hi I wanted to follow up to see if you are still having this issue. We have made some improvements to optimization in 9.0 staging-1594.  This issue is marked to be closed due to inactivity, so please reply back if this is still an issue for you.

**Comment by revtje** [comment]
Hi. Sorry I missed the replies. This problem is fixed. Good job! :)
The only issue regarding performance now is the fps degradation over time where it starts out good and goes lower the longer you play. A restart fixes it. But I believe there is a separate issue for that since that problem has been around for a long time.

**Comment by mirasrael** [comment]
Thanks for response @revtje !
