### ISSUE TITLE
[1539] Crash when harvesting a specific plant while law prevents that

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16140]
Harvesting this: https://cdn.discordapp.com/attachments/540912210621497344/707236021024194670/Unbenannt.png

Leads to:

```
--BEGIN DUMP--
Dump Time
05/05/2020 15:51:34

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--
```

**Comment by mirasrael** [comment]
Can't reproduce. Did you pickup it or use some tool? Also this error happens in async mode so may be in result of other (one of previous operations or from another player).

**Comment by D3nnis3n** [comment]
It's a server with multiple people, but at that time noone else was online. Crash is reproducable for them. Both pickup and shovel cause it.

**Comment by mirasrael** [comment]
Need the save file and the username then.

**Comment by D3nnis3n** [comment]
Caused by a law that prevents pickup. Requested save file.

**Comment by Alteraner** [comment]
Hello,
 here you can find the Game.eco file:
https://1drv.ms/u/s!AqAvy5MYOuAS62ZHzteQ-koagEkx?e=WdTyv7

**Comment by mirasrael** [comment]
@Alteraner It says the file corrupted (it should be valid zip archive, but it isn't).

**Comment by mirasrael** [comment]
Closed due to no response and not able to reproduce.
