### ISSUE TITLE
'Brightness' Setting in graphics settings needs to be updated (no longer works)

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16147]
**Note: This will only apply after my PR for lighting changes is merged, https://github.com/StrangeLoopGames/Eco/pull/6046**

The brightness setting in the graphics setting is now being overridden by the autoexposure post process effect, from what I can tell (it may have broken for another reason). 

Instead of having this 'brightness' setting, I think we should replace it with a 'gamma' setting that affects the gamma, and leaves the EV and brightness values of the lighting/camera alone. Hopefully this makes sense and can be done relatively easily, I'm not totally sure it is the best way to fix it so that players still have an option to tweak based on their monitor brightness. If there is another way to have it re-activated without messing up auto-exposure, that's ok too (but I imagine it might just be a direct conflict).

**Comment by keegan-o** [comment]
Interesting. I'm noticed now that the brightness setting does actually have an effect. I'm not sure if something changed or not.

**Comment by redwyre** [comment]
I'm adjusting the "Post-Exposure EV" in the global profile, but the night profile is overriding it. I use this because it's just a linear brightness. I've disabled night from changing it and bumped the gamma instead.
