### ISSUE TITLE
[0.9.0 Staging-1538] - Repeat unpredictable crashes

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16141]
When minimising the game with ALT+TAB or WIN+D it will occasionally crash and exit - generally after being minimised for a short time. This has happened a few times when doing a variety of things - in menus, in playtest, in single-player, but I can't reliably replicate it.

Here are the logs:
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4582464/crash.zip)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582461/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582462/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582345/Player-prev.log)

Let me know if there's something I can do to clarify what's happening - I'll attach more logs if it happens again, or I can just let the crash handler deal with it if that's preferable.

**Comment by trickenso** [comment]
Ok - this just happened again on playtest without tabbing out. I'm going to do a wipe and reinstall and see if that helps.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582706/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582708/Player.log)
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4582709/crash.zip)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4582725/Player-prev.log)

**Comment by trickenso** [comment]
And again after unstalling and deleting all local files before reinstall: 
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4583188/crash.zip)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4583189/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4583190/Player.log)

There doesn't seem to be a particular play action that might be causing this.

**Comment by redwyre** [comment]
Looks like a graphics driver crash, can you try updating your driver?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers

**Comment by trickenso** [comment]
Thanks - I checked this earlier, and it's showing as having the latest drivers.

Removing and reinstalling all the drivers to be sure. Will confirm the result.

**Comment by trickenso** [comment]
@redwyre - The driver I had previously was the most recent, but I uninstalled everything, and did a clean install just in case.

Just had a similar crash again. Here's the log:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4584381/Player.log)

**Comment by trickenso** [comment]
FYI - It's been stable for the last several hours, with no further changes to drivers.

**Comment by trickenso** [comment]
First crash since yesterday - assume it's the same thing :) Not adding pressure to deal with this - just making sure you have thorough documentation.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4590277/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4590278/Player-prev.log)
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4590281/crash.zip)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/4590282/error.log)

**Comment by trickenso** [comment]
Removing drivers with Display Driver Uninstaller and doing a controlled reinstall seems to have fixed this - will close until I run into it again.

Is it worth adding DDU or similar clean uninstallers to driver instructions? For people who have the latest drivers but are still having crashes? Updating to latest drivers apparently not the whole story.
