### ISSUE TITLE
Add generalized Log functionality to status component

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1615]
this would be misc events that occur that are specific to the table.  For example, most crafting tables would have a list of items that were crafted, in normal text

[5hr ago] Metachronism crafted 5 Logs
[6hr ago] Craig deposited 10 Boards
[7hr ago] Sean took 5 Tasty Meats

etc...

basically a read-only chat log for tables

**Comment by metachronism** [comment]
(this could be its own component too, doesn't have to piggyback onto status component)

**Comment by WeaselDog** [comment]
This is a nice idea but with new crafting system without hammer space I don't think it is ideal.
