### ISSUE TITLE
[0.9.0 staging-1540] Blurry items in the hands

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16152]
After last changes:
![image](https://user-images.githubusercontent.com/45708377/81145771-a03a1100-8f7f-11ea-8a9f-2f9ce125599d.png)

**Comment by keegan-o** [comment]
haha, of course. alright, since it's minimal gains anyways I'll disable DOF for now. Eventually we'll figure out how to not have it apply to the tools and such. 

fixed in https://github.com/StrangeLoopGames/Eco/pull/6049
