### ISSUE TITLE
[0.9.0 staging-1540] Civics: selection glitch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16158]
1. Start to create a law
2. In the IF line press plus and open selector
![bandicam 2020-05-06 15-59-37-281](https://user-images.githubusercontent.com/27898520/81169844-01c7a300-8fb3-11ea-8160-e30ca7d3fb80.jpg)
3. Collapse and open Logic category
![bandicam 2020-05-06 16-02-47-588](https://user-images.githubusercontent.com/27898520/81169864-0ab87480-8fb3-11ea-8b58-e99687674621.jpg)

It will lose its options. 
It will also glitch if you collapse ans then open other categories too

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/85252437-6b691700-b464-11ea-8016-37545120f274.png)
