### ISSUE TITLE
Filter Steam Links on Eco Tree and News Website

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16162]
steam://openurl_external/https://steamcommunity.com/linkfilter/?url=https://steamcommunity.com/games/382310/announcements/detail/1722001656482078015

==>

https://steamcommunity.com/games/382310/announcements/detail/1722001656482078015

Faster if you do it with a simple db query than me searching it.

**Comment by denysaw** [comment]
Done on WP side (TinyMCE filtration function). So you'll need just to re-paste articles with problematic links ;)
