### ISSUE TITLE
[0.9.0 staging-1540] Line glitches in craft icons

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16161]
It happen when you have a few orders in 1 crafted table and when you replace it:
![2020 05 06 Craft Dance](https://user-images.githubusercontent.com/45708377/81178558-1145ec80-8fb1-11ea-97ed-6e18a15e9546.gif)

**Comment by johnkslg** [comment]
Fixed in the PR I just merged
