### ISSUE TITLE
Change headline font

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16164]
![image](https://user-images.githubusercontent.com/3536496/81210193-63bde380-8f86-11ea-91d1-e20b61e7c4db.png)

It should be more like this, but in the Eco style, and not have shadow background. Work with @MilenkoTunjic to find a good font choice. 
![image](https://user-images.githubusercontent.com/3536496/81210289-8b14b080-8f86-11ea-934a-3880efe57eb5.png)

**Comment by beastyn** [comment]
I don't think its what @johnkslg is waiting for )
![bandicam 2020-05-11 15-20-13-801](https://user-images.githubusercontent.com/27898520/81551251-f1d90600-939a-11ea-9d83-d6accdd1729c.jpg)

@MilenkoTunjic need a hand here
