### ISSUE TITLE
Sort tabs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16167]
![image](https://user-images.githubusercontent.com/3536496/81219290-74755600-8f94-11ea-8604-2cb7ff3e532d.png)
Driving me bonkers.

**Comment by gzatravkin** [comment]
Added sorting based on tab name
![image](https://user-images.githubusercontent.com/53317567/81285480-fa95a900-9035-11ea-91b9-1caea78fd236.png)
