### ISSUE TITLE
Change "is on" toggle with sprite

### ISSUE THREAD

**Issue by serpopov** [StrangeLoopGames/EcoIssues#16169]
![image](https://user-images.githubusercontent.com/4238643/81220816-23a14400-900c-11ea-926f-7eb5bab1b2f7.png)

this looks out of place, could we replace it with nice light switch sprite?
example:
![image](https://user-images.githubusercontent.com/4238643/81220861-3582e700-900c-11ea-9fa3-ca8537cc4540.png)

**Comment by FalkosTMB** [comment]
Please build a switsh in every table.

**Comment by MilenkoTunjic** [comment]
Added new sprite for on/off toggle.
Checked in in UI_Elements_02 sprite sheet.
![UI_Elements_0224_06@0.jpg](https://images.zenhubusercontent.com/5edf28cbb0dce5fc774483ff/2384638f-0bf3-4e7c-bc32-9331c9bb7489)
