### ISSUE TITLE
NullReferenceException on Eco shutdown in Player

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#16178]
NullReferenceException: Object reference not set to an instance of an object
UI.BaseUI.OnDestroy () (at Assets/UI/Scripts/BaseUI.cs:93)

![image](https://user-images.githubusercontent.com/475445/81275073-d4820000-9059-11ea-9fd8-38d098aba0e4.png)

**Comment by johnkslg** [comment]
High priority is for blocking issues
