### ISSUE TITLE
[5.6 b89cd513] Client Crash 

### ISSUE THREAD

**Issue by Nohau** [StrangeLoopGames/EcoIssues#1617]
Client Crash when connecting to private lan server. 

Server Same version
OS Windows 10
Issue : Connecting to Server and then get spawn screen to customize avatar then crash's

Including Crash Reports
[2017-06-08_003720.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1060053/2017-06-08_003720.zip)

[2017-06-08_003630.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1060052/2017-06-08_003630.zip)

[2017-06-08_004328.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1060054/2017-06-08_004328.zip)

**Comment by Nohau** [comment]
One thing to note is we where testing a large world dimensions 250x250 perhaps large assets cause issue?

**Comment by Nohau** [comment]
Smaller world 150x150 shows this issue doesn't occur so far.

**Comment by pamduncan** [comment]
We have found in testing that a world larger than 200X200 (4X world) seem very unstable and have crashing problems - this was even true in previous alpha's and may still be an issue in 5.6

**Comment by Nohau** [comment]
Yea doing some research shows this may be a engine problem with unity perhaps with large asset downloads.

**Comment by metachronism** [comment]
closing as hopefully unity 2017 upgrade saves us
