### ISSUE TITLE
[0.9.0 staging-1541] Sometimes I can't join to server after connection interrupt

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16175]
Step to reproduce:
- start game. Join to server
- disconnect:
- press continue button and start to interrupt connection (press ESC during connection). After some interruptions I can't join to server

https://drive.google.com/file/d/1bV3qwNyUKtu6sJ2giFGhknI_RG5a2uyg/view?usp=sharing
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4591352/Player.log)
Server log:
[log_200507080805.log](https://github.com/StrangeLoopGames/EcoIssues/files/4591436/log_200507080805.log)

When I first encountered this bug, I had another error in the log. But I can't reproduce it. But before that I checked interrupts too:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4591400/Player-prev.log)

**Comment by johnkslg** [comment]
Can you try to repro this with a clean log? There are so many errors in there I cant tell which is the first.

**Comment by johnkslg** [comment]
I have a suspicion it's related to this: https://github.com/StrangeLoopGames/EcoIssues/issues/16204
I did see a similar error in the log.  May want to wait till that's fixed to try reproing.

**Comment by SlayksWood** [comment]
Seems fixed in staging-1553
