### ISSUE TITLE
Determine pollution scaling properties for various sized worlds

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16171]
Since we dont scale resource requirements for the 'trip to the laser', pollution create by players will thus be similar for similarly sized worlds. 

However, because plants and animals vary in number by world, they will drastically change the impact that pollution has.  Make a system to balance plant and animal co2 input/output based on total populations at spawn.

**Comment by SlayksWood** [comment]
@johnkslg 
Can we push it?

**Comment by WeaselDog** [comment]
Going to call this done for now as we implemented this in 9.0 and have had no issues since. We can re-examine after 9.1 with new pollution sources and reopen if needed.
