### ISSUE TITLE
[0.9.0 staging-1540] Icon for calories reduction benefit

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16174]
from #15636

Also use separate category for Labor benefits: DynamicValueType.LaborEfficiency.
Can you add an icon for this?

**Comment by beastyn** [comment]
Labor Efficiency it is

**Comment by RobertMangano** [comment]
after speaking to mirasrael he decided it was Labor Calories  reduction
![laborcaloriereduction](https://user-images.githubusercontent.com/26705633/81513304-df46d880-936a-11ea-85d0-55ccae6bdb7d.png)

**Comment by RobertMangano** [comment]
icon on icon sheet 04
