### ISSUE TITLE
[0.9.0 Staging-1538] - Basic governance options unavailable until after constitution is ratified

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16182]
Basic governance options like setting up (or at least drafting) custom votes, titles, or similar to use as part of your initial constitution do not appear to be available until after the constitution is ratified.

It seems reasonable to at least be able to adjust the standard vote, or set up a constitution that has a few ministers built in at inception, or things along those lines.

Without the ability to change at least some things, basic election defaults require at least one default vote cycle to set up titles and vote changes democratically, which gives a massive incentive to install a dictator to set things up quickly, and then (hopefully) amend the constitution later - not ideal in all situations.

If the idea is that constitutions will always be imperfect on inception, and require several phases of amendments and risks to get even a basic government set up, then this is working as intended. If the idea is that you should be able to set up a cabinet of ministers, or even adjust how long initial votes should take, then this is currently broken.

**Comment by trickenso** [comment]
It would be useful to bundle other things into single 'package' elections, as well - not just the constitution.

Like creating a district and also a law that refers to it, for instance.

**Comment by johnkslg** [comment]
You can now do exactly this! Added to 9.1
