### ISSUE TITLE
Data and Graph sections improvement

### ISSUE THREAD

**Issue by MarkZaytsev** [StrangeLoopGames/EcoIssues#16185]
These issues requires API and web changes altogether.

- [x] Add sub-categories for all the player actions, same as the dropdowns in game.  Use the LocCategory tag, which is used in game.

- [ ] Revive the FrontPage query and make it better. This query will return a number of graphs that should be displayed by default when the user goes to an Eco server web page.   We can make the graphs that are shown related to the three pillars: economy, ecosystem, and government.  Some ideas for graphs we can have:
- CO2, showing pollution sources and sinks, and effects: sea level and temperature rise
- Economy, showing total transactions in the top 1 or 2 currencies per volume (Ie, GDP, might need to add new stats for tracking this),  workparties completed, and total number of specialties for all users.
- Government, showing number of laws, elected titles, office holders, elections, civic actions performed

**Comment by MarkZaytsev** [comment]
I've changed API to support sub-categories, but now list in the Data section not showing correctly.
I assume issue is on the js side, since response from server looks correct.
![ss (2020-05-07 at 06 32 53)](https://user-images.githubusercontent.com/50739566/81290318-1169e900-9092-11ea-83e1-93d87bb24635.png)
![ss (2020-05-07 at 06 37 28)](https://user-images.githubusercontent.com/50739566/81290322-129b1600-9092-11ea-9b2b-76426047eb9c.png)

**Comment by MarkZaytsev** [comment]
@denysaw Checkout data_graphs_improvements branch.

**Comment by MarkZaytsev** [comment]
I've enabled front page graphs again, but they are not showing. I see the part commented in the `index.html` page related to the front page graphs, but enabling it does not helps. 

![ss (2020-05-07 at 06 44 58)](https://user-images.githubusercontent.com/50739566/81290795-e0d67f00-9092-11ea-84c6-ade63beec9b7.png)

**Comment by gzatravkin** [comment]
Looks like duplication of https://github.com/StrangeLoopGames/EcoIssues/issues/16396 .
Everything but 
" Revive the FrontPage query and make it better. This query will return a number of graphs that should be displayed by default when the user goes to an Eco server web page. We can make the graphs that are shown related to the three pillars: economy, ecosystem, and government. Some ideas for graphs we can have:"
is done, and this part is covered by https://github.com/StrangeLoopGames/EcoIssues/issues/16396
