### ISSUE TITLE
[0.9.0 Staging-1538] Changing constitution and re-ratifying does not update it in Capitol

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16181]
A constitution was proposed but didn't pass. I changed some things and proposed it again, but some parts of it look the same in the capitol. Voting in the web page looks correct.

![image](https://user-images.githubusercontent.com/982322/81281445-2460c700-905a-11ea-91fe-3aa0cec31528.png)

![image](https://user-images.githubusercontent.com/982322/81281508-38a4c400-905a-11ea-949f-2e1305ef9450.png)

**Comment by henrikolsson** [comment]
Seems to be a caching issue. Logging in and out fixed it

**Comment by johnkslg** [comment]
Could not repro this; put a constitution to election, failed it, then modified to add JohnK to executors on laws, and it showed up fine in both webpage and game:
![image](https://user-images.githubusercontent.com/3536496/82160954-bed8bb80-984d-11ea-9b6d-fceb5a3b86fd.png)
![image](https://user-images.githubusercontent.com/3536496/82160960-c5673300-984d-11ea-8eeb-036ca16769ee.png)
@beastyn can you see about working with @henrikolsson to get a solid repro case?

**Comment by trickenso** [comment]
If I recall correctly, the specific case was replacing Xao with octe as the executor in each case, rather than adding a new executor - perhaps this is the defining element?
Not managed to get this theory tested in single player, though...

**Comment by johnkslg** [comment]
Ah I was able to get that problem, thanks

**Comment by johnkslg** [comment]
Fixed! Nice find.
