### ISSUE TITLE
[0.9.0 Staging-1538] - Minor tooltip tweak - Capitols show unnecessary currency information.

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16189]
"Credit Data" is shown on the tooltip for Capitol, which doesn't seem to be particularly relevant, and adds clutter:

![image](https://user-images.githubusercontent.com/48172405/81288116-e5cc0c00-905b-11ea-90ab-eac11008d202.png)

I might be missing some usefulness for this, but I couldn't find one by looking around.

**Comment by SlayksWood** [comment]
It's intended behavior. Capitol has crafting component so it can be a public craft station, so it show persistent data like for other crafted table.

**Comment by trickenso** [comment]
Understood - thanks for clarifying.
