### ISSUE TITLE
 [0.9.0 Staging-1542] Invalid election does not show as being invalid in Web UI

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16199]
An active invalid election does not show as invalid in the Web UI.

![image](https://user-images.githubusercontent.com/982322/81326187-bfc55c80-9099-11ea-9654-503a771c3648.png)

![image](https://user-images.githubusercontent.com/982322/81326217-c9e75b00-9099-11ea-80e6-4b74d7be4f1a.png)

**Comment by beastyn** [comment]
@johnkslg 
Don't we need to remove an election completely if a Title was removed?

For repro:
1) Create a title
2) Start the election for the title
3) Remove a Title.
I threr a reason for election to be in invslid state? Can't imagine one as we don't have particular election as a parameter value.

**Comment by johnkslg** [comment]
@olegshegai seems reasonable to make elections insta-fail when they go invalid

**Comment by SlayksWood** [comment]
Fixed deleting invalid election, but still has problem in Web UI. Will be fixed in #16255
