### ISSUE TITLE
[0.9.0 Staging-1538] - A couple of typos

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16190]
...vote to ratify this ~~consitution~~ constitution

![image](https://user-images.githubusercontent.com/48172405/81297853-d2c13800-906b-11ea-961c-4b1f712e5342.png)

You have no ~~priviliges~~ privileges...

![image](https://user-images.githubusercontent.com/48172405/81297982-08662100-906c-11ea-8136-96a6304c2be2.png)

**Comment by trickenso** [comment]
Has government banking ~~priviliges~~ privileges.

![image](https://user-images.githubusercontent.com/48172405/81299047-8ecf3280-906d-11ea-98cc-72336544e6fa.png)

**Comment by trickenso** [comment]
Majority required ~~to instance win~~ for instant win

or perhaps:

Majority required to resolve instantly.

![image](https://user-images.githubusercontent.com/48172405/81299983-fd60c000-906e-11ea-9ca1-2450e98a1a17.png)

**Comment by SlayksWood** [comment]
Still 1 typo not fixed:
![image](https://user-images.githubusercontent.com/45708377/81662663-919f9e00-9446-11ea-9d8a-5c207129bd06.png)
