### ISSUE TITLE
[0.9.0 Staging-1538] - Modules tag doesn't contain modules

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16191]
I'm unsure what this tag is intended for, but I was trying to look up a list of modules and got these miscellaneous crafting tables instead:

![image](https://user-images.githubusercontent.com/48172405/81302971-005daf80-9073-11ea-91c8-fc2cbc4c9715.png)

I was expecting a tag with all the various upgrade modules in it.

**Comment by Sekor2600** [comment]
is fixed in current Staging Version
