### ISSUE TITLE
Creating Contract for Depot causes exception and throws user out of server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1619]
Placed depot and attempted contract to build a room and it caused and exception which threw off of server

https://www.dropbox.com/s/ttx7s35x15pp0k7/ClientNetworkException%2006081438.ecodmp?dl=0

**Comment by MarjieAVolk** [comment]
This should be fixed by my recent round of contract fixes (https://github.com/StrangeLoopGames/Eco/pull/1532)
