### ISSUE TITLE
[0.9.0 Staging-1538] - Cannot name districts/maps the same name as deleted ones

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16193]
Expected behaviour: After deleting an element, I should be able to create another with the same name, even if this means the deleted map is renamed to distinguish it from the live version.

Actual behaviour: Error shows indicating the name is already in use, when it isn't - the element with the same name has been deleted.

**Comment by trickenso** [comment]
Somewhat related to #16023

**Comment by SlayksWood** [comment]
merged to #16023
