### ISSUE TITLE
[0.9.0 Staging-1538] - District painting brush remains on map as a visual artefact.

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16194]
Steps to reproduce: Open a district map. Select a large brush size. Move the mouse rapidly off the map area. The brush will remain as a ghost. Selecting a smaller brush size and moving back onto the map will cause this ghost to remain until a district is painted over it.

Expected behaviour: the brush would not remain on the map. Actual behaviour: it does, like so -

![image](https://user-images.githubusercontent.com/48172405/81306200-1d947d00-9077-11ea-81bc-0cdcc601c771.png)

**Comment by SlayksWood** [comment]
@trickenso Can you provide video? I can't reproduce it.
And please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by trickenso** [comment]
This is what I did:
![District Brush](https://user-images.githubusercontent.com/48172405/81390104-d22fac80-9112-11ea-8300-345b5d5f64af.gif)

Logs:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4598028/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4598029/Player-prev.log)

**Comment by beastyn** [comment]
@trickenso thank you for the detailed report.
