### ISSUE TITLE
Suggestion: Add keys to lock/unlock doors with

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1620]
Original post: http://ecoforum.strangeloopgames.com/topic/2469/possible-keys-for-doors/

Adding keys to the game would allow you to rent out/sell houses a lot easier, it would let you divide the authorization for an area in a much more effective way, and it would also be a lot more realistic than going into the UI and clicking 'Lock'.

**Comment by pamduncan** [comment]
For me this would help in my situation where I have some people I want to have access to my house but not to all things inside it.  So I could give them a key to get it - but others could not get in.  Then  they can use the things I leave unlocked for them but not have access to everything.  Right now I can grant access through the deed but once I do then they have access to everything and I don't want that or having to have multiple deeds for different rooms of the house and having to manage authorization on multiple deeds or place items in rooms according to who I want to authorize on a room.

**Comment by KyeEco** [comment]
Maybe adding key rings to save space with keys, have skills like, secure door lock skill key skill, added to tool smithing? maybe even as a side thing to go with it all like a realestate so you can use keys to rent rooms and rent deeds for propertys? even sell propertys through the realestate? just a few ideas

**Comment by REPOSEECO** [comment]
Don't forget the big Vehicles you need Keys to drive.

**Comment by johnkslg** [comment]
We revamped the permissions system, should be able to have finer control as requested without keys.
