### ISSUE TITLE
[0.9.0 staging-1543] Missing strings in CO2 emission from crafted table.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16208]
I can't see this strings in Blast, Oil refenery. I started project and waited more than 5 minutes:
![image](https://user-images.githubusercontent.com/45708377/81384289-1d998900-911a-11ea-88c9-4ab5c1c51db0.png)
should be:
![81242859-12801500-8fc3-11ea-9cae-ca0baddba4fc](https://user-images.githubusercontent.com/45708377/81384406-4caffa80-911a-11ea-81b3-e57253661bb1.png)

**Comment by johnkslg** [comment]
Fixed!
Also use updated /spawn blastfurnace command to test this easily.
