### ISSUE TITLE
Election Priorities are weird

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16200]
I voted

Person A: 1
Person B: 2
Person C: 3
Person D: 4

It says i voted for Person D, but i expected to vote for Person A.
In runoff the lowest number is my main vote, not the highest. I sort them in order from 1 to X.

**Comment by D3nnis3n** [comment]
Seems to be a bug, you cannot do runoff voting, you need to only vote for one person for it to work.
No matter what entries you set, you vote for some random person then.

**Comment by johnkslg** [comment]
Where are you seeing who it says you voted for?
I cant repro this. Attach screenshots?

**Comment by D3nnis3n** [comment]
When you vote on the website, it shows who you voted for in the game chat, same for when other people vote. It only works reliably if i only choose one person. If i vote for four persons, it shows i voted for a person i did not select as first priority and the person that is shown becomes first priority on the webpage despite i did vote her for example with priority 3. I try to get some screenshots together.

**Comment by johnkslg** [comment]
I found some bugs, related to this web issue: https://github.com/StrangeLoopGames/EcoIssues/issues/16314

Will double check this when that's fixed.

**Comment by D3nnis3n** [comment]
That seems to be the issue i experienced, yes - hence the person it says i voted for is different to my number one priority. Good job!

**Comment by johnkslg** [comment]
Closing then as #16314 should cover this. Thanks!
