### ISSUE TITLE
Top links at https://www.play.eco/ still old

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16216]
![изображение](https://user-images.githubusercontent.com/4980243/81453525-67be5100-9192-11ea-9f04-1e64ecd00b49.png)

e.g.
http://ecoforum.strangeloopgames.com/ instead of https://forum.play.eco/
https://eco.gamepedia.com instead of https://wiki.play.eco
https://accounts.strangeloopgames.com/login instead of https://accounts.play.eco/login
https://accounts.strangeloopgames.com/home instead of https://accounts.play.eco/home

**Comment by j3fffff** [comment]
will be updated when new site is released
