### ISSUE TITLE
Microphone doesn't work

### ISSUE THREAD

**Issue by Djon8108** [StrangeLoopGames/EcoIssues#16211]
Не работает микрофон.В Виндовс микрофон настроен и работает нормально  в разных голосовых прогах тоже всё работает нормально меня хорошо слышно а вот в ECO все ползкнки стоят на максимум так же включал активацию голосом или при нажатие кнопки мен Не слышат люди.
Какк то можно это исправить?

Translate from beastyn for the team:
My microphone doesn't work. In Windows, the microphone is configured and works fine in different voice programs, everything also works fine, I can hear it well, but in ECO all the crawls are at the maximum, it also turned on voice activation or when people press the button, people don’t hear.

**Comment by beastyn** [comment]
Спасибо за обращение.
1) Пожалуйста, приложите к сообщению логи после сессии, где вы пытались говорить через голосовой чат.
Здесь инструкция https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2) Для анализа, предоставьте, пожалуйста, данные о комплектующих вашего компьютера и операционной системе
3) Вы пробовали использовать чат на каких-то определённых серверах?

**Comment by Djon8108** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4599353/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4599520/Player-prev.log)

Windows 10Pro
Процессор : intel(R) Core(TM) i5-4670CPU @ 3.40GHz  
Установленная памяь (ОЗУ): 16.0 ГБ
64-разрядная 
Не пойму как передать полные данные о комплектующих .
Пробовал подключать наушники с микрофон  через них меня слышно  а через штатный не слышно.
Микрофон робочий пробовал в стиме- скайп-Дискорд в разных играх а тут молчит.

**Comment by beastyn** [comment]
Что значит "штатный"?
Можно еще марку оборудования, которое пробовали использовать?

**Comment by Djon8108** [comment]
> Что значит "штатный"?
микрофон который подключен через стандартный вход(3,5мм) на материнской плате.
марку микрофона к сожалению не помню и не микрофоне нет обозначений.
Микрофон типо "Прещепка"
[https://www.guitarman.by/img_base/catalog/item/img/k0fdf7.jpg](url)

**Comment by beastyn** [comment]
Спасибо  за информацию.
Не подключались ли одновременно разные гарнитуры? 
Или второй комплект всегда отключался? В игре нет ручной настройки оборудования, возможно в качестве предпочитаемой выбиралось другое оборудование.

**Comment by Djon8108** [comment]
Всегда было подключено одно устройство .

**Comment by beastyn** [comment]
Возможно игра не определяет некоторые устройства.
На текущий момент есть запрос на вывод устройств в меню аудио настроек #13461.
Сейчас у нас нет возможности решать вопрос по каждому устройству отдельно, надеемся, что появление такой настройки поможет локализовать ошибку.
Спасибо, что обратили внимание на подобную проблему.
