### ISSUE TITLE
[0.9.0 staging-1543] All orders work at the same time on one crafted table

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16212]
Step to reproduce:
- place campfire(or another crafted table) and add 2+ orders with resources:
![image](https://user-images.githubusercontent.com/45708377/81401268-a4109380-9137-11ea-9e43-29c5dae590f5.png)
- add labor to each (or just to first order):
![image](https://user-images.githubusercontent.com/45708377/81401495-1e411800-9138-11ea-8543-6277c07b224d.png)
- all orders work at the same time:
![image](https://user-images.githubusercontent.com/45708377/81401541-331dab80-9138-11ea-93c7-97f897c937bc.png)

**Comment by beastyn** [comment]
Feature!

**Comment by elfl0rd** [comment]
I love it!

**Comment by johnkslg** [comment]
Feature removed. (fixed).
