### ISSUE TITLE
 [0.9.0 staging-1542] Unable to propose something for election when having immediate execution rights

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16217]
Right now when you have immediate execution rights for for example laws you're unable to propose them for a vote, your only option is to immediately apply it. 

Having the permissions should still allow you to propose things for a vote.

**Comment by beastyn** [comment]
Its intended, as you don't need voting proccess in dictator mode.

@johnkslg Is there a way to make two options for the executors?

**Comment by johnkslg** [comment]
If you want to propose it just to be nice?  That never happens in politics :)  
It would be a new feature, lets push it.

**Comment by trickenso** [comment]
> If you want to propose it just to be nice? That never happens in politics :)

Henrik was deliberately trying to be nice, and avoid using his executive privilege. A dictator with absolute power allowing the plebs to imagine they have democratic input is one way of doing things :D

**Comment by WeaselDog** [comment]
Fixed as part of https://github.com/StrangeLoopGames/EcoIssues/issues/17446
