### ISSUE TITLE
Items look like they are craftable even though there are not enough resources

### ISSUE THREAD

**Issue by aiorgovan** [StrangeLoopGames/EcoIssues#16213]
Hello!

I've noticed today, while using the Masonry Table, that if I wanted to craft, let's say, 500 Mortared Stone and I only have resources for 5 of them, the animation of crafting will go for an infinite number of times, without the number updating (decreasing) or even stop when the resources deplete. 
It doesn't occur that often though. 
There were a few temporary solutions I found. First time I replaced the table. The second time I changed the room (as well as the property, from my friend's to mine - I had authorization) and the third time I put some Mortar to be made and switched the crafting order and then it seemed to work. 
For the first two solutions, it bugged again after a while. 

ECO VERSION: 0.8.3.3 
![ecostonegif](https://user-images.githubusercontent.com/48785851/81422338-805f4480-915b-11ea-8729-f21a4bbcf574.gif)

** this is the gyazo link of the same gif, in case it didn't upload: https://gyazo.com/c236d9c6d00cea1bb9daa9657f75f5f2 

Thank you, 
Have a nice day!

**Comment by beastyn** [comment]
Thank you for the report. Should be fine in 9.0, will look closer
