### ISSUE TITLE
[0.9.0 staging-1542] Campfire stops animation when reordering Work Orders

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16219]
To replicate this:
- Start a work order on a Campfire
- Add labor
- Start a second work order. (It doesn't matter if you add labor on the second work order)
- Rearrange the work orders

The animation for the campfire will stop and reordering them back does not resume it.

**Comment by revtje** [comment]
In addition to this I have seen that a craft is sometimes ticking 1 second forward 1 second back if the resources run out. Is this perhaps related? Noticed it is draining the burnable fuel while doing this. If not I can make a new ticket for it

**Comment by olegshegai** [comment]
Already fixed
