### ISSUE TITLE
0.9-1544 "oil mining upgrade"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16223]
(base text issue, NOT localization related)

![изображение](https://user-images.githubusercontent.com/4980243/81467795-c4962780-91e3-11ea-9820-036a49d80d7f.png)
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru#173694

> Modern Upgrade with greatly increased efficiency for oil mining recipes.

**Comment by WeaselDog** [comment]
This was fixed in a previous update. It should be good in staging-1546
