### ISSUE TITLE
 [0.9.0 staging-1542] End election early when this percent has voted does not work properly

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16227]
Created a new election type with a title containing 1 person as "voters" and set "End election early when this percent has voted" to 100%:

![image](https://user-images.githubusercontent.com/982322/81471811-18a90800-91f4-11ea-8b5a-362a39f2af1d.png)

Created election using that type and voted:
![image](https://user-images.githubusercontent.com/982322/81471838-455d1f80-91f4-11ea-94c7-315e73b5baf2.png)

But it's not ending as it should.

**Comment by beastyn** [comment]
Didn't have any problem.
Law (or anything) should pass with civics tick.;
After you have woted wait for ticj to end.
/civics showtick should help.
Please, reopen if issue is still relevant.
![Uploading bandicam 2020-05-11 12-18-40-941.jpg…]()

**Comment by henrikolsson** [comment]
Managed to recreate it again in single player. 

Election process:
![image](https://user-images.githubusercontent.com/982322/81577528-d32e3b80-93a9-11ea-890a-8c28a9204cab.png)

Election:
![image](https://user-images.githubusercontent.com/982322/81577625-f1943700-93a9-11ea-873b-ff39518d5185.png)

Voting done: 
![image](https://user-images.githubusercontent.com/982322/81577786-36b86900-93aa-11ea-9083-72a789fcf0d2.png)

I tried both waiting for a manual tick and doing /civics ticknow:
![image](https://user-images.githubusercontent.com/982322/81577896-5b144580-93aa-11ea-92f1-8b63d262bb31.png)

**Comment by beastyn** [comment]
Yeap, I've repeated it with Elected Title election.
@henrikolsson thank you for the detailed example.

**Comment by johnkslg** [comment]
Election was checking > min percent instead of >= 
Also made results update instantly when a vote is cast.
Fixed.
