### ISSUE TITLE
USER ISSUE: family sharing users cannot join servers

### ISSUE THREAD

**Issue by Juice805** [StrangeLoopGames/EcoIssues#16222]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Have a family member share their steam library
install eco
attempt to join a friends server

**Expected behavior:**
I should be able to join a game

**Actual behavior:**
The following error message popped up

Connection Failed

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up

Connection Failed

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Comment by elfl0rd** [comment]
Yes, as you can see at steam - family sharing is not marked as supported.

**Comment by Juice805** [comment]
ctrl+f on steam for `family` or even `sharing` on the store page comes up with nothing.

**Comment by elfl0rd** [comment]
yes, because family sharing not marked as supported.

https://steamcommunity.com/app/382310/discussions/4/1696043263505397726/

**Comment by Juice805** [comment]
Yes, so there is no indication on the store page. AFAIK there is no explicit marking on steam pages for family sharing so unless it explicitly states it is not supported there is no way to "see at steam" for buyers. 

Also as per that forum thread it sounds more like a developer bug rather than the game being inherently able to support family sharing.

**Comment by trickenso** [comment]
> Can all Steam games be shared with friends and family?
> No, due to technical limitations, some Steam games may be unavailable for sharing. For example, titles that require an additional third-party key, account, or subscription in order to play cannot be shared between accounts.
https://store.steampowered.com/promotion/familysharing

Eco requires a third-party account/key, and therefore cannot be shared between accounts.

**Comment by beastyn** [comment]
@Juice805 thank you for the report.
I will look into a problem with adding additional information about family sharing/
Has this issue here #12797
