### ISSUE TITLE
[0.9.0 staging-1542] FPS fix/bug/weird stuff

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#16225]
Version [0.9.0 staging-1542]

So i log in on the server 37fps,disconnect from the server and log back in and boom 60 fps,without restarting the game client.

My specs: Rx 580 8gb,12 gb of ram oc at 2666,ryzen 5 1400 oc 3.7gh,windows 10 latest updates

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4603038/Player.log)

Deleted all the eco data before the test(local low)

**Comment by beastyn** [comment]
@Xao22 did you have it for a long playtime? Or after some time FPS was around the same?

**Comment by Xao22** [comment]
the boost persists for a while,depends if you travel or not,they are affected by memory leaks

**Comment by Xao22** [comment]
Update: after couple of days of testing the trick fix the fps,if i don't travel it stays at 60 fps for long periods of time until memory leaks kick in so it is an fps fix definitively.The bug started on circle 2 when map was bigger,wasn't there on 1km map,i think is something map size related

**Comment by Xao22** [comment]
On version 1594 trick is no longer needed,and it has 0 impact.fps are as they should.this can be marked as fixed

**Comment by mirasrael** [comment]
Thanks for confirm @Xao22
