### ISSUE TITLE
 [0.9.0 staging-1542] Times displayed when voting in web ui are wrong

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16228]
All elections display the wrong "since" time. Example of election created a few minutes ago:
![image](https://user-images.githubusercontent.com/982322/81471871-881ef780-91f4-11ea-98de-fd989cb8d5e6.png)

**Comment by beastyn** [comment]
@denysaw maybe an issue is in api, tell please
