### ISSUE TITLE
0.9-1544 Feedback of animal attacks

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16231]
No nearby animals. 5 blocks height from ground, BITTEN.

**Comment by Xao22** [comment]
think is a delayed anymation,not sure tho

**Comment by elfl0rd** [comment]
I'm not sure if it's a delayed animation, I spent almost 20 minutes building up pretty high and I kept getting bitten.

**Comment by StanKryvenko** [comment]
Are you sure that this is not a tarantula?

**Comment by elfl0rd** [comment]
tarantula? Eco is not provide feedback whi bite me.
But bite animation without animals is annoying.

**Comment by beastyn** [comment]
Its with animal, Its tarantula.
But will leave it for bite feedback,
Need to find a good place. Maybe with caloris here #13329
And also add message to the top notification (not temporary)

**Comment by SlayksWood** [comment]
Please add loss calories to notification. 'Jaguar attacked you! You lost 25 calories':
![image](https://user-images.githubusercontent.com/45708377/94894532-37a18280-0492-11eb-851d-65b08e47eb5b.png)
