### ISSUE TITLE
I have specialty points but cant spend them 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16238]
![image](https://user-images.githubusercontent.com/3536496/81481298-d7106100-91e3-11ea-957f-7de68d942818.png)

![image](https://user-images.githubusercontent.com/3536496/81481305-e2638c80-91e3-11ea-99de-fa75de730e59.png)

**Comment by beastyn** [comment]
@johnkslg I didn't have such an issue. Something special was done&

**Comment by gzatravkin** [comment]
I wasn't able to reproduce it. There are chances that this is already fixed since there are some change in skill UI in last few days.
