### ISSUE TITLE
Storage component has wrong icon again 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16235]
![image](https://user-images.githubusercontent.com/3536496/81481056-41c09d00-91e2-11ea-94a5-6ba77c4c8f3c.png)

**Comment by beastyn** [comment]
Its not wrong.
@serpopov has said that its intended for storage with power sources.
We kind of disagree )

**Comment by SlayksWood** [comment]
It don't have icon, but should be fixed here #15893
