### ISSUE TITLE
 [0.9.0 Staging-1542] Not possible to chose election type when proposing district maps

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16230]
When proposing district maps there is no option chose which election type to use for it, there is only a submit button.

**Comment by henrikolsson** [comment]
I think I get it now - the election typesare only for titles by design? Would be nice to be able to use custom election types for all kinds of proposals.

**Comment by beastyn** [comment]
Type of the election for the civics objects is defined by the Constitution
But Elected Title has its own election process. 
So, the Constitution has an election process for the election for the Elected Title like object.
And Elected Title has election process in itseld, as you should vote for a person in this Title.

**Comment by henrikolsson** [comment]
Thanks, I understand the thought behind it now. I guess it's more of a feature request then, It would be nice to be able to have different processes for different laws.
