### ISSUE TITLE
Mill meets non existant room requirements

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1624]
![image](https://user-images.githubusercontent.com/3150561/26950271-f201e39c-4c51-11e7-81e2-88cfac9f005a.png)

craig says mills have no room reqs - which, if so, why does this say it meets them?

**Comment by SeanAtr0n** [comment]
mill has:
        public override RoomRequirements RoomRequirements { get { return new RoomRequirements(typeof(LogItem), 0, 0, 0, 0); } }

imo we should delete that and get rid of the room requirements component on the mill

**Comment by metachronism** [comment]
well, mill should probably require a room anyway
