### ISSUE TITLE
Objects never showing in inventory

### ISSUE THREAD

**Issue by kelseytarin** [StrangeLoopGames/EcoIssues#16241]
In a previous game, I would buy fish and while it said I had xx in my inventory, they weren't anywhere. In a new game, I rt click on the butchery skill book and it says it created the scroll, but again it is nowhere in my inventory. I have like 6 invisible scrolls that I can't interact with.

**Comment by elfl0rd** [comment]
B - open backpack.

**Comment by beastyn** [comment]
@kelseytarin thank you for the report
Can you provide a screenshot with an opened backpack when you get something?

**Comment by beastyn** [comment]
Close due no response. Please, write here if you can provide more information.
Thank you.
