### ISSUE TITLE
[0.9.0 Staging-1542] - It is very easy to miss elections, even if you are online

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16244]
This is probably a feature request, but it's currently very easy for elections you have not voted in to be lost in notifications. It's also pretty easy to ignore notifications entirely - especially as they're usually a mess of other people's votes.

Something equivalent to a big flashing red light that indicates that you've not voted would be useful. Even a separate button for outstanding civic duties to perform, rather than grouping them on one button would be a start.

I hope it's clear why this is a problem, and I hope I'm not missing something obvious.

**Comment by beastyn** [comment]
@trickenso Thank you for the ideae, sound reasonable.
@MilenkoTunjic  Can we give some special treatment for imposrtant  start election messages?
They shpould gone if you have voted.

**Comment by gzatravkin** [comment]
Well for must-read notification we have OkBox. How about what?

**Comment by trickenso** [comment]
> Well for must-read notification we have OkBox. How about that?

The criteria for me is to have a clear, persistent indicator that votes are outstanding. Ideally this would be distinct from other notifications like 'someone else voted'.

Even if someone clicks 'ok' in the OkBox there should be something that says 'you still haven't voted in X things yet' somehow, and that cannot be dismissed without voting.

**Comment by gzatravkin** [comment]
duplication of https://github.com/StrangeLoopGames/EcoIssues/issues/16676
