### ISSUE TITLE
[0.9.0 Staging-1542] Adding labor through a work party does not work on crafted tables with fuel supply

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#16248]
It is not possible to add labor to some benches when in a work party. It might be polluting benches only.

A workaround is to give full access to the bench through the authorization tab then add labor. The work party will give rewards.

These are the ones I know of on the top of my head
Works: Research table, masonry table, carpentry table
Does not work: Cast Iron Stove, Blast Furnace

**Version:** [0.9.0 Staging-1542]
**Steps to reproduce:**

1. Start a craft on a cast iron stove or blast furnace
2. Make a work party for the labor
3. Get someone to accept the work party and try to add the labor 

**Expected behavior:** Able to add labor to all benches
**Actual behavior:** Not able to add labor to some benches. Cast Iron Stove & Blast Furnace. Maybe more benches? Maybe pollutant benches only?

**Comment by beastyn** [comment]
Didn't have suck a problem
![bandicam 2020-05-11 13-23-37-041](https://user-images.githubusercontent.com/27898520/81540143-a74f8d80-938a-11ea-9144-20f078fb2547.jpg)

Did a worker have a specialization for laboring?
Like for stove he will ned Advanced Cooking.

**Comment by revtje** [comment]
Can you try Cast Iron Stove or Blast Furance? We haven't tried Stove yet. I had cooking as skill for the cast iron stove work party.

**Comment by trickenso** [comment]
Having this same problem trying to add Oil Drilling labor to a work party in Royal Otter. Trying to get you more details and a screenshot.

**Comment by beastyn** [comment]
Ahh, sorry for delay.

After some investigation, can you help us with some informatio?
1) When you are trying to add labor to the work party, do you have something selected on the toolbar?
If you have/ what is it?
2) If you will have an empty cell on the toolbar will you be able to add labor?

**Comment by beastyn** [comment]
@olegshegai as a result we need to fix:
with shift+rmb we need to add labor.

Now: with shift + rmb its trying to place a selected item from the toolbar to the fuel component.

It shouldn't even work with items with this modification.
