### ISSUE TITLE
Missing Sprite for Slag & Crushed Slag

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16245]
The current icons for Slag & Crushed Slag use sprites from other rocks. They should have a unique sprite as this causes some other issues:

https://github.com/StrangeLoopGames/EcoIssues/issues/16096
https://github.com/StrangeLoopGames/EcoIssues/issues/15652

**Comment by RobertMangano** [comment]
new icons are in, but may need to be edited
