### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by ivan228243** [StrangeLoopGames/EcoIssues#16250]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by D3nnis3n** [comment]
You have to buy Eco to be able to play the game.
