### ISSUE TITLE
[0.9.0 Staging-1542] - Stone Road placement and deconstruction are different actions for law filtering

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16254]
Placing a stone road using a hammer or by hand triggers the "drop or pickup block" action, but hammering it to pick it up triggers "construct or deconstruct". This makes laws confusing to implement without errors.

I would expect picking up and placing the block to trigger the same action - placing stone roads without hammer complicates this a bit as this seems like it might be a "drop or pickup block" action.

One possibility would be to remove the option to place stone road without a hammer, and make all stone road actions into "construct or deconstruct", for clarity - this would bring them in line with asphalt roads.

**Comment by SlayksWood** [comment]
> ![image](https://user-images.githubusercontent.com/47274045/82159629-d6389880-988f-11ea-84c5-d84ec94d7c37.png)
> 
> Hello,
> using attached law is working with the trigger to drop, but pickup trigger is not working.
> Greetings

**Comment by Alteraner** [comment]
![image](https://user-images.githubusercontent.com/47274045/82186959-f39b5000-98eb-11ea-9c5e-3b1716b8694b.png)
Hello, even the deconstruct trigger is not working correctly. Attached law is not triggering the deconstruct of an road.

**Comment by trickenso** [comment]
@Alteraner - This doesn't work because of the filter problem in #16252, which already has a fix.

**Comment by Alteraner** [comment]
Okay, got it. My understanding was, using deconstruct would be a working workaround till the Playtest version will be updated with the fix.

**Comment by trickenso** [comment]
I haven't been able to find a workaround. Tried to say in https://github.com/StrangeLoopGames/EcoIssues/issues/16364#issuecomment-629860905 - "Laws like this aren't currently functional" - sorry I wasn't clear.

**Comment by johnkslg** [comment]
Made roads and ramps specially marked as 'Generates Construct/Deconstruct Action Without Tool Placement'. Now they activate the appropriate action, even though you're placing with hand. 
![image](https://user-images.githubusercontent.com/3536496/82258771-4d614180-990f-11ea-9685-e60607c6cdba.png)

**Comment by beastyn** [comment]
Seems like its breaking logic for an asphalt road. It has forms and can be constructed with hammer and placed with empty hand at the same time. And now placing concrete as an item will trigger construct/deconstruct. 
![bandicam 2020-05-19 13-41-38-023](https://user-images.githubusercontent.com/27898520/82305021-8dd7c280-99d6-11ea-9408-934d10ab677f.jpg)

**Comment by johnkslg** [comment]
Great find.

Fixed:
![image](https://user-images.githubusercontent.com/3536496/82393420-297b2a00-99fb-11ea-93c8-2261cb7f6b83.png)
![image](https://user-images.githubusercontent.com/3536496/82393447-3b5ccd00-99fb-11ea-9d1f-b5f9232211be.png)

Continues to work for stone roads:
![image](https://user-images.githubusercontent.com/3536496/82393494-62b39a00-99fb-11ea-800b-1ee07e84ea52.png)


Have I mentioned how awesome our QA team is?!
