### ISSUE TITLE
[0.9.0 Staging-1542] Craft tables progress when they can't work

### ISSUE THREAD

**Issue by BarikSHL** [StrangeLoopGames/EcoIssues#16258]
How to reproduce:
1) Make the 'table', put it, give fuel and pipe to be 'ok' 
2) Put 1k something craft
3) Give 100% of labor o that task
4) Make the 'table' not able to work. For example - put the pump opposite site, or disable waste pipe or just don't give it fuel (with fuel it's complicated, because you should wait for no fuel at all)
5) wait (overall crafttime is ticking)
6) repair ability of the table to craft
7) Catch the resources.
Video, how to reproduce:
https://drive.google.com/open?id=1YzaL1rnq3AWnRi5lWhXAX3xF-_XhLapA

**Comment by johnkslg** [comment]
Made work orders disable and highlight in red when this happens:
![image](https://user-images.githubusercontent.com/3536496/82105740-b3608580-96d1-11ea-8cf3-90c1859adf02.png)

**Comment by BarikSHL** [comment]
1554: 
with the reverse of pump we have much slower craft with red blinking, but it's still made the craft. So, the step to reproduce are the same. 
The same situation with oil refinery: it's blinking with red, it's slower, than it should be, but it works and craft.
Campfire looks like fixed (stop without fuel).
