### ISSUE TITLE
[0.9.0 Staging-1542] - Web interface law inspection - Unclear who has won an election

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16255]
When a vote is concluded, the web UI doesn't display the result, even after the vote has concluded.

Often this is fairly obvious, but in the case of a 50:50 split of the vote, for example, it's not clear whether this means the motion has passed or failed without checking the laws in game.

**Comment by SlayksWood** [comment]
If election cancelled by deleting elected title it should be any notification in Web UI too #16199

**Comment by denysaw** [comment]
You could re-test it after PR above merged.
