### ISSUE TITLE
[0.9.0 Staging-1542] - Government wages are inflexible and cause clutter

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16251]
Titles calculate and pay their wages hourly, which creates a bunch of notification clutter, and there's no way to manage this other than to turn them off entirely.

An option to be able to monitor these payments without getting notification spam hourly would be preferable. Perhaps through the ability to customise how government wages are paid - time period, etc.

This is edging even further into feature request, but a way to customise the way these wages get paid would be wonderful - the same functionality as the laws system would work just fine. Time online is not the only metric you might want to reward.
An example might be an infrastructure minister who gets paid based on the number of roads placed in a roads district - rewarding work done rather than time online. This could currently be governed by a separate law to pay that title, but then why have the wages function at all?

Having the wages function be more like the law system might avoid the need for an extra law for each title and be more elegant and convenient.

**Comment by SlayksWood** [comment]
@trickenso Server owner can set it in serverui now:
![image](https://user-images.githubusercontent.com/45708377/81641721-58f1cb80-942a-11ea-8a0f-e82f9154d563.png)
@johnkslg Can we increase basic 30 minutes to maybe 6 or 12 hours? to prevent spam.
@trickenso I think if you make a wage for all in different time, there will be even more spam. Also wages spam will be fixed in this issue #15953

**Comment by trickenso** [comment]
Ah - I'm on Royal Otter - didn't know this was an option.
Agreed that all different times could be a source of spam - #15953 also helps, for sure.

My thought was that wages are set in the government buildings, so it seemed reasonable that you might also be able to customise how wages are calculated and how often this is done, like you can with triggered laws.

**Comment by johnkslg** [comment]
Changed to once every six hours.  A lot more work to make it configurable in game so lets just do this.
