### ISSUE TITLE
[0.9.0 Staging-1542] "Construct or Deconstruct" event triggering payment does not cause notification

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16253]
I have a law like this:

![image](https://user-images.githubusercontent.com/982322/81505172-b5030580-92ed-11ea-9be4-181e51bb1307.png)

Constructing/deconstructing to trigger it pays the money, but there is notification for it.

**Comment by johnkslg** [comment]
Happening because the notification was removed from hammer operations:
![image](https://user-images.githubusercontent.com/3536496/81993274-39110200-95fa-11ea-87eb-66e1496d764c.png)


Reverting this, but Grigori can you tell me what this was a fix for?

**Comment by gzatravkin** [comment]
It is fix for this issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/13241

Notifications handels in too places: in TryPerform, and common caller on OnAct: Player.PlayerInteractResult.

So I left only player.PlayerInteractResult notifications
