### ISSUE TITLE
[0.9.0 Staging-1542] - Construct/Deconstruct block filters do not work

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16252]
A construct/deconstruct law with no block filter works as intended.

But adding filter of any kind to a construct/deconstruct command (the below shows a filter containing all block types, although any choice I have tried works the same way) causes the law to fail to prevent actions:

![BlockLaw](https://user-images.githubusercontent.com/48172405/81502806-1e781980-92d8-11ea-8ca9-be51c524eacf.gif)

**Comment by trickenso** [comment]
In case it's useful - I tested this for Pollute Air actions, and the filters worked as intended.

**Comment by johnkslg** [comment]
Fixed! Was a bug affecting block placement actions.
