### ISSUE TITLE
[0.9.0 Staging-1546] Civics: font for editing headers

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16260]
Its pretty hard to read when you are editing a header (font and color too)
![bandicam 2020-05-11 11-30-29-373](https://user-images.githubusercontent.com/27898520/81554558-75e1bc80-93a0-11ea-8ad2-322099f89510.jpg)

**Comment by WeaselDog** [comment]
Assigning myself until we get font ready.

**Comment by beastyn** [comment]
Do not see fixes
1777 has it
![bandicam 2020-09-08 17-27-16-100](https://user-images.githubusercontent.com/27898520/92476578-9f98dc00-f1f8-11ea-8821-840088821a16.jpg)
