### ISSUE TITLE
Can remove other players owned objects

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1626]
I hammer'd seans stove on property I don't have access too, and it removed and gave me the stove

**Comment by metachronism** [comment]
seems like only the owner should be able to remove stuff

**Comment by MarjieAVolk** [comment]
Lol yeah I just noticed this >>

**Comment by MarjieAVolk** [comment]
Might have been caused by the fixing of the plants highlighting red?
