### ISSUE TITLE
skills UI leaves the background fade on permanently after closing the skills UI sometimes

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16263]
![image](https://user-images.githubusercontent.com/14983165/81607900-445df680-938a-11ea-8cab-0a475a5095d2.png)

background fade gets stuck on when you open and close the skills UI quickly

**Comment by keegan-o** [comment]
Update: figured out this happens more with using the hotkeys and less with using the mouse to close the UI-- might actually be specifically a problem with the hotkey to close (z)

**Comment by trickenso** [comment]
It doesn't appear to require closing quickly - always happens to me regardless of time spent in the menu.

Closing the menu with ESC is fine, and closing with mouse is fine - pressing Z will always keep the screen fade.

Other menus appear ok when closing with their hotkey.
