### ISSUE TITLE
[0.9.0 Staging-1542] - Tractor feedback request - Display module status, show inventory

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16269]
When driving steam tractor:

1. Cannot see what is in inventory - unsure if this is intentional, but it's unlike all other active vehicles
2. There is no display of whether the current module is active or not

**Comment by SlayksWood** [comment]
You have animation for harvester and plough. And in future should be something for sower.
In any case it's dup #12398

**Comment by trickenso** [comment]
Ah - thanks for the dupe. I searched, but didn't find it.
