### ISSUE TITLE
Low FPS issues in Fullscreen, fine in Windowed

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16262]
> I was asked by SLG-Dennis in the Steam-Forums to write this E-Mail to
> you, regarding performance issues while in Fullscreen Mode on Windows,
> while Windowed-Mode works fine.
> 
> # Symptoms:
> 
> While in Fullscreen, I have low FPS and neither my Graphicscard nor my
> CPU seem to working to capacity. If I switch to Borderless Mode,
> however, I gain 'normal' FPS, 60 in main menu or about 40-55 in-game,
> that is.
> Beside this slower FPS rate, I also experience some sort of stutters;
> hard to explain: it's somewhat like a roller coaster, which is
> constantly going up and down and while on the peak of every hill, it
> gains speed, while being on the bottom it loses speed.
> In Main-Menu for instance, the continuous and consistent camera panning
> is sometimes slower, sometimes faster, like this 'coller coaster'. Each
> 'peak' is about every 1 to 1.5 seconds, I suppose.
> I may record a Video and upload it to youtube, if requested.
> 
> I'd also like to mention, that I have no such trouble under ArchLinux in
> Fullscreen using i3wm as Window-Manager with about the same graphics
> settings here. The game works fine here, but with an overall a bit
> slower performance, but that is another problem, I suppose.
> 
> 
> # My PC-Specs:
> 
> CPU: Intel i7 4790k
> Graphics: 4GB MSI GeForce GTX 970 Gaming 4G
> Mainboard: Gigabyte GA-Z97X-Gaming 5
> RAM: 16GB (2x 8192MB) G.Skill Ares DDR3-1600 DIMM CL9-9-9-24 Dual Kit
> Storage: 4000GB WD Black WD4003FZEX
> 
> 
> # Player.log
> 
> I attached the Player.log to this E-Mail and I also uploaded it to
> pastebin:
> 
> https://pastebin.com/JvZe1rRm
> 
> 
> # Graphics Settings
> 
> 1920x1080@60Hz
> 
> Shadow Quality: Fastest
> Foliage Quality: 60%
> Render Scale: 100%
> Brightness: 100%
> Field of View: 60
> View Distance: 150
> Minimap Detail: Lowest
> Interface Scale: 70%
> 
> [ ] VSync
> [X] Target FPS: 60
> Antialiasing: Off
> Global Illumination: Off
> [X] Ambient Occlusion
> [ ] Fog
> [X] Show Interact Cursor
> [ ] Underwater Distortion
> [ ] Bloom
> [X] Reflections
> [ ] Sunshafts
> [X] Volumetric Fog
> 
> 
> 
> If I missed something or if you need further information regarding my
> system or anything else, I'd be happy to provide them.
> 
> In advance, thank you for your time!
> 
> 
> Regards,

**Comment by hringriin** [comment]
Thanks! Next time, I will open the ticket myself :-)

**Comment by mirasrael** [comment]
Can you provide update on this problem for latest released version?

**Comment by hringriin** [comment]
Hi - it's fine, thanks!

Alexander Bondarev wrote on ‖ 2021-05-28 | 05:40:30 ‖ something like this:

**Comment by WeaselDog** [comment]
Glad to hear it! Thanks for your contribution
