### ISSUE TITLE
[0.9.0 staging-1547] Objects appear with big delay.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16266]
https://drive.google.com/file/d/1cCnawDpuaKmw9PhlGn3enSKrcfFbvH5Q/view?usp=sharing

**Comment by beastyn** [comment]
https://drive.google.com/file/d/1qQoLIMmoquVtw71ZiEAaEev2GlLSX1UJ/view?usp=sharing
https://drive.google.com/file/d/1sZNLknHL2LjM_nWZmyeFU9WDqBPUeHKm/view?usp=sharing

**Comment by johnkslg** [comment]
Was due to update optimizations not sending new items right away. I've changed this to make it send new objects immediately.  Give it a test to make sure all is working, seems good from my tests.

**Comment by mirasrael** [comment]
What about animal updates, physic updates, world object state updates etc?
