### ISSUE TITLE
[0.9.0 Staging-1542] - Steam Tractor inventory drag problem

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16268]
Dragging to inventory background does not work for steam tractor like it does for other inventories:

![Tractor](https://user-images.githubusercontent.com/48172405/81664952-fef80280-9437-11ea-9240-c3edca2edf19.gif)

**Comment by SlayksWood** [comment]
Can't reproduce it. Seems it's fixed in staging-1547 with https://github.com/StrangeLoopGames/Eco/pull/6066
