### ISSUE TITLE
[0.9.0 Staging-1542] - Scythe/Sickle naming convention

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16275]
It is unclear why they are all sickles except the modern scythe. None of the other tools have different names for the different tiers.

If it's tied to the new aoe effect, then steel sickle might make more sense renamed steel scythe.
If it's supposed to be consistent, then naming them all 'scythe' might make the most sense.

**Comment by SlayksWood** [comment]
It's intented bahavior
no AOE, small AOE - sickle
big AOE - scythe

**Comment by trickenso** [comment]
My main concern with this is that it's not immediately obvious the modern version will have a different title. Someone typing the name into chat to find crafting requirements wouldn't necessarily expect it to be named differently to the other tools of the same type.

**Comment by keegan-o** [comment]
It's not a problem-- the chainsaw not being 'modern axe' is fine, and the scythe not being 'modern sickle' is fine. Yes, scythes are more similar to sickles than chainsaws to axes, but they are different, and I'm fine with the line being drawn between them-- since after all, that is accurate, and how they'd be referred to irl.

**Comment by keegan-o** [comment]
In short, the sickle is a sickle https://en.wikipedia.org/wiki/Sickle
And the scythe is a scythe https://en.wikipedia.org/wiki/Scythe

Just like sickles and scythes irl, they are used for more or less the same thing at slightly different scales. Just like axes and chainsaws :)

**Comment by trickenso** [comment]
Foxed by the similar icons and models. Got it - makes sense.
