### ISSUE TITLE
[0.9.0 Staging-1542] - Law Triggers Errors

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16277]
I've been posting a few isolated tickets about law triggers, so I went through the whole list and did some basic checks:

- [x] 1. Query Action
The description reads 'An action that can happen in Eco' - it is not clear what this does, and the description does not help. It has no tooltip for further information. It can apparently apply to any object in the game, but a law preventing query action doesn't appear to do anything.

- [x] 2. Chat Sent
With Tag' is unclear what it does and has no tooltip to explain. 'Tag' is described in the 'Chat Sent' tooltip as 'The tag applied to the chat', but this is not obvious what this means. Is this a reference to HTML markup? Some clearer description text might help here.

- [x] 3. Start Election
#16257 

- [x] 4. Construct/Deconstruct
"With Item Used" includes blocks that cannot be constructed or deconstructed - rubble blocks and barrels, for instance. (Edit - still present in Staging 1602)

- [x] 5. Dig Or Mine
"With Item Used" includes blocks that cannot be dug or mined including wood logs, ashlar blocks, and so on.
"With Tool Used" is missing Excavator.

- [ ] 6. Drop Or Pickup Block
"With Item Used" has the same confusion as 4 and 5 - Pipes have the commands 'Pick up' and 'Place' but may not be picked up without using a hammer, which seems more like construction and deconstruction might be more appropriate. With 'Drop Or Pickup' prevented by law, a pipe may be deconstructed with a hammer, but not placed with a hammer or by hand - this gets quite confusing to keep track of with multiple block types that can have different actions for adding and removing them from the world. I have not tested them all individually.
Similar to #16254

- [ ] 7. Place Or Pick Up Object
It is not clear what "With World Object Item" means and how it is distinct from "With Item Picked Up Or Placed", and there is no description or tooltip to help.
"With World Object" contains items that cannot be picked up or placed, like acorn, for example.

- [ ] 8. Plow Field
"With Item Used" seems redundant, since only dirt blocks may be tilled. It also contains non-terrain blocks. Maybe you want this for modding, in case other blocks might be tilled? For vanilla, it makes sense to maybe hide this option.

- [x] 9. Tamp Road
Again "With Item Used" contains blocks that cannot be tamped. Since dirt blocks are the only ones that can be tamped, maybe hide this, or is it a planned feature for other roads to use the 'tamp' action? Perhaps I'm missing something here.

- [ ] 10. Add Labor To Work Order
"With Labor Profession" and "With Labor Skill" contain the same list.

- [x] 11. Add Item To Work Order
"With Ingredient Added" contains some items that are not ingredients, like Cast Iron Stove.

- [ ] 12. Create Currency
"With Item Used" contains items that cannot be used to create a currency, like Tailings.

- [ ] 13. Mint Currency
Same as 12

- [x] 14. Open Action
"With World Object Item" contains items that cannot be opened, like acorn, for example.

- [ ] 15. Plant Seeds
"On Tool Used" contains the steam tractor sower module but doesn't have an option for 'no tool' or 'hands'.
"With Species" contains Clam and Urchin, which have no seeds and cannot be planted.

- [x] 16. Harvest or Hunt
#16274

- [ ] 17. Gain Profession
"With Profession" and "With Specialty" contain the same filter items - "With Profession" contains specialities.

- [ ] 18. Gain Specialty
As 17

- [ ] 19. Specialty Level Up
As 16 and 17

General points:

1. Location - every time this parameter appears, it has the description "The position of The citizen when they sent the chat.". This does not generally apply to a chat trigger, so might be better if it read something like "The position of the citizen when they performed the action."

2. The categories in the trigger dropdown default to all being expanded. For ease of navigation, it might be easier if they defaulted to all collapsed, or perhaps remembered the way they were left.

3. With the option 'With Tool Used' - there is often the possibility of performing the action with no tool. Is there value in adding 'no tool' or 'Hands' as an option in this list when appropriate?

4. 'Pickup' and 'Pick up' are used interchangeably. The second one is correct English and more consistent with the participle 'Picked up', but either is fine - consistency would be preferable, as currently both are in use.

5. 'speciality' and 'specialism' are both used.

**Comment by tuha263** [comment]
[] 6. Drop and pick up
[] 7. Place Or Pick Up Object

**Comment by tuha263** [comment]
I separate 2 issues left to https://github.com/StrangeLoopGames/EcoIssues/issues/19757 and move it to triagle
