### ISSUE TITLE
Can't place log roof on lumber/stone blocks

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1627]
![image](https://user-images.githubusercontent.com/3150561/26951060-b5505c78-4c54-11e7-880a-6825f5f286dc.png)

I'm clearly targeting above, but the target always gets placed to the side

**Comment by metachronism** [comment]
might be a cursor issue, as the placed block appears where you would think but not where the ghost shows

**Comment by SeanAtr0n** [comment]
i've seen something like this before but am having difficulty reproducing it reliably

**Comment by metachronism** [comment]
have not been able to repro this, going to close for now as a fluke...
