### ISSUE TITLE
[0.9.0 Staging-1542] - Law filter error - Harvest or Hunt - "With Harvested Stacks" does nothing, "with tool used" list incomplete

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16274]
1. 'With Harvested Stacks' dropdown is non-responsive, and there is no tooltip. It is unclear what this is intended to do, and appears to do nothing.

2. "With Tool Used" list misses 'Stone Sickle', 'Iron Sickle', 'Steel Sickle'. Also there doesn't appear to be a different law for destroying plants, so should this list include 'Stone Machete', 'Iron Machete', 'Steel Machete', 'Modern Machete'?

![image](https://user-images.githubusercontent.com/48172405/81687577-02e44e80-9451-11ea-8c18-76cb0f445d13.png)

**Comment by trickenso** [comment]
Note: the "With Tool Used" filter should also include Wooden Bow, Recurve Bow and Modern Bow.

**Comment by johnkslg** [comment]
Need to extend the harvesting tag to those objects.
