### ISSUE TITLE
[0.9.0 staging-1547] Available number doesn't update if you link/unlink storage.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16273]
Step to reproduce:
- place crafted table(Campfire):
- place storage and add some resources for craft in it, storage should be unlinked:
![image](https://user-images.githubusercontent.com/45708377/81687648-d08f1d00-9461-11ea-863b-388f1b15efad.png)
![image](https://user-images.githubusercontent.com/45708377/81687857-eef51880-9461-11ea-9e38-738bc4a06c36.png)
- link storage to campfire:
![image](https://user-images.githubusercontent.com/45708377/81687916-f9171700-9461-11ea-86e0-1056cfac5c91.png)
- UI doesn't upgrade:
![image](https://user-images.githubusercontent.com/45708377/81687983-0207e880-9462-11ea-9ac6-6db6328f28a8.png)
- change counts, UI will update:
![image](https://user-images.githubusercontent.com/45708377/81688257-282d8880-9462-11ea-9b79-ead4cd18f7a1.png)

**Comment by johnkslg** [comment]
@gzatravkin when link occurs, it should be calling the same rebuild that gets called when inventories change.
