### ISSUE TITLE
Glass - additional form

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16271]
As I think, glass should be changed.

Current "window" form rename to "wall" (without model changes)
And add new form as "Window" with frame, like cube
![изображение](https://user-images.githubusercontent.com/4980243/81670467-56a26800-9450-11ea-8bd1-eb87b452c097.png)

**Comment by trickenso** [comment]
Alternatively, remove 'window' entirely. It's possibly a bit redundant. How is a glass window different from a glass wall?

**Comment by elfl0rd** [comment]
> How is a glass window different from a glass wall?

Glass window - glass panel with wood frame, like cube.
Glass wall - just glass panel.

**Comment by SlayksWood** [comment]
merged to #13191
