### ISSUE TITLE
Stats not restoring

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16282]
Per our discussion, the log files are being deleted on load because they cause crashes, need to make these resolve.

**Comment by mirasrael** [comment]
@johnkslg Is it still actual after https://github.com/StrangeLoopGames/EcoIssues/issues/16264 ? They should only have log file when in desync state now. So it should be preferred to remove it (like it works now).

**Comment by johnkslg** [comment]
Havent seen it crash, closing 👍
