### ISSUE TITLE
Tooltips on world markers stopped working 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16283]
![image](https://user-images.githubusercontent.com/3536496/81737030-556f3c00-944c-11ea-8816-be394d8ee9a5.png)
Happened probably because they were made clickable, they need to be both. Also be sure to test other functionality continues to work when new functionality is added/fixed.

**Comment by SlayksWood** [comment]
it doesn't work only for "Forage for food" tutorial markers. It's here #15619
