### ISSUE TITLE
 [0.9.0 Staging-1542] Not possible to reclaim ownership of deed owned by removed title

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16286]
I can't think of any way to change ownership of a deed that is currently owned by a removed title. Executive action and laws can only target currently valid titles.

Since editing a title removes the old one and creates a new one this does not seem too unlikely to happen.

**Comment by SlayksWood** [comment]
Seems need to delete claims if you delete title:
![image](https://user-images.githubusercontent.com/45708377/81788530-52875080-950b-11ea-8948-74d1a77e5721.png)

**Comment by trickenso** [comment]
This brings back the problem from 8.3 of land claims disappearing.

Is it worth reverting the deed or the land claim papers to the player who deleted the title?

**Comment by henrikolsson** [comment]
Just to clarify - since there is no owner with a removed title, it is not possible to delete it.

**Comment by henrikolsson** [comment]
The biggest issue is that editing a title creates a new one and deletes the old one. In that case I think the game should transfer the ownership of deeds, bank accounts, etc, to the new title instead of leaving them dangling.

**Comment by johnkslg** [comment]
It is supposed to transfer ALWAYS when changing something. If that doesnt happen, thats the bug.

**Comment by johnkslg** [comment]
Fixed the first part of this bug: when updating an alias or other entity, all references will be updated and the results displayed:
![image](https://user-images.githubusercontent.com/3536496/82494515-91cf1780-9a9e-11ea-9823-9574815b0f79.png)
![image](https://user-images.githubusercontent.com/3536496/82494532-9a275280-9a9e-11ea-9883-4d33d6f56909.png)

This should fix the most common cause of the bug. Next I'll make deleted titles clean up any references.

**Comment by johnkslg** [comment]
Second part done, if you do remove a title that owns something, it will revert it to everyone and send a notice.
![image](https://user-images.githubusercontent.com/3536496/82500505-56394b00-9aa8-11ea-9241-cb9e68927209.png)
![image](https://user-images.githubusercontent.com/3536496/82500521-5d605900-9aa8-11ea-9cba-d18965c14c40.png)
