### ISSUE TITLE
Tree: Scale tree for comments

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16281]
- [x] Jeff: Make portraits more prominent, at top of feature group. Current:
![image](https://user-images.githubusercontent.com/3536496/81729247-847fb080-9440-11ea-8b6b-2980a52b59d8.png)

Proposed:
![image](https://user-images.githubusercontent.com/3536496/81729778-64042600-9441-11ea-9ae9-933aeea1b574.png)

![image](https://user-images.githubusercontent.com/3536496/81729820-78482300-9441-11ea-930e-f99f954aab37.png)
- [x] Jeff: Popup tooltip is going off the edge of screen

![image](https://user-images.githubusercontent.com/3536496/81729846-85651200-9441-11ea-9721-f9abcada53cc.png)
- [x] Denys, When highlighting, display all devs in highlighted areas.  They persist even after highlighting turns off.

![image](https://user-images.githubusercontent.com/3536496/81729994-be04eb80-9441-11ea-8f5a-6aef0377f920.png)
- [x] Jeff: Give these a transparent background instead of white, perhaps. Or maybe a alphaed dark background. Currently looks like there should be white nodes. 

![image](https://user-images.githubusercontent.com/3536496/81730079-dd037d80-9441-11ea-8521-6feaa34bbc54.png)
- [x] Jeff: Clicking 'Join the discussion' takes you here, which is an empty meaningless page.  I was hoping it would show a page of the various comments that are in the different pages, grouped by category. Can you make this better and a true link to the 'discussion'?    

![image](https://user-images.githubusercontent.com/3536496/81730224-0b815880-9442-11ea-8349-405ba2853f59.png)
- [x] Jeff: Can you make this review a pull quote, and change '2018' to 'game of the year' to remove the datedness of it

**Comment by elfl0rd** [comment]
https://victorzhou.com/blog/replacing-disqus/

**Comment by rainfarmer** [comment]
Denys: can you have the dev icons display all working devs under the main feature
and when they click on sub-features, display just the devs working on that feature

**Comment by rainfarmer** [comment]
> https://victorzhou.com/blog/replacing-disqus/

looks cool. but i think its missing a main feature we want. which is a consolidation of all our comments into one area. disqus offers that.

**Comment by rainfarmer** [comment]
@denysaw found another bug, comments are being cut off. iframe has a height limit. looks like we need some sort of dynamic solution..

**Comment by rainfarmer** [comment]
- [ ] clicking on dev to open the sidebar content they are working on is no longer working

**Comment by denysaw** [comment]
- [ ] Show all subfeatures devs after feature introduction

**Comment by denysaw** [comment]
Finished my part.

**Comment by rainfarmer** [comment]
@denysaw still see the comments cut of bug. check out Laws comments
![image](https://user-images.githubusercontent.com/7343272/83440117-3d5e5d00-a3f9-11ea-942e-6242e92f56fa.png)

**Comment by rainfarmer** [comment]
@johnkslg were missing descriptions for Chunks, memory, server features

**Comment by denysaw** [comment]
`Refresh page, click on dev icon on tree. sends you to top of page and doesnt open sidebar.`

Worx for me in both browsers on developland. Sure of clearing cache first (ctrl+F5)?

`still see the comments cut of bug. check out Laws comments`
Ah... I tested only in FireFox, there everything looks good. Gonna fix.

**Comment by denysaw** [comment]
Ah man. @rainfarmer. Comments cut off is because of your `scale/zoom` thing. Disqus reserves a space for itself, for a zoomed version, but loads without zoom in Chrome (in FF zoomed, that's why everything is good). Please, apply zoom changes for Chrome for Disqus container also, so it'll zoom also there ;)
