### ISSUE TITLE
Error writing to stat database: IndexOutOfRangeExeption ...

### ISSUE THREAD

**Issue by osmelpv** [StrangeLoopGames/EcoIssues#16280]
I am getting this error on my server running. I hae nor idea what is happening or how to fix it.

Error writing to stat database: IndexOutOfRangeExeption Index was outside the bounds of the array.

the server was working fine until some power cut, i wake up and i sow the server closed.

**Comment by osmelpv** [comment]
Any of the users can't craft any item

**Comment by osmelpv** [comment]
![image](https://user-images.githubusercontent.com/14095459/81728094-84d37800-944f-11ea-8777-9f5c7c2724d1.png)

**Comment by osmelpv** [comment]
fixed, i just load a backup

**Comment by SlayksWood** [comment]
Nice to hear that you fixed this issue. We have some improvements in 0.9.0 for saving world. Closed for now.
