### ISSUE TITLE
Corn wind is comical

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1628]
It just kind of leans to one side

![image](https://user-images.githubusercontent.com/3150561/26951593-9d771464-4c56-11e7-9046-8f9b1f9bd991.png)

**Comment by SeanAtr0n** [comment]
might also be due to the speedtree hack? none of the animations look as good as they used to

**Comment by metachronism** [comment]
no corn has always looked bad
and the speedtree stuff gives you the identical result

**Comment by keegan-o** [comment]
Need @MilenkoTunjic  to re-export this or add the corn source meshes for speedtree to SVN so I can.
