### ISSUE TITLE
Version: 0.9.0.0 beta staging-1542    you can't select skills

### ISSUE THREAD

**Issue by CorsarSPb** [StrangeLoopGames/EcoIssues#16295]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
![test 1](https://user-images.githubusercontent.com/65302234/81838769-44f3ba00-954f-11ea-9165-25b3a3ff1cc7.png)

you can't select skills

**Comment by CorsarSPb** [comment]
immediately after training, there is no opportunity to choose a profession. I studied the stonework. and again, there is no way to choose something. an empty book.

**Comment by CorsarSPb** [comment]
also, many tasks are not closed during the course of training. 
- take a tent 
- take an axe 
- chop down a tree

**Comment by CorsarSPb** [comment]
quick menu opening doesn't work Y, B, O, G, L
only the map opens M

**Comment by SlayksWood** [comment]
It's localization problem. It should be fixed in next build with https://github.com/StrangeLoopGames/Eco/pull/6056
original issue #16094
> To fix this I think you can try set language to English or/and reset all configs to defaults.
