### ISSUE TITLE
Commas in player names aren't being escaped on the web site

### ISSUE THREAD

**Issue by vsysio** [StrangeLoopGames/EcoIssues#16297]
![image](https://user-images.githubusercontent.com/40701885/81873267-5fc33000-9549-11ea-8ed8-8415425b493c.png)

This users Steam name has a comma in it, and it isn't escaped, causing the page to break.

Edit: To clarify, this is on the "Current Elections" page.

**Comment by vsysio** [comment]
Web Client\WebBin\inc\js\Election.js:1009:

`$(".current-rankings table tr[data-voter='" + data[i].Voter + "'] td").each(function(){`

data[i].Voter needs to be escaped.

**Comment by SlayksWood** [comment]
@vsysio Thanks for the report, we know about this issue. merged to #14132
