### ISSUE TITLE
workparty problems

### ISSUE THREAD

**Issue by Skytitan11** [StrangeLoopGames/EcoIssues#16292]
cant access bench to add labor.
![Skjermbilde (897)](https://user-images.githubusercontent.com/65282900/81796300-8a8f9300-950d-11ea-8aff-37827c8c543b.png)

**Comment by elfl0rd** [comment]
rmb at table? (+modifiers)

**Comment by SlayksWood** [comment]
You don't have Oil Drilling to add labor (by your second issue). So it's intented

**Comment by elfl0rd** [comment]
> You don't have Oil Drilling to add labor (by your second issue). So it's intented

Hmm, as i think, in this case player should see error or hint about it.
Like "You don't have needed speciality to add labor"
