### ISSUE TITLE
changed on of my stars

### ISSUE THREAD

**Issue by Skytitan11** [StrangeLoopGames/EcoIssues#16293]
picked oildrilling for one of my stars, set up all the oil drilling equipment and it worked. today the star has changed to basic enginering and i dont have access to make any oil.

**Comment by SlayksWood** [comment]
@Skytitan11 So you don't have this issue? you just lost Oil drilling?

**Comment by SlayksWood** [comment]
Use template for issue: 
1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files.

**Comment by SlayksWood** [comment]
Are you sure that you took Oil Drilling? If on the playtest, then there are sometimes small timebacks.
Your orders could work with bug #16258.

**Comment by beastyn** [comment]
Closing due no response and we wasn't able to reproducwe it
