### ISSUE TITLE
[0.9.0 Staging-1542] - Visual Glitch - Black screen flicker when passing world boundary. Ashlar under brace corner block graphical glitch.

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16296]
Graphical glitch (little black triangles) with ashlar under brace corner when built across world boundary - where third coordinate flips from 0 to 720:
![image](https://user-images.githubusercontent.com/48172405/81861804-b8ea8e00-9560-11ea-8912-3cbcac028dd8.png)

Walking across the world boundary causes the screen to flash black:
https://drive.google.com/open?id=1knEGkXkdTbGq5dl0D6fc20hjptDxN2m6

It appears to be linked to black screen flickers reported here: https://steamcommunity.com/app/382310/discussions/4/1753527228527346293/

I've not found another ticket reporting this.

A save, with examples of the block glitch at 71,71,1:
[Save.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4624416/Save.zip)

Logs:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4624423/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4624424/Player.log)

**Comment by trickenso** [comment]
Just checked some more - this doesn't appear to affect any other ashlar block forms (not even the top brace corner), but it does affect other ashlar stone types.

**Comment by SlayksWood** [comment]
merged to #9664

**Comment by trickenso** [comment]
@SlayksWood - Thank you! Sorry for missing the dupe.

**Comment by SlayksWood** [comment]
@trickenso no problem, it’s hard to find the right one among many issues
