### ISSUE TITLE
[0.8.3.3] Slow world generation on Linux/Docker

### ISSUE THREAD

**Issue by lagonnebula** [StrangeLoopGames/EcoIssues#16298]
Hello,

It's seem I have some performance issue on world generation on linux and docker.
I've tested creating a 2.31km² and it took me the same time (nearly 15mn) than making a 4km² on windows with native execution.  

I know that some part of the world generation arn't multithreaded and in container it's a little bit slower, but ...  my server have a Xeon 4c/8t at 3.2Ghz and my computer have an i7 4c/8t at 4.2Ghz.

For the test I have capped my CPU on my computer to 70% max usage for ECO and 100% was allowed on my server (that should be more or less comparable in term of CPU capabilities)

**Comment by SlayksWood** [comment]
@lagonnebula 
Thank you for the report.
We have a lot of improvements in generation world in 0.9.0 for Linux. You should not have this problems. So it's fixed. But if you still have this problems in 0.9.0 please reopen.

**Comment by lagonnebula** [comment]
@SlayksWood Ok, thanks. I ll wait for 0.9 than !
