### ISSUE TITLE
[0.9.0 staging-1548] NetObject update in localization

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16291]
1) Change server languge to some non-english (checked with rissuan and german)
2) Start a fresh world
3) Check placing for the world objects

It has some time delay
https://drive.google.com/file/d/1DivApO7xstl3il30XdIc9-hkpTeYiRor/view?usp=sharing

Can be fixed with server restart

**Comment by johnkslg** [comment]
Fixed! Nice find.
