### ISSUE TITLE
[0.9.0 staging-1542] Item crafted in Law trigger missing

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16303]
![image](https://user-images.githubusercontent.com/47274045/81922544-91d1a200-95dc-11ea-9f82-a659aa09a2ed.png)
Hello,
 the current law system allows you to trigger actions on only three types. The issue is, if you would like to tax the crafting of a specific item, it won't work. Like you want to tax each tailing which has been crafted. Right now you can only check if a work order with tailings has been started, but it is independent if you have one or many tailings been ordered, the actin will be triggered only once. 

A trigger with "item crafted" would be helpful to get this demand setup.

**Comment by SlayksWood** [comment]
@johnkslg Can we add it in 0.9.0 or should push it to 0.9.1?

**Comment by trickenso** [comment]
Alternatively (or also) you could add a parameter to 'Create Work Order' that allowed you to calculate how many Tailings (or whichever product) would be crafted.

If 'Crafted Item Amount' was in here, you could maybe calculate it using 'Create Work Order' trigger:
![image](https://user-images.githubusercontent.com/48172405/81934647-32c55a80-95e7-11ea-8bf1-2df4f6a1b032.png)

"On Item Crafted" trigger might be more straightforward, though.

**Comment by johnkslg** [comment]
Added Item Crafted action that does this!
