### ISSUE TITLE
Ghosting on various graphics settings (back buffer not clearing), and some graphics settings don't work

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16307]
On various graphics settings you get bad ghosting, Simon says it looks like the back buffer is not clearing.
![image](https://user-images.githubusercontent.com/14983165/81971594-2dabdf80-95d6-11ea-85d5-559422aa94ac.png)

Also, turning off Ambient Occlusion doesn't actually work from the graphics menu-- could be a different issue but it's also pretty important.

**Comment by keegan-o** [comment]
(for me, it happens when I switch AA to lower with no GI)

**Comment by redwyre** [comment]
@keegan-o can you take a screenshot of your graphics settings that cause the ghosting?

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82394494-0ef68000-99fe-11ea-98f1-8fb245a6f604.png)
I start the game like this, everything is fine, then I turn off GI:
![image](https://user-images.githubusercontent.com/14983165/82394509-1c136f00-99fe-11ea-8058-ad985ecbb4e0.png)
And it's ghostin':
![image](https://user-images.githubusercontent.com/14983165/82394528-27669a80-99fe-11ea-8161-5e30e0588d18.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82394562-3cdbc480-99fe-11ea-949b-3247eece8e52.png)
Looks like it's only in the sky

**Comment by keegan-o** [comment]
I take it back, I can get full screen ghosting with these setting:
![image](https://user-images.githubusercontent.com/14983165/82394681-875d4100-99fe-11ea-939b-88f873279253.png)
![image](https://user-images.githubusercontent.com/14983165/82394690-8d532200-99fe-11ea-8179-a00f9c9f63a7.png)

**Comment by redwyre** [comment]
Can you try it with those settings and a new world? I can't reproduce it, but it may be something that's rendering in the city. If not I'll need the world and the position it happens.

Otherwise I'll have to get you to do a graphics capture for me in RenderDoc, I can walk you through it.

Also can you include a log file after it happens in case there's something in there?

**Comment by keegan-o** [comment]
working with Simon, but I determined that I haven't seen this in a steam build, only in Unity
