### ISSUE TITLE
[0.9.0 staging-1542] Can't exit from tractor with sower

### ISSUE THREAD

**Issue by BarikSHL** [StrangeLoopGames/EcoIssues#16306]
How to:
1) install harvest module into tractor //we can enter or exit freely with that module
2) change harvest to sower module
4) enter the tractor
5) no exit!  We can use /unstuck, and can run, but we have tractor interface instead of player's item menu.. Only relogin helps. 
If we just put sower module at clean tractor it wouldn't be bugged.
I found the problem at https://github.com/StrangeLoopGames/EcoIssues/issues/15216, but no reaction -_-

**Comment by SlayksWood** [comment]
@BarikSHL thank you for finding reprosteps.

**Comment by trickenso** [comment]
> have tractor interface instead of player's item menu.. Only relogin helps.

Just had this problem in Staging 1554 - unsure exactly how to reproduce, but will update.

**Comment by BarikSHL** [comment]
1554 - bug is still here, step to reproduce - the same (install harvester, change to sower). Mb fix is not in 1554?
