### ISSUE TITLE
Improvement for placing first and ending points in different fill types

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16304]
Composite redwood flat roof with floor fill - would expect it to snap to the top of the thin wall:
![Composite roof](https://user-images.githubusercontent.com/48172405/81399203-871d9580-9122-11ea-98d4-c0aec7f3cb50.gif)

_Originally posted by @trickenso in https://github.com/StrangeLoopGames/EcoIssues/issues/15955#issuecomment-625738629_

**Comment by elfl0rd** [comment]
A significant improvement will also be the ability to "finish" in the air and not just on any block.

**Comment by trickenso** [comment]
> A significant improvement will also be the ability to "finish" in the air and not just on any block.

Can finish three-point fill types in the air. I imagined this was part of the value of getting these final fill types.
