### ISSUE TITLE
Web call to server API for 'Vote' is sending wrong order

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16314]
I'm trying to vote this order:
![image](https://user-images.githubusercontent.com/3536496/81990905-f1d44280-95f4-11ea-9540-2a131a484217.png)

But that's not what's being received:
![image](https://user-images.githubusercontent.com/3536496/81990930-fe589b00-95f4-11ea-84e2-ac9434aab93c.png)

It appears to be sending the candidates in the default order instead of the ranked order I picked.

**Comment by SlayksWood** [comment]
Seems fixed
