### ISSUE TITLE
[0.9.0 staging-1542] Lawsystem - edit existing law with comma number will be changed

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16310]
If you create a law with a number having comma value after save and edit the value will be replaced without comma. 
![image](https://user-images.githubusercontent.com/47274045/81978630-1992cd00-962c-11ea-9f30-010ff69dc169.png)

after click on revise the law:
![image](https://user-images.githubusercontent.com/47274045/81978682-2adbd980-962c-11ea-86f9-84cd8c7c6caa.png)

**Comment by beastyn** [comment]
![bandicam 2020-05-15 12-51-15-515](https://user-images.githubusercontent.com/27898520/82025459-cf9cfc00-96aa-11ea-9e76-2e153c02f9d0.jpg)

**Comment by Alteraner** [comment]
With the new playtest Version no comma value is possible any more. It will be imidiatly change into full number value. :-(
Please keep comma values...

**Comment by trickenso** [comment]
This appears to be the same issue as #16411

**Comment by beastyn** [comment]
Should be fine with update
