### ISSUE TITLE
Long tooltips go off screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16315]
![image](https://user-images.githubusercontent.com/3536496/81991681-b0449700-95f6-11ea-87ba-01f6379f90bf.png)

Here is the law it's trying to display:
![image](https://user-images.githubusercontent.com/3536496/81991710-bdfa1c80-95f6-11ea-9c7c-0b14b273de3d.png)

**Comment by MarkZaytsev** [comment]
Now it should look like this. I used Wrap flag in tooltip on the server. So it's default wrapping tooltip section.

![ss (2020-05-15 at 02 06 17)](https://user-images.githubusercontent.com/50739566/82022326-b69a4800-96b6-11ea-995c-4f930c0dd432.jpg)
