### ISSUE TITLE
Servers sharing voice backend session

### ISSUE THREAD

**Issue by Ragonz** [StrangeLoopGames/EcoIssues#16318]
2 Eco servers in different countries are sharing voice sessions in game, the 2 servers are located in different datacenters in different countries on different continents and none of the ports used are the same.

This is not expected behaviour and needs to be resolve ASAP.
If any further information is required please reach out to me on discord Ragonz#4467

**Comment by beastyn** [comment]
Please, check if you are using the same Voice.eco
Try to delete that file on both servers.

**Comment by redwyre** [comment]
They were using the same voice server ID.
