### ISSUE TITLE
[0.9.0.0 beta staging-1542] Temporal Anti-aliasing Bug with tools and stacks of items

### ISSUE THREAD

**Issue by TheRealLittleKing** [StrangeLoopGames/EcoIssues#16329]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
1. Enable Temporal Antialiasing
2. Hold tool or stack of items (Wood,Stones,etc)
3. The "Ghost" should appear in front and to the right of the tool or just on top of a stack of items. (The ghost are easier to spot when looking at grass or just looking around)

**Expected behavior:**
There should be no ghost of the tool or item stack.

**Actual behavior:**
Logs gif: https://gyazo.com/f1d8f53688b5adef3b45d8d3d2b19002
Logs pic: https://gyazo.com/e348f161d44467e7f2b0a904d14fc945
Tool gif: https://gyazo.com/ba0460250224595aaf5ba77afef4f15c
Tool pic: https://gyazo.com/929f11290b64bf190f700e646b1efb9b

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Comment by redwyre** [comment]
Don't use Temporal Antialiasing. It will be removed at a later date.

**Comment by redwyre** [comment]
Replace with https://github.com/StrangeLoopGames/EcoIssues/issues/16332
