### ISSUE TITLE
[0.9.0 staging-1542] - Text Tweak - "CO2 from pollution" is not from pollution

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16323]
CO2 is no longer generated by pollution, but is now a direct emission from sources. The data point is still marked "CO2 from pollution", which is no longer accurate.

The data point could read something like "CO2 Emissions", "CO2 from player activity", "CO2 from vehicles and manufacturing" or similar, so it reflects that pollution is no longer the source of the CO2.

**Comment by johnkslg** [comment]
renamed
