### ISSUE TITLE
[9.0 Staging-1542] - UI Reverts back to default tab (randomized)

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#16324]
A few user reported that when you open a stockpile it defaults to the modules tab, 
This should be the storage tab by default (first in the line) 

But they also claim that it forgets which tab you have after a few minutes and reverts back to the default tab,

How to recreate:
Place a storage item down and open it up, 
Navigate to the storage tab, 

exit the ui and wait a few minutes or (also reported) look in another item ( like a campfire or someone else's storage) 
Return to your storage item down and reopen the ui (it should revert back to modules)

Players have reported this happens differently for each person, 
Some players say this happens everytime they reopen the ui,
Some players say this happens after a few minutes,
Some players say this happens after looking in another world objects ui,
Some players say this doesn't happen to them at all

Tested items, 
Stockpile
Storage Chests
Campsite (returns to crafting tab)

This is not limited to the same item,

What i think it should do, it should remember the last tab you had open in the ui, so if you left on storage, when you come back it should be on storage

Should stockpiles also have a Modules tab?

**Comment by SlayksWood** [comment]
Module tab deleted from stockpile. It should be fixed with https://github.com/StrangeLoopGames/Eco/pull/6056
So default tab should be storage for stockpile. And after playtest upgrade it will fixed.

> But they also claim that it forgets which tab you have after a few minutes and reverts back to the default tab

It's intented behavior.
