### ISSUE TITLE
[9.0 Staging-1542] Excessive Ram Usage

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#16325]
This is only one instance i have captured out of the 3 times this has happened, 

My ram usage for eco has hit a total of 19,000MB 
This current image shows eco using 10GB of ram after only 10 minutes of gameplay, 

1 other user has reported high usage as well, 
This image also shows my graphics settings

PC Specs,
i7-8700k  @ 4.7ghz
32GB 3200Mhz GSkill Ram
1070TI 
Currently stored on a HDD not a SSD
![high memory usage](https://user-images.githubusercontent.com/29281156/82033247-ced28d00-96df-11ea-85bd-d6ad42ad65b1.PNG)

**Comment by TheKye** [comment]
Here is a snap from another player with the same issue
![other user](https://user-images.githubusercontent.com/29281156/82033626-55876a00-96e0-11ea-9676-7e02b0c5e97e.png)

**Comment by SlayksWood** [comment]
@TheKye please provide log files
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheKye** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4633489/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4633491/Player-prev.log)

**Comment by SlayksWood** [comment]
thank you for information, merged to #16142
