### ISSUE TITLE
Pipes blocking table?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1632]
This table's work orders have stopped, but the status tab says it is okay.  I'm guessing that it's blocked because the tank on it's pipes tab is full, but this isn't displayed in the UI anywhere, and the state is very confusing.

This needs a status entry or something

![image](https://user-images.githubusercontent.com/23460210/26955314-dbac13a6-4c6a-11e7-8ae3-86c567fbc509.png)
![image](https://user-images.githubusercontent.com/23460210/26955315-de24ecde-4c6a-11e7-9ac3-87d09b5d1e53.png)

**Comment by craig-jong** [comment]
Also needs attachments, art assets for attachments, and chimney pipes. Possibly the world objects will need to be changed slightly? Depends on how the attachments are.

Following tables need to be looked at:
Cement Kiln
Blast Furnace
Factory
Oil Refinery
Stove
