### ISSUE TITLE
USER ISSUE: new windows may open out of frame

### ISSUE THREAD

**Issue by namelesswalaby** [StrangeLoopGames/EcoIssues#16320]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
1) start new character
2) open windows

**Expected behavior:**
sometimes the window will open out of frame

**Actual behavior:**
it should open inside of the frame

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Comment by SlayksWood** [comment]
@namelesswalaby Can you provide some more information? 
1. what kind of windows? with screenshots and steps
2. provide log files 
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
It was happen before when you switch from 8.3.3 to 0.9.0. But it was fixed by @serpopov. In any case if some part of window out from screen you can move it.
Reopen when you can provide us with necessary information
