### ISSUE TITLE
Chat window show old temp notices for a moment when you open it 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16328]
![animx22](https://user-images.githubusercontent.com/3536496/82077000-80979c80-9693-11ea-9455-ebdb5df16b18.gif)

**Comment by SlayksWood** [comment]
I can't reproduce it in staging-1553

**Comment by gzatravkin** [comment]
Reproduced 
(Open chat, create error message, wait for message desappear, reopen chat).

Should be fixed in fixes #6137
