### ISSUE TITLE
[0.9.0 staging-1542] Server lag spike on land claiming

### ISSUE THREAD

**Issue by TazMatic** [StrangeLoopGames/EcoIssues#16337]
I'm struggling to pin point what causes the lag spikes but I believe without any concrete evidence that when a player claims land the server gets hung up for 1-3 seconds causing block and entity lag. Server is currently running on 2.8ghz cpu's and don't seem to spike higher than 10% utilization and 2.2gb of ram.

**Comment by SlayksWood** [comment]
@TazMatic Thank you for the report. Can you provide save files?
Instruction is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Can't reproduce in 0.9.0 staging-1575.
Closing for no response, reopen when you can provide us with necessary information
