### ISSUE TITLE
[0.9.0 staging-1542] Server exception when transfering money due to law

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16335]
When triggering a tax action through a transfer money event, I received a server exception:
![image](https://user-images.githubusercontent.com/982322/82094131-bfae0800-96fc-11ea-98c7-8833aed9ec82.png)

Law looks like this:
![image](https://user-images.githubusercontent.com/982322/82094290-07cd2a80-96fd-11ea-83df-6dec620ae989.png)

**Comment by beastyn** [comment]
I can't repro exception with the new build 1553
But something is wrong

Law is blocking transfer with some missing fields as it won't understand reciever.
After that maybe crash will appear?
![bandicam 2020-05-18 11-28-06-390](https://user-images.githubusercontent.com/27898520/82180953-f9e4f880-98fa-11ea-8229-68307c692afe.jpg)

![bandicam 2020-05-18 11-28-25-816](https://user-images.githubusercontent.com/27898520/82180820-c0ac8880-98fa-11ea-8229-56ec91abdeb9.jpg)

**Comment by johnkslg** [comment]
Is the transferring of tax generating a 'transfer money' event? Shouldnt.

Probably some missing fields not getting populated.
