### ISSUE TITLE
Don't show removed titles in lists

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16334]
![owner](https://user-images.githubusercontent.com/25908592/82090255-88882880-96f5-11ea-9ed5-7da10b05afb8.png)

1) It clutters up the list without any use.
2) In case of transfering a deed by mistake to one of the removed titles, an admin needs to reclaim it, as it's stuck otherwise.

I'd have them removed from all such lists, actually.

**Comment by D3nnis3n** [comment]
At least group them away into another group.

**Comment by johnkslg** [comment]
Yes remove them, Oleg can you make these filter like our other lists?
