### ISSUE TITLE
[0.9.0 staging-1542] After collecting a plant it still shows fruit as you leave the render distance of the plant

### ISSUE THREAD

**Issue by TazMatic** [StrangeLoopGames/EcoIssues#16336]
After you collect a ripe plant and walk away it starts to phase back to ripe, then as you approach the plant the fruit disappears
![20200515170254_1](https://user-images.githubusercontent.com/31835653/82096267-9aa2a080-96ce-11ea-9789-b3ce0d44449a.jpg)
![20200515170312_1](https://user-images.githubusercontent.com/31835653/82096277-9ecebe00-96ce-11ea-93ce-65f563d73a15.jpg)
![20200515170309_1](https://user-images.githubusercontent.com/31835653/82096274-9d9d9100-96ce-11ea-8028-3877c9029841.jpg)

**Comment by SlayksWood** [comment]
dup #2825
