### ISSUE TITLE
Floating scrollbar on tooltips

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16331]
![image](https://user-images.githubusercontent.com/3536496/82080364-43cea400-9699-11ea-8864-f46392c2da31.png)

**Comment by SlayksWood** [comment]
same with species tooltip. I can't find issue for that:
![image](https://user-images.githubusercontent.com/45708377/82175662-196d2880-98dd-11ea-8756-ceaf2f746411.png)
