### ISSUE TITLE
Player icons are showing on reverse side of world on minimap 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16338]
![animx22](https://user-images.githubusercontent.com/3536496/82097613-16ddb980-96b8-11ea-9249-f1ef7d2d0b9e.gif)

**Comment by SlayksWood** [comment]
Your changes broke display icons in 2D map. Now they are visible only in small circle
![image](https://user-images.githubusercontent.com/45708377/83227665-6a0e3c80-a18d-11ea-90b5-75e4fd0b0242.png)
But we have another issue for that #13463
