### ISSUE TITLE
[0.9.0 staging-1542] Oil refinery still work, when no water flowing

### ISSUE THREAD

**Issue by BarikSHL** [StrangeLoopGames/EcoIssues#16333]
How to:
1) Put oil refinery
2) Make it work and test: it works
3) Put waste filter, connect it to refinery, give it power, but don't put claim on it (filter says, that he need an owner to wrok)
4) Start craft at oil refinery: it works, but no water and/or compost from waste filter.

**Comment by SlayksWood** [comment]
dup #16258
