### ISSUE TITLE
Web Elections: Simplify Voting

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#16341]
![image](https://user-images.githubusercontent.com/7343272/82106479-1e13c000-96d6-11ea-9feb-0f10d87cd624.png)
- [ ] Remove 'Update Vote' button. If user clicks yes or no, it auto updates their vote.

![image](https://user-images.githubusercontent.com/7343272/82106512-5915f380-96d6-11ea-8253-64ea5d840cc1.png)
- [ ] Can you find a better system for rating votes? Something like this: https://jsfiddle.net/f2a54cp0/2/

**Comment by beastyn** [comment]
Can we add a position number for candidates?
And need some hint about draggable interface here

**Comment by denysaw** [comment]
Comment is a double of John's issue. And next time new issue please, not Reopen. Thanx

**Comment by denysaw** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/16795
