### ISSUE TITLE
[Moved] File Not Found Error - Modding

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#16346]
Moved by request to EcoIssues from: [#6032](https://github.com/StrangeLoopGames/Eco/issues/6032)

Im doing some pre 9.0 work on my modkit, My modkit relies on a base dll that contains all of the major things used throughout my modkit, however, when trying to boot the server even in debug mode, its the first dll that loads but then after that if i have more then 1 dll that requires it the server throws an exception:

System.IO.FileNotFoundException: 'Could not load file or assembly 'em-base, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

my dlls are still built on the .NET Framework using Version 4.7.2
I also have the same issue even after switching to .NET Core or .NET Standard

is this an error server side? also could this be due to 9.0 being incomplete?

Using Staging Branch

Have also done more testing after a suggestion from Redwyre,

Using a .NET Standard 2.1 DLL as a base file with .NET Core 3.1 DLL Referencing the base file i get this error inside all of my objects:
System.TypeLoadException: Declaration referenced in a method implementation cannot be a final method. Type: 'Eco.Mods.TechTree.ElevatorDoorsItem'. Assembly: 'em-doors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. System.IO.FileNotFoundException: Could not load file or assembly 'base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

I can provide a copy of the code for these files as well if needed

Using .NET Core 3.1 DLL Base file with .NET Standard 2.1 DLL Referencing the base file i get this error:
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Redywre Response:
To correct myself: we are using .net core 3.0.101 sdk.
All your DLLs should be .net standard 2.1

After reds response

Okay, After swapping to .net standard 2.1 fully and fixing a couple of errors from new content i get this error, This comes up when another file that references it tries to use it as well:

System.IO.FileNotFoundException: Could not load file or assembly 'em-base, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'em-base, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

Full Error:
Could not load file or assembly 'em-base, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at Eco.ModKit.ModKitPlugin.LoadModDlls() in D:\EcoSource\Eco\Server\Eco.ModKit\ModKitPlugin.cs:line 159 at Eco.ModKit.ModKitPlugin.LoadModsData(TaskCompletionSource1 done) in D:\EcoSource\Eco\Server\Eco.ModKit\ModKitPlugin.cs:line 104
at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource1 done) in D:\EcoSource\Eco\Server\Eco.ModKit\ModKitPlugin.cs:line 81

**Comment by redwyre** [comment]
So "em-base" is your dll right? Is it in the mods directory as well?

**Comment by TheKye** [comment]
Correct, em-base.dll is my dll, it holds alot of my core code that my modpack relies on, it is in the mods directory its the first one to load

**Comment by MonzUn** [comment]
Are you still having this issue in staging-1695 @TheKye?

**Comment by TheKye** [comment]
No, this is all fixed in 1695
