### ISSUE TITLE
DataSets: return fewer day intervals

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#16344]
Endpoint `/datasets/get` should return averaged values with strict `Day` step:
- If it's 2 days or less (distance between from and two) then your interval should be `0.1` day.
- If 4 days or less, then interval equals `0.2` Days.
- If 10 days or less, then `0.5` Days
- If > 10 days then `1` Day.

So the count of returned items should be `Overall items between dateFrom and dateTo` /  `step`

Referring to:
https://github.com/StrangeLoopGames/EcoIssues/issues/16343

**Comment by johnkslg** [comment]
Stats now return in intervals of one hour if total range is <= 3 days, and 1 day otherwise.

**Comment by denysaw** [comment]
Perfect! You can merge it ;)
