### ISSUE TITLE
[0.9.0 staging-1542] - Minor Graphical Problem - Vehicle smoke responds to steering backwards

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16349]
The smoke appears to respond backwards to steering - if the left and right response were exchanged it would likely be just fine, but as it is the smoke appears to be haunted:

![Smoke](https://user-images.githubusercontent.com/48172405/82118186-616d3d80-976d-11ea-86a1-d6b6ce089417.gif)

I have only tested this for the steam tractor - it could be true for other vehicle smoke also.

**Comment by olegshegai** [comment]
Smoke prefabs corrected and committed to the SVN

**Comment by beastyn** [comment]
Hm... Looks like it still have this strange rotation, but less,
Have a glance one more time,please
https://i.gyazo.com/3b3794647a424724aa9869b7b57e6b50.gif

**Comment by Lyrcaxis** [comment]
Smoke prefabs corrected and committed to the SVN

**Comment by Lyrcaxis** [comment]
I missed that the objects were not using nested prefabs.

Fixed smoke on Steam Tractor, Steam Truck, Truck, Excavator, SkidSteer and commited to SVN.

Let me know if there are any vehicles left forgotten.

**Comment by TwixterZ** [comment]
@Lyrcaxis tested on Steam Tractor, Steam Truck, Truck, Excavator, SkidSteer and smokes are fine,

if I were to nitpick, Excavator smoke while diriving backwards went thru the exhaust

https://gyazo.com/5e10906ae0c683ffa52cfc3890d0bdce
