### ISSUE TITLE
Can't get SEGI to work in the title screen

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16345]
![image](https://user-images.githubusercontent.com/14983165/82109411-7359cc80-96ea-11ea-96f7-5cf7e504af71.png)
I get this error when I try to add SEGI to the title screen camera. I'd like it to be the same settings as SEGI in-game.

**Comment by redwyre** [comment]
I have a fix for this to go in to SVN but needs https://github.com/StrangeLoopGames/Eco/pull/6102 first

**Comment by redwyre** [comment]
Fix in SVN
