### ISSUE TITLE
[0.9.0 staging-1542] - Missing wheel element from Steam Tractor

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16354]
This rear wheel axle end piece is missing on both sides:
![image](https://user-images.githubusercontent.com/48172405/82127810-5981bd80-97ae-11ea-8b5f-fc6282b39fdb.png)

**Comment by SlayksWood** [comment]
I don't have this issue in staging-1553.
![image](https://user-images.githubusercontent.com/45708377/82180005-48d56280-98e8-11ea-9793-97c711ea4018.png)
@trickenso Can you check it again after updating playtest to new staging build.

**Comment by SlayksWood** [comment]
You need to sit in/out:
![image](https://user-images.githubusercontent.com/45708377/82190992-8f33bd00-98fa-11ea-938d-b106fe76fb44.png)

**Comment by trickenso** [comment]
Good spot - sorry for missing that detail!

**Comment by keegan-o** [comment]
After trying to correct this, it seems to me that what is happening is the wheel is being rotated 180 degrees by the vehicle script so that the inside is outside, which has that missing part.

**Comment by StanKryvenko** [comment]
Fixed in SVN
