### ISSUE TITLE
USER ISSUE: cedar trees missing trunk

### ISSUE THREAD

**Issue by Duffman1200** [StrangeLoopGames/EcoIssues#16356]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
planted new cedar tree

**Expected behavior:**
planted a full tree with trunk.

**Actual behavior:**
trunk section just above stump is missing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, no

**Comment by SlayksWood** [comment]
@Duffman1200 Thank you for the report. Can you provide screenshots? This is a known issue for oak, but not for cedar.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
