### ISSUE TITLE
[0.9.0 staging-1542] - If you set it in Korean and turn on the server, all functions will not work.

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#16350]
If you set it in Korean and turn on the server, all functions will not work.

Technology, ore cannot divide into lumps, soil spreads to 10 pieces, and trees are not cut.
Monsters move back and forth in the same place.

Everything works fine if you set it to English on the server.

And...

I received a reply about a month ago that the terminal vowel was modified, but it hasn't been resolved yet.
Please check.

ex.)
ㅋㅋㅋㅋ -> ?????
ㄴㄴㄴㄴ -> ????
안녕하세요 ㅋ -> 안녕하세요?
ㅎㅎㅎㅎㅎ -> ????

It comes out like on the right side of the chat room.
![20200516151645_1](https://user-images.githubusercontent.com/61628364/82119472-d8302800-97b9-11ea-882f-70f40df82776.jpg)

**Comment by SlayksWood** [comment]
@StoryNine Thank you for the report.
It's localization problem. It should be fixed in next build with StrangeLoopGames/Eco#6056
original issue #16094
