### ISSUE TITLE
[0.9.0 staging-1542] Possibility to get stuck inside the Capitol item

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#16352]
With no floor, the red ropes around the capitol are impassible, but the base is not solid, so you are able to get inside the ropes, but be too low to jump out as shown below
![image](https://user-images.githubusercontent.com/54982803/82121877-36441780-9788-11ea-9bba-49ac946bfafe.png)

**Comment by elfl0rd** [comment]
ha! Same issue with old stockpiles :D - https://github.com/StrangeLoopGames/EcoIssues/issues/10203

**Comment by Sekor2600** [comment]
fixed in SVN

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/82179200-6a354f00-98e6-11ea-86ce-5117b0e8609f.png)
