### ISSUE TITLE
[0.9.0 staging-1542] Campfire works without fuel

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#16351]
1. Place a Campfire
2. Fuel it with some wood in one slot and some wood pulp in the other
3. After the first job is done the campfire is out but the following jobs run though without burning fuel

As you see here, no fuel is burned, also no time displayed, campfire makes no sound and no fire but works:

![20200516131302_1](https://user-images.githubusercontent.com/63646359/82119510-836fbb80-977f-11ea-943c-3f9e037c6ced.jpg)
![20200516131305_1](https://user-images.githubusercontent.com/63646359/82119512-84085200-977f-11ea-9bff-f8bfc3c732f2.jpg)

Maybe other burnings would make that happen too.

**Comment by SlayksWood** [comment]
dup #16258
