### ISSUE TITLE
[9.0] Playtest Version Shader/Texture?

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#16368]
Sometimes some Parts of the Texture of Objects are Black
![grafik](https://user-images.githubusercontent.com/37456949/82161705-37b43380-989f-11ea-9c5b-4453c5d84e4e.png)

When you change now the Graphic Setting to Other value and then Back its normal again

**Comment by Sekor2600** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4642499/Player.log)
![grafik](https://user-images.githubusercontent.com/37456949/82183087-a0be9a00-98e5-11ea-8faa-393d1d7a9182.png)

**Comment by SlayksWood** [comment]
merged to #14042
