### ISSUE TITLE
Hosted worlds feedback: missing info how to connect to a server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16365]
I do have feedback on hosted worlds. My feedback is that I can't find anywhere in any page/document/email how to connect to the game server. Only the web-based dashboard is connectable, but the game server doesn't appear to be running on the same domain as the game cannot connect there. So as of now, I can't test it much yet. I recommend adding the game server connect info to the worlds list in the account website. It would also be good to send it in the welcome to Hosted Worlds email.

Since it's not there yet, can you let me know how to connect from in-game?

Thanks,

Emma

**Comment by D3nnis3n** [comment]
Issue itself is already resolved, customer knows how it works now, just needs improvement on website.
