### ISSUE TITLE
USER ISSUE: fishing not showing hooked fish

### ISSUE THREAD

**Issue by Duffman1200** [StrangeLoopGames/EcoIssues#16367]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
while having a fish on the hook, reel in the fish.	

**Expected behavior:**
fish dancing around on the hook while being reeled in.	

**Actual behavior:**
fish is either not visable at all or is off to the far edge of my view.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Comment by SlayksWood** [comment]
merged to #14410
