### ISSUE TITLE
Capitol object is a crafting table, but does not have a storage component

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16360]

**Comment by WeaselDog** [comment]
I can't replicate this. CapitolObject has the Link Component
![CapitolStorage](https://user-images.githubusercontent.com/47330823/82134100-c2663700-97a8-11ea-9c37-ac3a0ae901cf.png)

**Comment by johnkslg** [comment]
so it does! nvm
