### ISSUE TITLE
[0.9.0 staging-1542] - Cannot claim land under a stockpile

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16363]
Animation plays, then claim stake goes into stockpile. The claimed or unclaimed status of the land doesn't appear to make any difference. I would expect the land to be claimed - or, less preferably, the stake goes into the stockpile without the animation playing.
![Stake](https://user-images.githubusercontent.com/48172405/82152206-9e156380-9857-11ea-9505-9c17e7c5758f.gif)

Perhaps a broader question, but I wonder what is the use case for tools going into storage on right-click. It seems to be an irritant when it happens by accident, and I can't think of a situation where you would want to do it deliberately. If there isn't a case for this, I definitely make a request to prevent tools being placed in storage on right-click.
Feel free to disregard if this has already been considered.

**Comment by SlayksWood** [comment]
dup #16114
