### ISSUE TITLE
[0.9.0 staging-1553] Notification issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16378]
1. I can not reproduce with 100%, but notifications don't always appear. Step to reproduce:
 - /manage warnuser 1, Testtest (1 - my ID)
![image](https://user-images.githubusercontent.com/45708377/82206461-f3fa1200-9910-11ea-8690-b5de0220bd1e.png)
- open chat:
![image](https://user-images.githubusercontent.com/45708377/82206542-18ee8500-9911-11ea-94e8-b15ab35abf8f.png)
- use this command 2-3 times and then wait when notification disappear. Use this command another time. Notification appear only in right corner:
![image](https://user-images.githubusercontent.com/45708377/82206641-40dde880-9911-11ea-95a8-ee98dcca7de7.png)

**Comment by johnkslg** [comment]
Split off into two bugs so G can do this one.
Other bug was moved here: https://github.com/StrangeLoopGames/EcoIssues/issues/16435
