### ISSUE TITLE
[0.9.0 staging-1553] Command line doesn't close with shutdowning server.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16375]
![image](https://user-images.githubusercontent.com/45708377/82196505-70d1bf80-9902-11ea-81b8-ddd0a0af245d.png)

**Comment by mirasrael** [comment]
Caused by infinite loop in Stats.Run after recent change.

**Comment by mirasrael** [comment]
```csharp
public void Run()
        {
            this.aggregatableStatsSquashWorker.Start(ThreadPriorityTaskFactory.Lowest);
            while(true)
            { 
                Thread.Sleep(60000);
                this.Flush();
            }
        }
```
You should avoid loops like this. It is why we have workers. Because on server shutdown this loop will continue run and won't release the thread.
Add `flushWorker` instead and shutdown in in
```csharp
public void Shutdown()
        {
            this.aggregatableStatsSquashWorker.Shutdown();
            this.liteDbService.Dispose();
        }
```
You can use `PeriodicWorkerFactory.CreateWithInterval` to create the worker repeating every 1 minute,

**Comment by johnkslg** [comment]
Changed stats to flush whenever storage manager does instead.
