### ISSUE TITLE
Tooltips wrap to some max width by default

### ISSUE THREAD

**Issue by MarkZaytsev** [StrangeLoopGames/EcoIssues#16371]
"Make all tooltips wrap to some max width by default
This flag could still be used to wrap text to an even tighter width for some methods"
Requested during PR review https://github.com/StrangeLoopGames/Eco/pull/6095

Tooltip could use max width limit. To keep some long lines, but wrap those that are way too long
In that case we could remove Wrap flag from the server completely and make wrapping automated.
Thing is, we can't decide if wrapping is needed before we calculate default width of the tooltip without any wrapping since we have a lot parsed style, color, image data in text and can't assume wrapping just by string argument length. 
That is why wrapping should be decided on the client.

**Comment by gzatravkin** [comment]
duplication of 
https://github.com/StrangeLoopGames/EcoIssues/issues/16455#issuecomment-649849037
which wasn't reproduced
