### ISSUE TITLE
Upgrade Module Speciality icon updates

### ISSUE THREAD

**Issue by RobertMangano** [StrangeLoopGames/EcoIssues#16370]
Some of the icons seem really out of place or use other object icons. I have made a list of the ones I think should have new icons.

- [ ] Baking upgrade item-advanced
- [ ] Carpentry -Advanced
- [ ] Carpentry -Basic
- [ ] Cooking upgrade -advanced
- [ ] Farming upgrade- basic
- [ ] Glassworking- modern
- [ ] Logging -basic
- [ ] mechanic-modern
- [ ] mining -advanced maybe
- [ ] mining -modern

**Comment by keegan-o** [comment]
since these are just for the modules, pushing for later consideration (may not need these at all, either, depending on how those are arranged)
