### ISSUE TITLE
[0.9.0 staging-1553] Nested clause field narrower than other clauses

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16373]
![image](https://user-images.githubusercontent.com/45708377/82192192-509f0200-98fc-11ea-9eb7-a22996e0eb22.png)

**Comment by johnkslg** [comment]
Push all minor contract bugs because they will go away with work parties

**Comment by MrAnonymous110** [comment]
![image](https://user-images.githubusercontent.com/3883524/92508470-e4416900-f232-11ea-9c17-7ebee03ef27d.png)
I checked the UI and it's not happening anymore, could you verify it again?

**Comment by IcedForge** [comment]
There is a lack of consistency of the bar's alignment on the clauses in the UI it shouldn't really be offset like this for different variations.
![Screenshot_90](https://user-images.githubusercontent.com/24981362/94535297-b6ec4780-0241-11eb-8ecb-29e719243185.jpg)

**Comment by SlayksWood** [comment]
Nested Clause is a little wider now.
![image](https://user-images.githubusercontent.com/45708377/94893463-e6908f00-048f-11eb-8bd5-530c9076016a.png)

**Comment by beastyn** [comment]
I will just close it, thought its still not ideal, as we will change it and then review once again.
