### ISSUE TITLE
[0.9.0 staging-1542] - Minor Text Error - Land claims transferred by law has '</ecoicon>'

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16379]
This is on playtest server.
![82237138-1c900500-992d-11ea-96f9-205477fd82a3](https://user-images.githubusercontent.com/48172405/82237513-aa6bf000-992d-11ea-93f1-e0582267d6af.png)

The law that made the transfer:
![image](https://user-images.githubusercontent.com/48172405/82237865-3bdb6200-992e-11ea-850a-5fff8b334d0f.png)
![image](https://user-images.githubusercontent.com/48172405/82237876-4269d980-992e-11ea-8ea7-ec8d64191cfb.png)

Logs:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4645428/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4645429/Player-prev.log)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/82318922-5880a400-99d9-11ea-9db0-7daa81e18bae.png)

**Comment by SlayksWood** [comment]
if you try to move this deeds to another (Shift + LMB with stake)

**Comment by johnkslg** [comment]
It looks like the law is inserting its name into the deed name (you can see there are law icons in the deed name, but no deed name). Make it not use the marked up name from the law when generating the new name.

**Comment by SlayksWood** [comment]
![Uploading image.png…]()
