### ISSUE TITLE
[0.9.0 staging-1554] Milk should be hidden

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16385]
![image](https://user-images.githubusercontent.com/45708377/82290299-412cc100-99af-11ea-9c97-ec334e5b01ec.png)

**Comment by elfl0rd** [comment]
As I think "hidden" list should be available to edit by server owner.

E.g. i saw milk used in cooking at modded servers.

**Comment by mirasrael** [comment]
You can set (or remove it in modded file). I.e.:
```csharp
[Category("Hidden")]
public class DevtoolItem : HammerItem
```
Instead of hard-coding we should update ItemTemplate to support Hidden tag from tech tree (like for BlockTemplate).
