### ISSUE TITLE
[0.9.0 staging-1554] Possibility to change clothes color.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16386]
May be just delete possibility to change clothes in Edit mode 
![image](https://user-images.githubusercontent.com/45708377/82293583-73d9b800-99b5-11ea-922e-567233c5d238.png)
instead deleting all tabs:
![image](https://user-images.githubusercontent.com/45708377/82293510-54db2600-99b5-11ea-9224-aff229b60e75.png)
So you still can change clothes color.

**Comment by SlayksWood** [comment]
or we should add possibility to add persistent color to new clothes. But I think this is not for 0.9.0

**Comment by keegan-o** [comment]
Ah right, it would be good to still allow you to tint things for now.
