### ISSUE TITLE
[0.9.0 staging-1542] Contract Board no access to Treasury

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16397]
![image](https://user-images.githubusercontent.com/47274045/82364954-4837eb80-9a10-11ea-8bd8-582e156d2aa2.png)
Based on my Title  i have access to the Treasury, but I'm not able to create contracts using the Treasury for payment.

In this regards, what happens if i create a contract using an bank account which is managed by an elected title, and i lose the title before the contract is been finished. Is the contract still been paid or do the contract run into a failure, as me as contract owner does not have access to the bank account any more?

My recommendation to be able to change the contract owner as well to an elected title, so if the player changes of the title, the contract continue and go over to the new title holder....

**Comment by beastyn** [comment]
@john do we want to give an access for the treasury for the contract boards, parties and stores?
It seems to be reasonable.

@Alteraner contract won't fail, it wil still use government account and take money from there.
For now, working with the goverment account is on the person's conscience.

**Comment by Alteraner** [comment]
@beastyn thanks for your replay, I'm quite sure that in past you have been able to use the treasury for contract.

**Comment by johnkslg** [comment]
Yes it should do that (used to)
@olegshegai check that its querying Government Account and Government Access on the client, its probably only doing this in a couple places buts needs to be refactored to be done in all cases, using one system.
