### ISSUE TITLE
[0.9.0 staging-1554] Strange flying coins in mint

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16391]
![image](https://user-images.githubusercontent.com/45708377/82326602-c59a3680-99e5-11ea-834f-b6823b092daf.png)

https://drive.google.com/file/d/1Zi9NZd-kd75MLcru4FBVM4yTlEkgsxsZ/view?usp=sharing

**Comment by RobertMangano** [comment]
the coin bone goes down into the bag, and then the next frame it should appear under the press, maybe I might need to reanimate the coins some other way if it cant be fixed

**Comment by RobertMangano** [comment]
i am going through altering the animation now
