### ISSUE TITLE
[0.9.0 staging-1542] Loan contract failure crash the client

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16398]
Having a Law to recive all propertys by failed loan contract throw client exception and crashes the client:
Law:
![image](https://user-images.githubusercontent.com/47274045/82368440-b92dd200-9a15-11ea-9ac5-9f667e230be9.png)

Contract:
![image](https://user-images.githubusercontent.com/47274045/82368527-dfec0880-9a15-11ea-8f90-025a42d39309.png)

Error:
![image](https://user-images.githubusercontent.com/47274045/82368338-8e437e00-9a15-11ea-93a3-500ae4228d6e.png)

**Comment by beastyn** [comment]
@Alteraner thank you for the report.
I could not reproduce it.
Did you mark a contract as failed and after that you had a crash? 
And why do you try to take a property from the client? Its a person who gave the money.

In this case I have an error like this
![bandicam 2020-05-21 14-51-59-506](https://user-images.githubusercontent.com/27898520/82547130-a977d000-9b72-11ea-86cd-a97408d098a6.jpg)

And no crash.

@johnkslg can you take a look?

**Comment by Alteraner** [comment]
I give a loan to some one else. He failed to pay back the money in time. So I mark the contract as failed. The law should give me the clients property to have something adequate for the missing money.

The idea is to secure the loans with that law, otherwise there will no punishment to pay pack the money for the client.

**Comment by WeaselDog** [comment]
Just to clarify, the client is the person who is issuing the loan. For this law you would want to take property from the contractor. 😉

We are still looking into what is causing the issue.

**Comment by Alteraner** [comment]
Person A is offering a loan an Person B is taking this offer. Person B is not paying back the monay so Person A is clicking "contract failed". By click this, the client crash.

the Law says, if contract failes all propertys of Person B is going to Person A.

**Comment by johnkslg** [comment]
Few notes:
'Client' may be the lender (if its a loan) or the borrower (if its a bond). What you want is 'Borrower', which is available:
![image](https://user-images.githubusercontent.com/3536496/82602579-29e40400-9b66-11ea-9813-78c46b68cdaa.png)

I made this law and took a loan:
![image](https://user-images.githubusercontent.com/3536496/82603747-1043bc00-9b68-11ea-8471-af423ad2b0fb.png)

After default on the loan, it took effect:
![image](https://user-images.githubusercontent.com/3536496/82603704-fd30ec00-9b67-11ea-9a97-58b5e42a7633.png)

So everything seems to be working great.

**Comment by Alteraner** [comment]
Hello,
 great, i will test it as well. So i have created the law in a wrong way. Thanks.

Maybe it makes sense to check the exception eather, as an wrong made law should not throw an exception, better an error or just won't work.

**Comment by beastyn** [comment]
@Alteraner and it will not give any exceptions now. It will take property from the client now - a person who gave the money.
So, with this kind of law this kind (loan shark) person will not only lose his money, but lose his property too.
So, be careful. Maybe we will need to change this client-contractor names for something like  employer - employee...
