### ISSUE TITLE
[0.9.0 staging-1554] Global Illumination is very dark

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#16402]
**Version**: 0.9.0 staging-1554
**Steps to reproduce**: 
1. Be indoor
2. Put some braziers and/or fireplaces in the room
3. Wait until nighttime
4. Switch between GI off and low,medium,high,ultra

GPU: RTX 2070 Super

GI off:
![GI_OFF](https://user-images.githubusercontent.com/39825431/82384590-7af1dc00-9a30-11ea-88ba-c82be7c4d277.jpg)
GI low:
![GI_LOW](https://user-images.githubusercontent.com/39825431/82384603-80e7bd00-9a30-11ea-9bcc-49e26081f3c8.jpg)
GI medium:
![GI_MEDIUM](https://user-images.githubusercontent.com/39825431/82384609-8513da80-9a30-11ea-8b9f-86a828c8f972.jpg)
GI high: 
![GI_HIGH](https://user-images.githubusercontent.com/39825431/82384622-880ecb00-9a30-11ea-8be1-681618e76a08.jpg)
GI ultra:
![GI_ULTRA](https://user-images.githubusercontent.com/39825431/82384632-8cd37f00-9a30-11ea-90fe-2e8ccbb0ec39.jpg)

My other settings:
![Graphics Settings](https://user-images.githubusercontent.com/39825431/82384641-90ff9c80-9a30-11ea-9499-5a44a7246898.jpg)

**Comment by SlayksWood** [comment]
merged to #14766
