### ISSUE TITLE
Put news to open on a button

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16401]
News should be closed by default, and opened with a button
If there's new news since you last viewed, add an explanation point
Make the news fully opaque when opened
Get the button (a newspaper icon) and placement from milenko

**Comment by elfl0rd** [comment]
can you also add an option to turn off the news?
because since they're only English, they don't make sense to many players.

**Comment by MishkaFur** [comment]
> 
> 
> can you also add an option to turn off the news?
> because since they're only English, they don't make sense to many players.

Perhaps an option for language so have it English, Russian, German, French ie some of the main ones of the playerbase?

**Comment by elfl0rd** [comment]
> > can you also add an option to turn off the news?
> > because since they're only English, they don't make sense to many players.
> 
> Perhaps an option for language so have it English, Russian, German, French ie some of the main ones of the playerbase?

As you can see - https://github.com/StrangeLoopGames/EcoSuggestions/issues/1037
"moved to suggestions" and "wordpress backend is not able to do multilanguage without a lot of changes that would take incredibly long for little benefit"

In this case news should be able to disable.

**Comment by gzatravkin** [comment]
As I think the main consideration is translation.
@D3nnis3n we can left wordpress as it, but redact news in json or any similar format. And client will parse and choose correct lang, like that:

"eng" : "English 12312312312312312\n123123123\n",
"ru": "Русский 123123123123123\n" etc

**Comment by D3nnis3n** [comment]
I'd prefer to not do deal with any form of JSON.

We also do not provide changelogs nor main news in a variety of languages either. The news inside Eco are meant to be small, i don't think they need any translation - we do not even officially support any other languages. Not to mention i'm not aware of anyone of us speaking any of the mentioned languages despite german and russian.

But if we do it, the backend of Wordpress should be adapted so the actual news on the website itself can also be translated, including the Eco Tree and other stuff. I don't like half-baked solutions. In the end i'll have ingame news in four languages linking to one english article on the website - that's useless.

**Comment by mirasrael** [comment]
For different language support you can make suggestion. It is out of scope of the issue.

**Comment by johnkslg** [comment]
Added https://github.com/StrangeLoopGames/EcoIssues/issues/16506

**Comment by beastyn** [comment]
1) Icon is not clickable (just somewhere aroung a number)
2) Nothing was opened

**Comment by SlayksWood** [comment]
I can open it only with this steps:
- open game, I can't expand news:
![image](https://user-images.githubusercontent.com/45708377/84473922-8c767e80-ac92-11ea-93d9-57977501e041.png)
- join to any server, disconnect. Now I can expand news:
![image](https://user-images.githubusercontent.com/45708377/84474053-dc554580-ac92-11ea-99ca-b2add327f5bc.png)
- open another game menu (Your worlds for example), go to main menu again. I can see small Econew icon under News when it loads:
![image](https://user-images.githubusercontent.com/45708377/84474181-1d4d5a00-ac93-11ea-9df8-74dff27c8ff3.png)
 
Do we have any ability to collapse news?

**Comment by gzatravkin** [comment]
Should be possible to expand now. And removed this econew semitransporent. 

No, we don't have collapsing. Don't seems necesarry since it don't blocks anything interactive.

**Comment by beastyn** [comment]
Can't expand in localization
Russian-Russian

**Comment by SlayksWood** [comment]
Still an issue, I can't open news after just game starting
