### ISSUE TITLE
USER ISSUE: Glass Textures Don't Connect

### ISSUE THREAD

**Issue by binaryclock03** [StrangeLoopGames/EcoIssues#16400]
**Version:** 0.9.0.0 beta staging-1542

**Steps to Reproduce:**
Place down regular glass panes or horizontal glass panes

**Expected behavior:**
It should have connected the textures between the glass panes

**Actual behavior:**
Instead it shows ugly textures between the panes of glass.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Comment by elfl0rd** [comment]
Duplicate of #13940
