### ISSUE TITLE
[0.9.0 Staging-1554] ServerCrash / cannot start server after update

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16409]
Hello,
 with the update to the new version the server is not able to start. I got the following error and the server stops.

![image](https://user-images.githubusercontent.com/47274045/82424545-9fc46e80-9a85-11ea-9138-327968131e08.png)

[ServerCrash AggregateException 05201219.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4655595/ServerCrash.AggregateException.05201219.zip)

**Comment by SlayksWood** [comment]
> Old Savegame
> https://drive.google.com/open?id=1-X1EQ00XDo6JaRzm8pFhL9v6gNcWzVAe
