### ISSUE TITLE
[0.9.0 staging-1555] Can't see districts in web

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16406]
Just black planet:
![image](https://user-images.githubusercontent.com/45708377/82415288-faa79700-9a80-11ea-9000-a7fe68a67555.png)

**Comment by gzatravkin** [comment]
This looks like duplication of https://github.com/StrangeLoopGames/EcoIssues/issues/15959.
Anyway should be fixed after https://github.com/StrangeLoopGames/Eco/pull/6147
