### ISSUE TITLE
[0.9.0 Staging-1554] - Missing Icons

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16404]
Storage Component:
![image](https://user-images.githubusercontent.com/48172405/82389627-99f26d00-9a34-11ea-92b8-1834591937b2.png)
![image](https://user-images.githubusercontent.com/48172405/82389665-b0002d80-9a34-11ea-9658-160338f41ac6.png)

Change Reputation:
![image](https://user-images.githubusercontent.com/48172405/82389438-16d11700-9a34-11ea-9a1a-b274fc165ef8.png)

Wood Signs of both sizes and types:
![image](https://user-images.githubusercontent.com/48172405/82389976-5c421400-9a35-11ea-932b-92e3918ed4b8.png)

Plastic:
![image](https://user-images.githubusercontent.com/48172405/82390663-37e73700-9a37-11ea-8e10-4989699d1931.png)

Bank Accounts, Civic Articles, etc:
![image](https://user-images.githubusercontent.com/48172405/82391218-b1335980-9a38-11ea-8c67-a414567b8672.png)

Tags - Climate, Modern Research, Raw Food, Silica:
![image](https://user-images.githubusercontent.com/48172405/82391319-edff5080-9a38-11ea-8efe-b873027a17aa.png)

**Comment by trickenso** [comment]
Text component:
![image](https://user-images.githubusercontent.com/48172405/82394056-d6779600-9a3f-11ea-87e8-f9e40d078560.png)

**Comment by SlayksWood** [comment]
component icons #15893

**Comment by serpopov** [comment]
@WeaselDog I did fix half, could you handle others?

**Comment by WeaselDog** [comment]
@serpopov Yeah I will see what is going on

**Comment by WeaselDog** [comment]
Blocked by https://github.com/StrangeLoopGames/EcoIssues/issues/16588

**Comment by trickenso** [comment]
Citizen and Citizen Timer have no icon in 1605:
![image](https://user-images.githubusercontent.com/48172405/84955122-9531df00-b0ee-11ea-815d-526eee19b771.png)
