### ISSUE TITLE
[0.9.0 staging-1556] Biome Generation problems

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16415]
we missing ocean and deep ocean:
![image](https://user-images.githubusercontent.com/45708377/82433353-fc318900-9a99-11ea-9ce4-6072b6109af2.png)
![image](https://user-images.githubusercontent.com/45708377/82433366-005da680-9a9a-11ea-85f8-77c379a8358a.png)

Under water we have other biomes:
![image](https://user-images.githubusercontent.com/45708377/82433388-094e7800-9a9a-11ea-91bc-bce90bfa6762.png)
![image](https://user-images.githubusercontent.com/45708377/82433408-0f445900-9a9a-11ea-8180-52fb58d1a2ff.png)
![image](https://user-images.githubusercontent.com/45708377/82433422-153a3a00-9a9a-11ea-938b-10b26cbf5e6c.png)
![image](https://user-images.githubusercontent.com/45708377/82433430-19665780-9a9a-11ea-821b-198210935ef2.png)
![image](https://user-images.githubusercontent.com/45708377/82433449-1e2b0b80-9a9a-11ea-967f-e75086e128a5.png)

It was broken recently. We have good generation on playtest (14 days ago), but it was not broken by last @StanKryvenko changes. It was broken yesterday too.

**Comment by WeaselDog** [comment]
I still have this issue. Was there something that fixed it that is not merged yet?

**Comment by beastyn** [comment]
Fixed can be placed for tracking fixed issues. We don't have merged PR for it yet
