### ISSUE TITLE
[0.9.0 Staging-1554] Exception when revising law

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16414]
Click revise law, got disconnected with exception:
![image](https://user-images.githubusercontent.com/982322/82432855-eb304a00-9a90-11ea-8fbe-5e8bdfc0fac4.png)

Worked the second time.

**Comment by SlayksWood** [comment]
@henrikolsson provide log file please.

**Comment by henrikolsson** [comment]
Player.log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4656098/Player.log)

**Comment by SlayksWood** [comment]
merged to #15378
