### ISSUE TITLE
0.9 staging - polution data placed inside status messages.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16410]
As I think it should be like
status messages
space
pollution data

not like this
![изображение](https://user-images.githubusercontent.com/4980243/82426131-21b99500-9a90-11ea-9913-a2e435a9beb4.png)

also status data should be first.
At steam truck - ok
![изображение](https://user-images.githubusercontent.com/4980243/82426295-54fc2400-9a90-11ea-9cdc-a42ffde83dde.png)

at truck - bad
![изображение](https://user-images.githubusercontent.com/4980243/82426319-5cbbc880-9a90-11ea-80fe-0f51662bbd2a.png)

**Comment by mirasrael** [comment]
It has random placement now.

**Comment by elfl0rd** [comment]
> It has random placement now.

understandably

I think that this data should be placed outside the block with status messages.

**Comment by mirasrael** [comment]
I think we need a way to prioritize (order) status messages. It is issue not only with pollution stats.

**Comment by elfl0rd** [comment]
Agree about status, but in any case pollution data is different, and should be outside :)

**Comment by trickenso** [comment]
Statistics component?

**Comment by johnkslg** [comment]
For now just stick a priority tag that can be set on statuses to sort them
Later we'll do a proper statistics component
