### ISSUE TITLE
[9.0 1554] Server unable to load after update

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16417]
Server is unable to load after the update, this is from the "old old" royal otter world which I hosted for a while due to further testing going on.

Server was still working fine before the 1554 update (other than being flooded), worldfile can be sent over discord if need be @mishka#1337

This could just be a remnant of all the other issues that world DB had.

![image](https://user-images.githubusercontent.com/61889138/82436717-2da45780-9a8e-11ea-8d14-54ee046f29d7.png)

![image](https://user-images.githubusercontent.com/61889138/82436735-36952900-9a8e-11ea-9229-db243256f5d5.png)

**Comment by SlayksWood** [comment]
@MishkaFur 
It would be nice to provide save files here. Or sent it to JohnK#2378 in discord with link on this issue.

**Comment by MishkaFur** [comment]
File sent to JohnK via Discord :)

**Comment by johnkslg** [comment]
Fixed!
