### ISSUE TITLE
[0.9.0 Staging-1554] Unable to enter numbers with decimals in laws

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16411]
Neither "," or "." works for entering decimals in laws. After finishing input the game removes them.

Video showing the issue:
https://www.dropbox.com/s/hwfjvw7u1akyqlh/Eco%202020-05-20%2011-47-07.mp4?dl=0

**Comment by beastyn** [comment]
Thank you for the report.
Can you give a log file and save?
I can't reproduce it wil the later version.

**Comment by henrikolsson** [comment]
This is on royal otter so i don't have a save file. Here's my log, i'm not sure if it's still the right one: 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4658814/Player.log)

**Comment by trickenso** [comment]
I wasn't able to do this yesterday on Royal Otter, but on a single-player 1554 world now it's working fine:
![New Bitmap Image](https://user-images.githubusercontent.com/48172405/82565877-083d4980-9b73-11ea-9533-9a628a7cc60f.png)

**Comment by henrikolsson** [comment]
I am able to recreate it locally.  Here's logs and save:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4662967/Player.log)
[decimal world.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4662969/decimal.world.zip)

I did notice something weird though, the description of the law has the decimal entered even though the amount-box doesn't. Locale formatting issues maybe?

![image](https://user-images.githubusercontent.com/982322/82569515-a388eb80-9b80-11ea-94b3-cfc4b571ba36.png)

**Comment by henrikolsson** [comment]
I switched my windows region from Sweden (uses comma for decimals) to UK (uses period for decimals) and it started working. So it has something to do with locale formatting.

**Comment by trickenso** [comment]
I'm using UK settings - this follows for me, also.

**Comment by johnkslg** [comment]
Was this one you just fixed here https://github.com/StrangeLoopGames/EcoIssues/issues/16419

**Comment by beastyn** [comment]
Should be fine with update
