### ISSUE TITLE
[0.9.0 staging-1559] ColdForestSoilBlock has wrong model

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16426]
when alone:
![image](https://user-images.githubusercontent.com/45708377/82530890-fba2fc00-9b46-11ea-9012-f65c61f52c85.png)
![image](https://user-images.githubusercontent.com/45708377/82530898-ff368300-9b46-11ea-8311-9ee09a752dee.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82607033-eccf4000-9b6c-11ea-92fc-4829f7e2dc84.png)
fixed in staging
