### ISSUE TITLE
Repeated tooltip 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16424]
![image](https://user-images.githubusercontent.com/3536496/82503988-3194a180-9aaf-11ea-9ac1-dd26663de99d.png)

**Comment by SlayksWood** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/45708377/82544243-83940080-9b5d-11ea-9178-ccec4df9ba40.png)

**Comment by SlayksWood** [comment]
Have today here:
![image](https://user-images.githubusercontent.com/45708377/82796304-fd89f980-9e7d-11ea-8033-65d19c877df8.png)

**Comment by SlayksWood** [comment]
Seems fixed
