### ISSUE TITLE
[0.9.0 staging-1559] Contractor vs Client round 2

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16427]
It seems I was sleeping when I checked this the last time, or something went wrong.
![image](https://user-images.githubusercontent.com/45708377/82532011-1d04e780-9b49-11ea-86a0-badad4495498.png)
![image](https://user-images.githubusercontent.com/45708377/82532293-b92eee80-9b49-11ea-8bf8-7bd9847f8dc3.png)
![image](https://user-images.githubusercontent.com/45708377/82532424-0743f200-9b4a-11ea-91dd-804f85b73bd9.png)

**Comment by WeaselDog** [comment]
Ah will get this fixed. Thanks for catching it.
