### ISSUE TITLE
Basic Engineering Road tool issues

### ISSUE THREAD

**Issue by LightOracle** [StrangeLoopGames/EcoIssues#16420]
Stamping dirt should level Basic Engineering like hoeing does for farmers. It also cost way to much in materials compared to the other steel tools the smelter makes for an advanced profession? Why make it so hard for the Basic Engineer to make roads when it's already a job not many people like doing? You spend a lot of food making a road that is barely faster then walking on dirt.

**Comment by WeaselDog** [comment]
Thanks for the report! We have lowered the cost of Steel Road Tool and are planning to add the ability to gain experience in a future update.
