### ISSUE TITLE
why are the FPS so bad GTX 1080 32gb ram I7 6800K + ALT + Z not customizable for removing UI

### ISSUE THREAD

**Issue by lucderoover** [StrangeLoopGames/EcoIssues#16421]
i really dont get why its optimised so poorly u should focus allot more on fps i t doesnt matter on lowes or highest grapics its 90fps after 5 min 30fps if lucky and 15 fps or lower the longer u play if u disconect it does not fix the fps only if u close the game and start it back up, 1) are you caching and not unloading cached data that is not used for a while, 2) why is this all server calculations and does this make the game sutch terrible fps, 3 if it client side implement more pc performance utilizations i know this is not minecraft but dam i bet a tripple TITAN X with 128GB ram and a I9 even plays at this bad fps i got a monitor of 200hertz and all under 60fps is lag but <30 on a beast pc is just redicuelous u guys are losing player base just because of the bad optimization put your priorities right or hire a company that can help fix this(no offence) but i bought it in alpha and the performance even are waaaaay worse the when it came out u should not at any features until u fix the godam FPS ty,

**Comment by lucderoover** [comment]
also pls change hiding the UI and showing it with ALT + Z i got an azerty keyboard and i use z to walk forward and alt as sprint ket for my thumb or give me the option to change the keybind ty :)

**Comment by MishkaFur** [comment]
What resolution do you have
Can you screenshot your graphics settings

If your FPS does not change when going lowest to highest then something else is possibly affecting it.

**Comment by revtje** [comment]
Since the last update I cannot get over 38 fps no matter what I do in the graphics settings. In the main menu I get 90 fps and GPU load at 96% but when loading into the server I only get 38 fps. GPU load about 30%
Turning all graphics sliders to the minimum or maximum does not matter I still only get 38 fps.

I have tried reinstalling (+ deleting all settings from appdata). Tried different GPU drivers. 

I have an i5-9600K, 32GB RAM and RTX 2070 Super
CPU load is at 40%

This happened in this version: [0.9.0 Staging-1554]
It was good in: [0.9.0 Staging-1542]

**Comment by SlayksWood** [comment]
add about alt+z here #14479

**Comment by SlayksWood** [comment]
@lucderoover Thank you for the report. We know about problem with FPS and try to fix it in 0.9.0.

If you really want to help us, then provide more information.
1. Game version. 
2. Log files. If there are any exceptions, this may cause FPS drawdown. 
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Try changing the graphics settings and provide CPU GPU and RAM usage. The best way will be screenshots. 

You can get access to test 0.9.0 in Discord from our community manager.

**Comment by SlayksWood** [comment]
@revtje move your comment to #16142

**Comment by SlayksWood** [comment]
We have a lot of certain issues to FPS improvements, so closing for now, reopen when you can provide us with necessary information.
