### ISSUE TITLE
[0.9.0 Staging-1559]  Civics: can use a bank account when should not 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16429]
1. Create an Elected Title 
![bandicam 2020-05-21 15-12-11-200](https://user-images.githubusercontent.com/27898520/82551611-f317e900-9b79-11ea-9b27-158ce4083325.jpg)
2. Occupy it
![bandicam 2020-05-21 15-15-50-814](https://user-images.githubusercontent.com/27898520/82551642-0034d800-9b7a-11ea-9329-80450588d8a2.jpg)
3. Create a bank accout and assign the Title as a manager. Remove yourself too.
![bandicam 2020-05-21 15-16-15-803](https://user-images.githubusercontent.com/27898520/82551718-2a869580-9b7a-11ea-9497-2003765757e1.jpg)
4. Place a contract board and choose  the created bank account
![bandicam 2020-05-21 15-16-46-480](https://user-images.githubusercontent.com/27898520/82551798-5275f900-9b7a-11ea-8118-221fe226603d.jpg)
5. Delete this contract
6. Resign from office
7. Check, if you still have this bank account. You should not
![bandicam 2020-05-21 15-17-26-758](https://user-images.githubusercontent.com/27898520/82551832-628dd880-9b7a-11ea-90bd-ae2ef47bb77d.jpg)
8. Go to a contract board and try to create a conttract with created bank account
![bandicam 2020-05-21 15-17-44-479](https://user-images.githubusercontent.com/27898520/82551876-7b968980-9b7a-11ea-8ed7-b1ae6c4d0367.jpg)

You still see it, but you should not.

**Comment by johnkslg** [comment]
Not updating AccessibleAccounts for users on removal of a bank account probably.
