### ISSUE TITLE
Notifications controller is making 18K allocations per update and killing frame rate

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16434]
![image](https://user-images.githubusercontent.com/3536496/82589115-83413880-9b50-11ea-8b9d-9b9a958a6d38.png)
Allocations in updates should be zero. Looking at the update function, it looks like everything in there can be made to be event-based instead of polling.

**Comment by gzatravkin** [comment]
Optimizated so it creates few garbage. It still uses update instead of events so it won't update text more than 1 time for frame
