### ISSUE TITLE
[0.9.0 Staging-1554] - Minor Text/Icon Tweak - Tilled dirt missing icon and localisation text

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16432]
![New Bitmap Image](https://user-images.githubusercontent.com/48172405/82582854-94a73680-9b8a-11ea-82fa-c33fdea33c0f.png)

**Comment by SlayksWood** [comment]
@WeaselDog or maybe it shoould display Dirt intead TirredDirtBlock like for another Dirt:
![image.png](https://images.zenhubusercontent.com/5ec772b67a4d1abf650e1d9d/e63f8fc6-5490-4d7a-81e3-94b648a07083)
![image.png](https://images.zenhubusercontent.com/5ec772b67a4d1abf650e1d9d/0f1f54cf-d903-4084-955f-211eee0dad34)
