### ISSUE TITLE
Law spam

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16435]
2. Spam from law notification in chat. Step to reproduce:
- create law like this:
![image](https://user-images.githubusercontent.com/45708377/82206814-92867300-9911-11ea-9b0f-8da1ef09304e.png)
- start to place something 3 times. I have very strange notifications (I have civics debug off):
![image](https://user-images.githubusercontent.com/45708377/82206221-83eb8c00-9910-11ea-8a21-1407363fcb3a.png)
- if you place it very fast it can appear here:
![image](https://user-images.githubusercontent.com/45708377/82207010-da0cff00-9911-11ea-8a2b-a333808a0faa.png)

3. Notification from executive office. Step to reproduce:
- create executive action like:
![image](https://user-images.githubusercontent.com/45708377/82208825-e5155e80-9914-11ea-8cf4-3fd05dc2f3ec.png)
- /civics winelection. This notification doesn't always appear:
![image](https://user-images.githubusercontent.com/45708377/82208797-d9c23300-9914-11ea-90ca-0e19f7bf298d.png)
- I can't see it in chat only in tooltip:
![image](https://user-images.githubusercontent.com/45708377/82209121-6967e180-9915-11ea-94ae-ce36c29b5883.png)

**Comment by johnkslg** [comment]
Fixed! Nice find.

**Comment by johnkslg** [comment]
Reworked the spam into something different, let me know your thoughts and we can iterate on it (create a new bug plz for more comments).

The bug about text not appearing is in Grigori's court.

**Comment by johnkslg** [comment]
New state:
- Laws will display what they did, EXCEPT for broadcasting a message that includes the triggering player.
- Laws will tell why they did something (the condition), UNLESS it's a context variable (ie, 'dropped')

**Comment by SlayksWood** [comment]
Make law like 
![image](https://user-images.githubusercontent.com/45708377/82660638-67629300-9c33-11ea-8c0e-3d8538782560.png)
try to build by line
![image](https://user-images.githubusercontent.com/45708377/82660688-7c3f2680-9c33-11ea-9464-9f413e342015.png)
I will have 11 notifications. Will be fine to combine it.
If I use tax instead send notice:
![image](https://user-images.githubusercontent.com/45708377/82660950-c3c5b280-9c33-11ea-9bf6-e7c15f27df60.png)

Would be better like Slayks paid 10 times each 1 (Slayks Credit) into Treasury for: Tax from Law 3.
Or maybe you can find another option.

**Comment by beastyn** [comment]
Its in a sepa
