### ISSUE TITLE
Contracts/work parties all blending together

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16436]
![image](https://user-images.githubusercontent.com/3536496/82602665-4bdd8680-9b66-11ea-8521-b1f3bdff1de5.png)

**Comment by MilenkoTunjic** [comment]
Space text rows vertically so there is a bit more breathing space between the rows.
In the UI_Elements sprite sheet, there is a new sprite added to the top-middle part. use it as a background frame for each individual contract, so they all sit in their individual frames.
![UI_Elements_LASTMAY22](https://user-images.githubusercontent.com/14243410/82619038-227d3300-9c18-11ea-9cd4-608218826f81.jpg)

**Comment by gzatravkin** [comment]
![image](https://user-images.githubusercontent.com/53317567/83317473-4a196000-a203-11ea-92d1-fb7a06053f70.png)
