### ISSUE TITLE
Civics Feature Request - Propose changed or new civic based on failed or deleted versions

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16431]
If a proposal is removed or fails an election it can be viewed, but if you want to redraft or propose it again you need to remake it from scratch.

An option to directly edit/resubmit the failed or removed civic would be useful, especially with complex district maps.

**Comment by beastyn** [comment]
Yeah, we were talking about something like archive for deleted and failed objects

**Comment by IcedForge** [comment]
Its not apparent i believe but this feature already exists in current version of the game.
You need to click "revise/draft" exit draft then you can click that little button on image below to fetch a list of all laws, same goes for districts, demographics etc.

![Screenshot_59](https://user-images.githubusercontent.com/24981362/95314881-1d9ce100-0892-11eb-9bf1-2625a857022c.jpg)
![Screenshot_60](https://user-images.githubusercontent.com/24981362/95314887-1ece0e00-0892-11eb-906d-4933e44c6f3f.jpg)
