### ISSUE TITLE
quantity selection ugliness

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16437]
![image](https://user-images.githubusercontent.com/3536496/82602844-8b0bd780-9b66-11ea-94cb-422acf12a981.png)
Need to make these quantity selectors all use the nested prefab system so they can be fixed in one chunk. This is the debt repayment dialog.

**Comment by SlayksWood** [comment]
I can't see Bank account names when try to select it:
![image](https://user-images.githubusercontent.com/45708377/84751551-5eac7500-afc5-11ea-8e37-75666ed2668d.png)
same for transfer UI:
![image](https://user-images.githubusercontent.com/45708377/84751709-8b608c80-afc5-11ea-8c44-efaf3ec6a303.png)

**Comment by SlayksWood** [comment]
#16682
