### ISSUE TITLE
Staging Alpha 5.6 #Bb668640 Table requirements not being meet when they are table still work even though error

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1644]
Double doors tables still work but gives status error as shown in screen shoot.  or maybe its the whole in wall that separates the two rooms ?

![20170610152649_1](https://user-images.githubusercontent.com/15990789/27006082-657c88e0-4df1-11e7-9627-5a826598136b.jpg)

**Comment by MGrand3** [comment]
Not sure if this has changed, but I think a 1x2/2x1 is the biggest gap you can have in a wall/roof/floor for the game to count it as a valid room.

**Comment by midn8t** [comment]
but door fills gap and how else suppose to get a cart in or out original i posted idea of a big door like this garage door and developers said this was how it was suppose to be done by putting two doors to gather.

**Comment by MGrand3** [comment]
I was more referring to the gap on the left of your picture, which looks like it's 3 high.

**Comment by midn8t** [comment]
o well its not its only 2 high that is anther door way just with out the door

**Comment by metachronism** [comment]
this should be fixed in the upcoming staging (or at least, the real error preventing work will be correctly displayed)
