### ISSUE TITLE
[0.9.0 staging-1554] Bank account preview in shops

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#16443]
Have access to a different bank account
Visit someones shop
Your balances are shown at the bottom:
![image](https://user-images.githubusercontent.com/54982803/82641436-3cad1600-9c04-11ea-8683-e1d2ceab889b.png)
Change the bank account, the balance does not update:
![image](https://user-images.githubusercontent.com/54982803/82641489-50f11300-9c04-11ea-91bd-4df1b7848c57.png)

It does update if you modify the buy/sell counts:
![image](https://user-images.githubusercontent.com/54982803/82641606-7e3dc100-9c04-11ea-855a-cc5c2106baa9.png)

It does not update until you sell if you change the account after making a shopping list. Personally this is the orientation I do this as this is the order they are presented:
![image](https://user-images.githubusercontent.com/54982803/82641691-a9c0ab80-9c04-11ea-9e6d-5c7176cc3c8d.png)

**Comment by beastyn** [comment]
dup #16128
