### ISSUE TITLE
[0.9.0 staging-1554] Possible to violate property rights at world seam

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#16448]
User Amarok found this issue on my server and I reproduced it according to the steps below.

When a claim is placed just next to the world seam (where the coordinates wrap) it is possible to stand on one side of the seam and manipulate blocks on the other side, even though that side is claimed and you have no access to it.

Steps to reproduce:
1. Place a claim as close to the world seam as possible (we tested with the Z-axis).
2. Place a block at the absolute last (or first) coordinate so that it has a face that is accessible while standing on the other side of the seam.
3. Use the property owner command to remove all your access from the claim.
4. Place yourself on the side of the seam so that the block and you are on opposing sides.
5. Hammer the block.
6. Notice that you were allowed to do this, even though you have no authorization.

Unlisted Youtube video
https://www.youtube.com/watch?time_continue=1&v=nRzVY6DaXmI&feature=emb_logo

**Comment by SlayksWood** [comment]
object should be 718-719 (in 0,52 world) coordinate. You should be on 0 or 1. If it's opposite this is not working

**Comment by MonzUn** [comment]
Thanks for the clarification, shouldn't have assumed it worked both ways.
