### ISSUE TITLE
[0.9.0 staging-1561] Animals: predators are ignoring you

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16449]
https://drive.google.com/file/d/1vxcNJHJvgAZxur5jx6gQNwAXn2TAHcSD/view?usp=sharing
https://drive.google.com/file/d/134741vZiWhS5sCvnQhf_enI952pg-Buu/view?usp=sharing

**Comment by SlayksWood** [comment]
Still an issue. Predator in 95% cases will ignore you

**Comment by beastyn** [comment]
Still and issue in long wander distance. Will fix here #17137
