### ISSUE TITLE
[0.9.0 staging-1561] Can't use steam tractor plow after renaming.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16444]
I can install it but plow doesn't display.
![image](https://user-images.githubusercontent.com/45708377/82646334-1b0c5880-9c1d-11ea-96dc-a9fca02bb215.png)

**Comment by WeaselDog** [comment]
This was working for me on local. To fix this it is in the Steam Tractor prefab. Must change the name of Steam Tractor Plough to Steam Tractor Plow.

**Comment by WeaselDog** [comment]
Fixed in SVN
