### ISSUE TITLE
[0.9.0 staging-1561] Animals: twisted bodies on uneven surface

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16446]
They are broken
![bandicam 2020-05-21 17-13-40-914.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/bd703890-2b49-46c9-8630-0d74d622ba62)

**Comment by johnkslg** [comment]
Getting animals to look good as they navigate twisted terrain is an extremely difficult task. Really, they shouldnt be pathing on this terrain.  We will address this in a future update.  Mark closed for now and we will revisit with an animal upgrade.
