### ISSUE TITLE
Mechnical pump input not detecting nearby pipe

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16456]
![image](https://user-images.githubusercontent.com/3536496/82692107-f495ef80-9c13-11ea-8e96-39215fe3af38.png)

**Comment by SlayksWood** [comment]
@johnkslg 
it's only happen with new spawn command. If you replace water pump then al will be fine.

**Comment by johnkslg** [comment]
k nvm
