### ISSUE TITLE
[0.9.0 staging-1561] Work Party notifications are underline

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16455]
Seems something tries to fouldout it:
![image.png](https://images.zenhubusercontent.com/5ec772b67a4d1abf650e1d9d/e9c6fdc1-3b1d-41ac-b4f5-1a4b336e97c0)

**Comment by SlayksWood** [comment]
Still have problem with notification:
![image](https://user-images.githubusercontent.com/45708377/84484168-0b73b300-aca3-11ea-8db5-18783d04c168.png)

**Comment by johnkslg** [comment]
@serpopov @gzatravkin you guys have been working with long notifications yes? Can you advise here

**Comment by gzatravkin** [comment]
looks like duplication of 
https://github.com/StrangeLoopGames/EcoIssues/issues/16371

**Comment by gzatravkin** [comment]
Will do it during this week with #16371. But anyway proabably it's just need to use LimitTextMaxWidth in tooltip text.

**Comment by serpopov** [comment]
seems not reproduced
