### ISSUE TITLE
[0.9.0 staging-1554] Misleading formulation in law species filter

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#16453]
When writing a law using the "With Species" section (such as "Harvest or Hunt"), the species list is unclear on whether the law requires the species to be "any" or "all" of the listed species.

I assume it's "any" as an animal or plant can't be of multiple species.
See the attached image for the formulation.

Reproduction steps:
1. Propose a law using the "Harvest or Hunt" event.
2. Add all animals to the "with species" section.
3. Note that the description now claims that the entity on which the "Harvest or Hunt" even is acting upon must be of ALL animal species.

![image](https://user-images.githubusercontent.com/11805935/82655029-df27c200-9c21-11ea-8897-be8a684d8e53.png)

**Comment by beastyn** [comment]
Thank you for you report,

For situations where you can use different type of selection we have specific field with "Has all"," Has Any" options.
For triggers it should be obvious that one action is one trigger. If you shoot- it's one action, We can't shoot in two animals at one time.
So, I think we can leave it like it is for now.
Maybe in the later releases we will change UI one more time with more clear description,

**Comment by MonzUn** [comment]
My point was more that I would have expected the text to always say "or" in this case as if the law is ready out loud, it becomes "On event Harvest or hunt where species is X, Y and Z", which is nonsensical as one animal can only be of one species.

It being nonsensical is what saves the formulation from actually being confusing.
The formulation in itself is still wrong, but as it wouldn't risk confusing players, I'd say it's still a bug but a low priority one.

That's just my opinion though of course :)
