### ISSUE TITLE
Staging Alpha 5.6 #Bb668640 issue with tables

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#1645]
some twit came along and used my table logged off..

now i cant use my table, like does not prioritize my stuff before his, his thing is at 100%..

also can not cancel his project by right clicking on it it does nothing I also can not use hammer on the table to delete it because it gives error that table is in use - so this is bit annoying.

**Comment by MarjieAVolk** [comment]
Hm, all the other behavior is expected, but your projects should be able to craft if theirs are done.  Are your projects being blocked?

We're considering whether/how to allow table owners to cancel all projects on their table

**Comment by midn8t** [comment]
yah they where at the time wouldn't start
