### ISSUE TITLE
[0.9.0 staging-1554] Potential item count indicator in crafting view does not update when inventory is changed

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#16451]
Found by moderator "GreenMoon" on my server and reproduced by me.

This probably stems from UI optimization, but if a user is looking at the crafting interface while the inventory is changed, the UI will not update the indicator telling the user how many items they could potentially craft.

Reproduction steps:
1. Have a crafting table and two stockpiles within range.
2. Link one of the stockpiles to the crafting table.
3. Put crafting resources in the linked stocpile.
4. Open the crafting UI and note the number of potential items that can be crafted from the resources in the linked stockpile.
5. Open the storage tab and move all the crafting resources to the unlinked stockpile.
6. Go back to the crafting tab and notice that the indicator still claims that you can craft the same amount of items, despite there no longer being any accessible resources.
7. Modify the amount of crafts for a recipe (arrow by the indicator) and note that the number of potential crafts is now correct for this recipe.

![image](https://user-images.githubusercontent.com/11805935/82653229-2e202800-9c1f-11ea-9a20-15498fc97fb5.png)
![image](https://user-images.githubusercontent.com/11805935/82653272-3ed09e00-9c1f-11ea-980b-4737a15b40d3.png)
![image](https://user-images.githubusercontent.com/11805935/82653315-4d1eba00-9c1f-11ea-8cd5-83bd88290752.png)
![image](https://user-images.githubusercontent.com/11805935/82653382-6a538880-9c1f-11ea-958e-04d7ac6e37f8.png)

**Comment by SlayksWood** [comment]
dup #16273

**Comment by MonzUn** [comment]
Thanks! Didn't find it when I searched.
