### ISSUE TITLE
[0.9.0 staging-1554] Multiple Servers - Graphs and data not visible

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16461]
Royal Otter graphs not accessible - cause unknown.

![unknown](https://user-images.githubusercontent.com/48172405/82735134-5d19c500-9d17-11ea-88ab-20f0cc24f58e.png)

Tested on Chrome and Firefox. Confirmed by two players.

**Comment by MonzUn** [comment]
Confirmed on my server as well.

**Comment by beastyn** [comment]
Thanks you, friends.
We need to update you first, as we have new graphs with 1555 version (everything is fine locally for me). 
Will prnding it for now.

**Comment by WeaselDog** [comment]
Closing as this was fixed with the new graphs. Please let us if you experience this issue again.
