### ISSUE TITLE
[0.8.3.3] Database: InvalidCastException

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#16463]
Hi, we currently have an issue with our game database.
Do you have any clue to resolve this ?
Best regards.

[log_200523082129.log](https://github.com/StrangeLoopGames/EcoIssues/files/4672221/log_200523082129.log)

Actual Behavior
- Since 5 days, we receive this error in the log file:
Error writing to stat database: InvalidCastException Unable to cast object of type 'LiteDB.IndexPage' to type 'LiteDB.DataPage'.

- Now the game seems broken, laws don't work anymore.

Steps to Reproduce the Problem
- No clue

Specifications
- 0.8.3.3

**Comment by SlayksWood** [comment]
@Twelve57 
Please provide save files. Instruction is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
