### ISSUE TITLE
[0.9.0 staging-1554] Animals: Fish stuck in player placed blocks

### ISSUE THREAD

**Issue by Bonsai555** [StrangeLoopGames/EcoIssues#16460]
Steps to reproduce:
I don't know. I just came back to the house i am building, after beeing (probably) out of render distance, when i found the fish. It does have a collision box.

Expected behavior:
Should not happen.

Actual behavior:
Fish is stuck in the floor/ceiling.

![grafik](https://user-images.githubusercontent.com/12842716/82723614-6fbcdb80-9cd0-11ea-95b5-f7a4535ee220.png)

Updated information:
Fish dissapeared after a few minutes

**Comment by SlayksWood** [comment]
Thank you for the report. This is the old bug.
merged to #7574
