### ISSUE TITLE
USER ISSUE: My giant brown tree

### ISSUE THREAD

**Issue by CrazyChick2019** [StrangeLoopGames/EcoIssues#16466]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I cut it near the beach

**Expected behavior:**
it shall fall down nicely

**Actual behavior:**
It fly to the space,but first it dance in water

**Do you have mods installed? Does issue happen when no mods are installed?:**
It fly to the space,but first it dance in water

**Comment by SlayksWood** [comment]
@CrazyChick2019 
Can you provide a little more information? may be video or gif.
Can you  reproduce it every time or have it just occurred several times?
Please provide log files when you meet it next time.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by CrazyChick2019** [comment]
Hello I post the video on my YT I’m MalkaRu and the vid is
https://YouTube.be/V2_qwatqfdy

בתאריך יום ב׳, 25 במאי 2020 ב-11:03 מאת Kirill <notifications@github.com>:

**Comment by beastyn** [comment]
@CrazyChick2019 thank you.
Is video still valid? Can't see it.

**Comment by WeaselDog** [comment]
Hi @CrazyChick2019. We are not able to access the video you linked. Are you still having this issue? We have made some fixes to how trees drop. This issue is marked to be closed due to inactivity, so please reply back if you are still having this issue. Thank you for your contribution.

**Comment by CrazyChick2019** [comment]
Hello it’s all good I found my tree still giggling around the map one time
I saw it in water in the middle of the ocean than eventually I found it on
beach coast and chop chop we won the game XD ty.The game was fun

בתאריך יום ג׳, 30 ביוני 2020 ב-20:34 מאת Todd <notifications@github.com>:

**Comment by WeaselDog** [comment]
Glad to hear
