### ISSUE TITLE
Text Link Issue in Building Tier Tooltip

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16465]
To replicate this, type Tier 4 in chat and hover over it.

![Tier](https://user-images.githubusercontent.com/47330823/82745852-f0fe8780-9d3d-11ea-84b5-7195ec018dcb.png)

We either need to remove the link or add an icon to hammer. The hammer tooltip is useful:
![Hammer](https://user-images.githubusercontent.com/47330823/82745878-1f7c6280-9d3e-11ea-93c2-85ed9138fcf3.png)

**Comment by SlayksWood** [comment]
@WeaselDog 
It looked pretty well, maybe we should just add an icon for hammer?
![image.png](https://images.zenhubusercontent.com/5ec772b67a4d1abf650e1d9d/00e7864d-9a7b-4196-b420-d13d335064e6)

**Comment by WeaselDog** [comment]
Fixed in SVN. No attached pull request.
