### ISSUE TITLE
[0.9.0 staging-1554] Minor Water Glitch - Interaction with ramps

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16464]
When water level rises to submerge a ramp:
![image](https://user-images.githubusercontent.com/48172405/82736951-45493d80-9d25-11ea-8f9d-051a575176fd.png)

![image](https://user-images.githubusercontent.com/48172405/82736999-9822f500-9d25-11ea-9752-e302753ae270.png)

**Comment by SlayksWood** [comment]
dup #12471
