### ISSUE TITLE
[0.9.0. playtest version] Labor Party Concept in consistency

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16471]
Hello, first of all, I would like to congratulate the new labor concept. That is a fantastic feature and like John K. I’m looking for great usage in the community environment.

What I have observed is one inconsistency in the current configuration towards the concept and what John K. mentioned as well in the streams. Right now you have several recipes that you can start to craft at any time, but only specific special labor can be added. That working fine and is great. But there are as well recipes where you need to have a specialty level to even start the crafting process. This should not be the case, as this won’t work employers who have a bunch of machines in his hall and are asking around for employees to work on his machine by adding their labor. This means the employer have to have the specialty to start the crafting process, but with having this specialty there is no need to start a work party and ask an employee to add his labor anymore. (I hope I was clear in what I would like to explain)

So, what I would recommend changing is, that all recipes are not limited to a specialty level anymore, only to a skill. This means, while the employer still needs to read a skill scroll to learn about it, but does not need to spend a star for that recipe. So an employer still needs to know about his business but does not need to have experience with a star as this he would ask to bring in his employees. Means, once I have read them for example mechanic skill scroll, I’m able to start crafting all its items, but as long I have not to spend a star into mechanics, I’m not able to spend labor into the work order. 

To cover the different skill levels, I assume to enhance the labor system not only having specific labor, having in addition although the right level, might be very complex, the easiest way would also be to extend the skill book amount, so in mechanics for example not only one skill book needs to be researched to unlock the recipes, maybe more. 2-3 for example. This solution should be able to implement quite easy and would only have some recipe balancing updates than some coding, I would expect.

**Comment by MonzUn** [comment]
Actually, it is possible to add projects without having the skill and it is indeed useful!
We have used this a lot on our server to do things in our tables without having the skill.
![image](https://user-images.githubusercontent.com/11805935/82811260-9e81b000-9e90-11ea-940a-51f96e26e64d.png)
![image](https://user-images.githubusercontent.com/11805935/82811277-a80b1800-9e90-11ea-8d5b-dff3e8b32753.png)

**Comment by SlayksWood** [comment]
@Alteraner Can you provide some examples?
> But there are as well recipes where you need to have a specialty level to even start the crafting process

**Comment by Alteraner** [comment]
Hello,
 thanks @MonzUn, i was not aware of the possibility to start the project even i do not have the level. And indead the message which pops up is stating in the direction i was refering to. So Sorry, i was missleaded.
So at least this is what i was looking for, and the remaining recommendation would be, that you have to have the skill been read before you even can start the project. A manager should know about what he is doing even he does not have the right level. But that is not that high priority.

**Comment by SlayksWood** [comment]
@Alteraner 
Why did you think that you can't start the order?

**Comment by SlayksWood** [comment]
@Alteraner I added you suggestion here https://github.com/StrangeLoopGames/EcoSuggestions/issues/1121
Closed for now
