### ISSUE TITLE
[9.0] Client crashed and Steam 

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#16479]
Client crashed without Message and Steam thinks that the game is still running. 
Need to Restart Steam

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4679007/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4679008/Player.log)

**Comment by redwyre** [comment]
Do you know what caused the crash?
Was Eco.exe still running in the background?

**Comment by trickenso** [comment]
> Steam thinks that the game is still running.

I just had this after a crash playing single player - caused by ecoserver still running in the background. Is it this?

**Comment by redwyre** [comment]
That would probably do it. If possible could you attach the game _and_ server logs?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by Sekor2600** [comment]
Information from Player
Eco.Exe is nowhere to find in Taskmanager and did make each time diffrent Acion. 
Build, Mining ,cooking etc
