### ISSUE TITLE
Caught exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1647]
getting this when i try and Place a Mill, Windmill or waterwheel, it just drops me back to this window.
![snap038](https://user-images.githubusercontent.com/29383891/27050663-47c792c0-4fab-11e7-81a1-503c3929462d.png)

**Comment by Conchipedia** [comment]
using Staging alpha 5.6 #21f43d75 (forgot this bit sorry)

**Comment by MarjieAVolk** [comment]
Hm, I'm not seeing any problems placing these objects.  Does it have to do with some other circumstances, like where you are trying to place them?  Also, would you be able to get the error log from your server?

**Comment by Conchipedia** [comment]
Am playing on a Public server so No error log is available, it doesn't seem to matter Where i Try and place the Objects (have tried all over the place (i don't get any blocked or cant place here messages just throws me back to the screen shown)

**Comment by MarjieAVolk** [comment]
It was just a shot in the dark - Is it only those 3 types of objects that don't work?  You can place other objects?  Do you have the same problem on a different server?
