### ISSUE TITLE
[0.9 staging] Sea level rises too quickly

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16478]
With changes to pollution, it is too easy for the sea level to rise. We have seen it happen a few times in play-testing sooner than it should. Little time passed between when the first temperature increase happened and when the sea level rose. The sea level rising should be a risk if pollution is too bad, but it should not happen with these pollution levels. 

The threshold for when sea level rise happens needs to be adjusted and the general pollution generation needs to be investigated. This is a really important thing to fix as the sea level rising too much is a world ending event.

**Comment by WeaselDog** [comment]
Changing to investigate as a fix is implemented and we need to see it in playtesting.

**Comment by WeaselDog** [comment]
Pushing for now because we didn't get solid data from last playtest

**Comment by mirasrael** [comment]
You can regulate balance using `AtmospherePressureKgPerM2` and `PPMPerTon`. Now `PPMPerTon` = 1.93 which corresponds to old formula for default world, but it is probably too high value. You can try to change it and check how it works in default-sized world for expected small population.
