### ISSUE TITLE
[0.9.0 staging-1554] Work Party reward UI buttons opens the wrong reward item

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#16473]
While setting up a work party, it is possible to get the edit reward buttons to open the wrong reward item or a default one instead of the one related to the edit button.

Steps to reproduce:
1. Set up a project (I did not have the specialty for my project)
2. Draft a new Work Party
3. Open the edit UI of the default monetary reward
4. Change type from Currency Payment to Currency Payment (This in itself is odd, see second and third image for how it looks before and after)
5. Set up the currency payment with a currency, account, amount and Pay as you go and press Submit.
6. Press the edit button for the default Reputation Payment.
7. Notice that it opened the default currency payment, and that it is in the same odd state as the Currency Payment was before we set it up.

![image](https://user-images.githubusercontent.com/11805935/82811770-d50bfa80-9e91-11ea-913e-a576cd45d50c.png)

![image](https://user-images.githubusercontent.com/11805935/82812046-62e7e580-9e92-11ea-9148-1c590bf75d51.png)

![image](https://user-images.githubusercontent.com/11805935/82812074-76934c00-9e92-11ea-8793-393bf45c878e.png)

**Comment by SlayksWood** [comment]
dup #15952

**Comment by MonzUn** [comment]
Didn't look far enough back into history. Sorry for the dup and thanks for catching it :)
