### ISSUE TITLE
[0.9.0.0 staging-1554] Hammer shape tool malfunctions at world seam

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#16489]
If the line tool in the hammer is used to place blocks close to the world seam and the player moves their character to the other side of the seam while dragging a line (or other dragged shape), the toll will attempt to drag a line across the entire world.

Steps to reproduce
1. Give yourself a block that can be placed using the line tool.
2. Place yourself at either side of the world seam in either the X or Z axis.
3. Start dragging a line from your side of the seam to the other.
4. Move your character to the other side of the world seam.
5. Notice that the line tool now attempts to drag a line across the whole world.

![image](https://user-images.githubusercontent.com/11805935/82934841-711a2c80-9f8c-11ea-9e99-7f29db57a4c0.png)

![image](https://user-images.githubusercontent.com/11805935/82934866-7bd4c180-9f8c-11ea-8681-48e003e8ee49.png)

**Comment by beastyn** [comment]
Thank you for the report.
Dup #15309

Should be fixed soon
