### ISSUE TITLE
[0.9.0.0 staging-1554] LawSystem - Polution missing Location information

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16491]
![image](https://user-images.githubusercontent.com/47274045/82941587-e3900a00-9f96-11ea-9a53-a936258af9e0.png)

It would be great, if the polution would although have location information. For example, we would like to create a law to tax citicen creating polution in an district or area. This would help as well to create nature reserves.

**Comment by trickenso** [comment]
There's also no way to access 'Time' or 'Time Polluting' or a few other parameters in the conditions:
![image](https://user-images.githubusercontent.com/48172405/82943389-7037c980-9f91-11ea-9793-8a2f012b1780.png)

Some more can be accessed in 'then':
![image](https://user-images.githubusercontent.com/48172405/82943432-85acf380-9f91-11ea-9c0a-7a70b30bb152.png)

It's not clear why these would be available in one place and not others - this is similar for several triggers.

For example, Location and Time are missing from 'Chat Sent':
![image](https://user-images.githubusercontent.com/48172405/82943576-c442ae00-9f91-11ea-8d26-3d0fc697a909.png)

I'm unsure why someone would want to prevent someone from sending a chat at a particular place and time, but I'm not sure why the option wouldn't be made available when the data is already being captured.

**Comment by beastyn** [comment]
Thank you for the report.
@trickenso Time is in Statistics section, like this
![bandicam 2020-05-27 16-44-52-083](https://user-images.githubusercontent.com/27898520/83015189-7aad9e00-a039-11ea-96c1-8defa5cfbe42.jpg)

Sounds reasonable, but it can be quite problematic to add right now.
@johnkslg what do you think?
Will put it for the later releases.

**Comment by trickenso** [comment]
@beastyn My mistake - thanks for the clarification!
