### ISSUE TITLE
[0.9.0 staging-1568] Objective window: world object visualization

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16496]
Long objective won't appear properly

This is a message
![bandicam 2020-05-27 12-31-48-511.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/d9ca7de4-8f97-4d55-87c1-6a75aecfe42c)

This is what we see
![unknown (17).png](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/0efc6cbf-4836-411b-bddd-a9b750469edc)

- We should make all message visible fully even with the minimum size of a window. Just add these strings below.

- Links should be formed correctly

**Comment by SlayksWood** [comment]
Another player can't see world objective in objective window now:
![image](https://user-images.githubusercontent.com/45708377/84742424-1424fb80-afb9-11ea-93eb-5eb6219906b4.png)
And objective is cutted off in server description:
![image](https://user-images.githubusercontent.com/45708377/84742533-3cacf580-afb9-11ea-8897-c6e8a2c6b140.png)

**Comment by gzatravkin** [comment]
Proabably 1) was related to disappeared font in several places?
https://github.com/StrangeLoopGames/EcoIssues/issues/16686
Can't reproduce it now. 

2) Fixed (you may need to reset world objective, since it was also reduced from 150 symbols to 90)
