### ISSUE TITLE
Win Server on version 68ea8201 crash loop

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1649]
https://www.dropbox.com/s/i3hn4gxmz1a6p5g/UKServer_Crash_68ea8201.7z?dl=0

This is the Game.eco and the crash dump files.  this started after the server was upgraded to 68ea8201 from bb668640

I hope there is a fix for this or do we need to restart the world again?  Please let me know we have the UK players on hold... thanks!

**Comment by metachronism** [comment]
SLG marmot server was hitting the same crash.  This is fixed in upcoming staging
