### ISSUE TITLE
No metal/smooth map for Steam Tractor

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16492]
![image](https://user-images.githubusercontent.com/14983165/82965477-11685500-9f7d-11ea-88ee-4c3fa0e9eff3.png)

Not sure if it got lost at some point or if it wasn't ever authored.

**Comment by RobertMangano** [comment]
updated all three materials , normal map, albedo map and created a new metallness map These have been checked in
