### ISSUE TITLE
[0.9.0.0 staging-1554] Plugins no longer start

### ISSUE THREAD

**Issue by TazMatic** [StrangeLoopGames/EcoIssues#16493]
After the server starts up with a plugin installed you need to click on the plugins tab in the UI to start the execution of the plugin

**Comment by redwyre** [comment]
Is this an issue with modded plugins?

**Comment by TazMatic** [comment]
modded plugins

**Comment by redwyre** [comment]
What is the source for the plugin? What interfaces are you implementing?
Also you can visit #modding on our official discord to discuss it.

**Comment by beastyn** [comment]
Closing due no response. Please write here if you have additional information.

**Comment by TazMatic** [comment]
There was no response here because redwyre asked me to talk via github. If I'm not mistaken this bug still exists and I can compile all the information provided here again

**Comment by beastyn** [comment]
@TazMatic thank you for the feedback. If you were talking about it, that is great, I will just leave this issue till resolving or feedback from @redwyre

**Comment by redwyre** [comment]
@TazMatic do you have a simple example of a plugin that has the issue? I'm hoping to have some time this week.

**Comment by TazMatic** [comment]
So something this simple illustrates the issue, after the server fully loads you will not see made it in chat. after selecting the plugins tab in the server GUI boom there is your made it. 


`using System;
using Eco.Core.Plugins.Interfaces;

namespace ipChecker
{
    public class ModName : IModKitPlugin, IServerPlugin
    {
        private Boolean started = false;

        public string GetStatus()
        {
            if (!started)
            {
                start();
                started = true;
            }
            return "";
        }
        public void start()
        {
            Console.WriteLine("Made it!!!!!!!!!!!!!!!");
        }
    }
}`

**Comment by redwyre** [comment]
Ah sorry, the solution to this is simple, what you are after is `IInitializablePlugin`:

```
 using System;
 using Eco.Core.Plugins.Interfaces;

 namespace ipChecker
 {
    public class ModName : IModKitPlugin, IServerPlugin, IInitializablePlugin
    {
        private Boolean started = false;

        public string GetStatus()
        {
            return "This is my status";
        }

        public void Initialize(TimedTask timer)
        {
            Console.WriteLine("Made it!!!!!!!!!!!!!!!");
        }
    }
 }
```

(You can ignore the TimedTask timer)

**Comment by TazMatic** [comment]
I see, interesting behavior

**Comment by redwyre** [comment]
Does that solve the issue for you?
