### ISSUE TITLE
[0.9.0 staging-1568] "Report a bug" window doesn't have scroll bars.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16498]
![image](https://user-images.githubusercontent.com/45708377/82995546-656e4a80-a00c-11ea-93c0-6b2b983fbe1c.png)

**Comment by WeaselDog** [comment]
> I just submitted a bug before this one, and noticed that if I put enough words in "report a bug" window in game it doesnt show me all text I've written. The cursor moves to the middle when the black box is filled with text.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/7218
