### ISSUE TITLE
[0.9.0 staging-1568] Objective window: world object input field is glitching

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16497]
1) I don;t see cursor in the input field, only after I start typing
![bandicam 2020-05-27 12-10-09-839.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/e55d77e6-0a45-4aa3-84a6-3c323e03499c)

2) Its pretty hard to edit this field
![bandicam 2020-05-27 12-49-18-097.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/d1fa81fd-829d-49b9-82eb-5d787b570ed8)

I'm clicking on the field, but cursor won't appear, also no symbols can be added or deleted

**Comment by SlayksWood** [comment]
I can't set global objective now:
- open objective and write world objective:
![image](https://user-images.githubusercontent.com/45708377/84351110-5918ee80-abc3-11ea-8a4f-d19ed3325a1f.png)
- reopen objective, field is empty:
![image](https://user-images.githubusercontent.com/45708377/84351144-6d5ceb80-abc3-11ea-91aa-3babcd28b54b.png)

**Comment by SlayksWood** [comment]
need to check #16496 after fixing
