### ISSUE TITLE
Add support for news in multiple languages

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16506]

**Comment by gzatravkin** [comment]
Well this is more for @D3nnis3n 
Client already send preferred language here
`
            string currentLang = Eco.Shared.Localization.Localizer.CurrentLanguage.ToString();
            using (var newsRequest = UnityWebRequest.Post(string.Format("https://accounts.play.eco/api/v1/news?lang={0}", currentLang), form))
`

Just make this endpoint return results based on language and it will work.
