### ISSUE TITLE
Markers are superslow in game

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#16501]
When there are 70+ markers it casuses ~80ms per frame to render them

**Comment by johnkslg** [comment]
Wow that is ridiculous. Post profiling.

**Comment by gzatravkin** [comment]
Video from editor
https://drive.google.com/file/d/1mog7Mwoai9SVynSyHP7Yq4XZugyM1OYL/view?usp=sharing

Screenshot from profiler
![before any optimization](https://user-images.githubusercontent.com/53317567/83082168-ff5be480-a058-11ea-9cc3-a58e1de0a6f3.JPG)

(Atention at PostLateUpdate.PalyerUpdateCanvases)
