### ISSUE TITLE
[0.9.0. staging-1554] Texture dirt road

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#16503]
The texture of the dirt road is not combined into one common texture. It may affect optimization.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/83110648-0ec84580-a0cc-11ea-87ce-5e07e7154e93.png)

**Comment by keegan-o** [comment]
I don't fully understand this issue-- If it were actually the textures failing to combine in the material combiner, there would be a console error for that.

**Comment by SlayksWood** [comment]
We have a lot of invisible texture that loaded compared to dirt:
https://drive.google.com/file/d/1ZDszW_slZ9d2m4m5YebJl3WQGn5IkllG/view?usp=sharing

**Comment by SlayksWood** [comment]
@keegan-o Maybe I should assign @redwyre on it?

**Comment by redwyre** [comment]
@SlayksWood can you test this again? Should be fixed with my latest change (at least for the large square areas)

**Comment by SlayksWood** [comment]
Awesome for big areas:
![image](https://user-images.githubusercontent.com/45708377/99502411-1509f100-298e-11eb-87b6-d988c535421a.png)
