### ISSUE TITLE
Ecopedia Sections for Ecosystem Species

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16519]
We should have a whole 'Species' section of the Ecopedia, with three sections for now:
- Animals
- Plants and Fungi
- Invertebrates and Microorganisms

Each of these sections can in turn have the species we currently have in eco for each category.

Within the 'Plants and Fungi' group there should be three sub-groups: 
 - Trees
 - Plants
 - Fungi

The idea is right now we're separating and organizing things based on how they actually work/can be interacted with in Eco, **while also** being sure to not violate basic taxonomy. 

There are already icons setup for all the animals, trees, plants, and fungi species in eco.unity ready for use.

**Comment by WeaselDog** [comment]
For plants we want a group for Grass I think.

**Comment by johnkslg** [comment]
@WeaselDog can you create this with @keegan-o 's assistance? Any code support needed ping @serpopov

**Comment by WeaselDog** [comment]
Separate issue for adding descriptions: https://github.com/StrangeLoopGames/EcoIssues/issues/16597
