### ISSUE TITLE
Cloud Worlds: Restart 1 disconnected world, restarts all user's worlds

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16518]
On develop branch, User had 3 disconnected worlds.
I set 1 to be restarted without save file.
screen loads endlessly.
i restart page, and all 3 worlds have been restarted.

Worried this might effect connected worlds too.

**Comment by denysaw** [comment]
@j3fffff Tested. For me everything is good, reloads/resets only 1 world:
![image](https://user-images.githubusercontent.com/5720101/87836036-18318b00-c88f-11ea-8f2f-c7919daa7746.png)

Maybe it was some old error. In code (my refactoring) I see, that on every action something is done only on selected world. Totally no DB requests on a world collections (some db world aggregations etc).
So, I think bugged disappeared itself, but you could re-test for sure.
