### ISSUE TITLE
Generator Descriptions are missing / misleading

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1651]
Example:
CombustionGeneratorObject
"Consumes most fuels to produce energy." ---> "Consumes most fuels to produce MechanicalPower."
SteamGeneratorItem (Description is missing )
--->"Starting Generator for ElectricPower"
InductionGeneratorObject
Generates electricity out of most fuels  ---> Biodisel is not acceptet missing
ElectricGeneratorObject (Description is misleading)
Converts mechanical energy to electricity. -->The smallest ElectricPowerGenerator

**Comment by REPOSEECO** [comment]
#1328
Unclear which generators provide which type of power

**Comment by craig-jong** [comment]
generators have been condensed.
