### ISSUE TITLE
[0.9.0. постановка-1554] Distribution Station - does not work correctly.

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#16516]
Distribution Station - does not work correctly, it is reset every day, and gives out the indicated amount again. A player can take resources every day.
![2020-05-29_00-38-38](https://user-images.githubusercontent.com/36518011/83185913-2c85c100-a145-11ea-9c5d-82c28f7517cf.png)

**Comment by SlayksWood** [comment]
@olegshegai 
Seems you can take items second time after server restart.
