### ISSUE TITLE
Minimap graphic tweaks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16525]
- [x] Propagate anti-alias settings to minimap  (getting lots of sparklies)
![animx22](https://user-images.githubusercontent.com/3536496/83295882-91243880-a1a4-11ea-8317-d9f928a94943.gif)

- [x] Enable shadows / ambient occlusion at all zooms. Looks way better.
![animx22](https://user-images.githubusercontent.com/3536496/83295980-b9139c00-a1a4-11ea-9a21-f66894d796e9.gif)

**Comment by johnkslg** [comment]
Still seeing weird stuff with missing shadows and shadow shape
![animx22](https://user-images.githubusercontent.com/3536496/84210675-227d8f80-aa6e-11ea-8404-c87f072c8fa7.gif)
- No shadow at max zoom
- Zoom in, shadow appears
- Zoom in more, shadow changes shape

Also sparklies are there even with highest AA

**Comment by Dmittry62** [comment]
Looks like shadowing issues have already been dealt with.
![ltHeioGSV1](https://user-images.githubusercontent.com/8580108/87791626-3ffeff80-c84b-11ea-9027-c538bef2f465.gif)

**Comment by WeaselDog** [comment]
Looks like this was fixed. Can we double check?
