### ISSUE TITLE
Broke World When Testing Civics

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#16528]
Version: 9.0 staging-1554

Was trying to modify my law and pass it using admin commands. Something happened to crash the server and the world will no longer boot.

World was created in 9.0 staging-1515, and just started in 9.0 staging-1554 some hours ago when I started playing around with the civics again.
[log_200529084358.log](https://github.com/StrangeLoopGames/EcoIssues/files/4704291/log_200529084358.log)
[log_200529103840.log](https://github.com/StrangeLoopGames/EcoIssues/files/4704292/log_200529103840.log)
[9Test.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4704295/9Test.zip)

**Comment by johnkslg** [comment]
It's working fine now, server loaded and client connected. Something else must have fixed it.
![image](https://user-images.githubusercontent.com/3536496/83822694-9e4e9500-a686-11ea-8d49-861593326045.png)

**Comment by beastyn** [comment]
Yeap, looks fine with the latest build
