### ISSUE TITLE
Law - Law logic summary doesn't show Record Custom Stat's value

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#16527]
Version: 9.0 staging-1554

![image](https://user-images.githubusercontent.com/2676134/83298266-62ce4980-a1f4-11ea-8898-85c1b995e6c8.png)

The law logic summary only says:
```
On event <whatever>

Record custom stat <name>
for <target>
```
It does not mention the value at all, which is in this case a static `1`. But it should of course be able to show math, for example `number of properties multiplied by 10`.

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/83822895-3ba9c900-a687-11ea-99a6-6d04bf922110.png)

**Comment by beastyn** [comment]
Mmm, how this should work?
It should record some value every time action is triggered?

For example, with this law
![bandicam 2020-06-08 15-07-38-469](https://user-images.githubusercontent.com/27898520/84018959-1a542000-a99a-11ea-8a3f-caf4ab310064.jpg)

will show
![bandicam 2020-06-08 15-11-37-311](https://user-images.githubusercontent.com/27898520/84019172-5dae8e80-a99a-11ea-94ed-ee13122cdf0b.jpg)

**Comment by beastyn** [comment]
But it for the different issue.
