### ISSUE TITLE
USER ISSUE: Beets and Corn

### ISSUE THREAD

**Issue by robjames5** [StrangeLoopGames/EcoIssues#16520]
**Version:** 0.9.0.0 beta staging-1554

**Steps to Reproduce:**
When harvesting, always seem to get 3 yield. no matter the skill,spacing,nutrients, bonus harvest for planted crops

Tomatoes seem to work beside spacing. skills and bonuses seem legit
still testing other crops

**Expected behavior:**
higher yield when conditions are meet and skills are earned

**Actual behavior:**
no change in yield, always 3 yield. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nothing installed vanilla 9.0 beta test

**Comment by robjames5** [comment]
Wheat appears to be 3 no matter what category as well

**Comment by SlayksWood** [comment]
@robjames5 Thank you for the report.
I can't reproduce. I harvest Corn with current yield 2. Without skill I receive 2 Corn. With gathering 7 - 4 Corn
If you harvest Corn with current yield 1 with skill you will receive 2.

We have some different with planted and wild plants but it's another issue #15163

**Comment by SlayksWood** [comment]
you can see current yield with soil sampler:
![image](https://user-images.githubusercontent.com/45708377/83254074-cdf92b00-a1b6-11ea-8000-7d45bac7b6c0.png)

**Comment by robjames5** [comment]
Ill keep testing but its been 5 days of it with no change.  and if i can figure out how to screen shot pics on here, I might

**Comment by beastyn** [comment]
Could not reproduce after proper testing. Will close for now
