### ISSUE TITLE
Hosted Worlds: ux flow

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16530]
1 from hosted worlds sales page, unlogged in user. clicks button to login, then clicks register account. after registration, it should auto pass user to subscription page.

2 after hosted worlds purchase, im passed to hosted worlds sales page. I think its because im first passed to my worlds page, but i dont have any worlds yet, so it auto passes me to sales page. update so it goes to worlds page with our usual world pending messages.
But if user goes to world page, has no worlds or pending worlds, and did not purchase any worlds. in that case, it should pass user to sales page.

**Comment by denysaw** [comment]
Done, but this part is unreal: `But if user goes to world page, has no worlds or pending worlds, and did not purchase any worlds. in that case, it should pass user to sales page.`. Cuzz when user goes to /worlds right after purchase, there's no words/pending worlds and no info about world purchase even in userdata.

**Comment by rainfarmer** [comment]
then how are pending worlds displayed after purchase?

**Comment by j3fffff** [comment]
@denysaw as we discussed, can you add:
 if user goes to world page, has no worlds or pending worlds, and did not purchase any worlds. in that case, it should pass user to sales page.

**Comment by denysaw** [comment]
@j3fffff Oh, yeah, done.
