### ISSUE TITLE
USER ISSUE: Cannot use Books/Scrolls

### ISSUE THREAD

**Issue by blumbee82** [StrangeLoopGames/EcoIssues#16534]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Try to use a Book / Scroll

**Expected behavior:**
Gives Skill / Scroll

**Actual behavior:**
Nothing

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nothing

**Comment by beastyn** [comment]
@blumbee82 Thank you for the report.

Can you provide a log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Also, it will be nice to have a video with preocess recording.
Thank you.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
