### ISSUE TITLE
steam tractor attachments

### ISSUE THREAD

**Issue by RobertMangano** [StrangeLoopGames/EcoIssues#16538]
steam tractor combine attachment (harvester) is offset and appears incorrectly when attached to the steam tractor
![image](https://user-images.githubusercontent.com/26705633/83375963-fcc00d00-a413-11ea-8c99-1016429894fe.png)

it should appear like this
![image](https://user-images.githubusercontent.com/26705633/83376050-4d376a80-a414-11ea-86da-607cb0e30083.png)

**Comment by RobertMangano** [comment]
also noticed the wheels are out of position

**Comment by StanKryvenko** [comment]
Fixed in SVN
