### ISSUE TITLE
USER ISSUE: Ocean Broken Tiles

### ISSUE THREAD

**Issue by Twistt** [StrangeLoopGames/EcoIssues#16536]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Look out to the ocean

**Expected behavior:**
Surface should interlock vertice to vertice (presumably)

**Actual behavior:**
shows broken tiles that break up the volumetric shader of the underwater environment.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No Mods - fresh install. First play.
shows broken tiles that break up the volumetric shader of the underwater environment.

**Comment by SlayksWood** [comment]
merged to #12080
