### ISSUE TITLE
0.9.0 Staging-1554 Severe Server Lag after 2-4 Days of Gameplay

### ISSUE THREAD

**Issue by evanah64** [StrangeLoopGames/EcoIssues#16531]
After a few days of gameplay the server console will start kicking out the attached error and pings for all connected players go from 20-30 to 100-300 rending the game nearly unplayable. Server resets have no effect. We had the server transitioned to a new set of hardware, keeping the current save files and all is great for at the first few days and then the lag occurs again. Generated a whole new world and same occurs. Fine for a couple of days, errors start showing up in the console and lag renders game essentially unplayable.

We've also noticed with this version initial world generation has gone from roughly 30 minutes in 8.3 to 5-7 hours with this version. Also simple restarts have gone from 1-2 minutes to 5-15 minutes. This has occurred on both the original and new set of hardware.

Several players from different locations around the world have tested our connections with WINMTR and all have excellent results leading the provider to state it's not a problem on their end. We can also see the hardware memory usage and CPU are never an issue peaking at 35% and 10% respectively.

![Server Load Time and Error](https://user-images.githubusercontent.com/66179199/83336097-d452da00-a27e-11ea-9f8a-53113e645f24.PNG)

**Comment by beastyn** [comment]
@evanah64 Thank you for the report.
Can you provide more information and machine for server? Hardware, software.
Also it will be nice if you can provide a save file with the world.

**Comment by evanah64** [comment]
Both the original and current machine is: Intel Xeon E-2276G and 64gb of memory running Windows Server

Appears both files are over the size limit for github. The Game.db file is 21mb zipped and the game.eco file appears to be 45mb zipped.

**Comment by stavlor** [comment]
I've linked to both files since they are over the size limit for attachments, but they can be found at the URL below.
[https://storage.googleapis.com/stavlor-storage/Eco/Game.eco.zip](Game.eco.zip)
[https://storage.googleapis.com/stavlor-storage/Eco/Game.db.zip](Game.db.zip)

**Comment by mirasrael** [comment]
@stavlor do you have any mods installed?

**Comment by stavlor** [comment]
As far as mods go i believe the only things changed was generally a increase in MaxStackSize and the increase of some storage object sizes but i believe the same issue occurred with out the mods Essentially we were attempting to replicate some QOL mods we had in our 8.3.3 set up Other than stack size changes not sure there was much else changed Other than removing the Stockpile stack size limitation based of DefaultDim.y i believe the issue existed on the prior reset as well which had 0 modifications.

`            storage.Storage.AddInvRestriction(new StockpileStackRestriction(DefaultDim.y)); // limit stack sizes to the y-height of the stockpile`

I'll see if i can get a zip of the Mods directory on the server if it would be helpful.

**Comment by evanah64** [comment]
Here is a link to the backup file I just created. And Stavlor is correct, stack size was the only thing modified in this latest run. No other mods installed or modifications were made. But this exact same thing did happen when we ran it 100% unmodified.

Backup:
https://drive.google.com/file/d/140YWNgEkwFi7a-Si8od9hOPrhfyPNTAq/view?usp=sharing

Mods Folder:
https://drive.google.com/file/d/1hiHuXmiZk5BJDPoiA5urI7lHv4RBMark/view?usp=sharing

**Comment by mirasrael** [comment]
I'm not really sure what is wrong with the save file, but I continue getting same error when trying to load provided save. I even rolled back to version 1554, but same error.
```
[01:56:24] Failed to load object of type 'GameData'. It will be ignored, but may cause inconsistency and errors in other entities: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Eco.Core.Serialization.Serializers.ObjectSerializer.DecodeReferenceable(BinaryReader reader) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 106
   at Eco.Core.Serialization.Serializers.ObjectSerializer.Decode(BinaryReader reader) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\Serializers\ObjectSerializer.cs:line 128
   at Eco.Core.Serialization.SimpleSerializer.Deserialize(Stream stream) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\SimpleSerializer.cs:line 648
   at Eco.Core.Serialization.CurrentSerializer.Deserialize(Stream stream) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\Serializers.cs:line 48
   at Eco.Core.Serialization.EcoSerializer.Deserialize(Stream stream) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\Serializers.cs:line 109
   at Eco.Core.Serialization.DataStore.DeserializeSafe[T](Stream stream) in W:\projects\Eco-Master\Server\Eco.Core\Serialization\DataStore.cs:line 439
```
Are you running and generated the server on Windows 10?
Also you have extension .eco.zip. I guess you just renamed .eco to .eco.zip and renamed back, but probably you did something different?

**Comment by mirasrael** [comment]
Seems like you unpacked .eco file to the folder and repacked it back as the zip file? (May be it is Windows zip folder)

**Comment by mirasrael** [comment]
I started the server locally on latest version (after fixing issue with zip archive):

Some stats:
```
[02:48:28] Initializing IntegrationTestsPlugin... Finished in 0.0ms
[02:48:29] Saving world... Finished in 21,589.5ms
[02:48:49] No UPnP device with public ip was found
[02:48:50] [Server Initialization]... Finished in 71,963.1ms
```
![image](https://user-images.githubusercontent.com/475445/84027346-7ec1b000-a997-11ea-8b2f-dbef9be71df8.png)

It starts fast enough (a bit more than in one minute) and I have 1ms ping in game (for local server), but if problem related to server lags then it should be definitely more than 1ms.

So I see 3 possibilities:
1. It may be related to number of players online. Did you notice any correlation between number of players and lags? How much players do you have at the same time?
2. It may be related to Windows Server environment. You can try to start the server on Windows 10 and check if anything changes (only Windows 10 officially supported while we are doing our best effort to support other environments).
3. It may be related to some latest fixes. You have old enough version (current dev version is 1593). We will update version soon so you will be able to check this possibility.

**Comment by evanah64** [comment]
I agree and have seen the same thing. If I run it on my own local machine for just myself while testing things then there are no FPS or otherwise lag issues. 

1) The number of players did not seem to matter. It was observed with just one person online (myself) and up to 10-15 at once.

2) This is a hosted service through Pingperfect so we're not able to switch to Win 10.

3) We look forward to the update! As it stands most of our group have quit playing due to the performance issues. Hopefully an updated version will address most of that.

Thank you for taking the time to test it out.

**Comment by mirasrael** [comment]
When you mentioned PingPerfect I guess there is 4th option. Do you use exclusive hosting or shared hosting? In case of shared hosting your performance may significantly degrade if they're running another software which consumes CPU and network traffic. Probably this issue related to the hosting provider. You can contact them and ask for info. Eco actually is CPU intensive so doesn't work well on shared hosting.

**Comment by evanah64** [comment]
They did test that for us by moving us to a machine that only we were active on. The memory / CPU usage was the same as on a shared machine in which we never used more than 20% of our allocated CPU. Of course they wouldnt tell me what else was on the shared machine but assured me it wasn't a cause of our issues based on the statistics they have. All I have available is a meter for the CPU/Memory so unfortunately I can only go off what they're telling me.

I see version 1594 was release this morning so we'll perform that update and see how it goes. I'll report back anything we find.

Thank you

**Comment by mirasrael** [comment]
Actually if you're saying when you're running the server locally you see no issues then I assume there definitely issues with the runtime environment. I think if other people will connect your locally running server then they won't see major lags or low ping.

**Comment by evanah64** [comment]
It appears this latest patch has resolved the server lag issues. We're still using the same save file so I have not generated a new world yet but the server now restarts in about 90 seconds and we have not had any of the staggering lag issues I originally described. We do all still have what we believe to be a client side memory leak forcing client restarts every 90-120 minutes but I believe that's for another ticket.

Thank you

**Comment by mirasrael** [comment]
Thanks for confirm!
