### ISSUE TITLE
[0.9.0 staging-Various] OS Locks up when swapping screens during loading

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#16547]
I don't know if this is an issue related on my end, but it's repeatable every time for me and the worst type of 'crash' - no CTRL+ATL+DEL or OS response when it happens.

Actions:
Have 2 screens
Load Eco (I use steam client)
During the loading (before Continue menus come up, showing the tree) swap the application to the other screen (Win+Shift+Directional arrow)

Outcome:
The app switches screen and immediately locks up my computer requiring a hard reboot to break out.

Expected outcome:
Game application swaps screen and continue as expected.

It works fine once the game finishes loading, I attach my logs for review.

I play with Borderless Window and Alt tab, clicking out etc. doesn't have any issue
![image](https://user-images.githubusercontent.com/54982803/83428894-1f115500-a42b-11ea-830c-2fee916818c0.png)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4712219/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4712220/Player.log)

**Comment by SlayksWood** [comment]
I have this problem in ECO, but I can reproduce this issue in some other games too: World of Warcraft, Factorio (where I have preload too). But didn't have in Pummel and Divinity: Origin Sin.
@NN-Mike Do you have this issue in other games? It seems this question isn't for us.

**Comment by SlayksWood** [comment]
Closed for now.
