### ISSUE TITLE
Hosted Worlds: renew problems

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16545]
We should give more feedback for users after renew.

1) I've bought 1 world and 3 citizens
2) After success I was trying to renew to 2 worlds and 10 citizens
3) After order completing I was brought back to the same subscibtion page with an OLD numbers (1 world and 3citizens)

After some time it was updated. But.
We should tell a user if something in a procees of updating, as a person has spent money and actually can't see any changes (and can even try to spend more money).

Also I've waited for quite a long time for updating info on the subscription page and it was not updated after 15 mins and ctrl+f5

And it looks like they were not deleted at all.

**Comment by denysaw** [comment]
@beastyn But we can't show user unreal future numbers till payment will be accepted by PayPal. 
We can't show him 100 worlds and citizens and then got IPN reject (cuzz of e.g. insufficient funds) and then show 1 world again. That would be also confusing. Please, decide here with @rainfarmer what actually to do.

**Comment by rainfarmer** [comment]
Just add notification that purchases are pending.

**Comment by beastyn** [comment]
Yeap, just tell that something in the process. We should give feedback to the user every step he is making.
