### ISSUE TITLE
[0.9.0 staging-1573] Setting slider has texture glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16540]
Almost the left position:
![image](https://user-images.githubusercontent.com/45708377/83382765-822fc700-a3ec-11ea-8ec9-c4ee1047bb68.png)
a bit to the right:
![image](https://user-images.githubusercontent.com/45708377/83383056-041ff000-a3ed-11ea-983f-afa03b763bdb.png)
![image](https://user-images.githubusercontent.com/45708377/83382875-b1463880-a3ec-11ea-8493-61ec4d5fd6b9.png)

**Comment by TwixterZ** [comment]
confirmed fixed as of 9.4 develop 243 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/bc2a9cd2-1def-4608-92fc-05d96b59dd8d)
