### ISSUE TITLE
[0.9.0 staging-1575] Change some ecopedia screenshots

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16549]
1. This is old screenshot without background:
![image](https://user-images.githubusercontent.com/45708377/83487045-fdf44700-a4b2-11ea-9e87-6e9eee4cd547.png)
2. Strange white rectangle:
![image](https://user-images.githubusercontent.com/45708377/83487189-3d229800-a4b3-11ea-8c33-e282f80fe17c.png)

**Comment by WeaselDog** [comment]
Fixed in SVN
