### ISSUE TITLE
[0.9.0 Staging-1554] Law 'If' Error - Compare Right cannot select '# Enter a Number'

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16554]
Using 'Compare', the 'Right' entry cannot select '# Enter a Number'. Other options (including # Enter a Number in the 'Left' field) appear to work fine:

![Compare](https://user-images.githubusercontent.com/48172405/83535532-f3a16f80-a4e9-11ea-9c17-65d363cafe03.gif)

**Comment by beastyn** [comment]
@trickenso thank you for the report. Was fixed in later build. Hope you will get update soon.

**Comment by trickenso** [comment]
@beastyn Sorry for the dupe!
