### ISSUE TITLE
[0.9.0 staging-1575] Some items has wrong category and pages in Ecopedia

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16550]
Modern street light and Modern Double Street Light shoud be in Housing Objects Category, Light Page:
![image](https://user-images.githubusercontent.com/45708377/83488120-fb92ec80-a4b4-11ea-891b-666d6969fce4.png)

**Comment by WeaselDog** [comment]
This was actually intentional because they are not meant for housing but as a community object to be placed along roads and other monuments. Will double check this but it might stay as is.

**Comment by SlayksWood** [comment]
But we have Streetlamp in Housing, and in any case it has housing benefit and you can place it in room and get house value from it.
![image](https://user-images.githubusercontent.com/45708377/83490062-07cc7900-a4b8-11ea-9363-643f9fee958e.png)
