### ISSUE TITLE
[0.9.0 staging-1575] Disappeared contract/work party windows.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16552]
Step to reproduce:
- open contract board and press create contract (contract board window is more than Contract window):
![image](https://user-images.githubusercontent.com/45708377/83502297-060bb100-a4ca-11ea-8a1d-225613e6a4dd.png)
- click on empty space of contract board. So Contract window is under contract bord window:
![image](https://user-images.githubusercontent.com/45708377/83502510-5d118600-a4ca-11ea-9dd4-399e210870ee.png)
![image](https://user-images.githubusercontent.com/45708377/83502640-934f0580-a4ca-11ea-8a22-948b2353e8fd.png)
- try to start new contract. I have notification that I already have another contract:
![image](https://user-images.githubusercontent.com/45708377/83502703-aa8df300-a4ca-11ea-8520-0c35445fc706.png)
- But I haven't any possibility to open this window without reopenning or moving this windows.
- So I don't have any good idea to solve it, but we we can at least add possibility to activete this window if I press here (1 and 2):
![image](https://user-images.githubusercontent.com/45708377/83502941-03f62200-a4cb-11ea-80c6-9886d86f835a.png)

**Comment by gzatravkin** [comment]
Now this window is modal, you can't select anything else until you close this window.
