### ISSUE TITLE
[0.9.0 staging-1582] Disconnect with vehicle placing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16569]
Place a truck on the ground

You will be disconnected from a server.

No errors on a server, nothing special in a log

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4728795/Player.log)

@gzatravkin can be yours issue

**Comment by mirasrael** [comment]
Was same issue as https://github.com/StrangeLoopGames/EcoIssues/issues/16573 (thanks @olegshegai for investigation)

**Comment by beastyn** [comment]
1587 Still have it on the fresh world.
But actually was able to place a vehicle on the migrated white tiger
log is clear
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4737765/Player.log)
