### ISSUE TITLE
Elections: username, server name, server version dont always load

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16577]
In menu area it should display username, server name, server version.
Sometimes these don't all load. Happens more often when you do hard refresh ctrl f5
![image](https://user-images.githubusercontent.com/7343272/83818968-7d357680-a67d-11ea-92ed-adf9fcbd8360.png)

**Comment by gzatravkin** [comment]
CNR. 
When user is logged out it shows 
![image](https://user-images.githubusercontent.com/53317567/89199048-6a0f2c00-d584-11ea-8436-c9ef27b00510.png)
When looged in
![image](https://user-images.githubusercontent.com/53317567/89199101-785d4800-d584-11ea-9d6b-d4af54bc75bd.png)

Tried F5 and Cntr+F5 in chrome.
Some repro steps? Sending to QA so they can try to repro it.
@j3fffff 

If somebody will reproduce it, please attach a browser, fullscreenshot of page including addres bar and console output (cntr+shift+I in chrome)
