### ISSUE TITLE
WorldGenerator.eco Bug ?

### ISSUE THREAD

**Issue by YouStones** [StrangeLoopGames/EcoIssues#16570]
When I modify a value in the WorldGenerator.eco file, it creates during the world generation a recreate the 12 biomes with the same data in TerrainModules. In the end, the size of my file goes from 52kb to 101kb.

![git](https://user-images.githubusercontent.com/66413988/83738719-f371b300-a654-11ea-9a64-0b0e3d3a9d21.PNG)
_Files size_
![git1](https://user-images.githubusercontent.com/66413988/83738720-f40a4980-a654-11ea-9d8b-370c59c0fdf1.PNG)
_original biome of grassland_
![git2](https://user-images.githubusercontent.com/66413988/83738721-f40a4980-a654-11ea-96c5-7539e8dc2f8a.PNG)
_duplicates biome of grassland_

**Comment by D3nnis3n** [comment]
That issue is already fixed in Update 9.0: https://github.com/StrangeLoopGames/EcoIssues/issues/13400
