### ISSUE TITLE
Won't allow me do contract project or perform labor.

### ISSUE THREAD

**Issue by Elmoooy** [StrangeLoopGames/EcoIssues#16575]
![20200604130704_1](https://user-images.githubusercontent.com/65803627/83797268-004bd200-a668-11ea-9db7-24cd20687a3f.jpg)

Sorry about the delay - As you can see, I have access to the campfire via the work party contract. I try to put the mushrooms in the campfire and it says I am not authorized. I try perform the labor, but it says Im not authorized but yet I should be. I dont know what is wrong, either something on our end or its a bug.

**Comment by SlayksWood** [comment]
@Elmoooy Can your provide log files and WorkParty screenshot?

**Comment by Elmoooy** [comment]
Hello - The providing labor part works now, we all didnt realize that we cannot have anything in hands.  However, we cannot feed anything to project - I can provide you with log files if you tell me where they are :P

**Comment by SlayksWood** [comment]
Sorry I forgot to add link, but I assume it should be fine in new staging build. So don't need log files for now. But if it happens again please reopen and provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Closed for now
