### ISSUE TITLE
[0.9.0 staging-1586] Web Elections: strange wrapping for stats blocks

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16579]
1680x1050
![82411447-73572500-9a7a-11ea-86c3-90bb6f257821](https://user-images.githubusercontent.com/27898520/83841502-642ed300-a71a-11ea-8b42-304178963a5f.png)

1920x1080
![bandicam 2020-06-05 10-55-08-878](https://user-images.githubusercontent.com/27898520/83841849-16669a80-a71b-11ea-9a71-49a01d2ed9cd.jpg)

It looks rather strange

**Comment by j3fffff** [comment]
updated
