### ISSUE TITLE
Parallel work orders?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1657]
The first work order (ordered by someone else) had full resources before I started the 2nd one. Somehow the 2nd one got a few seconds taken off its time.

![image](https://user-images.githubusercontent.com/774628/27104742-0ab412d6-5042-11e7-80cb-b94a23aa61ae.png)

**Comment by metachronism** [comment]
I reordered them for a few seconds
