### ISSUE TITLE
Eco [0.9.9.0 beta staging-1554] Server crash - save games won't load and can't create new game

### ISSUE THREAD

**Issue by PennyTent** [StrangeLoopGames/EcoIssues#16585]
Multiplayer still functional.
Played fine for a few days, then after closing and restarting the game, could no longer load saves.
When attempting to connect to single player save files or start a new sp game, receive error message: "Failed to connect to local server. It may be because of server crash"

Server dump files from June 2 say: ServerCrash TypeInitializationException 06024601

Server log files: (Sorry if I've included too many/not the right files. Am mostly code illiterate)
[log_200602085627.log](https://github.com/StrangeLoopGames/EcoIssues/files/4740465/log_200602085627.log)
[log_200602040048.log](https://github.com/StrangeLoopGames/EcoIssues/files/4740466/log_200602040048.log)
[log_200602012644.log](https://github.com/StrangeLoopGames/EcoIssues/files/4740467/log_200602012644.log)
[log_200603125201.log](https://github.com/StrangeLoopGames/EcoIssues/files/4740468/log_200603125201.log)

**Comment by beastyn** [comment]
Thank you for the report.
Can you provide a save file?

Didn't have problems with commands in the latest build.

**Comment by WeaselDog** [comment]
Hi @PennyTent. We are not able to reproduce this on our end. Are you still experiencing this issue? If you have a save file for the world that was having this problem, it would be much appreciated.

**Comment by PennyTent** [comment]
Hi, sorry about that! I've had trouble logging in to GitHub and was unable to update - the issue resolved itself with the update you brought out a few days later. Thank you for responding.
I can still send the save files if you need, but the issue seems to be resolved.

________________________________

**Comment by WeaselDog** [comment]
Glad to hear it is resolved now.
