### ISSUE TITLE
1

### ISSUE THREAD

**Issue by vinopsspcs** [StrangeLoopGames/EcoIssues#16587]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1

**Expected behavior:**
1

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Invalid username or password.
```

**Comment by elfl0rd** [comment]
Use license copy
