### ISSUE TITLE
Missing Sprites for 9.0

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16588]
We are missing the follow sprites that are needed for 9.0:

- [x] Legal Action: Change Reputation
- [x] Game Action: Completed Contract
- [x] Game Action: Item Crafted
- [x] Item: Plastic
- [x] Tag: Silica

**Comment by RobertMangano** [comment]
![missing sprites_01](https://user-images.githubusercontent.com/26705633/84337629-6216b980-abdd-11ea-81f7-f978c1253d5a.jpg)

change reputation

**Comment by RobertMangano** [comment]
![missing sprites_02](https://user-images.githubusercontent.com/26705633/84338802-61cbed80-abe0-11ea-84d4-f5c64897bfb7.jpg)
completed contract

**Comment by RobertMangano** [comment]
![silica](https://user-images.githubusercontent.com/26705633/84342606-57622180-abe9-11ea-9e48-4a22bebf33d5.jpg)
silica tag

**Comment by RobertMangano** [comment]
![crafted items](https://user-images.githubusercontent.com/26705633/84346060-6ac5ba80-abf2-11ea-981f-353ac032563a.jpg)

item crafted

**Comment by RobertMangano** [comment]
Items are on the sheets and assigned in the eco scene which I just updated.
