### ISSUE TITLE
Pollution and other layers should expand radially, not using diamonds

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1659]
Right now various layers 'filter' using an algorithm that spreads a given value of a cell into the 4 neighbor cells.  This causes all the pollution/water/etc too like like oblique squares or diamonds on the map.

This should use a larger convolution kernel so we can better approximate a radial expansion, which would give us something closer to that of a circle.

**Comment by knexer** [comment]
The new spread behaviour uses a 3x3 gaussian kernel and therefore doesn't have this issue - on flat ground it expands into a circle, and it looks much smoother in general.  Not all content is migrated yet, resolving this anyways.
