### ISSUE TITLE
[0.9.0 staging-1592] Civics: law is crashing with Timer and Property

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16592]
1) Make a title and add yourself there
![bandicam 2020-06-08 16-12-34-208](https://user-images.githubusercontent.com/27898520/84026358-a1a79080-a9a6-11ea-88a8-b1c0e8abebd6.jpg)
2) Make a law where you are giving property from that title owner to a person with timer.
Like this
![bandicam 2020-06-08 16-12-25-126](https://user-images.githubusercontent.com/27898520/84026527-ec290d00-a9a6-11ea-9f5b-393e81bbe8d2.jpg)

Trigger DON'T have last field, its None.

You will have crash when law is triggered. And save will be corrupted.
[log_200608123423.log](https://github.com/StrangeLoopGames/EcoIssues/files/4745705/log_200608123423.log)
Everything is fine if Repeat from each user = Everyone.

**Comment by johnkslg** [comment]
Split this timer trigger into two.  Citizen timer, which requires a setting for citizens to run on:
![image](https://user-images.githubusercontent.com/3536496/84201060-8c8d3900-aa5c-11ea-90b1-50e97b4fa24d.png)


And Global Timer which does not:
![image](https://user-images.githubusercontent.com/3536496/84201676-e5f56800-aa5c-11ea-8ee2-5680ecb52b12.png)

Citizen timer can specify 'Cititzen'
![image](https://user-images.githubusercontent.com/3536496/84202471-2523b900-aa5d-11ea-8765-698fefd06a4d.png)

Global timer cant specify 'Citizen'
![image](https://user-images.githubusercontent.com/3536496/84201885-f73e7480-aa5c-11ea-822c-dd10d008ecc4.png)
