### ISSUE TITLE
[0.9.0 staging-1595] Tilled block become in Dirt after some time

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16607]
Hoe some ground:
![image](https://user-images.githubusercontent.com/45708377/84232296-aaa87700-aaf8-11ea-9ef7-fe50e3fb86d4.png)
Wait 15 minutes:
![image](https://user-images.githubusercontent.com/45708377/84233484-15f34880-aafb-11ea-9faf-86ff358ba097.png)
It's a nice bug-feature, but this is bug. So should be fixed. We have another issue for post 0.9 to change this behavior, but I assume it will be another way #14726

**Comment by Engimage** [comment]
While you call this a bug - it is really a long awaited feature that should just be polished a bit so that detilling is happening after more time.
There is a suggestion about this
https://github.com/StrangeLoopGames/EcoSuggestions/issues/1096

**Comment by Krizzoula** [comment]
Engimage, long awaited feature? I hope this is NOT a feature and literally a farmers nightmare. Tried to plow a field tonight and couldn’t even switch fast enough for sower to plant before ground was changing... This definitely needs to be on the 9.0 bug fix.

**Comment by Engimage** [comment]
> r

Yeah the feature is long awaited.
Sure thing its current state is a pain in the butt as it un-tills instantly during the tilling process :) But if it would un-till after a couple of hours it would be completely superb.

**Comment by SlayksWood** [comment]
dirt road too
![image](https://user-images.githubusercontent.com/45708377/86216527-d9a98a00-bb86-11ea-9df2-a67837903236.png)

**Comment by WeaselDog** [comment]
Fixed on current staging
