### ISSUE TITLE
[0.9.0 staging-1595] Web elections: no active elections after redesign

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16605]
No I can't see the active laws

![bandicam 2020-06-10 10-43-08-360](https://user-images.githubusercontent.com/27898520/84232746-602ff600-ab0a-11ea-8c50-099f2c2b7ca7.jpg)

I see only running elections and previous elections

What i want to see
1) Elected Titles
2) Active laws
3) Running elections
4) Previous Elections (with all results)

**Comment by j3fffff** [comment]
@gzatravkin could you update the generate test data query to include active elections?

**Comment by gzatravkin** [comment]
@j3fffff I believe @beastyn was refering to active laws. Generate test data already gives you active elections.

I restored laws https://github.com/StrangeLoopGames/Eco/pull/6346 but it looks really bad (some mix of old and new style).
Looks like laws were removed from html. 
So can you fix design for them? 

To obtain some laws you can use this command:
http://127.0.0.1:3001/api/v1/chat/sendChat?username=Grigorgri&message=/civics%20spawngov
(Need to have checkbox Allow debug calls in server, tab Users)
![image](https://user-images.githubusercontent.com/53317567/86523310-db9e7200-be40-11ea-8b1c-1db3137b3db9.png)
