### ISSUE TITLE
[0.9.0 staging-1595] Notfication panel: section displacement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16609]
1.
1) Notificztion are closed
2) One pesron create a contract, other person finish it. Few times
3) Person who created the contracts open panel
![bandicam 2020-06-10 14-37-24-738](https://user-images.githubusercontent.com/27898520/84257793-5967aa00-ab2f-11ea-8eeb-d22eb41f8894.jpg)

Everything is moved to the left, there is no any margins, should ve like that
![bandicam 2020-06-10 14-54-02-094](https://user-images.githubusercontent.com/27898520/84257884-7bf9c300-ab2f-11ea-94dd-a35efb8fce3e.jpg)

2. Also the person, who was a contractor had broken notifications at some point. Couldn't find particular steps.
![bandicam 2020-06-10 14-40-17-725 — копия](https://user-images.githubusercontent.com/27898520/84258164-e7439500-ab2f-11ea-98a0-232f3370a460.jpg)
UPD: just created a world and open the panel
![bandicam 2020-06-10 15-47-55-976](https://user-images.githubusercontent.com/27898520/84259474-f7f50a80-ab31-11ea-9df8-c897e2aee643.jpg)

**Comment by SlayksWood** [comment]
palyer with long name create contract:
![image](https://user-images.githubusercontent.com/45708377/84355431-46a2b300-abcb-11ea-8868-d6925576f01e.png)
