### ISSUE TITLE
[9.0 staging] Bring back negative shop prices

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#16603]
Its not longer possible to set a negative price in stores. This is important for stores that offer tailings or garbage disposal.

This was a commonly used feature of 8.3 that no longer works in 9.0 staging.

**Comment by WeaselDog** [comment]
From Dennis:
 > Mishka:
> > 
> > Cannot do negative values in 9.0 1611, someone tried (i think Xao?) to do a order to "buy" tailings off people and store them safely.
> > 
> > Just does not accept the - input from keyboard and cannot use the + and - buttons to end up minus either.

> 
> We included that on purpose in one of the last patches due to common requests.
> 
> While at that, fix this: #16796
