### ISSUE TITLE
[0.9.0 staging-1595] Web Elections: lost data for some categories

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16606]
There are empty pages for Previous Elections
![bandicam 2020-06-10 10-56-42-448](https://user-images.githubusercontent.com/27898520/84234486-cb2efc00-ab0d-11ea-8c10-d1286991006c.jpg)

**Comment by beastyn** [comment]
1601 looks fixed.
But it won't show comments 
Active election
![bandicam 2020-06-11 14-33-05-787](https://user-images.githubusercontent.com/27898520/84369706-ae1f2980-abf0-11ea-9e7f-289a5e11adce.jpg)

After passing in previous election section
![bandicam 2020-06-11 14-33-20-955](https://user-images.githubusercontent.com/27898520/84369720-b5463780-abf0-11ea-8201-6f1a27f6cefd.jpg)

**Comment by denysaw** [comment]
@beastyn yeah, for me also white page just happened. It's cuzz of JS Highcharts error. Will fix.

**Comment by denysaw** [comment]
@beastyn Could you, please, send me game saves with such finished election, which 100% had comments? For test purposes. Thank you

**Comment by denysaw** [comment]
Will be solved after merging PR mentioned above.
