### ISSUE TITLE
Elections: Cliking pre-made graphs totally removes other categories from UI

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#16617]
![image](https://user-images.githubusercontent.com/5720101/84329148-28fe2b00-ab84-11ea-91cd-974a8ca12131.png)

**Comment by rainfarmer** [comment]
never saw this. also the fonts dont look correct.
Since the graph uses iframes. ive found you sometimes have to open in incognito and hard refresh to get it to update. @denysaw

**Comment by j3fffff** [comment]
yup still happening
