### ISSUE TITLE
[0.9.0 staging-1594] Cleanup Crew perk labor cost issue

### ISSUE THREAD

**Issue by DCarts** [StrangeLoopGames/EcoIssues#16618]
**Expected behavior:** 
Chopping tree debris should cost the same labor as chopping a tree

**Actual behavior:** 
It costs 0 labor to chop tree debris

**Steps to reproduce:**

1. Level up Logging to 6
2. Get the level 3 perk that makes logging cost less labor
3. Get the level 6 perk Cleanup Crew
4. Chop any tree debris with a Stone Axe, broken or not

Video: https://drive.google.com/file/d/1DbSI6P0_hLAtw1N27pCjGOfrXgrpTxvX/view?usp=sharing

**Comment by WeaselDog** [comment]
Good catch! Thanks for reporting this,
