### ISSUE TITLE
 [0.9.0 staging-1601] White screen on loading

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16619]
After the tree loading screen we have the white screen loading now (sometimes it even has menu ghost)

https://drive.google.com/file/d/1Olg9dxoHV_CAh0J2UgaBwZmT948WXoSm/view?usp=sharing

**Comment by trickenso** [comment]
Having this one too in 1602.
![image](https://user-images.githubusercontent.com/48172405/84759558-cb704100-afbe-11ea-9c57-cdb4a031ad65.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4785813/Player.log)
