### ISSUE TITLE
Player badge icons need to be re-exported for icon sheet

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#16615]
The versions used were 128x128 and shrunk down by me in paint.net. Will probably look a little better with a reexport directly to 64x64. They are in icons 04.

**Comment by RobertMangano** [comment]
which ones are player badges?

**Comment by redwyre** [comment]
![image](https://user-images.githubusercontent.com/431728/84334565-0432a380-abd6-11ea-9f13-dbcdd08d6abf.png)

They are also in Content\Art\UI\Icons_BackerReward

**Comment by RobertMangano** [comment]
Milenko do you have the original psd for those in higher resolution?

**Comment by redwyre** [comment]
Also, there are three reward tiers that are missing icons:
banner (in game backer banner)
hare (tame hares)
super (getting info on what this is, I dunno)

They are currently just using the standard icon as a placeholder

**Comment by MilenkoTunjic** [comment]
last three you mentioned never existed
the rest I sent through to rob

**Comment by RobertMangano** [comment]
exported existing ones but will wait for details on the other 3 placeholders

**Comment by WeaselDog** [comment]
@redwyre I believe hare is the same as Wolf Whisperer.
What do we want banner and super to represent?

**Comment by keegan-o** [comment]
Closing as duplicate
