### ISSUE TITLE
[0.9.0 staging-1595] Claiming troubles

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16613]
Step to reproduce:
- place store on unowned property:
![image](https://user-images.githubusercontent.com/45708377/84270290-1d364880-ab33-11ea-90e4-365dc320f646.png)
- claim this store:
![image](https://user-images.githubusercontent.com/45708377/84270329-2f17eb80-ab33-11ea-856d-342dcba4bf67.png)
- unclaim:
![image](https://user-images.githubusercontent.com/45708377/84270375-4060f800-ab33-11ea-9e11-62f3f3104b04.png)
Same with distribution station, but  you can use it at all, because if you don't have an owner you can't add items:
![image](https://user-images.githubusercontent.com/45708377/84869309-86174680-b086-11ea-9cb8-b990441cc5e7.png)

**Comment by SlayksWood** [comment]
I will add medium label, because this issue could have a lot of different issues. Another option:
- build room and add some furniture to it:
![image](https://user-images.githubusercontent.com/45708377/84870056-7ba97c80-b087-11ea-8233-dc97c236d627.png)
- claim it:
![image](https://user-images.githubusercontent.com/45708377/84870173-9e3b9580-b087-11ea-8a72-b2044549cfee.png)
- I don't have any house points. I need either picking-up/placing  some furniture or breaking/repairing room:
![image](https://user-images.githubusercontent.com/45708377/84870280-c925e980-b087-11ea-8f2a-28629012faa8.png)

**Comment by johnkslg** [comment]
Probably not doing callback updating ownership properly

**Comment by beastyn** [comment]
check after #16889
