### ISSUE TITLE
Tailoring Foundation Update World Object Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16629]
**Tailoring Table Update**
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Loom**
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Advanced Tailoring Shop**
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Automatic Loom**
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Spin Melter**
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

Design Doc:
https://docs.google.com/document/d/1ZWJq5l0Ba280IiOf5PseQvx5tgfWaiHdTR1SJFBWCr0/edit?usp=sharing

**Comment by RobertMangano** [comment]
![advanced tailoring workshop.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/58f7ef4b-ea82-4e53-9c0b-a1b6857c08d1)

**Comment by keegan-o** [comment]
Re-assigned Rob because we may want concepts for the Spin Melter and Automatic Loom. These should both be industrial textile machinery that would fit in in a modern factory.

**Comment by RobertMangano** [comment]
![CONCEPT.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/574ae452-b635-44c0-b4b8-1da9716bdfd8)concept for automated loom

**Comment by RobertMangano** [comment]
assigned icons. I could not find the default tailoring table, but the icon is done and ready.
