### ISSUE TITLE
USER ISSUE: Animals frozen

### ISSUE THREAD

**Issue by ExplodedPuppy** [StrangeLoopGames/EcoIssues#16625]
**Version:** 0.9.0.0 beta staging-1594

**Steps to Reproduce:**

**Expected behavior:**
Animals moving around, running away from u when approaching

**Actual behavior:**
they aren't doing anything, and are frozen on the spot. I can kill em and gather their carcasses

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Comment by SlayksWood** [comment]
dup #16486
