### ISSUE TITLE
[0.9.0 staging-1601] Text overlaps in web UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16623]
1. Previous elections will overlap with User/ Server/Version if you have a lot of previous elections:
![image](https://user-images.githubusercontent.com/45708377/84374087-2d5b3000-abe6-11ea-92f1-5d5f3bd061e5.png)
2. If User have long name like I set for myself ( ) then username does not fully displayed:
![image](https://user-images.githubusercontent.com/45708377/84374275-6e534480-abe6-11ea-86b0-c903a6fd2fda.png)
![image](https://user-images.githubusercontent.com/45708377/84374324-8034e780-abe6-11ea-85e0-42b038677055.png)

**Comment by rainfarmer** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/16746
