### ISSUE TITLE
[0.9.0 staging-1601] Civics:  propose button's text is trying to run away

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16621]
It is almost out
 
![bandicam 2020-06-11 14-16-12-841](https://user-images.githubusercontent.com/27898520/84367768-22a49900-abee-11ea-8649-615ff14a3f6a.jpg)

**Comment by johnkslg** [comment]
@beastyn Text must be whipped into submission until it does not run away.
