### ISSUE TITLE
Add districts view for elections in Web

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#16624]

**Comment by denysaw** [comment]
What's done:
- Added 2D/3D switcher
- Auto-scroll 2nd map on scrolling first
- Refactored map-adding code

@rainfarmer If you find styling of these maps is needed (to place them side-by-side in 1 row e.g.), you can do it in separate issue ;) (I can give you saves with active Add/Modifiy District Elections Grigory gave me ;) )
