### ISSUE TITLE
[0.9.0 staging-1601] Glitch of progress bar in Drill UI.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16620]
Step to reproduce:
- take modern rock drill, lost all you calories (/work) and eat something (I eated beans), so I have 150 Calories:
![image](https://user-images.githubusercontent.com/45708377/84359086-c8490f80-abd0-11ea-8539-266d568d449b.png)
- start to drill and wait until you will hungry. I drilled 12 Blocks but progress bar is in the end.
![image](https://user-images.githubusercontent.com/45708377/84359151-e44cb100-abd0-11ea-9b1d-2b4ff298d51c.png)
- now eat full and drill 12 blocks:
![image](https://user-images.githubusercontent.com/45708377/84359308-1bbb5d80-abd1-11ea-96e7-94f5d2777b58.png)
- in first case progress bar should be at the same points.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Develop 277
