### ISSUE TITLE
Tailoring Foundation Update Clothing Art

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16634]
Milenko has just about finished 4 new sets of profession themed clothing, which in terms of which models are shown and displayed on the avatars have some additional differences-- the meshes for the actual avatars have been updated and broken up differently for them. This will be a new way to break up the avatar mesh going forward and eventually all old clothing assets will be updated to work the same way.

For now, we will need to hide and show specific sets of meshes that constitute the avatar for the new clothing to work. When an old clothing piece is equipped, we can simply switch that part back to the old avatar mesh as well, for the near future.

**Comment by keegan-o** [comment]
We need an initial set of new clothes to add with the new suite of tailoring/textile production world objects, to give tailors something to craft. These clothes should be wearable by all for fashion, and should highlight the qualities unique to the fabric type. 

- Woolen Clothing Set
- Cotton Clothing Set (Many current clothes will be designated cotton clothing but we should also come up with a new set I think for this update)
- Nylon Clothing Set

**Comment by Praefator** [comment]
How about something like formalwear, e.g. suits, tuxedos, top hats, dresses and the like? Something which would at a glance help distinguish people in government, people working in the various professions and the like

**Comment by MilenkoTunjic** [comment]
Making skirts and dresses work with bones will be massive pain in the arse. Rest should be fun to do.

**Comment by keegan-o** [comment]
I think even skirts and dresses like they are implemented in WoW would be an acceptable, if not exciting, start (they are all conservatively skinned to the body, with no physics or flowing around).

**Comment by Praefator** [comment]
Yeah, I see what you mean. Would definitely flesh out avatar customization a lot already without going overboard with flowing parts (depending on just how exquisite the dress is to be)

**Comment by legionaw** [comment]
> 
> 
> How about something like formalwear, e.g. suits, tuxedos, top hats, dresses and the like? Something which would at a glance help distinguish people in government, people working in the various professions and the like.
> 
> In addition, it could also further be expanded upon to include various crowns and other clothing which designated rulers of some sort in the various cultures of our world

Heh, the top hat was the common male headgear worn by the upper and middle classes in the nineteenth century while the Industrial Revolution was in the vogue. It seem to have come into use by 1795-1820 according to the Wikipedia [article](https://en.wikipedia.org/wiki/1795%E2%80%931820_in_Western_fashion) on this period in [history of Western design](https://en.wikipedia.org/wiki/History_of_Western_fashion).

Speaking of which, I wouldn't also mind having [shakos](https://en.wikipedia.org/wiki/Shako), a type of headgear worn by troops during Napoleonic Wars. While obviously there will **not** be warfare in Eco (at least not in near future), I thought it would be interesting to use for a sort of Army Corps of Engineers to make them stand out while constructing infrastructure such as roads, canals, dams, and so on. That and the Napoleonic military uniform to go with it. Uniform should be at least colorable. [Redcoats](https://en.wikipedia.org/wiki/Shako#/media/File:Wellingtons33rd.jpg), anyone? ;P

Shako and red military uniform is also great if you want to look like a Christmas toy soldier, too. xD Hehe
