### ISSUE TITLE
Brick sparkles / high-poly bricks

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1663]
![image](https://user-images.githubusercontent.com/774628/27111225-9ebcfa26-5063-11e7-8632-9b6b001d51fd.png)
Noticed some strange sparkles around bricks, some are also in the middle which seems odd so I took a look at the mesh, why is it so high-poly? Could speed up the builder by making it a plane.
![image](https://user-images.githubusercontent.com/774628/27111389-a9f2052a-5064-11e7-9b0c-1badb963ca19.png)

**Comment by keegan-o** [comment]
Bricks need revision overall, like many builders-- but this will definitely be for beta.
