### ISSUE TITLE
[0.9.0 staging-1602] Need another font for cyrillic in ECO news

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16638]
Cyrillic chars is bolder than Latin chars, so if you use any digits or latin chars in text it'll look bad.
![image](https://user-images.githubusercontent.com/45708377/84499505-66190900-acbb-11ea-9185-a96f590d1f46.png)

**Comment by elfl0rd** [comment]
also "disrocd" :P

**Comment by elfl0rd** [comment]
As far as I know, "fallback" font also contains Latin characters.
Perhaps the best solution is to display the whole article with it?
(In that case)

**Comment by SlayksWood** [comment]
I don't have any changes:
![image](https://user-images.githubusercontent.com/45708377/85100007-acb0bb00-b207-11ea-81af-3562173eaf28.png)
![image](https://user-images.githubusercontent.com/45708377/85100078-da95ff80-b207-11ea-9280-006c5b7666fe.png)

**Comment by gzatravkin** [comment]
> I don't have any changes:
> ![image](https://user-images.githubusercontent.com/45708377/85100007-acb0bb00-b207-11ea-81af-3562173eaf28.png)
> ![image](https://user-images.githubusercontent.com/45708377/85100078-da95ff80-b207-11ea-9280-006c5b7666fe.png)

In screenshot you can see that originally it had shadow (only at russian text, but not at number), and now not. 

Here I added more changes 
https://github.com/StrangeLoopGames/Eco/pull/6279
![image](https://user-images.githubusercontent.com/53317567/85228953-2211bc80-b3bd-11ea-9be7-398558ba7442.png)
