### ISSUE TITLE
[0.9.0 staging-1602] Sometimes I don't have Fill type choosing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16639]
We don't have any 100% case to reproduce it, but it happens sometimes.
![image](https://user-images.githubusercontent.com/45708377/84503882-ad0afc80-acc3-11ea-9c1b-203d38e44739.png)
log is empty:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4770826/Player.log)
@Quadbro Could changes in the crane break it

**Comment by Engimage** [comment]
Confirming, had this once. Can't reproduce.

**Comment by StanKryvenko** [comment]
Need more explanation for reproducing. Can't catch any case in the usual way.

**Comment by Engimage** [comment]
Can't reproduce it on demand.
However when the bug occurs only shape forms are displayed while you hold F (in the top left) however the block with fill types (point, line etc) is not displayed at all.
When the bug happens it stays there no matter what you do. I had to relog to get rid of it, as switching tools and even grabbing another building material did not fix the issue.

**Comment by elegorod** [comment]
It happens almost every day, but hard to say how to reproduce it. It's enough to disconnect from server and connect back, it's not required to restart client fully.

**Comment by IcedForge** [comment]
Will confirm that this is still a previlant happening on the current 0.9.0.0 - beta staging-stable-3 playtest run.

**Comment by Dmittry62** [comment]
I reproduced it several times so I'll take a closer look at this issue.
