### ISSUE TITLE
Wool, Cotton, and Nylon Item Icons

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16630]
We need a list of items involved in the production and then machined production of textiles, with the three we're adding here being Wool from animals, Cotton from a cotton plant, and Nylon from plastic.

New Items:

- [x] Cotton Boll Item: this one could wait till the plant is created by Milenko.
- [x] Cotton Item Icon: the bolls but with no branch like the boll icon has, make it a little pile of them.
- [x] Cotton Seed Icon
- [x] (Raw) Wool Item
- [x] Cotton Fabric Item
- [x] Wool Fabric Item
- [x] Nylon Fabric Item
- [x] Nylon Item (sheets of nylon from an industrial pressure cooker)
- [x] Nylon Chips Item (crushed Nylon ready to be fed into the spin melter)
- [x] Nylon Thread
- [x] Cotton Thread
- [x] Wool Yarn
- [x] Cotton Carpet Block Building Material Item: fabric + composite wood structural support
- [x] Wool Carpet Block Building Material Item: fabric + composite wood structural support
- [x] Nylon Carpet Block Building Material Item: fabric + composite wood structural support
- [x] Cotton Curtains Block Building Material Item: only fabric + support rod
- [x] Wool Curtains Block Building Material Item: only fabric + support rod
- [x] Nylon Curtains Block Building Material Item: only fabric + support rod

Design Doc:
https://docs.google.com/document/d/1ZWJq5l0Ba280IiOf5PseQvx5tgfWaiHdTR1SJFBWCr0/edit?usp=sharing

**Comment by RobertMangano** [comment]
icons added to sprite asset and icon sheet 04

**Comment by RobertMangano** [comment]
icons done and added to the icon sheet 04 and sprite asset 04, however items are not yet in the item list

**Comment by keegan-o** [comment]
Thanks Rob!
