### ISSUE TITLE
9.0 1602 - Map not displaying elements correctly

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16640]
Map is not showing elements ie crafting, cooking, research etc etc

![image](https://user-images.githubusercontent.com/61889138/84522020-cc0e8c00-accd-11ea-9352-e80d03f7dba1.png)

![image](https://user-images.githubusercontent.com/61889138/84522127-fa8c6700-accd-11ea-921a-8ea15ec5af8a.png)

River also no longer has water?
Had to unselect everything then select them again for it to appear

**Comment by beastyn** [comment]
@MishkaFur thank you for the report.
Can you make a screenshot with your graph settings?

I will leave this for icons issues for now,
@gzatravkin You can check it on the playtest. Just login, mark all the checkboxes for settings, then lodout ang login again. You won't see the icons.

**Comment by MishkaFur** [comment]
@beastyn 

![image](https://user-images.githubusercontent.com/61889138/84700015-6c70e480-af4a-11ea-9e22-929b05f02dc2.png)

**Comment by beastyn** [comment]
@MishkaFur thank you
I will make a separate issue for water investigation. icons are fixed. Let's continue there #16684.
