### ISSUE TITLE
[0.9.0 staging-1602] issues with oil refinery and water supply 

### ISSUE THREAD

**Issue by Tinytina79** [StrangeLoopGames/EcoIssues#16649]
Time of finding: 10 June we did testing to try and make it work different ways but was happening before and is still.

Play test version [0.9.0 staging-1595] and before

Bug/issue:
oil refinery wont stay working for more than 24hrs, without needing to be picked up and placed again, without giving an issues with water supply. tried both plumed in to its own water with multiple pumps and with 2 different water sources and 2 different pumps and still having same issue with the error and pump not working properly. Have tried having it close to water supply and further away with no change. Also tried both mechanical and Electric pumps to pump the water

have tried having it on its own plumbing and in with other items like blast furnace and happens either way. 
blast furnace  however stays working even when the oil refinery dose not

**Comment by Tinytina79** [comment]
![image](https://user-images.githubusercontent.com/36784025/84592669-bb574500-ae8a-11ea-9c43-941f73c38ed9.png)

![image](https://user-images.githubusercontent.com/36784025/84592673-cb6f2480-ae8a-11ea-9b35-470db28b3a9d.png)


constantly flicks between the 2 different screens

**Comment by Daisy-Wheel** [comment]
The same issue with blast furnaces. Replacing helps only for a short period of time.

**Comment by beastyn** [comment]
https://i.gyazo.com/079afd1b44758421dddd2d88cbfaeaed.gif

Just placed an oil refinery and had this. But it actually worked, just with this lag.

Can you provide a log file and a save?

**Comment by Tinytina79** [comment]
yes what happens in the video you put up is what happens the refinery works slowly whilst it dose this, i will see about getting the save and file log for you.

**Comment by evanah64** [comment]
We are experiencing this exact same issue. Also Staging 1602 and happens to all items using water. Blast furnace, Sinks, Oil Refinery and Froth Flotation Cell. We tried all the same things listed in original post as well as server restarts. Can't replicate why it starts happening or why sometimes replacing the pump with a new one works momentarily but it will start the exact same thing in beastyn's GIF at some seemingly random point. Happens to everyone regardless of on shared power/water/pump sources or running independently.

**Comment by TheKye** [comment]
Here is the save files requested from @Tinytina79 
The issue hasn't caused a server crash or error so there is no server log file to provide

https://mega.nz/file/aChylSIJ
Encryption Key: #KVfgx-GsgSZiLEDFCU5LNujXSHJFk_v29P2MXGhqYAY

**Comment by revtje** [comment]
Have the same issue on both an oil refinery and a blast furnace. It crafts the items but very slowly. Water supply status is switching between working and not working

staging-1605

**Comment by Engimage** [comment]
Confirming the issue on oil refinery. It seems to work 1 tick out of 3.
This is a real issue...

**Comment by mirasrael** [comment]
Happens when all orders blocked/finished. Easiest way to reproduce - add an order and then Off and On a table.
