### ISSUE TITLE
Low FPS on gtx 1080 and i7 processor (which are also being barely used)

### ISSUE THREAD

**Issue by copvampire** [StrangeLoopGames/EcoIssues#1664]
I.m running a pretty high-end PC, (attached the DxDiag.txt to give you that help if needed) but with the max settings I get 30 fps, I can turn whatever settings I want down it does so little improvements to the fps. The weird thing about it also, my 1080 and CPU are being barely used at the settings I have set.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1073285/DxDiag.txt)

Settings:
Shadow Quality: Fantastic
Foliage Quality: Max
Render Scale: 125%
Field of View: 60
View Distance: 100
Minimap Detail About half
Interface Scale: 90%
Music: 0%
SFX: 20%
Mouse Sensitivity 8.85
In advanced they are all ticked but "Lock time to Noon"

Any help would be appreciated, as I feel something is going wrong with either my setup or the game that needs to be fixed <3

**Comment by metachronism** [comment]
- Renderscale above 100% has little to no noticable effect, but greatly impacts the performance of all the post effects (everything under "advanced")
- Minimap is not optimized.  If you don't need it open, its best to close it.
- View distance has the largest effect on performance.  Trees/Forests specifically are very hard on performance right now.

**Comment by copvampire** [comment]
Turning the render scale to 100% or anything below that gives a slight improvement with making the average fps 40-50, so only adding 10.
I don't have the minimap ever open.
I also set the view distance down in intervals, it made no major difference, only adding 1 or 2 fps. But setting it to the lowest (I guess this game has V-sync) locked the fps around the 59.1 - 60 mark, but having no view of the world is kinda useless, which is why I left it at 100.

**Comment by metachronism** [comment]
Both "realtime reflections" and "global illumination" will have by far the largest effect on performance.

Both of these options re-render the scene multiple times, so they can have a huge negative impact on performance, with global illumination being the most expensive.

**Comment by copvampire** [comment]
I guessing over time them two options will become less expensive on the power needed to run it as not being able to run it on a 1080 is kind of a problem. But disabling them both seemed to make it max out at the vsync cap of 60 (which I hope soon can be an option to be removed)

**Comment by SeanAtr0n** [comment]
Not sure why we have the option for >100% render scale... i'll reduce that and look into vsync

**Comment by SeanAtr0n** [comment]
I'm submitting a PR with a vsync option and it caps render scale down to 100%. Obviously we will continue to look for performance optimizations as well. (This bug will auto-close when it goes through, feel free to reopen this if you think I missed something)
