### ISSUE TITLE
9.0 1602 Unable to pickup rubble in a stockpile

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16643]
Tested with Rev too incase it was an issue with my char.

Since 1602 I am unable to pickup pieces of rubble that are in a stockpiles area, it only selects the stockpile, this was working fine pre 1602

![image](https://user-images.githubusercontent.com/61889138/84537405-8eb6f800-ace7-11ea-9534-26687e6b3109.png)

**Comment by elfl0rd** [comment]
If possible, place fallen "in stockpile" items in it, it will solve many problems and provide new interesting mechanics.

**Comment by revtje** [comment]
Got the same. Managed to drop my wodden cart handles so they are inside a stockpile. Had to /freecar because I couldnt use the cart

**Comment by MishkaFur** [comment]
With the cart issue that @revtje had, if i claim the land then place a stockpile, his cart is effectively then locked in and impossible to use.

**Comment by SlayksWood** [comment]
still an issue.

**Comment by SlayksWood** [comment]
Need to add garbage too
