### ISSUE TITLE
Seating problems

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16644]
As i mention in - https://github.com/StrangeLoopGames/EcoIssues/issues/13371#issuecomment-543110473
still an issue
![изображение](https://user-images.githubusercontent.com/4980243/84380446-06096080-abf0-11ea-906c-3d948c0ccfec.png)

also seating on benches...
![изображение](https://user-images.githubusercontent.com/4980243/84380574-3a7d1c80-abf0-11ea-8af4-92c558751f93.png)

Couch - still not have sit.
![изображение](https://user-images.githubusercontent.com/4980243/84380680-6ac4bb00-abf0-11ea-87e0-03a7270e1c38.png)

In vehicle - still issue
![изображение](https://user-images.githubusercontent.com/4980243/84380800-a8294880-abf0-11ea-8f60-9e235efc0d84.png)
![изображение](https://user-images.githubusercontent.com/4980243/84380824-b0818380-abf0-11ea-901a-31267665d254.png)

**Comment by beastyn** [comment]
As I mentioned< I will make separate ssues
