### ISSUE TITLE
 [0.9.0.0 Staging 1602] Unable to enter 1000 as amount for executive action payment

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16659]
Entering 1000 turns it into 1. Entering 999 works. Entering 1001 turns into 1.001, which is unclear if it's a decimal or separator for thousands. Might be related to locale formatting.. This was on the playtest server. 

Video showing the issue:
https://www.dropbox.com/s/b7r6n9ea3p2mqhm/Desktop%202020.06.14%20-%2001.04.27.01.mp4?dl=0

**Comment by trickenso** [comment]
On local game (and UK number settings) 1000 works fine for me, but 1.000 and 1,000 both become 1.

**Comment by beastyn** [comment]
@henrikolsson thank you for the report.
Can you provide a log file?
Which language do you use on client and server?
Which language your OS is using?

**Comment by beastyn** [comment]
I assume it has the same reason #16655
