### ISSUE TITLE
[0.9.0 staging] Additional missing tag sprites

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16650]
Sorry my previous list was not complete. There are a few more sprites we need:

- [x] Game action: Global Timer (A timer that is just based on the time in world passed)
- [x] Game action: Citizen Timer (A timer related to actions of a specific citizen)

Currently all levels of upgrade use the same tag sprite, so ideally we will have two more.

- [x] Tag: Basic/Advanced Upgrade
- [x] Tag: Advanced/Modern Upgrade
- [x] Tag: Modern Research

The previous round looks great!

**Comment by RobertMangano** [comment]
icons checked in and added to eco scene
