### ISSUE TITLE
[0.9.0.0 Beta Staging 1602] Minor UI Glitch - 'Propose Law' button

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16656]
'Propose Law' in the top right looks broken (works fine, though)

![image](https://user-images.githubusercontent.com/48172405/84575084-b3bc7100-ada2-11ea-8f6a-dc87e9fc8b9f.png)

**Comment by SlayksWood** [comment]
dup #16621
