### ISSUE TITLE
USER ISSUE: Tilled tiles become dirt again too fast

### ISSUE THREAD

**Issue by ExplodedPuppy** [StrangeLoopGames/EcoIssues#16653]
![Naamloos](https://user-images.githubusercontent.com/66786674/84572872-46f2a800-ad9d-11ea-8808-f434b15a565d.png)
\
**Version:** 0.9.0.0 beta staging-1602

**Steps to Reproduce:**

**Expected behavior:**
It should take much longer for this to happen

**Actual behavior:**
plowed tiles become dirt again too fast. Like on a scale of a few minutes, part of my plowed fields are becoming dirt again. See attached picture: all spots on that field were converted to dirt in about 5 minutes.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Thanks you. Have it here #16607
