### ISSUE TITLE
[0.9.0.0 Staging 1602] Unable to target construct/deconstruct of Stone Ramp with laws

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16658]
Neither "Construct/Deconstruct" nor "Drop/Pickup Block" has Stone Ramp available in item filter. It is available to pick in "Place/Pick Up Object", but it doesn't trigger upon placing or removing a Stone Ramp.

**Comment by trickenso** [comment]
Having the same problem. There is also no tooltip that might indicate what action is the correct one.

**Comment by beastyn** [comment]
Thank you

**Comment by johnkslg** [comment]
I added some ways to override this awhile back with [ConstructWithoutToolAttribute]
Need to update filter to take this into account

**Comment by WeaselDog** [comment]
@olegshegai It is still an issue after the fix. I am going to unassign myself but please let me know if you need anything else from tech tree. I think we need to use an attribute to get those items to register.

**Comment by SlayksWood** [comment]
@WeaselDog @olegshegai @johnkslg 
Is it right that 1ramp takes like 4 blocks in law? If I place/pickup 1 ramp I get 4  paid/tax:
![image](https://user-images.githubusercontent.com/45708377/87005475-b6ef2500-c1c7-11ea-8dee-ddac9303f87d.png)

**Comment by johnkslg** [comment]
seems fine
