### ISSUE TITLE
[0.9.0 staging-1602] Wooden Elevator is invisible

### ISSUE THREAD

**Issue by stavlor** [StrangeLoopGames/EcoIssues#16651]
Placing Wooden Elevator in Eco 9.0 staging-1602 Wooden Elevator is invisible and cannot be targeted/interacted with.
https://storage.googleapis.com/stavlor-storage/ShareX/2020/06/Eco_2020-06-13_11-00-16.jpg

https://storage.googleapis.com/stavlor-storage/ShareX/2020/06/Eco_2020-06-13_11-00-50.png

**Comment by beastyn** [comment]
Thank you for the report.
Did relog help you?

**Comment by stavlor** [comment]
No, it appears to be completely invisible for all users but shows in world at that location when tagged in chat. Was working in prior builds it's just invisible and can't be collided with or interacted with for clients on 1602. Even when /give Wooden Elevator, 1 and replacing it doesn't appear for us.

**Comment by SlayksWood** [comment]
@stavlor is it official playtest? or you can provide saved files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by stavlor** [comment]
I can provide world files if you think they would be useful, but i can replicate the issue locally also by creating a new world, and /give Wooden Elevator, 1 as the shadow of the elevator shows when placing but the second you place its invisible in staging-1602 
This was done in a local game via /give Wooden Elevator, 1 and /give Dev Tool
Shadow of the item appears the second its placed it can't be seen also you can't collide with it.
https://storage.googleapis.com/stavlor-storage/ShareX/2020/06/Eco_2020-06-15_08-24-46.jpg

**Comment by stavlor** [comment]
Note issue persists in 9.0 staging-1605

**Comment by beastyn** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4796527/Player.log)
после установки лифта

**Comment by olegshegai** [comment]
Prefab is fixed and commited to the SVN

**Comment by stavlor** [comment]
Thankf for fixing the issue.
