### ISSUE TITLE
Air polluters need to pollute at different rates

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1665]
After testing a single stove for a few hrs I got what appears to be max air pollution spread so we also probably need to reduce the rate for everything as well.

![image](https://user-images.githubusercontent.com/774628/27112254-be5aaeda-506a-11e7-9284-014508992bbc.png)

**Comment by craig-jong** [comment]
this is fixed in staging only like 6 months later
