### ISSUE TITLE
[0.9.0 staging-1605] Seating: wooden bench need revamp

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16669]
Can't seat properly on the composite, hewn, lumber benches
![84380574-3a7d1c80-abf0-11ea-8af4-92c558751f93](https://user-images.githubusercontent.com/27898520/84658715-bb5d5080-af2f-11ea-80da-e6d63c1bc158.png)

**Comment by StanKryvenko** [comment]
fixed in SVN
