### ISSUE TITLE
Recurring payment confirmation, but still have benefits

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#16667]
Wanted to upgrade to dev tier here but I met the following issue.
Completed the payment via PayPal, got email reciept from there as long as notification from my bank about blocked costs.

However on the site I am getting this
![image](https://user-images.githubusercontent.com/38317412/84648428-b8516880-af0d-11ea-95d5-f5749849b948.png)

And after pressing the button
it is stuck in this state
![image](https://user-images.githubusercontent.com/38317412/84648521-d28b4680-af0d-11ea-82c3-a21275c5c020.png)

And every time I go to "Upgrades" I get same popup.

Seems the process is half complete, so need this confirmed/finished/fixed whatever

**Comment by Engimage** [comment]
It seems that most of the assets are granted for the dev tier pack
![image](https://user-images.githubusercontent.com/38317412/84654643-361a7180-af18-11ea-90f6-acee9bdb11b4.png)
However the popup with "Complete Order" appears on every page I go in my account.

**Comment by rainfarmer** [comment]
@Engimage thanks for the feedback.
So, is the issue, your bank delayed the payment, so eco website went in loop waiting for payment?

**Comment by Engimage** [comment]
@rainfarmer Nothing was delayed. Payment went through as per PayPay and Bank
![image](https://user-images.githubusercontent.com/38317412/84700820-8adfdb80-af5c-11ea-9173-cf5d5b453a88.png)
But the issue is that site itself did its job only partially. You can see it states I have access to source code and I got 3 invites - as it should for dev pack. However on any account page the popup appears to "Complete Order". I can just click to the side of it and it disappears. If I click "Complete Order" it freezes.

**Comment by rainfarmer** [comment]
@denysaw can you make sure confirmation popup doesnt keep showing if user closes page without confirming.

And check the rewards are not updated until confirmation and payment from IPN is processed.

**Comment by denysaw** [comment]
@rainfarmer Hm... But rewards are updating only on IPN confirmation as I remember, so it was probably called...

**Comment by denysaw** [comment]
Fixed in `release` branch and on Production environment.
