### ISSUE TITLE
[0.9.0 staging-1605] Seating: solve backpack mystery

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16668]
Some of our players really want to make creative changes with a backpack while sitting on a chair, so a backpack won't go through chair's (or vehicle's) back.

![84380446-06096080-abf0-11ea-906c-3d948c0ccfec](https://user-images.githubusercontent.com/27898520/84656128-a1217380-af2b-11ea-8336-38360df75657.png)
![67001012-8ae3bf00-f0e1-11e9-8696-8bd23020b3da](https://user-images.githubusercontent.com/27898520/84656133-a252a080-af2b-11ea-9224-23ae6c87c9db.jpg)

**Comment by elfl0rd** [comment]
How in looks in vehicles
![изображение](https://user-images.githubusercontent.com/4980243/84380800-a8294880-abf0-11ea-8f60-9e235efc0d84.png)
![изображение](https://user-images.githubusercontent.com/4980243/84380824-b0818380-abf0-11ea-901a-31267665d254.png)

And my first comment about it - https://github.com/StrangeLoopGames/EcoIssues/issues/13371#issuecomment-543110473

>I think, seating pose need to be improved.
>In vechicles (any) just hide backpack and tools from avatar.
>At "objects"
>Hide, or place backpack on ground, as if the player took it off and put it next to him

**Comment by keegan-o** [comment]
For sure, @StanKryvenko please look into the avatar equipment code and the world object interaction types and interaction 'mount' for vehicles and chairs to see if we can have the avatar always hide 'back' equipment while mounted or sitting.
