### ISSUE TITLE
[0.9.0 staging-1605] Graphs don't work in Gibberish

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16666]
Step to reproduce:
- start server in Gibberish
- try to use graphs:
![image](https://user-images.githubusercontent.com/45708377/84642364-0746d000-af05-11ea-901c-5e8d6e1adb79.png)

**Comment by j3fffff** [comment]
should they be in gibberish? do they work in real languages?

**Comment by gzatravkin** [comment]
Was broken in all localizations, and should be fixed now. 
https://github.com/StrangeLoopGames/Eco/pull/6373
