### ISSUE TITLE
[0.9.0 staging-1605] Need to hook up Icon for Core Block (Also re-name Core to Lower Crust)

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16663]
Impenetrable Stone Block:
![image](https://user-images.githubusercontent.com/45708377/84626354-9b0ca200-aeed-11ea-9e2d-e41f35acc7ed.png)

**Comment by keegan-o** [comment]
@RobertMangano These are the blocks at the very bottom of the world which the player cannot dig or mine through-- basically, the lower boundary of the world. IRL, this is not so much magma/lava as where the rock is hot enough and bendy enough to destroy drilling equipment. I think it would make sense to have an icon that is like a shearing and steamy rock. So basically, a subtle almost cooled lava kind of look. 

Also, we should not name this layer 'Core'. Core is like the center of the planet, way far beneath any possible drilling. We should call it 'Deep Crust', I think. Another option would be 'Moho', but humans have yet to succeed in drilling that far down so it'd be a bit silly to get there by digging. @WeaselDog Can you look into that re-name?

**Comment by RobertMangano** [comment]
icon is done but in unity i can't find it in the core item in the eco scene

**Comment by beastyn** [comment]
@keegan-o @WeaselDog anyone for the help here?

**Comment by keegan-o** [comment]
@Quadbro @StanKryvenko @serpopov Did one of you guys implement the drill UI? If so, perhaps you know where the 'Core' icon is?
