### ISSUE TITLE
Get hosted worlds working on title screen.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16661]
- [x] Get staging account server setup and working and used by staging builds, with plans for how to add it to release process implemented.
- [x] Verify that when you login with a 'citizen' account, or an account which has a hosted world associated with it, that world is shown on the screen.
- [x] Verify that citizen accounts can only join these, not start their own games or join other servers
- [ ] Verify that 'new game' will give you the option to start a hosted world, taking you to the correct webpage, and with a flow that makes sense for both steam and non-steam users.

**Comment by johnkslg** [comment]
These features all worked at one time btw, just need to check and restore what's not working.

**Comment by redwyre** [comment]
Afaik, the first three issues work correctly

**Comment by johnkslg** [comment]
They need to be tested and verified because they havent been looked at in months.

**Comment by mirasrael** [comment]
Last option was implemented as "Host you Own World" (details here https://github.com/StrangeLoopGames/Eco/pull/4349)

**Comment by redwyre** [comment]
Can you guys do a QA pass on this because it seems like everything is done.
