### ISSUE TITLE
9.0 1602 - Law verbose covers toolbar

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16673]
Law verbose covers the the toolbar not letting you see quality that is being held, needs to be shifted up a bit, its as if it has a max top position and the lower will just cover things, could it just be wider?

Placing which has less text does not have as much of this issue

![image](https://user-images.githubusercontent.com/61889138/84691561-46444800-af3c-11ea-9ccb-ae3f5ae70b3a.png)

![image](https://user-images.githubusercontent.com/61889138/84691707-7e4b8b00-af3c-11ea-8521-d6b0f2bfb145.png)

**Comment by SlayksWood** [comment]
Make this like OK/Confirm box
