### ISSUE TITLE
Upgrade modules effect is only calculated at time of queue, not craft of each piece.

### ISSUE THREAD

**Issue by Danevolent** [StrangeLoopGames/EcoIssues#16671]
Tested with rocker. Queued a sand craft for 2 pieces. Added the module after the queue was made, then observed that the second piece did not craft quicker.

**Comment by mirasrael** [comment]
Module only affects crafts which started when Module installed. If you have craft in progress, install a module then current craft will finish without the module effect, but next craft will be performed with module. Same when module removed. If you remove module then it will complete current iteration with module benefits, but next will be performed without.
At least it worked this way. If it changed then probably something was broken...

**Comment by mirasrael** [comment]
Also iteration counted as started as soon as resources and time calculated (not when actual progress started).

**Comment by beastyn** [comment]
I've checked. If module was plugged after iteration was started time was remaining the same. The next iteration was properly updated. So, work as intended.
