### ISSUE TITLE
[0.9.0 staging-1605] Seating: couch is unseatable

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16670]
I want to sit on this pretty soft couch. But there is no Sit placement. 
![bandicam 2020-06-15 17-55-11-865](https://user-images.githubusercontent.com/27898520/84659782-60c4f400-af31-11ea-912a-9afc396f6313.jpg)

**Comment by MazonDel** [comment]
The commit was made to the SVN as this was a problem in the prefab itself.
