### ISSUE TITLE
[0.9.0 staging-1607] Glitches of UI in "Elected title" election.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16679]
1. Two-digit numbers are trimmed:
![image](https://user-images.githubusercontent.com/45708377/84737435-9bba3c80-afb0-11ea-9cfe-846e4f381f4f.png)
2. If there are many candidates, then the page looks a little crooked:
![image](https://user-images.githubusercontent.com/45708377/84737567-d7ed9d00-afb0-11ea-9a63-1b1fe318252a.png)
Column with selecting ranks for candidates is very big.

**Comment by j3fffff** [comment]
fixed, we have new ranking system
