### ISSUE TITLE
Error when querying voice token

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16675]
Getting an internal server error for voice when querying "https://auth.strangeloopgames.com/voice/join-token"
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>

Three problems here:
- Our auth server is failing
- Our auth server is not sending back the error
- The eco server is trying to parse this html as json

**Comment by redwyre** [comment]
Despite being spammy, the server side code should continue fine (it's wrapped up in try/catches a little higher). I'll re-arrange some stuff and make it fail quicker when it gets a bad response.

Auth server is not actually logging exceptions properly so I'll change how that works.

**Comment by redwyre** [comment]
@johnkslg do you have the callstack of the error on the server?

**Comment by redwyre** [comment]
This is fixed in staging, but it might be a while before it gets into release

**Comment by redwyre** [comment]
I should note this fix is for the handling of errors, and much improved logging in the auth server. So if the original problem occurs again, it should be easy to track down.
