### ISSUE TITLE
Add a Join our Discord banner to Steam

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16678]
Like Satisfactory has:
![image](https://user-images.githubusercontent.com/3536496/84734444-b0b5b200-af55-11ea-9bf4-da75a1681ae6.png)

**Comment by D3nnis3n** [comment]
![screen](https://user-images.githubusercontent.com/25908592/84826621-7fa3b300-b023-11ea-8619-0b5473699610.png)

Done
