### ISSUE TITLE
Extend notifications to specially include elections

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16676]
![image](https://user-images.githubusercontent.com/3536496/84716078-10489900-af27-11ea-8e99-f0a5eef5bdac.png)
Add a new third icon here for elections that need your vote (get the icon from Rob)
When you login, this button should glow if there are new notifications waiting.
The label inside the list should say 'Elections which need your vote', and the only way to get rid of them is to vote.

**Comment by trickenso** [comment]
This will solve #16244

**Comment by RobertMangano** [comment]
![election notification](https://user-images.githubusercontent.com/26705633/84976553-8c332300-b16b-11ea-8fc8-98b9f8e9ead5.jpg)
something like this?

**Comment by RobertMangano** [comment]
checked the icon in on the sheet UI_Elements_02_TUTORIAL

**Comment by beastyn** [comment]
Icon is missed. Check please
![bandicam 2020-06-24 15-03-17-215](https://user-images.githubusercontent.com/27898520/85536156-47583200-b62c-11ea-8a99-96d960e6d08c.jpg)

**Comment by gzatravkin** [comment]
checked in
