### ISSUE TITLE
[0.9.0 staging-1605] Laws Web UI - No indication of whether you've voted

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16672]
I have no idea from this:
![image](https://user-images.githubusercontent.com/48172405/84679419-2eaf9400-af29-11ea-92eb-23f765c17519.png)

Separate elections into 'voted' and 'not voted'? Some kind of highlight if you've already made a choice for the election you're viewing?

**Comment by beastyn** [comment]
Actually, you should see highlighted vote and button should be called "Update Vote"
Did you have such issue on the playtest server or locally?
![bandicam 2020-06-17 10-57-10-523](https://user-images.githubusercontent.com/27898520/84861050-ad234780-b089-11ea-893b-a97175433fe2.jpg)

**Comment by trickenso** [comment]
Cannot check in playtest right now because of bugged law - in local it works as you suggest:
![image](https://user-images.githubusercontent.com/48172405/84905382-7e689980-b0a8-11ea-9ce3-9d578510e581.png)
I will test in Imperial Otter when it is possible to do so.

It would still be useful to see elections I have not yet voted in without having to click each law individually.

**Comment by beastyn** [comment]
Yeah, so we have this #16676

And we can add a label to the active elections in the web, I think.

**Comment by trickenso** [comment]
An indication once you've reached the web interface would avoid lots of clicking around.

**Comment by trickenso** [comment]
This will be solved by #16782
