### ISSUE TITLE
[0.9.0 staging-1608] Civics: districts are breaking through the map 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16687]
1) Create a district map (put a lot of districts for an intertaiment purpose)
2) Make some modifications and propose
3) Leave a map in the election state
4) Restart server.

Server will tell you that the poor districts have lost their home
![bandicam 2020-06-16 17-21-46-032](https://user-images.githubusercontent.com/27898520/84773472-e3af8280-aff5-11ea-895a-7d11eb32388b.jpg)

And then he will add them to the Zoning Office. Yeap, not to the map. To the table.
![bandicam 2020-06-16 17-22-42-828](https://user-images.githubusercontent.com/27898520/84773559-004bba80-aff6-11ea-9ef3-cb1ce01cc267.jpg)

And you can't delete them as Constitution won't work with Districts.

**Comment by SlayksWood** [comment]
Maybe a little change this system with auto-adding lost civics objects to any table. And change it to work party system when it will propose to you add this law to table:
![image](https://user-images.githubusercontent.com/45708377/84774295-47ca4a80-afe6-11ea-94a0-239fe9a995c8.png)

**Comment by MishkaFur** [comment]
This has happened on the playtest @beastyn but......with odder results, no districts were waiting to pass election but only one was in a edited state (Govt Infrastructure)

Bank V2, Bank, Court V2, Court and Glorius HQ V2 are all in the Govt Infrastructure draft not parts of Road Districts or Bank? somehow

![image](https://user-images.githubusercontent.com/61889138/84811689-23319b00-b005-11ea-8f41-3d0b83fe35a3.png)

![image](https://user-images.githubusercontent.com/61889138/84811725-2dec3000-b005-11ea-81ae-312346983639.png)

![image](https://user-images.githubusercontent.com/61889138/84811804-5116df80-b005-11ea-86e8-881672f8c3a3.png)
