### ISSUE TITLE
9.0 1602 Water on map issue

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16684]
From #16640

Map does not show water layer
![84522127-fa8c6700-accd-11ea-921a-8ea15ec5af8a](https://user-images.githubusercontent.com/27898520/84752833-b5bb4580-afd7-11ea-9f02-0e7da06741d4.png)
![84700015-6c70e480-af4a-11ea-9e22-929b05f02dc2](https://user-images.githubusercontent.com/27898520/84752935-d8e5f500-afd7-11ea-8700-a6acf3123b78.png)

**Comment by MishkaFur** [comment]
Rev is also having the same issue so do not beleve its an issue with only my settings

**Comment by beastyn** [comment]
@MishkaFur  Well, lets have your log here in any case )

**Comment by beastyn** [comment]
@MishkaFur  did you meet this one the last playtest?

**Comment by MishkaFur** [comment]
> 
> 
> @MishkaFur did you meet this one the last playtest?

Yea im still getting it, if i start a fresh world it is fine so this might just be related to the world save on Imperial otter, I have only had this on the current playtest world and it was only after one of the updates it started to happen

PC Spec

PC1 Ryzen 2700x, 32GB Ram, GTX 1660, Windows 10 2004
PC2 Ryzen 2600, 16GB Ram, GTX 760, Windows 10 1903

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4838978/Player.log)

**Comment by beastyn** [comment]
@mirasrael 
I can repro it and on the Otter I did not have it. Maybe you can figure out something.
If its time consuming we can push it till 9.1.

**Comment by SlayksWood** [comment]
> Zooming in and out layers out portions of water regions
> ![white_tiger_weird_stuff](https://user-images.githubusercontent.com/24981362/89471640-f84f0200-d77e-11ea-87f1-787056c38c54.jpg)
> As compared to this where the "shallow" water is clearly there, but on zooming in it removes a layer of water displaying dirt & rock instead.
> ![Screenshot_370](https://user-images.githubusercontent.com/24981362/89471666-0866e180-d77f-11ea-8a24-59c8a523f52f.jpg)

**Comment by IcedForge** [comment]
Hiogu has the same issue, myself i dont and i got the same settings as she does.
![Screenshot_1223](https://user-images.githubusercontent.com/24981362/89590403-1df40e00-d848-11ea-88f8-e0170673b168.jpg)
Hiogus DxDiag.txt
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5038406/DxDiag.txt)
Mine - Ice Forge DxDiag.txt
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5038414/DxDiag.txt)

**Comment by mirasrael** [comment]
Should be fixed, but on old worlds you may need to call /land resetworldcaches

**Comment by beastyn** [comment]
@MishkaFur would be nice if you check with the next playtest update. Thanks.
