### ISSUE TITLE
[0.9.0 staging-1607] Wrong order in message for buying/selling in notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16680]
![image](https://user-images.githubusercontent.com/45708377/84739124-bc37c600-afb3-11ea-9fa7-5dcc7b2d883a.png)

**Comment by gabrielgindridev** [comment]
Seems like the expected behavior is working:
![image](https://user-images.githubusercontent.com/65634950/92940350-65605200-f425-11ea-9e60-415e23df3688.png)

**Comment by beastyn** [comment]
Can we change an order for both chat log and on-screen notification?
1) We say that someone bought(sell) something
2) And then we tell about taxes?
