### ISSUE TITLE
[0.9.0 staging-1605] Balance Issue Crispy Bacon and Simmered Meat

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#16688]
Hi,
actually we do not produce Crispy Bacon on the Testserver cause of its huge amount of Raw Meat needed for it.

I made some Calculations for it compared with Simmered Meat:
All Calculations without Updates !

Medium Animal = 5 Raw Meat

1 Crispy Bacon:
31 Raw Meat (-7 Raw Meat for Scrap Meat, 4,8 Animals)
20 Scrap Meat (Equivalent of -7 Raw Meat is not needed for Crispy Bacon)
4 Raw Bacon

1 Simmered Meat:
8 Raw Meat + 1,2 Raw Meat From Bacon Recipe (1,8 Animals)
4 Scrap Meat (8 Needed, so +4 needed  , take +4 from Crispy  Bacon Recipe = 1,2 Raw Meat equivalent)
2 Prepared Meat

1 Simmered Meat = 1,8 Animals = 9 Raw Meat
1 Crispy Bacon = 4,8 Animals = 24 Raw Meat

I would say its okay to make it a little more expensive then Simmered Meat because you need it for the last 2-3 food exp points, but from 9 to 24 is too hard for me. 

Even with BU4 (Butchery Table) and AU3 (Cast Iron Stove) its not that cheaper.

Best regards,
mepHy

**Comment by WeaselDog** [comment]
Thanks for the feedback. We have adjustments to the Raw Bacon cost coming in 9.1, as well as increased Calories provided for Crispy Bacon.
