### ISSUE TITLE
[0.9.0 staging-1607] Empty information in some places

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16686]
It just happens
When you have created a contract
- Empty info about contract on contract board
- Empty information in the right Work panel
![bandicam 2020-06-16 14-54-18-926](https://user-images.githubusercontent.com/27898520/84761148-747c6300-afe2-11ea-8a55-f21646e2284b.jpg)

Can be connected to #16681

**Comment by gzatravkin** [comment]
Please check after https://github.com/StrangeLoopGames/Eco/pull/6255 , proabably it will fix it too

**Comment by beastyn** [comment]
Got it
