### ISSUE TITLE
Engineering Labor for Repairing Late Game Tools

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16696]

**Comment by WeaselDog** [comment]
To be clear, we want to add labor costs to repair? And we want to change Modern Tools to be made and repaired by Industry?

**Comment by WeaselDog** [comment]
Going to close as we do not want Basic Engineering to repair modern tools.

**Comment by trickenso** [comment]
Basic Engineering =/= Engineering

Sounds like confusion between the profession and the specialty.
