### ISSUE TITLE
'Basic Engineering' Specialty

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16699]
The Basic Engineer is the first specialty in the Engineering Profession. It unlocks invention of the first vehicles for transportation, and it is the cornerstone of initial progress towards industrial production. **Basic Engineering allows the first wheels and the first roads.** Basic Engineering scales and retains relevance by being the specialty associated with **late game road creation as well, with asphalt roads**.

Also, **all vehicles should require maintenance and repair which basic engineers could provide labor and/or materials for**. Tires are one obvious component that could need replacement, if perhaps as part of maintenance we require specific items as ‘fuel’. The Shoulder Basket could also require maintenance, giving an upkeep cost to its benefits of an expanded carrying capacity. Engineering labor could be required for **repairing late-game hand tools as well.**

**Comment by WeaselDog** [comment]
Closing as all of these are implemented except the Vehicle repair which has its own issue and Shoulder Basket which has its own Epic.
