### ISSUE TITLE
Shoulder Basket [Equipment]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16693]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0681c04a-3ee0-4ddf-81b4-f02fb79f5c5d)
The Shoulder basket is a way to **double or triple the carrying capacity of a player in Eco**, in particular to assist with digging, logging, and mining operations that involve **traversal of areas not passable by vehicles**. The bonus will not exceed tripling the carried slot, in order to avoid impinging on the role of small vehicles like the cart. It is a way to drastically cut back and forth movement for operations which players do not want to expand into a large extraction site with roads and vehicles. 

The shoulder basket will not just double or triple the size of the carried slot, but effectively grant two **new carried slots that can be filled with unique materials**. This will **solve an annoying problem of being incapable of holding some amount of two different block items the same time**. 

The shoulder basket should have a few downsides, again to ensure that it does not infringe excessively into the role of vehicles. **Carrying it and especially running with it should cost more calories**. It should not change the style of movement the character can engage in though, the whole point is to allow additional carrying with the base movement of the player. 

The shoulder basket should be very easy to equip and have automatically appear on your character. It should sit in a new equipment slot or in one of the 'back' slots, and basically just be a visualization tied to your second and third carry slots, which when activated causes the shoulder basket to appear and also initiates the higher calorie cost of moving while carrying so much. Part of the idea with having it have its own slot is that later on we could add a different kind of upgrade to replace it with, like an exoskeleton rig for expanded carrying, or a one for advanced movement in the end game. But perhaps these could also be fitted to the second 'back' slot we already have.

Basic mockup:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/388bbca7-a9e2-4524-ad65-dfc6446d6038)

**Comment by Krizzoula** [comment]
This would be an absolutely amazing addition to ECO. Having the ability to hold three different types. Dirt, Rock and Logs and once!!! I really hope this gets added! Great concept.
