### ISSUE TITLE
Sync staging db with prod

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16690]
Thinking a weekly cron job that exports prod db to staging db. via jenkins perhaps.
Just need to move 'user' table and 'users_products' table

This will allow us to use staging auth for testing with community

**Comment by redwyre** [comment]
@j3fffff dragging you in for backups

**Comment by j3fffff** [comment]
backup security updated.

**Comment by redwyre** [comment]
This is pushed to 9.0 as Jeff doesn't want to do a sync (accounts with different IDs, will break cloud worlds)
