### ISSUE TITLE
'Mechanics' Specialty

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16709]
As players unlock the Mechanics specialty for Engineering profession, steam power should become the engine of transport and industry. And with this, the race to unlock oil as a fuel. The Mechanics specialty has a big selection of items and vehicles currently, so not much new is needed here for now.

The main things are a wooden pumpjack to support the timeline refactor for engineering specialties (pre-electricity oil extraction), and to fix steam engines to require a water input to function. This could be handled using utilities as well.

**Comment by trickenso** [comment]
To give other professions some stake in this, could this early fuel requirement also include fish and/or vegetable oils?

Whale oil predated petroleum by a couple of hundred years, and it would give fishing some value outside food.
Also, the first diesel engine was demonstrated on peanut oil... Sunflower oil would also work, and wouldn't need a new plant, while giving Farming/Milling some more industrial applications.
