### ISSUE TITLE
0.9.0 staging-1605 disconnect icon

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#16723]
version 0.9.0 staging-1605

I get allot of disconnecting icon in areas that terrain has changed even with 3 ppl online including myself,if i travel to an area that is not "modified" i don't get the icon.When the disconnect icon appears world stops loading
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4790208/Player.log)

**Comment by beastyn** [comment]
@Xao22 Thank you for the report
Can you provide a video and make profiling with mirasrael's instruction?

When problem has happened, you can press F6 and it will record everything what happening in game for next 5 seconds. This data will be saved in a file in same directory where Player.log located (you will see message in chat with path to the file). 

You can place a file into google disk or other storage if its too big for the GitHub.

**Comment by Xao22** [comment]
https://www.mediafire.com/file/xn3oo8wywku6yal/Eco.rar/file

There are 5 records inside if is not enough i can record with a external source just let me know

**Comment by Engimage** [comment]
You can easily see this happening around my house on the playtest server. As I see it the main reason for that is the amount of world data transferred from the server to client during movement. If you are moving towards chunks with a lot of custom tada (trraformed blocks, planted trees etc) server transfers the data to the client as the area becomes in range with a player.

However while the data transfer is actually happening, game client considers this as a disconnect event, displaying red dc icon. This does not actually impact your gameplay, its just the world around you updates gradually. However the DC icon actually bothers people.

As a side effect looking at other players in my area you can see them moving in bursts which confirms that server can not keep up with world updates.
