### ISSUE TITLE
[0.9.0 staging-1609] Web elections: I want nice election header please

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16728]
It does not look nice. Too big font, too much space
![bandicam 2020-06-17 13-06-11-352](https://user-images.githubusercontent.com/27898520/84873278-70148080-b09c-11ea-9416-d00059a678b8.jpg)

**Comment by rainfarmer** [comment]
havent seen that before. did you try ctrl f5 for refreshing browser cache?

**Comment by beastyn** [comment]
Yeap, I did. Grigory has fine screenshots too. Will check tomorrow one more time.

**Comment by gzatravkin** [comment]
Have it too. 
It will appear if description is large ( i.e. the linebreaks are too huge). 
@rainfarmer the description is recently added here https://github.com/StrangeLoopGames/Eco/pull/6260 . 

Here is the new class. Could you fix it? 
![image](https://user-images.githubusercontent.com/53317567/85020651-0604e580-b147-11ea-806c-300292933796.png)

**Comment by rainfarmer** [comment]
fixed

**Comment by beastyn** [comment]
Don't see anything has changed. Cash is cleared with Ctrl+f5 (Chrome)
![Uploading bandicam 2020-07-03 16-57-56-226.jpg…]()

**Comment by rainfarmer** [comment]
its on a branch web-election-styling-redux

**Comment by rainfarmer** [comment]
pr into staging
