### ISSUE TITLE
[0.9.0 staging-1609] Gi Low looks bad

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16726]
Low Global Illumination somehow kills nice render.

No GI
![bandicam 2020-06-17 12-27-43-273](https://user-images.githubusercontent.com/27898520/84868491-35a7e500-b096-11ea-9963-9115ae1c434a.jpg)

Low GI
![bandicam 2020-06-17 12-28-21-465](https://user-images.githubusercontent.com/27898520/84868640-70aa1880-b096-11ea-9964-b38aa8711f56.jpg)

**Comment by keegan-o** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/6268
