### ISSUE TITLE
[0.9.0 staging-1609] Add parameters of "Basic election" to Civics in serverui

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16724]
So admins could change it for yourself. Only "Basic election" now don't have the possibility of any changes.
![image](https://user-images.githubusercontent.com/45708377/84863942-83b0ee80-b07e-11ea-819a-009336ab7a2f.png)

**Comment by johnkslg** [comment]
Can choose a few of the key parameters of this for alteration in config and follow the example with demographics like 'active'

**Comment by johnkslg** [comment]
@SlayksWood what are the few params you'd want to alter here?

**Comment by beastyn** [comment]
I think we need voters here for selection in the list of four basic demographics

**Comment by MishkaFur** [comment]
Config should have the below at a minimum though could just have all the config settings for Basic election
Vote percentage (atm it defaults to 25%)
Vote time (default is 24 but for longer term casual play servers 72hours might be handy or short speedrun 12 hours etc)
Demographic required

**Comment by beastyn** [comment]
parted here #16941
