### ISSUE TITLE
0.9 Tree farms

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#16739]
Planting trees next to each other should not be possible(they should not grow) they cause fps drop by more then 50%.I tested with a tree farm by planting joshua with 2 spaces beetwen them each direction and they don't impact fps at all (fully grow)

Suggestion:spaces betwen them should depend on tree width(volume),or be 3 blocks or more apart from each other

**Comment by Krizzoula** [comment]
This would definitely explain why there is so much impact on FPS near his area.

**Comment by TwixterZ** [comment]
This is now fixed with the introduction of spacing requirement between trees planting for 9.5
