### ISSUE TITLE
0.9 lumber fence textures seam

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16734]
![изображение](https://user-images.githubusercontent.com/4980243/84919772-0c557c00-b0cb-11ea-8679-a3f2a3780a3a.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/98beec21-b272-406f-bbe8-82f549294605)
Refactored lumber fences to make use of triplanars, fixed in develop for 9.1
