### ISSUE TITLE
0.9 lumber - fence orientation under roof is incorrect

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16736]
![изображение](https://user-images.githubusercontent.com/4980243/84920175-7f5ef280-b0cb-11ea-987d-d8682d310b90.png)

w/o roof
![изображение](https://user-images.githubusercontent.com/4980243/84920217-8980f100-b0cb-11ea-9188-afd1a716f116.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/85341340-c1f24780-b49c-11ea-862c-b7e12004ba85.png)

They'll no longer care what type of block is above them other than themselves.

**Comment by elfl0rd** [comment]
> They'll no longer care what type of block is above them other than themselves.

Why? It's bad for me.

**Comment by keegan-o** [comment]
You want them to only show the tops of the fences when there is nothing above them, then?

**Comment by keegan-o** [comment]
The way they have been updated now, they are coherent and self-contained which is the philosophy that applies to all the new blocks and wall types. What if you want a fence but want to put a frame block above it? If you're looking for something that connects totally vertically we should just add a new wall type, rather than a fence.

**Comment by keegan-o** [comment]
Unfortunately as in your example, they won't be able to connect to things other than themselves and also retain the correct rotation. So this is how it will be for now. We can add a thin wall type with a crossbrace at some point.

**Comment by elfl0rd** [comment]
> You want them to only show the tops of the fences when there is nothing above them, then?

Yes, it is good for building farm buildings
