### ISSUE TITLE
[0.9.0 staging-1605] Laws Web UI - Minor text wrapping issues

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16746]
Law with long description displaces pie and vote buttons - would be preferable if it just wrapped the description down the page.
Also overlapping User/Server text in the bottom left:
![image](https://user-images.githubusercontent.com/48172405/84995854-69414880-b144-11ea-8435-61a8dcff20ac.png)
(Using Chrome in 1680x1050, in case that makes a difference)

**Comment by SlayksWood** [comment]
User/Server text in the bottom left here #16623

**Comment by rainfarmer** [comment]
updated on web-election-styling-redux
