### ISSUE TITLE
[Animal optz - WIP]  Animals party hard

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16742]
in different ways.

- [x] 1) Walking on the water (crabs, otters, alligators, turtles)

![bandicam 2020-06-18 12-16-44-027](https://user-images.githubusercontent.com/27898520/84990494-a286b200-b15e-11ea-9e4d-0ed8a19c8ad4.jpg)
![bandicam 2020-06-18 12-16-50-880](https://user-images.githubusercontent.com/27898520/84990504-a581a280-b15e-11ea-9111-ab87f3b6cdf5.jpg)

- [x] 2) Standing on the water and on the ground

![bandicam 2020-06-18 12-17-03-492](https://user-images.githubusercontent.com/27898520/84990544-b6321880-b15e-11ea-9514-b27cc17d35b0.jpg)

And rest like that too
![bandicam 2020-06-18 13-03-52-855](https://user-images.githubusercontent.com/27898520/84994523-3eff8300-b164-11ea-96fb-930e8018c6c1.jpg)

Its pretty surreal sometime
https://drive.google.com/file/d/1VJXWSkEx4LPzZxe_I4MyaMPR5Hm29xa1/view?usp=sharing

- [ ] 3) Animals ignore you (I can see why, they are at the party after all)

- [x] 4) And teleport a lot

https://drive.google.com/file/d/1nQwoQuQDMUti_yV9h7KMqcME_VxinIso/view?usp=sharing

- [x] 5) Making server cry every tick

![bandicam 2020-06-18 12-21-40-522](https://user-images.githubusercontent.com/27898520/84991353-d9a99300-b15f-11ea-971c-e99ff390a3fa.jpg)

**Comment by SlayksWood** [comment]
- [ ] Animal Drift or body rotation by 90 degrees when running when changing direction. You can see different between walking a nd running animal:
https://drive.google.com/file/d/1qU2KtyVCpRDIYnbyP73jjQQfnvPZ2h3y/view?usp=sharing

**Comment by StanKryvenko** [comment]
@beastyn

**Comment by beastyn** [comment]
not everything is fixed yet

**Comment by SlayksWood** [comment]
- [ ]  When almost all of animal(Elk, Deer) die I have this in log:

```
Failed to call AnimationEvent EnableRagdoll of class UnityAnimal.
The function must have either 0 or 1 parameters and the parameter can only be: string, float, int, enum, Object and AnimationEvent. 
(Filename: C:\buildslave\unity\build\Modules/Animation/AnimationEvent.cpp Line: 126)
```

**Comment by SlayksWood** [comment]
Animal still often ignore players and nearby arrows.
