### ISSUE TITLE
Machinist Table Art Polish

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16744]

**Comment by keegan-o** [comment]
It's also one that suffers from the old wood style, let's get an updated texture for the wood parts and an animation for a full polish pass. Updates to mesh are fine too.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/85329324-20acc680-b487-11ea-9d79-13e576e06916.png)

**Comment by RobertMangano** [comment]
object has been checked in, but I have had problems with unity and have not been able to load the game to verify there are no problems with it.

**Comment by WeaselDog** [comment]
Going to mark as fixed an close. Please reply or reopen if you notice any issue with the model.
