### ISSUE TITLE
[0.9.0 staging-1610] Ecopedia missing links part 2.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16741]
Russian:
![image](https://user-images.githubusercontent.com/45708377/84986208-d7870a80-b146-11ea-810c-2dddfc7cafbe.png)
French:
![image](https://user-images.githubusercontent.com/45708377/84986429-39477480-b147-11ea-804d-0738bcc7c7d8.png)
German:
![image](https://user-images.githubusercontent.com/45708377/84986676-9d6a3880-b147-11ea-9e65-f0c691738c5e.png)

**Comment by Quadbro** [comment]
@SlayksWood such thing happens when page is not added to localized ones, this will be a regular issue, but will be fixed every one/two weeks with localization updates (from now)
