### ISSUE TITLE
[0.9.0 staging-1610] Crane don't place "new block forms"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16740]
Can't build with Crane when use some "new" block forms. For example Chimney and Float stairs:
![image](https://user-images.githubusercontent.com/45708377/84981992-65aac300-b13e-11ea-9bd6-bb642ae4c371.png)
It places block without form.

**Comment by beastyn** [comment]
placed without form still

![bandicam 2020-06-22 15-37-46-349](https://user-images.githubusercontent.com/27898520/85278389-55784800-b49e-11ea-8bee-f8a6098d00b5.jpg)

**Comment by Quadbro** [comment]
yes, my bad, forgot to update server files
