### ISSUE TITLE
0.9 labor message can stuck on screen

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16747]
Including another servers.
No way to closing.
Only one way to fix - restart client.

Open any bench, add labor, while message on screen hide interface by pressing alt+z
profit, after displaying interface you have permanent message on screen.
![20200618111843_1](https://user-images.githubusercontent.com/4980243/84997148-d8c03380-b156-11ea-8040-ae9ee5db92de.jpg)

**Comment by gzatravkin** [comment]
Could you attach loggs file when it happens?

**Comment by elfl0rd** [comment]
It has 100% repro, but why not?

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4799389/Player.log)
