### ISSUE TITLE
[0.9.0 staging-1605] Ashlar projects constantly spamming notification bar when out of resources

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#16748]
The ashlar stone projects are constantly spamming the notification bar that they are out of resources. See screenshot

**Version:** 0.9.0 staging-1605
Steps to reproduce:
1. Start an ashlar stone project in an advanced masonry table
2. Let it run out of resources
3. Check notification bar

**Expected behavior:** Notice once then stop and then notify again if a resource is added and it then runs out like all other crafts
**Actual behavior:** Constant notification that it is out of resources even though no resources are added or withdrawn

[playerlog.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4798276/playerlog.zip)
![ashlar_spam](https://user-images.githubusercontent.com/39825431/85016437-0367b780-b16a-11ea-9630-a77e8c672591.png)

**Comment by SlayksWood** [comment]
merged to #20368
