### ISSUE TITLE
Anti aliasing not working in avatar edit mode

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16752]
![animx22](https://user-images.githubusercontent.com/3536496/85060110-87fe0a00-b159-11ea-9cd3-9024562d441f.gif)
Look at them sparklies.
Probably uses a differnet camera. Make the cameras inherited prefabs so changes to one propagate to all.

**Comment by johnkslg** [comment]
Actually it appears in game too
![animx22](https://user-images.githubusercontent.com/3536496/85062766-e75e1900-b15d-11ea-8863-2a1ed848f909.gif)
This is with AA set to highest

**Comment by redwyre** [comment]
@johnkslg the the green flickering part of it or just a gif issue?

**Comment by redwyre** [comment]
Also what is your Global illumination set to? If you set it higher does it go away?

**Comment by johnkslg** [comment]
Green flickering is gif issue
Not sure on global illumination, are you seeing the issue on yours?

**Comment by redwyre** [comment]
John stated he isn't seeing it anymore
