### ISSUE TITLE
Get Edit and Continue working in the client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16761]
Unity supports edit and continue for its codebase, but it doesn't work for us due to some issues with how we treat singletons, etc.  
Step 1 - Investigate why edit and continue fails in the client and create a plan for what needs to change to make it work.
Step 2 - Implement said plan.

**Comment by redwyre** [comment]
Last time I checked on this, it would require making everything serialisable, which would be a massive undertaking for no other benefit...

I think it might be better to review the architecture of the game itself to speed up loading, as some stuff hasn't been looked at for years and there are newer ways of doing things (eg addressables).
