### ISSUE TITLE
9.0 1605 - Change property law still only applies to claims

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16775]
"Change property" law only applies to claims not vehicles/carts, it should also apply to them.

![image](https://user-images.githubusercontent.com/61889138/85079330-7b5fcd00-b1be-11ea-987e-2a02c30f4606.png)

When trying to interact with a wood cart
![image](https://user-images.githubusercontent.com/61889138/85079446-c8dc3a00-b1be-11ea-9d01-b62cc5409f0d.png)

Land and all its contents transferred as expected
![image](https://user-images.githubusercontent.com/61889138/85079502-e6110880-b1be-11ea-8440-39ff23c05e35.png)

**Comment by trickenso** [comment]
#16384 is the same problem.

**Comment by SlayksWood** [comment]
yea, merged to #16384
