### ISSUE TITLE
[0.9.0.0 Staging 1605] The law kicks the player out of the game if he violated it.

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#16770]
[0.9.0.0 Staging 1605] The law kicks the player out of the game if he violated it.
![2020-06-19_02-41-42](https://user-images.githubusercontent.com/36518011/85075293-5deb2d00-b1d7-11ea-8026-d05cc952cefb.png)

**Comment by SlayksWood** [comment]
Can't reproduce it in staging-1611. I create law like:
![image](https://user-images.githubusercontent.com/45708377/85104985-4ed5a080-b212-11ea-8679-f52ea510e032.png)
And I was not kicked from server:
![image](https://user-images.githubusercontent.com/45708377/85105061-73ca1380-b212-11ea-80b4-176d73c5d482.png)
![image](https://user-images.githubusercontent.com/45708377/85105073-7b89b800-b212-11ea-92dd-37ea6547799c.png)
![image](https://user-images.githubusercontent.com/45708377/85105201-bb509f80-b212-11ea-9606-742b6ee47f7a.png)

@Malenkei 
Can you provide save files? And ask the people who was kicked to provide a log file.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Still can't reproduce in staging-1736. Seems fixed, closed for now.
