### ISSUE TITLE
Hosted Worlds: sales page and account page update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16777]
User Story is:

1) My name is Vlad, I want to by a world as I'm a proper teacher and want to show Eco to my children (and school principal gave me money for it, imagine it!).
2) I go on the sales (educational) page, read all the stuff there and press the last button
3) I register my account
4) And I'm on the subscription page now (after a fix SLG team will make )
5) I didn't buy anything. I have to go out, as my dog was barking out a bear. 
6) When I'm back (and it was 3 days later, its not easy to make a friend with a bear) my browser logged me out.
7) I press Login button and go to the account page. I still want to buy a world.

- There is no button for it, only Learn more
![bandicam 2020-06-19 12-50-34-060](https://user-images.githubusercontent.com/27898520/85109932-961c5b00-b22b-11ea-95d7-63583425801c.jpg)
- Ok, let press it and go on the sales page and scroll all this stuff again.

Hey, wait, is my dog barking again?

Solution: 
1) Add Buy(Start-whatever) World button on the account page near the Learn More button. For those who don't need to learn anything anymore but didn't by a world.
2) Add Start World button somewhere on the first screen of the sales (educational) page. For those, who know information but somehow ended up there and just want to start their world.

**Comment by rainfarmer** [comment]
@johnkslg can you advice how you want menu

**Comment by johnkslg** [comment]
Makes sense, can have a direct link to buy hosted worlds on the account page
