### ISSUE TITLE
Remove walking from elk eating animation

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16784]
Ai does not support this
breaks title screen

**Comment by MilenkoTunjic** [comment]
I checked elk eating animations, they do not have any leg movement in them.

**Comment by MilenkoTunjic** [comment]
There is an old elk animation from 2014 where elk makes a step forward, but that has nothing to do with the current state of the elk rig or current animations, not sure if that is it. perhaps caption would explain it better?
or is this redundant bug?

**Comment by keegan-o** [comment]
Yep this was just the old animation
