### ISSUE TITLE
[0.9.0 staging-1611] Web elections: districts election design improvement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16783]
Need to redesign districts elections so they look great. For now there is too much empty space with too maps especially.

![bandicam 2020-06-19 16-53-42-493](https://user-images.githubusercontent.com/27898520/85129942-71d17600-b24d-11ea-9318-d35d6a908870.jpg)

**Comment by rainfarmer** [comment]
partially fixed, waiting for another fix to complete styling

**Comment by j3fffff** [comment]
moved to https://github.com/StrangeLoopGames/EcoIssues/issues/17028
