### ISSUE TITLE
Change loading screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16785]
![image](https://user-images.githubusercontent.com/3536496/85166781-a1b45580-b21c-11ea-9acd-3b6997dbdb9d.png)
Remove everything from the screen so the title screen is visible, put the loading tree in the bottom left with a faded background behind it, and put the text to the right of that, also in a faded background.

**Comment by johnkslg** [comment]
Some more details:

I would like to make the experience of entering the world a tranquil experience.
In the Minimal Loader scene, you can see a tree that grows and has leaves pop out while the game loads:
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/6557f6b3-7bd2-4860-b004-036a8b755b6c)

When a server starts connecting to a world (either an existing one or starting up one locally), it should switch open a new UI that does the following:
- The background title scene should lerp to blurred (using the same code as the escape scene now uses)
- That tree should fade-in, ungrown, in the bottom left corner
- There should be two rows of text: top row says the main thing it is doing, either connecting to a server or starting a local server. The second row should say whatever its currently doing (like the text in the progress dialog)
- The tree animation should change so that its growth represents the progress of the connection.  So by the time it fully connects, it will reach full growth with all the leaves.  This progress percent doesnt yet exist, so youll have to make one. IE, the 'connecting' part can be treated as the first '20%' (or whatever'), and the rest of the loading can be the 80%.  See what feels and looks good. Make sure the tree never 'pops', if the percent progress jumps forward for some reason, it should continue at the same pace. 
- The tree should always fully load, then fade out along with the background and text, before fading in the loaded level, even if this means delaying the load time. This is to give a nice smooth transition into the world

Like this:
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/a01365a1-fe34-41f0-b7f6-85475528155b)

When making the code:
- Dont add new blocks to ConnectionUI, this class is becoming a bloated mess. Add new UIs that are called by it.  
- Make sure if the process gets interrupted, it restores the screen appropriately.

**Comment by tuha263** [comment]
@johnkslg @MilenkoTunjic  I need a new texture for the stencil, "reverse" of the current one to do this task 
![stencil.png](https://images.zenhubusercontent.com/5f38a110742cd7b96b103fdc/b04a9a84-8d86-47ec-9a2e-e50f5d6ddb72)
Make the transparent part to be black, and make the black part to be transparent
