### ISSUE TITLE
Web elections: make marks for vote absent

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16782]
In the list of the active elections we need to show a mark if one didn't vote there

Something like
![no-vote](https://user-images.githubusercontent.com/27898520/85128430-b14a9300-b24a-11ea-90fd-49caa448c487.jpg)

**Comment by trickenso** [comment]
Alternative suggestion: split 'Running Elections' into 'Awaiting vote' and 'Voted'.
