### ISSUE TITLE
Feedback on election PR

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16795]
Need to add more details because users wont know how to use it:

- [x] Jeff: Please, make start and end- box where to drag candidates from/to and Big hardcoded numbers near every candidate which Denys will make alive in future :)
- [x] Jeff: Add header text 'Candidates in Order of Preference'
- [x] Jeff: Add text describing how to use it. 'Click and drag the candidates to put them in your order of preference.  If your first choice doesn't have enough votes to win, your second choice will be used, etc.'
- [x] Denys: Add big numbers and labels showing the ordering: '1st Choice:' '2nd Choice' etc
- [x] Denys: Start the candidates in a box that you drag them into the field. Having a default ordering isnt fair, because people will leave it that way.  Also, you need to be able to NOT rank a candidate at all. IE, I could rank just 3 and not care about the rest. There needs to be a way to clearly do this.
- [ ] Jeff: Put boxes around the candidates to make them look more like draggable cards. Can make them look like ballots

**Comment by denysaw** [comment]
Done my part in PR mentioned above. Here's quick demo: https://monosnap.com/file/4OsM720Cbmz407lMBe7Tq8Q0VVV9op
