### ISSUE TITLE
[0.9.0-1611] Economy Viewer Balance Does Not Match Account Balance

### ISSUE THREAD

**Issue by evanah64** [StrangeLoopGames/EcoIssues#16791]
![image](https://user-images.githubusercontent.com/66179199/85189235-1c13c280-b27b-11ea-8090-98971382e1f4.png)

Account balance in Economy Viewer does not match actual account balance. About 15 minutes elapsed between last transaction (manual transfer to another player) and this view. Only one account in use.

**Comment by beastyn** [comment]
Yeap, some update issues

1) Make a store and place something for sale (should be in the linked chest too)
2) Make some custom currency and change currency in the store for it
3) Make a transfer to somebody with this currency.

Economy viewer won't update information.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4836322/Player.log)
