### ISSUE TITLE
USER ISSUE: Actually no bug, but:

### ISSUE THREAD

**Issue by missdelinquent** [StrangeLoopGames/EcoIssues#16797]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Environment Data -> "Fir Yield Potential" text order should be moved up two positions to follow up "Fir Population"

At the moment its separated by Fireweed Pop/Yield.

Like:
Fir Population
Fireweed Population
Fireweed Yield
Fir Yield

Thank you for fixing in advance.

I like your game, even I dont understand 80% of farming because there isnt usefull information to so many questions on the eco wikipedia :), 

Your dear eco player

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by madpingui** [comment]
tested in develop branch unity editor its already separated in sub categories
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/a199162a-e579-4cb7-9432-a2a9325b70a3)

**Comment by Daniel-Magulado** [comment]
Confirmed on 0.9.4 Develop-263.

Closing.
