### ISSUE TITLE
More Balance for Furniture is Needed

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16799]
@WeaselDog commented on [Sun Apr 12 2020](https://github.com/StrangeLoopGames/Eco/issues/5920)

We have a ton of new housing objects we are highly promoting as a feature of 9.0. With current costs we can soft cap all our rooms very quickly with 3 pieces of cheap furniture (Stuffed Animal, Large Rug and Bench.). We have done some adjustments already but more early furniture costs needs to be lowered to accommodate the new furniture.

We need to give extra focus to statues, stuffed animals, animal mounts, tables, benches, and chairs,

**Comment by Engimage** [comment]
- Stuffed animals are too big to be used in houses.
- Statues are WAY too big to be used in houses. Maybe outdoors they make sense, but given their pretty low point value they are rarely used.
- Way too many items share "Decoration" category. Even flower pots... 
- Stuffed animals are not cheap by any means. Large Rugs require Tailor lvl 6 which is not easily achievable. (This is a reply to initial topic)
- Soft cap should probably be more soft.
- There is no reason to build T4 houses. This one should be addressed much more than actual furniture.

**Comment by WeaselDog** [comment]
Thanks for the great feedback. Some of the original post is also out of date, it is from a few months ago and we have made adjustments to some of these objects since then.

**Comment by WeaselDog** [comment]
@Xao22:
> stuffed animals could use a nerf but more important rooms,second room should give 25% 3rd room should give 0 at the same type in my opinion
