### ISSUE TITLE
[9.0-1611] Bring back negative shop prices

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16798]
Mishka:
> Cannot do negative values in 9.0 1611, someone tried (i think Xao?) to do a order to "buy" tailings off people and store them safely.

> Just does not accept the - input from keyboard and cannot use the + and - buttons to end up minus either.

We included that on purpose in one of the last patches due to common requests.

While at that, fix this: https://github.com/StrangeLoopGames/EcoIssues/issues/16796

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/16603
