### ISSUE TITLE
[0.8.3.3 B] USER ISSUE: Fish does not stack while fishing and keeps freezed in the air

### ISSUE THREAD

**Issue by Kamaling** [StrangeLoopGames/EcoIssues#16793]
![20200620131759_1](https://user-images.githubusercontent.com/22184124/85200950-c8958900-b2fb-11ea-84f3-0a29e583e8f4.jpg)
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Meinen Spielstand laden. Angeln. Fisch an der Angel einholen.
Load my savegame

**Expected behavior:**
Fisch an der Angel einziehen. Fisch stackt im Inventar.
Catch up fish on rod. Fish does stack in inventory.

**Actual behavior:**
Fisch bleibt in der Luft schwebend zurück und stackt nicht ins Inventar.
Fish keeps in air stuck and does not stack in inventory.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed

**Comment by Kamaling** [comment]
No mods in use

**Comment by beastyn** [comment]
@Kamaling thank you for the report.
We have plans for revisiting fishing in 9.1. Like this #7574
