### ISSUE TITLE
[0.9.0 staging-1611] Stacking furniture

### ISSUE THREAD

**Issue by Xao22** [StrangeLoopGames/EcoIssues#16792]
Version [0.9.0 staging-1611]

Stacking up furniture needs a nerf,ppl use like 3 or 4 of the same type to increase sp.Also they make 3 rooms at the same type like kitchens.More than 70% of players do not upgrade house to tier 2 or higher.In my opinion they should get nerfed to increase the demand on tier materials also economy.Many of them get bored after tier 1 and leave

**Comment by elfl0rd** [comment]
> Also they make 3 rooms at the same type like kitchens.
Intended.
Every additional room provide 50% less SP

**Comment by Xao22** [comment]
i know,but it needs more nerf if you ask me.make tier great again

**Comment by WeaselDog** [comment]
@Xao22 Can you specify which items people are stacking? We have reduced house points and diminishing returns of many pieces of furniture, so feedback on which are the problem would be helpful.

**Comment by Xao22** [comment]
stuffed animals could use a nerf but more important rooms,second room should give 25% 3rd room should give 0 at the same type in my opinion

**Comment by WeaselDog** [comment]
Thanks. I am merging this into the other Furniture Balance issue: https://github.com/StrangeLoopGames/EcoIssues/issues/16799
