### ISSUE TITLE
Password Reset not working for some people

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16790]
We still have the issue that some people when clicking on their password reset link are just redirected to a login page, not being able to set a new password.

**Comment by denysaw** [comment]
I need one of those wrong links for that. Cuzz I can't reproduce on production:
![image](https://user-images.githubusercontent.com/5720101/85631610-24eb0680-b676-11ea-8d69-a1adc61df30c.png)

And Jeff says we'll push re-designed version to Production soon and there's no point to fix something not super critical there :)
So test please on Developland is it working for you or not. Thanx ;)

**Comment by D3nnis3n** [comment]
It's ever been working for me, but several times a week its not working for
people writing me a ticket.

Denysaw <notifications@github.com> schrieb am Mi., 24. Juni 2020, 23:56:

**Comment by denysaw** [comment]
Yeah. So ask those people their link, which is redirecting to login for them. Maybe link is expired or wrong username, dunno, We'll see when we'll have a link.

P.S. they could also be scammers, which target is get resetlink of someone's account :/

**Comment by D3nnis3n** [comment]
Noone failed the verification, they’re legit. I’ve been sending the links when i got them to Jeff, but that mostly will not have any effect as they do expire after 24 hours and that time is usually over when they open the ticket and i ask them for the link and they report back. -- Mit freundlichen Grüßen,Dennis Scholz Von: DenysawGesendet: Donnerstag, 25. Juni 2020 01:15An: StrangeLoopGames/EcoIssuesCc: Dennis Scholz; AuthorBetreff: Re: [StrangeLoopGames/EcoIssues] Password Reset not working for some people (#16790) Yeah. So ask those people their link, which is redirecting to login for them. Maybe link is expired or wrong username, dunno, We'll see when we'll have a link.P.S. they could also be scammers, which target is get resetlink of someone's account :/—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rainfarmer** [comment]
@denysaw 
here are some examples from before. I didn't notice anything special about them in db. and they seem like they should have worked.

https://accounts.play.eco/user/login/reset/1a0777d33e803a7c91ea00a1a1be31b9/54832
https://accounts.play.eco/user/login/reset/30e69bac6baccc04f702ee37c895dd9d/50360
 https://accounts.play.eco/user/login/reset/1a0777d33e803a7c91ea00a1a1be31b9/54832

**Comment by denysaw** [comment]
@rainfarmer Yeah, they are already expired, gives us nothing for the test. Can we postpone this issue after re-designed version being released?

**Comment by rainfarmer** [comment]
yes

**Comment by denysaw** [comment]
@D3nnis3n got new fresh not working link, so I was able to determine the problem. It really was. Hotfixed on Prod now ;)
