### ISSUE TITLE
crafting tables not progressing 

### ISSUE THREAD

**Issue by true2form** [StrangeLoopGames/EcoIssues#1679]
if a crafting table is activated without all the ingredients it causes all tables within the localized area to stop progressing in alpha a88e14f2 even outside in a different room

**Comment by true2form** [comment]
followed by this crash dump


[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1085480/output_log.txt)

**Comment by MarjieAVolk** [comment]
We recently fixed a problem with crafting tables and carts getting frozen.  But this problem shouldn't have caused a crash.  Not sure what to make of the crash output there (but I see several other bugs in the log that I can fix... ;) )

**Comment by metachronism** [comment]
closing as dupe of inventory perf problems fixed in alpha 6
