### ISSUE TITLE
Title screen UI should only ever delay the first time 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16806]
![image](https://user-images.githubusercontent.com/3536496/85241225-f2c87300-b3ef-11ea-803e-e5b5364c94aa.png)
When returning to this screen after disconnecting, or from another page in the main menu, they should fade in fast, and with no delay.

**Comment by mirasrael** [comment]
It probably will require to keep it in memory which results in lot of unused resources eating user system RAM and GPU RAM. It is why we moved title screen to separate scene (and we're speaking about few gigabytes of memory). So unless we can find a way to keep it out of memory and load fast we should prefer to load it slow (at least after logging into a game). But there is no reason to have it slow when navigating in menu.

**Comment by gzatravkin** [comment]
@mirasrael is batching the scene to video was considered?

**Comment by keegan-o** [comment]
Video does seem like a good option if this is needed-- it's gonna be hard to do with this scene what other games tend to do and have just minimal custom geometry for any loading screens.

**Comment by mirasrael** [comment]
Yeah, it seems like a good solution and should improve loading speed a lot

**Comment by johnkslg** [comment]
I was just referring to the delay before the fade in of the UI elements. Dont need to do a video for the whole screen, thats a big job.

**Comment by beastyn** [comment]
I would say its still quite long
https://drive.google.com/file/d/16zu-MiIq0DOBUO99oKE8Zkl_E9-wuE2v/view?usp=sharing

**Comment by gzatravkin** [comment]
Speeded up buttons fade animation. 
But biggest delay of the video is because of scene loading. Animation starts after full load of scene.

**Comment by beastyn** [comment]
@gzatravkin I'm sorry, I should have to make attention, that this removing delay thing we are making for all main menu launching EXCEPT the first time. 

And now we have lost this little delay when you are opening the game for the first time (launch the client)
So. 
1. When we are launching the client for the first time, we have a bit of delay (how it was previously)
2. When we are opening the menu after the launching (ie. after disconnect) we don't need this delay at all (just soft appearance and what we can get with this scene loading stuff)

**Comment by SlayksWood** [comment]
- [ ] 1 .Still an issue. It works fine everywhere except starting game. 
Currently I start game and all UI appears immediately and after some time appears "ECO":
![image](https://user-images.githubusercontent.com/45708377/88028940-fc094480-cb41-11ea-895b-ecd22e00c627.png)

logo ECO appears correct and after appearing ECO (maybe another 5 seconds) all other UI should appear.

- [ ] 2. I found another wrong delay. Step to reproduce:
- open main menu:
![image](https://user-images.githubusercontent.com/45708377/88029231-628e6280-cb42-11ea-9124-9b1c4a06376c.png)
- press Your worlds. ECO will disapear after some delay and overlapped:
![image](https://user-images.githubusercontent.com/45708377/88029281-7c2faa00-cb42-11ea-83fc-7299627ea21a.png)
![image](https://user-images.githubusercontent.com/45708377/88029305-8487e500-cb42-11ea-9677-cf975c28b7b3.png)

**Comment by beastyn** [comment]
@johnkslg there is no more delay with start main menu for the first time.
It's for you to decide how important it is.

**Comment by beastyn** [comment]
So, I will assume that it's ok.
