### ISSUE TITLE
[0.9.0 staging-1614] UI: Transfer does not work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16809]
1. Tax and Result fields are wrong
![bandicam 2020-06-22 11-30-29-748](https://user-images.githubusercontent.com/27898520/85255507-d96d0880-b47b-11ea-98d2-b3cb04e1b568.jpg)

2. Send button does nothing

**Comment by SlayksWood** [comment]
Still an issue, I can't use "Send" button
