### ISSUE TITLE
Title screen UI adjustments

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16805]
![image](https://user-images.githubusercontent.com/3536496/85241166-c4e32e80-b3ef-11ea-802f-f5425a704d35.png)
- The menu items along the right side now overlap badly with the background behind it. make the faded, tapered panel more opaque, extend the tapering to the left more, and fill in the gaps between. 

Vivox logo also:
![image](https://user-images.githubusercontent.com/3536496/85241280-2905f280-b3f0-11ea-9dfd-561f67038ef9.png)

![image](https://user-images.githubusercontent.com/3536496/85241296-31f6c400-b3f0-11ea-958c-f7ea7274076a.png)
And news could use a corner-fade area so it looks like part of the UI, and not like someone got a newspaper stuck in a tree.  It may need to look more button-like,

**Comment by keegan-o** [comment]
We also need a black cover for skinny non 16:9 aspect ratios to mask out the edges of the pruned title screen world. 

16:9 works:
![image](https://user-images.githubusercontent.com/14983165/85332675-3d4bfd00-b48d-11ea-9770-22a9c6686573.png)

more squashed as it will appear in windowed mode does not:
![image](https://user-images.githubusercontent.com/14983165/85332721-4ccb4600-b48d-11ea-90a7-777159d8edac.png)

Just need to have a couple black boxes I think that cover up the sides.

**Comment by keegan-o** [comment]
Looks like that gradient is a tiny sprite stretched out, so I recommend against altering it (may be used in other places and is a straightforward 0-1 gradient), and I think either it needs to be replaced to be darker and also 'fill in the gaps' as john would like, or you could shift the options further to the right.

**Comment by MilenkoTunjic** [comment]
Is it possible to further tweak the screen?
IE- zoom out a bit more, and add more nature to the left-hand side of the image?

**Comment by MilenkoTunjic** [comment]
OK, I did changes and created some new sprites. Some of the changes should be fixed simply by updating the textures, however, right hand side meny will need a UI rebuild as well as adding sprites behind the news icon.
Whoever wants to do it, hit me up and I can guide you on how to put it together.
New sprites are added to UI_Elements_02, to the right of the news icon (in bottom left corner of the sheet) They are black background fade that gets stretched (no slicing) as a background, and one below is consistent black box that gets nine sliced, put on top of the background fade and frames the many text/newspaper. Also, even though it is a main menu, fonts should still be smaller than what they are now, and made sure that they fit nicely within the box frame, with 4 pixel breathing space between the text box and the UI frame itself.
let me know who will be doing this, as I want to be involved as well.

**Comment by SlayksWood** [comment]
Strange frame here:
![image](https://user-images.githubusercontent.com/45708377/85998857-05f0c980-ba14-11ea-854e-630e3831f7a7.png)

**Comment by SlayksWood** [comment]
create a separate issue for last comment

**Comment by SlayksWood** [comment]
I closed this one and will open separate issues.
