### ISSUE TITLE
[0.9.0 staging-1614] New runaway "Ratify"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16811]
![image](https://user-images.githubusercontent.com/45708377/85260621-a58de500-b473-11ea-92df-b3a25b3b1067.png)

**Comment by johnkslg** [comment]
Why are these happening?

**Comment by gzatravkin** [comment]
it happened because it was changed from unity layout to fast layout without setting align middle. Fixed. Searched for other simmiliar cases with this buttones, looks like this is the only one.
