### ISSUE TITLE
[0.9.0 staging-1614] Selecting Credit or bank account glitches

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16810]
in credit tab, contract board and the same objects.

- [ ] 1. Different tooltip position:
![image](https://user-images.githubusercontent.com/45708377/85259685-22b85a80-b472-11ea-8a33-6c696e84491f.png)
![image](https://user-images.githubusercontent.com/45708377/85259734-3794ee00-b472-11ea-82fa-31890cbb2323.png)
![2020 06 22 Different tooltip position](https://user-images.githubusercontent.com/45708377/85260155-e3d6d480-b472-11ea-9a22-f41ed28350ae.gif)
- [ ] 2. tooltip can overlap dropdown list:
![image](https://user-images.githubusercontent.com/45708377/85260222-00730c80-b473-11ea-813f-ce9b7cee9ea9.png)

**Comment by gzatravkin** [comment]
Fixes 1. 
For 2 I have this behavior: the last element is upper. I believe it's correct (otherway tooltip from dropdown would be overlaped by dropdown)
