### ISSUE TITLE
[0.9.0 staging-1614] Can't open chest without selected hammer on toolbar.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16819]
or dev tool. Seed, axe, empty:
![image](https://user-images.githubusercontent.com/45708377/85286072-a6863d00-b49a-11ea-8f16-1cc1eae6947a.png)
![image](https://user-images.githubusercontent.com/45708377/85286084-aa19c400-b49a-11ea-8b25-97b206fe4f3e.png)
![image](https://user-images.githubusercontent.com/45708377/85286092-ac7c1e00-b49a-11ea-9afa-4a15f86de7dc.png)
Hammer:
![image](https://user-images.githubusercontent.com/45708377/85286101-b00fa500-b49a-11ea-9aae-5ac963e944e5.png)

**Comment by olegshegai** [comment]
Prefab fixed and committed to the SVN
