### ISSUE TITLE
[0.9.0 staging-1614] UI: Storage linked inventories vertical positioning

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16820]
Sometimes is vertical now
![bandicam 2020-06-22 17-24-59-288](https://user-images.githubusercontent.com/27898520/85287170-4fd62e80-b4ad-11ea-9e3b-7da674dbf36d.jpg)

![bandicam 2020-06-22 17-34-55-457](https://user-images.githubusercontent.com/27898520/85288407-1bfc0880-b4af-11ea-9f22-8dae226b83b7.jpg)

It can be fixed after reopening

**Comment by SlayksWood** [comment]
Still have some glitch:
- place several storages:
![image](https://user-images.githubusercontent.com/45708377/85710554-0b39d580-b6ef-11ea-9df4-522b6df0ae8d.png)
- place another one:
![image](https://user-images.githubusercontent.com/45708377/85710584-12f97a00-b6ef-11ea-9a70-25982b6375e5.png)
- open it:
![2020 06 25 Storage linked inventories vertical positioning](https://user-images.githubusercontent.com/45708377/85711060-94e9a300-b6ef-11ea-9741-679b239bb2d4.gif)
- it always happens for first opening storages after placing.
