### ISSUE TITLE
[0.9.0 staging-1614] Civics: Law UI - triggers categories redesign

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16823]
From #13345

Need icons for all these types to display in the drop down. IE, they need to show their MarkedUpName in the dropdown, like when theyre displayed in a selector here:

https://user-images.githubusercontent.com/3536496/66857182-90070980-ef3b-11e9-96e2-d071408224a8.png
https://user-images.githubusercontent.com/3536496/66857249-b6c54000-ef3b-11e9-809c-8ec6037beb28.png

Some dont have icons, like SetTimer. Give Rob the list of icons needed and add them in once created. Some icons are probably already there but just need their file renamed to match the name of the class.

**Comment by RobertMangano** [comment]
![image](https://user-images.githubusercontent.com/26705633/87128288-b68f8080-c2d2-11ea-8c5c-17fcb80068dc.png)
added icon here
