### ISSUE TITLE
[0.9.0 staging-1614] Civics: Law UI: drop-down improvement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16824]
Fro, #13345

Make dropdown behave better. Make it position better in cases like this, and show more of the list (theres more veritcal space than is utilized). 'Better' is subjective so use your judgement to determine what would be the best option in cases like this. Perhaps we make it popup something in the middle of the screen instead, even. Discuss thoughts with johnk.
anim

**Comment by gzatravkin** [comment]
The main problem was that code that was checking for max size, which should be below 80% of screen, was not considering sacle of canvas. So by fixing it there are less free space:
![image](https://user-images.githubusercontent.com/53317567/87306303-35143a00-c4ee-11ea-988d-7d444243c7a4.png)

**Comment by johnkslg** [comment]
Perhaps if the list is long enough that it cant behave like a regular drop down (appearing below the arrow), then we center it in the screen, with a bit of margin on the top and bottom, and use a mouse blocker fadebox to hide the background.

@beastyn @SlayksWood @gzatravkin thoughts?

**Comment by SlayksWood** [comment]
We have good dropdown here:
![image](https://user-images.githubusercontent.com/45708377/87420869-b3e8a000-c5de-11ea-94e6-5b9902b8728b.png)
and here:
![image](https://user-images.githubusercontent.com/45708377/87420882-ba771780-c5de-11ea-9abc-6098637b02dd.png)
So for me it should look like:
![image](https://user-images.githubusercontent.com/45708377/87420982-e85c5c00-c5de-11ea-9fa2-ad819aea78f3.png)
![image](https://user-images.githubusercontent.com/45708377/87421124-1b065480-c5df-11ea-87c5-6d5c83103aa6.png)
Of course we can delete description and make this field width like trigger section width.
