### ISSUE TITLE
Dirt Roads obtainable

### ISSUE THREAD

**Issue by GruumshEco** [StrangeLoopGames/EcoIssues#16826]
When using the Skid Steer on dirt that has been stamped using a road tool, you can obtain "Dirt Roads"

They stack to 5 in a stockpile but you can carry 100 at a time in hand and place them on the walls of vertical surfaces and they do not retain the physics of dirt. 
![dirtroad1](https://user-images.githubusercontent.com/67291586/85331828-db978d00-b4a4-11ea-89d6-5c7cc35ff255.png)
![dirtroad2](https://user-images.githubusercontent.com/67291586/85331830-db978d00-b4a4-11ea-971b-5696c9f754bd.png)

**Comment by Krizzoula** [comment]
Lol, wow Grum... Awesome for finding this ..

**Comment by MishkaFur** [comment]
But it was so fun :D

![image](https://user-images.githubusercontent.com/61889138/85618889-5d301c00-b659-11ea-82f4-2486e3ac176c.png)
