### ISSUE TITLE
[0.9.0 staging-1616] Something wrong with font in game.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16833]
Seems it was changed to another and we have a lot of overlaps and looks pretty bad now in some places:
![image](https://user-images.githubusercontent.com/45708377/85367401-d3d1fa00-b531-11ea-85ee-12b962c0bb3c.png)
![image](https://user-images.githubusercontent.com/45708377/85367422-e0565280-b531-11ea-9035-cbca21e47c5a.png)
![image](https://user-images.githubusercontent.com/45708377/85366528-31fddd80-b530-11ea-9217-2177aa1fc2fb.png)
![image](https://user-images.githubusercontent.com/45708377/85366709-94ef7480-b530-11ea-8fb3-ee2551071e10.png)
![image](https://user-images.githubusercontent.com/45708377/85371242-9ae95380-b538-11ea-9302-1888ed79b099.png)

**Comment by beastyn** [comment]
From my perspective, as a person with reaaaaly bad sight, I don't like this font for its bold view.
Its pretty tight and hard to read
![bandicam 2020-06-23 15-32-23-882](https://user-images.githubusercontent.com/27898520/85394544-28906780-b568-11ea-9830-fe0bd59469d0.jpg)

**Comment by gzatravkin** [comment]
@MilenkoTunjic english font was changed from PerspectiveSans to Roboto (which was already in russian).

It was done because it looked bad when english and russian text was used together. 

Other option would be to use PerspectiveSans in both. Should I do so?

**Comment by MilenkoTunjic** [comment]
Bold version of the font (and/or) outline effect should not be used anywhere in the game. Also, roandom font sizes should not be random.

**Comment by SlayksWood** [comment]
> ![image](https://user-images.githubusercontent.com/45708377/85684283-a4102700-b6d6-11ea-97be-43652edc5c4b.png)

**Comment by SlayksWood** [comment]
> ![изображение](https://user-images.githubusercontent.com/4980243/85682534-1122bd00-b6d5-11ea-8f0c-f0f3d90e3341.png)

**Comment by gzatravkin** [comment]
Looks be already fixed

![image](https://user-images.githubusercontent.com/53317567/87116616-9b7a2d80-c24c-11ea-8069-c82f45bf9def.png)
![image](https://user-images.githubusercontent.com/53317567/87116649-ba78bf80-c24c-11ea-9ce4-0f8c9c3bf55d.png)
![image](https://user-images.githubusercontent.com/53317567/87116669-c6fd1800-c24c-11ea-80d4-ef8b75a9ba03.png)
![image](https://user-images.githubusercontent.com/53317567/87116713-e4ca7d00-c24c-11ea-82de-8f606e9ece25.png)

**Comment by SlayksWood** [comment]
Closed for now, but in some places we still have ovberlapping and another problem. I'll create separate issues
