### ISSUE TITLE
[0.9.0 staging-1616] UI:story about the little triggers 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16838]
1) Store: "+" and "-" don't work in selling list (you are trying to sell something to someone in someone's store)
In Buying section they are fine.
![bandicam 2020-06-23 13-20-50-376](https://user-images.githubusercontent.com/27898520/85379679-78b1fe80-b555-11ea-964f-c2b1e7d11677.jpg)

2) Removing is cut
![unknown (21)](https://user-images.githubusercontent.com/27898520/85380019-da726880-b555-11ea-96c3-0674e728c7f5.png)

**Comment by Dmittry62** [comment]
Could not reproduce.
1. "+" and "-" buttons work fine.
2. "Remove" button is not cut.
![sfsTR1t9Wp](https://user-images.githubusercontent.com/8580108/87035198-a784d180-c1f1-11ea-8585-eec0f800d796.gif)
![Unity_CxfN6xTs6K](https://user-images.githubusercontent.com/8580108/87035225-b23f6680-c1f1-11ea-889c-d4f696ae2768.png)
