### ISSUE TITLE
[0.9.0 staging-1616] Ecopedia: Selector displacement

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16836]
1. Open Ecopedia
2) Choose some category
3) Page selector is in the corner

![bandicam 2020-06-23 13-07-53-171](https://user-images.githubusercontent.com/27898520/85377581-bbbea280-b552-11ea-9096-0fd70520af2f.jpg)

**Comment by SlayksWood** [comment]
category too if you will use seaching:
![image](https://user-images.githubusercontent.com/45708377/85691850-8a261280-b6dd-11ea-98cd-3d277745209f.png)
