### ISSUE TITLE
0.9-1616 cannot interact with chest (w\o hammer)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16835]
w\o hammer - cannot interact
![20200623105021_1](https://user-images.githubusercontent.com/4980243/85376050-e2271280-b53f-11ea-8fdf-c3b33467a357.jpg)

with hammer - all ok.
![20200623105017_1](https://user-images.githubusercontent.com/4980243/85376030-db000480-b53f-11ea-9c12-0f4aaa4e5ab5.jpg)

**Comment by SlayksWood** [comment]
dup #16819
