### ISSUE TITLE
[0.9.0 staging-1617] Strange pollution effect

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16858]
Place 3 Blast Furnace, 2 Oil refinery and 1 combustion generator. it'll drop my FPS to 20.
![image](https://user-images.githubusercontent.com/45708377/85516531-f7b33f80-b606-11ea-8d23-52aaefeee5b2.png)
10 FPS:
![image](https://user-images.githubusercontent.com/45708377/85516595-0b5ea600-b607-11ea-90d4-b7a5df470019.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/bbfc5c16-f817-492e-a863-c13ae2101fd2)

Smog is still setting a particle emitter to emit with an emit rate of 25,000 plus-- this is all controlled via code and in-accessible to me.

**Comment by keegan-o** [comment]
Looks like the emit rate was fixed, Stanislav is now helping me to make this something I can access and fix.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0b8bca00-499c-4e75-90e9-7b43b88cce29)

Similar setup but with a few more blast furnaces ^

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/65edb41d-09b6-4721-8d9a-5c99d9845360)

With all pipe-emitter objects turned off from scene view^

I can't repro the massive drop in FPS but this shows there does seem to be an impact, for sure.

**Comment by keegan-o** [comment]
It seems like those 500k tris are coming from the smoke cubes, though in shifting around some chunks may have also stopped rendering. Will try altering the effect to use a lower tri mesh or a billboard to see if I can get acceptable results that are more performant.

**Comment by keegan-o** [comment]
Looks like it is because these all have collision enabled so they don't go through roofs. Disable collision and FPS goes up, even in this version where I'm also rendering 3M more tris:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/c1f60d3e-fb79-472b-8a1f-97330a512902)

**Comment by keegan-o** [comment]
Fixed performance on this for now by removing collision.
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/fa8aff3b-f5af-4c3c-ac25-5d4854aea3de)

I was never able to repro anything like the way that screenshot looked though.
