### ISSUE TITLE
Update game server auth handling for cloud world owners

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16856]
Users can buy cloud worlds (aka hosted worlds) and not own eco the game.
This creates an issue where users cannot edit their worlds, 
because they are rejected when the game server calls auth (because they dont own the game)

Update game server, 
when it sends user data to auth, it includes the game server's server id

Update auth, 
if user does not own eco, 
then check if they own that specific server id (check in worlds table > server_id + user_id)
If they do own that server
then let them login and return successful login response

**Comment by redwyre** [comment]
@j3fffff this is checked into staging

**Comment by WeaselDog** [comment]
@j3fffff Closing this as fixed. Please reopen as needed.
