### ISSUE TITLE
Icon doesnt match

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16850]
![image](https://user-images.githubusercontent.com/3536496/85467639-51146380-b560-11ea-9b51-b92d3389211e.png)
The 'Rooms' icon is not isometric like the rest, and the property icon is isometic at a different angle.
Note that both those icons are used in the tutorial, so check with Milenko first if they should be changed or different ones used here.

**Comment by RobertMangano** [comment]
these icons already exist on the misc icon sheet, I had held of swapping them for the exact reasons you mentioned. However milenko now says to just replace them so I will swap them out.
