### ISSUE TITLE
Dialog fade in/out

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16875]
- Make all dialogs fade in and out when they are opened and closed, over .2 seconds or so.  They can also move up and down as they do so (like popup dialog does). Make this all use shared universally applied code that happens automatically (so dialog creators dont need to remember to do it).
- Turn up depth of field on the game on any UI that fills the screen.

**Comment by beastyn** [comment]
It;s a bit strange, when everything is blurred except highlight.
Can we do something here?

**Comment by beastyn** [comment]
from John
They used to drift up and down, and fade in/out rapidly, they just turned slow and dont move.
