### ISSUE TITLE
Change default inventory scale

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16873]
This is what 100% scale looks like:
![image](https://user-images.githubusercontent.com/3536496/85632748-bd5c9900-b62c-11ea-8c1d-c25de75ad073.png)

Rebalance it so new 100% = current 75%:
![image](https://user-images.githubusercontent.com/3536496/85632982-352ac380-b62d-11ea-8600-27b612d9aeb6.png)

Change max and min of scale range as well

Also: reduce size of worldmarker text by 25%

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/86900831-85695180-c114-11ea-84c2-e9c797413915.png)
![image](https://user-images.githubusercontent.com/45708377/86900892-96b25e00-c114-11ea-90dc-ce95c85c2dac.png)
