### ISSUE TITLE
0.9 rotating part of the rolling mill is not interactable

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16880]
![20200625110837_1](https://user-images.githubusercontent.com/4980243/85681985-85a92c00-b6d4-11ea-97cb-f89325f3c4cf.jpg)
![20200625110843_1](https://user-images.githubusercontent.com/4980243/85681992-8772ef80-b6d4-11ea-982d-ceb972a70cc0.jpg)

**Comment by Sekor2600** [comment]
fixed in svn
