### ISSUE TITLE
What is maximum character limit on law titles?

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1688]
When proposing a law with a long title, I get this error in the server.
https://gyazo.com/3b02a1990bf72bf2af9635c664f350ea

Looks like the its hitting a character limit, can you let me know what that limit is and I'll enforce it on my end.
I'm currently enforcing titles at < 250 chars

**Comment by MarjieAVolk** [comment]
That exception isn't from a character limit - it's from the string being empty.  Don't think there's a character limit server side.  So just disallow empty titles.
