### ISSUE TITLE
Post-purchase flow for hosted worlds

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16888]
- [x] denys After buying a hosted world, I was taken back to the 'about hosted worlds' page. I should go to the hosted worlds dashboard, where I can see my world, and instructions how to join it. 

![image](https://user-images.githubusercontent.com/3536496/85797558-b9924a80-b6f0-11ea-8a4b-17e6dbcd46d6.png)
- [x] denys Move 'how to start' to the top. Can remove this from the Citizen sub page and just have it in Worlds
- [x] denys Add prominent text above everything 'World is paused, click 'Unpause' to begin world.
- [x] denys The world was starting up, but there was no text to that effect. There was a '...' appearing on the world icon.  Add prominent text 'World is starting up, please wait'
- [x] denys The moving '...' stayed there infinitely until I refreshed, then it showed the world. Make this live update, as soon as its done it should refresh. 
- [x] jeff Change text:

> How to Join and Share your Hosted World
> - Start Eco and your hosted world will appear on the title screen, click to join.
> - To share **citizen accounts**, share the login info and use it after downloading Eco from one of the links below.  It will appear in their title menu as well.
> - Make sure players are using the correct version of Eco for the version you've selected here.  
> - Players that own Eco, but are not one of your citizens, can join by logging into Eco, clicking Your Worlds, click plus icon, enter your Server ID.

![image](https://user-images.githubusercontent.com/3536496/85797508-a1223000-b6f0-11ea-8434-1aa2105b4ee8.png)
- [x] jeff Font cutoff here

**Comment by denysaw** [comment]
@rainfarmer Re-assigned `There was a '...' appearing on the world icon. Add prominent text 'World is starting up, please wait'` to you. I removed `live update` as the next bullet is about the same thing

**Comment by denysaw** [comment]
Finished my part here.
