### ISSUE TITLE
0.9 installed module name in modules tab

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16881]
![изображение](https://user-images.githubusercontent.com/4980243/85682078-9c4f8300-b6d4-11ea-8306-a15e6cde4141.png)

for now - no name, maybe like this?
![изображение](https://user-images.githubusercontent.com/4980243/85682428-f81a0c00-b6d4-11ea-9f70-0e259b5eb687.png)

also background need expanded.
![изображение](https://user-images.githubusercontent.com/4980243/85682534-1122bd00-b6d5-11ea-8f0c-f0f3d90e3341.png)

**Comment by mirasrael** [comment]
Not sure if it is necessary. You can always hover an icon and it is self explanatory (at least after some time), but module name will occupy name all the time and will require to increase height of entry while in most case won't add much value.

**Comment by elfl0rd** [comment]
Displaying the name of the installed module is useful because it reduces the number of actions required to view it.

Ideally display the installed module not only on this tab but also somewhere else in the name of the table.

**Comment by SlayksWood** [comment]
problem with background here #16833 for now.

**Comment by SlayksWood** [comment]
Adding duplicate information everywhere makes the interface harder.

**Comment by elfl0rd** [comment]
> Adding duplicate information everywhere makes the interface harder.

The name of the installed module is not in the interface, so it is not a duplicate.

**Comment by mirasrael** [comment]
Though if we change title to "[module] provides following benefits" then it will not extend vertical space.

**Comment by elfl0rd** [comment]
> Though if we change title to "[module] provides following benefits" then it will not extend vertical space.

Love this.

**Comment by SlayksWood** [comment]
Currently:
![image](https://user-images.githubusercontent.com/45708377/107741952-383f0500-6d1f-11eb-9f4c-eed4ec006973.png)
Must be:
![image](https://user-images.githubusercontent.com/45708377/107742337-e6e34580-6d1f-11eb-99da-7ce8bc0d9d3a.png)

**Comment by Mattprass** [comment]
Not getting that on 9.3

https://gyazo.com/c6e8d79f82154c72f2987c1a936f150d

**Comment by SlayksWood** [comment]
@Mattprass There is one difference between mine and your picture. My language is not English. So it looks like this is a localization problem.
Gibberish:
![image](https://user-images.githubusercontent.com/45708377/107914502-9cf29d80-6f73-11eb-8b26-4e88d3aafc83.png)
Russian:
![image](https://user-images.githubusercontent.com/45708377/107914689-0a063300-6f74-11eb-8525-f6d95c5e77fb.png)

**Comment by Mattprass** [comment]
Good catch, working in the fix
