### ISSUE TITLE
Reinforced Concrete is too inexpensive

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16897]
After changes to the Reinforced Concrete recipe, it is far too inexpensive in terms of Steel Bars. In addition Flat Steel is too expensive as it costs twice as much as other Tier 4.

**Cost with no upgrades:**
Rebar: 2 Steel Bar
Reinforced Concrete: 1/4 Rebar = 0.5 Steel Bar

**Cost with level 3 upgrades:**
Rebar: 2 Steel bar * 60% = 1.4 Steel Bar
Reinforced Concrete: 1/4 Rebar * 60% = 0.21 Steel Bar

**Cost with max upgrades:**
Rebar: 2 Steel Bar * 50% = 1 Steel Bar
Reinforced Concrete: 1/4 Rebar * 50% = 0.125 Steel Bar

**Other Tier 3 & Tier 4 costs with max upgrades as reference:**
Ashlar Stone: 1 Steel Bar * 50% = 0.5 Steel Bar
Corrugated Steel: 2 Steel Bar & 50% = 1 Steel Bar
Framed Glass: 2 Steel Bar * 50% = 1 Steel Bar
Flat Steel: 4 Steel Bar & 50% = 2 Steel Bar

**Comment by mirasrael** [comment]
I have opposite opinion. T4 is too expensive. If we wanna to see buildings from T4 and T3 we shouldn't make them expensive. Also Reinforced Concrete isn't expensive in real life and I don't see any real reason to make it expensive in game. And Steel isn't only component for Reinforced Concrete.

**Comment by WeaselDog** [comment]
On the playtest it was reported that Reinforced Concrete was the only building material used for this reason. We have the option to reduce the costs of other materials instead.
