### ISSUE TITLE
[0.9.0 stging-1630] Mint UI has a small flaw

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16891]
this should be align left
![image](https://user-images.githubusercontent.com/45708377/85826941-d892ea00-b78d-11ea-9f4c-bac268441b35.png)

**Comment by gzatravkin** [comment]
Already fixed
![image](https://user-images.githubusercontent.com/53317567/88464723-64825980-ce93-11ea-9c42-c0af2e2002b3.png)
