### ISSUE TITLE
USER ISSUE: water image is ripped

### ISSUE THREAD

**Issue by Nuke21** [StrangeLoopGames/EcoIssues#16896]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
go to this location

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does issue happen when no mods are installed?:**

**Comment by MishkaFur** [comment]
Please can you provide more info including screenshots

**Comment by SlayksWood** [comment]
@Nuke21 
> Please can you provide more info including screenshots

**Comment by Nuke21** [comment]
I thought the screenshot included a XYZ cord. The water where i reported the big was broken, I could see under the ocean clear as day.

**Comment by MishkaFur** [comment]
You did not attach any screenshot,worlds are also different between servers so coords wont necessarily be the same

**Comment by SlayksWood** [comment]
@Nuke21 
I want to understand exactly what your problem is. According to the description, we have such issue, but I would like to see your screenshot before merged it.

**Comment by Nuke21** [comment]
Yes it is this same problem posted in that with the ripped ocean. 

[img]https://user-images.githubusercontent.com/27898520/83019139-e6930500-a03f-11ea-85f9-9f210e1d91c3.jpg[/img]

> 
> 
> @Nuke21
> I want to understand exactly what your problem is. According to the description, we have such issue, but I would like to see your screenshot before merged it. For example this #12080. Do you have same problem?

**Comment by SlayksWood** [comment]
merged to #12080.
