### ISSUE TITLE
[0.9.0 staging-1630] Filter scrolling issues

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16890]
1) Scroll is cutting the last row
![bandicam 2020-06-26 10-34-16-126](https://user-images.githubusercontent.com/27898520/85825616-1e56af00-b79c-11ea-8a67-b2822ce1c95e.jpg)
2) We don't need scroll if everyhing is on screen
![bandicam 2020-06-26 10-56-41-602](https://user-images.githubusercontent.com/27898520/85825660-362e3300-b79c-11ea-8c99-350816bbd383.jpg)

**Comment by gzatravkin** [comment]
seems be fixed already
