### ISSUE TITLE
Governmental Glitches

### ISSUE THREAD

**Issue by Farbal** [StrangeLoopGames/EcoIssues#1689]
The Government is bugged on our private server. The leader should be "Redwolv", but, on the government tab it says, "John". because of this issue, we cannot remove a law that we added to test the law feature. 

The server is running on 5.5.4.

![image](https://user-images.githubusercontent.com/29560286/27314044-d4b4ebe8-5536-11e7-849b-e7fcf79465f6.png)

Thank you,
Farbal

**Comment by MarjieAVolk** [comment]
What you are seeing is placeholder text, because an error client side prevented the window from initializing all the way.  This doesn't necessarily mean your leader is not set correctly.

I've already fixed some government problems in 5.6, and changed how laws are set up a bit, so this error might already be fixed - but do you happen to have an output log file?  It will be in your Eco_Data folder.

**Comment by Farbal** [comment]
I don't believe that it was a client side issue, seeing as multiple people reported the exact same graphical error.
being said, here is the file you asked for!

thank you for getting back to me so quickly, I will let you know if we have a similar issue in 5.6

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1090180/output_log.txt)

**Comment by MarjieAVolk** [comment]
Hm well there isn't anything in your log there.  Do let me know if you still see it in 5.6.

I have a theory, but it's hard to determine if it's correct.  Does logging out and back in change the behavior for you?  If not that, then does restarting the server change it?  What also might help me figure it out is your server's Game.eco save file, if you have access to that.

**Comment by Farbal** [comment]
Logging out then back in, does not change the behavior. I'm not sure if restarting the server would have changed it we didn't try that, and we have moved on to playing 5.6. I tried to give you the Game.eco file, but it was too large. However, you can access the file at this link, https://filenurse.com/download/04975c0ac5250fccc8d0787b0a13668f.html

**Comment by MarjieAVolk** [comment]
Well, since this bug was on an old version, and laws have changed some behind the scenes, I'm going to close this for now.  If somebody sees this issue in 5.6, I'll be able to get better error messages there.
