### ISSUE TITLE
[0.9.0 staging-1630] Linked inventories have a strange free space

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16894]
![image](https://user-images.githubusercontent.com/45708377/85830685-aa190d00-b795-11ea-9f83-a6c7091b61e2.png)
![image](https://user-images.githubusercontent.com/45708377/85830718-b604cf00-b795-11ea-8697-5f39d580ec61.png)

**Comment by mirasrael** [comment]
FastLayuout?
