### ISSUE TITLE
[0.9.0 staging-1630] Web Election: ratification election shows candidates

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16893]
There should be just yes/no voting as in every binary election without candidates

![bandicam 2020-06-26 12-04-11-772](https://user-images.githubusercontent.com/27898520/85830612-54009580-b7a6-11ea-9ad2-aeadc03280e4.jpg)

**Comment by j3fffff** [comment]
ranked candidates box is showing for all types of elections

**Comment by denysaw** [comment]
https://github.com/StrangeLoopGames/Eco/pull/6345
