### ISSUE TITLE
9.0 1611 - Tax Laws not compounding?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16901]
So we have the below law setup

if wealth over 20% then tax 2.5% of wealth
If wealth over 15% then tax 2.5% of wealth
If wealth over 10% then tax 2.5% of wealth
If wealth over 7.5% then tax 1.5% of wealth

The logic being if someone had 10000, they'd get hit by the 7.5% and then 10% tax band so total tax is 4%, if they had over 15k then it'd be 6.5% etc

![image](https://user-images.githubusercontent.com/61889138/85946025-80005000-b939-11ea-9282-26af32c33d3c.png)

But it looks like it is only doing it based off the "lowest section of the law, do they need to be in reverse order? or did it just stop processing once it got a match?

The law has vanished off the court it was on so I cannot edit it or tweak it further (this on on Imperial Otter playtest) it was on the "Economy court" 843,1356

![image](https://user-images.githubusercontent.com/61889138/85946039-95757a00-b939-11ea-8744-5ddee7e26cb0.png)

Mephy and Engi should've both had tax in the 425 kind of tax, but its showing they only got selected for the 7.5% part of the law.

**Comment by MishkaFur** [comment]
@WeaselDog this is now even weirder......the one it found as a hit has changed.

Following our convo over discord where it just finds first match then runs off that

![image](https://user-images.githubusercontent.com/61889138/85993251-f068a900-b9ed-11ea-9257-ec6dce477776.png)

**Comment by MishkaFur** [comment]
It does seem to be a bit related yes but yea this is all in 9.0 

its now gone back to 7.5%
![image](https://user-images.githubusercontent.com/61889138/86109050-dc8b7880-babb-11ea-86cd-f4a052b627ab.png)

**Comment by beastyn** [comment]
After some investigation what I see.
For checking numbers I was using a bit different law, like this
![bandicam 2020-07-07 16-45-45-899](https://user-images.githubusercontent.com/27898520/86776081-59e15b00-c071-11ea-8e3a-7493280e06d0.jpg)

1) Each section was checked
2) Every person was taxed accordingly the law
3) But it will count numbers from amount of wealth person has after section pass.

ie. If person has 302 coins. First section will take 4% from 302, second section will take 3% from 290 (302-204*0.04)
![bandicam 2020-07-07 17-06-13-356](https://user-images.githubusercontent.com/27898520/86778793-366bdf80-c074-11ea-8b21-916002829afd.jpg)


So, in general it seems to be working for me.

**Comment by beastyn** [comment]
If we need to detect different base for the hole law we can think about it though

**Comment by beastyn** [comment]
Close sue no additional information. Please tell if issue is still valid.
