### ISSUE TITLE
Meteor rendering wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16902]
![image](https://user-images.githubusercontent.com/3536496/85958208-9d88e600-b948-11ea-9959-707a82d015d7.png)
It is no longer faded as if its behind the atmosphere, and a color like the moon since its a celestial object reflecting the sun. Revert to previous settings. Also, always include a screenshot when you make changes like this so it can be caught before the PR is merged

**Comment by redwyre** [comment]
see https://github.com/StrangeLoopGames/EcoIssues/issues/14882

**Comment by johnkslg** [comment]
This is must-fix for 9
