### ISSUE TITLE
Einlogprobleme 

### ISSUE THREAD

**Issue by Vija69** [StrangeLoopGames/EcoIssues#16905]
Ich kann nicht mehr auf dem Eigenen Server Einlogen. Weder das Neustarten des Servers noch Rechnerneustart oder Streamneustart haben geholfen. Fehlersuche in den Localen Dateien über Steam auch nicht. 
Da ich von programmieren keine Ahnung hab und mir all die Daten im Logfile nichts sagen würd ich mich Freuen über etwas Hilfe damit ich meinen Spielspass auch weiterhin mit Freunden Geniessen kann. Das Eilogen auf Fremden Servern Funktioniert nach wie vor. Ich bin mir sicher das Der Fehler nicht neu ist und sicher jemand schonmal dieses Problem hatte. Ich weiß jedoch nicht wo ich Dazu Antworten finden kann welche mir Weiterhelfen. 
mfg Vija. Anbei der Bugreport. 

<size=150%>Verbindung fehlgeschlagen</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>Error: TrustFailure (One or more errors occurred.)</size>

Log File:
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path D:/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX 580 Series (ID=0x67df)
    Vendor:   
    VRAM:     8171 MB
    Driver:   27.20.1017.1011
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.942300 ms
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

Logging in as 76561198031242317 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU5MzQxMDU0NywidnhhIjoibG9naW4iLCJ2eGkiOjM4MjM3OTgsImYiOiJzaXA6LnN0cmFuZ2Vsb29wZ2FtZXMtZWNvLjc2NTYxMTk4MDMxMjQyMzE3LkBtdDFwLnZpdm94LmNvbSJ9.RgBhLLgFd3kjRFzfQVG5GE8UwAWqq_v-Z8req0Izhdk
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
UnityEngine.ReapplyDrivenProperties:Invoke(RectTransform)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Connecting to 62.104.107.31:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Login info could not be verified. Our auth servers may be down.

<size=60.00%>Error: TrustFailure (One or more errors occurred.)</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 89429.
Total: 272.256400 ms (FindLiveObjects: 7.370100 ms CreateObjectMapping: 6.425000 ms MarkObjects: 257.848300 ms  DeleteObjects: 0.612300 ms)

Logging in as 76561198031242317 using token 
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Error parsing voice login reponse
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Logging in as 76561198031242317 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU5MzQxMDU2MSwidnhhIjoibG9naW4iLCJ2eGkiOjM4MjM4MDAsImYiOiJzaXA6LnN0cmFuZ2Vsb29wZ2FtZXMtZWNvLjc2NTYxMTk4MDMxMjQyMzE3LkBtdDFwLnZpdm94LmNvbSJ9.yMQTx_151Emf9LbDz7FL6A2kVx4c0xAwcWx9LnmUlbY
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.EventHandler`1:Invoke(Object, TEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
UnityEngine.ReapplyDrivenProperties:Invoke(RectTransform)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by beastyn** [comment]
@Vija69 thank you for the report and sorry for the delay.

Can you try this?
https://github.com/StrangeLoopGames/EcoIssues/wiki/UNITYTLS_X509VERIFY_FLAG_NOT_TRUSTED-issue-troubleshooting

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
