### ISSUE TITLE
Ecopedia glowing cursor movement sounds

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16907]
Need cool sound for these scrolling effects, with different ones for large/medium/small
![image](https://user-images.githubusercontent.com/3536496/85344317-34b2f100-b4a4-11ea-8854-387566f9b9d5.gif)

**Comment by beastyn** [comment]
Will be there different sounds for pages and subpages?

**Comment by Quadbro** [comment]
@beastyn Added a bit of ajustment between 3 sizes of cursor movement (Categories => page => subpage) (1, 0.5, 0)
Will be testable after second pr approved
