### ISSUE TITLE
Ocean sounds distance

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16917]
Ocean sound was quite loud here, seemed like a bug
![image](https://user-images.githubusercontent.com/6802030/85985289-bb238180-ba14-11ea-98c2-b1671c0456e6.png)

Heard a raging ocean at this placid lake. Make the ocean detection only detect sea level water. Something very wrong with the ocean sound, its everywhere and overpowering.
![image](https://user-images.githubusercontent.com/6802030/85985990-b90df280-ba15-11ea-9b6b-4979a5cdc0ff.png)

Heard no water sounds at this river and waterfall
![image](https://user-images.githubusercontent.com/6802030/85986026-c9be6880-ba15-11ea-91d9-931c5a2295be.png)

**Comment by SlayksWood** [comment]
For me distance doesn't change a lot, but it became quieter
https://drive.google.com/file/d/1JoJSyRp60aXbxgCtRRuzGTowroD9iuG3/view?usp=sharing

**Comment by SlayksWood** [comment]
@johnkslg Can you check it?
