### ISSUE TITLE
 Opening UIs via shortcut keys should make noise

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16914]

**Comment by SlayksWood** [comment]
Ecopedia have 2 sounds now. 
It's strange to hear this sound for BackPack.
When you open it with LMB all UIs have 2 sound:
https://drive.google.com/file/d/1WeBSU7LD3cTo5NAFQxmjxPdv32EDdFls/view?usp=sharing

**Comment by SlayksWood** [comment]
need to recheck double Ecopedia sound

**Comment by SlayksWood** [comment]
And chat open without any sound. Is it right?

**Comment by Quadbro** [comment]
fixed both cases
