### ISSUE TITLE
Popup notifications needs sounds

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16915]
Add a very unobtusive notice sound to popups. Should be different for 'status' vs 'error'. Note that these appear all the time so it shouldnt sound too 'error-like'

**Comment by beastyn** [comment]
Don't hear difference between error and notice sound

**Comment by Quadbro** [comment]
So we decided to make one simple, tiny sound for popups (that is genereous, and not too erre-like), cause errors are more common, and difference between that sounds will be unnouticable. But we can make different ones later, if needed.
