### ISSUE TITLE
[0.9.0 staging-1633] Elusive crash

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16928]
1. Start new world
2. Just do something somewhere.

At Friday it was pressing "Perform action" in the ballot box Enter Election

Today it was choosing an item in the mint. It always looks like this

```
System.Exception: Could not find matching method SetCoinsPerItem on type MintComponent taking 1 parameters.
   at Eco.Shared.Networking.RPCManager.InvokeOn(INetClient client, BSONObject bson, Object target, String methodname)</size>
```
[crash2.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4845190/crash2.txt)

**Comment by mirasrael** [comment]
@SlayksWood @beastyn Do you have this issue recently (after pooling fixes)?

**Comment by SlayksWood** [comment]
Seems fixed.
