### ISSUE TITLE
Hover sounds

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16920]
When mousing over UI elements, many will highlight with your cursor appearing over them. This should be accompanied by a sound, and it should vary for different types of buttons. It should be super subtle and soft.
![image](https://user-images.githubusercontent.com/6802030/85985531-0d64a280-ba15-11ea-845f-efa36c9550c5.png)

**Comment by beastyn** [comment]
Waiting for some improvements in SVN
