### ISSUE TITLE
Screen stutters, Game drops FPS and/or Crashes Eco 0.5.6

### ISSUE THREAD

**Issue by NightmanEco** [StrangeLoopGames/EcoIssues#1692]
I can be playing Eco 0.5.5.6 for a little while until I get a weird stutter across my screen and Eco drops FPS from 60 to 12 and/or crashes afterward. Anytime I try to reload the game, it will be down at that FPS. When I start the game, the rest of the computer will also become very slow, but only when that happens. 

When I delete the AppData folder and do a restart, it fixes the problem, but only temporarily until it happens again.  This happened on 0.5.5.4 and the stage version of 0.5.6. (I just bought the game today.)

Below is a Goole Drive link that has my computer specs, crash report, and video of what it looks like. I The server I click on in the video, the debug server available in the stage version is the server I was using the last time it happened if you wanted to get the game.eco file.

https://drive.google.com/open?id=0ByCKTt8OKJzARWh6UVA2U1k1QU0

I really want to enjoy this game, I've been anticipating it for a long time. I really appreciate your help.

Thank you so much!

**Comment by metachronism** [comment]
Which graphics options do you have turned on?

**Comment by metachronism** [comment]
we still have lots of optimization to do, especially in regards to rendering, but I am going to close this out for now as its not specifically a bug per-sey.  We are always keeping an eye on perf to keep it in the playable range before we do a larger perf-only round of fixes closer to beta release
