### ISSUE TITLE
Game modes buttons sound

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16924]
Clicks not working on these left right buttons. Try all buttons in this dialog and title screen make sure they make noise, even after leaving and returning to screens.
![image](https://user-images.githubusercontent.com/6802030/85986084-e5297380-ba15-11ea-844b-66cbb264a81c.png)

**Comment by beastyn** [comment]
No click sound in the servers filter (its)
![bandicam 2020-07-02 15-07-05-032](https://user-images.githubusercontent.com/27898520/86345983-b6113d00-bc75-11ea-8bdd-c4c3213cc988.jpg)

No click sound in the server list in the New Game 
![bandicam 2020-07-02 15-01-52-702](https://user-images.githubusercontent.com/27898520/86345451-fd4afe00-bc74-11ea-8856-f534ad61a4c8.jpg)

**Comment by Quadbro** [comment]
Added sound to filter panel and browser list
