### ISSUE TITLE
Item pickup sounds

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#16923]
No sound on pickup of these + other items pickup recheck
![image](https://user-images.githubusercontent.com/6802030/85985772-616f8700-ba15-11ea-8776-3769f0ffe528.png)

**Comment by beastyn** [comment]
No sound for carcass pickup sound
No plants pickup sound (tomato, beet, etc.)

**Comment by Quadbro** [comment]
Added carcass pickup sound, added plants pickup sounds
