### ISSUE TITLE
[0.9.0 staging-1634] Animals failed to set tick

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16934]
![image](https://user-images.githubusercontent.com/45708377/86106454-3e9eaa80-bac9-11ea-81d0-30bacbf22b9f.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/86217486-38233800-bb88-11ea-8a9f-237012426d6f.png)

**Comment by SlayksWood** [comment]
hmm seems it happens once again for me. But I don't have a lot of spams.

**Comment by beastyn** [comment]
Nope, still here
![bandicam 2020-07-08 16-10-58-256](https://user-images.githubusercontent.com/27898520/86911977-9ecec580-c135-11ea-9887-d5d064dd86a3.jpg)
![bandicam 2020-07-08 16-10-16-606](https://user-images.githubusercontent.com/27898520/86911985-a0988900-c135-11ea-986b-7673e551aca8.jpg)

**Comment by johnkslg** [comment]
Havent seen this with latest changed, marking fixed.

**Comment by Truewillis** [comment]
![image](https://user-images.githubusercontent.com/70230569/91211983-359b1580-e6d5-11ea-92b4-3da7de39d4d9.png)

was there a solution for this?

**Comment by aear** [comment]
I'm getting a lot of these too.
Usually seems to be wolves an coyotes and while I have the server running whilst I sleep.

![image](https://user-images.githubusercontent.com/2921052/91873766-59c89a80-ec71-11ea-91ed-41aed2833da2.png)
