### ISSUE TITLE
'Curved/Standard (Vertex Color)' Shader does not sort correctly with Eco Water

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16931]
![image](https://user-images.githubusercontent.com/14983165/86065340-350f3700-ba24-11ea-910a-454d76ece581.png)

This is a shader used for many particle effects, and currently it has strange sorting issues around water. Perhaps this is an issue with the water more than this shader.

For ref, the material of the particle effect in the screenshot:
![image](https://user-images.githubusercontent.com/14983165/86065429-7273c480-ba24-11ea-9e5a-335410fb0b33.png)

**Comment by redwyre** [comment]
Unassigning myself as @StanKryvenko has assigned it as a week task, but feel free to hit me up if you need anything

**Comment by StanKryvenko** [comment]
Fixed water in SVN
