### ISSUE TITLE
Minimap Refactor

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16930]
The minimap has accumulated 'just one more little piece of code I'll slip in here' for 4 years and is now a spaghetti patched up nightmare.  Pull it apart and make it a clean architecture.

I've grouped properties into different subcomponents they can be a part of.
![image](https://user-images.githubusercontent.com/3536496/86064664-8b7b7600-ba22-11ea-9819-6c6a09e2c7c1.png)

When pulling these apart, its important not to just naiively do it and make it call back into MinimapUI.  All references to MinimapUI in subcomponents of MinimapUI should be removed from other components as part of this task, and replace their need to call MinimapUI with callbacks provided by the subcomponent.

Display modes (property, districts, world layers) should be treated generically with derived classes providing the specifics, instead of being reimplemented 4 times.

Make the settings dialog use prefabs and modified prefabs, sharing all similar types.
![image](https://user-images.githubusercontent.com/3536496/86065627-f332c080-ba24-11ea-9f95-fed406028160.png)

Cleaning up the minimap will give us a solid foundation to keep clean and work with in the future.

**Comment by redwyre** [comment]
I started doing this by splitting code files to ui folder and rendering, and added the MinimapRig class to move some of the rendering stuff too (it's the root of the rendering prefab)

**Comment by IcedForge** [comment]
@gzatravkin Closed as per the other one same deal, just as a reminder if there is any information you want to copy & write up in a doc somewhere.
