### ISSUE TITLE
[0.9.0 staging-1634] Web election: graphs are shy in the comments

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16939]
Why are they so tight. Give them some more space, there is nothing around, even no map
![bandicam 2020-06-30 18-02-55-749](https://user-images.githubusercontent.com/27898520/86129344-f5b41980-bafb-11ea-9622-d17085a664f4.jpg)

**Comment by denysaw** [comment]
Strange. They had normal width when I was testing it. Will re-check. Cache cleared, right?

**Comment by beastyn** [comment]
Yeap, cleared with Ctlr+f5

**Comment by rainfarmer** [comment]
fixed, they are very friendly now

**Comment by beastyn** [comment]
Erm, why can't it be like this wide if there is no map around?
![bandicam 2020-07-06 10-39-06-445](https://user-images.githubusercontent.com/27898520/86559921-92e8d500-bf76-11ea-80d5-8e88f1111e2c.jpg)

And it seems this has broken the map around (thy are overlaped)

![bandicam 2020-07-06 10-40-38-502](https://user-images.githubusercontent.com/27898520/86559954-a4ca7800-bf76-11ea-9fa3-9d87098d9fea.jpg)

**Comment by j3fffff** [comment]
fixed the map and graph collision.

@denysaw you want to add support for full width comment graph, when there is not a map present.

**Comment by denysaw** [comment]
@j3fffff And it'll be real 100%? I can, if needed.

**Comment by j3fffff** [comment]
not full screen, just as long as comments area. i think its 98%
