### ISSUE TITLE
9.0 1611 - Law trigger "play" does nothing?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16935]
Law trigger "play A citizen has remained logged in for a moment" does not appear to do anything, had a law setup to use it to then pay them 1 Monies, have been logged in for a while, done various different actions so it should've realised I have played.

Should perhaps also say "user has been logged in for 5min" as a moment is not obvious

**Comment by MishkaFur** [comment]
Seems the "play" does do something when combined with pay some monies but it was not obvious till i looked into my transaction history.

It should only run perhaps once though ie you log into the server, be on it for 5min then it does the action?

**Comment by beastyn** [comment]
@MishkaFur
Play itself is just a periodic trigger, which is happening every 30 seconds on every logged in user.
That is in the description.
![bandicam 2021-03-17 14-55-51-658.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/d6610e6c-0144-4afc-9f39-a753300e2cf0)

So I assume I can make this description more clear.
For example if you bide a transferring to this trigger it will make a transfer every 30 seconds with every person online. Other words, every online player will trigger Play every personal tick (30 sec).

Usually it can be used for some checks on every logged in player, for example

**Comment by MishkaFur** [comment]
@beastyn 

It did not used to say every 30 sec so that is probably what led to the confusion as I was trying to do a law to send a message almost like a Message of the day kind of thing

"Please read the rules" kind of stuff

The Trigger makes 100% sense with the description so can close this though I do think a trigger of "Player has logged in" other than Player's first login would be useful for doing message of the day, updating people about rules message wise or even just doing custom stats, demographics etc

**Comment by beastyn** [comment]
#8119 for log in action
