### ISSUE TITLE
Game Crashes about every 10 minutes

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16932]
AMD Ryzen 9 3900X 12 core processor 3.79 GHZ
32.0 GB RAM
Win 10 pro V1909

[Player (2).log](https://github.com/StrangeLoopGames/EcoIssues/files/4849470/Player.2.log)
[error (2).log](https://github.com/StrangeLoopGames/EcoIssues/files/4849471/error.2.log)
[crash (6).zip](https://github.com/StrangeLoopGames/EcoIssues/files/4849474/crash.6.zip)

**Comment by redwyre** [comment]
Possibly graphics issue, get them to update graphics drivers

**Comment by trickenso** [comment]
Also check whether they are overclocked? There have been a few reports of regular graphics crashes on overclocked cards.

**Comment by MishkaFur** [comment]
Yea GPU memory clocks seem to make Eco's unity unstable, GPU processer overclocks are fine (same for CPU and memory) but it just seems GPU memory clocks makes it sensitive on nvidia cards.

**Comment by redwyre** [comment]
Overclocks have nothing to do with Eco, if Eco doesn't run with an overclock then the overclock is unstable. We may have to add that to our standard questions @beastyn @SlayksWood

**Comment by MishkaFur** [comment]
> 
> 
> Overclocks have nothing to do with Eco, if Eco doesn't run with an overclock then the overclock is unstable. We may have to add that to our standard questions @beastyn @SlayksWood

The GPU memory OC can be stable in other games and benchmarking but even just a few mhz i've seen makes eco/Unity unstable (but other unity games are fine), might also be related to drivers at the same time

**Comment by D3nnis3n** [comment]
@redwyre

AMD Radeon RX 5700 XT, Drivers are up to date.

**Comment by redwyre** [comment]
This is a long shot, but try setting desktop resolution to 1080p and starting the game, and setting the res to be 1080p (or shrinking render scale) in game. Should be able to revert desktop after.

**Comment by redwyre** [comment]
Also try getting them to play 9.0 and see if they have the same problem

**Comment by D3nnis3n** [comment]
I've not heard back from the affected person, starting 7 days to close timer.

**Comment by D3nnis3n** [comment]
Person did not get back to me, closed.
