### ISSUE TITLE
Accounts: Newsletter Consent

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16944]
It does look like we are currently not actively asking for a newsletter subscription when someone registers an account on SLG, at least i cannot remember ever having been asked. Regarding to EU law we are required to give them a checkbox that must be unticked by default, though. We have a little elevated rate of newsletter unsubscribes and this might be a potential reason.

People in the EU don't like to get e-mails they never explicitly asked for.

Please take a look how this currently is done and in case we do not do it like i described above, change it to a unticked checkbox at registration.

**Comment by denysaw** [comment]
@rainfarmer Could you implement design/html/css and I'll make all needed functionality afterwards?

**Comment by j3fffff** [comment]
@denysaw updated develop with html
