### ISSUE TITLE
CTD When Trying to Open Objectives

### ISSUE THREAD

**Issue by Charabis** [StrangeLoopGames/EcoIssues#16942]
- Client Issue

OS : Windows 10

Worked fine yesterday, but today when trying to open "Objectives" window, whether by hitting "o" or clicking it, it causes the game to crash to desktop.  It's done this every time today, so should be very repeatable.

As for logs, I went to \AppData\LocalLow\Strange Loop Games\Eco\Crashes, or tried to.  The folder doesn't exist, nor apparently do any logs to indicate what happened.

**Comment by SlayksWood** [comment]
@Charabis Thank you for the report. I need some more information.
1. What game version are you using?
2. Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
