### ISSUE TITLE
[0.9.0 staging-1634] Civics: add voters to the server config

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16941]
From #16724
We need to add voters as list of 4 basic demographics into server config for basic election settings

**Comment by johnkslg** [comment]
We default to 'Active' and none of the other options are better, I suggest we keep it to that and close this bug.

**Comment by beastyn** [comment]
@MishkaFur @IcedForge Did you have situations where you needed to setup Voter list?
