### ISSUE TITLE
Accounts: icon updates

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#16943]
- Update icon migrations to set everyone's selected_icon as their highest icon possible.
here is ranking of icons from lowest to highest:
default icon
betaicon
beta2packicon
beta4packicon
alphaicon
alpha2packicon
alpha4packicon
devicon
wolficon
kickstartericon
paxicon
slgicon
bannericon
hareicon
supericon

- Update successful user purchase, if their icon is higher then their previous icon, updated with their new purchase's icon.

- We need to update migrations and website to replace `2packicon`, `4packicon` with `alpha2packicon`, `alpha4packicon`, `beta2packicon`, `beta4packicon`
Just like `alphaicon` we can determine which icon they get based on purchase date or lack of date.

**Comment by WeaselDog** [comment]
I was just asking about this issue actually in https://github.com/StrangeLoopGames/EcoIssues/issues/16615#issuecomment-651936198

What do the icons Banner, Hare, and Super represent? I believe Hare is the same as Wolf Whisperer, but we are not sure what the banner or super icon should represent and who they should be applied to.

**Comment by rainfarmer** [comment]
they correspond to kickstarter tiers
http://i.imgur.com/UTgLbdr.jpg

**Comment by WeaselDog** [comment]
Cool, thanks for clarifying.

**Comment by denysaw** [comment]
All done, but used icon ranking progression like we had in migration (actually icons in `icon` field should and was sorted from lowest to highest):
![image](https://user-images.githubusercontent.com/5720101/86261269-a256cf80-bbbe-11ea-97e3-f27d641326f5.png)

so beta -> alpha -> 4packicon -> devicon -> hareicon -> bannericon -> wolficon -> supericon -> slgicon
+special kickstartericon/paxicon in addition.

E.g. look on this line: `('wolf',      14,  '4packicon;devicon;hareicon;bannericon;wolficon', 'hare;banner;wolf'),`

Means Wolficon higher/contains not just dev, but than hare and banner, which both goes after in your progression. 
So if our old progression was wrong, please set up new progression for each icon and reward (e.g. there `wolf` also contains hare and banner) in migration file: `006_GiveIconsAndRewards.php`. Cuzz right now old and your progression contradict each other :/

And if I did right using old progression we had in migration, then task is completed :)
