### ISSUE TITLE
[0.9.0 staging-1634] icon overlaps text in right notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16947]
![image](https://user-images.githubusercontent.com/45708377/86217134-b3d0b500-bb87-11ea-9bd6-c511f44678c6.png)

**Comment by gzatravkin** [comment]
Looks be already fixed
![image](https://user-images.githubusercontent.com/53317567/87116804-23f8ce00-c24d-11ea-9379-623538387290.png)
