### ISSUE TITLE
[0.9.0 staging-1635] Fish swims over the water

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16951]
![image](https://user-images.githubusercontent.com/45708377/86227553-d9fd5180-bb95-11ea-9e56-0e8861e1911a.png)

**Comment by beastyn** [comment]
check after #16951

**Comment by SlayksWood** [comment]
Still a issue:
![2020 08 03 Fish swims over the water](https://user-images.githubusercontent.com/45708377/89172381-37b4fd00-d58b-11ea-9353-0d6d1fb1f8cd.gif)
