### ISSUE TITLE
[0.9.0 staging-1636] Law UI after #6326

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16954]
- [x] 1. Overlapping delete and expand buttons in section:
![image](https://user-images.githubusercontent.com/45708377/86319360-0ae49180-bc3d-11ea-9327-fa87efecc5a7.png)

- [x] 2. Wrong position for "delete" button in trigger:
![image](https://user-images.githubusercontent.com/45708377/86319805-08366c00-bc3e-11ea-85ed-60d67372b506.png)
It has position like it should delete all triggers. so you need to move a little in red zone:
![image](https://user-images.githubusercontent.com/45708377/86319965-65cab880-bc3e-11ea-9638-644cd5bb7594.png)
![image](https://user-images.githubusercontent.com/45708377/86320012-8266f080-bc3e-11ea-8b96-e63d5285920b.png)

- [x] 3. Strange double "-" if mouseover None zone:
![image](https://user-images.githubusercontent.com/45708377/86320349-60ba3900-bc3f-11ea-8df4-b522d758f895.png)

- [ ]  4. A lot of "-"es lie outside the zone to be removed, so it’s difficult to remove them, so it make harder to delete this part. For example I want to delete trigger:
![image](https://user-images.githubusercontent.com/45708377/86320438-965f2200-bc3f-11ea-8c44-7664764357b1.png)
![image](https://user-images.githubusercontent.com/45708377/86320480-a5de6b00-bc3f-11ea-9669-41f46b88dc61.png)
![image](https://user-images.githubusercontent.com/45708377/86320518-b8f13b00-bc3f-11ea-85c1-41eddcd740dd.png)
> * The best way is green, you can always highlight "-". yellow - 50/50, if you move the mouse quickly then most likely you will highlight. Red - never:
>   ![image](https://user-images.githubusercontent.com/45708377/85271833-03c2c400-b484-11ea-936f-09265c748d58.png)

- [x] 5. Still hard to add if/then if I delete it: 
![image](https://user-images.githubusercontent.com/45708377/86320761-35841980-bc40-11ea-82e6-c5b7c01d6399.png)
Seems button is offsetted. I need to mouseover this to see it:
![image](https://user-images.githubusercontent.com/45708377/86320848-649a8b00-bc40-11ea-9e35-2d4e991fb850.png)

- [x] 6. Still an issue:
> The 'Trigger Configs' are a special dynamically generated list that should be treated as a block of properties, and users cant add/remove elements from it. Use attributes on the list property that get propoagated to the client (follow other property attribute examples) to force the system to behave this way.
![image](https://user-images.githubusercontent.com/45708377/86321264-526d1c80-bc41-11ea-8620-855eed885207.png)

- [x] 7. When you write many words in section sescription then UI moves after pressing every "space":
![2020 07 02 Law UI moves](https://user-images.githubusercontent.com/45708377/86322445-aa0c8780-bc43-11ea-8c71-939b7867326c.gif)

- [x] 8. If you write a long string in section description it will have free space under it:
![image](https://user-images.githubusercontent.com/45708377/86322326-72054480-bc43-11ea-89cc-effc5052110e.png)

- [ ] 9. Exclamation point is offsetted:
![image](https://user-images.githubusercontent.com/45708377/86322555-e2ac6100-bc43-11ea-8b95-74088c6ef940.png)

- [x] 10. Need some love here(if you add 2 if or more):
![image](https://user-images.githubusercontent.com/45708377/86322995-a75e6200-bc44-11ea-923a-6a764705d923.png)

**Comment by beastyn** [comment]
- [ ] summary is looking bas with icons, Too tight and with overlapping
![bandicam 2020-07-02 12-02-41-495](https://user-images.githubusercontent.com/27898520/86327080-17c4ad80-bc5c-11ea-817d-2ec5bc84d8b4.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/86327682-59e5f300-bc4c-11ea-9daf-ae001ecb8ad3.png)
> * 5. some elements in law don't upgrade if you add/delete something. you need to select fields or do something else. Step to reproduce:
> * start a new law:
>   ![image](https://user-images.githubusercontent.com/45708377/85273670-8e0c2780-b486-11ea-9b82-70a381be594e.png)
> * add some trigger:
>   ![image](https://user-images.githubusercontent.com/45708377/85273732-a8460580-b486-11ea-923d-6de94e3efe3a.png)
> * reselect trigger and this section:
>   ![image](https://user-images.githubusercontent.com/45708377/85273851-d1669600-b486-11ea-8a3a-042c5fccd359.png)
> * add some condition, we have overlap here:
>   ![image](https://user-images.githubusercontent.com/45708377/85274170-42a64900-b487-11ea-8083-554f031c98ed.png)
> * selecting something else will fix it:
>   ![image](https://user-images.githubusercontent.com/45708377/85274241-594ca000-b487-11ea-8fe5-694c66f19912.png)
> * but if you delete this condition then you will have a lot of space here:
>   ![image](https://user-images.githubusercontent.com/45708377/85274316-72ede780-b487-11ea-9b7f-f54ac78033ad.png)

**Comment by serpopov** [comment]
Text-related bugs will be fixed within TMPro upgrade revision

**Comment by SlayksWood** [comment]
Still an issue: 4,7,8,9,12

**Comment by SlayksWood** [comment]
Still an issue 4,9,12

- [ ] 13. Sometimes when I select 'is Admin' "-" doesn't appear:
![image](https://user-images.githubusercontent.com/45708377/88394217-b65dad80-cdc7-11ea-932c-9b78ce2a1922.png)

**Comment by serpopov** [comment]
I disagree 4 is an issue - its working well with case you described

**Comment by SlayksWood** [comment]
Closed, I opened separate issues.
