### ISSUE TITLE
[0.9.0 staging-1636] Gigot sleeve shirt icon/model issue

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16958]
So, now Gigot sleeve shirt is looking like that?
![bandicam 2020-07-02 13-05-02-050](https://user-images.githubusercontent.com/27898520/86350058-8bc27e00-bc7b-11ea-939e-4b8196ecafa7.jpg)

But the icon looks different with the vest part

**Comment by Dmittry62** [comment]
The same Gigot shirt icon is used for both male and female avatars. There should be another one for male avatar. Do we have one?

**Comment by SlayksWood** [comment]
female:
![image](https://user-images.githubusercontent.com/45708377/87298091-47a06a80-c512-11ea-9a43-f063e396312d.png)
male:
![image](https://user-images.githubusercontent.com/45708377/87298109-4d964b80-c512-11ea-81c8-39008d0e3976.png)
@keegan-o can you take a look?

**Comment by MilenkoTunjic** [comment]
Added same version of the shirt for male so the icon should accurately represent the shirt
