### ISSUE TITLE
[0.9.0 staging-1635] Animals don't respond to landscape changes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16950]
https://drive.google.com/file/d/1iCS5OJmiCAVuj6cpm1-NqtpdArTVaidF/view?usp=sharing

**Comment by johnkslg** [comment]
That video is hilarious. Little turtle that could.
Lets push to next animal upgrade

**Comment by beastyn** [comment]
Its pretty bad for animals with long routes. Jaguars can stuck in a house as they will ignore the wall of a house, so we've got complaints from the playtest. I think we should bring it back to 9.0.

**Comment by johnkslg** [comment]
@StanKryvenko there can be some kind of landscape manager that detects changes along an animals route and forces a repath.

**Comment by SlayksWood** [comment]
It's became better.
