### ISSUE TITLE
[0.9.0 staging-1636] Need to check hovering sound for interactibles

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16959]
This can be both sound and UI issue
- [x] 1) In legislation UI (L)
This headers don't do anything, but has hovering sound

- [x] 2) In Economy viewer (Y) you can click on the coordinate, but It do not have a hovering sound
![bandicam 2020-07-02 16-02-14-139](https://user-images.githubusercontent.com/27898520/86351350-94b44f00-bc7d-11ea-8160-ffbc6ae7ae29.jpg)

- [x] 3) In the transfer UI Send button does not have a hover sound
![bandicam 2020-07-02 16-05-46-874](https://user-images.githubusercontent.com/27898520/86351615-faa0d680-bc7d-11ea-9dfc-75e70a85a0bd.jpg)

- [x] 4) Skills UI -  specialties names has a sound, but does not do anything
![bandicam 2020-07-02 16-09-00-046](https://user-images.githubusercontent.com/27898520/86351906-6e42e380-bc7e-11ea-870a-d81fc20bbe78.jpg)

- [x] 5) Civics UI
Show Hide button does not have a hovering sound
![bandicam 2020-07-02 16-16-36-271](https://user-images.githubusercontent.com/27898520/86352792-cd552800-bc7f-11ea-87b1-07b742a58491.jpg)

- [x] 6) Civics UI
+, - 
Select
![bandicam 2020-07-02 16-31-26-506](https://user-images.githubusercontent.com/27898520/86353916-81a37e00-bc81-11ea-8e01-9511da6ca94b.jpg)

**Comment by Quadbro** [comment]
Will handle that in audio pass, just need to add some actions for ignoring hover sounds in exeptional cases

**Comment by Quadbro** [comment]
4. Has tooltip, skipping
