### ISSUE TITLE
Can't login to staging world, after using swagger's /api/v1/elections/generatetestdata

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#16963]
1 Start fresh world
2 Login to world from client
3 From Swagger use /api/v1/elections/generatetestdata
4 Client kicked and cant log back in. Log in gives this error:

<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Elections.Election.FullDescribe()</size>

Log File:
PlayerConnection initialized from C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55053
Multi-casting "[IP] 192.168.213.113 [Port] 55053 [Flags] 2 [Guid] 4103786561 [EditorId] 3867029654 [Version] 1048832 [Id] WindowsPlayer(MotherShip) [Debug] 0 [PackageName] WindowsPlayer [ProjectName] Eco" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55053]
PlayerConnection already initialized - listening to [0.0.0.0:55053]
Initialize engine version: 2019.4.1f1 (e6c045e14e4e)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   
    VRAM:     4018 MB
    Driver:   26.21.14.3200
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.549100 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename: C:\buildslave\unity\build\Runtime/SceneManager/SceneManager.cpp Line: 582)

WwiseUnity: Wwise(R) SDK Version 2019.2.1 Build 7250.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Running with audio. To disable audio and increase load speed, delete Content/Wwise_Eco folder or rename it.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script (ImportantNotificationsListController) on this Behaviour is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 199)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

The referenced script on this Behaviour (Game Object 'Important notifications') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Connecting to 192.168.0.17:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ServerInfo)
SelectedServerUI:Join()
Steamworks.ServerFailedToRespond:Invoke()
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
System.EventHandler`1:Invoke(Object, TEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename: C:\buildslave\unity\build\Runtime/VirtualFileSystem/ArchiveFileSystem/ArchiveStorageReader.cpp Line: 584)

Missing following icons:
AttachmentComponent
BlockForm
ChargingComponent
DeedManagementComponent
DidntVote
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
VehicleHoeComponent
VehicleToolComponent
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Missing following objects: AirPollutionGeneratorObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Elections.Election.FullDescribe()</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
Eco.Shared.Networking.UdpDisconnectedHandler:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
Steamworks.ServerFailedToRespond:Invoke()
System.Xml.Schema.XdrBeginChildFunction:Invoke(XdrBuilder)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.ServerFailedToRespond:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 1.09 GB.
System memory in use after: 0.78 GB.

Unloading 8167 unused Assets to reduce memory usage. Loaded Objects now: 251002.
Total: 2011.758600 ms (FindLiveObjects: 61.712100 ms CreateObjectMapping: 30.737400 ms MarkObjects: 1697.257800 ms  DeleteObjects: 222.050200 ms)

Connecting to 192.168.0.17:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ServerInfo)
SelectedServerUI:Join()
Steamworks.ServerFailedToRespond:Invoke()
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
System.EventHandler`1:Invoke(Object, TEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename: C:\buildslave\unity\build\Runtime/VirtualFileSystem/ArchiveFileSystem/ArchiveStorageReader.cpp Line: 584)

Missing following icons:
AttachmentComponent
BlockForm
ChargingComponent
DeedManagementComponent
DidntVote
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
VehicleHoeComponent
VehicleToolComponent
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Missing following objects: AirPollutionGeneratorObject
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Elections.Election.FullDescribe()</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
Eco.Shared.Networking.UdpDisconnectedHandler:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass60_0:<Initialize>b__0()
Steamworks.ServerFailedToRespond:Invoke()
System.Xml.Schema.XdrBeginChildFunction:Invoke(XdrBuilder)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.ServerFailedToRespond:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 1.11 GB.
System memory in use after: 1.07 GB.

Unloading 7151 unused Assets to reduce memory usage. Loaded Objects now: 296289.
Total: 781.760600 ms (FindLiveObjects: 25.542400 ms CreateObjectMapping: 24.675100 ms MarkObjects: 714.314400 ms  DeleteObjects: 17.227800 ms)

**Comment by redwyre** [comment]
This looks like the actual error:
> <size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay
System.NullReferenceException: Object reference not set to an instance of an object.
at Eco.Gameplay.Civics.Elections.Election.FullDescribe()

**Comment by rainfarmer** [comment]
https://github.com/StrangeLoopGames/Eco/pull/6340
