### ISSUE TITLE
[0.9.0 staging-1636] Web elections: graphs don't match

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16960]
1. This is how graph looks in the preview for comments
![bandicam 2020-07-02 17-41-20-690](https://user-images.githubusercontent.com/27898520/86360909-7ace3880-bc8c-11ea-9677-e699a15b21fe.jpg)
See, this one has bars for actions
2. After saving we don't have this bar here no more
![bandicam 2020-07-02 17-41-30-184](https://user-images.githubusercontent.com/27898520/86361523-6b032400-bc8d-11ea-851f-5742e8fead7e.jpg)

**Comment by denysaw** [comment]
To solve this, this one should be done and merged first: https://github.com/StrangeLoopGames/EcoIssues/issues/17039

**Comment by denysaw** [comment]
Solved both. @beastyn WARNING: only new comments' graphs will have different types (columns, etc), all old posted will be just lines as they have no type info stored.
