### ISSUE TITLE
[0.9.0 staging-1637] Fishing pole sound adjustments

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16965]
1) There is no reel sound at the beginning (it appears only on some close distant as if it's on the fish, not the fish pole)
2) Sound for fish splashing is reverted. There is no sound when a fish is in the water, and it appears when a fish is in the air.
https://drive.google.com/file/d/13ftJUWBsATzKWElBUiTt3G4FYznnwkyn/view?usp=sharing

**Comment by SlayksWood** [comment]
1. Reel sound should appear when I twist it. But if I start twist it  and finish at 1 ms I hear a long twist sound.
2. Sound for fish splashing appear when I catch fish, but it is interrupted by reel sound.
3. I steel have Sound for fish splashing on a coast.
https://drive.google.com/file/d/1Z79W8FrUsITJmoLB9VxQK3q_pzSSOTPc/view?usp=sharing

**Comment by SlayksWood** [comment]
Seems reel sound tied to bobber. I can't hear it well when he's far.

**Comment by SlayksWood** [comment]
Still an issue:
1. Reel sound should appear when I twist it. But if I start twist it and finish at 1 ms I hear a long twist sound.
2.I still have Sound for fish splashing on a coast.

**Comment by SlayksWood** [comment]
Need to test after fixing this issue #20452
> 2\. I still have Sound for fish splashing on a coast.

**Comment by IcedForge** [comment]
Seems like all the sound issues seems to be resolved, there is still a few odd cases but those are not caused by the audio misbehaving but the fishing rod itself.
