### ISSUE TITLE
Cloud Worlds: update client's build information

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16968]
Server is updated to 0.9 version
But links and requirements are still for the 8.3.3 version

![bandicam 2020-07-03 15-22-43-420](https://user-images.githubusercontent.com/27898520/86460014-16b97c00-bd41-11ea-8a83-813ff965b8f2.jpg)
![bandicam 2020-07-03 15-22-54-606](https://user-images.githubusercontent.com/27898520/86460016-17eaa900-bd41-11ea-9724-4e9f62550f26.jpg)

UPD: after one more updating picture is a bit different
It says version is 9.0.0 but there is no links.
![bandicam 2020-07-03 15-46-04-537](https://user-images.githubusercontent.com/27898520/86462005-52a21080-bd44-11ea-8aaa-f6a080dfbfb3.jpg)

**Comment by denysaw** [comment]
@beastyn Done. Btw, right now, if world doesn't start for you (you see dotted pre-loader) - that means, that world REALLY doesn't start. For me during tests, sometimes versions were changed (world restarted) in 2 minutes, sometimes hangs for 15-20 minutes (and then I just screw it and closing the tab). Now you could also see in F12-Network tab, that there's a request to world/info (via Accounts server) every 5 seconds. To find out error game server returns simply copy world's url from big url (from last slash till the end): `https://accounts.developland.strangeloopgames.com/getWorldInfo/world6.eco.hw.sfo2.do-slg.com` -> `world6.eco.hw.sfo2.do-slg.com` and add `/info` in the end. For me it's usually 502 error. Seems nginx is getting wrong about new world's docker container IP, cuzz as I remember usual container-loading error is 503. You could ask more GameDevs if 20+ mins of world's loading seems too much for you ;) So now you know it's REALLY world start hangs and not some accounts->world sync mistake (like happened before, when you should refresh manually to request it once more).
