### ISSUE TITLE
[0.9.0 staging-1637] GI checking message

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16964]
1) It seems to work in the wrong way. It will tell you that you don't have enough memory when you actually do.
2) Need some improvements on logic here. If you will grab scroll and move it around from low to high without releasing it, you will have a bunch of messages.
Message should appear only after releasing button (like decision was made at this point).
![d46680b64490e542e5466c3a1e412e1d](https://user-images.githubusercontent.com/27898520/86439837-bf0c1800-bd22-11ea-8b5a-6072fd970ecb.gif)

**Comment by SlayksWood** [comment]
fixed here https://github.com/StrangeLoopGames/Eco/pull/6338
