### ISSUE TITLE
Stuck at downloading mods on nearly every server, even ones without mods

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#16977]
> I changed my ISP recently, so now when I tried to join couple of servers, I was stuck at either Downloading mods 0% or at 33%. The only server that has loaded is the one without mods. Was there any recent update that may lead to that or is it my ISP? I have no such problems with any other games I played recently or any other software

All info and logs over there: https://steamcommunity.com/app/382310/discussions/4/2576571715844572117/

**Comment by WeaselDog** [comment]
Not able to replicate this in latest version
