### ISSUE TITLE
9.0 1611 - Tax player wealth does not tax bank accounts?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#16979]
Have got an abandoned law on the server set to tax player wealth but it only seems to actually tax the player's personal account, it has also not worked on Scott who has a shop account with only himself as a user.

I dont think the wealth calculation applies on it either for tax based off wealth

![image](https://user-images.githubusercontent.com/61889138/86514560-fc4bd500-be0a-11ea-8bca-4dbf4203b1f7.png)

![image](https://user-images.githubusercontent.com/61889138/86514568-0e2d7800-be0b-11ea-8a5d-42ac1d5e36f0.png)

![image](https://user-images.githubusercontent.com/61889138/86514632-3ddc8000-be0b-11ea-9bf0-c63d92969155.png)

**Comment by D3nnis3n** [comment]
Only managers are taxed, did you take that into account? Users are not part of the calculation, on purpose.

**Comment by MishkaFur** [comment]
> 
> 
> Only managers are taxed, did you take that into account? Users are not part of the calculation, on purpose.
So shove all your money into a shared account, have none in your account and immune to tax if not a manager?

So a tax all wealth for abandoned tax is impossible unless you manually set the account name of the player to get the money back to govt?

Also wealth says it includes money in the shared bank accounts pro rata so in theory rev has over 12.5k, he was also not getting taxed at all by the tax band law.

**Comment by D3nnis3n** [comment]
The issue is, that there might be people accessing several accounts without actually owning the money - their share shouldn't be taxed. I might also want to give tax exemptions to specific companies - i can only do that when only Managers are counted as being the owners of the accounts, so yes, that's intended.

The abandoned tax is not impossible. Octe didn't own the money on that account, it is owned by rev only. So the money is not abandoned.

Revs account should get taxes if the tax targets his wealth, if it doesn't that's a bug.

**Comment by MishkaFur** [comment]
> 
> Revs account should get taxed if the tax targets his wealth, if it doesn't that's a bug.

I dont believe it does or at least it fails because he doesnt have enough money to pay the tax.

**Comment by D3nnis3n** [comment]
We'd need a reproduction case / screens of that, if possible.

**Comment by johnkslg** [comment]
@beastyn @SlayksWood can you investigate this one and let me know if anything needs to be changed?

**Comment by beastyn** [comment]
Yeap, it does not tax account were you are a sole manager.

So, for now I think we should tax accounts were citizen is only one manager.
Don't touch accounts were citizen is a user or manager with someone else.

**Comment by D3nnis3n** [comment]
It needs to tax accounts with one or several managers, otherwise the tax system is useless as its only one click to circumvent taxes.

**Comment by D3nnis3n** [comment]
@olegshegai 
Logic needs to be fixed so tax calculation and taxing for accounts is splitted correctly between the managers of the accounts. Of course 100% for only a single manager.

**Comment by beastyn** [comment]
@D3nnis3n how to count it? /N where N is managers count&

**Comment by D3nnis3n** [comment]
@beastyn Look at Mishkas screens, John already implemented a logic to split the money over the managers in regards to wealth and taxing. There is the line "x percent are counted as your wealth in the tooltip".

It seems to work for several managers, but not for a single one, so probably just a small logic bug.

But yes, money is split evenly between managers for purposes of wealrh calculation and how mich can be taxed for this person from that account.

**Comment by SlayksWood** [comment]
It works fine for me now. I'll start with an easy example.

- [ ] 1.
- create new server, place capitol, court, mint and bank. 1 player.
- create a new credit in mint and a new bank account. Have 10k Test coin on each account.
![image](https://user-images.githubusercontent.com/45708377/87639622-2f1c9400-c74e-11ea-9ae1-5cd86bd13432.png)
- create law to tax 10% of my wealth. So I should pay (10000+10000)*10/100 = 2000.
![image](https://user-images.githubusercontent.com/45708377/87640019-c41f8d00-c74e-11ea-92e8-35f8e6ba378b.png)
- wait until law will tick. I paid:
![image](https://user-images.githubusercontent.com/45708377/87640134-ee714a80-c74e-11ea-9f68-ad5af2ad7d36.png)
- Seems work, 

- [ ] 2. but we need to add more users. /test makeusers,1
- so Slayks personal Account have 10000, Test user 1 have 10000 and Account 2 have 10000 and have 2 people in managment (slayks and test client 1). We should both pay 1500 Test coin.
![image](https://user-images.githubusercontent.com/45708377/87640797-ecf45200-c74f-11ea-82a1-8a6af884518e.png)
![image](https://user-images.githubusercontent.com/45708377/87640819-f7165080-c74f-11ea-867a-8e01ad4374ea.png)
- wait until law will tick. Seems right again:
![image](https://user-images.githubusercontent.com/45708377/87641027-380e6500-c750-11ea-8c78-31224ced5dcc.png)

- [ ] 3. now move test client 1 to user in account 2:
![image](https://user-images.githubusercontent.com/45708377/87641265-8459a500-c750-11ea-9b03-624ba7b5f540.png)
- made balance for each account = 10000. I should pay 2k, test client 1 should pay 1k:
![image](https://user-images.githubusercontent.com/45708377/87641629-0a75eb80-c751-11ea-932d-8d6139cd042e.png)
 So I checked that it works!

- [ ] 4. Create more complex. Add another 5 users (/test makeusers,5). So I have 6 Users now(with me):
![image](https://user-images.githubusercontent.com/45708377/87641832-545ed180-c751-11ea-962f-a1eb9faab977.png)
- create 6 bank account, All this and personal accounts will have 10000. 
![image](https://user-images.githubusercontent.com/45708377/87642242-ed8de800-c751-11ea-86f5-343c9cf662e9.png)
So when I will change all.
I should pay: 1000 (personal acc) + 1000 (solo manager in 1 acc) + 500 (like 1/2 manager in acc)= 2500
Test client 1: 1000 + 500 = 1500
Test client 2: 1000 + 1000 + 500 = 2500
Test client 3: 1000 + 500 = 1500
Test client 4: 1000 + 500 + 1000 = 2500
Test client 5: 1000 + 500 = 1500
The way I give access  without me: 
1. I add manager and user:
![image](https://user-images.githubusercontent.com/45708377/87642894-d00d4e00-c752-11ea-99e7-8f968bb0d4f6.png)
2. I delete myself:
![image](https://user-images.githubusercontent.com/45708377/87642909-d8658900-c752-11ea-8117-c4db67671266.png)
![image](https://user-images.githubusercontent.com/45708377/87643432-8d984100-c753-11ea-918e-ac582a73ecc3.png)
- wait law tick:
![image](https://user-images.githubusercontent.com/45708377/87643828-05666b80-c754-11ea-981e-87f7744159f0.png)

@MishkaFur You can check it too after update
