### ISSUE TITLE
USER ISSUE: Guest Does not Earn EXP from all Sources

### ISSUE THREAD

**Issue by TaterBoy84** [StrangeLoopGames/EcoIssues#16971]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1: Create a private world.
2: Set collaboration difficulty to 0-3 players.
3: Have a guest join via the Steam friend's list.
4: Set a specialty in a skill such as Hewing.

**Expected behavior:**
The guest player should get exp in a skill they have a star of proficiency in.

**Actual behavior:**
Only the host of the game is getting proficiency exp in every proficient skill, except when it comes to logging, but no exp from hewing is earned by the guest player when they craft Hewn Logs, for example.

**Do you have mods installed? Does issue happen when no mods are installed?:** No mods installed

**Comment by D3nnis3n** [comment]
Is the guest player using a carpentry table? The specialty does not apply to the workbench.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
