### ISSUE TITLE
Client failing to auto-reconnect after server restart

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16973]
This used to work: client would detect disconnected server has returned, it would disconnect and reconnect.
Now it gets stuck here:
![image](https://user-images.githubusercontent.com/3536496/86494597-abfd4600-bd2a-11ea-99df-70306efb87d5.png)

Medium pri because this is important for development iteration

**Comment by Quadbro** [comment]
failed to repro in any way, always connects on server restart... Probably fantom error? Or seems like you used to change a lot on server

**Comment by mirasrael** [comment]
I also have this error often enough (and Swapni today has it). It usually happens after Alt + Shift + R when you was connected to server and made some code changes.

**Comment by redwyre** [comment]
Definately still a problem, the ConnectionUI seems to get stuck in `ConnectState.Connecting` and doesn't update `connectStatus`

**Comment by Quadbro** [comment]
@redwyre Are you talking about auto recconect or manual restart with John's command (Alt + Shift + R) ?

**Comment by Quadbro** [comment]
I have fantom regular connect hangs, and seems liike they are not related to reconnect actions on server restart

**Comment by redwyre** [comment]
Usually first time auto connect for me

**Comment by serpopov** [comment]
It happens when Alt+Tab, but last days it unstucks occasionally for me

**Comment by redwyre** [comment]
Still getting this, with background option on.
Rob also has been getting it

**Comment by mirasrael** [comment]
I'll take care of this, because I have it almost every time.
