### ISSUE TITLE
Ambient sounds stop abruptly when crossing world wrap

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#16980]
https://drive.google.com/file/d/1JZnRruEks7AiiI1Hhsa2NYbSegG6X_5k/view?usp=sharing

Mostly seems to be crickets

**Comment by Quadbro** [comment]
Need to implement custom sound diffussion system near zero coords to resolve this issue, so we can postpone this a bit

**Comment by johnkslg** [comment]
How about duplicating the sound across the border?

**Comment by Quadbro** [comment]
> How about duplicating the sound across the border?

It will cause very weird ear'side switch effects and sounds vill be stronger near world border

**Comment by gzatravkin** [comment]
The same problem as https://github.com/StrangeLoopGames/EcoIssues/issues/21650

**Comment by gzatravkin** [comment]
So after investigation I see that the problem is that position of sfx gameobjects wasn't updating because realted game objects were immediatly deleted after spawning
