### ISSUE TITLE
 [0.9.0 staging-1641] Web election: candidates box improvements

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16989]
1) I can see how I was voting for the candidates
![bandicam 2020-07-06 14-18-37-633](https://user-images.githubusercontent.com/27898520/86578980-1e259300-bf96-11ea-82c8-780aab8a1b74.jpg)

Maybe we can leave candidates in the Ranked box after voting?

2) Can we move ranked box with scrolling? If the list is big we won't see the box for dropping there. Quite inconvenience.
![bandicam 2020-07-06 14-53-21-079](https://user-images.githubusercontent.com/27898520/86581055-fc79db00-bf98-11ea-92a8-d6dae72bf172.jpg)

**Comment by j3fffff** [comment]
User can still rank candidates after election is over
- generate test data
- use swagger to end election
- in previous elections category, you can still rank candidates. should save candidate's rank. this info comes back from the game server.

This is probably similar issue to Anna's #1 issue above.


Anna's #2 issue. its not setup for that. dont have time to add it. most elections are just a few people.
