### ISSUE TITLE
USER ISSUE: Sleeping / Skill Menu Glitch

### ISSUE THREAD

**Issue by ThorloX** [StrangeLoopGames/EcoIssues#16985]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I went to bed, accidently hit Z and the sleeping uncheck boxed disappeared. 
then I disconnected in the hopes of a fix, I got out of the bed, but all the crafting stations were unaccessable.

**Expected behavior:**
That id would have reset itself by dc/ing 

**Actual behavior:**
glitched the whole game and will have to do a roll back from backup

**Do you have mods installed? Does issue happen when no mods are installed?:**
glitched the whole game and will have to do a roll back from backup

**Comment by TwixterZ** [comment]
@ThorloX thanks for raising this up. 

However, i have not been able to reproduce this on latest build, I would like to request more information from you about this issue.
1. Kindly provide us with your complete PC specification including the operating system and its version.
2. Please upload the game logs (Log file - https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file). This will help us further investigate this issue.
3. How frequently do you encounter this issue?
4. If you can reproduce this issue, could you provide us with steps or a recorded video of it? If so, please upload it here.

Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
