### ISSUE TITLE
[0.9.0 staging-1641] Chat name is in several strings

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16987]
Step to reproduce:
- press Enter to add text:
![image](https://user-images.githubusercontent.com/45708377/86572625-d98cfe00-bf7b-11ea-92c6-90f365df5d8b.png)
- Ctrl+V long text:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus feugiat ligula, in ultrices risus iaculis vitae. Nam finibus augue et metus mollis, ut semper dui dapibus. Curabitur faucibus purus id risus porttitor, ut placerat ligula rhoncus. Nunc scelerisque, arcu vel mattis varius, nisl massa tincidunt justo, a porttitor leo nisl varius lectus. Vivamus gravida felis quis nisi malesuada, id pulvinar nisl hendrerit. Nullam molestie non dui et tincidunt. Curabitur luctus dapibus odio, eu hendrerit velit finibus a. Suspendisse sit amet tincidunt odio. Donec pretium, mauris at consectetur porta, magna ligula ullamcorper tortor, eget porta tortor felis condimentum mauris. Curabitur tincidunt dictum nulla, et convallis nisl tincidunt id.
```
![image](https://user-images.githubusercontent.com/45708377/86572693-f4f80900-bf7b-11ea-8de1-538eeae84c32.png)
- press ESC to chat:
![image](https://user-images.githubusercontent.com/45708377/86572759-0ccf8d00-bf7c-11ea-8208-e55fe8f57d36.png)
- press Enter to open chat again. Chat name is in several strings:
![image](https://user-images.githubusercontent.com/45708377/86573010-689a1600-bf7c-11ea-934c-da6c3dd27780.png)

**Comment by MonzUn** [comment]
I have this issue permanently, without entering a long string.
My chat field can be empty and my "General" text is still on two lines.

**Comment by mirasrael** [comment]
@MonzUn do you use English language on the client?

**Comment by MonzUn** [comment]
Actually, I hadn't checked this in Dev-23 and it's no longer the case it seems.
Although this version changed much of how my UI looks so it might be it got fixed due to that.

I do have odd spacing in my chat now though (likely a separate issue from this one, just figured I'd mention it)
This is in 2560 * 1440 but It was the same in 1920 * 1080 as well.
![image](https://user-images.githubusercontent.com/11805935/89519194-43e3c900-d7dc-11ea-94b9-80d17ad27dd6.png)

**Comment by SlayksWood** [comment]
Fixed for me.
@MonzUn Please create an issue if you have your problem in 9.4
closed for now

**Comment by MonzUn** [comment]
Haven't seen this in a long time so it's most likely fixed
