### ISSUE TITLE
Minimap performance problems

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1698]
Cuts frame rate in half, makes everything lag.  Detail slider doesnt seem to be working properly. 

We may need to redesign how this works, considering the webgl minimap is lightning fast and full detail, we may want to sacrifice rendering on the minimap to make it usable.  Perhaps there are other optimizations we can do that avoid that, though.

**Comment by metachronism** [comment]
we should be able to reduce the minimap to one draw call, at the cost of some quality

using vfetch into a heightmap to deform a pre-generated mesh representing the world.  this should work better than the geometry shader for performance

to improve quality you then just increase the # of meshes used, while using batching to reduce draw call count

this also would allow more easily handling worlds that vary significantly in size while maintaining the same perf

**Comment by metachronism** [comment]
pretty sure sean has fixed this.
