### ISSUE TITLE
[0.9.0 staging-1641] Economy viewer: need some fixes here and there

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16991]
1) Contracts tab
Distance is on the Currency column
2) Contracts tab:
Hover over currency - it will open contract tooltip, not currency tooltip (seems like line has one tooltip for contract)
3) Public crafting station won;t open currency tooltip at all
![bandicam 2020-07-06 17-23-25-607](https://user-images.githubusercontent.com/27898520/86594598-bd578400-bfb0-11ea-9ca4-12d56691e0d1.jpg)

**Comment by SlayksWood** [comment]
- [ ] 1. point 1 still an issue:
![image](https://user-images.githubusercontent.com/45708377/87763656-d0bee680-c81d-11ea-88f1-cce5c003b2da.png)

- [ ] 2. I can see contract tooltip only by contract icon. Make  by contract name too or better 1 tooltip  by full string Name:
![image](https://user-images.githubusercontent.com/45708377/87763989-5478d300-c81e-11ea-9653-77e2add7eaee.png)

**Comment by SlayksWood** [comment]
So. I still have tooltip only mouseover icon:
![image](https://user-images.githubusercontent.com/45708377/88918422-147c0c00-d272-11ea-81a4-b46d19d0835a.png)
But if I mouse over here:
![image](https://user-images.githubusercontent.com/45708377/88918482-2c539000-d272-11ea-8676-ea1176315043.png)
I don't have tooltip, but if I click here it will open Contract for me.
