### ISSUE TITLE
Truck Needs Normal and Metalness Maps

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17009]
![image](https://user-images.githubusercontent.com/14983165/86639234-74da9f00-bf8d-11ea-9318-22a51876caeb.png)
Currently missing them, thus everything looks a little faded and glossy on the truck.

**Comment by beastyn** [comment]
Hmmm, I think body looks little plastic.
But this discs are just nooooice.
![bandicam 2020-07-27 17-42-54-529](https://user-images.githubusercontent.com/27898520/88542923-a3014b00-d030-11ea-8b2a-0eb78573154a.jpg)
