### ISSUE TITLE
Staging builds regular cleanup

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17007]
simon says: AWS S3 bucket "eco-releases" is ~745GB and steadily growing
I suggest moving staging builds to a separate bucket that is routinely cleaned (eg monthly removing builds 2 months old)

**Comment by redwyre** [comment]
It's true, I did say that.

Let me know when you setup a new bucket and I'll start directing new staging builds there.

**Comment by j3fffff** [comment]
Staging bucket is: arn:aws:s3:::eco-releases-staging

Note: 
I removed all the old staging builds.
Also ~50 old test worlds
and deleted ~400gigs of old cloud world saves

Going to see how that effects billing next cycle

**Comment by j3fffff** [comment]
@mirasrael , do you know where the ECS api is getting its server versions list from? 
I removed unneeded staging builds from S3, but they still show up in the ecs api.
And we will be separating staging builds into its own s3 bucket. Maybe you could help update the api to check in this bucket for staging builds: arn:aws:s3:::eco-releases-staging

**Comment by mirasrael** [comment]
All versions parsed from tags of server images on Docker Hub: https://hub.docker.com/r/strangeloopgames/eco-game-server/tags

**Comment by mirasrael** [comment]
EGS API doesn't use S3 bucket with releases in any way

**Comment by denysaw** [comment]
Changed download links on both *lands. Probably you could close the issue

**Comment by j3fffff** [comment]
@redwyre did you update build process to send staging to the new bucket?

**Comment by redwyre** [comment]
change for new bucket going in today

**Comment by redwyre** [comment]
develop and staging builds are now going into the new bucket
