### ISSUE TITLE
CW: Remove old world saves

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17004]
Setup cron job that removes unused world saves that are over a month old.

You can find unused worlds from this api query (should be available in postman):
/storage/unused

**Comment by j3fffff** [comment]
hosted-worlds-backups-eu-central-1
hosted-worlds-backups-us-west-1

**Comment by denysaw** [comment]
Done (not yet merged to prod though), but after deploy it'll be needed to add it to the cronjob, this method: `cron/removeOldWorldSaves`
