### ISSUE TITLE
Town Hall 5.6

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#1700]
![2017-06-21](https://user-images.githubusercontent.com/29607241/27393480-6962c27e-5677-11e7-904e-74b055e2a951.png)
Town Hall's Skin is not showing, instead, it is default skin of a white box.

**Comment by MarjieAVolk** [comment]
Yep, we've still got placeholder "art" on a few objects.  Coming soon!

**Comment by metachronism** [comment]
actually, there is table art for townhall, looks like its using the wrong model atm

**Comment by keegan-o** [comment]
The art is just placeholder, so no real art yet.
