### ISSUE TITLE
 [0.9.0 staging-1644] Civics: timer is overlapped till update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17019]
1) Create a law
2) Pick Global Timer in the trigger section
![bandicam 2020-07-07 15-59-46-062](https://user-images.githubusercontent.com/27898520/86771288-6498f180-c06b-11ea-969c-b6df42690b68.jpg)
3) It will be fixed if you reopen UI or add a condition for example.

**Comment by SlayksWood** [comment]
This is global problem for many UIs. It started after adding pooling. I assume it will be one solution for all. For example Work party:
https://drive.google.com/file/d/1di3G8qKeyGT0KvVk9-EG9bFokWoOxOgA/view?usp=sharing

**Comment by SlayksWood** [comment]
now we have a big space till update:
![image](https://user-images.githubusercontent.com/45708377/87408938-e4274300-c5cc-11ea-94a1-c136e64c6832.png)
after update:
![image](https://user-images.githubusercontent.com/45708377/87408966-f0130500-c5cc-11ea-99c1-870d90c3a535.png)
