### ISSUE TITLE
Elections: district map not displaying

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17028]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/fe45d316-2a2e-4645-bc0b-f207faee282a)

**Comment by j3fffff** [comment]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/b062cfde-aeb5-4d5d-a1e2-7c2f437b8c0f)

**Comment by j3fffff** [comment]
fixed itself when i reset world save.

**Comment by j3fffff** [comment]
nevermind it came back! seems to work with a fresh server using generatetestdata 
after a day it stopped working.

**Comment by j3fffff** [comment]
I'm only seeing one map. I'm guessing you removed it thinking it was a mistake. but its supposed to have 2 maps, so user can compare the old and new districts.

**Comment by denysaw** [comment]
@j3fffff Maps were working perfectly before. But if something in html changed from that time, it could break everything.
When it's Adding District, 1 map is totally correct behavior. Only when Modify District, then should be two.

**Comment by denysaw** [comment]
@j3fffff Explain, please, current problem. One map in `Add District` is ok.

**Comment by j3fffff** [comment]
ok, the issue is the map is not displaying correctly. as in the screen shot.

i can see the button to change it to 2d or 3d. but map is not displayed.

seems it works on new server. but when i checked later it didnt work. maybe try turning server on and off.

**Comment by denysaw** [comment]
@gzatravkin Grigory, could you take a look, please, when you have a time. Seems something with map data after time passed.

**Comment by gzatravkin** [comment]
The only way I was able to reproduce it is by unathorized user (but still there are no error from console)

I tried: 
Spawngov, create election to modificate and to create district maps
GenerateTestData

So here fix for unathorized users.

If there are still some other error please attach a server data from server with election to reproduce it.

**Comment by beastyn** [comment]
Did not have this, but @j3fffff reopen please if its still an issue for you.
