### ISSUE TITLE
[0.9.0 staging-1644] A lot of OKbox about notification of inability to open the skills window

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17020]
Step to reproduce:
- have active any tutorial:
![image](https://user-images.githubusercontent.com/45708377/86779027-c190a980-c063-11ea-9dcd-7015781da783.png)
- press Z 10 times:
![image](https://user-images.githubusercontent.com/45708377/86779070-ca817b00-c063-11ea-91ec-2cb13c4d72a6.png)
 - I have 10 OkBox now. It should prevent to open second okbox if i have another one.

**Comment by TwixterZ** [comment]
on 9.3.0 staging 1945 - issue persist
