### ISSUE TITLE
[0.9.0 staging-1644] Wrong tooltip for Experience bar in Skill window.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17022]
Step to reproduce:
- open skill window.
- select learned skill but without star.
![image](https://user-images.githubusercontent.com/45708377/86782465-c2c3d580-c067-11ea-919a-f83dffd557a6.png)
- mouseover EXP bar, I have "not a number" in tooltip:
![image](https://user-images.githubusercontent.com/45708377/86782124-652f8900-c067-11ea-9351-079b8f846a30.png)
- but this tooltip very strange too. I don't need any exp to level-up. I just need to spend star. So I assume we should to change exp bar tooltip for specialty 0 level. Something like.
"You must specialize in {specialtyname} to level-up "

**Comment by Daniel-Magulado** [comment]
Also happening on 0.9.2.4 Release-162 as reported in this ticket #20766.

![not a number](https://user-images.githubusercontent.com/77248866/109389201-77d43680-7946-11eb-84bc-4fa404d230e2.jpg)

**Comment by Ry4ndrew** [comment]
Closed this issue as it is fixed in the current staging [0.9.4 Staging-2030].
