### ISSUE TITLE
[5.6] Cannot gather any plants

### ISSUE THREAD

**Issue by Mosseman** [StrangeLoopGames/EcoIssues#1703]
No plants can be gathered either by pressing E or using a scythe. Plant model disappears from world, but no plant is added to inventory.

Edit: In addition, freshly killed animals report that carcass has already been harvested, resulting on no meat being available.

Game is currently unplayable.

**Comment by craig-jong** [comment]
If you send your save file to craig@strangeloopgames.com, I can take a look to see whats up. This hasn't happened to any of our test servers, so having something to check out would be helpful.

**Comment by Mosseman** [comment]
Hi Craig, came back to give an update. Unfortunately, I no longer have the affected save files.

I think I may have suffered from a dodgy installation. I'm hosted on PingPerfect, was running 5.5, then updated to 5.6 shortly after its release. The issue only impacted my server so after playing around with it, restarting server, regenerating server, allowing server to run many minutes (1hr+ after world gen) I was still getting the same issue. I eventually did a full reinstall of the server and it now works fine.
