### ISSUE TITLE
DataGraphs: Add Units to `/api/v1/elections` response

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#17039]
In `world:3000/api/v1/elections` (both `returnActive` true/false) response, return not only 
`response.Comments[i].Graph.Keys[j][0]`, but also `Units`.
Suggest nesting:
```
`Comments[].Graph.Keys[] = [
    'DisplayName': 'Agave Species', 
    'Units': 'Organisms'
];
````

Right now it's string inside of an array:
![image](https://user-images.githubusercontent.com/5720101/86961347-5e853c80-c161-11ea-94ba-782e6cd3f8cf.png)

It's everything needed for determination chart type (`spline`/`column`/`dotted`) for already posted comments:
https://github.com/StrangeLoopGames/EcoIssues/issues/16960

Putting priority same as this task, which is rely on it.

**Comment by gzatravkin** [comment]
Speaked by DM, but duplicating here.

Looks like it can be managed at JS side.

Graph contains what JS sents to endpoint addcomment
![image](https://user-images.githubusercontent.com/53317567/86963946-b610b180-c13b-11ea-9049-7f325640876e.png)

And at moment of sent it have access to all necesarry data. So it should be possible to just add Units as second element of array here

**Comment by denysaw** [comment]
@WeaselDog I wanted to close after PR merge, yep

**Comment by denysaw** [comment]
@gzatravkin Thanx, for pointing to the correct direction ;)
