### ISSUE TITLE
USER ISSUE: Server doesnt exist

### ISSUE THREAD

**Issue by KageCooke** [StrangeLoopGames/EcoIssues#17041]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Loose internet connection
Attempt to rejoin server

**Expected behavior:**
Joined the server

**Actual behavior:**
The following error message popped up:
Could not join the server. It either doesnt exist or isnt on the master server.
<size=150%>Connection Failed</size>

The requested server was not found. It either doesn't exist, or is not registered on the master server.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
Could not join the server. It either doesnt exist or isnt on the master server.
<size=150%>Connection Failed</size>

The requested server was not found. It either doesn't exist, or is not registered on the master server.
```

**Comment by SlayksWood** [comment]
@KageCooke Thank you for the report and sorry for waiting.
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
