### ISSUE TITLE
[5.6] Cannot remove block stacks from chest

### ISSUE THREAD

**Issue by MeirionHughes** [StrangeLoopGames/EcoIssues#1704]
After the upgrade I am unable to remove the blocks (10) of dirt/stone/icon from chests. Keeps saying it can only be carried -- which I'm trying to do.

**Comment by Mosseman** [comment]
Most likely a bug as the system migrates from heavy items (such as stone) being stored in chests to them stored in stockpiles. Looks like you'll have to give up on the affected chests/world.

**Comment by MarjieAVolk** [comment]
Ah, yeah it probably won't let you unless you somehow manage to move all carried items out of the chest all at once.  If you start a fresh world, this won't be a problem.  Sorry about that!
