### ISSUE TITLE
[0.9.0 staging-1649] Remove text before the quote

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17047]
Still an issue:
> ![image](https://user-images.githubusercontent.com/3536496/85063264-bc27f980-b15e-11ea-8e4c-3608bbb6aff9.png)
> 
> * [ ]  4. Remove text before the quote on all pillars. It should always be 'image', 'quote' then 'text'.
![image](https://user-images.githubusercontent.com/45708377/87013058-c45ddc80-c1d2-11ea-97ba-9e206f384188.png)

**Comment by WeaselDog** [comment]
Pushing to next week because it is blocked

**Comment by WeaselDog** [comment]
The bulk of this was fixed by the Ecopedia localization fix.
