### ISSUE TITLE
 [0.9.0 staging-1649] Civics and pooling? Lists won't work after cach disabling

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17052]
1) Create a new world
2) Place capitol, ratify, place a court
3) Open a law UI, check that lists are working
4) /toggleuicache (ui cache is disabled)

After that this error has began to spam.
```
NullReferenceException: Object reference not set to an instance of an object.
  at UpdateManager.DoUpdates (System.Collections.Generic.Dictionary`2[TKey,TValue] dict, System.Boolean updateLate) [0x00000] in <00000000000000000000000000000000>:0 
```
And lists won't work no more.

![bandicam 2020-07-09 17-23-31-082](https://user-images.githubusercontent.com/27898520/87039851-36e9af00-c209-11ea-899c-e8b724d07a95.jpg)

It's not happening all the time.

**Comment by SlayksWood** [comment]
I have this error without /toggleuicache too.

**Comment by mirasrael** [comment]
Seems related to pooling. It is actually very hard to reproduce, so probably will be auto fixed when all pooling issues resolved.
