### ISSUE TITLE
Escape closes both error window and window behind it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17055]
![image](https://user-images.githubusercontent.com/3536496/87091657-eb2a0c00-c1ee-11ea-97df-56f933d6c6c8.png)
Should only close the error/status display, if its open
Make this an intrinsic part of the UI system, sending to the top on the stack, rather than 'if error box' etc all over.

**Comment by gzatravkin** [comment]
It was discussed before.
Seems like for users it's more comfortable to have "esc closes ui window".

Personally I would preffer to close with esc UI windows too. Otherway you can missclick esc: try to escape error message, but press after it goes by itself, and the window will be closed without unwantable. Anyway with UI windows you have a cursor and you should be able to close messages by clicking them.

https://github.com/StrangeLoopGames/EcoIssues/issues/14977
https://github.com/StrangeLoopGames/EcoIssues/issues/15123

Are you sure you want to have "Should only close the error/status display, if its open"?

**Comment by johnkslg** [comment]
Hmmmm
How about you make the panel highlight when you mouse over it so you know clicking will remove it and we call it good
Also while youre in there can you reduce the text size by about 25%?  It's too big when there are long law strings in there.

**Comment by SlayksWood** [comment]
- [ ] 1. highlight is almost invisible. without highlight/ with:
![image](https://user-images.githubusercontent.com/45708377/88024028-bac16680-cb3a-11ea-9a6a-6765d6b57b22.png)

- [ ] 2. I still can't close only notification window.

**Comment by SlayksWood** [comment]
I would make them auto customizable in width due to such laws with max and min width like OkBox.
> Notifications from law effects on actions are blocking screen on every action with huge bloated notification windows as seen below.
> Recommendations, move them into notification bell system to remove spam in front of the user and leaves a bad experience.
> ![Screenshot_244](https://user-images.githubusercontent.com/24981362/88331326-15221900-cd2d-11ea-9d4e-028f2bdaaf1f.jpg)

**Comment by Fnunzi** [comment]
Want to add this in here too. "they also get in the way when adding work.  i know i can move the screen that the work button is on but why should we have to do that..   should be a way to disable the messages or move them"  The message of how much work you added gets in front of the actual add work button on crafting screen.
