### ISSUE TITLE
Law wasnt displaying status when it paid user

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17058]
![image](https://user-images.githubusercontent.com/3536496/87093230-b8cdde00-c1f1-11ea-9377-56017ad18e21.png)
This law pays the user when they place a road, and taxes them when it gets picked up. Taxing displayed a status:
![image](https://user-images.githubusercontent.com/3536496/87093306-d7cc7000-c1f1-11ea-9bd9-504f2cbd9dec.png)

But paying showed no such status. 
All legal actions should display a status to the user, check for problems with others too.

**Comment by SlayksWood** [comment]
dup #17045
