### ISSUE TITLE
JsonSerializationException

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17065]
> [17:21:13.598] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
> [17:21:13.613] [1] [ Info] [Eco] Eco Server 0.8.3.3 beta
>  
> [17:21:13.749] [1] [ Info] [Eco] Server Initialization...  
> [17:21:13.749] [1] [ Info] [Eco] Starting LocalizationPlugin...  
> [17:21:14.023] [1] [ Info] [Eco] Starting ModKitPlugin...  
> [17:21:14.023] [1] [ Info] [Eco] Loading mods...  
> [17:21:14.088] [1] [ Info] [Eco] Compiling mods...  
> [17:21:15.737] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
>  
> [17:21:15.737] [1] [ Info] [Eco] Loading mods finished in 1 728,1ms
>  
> [17:21:15.753] [1] [ Info] [Eco] Starting NetworkManager...  
> [17:21:15.753] [9] [ Info] [Eco] Initializing Simulation Types...  
> [17:21:15.808] [11] [ Info] [Eco] Starting WorldGeneratorPlugin...  
> [17:21:15.824] [5] [ Info] [Eco] Starting GameplayStatsPlugin...  
> [17:21:15.844] [7] [ Info] [Eco] Starting BackupPlugin...  
> [17:21:15.852] [7] [ Info] [Eco] Starting StorageManager...  
> [17:21:16.480] [9] [ Info] [Eco] Initializing items...  
> [17:21:18.227] [7] [ Info] [Eco] Starting PausePlugin...  
> [17:21:19.203] [9] [ Info] [Eco] Initializing skills...  
> [17:21:19.263] [7] [ Info] [Eco] Starting StatDatabase...  
> [17:21:19.263] [5] [ Info] [Eco] Starting WorldPlugin...  
> [17:21:19.299] [5] [ Info] [Eco] Loading World...  
> [17:21:19.920] [5] [ Info] [Eco] Initializing world...  
> [17:21:20.677] [5] [ Info] [Eco] Starting TimePlugin...  
> [17:21:20.677] [5] [ Info] [Eco] Loading Time...  
> [17:21:20.677] [5] [ Info] [Eco] Starting ReputationPlugin...  
> [17:21:20.677] [5] [ Info] [Eco] Loading Reputation...  
> [17:21:20.677] [5] [ Info] [Eco] Starting PlayerHousingManager...  
> [17:21:20.677] [5] [ Info] [Eco] Starting UserManager...  
> [17:21:20.704] [1] [ Info] [Eco] Server Initialization finished in 6 954,4ms
>  
> [17:21:20.711] [1] [ Info] [Eco] Failed to load server, Exception was Exception: JsonSerializationException
> Message:Could not load assembly 'System.Private.CoreLib'.
> Source:Newtonsoft.Json
> 
> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'System.Private.CoreLib'.
>    at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)

User is using Windows.

**Comment by SlayksWood** [comment]
@D3nnis3n Can user provide save files?

**Comment by D3nnis3n** [comment]
https://drive.google.com/drive/folders/1y-8UD28-r9TqwOVVt7Z6lg2KaD1kXzbu

The old ones are the ones the person tried to load first, the 8.3.3-test one is the one i requested to be created newly (no DB was generated).

**Comment by D3nnis3n** [comment]
Person forgot one of the steps, deleting the old files before reinstalling. Working now.
