### ISSUE TITLE
Selecting citizen timer creates a broken view

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17061]
![image](https://user-images.githubusercontent.com/3536496/87094448-c2584580-c1f3-11ea-85b7-9f3ac0c90023.png)
Fixes if you minimize/reopen:
![image](https://user-images.githubusercontent.com/3536496/87094495-d56b1580-c1f3-11ea-9b7a-6cc16009751a.png)

**Comment by SlayksWood** [comment]
dup #17019
