### ISSUE TITLE
USER ISSUE: I'm in the sky...

### ISSUE THREAD

**Issue by JuGre** [StrangeLoopGames/EcoIssues#17067]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I was mining, everything went black... I saw on the minimap that I was in the sky (stationnary) and the markers indicated I was around 1500 meters away... I disconnected, restarted the server, still the same, maybe the problem is with the server provider, I'll contact them as well...

**Expected behavior:**
I should have been on the ground... :-)

**Actual behavior:**
The following error message popped up:
No error message, only floating in the dark... 

**Do you have mods installed? Yes, clean smelting
Does issue happen when no mods are installed?: yes

**Comment by SlayksWood** [comment]
@JuGre Thank you for the report. Can you provide some information?
1. Are you playing on your own server? 
Please provide save files if possibly. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
2. Provide some screenshots or coordinates.
3. Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
4. Do you have Firewall or Antivirus enabled?
5. Which kind of internet connection are you using?
6. Please provide your PC specification (include Operating System).

**Comment by JuGre** [comment]
Thank you for your answer!
I will send you all the infos (but not this morning, probably more
tomorrow) but maybe I should wait for the answer from the server provider
(I don't want you to work for nothing...) If ever they solve it, I could
send you the infos and what they did (if they tell me) if you want to keep
a record of it...?

Have a nice day

Julie

Le ven. 10 juill. 2020, à 05 h 07, Kirill <notifications@github.com> a
écrit :

**Comment by JuGre** [comment]
Hi, after communicating with Ping Perfect and trying a few things, the
conclusion is that I'll use a backup and restart from there... nothing
worked, do you still want the infos you requested in your email or not
necessary?

**Comment by D3nnis3n** [comment]
If you can still provide the save-file with the issue, yes. We need that to investigate the issue.

**Comment by JuGre** [comment]
Hi!

Finally, even the backup option didn't work, I restarted a new world from
scratch, I'll try to see if they deleted the save-file with the problem in
the process of erasing everything and I'll send it to you if possible
(probably not today, busy day...)

Have a nice day!

**Comment by JuGre** [comment]
Hi,

I'm sorry, I went on Ping Perfect's website, it seems all the previous
backups have been deleted or I can't find them... so you may close this
ticket, next time (if there is a next time) I will make sure to gather all
the infos before restarting everything...

Thanks for your attention, have a nice day!

Julie
