### ISSUE TITLE
[5.6] permissions issue. Theft issue

### ISSUE THREAD

**Issue by EvilCanadian2** [StrangeLoopGames/EcoIssues#1706]
After some brief testing my friend and I noticed a major flaw. I had access to his research table via whitelist and I went to the storage tab to move items into my inventory to move to the research table. The items in question was wood, I could not access his stockpile directly but I could move items from it's storage page to my inventory when accessed through a research table.

I did some testing with his store, it must be set to public or white list with the people you wish to sell to in order to trade. I could access his store chest via the storage tab and take things. This is a huge issue from our perspective. I'm going to try to do this with a 3rd party and verify.

I confirmed with some random person's store. I was able to access their storage and remove items. (don't worry I put them back)

After a bit more testing we have discovered that if the store is the only thing that is public (or whitelisted with my name) there is no issue, if I am allowed access to the research table (public or whitelisted with my name added) I could get into his storage containers.

**Comment by MarjieAVolk** [comment]
Okay this is rather complicated, so I just want to make sure I understand your report.

The behavior you describe on the store sounds correct - changing the auth settings on the store affects who has access to purchase from the store.

So the bug you are reporting is this: Your friend has a research table and a stockpile.  They gave you auth access to the research table, but not to the stockpile.  When you go to your friend's stockpile, it won't let you hit 'E' to access it.  But when you go to your friend's research table, you can see the stockpile in the storage tab and take items out of it.  Is that correct?

**Comment by EvilCanadian2** [comment]
Yes that sounds about right. Although it isn't exclusive to the stockpile, any container I could pull from. Also if I accessed his store I could get his items because I could get them through the research table.

**Comment by MarjieAVolk** [comment]
Okay just to double check - are the settings on the research table inherited from the deed?  If so, when your friend adds you to the research table, they may also be adding you to the deed without realizing it

**Comment by EvilCanadian2** [comment]
He took me off everything and there was no issues, he then make his research table public and I could take from the containers.

He then changed it to whitelist and added me, I could access his containers here too.
At no point could I go to the stockpile and press E.

After talking it through with someone else on our server it may have been a server issue as there were other problems that got fixed by restarting the server (like nobody getting any seeds from a  tree)

**Comment by MarjieAVolk** [comment]
Okay, that does sound like a bug, thanks for clarifying!  I'll look into it.

**Comment by MarjieAVolk** [comment]
Wait I think I have a theory - had your friend recently removed you from the deed and/or storage auth?
