### ISSUE TITLE
Elections: heat map needs color key

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17068]

**Comment by j3fffff** [comment]
@Quadbro @johnkslg 
Anyone know what the colors correspond to on heat map?
Is it this?
dark purple ---  red ---- yellow ------ white
low--------------------------------------high

**Comment by redwyre** [comment]
![image](https://user-images.githubusercontent.com/431728/87449654-cd223880-c640-11ea-8f27-367575d390e2.png)

**Comment by j3fffff** [comment]
added to develop.
