### ISSUE TITLE
Server exception at moment of selecting graph data with localization

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#17064]
Steps to reproduce:
-Put server on not english language (russian by example).
-Restart server
-Open server page, http://127.0.0.1:3001/
-Select Выборные Должности

It will throw exception (because of passing translated data to server instead of key).
It should pass not localizated key which is sent in treelist (where are DisplayName and Name)

![image](https://user-images.githubusercontent.com/53317567/87101304-25ae9b80-c225-11ea-99c0-8591806ffb0d.png)

**Comment by denysaw** [comment]
That's what I was talking about. DataGraphs localization is not a single step thing...

**Comment by denysaw** [comment]
@gzatravkin Grigory, so it's fixed in PR, right? Can I un-assign and put fixed label then?
