### ISSUE TITLE
Can't interact with Elections webpage, unless logged into game.

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17075]
User is only able to vote and comment on elections page when their client is logged into game server.
If user leaves the game server, they can no longer interact with election page.

Elections is on a website so users and teachers can interact with elections quickly and easily from a website.

So, on game server's api auth check, 
even if user is not logged into the game server, 
but does have the correct auth, 
then let them vote, comment and interact with the website.

**Comment by redwyre** [comment]
Are you saying something like keep the auth token in the browser for use later? If you just visit the webpage directly there's currently no way to get a token outside of launching it from the game, though adding openid support (it's on the backlog) would allow us to get a token via the web without the game.

**Comment by j3fffff** [comment]
I do want to add a login system via the browser. made a seperate github task for that.

but this issue, is just to allow website use after leaving game.
So user logs into game, 
goes to elections webpage
closes client
still on webpage and using it

the token should still be the same in this case. So i think game server api is not only checking token, but requiring user to be ingame currently.

**Comment by gzatravkin** [comment]
CNR. Tried to vote on white tigre, works fine even after shutdown of steam. 
QA any thoughts?
