### ISSUE TITLE
Kiln Placement

### ISSUE THREAD

**Issue by CaitEco** [StrangeLoopGames/EcoIssues#1707]
Kiln requires 32 Mortared Stoned. Room has 32 Mortared stone but reads 1. 
-Workaround add 34 mortared stone to room and it will now read 32.
![kiln](https://user-images.githubusercontent.com/29618526/27415450-a56c6cd4-56cc-11e7-8471-843d55407e35.png)

**Comment by craig-jong** [comment]
Are you counting diagonals as part of the room? Diagonal detection is currently a bit buggy - I'll look into this.

**Comment by craig-jong** [comment]
Updates to rooms should fix this.
