### ISSUE TITLE
USER ISSUE: cant open world after chrash

### ISSUE THREAD

**Issue by YoutuberNL300** [StrangeLoopGames/EcoIssues#17087]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
game chrashed after loading(at something with plants)
now when i whant to open this world it says: conection falure

**Expected behavior:**
staterd

**Actual behavior:**
The following error message popped up:
conection falure
Failed to establish connection - no response from remote host
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
conection falure
Failed to establish connection - no response from remote host
```

**Comment by YoutuberNL300** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/8302
this didn't work

**Comment by SlayksWood** [comment]
@YoutuberNL300 Thank your for the report.
Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
