### ISSUE TITLE
Anti aliasing not working.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17081]
Off:
![image](https://user-images.githubusercontent.com/3536496/87230490-4a119180-c365-11ea-9c13-d558d3668fef.png)

High:
![image](https://user-images.githubusercontent.com/3536496/87230496-572e8080-c365-11ea-865e-074460d00229.png)

Some difference but seems like the bulk of jaggies still there. I think something is wrong.

**Comment by redwyre** [comment]
It's working, but it's not perfect. I tried FXAA which actually seems to work better for the gold bars but it seems a little blurry instead.

**Comment by redwyre** [comment]
Actually, this is more a texture or texture filtering issue, those bars are flat and normal mapped. Would be worth smoothing the indent a bit in the normal map so it's not such a harsh change in lighting.
![image](https://user-images.githubusercontent.com/431728/87334438-fc25a500-c581-11ea-88bc-4ae33de8d4a2.png)

**Comment by redwyre** [comment]
@MilenkoTunjic can you make the normalmap a bit more rounded on the edge?

**Comment by MilenkoTunjic** [comment]
sure

**Comment by MilenkoTunjic** [comment]
Normal map has been fixed and checked in
