### ISSUE TITLE
[5.6] Full Chest, Causes Campfire to input into stockpile(food items) in which halts other production blocks

### ISSUE THREAD

**Issue by evil719** [StrangeLoopGames/EcoIssues#1708]
Basically, cook a lot of meals, forget to add more chest to campfire, campfire moves the cooked item to a linked stockpile(easily solved there) said linked stockpile can no longer accept other items due to food item being placed int it.

**Comment by pamduncan** [comment]
Appears that when stockpiles are getting inventory from a cookfire/stove/bakery they cannot take carry items or items from other tables (like the stockpile does when there is no cookfire/stove/bakery feeding it inventory) , so production is blocked - not sure if this is intended for an issue with the cooking process

**Comment by MarjieAVolk** [comment]
Haven't been able to reproduce this issue yet

**Comment by MarjieAVolk** [comment]
Closing as duplicate of StrangeLoopGames/EcoIssues#1729 -- we got a bunch of reports of this problem
