### ISSUE TITLE
[0.9.0 staging-1655] Incorrect bank accounts selection for Civics

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17085]
- [ ] 1. So I should have ability to use Treasury without access for every things when we have voiting system. People will see it and vote yes/no. I can't use it in Census right now:
![image](https://user-images.githubusercontent.com/45708377/87283494-056d2e00-c4fe-11ea-8861-2c7a64ddd049.png)
But I shouldn't have ability to use Treasury for Wages in Registrar.

- [ ] 2. I can't use Personal accounts in law:
![image](https://user-images.githubusercontent.com/45708377/87289634-91368880-c505-11ea-98a0-478018246fa9.png)

**Comment by olegshegai** [comment]
It's intended behaviour for `Tax` and `Pay` legal actions:
![image](https://user-images.githubusercontent.com/56091594/88396389-23267700-cdcb-11ea-882c-8b6e2200a561.png)
