### ISSUE TITLE
Items movement in tutorial

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17080]
(In issue - provide too many negative feedback)
e.g.
https://discordapp.com/channels/254025510651297802/456533794657271819/731219918820868157
>I find it very annoying to move stuff. I feel like playing drag n drop simulator. To move stuff I need to drag and drop so many individual icons. Don't know any other game that feels so complicated in that regard.

About shift+drag, control+drag, alt+click, etc,

**Comment by D3nnis3n** [comment]
Yeh, those shortcuts really need to be explained somewhere, even if it's a list in the key settings.
We still have developers not knowing these!

**Comment by elfl0rd** [comment]
yea, maybe something like "controls" page in ecopedia?

**Comment by SlayksWood** [comment]
shift/control/ shift+control

**Comment by johnkslg** [comment]
This can appear in the tool tip on the item when its in another storage.
Shift-click and drag to X
Ctrl-click and drag to Y
