### ISSUE TITLE
Multiple reports of Creating laws causing server disconnects/crashes

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#1709]
We have had multiple people reporting that creating Laws and or the violation of a law that is in place is causing disconnects and/or crashing on servers.

**Comment by chrisbraidsw** [comment]
Defect originally observed: Staging Alpha 5.6 #2363f661
Defect last found: Alpha 5.6

64-bit Client used for all reported instances.
Client side crashes and an eventual Server side crash.

Description of issue:
Laws proposed restricting the number of Wolves, Elk, Foxes and Bison to 5 kills per player per day (1 for Wolves).
While being voted on/in proposed state all players were able to kill animals as expected.
Law was made active and as soon as the first player tried to kill a Wolf his client crashed to server selection with error message:
Connection Failed
Caught exception: Exception has been thrown by the target of an invocation

Another player reported the same issue.
Other players are able to attack the animals and see the orange chat informing them the law is active and they cannot kill any more animals, the law name is shown.

Pastebin for the server crashlog: https://pastebin.com/1KwEj7Rq

**Comment by SeanAtr0n** [comment]
confirmed this happens on a fresh server, looks related to some refactoring

**Comment by MarjieAVolk** [comment]
IDK what got refactored exactly, but I think I found the issue (crashlog message was helpful) - just gotta test it out
