### ISSUE TITLE
[0.9.0 staging-1661] Spam NullReferenceException after collect item

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17107]
Step to reproduce:
- place craft station (Camprire) and add fuel. Don't place any stockpile or don't link it.
- start order, add resources and labor:
![image](https://user-images.githubusercontent.com/45708377/87424936-894e1580-c5e5-11ea-8af9-5d3374a438b3.png)
- wait until order will wait. Press collect:
![image](https://user-images.githubusercontent.com/45708377/87425094-bd293b00-c5e5-11ea-8425-6e85b3543747.png)
- I have a lot of exceptions in log:
```
NullReferenceException: Object reference not set to an instance of an object.
  at WorldMarker.UpdateMarker (System.Boolean& positionChanged) [0x00000] in <00000000000000000000000000000000>:0 
  at WorldMarkerManager.LateUpdate () [0x00000] in <00000000000000000000000000000000>:0 
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4918745/Player.log)

P.S. it happens always when craft end

**Comment by serpopov** [comment]
Thats not reproduced on staging, only in current Steam build
