### ISSUE TITLE
[0.9.0 staging-1659] Buttons Copy/Delete local world can disappear

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17103]
Step to reproduce:
- start game, press Your Worlds:
![image](https://user-images.githubusercontent.com/45708377/87394084-e501aa00-c5b7-11ea-9590-7c75545d1cd1.png)
- I have this buttons and I have auto-selected first local world, but it seems a little illogical now when we replaced it. So we need to delete autoselecting at all or change it to the first world in the first tab (in my case server Slayks in Favorite)
- select another world in non-local worlds tab:
![image](https://user-images.githubusercontent.com/45708377/87394409-6e18e100-c5b8-11ea-8072-2f1687f01549.png)
- select any local world now, buttons Copy/Delete has disappeared
![image](https://user-images.githubusercontent.com/45708377/87394467-7f61ed80-c5b8-11ea-9cc9-2774d98820c2.png)

**Comment by beastyn** [comment]
Can we change default selection?
"I have this buttons and I have auto-selected first local world, but it seems a little illogical now when we replaced it. So we need to delete autoselecting at all or change it to the first world in the first tab (in my case server Slayks in Favorite)"
