### ISSUE TITLE
[0.9.0 staging-1658] ECO news is missing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17102]
Seems only in build:
![image](https://user-images.githubusercontent.com/45708377/87388531-b1218700-c5ad-11ea-964f-47d99e84a4fe.png)

**Comment by SlayksWood** [comment]
I don't have news if I start client from steam. Start from local folder:
![image](https://user-images.githubusercontent.com/45708377/87406217-1767d300-c5c9-11ea-96f1-bc8783687ddd.png)

**Comment by gzatravkin** [comment]
Looks like news service are not working with steam client. 
This is format of token "14000000742AB3752C16A1199741EB3C010010011D641B5F180000000100000002000000B7E54C877FF4D52DA02A0F0003000000B800000038000000040000009741EB3C0100100166D5050003A0E5B5A800A8C0000000000F171B5F8FC6365F0100F1170100010006490B0000000000068EDE6260AAF3F085E4BE12EA4A903C44E9BD9BB049A5C5E282D2DE0F472615A22D30346C3EB0BBF49276EFA69C8A08F190DF1AE07FA75682B22AE022E793A2C82BC475159408981957A4EBF99CB334D9DFF4A4D86CD8600C1E80EAD315658B51F6B067A262A71B55E5B6F196638D94EE3AABB31C92B7527077407B9A62BC9E" of steam.

This should work with elections, but not with news. @denysaw can you check it?

This is endpoint of token checker at game server. "https://auth.stagingland.strangeloopgames.com/game/verifytokenv3?token={escapedAuthToken}&serverId={Uri.EscapeDataString(serverId)}";

**Comment by redwyre** [comment]
My bad @denysaw, looks like it's better if you use the endpoint after all :(

**Comment by denysaw** [comment]
Done on both develop and staging -lands

**Comment by SlayksWood** [comment]
I again lost Eco News in both version

**Comment by SlayksWood** [comment]
need to check #17190 after fixing

**Comment by denysaw** [comment]
Will be working after this PR will be merged: https://github.com/StrangeLoopGames/Eco/pull/6527
