### ISSUE TITLE
Multiple graphical issues on mac in 5.6

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1710]
Seen two reports of graphical errors in 5.6 from mac users. One had the grass show as pitch black, other mentioned major artifacting, link below.

http://ecoforum.strangeloopgames.com/topic/2527/5-6-graphics-issues/4

**Comment by SeanAtr0n** [comment]
Sounds like toggling the advanced gfx settings as suggested in the thread should provide more useful info.  I suspect GI is enabled and may be causing problems.

**Comment by metachronism** [comment]
GI support on non-dx11 machines is going to be spotty.  The guy who wrote it hasn't yet added support for those platforms yet

**Comment by metachronism** [comment]
closing this for now without more info, but GI is likely to blame
