### ISSUE TITLE
Planter Pots won't display any plant at all

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17114]
There are multiple issues with planter pots right now but at the moment I cannot get any plants to appear in them, at all-- in addition to the weird useless 'fake plant' world object component, they are very broken feeling.

![image](https://user-images.githubusercontent.com/14983165/87465775-0ff4f980-c5ca-11ea-8483-03d7446af071.png)

**Comment by mirasrael** [comment]
Works for me. Do you do anything special to get this?
![image](https://user-images.githubusercontent.com/475445/87511110-75ee8900-c67d-11ea-8478-f2dabf416d55.png)

**Comment by SlayksWood** [comment]
For me it doesn't work for Acorn. Seems other plant are displayed right.

**Comment by SlayksWood** [comment]
Checked on 0.9.4 staging-2010, can't reprduce:
![image](https://user-images.githubusercontent.com/45708377/121003430-339ed080-c796-11eb-8f46-2eaa219054b6.png)
closed for now.
