### ISSUE TITLE
CW configs not saving

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17118]
Editing any configs for staging cw. click save does nothing.

**Comment by beastyn** [comment]
Try to change world name from NetworkManager Config.
Save button is active, nothing is happening
And after page refreshment I can't open any config settings with this error
![bandicam 2020-07-29 10-01-50-037](https://user-images.githubusercontent.com/27898520/88758744-9987f800-d182-11ea-8fb8-266a04d3d9c3.jpg)

**Comment by denysaw** [comment]
Was fixed by using adminToken. Worx for newly created worlds.
