### ISSUE TITLE
discussion serialization broken on 5.6 server?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1711]
Load up the 5.6 save then try to create a law

**Comment by MarjieAVolk** [comment]
I don't think the schema has changed for this part of the code.

I'm turning this bug into a bug for better error messaging in the Serializer when the schema gets messed up, instead of the cast exceptions.

**Comment by SeanAtr0n** [comment]
pretty sure meta fixed
