### ISSUE TITLE
Addind people to deed, hovering problem

### ISSUE THREAD

**Issue by Sladeck** [StrangeLoopGames/EcoIssues#17121]
9.0 - When trying to add someone to your own deed and you already have some people in the list of your deed so you can scroll the list, the "hover expand" icon appear in front of the name you want to add.

So you need to expand the list before trying to add someone if the name of the one you want to add is right in front of the expandable section before adding it, otherwise the expandable icon appear and enable you to expande the list of people currently allowed in your deed, instead of adding someone.

**Comment by SlayksWood** [comment]
We should have this issue, but I can't found it. I can't add myself to property:
![image](https://user-images.githubusercontent.com/45708377/87523893-2d8c9680-c690-11ea-8c26-d0152645356f.png)
Maybe it was fixed but was returned again.

**Comment by Dmittry62** [comment]
I can't reproduce any of the two issues described here.

**Comment by beastyn** [comment]
Nope, still here.
It happend when a name is on the window wdge line.
Like that
![bandicam 2020-08-04 16-56-00-496](https://user-images.githubusercontent.com/27898520/89291156-72926000-d673-11ea-9c29-1205c83a7739.jpg)
![bandicam 2020-08-04 16-56-18-026](https://user-images.githubusercontent.com/27898520/89291161-758d5080-d673-11ea-923a-1c14570f6d0c.jpg)
So 'Everyone' will have this expand icon

**Comment by abaza121** [comment]
![image](https://user-images.githubusercontent.com/17747441/102140514-fbae7480-3e67-11eb-8f4a-a515fe12d604.png)
This picker seems to be changed since then.

**Comment by SlayksWood** [comment]
We still have this picker 
![image](https://user-images.githubusercontent.com/45708377/102451905-7931da80-404a-11eb-9d9d-3a1bc44bfd7b.png)
But the issue is fixed.
