### ISSUE TITLE
[0.9.0 staging-1663] Filter in Mint  doesn't include all items

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17120]
![image](https://user-images.githubusercontent.com/45708377/87508568-5739c380-c678-11ea-84d1-cbe8b2647dca.png)
I have a very poor choice.

**Comment by WeaselDog** [comment]
@SlayksWood I believe this is only showing discovered items. Can you double check?

Also I was last one to edit what can be minted so I will take over the issue.

**Comment by SlayksWood** [comment]
@WeaselDog I checked it before and nothing was changed. In any case if we add only discovered items here so we need to add 'show undiscovered items' button.

**Comment by WeaselDog** [comment]
Issue was fixed by other changes to currency. We can create a new issue for adding option to show undiscovered when minting currency, but the bug has been fixed.
