### ISSUE TITLE
[0.9.0 staging-1664] Invisible undeground animal

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17124]
or just a traveling brain.
I used /sim debuganimal to investigate animal behavior. But one time I have linked with coyote that was undeground. I tried to dig it with dev tool, but I can't, seems he is invisible too. Possible that the animal doesn't exist at all, but we have wrong extra calculation.
Video:
https://drive.google.com/file/d/1v3sng77BWHCM9XOO5yjv2ClLu_RtCuB1/view?usp=sharing

**Comment by johnkslg** [comment]
May still be around in weird cases.
