### ISSUE TITLE
USER ISSUE: Brick Production Does Not Halt

### ISSUE THREAD

**Issue by JakeMercer** [StrangeLoopGames/EcoIssues#17128]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Create a brick job in the kiln with plenty of mortar but not enough clay.

**Expected behavior:**
It should stop trying to craft and using fuel when the clay runs out.

**Actual behavior:**
Instead it keeps "crafting" but the number remaining does not decrement.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Vanilla installation.

**Comment by JakeMercer** [comment]
Possibly linked to #14974?

**Comment by beastyn** [comment]
Thak you for the report.
Logic for a storage and orders was changed, should be fine in 9.0.
There won't be any fixes for the 8.3.3
