### ISSUE TITLE
[0.9.0 staging-1664] Fake plant tab is empty

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17127]
and doesn't have icon:
![image](https://user-images.githubusercontent.com/45708377/87535421-253c5780-c6a0-11ea-97d0-e98ef77abca5.png)
Maybe we should delete it?

**Comment by keegan-o** [comment]
They should ideally use the storage component to determine which plant appears (put the seed in the one storage slot). The code that makes this work does not need to be visible to the player at all.

**Comment by keegan-o** [comment]
I did my 'design' part of this task, it's up to programmers to actually make this thing work.
