### ISSUE TITLE
[0.9.0 Staging 1489] Invertebrate disable visuals option

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#17122]
Somewhat need an option to disable invertebrate visually appearing ingame due to users that have Arachnaphobia or a phobia of insects being unable to play the game safely/without fear

**Comment by D3nnis3n** [comment]
Moving to issues as the feedback i get for this and the amount of players stopping playing simply because of spiders is unreal.

**Comment by keegan-o** [comment]
This feature was added to 9.0
