### ISSUE TITLE
[0.9.0 staging-1667] Numbers are too large

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17136]
![image](https://user-images.githubusercontent.com/45708377/87650084-ce935400-c759-11ea-81a1-2afa0803c741.png)
And this numbers should be center align:
![image](https://user-images.githubusercontent.com/45708377/87650165-e79c0500-c759-11ea-8fa5-86e74d3db9a6.png)

**Comment by beastyn** [comment]
One is normal, one is bold
Still not centered
![bandicam 2020-07-30 16-36-00-968](https://user-images.githubusercontent.com/27898520/88918440-e0f5ad80-d282-11ea-9699-d5f8894268a5.jpg)
