### ISSUE TITLE
[staging-1668] Titlescreen UI dissapeared

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17139]
![image](https://user-images.githubusercontent.com/431728/87725549-d4904000-c800-11ea-8444-d41c47cd4711.png)
Nothing in the log

**Comment by SlayksWood** [comment]
I have this issue one time too. But nothing in log(
Need to investigate it. @gzatravkin maybe related with your last changes.

**Comment by SlayksWood** [comment]
Seems it isn't hard to reproduce it. Just make some manipulation in new game and then press Your Worlds (I have this issue 3 times when press Your Worlds). You can see video:
https://drive.google.com/file/d/1aPLfYh3twxKaBmhVbyg6BQF-d61rRKiL/view?usp=sharing
