### ISSUE TITLE
Ecopedia page link is enabled by default

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#17130]
Excepted behavior: page icon appears only after mouse over
Now:
![image](https://user-images.githubusercontent.com/53317567/87583026-b5cf6380-c6b1-11ea-9054-2e98485f783d.png)

**Comment by SlayksWood** [comment]
Happens when first opened after placement.

**Comment by Dmittry62** [comment]
Looks like there's already a fix by @gzatravkin but it's not merged yet.
