### ISSUE TITLE
Adjustments to 3rd person camera and Avatar jump animation

### ISSUE THREAD

**Issue by MilenkoTunjic** [StrangeLoopGames/EcoIssues#17133]
Please set the third person camera to the values of:
X: 0.3 , Y: -0.3 . Z: -2.3
Also, make sure that default FOV for third person camera is set at 60

In regards to the avatar jump animation, make it overall faster, reduce hang time and make sure that transition between landing and grounded strafe is minimal (almost instant, to eliminate sliding on the ground after landing.

**Comment by redwyre** [comment]
camera offset is already done in https://github.com/StrangeLoopGames/Eco/pull/6390

**Comment by StanKryvenko** [comment]
Tweaked animation in SVN
