### ISSUE TITLE
welcome message deltas seem incorrect

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1713]
![welcomemsg](https://user-images.githubusercontent.com/3150561/27458833-d861873a-575f-11e7-8d4c-e74d7ac5a350.png)

**Comment by MarjieAVolk** [comment]
:O I've seen it give the delta as equal to the population, usually on first login (which actually I could probably fix that easily), but this is very weird.

I did just change the GetStatDiff method or whatever that's called, which was basically rounding down the time range to the nearest tick, but now it is rounding it up (for law enforcement reasons), but not sure if that would affect this.  What save was this on?  Let's look at the population graphs for it, maybe there was a weird fluctuation that it just caught the edge of.

Also, I thought I removed commongrass from this.... hmmmm
