### ISSUE TITLE
[0.9.0 staging-1668] Plant population spread is way too fast

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17143]
Some plants are spreading at incredibly fast speeds, significantly disrupting gameplay and causing a visual eyesore. It is really noticeable with some species. By day 0.13, Barrel Cactus had increased in population from 5,000 to 29,000. Pumpkin had increased from 2,000 to 7,400.

Here is snap of population chart:
![PlantPopulations](https://user-images.githubusercontent.com/47330823/87729886-3c9c4300-c77b-11ea-9b01-f5b269d91157.png)

**Comment by WeaselDog** [comment]
Unassigning myself, but let me know if you need anything from my end.

**Comment by WeaselDog** [comment]
@StanKryvenko What needs to be investigated here?

**Comment by WeaselDog** [comment]
@MazonDel Please come to me if you have any questions about this.

**Comment by mirasrael** [comment]
@MazonDel if you won't be able to find solution fast enough then you can pass this task to me.
