### ISSUE TITLE
[0.9.0 staging-1669] Store UI. Players Currency have doesn't update immediately.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17148]
You need to change something or reopen UI. Step to reproduce:
- go to someone store
- want to sell something in it:
![image](https://user-images.githubusercontent.com/45708377/87762038-1c23c580-c81b-11ea-807d-55cb29cb9d43.png)
- press trade:
![image](https://user-images.githubusercontent.com/45708377/87762084-3198ef80-c81b-11ea-8730-345132d7dca0.png)
- to update it I need to press some button in UI for example "+":
![image](https://user-images.githubusercontent.com/45708377/87762164-54c39f00-c81b-11ea-85c4-c74b578bad74.png)

**Comment by Dmittry62** [comment]
Followed the steps. Look alright. Must've been fixed.

**Comment by beastyn** [comment]
Nope, still here
After buying from Slayks store he still has 1000 Shells.
But he does not
![bandicam 2020-08-04 16-39-14-354](https://user-images.githubusercontent.com/27898520/89289792-3f4ed180-d671-11ea-854e-a76a4225aa81.jpg)

![bandicam 2020-08-04 16-39-44-988](https://user-images.githubusercontent.com/27898520/89289799-4249c200-d671-11ea-9cb4-841de7ba4225.jpg)

**Comment by johnkslg** [comment]
Value is being assigned here: ![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/2ee547f2-7e72-47d8-8193-3bd3e11905ec)

This is only being updated when the function is called, but it should be triggered whenever the owners currency changes. This means youll need to subscribe to the server side data that has how much money is in their bank account.

The credit component does this:
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/f41c5e9d-3f3a-4a8e-ba7c-14a5ec515a05)

I reckon the best fix is to take that code in the credit component that subscribes to the holding changes and put it in a shared utility, that both CreditComponent and StoreComponent will use, and they can both then subscribe to changes of the bank account amount.

Some reading to help you understand these systems:
How syncing data between client and server works: https://github.com/StrangeLoopGames/Eco/wiki/Controller-View-System
