### ISSUE TITLE
Final product of a work order is not added to other work orders

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#1715]
Craft X that requires Y boards
Craft exactly Y boards
last boards won't make it into X.

Needs testing to reproduce

EDIT: Seems like it just doesn't always take materials - who knows

**Comment by metachronism** [comment]
I would think this is fixed by now, but double check

**Comment by MarjieAVolk** [comment]
Tested this out, and it is still happening

**Comment by MarjieAVolk** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/1675
