### ISSUE TITLE
Stockpile being accessed through walls roof and ground

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#17165]
\
**Version:** 0.9.0.0 beta staging-stable-3

**Steps to Reproduce:**
build a house with stockpile on the roof, try and remove roof to replace with another block and it accesses Stockpile, same happens for Walls (when a stockpile is close) also does same for a stockpile on the surface and when trying to mine/dig underneath and replace the roof with blocks

![snap6946](https://user-images.githubusercontent.com/29383891/87855657-a0f10b00-c911-11ea-8f79-f56340878a53.png)

above snapshot is me trying to remove dirt under my *TEMP SURFACE* name stockpile

**Comment by matheod** [comment]
Yes this is really annoying for construction. Same happen with capitol building for exemple.

**Comment by Conchipedia** [comment]
somehow i think the detection of a normal stockpile has increased beyond its normal range, and gets targeted way to easy, especially through walls

**Comment by Fnunzi** [comment]
Yes i had the same problem when building. I could not pick a block up if a stockpile was behind it.

**Comment by Dmittry62** [comment]
I think the problem appeared after commit 84b2fd0a.
https://github.com/StrangeLoopGames/Eco/blob/staging/Client/Assets/VoxelEngine/Physics/MapIntersection.cs#L212

@StanKryvenko could you take a look at this?

**Comment by Conchipedia** [comment]
i see this says fixed but still a problem in 
![snap7026](https://user-images.githubusercontent.com/29383891/89548678-3be95080-d7ff-11ea-9299-2ef243aade2e.png)

as you can see from following snapshot i planted some Camas in dirt above a stockpile underneath and cannot access plants, just the stockpile
![snap7029](https://user-images.githubusercontent.com/29383891/89548758-53c0d480-d7ff-11ea-861b-e0a9b213776c.png)
