### ISSUE TITLE
[0.9.0.0 beta staging 3] Basic election anonimity is broken in chat

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17164]
When a user vote, it's name and vote is written on the chat, despite the election being anonymous.

![image](https://user-images.githubusercontent.com/339611/87843197-e6322000-c8b2-11ea-8333-489194e3e9bd.png)

**Comment by matheod** [comment]
Need to also check when changing vote.

![image](https://user-images.githubusercontent.com/339611/87993542-1237e600-caeb-11ea-990d-ec50d1d6941a.png)

**Comment by johnkslg** [comment]
@olegshegai can you take this one? Thanks!

**Comment by johnkslg** [comment]
Thanks @matheod  great find
