### ISSUE TITLE
Server Unlisting / Banning Feature

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17173]
We do have some cheating servers that fake their online and total numbers to gain advantage over other servers, also manipulating the server listing priority by doing so, thats not only manipulating our services but intolerable behaviour to all the server-admins trying their best to get a good listing in legit ways. It's also deceiving players into believing the server is bigger than it is, causing reports to me.

We need a option in backend, next to banning users, to act upon servers, there should be two options:
- Unlisting the server from the master list, so people can still direct connect but the server is no longer shown. (Backend already available)
- Banning the server, so it's unlisted and people can no longer join on it. (Backend not yet available afaik)

Unlisting should be possible by IP + Port, for the whole IP, for a IP Range, for the Server-ID and even for servers that include specific tags in their names or descriptions. Reason field needs to be available for internal tracking.

Banning should be possible by IP+Port or ID only, reason field to be shown to users trying to connect.

I believe mirasrael and redwyre implemented the unlisting in backend, so talk with those.
The unlisting feature should be enough for at the moment, there is little reason i can imagine for a server being banned, but the possibility should be there long-term.

**Comment by mirasrael** [comment]
Ban list currently is in file and is part of master server.

**Comment by j3fffff** [comment]
@D3nnis3n on discord it sounded like we're going to try diplomacy first.
Hopefully that will mean very few bans required. 

In that case, don't think we need to make a ui to interact with master server (big task)
And we can just rely on manually updating ban file on master server.

And if we increasingly need to ban/hide servers. 
then we can revisit this task
Sound good?

**Comment by D3nnis3n** [comment]
Seems good to me.

Jeff <notifications@github.com> schrieb am Mo., 20. Juli 2020, 19:52:
