### ISSUE TITLE
Streamline recipes of different specialties

### ISSUE THREAD

**Issue by Chojin666** [StrangeLoopGames/EcoIssues#17178]
Not an issue, but a convenience improvement.

1. Version: Steam - public_test_9.0
2. Streps to reproduce: Open e. g. Carpentry Table and Masonry Table. 
3. Expected behavior: Streamline the access of recipes with different variations (assuming the variations only differ in look and a complementary ingredient like hardwood and softwood e. g., while labor, etc remains the same) one way or the other. This would also reduce the amount of recipes in the list of the bench itself in order to tackle loading times when opening a bench, as well as making variations of recipes more transparent to the user. 
4. Actual behavior: While all Hewn Log recipes variations are listed in the recipe list of the bench itself, all the different Mortared Stone recipes variations are avaiable through the "Advanced Crafting" gear button.

**Comment by SlayksWood** [comment]
merged to #13334
