### ISSUE TITLE
USER ISSUE: Felle werden nicht erzeugt

### ISSUE THREAD

**Issue by thanse2s** [StrangeLoopGames/EcoIssues#17175]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Hasenkadaver zur verarbeitung ausgewählt
2. Produktion gestartet 

**Expected behavior:**
Fleich und Leder wird produziert

**Actual behavior:**
Nur Fleich wird produziert

**Do you have mods installed? Does issue happen when no mods are installed?:**
Nur Fleich wird produziert

**Comment by SlayksWood** [comment]
@thanse2s Can you provide more information?
1. What crafting table do you use?
2. Provide Some screenshots - linked inventories too. The best option would be to make a video
3. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
