### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Tooltip Error for Shop Item "Jungle Campfire Stew"

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#17176]
When you hover over what is in a Shop you can see that "Jungle Campfire Stew" is named "Infused Oil"

![20200719232255_1](https://user-images.githubusercontent.com/63646359/87885540-109cee00-ca17-11ea-857a-09e28e7f6b48.jpg)

**Comment by Engimage** [comment]
Somewhat related
I have seen a message in the log, when your shop is sold out of "item-name". Maybe it was said "Jungle Campfire Stew" as I actually do sell them, but the log said I am sold out of "Infused Oil"
