### ISSUE TITLE
[0.9.0 staging-1672] Another players can change default account in Mint

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17179]
Step to reproduce:
- place mint, clame it, add everyone in autorization tab, craft some coins. Select Target accont:
![image](https://user-images.githubusercontent.com/45708377/87914416-42df3780-ca79-11ea-9172-68f3295f674e.png)
- another player open mint and change account:
![image](https://user-images.githubusercontent.com/45708377/87914436-4a9edc00-ca79-11ea-86e3-84cca411f748.png)
- first player check default account:
![image](https://user-images.githubusercontent.com/45708377/87914465-57233480-ca79-11ea-9570-847dabe70585.png)
- it should still be craft here!!!, but it was changed to another player account.

**Comment by Dmittry62** [comment]
It was decided to develop a system of user preferences for all world objects (e.g. default bank account in mint). So this issue will be dealt with later.

**Comment by SlayksWood** [comment]
this issue was fixed I created another one #17403
