### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Development build error console flicker

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17174]
There is a visually hidden console in development build. Quite often when it recieves error messages it appears on screen momentarily for a frame or two and disappears.
This red error flickering has a lot of negative feedback from players on a test server.
I think this is not intended behavior and can be fixed.

**Comment by mirasrael** [comment]
Unfortunately we don't have much control over this logic. It is embedded Unity console which we can only disable **after** this already opened. We already disabling it every frame, but it seems Unity may for some reason show it between frames and if you have errors in multiple sequential frames then it may appear for awhile.
