### ISSUE TITLE
Getting back more resources from building item

### ISSUE THREAD

**Issue by MarttiMarran** [StrangeLoopGames/EcoIssues#1717]
You can reproduce this bug by placing a large amount of items into queue, for example 1000 campfire beans. Then let it finish building some and after that you can cancel it. You'll get back most of the resources plus you will get disconnected due to "inactivity"

**Comment by MarjieAVolk** [comment]
Just tested this out with a large order, and it took a very long time (not too surprising), and also gave me back less resources than I expected - I crafted, I think 4 out of the 900 items, but got back resources as if I had crafted 8.  So yeah there's a problem here, maybe a concurrency problem

**Comment by MarjieAVolk** [comment]
Yeah, so the cancel operation calculates the # of resources to give back at the beginning, then goes on and tries to add items, etc - if the inventory add operation takes a long time, then the work order can continue crafting while this is going on.

Not sure how to solve this

**Comment by MarttiMarran** [comment]
You'll get mats back when you build lets say 100 campfire beans, you have mats for 10. When it gets halted then you will get back mats for some.
