### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Teleporting fish

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17184]
Fish was on floor : removing the block it's on will make it fall in lake, but putting back the block will make it teleport on the block again. Putting a block above this block will also teleport this fish above the new block.

See video : https://imgur.com/a/Y5TSnyJ

**Comment by johnkslg** [comment]
Push to next animal upgrade

**Comment by SlayksWood** [comment]
I guess this is still an issue:
![image](https://user-images.githubusercontent.com/45708377/100982604-4e7b5880-3559-11eb-99d5-c13609781bb6.png)
build such platform above the water:
![image](https://user-images.githubusercontent.com/45708377/100982635-5affb100-3559-11eb-90bf-5a81e1c36423.png)
