### ISSUE TITLE
Object deleted by sand block

### ISSUE THREAD

**Issue by Fnunzi** [StrangeLoopGames/EcoIssues#17187]
I was mining and made a hole in stone.  i had 4 stone chunks on the ground and didn't pick them up yet.   I then grabbed some sand and put the sand on top of the 4 stone chunks.  all 4 stone chunks were deleted when the sand settled into place. 

I have yet to try with other stuff like dirt or clay.    But im going to guess it acts the same way to if i put a log or stockpile on the ground it deletes all the plants under it.

**Comment by SlayksWood** [comment]
I finally found it. dup #16246
