### ISSUE TITLE
Add Buy/Sell Tags of goods in shops

### ISSUE THREAD

**Issue by Chojin666** [StrangeLoopGames/EcoIssues#17180]
Not an issue but a quality of life improvement.

1. Version: public_test_9.0 - 
2. Steps to reproduce: Open Shop interface and adit buy/sell list
3. Expected behavior: Possibility to select whole tags for goods, e. g. Wood Tag. This would reduce the shop management a lot.
4. Actual behavior: E.g. If you want to buy/sell all the different log types, you have to add all of the different types sequentially to you buy/sell list.
5. Providing Log files.

**Comment by SlayksWood** [comment]
dup #14630
