### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Store Credit Changes back periodically

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#17194]
Engimage and me (mepHy) changed our Stores to "Candy" our world credit, after a few moments, it switched back to our own currency.

**Comment by mepHy86** [comment]
It happens again and again after a few time and we dont know why

**Comment by SlayksWood** [comment]
@johnkslg @StanKryvenko Seems it's related with your last changes with claiming/unclaiming store.
Step to reproduce:
- claim 1 plot and place store:
![image](https://user-images.githubusercontent.com/45708377/88044981-f4a06600-cb56-11ea-814d-bad3672fb3a1.png)
- change currency and bank account in credit tab:
![image](https://user-images.githubusercontent.com/45708377/88045446-35987a80-cb57-11ea-843a-d453e6f12f8d.png)
- claim another plot to this property:
![image](https://user-images.githubusercontent.com/45708377/88045494-4648f080-cb57-11ea-8dbb-d682df5f012d.png)
- open credit tab in store:
![image](https://user-images.githubusercontent.com/45708377/88045511-4fd25880-cb57-11ea-9df8-77750fc3faeb.png)
- bank account and currency was updated by default.

**Comment by mepHy86** [comment]
Confirmed on test server, it may change when you change the claimed property, this happens also when you extend your property

**Comment by johnkslg** [comment]
Perhaps related to what youre doing

**Comment by Dmittry62** [comment]
It certainly seems so

**Comment by WeaselDog** [comment]
Still an issue

**Comment by SlayksWood** [comment]
Still an issue for treasury:
![image](https://user-images.githubusercontent.com/45708377/90101845-1d77dd80-dd48-11ea-8355-f60633ece986.png)
- claim a new property - Ctrl+RMB:
![image](https://user-images.githubusercontent.com/45708377/90101908-33859e00-dd48-11ea-9750-0a0cd006e7a9.png)
