### ISSUE TITLE
[Title Screen UI] Eco News should be close-able

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17190]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/24b9bb0a-ef92-4cd7-a74e-73efdd4fbbdf)
Not being able to close the Eco News once open is a little annoying, ideally just a regular UI [X] available would be good.

**Comment by SlayksWood** [comment]
When I press 'X' I can't open news anymore, I need to restart client:
![image](https://user-images.githubusercontent.com/45708377/89387623-6e198600-d70b-11ea-9882-44d78bb16eeb.png)
![image](https://user-images.githubusercontent.com/45708377/89387633-6fe34980-d70b-11ea-9a79-1d4c296d39b7.png)
