### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Error getting title: Object does not match target type

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17196]
![image](https://user-images.githubusercontent.com/339611/87989876-1c55e680-cae3-11ea-8910-54688a9a77f5.png)

**Comment by SlayksWood** [comment]
@matheod Thank you for the reprort.
1. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Do you have this error for all objects or only for this bank?
3. Did restarting the game help you?

**Comment by matheod** [comment]
1. Unfortunatly no

2. This was only for this bank (there wasn't other bank, but all other item on map was displayed without issue on minimap)

3. I don't know, but I tested multiple time today and wasn't able to reproduce this issue.

**Comment by TwixterZ** [comment]
Closing this issue for being not-reproducible and an old issue. 
@matheod please do let us know if you faced this issue on our newer patches.
