### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Road Tool, Road despawn

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#17192]
When you make roads with a "Road Tool", the road went away like when you hoe a Farm and wait.

![20200720204920_1](https://user-images.githubusercontent.com/63646359/87974662-b3627480-caca-11ea-982d-ede3404424e3.jpg)

You see its gone, it was road before, even over the stairs.

**Comment by Fnunzi** [comment]
Same with Tilled Land. It goes away after a really short amount of time.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/6394
