### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Opening the Read-only law view prevent further editing

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17199]
- Draft a law then close it.

- Click on the button to view the law without editing it, then close it

- Click on the edit button : you got the read only view and got edit it.

- To bypass the bug, you have to add a new section, then close then open again.

**Comment by SlayksWood** [comment]
already fixed with https://github.com/StrangeLoopGames/Eco/pull/6406
