### ISSUE TITLE
Ambient occlusion not visible enough

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17191]
Top: on, Bottom: off
![image](https://user-images.githubusercontent.com/3536496/87974406-e252f900-ca7e-11ea-8b40-50d9adfeaa50.png)

They may be slightly different, but its very hard to tell. I'd like to experiment with turning it up, so you see shaded areas in the cracks. 

Compare to Minecraft:
![image](https://user-images.githubusercontent.com/3536496/87974570-1f1ef000-ca7f-11ea-9e65-6ecd6957c7a1.png)

Lots of our game looks very flat, and improving ambient occlusion will make a big difference.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/87976196-8f2e7580-ca81-11ea-9a4b-d089d6a87249.png)

**Comment by keegan-o** [comment]
Turning it up beyond where we have it will result in lots more artifacts (shimmering shadows/lights and very weird screen effects as you enter/leave buildings in third person, especially)

**Comment by keegan-o** [comment]
AO isn't as strong in the cracks of those blocks because they aren't cubes, I think
