### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Creating law : sometime a refresh is required

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17197]
I was tring to create a law:

![image](https://user-images.githubusercontent.com/339611/87992238-1b738380-cae8-11ea-8ccc-a5ee8a283956.png)

The first time after selecting percent, the **A section didn't show** (so I just had percent but not the UI to select the percent amount), After closing and reopening the draft law, the A section was back.

I tried to reproduce the issue, so I switched the "percent" type to "number", then switched back to "percent". This type the A section was here, but **the B section (to delete the then(list) part) wasn't here** (but the X to delete IF and THEN(list) was here).

I closed and reoponed the draw law : the B section was here, I clicked on it and tried to reproduce the bug but this time **clicking the + (at the right of List) did nothing**. Closing and reopening the draft law make the + button work again.

I tried to reproduce the three bug here:
- I couldn't reproduce again the first bug (A section missing)
- I was able to reproduce the second bug (B section missing, I think the X go below the other X because you can see a strange glitch with the X going to strange position)
- I was able to reproduce the third bug (+ do nothing)

edit : bug A happened again (with arithmetic this time) and refresh didn't fix it. Most of the time there is nothing, sometime "Left value" appear but it's rare.

**Comment by matheod** [comment]
I tried in solo and I didn't get any bug.

**Comment by SlayksWood** [comment]
I will merge in one issue #17202
