### ISSUE TITLE
Industrial Workbench 5.6 release, still broken

### ISSUE THREAD

**Issue by Kriegsfalke** [StrangeLoopGames/EcoIssues#1719]
the industrial workbench still no function

**Comment by MarjieAVolk** [comment]
It seems to work for me.  What problems are you having with it?

**Comment by Kriegsfalke** [comment]
It is as if he were not there, can go through

**Comment by ecoemmeck** [comment]
can confirm this issue as i placed an industrial workbench last night and it had the same issues

**Comment by MarjieAVolk** [comment]
This should be fixed in current staging build
