### ISSUE TITLE
[0.9.0.0 beta staging-stable-3] Law : advanced option button do nothing

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17198]
Try to create any law, for example:

![image](https://user-images.githubusercontent.com/339611/87993119-0861b300-caea-11ea-829f-2631952c6ddf.png)

Then try to click on the advanced option button : nothing happen.

Closing and reopening the law doesn't fix the issue.

edit : restarting game fixed the issue

**Comment by SlayksWood** [comment]
This issue should be fixed in new version. Please reopen if you have this issue after playtest update.
