### ISSUE TITLE
[0.9.0.0 beta staging 3] law name are not escaped

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17203]
Law name are not sanitized in left menu of Web UI. XSS vulnerability

Example :

1. Step de reproduce
Create a law named `<script>alert(42)</script>` and propose it to vote. Access Web UI.

2. Expected behaviour
Nothing happen, the law name is displayed in plain text

3. Actual behaviour
The javascript will be executed and the alert popup will appear

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/88040702-f61b5f80-cb51-11ea-906c-1b5f856cf014.png)

**Comment by IcedForge** [comment]
Changes made is causing the website to callback script error and can no longer access any running elections or any previous elections either.
![Screenshot_43](https://user-images.githubusercontent.com/24981362/95183481-53749380-07c6-11eb-826b-415b2e2aab7d.jpg)
![Screenshot_44](https://user-images.githubusercontent.com/24981362/95183489-553e5700-07c6-11eb-8e44-ac41d20af79d.jpg)

**Comment by IcedForge** [comment]
Bumped priority on it as this completely broke my ability to vote on anything anymore.
@denysaw

**Comment by IcedForge** [comment]
Forced to clear cache to use election website again after shutting server down and using a new fresh world.

**Comment by denysaw** [comment]
@IcedForge Forced :) Yes, please clear cache before each new tests ;) Sometimes, I'm updating anti-cache version variable, but sometimes forgetting (like this one). So problem is gone after cache clear, right?

**Comment by denysaw** [comment]
As I got yes, could as I see it's the only problem. So yep, it's web and cache should be cleaned (Ctrl+F5 while being on page). Putting fixed, put re-open if clear cache doesn't help.

**Comment by IcedForge** [comment]
still getting this trying to open the previous election page after i set a law with the popup alert code.

0.9.1.0 beta develop-81
![Screenshot_97.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/87a0be55-d118-4d80-aa0d-42e3ef39aca6)

The actual law page

![Screenshot_99.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/693cf00f-fdab-4b0d-bdd3-817ff620e8d7)

On page refresh with cache clearing it throws me the popup again.
@denysaw

**Comment by denysaw** [comment]
@IcedForge Aha, really. Current election was still not escaped (only menu section), thanx for pointing out 👍  Done. You could re-test after PR above will be merged ;)

**Comment by IcedForge** [comment]
I assume all of the pages are now included?, Previous elections, current elections etc?

**Comment by denysaw** [comment]
@IcedForge Yeah.

**Comment by SlayksWood** [comment]
I still have problem with election name, maybe it was broken with new system?)
![image](https://user-images.githubusercontent.com/45708377/95858485-da48e380-0d65-11eb-9c79-72aeb0973721.png)

**Comment by denysaw** [comment]
@SlayksWood Wha? =)) Not funny. You can't have name with `<script` in it as it's counted as an XSS attack. <script tags are being removed there and will be in some other places. It's norma. So on the snap everything is correct, cuzz after removing <script tags only `Act` should've been left, which we see on a left snapshot. Returning labels back
