### ISSUE TITLE
Alpha 5.6 - Carts are not moving when crossing coordinates 999 to 0

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#1720]
Description: Moving a small wood cart through block 999 to block 0 makes the cart stop or beeing very slow (like fps lag).

**Comment by SeanAtr0n** [comment]
I'm having difficulty reproducing this... does it give you issues everywhere or in some specific circumstance?

**Comment by fillion07** [comment]
I retest it and if you put down your cart right between 999 and 0 and you take it back, you will jump in the air with the cart. But I was not able to reproduce the issue with the cart stucked to these coordinates

**Comment by SeanAtr0n** [comment]
Seems to be resolved
