### ISSUE TITLE
[0.9.0.0 beta staging 3] When drafting new law Trigger/if/then UI will not always appear

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17201]
https://imgur.com/a/fhOJ0qX

I didn't get the bug before but now I always get this bug. If I draft a new law I will not be able to do anything as trigger / if / then will not show.

If I add an other section same issue. If I add an other section (so third section) the triger/if/then ui will show.

Was able to reproduce this bug three time in a row.

**Comment by matheod** [comment]
Probably related : I was working on a law, closed the law and reopened it. Got this:

![image](https://user-images.githubusercontent.com/339611/87995600-406bf480-caf0-11ea-9c34-847a4c00f441.png)

So it's like if what i drafted disappear. Clicking on the + does nothing.

However, it didn't really disappear, content it's still here (you can see icon of the law, and on tooltip you can see that content is here)

**Comment by SlayksWood** [comment]
@matheod when you make issues, please make them with the following template:
1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files.
Do you have log files for this issue?

**Comment by matheod** [comment]
No sorry I forgot to save the log file.

But I tried to reproduce the bugs multiple time since update and I am no longer able to reproduce the issue.

I think we can assume it was fixed and close the issue (I let you do it) ? I will reopen the issue and save le logfile if this happen again.

**Comment by matheod** [comment]
Was able to reproduce.

- I duplicated a law, updated it and proposed it. I then duplicated my proposed law to improve it again and the third section was not editable. (see B1.log).
-I closed the law, and reopened it. This time section 3 was editable but it was section 1 that wasn't (B2.log).

[B1.log](https://github.com/StrangeLoopGames/EcoIssues/files/4968866/B1.log)

[B2.log](https://github.com/StrangeLoopGames/EcoIssues/files/4968860/B2.log)

**Comment by matheod** [comment]
I continued trying to work on my law and after a closing / opening I now only have section 1.
[Player - Copie (3).log](https://github.com/StrangeLoopGames/EcoIssues/files/4968991/Player.-.Copie.3.log)

![image](https://user-images.githubusercontent.com/339611/88342279-65a27200-cd3f-11ea-9af1-6b8d7871ee4d.png)

**Comment by matheod** [comment]
Reconnecting to the server fix the issue.

**Comment by henrikolsson** [comment]
Seeing this as well.

**Comment by IcedForge** [comment]
Should be fixed by release of 9.0, please reopen if this still is an issue for you.
