### ISSUE TITLE
Alligator swim animation needs be lowered just slightly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17208]
![image](https://user-images.githubusercontent.com/3536496/88019725-41485a80-cadf-11ea-8188-a5edae2e9324.png)

**Comment by keegan-o** [comment]
@johnkslg and @SlayksWood Best to assign animal animation issues to  @MilenkoTunjic (since lach is not really here) as they are all made in max and editing them will be easier for max users.

**Comment by MilenkoTunjic** [comment]
On the art side, animation looks correct. Bip001 bone is set at -13.8 vertically (on z axis in max) for this particular animation. I might be wrong but what it looks to me is as if in the game, the root (Bip001bone) is set at 0, pulling the whole mesh up above water. I might be wrong, but whatever it is does not seem to be on the art side.
Can someone please investigate and let me know?

**Comment by StanKryvenko** [comment]
Alright, we have these two guys related to this issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/17568
https://github.com/StrangeLoopGames/EcoIssues/issues/16951
And I think we should move it to a deeper water level than it is for now.

**Comment by MilenkoTunjic** [comment]
Crabs should walk on the bottom, not swim.
Sharks might need fixing too.

**Comment by MilenkoTunjic** [comment]
Floating Swimming aniamls have all been adjusted now @StanKryvenko is going to set it up on his end to make sure it works.
