### ISSUE TITLE
[0.9.0.0] beta Stagin-stable-3 : Chat freeze lag

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17215]
When enabling / disabling any chat channel it freezes up the client for a second.

**Comment by D3nnis3n** [comment]
I got that issue as well.

**Comment by SlayksWood** [comment]
Use this world to reproduce freezes: https://drive.google.com/file/d/13VV7ASrU4wfm99SAKSRRZnih6OhrcciI/view?usp=sharing
