### ISSUE TITLE
USER ISSUE: error 500 - login server is down

### ISSUE THREAD

**Issue by Thunderclash** [StrangeLoopGames/EcoIssues#17221]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Try to connect to any server.

**Expected behavior:**
User can connect to the server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Happens to all servers currently. Regardless any mods installed (yes I have my game modded (server)).

The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Comment by WeaselDog** [comment]
Thank you for your report. The servers are back up and we are addressing the source of the issue.

**Comment by WeaselDog** [comment]
We have made some improvements to auth server that will help if this situation happens again. Thanks again for letting us know.
