### ISSUE TITLE
World object rendering test

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17220]
Test performance of the rendering of world objects by comparing framerate/GPU load with them as normal, and then not rendered.

You can add flag to a function key to toggle world object rendering on and off.

**Comment by swapnilnegi** [comment]
Some key points after profiling:

1. There is an increase in FPS when we disable world objects in the current camera view. More the number of objects disabled more is the increase in performance. In cases where there are less objects in the view to be disabled, performance seemed to be almost same.
2. There is also a decrease in CPU time taken to render individual frame. More vertices and triangles to process, more is the time taken by CPU to render the objects. And it clearly seemed to have improved when there were less objects in the view.
3. Less draw calls and SetPassCalls when the objects were disabled.
4. Less triangles and vertices count. Difference is directly proportional to the number of objects disabled.

The doc below has some profiling data of some places in the world with/without the world objects and a comparison of CPU and rendering data.

ON- Is with the world Objects
OFF- Is without the world Objects.

https://drive.google.com/file/d/1zihYmGboxpd4qGXuxFJKuAJPuO3V1pxT/view?usp=sharing

**Comment by redwyre** [comment]
This happened the the result was that there would be no CPU gain from using LODs at this point
