### ISSUE TITLE
USER ISSUE: odd error

### ISSUE THREAD

**Issue by kintobor115** [StrangeLoopGames/EcoIssues#17222]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
have steam randomly dissconnect and have some kind of token error then try connecting to your friends server and get failed connects 500 internal server error auth fails and such   

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (500) Internal Server Error.</size>
```

**Comment by MonzUn** [comment]
This is just the Steam servers being broken. It happens rather often and there is nothing really that SLG can do about it.
I generally advise players to use the standalone SLG client from their website instead.

**Comment by MonzUn** [comment]
Dup https://github.com/StrangeLoopGames/EcoIssues/issues/17221
