### ISSUE TITLE
Optimization: Animals causing large performance impact

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#17225]
@SlayksWood send me the dump where he has ~15 FPS. I analyzed it and it seems like animals causing this:

It seems we have 653 animals in this snapshot.

Culling takes 6.2ms which means that there lot of renderers to be analyzed (every animal has bunch of renderers for body parts):
![image.png](https://images.zenhubusercontent.com/5645db18638e718c995e828f/debec94a-b617-4584-9196-22072cc3553e)

3.55ms in Amimal Interpolate + 2.37ms in Solver (which used for animals):
![image.png](https://images.zenhubusercontent.com/5645db18638e718c995e828f/09220e41-6816-49eb-a127-8d5fb5a17c25)

Physics takes 9.61ms, but it executed 4 times (because of Fixed Update and slow frame rendering) and also it has SolverManager part (which used for Animals).
![image](https://user-images.githubusercontent.com/475445/88154892-0a259680-cc10-11ea-8ffd-e4a27a263e61.png)

Another 1.3ms from AnimalAnimationManager + 1ms from UnityAnimal + 0.37ms from MoveThroughSound (which also probably caused by animals) + 0.63 from Solver Manager.
![image.png](https://images.zenhubusercontent.com/5645db18638e718c995e828f/c7702a00-1df1-4729-bf82-f719fe67989c)

**Comment by SlayksWood** [comment]
EcoProfilingData:
https://drive.google.com/file/d/101b6T_0460CHMXDuIhKnLZ6v4UIidBfE/view?usp=sharing
I didn't really do anything special: some test work party and a little movement around the world.
But currently FPS falls is noticeable when you just stand in one place for a long time. To increase this effect you can run around the world.

**Comment by SlayksWood** [comment]
check this #15236 after fixing

**Comment by johnkslg** [comment]
I've added lodding which should help here.  
Needs reprofiling

**Comment by mirasrael** [comment]
Optimization delayed until animal fixes, because it may cause conflicts and will need another optimization pass after this.

**Comment by mirasrael** [comment]
After latest changes impact not so significant. It is stills something we can improve in future though, so pushed for later release.

**Comment by namquang93** [comment]
This has been improved a bit further thanks to ECS/Jobs implementation: https://github.com/StrangeLoopGames/Eco/pull/7558.

**Comment by WeaselDog** [comment]
We will push the remainder out of 9.3, but leave this issue open for future optimization.

@namquang93 
> there're still lots of room for animal optimization. In profiler I can see AITarget, AnimalAnimationManager, path finding code... takes 3-4ms per frame. But this requires lots of work.

**Comment by mirasrael** [comment]
In 9.4 animal calculations significantly improved. Guess issue may be closed:
![image](https://user-images.githubusercontent.com/475445/115238160-0afb4280-a126-11eb-9507-4e430bba58f8.png)
