### ISSUE TITLE
No easy way to rep people?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17230]
The reputation indicator behind player names in the "O" menu has been removed.
The only way to rep people is through tooltip gore and that doesn't even work reliably on click.
We need the indicator back or an even easier way to rep people.

**Comment by SlayksWood** [comment]
0.8.3.3 UI:
![image](https://user-images.githubusercontent.com/45708377/88259973-1a02b080-cccc-11ea-8181-64039dd11f6b.png)
You can give reputation to people when click on reputation name.

**Comment by matheod** [comment]
I didn't know there was a reputation system untill someone gave me reputation. I then searched how to give reputation but was unable to found how. But ecopedia gave me the solution.
