### ISSUE TITLE
[0.9.0.0 beta staging-stable-7] Ecopedia button randomly doesn't work and show tooltip instead

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17238]
Step to reproduce:
- try to click on the ecopedia button

Expected result:
- The ecopedia page open

Actual result sometime:
- Nothing happen and a tooltip is displayed (which seems to be related to the object in the not displayed minimap area)

![image](https://user-images.githubusercontent.com/339611/88243301-4a2c5e00-cc90-11ea-9d33-3144b6bb191f.png)

**Comment by SlayksWood** [comment]
Seems minimap a little overlap it. So just place some object under button and mouseover green part of ecopedia icon:
![image](https://user-images.githubusercontent.com/45708377/88280283-2f88d200-ccee-11ea-8056-c588a0e532a3.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 277

https://images.zenhubusercontent.com/47210472/413a31ad-5eb4-4d83-bf70-a6cab6193f03/3c87a71c3e8b1aa38d2dca5f62c7db3d.mp4
