### ISSUE TITLE
[0.9.0.0 beta staging-stable-7] Election tooltip : write if "Majority required for instant win" require "Minimum Election Hours ?"

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17239]
Current tootltip:
![image](https://user-images.githubusercontent.com/339611/88243688-83b19900-cc91-11ea-84bc-ee18283bdd44.png)

**Comment by matheod** [comment]
(I think it's difficult to understand everything, and the only way to be sure is by doing test, maybe the ecopedia should add more information about how voting work, maybe with a timeline or some sort of diagram).

**Comment by WeaselDog** [comment]
Fixed in 9.1 with https://github.com/StrangeLoopGames/Eco/commit/add74f9c348d53e6577fd3dddd61c25eeb2ecf24
