### ISSUE TITLE
[0.9.0.0 beta staging-stable-7] Admin can't use dev command

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17237]
I don't know if this is a bug, this might work as intented.

Step to reproduce :
- create a new game
- give yourself admin rights
- try a dev command like `/civics spawnlaws`

Expected result :
The command is executed

Actual result : 
We are told we do not have permission to execute the command

**Comment by SlayksWood** [comment]
This is intented behavior. If you have any wishes about moving some commands for use by admins, you can write about it.
