### ISSUE TITLE
Diqus website links back to 404 tree links

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17240]
On Eco page on Disqus website: https://disqus.com/home/forum/strangeloopgames/
Clicking on Comment Title ("Eco Updates: Laws")
Sends user back to: https://accounts.play.eco/updates/laws

This page doesnt work, nor on develop server.

**Comment by denysaw** [comment]
Fixed, but surely only on develop/staging. As prod site doesn't have updates yet, but I hardcoded prod url there to not to mess up Discord with develop/staging comment threads.

**Comment by denysaw** [comment]
@j3fffff First fix was working for intro posts, but as it appeared only for 1 word ones. So only `Towns And Nations` failed, Laws (initial issue example was working perfect). Now fixed that also.

**Comment by denysaw** [comment]
Although, this thread is incorrect and should be deleted:
![image](https://user-images.githubusercontent.com/5720101/91068559-c8d03e80-e634-11ea-9cf9-01b673813258.png)

As right now we have no top-feature `Elected Titles`, only Titles and Elected Titles as sub-feature of it.
Seems it's some old discussion link, which was commented before moving Elected Titles under the Titles feature.
@j3fffff If you have possibility, please delete it ;) Thanx!
