### ISSUE TITLE
[Website] checkbox to agree to terms when buying / upgrading / inviting look unchecked when checked

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17245]
Step to reproduce:
Either try to buy / upgrade / invite and try to click on the checkbox to agree to term

Expected:
The checkbox is checked

What happen:
nothing will happen visually : the checkbox will seems unchecked. You will however be able to buy / upgrade / invite as the checkbox is technically checked. Unless you try to click a second time and then try the submit button and then giveup :D 

Tested on Google Chrome `Version 84.0.4147.89 (Build officiel) (64 bits)`,

**Comment by D3nnis3n** [comment]
Merged with #17294
