### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Web - Vulnerability - Script in comment are executed

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17254]
Step to reproduce:
- Open the Web UI and open a page where you can comment (exemple : law vote)
- Write `<script>alert(42)</script>`

Expected:
- The comment contain  `<script>alert(42)</script>` in plain text

Actual:
- The script in comment is executed and an alert appear

![image](https://user-images.githubusercontent.com/339611/88348902-eddc4380-cd4e-11ea-8e87-3285bf6a2e2d.png)

**Comment by beastyn** [comment]
Still here, please, check again

**Comment by beastyn** [comment]
oooops, didn't get this into build
