### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Shop UI leaving one item

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17253]
In existing shop remove all items from either sale or buy.
the last deleted item persists with a button over its head
![image](https://user-images.githubusercontent.com/38317412/88345616-ffbde680-cd4e-11ea-8e51-e9d8e7e8fabb.png)

**Comment by SlayksWood** [comment]
dup #17108
