### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Notification blocking screen

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17250]
Notifications from law effects on actions are blocking screen on every action with huge bloated notification windows as seen below.
Recommendations, move them into notification bell system to remove spam in front of the user and leaves a bad experience.
![Screenshot_244](https://user-images.githubusercontent.com/24981362/88331326-15221900-cd2d-11ea-9d4e-028f2bdaaf1f.jpg)

**Comment by SlayksWood** [comment]
merge to #17055
