### ISSUE TITLE
v5.6 game crashes when joining

### ISSUE THREAD

**Issue by Ueland** [StrangeLoopGames/EcoIssues#1726]
The server i play on got restarted for the tree leaves fix, when rejoining  my client crashed with a recommendation to send this to you guys.

https://www.dropbox.com/s/xvl2dcngpfqzwz7/2017-06-24_185720.rar?dl=0

**Comment by MarjieAVolk** [comment]
Another one of these:
Crash!!!
SymInit: Symbol-SearchPath: [...]

Duplicate of #1734
