### ISSUE TITLE
 [0.9.0.0 Staging-stable-8] Steam Tractor Harvester stops harvesting.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17268]
Harvester implement stops working after a little bit of time. 
Harvest 400-700 plant fibers, stops working - Solved by turning harvester off / on again using key bind.

**Comment by SlayksWood** [comment]
@IcedForge Thank you for the report. I can't investigate it until vehicles will fixed.
but do you have enough space and weight in steam truck?
Can you provide log files when it happens next time and maybe video?

**Comment by IcedForge** [comment]
Yes, the harvester works overall just fine, It just stops picking / harvesting plants after a while; it feels sporadic but a quick stop/start harvesting action starts it back up and it keeps harvesting. Its pretty reliably happening. Not at my current rig and this pc cant handle Eco and recording at the same time XD will see if i can do it when i get back home by the weekend.

**Comment by TwixterZ** [comment]
Hi @IcedForge, Issue is tested on 9.5 Staging build and confirmed no longer persist.
