### ISSUE TITLE
Make a command to pause pollution

### ISSUE THREAD

**Issue by StanKryvenko** [StrangeLoopGames/EcoIssues#17266]
@RobertMangano would like to have a command to pause pollution spread.
It would be better to make a command like "/pollution pause" and "/pollution unpause" or "/pollution continue"
Pollution should be paused at least for GroundPollutionSpread layer.

Also, we have this command finished: https://github.com/StrangeLoopGames/Eco/pull/6432
It removes GroundPollutionSpread from blocks in an area

**Comment by beastyn** [comment]
Check after #7483
