### ISSUE TITLE
[9.0 Staging-stable-8] Work party, general Skill requirement: level not functioning

### ISSUE THREAD

**Issue by Danevolent** [StrangeLoopGames/EcoIssues#17260]
![image](https://user-images.githubusercontent.com/32351822/88377678-c1700800-cdde-11ea-8200-2bcf88a6e18b.png)
Setting required level of a skill doesn't work. At least in this instance.
The number value was set to 7. Also the skill value seemed to accept greater than 7.

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1678:
![image](https://user-images.githubusercontent.com/45708377/88395259-7697c580-cdc9-11ea-81d8-02f2d0b43926.png)
![image](https://user-images.githubusercontent.com/45708377/88395275-7d263d00-cdc9-11ea-8d62-d96d2acbc292.png)

**Comment by Danevolent** [comment]
That one works, but not this one 
![image](https://user-images.githubusercontent.com/32351822/88406204-82a67600-ce0f-11ea-9dfc-a8441081677c.png)

**Comment by beastyn** [comment]
@Danevolent still working for me. Is there a way to get a log from session with this error?
 
![bandicam 2020-07-27 15-16-32-745](https://user-images.githubusercontent.com/27898520/88531405-3bd99b80-d01c-11ea-92d2-e26b972a0326.jpg)

**Comment by Danevolent** [comment]
I see, I attempted to repeat the situation.

It actually happened when I selected multiple skills.
In which case this occurs "2 NotAllowedInInventories Skills"
![image](https://user-images.githubusercontent.com/32351822/88535177-a86a8f80-d048-11ea-880b-7701b3fa1e2f.png)
![image](https://user-images.githubusercontent.com/32351822/88535195-af919d80-d048-11ea-9698-dc657b9ee25a.png)
Which I then noticed occurs because they were in different skill trees
![image](https://user-images.githubusercontent.com/32351822/88535412-fb444700-d048-11ea-9b9d-74e65165a8c0.png)

My first attempt to repeat the original bug, didn't succeed.
However after trying to change the values after initial selection, it seemed to occur again
![image](https://user-images.githubusercontent.com/32351822/88535577-537b4900-d049-11ea-9902-1649c3eeb11d.png)
![image](https://user-images.githubusercontent.com/32351822/88535586-5a09c080-d049-11ea-8750-415da4adb936.png)

How would I get a log from session?

**Comment by beastyn** [comment]
@Danevolent Sorry for the looong answer.
If you are still taking part in they playtest you can check it again? as some UI issues were fixed.
Would be pretty much appreciated.

**Comment by beastyn** [comment]
Close due no response
