### ISSUE TITLE
Server Renaming Game.eco file

### ISSUE THREAD

**Issue by KyeEco** [StrangeLoopGames/EcoIssues#1727]
hey guys, for some reason, my server shuts down, restarts and has renamed the Game.eco file and added some kind of extention like, Game.eco.offuhd9.498ygdf then procceds to make a new game.eco file, i also have crash files as well, if you could let me know if its a client or hosting issue that would be wonderful

thanks, Kye

https://www.dropbox.com/s/53oisijaf8vljq8/kye%20server.zip?dl=0

**Comment by metachronism** [comment]
sounds like an antivirus or some other program interfering with the file

**Comment by KyeEco** [comment]
We have private hosting through ping perfect, so not 100% if a firewall or another program could be the possible issue, if it doesnt seem to be client side but hosting side ill take it up with them, but i wasnt sure if any other players where having the same issue :)

**Comment by metachronism** [comment]
the server will make .tmp files when saving out the world, which then are immediately renamed to game.eco replacing the last save.  This is just to prevent any corruption that could otherwise occur.

closing as cant otherwise reproduce this issue
