### ISSUE TITLE
0.9-1679 Backpack keep hint about old items

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17275]
![изображение](https://user-images.githubusercontent.com/4980243/88464621-03737980-cec5-11ea-8173-7ac076990dd7.png)
![изображение](https://user-images.githubusercontent.com/4980243/88464625-0a9a8780-cec5-11ea-8bd8-60a5c41ee834.png)
![изображение](https://user-images.githubusercontent.com/4980243/88464630-15551c80-cec5-11ea-9a8b-bae5a4e0bdf3.png)

**Comment by Engimage** [comment]
This issue is actually related to all backpack contents, not just equipment slots.
I have mentioned it in #15802 which is now closed as (3).
When you move an item from the slot, that slot often will still display hint for the item that was removed.

**Comment by SlayksWood** [comment]
dup #9344
