### ISSUE TITLE
0.9 localization - "ID" + "User" should be one string there

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17279]
![изображение](https://user-images.githubusercontent.com/4980243/88464807-5d287380-cec6-11ea-819a-ef7adc624bee.png)

**Comment by Quadbro** [comment]
This is an autogenerated tooltip section for all objects that have ID, so i can't just add a case for User.

**Comment by elfl0rd** [comment]
No way to fix|change this behavior?
It makes correct localization is impossible :(

**Comment by mirasrael** [comment]
For now unfortunately it can be done. In future we can extend system to support additional formatting info, so you will be able to specify form of word used in string.
In example now it looks like:
"{Entity.DisplayName} ID"
With extended localization support it may be like this:
"{Entity.DisplayName:Genitive} ID"
Then in localization you can set:
User - пользователь
User:Genetive - пользователя
etc

**Comment by elfl0rd** [comment]
Any issue|feature about it?
If no maybe open this issue and add to backlog?

**Comment by mirasrael** [comment]
Opened new issue for this
