### ISSUE TITLE
0.9 "mask" slot in backpack has backpack icon

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17277]
![изображение](https://user-images.githubusercontent.com/4980243/88464684-6bc25b00-cec5-11ea-93e3-c09ca9b0d574.png)
![изображение](https://user-images.githubusercontent.com/4980243/88464687-754bc300-cec5-11ea-9562-43c53ac68dbb.png)

**Comment by SlayksWood** [comment]
merged to #15221
