### ISSUE TITLE
Concrete Kiln with full Smoke/no pipes crashes server

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1728]
Using Pingperfect for a dedicated server, 3gb ram, higher priority CPU. 
the 5.5.6 version of the game released
The issue we found and corrected but wasn't able to fix the main problem. We had a concrete kiln creating 40 products and every 5 min or so will crash the server. We found that the pipes weren't connected and the buildup was at 100%. there was a ceiling right above the thing and it was placed on the wall above another device. The person created the product without or forgetting about the pipes being connected. I read the error thing and we talked and found where the issue was and removed it, placing the concrete kiln somewhere else and added pipes. it's working fine now. 

If you need to get a hold of me directly I'm Fr3aKeD in your discord server and email is Fr3aKeD@gmail.com

[crash reports.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1101544/crash.reports.zip)

**Comment by Fr3aKeD** [comment]
Now i'm not quite sure what's going on. The screenshot there... the 2 pipes on ground WAS FOR SURE connected to the pipes above to make a connection i seen it like 20 seconds earlier then i go back in and pipes where there with smoke coming out...


[![https://gyazo.com/feb18dcd8ff950bcf756d36056971ac5](https://gyazo.com/feb18dcd8ff950bcf756d36056971ac5/raw)](https://gyazo.com/feb18dcd8ff950bcf756d36056971ac5)

[Crash 06265553.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1101603/Crash.06265553.zip)

**Comment by Fr3aKeD** [comment]
Trying to pinpoints exactly what is going on, looks like blast furnace are crashing server but not quite sure. We stopped ALL crafting using pipes. Which sucks when the best foods are using stove lol

**Comment by SeanAtr0n** [comment]
Was the server especially laggy at the time when these crashes occurred?

**Comment by Fr3aKeD** [comment]
No, no lag that we are aware of. we have 3 gb ram so, i don't know if that might have helped? :)

**Comment by Fr3aKeD** [comment]
Also, the crashes did stop after we seperated all to single pipes. We are keeping eye out, if crashes happen i go looking for devices, which sucks cause usually when they start it's every 5 min or so and sometimes i get booted back a hundred or so blocks. Constantly using the /tp coords feature from Clay mod. :)
