### ISSUE TITLE
0.9-1679 food tutorial - overlap

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17281]
![изображение](https://user-images.githubusercontent.com/4980243/88465118-fbb5d400-cec8-11ea-9277-5014afbc4275.png)

**Comment by SlayksWood** [comment]
in english too.
![image](https://user-images.githubusercontent.com/45708377/88652320-54f15380-d0d3-11ea-84d4-d58ae1ad8bde.png)

**Comment by SlayksWood** [comment]
This window is strange too ![image](https://user-images.githubusercontent.com/45708377/88652491-97b32b80-d0d3-11ea-8123-00b5f45534e0.png)
