### ISSUE TITLE
0.9 localization - "constructed" should be different string than one used in laws.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17280]
(map - world - constructed)
![изображение](https://user-images.githubusercontent.com/4980243/88464842-9eb91e80-cec6-11ea-94df-af0b2c4cb9e8.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/116847857-1bb2ba80-abf4-11eb-9202-a461cc8b23a9.png)
