### ISSUE TITLE
My sales/purchases list display

### ISSUE THREAD

**Issue by Xandoria** [StrangeLoopGames/EcoIssues#17304]
Could you please sort my sales/purchases list so that the most recent events appear immediatly and not the oldest. It is very difficult to open the 50 more links at the back of the page and then scroll down that very long list with my mouse wheel to check who bought all those steacks from my shop when I was offline...

**Comment by SlayksWood** [comment]
@Xandoria 
Do you talk about transaction window? We already changed this behavior since May,12. 
@D3nnis3n seems this issue was ficed with https://github.com/StrangeLoopGames/Eco/pull/6275

**Comment by D3nnis3n** [comment]
Wow, didn't notice that. Great, your suggestion has already been implemented - issue closed :)
