### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Project bugs when changing modules

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17315]
I had a big project in my Kitchen. In the middle of the project I took out its module (ADUP 4) to craft Advanced Cooking 5 module in this kitchen, moved the module project to be first and labored it. Then I had to afk for an hour. The module completed, and existing big project contonued without module installed.
When I came back I found the module and installed it. However the project was left in the weird state
![image](https://user-images.githubusercontent.com/38317412/88554228-efe42200-d02e-11ea-80e4-abacf686dc14.png)
Same with other projects on other kitchens.

Generally the resource bar is pretty filled up, but the table is not really producing anything.
On the attached screenshot is the kitchen that is out of resources, but the time bar moves.
In another kitchen there are resources available in stock, however the time bar is not there at all, and the table is not producing anything.
![image](https://user-images.githubusercontent.com/38317412/88554399-26ba3800-d02f-11ea-84fa-144cc710a199.png)
Maybe they will start doing something later on, but for a considerable time nothing has happened.

Relog did not fix anything.

**Comment by mirasrael** [comment]
@Engimage can you reproduce it on local server and attach game save?

**Comment by Engimage** [comment]
> @Engimage can you reproduce it on local server and attach game save?

I will try to do that if I find time.
However I could see the longer the project the more time it seems to be idle. For my 10 hour project the total time was showing like 18 hours and did not recalculate when the module was inserted.

**Comment by Engimage** [comment]
Could reproduce 100% by doing the following:
1. Insert module
2. Start the project, labor it. Lets assume project takes 8 hours (in this save).
3. Remove the module
4. Stop the production by either adding another project ahead, or disconnecting storage.
-  When active item finishes crafting the project stops, becomes blue-ish. However after a couple of seconds projects starts "working" again with doubled timer (16 hours in this case, like there is no module). The timer is ticking but nothing is produced.
5. Plug module back, connect storage back
- Project remains in this weirds state, not working, with timer still ticking at 16h, probably waiting until timer reaches the values with module (8h), but during next 8 hours it will produce nothing.

I guess interrupting the project will fix the values, but this re-calculation should probably be triggered immediately upon module operations.
[Project Bug.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4983833/Project.Bug.zip)
