### ISSUE TITLE
 [0.9.0.0 beta staging-stable-8] Laws: Unable to pick "Land Claim Paper" in filter for Trade trigger

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17317]
Land Claim Paper is not showing up in item filter for Trade Trigger. 

![image](https://user-images.githubusercontent.com/982322/88570072-bd8cf180-d03b-11ea-8783-b39d43e7b946.png)

**Comment by WeaselDog** [comment]
@ptitducanh The issue is these items class names are called PropertyToolItem and PropertyClaimItem. Land Claim Stake & Land Claim Papers are their friendly name.

Let me know if you have questions, I was about to do this one.
