### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Laws: Title filter display seems broken

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17318]
Hovering over the titles for tooltip displays this error: 

![image](https://user-images.githubusercontent.com/982322/88570391-486dec00-d03c-11ea-9158-ea96335bd45b.png)

**Comment by SlayksWood** [comment]
fixed  with https://github.com/StrangeLoopGames/Eco/pull/6366
