### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Skill Requirements for demographics is broken

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17319]
Picking skill requirements for demographics doesn't do anything. The other condition types seem to work.

[https://www.dropbox.com/s/mdrlq3aaspntkq2/Desktop%202020.07.27%20-%2019.31.26.03.mp4?dl=0](https://www.dropbox.com/s/mdrlq3aaspntkq2/Desktop%202020.07.27%20-%2019.31.26.03.mp4?dl=0)

**Comment by SlayksWood** [comment]
Apparently another problem with pooling which is not present in staging-1686.
@henrikolsson 
You have error in Development console. Can you provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Do you have this problem after restart game?

**Comment by henrikolsson** [comment]
Yes, problem persists after restart.
Logs:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994786/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994787/Player.log)

**Comment by IcedForge** [comment]
Cannot reproduce since release; will close for now please report it if you run across it again.
