### ISSUE TITLE
[0.9.0] Contract Scrolling Issue

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#17312]
If you scroll the diffrent Clause in the Contracrboard you scroll the complete UI 

https://drive.google.com/file/d/1us1izR0SOkWDjtPP6yfEHEakaWTYbeqx/view?usp=sharing

**Comment by serpopov** [comment]
That needs to explain expected behavior

**Comment by SlayksWood** [comment]
Set UI scale = 165%. I can't see all clause list. And we need to add scroll to this list:
![image](https://user-images.githubusercontent.com/45708377/90004564-8571e980-dc9e-11ea-8d4c-a835e92a7659.png)
![image](https://user-images.githubusercontent.com/45708377/90004600-928ed880-dc9e-11ea-81b8-38bf73f866c9.png)
