### ISSUE TITLE
Alpha 5.6 - Possible issue with Laws

### ISSUE THREAD

**Issue by nitehawk** [StrangeLoopGames/EcoIssues#1731]
Game Save file:
https://drive.google.com/file/d/0B65z7yXcGB4qLTVWbGxjbEJ4TW8/view?usp=sharing

Crash dump file:
https://drive.google.com/file/d/0B65z7yXcGB4qTWt3TUxHUEtsZms/view?usp=sharing

The start of this particular issue came about when I tried to update my EcoSim.eco config to fix Birch/Cedar tree seed drops.   I stopped my server, hosted on killservers, updated the SeedRange options, and tried to restart the server.

There are a number of potential issues at play, however, I'm told that there are efforts to track down an issue with laws in 5.6, so I'm including this in case it helps.

Potential issues:
* 150x150 world
* Laws (1 law related to killing wolves)
* Potential for wrong version of ClayTK being installed

**Comment by MarjieAVolk** [comment]
The crash is in loading the Legislation object - @metachronism, is this caused by the missing Serialized annotation that you added recently?  Has that fix been released?
