### ISSUE TITLE
[0.9.0 staging-1686] Filter: shows only discovered by you

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17314]
1. Server has brick discovered
2. You don't see brick in the item filter (without show discovered check box.)
Seems like it will show a brick only if you discovered it locally.
![bandicam 2020-07-27 16-53-31-804](https://user-images.githubusercontent.com/27898520/88543756-dee8e000-d031-11ea-8828-25457d0ca064.jpg)
![bandicam 2020-07-27 16-52-42-145](https://user-images.githubusercontent.com/27898520/88543762-e01a0d00-d031-11ea-89d7-73929f703e96.jpg)

Item filter always should show everything discovered on the server.

**Comment by Engimage** [comment]
This has been a pain on the playtest

**Comment by johnkslg** [comment]
maybe the list isnt updating, check if the clients list matches the servers list via breakpoints.

**Comment by beastyn** [comment]
Yeap, seems to be fixed somehow. Thanks.
