### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Vehicle sent flying to space if log off driving

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17322]
Steps to reproduce
- Drive a Steam Truck for example, on MP server.
- Log off while driving, or crash
- Log back in and watch space trip.

Has been an issue since... 9.0 playtest started I guess.

**Comment by D3nnis3n** [comment]
(Wrong button, sorry)

**Comment by beastyn** [comment]
Yeap, its back
