### ISSUE TITLE
User, who was invited before now unable to login

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#17328]
Getting 500 error when trying to login on staging. Observed by @D3nnis3n

**Comment by beastyn** [comment]
Checked on staging.
Account 1 has sent an invitation to the account 2 (not registered)
Account 2 has registered with the kink from a letter
Account 2 try to log in and has this
![bandicam 2020-07-29 09-41-22-969](https://user-images.githubusercontent.com/27898520/88757796-4ca32200-d180-11ea-8e50-a54188cb3c71.jpg)

**Comment by denysaw** [comment]
Really, fixed

**Comment by beastyn** [comment]
Sorry, not sure if its for you. But I'm fine with the web right now, but I have this error in game.
Trying to login on staging with account which was invited.
![Uploading bandicam 2020-08-04 10-15-12-583.jpg…]()

**Comment by denysaw** [comment]
Re-tested once again on stagingland. Worx as a charm. Some photo proof:
![image](https://user-images.githubusercontent.com/5720101/89471766-46640580-d77f-11ea-9937-3323d147ddf8.png)
![image](https://user-images.githubusercontent.com/5720101/89471773-4a902300-d77f-11ea-89c6-4fc4d5cf73c5.png)

@beastyn Please, re-test ;)

**Comment by beastyn** [comment]
I will make other issue for game auth part
