### ISSUE TITLE
Jenkins failing with no explanation in PR

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17326]
![image](https://user-images.githubusercontent.com/3536496/88589005-51939480-d00d-11ea-882e-3fc8e4dd3727.png)
In https://github.com/StrangeLoopGames/Eco/pull/6470

**Comment by redwyre** [comment]
Unfortunately I didn't think to check this right away and the build log has been discarded. It looks like this could occur when unity fails to build, but it isn't a code error. I do have plans for much better logging but it will take a bit more work than I'm willing to spend right now, so I'll bump this to 9.1. If it happens again we can bring it back.

As always the full log is available by clicking on the X next to the change id, or clicking the link in the checks section down the bottom of the PR.

**Comment by redwyre** [comment]
Looks like one case is the build timing out
