### ISSUE TITLE
Steam authentication going down should not disconnect players

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17329]
We have a problem that players get kicked from games when Steam Authentication goes down and are unable to reconnect. It is still possible to connect using our standalone build. When this happens, the error message is ambiguous if it is on Steam's end or our end.

We should find a solution to prevent people from getting kicked when Steam Auth goes down. If possible, we should make the error message very clear it is on Steam's end when unable to connect for this reason.

**Comment by johnkslg** [comment]
Other games do not have login blocked during Steam maintainence. Figure out why we do. I can email our steam contact if needed.

**Comment by redwyre** [comment]
Looks like the server is re-verifying every 15 minutes, we can make this more forgiving

**Comment by johnkslg** [comment]
15 minutes is good, just make it more tolerant of unreachable steam 
Or better yet change the method to match what other games use so it doesnt go down at all.

**Comment by redwyre** [comment]
Yeah I didn't touch the 15 min checks, but now steam verification doesn't need to contact steam servers.

So servers wont be affected by steam going down, but still will be affected by our auth server itself going down.
