### ISSUE TITLE
Trees grow where they shouldn't

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#1732]
In 5.6 i'm having an Issue with trees growing on / in stockpiles and also on farmed plots of land which currently are growing a plant e.g. a tree growing where wheat is already growing then it stops the plant from growing / being harvested

**Comment by Amphysbaenas** [comment]
Same in 5.6.1. Solution is to use the road tool before puting the stock pile

**Comment by Nanders** [comment]
This might be fixed with the new occupancy changes, will test.

**Comment by ecoemmeck** [comment]
This is still a thing. Trees are removing crops planted in a field in alpha 6

**Comment by MarjieAVolk** [comment]
Gonna track this over here: https://github.com/StrangeLoopGames/EcoIssues/issues/2110
