### ISSUE TITLE
[Balance] Campfire Cooking issues

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17339]
I have been a main cook on the playtest this run.
I did struggle very hard trying to feed people. Here is my analysis as of why.

Here is a spreadsheet with data related to campfire cooking
https://docs.google.com/spreadsheets/d/1lPYLu_tLQfXykIEJm-fYlGgAFfm-sAUq0lhovnyLkqE/edit?usp=sharing

So early game every profession has low skill level making them consume huge amounts of calories.
However there is a charred food that everyone can produce internally. By making 2 campfires any profession can easily feed themselves by gathering payayas (meme) and hunting animals (anyone can do) so people generally prefer doing it themselves early as they have not got much to provide.

So by picking campfire coocking profession you can only be useful to a prebuilt group where you can be somewhat useful.
And you are useful due to saving calories on charring the same food.

Then we come to Fried food. The current issue with those is the amount of Fat required. In early stages this requires Butcher to be operational, and also we have to understand that only BU1 is available at this point meaning near to 0 cost reduction. More advanced modules will only be available when Mason levels up which is pretty slow.
So Fried food will require 6 raw ingredients, not to mention more complicated crafting process which will definitely require Render Fat.

When we go to salads, another problem emerges. And this is just amount or raw resources required per one dish. Compared to charred food which is so easily obtainable, salads, while still providing far from fantastic stats both nutrition and calorie, will require **16 raw resources**, and in all cases those require some type of Greens, which are the most difficult to obtain of all farming crops. Only Fern can be picked up, while others will require Scythe, and there is no way to plant many of them soon enough. Don't even mention Beet Greens, which are the rarest of them all, while recipe requires A LOT of them, and Beet greens are not used anywhere later in the game.

You can tell - but they are effected by modules! Trust me, when BU3-4 are a thing, Cooking already kicks off completely outshining Campfire Cooking by all means. The only thing that will change in the early game is crafting time - mostly due to level 3 abysmal perk.

Then we come to the "top" Campfire Cooking recipes - stews.
They still require a lot of raw resources, but also require charring them (adding calory cost and time), and also have a requirement of a butchery, this time also with two steps.

What I have to say here. While being a stubborn one, and far from lazy, I was completely struggling to keep up here from all possible standpoints.
1. The amounts of crops needed to craft. Farming did not kick in yet, you have to rely on gathering. But even with gathering skill there is not much food available in the world, excluding Rainforest.
2. The speed of crafting. Even with level 3 perk and some modules I just could not keep up with production, and chopping logs at least for fuel. And if you don't have a cooperative gatherer then you are screwed.
3. Due to increased amounts of raw materials the price of the food is significant, making its use a priviledge and not a benefit for any citizen.
4. The amount of Tallow required across all recipes is insane and does not correspond to what you could naturally get.
5.The choice of crops is a pain. Most of them are not replenishable without heavy investment from the farming profession, which just can not happen at this stage of the game.

So what do I want to say here. Campfire Cooking is the early game profession. I highly doubt that it should require any butchery products. All recipes cost should be at least halved and some ingredients revised. While usage of Tallow is fine, the amounts should be considerably lowered. Stews should probably use Charred Meat instead of Scrap Meat as a natural progression and reuse comfort.

**Comment by SlayksWood** [comment]
some changes we've already done here https://github.com/StrangeLoopGames/Eco/pull/6447
@WeaselDog seems we need some more improvement

**Comment by SlayksWood** [comment]
Seems this numbers are a little overpowered now, closed for now, just will discuss in disrocd.
