### ISSUE TITLE
[0.9.0 staging-1686] Crafting bar/resources don't always update

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17335]
Step to reproduce:
- Place Carpentry table, take 6 hewn log in hands (for on ecraft iteration):
![image](https://user-images.githubusercontent.com/45708377/88654354-eeba0000-d0d5-11ea-801b-f9e3cc3ebec1.png)
- start hewn log door order. Resources doesn't update in UI:
![image](https://user-images.githubusercontent.com/45708377/88654425-0abda180-d0d6-11ea-92cf-890e7cfa0b2d.png)
- add labor to this order. Craft bar and time doesn't update in red frame. In other(green) frame craft bars work correct:
![image](https://user-images.githubusercontent.com/45708377/88654574-3771b900-d0d6-11ea-9c42-0f560a51e90f.png)
- when craft will finish this bar will update too:
![image](https://user-images.githubusercontent.com/45708377/88654631-4ce6e300-d0d6-11ea-86dc-7b672e4f64cd.png)

**Comment by beastyn** [comment]
1. Is still here

I put my order, resources were taken BUT I see 6/6 in the interface. It will become 0/6 only after labor adding, But it should recount after taking my resources.
![bandicam 2020-08-17 12-52-14-176](https://user-images.githubusercontent.com/27898520/90371944-1d017e80-e089-11ea-8bf5-039f4fb7b6d2.jpg)
