### ISSUE TITLE
[0.9.0 staging-1686] Notifications: icons are slow after closing a window

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17337]
1. Make some notifications
2. Open a notification window
![bandicam 2020-07-28 14-57-28-647](https://user-images.githubusercontent.com/27898520/88659302-42d0de80-d0ee-11ea-929b-23baf539dcbe.jpg)
3. Close a notification window
![bandicam 2020-07-28 14-57-29-466](https://user-images.githubusercontent.com/27898520/88659321-49f7ec80-d0ee-11ea-99b0-cc1604afe272.jpg)

Icons will stay on screen for a sec

**Comment by gzatravkin** [comment]
CNR both unity/playtest. Still occur? Maybe it was fixed by tmpro changes

**Comment by beastyn** [comment]
yeap, didn't see anymore
