### ISSUE TITLE
[0.9.0 staging-1686] Crafting UI glitches

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17334]
- [x] 1. Dark stripe and light stripe have different width:
![image](https://user-images.githubusercontent.com/45708377/88637105-6716c600-d0c2-11ea-9e0d-813763e523ef.png)

- [x] 2. Sometimes string color don't update if you levelup or take specialty (String color remains the same, but the order is changed):
![image](https://user-images.githubusercontent.com/45708377/88643412-5702e480-d0ca-11ea-8325-f1dcb09690a8.png)
Just open some craft table and start to learn/specialize/levelup skills
You can see that 2 dark strings have line string between them, This seems to be why the first problem arises

**Comment by johnkslg** [comment]
When resorting happens, you should also redo the stripes.
