### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Crash when starting election to remove a law

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17344]
- Used the X button to remove a law in solo.
- Popup told me that I could only do that by launching election, I pressed the button to confirm that I wanted to launch the election
- Server crashed

[crashlogeco.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4990484/crashlogeco.txt)

- I then tried to reproduce the bug but it told be an election was already active (so the carsh happend after creating the election)
- I tried to deleted an other law and was able to do it without crash

**Comment by SlayksWood** [comment]
```
<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Elections.Election.FullDescribe()</size>
```

**Comment by beastyn** [comment]
Should be fixed. Please tell if meet again.
