### ISSUE TITLE
getting this crash dont know why

### ISSUE THREAD

**Issue by true2form** [StrangeLoopGames/EcoIssues#1734]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1104481/output_log.txt)

**Comment by MarjieAVolk** [comment]
Seen a couple reports with a similar crash log: "Crash!!! SymInit: Symbol-SearchPath:" followed by a bunch of files names and stuff I don't recognize.  After some googling, it seems this error is related to a missing or corrupt asset file of some kind, but I haven't made much more progress than that.

It may be relevant that just before the crash there's a message about unloading unused assets.

**Comment by MarjieAVolk** [comment]
Here's another one: https://gist.github.com/tyrope/f1bc78cd21522daedf068de2563d91e5
