### ISSUE TITLE
Froth Floatation Cell - Water flow issue

### ISSUE THREAD

**Issue by Zoneman81** [StrangeLoopGames/EcoIssues#17343]
The unit stops/starts the process, status tab indicate a lack of water flow, water not needed.
![20200728201553_1](https://user-images.githubusercontent.com/38038590/88705165-72dca980-d10f-11ea-9ae1-4be4e661deaa.jpg)
![20200728201554_1](https://user-images.githubusercontent.com/38038590/88705167-72dca980-d10f-11ea-94c1-6a40f46993a4.jpg)
Status tab just switches between those 2 attached screenshots, making the function of the machine slower by a factor of x10

**Comment by beastyn** [comment]
Yeap, just place a cell and launch an order

**Comment by Danevolent** [comment]
Ice Forge: Today at 17:49
Its tick update flows
as far as i can see it doesnt output waste
Behavior wise i can tell from the client side testing it; It checks for water flow then rechecks on 1 second into craft for another update and it disconnects / doesnt seem to detect a connection to a pipe
also tested connecting it to a waste filter and it gives 0 waste

**Comment by Zoneman81** [comment]
Its still has the same error, we have one on playtest server at 1290,91,104

**Comment by Zoneman81** [comment]
update, still not working, but we moved it to 1291,94,85
