### ISSUE TITLE
Sawmill Revamp - Model, Animation, Prefab

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17359]
- [x] Concept
- [ ] New Model + Texture + Animations
- [ ] Update SawmillObject Prefab

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/f7b37f20-7d34-4266-a3ee-02fbc5ed6c8b)

The sawmill is cute, but old and pretty outdated. Somehow, the animation (assuming there was one which I could have sworn there was) was lost, as well.

Time to revisit this asset! We should get a more realistic one, that takes up more room and is more like a sawmill you might lay a trunk onto, but I think it'd be nice to keep the sawblade pretty large/exaggerated, for the eco feel.

**Comment by RobertMangano** [comment]
![sawmill concept.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/f41ae24b-498c-4569-86ff-cbda01b51b1a)

**Comment by RobertMangano** [comment]
sawmill object added to staging and added to the eco scene
