### ISSUE TITLE
Modern Sign Collection [Add to Tech Tree]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17360]
- [x] Added to Tech tree w/ recipes
**Recipe Notes:** All these should require wood and metal, except StandingGlassSign which should also require glass, and StandingSteelBrickSign which should only require metal and brick (no wood).
- [x] Unity Setup (Object prefabs and icons in Eco.unity, art tested+fixed in-game)

Item+Object Names:
**StandingGlassSign
StandingSteelBrickSign
HangingLongSteelSign
StandingLongSteelSign
HangingSteelFramedSign
HangingSteelShopSign
HangingSteelMineSign
HangingSteelPlainSign**

- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Comment by Phlo123** [comment]
Blender renders.
![1.png](https://images.zenhubusercontent.com/5edf279448c519fc438646f4/48a5228b-e77c-4977-8aa8-0bab5366080a)![2.png](https://images.zenhubusercontent.com/5edf279448c519fc438646f4/3a6ce6fc-74d3-4a57-8f11-a0fd6d3f88eb)

**Comment by Phlo123** [comment]
![image](https://user-images.githubusercontent.com/17730996/90236046-e3cbd300-de2a-11ea-907a-bd921a343596.png)

**Comment by RobertMangano** [comment]
icons are done and added to sprite sheet 04 and sprite asset 04

**Comment by Sekor2600** [comment]
can not create Occupancy for the StandingLongSteelSignObject
always come like this
![grafik](https://user-images.githubusercontent.com/37456949/98423613-73ca9300-208f-11eb-9d0f-43a4cbfd0de1.png)
