### ISSUE TITLE
Modern Interior Lights Collection (Re-name to match tech tree)

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17362]
- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Comment by Phlo123** [comment]
Object/Prefab names.
KitchenMetalLampObject
KitchenWoodLampObject
ModernAbstractFixtureObject
ModernHangingFixtureObject
ModernHangingLampObject

**Comment by RobertMangano** [comment]
icons are done and on icon sheet 04 and 05
