### ISSUE TITLE
Housing Objects

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17363]
**9.1 Housing and Decorative World Objects (Signs, Doors, Lights, etc)**

9.1 will add a suite of new objects for players to use with their buildings and decorate with, including many types of metal and glass and modern signs, new light objects, and updates as well as additions to doors and decorative objects.

Phlo is doing most of the modeling and texturing for these assets,
Rob is doing concepts and icons (once the objects are finished)
Phlo can implement them in Unity (Rob could help with this too).

**Comment by elfl0rd** [comment]
As suggestion, can we have more fat powered street lights?
