### ISSUE TITLE
5.6 Contracts bug

### ISSUE THREAD

**Issue by Ryumidori** [StrangeLoopGames/EcoIssues#1736]
Hello there Devs,

today we started ussing currency so i was able to setup some contracts. 
1 person took one and went to my depot to deliver but couldn't.
at first there were no chest he could see, and when that was fixed by setting the chest public the contract didnt complete when he put it in the chest trough the depot.
I hope i have been clear enough on what happend and how, if not i am open to anwsering any question you may have on the subject.

Greetings,

Paul

**Comment by johnkslg** [comment]
Thank you, contracts will be much better in next release! Fixes applied.
