### ISSUE TITLE
Modern Door Collection

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17361]
We should get new doors that are designed to go well with the updated building materials of Flat Steel, Reinforced Concrete, Framed Glass, and Corrugated Steel.

The doors **don't have to be specifically made of those materials**, but should look good with the updated sets. 

- [x] Concept
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

**Comment by Phlo123** [comment]
Concept by Rob
![door_concepts_phlo](https://user-images.githubusercontent.com/17730996/98520588-e8adf080-227a-11eb-8315-66a176cfc188.jpg)
