### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] NullReferenceException and wasn't able to excavate any blocks until disconnected and reconnected to the server

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#17378]
Got debug spam of "NullReferenceException: Object reference not set to an instance of an object" when trying to excavate blocks in a ice biome. No blocks were getting mined or picked up. Disconnect and reconnect fixed it.

Removing the blocks with shovel and pickaxe worked. It was just the excavator.
Only seen once. Haven't been able to reproduce yet

Version: [0.9.0.0 beta staging-stable-8]

![20200729084635_1](https://user-images.githubusercontent.com/39825431/88766904-1f9f4100-d179-11ea-9863-1d3481987bb8.jpg)
[PlayerLogs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4993127/PlayerLogs.zip)

**Comment by IcedForge** [comment]
"Can't reproduce [0.9.1.0 beta staging-1813], closed for now and will reopen if we run into it again."
