### ISSUE TITLE
Crab Pot World Object [Add to Tech Tree] [Add Gameplay Code]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17373]
I'll let balance try to see if they can get this working without dedicated programmer help, you guys assign it to the code workspace if you need code help for it to get up and running with crabs.

- [x] Audio for Doors opening and closing on 'using' animation state. We might already have an acceptable creaky door audio that works fine for this!
- [ ] Added to Tech tree w/ recipes
- [ ] Gameplay Created for it to catch crabs like the fish trap catches fish.
Gameplay Notes:
This one is straightforward, we want this object to work just like fish traps do, but for crabs instead. It may need further updates to the prefab, feel free to re-assign Keegan to investigate on the art side if it can't be figured out on the code side.

- [x] Unity Setup (Object prefabs and icons in Eco.unity, art tested+fixed in-game)
- [x] Model + Texture + Animation
- [x] Prefab in Project
- [x] Icon

Crab Pots should be like fish traps but for Crabs!

Rob has already made world object art for a wooden crab pot, it'll need an icon too and a world object of course. 

Needs a prefab and the icon should be added to eco.unity as CrabPotItem

**Comment by RobertMangano** [comment]
icon is done , the item just needs to be plugged in

**Comment by keegan-o** [comment]
@RobertMangano 

Please add the icon to eco.unity as CrabPotItem,

and please setup the prefab to look as you want it to (right now the prefab has a blank material).

**Comment by Sekor2600** [comment]
Working on the Prefab![grafik.png](https://images.zenhubusercontent.com/5ec774ef9e621b3c4b663153/d3425ba5-28cd-41a1-b8ed-1e30d1eee3bb) @RobertMangano

**Comment by Sekor2600** [comment]
Problem with the Animation from the CrabPot
https://drive.google.com/file/d/1qQpfMMGof4CnRaYdBNE2x2kq5iSjCWeU/view?usp=sharing

**Comment by freakydna** [comment]
@keegan-o Audio added, can test when available in game.

**Comment by WeaselDog** [comment]
Added in upcoming 9.5 update
