### ISSUE TITLE
Street Light Hitbox impeding compact road designs

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17389]
![image](https://user-images.githubusercontent.com/25908592/88797704-08c21400-d1a4-11ea-821b-294f4faaf6b8.png)
Can someone fix the hitbox of these lights
it makes a working road structure really hard lol
my mirror is held by air there, while it can clip through other cars mirrors

**Comment by Sekor2600** [comment]
fixed in svn
