### ISSUE TITLE
[0.9.0 staging-1693] CW: no builds links

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17387]
This information has disappeared
![bandicam 2020-07-29 09-30-37-756](https://user-images.githubusercontent.com/27898520/88791519-4a0df000-d1b3-11ea-90f2-14fdaf05aad2.jpg)

Also, can we make it look better? Linux is not really matching here, under Windows maybe

**Comment by denysaw** [comment]
Fixed on *lands. For staging only Windows x64 version will be available. It's normal behavior as I got.
