### ISSUE TITLE
[0.9.0 staging-1693] Error disclaimer is off

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17388]
1. Create a law with Didn't vote trigger
2. Choose Prevent in Then section
3. Error sign will be displaced
![bandicam 2020-07-29 16-44-19-498](https://user-images.githubusercontent.com/27898520/88796247-c821c500-d1ba-11ea-8d52-da64c5bf9908.jpg)

**Comment by beastyn** [comment]
Also in Amendments
![bandicam 2020-07-31 12-15-24-333](https://user-images.githubusercontent.com/27898520/89011293-8cf1d400-d329-11ea-894b-f6876830bf76.jpg)

And Capitol won't use it too
 - Place capitol
 - Delete all articles
 - Create a new article
No disclaimers for mandatory fields

**Comment by johnkslg** [comment]
@sergey can you advise Duc on this one

**Comment by ptitducanh** [comment]
@beastyn @johnkslg 
The Capitol UI uses WorldObjectPanel and it doesn't support showing error marks. 
So if we need error marks in this UI I have to change WorldObjectPanel logic and it's kinda risky since we're about to publish 9.0.

**Comment by beastyn** [comment]
@johnkslg I will push it then for 9.1 Government epic.

**Comment by beastyn** [comment]
It still worke in a strange way.
1. I have a new article. It says me that I need ti fill Applies to field. That's fine.
![bandicam 2020-09-25 15-19-07-984](https://user-images.githubusercontent.com/27898520/94255998-8dca6f00-ff42-11ea-89bc-bf517645da4b.jpg)

But I don't see a field error if I choose Applies to. Thought the error at the top is telling me that I need to choose Executors or Proposers. All fields here should be with an error mark. And when Proposers OR executors will be filled errors should be gone.
![bandicam 2020-09-25 15-22-08-936](https://user-images.githubusercontent.com/27898520/94257965-91abc080-ff45-11ea-9cb7-0ce426649e57.jpg)

2. The same goes to Laws and other.

I really think that we should SHOW which fields are causing errors precisely.
Tell me if refactoring is too hard and dangerous. 9.1 is for bug fixing so we can push it.

**Comment by johnkslg** [comment]
it does show when the fields are bad, when there is only one. 
When there are multiple, it doesnt. To support this will require some refactoring.
I would make it as so: make two PropErrors, one pointing to each property that together is in error. 

Also, whats with that exclamation point sometimes having a black background and sometimes not?  I think it would be better if it had neither, a circle background instead.  Ask @milenko for something improved.

**Comment by beastyn** [comment]
@MilenkoTunjic then I will wait for your advice on these icons. Thanks!

**Comment by johnkslg** [comment]
I've fixed the constitution one. For the issue where it shows the error at the top instead of by the params, I propose 'wont fix', its clear enough they can mouse over and read it and will require a big refactor

**Comment by johnkslg** [comment]
@SlayksWood Can check latest state to verify errors display well enough

**Comment by SlayksWood** [comment]
Capitol fixed. Disclaimers are used no deeper than a section or article. Closed for now.
