### ISSUE TITLE
 [0.9.0.0 beta staging-stable-8] Elected title invalid for unclear reasons

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#17392]
It says property missing from wages, but everything looks filled in?
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994967/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/4994968/Player-prev.log)

![image](https://user-images.githubusercontent.com/982322/88802961-11b6e380-d1ac-11ea-8a55-0560746d56d6.png)

**Comment by beastyn** [comment]
Thank you for the report.
I think account was concealed under the gear icon. 
It should be visible with the new update for the playtest.
