### ISSUE TITLE
Fix animation offsets and speeds

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17395]
Go through all animal animations and fix them for alignment and speed:
- Running speed on many animals does not match animation. Fix animation or speed.
- Weird offsets in amphibious animals like alligator and otter.

**Comment by swapnilnegi** [comment]
![image](https://user-images.githubusercontent.com/68607957/88888766-8e08ff80-d25c-11ea-98ee-1f38d45a29fe.png)
Apart from these, I think we have added some recently?

**Comment by mirasrael** [comment]
You can check by Animal derived classes.
![image](https://user-images.githubusercontent.com/475445/88894660-e2a67d80-d250-11ea-950f-bd95ae1a6a95.png)

**Comment by SlayksWood** [comment]
Still an issue for running Alligator.

**Comment by SlayksWood** [comment]
merged to #18000
