### ISSUE TITLE
Setup shared animation controller

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17394]
Currently, every animal has its own animation controller, meaning any change to an animal's animation control needs to duplicated literally dozens of times.  

Unity offers a solution for this with Animator Overrides: https://docs.unity3d.com/Manual/AnimatorOverrideController.html

Setup a single root animation controller which contains all the things animals can do, and is then overriden for the various animals with the correct animations plugged in.  Some animations will of course not be used in the overrides, if an animal is not amphibious for example those animations will just be left blank.

Then, setup all the overrides with the animations available to them.  Lots of animations not being used.

For creating the root animation controller, check out the wolf for an example of land walking to start with, it has the best rotation setup right now. Let me know if there are code changes needed for this, I'd like to keep close tabs on this one.

**Comment by swapnilnegi** [comment]
![image](https://user-images.githubusercontent.com/68607957/89045741-a61a7500-d369-11ea-87e6-6ea27eab3bd8.png)
Base controller for animals. 
Currently testing on terrestrial animals. (Wolf, Jaguar)
