### ISSUE TITLE
Allow using Images in own Ecopedia pages

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17406]
Ecopedia allows you to easily add your own pages just by adding some new files, but i haven't found a way to actually add in Images into these pages (like a Organigram for a Government Hierarchy or a Capital Layout). This would be a very nice feature for admins to make great descriptions and tutorials for their very specific servers in the Ecopedia.

Could you see if there is any possibility to enable us to use Images, either hosted third party or getting them into the server files to use them there?

Bonus Point: If that would also work for the category icons.

(John told me to open this request)

**Comment by redwyre** [comment]
It should be possible to put them in a unity package (client side mod) and reference them that way.

**Comment by thetestgame** [comment]
I have made a working example showcasing custom pages with category images. However properly associating client files with the banner image similar to the Eco Tree is proving difficult.
