### ISSUE TITLE
[0.9.0 develop-13] Highlight and news counter are offset.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17401]
Seems forgot to change after redoing UI
![image](https://user-images.githubusercontent.com/45708377/88897693-62821700-d254-11ea-9b73-3ca940d58574.png)

**Comment by gzatravkin** [comment]
Looks be fixed
![image](https://user-images.githubusercontent.com/53317567/89721941-80b8e700-d9b9-11ea-99cf-d8b35431b2d9.png)
