### ISSUE TITLE
Expanded Road Possibilities

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17408]
We've been having issues to find an aesthetically pleasing way to build a road due to how the sideline blocks work with connecting to each other.

This picture details it best:
![b](https://user-images.githubusercontent.com/25908592/88916730-e1804b00-d266-11ea-8a28-9c42c0195362.png)

Also, for two wide roads it's really hard to find any symmetric way:
![a](https://user-images.githubusercontent.com/25908592/88916706-d4fbf280-d266-11ea-885a-d730e908667a.png)

A solution to both is actually removing these linking sideline blocks and instead adding a wider variety of blocks that have white lines on the edges and that can be placed freely without the need to merge.

This would also allow to place two in the middle of the second picture, one with edge to the right and one with edge to the left to get a perfect middle line on a road that has an amount of asphalt blocks that is not uneven.

I'll also add to this issue a list of other useful road blocks in the future, but for now replacing the linking form with:
- A rotateable form with one edge stripe (For any outer side, when rotated or for a middle stripe with two blocks)
- A rotateable from with two edge stripes (For corners on any outer side when rotated)

would totally suffice to get the job done in a basic aesthetically pleasing way.

**Comment by keegan-o** [comment]
you'll want a rotatable corner line on outside too otherwise those types of roads wouldn't be able to make turns

**Comment by keegan-o** [comment]
Added these two forms into SVN, they will likely appear in 9.2.
