### ISSUE TITLE
Calculate ecosystem equilibrium states

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1740]
If we use this approach to simulate ecosystem populations, we may be able to use it to find/create ecosystems in equilibrium:
https://en.wikipedia.org/wiki/Generalized_Lotka%E2%80%93Volterra_equation
https://en.wikipedia.org/wiki/Community_matrix

**Comment by knexer** [comment]
This isn't quite the way I ended up taking world layers, but we could maybe still borrow ideas from this space in the future.
