### ISSUE TITLE
[ 0.9.0.0 beta staging-1695] Civics: Hunting Law block message alteration

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17413]
On user end notification on hunting law prohibition can be confusing as it states Reason : Succeeded ( why ) which can give the impression that you are supposed to be able to do it but its not allowed through legal action.
![Screenshot_11](https://user-images.githubusercontent.com/24981362/88952155-51a6c500-d297-11ea-85ce-540ef1c036c3.jpg)
Law used to prevent Hunting/Gathering action in specified district.

![Screenshot_12](https://user-images.githubusercontent.com/24981362/88952163-54091f00-d297-11ea-9b3e-7740eb02eaf9.jpg)
message recieved on trying to shoot an animal specified.

The law works fine as intended, but the end result user recieves may be confusing due to how it states a "success".

Expected result
Popup notification stating  : Reason : Prohibited, location X

**Comment by beastyn** [comment]
Its still a bit confusing with this 'succeeding' part.
![bandicam 2020-08-06 15-18-58-109](https://user-images.githubusercontent.com/27898520/89521040-38060000-d7f8-11ea-951f-69adcc4d5d23.jpg)

**Comment by johnkslg** [comment]
Tuned this:
when displaying one:
![image](https://user-images.githubusercontent.com/3536496/90079641-5454e180-dcbd-11ea-9511-a59a31b4036e.png)
![image](https://user-images.githubusercontent.com/3536496/90079638-4f902d80-dcbd-11ea-9fd1-2e028cc3c784.png)


and when displaying a few:
![image](https://user-images.githubusercontent.com/3536496/90079917-1c01d300-dcbe-11ea-82c2-061ed944e179.png)
![image](https://user-images.githubusercontent.com/3536496/90079911-173d1f00-dcbe-11ea-897f-38788e94344a.png)
