### ISSUE TITLE
[0.9.0 staging-1695] Tools lost durability line

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#17411]
![image](https://user-images.githubusercontent.com/38317412/88922610-041b5f80-d279-11ea-8e73-84f1f3ae8552.png)

**Comment by Conchipedia** [comment]
![snap7003](https://user-images.githubusercontent.com/29383891/88931277-88b7af00-d274-11ea-87f0-0817afb2d9c8.png)
Durability is going down just not visible on tool icon
