### ISSUE TITLE
[0.9.0 staging-1695] Water from pipes does not expand outwards

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#17419]
Water used to expand outwards after forming blocks upon exiting a pipe.
This no longer happens, as can be seen in the screenshot below.
This makes pumping water into aqueducts impossible.

If water is taken from a river, the water still flows properly and can be diverted using aqueducts.

Steps to reproduce:
1. Build a pump and connect it to a pipe with an exit above ground level.
2. Notice that water flows out of the pipe and creates a pillar of water that never expands outwards.

![image](https://user-images.githubusercontent.com/11805935/88961790-cb45af80-d2a5-11ea-9dd4-c156d9de673f.png)

**Comment by beastyn** [comment]
@MonzUn Thank you for the report, We have plans for the big water changes (#16648) and will take your opinion into considiration.

**Comment by NemoLArs** [comment]
This is an actuall bug that happend between 8 and 9. Water behaives different now in 9 than in 8. 

Here's a pic from 8.3 that shows how water "flows" compared to Monzuns pic from v9. 

![image](https://user-images.githubusercontent.com/32419758/89447237-f6247d80-d755-11ea-9e2d-7712bac61626.png)

**Comment by MonzUn** [comment]
Yeah, this is not an opinion, but a bug.

**Comment by beastyn** [comment]
Yeap, agree. It became worse.
So, that one #1424 is for update.

And this one we will use for repairing the ultimately broken behavior.
@redwyre It's just not flowing right now. At all.

**Comment by MeirionHughes** [comment]
I guess this is the reason piping water into a field doesn't raise its moisture? tried direct to soil, a basic hole (1 water block) and 1 water block surrounded by aquaduct - non of them raised the moisture level.

**Comment by MonzUn** [comment]
None of those methods have ever worked for raising moisture I think.
Running water in an aqueduct is the only think I think should work (Not sure even that affects it though).

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/102340779-f6f0da00-3fa7-11eb-9eff-4e10a08a05e3.png)
