### ISSUE TITLE
Premade Graphs not displaying all variables

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17422]
For example, pre made graph > population.
Should be displaying citizen, animal, plant, and tree populations. 
But current only displays tree population.
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/29876c0e-02df-4dff-ad8a-ca79a786ccb7)
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/e0fd46f9-d014-47b3-8fbb-0c8492156c7f)

**Comment by denysaw** [comment]
As I remember there's just no such data yet. There're just by-species Animail-, Plant- and Citizen Population. Is it correct, @johnkslg I remember you told they will be added soon, but I dunno if those were added already.

**Comment by j3fffff** [comment]
![image](https://user-images.githubusercontent.com/7343272/89060226-878b8e00-d317-11ea-8c7f-bea4536aad7d.png)
I see most of them, but not plants. but maybe it exists elsewhere.

**Comment by denysaw** [comment]
@j3fffff Yeah, then at least Animal and Citizen Population series should also be there. Will check.
