### ISSUE TITLE
Storage Silo and Powered Storage Silo World Objects.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17427]
Names:
StorageSiloObject + SiloItem
PoweredStorageSiloObject + PoweredSiloItem

- [x] Gameplay restrictions to item types allowed
- [x] Added to Tech tree
- [x] Models + Textures
- [x] Prefabs
- [x] Icons

These can start out as being the same as shipping containers, but ideally they can only hold particular kinds of materials. I think the best way to sort that would be to allow particular **tagged** items to be stored in specialty storage objects like these. 

Silos should be good for storing soil and wet farming products like fertilizers, but also for products typical of grain bins like harvested grain, corn, etc. Later on we may expand eco to break grain bins out into their own objects and items. For now, silos can cover both functions and be more like universal farming product storage.

Storage silos should not be restricted to only farming products, they could also be used to store things like plastic pellets or any other thing you might feasibly be able to 'pour' in and out. No full-on liquids like ore concentrates or wet tailings, though. 

The Powered Storage Silo is intended to be used for anything that is temperature or environmentally sensitive, including food products, seeds, perhaps high end fertilizers could require it, and eventually with more agricultural updates certain kinds of meal or feed.

An MVP 9.2 solution for these guys could be make them storage which takes everything except world objects, with perhaps a second option being one silo per item type allowed, with quite massive capacity for that one item. Probably just hide Powered Storage Silo for 9.2 unless a good use can be thought of.

**Comment by Phlo123** [comment]
![2](https://user-images.githubusercontent.com/17730996/89007631-c0c0ff80-d311-11ea-812d-81b172edc436.png)
Grain Silo and Powered Grain Silo

**Comment by keegan-o** [comment]
Lets get prefabs and icons done for these for 9.2!

**Comment by Phlo123** [comment]
Prefabs done and uploaded.

**Comment by RobertMangano** [comment]
icons have been added to icon sheet 04 although the item does not exist in the item list

**Comment by SlayksWood** [comment]
have them in game, but Powered storage silo is hidden yet.
