### ISSUE TITLE
Make a species compendium in the ecopedia

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17421]
![image](https://user-images.githubusercontent.com/3536496/88969574-eb557e80-d265-11ea-93a7-f8e7319e8836.png)
Species page is very barren. Add an image of each species and some real-world info about each. Both plants and animals.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/19056
