### ISSUE TITLE
Wooden Liquid Storage Tank [Model + Prefab]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17426]
These are large world objects for holding stockpiles of oil, water, or other industrial liquids like sewage, possibly even wet tailings (we would want the object to still emanate some pollution if that were the case). 

They should be pretty industrial, comparable in size to the silo storage objects, but probably made to be a wider and fatter cylinder.
They should have a center, and on one side of the object there should be a large pipe port input, and on the other side, a large pipe port output.

They will **not** need electricity, so the gauges and such on the object should be mechanical/glass, not electronic. But they will be a mid/high tech steel industrial object.

Probably something like 5x5x5, odd number will help aesthetically so you can have the ports in the dead center.

For the Wooden Liquid Storage Tank, think old water tower style, planks hooped with two rings of iron. It should be smaller, something like 3x3x3. Still should have large pipe port on both sides.

- [x] Concepts
- [x] Model/Textures
- [x] Prefab in eco.unity

**Comment by RobertMangano** [comment]
![liquid storageconcept.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/8b500eb5-14fa-40fb-9f71-d51f59533ff0)

**Comment by RobertMangano** [comment]
![liquid storageconcept2.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/b6812b0d-099b-40da-997c-aa595f1a780b)

**Comment by RobertMangano** [comment]
[Uploading... wooden liquid storage.jpg]

**Comment by RobertMangano** [comment]
![wooden liquid storage.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/c1f487d8-d31c-41c6-b618-b42b101cb3c0)

**Comment by keegan-o** [comment]
Upping priority to medium since 90% of work has been done, just needs a prefab.
