### ISSUE TITLE
[0.9.0 develop-15] Civics: capitol's overlapping cases

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17433]
Need some adjustments here and there
1) Article 
![unknown (25)](https://user-images.githubusercontent.com/27898520/89020644-b2d2a500-d338-11ea-9bfe-218de362ec31.png)

2) Removed Article
This one looks ugly, actually.
![bandicam 2020-07-31 14-25-04-130](https://user-images.githubusercontent.com/27898520/89021279-b286d980-d339-11ea-99e9-256f064c5483.jpg)

**Comment by SlayksWood** [comment]
Need a little lift up:
![image](https://user-images.githubusercontent.com/45708377/90602650-c5871e00-e202-11ea-997c-60e29b7d12c9.png)
