### ISSUE TITLE
Industrial Elevator World Object [Functionality Issues]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17431]
- [x] Audio for buttons, moving, stopping. 
- [x] All basic functionality issues resolved

**Functionality Issues Notes**: Currently, there is an issue with raising the elevator from the bottom when you are standing in it with a truck. If you hop in the truck right after you activate the elevator, the elevator will work though, so something weird is happening with player/elevator/truck colliders. Sometimes the elevator with a truck will also just move up slower.

During initial setup we ran into issues with 'drift' where the elevator cabin position would drift over time and end up intersecting with other geometry and colliders and thus be stuck. Keep an eye out for that, we may want to more actively force the elevator to only be able to move up and down somehow. 

- [x] Tech Tree + Recipe Added

Item/Object name:
IndustrialElevator

- [x] Unity Setup (Object prefabs and icons in Eco.unity, art tested+fixed in-game)
- [x] Model + Texture
- [x] Prefab
- [x] Icons

**Comment by WeaselDog** [comment]
Please split into sub issues.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/66f6d93d-c6d0-4859-89b3-d10311810731)

@MilenkoTunjic Right now the large elevator controls don't really match the needed controls for the elevator script, we need up, down, and stop buttons.

We also will want an animation of both doors opening and closing at once so the elevator can be used in whatever way players like. 

We will also need a call post object that differentiates itself from the small elevator call post. This is less important, in setting it up we could probably have it use the other call post object or a duplicate of it.

**Comment by MilenkoTunjic** [comment]
Up and Down buttons are animated
they light as lever is moved up and down
There are also Open and close door buttons (even if this is automated, they should still play the animations 
as the door is opening and closing)

**Comment by keegan-o** [comment]
Alright I got this mostly working now and checked into SVN! Just needs an icon still Milenko!

**Comment by IcedForge** [comment]
Once code goes in and starts tinkering and adjusting anything needed to be fixed please take a look at
https://github.com/StrangeLoopGames/EcoIssues/issues/18809 as well, might be some sync positioning issues with the platform itself causing it to keep stopping? And if the same code is used in the new elevator we might see this more frequently.

**Comment by WeaselDog** [comment]
@Quadbro Adding you for the code based issues. We have the object added in Develop.

**Comment by SlayksWood** [comment]
Closed this one. We will create a new issue for any problem we will have during testing.
