### ISSUE TITLE
[0.9.0 develop-15] Filter glithes

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17432]
- [x] 1. When any element is selected, the width changes. It isn't happen always, but in many cases. Step to reproduce:
- open filter in any object. I have width = 8 items:

- select item. My width will change to 7 items:

- [x] 2. Doesn't show all items until you choose any item. Seems it replace one item to another. Step to reproduce:
- just open filter and see to items in it. In my case look at Acorn, it will replaced by Zonning Office in the end. But when you select any item it will be displayed right:
![2020 07 31 Filter glithes](https://user-images.githubusercontent.com/45708377/89012816-7775ad80-d31b-11ea-9f99-c438c49ace55.gif)
![image](https://user-images.githubusercontent.com/45708377/89012399-d8e94c80-d31a-11ea-8c9f-b95d4aba22c5.png)

- [x] 3. maybe make min width a little more?
![image](https://user-images.githubusercontent.com/45708377/89013321-5bbed700-d31c-11ea-8acb-e28735a1a22e.png)

**Comment by SlayksWood** [comment]
check amendments after that:
![image](https://user-images.githubusercontent.com/45708377/89016311-2ff22000-d321-11ea-9c8f-e0129858c5e3.png)
![image](https://user-images.githubusercontent.com/45708377/89016333-37192e00-d321-11ea-900c-86d6fecc5b21.png)
![image](https://user-images.githubusercontent.com/45708377/89016345-3aacb500-d321-11ea-99a1-5f185e1b3aea.png)

**Comment by serpopov** [comment]
Missing icons in other issue
