### ISSUE TITLE
USER ISSUE: Server not loading

### ISSUE THREAD

**Issue by bbborracho** [StrangeLoopGames/EcoIssues#17449]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Click either "Continue" or "Host Your Own World"

**Expected behavior:**
Normal popups then server loads

**Actual behavior:**
Normal popups, but then error message stating that an unspecified user is not online and not loading the server

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods are installed

**Comment by MonzUn** [comment]
Sounds similar to the errors you get when you're not logged in to Steam properly or steam is not responding.
Have you tried relogging your Steam account or using the SLG client?

**Comment by SlayksWood** [comment]
@bbborracho Thank you for the report. please, provide to us a little more information.
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).

**Comment by bbborracho** [comment]
Hi, I was having the issue with all servers, but it was a PEBCAK situation. Steam had switched to offline mode for some reason, which was the problem.

Sorry.
