### ISSUE TITLE
Possibility to reference to amount of elections of a title

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17445]
- In Elected Titles: Making the Vice-President requiring to not have been elected President twice
- In Laws: Paying someone that has been elected and is now out of office with a pension

**Comment by johnkslg** [comment]
There are some stats with term limits, did you try those?

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/strangeloopgames/ecoissues/issues/14182
