### ISSUE TITLE
9.0 Test - Tinny/Attenuated, Loud/Silent Sounds

### ISSUE THREAD

**Issue by Trug42** [StrangeLoopGames/EcoIssues#17452]
Just started testing 9.0 today, and noticed that many of the sounds seem to be very tinny and attenuated. It's particularly noticeable in the wood chopping and grunt sounds that are made sometimes after a jump or a fall. I made two videos to contrast those sounds on my machine in 8.3.3 vs. the 9.0 test client on Steam, see below.

[8.3.3](https://www.youtube.com/watch?v=F8B0oVRT_e4)
[9.0](https://www.youtube.com/watch?v=Eua5SBXK4Bk)

**Comment by beastyn** [comment]
[ ] Chopping tree
[ ] Jump, crunt

**Comment by beastyn** [comment]
Additions: 1733

-[ ] Water-wind balance. Maybe we can try to adjust volume for water and wind? Water is too low for now and wind is too loud. Just a little bit, it almost perfect, but not here yet ) Especially lake-river sound,

**Comment by beastyn** [comment]
- [] Vehicles are quite loud

**Comment by RaptorX23YT** [comment]
There also seems to be an issue with vehicle sounds, they change in volume depending on your position in the world, and also get quieter when the background music comes on. Try driving a steam truck around a work, you should be able to replicate it.

**Comment by NDKilla** [comment]
> * [ ]   Vehicles are quite loud

For some reason most vehicles seem normal to me (not unreasonably loud or quiet, in comparison to the rest of the game). The exception being the powered steam cart(?), which I'm glad I no longer drive because I had to have my game at like 1% volume any time I was driving it.

Additionally maybe unrelated but I seem to sometimes hear vehicle sounds when I'm pretty sure I shouldn't (nobody driving nearby?)

**Comment by D3nnis3n** [comment]
From https://github.com/StrangeLoopGames/EcoSuggestions/issues/1186

> Hey,
> 
> I'm not sure if I'm the only one but when you "open" the carpentry table and also when using the rock drill there are those very unpleasant sounds like someone scratching their fingernails on a blackboard or like styrofoam rubbing against each other, that sort of thing.
> 
> It kind of hurts my ears and makes the hair on my neck stand up.
> 
> So my suggestion is to perhaps replace these with more pleasant sounds if it's not too much trouble.

**Comment by SlayksWood** [comment]
Fountain sound spread is too far and it's louder than sound waterfall or sea

**Comment by beastyn** [comment]
@Quadbro I'm not sure if it was in the latest build (1741). but animals roars are still too loud (louder than a modern rock drill).
Here is a wolf, but I think all of them need to be fixed.

https://drive.google.com/file/d/15T9-8OC8P_HMvh7g9yHsU7usGW6CZiFq/view?usp=sharing

**Comment by beastyn** [comment]
- [ ] opening carpentry table making unpleasant scratchy sound, also its pretty scratchy in a iron rock drill too

**Comment by beastyn** [comment]
As dev asking to create separate issues we will have this for collecting and reviewing beforе giving to dev.
