### ISSUE TITLE
Some missing icons

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17455]
![image](https://user-images.githubusercontent.com/3536496/89082595-4b6e2280-d343-11ea-98c4-858b0cbb36c7.png)
Devise a process to get these auto-addressed
Check other missing icons

Trade got renamed for example

**Comment by SlayksWood** [comment]
'didn't vote' yet

**Comment by SlayksWood** [comment]
Still an issue
![image](https://user-images.githubusercontent.com/45708377/90391493-e41bd680-e095-11ea-82ec-db43f23b5dbf.png)

**Comment by WeaselDog** [comment]
Fixed in SVN
