### ISSUE TITLE
[0.9.0 beta staging 1695] Not all currency are listed on currencies tab

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17469]
Step to reproduce :
- log in on the new officiel test server
- open currencies in use tab

Expected result:
-dollar currency is listed

Current result:
-dollar currency is not listed

![image](https://user-images.githubusercontent.com/339611/89105725-f950fe00-d423-11ea-8294-736099c0baf8.png)
[Player - Copie (5).log](https://github.com/StrangeLoopGames/EcoIssues/files/5010910/Player.-.Copie.5.log)

**Comment by SlayksWood** [comment]
dup #17462
