### ISSUE TITLE
USER ISSUE: Disconnect/Kick on starting President-election

### ISSUE THREAD

**Issue by Hiroyugane** [StrangeLoopGames/EcoIssues#17464]
\
**Version:** 0.9.0.0 beta staging-1695

**Steps to Reproduce:**
1. go to the voting box (was flying)
2. click on "start election"
3. choose "president"
4. perform action
5. insta-disconnect with an error

**Expected behavior:**
Just start election

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Elections.Election.FullDescribe()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
white-tiger

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5010010/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5010011/Player-prev.log)

**Comment by SlayksWood** [comment]
dup #17344
