### ISSUE TITLE
Show new districts on the map by default

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17467]
I'd reverse the behaviour. People often dont notice road districts as they cant see it. The districts probably should show by default, you needing to untick them if you dont want to see them. I mean, it's the same for claims and districts are voted upon. So it's not something you typically spam to annoy people.

**Comment by gzatravkin** [comment]
So you offer to switch to last district every time district map is added? 

Seems be no obvious for users, and can be annoying in case if they b.e. wanna see properties. They will need to turn back to property every time there are new district map (and it may be often, depend on elections model etc). 

If it's necesarry how about popups "The district X was accepted, do you want to select it?", "The district X was changed..."? 

But I can imagine that can be annoying too. And I believe we already have right-side notification "District map was accepted". Is it not visible enough? Any idea to improove it if not?

**Comment by D3nnis3n** [comment]
Back when i created this issue you could select multiple districts. As this is currently no longer the case, this issue is irrelevant until that changes.
