### ISSUE TITLE
Dirt drop on claimed land

### ISSUE THREAD

**Issue by mycide** [StrangeLoopGames/EcoIssues#17460]
Plot A - owned by another player
Plot B - unclaimed, or claimed by yourself, with at least 1 higher elevation of any block (from what I can tell)

for my example, i have dirt in my shovel. if i highlight the side of Plot B, i can drop it on to Plot A. This seems to create a problem between the server and the client, immediately appearing as the inability to switch from the shovel. The carried dirt is not visible. After logging out and back 2x, I was able to see the dirt, and drop it, resolving the problems i was experiencing

**Comment by beastyn** [comment]
@mycide 
Thank you for the report. Video would be great. We have a similar issue here #12222, but usually it can appear with high ping. I can't reproduce it locally.
So we need to distinguish your case first.

**Comment by beastyn** [comment]
Will close due no response ans take it as dup  #12222

**Comment by mycide** [comment]
I apologize I was not able to get to this sooner. It's hard to tell from
just the video, but when I back up after "dropping the dirt" im attempting
to change tools via mouse wheel and buttons, then i switch that slot to the
chainsaw, and try those again

https://youtu.be/lp0uS_ShvPI
