### ISSUE TITLE
Staging #311c9071 - no inv accessible

### ISSUE THREAD

**Issue by Ciannicay** [StrangeLoopGames/EcoIssues#1747]
neither stockpiles nor chest can be accessed using "e".
Items taken out by tools dont show up in carried item slot but can be placed and put back into stockpile
Stockpiles with no blocks beneath them can be walked through / you will slowly fall through them

**Comment by MarjieAVolk** [comment]
We had some issues in that build, already fixed (Except for the stockpiles thing, which is known behavior)
