### ISSUE TITLE
USER ISSUE: Self-Opening Storage

### ISSUE THREAD

**Issue by Panderling** [StrangeLoopGames/EcoIssues#17479]
\
**Version:** 0.9.0.0 beta staging-1695

**Steps to Reproduce:**
Link inventories and collapse some. Come back 5 minutes later and the collapsed ones are no longer collapsed. When clicked to collapse again they take two clicks.

**Expected behavior:**
Collapsed Inventories should stay collapsed

**Actual behavior:**
Inventories are opening back up on their own and can't be collapsed again. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MazonDel** [comment]
To reproduce:

1: Have at least 3 stockpiles/chests/etc in range of each other.
2: Open one stockpile. Expand/collapse some number of the shown inventories leaving at least 1 open and at least 1 closed.
3: Exit the stockpile.
4: Wait several minutes. To determine specifically when to continue, place a break-point on the "if (comp == null)" line in LinkComponent.SetObjectExpanded() on the server. This line will trigger once per displayed inventory (ex: If you saw 2 other inventories in the stockpile view, it will trigger twice). After a few minutes it will trigger once per displayed inventory again. You may now continue.
5: Open the SAME stockpile, see how all the inventories are now expanded.
6: Clicking to collapse one of the formerly collapsed inventories will now require two clicks to execute.

**Comment by beastyn** [comment]
Do not save collapsed state after client restart.
But arrow will tell me its collapsed, so you need to click twice to collapse it again.
![bandicam 2020-08-18 11-17-30-026](https://user-images.githubusercontent.com/27898520/90477275-8db9a100-e144-11ea-9b73-571ae079a1b4.jpg)

**Comment by mirasrael** [comment]
I'll fix this. It seems a bit complicated to properly setup pooling for this.
