### ISSUE TITLE
0.9.0.0 - beta staging-1695 : Title duplicate delete 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17478]
Deleting a title using ENTER instead of pressing green OK button will cause trying to delete next title to ask if you want to delete the previous one.

Edit : After more testing
It will only prompt on previous title IF the following
Enter was used on first title
And second title you attempt to remove is directly following in the list.

So - Title 1,2,3,4,5 avaible
Delete title 1 using enter instead of yes
Try to delete title 3, no issue prompt asks if you want to delete the title
If you try to delete title 2 instead it will prompt Do you wish to delete title 1

**Comment by IcedForge** [comment]
![Screenshot_265](https://user-images.githubusercontent.com/24981362/89124788-fadcfd80-d4d9-11ea-98a5-6ce61e89681c.jpg)
When pressed ENTER to delete previous title, now attempting to delete another title - Image asking if i want to delete the title i already deleted.

**Comment by beastyn** [comment]
@IcedForge thank you for the report. 
Can't reproduce with fresh develop.
Maybe some special steps?
Also video and client log will be useful.

**Comment by beastyn** [comment]
Could not reproduce and also not enough information, will close. Please tell if still actual.
