### ISSUE TITLE
Peculiar Game Locking Crashes

### ISSUE THREAD

**Issue by f00ki3b00ki3** [StrangeLoopGames/EcoIssues#17472]
I own Eco on steam, and really love the game from what I’ve played and seen; except, for the past year and a half out of two, I haven’t been able to actually play the game. Every time I start the game up, I can never get past the loading screen without encountering a peculiar crash. The crash begins with both of my monitors freezing, without freezing anything else. Then, both of my monitors go dark at the same time, and upon coming back, the game will still be open, but completely transparent. Only the cursor remains until I close the game. Is there any help I could get fixing this issue? The updates I’ve seen on this game over the past year and a half have deeply intrigued me, but I could never actually get to it. 

Server Log:
[log_200728115430.log](https://github.com/StrangeLoopGames/EcoIssues/files/5011091/log_200728115430.log)

Client Log:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5011095/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5011096/Player-prev.log)

Specs
PC: AMD Radeon RX480 8G, Corsair Vengeance 16G DDR3 @ 1600MHz, AMD FX-8350 Eight Core @ 4.00GHz, on an ASUS M5A97, with a 7200 rpm 1TB hard disk. My main monitor is an LG 24en33tw, connected through a displayport/DVI cable. My secondary monitor is an old dell connected through a VGA cable plugged into a VGA to HDMI converter.

**Comment by SlayksWood** [comment]
@f00ki3b00ki3 Thank you for the report.
Would you like to try playing the playtest build of our 0.9 version at first? Maybe your issue was already resolved in new version.
If you agree, please contact with me (Kirill (Slayks)#6251) or our community manager @D3nnis3n (D3nnis3n#2053) in Discord.

**Comment by beastyn** [comment]
Close due no feedback. Hope everything was solved.
