### ISSUE TITLE
USER ISSUE: Flight Controls

### ISSUE THREAD

**Issue by LadyNasse** [StrangeLoopGames/EcoIssues#17480]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
/fly

**Expected behavior:**
Move with the set movement keys.

**Actual behavior:**
Uses default movement keys only.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods installed.

**Comment by SlayksWood** [comment]
dup #9665
