### ISSUE TITLE
[0.9.0 develop-19] Searching in Ecopedia is broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17486]
For example try to find Contract Board or Real Estate Desk. I should see Category and Page too, not only subpage:
![image](https://user-images.githubusercontent.com/45708377/89160422-b4d77680-d579-11ea-8056-5da154a072da.png)
![image](https://user-images.githubusercontent.com/45708377/89160498-d6386280-d579-11ea-8029-5e9c8f98bf35.png)

**Comment by beastyn** [comment]
Still broken!
Now, with contract board searching it gives me Real Estate somehow
![bandicam 2020-08-17 13-02-38-995](https://user-images.githubusercontent.com/27898520/90372564-04459880-e08a-11ea-8db9-5e63fdf0963d.jpg)
