### ISSUE TITLE
[0.9.0 develop-19] New world generation problem

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17483]
Biomes doesn't destroyed, but upper layer for all biomes except Desert and Ice is Dirt.
![image](https://user-images.githubusercontent.com/45708377/89153130-ff9ec180-d56c-11ea-8122-58a6274617b4.png)
![image](https://user-images.githubusercontent.com/45708377/89154172-0cbcb000-d56f-11ea-91aa-a5128796bc48.png)

**Comment by beastyn** [comment]
After check #17266

**Comment by SlayksWood** [comment]
Something awful, can affect playtest too. Still need to test more. Critical for now:
![image](https://user-images.githubusercontent.com/45708377/89172720-c3c72480-d58b-11ea-8057-d8d9798e055a.png)
