### ISSUE TITLE
Shoveling or Mining, Stone and Dirt doesn't get highlighted...

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1748]
After mining or shoveling a few things sometimes the dirt or stone doesn't get highlighted, if you are to fast i guess. But you have to pretty much look at sky or turn around then back at it for the said object to be picked up.

**Comment by Fr3aKeD** [comment]
5.6.1

**Comment by metachronism** [comment]
can't reliably repro this
