### ISSUE TITLE
[0.9.0.0 beta staging-1702] Chat send "message" input doesn't show

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17496]
Step:
- Add a chat send condition
- The message input will not be visible
- Close and reopen the law edit
- The message input will be here

[Player - Copie (9).log](https://github.com/StrangeLoopGames/EcoIssues/files/5016355/Player.-.Copie.9.log)

**Comment by beastyn** [comment]
Should be fixed with this
#17385
