### ISSUE TITLE
[0.9.0.0 beta staging-1702] Custom stat compare selection doesn't update the ui

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17495]
- Tried to add a custom stat query to a compare
- Nothing happened (the UI was still like if I didn't choose the custom stat query in the compare left input)
- Closed and reopen edit : the custom stat query was here
- Tried to reproduce the bug:
  - Tried to add a custom stat query to a compare
  - Nothing happened
  - Closed and reopen edit : this time the custom stat query wasn't here and a 4 was here

The log file contain all those step.
[Player - Copie (8).log](https://github.com/StrangeLoopGames/EcoIssues/files/5016282/Player.-.Copie.8.log)

![image](https://user-images.githubusercontent.com/339611/89188719-52916c80-d59f-11ea-98a5-863e015d3eff.png)

**Comment by matheod** [comment]
Don't know if related but after that the "Then" section lost its content (but this might be a missclick)

**Comment by beastyn** [comment]
Should be fixed in the next update
