### ISSUE TITLE
0.9 time slept form localization

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17494]
1) i cannot see strings for hours and seconds
2) Time slept: exists on crowdin but not used
3) button should be longer\bigger.
![изображение](https://user-images.githubusercontent.com/4980243/89180605-c2e9bf00-d59a-11ea-99fe-234c8f13010b.png)

**Comment by Quadbro** [comment]
strings are in (but not translated yet), time slept is used correctly,

**Comment by Quadbro** [comment]
made button wider a bit to include loc names properly
