### ISSUE TITLE
[0.9.0.0 beta staging-1702] Global timer "Time input" doesn't show

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17497]
Step to reproduce :
- add a global timer condition

Expected behaviour:
- there is an input to set time

Current behiavour:
- there is no input to set time

Able to reproduce 3 times in a row.

![image](https://user-images.githubusercontent.com/339611/89190646-0ac01480-d5a2-11ea-8a4e-8aa7b2b5d0d4.png)

**Comment by johnkslg** [comment]
That tooltip isnt saying what triggers should be there, its saying what context is available, which can be used in the clause sections.
