### ISSUE TITLE
[0.9.0.0 beta staging-1702] Tree debris infinite spawn

### ISSUE THREAD

**Issue by hegemonart** [StrangeLoopGames/EcoIssues#17498]
If u chop down Joshua tree
![Eco_2020-08-03_17-29-40](https://user-images.githubusercontent.com/69156604/89193856-41e8f280-d5af-11ea-90b6-3326c75d4782.jpg)

and leave behind only top part
![Eco_2020-08-03_17-30-24](https://user-images.githubusercontent.com/69156604/89193883-4b725a80-d5af-11ea-8e5e-d9585760491f.jpg)

u can use it as ragdoll ball, shooting like a bullet with a simple collision. its probably a result of its model.
and if it hit any surface, there will be spawned tree debris from 1 to 4(mb more, 4 was max, when tested)
each give wood pulp and seeds at times.

i believe, that people, if they want, can:
- make small arena(5x5 or 10x10) like a box 5-10m deep, that ll prevent that block from flying away
- plant one joshua tree,
- chop it and leave only top part behind
- smash it with body for some time
- repeat
- get infinite amount(depends on persistance) of tree debris,

i haven't tested it, but i think, that if there ll be more top blocks from joshua tree and they ll be in a close space, colliding with itself and player model, than it possibly be even easier to get wood pulp

so, as result, it will be way too easy for people to make almost any number of tree seeds, mortars, cellulose fiber and cheap fuel
without need to spend any calorie on chopping tree, just calorie to gather wood pulp

possible solution:
make weight of log blocks heavier in collision calculation, so people can't shoot em too far away
or
make limit how much one log block can spawn tree debris

**Comment by IcedForge** [comment]
This also works with an excavator f.ex just pushing the entire trees around a grassland area to create mass amounts of pulp & seeds.

**Comment by mirasrael** [comment]
It is now only possible to spawn at max 10 tree debris from one tree and also as soon as tree finished felling (either in 10 seconds or when stop moving) it will stop spawn tree debris.
