### ISSUE TITLE
[0.9.0 develop-19] Predators attack and eating other animals with the wrong side

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17491]
Sideways or backway
![2020 08 03 Predators attack and eating other animals with the wrong side](https://user-images.githubusercontent.com/45708377/89177647-959a1280-d594-11ea-845a-27076ff7c6a5.gif)

**Comment by johnkslg** [comment]
Need to get the code that makes them face the prey working. Its in there but something about it is broken. Check the animal debug

**Comment by mirasrael** [comment]
It is probably related to issue fixed in https://github.com/StrangeLoopGames/Eco/pull/6513

**Comment by beastyn** [comment]
Nope. Still something wrong with positioning.
![355ef034d6f5c96838c647fbd81c494a](https://user-images.githubusercontent.com/27898520/89266710-b2475080-d64f-11ea-912f-8b250df0114f.gif)

**Comment by johnkslg** [comment]
They need to face the target properly.
The coyote raising their arms is because IK is forcing them to look forward while their animation is trying to make them bend down.
