### ISSUE TITLE
USER ISSUE: Invisible Wood Cart

### ISSUE THREAD

**Issue by Caldrena** [StrangeLoopGames/EcoIssues#17501]
\
**Version:** 0.9.0.0 beta staging-1702

**Steps to Reproduce:**
Unsure? it was visable before

**Expected behavior:**
Be fully visable.

**Actual behavior:**
Is invisible.

After picking up and replacing it fixed itself.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/68741535/89212569-ad23cc00-d591-11ea-9cae-58037985ce39.png)

**Comment by Caldrena** [comment]
![image](https://user-images.githubusercontent.com/68741535/89237884-60a4b480-d5c2-11ea-9cb7-43d8fd965f86.png)
 now work bench and tool bench have turned invisible, not sure what im doing to make it so

**Comment by SlayksWood** [comment]
@Caldrena 
Can you provide log files?

**Comment by Caldrena** [comment]
Im not sure how to do that but if you tell me how i can try.

**Comment by Caldrena** [comment]
I'm not sure how to do that but if you tell me how i can try.

**Comment by beastyn** [comment]
I think it will be impossible to get an actual log file )
@Caldrena for information, you can use https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
We will investigate it further, thank you for the report.

**Comment by SlayksWood** [comment]
merged to #17803
