### ISSUE TITLE
[0.9.0.0 beta staging-1702] Item not turning into compost (turning into nothing)

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17503]
Step to reproduce:
- Put green item on floor, then wait
- The icon of the iten will slowly turn into the "trash" icon
- But after the icon turned fully into trash (i even waited a lots of more), the item will not be transformed into compost
- If you try to move the item, it will revert into the green item.

![image](https://user-images.githubusercontent.com/339611/89219128-884e4980-d5cf-11ea-8b49-8be04f158862.png)

**Comment by beastyn** [comment]
Investigating this one here #17560
Thank you.
