### ISSUE TITLE
Selector text is aggregating lists of length 1

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17509]
![image](https://user-images.githubusercontent.com/3536496/89229420-3e953d00-d596-11ea-8924-900c7eae5c1f.png)
This should just say the district name, and the tooltip goes to that district.

**Comment by SlayksWood** [comment]
Can you change number shown to 2 elements? 3 elements seems is too big. Or better limit by count of chars:
![image](https://user-images.githubusercontent.com/45708377/90612117-46004b80-e210-11ea-971a-5cae5aea79bd.png)
And if you change these names to longer ones:
![image](https://user-images.githubusercontent.com/45708377/90613577-3bdf4c80-e212-11ea-80d9-36c84dbd7ad1.png)
