### ISSUE TITLE
Typing missing command no longer shows search

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17510]
![image](https://user-images.githubusercontent.com/3536496/89229539-73a18f80-d596-11ea-97d8-5d6270807dd3.png)
Previously, typing something like '/tog' would show you all chat commands with a name or help containing the string tog, now it no longer does.

**Comment by SlayksWood** [comment]
Seems still an issue. We have command '/qa toggle'
![image](https://user-images.githubusercontent.com/45708377/89414309-dcbe0a00-d732-11ea-969e-b09311694cea.png)
try to write /tog:
![image](https://user-images.githubusercontent.com/45708377/89414130-949ee780-d732-11ea-984e-ae49dcd20888.png)
I don't have any commands matching '/tog'

**Comment by mirasrael** [comment]
Fixed
![image](https://user-images.githubusercontent.com/475445/89519826-a4c3cf00-d7e5-11ea-84be-f8fc03025071.png)
