### ISSUE TITLE
Pushing escape to close popup dialog while cursor is inactive should not activate cursor

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17515]
![image](https://user-images.githubusercontent.com/3536496/89231965-45727e80-d59b-11ea-85a8-687356cf0c0e.png)
Pressing escape should always just do 'one thing': close the dialog, pop the mouse cursor, never both.

**Comment by gzatravkin** [comment]
Was you trying it in unity or in built version?

**Comment by SlayksWood** [comment]
Can't reproduce too in develop-20 build.

**Comment by johnkslg** [comment]
![animx22](https://user-images.githubusercontent.com/3536496/95154379-8d9e5080-0746-11eb-9d05-d84454e54342.gif)
Repro happens when opening up a civics object then closing by clicking X
The cursor then goes away and youre moving around.  It should leave the cursor up because the world object UI is still open.
