### ISSUE TITLE
Spacing on auto-wrapping bad in popup

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17514]
![image](https://user-images.githubusercontent.com/3536496/89231868-122fef80-d59b-11ea-99d6-27d7170b29f5.png)

Notice the long second line gets double spaced when it wraps, while the above one does not.
Likely a case of wraps that happen mid-tag (in this case the bank account name) getting doubly applied somehow.

**Comment by SlayksWood** [comment]
Seems this happens because player nickname occupies 2 strings.
merged to #17485
