### ISSUE TITLE
Some items missing tooltip title

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17511]
![image](https://user-images.githubusercontent.com/3536496/89229738-dd219e00-d596-11ea-8ef9-74a9f5ef312d.png)

**Comment by johnkslg** [comment]
These are items spawned during /test economics, if it affects it.

**Comment by gzatravkin** [comment]
CNR. Some additional info? 
Save data, branch (was it at develop?). 
Was everything up-to-date (SVN)?

![image](https://user-images.githubusercontent.com/53317567/89341665-023a0d80-d678-11ea-846f-3c596f73f227.png)

**Comment by gzatravkin** [comment]
Closed, please reopen if you will see it again.
