### ISSUE TITLE
Laws broken after /spawn civics

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17513]
![image](https://user-images.githubusercontent.com/3536496/89230093-8cf70b80-d597-11ea-92da-3ad8d5e35ec1.png)

**Comment by johnkslg** [comment]
Getting exception:
NullReferenceException: Object reference not set to an instance of an object
IconUtils.InstantiateIcon (UnityEngine.GameObject iconPrefab, UnityEngine.Transform parent) (at Assets/Scripts/Utils/IconUtils.cs:24)
SplitNameUI.BuildIcons (System.String text) (at Assets/UI/Scripts/Skills/ViewUISystem/SplitNameUI.cs:51)
SplitNameUI+<>c__DisplayClass6_0.<SyncWithView>b__0 () (at Assets/UI/Scripts/Skills/ViewUISystem/SplitNameUI.cs:22)
Eco.Shared.View.SubscriptionsExtensions.SubscribeAndCall (Eco.Shared.View.ISubscriptions ss, Eco.Shared.View.IObservable s, System.String propname, System.Action changedCallback, System.Action unsubscribeCallback) (at C:/Eco/Server/Eco.Shared/View/Subscriptions.cs:130)
SplitNameUI.SyncWithView (Eco.Shared.View.View view, System.String propName) (at Assets/UI/Scripts/Skills/ViewUISystem/SplitNameUI.cs:22)
ViewExtensions.AutoSetupUI (Eco.Shared.View.View parentView, Eco.Shared.View.ISubscriptions subscriptions, UnityEngine.Transform autogenRoot, System.String propertyPath, System.Action OnChange, System.Boolean allowAutogen, UnityEngine.Transform root) (at Assets/Scripts/View/ViewExtensions.cs:136)
AutoViewUI.ViewInited () (at Assets/UI/Scripts/WorldObject/AutoViewUI.cs:34)
ViewBehavior.InitView (Eco.Shared.View.View parentView, Eco.Shared.View.View view, Eco.Shared.View.View

**Comment by johnkslg** [comment]
Probably trying to display this law which doesnt have an icon for its trigger yet:
![image](https://user-images.githubusercontent.com/3536496/89230707-b3697680-d598-11ea-92e8-fd36882d587a.png)

**Comment by beastyn** [comment]
As here #16827
@Dmittry62 maybe this command will help you?
