### ISSUE TITLE
Store not updating owner

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17512]
![image](https://user-images.githubusercontent.com/3536496/89229918-3984bd80-d597-11ea-9bdb-a7869f4d81c3.png)
/test spawneconomics
go to spawned store
/owner
see youre the owner
/owner 2
see youre still the owner but should not be.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/89229979-57522280-d597-11ea-931c-e6205613e20c.png)

**Comment by SlayksWood** [comment]
work for me but have exception when change owner:
![image](https://user-images.githubusercontent.com/45708377/89283743-5207dd00-d656-11ea-8655-687d072c2b2f.png)
