### ISSUE TITLE
Storage/Stockpiles are reaching

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1751]
I'm transporting dirt right now from one stockpile to next and they are fair ways away. I went to take cart to next pile and for some reason i still see the previous stockpile in the cart UI and can even take dirt out. I was a good 50 blocks away give or take and another thing was i didn't see the stockpile that the cart was right next to. This has happened multiple times but i thought it to be lag.

**Comment by Fr3aKeD** [comment]
5.6.1

**Comment by MarjieAVolk** [comment]
Hm yeah sounds like lag

**Comment by Fr3aKeD** [comment]
Yeah, i thought it be lag too but i can access a destroy blocks fine.

**Comment by MarjieAVolk** [comment]
Still not able to repro this

**Comment by Fr3aKeD** [comment]
i haven't been able to replicate it either. I haven't seen it but like 3 times.

**Comment by metachronism** [comment]
closing this out, as its likely more perf issues related to inventories - fixed as of alpha 6
