### ISSUE TITLE
[0.9.0 develop-21] 'Select attacking' takes 3000 sec

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17519]
![image](https://user-images.githubusercontent.com/45708377/89261987-a5b6fe00-d637-11ea-9a48-e0e77d4079b2.png)
And animal stay 50 minutes in one position:
![image](https://user-images.githubusercontent.com/45708377/89262062-c5e6bd00-d637-11ea-9620-626e3dff0b58.png)

**Comment by johnkslg** [comment]
Its supposed to be them eating for a long period of time. Maybe on wrong behavior.
