### ISSUE TITLE
0.9.0.0 - beta staging-1702 : Wages pays with added decimal?

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17528]
![Screenshot_320](https://user-images.githubusercontent.com/24981362/89313319-a1f79b80-d678-11ea-8834-4fb8880f9aab.jpg)

not sure why there is a decimal number pulled from the Government Wage account

**Comment by beastyn** [comment]
@IcaeForge thank you for the report.
Its really hard to say what has happened here, as we don't know what was start amount for this account, how much money titles have got, maybe some people were occupying their posts for some part time and so on (transactions screens or something).
Also we still have rounding problems.

**Comment by IcedForge** [comment]
Yeah after digging into how wages are calculated i dont believe this is a bug, because if the person has been elected position for less then an hour it would pay according to minute so i think it is safe to close this if you want.

**Comment by beastyn** [comment]
Yeap, thanks for the attention.
