### ISSUE TITLE
I'm 50 managers of my own!

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17526]
![image](https://user-images.githubusercontent.com/25908592/89295992-12df8900-d662-11ea-891a-73653e27ea5f.png)

**Comment by IcedForge** [comment]
This seems to be only ever Personal accounts, does not happen on any manually created accounts
![Screenshot_312](https://user-images.githubusercontent.com/24981362/89296155-3f93a080-d662-11ea-82ec-fb13012585b1.jpg)
![Screenshot_313](https://user-images.githubusercontent.com/24981362/89296159-40c4cd80-d662-11ea-9e20-bcb6d58f451d.jpg)

**Comment by D3nnis3n** [comment]
This happens with all accounts. Depending on account the owner is listed between 3 to hundred times on owner, seemingly randomly.
