### ISSUE TITLE
Game crashed. Got broken graphics afterwards

### ISSUE THREAD

**Issue by cmfrydos** [StrangeLoopGames/EcoIssues#17529]
Hello,

the game just crashed a few hours ago, but unfortunately I did save the logs in time.
After I started eco a few minutes ago, the Unity-Error handler showed up during the load into the main menu, and the game quit.
When I restarted the second time I got to the menu, but the background was broken. It looked like over sharpened and was static (it was not animated like normal). I then got some strange graphical glitch when I tried to connect to my world:
![bug](https://user-images.githubusercontent.com/22503801/89321447-4088fa00-d683-11ea-9edb-b47842470315.PNG)
The background was constantly flickering between black and the 'normal' loading landscape. Loading took way longer (2-3x) than normal.
After I connected to the game, the world was just black: 
![bug2](https://user-images.githubusercontent.com/22503801/89321740-9a89bf80-d683-11ea-903d-3b5588bcd1e9.PNG)
Here are the logs from the second crash, and the current (broken, but running) state: 
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5023407/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5023408/Player.log)
I think my graphics card is in a strange state, so I will restart my computer (and edit this post then). But it seems like eco isn't correctly identifying that something isn't right (at least during second startup).
I'm not sure if this is a really issue on your part, but I wanted to let you know that there is some strange error handling behaviour.

**Comment by cmfrydos** [comment]
Ok, after I restarted my computer everything seems fine.
I forgot to mention that during the 'broken' loading phase, I was able to see my inventory (see first picture).
Normally you just see the animated background, maybe it is rendered above the game during the load, but because the animation was not possible (because my graphics card fail), I could see it way earlier?

**Comment by beastyn** [comment]
@cmfrydos Thank you for the report. Please, provide your PC specification (hardware and OS)
Did you meet this issue for the first time?

**Comment by cmfrydos** [comment]
Yes, I didn't meet this issue before, but I played just for a few dozen hours on this patch (latest 0.8.x from steam). I had no other problems so far, way better than a few years ago!

I think my graphics card 'crashed' while I played eco. I don't know why and how, and sadly I don't have the logs anymore. I then made a break and continued watching some streams and doing a little bit of work. When I then tried to restart eco, my system wasn't ready, and led to the error I described above. I did not encounter this with any other game, but since it was just a "graphical glitch" I went and restarted the whole system.

Sorry, I missed the fact that the specs in the logfile are not complete:
- Windows 10 64 Bit Version 2004 (Build 19041.388)
- Intel Core i5 650 (Clarkdale)
- 8 GB DDR3 Ram
- Nvidia GT 1030 with 2GB GDDR5, Driver Version 451.48 DCH

**Comment by beastyn** [comment]
@cmfrydos Thank you for the detailed information. We have greatly improved performance in 9.0, so I suppose it should be ok there.
If you want to check it before official release on our playtest server, you can write to @D3nnis3n so he can provide you with more information (Discord D3nnis3n#2053).
You can use this issue for any updates though I will close it (we will get notifications if you have anything to add).
