### ISSUE TITLE
[0.9.0 develop-21] Chat won't show me my message

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17524]
1, Scroll down to the bottom of the chat window
2. Write something

You expect to see your message, but you won't
![2bef744d5c92575638a8d0efe9ae9f49](https://user-images.githubusercontent.com/27898520/89283725-0f023580-d667-11ea-899c-c644eb040320.gif)

**Comment by gzatravkin** [comment]
Can't reproduce. Still happeans? 
![image](https://user-images.githubusercontent.com/53317567/90347039-1aa91100-e004-11ea-82f4-7a31ef3afe4a.png)

**Comment by beastyn** [comment]
Seems fixed. Maybe was die empty lines.
