### ISSUE TITLE
[0.9.0 develop-21] Civics: can't use decimals in Laws

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17522]
For example in Tax or Payment.
Put 0,5 and it will reset value to 0

![fed1b69601063958b5144d07a9efae70](https://user-images.githubusercontent.com/27898520/89282241-aade7200-d664-11ea-8bb8-ea8ebb6363c4.gif)

It was fixed some time ago, but...

**Comment by olegshegai** [comment]
A tricky one, does not appear in every combination of client/server languages (:
