### ISSUE TITLE
Log details at Eco startup

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17534]
Should log all the information we would have to ask players when submitting bugs
* game version
* RAM (total/available)
* OS detailed version
* CPU info
* Bitness (32/64-bit)

**Comment by WeaselDog** [comment]
Let's finish all other 9.0 issues before doing this.

**Comment by redwyre** [comment]
This is needed before we can consider any kind of issue automation with player logs

**Comment by WeaselDog** [comment]
From @mirasrael 
> When getting crash reports we're usually asking users about some details like game version they're using, GPU RAM, Windows version etc.
> So we need to extend log header with all that info.
> @SlayksWood can you add fields here you're usually asking which isn't available in the log?
