### ISSUE TITLE
Building Materials Art (Forms) T4 Parity

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17539]
**Current Advanced Building Materials 9.0/9.1 Standard Update**:

With 9.0 in Eco, we introduced Ashlar Stone and Composite Lumber, new building materials with great eco-system derived themes and tons of forms to choose from.

**Ashlar Granite:**
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/252a38df-32ed-451f-8e62-e81233027686)

But our old sets are languishing! **We want players to be able to build with more and more forms as they advance through the tech tree. All top tier or late game building materials should have roughly comparable numbers of forms available on them, leading to tons of choice and expressiveness in player-built structures.** The number of forms across different materials does not need to be super strict, as part of the joy of having different sets is that each has unique uses and strengths. The other big part of updating old sets is **adding new unique forms based on what that building material might be used for that others would not. However, often, a previously existing form can be interpreted in a new way with different shapes that makes it look and feel very different.** This should be taken advantage of too.

In addition, the art is simply placeholder for the very few forms that exist on some of the sets, like Flat Steel:
**Flat Steel:**
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/e1c26122-166c-4a27-bc73-8cc27efda19e)

In addition to upgrading our end-game building materials, we want to expand earlier game materials with more options since these are still aesthetic possibilities for players at any point in the game. But for now, the priority is on top tier materials that should feel expansive and exciting, since the players worked hard to get them.

These are the high tier sets that need expansion and improvement to match Ashlar Stone and Composite Lumber, thankfully to start we don't need to include any variants of them, so compared to those two sets they will be a lot quicker to implement.

**Flat Steel**

**Reinforced Concrete**

**Framed Glass**

**Corrugated Steel**

Feel free to start the process for each of these with some quick concepts if you like-- you can also use existing concept art for inspiration, there is much in our old concept art that would be easy to add to block sets but which has not been, like brightly colored roofs, etc. 

Basically, people should take ownership of a particular building material, perhaps asking Milenko for help with needed new triplanars, and start making meshes for the forms they want to add-- for forms that are to be added that already exist in other sets, investigate those forms and their builders, potentially copying and pasting them as a place to start, then working to change their geometry and textures. Any brand new forms/shapes that are nothing like previously existing forms (and thus cannot use existing forms) will need a new icon for the new form.

Once the blockset is finished with new forms all linking to new builders and such, provide sekoris a list of the exact block names to add to the forms list in the tech tree. They'll also need to know about any new forms added to the game and if they are rotatable or not. Since adding an existing form to block material that doesn't have it is easy to do in the tech tree, this can be done by artists directly in the .csv to test their new block forms and art.

**Comment by MilenkoTunjic** [comment]
Can you post a grab of an existing set? Just to show the pieces for general idea.
Also, for materials/textures, we are using triplanar as a base and adding detail, right?

**Comment by keegan-o** [comment]
Each set should be evaluated in-game by whoever is working on it-- I'd have to post a video to get the full point across. I will post details for each set in its respective task issue! There are certain forms which I think should be added to all the sets, and beyond that it's whatever we want to do for each material to make it feel as fleshed out as ashlar stone or composite lumber.

**Comment by keegan-o** [comment]
I think at least these forms should be added to all the materials:

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/582dd044-bba8-4811-970f-57d585939952)

Cube, Floor, Flat Roof
Wall, Window, Double Window, Fence
All Roof Forms: Roof Cube, Roof Peak Set, Roof Peak, Roof Corner, Roof Turn, Roof Side
Basic Slope Side, Basic Slope Point, Under Slope Side, Under Slope Peak (these second two are just rotations)
Column
Stairs, Stairs Corner, Stairs Turn, Ladder

Beyond that, it can be extended per material type as desired--
Obvious things to add would be walls or floors with unique trim, secondary kinds of fences, braces, chimneys for Reinforced concrete, etc.

For brand new forms, the aforementioned trim pieces might be one, another that would be great to have would be 1/2 slope blocks, which could be named 'HalfRampA', 'HaldRampB'. (The second you add those, players will want them for all block materials though) The point though should be to add cool new fun stuff.

**Comment by keegan-o** [comment]
Updates are good enough now to consider these materials in pretty good shape! Future updates will focus on unique forms and new stuff for them.
