### ISSUE TITLE
Framed Glass Building Material (Forms and Art) Update

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17537]
Framed Glass is a kind of unique building material in that it tends to always use multiple materials in the block art to have the glass and its metal framing.

This should be a modern looking material with which you can build bright greenhouses and appealing parts of modern buildings with skylights and areas designed to let in tons of light. 

Right now the set is very minimal and a little clumsy.

Two different kind of aesthetics that could be both represented in different forms in this set are the more industrial/utilitarian greenhouse scaffolding-like forms, and additionally a thinner framed more elegant and clean set of forms for pristine modern buildings. 

_________________

I think at least these forms should be added to all the materials:

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/582dd044-bba8-4811-970f-57d585939952)

Cube, Floor, Flat Roof
Wall, Window, Double Window, Fence
All Roof Forms: Roof Cube, Roof Peak Set, Roof Peak, Roof Corner, Roof Turn, Roof Side
Basic Slope Side, Basic Slope Point, Under Slope Side, Under Slope Peak (these second two are just rotations)
Column
Stairs, Stairs Corner, Stairs Turn, Ladder

Beyond that, it can be extended per material type as desired--
Obvious things to add would be walls or floors with unique trim, secondary kinds of fences, braces, chimneys for Reinforced concrete, etc.

For brand new forms, the aforementioned trim pieces might be one, another that would be great to have would be 1/2 slope blocks, which could be named 'HalfRampA', 'HaldRampB'. (The second you add those, players will want them for all block materials though) The point though should be to add cool new fun stuff.

Not every single form needs to contain both glass and metal, there could be unique bright metal forms without glass included in this set, but those should be more to flesh out things you would want to go with your glass structures, not the focus.

**Comment by keegan-o** [comment]
Keep in mind with this set, it might make more sense to split forms between it and flat steel! That way you could put the scaffolding and such into flat steel, and other parts with no glass in them, and then save all sorts of window and grating with glass and walls and windows and such with glass for this set. The set does not need to be something that mirrors all the other sets, though there should at least be walls and floors and slopes with which a whole building *could* be made.

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/999934da-5be5-4368-9837-0fc9f4628583)
Lots of things like this could be added to flat steel instead:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/360dc57d-952f-4888-bf44-ab099a55ec07)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/1cb85222-7ca8-4dfc-a391-f6a1bafe2998)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/31fd28a4-a65b-4da8-9be1-363bc9df3e6b)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0e655a92-84cb-4b7f-abd9-b1e7fa93b1c6)

**Comment by MeirionHughes** [comment]
possible to make it functional too? so that is raises the temperature?

**Comment by keegan-o** [comment]
Didn't quite finish all the forms but we'll re-approach with the intention to give more unique forms sometime soon instead! Got the basic ones needed, too.
