### ISSUE TITLE
Flat Steel Building Material (Forms and Art) Update

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17535]
Flat Steel is intended to be an endgame building materials used for construction of large modern steel based (or framed) buildings. It should allow sleek, polished, smooth, modern metal surfaces typically dark in color. Some of the different forms could be walls with different surface treatments or colors, to add variety inside the set. It should have good support for modern looking windows of a few different types, and interesting columns. It should have a flat roof form, and should also have the new metal roof form added to ashlar stone. In addition to all these, flat Steel should have fence forms that allow interesting modern decorative grates. Having variants for highly polished and smooth surfaces and matte dark lustery surfaces is a good goal for this set.

_________________

I think at least these forms should be added to all the materials:

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/582dd044-bba8-4811-970f-57d585939952)

Cube, Floor, Flat Roof
Wall, Window, Double Window, Fence
All Roof Forms: Roof Cube, Roof Peak Set, Roof Peak, Roof Corner, Roof Turn, Roof Side
Basic Slope Side, Basic Slope Point, Under Slope Side, Under Slope Peak (these second two are just rotations)
Column
Stairs, Stairs Corner, Stairs Turn, Ladder

Beyond that, it can be extended per material type as desired--
Obvious things to add would be walls or floors with unique trim, secondary kinds of fences, braces, chimneys for Reinforced concrete, etc.

For brand new forms, the aforementioned trim pieces might be one, another that would be great to have would be 1/2 slope blocks, which could be named 'HalfRampA', 'HaldRampB'. (The second you add those, players will want them for all block materials though) The point though should be to add cool new fun stuff.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/6c0948d0-4abd-487f-b0bd-0b166e0c1910)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/7aee5b34-80af-4a7d-8dde-060a24b48cf0)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0e5d288f-ac06-467a-a12a-dbaae48e9334)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/b73a92e8-219d-46ca-8e56-c1bd10cb600d)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/42f74bb5-5abc-46ad-b3bd-4204cf4a3a39)

^ That's what you're starting with, it's very little.

**Comment by keegan-o** [comment]
I think of mies van der rohe for lots of what I'd like this set to be able to accomplish:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/e3d20108-72ff-4a7b-897b-a63a3e7c455a)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/6c5fcff8-9034-4316-b4f8-2c8b1efeb3b6)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/8c49fc30-e7b1-4948-9a4a-8dc0f7d11a9f)
Also highly polished forms:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/a0957a89-c8e9-4194-b446-5e7925a254b8)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/3ac152b7-4642-4494-92bc-59f21c5c0901)

**Comment by RobertMangano** [comment]
I will start work on this one

**Comment by keegan-o** [comment]
Finished, thanks Rob.
