### ISSUE TITLE
Branches not highlighting to cut down.

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1753]
sometimes if you get it just right you can cut them down. but very hard to find and stay in that highlighted area. I'm only speaking of branches with trees that haven't been cut down. I'm trying to clear a little of the areas branches off road so this powered cart can move by.

5.6.1

**Comment by metachronism** [comment]
its currently detecting distance between your feet at the tree/leaves

**Comment by metachronism** [comment]
and not your head/eyes which is what it should be
