### ISSUE TITLE
Resolution mismatch

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17541]
![image](https://user-images.githubusercontent.com/3536496/89344702-22a79f00-d65b-11ea-95cc-e8d6bae082ab.png)
Resolution of picture on the left = good
Resolution of picture on the right = bad

**Comment by serpopov** [comment]
@RobertMangano I saw you have 'large' icons versions but they are baked into 64x64 spritesheet for some reason. Is there different spritesheet for 'large' specialty icons?

**Comment by johnkslg** [comment]
also the cutoff shadow looks bad. We'll need to remove it or make a frame for that icon.

**Comment by johnkslg** [comment]
Ideally these icons can match the profession sketch style @MilenkoTunjic

**Comment by MilenkoTunjic** [comment]
How many icons? is there a list?
If you give the list to me, I can make another sheet for them.

**Comment by RobertMangano** [comment]
@serpopov Those "large" ones were a set of icons that weren't scaled down for the little tier system because those had to be smaller and offset to the left, in hindsight I should have called them "normal" instead of large.

**Comment by serpopov** [comment]
Added large version, however not all icons implemented, @RobertMangano is on it
