### ISSUE TITLE
Server Up, no one can log in

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1754]
I was trying to access stockpile but it would let me, stayed highlighted(guessing from lag) as i was walking around it then i got DCed. tried to log in and it dropped fps for a split second at 2% then stops loading at 4% then timed out. No one can log in either.
5.6.1 -
https://drive.google.com/open?id=0B3rEuklpfVF7emYtSTMyZHBKU3M

**Comment by Fr3aKeD** [comment]
staging - ea761314

**Comment by metachronism** [comment]
should be fixed as of latest staging: #5314c8ac
