### ISSUE TITLE
Arachnophobia mode still shows particle spiders

### ISSUE THREAD

**Issue by TristanWinkworth** [StrangeLoopGames/EcoIssues#17566]
![image](https://user-images.githubusercontent.com/29963255/89432085-af5f6500-d70e-11ea-8e46-a8abdab5bf8c.png)

Mode is turned on, small spiders still appearing.

**Comment by mirasrael** [comment]
Did you relogin to the game after setting this?

**Comment by TristanWinkworth** [comment]
Re-log appears to correctly remove all spiders.

Resolved.

**Comment by mirasrael** [comment]
It actually said in tooltip for setting. It is hard to apply it to living world and it isn't intended to be changed often. So guess it should be fine ;)
