### ISSUE TITLE
Red coding flashing over my screen

### ISSUE THREAD

**Issue by DivineMadness1** [StrangeLoopGames/EcoIssues#17562]
[2020-08-05 19-57-29.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5027622/2020-08-05.19-57-29.zip)

It is flashing the red coding stuff whatever it is.

**Comment by beastyn** [comment]
You are playing with developer build (right bottom corner), which we are using for better testing purposes. You can press F7 to see this log. Sometimes its flickering if error log is big.

**Comment by DivineMadness1** [comment]
Do you want the log file i have or you dont need it?

**Comment by beastyn** [comment]
If you have some specific action that causing some specific error - yes, it will be helpful to get this information from you with a log file attached.
