### ISSUE TITLE
0.9.0.0 - beta staging-1702 - Waste dont get Compost

### ISSUE THREAD

**Issue by mepHy86** [StrangeLoopGames/EcoIssues#17560]
Drop Plant Fiber or Raw Food on the ground:

![20200805085210_1](https://user-images.githubusercontent.com/63646359/89381327-45889080-d6f9-11ea-9699-79c80dba6060.jpg)

wait one Day:

![20200805085215_1](https://user-images.githubusercontent.com/63646359/89381348-4de0cb80-d6f9-11ea-8571-7ae925a0ba4a.jpg)

I think there is a Tick or something missing to define is it "real waste" or Compost

**Comment by SlayksWood** [comment]
@mepHy86 Do you use fastforward?
Don't have this issue in develop-22

**Comment by mepHy86** [comment]
Its on White Tiger and i have no admin rights ;)

**Comment by mepHy86** [comment]
I replaced them after server update yesterday and it still does not get compost or waste

![20200806090402_1](https://user-images.githubusercontent.com/63646359/89501631-f52a3500-d7c3-11ea-9a25-498265af9aba.jpg)

**Comment by IcedForge** [comment]
Still an issue on 0.9.0.0 beta staging-1714
![Screenshot_449](https://user-images.githubusercontent.com/24981362/90010985-1649c480-dca1-11ea-9d3e-3ba24badeb4f.jpg)

**Comment by beastyn** [comment]
Something is definitely wrong, but sometimes it won't turn into compost, sometimes it will (with /ff it will).
Sometimes it stays in the first model, sometimes in the second one.
But after restart it usually the firstone,

Use this save for checking the compost.
There are three packages, they were at the last decaying stage, but after restart became like first garbage model.
And you still can take a seed from it (you should not be able to).
43, 61, 460

It will look like this
![bandicam 2020-08-21 11-18-16-497](https://user-images.githubusercontent.com/27898520/90858766-3fa0d980-e3a0-11ea-8b1b-fd403450bf97.jpg)

https://drive.google.com/file/d/1u-P4Gt_XQbnTcRqn3GE1PCCybthTtpjD/view?usp=sharing

**Comment by BrewCrewECO** [comment]
After having admin delete the garbage objects that were created with this bug, after a server restart the garbage re-appears. 
Build 1732.

**Comment by mepHy86** [comment]
Build 1740 on Giant Panda still an Issue.

**Comment by beastyn** [comment]
@mepHy86 yeap, it will be in 1741 version )
