### ISSUE TITLE
Graphics settings dont remember their saved settings until you press 'escape'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1756]

**Comment by SeanAtr0n** [comment]
I fixed the time lock one, need to refactor EscapeMenu a bit to fix the others... some of their values depend on data stored in the prefab :(

**Comment by SeanAtr0n** [comment]
Looks like Eric removed my fix for time lock in svn a while back, guess it doesn't matter as we are getting rid of the feature
