### ISSUE TITLE
0.9.0.0 - dev-23 | Contract Board - Multiply issues 

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#17567]
Contract board has many issues atm. Listing them one by one.

- [x] 1. Clause "Build Road" 

You can't click the "Type" button to choose which type of road you want to be built. 
Pic: 
![image](https://user-images.githubusercontent.com/32419758/89433768-ff581f00-d742-11ea-93ea-867a09ea31a1.png)

- [ ] 2. Completed contracts are still visible in "Economy Viewer"

2 contracts which are both marked as finished are still visible and has tag "Waiting for Review" (see pic)
Contractor got payment when i finished the contract via the contract board. Contract is gone from the board.
Pic:
![image](https://user-images.githubusercontent.com/32419758/89434026-5958e480-d743-11ea-8c45-2b3ac0620af3.png)

- [ ] 3. Discription gone?

When looking on the contract board i could see all information stated in the contract, but when hovering the contract that open up a tooltip box some information is gone. (see pic)
Pic:
![image](https://user-images.githubusercontent.com/32419758/89434275-a63cbb00-d743-11ea-9a87-de6858a7a3b2.png)

- [x] 4. Can't remove the last clause if you add more.

If you click "add clause" in a contract you can't remove it if it's the last one. The remove button for the last clause in the list are place under the "ADD CLAUSE" border/button. (see pic)
Pic:
![image](https://user-images.githubusercontent.com/32419758/89434828-50b4de00-d744-11ea-814d-864e401c4c45.png)

**Comment by SlayksWood** [comment]
@NemoLArs Can you more describe 3rd point?

**Comment by NemoLArs** [comment]
Sure! :) 

You can see thru the "tooltip box" that the contract has a discription. But when hover the name and the tooltip box appears that information is gone and stated as Invalid, that the clause is missing.

**Comment by serpopov** [comment]
2/4 fixed, need to split this issue @beastyn

**Comment by beastyn** [comment]
@serpopov yessir!

So, only checking for 1 aqnd 4
2 is here #18284
3 is here #18285
