### ISSUE TITLE
[0.9.0 develop-23] Numbers are too big in UserStatus Bar

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17563]
![image](https://user-images.githubusercontent.com/45708377/89416098-71c20280-d735-11ea-89fd-503d8edfad8d.png)

**Comment by SlayksWood** [comment]
Seems text size for speed is small too:
![image](https://user-images.githubusercontent.com/45708377/89416288-b3eb4400-d735-11ea-83c4-617da13d5fd8.png)

**Comment by johnkslg** [comment]
Must have some kind of size alreation tags on it
