### ISSUE TITLE
[0.9.0 develop-23] Animals don't know how to move on ramp

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17564]
https://drive.google.com/file/d/1YE7v4zDZPFVaE2DO-BXONmgEFWM0mlKC/view?usp=sharing

**Comment by SlayksWood** [comment]
Still an issue: https://drive.google.com/file/d/1saNtAlAoa9abkn5rTQngwqi0jXD0wRcF/view?usp=sharing

**Comment by mirasrael** [comment]
Fixed in SVN (both staging and develop).
