### ISSUE TITLE
[0.9.0 staging-1706] Hide Asphalt concrete Ramp

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17578]
![image](https://user-images.githubusercontent.com/45708377/89506483-d6cc3580-d7d3-11ea-857d-1f847e2b58dd.png)

**Comment by WeaselDog** [comment]
Taking over this one

**Comment by WeaselDog** [comment]
We need to rename it back to original name, hide it, and make sure it is setup for migration.

**Comment by SlayksWood** [comment]
I assigned this issue to Stanislav because it appeared after his fixing for command /road #16581.
Currently this command is broken again for Asphalt concrete.
