### ISSUE TITLE
0.9.0.0 Develop-23 : Map zoom causes visual issues?Water?

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17572]
Zooming in and out layers out portions of water regions
![white_tiger_weird_stuff](https://user-images.githubusercontent.com/24981362/89471640-f84f0200-d77e-11ea-87f1-787056c38c54.jpg)
As compared to this where the "shallow" water is clearly there, but on zooming in it removes a layer of water displaying dirt & rock instead.
![Screenshot_370](https://user-images.githubusercontent.com/24981362/89471666-0866e180-d77f-11ea-8a24-59c8a523f52f.jpg)

**Comment by SlayksWood** [comment]
@IcedForge Can you provide your PC specification and graphics settings?
merged to #16684

**Comment by IcedForge** [comment]
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5038404/DxDiag.txt)
![Screenshot_1223](https://user-images.githubusercontent.com/24981362/89590386-159bd300-d848-11ea-9823-7ac1b025d9c6.jpg)
