### ISSUE TITLE
Server crash 5.6

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#1757]
Server Crash
Host: Dawn Server
Crash occurs during a vote (kill law on bison max 3/day
I think it's reproductible.
Version 5.6
crash.ecodmp added in attachment (just renamed .txt)

Game.eco:
https://www.dropbox.com/s/lrw1ysk0lg3we66/Game.eco?dl=0

Crash.ecodmp
https://www.dropbox.com/s/1xhg0ng3wgv4roh/Crash%2007010433.ecodmp?dl=0

**Comment by Amphysbaenas** [comment]
Not solve in [0.5.6.1]

**Comment by MarjieAVolk** [comment]
This should be fixed in the next release
