### ISSUE TITLE
 0.9.0.0 Develop-23 : clarify tax notification

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17573]
When a user does not have enough money to be taxed via sale by a store it will tax correctly, but the text says 0 tax
![Not_taxing_](https://user-images.githubusercontent.com/24981362/89471827-672c5b00-d77f-11ea-96b7-3775c4841fc1.jpg)

Like stated, it taxed correctly ( checked the funds afterward ) but the player tax notification does not display the tax withdrawn from the sale itself.

**Comment by SlayksWood** [comment]
You paid that mean that you buy items, Only the one who sells pays the tax. You can see when I buy and sell in Anna's Store 
information for me:
![image](https://user-images.githubusercontent.com/45708377/89507864-c6b55580-d7d5-11ea-9f27-f9d2c78de215.png)
information for Anna:
![image](https://user-images.githubusercontent.com/45708377/89508131-26abfc00-d7d6-11ea-8f97-9c44d1e4c34c.png)

Seems we need a little clarify this messange. So
![image](https://user-images.githubusercontent.com/45708377/89508500-ac2fac00-d7d6-11ea-8f53-c25b1439ca76.png)

**Comment by SlayksWood** [comment]
Still an issue. Beastyn store, I bought and then sell 1 bannock. From mine side:
![image](https://user-images.githubusercontent.com/45708377/94010125-2e3b5a80-fdae-11ea-8bb6-46481d340001.png)
If I don't pay tax, I should not have you pay tax 0(10%):
![image](https://user-images.githubusercontent.com/45708377/94010276-617de980-fdae-11ea-9096-0ed34bd64217.png)
You can change it to Beastyn paid tax or just delete it to avoid confusing people.

From Beastyn side:
![image](https://user-images.githubusercontent.com/45708377/94010386-8c683d80-fdae-11ea-8a98-efee1f9992d4.png)
When I sold item to her I still paying her. Should be like:
![image](https://user-images.githubusercontent.com/45708377/94010817-1b755580-fdaf-11ea-9785-f42199690901.png)
