### ISSUE TITLE
Add modkit to download links on accounts site

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17574]
A modkit zip file is now included alongside the game and server builds, eg for staging:
```
https://eco-releases-staging.s3-us-west-2.amazonaws.com/EcoPC_v0.9.0.0-beta-staging-1706.zip
https://eco-releases-staging.s3-us-west-2.amazonaws.com/EcoServer_v0.9.0.0-beta-staging-1706.zip
https://eco-releases-staging.s3-us-west-2.amazonaws.com/EcoModKit_v0.9.0.0-beta-staging-1706.zip
```

I've used the same format for the file so hopefully that makes it easy for you :) Let me know if you need anything else.

**Comment by denysaw** [comment]
@redwyre Add that only on new (staging) site or on current prod also?

**Comment by redwyre** [comment]
Just staging for now, can get added to prod when you push the new site
