### ISSUE TITLE
[0.9.0 staging-1706] Steam tractor harvester should be lifted when turned off

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17582]
this part:
![image](https://user-images.githubusercontent.com/45708377/89524538-6c27f380-d7ed-11ea-85b8-23f4dbec29f1.png)
Because now I can't move on Ramps:
![image](https://user-images.githubusercontent.com/45708377/89524588-81048700-d7ed-11ea-8bde-29134f54c570.png)

**Comment by MazonDel** [comment]
Fixed, you'll have to update your SVN from /trunk to see the fix.

The harvester front will start raised, then when the player presses Q it animates a lowering and then rotation till Q is pressed again, which then stops the rotation and animates the raising.

**Comment by IcedForge** [comment]
Changes to this caused the steam tractor harvest tool to not function at all, neither animations nor actual mechanic.
