### ISSUE TITLE
EcoServer 5.6.1 #3810b5df - client hangs on entering world

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#1758]
I logged out about 6 hours ago after preparing for and starting a laser project. Now when I login, as soon as I enter the world, the game client hangs and goes permanently "Not Responding". I have tried this multiple times. Currently the longest I have let it wait in "Not Responding" state is about 20 minutes.

Killing/restarting the server did not resolve this.

The Game.eco can be found at:
https://drive.google.com/open?id=0By3yTnmDe0ulRXI0bU83NnFrMVU

**Comment by pamduncan** [comment]
game is crashing before a dump file is created - which is why he has none to post.  This was a 5.6 world migrated to 5.6.1 a couple of days ago

**Comment by pamduncan** [comment]
This was solved by installing the latest 5.6.1 staging on both client and server.  This issue can be closed
