### ISSUE TITLE
Put minted currency at the top of the list in currency list menu

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17586]
Minted currency are the one that have the most chance to be used.
They should be shown above player currency in the currency list menu to help selecting them.

**Comment by IcedForge** [comment]
Contracts, Work partys & store credits selections are still listing personal accounts at the top.
![Screenshot_55.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/6b1aaf94-2758-4cbe-a8e5-aff233ebec1d)

**Comment by gabrielgindridev** [comment]
We will keep the multi-selector as is because it will get refactored. e.g.:
![image](https://user-images.githubusercontent.com/65634950/94476264-a5a22d00-01a6-11eb-8b48-71f1a7cbe96c.png)
