### ISSUE TITLE
/meteor spawn should be admin level

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17596]
Currently it's developer level, but it should be possible to add a meteor after at first deciding to not have one. As /meteor destroy is available to admins, it's not a dangerous command either.

**Comment by hegemonart** [comment]
is there a limit, how much meteor can be spawned with that command per server?

**Comment by MazonDel** [comment]
> is there a limit, how much meteor can be spawned with that command per server?
> 
> if not, there should be

@hegemonart Why should there a limit in how many meteors the admins can spawn in a server? Presumably if the players can blast one of them, they can handle more.
