### ISSUE TITLE
0.9 localization: Hunting description strings lost from crowdin

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17594]
![изображение](https://user-images.githubusercontent.com/4980243/89530273-e6a94100-d7f6-11ea-8ef9-284fc55d31c6.png)
![изображение](https://user-images.githubusercontent.com/4980243/89530319-f9237a80-d7f6-11ea-838d-c3d6b3f8e999.png)
"Увеличивает как близко вы можете подойти к животным"

p.s.
Also, guys, can you do something to stop these things from happening? It's really annoying.

**Comment by Quadbro** [comment]
you can be carefull too, because this one became modular, and the translation is 
![image](https://user-images.githubusercontent.com/6802030/89975422-e219d800-dc8f-11ea-8b96-150626fd9535.png)

**Comment by Quadbro** [comment]
closing cause there is no issue
