### ISSUE TITLE
0.9 localization: "benefits" in benefits is not localized

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17595]
As i see this string exists on crowdin, but not used there.

![изображение](https://user-images.githubusercontent.com/4980243/89530452-2e2fcd00-d7f7-11ea-894e-f4ed9538c484.png)
etc.

**Comment by Quadbro** [comment]
string is used, but has no translation, will be autofixed in next strings sync

**Comment by Quadbro** [comment]
approved translations and added loc sync
