### ISSUE TITLE
0.9.0.0 beta Develop-23 : Accept contracts with no permissions on Contract board

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17598]
1. Conflicting permissions for taking on contracts via Contract Board.
Here i have removed EVERYONE from a contract board - Added Mishka
Yet Hiogu can Take any contract i post via this board using the direct Y interface for contracts.
![Screenshot_376](https://user-images.githubusercontent.com/24981362/89538692-2eca6280-d7fb-11ea-9c8b-20c2b9686ed4.jpg)
As telling by this, she has clearly accepted the contract and the contract itself works fine ( in this case LOAN OFFER )
![Screenshot_377](https://user-images.githubusercontent.com/24981362/89538704-31c55300-d7fb-11ea-9b31-25f07330ff97.jpg)

2. Expected outcome, If you do not have permissions to access a contract board, you should not be able to accept contracts listed on said board.

**Comment by beastyn** [comment]
Lets make what is easier right now as we will change contracts/party logic later.
@gzatravkin  How will be easier to fix it right now?
1) You should not be able to see contracts if you do not have an access to the board with it.
2) You don't see Accept button if you do not have a permission
3)  Or just remove Accept button at all for Economy viewer for all the contracts

**Comment by IcedForge** [comment]
From a player perspective of things i would assume it wouldnt let me accept a contract without opening the board itself since as of right not it does require you to be inside a very close proximity of it already, so i would personally suggest option 1 and 3

**Comment by gzatravkin** [comment]
I did 2 for now. 
Hides button in case of no permission to accept
