### ISSUE TITLE
[0.9.0 staging-1706] Auth returns invite error when trying to login in-game

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17593]
History has happened on stagingland

1. Acc1 has bought and send invite to Email2 (account has not been existed)
2. Email2 go with link from the email and register Acc2
3. Acc2 is entering a SITE account SUCCESSFULLY.
4. Acc2 is going to launch a game and log in
5. Acc2 is sad, he could not log in
![Inkedbandicam 2020-08-06 16-21-03-465_LI](https://user-images.githubusercontent.com/27898520/89528607-c5e7e800-d804-11ea-892d-01dacfee6125.jpg)
6. And now site is rejecting him too, painfully
![bandicam 2020-08-06 16-50-44-410](https://user-images.githubusercontent.com/27898520/89528776-10696480-d805-11ea-8f7b-d5b7ec86e4ab.jpg)

It's coming from here #17328

**Comment by redwyre** [comment]
@denysaw is this related to the recent invite issues?

**Comment by denysaw** [comment]
@redwyre Yes, but that was on Accounts website side and already fixed. Now invites should be fixed in a similar way on Auth side, cuzz it doesn't allow invited person to login and even breaks his DB row so ONLY AFTER IN-GAME login attempt it forbids to login.

**Comment by denysaw** [comment]
Ok, I've found the issue in `Auth` project myself. Will push soon.
Issue was here:
![image](https://user-images.githubusercontent.com/5720101/89628684-f2e7d980-d89c-11ea-98fc-217fb0fa352e.png)
We already don't check for inviter's product as now users could sign up w/o owning Eco and easily buy invitations w/o owning any tier.
