### ISSUE TITLE
0.9 issue with text in specialities interface

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#17590]
open specialities (z)
select any category, select any profession available to add star. Text about star is broken
![изображение](https://user-images.githubusercontent.com/4980243/89529018-acd73b00-d7f4-11ea-9515-746637423137.png)

select any non-researched profession.
Specialities names broken
![изображение](https://user-images.githubusercontent.com/4980243/89529059-bf517480-d7f4-11ea-8f04-2b11398fc4ed.png)

**Comment by SlayksWood** [comment]
This happens for me only in Russian or as I assume non-latin (checked English, German and Russian).

**Comment by Quadbro** [comment]
One of the most random and strange loc problem i ever seen
