### ISSUE TITLE
[0.9.0 staging-1708] Can take Dirt Road block in hands in non-English 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17608]
Step to reproduce:
- start client and server in any non-English language.
- try to dig Dirt Road. checked in Russian, Korean and German:
![image](https://user-images.githubusercontent.com/45708377/89615027-54547c00-d88e-11ea-88bf-bc4053dcbeff.png)
But it works fine in English and what's more alarming in Gibberish
Seems we have some troubles in localization, that we don't have in English #17590

**Comment by Quadbro** [comment]
Looks like happens after this one https://github.com/StrangeLoopGames/EcoIssues/issues/16500
