### ISSUE TITLE
USER ISSUE: lost house value

### ISSUE THREAD

**Issue by ichfallen** [StrangeLoopGames/EcoIssues#17600]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
host a solo world
quit and launch as I play it
reached level star 7

**Expected behavior:**
nothing should have change

**Actual behavior:**
hoouse value droped to zero and it seems no more exp from it too

**Do you have mods installed? Does issue happen when no mods are installed?:**
hoouse value droped to zero and it seems no more exp from it too. Tryed it on two different hosted world.

**Comment by beastyn** [comment]
@ichfallen thank you for the report.
Can you provide a log file? (instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file) 

Did you try to replace some building blocks (like pickup and place a wall block) or replacing some furniture?

Also to have screenshots will be nice too.

**Comment by beastyn** [comment]
Closing due no feedback. Did not meet in 9.0, will take it into consideration.
