### ISSUE TITLE
0.9.0.0 beta staging-1706 : Manage treasury with TAX no allowed permission denied on personal account.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17604]
When trying to use action TAX in a executive office desk on a players personal account it will not approve and give following error due to not having access or permissions to this account.
![d1fe92e0b8a46ca28d068ff4140ebcf6](https://user-images.githubusercontent.com/24981362/89582873-a3bc8d00-d839-11ea-96b9-fc5a0b25afc8.png)

But it will give a notification saying the player was indeed taxed the amount which is not the case money was never transfered over.
![6e7be4ae5e6b44d5909e02ba6cec7ee0](https://user-images.githubusercontent.com/24981362/89582939-c058c500-d839-11ea-8496-8622dea55b54.png)

Steps to reproduce.
Send money to player, go to a executive office and use direct tax on player .

**Comment by beastyn** [comment]
@IcedForge thank you for the report.
Can you make a screenshot with executive action?
Maybe some special conditions or something?
I was able to tax a person just fine. 
![bandicam 2020-08-07 14-42-49-670](https://user-images.githubusercontent.com/27898520/89632925-782eb680-d8bc-11ea-90b7-8c7e640c31a9.jpg)
![bandicam 2020-08-07 14-44-01-662](https://user-images.githubusercontent.com/27898520/89632936-7a911080-d8bc-11ea-8c26-a0f10907f7df.jpg)

**Comment by IcedForge** [comment]
Clarification now, as i wasnt the person who did it, he tried to do it via the Treasury object "Manage Treasury". so that would be another bug i guess?

**Comment by beastyn** [comment]
So.
If you are a title with Manage access you still can't tax anyone, because you Don't have permission to an other person's account.
