### ISSUE TITLE
Mortared Stone stuck in Storage Chest

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1760]
Quarry put them all into the storage instead of the Stockpile. I tried to move to Carrying slot or Stockpile and got error of "Martared Stone can only be carried." 

[![Screenshot from Gyazo](https://gyazo.com/2847e10ecd8c1e092c666afeb3f47bc4/raw)](https://gyazo.com/2847e10ecd8c1e092c666afeb3f47bc4)

Version - 5.6.1 Staging ea761314

**Comment by MarjieAVolk** [comment]
Duplicate of StrangeLoopGames/EcoIssues#1729
