### ISSUE TITLE
[0.9 staging-1706] Extreme lag with Civic ticks

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17607]
On the white-tiger playtest, they are significant lag spikes during civic ticks. This can cause a ping to go from 180 to 2000. It is severe enough that items are getting desynced, causing item duplication and loss.

The following demographic is especially troublesome because it checks all the property of every play.
![LaggyDemographic](https://user-images.githubusercontent.com/47330823/89594548-f597ef80-d806-11ea-9e5f-af2abcc4f31e.jpg)

**Comment by beastyn** [comment]
Tested with some WT save. Should be checked on the live playtest too.
