### ISSUE TITLE
[0.9.0 staging-1708] Ecopedia: check picture quality/size

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17609]
Banners are looking great, but in the Ecopedia they are looking far worse.
For comparison:
![bandicam 2020-08-07 11-55-59-131](https://user-images.githubusercontent.com/27898520/89618144-01d28a00-d8a5-11ea-8f8a-ccb169ccb41e.jpg)

**Comment by beastyn** [comment]
If its time consuming - push it to 9.1.

**Comment by gzatravkin** [comment]
Fixed by SVN changes (size up images)
![image](https://user-images.githubusercontent.com/53317567/89724744-8d4f3680-d9dd-11ea-8c44-4eb780456890.png)
