### ISSUE TITLE
Citizen password ux

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17617]
When world owner creates or edits a citizen password. It displays the password too short of time in notification. Plus if you try to highlight the password text and copy it. The notification is immediately removed from the click.

Set these password notifications to stay on screen until page reload. And not disappear from click.
Or if that's hard, you can setup some other type of notification for passwords.

**Comment by denysaw** [comment]
@j3fffff Wat? )) Citizen owner (parent acc) JUST entered (or copy-pasted) NEW citizen password. And hit enter. Why does he need to copy-paste it again from notification? Even attempt to do it. I just changed notification from the one containing password to just: "Citizen's password successfully changed". Sending many times unencrypted password isn't a good practice anyway...

**Comment by j3fffff** [comment]
Oh, youre right, edit password works good.

Buuut, reset user, doesnt. when you enter new username, it auto creates a password.

**Comment by beastyn** [comment]
@denysaw yeap, resetting is a problem, give it back to you

**Comment by denysaw** [comment]
Really ;) Done, could be tested on staging ;)
