### ISSUE TITLE
Steam linking not working

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17618]
steam linking doesnt seem to work on staging

im getting return url from Steam, and i change domain to staging, so it looks like this:
https://accounts.stagingland.strangeloopgames.com/account#access_token=74b94f36f7d79f0c1505deca03736422&state=%7B%22user%22%3A%22178193%22%2C%22token%22%3A%220ef2860384e5dcaeff5b13b337d2fe34%22%7D&token_type=steam&steamid=76561197962315748

but doesnt do anything when i get to account page. no errors

**Comment by redwyre** [comment]
I think the relevant docs are here: https://partner.steamgames.com/doc/webapi_overview/oauth

Might just need to update the url in the initial request

**Comment by denysaw** [comment]
Re-checked. Everything working. The problem was in URL:
![image](https://user-images.githubusercontent.com/5720101/91647832-b9e7f280-ea5f-11ea-82e8-ee2e31fa2b53.png)

Instead of `hash` sigh `#`, should be standard `?`. So this fixed url worx good:
https://accounts.stagingland.strangeloopgames.com/account?access_token=74b94f36f7d79f0c1505deca03736422&state={%22user%22%3A%22178193%22%2C%22token%22%3A%220ef2860384e5dcaeff5b13b337d2fe34%22}&token_type=steam&steamid=76561197962315748

**Comment by j3fffff** [comment]
OK, looks like steam hardcodes the #, instead of using ?
Can you update so our site looks for the #

**Comment by denysaw** [comment]
@j3fffff So which part of URL you can edit? Before # and after? If you could edit after-hash part just put `steam?` in the beginning, so final url would look like: `https://accounts.stagingland.strangeloopgames.com/account#steam?access_token=74b94f36f7d79f0c1505deca03736422&state={%22user%22%3A%22178193%22%2C%22token%22%3A%220ef2860384e5dcaeff5b13b337d2fe34%22}&token_type=steam&steamid=76561197962315748` and that's it. Cuzz server side have no access to hash (which will be `access_token` in our case).

**Comment by beastyn** [comment]
So, it;s a Jeff's part now, moving to hm.

**Comment by j3fffff** [comment]
i cant edit after hash. should be ok to just look for steamid parameter

**Comment by denysaw** [comment]
Server won't feel that part of url. Cuzz there's no `?` at all.
Steam hardcodes WHOLE this part of url `#access_token=74b94f36f7d79f0c1505deca03736422&state=%7B%22user%22%3A%22178193%22%2C%22token%22%3A%220ef2860384e5dcaeff5b13b337d2fe34%22%7D&token_type=steam&steamid=76561197962315748`  ?

**Comment by redwyre** [comment]
Unfortunately that's just how steam (and some other oauth implementations) works: https://partner.steamgames.com/doc/webapi_overview/oauth
You will just have to post or redirect in javascript to a server endpoint. The `state` parameter is our data from the request.

**Comment by denysaw** [comment]
@redwyre Ahaaa.. Really. Seems it was done with sane intention: `Note that the response (including the token) is provided in the URI fragment, so it will need to be accessed client-side and passed back to your server if you need to do server-side requests.`
So only client logic could read that. Ok, will do client logic then ;)
