### ISSUE TITLE
Blast furnace does not generate sewage during operation.

### ISSUE THREAD

**Issue by sasap95** [StrangeLoopGames/EcoIssues#17611]
If you put a blast furnance and a Wastefilter (without owner), no Sewage will be generated.

See:
![bug](https://user-images.githubusercontent.com/65181812/89635358-2d567400-d8a7-11ea-8e47-05ca86f2dff6.jpg)

![bug2](https://user-images.githubusercontent.com/65181812/89635968-1ebc8c80-d8a8-11ea-9d1e-8f6bfbcf58e7.JPG)

**Comment by SlayksWood** [comment]
Thank you for the report.
dup #12484
