### ISSUE TITLE
Trees in water Can't be cut

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1761]
It's ones that get in water with branch if you don't cut the branch right away there is a chance it wont be cut at all. The Branch will become unclickable(highlighted) no mater what angle you go from so makes the tree unable to cut cause said branch.

**Comment by SeanAtr0n** [comment]
I'm having a hard time reproducing this, maybe it got fixed already...
![image](https://user-images.githubusercontent.com/774628/28990800-a54c4450-7935-11e7-9c07-e4f000042af6.png)

**Comment by SeanAtr0n** [comment]
I'm guessing this was fixed w/ one of Marjie's property changes, closing for now... please reopen it if you see it again
