### ISSUE TITLE
Fish trap showing in salt water when in river

### ISSUE THREAD

**Issue by RaptorX23YT** [StrangeLoopGames/EcoIssues#17626]
ECO 9.0 beta_playtest

steps to reproduce: place a fish trap in a river away from the ocean

expected result: Fish trap should show active and working

Actual result: Fish trap shows that it needs to be placed in salt water, despite having been placed in what is shown to be freshwater on both the map and according to logic. fish trap will not work.

![20200809064018_1](https://user-images.githubusercontent.com/69419464/89730264-4a0bbc80-da0b-11ea-8cbf-44d4628605e9.jpg)
![20200809064034_1](https://user-images.githubusercontent.com/69419464/89730266-4aa45300-da0b-11ea-897f-2e503df00c29.jpg)

![20200809063916_1](https://user-images.githubusercontent.com/69419464/89730290-6dcf0280-da0b-11ea-8dc8-64a9dfa5bb3e.jpg)
![20200809064004_1](https://user-images.githubusercontent.com/69419464/89730291-6e679900-da0b-11ea-89e7-ba178dbd0f27.jpg)

**Comment by SlayksWood** [comment]
Could there be a problem due to fresh water disappears over time? We have this issue before, but I can't check it because Fresh Water Layer doesn't work:
![image](https://user-images.githubusercontent.com/45708377/89777448-65aeba00-db14-11ea-9391-6e5351300c59.png)

**Comment by RaptorX23YT** [comment]
I'll take a look at it later today. I'm not really sure if there is a way
to check that, but the salt water should show that, and I did not see it on
my map.

**Comment by RaptorX23YT** [comment]
It does appear to be from salt water spread, although it seems to be a lot more than you would expect.
![20200810200455_1](https://user-images.githubusercontent.com/69419464/90078169-04344a00-dcd2-11ea-8fda-d017d6e5c7a3.jpg)

As you can see from the slightly purple / gray area, it has spread way into the rainforest

**Comment by Quadbro** [comment]
@SlayksWood Will be fixed in incoming pr, but you need to trigger layer rebuild for layers update. The easiest way will be to clear storage and start a new world
