### ISSUE TITLE
3 small bug's

### ISSUE THREAD

**Issue by LuZiferdk** [StrangeLoopGames/EcoIssues#17627]
In the  first and 2nd pic you  can see i can acces the  stokpite true the  log/housewall and i cant tuchs the wall ecpt  wen  i look to the side wher  the  stokpite  is not…

3 and 4 pic i whors jumping to get a ston  5 blocks up over that  is 2  layers off stone  and i  cute  tuchs the  stokpit true the 2  layers off stone

5  and 6 pic is a raw roast 600 cal and a campfire  roast 100 cal i think  is shut say  1000

![wall 1](https://user-images.githubusercontent.com/37664204/89736612-e9ac6780-da6a-11ea-9476-f0a155f6617f.jpg)
![wall 2](https://user-images.githubusercontent.com/37664204/89736615-ed3fee80-da6a-11ea-8037-25a12f0a15ae.jpg)

![mine 1](https://user-images.githubusercontent.com/37664204/89736625-f466fc80-da6a-11ea-9551-9ac3385c8f43.jpg)
![mine 2](https://user-images.githubusercontent.com/37664204/89736630-f92bb080-da6a-11ea-8083-daa0a349729e.jpg)

![roast 1](https://user-images.githubusercontent.com/37664204/89736635-ffba2800-da6a-11ea-9ebb-8ea3f1a332e5.jpg)
![roast 2](https://user-images.githubusercontent.com/37664204/89736637-034daf00-da6b-11ea-9d19-90b1b9c06568.jpg)

**Comment by LuZiferdk** [comment]
by  the  way  the  small  cart dossent show ho many kg the r is in it

**Comment by SlayksWood** [comment]
@LuZiferdk Thank you for the report. Please don't create 1 issue for different problems and use template:
1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files.

About you issues

> In the first and 2nd pic you can see i can acces the stokpite true the log/housewall and i cant tuchs the wall ecpt wen i look to the side wher the stokpite is not…
we have another issue #17251

> 5 and 6 pic is a raw roast 600 cal and a campfire roast 100 cal i think is shut say 1000
fixed here : https://github.com/StrangeLoopGames/Eco/pull/6540

> by the way the small cart dossent show ho many kg the ar in it
I reopen issue #17332


> 3 and 4 pic i whors jumping to get a ston 5 blocks up over that is 2 layers off stone and i cute tuchs the stokpit true the 2 layers off stone
Can you describe it more?

**Comment by LuZiferdk** [comment]
Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

Fra: Kirill<mailto:notifications@github.com>
Sendt: 10. august 2020 08:48
Til: StrangeLoopGames/EcoIssues<mailto:EcoIssues@noreply.github.com>
Cc: LuZiferdk<mailto:luzifer@live.dk>; Mention<mailto:mention@noreply.github.com>
Emne: Re: [StrangeLoopGames/EcoIssues] 3 small bug's (#17627)


@LuZiferdk<https://github.com/LuZiferdk> Thank you for the report. Please don't create 1 issue for different problems and use template:

  1.  Version
  2.  Steps to reproduce.
  3.  Expected behavior.
  4.  Actual behavior.
  5.  Providing Log files.

About you issues

In the first and 2nd pic you can see i can acces the stokpite true the log/housewall and i cant tuchs the wall ecpt wen i look to the side wher the stokpite is not…
we have another issue #17251<https://github.com/StrangeLoopGames/EcoIssues/issues/17251>

5 and 6 pic is a raw roast 600 cal and a campfire roast 100 cal i think is shut say 1000
fixed here : StrangeLoopGames/Eco#6540<https://github.com/StrangeLoopGames/Eco/pull/6540>

by the way the small cart dossent show ho many kg the ar in it
I reopen issue #17332<https://github.com/StrangeLoopGames/EcoIssues/issues/17332>

3 and 4 pic i whors jumping to get a ston 5 blocks up over that is 2 layers off stone and i cute tuchs the stokpit true the 2 layers off stone
Can you describe it more?

3 and 4 pic i whors  jumping up to get a lose stone in the  seling  wen  i prest  e i open  up my  stokpite on the ground 7  or 8  blocks up true the stone just like whit  pic 1 and 2 wher i cute acces my stokpite   true the  wall…..sorry for my spelling bot i am dyslexic,

p.s. sorry for the way i made the report i have difficulties whit understanding som Words… so i just made the report i thort better to make it then not to

have a nice day

**Comment by beastyn** [comment]
Thank you. That should be fixed with #17251
