### ISSUE TITLE
Typo in FuelSupplyComponent

### ISSUE THREAD

**Issue by FyreAus** [StrangeLoopGames/EcoIssues#17620]
Currently in the FuelSupplyComponent the Property FuelTags reads

`public IEnumerable<string> FuelTags => this.FuelTags;`

and is therefore self-referencing and never assigned correctly.

It should be
`public IEnumerable<string> FuelTags => this.fuelTags;`
to correctly reference the private field that is initialized by the WorldObject.

**Comment by mirasrael** [comment]
Yeah, you're right. But seems only usage for FuelTags is FuelTags itself :) So it is why it doesn't fail with infinite recursion. Will expose it for mods though.
