### ISSUE TITLE
[0.9.0.0 beta staging-1706] Auto Scroll chat spam when building

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#17621]
When using the hammer to place/remove blocks the chat window will start auto scrolling frequently and sends the chat back to an earlier time, this will occur every 10-20 second or so and start auto scrolling around 20 lines of chat history repeatedly.

When this occurs it also has a negative minor effect on FPS.

**Comment by SlayksWood** [comment]
#17524

**Comment by gzatravkin** [comment]
Can't reproduce (#17524 neither)

If still occur please attach a video 

![image](https://user-images.githubusercontent.com/53317567/90347030-0a913180-e004-11ea-8de8-61b752e5a35c.png)
