### ISSUE TITLE
endless unclaim deeds

### ISSUE THREAD

**Issue by Godzkonga7016** [StrangeLoopGames/EcoIssues#1763]
version 5.6  i was at my base, doing unclaim deeds, i was on the inside of my base next to a wall that was also the border of the claim,  i was doing the unclaim action, i noticed i was getting more then the one deed back, i ended up with 50 flag claims, i looked at the world map and my deed colors were purple the spot i was on when this happened the claim was white, this was on pam's US killserver, she says if you need saves she could get them

**Comment by SeanAtr0n** [comment]
fixed in 5.6.1
