### ISSUE TITLE
[0.9.0.0 beta staging-1706] Losing data after restart for objects (contracts, civics, etc...)

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17638]
Contract boards UI bug out and stops listing items, not sure on conditions - noticed it this morning by another user from the playtest.

1. Posted a large bulk of Loan offers in varying amounts. 250-1000, 100-500, 3000-5000 etc.
2. On login today we see that only a small portion of the avaible contracts are actually on the board. ( 5 / 20+
![Screenshot_417](https://user-images.githubusercontent.com/24981362/89782507-b377f200-db15-11ea-8170-2bb361e0643c.jpg)
 contracts )
![Screenshot_416](https://user-images.githubusercontent.com/24981362/89782498-ad821100-db15-11ea-95a7-8731481904ed.jpg)

**Comment by beastyn** [comment]
@John I assume its all connected to the last feature for the orphanage objects.
And maybe connected to this too #16601.
Case 1:
1) Create new contracts (18) on the board
![bandicam 2020-08-11 12-09-00-324](https://user-images.githubusercontent.com/27898520/89871627-26926e80-dbd1-11ea-9ec7-3d80b2c9a595.jpg)

2) Restart server
![bandicam 2020-08-11 12-28-43-398](https://user-images.githubusercontent.com/27898520/89871641-2b572280-dbd1-11ea-9b4c-1e37fecbf17f.jpg)

3) It will tell you that they are orphans
4) They will return to the board

I assume here we can have an issue where they won't placed back properly.

Case 2:
1) Create new contracts (18)
2) Place a second empty board
![board1](https://user-images.githubusercontent.com/27898520/89871883-94d73100-dbd1-11ea-8763-6910cf93db1d.png)
3) Pick up a board with contracts (DO NOT REMOVE DATA)
![board2](https://user-images.githubusercontent.com/27898520/89871955-aae4f180-dbd1-11ea-9663-823c897de629.png)
![board3](https://user-images.githubusercontent.com/27898520/89871989-b46e5980-dbd1-11ea-818f-6615404923d6.png)

.4) Restart server
![board4](https://user-images.githubusercontent.com/27898520/89871992-b89a7700-dbd1-11ea-9953-ee4fb247a9f1.png)

You will lose contracts
![board5](https://user-images.githubusercontent.com/27898520/89872001-bb956780-dbd1-11ea-8550-dee8017c0247.png)
SAVE: https://drive.google.com/file/d/177sVWSg7tkQZwIvjnEm918UcJ-Z2vPBU/view?usp=sharing

PROBLEM:
1 -  Do we need it with contracts? It was working fine after this #13279
2 - It can cause a lot of issues in Civics. So we potentially can lost objects there

It actually did with laws:
1) Create three laws: accepted, in election and draft
![law1](https://user-images.githubusercontent.com/27898520/89872801-e9c77700-dbd2-11ea-98a8-8ca96401c8af.png)
2) Pickup the court (DO NOT DELETE DATA)
![law2](https://user-images.githubusercontent.com/27898520/89872926-18dde880-dbd3-11ea-9a0c-b6e9f6d71620.png)
3) Restart server
![law3](https://user-images.githubusercontent.com/27898520/89873011-3b700180-dbd3-11ea-9f22-c225cbf8af79.png)
You will lose the laws.
![law4](https://user-images.githubusercontent.com/27898520/89873079-53478580-dbd3-11ea-9fd5-2daff67ab8ca.png)

SAVE: https://drive.google.com/file/d/1hIa5FxHQ8kGh8dV9fcRgiTzaJIZvK6V-/view?usp=sharing

This is a huge problem as it can affect ALL the objects with stored data even without picking them up (its just for easy repro case). 
Its really dangerous feature for now. We should not have orphans at all with proper data storing and even if we have such mechanic it should work in some rare cases (which should be fixed after)

**Comment by beastyn** [comment]
@johnkslg 
I've checked logs from WT from that day, and it seems some of contracts were returned to the board and some not.

 
[16:09:27.789] [23] [Error] [Eco] Government loan 2 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Government Loan 3 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Government Loan 4 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan 2 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan 3 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan - Long Term 3 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Government loan 5 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Government loan 6 has no host, removing.
 
[16:09:27.789] [23] [Error] [Eco] Contract 35 hosted by Contract Board, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Government Loan 7 hosted by Contract Board, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan 4 hosted by Federal Bank Loan Offers, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan - Long Term 4 hosted by Federal Bank Loan Offers, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Bank Loan 5 hosted by Federal Bank Loan Offers, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Government loan 8 hosted by Contract Board, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Government Loan 9 hosted by Contract Board, but host didn't list it.  Added to host.
 
[16:09:27.789] [23] [Error] [Eco] Government loan 10 hosted by Contract Board, but host didn't list it.  Added to host.

**Comment by johnkslg** [comment]
This was happening because the container object was not being marked dirty and not saving. I made it manually mark dirty for now, but I want to build a system to ensure this is automatic in the future (created issue for this: https://github.com/StrangeLoopGames/EcoIssues/issues/17690)

I removed the code that destroys host-less objects (because its permitted to have host-less objects when picking up a court, for example) but wasn't able to fully test due to being blocked by https://github.com/StrangeLoopGames/EcoIssues/issues/17689)

**Comment by beastyn** [comment]
It's still deleting data on the picked up objects with a kind of different message
![bandicam 2020-08-14 11-15-45-033](https://user-images.githubusercontent.com/27898520/90219816-4d92af80-de20-11ea-8252-6d42dc6d6257.jpg)
![bandicam 2020-08-14 11-21-26-982](https://user-images.githubusercontent.com/27898520/90219819-4ff50980-de20-11ea-845f-254fe62f48d3.jpg)

**Comment by johnkslg** [comment]
Finished fix now that the other blocking bug is gone.
