### ISSUE TITLE
9.0 Missing Sound for SteamEngine

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#17636]
We have only Sound when we open the UI of the SteamEngine but no Working Sound

**Comment by freakydna** [comment]
Fixed. https://drive.google.com/file/d/1UzYAjuM4qllg_9GSqEgacwSSP0L9yd53/view?usp=sharing (playable in latest VLC)
@Sekor2600 is it ok to close this out?

**Comment by freakydna** [comment]
@SlayksWood closing. Fixed in svn develop #8880:  https://drive.google.com/file/d/1UzYAjuM4qllg_9GSqEgacwSSP0L9yd53/view?usp=sharing
