### ISSUE TITLE
Make linked system better

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17631]
Inspired by this changes https://github.com/StrangeLoopGames/Eco/pull/6541 
We have another items with this problem Crafting stations with fuel, some lights(braziers) and I think we will have a lot of another objects in future. So, currentrly we have 2 option for inventories in our techtree: None and Linked. I assume we can add another one - 'Excluded' that allow to see another **linked** inventories in its storage, but it will not shown in another storages. That you did for Pots, but add this customization to all items in techtree.

**Comment by IcedForge** [comment]
I would like to comment regarding links in general, is there any change to see a default toggle : do not link ?

**Comment by WeaselDog** [comment]
We have decided to address the issue with the fuel storage by editing how the fuel component directly.
