### ISSUE TITLE
Investigate Hashicorp Vault for storing shared secrets

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17632]
Would be a useful replacement for user-secrets in unit testing

https://www.vaultproject.io/

Nuget package available for .net core: https://github.com/rajanadar/VaultSharp

Docker image: https://hub.docker.com/_/vault

**Comment by Abhiw205** [comment]
Vault is configured using Docker-compose and listing on local host. 
working on further enhancement along with auth docker image.

**Comment by Abhiw205** [comment]
HI, 
Deployed as Docker container, using docker-compose and consule as a backend. 
Vault can be reachable at  **http://vault.do-slg.com:8200/ui/vault/secrets**. 
use token as auth method. root token:-  "s.evudBneWX19Zn8vlxacrUGDL"

Alternate 
You can also test vault at api endpoint "http://vault.do-slg.com:8200", with default token 

Example:- 
curl \
    -H "X-Vault-Token: s.evudBneWX19Zn8vlxacrUGDL" \
    -H "Content-Type: application/json" \
    -X POST \
    -d '{ "data": { "Hello": "world" } }' \
    http://vault.do-slg.com:8200/v1/kv/data/hello


curl \
    -H "X-Vault-Token: s.evudBneWX19Zn8vlxacrUGDL" \
    -X GET \
    http://vault.do-slg.com:8200/v1/kv/data/hello

Please create a detailed ticket, with scope of users and integration plan with  cloud accounts.

**Comment by Abhiw205** [comment]
Please refer this user guide to use Vault secrete in C# code. 
Vault host url:- http://vault.do-slg.com:8200
Root Token: s.evudBneWX19Zn8vlxacrUGDL

https://learn.hashicorp.com/tutorials/vault/dotnet-httpclient?in=vault/app-integration
