### ISSUE TITLE
USER ISSUE: Stockpile Stack Issue?!

### ISSUE THREAD

**Issue by Blanus-1** [StrangeLoopGames/EcoIssues#17649]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Craft Stone Road and let it place in a Stockpile it creates a Stack of 5
2. Take it out in you hand or a cart for example and then you can stack it of 10

**Expected behavior:**
It should Stack in Stockpile the same as in Hand or Cart

**Actual behavior:**
It stacks not the same in Stockpile

**Do you have mods installed? Does issue happen when no mods are installed?:**
It stacks not the same in Stockpile

It's not only the Stone Road its many other Items as well, like Dirt, Stone Ramps, Tailings and so on

**Comment by SlayksWood** [comment]
No, this is intented behavior.
The increase to stack of 10 in hands or Vehicles is made for convenience. Stockpile, in turn, has the balance of the blocks, as if you put it on the ground. 
So, Stockpile has size 5x5x5 = 125 Blocks. And you can place only 125 Dirt in it.
