### ISSUE TITLE
Internal Server Error, Trace ID: |54fd1681-4a3b2fc901bd4f8a

### ISSUE THREAD

**Issue by TheSpaceDad** [StrangeLoopGames/EcoIssues#17646]
Since updating to staging-1711 today I am getting an error pop up stating:

Internal Server Error, Trace ID: |54fd1681-4a3b2fc901bd4f8a

This happens if I log in through Steam or through my SLG account:

![unknown](https://user-images.githubusercontent.com/6314156/89830015-729ece00-db53-11ea-9ccc-a783538a322f.png)

![Capture](https://user-images.githubusercontent.com/6314156/89830033-7af70900-db53-11ea-886f-6757cc324dda.PNG)

**Comment by redwyre** [comment]
Fixed up the user already.

Problem is again a datetime of 0 in the gametoken table.
