### ISSUE TITLE
[stagingland website] Password world can't contain "csrf"

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17642]
Step to reproduce:
- go on cloud world
- try to set password to something containing `csrf``

Expected behaviour:
- the password update

Current behaviour:
- we get the forbidden error (because ajax detect 'csrf' in the data string and believe we passed a csrf parameter)

**Comment by denysaw** [comment]
@matheod Hey ) Sadly we are using old dinosaurish framework (ci3), so I'm pretty not sure we could fix this and leave global CSRF defense ON :)

**Comment by matheod** [comment]
I don't know this framework, but the part that handle adding csrf is  :

```
$(document).ajaxSend((e, xhr, opt) => {
				if (!opt.data) {
					xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
					opt.data = '';
				}

				if (typeof opt.data == 'string') {
					if (opt.data.indexOf('csrf') == -1) {
						opt.data += (opt.data ? '&' : '')+`csrf=XXXX`;
					}
				} else if (opt.data instanceof FormData) {
					if (!opt.data.has('csrf')) {
						opt.data.append('csrf', 'XXXX');
					}
				}
			});
```

This one is generated by CI3 ? You have no way to modify this ?

If not, you still have the possibility to add this to every page (after the generated code) :
```
$(document).ajaxSend((e, xhr, opt) => {
	if (typeof opt.data == 'string') {
		if (opt.data.indexOf('&csrf') == -1 && opt.data.indexOf('csrf') != 0) {
			opt.data += (opt.data ? '&' : '')+`csrf=` + window.csrf;
		}
	}
});
```
This will be strange but it should work.

**Comment by denysaw** [comment]
@matheod Nope :) It's front-end logic written by me.
This should be fixed on server, not on the client.
Your solution will break ALL forms, where opt.data is not a string, but FormData. 
Will try to override something on server. Client logic is good.

**Comment by denysaw** [comment]
Ah... )) I got it ) So you mean client doesn't add `csrf`, cuzz it thinks it's already added... Clear now =)
Yeah, then looking for `&csrf` (your way) should help, sure =)
I thought problem is much deeper, on  server =) Huh! Nice. Will fix then, sure =)

**Comment by matheod** [comment]
Yea that why I wasn't understanding why there was something to do on the server part :D 

Good :D
