### ISSUE TITLE
Update cw versions filter to include playtest version

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17647]
Include playtest versions in filter for available cloud worlds

**Comment by denysaw** [comment]
@j3fffff  @D3nnis3n  Sadly it's not our side (( We are retrieving versions from here:
https://egsapi.strangeloopgames.com/api/instance/server/versions (curl from staging to test).
So that's where playtest versions should be added. Next time we all know where to look to :)
Re-assigning on GameDevs.

**Comment by j3fffff** [comment]
i confirmed the playtest builds are in docker images.
have to investigate why the api is not picking it up

**Comment by gzatravkin** [comment]
@denysaw so there are correct builds? Is still something is needed from gamedevs?

**Comment by denysaw** [comment]
@j3fffff Thanx. I didn't know about that option. Thought it's ALL by default. Ok, will do ;)
@gzatravkin No no, seems nothing needed from GameDevs ;) Sorry for bothering! Thanx!
