### ISSUE TITLE
[0.9.0.0 beta staging-1711] White Tiger's lags, FPS drops

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17653]
Please:
1. Place here a link for the snapshot you've made with F6.
2. Tell us when your issue appears, if you have any idea.
3. Tell us what FPS do you have (average or with some conditions)(Esc - left bottom info).
4. Tell us what ping do you have on the server (Esc - left bottom info).
5, Tell us about your PC hardware, OS.

Any information you provide will be helpful for us.
Thank you!

**Comment by revtje** [comment]
**Computer Specs:**
**CPU:** i5-9600K
**GPU:** Gigabyte GeForce RTX 2070 SUPER 8GB AORUS
**RAM:** 32GB DDR4
**SSD:** Samsung 970 EVO NVMe
**OS:** Windows 10 Pro
- Issue appears when driving through White Tiger capital

- 75 FPS at the start of game. 40 FPS after a drive through of the capital. 20 FPS at certain places when driving to and from the capital

- 17 ms ping

- After a fresh restart I have good FPS and **high** GPU load (90-100%). When the FPS drops down to 20-40 I have **low** GPU load (40-50%).

**Snapshot file after a fresh restart at my place in the desert**
[EcoProfilingData-2020-08-13T16-25-15.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5069677/EcoProfilingData-2020-08-13T16-25-15.zip)

**Snapshot files while driving around the capital, walking around in a tree farm, driving back from the capital**
[EcoProfilingData-2020-08-13T16-28-48.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5069682/EcoProfilingData-2020-08-13T16-28-48.zip)
[EcoProfilingData-2020-08-13T16-29-10.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5069687/EcoProfilingData-2020-08-13T16-29-10.zip)
[EcoProfilingData-2020-08-13T16-29-47.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5069694/EcoProfilingData-2020-08-13T16-29-47.zip)

**Snapshot file when im back at my place in the desert again**
[EcoProfilingData-2020-08-13T16-30-46.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5069703/EcoProfilingData-2020-08-13T16-30-46.zip)

**Comment by SlayksWood** [comment]
https://drive.google.com/file/d/1-rhBh4MeABDLGabuOlCxD7vRPLIk21M1/view?usp=sharing

**Comment by beastyn** [comment]
Usin animal debugging.
Drop to 10-15 fps
https://drive.google.com/file/d/1DQaOc35_yCsDF-kqt0cZd8vbl4hSFc_7/view?usp=sharing

**Comment by mirasrael** [comment]
Optimization for 9.0 finished. Not all issues fixed, but we need now to concentrate more on bugs than on performance. Closing it for now. Will create new issue for 9.1+.
