### ISSUE TITLE
Staging game server auth failure

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17658]
When changing a cloud world's settings on the website:
Website sends a GET query to the game server at: `<GameServerUrl>/api/v1/plugins/<NameOfPlugin>`
Game server API returns error: `You are not logged in`

Same error for both staging and production sites.
Also tried editing cloud worlds configs while logged in-game via Steam and Launcher. (because some api commands cant be called unless logged into game)
And also same error from Postman, using either auth

Also, when users login to game server, they are seeing a #2 added to their username.
Seems game server is distinguishing between their username setup as admin, and username when logging in.

I'm guessing game server is calling production auth somewhere, and that is causing the confusion.

Note: Some playtest users are reporting the error `You are not a citizen on this server`
This is because their staging and production accounts have different user IDs.
In theory, staging game server shouldn't care what the production user id is.

Note: Possibly related, strange error: the matching version for client, not on steam, wont login to staging server. But 8.3.3 version will! It's possible config needs user logged in, not on steam, with matching version. but wasnt able to test this, because it wont login with this error:
![image](https://user-images.githubusercontent.com/7343272/89958067-d7a70200-dbed-11ea-9df8-61db26b4a09f.png)

**Comment by redwyre** [comment]
Internal server error is same as https://github.com/StrangeLoopGames/EcoIssues/issues/17646, that account should be fixed now.

**Comment by j3fffff** [comment]
turns out none of the play testers linked their steam account to their cloud world account
