### ISSUE TITLE
[0.9.0.0 beta staging-1711] cannot fill/access Stockpile/truck from above.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17655]
If you are using an excavator for example or just trying to access a stockpile/large stockpile/truck from above it is impossible to do so other then a few specific cases see below.

- Cannot access stockpile using a Excavator
![Screenshot_440](https://user-images.githubusercontent.com/24981362/89895513-3e232480-dbdc-11ea-9cfa-ec02c98e517d.jpg)

- Cannot access the truck flat bed to deposit materials IF it is empty.
![Screenshot_443](https://user-images.githubusercontent.com/24981362/89895546-4b401380-dbdc-11ea-90c2-685695020616.jpg)

- Need to drop in materials in the cabin detection area instead
![Screenshot_442](https://user-images.githubusercontent.com/24981362/89895575-585d0280-dbdc-11ea-90a9-df47f625603d.jpg)

- Once the truck has materials so its model looks full it can be accessed.
![Screenshot_441](https://user-images.githubusercontent.com/24981362/89895852-c275a780-dbdc-11ea-9974-147b8bfc67ba.jpg)

- Max range from a truck flatbed i can be to deposit material, which would cause the excavator to fly off and pickup the materials again.
![Screenshot_445](https://user-images.githubusercontent.com/24981362/89896282-7bd47d00-dbdd-11ea-902c-3d7c8f92555c.jpg)

- This is the max range from the stockpile i can access it with an excavator.
![Screenshot_444](https://user-images.githubusercontent.com/24981362/89896127-34e68780-dbdd-11ea-9d86-c2cc0bdd0d2a.jpg)

**Comment by SlayksWood** [comment]
maybe related with #12785

**Comment by mirasrael** [comment]
Fixed interaction:
![image](https://user-images.githubusercontent.com/475445/90259761-3ae59e00-de53-11ea-8bbd-a28c82a3bd3a.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/90259789-4638c980-de53-11ea-8259-90411c1dd0dc.png)
