### ISSUE TITLE
Shrink player marker

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17664]
![image](https://user-images.githubusercontent.com/3536496/89979500-c3322c00-dc24-11ea-84f6-8ff622d363fd.png)
Should be half the size I'd say

**Comment by johnkslg** [comment]
Get other players icons too probably 
Post SS of finished job

**Comment by ptitducanh** [comment]
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/2c0d4a24-5983-4956-8012-ab2e1a63700d)
New marker size.
@johnkslg
