### ISSUE TITLE
Chat category label is gigantic

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17668]
![image](https://user-images.githubusercontent.com/3536496/89980037-df829880-dc25-11ea-9097-f0c26948147a.png)
DEMOGRAPHICS!!!

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/89980071-f628ef80-dc25-11ea-8fa2-24be427b3229.png)

**Comment by johnkslg** [comment]
While youre in there, make the mousewheel scroll 3 times faster too.

**Comment by SlayksWood** [comment]
Don't have this 'DEMOGRAPHICS!!!' in build version. But maybe bug in Unity?
![image](https://user-images.githubusercontent.com/45708377/90000761-3bd2d000-dc99-11ea-9857-e7d429ef07d5.png)
