### ISSUE TITLE
Ambient sounds stop aburptly when crossing world wrap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17665]
crickets at night especially.

**Comment by SlayksWood** [comment]
I think it's related with changing environment. #9664
Zero point

**Comment by s3lbie** [comment]
Crossing between 720 to 0 in coordinates causes certain ambient noises to stop. A flicker occurs between the two points.

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/16980
