### ISSUE TITLE
'Meteor spotted' tutorial doesnt continue following meteor

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17666]
![image](https://user-images.githubusercontent.com/3536496/89979742-553a3480-dc25-11ea-98a6-c89c01507a8f.png)
regression bug

**Comment by johnkslg** [comment]
Can push

**Comment by tuha263** [comment]
I already fixed it in: https://github.com/StrangeLoopGames/EcoIssues/issues/17666
