### ISSUE TITLE
Footstep audio frequency should be dependent on movement

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17663]
If youre slowed because youre moving against a wall or through bushes, the footstep sounds should slow accordingly. And if youre walking directly into a wall they should stop altogether.

**Comment by SlayksWood** [comment]
It works fine in 3rd person view.

**Comment by Quadbro** [comment]
@SlayksWood  it workd in third person cause it is bound to animation... we have no avatar in first person, so it is very tricky to implement such feature

**Comment by IcedForge** [comment]
There is still a couple of first person issues left.
(would it be possible to link movement to speed? so if you are not moving at all it stops playing? The slowdown in grass/plants etc works fine ).

- When blocked by object movement should stop.
- When blocked by terrain movement should stop.
- When walking into terrain types it should not detect block type blocking, it should only play audio detected by terrain walked on.
    ( this happens only to non full blocks, not sure how possible it is to fix without major rework of any logic involved )
![Screenshot_80.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/94329e64-96a2-4fbb-ba16-62e1df4abfea)

**Comment by Quadbro** [comment]
Added couple of tweaks:

- When blocked by object movement should stop.
- When blocked by terrain movement should stop.
Slows accordingly to move speed (as in third person)

-When walking into terrain types it should not detect block type blocking, it should only play audio detected by terrain walked on.
Fixed block detection precision
