### ISSUE TITLE
Show in world heatmap only shows property

### ISSUE THREAD

**Issue by jellyfluff** [StrangeLoopGames/EcoIssues#17679]
With nothing but "show in world" ticked in world layers it always and only shows the properties as if you are holding the claim stake. Other "yield potential" or "populations" can be ticked, but what is visible in world doesn't change from the highlighted property.
![image](https://user-images.githubusercontent.com/69574955/89989429-90009480-dc46-11ea-84fb-50339a8b9a4b.png)

**Comment by SlayksWood** [comment]
It happen only when you don't have Civics map. So maybe related with #17489
