### ISSUE TITLE
Fix all mouse wheel scrolling

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17674]
![image](https://user-images.githubusercontent.com/3536496/89980434-b9a9c380-dc26-11ea-875d-d188d0735436.png)
This one and many others in the game scroll frustratingly slow, make them scroll like windows does, at a good pace.  
This should be applied across all of them, ideally with a prefab change though this will probably be too much to do for now

**Comment by mirasrael** [comment]
Suggest to only fix Work scrolling for now, because it may be a big task. And push further refactoring to post-9.0.
