### ISSUE TITLE
Server crashes on startup 5.6

### ISSUE THREAD

**Issue by Gyllen1337** [StrangeLoopGames/EcoIssues#1767]
Server crashes when i try to start it,

--BEGIN DUMP--
Dump Time
07/04/2017 09:56:12

Exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Eco.Server.PluginManager..ctor(String configDir)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--

**Comment by metachronism** [comment]
you need .net 4.6, or a more recent version of mono if running on linux/mac
