### ISSUE TITLE
[0.9.0.0 beta staging-1715] Civics obects are disabled with server start.

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17675]
Every time server is launching I see that civics objects are disabled.
![bandicam 2020-08-12 10-42-25-568](https://user-images.githubusercontent.com/27898520/89981405-42f3e100-dc8d-11ea-8a7d-d12f17c0f5b0.jpg)
Maybe room is broken?
That should not happen.

Though they will be fixed in a short while. But I had an Issue once when they were disabled finally when timer was finished.
(save https://drive.google.com/file/d/1Ek6QcNzcIihdgSJmLXDJIZzemIOrHrEG/view?usp=sharing)

@olegshegai can you please look into this one and check if it can be easy fixed or this one will need some dangerous fixes (then I will push it).

**Comment by olegshegai** [comment]
Not quite easy, my best effort so far is keep everything but the capitol (others feel bad about this too):
![image](https://user-images.githubusercontent.com/56091594/90339331-c3ea0a00-dff8-11ea-9b84-a556b14c5876.png)

**Comment by johnkslg** [comment]
It's probably a case of these things detecting invalid rooms before the game has completed initializing and setting the validity of the rooms. Can you make the initial scans they perform to determine validity happen after the housing system has been completely initialized? Can make an event for this.   Can use the NowOrOnInit pattern of global data (make it a shared util)

**Comment by johnkslg** [comment]
Can manage initialization order through the use of callback.

**Comment by olegshegai** [comment]
Seems to be okay now

**Comment by SlayksWood** [comment]
Can't reproduce it in staging-1867
