### ISSUE TITLE
Viewport in chat should expand when theres no scroll bar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17671]
![image](https://user-images.githubusercontent.com/3536496/89980253-5fa8fe00-dc26-11ea-8da6-00e0da8bab2e.png)

Viewports can natively do this

**Comment by madpingui** [comment]
It is already expanded tested in develop branch unity editor
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/2cc270cd-564c-42ec-8dd1-d2478772e99a)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3.2 Release-212.

![eeee](https://user-images.githubusercontent.com/77248866/115731640-e0c1b300-a3b9-11eb-9d88-79f0db07432c.gif)

Entries in the Notifications Window do expand when there's no scroll bar.
Closing.
