### ISSUE TITLE
[0.9.0 staging-1715] Can't hear anothers player vehicle sound

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17685]
https://drive.google.com/file/d/1qdQAryl51Wxx9gxjIMpdTQK2UGK62BbE/view?usp=sharing
But I hear sound when another player open vehicle UI. I think I shouldn't.

**Comment by Quadbro** [comment]
vehicle open sounds are the same as for crafting tables, and they are synced intentionaly. We can remove this for vehicles or change sounds to less loand and engine specific one in separate issue

**Comment by SlayksWood** [comment]
Still an issue, I hear another sound compared to my driving sound. I would prefer not to hear the sound of another player opening vehicle UI like any other UI.
https://drive.google.com/file/d/1i-qvW0O3IoPM6yrXQk2lJ5-jtO4ctBNp/view?usp=sharing
And seems after that changes I don't hear opening UI by myself for Powered Cart, Wood Cart and Small Wood Cart.

**Comment by Quadbro** [comment]
@SlayksWood Powered Cart, Wood Cart and Small Wood Cart have no created opening sounds, so the sounds are not played
