### ISSUE TITLE
Cloud Worlds api auth token for admin access

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17687]
in user config there is "APIAuthToken" which will create a "api-user" and "APIAdminAuthToken" which will create a "api-admin-user" user
if you create new tokens and add them when you create a hosted world you can use them for api calls

**Comment by denysaw** [comment]
@j3fffff Hehe ) Can you more detailed explain me what to do? :) Seems we aren't passing APIAuthToken config right now?

**Comment by redwyre** [comment]
When creating a new world, you can generate a random guid and set it as the APIAdminAuthToken in the initial config, and save it for later use. You can then use it when making API calls on the world without needing a real user's token.

**Comment by denysaw** [comment]
@redwyre Aha... So it's permanent and doesn't require refreshing, yep? So can store in DB row permanently, right?

**Comment by mirasrael** [comment]
Yes, but it is safer to regenerate it for every server restart.
