### ISSUE TITLE
[0.9.0 staging-1720] Missing Selection frame for subrecipes.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17696]
![image](https://user-images.githubusercontent.com/45708377/90114306-376eeb80-dd5b-11ea-9502-363425c1ea85.png)

**Comment by beastyn** [comment]
Still here, press any gear on a craft table.
![bandicam 2020-09-02 14-31-22-006](https://user-images.githubusercontent.com/27898520/91964826-15003a80-ed29-11ea-9c05-62a8432d748d.jpg)
