### ISSUE TITLE
Wood cart not displaying the weight capacity it used to.

### ISSUE THREAD

**Issue by NaateeD** [StrangeLoopGames/EcoIssues#17692]
Upon opening the wooden cart in previous versions before the 9.0 playtest the woodcarts and trucks, etc. had a internal weight capacity on the upper right hand corner of the GUI. Not sure if intended now or not.
![cartweight](https://user-images.githubusercontent.com/32089039/90088518-1ff91980-dced-11ea-91f6-7b358de8108d.png)

**Comment by SlayksWood** [comment]
dup #17332
