### ISSUE TITLE
USER ISSUE: Issues with carts inventory disappearing

### ISSUE THREAD

**Issue by Aperson93** [StrangeLoopGames/EcoIssues#17694]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Have a crafting table craft multiple items and have the cart at the top of the storage so it places the items there. Then pull the cart away from zone and fill it up with other items until it is full. Bring the full cart back into range of the crafting bench and it will delete some of the items.

**Expected behavior:**
Crafting bench should start putting items in the next stockpile or hold until the cart is unloaded and then put items into cart

**Actual behavior:**
Deletes items in the cart to put the crafted items there

**Do you have mods installed? Does issue happen when no mods are installed?:**
Deletes items in the cart to put the crafted items there

**Comment by SlayksWood** [comment]
@Aperson93 Thank you for report. Can you provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
And it would be great if you provided a video or at least screenshots of the process.

**Comment by Aperson93** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5072091/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5072092/Player.log)

**Comment by Aperson93** [comment]
@SlayksWood

**Comment by SlayksWood** [comment]
@Aperson93 I saw that you provide log files. But I was hoping for some video too

**Comment by Aperson93** [comment]
Sorry, I think I figured this out, it looks like a crafting bench was grabbing some items
