### ISSUE TITLE
USER ISSUE: Backlog items crafting instantly

### ISSUE THREAD

**Issue by Aperson93** [StrangeLoopGames/EcoIssues#17695]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Set up a crafting que that goes over the items that are actually available. This was completed on the wainwright table for Stone roads. When I ran out of stone, I left and went to get stone and brought it back. When I put the stone in the stockpile, the stone roads appeared instantly

**Expected behavior:**
Should only start crafting time when both items are available.

**Actual behavior:**
Precrafts before all required items are available

**Do you have mods installed? Does issue happen when no mods are installed?:**
Precrafts before all required items are available

**Comment by SlayksWood** [comment]
Thank you for the report. This will be fixed in 0.9.0
