### ISSUE TITLE
Lights in 5.6.1 cannot be turned on/off

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#1769]
In 5.6.1 (release, not staging) generators can no longer be turned on/off by right-clicking. There does not appear to be any other control mechanism for doing so.

In my world, I have 24 generators prepped and fueled for lasers and all turned off. I am now unable to turn them on.

**Comment by egburr** [comment]
Game.eco is available at https://drive.google.com/open?id=0By3yTnmDe0ulTGk3NGFkMV92aTA  if needed.

**Comment by egburr** [comment]
I just realized/discovered that I can't turn lights on/off with right-clicks either.

The only way to stop fuel from being used is to remove it from the generator. Very frustrating.

**Comment by MarjieAVolk** [comment]
You should be able to turn your generators on and off in their window - there is a check box in the lower right.

It does appear that lights can't currently be turned off.

**Comment by egburr** [comment]
oh wow. I completely missed that. I see it now.
Thanks!

**Comment by egburr** [comment]
Never mind this. Lights have that same checkbox thing.
