### ISSUE TITLE
USER ISSUE: Tree Chop Noise Not Played (Intermittent)

### ISSUE THREAD

**Issue by joeberardis** [StrangeLoopGames/EcoIssues#17703]
\
**Version:** 0.9.0.0 beta staging-1714

**Steps to Reproduce:**
Take Default Ax, Chop down tree, the sound effect for chopping will not be triggered even though you are making contact choping the tree.	

**Expected behavior:**
Tree Chopping sounds should play on each successfull hit.

**Actual behavior:**
No sound effect triggered

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@joeberardis 
Can you provide video with sound? and you audio settings?
Also provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by joeberardis** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5071480/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5071481/Player-prev.log)

**Comment by joeberardis** [comment]
https://mega.nz/file/rVUWzSzY#yjl5qM7lwNY839pwZPL9Ldil1y84VR1IJEViMpECQow

^ Video Demonstrating the Issue

**Comment by Hexnaught** [comment]
I have had the same issue (`0.9.0.0 beta staging-1722`) and noticed it happen more so when I have pressed TAB to take control of the mouse, then clicked back in to the game view to go chop a tree.

**Comment by beastyn** [comment]
Thank you again. We did some fixes on the way. That should be fixed too. Please write here if you meet this again ( in version post 1730)
