### ISSUE TITLE
[0.9.0 staging-1721] Otters' unknown deadly decease

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17706]
Otters are dying if they see you in the water.
(no fly mode)

Just DYING. 
In the fresh world. Without pollution right after the start,
@D3nnis3n not sure how it works on the playtest. Be AWARE,

![unknown (26)](https://user-images.githubusercontent.com/27898520/90136631-e9271000-dd8d-11ea-9be6-dc5099971909.png)

**Comment by SlayksWood** [comment]
@D3nnis3n Safe them!
https://drive.google.com/file/d/1n_0Nah4qzHqzP60t_NQigFyKxyGZzrtb/view?usp=sharing

**Comment by D3nnis3n** [comment]
We'll need to prepare an excorcism, seems the dark ritual by players has ultimately succeeded. Archangel will not allow this to go on!
