### ISSUE TITLE
USER ISSUE: Servers Not Updating to New Verision when Steam Client is Updating

### ISSUE THREAD

**Issue by Twerk17** [StrangeLoopGames/EcoIssues#17708]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
1. Steam Updates
2. Server has no place to change version, and no auto update from what I can see.

**Expected behavior:**
Server Updates automatically

**Actual behavior:**
The following error message popped up:
``Version Type for Client 1722"
"Version Type for Client 1714"
<size=150%>Connection Failed</size>

Incompatible version.
User version:   0.9.0.0 beta staging-1722
Server version: 0.9.0.0 beta staging-1714

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**


**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ChreV0** [comment]
![123](https://user-images.githubusercontent.com/69639838/90152334-5dfb4980-dd90-11ea-8000-3a643c4cfc7f.png)

**Comment by j3fffff** [comment]
version updating is in advanced options of server options. well make this more visible in future
