### ISSUE TITLE
[Bug][Shop][UI][v0.9 staging-1722]Price / Quantity / Durability columns miss-aligned after adding Fishing Pole

### ISSUE THREAD

**Issue by Hexnaught** [StrangeLoopGames/EcoIssues#17712]
### Version

`0.9.0.0 beta staging-1722`

### Cause / Description

Added a fishing pole to the shop after numerous other items were already listed for sale.
Everything that was for sale and in view appeared to be fine, but scrolling up, other items had their columns miss-aligned.

Coming in and out of the interface _did not_ fix the issue.
Moving items up/down in the order of items _did_ solve the issue.

I am unsure if this was the same view other people got, when viewing the shop front.

### Image

The image below shows the one remaining item that was left in the 'buggy' state after I had tried various things to solve it.

![shop-interface-1](https://user-images.githubusercontent.com/1098786/90201098-b0108f00-ddd1-11ea-8f5d-204c34006a64.png)

**Comment by beastyn** [comment]
@serpopov For the repro you need to make scroll first. So either add a lot of items or reduce the window's height.
And then add a tool (like fishing pole) and scroll on top.
