### ISSUE TITLE
Campfire don't do anything

### ISSUE THREAD

**Issue by Ishjarta** [StrangeLoopGames/EcoIssues#1771]
In the campfire there is an finished project, but I cant collect them. I cant cancel it, too. While starting a new project, I am kicked with the issue "Inactivity". Breaking with the hammer gives a notification "This table has an active project and can't be picked up"

**Comment by Amphysbaenas** [comment]
i think your server need a restart

**Comment by MarjieAVolk** [comment]
So when you try to start a new project, you are kicked for inactivity.  What happens when you try to collect or cancel the project?

Would it be possible to send me your server's Game.eco save file?

**Comment by MarjieAVolk** [comment]
I think these issues are resolved in the current staging build.  Reopen if you continue having this problem.
