### ISSUE TITLE
gravity failure after breaking stone

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoIssues#17714]
if you break multiple stone blocks, and dont start from the top of the pile. the stones will not fall
![gravity](https://user-images.githubusercontent.com/68322457/90218753-35904100-ddca-11ea-82b2-613210ee4ad0.png)

**Comment by SlayksWood** [comment]
merged to #15298

**Comment by Draveynz** [comment]
continuously break stone,  atleast 2 stones should work. and pull from the bottom stones. 
top stone will still float
