### ISSUE TITLE
[0.9.0 staging-1724] Animals: corpse teleporting

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17718]
If someone kills an animal for you a corpse will disappear.
Person who has killed an animal will see a corpse just fine.
https://i.gyazo.com/11b001261ec4b040da2b28e97f8270ee.gif

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5073235/Player.log)

**Comment by Spaceferret42** [comment]
Mine happened when shot by same player though

**Comment by kealas** [comment]
Ours aren't involving multiple players either.  One person hunting has animals disappear while shooting them and even more often on death.  Carcasses teleport to other locations even when no one else is around.  It's consistent enough you can see it within minutes of walking around with a bow.

**Comment by beastyn** [comment]
About usual teleporting we have this #18034

But corpse teleporting is still an issue with lower priority. They won't disappear entirely, but will make some strange movement before reappearing (crab will just teleport down on the ground)
https://drive.google.com/file/d/1zcEgl4zy1wV0Hvl_lNZaL4F_Mzo_JVSV/view?usp=sharing

**Comment by beastyn** [comment]
Also check #18312
