### ISSUE TITLE
[0.9.0.0 staging-1722] Profile: Server crashes when voting

### ISSUE THREAD

**Issue by matta22** [StrangeLoopGames/EcoIssues#17728]
We are currently running a playtest on a SLG hosted cloud world, voting does not work. We have tried three different browsers to access the webpage and all connection attempts fail. 

We have used:
Microsoft edge
Firefox
Chrome

Our server ID is: 9960bf2c9cd343128ecbe832ea8105c4
Our server name is: The blackhat

All users were logged into the game when attempting to vote, and none have special characters in their name. Steam and SLG client have been attempted. 

We can however get the admin to get us a link to the webpage, but it does not allow anyone to vote only see the elections that are taking place. 

The website we can access: 
http://staging-world25.eco.hw.sfo2.do-slg.com/?

**Comment by denysaw** [comment]
@matta22 Thanx. Can you please tell or make a snapshot of what it writes? What is the error message? Thanx

**Comment by matta22** [comment]
I am not getting any in game message or error when i attempt to open it, but here is the webpage that I recieve after ~30 seconds or so of waiting. Users have also reported server lag when someone is attempting to access this page. All users are receiving the same message as below. If there is anything I can grab in the game files please let me know how to do so and i will get it back to you ASAP @denysaw 
![image](https://user-images.githubusercontent.com/40648993/90413045-52579d80-e084-11ea-8eac-26015aea124b.png)

**Comment by denysaw** [comment]
@matta22 Thanx.  @redwyre seems server totally doesn't load. Confirm, to unassign myself. Thanx

**Comment by redwyre** [comment]
So, the web page works correctly normally, but when attempting to vote it times out?

**Comment by redwyre** [comment]
I'll pass this to you @tuha263 to look at as part of profiling

**Comment by j3fffff** [comment]
tested and created optimization tasks
