### ISSUE TITLE
[0.9.0.0 beta staging-1722] Using /bm or /bt stops you from building higher.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17723]
Using /bm & /bt command to spawn in a structure of Ashlar or Composite material ( any type ) prevents you from building higher on that tile, it is NOT affecting the claim 5x5 area only the specific tile per tile.

Composite Lumber
![Screenshot_453](https://user-images.githubusercontent.com/24981362/90261931-ebe93a00-de4d-11ea-89b1-db13150fc623.jpg)
Ashlar Granite
![Screenshot_454](https://user-images.githubusercontent.com/24981362/90262013-058a8180-de4e-11ea-87a5-ae416fa67390.jpg)

While using any other material works perfectly fine.

Flat steel
![Screenshot_455](https://user-images.githubusercontent.com/24981362/90262069-189d5180-de4e-11ea-8976-6a8702e5ae0f.jpg)

1. Create world
2. spawn building using /bm & /bt for tier 4 ashlar / composite material
3. Try to place anything ontop, construction material, work bench, stockpile etc.

**Comment by IcedForge** [comment]
Running /level command will "reset" the tiles so they can be used again.

**Comment by IcedForge** [comment]
After some more testing, it seems that it is only the direct tile above that is an issue, tried removing all of it manually and it still refuses to let me build that 1 tile spacing above.
![Screenshot_457](https://user-images.githubusercontent.com/24981362/90263206-9f066300-de4f-11ea-9ac4-10818931ca9d.jpg)

**Comment by SlayksWood** [comment]
@IcedForge Don't try. You have invisible Roof Block here. This command use top Roof block, but new materials (COmposite Lumbers and Ashlar Stones) don't have it.

**Comment by IcedForge** [comment]
That would explain it, it was used to spawn prefab buildings for government law capitol house and federal bank on white tiger.

**Comment by SlayksWood** [comment]
we discussed this here #14627
