### ISSUE TITLE
Severe Lag Acccessing Multiple Storage from ANY table or another Storage Item

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1772]
I have 2 shop's on the Surface (One Selling Dirt, the Other Stone and Coal), they can both access 16 Stockpiles 7 blocks below, and also another 16 at 6 blocks below that, the Lag wasn't so bad before 5.6 and now getting worse in 5.6.1, can take up to 12 Seconds just to open the window, i Used to be able to sort the stockpiles into an order (i have renamed them Shop Sub Level 1 (dirt 1-16) and Shop Sub Level 2 (Dirt 1-16). For the other Shop they are named Shop Sub Level 1 (Stone 1-16) and Shop Sub Level 2 (Stone 1-16), if i try and sort them into any type of order i can get Disconnected with the Message "Inactivity", Even removing the tick in the storage and minimising the contents they still lag, this is also effecting the speed on the opening of a window for the crafting tables to craft an item.

**Comment by Conchipedia** [comment]
also getting the Error "Inactivity" when trying to view contents of ANY storage that has quite a lot of other storage close by.

**Comment by Conchipedia** [comment]
I love the way that tables can see close by Storage, but wouldn't it be better to have a maximum number of them that can be accessed/Turned On (example 10), as my shop is looking at 60+ at the moment, and having ALL storage unticked and letting the player turn ON which storage is being  accessed would be an easier way to decide which Storage is used, as getting the "Inactivity" kick when trying to sort them is getting a bit annoying at the moment.

**Comment by Conchipedia** [comment]
I get "Inactivity" kick as well, normally when opening a table/shop/storage that has auto connected to loads of other storage, wish they would put in  an option that NO storage is auto connected when a NEW table or Storage is added and you open it for the first time and then give you the Option to add which storage you want connected to this , a simple notification like they do with tables (not meeting required options) saying somehting like (Please Note no storage has been chosen for this item and crafting can not be started until one is added, please open tab and choose which ones you want to use)(edited)
same as putting an option in Power tab, which power source do you wish to use and what storage container is it in, Then it can keep the power slots full when they get empty automatically using the desired item. as i dig a lot of Coal up and store in underground stockpiles its easier for me to keep the stockpiles full (or at least have stuff in) rather than running about and placing 20 coal into the two slots in each item that requires it.

**Comment by metachronism** [comment]
this is largely fixed with inventory overhaul in alpha 6
