### ISSUE TITLE
USER ISSUE: Auth Servers?

### ISSUE THREAD

**Issue by Twerk17** [StrangeLoopGames/EcoIssues#17726]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
1. Attempt a log in

**Expected behavior:**
Logging into the Server Properly

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by WeaselDog** [comment]
Hi @Twerk17. Sorry to hear this is happening. Thank you for letting us know.

A couple a questions so we can help find the source of this issue.
- Are you trying to play in single player or multiplayer?
- Are you able to connect to our official 9.0 playtest server?
- Have you been able to connect using this version in the past?

**Comment by Twerk17** [comment]
It happens as the server is on longer is slowly degrades where we likely would need to restart every 6 or so hours to avoid any issues.

**Comment by WeaselDog** [comment]
So to clarify, is this a server you are hosting? Does this error message only appear sometimes, or are you always unable to connect?

**Comment by beastyn** [comment]
I will close it due no response.
Still we are waiting for feedback if issue is still actual.
If you have degradation situation, please make snapshot with F6 and place file here. 
Also we will be grateful if you attach a server (if you are hosting it) log and a client log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world
Thank you.
