### ISSUE TITLE
[0.9.0 staging-1725] Glitch dragging items beetween linked inventories

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17721]
Step to reproduce:
- place several stockpiles (at least 4) 
- open one stockpile and add 10 Crushed Iron ore(for example):
![image](https://user-images.githubusercontent.com/45708377/90242651-14653a00-de36-11ea-95b0-ecd6da9e4bcb.png)
- drag 10 Crushed Iron ore to second stockpile(first stockpile should be empty):
![image](https://user-images.githubusercontent.com/45708377/90242712-2f37ae80-de36-11ea-8271-f47034faa3e7.png)
- start to drag 10 Crushed Iron ore, but don't move it in cell, just move on a free space (in green zones):
![image](https://user-images.githubusercontent.com/45708377/90242856-74f47700-de36-11ea-9880-c283a2ce4580.png)
- 10 Crushed Iron ore will move to first linked stockpile, but should be moved in Tiny stockpile:
![2020 08 14 Glitch dragging items beetween linked inventories](https://user-images.githubusercontent.com/45708377/90243179-154a9b80-de37-11ea-8a43-1f321b3951ae.gif)

**Comment by Engimage** [comment]
You can also reproduce this by accessing any table's linked storage. Trying to drop items between cells with Shift pressed will drop them into the first storage in the list.

**Comment by SlayksWood** [comment]
@WeaselDog 
This is very annoying issue, Especially if you have a lot of inventory. And this is regression. Can we fix it a little faster? I will add at least 9.x to it.

**Comment by serpopov** [comment]
https://github.com/StrangeLoopGames/Eco/pull/7094

**Comment by SlayksWood** [comment]
Still an issue.
