### ISSUE TITLE
[0.9.0 staging-1725] Wrong hint for taking items from stockpile with empty cell on toolbar

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17722]
Step to reproduce:
- place stockpile and add some items in it:
![image](https://user-images.githubusercontent.com/45708377/90245625-b3406500-de3b-11ea-95c8-2ac06021a335.png)
- so, when I want to take All items (CTRL) It should say that I can take Dirt(like first item in hands), chest and tomato
- select any tool on toolbar and press CTRL, I have right hint:
![image](https://user-images.githubusercontent.com/45708377/90245780-ff8ba500-de3b-11ea-836c-ac8c774729d4.png)
- change cell to empty(or celect any item) and press CTRL, I have wrong hint:
![image](https://user-images.githubusercontent.com/45708377/90245894-306bda00-de3c-11ea-997c-83f6fefc79f4.png)
it said that I can take all items.

**Comment by TwixterZ** [comment]
still ongoing as of 0.9.3.0 staging 1945

**Comment by TwixterZ** [comment]
This issue no longer prevalent as of latest develop build
