### ISSUE TITLE
[0.9.0 staging-1722] Incorrect progress display of Work Orders

### ISSUE THREAD

**Issue by NuNky38** [StrangeLoopGames/EcoIssues#17724]
When using a translation (currently Russian) with a long text, the progress bar and buttons are displayed incorrectly
![1 1jpg](https://user-images.githubusercontent.com/69684724/90264350-8ca61c80-de83-11ea-8cc3-3e28aa9f6145.jpg)

Here's how it looks in the original
![1 2](https://user-images.githubusercontent.com/69684724/90264434-af383580-de83-11ea-8a85-d38cbe92b19a.jpg)

**Comment by SlayksWood** [comment]
We are planning to redo this interface, but for 9.0 we need to fix it.
Maybe you should transfer the text to the 2nd line if the name is long? or just decrease? leaving some distance (give it a minimum size limit) to display these bars

**Comment by NuNky38** [comment]
Here's it how looks in 2 lines. I put a transfer sign in translation, but now also in other places the name in 2 lines (in example in Console) and looks not well. 
![1 3](https://user-images.githubusercontent.com/69684724/90401947-49d98400-e0d1-11ea-8f4c-077ad48f9ef9.jpg)

Can you do a fixed size a field with auto transfer to the second line long strings? Or we do it like this?

**Comment by SlayksWood** [comment]
STill have some flaws:
![image](https://user-images.githubusercontent.com/45708377/92469499-91899200-f1dd-11ea-9e8c-59dca0816756.png)
but we can fix it later with https://github.com/StrangeLoopGames/EcoIssues/issues/13334
