### ISSUE TITLE
door wont open with shovel

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoIssues#17738]
only seems to happen when shovel is currently equipped.
switching toi anything else and it works again. seems intermittent to me atm, will test further
doesnt matter on material of door and/or shovel material

![locked](https://user-images.githubusercontent.com/68322457/90324909-71e2af00-df3a-11ea-8f75-073495225f74.png)

first noticed on 16XX
currently 1722

**Comment by Draveynz** [comment]
only seems to happen with door already closed. 
not sure what "locks" the door when u have shovel, haven't been able to narrow it down
switching shovel out of hand fixes it temporarily

**Comment by SlayksWood** [comment]
dup #3868
