### ISSUE TITLE
Animals: cave spawns?

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoIssues#17739]
currently on 1722
first noticed on 16xx playtest

animals spawning or falling thru ground into cave system?
ive seen couple jaguars, and now bison
upon killing them they most likely spawn corpse above ground, instead of below

![cavebison](https://user-images.githubusercontent.com/68322457/90326048-17048400-df49-11ea-8b9e-347c9323f1bf.png)

**Comment by beastyn** [comment]
Yeah, its teleportation issue like this #17718, thank you,

**Comment by beastyn** [comment]
Will leave it foe live animals teleportation,

**Comment by beastyn** [comment]
check after #18034
