### ISSUE TITLE
USER ISSUE: Markers for Campside and Tiny Stockpile not updated when moved

### ISSUE THREAD

**Issue by joeberardis** [StrangeLoopGames/EcoIssues#17737]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
Place Campsite and Tiny Stockpile from original loadout, then move the stockpile and campsite. 	

**Expected behavior:**
Markers should have moved to new location.	

**Actual behavior:**
Markers did not move to new location and still point to old location.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by joeberardis** [comment]
![Eco 2020-08-15 9_59_05 PM](https://user-images.githubusercontent.com/6415889/90324915-d7d33480-df42-11ea-8f55-076d5587c7a0.png)

**Comment by WeaselDog** [comment]
Hi @joeberardis. Thank you for reporting this concern.

This is the intended behavior. Only placing a "Starter Camp" will place a marker; this is the campsite at the start of the game that can claim territory, has starter items, and places a tiny stockpile with it.

With the map open, you can remove the marker from the Campsite and place it anywhere. There is even a chat command, /marker [text], that will place a marker in your current location using the text you provide.

We have removed the marker for the Tiny Stockpile when placing a starter camp so this process is easier. I appreciate your report, but we will not be changing this behavior at this time.

**Comment by joeberardis** [comment]
Thank you @WeaselDog , I was unaware of this functionality, i am participating in this blind with no eco experience before so i may accidentally submit these while i am learning the game, sorry to have taken your valuable time on this report.
