### ISSUE TITLE
USER ISSUE: Tutorial said i completed house but house is not completed

### ISSUE THREAD

**Issue by joeberardis** [StrangeLoopGames/EcoIssues#17735]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
Build floor of hewn log, build walls of hewn log, build roof of cobbled stone, roof is not completed. Hole in top of room still. There is one room block on each wall. Wondering if this is what prompted the tutorial to move on to the next step before i actually completed the house

**Expected behavior:**
Tutorial should have moved on from build a home after i completed the roof	

**Actual behavior:**
Tutorial moved on before i comopleted the roof.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by joeberardis** [comment]
![Eco 2020-08-15 6_36_18 PM](https://user-images.githubusercontent.com/6415889/90322773-48b82380-df26-11ea-89f3-9554f8630f1c.png)

**Comment by beastyn** [comment]
Thank you for the report.
Was some else around you finishing a room at the same time?

**Comment by joeberardis** [comment]
I dont believe so, my claimed laind in game is not directly touching any other players and i would say that the closest player claim is about 200-300 blocks from my claim.

**Comment by WeaselDog** [comment]
Issue is actual: https://github.com/StrangeLoopGames/EcoIssues/issues/9225
> A player reported that he placed down 4 walls each 5 wide on dirt, removed a dirt beneath a wall and got the tutorial "making a room" done - while that definitely has not been a full room without a roof.

**Comment by SlayksWood** [comment]
I guess this is still an issue. for reason that you can just digging and make Room from cave :
![image](https://user-images.githubusercontent.com/45708377/107334650-07b15e00-6ac8-11eb-859a-83cc5682bbd6.png)
So I guess we just need to clarify our tutorial. So Add the clarification that you must build a room with a volume of at least 25 meters and a level of at least 0.2 on your property(room to use first craft stations: Masonry table and Carpentry table). It will prevent to include different random rooms like cave. And also prevent when someone will finish room nearby you.

**Comment by TwixterZ** [comment]
fix confirmed, tested on 9.4 develop build 243
