### ISSUE TITLE
USER ISSUE: Agave's texture needs fixing

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17745]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
посмотрел на агаву

**Expected behavior:**
ожидал красивые текстуры

**Actual behavior:**
Текстура сломана. У всех. На всех агавах. На любых настройках графики.

[скрин](https://media.discordapp.net/attachments/743588336802726060/744205810787287040/unknown.png?width=962&height=557)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@ferrumbasso Спасибо за помощь.
@keegan-o need to check Agavу texture. LOD maybe?

**Comment by mirasrael** [comment]
It is problem with LODing
