### ISSUE TITLE
USER ISSUE: Летающие крабы и не только.

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17742]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
Путешествие по миру	

**Expected behavior:**
Плавающие под водой животные	

**Actual behavior:**
Летают без крыльев над водой. [скрин](https://media.discordapp.net/attachments/743588336802726060/744226712794956025/unknown.png?width=962&height=541)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Спасибо за помощь. Летающие животные исправляются.
