### ISSUE TITLE
USER ISSUE: Проблема с таймером крафта

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17744]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
войти в интерфейс станка 

**Expected behavior:**
таймеры должны совпадать

**Actual behavior:**
время крафта в открытом станке как-то не хочет отоброжаться корректно. Иконка на нем показывает все правильно
[скрин](https://media.discordapp.net/attachments/743588336802726060/744208388812177539/unknown.png?width=962&height=305)
**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Спасибо за помощь. Исправлено в 1728
