### ISSUE TITLE
[0.9.0 staging-1728] Wooden Doors don't have Hint Open/Close

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17748]
All Lumbers Doors, All Composites Doors:
![image](https://user-images.githubusercontent.com/45708377/90365740-f6cee500-e06e-11ea-9908-dbbc5eaf5aeb.png)
should be:
![image](https://user-images.githubusercontent.com/45708377/90365869-33024580-e06f-11ea-83e7-d9a3a5cc2a78.png)

**Comment by Sekor2600** [comment]
fixed in svn
