### ISSUE TITLE
USER ISSUE: нет отображения веса в транспорте

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17743]
\
**Version:** 0.9.0.0 beta staging-1722

**Expected behavior:**
Там должны быть цифры загруженных ресов/максимальный допустимый вес

**Actual behavior:**
[скрин](https://media.discordapp.net/attachments/743588336802726060/744677834944938024/unknown.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Спасибо за помощь. Исправлено в 1728
