### ISSUE TITLE
USER ISSUE: Животные против законов физики и стен

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17746]
\
**Version:** 0.9.0.0 beta staging-1722

**Steps to Reproduce:**
стоял

**Expected behavior:**
не проникать на частную собственность

**Actual behavior:**
Дикие животные игнорируют стены, потолки и любые физические преграды. В основном проходят сквозь потолок. При этом отображение не синхронизируются с другими игроками. Как пример  - этого Ягуара никто не видел. (пс - просрочку и грибы не ел, это не глюк!) [скрин](https://media.discordapp.net/attachments/743588336802726060/744284233446719578/unknown.png?width=962&height=433)
**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Спасибо за помощь. Натекущий момент животные в процессе исправлений, момент о прохождении через стены добавлю в общий список, исчезновение также известино.
