### ISSUE TITLE
USER ISSUE: Глюк с картой

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17756]
\
**Version:** 0.9.0.0 beta staging-1728

**Steps to Reproduce:**
Просмотр карты

**Expected behavior:**
Отображение карты

**Actual behavior:**
Было квадратное, стало треугольное в стиле каких-то комиксов. Переустановка клиента не помогла. Очистка найденых неудаляемых стимом хвостов тоже не помогло. Видимо что-то не удалили. Как это исправить?
[скрин карты](https://media.discordapp.net/attachments/743588336802726060/744905727750963240/unknown.png?width=962&height=541)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by mirasrael** [comment]
@ferrumbasso привет. Карта AMD и недавно обновил драйвера?

**Comment by ferrumbasso** [comment]
@mirasrael Да, rx 480, драйвера последние, говорят

**Comment by mirasrael** [comment]
Похоже AMD своим апдейтом сломали тесселяцию :(

**Comment by beastyn** [comment]
Быстрого решения нет, к сожалению. Будем думать.

**Comment by mirasrael** [comment]
Investigated issue and found that it was related to recent defaults introduced by AMD in ADM Radeon Software
![image](https://user-images.githubusercontent.com/475445/90526923-a4c6b600-e179-11ea-834a-8825f93b3624.png)

This value should be change to 64 to make map work again. It seems it chooses this default value based on GPU type (in example it may be lower for low-end or old GPUs).
Unfortunately there is no way in Unity to check for MaxTessellationLevel and show appropriate warning, but probably we can expose this info with our native plugin (RuntimeGraphicsInfo) then we can try to get this info from DirectX using this API: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb323634(v%3Dvs.85)
