### ISSUE TITLE
Make BSONObject use a dictionary

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17762]
For some reason this foundational class searches through keys everytime instead of using a simple dictionary. It likely has a significant effect on performance. 

![image](https://user-images.githubusercontent.com/3536496/90457790-649c0080-e0b1-11ea-86f0-417b2ee4f4f4.png)
![image](https://user-images.githubusercontent.com/3536496/90457833-82696580-e0b1-11ea-8b27-d29e7bb5a082.png)

**Comment by mirasrael** [comment]
It was initially done as Dictionary and has more impact on performance implement this way (especially because of more memory allocations). Eric refactored this to lists. For most cases it has less than 10 keys and won't have significant difference comparing to Dictionary (or even will be faster). So I don't really think it has significant impact on performance comparing to Dictionary, but to be sure we need to do proper benchmark and compare different implementations. Anyway this task doesn't seems critical for performance and we don't have this part appearing in profiler so may wait until next release at least.

**Comment by mirasrael** [comment]
Did some comparison testing:
```
0: list = 3ms dict = 4ms (75.00%)
1: list = 11ms dict = 11ms (100.00%)
2: list = 19ms dict = 17ms (111.76%)
3: list = 28ms dict = 23ms (121.74%)
4: list = 29ms dict = 29ms (100.00%)
5: list = 32ms dict = 26ms (123.08%)
6: list = 41ms dict = 31ms (132.26%)
7: list = 49ms dict = 35ms (140.00%)
8: list = 59ms dict = 38ms (155.26%)
9: list = 69ms dict = 43ms (160.47%)
10: list = 80ms dict = 47ms (170.21%)
11: list = 89ms dict = 52ms (171.15%)
12: list = 99ms dict = 57ms (173.68%)
13: list = 110ms dict = 61ms (180.33%)
14: list = 120ms dict = 65ms (184.62%)
15: list = 132ms dict = 71ms (185.92%)
16: list = 146ms dict = 75ms (194.67%)
17: list = 159ms dict = 79ms (201.27%)
18: list = 177ms dict = 87ms (203.45%)
19: list = 189ms dict = 90ms (210.00%)
20: list = 208ms dict = 95ms (218.95%)
21: list = 226ms dict = 100ms (226.00%)
22: list = 243ms dict = 103ms (235.92%)
23: list = 262ms dict = 108ms (242.59%)
24: list = 281ms dict = 114ms (246.49%)
25: list = 304ms dict = 118ms (257.63%)
26: list = 324ms dict = 122ms (265.57%)
27: list = 344ms dict = 127ms (270.87%)
28: list = 369ms dict = 131ms (281.68%)
29: list = 389ms dict = 137ms (283.94%)
30: list = 412ms dict = 147ms (280.27%)
31: list = 433ms dict = 147ms (294.56%)
32: list = 461ms dict = 156ms (295.51%)
33: list = 487ms dict = 155ms (314.19%)
34: list = 510ms dict = 163ms (312.88%)
35: list = 541ms dict = 161ms (336.02%)
36: list = 563ms dict = 170ms (331.18%)
37: list = 597ms dict = 177ms (337.29%)
38: list = 626ms dict = 181ms (345.86%)
39: list = 655ms dict = 183ms (357.92%)
```
Test code is:
```csharp
const int iterations = 100000;
var i = 5; // i -> 0:40
                var sumObj = 0;
                for (var it = 0; it < iterations; ++it)
                {
                    var bsonObj = BSONObject.New;
                    for (var j = 0; j < i; ++j)
                        bsonObj[keys[j]] = BSONValue.NewBSONValue(j);
                    for (var j = 0; j < i; ++j)
                        sumObj += bsonObj[keys[j]].Int32Value;
                    bsonObj.Recycle();
                }
```
From these test results it seems like for most cases using Dictionary is more effective for performance. It is roughly equal for small numbers (<=6) with like 10-20% benefit for Dictionary, but then it starts fast growing.
Seems like there no real benefit from using lists and we can switch back to Dictionary.
