### ISSUE TITLE
[5.6] Cement kiln, cannot use pipes to redirect pollutions

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#1776]
When using the cement kiln I connected pipes to it, but the smoke still comes out from the kiln.
![bild](https://user-images.githubusercontent.com/27635053/27905297-dc64d630-623f-11e7-83cd-5ebd4b49d5f7.png)

**Comment by Amphysbaenas** [comment]
Try that :)
![capture011](https://user-images.githubusercontent.com/29807119/27942952-7178cec0-62db-11e7-83ee-f3d03c46e380.PNG)

**Comment by MarjieAVolk** [comment]
I believe this is because the pipe has to be connected to a certain block on the cement kiln.  It is confusing right now - eventually we will have a pipe port visible on each object.
