### ISSUE TITLE
erro dev text  covering screen

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoIssues#17763]
Version:
   v9 1722 & v9 1728
Reproduction:
   Seems to happen whenever i try to move anything (tested every item i currently have "tier 1 - 2, food, seeds") in or out of my cave1 stockpile (test with other stockpiles aswell)
Expected Behavior:
   Move without errors
Actual Behavior:
   Posted errors each time i move, sometimes will not move
Log Files:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5087930/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5087931/Player-prev.log)

![sanderror](https://user-images.githubusercontent.com/68322457/90465791-c1a9ad80-e0d5-11ea-8831-0f4d9c660eb7.png)

**Comment by Draveynz** [comment]
Restarted game, no visible error

**Comment by beastyn** [comment]
It's a console from develop build. You can show it or hide with F7.
Errors are in the separate issue.

**Comment by Draveynz** [comment]
shows after few hours of gameplay. estimate after 5 - 6 hours itll start popping up and wont go away untill restart

**Comment by Draveynz** [comment]
closed but not fixed?

**Comment by beastyn** [comment]
It won't be fixed )
It's a log from a developer build. You can create a separate issue about error you have there (and you did it already with #17749) 
But log itself will always be with you in Developer build. You can hide it or show it with F7.

**Comment by Draveynz** [comment]
the error is the fact im not pushing F7 to open or close it

**Comment by beastyn** [comment]
It can blink for a second even when switched off, that's ok. But then maybe you want to open it and look for an error (or look into the log file)
