### ISSUE TITLE
Cannot connect to any 9.0 servers

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#17771]
I cannot connect to any 9.0 servers and only get the attached error message. Yesterday devs were working on fixing my config access to my 9.0 test server and my server is back up now, but something was done to my account to where I can't connect to any servers now. It may be because they linked my Steam and SLG accounts?

[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5090493/log.txt)
![error-screen](https://user-images.githubusercontent.com/69723929/90515624-8ab0b780-e128-11ea-9927-2154e65bf107.jpg)

**Comment by beastyn** [comment]
Have it again (1740)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5127742/Player.log)
![bandicam 2020-08-26 10-17-02-908](https://user-images.githubusercontent.com/27898520/91258684-61c29f00-e786-11ea-8357-d7c0cb152ec4.jpg)

**Comment by beastyn** [comment]
Created in a separate issue
