### ISSUE TITLE
[ 0.9.0.0 beta staging-1728] Ashlar Build block name mistake

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17779]
Currently a confusion in terms of the corner brace type name
![Screenshot_34](https://user-images.githubusercontent.com/24981362/90546369-43f3a980-e18a-11ea-9180-60bad506e16d.jpg)

I believe they are twisted around, the UnderBraceCorner is supposed to be BraceCorner and the other way around.
![Screenshot_36](https://user-images.githubusercontent.com/24981362/90546421-579f1000-e18a-11ea-9963-118f212726b1.jpg)
![Screenshot_35](https://user-images.githubusercontent.com/24981362/90546424-5837a680-e18a-11ea-9fe9-e7220f45246b.jpg)

**Comment by beastyn** [comment]
@keegan-o little comment here please )

**Comment by keegan-o** [comment]
This is right-- the names are switched by accident. Will fix, but after other last minute 9.0 stuff. (slight chance it gets pushed to 9.1)

**Comment by keegan-o** [comment]
fixed in develop
