### ISSUE TITLE
ECO 5.6.1 MAC OSX ISSUE

### ISSUE THREAD

**Issue by Issue3996** [StrangeLoopGames/EcoIssues#1777]
When I try to launch Eco on my Mac, it will crash pretty much every time it tries to enter the server. I have no idea how to fix this problem and I am using Eco to play at school so help would be greatly appreciated!

**Comment by SeanAtr0n** [comment]
Could you open a terminal and try:
ls ~/Library/Caches/unity.Strange\ Loop\ Games.ECO

Is there a 'mods' directory in there?

I saw a similar issue before due to that Mods dir from older builds, could you try deleting it (or the entire directory) and let us know if that helps you progress?

**Comment by Issue3996** [comment]
Thanks

**Comment by SeanAtr0n** [comment]
Seems to be resolved
