### ISSUE TITLE
(0.9.0.0 Staging-1728) Old chat messages popup in general chat 

### ISSUE THREAD

**Issue by MickDK87** [StrangeLoopGames/EcoIssues#17770]
![chat](https://user-images.githubusercontent.com/69853693/90515161-873a2200-e162-11ea-8bb5-0fd64546e375.png)
 

Know issue?

**Comment by SlayksWood** [comment]
@MickDK87 Thank you for the report. Can you describe this issue more detail? Maybe some steps to reproduce? and also provide log files when it happens.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MickDK87** [comment]
After posting this it has happened twice, it appears to happen when you scroll up in the chat history to see an old message, when scrolling back down to the most recent message random old messages will appear. This might be the cause or simply a coincidence, I'll try to reproduce the problem and get a log file. Sorry for the lack of information, new to using GitHub.

**Comment by MickDK87** [comment]
I have been trying to reproduce the issue with no luck, the scrolling must have been a coincidence. From what i gathered asking around it is not a very common problem. At a loss on what to do to get you more information. Considering no one else has added to this post you can close this issue and I'll start a new one with log files etc. if it happens again, up to you. -Mick

**Comment by beastyn** [comment]
@MickDK87 thank you for your attention to this issue. You can use this one for the log attachment, though I will close it. You just can tag me, then I won't miss it.
