### ISSUE TITLE
[ 0.9.0.0 beta staging-1728] Ashlar Block types missing

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17778]
![Screenshot_24](https://user-images.githubusercontent.com/24981362/90545675-473a6580-e189-11ea-9f80-b8bc40f4ef8e.jpg)
Missing an  "Inverted Under Brace Corner" as well as a "Inverted Brace Corner" as it is impossible to make a whole detailed bracer mounted wall with an inwards 90 degree corner as it currently stands.

![Screenshot_26](https://user-images.githubusercontent.com/24981362/90545682-4acdec80-e189-11ea-8e26-ce6f9f4f4c64.jpg)

Missing some form of closure of the Bracer wall type to fit into the wall itself, or make extensions of a Under / Top brace so you cant make bigger "pillar type structure" unless you make it look like some giant sat on it to compress it.
![Screenshot_25](https://user-images.githubusercontent.com/24981362/90546141-f0815b80-e189-11ea-8b4d-f60281c32eba.jpg)

**Comment by Praefator** [comment]
Seconded. Using this blockform in the meantime

![underbrace corner v3](https://user-images.githubusercontent.com/841990/90611387-f36e6180-e206-11ea-8bf9-481e294460ea.jpg)

**Comment by keegan-o** [comment]
Added Inner brace for upper and normal, the meeting of braces and walls can be improved with alternate forms coming in the future, will likely add something like 'ledge walls', as well as things that are like floor blocks with borders, but vertical. (Will close when I get the art I made hooked up)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/9d61d5f7-b3b7-4e5e-841a-7bf22d3baa31)
Will be in 9.1.
