### ISSUE TITLE
USER ISSUE: Рассинхронизация

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17776]
\
**Version:** 0.9.0.0 beta staging-1728

**Steps to Reproduce:**
Майнинг нескольких игроков. 

**Expected behavior:**
Синхонизированный камушек	

**Actual behavior:**
У одного игрока он был, у другого нет.
[скрин одного игрока](https://cdn.discordapp.com/attachments/743588336802726060/745273286916833357/unknown.png)
[скрин другого игрока](https://cdn.discordapp.com/attachments/743588336802726060/745273486817099846/unknown.png)

Так же была проблема с синхронизацией некоторых животных до обновы 1728

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Thank you for the report.
Animals should be fixed soon.
Rubbles issue need some investigation.
Eould be nice to have your log from the session (or from any with this kind of issue)

**Comment by mirasrael** [comment]
Probably fixed with latest physics changes.
