### ISSUE TITLE
USER ISSUE: Глюк с графическим отображением

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17773]
\
**Version:** 0.9.0.0 beta staging-1728

**Steps to Reproduce:**
Включить глобальное освещение	. Появляются глюки на стройматериалах и других объектах. Проверено несколькими клиентами

**Expected behavior:**
Отсутствие призрачных текстур

**Actual behavior:**
Наложение/дублирование текстурок, которых быть не должно.
[скрин1](https://cdn.discordapp.com/attachments/743588336802726060/745322665769697356/unknown.png)
[скрин2](https://media.discordapp.net/attachments/743588336802726060/744974081421607064/unknown.png?width=962&height=493)
[скрин3](https://cdn.discordapp.com/attachments/743588336802726060/744973522337529896/unknown.png)
[скрин4](https://cdn.discordapp.com/attachments/743588336802726060/744973163724800143/unknown.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #17583
