### ISSUE TITLE
USER ISSUE: Revised, Passed Laws Dissapear

### ISSUE THREAD

**Issue by Twerk17** [StrangeLoopGames/EcoIssues#17786]
\
**Version:** 0.9.0.0 beta staging-1728

**Steps to Reproduce:**
1. Pass a Law
2. Revise Law
3. Passed it with /fin
4. it poofs and is gone until server reset.

**Expected behavior:**
Stayed in one of the three slots to continue revising?

**Actual behavior:**
It dissapears after the revision is passed.

Video Proof:
https://youtu.be/BAllo5hkQQU

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Twerk17** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5093734/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5093737/Player-prev.log)

**Comment by beastyn** [comment]
Yeap, its an old bug, hard to catch. Laws always should stay on the court, in every stance.
Its not a feature. Thank you for the video and the log, pretty useful!
Maybe it will be fixed in 1730 build, will see after fresh playtest session.

Merging here #16601
