### ISSUE TITLE
[0.9.0 staging-1731] Not all items in Filter have tooltips

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17788]
- [ ] 1. Triggers in Amendments:
![image](https://user-images.githubusercontent.com/45708377/90600169-c28a2e80-e1fe-11ea-94b6-210fc36eebe9.png)

**Comment by johnkslg** [comment]
Do you mean they dont have icons, or tooltips @SlayksWood
