### ISSUE TITLE
[ 0.9.0.0 beta staging-1728] Crafting type selection ui issue

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17783]
When trying to use specific craft item type you need to check "Show All" and then uncheck it
when it should show the available craft types on initial window.

https://i.gyazo.com/49c11f4d407daa0387fa435eb1411f06.mp4

Recommendation, add a material available check on window opening.

**Comment by SlayksWood** [comment]
'Show All' button doesn't work. It always show all recipes to me.
I have table with linked stockpile with Composite Oak and Composite Joshua:
![image](https://user-images.githubusercontent.com/45708377/92324303-27d87f00-f049-11ea-8979-4ac38fc83d9f.png)
But it's shown all recipes.

**Comment by serpopov** [comment]
![image](https://user-images.githubusercontent.com/4238643/92393040-6b1a1700-f149-11ea-892d-a9416589f8a1.png)

Filter works when you have resources to at least one of them

**Comment by SlayksWood** [comment]
yea, you are right.
