### ISSUE TITLE
Construction issues, stairs placement

### ISSUE THREAD

**Issue by Egrof** [StrangeLoopGames/EcoIssues#1778]
![escaliers](https://user-images.githubusercontent.com/16516876/27935377-16415502-62ab-11e7-9871-424f8cb44a56.jpg)

WHY ???!!!
Those wood stairs only want to be placed this way. I can't press E or A to turn it. It's the same for roofs.

Generally construction can be a painful experience. We need an option for a little cross in the center of the screen to see where we are pointing.

**Comment by MarjieAVolk** [comment]
Duplicate of StrangeLoopGames/EcoIssues#438
