### ISSUE TITLE
read more button outside of div

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17782]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/70acdb7e-1234-4ef3-8319-951994a9fea1)
In Recent Updates section
Read more button is outside of div, only for this update.
All other updates has read more button inside div. should be inside.

**Comment by denysaw** [comment]
@j3fffff @D3nnis3n That only means, that content is corrupted. Some div in content isn't closed. That's how it breaks our HTML.

**Comment by j3fffff** [comment]
I'm betting related to this, is bug where title categories are not displayed correctly.

For example, World Simulation: UI should actually be World Simulation: Biomes

I checked in ACF backend, and Biomes backend name is also biomes.
I left this error on staging site for you to test with. (Please remove both of these UI posts when youre done testing, as they are supposed to be small status updates, not blog posts.)
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/7e912977-2664-4f62-8f0c-b79ded1f0d17)
