### ISSUE TITLE
USER ISSUE: Баг со звуками, которых не должно быть

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17784]
Version: 0.9.0.0 beta staging-1728

Синхронизированный звук открывающейся двери у всех игроков (при открывании или закрывании любой двери в любом уголке планеты), звук телеги на каменной дороге (когда телеги и близко нет), дублированный звук телеги (когда ею управляет другой игрок)

**Comment by SlayksWood** [comment]
dup #17622, #17685
