### ISSUE TITLE
[0.5.6.1] No texture on Steam Generator Object

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#1779]
As you can see in the picture below there is no texture on the Steam Generator Object:
![012](https://user-images.githubusercontent.com/29807119/27943071-8248ac6a-62dc-11e7-9e1e-f65e20d1ec21.PNG)

**Comment by keegan-o** [comment]
Will get to the object when we world object art is being worked on. Many world objects still need art or updates, so not really bugs, it's content.
