### ISSUE TITLE
[0.9.0.0 1728] Can't create electric planer

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#17791]
I have created an electric lathe, 
![unknown1](https://user-images.githubusercontent.com/13696708/90610808-a1313e80-e20e-11ea-9321-d48da71289bb.png)

but I do not allow creating an electric planer.
![unknown](https://user-images.githubusercontent.com/13696708/90610800-a0001180-e20e-11ea-9010-d75e6f9f43a8.png)

**Comment by SlayksWood** [comment]
Work fine for me:
![image](https://user-images.githubusercontent.com/45708377/90612943-61b82180-e211-11ea-9603-db427de15a0e.png)
![image](https://user-images.githubusercontent.com/45708377/90612981-70063d80-e211-11ea-8f39-3c2f10051d36.png)
@Astrija 
Do you have Electric Lathe in this room?

**Comment by Astrija** [comment]
yes, Electric Lathe in this room, i can send game.db for test this

**Comment by Astrija** [comment]
I first put the lathe in another room, and then I connected the room. After rearranging the machine, everything fell into place.

**Comment by WeaselDog** [comment]
Hey sorry for delay in getting back, but I can confirm this is fixed in the latest 9.6 release. Thank you for your report!
