### ISSUE TITLE
[0.9.0 staging-1731] Animals: tick fails

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17794]
![bandicam 2020-08-19 16-12-26-674](https://user-images.githubusercontent.com/27898520/90628675-7c9d8c80-e237-11ea-980c-9592fc4a31b0.jpg)

**Comment by coolfarmer** [comment]
This issue is fixed? I'm on 1740 and I have constantly Animal tickfail

**Comment by beastyn** [comment]
Not in the build yet

**Comment by SlayksWood** [comment]
I don't have any tickfail in 3 hours. Seems fixed or at least not so often.
