### ISSUE TITLE
USER ISSUE: cart stuck in small hole

### ISSUE THREAD

**Issue by bitofagit** [StrangeLoopGames/EcoIssues#17797]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
pull cart into a small hole in a forest

**Expected behavior:**
i put some logs down to act as a step, but still stuck. in real life log steps would work i  think

**Actual behavior:**
still stuck

**Do you have mods installed? Does issue happen when no mods are installed?:**
still stuck

**Comment by beastyn** [comment]
@bitofagit Thank you for the report.
This kind of situation can be handled with /unstuckvehicle command.
Also in 9.0 we were able to release a cart with logs.
