### ISSUE TITLE
CW: Disable maximum worlds options for tier 11(dev)+

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#17796]
Right now we have `world_maximum` option in DB and it set to 1 on staging.
Make Dev Tier (11) and up to have unlimited cloud worlds.

**Comment by beastyn** [comment]
Still allowing to get more than one world if you are inputing numbers manually (not using an arrow)
(worlds were not loaded, just infinite processing )

**Comment by denysaw** [comment]
Added 2 additional checks for max allowed worlds per account and added clear error notification. So if there were separate issue about notification, you could close it too ;)
