### ISSUE TITLE
Adding the new MortaredStoneDoor Variants

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#17801]

**Comment by IcedForge** [comment]
All types of the same object should be grouped and crafted dependent on the material types and not each separate entity in the crafting list.
![Screenshot_90.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/41ea3716-0cea-4304-aba8-55e50a67ed7e)

They should all be under the same Mortared Stone "object" and be selecting recipe via the new material selection system.
