### ISSUE TITLE
[0.9.0 staging-1728] Air pollution from cast iron stoves with pipes not working correctly

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#17804]
When using a cast iron stove with a chimney, the air pollution still shows up at the location of the cast iron stove, rather than where the outlet for the chimney pipe is. Cast iron stoves also seem to generate a lot more pollution than in the past, completely polluting nearby rivers and land with ground pollution. I'm not sure if this intended to be this way.

**Comment by SlayksWood** [comment]
Thank you for the report.
first part is dup #17316
The pollution from the cast iron stove has become even less, it just didn't work correctly in 0.8.3
