### ISSUE TITLE
Invisible objects

### ISSUE THREAD

**Issue by dezorro** [StrangeLoopGames/EcoIssues#17803]
when i leave area for example to go mining then return rocker box is invisible can not place anything where it is ment to be have worked out a relog fix's this but when i go mining again and come back its invisible again 
i made a second rocker box to test if i could place it where the invisible one is but cant place it lol
![image](https://user-images.githubusercontent.com/45708377/90723760-fda36500-e2c5-11ea-8575-48213af79ca4.png)

**Comment by SlayksWood** [comment]
@dezorro Thank you for the reprort. When you make issues, please make them with the following template:
1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files when this bug happened
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

In your case I want to know about your coordinates and coordinates already placed rocker box too,

**Comment by dezorro** [comment]
![rocker box 2](https://user-images.githubusercontent.com/69855980/90724373-cb175d80-e301-11ea-92d9-06cefba544e0.jpg)
this is the rocker box where it is ment to be but some times disapears as stated in report the cords that you mean are you talking about map cords as for log files the next time i see the thing missing i will attach log files

**Comment by beastyn** [comment]
@dezorro thank you for the attention to the issue. Also it would be helpful to know your PC specification.

**Comment by dezorro** [comment]
what spec would you like i run win 10 pro, i7 7700, rtx2070, 32gb ram @beastyn

**Comment by beastyn** [comment]
@dezorro That's it, thank you. will make further investigation.

**Comment by dezorro** [comment]
thank you @beastyn thought this was forgotten about lol

**Comment by beastyn** [comment]
@dezorro did you have any mods installed for this server?
And maybe you can attach save file (if you still have it) ?

**Comment by dezorro** [comment]
no mods on server

**Comment by dezorro** [comment]
and sorry save file ? not the player logs ?

**Comment by beastyn** [comment]
.eco file from Storage folder. If it was your server, of course.
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
.eco and .db  files

**Comment by dezorro** [comment]
sorry not my server but will ask the server admin if he can email me them

**Comment by beastyn** [comment]
@dezorro Thank you, that would be helpful.
These kind of things hard to reproduce as they can be connected to the poor ping (bad connection), for example.

**Comment by SlayksWood** [comment]
merged to #19797
