### ISSUE TITLE
[0.5.6.1] RPC Exception in Storage Chest

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#1781]
have 2 chests in the world linked to each other, open both of them in seperate UI instances and moving thing on 1 UI quickly from 1 chest to another and back.

[exception.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1131940/exception.txt)

**Comment by metachronism** [comment]
inventory overhaul did away with this error for alpha 6
