### ISSUE TITLE
Board Icon Update

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17817]
It would be nice if the original Board icon was updated to match the new hardwood/softwood boards.

![BoardIconUpdate](https://user-images.githubusercontent.com/47330823/90810210-78c14700-e2d7-11ea-8284-152e77a81329.png)

The original board sprite could be used for the board tag if that works.

**Comment by RobertMangano** [comment]
what is the original board supposed to be made of?

**Comment by keegan-o** [comment]
It's supposed to be a mixture of softwood and hardwood boards, what you get when you mix the wood types going in.
