### ISSUE TITLE
Unable to generate new world in Steam singleplayer

### ISSUE THREAD

**Issue by Panderling** [StrangeLoopGames/EcoIssues#17815]
When attempting to create/generate a new world to play solo in 9.0

I click on 'Host a new World'
Enter a world name
Choose settings and enter a map seed
Press start
Popup appears asking 'Generate Random new world?
Click yes
Nothing happens. 

Has been happening for the last three days (when I started trying). I have uninstalled my game and reinstalled, and I also attempted to create new world in both 9.0 and 8.3 and neither were successful.

**Comment by WeaselDog** [comment]
Thanks for reporting this.

I can replicate this on the latest staging build in Steam, but not on our internal build in Unity. We will look into this.

**Comment by WeaselDog** [comment]
Here is video with replication steps on Steam. Key things to note: https://drive.google.com/file/d/1DPv500q28foL7Av1TQXzsr3DOtEpFoBH/view?usp=sharing

- Trying to generate a randomly generated world does not load or create a save
- Using a non-random world creates a save but it does not load
- You are able to load the save of the non-random world save and play in singleplayer

**Comment by redwyre** [comment]
Looks like the difficulty settings added "DifficultyModifiers" and it's not getting set correctly from the UI (custom difficulty works)
@gzatravkin looks like you were working on this so I'll pass to you

**Comment by SlayksWood** [comment]
check this one after fixing #17313
