### ISSUE TITLE
[0.9.0.0 beta staging-1732] No linked inventory on crafting station upon update

### ISSUE THREAD

**Issue by Draveynz** [StrangeLoopGames/EcoIssues#17818]
Version:
v1732
Reporduction:
Open workbench, click on Storage inventory

Expected Behavior:
Show Nearby Stockpiles, Inventory

Actual Behavior:
No Inventory Nearby, even with stockpile is next to it

updated from 1728 now several workbenches can not see stockpiles
other are intermittent. 

Research/Anvil/Kiln/Wainwright/Masonry/Cement Kiln/Rolling Mill/ does not see any stockpiles
Sawmill/Carpentry/Tailoring/Assembly Line/Lathe/Shaper/Screw Press/Machinist Table take few seconds to load the stockpiles

Assembly Line is furthest from stockpile and it can still see it.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5104930/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5104931/Player-prev.log)

![linkedstockpiles](https://user-images.githubusercontent.com/68322457/90811513-58e74e80-e2ea-11ea-9dd7-65cdd39f174f.png)

**Comment by Draveynz** [comment]
Research/Anvil/Kiln/Wainwright/Masonry does not see any stockpiles
Sawmill/Carpentry/Tairloring take few seconds to load the stockpiles

**Comment by Draveynz** [comment]
Restarted game twice, seemed to fix it temporary

**Comment by Sobaton** [comment]
same here whit Screening Machine.. the machine still work, but dont show the stockpiles
+ mass bug (red spot on screen)

**Comment by IcedForge** [comment]
This is not limited to workbenches, this happens on any storage inventory window with the latest build im experiencing 2x -> 4x longer times to open inventories / access stockpiles/vehicles now.

**Comment by RedBaron88** [comment]
My players have reported this issue as well.

**Comment by SlayksWood** [comment]
linked inventories always work now, but still have exceptions, so I opened a separate issue #17871
