### ISSUE TITLE
5.6 Server Bug - Mortared Stone in Storage Chest

### ISSUE THREAD

**Issue by OzHawkeye** [StrangeLoopGames/EcoIssues#1782]
Server, Client or Website? Server
OS/Web Browser? Firefox
Detailed Description of Issue: I had my new placed Quarry create some Mortared Stone. Instead of placing the output into the Stockpile (which was in range to be linked and was never full), it placed the Mortared Stone into a Storage Chest (despite the fact that Storage Chests shouldn't be able to hold items that need to be carried). I now cannot remove the stone from the chest, nor, consequently, remove the chest.
Reproducible? How difficult is to reproduce? Pretty easy, since all subsequent Mortared Stone jobs are going into this chest.
Additional Comments: Kinda killed the game, since I can't use the Quarry to make Mortared Stone, therefore I can't build stone buildings, preventing me from making a Kiln, preventing brick, etc and so on.
Client Version: 5.6 so far as I know.

**Comment by metachronism** [comment]
fixed as part of alpha 6 inventory optimization/overhaul
