### ISSUE TITLE
Eco Steam Upgrade

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17826]
Upgrade our steam page to have gifs
https://1drv.ms/w/s!AnNPKT4C9Ig9pn2xPJoLHpPhA7_f?e=pbEbZb

Also add any of the good latest screenshots to the screenshots section!

Looks like dimensions for animation images should be 615 px wide, and whatever we want pixels tall, probably around 200 px.

**Comment by keegan-o** [comment]
Phase one of this task is complete, I got lots of animated images on the store page and added lots of new 9.0 screenshots to the screenshots. Will still add at least an item scrolling animated image and probably a few more updated screenshots before calling it good for 9.0.

**Comment by keegan-o** [comment]
https://store.steampowered.com/app/382310/Eco/

Alright, I think I got this good to go for 9.0. From here it's just more updates to the screenshots (and of course eventually trailer).
