### ISSUE TITLE
Visual Ghost Elevator Call Post

### ISSUE THREAD

**Issue by jellyfluff** [StrangeLoopGames/EcoIssues#17828]
I placed the wooden elevator call post but its shadow ghost remains , I've re-logged multiple times.

![image](https://user-images.githubusercontent.com/69574955/90844226-0b3e0680-e329-11ea-91ab-e5a1dd1e37fb.png)
While holding an actual wooden elevator call post, the ghost remains next to it.
![image](https://user-images.githubusercontent.com/69574955/90844480-9ddea580-e329-11ea-9059-837b0577ed4b.png)

**Comment by SlayksWood** [comment]
@jellyfluff Can you provide log files? I have a lot of exception in staging-1732, it's maybe related with #17809
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by jellyfluff** [comment]
It says its too big "Try again with a file smaller than 10MB"

**Comment by SlayksWood** [comment]
Can you add to any free Cloud Storage? like OneDrive, Google Drive or Dropbox

**Comment by jellyfluff** [comment]
https://drive.google.com/file/d/1pyP_YyF81eDtg1lKcAf1Sh3wt25JTQpf/view?usp=sharing

**Comment by SlayksWood** [comment]
```
NullReferenceException: Object reference not set to an instance of an object.
  at ShadowPlacement.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
My exception with Call Post was fixed in staging-1733. I close this issue for now. Reopen please it if you will have this problem in staging-1733 or newer
