### ISSUE TITLE
[0.9.0.0 beta staging-1732] Ui Map - Markers on Crafting

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17821]
Is it possible to change and or enable/disable automatically making markers for every craft you start?

Currently once you start to be further down the cycle and you start to have a lot of different machines and crafting tables
the map marker creations starts to get very annoying as there is no way to stop it from spam creating markers. And you cannot just click delete all as that would also remove any markers you actually want to keep.

Suggestion - 
1. Enable / Disable ( menu button checkbox ) for automatic marker creation on crafting.
2. Tie in crafting markers to the top right corner fast access/view craft so it is possible to checkbox mark the item craft you want to keep an extra close eye on.
3. Add a sub folder for Markers for "Crafting markers" vs "player manual created markers"

**Comment by SlayksWood** [comment]
merged to #14717
