### ISSUE TITLE
Minimap Refactoring Assistance: Make display of property overlays use the same shader as in the landscape

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17820]
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/a9a37eba-7b20-498f-81f1-e587a2480b3d)
It should use the same shader so that it has those nice borders. 
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/b91e46ce-63d0-43cf-bc58-7117b302f508)

**Comment by johnkslg** [comment]
This one needs to be applied in the new refactored towns branch, or wait till it gets merged

**Comment by johnkslg** [comment]
Theres a ton of changes to minimap rendering in there

**Comment by ptitducanh** [comment]
@johnkslg do we already have pr for towns branch?

**Comment by ptitducanh** [comment]
is this cool?
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/6760fd6a-3c93-4598-82e1-0b665f55ab6c)

**Comment by SlayksWood** [comment]
my horizontal lines are much thicker than vertical ones:
![image](https://user-images.githubusercontent.com/45708377/99356310-01418a80-28bb-11eb-9c7b-a83e5724e5e1.png)
![image](https://user-images.githubusercontent.com/45708377/99356382-1c13ff00-28bb-11eb-978a-f774bbae161d.png)

**Comment by ptitducanh** [comment]
They're even now :D
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/1ae1f711-c8ee-48b2-ad15-2d5e381c5a8a)
