### ISSUE TITLE
[0.9.0. staging-1732] Rubble chunks don't unload

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17827]
It seems rubble chunks do not unload. Here is how to replicate:

1.) Have save that has a lot of stockpiles with rubble: 
https://drive.google.com/file/d/1HIsUxTzJykm4xWam0SKmmCaj_2j4UYdf/view?usp=sharing

2.) Use fly command to move all over the map, especially by stockpiles

3.) After flying by a lot of rubble, go to an isolated area

4.) See this: 
![RubbleChunkSpam](https://user-images.githubusercontent.com/47330823/90836699-efc10480-e304-11ea-9437-4a0b31448fe0.png)

**Comment by mirasrael** [comment]
These rubbles is pooled objects (as you can see they disabled) and doesn't make impact on performance. They probably should be grouped under some pool game object, but it is very minor issue.
