### ISSUE TITLE
Backpack when opens also opens clothing options every tim

### ISSUE THREAD

**Issue by Crea-Elle** [StrangeLoopGames/EcoIssues#17824]
Every time you open your backpack, the clothing option also opens. 
![cloth](https://user-images.githubusercontent.com/62965859/90832536-d6b35600-e2fa-11ea-8af5-e8c4a9dc97f0.JPG)

**Comment by SlayksWood** [comment]
Step to reproduce:
- open backpack:
![image](https://user-images.githubusercontent.com/45708377/90855739-fbeea580-e388-11ea-86d0-7232cb6aa7dd.png)
- hide clothes:
![image](https://user-images.githubusercontent.com/45708377/90855760-07da6780-e389-11ea-8b4c-a16818793bad.png)
- close backpack. I have error in log:
```
GameObjects can not be made active when they are being destroyed.
DropDownToggle:UpdateDropDown(Boolean)
UnityEngine.Events.UnityAction`1:Invoke(T0)
UnityEngine.Events.InvokableCall`1:Invoke(T1)
UnityEngine.Events.UnityEvent`1:Invoke(T0)
UnityEngine.UI.Toggle:Set(Boolean, Boolean)
DropDownToggle:ReleaseInstance(Boolean)
```
- open backpack:
![image](https://user-images.githubusercontent.com/45708377/90855802-293b5380-e389-11ea-9f97-3848ffa9e6fb.png)
- clothes are openned again.
