### ISSUE TITLE
Minimap Refactor Assistance: Trees arent toggling on and off in the minimap config panel 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17829]

**Comment by gzatravkin** [comment]
Here the problem was in missing values of list in MinimapConfig. Proabably was deleted during reafctoring. Restored in Editor refactoring.

**Comment by gzatravkin** [comment]
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/941d5a19-3557-4e58-a2aa-9c0575058d7a)
