### ISSUE TITLE
Bloomery can overload Cart at Crafting with Tailing's.

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1783]
Before i take the Screenshot
![tailing](https://user-images.githubusercontent.com/26040573/27992988-b83a5e52-64a0-11e7-9f3e-3b864911f01e.jpg)
 it took 10 Tailing's out	.

**Comment by metachronism** [comment]
this is intended;  if the cart is checked as a valid location for finished items, then those items will get dumped there
