### ISSUE TITLE
Some minimap property colors are too opaque

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17847]
![image](https://user-images.githubusercontent.com/3536496/90938992-599de480-e3bf-11ea-9c32-7aa44f7cb512.png)

In general they all should be more transparent. This green here makes whats beneath it completely invisible.

**Comment by IcedForge** [comment]
![Screenshot_385](https://user-images.githubusercontent.com/24981362/93202452-fd767800-f752-11ea-9c27-99e60820d5ca.jpg)
The green is still too opaque to have terrain visible under it, and pink is almost in the same area

This is the highest color saturation levels you have before it stops having terrain visible below the claim
![Screenshot_387](https://user-images.githubusercontent.com/24981362/93202965-e421fb80-f753-11ea-8ca0-3f89d709c268.jpg)
![Screenshot_388](https://user-images.githubusercontent.com/24981362/93202968-e5ebbf00-f753-11ea-9bea-eeb9d78a454c.jpg)


When seen in world
![Screenshot_386](https://user-images.githubusercontent.com/24981362/93202756-82619180-f753-11ea-984e-e217f0119e4a.jpg)

**Comment by SlayksWood** [comment]
Still an issue for black, but black is generally a very problematic color for property and there is a separate issue for it #9168.
Closed for now.
