### ISSUE TITLE
Strange behavior of objects edges near water

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17842]
\
**Version:** 0.9.0.0 beta staging-1732

**Steps to Reproduce:**
с строительным блоком посмотреть на воду в паре блоков от берега

**Expected behavior:**
без изменений
[скрин](https://cdn.discordapp.com/attachments/743588336802726060/746458940035825664/unknown.png)

**Actual behavior:**
Края начинают вести себя как волны

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
steps to reproduce:
- take some logs and look at them when background is water. You have strange behavior on border:
![image](https://user-images.githubusercontent.com/45708377/91014780-ab7a8080-e5f2-11ea-8539-a83051f02800.png)

**Comment by redwyre** [comment]
do you just mean the edge of the logs going wiggly?

**Comment by beastyn** [comment]
@redwyre yeap, exactly.

**Comment by TwixterZ** [comment]
its subtle, but same can still be seen in 9.2.4 

https://gyazo.com/0ee1df2e84ecd6d106b9ef90154991ea

**Comment by redwyre** [comment]
This is just an artefact with the water reflection. I think it may be possible to add an option to use a higher quality shader at the cost of performance.

**Comment by WeaselDog** [comment]
Fixed in version 9.5 with a setting to enable/disable higher quality water settings
