### ISSUE TITLE
Use adminToken on cw website

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17844]
because most users buy cloud world, then login to game on steam. 
if their steam account isnt linked to their eco account, 
then game server doesnt register their eco account as a user on the server. 
Then server blocks them from editing server configs on accounts website.

website interacts with game server via rest queries.
see GameServer:Port/swagger for examples of queries.

**Comment by gzatravkin** [comment]
For that you can use adminToken from userconfig.

![image](https://user-images.githubusercontent.com/53317567/91050802-905d4000-e5f5-11ea-98b8-4786a8b231d9.png)

**Comment by j3fffff** [comment]
yes, forgot about that. good idea
