### ISSUE TITLE
USER ISSUE: Баг с отображением брызг воды

### ISSUE THREAD

**Issue by ferrumbasso** [StrangeLoopGames/EcoIssues#17843]
\
**Version:** 0.9.0.0 beta staging-1732

**Steps to Reproduce:**

**Expected behavior:**
отображение брызг

**Actual behavior:**
отображение черной текстуры (у нескольких игроков), лечится перезаходом
[скрин1](https://cdn.discordapp.com/attachments/743588336802726060/746284795809497108/unknown.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ваниль 100%

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Спасибо за отчет по багу.
Он известен, свзяан с ломающимся шейдером, закрываю как дупликат #14042
Dup. Closing
