### ISSUE TITLE
USER ISSUE: Cement Kiln gives off ground pollution

### ISSUE THREAD

**Issue by Aperson93** [StrangeLoopGames/EcoIssues#17856]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Create Cement

**Expected behavior:**
Give off Smog pollution, but not ground pollution

**Actual behavior:**
It is give off only air pollution

**Do you have mods installed? Does issue happen when no mods are installed?:**
It is give off only air pollution

**Comment by SlayksWood** [comment]
This is intended behavior for now. You can add suggestion about add ground pollution to some craft station. Closed for now.
