### ISSUE TITLE
adminToken error on CW API auth

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17855]
CW UI trying to use adminToken, 
but that doesnt work on updated servers, even though they have one in db
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/c978f964-29f1-4d85-bd0d-cdf1357000bd)

**Comment by denysaw** [comment]
@j3fffff As from Accounts AdminToken is passed right now even for server `upgrade`, that means, that CW API aren't accepting AdminToken for `/api/instance/upgrade` method. Please, change controller to be able to receive AdminToken and store it in the world's config ;)

**Comment by j3fffff** [comment]
all old worlds should be reset so this update worlds
