### ISSUE TITLE
Minimap Refactor Assistance: Property getting added multiple times when disconnecting and reconnecting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17852]
![image](https://user-images.githubusercontent.com/3536496/90944710-6594a100-e3d5-11ea-8e01-19f23037e2e9.png)

Pooling is calling PropertyManager.Awake with each connect, but not PropertyManager.Destroy.

**Comment by gzatravkin** [comment]
It is not related to pooling (PropertyManager don't implement any), just wrong name of method. Should be OnDestroy (it's called by Unity). Fixed in editor refactoring PR
