### ISSUE TITLE
'Withdraw From Election' in Ballot Box doesn't work

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#17857]
1. Hi, I'm at White Tiger, lastest version for 9.0 test (0.9.0.0 beta staging-1732.
2. I started an election, and now I can''t withdraw from it.
3. I expected to be able to withdraw from election
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5112535/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5112536/Player-prev.log)
Contact AgathaPwned in Discord or Contra in White Tiger for more information if needed

![image](https://user-images.githubusercontent.com/4639977/90958825-fb443500-e496-11ea-949a-951a2cacc608.png)

**Comment by johnkslg** [comment]
@D3nnis3n can you attach relevant game save?

**Comment by D3nnis3n** [comment]
Unfortunately we don't have any backup from August 22 left, they've already been removed automatically.
