### ISSUE TITLE
 [0.9.0.0 beta staging-1732] Election Minimum voters required tweak?

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17866]
Currently the Minimum voters are set to 25% in the basic election process.
If this is set to 0, it is automatically counted as a default win as long as a election has a participant.
![Screenshot_77](https://user-images.githubusercontent.com/24981362/90967970-425a1680-e4e7-11ea-9907-ec71cb8d735d.jpg)

Expected outcome this would not automatically WIN by default with 0 votes.
an election with 0 votes should count as a failed election.

**Comment by beastyn** [comment]
Why not?
If you are pointing minimum as 0 you are expecting that you should not get any votes at all for winning. 
From logic point of view its intended.
Just do not place 0 as a default value.

**Comment by IcedForge** [comment]
It feels a bit unintuitive that an election with 0 votes would auto win instead of be a failed election as not even the individual running for office voted.

**Comment by IcedForge** [comment]
Further adding to this. 
Have a title appointing another title, if there is no one holding the first title the second title is an auto win as
0 votes / 0 elected eligable voters = 100% and with 0 votes allowing auto win ends up with this.
![Screenshot_35](https://user-images.githubusercontent.com/24981362/101999362-89f5ef80-3cdc-11eb-8c0c-a23b5e57c727.jpg)

President elects the director of the federal bank, but because there were no president when the election ended the player participating won the election with 0/0 votes.

There should be a hard coded MIN 1 vote to win an election of any type.
