### ISSUE TITLE
 [0.9.0.0 beta staging-1732] Admin command "/titles Assign" not functioning properly

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17867]
Tried assigning someone to a title position and it clearly states that it successfully ran the command and it worked but in reality it did not, and just added myself into the title not the userid i pointed towards, and username did not work either.

As you can see here, it ran the command and registered it as a function - no errors.
![Screenshot_79](https://user-images.githubusercontent.com/24981362/90967994-98c75500-e4e7-11ea-83c8-30915df4a24c.jpg)

But in reality it added me to the title instead for unknown reasons.
![Screenshot_80](https://user-images.githubusercontent.com/24981362/90968013-e3e16800-e4e7-11ea-9a73-ac444928fbe7.jpg)

**Comment by RemonRamy** [comment]
This is now resolved, closing.

Internal reference: https://app.clickup.com/t/10591183/ECO-22006
