### ISSUE TITLE
USER ISSUE: Trying to buy properties

### ISSUE THREAD

**Issue by retmet** [StrangeLoopGames/EcoIssues#17860]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. I tried to buy a property in Real Estate Desk when other person buy this property with the desk in it.
2. A message said "You can't afford to buy this deed for 2000 Money. You only have 2029."

**Expected behavior:**
I should be able to buy it

**Actual behavior:**
It won't let me buy it

**Do you have mods installed? Does issue happen when no mods are installed?:**
No, i dont.

**Comment by SlayksWood** [comment]
Thank you for the report. This bug should be fixed in 0.9.0.
Closed for now.
