### ISSUE TITLE
USER ISSUE: Particals create a black hole

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#17869]
\
**Version:** 0.9.0.0 beta staging-1732

**Steps to Reproduce:**
No clue how this happens, but it has happen more than once.

**Expected behavior:**
Normal particals for grabbing stone/dirt should make a neat little partical effect..however...

**Actual behavior:**
Instead it creates a growing black circle and make the whole server seems dark to the player this bug hits. Other on servers are not effected by it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. No changes in the code or files either.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Thank you for the report. You can have it with teleport or fast running (whith a lot of chunk loading).
Dup, have it here  #14042
