### ISSUE TITLE
 [0.9.0.0 beta staging-1732] Citizen Statistics - Gain Specialty does not track

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17862]
Trying to request to fetch Citizen Statistics for Gain Specialty yields 0 result.

![Screenshot_92](https://user-images.githubusercontent.com/24981362/90967519-8990d900-e4e0-11ea-9b48-06513aea76b9.jpg)
![Screenshot_93](https://user-images.githubusercontent.com/24981362/90967520-8a296f80-e4e0-11ea-9bf4-663ca45a5a8b.jpg)

Expected result -  Should say 8 not 0 
![Screenshot_94](https://user-images.githubusercontent.com/24981362/90967532-b7761d80-e4e0-11ea-96f6-0fb5665c5027.jpg)

Tested using this in a law as well to prevent skill up and it gives 0  result on a fresh 1732 built world.

**Comment by beastyn** [comment]
Thank you, good find.
You can try to use custom statistic for now, it should work fine (I'm not quite sure if it will fit you needs)
@olegshegai I'm pointing this one for the 9.0 release but if it's hard to fix, then tell me olease and we will push it,

**Comment by beastyn** [comment]
@olegshegai the problem seems to be deeper. All actions have lost their stats. Can you check it please.

**Comment by IcedForge** [comment]
This is becoming a clear issue in law creations based on timers such as this
![Screenshot_153](https://user-images.githubusercontent.com/24981362/91463082-41c8d380-e88b-11ea-814a-dacf3a550fb2.jpg)
If anyone can think of another way to work around not using Citizen statistics in time based laws id gladly hear it but right now im getting more requests for laws on timers that cant be made since the individual tracking seems off?

**Comment by MishkaFur** [comment]
Yea this is somewhat required for alot of the laws players will end up creating ie can only mint every 24 hours, hunting limits etc

**Comment by Twerk17** [comment]
Yes I tried to create a law preventing the use of stars after a certain point and it continued to allow it due to this issue.

**Comment by IcedForge** [comment]
Current work around for this particular law 
![Screenshot_95](https://user-images.githubusercontent.com/24981362/91666455-2e24a380-eafd-11ea-91b0-b9918772f4df.jpg)
Where you change the "Right" value to what ever you want the limit to be for specialty picking.

**Comment by beastyn** [comment]
Counting starts from 0 (or its just in test law) Issue is here #18077
