### ISSUE TITLE
Laws, Demographics

### ISSUE THREAD

**Issue by AndreK78** [StrangeLoopGames/EcoIssues#17876]
Hi
is it now possible to makes only 3 Laws at the court? Or I dont understand the new Law System? The same for Demographics - I can make only 3 new demographics? 

Or is this a bug? 

best regards

**Comment by IcedForge** [comment]
Each government object only features 3 slots yes that is intended as far to my knowledge.

**Comment by AndreK78** [comment]
hmm ok, but doesn't that take away the strength of the new possibilities ?! I would think that's a shame ... :(

**Comment by beastyn** [comment]
You can place one more civics table (court, zoning office, etc) and create there more objects. There is no limit for tables number.
