### ISSUE TITLE
USER ISSUE: Character stuck

### ISSUE THREAD

**Issue by dwnetdev** [StrangeLoopGames/EcoIssues#17879]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Create a corner with stone blocks.
2. Place 1 trash square in corner.
3. Jump into corner while on an empty stomach.
4. User becomes stuck and unable free themselves because user cannot perform work when hungry so tools wont work to free self.

**Expected behavior:**
Either some way to free youself when in this situation or the ability to at least use your hammer to remove blocks			

**Actual behavior:**
Game is dead.  Must start all over when playing solo.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Game is dead.  Must start all over when playing solo.

**Comment by SlayksWood** [comment]
@dwnetdev Thank you for the report. 
You can use "/unstuck" to free your avatar in difficult cases. We have plans to improve user experience with user commands.
So closed for now, please reopen if this doesn't help.
