### ISSUE TITLE
[0.5.6.1] No texture on Compost Pile

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#1787]
As you can see below there si texture on Compost Pile. And no usage when we open it.

![004](https://user-images.githubusercontent.com/29807119/28000306-30d23b44-6525-11e7-977c-bc0a30dffe0e.PNG)
![003](https://user-images.githubusercontent.com/29807119/28000288-19fcbdc2-6525-11e7-9988-dc60bab12e23.PNG)

**Comment by craig-jong** [comment]
This item should not even be in the game right now - I guess we can try and get it in for A6.

**Comment by keegan-o** [comment]
Will get to the object when we world object art is being worked on. Many world objects still need art or updates, so not really bugs, it's content.
