### ISSUE TITLE
[0.9.0 staging-1736] Accounts: link for Modkit won't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17873]
So, now we have a link for the modkit download, but it will show me an error

This XML file does not appear to have any style information associated with it. The document tree is shown below.
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>EcoModKit_v0.8.3.3-beta.zip</Key>
<RequestId>56F2F8B25CEC9637</RequestId>
<HostId>1nl5on+ZQZrGF7Zf+c6Inx0tpkNILv0bDt6HWcPSTurVqNrxWn7Fbz5MqWOLNIOouvUwRrJKEN8=</HostId>
</Error>
```
I suppose we need to fix it?

**Comment by redwyre** [comment]
It's only a problem because there is no existing modkit for 8.3.3, it should work fine when 9.0 is added.

**Comment by beastyn** [comment]
Thanks. I hope so. I will close for now )
