### ISSUE TITLE
EcoForum: Old to new forum 301 redirects for preserving old links and SEO

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#17878]
USERS:
https://forum.play.eco/members/dennis.4929/ -> https://forum.play.eco/core/user/1-dennis/ (I got a new ID on the forums, so ignore that, its just about the ID)

TOPICS:
https://forum.play.eco/threads/eco-mods-rules-guidelines.33/ -> https://forum.play.eco/thread/33-eco-mods-rules-guidelines/

FILEBASE:
https://forum.play.eco/resources/colored-vehicles.189/ -> https://forum.play.eco/filebase/file/189-colored-vehicles/

BOARD:
https://forum.play.eco/forums/news.4/ -> https://forum.play.eco/board/4-news/

POSTS:
https://forum.play.eco/threads/new-official-forums-for-eco.1096/#post-4689 -> https://forum.play.eco/thread/1096-new-official-forums-for-eco/#post4689

**Comment by denysaw** [comment]
Done. Changes were made not only in `.htaccess` but also in `/httpdocs/templates/thread.tpl` (for rewriting anchors as it's impossible with .htaccess, cuzz hash isn't being sent to server).

**Comment by denysaw** [comment]
@D3nnis3n check and close if all is ok ;)

**Comment by D3nnis3n** [comment]
Works, thank you!
