### ISSUE TITLE
[0.9.0 Staging] Need sprites for Barter Trade & Didn't Vote

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17887]
The trade game action is now split into two: Barter Trade & Currency Trade.  We need a new sprite for the Barter Trade game action. The old icon for Trade can be used for Currency Trade.

In addition there is a new game action, "Didn't Vote". We need a sprite for this as well. It can be something simple for now based on the vote sprite.

**Comment by RobertMangano** [comment]
added to icon sheet 04

**Comment by RobertMangano** [comment]
![bartericon](https://user-images.githubusercontent.com/26705633/91251189-3ba8f900-e79e-11ea-9735-d0b68f80f4ad.jpg)

**Comment by WeaselDog** [comment]
Very nice!
