### ISSUE TITLE
CLoud World missing serverID

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17885]
User sucessfully reset world save but serverID and server url were not updated in db.
So now on UI, world looks like its about to load up, but there is an error in bottom right `Not Found`
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/71d381ce-2de3-4b22-bcb0-c4b8f914ff9f)

As a backup for this situation, maybe we should have a check for worlds that are missing data in db, but cw api is returning normal world data

**Comment by denysaw** [comment]
@j3fffff That just meant, that CW API didn't return serverId and webServerUrl (failed with error). We'll even adding new world in such case right now (cuzz of payment things). But as for reseting world save, we could just show the error and don't write empty serverId and url in DB. Will do.

**Comment by j3fffff** [comment]
ya, and with reset button, right? so they can do something about it
