### ISSUE TITLE
Eco Server / Client doesn't Show All Languages Supported

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#17888]
The Eco Client only has limited languages to choose from where the Localization csv's have many more, 
The same goes for the Eco Servers, 

One example of this:
"BrazilianPortuguese" Is a language we can localize for or has localization's done for this language but is not a language that can be selected in the server settings or client settings.

More Examples:
Localization for my Modpack Elixr Mods:
https://docs.google.com/spreadsheets/d/19iKX9u3spqcYcZ89K2X2aGekS5jRn5h-IVmSagS3EY4/edit#gid=41903805

Default Eco Localization File:
`"English","Gibberish","French","Spanish","German","Korean","BrazilianPortuguese","SimplifedChinese","Russian","Italian","Portuguese","Hungarian","Japanese","Norwegian","Polish","Dutch","Romanian","Danish","Czech","Swedish","Ukrainian","Greek","Arabic","Vietnamese","Turkish"
`
The server and eco client only displays 10 languages to choose from but the localization's show 24 total languages

I know not all are completed translations, 

Could these languages be missing due to incomplete localizations?

**Comment by TheKye** [comment]
![unknown (1)](https://user-images.githubusercontent.com/29281156/91242729-83725500-e78b-11ea-9824-4364f803eff4.png)
This image was provided by another user showing their changes using the localization.eco file not working (8.3.3)

**Comment by SlayksWood** [comment]
Some languages are hidden and are available only during development. 
@WeaselDog @johnkslg 
can we revise what languages ​​are available in the game?
We have several languages ​​in crowdin that are not represented in the game:
![image](https://user-images.githubusercontent.com/45708377/91526843-361df100-e90d-11ea-81c7-64bd1fdb0534.png)
![image](https://user-images.githubusercontent.com/45708377/91526959-74b3ab80-e90d-11ea-8770-16f97d54e857.png)
![image](https://user-images.githubusercontent.com/45708377/91526975-7da47d00-e90d-11ea-8734-ce82ac7846e1.png)

**Comment by SlayksWood** [comment]
This behavior was changed. For a language to appear in selection, you need 30% of the translation or more
