### ISSUE TITLE
[0.9.0 staging-1740] Empty notification when voting.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17889]
Step to reproduce:
- start any election. Press Yes/No. I have empty notification:
![image](https://user-images.githubusercontent.com/45708377/91261691-87e14280-e778-11ea-9b18-45d24b30f4af.png)
![image](https://user-images.githubusercontent.com/45708377/91261773-8d3e8d00-e778-11ea-84e5-4c58da47aec2.png)

**Comment by redwyre** [comment]
It looks like might be happening every time someone votes
