### ISSUE TITLE
[0.9.0.0 beta staging-1732] Law : Server exception on changing laws too quickly

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17883]
When changing laws too quickly in succession it kicks me out ( tried 5 times now and the same thing happens every time)

1. Start a fresh world and setup law objects etc
2. Add a law and modify it, then modify it with another number in anything then do it a 3rd time fairly quickly and it will kick you out with following error.

![Screenshot_107](https://user-images.githubusercontent.com/24981362/91172259-266b9600-e6dc-11ea-88b8-f6e25a6fb8a7.jpg)

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1740.
Can you provide a bit more information. 
What Article for law do you have? everything is detailed, step by step. And provide log file

**Comment by IcedForge** [comment]
https://i.gyazo.com/b76f769abacc63ce43a354081da2da2e.mp4
Just kept changing out the number value of a law ( doesnt seem to matter what specifications )
it did take 10-12 times now ( last time i tried it only took me 2-3 times for the exception to throw me out.

Server log
[log_200826101600.log](https://github.com/StrangeLoopGames/EcoIssues/files/5128502/log_200826101600.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5128504/Player.log)
World file
[Storage.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5128509/Storage.zip)

**Comment by TwixterZ** [comment]
Re-tested on 9.5 Staging-2287 by re-enacting same law (adjusting amount) for about 35 times, does not reproduced 
![image](https://user-images.githubusercontent.com/78054747/163523512-187debda-178e-4ed0-93b3-8b470938944b.png)
Closing this for being an old issue
