### ISSUE TITLE
[1740] Double "not authorized" message

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17897]
![image](https://user-images.githubusercontent.com/25908592/91322630-42486800-e7c0-11ea-8e35-5bbf38aeebb9.png)

**Comment by madpingui** [comment]
Tested on Steam Version 0.9.2.4 Release-156, editor Unity develop branch and editor unity staging branch.
In all of them it returns 1 notification
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/9b241e26-ecc5-4f60-ba70-091b30fc02ec)

**Comment by SlayksWood** [comment]
seems was fixed:
![image](https://user-images.githubusercontent.com/45708377/121014484-b4fc6000-c7a2-11eb-95be-293401844ce3.png)
