### ISSUE TITLE
[0.9.0 staging-1740] Wrong icons for some furniture.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17892]
- [x] 1. Composite Softwood chair has 4 stars. Should be 3.
![image](https://user-images.githubusercontent.com/45708377/91299062-ba576380-e7a9-11ea-8aed-8e0baf1042b5.png)

- [x] 2. Lumber bench has wrong material on icon (looks like Birch)compared to lumber chair and lumber table:
![image](https://user-images.githubusercontent.com/45708377/91299192-ea066b80-e7a9-11ea-87a6-52ee8bb0d196.png)

**Comment by RobertMangano** [comment]
committed changes to staging
