### ISSUE TITLE
[0.9.0 staging-1740] Plants look blurry

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17906]
There is something wrong with how plants are rendering so they look blurry and kind of like a blob.
![PlantBlobs](https://user-images.githubusercontent.com/47330823/91380036-dcb4a580-e7d8-11ea-8783-28f03ff4d9b1.png)

**Comment by WeaselDog** [comment]
Can't reproduce this anymore.

**Comment by WeaselDog** [comment]
Reproduced on 1742. I am not sure how to cause it yet.

**Comment by mirasrael** [comment]
I refactored plants rendering. Probably this issue fixed as well.

**Comment by beastyn** [comment]
I will close it.
@WeaselDog  please reopen, if happens again
