### ISSUE TITLE
[playtest-1740] Can't use road tools on "Desert Sand" dirt in desert biomes

### ISSUE THREAD

**Issue by KhisanthMagus** [StrangeLoopGames/EcoIssues#17901]
As of 1740 you can no longer use road tools on the dirt in the desert, which is named "Desert Sand" but if you scoop it with a shovel it is just dirt.  If you scoop it and put it back down so it is plain dirt it can then be stamped with a road tool.  No errors appear in the dev or server console for this.

**Comment by mirasrael** [comment]
It is intended behavior. Desert Sand can't be converted to Road and Dirt Roads in Desert may be eventually destroyed by unfriendly environment.
