### ISSUE TITLE
[0.9.0 staging-1740] Unable to vote on Giant Panda

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17905]
Steps to replicate:

- Login to server and press "L" to access Government UI
- Go to Legislation tab
- Click "Vote" on current election
- Press either Yes or No to vote
- Status gets stuck to Submitting and this error appears in bottom left corner
![VoteError](https://user-images.githubusercontent.com/47330823/91379198-f48b2a00-e7d6-11ea-8bc2-8802b126e5da.png)

**Comment by denysaw** [comment]
@redwyre Hey, any ideas why auth token is incorrect?
