### ISSUE TITLE
[0.9.0 staging-1741] Meteor orbit is too low

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17914]
It appears from ground:
![image](https://user-images.githubusercontent.com/45708377/91411835-97808a00-e851-11ea-9b13-75962eb7543b.png)
Looks very strange at the highest points in the world:
![image](https://user-images.githubusercontent.com/45708377/91411995-ce56a000-e851-11ea-8869-c46249b23f45.png)

**Comment by redwyre** [comment]
It apparently doesn't work when you're flying

**Comment by SlayksWood** [comment]
I'm not flying I stay on mountain
