### ISSUE TITLE
Campfire Stew is available in the store

### ISSUE THREAD

**Issue by Crea-Elle** [StrangeLoopGames/EcoIssues#17918]
Campfire Stew is available to select in the store, but not available to cook at the campfire.  Also, when hovering over the tooltip, no recipe is linked or displayed.
![cs](https://user-images.githubusercontent.com/62965859/91434475-b2cfa300-e819-11ea-85c3-8ad1e0123c6e.JPG)

**Comment by ashleysilverdust** [comment]
Glad someone mentioned this! It should either be completely gone from the game, or be craftable - one or the other.

**Comment by WeaselDog** [comment]
Thanks for letting us know! This will be fixed in the next update.
