### ISSUE TITLE
Cancelling a project on any crafting table kicks you for inactivity and sometimes crashes your client

### ISSUE THREAD

**Issue by Neurotik** [StrangeLoopGames/EcoIssues#1792]
I and and many people on my server are getting kicked for cancelling projects. The server boots us for inactivity and then all the tables on the server get frozen and will not craft until a restart.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1137146/output_log.txt)

**Comment by Darkwolf6180** [comment]
Same is happening on the server I play upon. It's extremely frustrating and /needs/ to be fixed to allow less maintenance to servers and less days where nothing can be done.

**Comment by Egrof** [comment]
Had the same crash, cancelling production in a Mill 
client 5.6.1 on Windows 10 x64
