### ISSUE TITLE
USER ISSUE: Animals vanish when shot by another player in multiplayer

### ISSUE THREAD

**Issue by Wh00pAss** [StrangeLoopGames/EcoIssues#17927]
\
**Version:** 0.9.0.0 beta staging-1740

**Steps to Reproduce:**
Multiplayer game, someone else kills an animal, as soon as it dies, it vanishes from my screen but they can see it and collect it.

**Expected behavior:**
I should be able to see it

**Actual behavior:**
It vanishes

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Thank you for the report. dupe #17718
