### ISSUE TITLE
USER ISSUE: Chest sound

### ISSUE THREAD

**Issue by Wh00pAss** [StrangeLoopGames/EcoIssues#17923]
\
**Version:** 0.9.0.0 beta staging-1740

**Steps to Reproduce:**
Open a chest

**Expected behavior:**
A nice sound, not something so long and obnoxious. When you're on a server with lots of people accessing chests its terrible.

**Actual behavior:**
Plays a nasty long creaking sound

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ashleysilverdust** [comment]
Yes, the chest sound in playtest is so bad that I have turned the game sound off entirely.
