### ISSUE TITLE
setup 301 redirects for new website

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17926]

**Comment by j3fffff** [comment]
Going from step 2 to 3![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/d16a754b-16b9-49a3-9589-4b509b9d6a82)

play.eco ----> / (on aws)
play.eco/team ----> /team (on aws)
accounts.play.eco/home ----> /account
accounts.play.eco/hostedworlds ----> /worlds
accounts.play.eco/products/upgrades ----> /buy
accounts.play.eco/roadmap ----> /#tree (on aws)

These 301 redirects should already be complete, and dont need to be changed
strangeloopgames.com or strangeloopgames.com/about-us ----> play.eco/team
strangeloopgames.com/eco ----> play.eco
accounts.strangeloopgames.com/* ----> accounts.play.eco/*

**Comment by denysaw** [comment]
Done those right in nginx config: `/etc/nginx/conf.d/accounts.play.eco.conf`:
![image](https://user-images.githubusercontent.com/5720101/92419945-cad7e880-f170-11ea-87e7-30b2ae390c72.png)

You just need to uncomment those lines after release and restart nginx with this command:
`sudo service nginx restart`
