### ISSUE TITLE
USER ISSUE: Loup

### ISSUE THREAD

**Issue by Fanois911** [StrangeLoopGames/EcoIssues#17920]
\
**Version:** 0.9.0.0 beta staging-1740

**Steps to Reproduce:**
Écouter un loup

**Expected behavior:**
un meilleur bruit

**Actual behavior:**
vous avez été chercher cela ou qu'un loup sa grognait et hurlait de ce genre la... sérieux ?!?!?!?!

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Fanois911 thank you for the report.
Yes, our wolves are howling quite loud then they are attacking. This should be fixed with this #17915

If I did not get your issue right, please write with more details.
