### ISSUE TITLE
Meteor cutscene triggered while sleeping

### ISSUE THREAD

**Issue by ceresward** [StrangeLoopGames/EcoIssues#17924]
I had an odd problem occur at the start of a new single-player game using the 9.0 public testing.  I had active quests to sleep in the campsite bed, and to look at the meteor.  I decided to do the quest to sleep in the bed first.  I pressed 'E', then the sleep timer began, then my character started to lie down.

As my character was lying down, I guess the camera angle lined up just right somehow to trigger the "look at the meteor" quest, and the cutscene began.  Problem was - my character was still sleeping during all of this!  Multiple in-game days passed during the cutscene, and when I finally got back into the game, it said I had slept for the equivalent of 7 real-world hours!  Needless to say, losing 7 hours right off the bat wasn't the start I was hoping for...

What I would have expected to happen, is either (a) the meteor quest/cutscene should not have been able to trigger while sleeping, or (b) sleeping should have been paused/cancelled when the meteor quest/cutscene began.

**Comment by johnkslg** [comment]
Maybe it's all just a dream?
