### ISSUE TITLE
[0.9.0 staging-1740] No ambient music

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#17921]
I don't know why but in 5 hours play session (me and my friend), nobody had music in their game. Yes we have sounds and environment effects, but never ambient music.

It's really boring without some music, please fix!

**Comment by Quadbro** [comment]
music is doubled in recent fixes, Are you sure you have music slider enabled?)

**Comment by coolfarmer** [comment]
My music slider is by default, at 80%. All my 4-5 friends have the same setting, and we have no music... xD The sound of silence only, except for animal, environment or sound effect.

I hope this will be fixed in final build for sept 9, it's pretty boring without music :(

**Comment by coolfarmer** [comment]
Music is back in 1749, thanks! :)

The song is played for about 5 minutes, and then stop for about ~30 min, then replay for 5 min, etc.
Is it possible to shorten this waiting time before it play again (by maybe having a slider in Audio tab) ?
