### ISSUE TITLE
Rock drill usage stuck mouse when use with /fly

### ISSUE THREAD

**Issue by Sakexz** [StrangeLoopGames/EcoIssues#17925]
Once i use the rockdrill and go out of the ui my mouse gets stuck.

**Comment by Sakexz** [comment]
dev console says "rotation quaternions must be unit lenght"

**Comment by SlayksWood** [comment]
@Sakexz Thank you for the report.  Can you provide video of any additional steps?
Also provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Sakexz Do you use any admin command before like /fly?

**Comment by Sakexz** [comment]
just tried it out again with fly activated, its very likely tbh. clearly you troubleshot my problem for me xD

**Comment by SlayksWood** [comment]
merge to #17167
