### ISSUE TITLE
Accounts: wrong validation for registration form after redirect

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17938]
1) Buy the game (without registration).
2) Try to register after redirect.
3) Do not check age box and letter box.
You will get an error about missing e-mail. But e-mail is fine and error should be about missing checkbox.
![Inkedbandicam 2020-08-28 11-59-02-987_LI](https://user-images.githubusercontent.com/27898520/91531601-79d12480-e926-11ea-8287-1b8082719153.jpg)
4) Check only letter box 
You will get the right error about missing age check
![Inkedbandicam 2020-08-28 11-59-11-011_LI](https://user-images.githubusercontent.com/27898520/91532057-2b705580-e927-11ea-8443-df51981dc00d.jpg)

**Comment by denysaw** [comment]
@beastyn As I remember, I've fixed it about week ago. Please, re-test
