### ISSUE TITLE
User Icon missing in tooltips

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17933]
Before we had the tier icon in front of names in tooltips as well, it's now gone.
As its recognition for players it should be visible everywhere where it was before, not only in chat.

**Comment by SlayksWood** [comment]
And it shouldnot be white too.
![image](https://user-images.githubusercontent.com/45708377/91525203-a460b480-e909-11ea-9f6f-740834d86814.png)
maybe the same problem here #17881
