### ISSUE TITLE
USER ISSUE: Wall of red text flashing

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#17932]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
Unknown

**Expected behavior:**
Nothing

**Actual behavior:**
While playing on a friend's locally hosted server, there is a wall of red flashing text on the left hand side of the screen.  Too fast too read, but really annoying.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5139889/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5139890/Player-prev.log)

**Comment by D3nnis3n** [comment]
It's the debug console and intended to be there :)
