### ISSUE TITLE
Moving Items too fast in between storage causes game clock to freeze. [0.5.6.1 stable]

### ISSUE THREAD

**Issue by Fireboss4** [StrangeLoopGames/EcoIssues#1793]
Moving items too fast in between storage inventories (I.E. Chest to Powered Cart) can freeze the game clock. The best way to prevent this is to slowly move stacks of items and make sure the stack is solidly in its new home before moving to the next stack.

**Comment by metachronism** [comment]
fixed as part of alpha 6 inventory performance overhaul
