### ISSUE TITLE
[8.3.3] Animals dying on their own - check for 9.0 behaviour

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17931]
```
On our school server, I've taken the role of gatherer. This morning, wandering the world, I was surprised by the lack of edibles. I pulled up the web interface, looked at the graphs, and found that prickly pears were gone, and several other edible plants were on their way to extinction (attached jpg). Based on timing, this isn't human-caused. Or at least, it's mostly not human-caused.

Short history of human happenings:

* Days 0 - 6: I went in-game 3-4 times, 5 min each, just to make sure things were working and all was ready for students.
* Day 7 (Tuesday): Students join for our first day of 'class'
* Day 9 (Today): I go looking for foods to gather, and find startlingly few. Papayas and Pineapples seem well. Many other things are declining (see jpg).

I just wanted to share these curious ecological events as an FYI. This is our practice world, so no big deal. But I could imagine it could be significant in other circumstances.
```
![Loss_of_food_diversity](https://user-images.githubusercontent.com/25908592/91518543-ca2d8f80-e8f0-11ea-8d85-da655d8ba753.PNG)

**Comment by SlayksWood** [comment]
Staging-1743, new server lasting 1 hour with updated config, I made 1 restart. All alligators are died, almost all foxes are died too:
![image](https://user-images.githubusercontent.com/45708377/91558092-574b0580-e93e-11ea-883a-591b04be7036.png)

**Comment by TheforestHermit** [comment]
Our server, also Staging-1743 has noticed an almost complete die off of alligators and foxes without hunting. 
Possibly related, the desert vegetation has been dying in massive swathes .  There is over-crowding die off and then there is this. All plants  that are not trees are perishing except in very limited regions. For being desert plants they are not-hardy.

**Comment by mirasrael** [comment]
@TheforestHermit if you started server before recent update then it is intended. We changed Desert balance to supply significantly less plants. So it should be much more spread now. For new world generation it should though balance spawned plants to not make them too overcrowded.

**Comment by WeaselDog** [comment]
@mirasrael Adding you on this one. I will get more data on animal population changes.

**Comment by Spiralexe** [comment]
This issue was in 8.0 aswell for foxes at least

**Comment by mirasrael** [comment]
Main issue with animal simulation fixed, but they still have some drop in population for first few ticks. It is related to plant simulation issues, especially in initial generation phase (I'm working on the fix).
