### ISSUE TITLE
USER ISSUE: Black circle when mining limestone

### ISSUE THREAD

**Issue by GreaseMonk** [StrangeLoopGames/EcoIssues#17934]
![unknown](https://user-images.githubusercontent.com/1354802/91528142-64003700-e907-11ea-92c4-7c866a868f2f.png)
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
1.Set time to night
2.In the desert
3.When mining limestone
4.Then a big black circle effect grows 

**Expected behavior:**
Shown a dust cloud or something	

**Actual behavior:**
Created a black round circle

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@GreaseMonk Thank you for the report. Do you have this issue after restart game?

**Comment by GreaseMonk** [comment]
@SlayksWood this is the second startup of the game. I started the game yesterday and just this morning.
Also, attached, graphic settings which could be related. I'm getting this black blob now with most things, like cutting wood and putting stone into a stockpile.
![Untitled](https://user-images.githubusercontent.com/1354802/91529178-22708b80-e909-11ea-8e34-71defba23187.png)

**Comment by GreaseMonk** [comment]
More of the same issue; placing a log does it too.
![Untitled](https://user-images.githubusercontent.com/1354802/91529283-4d5adf80-e909-11ea-9f98-af9a0c37edce.png)

**Comment by GreaseMonk** [comment]
I will try to reproduce the issue later. After a restart, the issue has disappeared. I suspected that changing the shadow details in the graphical settings was the cause, but alas

**Comment by SlayksWood** [comment]
@GreaseMonk This is known issue, I merged it to #14042
Can you add you PC specification in this issue #14042?
