### ISSUE TITLE
Accounts: Some links in mail is broken

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17936]
After buying game I have 2 letters. In second letter I have a lot of links to download game, forum and etc. Some of them are broken:
![image](https://user-images.githubusercontent.com/45708377/91529777-97948e80-e912-11ea-8c2c-7c3b013e8c47.png)
So broken links:

- [ ] 1. To download game and server: 
![image](https://user-images.githubusercontent.com/45708377/91529846-b85ce400-e912-11ea-9c7f-fdbdcf42b95e.png)

- [x] 2. Wiki link is old. it redirects you to this https://eco.gamepedia.com/Getting_Started, but we already have a new wiki https://wiki.play.eco/en/Getting_Started
9.0 is soon so we can change this link too.

- [x] 3. Forum link is broken. It has old link too http://forum.strangeloopgames.com/, a new one is https://forum.play.eco/

**Comment by SlayksWood** [comment]
ECO Invitation too:
![image](https://user-images.githubusercontent.com/45708377/91542832-f82dc680-e926-11ea-8791-42df9776aab1.png)

**Comment by SlayksWood** [comment]
- [ ] 1. So now I have problems only with a server link:
![image](https://user-images.githubusercontent.com/45708377/96228098-c4bdfe80-0f9d-11eb-8828-a61886ea586a.png)
Since we currently support Linux and Mac server too. Should we add link to it too? like here:
![image](https://user-images.githubusercontent.com/45708377/96228329-1e262d80-0f9e-11eb-822b-12009bdd0b1e.png)

**Comment by denysaw** [comment]
Done. Could be tested on Staging.
