### ISSUE TITLE
Account: Incorrect form behavior if you make a mistake when changing your password

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17941]
So I want to change password in my account page, press Edit Password:
![image](https://user-images.githubusercontent.com/45708377/91534351-0cb79200-e91a-11ea-8654-651f15febf65.png)
- when I enter old password I can make mistake:
![image](https://user-images.githubusercontent.com/45708377/91534497-4be5e300-e91a-11ea-89de-ede5ac8fcec2.png)
- press update. This form was closed and I have notification in right bottom corner:
![image](https://user-images.githubusercontent.com/45708377/91534593-7172ec80-e91a-11ea-94af-3d7b4e597c6b.png)
This is incorrect behavior. First time I didn't see this error and I thought that I changed password.
I should have this error here:
![image](https://user-images.githubusercontent.com/45708377/91534839-ea724400-e91a-11ea-9261-a0fd82c8a600.png)
Also error say "Current Password" in form "Old Password"

**Comment by denysaw** [comment]
> Also error say "Current Password" in form "Old Password"
Current actually means NOT NEW and means old )) But ok, I'll rename

**Comment by denysaw** [comment]
Done. Could be tested on Staging. For styling improvements (if needed), turn to Jeff, pls ;)
