### ISSUE TITLE
USER ISSUE: My Account is Broken

### ISSUE THREAD

**Issue by Twerk17** [StrangeLoopGames/EcoIssues#17948]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
1. Try and Log in Via Steam
2. Try and Log in Via Strangeloop Account	

**Expected behavior:**
Log In

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>You cannot log into this world.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by redwyre** [comment]
When did you buy the game?

**Comment by Twerk17** [comment]
during 8.0 I am in the CW playtest and we had some issues with my server and the changes I made with J3ff made it so I cannot log in to even a single player world it brings up an error.  Let me add the log files

**Comment by Twerk17** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5143318/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5143320/Player-prev.log)

**Comment by j3fffff** [comment]
server is mixed up by following account combinations:
log in with steam => steam id user created
log in with slg => slg account created
log in with steam linked slg => doesn't know what to do with the two existing accounts

go into /Game.eco/Users and remove duplicate slg id that is not linked to steam
a linked account looks like STEAMID_SLGID
