### ISSUE TITLE
"Property Requirements" conditional appears to bug certain Law triggers

### ISSUE THREAD

**Issue by NDKilla** [StrangeLoopGames/EcoIssues#17949]
Hello all, I have noticed this issue on my unmodded 9.0 test server, "Eco Server 0.9.0.0 beta staging-1742" running on a Windows 10 Pro desktop. This likely has been ongoing since before this specific build.

I have several laws set up to allow everyone, along with certain elected and appointed positions to ignore authorizations. For things like hunting, where the "ignored authorization because of law" popup is a semi-rare occurance, it was not too obnoxious. However I tried to make a law regarding building in government land, and every time I placed 20 tier 4 blocks at once, the popup filled my screen. 

I tried to change the law to make it only apply where the users wouldn't normally have permissions to build, and it *looks* like it worked, however I realized that I was actually placing like, "ghost blocks" and it wasn't actually taking blocks from my inventory. There was no way to continue interacting with blocks that appeared to be placed, and it wasn't until I disconnected and rejoined that all the blocks disappeared.

![image](https://user-images.githubusercontent.com/1078941/91595394-755e3900-e931-11ea-8f95-15f40471993d.png)

**Comment by NDKilla** [comment]
I've just tested this with my hunting law instead of placing blocks. Instead of just not working, I actually got disconnected from the server with an exception.

I've created a pastebin with the log of the exception when I got disconnected https://pastebin.com/y2ZuzSMu

**Comment by beastyn** [comment]
@NDKilla thank you for the report
1. I did not have ghost blocks, I just could not place anything on the property without any error.
2. Server was crashed with hunting and property checking

I will create separate issue for the  crash case, as it is high, and this one we can use for checking "ghost" blocks for the later releases.

1. Create a law like this.
![bandicam 2020-09-01 11-45-41-930](https://user-images.githubusercontent.com/27898520/91811279-b06dae80-ec48-11ea-8886-daf4bb4f0adc.jpg)
2. Expected: I should be able o place a block on this property.

Actual: nothing happens. No errors, no action detection. Just nothing. Though, I don't have ghost blocks

**Comment by NDKilla** [comment]
@beastyn I may be wrong but just to clarify the law you have above has "trigger: construct or deconstruct" which i believe only applies to things like placing tables etc.

There should be like a "dig or place block" which applies to modifying the terrain with tools or placing world blocks with a hammer.

**Comment by beastyn** [comment]
@NDKilla  Construct and Deconstruct for the building process with a hammer, and for placing objects (tables for example) we have Place or Pickup Object. But I assume it won't work for any trigger )

**Comment by SlayksWood** [comment]
Fixed in 0.9.3 staging. I remember another similar issue with ignore authorization, seems we had duplicated issue.
