### ISSUE TITLE
USER ISSUE: skidsteer unloading flip

### ISSUE THREAD

**Issue by MCvDijk** [StrangeLoopGames/EcoIssues#17950]
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
full up with dirt, dump dirt on the ground while standing still. your skidsteer should flip when it collides with the dirt. same with stockpiles

**Expected behavior:**
not to flip

**Actual behavior:**
skidsteers collides with dirt and flips

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #8206
