### ISSUE TITLE
Arrastra doesnt change craft resource values on module installation.

### ISSUE THREAD

**Issue by Sakexz** [StrangeLoopGames/EcoIssues#17953]
Im unaware if this is a bug or a feature, since the time value still changes but not the craft resources.
https://youtu.be/tBY1-2odzMo

**Comment by IcedForge** [comment]
Its intended. It also informs the player via the "Static Value tag" if you mouse over the resource input but this in general propably needs a bit of a better display somehow as a lot of people have been confused over this.

**Comment by Sakexz** [comment]
ok thank you for info! ^^
