### ISSUE TITLE
Push AuthServer to production

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#17955]
Here is the plan for updating the auth server to prod (feel free to modify or link to other issues):

Steps before push:
- [x] Migrate database (for selected_icon)- @j3fffff @denysaw

Push:
- [x] Push staging branch to master - @redwyre 

Steps after push:
- [x] Let players know that accounts.play.eco is the correct url to use (no longer accounts.stagingland.strangeloopgames.com) - @D3nnis3n

**Comment by denysaw** [comment]
So it's push both new Accounts and Auth to production, not just Auth :)

**Comment by j3fffff** [comment]
no were not pushing accounts site yet. decided to wait til 9-8

**Comment by redwyre** [comment]
Yeah, I've removed it from the list, now just db migration
