### ISSUE TITLE
USER ISSUE: wont let me play the game

### ISSUE THREAD

**Issue by jonahmastro** [StrangeLoopGames/EcoIssues#17951]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
try to log in on my account i guess

**Expected behavior:**
Let me play the FUCKING GAME I PAID 15$ FOR

**Actual behavior:**
The following error message popped up:
Eco is currently open to alpha and beta backers only.
Upgrade your account to join.

i have no mods by the way this is literally the first time i opened the game

**Comment by D3nnis3n** [comment]
Please contact support@strangeloopgames.com with your SLG ID if you bought the game and please update to 0.8.3.3 as you're using an outdated version.
