### ISSUE TITLE
Missing news button 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17958]
![image](https://user-images.githubusercontent.com/3536496/91622139-97b08080-e94a-11ea-9544-5138f509b119.png)

**Comment by johnkslg** [comment]
This was on playtest build, maybe theres no news there?

**Comment by beastyn** [comment]
They have just disappeared. I still see them in the admin board,

**Comment by gzatravkin** [comment]
No news in steam, but still in unity with SLG login.

@denysaw proabaly some problems with login service? can you check it?

**Comment by denysaw** [comment]
Problem appeared to be on a Auth side. I've set tokens logging to test it out. And right after it was requested (user is 100% online), I've re-requested `VerifyToken` method (which I'm calling in the beginning of news controller):
![image](https://user-images.githubusercontent.com/5720101/92337466-402cb600-f0aa-11ea-8a04-ab602af28aad.png)

Next real user steam token I logged and tried to verify produced:
![image](https://user-images.githubusercontent.com/5720101/92337482-58043a00-f0aa-11ea-983a-acc7d4884c04.png)

When token verification will be fixed on Auth side, News endpoint will successfully return the news 👍 ;)
Re-assigning on Simon
