### ISSUE TITLE
[Beta 9.0] No longer runs under proton, crash on title screen

### ISSUE THREAD

**Issue by cemeceme** [StrangeLoopGames/EcoIssues#17963]
The game launches and shows the initial loading screen with the tree in the bottom left. Once loaded and the title screen should come up, the game crashes.

The current build of the beta no longer runs with seemingly any version of proton. While I don't know which exact build last worked, I do know that two weeks ago the game did launch and play correctly.

Running ubuntu 20.04.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5145406/Player.log)

**Comment by mirasrael** [comment]
From logs it seems it failed to initialize Steam API. We recently updated Steam.NET to latest version.
```
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
SteamManager:Awake()
```

You can try to start game not from Steam (if you're running it from Steam), but we're not supporting Proton anyway. On release (and probably later this week) Linux version will be available.
