### ISSUE TITLE
Road Tool not working on Desert Biom Dirt Blocks

### ISSUE THREAD

**Issue by itsmepete** [StrangeLoopGames/EcoIssues#17962]
It is not possible to stamp roads with the Road Tool in the Desert on the 'Desert Sand' Block.
![grafik](https://user-images.githubusercontent.com/70199719/91639061-6d43ed80-ea46-11ea-9ee7-3f2903a54ab9.png)

If you use the Stockpile or the shovel to reset/convert the 'Desert Sand' Dirt Block to the normal 'Dirt' Block, you are able to stamp the roads.
![grafik](https://user-images.githubusercontent.com/70199719/91639086-a1b7a980-ea46-11ea-8efa-729d92e43aff.png)
![grafik](https://user-images.githubusercontent.com/70199719/91639094-ab411180-ea46-11ea-856f-fb292ae66cc7.png)

But then once the Desert regenerates, the Road will disappear again, see attached picture
![grafik](https://user-images.githubusercontent.com/70199719/91639036-3ff73f80-ea46-11ea-9e3c-4242ec2215cb.png)

**Comment by IcedForge** [comment]
Intended function.
