### ISSUE TITLE
[0.9.0.0 beta staging-1740] : Removed map districts should not be listed

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17961]
Removed districts are still selectable in the map view? Not sure if its intended but i would assume not?
![Screenshot_171](https://user-images.githubusercontent.com/24981362/91632823-bdd62f00-e9e3-11ea-9924-8d729c1e9162.jpg)

**Comment by johnkslg** [comment]
@gzatravkin note that I've completely refactored this code so something basic will do for a fix, because I will be overwritting it when I merge in my refactor for 9.1
