### ISSUE TITLE
USER ISSUE: Logging efficiency perk doesn't seem to work

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#17972]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
Level logging up to level 3.  Choose Tool Efficency: Logging perk

**Expected behavior:**
Expect calorie useage per action to be reduced from the bonuses from leveling

**Actual behavior:**
Only getting base level reduction.  For example, at level 3 logging, a stone axe will use 14 calories per action.  This number should be reduced with the efficiency perk, but getting a constant 14 calories per action after choosing the perk..

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5145995/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5145996/Player-prev.log)
![image](https://user-images.githubusercontent.com/38095046/91646187-3358f400-ea12-11ea-8399-e7161811e71a.png)
![image](https://user-images.githubusercontent.com/38095046/91646193-466bc400-ea12-11ea-8f02-f84f853510d2.png)

**Comment by SlayksWood** [comment]
dup #12378
