### ISSUE TITLE
[0.9.0.0 beta stating-1742] Currency Exchange rate stuck at zero no matter what is entered

### ISSUE THREAD

**Issue by MetallicDragon** [StrangeLoopGames/EcoIssues#17971]
When entering an exchange rate between currencies on a currency exchange, the rate is stuck at zero no matter what is entered. This affects the actual rate when using it, so that you get currency for free. 

This is on the 0.9 public test on the Giant Panda server.  We had 3 people try to set it up with the same results.

Reproduction Steps:

1. Place a currency exchange in a room with the appropriate tier level.
2. Set up an exchange between two currencies
3. Have someone else make an exchange using it

Interface screenshots when exchanging:

![20200829134854_1](https://user-images.githubusercontent.com/3228297/91645952-fd5e4480-e9fe-11ea-8e25-fd68b0dda8cd.jpg)

The resulting transaction:
![20200829134955_1](https://user-images.githubusercontent.com/3228297/91645951-fc2d1780-e9fe-11ea-96ea-b8cf0569c502.jpg)

**Comment by SlayksWood** [comment]
It reset after time with exception. Fast steps to reproduce:
- place currency excange and add some exchanges:
![image](https://user-images.githubusercontent.com/45708377/91718183-94600380-eb9b-11ea-9fd2-364d04767c62.png)
- close ui and use /toggleuicache. You should have exception( 1 exception for one exchange) and reset to 0:
![image](https://user-images.githubusercontent.com/45708377/91718275-b5c0ef80-eb9b-11ea-8dbc-adadefd4c894.png)
```
NullReferenceException: Object reference not set to an instance of an object.
  at CurrencyChoiceUI.ReleaseInstance (System.Boolean destroy) [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5150155/Player.log)

**Comment by beastyn** [comment]
Still resets, thought there is no exceptions no more

/toggleuicache

1. Add exchange with some rate (5 here)

![bandicam 2020-09-01 10-16-02-168](https://user-images.githubusercontent.com/27898520/91797503-29b2d480-ec3c-11ea-9a3d-24d08dcd8c6c.jpg)

2. Close UI, open UI - 0 for rate
![bandicam 2020-09-01 10-16-49-599](https://user-images.githubusercontent.com/27898520/91797548-45b67600-ec3c-11ea-911f-d370c5ae40ac.jpg)
