### ISSUE TITLE
[0.9.0.0 beta stating-1742] Districts not showing up in map

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#17979]
Districts created on the zoning office stop showing up in the game map after a while or not at all, and all removed or deleted proposals still show up as options in the list on the right side.

**Comment by SlayksWood** [comment]
removed districts here #17961
@RedBaron88 
Can you provide save file? Instruction is here  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
And Maybe some steps? or screenshots. I don't exactly understand what you mean.

**Comment by RedBaron88** [comment]
This was happening in our previous 9.0 cloud world too, so its not just on our new 9.0 server.

Here are some screenshots. The first screenshot is the game map, which shows the district not showing up when its selcted (as well as all the failed/removed districts that still show up as options). The second screenshot is the district on the zoning office object as it should appear for players in the map.
![GameMap-NoDistrictsShowUp](https://user-images.githubusercontent.com/69723929/91994321-18c99800-ecfc-11ea-9f20-df4887013c1a.png)
![ZoningOffice-WhatShouldShowUp](https://user-images.githubusercontent.com/69723929/91994356-2121d300-ecfc-11ea-8927-df3bd00c5308.png)

**Comment by MishkaFur** [comment]
This is also happening for myself and TaTyper on Giant Panda and also White Tiger so believe this may be an issue with build 1742 and later.

**Comment by WeaselDog** [comment]
Fixed in staging-1756
