### ISSUE TITLE
USER ISSUE: Failed to connect to new private server

### ISSUE THREAD

**Issue by smelandb** [StrangeLoopGames/EcoIssues#17976]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
1. Start new private server, random gen, 1-3 player
2. Attempt to start

**Expected behavior:**
Be in game... at all...

**Actual behavior:**
Failed to login.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Failed to login.

**Comment by SlayksWood** [comment]
@smelandb 
1. Can you provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you try to connect to official servers and provide log files too?
3. Can you see servers in list normally? With ping and server info?
4. Do you have Firewall or Antivirus enabled?
5. Which kind of internet connection are you using?
6. Please provide your PC specification (include Operating System).
7. Does server have external IP address and did server admin use it in config file?

**Comment by beastyn** [comment]
Please update and check with 9.0.1 version.
Write if issue is still here.
