### ISSUE TITLE
I'm pretty sure Friend Rice is supposed to be Fried Rice.

### ISSUE THREAD

**Issue by dopeghoti** [StrangeLoopGames/EcoIssues#17988]
![image](https://user-images.githubusercontent.com/295727/91668502-09f7a100-eac2-11ea-94de-daac04794624.png)

**Comment by D3nnis3n** [comment]
No, it's actually supposed to be like this :)

**Comment by SlayksWood** [comment]
@dopeghoti 
you can read description: "A homely recipe made from a mix of cooked rice and fruit. Not only is it friendly, but it also happens to be pan fried."
