### ISSUE TITLE
Fresh water vs salt water locations

### ISSUE THREAD

**Issue by mycide** [StrangeLoopGames/EcoIssues#17980]
I first noticed fresh water was only showing in certain stream/pond locations, and not the whole bodies of water

I left fish baskets in those spots and checked both

One had 2 fish, the other had none

I noticed that even though the basket is in the white area for fresh water, its not registering as fresh water

then I checked the fresh water map, and noticed the inconsistent behavior in the screenshot

is this normal? could this be cause by trying to run the server on my local machine? is there a specific log that would be of use for something like this? I have a hard time judging if something is part of the game, or a bug, sometimes. Is there an easy to review list of all known bugs?

![image](https://user-images.githubusercontent.com/14035118/91649456-4e832e00-ea29-11ea-8255-2401ce5bc8a9.png)

**Comment by mirasrael** [comment]
After fix:
![image](https://user-images.githubusercontent.com/475445/91734624-d39a4e80-ebb3-11ea-8ece-95a5b8dc3c0f.png)
![image](https://user-images.githubusercontent.com/475445/91734640-d9902f80-ebb3-11ea-85ef-e8d4099f8f2f.png)

**Comment by mycide** [comment]
does it take some time? my salt water looks ok, but i did an update to make sure i had the latest build, and this is my fresh water afterwards

![image](https://user-images.githubusercontent.com/14035118/91910445-e2d8d500-ec63-11ea-8998-dc48a768de03.png)

**Comment by mycide** [comment]
nevermind, looks good now with that update

**Comment by mirasrael** [comment]
It may be delayed for about 10 minutes until World Tick for old server.
