### ISSUE TITLE
USER ISSUE: Clay Blocks Turn to Dirt

### ISSUE THREAD

**Issue by Titanborn** [StrangeLoopGames/EcoIssues#17989]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
1. Be in the Mountain Biome
2. Dig a clay block
3. Cry as it turns to a dirt block

**Expected behavior:**
Clay blocks should give clay when shoveling them.

**Actual behavior:**
Instead they are turning into dirt in once they are shoveled

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Can you provide screenshots of your clay block:
![image](https://user-images.githubusercontent.com/45708377/91685017-c5234700-eb61-11ea-91ad-5f0b3a9b4ca0.png)
I can't reproduce in staging-1746:
![image](https://user-images.githubusercontent.com/45708377/91684971-a2912e00-eb61-11ea-975b-6fef3d526561.png)

I assume you can confused in our blocks. We have IceBlock a bit like clay which is dirt:
![image](https://user-images.githubusercontent.com/45708377/91685184-45e24300-eb62-11ea-8c98-289abb18d8bc.png)

**Comment by Titanborn** [comment]
We found clay in the jungle. Sorry about that.

What about sand blocks though? If they are touching water when I shovel
them they turn to dirt. If they are next to dry blocks or underwater air
blocks they come out as sand properly. Is this intended?

**Comment by SlayksWood** [comment]
This is different blocks. We have RiverSand, OceanSand and Sand. You can use only Sand like Sand
