### ISSUE TITLE
Server crash due to "authoritative server"

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#17987]
There were some issues with the hosting company network earlier today and my 0.8.3.3 Eco Server crashed and I could not restart it. The Eco 0.9 Test Server that was running along side the 0.8.3.3 Server, did not have this issue.
Here is a screen of the server crashing before launching.
![image](https://user-images.githubusercontent.com/17730996/91662962-77b9c200-eaee-11ea-8dcd-04cfb1736216.png)

Maybe if there was an option in the eco server to disable connecting to this authoritative server, the eco server would of launched.

**Comment by D3nnis3n** [comment]
As it worked without issues in 9.0, there isn't really an issue, there won't be any more patches to 8.3.X.
