### ISSUE TITLE
Lasers and Computer Lab not detecting each other

### ISSUE THREAD

**Issue by PWildgen** [StrangeLoopGames/EcoIssues#1799]
I'm having an annoying issue with my lasers and computer lab. I have 14k power but when I set all 4 lasers down with the computer lab, not all of them detect each other. Some lasers say 4/4 others 3/4 etc. I got all 4 lasers to detect each other, but the computer lab wouldn't even detect itself. I currently have all 4 set down really close to each other with the computer lab outside on the dirt. 2 of my lasers say 0/4 with 0 lab, one says 2/4, and the last one says 4/4. All 4 show power being used. The lab says 0 labs and 0 lasers. I'm sick of just burning a ton of gas and polluting for absolutely no reason. I've been waiting 6 versions to destroy the meteor and i'm going to be extremely upset if I went through all the crap you guys made us go through in 5.6 for all 4 lasers and 500 GASOLINE to power them for 10 hours. The last thing I want to do is just turn off the meteor with everything I had to go through.

**Here are some questions I'm hoping you can answer quickly:**
Do all 4 need to be pointed in different directions?
Does it matter what order they are sat down in?
Does it matter what material is underneath the lasers?
Does it matter how close they are to each other?
I know it takes 10hrs but do all 4 lasers and computer lab need to show green in the computer lab to start charging?
Even though the lasers say they take 3k power each, with all 4 down and the lab it says there is a 24k demand?
Are there any kind of animations when it destroys the meteor?
There hasn't been a server reboot after I set them down.

**I will say you guys have done an AMAZING job from v5.5 to v5.6. You're basically ready for Steam release....as soon as you fix blowing up the meteor (the main point of the game).**

**Comment by PWildgen** [comment]
_**Disregard the bug.... but PLEASE read my suggestions/recommendations, coming from a dedicated player since 5.0 that has mastered the game. I would really appreciate it!**_

**After realizing the lasers work fine (they looks AWESOME by the way) and they aren't invisible anymore, you guys are TOTALLY ready for Early-Access Steam! Please do so quickly so you guys can start making some serious money and hire more devs to create more content. I LOVE the route you're going with the Beta announcement! I seriously have to give it to your team for how insanely far you came from 5.5 to 5.6! The only issues I've found so far are some of the late-game objects don't let you pick them back up or access them after setting them down. Thank you for fixing the Industrial workbench in 5.6.1, right when I needed it. I know the others will be fixed soon in coming updates. I've only found a few bugs so far, but that's seriously saying something compared to 5.5! Nothing has been frustrating enough to rage quit, which means you're READY for Steam!!!**

**Touche' on the Excavators, they are SOOOO bad ass and work amazing!**

**The Problem** 
I guess if they all aren't detecting correctly, re-logging fixes the issue. I logged out for a few hours and they all 5 showed up as 4/4. I always picked them back up to not waste gas before logging off.

_**Here are my 4 suggestions for the laser project:**_

1) I don't understand why you haven't added Transmission Poles to a crafting bench?!? They work perfect!!! I ran around 20 power lines from my power plant to my base, and it transfers the power perfectly! I wasn't sure if they were a thing yet, but they look REALLY cool! I admin spawned them in without much hope, and was beyond happy with them! I saw a post on the forum that said I might need a generator at the other end, but they distribute power by themselves without issue. Please add them to crafting in 5.6.2! I would say they should be made in the factory and take Lumber, Circuits, and Polished Steel. That would make them not easily craftable.

 2)  I would say that you should make the required charge lower, maybe 50k each instead of 100k. It would also be nice to have some form of progress bar or something. It's insane the amount of gasoline you need to run 12 generators for 9 hours straight, without the server rebooting or you loose the whole charge. I put 9 hours worth of fuel in a generator and all 12 would take at least 500 Gasoline to run that long....that's crazy! To be honest, I only had 300 Gas stocked up when I started it not realizing what it was going to cost in gas, and didn't have the ability to craft enough with the pumpjacks in the given time. I ended up admin spawning 250 gas, 7 at a time, into my inventory. I didn't want something to go wrong in the last hour and loose all that gas. I think it should cost around 300 fuel, and whatever time frame that works out to. Also if you put down extra generators it goes faster. I still don't understand why it says there is a 24k demand on the system......

3)  I wish you had a generator that had more than 1k power. I think the Induction Generator needs to be 2500 with the extra resource costs and size. I had to have a huge room to cram 12 generators into. 

 4)  I think it should only take 10k power total to run the lasers, but only if Induction Generators were 2500 power.  Basically 4 Induction generators or 10 Electric Generators. That's reasonable for the area they take up.

**Comment by johnkslg** [comment]
Breaking aspects are fixed, lowering priority and keeping this bug for later

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#377
