### ISSUE TITLE
[0.9.0 staging-1746] Voice settings don't work properly 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#17995]
Step to reproduce:
- join to server and set Voice Volume and Microphone to "+15":
![image](https://user-images.githubusercontent.com/45708377/91690111-146f7480-eb6e-11ea-84dc-8d3fb93b5d4a.png)
- restart client and join to server. I have "+15" in UI, but it doesn't work while I will not change one of two bar. I talk and hear like I have "0"

**Comment by johnkslg** [comment]
@redwyre could pass to @ptitducanh

**Comment by redwyre** [comment]
@ptitducanh this should just either be applying the settings at load time (probably already does this), or having the voice manager get the current settings when it starts up
