### ISSUE TITLE
USER ISSUE: Passworld

### ISSUE THREAD

**Issue by Fanois911** [StrangeLoopGames/EcoIssues#17991]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
Repeat the password each time you log in.

**Expected behavior:**
Keep the password for each future connection.

**Actual behavior:**
You have to write down the password each time you log in. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #15352
