### ISSUE TITLE
USER ISSUE: pipe tooltip

### ISSUE THREAD

**Issue by xasil** [StrangeLoopGames/EcoIssues#18005]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
Can't make a valid pipe. There is no tooltip help when hover over pipe like ecopedia says.

**Expected behavior:**
valid

**Actual behavior:**
says invalid at blast furnace, pipe input from ocean

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@xasil Can your provide any additional information? maybe screenshots or video? And also don't forget to provide log files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
work fine for me:
![image](https://user-images.githubusercontent.com/45708377/91821530-3258da00-ec3f-11ea-9439-26a48423d183.png)
You need to make system like this:
![image](https://user-images.githubusercontent.com/45708377/91821604-43a1e680-ec3f-11ea-873b-dcc82827bfab.png)

**Comment by beastyn** [comment]
@xasil red arrow on the pipe is working for output.
