### ISSUE TITLE
5.6.1 crafting issue

### ISSUE THREAD

**Issue by EvilCanadian2** [StrangeLoopGames/EcoIssues#1800]
Some of the players on my server keep have the same issue, while others have not reported it. What's happening is that an item is being queued up on a table, campfire, or any production object and there is no progress. I've double checked the status is acceptable, there is fuel (if needed), and that there is the required item(s).

The information that I get is that the requested item goes into the building queue, there are 100% resources, and "Time: 0%" and does not change. I am able to resolve the issue by restarting the server but this is only a temporary fix as the issue come up again sometime later. We have not been able to figure out exactly what causes the issue and we had no problem before the patch.

**Comment by REPOSEECO** [comment]
Argree and this happen
@everyone Current version of ECO is far too much instable and I'm currently too busy on other projects to handle this. The server will be now be offline until a more stable version is released. I do hope you will understand

**Comment by REPOSEECO** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/1793

**Comment by metachronism** [comment]
this is the inventory performance problem, alpha 6 has this fixed.
