### ISSUE TITLE
[0.9.0 staging-1746] Alligators are in troubles with pathing, and animation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18000]
1) It has problems with choosing a path
https://drive.google.com/file/d/1kT3RJieCguSLzvIv0KYbIY8Lw90MkmI9/view?usp=sharing
2) It has strange moving animation with a little one-paw jumping in the flee state
https://drive.google.com/file/d/1qgJ72ZKQuAvBY3huTEEWGwqnxJbPsXx5/view?usp=sharing
3) It has his head in the ground
https://drive.google.com/file/d/1Vcc8LqOvuSHZzFUkUSVrp02NfSL8nedU/view?usp=sharing

**Comment by johnkslg** [comment]
@beastyn likely will need a push pending a pathing system rewrite, it doesnt handle long animals like this well
