### ISSUE TITLE
Eco Tree: Clicking "World" branch does nothing

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18010]
For Eco Tree, all branches and roots work except one. If you click the World branch nothing happens.

**Comment by denysaw** [comment]
There was JSON parse error, cuzz of unusual escaping (`&` was escaped with `\&`, which finally gave `\\&` after json encode) in developer status. I'm replacing that with usual `&` now (w/o escaping backslash).

**Comment by WeaselDog** [comment]
Works great now. Thank you!
