### ISSUE TITLE
Eco Tree Polish

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18018]
- [x]  Add a date and label for the work status people set, to see that it's current:
ie:
'9/1/20 work status:
Fixing UI issues'
 - [x]  Dont display updates older than a week
 - [x]  Jeff: Reapply shiny-rays from users onto the tree (the little animation)
 - [x]  Make the fades happen faster when you mouse over
 - [x] When you mouse over, make it highlight the node on the tree they are working on
 - [ ] Jeff: Can't tell the difference between 'feature complete' and 'polished' colors in the key or tree.

**Comment by denysaw** [comment]
@johnkslg 
`When you mouse over, make it highlight the node on the tree they are working on` when I mouse over developer avatar or what? 
`Add a date and label for the work status people set` on a tree (I believe there's label, just no date) or on the sidebar?

**Comment by johnkslg** [comment]
1. Yeah when you mouse over developer label
2. Show date on popup and work status in the article view

**Comment by denysaw** [comment]
@WeaselDog Removing milestone as I've added that for my part. My part is finished here so I'm removing milestone to let Jeff plan his part and put own milestone. Please, don't count this issue in your Scrum'ish CRM as undone/postponed during my sprint.

**Comment by j3fffff** [comment]
shiny dev rays on develop again (yay, i like them)

as for 'feature complete' and 'polished' colors looking similir. that's because there are not tasks listed as polished.
Someone may need to come in and officially rank all the tasks completion.
