### ISSUE TITLE
Remove unlocalizable text from all images in ecopedia

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18015]
As we prepare the game for asian release, we will need to ensure that there is NO english visible anywhere in the game, including in images.  This means a number of ecopedia images will not work, and will need to have their text removed or hidden somehow.  

Or, we can have localized images, where we create these images in each language. This would be a huge hassle though because it means a lot of new textures added to the game, and a lot of work (or a new screenshot system) to take images in every language.

A third option is to add text boxes atop the images that can then be localized normally.  

Let me know your thoughts and we can figure out an approach.  Can work with Rob to get these images up to par.

**Comment by MilenkoTunjic** [comment]
Yeah, if they need text, text boxes should be added.

**Comment by keegan-o** [comment]
I believe Rob finished this!

**Comment by WeaselDog** [comment]
We still need to implement this. I will remove Rob's assignment.

**Comment by WeaselDog** [comment]
Need to finish this as the images in develop have no text

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1955

There are a lot more pages, texts, and images on Ecopedia that don't get localized when language is set to Asian language such as Chinese.

See screenshots and video below.
![1.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/836e90a6-b5e3-40a1-b472-23cb70fea469)
![2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/9d6ccb01-ab1b-4bf6-85da-309e0e9f86bc)
![3.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/a169d5d5-d1e5-4c98-95af-8683f40cb553)
![4.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/a163b5ae-b4fe-4ce0-8610-fe849704b994)
![6.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8a4865e4-3595-48d4-8dd4-b487232d7cee)
![7.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/611cd4cb-1ae7-4ddd-9748-bbcf90157afb)
![8.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/2e915bab-4725-4971-84a9-f575cfb91aa9)
![9.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/1bc0a2c3-0eb6-4b09-93ae-252230c4ad42)

Video
https://images.zenhubusercontent.com/47210472/77cd36c4-6eb3-40c2-b10d-c33626b9bb71/asd.mp4

**Comment by gabrielgindridev** [comment]
> Tested on 0.9.3 Staging-1955
> 
> There are a lot more pages, texts, and images on Ecopedia that don't get localized when language is set to Asian language such as Chinese.
> 
> See screenshots and video below.
> ![1.jpg](https://camo.githubusercontent.com/26dd1126be9ba2c62e2d87ddd7e18b3a3b84bea4c4ffa8dd5ad93be0afd1552e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f38333665393061362d623565332d343061312d623437322d323363623730666561343639)
> ![2.jpg](https://camo.githubusercontent.com/65b109dc8f5bd5bb9188e11ffec484e796343eef566377f01674681ea056ab6a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f39643663636230312d616231622d346266362d383564612d333039653065396638366263)
> ![3.jpg](https://camo.githubusercontent.com/132b70de5a29e3a2fcc08b13307d5106a3abe2a982a9228c836f1fd2c87dc0cd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f61313639643564352d643165352d346339382d393561662d383638336634306362353533)
> ![4.jpg](https://camo.githubusercontent.com/6d56d4b976599033661deebbf8f8c787512ffeb1a5d594859455a084f2075327/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f61313633623561652d623466652d346365302d383631302d666538343937303462393934)
> ![6.jpg](https://camo.githubusercontent.com/ba42cb31743c8c9803b8672a3ed95e311880c957ae7a3400335fb0e6462091be/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f38613438363565342d333539352d343864342d386464342d623438373233326437636565)
> ![7.jpg](https://camo.githubusercontent.com/577095588511be6054c677d508c0c04a8aa36cb3a957851f40a447baad2ee2e8/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f36313163643463622d316165372d346464642d393734382d626263663930313537616662)
> ![8.jpg](https://camo.githubusercontent.com/0f93909489bc125da8ccc484f6f7dfdc2f0093db2b2176dbda0aa179027ebc75/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f32653931356261622d343732352d343937312d383461392d663537356366623931616139)
> ![9.jpg](https://camo.githubusercontent.com/17896a0d56d55fe4497c62f3422a31d7c6920ac8ae95d40d1dbd4d3d47c571c1/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f31626330613263332d306562362d346230392d393361652d323532323330633461643432)
> 
> Video
> https://images.zenhubusercontent.com/47210472/77cd36c4-6eb3-40c2-b10d-c33626b9bb71/asd.mp4

Hey, @Daniel-Magulado I don't think it is a bug.I think it is only missing the translations: 
(you can look in the defaultstrings.csv)

in the first image, for example
![image](https://user-images.githubusercontent.com/65634950/111518796-2fce5580-8735-11eb-8389-f873e0db4cd3.png)

```csharp
,"Lumberjacks",,,,,,,,,,,,,,,,,,,,,,,,
,"Propose Demographics",,,,,,,,,,,,,,,,,,,,,,,,
,"Lumberjacks would chop wood if they could.",,,,,,,,,,,,,,,,,,,,,,,,
,"Personal Currency",,,,,,,,,,,,,,,,,,,,,,,,    // no translations
,"Skill Requirements",,,,,,,,,,,,,,,,,,,,,,,,   // same
,"Required Level",,,,,,,,,,,,,,,,,,,,,,,,         // same
```

**Comment by IcedForge** [comment]
Gone over it with gibberish and it looks like its not missing anything, i am not finding any strings missing nor images with strings not having inclusion. Will make a new issue if we find specific ones.
