### ISSUE TITLE
Efficiency upgrades for petroleum refining leads to infinite barrels.

### ISSUE THREAD

**Issue by Doyan** [StrangeLoopGames/EcoIssues#1801]
If you have a high enough efficiency on petroleum refining, the amount of barrels needed for 1 petroleum is less than 1. Since you get 1 barrel back for every gasoline you make and can do so for only 1 petroleum at high efficiency the amount of barrels in your inventory can grow quite rapidly. This behaviour seems unrealistic. 

Possible solution is to remove or decrease the the barrel reduction from efficiency.

**Comment by Amphysbaenas** [comment]
i confirm

**Comment by craig-jong** [comment]
This should be fixed in the next staging
