### ISSUE TITLE
buying 2+ worlds at once bug

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18025]
If you are buying 2+ worlds at once the last of them won't start with some error.

![Inkedbandicam 2020-09-02 14-17-12-192_LI](https://user-images.githubusercontent.com/27898520/91964238-53e1c080-ed28-11ea-86fb-df4eae028856.jpg)

**Comment by SlayksWood** [comment]
Today I buy 2 worlds and it works:
![image](https://user-images.githubusercontent.com/45708377/96562514-8724e280-12c9-11eb-85fe-b9302411c8fa.png)
need to check one more time.
