### ISSUE TITLE
[0.9.0 staging-1750] Civics: if section logic update

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18026]
1. Create a law with two if conditions, like that
![bandicam 2020-09-02 15-29-43-274](https://user-images.githubusercontent.com/27898520/91970479-23eaeb00-ed31-11ea-92cd-3f74d805d148.jpg)
2. I want to make ANY for this set of conditions, but I don't see the options
3. Press Else +
4. Now I have the options, and they will stay if I remove else part.
![bandicam 2020-09-02 15-33-20-778](https://user-images.githubusercontent.com/27898520/91970953-e044b100-ed31-11ea-87dc-0fc0d9e4f3ff.jpg)

Expected: Options should appear at once when set of conditions is used

**Comment by IcedForge** [comment]
I cant reproduce this at all? possible localization related issue or perhaps fixed through another factor? @beastyn

**Comment by beastyn** [comment]
Seems to bi fixed
