### ISSUE TITLE
[0.9.0 staging-1750] Filter doesn't save my view type selection

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18023]
Step to reproduce:
- open filter. I have icon view:
![image](https://user-images.githubusercontent.com/45708377/91944011-1d934980-ed06-11ea-9fc3-32d2a43839ba.png)
- change to string view:
![image](https://user-images.githubusercontent.com/45708377/91944061-2a17a200-ed06-11ea-92d7-1c86d2a74e20.png)
- close and open filter again. I have icon view again:
![image](https://user-images.githubusercontent.com/45708377/91944106-3996eb00-ed06-11ea-8800-8fc8398a3e45.png)
Save my selection at least until cache will clear.

**Comment by serpopov** [comment]
Filter window: saves grid/list toggle state for a session, only affects modes when grid mode is default
