### ISSUE TITLE
[0.9.0 staging-1750] What should be the icon 'Citizen'?

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18021]
So:
1. It takes Trigger icon in law:
![image](https://user-images.githubusercontent.com/45708377/91942618-e6bc3400-ed03-11ea-9ba9-24b61399973a.png)
2. it takes Demographic icon in census:
![image](https://user-images.githubusercontent.com/45708377/91943014-8ed1fd00-ed04-11ea-87fe-d9a58a78d55d.png)
3. it doesn't have icon in Work Party, Government office and Registrar:
![image](https://user-images.githubusercontent.com/45708377/91943355-20da0580-ed05-11ea-91fc-c05dbf829c05.png)

![image](https://user-images.githubusercontent.com/45708377/91942888-5500f680-ed04-11ea-8741-f02f3b222f3d.png)
![image](https://user-images.githubusercontent.com/45708377/91943176-cfca1180-ed04-11ea-9c4d-3259b06ec0f2.png)

**Comment by WeaselDog** [comment]
@serpopov We have a sprite for citizen now in Unity.
