### ISSUE TITLE
[0.9.0 staging-1756] Workparty "negative" payment

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18039]
If you performed 0% in Work Party you will get '-0', should be just '0':
![image](https://user-images.githubusercontent.com/45708377/92092063-4258f100-edda-11ea-97bf-b9a4a27b4ebe.png)

**Comment by olegshegai** [comment]
Unassigned
Thanks for handling that, @tuha263
