### ISSUE TITLE
Item label: inappropriate pluralization

### ISSUE THREAD

**Issue by TheforestHermit** [StrangeLoopGames/EcoIssues#18032]
Slag is the plural of slag.  Slags is an offensive slang term that should probably be added to the profanity list.  As hilarious as some people find your crusher telling you about it.

**Comment by TheforestHermit** [comment]
Adding player logs. 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5162845/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5162846/Player-prev.log)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/12761
