### ISSUE TITLE
animals getting stuck on terrain and teleporting

### ISSUE THREAD

**Issue by kealas** [StrangeLoopGames/EcoIssues#18034]
When you spook or shoot at an animal it often does the attack or flee animation without going anywhere.  Frequently animals that do manage to flee get stuck on terrain and then experience the same problem.  Eventually if not killed first it will teleport a short distance away.  If killed the corpse will teleport the same as the animal would have.  Sometimes it is not obvious or the animal is killed fast enough they do not appear to be stuck and the player does not realize why the corpse seemed to vanish.  Other times animals will very obviously tilt into the ground, point up at the sky, or jerk back and forth before teleporting.  Some species are worse than others but it happens to all species.  Predators and deer seem to have the highest odds of failing to move at all.  Bison are one of the most consistent at getting stuck on a raised terrain block after running.

It does not matter if it is one person or multiple people around while an animal is being hunted.  The corpse does not appear where the animal was for anyone.  It can sometimes be located several blocks away but we haven't always found it.

This is not an issue of invisible corpses or a single species disappearing.

When the server has been running for several hours this happens with nearly every animal shot at and makes hunting nearly impossible.  Majority of animals you see get stuck or immediately teleport.  They may even teleport again several times within a couple seconds of reappearing before they stop.  This is a very frequent and consistent bug.  It has happened on previous worlds but seems to have gotten worse in the past week compared to our first world 3weeks ago.  It improves on restart and animals will appear mostly normal for a short time but it starts happening again within 1-2hours and rapidly gets worse.   It happens to players with good connections and high fps that are not experiencing any lag.

Our server console also increasingly fills with "failed to set tick" errors.
![tickerror](https://user-images.githubusercontent.com/49254597/92041739-6e269900-ed3e-11ea-86dc-13edddcb367e.png)

I have requested our server try to get some video clips and screenshots.
We are running a 2km world and the previous world was 1km.  We are using less than half our available server resources even when the server has not restarted recently and animal tick errors have become constant.

**Comment by kealas** [comment]
Typical hunting on our server
https://youtu.be/Us9dk0XW72M
https://youtu.be/2MGJ7SiOxAY

**Comment by beastyn** [comment]
@kealas Thanks for the report. Will take it for further investigation.
And which server was it?

**Comment by kealas** [comment]
This is on our serenity pingperfect server.  95.154.229.140:3020
I have 90-100ms but some of our members on right now are saying they have pings of 10-12ms and I know our hunter that was dealing with it the most is among those with the better connections.

I have a save from today and one from our previous game dated aug 25th.  It was less frequent on the previous world but the issues with animals still happened.  It may require the more tech savvy person here to upload those later today and answer more detail than that.

**Comment by beastyn** [comment]
Can I have a log from server from that session?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by Yorkforce** [comment]
Just to add, these animal issues also occurs on White Tiger and Giant Panda, not sure if they are producing similar console error logs but the most obvious time it occurs is when killing jaguars, they almost always teleport on death and frequently warp around.
From what I have seen the server is correctly tracking their position but the client is out of sync, when shooting an animal once on my own property for example, the second shot will state its on my neighbours property even though the animal is still on my property on my screen.

**Comment by beastyn** [comment]
Still have it in playtest (1774- after this PR)

**Comment by KhisanthMagus** [comment]
Unfortunately the server logs really don't say much of consequence.  Strangely I've noticed that even when there are Tick errors for animals in the server console they don't appear in the .log file.  This is the console log for today, which I can tell you that the animal teleporting just happened to me a few minutes ago.
[log_200910060726 (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5205112/log_200910060726.1.log)

If it is of any help at all, here is a link to the save of our world itself from a few days ago: https://drive.google.com/file/d/1Eo5AEkaTTBKAYKg1QPyAGS8fWuEFDWuP/view?usp=sharing

It may or may not be of importance that kealas and I have ~100ms ping to the server we use.

**Comment by beastyn** [comment]
@KhisanthMagus can you provide console screenshot?
And also give credits of server were is it happening?
Or maybe give as a screenshot of a place with coordinates from the Tick error? (the last one you've got).
Anything will be helpful really )

**Comment by mirasrael** [comment]
What is current status of the issue? Do we have this on latest released version (9.1.5+)? I asked @SlayksWood and he says there is no recent reports and he personally didn't experience it for awhile.

**Comment by WeaselDog** [comment]
This is issue is still actual. I have seen it on official servers recently. I am not sure how to replicate this on local.

**Comment by SlayksWood** [comment]
@mirasrael yeah, I forgot to change issue status after discussion in discord.

**Comment by mirasrael** [comment]
One part of issue was WorldTime syncing (fixed in https://github.com/StrangeLoopGames/Eco/pull/7492) which caused invalid position prediction because of desync between WorldTime on client and server. Another part of issue is packet processing delays (like we had for chunks) it may be fixed with separate queue for animal updates, but can't be a part of 9.2 because of missing support. Need to check in 9.2 if WorldTime fix improved it enough.

**Comment by mirasrael** [comment]
Another part of fix is for 9.3: https://github.com/StrangeLoopGames/Eco/pull/7497
It should reduce updates latency and teleport should happen only for very high network ping (like 1.5-2s).
