### ISSUE TITLE
Backpack closing on ESC key press

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#18045]
Pretty straight forward, when pressing the ESC key it will close the backpack first then close any UI screens on second press.

**Comment by D3nnis3n** [comment]
@gzatravkin There is people playing with backpack open all the time / around base. A way to pin it for those who do not want it affected by ESC would be good, next to a priority system when closing. The same might apply to undocked minimap that some people also like to keep around at their set position.

**Comment by gabrielgindridev** [comment]
> use dial it back. just make escape not affect backpack
From @johnkslg

**Comment by Yorkforce** [comment]
Still occurring in 0.9.0.5
