### ISSUE TITLE
Sloped Roof Blocks at Corner

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#1804]
Corners are not wrapping properly.  This happens with both Log Roof blocks and Reinforced Concrete blocks.

Here is the concrete:
![mqpwuz2rtyqwan0naoonyw](https://user-images.githubusercontent.com/30206504/28244600-645f5e42-69a3-11e7-9553-b55f84a77c89.png)

**Comment by keegan-o** [comment]
Duplicate of general roof issues
