### ISSUE TITLE
Fish basket / Fresh water issue

### ISSUE THREAD

**Issue by mycide** [StrangeLoopGames/EcoIssues#18041]
The changes made have set fresh and salt water to the appropriate places, but fish baskets are not catching fish. I notice the situation in the screenshot almost every time i place a basket, not sure if that keeps the fish from being caught, or if there is an issue with the fish on the server not recovering from the lack of fresh water previously, and i should reset to a clean world.

If you let me know how you would like me to approach it, I can troubleshoot whichever way gets you the most info
![airBubble](https://user-images.githubusercontent.com/14035118/92140357-d3719d00-edc5-11ea-88d1-d9344a3c5b7e.jpg)

**Comment by mycide** [comment]
if you need info quicker, feel free to reach out on discord: otherbarry

**Comment by SlayksWood** [comment]
@mycide 
Can you provide screen of Fresh water layer and Fish trap status?

**Comment by mycide** [comment]
yes, though the last few time i went to them, this was not occurring. ill update if/when i see it. (ill try moving them)

**Comment by mycide** [comment]
Im going to close this, i havent seen it happen again
