### ISSUE TITLE
[0.9.0 staging-1756] Users get kicked out of the server when using my hostname to connect

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#18056]
I'm currently hosting a server for Beta Public 9.0. Before the version 1756 my friends was able to play without problem but since the update they are kicked out every ~5 minutes. I realized that when they connect using the IP, they have no problem and they are not disconnected. But when using my hostname, the problem happen.

I'm using the service NoIP (https://www.noip.com). For example: coolfarmer-pc.no-ip.info:3000

Even before 1756 the problem has occurred 3-4 times for a specific user but since 1756 it happen all the time.
I don't like giving my IP to my users because if my ip change I need to give it back to all of them.

I don't know why this happen, I would like to help you to find the problem so if you want some more details don't hesitate.
Thanks!

**Comment by redwyre** [comment]
What message do users get when they are kicked? Can you also attach the server log file?

**Comment by coolfarmer** [comment]
I'm not sure if they get a message, I'll check with them tomorrow.

And here is the server log where at least 1 user had the problem:
https://gist.github.com/coolfarmer/8d99c101408976298d2038498dae7fe3

**Comment by coolfarmer** [comment]
> 
> 
> What message do users get when they are kicked? Can you also attach the server log file?

They said to me that they have no message. Instead they have a little red icon in the bottom right corner (lost connection).

**Comment by coolfarmer** [comment]
Just found this in recent server log, maybe it can help you!

```
[07:03:11] Error when verifying login token: The operation has timed out.
[07:03:11] User fillion07's login info could not be verified. Our auth servers may be down...
```

**Comment by coolfarmer** [comment]
Problem seems to be fixed in the last update.
