### ISSUE TITLE
[0.9.0 staging-1756] Developer Console Error dragging items

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#18057]
![image](https://user-images.githubusercontent.com/54982803/92302355-7f042400-ef63-11ea-92b1-a4e6c6ba80b7.png)

Open a storage item
Left click an item from inventory (I had a broken pickaxe). Keep left click held down to drag it and press ESC twice to close storage.
Item in hand icon remains on screen and then Development console pictured above came up and cannot be closed.

**Comment by beastyn** [comment]
@NN-Mike  thank you for the report. Is your log for this case still available?

**Comment by IcedForge** [comment]
Can't reproduce [0.9.1.0 beta staging-1813], closed for now and will reopen if we run into it again.
