### ISSUE TITLE
[0.9.0 staging-1757] Attempting to vote/open legislation/view data directs to wrong IP address

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#18055]
When players on my server try to open the voting/legislation/data webpage, they are now being directed to an IP address that is different from the server's IP and the page times out.

**Comment by redwyre** [comment]
What is in your network config?

**Comment by RedBaron88** [comment]
I have the IP address blank in the config which has always worked before until the latest version release. My ports are forwarded correctly on my router and server computer.

**Comment by beastyn** [comment]
@RedBaron88 Did problem still valid after update?
If yes, please provide Network config file

**Comment by RedBaron88** [comment]
Voting is working now, thank you.
