### ISSUE TITLE
[0.9.0 staging-1757] Passenger hear vehicle sound if leave vehicle after driver.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18052]
Step to reproduce:
- first player use truck as driver.
- second player use truck as passenger.
- first player leaves truck.
- second player still hear truck sound without driver(should not)
- second player leave truck. He still has truck sound:
https://drive.google.com/file/d/1esACRyHR3pomRLWiXE5vvP5qj35GoXFH/view?usp=sharing

**Comment by Quadbro** [comment]
@SlayksWood Can't her described issue on video)

**Comment by SlayksWood** [comment]
Still and issue in 0.9.2 staging-1862.
