### ISSUE TITLE
Font Bug with special characters (ä, ö, ü, ß, etc.)in the Capitol

### ISSUE THREAD

**Issue by Paul25995** [StrangeLoopGames/EcoIssues#18058]
In the Capitol is a Font-Bug. In the following is a list with the wrong Characters that I found.

! " § $ % / ( ) ß , . - + * ' # ä Ä ö Ö ü Ü ´ °

![Bug_Capitol](https://user-images.githubusercontent.com/53189877/92307618-edfb7000-ef97-11ea-97d5-3f4fbc6e1682.png)

**Comment by SlayksWood** [comment]
. ' , " too
