### ISSUE TITLE
[0.9.0 staging-1758] 'Craft' button is inactive in Subrecipes when select the same recipe second time. 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18067]
Step to reproduce:
- open any recipe with a lot of variants(Composite table):
- select composite ceiba table:
![image](https://user-images.githubusercontent.com/45708377/92324173-daa7dd80-f047-11ea-9f2f-4a10b8ab37fa.png)
- select it another time. Craft button is inactive:
![image](https://user-images.githubusercontent.com/45708377/92324183-f4492500-f047-11ea-81b0-168cf0a30ad2.png)

**Comment by IcedForge** [comment]
Switching states "Show All" on / off disables the ability to craft causing the same issue
