### ISSUE TITLE
[0.9.0 staging-1758] Migration is broken

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18066]
Can't launch saves after the last PRs.
https://github.com/StrangeLoopGames/Eco/pull/6601
even simple servers.
And playtest too. Like this save.
https://drive.google.com/file/d/1MIN2Fklrey5g3DBe4q2TCDk2V2t09cOL/view?usp=sharing
errors like this
[log_200906030533.log](https://github.com/StrangeLoopGames/EcoIssues/files/5179412/log_200906030533.log)
[log_200906030228.log](https://github.com/StrangeLoopGames/EcoIssues/files/5179413/log_200906030228.log)
[log_200906025545.log](https://github.com/StrangeLoopGames/EcoIssues/files/5179415/log_200906025545.log)

**Comment by SlayksWood** [comment]
Almost fresh world with some testusers, some craft station, non-ratify constitution and real estate desk.
[log_200906021117.log](https://github.com/StrangeLoopGames/EcoIssues/files/5179536/log_200906021117.log)
