### ISSUE TITLE
Server related issues

### ISSUE THREAD

**Issue by Kenterfie** [StrangeLoopGames/EcoIssues#1806]
We have noticed some annoying bugs/issues.

Version: 0.5.6.1 alpha

1. Makes no sense to give user the ability to change gameserver/webservice port, but force port 2999 to bind on 0.0.0.0 without chance to change.
_Recommentation_
Make it also configurable and bind it also to the specified ip/port.

2. Server tries to add "netsh http urlacl" rule on startup. The rule use also not the defined static ip, so only one process can use.
_Recommentation_
Change the netsh call by static IP, if no "AnyIP" configured and add an option to disable it completely.
+:3001 -> [IP]:3001

**Comment by metachronism** [comment]
1) is intended, as this is for UDP broadcast on a known port to detect other servers.  client needs to assume this is a fixed port for it to work.  This has essentially no effect for most servers since you are probably connecting to them outside the LAN

2) I will make this modification
