### ISSUE TITLE
[9.0 staging-1756] Cement Kiln wrongly refers to Advanced Masonry and has typo

### ISSUE THREAD

**Issue by Kenionatus** [StrangeLoopGames/EcoIssues#18062]
Cement Kiln description contains "produces AdvancedMasonry and concrete products."
All recipes use normal Masonry labor. There also is no space between "Advanced" and "Masonry".
![grafik](https://user-images.githubusercontent.com/54814353/92315545-64738e80-efe7-11ea-91b3-2c7bffb84ace.png)
![grafik](https://user-images.githubusercontent.com/54814353/92315571-ae5c7480-efe7-11ea-9ddc-c0bc5ccf46de.png)

**Comment by SlayksWood** [comment]
I guess this is another autocorrect 'Cement' to 'AdvancedMasonry', so it should be 'produces cement and concrete products.'
