### ISSUE TITLE
Stuck in tent on first campsite deployment

### ISSUE THREAD

**Issue by boinkbusky** [StrangeLoopGames/EcoIssues#18069]
I was kind of in the tent outline during my first campsite deployment was stuck in the left front corner area on the candle side I couldn't jump crouch or get unstuck left the game and came back still stuck but couldn't see my character left again and came back and it finally pushed me out onto the land I'm only reporting this because it seemed like something only a very few people might expire cell 

THANKS BoinkBusky

**Comment by SlayksWood** [comment]
@boinkbusky 
Can you provide some information:
1. Game version.
2. Several Scrensots or Video.
3. Log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information. We have some improvement in 0.9.0 for tent stucking and for /unstuck
