### ISSUE TITLE
[9.0 staging-1756] Modern Stove air pollution location

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#18064]
When using the modern Stove, the air pollution is at the location of the stove and not at the location of the chimney pipe outlet.
![stovepollution](https://user-images.githubusercontent.com/69723929/92315990-9b2fb180-efb3-11ea-8fae-5789ef9629e3.png)

**Comment by SlayksWood** [comment]
dup #17316
