### ISSUE TITLE
Alpha 5.6.1 - Power supply under power demand still makes work the factory

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#1807]
The green dot in the top left corner of the window show that the factory is working but the power demand is higher that the power supply:
![image](https://user-images.githubusercontent.com/7052045/28298162-bda69842-6b3f-11e7-9940-0c02ff1915c1.png)

**Comment by craig-jong** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1788
