### ISSUE TITLE
Arrow NullReference exception

### ISSUE THREAD

**Issue by RaptorX23YT** [StrangeLoopGames/EcoIssues#18075]
Version 9.0 Public Beta

What should happen: Arrow is shot into log or piece of rock, object is removed, arrow is also removed, and any references to it are killed.

What actually happens:
Arrow is shot into an object that is then removed. this triggers a NullReference exception, referencing an object which has no instance, which is called every tick, causing an increased load on the server.
![20200906143131_1](https://user-images.githubusercontent.com/69419464/92376921-5437de00-f0d1-11ea-86e4-35eb39f8d0ca.jpg)

**Comment by SlayksWood** [comment]
@RaptorX23YT Can your proveide log files?Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by RaptorX23YT** [comment]
@SlayksWood Yep, here you go.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5183096/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5183097/Player-prev.log)
