### ISSUE TITLE
Crash dump 2017-07-19-211020

### ISSUE THREAD

**Issue by Pharaoh2** [StrangeLoopGames/EcoIssues#1808]
Hello 
normally started game, chosed "RG Commynity discord..." and logged in. loaded 100% - crash happened right when it should show the game.

[2017-07-19_211020.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1160083/2017-07-19_211020.zip)

Thx

**Comment by metachronism** [comment]
closing for now, unity 2017 hopefully has addressed these
