### ISSUE TITLE
Crafting table are stucking in loops while having no material

### ISSUE THREAD

**Issue by itsmepete** [StrangeLoopGames/EcoIssues#18080]
Since staging 1774 some of my machines stuck in loops. I know that they do not have the required crafting materials. But why the machine keeps starting, stopping, and spamming that message in my chat? It makes me unable to read the chat.

If I feed them with the material they eventually fall back in that loop once the material is fully used and the work order was not completed.

Okay. It seems the draft of a working party caused that, but I am not sure. Anyway, I think it should not spam the chat. 

https://drive.google.com/file/d/1MLYi9kjhsgitB0WgKLSfkSu20Qdk0Wri/view

**Comment by beastyn** [comment]
@itsmepete Thank you for the report. Please provide log files. Instruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Also would be nice to see Status and Power tabs for this table.

**Comment by itsmepete** [comment]
@beastyn 

I have been offline in the meanwhile. Right now the problem does not exist on the machine. Anyway, I will provide Screenshots and the Log file.
Hopefully, the log file was not overwritten in the meanwhile. Probably it is in the log.copy.txt from yesterday.

![grafik](https://user-images.githubusercontent.com/70199719/92492657-2e701d80-f226-11ea-943d-fda853c0317f.png)
![grafik](https://user-images.githubusercontent.com/70199719/92492673-35972b80-f226-11ea-8b17-274d77926da7.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5189058/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5189059/Player.log.copy.txt)

**Comment by itsmepete** [comment]
@beastyn 
Power issues seem to cause it. I faced it again. 
I have some machines running with mechanical power. In my case there are 3 machines. 2 of them can run the same time.

If now one of the machines has enough crafting materials and keeps running and the other two both do not have enough materials but an active queue. They will rotate/turn over the needed power.

It goes like e.g.:
600W in total.
Machine I: keeps working with 200W
Machine II: Needs 400W, starting the work order, realizes 'missing material', pauses.
Machine III: Needs 200W, stops the machine II because Machine II does not have enough power supply, starting the work order in machine II, realizes 'missing material', pauses.
Machine II: Gets the 400W again, forced machine II to stop, missing material, go on
They stealing the power from each other **without** having the material at all.

I hope my explanation is clear. So it may be my mistake. But I am not sure if that never-ending loop is intended.

I'll add a video to make it more clear.


https://drive.google.com/file/d/1PJUdSFDH7akhip5c-Sb5L4aNh6hyeURP/view?usp=sharing

**Comment by beastyn** [comment]
@itsmepete Thank you for such detailed report .
Its not actually break anything, its how it works for now.
They just try to consume any power they have around regardless work orders.
So, in general you need to have power enough to launch all of them.
Some of the tables have on/off component, so you can switch them off.
We will think about possible improvement for this.



I will leave this issue for further improvement.
So, we should
