### ISSUE TITLE
Arrastra doesnt count the reduce cost when you put in an upgrade module

### ISSUE THREAD

**Issue by DieKattie** [StrangeLoopGames/EcoIssues#18098]
Hi Guys. Maybe i might be wrong but i think i have discovered a bug. The Arrastra doesnt count the reduce cost of ressources right now. I put a basic upgrade 4 (45% reduce) in it so normally it should just take 6,6 iron ore to produce 2 crushed iron ore.
thats not the case. the arrastra still takes 12 iron ore to produce 2 crushed iron ore.

i did the same with the carpentry table. there it counts right.
if you have the work order set up you can see that on the tooltip when you mouse over the order.

![grafik](https://user-images.githubusercontent.com/70978303/92523548-d5ea5180-f220-11ea-9db1-151d1975d257.png)
and here is the carpentry table. 
![grafik](https://user-images.githubusercontent.com/70978303/92523597-edc1d580-f220-11ea-8d85-dc6711d38240.png)

**Comment by IcedForge** [comment]
Duplicate and not an issue, indended functions as you can tell by the yellow outline of the resource cost, if you mouse over it is a "Static" value and there for not having a reduction on resources only processing time.

**Comment by SlayksWood** [comment]
@DieKattie Thank you for the report. This is intended behavior as @IcedForge said. You can also read ECOpedia:
![image](https://user-images.githubusercontent.com/45708377/92559004-6acc6980-f278-11ea-8d8b-4dfc4552e6d2.png)
