### ISSUE TITLE
Error when starting Server with 9.0

### ISSUE THREAD

**Issue by Paul25995** [StrangeLoopGames/EcoIssues#18092]
Hey guys,
I really need your help!
The server on 9.0 won't start anymore... Was running normal yesterday. Even after reinstall its still dead... The CLI shows an immense amount of red errors after "Loading Mods" (I dont have any mods installed).

Does anyone has a solution?

Only affects 9.0. Even clean reinstall with default config and no storage produces this failure.

![unknown](https://user-images.githubusercontent.com/53189877/92497598-d3c0cc80-f1f9-11ea-8194-03ac2a3eb674.png)

**Comment by redwyre** [comment]
What branch on steam are you using?

**Comment by Paul25995** [comment]
We are using the 9.0 Test

**Comment by Paul25995** [comment]
On the PC of my friend it still runs and mine crashed today. So I want to try letting steam reinstall the Visual C++ Redistributables, which version does Eco Server use?

**Comment by mirasrael** [comment]
It may be a virus or a anti-virus.

**Comment by beastyn** [comment]
@Paul25995  any updates? Did you verify files?

**Comment by redwyre** [comment]
Can you try again with released version?
Also is this from steam? On PC?

**Comment by SlayksWood** [comment]
Closed for now. Reopen please if you still have this issue.
