### ISSUE TITLE
9.0 1774 server eco.templates are not complete

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18095]
Civics.eco.template does not include the section about basic election settings, other template files may be the same.

Had to "save" the the config via GUI to get the file to update.

Below is missing from template, other templates might also have missing files

"  "BasicElectionSettings": {
    "MaximumElectionHours": 24.0,
    "MinimumElectionHours": 2.0,
    "MinimumPercentOfEligibleVotersRequired": 25.0,
    "EndElectionEarlyWhenThisPercentHaveVoted": 95.0,
    "MinimumDaysBetweenElectionsOfThisType": 0.0,
    "MajorityRequiredForInstantWin": 90.0,
    "AnonymousVoting": false
  }
}"

**Comment by WeaselDog** [comment]
Thank you for reporting this.
It is actually already fixed, just not in latest playtest build.
