### ISSUE TITLE
Auth servers may be down?

### ISSUE THREAD

**Issue by jeliasson** [StrangeLoopGames/EcoIssues#18091]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Try to login to a server

**Expected behavior:**
Being logged into a server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (502) Bad Gateway.</size>
```

![image](https://user-images.githubusercontent.com/865493/92492063-3b274e00-f1f3-11ea-8fd5-283bb50d3857.png)

**Do you have mods installed? Does issue happen when no mods are installed?:**
No, no mods.

**Comment by jeliasson** [comment]
Issue has been self-resolved. 

Anyone can clarify if the Auth server is with StrangeLoopGames or with Steam? Thanks!

**Comment by mirasrael** [comment]
Hi @jeliasson Thanks for report. We restarted auth server for update in preparation for 9.0 release. Sorry for inconveniences.

**Comment by jeliasson** [comment]
@mirasrael No worries, and thanks for getting back to me. 

Out of interest, do you have any insight in how fast we can expect to get the update to the docker container [zokradonh/ecogameserver](https://github.com/zokradonh/ecogameserver) once 9.0 is released?

Thanks again!

**Comment by mirasrael** [comment]
@jeliasson
https://hub.docker.com/repository/docker/strangeloopgames/eco-game-server there is official Docker container (and it is already has RC for 9.0 ;))

**Comment by jeliasson** [comment]
@mirasrael Any documentation for the docker image? 

From what I can see in the Dockerfile, it is pretty much the following volume mounts. 
- `/app/Storage`
- `/Config` 
- `/Mods`

Is this correct? If so, I think I safely can migrate to `strangeloopgames/eco-game-server` once the `latest` tag is built with 9.0 😀

**Comment by mirasrael** [comment]
Yes, it is correct

**Comment by jeliasson** [comment]
@mirasrael Thanks again!
