### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by RowanJones** [StrangeLoopGames/EcoIssues#1809]
Hi Folks,

I'm not really techno-savvy, but I'm doing my duty to report my crash dumps! :) <3

I've noticed that my game has stopped loading the world, which is why I came here today.

Cheers,

-RJ

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160498/output_log.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160499/output_log.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160500/output_log.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160501/output_log.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160502/output_log.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1160503/output_log.txt)

**Comment by metachronism** [comment]
closing as hopefully new unity 2017 has address these...
