### ISSUE TITLE
[Server] 0.9.0.0 beta Server Console buffering error

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#18108]
When starting up the newly released 0.9.0.0 beta server it logged https://starb.in/ePizgw.yaml to the console just before it started the PerformancePlugin. Server continued to load up fine (as far as I can tell).

**Comment by redwyre** [comment]
@Lagicrus it looks like the paste has expired, do you happen to have the original log? (I remember what the issue was, but it would be good for reference)

**Comment by Lagicrus** [comment]
> @Lagicrus it looks like the paste has expired, do you happen to have the original log? (I remember what the issue was, but it would be good for reference)

Sorry no :/ didn't think I needed it for this long so I didn't, my bad
