### ISSUE TITLE
0.9.0 USER ISSUE: Cant move or repair tool

### ISSUE THREAD

**Issue by LarsFalgren** [StrangeLoopGames/EcoIssues#18109]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
Work, Break tool (First Stone Axe you get), can't move or repair the axe now.

**Expected behaviour:**
Be able to move and repair it or even move it out of my hotbar.

**Actual behaviour:**
Stuck, can still equip it just not use, move or repair it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LarsFalgren** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5194970/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5194971/Player-prev.log)

**Comment by beastyn** [comment]
@LarsFalgren thank you for the report. Will fix it here #18107

As workaorund: 
- place a not broken tool into a tool bench
- crag and drop this tool from tool bench to a broken tool on you toolbar. It will switch them.

Sorry for the troubles. Will fix it ASAP.
