### ISSUE TITLE
Fix UI for all buttons

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18100]
- Go through the various prefabs one by one, and change the buttons to use prefabs.
- Make a folder of the different types of buttons that are used in the game.  Merge similar buttons.  Use prefab variants for close button cousins.  
- Make sure each of the prefab buttons have different colors for hover and click, they make a sound when used, and they change the cursor to the hand.
- Make dropdowns do this too.

Do only a few prefabs at a time to avoid merge conflicts.

**Comment by beastyn** [comment]
Part1 - to test
Dialogs (tutorial close, graphs open browser, bug report with exception)
Contracts
Treasury Tax-allocate
Avatar Creation
Backpack avatar edit
Tutorial(intros)
Giving reputation
Server creations and browsing
Objectives
Crafting-variants
Deed editing
Wake up

**Comment by beastyn** [comment]
Economy viewer bottom buttons
Repair
Civics (general windows, propose cards, proposing)
Esc menu (logins button, reset buttons)
Sever browsing (join, settings)
Report a bug
Transfer window
Work party - delete, post
Minimap
Craft (work, collect,order)
Real Estate desk (all buttons)
Skills-learning buttons
Registrar(advanced)
Bank(advanced)
Recipe order button

**Comment by TwixterZ** [comment]
Part1 - Test results : 
- [ ] Dialogs (tutorial close, graphs open browser, bug report with exception) 
- [ ] Contracts
- [ ] Treasury Tax-allocate
- [ ] Avatar Creation
- [ ] Backpack avatar edit
- [ ] Tutorial(intros)
- [ ] Giving reputation
- [ ] Server creations and browsing
- [ ] Objectives
- [ ] Crafting-variants
- [ ] Deed editing
- [ ] Wake up

**Comment by TwixterZ** [comment]
Part 2 - Test results :

- [ ] Economy viewer bottom buttons
- [ ] Repair
- [ ] Civics (general windows, propose cards, proposing)
- [ ] Esc menu (logins button, reset buttons)
- [ ] Sever browsing (join, settings)
- [ ] Report a bug
- [ ] Transfer window
- [ ] Work party - delete, post
- [ ] Minimap
- [ ] Craft (work, collect,order)
- [ ] Real Estate desk (all buttons)
- [ ] Skills-learning buttons
- [ ] Registrar(advanced)
- [ ] Bank(advanced)
- [ ] Recipe order button

**Comment by TwixterZ** [comment]
- [x] Economy viewer bottom buttons

- [x] Repair

- [x] Report a bug

- [x] Transfer window 

- [x] Skills-learning buttons

- [x] Bank(advanced)

Feedback : 
 "+" & "-" button does not have a highlighted state when mouse over them. 
"+" button mouse over highlight are too subtle 
The corner "x" button not center

Feedback part will be created as a new issue as discussed with Anna
