### ISSUE TITLE
USER ISSUE: Can't move broken tool in inventory

### ISSUE THREAD

**Issue by WalkmanNik** [StrangeLoopGames/EcoIssues#18114]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
1. To broke tool (machete in my case)
2. Try to move it from hotbar in any other slot in hb or inventory

**Expected behavior:**
It should be moved to any slot in hotbar

**Actual behavior:**
It's just takes place in inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, i'm playing on official server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hotfixed.
