### ISSUE TITLE
USER ISSUE: cant move my broken pickaxe

### ISSUE THREAD

**Issue by Marcvader3** [StrangeLoopGames/EcoIssues#18117]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
my pickaxe broke

**Expected behavior:**
I should be able to move it in my inventory

**Actual behavior:**
Now i cant use this slot anymore

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Equitime77** [comment]
I was just about to write the exact same issue.

**Comment by D3nnis3n** [comment]
Hotfixed.
