### ISSUE TITLE
Error when connect to a new server

### ISSUE THREAD

**Issue by Kingkopop** [StrangeLoopGames/EcoIssues#18118]
![image](https://user-images.githubusercontent.com/17802048/92616017-0633fd80-f2be-11ea-98c7-a9174eb24dfc.png)
I trying to join the server for the first time and that is the error.
Some guys have an idea ?

**Comment by Kingkopop** [comment]
we have found something, whenwe reboot server we can join the serv since few minutes but one other try to join 30 min later and same error

**Comment by beastyn** [comment]
@Kingkopop Thank you for the report.
What server are you trying to connect?
Do you use mods on this server?
Are you in the process of tutorial finishing or is it finished when you are trying to connect?
Please, provide a log file after you try to connect and have this error.
Instruction is here 
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by rodseb** [comment]
Hello,
I am the owner of a server, I have several players who have problems with their first connection
v9.0.1
[Bug.txt](https://pastebin.com/8c6Vf4Ae)
mods installed:
[discord](https://forum.play.eco/filebase/file/192-discordlink/)

**Comment by beastyn** [comment]
@rodseb Thank you for the information. Can you provide your .eco + .db file if you don't mind?

**Comment by rodseb** [comment]
Hello
the waiter was in French.
it is hosted at verygames.

since I took it in English, I have currency problems.

**Comment by Nidhogg62** [comment]
I'm the owner of the eco server where kingopop plays, our server is french and hosted at very games, with a linux operating system.

**Comment by beastyn** [comment]
Soorry, I've forgotten to add merging link. We are here #18132

**Comment by beastyn** [comment]
@Nidhogg62 it would be nice to hear if problem was solved for you, thank you!
