### ISSUE TITLE
[Client] Update 9 - CTD on boot

### ISSUE THREAD

**Issue by BiddinWar** [StrangeLoopGames/EcoIssues#18110]
https://youtu.be/SSHt9Ua3PLE

TL;DR; Since Update 9 my ECO game now crashes on boot, has my GPU rev up like mad, video showing all of it since I really don't know what to say. Uninstalled any AV as well, apart from Windows Defender to see if that would help, nöpe. 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5195002/Player.log)

**Comment by mirasrael** [comment]
Seems like same problem as here (for another game) https://forums.kleientertainment.com/forums/topic/109463-game-crashed-when-start-a-new-game/
Can you try to update/downgrade GPU driver?

**Comment by BiddinWar** [comment]
> 
> 
> Seems like same problem as here (for another game) https://forums.kleientertainment.com/forums/topic/109463-game-crashed-when-start-a-new-game/
> 
> ```
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed. 
> ```
> 
> Can you try to update/downgrade GPU driver?

Doesn't do squat sadly

**Comment by redwyre** [comment]
when at the title screen can you hit escape and reduce all the graphics settings and see if it still crashes?

**Comment by BiddinWar** [comment]
> 
> 
> when at the title screen can you hit escape and reduce all the graphics settings and see if it still crashes?

No, I'm unable to do any of that since it crashes before I get the chance to interract

**Comment by BiddinWar** [comment]
I've uninstalled the Game, the VC Redistr. 2015, 2017, 2019 and then reinstalled the VC redistr. then the game and it now lets me launch into the menu consistently.

**Comment by redwyre** [comment]
So is the issue solved for you now? Or are you still getting crashes?

**Comment by BiddinWar** [comment]
> 
> 
> So is the issue solved for you now? Or are you still getting crashes?

So far I've not experienced any more crashing after doing the reinstall of VC redistr.

**Comment by beastyn** [comment]
Then will close it. Write if you have issues again, thanks.
