### ISSUE TITLE
USER ISSUE: Can't repair broken stone pick

### ISSUE THREAD

**Issue by zigon15** [StrangeLoopGames/EcoIssues#18116]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
1. Break stone pick
2. Can't drag into tool bench (Well can't even drag it anywhere)

**Expected behavior:**
Should be able to drag the broken pick around

**Actual behavior:**
Can't drag pic at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hotfixed
