### ISSUE TITLE
Can’t start older version prior V8.0

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#18111]
Yesterday I played with V7.8.9 and it worked but today it doesn’t; the process stuck with screen “Logging in...”

**Comment by mirasrael** [comment]
@denysaw did you remove auth endpoints on new accounts site? They used by old versions of the game (before 8).

**Comment by Nicolausi113** [comment]
Sorry, I don’t know about “auth endpoints” and where to remove it?

**Comment by redwyre** [comment]
@Nicolausi113 He's talking to another one of our developers ;)

@mirasrael @denysaw I believe @j3fffff was doing stuff with redirects

**Comment by denysaw** [comment]
@mirasrael No, I didn't maybe just from routes. Can you tell me proper url, which is not working?

**Comment by Nicolausi113** [comment]
Someone fixed the problem – it’s working again!

**Comment by denysaw** [comment]
It was me actually :D
