### ISSUE TITLE
"Log cannot be sliced any smaller" on full trees

### ISSUE THREAD

**Issue by kapawlak** [StrangeLoopGames/EcoIssues#18122]
![fell](https://user-images.githubusercontent.com/29474019/92624860-d6183a80-f27c-11ea-8c8a-7d16bd10585c.png)
I get the "Log cannot be sliced any smaller" message on full trees after felling them. Reconnecting to server makes the tree vanish. 

After getting the message the first time, I now continually get it --- I can't cut down *any* logs. Tree logging worked fine prior to first incident.

9.0.1 White Tiger

**Comment by beastyn** [comment]
@kapawlak Thank you for the report. Please provide a log file.
Instruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Did you have this issue after client restart?

**Comment by kapawlak** [comment]
Got it to happen again and quit immediately. Logs attached.

I have to fully quit out of Eco + steam or change betas to get the effect to go away. Simply disconnecting or sometimes even quitting out of Eco.exe doesn't fix it. 

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211421/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211423/Player.log)

**Comment by JohnPatrickPrestron** [comment]
Same problem here

**Comment by beastyn** [comment]
@kapawlak Thank you for the additional info. Did you do something specific before cutting the trees?

**Comment by mirasrael** [comment]
@kapawlak did you have this issue only with specific kind of trees (like Palm) or with any kind of trees?

**Comment by mirasrael** [comment]
From error log it seems like an issue with collider mesh which doesn't have read/write flag enabled:
```
CollisionMeshData couldn't be created because the mesh has been marked as non-accessible. Mesh asset path "" Mesh name "Turbo Slicer mesh"
UnityEngine.Object:Instantiate(Object)
NobleMuffins.TurboSlicer.TurboSlicer:ConsumeJobYield(JobSpecification, JobYield)
NobleMuffins.TurboSlicer.TurboSlicer:Update()

[ line 57] 
(Filename:  Line: 57)

CollisionMeshData couldn't be created because the mesh has been marked as non-accessible. Mesh asset path "" Mesh name "Turbo Slicer mesh"
UnityEngine.Object:Instantiate(Object)
NobleMuffins.TurboSlicer.TurboSlicer:ConsumeJobYield(JobSpecification, JobYield)
NobleMuffins.TurboSlicer.TurboSlicer:Update()
```

**Comment by SlayksWood** [comment]
closed as not reproducible in staging-1806.
