### ISSUE TITLE
USER ISSUE: Cant fix tools

### ISSUE THREAD

**Issue by cyrus1087** [StrangeLoopGames/EcoIssues#18123]
\
**Version:** 0.9.0.0 beta

**Steps to Reproduce:**
Break a tool in hotbar

**Expected behavior:**
should be able to pull broken tool from hotbar and place in storage or repair table

**Actual behavior:**
cannot move broken tool from hotbar or place in repair table

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5196926/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5196930/Player-prev.log)

**Comment by MishkaFur** [comment]
This is resolved in 9.0.1
