### ISSUE TITLE
Uninteractable blocks

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#1812]
if that is even a word... Anyways.

These blocks i picked up but are still visible. Reloging in will fix the issue but i wanted to bring this up to you if haven't already. It's happened a couple times with stockpiles close by.
[![Screenshot from Gyazo](https://gyazo.com/a26f593e1c1eef69df44c9d43ac4a821/raw)](https://gyazo.com/a26f593e1c1eef69df44c9d43ac4a821)

**Comment by metachronism** [comment]
chunk building issue, should be resolved now (or changed enough to where this isnt relevant)
