### ISSUE TITLE
USER ISSUE: Main menu not showing up

### ISSUE THREAD

**Issue by Le-Sten** [StrangeLoopGames/EcoIssues#18129]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Turn on the game after update 9 (09/09/2020).
2. Close the game.
3. Turn it back on.
4. Wait for loading then no menu, only the options by pressing the escape key is working.
5. Everytime I start the game, no main menu is showing up.

**Expected behavior:**
It should have shown the main menu.

**Actual behavior:**
Instead it is just showing the scenery of the city with the ECO logo on the top right corner and no menu whatsoever. It is then impossible to play.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed, this issue happens when no mods are installed and for every other startup.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5197397/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5197398/Player-prev.log)

**Comment by beastyn** [comment]
@Le-Sten Thank you for the report.
Did you disconnect from server or restart a client?

**Comment by Le-Sten** [comment]
Well im not exactly sure of what you mean but I didn't do anything crazy, I
turned on the game, clicked on "new game", then "new world", then I
selected one server in the list, played for a few minutes, logged off,
exited the game, did some stuff in the meantime, went back to it after,
turned ECO back on, arrived where the main menu should have been, but after
10-20 minutes nothing appeared. Only the options were accessible by
pressing "esc".

**Comment by Le-Sten** [comment]
Re-installing the game solved the issue but now it erased my saved games. I
am a little bit upset by all of this to be completely honest, I paid you
for a working game...

Le jeu. 10 sept. 2020 à 09:05, Rémi Poujoulat <poujoulat.remi@gmail.com> a
écrit :

> Well im not exactly sure of what you mean but I didn't do anything crazy,
> I turned on the game, clicked on "new game", then "new world", then I
> selected one server in the list, played for a few minutes, logged off,
> exited the game, did some stuff in the meantime, went back to it after,
> turned ECO back on, arrived where the main menu should have been, but after
> 10-20 minutes nothing appeared. Only the options were accessible by
> pressing "esc".
>

**Comment by beastyn** [comment]
@Le-Sten sorry to hear that you had this issue. Game is still under development, it's beta and some issues can appear.
You have Storage folder where all your save are stored.
```
For a server run through steam UI:

Right click on "Eco" and select "Properties". Go to the "Local files" tab, and click "Browse local files..."

    Open the Storage folder
```

Actually uninstalling game from Steam should not delete this folder. How did you uninstall it?

**Comment by Le-Sten** [comment]
That the game is still under development is not an excuse. There used to be a time when games were first sold FINISHED... Not my fault if you are lazy. Good day Anna, or Beastyn, don't really know who you really are lol...

**Comment by beastyn** [comment]
@Le-Sten I did not mean an offense, And It's not an excuse, just the way it is for the game under development )
And you did not answer the question. Reinstalling the game though Steam should not delete your save files. And If you are deleting game manually, backup this folder \Eco_Data\Server\Storage as it contains you worlds. Hope you still can enjoy the game.
