### ISSUE TITLE
Login to Hosted World failed

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#18124]
V9.0.1 & 9.0.0
A world was generates but can’t be accessed.
(C++ Redistributable 2019 is installed)

[log_200909065532.log](https://github.com/StrangeLoopGames/EcoIssues/files/5196922/log_200909065532.log)

**Comment by mirasrael** [comment]
@Nicolausi113 you can try this tool: https://github.com/lucasg/Dependencies (or alternative) to check which dependencies enet.dll is missing.
You can find enet.dll by path like this: C:\Users\Username\AppData\Local\Temp\.net\EcoServer\zdi24l33.2nd\enet.dll (last dir may be any combination of letters and numbers).

**Comment by Nicolausi113** [comment]
@mirasrael 
I found enet.dll in pointed folder and applied it to the tool; it shows one marked file: WS2_32.dll
![Unbenannt](https://user-images.githubusercontent.com/38510829/92639457-1ce94d00-f2dc-11ea-818a-aaa24f10a621.PNG)

**Comment by mirasrael** [comment]
It is winsockets 2 .dll. Can't imagine how it may missing :\

**Comment by mirasrael** [comment]
Only Windows 10 is officially supported, but you can fix this by downloading WS2_32.dll from resource you trust (or ask someone with Windows 10 - probably it will also work) and put it in system32. It should work I guess.

**Comment by Nicolausi113** [comment]
@mirasrael thanks!
My system is Windos10 and the questionable dll is contained in System32 and sysWOW64.
Maybe we wait for another user run in this problem?
Meanwhile I can start the game with a world generated on the separate webserver.

**Comment by Nicolausi113** [comment]
Finally I got it running by installing C++ Redistributables once again for X64 and X86 as well!
