### ISSUE TITLE
USER ISSUE: Local Server Crashed

### ISSUE THREAD

**Issue by BlackiChu** [StrangeLoopGames/EcoIssues#18126]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5197010/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5197012/Player-prev.log)

\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Try to start a Local Server.
2. After initilising the WebPlugin the Server Crashed.

**Expected behavior:**
It should have started my new world or any other world i already have.

**Actual behavior:**
Instead it keeps crashing over and over again everytime the Webplugin is trying to initilise.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have any mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@BlackiChu Thank you for the report. Can you provide server log file too?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by BlackiChu** [comment]
[log_200909072444.log](https://github.com/StrangeLoopGames/EcoIssues/files/5204126/log_200909072444.log)
Hello,
this is the Server Log from my last attempt.

**Comment by beastyn** [comment]
@BlackiChu Hmmm, Do you have something in Server/Dump folder? If you have. can you provide log from there?

**Comment by BlackiChu** [comment]
@beastyn yeah there're some ecodmp files i zipped it and attachted them here 
[ServerCrash InvalidOperationException 09092339.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5209149/ServerCrash.InvalidOperationException.09092339.zip)

**Comment by SlayksWood** [comment]
@BlackiChu 
You have an exception that shows that you are starting the server 2 times, or on a port that is already busy.
Can you check that 3000/3001 port is not used? or try to change Game and Web ServerPort to another. You can make it in Network.eco.

**Comment by mirasrael** [comment]
@BlackiChu which OS are you running?

**Comment by BlackiChu** [comment]
@SlayksWood Hi thanks for the reply. I looked into what you suggestet and noticed that there were 2 rules set in my firewall both opened by eco with port 3001 in incoming rules. Port 3000 and 3001 are not being used from any other progams on my system.

@mirasrael I'am currently using Windows 10 64Bit Version 1909

**Comment by BlackiChu** [comment]
So I got a bit curious and played with the EcoServer.exe. So after it tried to initialize the WebServerPlugin this error message showed up: "The requested address is invalid in this context."
Any ideas what could solve this?

**Comment by redwyre** [comment]
Did you change the ipaddress in network.eco? It needs to be your _local_ ip address you want the server to listen on.

**Comment by BlackiChu** [comment]
@redwyre Thanks a lot that did the trick. I never changed the Network.eco, but what did change over the time was my router and provider so I never tought about that.
