### ISSUE TITLE
menu different on admin pages

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18127]
When youre on an admin page, instead of showing the account icon in top right, it shows account word link in left.
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/e6fda260-4fb4-4784-8066-273b0392b3a3)

Doesnt really matter, but make me happy to have the icon in the top right, like the rest of the website

**Comment by denysaw** [comment]
Done. Could be tested on Stagingland
