### ISSUE TITLE
GUI scalability for 3840x1200 resolution

### ISSUE THREAD

**Issue by zajcom** [StrangeLoopGames/EcoIssues#18131]
With 3840x1200 resolution when interface scalability is set to 60% (minimum size), items are very huge on screen.

![obraz](https://user-images.githubusercontent.com/62840280/92645289-ea901d80-f2e4-11ea-9188-5d5268e7b11c.png)

Same screen setting with only diffrent resolution, that is set to 1920x1200:
![obraz](https://user-images.githubusercontent.com/62840280/92645637-6b4f1980-f2e5-11ea-9c70-0b4382f5f790.png)

Main menu is okay on any resolution, issue is observed only during game and connected with width size.

Game version: 0.9

**Comment by SlayksWood** [comment]
dup #16535
