### ISSUE TITLE
faster page load on main page

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18135]
Use thumbnail size pics for devs in tree
large pics are causing delay in page load

Also, its loading tree sidebar pictures. dont load any, until sidebar is opened.

feel free to look for other ways to speed up landing page.
Also, the loading screen, doesn't have to wait for everything.
its ok if video and tree are not fully loaded yet. see if you can set it to hide, once everything else is loaded.

**Comment by denysaw** [comment]
Done. On Staging and Prod.
What was done:

- Installed `php7.3-gd` lib on `api.slg.com` to give ability to the WordPress to re-scale uploaded images (including Devs' avatars).
- Re-generated all uploaded images on `api.slg.com`.
- Enabled nginx' `gzip` web-page (and assets') compression (which saves big portion of data transferred from the website and strongly recommended by Google Page Speed Insights) on staging and prod servers.
- Refactored landing page cache. Now it caches not raw WP updates and users (as before), but whole processed/filled/filtered template's `data`. (increased time to the first bite).
- Totally removed preloader splash (3 loading dots) as we can't tell it to wait for half of the page and don't wait for another. Overall template loads very fast (including main menu and clouds) so it had totally no point and was only steeling customers' time. W/o it, page offers users some actions much much faster.
- P.S. Updates' images weren't loading to a sidePanel until it's open even before this.

**Comment by j3fffff** [comment]
fantastic!
we will implement a cdn soon too, that will bump it up a lot.
