### ISSUE TITLE
0.5.6.1 [Stable] Dump Files

### ISSUE THREAD

**Issue by Fireboss4** [StrangeLoopGames/EcoIssues#1813]
Here are my dump files for 0.5.6.1.  Most of them are probably the same as they mostly pertain to re-logging in attempts after being kicked for inactivity (when the server clock freezes) or other similar issues during login attempts. Game boots fine after crash and returns to normal. 
Zip file link: [https://app.box.com/s/cecn8czqta8ne6fbn0pyh1uovc4cg9d9](url)

**Comment by metachronism** [comment]
closing as largely resolved with inventory overhaul
