### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by illbredmiscreant** [StrangeLoopGames/EcoIssues#18145]
I'm currently unable to run the game server on Windows Server 2019. I have 3.1.8 net core runtime installed. I see this issue with a clean install. Running EcoServer.exe crashes and yields the following crash dump.

```
--BEGIN DUMP--
Dump Time
09/09/2020 19:51:17

Exception
Exception: DllNotFoundException
Message:Unable to load DLL 'enet' or one of its dependencies: The specified module could not be found. (0x8007007E)
Source:Mirasrael.ENet

System.DllNotFoundException: Unable to load DLL 'enet' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at ENet.Native.enet_deinitialize()
   at ENet.Library.Deinitialize()
   at Eco.Networking.ENet.ENetUdpLibrary.Dispose(Boolean disposing)
   at Eco.Networking.ENet.ENetUdpLibrary.Finalize()

--END DUMP--
```

**Comment by beastyn** [comment]
@illbredmiscreant Thank you for the report.
What bitness do you have?

**Comment by illbredmiscreant** [comment]
Hey @beastyn , this is a 64 bit system.

**Comment by illbredmiscreant** [comment]
For added context, I had no issue prior to the recent update. Right now I can fire up the old server on v0.8.3.3 and connect on steam client without issue.

**Comment by mirasrael** [comment]
@illbredmiscreant can you try install vs redistributable 2019 both x64 and x86. And also please attach full server log.

**Comment by illbredmiscreant** [comment]
@mirasrael Looks like installing the redistributables fixed the problem. Thanks!

**Comment by mirasrael** [comment]
@illbredmiscreant glad to know you problem fixed! @redwyre can you add x86 to steam prerequisites (it now only has x64) and also update server message (asking for  vs redist installation)

**Comment by redwyre** [comment]
@mirasrael there is no option for x86/x64:
![image](https://user-images.githubusercontent.com/431728/93097424-e56a0e80-f6e8-11ea-9959-a827624f1938.png)
But it is enabled now so we'll just have to wait and see if that fixes it.

**Comment by redwyre** [comment]
Haven't heard any more issues

**Comment by 7Developer** [comment]
Worked and fixed the Problem in my Windows Server! Thanks!
