### ISSUE TITLE
USER ISSUE: Tooltip Behavior

### ISSUE THREAD

**Issue by Jumbalja** [StrangeLoopGames/EcoIssues#18149]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Hovering mouse cursor over items or selectable things shows a tooltip box that doesnt disapear for a couple seconds or cursor is on the tooltip.

**Expected behavior:**
It would be nice if the tooltip disapeared as soon as the cursor leaves the item generating the tooltip.

**Actual behavior:**
The tooltip does not disapear if the cursor is on the tooltip and it takes an annoying amount of time for the tooltip to disapear after moving the cursor off the item.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by serpopov** [comment]
closely related to #17096
