### ISSUE TITLE
5.6.2 #5e0d162a Picking up Woodpulp costs way to much calories, etc

### ISSUE THREAD

**Issue by Ciannicay** [StrangeLoopGames/EcoIssues#1814]
Client/Server on localhost;  win 8.1;  64bit;  5.6.2 #5e0d162a
After chopping down trees you have a bunch of woodpulp lying around.
Even with max Logging (52%) and lvl4 Calorie Efficiency (20%) picking a singe item up needs 76,54 calories?
I mean chopping the whole tree needs less thats clearly off balance
I guess its a parameter error - looks like its one magintue to high.
Searched all files but couldnt fins a config with that info.

also i could only find WooPulpItem entries whereas the stuff i pick up probably should be WoodPulpBlock?

futhermore the gfx for it is buggy: the block/item seems to float above ground when further away

**Comment by Ciannicay** [comment]
additional info: that stuff can only be picked up with an axe and ONLY if its on a ground level with odd numbers - on ground level with even numbers you wont get that green outline of interaction.

**Comment by Ciannicay** [comment]
The stuff can be burried by dirt falling on it - as a result it is gone completely

**Comment by Ciannicay** [comment]
Problem persists in 5.6.2 staging 8802b6fc

**Comment by Ciannicay** [comment]
hmm, why did you close it? it still is true for the current staging version ?
Shall i really open it anew with the current version in the title?

**Comment by MarjieAVolk** [comment]
It's fixed on master - it should be fixed in the next release.  Sorry I wasn't clear about that

**Comment by Ciannicay** [comment]
would you please link it to the master then? how else should i and others know?

**Comment by Ciannicay** [comment]
ah, ok. at work we have master issues for stuff that appears more often (and thus is mentioned in serveral issue-tickets, said "slave" issues simply get linked to the master and not answered in detail) in order to reduce efforts of maintaining - so i thought you'd refer to something similar.
Didnt think you meant your next master-version. my bad.
Thanks for explaining!
