### ISSUE TITLE
cw remove item, should say when new subscription starts

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18140]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/7e8d599e-97a2-4317-9359-7dc60e9ca2b5)
Top image shows removal of world. does not say when world expires

For example, below image when adding a world, shows subscription start date.
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/fe2f21d8-d4ff-4552-8198-a3ebd7b67ed5)

In the grey totals box
display "Items expire date"

**Comment by SlayksWood** [comment]
fixed
![image](https://user-images.githubusercontent.com/45708377/99765449-2549d980-2b10-11eb-8543-4b3795964692.png)
