### ISSUE TITLE
USER ISSUE: Linux client stuck on 0.8.3.3 instead of 9.0.1

### ISSUE THREAD

**Issue by Dessix** [StrangeLoopGames/EcoIssues#18148]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Use Linux (Ubuntu in my case) to start the game.
Select either "none" or "9.0.1" in the beta listing; the game will not update, instead staying at 0.8.3.3.
Setting an earlier channel will downgrade, but setting it back to 9.0.1 upgrades it back to 0.8.3.3.

**Expected behavior:**
The game should have updated to 9.0.1.

**Actual behavior:**
Instead, the game stayed on the earlier build.

**Do you have mods installed? Does issue happen when no mods are installed?:**
This is on a completely new installation after freshly purchasing and downloading the game.

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/18081
