### ISSUE TITLE
Self-changing graphics?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18144]
```
Wuuuut? Graphics downgraded! Look at all objects, how low resolution they are now.. :(
EDIT: Probably some server issue - now after connecting couple of hours later, graphics look normal
EDIT2: I have allmost maxed out.. The resolution seem to auto change sometimes (matter of seconds, minutes)..
https://postimg.cc/pmJcshhR
https://postimg.cc/7CPsdH07
```

**Comment by beastyn** [comment]
It would be nice to have screenshots with graphic settings and PC spec form the person with the issue.

**Comment by 2hug** [comment]
I did play with those settings for months - no problem until update 9:
![20200910161134_1](https://user-images.githubusercontent.com/71083333/92743908-47411600-f381-11ea-96f9-502fa9febb97.jpg)

Specs:  6700k, gtx1080, 32gb ram, asus pro gaming.

**Comment by beastyn** [comment]
@2hug Thank you for the details. In 9.0 some settings were changes (like GI, Anialiazing). So you will need to play with setting a little bit to find one comfortable for you.

About resolution changes - it would be wonderful if we understand if you have issues with spontaneous resolution changes only with Exclusive option, or you will have it with Borderless fullscreen too.

Also, if you setting will change again, please. provide log file.
Instruction https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
