### ISSUE TITLE
Unable to create local game

### ISSUE THREAD

**Issue by Foehammer418** [StrangeLoopGames/EcoIssues#18151]
[log_200909115810.log](https://github.com/StrangeLoopGames/EcoIssues/files/5199221/log_200909115810.log)

Steps to Reproduce:
Try to start a Local Server.
After initializing world layers, fails to load server

Expected behavior:
It should have started a new world or any other world i already have.

Actual behavior:
Unable to load server and exits to main menu

Do you have mods installed? Does the issue happen when no mods are installed?:
I don't have any mods installed.

**Comment by redwyre** [comment]
Something is locking the server files, you may have a server running in the background? You can try restarting your computer and see if that helps.

If not you might have corrupted file descriptors, you can try uninstalling and making sure all the files are gone before reinstalling. If you can't remove the files you will probably need to run chkdsk to fix and file problems

**Comment by Foehammer418** [comment]
Uninstalling and deleting any leftover files, then reinstalling fixed the issue. Thank you!!
