### ISSUE TITLE
USER ISSUE: Web interface not opening

### ISSUE THREAD

**Issue by gandoulphe** [StrangeLoopGames/EcoIssues#18155]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
press G to open graph or
try to open constitution in browser

**Expected behavior:**
open a window in web browser

**Actual behavior:**
nothing happensm i can't participate in any govt action

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by gandoulphe** [comment]
My username is "Soupetard Salonique" and i'm playing through steam.

**Comment by beastyn** [comment]
@gandoulphe thank you for the report. What server do you play on?

**Comment by gandoulphe** [comment]
My default browser is Firefox, i tried with chrome too to no avail.
I'm playing on the "9.0! | Beginner Friendly | Otterville | Zero-skill network" server.

**Comment by redwyre** [comment]
The issue was the web url didn't start with http(s)://, which has been fixed by the host.

**Comment by beastyn** [comment]
Thanks!
