### ISSUE TITLE
USER ISSUE: Animals are glitching

### ISSUE THREAD

**Issue by SaintStyle** [StrangeLoopGames/EcoIssues#18154]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Shooting Animals

**Expected behavior:**
Stays at its coords

**Actual behavior:**
Glitches through the world

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@SaintStyle thank you for the report
1. What server do you play on?
2. Can you provide video?
3. Can you provide client log and server log (if you are the owner)?

Instruction is here
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by coolfarmer** [comment]
Oh god, we have the same problem on our private dedicated server:

CPU: AMD Ryzen 7 2700X
RAM: 16Gb
Internet Connection: 1Gbps (Optic Fiber)

Animals are very unstable, hunting them is really difficult, it's like they are teleporting, arrow can pass through their head.
We are 10-15 players online (Quebec and France). I THINK that the difficulty to hunting them is more difficult when we are many people connected (animals are synching through P2P?)

Server log: https://gist.github.com/coolfarmer/5e73bd02cf30059b905a478498833c56
Player log: https://gist.github.com/coolfarmer/3741c4e029b08b11db7a931c4b7fe899
Player-prev log : https://gist.github.com/coolfarmer/9f570c852ce0ed2b3497dc15828192bf

I'll try to do a video.
It's not "unplayable", but it's really annoying, they are really unstable.

**Comment by beastyn** [comment]
@coolfarmer do you have Tick error in the console?

**Comment by coolfarmer** [comment]
> 
> 
> @coolfarmer do you have Tick error in the console?

Not at all!

**Comment by SlayksWood** [comment]
merged to #18034
