### ISSUE TITLE
USER ISSUE: 0.9.0.1: Screen ingame turns darkend. like its at 50% brightness

### ISSUE THREAD

**Issue by LarsFalgren** [StrangeLoopGames/EcoIssues#18157]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
I have no idea... im the only one of my friends that have it. pictures linked.

**Expected behavior:**
The same brightness instead of it turning up and down all the time.

**Actual behavior:**
The screen darkens randomly from time to time, it can be 10 secs apart.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LarsFalgren** [comment]
![Darkend](https://user-images.githubusercontent.com/71016033/92716887-b574e100-f35f-11ea-9c96-6a3678e3a1d6.PNG)
![Light](https://user-images.githubusercontent.com/71016033/92716926-c160a300-f35f-11ea-8a06-3214c33b2ba5.png)

I cant seem to upload the player.log it says its too big

**Comment by beastyn** [comment]
@LarsFalgren thank you for the report.
I still need your log file, maybe use google drive or something? 
If it too big its not good.

**Comment by LarsFalgren** [comment]
https://drive.google.com/drive/folders/1uHFuVT1xMyWQBt1ZZu6DsUKGzy1L9Tfj?usp=sharing
think this works. never used google drive before.

**Comment by LarsFalgren** [comment]
Steps to Reproduce: seems like it happens most often when I open stockpiles. they have that overlay and it just keeps sticking around.

**Comment by beastyn** [comment]
Did client restart help you?

**Comment by LarsFalgren** [comment]
it works for the first 20mins then it starts again.

**Comment by beastyn** [comment]
Ok, thank you. Also I will need ro know what ping do you have on a server (what server is it?)
And also you PC specification.

**Comment by LarsFalgren** [comment]
My own server that I host.
also added my Dxdiag
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5209253/DxDiag.txt)

**Comment by keegan-o** [comment]
Definitely looks like the UI overlay sticking around when it shouldn't to me!

**Comment by LarsFalgren** [comment]
I've also had the reverse of the bug. When I was in a crafting bench and the darkened background that comes when entering just disappears there after a couple of seconds. so it really seems like everything with backgrounds can't decide if it wanna stick around or not.

**Comment by Mkorny** [comment]
Adding a few more notes and Repro:

I am attaching a OneDrive .mp4 that very clearly shows the bug occuring:
[Video Repro](https://1drv.ms/v/s!AlwkS4BRguXxmBV5b9HLXrjDuVGd?e=otxam3)

And a quick timeline:
Second 26 - normal view
Second 31 - gets darker once i open the menu.
Second 46 - compare to sec 26 and u will see the exact side-by-side comparison on the tunnel/ramp down.
Minute 02:48 - You see a clear "switch" in the lighting; or brightness of the game, which makes it "playable" again.

Also adding DxDiag, as i'm sure it'll be helpful.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5398204/DxDiag.txt)

**Comment by Mkorny** [comment]
With the latest changes, since the background doesn't darken, just blurs... it actually prevents this from happening again :) 

I call it as fixed tbh! 👍

**Comment by SlayksWood** [comment]
Yes, I also got it better. We have some blurring problems, but they are other issues. closed this one.
