### ISSUE TITLE
Minimap refactoring

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18152]
A few things we need to refactor in the minimap:

**Setting icons on the minimap**
The options to decide which categories of objects to display aren't working in the refactor, and they need a refactor themselves as they're quite spaghettified.  

I would tackle it like this: Make the MinimapConfigPanel subscribe to the MinimapUIObjectManager, getting notified when new objects get added or removed, and the config panel will use this information to determine what settings to create or hide. Check out BuildOverlayToggles which does this same thing with the OverlayManager that I added.  Then, when these get settings get checked, ConfigPanel can call the MinimapUIObjectManager and set them to visible or invisible.

This way, we can ensure a few important things which are not currently the case:
- MinimapUIObjectManager neednt know anything about displaying settings, or reference ConfigPanel at all. That's the *controller*, and it can operate on MinimapUIObjectManager through the public interface of callbacks and events.

- The component MinimapToggle is used to send clicks back to the ConfigPanel and ObjectManager. but this shouldn't happen. It should just be a basic toggle, that is told what to do by whatever owns it, in this case the ConfigPanel.  You can use the existing prefabs for MinimapSetting defined in the ConfigPanel, creating those when those subscriptions fire (when new categories are added/removed), and the ConfigPanel 'glues' together that toggle to the ObjectManager, setting up the code for when the toggle is clicked to call a function on the ObjectManager.   This keeps encapsulation, and allows us to share the same prefab for the setting among the different settings of the ConfigPanel.

- Remove the custom code that handle saving to PlayerPrefs, and use the encapsulated versions I created with RememberToggle and RememberToggleIndex. This way the playerprefs are handled automatically by whatever needs them, no custom code needed.

**Editing districts/property**
So with my refactor I've changed a lot of the minimap to be *agnostic to the overlay sources*. I defined an 'IOverlay' interface, and made the various types of overlays implement this: property, districts, world layers, the new settlements system.  Now the minimap can just display whatever overlay is selected, and the configpanel can create the options for the overlays, neither having any reference to districts, property, etc.  Nice and simple interface.

We'll need to extend this to support editing.  I think what we'll want to do (possibly) is make an interface like IEditableLayout, which can be edited by the user, and districts and property will implement this. Then we can remove things like MinimapSelectionDistricts and MinimapSelectionProperty, and just operate on this interface, not needing to know what type it is at all.

Once this is working, it will open the door for a lot of other cool map editing things I'd like to do. Settlements will likely have editable mapping.  Work Parties will have them for things like 'Set the plots where you'd like the road to be created' or 'Set the plots to be tilled', and we can just implement a new IEditableLayout and it will all automagically work.  

So in the end, the minimap should have no reference to districts, property, world layers, or anything. It just operates through a provider (OverlayManager) that give it IOverlays, and some of them can be edited.  

Let me know architecture questions. happy to help with this!

**Comment by IcedForge** [comment]
@gzatravkin Ill close the 2 map related issues now tagging you so you can copy any content you want from it into a doc if you want.
