### ISSUE TITLE
[0.9.0.1] No music / sound effect stop working randomely

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#18153]
I was playing all the day with a group of friends (15) and no one of us have music. We played ALL THE DAY for about 14 hours straight line, and NO music at all, only sounds effect and ambience like wind, or animal.

And second problem, the sounds effect stop working randomely. Imagine I was using my wood cart, or axe, or shovel, the sound work 2 minutes, then stop working for 4 minutes, etc, etc etc. 50% of time my wood cart don't have any sound...

Please fix, it's really annoying :/

**Comment by beastyn** [comment]
@coolfarmer thank you for the report. Can you provide you log file?
Instruction is here https://github.com/strangeloopgames/ecoissues/issues/18097

**Comment by beastyn** [comment]
@Quadbro seems like we have a bunch of reasons for sounds to disappear.
Try this:
1) Place and launch campfire
2) Place tool bench
3) You should hear a sound from campfire
4)/give modern hammer
5) Select a hammer / inventory durability 1
6) Place a hammer into a tool bench for reparing. Sound of a campfire will disappear.

**Comment by coolfarmer** [comment]
Server log is here: https://gist.github.com/coolfarmer/6d0047e4cda4d48cf6d136cecf2f2e1a
Player log: https://gist.github.com/coolfarmer/3741c4e029b08b11db7a931c4b7fe899
Player-prev log : https://gist.github.com/coolfarmer/9f570c852ce0ed2b3497dc15828192bf

**Comment by coolfarmer** [comment]
I don't know how to reproduce the bug, but I know a workaround that can fix it every time it happen.
For example if I lose the sound of my wood cart:

1. Press "E" to release the cart from my hand
2. Change my hand tool, for example if I have the axe I can change to the pickaxe
3. I take again my wood cart and hop the sound is back

**Comment by Aryathal** [comment]
I also have problems with music. For some reason, the music worked for only like, 20 minutes, and now there is no music although the slider for music is at e.g. 50

**Comment by NJAldwin** [comment]
I am experiencing a loss of all Steam Truck and Steam Tractor sounds.  It occurs reproducibly if I enter a tractor or truck in 1st person then press F5 to switch to 3rd person while on the vehicle.  Sounds do not come back upon switching back to 1st person.  Sounds do not return upon exiting or re-entering the vehicle.  The only way I've found to restore the sounds is to destroy the tractor or truck and re-place it, or to restart the game (I am playing singleplayer on my machine, no separate server).

Is this related to this issue or a new issue?

_[0.9.0.2 beta release-71]_

**Comment by coolfarmer** [comment]
95% of the sound problems can be fixed by changing the tool in your hand.

5% = The river by example, I can her the sound of water or the wind, and suddendly no more sound, exept my foots or jump.

**Comment by coolfarmer** [comment]
This problem is supposed to be fixed in 0.9.0.3 ?

**Comment by SlayksWood** [comment]
@coolfarmer no, in 9.1

**Comment by SlayksWood** [comment]
It got better, so closed for now.
