### ISSUE TITLE
5.6.1 -> 6.0.0 Backwards Compatibility

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#1815]
I tried Staging Alpha 5.6.2 #5e0d162a with Game.eco file from 0.5.6.1 Stable.
And it don't works.

The only solution to allows your Game.eco file form 0.5.6.1 Stable to work on Staging Alpha 5.6.2 #5e0d162a is actually to open the file, remove the /user files , save and then your 0.5.6.2 server works , but you lost all players informations.

The Game.eco and crash file below:
https://www.dropbox.com/sh/vv13rbit681rjwn/AAA0trkmR95fdkcsBnX4dSxoa?dl=0

Join us on Ecotopia:
![banniere-eco 1](https://user-images.githubusercontent.com/29807119/28529543-1e96360c-7091-11e7-822b-c061273d0725.gif)

**Comment by metachronism** [comment]
backwards compatibility is not yet working for 5.6.1 -> 6.0.0

**Comment by metachronism** [comment]
this is partially supported, only user inventories are lost currently

**Comment by MarjieAVolk** [comment]
(Laws are lost too)
