### ISSUE TITLE
USER ISSUE: Value of constitution`s room

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18165]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Create empty nonclaimed room
2. Put capitol
3. Ratify and fin constitution
4. Pick up capitol
5. Claim room and put some decor
6. Put another capitol

**Expected behavior:**
Value of new contitution's room (4) must be exceed the active constitution's room (0)

**Actual behavior:**
In capitol: "Value of contitution's room (4) does not exceed the active constitution's room (0 for old Constitution) by more than 50% (6), so it cannot be ratified"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nothing mods, singleplayer.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Artem314159 Thank you for the report.
Try to claim a room with furniture.

**Comment by SlayksWood** [comment]
This is a problem with updating notification when you pick up constitution:
![image](https://user-images.githubusercontent.com/45708377/100229306-16f72580-2f35-11eb-9b92-2dcf4a44fdf4.png)
