### ISSUE TITLE
USER ISSUE: Didn't get a bow for hunting

### ISSUE THREAD

**Issue by pfmd86** [StrangeLoopGames/EcoIssues#18167]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
used my skill star in the tutorial on "Hunting" but I didn't get the bow. I checked inventory, stockpiles and backpack

**Expected behavior:**
getting the bow for hunting

**Actual behavior:**
did not get anything

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5205326/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5205327/Player.log)

**Comment by MishkaFur** [comment]
Skills logging/mining do not give tools anymore, Believe same applies to hunting.

**Comment by beastyn** [comment]
Free tools are no more )
