### ISSUE TITLE
USER ISSUE: Election description error

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18164]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Put a capitol
2. Ratify standart constitution
3. Use /fin fo this election
4. Put Census Bureau
5. Pick up capitol in inventory
6. Create first demografic and put to the vote
7. Create second demografic and put to the vote

I think, this is one of many scenarios to get this error.

**Expected behavior:**
Everything should be fine (:

**Actual behavior:**
Crash local server and exception "NullReferenceException: not set instance of Civics.Elections.Election.FullDescribe()"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nothing mods, clear client.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Artem314159 Thank you for the report. Please provide client and serve log file
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

Could not reproduce it by these steps.

**Comment by Artem314159** [comment]
So far, I can't reproduce either, I will look for another option to catch this mistake

**Comment by beastyn** [comment]
It's still here.
Pretty hard to reproduce and it can happen with an activation of any Elections.
Need to try fix it anyway. Need to create a lot of civics objects maybe with clearing the cache.

**Comment by johnkslg** [comment]
I think this will have gone away with my re-write of the proposal system last week, can you tell me if it comes back?
