### ISSUE TITLE
USER ISSUE: Server Login "User doesn't have any assigned products"

### ISSUE THREAD

**Issue by Chuchzilla** [StrangeLoopGames/EcoIssues#18168]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1.Start Dedicated server
2.Try to login

**Expected behavior:**
Join Server

**Actual behavior:**
The following error message popped up:
Connection Failed
Invalid login info
User doesn't have any assigned products

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Also on a fresh world. I am admin also.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5206076/Player.log)

**Comment by beastyn** [comment]
@Chuchzilla  please send a message to the support
D3nnis3n#2053 on Discord
