### ISSUE TITLE
USER ISSUE: Redwood Space Program

### ISSUE THREAD

**Issue by Hemmylock** [StrangeLoopGames/EcoIssues#18166]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Have someone host, have the host cut down a Redwood tree and split it, have the client jump into the logs.

**Expected behavior:**
Bumping into the logs.

**Actual behavior:**
As soon as I touched the logs, I shot upwards 1,500M from the map and remained there. Quitting and re-joining didn't fix it, I had to be teleported back.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Hemmylock  Thank you for the report.
Please provide a log file from the session where you've got the issue
Instruction: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file.

Also video would be helpful (if you have it again).

**Comment by beastyn** [comment]
merging here #12553
