### ISSUE TITLE
 Getting Crashes Nviida card goes blank and Onboard graphics then follows Eco closes and reports crash then all comes back

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#18163]
**Version:** 0.9.0.0 beta
**Version:** 0.9.0.1 beta

This is a weird Bug that i **only** seem to be getting when running eco, 
here are 9 Crash Reports in a zip all after exactly same thing happening
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5204568/Crashes.zip)

I have no idea how to reproduce this ,i can be mining or digging or just doing something in eco, then everything goes blank on my main monitor (Nvidia card)  then my 2nd monitor goes blank as well (Intel onboard graphics), sometimes i see eco reporting a crash dump on this blank screen other times it doesn't, i can get my screens back by pressing ctrl alt and delete, if i am really unlucky i get a total lockup of PC (that only ever happened once)
my graphic drivers are up to date, i even uninstalled and reinstalled a fresh copy

![snap7185](https://user-images.githubusercontent.com/29383891/92804357-31971500-f3b0-11ea-9aac-38f759f0175c.png)
![snap7186](https://user-images.githubusercontent.com/29383891/92804656-6014f000-f3b0-11ea-9257-06c83bfdb5b1.png)

i had thought it was because game was in Fullscreen even changed that to full screen windowed (that didn;t make any difference)
![snap7187](https://user-images.githubusercontent.com/29383891/92805886-66f03280-f3b1-11ea-92ce-5567b193f739.png)

**Comment by Conchipedia** [comment]
I think i might have Solved this with the help of my Friend, my Graphics card wasn't kicking in the fans when the temperature was going up, and that certainly was happening in ECO, have now played a few hours with nothing kicking me
so will leave this open for a day or so, if it doesn't happen again i will close this

**Comment by Conchipedia** [comment]
had a another crash this is the crashfile
[Crash_2020-09-11_210835796.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5211708/Crash_2020-09-11_210835796.zip)

**Comment by redwyre** [comment]
Definitely looks like GPU issues. Does it crash if you just leave it open at the title screen?

**Comment by Conchipedia** [comment]
as far as i can tell it was only in game
another crash file
[Crash_2020-09-14_143203204.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5219731/Crash_2020-09-14_143203204.zip)

**Comment by redwyre** [comment]
The error you are getting is:
> The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action. 

It looks like it's highly likely there are hardware issues with your card, but there are a few things you can try (but do so at your own risk):
* Completely remove and reinstall the graphics drivers (better yet use https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
* Underclock the card to see if it increases stability
* You could try increasing the TdrDelay timeout: https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys

Might just be time to upgrade your GPU ;)

**Comment by redwyre** [comment]
It looks like this may be a more general issue, this is now being looked at as part of #18403
