### ISSUE TITLE
Weird default keybindings

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18160]
https://steamcommunity.com/sharedfiles/filedetails/?id=2225208291

This is not right, everything reversed.

**Comment by beastyn** [comment]
Hoe does THAT happened?
We need a log at least

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/94921743-8b779000-04c1-11eb-89a3-b4527266804a.png)
