### ISSUE TITLE
[Staging Alpha 5.6.2 #5e0d162a] Crash during generating world

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#1817]
Hi , i want to test 0.5.6.2 stagging.
When the world is generating ecoserver crash due to a outofmemory bug.

Dump here:

[Crash 07264020.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1176448/Crash.07264020.txt)

**Comment by MarjieAVolk** [comment]
--BEGIN DUMP--
Dump Time
07/26/2017 13:40:20

Exception
System.OutOfMemoryException: Une exception de type 'System.OutOfMemoryException' a été levée.
   à System.Text.StringBuilder.ToString()
   à System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   à System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   à System.String.Format(String format, Object[] args)
   à Eco.Core.Controller.ControllerManager.Run()
   à Eco.Server.PluginManager.<>c__DisplayClass11_0.<StartPlugins>b__0(Object x)
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by metachronism** [comment]
closing, similar issue to other OOM issues.

We've gone back to a 64-bit server for now
