### ISSUE TITLE
[0.9.0.1] Desert plants are dying out

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18171]
With change to fertility to desert, many of the desert plants are not surviving. This is especially bad with Prickly Pear. This could be compounded with other plant issues, but this requires special attention compared to other plants.

**Comment by coolfarmer** [comment]
Is there a problem too with the jungle? On my server the plants and papaya trees in the jungle are 30-40% dead ... :/

**Comment by beastyn** [comment]
Should be more common problem.##18173
