### ISSUE TITLE
USER ISSUE: Random Plant Extinction

### ISSUE THREAD

**Issue by ibcyndilu** [StrangeLoopGames/EcoIssues#18173]
![Screenshot_14](https://user-images.githubusercontent.com/71125386/92900544-c79d6080-f3ed-11ea-90dc-cc8d62d728b7.png)
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Join a fresh server and play for a few hours. Then go out and try to gather some food from plants. In the screenshot you can see how far away from my camp I am and everything is just... dead. In the entire rainforest. except trees and mushrooms.

**Expected behavior:**
Plants should be abundant. There is currently no pollution. Areas are unexplored and nothing bad has happened yet! You should be able to find food and stuff.

**Actual behavior:**
After a few hours, prickly pears, small cactuses, and agave die off in the desert. Quickly followed by ferns, taro roots, papayas and pineapples in the jungle.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
Here is about desert #18171

**Comment by beastyn** [comment]
@WeaselDog placing on hotfix. Please move if we are waiting for Alex.

**Comment by beastyn** [comment]
and this #18274
