### ISSUE TITLE
USER ISSUE: Can't Crouch

### ISSUE THREAD

**Issue by alaffray** [StrangeLoopGames/EcoIssues#18176]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Game is in French but using a QWERTY keyboard

**Expected behavior:**
I should be able to crouch like previous version

**Actual behavior:**
Nothing is happening

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@alaffray Thank you for the report. Crouch is actually slowly moving.
Can you move slowly with CTR? (also swim down)

**Comment by alaffray** [comment]
@beastyn Yes CTRL is allowing me to walk slowly and swim down.

**Comment by beastyn** [comment]
@alaffray Well, that's the way it is )
We actually do not have crouch mechanic. Worth to rename it maybe )
