### ISSUE TITLE
USER ISSUE: Incorrect displaying arithmetic operations in laws

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18183]
![IncorrectArifmOps](https://user-images.githubusercontent.com/17272063/92945474-fbb06a00-f45d-11ea-8ad4-5f8776edf1ff.png)

**Comment by SlayksWood** [comment]
fixed 
![image](https://user-images.githubusercontent.com/45708377/102051966-78086f80-3df6-11eb-95e7-551037188db9.png)
