### ISSUE TITLE
USER ISSUE: Civic duties

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18182]
**Version:** 0.9.0.1 beta

**Civic duties behavior is always this:**

![1](https://user-images.githubusercontent.com/17272063/92939525-9311bf00-f456-11ea-93ff-6ab89feb4a58.png)
![2](https://user-images.githubusercontent.com/17272063/92939523-92792880-f456-11ea-873a-9192798684e5.png)
![3](https://user-images.githubusercontent.com/17272063/92939519-9147fb80-f456-11ea-929d-7241b2828604.png)
![4](https://user-images.githubusercontent.com/17272063/92939536-9442ec00-f456-11ea-8e3d-56db4a19473b.png)
![5](https://user-images.githubusercontent.com/17272063/92939532-93aa5580-f456-11ea-9ed0-73308b05cad5.png)
![6](https://user-images.githubusercontent.com/17272063/92939531-93aa5580-f456-11ea-8bd2-cefc20f7f135.png)
![7](https://user-images.githubusercontent.com/17272063/92939528-9311bf00-f456-11ea-9cd8-8c5916e8f26a.png)

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/94428948-3de5e500-019a-11eb-9be1-8a9add2b54e1.png)

**Comment by mirasrael** [comment]
Problem was with extension methods returned by ReflectionUtils.AllMembers (for non-instance members request).

**Comment by olegshegai** [comment]
May be closed together with https://github.com/StrangeLoopGames/EcoIssues/issues/18598
