### ISSUE TITLE
Eco Tree Issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18187]
- [x] Eco tree discussion shows a bunch of pictures of Simon for some reason:
![image](https://user-images.githubusercontent.com/3536496/92956161-41980e80-f41b-11ea-87e3-ef0ccf172da6.png)

- [x] Clicking Simon or following non-existent feature link breaks it: 
![image](https://user-images.githubusercontent.com/3536496/92956174-4957b300-f41b-11ea-8140-14fdba95a2ce.png)

- [x] Need a better way to view when there are comments.  On each entry, add a popup like the yellow number, but in a comment speech bubble, that shows how many new comments are there since last time you viewed that one:
![image](https://user-images.githubusercontent.com/3536496/92956240-65f3eb00-f41b-11ea-8e80-84e860ab9115.png)

- [x] Also make community discussion show this bubble: 
![image](https://user-images.githubusercontent.com/3536496/92956256-7015e980-f41b-11ea-9170-077ed26665ed.png)

**Comment by denysaw** [comment]
@johnkslg Not sure we even could get overall comments count, not even saying about NEW comments count. @j3fffff could you look into it (research? Thanx

`Also make community discussion show this bubble:`
Q: Which bubble? Can't get where's bubble on the snapshot (

**Comment by denysaw** [comment]
About `Eco tree discussion shows a bunch of pictures of Simon for some reason:`. Seems it's just `og:image` parsed Simon (by Disqus).
@johnkslg @j3fffff Could we just remove this section by Disqus config?

**Comment by johnkslg** [comment]
yeah you can remove that section
there is no bubble, just showing where it would go
im sure disqus must have API for querying comments and dates

**Comment by WeaselDog** [comment]
If you follow this link, [https;//play.eco/updates/techtree](url), it causes the same issue if you click the picture of Simon

**Comment by denysaw** [comment]
@WeaselDog You meant accounts.play.eco?

**Comment by denysaw** [comment]
Um... But that's because it's unexisting section (techtree). Every unexisting section would cause that. But, yep, I'll fix it, so it won't appear for unexisting sections.

**Comment by denysaw** [comment]
@j3fffff `im sure disqus must have API for querying comments and dates`, research please about it. Will help me a lot ;)

**Comment by denysaw** [comment]
@j3fffff First is yours, cuzz it couldn't be removed by plugin initialization settings, only by tweaking settings in Disqus' Admin Cabinet. Please, follow this manual: https://www.lovinglifemoore.com/2020/05/how-to-remove-the-also-on-feature-from-disqus.html

**Comment by denysaw** [comment]
Could be tested on Staging.

**Comment by j3fffff** [comment]
I can't get the Disqus Community page  (that is showing simons pic) to update with a new post.
I've tried posting various comments in separate disqus comments. 
@SlayksWood can you see if you can get an update to show on the Community page: https://disqus.com/home/forum/strangeloopgames/

Should be able to just post on the eco tree, and it shows up. Maybe it requires a facebook login on disqus or something...

**Comment by denysaw** [comment]
@j3fffff Man, this is issue is completely fixed. I remembered, that I have Disqus credentials and removed Simon myself ;)

**Comment by SlayksWood** [comment]
This one i closed, open another issue with Simon xD
