### ISSUE TITLE
Looking up under Asphalt Road (it is invisible) 5.6.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1818]
![snap017](https://user-images.githubusercontent.com/29383891/28631058-e41973b0-7223-11e7-8ef1-656a548ddb43.png)
Have placed Asphalt road as a floor, built a room underneath and when looking up the ceiling is invisible (

**Comment by keegan-o** [comment]
Fixed it in master.
