### ISSUE TITLE
Laws dont display correct creator

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18184]
![laws](https://user-images.githubusercontent.com/25908592/92946137-85f4d000-f456-11ea-958b-203d66e4aeb8.png)

**Comment by D3nnis3n** [comment]
And no, soldier had _nothing_ to do with the law at all, he said. So i don't get that discrepancy.

**Comment by D3nnis3n** [comment]
I also noted the name of thesoldier57 tended to change to different names when i opened the tooltip several times, like its taking the last person voting or something.

**Comment by johnkslg** [comment]
while youre in here, can you also sort the votes list in the tooltip? Group it by yes/no

Vote:
5 yes: Joe, Bob, Jim, etc
6 no: Tim, Tu, Duck, etc

**Comment by tuha263** [comment]
I can't reproduce this.
and "Election started by" is able different from "Law Created by"
I also updated the tooltip
![electiontooltip](https://user-images.githubusercontent.com/9598614/99803354-e0ec2700-2b6b-11eb-989f-63c6ab7f3035.png)

**Comment by SlayksWood** [comment]
I don't know how to check it right. This is possibly, because this is different string. One player can create draft, second player can start election.
But it always display for me right information. So closed.
