### ISSUE TITLE
USER ISSUE: Bad Performance - < 30 fps

### ISSUE THREAD

**Issue by Jaredtherocker** [StrangeLoopGames/EcoIssues#18180]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Launch the game. This even occurs in the title menu.

**Expected behavior:**
60+ fps and smooth performance	

**Actual behavior:**
Drops under 30 fps and even down to 10.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A - No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5209065/Player-prev.log)

**Comment by Jaredtherocker** [comment]
Uninstalling and reinstalling the game seemed to have bandaided the issue. I am now running 48 fps instead of 20-30 fps.

**Comment by Jaredtherocker** [comment]
![image](https://user-images.githubusercontent.com/71134381/92930656-5ae78d80-f410-11ea-9db9-7a95989d04c7.png)

**Comment by Jaredtherocker** [comment]
Still not too great. Barely playable. I suspect this is a cache issue. Will continue to monitor for degradation...
Any thoughts on how to improve performance?

**Comment by Jaredtherocker** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5209264/Player.log)

Updated log post reinstall attached.

**Comment by beastyn** [comment]
@Jaredtherocker Thank you for the report. PC spec + OS would be nice to have too.
Also please provide a log file if you have fps drop again (you can have spammy errors there so it can drop fps too) 

Tiy can play with shadows quality, maybe View distance around 120

**Comment by Jaredtherocker** [comment]
@beastyn I just changed the view distance to 120, seems to improve a little. Dropped shadow quality to low. No difference.

Winver: Windows 10 - 2004 (OS Build 19041.508)

Processor: Intel Core i7-4770K CPU @ 3.50 GHz
Video: NVIDIA GeForce GTX 1060 6GB (ID=0x1c03)
RAM: 16 GB
64 bit OS

Log is included in previous comment :) 
Thanks!

**Comment by IcedForge** [comment]
There were a few optimization upgrades in 9.1, are you still having the same severe deterioration and how fast are these occurring? 
Is this happening while playing on your own local world? Or is this any multiplayer server?

**Comment by SlayksWood** [comment]
We have issues to improve optimization. Closed this one, one of the newest #19440
