### ISSUE TITLE
USER ISSUE: Delete dependent Demographics

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18188]
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Put Capitol and ratify constitution
2. Put Census Bureau and create standart demografic (Dem1)
3. Create a new demography (Dem2) dependent on the Dem1
4. Delete Dem1 via election
5. Try to delete draft Dem1

![image](https://user-images.githubusercontent.com/17272063/92968666-388f5780-f484-11ea-91d0-4687e5ee2983.png)

**Actual behavior:**
Crash Server with exception: 

"Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.CivicObjectComponent.<>c__DisplayClass41_0.<Remove>b__0(IHasID x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable'1 source, Func'2 predicate)
   at Eco.Gameplay.Components.CivicObjectComponent.Remove(Player player, Int32 index, Boolean removeActive)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"

**Do you have mods installed?**
SinglePlayer without mods

**Comment by IcedForge** [comment]
Could you please upload server files and the player log / server logs?

**Comment by Artem314159** [comment]
[EcoDemogrError.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5223683/EcoDemogrError.zip)

@IcedForge If I uploaded not what you need, please clarify where these files are located. 🙃

**Comment by beastyn** [comment]
@Artem314159 Thanks a lot for the additional info.
I will use this issue like a base.
It can be connected to #16601 

1) Create a fresh world.
2) Place a capitol and ratify
3) /toggleuicache
4) Place a census
5) Create demographic 5. (/fin)
6) Create demographic 6 with Demographic Requirement with Demo 5
7) Delete Demo 5 (/fin)
8) You should have REMOVED object on the table.
9) Try to remove it. have a server crash
https://drive.google.com/file/d/1Fp6mKboxi5XsWy9MNjUCvPk7S2spexfT/view?usp=sharing

**Comment by beastyn** [comment]
Different possible cases
#16377, #18252, #18265

**Comment by SlayksWood** [comment]
Seems fixed, I don't have crashes and second demographic will be Invalid.
![image](https://user-images.githubusercontent.com/45708377/94427302-86e86a00-0197-11eb-96d6-2aba9fbbf2d8.png)
![image](https://user-images.githubusercontent.com/45708377/94427329-8fd93b80-0197-11eb-9c94-124262c1ae10.png)
