### ISSUE TITLE
USER ISSUE: Débris Bois de chêne 

### ISSUE THREAD

**Issue by Kingkopop** [StrangeLoopGames/EcoIssues#18186]
\
**Version:** 0.9.0.1 beta

L'orsque l'on enleves les diférent débris et souche du bois de chêne les débris ne s'enleve pas sur la cartographie et cela pollue la terre sans qu'il y ai rien à la surface.

![image](https://user-images.githubusercontent.com/17802048/92956069-87c68f80-f466-11ea-9b21-5a79db5e0ee7.png)

**Comment by Nobilem** [comment]
Here come the french translation team ! 

When oak branches and strains are remove, it actually doesn't remove them from the map. This create ground pollution even if there isn't any garbage at those locations.

**Comment by beastyn** [comment]
@Kingkopop @Nobilem thank you for the report.
How long are you waiting after the clearing?

**Comment by beastyn** [comment]
merging here #18533
