### ISSUE TITLE
Imposible to start any Solo Game

### ISSUE THREAD

**Issue by Madkuya** [StrangeLoopGames/EcoIssues#18199]
I am unable to start an solo World. Everytime i start tro create a new World thise comes up
![20200909221432_1](https://user-images.githubusercontent.com/71166724/92989033-5040fd00-f4d1-11ea-8eb9-457cba1ca594.jpg)

On that given lokation are **NO Log Folder!** ( i uninstall the Game 5 Times now and delate **all** left over Folders) Also the Game does **NOT** create an Log File here!

But inside the Strange Loop Games Folder, there is an Playes log Createt every time.:

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212280/Player-prev.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212281/Player.log)

**Comment by beastyn** [comment]
@Madkuya Thank you for the report.
Would you don't mind to provide a little bit of experiment?
- Go to the your Game folder on steam ( something like SteamLibrary\steamapps\common\Eco\Eco_Data\Server)
- 1) Check if Storage folder is empty
- 2) Try to launch EcoServer from there

And can you provide a little bit more info about you PC specification and OS?
-

**Comment by Madkuya** [comment]
Yes Storage is empty.  If i run the EcoServer.exe the bios screen pops up like 2 seconds and closes again.  same with the EcoServer32.exe  

Win 7 Ultimate
AMD FX(tm)-6300 Six-Core Processor  3.50 GHz
RAM 24GB

Nvidia GeForce GTX 1050 Ti



Eco Runs Perfectly before the 9.0 Update!

**Comment by Madkuya** [comment]
I remember to have the same issue onj the 8 Update. Sadly i can't remember what the fix was.    Writing thos lines i just remember how it was solved. I'll check if it works again.  

i have been told to go into the _WorldGenerator.eco.template_ and change the line 
from:
_  "ConfigVersion": 1,
  "$id": "1",  
  "Dimensions": {
    "x": 72,
    "y": 72_

to:
 _  "ConfigVersion": 1,
  "$id": "0",  
  "Dimensions": {
    "x": 72,
    "y": 72_

Sadly  it does not work this time.
When ever i run the server.exe. i see this for like 1 second:
![Ecoserverfail](https://user-images.githubusercontent.com/71166724/93360716-4b1edd80-f844-11ea-972d-90478ce57f51.jpg)

**Comment by redwyre** [comment]
You should never modify the template files. You can however delete all your .eco files and they will be regenerated with new versions. It doesn't look like that is related to this issue though.

Do you have Windows 7 SP1 or newer? Can you run winver and show the version?
You can try installing the latest VC runtime here: https://aka.ms/vs/16/release/vc_redist.x64.exe and see if that helps

If not, try installing the latest dotnet runtime: https://download.visualstudio.microsoft.com/download/pr/add2ffbe-a288-4d47-8b09-a39c8645f505/8516700dd5bd85fe07e8010e55d8f653/windowsdesktop-runtime-3.1.8-win-x64.exe
While not necessary, it should install any missing dependencies

**Comment by Madkuya** [comment]
Hello, yea ok i understand.

I have 
Windows 7 Version 6.1(Build 7601: Service Pack )

Some cobyright blabla

Licensed for:
UseranameUltimate64

**Comment by redwyre** [comment]
Could you try opening `%TEMP%\.net\` in explorer, and delete any eco folders?

**Comment by Madkuya** [comment]
Wow ther are tons of numbered folders. But none is named Eco.  May it be one or some  of the numbered Folders?

**Comment by Madkuya** [comment]
> Could you try opening `%TEMP%\.net\` in explorer, and delete any eco folders?

ok found and delate them.

Just to be sure i delate the Game and all remaining Folders then install it new so there are no edidet conifs left.

**Comment by redwyre** [comment]
I'm not sure what else I can suggest. Windows 7 is out of support, and we only officially support Windows 10. You can try searching for general help with running dotnet apps on Windows 7.

**Comment by Madkuya** [comment]
2 Days ago i went to the Shop on Steam. I saw that you not support the System that you startet on and i must say thats not ok. Its like buying an Car and on like 90% of the assembling you get a call that you wont get what you already have payed for.  Like btw we dont support your gasoline type anymore.

**Comment by Madkuya** [comment]
Well i invest the 20€ for change to win10 then and hope it will Work.  Anyway, such approach is not ok

**Comment by redwyre** [comment]
Unfortunately that is a fact of computer software and games, older operating systems go out of support and new ones replace them. We don't specifically try to stop supporting older systems, it just happens as components we use drop support.

You may be able to get Windows 10 for free if look around: https://www.zdnet.com/article/heres-how-you-can-still-get-a-free-windows-10-upgrade/ (and remember to backup all your important files before upgrading)

**Comment by Madkuya** [comment]
yes thank you i found it. and i run on win 10 now as well. I already have a new issie, so i guess this one can be closed.
