### ISSUE TITLE
USER / SERVER ISSUE: Fish Traps not functioning correctly. Not in water when clearly underwater.

### ISSUE THREAD

**Issue by soulnet** [StrangeLoopGames/EcoIssues#18197]
![Fish Trap](https://user-images.githubusercontent.com/36501028/92986962-cc533900-f501-11ea-8a82-b48b7a81f941.png)
![Fish Trap2](https://user-images.githubusercontent.com/36501028/92986975-decd7280-f501-11ea-8900-bb359285e1ec.png)
![Fish Trap3](https://user-images.githubusercontent.com/36501028/92986982-e4c35380-f501-11ea-9049-70dbceb2e36d.png)

Fish traps stopped working for a while. 

Then when removing and placed again seemed to bug out the water.

Now trees growing underwater.

Fish animations working but fish don't move from block. Will sink occasionally.

**Comment by soulnet** [comment]
Beta 9.0.1

**Comment by beastyn** [comment]
@soulnet Thank you for the report.
It can be fresh water detecting issue too.
After replacing fish trap is it working fine?

Please provide log file. Instruction <https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file>

Also it would be nice to see a screenshot with a map showing the fresh water layer.

**Comment by soulnet** [comment]
First location and map as requested.

![red dot](https://user-images.githubusercontent.com/36501028/93070748-9c9f5f00-f6c2-11ea-9c0c-6d262a05a72f.png)
![map1](https://user-images.githubusercontent.com/36501028/93070788-aa54e480-f6c2-11ea-819d-fad1658d3896.png)

Second location and map as requested.

![Map2](https://user-images.githubusercontent.com/36501028/93070866-c193d200-f6c2-11ea-8f2f-cf6542b0a961.png)
![red dot 2](https://user-images.githubusercontent.com/36501028/93070904-cb1d3a00-f6c2-11ea-9c65-8e7c2b6e0cd3.png)
![underwater](https://user-images.githubusercontent.com/36501028/93070918-cfe1ee00-f6c2-11ea-91af-0bb8555b21d4.png)

Log Files Attached. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5217566/Player.log)

2nd Log Link (70mb)

https://drive.google.com/file/d/1ddKTkVANQRgYxZlYouCT6EpQglYwzPf1/view?usp=sharing

**Comment by soulnet** [comment]
UPDATE: This seems to be related to https://github.com/StrangeLoopGames/EcoIssues/issues/18291. 

When built under a 'bridge' they cease to function and it seems to be that anything built under the bridge becomes dry as opposed to wet.

Have tested traps in locations not under bridges and works as normal.

This request can be closed or merged.

**Comment by beastyn** [comment]
@soulnet Thanks for the additional info. Yeap, looks like #18035 and #18291 . Merging it.
