### ISSUE TITLE
USER ISSUE: Hosting Private Server disconnects and crashes.

### ISSUE THREAD

**Issue by Cliffmchrist** [StrangeLoopGames/EcoIssues#18196]
**Version:** 0.9.0.1 beta
Hosting private server via the main menu's 'Host a World' option, other members on the server *USUALLY* get disconnected every 5-10 mins, at one point one of the non-host players stopped disconnecting, but other players were still having the issue. Host internet is a stable 200-210Mbps Down, 20-22Mbps Up, depending on time of day, and is a wired connection. After this issue repeated for several hours, the host player, me, disconnected and received an error, the first time I tried to report this, I lost the error and couldn't find the code, this is the second time it has happened and now I was able to copy the code via the crash message.
**Steps to Reproduce:**
Unknown, was not having these issues before 9.0 updates

**Expected behavior:**
Stable connection for players and no crashes when hosting a server via in-game menu.

**Actual behavior:**
Repeated disconnects and crashes.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Providing the requested files from the host as well as from one of the non-host players, the Host's files have HOST added to the name. Also providing the crash data that was copied to the clipboard.

[Eco crash data.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5212076/Eco.crash.data.txt)

[Player - HOST.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212072/Player.-.HOST.log)

[Player-prev - HOST.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212074/Player-prev.-.HOST.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212079/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5212081/Player-prev.log)

**Comment by beastyn** [comment]
@Cliffmchrist Thank you for the report.
What is PC specification for the host machine and used OS?

Did players have issues with chopping the trees, hunting animals? 
Did server restart help?

If ti possible, can you provide a server log (with dump) and save file?

**Comment by Cliffmchrist** [comment]
Host PC Specs:
CPU: Intel I7-8750H @2.2GHz
GPU: Nvidia GTX 1060
16 Gigs Ram
Windows 10, 64bit

Players have no issues while on the server, server restart did not help, even tried disabling firewall and antivirus.
One of the players, the one I send the logs for last time, was able to connect for hours without any disconnects Yesterday, while other players were still suffering the disconnects. 

[log_200911093908.log](https://github.com/StrangeLoopGames/EcoIssues/files/5228544/log_200911093908.log)
[log_200913014950.log](https://github.com/StrangeLoopGames/EcoIssues/files/5228545/log_200913014950.log)
[log_200914022809.log](https://github.com/StrangeLoopGames/EcoIssues/files/5228546/log_200914022809.log)
[log_200911093358.log](https://github.com/StrangeLoopGames/EcoIssues/files/5228547/log_200911093358.log)

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5228578/Dump.zip)

Hope this helps

**Comment by beastyn** [comment]
From all of these logs the reason of your crashes can be from this issue #18113.
And maybe something else for different players.
But fix for animals will be later and need some time.

In general it seems that you have a lot of animals with corrupted routes and if a player sees them a client can be disconnected.
I will merge this task to   #18113 and close it but feel free to write here, I will answer.

I am sorry for the inconvenienceю

**Comment by Cliffmchrist** [comment]
so the animals are causing the issues? well, time to go on a murder spree XD

I'm curious as to why the one play was having no issues then for a while? what happened to make them special, and can we maybe force that onto all our players somehow?

Is there a way to find our which animals are corrupted and kill them? is there a series of commands I can put in as admin and server owner to kill the animals and reset them?

**Comment by Cliffmchrist** [comment]
Or would starting a new map help?

**Comment by beastyn** [comment]
You can try to watch around people who were disconnected, but this error does not contain coordinates.

New generation can help, but it does not mean you won't have it. There maybe a bunch of conditions and we are still in the process of investigation and fixing. But yes, you can save your current world and give it a try with the new one.

Killing animals can help but again, it doesn't mean that after spawning other animal won't have it.
Its pretty strange that in your case you have so mach players with this issue, it should be pretty rare. Maybe it can br something else but first we need to remove visible one with particular error.

**Comment by Cliffmchrist** [comment]
ok, thank you for getting back with me, I'm going to have them try to jump on after killing all animals and see if that corrects the error, if not, I'll get the logs and send them

**Comment by beastyn** [comment]
@Cliffmchrist Oh, that will be a great help. Thank you.

**Comment by Cliffmchrist** [comment]
ok, I've been trying to figure out how to kill all the animals, is there a command to do this? or do I need to just give everyone a bow?

**Comment by beastyn** [comment]
Hmm, we have a command for it just for devs, so you can't use it if you don;t have a devtier.
Only /sim oneshot for admins

**Comment by Cliffmchrist** [comment]
just messaging back to see if there was any update on this issue or estimated time frame before it gets fixed, me and my friends can't play till this is resolved.

**Comment by beastyn** [comment]
@Cliffmchrist Its in the progress. Maybe will be able to add it to the hotfix next week. Did not you try to launch a new server?
Is it private?
