### ISSUE TITLE
[Server] 9.0.1 Server crash on adding demographic law passed 

### ISSUE THREAD

**Issue by loopyman** [StrangeLoopGames/EcoIssues#18194]
First want to say this feels is the most stable and efficient build yet. <3
Our server has been operating great since beta 9.0.1 hot fix release. Unfortunately we encountered two EcoServer.exe crashes within 12 hours today and I'm providing information here for both crashes. I'll focus on the first one which we know occurred immediately following a law passing to create a new 'Citizen' demographic. The second seemed to happen "randomly" while users are playing. Our server has approx 73 active citizens with about 20-50 playing at any time. Unfortunately with this many users its difficult to nail down exactly what was going on. There are no mods on this server and it is hosted public.

I am unable to reproduce these bugs, perhaps the second crash was related to the first, perhaps not. I'll let the interpreters decide :)

(Server time CDT)
The server has crashed twice requiring the EcoServer.exe to be started again.
First crash occurred around: 9am
Second crash at 1:55pm

Attached is all dumps this server has generated since launch. 
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5211831/Dump.zip)
All server logs:
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5211832/Logs.zip)
Game-Log.db
[Game-log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5211834/Game-log.zip)
Configs
[Configs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5211840/Configs.zip)

Server Stats, 6H showing last crash just before 14:00
![grafana](https://user-images.githubusercontent.com/23000658/92981166-5649c600-f45e-11ea-9adb-60f9e2d003e2.png)

I hope this is enough data. 'Game.db' and 'Game.eco' are too large for github. I can host a download link for it if its needed. 

Thanks!

**Comment by IcedForge** [comment]
Host it anywhere is fine, having the game files would be great to narrow down this issue.
