### ISSUE TITLE
Land Claim near or at 0,0 breaks trees.

### ISSUE THREAD

**Issue by ChrisMayhew** [StrangeLoopGames/EcoIssues#1819]
On my server we encountered a bug that when I claim land at 0,0 or near 0,0 no one else on the map can chop trees, It's as if I own all the land on the server.

The only way to solve this was for my to unclaim the plots.

Version 5.6.1

**Comment by fusspawn** [comment]
Something to note it only effected tree's other structures and actions continued as normal. 

I tried claiming some extra land whilst it was broken. and could not even cut tree's on the land I owned.

**Comment by ChrisMayhew** [comment]
![treebug](https://user-images.githubusercontent.com/9767399/28755541-418b73f2-7555-11e7-9367-af039ca2ca6e.png)

I believe that this piece of the tree may be causing this bug. I can't, however, delete it or pick it up because when I do I get crashed out of the game.
