### ISSUE TITLE
/ff works, /ff 0 will only stop for admin not other players

### ISSUE THREAD

**Issue by Shoe73** [StrangeLoopGames/EcoIssues#18191]
I issued /ff to fast forward the time.  I issued /ff 0 to stop the fast forward, but it did not stop for the other players.

**Comment by WeaselDog** [comment]
Thanks for reporting this. We have a fix now ready for next update.

**Comment by Lagicrus** [comment]
> I issued /ff to fast forward the time. I issued /ff 0 to stop the fast forward, but it did not stop for the other players.

I had this same issue earlier and even when I did `/ff 0` it still was spamming through my research time :/ (Was the only player connected and the only admin)

**Comment by WeaselDog** [comment]
@Lagicrus Sorry about that. We do have a fix for this, but it has not made it into the game yet.

**Comment by Lagicrus** [comment]
> @Lagicrus Sorry about that. We do have a fix for this, but it has not made it into the game yet.

Thanks :) Happy to hear it. My "solution" was enabling sleep fast forward temp and using that.
