### ISSUE TITLE
CLIENT ISSUE: Client crashes, reproducible; play game, wait for crash

### ISSUE THREAD

**Issue by MacKenzieTStout** [StrangeLoopGames/EcoIssues#18193]
Only getting about 15 minutes of game play max before Eco 9.0.1 crashes
Have tried multiple servers and reducing graphics quality; no effect on preventing crashes

**Comment by D3nnis3n** [comment]
Can you attach the crashes and the logs?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by MacKenzieTStout** [comment]
![image](https://user-images.githubusercontent.com/1253873/93008079-9b84fb00-f525-11ea-8df3-a202b9b1c214.png)

No log available for server.

**Comment by MacKenzieTStout** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5213488/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213489/Player-prev.log)

**Comment by beastyn** [comment]
@MacKenzieTStout thank you for the report. Can you uninstall the game in Steam and reinstall it?
Also please provide Player.log with your next play session attempt.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
