### ISSUE TITLE
USER ISSUE: Massive memory leak when connecting to server cca 2GB per second

### ISSUE THREAD

**Issue by Dzemy** [StrangeLoopGames/EcoIssues#18190]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Connect to any server or create own.
Last playable version for me was 0.8 (playtime 50h)

**Expected behavior:**
Game start

**Actual behavior:**
Game crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**logs**

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211519/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5211520/Player-prev.log)

**Comment by beastyn** [comment]
@Dzemy Thank you for the report.
1) Can you provide more accurate steps how are you creating a game (the new game)?
2) Can you provide logs from server after creating a new one?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world
3) What is your PC specification and OS?

**Comment by Dzemy** [comment]
1. I just create a new word with default setting, or join to any server. Then after creating the character and save it game crash. 
![image](https://user-images.githubusercontent.com/21079305/93171826-1880c200-f72a-11ea-8fb8-e4d635372219.png)

2. There is server log.
[log_200915080021.log](https://github.com/StrangeLoopGames/EcoIssues/files/5222766/log_200915080021.log)

3. 
Windows 10 Pro N (I have Media Feature Pack additionally downloaded) Version 2004
MB: msi z97 gaming 5
Intel core i5-4690
AMD Radeon R9 290
Crucial Ballistix Tactical DDR3 16GB

**Comment by redwyre** [comment]
Is this still happening with 0.9.0.3?

**Comment by redwyre** [comment]
Also if it still happens with a local server can you show the details tab from task manger? (just sort by name and you should see eco and ecoserver together)

**Comment by Dzemy** [comment]
Yes, is still happening. v 0.9.0.3
![EcoTaskManager](https://user-images.githubusercontent.com/21079305/94857679-2f195f80-0432-11eb-970c-d10aa1ada931.gif)

**Comment by Dzemy** [comment]
0.9.0.5 Still the same

**Comment by redwyre** [comment]
How's 9.1?

**Comment by Dzemy** [comment]
Unfortunately still the same on 9.1.2.

**Comment by mirasrael** [comment]
Hi @Dzemy 
Do you see any improvements on latest builds? If you still have the issue can you please provide the server save file on which you have this issue.

**Comment by Dzemy** [comment]
I reinstalled the computer and it's working now, if it reappear I'll let you know. Thanx a lot.

**Comment by mirasrael** [comment]
@Dzemy Thanks for answer! Closing it for now, feel free to comment here if issue reappear.
