### ISSUE TITLE
[0.9.0.1] store quantity not updating.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18195]
Steps to reproduce
Setup store, add item and set buy limit.
Close store window now reopen and change item amount. It will reset.
(Value works fine but not quantity)

**Comment by IcedForge** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5217334/Player.log)


NullReferenceException: Object reference not set to an instance of an object.
  at TreePart.Start () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 

Trying to update quantity field.

**Comment by IcedForge** [comment]
https://i.gyazo.com/fbe634d7b8660eeba37a302358e9ba52.mp4

**Comment by beastyn** [comment]
For me:
1) Setup a store.
2) Add 3 items into purchasing list
![bandicam 2020-09-14 14-44-47-862](https://user-images.githubusercontent.com/27898520/93072275-9a290f00-f69a-11ea-9b70-bf17ae19f8be.jpg)
3)  Reconnect/ Now:
I can't give a new quantity for the first one. It's always zero.
I can give a lower number for the second and the third.

4) Reconnect
The first one will be fixed.
The second and third will have the same bug.

**Comment by serpopov** [comment]
no need to reconnect, could use toggleuicache
