### ISSUE TITLE
The 1 FPS problem

### ISSUE THREAD

**Issue by UselessAqua98** [StrangeLoopGames/EcoIssues#18209]
Also made the OS lag, needed to restart the PC to fix that.
[log_200912124209.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213048/log_200912124209.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213049/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213050/Player-prev.log)

**Comment by D3nnis3n** [comment]
Problem fixed.
