### ISSUE TITLE
[9.0.1] Small Tables are unobtainable

### ISSUE THREAD

**Issue by bswan** [StrangeLoopGames/EcoIssues#18206]
Was going to craft some more small tables(world migrated from 8.3.3, so we have some already), stations where small tables were crafted before now only list full-size 2x1x1 tables. 
Picked up one of the already crafted small tables - it does not have section named 'Crafted At' on it's description.
Regardless of that you still can pick up and place it normally.

**Comment by D3nnis3n** [comment]
Small Tables were removed from the game with the furniture revamp, so them not being craftable is intended. The ones you still had from migration stay.
