### ISSUE TITLE
[0.9.0.1] Wage payment issues

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18215]
Ran into an issue on White Tiger server with wages not being paid properly and when checking why its stating "Invalid account"

![Screenshot_320](https://user-images.githubusercontent.com/24981362/93006431-60ea8500-f55c-11ea-9748-91626e4e92ae.jpg)
Also noticed that the overlay mouse over description does not correspond to the actual information set in the title.
Where is set to pay 6.5$ per hour but according to the description it says 10$
The title manager that has set the wages is also manager and authorized on the bank account in question as well.
![Screenshot_321](https://user-images.githubusercontent.com/24981362/93006434-647e0c00-f55c-11ea-88ac-b7ef86062d2e.jpg)

**Comment by johnkslg** [comment]
@IcedForge can you reproduce this and attach a world file?

**Comment by olegshegai** [comment]
Or maybe steps to reproduce?
Is it an old account (in other words, may it be related to migration)?

**Comment by IcedForge** [comment]
Have not been able to replicate it and have not seen it since the issue with the one wage setting on white tiger initially
