### ISSUE TITLE
USER ISSUE: Whole stack moves when only a fraction selected

### ISSUE THREAD

**Issue by AliaAnor** [StrangeLoopGames/EcoIssues#18218]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Shift click a large stack with an odd number like 61
2. Change from x1 to x5 or x10
3. Slide the bar over until it says 60
4. Move the items

**Expected behavior:**
Move 60 units

**Actual behavior:**
Moves the whole stack (in this example, 61)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
I am not having any luck replicating this, is this a specific item type? Specific container or any item in anything?
Need some more information to proceed.

**Comment by AliaAnor** [comment]
Hmm. I can't replicate it either. Next time it happens I'll look to see what is different from my steps.
