### ISSUE TITLE
USER ISSUE: crash on white tiger

### ISSUE THREAD

**Issue by hvm2hvm** [StrangeLoopGames/EcoIssues#18214]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
I was accessing a carpentry table

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client, Boolean doAllParams)
   at Eco.Shared.Serialization.BsonManipulator.ToBson(Object val, INetClient client, Boolean useReflection)
   at Eco.Core.Controller.ControllerManager.PackageValue(IMvcNetClient boundClient, Object value, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, Int32 nameID)
   at Eco.Core.Controller.ControllerManager.GetChanges(IMvcNetClient client)
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__70_1()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@hvm2hvm Thank you you for the report. Can you provide a full log for the session where you had a crash?
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by hvm2hvm** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5218383/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5218384/Player-prev.log)

**Comment by beastyn** [comment]
I am going to take this on for the base for this Crash error.

Players just have it from time to time. Just playing.
1) It can be connected to civics. like here #18194
2) Or just swimming like here 
3) Just anything like opening table, collecting plane fibers #18198

**Comment by SlayksWood** [comment]
> Welp, its been awhile since I have been active on the Github as I've been moving and such but I AM BAAAAACK!!!! Of course, as always my friendly and lovely Devs, I bring bugs, crashes, and other problems that need to be splatted! Hope you are ready for the ever detailed reports from the Graesyn Line!
> 
> **Steps to reproduce:** Cut down an Old Growth Redwood so that it falls onto a road comprised of Stone Road and Stone Ramps
> **Expected behavior:** Tree Falls and Has no Issue
> **Actual behavior:** Crash to Main Menu
> **Providing Log files:**
> [redwood crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5289585/redwood.crash.txt)
> [System Specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5289588/System.Specs.txt)

**Comment by Sarah-Graesyn** [comment]
So, I have to honestly admit I am not at all sure what caused this one @SlayksWood I was AFK when it crashed but when I got back to the screen I grabbed the text and copied it into a txt file for ya'll, figured you would be able to decipher it.

[unknown crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5297622/unknown.crash.txt)

**Comment by Sarah-Graesyn** [comment]
**Steps to reproduce:** Edit a Road District Map
**Expected behavior:** Save the Map and have no issue
**Actual behavior:** crash to main menu
**Providing Log files:**
[Road Edit.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5308818/Road.Edit.txt)

**Comment by mirasrael** [comment]
I added logging in https://github.com/StrangeLoopGames/Eco/pull/6984 for this issue, so we will be able to identify where it happens, but it actually may happen to any non thread-safe enumerable

**Comment by SlayksWood** [comment]
still an issue in 0.9.1:
> I was building some highway on WT when the server booted me out with this log:
> 
> [enumeration.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5486208/enumeration.txt)

**Comment by mirasrael** [comment]
Detected case from https://github.com/StrangeLoopGames/EcoSuggestions/issues/1326:
`Error during packaging property 'PlayerCountAtEachLevel' of 'Eco.Gameplay.Skills.SkillTree'`

**Comment by mirasrael** [comment]
Fixed issue with PlayerCountAtEachLevel. Probably it was cause of original issue. If we will have another similar crashes then we should check which property causes this.
