### ISSUE TITLE
Trees dont show as full grown without disconnecting and relogging

### ISSUE THREAD

**Issue by Equitime77** [StrangeLoopGames/EcoIssues#18210]
I noticed this in the last version. Where trees still appear as growing even tho as soon as you reenter the game they show as fully grown.

**Comment by beastyn** [comment]
@Equitime77 thank you for the report.
Did I get you right:
You are planting a tree and it does not change it's model in time but soil sampler shows it like fully grown?

**Comment by SlayksWood** [comment]
merged to #9057
