### ISSUE TITLE
USER ISSUE: Work Parties Double-Count Resources

### ISSUE THREAD

**Issue by 0600Zulu** [StrangeLoopGames/EcoIssues#18229]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Create a work party for crafting an item that consumes resources over time (e.g., logs -> hewn logs). 

2. Submit resources to that work party that do not complete the work party (e.g., submit 20 logs to a hewn log party that needs 100 logs total). The excess logs will go into a nearby inventory. 

**Expected behavior:**
The items then consumed from the nearby inventory should not count towards the work party (since the provider was already credited for the contribution).

**Actual behavior:**
As soon as the excess items are needed for the recipe, they are counted as being added % to the work party, even though they were already counted.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5214942/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5214943/Player-prev.log)

**Comment by beastyn** [comment]
@0600Zulu Thank you for the report. We are discussing it here #18030
