### ISSUE TITLE
USER ISSUE: Nail production in Anvil doesn't take all resources from hand when stacking multiple.

### ISSUE THREAD

**Issue by XmYx** [StrangeLoopGames/EcoIssues#18220]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Try to make more then one set of Nails in an Anvil while holding Iron Bars.

**Expected behavior:**
Taken all neccesary Iron Bars for the Nails (Labour was done)

**Actual behavior:**
Took only one Iron Bar, had to handfeed it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Intended, there is no "hammerspace" aka full inventory in work appliances anymore, to craft more then 1 item in a single work order you need to provide a storage space for the appliance to take materials out of.

**Comment by XmYx** [comment]
Copy, thanks boss : )
