### ISSUE TITLE
USER ISSUE: Law trigger "Add Labor To Work Order"

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18228]
In laws in triger "Add Labor To Work Order", property "Labor profession", in addition to professions, also shows skills in the filter, and property "Labor Skill", in addition to skills, also shows professions.

![image](https://user-images.githubusercontent.com/17272063/93025420-774d1b00-f606-11ea-9042-6dd974c687dc.png)

**Comment by IcedForge** [comment]
![Screenshot_359.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/5def2f60-3adf-4f9e-babe-f8687a06a931)
![Screenshot_358.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/84c48ab3-8452-4a06-9a89-7d95d845daf7)

It lists professions as stated by the description, but i do not think this is really necessary; as if you have the skill unlocked you automatically have that profession as well and is mostly just confuses for users.

Possible solutions is either to remove "With Labor Profession" completely, or fix the request function and make sure it only lists the skills in skill and professions in professions and not both.

**Comment by Artem314159** [comment]
It seems to me that the best solution is to merge these two properties into one.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop-176

Profession and Skill are now separated. For With Labor Profession, the filter UI now only shows profession and respectfully same behavior with Labor Skill.

Resolution: Closing.
