### ISSUE TITLE
5.6.2 staging 8802b6fc precipitous water level rise!

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#1822]
Migrated world from 5.6.1 to 5.6.2 staging 8802b6fc and water levels have risen ridiculously high. Our entire complex at the top of a mountain is now unterwater. There are very few bits of land above water.

game.eco is at
https://drive.google.com/open?id=0By3yTnmDe0uldXRzQnFtOUJKT1k

**Comment by craig-jong** [comment]
To be honest, this is a bug we've seen before but have no idea what the cause is. I'll take a look - I suspect its something up with migration, though.

**Comment by MarjieAVolk** [comment]
Oh, maybe it isn't an Alpha 6 priority bug in that case
