### ISSUE TITLE
[0.9.0.1] Title: Successor not removed on Succeeding a title.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18239]
When a Title holder is removed, and is replaced by a successor it should remove the original title of the successor.

Example: White Tiger Government system
President - Elected title by basic election. - Successor( Vice President )
Vice President - Elected title by basic election. - Successor(none)

When President is no longer eligible(Has Requirement for title holder: Active)
it removes player from title and replaces title holder with player from Vice President BUT it does not remove Vice President title which should be automatically done on inheriting a title via succession. ( currently worked around by adding NOT Vice President as requirement as well )

**Comment by SlayksWood** [comment]
Step to reproduce:
- create a nerw title in registrar and add 2 player to users here:
![image](https://user-images.githubusercontent.com/45708377/116857148-042ffd80-ac05-11eb-87d7-d378421cc387.png)
- create 2 elected title. President and Vice-President:
![image](https://user-images.githubusercontent.com/45708377/116857324-43f6e500-ac05-11eb-974b-603acfe0c171.png)
![image](https://user-images.githubusercontent.com/45708377/116857439-7d2f5500-ac05-11eb-9445-f937013187fc.png)
- start and win election for both title.
- Player 1 (Devqa) became a president, Player 2 (Slayks) became a vice-president:
![image](https://user-images.githubusercontent.com/45708377/116857750-f9c23380-ac05-11eb-8b87-4c2035638e52.png)
- So As far as I understand If Devqa lost Required Title, then he should be removed from President, and Slayks will be President and he should be removed from Vice-President. @WeaselDog @johnkslg  I would actually reconsider this point - in my opinion, this is a complication that will cause a lot of problems in the laws. So I add a Triage label.
- remove devqa from required title user:
![image](https://user-images.githubusercontent.com/45708377/116858064-781ed580-ac06-11eb-9617-9d3a0abcda9d.png)
- /civics ticknow:
- So Slayks ocupants 2 Titles.
![image](https://user-images.githubusercontent.com/45708377/116858143-94227700-ac06-11eb-9a84-1e0c829d33fa.png)

**Comment by IcedForge** [comment]
After a lot of experimentation and deep diving into the system since the post was initially made, i believe it is potentially better to just use the current system as the way we solved it on tiger is to set conditioning for title holder as the removal mechanic.

So 
Vice president succeeds to president

Vice president title "Required of title holder = Not president"
This then removes the previously title by succession as the vice president is now also president, on the next tick it will remove him from VP office since he is now holding a title that is prohibited by his office.

**Comment by WeaselDog** [comment]
Going to close as it seems we are fine with the current behavior. Please reopen if a change should happen.
