### ISSUE TITLE
[0.9.0.1] Selecting multiple titles in constitution.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18233]
More a suggestion then an issue but it is one at the same time.
Would like a way to select multiple titles at the same time under constitutional rights instead of having to add a article for each specific title
even if it has the same rights and rules as another title.
As an example.
4 different groups of players all holding area titles representing their area, currently i would need to add 4x articles for the same permissions.

**Comment by tomsseisums** [comment]
@WeaselDog @IcedForge an issue this old - should it be fixed in `staging` or `develop`?

**Comment by IcedForge** [comment]
Probably safest to do it in develop, since its simply adding more articles instead

**Comment by TwixterZ** [comment]
feature tested and confirmed as of 9.4 Staging 1987 (tested against Capitol and Amendments)

Players now able to select multiple aliases for civic "executor" or "proposers"
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/fbab6f76-90f4-4b26-8142-acd6e4798aab)
