### ISSUE TITLE
[0.9.0.1] Cannot select Hewn Door variants

### ISSUE THREAD

**Issue by QUEWEX** [StrangeLoopGames/EcoIssues#18235]
Other hewn furniture at the carpentry table (bench, chair, table) have the Advanced Crafting option to select a variant; however, the Hewn Door project does not.

**Comment by itsmepete** [comment]
The same goes for Mortared Stone Door (and probably other Door Types). I guess that is intended.

**Comment by beastyn** [comment]
@QUEWEX Thank you for the report.
We do not have them yet. But will soon.
