### ISSUE TITLE
USER ISSUE: Mint UI issue

### ISSUE THREAD

**Issue by Twerk17** [StrangeLoopGames/EcoIssues#18232]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Place a Mint on your claim
2. Give access to someone who does not have access on your claim to mint currency
3. Give that person a title that allows treasury perms and all other government money perms
4. Ask them to mint a currency

**Expected behavior:**
Allowed them to mint a currency

**Actual behavior:**
It allows them to do every step but name the currency. Once given perms on the claim currency minting was possible.  UI missing to explain why they couldnt?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![image](https://user-images.githubusercontent.com/41242818/93030978-2e409b00-f5f5-11ea-8404-aa973a4c3a24.png)

**Comment by IcedForge** [comment]
Need a different error type / text for informing the player that they are not autherized to create a currency as they only have "use" rights.

**Comment by IcedForge** [comment]
![Screenshot_55](https://user-images.githubusercontent.com/24981362/94259572-fa3b7300-ff2e-11ea-8860-955483e93f7f.jpg)
Can we take that error msg you made and have it as a static visible thing on the ui as long as there is no currency?
Once you miss that msg now it is hard to know why the craft button is not clickable? Or have the error show on "craft" button press?

**Comment by evil-morfar** [comment]
Just encoutered the same issue.

![image](https://user-images.githubusercontent.com/10189576/94903121-94ed0200-0499-11eb-9837-a4429d34804d.png)
It feels like "Ignore Auth" should do exactly that, and give use rights as well.

**Comment by IcedForge** [comment]
This should only be displayed if NOT authorized on the claim, currently visible when a user can create currency ( not just owner of the mint itself ).
https://cdn.discordapp.com/attachments/754950557428351027/762950644058292234/unknown.png 
Also shows after a currency is created until UI cache is cleared.

**Comment by IcedForge** [comment]
Found some more related issues here #18786

**Comment by serpopov** [comment]
This is currently not possible in 9.2, should be pushed to 9.3 and will be auto fixed, @WeaselDog

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/108055442-0a302c80-7061-11eb-96cc-e652c6baa987.png)
