### ISSUE TITLE
USER ISSUE: Culinary Research Paper Basic Meat

### ISSUE THREAD

**Issue by StelanS** [StrangeLoopGames/EcoIssues#18231]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Starting without the skill
2. Cancelling the project

**Expected behavior:**
I should get my meat back

**Actual behavior:**
wont get back the meat

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
https://i.gyazo.com/b29544023f2ad2f3cba78b89d7a7ece7.mp4
Not getting an issue with returning of items, do you have any inventory linked to the research table?
Have you experienced this multiple times or just a one time occurrence?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
I guess meats were added to another project.
