### ISSUE TITLE
USER ISSUE: вылетает игра

### ISSUE THREAD

**Issue by teraruga69** [StrangeLoopGames/EcoIssues#18246]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
при открытии карты игра зависает и выдает ошибку eco - unity 2019.4.9f1_50fe8a171dd9

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@teraruga69 Спасибо за отчетю
Хотелось бы получить:
1) Логи с игровой сесии, где игра вылетела
2) PC спецификацию и опрационную систему
3) Может быть более подробное описание ошибки сохранилось в журнале событий?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
