### ISSUE TITLE
USER ISSUE: Food indicator not showing up when tutorial is skipped

### ISSUE THREAD

**Issue by IanMoroney** [StrangeLoopGames/EcoIssues#18248]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Skip the tutorial by pressing X, no more items to skip. Food bar does not show up.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@IanMoroney Thank you for the report.
It's because of the skipping in some particular order.
Press Esc. Go to the tutorial tab. RestartTutorial. Press X on one of the tutorials and click checkbox (Skip all tutorials). Then Yes.
It should fix the issue.
Write here if it did not help.

**Comment by IanMoroney** [comment]
Hi Anna, this did not help.

I found that the food tutorial only shows up when your calories are near 0
(I.e. the first time you are unable to do work)

I would suggest if you're skipping through tutorials, you would expect to
get the food tutorial regardless of the state of your calories, so you can
skip it and get the overlay.

**Comment by beastyn** [comment]
Well, it should have worked like here #15215
So full restart and

**Comment by IanMoroney** [comment]
Yes, this behaviour is the same as #15215.
If you skip individual tutorials, you're left without the calorie widget.
The quest will only begin when calories reach near 0, so no work can be performed.
as per @johnkslg 's comment:
https://github.com/StrangeLoopGames/EcoIssues/issues/15215#issuecomment-606885342
It would be a better experience if the food tutorial showed up after skipping one of the other tutorials, so you're not stuck there wondering why the calories aren't showing up, and there's no further prompts.

**Comment by beastyn** [comment]
@IanMoroney yap, it will be improved one day, But were you able to bring the food bar back?

**Comment by IanMoroney** [comment]
Yes, unintuitively.

**Comment by beastyn** [comment]
@IanMoroney ok, great. Then I will close it as we have issue for the tutorial fix.
