### ISSUE TITLE
5.6.2 staging 8802b6fc Blast Furnace exhaust

### ISSUE THREAD

**Issue by Ciannicay** [StrangeLoopGames/EcoIssues#1824]
The exhaust of the blast furnace is not accessible as it is located inside the object.
i did completely cover it in iron pipes but i still says disconnected and does not show any of the pipes creating a connection other than with other pipes

Pipe object that resides inside the object is aligned to front instead of back - maybe thats the bug.

connecting to it from below doesnt work either

**Comment by SeanAtr0n** [comment]
will be fixed in next staging build
