### ISSUE TITLE
[0.9.0.1] Improvements to Constitutions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18247]
We are currently having a constant catch 22 that interrupts and or confuses a lot of players setting up the new government systems with being forced to ratify a initial constitution without actually having any options to customize it, forcing them to use a massive amounts of constitutional amendments instead to correct or change this.

![Screenshot_373.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/78852eeb-3edf-4857-9448-374fb6ff2007)

Some player feedback regarding the issue.
https://cdn.discordapp.com/attachments/448531486313021459/755094141695950950/unknown.png
![Screenshot_376.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/731cbc34-f7ba-4d12-a584-6d719f00a3f6)

Also a lot of feedback regarding any updates done to titles, laws etc cannot be named the same even if they "update" their previous parts which results in President 2, President 3, President 4, President 5.

As a good  point by some of the player feedback in particular.

"and I can see how using "version numbers" in titles might be kind of unsightly
"Treasurer v1.4 reports to President v3.1"

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/16182
@IcedForge Please add the relevant information there

**Comment by WeaselDog** [comment]
Reopening as it is useful information that was not merged

**Comment by johnkslg** [comment]
@IcedForge whenever you change something its supposed to update other uses of it. Verified this is working in latest staging:
![image](https://user-images.githubusercontent.com/3536496/93840094-0334f780-fc44-11ea-892f-cf9dc31899de.png)

If youre not seeing this working, thats not an improvement needed, thats a bug, can you file it separately with repro steps?

**Comment by SlayksWood** [comment]
I added suggestion from our discord chat here to not forget:

What do you think about changing interaction between Capitol and Amendments? Now the constitution contains only basic articles. If I add or change article then new article will in Amendments. But I think Capitol should have all articles. 
Amendments should be like Executive Office. You propose new article in Amendments. But then it should be in Capitol.
So Article will be like:
![image](https://user-images.githubusercontent.com/45708377/93879383-49da2e80-fce4-11ea-9f8c-e4e07cf8fe4c.png)
And new article should appear in Constitution
![image](https://user-images.githubusercontent.com/45708377/93879412-552d5a00-fce4-11ea-8492-d9ec0e1545a2.png)
Removed articles will be in bottom and we can hide them by some button:
![image](https://user-images.githubusercontent.com/45708377/93879456-67a79380-fce4-11ea-8be5-0d34e6dfe2d1.png)

**Comment by johnkslg** [comment]
You can now create packages in a single election. Give this a try in 9.1 and let me know how it goes, we can iterate further from there in a new issue.

**Comment by IcedForge** [comment]
Should be fixed in 9.1 Any related issues can be made into a new one if thats the case for easier tracking as this contained a lot of different parts which has been addressed in the current devbuild
