### ISSUE TITLE
ServerCrash TargetInvocationException

### ISSUE THREAD

**Issue by Regitus** [StrangeLoopGames/EcoIssues#18242]
Version 9.0.1
No Mods
After restart of the server it crashed. There were no dumps in the previous uptime of the server. The reason of the restart was a problem with the server not responding unregulary for 30+ seconds and then catching up.

After a few errors at different points of the startup it could load up the server and it is now working. All of  them had the same wording like in this ecodmp file.

[ServerCrash TargetInvocationException 09141333.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5219730/ServerCrash.TargetInvocationException.09141333.ecodmp.txt)
[log_200914061314.log](https://github.com/StrangeLoopGames/EcoIssues/files/5219733/log_200914061314.log)
[log_200914060840.log](https://github.com/StrangeLoopGames/EcoIssues/files/5219729/log_200914060840.log)

**Comment by beastyn** [comment]
@Regitus thank you for the report, Please provide PC specification and OS for the host machine.
Was you server closed properly before you were trying to launch a new instance of it?
Did you manage to launch a backup&

**Comment by Regitus** [comment]
For more detailed specifications of the server machine, you would have to ask PingPerfect. But probably this is already known. My service there has 4GB RAM.

As far as I could tell the server has been shut down normally. The last actions minutes before shutdown were missing.
It is important to know that the machine my server was on was causing problems at that time. So it could be that it is related to that.  
PingPerfect moved my server to another machine overnight because of this reason.

I didn't use a backup to load it because it would just boot up after a few crashes.

**Comment by beastyn** [comment]
@Regitus do you have any issues right now with launching?

**Comment by Regitus** [comment]
No. I don't have any issues right now.

**Comment by beastyn** [comment]
I will close the issue. Feel free to write here if you have this issue again and can provide additional information.
