### ISSUE TITLE
USER ISSUE: Cant Choose Road Object at Road Build Contract

### ISSUE THREAD

**Issue by Lars225** [StrangeLoopGames/EcoIssues#18251]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
If you create a Contract to build roads between construction posts you can not pick any other Build Material as dirt.
I Try to klick on the Dirt but no Menue opened.

**Expected behavior:**
Fix the Button pls

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, all at Vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Lars225 Thank you for the report.
We have it in here #17567
