### ISSUE TITLE
Unclaim Abandoned not working

### ISSUE THREAD

**Issue by Calura** [StrangeLoopGames/EcoIssues#18253]
Unclaiming abandoned properties is not working. We have a law in place that is supposed to unclaim the property of anyone that has been placed in the "Abandoned" demographic. We changed the demographic on the actual server config files to reduce abandoned to 4 days. People are appropriately being moved in to that demographic. But when the server "checks" for them every 6 hours to unclaim their property, it isn't happening. So I tried to do it manually using the unclaim abandoned admin command (/property unclaimabandoned 4) and it still didn't work.

Here's the screenshot showing it SAYS I unclaimed properties, but I'm standing on one that should have been unclaimed and it's still claimed.

With the shortage of trees that we start out with, there is a HUGE need for logs and wood products right now. We were HOPING to get it back from these players who just aren't playing and helping to advance the community. But apparently we can't!
![unclaimnot](https://user-images.githubusercontent.com/53465919/93150516-5f899b80-f6c7-11ea-8f69-5e127262869b.jpg)

**Comment by beastyn** [comment]
Can be related to #18059

**Comment by Calura** [comment]
Yes, I got the law to work, but the admin command still does not work.
