### ISSUE TITLE
USER ISSUE: Contract Board: Can't Change Road Blocks

### ISSUE THREAD

**Issue by Titanborn** [StrangeLoopGames/EcoIssues#18254]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Make a contract to build a road.
Try to change the road block (yes stone roads have been researched and are in use)
No selection for other blocks presented and can't change from dirt.

**Expected behavior:**
Should be able to select any researched road type.

**Actual behavior:**
Just shows dirt and clicking produces no results

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@Titanborn  Thank you for the report.
We have it in here #17567
