### ISSUE TITLE
[Enhancement] Demographic requirement - always show 'citizen'

### ISSUE THREAD

**Issue by GreaseMonk** [StrangeLoopGames/EcoIssues#18256]
I would like to point out I had not filled in the 'Citizen' in the 'advanced options' from the demographic requirement in the 'if' block, which should be always be visible when it is a requirement, and not hidden under advanced options.
![ddd123](https://user-images.githubusercontent.com/1354802/93165476-76a6a880-f71c-11ea-8db5-6c09152b571a.png)

**Comment by GreaseMonk** [comment]
I would like to point out I had not filled in the 'Citizen' in the 'advanced options' from the demographic requirement in the 'if' block, which was the error.
Maybe this is an enhancement - to show the citizen ?

**Comment by GreaseMonk** [comment]
Please also note that in this particular screenshot, the laws do not work. So if anyone is thinking of using this for their server, use a citizen timer instead of global timer and remove the if block.

**Comment by IcedForge** [comment]
It is now working where if its unable to fill in citizen automatically it will display the client field but if its able to set "Citizen" it will stay hidden under advanced options.
