### ISSUE TITLE
USER ISSUE: Disconnected from server

### ISSUE THREAD

**Issue by alexisgentil** [StrangeLoopGames/EcoIssues#18250]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
My friend has setup a server on his computer using the "Eco Server" tool on Steam.
Every 10 mins, me and the people who are not on the same network lose connection. The ones who are on the same network as him (at his house) are not disconnected.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5221292/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5221293/Player.log)

His server IP adress is 86.196.52.60 and I got these disconnections on sept. 14 at 11:22pm, 11h32pm, 11h42pm, etc...

**Comment by beastyn** [comment]
@alexisgentil Thank you for the report.
I will need some additional info:
1) What ping do you have?
2) What connection and OS server is using?
3) Can we see the Network config from server?

**Comment by alexisgentil** [comment]
**1. What ping do you have?**
~20ms to 30ms with 70Mbit/s VDSL2. My connection is monitored and I had no loss of flow nor micro-cut.

**2. What connection and OS server is using?**
Server is using a fiber optic home connection and is running on a Windows PC.

**3. Can we see the Network config from server?**
```
{
  "PublicServer": false,
  "Playtime": "",
  "Password": "",
  "Description": "MSI",
  "DetailedDescription": "",
  "ServerCategory": "None",
  "IPAddress": "Any",
  "RemoteAddress": "",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 20,
  "MaxConnections": -1,
  "ID": "7cf0508b-6dae-4b57-9777-80325f71fa1f",
  "Passport": "9762a4aa-b3c1-4881-a19d-1552596d873f",
  "UPnPEnabled": true
}
```

**More info :**
I tried hosting the server and my friends (the one previously hosting and the others on their own connections) but problem is still there. It already happened in the previous version of Eco. 
What is weird is that it happens every 10mins on the dot. I think it is something to dig into. We tried to deactivate auto-save but the bug still happens.

Ports 3000 and 3001 of the PC are opened.

**Comment by redwyre** [comment]
Could you try disabling UPnP on the server and manually forwarding the ports?

**Comment by alexisgentil** [comment]
We disabled UPnP and that worked ! No more disconnections, bug is gone !

**Comment by redwyre** [comment]
No problem, sounds like the issue is something on your local network - perhaps your router is clearing out UPnP entries after 10 minutes.
