### ISSUE TITLE
Linking storage speedup

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18258]
Its slow with opening

**Comment by SlayksWood** [comment]
Will close after second iteration

**Comment by Conchipedia** [comment]
Version 0.9.0.5
getting lag when opening storage (didn't seem as bad until Lumber Stockpiles are part of the Linked Storage)

![snap7473edited](https://user-images.githubusercontent.com/29383891/96584380-0c15f900-12d6-11eb-9131-0bd23115abbc.png)
The above Snapshot of CPU Usage from Task manager shows a specific Drop in CPU Usage when opening and then closing Storage

![snap7474edited](https://user-images.githubusercontent.com/29383891/96585359-66638980-12d7-11eb-8f47-e785fb40ce91.png)
This One is using **Intel Extreme Tuning Utility** and i have marked the Opening and closing CPU Dropping Points.


I would have thought it would have been Higher usage for CPU as it is accessing More information, but it is definitely doing something that is so Obvious causing Lag

**Comment by serpopov** [comment]
lets close this issue for 9.1 and make advanced UI optimization for 9.2, like "Switching tabs, open/close speedup"

for this issues all related bugs should be fixed, like layouts and misorder
