### ISSUE TITLE
Placing Cart Crashes Giant Panda & Duplicates Cart

### ISSUE THREAD

**Issue by zach-hill** [StrangeLoopGames/EcoIssues#18255]
This happened at approximately 3:20PM EST 9/14/2020 on the Giant Panda server

My cart was flipped upside down, I tried picking it up with a hammer and it did not disappear, upon attempting to place the cart again, the server appeared to start lagging and disconnected me, when rejoining I still had the cart item. I tried throwing it in the garbage but I couldn't interact with anything after doing so, so I rejoined and after reconnecting I still had the cart item, after placing it the server appeared to lag or crash again.

**Comment by beastyn** [comment]
@zach-hill Thank you for the report. Working here #17727 with it
