### ISSUE TITLE
Server Crash and Restart on Census Edit

### ISSUE THREAD

**Issue by mrogers6t** [StrangeLoopGames/EcoIssues#18252]
Version: 9.0.1

Issue: I had a player on my server try to remove a draft of a demographic in the Census Bureau and the server crashed and restarted itself. We tested two more times and the server crashed and restarted both times the draft was attempted to be erased. 

Steps to recreate: Draft a demographic in Census Bureau table and then delete draft and it crashes and restarts server.

**Comment by beastyn** [comment]
@mrogers6t Thank you for the report.Can you provide log filed from client and server?
Also it would me nice to have steps for reproduction., like what exactly was created, were there any elections with this demographic and so on.

**Comment by beastyn** [comment]
I will assume that its the same #18188.
If you have different kind of error my question is still valid.
