### ISSUE TITLE
Crashed when initializing server

### ISSUE THREAD

**Issue by redwannil** [StrangeLoopGames/EcoIssues#18263]
Last time I played this server record was June 21, 2020.
Everything was okay and the game was playable.
After updating version 9.0.1, I can't play because of server crashed in the initializing stage.
I find something which might be a reason in server log:

"Can't encode instance of type 'Eco.Mods.TechTree.AsphaltConcreteItem"

Below is the full log file for reference.
https://gist.github.com/redwannil/86fbca6d0760b36d5262eaad944b09a9

Please help me to fix this problem.
Thanks a lot.

**Comment by beastyn** [comment]
@redwannil Thank you for the report. Please, provide .eco file and .db file (you can make it privately with my e-mail: anna@strangeloopgames.com).
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by beastyn** [comment]
@redwannil what was the original version of the world? 8.3.3?

**Comment by redwannil** [comment]
Yes, 8.3.3

Anna <notifications@github.com> 於 2020年9月18日 週五 下午3:19寫道：

**Comment by beastyn** [comment]
@redwannil and hasthis server any mods?

**Comment by redwannil** [comment]
No mod is this server.

Anna <notifications@github.com> 於 2020年9月18日 週五 下午11:49寫道：

**Comment by beastyn** [comment]
@olegshegai Please, take a look (in your e-mail) Can we cure this save?
