### ISSUE TITLE
Server Crashes when cancelling a Demographic

### ISSUE THREAD

**Issue by CAAdams97** [StrangeLoopGames/EcoIssues#18265]
Version: 0.9.0.1 beta

When attempting to cancel the demographic change posted below the server crashes. I don't have access to server logs since it's an official server that I don't have access too, but you guys should (Crashes were around 8:15 Central Time on 9/14/2020 on the Official Sea Otter server) and I don't believe there are any player logs generated since it's just a server disconnect from my end. 

![Demographic](https://user-images.githubusercontent.com/28960082/93230113-f47aac00-f73c-11ea-98b1-15e2c6842cad.PNG)

My best guess is that this is happening because the demographic listed above is referenced in the law posted below. 

![Law](https://user-images.githubusercontent.com/28960082/93230191-08261280-f73d-11ea-979a-e5b84e7e7e17.PNG)

Edit: I tried removing the law FIRST before removing the demographic to cleanup the referencing issue and the server still crashes. I do not believe that demographic is referenced anywhere else but I may be wrong.

**Comment by beastyn** [comment]
@CAAdams97 Thank you for the report.
I will ask of the server logs, but still it would be nice to have your log from that session too.
Did not you have any error messages after the crash? Were you just kicked off the server without any error popups?

**Comment by beastyn** [comment]
I will assume it's the same like ##18188 and close it

**Comment by CAAdams97** [comment]
Here are the player logs just in case there is something useful in there, although the information may not be in there as this is posted a while after the crash.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5233021/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5233025/Player-prev.log)

I don't recall seeing any error messages after the crash. It just looked like a normal server shutdown from my end (like the daily resets). 

Not sure I fully understand your 3rd question: "And what was the original demographic? Was it a draft or the passed one?", but none of these were passed. Everything here was still just a draft at the time.
