### ISSUE TITLE
9.0.1 Some Research papers only need skill learnt but not specialised

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18261]
Some of the research papers only need you to have learn the skill not specialised into it spending a star.

Looking in the .cs files it looks to be the below line
"  [RequiresSkill(typeof(BakingSkill), 1)] "
  [RequiresSkill(typeof(SmeltingSkill), 0)] 

Found it on metallurgy am not sure what others are having the same issue, was reported in bug-testing by DavekeC, screenshot below is from a fresh copy of the server files.

![image](https://user-images.githubusercontent.com/61889138/93204398-f26d1900-f74d-11ea-9b78-1bdc63d6a734.png)

**Comment by WeaselDog** [comment]
Thanks for alerting us to the confusion.

This was a design decision to allow early progression while requiring still needing specialties later on. This will be addressed as part of https://github.com/StrangeLoopGames/EcoIssues/issues/17218
