### ISSUE TITLE
Accessibility issue : Material border color and upgrades for colorblind people

### ISSUE THREAD

**Issue by Drekal** [StrangeLoopGames/EcoIssues#18266]
I am a Protan colorblind and in a crafting table with an upgrade, I cannot see the difference between the yellow and green borders for materials with dynamic and static values.
Because of this I only discovered dynamic and static values after roughly 100 hours of play.  

I suggest maybe changing the green of that border to a darker green.

Regards

**Comment by R4wizard** [comment]
I've only recently just discovered that some item frames are yellow, some are green - this difference is impossible for me to see.

I recommend an alternative to solving this with different colours - or selectable colours. As a colourblind person, I often relegate colour in terms of an identifying factor (why trust a sense that doesn't work properly?), and as a result, I personally prefer solutions that handle this with solutions not involving colour, for example:
- Shapes (change the item frame shape as well as the colour?)
- Patterns (dotted colour, dashed colour)
- Icons / Text (add an upgrade icon on the frame, maybe with a number indicating the level)

Just my 2cents :)

**Comment by Daniel-Magulado** [comment]
Hi @Drekal 

A more color-friendly palette has been implemented and will be rolled out in the coming major game updates.
