### ISSUE TITLE
5.6.2 staging 8802b6fc placing worktables breaks rooms

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#1827]
Placing worktables makes rooms into "not rooms". Removing and replacing any block of the room makes it into a room again.

**Comment by egburr** [comment]
Possibly only occurs when the "room" is not built on ground? My floor is logs. Removing/replacing a wall piece does not fix this, but removing/replacing a floor piece does.

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/2746/room-goes-away possibly the issue

**Comment by craig-jong** [comment]
I believe this is fixed, but I'm going to leave this open until I'm sure.

**Comment by johnkslg** [comment]
Verified working
