### ISSUE TITLE
9.0.1 Client crash to main menu "Exception: InvalidOperationException"

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18277]
Client crash, this was the ouser LordTableTop on my server, no other user was affected at the same time, in chat it showed up "LordTableTop has left the game" twice which seems to be a telling sign of the crash

Attached is the text from the client crash and the server

[logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5228186/logs.zip)

have got a few others in the server's dump folder if you want those too

![image](https://user-images.githubusercontent.com/61889138/93262581-5fa79b00-f79c-11ea-9b60-b87d183ddb67.png)

**Comment by beastyn** [comment]
@MishkaFur Thanks. Moving here #18214
