### ISSUE TITLE
USER ISSUE: Broken Aqueduct

### ISSUE THREAD

**Issue by DurenBlake** [StrangeLoopGames/EcoIssues#18273]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Build an simple Aqueduct
try to fill it with water dumped out of an Pipe pumped by a single mechanical pump
Screenshot: ECO-Discord Channel general-help 15.09.2020 20:46
https://cdn.discordapp.com/attachments/448531486313021459/755499808524861460/unknown.png

**Expected behavior:**
The water should flow down the Aqueduct (wich it did in ECO 8)

**Actual behavior:**
Only creates a single Waterblock beneath the pipe and the water does not flow.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@DurenBlake Thank you for the report.
Flow issue base is here #17419
