### ISSUE TITLE
USER ISSUE: 100% Plant Death

### ISSUE THREAD

**Issue by csnick92** [StrangeLoopGames/EcoIssues#18274]
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Have plants

**Expected behavior:**
Plants should not be dying due to overcrowding when they are the only plant in the world.

**Actual behavior:**
All plants seem to have a VERY OVERCROWDED tag to them, causing them to die within roughly a 24 hour period, seems to be first the desert plants go, then the jungle (esp mushrooms), then grassland

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

Using admin tools, I removed every single plant from the game, planted a single Agave, and then quit and restarted my server. Upon logging back in, I used a soil sampler on the Agave and it was still showing as Very Overcrowded, even though it was the only plant on the entire world.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![0 plants 1](https://user-images.githubusercontent.com/71349232/93256481-52d27980-f793-11ea-8bc9-4a395c63b854.png)
![0 plants 2](https://user-images.githubusercontent.com/71349232/93256476-5239e300-f793-11ea-9288-58e89b372ecb.png)
![0 plants 3](https://user-images.githubusercontent.com/71349232/93256473-5108b600-f793-11ea-9eda-441d5708739f.png)
![0 plants 4](https://user-images.githubusercontent.com/71349232/93256483-536b1000-f793-11ea-8ac4-55536f661d59.png)

**Comment by beastyn** [comment]
@csnick92 Thank you for the report. Merging it here #18173.
For now its common issues we are working on fixing it.
I am sorry for the inconvenience.
