### ISSUE TITLE
Updates for CW Admin Management Tool

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18278]
- [x] Remove 'id' and replace with 'user_id' to Worlds in Database 

- [x] Check hat all the world management buttons are working

- [x] Add reset button to Worlds in Database

- [x] Fix delete world in Worlds Online

- [ ] Jeff: Worlds Online should include both regions, and separated by region (please, return `region` field in `/api/instance/all` CW API endpoint and sort result by region asc + name asc (to separate result by region). I've added region to table, so just add in CW API (+sorting) and that'll fix this bullet).

- [x]  when admin starts new world.
add ability to set the user_id that will receive newly started world.
that user will then see the world under their worlds page

- [x] When starting a world, many of the options do not apply to new world, such as awsname and version.

**Comment by denysaw** [comment]
@WeaselDog Finished my part. That's why removing milestone for Jeff to plan his ;)

**Comment by j3fffff** [comment]
last task moved to https://github.com/StrangeLoopGames/EcoIssues/issues/18869
