### ISSUE TITLE
restart broken worlds cron job

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18270]
If world is missing serverID and pending = 0
restart it and update serverID and serverURL

**Comment by denysaw** [comment]
Done. Cronjob worx, but SW API returns fail for some worlds, so check the output.
Also cron should be added to cron jobs on Prod to be run.

**Comment by j3fffff** [comment]
cron is returning error:
`Unable to locate the specified class: Session.php`

**Comment by denysaw** [comment]
Fixed (on staging).

**Comment by j3fffff** [comment]
added to cron tab for once a day
