### ISSUE TITLE
set docker containers to backup to s3

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18279]
Starting with jenkins

**Comment by redwyre** [comment]
* Created AWS S3 bucket "slg-docker-backups"
* Created AWS IAM group "slg-docker-backups" with write-only access to S3 bucket "slg-docker-backups"
* Created AWS IAM user "slg-docker-backup" in group "slg-docker-backups"
* Modified Jenkins docker compose file to add a "jenkins_backup" container which backs up every day to S3 container "slg-docker-backups"

**Comment by mirasrael** [comment]
Eco Server has native support for S3 backups.

**Comment by redwyre** [comment]
@mirasrael this is for infrastructure backups, specifically jenkins

**Comment by mirasrael** [comment]
Ok :) Just fyi in case if you didn't know this :)
