### ISSUE TITLE
Reference errors when importing V.9 modkit into Unity V2019.4.9

### ISSUE THREAD

**Issue by Slashroot101** [StrangeLoopGames/EcoIssues#18281]
Whenever I try to import the latest modkit into Unity V2019.4.9, I get a bunch of reference errors as seen below.

![image](https://user-images.githubusercontent.com/13453550/93284757-53720c80-f7a1-11ea-9ec0-0c756dd3cc9e.png)

I am not entirely sure if this is user error and I am missing packages or this is the modkit, but I know a few other people are having issues with it too. This is on fresh Unity with nothing added.

**Comment by Slashroot101** [comment]
Just checking in, any progress on this one? I can provide more info if needed

**Comment by redwyre** [comment]
Can you try adding the unity Collections package?
if editing directly: `"com.unity.collections": "0.9.0-preview.5",`

**Comment by Slashroot101** [comment]
Yeah, that fixed it.

**Comment by redwyre** [comment]
For reference I've update the instructions here: https://wiki.play.eco/en/Installing_the_ModKit
