### ISSUE TITLE
Contracts : Completed contracts are still visible in "Economy Viewer"

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18284]
Completed contracts are still visible in "Economy Viewer"

2 contracts which are both marked as finished are still visible and has tag "Waiting for Review" (see pic)
Contractor got payment when i finished the contract via the contract board. Contract is gone from the board.
Pic:
![89434026-5958e480-d743-11ea-8c45-2b3ac0620af3](https://user-images.githubusercontent.com/27898520/93294505-20149980-f804-11ea-8792-6ab7ca517dbf.png)

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/108837988-162d6880-75e4-11eb-87ee-8d01e98dbe3c.png)
