### ISSUE TITLE
USER ISSUE: Wolves!

### ISSUE THREAD

**Issue by Bluelight82** [StrangeLoopGames/EcoIssues#18282]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Play the game and get attacked by a wolf.

**Expected behavior:**
Expect not to get attacked by a wolf. A wolf is not hostile normally, it will even run away from humans. We kill more sheeps and humans.

**Actual behavior:**
Wolf is randomly attacking.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file:**
Log file not needed for this issue.

**Comment by beastyn** [comment]
@Bluelight82 Thank you for the report.
Our animals are pretty lonely and hungry all the time, wolves too. They don't have packs sometime too That's the way they are. And here you are, chopping some trees, looking so tasty and not really dangerous or fast enough to run away. 

But! You can take a bow or a torch and scare it away.
Also we will think about making additional tutorial for aggressive animals and adjust their behavior for settlements.
