### ISSUE TITLE
USER ISSUE: Ore machines upgrade not working

### ISSUE THREAD

**Issue by AncientGammoner** [StrangeLoopGames/EcoIssues#18286]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Place upgrade module into arrastra or stamp mill and go to craft recipe.

**Expected behavior:**
A reduction in resource costs to craft recipes at these machines per the upgrade module.

**Actual behavior:**
No difference over using no upgrade module

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@AncientGammoner Thank you for the report
This is intended behavior. as you can tell by the yellow outline of the resource cost, if you mouse over it is a "Static" value and there for not having a reduction on resources only processing time.
You can also read ECOpedia:
![image](https://user-images.githubusercontent.com/45708377/92559004-6acc6980-f278-11ea-8d8b-4dfc4552e6d2.png)
