### ISSUE TITLE
USER ISSUE: Stuck in floor

### ISSUE THREAD

**Issue by cutefeet** [StrangeLoopGames/EcoIssues#18287]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Place Hewn Log Floor with right click on ground (not in a storage).

**Expected behavior:**
Hewn Log Floor gets dropped on the ground.

**Actual behavior:**
Floats mid-air and player gets stuck.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by cutefeet** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5230768/Player-prev.log)

**Comment by beastyn** [comment]
@cutefeet Thank you for the report.
Can you provide additional info?
1) Screenshot would be nice to have.
2) What tool did you use?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
