### ISSUE TITLE
Contract: Final clause in contract can not be moved up or deleted.

### ISSUE THREAD

**Issue by Mozleron** [StrangeLoopGames/EcoIssues#18289]
Problem Description:
When editing a contract, the Add Clause button captures the clicks that should be going to the Move Up/Down/Delete buttons, causing the clause to not be moved or deleted, but for a new on to be created instead.

Expected Behavior: 
When clicking on the move up or delete buttons of the final clause in a contract, it should move above the clause immediately above it or be removed, respectively.

Actual Behavior: 
A new clause is inserted at the bottom of the contract, and the old clause remains in it's previous position relative to the rest of the contract.

Possible Solution:
With the move up/down/delete buttons hanging from the bottom of the clause panel, rather than being inside the confines of the panel, it appears that the Add Clause button is rendering over the top of them, causing it to catch the mouse events first.  Putting the buttons into the individual clause frames would be one possible way to fix this issue.  

Opinion: 
It also seems like someone was getting too cute with mouse hover type events instead of just having the buttons always visible.

**Comment by beastyn** [comment]
@Mozleron thank you for the report. Merging here #18128
