### ISSUE TITLE
Map renderig bug

### ISSUE THREAD

**Issue by Templorum** [StrangeLoopGames/EcoIssues#18292]
Hi guys, im just buy this game 1 day ago, and this grate. But my map is heave render bug,
![image](https://user-images.githubusercontent.com/13473543/93331523-13566c80-f829-11ea-8d8d-eb03e54b8b7b.png)

If i scale up or dawn the map - size of this "box" will scale up. 
This is my setting page, i can sand "debug log file" but i dont find it in game catalog. 
![image](https://user-images.githubusercontent.com/13473543/93331794-83fd8900-f829-11ea-899b-dc6b9e208b79.png)

To fix this i try change grafic settings (all of they) and try restart the game.

**Comment by beastyn** [comment]
@Templorum thank you for the report. Did not it tell you anything before connecting to the server?
It should actually.
I assume you have AMD and maybe have updated drivers recently.

Please read the last comment in this issues #17895
I will close this one but if changing tesselation level won't help, feel free to write here, I will answer
