### ISSUE TITLE
Eco single player Connection/Login failed error

### ISSUE THREAD

**Issue by Adsieboy** [StrangeLoopGames/EcoIssues#18299]
Hi, i am having issues loading into single player game in Eco. It loads all the way to saving world, then get the error in the screen shot. I have tried several times in a row to log in but get same error. I can join a friends game but the error comes up on the first attempt but works ok on the second.

![image](https://user-images.githubusercontent.com/71398029/93377662-39910200-f853-11ea-8916-da6f268ab6f1.png)

Also attached Log 
[log_200916072913.log](https://github.com/StrangeLoopGames/EcoIssues/files/5234200/log_200916072913.log)

Hope you can help!
Thanks

Adam

**Comment by beastyn** [comment]
@Adsieboy thank you for the report.
Please provide 
1) Client log file https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2) PC specification and OS
3) .eco file (you can send it to me via e-mail anna@strangeloopgames.com)

**Comment by beastyn** [comment]
@Adsieboy I've got your save file and was completely fine with logging in (test 1).
So, from your logs I can see that something is wrong with access to the files in Local Low.
For example 
AppData\LocalLow\Strange Loop Games\Eco\recentServers.eco" is denied.
or
AppData\LocalLow\Strange Loop Games\Eco\favorites.eco" is denied.
You can delete these files and try again.

**Comment by Adsieboy** [comment]
Hi Anna,

Deleting the files you suggested worked! I can now load the game and play!

Thanks so much for your help!

Regards

Adam
