### ISSUE TITLE
Contract: Unable to place Lumber Door within confines of contract area

### ISSUE THREAD

**Issue by Mozleron** [StrangeLoopGames/EcoIssues#18290]
Description:
I have a contract to build an extension onto the Capitol building.  I am able to build the floor and walls using Lumber without issue.  I am unable to place doors on the same property, however.  I tried with Hewn doors and Lumber doors and received the same error with both.

Expected Behavior:
I should be able to place a door within the build area defined by the contract.

Actual Behavior: I receive the error "you are not authorized to build here" and am unable to place the door.

I have attached images of the contract and a first person capture of the error. I did not move my avatar between capturing the two screen shots.
![Contract](https://user-images.githubusercontent.com/2364796/93318787-f2a7fb80-f7c3-11ea-86cd-3524038ce881.png)
![unauthorized](https://user-images.githubusercontent.com/2364796/93318790-f3d92880-f7c3-11ea-9e6e-7f20053b29c2.png)

**Comment by Moritur** [comment]
Work on this issue is currently blocked by issue https://github.com/StrangeLoopGames/EcoIssues/issues/21079

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3.1 Release-207

Appears to be working. Tested with Hewn Door and Lumber Door.
Closing.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/540dfb98-0362-4282-b821-15642f7de7cd)
