### ISSUE TITLE
Fuel Supply Bloomery continually alternates between 3 Value

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1829]
Other Value was >1day
![grafik](https://user-images.githubusercontent.com/26040573/28743566-f586e396-744c-11e7-9aac-a7376145d25d.png)

**Comment by MarjieAVolk** [comment]
Well that's odd - haven't been able to repro over here yet.  There's a section just below Fuel Supply titled Consuming Fuel - does the value on that panel also change?  Also, if you consistently see this, could you send your server save file?

**Comment by REPOSEECO** [comment]
Sorry i have no own server. Just player. Only the value on the panle change.

**Comment by MarjieAVolk** [comment]
Did you close the issue because you figured out the problem?

**Comment by REPOSEECO** [comment]
I think that was a problem on only one Server. On another server the Problem don't exist. Other wise i can reopen the Ticket
