### ISSUE TITLE
USER ISSUE: funktion ohne funktion

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#18297]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
stufe 6, Holzfällen
Talent "Clean Up Cred"

**Expected behavior:**
keinen Kalorienverbrauch/Abnutzung beim entfernen des Baumstumpfs, Holzresten und zerkleinern des Baumstamms

**Actual behavior:**
weiterhin kosten an Kalorien

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hallo Timo,
die Übersetzung ist vermutlich falsch auf Deutsch.

Das Talent entfernt nur die hohen Zusatzkosten für Debris, statt 60 solltest du also massiv weniger Kalorien brauchen. Ist das der Fall? Wenn ja, dann funktioniert es wie vorgesehen.

**Comment by IcedForge** [comment]
Possibly rephrase the description of the cleanup crew perk in logging skill?

**Comment by TimoNuernberg** [comment]
Hallo
okay, danke, die Kosten sind 11 pro Schlag; gut, danke für die Information,
