### ISSUE TITLE
Soil in River changes with Bridges

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18291]
When you build a bridge over water the type of blocks changes in the River to the Biome Blocks instead of the Riverblock

![grafik](https://user-images.githubusercontent.com/37456949/93321922-09297380-f813-11ea-9378-2e4978907fb8.png)
![grafik](https://user-images.githubusercontent.com/37456949/93321953-10508180-f813-11ea-94c3-fcac3005a72d.png)

**Comment by soulnet** [comment]
Could be related, see image below with fish swimming in the bridge.

![image](https://user-images.githubusercontent.com/36501028/93339420-e7f67080-f86e-11ea-9894-23ce09e6ac59.png)

**Comment by SlayksWood** [comment]
> Not sure if this is intended, but on our Coast Redwood server the Ocean and River Sand underneath a bridge slowly turned to regular Dirt:
> 
> ![image](https://user-images.githubusercontent.com/964559/96427072-f22fc580-11b2-11eb-99b6-9bd4d7acb738.png)
> 
> I'm guessing that's just how it operates if it has some block above it, even though it's way above it?

**Comment by SlayksWood** [comment]
> It's still there on Coast Redwood:
> 
> ![image](https://user-images.githubusercontent.com/964559/96682965-66db3f00-132e-11eb-9322-cccff6cc5787.png)
> 
> But you might be right, it might be tied to trample:
> 
> ![image](https://user-images.githubusercontent.com/964559/96683193-a9048080-132e-11eb-84cc-76495fa3bb74.png)
> 
> I don't think all of my house for example has the dirt underneath it, just the parts I walk around on the most...

**Comment by IcedForge** [comment]
Closing this and using #19606 to track this behavior
