### ISSUE TITLE
[0.9.0.2 beta release-70 ]Contract Board: Can only select learned materials as road types.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18296]
Can not select not yet learned road types using "Build Road"
missing a "show unlearned" button ( but i would think this feature is unnecessary here as it should always show all road types maybe? )

Before learning skills
![Screenshot_404.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b769ace7-174f-4aab-8285-f7e40fe65d03)

After learning skills
![Screenshot_1.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/934d2c75-a868-4a73-9bc8-5610da70d3ad)

closely related to https://github.com/StrangeLoopGames/Eco/pull/6801/commits

**Comment by Mozleron** [comment]
When I try to create a road contract, I can't even get that pop-up to come up.

**Comment by flying7eleven** [comment]
I have the same issue like @Mozleron. Even with 0.9.0.2 (release-71) I still cannot open the selection window for the road type.

**Comment by serpopov** [comment]
For this issue refactroing was performed. Things to test:

- Trigger selection on laws restricts to the correct tagged stuff, check tool related triggers, etc.
- Ecopedia 'show discovered' continues to work properly, as well as item filter 'show discovered'
- Migration from previous created Mint, Contracts (Build Roads, Harvest etc), Item Distribution Station and their pickers.
- See if only allowed items are presented in filter dialog

**Comment by johnkslg** [comment]
This filter dialog needs a 'Show Undiscovered' button. 
I believe there was another bug that fixed this, so if that exist now just close this.
