### ISSUE TITLE
Powered cart glitches out with 3rd person use.

### ISSUE THREAD

**Issue by murderinspree** [StrangeLoopGames/EcoIssues#18301]
Whenever i get on a powered cart then switch to 3rd person, it starts to jump around and flips over. i can exit the cart and it will usually fix itself. if i go into 3rd person view before getting on the cart, then get on the cart, it doesnt move... at all. it will not drive, i can not switch back to 1st person and i can not exit the cart. i must log out of the server then back in to be off the powered cart. i have tried to use fly command to see if i can get off the cart but it only makes it worse (my character starts to fall over/ flip around the cart like the cart does in the first part of this issue). not sure if anyone else has this problem or not. I thought i would post it here and see if there is a fix on my end or if it is a game issue.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-192.

To reproduce this issue, simply remove the avatar's bag before mounting. Then once mounted, switch to 3rd person view. Then observe.

Notes:
- I am unable to exit the cart.
- I am unable to drive the cart even if there's fuel.

Video Repro:
https://images.zenhubusercontent.com/47210472/ea6812e8-f539-4028-bc5b-88b32900ad1d/2021_02_25_23_26.mp4

Logs
[https://app.zenhub.com/files/47210472/f2763fcc-56f9-4fbe-a548-f03f6bb31ad0/download](https://app.zenhub.com/files/47210472/f2763fcc-56f9-4fbe-a548-f03f6bb31ad0/download)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-282.

Appears to be fixed. Closing.
