### ISSUE TITLE
MARMOT - SLG Staging Server 5.6.2 no UI always (0,0,0) Position

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1830]
![0_0_0](https://user-images.githubusercontent.com/26040573/28752530-7e0ceef6-7522-11e7-94df-6acf0f0861b4.JPG)

**Comment by MarjieAVolk** [comment]
I'm not seeing this issue.  Could you attach your output_log.txt?

**Comment by REPOSEECO** [comment]
Server is now offline
[log_170730120038.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1202314/log_170730120038.zip)

**Comment by REPOSEECO** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1202315/output_log.txt)
