### ISSUE TITLE
Store: Unable to increase Max to Buy quantity

### ISSUE THREAD

**Issue by Mozleron** [StrangeLoopGames/EcoIssues#18302]
Description:
In a Store, there are two conditions I where have noticed the inability to increase the Max To Buy amount.
Condition 1: When adding a single new item to the Purchasing list. 
Condition 2: When an item has existed on the store Purchase list for more than a few minutes (I have been unable to pin down the exact time span, but it seems like it is related to when the server does the Update tick)

Condition 1
Expected Behavior:
When adding a single item to the purchase list, it will show up at the bottom of the list with a Price of 1 and Max to Buy of 0.  I should then be able to either click the + button to increase the Max to Buy or click into the text box and set the value directly.

Actual Behavior:
Clicking the + button does not change the Max to Buy value.  I am able to click and type in a numerical value, but pressing Enter will return the text box to 0 and the 999 on the icon does not change.

Condition 2
Expected Behavior:
When opening the Store screen, I should be able to increase the Max to Buy value for any item in the list.

Actual Behavior:
I can decrease the Max to Buy value (eg, from 50 to 49), and then re-increase it to it's previous maximum (50), but not over.

Additional info:
If I add two new items at the same time or remove an item and add a new one at the same time, in the same filter box pop up, I am able to edit the Max to Buy value of the newly added item.  If I move the newly added item up or down in the list, I am able to change it's Max to Buy value.  In each of the previous conditions, I am still unable to edit the Max to Buy of any items that were previously in the list before the new store session was opened.

There seems to be some sort of timeout of a minute or two where an item can behave correctly, but at some point, the item in the list simply locks up and the Max to Buy can no longer be edited without first removing it.

**Comment by IcedForge** [comment]
Duplicate #18195
