### ISSUE TITLE
Desert roads converting back to desert sand.

### ISSUE THREAD

**Issue by Cameeb** [StrangeLoopGames/EcoIssues#18309]
I'm not sure if it intended or not but after the 9.0 update, my desert roads are gradually converting back to desert sand.  When using the road tool on desert sand after about 5-10 minutes it will change back.

**Comment by IcedForge** [comment]
This is an intended function.
Desert Sand can't be converted to Road and Dirt Roads in Desert may be eventually destroyed by unfriendly environment.
