### ISSUE TITLE
USER ISSUE: Compostable materials generate trash

### ISSUE THREAD

**Issue by iflounder** [StrangeLoopGames/EcoIssues#18308]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
1. Place 1 Compostable material in a trash pile (green background).
2. Place 2 stacks of Compostable material in another Trash Pile (i used 2 single pieces of charred tomatos)
3. Wait 24 hours.

**Expected behavior:**
The first pile will generate 1 compost and the second pile will generate 1 compost and 1 garbage (Note doing 4 stacks will result in 1 and 3)

**Actual behavior:**
The second pile generates 2 compost.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by iflounder** [comment]
I believe i swapped the expected behavior and actual behavior in this bug issue. It should generate 2 compost or 1 instead it generates 1 trash and 1 compost.

**Comment by beastyn** [comment]
Yeap, something is with food items.
I've checked Charred tomato and Bear S U P R E M E and just one of them became a compost. Other one is garbage.

**Comment by beastyn** [comment]
@WeaselDog 
1) Maybe we can put a recipe in the Farmer table with the Food tag to make a compost from everything what is eatable (can also be skill related)
2) And everything you drop on the ground should become a garbage.
Example:
Make "Compost" - Seeds "100"
Make "Compost" - Food "20"
Make "Compost" - Raw Food/Crop "40"
@IcedForge  idea.

**Comment by WeaselDog** [comment]
We will add recipes for fertilizer, but in the meantime can we fix this as part of https://github.com/StrangeLoopGames/EcoIssues/issues/10119. If it is all compostable items, it should be 1 compost. If it has trash items, it should create 1 garbage.
