### ISSUE TITLE
New crash I haven't seen before

### ISSUE THREAD

**Issue by Calura** [StrangeLoopGames/EcoIssues#18312]
![issuesissue](https://user-images.githubusercontent.com/53465919/93499992-b7035380-f8e1-11ea-961d-90cf2100b3c1.jpg)

So I saved all of it to a text file

[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5240649/log.txt)

**Comment by beastyn** [comment]
@Calura Thank you for the report.
Any additional info like some particular actions?
Also it will be great to have your DxDiag results.

What is you connection to the server (and which server do you play on)? What ping do you have?

**Comment by Calura** [comment]
I actually can't remember exactly what I was doing. The crash took me by surprise and I was more focused in getting the report up, and forgot my actions leading up to it.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5246165/DxDiag.txt)


I play on the Guardians Gaming server and I'm an admin on there (with full back-end access, so I can get server logs if you need those too). It's not a hosted server - the actual box owner is one of our other admins. But the server itself sits at a server farm in New Jersey. IP address is 66.85.75.178. Ping is usually about 10-30, so it's pretty low (I have a gigabit internet connection).

I did report this right away, so based on the time could it have been around the 9.0.2 update release time?

**Comment by Calura** [comment]
Information submitted

**Comment by beastyn** [comment]
@Calura Thank you for the detailed answer and sorry for the delay. 
If you are making a local server and play solo is it fine for you?

**Comment by beastyn** [comment]
Connected to #17718

**Comment by Calura** [comment]
> @Calura Thank you for the detailed answer and sorry for the delay.
> If you are making a local server and play solo is it fine for you?

It's really difficult to say. I only saw that crash once since 9.0 came out and not since then.
