### ISSUE TITLE
Ingame News

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18318]
- [x] Order is wrong. Newer news needs to be displayed first, not last. People don't want to scroll to see the newest news.
- [x] Lines are overlapping.
- [ ] After fix, update news to remove line-breaks
![fix](https://user-images.githubusercontent.com/25908592/93533559-7b997100-f943-11ea-97d5-215150ce7617.png)

**Comment by denysaw** [comment]
Order fixed on our side.

**Comment by denysaw** [comment]
@redwyre Assign someone to fix 2nd checkbox, pls ;)

**Comment by SlayksWood** [comment]
need to delete line-breaks and close this issue

**Comment by gabrielgindridev** [comment]
> @D3nnis3n
> need to delete line-breaks and close this issue

@SlayksWood I'm not sure if was already deleted, but I think @D3nnis3n went on vacation

**Comment by D3nnis3n** [comment]
Yeh, that was done.

Gabriel Martins <notifications@github.com> schrieb am Fr., 25. Sept. 2020,
16:53:
