### ISSUE TITLE
General News Page for Major Announcements

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18316]
A general news page for major announcements with higher reach (like releases).
Probably working the same as it did on the old website.
Check back with Jeff to get this fleshed out.

**Comment by j3fffff** [comment]
are you thinking a tree section or a new area for announcements?
This is for shorter announcements or long blog posts?

**Comment by D3nnis3n** [comment]
Mainly longer announcements for releases and pretty much anything that is important enough to be have a high reach, e.g. easily visible.

**Comment by j3fffff** [comment]
@johnkslg whats your take on this? we removed news section from site before. could ad it back

**Comment by johnkslg** [comment]
We could have something for major announcements I suppose. But need to hide it when the announcments are old.

**Comment by j3fffff** [comment]
@denysaw can you add back the news section on the main landing page.
It's in news.twig
Then only display it when newest post is less then 2 weeks old.
You can get `date` from the wordpress api: https://api.strangeloopgames.com/wp-json/wp/v2/posts

**Comment by denysaw** [comment]
@j3fffff Yeah, sure. Will do.

**Comment by denysaw** [comment]
Done. Could be tested on Staging, though it doesn't appear as there's no fresh news (that 2 weeks range) + mind about 2hrs cache, after adding fresh news. You could click that magic `Flush` button in the admin area to clear it.
