### ISSUE TITLE
[0.9.0.2 dev-56 ] Excavator Animation / Movement flow

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18310]
Acceleration and deceleration makes the excavator look like its a boat currently.
https://i.gyazo.com/95ce4bff812a30d6c1b76a0cf46c0efa.mp4

Toning down the animation for stopping, starting and adding a "Stop" before switching between forward motion and backward motion
as its currently stopping but out of a realistic viewpoint the vehicle motion is reversing.

As you can see in the clip, when the excavator starts moving forward its starting to lean forward, and the opposite for going into reverse; 
on starting driving this is the complete reverse that should be happening.

When stopping in a direction, it should lean towards that direction; when starting it should lean backwards from it.

**Comment by SlayksWood** [comment]
Still an issue, but we have another issue for this #12437
