### ISSUE TITLE
Clear Cache Button for News

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18319]
I wanna press that button. Priority is as high as its enerving for you to need to press the button for me.

**Comment by beastyn** [comment]
Give the button, please!

**Comment by denysaw** [comment]
![image](https://user-images.githubusercontent.com/5720101/96032509-10b65980-0e5f-11eb-925a-2a2c2c4601af.png)

@D3nnis3n Soon (on a next merge) gonna be on Production ;)
