### ISSUE TITLE
[0.9.0.1 beta] Elected titles without government treasury access can create titles with wages paid by the treasury

### ISSUE THREAD

**Issue by TemporalWolf** [StrangeLoopGames/EcoIssues#18313]
![image](https://user-images.githubusercontent.com/34265614/93510748-9386db80-f8d6-11ea-8eed-bba3f1026cc1.png)

With those settings I can create an unelected title in the Registrar, set it to pay wages from the Treasury, and it will.

**Comment by TemporalWolf** [comment]
So this may be invalid: I had this access earlier. Now I don't. One notable change since then is we've filled an elected title with those permissions, who is set as removable by the above Prime Minister.

So perhaps those permissions fell to me while that title was unoccupied?

**Comment by IcedForge** [comment]
Seems to be fixed with recent changes to treasury account permission system.
