### ISSUE TITLE
[9.0.2 Beta] [Linux Client] Map and Minimap ground is not showing

### ISSUE THREAD

**Issue by bryandelong** [StrangeLoopGames/EcoIssues#18328]
Running Manjaro 5.4 Kernel
Nvidia Non-Free Drivers,  GTX 1070

When looking at the Map,  The ground plane is not showing and the layers are also a bit messed up and very unusable

**Comment by redwyre** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18081
