### ISSUE TITLE
Inventory bug?

### ISSUE THREAD

**Issue by InsomniCat** [StrangeLoopGames/EcoIssues#18320]
so this keeps happening, I've tried disconnecting as well as plain quitting the game completely and restarting and it still does this
![image](https://user-images.githubusercontent.com/71470443/93533877-88996e80-f909-11ea-9a5e-e8764768f504.png)

**Comment by beastyn** [comment]
@InsomniCat Thank you for the report.
Please describe step by step what you did and what are you trying to do.

**Comment by InsomniCat** [comment]
> @InsomniCat Thank you for the report.
> Please describe step by step what you did and what are you trying to do.

just trying to move things from one spot to another, but it keeps popping that menu up even when my inventory is completely empty except for one tool it will still pop up

**Comment by beastyn** [comment]
@InsomniCat thanks you for the additional information.
Are you trying to put things into your backpack? it has overweight. Or just inside a stockpile?

Please, provide your log file too.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@InsomniCat Thank you for the logs. They look fine. Can you make a video with your steps?
Do you have mods installed?
Can you provide save file .eco?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
