### ISSUE TITLE
[0.9.0.2 beta release-71] Uppercase names

### ISSUE THREAD

**Issue by Sephyros** [StrangeLoopGames/EcoIssues#18323]
When defining a name to contract board, work parties, contracts, storage chests, stockpiles and some other places the edit text displays as "uppercase", after saving the edition the text is shown as we type, the problem is that we cannot see the difference between uppercase and lowercase during editing.

![During Edit](https://user-images.githubusercontent.com/2486599/93551881-69203700-f945-11ea-99d1-d681dc7d3d72.jpg)
![After edit](https://user-images.githubusercontent.com/2486599/93551878-6887a080-f945-11ea-9103-0e81c0da2323.jpg)
![On aiming](https://user-images.githubusercontent.com/2486599/93551883-69b8cd80-f945-11ea-9661-08f7007212c3.jpg)
![On hover](https://user-images.githubusercontent.com/2486599/93551884-69b8cd80-f945-11ea-9960-5cf129b09a3a.jpg)

**Comment by beastyn** [comment]
@serpopov please discuss with UI team
