### ISSUE TITLE
[ECO 9.0.2] Failed to load server NullReferenceException or KeyNotFound (French)

### ISSUE THREAD

**Issue by baguette-deluxe** [StrangeLoopGames/EcoIssues#18326]
In French, we always have the KeyNotFound or NullReference error in Linux SERVER or Windows SERVER

Has the team spotted this problem or is it not a priority? Because this bug, after restarting the server, the player has values ​​errors and it is very complicated to continue playing. Some players don't speak English very well so we still config the server in french. We are a little confused.

Some rules and values ​​become glitchy and risk breaking the world and potentially starting all over again (which was not the case with 8.3.3)

If we change the language in English, the problem is fix BUT like I said, some players don't speak English very well

9.0.2 did not fix this problem

The correction of this 
bug is in progress?

https://pastebin.com/WRnZdHrq

**Comment by beastyn** [comment]
@baguette-deluxe Thank you for the report.
yeap, looks like this one #18211 for the hotfix.
Can you provide the .eco and .db file? (you can use my e-mail for private sending anna@strangeloopgames.com)

**Comment by baguette-deluxe** [comment]
Hi,

Here are the requested files :

to reproduse this, very simple :
(need 2 players)
1. set localization server in FRENCH
2. launch the server
3. first player connects, it works
4. 2nd player connect and gets this problem

We need to reboot the server to "force" the player connect but, we spotted somes values buggy or glitched like account bank somethink like that

Note :
If you set 2 admin in User (before launch for the first time the server and world) the 1st player is ok but the 2nd player (after reboot server) have buggy credit (not infinity)

[test server in french.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5245068/test.server.in.french.zip)

**Comment by baguette-deluxe** [comment]
the 1st error message on connection (NullReferenceException) :

`<size=150%>Connexion échouée</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.TryCreateUserAccount(User user)
   at Eco.Gameplay.Players.User.Initialize()
   at Eco.Core.Systems.Registrar.Insert(IHasID newObj, INetObject netObj)
   at Eco.Gameplay.Players.UserManager.PrepareNewUser(String steamId, String slgId, String username)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>

Log File:
Initialize engine version: 2019.4.9f1 (50fe8a171dd9)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 960 (ID=0x1401)
    Vendor:   
    VRAM:     4053 MB
    Driver:   27.21.14.5206
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.603400 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 589)

WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename:  Line: 334)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
SteamManager:Awake()

[ line 589] 
(Filename:  Line: 589)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[12:48:07.792] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.HandleEventMessage:Invoke(vx_evt_base_t)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.HandleEventMessage:Invoke(vx_evt_base_t)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
MessagePump:RunOnce()
MessagePump:RunUntil(LoopDone)
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[12:48:41.690] Connecting to 192.168.0.42:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ServerInfo)
SelectedServerUI:Join()
Steamworks.RulesRefreshComplete:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.EventHandler:Invoke(Object, EventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)

Unloading 15 unused Assets to reduce memory usage. Loaded Objects now: 90279.
Total: 221.523300 ms (FindLiveObjects: 5.769300 ms CreateObjectMapping: 7.028100 ms MarkObjects: 208.575100 ms  DeleteObjects: 0.150500 ms)

[12:52:23.527] Connecting to 192.168.0.42:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ServerInfo)
SelectedServerUI:Join()
Steamworks.RulesRefreshComplete:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.EventHandler:Invoke(Object, EventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing! 
(Filename:  Line: 334)

Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d 
(Filename:  Line: 584)

[12:52:29.919] Missing following icons:
AsphaltConcreteRampItem
AttachmentComponent
BlockForm
ChargingComponent
ContractEscrowBankAccount
FakePlantComponent
FormType
FuelConsumptionComponent
FuelSupplyComponent
GovernmentBankAccount
LinkComponent
LiquidProducerComponent
LogicGateObject
ModularStockpileComponent
ModularVehicleComponent
MountComponent
OnOffComponent
PersonalAccount
PowerConsumptionComponent
PowerGeneratorComponent
PowerGridComponent
PowerGridNetworkComponent
RoofsFormGroup
RoomRequirementsComponent
StandaloneAuthComponent
TollComponent
TreasuryBankAccount
VehicleHoeComponent
VehicleToolComponent
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<CreateMissingItems>d__52:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<BuildItems>d__53:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[12:52:30.062] Missing following objects: AirPollutionGeneratorObject
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
<BuildFromModKit>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[12:52:31.237] Disconnected with error: Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccountManager.TryCreateUserAccount(User user)
   at Eco.Gameplay.Players.User.Initialize()
   at Eco.Core.Systems.Registrar.Insert(IHasID newObj, INetObject netObj)
   at Eco.Gameplay.Players.UserManager.PrepareNewUser(String steamId, String slgId, String username)
   at Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username)
   at Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Action`2:Invoke(T1, T2)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
Steamworks.RulesRefreshComplete:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.RulesRefreshComplete:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 30764 unused Assets to reduce memory usage. Loaded Objects now: 91538.
Total: 339.397900 ms (FindLiveObjects: 6.969200 ms CreateObjectMapping: 12.692500 ms MarkObjects: 286.401400 ms  DeleteObjects: 33.334400 ms)`

**Comment by beastyn** [comment]
@baguette-deluxe Thanks a lot!
So its like the same but kind of a different.
I will leave it separately and place with hotfix too.
For reproduction fresh world can be used. Just with French localization and second person which is trying to connect.
Maybe it will help here #18211

**Comment by baguette-deluxe** [comment]
Thank you for listening !

We are available every day to test any preview version for Linux server (or Windows server) to check if the future patch works and to give you more information.

This fix will allow us to play quietly without risk of bug with the database and use french most of the time

if you want more details / information, contact me

**Comment by lagonnebula** [comment]
Well, i got the issue fix with 0.9.0.2-beta Linux server.
Server in French, Client in French maybe my world was generated in english ? 
The missing translation are fallback in english

**Comment by baguette-deluxe** [comment]
@lagonnebula Yes, you just need a fresh world with localization in french and test it with someone.

**Comment by beastyn** [comment]
Need to check with 9.0.3/ Locally I was fine. Please write here if an error occur after 9.0.3 update.
