### ISSUE TITLE
Cloud Worlds - Issue changing config options

### ISSUE THREAD

**Issue by kyle079** [StrangeLoopGames/EcoIssues#18324]
When trying to modify any config option on the Cloud Worlds page an error pops up saying "You are not logged in"

I have signed out of play.eco, cleared cache and cookies, and tried in a different browser (Chrome & Firefox).

**Comment by denysaw** [comment]
Probably world was restarted. We had bug with adminToken. 
Try now please (removed your adminToken), should work now.

**Comment by beastyn** [comment]
@kyle079 did it work for you?
