### ISSUE TITLE
Replace Constitution Font to original except in fallback cases

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18321]
![image](https://user-images.githubusercontent.com/3536496/93535351-a2cc5000-f8fb-11ea-86b6-dec6f89ceb85.png)
This font doesn't look like timeless statescraft for the ages, it looks like 3rd period cursive practice.  Change back to the original font, and make it fall back to this font if it doesnt have the symbols needed.

**Comment by D3nnis3n** [comment]
Didn't we want to choose a cool statescraft looking font that is readable and supports other characters? I don't even know why we switched to that font at all, the goal was to make it more readable for the many people that cannot read the original font well. This font obviously didn't live up to a constitution at all, but i'm sure there is fonts that do and are more easy to read.

**Comment by johnkslg** [comment]
That was the best that we could find it seems. 
I think we were trying to find something that had characters for all languages. But that probably doesnt exist for a cool statescraft font, so we will need fallback fonts
