### ISSUE TITLE
[0.9.0.2 beta develop-57] Objects not closing on exceeding range.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18327]
Open stockpile make it as small as possible, leave to the side; go out and mine fill carry slot and you can drag into stockpile with infinite range.
I can have several inventories open at the same time and transit items across the world.

Needs to close open windows when extending away from objects.

This applies to ALL objects, nothing closes down on range, courts, mint, store, stockpiles etc etc.

**Comment by SlayksWood** [comment]
check this one #18045 again after fixing this issue.
