### ISSUE TITLE
USER ISSUE: Upgrade stockpile with filters  ( ECO) 

### ISSUE THREAD

**Issue by JasonBourneTv** [StrangeLoopGames/EcoIssues#18330]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
there will be missing filters on the stockpiles

**Expected behavior:**
could you make an update to put filters on the stockpiles for example a stockpile with copper 

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a suggestion, not an issue. We also have one open for this already, so i'm closing this issue.
