### ISSUE TITLE
Server doesn't restore close button in console after exiting

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18331]
If you run the server in a console window, the close button will get disabled while running the server, but after the server exists it's still disabled.

**Comment by mirasrael** [comment]
Can you clarify the issue. If you exit the server how button may be disabled if you exited server and console window closed?

**Comment by redwyre** [comment]
if you run the server in an existing console window

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/120172356-a0045780-c20b-11eb-82b3-b29961dde5ab.png)
