### ISSUE TITLE
Better design of how to play for cloud worlds

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18333]

**Comment by j3fffff** [comment]
new styling on develop for how to play window.
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/c39315f6-1be3-45f9-b96c-a12eab26fd14)

@denysaw can you put an x in the corner to close it, and have it hidden forever if user closes it

**Comment by denysaw** [comment]
Done. Could be tested on Staging. To re-test (to make it shown again) just delete `closedHowToStart` flag from browser's LocalStorage.

**Comment by denysaw** [comment]
Implemented these improvements:
![image](https://user-images.githubusercontent.com/5720101/97744841-3478d100-1ae8-11eb-9f77-46edf42b1495.png)

Could be tested on Staging
