### ISSUE TITLE
USER ISSUE: Corrupted Map with identical minted currencies

### ISSUE THREAD

**Issue by d2d25** [StrangeLoopGames/EcoIssues#18338]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Make a money with a name.
Make other monay with the same name.
Restart the serv.

**Expected behavior:**
Corrupted map,
Unable to launch the map solo and on a dedicated serveur

**Actual behavior:**
Corrupted map,
Unable to launch the map solo and on a dedicated serveur

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_200919122823.log](https://github.com/StrangeLoopGames/EcoIssues/files/5248585/log_200919122823.log)

**Comment by d2d25** [comment]
We can therefore create a currency with the same primary key. (the uppercase may play a rock) But when loading, an exception is lifted

**Comment by beastyn** [comment]
@ptitducanh we can just restrict identical names case insensitive.

**Comment by WeaselDog** [comment]
So sorry to hear this happened @d2d25 . Your backup folder should have a save to restore the world from before this happened. We will be implementing a hotfix to prevent this in the future.
