### ISSUE TITLE
[0.9.0.2 beta release-73] [Linux client] collision with pipes

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18344]
if you connect 2 machines consuming water in parallel, then when one of the machines is turned on, a fountain of dirty water gushes at the place where the second machine is connected to the sewage system.
![изображение](https://user-images.githubusercontent.com/13696708/93662288-b85e8880-fa67-11ea-98b6-0d4d0d8363f6.png)

**Comment by SlayksWood** [comment]
@Astrija Can you add stations connection screen?

**Comment by Astrija** [comment]
video with problem:
https://youtu.be/c5CXIwZmGJA

**Comment by SlayksWood** [comment]
the same problem like here #11846. You have stockpile near pipe and pipe flow has visual glitches when stockpile inventory changes. So merged
