### ISSUE TITLE
Void items when picking up storage objects

### ISSUE THREAD

**Issue by cemeceme** [StrangeLoopGames/EcoIssues#18340]
**Version:** Eco Server 0.9.0.2 beta release-71
It is possible to void some items without creating trash using storage objects.
Checked this on a clean install of the server.

**Steps to reproduce:**
Chose an item with a weight low enough to hold an entire stack, but high enough such that a chest full of it is too heavy to carry at once. Something between 0.05kg and 0.3kg seems to work.

Fill a chest with that item.

Try to pick up that chest with a hammer. This transfer one stack into the players inventory

Repeat trying to pick up the chest.

**Expected behavior:**
Another stack gets transferred into the players inventory, up until the weight limit is reached, after which the action should fail with a message.

**Actual behavior:**
The players inventory fills up with that item up to the weight limit and also gives back the chest, destroying the remaining items that would have remained in the chest.

**Comment by SlayksWood** [comment]
it works with stockpiles too.

**Comment by SlayksWood** [comment]
> **Version:** 0.9.0.4 beta release-94
> 
> **Steps to Reproduce:**
> Go to tent storage and try to put pick and hammer in personal inventory when inventory is full.
> 
> **Expected behavior:**
> Item should have not been able to move into inventory and stayed put.
> 
> **Actual behavior:**
> Item disappeared from campsite inventory and did not end up in personal inventory. instead it just disappeared. Empty square still thinks item is there
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5358090/Player.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5358092/Player-prev.log)
> 
> though
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Still and issue: https://drive.google.com/file/d/19WMl5-Q2YfedGHEBrhCMc19KR1CGYT4P/view?usp=sharing
