### ISSUE TITLE
USER ISSUE: Cannot Drag Items

### ISSUE THREAD

**Issue by klavavaski** [StrangeLoopGames/EcoIssues#18343]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
1. Attempt to drag an item
2. While dragging the item, attempt to scroll the inventory

**Expected behavior:**
Continued dragging the item, and scrolled, to allow the sorting of items from inventory to inventory	

**Actual behavior:**
Drops the item from grab, places it in an unknown container, and either grabs another item under the cursor, or starts dragging an entire container around.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@klavavaski  Thank you for the report.
We have 2 issues which can confused you: #17721 and #12442. Can you take a look and say that you don't have these issues?
If you don't have it, then describe more you problem. I can't find another problem which you may have encountered.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
