### ISSUE TITLE
USER ISSUE: Wind ambiant song in Cold Forest Biome

### ISSUE THREAD

**Issue by dxtreme01** [StrangeLoopGames/EcoIssues#18341]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Being in the cold forest biome, outside or even inside a house and there is the ambient sound of the wind repeating itself over and over again to a point where it is no longer bearable.
We find ourselves forced to lower or even mute the sound of the game, or listen to music in the background when we spend hours in the area. Please do something.
The sound of the wind should stop when you are indoors.
And outside it shouldn't be windy 24/7. There should be some windy times and some less windy. At least add some audio variation, I say that because I've been listening to the same wind loop for several hours, and it's going to drive me crazy.
Thank you for your work ! Your game great ! :)

**Expected behavior:**
No indoor wind, or a better ambient sound loop for the wind.

**Actual behavior:**
The same wind song in your ears outdoors and indoors, and that, continuously 24/7.	
(can drive you crazy if you live and work in these biome)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Playing Vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@dxtreme01 
As far as I know, the wind level depends on your altitude. If you live high in the mountains, then a strong wind is possible.
What is the height coordinate of your house location?

**Comment by dxtreme01** [comment]
@SlayksWood 
Not so high, the top floor of the house is at 70.
And the ground level is at 64 where the road is and all the planted trees.
For example, the ground level of our desert biome is at 66, so I don't think I'm that high?
I have a mountain nearby, I didn't even manage to climb to the top, but I hit 102. So ... My house definitely not on top of a mountain with its 64 :)
