### ISSUE TITLE
USER ISSUE: Transparency broken on potted plants

### ISSUE THREAD

**Issue by kapawlak** [StrangeLoopGames/EcoIssues#18342]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
1. Put seed in potted plant (have tried blue stem, ocean spray, bull rush)
2. Look at plant. 

**Expected behavior:**
It should properly render foliage texture and transparency

**Actual behavior:**
Foliage will appear as retangular faces with the texture smeared over

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![plants](https://user-images.githubusercontent.com/29474019/93656720-36c41780-f9e1-11ea-997d-7efd223d5052.png)

![plants2](https://user-images.githubusercontent.com/29474019/93656753-7be84980-f9e1-11ea-8b1f-ac565da126f2.png)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5248959/Player-prev.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5248960/Player.log)
(also sometimes the  green select "ghost" won't go away)

**Comment by keegan-o** [comment]
These are not prefabs so I have no access to them on the art side-- I am guessing that code is setting the 'age' value of the fake plants to something above 1, or not setting it at all, which would break the alpha cutout. If need be, perhaps duplicate materials without age/pollution could be created. Otherwise, if possible, figure out a way to manually set alpha cutout on these materials/objects.

**Comment by keegan-o** [comment]
Actually, this is weird. I cannot repro this bug.

**Comment by SlayksWood** [comment]
@keegan-o Where did you try to reproduce it? in staging or develop?

**Comment by SlayksWood** [comment]
> Strange graphical glitch when placing some seeds in clay pots. See attached screenshots. Same occurs on other player's screen, though GM Ice Forge sees them as normal. The bug is repeated with huckleberry seeds, dwarf willow seeds. Taro root placed in the same way did not seem affected. Persists through game restart.
> 
> [DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5270543/DxDiag.txt)
> ![bug1](https://user-images.githubusercontent.com/71788933/94057816-71162600-fde0-11ea-94f3-5cbccb012309.jpg)
> ![bug2](https://user-images.githubusercontent.com/71788933/94057818-72475300-fde0-11ea-8f72-2002433078f9.jpg)
> ![bug3](https://user-images.githubusercontent.com/71788933/94057824-73788000-fde0-11ea-9a2b-527de93c279c.jpg)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5270564/Player.log)

> Same:
> 
> ![image](https://user-images.githubusercontent.com/48658286/94070041-37eaaf80-fdfa-11ea-8650-791d01c0e453.png)
> 
> ![image](https://user-images.githubusercontent.com/48658286/94070102-4fc23380-fdfa-11ea-9b03-d843f97be70b.png)

**Comment by ky0uraku** [comment]
![image](https://user-images.githubusercontent.com/48658286/94527258-607e0980-023f-11eb-8f2a-3830c52f1d5a.png)

**Comment by ky0uraku** [comment]
![image](https://user-images.githubusercontent.com/48658286/94610397-ea15f180-02a8-11eb-8006-47bd590d84e8.png)
