### ISSUE TITLE
[0.9.0.1-beta|0.9.0.2-beta-release-71] Districts missing from Zoning Office

### ISSUE THREAD

**Issue by SnakeSolidNL** [StrangeLoopGames/EcoIssues#18346]
Defined some districts using the Zoning Office (District Map 1), used /civics vote & /fin to finalize and enable a new district map.
Then upon editing the District Map 1 (became District Map 2) and using /civics vote & /fin, I got an error in the map viewer stating that Disctricts Map 1 was missing.
Trying to update Districts Map 2 to a new Districts Map (probably 3), the entire entry is gone from the Zoning Office.
(see screenshots for more information).
Cannot update any existing districts because there is no reference anymore.

(edit: I used the clearoldelections command after defining District Map 2, because there was a lot of clutter from old wrongfully created elections)

![scrn1](https://user-images.githubusercontent.com/38540031/93671761-0f834e00-faa6-11ea-8880-4eb8f0124b3b.png)

![scrn2](https://user-images.githubusercontent.com/38540031/93671762-1316d500-faa6-11ea-9041-f677404d1e61.png)

**Comment by SlayksWood** [comment]
merged to #16601
