### ISSUE TITLE
Unable to start Server with BadImageFormatException on Windows 10

### ISSUE THREAD

**Issue by Kampfmoehre** [StrangeLoopGames/EcoIssues#18345]
I can no longer start the Eco server since the PC crashed while playing and hosting the server.

I hosted my own world on the same PC as I was playing with the steam version of the Eco Server on Windows 10 x64. I played some days but yesterday the PC crashed while I was playing. Since then I can no longer start the Eco Server as it crashes with the following message:
```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Eco.Shared.Localization.LocString..ctor(Object s, Boolean localize)
   at Eco.Shared.Localization.LocString.Localized(String s)
   at Eco.Server.MainClass.Main(String[] args)
```

Things I have already tried:
- Copy an older backup of the world I was playing
- Remove the world to generate a new one
- Let steam check the game files
- Remove EcoServer.exe and let steam download it again
- Rename the directory  and let steam download everything again
- Download the server from the https://play.eco/account website
- run `sfc /scannow`
- run `DISM.exe /Online /Cleanup-image /Restorehealth`
- install dotnet core sdk (as I have guessed from the message that some framework files are broken)

The windows event log shows two events for each time I try to start the server. One shows the following (german):
```
Name der fehlerhaften Anwendung: EcoServer.exe, Version: 1.0.0.0, Zeitstempel: 0x5e9fbf92
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.488, Zeitstempel: 0x5b4a3325
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000000000023e49
ID des fehlerhaften Prozesses: 0x321c
Startzeit der fehlerhaften Anwendung: 0x01d68e6895e233f1
Pfad der fehlerhaften Anwendung: D:\Steam\steamapps\common\Eco Server\EcoServer.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 694fd887-3d97-4bc0-acd2-1ba85c1b8bbc
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

and the other shows nearly the same message as the Eco Server
```
Application: EcoServer.exe
CoreCLR Version: 4.700.20.20201
.NET Core Version: 3.1.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException: Could not load file or assembly 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Eco.Shared.Localization.LocString..ctor(Object s, Boolean localize)
   at Eco.Shared.Localization.LocString.Localized(String s)
   at Eco.Server.MainClass.Main(String[] args)
```

I guess the Eco Server is published as self-contained version and someow all contained in the exe. But it sure needs some system files that maybe did break somehow during the crash (I wonder how though). Can someone give me some hints as to what I can try to make it work again or what I can provide for further debugging?

Btw. the EcoServer32.exe is still working.

**Comment by redwyre** [comment]
Could you try opening `%TEMP%\.net\` in explorer, and delete any eco folders?

**Comment by Kampfmoehre** [comment]
Thanks that fixed it, the server now runs again.
