### ISSUE TITLE
5.6.2 staging 8802b6fc Problems with oil pumping jack

### ISSUE THREAD

**Issue by Ciannicay** [StrangeLoopGames/EcoIssues#1835]
* pump placed on unclaimed ground wont open GUI
* pump on claimed ground opens gui, but its completely full of recipie structures missiny any usable recipie

**Comment by Ciannicay** [comment]
* said recipie stubs cause crash when anything is ordered

--BEGIN DUMP--
Dump Time
08/04/2017 22:11:58

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC CreateWorkOrder on CraftingComponent!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.


Stack:
   bei Eco.Gameplay.Components.CraftingComponent.CreateWorkOrder(Player player, Recipe recipe, Int32 quantity)



Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   bei Eco.Plugins.Networking.Clients.ClientManager.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bson)
   bei Eco.Shared.Networking.NetPort.ProcessBuffer(Int64 maxMilliseconds)
   bei Eco.Shared.Networking.NetPort.Update(Int64 maxMilliseconds)
   bei Eco.Plugins.Networking.Clients.Client.<.ctor>b__49_0()

--END DUMP--

**Comment by craig-jong** [comment]
I'm not getting this issue when placing pumpjack and the dump seems like it's a non-pumpjack specific issue.

If someone can get steps to reproduce this, please reopen it.
