### ISSUE TITLE
Modkit Issue: <sprite> Not Working

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#18355]
Icons appear in game fine, So long as its setup "Right" the icon will disappear from the toolbar properly, 

However, if the sprites/images are custom the the game has a problem with displaying the icon in the chat and tooltips (kinda, the main icon shows but the the chat based icons don't)

this then gives us the <sprite="" name="" color=#>

Will attach unity files for inspection:

This doesn't happen if the icons are already in the game ( have tested it)

**Comment by TheKye** [comment]
[Icon Testing.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5251163/Icon.Testing.zip)
Find attached the unity files used for testing, includes:
cs
Compiled unity file ( its 16mb for a single icon?)
sprite sheets
Unity Scene

**Comment by redwyre** [comment]
This may be relevant: https://forum.unity.com/threads/sprite-asset-from-asset-bundle.794388/

@serpopov can you look at this?
