### ISSUE TITLE
Periodic network freezes with "thread pool starvation" error

### ISSUE THREAD

**Issue by ky0uraku** [StrangeLoopGames/EcoIssues#18358]
Linux, high-performance dedicated server.
version 9.0.2

About a day after turning on the server, more and more often errors begin to appear in the log:

```warn: Microsoft.AspNetCore.Server.Kestrel[22] Heartbeat took longer than "00:00:01" at "09/20/2020 10:17:41 +00:00". This could be caused by thread pool starvation.```

At the same time, the players in the game have a disconnect icon and freeze

After restarting, the problem goes away for a while.

**Comment by MishkaFur** [comment]
I have also been getting this but assumed it was more due to my servers older specs (opteron 6376, 128GB ram and Eco stored on SSD's), restarting it does seem to resolve it for a while

![image](https://user-images.githubusercontent.com/61889138/93757964-83853980-fbff-11ea-9c04-7dd29095148e.png)

Does not seem to coincide with other physical server load being high at the time,

**Comment by ky0uraku** [comment]
@MishkaFur We have a modern server with high performance Ryzen CPU, Eco's data is fully stored in-memory. The network stack is optimized, and the number of players is not large enough to significantly load the server - only 10-20 players simultaneously.

It is unlikely that the problem is in the hardware. Searching for similar error messages on Stackoverflow invariably leads to cases with problems on the application side.

**Comment by Praefator** [comment]
Yeah, getting similar issues on a Ryzen 3900x with 16 available threads (within a VM). Usually no higher than about 16 players at the same time, not leading to high utilization whatsoever

**Comment by mirasrael** [comment]
@ky0uraku @MishkaFur @Praefator can you make a process dump next time when you have spam of these messages and attach to the issue?

**Comment by Bazzi89** [comment]
We have the same issue on our server, restart helps for a while... then cpu-usage rises to 90+%, lagg, 60%, lagg, 99%, and back to 60-70%, same message in server console!

**Comment by MishkaFur** [comment]
I have not had this error again after moving to new hardware as discussed on discord, Praefator's server is vastly more powerful than even my new hardware.

Old hardware Opteron 6376 and 128GB ram Server 2019
New hardware Xeon 2690V1 but the game is running as a VM with 6 cores, 32GB ram and is Server 2016

@Bazzi89 what OS is your server? as it may be related to OS

**Comment by MishkaFur** [comment]
@mirasrael just had this on my server on the new hardware, first time in like 2 weeks and first time on my new hardware

![image](https://user-images.githubusercontent.com/61889138/96371292-e4e5ed00-1158-11eb-87f5-f67d67ade958.png)

A handful of users (about half) also got red DC then eventually booted to game main menu with no message, how shall i send or give you access to the file? it is 12GB uncompressed or 1.47GB compressed (a .rar)

**Comment by mirasrael** [comment]
I fixed major memory leak which may cause significant delays and threads freezing (due to GC blocks). Need to check if issue still persists after 9.1.

**Comment by MishkaFur** [comment]
@mirasrael 

I have been able to replicate the issue by causing high CPU load on the server which has the eco server itself (loaded up a second ecoserver which used high CPU whilst generating the world).

Seems to just be an issue when not enough cycles are available for the process ie something else having higher demand, priority of the process might be a work around?

**Comment by mirasrael** [comment]
Yes, this happens because of CPU starvation. It happens either because of heavy CPU load or because of lot of locks in GC (Garbage Collector) which pauses all threads and causes timeouts to expire.
