### ISSUE TITLE
USER ISSUE: Blast Furnace Output not Working

### ISSUE THREAD

**Issue by zigon15** [StrangeLoopGames/EcoIssues#18356]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Connect iron pipes to blast furnace smog/sewage output and vent the output somewhere else. The ground/air pollution stills builds up at the blast furnace location

**Expected behavior:**
Air/Ground pollution should build up at Smog/Sewage pipe end

**Actual behavior:**
Air/Ground pollution build up at blast furnace output

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@zigon15 Thank you for the report.
merged to #17316
