### ISSUE TITLE
USER ISSUE: Log in Error

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#18352]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
1. Try to log in to server.

**Expected behavior:**
It should have let me log on.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>No such host is known. No such host is known.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Shoe73** [comment]
Having the same issue.

**Comment by redwyre** [comment]
Our DNS provider is currently experiencing issues that may affect the ability to log in (eg "No such host is known." error). Unfortunately there it not much that can be done other than trying again.

**Comment by redwyre** [comment]
Our DNS provider has resolved the issue
