### ISSUE TITLE
Cloud World Issue - Can't update, sees server twice

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18359]
Customer:
FYI. I have gone into the world dashboard via Firefox to update our server to 9.0.2. At this moment, there are two odd things. A small one and a medium one.

Small thing: I have a doubled dashboard. That is, our one world appears twice on the dashboard. The two parts seem identical. Both have the same info, and both seem functional. (see attached screenshot)

Medium thing: I do not seem able to update to 9.0.2. When I click on the game versions dropdown list, 9.0.2 is not an option. (see second attached screenshot)

The 9.0.1 is working okay for us, so we can stick with it for another week. Still, it would be nice to upgrade when possible.

**Comment by j3fffff** [comment]
@redwyre can you check on 9.0.2 push to cloud worlds?

**Comment by j3fffff** [comment]
the double dashboard might have been because i was working with their world. i doubled it, and gave it to my user for testing.

**Comment by redwyre** [comment]
I have pushed 9.0.2 to docker
