### ISSUE TITLE
USER ISSUE: Salmon

### ISSUE THREAD

**Issue by Jockel380** [StrangeLoopGames/EcoIssues#18354]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
You can´t catch a salmon with bows under water. 

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I don´t have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StanKryvenko** [comment]
Fixed in SVN
