### ISSUE TITLE
Talents "Focused Workflow" works when you have two the same craft station.

### ISSUE THREAD

**Issue by jcbjoe** [StrangeLoopGames/EcoIssues#18362]
Hello,

The Focused workflow selected able talent for Basic Engineering does not seem to be working. I have tried multiple different configurations including having the wainwright table in a room on its own without anything else. The time always seems to be the same regardless. Note, each attempt I did put work into these tables because I have heard this is required too.

Version: 9.0.2

Room with 2 Wainwright tables: 
![image](https://user-images.githubusercontent.com/3605644/93716159-0b1e6a00-fb66-11ea-9d8d-c98d556824d8.png)

Room with only 1 Wainwright table and a few bits of furniture (not crafting stations):
![image](https://user-images.githubusercontent.com/3605644/93716190-4751ca80-fb66-11ea-93cf-ec35c47a1456.png)

However the skill says that the time should be doubled: 
![image](https://user-images.githubusercontent.com/3605644/93716203-5c2e5e00-fb66-11ea-9b75-c917b16e9672.png)

If you need me to do more testing let me know or if im doing something wrong

Thanks,
Joe

**Comment by SlayksWood** [comment]
@jcbjoe Thank you for the report.
This talent works, but effect will start work when you finish crafting 1 item in your project or start another one.
For example:
- I don't have any modules and talent isn't learned, I start 2 orders: Basic Engineering Basic Upgrade (2 min) and 10xAsphalt Concrete (4x10 = 40 min):
![image](https://user-images.githubusercontent.com/45708377/93734274-4316c300-fbe1-11ea-9260-db08126d72bc.png)
- learn talent:
![image](https://user-images.githubusercontent.com/45708377/93734295-59bd1a00-fbe1-11ea-83ee-f41265991fa5.png)
- I still have the same time numbers, but if I start another Basic Engineering Basic upgrade order then time will change:
![image](https://user-images.githubusercontent.com/45708377/93734339-912bc680-fbe1-11ea-924e-d86034a98466.png)
- or if I add resources and labor for 1 Asphalt concrete Time will change too when another Asphalt concrete should crafted:
![image](https://user-images.githubusercontent.com/45708377/93734762-4448ef80-fbe3-11ea-9a55-f5b641b742c3.png)
Now it takes 18 minutes instead 36 (9x4)
So closed.

**Comment by jcbjoe** [comment]
In both of my images, the recipes start from 15 seconds regardless if they are in a room on their own or with another wainwright table. If you like, later I can get screenshots of the recipes not started to prove that regardless of the amount of wainwright tables the time doesn't change.

**Comment by jcbjoe** [comment]
Hello @SlayksWood 

I have looked into this again.

This is a picture from me learning the skill

![image](https://user-images.githubusercontent.com/3605644/93811136-9a4f7e80-fc47-11ea-840b-4343aea08eaf.png)

In this image you can see the times are correct to your last image. HOWEVER you can also see there is TWO wainwright tables.
I thought this talent would only half the duration if there was ONE table?

Thanks,
Joe

**Comment by ninjabane** [comment]
I have a similar problem with Carpenter.  I have Focused Workflow: Carpentry and I noticed the recipe craft times on my Carpenter table were not halved.  I even picked up the table, put it in a new separate room with just a couple of chests and crafted a few items but it's still the same.  For example, the Board recipe is 6 seconds on the Carpenter table and it still takes me 6 seconds to craft while I assume it should be taking me 3 seconds.

I've noticed the difference between jcbjoe's room and SlayksWood's room is that jcbjoe is in a Tier 1 room and SlayksWood is in a Tier 2 room.  My Carpenter table is also using a Tier 1 room.  Could this be the problem?

**Comment by SlayksWood** [comment]
Step to reproduce:
- take any craft specialties (Carpentry)
- /levelup Carpentry and learn talent 'Focused Workflow':
![image](https://user-images.githubusercontent.com/45708377/93972198-8193b580-fd7a-11ea-8de6-dad9f121cf8b.png)
- place 1 Carpentry table and start butchery table project. It takes 1 minute:
![image](https://user-images.githubusercontent.com/45708377/93972286-a5ef9200-fd7a-11ea-86e6-d88d9a29cc7d.png)
- place second Carpentry table and start another butchery project. It will take 1 minute, but will show in recipe 2 minutes:
![image](https://user-images.githubusercontent.com/45708377/93972357-cae40500-fd7a-11ea-9523-0f1eba2513a9.png)

**Comment by ShoppyCodes** [comment]
Can confirm this also does nothing to carpentry. Tested with making 1 Hewn log with 1 carpentry table and 2 in the same room.

**Comment by thomasfn** [comment]
Confirming that this still occurs as of 0.9.2.4 beta release-156, and affects all professions that have the focused workflow talent (just reproduced it on an official server with Advanced Masonry).

**Comment by WeaselDog** [comment]
@Quadbro Let me know if you guys need help figuring out expected behavior
