### ISSUE TITLE
USER ISSUE: Graphical Bug, Shader's are Black

### ISSUE THREAD

**Issue by Sarumaas** [StrangeLoopGames/EcoIssues#18367]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
1. Start the Game
2. Wait for the first night
3. Since then all effects and windows are black

**Expected behavior:**
Normal, transparent. Shaderbug i think

**Actual behavior:**
Black, shader incorrect

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and no

**System:**
Intel i7-4790
24 GB (DDR3) RAM
AMD R9 Fury Nitro (Sapphire) 4 GB VRAM (HBM) [Radeon Software Driver 20.9.1]
Windows 10 Pro

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5254212/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5254213/Player-prev.log)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5254216/output_log.txt)
![Eco_2020_09_21_10_15_26_269](https://user-images.githubusercontent.com/71633422/93747092-7b74cc00-fbf6-11ea-9122-32c37f78674b.png)

**Comment by SlayksWood** [comment]
merged to #14042
