### ISSUE TITLE
USER ISSUE: Cant log in

### ISSUE THREAD

**Issue by gamingsheep003** [StrangeLoopGames/EcoIssues#18360]
\
**Version:** 0.9.0.2 beta staging-1794

**Steps to Reproduce:**
Type login stuff and press the Login button

**Expected behavior:**
I should've logged in

**Actual behavior:**
The following error message popped up:
Username or Password incorrect (I actually dubble checked both)
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That's a support issue, please contact support@strangeloopgames.com.
In any case, request a new password from the website and see if it works.
