### ISSUE TITLE
USER ISSUE: Basic Mining Upgrade 1

### ISSUE THREAD

**Issue by TenshiKira** [StrangeLoopGames/EcoIssues#18364]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
1. make crushed iron ore without basic mining upgreade 1: resources needed 12 iron ore
2. make crushed iron ore WITH basic mining upgreade 1: resources needed 12 iron ore

**Expected behavior:**
step 2: reduce resources needed by 50% it says

**Actual behavior:**
Step 2: crafting time reduces by half but not the recources needed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Intended. The upgrades only work for time where the reciped have a yellow border.
