### ISSUE TITLE
Random crash on moving items to chest from inv

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#1837]
Was droping items into a chest and the game crashed and gave me a bug report folder thingy,
im runing 5.6.1
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1202882/DxDiag.txt)

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1202883/output_log.txt)

[error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1202884/error.txt)

[crash.dmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1202885/crash.dmp.txt)

All files have added .txt to the end of them for easy upload

**Comment by MarjieAVolk** [comment]
This should be fixed in staging now
