### ISSUE TITLE
[9.0.2] Flat roof blockform clipping

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#18373]
![20200921151935_1](https://user-images.githubusercontent.com/841990/93772008-922f1900-fc1e-11ea-918e-bca273bdd352.jpg)

See above, whenever furniture is placed next to flat roofs (when used as "window sills"), these sort of issues come up. Is there any way for the flat roof to acknowledge furniture as if they are "an adjacent block" so that it reverts to the full wall form on that side?

**Comment by keegan-o** [comment]
Fixed but unfortunately the logic for detecting if there are objects will only work (without ballooning the rules insanely) with whether they are clipped into, not with whether they are occupying any of the 'solid' spots in the builder. Thus, the clipping will be fixed but now you may find the builders too shy about world objects-- if one is detected on any side, it won't allow the ledge to form. One potential quick fix to all of this may be to see if we can make 'WorldObject' blocks be detected as 'Solid' by builders. That could result in some awkward behaviors as well though, so don't expect the fix soon.
