### ISSUE TITLE
Changing currency in shop disconnects the client

### ISSUE THREAD

**Issue by patrickvandijk** [StrangeLoopGames/EcoIssues#18385]
Tested with more users. Change the currency of the shop in 0.9.0.2 disconnects the client. The currency is set. Reconnect is possible. Server is not crashing.

**Comment by SlayksWood** [comment]
@patrickvandijk Thank you for the report. I can't reproduce it and don't have this issue. Can you provide log file when it happens next time? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file.
And maybe some additional information about currency in your server and shops will help us. It would be great if you provide save files too. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Praefator** [comment]
Possibly related to #18376

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
