### ISSUE TITLE
pause button should sync with game

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18388]
we need a game metric on whether server is paused or not. it gets too easily unsynced from our web tracking of it.

Game Side: add 'pause: on or off' to /info or another query.

Web Side: detect pause setting from game server query

**Comment by gzatravkin** [comment]
Added https://github.com/StrangeLoopGames/Eco/pull/6967 to serverInfo as IsPaused (bool)

**Comment by denysaw** [comment]
Done. Could be tested on Staging with new worlds (which go from develop branch).
