### ISSUE TITLE
Teacher Verification and allow access to CW

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18381]
on db viewer, adding user as a teacher, reloads the page. dont reload page

if marked as a teacher, let them buy cloud worlds. including seeing buy links on cw and education sales pages

**Comment by denysaw** [comment]
Done. Could be tested on Stagingland.

**Comment by j3fffff** [comment]
@beastyn you can set your test user as a teacher using the db editor
