### ISSUE TITLE
Invites bug

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18389]
3 for a 6

**Comment by denysaw** [comment]
@j3fffff A little wider description would help here :)

**Comment by j3fffff** [comment]
haha, sent you in secret

**Comment by denysaw** [comment]
Attempted to fix it. But if it'll help we'll know just after some time passed. As seems it's cuzz of rare case when PayPal calls IPN twice. There was no check, that user shouldn't be rewarded if he somehow gets same tier, which he already owns.

**Comment by j3fffff** [comment]
i think there is a check if ipn has a duplicate transaction #
but im guessing the invites send off before that is checked?
So maybe, wait to update our all_purchases table with transaction # and/or check if all_purchases already has that txn #
Then after that, updating all other accounts purchases, like invites.
