### ISSUE TITLE
Grafik (particle?) Problem

### ISSUE THREAD

**Issue by Madkuya** [StrangeLoopGames/EcoIssues#18383]
If you remember me. As you may know its Impossible for me to Play on Win7  i now run on Win 10.

Every block Placement or Destruktion or Stockpile movement creates Black Spheres. 
![20200921203808_1](https://user-images.githubusercontent.com/71166724/93809552-b2c29780-fc4d-11ea-9667-242c719fb733.jpg)
![20200921204031_1](https://user-images.githubusercontent.com/71166724/93809592-bd7d2c80-fc4d-11ea-9783-6812198bfac9.jpg)
![20200921203807_1](https://user-images.githubusercontent.com/71166724/93809634-c968ee80-fc4d-11ea-9552-7d3c4a584436.jpg)

Updating the Grafikstriber works for a while.  But now its just back for no reason. 

Win 10 Pro
AMD FX(tm)-6300 Six-Core Processor 3.50 GHz
RAM 24GB
64-Bit Operating System

Nvidia GeForce GTX 1050 Ti  (newest triber 456.83)

**Comment by SlayksWood** [comment]
@Madkuya Does the client restart help you? It can happen with every player if they move faster than chunks load or use some admin commands like fly, teleport. We have another issue about that #14042

**Comment by Madkuya** [comment]
Well i relog and after i come back it was gone, but like after 30 seconds  all plants on the wohle Planet dies. Every Plant exept from Trees was dead.  Today i will delete all Storage again and Create the Planet again  from scrap.

**Comment by SlayksWood** [comment]
@Madkuya this is another known issue. thank you for the answer, merged to #14042
