### ISSUE TITLE
[0.9.0.2 beta release-71] Users get kicked out of the server when using my hostname to connect

### ISSUE THREAD

**Issue by coolfarmer** [StrangeLoopGames/EcoIssues#18382]
I'm using the service NoIP (https://www.noip.com). For example: coolfarmer-pc.no-ip.info:3000

Since your provider has problems with their DNS, my friends are constantly disconnected from my server, every 5-10 minutes (mosthly people in North America, users in Europe have less problem).

I don't know what to do. I posted an issue like this one during the week before the release and the problem was fixed by itself after a new version.

Server log: https://gist.github.com/coolfarmer/bc28e400cbf0bc3247192610b3e62559

**Comment by beastyn** [comment]
@coolfarmer Thank you for the report.
Please provide the config files from your server

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
