### ISSUE TITLE
DisplayName for RecipeFamily can not return a NotTranslated version.

### ISSUE THREAD

**Issue by FyreAus** [StrangeLoopGames/EcoIssues#18386]
Class Recipe Family contains:
`public LocString DisplayName => Localizer.Do($"{this.RecipeName} Recipe");` 
and
`[SyncToView] public string              RecipeName       { get; protected set; }`

This means DisplayName would translate this string inside to the localized version, calling `DisplayName.NotTranslated` should in theory return the unlocalized version of the string regardless of language setting.

However.. RecipeName is set from an already localised string in the Initialize methods
```
protected void Initialize(LocString displayText, Type recipeType)
        {
            ...
            this.RecipeName = displayText;
            ...
        }
```

This means the string being passed to DisplayName has been pre-Localized and calling DisplayName.NotTranslated will only ever return the translation of the argument displayText passed into the Initialize method.

This seems to only be a problem for Recipe Family.

The fix is to either change what is being passed into the initialize method to be a string (which involves fixing every Recipe Family class) or to change the line in the initialize method from 
`this.RecipeName = displayText;`   to   `this.RecipeName = displayText.NotTranslated;`

**Comment by Quadbro** [comment]
Nice find!
