### ISSUE TITLE
Admin and user re-send invitation logic

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#18387]
@D3nnis3n:
```
For future easy fix:
Allow users to see to whom they sent invites and allow to resend.
Allow resending invites for admins in the admin db when clicking on invites for a user.
```

**Comment by denysaw** [comment]
@j3fffff Make please some design for the first point. And I'll alive that with logic.

**Comment by denysaw** [comment]
@j3fffff Deal? :)

**Comment by j3fffff** [comment]
deal :)

**Comment by denysaw** [comment]
@j3fffff Great, please, write me when I can pull (push right to develop as usual) so I can put some logic on it ;) Thanx

**Comment by j3fffff** [comment]
updated styling

**Comment by denysaw** [comment]
Added design and logic also to the admin UI as was described in title and description :)
![image](https://user-images.githubusercontent.com/5720101/100401194-0f30a180-3059-11eb-8086-98f42f594d22.png)
