### ISSUE TITLE
[0.9.0.2 beta develop-60] On/Off button disable/Off state missing graphic

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18398]
Off state on the switch is not in the correct layer or is missing img as its just a white box.

machine is on ( just missing connection so ignore red light )
![Screenshot_5.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/e612e776-4e32-4506-9547-91cd64be98b9)

Machine disabled state missing icon.
![Screenshot_4.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0b2449bc-f606-4e63-9866-d5f755ee54a3)

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/6849
