### ISSUE TITLE
Incorrect cursor behavior

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18392]
![animx22](https://user-images.githubusercontent.com/3536496/93845272-1603f800-fc55-11ea-8ca6-4de8eeb3046e.gif)
After closing this dialog box, my cursor disappeared, even though the world object window was still open.

**Comment by johnkslg** [comment]
Also noticed, when you close a UI the cursor doesnt disappear till it fades out. If the cursor is supposed to disappear, it should do so immediately, not wait for the fadeout (noticeable on popups)

**Comment by IcedForge** [comment]
This is a global effect, same for selecting object types in f.ex the Mint where it closes the sub window and it hides the mouse, this should not happen until all other windows are closed down ( with the exclusion of the inventory bag of course ).
