### ISSUE TITLE
Cleanup notification panel

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18393]
![image](https://user-images.githubusercontent.com/3536496/93846323-882a0c00-fc58-11ea-8d20-c146cdd753e6.png)
- Floating text 'no notifications' in there
- Dont show voting as mail
- See what else spams it up that shouldnt be in here (ask QA)

**Comment by IcedForge** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/18380 closely related issues

**Comment by gzatravkin** [comment]
Removed votes from here. 
CNR No current notifications. Any hint to repro? QA? Was it only at unity or in release too?

**Comment by SlayksWood** [comment]
- [ ] 1. Still here, but this is appearenced sometimes, don't have any steps(. If you don;t fix it next time than I'll create a sepparate issue for investigate:
![image](https://user-images.githubusercontent.com/45708377/95335020-89457500-08b7-11eb-8ee3-68f619dd7b06.png)

- [ ] 2. Have empty pending elections, but this one should appear when you have any election here:
![image](https://user-images.githubusercontent.com/45708377/95335171-b8f47d00-08b7-11eb-8273-71ea7a31c1ff.png)
Or I'm wrong and now it has another behavior?

**Comment by gzatravkin** [comment]
1. Could you attach log file when happened? Maybe some exception is there
2. It suppose to show only elections pending to vote, where you can vote. You had some election without your vote and it don{t shoved it? Anyway the idea is that this icon disappear if is empty.

**Comment by SlayksWood** [comment]
1. [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5341015/Player.log)
2. I don't have any election on this server at all on that moment.

**Comment by SlayksWood** [comment]
1. I will be watching for a couple of days.
2. Still have without any election:
![image](https://user-images.githubusercontent.com/45708377/96442933-8e3de900-1214-11eb-9f02-a1f350ce1867.png)

**Comment by IcedForge** [comment]
Still an issue in [0.9.1.0 staging-1823]

**Comment by gzatravkin** [comment]
@IcedForge  still an issue - part 1 too or just elections?

**Comment by IcedForge** [comment]
Looks like side bar notifications are fine now.
