### ISSUE TITLE
[os-0907c] Issues with actions

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18396]
for this https://github.com/StrangeLoopGames/Eco/pull/6740

- [x] 1) Rubbles can be duplicated.

Just cut some rubbles and place them. You can make it fast or placing them in a stock. At some point they start to duplicate.
Also you will have invisible rubble in you hand (try to take shovel, for example)
https://drive.google.com/file/d/1JHNkEYbvDQq-XCcITcnnP06ybxCNyeVq/view?usp=sharing

- [x] 2) Can't place blocks on grass

Take a brick. Try to place it (or build it) on a grass, You can't
![bandicam 2020-09-22 14-27-24-119](https://user-images.githubusercontent.com/27898520/93865609-ff56b300-fcdf-11ea-804b-f22ce274ff20.jpg)

- [x] 3) Can't harvest Camas anymore with shovel

- [x] 4) Can plow a road with  a tractor and a hand plough.

**Comment by SlayksWood** [comment]
fixed in os-0907c. check after merge.
