### ISSUE TITLE
Broken item link

### ISSUE THREAD

**Issue by Calura** [StrangeLoopGames/EcoIssues#18404]
Most likely caused by a player having a name similar to the item.

![brokenlink](https://user-images.githubusercontent.com/53465919/93897188-c73f7800-fcbf-11ea-8eca-861318da2d15.jpg)

**Comment by johnkslg** [comment]
It looks like the code that scans the user input for tags is finding a tag inside a tag?

**Comment by johnkslg** [comment]
@mirasrael just refactored tag parsing, consult him on this please

**Comment by mirasrael** [comment]
I guess it is issue in TextLinkManager which replaces item name within user name.
Like "The Rocker" => "<link id="user:The Rocker">" => <link id="user:The <link id="item:Rocker">>
Probably we need unit tests for TextLinkManager to identify such cases.

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/103071497-c0811380-45d4-11eb-9ebb-0bb9c626e6fb.png)

**Comment by Daniel-Magulado** [comment]
Build: Staging
Repro: Unable to reproduce. Appears to be fixed.

![The Rocker Box ID Link.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/3e00ec27-834b-4c81-afd7-1d070b010d9d)

Observation: The chat behavior now prioritizes which ID it detects first. For the term "The Rocker Box," the chat links the user's name "The Rocker" without any issues.

Resolution: Closing.
