### ISSUE TITLE
dashboard map not showing water

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18407]

**Comment by denysaw** [comment]
@gzatravkin Not sure it's web at all, so re-assigning on you. If that will be web and too pain in the ass, re-assign back on me ;)

**Comment by gzatravkin** [comment]
CNR. 
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/a3ab77c4-2cb7-4770-bac4-4eb666ba4fa5)

Any specific steps?

**Comment by j3fffff** [comment]
seems to be working now. good job :D
