### ISSUE TITLE
User can no longer delete their own proposed law

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1840]
Previously a user could remove their own proposed law.

Now only admins can.

I think we should allow the law proposer to remove it, incase they made a mistake.

**Comment by MarjieAVolk** [comment]
I removed it intentionally.  The proposer can still remove their law during the voting phase, but after it has been voted into effect they can't.  It seems like a huge loophole to allow the proposer to just cancel their law at any time, after the server has already voted on it.  They have lots of time to remove it during the voting phase if there is something wrong with it.
