### ISSUE TITLE
[0.9.0.2 beta release-71] Linux: Tools rotated upside down

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18414]
My character seems to have adopted a rather unique way of holding her pickaxe. Breaking stone works perfectly fine though and the animation seems fine I think, so it's only the placement of it. Please also note the distortions in the picture. Sometimes when dialogues are closed they leave that behind. I haven't restarted the game, so I assume the player log is identical as the one in my previous post
![Pickaxe](https://user-images.githubusercontent.com/30699769/92997468-cf572500-f513-11ea-860f-ad707d7b3b09.jpg)

Edit: I'll just add that this applies to other tools as well. Works fine, but is incorrectly placed on the screen

_Originally posted by @AHSauge in https://github.com/StrangeLoopGames/EcoIssues/issues/18081#issuecomment-691496824_

**Comment by redwyre** [comment]
It just occurred to me this is probably something to do with the FPV code pulling values directly out of the projection matrix

**Comment by jomu78** [comment]
I have the same bug on Ubuntu 20.04, Nvidia 1060 installed. On the same system running Windows 10, the game is running fine . The world is hosted on a Linxu server so it is the same world.

**Comment by JanThomas118** [comment]
Same issue here. Fedora 32 with an AMD RX480 (amdgpu driver)

**Comment by muthenberg** [comment]
I've got the same issue under Ubuntu 18.04 and now 20.04. Works fine under Windows on the same machine.

**Comment by sigi714** [comment]
Can confirm on 0.9.1.7. Ubuntu 20.04. 
AMD Ryzen 5 1600 Six-Core Processor
Radeon RX550/550 Series (POLARIS12, DRM 3.35.0, 5.4.0-54-generic, LLVM 10.0.0) (0x699f)
client glx vendor string: Mesa Project and SGI

**Comment by mirasrael** [comment]
Blocked by this Unity issue https://issuetracker.unity3d.com/issues/crash-on-vkgetinstanceprocaddr-when-consecutively-executing-a-method-for-a-number-of-meshes-which-creates-a-cropped-4k-texture which prevents us from run Unity Editor with Vulkan API to reproduce and fix the issue.

**Comment by Tiefseefisch246** [comment]
Same on MacBook Air with the new M1 chip

**Comment by dimension128** [comment]
Same on arch, NVIDIA 455.45.01
Also, possibly related: the tomato plant is invisible.

**Comment by AsbjornOlling** [comment]
I'm having this issue on a fresh install of Eco global survival today.

Ubuntu 20.04
Nvidia GTX1070
nvidia-driver-450

**Comment by raymondbh** [comment]
Same issue here on linux, but not when I run with Proton. But performance is better with linux native so please fix this. Like the game very much, but this is very annoying to play with. A -1 to the z axis should do the trick.

**Comment by LottieVixen** [comment]
A fix I have found for this on Linux (steam) is go to the game, properties, compatibility and check "Force use of a specific tool" then select Proton 5.13-6 
![image](https://user-images.githubusercontent.com/495512/119126730-493c9800-ba2b-11eb-9af2-fa61cd36a05e.png)

![image](https://user-images.githubusercontent.com/495512/119126816-71c49200-ba2b-11eb-9de1-49939b3548cd.png)

working as of 9.3.4 beta release-226

**Comment by raymondbh** [comment]
Not really a fix, you just run the Windows native in Proton (wine) mode. But it kinda works so...

**Comment by jomu78** [comment]
@SlayksWood: / @mirasrael why is this bug closed?  In which version is this fixed? As mentioned above the "solution" above is just a workaround.

**Comment by redwyre** [comment]
It's fixed in 9.4 which will be available soon
