### ISSUE TITLE
Add option to reset world with new world seed

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18410]
you can load randomly generated world by adding this to /start config
`"Storage.eco": "{\"NewGameTemplate\": null}"`

In UI, either add a checkbox, or a popup to give this as an option for users.

**Comment by j3fffff** [comment]
call it 'New Map'
have it autochecked

**Comment by j3fffff** [comment]
this is for the /worlds page. This check box will be available for each world, next to the Advanced Options > Clear Save

**Comment by denysaw** [comment]
Could be tested on Staging. As for this issue it's done only to users (w/o admin interface changes).

**Comment by SlayksWood** [comment]
I have option: 
![image](https://user-images.githubusercontent.com/45708377/99650916-0ba08780-2a67-11eb-90af-2eccec96f3af.png)
But it always uses default world.

**Comment by j3fffff** [comment]
tested and working with postman

**Comment by denysaw** [comment]
Really. FIxed. Also hotfixed on Prod.
