### ISSUE TITLE
Items Transferred still linked in inventory

### ISSUE THREAD

**Issue by DragoonWise** [StrangeLoopGames/EcoIssues#18412]
Didn't found this issue, so i hope it's not already reported.

![382310_screenshots_20200922174412_1](https://user-images.githubusercontent.com/58194005/93909115-ba427900-fcff-11ea-9b65-5e048e6ec35e.jpg)

i transferred pumpkin from inventory to chest and when i put cursor on previous spot in inventory, the empty spot say it's pumpkin.

**Comment by beastyn** [comment]
@DragoonWise thank you for the report.
Yeap, issue is pretty old and living in here #11519
