### ISSUE TITLE
[0.9.0.2 beta release-71] Mac: Unable to connect to any server

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18419]
Running the "Eco Server" (also from steam) does seem to work. However, the Mac client still has the connect timeout issue mentioned above. Let me know if there's anything I can do to increase the logging verbosity of the Eco Mac client. Again, this is `0.9.0.2 beta release-65` 

```
JohnMayer:~ johnmayer$ nc -v -z localhost 3001
Connection to localhost port 3001 [tcp/redwood-broker] succeeded!
JohnMayer:~ johnmayer$ nc -u -v -z localhost 3000
Connection to localhost port 3000 [udp/hbci] succeeded!
```

End of server logs:

```
[14:54:08.779] [5] [ Info] [Eco] Initializing WebServerPlugin...  
[14:54:08.783] [16] [ Info] [Eco] Skipping Windows firewall setup, platform = Unix
 
[14:54:08.783] [16] [ Info] [Eco] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
 
[14:54:09.532] [16] [ Info] [Eco] Web Server now listening on: http://[::]:3001
 
[14:54:09.534] [5] [ Info] [Eco] Initializing WebServerPlugin... Finished in 754.7ms
 
[14:54:09.534] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin...  
[14:54:09.534] [5] [ Info] [Eco] Initializing IntegrationTestsPlugin... Finished in 0.1ms
 
[14:54:10.140] [5] [ Info] [Eco] Saving world...  
[14:54:10.276] [205] [ Info] [Eco] Skipping Windows firewall setup, platform = Unix
 
[14:54:10.276] [205] [ Info] [Eco] (You may need to manually open port 3000 if the EcoGameServer is inaccessible)
 
[14:54:23.451] [5] [ Info] [Eco] Saving world... Finished in 13,310.3ms
 
[14:54:23.452] [5] [ Info] [Eco] [Server Initialization]... Finished in 94,825.4ms
```

Client Message

```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Log File missing.
```

_Originally posted by @johnpmayer in https://github.com/StrangeLoopGames/EcoIssues/issues/18081#issuecomment-692248265_

**Comment by redwyre** [comment]
Something to do with IPv4/IPv6, I asked @johnpmayer to try setting the IPAddress in the network config to 127.0.0.1 to force it to use IPv4, and it crashed:

> Setting IPAddress to 127.0.0.1:
> 
> I got more logs from running from the terminal, an unhandled exception:
> 
> ```
> [03:20:20] Initializing NetworkManager... 
> [03:20:20] Initializing NetworkManager... Finished in 26.3ms
> [03:20:20] Initializing WorldLayerManager... 
> [03:20:20] Initializing WorldLayerManager... Finished in 0.1ms
> [03:20:20] Initializing WebServerPlugin... 
> [03:20:20] Skipping Windows firewall setup, platform = Unix
> [03:20:20] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
> [03:20:21] Web Server now listening on: http://[::]:3001
> [03:20:21] Initializing WebServerPlugin... Finished in 771.0ms
> [03:20:21] Initializing IntegrationTestsPlugin... 
> [03:20:21] Initializing IntegrationTestsPlugin... Finished in 0.1ms
> [03:20:21] Saving world... 
> Unhandled exception. System.InvalidOperationException: Host creation call failed
>    at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit, UInt32 incomingBandwidth, UInt32 outgoingBandwidth, Int32 bufferSize)
>    at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit)
>    at ENet.Host.Create(Address address, Int32 peerLimit)
>    at Eco.Networking.ENet.ENetUdpPeer.Start()
>    at Eco.Plugins.Networking.NetworkServer.Initialize(IUdpLibrary udpLib)
>    at Eco.Plugins.Networking.NetworkManager.Run()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ThreadHelper.ThreadStart()
> Abort trap: 6
> ```
> 
> BTW, what's the difference between "IPAddress" and "RemoteAddress" in Network.eco?

**Comment by johnpmayer** [comment]
I'll keep an eye on the thread; let me know if there is a new build / configuration and you'd like a quick test run / get new log files. The above is from 65

**Comment by johnpmayer** [comment]
Quick periodic update, issue persists on `0.9.0.3 beta release-78`

Note that I do get nice logs that the web server is listening on 0.0.0.0, which I explicitly configured, but there are no such logs for the address that the game server (ENet UDP) is listening on. Adding that would probably be useful.

(In-Game Dialog)

```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Log File missing.
```

(Player.log)

```
LocalServer -  Initializing WebServerPlugin... 
LocalServer -  Skipping Windows firewall setup, platform = Unix
LocalServer -  (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
LocalServer -  Web Server now listening on: http://0.0.0.0:3001
LocalServer -  Initializing WebServerPlugin... Finished in 627.7ms
LocalServer -  Initializing IntegrationTestsPlugin... 
LocalServer -  Initializing IntegrationTestsPlugin... Finished in 0.2ms
LocalServer -  Saving world... 
LocalServer -  Skipping Windows firewall setup, platform = Unix
LocalServer -  (You may need to manually open port 3000 if the EcoGameServer is inaccessible)
LocalServer -  Saving world... Finished in 4,056.2ms
LocalServer -  [Server Initialization]... Finished in 34,295.0ms
[05:21:56.931] Connecting to local host. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[05:21:56.932] Connecting to 127.0.0.1:3000...
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[05:21:56.932] Connection complete. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[05:22:11.982] Disconnected with error: Failed to connect - connection timed out. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
LocalServer -  Saving... 

Unloading 15 unused Assets to reduce memory usage. Loaded Objects now: 90376.
Total: 305.267626 ms (FindLiveObjects: 3.364415 ms CreateObjectMapping: 5.938405 ms MarkObjects: 295.777351 ms  DeleteObjects: 0.187065 ms)

LocalServer -  Saving... Finished in 1,040.8ms
LocalServer -  Shutdown finished
```

(Network.eco)

```
{
  "PublicServer": false,
  "Playtime": "",
  "Password": "",
  "Description": "JohnMayer",
  "DetailedDescription": "",
  "ServerCategory": "None",
  "IPAddress": "0.0.0.0",
  "RemoteAddress": "",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 20,
  "MaxConnections": -1,
  "ID": "b4ca80a4-166b-4646-adf3-0c9a183d95cc",
  "Passport": "42fc395e-80e0-47cf-be8f-0c80c24fdfff",
  "UPnPEnabled": true
}
```

**Comment by riedeljan** [comment]
Hey guys,
I've got very similar problems.

I set up my server with 9.0.2 & 9.0.3 standalone builds on a debian VPS.
So far, the web server listens on i`pv4:3001` internally which is fine.

But no matter what "IPAddress" I set or how I change the config, the gameserver always seems to listen on `ipv6:3000`.
`EcoServer 3854 3945 EcoServer  ecoserver  394u     IPv6              34664      0t0        UDP *:3000`

Sadly I've got no possibilities to route v6 traffic to my host right now but anyway would expect the server to listen on v4 when I specify `127.0.0.1` or `0.0.0.0` as "IPAdress".

**Comment by johnpmayer** [comment]
Confirming another detail brought up on the email chain that, using lsof, I can see that the EcoServer game service is using IPv6 

```
JohnMayer:Server johnmayer$ lsof -i TCP:3001 -i UDP:3000 -P
COMMAND     PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
EcoServer 20246 johnmayer  378u  IPv4 REDACTED      0t0  TCP *:3001 (LISTEN)
EcoServer 20246 johnmayer  405u  IPv6 REDACTED      0t0  UDP *:3000
```

It is *really* curious that the game crashed with 127.0.0.1; this feels like it has to be just a silly bug in how `Eco.Networking.ENet.ENetUdpPeer.Start` calls the ENet APIs...

**Comment by mirasrael** [comment]
Hi @johnpmayer Did you try to set IPAddress to 127.0.0.1 or other non-broadcast IP?

**Comment by johnpmayer** [comment]
Update (0.9.0.3 beta release-82)

I ran a more specific lsof:

```
COMMAND     PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Eco       82290 johnmayer   79u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP localhost:65507->localhost:57343 (ESTABLISHED)
Eco       82290 johnmayer   84u  IPv6 REDACTEDxxxxxxxxxx      0t0  UDP *:61031
Eco       82290 johnmayer   90u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65521->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
Eco       82290 johnmayer   91u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65511->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
Eco       82290 johnmayer   96u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65516->phy-v100-74-201-103-217.vivox.com:https (ESTABLISHED)
Eco       82290 johnmayer   97u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65513->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
Eco       82290 johnmayer   98u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65514->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
Eco       82290 johnmayer   99u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65517->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
Eco       82290 johnmayer  100u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP REDACTEDMYIP:65518->ec2-52-10-137-131.us-west-2.compute.amazonaws.com:https (CLOSE_WAIT)
EcoServer 84151 johnmayer  378u  IPv4 REDACTEDxxxxxxxxxx      0t0  TCP *:redwood-broker (LISTEN)
EcoServer 84151 johnmayer  406u  IPv6 REDACTEDxxxxxxxxxx      0t0  UDP *:hbci
```

Both the Eco game client and the EcoServer game ports on UDP are runnong IPv6. This is using "Any" in Network.eco.

I also tried setting my IP in Network.eco; this time taking my "public" network device ip, rather than loopback 127.0.0.1, but I get the same behavior, the game socket failing to get created.

```
[01:05:45] Initializing WorldLayerManager... Finished in 0.1ms
[01:05:45] Initializing WebServerPlugin... 
[01:05:45] Skipping Windows firewall setup, platform = Unix
[01:05:45] (You may need to manually open port 3001 if the EcoWebServer is inaccessible)
[01:05:45] Web Server now listening on: http://REDACTEDMYIP:3001
[01:05:45] Initializing WebServerPlugin... Finished in 654.6ms
[01:05:45] Initializing IntegrationTestsPlugin... 
[01:05:45] Initializing IntegrationTestsPlugin... Finished in 0.1ms
Unhandled exception. System.InvalidOperationException: Host creation call failed
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit, UInt32 incomingBandwidth, UInt32 outgoingBandwidth, Int32 bufferSize)
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit)
   at ENet.Host.Create(Address address, Int32 peerLimit)
   at Eco.Networking.ENet.ENetUdpPeer.Start()
   at Eco.Plugins.Networking.NetworkServer.Initialize(IUdpLibrary udpLib)
   at Eco.Plugins.Networking.NetworkManager.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abort trap: 6
```

I'm assuming both Eco and EcoServer using ENet, and am guessing that the game client is similarly hard-coded to Any (so it doesn't crash, but defaults to listening on IPv6). And for some reason, IPv6 UDP sockets have trouble talking to each other.

**Comment by Pavion** [comment]
Hi @SlayksWood 
With the latest update this is still not working and I can't see a solution here. Is there a reason for this issue to be closed?
BR Pav

**Comment by SlayksWood** [comment]
@Pavion Hi, Closing the issue doesn't mean that it was released. For you it will be fixed with next update.

**Comment by Pavion** [comment]
Thank you, I'm looking forward to it. This game is truly amazing!

**Comment by johnpmayer** [comment]
Do you still need verification of the fix on the release_preview channel? Or has somebody already validated the change on OSX?

I still have issues on `0.9.0.4 beta release-97` (currently, I experience the "Host creation call failed" crash even with the default config, where IPAddress is Any)

**Comment by johnpmayer** [comment]
I'm still having issues launching EcoServer on mac. You'll see in the below logs I'm running [Eco Server 0.9.0.5 beta release-100]

https://gist.github.com/johnpmayer/a4ecd00817ccd63ca626b9b9167e0c6b

Fails on "Any" (shown in above logs), and also "0.0.0.0", and "127.0.0.1"

**Comment by mirasrael** [comment]
@johnpmayer what is your exact PC spec (including OS version)?

**Comment by mirasrael** [comment]
Also can you try to run this executable?

[publish.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5382902/publish.zip)

Run with: `dotnet ENet-Test.dll`
And check (in another console window): `lsof -i UDP:10201 -P`

**Comment by mirasrael** [comment]
No new information/confirmation for more than two weeks. Closing now. Feel free to re-open if new information arrive.
