### ISSUE TITLE
USER ISSUE: Cant build a Workbench

### ISSUE THREAD

**Issue by Phiboo** [StrangeLoopGames/EcoIssues#18427]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Start Game on a Server, place tent, chop log and put it in your stockpile.
Try to craft a workbench, add work, but it doesn't go on. It says "0 of 0 wood added".
It recognices the wood in the menu where you choose to craft the workbench.
It doesnt work for me, neither for my friends, we used all different woods.

**Expected behavior:**
Well I should be able to craft a workbench.

**Actual behavior:**
I described that in steps to reproduce but hey:
It does nothing. The workbench wont craft, it needs 0 seconds and the Workbench Project doesnt need any labor.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, we are using a nitrado server and reinstalled the game (used older version, but set it new up to be sure).

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263581/Player-prev.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263584/Player-prev.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5263585/Player.log.copy.txt)

**Comment by SlayksWood** [comment]
merged to #18426
