### ISSUE TITLE
DLL issues

### ISSUE THREAD

**Issue by TazMatic** [StrangeLoopGames/EcoIssues#18429]
So Ive been struggling to get alot of 3rd party libraries to work in eco. One example will be Harmony 2.0 for core 3.1, upon starting the server with harmony it complains about missing system DLL's that are dependents for the eco server not the 3rd party library. 
![Capture](https://user-images.githubusercontent.com/31835653/93937532-f375eb80-fcf5-11ea-88ce-98ee661d7b5b.PNG)

**Comment by redwyre** [comment]
Do you know the exact versions of the DLLs and the references to those DLLs? Since we're loading them manually there's no binding redirects.

**Comment by redwyre** [comment]
Also have you included MonoMod.Common and its dependencies?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
