### ISSUE TITLE
USER ISSUE: Crafting a workbench doesnt work

### ISSUE THREAD

**Issue by TheFlooh** [StrangeLoopGames/EcoIssues#18426]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Start Game on a Server, place tent, chop log and put it in your stockpile.
Try to craft a workbench, add work, but it doesn't go on. It says "0 of 0 wood added".
It recognices the wood in the menu where you choose to craft the workbench.
It doesnt work for me, neither for my friends, we used all different woods.
I attached some screens, hope they will help.

**Expected behavior:**
Well I should be able to craft a workbench.

**Actual behavior:**
I described that in steps to reproduce but hey:
It does nothing. The workbench wont craft, it needs 0 seconds and the Workbench Project doesnt need any labor.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, we are using a nitrado server and reinstalled the game (used older version, but set it new up to be sure).

![AttachedWorkplace](https://user-images.githubusercontent.com/71729371/93928603-db649300-fd1a-11ea-873d-3545bd8d8538.png)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263570/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263571/Player.log)
![Workbenchnotworking](https://user-images.githubusercontent.com/71729371/93928546-c556d280-fd1a-11ea-9804-857e5bb43653.png)
![WorkBenchProjectdoenstneedLabor](https://user-images.githubusercontent.com/71729371/93928551-c5ef6900-fd1a-11ea-8a43-cb05e37e288b.png)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
#18427
> **Version:** 0.9.0.2 beta release-71
> 
> **Steps to Reproduce:**
> Start Game on a Server, place tent, chop log and put it in your stockpile.
> Try to craft a workbench, add work, but it doesn't go on. It says "0 of 0 wood added".
> It recognices the wood in the menu where you choose to craft the workbench.
> It doesnt work for me, neither for my friends, we used all different woods.
> 
> **Expected behavior:**
> Well I should be able to craft a workbench.
> 
> **Actual behavior:**
> I described that in steps to reproduce but hey:
> It does nothing. The workbench wont craft, it needs 0 seconds and the Workbench Project doesnt need any labor.
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> No, we are using a nitrado server and reinstalled the game (used older version, but set it new up to be sure).
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263581/Player-prev.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5263584/Player-prev.log)
> [Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5263585/Player.log.copy.txt)

**Comment by SlayksWood** [comment]
@TheFlooh @Phiboo what server do you play? and does you server has blast furnace like here #18433, It can cause your problems.
Also, please, provide your PC specification (include Operating System).

**Comment by TheFlooh** [comment]
Our Nitradoserver uses the Version Nitrado gives you: 0.9.0.2 beta release-71
No Settings were made. We just gave a password, a name, and registered one as admin. Meteor is off with 0 days, because Nitrado doesnt allow to let the field empty.
We both use Windows 10 on Version 2004 (Build-Nr. 19401.508 and 19041.450).
Both Custom PCs, mine with: i5-6600K, 16GB DDR4-RAM, equipped with both SSD and HDD, Nvidia GeForce GTX970 Mini 4GB.
Phiboos: i7-4790K, 28GB DDR3-RAM, HDD and SSD Nvidia GTX1060 6GB GDDR.

Do you need any more information?

**Comment by TheFlooh** [comment]
Hi, how is the current state? @SlayksWood

**Comment by SlayksWood** [comment]
@TheFlooh Sorry for the wait. Can you give me server ID and password? to check it on your server. I still can't reproduce your issue. If you do not want to tell it here write to me in Discord Kirill (Slayks)#6251
Does this problem occur if you start server from the game?

**Comment by TheFlooh** [comment]
Now after we fixed the empty difficulty file it works.
Copying the template into the difficulty file and restarting the server solved the problem
Strange that its empty because we reinstalled the server but anyways, it fixed so I'll close it.

**Comment by SlayksWood** [comment]
I will open a new issue with problem when player set Craft time multiplier = 0 and Craft resource multiplier = 0
