### ISSUE TITLE
USER ISSUE: Land Claim

### ISSUE THREAD

**Issue by IAmNotLiable** [StrangeLoopGames/EcoIssues#18432]
\
**Version:** 0.9.0.2 beta release-71

**Steps to Reproduce:**
Try to claim land

**Expected behavior:**
claimed the land	

**Actual behavior:**
did nothing and wo't let me switch whats in my hands

**Do you have mods installed? Does the issue happen when no mods are installed?:**
vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@IAmNotLiable Thank you for the report. We need additional information.
1. Do you often have this problem?
2. Do you have any notification in game? You can provide video or screenshots
3. Please provide log files when it happens next time. Instruction is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
4. Please provide your PC specification (include Operating System).
5. What server do you play? Do you have this issue in any server? Can you try to connect to official servers, try to claim land and provide log files?
6. Provide save files, if possible. Instruction is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
