### ISSUE TITLE
Pipes connected and disconnected at the same time

### ISSUE THREAD

**Issue by 42656e** [StrangeLoopGames/EcoIssues#18434]
When a pipe is attached to the sewage output of a blast furnace with a direct bend and another block is directly next to it the pipe does count as connected (this is shown visually). But in the same time the pipe seems to be also not connected as the water still spills out of the pipe. See screenshot.

[Screenshot](https://imgur.com/FPkeD7A)

**Comment by SlayksWood** [comment]
merged to #11846
