### ISSUE TITLE
Blast furnace crashing the server

### ISSUE THREAD

**Issue by Napoleon2587** [StrangeLoopGames/EcoIssues#18433]
Issue: Server crashing because of blast furnace tasks
Reproduction rate: 100%
Server Host: Nitrado (Version: 0.9.0.2 beta release-71) since ~10 days

I made a support request with the message below:

Yesterday the server crashed while I was building a waste filter. Before the crash it showed everything right but after the crash it didn't function correctly anymore. It does not produce any compost and the interface with the upwards counting percentage in the status-tab isn't showing. It went more malicious today. The server crashed again while Nitrado faced much trouble with their servers this evening. This time we had a blast furnace producing some steel stuff. Since the crash it is totally bugged. If I start a production there the server crashes. I can reproduce this 100% of time. The furnace is not usable anymore. I tried to remove and replace the furnace, even gave me the DevTool and deleted the furnace + produced a new one and placed it. Even with the new one it does happen. It happens for other players on the server aswell. We cant produce any steel anymore while this problem persists, so sadly we only have the choice between not to play or start to /give us everything we need. After deleting and replacing the waste filter it now correctly shows the compost counter but because it constantly crashes because of the furnace I don't know if it actually produces something.
The server does not produce any crashlogs. I attached one of the restart logs. Because of our tries to fix this we have around 20-30 of those logs but they all seem to be normal.

The support could help me to "fix" it. I had to disconnect the waste filters output from the fresh water network, then it doesnt crash anymore and the filter is producing compost normally.

Location:
Furnace: around 575, 250.
The waste filter is right below if you follow the pipes.

Log from Nitrado server:
[restart.log](https://github.com/StrangeLoopGames/EcoIssues/files/5266387/restart.log)
One example log from our server:
[log_200921104203.log](https://github.com/StrangeLoopGames/EcoIssues/files/5266475/log_200921104203.log)

Savegame uploaded here:
https://drive.google.com/drive/folders/1Ut3N3Cj9rDd0YHZNcduI6awKleX6dfye?usp=sharing

**Comment by SlayksWood** [comment]
@Napoleon2587 Thank you for the reprort. This is known issue and we and we are working on fixing it.
I can give one advice to you for now, don't connect waste filter output to blast input, just delete 2 pipes:
![image](https://user-images.githubusercontent.com/45708377/93984402-6c278700-fd8c-11ea-9a94-90853a5b77b9.png)
And it should work.
duplicate #18374
