### ISSUE TITLE
[0.9.0.1] Wages pay double at the same instance.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18435]
Wages pay way too frequent 
![Screenshot_422.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f1e0038b-9ca9-4e4a-84dc-1cd2897a9e5f)

**Comment by IcedForge** [comment]
Tested it out on [0.9.0.2 beta develop-62] and it doesn't matter what i change the payment interval to it will always pay out twice.
![Screenshot_32.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/e0e31432-885b-40cc-81bf-8bac623f7968)

**Comment by jamesyoung79** [comment]
same issue still exists #18587

**Comment by IcedForge** [comment]
For clarification this is not just notifications happening twice, it is actually taking money for each notification ( so each tick a payout happens it does it runs payment twice ).

**Comment by serpopov** [comment]
![image](https://user-images.githubusercontent.com/4238643/104592541-f16ada80-56a0-11eb-8ebd-cf0af07965e9.png)
Seems it is fixed on staging

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Staging-1907

Issue: Appears to be fixed. Closing.

![wasge.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/352b267d-f067-4a97-aaa8-b0a997ead015)
