### ISSUE TITLE
[0.9.0.2 beta develop-61] Law Trigger: Not Felled not functioning/reversed

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18439]
The sub trigger for Chop Tree - If "Not Felled" is not functioning properly as it does the same thing "Felled" does, ie registering action as true on actually cutting down the tree and not just chopping it.

The trigger in action.
 - Cut down the tree
 
![Screenshot_24](https://user-images.githubusercontent.com/24981362/94039388-f80ad480-fdc7-11ea-874e-7c7152011cbc.jpg)

- Cutting tree but it is NOT felled

![Screenshot_25](https://user-images.githubusercontent.com/24981362/94039398-fa6d2e80-fdc7-11ea-9373-f7d12e44d9ad.jpg)

The Law Logic
![Screenshot_23.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/dda64aaa-99e9-45ab-80ed-16e93161eef2)

**Comment by WeaselDog** [comment]
This is an issue for all axe interactions. It is an issue with how "Not" action works. I confirmed with better laws than in the screenshot.

**Chop Branches:**
Both trigger false when not targeting branch. Both trigger true when targeting branch.
![BranchesLawTrigger](https://user-images.githubusercontent.com/47330823/94395668-0719bb80-0115-11eb-9215-4cbf6163bd69.png)

**Fell Tree:**
Both trigger false when not felling. Both trigger true when felling.
![FellLawTrigger](https://user-images.githubusercontent.com/47330823/94395782-45af7600-0115-11eb-8e5d-785b8b758762.png)

**Chop stumps:**
Both trigger false when not destroying. Both trigger true when destroying.
![StumpLawTrigger](https://user-images.githubusercontent.com/47330823/94395892-87d8b780-0115-11eb-859b-4216064100fa.png)

**Comment by tuha263** [comment]
I Fixed it
![NotNotFelled](https://user-images.githubusercontent.com/9598614/99979568-ce772500-2dd9-11eb-845f-df07a8436a26.png)
![Felled](https://user-images.githubusercontent.com/9598614/99979574-d0d97f00-2dd9-11eb-9afc-e43e719cc677.png)

**Comment by Daniel-Magulado** [comment]
We tried to repro the bug and the action is still reversed. What happening is reversed of what it should be.

![not felled false.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/43412490-02dc-45d0-b0f5-1023297c0428)
