### ISSUE TITLE
Cloud World disconnected since purchase

### ISSUE THREAD

**Issue by Ninjawolf1165** [StrangeLoopGames/EcoIssues#18430]
I bought a cloud world server 3 days ago and it has been disconnected the whole time. Trying to change the name gives an unknown API error and trying to reset the world gives an internal server error.
![Cloud World disconnected](https://user-images.githubusercontent.com/71734603/93942339-32a83a80-fcfe-11ea-87c5-09c6185e4b47.PNG)

**Comment by ddrght12345** [comment]
I just left this message on the discord, but I will leave it here as well to keep it all in one place:
```html
<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$Message</p>
<p>Filename: libraries/EGS.php</p>
<p>Line Number: 183</p>
```
and
```html
<p>Type: TypeError</p>
<p>Message: Argument 1 passed to MY_Output::error() must be of the type string, null given, called in /var/sites/accounts/site/application/controllers/traits/WorldsTrait.php on line 116</p>
<p>Filename: /var/sites/accounts/site/application/core/MY_Output.php</p>
<p>Line Number: 29</p>
```

----
Side-note:
I feel like you should probably:
1. Catch the errors and use pretty, user-friendly, error messages (I would not have seen this error if I hadn't checked the console myself)
2. Hide the full stacktrace in error messages, even without proper error handling

**Comment by denysaw** [comment]
That was CW API error while world start. As I see cron worked now and world is restarted and active (and problem gone).
I made some error message improvements for server reset.

Side-answer:

1. Yeah, it's actually was attempt to re-form EGS API error into human-readable one. But as it appeared in that response object was no `Message` attribute. This is what current error tells us.
2. Sorry, but on Staging we do show full error's stacktrace. This is stagingland for :)

**Comment by ddrght12345** [comment]
Ah ha. I love when error handling causes further errors. All good. I've been there too.
And gotcha, I glossed right over the fact that it is, indeed, staging. I would agree with the debugging point.

Thanks for the quick fix!

**Comment by denysaw** [comment]
Yeah, welcome ;) Thanx for reporting ;)
