### ISSUE TITLE
cw api: /start sometimes not returning server id or web url

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18442]
@denysaw do you remember the error its giving when no server id is returned?

**Comment by redwyre** [comment]
@denysaw can I get some more info about this?

**Comment by j3fffff** [comment]
this is an issue with cw api.
using /start to start a new cw. api is supposed to return a server id and server url.
Sometimes api doesnt return either, just empty server id and server url parameters. no error

**Comment by denysaw** [comment]
@redwyre @j3fffff Sorry for the delay. I think this is double of this one:
https://github.com/StrangeLoopGames/EcoIssues/issues/18476

There's error on a snapshot in description. As I remember we always had this error when there were no free nodes and as a sequence no `serverId` ans `webServerUrl` in the response.

**Comment by redwyre** [comment]
@mirasrael has made a some internal changes that should make it behave better, but it is possible for status to be "MISSING" and not have a server id.

I have added some logging with extra detail in "/start", so if something does happen again we will have a better idea of what is going on.
