### ISSUE TITLE
Graphical glitch on plants in pots

### ISSUE THREAD

**Issue by opelwerk** [StrangeLoopGames/EcoIssues#18444]
Strange graphical glitch when placing some seeds in clay pots. See attached screenshots. Same occurs on other player's screen, though GM Ice Forge sees them as normal. The bug is repeated with huckleberry seeds, dwarf willow seeds. Taro root placed in the same way did not seem affected. Persists through game restart.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5270543/DxDiag.txt)
![bug1](https://user-images.githubusercontent.com/71788933/94057816-71162600-fde0-11ea-94f3-5cbccb012309.jpg)
![bug2](https://user-images.githubusercontent.com/71788933/94057818-72475300-fde0-11ea-8f72-2002433078f9.jpg)
![bug3](https://user-images.githubusercontent.com/71788933/94057824-73788000-fde0-11ea-9a2b-527de93c279c.jpg)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5270564/Player.log)

**Comment by ky0uraku** [comment]
Same:

![image](https://user-images.githubusercontent.com/48658286/94070041-37eaaf80-fdfa-11ea-8650-791d01c0e453.png)

![image](https://user-images.githubusercontent.com/48658286/94070102-4fc23380-fdfa-11ea-9b03-d843f97be70b.png)

**Comment by SlayksWood** [comment]
merged to #18342
