### ISSUE TITLE
[0.9.0.2 beta develop-61] Civic objects issue: Objects gone via election or command

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18440]
Summary from https://github.com/StrangeLoopGames/EcoIssues/issues/16601

Civics objects does not apply to container objects  ( court, census table, government office ) as intended via Election process ( either admin command or general election ). The laws are applied but are not attached to an object and is therefor subject to mischief as well as players can overwrite these objects and then you have laws/titles that are functioning but are not editable and causes all kinds of damage to the system.

This seems to be very world generated specific ( no confirmation but it could happen in progress i assume somehow )
Generating a world will either have it immediately or not at all it would seem, tried generating a few more worlds after this and none had this issue at all. The attached world however had this happen from the start.

- Save with the issue [0.9.0.2 beta develop-61]
[broekn law.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5269572/broekn.law.zip)

Edit: 
The reattachment system works accordingly so if you restart the server if it happens it will reattach the passed object perfectly fine there is just something that causes it to not get attached on revisions the problem for general public is that a law passes, it vanishes then they cant really be expected to restart every time they need to do a change so they add a new law on the previous slot and it causes even more cascading issues.

**Comment by beastyn** [comment]
New issues with this case :
#18506

**Comment by JustinGianelloni** [comment]
The issue can be duplicated by using "/civics finish election" or "/fin", or by normal web-based voting. In addition, we now have a district map that disappeared off the table, and did NOT return after a server restart. The only solution I have at my disposal is to completely redraw that district map, update the references in all relevant laws, and propose both at the same time and hope they pass.

**Comment by jamesyoung79** [comment]
Is there an /civics command to attach an invalid law/demographic/district/title/ect. to an eligible object? If not would it be possible to make one for the time being?

**Comment by IcedForge** [comment]
Unfortunately not @jamesyoung79 we have a change to the civics object system that will address these types of issues but it is not possible as far as a quick fix goes to address this issue it is reworked a bit and should be more robust once the next non hotfix update comes out. (and no i do not have a date for that)

**Comment by johnkslg** [comment]
This should be fixed in develop

**Comment by IcedForge** [comment]
As john mentioned, this should be fixed for 9.1 (works on current dev build)
