### ISSUE TITLE
20fps on brand new game with a RTX2070 Super, and 32GB Ram

### ISSUE THREAD

**Issue by HijackHornet** [StrangeLoopGames/EcoIssues#18454]
I have an High end PC that run hundreds of other games correctly. After not playing this game for 2 years, i gave it another try today. But even on a brand new save, i have 30fps max with the lowest settings.
![Screenshot 2020-09-24 11 16 25](https://user-images.githubusercontent.com/2307228/94127217-efaeaa00-fe58-11ea-9d2b-49cd93ec26f8.png)
Specs :
OS Name
	Microsoft Windows 10 Famille
Version
	10.0.18363 Build 18363
Processor	
        Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 6 Logical Processor(s)
Total Physical Memory
	31,9 GB
Graphics Card
RTX 2070 Super - 8GB

**Comment by ExoFrece** [comment]
same for me mostly 20 sometimes drops to 5

Specs :
OS Name
Microsoft Windows 10 Home
Version
10.0.18363 Build 18363
Processor
AMD Ryzen 5 3600X 6-Core Processor, 3793 MHz, 6 Core(s), 12 Logical Processor(s)
Total Physical Memory
31,9 GB
Graphics Card
RX 5700 XT - 8GB

**Comment by HijackHornet** [comment]
Global Illumination alone managed to make the game go from 225fps to 25fps.
By deactivating it and restarting the game, the issue disapeared.
