### ISSUE TITLE
[0.9.0 release-78] Hard to aim with a bow in 3rd view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18455]
![image](https://user-images.githubusercontent.com/45708377/94137910-e5e47100-fe6f-11ea-9fd3-3800d73a0ef2.png)

**Comment by MilenkoTunjic** [comment]
You should not aim with anything in third person, I guess. Once you use bow, it should switch to the FP, or close enough to be useable.
it should be a mechanic. IE- when you aim, camera slings to FP, when you release the arrow, camera slowly slings back to thrid.

**Comment by SlayksWood** [comment]
Still an issue in 0.9.3 develop-170, I don't have AIM
