### ISSUE TITLE
Can merge stacks with different Item objects

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1845]
For example, if you have 1 mint item with a currency on it, and one without, if you drop one onto the other in your inventory, they will stack together, potentially erasing your currency data

**Comment by metachronism** [comment]
items with custom data need to have a max stack size of 1 to prevent this, probably

**Comment by craig-jong** [comment]
To be honest, I don't think its a bad idea to just make all world object items not stack - you shouldn't really be able to carry around a dozen or so workbenches in your backpack...

**Comment by metachronism** [comment]
maybe, but there are small things (like candles) that should be stackable

**Comment by metachronism** [comment]
fixed with unique items change
