### ISSUE TITLE
Can't create world or play existing worlds

### ISSUE THREAD

**Issue by dragongod23** [StrangeLoopGames/EcoIssues#18458]
For the past few days I have not been able to continue my existing world or even create a new one. I have reinstalled several times and it has not helped at all. Each time I try to open one of my existing worlds the error comes up saying "failed to connect to the local server. It may be because of server crash, you can check the server logs in C:/programe files (x86)/steam/steamapps/common/eco/eco_data\server\logs for more details" but there is nothing in the logs file to show anything. If I go into the folder and run the ecoserver file it will start up a server but if i try to connect to it i recieve the same error message as well. Any help would be appreciated

**Comment by beastyn** [comment]
@dragongod23 Thank you for the report.
Did you try anything from this help page?
<https://github.com/StrangeLoopGames/EcoIssues/wiki/Troubleshooting:-Can't-connect-to-the-server>

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
