### ISSUE TITLE
Cant connect to any server in current update, but i have 500 hours played in the past :(

### ISSUE THREAD

**Issue by landenbirch** [StrangeLoopGames/EcoIssues#18452]
This is a link to a clip of what happens whenever i try to join a server. https://youtu.be/7ZeF3JfwbsA is there any suggestions? thank you for helping

**Comment by beastyn** [comment]
@landenbirch Thank you for the report. 
1. Some additional info like logs would be useful.
2. Also, can you look into your Performance tab and make a screenshot when trying to connect?
3. Which server do you try to connect (is it localized)
4. Can you provide your PC specification?

**Comment by landenbirch** [comment]
1. This is a link to a log I found. [eco fail.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5375845/eco.fail.txt)

2. Screenshot of performance tab: it looked completely normal

3. I was trying to connect to my number one most recommended server as I used to do

4. My PC specs are: AMD Ryzen 7 2700x 8 core CPU / Radeon RX 590 Series GPU

**Comment by SlayksWood** [comment]
@landenbirch 
1. Try to connect to any server and provide log files. You can find log files here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file . Provide them please.
2. Try to delete game and install it again.
3. Try to connect to any official server  and provide log files again.
4. What Operating System do you use?

**Comment by IcedForge** [comment]
@landenbirch 
Are you still experiencing this issue, please follow SlayksWoods instructions above as we need a player log from you to move further in this investigation. If this is not happening anymore feel free to close this issue yourself or i will close it in a few days from now in lack of response.

**Comment by IcedForge** [comment]
Will close this in lack of reply unfortunately. If this is still an issue feel free to open this and let us know.
