### ISSUE TITLE
[0.9.0.2 beta develop-62] Road tools should not highlight sand.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18459]
Since sand cannot be turned into dirt road it should work like the hoe on tamped tiles, no highlight the ground as if you can apply it.![Screenshot_35.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8749e296-dae2-4934-9fa9-d0dfcf2ee89e)

**Comment by SlayksWood** [comment]
Desert Sand and Ocean Sand too.

**Comment by SlayksWood** [comment]
Seems fixed with reworking actions:
![image](https://user-images.githubusercontent.com/45708377/97980458-dc8ce380-1de1-11eb-88e2-df17d0ae8157.png)
