### ISSUE TITLE
[0.9.0 develop-63] 'Enter Description' in Constitution should be aligned left

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18468]
![image](https://user-images.githubusercontent.com/45708377/94235649-986e0f80-ff14-11ea-9171-cf8288c9f507.png)

**Comment by ptitducanh** [comment]
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/ce8ddead-cd9a-43ef-b7d6-0b718ba6db14)

It's aligned correctly on my PC. 
Someone fixed it perhaps.
