### ISSUE TITLE
Change highlight of title screen menu options from green to blue 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18463]
And make the whole button clickable, not just the text.

**Comment by SlayksWood** [comment]
Continue button isn't full clicable, only in red zone:
![image](https://user-images.githubusercontent.com/45708377/95950316-f2b80d00-0dfc-11eb-931b-899d0122a698.png)
Other buttons you can click in green zone, maybe we should limit it with buttons? (yellow lines)

**Comment by SlayksWood** [comment]
Checked on 0.9.2 develop-102. Still an issue with 'Continue' button, I can click only on text.

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/7238
