### ISSUE TITLE
[0.9.0.2 beta develop-62] Tool tip for Government account is shy

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18460]
Government account mouse over tool tip is hiding behind the interface.
![Screenshot_29.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/3e16b66c-4f01-4d09-8463-586ebfc3a87a)

**Comment by SlayksWood** [comment]
check thi one too #19197
