### ISSUE TITLE
Avatar eyes are funny colors

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1846]

**Comment by SeanAtr0n** [comment]
Looks like best fix is probably to change the texture, then we can eventually set eye color

**Comment by MarjieAVolk** [comment]
lol so just make the color be in the irises instead of the whites?  Hahaha, makes sense I guess.  So are the eyes clothing items right now?  I just couldn't even find where that color could be getting set.

**Comment by SeanAtr0n** [comment]
The face is a clothing item that sets eye color, maybe if that recently changed in autogen that could explain the issue

**Comment by MarjieAVolk** [comment]
So the color of the face is the color of the eyes?  Ohhhhh okay.  Yeah, totally makes sense to just have that be the irises too, cool, thanks
