### ISSUE TITLE
USER ISSUE: Water does not flow

### ISSUE THREAD

**Issue by 0600Zulu** [StrangeLoopGames/EcoIssues#18465]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Dig near/in water.

**Expected behavior:**
Water flows

**Actual behavior:**
Water doesn't flow. Note that before 0.9.0.3, I was able to get water to flow in an aqueduct (after much trial and error with broken water).

![Eco 9_24_2020 9_15_19 PM](https://user-images.githubusercontent.com/26182839/94218876-14337200-feab-11ea-8af6-e31828f7cd5d.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5280157/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5280158/Player-prev.log)

**Comment by beastyn** [comment]
Thank you for the report. We are planning to change water behavior soon. Issue is here #17419
