### ISSUE TITLE
USER ISSUE: Nutrient Percentages All at 0

### ISSUE THREAD

**Issue by AliaAnor** [StrangeLoopGames/EcoIssues#18470]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
1. Upgraded to 9.03
2. Use Soil Sampler on block

**Expected behavior:**
It should have some nutrients.

**Actual behavior:**
0, 0, 0

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5281296/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5281297/Player-prev.log)

**Comment by Yourself** [comment]
Can confirm that this happened to a server I run as well; the nutrient levels truly seem to be zero'd out everywhere as adding fertilizer will add nutrients back to the soil but only near where the fertilizer was placed. The map layers show the amount being universally 0.

**Comment by Yourself** [comment]
An addendum to this: I can set the layers with /sim setlayer as an admin, but after a minute or two the layers are immediately zero'd out again.

**Comment by ky0uraku** [comment]
Maps also broken:

![image](https://user-images.githubusercontent.com/48658286/94332461-3da0ea80-ffde-11ea-8255-91fbfffb9e01.png)

**Comment by AliaAnor** [comment]
I used fertilizer and it appeared to register, but then ten minutes later it was back to 0.

**Comment by beastyn** [comment]
@AliaAnor Thank you for the report. nutrients were broken before, so you could have 0,0,0 at some point. For now plants also don't require nutrients, so they should not die so fast. It was a temporary measure it will be fixed soon.
