### ISSUE TITLE
Any CW can't be started. CW API 500 errors

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#18476]
![image](https://user-images.githubusercontent.com/5720101/94266813-ebf35400-ff3a-11ea-92ee-2a56c5ba457b.png)

Warning (about `key_exists`) is already fixed by me.
Seems it's `No free nodes` error, but please, make correct error explanation.

**Comment by SlayksWood** [comment]
check this one https://github.com/StrangeLoopGames/EcoIssues/issues/15438 after fixing

**Comment by j3fffff** [comment]
im able to make a world in postman on sfo2
where are you getting error? what region? still happening?
