### ISSUE TITLE
CW: can't delete failed world

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18477]
World was created with the errors and I can't delete it from an admin dashboard
![bandicam 2020-09-25 17-48-05-379](https://user-images.githubusercontent.com/27898520/94268887-4a2e3000-ff57-11ea-98b5-ae436a9a2649.jpg)

**Comment by j3fffff** [comment]
how was it created. fyi the cloud world management admin page is not functional yet.

**Comment by beastyn** [comment]
@j3fffff yeap, through admin dashboard. Ok, Then I close and wait for the finishing )
