### ISSUE TITLE
[0.9.0 develop-63] Civics: QoL understandable Error

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18473]
Can we change an error description a bi?
We can have an error in Trigger, in If or in Then. But If-then section is know works like one and it's a bit frustrating.
![Screenshot_50](https://user-images.githubusercontent.com/27898520/94254423-30352300-ff40-11ea-8404-ad2c54720e03.jpg)

**Comment by serpopov** [comment]
Additional: make numeratrion start from 1 instead of 0

**Comment by johnkslg** [comment]
It actually does make sense, because there can be many if-then blocks, dozens, and if we hide that it may be hard to find it.  Suggest close.

**Comment by minhnh-10** [comment]
So I will update as Sergey comment, display property index start from 1

**Comment by serpopov** [comment]
Index start from 1 added, we could make UI task to show extra frame to display if-then block visualy

**Comment by IcedForge** [comment]
Had a discussion with sergei about this issue and we need to further clarify and highlight sections as well as remove any text that is not relevant to the direct issue as people overall is very confused when making simple laws as the tooltip gives them a lot more information then is necessary, out of my perspective this is a case of Less is more.

It is more advantageous of directing the player to the specific issue then having them get all aspects of the entire object 

https://cdn.discordapp.com/attachments/756091636710244432/799250846125785089/Screenshot_69.jpg

As a player if i have no knowledge in programming or coding ( which is the larger majority of our players ) 
This is what they expect this to be looking like

https://cdn.discordapp.com/attachments/756091636710244432/799252696393449503/Screenshot_71.jpg

And an error message should only ever give you the information you need, not the entire object with all parts of it as it just makes it unusable for most people so they just browse through the entire list anyway until they find the explicit explanation marker.

I suggested to have a bit more of a highlight of the box itself to clarify where this error is located.

**Comment by IcedForge** [comment]
Will close this as we came to the conclusion that it would be better to further increase visibility of the incorrect fields instead.
