### ISSUE TITLE
USER ISSUE: Over max players reports client timeout instead of proper error

### ISSUE THREAD

**Issue by ikiris** [StrangeLoopGames/EcoIssues#18479]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Server over max players and attempt to connet

**Expected behavior:**
Clients get 400 style temporary over limit error

**Actual behavior:**
The following error message popped up:
`Timed out connecting to server`
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ikiris** [comment]
This is especially bad because the clients think the game is broken and only the server owner can stumble across the fault if its unexpected

**Comment by mirasrael** [comment]
In 9.2
![image](https://user-images.githubusercontent.com/475445/96714010-320ccd80-13aa-11eb-9a7f-b443eb731c13.png)
