### ISSUE TITLE
USER ISSUE: No players credits

### ISSUE THREAD

**Issue by GreenRing13** [StrangeLoopGames/EcoIssues#18478]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Joining the server

**Expected behavior:**
Player should be given infinite personal credit

**Actual behavior:**
Only the first players that joined the server has infinite credit, the others don't have anything

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@GreenRing13 Thank you for the report.
Can you provide log and save files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
