### ISSUE TITLE
[0.9.0.3 beta release-78] Law create Craft order with Tailings and Wet Tailings not working

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#18471]
Hello,
 when creating below law with Tailings or Wet Tailings, the trigger to tax is not working. Nothing happends:
![image](https://user-images.githubusercontent.com/47274045/94245020-f9e4ad00-ff19-11ea-8a6c-675db9202b03.png)

Issue was with previous version as well.

**Comment by IcedForge** [comment]
Trigger - Craft Item
Trigger - Create Work order 
![Screenshot_71.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f346595d-588e-4be0-af2e-cad139365f32)
Neither detects secondary output/byproducts from crafting or setting an order. 
![unknown.png](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/da7ab6a3-1399-4ea0-9391-71b5fbc8fef7)
Needs to use the primary output for law triggers.

**Comment by IcedForge** [comment]
There is a few problems with how it is designed right now, as you can unintentionally prevent / tax etc items not intended. 
Need to split the trigger somehow to specifically detect item as byproduct and not just "item crafted" 
Some suggestions from me and kirill is adding a separation under IF section just like the other split tiggers
![unknown2](https://user-images.githubusercontent.com/24981362/94405888-791fee00-0171-11eb-8d9b-fb626c72c201.png)

Another way is adding another trigger block like this but im not sure which is more logical to the user.
![Screenshot_72](https://user-images.githubusercontent.com/24981362/94406054-b97f6c00-0171-11eb-8988-cfca9fb19040.jpg)

Also want to rename "Item Used -> Item Crafted"

**Comment by Alteraner** [comment]
I personally would not split between primary and secondary output. In my point of view, the output is output. I would keep it flexible, as it might come up, that further recipes have more than one output. The law trigger should check all outputs and not only the first (primary) so even if a third or any further more outputs will be created by a new recipe, it would be flexible and you would not have to add a second or third output selector in the law system.
In the first versions of 0.9 and in the previous 0.8 it was the case. somewhere down the road, the trigger changed and only the primary was used.

**Comment by IcedForge** [comment]
That's why i would like to have both; so it would register ANY output type block specified; but also allow you to separate into only check primary/secondary etc under the IF section when you would like to do that. As with more recipes added and if we add more variations to byproducts this could cause a lot of unforeseen issues if it simply reads X block type, on any output instead of checking if its a primary or byproduct.

**Comment by Alteraner** [comment]
I'm fine with it as long i can trigger on Tailings and Wet Tailings quite soon. It's a typical demand by servers to have some additional economy tax for items polut the environment. You can do it for garbage, for air pollution but not for tailings and wet tailings right now.

**Comment by johnkslg** [comment]
It's a unique enough situation the easiest way to approach it is to add a 'Byproduct' property of the action as shown in the Jens' mockup above.  Then we can tag items that can be byproducts (dry/wet tailings) and make the property require that tag, so only actual byproducts show up in the trigger configuration.

**Comment by Alteraner** [comment]
@johnkslg, Maybe the easiest way to do will be to change it back as it was in the 9.0 staging time. Here all items which are crafted independent of primary or secondary have been triggered. 
To be fair, I was thinking a lot on a realistic case, where I need to differentiate between primary or secondary product. The entire team has done a brainstorming to find a situation where this kind of trigger might be useful, but we didn't find a usecase.
Typically, I want to tax or do some actions around a crafted item to be triggered. I don't care, if its primary or secondary crafted. Its there, doesn't matter how.

**Comment by IcedForge** [comment]
I would not want to revert it but fix it in a more permanent feature as this will become an even bigger issue later on as more products are available and removing the option to specifically tax certain objects is a big enough reason to invest this time into fixing that.

**Comment by johnkslg** [comment]
I like having it as a 'with byproduct' trigger option instead of a separate craft option because otherwise we would have to do multiple craft actions when theres a byproduct.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/101341444-2447d480-3892-11eb-9ddf-c7522afff3ca.png)
