### ISSUE TITLE
[0.9.0.3 beta release-78] removed demograpic with wages still been triggered

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#18474]
An demographic with wages which has been removed and replaced by an newer version is still been triggered during the civic ticker.
You can see on screenshot account log of treasury where removed demographic is been triggered.
![image](https://user-images.githubusercontent.com/47274045/94260173-fa883e00-ff2f-11ea-982e-a54114b804dd.png)

**Comment by SlayksWood** [comment]
@Alteraner Thank you for the report.
Does it pay when demographic was cancelled? or after canceling it continues to pay every wage tick?
We added wages when you cancel or remake it to pay to pay for the time that people held in this position before canceling it.
#14607

**Comment by Alteraner** [comment]
By the time we renewed/replaced the demographic with the new version 1 week ago, the wage stopped as intended for the old one. By the time the new update "release-78" came in, the removed demographic started to pay wages again. So the event to start paying wages came in with the update to the newest version. Before it went fine. 
Hope this helps you find the root cause. If you need further questions, please do not hesitate.

**Comment by SlayksWood** [comment]
@Alteraner Thank you. Did you any server restart between deleting demographic and updating to the release-78? Or it was first server restart.

**Comment by SlayksWood** [comment]
Can you provide save files? You can send to discord if you don't want to make your save public.

**Comment by beastyn** [comment]
Was fine for me on release version and after restart too.

**Comment by Alteraner** [comment]
As I remember correctly, we had one restart after the patch and then a second restart some time ago. I need to check whether the removed wage immediately started to work or even after the second restart. As I had to admin command deleting the old demographic to get it stopped, I need to check if I have an old backup with me. Hope there is such one with me, if yes, I will share it with you.

**Comment by Alteraner** [comment]
@SlayksWood, i have shared with you the save files some day's ago via discord. Did you had some time to investigate on it?

**Comment by SlayksWood** [comment]
@Alteraner Yea, thank you, I saw it. We will investigate it after finishing hotfixes for 9.0.x. While time isn't enough to do it.

**Comment by SlayksWood** [comment]
> Demographic wages continue to pay after demographic was revised.
> ![image](https://user-images.githubusercontent.com/8082068/95100000-a125c900-06fe-11eb-8ea2-dd71264a7623.png)
> 
> It is not an issue with the paying off partial wages during transition to revision it continues to pay old demographics after revisions continuously even after server restarts. Also, demographics are double paying.
> ![image](https://user-images.githubusercontent.com/8082068/95100227-e518ce00-06fe-11eb-8d3c-245c8b0d62c3.png)
