### ISSUE TITLE
Marking as finished an invalid transport contract makes the server crash

### ISSUE THREAD

**Issue by Blaazouille** [StrangeLoopGames/EcoIssues#18486]
Step to reproduce :

1. Make a transport contract.
2. Remove the origin stockpile 
3. Mark the contract as finished

The server just crashes instantly.

[log_200926023543.log](https://github.com/StrangeLoopGames/EcoIssues/files/5285950/log_200926023543.log)

**Comment by beastyn** [comment]
@Blaazouille Thank you for the report.
1. Can you provide client log file and dump fuke after server crash (it's in the dump folder)?
2. When stockpile was removed, after contract was accepted or from other step?

**Comment by Blaazouille** [comment]
1. I can't retrieve the logs from that time on the client [ServerCrash-Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5293067/ServerCrash-Dump.zip)
2. The stockpike has been removed after the contract was accepted. Contract is still in my contract list marked as invalid.

**Comment by beastyn** [comment]
Ok. Then:
1) Who was an owner of a deed with stockpiles?
2) Which stockpile was removed - source or destination?
3) Was it just picking stockpile up after accepting by other person or something has happened with deed too?

Maybe some screenshots?

**Comment by Blaazouille** [comment]
1. The owner of the contract (me)
2. The source stockpile was removed just before the end of the contract
3. I'm not 100% sure, but I think I removed both the stockpile, and the deed after that. I can post the contract detail, but it's not accurate anymore since everything has been moved. I didn't try to finish the contract again since it crashed the server twice already.

When the server crashed contract was showing :
- Source: **None**
- Target: **Stockpile**

![image](https://user-images.githubusercontent.com/17403753/94690214-1cb6fd00-0330-11eb-8c5e-9474faf8883c.png)
![image](https://user-images.githubusercontent.com/17403753/94690235-25a7ce80-0330-11eb-937a-1be59ee4e237.png)

**Comment by SlayksWood** [comment]
Still can't reproduce, but will finish investigating before release 9.1.

**Comment by Blaazouille** [comment]
Wasn't able to reproduce since it happened the first time.
I'm not sure what went wrong at that time.

**Comment by WeaselDog** [comment]
Thanks for getting back to us.  Please let us know if you experience this issue again.
