### ISSUE TITLE
Cloud World disconnected on website, shows as online in game but can't join

### ISSUE THREAD

**Issue by Ninjawolf1165** [StrangeLoopGames/EcoIssues#18481]
I posted an issue a few days ago where my cloud world server was disconnected and I couldn't do anything with it. The issue was marked as closed, but the server is still disconnected. I have the ability to change the name and trying to reset the world doesn't give an error anymore, but I still can't play the world. On my server list in game, the world is shown as online, but it says it requires 0.9.0.2 beta staging-1793.

![In game server info](https://user-images.githubusercontent.com/71734603/94309273-cf104e00-ff45-11ea-89c5-a83733c1e815.PNG)

 Trying to join says I need to change the version in the steam beta list, but there is no version on the steam beta list or the strange loop account page that gives staging-1793, so I cannot join.
![join attempt](https://user-images.githubusercontent.com/71734603/94309586-4e9e1d00-ff46-11ea-8f4e-0ac47bf51f27.PNG)

Since the server is disconnected on the Eco Worlds page, I can't change the version so I can't access the server at all.

**Comment by beastyn** [comment]
@denysaw please, take a look

**Comment by denysaw** [comment]
@j3fffff Any ideas what actions should we perform here?

**Comment by j3fffff** [comment]
Hey @Ninjawolf1165 
sorry we mistook your previous bug. Could you link to it so we can reassess our process on that one?

I reset your world with version 9.0.3
should be working correctly now.
