### ISSUE TITLE
[0.9+] Loading Eco Crash [LINUX MINT 20]

### ISSUE THREAD

**Issue by ToufouMaster** [StrangeLoopGames/EcoIssues#18487]
When i start my game every things fine

but when i connect to a server (any server and mines too)

My Game Freeze when Loading Eco 90% and after 10sec the game close itself
![Capture d’écran du 2020-09-26 16-02-15](https://user-images.githubusercontent.com/68186078/94342639-9e4a1a80-0012-11eb-83b7-74e7939a7078.png)
i don't  know how to resolve this

**Comment by JanThomas118** [comment]
Have you looked at RAM usage during the loading screen? It might be related to #18448 ?

**Comment by beastyn** [comment]
@ToufouMaster Thank you for the report.
As @JanThomas118 has mentioned (and it was quite nice) can you check your RAM usage in this process?.

**Comment by antaeusdk** [comment]
I have the same issue.

I had System Monitor open when I tried to play Eco. The game opens, but crashes when I try to join a server. Besides a slight bump in RAM usage, it doesn't look as though there is a memory leak. Albeit it might be so fast the system does not really register it.

![Screenshot from 2020-10-19 06-17-18](https://user-images.githubusercontent.com/2125190/96401285-25824c80-11d3-11eb-9f13-559f7412ed4c.png)

OS: Ubuntu 20.04LTS
CPU: AMD Ryzen 3700X
RAM: 32GB
GPU: Nvidia Geforce 1060 3GB

**Comment by antaeusdk** [comment]
This bug report still bears the tag "Status: Needs Information". What information does SLG require? I am willing to chip in (Since I have the same issue as OP).

**Comment by redwyre** [comment]
Can you attach a log file? https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by antaeusdk** [comment]
Sure thing!

[http://antaeus.dk/Player.log](url)

**Comment by ToufouMaster** [comment]
Sorry i reboot my Pc because of HDD corruption

i know something i have 0 Problem with ram my Processor is pretty bad but My Graphics card is good enough to run the game at 60Fps at minimal resolution 35%res and full Low

sorry i'm french my english is not really good

Here my specification:

Intel core I3 5005U
Nvidia Geforce GT-920MX
12Go Ram DDR3

i have no more information sorry

**Comment by IcedForge** [comment]
Unfortunately for the OP issue im not sure there is anything we can do would like
@redwyre opinion on this. The CPU is way below minimum requirements and im guessing that this is causing some computation issues where its simply not catching up quickly enough?

@antaeusdk
I cannot access the log file could you reupload this and create a separate own issue if this is still a problem for you after 9.1 update ?

**Comment by IcedForge** [comment]
Will close this as there were never any replies.
