### ISSUE TITLE
Voting in webpage should not refresh page

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18482]
![animx22](https://user-images.githubusercontent.com/3536496/94316160-b77e9880-ff38-11ea-9eb6-23fe76d7326b.gif)
It looks like it tries to do a live update but then reloads anyway.
Check other parts of the web system for failed live updates too.

**Comment by denysaw** [comment]
Could be re-tested after merging the above PR.
