### ISSUE TITLE
[0.9.0.3 beta release-78] Tools disappear after leaving car in 3rd person view

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18496]
![изображение](https://user-images.githubusercontent.com/13696708/94376125-36362a00-0121-11eb-93de-cfe6de4a9e2c.png)

How this is repeat:
1. Choose a chainsaw from the first person
2. Get in the car
3. Enable third person mode
4. Observe
5. If you leave the car, the chainsaw will disappear from your hands, it will work

**Comment by SlayksWood** [comment]
We still have this issue in develop, but have another steps to reproduce:
- go in 3rd person view, take any tools in hands.
- get in the car
- leave the car. Tool will disappear.
![2020 09 28 Tools disappear after leaving car in 3rd person](https://user-images.githubusercontent.com/45708377/94397743-13c9fe00-016d-11eb-94bd-3b571e0d73af.gif)

**Comment by SlayksWood** [comment]
merged to #12829
