### ISSUE TITLE
Stockpiles tutorial: Saguaro cactus doesn't count in the tutorial

### ISSUE THREAD

**Issue by rodneymillerpca** [StrangeLoopGames/EcoIssues#18495]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Attempt the wood/ supply gathering tutorial.

**Expected behavior:**
Saguaro Cactus should count as trees. Logs when cut

**Actual behavior:**
Tutorial hangs till you go cut another tree species

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
![Uploading image.png…]()
