### ISSUE TITLE
Fake plant highlight can remain after taking seed

### ISSUE THREAD

**Issue by LeeDassin** [StrangeLoopGames/EcoIssues#18491]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Place a pot

Put in bullrush seed

remove seed

**Expected behavior:**
Removal of plant and green outline from the pot

**Actual behavior:**
green outline of plant remained 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/94398216-d44fe180-016d-11eb-9ef3-512e16daf7a5.png)
It will fixed after restart client
may be related with #18053

**Comment by SlayksWood** [comment]
I have it today again
![image](https://user-images.githubusercontent.com/45708377/97424988-8cfe7180-1922-11eb-995d-26f4fb00412c.png)
![image](https://user-images.githubusercontent.com/45708377/97425688-7d335d00-1923-11eb-8ed0-f7e82d1a79e2.png)

**Comment by SlayksWood** [comment]
Step to reproduce:
- take stone hammer, agave seed and square pot.
- put agave seed into Square pot:d
![image](https://user-images.githubusercontent.com/45708377/97538036-cee5f100-19d0-11eb-877f-313163ab10ac.png)
- use LMB to take seed with stone hammer:
![image](https://user-images.githubusercontent.com/45708377/97538075-e1602a80-19d0-11eb-9889-eb8cda87bdb6.png)
