### ISSUE TITLE
{0.9.0.3 Beta-Release-78] Redwood Falling onto Stone Road Ramp Crash to Main Menu

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18497]
Welp, its been awhile since I have been active on the Github as I've been moving and such but I AM BAAAAACK!!!! Of course, as always my friendly and lovely Devs, I bring bugs, crashes, and other problems that need to be splatted! Hope you are ready for the ever detailed reports from the Graesyn Line!

**Steps to reproduce:** Cut down an Old Growth Redwood so that it falls onto a road comprised of Stone Road and Stone Ramps
**Expected behavior:** Tree Falls and Has no Issue
**Actual behavior:** Crash to Main Menu 
**Providing Log files:**
[redwood crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5289585/redwood.crash.txt)
[System Specs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5289588/System.Specs.txt)

**Comment by SlayksWood** [comment]
merged to #18214

**Comment by beastyn** [comment]
@Sarah-Graesyn Thank you for the report, as usual )
