### ISSUE TITLE
[v0.9.0.3] Executive action : Property ownership changed to an elected title

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#18509]
**Description:**
The elected title "Mayor" is created. _Player 1_ is elected for the elected title "Mayor". The "Mayor" may perform any executive action immediately. _Player 1_ as "Mayor", do an executive action to change the ownership of a property to the elected title "Mayor". 
After a second election, _Player 2_ is elected for the elected title "Mayor". But _Player 2_ doesn't have access to the property with the elected title "Mayor" as the owner.
It looks like when the owner of a property is not a specific player but an elected title (and probably all groups of people like demographic and title) and the occupant of this elected title changes, the new occupant doesn't have access to the property.

If you need more details by adding the steps to reproduce, I'll try to see if I can reproduce it again.

**Steps to reproduce:**

**Current result:**
The new occupant of an elected title doesn't have access to the property owned by this elected title.

**Expected result:**
The new occupant of an elected title should have access to the property owned by this elected title.

**Comment by beastyn** [comment]
@fillion07 Thank you for the report. 
I could not easily reproduce it. I was trying to make Player2 to be owner of the title by election and also by succession. Both of them don't have any problems with getting access to the property. Maybe something else is missing in this process?
Can you provide Mayor title logic?
And also client log will be nice to have, maybe some exceptions are in there.

**Comment by beastyn** [comment]
Also can you check if re-logging by Player2 is helping for getting an access?

**Comment by fillion07** [comment]
Prior to change the owner of the title **via an Executive Action**, have you tried to change property owner of a claim from a _Player 3_ to an _elected title_ via an Executive Action (in the Executive Office) while the occupant of the elected title was _Player 1_ at the moment of switch of the ownership of the property. Then elect a _player 2_ for that elected title and let _Player 2_ try to unclaim the property owned by the elected title.

Note: Re-logging didn't solve the problem.

If you cannot reproduce it, I'll try to see if I can have 3 players willing to test it in a local server.

![Mayor elected title](https://user-images.githubusercontent.com/7052045/94576082-f2d3dc80-0242-11eb-95d3-80df46e2618a.png)
![Mayor elected title info](https://user-images.githubusercontent.com/7052045/94576122-fd8e7180-0242-11eb-974b-818c424f8718.png)
![Current Mayor not able to unclaim](https://user-images.githubusercontent.com/7052045/94576149-0717d980-0243-11eb-9fac-4851d848464d.png)
![Property owned by Mayor](https://user-images.githubusercontent.com/7052045/94576164-0d0dba80-0243-11eb-8e89-a94d87c98b1f.png)

**Comment by beastyn** [comment]
@fillion07 yeap, I did use an Executive action for passing the rights.

We will investigate it further.
Still will be nice to have your client log file from a session with the issue. Thanks!

**Comment by beastyn** [comment]
I've got it.
It's not exactly about access, you can place objects, you can change owner through deed UI, but you can't unclaim.
Is it so?

**Comment by fillion07** [comment]
Yes @beastyn that is exactly the case where the player cannot unclaim the property. We will do the workaround for now. Thanks again for the investigation.

**Comment by beastyn** [comment]
Issue for this fix #18537 (created a new one for the clearance)
I will close this one. Thanks again!
