### ISSUE TITLE
Civics disappearing from desks after modification vote.

### ISSUE THREAD

**Issue by JustinGianelloni** [StrangeLoopGames/EcoIssues#18506]
We're currently experiencing an issue where civics (laws, districts, etc.) disappear from their respective desk after a modification is proposed and successfully voted on. The active law is listed when running "/objects list laws" however, it is not located at any Court.  The previous law which was replaced is now showing in the draft slot with "(removed)". The only way we have found to restore civics that disappear this way is to restart the server. After the restart, they appear correctly in their respective desks and can be modified. However, subsequent modifications and votes will reproduce the issue.

The problem appears to occur less frequently with actions that don't require a vote (instant pass via Executive action), but has still been observed to happen. See attached image for example including the newly voted in active law listed in the chat window, but not in the civics desk.

![Untitled](https://user-images.githubusercontent.com/22803114/94461956-ceb3c500-0188-11eb-9733-373315ef473d.jpg)

**Comment by beastyn** [comment]
@JustinGianelloni How did voting was performed? In a common way through a site or with the specific command?

**Comment by beastyn** [comment]
Original is here #18440, merging
