### ISSUE TITLE
USER ISSUE: Invisible objects

### ISSUE THREAD

**Issue by devvra-sys** [StrangeLoopGames/EcoIssues#18500]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
1. Log into server
2. Encounter missing stuff
My sister ([ONE] Czarne Kitku) was seeing the Cast Iron Stove and Storage Chest in the game, but I wasn't until I relog. My internet connection is working smoothly.

**Expected behavior:**
Cast iron stove should not be missing

**Actual behavior:**
Cast iron stove and storage chest was missing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Duplicate issue #17803
