### ISSUE TITLE
[0.9.0 develop-66] Strange hands animation when you use A/D(Left/Right) to leave ladder

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18502]
and space too:
https://drive.google.com/file/d/15kZ0OjVIwGuVqF_DjWmeyhf4JbfPX40P/view?usp=sharing
Should I be able to move to another ladder using A / D?
![image](https://user-images.githubusercontent.com/45708377/94424510-045dab80-0193-11eb-847c-6ca8f6aad0ce.png)

**Comment by SlayksWood** [comment]
also this one doesn't work:
> Yes, and another problem, leaving in situations like this
> ![unknown](https://user-images.githubusercontent.com/4980243/47746728-bc2c6a80-dc97-11e8-9029-8bd7ae5247ba.png)
> I want direct attach w\o pressing buttons, you can attach to it when fall\jump

**Comment by SlayksWood** [comment]
Still an issue after https://github.com/StrangeLoopGames/Eco/pull/6959

**Comment by IcedForge** [comment]
This was merged into dev branch and not staging leaving 9.1 in a bit of a pickle can we add this in staging as well or instead?

**Comment by SlayksWood** [comment]
Still an issue in staging-1831.

**Comment by SlayksWood** [comment]
Closed for now. But we can return to this later. It might be worth editing the speed a bit, especially in 3rd person view
