### ISSUE TITLE
Not sure if this is just how the game is or if it's an issue?

### ISSUE THREAD

**Issue by InsomniCat** [StrangeLoopGames/EcoIssues#18507]
So I've been noticing that when I plant things and come back to them the next day or even a few hours later what I planted isn't always there, instead it's grass or some other "weed" plant (I know they aren't really weeds it's just what I call the random grass and other plant fiber based things). I don't really know if this is a bug or what's going on but it is kind of irritating to basically end up wasting seeds to plant something and not even get what you planted. (Picture for example of what happens, ignore the dead plants)
![Untitled](https://user-images.githubusercontent.com/71470443/94469110-20f5e580-018b-11eb-8f52-7127422292c7.png)

**Comment by fillion07** [comment]
Is the zone where you plant your pumpkins an area of high potential of yield?

Here where to look at to know where on the planet the pumpkins grow best:
Click "M" on your keyboard to open the map, open world layers tabs on the right side of the map, then open the "Plant" tab and finally check on Pumpkin Yield Potential
![Pumpkins](https://user-images.githubusercontent.com/7052045/94517542-2fc5b200-01f6-11eb-873b-462bf9e5d58f.png)

**Comment by beastyn** [comment]
@InsomniCat Thank you for the report.
If environment is not hostile towards your plants they should be fine. 10% can day anyway even in the perfect купшщт.
We did have some issues with dying plants. It should be fixed with 9.0.4 hotfix. We will check your case too.

**Comment by InsomniCat** [comment]
Like I said,  ignore the dead plants.  My issue is when I plant ANYTHING at all, not just pumpkins, and go back to check on it instead of what I planted something else is growing in the spot.  Usual grass or weeds

**Comment by InsomniCat** [comment]
> @InsomniCat Thank you for the report.
> If environment is not hostile towards your plants they should be fine. 10% can day anyway even in the perfect region.
> We did have some issues with dying plants. It should be fixed with 9.0.4 hotfix. We will check your case too.

The issue has nothing to do with the plants dying,  that's not what I asked about

**Comment by InsomniCat** [comment]
@fillion07 
@beastyn

**Comment by beastyn** [comment]
@InsomniCat if your plant is dead some other plant can take its place. The thing is that its just too fast right now, we will make more delay for this process later on.
