### ISSUE TITLE
USER ISSUE: Masonary table glitch

### ISSUE THREAD

**Issue by guardedki** [StrangeLoopGames/EcoIssues#18517]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Put any kind of stone in a stock pile.. Click on Mortared Door or Mortared Large hanging sign.. (Either of these will do). Set it and put the required work time in.. Walk away.. 

**Expected behavior:**
I expect the item to be made an in my stock pile at the top of the storage listing on the Masonary table!

**Actual behavior:**
It shows the message where the Project starts.. nothing showing an end. check the table and the whole project i project is gone along w/ the resources.  https://steamcommunity.com/profiles/76561198242321850/screenshots/ (for proof) (after a restart, i had to stay with the tab;e to watch them being made.. this is not fair to the player base.. at all)....
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5298282/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5298284/Player.log)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LadyNasse** [comment]
>"...project is gone along w/ the resources. https://steamcommunity.com/profiles/76561198242321850/screenshots/ (for proof) (after a restart, i had to stay with the tab;e to watch them being made.."

FYI that link goes to what looks like ARK screenshots.

**Comment by IcedForge** [comment]
@guardedki Thank you for your report, could you please upload the savefile .eco and also include a Dxdiag.txt file.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
