### ISSUE TITLE
[0.9.0.3 beta release-82] New plant generation logic causes lines between trees

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18515]
New hotfix for plants causes the trees to generate as tree farms in almost perfect lines.
![Screenshot_95.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/d572b6b4-b427-409e-ba78-b86d20d5c6c3)
![Screenshot_94.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0b3453a5-04a5-4e92-b634-c1931da62bf7)![Screenshot_96.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/098f5773-0d27-4dc3-87ab-a820ed9e0680)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/94655220-e9ac4380-0306-11eb-8350-44a88519e377.png)
![image](https://user-images.githubusercontent.com/45708377/94655339-16605b00-0307-11eb-8323-9d56814056e5.png)
