### ISSUE TITLE
[0.9.0 develop-67] Mortared Sandstone Door looks like Granite one

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18512]
![image](https://user-images.githubusercontent.com/45708377/94525622-02e8bd80-023d-11eb-8ede-02c4023ee5b2.png)

**Comment by Sekor2600** [comment]
fixed in svn

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/96121985-81aa4f80-0ef9-11eb-855e-fcd916adcfc7.png)
