### ISSUE TITLE
Project init duplicating resources

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1852]
![image](https://user-images.githubusercontent.com/774628/29337692-2021cdaa-81c7-11e7-9904-bcefdebd3ab0.png)

Looks like some order of initialization issue... I only had 10 logs in my stockpile but those 10 counted as 20.

**Comment by MarjieAVolk** [comment]
So the project needed 10, you put 10 in, it took 10, and you still had 10 afterwards?

**Comment by SeanAtr0n** [comment]
Project needed 30, I only had 10 in my stockpile. It seems to have taken 20 on creation even though I only had 10.

**Comment by MarjieAVolk** [comment]
Haven't been able to repro this

**Comment by SeanAtr0n** [comment]
Hmm guess carts just need 20, whoops nevermind >.>
