### ISSUE TITLE
Crash with Law Modification

### ISSUE THREAD

**Issue by Cipherian** [StrangeLoopGames/EcoIssues#18525]
After modifying law with this code, it caused the server to crash.
Current Law (Inactive Land Reclaim Act):
Section 1
On event Citizen Timer every 1 day on each person in Abandoned
Change owner of All property owned only by Abandoned to unowned
Proposed Law (Property Laws):
Inactive Land Reclaim Act
Citizens in the Abandoned demographics will have their properties reclaimed.
On event Citizen Timer every 1 day on each person in Abandoned
Change owner of All property owned by Citizen to unowned
[log_200929100246.log](https://github.com/StrangeLoopGames/EcoIssues/files/5300919/log_200929100246.log)
https://www.dropbox.com/s/h2e4hf1hocfn9cs/Game.eco?dl=0
https://www.dropbox.com/s/jqx26k9hmwxrzqs/Game.db?dl=0

**Comment by beastyn** [comment]
@Cipherian thank you for the report.
Merging this issue here #16568.
Is your sever OK after restart?
