### ISSUE TITLE
[0.9.1 develop-67] Some fake plants appear displaced first time adding in pot.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18521]
Step to reproduce:
- take agave seed,100
- add it to pot. Agave will appear shifted by 4 blocks
- take it and place again. All's fine:
![2020 09 29 Some fake plants appear displaced first time adding in pot](https://user-images.githubusercontent.com/45708377/94556163-51aa4d80-0265-11eb-84e5-af18aef00824.gif)

check this one after fixing #17114. Maybe it's related

**Comment by ptitducanh** [comment]
I reset position of Agave, Jointfir and White Bursage.
