### ISSUE TITLE
Trampled Spread no longer decrease

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18533]
After 2 Weeks the Trampled Spread did not decrease
![grafik](https://user-images.githubusercontent.com/37456949/94743701-23696280-0378-11eb-9b01-c58547710cf7.png)
Because of this the area remains brown and the Grass does not grow back any more

With Player Activity you see that its much lower then the Trampled Spread
![grafik](https://user-images.githubusercontent.com/37456949/94743868-5c093c00-0378-11eb-9075-016be8f3839b.png)

**Comment by beastyn** [comment]
Adding here this one #18186

**Comment by mirasrael** [comment]
Another source of trampled is Debris? What do you have for Debris layer?

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/94997184-db318680-05a9-11eb-8346-ac5e6bcf862c.png)
Debris layer
but see no Treedebris in the World. Only thing was a lonely Tree stump

**Comment by mirasrael** [comment]
Issue was related to Debris cache updates (which effectively didn't work). I fixed the logic, but it caused Debris cache to reset. So it should work fine with new Debris, but old Debris information lost. It may be recovered, but will require very expensive full world scan (every block) so I guess we can let it go.
