### ISSUE TITLE
USER ISSUE: Iron pipe extend water

### ISSUE THREAD

**Issue by Shnickersss** [StrangeLoopGames/EcoIssues#18532]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Iron pipe extend water

**Expected behavior:**
Iron pipe must suck water

**Actual behavior:**
Iron pipe extend water

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Shnickersss** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5306062/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5306064/Player-prev.log)

**Comment by beastyn** [comment]
@Shnickersss thank you for the report.
I am not sure exactly what you mean. Can you provide screenshots, steps?

**Comment by Shnickersss** [comment]
When I bring the pipes to the water, they do not submerge in the water, but "push apart" the water like Moses
![1](https://user-images.githubusercontent.com/72146035/94822673-940d8f00-040b-11eb-8c96-3ac3729ea319.png)
![2](https://user-images.githubusercontent.com/72146035/94822677-95d75280-040b-11eb-8ccf-74b6203baa00.png)
![3](https://user-images.githubusercontent.com/72146035/94822679-95d75280-040b-11eb-94ef-39840125938d.png)
![4](https://user-images.githubusercontent.com/72146035/94822681-966fe900-040b-11eb-86fb-d46a9e6d6e9c.png)

Thank you for your respons!

**Comment by beastyn** [comment]
Ah, yes, thanks for the details. We are going to improve water behavior. I will merge this issue into #12080
