### ISSUE TITLE
[0.9.0.3] Civics: Can't unclaim as elected title owner

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18537]
1) Claim a property.
2) Create an elected title
3) Transfer the property to this elected title
4) Own the elected title
5) Try to unclaim

It will tell you that you do not have access.
You should be able to unclaim.
From this #18509

**Comment by IcedForge** [comment]
Fixed in changes made for 9.1, reopen if it shows up again.
