### ISSUE TITLE
[0.9.0.3 Beta] Government Notifications Fill Screen so that I cannot see to place blocks

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18534]
So, when the government and other game notifications are obscuring the screen so that it is unplayable for a chunk of time and I have to stop what I am doing to allow them to fade before I can continue working.

![20200930182704_1](https://user-images.githubusercontent.com/1329717/94750646-277f8b00-034c-11eb-9cf4-64ef9ed8350f.jpg)

**Comment by Sarah-Graesyn** [comment]
like, spamming my chat log, or even the notification log is one thing but making it so that I can't see to play the game is absolutely ridiculous

**Comment by beastyn** [comment]
@Sarah-Graesyn thank you or the report.
You have "Infobox on success" in Then section (it is hidden with gear). But it will work only with some triggers right now. Will be fixed in 9.1 #18213
