### ISSUE TITLE
Fix civics upgrade issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18535]
- Bad duties
![image](https://user-images.githubusercontent.com/3536496/94752154-40ce0a80-033f-11eb-8223-e8983d2fbf1f.png)
- Revised law not appearing in tooltip
- Copying not working when editing an existing law

**Comment by beastyn** [comment]
Duties tab is here #18505
Will you take it oe leave it for @gabrielgindridev ?
