### ISSUE TITLE
ECO 9.0.3 beta - Store Ownership via Titles prevents from players selling at store

### ISSUE THREAD

**Issue by Uniphix** [StrangeLoopGames/EcoIssues#18530]
We have a store title "Store Manager" that is appointed to a few people to manage the global store on our server.  However, we haven't really tested the "Buying aspect" but when a player tries to sell a single item with a store linked up to 5 empty chests and 1 large lumber stockpile.  They receive the "no space destination in inventory" issue.  What we expect is that if a Property Ownership is linked to a "Title" that all "Title Holders" in that group would be appointed to manage the store, everything works as expected except the player cannot sell.

Logged into the "Seller" that wants to sell 2 beet greens!
![382310_screenshots_20200930011418_1](https://user-images.githubusercontent.com/1548249/94660311-5d742f00-02ba-11eb-8fb0-5eeb4c898956.jpg)

Logged into a character that is part of the "Store Manager" title group, and clearly you can see that there are items listed and completely empty for storage.  So I am not sure exactly what is happening and or if it is a bug so I am reporting it.
![382310_screenshots_20200930011728_1](https://user-images.githubusercontent.com/1548249/94660769-fc009000-02ba-11eb-9e1e-9fa7b6d5ae83.jpg)

![382310_screenshots_20200930011733_1](https://user-images.githubusercontent.com/1548249/94660774-fd31bd00-02ba-11eb-974b-c80109492791.jpg)

Thank you,
Ravenal/Uniphix

**Comment by beastyn** [comment]
@olegshegai for catching up:
person 1 is placing storage on a deed
move rights to the deed to the elected title
then placing the chest on free space -> caiming the deed -> passing deed to the elected title
Person 2(with elected title) is linking this chest to the store
other person 3 (or person 1) can not sell anything in that store though chest is linked

**Comment by johnkslg** [comment]
This is a tricky one, because linked storages are setup via users manually connecting them to the table.  If the table isn't owned by any user, then we can't setup the links for this.  Couple ways we can go about it:
- When determining linked storage, look at what storages are linked for ALL users in the owner alias.

- Have a way to set linked storage for yourself AND for the owner demographic, if youre part of it. This is more complicated and confusing though, I think we go with the first.

**Comment by SlayksWood** [comment]
1. I would prefer a different option. Which would possibly partially solve another problem too.
I'd add option to select which title/name you want to be when you use this store:
- so I want to have government store. I have special title for it 'Store Owner'. And i'm user of rhis title.
- when I open store I will have option (only if I'm user of this title) to select how I want to use this store. If I select store owner I can use it like seller, but if I select my name I will use this store like buyer:
![image](https://user-images.githubusercontent.com/45708377/97264215-9362ef80-1835-11eb-9174-444658f7a075.png)

2. This option is simpler, but doesn't solve the second problem.
If you have access to the title, you edit store as the title owner. What John said. The only difference is that the setting is the same for all users. And if someone has changed, then it will change for everyone.

**Comment by D3nnis3n** [comment]
@Uniphix If you do have a SLG account and want a little reward, send me an e-mail to dennis@strangeloopgames.com with your SLG ID :)
