### ISSUE TITLE
USER ISSUE: Wooden cart cannot be picked up due to inventory full even there's enough room in your bag and bars

### ISSUE THREAD

**Issue by Kyle2027** [StrangeLoopGames/EcoIssues#18542]
![Wooden Cart bug](https://user-images.githubusercontent.com/24474357/94799009-29e4f200-03eb-11eb-8ec3-2e463e4acf9b.png)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5311240/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5311241/Player.log)

\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
1. Take a wooden cart;
2. Fill it with goods;
3. Try to move it over a broken bridge;
4. Unload it with any tool or drag and drop into a Stockpile;
5. Attempt to pick up the wooden cart with your Hammer.

**Expected behavior:**
At picking up with the hammer it should be removed from the world.

**Actual behavior:**
Instead an error message is displayed on screen like : "Not enough room in inventory"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, i don't have mods installed. The game is installed through steam client as it is.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Kyle2027 Thank you for the report.
Can you provide inventory tooltip:
![image](https://user-images.githubusercontent.com/45708377/94800356-22bee380-03ed-11eb-85d2-db59124ed3ea.png)
You should have enough weight in backpack to pick up Wood cart.
Also provide screenshot of Wood Cart storage

**Comment by SlayksWood** [comment]
This issue is returned #17119. @Kyle2027 should have another message.

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/101766447-dc27ec80-3af3-11eb-8e43-0ef5edf99a8c.png)
