### ISSUE TITLE
Fix PR build fails

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18547]
If it's legit failing tests, it should output the results as before. 
![image](https://user-images.githubusercontent.com/3536496/94862943-8a296300-03ee-11eb-85b9-6b21f0a0f8cb.png)
![image](https://user-images.githubusercontent.com/3536496/94862950-8e558080-03ee-11eb-87d3-81a5e3774ca7.png)

Also, havent seen any CI tests fail for awhile, meaning theyre probably not running. Can you check that they are?

**Comment by redwyre** [comment]
As a work around until I have time to fix this:

Click the details link:
![image](https://user-images.githubusercontent.com/431728/94864894-06b85200-0480-11eb-8e9d-663c18d8769b.png)

Click console output:
![image](https://user-images.githubusercontent.com/431728/94864941-1768c800-0480-11eb-8939-741b99d160ab.png)

Scroll down to the bottom then scroll up to look for what failed:
![image](https://user-images.githubusercontent.com/431728/94865020-3cf5d180-0480-11eb-9b01-daf3e101eb4d.png)

**Comment by redwyre** [comment]
clean error doesn't exist anymore, and added some extra cases for failures with running tests
