### ISSUE TITLE
USER ISSUE: Trapped in Stockpile

### ISSUE THREAD

**Issue by benny4444** [StrangeLoopGames/EcoIssues#18546]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
exit vehicle with zero clearance to exit next to a building, underneath a structure with a stockpile on it, filled with items.

**Expected behavior:**
exit normally, maybe on passenger side that has tons of clearance

**Actual behavior:**
it exits you on zero clearance to exit side, then places you above vehicle, and if you so happen to be next to a building, poof, your on top of the building. in this case a stockpile was on the building. now I'm stuck inside the stockpile. The boxes are acting like a invisible wall preventing me from jumping out of this nightmare.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@benny4444 thank you for the report. Did /unstuck help you?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
