### ISSUE TITLE
[0.9.1.0 develop 73] Law Logic description issue with multiple sections

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18555]
Logic description building doesnt work properly.

Add a law and it builds descriptions as you make the law.
![Screenshot_5.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/584a7a35-31ee-48b6-bca3-8a9e3e36ccc9)

Add a law, make sure its 100% error free.
Add a second section and it will not build the logic while you are making the law.
![Screenshot_7.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/09600992-bc66-422a-b7eb-e9190d632696)

**Comment by SlayksWood** [comment]
#18499

**Comment by ptitducanh** [comment]
It should be fixed by #18499. 
I'll move this issue to Review.
