### ISSUE TITLE
[9.0.3 release-78] Treasury taxing not working

### ISSUE THREAD

**Issue by evil-morfar** [StrangeLoopGames/EcoIssues#18553]
When trying to tax an account from the treasure (with all necessary permission/titles etc set) it seems to go through, and notifications are publicly announced.

![image](https://user-images.githubusercontent.com/10189576/94905999-0cbd2b80-049e-11eb-9300-b77e5de406cf.png)

However, the account isn't actually taxed, and nothing is transferred.

**Comment by IcedForge** [comment]
This should have been fixed here. 
#17604

Can confirm this is still an issue; I can use allocate but when i tax someone it does not actually take money, it only says it takes money.
![Screenshot_26.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/515140f2-8b8e-414d-a327-a063067a8ee4)

**Comment by olegshegai** [comment]
Taxation fixed
Correction of feedback messages may be reopened with reduced priority (or as a separate issue)
