### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by lilithwhite** [StrangeLoopGames/EcoIssues#18559]
My server is crashing after loading it, unfortunately the error doesn't reach the log or dump files so I can only snap a pic of it very quickly. I'm on the latest version of Eco (Eco Server 0.9.0.3 beta release-78)
![eco](https://user-images.githubusercontent.com/39236392/94942171-91c83500-04de-11eb-9cdc-4650693a8098.png)
Also log included even though there's most likely nothing more useful in it.
[log_201002063410.log](https://github.com/StrangeLoopGames/EcoIssues/files/5318952/log_201002063410.log)

**Comment by lilithwhite** [comment]
Oh there is more about the crash in the event viewer:
Faulting application name: EcoServer.exe, version: 1.0.0.0, time stamp: 0x5e9fbf92
Faulting module name: coreclr.dll, version: 4.700.20.20201, time stamp: 0x5e867108
Exception code: 0xc0000005
Fault offset: 0x0000000000066a54
Faulting process ID: 0x465c
Faulting application start time: 0x01d698d179072bd5
Faulting application path: D:\SteamLibrary\steamapps\common\Eco Server\EcoServer.exe
Faulting module path: C:\Users\regis\AppData\Local\Temp\.net\EcoServer\fpu2dcdw.hvg\coreclr.dll
Report ID: ae462e19-57da-40f6-b12f-431832845a7d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by redwyre** [comment]
Here's some things you can try: https://github.com/StrangeLoopGames/EcoIssues/wiki/Troubleshooting-EcoServer

**Comment by beastyn** [comment]
@lilithwhite thank you for the report. Please read a troubleshooting wiki page and let us know if it won't help you.

**Comment by lilithwhite** [comment]
It seems it was caused by a setting in EcoServer.runtimeconfig.json under %TEMP%\.net\.
Adding the following settings causes this crash:
"configProperties": {"System.Runtime.TieredCompilation": "false"},

**Comment by redwyre** [comment]
Did you make this change yourself?

**Comment by lilithwhite** [comment]
Yea, I needed it to get a mod(Applied Energistics) working but the crash occurred with or without the mod, just having that setting was enough.
