### ISSUE TITLE
[0.9.1 develop-73] No bullrush destroy animation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18554]
There is no some funny explosion like parts with scything.
https://i.gyazo.com/bf0b6228e1a506dca78fe34ab17420cd.gif

Ask @keegan-o for animation itself if needed.

**Comment by MazonDel** [comment]
Fix was entirely in an SVN update to "/trunk".

The "P_BullrushPlantDelete" prefab had gotten disconnected from the Bullrush entry in the "Plant Blocks" blockset.
