### ISSUE TITLE
Status indicator light is confusing

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1855]
When your table isn't running, the status light indicator isn't strong enough, and it also doesn't tell you what to do.

Suggestions:
- When the light is red, have it flash
- When you click on the light, open the status tab?

**Comment by metachronism** [comment]
The status light in general is taking up space that was intended for an icon of the object in question (look at the sprite sheet, there is a big square frame that is what its intended for)
