### ISSUE TITLE
USER ISSUE: white screen of death without a crash

### ISSUE THREAD

**Issue by Vantropix** [StrangeLoopGames/EcoIssues#18551]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
1. start the game 2. wait for the loading circle of a tree to finish 3. white screen forever 4. press esc and notice the game didn't crash but it's just stuck on a white screen, i can ajust settings but it does nothing to solve the issue

**Expected behavior:**
game should start normally

**Actual behavior:**
game gets stuck on a white screen endlessly

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, i re-installed the game checked files and all, nothing makes this white screen go away

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
there are no logs, i don't get any further than initial loading

**Comment by SlayksWood** [comment]
@Vantropix Thank you for the report.
1. Please provide your PC specification (include Operating System).
2. Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
