### ISSUE TITLE
USER ISSUE: Duping

### ISSUE THREAD

**Issue by HunterKnight638A** [StrangeLoopGames/EcoIssues#18568]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Take some logs from a small stock pile and place them back down from the inventory and it adds some more logs to the stock pile.

**Expected behavior:**
The amount of logs should have remaned the same.

**Actual behavior:**
Instead it added some logs to the caried amount.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and don't know.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@HunterKnight638A 
Can you give any additional information?
1. What stockpile do you use?
2. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Any video or screenshots of position to take logs.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
One type of duping with stockpile were fixed in 0.9.0.4
