### ISSUE TITLE
Dirt Terrain Builder Issue

### ISSUE THREAD

**Issue by Indyjunk** [StrangeLoopGames/EcoIssues#18562]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Surround 2 wood walls that meet with dirt

**Expected behavior:**
a smooth surface

**Actual behavior:**
Jagged edges (Graphical bug)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A

Here are pictures that better describe the issue than I can.

![20201002143727_1](https://user-images.githubusercontent.com/61563347/94958548-b829a880-04bd-11eb-807a-93b80d4eafd4.jpg)

![20201002143744_1](https://user-images.githubusercontent.com/61563347/94958556-ba8c0280-04bd-11eb-9e18-e10729109e02.jpg)

**Comment by keegan-o** [comment]
This was an issue on many terrain builders, I went through and fixed them all-- hopefully no new issues arise from this but I saw nothing from my tests. Fixed for whatever patch is after 9.2.
