### ISSUE TITLE
Different doors has the same texture

### ISSUE THREAD

**Issue by FlyNeko48** [StrangeLoopGames/EcoIssues#18566]
![2020-10-03_113915](https://user-images.githubusercontent.com/14149980/94987252-a0a9f880-056d-11eb-8d95-da8d9c26746a.png)
Lumber door and Hardwood lumber door

![2020-10-03_114155](https://user-images.githubusercontent.com/14149980/94987263-bb7c6d00-056d-11eb-8012-77ffd2d10662.png)
Composite doors - composite lumber, hardwood, birch and joshua

0.9.0.3 beta release-78

**Comment by Sekor2600** [comment]
Prefabs in SVN are fixed

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/b332fa32-7a6c-4704-87bd-138ac00584ca)
Thanks sekoris!
