### ISSUE TITLE
USER ISSUE: No ore?

### ISSUE THREAD

**Issue by seaglassfoxen** [StrangeLoopGames/EcoIssues#18563]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Start a new world: solo. Mine for materials for about 2 weeks. 

**Expected behavior:**
Mining should eventually produce ore of some kind.

**Actual behavior:**
After hollowing out most of a giant subterranean mountain of sandstone in the desert biome, and having various stones and soils completely take over your camp and you start running out of places to put stockpiles, find zero ore. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, though I did go in and monkey with code trying to resolve this on my own. And yes. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_201002124008.log](https://github.com/StrangeLoopGames/EcoIssues/files/5319927/log_201002124008.log)

**Comment by SlayksWood** [comment]
@seaglassfoxen 
Ore generation has been changed in 9.0. Now it lies much lower.
You can privide a save file, I'll check.
You can read about new ore generation here:
https://steamcommunity.com/games/382310/announcements/detail/2087922294403392738

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.

**Comment by seaglassfoxen** [comment]
Hey there.
Yes, I see. According to the code, it has the highest chance of spawning
far deeper than it used to, though small amounts should still spawn at
higher levels. According to the percentages at least. I'm no expert but it
looks like python, which seriously gives me a headache. (Or maybe MS just
sucks at teaching it?)  lol. So who knows... I probably just didn't dig
long enough or far enough.
I would love to send you a copy of the save but unfortunately, I had a
drive failure recently and lost pretty much everything, including all my
game save files. First, the primary game drive went, then 9 hours later,
the backup drive failed before I had a chance to salvage anything. When I
get my new motherboard etc installed and start a new game, if I run into
the same issue, I will send along a save.
Thanks for the response! Have a wonderful day!.

Best Regards,
G Naoma Roos
