### ISSUE TITLE
USER ISSUE: No start menu 

### ISSUE THREAD

**Issue by Ryuu3rs** [StrangeLoopGames/EcoIssues#18569]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
load game 

**Expected behavior:**
to be able to have a start menu to play the game 

**Actual behavior:**
having no main menu but esc still works 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ryuu3rs** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5321937/Player.log)

**Comment by redwyre** [comment]
Hi @Ryuu3rs, it looks like there was an issue with steam, could you try restarting steam and run it again?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
