### ISSUE TITLE
USER ISSUE: Cart/mole hybrid

### ISSUE THREAD

**Issue by Ichimaru8259** [StrangeLoopGames/EcoIssues#18574]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
1. Have a cart
2. Look away

**Expected behavior:**
Stay where I left it

**Actual behavior:**
Fell thru the ground. Only the tips of the handledbars are above the terrain

**Do you have mods installed? Does the issue happen when no mods are installed?:**
A. Yes. B. No idea. 
The mods came with the server I joined

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #15688
