### ISSUE TITLE
USER ISSUE: Delays placing objects or picking up

### ISSUE THREAD

**Issue by onehotday** [StrangeLoopGames/EcoIssues#18575]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Place objects or pick up.

**Expected behavior:**
place or pick up

**Actual behavior:**
it lags showing connectivity issues.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
none

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by onehotday** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5323994/Player-prev.log)

**Comment by beastyn** [comment]
@onehotday thank you for the report.
1) Can you provide your PC spec?
2) What ping do you have on a server you play?

**Comment by onehotday** [comment]
I ended up deleting the game and created a new one the issues went away.

Jeremy Smith
