### ISSUE TITLE
[0.9.0.3] Currency Rounding Issues

### ISSUE THREAD

**Issue by gehnster** [StrangeLoopGames/EcoIssues#18578]
We minted 200k coins at the beginning of the game, throughout all the buying and selling of coins the rounding errors have accumulated significantly. As you can see after 7 days of transactions we now have ~535 extra money in circulation.
![image](https://user-images.githubusercontent.com/7077730/95032946-0c7d8580-0682-11eb-880e-fc5b4570f84b.png)

**Comment by SlayksWood** [comment]
merged to #8466

**Comment by gehnster** [comment]
So, in other words don't care, won't fix. Just saying my issue vs the merged issue is 10 thousand issues difference. Let's call a bug a feature at that point and be done with it.
