### ISSUE TITLE
Crafting Soil sampler on Tool bench requires Wrong labor type

### ISSUE THREAD

**Issue by jtac** [StrangeLoopGames/EcoIssues#18577]
Bug: On tool bench, soil sampler requires generic labor to create.
Expected: On tool bench, soil sampler should require fertilizing labor to create.

Additional note: icon for labor shows as fertilizer, not generic labor -> seems like a misconfigured labor type.

**Comment by SlayksWood** [comment]
@jtac 
Don't have any problem with it. Without taking Fertilizers:
![image](https://user-images.githubusercontent.com/45708377/95082015-1a371780-0723-11eb-8f10-09b8e42a5c1c.png)
![image](https://user-images.githubusercontent.com/45708377/95082169-50749700-0723-11eb-8abf-74bd0838b712.png)

After taking. Use 25 Calories. It means that benefit is working:
![image](https://user-images.githubusercontent.com/45708377/95082254-7306b000-0723-11eb-90fd-65cd7f0c4b1b.png)
give Fertilizers experience:
![image](https://user-images.githubusercontent.com/45708377/95082451-b2cd9780-0723-11eb-9668-f0268b9ec39e.png)

Can you provide more information?

**Comment by jtac** [comment]
If it's intended that you _should_ be able to craft a soil sampler without having fertilizers specialization, then there's no issue.

I expected soil sampler requiring fertilizers specialization as it asks for fertilizers labor
