### ISSUE TITLE
[0.9.0.3 beta release-78] Frequent Client Crashes

### ISSUE THREAD

**Issue by Aryathal** [StrangeLoopGames/EcoIssues#18570]
Unfortunately, the game crashes quite frequently for me. At first I was using steam, and then I tried the installer from the play.eco site, but that didn't solve the problem. Currently, I'm using the latter one.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5322005/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5322006/Player-prev.log)

On servers with few players and areas with few objects it runs relatively stable, if I don't move too much. But I tried to join the Giant Panda server right now, and the game crashes after about 2-5 minutes.

I don't use any mods.

**Comment by redwyre** [comment]
Looks like it's caused by #18403, you can follow that issue to track the progress

**Comment by Aryathal** [comment]
Um, I'm not sure, but #18403 is marked as fixed and closed. Was that fix already included in one of the updates? Because I'm still getting crashes.

**Comment by redwyre** [comment]
try 9.1, if it's still an issue I'll reopen this issue
