### ISSUE TITLE
Add a little icon to the top of play.eco that points downwards, directing people to the tree

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18588]
Some people dont scroll down and see the cool tree we have, I'd like to make a little icon that directs them to do it, something like this:
![image](https://user-images.githubusercontent.com/3536496/95115249-02976900-06fa-11eb-9977-7736177fa953.png)
(dont use this image exactly, make it better)

**Comment by j3fffff** [comment]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/9023fe6b-5b35-4841-8a82-0dfab68d2e6d)
