### ISSUE TITLE
Demographic wages incorrect.

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#18587]
Demographic wages continue to pay after demographic was revised.
![image](https://user-images.githubusercontent.com/8082068/95100000-a125c900-06fe-11eb-8ea2-dd71264a7623.png)

It is not an issue with the paying off partial wages during transition to revision it continues to pay old demographics after revisions continuously even after server restarts. Also, demographics are double paying.
![image](https://user-images.githubusercontent.com/8082068/95100227-e518ce00-06fe-11eb-8d3c-245c8b0d62c3.png)

**Comment by SlayksWood** [comment]
merged to #18474
