### ISSUE TITLE
Admin Chat Commands with Star support

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#18581]
Hello,
 one of the most questions by players to server admins is to change some usage of the stars given into specialities. Most of the time players want to undo a given star to a specialty. Right now as admin you do not have the possibility to take one star of a user so he can reassign it to another specialty. The only way right now is to reset the player's account by giving him admin permission, run the command to unlearn and reset everything, and then take the admin power again.

I would recommend to get some commands similar to:
/skill reset [playername]
/skill unlearn [speciality] [playername]
/skill unstar [speciality] [playername] (maybe you have a better name then unstar :-) )
/skill reset expiriance [speciality] [playername]
/skill give expiriance [speciality] [playername] [number]
maybe some more commands to get fully flexibility.

Thanks in advance.

**Comment by johnkslg** [comment]
We probably should allow people to unlearn stuff for a penalty too

**Comment by Alteraner** [comment]
Penalty could be managed by law system. A trigger to unlearn should be able.

**Comment by beastyn** [comment]
@Alteraner thank you for the attention to this problem.

Sorry to say, but we won't add trigger for now. It will be strange as it is not common action and only for admin use.

In current state we have three commands which should be enough to help people. I don't think we should dig deeper for now (as penalties or xp changes) as it is quite dangerous. And also I assume we will revisit Skill system at some point.
So, for now we have

/skills reset <player>,<skill name> - reset pointed specialization
(empty skill name will reset all specs)

/skills removetalent <player>, <talent name> - for removing particular talent

/skills notalents <player>,<skill name> - remove talents for spec
(if skill name is empty talents will be removed for all specialization)

@johnkslg @WeaselDog should I proceed with other adjustments, like playing with xp in specialization or is it enough from your point of view?
Thanks!

**Comment by Alteraner** [comment]
Okay, got it. Would prefer if you can do a minor update and enable the existing commands with [playername] so I do not need to make a player an /admin to run the command and then /unadmin him again. That's a little bit painful as the commands only work for me. 99% of the cases I have to use the command for other players as they have accidentally given the star to the wrong specialty.

**Comment by beastyn** [comment]
@Alteraner Yeap, that is the idea. If everything in PR and QA goes fine, should be available in 9.2
