### ISSUE TITLE
9.0.3 Meteor impact shows despite it being disabled

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18584]
Meteor shows when joining the server despite it being disabled

![image](https://user-images.githubusercontent.com/61889138/95070577-3b3a4100-0700-11eb-96a4-9b4eea7a33c7.png)

![image](https://user-images.githubusercontent.com/61889138/95070598-442b1280-0700-11eb-93ae-51a3be7f3d5b.png)

Shows in web UI too

![image](https://user-images.githubusercontent.com/61889138/95070676-602eb400-0700-11eb-99ec-6df4ff85e012.png)

Does not show (correctly) in server browser
![image](https://user-images.githubusercontent.com/61889138/95070759-7d638280-0700-11eb-9a61-1be6b58fc4dc.png)

No meteor is around the planet

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/97535119-2b92dd00-19cc-11eb-930f-48ad2af82b41.png)
But in website we still have a problem, but I will create another issue:
![image](https://user-images.githubusercontent.com/45708377/97535275-757bc300-19cc-11eb-9bd8-aa0ea6e93011.png)
