### ISSUE TITLE
Civics passed not attached to object

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#18586]
I know this has been posted a few time and is flag fixed but it is not the case. #18440
In issue 18440 it was mentioned restarting corrects the issue, but this has not worked for me. 

When titles or demographics pass the do not get attached to object they were created on whether by election or admin commands. Results seem to be inconsistent out of several attempts only one stuck it was not the first or last to be proposed or pass.
![image](https://user-images.githubusercontent.com/8082068/95098710-0973ab00-06fd-11eb-9f43-9a14f3aa7ae8.png)
![image](https://user-images.githubusercontent.com/8082068/95098833-290ad380-06fd-11eb-8b10-ddbcc006b66d.png)
![image](https://user-images.githubusercontent.com/8082068/95099143-8a32a700-06fd-11eb-9ed8-10182d463ab5.png)

**Comment by beastyn** [comment]
Yeah, this situation is in #18440 Also this system will likely be changed with the next update, so merging it.
