### ISSUE TITLE
[0.9.1.0 develop-75] Missing poligon in a door

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18580]
There is a hole in the model for composite doors
![bandicam 2020-10-05 11-38-13-807](https://user-images.githubusercontent.com/27898520/95050838-ac302780-0705-11eb-8dbe-60b346cc3b0c.jpg)

**Comment by Sekor2600** [comment]
its on both sides

**Comment by Phlo123** [comment]
I fixed the mesh and replaced it in SVN.
