### ISSUE TITLE
TypeTooltip not working properly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18598]
![image](https://user-images.githubusercontent.com/3536496/95155460-0d2d1f00-0749-11eb-9c42-fb8fbd38dcbd.png)
Problem with the new style of tooltips for types:
- It's not putting the whole tooltip text into the foldout of the MarkedUpName, that means the name will be something like <foldout data="wayyy too much data">Tooltip title</foldout>.
- Tooltips on types are supposed to call the static function tooltips on the type, like this one:
![image](https://user-images.githubusercontent.com/3536496/95155726-a2301800-0749-11eb-8b00-a6725bb4d052.png)
Or this one, which shows how it can accept a type and a user:
![image](https://user-images.githubusercontent.com/3536496/95155798-ce4b9900-0749-11eb-808a-b4eb88c1d59a.png)

Need to make this work like other tooltips, where it queries the server for the data upon mouse-over, and then it builds it (or returnts cached data when theres no functions to call and it just describes a type). TypeTooltip used to do this, so you might want to restore it and find a way to preserve its functionality.

**Comment by olegshegai** [comment]
May be closed since type tooltips are back (https://github.com/StrangeLoopGames/Eco/pull/6935) and not broken (https://github.com/StrangeLoopGames/EcoIssues/issues/18182)
