### ISSUE TITLE
[civics-rebase-2-54] Civics Issues #2

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18590]
https://github.com/StrangeLoopGames/Eco/pull/6875
- [x] Rename "Create Ratification Election" -> Create Constitutional draft?

- [x] Need some order clarification of tooltip error in Amendments, since you are allowed to not set proposer and election process if you use executor, it can be confusing to see this tooltip not sure what we can do to simplify it or if its good as is.
![Screenshot_30](https://user-images.githubusercontent.com/24981362/95127233-f7732600-0757-11eb-8547-35d195ce26c7.jpg)

- [ ] Need to limit description length in civics objects as you can make them obscure and hide the actual object itself.
![Screenshot_32](https://user-images.githubusercontent.com/24981362/95128660-0f4ba980-075a-11eb-9aa5-ef773cc5d518.jpg)

- [ ] Wages listed under civics objects that are not yet enacted (only drafted) are attempted to payout.
![Screenshot_33](https://user-images.githubusercontent.com/24981362/95128937-79644e80-075a-11eb-9246-4c03d70d497d.jpg)

- [ ] Notifications for the new baked multi elective stuff needs to be nested somehow to avoid the text overlap
![Screenshot_34](https://user-images.githubusercontent.com/24981362/95129918-08be3180-075c-11eb-81c5-c76ea2db5ef1.jpg)

- [x] Capitol Constitution Description text misalignment it should be left and the button to edit is way off but that might be a symptom from the alignment issue?
![Screenshot_35](https://user-images.githubusercontent.com/24981362/95130070-4b800980-075c-11eb-8cac-732daeab2ffe.jpg)

**Comment by johnkslg** [comment]
```
Rename "Create Ratification Election" -> Create Constitutional draft?

```
Will leave this as is, because you have to do this to create the election.

**Comment by johnkslg** [comment]
These arent related to the civics multi election PR so Im going to merge that one

**Comment by johnkslg** [comment]
Wages need to register/deregisted when the state changes, there's a virtual function called on the containers when the state changes you can hook this up to.
