### ISSUE TITLE
Jenkins not displaying failures

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18595]
Jenkins failed:
![image](https://user-images.githubusercontent.com/3536496/95152504-0fd84600-0742-11eb-9540-cbb4ed5d0901.png)

Clicking details shows 'no failures'
![image](https://user-images.githubusercontent.com/3536496/95152476-ffc06680-0741-11eb-8c2a-45092a2d0d3e.png)

On PR: https://github.com/StrangeLoopGames/Eco/pull/6875

**Comment by redwyre** [comment]
This is similar to https://github.com/StrangeLoopGames/EcoIssues/issues/18547, the same workaround applies

**Comment by redwyre** [comment]
Jenkins build has been significantly refactored, open a new issues if it happens again (but it's working fine now)
