### ISSUE TITLE
Make tooltip over text detect a rect around the text instead of the actual text pixels

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18597]
![animx22](https://user-images.githubusercontent.com/3536496/95154926-d0acf380-0747-11eb-9fe7-8789f0d129a3.gif)
it seems to do a raycast against the actual letters, so that spaces and circles in O dont trigger it and other such silly things.  Make it work by detecting a box behind the text instead.

**Comment by SlayksWood** [comment]
Still an issue. I don't have tooltip in space between 2 words.

**Comment by SlayksWood** [comment]
Still an issue for 9.2. PR was merged to 9.3. So I reopened it. We have 2 points - make another fix or push this issue to 9.3
