### ISSUE TITLE
Civics: Ui description lenght too long

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18604]
Need to limit description length in civics objects as you can make them obscure and hide the actual object itself.
![Screenshot_32.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/e6b48e64-594d-4c1e-85a6-64bf8a575c57)
Split from #18590

**Comment by johnkslg** [comment]
Need to change this dialog so the description is part of the scroll

**Comment by IcedForge** [comment]
This is only fixed for capitols, this is till an ongoing issue for Laws, Demographics, Districts etc.
