### ISSUE TITLE
[0.9.0.3 br-78] Road Tool should work on Desert Sand

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18601]
I've tried making some dirt roads in the Desert, but turns out you can't use the Road Tool on Desert Sand:

![image](https://user-images.githubusercontent.com/964559/95157523-1a004180-074e-11eb-83fb-cf4f838e7aac.png)

However, Desert Sand is not a type of Sand, it's a type of Dirt - if you shovel it up and down, you have a surface you can use the Road Tool on. So unless Desert Sand is supposed to be a type of Sand, the Road Tool should work on it.

Related - #18459

**Comment by SlayksWood** [comment]
No this is intented, If you make Dirt from Desert Sand and use Road Tool you will make Dirt Road, but after some time Dirt Road in Desert will dissapear.

**Comment by ThePiachu** [comment]
Huh, I was about to make another bug about dirt roads in the desert disappearing just now... Glad it's intended at least!
