### ISSUE TITLE
Civics: Notification text overlap

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18603]
Notifications for the new baked multi elective stuff needs to be nested somehow to avoid the text overlap
![Screenshot_34.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/878b13c3-2f49-4afe-b63c-2e991a0d8200)
Split from #18590

**Comment by johnkslg** [comment]
The alpha blend not working on these, probably remove it.
