### ISSUE TITLE
Camera: Add scroll distance in 3rd person

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18606]
Adding a scrollable ( maybe hotkey + scroll ) distance from character in 3rd person to allow easier placement of larger objects as well as the ability to overview in a better way.

**Comment by IcedForge** [comment]
Maybe take a look at #3550 to see if its possible to do this at the same time and or other potential 3rd person camera related tweaks?

**Comment by WeaselDog** [comment]
Added in 9.2
