### ISSUE TITLE
[Eco Server 0.9.0.3 beta release-78] Crash on fresh install on headless Linux box

### ISSUE THREAD

**Issue by EzTargetUK** [StrangeLoopGames/EcoIssues#18615]
When attempting to setup a new install of EcoServer on a new server using the SteamCMD install instructions on the wiki and running the executable I'm getting the following error:

[03:45:07] Failed to load server, Exception was Exception: DllNotFoundException
Message:Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
Source:System.Drawing.Common

System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()

This is on a headless Linux server. I've even tried to run with the -nogui switch that I spotted on one site which had instructions for the previous version of EcoServer, but still getting this error.

I've installed the .Net Core 3.1 SDK.

No changes were made to the install, as this was the first run of the server software on a brand new install of Ubuntu 20.04.1.

**Comment by EzTargetUK** [comment]
Thanks to help from DopeGhoti on the Discord server I was able to fix this error. 

sudo apt install libgdiplus

For some reason when I installed the requirements on the server it did not install the GDI+ library, At least I can now run the server on a headless Linux box.

**Comment by IcedForge** [comment]
Closing this then since its resolved.
