### ISSUE TITLE
[0.9.0.3 br-78] Mining Level 3 talent for calorie reduction not functioning

### ISSUE THREAD

**Issue by ACuteLittleCrab** [StrangeLoopGames/EcoIssues#18614]
When picking the level 3 talent perk for mining that reduced calorie costs by 20% for related tools, no reduction occurs.

Tested with a stone and modern pick. Before taking the talent, the stone pick cost 14 calories/swing and the modern pick 7 calories/swing. After taking the perk the costs remained the same at 14 calories/swing for stone and 7 calories/swing for modern.

**Comment by IcedForge** [comment]
duplicate #12378
