### ISSUE TITLE
[0.9.0 develop-76] 'Cancel' button is inactive if you change status for 'Remember me' button

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18610]
Step to reproduce:
- start to connect to server with password:
![image](https://user-images.githubusercontent.com/45708377/95177221-9fbfd380-07c6-11eb-8581-9212a299aec2.png)
- add check mark to remember me, 'Cancel' button is inactive:
![image](https://user-images.githubusercontent.com/45708377/95177337-c120bf80-07c6-11eb-8878-990b82d6cd9b.png)
But you can always close this window by ESC.

**Comment by WeaselDog** [comment]
Text for these is overcrowding the buttons. Please fix while doing this, or we can create a new issue.

**Comment by MrAnonymous110** [comment]
> Text for these is overcrowding the buttons. Please fix while doing this, or we can create a new issue.

Yes, I will do

**Comment by SlayksWood** [comment]
Still an issue. Text overlapping is fixed
![image](https://user-images.githubusercontent.com/45708377/95846090-afee2a80-0d53-11eb-8438-98d7e04a5679.png)

**Comment by MrAnonymous110** [comment]
Ah, I'm waiting to merge this part into develop branch :D

**Comment by MrAnonymous110** [comment]
Merged
