### ISSUE TITLE
[0.9.1.0 beta develop-77] Civics: Revisions of objects "duplicate on election passing"

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18623]
Add a law, pass via command or election doesnt matter then make a revision, select previous version and apply it will then add a new slot with the added revision law; rinse and repeat for infinite amount of slots.

![Screenshot_62.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b8d5b5b3-63ad-4f7c-a54b-ef08ba5097e6)

**Comment by IcedForge** [comment]
Making a revision of a revision no longer duplicates stuff, but its removing its prior version and adds the new one properly BUT its changing name title to <deleted> even though its not?
![Screenshot_82.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a2bb749e-d886-4323-b185-5eabcba0b8aa)
The law itself operates correctly and it passes election etc its just very confusing for the user.
Maybe have a check for if you are trying to copy the already drafted law? 
So on copy action, check if law ID is identical to what you already have?
![Screenshot_83.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a8086fbe-dd42-4839-bfad-28c8d0d4369d)

If i click accept here it will replace the current "Law 2 Revision" with an identical copy since the law id is the same it will remove the previous and rename it; then it will take this renamed deleted article and past it into place because its id is the same?

**Comment by SlayksWood** [comment]
Still an issue. Step to reproduce:
- create 3 laws (Law 24/Law 25/ Law 26):
![image](https://user-images.githubusercontent.com/45708377/96109784-b4e3e300-0ee7-11eb-9f6b-e2b866921944.png)
- start to revise law 26. start election. In moment when election is finished you will have 2 the same laws (maybe 2 sec), you need to have time to press Revise Law in Old Law 26:
![image](https://user-images.githubusercontent.com/45708377/96110255-46ebeb80-0ee8-11eb-8d6e-08db8f1bbed2.png)
- it will create another cell for law:
![image](https://user-images.githubusercontent.com/45708377/96110420-84507900-0ee8-11eb-8240-88d420bd47f3.png)

Video:
https://drive.google.com/file/d/1FL6TY0BQs_n32EvzikhlLCPPI-9M5yGL/view?usp=sharing

**Comment by johnkslg** [comment]
Need to be mindful of priorities. This doesn't break any features, and is very hard to trigger, so it shouldnt be high priority.

**Comment by johnkslg** [comment]
It will now check state and block it if you manage to click during a transition
