### ISSUE TITLE
[0.9.1.0 beta develop-77] Civics: Object passes election while parent object is picked up causes object to disappear

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18621]
If you add a law, propose it and it wins while the court is picked up it will invalidate the law on completed election regardless of outcome (this seems to happen randomly and is not reliably reproduced)

**Comment by johnkslg** [comment]
Fixed, now it will preserve objects in an active or draft election when you pick up a civic object.
