### ISSUE TITLE
Icons for laws are too spread out in chat

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18633]
![image](https://user-images.githubusercontent.com/3536496/95380215-4675a400-089b-11eb-979e-2f64ccb28102.png)

**Comment by ptitducanh** [comment]
I've updated the sprite asset setting. Icons are close to each others now. 
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/4f8c1255-fef1-4314-bc12-a33f57e96d13)
