### ISSUE TITLE
cw auto delete cron job not working on prod

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18637]
There are worlds in the db with an end_date that is in past.
It might be stopping worlds, but removing world from db is not working.

**Comment by j3fffff** [comment]
still seeing worlds with past due end_dates

**Comment by denysaw** [comment]
Where? Show me the world, which has `renew` = 1, `free` = 0 and passed date?
![image](https://user-images.githubusercontent.com/5720101/96046636-166a6a00-0e74-11eb-85ed-a5ea30538167.png)

**Comment by denysaw** [comment]
Why is `renew = 0` for passed worlds is completely another issue, but ok, let's just ignore that in this one.

**Comment by denysaw** [comment]
Removed `renew = 0` from conditions and cron worked great. Done on prod.
