### ISSUE TITLE
Upgrade not working in the Campfire

### ISSUE THREAD

**Issue by Laumiauu** [StrangeLoopGames/EcoIssues#18631]
Hi!
Most of the recipes in the Campfire are not affected by the upgrade.
After checking the campfire, it seems that in most of the recipes the ingredients are set to static value, and therefore, when pluggin the upgrade it does not affect the ingredient nor the recipe. 

I assume that it is a bug...

This happens in all campfires in our wolrd(server).

Thanks/Laura

**Comment by SlayksWood** [comment]
@Laumiauu Thank you for the report. 
This is intented behavior. Ingredients with yellow frame are static and they don't have influence from modules:
![image](https://user-images.githubusercontent.com/45708377/95418503-5dba9d00-0940-11eb-986a-e84ad0b93596.png)
