### ISSUE TITLE
[9.0.3] Civics: Entire Law goes missing after revision

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#18635]
After revising a progressive tax law to include new demographics to be taxed in separate clauses, the entire law disappeared from the court itself altogether, but continues to tax affected groups. 

The clause has 8 clauses, affecting 4 demographics groups in 2 different currencies, and has the same structure of "Citizen Timer (24h) to everyone, if [said demographic], Tax the relevant currency in a certain percentage."

A potential cause of the bug? The name of the law is called "Mingyang Tax Schedule Omnibus", and the revision is named as such with "Rev.2" added after that. POSSIBLY because a draft with a similar/same name existed before, and when it was pushed through, could have caused it to mis-reference and disappear from the court altogether?

**Comment by beastyn** [comment]
@SatsukiShizuka Thank you for the issue. We are tracking it here #18440
