### ISSUE TITLE
TagParser refactoring

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#18649]
Current tag parser implementation not flexible enough to handle scenarios like `"<Unassigned>"` text (with non-tag text formatted as tag) (see  https://github.com/StrangeLoopGames/EcoIssues/issues/17381). It was fixed by change in `ViewExtensions.SetText` as:
```csharp
 text.text = EcoTagParser.Parse(val, false, false);
```
but it breaks another cases where it should be auto-closed (i.e. if text is "<color=white>abc").

This change should be reverted and proper support for such cases added. I started refactoring in https://github.com/StrangeLoopGames/Eco/tree/tag-parser-refactoring, planned for 9.1/9.2.

**Comment by johnkslg** [comment]
We can simply not support display of things like <unassigned> and change the text.

**Comment by mirasrael** [comment]
It is already fixed and TMPro supports tags like this. So no real reason to not support them.
