### ISSUE TITLE
[0.9.0.3 br-78] Outline of items in a Large Lumber Stockpile sometimes doesn't match their visual representation

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18644]
Sometimes the outline of items in the Large Lumber Stockpile doesn't match their visual representation:

![image](https://user-images.githubusercontent.com/964559/95436388-9fc7ec80-0908-11eb-9f27-68e41a9fa9e6.png)

![image](https://user-images.githubusercontent.com/964559/95436404-a5253700-0908-11eb-9e65-51083e92a4da.png)

Not sure if it's only in that Stockpile or what's causing it. It might be due to some items being consumed from the stockpile?

**Comment by ThePiachu** [comment]
Actually it just happened to me on loading world in single player straight away, so probably isn't caused by things being used in manufacturing...

**Comment by SlayksWood** [comment]
@ThePiachu Thank you for the report, it related with world border(your stockpile crosses it)
dup #17767
