### ISSUE TITLE
[0.9.1 develop-78] Craft glithes if you have Craft resource/time multiplier = 0

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18640]
Need to set minimum value = 0,01 (more than zero)

- [ ] 1. If you set Craft resource multiplier = 0 your craft don't work at all.

- [ ] 2. If you set Craft time multiplier = 0 and start order without adding any resources you will have a lot of exceptions in log file:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5345665/Player.log)
from here: https://github.com/StrangeLoopGames/EcoIssues/issues/18426

**Comment by olegshegai** [comment]
@beastyn 
Probably divided to zero somewhere and infinite time appeared.
Handy stuff: 
![image](https://user-images.githubusercontent.com/56091594/95707333-e9466d80-0c61-11eb-85f1-d5a27d31aafd.png)

**Comment by beastyn** [comment]
So, I am using minimum value check.
Need to test:
-WebServerUrl without http:// and https:// in config
-WebServerUrl without http:// and https:// in ServerUI
- Craft Resource Multiplayer = 0 in config
- Craft Resource Multiplayer = 0 in ServerUI
- Craft Resource Multiplayer = 0 with Host World custom setting
- Craft Time Multiplier = 0 in config
- Craft Time Multiplier = 0 in ServerUI
- Craft Time Multiplier = 0 with Host World custom setting

**Comment by SlayksWood** [comment]
If you start server in game with parametrs = 0:
![image](https://user-images.githubusercontent.com/45708377/98680986-36a61f80-2373-11eb-90dc-1bf7cceb2ad7.png)
In server the same exception but in log file.
In server UI it will change to 0,01:
![image](https://user-images.githubusercontent.com/45708377/98681197-7967f780-2373-11eb-9a8f-a5c5c47a8541.png)

Close this one and create a separate issue for ingame tooltip #19246
