### ISSUE TITLE
[0.9.0.3 br-78] Rocker box handle missing texture / geometry on the inside connector

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18645]
Tiny visual glitch, the Rocker box's handle is missing a bit of texture / geometry on the inside of the connector thingy:

![image](https://user-images.githubusercontent.com/964559/95436668-f1707700-0908-11eb-939f-3ad50237e601.png)

![image](https://user-images.githubusercontent.com/964559/95436689-f9c8b200-0908-11eb-9d8a-116fde558b45.png)

**Comment by SlayksWood** [comment]
dup #18513
