### ISSUE TITLE
[ 0.9.1 develop-78] Control Buttons look strange

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18643]
In your PR:
![image](https://user-images.githubusercontent.com/45708377/95429507-2a353e00-0953-11eb-9aaa-798f00bee533.png)
I have:
![image](https://user-images.githubusercontent.com/45708377/95429522-302b1f00-0953-11eb-9e9b-7f0b8a0f0438.png)

**Comment by johnkslg** [comment]
This is happening because they arent being tagged as nine-slice somehow, or the  meta data of the image (which is stored in the corresponding .meta file) is getting lost, not checked in perhaps.

**Comment by tuha263** [comment]
Thank @johnkslg, I just updated the metafile. Please update SVN and recheck it.

**Comment by IcedForge** [comment]
They have a very strange square smear on them now?
![Screenshot_13.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/1fc9104b-a490-4fe4-b55c-8a2640ed82be)

**Comment by IcedForge** [comment]
Closing this and linking it to the other issue as its a duplicate kind of but not really.
