### ISSUE TITLE
Failed to load server??

### ISSUE THREAD

**Issue by Calura** [StrangeLoopGames/EcoIssues#18657]
![error](https://user-images.githubusercontent.com/53465919/95488260-522c9d80-0963-11eb-852f-0d3c11ede133.png)

The server won't load because of this. I've deleted the file and let the auto-updater recompile it. Nada.

**Comment by Calura** [comment]
![crashlog](https://user-images.githubusercontent.com/53465919/95499582-7c865700-0973-11eb-9af6-15395dd585c0.png)

Full log of the crash. We have no mods that affect the waste filter at all. We have one for colored trucks, and one for chat announcements, that's all. But all mods were also deleted in an attempt to stop and possible conflicts. This is still the errors that it came back with. We have implemented a TEMPORARY fix that removes the checks on the waste filter. But our auto-updater tried to download "app 739590" again, and I assume overwrites the waste filter file. So I disabled it for now, too.

**Comment by redwyre** [comment]
Try this: https://github.com/StrangeLoopGames/EcoIssues/wiki/Work-around:-Mod-compilation-issues

**Comment by Calura** [comment]
I didn't try deleting the *entire* mods folder, but I did delete that file that it kept pointing to in the exception. We have an auto-updater that uses an anonymous steam log-in and it kept downloading the "app 739590" after I deleted that file. But when it put the file back on, it was back to the bad version. So the auto-updater itself keeps overwriting the working file that WE created, and replacing it with the bad one.

We have someone familiar with code that was able to by-pass the "Last Tick Received" check that this file was trying to do. That is the file we created that worked. But when we ran the updater again, it started to crash AGAIN. So the actual files being downloaded from Strange Loop Games through Steam, are causing the server to crash and not load. We're just INCREDIBLY lucky to have someone that could alter the code in that exact file (waterfilter.cs) and fix it for now.

**Comment by redwyre** [comment]
The problem is probably not that file, but another, you should delete the entire mods file to make sure you are using the right version of _all_ the files.

"app 739590" is the steam app ID for Eco Server

**Comment by mirasrael** [comment]
Just checked last version from Steam. It has this (correct) line `public bool Operating => this.converter.In.BufferAmount > 0 || this.converter.In.LastTickConsumed > 0;`
You may try to verify all files in Steam. There is unfortunately nothing we can do on our side. Version in Steam is correct and most of users was successfully updated server with valid file version.

**Comment by Calura** [comment]
We didn't bother updating from Steam again. I just copied that line and pasted it into the file. It's good now. Thanks.

Although I'm now looking at our server as a result of all of this, and so many ideas are popping up. Maybe the updater was interrupted somehow and only downloaded part of a file. Maybe the file was written to a bad part of the hard drive. I don't know. But I do apologize for the back-and-forth. We have it all working now, at least. Thanks!

**Comment by mirasrael** [comment]
Happy you are fine now! Thanks for letting us know!
