### ISSUE TITLE
[V. 9.0.4] Corp Deed Bug

### ISSUE THREAD

**Issue by SPC-Phoenix** [StrangeLoopGames/EcoIssues#18654]
Version: 9.0.4
There's an Odd bug with Deeds Store and transferring the deed to a title instead of a person. When a title owns a Deeds the store doesn't recognize the  chests but when a person owns it, it does. Here's screen shots of what I'm taking about. Everything should work the same even though a title owns the  deed instead of a person. This is important if you want to set-up a house, like the white house, to be owned by someone in power and want to easily transfer ownership without hassle.

![Personal Owned](https://user-images.githubusercontent.com/72566272/95483961-b7bd6180-0944-11eb-978e-d362c53d74e1.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=2251678548
![Title Owned](https://user-images.githubusercontent.com/72566272/95483950-b2f8ad80-0944-11eb-8f40-ab9f5e8330d3.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=2251678623

**Comment by IcedForge** [comment]
Duplicate #18530
