### ISSUE TITLE
[0.9.1 develop-78] Clarify loan contract notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18651]
50 (Beastyn. credit) in my case:
![image](https://user-images.githubusercontent.com/45708377/95448874-a5571e00-096c-11eb-9bd4-afb0a1b6c6ce.png)
Step to reproduce:
- first player make loan contract.
- second player take it and without any pay press finish button.

**Comment by TwixterZ** [comment]
Fix tested and observed as of 9.4 Staging 2020

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/2252ccba-e979-4052-a370-3dc4436fcb23)
