### ISSUE TITLE
[V. 9.0.4] Multiplayer Organization issue

### ISSUE THREAD

**Issue by SPC-Phoenix** [StrangeLoopGames/EcoIssues#18655]
Version: 9.0.4
There's an issue with chest priority system. The problem is chest priority is different for each person. This is a problem because I am the organized one and my buddy doesn't care. If I go threw each machine set up a chest priority and what chest it's allowed to go into and not go into then this should be the same for everyone. It's a major inconvenience the way it is now.

**Comment by IcedForge** [comment]
Duplicate from https://github.com/StrangeLoopGames/EcoSuggestions/issues/329
