### ISSUE TITLE
[0.9.0 develop-78] Display Crushed Gold Ore on minimap like Gold ore

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18652]
Should be gray, now it's yellow:
![image](https://user-images.githubusercontent.com/45708377/95456954-cfaed880-0978-11eb-8c78-6a5adfb35ba2.png)
![image](https://user-images.githubusercontent.com/45708377/95456960-d2a9c900-0978-11eb-95e8-4c13f8da5734.png)

**Comment by ptitducanh** [comment]
I updated the Crushed Gold Ore to grey. 
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/7096554b-62ef-452f-8644-98fb13e2dc81)
