### ISSUE TITLE
Plant Yield Potential Heat Maps Broken in 9.0.4

### ISSUE THREAD

**Issue by Rybadour** [StrangeLoopGames/EcoIssues#18660]
Our server was running 9.0.3 and just updated and now all the heatmaps for plants no longer show white, yellow, red, purple but instead just a faint dark grey.

Screenshot: https://imgur.com/a/kg0cJaC

**Comment by SlayksWood** [comment]
@Rybadour Thank you for the report.
@WeaselDog 
It seems to be related to nutrients. There is no problem on new worlds, apparently we have to wait until the nutrient layers are restored. 
For example, on the server on which I'm playing, the restoration for Big bluestem has already begun (I suppose it is not need a lot)

**Comment by Rybadour** [comment]
Agreed, I didn't notice the note in the patch notes that says all the soil is reset to 0. I guess it's expected behaviour so I'll close this.
