### ISSUE TITLE
[0.9.1.0 develop-79]Civics: Trigger breaks storage links

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18668]
Trigger type "Add Resources To Work Order" - Sub trigger " Auto Contributed" will break links completely for automatically retrieving resources into a work order.

It will still add materials if you manually input into table, or add 1 cycle worth of materials if you add it to a linked stockpile BUT
it will not take any more materials from this stockpile per auto IF you have a law using this sub trigger type at all even if its just reading it and sending a text notification.
![Screenshot_95](https://user-images.githubusercontent.com/24981362/95581565-81add980-0a39-11eb-84d3-4db90f69e23a.jpg)

It looks like it struggles with an automatic addition as it is missing a variable for the blank user slot of auto pull resources, not sure how this reacts in terms of resource % for work party contributions etc. Need a proper overhaul to make sure this doesnt break 25 other things at the same time.

![Screenshot_90](https://user-images.githubusercontent.com/24981362/95581840-f84ad700-0a39-11eb-852e-7f41cb64c304.jpg)

**Comment by johnkslg** [comment]
Fixed, along with a number of other cases where it treated 'bad variables' as 'prevent the action entirely'. Nice find.
