### ISSUE TITLE
[0.9.1.0 beta develop-79]Civics: Adding revisions of titles into the same election multiple times

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18666]
Adding a title revision into a election, then going into the draft of the title again and adding it once more will purge links and associations as well as title holders and make a new version of it completely.

Revise title, add changes to an election creating a new election draft.
Now edit title revision then add changes to the same election
![Screenshot_87.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a88da098-d286-4d51-8564-7a40381dd0a7)

Need to prevent this, or update already existing provision if object id is already existing.

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/95640016-8da49600-0a4f-11eb-8df3-d2eace6a9159.png)
