### ISSUE TITLE
[0.9.0 develop-79] Can't start election for elected title

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18667]
Don't have any button:
![image](https://user-images.githubusercontent.com/45708377/95576335-f3395800-0a38-11eb-8208-3d5c71f54c41.png)
how should it work with the new package system?

**Comment by SlayksWood** [comment]
check this one after fixing #14132

**Comment by johnkslg** [comment]
Fixed this and other actions:
![image](https://user-images.githubusercontent.com/3536496/95639749-8cbf3480-0a4e-11eb-8fe3-0c3deefef17d.png)
