### ISSUE TITLE
Tooltip is too sensitive for nested

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18673]
![anim](https://user-images.githubusercontent.com/3536496/95636808-f5091880-0a44-11eb-8a4e-0d0a271cb3a8.gif)
It used to work as follows:
- If the tooltip has no nested properties, it disappears instantly when you un-hover whatever brought it up (and hovering in the tooltip doesnt do anything)
- If the tooltip has nested properties, its more flexible.  It wont disappear if the mouse is close to the edge of the box (so you can bridge the gap between the text and the tooltip as you go to explore the subtooltips) and theres a bit longer delay when you un-hover before it disappears

This seems to have been lost, please restore.

**Comment by IcedForge** [comment]
Seems like this issue is only pertaining specific objects, names and items, recipes etc have the same prolonged delay but certain objects in ecopedia as well as civics have this issue.

**Comment by IcedForge** [comment]
Seems resolved by another source in build 9.3 staging-1940
