### ISSUE TITLE
Disappearing map

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18674]
![image](https://user-images.githubusercontent.com/3536496/95637081-b1fb7500-0a45-11eb-8fab-153604ca338f.png)
Clicking this button makes the map totally disappear:
![image](https://user-images.githubusercontent.com/3536496/95637095-bb84dd00-0a45-11eb-8948-aa11ba81d9bc.png)
There should be buttons to make it a movable window, fullscreen, and docked.

**Comment by SlayksWood** [comment]
I suppose that the Movable map is rendered off-screen? But we have a logic: if the map go away screen, then its edge should still be visible. Can't reproduce in develop-81. 
@gzatravkin Can you take a look?

**Comment by gzatravkin** [comment]
CNR at develop or release.
There are MinimapModeBehavior line 169 which prevents such behavior
minimapUI.ClampToScreen();

@johnkslg do you remember which branch was you at moment of issue?
