### ISSUE TITLE
[0.9.0.4] not fully working specialization mining

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18672]
specialization does not fully work.
The tool does not increase the amount of life.
![изображение](https://user-images.githubusercontent.com/13696708/95631891-24dc0e80-0a8d-11eb-9879-a7ca3893b11f.png)
![изображение](https://user-images.githubusercontent.com/13696708/95631916-34f3ee00-0a8d-11eb-8241-04f5012d00ef.png)

**Comment by IcedForge** [comment]
Duplicate #12378 - Also fixed for 9.1
