### ISSUE TITLE
Make all lerps take the same amount of time

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18675]
![anim](https://user-images.githubusercontent.com/3536496/95638698-64cdd200-0a4a-11eb-898a-be35f4d08641.gif)
Blur lerp-out is faster than ui fade-out.  All lerps should have identical time, adds a lot to the polish feeling.  Check other lerps as well.

**Comment by serpopov** [comment]
+ table highlight sync
