### ISSUE TITLE
USER ISSUE: Items Lost

### ISSUE THREAD

**Issue by blueadeptmage** [StrangeLoopGames/EcoIssues#18676]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
Go to tent storage and try to put pick and hammer in personal inventory when inventory is full.

**Expected behavior:**
Item should have not been able to move into inventory and stayed put.

**Actual behavior:**
Item disappeared from campsite inventory and did not end up in personal inventory. instead it just disappeared. Empty square still thinks item is there
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5358090/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5358092/Player-prev.log)

 though

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #18340
