### ISSUE TITLE
[0.9.0.4] Upsidedown reflection on specific Asphalt Road Ramp

### ISSUE THREAD

**Issue by GauHelldragon** [StrangeLoopGames/EcoIssues#18678]
![image](https://user-images.githubusercontent.com/2829037/95640179-61d5e000-0a50-11eb-9878-ce8173a978f7.png)

The double line corner piece of an asphalt ramp has the reflection upside down.

**Comment by IcedForge** [comment]
Possibly related to #16418

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1955

To reproduce, build the ramps heading towards the East.
![Untitled.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/240641d7-4c2f-45a5-a9ec-9476d3d89d80)


Video Repro:
https://images.zenhubusercontent.com/47210472/8a3466a4-5d41-413d-9382-63b2e0888a3c/2021_03_18_07_27_trim.mp4

**Comment by keegan-o** [comment]
fixed in staging and develop branches (so should be in 9.3)
