### ISSUE TITLE
[0.9.0.4]: Some Oak trees and all Forest biomes disappeared after update

### ISSUE THREAD

**Issue by RTHauke** [StrangeLoopGames/EcoIssues#18687]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
Just updated server (on Linux) 
[eco-server-logs.tar.gz](https://github.com/StrangeLoopGames/EcoIssues/files/5359249/eco-server-logs.tar.gz)

to 0.9.0.4 via Steam from v. 0.9.0.3.

**Expected behavior:**
Biome should not have disappeared.

**Actual behavior:**
There are not any forest biomes anywhere in the world after the update.  They appear to have been replaced by grasslands.	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for your report. 
Could you try to reset the nutrient layers as lack of nutrients might cause some odd side effects now that it has been fixed.

Commands for manipulating layers
"/sim setlayer Potassium, 0.6, 0.9"
"/sim setlayer Nitrogen, 0.6, 0.9"
"/sim setlayer Phosphorus, 0.6, 0.9"

Also feel free to upload the world file as well for further investigation.

**Comment by RTHauke** [comment]
I will try the nutrient adjustment and let you know the results.  Here is a link to the current save file: https://drive.google.com/file/d/1hfkEwnKY7Rnb1ZNpv6fs_Du43xjpSUcT/view?usp=sharing

**Comment by RTHauke** [comment]
The nutrient adjustment seems to have stopped the tree and plant die-off.  Am I correct assuming that the forest biome will never return?  I'm not sure of what impact loosing it will have on the play-through.

**Comment by SlayksWood** [comment]
@RTHauke Forest biome only used in save from 0.7 version. It was replaced with other biomes in 0.8 version. Therefore, we save the forest biome only for worlds that migrated from version 0.7 to version 0.8 and now to version 0.9. So if you have a new world you will not have Forest biome, but you will have others biome, which people doesn't have in 0.7 version.
Closed for now.
