### ISSUE TITLE
[0.9.0.4] mismatch of stars of specializations

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18683]
The number of possible specializations does not correspond to the number of stars
![изображение](https://user-images.githubusercontent.com/13696708/95648334-fa1aa600-0ade-11eb-95f9-2e8c147909f3.png)

**Comment by SlayksWood** [comment]
@Astrija Thank you for the report.
As far as I know. Full stars show you how much specialties you take in current profession. But empty star shows that you can take another specialty in this profession. For example Mason Specialty:
You have Mining learned - your have 1 empty star. 
You take Mining - you have 1 full star.
You  learn masonry - you have 1 full star and 1 empty(it shows that you can take specialty in this profesion)
You learn pottery  - you still have 1 full star and 1 empty.
If you learn and take all specialties - you will have 5 full star.
@serpopov Isn't it?

**Comment by serpopov** [comment]
@SlayksWood is right, it it supposed to be like that
