### ISSUE TITLE
[0.9.0.4]Plant moisture seems to be based on rainfall only and not soil moisture

### ISSUE THREAD

**Issue by jzvandenoever** [StrangeLoopGames/EcoIssues#18686]
I first encountered this when trying to create a rice field. I tried making a place with higher moisture to suit the rice because the total soil moisture is one thing I can manipulate. However, once I started planting there I was told the moisture for the rice was too low. Despite the total soil moisture being higher. I created some space with even higher moisture levels to compensate but the moisture requirements did not change at all.
![rice suitability](https://user-images.githubusercontent.com/6650962/95654181-94d6ad00-0afe-11eb-9f10-0d04671704de.png)
What is lower in both farmed cases is the rainfall. It matches the moisture percentage differences. In the farmed cases the rainfall is 6% lower, which matches the 7% below the optimum that is reported in both farmed cases. Regardless of total soil moisture. 

I have done the same check with some wheat and it seems to be consistent there too. I have two wheat plants with the same total soil moisture but different rainfall. This is what changes the moisture suitability. (38% rainfall which is 3% above the optimum, and 39% rainfall which is 4% above the optimum. Then I sampled the 3rd spot which has the same rainfall as the second but lower soil moisture and that is still 4% above the optimum.
![wheat suitability](https://user-images.githubusercontent.com/6650962/95658366-20116c00-0b1a-11eb-9219-175d60b1dd8c.png)

So this probably affects all plants.

**Comment by johnkslg** [comment]
Soil Moisture world layer should include the rainfall layer, so that should be the one being used.

**Comment by mirasrael** [comment]
Moisture requirement for plant is now effectively Rainfall. But also we have Soil Moisture requirement as resource (like Phosphates for plants). So plants using these two types of Moisture separately.
```csharp
this.ResourceConstraints.Add(new ResourceConstraint() { LayerName = "Phosphorus", HalfSpeedConcentration =  0.1f, MaxResourceContent =  0.2f });
this.ResourceConstraints.Add(new ResourceConstraint() { LayerName = "SoilMoisture", HalfSpeedConcentration =  0.1f, MaxResourceContent =  0.05f });
```
and for Rainfall:
```csharp
this.IdealMoistureRange = new Range(0.75f, 0.95f);
this.MoistureExtremes = new Range(0.7f, 1);
```
Currently SoilMoisture already interacts with Rainfall and FreshWater layers, so it includes all these components.

We have two solutions here:
1. We can just rename Moisture to Rainfall to remove confusion.
2. We can remove SoilMoisture as resource constraint and change Moisture to use SoilMoisture instead of just Rainfall, because it then doesn't makes any sense to have them both.

**Comment by johnkslg** [comment]
Yeah the way it should work (and used to work):
soil moisture = rainfall + freshwater spread
plant layer uses soil moisture only

**Comment by mirasrael** [comment]
So option 2 then, right? We're removing Soil Moisture as resource constraint and use it instead of Rainfall in habitability calculation?

**Comment by mirasrael** [comment]
Reverted to Rainfall for now, because Soil Moisture is very unstable characteristic which isn't directly bind to biome and may cause unexpected results.
