### ISSUE TITLE
USER ISSUE: qwe

### ISSUE THREAD

**Issue by ILYA4372** [StrangeLoopGames/EcoIssues#18684]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1 q

**Expected behavior:**
cool

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by IcedForge** [comment]
Outdated and the most frequently used cracked version of late. 
Make sure you connect using a account that owns a copy of the game and try using the latest version.
