### ISSUE TITLE
[0.9.0.4] mowing problem salal

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18685]
Salal is not a food, but the plant needs to grow. Why?
https://youtu.be/atTRtfsP6AI

**Comment by SlayksWood** [comment]
All plants in eco have maturity. To get Plant fiber the plant must mature.
![image](https://user-images.githubusercontent.com/45708377/95713582-717f3f80-0c6f-11eb-9c7f-5f3ce95f0184.png)
