### ISSUE TITLE
[0.9.0.4 br-94] World Merging causes crash on loading world

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18682]
Got that error while trying to load one of my test worlds:

[Test.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5358494/Test.zip)

[log_201009102647.log](https://github.com/StrangeLoopGames/EcoIssues/files/5358493/log_201009102647.log)

Might have something to do with the world having been created in an older version of ECO and so on.

**Comment by IcedForge** [comment]
Yes, this seems to be a merger conversion issue.

[22:27:16.221] [20] [Error] [Eco] Failed to load server, Exception was Exception: InvalidCastException
Message:Unable to cast object of type 'Eco.Gameplay.Items.LimitedInventory' to type 'Eco.Gameplay.Items.BuilderInventory'.
Source:Eco.Core


[22:27:16.254] [1] [Error] [Eco] Unhandled errorSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by SlayksWood** [comment]
@ThePiachu Can you provide save file?

**Comment by mirasrael** [comment]
Issue was related to Crane inventory migration.
