### ISSUE TITLE
Meteor spawns many 'DefaultObject'

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1868]
Couldn't find mapping for object 'FieryMeteorObject'

**Comment by Nanders** [comment]
When does this happen?

**Comment by SeanAtr0n** [comment]
When the meteor destroys the world

**Comment by Nanders** [comment]
Apparently this got depreciated? Should this be removed totally or placeholder-ed?

**Comment by Nanders** [comment]
This got depreciated and will be fixed with updates to the Meteor.
