### ISSUE TITLE
World object's lacking DisplayName

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18680]
Court Object, and many others, dont have a display name:
![image](https://user-images.githubusercontent.com/3536496/95640947-3b19a880-0a54-11eb-89ea-a57629e82be4.png)

It used to use the camel case name if the 'friendly name' is not defined in the tech tree (which it isnt for any world objects), but this was changed back in May by Alex in PR https://github.com/StrangeLoopGames/Eco/pull/6055:
![image](https://user-images.githubusercontent.com/3536496/95640936-2e955000-0a54-11eb-9b66-bb01622863b1.png)

This results in MarkedUpName being empty if a world object is placed on a non-owned property, because it defaults to the friendly name, and you get this result when trying to pick something up:
![image](https://user-images.githubusercontent.com/3536496/95641029-c7c46680-0a54-11eb-88e6-c4748ad1b7f4.png)

Seems like it should be reverted to use camel case name in this case? Unless you had something else in mind:

**Comment by mirasrael** [comment]
It used this post processor to set FriendlyName to all objects which doesn't have it: `\Server\TechTreeTemplates\_EnsureFriendlyNamePostProcessing.cs`. So all generated objects should always have DisplayName.

**Comment by mirasrael** [comment]
Actually I have it:
![image](https://user-images.githubusercontent.com/475445/95852210-0e1f0b80-0d5c-11eb-98b4-60d251266412.png)

**Comment by WeaselDog** [comment]
Seems it is resolved now.
