### ISSUE TITLE
USER ISSUE: Persistent motor tool sound

### ISSUE THREAD

**Issue by hitzu111** [StrangeLoopGames/EcoIssues#18688]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
Scroll fast through tools with one of them being ~~a chainsaw or~~ a modern rock drill. The sound of the motor appears and remains being played on that place and doesn't disappear even after a relog. Other players do not hear it. Server restart fixes the problem.

**Expected behavior:**
The sound should disappear.

**Actual behavior:**
The sound remains on that place.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes. The tools are vanilla ones. Have not tested without mods.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5359427/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5359428/Player-prev.log)

**Comment by SlayksWood** [comment]
I reproduced it, but I have glitch always with modern rock drill. Chainsaw sound never remains. My toolbar:
![image](https://user-images.githubusercontent.com/45708377/95715117-fb300c80-0c71-11eb-891c-78067f7f03dc.png)

**Comment by hitzu111** [comment]
I confirm, it is only a rock drill and never a chainsaw. I was confused because they were close together. Sorry for misleading.

**Comment by Quadbro** [comment]
Rechecked issue, it was fixed it my latest tool sound update. So it's not reproducible anymore.
