### ISSUE TITLE
USER ISSUE: Chat filter

### ISSUE THREAD

**Issue by LucanderP** [StrangeLoopGames/EcoIssues#18699]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
1. Press C
2. Click on the filter
3. Resize the window

**Expected behavior:**
It should filter out every thing that i filter out.

**Actual behavior:**
It shows everything

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@LucanderP Thank you for the report.
Can your a little clarify your problem? I don't exactly understand what you means. Maybe some screenshots.
Also provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and PC specification (include operation system).

**Comment by IcedForge** [comment]
Will close this in lack of a reply. Please reopen if you still experience this issue and also please include some screenshots of what the issue was as i couldn't really understand this.
