### ISSUE TITLE
[0.9.0.4] ModKit - Sprite not rendered in chat for Tags

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#18698]
Hello Guys !
The 0.9.0.4 fixes the <sprite ... bug for modded icons in text.
However, there's still a bug for TAG icons.

See screenshot here:
https://images-ext-2.discordapp.net/external/p3-Xp1msTLduEaBq1l_hX35CjL0OpxmUBJgLQmbU_8U/https/steamuserimages-a.akamaihd.net/ugc/1667979695693184182/00950F60530BB999715D22F03B5EFC139B756590/?width=1204&height=677

To reproduce, here's my mod link:
https://forum.play.eco/filebase/download/785/

**Comment by serpopov** [comment]
https://user-images.githubusercontent.com/4238643/98584450-7a0f7800-22f8-11eb-856e-26a16db9b54f.png
