### ISSUE TITLE
USER ISSUE: broken Pickaxe sound

### ISSUE THREAD

**Issue by Narviath** [StrangeLoopGames/EcoIssues#18695]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
I heard a different sound for tools when they are break.
But there isn't for pickaxe	

**Expected behavior:**
different sound for broken pickaxe like other tools

**Actual behavior:**
same sound for pickaxe and broken pickaxe

**Comment by SlayksWood** [comment]
@Narviath Thank you for the report. What pickaxe do you use? I have broken sound for all pickaxes. Can't reproduce. Can you provide video or something else?

**Comment by Narviath** [comment]
It was a stone pickaxe.
When I play today I didn't reproduce the bug so I will close this issue.
Sorry
