### ISSUE TITLE
USER ISSUE: Game Freeze

### ISSUE THREAD

**Issue by Aeridhredhir** [StrangeLoopGames/EcoIssues#18694]
\
**Version:** 0.9.0.4 beta release-94

Hello, I started Eco a few weeks again but sadly i am unable to enjoy my time in it.
I am unsure why but my game freezes every 2-15 minutes and the following happens:
1. the game freezes
2. a small Unity Crash helper window pops up with some kind of loading bar in it but no Error text/number or any clue what happened
3. Both, the unity crash helper and the eco window itself are closing
4. I start the game again connect to server play a few minutes 1. happens again you all get what im saying :(

I have no clue why it happens nor do i know how to fix it. 
I really hope someone could help me with this since i love eco and would like to play it without that hurdle.

Sincerely
Me
**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes 2 but other Players on the Server dont seem to have problems

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5361645/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5361646/Player.log)
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5361756/Crashes.zip)

**Comment by SlayksWood** [comment]
@Aeridhredhir Thank your for the report.
1. Please provide your PC specification (include Operating System).
2. Did you update drivers to the latest version?

**Comment by Aeridhredhir** [comment]
Operating System
	Windows 10 Home 64-bit
CPU
	Intel Xeon E3 1230 v3 @ 3.30GHz	
	Haswell-WS 22nm Technology
RAM
	16,0GB Single-Channel DDR3 @ 799MHz (9-9-9-24)
Motherboard
	ASRock Z87 Extreme3 (CPUSocket)	
Graphics
	BenQ EW2775ZH (1920x1080@60Hz)
	BenQ EW2775ZHý (1920x1080@59Hz)
	3072MB ATI AMD Radeon R9 200 Series (C.P. Technology)	
Storage
	465GB Samsung SSD 840 EVO 500GB (SATA (SSD))	
Optical Drives
	ASUS DRW-24F1ST a
Audio
	AMD High Definition Audio Device

**Comment by mirasrael** [comment]
Hi @Aeridhredhir 
From crash report and error log it seems like there some issues with DirectX or drivers. You can try to experiment with drivers (rollback to older version) or try to update/reinstall DirectX. If you have an opportunity to test with another GPU (i.e. get it from friend and replace your own) it also may help with troubleshooting.

**Comment by IcedForge** [comment]
There were some changes and fixes applied in 9.1 that worked towards helping in optimizations.
If you still experience this issue please reply and we can keep investigating this otherwise i will close this issue in a few days if there still has not been any reply from @Aeridhredhir

**Comment by IcedForge** [comment]
Will close this as there was never a reply, feel free to open this again if the issue persists.
