### ISSUE TITLE
Possibility to see another district map durin drawing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18705]
#18538

**Comment by IcedForge** [comment]
I cannot select "Viewing map" and another district at the same time, one will disable the other
Also this viewing map checkbox i think is unnecessary with the ability to select the draft districts in the right column.

![Screenshot_63.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a0561a8d-248a-4239-b703-b0d425c82ac5)

**Comment by gzatravkin** [comment]
It always was work in this way: to show another one. Shouldn't be high priority and re open if it's just this (we already have issue to make multiselection).

This checkbox is to be able switch between editing and another map.

**Comment by IcedForge** [comment]
The idea is to be able to select a layer and use that as a reference point as you are drawing a new district.
For example i have a different road map, now i want to see this road district while i am making a new zoning so i dont need to constantly switch between active and editing mode as this is extremely frustrating for a lot of players that play on servers with  a lot of district usage.

Previously you could hold ctrl and display other maps ( properties etc ) this is no longer possible.

**Comment by gzatravkin** [comment]
You still don't need to switch between editing and active mode, you can just toggle it without closing editing mode

**Comment by SlayksWood** [comment]
A simple example (in a game you usually don't need to do this), but you often connect areas on different maps:
- create district map 1 like:
![image](https://user-images.githubusercontent.com/45708377/99526655-996b6c80-29ac-11eb-9baf-7848ffd26a2a.png)
- create another district map 2 and fill only empty plots inside this "circle'
Switching the mouse will have to spend more time, much more time. Therefore, I agree that this is a regression

**Comment by gzatravkin** [comment]
Ok, https://github.com/StrangeLoopGames/Eco/pull/7180/ - here added the possibility to switch between two last selections by pressing control.
