### ISSUE TITLE
[0.9.1 develop-81] Elevator call post lost some texture

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18707]
On active button:
![image](https://user-images.githubusercontent.com/45708377/95738728-5d006e80-0c92-11eb-941d-0dcaa9c2768e.png)

![image](https://user-images.githubusercontent.com/45708377/95738772-6f7aa800-0c92-11eb-93fa-242ff3870aa8.png)
![image](https://user-images.githubusercontent.com/45708377/95738779-730e2f00-0c92-11eb-81da-4dba3c573a9b.png)

**Comment by keegan-o** [comment]
I did some surgery and hacked out the actual control panel from the elevator so the call box aren't these weird buttons attached to nothing.
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/3d41dad9-7181-45f5-bf51-0f1bb6046834)

**Comment by IcedForge** [comment]
Looks great, slight issue with the item box as when trying to deconstruct it will only detect on the buttons, so you cannot deconstruct it by hitting anywhere other then buttons that are not pressed down.

![Screenshot_26.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/7fa0faad-847d-48e0-8c6e-58fa7077c5bc)

**Comment by IcedForge** [comment]
Making a new issue for the clearance specific
