### ISSUE TITLE
USER ISSUE: After Biom Die, nothing more

### ISSUE THREAD

**Issue by Mark-3503** [StrangeLoopGames/EcoIssues#18701]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
after the well-known bug biome die, there is no recovery.
the 2 jungle and the 2 desert biomes do not recover, only trees grow, no mushrooms, ferns or other plants come back

**Expected behavior:**
Plants spore grows

**Actual behavior:**
nothing the Bioms are dead,

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Mark-3503 Thank you for the report
What do you mean by 'biome die'? please, provide someadditional information (maybe some screenshots), you can also provide save file, Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Mark-3503** [comment]
Sorry my english ist not Perfect.
From Patch 9.0.3. to 9.0.4 was plant Mass extinction in deserts and jungles .

Every plant, grass, mushroom in the jungle was away overnight, and same in the desert.
Only trees (and those similar to wood) have remained

**Comment by SlayksWood** [comment]
@Mark-3503 Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save, if you still have this problem.
But first try to use this 3 admin commands ( If you are not server owner, you can ask an admin on the server to use these 3 commands).
"/sim setlayer Potassium, 0.6, 0.9"
"/sim setlayer Nitrogen, 0.6, 0.9"
"/sim setlayer Phosphorus, 0.6, 0.9"

We have fixed a bug with nutrients and this situation is possible on some servers.

**Comment by IcedForge** [comment]
Due to lack of response i will close this issue. Please reopen if you still have this issue after using the commands SlayksWood wrote down.
