### ISSUE TITLE
[0.9.1 develop-82] 2xOkBox when start election for elected title

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18709]
Step to reproduce:
- press start election:
![image](https://user-images.githubusercontent.com/45708377/95745777-5677f400-0c9e-11eb-8107-eee59c0cc33d.png)
- I have first OkBox:
![image](https://user-images.githubusercontent.com/45708377/95745798-60015c00-0c9e-11eb-938d-1a90e754ef19.png)
- press Ok, I have second OkBox:
![image](https://user-images.githubusercontent.com/45708377/95745828-6f80a500-0c9e-11eb-9480-8dea85da6473.png)
Is it possible to simplify? and use only one or maybe just in chat?

**Comment by johnkslg** [comment]
Can remove that first box.

**Comment by abaza121** [comment]
This only happens with the ballot box (or any component that starts an election by itself ie. without from the notifications panel
