### ISSUE TITLE
[0.9.1.0 beta develop-82]Render limit for ballot box is too short

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18710]
setting level of detail to <22% makes the ballot box only have 6 tiles of render range, which is not consistent with other placed objects.

**Comment by ptitducanh** [comment]
LOD setting of Ballot Box was different than other objects. It was culled at 3% while others are culled at 2%. 
So I updated the LOD Group setting of Ballot Box.
