### ISSUE TITLE
Easy vehicle duping

### ISSUE THREAD

**Issue by Guedez** [StrangeLoopGames/EcoIssues#18713]
Have vehicle on inventory and wait for the server to start lagging. Might work even on non lagging servers, but it's trivial if the server is lagging.
1 Place the vehicle on the ground.
2 As soon as the vehicle spawns in the world, esc -> disconnect. You need to do this before the item leaves your inventory, which is why the server lagging helps.
3 As you go back in the world, place the Vehicle on the ground again.
4 Repeat until you finish making all Mechanics and Industry users sad forever. Works with all vehicles, carts, trucks, skid steers, anything.

**Comment by SlayksWood** [comment]
The problem is definitely there, I heard from people. I can't reproduce it in any way (and I think I can't make it). Usually happens with servers that are online for a long time without rebooting (about 2 days) and with a lot of online. But I couldn't get the logs(

**Comment by mirasrael** [comment]
Seems like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/17727 which already fixed.

**Comment by Guedez** [comment]
This bug was reported the day it was reproduced on a up to date server

**Comment by mirasrael** [comment]
Fix in 9.1 version which isn't yet released.
