### ISSUE TITLE
Having the person yell "TIMBER!" every single time a tree is chopped down is annoying

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoIssues#18712]
It's really an annoyance, especially for those who want to be a lumberjack! The audio recording quality isn't great either which further takes away from enjoyment.

I would like to suggest removing it entirely or make it a small % chance to happen, such as 1-5%. 

Alternatively, allow the player to optionally turn it off - best of both worlds.

Edit: Typo "auto" --> "audio"

**Comment by Sarah-Graesyn** [comment]
I tend to agree with @D3nnis3n and @johnkslg on making it a chance for it triggering, perhaps even making it just a chance of triggering if you are within "x" distance of a players claim

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop 175.

Frequency: TIMMMBBEERR!!!! audio triggers after cutting the 4th tree after the first trigger of the audio.

Recommendation:
1. 100% trigger during the tutorial. Player's first time cutting a tree.
2. Trigger audio after cutting a tree when there's an avatar within a given radius area of the player cutting the tree. Trigger once only.
3. Set condition trigger audio to timer cooldown. Once every 30 minutes, I guess? 

Issue: The audio is still annoying for a player. The current frequency or chance to trigger audio is still high.


Feedback: It's no fun to keep hearing the same TIMBER over and over again but it kills the essence of cutting if audio is removed or the chance is too low to trigger. It gives ECO a character as a game.

https://images.zenhubusercontent.com/47210472/c42c6d0f-25e2-4d00-b8e6-6fb7dab532a1/2021_02_04_05_23.mp4

**Comment by TwixterZ** [comment]
Fix Tested as of 9.4 Staging 2020

Chopped down 30 trees, avatar only shout "TIMBERRR" once within 5 minutes, when alone

Avatar did not shout "TIMBERRR" despite another player standing in front of the tree being chopped (within 1 square from tree)
