### ISSUE TITLE
My own server doesnt recognize me anymore and wants me to create a new char!

### ISSUE THREAD

**Issue by Sheetso** [StrangeLoopGames/EcoIssues#18717]
Since the last 9.0.4 update, my dedicated server is recognizing me as a 2nd new player. I dont know what I should do. tried to restart the server 10 times, restarted my pc, the game and everything and it always wants me to create a new char with the username "sheetso2" while my original was "sheetso". In mainmenu on the right bottom site it says i´m logged in as "sheetso"which would be the right one. Please help. 
Here is the uploaded save file from the server: https://drive.google.com/file/d/16m3iqW6L0QxzbERx_hnECnVb-Lc_I_C7/view?usp=sharing
Thanks

**Comment by mirasrael** [comment]
@Sheetso Do you have the backup before new user was created?

**Comment by Sheetso** [comment]
Sure! I had 19 Backups. I tried the last 6 but they all lead me to create a new player.

**Comment by mirasrael** [comment]
I checked the save and it says you have different Steam ID for Sheetso and Sheetso#2 users. This ID should never change though. 
I checked both urls:
https://steamcommunity.com/profiles/76561197974077341/ - for new ID
and 
https://steamcommunity.com/profiles/76561198668141828/ - for old ID, it says unable to load account data (which may happen when family sharing is active).

So it seems something related to Steam account actions (i.e. if you used two different Steam accounts for the game or something like this). Can you add any information related to your Steam account actions during Eco usage which may help to troubleshoot this issue?

**Comment by Sheetso** [comment]
Hmmm.... This is rly strange since i have no family sharing activ and also haven't changed anything in steam. played it with two friends the last couple of days without any problems. Then the update 9.0.4 was coming and since then its forcing me to create a new character. I really dont know and can't imagine whats going on.

**Comment by mirasrael** [comment]
I guess I can fix the save file (remove new user and change ID for old user), but if we won't know the reason we can't fix this issue and guarantee it won't appear again.

**Comment by mirasrael** [comment]
So if you have any ideas what may be related it will be very helpful.

**Comment by Sheetso** [comment]
Thanks. Would appreciate your help by changing the ID but I really can't figure out what happend or what could cause this. Hopefully it won't appear again. If it will, I will take notes what has changed and will come back to you!

**Comment by mirasrael** [comment]
@Sheetso can you contact me in Discord mirasrael#5137 ?

**Comment by Sheetso** [comment]
Everything works fine now. Thank you really much for your help!
