### ISSUE TITLE
USER ISSUE: Law bug - Custom stat record count for 'items moved' not working correctly?

### ISSUE THREAD

**Issue by owenowen101** [StrangeLoopGames/EcoIssues#18718]
![ba8cd1985953c1439bdb4610b42a1ecf](https://user-images.githubusercontent.com/4236816/95772885-5afbd700-0cb5-11eb-93b4-5377fa817d5e.jpg)
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
1. Draft law
2. Trigger = 'on inventory action' (any item(s) will do)
3. If = 'take'
4. Then = 'record custom stat', person = 'citizen', count = 'items moved'.

**Expected behavior:**
Count added to the custom stat should be equal to the number of items picked up.

**Actual behavior:**
A count of 1 is instead added, regardless of the number of items picked up. The same occurs if 'change in item count' is used instead of 'items moved'.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Local vanilla server, latest version.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5366440/Player.log)

**Comment by IcedForge** [comment]
Thank you for reporting.
It was using another method incorrectly but is fixed for 9.1
