### ISSUE TITLE
Mod Files Bigger then 30MB won't download,

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#18716]
If the Mod asset files are bigger then 30MegaBytes they don't seem to download, even on local servers, is this intentional?

This only happens if a single file is bigger then 30mb not a total overall ( i have 150mb worth of asset files in my servers and they download fine) 

I can supply files for testing if needed

What I think happens:
It takes to long for it to collect information on the size then just skips if it hits a certain timer

**Comment by redwyre** [comment]
@mirasrael Looks like this is probably an RPC problem/limitation?
```cs
public void SendContentFiles(List<string> requestList, INetClient targetClient)
{
    foreach (var request in requestList)
        targetClient.RPC("LoadContent", request, File.ReadAllBytes(this.contentFileNameMap[request]));
}
```

**Comment by mirasrael** [comment]
@redwyre it may be an issue with max number of segments for one UDP packet. I didn't heard about such limitation, but we need to check for this. In this case we can just split content into multiple parts.

**Comment by stavlor** [comment]
Is there a possible chance of us getting a solution for this with the 9,2 release?

**Comment by redwyre** [comment]
Doesn't look like it, but if lots of mods are hitting this issue we could increase priority for 9.3

**Comment by TheKye** [comment]
all mods over 30MB hit this issue, we have to break the mods down into smaller components to work

**Comment by stavlor** [comment]
Yeah, as a server owner i generally have to publish my mods as a zip to get around the issue and give folks instructions on how to install.

**Comment by Ry4ndrew** [comment]
Hey @TheKye, I am currently retesting this to confirm the fix. Can you provide the mod files for testing?
Thanks.

**Comment by TheKye** [comment]
> Hey @TheKye, I am currently retesting this to confirm the fix. Can you provide the mod files for testing?
> Thanks.

Hi Sorry! I missed the notification for this, I have tried this on 9.4.0 Staging-2085 and i have a file here that is in fact 43MB in size, and it had failed to download, here is the file and all associated files for testing:

For Testing: 
Items provided in this file:
Black Reinforced Concrete
Blue Reinforced Concrete
Brown Reinforced Concrete
Green Reinforced Concrete
Grey Reinforced Concrete
Orange Reinforced Concrete
Pink Reinforced Concrete
Purple Reinforced Concrete
Red Reinforced Concrete
Yellow Reinforced Concrete
White Reinforced Concrete

https://mega.nz/file/TL4ymLiD
Encryption Key: u16xFm2dzJ-MChWCPahCBoF2Y-dqDDo2TyQesd5UTMM
