### ISSUE TITLE
USER ISSUE: No Meteor at all

### ISSUE THREAD

**Issue by Virkiato** [StrangeLoopGames/EcoIssues#18722]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
Meteor is not visible in the sky since day 2. We finally had lasers and it is 6 days of plenty game without seeing meteor at all. It disapeared.

**Expected behavior:**
Meteore should have run around the world and tell us how many days are up before it collapses

**Actual behavior:**
There is no meteor at all since day 2. Our lasers don't find any meteor in the sky. The computer does sound when the 4 lasers are connected. The Lasers head stay down but we have the luminal effects. We even made a tower of 250m of height : no Meteor at all.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
We don't use any mod. Normal game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5367503/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5367504/Player.log)

**Comment by SlayksWood** [comment]
@Virkiato Thank you for the report. 
1. Did you see meteor at first day?
2. Can you provide save file? Instruction is here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
3. Let admin will try to use command /meteor spawn

**Comment by Virkiato** [comment]
@SlayksWood Thank you for the help.

1. Yes, as I said, the meteor was visible during first days of game then disapeared
2. No need now
3. I used the command /meteor spawn and it worked. The meteor is here again with the good remaining time.

Thanks you for the support

**Comment by SlayksWood** [comment]
I have never encountered similar problems. Closed for now.
