### ISSUE TITLE
update url bar with each eco tree click

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18724]
When a user clicks on a section of the eco tree, uprate the browser's url bar with the url for that section.

For example:
https://play.eco/updates/professions/tailor/09-14-2020
when user clicks on 'professions', the url becomes https://play.eco/updates/professions/
Then if they click 'tailor', the url becomes https://play.eco/updates/professions/tailor/

**Comment by denysaw** [comment]
Done. Could be tested on staging.
