### ISSUE TITLE
ECO CANT BUILD ANYTHING

### ISSUE THREAD

**Issue by RED7201** [StrangeLoopGames/EcoIssues#18720]
https://www.youtube.com/watch?v=0E2BsUBRL44&ab_channel=REDSTEEL

**Comment by IcedForge** [comment]
@RED7201 Thank you for reporting. In your server settings do you have crafting timer and crafting multiplier at 0 values?
You can find this Difficulty.eco file in Eco\Eco_Data\Server\Configs, you can open it with notepad and check, or check via the server gui by writing /servergui if you are playing on a single player world.

**Comment by SlayksWood** [comment]
Here:
![image](https://user-images.githubusercontent.com/45708377/95827326-4282cf80-0d3c-11eb-861b-3dd3be9ad498.png)
or here:
![image](https://user-images.githubusercontent.com/45708377/95827445-6e05ba00-0d3c-11eb-92c7-a21a18fd1d8f.png)
merged to #18640
Reopen please if you still have any problem.
