### ISSUE TITLE
USER ISSUE: Plants in the Rainforest died out

### ISSUE THREAD

**Issue by DarkLiKally** [StrangeLoopGames/EcoIssues#18735]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. We played about 10 Days now
2. Since a few days all plants in the rainforest except the trees and the bushed with red flowers are remaining
3. Our eco system is not affected that much, we have no pollution at all, only a level 1 pollution of the ground because of tailings until we move them underground. But that area is faaaaar away from all rain forests	
4. The rest of the world is fine

**Expected behavior:**
Plants won't die out in the rainforest.

**Actual behavior:**
Plants in the rainforest die out

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #18757
