### ISSUE TITLE
9.0.4 Skid steer able to interact with stockpiles under itself even through 5+blocks

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18731]
I have stone road above stockpiles (touching the top of them) and it seems that the skid steer can interact with them?

It is as if the interact ability is passing through the 1 block of stone road, not sure if this is intentional or not

![image](https://user-images.githubusercontent.com/61889138/95834652-23cd0a80-0d35-11eb-9ea3-8e2c692d8720.png)

**Comment by SlayksWood** [comment]
we have this problem:
![image](https://user-images.githubusercontent.com/45708377/95990348-0df23f00-0e34-11eb-8457-e521eab3dbb1.png)
But if youi change person view it will fixed.

**Comment by MishkaFur** [comment]
Update, appears to do the same through several layers of sandstone too so makes it difficult to store tailings under the surface if any skid work is happening above them

**Comment by MishkaFur** [comment]
![image](https://user-images.githubusercontent.com/61889138/97869299-25bd3480-1d09-11eb-99af-f37ee057e493.png)


![image](https://user-images.githubusercontent.com/61889138/97869313-2bb31580-1d09-11eb-805c-d3bddc973651.png)

10 block difference in height but skid is able to interact

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6 release
