### ISSUE TITLE
Implement "White Hat" and "Bug" Icon

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18736]
- [x] @MilenkoTunjic We need you to provide the images for Jeff.
- [x] @j3fffff We need you to do the implementation on the web side.
- [x] @D3nnis3n Pass emails or username of users and their icon to @j3fffff 
- [x] @j3fffff Add icon to user's db.
- [x] @gzatravkin I guess we need you to implement it in the game, not sure?

Please feel free to reassign people as you see fit.

**Comment by WeaselDog** [comment]
Let's make it into an Epic and split up the parts for each person.

**Comment by D3nnis3n** [comment]
Not sure thats really required, this is a minor task.

**Comment by WeaselDog** [comment]
Assignees from 3 different teams, not clear what is supposed to happen with code.

**Comment by j3fffff** [comment]
So I hear we are wanting to give every player that writes a bug on github, the bug icon.

dont see any easy way to get a list of those people on githb. is there one? or maybe an api option.
Even if we get a list, we probably don't want to manually update that. Might be able to automate it, seems like a bit of work for a small feature.

Or we could just have it be an on request feature. and let the community know.

what you think?

**Comment by j3fffff** [comment]
oh and @gzatravkin can you setup the game to display the white hat and bug icon if auth returns:
selected_icon = whitehaticon or bugicon

**Comment by johnkslg** [comment]
@gzatravkin Make the system find the right icon without having to add code, should just find by string.

Also invent a way to easily tell what account to give these to. In the report-bug dialog, make it implant the slg or steam user id.  Update the template in EcoIssues also to implant this.

Make it input into the bug in a standard way, and next step we can make an auto-process that checks for fixed bugs and auto gives them the icon

**Comment by SlayksWood** [comment]
don't have user id if I log from steam:
![image](https://user-images.githubusercontent.com/45708377/99046074-4c019080-25a3-11eb-829d-e3790f1a956b.png)

**Comment by j3fffff** [comment]
if no user id, should use steam id

**Comment by SlayksWood** [comment]
at least it should provide slg ID if my slg account link with steam, but I connect to game from steam.

**Comment by j3fffff** [comment]
@SlayksWood where is slgid not being passed? where did you get the error message?

**Comment by SlayksWood** [comment]
When player report a bug and start game from steam.
Start game and authorize in game:
![image](https://user-images.githubusercontent.com/45708377/102353467-24df1a00-3fba-11eb-93e6-0f7527445913.png)
Start game in Steam:
![image](https://user-images.githubusercontent.com/45708377/102354164-3c6ad280-3fbb-11eb-9b74-67602362fc19.png)

**Comment by j3fffff** [comment]
so the bug reporting system, auto send bug reports to github with a userid.
and steam only users are missing their steamid? 
sounds like in-game code is doing this? or bug reports code. @redwyre

**Comment by redwyre** [comment]
This is a game-side issue
@gzatravkin if the user_id is not set, try steam_id:
`	**User Id: ({(NetworkManager.obj?.Session?.user_id ?? "Not logged user")})**`

**Comment by SlayksWood** [comment]
I close this one and create another with "not logged user"
