### ISSUE TITLE
USER ISSUE: farm always overcrowded

### ISSUE THREAD

**Issue by Springy150** [StrangeLoopGames/EcoIssues#18738]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
farm corn/sun flower spaced out 3x3 still overcrowded

**Expected behavior:**
lose overcrowded

**Actual behavior:**
overcrowded

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Springy150 Thank you for the reprort.
Can you provide save file? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
And coordinates if problem in one place.

**Comment by Springy150** [comment]
@SlayksWood yes ill will pop in on my google drive and will send you a DM with link

**Comment by SlayksWood** [comment]
@Springy150 Sorry missed your message, you can send it to kirill@strangeloopgames.com or in Discord Kirill (Slayks)#6251

**Comment by SlayksWood** [comment]
There were improvements with plants in 9.1. Closed for now. If you still have problem please reopen.
