### ISSUE TITLE
In cw dashboard, world map image is getting cert error

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18746]
cw world map image is getting a cert error.
The map image is only http, and cw dashboard on our website is https.
So i think there is error trying to call insecure asset in https. 
gives error: worlds:353 GET https://eco-testing-server.eco.hw.sfo2.do-slg.com/Layers/WorldPreview.gif net::ERR_CERT_AUTHORITY_INVALID

But we need that insecure image..

this is in chrome. ff is supposed to be working

**Comment by denysaw** [comment]
Done on dev/staging and hotfixed on Prod. Please, test.
