### ISSUE TITLE
[client] [9.0-9.0.5] server search filter by Lang bug

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#18742]
Client on EN server search filter have checkbox on Lang  by default, but  on all other  Lang it checkbox off by default

![en](https://user-images.githubusercontent.com/26339332/95910723-2a956500-0da9-11eb-95c1-d7df8086147e.png)
![de](https://user-images.githubusercontent.com/26339332/95910721-29fcce80-0da9-11eb-8059-cfc4bed556ad.png)
![ru](https://user-images.githubusercontent.com/26339332/95910728-2bc69200-0da9-11eb-8e17-3c919a964858.png)
![fr](https://user-images.githubusercontent.com/26339332/95910725-2b2dfb80-0da9-11eb-9cef-22714f3578b7.png)
![it](https://user-images.githubusercontent.com/26339332/95910727-2b2dfb80-0da9-11eb-938c-c78910544fa8.png)

**Comment by mirasrael** [comment]
It is intended behavior, because much more English servers than other servers and user may end up with only few servers or no servers available with language filter.

**Comment by StallEF** [comment]
I understand that it may turn out that there are no active servers in the client's language and so that the game does not seem dead, they see everything, but on EN 80% of all servers and EN the client sees only 80%, for example, RU client shows 100% of the forced player search among 100% of the same 5% RU servers, since 90% of players do not know about the existence of a filter in the game.

**Suggestion:** make settings more visually obvious
I see the solution to both problems in the only option - this is the removal of search parameters into the search itself.
![add](https://user-images.githubusercontent.com/26339332/95942424-bf20b700-0deb-11eb-9a6f-0a68d66c798f.png)

**Comment by mirasrael** [comment]
I guess we can add an option and implement logic to put same language servers on top of suggestions list. What do you think @StallEF ?

**Comment by StallEF** [comment]
yes thanks, this will be a good option until another concept of how search works in the game is suggested

**Comment by mirasrael** [comment]
@beastyn need to implement last suggestion. New option which will put same language servers on top of the list, which should be enabled by default.

**Comment by johnkslg** [comment]
You can make the match score give bonus points for same language.
