### ISSUE TITLE
Drop down notifications polish

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18751]
![animx22](https://user-images.githubusercontent.com/3536496/95926409-16357600-0d71-11eb-983f-5831f45e79de.gif)
- [x] Transitions are awkward for pulling/raising this bar:
- When you pull it down, it does a little jerk at the start.  It should be doing the lerp out_back, so that it overpulls and then clicks into place (think opening a pull-down window shade)
- When you pull it up, it should do in_back, so the over-pull happens first, then it rolls up.  
- Also noticed that the rollup goes all the way to the top. It should go back to where it was when I pulled it down.  

![image](https://user-images.githubusercontent.com/3536496/95926310-ceaeea00-0d70-11eb-8a50-9e91b4b9637e.png)
- [x] Setting the expanded height to full should bring it much further down, almost touching the toolbar.  It should default to this max level. Make sure the settings panel doesnt go off the edge when you do this. 
- [x] Closing the cursor (pressing escape or clicking the landscape) while this panel is expanded should bring it back to its regular unexpanded size.
- [x] Clicking in the blank background of this notification window should expand it or collapse it

**Comment by IcedForge** [comment]
Expanded full height is still only half way at max, request was full lenght, almost down to toolbar itself which is nice if you want to check further back in it without opening chat.

Esc opens escape menu regardless if log is interacted with or not which i think should stay that way as it is how all our other menus works you can left click outside it to have the proper effect though and it seems and feels seamless and nice.

![Screenshot_34.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2903c7a8-6012-4766-a96e-ec36db9d96ec)

**Comment by gzatravkin** [comment]
From John:
I was wrong about the lerp on the notification panel, you can remove it and make it quad out

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 250
