### ISSUE TITLE
[0.9.1 develop-84] Window of object with Bed Component doesn't close by ESC

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18756]
I first encountered this with Wooden Straw Bed. I encountered this today with Wooden Fabric Bed. I decided to check on the last item that contains Bed Component - Campsite. And here is also a glitch. Of course I could be wrong, but I guess this is due to Bed Component.
Step to reproduce:
- open Campsite/Wooden Straw Bed/ Wooden Fabric Bed.
- press ESC, you can move camera with UI:
![image](https://user-images.githubusercontent.com/45708377/95957549-86dba180-0e08-11eb-932d-0e37cd259d52.png)

**Comment by SlayksWood** [comment]
Checked on develop-110, still an issue.

**Comment by JestinJae** [comment]
Just wanted to note that this seems to have been fixed in 0.9.2.4, at least with the campsite.
