### ISSUE TITLE
Food Recipe "Pineapple Fried Rice" appears as "Pineapple Friend Rice" in game

### ISSUE THREAD

**Issue by Chillbillyy** [StrangeLoopGames/EcoIssues#18758]
https://cdn.discordapp.com/attachments/764313352222277642/765883487843778570/unknown.png

**Comment by SlayksWood** [comment]
Easteregg:
![image](https://user-images.githubusercontent.com/45708377/95978279-9e278880-0e22-11eb-83c3-2695bfd99cfc.png)
