### ISSUE TITLE
Give option to not sprint while using automove

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18755]
When using the autorun, it is usually used to travel long distances. For balance reasons, when you sprint you lose calories and end up moving very slow. As a result, long distance travel using the autorun button can take longer than if you just walked.

We just need to remove the part that sprints and the command works great.

**Comment by beastyn** [comment]
As I remember someone has asked me to make sprint by default and switch it off with Shift.
But if you say so, no problem )

**Comment by mirasrael** [comment]
It actually may be smart and auto-run if you are run and auto-walk if you're walk when press the key.

**Comment by WeaselDog** [comment]
Yes, please remove the sprint for now. We can discuss having a way to implementing sprinting, but for now the feature does not work how it should.

**Comment by beastyn** [comment]
Should work as:
Auto-moving is walking by default.
Press shift - run.
Press shift - walk.
No holding.

**Comment by SlayksWood** [comment]
Have a problem to switch on run mode. Sometimes it works, but in many times I need to hold button to 2-3 sec.
