### ISSUE TITLE
USER ISSUE: Walls don't connect to full blocks

### ISSUE THREAD

**Issue by hitzu111** [StrangeLoopGames/EcoIssues#18759]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
Place a wall next to a floor made of full blocks.

**Expected behavior:**
Walls should connect to the floor and fill the gaps. This was an issue since forever and it became worse with the introduction of new materials such as composite lumber. For example, clad walls look so nice and pristine from the outside that it's just a shame to replace them. I feel almost physical pain from both solutions: leaving a gap or making an outside wall look bad.

**Actual behavior:**
They don't fill the gaps.

### Expected:

![Screenshot_136](https://user-images.githubusercontent.com/50346354/95982965-899abe80-0e29-11eb-8764-b2025acc7405.png)
**AND**
![Screenshot_134](https://user-images.githubusercontent.com/50346354/95982972-8b648200-0e29-11eb-9bb5-5c54f19c3961.png)

### Actual:

![Screenshot_137](https://user-images.githubusercontent.com/50346354/95982961-89022800-0e29-11eb-8231-e68c3f76d380.png)
**OR**
![Screenshot_135](https://user-images.githubusercontent.com/50346354/95982968-8acbeb80-0e29-11eb-947d-cd1ed0ca6a39.png)

**Comment by SlayksWood** [comment]
merged to #4601
