### ISSUE TITLE
[0.9.1 develop-84] Hiding interface glitch by ESC if text input is active

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18754]
Step to reproduce:
- open any object window:
![image](https://user-images.githubusercontent.com/45708377/95954199-99071100-0e03-11eb-9b8c-6ef722145aa3.png)
- start to rename it:
![image](https://user-images.githubusercontent.com/45708377/95954238-a58b6980-0e03-11eb-8acc-ebd804797ebe.png)
- press ESC. It should only stop to change text field, but it will also open ESC Menu:
![image](https://user-images.githubusercontent.com/45708377/95954285-bb009380-0e03-11eb-88f5-d783cb7214bc.png)
So it can happen with text component, description or with any text input field.

**Comment by gzatravkin** [comment]
This issue happens due to changes in popups (in UIManager it was changed from UIInput to Input for escape). 
Make sure that after fix of this issue you still will be able to close popups with text to enter by escape (not just cancel editing).

**Comment by johnkslg** [comment]
Make sure to fix this through the escape system, not through special cases

**Comment by SlayksWood** [comment]
I can't cancel renaming now. When you press ESC maybe cancel all changes and return old name. This works the same in others UI (renaming save file)

**Comment by gabrielgindridev** [comment]
Issue fixed in staging. Just wait for staging to dev merge
