### ISSUE TITLE
Fix crops vs wood tag

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18764]
![image](https://user-images.githubusercontent.com/3536496/96033911-98777600-0e15-11eb-8a9a-6a8639276ad4.png)
Crops should be actual crops. If this is used for harvest contract, its meant to allow harvesting all types of crops.

**Comment by IcedForge** [comment]
Cannot select tags using Harvest Field for contracts
Not sure if this is what you meant @johnkslg 
![Screenshot_23.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/5c14bd20-7799-40d4-b2f7-ad76c1ae7f94)

Might be unrelated as i cannot select any category and submit, it will just be empty

**Comment by serpopov** [comment]
Harvest tag is hidden

**Comment by serpopov** [comment]
@IcedForge I mean that is techical issue, harvest contract should stay same as it was with same items available.
