### ISSUE TITLE
USER ISSUE: Pipes leaking

### ISSUE THREAD

**Issue by Sanquira** [StrangeLoopGames/EcoIssues#18762]
![pipe_leak](https://user-images.githubusercontent.com/8235842/96016772-70096f00-0e49-11eb-9da8-6f68d088b03a.png)
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Place the pump
2. Place 2 Blast Furnaces
3. Connect furnaces to pump
4. Power up the pump
If the effect does not occur, try add more machinery.

**Expected behavior:**
Water is not springling from the pipe and it should go into machinery.
Machinery should work.

**Actual behavior:**
Water is leaking from the pipe despite the pipe being closed.
Machinery is ready and green, but turn red (missing water) when there is work to do.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and idk

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5379534/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5379535/Player-prev.log)

**Comment by SlayksWood** [comment]
@Sanquira Thank you for the report. 
Pipe leaking was  only a visual bug. Apparently something has changed. Merged to #18762
