### ISSUE TITLE
[0.9.1.0 beta staging-1804]Civics: Capitol invalid article doesnt update text when functioning again.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18761]
Procedure to break stuff:
Add capitol
Add election process
Add government office

Draft a constitution ratification, create a draft title and election process draft
Set title as veto user in "Election process 2"
use this "Election process 2" in the constitution

Vote in the constitution and it will break and turn invalid because the Veto user is not actualized as it is only a draft and not active.
Now you do not have preliminary permissions as the constitution is not in draft form anymore.

So fixing this you open capitol, change election process back to basic election and hit draft again,
now you can edit title and add it to election, now change back election process on constitution into "Election process 2" again.

This will make the constitution work fine, and all permissions and mechanics are working as intended BUT it doesnt update the text display on invalid items in the constitution itself.
![Screenshot_155.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/897e274c-d60d-4606-b5c4-1ce098a9fb69)

**Comment by johnkslg** [comment]
Made it now require any referenced thing that's a draft also be in the election, or it can't start. 
Text should be fixed too.
