### ISSUE TITLE
Game freezes at random on Linux

### ISSUE THREAD

**Issue by JanThomas118** [StrangeLoopGames/EcoIssues#18767]
OS: Fedora 32
GPU: Nvidia 1060ti (proprietary driver latest)
Steam Runtime Soldier

The Game hard freezes in regular intervals (arround 4 minutes) to the point that one has to kill it from some task manager (SIGKILL is neccesarry, normal closing wont do anything). It does not seem to be due to RAM usage as that looks normal.

Log: https://pastebin.com/gunBVTL3
Graphics Settings: [screenshot](https://media.discordapp.net/attachments/550333577074835486/766022658428764200/Screenshot_from_2020-10-14_21-40-05.png?width=1080&height=456)

Note: The game music keeps running when this happens
Another Note: My roommates System (RX 480) does not have this at all

Some more info: I ran the game with gdb and found some more info about the segmentation fault. I have created a core dump of the thing aswell. If it helps you fix this i can provide it too

```gdb
Thread 34 "UnityGfxDeviceW" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f9885dfe700 (LWP 35270)]
0x00007f9970258597 in vk::DataBuffer::CreateResource() () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
(gdb) backtrace
#0  0x00007f9970258597 in vk::DataBuffer::CreateResource() () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#1  0x00007f99702582a7 in vk::DataBuffer::Initialize(void const*, vk::CommandBuffer*, vk::ScratchBuffer*, unsigned long) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#2  0x00007f997020e65b in GfxDeviceVK::InitializeBufferInternal(GfxBuffer*, void const*, GfxUpdateBufferFlags) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#3  0x00007f997019fe33 in GfxDeviceWorker::RunCommand(ThreadedStreamBuffer&) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#4  0x00007f99701a0d3b in GfxDeviceWorker::RunExt(ThreadedStreamBuffer&) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#5  0x00007f9970196e05 in GfxDeviceWorker::RunGfxDeviceWorker(void*) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#6  0x00007f99705a021a in Thread::RunThreadWrapper(void*) () from target:/home/louis/.local/share/Steam/steamapps/common/Eco/UnityPlayer.so
#7  0x00007f996f989432 in start_thread () from target:/overrides/lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f996f8b7913 in clone () from target:/overrides/lib/x86_64-linux-gnu/libc.so.6
(gdb) generate-core-file 
```

**Comment by mirasrael** [comment]
Hi. It is GPU related crash (it fails when Vulkan tries to CreateResource) which is either due to Unity bug or due to driver bug. Did you try to update drivers to latest or rollback to older version? Also did you try disable shadows and reduce resolution? Also you can try different screen modes (i.e. Exclusive Fullscreen).

**Comment by JanThomas118** [comment]
Updated to latest nvidia driver (i don't think downgrading is a thing here) tried switching to windowed or to exclusive full screen and setting the game settings to lowest possible also doesn't change it.
Its super weird, sometimes it happens every 5 minutes and sometimes it doesnt happen for 2 hours

**Comment by SlayksWood** [comment]
@JanThomas118 Do you still have problem?

**Comment by SlayksWood** [comment]
Closed for now. Have some improvements, but hard to test it on Linux.
