### ISSUE TITLE
[0.9.1.0 beta staging-1804]Icons in work parties

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18760]
Some icons can be very hard to see due to background coloring and the color of the icons themselves such as carcass in work party
![Screenshot_153.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2277aaa4-4656-4c36-926c-faab2f450812)

**Comment by SlayksWood** [comment]
and in tooltips too

**Comment by SlayksWood** [comment]
The icon background was fixed:
![image](https://user-images.githubusercontent.com/45708377/111963965-2bbf8080-8b05-11eb-8d8e-a11ef743b614.png)
Closed for now.
