### ISSUE TITLE
[0.9.0.5 beta release-100]Tooltip overlay displays above work button when crafting window is too short

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18763]
When you mouse over Work button the tooltip for crafting an item can cover it and you cannot click on the button, this happens when a crafting cycle tooltip is too long and has a lot of ingredients and the Y displacement of the crafting UI is too short.
![Screenshot_158.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0911a87f-e907-4213-b1c0-8783c204d8e6)

While this works fine as long as the window is tall enough to fit the tooltip ABOVE the crafting window itself.

![Screenshot_159.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a4cb47ff-9f2a-4c05-a6c9-04f7d0aeebbf)

**Comment by johnkslg** [comment]
I suppose it should try to scoot left/right so it doesnt cover the element its referring to

**Comment by SlayksWood** [comment]
Still possibly and I don;t know why it happens. Just make minimum size for window (length and width), place window in middle (+/-) and mouseover 'Work':
![image](https://user-images.githubusercontent.com/45708377/100736614-1272b700-33e4-11eb-9956-2684b8910e81.png)
