### ISSUE TITLE
[0.9.0.4] Animals can recover from extinction.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18772]
When animal species count reaches zero, it is still possible for new animals to spawn. This really interferes with simulation and need for hunting protection laws.

Can we add a check if the actual population is zero that no more will respawn? Also, if there are none of that species in an area, ideally they will not respawn there either.

**Comment by SlayksWood** [comment]
Seems fixed. Bisons died and aren't restored. Coyotes become restored:
![image](https://user-images.githubusercontent.com/45708377/98917548-928cb780-24dd-11eb-8983-34ab1ea376a4.png)
