### ISSUE TITLE
"Business" option reported to be not working in contact form

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18771]
For QA: Please test if it works and the mail arrives _on production_, not staging.

**Comment by SlayksWood** [comment]
I tried to send mail but have error (I hid the mail):
![image](https://user-images.githubusercontent.com/45708377/96223637-e798e480-0f96-11eb-8351-1267c7ed4e01.png)

**Comment by SlayksWood** [comment]
It doesn't work on staging too.

**Comment by denysaw** [comment]
Could be tested on Staginland.
