### ISSUE TITLE
[0.9.1.0 beta-staging-1805] Barter function displays 0 balace in Y economy view

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18775]
If you toggle barter in a store it displays a value of 0 in the economy viewer which personally at least i associate with that "This store cant buy my things as it has no money"

Maybe change the value into text in the same way that personal currency says "Infinity" but an alternative text "Barter"? 

![Screenshot_167.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/011c0c07-1f33-4490-af83-38eef0b31b55)

**Comment by SlayksWood** [comment]
And maybe write something else instead 'Store Credit'. Maybe Barter with another color?

**Comment by SlayksWood** [comment]
Have a little problem when place a new store. Step to reproduce:
- connect to server, place several stores with barter:
![image](https://user-images.githubusercontent.com/45708377/101876433-709a5980-3b9d-11eb-8e4a-3eab8ef3aaca.png)
