### ISSUE TITLE
9.0.4 unable to load the voting page for elections

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18785]
**Steps to reproduce:** click on in game election notification, click on open in browser
**Expected behavior:** webpage to vote in election for new law proposal opens
**Actual behavior:** get screen saying that it took too long to respond and it can't load; it is worth noting that the same server was loading fine for me just about a week, maybe week and a half ago.
**Providing Log files:**

![20201015221949_1](https://user-images.githubusercontent.com/1329717/96209233-ba1b4f00-0f34-11eb-8feb-ba8160eb3228.jpg)

![20201015221954_1](https://user-images.githubusercontent.com/1329717/96209223-b38cd780-0f34-11eb-8d2c-158b16250069.jpg)

![20201015221957_1](https://user-images.githubusercontent.com/1329717/96209211-aff95080-0f34-11eb-9df3-5b7d44d4681d.jpg)

![image](https://user-images.githubusercontent.com/1329717/96209113-83ddcf80-0f34-11eb-81c6-ebbef79810e8.png)

**Comment by Sarah-Graesyn** [comment]
so I get the same result in Microsoft Edge, Google Chrome, and Mozilla Firefox, just attempted to load the voting page on all three of them.

**Comment by SlayksWood** [comment]
@Sarah-Graesyn Thank you for the report. please provide some information:
1. Which kind of internet connection are you using?
2. Please provide your PC specification (include Operating System).
3. Do you have Firewall or Antivirus enabled?
4. Do you have this problem only on this server? or you have it on any server?
5. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
6. As far as I understand this is official server "Coast Redwood"?

**Comment by MishkaFur** [comment]
This is on my server, that IP 95.217.35.61 is a Hetzner one which I do not use as my provider nor have ever used for my Eco Servers.

Port though is correct for my server unless one of the officials also uses 4001 for web UI, screenshot below of my network.eco's IP section

![image](https://user-images.githubusercontent.com/61889138/96254310-01452680-0fad-11eb-9907-b4762d2b69cb.png)

**Comment by StallEF** [comment]
you cannot connect via an external IP because your router cannot forward packets to itself, this is called a loop. If you play alone, then it is enough to change your IP to the one that your computer has on the local network

if you have public server it problem easily resolved via DNS (domen name) and add in you locanhoct file in Windows

**Comment by MishkaFur** [comment]
@StallEF this log is not that issue at all and your comment does not seem to make sense, Sarah is in a different country to me, playing on my server and it has directed them to the IP of a server at Hetzner not mine.

**Comment by SlayksWood** [comment]
@MishkaFur Try to add 95.217.35.61:4001 in Remote Address

**Comment by MishkaFur** [comment]
> 
> 
> @MishkaFur Try to add 62.133.10.114:4001 in Remote Address

Actually added the server domain server.snepserv.com:4001 and it is working for the webui, @Sarah-Graesyn please check webui when you are on if i dont see you first

**Comment by redwyre** [comment]
You should probably put `server.snepserv.com` as both remote address and web server url

**Comment by MishkaFur** [comment]
> 
> 
> You should probably put `server.snepserv.com` as both remote address and web server url

I am assuming remote address i need to format it as server.snepserv.com;4000 or just server.snepserv.com as the description says "uses GameServerPort if no explicit port specified" but that seems redundant as you'd not have a differant port in that field than Game Server Port?

![image](https://user-images.githubusercontent.com/61889138/96730415-0986d280-13ae-11eb-9a2b-e8e5dde574b8.png)

**Comment by redwyre** [comment]
You could have a different port due to port mappings and internal network routing. But if it's pointing directly to a machine you can leave it off as it's always going to be the same.

**Comment by Sarah-Graesyn** [comment]
server.snepserv.com is working. Am able to pull up the webui for the server though as I am not also currently logged into the server I can only see what has been done on the server thus far

**Comment by IcedForge** [comment]
@Sarah-Graesyn 
Did this get resolved? Or are you still having this issue?

**Comment by Sarah-Graesyn** [comment]
So far as I know it’s been resolved
