### ISSUE TITLE
[0.9.1.0 beta-staging-1806] Crafting Fee / Taxation on queued not crafted.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18789]
Crafting fees and taxations are applied on work order created not item created,
if fee is 1$ per item
and you set a work order for 100 items
it will charge you 100$ immediately
now if you regret your decision, or maybe something happened and you want to cancel
you have paid all crafting fees already and cannot get that money back.

This should be changed into paying on actual item crafted not queued.

**Comment by SlayksWood** [comment]
Still an issue:
- first player create public workbench with fee
![image](https://user-images.githubusercontent.com/45708377/108054796-2aabb700-7060-11eb-9bda-8564879672ab.png)
- second player create an order for 100 Boards. He pay 1000 Test Fee coin to first player. Should pay them to Contract Escrow Bank Account:
![image](https://user-images.githubusercontent.com/45708377/108054905-52028400-7060-11eb-8be2-37d0eb6152a0.png)
-cancell order:
![image](https://user-images.githubusercontent.com/45708377/108054933-5cbd1900-7060-11eb-878b-5ec8e2061696.png)
- first player lost all money:
![image](https://user-images.githubusercontent.com/45708377/108054957-647cbd80-7060-11eb-8d0c-c9396b3e98fa.png)

**Comment by SlayksWood** [comment]
need to test in 9.4

**Comment by TwixterZ** [comment]
Tested on 9.4 Develop 259, fee is charged when build order is created

**Comment by TwixterZ** [comment]
Repro :
Req : 2 id

step :
1 - use 1st id to /spawn tool bench (as example)
2 - set authorization to everyone
3 - set Fee per item price
4 - connect to same world with 2nd id
5 - transfer some fund from 1st id to 2nd id
6 - use 2nd id to proceed to craft item(s) on tool bench
7 - observe fee is charged the moment "order" button is clicked

**Comment by tuha263** [comment]
The fee is charged as guaranteed money (transfer to treasury) and will be refunded to the player if the order was canceled
![Refund](https://user-images.githubusercontent.com/9598614/117027336-cc20db80-ad26-11eb-9bc6-0ed7383aeb87.png)

**Comment by TwixterZ** [comment]
this is confirmed working, as of 9.4 Develop 277
