### ISSUE TITLE
USER ISSUE: Waste filter do not consume power

### ISSUE THREAD

**Issue by Sanquira** [StrangeLoopGames/EcoIssues#18783]
\
**Version:** 0.9.0.5 beta release-100

**Expected behavior:**
Waste Filter is processing Sewage, producing Compost, but does not consume power.

**Actual behavior:**
Waste Filter consumes power when working.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Comment by SlayksWood** [comment]
merge #18583
