### ISSUE TITLE
[0.9.0.5 - beta-release-100] Prev election page on website does not reposition logged user

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18782]
Slight issue with when you have a long list of previous elections it does not update the positioning of the logged in client and server window causing overlap in the list.
![Screenshot_1.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f3910eeb-dc39-4dc7-8042-593039b61f53)

**Comment by j3fffff** [comment]
fxed on staging
