### ISSUE TITLE
[0.9.1.0 beta-staging-1806]Currency Exchange

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18788]
Currency exchange does not hold value restrictions for limitations in how much currency to buy and when to stop.
![Screenshot_13.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/da260c9f-dee5-491b-97fb-59a4e7d9bf04)

Could probably push this to 9.2 as there is not a lot of people that use the exchange in general?
@WeaselDog

**Comment by abaza121** [comment]
This is solved by Oleg in this pull request https://github.com/StrangeLoopGames/Eco/pull/7480
