### ISSUE TITLE
9.0.5 Research papers yield way way too high XP rate

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18799]
It is currently possible to just spam out research papers to level a skill instead of crafting items and have a drastically reduced resource requirement

Geology paper basic needs 30 rocks, crushed limestone needs 20 but geology paper gives x4 the XP rate, same is for other papers

So to level mining its best to just get  300 rocks (15 papers) instead of doing 10 crafts of crushed limestone in this case.

Crushed Limestone this.ExperienceOnCraft = 0.5f;
Geology paper Basic      this.ExperienceOnCraft = 2;

**Comment by WeaselDog** [comment]
Lowered exp provided in 9.4
