### ISSUE TITLE
9.0.5 Store default uses credit even if the minted currency is set at treasury

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18793]
Store uses credit even if the minted currency is set at treasury

Crafted a new store, checked treasury which is sent to the minted currency, placed the store and it picked up my player credit by default.

World was generated on 9.0.0 if this is of any help seems to only be stored made/placed after 9.0.5 as this was not happening before.

**Comment by Bazzi89** [comment]
thought it is intended :P

**Comment by MishkaFur** [comment]
Nope @Bazzi89 
![image](https://user-images.githubusercontent.com/61889138/96337341-5d2bb000-107e-11eb-82d3-3b5fdc1816b3.png)
