### ISSUE TITLE
Animal assert triggering constantly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18796]
![image](https://user-images.githubusercontent.com/3536496/96321534-a02c4b80-0fca-11eb-853e-f3ccbb175c9c.png)

**Comment by mirasrael** [comment]
@johnkslg instead of removing assert you can use AssertionFlags.WarnOnly parameter. In this case you won't lose information about an issue, but won't be chased by constant breakpoints.
