### ISSUE TITLE
[9.0.5 Beta Release] Government Notifications bypassing chat filters and still showing up/ Government Notifications Obscuring Screen and making game unable to be seen

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18798]
**Steps to reproduce:** Filter out the chat so that you only get the things in chat that you want to see in the chat box
**Expected behavior:** Only see what I have left in my chat
**Actual behavior:** Government Law notifications (Specifically I have noticed this with a law that myself and Mishka have set up on the server we are running that pays people for working on roads) co9ntinually spam roads despite the fact that they should be getting filtered out so that they don't show up in the actual chat
**Providing Log files:**
![20201016193644_1](https://user-images.githubusercontent.com/1329717/96324469-a41a9680-0fe7-11eb-9a59-1d70e26a3037.jpg)
![20201016192923_1](https://user-images.githubusercontent.com/1329717/96324480-ac72d180-0fe7-11eb-9c73-d02ee3f8c533.jpg)
![20201016192933_1](https://user-images.githubusercontent.com/1329717/96324524-d88e5280-0fe7-11eb-9e29-a906d1257806.jpg)
![20201016193031_1](https://user-images.githubusercontent.com/1329717/96324547-f065d680-0fe7-11eb-8a64-9642fbcc2c4f.jpg)
![20201016193434_1](https://user-images.githubusercontent.com/1329717/96324567-0b384b00-0fe8-11eb-8262-2a06f6745fec.jpg)

I refined the filters to drop out "yourtrades" after I realized this was happening thinking that maybe there was something happening that Eco was confused but then I tested to check and the law was still forcing the notifications into my chat window. Additionally the notifications pop up over the game screen directly in the middle and make it impossible to play the game for about 45 seconds or so until the popup decides to go away when you do large movements of blocks or many blocks one after another quickly.

Tagging @mirasrael and @johnkslg so you guys can see this as I think this is a bug in the government system itself.

**Comment by IcedForge** [comment]
Thank you for reporting, this has been fixed for 9.1
