### ISSUE TITLE
[9.0.5] Admin Devtool Bug: Removing Admin while player is offline and Devtool is on the players hotbar bugs the Devtool

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18802]
**Steps to reproduce:** Grant player admin, have them spawn in a Devtool, let them use it a bit and then they log off, remove admin while they are offline but while the devtool was left in their hotbar (mine was in slot 1), when they log in they attempt to use it get the "you cannot currently use this tool" message, restore admin
**Expected behavior:** Devtool functions normally
**Actual behavior:** when picking up a block it no longer gives infinite of that block you have to pick up/replicate a block with the Devtool every time you want to place one by looking at a block and pressing E while targeting it though the Smite functionality still works fine
**Providing Log files:**
I am not quite sure what log files to provide here as I am not sure what all would be helpful, if you guys can think of what might be helpful let me know and I'll grab them from in game or from my files.

@mirasrael, @johnkslg the two of you are the only ones I can think of to tag on this one

**Comment by MishkaFur** [comment]
Not a bug, modified devtool on my server.
