### ISSUE TITLE
[0.9.0.5] Tools are upside down under Pop_!OS

### ISSUE THREAD

**Issue by omelancon** [StrangeLoopGames/EcoIssues#18807]
**Version**: 0.9.0.5 beta release-100

**Bug**

Currently selected item/tool is upside down..? This is best explained with a screenshot.
![382310_screenshots_20201017213721_1](https://user-images.githubusercontent.com/16464818/96357136-83c10980-10c5-11eb-8acd-55489e6eec59.jpg)

**Specs**

I ran the native game (not with Proton) under Pop_!OS, I am using system76-nvidia driver on an Oryx pro with the following specs.

- Pop!_OS 20.04 LTS (64-bit)
- 6 GB GDDR6 RTX 2060
- 5.1 GHz i7-10875H 
- 32 GB

The game runs very well overall except for this... surprising glitch.

**Comment by Astrija** [comment]
duplicate
https://github.com/StrangeLoopGames/EcoIssues/issues/18414
