### ISSUE TITLE
[9.0.5] "BunnyHop" makes you go twice as fast!

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#18803]
So im that guy that jumps all the time.. and with the last patch i found that you can "BHop" and go really fast.

I made a little recording of normal running - run / jumping - Bhop between some lightposts.

The normal run and normal run / jumping takes roughly 9 seconds - the bhop takes roughly 5 seconds.
I made this video "under pressure" so the Bhop is really bad.. you can jump at least 50% faster than i did in the video..

https://youtu.be/Mx3kC0KGa8Q

**Comment by SlayksWood** [comment]
related with moving by diagonally (W+A or W+D). We must have this issue, but I can't find.

**Comment by NemoLArs** [comment]
> related with moving by diagonally (W+A or W+D). We must have this issue, but I can't find.

Oh you mean like. 10 movementspeed for each button hold?
w = 10;
w + a = 20;

**Comment by SlayksWood** [comment]
@NemoLArs No it's more like W = 1, W+A = sqrt (1+1)

**Comment by NemoLArs** [comment]
I don't think that's the problem. Because jumping without moving the mouse don't make you go faster. You need to move the mouse sideways.
