### ISSUE TITLE
USER ISSUE: Elevator intermittenly stops randomly

### ISSUE THREAD

**Issue by TootleBrush** [StrangeLoopGames/EcoIssues#18809]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
Set up a elevator.
Go up/down using the controles inside, or the external ones.

**Expected behavior:**
It would normally go up or down till it hit the ends, either ground/dirt/floor/stone etc. or the top of the elevator itself.

**Actual behavior:**
It go down for a varied and changing number of seconds before you have to push the button again, and again, and again. It never run a full cycle.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@TootleBrush Thank you for the report. There has never been a similar problem.
Can you provide additional information?
1. how many people are in the elevator?
2. maybe there are any objects there, like wood cart?
3. If you can provide some video.
4. Log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TootleBrush** [comment]
1. Only me
2. Nothing in it.
3. Find video here:
https://www.dropbox.com/s/iwx51tk0bfbl6yp/Desktop%202020.10.20%20-%2011.09.19.01.mp4?dl=0

Hope it helps. Others I talk with have also experienced it

**Comment by vini2003** [comment]
I am having this issue right now.

https://streamable.com/qk569i

**Comment by vini2003** [comment]
While that video does not show it stopping multiple times, it already should not be stopping there, so that's a start, Overall, the elevator just behaves very erratically.

**Comment by TootleBrush** [comment]
Sorry maty.
My issue was not with that elevator. It was with the old elevator, that
video is not one I have send, and I haven't seen this new elevator since I
haven't played the game for about half a year now.
But nice that you reply to me. Good to see you guys taking it serious.

**Comment by Lenniitsch** [comment]
I have the same issue with the industrial elevator on my server. 
Going down is not an issue (even with vehicles), but going up doesn't work. Random stops, sometimes the vehicle "slide" off as they are not attached to the platform. 

Here is a video showing the stops: https://www.youtube.com/watch?v=9aZ5GTntqwM 
Server & Steam Client Version: 0.9.3.3 beta release-219

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416161/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6416163/Player-prev.log)

**Comment by D3nnis3n** [comment]
Merge with https://github.com/StrangeLoopGames/EcoIssues/issues/23983
