### ISSUE TITLE
[0.9.1.0 beta staging-1806] Crowdin requires updating (Help text for chat command)

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#18800]
- Drops a global waypoint at the current position. Accepts an optional text string for the waypoint.
- Makes all animals hungry.
- Spawns a store with storages and random trade offers.
- Resets the world caches.
- Displays a list of all known users, showing username and ID.
- Removes user as an Admin by account id, steamid, slgid, or username
- Save the world!
- Kicks user
- Resets the world caches
- Removes the nearest global waypoint to you current position.
- Shows list of admins or add user by account id, steamid, slgid, or username
- Shows list of banned users or bans user by account id, steamid, slgid, or username
- Displays a list of all known users, showing username and ID.
- Shows list of muted users or mutes user by account id, steamid, slgid, or username
- Unban user by account id, steamid, slgid, or username
- Unmute user by account id, steamid, slgid, or username
- Removes user from the whitelist by account id, steamid, slgid, or username
- Shows list of whitelisted users or add user to whitelist by account id, steamid, slgid, or username
- Shows the user ID of the requested user.
- Adds meteor impact hours
- Destroys the meteor in orbit.
- Make the meteor enter the targetable range, or the specified angle if one is passed in.
- Adds user as manager to bank account with ID.
- Adds user to bank account with ID.
- Creates an account with specified name.
- Deletes an account even if there is still currency on it.
- Remove user as manager from bank account with ID.
- Removes user from bank account with ID.
- Manually set an account creator.
- Removes dead plants in an area.
- Unpollute an area. Remove dead plants and replace dirt on grass blocks.
- Levels up a string matching the passed skill\s name to the max.
- Teleport to an xyz coordinate or an xz coordinate. For two components Y is calculated automatically.
- Force the world to fast forward. Pass 0 to stop.
- Shows you user ID
- Displays a list of all administrators
- Shows you Ignore List or adds the player to the Ignore List by the name or remove if the player is on the list already
- Spawns a meteor into orbit, regardless of current disaster settings.

Duplicate strings =>  {0}{1} labor   and    {0} {1}labor

i hope "Developer" chat commands will be add beforehand too

**Comment by mirasrael** [comment]
@Quadbro Localizer now only handles ChatCommandAttribute, but these strings is from ChatSubCommandAttribute. Need to be updated.

**Comment by Quadbro** [comment]
Yeah, thanks, will fix asap

**Comment by SlayksWood** [comment]
localized in Gibberish.
@StallEF Reopen if you still have some problem
