### ISSUE TITLE
USER ISSUE: EMpty void of death

### ISSUE THREAD

**Issue by FerreTux** [StrangeLoopGames/EcoIssues#18811]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
Kill aligator
Jump on aligator
Enterspace

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@FerreTux Thank you for the report. Anything else you can add? Screenshots, video?

**Comment by FerreTux** [comment]
Basically I was teleport to z max or something.   Everything was a complete black void but when I moved X̄ or ȳ it registered on the map as lateral movement ect.   Using Teleport  admin commands with Z index moved me back into the game world.    As for experience when it happened I shot straight into the air and watched the planet disappear into the darkness.  Not even a pale blue dot was visible by the end.    I believe it had me a 1511 meters away but on the map   directly above where i was.   



To understand this a bit better I was directly at the edge of another players territory line.  they had no kill permissions and alligator was crawling back to the line where we wouldn't be able to hurt it.   It was almost there when Me and my friend were finally able to kill it.   The corpse vanished and I ran up to where it was and jumped as soon as I did my friend reported me being a rocket ship to space.    Presumptively, I would assume it would have to do with the corpse vanishing so my character received some sort of bogus collision that applied a max acceleration to my character.    Root cause is more than likely a corpse vanishing or desyncing when two people are killing it on the border of a territory.

Alternative solutions/Suggestion.  Add a /stuck that respawns you at your x,y coordinates similar to /tp x, y.  Even better if you add a bit of random x,y drift in case someone gets stuck in a pit or something. 

Of course theres always the best UX solution /stuck just respawns you at a bed 

Hope that helps sorry I can't offer more.  I was very tired and dying laughing when this happened.

**Comment by FerreTux** [comment]
You should also run your logs per day rather than per execution.   The overwrite doesn't help for bug triage.  =p  most people try to reboot a few times on their own before reporting a bug.  <- happens to me at work too.    

Really liked the in game bug report +1 big kudos to team for that.   Maybe just have it snapshot the log as soon as that button is pressed.   I know other games like eve online keep ever run ever. The diskspace is really negligible at that point.

**Comment by SlayksWood** [comment]
merged to #18805
