### ISSUE TITLE
Long constitution names can break it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18817]
![image](https://user-images.githubusercontent.com/3536496/96397153-bc241e80-117d-11eb-96d3-7037e1b3ff04.png)
looks like its compressing past the boxes of the article name and the article title.

**Comment by SlayksWood** [comment]
I don't like when text is going out window and you can't see it without changing window size:
![image](https://user-images.githubusercontent.com/45708377/98238401-615d3600-1f77-11eb-8ba6-437901eb26a4.png)
In this case, we need to add a horizontal scrollbar. But it won't look very good. Therefore, it is closed for now. If we need any changes, we will return to this problem later.
