### ISSUE TITLE
[0.9.0.5 br-100] Rocks are a bit too eager to deny being picked up

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18816]
I was mining next to someone's property and some rocks seemed a bit too stubborn to be picked up even if some tiny part of them was on someone's property:

![image](https://user-images.githubusercontent.com/964559/96394183-38b2ff00-1176-11eb-874f-87b3d3eb1308.png)

or even near it:

![image](https://user-images.githubusercontent.com/964559/96394208-410b3a00-1176-11eb-8eb2-981705c2a5a7.png)

Since you can physics glitch them around anyway, maybe the chunks should be a bit less eager to be restrictive about being picked up. If you can mine them, you probably can pick them up after all, and if someone else mines them and they fall on the border of two properties, it's a fair game I suppose.

**Comment by SlayksWood** [comment]
merged to #15556
