### ISSUE TITLE
[9.0.5 beta release] unknown reason - crash to main menu while mining granite

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#18810]
**Steps to reproduce:** mine out a wall of rock (I was mining granite at the time)
**Expected behavior:** mine granite, start picking up chunks, store, crush, etc
**Actual behavior:** crash to main menu
**Providing Log files:**
[mining crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5398137/mining.crash.txt)

**Comment by SlayksWood** [comment]
merged to #18214
