### ISSUE TITLE
When an inventory is too heavy, attempting to unload will instead take your tool 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#1882]

**Comment by MarjieAVolk** [comment]
Yeah this is a question we've had a few times - should we just not allow tools to get put into inventories with right click?  That's about the only solution I can think of

**Comment by Nanders** [comment]
I like that idea, still make it able to store in inventories but not able to "quick store"

**Comment by metachronism** [comment]
yeah honestly I think right click to place should only be for things you are carrying, never anything in your toolbar for consistency sake

**Comment by MarjieAVolk** [comment]
I know you do; I still don't understand why.  Seems more consistent to have right click behave the same for everything.  And also there is no alternative that is remotely as easy.  Do you just want to have different controls for carried vs. non carried across the board?  If so, there are lot of other things for which they have always been the same - such as right clicking to place
