### ISSUE TITLE
[0.9.0.5 br-100] Ocean / River sand turns to dirt underneath bridges

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18824]
Not sure if this is intended, but on our Coast Redwood server the Ocean and River Sand underneath a bridge slowly turned to regular Dirt:

![image](https://user-images.githubusercontent.com/964559/96427072-f22fc580-11b2-11eb-99b6-9bd4d7acb738.png)

I'm guessing that's just how it operates if it has some block above it, even though it's way above it?

**Comment by SlayksWood** [comment]
@ThePiachu Thank you for the report. Has it disappeared over time? I tried to investigate this problem yesterday. I did not observe anything of the kind. So I have an assumption that it is related to Player Activity. And that after a while it will again turn into Ocean Sand.
So I add it to investigate for now. Will be nice to have your answer after some time about any changes.

**Comment by ThePiachu** [comment]
It's still there on Coast Redwood:

![image](https://user-images.githubusercontent.com/964559/96682965-66db3f00-132e-11eb-9322-cccff6cc5787.png)

But you might be right, it might be tied to trample:

![image](https://user-images.githubusercontent.com/964559/96683193-a9048080-132e-11eb-84cc-76495fa3bb74.png)

I don't think all of my house for example has the dirt underneath it, just the parts I walk around on the most...

**Comment by SlayksWood** [comment]
merged to #18291
