### ISSUE TITLE
[0.9.1.0 beta staging-1806]Civics: Mint currency trigger review

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18821]
Mint currency  sub-trigger "Currency Amount" only count amount of instances you craft a currency, not total value of the craft which makes laws for currency amounts unnecessarily complex and can easily be circumvented if not done correctly.

Change currency amount into the total value of the currency its pointed towards.
![Screenshot_47.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a96c2715-d921-4814-90cd-a3cf3b3b0f93)

**Comment by johnkslg** [comment]
Update the comment on the context value too
