### ISSUE TITLE
[0.9.1.0 beta staging-1810]Civics: Able to vote on things that are not put to election.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18829]
When ratifying constitution you can click its name link, go to the website and vote for it before it is set to an election.
![Screenshot_14.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/218df019-b0ba-48ad-a7b2-ab3f91dda6f0)

![Screenshot_11.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/1ddb1bab-facd-4b7b-b574-c4808899a79e)

**Comment by SlayksWood** [comment]
Still an issue.

**Comment by SlayksWood** [comment]
This issue still exists and needs to be fixed before release. It was auto closed after develop merge.

**Comment by johnkslg** [comment]
@gzatravkin can you field this

**Comment by SlayksWood** [comment]
fixed in 0.9.1.1
