### ISSUE TITLE
LawSystem: Skid & Excavator not triggering Dig or Mine trigger

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#18828]
Hello,
 in the law system, the skid and the excavator are not triggering the dig or mine trigger when in use. So a law to prevent dig or mine can be cheated by using the skid or excavator. Even the skid is been listed as an item to use it does not matter. the excavator is not listed as an item, but should although in my point of view.

**Comment by IcedForge** [comment]
Fixed in 9.1 with refactoring and tweaks.
Excavator / Skid-steer dig action as well as tractor / handplough plowing action

**Comment by IcedForge** [comment]
Checked through it, it does trigger its civic action but its not actually preventing it to mine tiles.
Would like to see this fixed in 9.1 if possible? @WeaselDog as this prevents any laws directed at using heavy machinery in authorizations and so.

**Comment by IcedForge** [comment]
It prevents digging properly but it still allows mining actions. ( staging-1876 )

**Comment by tuha263** [comment]
This will be fixed by this PR: https://github.com/StrangeLoopGames/Eco/pull/7370
