### ISSUE TITLE
Eco Tree - Issue clicking User Experience dev

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18834]
In the Eco Tree, when I click a developer who is assigned to a User Experience task, it redirects me to the top of the page. For all other branches/roots, it brings up the section they are working with the tab selected for the issue.

Can we make sure User Experience has the same behavior?

![EcoTreeUserExp](https://user-images.githubusercontent.com/47330823/96508672-d3135100-120f-11eb-9234-843ccfe25227.png)

**Comment by denysaw** [comment]
Could be tested on Staging.
