### ISSUE TITLE
USER feedback: Ecopedia focus should start on the typing bar so you can press F1 and just start typing

### ISSUE THREAD

**Issue by thepolypusher** [StrangeLoopGames/EcoIssues#18832]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Open Ecopedia
2. Start typing

**Expected behavior:**
You should be able to search without having to click on the search bar

**Actual behavior:**
Nothing, you can't search without a pointless click

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by WeaselDog** [comment]
Make this apply to the economy viewer as well. Both should start with the search bar as the default.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop 192.

Pressing F1 and typing now works.
