### ISSUE TITLE
Eco Tree - Need category for Client in Performance root

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#18838]
We need to add a category for Client in Performance category. We have a fair amount of these issues assigned, and there is no proper place to put it.

This is especially important because optimization is a highly requested thing for us to work on, and it is good to show that we are actively working on this.

**Comment by j3fffff** [comment]
Also added documentation for adding new sub features to the tree https://docs.google.com/document/d/1qcWvE6eELCcwy04kDgOg-fq9Mi7LXSLc8DTutEMveRM/edit#heading=h.b1v62y3ifuja
