### ISSUE TITLE
[0.9.0.5 br-100] Vehicles tend to clip through the floor when area is loaded

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18839]
I decided to build my house on the ocean not to have to deal with digging up dirt or levelling the ground. However, I still have to park my truck on solid ground, otherwise I'd have to fish it out from the bottom of the ocean on regular basis. It seems that when vehicles are loaded into an area (possibly after server restart or what have you) they have a tendency to clip downwards through the floor. I've even seen this happen on solid ground, but in that case the vehicle just looped back around from the bottom of the map back on top.

This is also an issue in the mines where carts would randomly teleport to different levels and so on.

It would be nice for the vehicles to be a bit more stable in the game.

**Comment by SlayksWood** [comment]
merged to #15688
