### ISSUE TITLE
[Web] Add possibility to logout from any page

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18842]
maybe here:
![image](https://user-images.githubusercontent.com/45708377/96549494-38228180-12b8-11eb-9763-1168a1747701.png)
or here:
![image](https://user-images.githubusercontent.com/45708377/96549512-3fe22600-12b8-11eb-9374-893095445389.png)
I prefer 1st point, it suits our site more.

**Comment by denysaw** [comment]
@johnkslg As you are the main menu master :), please, approve 1 or 0 of these cases and I'll implement. In submenu it's a nice idea.

**Comment by johnkslg** [comment]
Case 1 looks good!

**Comment by denysaw** [comment]
Done. Could be tested on Staging.
