### ISSUE TITLE
[0.9.1.0 beta staging-1813] Tutorial List UI still apperant after skipping/completing

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18844]
The tutorial list graphic stays after completing/skipping tutorial and should not be visible.
![Screenshot_21.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/a9067f99-7b83-45c8-a841-bb4f634b8558)

**Comment by SlayksWood** [comment]
Still an issue. only text dissapears, frame still here and doesn't dissapear after client restart.
