### ISSUE TITLE
﻿CW: Infinity payment when removing one of citizens

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18849]
- buy 1 world and 3 citizens:
![image](https://user-images.githubusercontent.com/45708377/96581979-52258980-12e3-11eb-8185-4b5ac7145d66.png)
- want to update my subsrciption and have 2 citizens:
![image](https://user-images.githubusercontent.com/45708377/96582058-6c5f6780-12e3-11eb-9436-b45d110ebeae.png)
- press update subscription:
![image](https://user-images.githubusercontent.com/45708377/96582096-7b461a00-12e3-11eb-9ac3-0e3b0f54b938.png)
- complete order:
![image](https://user-images.githubusercontent.com/45708377/96582193-96188e80-12e3-11eb-8578-200578ca79c5.png)
- you will have message 'Congrats' and redirected. Open Subscription page again. You will have infinity payment:
![image](https://user-images.githubusercontent.com/45708377/96582326-cbbd7780-12e3-11eb-8236-9450a20e2c28.png)
 On first account I wait near 30 minutes.

**Comment by denysaw** [comment]
Fixed. I would say it was critical, but thankfully we have no players with removing-the-citizens case. Also hotfixed on Prod.

**Comment by SlayksWood** [comment]
Yes, it was fixed, and the subscription amount is changing correctly. Checkde on stagingland.
