### ISSUE TITLE
[CW] Owner CW can't change advanced options after losing Admin on server.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18848]
And it's not clear why he loses admin. So step to reproduce:
- start CW, open Advanced options (I just want to add my account to admin list), UserManager tab:
![image](https://user-images.githubusercontent.com/45708377/96573767-45029d80-12d7-11eb-8a8e-e93fa7c6f91e.png)
- So I add another user to admins. I don't remember my slgID and of course I don't remember my SteamID, so I decide just to enter my server nickname:
![image](https://user-images.githubusercontent.com/45708377/96573852-5e0b4e80-12d7-11eb-9a2a-70c2c7e2cbea.png)
- then wait for tick or just use /civics ticknow. I get admin, but CW owner lost admin:
![image](https://user-images.githubusercontent.com/45708377/96573901-6bc0d400-12d7-11eb-8a9d-393096955e2e.png)
- I don't really understand why, but he still in don't delete his slgID. But after that I can't change advanced options at all:
![image](https://user-images.githubusercontent.com/45708377/96573948-7aa78680-12d7-11eb-936b-a67fe63b358c.png)

previous issue with the same problem #18324

**Comment by mirasrael** [comment]
It happened because AdminAuthToken was overwritten with empty value. It is now fixed to not update values not contained in JSON update.

**Comment by SlayksWood** [comment]
need to check in staging build.
