### ISSUE TITLE
[CW] Add notification to add citizen name

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18851]
after reset citizen:
![image](https://user-images.githubusercontent.com/45708377/96588854-cc0e4080-12ec-11eb-86ce-2595ec793195.png)
 will be:
![image](https://user-images.githubusercontent.com/45708377/96589015-ff50cf80-12ec-11eb-876d-a31cfbb13a10.png)
to clarify it.

**Comment by denysaw** [comment]
Done (Stagingland).
