### ISSUE TITLE
[0.9.1.0 beta staging-1814] Work Party tables headers have not localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#18856]
Work Party tables headers have not localization (how on picture), but on tooltip localization is present
![2020-10-20](https://user-images.githubusercontent.com/26339332/96634332-0397df80-1323-11eb-9774-617731f3461f.png)

**Comment by johnkslg** [comment]
When fixing this, can you make it so the localization tool outputs when there are fields that are missing the localization component and likely need it?
