### ISSUE TITLE
USER ISSUE: Steam engine pipes

### ISSUE THREAD

**Issue by rodneymillerpca** [StrangeLoopGames/EcoIssues#18850]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
Place steam engin and try to  connect pipe.

**Expected behavior:**
Pipe connects.

**Actual behavior:**
Pipe does not connect

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for your report. Currently the steam engine does not require water in 0.9.0.X hence why it is not connecting.

**Comment by rodneymillerpca** [comment]
Correct. Was the same in 8.X.X Just thought it should be on a low priority todo list for future development.
