### ISSUE TITLE
When building at specific location (inside building at 395,1200) all players disconnected from the server

### ISSUE THREAD

**Issue by svy** [StrangeLoopGames/EcoIssues#18857]
При постройке игроком v.petroew на координатах 395,1200 выкидывает всех с сервера. В конфиге сервера вкладка "Сеть" пользователи есть, пинги до них есть, но информация (объекты, животные)
 не передаются. Файлы сохранения игры: https://yadi.sk/d/ImbvPTdM0-RLyg?w=1
Лог снят при завершении сервера после выкидывания всех игроков с сервера. Сервер выключается по 10-15 минут. Если 
игрок не строил, то сервер завершается быстро и корректно.
[Error] [Eco] Unhandled errorSystem.OperationCanceledException: The operation was canceled. at System.Threading.CancellationToken.ThrowOperationCanceledException() at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) at Eco.Server.MainClass.Main(String[] args)

**Comment by mirasrael** [comment]
Investigated the issue. It happens when player makes changes in a building with very big rooms. When multiple block changes happened at same time it causes very deep recursive check for rooms:
![image](https://user-images.githubusercontent.com/475445/96870277-54b9e780-1479-11eb-8833-49550b03f6ff.png)

**Comment by Praefator** [comment]
Similar issue: #18616

**Comment by mirasrael** [comment]
https://drive.google.com/file/d/1YC_X4tz3GalD4wyC_cTvundraP00llQ8/view?usp=sharing there is hot-fixed exe file for 9.0.5 in case if you don't wanna to wait until 9.1.
