### ISSUE TITLE
[0.9.0.5 br-100] Store tooltips don't display store's balance

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18859]
When you browse the economy by pressing Y you get a nice breakdown of what stores are buying / selling and their balance:

![image](https://user-images.githubusercontent.com/964559/96682300-773eea00-132d-11eb-8c36-217c1dede56c.png)

However, when you browse the store via a tooltip, you don't have the information about the store's balance:

![image](https://user-images.githubusercontent.com/964559/96682345-89b92380-132d-11eb-91fc-7301f012136a.png)

This information is available, just a bit further down:

![image](https://user-images.githubusercontent.com/964559/96682465-b53c0e00-132d-11eb-82ea-2d36b6abb987.png)

Playing on Coast Redwood this was one of the key pieces of information that was missing for me. I often had to check which stores actually had the money to pay me for my goods, so I would have to either go the extra hover on each store to check their balances, or do a search for the given item. Both of them take a bit long. Tooltip one takes extra time to navigate stores one by one and check the accounts. Search takes a bit because we lack https://github.com/StrangeLoopGames/EcoSuggestions/issues/1269 and because you have to re-do the search each time you open the window (say, after you empty a store from all its money and still have more to sell).

So it would be nice if the store's balance was displayed say, right next to / above the currency used by the store.

**Comment by SlayksWood** [comment]
Can we display in Balance money in Account only for currency which use the store? it will look like this:
![image](https://user-images.githubusercontent.com/45708377/101753119-5734d700-3ae3-11eb-9da0-ec2bcdd4afa6.png)
