### ISSUE TITLE
9.0.5 Disconnect under water for atlantis on main menu

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18852]
Disconnect whilst head is underwater in 9.0.5 and you'll see Main Menu atlantis theme, reproducable has happened a few times whilst im trying to find a good worldgen for white tiger

![atlantis](https://user-images.githubusercontent.com/61889138/96598402-bd248f80-12e6-11eb-9111-b4af0481ec5b.JPG)

**Comment by SlayksWood** [comment]
Should have this issue.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1990.

100% reproducible.
Simply disconnect while submerged underwater.

**Comment by MishkaFur** [comment]
Even worse in 9.5 :D 

![image](https://user-images.githubusercontent.com/61889138/164737522-e5a4d176-d289-4d84-97fb-97ecfdeae83b.png)

**Comment by legionaw** [comment]
> Even worse in 9.5 :D
> 
> ![image](https://user-images.githubusercontent.com/61889138/164737522-e5a4d176-d289-4d84-97fb-97ecfdeae83b.png)

This need to be an option, even if this is unintended, to be honest. This actually looks cool. Please make it happen, after this issue is fixed, of course. lol

**Comment by TwixterZ** [comment]
Hi @MishkaFur, Rejoice! this issue is now fixed as of our latest Staging build. Please let us know if you facing this still.
