### ISSUE TITLE
USER ISSUE: Placing and Picking Up Stone Roads Not Triggering Laws Correctly

### ISSUE THREAD

**Issue by worldnamer** [StrangeLoopGames/EcoIssues#18861]
Please read carefully, this is not a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18860.} though it is very similar.

\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Create a currency; for the purposes of this ticket, we'll call it Wooden Nickels.
 
2. Create a law with the trigger "On Event Place or Pick Up Object" where Block Placed or Picked Up is Stone Road; if Dropped then Try to pay Citizen 8 Wooden Nickel from Treasury Bank Account; else if Picked Up then Collect tax of 8 Wooden Nickel from Citizen into Treasury Bank Account.

3. Ensure the Treasury Bank Account has at least 8 Wooden Nickel. Ensure the player has at least 8 Wooden Nickel.

4. Place, then pick up the Stone Road.

**Expected behavior:**
OPTION ONE: Upon placing the Stone Road, the treasury should pay the Citizen 8 Wooden Nickel. Upon picking up the Stone Road, the Citizen should pay the Treasury 8 Wooden Nickel.

OPTION TWO: Creating laws with the Place or Pick Up trigger should not allow that trigger to affect blocks unless they can actually be placed or picked up. I'm told that Stone Roads can only be "Constructed or Destructed". Why there's a separate category is beyond me (perhaps this is a legitimate programming decision, but I don't have enough information to judge that.) What is completely baffling is that the game allows you to create a trigger for an event that literally can't happen.

**Actual behavior:**
Neither placing, nor picking up the Stone Road triggers any event.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5413982/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5413984/Player.log)

**Comment by SlayksWood** [comment]
merged to #18860
