### ISSUE TITLE
USER ISSUE: Placing and Picking Up Dirt Ramps/Stone Roads/Stone Ramps Not Triggering Laws Correctly

### ISSUE THREAD

**Issue by worldnamer** [StrangeLoopGames/EcoIssues#18860]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Create a currency; for the purposes of this ticket, we'll call it Wooden Nickels.
 
2. Create a law with the trigger "On Event Place or Pick Up Object" where Block Placed or Picked Up is Dirt Ramp; if Dropped then Try to pay Citizen 1  Wooden Nickel from Treasury Bank Account; else if Picked Up then Collect tax of 1 Wooden Nickel from Citizen into Treasury Bank Account.

3. Ensure the Treasury Bank Account has at least 1 Wooden Nickel. Ensure the player has at least 1 Wooden Nickel.

4. Place, then pick up the Dirt Ramp.

**Expected behavior:**
Upon placing the Dirt Ramp, the treasury should pay the Citizen 1 Wooden Nickel. Upon picking up the Dirt Ramp, the Citizen should pay the Treasury 1 Wooden Nickel.

**Actual behavior:**
After placing the Dirt Ramp, the treasury pays the Citizen 1 Wooden Nickel. After picking up the Dirt Ramp, nothing happens. This allows the Citizen to mine the Treasury for money by simply placing and picking up the same ramp in the same spot.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5413937/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5413938/Player-prev.log)

**Comment by SlayksWood** [comment]
@worldnamer You should use Construct or Deconstruct trigger. Initially, drop and deconstruct had to be used for these items #16254
@WeaselDog Can we fix this by removing them from this trigger?

**Comment by Sarah-Graesyn** [comment]
@SlayksWood I see you beat me to this one :)

@worldnamer as Kirill said above, we encountered this issue during the playtest and the resolution was that the law had to be written using the Construct/Deconstruct trigger for it as the drop trigger was only triggering on the placing of the blocks; if you need help on the law you can always ping me on the Eco discord

**Comment by WeaselDog** [comment]
Thanks for reporting this.

@tuha263 Can you remove ramps from On Event Place or Pick Up Object? RampItem is a type of WorldObjectItem. Will have to double check for Stone Roads, but this should have the same solution as Pipes.

**Comment by worldnamer** [comment]
@SlayksWood @Sarah-Graesyn For the road, I did rewrite the law to use the correct trigger, thank you for the help on Discord. This should be an easy patch to just remove those objects (Stone Road/Asphalt) from the Drop/PickUp trigger as selectable objects.

For the ramps, this is a totally different issue that the trigger was only triggering on placement and not pick-up. That's why in my other ticket I said "please read carefully, this is not a duplicate". I'm a little lost in the weeds on the nuance of your ticket workflow, so I assume merging these issues was the right choice, but these are two separate bugs.

Thanks for looking into them!

**Comment by JustinGianelloni** [comment]
I can confirm that we are also experiencing an issue in 9.1.2 with laws triggering on the placement of Stone Ramps. We have tried both the "Construct/Deconstruct" trigger and "Construct" condition, along with the "Place/Pick Up" trigger with the "Placing Object". With both commands, the placing of a Stone Ramp inside a district is not passing the conditional test to pay players for placing them. The deconstruction trigger, however, does work correctly when the ramps are picked up.

**Comment by IcedForge** [comment]
The inherent problem is how it is action performing if you run /civics debug this is very easy to see

This is placing a stone ramp


You have
1x Trigger "Place or Pickup object"
4x Trigger "Construct or deconstruct" - Construct - where item used is "none"
![Screenshot_72](https://user-images.githubusercontent.com/24981362/98970866-bc130680-2510-11eb-986b-637ac3c14d07.jpg)


Now if you pickup the object again
4x Trigger "Construct or deconstruct" - where item is used "Stone Ramp"
1x Trigger "Construct or deconstruct" - where item is used "Stone Road"

![Screenshot_73](https://user-images.githubusercontent.com/24981362/98971174-1d3ada00-2511-11eb-90fb-39c109f564c7.jpg)


It should only count as item used Stone ramp on 1x construct and deconstruct but for all tile counts you can use the "none" from the first part?

**Comment by GreaseMonk** [comment]
I think what really needs to happen here is replace the old stone ramp with multiblock shapes, just like Asphalt. 
That will be so much easier than solving these complex behaviours.

**Comment by Deantwo** [comment]
I suggested **Dynamic Ramp Blocks** once, would still be nice I guess.
See: https://github.com/StrangeLoopGames/EcoSuggestions/issues/824

**Comment by tuha263** [comment]
Because we need to refactor the Ramp, and it's will be a bit risky to apply to 9.2 so I will move it to 9.3.

**Comment by tuha263** [comment]
This duplicates with https://github.com/StrangeLoopGames/EcoIssues/issues/19473. Agree with @GreaseMonk  and @Deantwo, I will refactor both DirtRamp and StoneRamp so they will have the same behaviors with AsphaltRamp
