### ISSUE TITLE
Don't escape fields in CW Network.eco config

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#18863]
![image](https://user-images.githubusercontent.com/5720101/96723506-ed376580-13ae-11eb-8602-0643454d9905.png)

Dennis: Both descriptions shouldn't be escaped.
Example: `<#BCC6CC>[SLG]</color> <#DC143C>Common Chimpanzee</color> - <#FF0000>Official ECO Testing Server</color>`

@D3nnis3n set priority for this fix, please.

**Comment by denysaw** [comment]
Fixed on Stagingland. Tell me if I need to hotfix on prod also.

**Comment by denysaw** [comment]
Hotfixed also on Prod.

**Comment by D3nnis3n** [comment]
Confirmed.
