### ISSUE TITLE
Cannot join or create solo worlds

### ISSUE THREAD

**Issue by Driverdown** [StrangeLoopGames/EcoIssues#18865]
I was playing Eco when I had a power cut, when power was restored I now get an error when trying to enter any of my solo worlds or create a new solo world. I can join existing multiplayer ones however.

When I try to join/create a solo world I get the message: Failed to connect to the local server. It may be because of server crash, you can check the server logs in: D:/Steam/Steamapps/Common/Eco/Eco_Data\Sever\Logs for more details

I can't find any log with the error message and on advice from one of the devs (Dennis) I uninstalled the game, backed up the Server folder and deleted the local Eco files then reinstalled, however the problem persists.

**Comment by IcedForge** [comment]
@Driverdown Thank you for reporting.
Could you provide some additional information.
please upload player logs after trying to create / load a server
Also check /server/Dump folder if you have any exceptions and post them here
and please list pc specifications as well.

**Comment by Driverdown** [comment]
So in a strange turn of events it's now working. I'm not sure how or why, but... yay?
