### ISSUE TITLE
CustomBlockSets not Displaying In Game

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#18879]
I have made 12 different blocksets and none of them display in game, the blocks take up occupancy but the actual block isn't displaying, the code is correct and the custom builders are set up properly as well as the blocksets, i had them display in game once then after that they haven't since

The first time they displayed was back in 9.0.2 

Back before 9.0 was released they would show up in the pre-release of 9.0

**Comment by redwyre** [comment]
@TheKye can you attach a game log? You should just have to join the server then quit. I have reproduced an issue, I just want to make sure it's the same one you're having.

**Comment by TheKye** [comment]
yeah let me get one sorted out for you, 

i have more info on this issue as well, i have managed to get blocksets working in game but they require you too have a "Dummy Set" in the block sets with a standard shader on them, even then it can still be a bit funny

**Comment by redwyre** [comment]
I spent a bit of time on this trying to repro, I have made a custom "stained glass" block as an example mod project, however there are multiple issues blocking it. Will get back on this later.

**Comment by thetestgame** [comment]
I was able to get a test block to recognize and display in game. However, the process of getting the game to recognize the block does not seem to be consistent and when it did display the game was using a default cube mesh and was rendered at an incorrect location. This is behavior others in the modding community have experienced as well. Their methods for resolving this do not seem to be consistent.

An example screenshot of the problem with the red box showing where the glass block was supposed to be.
![image.png](https://images.zenhubusercontent.com/6078d2c0ad8d06f8a157185c/370a2a6f-7f18-4e9d-95f2-6dbdb85b6c3a)
