### ISSUE TITLE
[0.9.1.0 beta staging-1816]Music no longer playing 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18888]
Music track seems to be missing or not playing in staging

**Comment by IcedForge** [comment]
There is no bird chirping sound when starting the game in ENG localization but seems to be working in all of the other ones as well.

**Comment by WeaselDog** [comment]
Music stops a lot in 9.0 as well.

**Comment by Quadbro** [comment]
Just got a few local builds after some audio changes in 9.1... All the ambiences and music works perfectly. I even made a long runs, all works. There can be a problem on build machine with soundbanks transfer.

**Comment by Quadbro** [comment]
@IcedForge Can you provide more detailed info?)

**Comment by IcedForge** [comment]
Staging-1816
Eng Localization - No birds chirping, only plays ambience truck / town sound in main menu
i switch over to french ( restart )
FR Localization - Now i have birds chirping starting the game
Switch over to german ( restart ) 
GER Localization - I still hear bird noises when starting the game
Switch back to english ( restart ) 
ENG Localization - No bird noises on launching client
This was happening every time guaranteed.
Seems to be fixed in latest Staging build though.

**Comment by SlayksWood** [comment]
I guess we can close this one for 9.1 at least it is not regular and we will investigate it more in new develop builds.
