### ISSUE TITLE
Extensive Chat Logging

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18886]
Features:
- Files exclusively with chat logs for every day in server time (not game time), optionally by channel and for direct messages
- Profanity Filter does not affect the chat logs for administrative review

https://github.com/StrangeLoopGames/Eco/pull/7019

**Comment by WeaselDog** [comment]
We need to change log file to .log from .txt before we can close this.

**Comment by IcedForge** [comment]
Still in .log form and not .txt form
![Screenshot_65.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c787941e-2617-40a7-b671-14bf62122757)
