### ISSUE TITLE
[0.9.1 staging-1820] Game is broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18887]
Step to reproduce:
- start server
- connect to it:
![image](https://user-images.githubusercontent.com/45708377/96995644-2e5a8180-1537-11eb-8b74-ebe9e7656834.png)
- I don't have any UI and can't move
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5429002/Player.log)

**Comment by redwyre** [comment]
I'm guessing this is the issue:
```
