### ISSUE TITLE
Game crashes when joining Steam friend's game [Linux]

### ISSUE THREAD

**Issue by clay53** [StrangeLoopGames/EcoIssues#18898]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5433452/Player.log)

**Comment by redwyre** [comment]
Does this happen with just your friends game, or any game you join?

Have a look here and see if anything helps: https://linuxconfig.org/install-and-test-vulkan-on-linux

Also you could try reducing your graphics options before joining to see if that helps too.

**Comment by clay53** [comment]
Any game. I already have Vulkan installed (checked to make sure - I have an RTX 2060 so it's definitely supported). Reducing graphics settings didn't help.

**Comment by antaeusdk** [comment]
I can verify this issue.

https://github.com/StrangeLoopGames/EcoIssues/issues/18487

**Comment by SlayksWood** [comment]
We had  some fixes to join a friend to the game in Steam.
@antaeusdk @clay53 Can you check it?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
