### ISSUE TITLE
USER ISSUE: Modules

### ISSUE THREAD

**Issue by TimoGiese** [StrangeLoopGames/EcoIssues#18890]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
put module in the stone crushing thing

**Expected behavior:**
should reduce the cost

**Actual behavior:**
does not change a thing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I dont think so, this game has mods?

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended. Recipes with a yellow border only get the crafting time reduced.
