### ISSUE TITLE
[0.9.0.5] Abuse - Prevent Play Action with Pay

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#18894]
With this law and server configuration which disallow play prevent, we still can prvent play.

![unknown](https://user-images.githubusercontent.com/7646137/97061443-2f230000-1597-11eb-9cb8-8ea64c69e69d.png)

Fix is to add action Pay_LegalAction in file LawSection.cs (line 194)
I can make a Pull Request (I'm Dev Tier)

**Comment by Thibault-Brocheton** [comment]
Looks like any conditional in the Then still allows to prevent Play action
![image](https://user-images.githubusercontent.com/7646137/97062054-80cc8a00-1599-11eb-9b93-3fa8957f9380.png)

**Comment by WeaselDog** [comment]
Thank you so much for finding this issue. As a Dev Tier player, you are welcome to submit PR.

**Comment by johnkslg** [comment]
Fixed 
![Uploading image.png…]()
