### ISSUE TITLE
[0.9.1.0 bs-1820] Can't do anything in a new world

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18896]
Tried 0.9.1, created a new world, and then when it loaded this is what I was greeted with:

![image](https://user-images.githubusercontent.com/964559/97063108-bef28b00-1552-11eb-8210-6402a18d39be.png)

No character creation, no UI, no nothing. I can look around, but that's about it.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5432174/Player.log)

**Comment by SlayksWood** [comment]
dup #18887
