### ISSUE TITLE
Disable 'Populating WWise Picker' in startup

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18899]
Even with AutoPopulate off, this is wasting time in startup of Unity for everyone. Find a way to disable it by default.
Here's a link on it: https://www.audiokinetic.com/qa/5165/unity-keeps-getting-stuck-on-populating-wwise-picker

**Comment by Quadbro** [comment]
Yeah, in new unity versions Populating is triggered on enable, disabled it, hope it wouldn't break anything)) It shouln't, tbh
