### ISSUE TITLE
unity-crash few minutes into the game (shader unsupported; JDShippingContainerObject/Item not disabled)

### ISSUE THREAD

**Issue by halo7921** [StrangeLoopGames/EcoIssues#18902]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5434861/output_log.txt)

my setup:

i5-4430 3 GHz
16GB RAM
AMD Radeon R9 200 series
Win10

drivers are updated

since the 9.0 update the game crashes a few minutes into a session. During the betaphase the game worked often as supposed in singleplayer but not mp

**Comment by halo7921** [comment]
![Unity-Crash](https://user-images.githubusercontent.com/73431453/97111142-656a9780-16dd-11eb-8f6b-5b7b7c88c882.png)

**Comment by redwyre** [comment]
Can you try without mods?

**Comment by halo7921** [comment]
same without mods

**Comment by IcedForge** [comment]
@halo7921
Output log seems to point towards an older unity version then current player log is using?

Initialize engine version: 2018.3.12f1 (8afd630d1f5b)
vs
Initialize engine version: 2019.4.9f1 (50fe8a171dd9)

Could you provide a fresh player log after reinstalling?
Would also point out that your cpu specification is just below minimum requirements
which for Intel is Intel i5-6500 3.2 GHz Quad-Core.

**Comment by halo7921** [comment]
my bad, thought the output_log is from the latest crash

ok, it's time for some new parts... (worked fine with eco 7.x and 8.x)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5448596/Player.log)

**Comment by IcedForge** [comment]
Unfortunately this runs into the issue of not having enough memory to process will close this issue now.
