### ISSUE TITLE
Voice chat choppy and cutting off

### ISSUE THREAD

**Issue by SomethiNotGreat** [StrangeLoopGames/EcoIssues#18903]
Hey so im playing on Oculus Quest if that helps. So when i go into any server everything is normal exept for the voice chat, so when someone talks its incredibly choppy and when someone talks the connectivity keeps cuts in and out, i can barely make out what people are saying. and idk if its only me but ive turned on and off certain settings and it doesnt fix anything (i have auto update on so im most likely on the latest verson but its been happening even after updating the game) and one more thing to point out is that i have perfectly fine internet

**Comment by IcedForge** [comment]
@SomethiNotGreat Thank you for reporting.
Could you add your pc specifications and does this happen regardless of distance to players ( radius )?
Or does this occur when close to another player as well?

**Comment by SomethiNotGreat** [comment]
I am using on Oculus Quest (Non Link) and it does happen regardless of player distance and something ive found out is if it me and one other person only then is the voice chat not choppy and cutting off

**Comment by IcedForge** [comment]
Hello again, with the recent changes in 9.2 as well as 9.3 now i would like to check in for an update and see if you are still experiencing this issue?
