### ISSUE TITLE
Cannot create Scrolls

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18905]
> Small bug happening on a multiplayer hosted game where you can create the carpentry skill book but when you right-click the scroll doesn't appear anywhere.
> 
> The game says at the top of the screen that it has created a crafting skill scroll, but it doesn't actually get created. Right-clicking the book repeats the message that the scroll has been created, but it never appears or shows up in the inventory.
> 
> Restarting the game clients and server did not resolve the issue. Using the book on either client has the same result.
> 
> We can't really progress in the game without carpentry, so hopefully this can be resolved soon.

**Comment by IcedForge** [comment]
Would need logs and confirmation that this is not a modded issue, have not seen any other reports of this issue so it is either very unique or an outside source aka mods and or editing causing this?

**Comment by IcedForge** [comment]
Will close this due to lack of follow up information will reopen if i get some more information on this.
