### ISSUE TITLE
[0.9.0.5 beta release-100] Store Owned by Title Crashes Server When Title Unfilled

### ISSUE THREAD

**Issue by Hitman82a** [StrangeLoopGames/EcoIssues#18904]
Player in server government made a title called Bookeeper. The player was the elected title holder, and the title made so that the position would be vacated if titleholder went inactive. A Government store was set up with the Bookeeper as owner so that the title could change hands without impacting the store. The titleholder went inactive and was automatically removed from the title, so Bookeeper was held by no one. When anyone buys an item from the store owned by Bookeeper (and no one holding the title), the server crashes. Every single time. We removed the store to solve that particular issue.

**Comment by SlayksWood** [comment]
hard to reproduce in 9.1, but I guess the crash should be. check it after fix this one #18530

**Comment by johnkslg** [comment]
@Hitman82a awesome find

**Comment by D3nnis3n** [comment]
@Hitman82a If you do have a SLG account and want a little reward, send me an e-mail to dennis@strangeloopgames.com with your SLG ID :)
