### ISSUE TITLE
[0.9.1 staging-1823] Control buttons texture is bad.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18907]
![image](https://user-images.githubusercontent.com/45708377/97144382-63ecae00-1775-11eb-814f-88bc4e1e5462.png)

**Comment by IcedForge** [comment]
Related changes came from #18643 and leaving it here as this is the current issue.

**Comment by tuha263** [comment]
Seem it's gone without any code change. I will tag it with not reproduced

**Comment by IcedForge** [comment]
@SlayksWood Take a look when you are on to verify on 1827, it solved itself for me and you can probably close it if its working.

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/97673427-d246ae80-1a9c-11eb-8915-6d967068bf3c.png)
We have old issue with bars in this menu too, in some position we have this:
![image](https://user-images.githubusercontent.com/45708377/97673479-e5597e80-1a9c-11eb-8b1d-acf59d4475f9.png)
It may be related< but I can't find issue with bars

**Comment by WeaselDog** [comment]
I also can't reproduce this. Could it be something with your settings?
![ControlSetting](https://user-images.githubusercontent.com/47330823/97790566-cfc08380-1b86-11eb-826c-e462493aa93a.png)
![VolumeSettings](https://user-images.githubusercontent.com/47330823/97790568-d222dd80-1b86-11eb-96cf-a0f4cd38c591.png)
