### ISSUE TITLE
USER ISSUE: can't switch from Land Claim Stake after claiming & dropping

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#18913]
\
**Version:** 0.9.1.0 beta staging-1823

**Steps to Reproduce:**
1. I made a law forbidding the drop of tailings on unowned terrain
2. I took a tailing into my hands
3. I used a land claim stake to claim area
4. when I claimed the area, the tailing got dropped too
5. I now can't switch away from my land claim stake

**Expected behavior:**
I should be able to switch to another item in my toolbar

**Actual behavior:**
I can't switch to another Item in my toolbar. After sending this bug report, it worked again.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5438551/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5438552/Player-prev.log)

**Comment by IcedForge** [comment]
NullReferenceException: Object reference not set to an instance of an object.
  at UI.SelectionInventoryUI.SendCantSelectMessage (System.Int32 i) [0x00000] in <00000000000000000000000000000000>:0 
  at UI.SelectionInventoryUI.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

Is the exception thrown.
This is the result of missing a shovel type item in your inventory, as it is trying to find one to switch to and until you add a shovel in your toolbar you will keep getting the exception when trying to use any tool.
