### ISSUE TITLE
Flat Steel Window/Floor don´t connect correct

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18919]
![grafik](https://user-images.githubusercontent.com/37456949/97213686-3bd76c00-17c2-11eb-9ea2-8ad3baa5efb5.png)
![grafik](https://user-images.githubusercontent.com/37456949/97213953-a2f52080-17c2-11eb-91bd-e04ab627ab95.png)

Windows don´t connect

**Comment by SlayksWood** [comment]
And maybe change connetion for Flat Steel Floor block in height too? 
![image](https://user-images.githubusercontent.com/45708377/97301410-cb375a80-1868-11eb-8365-53a44e9aa6f5.png)
like in length:
![image](https://user-images.githubusercontent.com/45708377/97301549-f457eb00-1868-11eb-946b-f455785d1a55.png)

**Comment by RobertMangano** [comment]
windows aren't supposed to connect at a T intersection

**Comment by keegan-o** [comment]
checked in updated flat steel meshes to staging, in the middle of other testing so will test tomorrow.
