### ISSUE TITLE
[0.9.1 staging-1823] Can't place Stone/Dirt Ramp

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18914]
I have highlight, but can't place it, and I also don't have any hint.
![image](https://user-images.githubusercontent.com/45708377/97168800-1d5d7a80-179a-11eb-8086-009b6d0df395.png)

**Comment by WeaselDog** [comment]
Related to https://github.com/StrangeLoopGames/Eco/pull/6972
