### ISSUE TITLE
playtest world not auto updating correctly

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18918]
playtest world auto updated to weird version
Eco Server 0.9.0.5 beta release-100

currently being manually updated.

Probabaly need regex that only allows staging versions

**Comment by denysaw** [comment]
Seems there was some wrong version in the cloud (or where CW API retrieves it), so probably one-timer, but for now I've filtered by `release` word. Hotfixed on Prod also.
