### ISSUE TITLE
Fix default minimap icons to a limited set

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18920]
![image](https://user-images.githubusercontent.com/3536496/97215183-5d643380-1781-11eb-8e7d-492072ee0ae6.png)
Shouldnt show all this nutiness.  

We can make some icons show only when we belong to them, have radio button for show all, show mine, and dont show. Campsite and basic tables should be 'show mine'.

**Comment by TwixterZ** [comment]
Fix Tested and confirmed as of 9.5 Develop 297
