### ISSUE TITLE
restartBrokenWorlds not working

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#18921]
In prod db, Theres some cloud worlds without serverid or server url.
/restartBrokenWorlds
but they were not updated.

The worlds are not online either.

maybe update /restartBrokenWorlds to start a new world by same name if world is not online.

fyi, i manually fixed the prod cws

**Comment by denysaw** [comment]
`maybe update /restartBrokenWorlds to start a new world by same name if world is not online.`

Nah, it would be rejected cuzz of aws_name doubling. It should be able to restart.

**Comment by denysaw** [comment]
Yeah, your truth. It worked for the case, when there is world instance, but fail-started. And when there was totally no that instance, CW API returns error:
![image](https://user-images.githubusercontent.com/5720101/97295255-599ee280-184f-11eb-84ed-e430a0451ce6.png)

I used your @j3fffff world for the test (it was off anyway):
![image](https://user-images.githubusercontent.com/5720101/97295320-6a4f5880-184f-11eb-8fc6-5534af7f9629.png)

So I've improved verbosity and added condition, so when I'm getting `Object reference not set to an instance of an object.` error on CW API `/restart`, I'm doing `/start` to that world instead. Tested on your world and seems worx as a charm.
Please, test right on Prod.
