### ISSUE TITLE
[0.9.0.5 br-100] Corporate store has issues seeing items

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18932]
Playing on WT currently and our shared corporate store has some issues (as mentioned in #18931). I'm guessing it has some issues with inventory linking due to stockpiles changing, etc:

![image](https://user-images.githubusercontent.com/964559/97244605-628fa580-17b6-11eb-8440-7409e93808a9.png)

I tried linking inventories to it, didn't help, someone else tried re-linking inventories and re-listing items, that didn't help. We haven;t tried everyone yet, but things are a bit weird.

It might have something to do with corp ownership of the store and the area:
![image](https://user-images.githubusercontent.com/964559/97244800-d8940c80-17b6-11eb-9bef-c57b0aacf02d.png)

**Comment by ThePiachu** [comment]
Oh yeah, turns out it was due to the store ownership - apparently only the store owner can link inventories, and corps aren't people that can do the linking, so womp womp

![image](https://user-images.githubusercontent.com/964559/97245062-72f45000-17b7-11eb-8590-56f12de45831.png)

**Comment by SlayksWood** [comment]
dup #18530
