### ISSUE TITLE
[0.9.1 staging-1823] Some new forms have wrong sound when place them.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18939]
- [x] Corrugated Steel: DoubleWindow, Fence, RoofCube, RoofPeakSet, RoofPeak, RoofCorner, RoofTurn, RoofSide.
Should be metal sound like all others Corrugated Steel Forms.

- [x] Flat Steel: RoofCube, RoofPeakSet, RoofPeak, RoofCorner, RoofTurn, RoofSide.

**Comment by Sekor2600** [comment]
Fixed in Develop SVN
