### ISSUE TITLE
"Fuel Remaining" UI changes wildly while crafting

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#1893]
![image](https://user-images.githubusercontent.com/6262198/29436790-3de8feca-8362-11e7-8b9c-35eb4727de91.png)

The value here is jumping back and forth by +/- 20 minutes

**Comment by MarjieAVolk** [comment]
I've seen it fluctuating back and forth by 1-2 seconds a lot as well.
