### ISSUE TITLE
Add High Res Icons for use ingame with signs/stores

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18934]
This is not very pretty when you get closer, would it be possible to get high res variants instead to be used ingame for these things?

![Screenshot_21.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/5a6617e1-5996-495d-87b6-153e12462f70)

**Comment by SlayksWood** [comment]
@serpopov Shadow is wrong too.

**Comment by WeaselDog** [comment]
Added in 9.5
