### ISSUE TITLE
client perf - many animals kills perf

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1894]
![image](https://user-images.githubusercontent.com/3150561/29437035-5cfc8f6a-8363-11e7-8b1d-9d52e9f45f32.png)

this isn't a common ecosystem state, but there might be some easy perf gains to be had profiling what is so slow.

**Comment by SeanAtr0n** [comment]
Looks like a big chunk is physics, could improve by using a simplified rigidbody/collider while animals are alive
