### ISSUE TITLE
USER ISSUE: Ashler block chimney and cement kiln

### ISSUE THREAD

**Issue by rodneymillerpca** [StrangeLoopGames/EcoIssues#18942]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
Place Ashler chimney block in roof or floor above cement kiln.

**Expected behavior:**
Chimney block should act like chimney pipe.

**Actual behavior:**
Cement kiln says it is blocked. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting.
Chimneys do not act as a pipe object and cannot be used as an exhaust method.
This is related to #13561 if you want to track it further.
