### ISSUE TITLE
Create lag detection system

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18944]
Building on the diagnostic system in #18943, add a lag detection system to the diagnostics that will allow release servers to identify lag sources. Create a design for how this will work.

Will require some research to determine the best way to implement it, some thoughts:
- We can add a diagnostic detection to every worker thread, and set times on each for what is 'out of bounds' in terms of timing. If it's detected taking longer than that, it will log a diagnostic warning, attaching a classtack from during the lag.

**Comment by redwyre** [comment]
This kind of stuff I had hope to build into PerformanceManager/PerformanceCounters

**Comment by johnkslg** [comment]
Merging to https://github.com/StrangeLoopGames/EcoIssues/issues/19560
