### ISSUE TITLE
Webserver voting mechanic

### ISSUE THREAD

**Issue by gatekeeper258** [StrangeLoopGames/EcoIssues#18954]
I created a draft of the president, was able to go to the weblink and vote for it. Later that day going back to the webpage when I click on the link of the vote the page is blank. Same for another player who hasnt even voted yet. 
![explorer_n1cEasDwRb](https://user-images.githubusercontent.com/6466146/97366373-997cbe80-187d-11eb-84a2-3d0b110fc992.png)

**Comment by SlayksWood** [comment]
As far as I can see, player is not login:
![image](https://user-images.githubusercontent.com/45708377/97530758-d94dbe00-19c3-11eb-877d-d2953cdc4317.png)
@gatekeeper258  Thank you for the report and Can you provide any additional information?
1. Do you still have problem? try to restart sever and try again.
2. Give IP address or ID to connect to your server and checking it by ourself. If you don't want to make it public, you can write me in Discord Kirill (Slayks)#6251 or e-mail kirill@strangeloopgames.com. I tried to connect by IP from the screenshot but couldn't.
2. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by gatekeeper258** [comment]
sorry that was due ro using the browser while not logged into the game at the same time. please close issue my bad.
