### ISSUE TITLE
Toll Object can't be picked up by Hammer or Smote by dev tool once placed

### ISSUE THREAD

**Issue by FyreAus** [StrangeLoopGames/EcoIssues#18950]
Because of Interaction order {Target, Selected Item, Block, Carried} and the **Toll Object** having both a Left and Right mouse click interaction, the Toll object can't be picked-up or removed by the dev-tool.

This isn't really an issue for in game as the Toll Object is (currently) an example object for the Auto Generation of World Object component UI (can we get a bool prop view? ).

**If** there is no intention to bring the Toll Object into the game, it would be good to leave this behavior, but clearly indicate in the file with a comment what effect overriding the left click interaction on a world object (Blocking tool use) will do, and that this behavior is probably undesirable .

**Comment by WeaselDog** [comment]
Hi. Thank you for your feedback. The toll object is not currently implemented. It is for internal testing purposes and is only available by going through files or using a dev command. We have restricted access to developer commands as they have potential to break the game.  We will figure this out when it is time to implement the object.
