### ISSUE TITLE
Change deeds to be non-contiguous

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18952]
- [x] When adding a plot that is non contiguous, if there's a nearby deed owned by the user pop up a notification 'This plot is not connected to <X>, do you want to start a new deed for it?'
- [ ] When removing a plot, pop up a dialog 'This will split the plots on <X> into <Y> properties, create a new deed / new deeds?  Watch out for removing a plot that creates 2 or 3 additional deeds and handle appropriately.
- [ ] Create a migration process that splits out all non-contiguous deeds on load with duplicate settings.

**Comment by johnkslg** [comment]
Need this for 9.2

**Comment by IcedForge** [comment]
Escalating this from medium to high, the migration part of this is critical to function properly 
It is also not saving deed permissions on claim splitting either.

**Comment by gzatravkin** [comment]
I see reopen, what exactly don't worked at test?  It don't creates deeds after splitting?

**Comment by gzatravkin** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/7532

**Comment by IcedForge** [comment]
Separated issues for 
1. Migration issue of permission not being inherited from parent/original plot 
https://github.com/StrangeLoopGames/EcoIssues/issues/19903

2.Optimization issue from deleting larger plots causing empty plot entries (can be viewed by deleting larger areas and check real estate desk)
https://github.com/StrangeLoopGames/EcoIssues/issues/19925
![Screenshot_24.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/fdd16228-de0d-4f64-adcd-e24d7978bda0)

**Comment by gzatravkin** [comment]
So, this one can be closed? Since there are 2 different issues to track it.

**Comment by gzatravkin** [comment]
@IcedForge
