### ISSUE TITLE
[client] [0.9.1.0 beta staging-1826] Ecopedia menu bag

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#18968]
if you collapse all menu, then when you use the link, the active section's frame moves to where the menu item should be in the expanded form, but the menu itself does not expand

![2020-10-09](https://user-images.githubusercontent.com/26339332/97490730-4afd1c00-1972-11eb-9787-cfbda7f2524e.png)

**Comment by SlayksWood** [comment]
merged to #18966
