### ISSUE TITLE
USER ISSUE: Throws from the server every 10-15 minutes

### ISSUE THREAD

**Issue by NuFun2007** [StrangeLoopGames/EcoIssues#18962]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Play on a server with a friend

**Expected behavior:**
Does not throw from the server

**Actual behavior:**
Throws from the server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are no modifications.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by NuFun2007** [comment]
My logs
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5453024/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5453033/Player-prev.log)
Logs of my friend who came to my server
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5453070/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5453071/Player-prev.log)

**Comment by SlayksWood** [comment]
@NuFun2007 Thank you for the report and sorry for waiting. You have a lot of exceptions in the log and most likely the crash is related to them.
Need to have some tests:
1. Try to use English version to play with your friends.
2. Try to play on any other russian server.
3. Provide your PC specification (including Operation System)

And provide logs again.

**Comment by SlayksWood** [comment]
Closed for now. Reopen if you will still have this problem.
we changed infinity symbol (u221E) in russian localization which cause a lot of spam in log file.
