### ISSUE TITLE
Crafting didn't auto-take from a finished recipie

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1896]
Cooked some Bison then CamasMash, bison finished and then the CamasMash was stuck waiting for lard.

It didn't start until I Unchecked/rechecked my storage chest. (was the first time i fiddled w/ the checkbox but it was clearly checked, maybe that is out of sync)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1715 -- coincidentally I am fixing this in https://github.com/StrangeLoopGames/Eco/pull/1675
