### ISSUE TITLE
Vehicles can disappear once out of view, or logging out/back in.

### ISSUE THREAD

**Issue by Homeblest** [StrangeLoopGames/EcoIssues#18979]
It seems that, once out of view, vehicles (carts, trucks, etc...) will randomly change their location on the Y axis. 

I park my steam truck routinely just above a mine shaft I've created, and it just sometimes clips into the ground or on the garage roof. Usually this happens when I log out and back in, but it can happen once the vehicle is out of view. My friends have also had this issue.
![image](https://user-images.githubusercontent.com/5695473/97554695-0784cb00-19cf-11eb-9266-af84b0900bfb.png)

Can this be solved by storing the rotation/position of the vehicle, and moving them to the right location if they suddenly clip out somewhere?

**Comment by SlayksWood** [comment]
Thank you for the report.
merged to #15688
