### ISSUE TITLE
Composite Joshua Door missing unique look

### ISSUE THREAD

**Issue by Metamess** [StrangeLoopGames/EcoIssues#18972]
In Eco 0.9.0.5 every tree type has it's own type of Composite Lumber, each with their own unique coloring. These unique looks extend into the Composite Lumber items, such as tables, chairs and doors. However, the unique look for the Composite Joshua Door seems to be missing, as it has the exact same appearance as the (type-neutral) Composite Hardwood Door.

![image](https://user-images.githubusercontent.com/2466330/97507740-24dd7900-197e-11eb-9e3d-4d75c5379e16.png)
In this image, a Composite Hardwood Door (left) is shown next to a Composite Joshua Door (right) against a Composite Joshua Lumber background. 

This implies the Composite Joshua door is either missing implementation, or perhaps it has an erroneous index value for the array of Composite Door textures.

**Comment by SlayksWood** [comment]
Don't have this issue in staging-1826:
![image](https://user-images.githubusercontent.com/45708377/97529750-9d195e00-19c1-11eb-8869-a82d7b3190a2.png)
But this door is unique and I exactly checked it. There is one stupid idea if it's not your door someone could rename door:
![image](https://user-images.githubusercontent.com/45708377/97529934-1618b580-19c2-11eb-8bb9-eb345e7f329d.png)
In any case, If we had issue, then it was fixed. closed

**Comment by Metamess** [comment]
@SlayksWood Thank you for your quick response! It is good to see that the issue might be fixed. Just for any potential future reference, I would like to add the following information:

First, there was no accidental, misleading renaming going on. I have set up the scene in the screenshot myself, specifically for the purposes of reporting this issue. As you can also see (if you look very closely) the door I am hovering over does have the icon for the Composite Joshua Door. 

I have confirmed that other players on my server also see the two door types as visually identical. This persists over both client and server restarts, and affects all Composite Joshua Doors on our server. We do not run any mods. Should this issue pop up elsewhere I hope this additional information can be of help.
