### ISSUE TITLE
Generators' fuel supply don't appear in storage link

### ISSUE THREAD

**Issue by Mogdu** [StrangeLoopGames/EcoIssues#1897]
Generators' fuel supply is a bit custom, and for that they can't be seen in the storage tab. 
Meaning you can't auto refuel generators. One need to log back in, and carry the fuel to it. When it would be much easier to have a pumpjack > refinery > generator loop that would auto produce.

The issue is the same in 0.5.6.1 and 0.6.

**Comment by MarjieAVolk** [comment]
It looks to me like all the generators use regular FuelSupplyComponents, which should show up normally.  So no idea what's up here.

**Comment by craig-jong** [comment]
Probably because they don't have link components? It's just a guess because I'm not 100% sure how linked inventories function, but I'll look into this.

**Comment by MarjieAVolk** [comment]
Oh they don't?  Yeah, that would do it

**Comment by MarjieAVolk** [comment]
We should probably have StorageComponent require LinkComponent

**Comment by MarjieAVolk** [comment]
Fixed in PR above ^
