### ISSUE TITLE
[0.9.1.0 beta staging-1827]Elevator call post: Deconstruct clearance usage is limited to buttons, not the entire object.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18985]
Can only deconstruct with hammer by directly hitting clickable buttons not the entire object.
![Screenshot_26.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/89dd6081-9dea-4342-84df-1c874fbb704d)

Changes to art from #18707 is the culprit as it was previously only the buttons and nothing else so it needs to be adjusted to its size.

**Comment by Sekor2600** [comment]
fixed in Staging SVN
