### ISSUE TITLE
Trees growing in chests

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1898]
I believe trees shouldn't be able to grow inside world objects.  Is this an occupancy problem?  I know the chest was weird before.

**Comment by Nanders** [comment]
I'm having trouble recreating this issue

**Comment by MarjieAVolk** [comment]
Yeah it's probably hard to repro - but Repose had it going on on his land, on Marmot.  He's over the the west of us.

**Comment by Nanders** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1732

**Comment by MarjieAVolk** [comment]
Aha, I thought that one had been closed by Sean's tree changes

**Comment by SeanAtr0n** [comment]
Looks like there might not be any code that checks for occupancy while spawning plants

**Comment by Nanders** [comment]
Where should we check that? Within SpawnPlant()?

**Comment by SeanAtr0n** [comment]
I'll look into it, guess there isn't any way to quickly determine if the top block is occupied anymore. We probably need to add a new way to quickly look that up.
