### ISSUE TITLE
[0.9.1.0 beta staging-1828] Inventory tooltips on previous positions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18995]
When i enter an inventory, i move an item to another slot the tooltip is still accessible from their original position until i clear cache
![Screenshot_45.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0f0e3690-9ae5-4e23-aede-970ce1d4695e)

**Comment by SlayksWood** [comment]
merged to #9344
