### ISSUE TITLE
All Water is Polluted on New World [Develop Branch]

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#18990]
![image](https://user-images.githubusercontent.com/14983165/97641615-8a724980-1a00-11eb-9932-3baf75b973de.png)

All the water appears to be the polluted brown color on a freshly generated world, happening in **Develop branch** last week of October 2020.

**Comment by MazonDel** [comment]
This appears to be happening because currently the WorldLayerLandscape.cs gets nothing back from the WorldLayerManager when it RequestLayer() is called because the relevant code was removed through a combination of deletion and commenting. Fix investigation underway.
