### ISSUE TITLE
Ecko Statue is back to being an easy find again

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#18991]
\
**Version:** 0.9.0.5 beta release-100

open up Ecopedia scroll down left side to **Reference** 
Choose section **Housing Objects**  
under the **Tags Applying to:**  Hover Mouse over **Housing**
scroll down till you see **Ecko Statue**
now hover mouse over **Ecko statue** and this will show information about it
now highlight **Ecko Statue** in this window and you will get World Co-ordinates
![snap7520](https://user-images.githubusercontent.com/29383891/97654067-12d10880-1a5a-11eb-94ce-0f94cb6f6dd3.png)

![snap7521](https://user-images.githubusercontent.com/29383891/97654733-832c5980-1a5b-11eb-8650-a889d75b3386.png)

![snap7522](https://user-images.githubusercontent.com/29383891/97654856-bcfd6000-1a5b-11eb-9d90-643192779be0.png)

![snap7524](https://user-images.githubusercontent.com/29383891/97656629-c5579a00-1a5f-11eb-94d4-76225293ef75.png)

You Still cannot Type **Ecko Statue** into Chat to find it, so that part still works

**Comment by WeaselDog** [comment]
Thanks for letting us know. It is already fixed for next update, and we are tracking it internally here: https://github.com/StrangeLoopGames/Eco/issues/7082
