### ISSUE TITLE
[0.9.0.5] Opening ECOPedia category puts the highlight cursor in a wrong position

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19006]
I came across this usually when I search for things in ECOPedia. I type in a search, click on the proper category, and then see this:

![image](https://user-images.githubusercontent.com/964559/97776390-b7b81800-1b24-11eb-84e7-95af545d3bc1.png)

The little selector is partially off the selection. Everything works normally, it's just a tiny visual glitch.

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/18966

**Comment by SlayksWood** [comment]
merged to #18966
