### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by QCsmaz** [StrangeLoopGames/EcoIssues#19008]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Informations de connexion invalides.

<size=60,00%>User doesn't have any assigned products</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
you enter the incorrect username or password.
