### ISSUE TITLE
[0.9.1.0 beta staging-1829] error in save crowdin defaultstrings.csv string 2711

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19001]
"{0} = Value and name of currency - contract payment {1} = Value and name of currency - tax on contract payment","{0} ({1}) to retain from contractor on completion","","{0} ({1}) à taxer au contractant à l'achèvement","{0} ({1}) to retain from contractor on completion","{0}({1}) nach Fertigstellung an Auftragnehmer auszuzahlen","완료 시 계약자로부터 {0} ({1}) 유지","{0} ({1}) a ser retido do contratado na conclusão","{0}（将在完成后，从承包人处收取 {1} 的税金）","{0} ({1}) будет удержано с исполнителя по завершению","{0} ({1}) per trattenere da contraenti al completamento","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","完了時に {0} ({1}) を請負人から徴収","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) буде утриманого з підрядника по завершенню","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) to retain from contractor on completion","{0} ({1}) tamamlandığında müteahhitten alınacak"

![2711](https://user-images.githubusercontent.com/26339332/97775516-5f0f6c00-1b72-11eb-80f9-f3b86130e06a.png)
![crowdin](https://user-images.githubusercontent.com/26339332/97775518-620a5c80-1b72-11eb-9114-079d5a4d0254.png)

**context parameter on crowdin writes in first value of strings 2711 and localization not work in game**

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/110438081-1c811180-80c7-11eb-83c1-2797e0ac086c.png)
