### ISSUE TITLE
USER ISSUE: Not Getting Land Expansion Papers

### ISSUE THREAD

**Issue by Tudorhc5** [StrangeLoopGames/EcoIssues#19009]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Start game (with tutorial)
2. Fill your starter camp inventory
3. Reach the land expansion mission
4. You will see you have no papers

**Expected behavior:**
add a temporary slot for the papers, or delete a low need item to place the quest item	

**Actual behavior:**
doesnt add the expansion papers to the camp inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Tudorhc5 Thank you for the report. I don't understand your problem, Can you provide more information with screenshots or maybe video?
Also provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
When placing the tent down it should claim a 2x2 area, and adding 6 claim papers into the inventory of the campsite, you should  not receive any other papers except from research?
Is this an issue with description or localization translation being misleading?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
