### ISSUE TITLE
[0.9.0.5 br-100] Going into a truck with a mining drill can make you hold it still when inside in third person

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19002]
![image](https://user-images.githubusercontent.com/964559/97776150-12507480-1b23-11eb-9be4-5794f2fbcbff.png)

Was fooling about on WT with a bit of lag. Had the drill out, entered a vehicle and then this happened.

**Comment by SlayksWood** [comment]
merged to #12829
