### ISSUE TITLE
Apostraphe in Localizer breaks chat and tooltip icons

### ISSUE THREAD

**Issue by JamesTalon** [StrangeLoopGames/EcoIssues#19010]
Version: 9.0.5
Reproduction: Have the various Localizer fields in an item file and the LocDisplayName field contain an apostrophe for the item (included a before and after pair of files where this occurs)
[Apostrophe icon example.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5469647/Apostrophe.icon.example.zip)

What happens, in essence, is the item shows up perfectly fine on the crafting table (Cast Iron Stove in this case) but tooltips and chat show nothing but a blue square and don't load the actual icon itself. This was like introduced in 9.x, as it was working when I was running an 8.x server

**Comment by IcedForge** [comment]
Is this some odd formatting change that caused this?
![Screenshot_22.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/290e5c79-b441-464d-b634-13bf86022f2c)

**Comment by mirasrael** [comment]
Guess it is single-quote. It happens because way how attribute parser currently implemented (should be easy to fix). It makes something like <ecoicon name="Fish n' Chips"/> but then regex looks for `["'](\w+)["']` which produces wrong output (Fish n)
