### ISSUE TITLE
[0.9.1.0 beta staging-1828]Civics: Trigger tooltip for Harvest or Hunt sub property

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19011]
Could change the tooltip for these 2 properties to clarify which is which.
![Screenshot_51.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/e5fd586e-e4aa-48ef-8b6d-20f31e2fbd27)
Destroying Organism "Was the plant or animal destroyed?"
Not Destroying Organism "Was the plant or animal damaged? ( injured? damage is better for trees but injured seems better for animals?)"

This is very confusing, why is both the same?
Also maybe change the name on "Not destroying Organism" into "Damage organism? as this is more user friendly.

**Comment by TwixterZ** [comment]
fix is checked and confirmed as of 9.4 Develop 267
