### ISSUE TITLE
USER ISSUE: Desert Sand coming in inventory as dirt

### ISSUE THREAD

**Issue by Tudorhc5** [StrangeLoopGames/EcoIssues#19029]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
1. Go to desert
2. Find Desert Sand
3. Dig With Shovel
4. Place Down (it will place as dirt)

**Expected behavior:**
It should give me either sand or desert sand	

**Actual behavior:**
it gives dirt

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
No, Desert Sand is Dirt block. To get sand you only have to dig Sand Block.
So it's intended behavior, closed for now.
