### ISSUE TITLE
USER issue - my crafting stations are still showing up in the public crafting stations even though they are not authorized for Everyone

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19026]
USER issue - my crafting stations are still showing up in the public crafting stations in the economy viewer even though they are not authorized for Everyone

staging - 1830

![image](https://user-images.githubusercontent.com/32143431/97812050-a9651b80-1c4c-11eb-8fb9-86b1635fcf92.png)

![image](https://user-images.githubusercontent.com/32143431/97812062-c00b7280-1c4c-11eb-8f3a-9b67a57bcdd2.png)

**Comment by SlayksWood** [comment]
@dmplatten 
@WeaselDog @johnkslg 
I do not even know if it is needed to be remade?
All tables on which you can craft are displayed here.

**Comment by IcedForge** [comment]
Maybe look into only showing not owned crafting stations? Instead of showing all crafting stations you have access to?

**Comment by WeaselDog** [comment]
Thanks for finding this. Yes, this should ignore tables you own unless they are public crafting tables.

**Comment by dmplatten** [comment]
You’re welcome:)

**Comment by SlayksWood** [comment]
Still an issue. I don't see my craft station if I own it and don't add Everyone to authorization, but If I add Everyone, I will see it in Public craft station.  Step to reproduce:
- place Masonry table and claim it, check Public Craft Stations:
- open Masonry table, authorization tab and add Everyone to it:
![image](https://user-images.githubusercontent.com/45708377/107922717-79ceea80-6f81-11eb-8fb3-f45c335b000a.png)
- check Public Craft Stations, now I have it in my Public Craft Stations:
![image](https://user-images.githubusercontent.com/45708377/107922959-d0d4bf80-6f81-11eb-8869-6e261a0a861a.png)

**Comment by Moritur** [comment]
@SlayksWood when fixing this issue I made it display all crafting stations that are placed on unowned land or authorized for 'everyone' demographic. This means that now it shows all the stations that anyone can access.
Isn't it the expected behavior? If it isn't then what crafting stations should be displayed?

Description and name of this issue imply that showing crafting stations authorized for 'everyone' is expected behavior
