### ISSUE TITLE
Plants are 100% grow but you can't see it only if take one

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1902]
if you pickup one all other will be shown perfect the same happen with beets

![grafik](https://user-images.githubusercontent.com/26040573/29485241-d25c36fe-84ce-11e7-9283-c469c23fb7f9.png)

**Comment by REPOSEECO** [comment]
![grafik](https://user-images.githubusercontent.com/26040573/29485284-a8293296-84cf-11e7-9490-16a675e196bc.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1406
