### ISSUE TITLE
USER issue - plant fiber image object is disconnected from its resource

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19025]
USER issue - plant fiber image object is disconnected from its resource

1. link 2 or 3 storage units to the workbench
2. open storage tab while at workbench
3. move stacks of items (plant fiber) from one storage unit to another
4. in some cases the stack is just an image and cannot be dragged anymore, and also the tooltip does not display the stack information
![Untitled](https://user-images.githubusercontent.com/32143431/97811869-68b8d280-1c4b-11eb-9f2f-85264074fb28.jpg)

**Comment by dmplatten** [comment]
staging - 1830

**Comment by SlayksWood** [comment]
should be fixed with https://github.com/StrangeLoopGames/Eco/pull/7094
will be available in release-105 or higher.
but still will investigate.

**Comment by IcedForge** [comment]
Should be fixed by aforementioned release. Please reopen if this is still something you experience.
