### ISSUE TITLE
Popup is not expanding vertically

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19022]
![image](https://user-images.githubusercontent.com/3536496/97811242-1321fd00-1c2e-11eb-8509-bd35bd6563a5.png)

This was working earlier, seems to have just broke
Reproed with /civics spawngov

**Comment by serpopov** [comment]
@SlayksWood is it actual?

**Comment by MrAnonymous110** [comment]
I tested and see that the popup is expandable vertically now, could you check again
![poup expand](https://user-images.githubusercontent.com/3883524/102359502-751ea200-3fe3-11eb-9da6-dbcd5246197d.gif)

**Comment by SlayksWood** [comment]
Seems fixed
