### ISSUE TITLE
9.1.0 1830 softwood/harwood Lumber chair says bench in description 

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19028]
WorldObjectItem<HardwoodLumberChairObject> 
    {
        public override LocString DisplayDescription => Localizer.DoStr("A sturdy lumber bench. It doesn't feel as wobbly as more basic wooden benches.");

        WorldObjectItem<SoftwoodLumberChairObject> 
    {
        public override LocString DisplayDescription => Localizer.DoStr("A sturdy lumber bench. It doesn't feel as wobbly as more basic wooden benches.");

        static SoftwoodLumberChairItem()

**Comment by WeaselDog** [comment]
Thanks for catching these! This will be updated in next patch.
