### ISSUE TITLE
Random Crashes with No Crashlogs (Seems Graphics Related)

### ISSUE THREAD

**Issue by cyberdragon442** [StrangeLoopGames/EcoIssues#19032]
I just got this game and was playing for a while (hours) on my friend's world just fine then started constantly crashing randomly after only a few minutes in the game with no crashlogs being generated.

It's reporting a ton of graphics errors in the player log though. I have my graphics settings turned all the way down (except for render scale which I have tried on 75 then lowered it and still kept crashing). I do not get any lag or noticeable effects before the crashes, just instant freeze then crash to desktop. 

Latest Log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5471955/Player.log)

Previous Log
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5471957/Player-prev.log)

**Comment by IcedForge** [comment]
@cyberdragon442 Thank you for your report.
Could you provide your pc specifications and or attach dxdiag.txt to help troubleshoot this issue.
Also have you tried setting your maximum fps lower?

**Comment by cyberdragon442** [comment]
Here's DxDiag

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5477865/DxDiag.txt)

I've set the max FPS to 60 but I'll try lower (30)

**Comment by redwyre** [comment]
We've made some changes in 9.1 which should help (out in the next day or two), let us know if you're still having issues then.

**Comment by IcedForge** [comment]
@cyberdragon442
Are you still having these issues?
If so let us know and if it is resolved you can close the ticket if you would like or ill close it in a few days if we dont hear back from you.

**Comment by SlayksWood** [comment]
Closed for now. Reopen it if you still have problems.
