### ISSUE TITLE
USER issue - Object tooltip description is sometimes wrong

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19035]
Object tooltip description is sometimes wrong

if i move the cursor from right to left, from an empty box to the huckleberries stack, it show the masonry table information instead of huckleberries information

staging - 1830

![image](https://user-images.githubusercontent.com/32143431/97825763-932b7f80-1c8d-11eb-8289-bbebffc53f62.png)

**Comment by SlayksWood** [comment]
related with #9344
