### ISSUE TITLE
[0.9.1 release-103] Logging: Wrong experience per hitting tree

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19039]
It should give you damage x 0,1 x XPmultiplier, but now it doesn't include damage and you always gain 0,1 x XPmultiplier.
Take specialty and hit tree with stone axe and then modern axe:
![image](https://user-images.githubusercontent.com/45708377/97875998-40ed6b80-1d2c-11eb-9fb6-47207c28736c.png)

**Comment by SlayksWood** [comment]
Now we have "Double" experience when chopping tree
So I have basic coefficient 0,1 + axe damage multiply on basic coefficient 0,1 myltiply on XPmultiplier
So I have 0,24 per one hit with stone Axe and logging level 1 instead of 0,14:
![image](https://user-images.githubusercontent.com/45708377/104560472-fc008200-5656-11eb-88c1-f6ad04bdaed2.png)

**Comment by TwixterZ** [comment]
Fix confirmed, tested on 9.4 develop 248,
