### ISSUE TITLE
SLG.com security threat: directories exposed

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#19038]
Security: Webserver files exposed
Message:    Hi, I had the following old (apparently stemming from the alpha time) link in my password manager to login: https://www.strangeloopgames.com/eco-account The webser exposes some of the files publicly or at least lists them. I think you might want to turn that off for security reasons. Maybe even add a forward to the current login page? Cheers Thomas

**Comment by D3nnis3n** [comment]
Confirmed fixed.

**Comment by denysaw** [comment]
@D3nnis3n Added redirect to play.eco.

**Comment by D3nnis3n** [comment]
Confirmed as well.
