### ISSUE TITLE
USER ISSUE: water not flowing.

### ISSUE THREAD

**Issue by arrakis09** [StrangeLoopGames/EcoIssues#19046]
\
**Version:** 0.9.0.5 beta release-100

**Steps to Reproduce:**
used a shovel to dig up sand on waters edge and the water doesn't flow.	

**Expected behavior:**
the water should have flown into the space i dug up to fill in to move water to locations for farming

**Actual behavior:**
instead the water just acted as if there was something blocking it and made a portal that you can walk into and start swimming.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no modds just base game

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
You must build an aqueduct to deliver water to the desired location. Use brick and select aqueduct form.
This is intended for now, but we plan to redo the water in the future. Therefore merged to #16648
