### ISSUE TITLE
Sign code using ecoicon has inconsistent results.

### ISSUE THREAD

**Issue by LadyNasse** [StrangeLoopGames/EcoIssues#19042]
Steps To Reproduce:
///Create a sign with various icon images.

///My two examples are...
///Sign code that works as expected:
< color=white>Available Furniture

*< ecoicon item='PlanterPotRoundItem'> *< ecoicon item='LimestoneOwlStatueItem'> *< ecoicon item='AshlarStoneDoorItem'>  < ecoicon item='BrazierItem'> *< ecoicon item='CeilingCandleItem'>

*< ecoicon item='BrickFireplaceItem'> *< ecoicon item='AshlarStoneChairItem'> *< ecoicon item='AshlarStoneBenchItem'> *< ecoicon item='AshlarStoneTableItem'> *< ecoicon item='AshlarLargeStoneFountainItem'>

< ecoicon item='SmallSinkItem'>  < ecoicon item='ToiletItem'>  < ecoicon item='BathtubItem'>  < ecoicon item='MillItem'>  < ecoicon item='CastIronStoveItem'>  < ecoicon item='BakeryOvenItem'>

< /ecoicon>
< sub>*Multiple Styles Available< /sub>
< /color>

///Sign that doesn't work:
Resources Needed:

< ecoicon item='LogItem'>  < ecoicon item='GneissItem'>  < ecoicon item='LimestoneItem'>

< ecoicon item='GraniteItem'>  < ecoicon item='BasaltItem'>  < ecoicon item='ShaleItem'>
< /ecoicon>

///Non-working code DOES work when modified thusly:
Resources Needed:

< ecoicon item='LogItem'>< /ecoicon>  < ecoicon item='GneissItem'>< /ecoicon>  < ecoicon item='LimestoneItem'>< /ecoicon>

< ecoicon item='GraniteItem'>< /ecoicon>  < ecoicon item='BasaltItem'>< /ecoicon>  < ecoicon item='ShaleItem'>
< /ecoicon>

Expected Behavior:
The second sign should display the icons, the same as the first sign.

Actual Behavior:
The sign is inexplicably blank.

Mods?
No mods!

**Comment by LadyNasse** [comment]
OOOO, INTERESTING FIND. When adding a < color>< /color> tag around the entire sign info, the "broken" code suddenly works.

**Comment by SlayksWood** [comment]
@LadyNasse Thank you for the report. Checked on 0.9.1 release-105 and I don't have any problem.
Can you add screenshots of the result that is wrong? Also which version are you playing?
don't forget to provide log files:
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LadyNasse** [comment]
The example sign, that works:
![image](https://user-images.githubusercontent.com/69120196/98025281-16a0ba00-1dcf-11eb-868b-e85ff8a3e53a.png)

Sign that doesn't work:
![image](https://user-images.githubusercontent.com/69120196/98025384-36d07900-1dcf-11eb-880d-4ac9af31bfe7.png)
![image](https://user-images.githubusercontent.com/69120196/98025427-4485fe80-1dcf-11eb-8f48-591696b3f726.png)

Adding the color tag to the unworking sign:
![image](https://user-images.githubusercontent.com/69120196/98025559-7c8d4180-1dcf-11eb-82b6-434d41fa4956.png)
![image](https://user-images.githubusercontent.com/69120196/98025588-86af4000-1dcf-11eb-921a-1843ae604004.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5483209/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5483210/Player-prev.log)

**Comment by LadyNasse** [comment]
Oh! And version 0.9.0.5 beta release-100

**Comment by redwyre** [comment]
I think 9.1 had some tag parsing changes, is it still an issue?

**Comment by mirasrael** [comment]
Actually TagParser was fixed in 9.2.

**Comment by SlayksWood** [comment]
So need to check in 9.2

**Comment by SlayksWood** [comment]
need to check in new staging build

**Comment by Daniel-Magulado** [comment]
@SlayksWood Seems to be fixed in staging. 

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/bf7d07d1-9ccc-4c26-8229-946b2a97fd4a)

Doesn't require individual < /ecoicon> to work anymore.
