### ISSUE TITLE
Negative weight on user inventory

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1904]
![grafik](https://user-images.githubusercontent.com/26040573/29487625-c04688b0-84fc-11e7-9088-f3ecbc92970e.png)

**Comment by metachronism** [comment]
do you have any info as to what kind of inventory actions you were performing when this occured?

**Comment by MarjieAVolk** [comment]
When I placed a cart, my inventory weight went down. When I picked it up, the weight didn't go back up. Happened consistently several times in a row, not sure if it always happens.
