### ISSUE TITLE
[0.9.1.0 beta staging-1831] trees names error localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19043]
In 9.0 to all trees names was add "Species" and it have not localization any more

![2020-10-30 (1)](https://user-images.githubusercontent.com/26339332/97915985-6a75b980-1d63-11eb-9381-4de969cdf3e7.png)
![2020-10-30 (2)](https://user-images.githubusercontent.com/26339332/97915990-6ba6e680-1d63-11eb-99d9-fe1772f6871a.png)
![2020-10-30 (3)](https://user-images.githubusercontent.com/26339332/97915992-6c3f7d00-1d63-11eb-8324-73bd61db5440.png)
![2020-10-30 (5)](https://user-images.githubusercontent.com/26339332/97915993-6c3f7d00-1d63-11eb-9c50-c41b60be3bdd.png)
![2020-10-30 (6)](https://user-images.githubusercontent.com/26339332/97915996-6cd81380-1d63-11eb-99f9-3b7fb1aa3568.png)
![2020-10-30 (7)](https://user-images.githubusercontent.com/26339332/97915997-6cd81380-1d63-11eb-9cea-0de14c297bff.png)
![2020-10-30 (8)](https://user-images.githubusercontent.com/26339332/97915998-6d70aa00-1d63-11eb-8b35-abd91917e1e6.png)
![2020-10-30 (9)](https://user-images.githubusercontent.com/26339332/97916000-6d70aa00-1d63-11eb-83f1-29ce92a2e569.png)
![2020-10-30 (10)](https://user-images.githubusercontent.com/26339332/97916001-6e094080-1d63-11eb-8130-4cb5acb04eef.png)
![2020-10-30](https://user-images.githubusercontent.com/26339332/97916002-6e094080-1d63-11eb-8250-07e5290ac795.png)
![2020-10-31 (9)](https://user-images.githubusercontent.com/26339332/97916003-6ea1d700-1d63-11eb-9596-93336c00664a.png)
![2020-10-31 (10)](https://user-images.githubusercontent.com/26339332/97916004-6f3a6d80-1d63-11eb-9052-ef695d62d349.png)
![2020-10-31 (11)](https://user-images.githubusercontent.com/26339332/97916006-6f3a6d80-1d63-11eb-9302-864534215dda.png)
![2020-10-31 (12)](https://user-images.githubusercontent.com/26339332/97916008-6fd30400-1d63-11eb-850c-f3a7ce7ceca7.png)
![2020-10-31 (13)](https://user-images.githubusercontent.com/26339332/97916009-6fd30400-1d63-11eb-83bc-f6e0ab756f8a.png)

and in Ecopediya too

![2020-11-02 (12)](https://user-images.githubusercontent.com/26339332/97916391-f851a480-1d63-11eb-8b09-263cd351176d.png)

**Comment by gabrielgindridev** [comment]
Fixing issue, but we will only run localization process in `staging`, which means new words will be add in staging.
![image](https://user-images.githubusercontent.com/65634950/110854817-45a2cd00-8294-11eb-9d98-5fa0bb082d0b.png)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 266
