### ISSUE TITLE
[Click to view Demographic] link doesn't work on Demographic (Abandoned) tooltips

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19047]
[Click to view Demographic] link doesn't work on Demographic (Abandoned) tooltips

nothing happens when i click that text

![Untitled](https://user-images.githubusercontent.com/32143431/97934792-b9602680-1d44-11eb-844d-3e62cd621d7b.jpg)
staging - 1831

**Comment by SlayksWood** [comment]
You need to click 'Abandoned' to view:
![image](https://user-images.githubusercontent.com/45708377/97953837-c287dc80-1db2-11eb-8bfa-e59fa75d853b.png)

**Comment by SlayksWood** [comment]
dup #19047

**Comment by SlayksWood** [comment]
@johnkslg @WeaselDog 
Maybe we should remake this hint somehow? This is not the first time a similar problem has been created.

**Comment by Daniel-Magulado** [comment]
Hi

This is now fixed. I'll be closing this one but feel free to submit any bug you encounter or if this issue is still a problem for you on the latest official version.
