### ISSUE TITLE
Fix property deed resizing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19045]
![image](https://user-images.githubusercontent.com/3536496/97926040-4db39480-1d17-11eb-8a8f-71eafeac815e.png)
Need help with the vertical resizing code for this, it gets cutoff when you change the number of allowed occupants. Can you improve this and let me know what approach to use  for the future? I think its from a mix of veritcal layout and your new fast vertical layout.

**Comment by johnkslg** [comment]
Also make the sections collapsible

**Comment by IcedForge** [comment]
Will close this one as it fixed its preliminary issue, have new ones for rework / ui sheet improvements and issues.
