### ISSUE TITLE
9.0.5 Abandoned demographic can apply to new players if min hours played set

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19040]
Abandoned demographic is hardcoded to only apply to chars over 24 hours old, it should be set to be Abandoned Day range * 24

![image](https://user-images.githubusercontent.com/61889138/97888445-0df2aa00-1d23-11eb-8c10-4ffb5bbd5820.png)

I had a player who was 24 hours old go into abandoned due to putting in min hours played 0.25, this should NOT have applied to the player as the char age was less than Abandoned day range * 24

![image](https://user-images.githubusercontent.com/61889138/97888569-2e226900-1d23-11eb-8b10-92ecda813817.png)

**Comment by IcedForge** [comment]
Also missing the 3rd parameter in the civics.eco config / server GUI
![Screenshot_72](https://user-images.githubusercontent.com/24981362/97959067-d9c4cb00-1dae-11eb-955b-bb8be1591b72.jpg)
