### ISSUE TITLE
The "Tags applying to:" reference for all of the Clothing items in the Ecopedia are text instead of a graphic   

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19051]
The "Tags applying to:" reference for all of the Clothing items in the Ecopedia are text instead of a graphic  

![Untitled](https://user-images.githubusercontent.com/32143431/97937282-32af4780-1d4c-11eb-95c4-68f250e62eff.jpg)
staging - 1831

**Comment by SlayksWood** [comment]
merged to #19053
