### ISSUE TITLE
The "Tags Applying to:" reference is incorrect in all Research Paper item tooltips

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19054]
The "Tags Applying to:" reference is incorrect in all Research item tooltips

![Untitled](https://user-images.githubusercontent.com/32143431/97939101-2ed1f400-1d51-11eb-94be-62d794af1d72.jpg)
staging - 1831

**Comment by SlayksWood** [comment]
merged to #19053
