### ISSUE TITLE
"suprising" should be "surprising" on the Plant Fibers page in the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19050]
"suprising" should be "surprising" on the Plant Fibers page in the Ecopedia

![Untitled](https://user-images.githubusercontent.com/32143431/97936646-2e822a80-1d4a-11eb-8a03-b5624cb39031.jpg)
staging - 1831

**Comment by WeaselDog** [comment]
Thanks again!

**Comment by dmplatten** [comment]
You’re welcome!
