### ISSUE TITLE
[Click to view in the skill window] isn't working for the skill (Campfire Cooking Specialty) tooltips

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19052]
[Click to view in the skill window] isn't working for the skill (Campfire Cooking Specialty) tooltips

![Untitled](https://user-images.githubusercontent.com/32143431/97937854-dcdb9f00-1d4d-11eb-8e18-20f807b8b092.jpg)
staging - 1831

**Comment by SlayksWood** [comment]
dup #19047
