### ISSUE TITLE
The "Tags Applying to:" reference is incorrect in all Clothes/Research Papers item tooltips

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19053]
The "Tags Applying to:" reference is incorrect in all Clothing item tooltips

![Untitled](https://user-images.githubusercontent.com/32143431/97938206-d3066b80-1d4e-11eb-862c-0580abbbf7b6.jpg)
staging - 1831

**Comment by SlayksWood** [comment]
> The "Tags Applying to:" reference is incorrect in all Research item tooltips
> 
> ![Untitled](https://user-images.githubusercontent.com/32143431/97939101-2ed1f400-1d51-11eb-94be-62d794af1d72.jpg)
> staging - 1831

**Comment by serpopov** [comment]
Fixed error but "Clothes" does not have tag sprite icon (it does not exist)
