### ISSUE TITLE
[6.0.0 staging-ceca2382] DivideByZeroException while generating world

### ISSUE THREAD

**Issue by KlaasT** [StrangeLoopGames/EcoIssues#1905]
For a test I tried to generate quite a bigger world (180x180 and 200x200) however the generation seems to get stuck at about 74%.

I can see crashdumps which are giving me a DivideByZeroException:

> Exception
System.DivideByZeroException: Es wurde versucht, durch 0 (null) zu teilen.
   bei Eco.Shared.Voxel.ChunkGrid`1.GetWrappedChunkPositionInternal(Vector3i chunkPos)
   bei Eco.Shared.Voxel.ChunkGrid`1.GetChunk(Vector3i chunkPos)
   bei Eco.World.WorldChunkGrid.GetBlock(Vector3i worldPos)
   bei Eco.Simulation.RouteProbing.RouteManager.GetWalkableWorldBlock(Vector3iWrapped pos)
   bei Eco.Simulation.RouteProbing.RouteManager.GetConnectedWorldBlock(Vector3iWrapped fromWalkable, Vector3i dir)
   bei Eco.Simulation.RouteProbing.Flooding.TryMove(Func`2 checkVisited, Vector3iWrapped from, Vector3i dir)
   bei Eco.Simulation.RouteProbing.Flooding.FloodFill(Vector3iWrapped start, Func`2 checkVisited, Action`1 visit)
   bei Eco.Simulation.RouteProbing.RouteManager.InitRouteCache()
   bei Eco.Simulation.RouteProbing.RouteManager.Update()
   bei Eco.Simulation.RouteProbing.RouteProbingPlugin.Run()
   bei Eco.Server.PluginManager.<>c__DisplayClass11_0.<StartPlugins>b__0(Object x)
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by SeanAtr0n** [comment]
Did you restart the server to do the generation or hit WorldGenerator->Regenerate?

**Comment by KlaasT** [comment]
I restarted the server however I can reproduce this error when I hit regenerate.
