### ISSUE TITLE
[0.9.1.0 beta staging-1832] Contract status need localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19065]
![2020-11-03](https://user-images.githubusercontent.com/26339332/98025158-6658a300-1e1a-11eb-8923-2575a10bd0db.png)

**Comment by StallEF** [comment]
@gabrielgindridev  in [0.9.3 staging-1937]:
in Contact header localization work well
![2021-02-23 (3)](https://user-images.githubusercontent.com/26339332/108831327-02c9cf80-75db-11eb-96a8-d8f7d24d835b.png)
but in other 3 places not
![2021-02-21](https://user-images.githubusercontent.com/26339332/108831408-212fcb00-75db-11eb-8681-aa31128f7f86.png)
- Contact board
- Contact tooltip
- right notification bar

**Comment by TwixterZ** [comment]
tested and confirmed as of 9.4 develop 251
