### ISSUE TITLE
User icon offset in text

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19067]
![image](https://user-images.githubusercontent.com/3536496/98034615-2965bf80-1dcc-11eb-98ba-52433a6249f6.png)

**Comment by IcedForge** [comment]
This is not an issue in release 105 ?
Is this on dev build?

**Comment by SlayksWood** [comment]
Have this one in 0.9.2 develop-103
![image](https://user-images.githubusercontent.com/45708377/98221111-4af7b000-1f60-11eb-8a3c-ccf525d4164e.png)

**Comment by serpopov** [comment]
fixed in SVN
