### ISSUE TITLE
USER ISSUE: Sweeping Hands not working

### ISSUE THREAD

**Issue by MitsukiAkina** [StrangeLoopGames/EcoIssues#19068]
\
**Version:** 0.9.1.0 beta release-105

**Steps to Reproduce:**
mine some rock
4 stone are dropped
collect rock

**Expected behavior:**
Normally it should have collected every rock intstead of one rock

**Actual behavior:**
I just collect one rock

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No there are no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5483829/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5483830/Player-prev.log)

**Comment by IcedForge** [comment]
@MitsukiAkina Thank you for reporting this.
We are working on resolving this as soon as we can.

**Comment by SlayksWood** [comment]
Fixed in 0.9.1.1
