### ISSUE TITLE
[0.9.1 release-105] Wrong information in modern pickaxe tooltip.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19060]
We've got a mistake somewhere. So previous issue #13155 were fixed. And now I need 1 hit with Modern pickaxe to destroy basalt without Mining specialty. That's right. But tooltip says that I need 2 hits:
![image](https://user-images.githubusercontent.com/45708377/97978246-5b801d00-1dde-11eb-8da9-85a4e70c51bb.png)

**Comment by Daniel-Magulado** [comment]
Changes are done on Clickup. https://app.clickup.com/t/10591183/ECO-11993
Closing as fixed.
