### ISSUE TITLE
[0.9.1.0 beta staging-1832] road contract bug

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19064]
if set road width 3+ 
![start](https://user-images.githubusercontent.com/26339332/98020967-bfbdd380-1e14-11eb-8133-a421c78c232e.png)

to it reset to 3 all times
![proposet](https://user-images.githubusercontent.com/26339332/98021619-8fc30000-1e15-11eb-9076-b676ab7326f4.png)

and if try edit contract it show 1
![finish](https://user-images.githubusercontent.com/26339332/98021223-1b885c80-1e15-11eb-8325-da1f8400bf0f.png)

**Comment by johnkslg** [comment]
maybe just needs a .Changed call

**Comment by SlayksWood** [comment]
![Uploading image.png…]()
