### ISSUE TITLE
Random crashes/freezes

### ISSUE THREAD

**Issue by Guruthos1988** [StrangeLoopGames/EcoIssues#19061]
I have the issue that the game randomly crashes or freezes (sound still working and when pressing tab mouse still moveable but no reaction on clicking anything). Sometimes it happens after a few minutes, sometimes i can play for about an hour. 
No crash reports are generated. Sometimes when a crash happens i get a popup for a very short time saying something with unity i think but it is way too short for me to read it.

first i suspected it's because my GPU is overheating cause it was always at 100% so i set max frames to 30. GPU now shows a max usage of around 70 and average between 50 and 60 and the temperature is normal. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5480893/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5480894/Player-prev.log)
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5480896/DxDiag.txt)

**Comment by IcedForge** [comment]
@Guruthos1988 Thank you for your report. We have added some optimization and fixes for some graphic issues in 9.1
please reply if you still have these issues in the new update.

**Comment by Guruthos1988** [comment]
Issue still is there. even it feels like the timeframe between the crashes is mostly longer

**Comment by TwixterZ** [comment]
@Guruthos1988, do you still facing this issue on the latest build of ECO?

**Comment by IcedForge** [comment]
Will close due to lack of reply.
