### ISSUE TITLE
Pipe class crashes server at start

### ISSUE THREAD

**Issue by SRMM** [StrangeLoopGames/EcoIssues#19075]
After an update from [Eco Server 0.9.0.5 beta release-100] to [Eco Server 0.9.1.0 beta release-105] the server wouldn't restart.
The logs point to an error in the pipe classes.

[log_201103084657.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484048/log_201103084657.log)

**Comment by aviator671** [comment]
Same here, here is the logs.


[log_201103104239.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484240/log_201103104239.log)

**Comment by ssarco** [comment]
Have you tried to delete your mods folder and reverify files through steam or replace it with the zip file mods folder if you download it off the website?

**Comment by SRMM** [comment]
We use a Nitrado server.
Deleting the Mods folder there and let it automatically load a new one didn't help.
So we tried the Mods folder from the Steam Version and it seems to have helped.
The server is up and running for now.

**Comment by IcedForge** [comment]
Closing this issue as it has been resolved by the OP
