### ISSUE TITLE
9.1.0 Whilst in the options menu shortcut keys still work ie Y or O

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19073]
Whilst in the options menu shortcut keys still work, when in the options no shortcut keys should function especially not Y or O which lag a fair bit on a popular server.

**Comment by IcedForge** [comment]
This is still an issue, all shortcuts works and when you scroll down a list in a esc menu it also scrolls through your hotbar, when you have a esc menu open it should disable all "game" related hotkeys and functions and only interface with the actual menu you have open.
