### ISSUE TITLE
[0.9.1.0 release-105]Work Party edit payment, requirements etc broken

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19079]
Editing payment, requirements etc in work parties / contracts are broken and links you to an empty ui page.
![Screenshot_5.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c82e105b-a765-4d14-ab63-ec724af5a08c)

**Comment by SlayksWood** [comment]
fixed in 0.9.1.1
