### ISSUE TITLE
9.1.0 Steam truck smoke is infront of the steam truck by about 25metres

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19071]
As per title, though it is only when the steam truck is moving forwards

![image](https://user-images.githubusercontent.com/61889138/98038782-9c475880-1e15-11eb-80d3-9bb3175395ea.png)

**Comment by WeaselDog** [comment]
Thanks for reporting this. Bumping in priority due to how often trucks are used and this is very strange looking.

**Comment by MazonDel** [comment]
This was a fix pushed to the SVN, no code fix.
