### ISSUE TITLE
github link and instructions missing

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19089]
I've linked my github but I don't see the location of the source code.  Also I would like to notify you that the link of Instructions appears to be a dead link.

**Comment by denysaw** [comment]
Hm... For me everything worked. License Agreement page worked, apply the agreement also worked. Can't reprodue.
@SlayksWood @IcedForge Can some one of you also try and write sane steps of the problem? ;) Thanx!

**Comment by D3nnis3n** [comment]
User actually wasn't invited as the automatic e-mail didn't arrive. Was invited manually yesterday.

**Comment by D3nnis3n** [comment]
I guess the instruction link is referring to an email you get when ordering dev-tier. Not sure, though.

**Comment by D3nnis3n** [comment]
That was the case. Adapted the mail to tell how getting access to dev tier works and that the instructions can only be seen after being invited. Denys will apply that and this fixes the issue.

**Comment by D3nnis3n** [comment]
Confirmed fixed.

**Comment by denysaw** [comment]
Could be tested only on Stagingland for now
