### ISSUE TITLE
Unable to play since update

### ISSUE THREAD

**Issue by WeaselWarDance0** [StrangeLoopGames/EcoIssues#19085]
I had a 44MB update, and have not been able to play since then.

[log_201104100626.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484670/log_201104100626.log)

**Comment by IcedForge** [comment]
@WeaselWarDance0
Looks like issues with permissions to run the server.exe and or the containing folders. Are you running the game as administrator?

System.UnauthorizedAccessException: Access to the path 'D:\Steam\steamapps\common\Eco\Eco_Data\Server\WebClient\WebBin\Layers\Agave.gif' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Init()
   at Eco.Simulation.WorldLayers.WorldLayerManager.InitLayers(LayerInitOperation operation)
   at Eco.Simulation.WorldLayers.WorldLayerManager.Regenerate()
   at Eco.Simulation.EcoSim.Regenerate()

**Comment by WeaselWarDance0** [comment]
Uhh, I have no idea lol. It was working fine yesterday. I deleted that game and tried to make a new one, and that error happened.
(Still relatively new to the game, sorry)

**Comment by WeaselWarDance0** [comment]
Got this error just now when trying someone else's server:

[Eco Error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5484728/Eco.Error.txt)

**Comment by WeaselWarDance0** [comment]
Uninstalled and reinstalled the game. Tried starting a new game from scratch again, and it did the same thing. It seems I can load into other peoples' servers now, but I can't play solo.

[log_201104025747.log](https://github.com/StrangeLoopGames/EcoIssues/files/5485424/log_201104025747.log)
