### ISSUE TITLE
[0.9.0.5 -> 0.9.1.0 migration]Server crash 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19083]
User pm'd me with a crash issue after migrating over to 9.1
Player log
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484638/Player.log)
Server log
[log_201103075430.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484640/log_201103075430.log)
Migration log
[migrations.log](https://github.com/StrangeLoopGames/EcoIssues/files/5484641/migrations.log)

System.ArgumentException: An item with the same key has already been added. Key: StevoMCMXXXII
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Eco.Gameplay.Economy.CurrencyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyManager.Initialize()
   at Eco.Gameplay.Economy.EconomyPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)

**Comment by SlayksWood** [comment]
save file from #19108
https://drive.google.com/file/d/1vaBkJZ6XCWakzCYWlFKZlT1bd8mkjs6k/view?usp=sharing

**Comment by plex68** [comment]
it is impossible to launch a subsequent backup then to put the server in 9.1.0, the bug being still present crashes the server despite the old version which worked

**Comment by plex68** [comment]
> save file from #19108
> https://drive.google.com/file/d/1vaBkJZ6XCWakzCYWlFKZlT1bd8mkjs6k/view?usp=sharing


Do you have any news concerning a possible correction of my backup to be able to restart my server?

**Comment by mirasrael** [comment]
@plex68 I'm working on fix now

**Comment by mirasrael** [comment]
@plex68 seems you changed server locale from French to English, started server and then stopped it. There is known issue which caused such workflow to make two personal accounts with different names. It is already fixed in 9.2, but still a problem in 9.1.
I may assume you unintentionally changed server locale, because you made changes in Localization.eco.template instead of copy this file to Localization.eco and make changes in it. So it was overwritten after update. If you restore your world from 9.0.5 save and ensure same locale set then it should fix problem.

**Comment by mirasrael** [comment]
In case if you wanna to repair the save you can use hot-fixed 9.1.1 version: https://drive.google.com/file/d/1nseAvEU-evFNvX9NzdxYlM_i2m-vl8WK/view?usp=sharing (you may use it instead of retail exe).

**Comment by plex68** [comment]
Thank you !! Thank you very much for allowing me to recover my backup, it was complicated last night.

I tried a lot to restart my server!

But it's great you have found a solution and I thank you again!

Good luck and courage for your release of 9.1.2 :)
