### ISSUE TITLE
[6.0.0 staging-ceca2382] System.Reflection.TargetInvocationException after removing store

### ISSUE THREAD

**Issue by KlaasT** [StrangeLoopGames/EcoIssues#1908]
After playing a few hours I tried to remove a store from its place and set it somewhere else. After this the server crashed and I am unable to start it.

I've attached the crashdump.

[Crash 08203347.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1237148/Crash.08203347.ecodmp.txt)
[Crash 08203419.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1237147/Crash.08203419.ecodmp.txt)
[Crash 08203246.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1237146/Crash.08203246.ecodmp.txt)

**Comment by johnkslg** [comment]
fixed
