### ISSUE TITLE
[0.9.1.0] Placing down Government table with active "proposed" elections

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19081]
When i try to place my Zooning office which has 2 active districts and 2 new  proposed modified on the active ones i can't select all 4 in the list. See pic. And if i don't select the proposed ones they get inactive and removed. 

Now you can loose a proposes district or you can abuse it and remove stuff that you don't want.

![image](https://user-images.githubusercontent.com/32419758/98046664-e8e95e80-1e2a-11eb-9bcb-9ae888dbb3d0.png)
![image](https://user-images.githubusercontent.com/32419758/98046668-ebe44f00-1e2a-11eb-8121-5e8b2485c6c2.png)

**Comment by johnkslg** [comment]
Fixed, now it always brings its pair even if you didnt select it.
