### ISSUE TITLE
Server encountered an exception

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19087]
Server encountered an exception

![image](https://user-images.githubusercontent.com/32143431/98055268-10c8ca00-1e0b-11eb-9839-53dbc2d1e029.png)

**Comment by IcedForge** [comment]
@dmplatten Thank you for reporting, could you please provide server and user logs

Server log found in: ...\Eco\Eco_Data\Server\Logs or ...\Steam\steamapps\common\Eco\Eco_Data\Server
Player log found in: C:\Users\[YOUR_USERNAME]\AppData\LocalLow\Strange Loop Games\ECO or %USERPROFILE%\AppData\LocalLow\Strange Loop Games\ECO

Also are you hosting this, is it a rented server? 
Do you have mods on ?

**Comment by dmplatten** [comment]
Hi, I was just playing on someone else's server. I think they had mods. I didn't go back to it after the crash, so i'm playing on a different server now. Do you still want me to try to get my player log? I was looking at the tutorial when it happened.

**Comment by IcedForge** [comment]
There where a few changes to a lot of files so any number of issues could have caused this  if it was a modded server.
Ill close this for now you can reopen it if you see this again.

**Comment by dmplatten** [comment]
Okay sounds good.

Sent from my iPad

On Nov 4, 2020, at 8:33 AM, IcedForge <notifications@github.com> wrote:

﻿

There where a few changes to a lot of files so any number of issues could have caused this if it was a modded server.
Ill close this for now you can reopen it if you see this again.
