### ISSUE TITLE
USER ISSUE: Currency creator for all currencies changed to "Jimmy"

### ISSUE THREAD

**Issue by rodneymillerpca** [StrangeLoopGames/EcoIssues#19092]
![jimmy](https://user-images.githubusercontent.com/60119304/98063267-a40afb00-1e1d-11eb-8076-084dea229f0a.png)
\
**Version:** 0.9.1.0 beta release-105

**Steps to Reproduce:**
Upgrade to 9.1

**Expected behavior:**
Should have proper creators name.

**Actual behavior:**
It has them named "Jimmy"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@rodneymillerpca Thank you for reporting, will add this to the sorted duplicate #19093 .
