### ISSUE TITLE
Main menu interface doesn't appear on Linux

### ISSUE THREAD

**Issue by SollyW** [StrangeLoopGames/EcoIssues#19094]
When starting the game, the main menu doesn't appear. Pressing escape opens the settings menu like normal.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5485380/Player.log)

**Comment by IcedForge** [comment]
Some vivox spam all through the log? Need input is this a build issue ?

Fallback handler could not load library /home/solly/.local/share/Steam/steamapps/common/Eco/Eco_Data/Mono/libVivoxNative
Fallback handler could not load library /home/solly/.local/share/Steam/steamapps/common/Eco/Eco_Data/Mono/libVivoxNative.so
Fallback handler could not load library /home/solly/.local/share/Steam/steamapps/common/Eco/Eco_Data/Mono/libVivoxNative
Fallback handler could not load library /home/solly/.local/share/Steam/steamapps/common/Eco/Eco_Data/Mono/libVivoxNative
Fallback handler could not load library /home/solly/.local/share/Steam/steamapps/common/Eco/Eco_Data/Mono/libVivoxNative.so

**Comment by redwyre** [comment]
Are you playing through steam? Does it work if you run it manually without steam?

**Comment by SollyW** [comment]
I am on steam. It works using the standalone version.

**Comment by redwyre** [comment]
It looks like there's an issue with Eco communicating with steam, it could either be an issue with Eco (try verifying files in steam), or an issue with steam itself (maybe reinstall?)

**Comment by WeaselDog** [comment]
@SollyW Are you still having this issue in version 9.1.9?

**Comment by WeaselDog** [comment]
Closing the issue due to inactivity, but please let us know if you still have this issue.
