### ISSUE TITLE
9.1.1 Difficulty.eco file works wrong after change it in Server UI

### ISSUE THREAD

**Issue by tbgray** [StrangeLoopGames/EcoIssues#19099]
Low/no collaboration servers auto jump to level 7.

**Comment by SlayksWood** [comment]
@tbgray Thank you for the reprort.
1. What server are you playing on? Have you changed the difficulty settings in the template? 
2. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Try to use backup and check difficulty settings config before server update.

**Comment by SlayksWood** [comment]
It's related with configs. You need to delete your difficulty.eco file and make another one from difficulty.eco.template.
and another question. 
What language is on your server?

**Comment by SlayksWood** [comment]
So how to reproduce issue:
- Have difficulty.eco in configs.
- Start server.
- open serverui and change some settings:
![image](https://user-images.githubusercontent.com/45708377/98129253-f9044b00-1ec9-11eb-92a0-44cc6a79ce9a.png)
- check experience needed. I need 0 expirience to level up any specialty:
![image](https://user-images.githubusercontent.com/45708377/98129316-0c171b00-1eca-11eb-8a70-8ce2f24bca35.png)

**Comment by IcedForge** [comment]
These 2 modifiers has 0 value regardless of difficulty setting you choose, this is a critical issue as it breaks the game in terms of 0/0 experience required per level and is extremely detrimental to new player experience and views of the game if they try to create a game and be forced into big repercussion issues they have no idea why its happening.

Need to fix the preset selection values for these modifiers.

![Screenshot_29](https://user-images.githubusercontent.com/24981362/98238552-d116f500-1f66-11eb-938f-5929070c9045.jpg)
