### ISSUE TITLE
6 digits after the decimal point are displayed for additional labor required on the Hewn Log Project

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19095]
6 digits after the decimal point are displayed for additional labor required on the Hewn Log Project

![Untitled](https://user-images.githubusercontent.com/32143431/98068177-5ac0a880-1e29-11eb-953f-f576b98bfe09.jpg)

**Comment by SlayksWood** [comment]
I guess it's regression, but we can wait fo 9.2.
