### ISSUE TITLE
 Error loading server, crash 9.1.1

### ISSUE THREAD

**Issue by plex68** [StrangeLoopGames/EcoIssues#19108]
I am totally lost I have a crash server since update 9.1.1, it is impossible for my community to play ECO following this update.

When starting the server it loads and then leaves me with this error message:

[11: 52: 42.052] [35] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message: An item with the same key has already been added. Key: Inwin91
Source: System.Private.CoreLib

[log_201104121358.log](https://github.com/StrangeLoopGames/EcoIssues/files/5487545/log_201104121358.log)

**Comment by SlayksWood** [comment]
@plex68 Thank you for the report. known issue. merged to #19083

**Comment by SlayksWood** [comment]
@plex68 Can you provide save file to this issue or if you don't want to make it public you can sent it to me in discord Kirill (Slayks)#6251 or mail kirill@strangeloopgames.com
