### ISSUE TITLE
[0.9.2 develop-102] Can see tooltip from Create Avatar window during Loading world.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19106]
Just mouseover approximate position
![image](https://user-images.githubusercontent.com/45708377/98102885-3aceca80-1ea5-11eb-8b42-b37489dc1da1.png)

**Comment by tuha263** [comment]
I can't reproduce it but I think it's will be better if I hide the Cursor on this screen. The cursor seems useless here.
