### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Icemax67** [StrangeLoopGames/EcoIssues#19104]
Unable to join our server from VeryGames.
There are some errors in the log.
Restart, new installation of the server didn't work.
[log_201104090715.log](https://github.com/StrangeLoopGames/EcoIssues/files/5486600/log_201104090715.log)

Thank in advance for your help.

**Comment by SlayksWood** [comment]
It looks like the problem is in the mods. Try removing pipe mod and starting the server again.

**Comment by EndruK** [comment]
Hi,
I got the exact same error since v0.9.1.0. (Before that update everything worked fine)
However, I didn't install any mods on my own. I'm just using the default server environment.
System: Debian

Greets

**Comment by SlayksWood** [comment]
If you're getting issues with
[02:10:27] Mods recompiled with warnings.
[02:10:27] Mods recompiled with errors.
in the logs, please remove the "Mods" folder and have Steam verify integrity.

**Comment by EndruK** [comment]
I'm running a dedicated eco server on a linux vserver. I can't let steam check something there.

**Comment by EndruK** [comment]
However, I managed to get the server up by changing the name of the pipe mod at:
`Pipes.cs` to `Pipes.cs.backup` at `Mods/Items/` and start the server

**Comment by Icemax67** [comment]
Thanks for your help. I replaced the "Mods" folder from the server file by the one in my Steam folder, it works.
