### ISSUE TITLE
USER ISSUE: sweeping hands

### ISSUE THREAD

**Issue by redeaglesss** [StrangeLoopGames/EcoIssues#19102]
\
**Version:** 0.9.1.0 beta release-105

**Steps to Reproduce:**
Perk sweeping hands in mining does not work

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i dont have any mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #19068
