### ISSUE TITLE
[0.9.1.0] Skid's debris and mining issues

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19100]
I've tried doing some mining with a Skid on WT. I could dig into rock just fine, but eventually I'd fill up and drop some stone chunks on the ground. I wouldn't be able to pick those chunks up manually or with the Skid until I relogged onto the server. Not sure what's up with that. It might be due to me doing those actions on a government road district where I needed an authorisation or something...

[Player - Skid mining issues.log](https://github.com/StrangeLoopGames/EcoIssues/files/5486004/Player.-.Skid.mining.issues.log)

**Comment by ThePiachu** [comment]
Hmm, it might be generating some phantom rocks, since when I relogged some of them disappeared? Plus those can also generate while a skid is not empty...

**Comment by SlayksWood** [comment]
have this problem too.

**Comment by SlayksWood** [comment]
Perhaps related with our rubble changes, so assigned @MazonDel. But it can be related with Action changes too, so @olegshegai can take a look too.

**Comment by ThePiachu** [comment]
Also also, not sure if related - Skids can break blocks on other people's properties. Run into a rock wall owned by someone and it turns to 4 rock chunks.

**Comment by GreaseMonk** [comment]
Can confirm since 0.9.1.0 immediately left debris that are existing on the client side but not server side

**Comment by GreaseMonk** [comment]
The Excavator occasionally does the same thing by the way, but only on breaking stones.

**Comment by ThePiachu** [comment]
I think the problem has gotten a bit less severe as of 0.9.1.2 br-111, but you still get occasional debris. Not as much as before I don't think, or at least it's not as intrusive.

[Player - Skid still.log](https://github.com/StrangeLoopGames/EcoIssues/files/5504188/Player.-.Skid.still.log)

**Comment by morewind** [comment]
Player with "Mining Lucky Break Talent" no bug, player with "Mining Sweeping Hands" has a bug. Two players on single server reports "yes/no" bug.

**Comment by ThePiachu** [comment]
> Player with "Mining Lucky Break Talent" no bug, player with "Mining Sweeping Hands" has a bug. Two players on single server reports "yes/no" bug.

I do have Sweeping Hands, so at least that part seems to be true for me.

**Comment by Shoe73** [comment]
I just upgraded to 9.1.4 and it is still an issue.  Drive the skid steer some block are falling to the ground, can't pick up with skid steer or manually.  They do turn green when hoover over the blocks.

**Comment by WeaselDog** [comment]
Thank you for all the detailed info. We have a fix in the works and should be able to push a fix soon.

**Comment by SlayksWood** [comment]
Still an issue after this fix https://github.com/StrangeLoopGames/Eco/pull/7143 . It happens much less but still could be happen. Digged near 5 stockpiles have 3 fantom rubbles.

**Comment by Bazzi89** [comment]
please fix it... its no more funny to work with my loved skid steer :(

**Comment by MazonDel** [comment]
Fixed per @gzatravkin 's hotfix. Good job!

**Comment by SlayksWood** [comment]
Seems fixed in release-118.
