### ISSUE TITLE
9.1.1 MU4 Very low resource usage compared to previous levels

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19113]
MU4 only requires 12 composite which is approx a 10th of the cost of the MU3 cost.

Suggestion something like this, due to the two different composite types it will mean players have to travel the word a lil more to make them

80 Composite
10 Composite Redwood
10 Composite Oak
40 Screws

Below code as am using this on my server, this is approx same cost as the MU3 upgrade

     new IngredientElement("CompositeLumber", 80, typeof(CompositesSkill), typeof(CompositesLavishResourcesTalent)),   
               new IngredientElement(typeof(CompositeRedwoodLumberItem), 10, typeof(CompositesSkill), typeof(CompositesLavishResourcesTalent)), 
               new IngredientElement(typeof(CompositeOakLumberItem), 10, typeof(CompositesSkill), typeof(CompositesLavishResourcesTalent)), 
               new IngredientElement(typeof(ScrewsItem), 40, typeof(CompositesSkill), typeof(CompositesLavishResourcesTalent)),     
               new IngredientElement(typeof(ModernUpgradeLvl3Item), 1, true),

**Comment by TwixterZ** [comment]
fix is checked and confirmed as of 9.4 develop 279
