### ISSUE TITLE
[0.9.1.1 beta release-107] Ecopedia need localization update (group tags)

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19117]
![anim](https://user-images.githubusercontent.com/26339332/98164252-0e429f00-1ef5-11eb-83ae-85a845432708.png)
Birds
Mammals
Reptiles

![mater](https://user-images.githubusercontent.com/26339332/98164287-18649d80-1ef5-11eb-9486-57d28969e7d0.png)
Building Materials
Byproducts
Liquids
Metals
Processed Rock
Roads

![popul](https://user-images.githubusercontent.com/26339332/98164293-1b5f8e00-1ef5-11eb-82a1-99dde7e76d66.png)
Population: {0}

**Comment by SlayksWood** [comment]
@StallEF Thank you for the report.
@Quadbro 
Don't have it in gibberish, but maybe this string doesn't use translations from crowdin? Can you check it please.

**Comment by StallEF** [comment]
@SlayksWood I could not find any of these words in crowdin now

**Comment by StallEF** [comment]
@Quadbro 
Beds
Decoration
Seating
Washroom
![2020-11-08 (4)](https://user-images.githubusercontent.com/26339332/98483483-da7bb800-2219-11eb-987a-90a5e798e0a5.png)
Research Papers
![2020-11-08 (5)](https://user-images.githubusercontent.com/26339332/98483504-fed79480-2219-11eb-8d7d-6e2e9e0420e0.png)
Community
Power Generation
Signs
![2020-11-08 (6)](https://user-images.githubusercontent.com/26339332/98483516-13b42800-221a-11eb-99e3-496fa8c145b4.png)
Charred Food
Produce
![2020-11-08 (7)](https://user-images.githubusercontent.com/26339332/98483526-24fd3480-221a-11eb-8971-f871acf9f999.png)
Craft Tables
Economic
Researching
![2020-11-08 (8)](https://user-images.githubusercontent.com/26339332/98483537-3b0af500-221a-11eb-9131-6841df693355.png)
