### ISSUE TITLE
9.1.1 - Fishing pole doesn't Behave properly

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#19114]
So uhh.. yeah i was doing some testing in my world and i cast the fishing rod out to use and the line doesn't exactly stay in the water...

This image is of the rod casted out 
![20201105034322_1](https://user-images.githubusercontent.com/29281156/98140396-7f944900-1f19-11eb-8838-ca63cfff1f82.jpg)

Reeling it in does not fix the issue either

Edit: Holding in left click then casting makes it act properly,
just clicking however causes it to behave as described

Edit 2: After Reeling it in some it then begins to behave just like the image above

**Comment by MazonDel** [comment]
I increased the minimum cast strength to 150 which appears to solve the problem. Update from the "/trunk" SVN to get the update.
