### ISSUE TITLE
[0.9.1.1] Placing Stone / Dirt ramps kicks you from the server

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19119]
Placing a stone or dirt ramp kicks you from the game and gives you this error (see pic)

![image](https://user-images.githubusercontent.com/32419758/98170745-d0db1300-1eee-11eb-95b5-d1baa5d4e50f.png)

**Comment by SlayksWood** [comment]
@NemoLArs Thank you for yhe report.
1. Provei log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Do you have mods installed?
3. Provode save file if possible. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
4. Provide your PC specification (include Operating System).
5. Add more information. Server language, client language, what did you do before?

**Comment by MonzUn** [comment]
@SlayksWood This is from an experimental mod I run on this Server that broke with the update.
Feel free to close this ticket.

**Comment by SlayksWood** [comment]
@MonzUn thank you for the information.
