### ISSUE TITLE
USER ISSUE: Rocketman?

### ISSUE THREAD

**Issue by Boddypen420** [StrangeLoopGames/EcoIssues#19115]
\
**Version:** 0.9.1.1 beta release-107

**Steps to Reproduce:**
Mine granite directly downwards with nothing obstructing sky above you. When falling into the broken block has a chance to launch into the sky. Currently at 1569y with no way to get down

**Expected behavior:**
mined the block and allowed to be picked up

**Actual behavior:**
launched me into oblivion, above the spherical world.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Boddypen420 Thank you for the report. 
1. Try to use /unstuck.
2. If unstuck doesn't help then ask you administrator to teleport you (/teleport targetto)
merged to #18805
