### ISSUE TITLE
[0.9.1.1] Some can vote, some can't

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19120]
Some can vote on elections, some can't. I can't and at least 2 more on the server can't. We are not using the same browers. I have tried to clear my browser etc. Error = see pic

![image](https://user-images.githubusercontent.com/32419758/98171452-0b917b00-1ef0-11eb-9ca0-bb859dca0c99.png)

**Comment by NemoLArs** [comment]
Notice how it's locks on "Submitting"

**Comment by NemoLArs** [comment]
When opening the webserver from the game i get this error on the main screen : 

![image](https://user-images.githubusercontent.com/32419758/98172094-0680fb80-1ef1-11eb-9177-585aaaac7d3b.png)

As you can see, no information about the elections or the server.

**Comment by NemoLArs** [comment]
When disabling AdBlock - all works just as it should. Never had that issue before.

**Comment by SlayksWood** [comment]
@NemoLArs Can you give your server IP adress or ID?

**Comment by NemoLArs** [comment]
> @NemoLArs Can you give your server IP adress or ID?

92.32.88.81:3000

**Comment by SlayksWood** [comment]
> **Version:** 0.9.1.1 beta release-107
> 
> **Steps to Reproduce:**
> trying to submit a vote.
> 
> **Expected behavior:**
> vote should be submitted
> 
> **Actual behavior:**
> Error: {"Errors":{"RankedVotes[0]":["Could not convert string to integer: Yes. Path 'RankedVotes[0]', line 1, position 61."],"RankedVotes[1]":["Could not convert string to integer: No. Path 'RankedVotes[1]', line 1, position 66."]},"Type":"[https://tools.ietf.org/html/rfc7231#section-6.5.1","Title":"One](https://tools.ietf.org/html/rfc7231#section-6.5.1%22,%22Title%22:%22One) or more validation errors occurred.","Status":{},"Extensions":{"traceId":"|5d5c033c-455d85c72b6d525a."}}
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> no and yes
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file


> disabling addblocker seem to works

**Comment by denysaw** [comment]
Looks just the cache issue. Sometimes Chome/FF bugs and doesn't clear all external resources with Ctrl+F5 of the page, which uses those. Please, open `http://YOUR_WORLD_URL/inc/js/header.js` and press Ctrl+F5. And try after it. And I'm pushing anti-cache solution right now.
