### ISSUE TITLE
After using the "Drop Marker" button, the new marker doesn't get created until the world is moved a little bit

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19125]
After using the "Drop Marker" button, the new marker doesn't get created until the world is moved a little bit

![image](https://user-images.githubusercontent.com/32143431/98187516-1abbfd00-1edf-11eb-9758-0ef1127b89e0.png)
0.9.1.1 beta release-107

**Comment by gzatravkin** [comment]
This one was fixed in develop by Duck
