### ISSUE TITLE
Trees don't disappear from minimap until fully removed

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1913]
Trees should disappear from the minimap the moment they are felled with an axe

![image](https://user-images.githubusercontent.com/3150561/29537959-8a958d6a-8678-11e7-9ac9-277081e63f54.png)

**Comment by SeanAtr0n** [comment]
Works for me in-editor, seems like the client is occasionally losing some data that is only sent once
