### ISSUE TITLE
USER ISSUE: Teleport

### ISSUE THREAD

**Issue by xplayman** [StrangeLoopGames/EcoIssues#19138]
\
**Version:** 0.9.1.1 beta release-107

**Steps to Reproduce:**
I'm mining above ground and randomly when I walk on the stones that i've mined I get teleported 1500 tiles into space and have to /fly to get back down. Similar hapens in caves, except I get randomly teleported with in the cave.

**Expected behavior:**
none

**Actual behavior:**
Unneccasary teleportation.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I only have server mods installed, Nidtoolbox and it's extensions.
I havent tried with out the mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
thank you for the report. merged to #18805
