### ISSUE TITLE
[0.9.2 develop-103] Excavator sound is broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19139]
- [ ] The sound is infinity, fixed be restart client
- [ ] If you hit the wall with scoop and press the sound increases
Video https://drive.google.com/file/d/12a1EGNXMN2jfh6B2-Ie-aNtd3jgM6S5W/view?usp=sharing

**Comment by ptitducanh** [comment]
I checked. It was fixed on develop.
