### ISSUE TITLE
[0.9.2 develop-103] Command '/civics addvotes' doesn't work

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19134]
a bit inconvenient to test without this command, can it be fixed?

**Comment by tuha263** [comment]
It's working now. We need at least one Election is running. If there's no, we will receive an error message
![NoElection](https://user-images.githubusercontent.com/9598614/101236324-f2543800-3702-11eb-9a4d-498daf846389.png)
![HaveElection](https://user-images.githubusercontent.com/9598614/101236327-f4b69200-3702-11eb-91fc-fd4d260420c3.png)

**Comment by IcedForge** [comment]
Not working for me on staging-1876

![Screenshot_61.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/3d3e8e45-7b84-4cc0-a8e0-3c58caa83fed)

**Comment by SlayksWood** [comment]
Still doesn't work(
![image](https://user-images.githubusercontent.com/45708377/102483520-ec9d1180-4075-11eb-9057-60f91c6f4931.png)

**Comment by tuha263** [comment]
Seem the test users were not in the "Active" demographic any more so they can't vote, can you check to create a new world (to remove all test user then create again) or make the election which doesn't require "Active" demographic

**Comment by IcedForge** [comment]
If i create and use a new election process which uses Everyone it works fine, but if i have the default basic election requiring Active demographic it will not function.

This can be used with bypass since i can select which election process to use  (it just requires me to create a new one to add in the constitution instead ) so i will reopen but pushed to 9.3 instead.

**Comment by tuha263** [comment]
The reason we didn't count players as Actives is we use Greater as the Condition. So even we set the requirement to 0 hours a day, but if the test players had not log in then they would not count as Actives. So I will change the condition to GreaterOrEqual.

**Comment by SlayksWood** [comment]
It still doesn't properly work:
![image](https://user-images.githubusercontent.com/45708377/107346629-fa02d500-6ad5-11eb-966d-870d4f6990ab.png)
The screenshot shows that they are voting. But I vote first (being one Active player), then the elections are over and their votes are not counted.

**Comment by SlayksWood** [comment]
It still doesn't work for me.(
Steps to reproduce:
- place capitol, court or something else, just start a new election:
https://drive.google.com/file/d/1oUBOiK8yMQEQoc9V-DLXOEsKbpi5_q5d/view?usp=sharing
- use /civics addvotes
- check votes in web:
![image](https://user-images.githubusercontent.com/45708377/120967224-ea3b8a80-c76f-11eb-9bdc-40aff247117a.png)

I use default basic election:
![image](https://user-images.githubusercontent.com/45708377/120967580-528a6c00-c770-11eb-8c36-15bce573041b.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/123046116-5ff85500-d404-11eb-8a09-2e0e1f66ba33.png)
