### ISSUE TITLE
[0.9.2 develop-103] Strange notifications(?) when claim land

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19137]
They can be easy overlapped with other UI:
![image](https://user-images.githubusercontent.com/45708377/98242273-3fff4880-1f7d-11eb-929c-becfc4b6de93.png)
Need more love here.
The bottom could be wrong align:
![image](https://user-images.githubusercontent.com/45708377/98242376-71781400-1f7d-11eb-9831-55911c2a0065.png)
Step to reproduce:
- select block which out of property
![image](https://user-images.githubusercontent.com/45708377/98242396-7d63d600-1f7d-11eb-8ea6-a637236506d4.png)
- then select the block that is on property  border. 
![image](https://user-images.githubusercontent.com/45708377/98242467-95d3f080-1f7d-11eb-807a-21bd3f5562a1.png)

**Comment by IcedForge** [comment]
The bottom text "This plot is already claimed" should not be a static 'error' it should only really display when you attempt to claim something that is already claimed OR you are unauthorized on a claim.

As it is an error type situation it should not be visible when you CAN interact with that claim, IE left click is possible as it is your claim.

Would also make sure that the "Claiming property plots" tooltip is aligned with the tile lookup information, it looks very weird right now and not sure about the massive font size?
