### ISSUE TITLE
USER ISSUE: cannot vote

### ISSUE THREAD

**Issue by IgneusTempus** [StrangeLoopGames/EcoIssues#19144]
\
**Version:** 0.9.1.1 beta release-107

**Steps to Reproduce:**
trying to submit a vote.

**Expected behavior:**
vote should be submitted

**Actual behavior:**
Error: {"Errors":{"RankedVotes[0]":["Could not convert string to integer: Yes. Path 'RankedVotes[0]', line 1, position 61."],"RankedVotes[1]":["Could not convert string to integer: No. Path 'RankedVotes[1]', line 1, position 66."]},"Type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","Title":"One or more validation errors occurred.","Status":{},"Extensions":{"traceId":"|5d5c033c-455d85c72b6d525a."}}

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IgneusTempus** [comment]
disabling addblocker seem to works

**Comment by SlayksWood** [comment]
merged to #19120
