### ISSUE TITLE
Undiscovered Tall Boots Requires Tailoring or Carpentry

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19148]
Undiscovered Tall Boots Requires Tailoring or Carpentry

![Untitled](https://user-images.githubusercontent.com/32143431/98316421-5ec70480-1fa8-11eb-9a03-2d0f05a25800.jpg)
0.9.1.1 beta release-107

**Comment by SlayksWood** [comment]
I guess it was maden so in 8.3.3 because you can use them wothout any specialty when create avatar. Carpentry was undiscovered in 8.3.3 at once. So this Boots should be always undiscovered.

**Comment by dmplatten** [comment]
I guess I was just thinking that carpentry wouldn’t be required to make the boots. It seems like tailoring would be the only requirement.

**Comment by WeaselDog** [comment]
Great find! These boots will start discovered in next patch.
It says it requires Carpentry because the crafting table requires Carpentry, This could be more clear.

**Comment by dmplatten** [comment]
Thanks! yeah, that's what i was thinking about carpentry. It makes sense but it seems strange at first glance.
