### ISSUE TITLE
[0.9.2 develop-103]  Music plays intermittently

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19140]
https://drive.google.com/file/d/1tA_BHrj6Y2wOVXKZXvLhqy1KfkxcNjov/view?usp=sharing

**Comment by WeaselDog** [comment]
Still a problem in 9.2 release. There are extended breaks with no music. It should be playing music most of the time.

**Comment by Quadbro** [comment]
Fixed in Develop with a help of Leonard. Previously it was playing 8 hours of music for each day, now it has 16
