### ISSUE TITLE
Offscreen UIs don't get clamped to the screen when reopened

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1914]
easiest repro is to open a ui, put near the edge of screen, the close UI and change interface scale.

reopen the ui, and it will likely be off screen

**Comment by MarjieAVolk** [comment]
Seems to work fine for me

**Comment by MarjieAVolk** [comment]
I finally saw this - and it was caused by exceptions being thrown during UI open.  In this case, it was view manager problems.  So I don't think this is a bug of it's own at this point?

**Comment by MarjieAVolk** [comment]
I'm gonna actually change the position of the world object ui prefab so it's centered on screen - that should make it always show up even if there's an exception, then the actual error should be more obvious
