### ISSUE TITLE
Admins Demographic Requirements list "Citizen is an admin" twice

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19149]
Admins Demographic Requirements list "Citizen is an admin" twice

![Untitled](https://user-images.githubusercontent.com/32143431/98317049-b4e87780-1fa9-11eb-93f7-32be27d611e3.jpg)
0.9.1.1 beta release-107

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/98334922-07ab4900-2015-11eb-9a67-3007af30d51b.png)

**Comment by SlayksWood** [comment]
It fixed for a new world, but I still have this issue in migrated world:
![image](https://user-images.githubusercontent.com/45708377/100197625-9a9c1c80-2f0b-11eb-97d5-54036788a693.png)
