### ISSUE TITLE
USER ISSUE: I flow to space and can't play

### ISSUE THREAD

**Issue by SunriZZe** [StrangeLoopGames/EcoIssues#19146]
\
**Version:** 0.9.1.1 beta release-107

**Steps to Reproduce:**
dig stone

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@SunriZZe Thank you for the report.
1. Try to use /unstuck.
2. If unstuck doesn't help then ask you administrator to teleport you (/teleport targetto)
merged to #18805
