### ISSUE TITLE
[v0.9.1.1] Skid Steer creates non pickable rubbles

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#19143]
Skid Steer creates non pickable rubbles. 
You have to relunch the game in order to make disappear these rubbles from the client. These "fake" rubbles have a hit box in the client side.

UPDATE: Other players can also see these "fake" rubbles but they cannot pick it up.

**Comment by ThePiachu** [comment]
Dup #19100
