### ISSUE TITLE
USER ISSUE: Tür schließen

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19145]
\
**Version:** 0.9.1.1 beta release-107

**Steps to Reproduce:**
offene Tür, meine, inklusive Berechtigung
folgende Optionen werden angezeigt "Icon Rechte Maustaste - Open/Close" "E Setup Lock"

rechte Maustaste auf die Tür anwenden

**Expected behavior:**
die Tür sollte sich schließen

**Actual behavior:**
nichts passiert

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

- Kurze Info, das ist seit ein paar Versionen so. Gut das, mit dem "Alt"+rechte Maustaste "außerhalb der Werkbank" um "Work" hinzuzufügen, geht auch nicht 
- Hinweis: mit 2 verschiedenen Mäusen getestet.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@TimoNuernberg Thank you for the report. Can you tell more about your problem:
1. What is selected on the toolbar?
2. Provide log file. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. What language is setted on the server and on the client?
4. In which version did you have this problem first time?

**Comment by TimoNuernberg** [comment]
Hallo,
also, es geht meistens nicht, wenn ich mit der Schaufel ausgerüstet bin.
leere hand oder die Axt sind kein Problem, damit kann ich die Tür öffnen.

**Comment by SlayksWood** [comment]
merged to #3868
