### ISSUE TITLE
[Client] Skills instantly jumping to Lv.7

### ISSUE THREAD

**Issue by S3ranath** [StrangeLoopGames/EcoIssues#19159]
Hello Team, i think i have encountered a bug with new game starts in the current version of the game.

**ECO Version:** 9.1.1

**Expected behavior:** Upon starting a new game and investing a skill-star into a skill, the progress towards leveling up different skills should scale in a normal matter depending on collaboration settings.

**Actual behavior:** Upon starting a new game and investing a skill-star into a skill the survivalist skill jumps to Lv.7 and upon using the skill in which the star was invested that skill also jumps to Lv.7.

**Steps to Reproduce:** To verify that the game-data and config files are not out of date, the game was uninstalled and all traces of the game files were deleted. The game was freshly installed. This bug occurred on two different clients (Win10 and Win7) with two different steam accounts so it should be able to reproduce quite easily. The bug occurs on all collaboration levels. The only workaround i have found so far is opening up the server ui and setting all difficulty settings by hand and then resetting all skills. This bug also occurred in “Singleplayer” (No friends able to join) and multiplayer with one further client besides me logged into the server. The main problem is finding solid standard settings to play with without having to tweak the game files to get the wanted result. From what I observed through extensive tests yesterday night it seems like the new game screen settings aren’t writing their difficulty settings/values into the config file, resulting in the game always starting on the same settings regardless of collaboration level. Also if it helps the authlevel is Developer (But i have no idea if this is the normal authlevel for all users on the Server, this was the case before and after a reinstall of the game). The tests have also been performed on various skills (gathering, hunting, logging, mining) with the same outcome. If you need any more information to resolve this I am glad to help, I just recently got into this game and absolutely love the concept and idea behind it, you are doing a great job. 

PS. Sorry for my rusty English I'm just an IT Tech from Germany. Wish you all a nice day. Cheers S3ranath

**Comment by SlayksWood** [comment]
@S3ranath Thank you for the report. This is known issue and we have already fixed it. Fixes will be available in next release (0.9.1.2).
So merged to #19099

**Comment by S3ranath** [comment]
Ok thanks for the quick followup, can you please tell me what the usual base values are for 2 Player (I think its no Collab) so that we can play until the next patch? That would be very kind.
