### ISSUE TITLE
"projects required skilled" should be "projects require skilled" in the Crafting Component page of the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19155]
"projects required skilled" should be "projects require skilled" in the Crafting Component page of the Ecopedia

![Untitled](https://user-images.githubusercontent.com/32143431/98324016-2bd93c80-1fb9-11eb-911e-b111bc59d10c.jpg)
0.9.1.1 beta release-107

**Comment by WeaselDog** [comment]
Thanks for finding this and the great sceenshots! This will be fixed in the next patch.

**Comment by dmplatten** [comment]
you're welcome!
