### ISSUE TITLE
"the how the" should be "how the" in the Constitution section on the Government Overview page

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19152]
"the how the" should be "how the" in the Constitution section on the Government Overview page

![Untitled](https://user-images.githubusercontent.com/32143431/98319234-4e198d00-1fae-11eb-8604-02d739bcd318.jpg)
0.9.1.1 beta release-107

**Comment by WeaselDog** [comment]
Thank you!

**Comment by dmplatten** [comment]
you're welcome!
