### ISSUE TITLE
[0.9.1.1] Some wrong work order icons

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19156]
I noticed a few things have wrong icons displaying in their work order (in the circle):

Engineering Research Paper Modern looks like Advanced:
![image](https://user-images.githubusercontent.com/964559/98327940-88346000-1fa9-11eb-814c-489160600ce4.png)

Iron Axel looks like a Steel Axel:
![image](https://user-images.githubusercontent.com/964559/98327966-95e9e580-1fa9-11eb-967c-712a8fab4a26.png)

Iron Plate looks like a Steel Plate:
![image](https://user-images.githubusercontent.com/964559/98327980-9d10f380-1fa9-11eb-8fcb-210cb7d08cf3.png)

Iron Gear looks like a Steel Gear:
![image](https://user-images.githubusercontent.com/964559/98327991-a4d09800-1fa9-11eb-83f0-7c5c9593e2b9.png)

And AFAIR Iron Pipe also looks like a Steel Pipe. Could be more, generally it seems iron things have steel equivalent icons.

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 250
