### ISSUE TITLE
Artefacts at Show in world overlays (develop)

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#19162]
Repro steps: 
-Create district map
-Select it, put Show in world overlays

When go close to line of district it will show a lot of visual artefacts
![image](https://user-images.githubusercontent.com/53317567/98391613-9f209400-2035-11eb-919e-45c09db3f0ab.png)
![image](https://user-images.githubusercontent.com/53317567/98391702-bfe8e980-2035-11eb-99cd-ec486ca3ea1e.png)

Excepted behavior - uniforme color

**Comment by SlayksWood** [comment]
This is the old issue with claiming. 
merged to #9191
