### ISSUE TITLE
[0.9.2 develop-105] Ice Age after migration to 9.2

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19160]
Step to reproduce:
- switch to release version. delete configs folder and download it from steam to generate the right world (or just use WorldGenerator.eco.template):
save file: https://drive.google.com/file/d/1DsG-kPb1q3T_RIExlqXp_Hg3I6GYO27w/view?usp=sharing
- wait 10 minutes and check temperature with soil sampler:
![image](https://user-images.githubusercontent.com/45708377/98360898-b2cef900-203b-11eb-9fa4-623536aedc75.png)
![image](https://user-images.githubusercontent.com/45708377/98360932-bcf0f780-203b-11eb-8f34-0107029d2e1b.png)

- switch to develop version and check tempreture:
![image](https://user-images.githubusercontent.com/45708377/98361873-5ec51400-203d-11eb-972a-d75fed6a40b4.png)
- temperature is -10°C for every block and nutrients is missing:
![image](https://user-images.githubusercontent.com/45708377/98361961-8320f080-203d-11eb-862d-4cd2d4fbab6c.png)
![image](https://user-images.githubusercontent.com/45708377/98362047-a51a7300-203d-11eb-8954-5faec3fe5690.png)
- wait a few ticks and world will be in Ice Age:
![image](https://user-images.githubusercontent.com/45708377/98366021-5f14dd80-2044-11eb-8d24-0aef58e16dce.png)

**Comment by WeaselDog** [comment]
Can confirmed fixed with https://github.com/StrangeLoopGames/Eco/pull/7218
