### ISSUE TITLE
Confirm sleeping will actually make trees and crops grow

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19167]
Lots of reports of this not working

**Comment by D3nnis3n** [comment]
Also this: https://github.com/StrangeLoopGames/EcoIssues/issues/9057

**Comment by IcedForge** [comment]
Trees dont visually update on sleeping / fast forwarding, reconnecting will update them so they are visually updated. 
Crops are sort of in the same position, highlighting shows the full size crop but visually not properly updated.
All harvest yield / values are correct though this should be a priority fix as it is messing a lot with the singleplayer / smaller groups trying to speed up harvests and it is a confusing behavior.

**Comment by SlayksWood** [comment]
Trees and plants grow, but to update models you need either reconnect or refresh chunk. We have a small regression 
relatively 9.0 like problem with plants model, but this is the same issue like #9057. Why should we have 2?
