### ISSUE TITLE
The Paper Ecopedia links bring the user to the Wood Pulp page in the Ecopedia instead of the Paper page

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19172]
The Paper Ecopedia links bring the user to the Wood Pulp page in the Ecopedia instead of the Paper page

![Untitled](https://user-images.githubusercontent.com/32143431/98428770-10316d00-2071-11eb-9ff0-e8025ffd8265.jpg)

![image](https://user-images.githubusercontent.com/32143431/98428797-36570d00-2071-11eb-974c-16d3d4ac9153.png)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
It happens because you set 'Show only discovered items', but paper is currently undiscovered. This is other issue #17210
