### ISSUE TITLE
9.1.2 Server GUI/ingame commands resetting config files to old template

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19171]
![image](https://user-images.githubusercontent.com/61889138/98425212-3e707600-208c-11eb-99a3-622c66ec523d.png)

![image](https://user-images.githubusercontent.com/61889138/98425284-7c6d9a00-208c-11eb-91f9-f572a1bb1471.png)

![image](https://user-images.githubusercontent.com/61889138/98425219-47614780-208c-11eb-8b7a-3b2d3181ba0b.png)

Non admin user reports not seeing the command, this was working prior to 9.1.2, config file looks all correct same for the GUI, happening for another admin on my server too

 "UnStuckDisableTime": 15.0,
  "AdminCommandsLoggingLevel": "LogFileAndNotifyEveryone",
  "DelayNearbyFoodCheckMinutes": 4.0,
  "NearbyFoodSpawnLocationRadius": 20.0,
  "NearbyFoodSpawnCount": 5,
  "UseExactSpawnLocation": true,

**Comment by MishkaFur** [comment]
Update, seems to be fine if using the template but moment you save it via GUI it resets to the above snipshot of the config file whereas the new template is the below at the top of the file 

Surely where the line is in the file should not matter just that it is IN the file?

  "UseWaste": false,
  "MaxRepFromOnePerson": 30.0,
  "MinRepFromOnePerson": -10.0,
  "AllowDebugCalls": false,
  "AdminCommandsLoggingLevel": "LogFileAndNotifyEveryone",
  "WhiteList": {

**Comment by IcedForge** [comment]
Server GUI and Ingame server setting changes overwrite configs with old config data and does not use the newer updated templates causing a LOT of mixed issues.

Reproduction, 
Download server files ( doesnt matter which ones) 
Copy template and fix so its properly named for example User.eco
Now start server and add an admin it will change a lot of code inside the User.eco file and if you use whitelist or blacklist functions
it will cause crash on server loading.

**Comment by MishkaFur** [comment]
Update
commands not showing are an issue with Discordlink 2.1.1/EM-Framework but as per Forge's comment above, this issue has exposed another, renaming title of github issue

**Comment by MonzUn** [comment]
Latest DiscordLink with no EM-Framework =  No repro
Latest EM-Framework with no DiscordLink = Repro

The issue is with EM-Framework and I've let the author know.

It's nice that it unearthed this related issue of config overwriting though.
That may explain some odd cases where I've had the config now take changes properly.

Are the config files being overwritten using the template, or the config state in memory?
