### ISSUE TITLE
[0.9.1.2] UI displaying same store twice

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19175]
The store was picked up and replaced on the same spot - The game UI displays it twice but only one of them is "active" and exists.
See pics. The one that's active displays the Buy / Sells offers correctly.

![image](https://user-images.githubusercontent.com/32419758/98441376-1faac780-20fe-11eb-9c82-da6e7cb98e67.png)

![image](https://user-images.githubusercontent.com/32419758/98441377-233e4e80-20fe-11eb-88c4-3fd9ccf36e5a.png)

**Comment by SlayksWood** [comment]
@NemoLArs Thank you for the report. 
Ask the store owner to pick up and place the store again. After the upgrade to 9.1, stores glitch a little after the migration.
If it doesn't help please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and if possible provide save file. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by dutchuss2016** [comment]
this issue appears to fix its self on server restarts

**Comment by NemoLArs** [comment]
Is that enough? Servers that restarts.. like never? Should they have 8 copies of one store in thier UI and Y (economyviewer)? Which only one is correct and works? 

Seems odd to close this if it's not fixed! @SlayksWood
