### ISSUE TITLE
USER ISSUE: Room tiers impacted by stockpile inventory

### ISSUE THREAD

**Issue by darkarcher1** [StrangeLoopGames/EcoIssues#19174]
\
**Version:** 0.9.1.2 beta release-111

**Steps to Reproduce:**
tier 2 brick room no windows or door ...place several stockpiles down and fill with iron bars and other placeable blocks and tier will drop because it counts the blocks as what you used to build the room with

**Expected behavior:**
stockpiles holding materials for machines to use should not impact room tier

**Actual behavior:**
the materials in stockpile was counted as blocks used to build with

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes i have big shovel, colored vehical,and elspeths tailings mods installed and i have not played without to see if it has same results

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by darkarcher1** [comment]
![tier2 room specs](https://user-images.githubusercontent.com/36246984/98435690-150f1480-20a3-11eb-8a17-6d40a2a3734d.PNG)
![tier2 room](https://user-images.githubusercontent.com/36246984/98435692-193b3200-20a3-11eb-82dd-f8e314ec526f.PNG)

**Comment by darkarcher1** [comment]
even after removing the door and filling with brick still the same 1.77

**Comment by IcedForge** [comment]
This is an old and duplicate issue #9818 declared working as intended as building with stacked free blocks is possible.

**Comment by darkarcher1** [comment]
so if you have a very large room you have to put stockpile outside of it an hope they are close enough to be able to pull materials from???
