### ISSUE TITLE
The chopping motion to chop down a tree is vertical in 3rd person view, instead of horizontal like the first person view

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19178]
The chopping motion to chop down a tree is vertical in 3rd person view, instead of horizontal like the first person view

![Untitled](https://user-images.githubusercontent.com/32143431/98446382-254ae200-20eb-11eb-8888-691be05b94da.jpg)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
merge to #19058
