### ISSUE TITLE
A yellow oak slice cannot be sliced any smaller if it is laying flat on the ground in third person view

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19173]
A yellow oak slice cannot be sliced any smaller if it is laying flat on the ground in third person view

![Untitled](https://user-images.githubusercontent.com/32143431/98430803-5d680b80-207e-11eb-8acf-edaf8c2b8c68.jpg)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
It happens with thick trees when you hit end of tree. So to reproduce better using Old growth redwood:
![image](https://user-images.githubusercontent.com/45708377/98538823-68988280-229c-11eb-9e37-bf934a4905aa.png)
But this looks fine. To cut, you must hit the other side. Therefore, it may be worth doing this for all trees. But we should to change notification message.
Also I don't like behavior when you cut tree and you must first clear the tree from branches, you can do it from any side.
For some reason it seems to me that once upon a time it may have been, maybe in version 7.

**Comment by SlayksWood** [comment]
it fixed in 9.2 with https://github.com/StrangeLoopGames/Eco/pull/7227
