### ISSUE TITLE
User is brought to an incorrect page after clicking for Ecopedia help if that item is not discovered and Show only discovered items is checked in the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19181]
User is brought to an incorrect page after clicking for Ecopedia help if that item is not discovered and Show only discovered items is checked in the Ecopedia

This could be confusing unless the user realizes they need to uncheck that box before they can see the help they want.

0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
dup #17210
