### ISSUE TITLE
"Host a World" is not localized in Spanish

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19186]
"Host a World" is not localized in Spanish

![Untitled](https://user-images.githubusercontent.com/32143431/98449322-8df08980-2100-11eb-8ef7-0dc91184c304.jpg)
0.9.1.2 beta release-111

**Comment by D3nnis3n** [comment]
Same as here: https://github.com/StrangeLoopGames/EcoIssues/issues/19189
