### ISSUE TITLE
A lot of initializing messages are not localized for spanish

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19187]
A lot of initializing messages are not localized for spanish

Here is one example:
![image](https://user-images.githubusercontent.com/32143431/98449443-b75de500-2101-11eb-916e-df82e857b8a8.png)
0.9.1.2 beta release-111

**Comment by D3nnis3n** [comment]
Same as here: https://github.com/StrangeLoopGames/EcoIssues/issues/19189
