### ISSUE TITLE
[0.9.1.2] RIGHTS ABUSE - Ability to change Owner of property if we are in access list

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#19188]
If we are in the Access List of a property, we can change the Owner of this property to anybody !
This is a heavy rights abuse.
Moreover, we see the gear icon for all properties, even if we're not owner (we shouldn't see it, and I do believe we didn't see it in previous versions)

My pseudo is Zangdar:
![cap1](https://user-images.githubusercontent.com/7646137/98449462-26543180-2134-11eb-8daa-3559b8b05d7c.PNG)

I click on gear and put property to me:
![cap2](https://user-images.githubusercontent.com/7646137/98449463-27855e80-2134-11eb-8a9e-4683b459e05a.PNG)

If I'm not in access list, I can't change the owner.
![cap3](https://user-images.githubusercontent.com/7646137/98449465-28b68b80-2134-11eb-86b9-00b26976ea61.PNG)

**Comment by johnkslg** [comment]
Button is there so you can change it if a law allows
It should be only for owners though, thats a bug

**Comment by SlayksWood** [comment]
fixed 
![image](https://user-images.githubusercontent.com/45708377/98546739-37be4a80-22a8-11eb-91e5-76eaff7275bd.png)
