### ISSUE TITLE
"multiplied by you" should be "multiplied by your" on the Skills Overview page of the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19199]
"multiplied by you" should be "multiplied by your" on the Skills Overview page of the Ecopedia

![Untitled](https://user-images.githubusercontent.com/32143431/98454917-3c63f100-2138-11eb-8f44-e9d8f8ea573f.jpg)
0.9.1.2 beta release-111

**Comment by WeaselDog** [comment]
Thanks again for catching all of these!

**Comment by dmplatten** [comment]
You’re welcome!
