### ISSUE TITLE
A lot of the articles in the Ecopedia are not localized for Spanish, and they also include item tags such as (Economy|Economy Overview}

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19191]
A lot of the articles in the Ecopedia are not localized for Spanish, and they also include item tags such as (Economy|Economy Overview}

![image](https://user-images.githubusercontent.com/32143431/98449690-8383bf00-2103-11eb-92e9-184f2f55eec1.png)
0.9.1.2 beta release-111

**Comment by D3nnis3n** [comment]
Same as here: https://github.com/StrangeLoopGames/EcoIssues/issues/19189
