### ISSUE TITLE
Skill tooltip is displayed behind the choose skill dialog box when specializing in that skill

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19197]
Skill tooltip is displayed behind the choose skill dialog box when specializing in that skill

![image](https://user-images.githubusercontent.com/32143431/98453933-a080b800-212c-11eb-9882-9aefa94e8171.png)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/100991241-d4040600-3563-11eb-90a3-5c4283bbdc33.png)
