### ISSUE TITLE
Font size for the message Category is larger than the font size of the message

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19198]
Font size for the message Category is larger than the font size of the message, resulting in mis-alignment between the message and it's category

![Untitled](https://user-images.githubusercontent.com/32143431/98454341-8e554880-2131-11eb-98a1-c8e52a704590.jpg)
0.9.1.2 beta release-111

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging 1940.

I think this is not about the font size anymore. The misalignment is still noticeable. It gets worse as more information and message gets posted.![misalignment.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/7c941fa4-f94c-4850-857d-e1e15c4a92ac)
