### ISSUE TITLE
Carpentry Skill Book - Dendrology Research Paper Basic tooltip has inconsistent required amount of Research Papers

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19193]
Carpentry Skill Book - Dendrology Research Paper Basic tooltip has inconsistent required amount of Research Papers

tooltip - "requires 1.5" compared to the 2 required as shown by the Research Paper icon on the Crafting page.

![Untitled](https://user-images.githubusercontent.com/32143431/98452992-69a5a480-2122-11eb-8c98-7278246ced4b.jpg)
0.9.1.2 beta release-111

**Comment by SlayksWood** [comment]
@dmplatten Thank you for the report.
This is intented behavior for now. It always rounds up.
In your case seems it related with CraftResourceModifier = 0,5. But it also happen with modules.
If you start 2 books you will spend 3 Dendrology Research Paper Basic
