### ISSUE TITLE
9.1.2 Being in orbit (1550+ height) you do not fall nor unstuck works

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19194]
Being in orbit (1550+ height) you do not fall nor unstuck works

Specifically 1550 height for some reason, if you are over that height then you cannot fall back to the planets surface.

**Comment by SlayksWood** [comment]
1550 is something like Lagrange point, but seriously most likely the planet attraction ceases to work at this height. I don't think it's worth fixing, I guess this issue related with #18805

**Comment by IcedForge** [comment]
Needs to address the problem with /unstuck as it does not drop you down IF you are above a certain height.
the unstuck command should place you at "ground" level regardless of your Y: positioning
Still needs a priority release triage @WeaselDog

**Comment by mirasrael** [comment]
I tested on latest staging version and it seems to work with /unstuck now.
![image](https://user-images.githubusercontent.com/475445/100460040-8efd5100-30d7-11eb-952d-c51e2c2ed526.png)
after /unstuck
![image](https://user-images.githubusercontent.com/475445/100460074-9e7c9a00-30d7-11eb-9f53-33064b1b4aca.png)

**Comment by IcedForge** [comment]
Unstuck command seems fixed now (staging-1876) and with the fixes towards rubble space flight this should be ok.
