### ISSUE TITLE
The Meteor Tutorial tag link is displayed instead of the hyperlinked text on the Arc of Progress page in the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19207]
The Meteor Tutorial tag link is displayed instead of the hyperlinked text on the Arc of Progress page in the Ecopedia

![Untitled](https://user-images.githubusercontent.com/32143431/98469128-dd3fc400-21ab-11eb-8c03-9764155e6e1c.jpg)
0.9.1.2 beta release-111

**Comment by serpopov** [comment]
works in develop

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/99064924-b02e4f80-25b7-11eb-912f-e302be82b7f7.png)
