### ISSUE TITLE
"as individual member of a larger society, and the creating a" should be "as an individual member of a larger society, and the creating of a" on the Arc of Progress page in the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19208]
"as individual member of a larger society, and the creating a" should be "as an individual member of a larger society, and the creating of a" on the Arc of Progress page in the Ecopedia

![Untitled](https://user-images.githubusercontent.com/32143431/98469414-67d4f300-21ad-11eb-975b-bb400858d758.jpg)
0.9.1.2 beta release-111

**Comment by IcedForge** [comment]
And the creating of a positive interplay between individual needs and societal needs is critical to success
vs
And the creating(creation? feels like it fits better with previous sentence in mind) of a positive interplay by balancing between individual needs and societal needs as a critical part to success.
The spelling is correct now but it feels like the English itself is a bit odd for me with the double and part sentence building?
