### ISSUE TITLE
Mining, Logging and Gathering specialty experience is only 0.1 of what it should be

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19201]
Mining, Logging and Gathering specialty experience is only 0.1 of what it should be

![Untitled](https://user-images.githubusercontent.com/32143431/98455157-dc227e80-213a-11eb-9c4c-f933423ed605.jpg)
0.9.1.2 beta release-111

**Comment by dmplatten** [comment]
I can see where this may be working as designed. After looking closely at the other specialties, it makes sense that this value is specific to the skill and how frequently the skills are expected to be used (xp gain triggered).

**Comment by SlayksWood** [comment]
Yes, and for now if you use Mining or Gathering tools you have ExperienceMultiplier = 0,1, and this is intented behavior. But we have a separate issue #19039 for Logging, because it should depend on your damage.
