### ISSUE TITLE
0.6 #A6fb2ccf Trees warp around when colliding with wood pulp 

### ISSUE THREAD

**Issue by Mogdu** [StrangeLoopGames/EcoIssues#1921]
So at 171 calories the swing at those bad boys we're not clearing the pulp. And when cutting new tree in the pulp zone they warp around like crazy. 
It's due to the complexity of the hitbox of the wood pulp objects I suppose. 

Edit: Actually it doesn't matter if it's a pulp zone or not, the pulp spawn on impact and then the tree makes a huge jump regardless.

**Comment by keegan-o** [comment]
This is because we don't have custom collision on blocks yet. That will be the ideal solution rather than make the mesh too much simpler, though we will probably do some optimization there as well. In the meantime though we may make it a non-collidable object with a trigger.

**Comment by keegan-o** [comment]
Should be fixed now with no more collision on debris.
