### ISSUE TITLE
[0.9.1.2 beta release-111] Law remains uneditable in court after veto election

### ISSUE THREAD

**Issue by leachiml** [StrangeLoopGames/EcoIssues#19217]
You can't edit or remove a law from the court, after the election ended through an "Veto election" action. So you can't make a new Draft or edit it becouse it is still in the "Proposed" state. And you also can't start a new election for this Law on the "Ballot Box".

![Screenshot 2020-11-09 155355](https://user-images.githubusercontent.com/34484044/98557263-47d42b00-22a4-11eb-86c8-f4535e897acf.png)

![Screenshot 2020-11-09 155520](https://user-images.githubusercontent.com/34484044/98557293-502c6600-22a4-11eb-987d-8503f31a1ec9.png)

**Comment by JustinGianelloni** [comment]
I have been able to duplicate this as well. The only way I was able to remove a vetoed law was to use admin commands (/objects laws remove [law revision]).

**Comment by SlayksWood** [comment]
check with /civics vetoelection.
