### ISSUE TITLE
USER ISSUE: Can't remove tree debris when close to another tree roots

### ISSUE THREAD

**Issue by hairintd** [StrangeLoopGames/EcoIssues#19215]
\
**Version:** 0.9.1.2 beta release-111

**Steps to Reproduce:**
1. have a tree with empty space in the ground close to it's roots (like when you dig this cube and game said: you trying to dig, but the roots are too strong)
2. chop tree close to this to let debris appears at that space (close to the roots)
3. try to remove debris with axe or chainsaw without chopping the tree which roots have the debris close

**Expected behavior:**
debris should be removed (there should be a way to remove them without chopping another tree)

**Actual behavior:**
Game said: you tried to remove debris but the roots are to strong (and no way you can remove or move those debris)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5509694/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5509695/Player.log)

![20201109131612_1](https://user-images.githubusercontent.com/10298859/98528911-020c6800-228e-11eb-8a22-40e6733c10be.jpg)
![20201109131617_1](https://user-images.githubusercontent.com/10298859/98528920-033d9500-228e-11eb-8d07-3e8da762f51d.jpg)

**Comment by SlayksWood** [comment]
This should work only with digable blocks. But for now it seems works with all nearby blocks (Stones too)

**Comment by SlayksWood** [comment]
I added to 9.1.3 but we can push to 9.2.

**Comment by hairintd** [comment]
also same behavior with asphalt put in place of debris
