### ISSUE TITLE
Can't close Campsite window with "escape" key

### ISSUE THREAD

**Issue by Mkorny** [StrangeLoopGames/EcoIssues#19226]
**Version:** 
9.1.3 beta release-115

**Steps to Reproduce:**
1- Interact with a Campsite
2- Hit "Esc" to close the window and leave off...
3- You get to move, but the window doesn't close (it will when you move a few meters out of range)

**Expected behavior:**
Campsite window should close normally
I confirmed many other interactable items work fine (Tiny Stockpile, Stockpile, Campfire, Workbench, Tool Bench...)

**Actual behavior:**
Campsite window doesn't close -> until you hit the "x" on the corner; or move out of range

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

![image](https://user-images.githubusercontent.com/34373753/98608715-b8e70300-22e3-11eb-8017-c46342669f45.png)

**Comment by SlayksWood** [comment]
dup #19041
