### ISSUE TITLE
[0.9.1.2 beta release-111] Store "Quantity" not updated after permission change

### ISSUE THREAD

**Issue by leachiml** [StrangeLoopGames/EcoIssues#19221]
After changing the owner of the property to a title, no contents of stockpiles or chests will be recognised although they are displayed under "Storage":
![Screenshot 2020-11-09 193419](https://user-images.githubusercontent.com/34484044/98582159-d9eb2c00-22c2-11eb-9edd-32aa602dbe3f.png)

Storage Menu:
![Screenshot 2020-11-09 193442](https://user-images.githubusercontent.com/34484044/98582225-f4250a00-22c2-11eb-84d1-85ccf91f533b.png)

**Comment by SlayksWood** [comment]
@leachiml Thank you for the report. Do you have access to this title?

**Comment by SlayksWood** [comment]
Uh, seems I understand what you mean. You need to update this tab by link/unlink any stockpiles
![image](https://user-images.githubusercontent.com/45708377/98641028-2888dc80-233c-11eb-9e78-abe4c54ef6a0.png)
or just reconnect.

related with #18996, so merged.

**Comment by leachiml** [comment]
> @leachiml Thank you for the report. Do you have access to this title?

Yes, I have access to this Title, but I unlinked/linked all the Storages and reconnected to the server, but the problem is still there.

I also expirienced the bug from #18996 where the Store UI did not update on a different Land Claim, but as you said, I fixed that with a relog.

Here is some Information, how I think I created that bug:
> The Problem occured after, I changed the Owner of the Property (as a Authorised user) to a Title (which I have access to). The Shop was first placed (before the owner change) by the Owner of The Property, but I recreated the bug on the same Property afterwards with a different Shop placed by me. I also placed new chests and stockpiles but the problem still occures. When I tried  to change the Owner back to the original one, the Problem is still present.
