### ISSUE TITLE
9.1.3 Unable to remove any fuel from vehicle/table

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19227]
Unable to remove any fuel from vehicles nor tables, this occurs whether I am only person authed on the vehicle or claim.

Applies also if hitting object with a hammer
![image](https://user-images.githubusercontent.com/61889138/98610108-cb167080-22e6-11eb-826a-2c0563023938.png)

am able to add fuel though

**Comment by aaronstatic** [comment]
This bug has rendered our server unplayable and we've had to shut down since there is no longer an option to roll back via the steam "betas" tab. Why was this removed and when will there be a response to this bug?

**Comment by SlayksWood** [comment]
merged to #19231
