### ISSUE TITLE
USER ISSUE: Brennholz aus der Feuerschale nehmen

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19228]
\
**Version:** 0.9.1.3 beta release-115

**Steps to Reproduce:**
man lege Log in die Feuerschale und dann versucht man es wiede heraus zu nehmen 	

**Expected behavior:**
kein vorrat mehr in der Feuerschale

**Actual behavior:**
"Sie haben keine Berechtigung das zu machen; (seit dem aktuellen Patch) vor dem Patch (also vor 5 Stunden) ging es noch

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #19231
