### ISSUE TITLE
The Movement tutorial is not listed on the Tutorials page

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19237]
The Movement tutorial is not listed on the Tutorials page

![Untitled](https://user-images.githubusercontent.com/32143431/98622775-491f4b00-22d8-11eb-8d20-098455f2fd87.jpg)
0.9.1.3 beta release-115

**Comment by SlayksWood** [comment]
@dmplatten Thank you for the report. Why did you decide that it should be displayed here? 
Not all tutorials are displayed here, only tutorials that have special information before doing. So you can to check it second time. You can click on this tutorials and see second time.
This is intended behavior, closed for now.

**Comment by dmplatten** [comment]
You’re welcome. Oh okay, I thought all of the tutorials except this one were listed there. Thanks.
