### ISSUE TITLE
bloomery  fuel error

### ISSUE THREAD

**Issue by Kyrasq** [StrangeLoopGames/EcoIssues#19238]
trying to move my bloomery but cant because it saying i don't have autho on removing the fuel i try adding more and i different type of fuel to see if it would fix but not it failed and now that's stuck in there as well plz fix asap

**Comment by SlayksWood** [comment]
@Kyrasq Thank you for the report. 
1. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Provide screenshot with notification and Bloomery/ Fuel tab

**Comment by Kyrasq** [comment]
yes
i am  it used to work back in 9.1.1 and 9.1.2 i think

**Comment by Kyrasq** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5515180/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5515183/Player.log)
 here is the logs hope it helps if not i'm happy to redo the problem again and re-post the logs this is a multi player server screenshots are coming trying to get it out of steam is a pain

**Comment by SlayksWood** [comment]
merged to #19231
