### ISSUE TITLE
9.1.3 Can't remove Fuel

### ISSUE THREAD

**Issue by Dekoser** [StrangeLoopGames/EcoIssues#19231]
\
**Version:** 0.9.1.3 beta release-115

**Steps to Reproduce:**
Having fuel (coal) in owned car (powered card; steam tractor) after version update

**Expected behavior:**
possible to remove fuel (to collect car from crash)

**Actual behavior:**
no autorization to remove fuel even as full owner

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Dekoser** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5514093/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5514098/Player.log)

**Comment by ThePiachu** [comment]
Multiple people reporting that on White Tiger

![image](https://user-images.githubusercontent.com/964559/98617446-ddc38200-22b3-11eb-9b5d-6c24393a366c.png)

**Comment by AlekzanderL** [comment]
I am also having the same issue

**Comment by StallEF** [comment]
@mirasrael  Coal from SteamTruck can't remove too
