### ISSUE TITLE
USER ISSUE: Skid Steer leads to ghost sandstones

### ISSUE THREAD

**Issue by seekbat** [StrangeLoopGames/EcoIssues#19249]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
Take Skid steer
dig tunel in sand stone

**Expected behavior:**
sandstone should only be taken to the inventory of the skid

**Actual behavior:**
stones get into the inventory and fall as ghost blocks on the ground. the stones on the ground have no interaction and after reconnect the stones disapear

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LsHallo** [comment]
Also having the same problem when digging gold:
![image](https://user-images.githubusercontent.com/22171518/98734672-9a940c80-23a2-11eb-8134-ed9e55ca69bd.png)

Can't pick up any of the stones lying on the ground.

**Comment by SlayksWood** [comment]
dup #19100
