### ISSUE TITLE
9.1.4 Nametag/sign text not visible through glass

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19248]
Nametags are not visible though glass

![image](https://user-images.githubusercontent.com/61889138/98693988-dca05c80-2368-11eb-9961-b2cc279dc69b.png)

Second pic is after moving so my char had a "clean" view of the other player
![image](https://user-images.githubusercontent.com/61889138/98694024-e4600100-2368-11eb-9d55-d24235f14ac8.png)

**Comment by SlayksWood** [comment]
I guess Nametag is blocked be mortared stone on first picture. I don't have this problem:
![image](https://user-images.githubusercontent.com/45708377/98777637-2a1cd800-2402-11eb-8284-a586184d7a29.png)
![image](https://user-images.githubusercontent.com/45708377/98777654-3143e600-2402-11eb-94eb-e15e2d0e21e4.png)
@MishkaFur Can you check it again?

**Comment by MishkaFur** [comment]
Its only through glass itself that it does not show

![image](https://user-images.githubusercontent.com/61889138/98789806-bb884c00-23fa-11eb-927b-9513151d3088.png)

![image](https://user-images.githubusercontent.com/61889138/98789836-c6db7780-23fa-11eb-98a1-4e23fe63b117.png)

**Comment by MishkaFur** [comment]
Appears it is affecting signs too, vehicle text is fine

![image](https://user-images.githubusercontent.com/61889138/98804969-d2d13480-240e-11eb-8cef-20125f33be07.png)

![image](https://user-images.githubusercontent.com/61889138/98804991-db296f80-240e-11eb-8687-15cef49474d1.png)

![image](https://user-images.githubusercontent.com/61889138/98805030-e7153180-240e-11eb-9b67-68ccadd53fb7.png)

**Comment by SlayksWood** [comment]
We have this issue. But it looks very strange:
![image](https://user-images.githubusercontent.com/45708377/99939601-83c6c000-2d7b-11eb-9d82-d91d9a587bc9.png)
a few steps back:
![image](https://user-images.githubusercontent.com/45708377/99939620-8a553780-2d7b-11eb-917d-6a8ec7873d8a.png)

**Comment by redwyre** [comment]
This is an issue with transparent draw order. Sometimes the glass is drawn first and when the text gets rendered it thinks it's behind a solid wall. Same issue with text and water.

Possible solution is to render sign and player text (maybe as alpha cut out) before other transparent objects.
