### ISSUE TITLE
StoreUI spams exceptions

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1924]
NullReferenceException: Object reference not set to an instance of an object
UI.StoreUI.<Update>m__5 (UI.TradeOfferUI x) (at Assets/UI/Scripts/WorldObject/StoreUI.cs:75)
System.Linq.Enumerable+<CreateGroupByIterator>c__Iterator5`2[UI.TradeOfferUI,System.Int32].MoveNext ()
System.Linq.Enumerable.ToDictionary[IGrouping`2,Int32,Single] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector, IEqualityComparer`1 comparer)
System.Linq.Enumerable.ToDictionary[IGrouping`2,Int32,Single] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector)
UI.StoreUI.Update () (at Assets/UI/Scripts/WorldObject/StoreUI.cs:75)

NullReferenceException: Object reference not set to an instance of an object
UI.TradeOfferUI.Update () (at Assets/UI/Scripts/ItemOrSlot/TradeOfferUI.cs:44)

**Comment by johnkslg** [comment]
fixed
