### ISSUE TITLE
9.1.4 store transfers incorrect (says paying you not "You paid")

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19247]
Bad_karma sold me items which my store is buying, the chat alert saying Sold 166 Sand, paying you 49.8 EDP, but I paid them.

Fairly sure this was reported before but could not find the github

![image](https://user-images.githubusercontent.com/61889138/98686650-b7a7eb80-2360-11eb-8426-70217e6d867f.png)

![image](https://user-images.githubusercontent.com/61889138/98686692-c42c4400-2360-11eb-97cf-0dd422d320b3.png)

**Comment by beastyn** [comment]
With new notification system we have unified message for seller and buyer
![bandicam 2021-01-14 11-48-26-388.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/4089d1f2-2f82-4f54-9978-b0652a4fb010)
