### ISSUE TITLE
[0.9.1.3] Land claims can't see all titles

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19240]
Today on White Tiger I wanted to claim some land and let some other groups use it as well - letting farmers farm and another mining corp mine. I wanted to authorise this group:

![image](https://user-images.githubusercontent.com/964559/98656839-ffddf400-22f5-11eb-8a7c-0162b04faee9.png)

However, I'm guessing because I was not part of that group I could not find that list inside of my land claim authorisation window:

![image](https://user-images.githubusercontent.com/964559/98656906-171ce180-22f6-11eb-9523-26e539fd8f9f.png)

I get that it's not that often you have groups between multiple groups, but it would be nice to be able to assign any group / title on land claims and probably other places too.

**Comment by Thibault-Brocheton** [comment]
for now you need to be manager of the title to see it in the list

**Comment by SlayksWood** [comment]
@WeaselDog @johnkslg 
Is this by design? I don’t remember such changes. To me, all titles should be available.

**Comment by IcedForge** [comment]
I agree, you should not need to be a manager of a title to add it to permissions for areas.

**Comment by johnkslg** [comment]
You should not need to be a manager of a title to select it correct, this is a bug.

Also, the text with 'defined by' is weird. It's supposed to display the full list of accessible users.  Just remove it though, players can see that in the tooltips for the demographics/titles/etc.
