### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by redeaglesss** [StrangeLoopGames/EcoIssues#19243]
\
**Version:** 0.9.1.3 beta release-115

**Steps to Reproduce:**
I am not authorized to remove fuel from trucks

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MishkaFur** [comment]
This has been resolved in 9.1.4 please update.
