### ISSUE TITLE
USER ISSUE: Some of chests disappears suddenly

### ISSUE THREAD

**Issue by hairintd** [StrangeLoopGames/EcoIssues#19245]
\
**Version:** 0.9.1.3 beta release-115

**Steps to Reproduce:**
Random bug, don't really know how to reproduce it, just kept playing for a while move around the map do stuff. When return to my food stores - no chests found where i left them (playing solo on private server). If i quit and reenter game chests will respawn where they actually was with all the stuff in. I got this bug for three times - today on 9.1.3, yesterday on 9.1.2 and long ago (when some of tables disappears too may be on 9.1). It's not visual bug, i can move on the chests position and interact, like they are really not here.

**Expected behavior:**
Chests be were they should be.

**Actual behavior:**
Chests disappearing (and tables possibly too)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5517233/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5517234/Player-prev.log)
Logs provided before restarting the game.

bug:
![20201110151519_1_chests_disappear](https://user-images.githubusercontent.com/10298859/98675150-ea56e180-236a-11eb-9b14-468a34be88bc.jpg)
after restart:
![20201110153802_1_game_restarted_chests_respawn](https://user-images.githubusercontent.com/10298859/98675147-e925b480-236a-11eb-82d3-52ae7fca1f80.jpg)

**Comment by SlayksWood** [comment]
merged to #16480
