### ISSUE TITLE
The experience displayed on the House tooltip is not multiplied by the server xp multiplier

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19253]
The experience displayed on the House tooltip is not multiplied by the server xp multiplier

the server xp multiplier on my current server is 25.

![image](https://user-images.githubusercontent.com/32143431/98751331-ee482b00-238d-11eb-8ce7-54a5e885efce.png)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
Multiply only Total house value:
![image](https://user-images.githubusercontent.com/45708377/98776844-c6de7600-2400-11eb-9724-9e0ffb838a5a.png)

**Comment by beastyn** [comment]
Fixed by someone already.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/100072432-4b8fb200-2e4d-11eb-90df-711c074e5da9.png)
