### ISSUE TITLE
All product values are negative for most of the Recipes listed on the Mining Specialty tooltip

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19251]
All product values are negative for most of the Recipes listed on the Mining Specialty tooltip

![Untitled](https://user-images.githubusercontent.com/32143431/98750118-200bc280-238b-11eb-8878-324bd43f2e11.jpg)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
@dmplatten Thank you for the report.
This is not a minus, this is a dash. I guess we can delete it to prevent confusion.
