### ISSUE TITLE
Tooltip for installed upgrades

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19256]
No Tooltip is displayed when hovering over a Basic Upgrade 1 module that is installed in a work table

![Untitled](https://user-images.githubusercontent.com/32143431/98753057-7c71e080-2391-11eb-803f-0794f563d111.jpg)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107338250-611b8c00-6acc-11eb-96b7-253b8dbbe059.png)
