### ISSUE TITLE
Seed Tooltips don't have the Ecopedia help icon in the upper right corner of the tooltip

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19257]
Seed Tooltips don't have the Ecopedia help icon in the upper right corner of the tooltip

![Untitled](https://user-images.githubusercontent.com/32143431/98754233-3f5b1d80-2394-11eb-9328-ca1c09ea2a05.jpg)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
dup #19236

**Comment by dmplatten** [comment]
This one is different than 19236 I think. That one was everything on the crafting page, while this one only applies to seeds, and it doesn’t matter where you view them from.
