### ISSUE TITLE
Destroying tree debris on a character that took the level 6 Logging talent "Cleanup Crew" still costs calories

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19252]
Destroying tree debris on a character that took the level 6 Logging talent "Cleanup Crew" still costs calories

![image](https://user-images.githubusercontent.com/32143431/98750599-601f7500-238c-11eb-8598-6f9745ba112e.png)
![image](https://user-images.githubusercontent.com/32143431/98750713-a4ab1080-238c-11eb-9d99-66555e273f32.png)
![image](https://user-images.githubusercontent.com/32143431/98750731-b1c7ff80-238c-11eb-91bc-97962dbda6c8.png)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
this's intended behavior. "no longer costs **additional** calories"
