### ISSUE TITLE
USER ISSUE: Sprung in die Höhe

### ISSUE THREAD

**Issue by Patrick021099** [StrangeLoopGames/EcoIssues#19250]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
Beim Stein abbauen werde ich in die Höhe katapultiert. Ich sehe nichts mehr, mein Bildschirm ist schwarz.

**Expected behavior:**
normal Stein abbauen

**Actual behavior:**
in die Luft schleudern

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #18805
@Patrick021099 
ask you administrator to teleport you (/teleport targetto) or use another teleport command.
