### ISSUE TITLE
Lost all my added items when I cancelled a project

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1926]
Steps to repro:
- Set up a work bench and a stockpile and link their inventories
- Add 10 logs to the stockpile
- Start a Small Wood Cart project at the workbench (it takes the 10 logs)
- Cancel the project (the logs disappear)

I stepped through this and CraftingComponent looks fine, it is adding the 10 logs back into the stockpile on cancel, and the inventory modification says it is a success.  It even seems to be adding 5 logs to two different stacks in the apply method.  So I'm at a loss - could be unique to the stockpile?

**Comment by metachronism** [comment]
this was stockpile related, its fixed in latest

**Comment by MarjieAVolk** [comment]
Think this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/1928 after all
