### ISSUE TITLE
Suggestion: Bracking vehicles or carts keep Text and autorisations

### ISSUE THREAD

**Issue by Fireztonez** [StrangeLoopGames/EcoIssues#19263]
Presently (v 9.1.4 and before) each time you break the carts or vehicles, the text you have wright on it and all authorizations you have set for other people is lost. This is little annoying to always have to retype the text and set the Authorizations correctly each time.

When you break signs or shops, all setting is keep in place, I imagine you can do the same thing for the carts and vehicles.

Thank's for your amazing game and all your work, you do an excellent job!!
Fireztonez

**Comment by SlayksWood** [comment]
Thank you for the report.
dup #15506
