### ISSUE TITLE
It is a little startling for the user to see all content disappear after entering 3 letters in the search box that aren't found in the Ecopedia

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19261]
It is a little startling for the user to see all content disappear after entering 3 letters in the search box that aren't found in the Ecopedia

The Ecopedia has to be closed and re-opened to see the content again.

![Untitled](https://user-images.githubusercontent.com/32143431/98758204-38380d80-239c-11eb-8210-c231e6e99c98.jpg)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
Do you try to delete 'abc'? If you delete it content will appear again:
![2020 11 11 ecopedia searching](https://user-images.githubusercontent.com/45708377/98774909-060ac800-23fd-11eb-93e8-6586a349787b.gif)

**Comment by dmplatten** [comment]
Yes, that worked most of the time I tried it, but then it didn’t work anymore. I had to close and reopen it after that.

**Comment by SlayksWood** [comment]
@dmplatten Can you provide log file when it happen next time?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by dmplatten** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/32143431/99013754-3e0a2c00-251f-11eb-932a-5d61f9662024.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5534051/Player.log)

**Comment by IcedForge** [comment]
Duplicate from #18831
BUT i did find the cause of the issue and that is by having "Show only discovered items" enable it will not update ecopedia search function.
