### ISSUE TITLE
Avatars blocked by plants again

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19274]
![image](https://user-images.githubusercontent.com/3536496/98875384-fb6a2600-2430-11eb-9f95-67c583f16687.png)
I added code to fix this while back here: https://github.com/StrangeLoopGames/Eco/pull/5867

Figure out why it stopped working and repair please!

**Comment by SlayksWood** [comment]
and we still have this one #12625
