### ISSUE TITLE
[0.9.1.4] When resigning from office, you should only see titles you actually own

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19276]
When you're resigning from office, you see all the titles, even ones that are drafted or proposed. You should only see the titles you actually have to keep things simple:

![image](https://user-images.githubusercontent.com/964559/98880694-2d818500-243d-11eb-8a59-96275b753691.png)

**Comment by Mattprass** [comment]
Does this now need to be assigned to QA?
