### ISSUE TITLE
Learned: 5 specialties under the Specialties Unlocked category of the Engineer Profession Tooltip even though 4 specialties aren't discovered yet

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19280]
Learned: 5 specialties under the Specialties Unlocked category of the Engineer Profession Tooltip even though 4 specialties aren't discovered yet

![Untitled](https://user-images.githubusercontent.com/32143431/98885022-413de300-245f-11eb-9ae5-a95cff89d956.jpg)
![image](https://user-images.githubusercontent.com/32143431/98885159-8f52e680-245f-11eb-9588-4f06792ea487.png)

0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
@dmplatten Thank you for the report.
seems all specialties always are learned  in this tooltip.

**Comment by SlayksWood** [comment]
This is similar to what was left from before 8.0 version of the skills.
and for now we should either remove this from tooltip or make it more suitable for current skills, Locked or Unlocked (Learned or Unlearned) specialties.
just renaming doesn't make it clearer.

**Comment by serpopov** [comment]
Actualy that does make sense - it shows which specialties does it contain, i.e:
![image.png](https://images.zenhubusercontent.com/5ee792a8129fd28407ccd591/e2b1d9c8-6bcc-4fab-8dfa-70147a2c0c49)
