### ISSUE TITLE
Cancelling a project doesn't give the correct resources back

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1928]

**Comment by MarjieAVolk** [comment]
Been stepping through CraftingComponent, and all it's math looks right.  I'm pretty sure this is an inventory system problem, perhaps to do with InventoryCollections?

In the couple of examples I just tried, I made an order requiring 100 stone and 100 logs, then cancelled and got back 90 and 90.  Tried again with those and got back 80 and 80.  I'm wondering if it's trying to put 20 items in the player's carried inventory or something?

**Comment by REPOSEECO** [comment]
may be this help  6.0 (bac3d6c8)
1. begin the game
2. 1 Skill point Basic crafting
3. 1 Skill point Hunting
4. Build a Workbench (!! no Chest no Stockplie !!)
5. Hit one tree
6. Collect 6 wood
7. Start the Project 28 Arrow ( 7 wood needed)
8. Wait until 86% the project had stopped
9. Click Collect --> 6*4 + 5 = 29 
10. Cancel the Project
11. You get 6 wood back
got to step 7. :-)

**Comment by REPOSEECO** [comment]
I. Start the Project A = 2 Storage Chest
II. Fill until 1 Wood is missing
III Wait until Project A = stopped 95%
IV. Start the Project B = 3 Stopile
V. Fill it with 10 Wood
VI. Wait until Project B = stopped 67%
VII. Collect you get 1 Stockplie
VIII. Build the stockpile & Link it to the Workbench
IX. Cancel Project B --> Project A start automatic cancel it (you have 5 sec)
X.   Done you have 24 Wood's

**Comment by MarjieAVolk** [comment]
Found more evidence: if I try to refund resources into the player's inventory, they are given the correct #.  But if I try to refund directly into linked inventories (which in my case was only a single stockpile), they are given an incorrect #.  Actually, this may be related to the stockpile inventory restriction?

**Comment by MarjieAVolk** [comment]
Repose just noticed, when this happens, you get a notification saying you added materials to the project.  It looks like the linked inventories are putting the refunded items back into the work order before it is fully cancelled!
