### ISSUE TITLE
[0.9.2.0 beta develop-111]Districts: Can draw district without seeing it

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19289]
If i select another district layer, my current view disappears but if i do not have the district layer i am editing as active, i should not be able to draw on the map as i do not have interactive cursor.
![Screenshot_64.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/56f7e691-983f-48c5-b4e8-2de32841622d)

**Comment by gzatravkin** [comment]
Check minimapEditor.cs . It should detect when overlay is not selected, maybe at Update method
