### ISSUE TITLE
[0.9.2.0 beta develop-111]Districts: Cannot exit edit mode via esc key under special conditions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19290]
Reproduce steps
Edit any district map
Hit TAB to hide cursor, then press escape key

Now you cannot get the cursor to appear with trying to use esc hotkey for exiting district editing
you can use the X in the top right corner but esc wont work properly due to hidden cursor.

**Comment by gabrielgindridev** [comment]
Can't repro. Current tab behavior also hides all UI. Only allows hiding cursor when there is no UI
