### ISSUE TITLE
[0.9.2.0 beta develop-111]Map Filter UX improvement: Adding folders/sorting for different layers by category

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19291]
Would like to see a massive quality of life improvement when using the map filters and looking at different layers.

Right now for example when looking into Plants we have a list of 120+ items which is very annoying when interacting with the map
this could get some very good improvements by categorizing further into sub folders.

Plants Group ( not sure but maybe rename this into something more sciency? This category does not have functional overlays anyway at the moment)
     |>Trees
------ |>Population
------ |>Yield Potential
     |>Plants
------ |>Population
------ |>Yield Potential

We also have Animals that are a bit unruly where we could split them into Population vs capacity to make it easier for players
where we could also further separate this into Land based and Sea/Water based animals which would help the management when more animals are added.

Animals
    |> Terrestrial Animals
------ |> Population
------ |> Capacity
    |> Aquatic Animals
------ |> Population
------ |> Capacity

**Comment by MishkaFur** [comment]
yes!

**Comment by johnkslg** [comment]
This is quite easy to do with the refactoring I did adding category sorting.  Sure, let's do it.

**Comment by SlayksWood** [comment]
close this one, I open another one #20507
