### ISSUE TITLE
Bulle de détails disparait

### ISSUE THREAD

**Issue by Vinkatsuki** [StrangeLoopGames/EcoIssues#19293]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
dans un stockpile ou dans l'inventaire, viser un item avec le curseur de la souris
la bulle de détail devrait apparaitre 

**Expected behavior:**
La bulle de détail devrait rester ouverte tant que mon curseur est sur l'item

**Actual behavior:**
la bulle de détail reste 1 à 2 secondes avant de disparaitre 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5533513/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5533514/Player-prev.log)

**Comment by Thibault-Brocheton** [comment]
@Vinkatsuki maintient appuyer control pour qu'elle reste ouverte.
Tu peux aussi désactiver cette option dans les options.

Attention, la prochaine fois, rédige ton issue en anglais !
Be careful, next time, write your issue in english !
