### ISSUE TITLE
9.1.4 Ignore/Mute can be done against admin

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19294]
Admin should probably exempt from being able to get ignored/muted due to the high chance they are actually needing to communicate with a player.

![image](https://user-images.githubusercontent.com/61889138/99001917-87fd0d00-2533-11eb-88b8-7056dcf79edb.png)

**Comment by IcedForge** [comment]
Dont see why an admin would /mute their coworkers in the first place regardless they can still use command to unmute.
As for ignore i dont really know why a player shouldnt be allowed to ignore anyone in particular if they find them bothersome

**Comment by WeaselDog** [comment]
There are situations where we would want this behavior.
