### ISSUE TITLE
The Waterwheel can be placed partially underground

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19299]
The Waterwheel can be placed partially underground

again, this does benefit the player but doesn't seem like it should be allowed.

![image](https://user-images.githubusercontent.com/32143431/99018761-dfe24680-2528-11eb-9b5d-b5e100de003e.png)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
returned #14577

**Comment by Bazzi89** [comment]
we need more ways to get mechanical power!

**Comment by dmplatten** [comment]
yes!

**Comment by Sekor2600** [comment]
link to https://github.com/StrangeLoopGames/EcoIssues/issues/2105
