### ISSUE TITLE
Disqus revive comment titles

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19295]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/78c1c06d-efed-4615-8a35-9f70ce578fd8)
https://disqus.com/home/forums/strangeloopgames/
Disqus used to pull the title of the comment section, like `Eco Updates: Tech-Tree`

But since, i added open graph to change the image, it now displays the same title for all comment sections `Build a Civilization in a Simulated Ecosystem`
This op:title is set to 'Eco'
But for some reason, disus uses the the first h1 on the page, which is `Build a Civilization in a Simulated Ecosystem`

See if you can find a way to get disqus comment title, to match the comment section, like it used to.

Note, this is hard to test, I haven't been able to get my test comments to display on the disqus. just had to wait til a user commented.

**Comment by denysaw** [comment]
Fixed (on staging for now). Proofs:
![image](https://user-images.githubusercontent.com/5720101/100469153-092cd600-30d6-11eb-8655-59355895451f.png)

![image](https://user-images.githubusercontent.com/5720101/100469178-1053e400-30d6-11eb-9683-ca9ce415ac42.png)
