### ISSUE TITLE
Objects with weight = 0 kg

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19300]
The Waterwheel weighs 0 kg

Seems like it would be quite heavy but for game purposes maybe something like 3 kg?

0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
- [ ] Icebox
- [ ] Waterwheel

**Comment by WeaselDog** [comment]
Thanks for reporting. We have an issue for this already: https://github.com/StrangeLoopGames/EcoIssues/issues/10043
