### ISSUE TITLE
Numerical format is not consistent for "labor performed" on the Project tooltip

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19301]
Numerical format is not consistent for "labor performed" on the Project tooltip

In this case there is "4000" without the comma on the left, and "4,000" with the comma on the right.
![Untitled](https://user-images.githubusercontent.com/32143431/99020008-a52ddd80-252b-11eb-817d-dafdf20026cf.jpg)
0.9.1.4 beta release-116

**Comment by SlayksWood** [comment]
depend on your localization. But I don't have space too:
![image](https://user-images.githubusercontent.com/45708377/99041431-f8d80f80-259b-11eb-9668-8073cd0f8cf2.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1940

Tested all languages.
