### ISSUE TITLE
[0.9.2 develop-112] Top notifications need improvements

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19306]
We need to add improvements when open it with hotkey 'N'

- [ ] First behavior when I don't have cursor:
- Scroll works with toolbar
- press N, top notifications will open.
- scroll should work with top chat.
- press another time 'N'
- top chat should close and scroll works with toolbar again.

- [ ] Second behavior with cursor(in tab mode):
- have cursor, press N
- top notifications will open.
- mouseover top notifications to scroll it
- press tab, top notifications should be closed. (Currently I need to press N again)

**Comment by johnkslg** [comment]
Make the tweens smooth too, I saw they were jumpy and weird (use dotween not itween)

I'd also like to see holding N show the notifications and releasing hide it, vs toggling it potentially, see how it feels.

**Comment by MrAnonymous110** [comment]
I implemented hold/release 'N' key to open/close the top bar.

**Comment by SlayksWood** [comment]
Much better now. I have one suggest with holding without Tab mode and just press in Tab mode, but this may not be clear to everyone. I think we need to look at user feedback first.
