### ISSUE TITLE
Rent in Economy Viewer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19317]
Extend the economy viewer with another tab that lists eligible properties for rent. 
Add columns for all the relevant values, like who is invited to become a resident, the move in fee, the amount, and a text listing entered by the landlord.

For the text listing, add a text field as part of the RentForProperty object that can be filled out by the landlord to describe the property.  The economy viewer rows for rent can be a bit taller to accomodate these longer entries, but can have them truncate with mouse-over showing the full thing.

For the cost and move-in fee columns: these can be either constants or calculated values. If they're constants, they should store and sort properly. If they're calculated, they should say 'calculated' with mouse-over giving the deed tooltip and showing the full description.  

You can probably handle this by just syncing all rent objects with the client, possibly on GlobalData.Obj, and displaying that list in the viewer.

**Comment by SlayksWood** [comment]
Rent was pushed to 9.3. So it was hidden for now. need to check in 9.3.
