### ISSUE TITLE
USER ISSUE: Launched off planet

### ISSUE THREAD

**Issue by okazagi** [StrangeLoopGames/EcoIssues#19314]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
I was mining, picked up stone from underneath myself.

**Expected behavior:**
Dropped me into the position of the stone

**Actual behavior:**
Launched me into space

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #18805
