### ISSUE TITLE
Test plan for residency and rent

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19318]
With residency and rent theres a lot of changes that need to get a thorough testing for 9.2, heres a list of things that should be checked before release.
- [x] Residency invitations work as expected with titles and demographics
- [x] Residency works properly with laws, with prevention laws able to prevent cases like eviction or manual removal.
- [ ] Rent charges properly, updating on residency status change, loads/saves properly without lost payments.
- [ ] Demographics and titles wages work properly when changing/adding/removing wages and changing/adding/removing users/groups.
- [ ] Rent works properly with changing plots on a deed
- [x] Ensure invitations sent to demographics and titles behave properly when the title is deleted or changed after an election 

Also any ideas for ease-of-use improvement feel free to file issues for them.
Thank you!

**Comment by SlayksWood** [comment]
Checked Residency stuff and created a couple of issues #19842 #19843 #19844 #19845
Push this issue to 9.3 because rent stuff was pushed to 9.3 too.
