### ISSUE TITLE
USER ISSUE: Not french !

### ISSUE THREAD

**Issue by VirusGamers** [StrangeLoopGames/EcoIssues#19319]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
because you put 1 sentence in French that the game is in French ?

**Expected behavior:**
Better translation

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i don't have the mods. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
All translations of Eco are community made on Crowdin: https://crowdin.com/project/eco-by-strange-loop-games
The french translation has 97% progress, languages with more than 80% translated are considered supported. The quality of the translation may vary, as it's a community translation.
