### ISSUE TITLE
Corn and wheat should act like rice - product being a seed as well

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19327]
I'm surprised this hasn't been mentioned as an Issue or Suggestion despite a few people remarking about it on regular basis - corn and wheat should be their own seeds, just like rice. With those plants you pretty much plant what you harvest.

This could be one approach to solve #12718 as well. Of course maybe some small balance run might need to be ran on top of the change to make sure you are getting a little bit extra wheat and corn to be as if you harvested a seed.

**Comment by WeaselDog** [comment]
Thanks for the great feedback, but we are going to leave this be for now. It is important that Farming specialty still has an important use and domesticated Corn & Wheat does require processing in order to extract the seeds.
