### ISSUE TITLE
[0.9.1.2 beta staging-1839] command /bt 4 not building roof blocks

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19320]
![bt_command](https://user-images.githubusercontent.com/26339332/99144337-f9dd6f80-2675-11eb-9bfb-9718bfd97d25.png)

**Comment by StallEF** [comment]
![2020-11-14 (13)](https://user-images.githubusercontent.com/26339332/99146978-07065880-268e-11eb-8770-fd83ce4900bd.png)

**Comment by SlayksWood** [comment]
merged to #14627
