### ISSUE TITLE
[0.9.1.4 beta release-116] Store behaves incorrectly when Property is Owned by a Title

### ISSUE THREAD

**Issue by leachiml** [StrangeLoopGames/EcoIssues#19322]
When you place a Store in a Property owned by more than one Player via a Title, the Store Shows "Sold Out" in the UI and you also can't buy anything. If you remove all players but one and re-place the shop, everything will work again (sometimes you don't have to re-place the Store becouse it updates).

Re-logging and Server restart does not help.

![Screenshot 2020-11-09 193419](https://user-images.githubusercontent.com/34484044/99153038-3628c400-26a6-11eb-949a-6d118ff9582a.png)

![Screenshot 2020-11-09 193442](https://user-images.githubusercontent.com/34484044/99153043-3759f100-26a6-11eb-9d03-de6e068a07ed.png)

**Comment by ThePiachu** [comment]
Wasn't this supposed to have been fixed with https://github.com/StrangeLoopGames/EcoIssues/issues/18530 ?

**Comment by IcedForge** [comment]
@ThePiachu The fix is applied on staging, so currently not on the live version but it is fixed.
