### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by redeaglesss** [StrangeLoopGames/EcoIssues#19321]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
i am in space (1576 block above ground)

**Expected behavior:**
i want to be on earth

**Actual behavior:**
i am astronaut

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@redeaglesss Thank you for the report.
Please ask your administrator to teleport you (/teleport targetto)
merged to #18805
