### ISSUE TITLE
USER ISSUE: Mouse escapes game

### ISSUE THREAD

**Issue by Austen002** [StrangeLoopGames/EcoIssues#19326]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
1. Open Game
2. Play and load into world
3. Turn 360 and find mouse out of screen (multimonitor)

**Expected behavior:**
It should have stayed within the game, as everytime I click I tab out from turning too far

**Actual behavior:**
Instead it should keep the mouse confined to my screen resolution and not move outside of it, otherwise issues arise where I tab out frequently	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting.
Could you provide a screenshot of your graphic settings?
Not seeing this problem with neither windowed nor borderless fullscreen personally no matter resolution etc.
Only part i can see is a slight concern is that when you tab and have free mouse movement it is not confined but this behavior is quite common for these types of games.

Would like some more feedback and understand under what conditions this is happening.
Do you have any mouse interacting software? Macro, autoclicker etc?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
