### ISSUE TITLE
USER ISSUE: Campsite UI don't close

### ISSUE THREAD

**Issue by dp1492** [StrangeLoopGames/EcoIssues#19329]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
1. Open Campsite
2. Close with ESC

**Expected behavior:**
UI window close

**Actual behavior:**
UI window don't close

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/19041

**Comment by SlayksWood** [comment]
dup #18756
