### ISSUE TITLE
Add occupancy to Storage Silo and Powered Storage Silo

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19331]
Storage Silo and Powered Storage Silo need to have their occupancy added.

**Comment by SlayksWood** [comment]
@Sekor2600 
Ladder/Frame in Powered Storage Silo doesn't have collider:
![image](https://user-images.githubusercontent.com/45708377/99798486-2eec3500-2b42-11eb-99eb-931328a810f3.png)

Strange highlight:
![image](https://user-images.githubusercontent.com/45708377/99798463-23007300-2b42-11eb-9e89-1f9705111f75.png)

**Comment by Sekor2600** [comment]
fixed in staging
