### ISSUE TITLE
9.1.4 Framed glass window corner loses "block" if near objects making it a U shape

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19330]
If you have 2 Framed glass window placed down then place two blocks behind it which makes it into a U shape, it loses the being a block until you remove the blocks behind it

![image](https://user-images.githubusercontent.com/61889138/99192162-45247a80-2769-11eb-8732-9c14a9de6642.png)

**Comment by SlayksWood** [comment]
merged to #19222
