### ISSUE TITLE
USER ISSUE: No server

### ISSUE THREAD

**Issue by ajr8200** [StrangeLoopGames/EcoIssues#19338]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
Cant start game wants me to check server logs. logs not there.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ajr8200** [comment]
![20201116_023550](https://user-images.githubusercontent.com/74530735/99226442-cacf1700-27b7-11eb-8fc9-f7f8604e2f07.jpg)

**Comment by SlayksWood** [comment]
@ajr8200 Thank you for the reprort. 
1. This folder is empty? Can you also check 'Dump' folder and provide last files from it?
2. Please provide your PC specification (include Operating System).

**Comment by ajr8200** [comment]
![20201116_032804](https://user-images.githubusercontent.com/74530735/99229273-c99fe900-27bb-11eb-9ce5-9081495ab340.jpg) gpu is a 1070 and a 3tb ssd. Where would I find the dump files?

**Comment by ajr8200** [comment]
[log_201116021931.log](https://github.com/StrangeLoopGames/EcoIssues/files/5545076/log_201116021931.log)

**Comment by IcedForge** [comment]
[02:19:39.887] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[02:19:39.909] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[02:19:39.934] [5] [ Info] [Eco] Loading mods... Finished in 7,800.7ms

@ajr8200
Please remove your "Eco_data/server/Mods" folder and redownload it / verify integrity if you are using steam
seems like there is incorrect / corrupt / faulty mods causing issues.

Would also like to see the server log as well which you should find in "Eco_data/server/logs"
To make sure there is not other things causing issues as well.

**Comment by ajr8200** [comment]
[log_201116021931.log](https://github.com/StrangeLoopGames/EcoIssues/files/5556938/log_201116021931.log)

**Comment by ajr8200** [comment]
Ive Deleted it and still a problem making my own world

**Comment by IcedForge** [comment]
It still contains mods recompiling errors.
Can you start the server.exe instead of starting the world ingame instead and see if you see any issues crop up?

**Comment by D3nnis3n** [comment]
Closing issue due to old age and missing information.
