### ISSUE TITLE
[0.9.1.4][BUG][Stockpile] Pipes outside stockpile connect with pipes in stockpile

### ISSUE THREAD

**Issue by Brandjuh** [StrangeLoopGames/EcoIssues#19336]
I have found a bug in the 0.9.1.4 version of the game, as you can see on the attached screenshot, pipes laid outside the stockpile are connected to to the pipes that are connected inside the stockpile.
![image](https://user-images.githubusercontent.com/26203955/99199093-014b6880-279d-11eb-9edc-e45af03a0db8.png)

**Comment by SlayksWood** [comment]
dup #9232
