### ISSUE TITLE
Need new art for tag "Fertilizer"

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19332]
We have a new tag "Fertilizer" that needs an icon. Currently it is used to determine what can go in a silo. It does not need to be too fancy.

**Comment by StallEF** [comment]
@WeaselDog  crowdin used "Fertilizers" now only, maybe use plural for group batter ?

**Comment by RobertMangano** [comment]
added icons to icon sheets and is labeled Fertilizer
