### ISSUE TITLE
USER ISSUE: Updating elected title results in loss of access to government account

### ISSUE THREAD

**Issue by DanielW093** [StrangeLoopGames/EcoIssues#19343]
\
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**
1. Create elected title
2. Create government bank account and give that elected title exclusive access
3. Pass a vote to update the elected title (which forces a name change)
4. The government bank account will not longer be accessible

**Expected behavior:**
The rights to the bank account are updated with the new title similarly to how the same person remains elected when it is updated (ideally we wouldn't be required to change the name of an elected title to change what powers it has) 

**Actual behavior:**
The bank account remains only accessible by the now deleted old elected title, meaning any currency in that account is lost

**Comment by IcedForge** [comment]
Thank you for reporting this.
Could you expand a little bit on what you mean by it forces the name to change? It should inherit and be named the same after the title is passed via election?

**Comment by DanielW093** [comment]
By default it adds the word revision to any change that is created, I believe. I suppose the intent is that the word revision doesn't actually get added to the title itself when the election goes through? I think in our case, someone manually changed it because they assumed that if they didn't we would end up with a role that was literally called "President Revision", so perhaps it's just a result of slightly unclear UX?

**Comment by IcedForge** [comment]
There is a split issue here.
Making a revision of a title should not remove them from the title it should inherit all its previous occupants and lists.
Seems like there is an issue with references not updating properly.

When making a revision to a title it 1. kicks any occupants, 2. nullifies access to accounts as the title did not properly inherit objects

![Screenshot_106.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c7a75a4f-c47e-44b1-a6b6-2db644f156b2)

![Screenshot_107.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/82486f67-33ca-45af-b353-15e5bf3f7e44)

**Comment by johnkslg** [comment]
Fixed! 
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/5f4d0593-f8f9-4974-ad4a-458036872656)
Thanks guys great report.
