### ISSUE TITLE
Add new residency related game values

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19344]
**float - ResidentPopulation**
- Returns the number of residents in/out of the given districts, or everywhere if none specified. Share code with District Requirements

**bool - Resident of District** 
- Returns true if a user is/is not a resident of a set of districts. Also shares code. 

These will allow making voting districts based on residency.

**Comment by SlayksWood** [comment]
A lot of games values were added, but need to test it a lot.
