### ISSUE TITLE
Automatic resident on own Claim

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#19357]
It is confusing that you have to add yourself as resident for your claim.
this would confuse many players with the new System. 
It would be better if, when you create a new claim, you would immediately be a resident.

**Comment by WeaselDog** [comment]
It would be nice to have this for the first claim, not all claims.

**Comment by johnkslg** [comment]
Yes, when you claim property if you're not a resident anywhere it should add you as one automatically.

**Comment by IcedForge** [comment]
I will second that, i believe there will be a lot of confusion to this.

Not sure if adding auto adding on every new claim though as this could get very confusing unless we have a residency button / menu where you can leave residency by remote to not have to find the claim you have it on.
