### ISSUE TITLE
[0.9.2 develop-115] Too big notification

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19358]
It should always return to its original sizes. Step to reproduce:
- find something that you can't use and will have notification:
![image](https://user-images.githubusercontent.com/45708377/99386145-0c101580-28e3-11eb-9e88-085cabc54bd3.png)
- press 'E' quickly many times. Notification will grow:
![image](https://user-images.githubusercontent.com/45708377/99386229-306bf200-28e3-11eb-9f44-b09c0e54959a.png)
- and another several hundreds:
![image](https://user-images.githubusercontent.com/45708377/99386292-4974a300-28e3-11eb-9491-c508a802f117.png)

**Comment by abaza121** [comment]
Can't reproduce, fixed by @ptitducanh here is a video of how it looks now 

https://user-images.githubusercontent.com/17747441/104284940-87451080-54bb-11eb-881d-b2338c5f701a.mp4
