### ISSUE TITLE
USER ISSUE: Step outside the Planet

### ISSUE THREAD

**Issue by elfrea** [StrangeLoopGames/EcoIssues#19364]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
Take a pick
hack on some rocks on the floor

**Expected behavior:**
Mine the rock and stay on the ground

**Actual behavior:**
Mine the rock and get launched outside the atmosphere, and get stuck. even when I log out and come back

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@elfrea Please ask your administrator to teleport you (/teleport targetto)
merged to #18805
