### ISSUE TITLE
Meteor color looks bad

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19379]
![image](https://user-images.githubusercontent.com/3536496/99602166-dee06780-29b5-11eb-91a8-118b2e4eded2.png)

It looks fluorescent blue, it should look like a rock behind the atmosphere. This looked better before. 
For reference, here's a giant banana behind the atmosphere. 

![image](https://user-images.githubusercontent.com/3536496/99602218-f7e91880-29b5-11eb-815f-5c2df6fbd8ae.png)

**Comment by ptitducanh** [comment]
Final results are approved by @keegan-o 
I pushed them to SVN trunks

![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/086edf5f-41f8-426e-a579-fb58cf9ee611)
![image.png](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/823e6401-27b7-42d4-b8a8-a80912528985)
