### ISSUE TITLE
 Glass Now has a weird edge effect inside after every 4 blocks 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#19376]
\
**Version:** 0.9.1.5 beta release-119

![snap7642](https://user-images.githubusercontent.com/29383891/99556623-ab9fd780-29b9-11eb-9c4f-28af7af73a5a.png)
![snap7643](https://user-images.githubusercontent.com/29383891/99556930-0802f700-29ba-11eb-95c9-5e95691d79a8.png)

Something has changed since Glass windows was updated, and it looks weird and not as nice as it used to

**Comment by Thibault-Brocheton** [comment]
Reported in https://github.com/StrangeLoopGames/EcoIssues/issues/18617

**Comment by Conchipedia** [comment]
Closing this as already info about this in another Github
