### ISSUE TITLE
USER ISSUE: can't pick up my projects

### ISSUE THREAD

**Issue by JLr61** [StrangeLoopGames/EcoIssues#19377]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
1. craft an item with a 0.0% resource needed

**Expected behaviour:**
it should put finished projects in a free storage

**Actual behaviour:**
but it stayed in the project in the crafting station

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, it doesn't have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@JLr61 Thank you for the report. Can you add more details?
I don't quite understand your description of the problem:
> 1. craft an item with a 0.0% resource needed

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
