### ISSUE TITLE
[0.9.2 develop-118] Displaying districts in Minimap

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19375]
- [ ] bug with displaying when creating the first district

Step to reproduce:
- create a new server
- check minimap, I don't have district map and it shouldn't be:
![image](https://user-images.githubusercontent.com/45708377/99531199-71cbd280-29b3-11eb-8a54-44c877c9d172.png)
- place capitol and ratify, place zoning office start to create district map. I have Districts when edit:
![image](https://user-images.githubusercontent.com/45708377/99531525-e7d03980-29b3-11eb-9f1d-52f693b63d78.png)
- submit and winelection:
![image](https://user-images.githubusercontent.com/45708377/99531596-06cecb80-29b4-11eb-97c7-6cf244c14bc9.png)
- open map and I have 5! 'Test map' draft, but I lost settlements:
![image](https://user-images.githubusercontent.com/45708377/99531654-1ea64f80-29b4-11eb-8b96-2f741d0b4568.png)
- but when I first time want to see (on my other new server) I don't have districts at all.
- restart client, all's fine:
![image](https://user-images.githubusercontent.com/45708377/99532415-5235a980-29b5-11eb-9bff-ab54e48a5a42.png)

- [ ] Displaying deleted disctrict maps.
Start to revise district map:
![image](https://user-images.githubusercontent.com/45708377/99532457-61b4f280-29b5-11eb-915e-dc4910dad265.png)
- delete revision and open map:
![image](https://user-images.githubusercontent.com/45708377/99532491-71ccd200-29b5-11eb-99a1-11fc62ff7952.png)
-start to revise again:
![image](https://user-images.githubusercontent.com/45708377/99532675-b9ebf480-29b5-11eb-96ce-5fb5d5216a4c.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5560089/Player.log)

**Comment by SlayksWood** [comment]
After winning election to adding District Map:
![image](https://user-images.githubusercontent.com/45708377/101142679-fdd23100-3626-11eb-83c6-2b67d7f60a61.png)
I still have Draft in name:
![image](https://user-images.githubusercontent.com/45708377/101142761-1b06ff80-3627-11eb-8a48-d00acb424b09.png)

**Comment by gzatravkin** [comment]
Check 
        void UpdateList(IEnumerable<IOverlay> list)
at OverlayManager.cs

It should update overlays names after changing of state
