### ISSUE TITLE
Stockpile visualizer seems to not render second block materials in truck stockpiles

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19378]
Glass in a truck does not have the support framework holding it in place like the stockpiles have

![image](https://user-images.githubusercontent.com/61889138/99600631-be380200-29f5-11eb-893d-1fff747a425d.png)

Pic in a stockpile below showing the support framework
![image](https://user-images.githubusercontent.com/61889138/99600669-ce4fe180-29f5-11eb-86e0-a39cd95b13e9.png)

**Comment by Sekor2600** [comment]
Added from https://github.com/StrangeLoopGames/EcoIssues/issues/21595
> ![grafik](https://user-images.githubusercontent.com/37456949/116152106-cce1be00-a6e5-11eb-9a2e-88593764f887.png)
> A part of Block is invisible on cargo areas
> 
> In Stockpile
> ![grafik](https://user-images.githubusercontent.com/37456949/116736998-f2760c80-a9f0-11eb-9081-8a5051d7e2d3.png)
>

**Comment by keegan-o** [comment]
Updated to medium from low because it affects more blocks now including new content in a glaring way, Todd (and I agree) is hoping to see if we can fix this for 9.4.
