### ISSUE TITLE
[CW] Disable 'Update subscription' button until current payment will finish processing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19387]
Step to reproduce:
- buy 1 world and several citiziens, complete payment. You will redirect to Worlds page:
![image](https://user-images.githubusercontent.com/45708377/99661560-119d6500-2a75-11eb-958b-71f63b1f9523.png)
- press Subscription, you will have payment notification:
![image](https://user-images.githubusercontent.com/45708377/99661582-195d0980-2a75-11eb-819a-9e3bcc936228.png)
- hide it and change world number, you will have window to choose region:
![image](https://user-images.githubusercontent.com/45708377/99661593-20841780-2a75-11eb-9649-827df601e307.png)
- select any region, payment notification disappeared, but if I refresh page I will have it again:
![image](https://user-images.githubusercontent.com/45708377/99661607-2843bc00-2a75-11eb-9b2f-eae8e1b6b091.png)
- So I can make another payment if I enter the numbers of the Server or the Citizens are different from the first ones.

**Comment by denysaw** [comment]
Done. Could be tested on Stagingland.

**Comment by SlayksWood** [comment]
Can we add any hint when I mouseover this button?
![image](https://user-images.githubusercontent.com/45708377/102189291-79ee3380-3ec7-11eb-87a6-c375a8fe692d.png)
Why I can't update subscription

**Comment by denysaw** [comment]
@SlayksWood Solved on Stagingland. Please, next time do not Reopen issue if there was done ALL, what has been described in the issue. Reopened equals not fixed. And this one was fixed. New wish - new issue, or bunch of wishes of the common topic in a single issue, w/o reopening it 10 times after adding 10 new thoughts ;) That's not making developer happy to got re-opens for a tasks, that actually were successfully solved ;) Thank you :)

**Comment by Ry4ndrew** [comment]
Confirmed fixed as of current web release.
