### ISSUE TITLE
Some notifications should to to the chat area of the screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19380]
![image](https://user-images.githubusercontent.com/3536496/99602361-2cf56b00-29b6-11eb-95d1-63c9118e0a38.png)

Right now only chat can go small text on the screen, but others should as well, such as when you receive items.  Also go through and add some other short, simple, temporary notifications that should go to the screen.  They can skip the notification log entirely. 

(it also appears that these notifications for picking stuff up arent temporary, they didnt disappear)

**Comment by beastyn** [comment]
@johnkslg I need little more clarification here.
Do you want to bring these kind of little notification on screen as it was in 8.3.3 though we've intentionally moved them to the top notifications in 9.0? Why do you want that?
![bandicam 2021-01-18 16-45-34-025.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/9ef6a6e1-bad9-4905-8339-f57e9c7924e4)
Question is: do we want to bring something back or do we want to make something new? Like a bunch of settings were a player will define what and where should be displayed?

**Comment by johnkslg** [comment]
Yes I want to bring those back, for things that are a direct result of your actions, but aren't so important they warrant an infobox. 

Notifications not a direct result of your current action can go to the notification bar as usual.
