### ISSUE TITLE
[CW] Export/Import Save doesn't work or works very strange

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19386]
tested on stagingland
- [x] Export save doesn't work at all

- [ ] I'd say that Import Save doesn't work too, but I managed to add a new world once. But it performed very strangely. So now I have 2 worlds in list:
![image](https://user-images.githubusercontent.com/45708377/99646939-2c1a1300-2a62-11eb-91ac-06cfeb2abe7a.png)
The world that I added, I generated on my PC, because I needed a world for testing, but I could not export it.
but I bought only one and can manage only one server:
![image](https://user-images.githubusercontent.com/45708377/99647041-4bb13b80-2a62-11eb-8850-cf931cd9c5e3.png)
Based on the server ping, you can see that they are on different servers. I always choose Frankfurt when buy World, but the loaded server has been started in San Francisco.

But currently I just have error when try to import world:
![image](https://user-images.githubusercontent.com/45708377/99650263-41913c00-2a66-11eb-9046-4a34e762195f.png)

**Comment by denysaw** [comment]
@SlayksWood Please, give me the problematic world, where Export doesn't work at all. Cuzz for me it worked from the first time a charm:
![image](https://user-images.githubusercontent.com/5720101/100457705-cf060900-30c2-11eb-9df2-7fdf911eadae.png)

**Comment by denysaw** [comment]
Tested with Kirill even on that exact problematic world and export worked ideally.
@j3fffff Check please with import, why it creates 2nd world? Probably CW API error... dunno :/

**Comment by j3fffff** [comment]
it could show duplicate servers on recent list, if serverid changed during import.
@SlayksWood next time you test it, can you check if server id changes?
