### ISSUE TITLE
[CW] Citizens glitch during rename

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19388]
Step to reproduce:
- open Citizens page:
![image](https://user-images.githubusercontent.com/45708377/99663443-ad2fd500-2a77-11eb-9b5f-3515e786b56c.png)
- place Reset Citizen:
![image](https://user-images.githubusercontent.com/45708377/99663477-bc168780-2a77-11eb-8b5f-ceeb376cfdf0.png)
- Enter already existed name in username field, you will have error:
![image](https://user-images.githubusercontent.com/45708377/99663536-d486a200-2a77-11eb-9d2e-3bb1ca9d2465.png)
- You can't edit this name anymore and can't reset citizen again:
![image](https://user-images.githubusercontent.com/45708377/99663675-039d1380-2a78-11eb-8d16-48325c0fdf1a.png)
- you need to refresh page to fix it.

Also you have Internal server error if you enter non-latin username:
![image](https://user-images.githubusercontent.com/45708377/99663802-38a96600-2a78-11eb-904a-035c354313b3.png)
and can't edit it anymore too.

**Comment by denysaw** [comment]
Could be tested on staging.
