### ISSUE TITLE
[0.9.1.6-beta-staging-1848]  Contract credit need localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19396]
words have not in crowdin now

![2020-11-19 (1)](https://user-images.githubusercontent.com/26339332/99717037-e5580780-2ab9-11eb-8704-20da5a06a2ca.png)
![2020-11-19](https://user-images.githubusercontent.com/26339332/99717039-e6893480-2ab9-11eb-921a-541e2e01b976.png)

**Comment by gabrielgindridev** [comment]
I believe it is being translated, we just don't have those combinations.

Tested using gibberish
![image](https://user-images.githubusercontent.com/65634950/100785993-3cca7180-33f0-11eb-9c6f-63c655f474fa.png)

**Comment by StallEF** [comment]
@gabrielgindridev i writed about what it have not in crowdin
