### ISSUE TITLE
Buy page changes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19398]
Couple adjustments for buy page:
![image](https://user-images.githubusercontent.com/3536496/99725793-72737000-2a6a-11eb-8692-1bc689bf162f.png)
- [x] Remove 'save your planet today', sounds too sales-y.  Replace with 'Click which tier you would like to purchase.'
- [x] Make icon have a 'buy' button. It's not clear to people you need to click these to buy.
- [x] Replace the word 'beta' with 'single copy' 
- [x] Compress the large vertical margins so you can see the info on a single page without having to scroll 

After selection:
![image](https://user-images.githubusercontent.com/3536496/99725911-a8185900-2a6a-11eb-83e6-186a1453fb43.png)
- [ ] Allow them to checkout first before setting up an account, go straight to payment from the button click.

**Comment by StallEF** [comment]
@johnkslg   why is the first stage called betta when it is a standard account, and betta is just an additional badge that is given to those who bought the game at the early access stage
![2020-09-12 (1)](https://user-images.githubusercontent.com/26339332/99758527-00029e80-2b03-11eb-8a90-1ac484927b8c.png)

**Comment by j3fffff** [comment]
@StallEF were still in beta,
so if you purchase during beta (2018 to now) then you get beta icon.
in future, after beta, new users will only get standard

**Comment by denysaw** [comment]
`Allow them to checkout first before setting up an account, go straight to payment from the button click.`

@johnkslg In such case if customer gonna have connection problems after successful payment, we won't be able to identify him, that he just bought Eco. Surely we could solve it via Contact Support (check his snapshots), but as I imagine it was made for this thing. But if you wish we really could skip.

**Comment by denysaw** [comment]
@j3fffff If here are mine part, please, edit description (add me near checboxes), thanx ;)

**Comment by j3fffff** [comment]
> `Allow them to checkout first before setting up an account, go straight to payment from the button click.`
> 
> @johnkslg In such case if customer gonna have connection problems after successful payment, we won't be able to identify him, that he just bought Eco. Surely we could solve it via Contact Support (check his snapshots), but as I imagine it was made for this thing. But if you wish we really could skip.

yes agreed. also requires significant code changes. so i would also recommend against this one.

**Comment by denysaw** [comment]
@j3fffff If there will still be need in implementation of last bullet (or any other new one, when logic changes would be need), please assign me back. Un-assigning myself for now to filter this issue from the list of current ongoing ones (opened 4th time already 😄 )

**Comment by j3fffff** [comment]
![image](https://user-images.githubusercontent.com/7343272/102565668-c6399f00-4092-11eb-8298-c6712b005b9d.png)

**Comment by StallEF** [comment]
@johnkslg @j3fffff  can we add - Additional Notes: Translations included in the game are made by our community on Crowdin, only the english language is official and made by us. Only languages that cover at least 80% of the strings in acceptable quality are marked as available here on Steam, but there are more than these available in the game. 
how it on steam but with active url on Crowdin ?
