### ISSUE TITLE
[0.9.1.6-beta-staging-1848] Dynamic/Static value in tooltip need localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19397]
crowdin have:
Dynamic value - can be affected by modifiers
Static value - not affected by modifiers
but not used in game

![2020-11-04 (14)](https://user-images.githubusercontent.com/26339332/99721199-e3914280-2abf-11eb-881a-970e70b016d6.png)
![2020-11-13](https://user-images.githubusercontent.com/26339332/99721213-e724c980-2abf-11eb-98a6-e965ed72a08e.png)

**Comment by gabrielgindridev** [comment]
@StallEF thanks, we appreciate the help!
A bit sneaky, but I managed to find them 😃

![image](https://user-images.githubusercontent.com/65634950/105050347-7280f380-5a4c-11eb-89c0-b42246ae0b90.png)
![image](https://user-images.githubusercontent.com/65634950/105050417-84fb2d00-5a4c-11eb-8481-618862e3d0e9.png)

**Comment by gabrielgindridev** [comment]
@WeaselDog can I just close?

**Comment by StallEF** [comment]
on [0.9.3 staging-1935] translate not work here

**Comment by SlayksWood** [comment]
It translates to gibberish but doesn't seem to use strings in other languages.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/116847553-6d0e7a00-abf3-11eb-943f-671e7709e3d9.png)
![image](https://user-images.githubusercontent.com/45708377/116847585-80b9e080-abf3-11eb-954f-9dcabdd8d737.png)
