### ISSUE TITLE
World layers in landscape are too bright

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19393]
![image](https://user-images.githubusercontent.com/3536496/99702906-44326800-2a4b-11eb-805c-f744ce49da7c.png)
They wash out the landscape and you cant see.  Find a happy medium that works for property too.

**Comment by johnkslg** [comment]
Make sure it works in minimap nicely

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107342053-cd988a00-6ad0-11eb-978e-96085b9fca17.png)
