### ISSUE TITLE
[0.9.2.0]Civics: Custom statistic count doesnt show +1 in description

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19406]
When you create a law such as 
![Screenshot_146](https://user-images.githubusercontent.com/24981362/99824966-b774d080-2b56-11eb-91a6-39ee6c966b2c.jpg)

Negative value usage is shown, and positive value above 1 is shown but if you have +1 it will not say this in descriptions and may be very confusing to a lot of players.

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/102050049-1f83a300-3df3-11eb-95de-5175af10a177.png)
