### ISSUE TITLE
[0.9.2 develop-121] Move trees to separate category

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19403]
delete them from plant and make tree:
![image](https://user-images.githubusercontent.com/45708377/99776061-51218b00-2b21-11eb-8a53-84e799b726f7.png)
like in web graph:
![image](https://user-images.githubusercontent.com/45708377/99776131-5ed71080-2b21-11eb-813e-5497960b026d.png)

**Comment by WeaselDog** [comment]
Can you remove Settlements tab at the same time?

**Comment by SlayksWood** [comment]
Trees are separated from Plants, but They were added to Plant Group that make extra click to find them. And this is very bad now.
Closed, I open a new one #20507
