### ISSUE TITLE
USER ISSUE: ECO Space Mission

### ISSUE THREAD

**Issue by Blackout443** [StrangeLoopGames/EcoIssues#19407]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
1. stand outside on a stoneblock
2. mine down on the stoneblock with a Pickaxe
3. get yeeted by the stoneblock that splits into 4 parts
4. see the world getting smaller and meet the asteroid
5. roam around the great emptieness 

**Expected behavior:**
It should have just splitted the Stoneblock into its 4 parts to collect.

**Actual behavior:**
Instead it send me to space like I would start a counterstrike against the asteroid with no chance to get back home. Now I'm floating around in space with a distance of 1467m to my next waypoint.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StallEF** [comment]
![382310_screenshots_20201115230440_1](https://user-images.githubusercontent.com/26339332/99875959-9bc80380-2c04-11eb-920e-4e17487ee561.jpg)

**Comment by SlayksWood** [comment]
dup #18805
If you stucked, please ask your administrator to teleport you (/teleport targetto).

**Comment by Blackout443** [comment]
The command /unstuck worked in the end pretty well. It is possible that you will land at the other end of the worlb but it's still better then floating in Space.
