### ISSUE TITLE
[0.9.2 develop-121] Possibility to move during avatar creation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19405]
After all the changes with cursor, we got a rather strange possibility.
Step to reproduce:
- create new server, connect first time to it.
- after the appearance of avatar creation window, the cursor will appear with a delay of half a second, and at this moment you can move. In general, I found this in such a way.
- But Currently you can to press tab and exit from tab mode durin avatar creation and move!
- need to prevent it again.

Seems I can  move on the loading screen when 'Loading World...' appears
![image](https://user-images.githubusercontent.com/45708377/99795959-b84d3880-2b3d-11eb-93e9-9d0d50445470.png)

**Comment by johnkslg** [comment]
Look how joyous he is though!

**Comment by SlayksWood** [comment]
checked in 0.9.2 staging-1860, still an issue, try not to use fast connection in unity or better try to use our staging build
