### ISSUE TITLE
[0.9.2 develop-121] Scroll with mousewheel doesn't  work if you mouseover text

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19402]
it works in non-red zone in chat, but in species tooltip it doesn't work at all:
![image](https://user-images.githubusercontent.com/45708377/99775329-2b47b680-2b20-11eb-8058-015ccb1adf5b.png)
The same in other UI's

**Comment by SlayksWood** [comment]
> ![animx22](https://user-images.githubusercontent.com/3536496/100267979-2fe9e180-2f09-11eb-89b6-3f6dcde8aabf.gif)
> It stops sometimes. In the gif I'm trying to scroll the whole time.

**Comment by gzatravkin** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/7249
