### ISSUE TITLE
Butchery Table rendering flickers/disappears

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#19409]
when you pass from behind the butcher table, at the last moment it "disappears"

Video
https://youtu.be/X003KcZcd6s

Perhaps this is due to this parameter:
Config
![изображение](https://user-images.githubusercontent.com/13696708/99868599-f2b5e480-2bd4-11eb-80d8-76ba16939aa9.png)

**Comment by SlayksWood** [comment]
Seems,we already have this issue. I can't find, let it be separate for now

**Comment by keegan-o** [comment]
fixed in develop, when I attempt to merge into staging, says there is a conflict so will let it just go in 9.4.

**Comment by keegan-o** [comment]
nvm, had to get something else manually into staging anyways so I threw this in too (and tested it), so it's in for 9.3
