### ISSUE TITLE
Setup Migration for Flat Steel Stairs

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19414]
We have a new block form for Flat Steel that has replaced the old Stair form. We need to make sure migration is setup for this for 9.2.

The old form is Stairs, and the new form is Float Stairs.

**Comment by SlayksWood** [comment]
Flat steel stair migration doesn't work. 0.9.1.6:
![image](https://user-images.githubusercontent.com/45708377/100084215-8862a580-2e5b-11eb-8c08-a3274d64447e.png)
0.9.2 staging-1853:
![image](https://user-images.githubusercontent.com/45708377/100084263-9a444880-2e5b-11eb-838d-93345aa7ea63.png)
