### ISSUE TITLE
Unable to buy/sell Composite Lumber in store

### ISSUE THREAD

**Issue by godgeneral16** [StrangeLoopGames/EcoIssues#19419]
Hi, i noticed that you cannot sell Composite Lumber in the store. When you search for it, you are unable to find it and add it to the list.
![afbeelding](https://user-images.githubusercontent.com/72979198/99907712-9e972700-2cde-11eb-847d-3da68d21e527.png)
![afbeelding](https://user-images.githubusercontent.com/72979198/99907719-a8b92580-2cde-11eb-91ad-ea7a6b90ca06.png)

**Comment by SlayksWood** [comment]
@godgeneral16 Tell me please what professions have you researched? Did anyone can make it now?
![image](https://user-images.githubusercontent.com/45708377/99961154-f8f7bc80-2d9e-11eb-8d43-ceaa43ca682c.png)
![image](https://user-images.githubusercontent.com/45708377/99961187-06ad4200-2d9f-11eb-9c8f-731d8b567cb9.png)

- after researching all specialties:
![image](https://user-images.githubusercontent.com/45708377/99961440-7e7b6c80-2d9f-11eb-972a-87d33125ca4f.png)

You also can use this:
![image](https://user-images.githubusercontent.com/45708377/99961485-97841d80-2d9f-11eb-864d-0d613ad3c149.png)

**Comment by godgeneral16** [comment]
Aah, okay. clear to me. we tried to setup an Admin shop, sort of, where you can sell Composites and Ashlar to the government. but nobody reached composites yet. i guess thats it then indeed. it can be closed then, as this is a clear explanation.
