### ISSUE TITLE
Christmas art!

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19416]
- [x] We can replace the item distribution station (or make an additional item) that is a christmas tree, and the more items in the stack to distribute the more presents are visible.
- [x] Make the elk have red noses and christmas decorations

Can add some other ideas too as time allows.

**Comment by SpiritOfAncientWherewolf** [comment]
In Russia, only the new year is celebrated in December. Christmas is celebrated on January 7.  But I have already started preparing for a month. I use the modkit to Animate the salute and prepare a Christmas tree based on the distribution station code :)
About Christmas trees and other things, better give us a normal modkit. A scene with an avatar model for creating clothes, and preferably at least a cart with all the scripts responsible for its work. You will see how many mods will appear almost immediately.

**Comment by keegan-o** [comment]
Christmas elk skin already exists! So it just needs code to switch it in however we want to do that.

**Comment by keegan-o** [comment]
Phlo we will want meshes and textures for a new stockpile present block-- so a 1x1x1 meter present, with a variant for when nothing is on top of it (so it can have a bow or lace sticking up in that case, but that disappears when something is put on top of it).

We also will want to get a decorated fir or spruce tree with lights in a stand/holder, probably ~3 meters tall.

**Comment by legionaw** [comment]
Let me say, first of all, that this would be awesome but as I said in my own [suggestion](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1275) earlier, I think I would like to also have Christmas tree as a separate decor item. But, secondly, @keegan-o a stockpile as a Christmas tree with presents and string of lights on distribution station would be also awesome. Can we have them as separate versions so we can keep them all year around? Or at least make them available as a separate DLC for server operators? Pretty please? :3

After all, we do have Carved Pumpkin decor item for Halloween all year around and it wouldn't be fair to not have that for Christmas decors available for crafting and placement year-around as well. :p

Alternatively, create a new tab / option in stockpile / distribution selection window to toggle Christmas tree. I'm a sucker for Christmas decor stuff and I want me a small Christmas corner all year around! :p

**Comment by legionaw** [comment]
I just belatedly realized the OP in this suggestion thread was made by @johnkslg of SLG. Whoops, sorry about that. But thank you for even considering Christmas decor stuff for Eco, nonetheless! Really appreciate it. 😻 Cheers!

**Comment by keegan-o** [comment]
Hooked up temporary skins for elk, items in block form, and distribution station in release branch. Also made tasks for longer term improvements for holiday content.
