### ISSUE TITLE
[0.9.1.5 beta release-119] Registrar title references

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#19422]
If you have a title from government office as user / manager on a title in the registrar and then do a revision on the title in the government office, the registrar don't fix the new reference. See pic.

![image](https://user-images.githubusercontent.com/32419758/99916619-770a8380-2d0b-11eb-8c9c-e40df832e50f.png)

**Comment by SlayksWood** [comment]
Need to check it in staging build after fixing #19373

**Comment by SlayksWood** [comment]
It works in 0.9.2 staging-1862. So closed for now.
