### ISSUE TITLE
[0.9.2 staging-1852] Face remover troubles with glass and lumber

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19427]
Use Lumber Wall and GlassWindow:
![image](https://user-images.githubusercontent.com/45708377/99939996-61817200-2d7c-11eb-8d17-fb1953a1460f.png)
![image](https://user-images.githubusercontent.com/45708377/99940240-d0f76180-2d7c-11eb-81c5-a3ecae5accb7.png)

**Comment by keegan-o** [comment]
If we need a solution on the art side like making glass window a different thickness let me know @redwyre , I would think perhaps glass window shouldn't count as 'solid' for the face remover? I can never remember how it works exactly or what options are available, but something like that.

**Comment by redwyre** [comment]
Ah, this is getting complicated. glass <=> glass should remove faces, but opaque <=> glass shouldn't...

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/119129430-93c80f80-ba3f-11eb-8baf-927f58b250c8.png)
