### ISSUE TITLE
USER ISSUE: Stuck in the air

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoIssues#19437]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
Mining under me, and it push me in the air far far away of the planet, and sometimes I fall back, but this time no

**Expected behavior:**
No jump 

**Actual behavior:**
Big big jump far away in the stratosphere. I'm stuck.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #18805
@lou-vier Please ask your administrator to teleport you (/teleport targetto).
