### ISSUE TITLE
[0.9.2 staging-1852]Civics: Government office elected titles wages confusion

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19432]
The wages part of the titles needs to have a better ui placement and description to clarify where does title permissions and customization end and what does the wages begin and what does it does previously this was not an issue as it was optional to enable them or not.

![Screenshot_10.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f152daf7-f385-4f86-a303-b38854e44f37)

Need to have some form of highlight stating "Wage" or somesuch with a more definitive border to separate the title permissions and requirements from its wages to make it more user intuitive.

**Comment by johnkslg** [comment]
The 'wages' title is supposed to be visible, its a bug that it's not appearing.
