### ISSUE TITLE
[0.9.2 staging-1852] Map UI element issue: background is incorrectly matched

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19430]
Background does not properly follow the border of the ui 
![Screenshot_7.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b8d27aab-e448-44d6-92af-04291a2f0b05)

**Comment by SlayksWood** [comment]
link #19430

**Comment by gzatravkin** [comment]
Seems like sime prefab tweak
