### ISSUE TITLE
[0.9.2 staging-1852] Government account creation option visible without permissions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19433]
I can see the option to create government account without the actual permission to do so.
Making it very confusing why i would have a button i cannot click on.

It used to be hidden unless i had a title permission for creating government acconts?
![Screenshot_11.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/abace379-446b-433c-b651-c497275bca5c)

**Comment by johnkslg** [comment]
Fixed!
