### ISSUE TITLE
Performance degradation still at large

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19440]
From user Twinsen:
 there seems to be CPU performance degradation, sometimes as serious as going from 100 fps to 15 fps. It happens slowly so it takes anything from 30min to 3 hours. It seems to be sped up significantly in endgame. Here's some thing that seem to help degrade performance:
  -> large draw distance(i just keep mine at minimum)
  -> moving around a lot, e.g. driving a truck to do trades
  -> underground mines with many objects(loose stone)
  -> moving around large player modifications, e.g. a city.
- that's unrelated to the server lag that happens quite often even on official servers. I was not a huge issue for me but I see players often complain about it(both server and/or client lag)

**Comment by asafteirobert** [comment]
Possibly the easiest way to reproduce is to:
- join an active official server in the endgame 
- wait for everything to load, look at a specific point and note your FPS
- explore the server, drive around active areas, player bases, shops, mines. 15 maybe 30 minutes would probably do it.
- return to the initial area and note your FPS, it would be much worse.

**Comment by ThePiachu** [comment]
I noticed that too on White Tiger. When the game first loads it's pretty nice and smooth, but after walking around and especially getting to the capitol area, the FPS drop a lot. After disconnect and reconnect things go back to being pretty smooth.

I think what might help would be unloading some chunks from client-side memory if you get too far from them.

**Comment by WeaselDog** [comment]
Closing as there has been significant improvements and we have issues for more specific things.
