### ISSUE TITLE
Shorter vote election processes not taking hold

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19441]
From user Twinsen:
"- on our server we made an initial consititution in which any "Active" can create a law with 24h vote. After we added the elected title for our leader, we wanted to allow our leader to create 14 hour "fast votes". We voted to creating the new election process, then voted on constitutional amendments, but they never seem to have taken effect, when our leader tried to make a law, after all that effort, they were still 24h elections. We assumed it's a bug where the game created the vote as "Active" instead of the elected title. I assumed there should be a drop-down to select which type of vote should be created, or maybe i'm still hoplesly confused"

@IcedForge can you check this and see if there's an issue?

**Comment by IcedForge** [comment]
Can confirm that basic election takes precedence over any other eligible election processes, also seems to be an issue with amendments are not properly added into the constitution list.
I can also confirm that the election processes does take effect, they are just not used if you are eligible for 2 different ones at the same time
There was an issue closely related #16230 but ill create a new issue for these 2 separate items please thank the user for bringing attention to this.

**Comment by IcedForge** [comment]
New issues 
Constitution not listing new amendments properly: #19447
New feature suggestion for changing out so election process is selectable : #19448
