### ISSUE TITLE
[0.9.1.5 beta release-119]Civics: Ability to select election process when proposing an object 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19448]
If you are eligible for multiple election types there is no way to select this and they just arbitrarily pick one at seemingly random so if i have a role as president and have a parliamentary voting system AND popular vote where i might think a law or title should be a general popular vote i want to pick a voting process everyone can vote on vs one that is closed off by public access which i cannot do at the moment and this is very frustrating at times and could be fixed by simply adding a sub menu / popup option when i click "Add changes to an election".

Suggestion: 
When clicking "Start Election"
![Screenshot_27](https://user-images.githubusercontent.com/24981362/100064077-57ba4600-2e32-11eb-8230-ecc9a5b6ab15.jpg)

Use something like this sub menu list
![Screenshot_24](https://user-images.githubusercontent.com/24981362/100063756-f5614580-2e31-11eb-8dd0-816388e33ab3.jpg)
But list each type of election process i am eligible to use ( don't just list everyone there as i should not see things i can't use anyway )
This should then be the process used in this election, as only the election draft creator can start the actual election this should allow you to select this lastly.

Now the election process is decided when adding the object into the bundle this would effectively change by this

The alternative depending on how complicated that change is would be to inject this change into when you add each article but then it would need to be set for each different object in the bundled elections and become unintuitive at best

**Comment by johnkslg** [comment]
Added this ability.  When the constitution provides a few ways to do something:
![image](https://user-images.githubusercontent.com/3536496/101428895-83b7db80-38b6-11eb-8ccf-8904f2e57066.png)
![image](https://user-images.githubusercontent.com/3536496/101428903-874b6280-38b6-11eb-9c00-66be05b36d2d.png)

It will now detect this and prompt you which one to use:
![image](https://user-images.githubusercontent.com/3536496/101428794-4fdcb600-38b6-11eb-923b-71c3f0d16c50.png)
![image](https://user-images.githubusercontent.com/3536496/101428953-a2b66d80-38b6-11eb-8600-f58822e2b8ad.png)
