### ISSUE TITLE
[0.9.1.5 beta release-119]Civics: Amendments not showing up

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19447]
Amendments done to the constitution does not reveal themselves in the list as added articles.

the constitution doesnt properly add new articles via amendments.
![Screenshot_21](https://user-images.githubusercontent.com/24981362/100063171-0fe6ef00-2e31-11eb-8661-0531eff2451c.jpg)

As you can see i have a lot more then just 7 articles
![Screenshot_22](https://user-images.githubusercontent.com/24981362/100063175-12494900-2e31-11eb-91d3-383e613930d2.jpg)

Regression as this worked in 9.0 previously

**Comment by SlayksWood** [comment]
need to test in staging after fixing #19352

**Comment by johnkslg** [comment]
It will cross out the removed ones:
![image](https://user-images.githubusercontent.com/3536496/101432591-fed0c000-38bd-11eb-84a9-69c7921fb374.png)


But new ones arent shown there, I dont believe they ever were. They should show up in the government list, though.

**Comment by IcedForge** [comment]
Fixed in staging 1866
