### ISSUE TITLE
Make a Chinese logo

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19455]
Our Chinese name is: 生态物语 

Need a stylized Eco logo we can use everywhere.  Perhaps the 4 letters in a globe? Or other options. Here's examples:
![image](https://user-images.githubusercontent.com/3536496/100135189-2182c380-2e3e-11eb-854d-00d5bce89747.png)
![image](https://user-images.githubusercontent.com/3536496/100135202-25164a80-2e3e-11eb-9d0f-178dab607b80.png)
![image](https://user-images.githubusercontent.com/3536496/100135209-28113b00-2e3e-11eb-8839-72c39e43a2a4.png)
![image](https://user-images.githubusercontent.com/3536496/100135221-2b0c2b80-2e3e-11eb-893a-95d15a4337fa.png)
![image](https://user-images.githubusercontent.com/3536496/100135227-2d6e8580-2e3e-11eb-8633-06847519fce5.png)

**Comment by johnkslg** [comment]
Perhaps something like this: 
![image](https://user-images.githubusercontent.com/3536496/100135407-73c3e480-2e3e-11eb-8823-9dd40a56e1cb.png)

**Comment by keegan-o** [comment]
push candidate till next sprint just because milenko will be OOT this sprint

**Comment by MilenkoTunjic** [comment]
How about something like this?![LogoRound_Larger.jpg](https://images.zenhubusercontent.com/5edf28cbb0dce5fc774483ff/ef127553-d27f-445d-a6fc-db616dda72b6)

**Comment by keegan-o** [comment]
I assume this needs action by someone reviewing what you've done next milenko? Or is it done?
