### ISSUE TITLE
Chests are stackable but picking up multiples won't stack them?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1945]
Seems like they should either not be stackable or get auto-stacked when picked up.

**Comment by Senbotsu** [comment]
Same thing happens with any inventory item. IE picking dirt ramps back up puts them in your inventory one at a time.  Same for the initial 5 arrows you get when you pick up hunting, they pop into your inventory as 5 single arrows that you have to manually stack.

**Comment by metachronism** [comment]
needs some more thought about how we handle unique items, pushing this back from 6.0.1 release

**Comment by Conchipedia** [comment]
Dirt Ramps and Stockpiles Still Not stacking together when hitting then with Hammer #6.0.3
