### ISSUE TITLE
9.1.5 Titles are not sorted alphabetically 

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19452]
As per subject, Titles are not sorted alphabetically but by ID number

![image](https://user-images.githubusercontent.com/61889138/100094118-716a8600-2e50-11eb-9380-d612bb4d04d8.png)

**Comment by SlayksWood** [comment]
Should they? Although if there are 20+ of them available, then we probably need to sort alphabetically, but it was always by ID

**Comment by MishkaFur** [comment]
They probably should sort alphabetically for ease of use especially when a large amount of titles are used, other elements sort alphabetically ie transfer money

**Comment by johnkslg** [comment]
Make sure it works in Bank too, which shares this UI

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107734612-deceda00-6d0e-11eb-9119-890615304e62.png)
![image](https://user-images.githubusercontent.com/45708377/107734644-fa39e500-6d0e-11eb-878d-0ae006d28923.png)
