### ISSUE TITLE
[0.9.1.5 beta release-119]Ecopedia: Missing information on stockpile

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19453]
Missing data on normal stockpile
https://cdn.discordapp.com/attachments/456533794657271819/780767163409498112/unknown.png
compared to lumber stockpile for example
https://cdn.discordapp.com/attachments/456533794657271819/780767534361214976/unknown.png

**Comment by IcedForge** [comment]
regular chests also suffers the same problem

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/104411788-1ade1600-557c-11eb-8686-7d1d7347343a.png)
