### ISSUE TITLE
[0.9.2 staging-1853] Flat steel door glass problem

### ISSUE THREAD

**Issue by JNordik** [StrangeLoopGames/EcoIssues#19462]
The glass of a flat steel door begins to rise upward if you start moving away from it. The same thing happens with the pictures on the signs.

_In the center of the screenshot._
![image](https://user-images.githubusercontent.com/27322047/100163912-c5fd1800-2ec7-11eb-9f53-f59734396bb3.png)

**Comment by Sekor2600** [comment]
fixed in Staging svn
