### ISSUE TITLE
[0.9.2 staging-1854] Wrong World Age after migration

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19468]
![image](https://user-images.githubusercontent.com/45708377/100192061-4b9db980-2f02-11eb-9511-fef3a4a821c9.png)
![image](https://user-images.githubusercontent.com/45708377/100192183-83a4fc80-2f02-11eb-9284-5220846ec07e.png)
Happens a several times. Last time I migrate this world: https://drive.google.com/file/d/1n8hmKzq3jee6qZvemHjLCavqCFq63nA_/view?usp=sharing

**Comment by mirasrael** [comment]
won't fix existing worlds, but fixed for new worlds and migrated worlds
