### ISSUE TITLE
Move Flat Steel out of root folder

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19461]
![image](https://user-images.githubusercontent.com/3536496/100156397-a92bfa80-2e5d-11eb-8c3c-531539530979.png)
It needs to go in art folder like everything

**Comment by keegan-o** [comment]
Not sure how these would have gotten here, I don't think Rob or anyone on the art team ever made a git commit/PR with them being added here. They can be safely deleted.

**Comment by keegan-o** [comment]
https://github.com/StrangeLoopGames/Eco/pull/7458
