### ISSUE TITLE
Pressing escape when logging into the game for the first time does not function properly.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19464]
Is this an editor-only problem?

**Comment by SlayksWood** [comment]
I guess it's all related with this issue #19425

**Comment by gzatravkin** [comment]
Investigated. Seems editor only thing. 

You can control+` now, and it works fine in staging in editor

**Comment by IcedForge** [comment]
Escape button wont work on first time logins on a server.
When you login into a server, create your character then proceed to perform an action ingame and the esc feature is no longer working so the only way to close down the game is to terminate the process.
