### ISSUE TITLE
[0.9.2.0 beta staging-1854]Civics: Inconsistencys with trigger item use with ramps

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19473]
With changes to ramps i also noticed this
Placing dirt ramp 
= item used: Dirt Ramp
= item used: None
= item used: None
= item used: None
= item used: None

Picking the ramp back up
= item used: Dirt ramp
= item used: Dirt ramp
= item used: Dirt ramp
= item used: Dirt ramp
= item used: Dirt          <--- This should not be Dirt, and this is also the detection tile when using tool to pickup

![Screenshot_63.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/052c5483-b835-44b7-968d-7a918964e89f)

Stone ramps with changes we now have

Placing ramp 
= item used: Stone Ramp
= item used: None
= item used: None
= item used: None
= item used: None

Picking the ramp back up
= item used: Stone Ramp
= item used: Stone Ramp
= item used: Stone Ramp
= item used: Stone Ramp  
= item used: Stone Road   <--- This should not be stone road, and this is also the detection tile when using tool to pickup

![Screenshot_64](https://user-images.githubusercontent.com/24981362/100232900-49028a80-2f29-11eb-9ced-1336479c0b17.jpg)

Placing down ramps works as intended 

Question here is should all ramp construction follow the same system as asphalt ramps?
@johnkslg

**Comment by IcedForge** [comment]
#18860 is the original behavior

**Comment by tuha263** [comment]
I will close this because we are going to refactor the Dirt and Stone Ramp so they will have the same behaviour with the Asphalt Ramp.

**Comment by IcedForge** [comment]
![Screenshot_52](https://user-images.githubusercontent.com/24981362/116052593-0da3ed80-a67a-11eb-901b-b99dbc338d58.jpg)
It doesn't detect tool used on placement even if you do hold a tool in the interaction but i think that's because it doesn't have a requirement for a tool to be placed and looks good enough until we get around to rework stone roads completely in the future. Good job at finally nailing this trigger problem with it that's been a major issue for a long time.
