### ISSUE TITLE
Scrolling entries makes an abrasive sound

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19479]
![animx22](https://user-images.githubusercontent.com/3536496/100270465-f87d3400-2f0c-11eb-9aa7-63f162061d70.gif)
Make the sound more subtle with less oomph

**Comment by SlayksWood** [comment]
It's hard to check without a first source
@johnkslg Can you check it?

**Comment by Quadbro** [comment]
@SlayksWood  Leonard tweaked hover sound, now its more soft and quiet
