### ISSUE TITLE
Bird sounds no longer exist in minimal loader 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19476]
The startup is supposed to be black screen, tree icon, with gentle bird sounds as it loads. Those bird sounds should seamlessly continue when the scene loads. It should also restart when the user disconnects and returns to title screen. This used to all work, please revive it. 

The sounds should be birds + city sounds we have at the title screen now. Post video with sound in PR please

**Comment by SlayksWood** [comment]
Birds were returned but still don't have them on main title.
