### ISSUE TITLE
Game started with no ambient sound or music

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19478]
![image](https://user-images.githubusercontent.com/3536496/100270101-67a65880-2f0c-11eb-9aed-a89c029b6f58.png)
Just silence. The player should be welcomed with a luscious soundscape of auditory delights.

**Comment by SlayksWood** [comment]
Staging 1877 still don't have any music and have a few enviroment sound.

**Comment by Quadbro** [comment]
Triggered svn changes once again (should work in builds now). Will need to investigate remote builds problem if not.

**Comment by IcedForge** [comment]
The newest staging build as of this comment (english) has 0 music track going on initial start, title screen and when you hop in on a server. 
It does have the bird chirping and ambience sounds but no music, which should always have priority to run its sequence on initial start and login i would think?

**Comment by Quadbro** [comment]
Found a problem, soundbanks are not copied to builds properly, fixing....

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Staging-1910

Issue: Still happening. There's still no music. There are, however, sound for wind, ocean, chirping of birds that can be considered as ambient sound.

Video Repro:
https://images.zenhubusercontent.com/47210472/51d9290c-8795-4e9c-9ea1-0cbe7f13b6df/2021_01_24_00_12.mp4

Feedback: It would be better if there can be background music. The silence and ambient noise gave me a feeling that this could be a horror game.

Example: (Video with background music)
https://images.zenhubusercontent.com/47210472/23213535-663e-4518-b750-e50494431129/with_music.mp4

**Comment by Quadbro** [comment]
@SlayksWood @IcedForge Should be fixed in release/staging. Issee was with build process on remote machine

**Comment by IcedForge** [comment]
I have it now running in build 167 while ingame, but it does not start guaranteed in the main menu which i think should happen.

**Comment by WeaselDog** [comment]
@IcedForge To be clear, the game starts with music and sound now when connecting to a server, but there is just no music in the main menu?

**Comment by Quadbro** [comment]
We have no code to start music in main menu, actually, only ambient sounds of town/birds

**Comment by Quadbro** [comment]
@WeaselDog @IcedForge The issue wasn't about main menu music, do we need to implement that?

**Comment by WeaselDog** [comment]
The issue was just for in-game. I will close the issue and we can reopen if the music does not appear in game
