### ISSUE TITLE
Scroll behavior misbehaving

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19474]
![animx22](https://user-images.githubusercontent.com/3536496/100267979-2fe9e180-2f09-11eb-89b6-3f6dcde8aabf.gif)
It stops sometimes. In the gif I'm trying to scroll the whole time.

**Comment by serpopov** [comment]
@gzatravkin thats related to event swallow in link text

**Comment by SlayksWood** [comment]
merged to #19402
