### ISSUE TITLE
Rooms sometimes don't like doors maybe?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1948]
At least there was some kind of room problem.  I built what should have been a normal valid room, with 2 2x1 windows and 2 1x2 doors, and it wasn't detected.  I put 1 log in one of the doorways, then it was detected.  I removed that log again and it didn't change.

**Comment by craig-jong** [comment]
I can't replicate this issue - if someone finds a way to do so please add it to this issue

**Comment by MarjieAVolk** [comment]
It's probably not actually related to the door, at this point I'm guessing it just missed a block placed event somehow.  I placed the last block in the upper corner, if that's relevant.  Possibly it's because that server was just messed up, or had threads that were backed up or something, because it was doing other weird stuff at that time too.

**Comment by craig-jong** [comment]
I'm closing this issue then - if this becomes a repeated issue we can look into it more.
