### ISSUE TITLE
Tooltip table not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19484]
![image](https://user-images.githubusercontent.com/3536496/100291329-57a16f80-2f32-11eb-8824-8577faa141a9.png)

**Comment by johnkslg** [comment]
This looks like its using HTML data to parse the table so it can be displayed in the web, which breaks the tooltips
Make sure and test the web display of tables to ensure you dont break that by fixing this (IE, always look into what the code youre fixing was intended to do and make sure you dont rebreak it)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/100414367-a19d6900-308a-11eb-82a8-de7b6d8af6f7.png)
