### ISSUE TITLE
Make Deeds exist in registrars in code

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19482]
Deeds need to be changed to derive from Simple Entry and be stored in a Registrar in code. This will allow them all the fixin's and priviliges that go with being in a registrar, such as appearing in the selection boxes in laws.   Once this is added, we can implement specifying specific property as in #17733

**Comment by johnkslg** [comment]
May go into 9.3 or later

**Comment by TwixterZ** [comment]
This changes made and completed in 0.10.0.0 Develop
