### ISSUE TITLE
Tooltips dont show up on laws dialog

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19483]
![image](https://user-images.githubusercontent.com/3536496/100291231-14470100-2f32-11eb-85e6-88c5840e278d.png)
Mousing over these, I can see the tooltip trying to appear, but its still behind the topmost dialog. 

/civics spawngov, then open the court to get here
Probably the case on others too

**Comment by IcedForge** [comment]
Is this on staging? Or develop.
Staging suffers from #19494 and using /civics spawngov can cause all kinds of issues on the built client at least.
