### ISSUE TITLE
[0.9.2.0 beta staging-1856]Civics: Can no longer apply effects from laws due to list not filled according to ui

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19492]
Can no apply laws as effects are not listed properly and wont work.

![Screenshot_1.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/4cc70975-907d-490f-91ef-1548a7a29056)
![Screenshot_2.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/05f030bd-ae1f-4c31-a280-30dfcfbb3431)

It is also not saving this field input
![Screenshot_12.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/feb54773-2cc6-4e26-a36b-bce8c22aa7f8)

**Comment by SlayksWood** [comment]
Still have problem with Message field, but I'm going to create a separate issue. Closed.
