### ISSUE TITLE
Negative weight

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1949]
Thought there was a bug for this, but couldn't find it.

When I placed a cart, my inventory weight went down.  When I picked it up, the weight didn't go back up.  Happened consistently several times in a row, not sure if it always happens.

**Comment by REPOSEECO** [comment]
#1904

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1904
