### ISSUE TITLE
Custom HTTP/API Requests

### ISSUE THREAD

**Issue by TheLoneRonin** [StrangeLoopGames/EcoIssues#19499]
In the [EcoModKit](https://github.com/StrangeLoopGames/EcoModKit) repository. There doesn't seem to be any wiki pages related to writing API requests.

I'm unsure of whether or not Eco actually allows you to write your own API requests. Ideally, I would just need to be able to do the following in C# using `System.net.http`:

```c#
using System.Net.Http;
using System.Net.Http.Headers;

...

HttpClient client = new HttpClient();
client.BaseAddress = new Uri(URL);
HttpResponseMessage response = client.GetAsync(urlParameters).Result;
```

**Comment by D3nnis3n** [comment]
Not a bug, not sure why you opened an issue for this? This question is best answered in our discord in the modding channels.
