### ISSUE TITLE
USER ISSUE: Stockpile

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#19496]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
Stockpile abbauen obwohl noch Mörtel gelagert wird

**Expected behavior:**
Nichts. Da das Lager noch mit Mörtel voll war.

**Actual behavior:**
Mörtel bleibt in den Kisten auf dem Boden und kann nicht mehr aufgenommen werden. Stockpile landet im Inventa

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
> Some stockpiles have become invisible
> ![image](https://user-images.githubusercontent.com/22171518/100388037-cad9dd00-3029-11eb-959b-2c3f67ab1a72.png)
> Can walk through them
> ![image](https://user-images.githubusercontent.com/22171518/100388055-d62d0880-3029-11eb-8485-f20032da7d0a.png)
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5604779/Player.log)
