### ISSUE TITLE
9.2.0 1856 Mods\UserCode readme.md not readme.txt

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19498]
As per title, usercode folder has a readme.md not a readme.txt 

Configs folder has a readme.txt

**Comment by redwyre** [comment]
What is the problem with it being a md file?

**Comment by mirasrael** [comment]
.md file allows you to use standard formatting which then may be displayed if you're using viewer supporting .md files (i.e. GitHub supports it as many other programs).

**Comment by MishkaFur** [comment]
No real problem with it being a .md but it is not inline with user friendlyness of the other readme being a .txt, perhaps just have both?

**Comment by mirasrael** [comment]
better to rename all to .md then

**Comment by redwyre** [comment]
I'll leave it up to you @mirasrael

**Comment by mirasrael** [comment]
Renamed Configs/README.txt to .md for consistency.
