### ISSUE TITLE
[0.9.2.0 beta staging-1856]Civics: Cannot create new sections in laws

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19491]
Can no longer create new sections clicking the plus inside the law interface.
![Screenshot_11.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2428d702-2ab5-4ffe-a2de-05c41dd89aab)

**Comment by SlayksWood** [comment]
A lot of pluses don't work:
![image](https://user-images.githubusercontent.com/45708377/100735952-1ce08100-33e3-11eb-907d-c7601671a3e4.png)
![image](https://user-images.githubusercontent.com/45708377/100735994-31247e00-33e3-11eb-909c-df105ac78402.png)
![image](https://user-images.githubusercontent.com/45708377/100736063-46011180-33e3-11eb-9369-1d111403ace0.png)

need to check this one https://github.com/StrangeLoopGames/EcoIssues/issues/19352 after fixing too

**Comment by SlayksWood** [comment]
check this one #19352 after fixing
