### ISSUE TITLE
[0.9.2.0 beta staging-1854] Impossible to create currency on the minting press

### ISSUE THREAD

**Issue by JNordik** [StrangeLoopGames/EcoIssues#19497]
It is not possible to create currency on the mint press. When you try to create, a prompt "Need to give your currency a name before you can craft it" appears, even if all textfields are filled in correctly.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/100414677-5041a980-308b-11eb-815b-63bd93af566e.png)
