### ISSUE TITLE
Waste Filter not working as intended

### ISSUE THREAD

**Issue by Sakarias411** [StrangeLoopGames/EcoIssues#19501]
I placed a waste filter, everything is connected properly, there's power, it's on a claim, and there's a stockpile next to it.
But the waste filter does not consume ANY power, it always shows as "0 watts"

Also, if you put a bend pipe on the output of the waste filter, it generates nothing as output, but it clears the input waste (infinite free waste blackhole?)

Power : 
![image](https://user-images.githubusercontent.com/4887819/100391038-8bfc5500-3032-11eb-94e2-8b1b6d46016d.png)

Flowing output : 
![image](https://user-images.githubusercontent.com/4887819/100391052-961e5380-3032-11eb-9006-e9cc453a2735.png)

Sewage input : 
![image](https://user-images.githubusercontent.com/4887819/100391061-9e768e80-3032-11eb-896a-72235e892e7c.png)

Water output : 
![image](https://user-images.githubusercontent.com/4887819/100391067-a3d3d900-3032-11eb-80fc-68aef3ee7985.png)

Status : 
![image](https://user-images.githubusercontent.com/4887819/100391075-a9312380-3032-11eb-8792-562b86dc08b0.png)

Game version : 
![image](https://user-images.githubusercontent.com/4887819/100391174-eb5a6500-3032-11eb-81e4-69bbe5c51413.png)

**Comment by LsHallo** [comment]
Same problem here:
Working, enabled and active but consuming 0W
![image](https://user-images.githubusercontent.com/22171518/100391084-ad5d4100-3032-11eb-933b-8903180ac6b6.png)
![image](https://user-images.githubusercontent.com/22171518/100391089-b0f0c800-3032-11eb-815f-9bc89cc802fe.png)
![image](https://user-images.githubusercontent.com/22171518/100391093-b51ce580-3032-11eb-836f-bdd3551f7b68.png)
Full setup:
![image](https://user-images.githubusercontent.com/22171518/100391116-c8c84c00-3032-11eb-8e17-21c1e562e1ae.png)

**Comment by SlayksWood** [comment]
I have reproduced a similar issue, but my filter could not work indefinitely without electric power.
merged to #18583
