### ISSUE TITLE
USER ISSUE: Storages are gone

### ISSUE THREAD

**Issue by RaynorsRaider** [StrangeLoopGames/EcoIssues#19509]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
Liek the titel said, some of my storages are gone. Came online and saw it. Some boxes are still at the same place but storage itself is gone. Not possible to set a new one. Nad the boxes can't be moved or crushed:/ Now they blocking ground. Strange.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #19496
