### ISSUE TITLE
USER ISSUE: pipes disabled because of invalid status

### ISSUE THREAD

**Issue by KEATONKK1** [StrangeLoopGames/EcoIssues#19507]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
try to use any machine with pipes tap

**Expected behavior:**
worked

**Actual behavior:**
was light red and had msg when hovered over it said disabled because of invaild status

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@KEATONKK1 Thank you for the reprort.
Can you provide a little more information? At least what craft station did you use? and status tab screenshot.
Also please provide log file. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
possibly related with #18397

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
