### ISSUE TITLE
USER ISSUE: non broken ore should be 2 pieces in inventory.

### ISSUE THREAD

**Issue by DanielStrohmeyer** [StrangeLoopGames/EcoIssues#19508]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
Use a skid and 

**Expected behavior:**
if you pick up a non brocken ore part with your skid (this bigger piece, that you can pick into 2 pieces with your pickaxe) you should get 2 pieces in youre inventory

**Actual behavior:**
you only get one piece from this bigger part in youre inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
applied egogistics, but without this mod its the same.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
tested on 0.9.3 staging, confirm this is still an issue

**Comment by WeaselDog** [comment]
Thanks for your report. This will be fixed in the upcoming 9.5 update.
