### ISSUE TITLE
[0.9.1.6] Price sorting - null should always be the last on the list

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19506]
Sometimes I like to check out what's the most expensive item to buy or sell on a server. However, when I sort items by the price descending, null prices are always on top:

![image](https://user-images.githubusercontent.com/964559/100402311-c523cd80-3010-11eb-8b00-fcfe2c3db8de.png)

This means that if I want to find the most expensive items I have to scroll down to the middle of the list, which is functionally the same as having to scroll down to the middle of the list when sorting by price ascending. Ideally, when sorting your most desirable results should be on the top.

**Comment by SlayksWood** [comment]
fixed in 9.2:
![image](https://user-images.githubusercontent.com/45708377/100415055-49fffd00-308c-11eb-9ca1-3833b1def894.png)
