### ISSUE TITLE
[0.9.1.7 release-126] Invisible stockpiles

### ISSUE THREAD

**Issue by LsHallo** [StrangeLoopGames/EcoIssues#19500]
Some stockpiles have become invisible
![image](https://user-images.githubusercontent.com/22171518/100388037-cad9dd00-3029-11eb-959b-2c3f67ab1a72.png)
Can walk through them
![image](https://user-images.githubusercontent.com/22171518/100388055-d62d0880-3029-11eb-8485-f20032da7d0a.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5604779/Player.log)

**Comment by LsHallo** [comment]
Happened as far back as 0.9.1.5
Prior to that don't know.

**Comment by SlayksWood** [comment]
merged to #19496
