### ISSUE TITLE
USER ISSUE: Flying away

### ISSUE THREAD

**Issue by dp1492** [StrangeLoopGames/EcoIssues#19505]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
Mine below my foot.

**Expected behavior:**
No droping

**Actual behavior:**
Not always, sometimes, the rocks with moving drop up me, but very far. Height more then 1500, and after don't falling back. Only teleport works (reload not solve the problem). But after teleport some graphics is a black patch.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![blackpatch](https://user-images.githubusercontent.com/74495323/100398695-1606e680-3050-11eb-848e-f2ee7a199aff.png)

**Comment by SlayksWood** [comment]
dup #18805
