### ISSUE TITLE
USER ISSUE: Storages gone -UPDATE

### ISSUE THREAD

**Issue by RaynorsRaider** [StrangeLoopGames/EcoIssues#19511]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
After re-log the storages are visible again. It seems its kind of visuel bug. 

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
oh,well but we have and this issue too #17803
Thank you for the report.
