### ISSUE TITLE
Room calculation should list all considered blocks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19515]
https://www.reddit.com/r/EcoGlobalSurvival/comments/k190gr/suggestions_on_why_the_room_tier_isnt_being/
Here it's saying the room is 3.26 but all the listed materials are 4 - there must be some blocks that are not being included in the display, the kitty-corner pieces probably.  Include those in the displayed materials.

**Comment by SlayksWood** [comment]
I agree with @mirasrael His roof looks like this:
![image](https://user-images.githubusercontent.com/45708377/100581291-8e8fd080-32f8-11eb-96b2-2c3932d8c197.png)
But for right calculation it should be:
![image](https://user-images.githubusercontent.com/45708377/100581321-9c455600-32f8-11eb-8f20-3b6126e7b52f.png)

We can either just add a notification in tooltip about it or add empty block in tooltip and calculate it.

**Comment by redwyre** [comment]
If single block placement lets you place blocks diagonally then it should be updated to make the second one necessary. Also hammer placement too.
