### ISSUE TITLE
Skid can break rock on other owned land

### ISSUE THREAD

**Issue by DragoonWise** [StrangeLoopGames/EcoIssues#19514]
i was using my skid in my mine and at the limit of my land, my skid broke the rock without being able to get the broken rock.
By checking why, i saw that my skid broke rock in my neighbour land (and i don't have the right on this land).

**Comment by SlayksWood** [comment]
Skid steer doesn't pick up rubbles, but breaks them.
![image](https://user-images.githubusercontent.com/45708377/100580031-44a5eb00-32f6-11eb-8013-2a606e6cc3eb.png)
