### ISSUE TITLE
stockpile glitch

### ISSUE THREAD

**Issue by tcsweeney94** [StrangeLoopGames/EcoIssues#19516]
unsure of how to reproduce i emtyped stock piles and i had a lag spike now i cant place blocks where the stock piles are located

**Comment by SlayksWood** [comment]
@tcsweeney94 Thank you for the report.
Can you discribe it more detail? Maybe provide some screenshots or video. 
And please provide log files when it happens next time. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
