### ISSUE TITLE
[0.9.1.7] Oak saplings (and probably other trees) are too bushy

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19526]
One issue that keeps annoying me is how bushy the oak saplings and other trees tend to be:

![image](https://user-images.githubusercontent.com/964559/100554937-42d41d00-324d-11eb-9c46-d9753ac10f22.png)

You pretty much plant them and you get a large bush in your face making it impossible to say, use a road tool right next to it, use the soil sampler, etc. It would be nice if the saplings had a lot smaller foliage and maybe resemble something like

![image](https://user-images.githubusercontent.com/964559/100554984-98a8c500-324d-11eb-9fa2-626a78b6c037.png)

Generally, when you walk through densely planted trees you should still be able to interact with the ground no matter their growth stage.

**Comment by SlayksWood** [comment]
This is a very small option, we don't have such small tree models.

**Comment by ThePiachu** [comment]
most of the issue is with foliage I think, so if we could replace the bushy blocks with something like, single leafs that might be somewhat simple art fix and it might be good enough to solve the problem? But yeah, long-term sapling models might be neat...

**Comment by keegan-o** [comment]
Unique sapling models are part of a future investigation into improvements to the tree system in Eco, closing as it has been on the internal docket for ages and will remain something we explore when we get to the tree system overhaul we'd like to do.
