### ISSUE TITLE
USER ISSUE: Fliege 1'500 meter übern boden 

### ISSUE THREAD

**Issue by Bergy1887** [StrangeLoopGames/EcoIssues#19520]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
kann ich nicht sagen

**Expected behavior:**
das man auf den boden zurück kommt

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #18805
If you stucked, please ask your administrator to teleport you (/teleport targetto).
