### ISSUE TITLE
[0.9.1.7 beta release-126]Contract Properties Broken

### ISSUE THREAD

**Issue by BradleyPratt** [StrangeLoopGames/EcoIssues#19522]
Contracts don't seem to save the requirements made.

**Proposed Contract**
![ijv0ueU](https://user-images.githubusercontent.com/22839258/100526291-5df84b80-31bf-11eb-8427-afd7a38e69e0.jpg)

**Contract when posted**
![eABGJyz](https://user-images.githubusercontent.com/22839258/100526304-749ea280-31bf-11eb-8133-98ce2ed483e2.jpeg)

The tier and volume are not saved.

**Comment by SlayksWood** [comment]
the same issue with road contract #19064

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/101335016-ada6d900-3889-11eb-9fd6-c6eff68b05cd.png)
