### ISSUE TITLE
USER ISSUE: Wasseroberfläche fehlt

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19521]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
man generiere einen neuen Wasserfall

**Expected behavior:**
Wassertextur auf allen Seiten

**Actual behavior:**
1 von 3 Seiten hat nur eine Textur

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein
![image](https://user-images.githubusercontent.com/63196305/100520937-e61b2880-31a0-11eb-9784-7975b14c50e2.png)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/63196305/100520903-bc620180-31a0-11eb-9b5a-7c316f2efe67.png)
![image](https://user-images.githubusercontent.com/63196305/100520912-cc79e100-31a0-11eb-8053-f1c665de5c30.png)

**Comment by TimoNuernberg** [comment]
ich bastel gerade an einem Kanal aus Lehm, bzw später Pottery (ja hier fehlt noch die deutsche Übersetzung)

und hier konnte ich die fehlende Textur nachbauen. Das Wasser fließt bis ganz runter (getestet, ich hab den Charakter rein gestellt)
![image](https://user-images.githubusercontent.com/63196305/100543496-ce02e200-3250-11eb-8157-f1fa96f36fa0.png)

**Comment by SlayksWood** [comment]
@TimoNuernberg Thank your for the report.
We have a lot of water problems which we want to fix, so merged in one of them #19270
