### ISSUE TITLE
[0.9.1.7] Recipe Display Name appears only as Recipe

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#19529]
Issue: In-game the Recipe Name is only called recipe.
![image](https://user-images.githubusercontent.com/29911902/100563628-edfada00-3312-11eb-95f3-ec3603744384.png)

There is one call of Init in code.
![image](https://user-images.githubusercontent.com/29911902/100563617-e5a29f00-3312-11eb-876b-a251c24eff89.png)

Fix:
Init is called twice, the name then displays in-game tooltip.
![image](https://user-images.githubusercontent.com/29911902/100563906-acb6fa00-3313-11eb-9722-a1ae2e5b8d2f.png)

Note: The data for the wiki requires this to be working

**Comment by ZeelNightwolf** [comment]
Known Recipes Missing the second Init:
Culinary Research Paper Basic
Culinary Research Paper Basic Meat
Culinary Research Paper Modern
Culinary Research Paper Advanced
Culinary Research Paper Advanced Meat
Refine Tallow
Ashlar Basalt
Ashlar Gneiss
Ashlar Granite
Ashlar Limestone
Ashlar Sandstone
Ashlar Shale
Corrugated Steel
Flat Steel
Steel Bar
Steel Pipe
Metallurgy Research Paper Modern
Quicklime
Rebar
Rivet
Steel Saw Blade
Asphalt Concrete
Stone Ramp
Stone Road
Engineering Research Paper Advanced
Iron Wheel
Wooden Wheel
Butcher Bison
Butcher Medium Animal
Butcher Small Animal
Butcher Tiny Fur Animal
Butcher Tiny Leather Animal
Campfire Animal Medium
Campfire Animal Small
Campfire Animal Tiny
Campfire Bass
Campfire Bison
Campfire Blue Shark
Campfire Cod
Campfire Crab
Campfire Moon Jellyfish
Campfire Pacific Sardine
Campfire Salmon
Campfire Trout
Campfire Tuna
Render Fat
Hardwood Lumber
Lumber
Softwood Lumber
Board
Dendrology Research Paper Advanced
Dendrology Research Paper Modern
Saw Boards
Composite Lumber
Exotic Fruit Salad
Exotic Salad
Exotic Vegetable Medley
Grassland Salad
Forest Salad
Mixed Fruit Salad
Mixed Salad
Mixed Vegetable Medley
Mushroom Medley
Rainforest Fruit Salad
Rainforest Salad
Refine Fish
Refine Kelp
Refine Meat
Advanced Circuit
Basic Circuit
Electric Motor
Gold Flakes
Light Bulb
Substrate
Agriculture Research Paper Advanced
Agriculture Research Paper Modern
Soil Sampler
Gathering Research Paper Basic
Framed Glass
Glass
Advanced Combustion Engine
Radiator
Rubber Wheel
Steel Axle
Steel Gearbox
Steel Gear
Steel Plate
Charcoal


There is more. If you look at the comparison history on this page of the wiki you will be able to find others
https://wiki.play.eco/en/index.php?title=Module%3ASkills&type=revision&diff=4577&oldid=4512

**Comment by D3nnis3n** [comment]
Blocks wiki

**Comment by mirasrael** [comment]
Init shouldn't be called twice. It is a hack. But off course it should show correct display name for recipes.

**Comment by D3nnis3n** [comment]
That's how it worked before, any solution that works with the wiki will be fine.

**Comment by SlayksWood** [comment]
fixed in staging.
