### ISSUE TITLE
[0.9.1.7 beta release-126] Research work parties will not accept tag based research papers

### ISSUE THREAD

**Issue by thomasfn** [StrangeLoopGames/EcoIssues#19525]
This might also apply to generic recipe work parties with any tag based recipe component, but I haven't tested this.

Steps to reproduce:

1. Player A start a research project with a recipe that wants a tag (e.g. Basic Research Tag), e.g. Mechanics.
2. Player A post a work party on a contract board to contribute labor and materials for the project
3. Player B accept work party, and attempt to contribute any basic research papers to the research table (by holding in hand and right clicking onto the table)
4. Observe that "There are no available projects that require X" error message is displayed and the papers are not accepted
5. Observe that contributing any specific research papers that the recipe explicitly asks for, e.g. metallurgy basic for Mechanics, are accepted with no issues

![wpbug_3](https://user-images.githubusercontent.com/2463967/100550995-e1747400-3275-11eb-8e45-21d870c18098.png)
![wpbug_2](https://user-images.githubusercontent.com/2463967/100550998-e3d6ce00-3275-11eb-9eab-57a33e951a29.png)

**Comment by SlayksWood** [comment]
have it in release-129, didn't check in staging yet.

**Comment by olegshegai** [comment]
Seems to be okay on staging: https://drive.google.com/file/d/1qWYJnCNLpxmufKWjsjnaS8GofBDBGDAU/view?usp=sharing

**Comment by SlayksWood** [comment]
Can't reproduce in staging too, seems fixed.
