### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by serg65956** [StrangeLoopGames/EcoIssues#19533]
**Version:** 0.9.1.4 beta release-116

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5615980/Player.log)

**Comment by SlayksWood** [comment]
Update top the latest version and reopen it if it happens again.
