### ISSUE TITLE
Tooltip still sensitive to spaces in text 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19539]
![anim](https://user-images.githubusercontent.com/3536496/100677054-08d34b80-331f-11eb-956f-1882d546ba0f.gif)
I remember this getting fixed previously

**Comment by MrAnonymous110** [comment]
> ![anim](https://user-images.githubusercontent.com/3536496/100677054-08d34b80-331f-11eb-956f-1882d546ba0f.gif)
> I remember this getting fixed previously

Ah, I fixed the selector dropdown prefab, it's hover receiver to show the tooltip, not the tooltip popup.  The way I did is deactivate raycast of text mesh and let the background received hover instead. So when we want to fix the new place, need to do it one by one.

**Comment by SlayksWood** [comment]
This issue is not closed. merged to #18597
