### ISSUE TITLE
Store currency amounts as integer cents instead of a float

### ISSUE THREAD

**Issue by gjsmo** [StrangeLoopGames/EcoIssues#19545]
Fairly simple request here. Occasionally you will get an error when trying to spend all of a particular currency ("You currently have 1 gjsmo credit but you need 1 gjsmo credit") which has all the hallmarks of being a floating point error where you actually only have 0.9999999999992 credits instead of 1.

It would be significantly better to store currency as an integer in cents (0.01 credits). This is how the professional financial and banking industry does it and it eliminates this kind of error. It appears that prices in the store cannot be set lower that 0.01 credits, which is perfectly reasonable, so the minimum storable number should be 0.01 or 1 cent. 1.00 credits would be stored as 100 cents, etc.

**Comment by SlayksWood** [comment]
merged to #8466
