### ISSUE TITLE
Expand RecurringPayment action

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19540]
This action is a bit confusing to use, separate it out with some derived versions to make it simpler.  Make a 'Pay Rent' action, which has Resident (User) and Landlord (Alias) for the citizens (you can override the Citizen member name to Resident with LocDisplayName).

And also make one for ReceiveWages, which has Wage Earner (User) and Wage Payer (IAlias).

**Comment by IcedForge** [comment]
When this is looked into can we take a look at current wage system as its paying double consistently.
#18435

**Comment by tuha263** [comment]
Already have a task for Rent action: https://github.com/StrangeLoopGames/EcoIssues/issues/19337

**Comment by tuha263** [comment]
@johnkslg Because we also have the Move-In fee so I will name "Resident", "Landlord" for both action
