### ISSUE TITLE
[0.9.2.0 beta staging-1860]Nutrient pie and color balance are not balanced

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19548]
Some issues with color fills not being weighted properly or there is something else missing here. as i got most vitamins, the green chart should be the majority not the minority.
![Screenshot_10.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c8d4849f-5939-40d8-9155-cc839c8653de)

**Comment by WeaselDog** [comment]
Fix with https://github.com/StrangeLoopGames/EcoIssues/issues/19450
