### ISSUE TITLE
Prep CW kubernetes on Aliyum

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19544]
setup a working system on a testing account with Aliyum.

**Comment by j3fffff** [comment]
Perfect Worlds said: 
Would you like to register an enterprise account in the name of Strangeloop on Aliyun? Then you can start the integration earlier and more freely.
Of course, when the game is officially launched, the ECO servers still needs to be migrated to the Aliyun account hosted by Perfect World, so as to meet the GOV requirements.

Aliyun registration url: https://account.alibabacloud.com/login/login.htm
Aliyun registration FAQs url: https://www.alibabacloud.com/help/doc-detail/52595.htm
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/3eca1a22-7117-43d6-bc3a-f34a9ad589b2)
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/76f668f5-54af-4fb1-9007-eb0a58db4b7d)

**Comment by WeaselDog** [comment]
Issue moved to [StrangeLoopGames/Eco #7285](https://github.com/StrangeLoopGames/Eco/issues/7285) via [**ZenHub**](https://www.zenhub.com/)
