### ISSUE TITLE
[0.9.2 staging-1860] NRE when unclaiming with CTRL+LMB

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19547]
Use Ctrl+LMB to delete deed. I have exception in server log:
![image](https://user-images.githubusercontent.com/45708377/100707957-8c8f4580-33bc-11eb-84d1-dad9a3db864f.png)
[log_201201093629.log](https://github.com/StrangeLoopGames/EcoIssues/files/5620772/log_201201093629.log)

**Comment by Mattprass** [comment]
This needs more information, as I'm unable to reproduce.
