### ISSUE TITLE
[0.9.2 staging-1860] Tooltips are closed one by one and take a long time

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19553]
Step to reproduce:
- open a lot of tooltips:
![image](https://user-images.githubusercontent.com/45708377/100725574-41cdf780-33d5-11eb-9a82-1350143fcab5.png)
- mouseover a free space:
https://drive.google.com/file/d/1kNEwNnayn1vSCC8Ix3geydpsdOg7t7DB/view?usp=sharing

**Comment by johnkslg** [comment]
They are meant to close slowly so you can mouse-back on them if you want to view an above layer.

**Comment by MrAnonymous110** [comment]
Hi, I found out that, current count time to close tooltip is 0.5s, the purpose for that is when the player moves mouse over another tooltip, there is an empty space gap between them, and takes time to move the cursor through it. If the time too short, they will close when player even not hover on the desired tooltip. So I think we should keep the behavior like current
