### ISSUE TITLE
Orphan laws stuck on Court House

### ISSUE THREAD

**Issue by Robert-Verm** [StrangeLoopGames/EcoIssues#19554]
I moved the court took me 15 seconds when I replaced it I choose to adopt orphan laws and no laws appeared in the court but they are in the legal (L) page and do not work. New laws work but it is very confusing for the players.
[https://drive.google.com/file/d/1_QQfPNzyk2II4XWv5p_SHURFgjdyIe1l/view?usp=sharing](url)

https://drive.google.com/file/d/1_QQfPNzyk2II4XWv5p_SHURFgjdyIe1l/view?usp=sharing

**Comment by IcedForge** [comment]
@Robert-Verm Thank you for reporting this issue.
Is this an older world that has migrated into 9.1 version?

**Comment by Robert-Verm** [comment]
No it was not however I was able to remove the old laws by ID# with admin commands and they are no longer active because they was removed. It was odd that they showed up on the "L" worked but was not accessible to change or delete.

**Comment by SlayksWood** [comment]
Can not reproduce. Seems fixed with refactoring.
