### ISSUE TITLE
[0.9.2 staging-1860] Registrar and Bank UIs

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19552]
- [ ] 1. Need some love here:
![image](https://user-images.githubusercontent.com/45708377/100718390-55289500-33cc-11eb-8712-8a873f82081c.png)
and here:
![image](https://user-images.githubusercontent.com/45708377/100718439-64a7de00-33cc-11eb-99b9-863526f97353.png)
Also names in Manages and Users are too small.

- [x] Selector doesn't save players. Step to reproduce:
- add Dummy and Ice Forge to my Bank account:
![image](https://user-images.githubusercontent.com/45708377/100718682-ab95d380-33cc-11eb-8e9a-b25da2353080.png)
- submit:
![image](https://user-images.githubusercontent.com/45708377/100718708-b2bce180-33cc-11eb-9e76-bdd7f258c708.png)
- want to change it, press '+' again. They are not selected:
![image](https://user-images.githubusercontent.com/45708377/100718799-ce27ec80-33cc-11eb-87d8-fd0774ce004a.png)

**Comment by SlayksWood** [comment]
based on the discussion in Discord:

- [ ] 1. Make left align Account Managers and Account Users
- [ ] 2. Make managers and users nicknames and titles text bigger
- [ ] 3. Delete collapse button.
![image](https://user-images.githubusercontent.com/45708377/101604296-c0e4b080-3a11-11eb-976a-ac4107013aaa.png)
- [ ] 4. Possible to make the black bar smaller like it was in 9.1:
![image](https://user-images.githubusercontent.com/45708377/101604320-ce9a3600-3a11-11eb-8c0f-79d3ee57c98b.png)

**Comment by SlayksWood** [comment]
Another problem with UI - Account managers tab is a little bigger than Account users tab:
![image](https://user-images.githubusercontent.com/45708377/101733201-89d4d480-3acf-11eb-998c-d514d82ed97b.png)

**Comment by SlayksWood** [comment]
Still have a few flaws:

- [ ] 1. Managers and users nicknames are still less than in other UI. In select window they are bigger:
![image](https://user-images.githubusercontent.com/45708377/102065067-24ebe800-3e09-11eb-970b-c581b08371a9.png)

- [ ] 2. Advanced settings button should be fixed for localization:
![image](https://user-images.githubusercontent.com/45708377/102065206-4c42b500-3e09-11eb-944c-7dae7a5f5a2a.png)

- [ ] 3. This is look like one line now:
![image](https://user-images.githubusercontent.com/45708377/102065451-9fb50300-3e09-11eb-9308-64bfcee32471.png)
The background is too light now and no separation is visible. It might be worth adding separation for two different parts here:
![image](https://user-images.githubusercontent.com/45708377/102065630-dee35400-3e09-11eb-8ca7-5a8e468be62a.png)
But I think you need to discuss it with @MilenkoTunjic 

- [ ] 4. New one, which I did not notice before. I can select visual a several titles or bank accounts:
![image](https://user-images.githubusercontent.com/45708377/102066311-b740bb80-3e0a-11eb-9923-99f3d982493a.png)
Should be selected only active title, also you can unselect all:
![image](https://user-images.githubusercontent.com/45708377/102066379-ccb5e580-3e0a-11eb-9d84-066e7faf7c66.png)

**Comment by IcedForge** [comment]
Still have issues of that it has not very clear distict field differences need to have a separation bar between Mangers / Users as described by Slayks it could also use the same for the categorization fields themselves.

Similar to how the contracts are separated.
![Screenshot_56](https://user-images.githubusercontent.com/24981362/102353839-efcacb80-3fa9-11eb-8447-1fd983501a5e.jpg)

**Comment by SlayksWood** [comment]
Create a separate issue.
