### ISSUE TITLE
USER ISSUE: Flying in the solar system

### ISSUE THREAD

**Issue by Jonnyb92k** [StrangeLoopGames/EcoIssues#19559]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
I was standing on top of a block of limestone, i mined it and then it launched me into the solar system. This has happened to me twice. 

**Expected behavior:**
I should have just fallen, with the broken limestone.

**Actual behavior:**
I launched me into space, i cannot see anything except my hot bar. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5623478/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5623481/Player.log)

**Comment by SlayksWood** [comment]
Thank you for the report.
merged to #18805
