### ISSUE TITLE
USER ISSUE: Shooting out of Planet

### ISSUE THREAD

**Issue by nickhunter93** [StrangeLoopGames/EcoIssues#19562]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. Pick a lot of Rock2. Stand on Picked Rock
3. Gather the Rock on which you stand.
4. FLY TO THE MOON

**Expected behavior:**
Not shooting to the sky and never coming down again	

**Actual behavior:**
Shooting to the sky never coming down again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods xD

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report.
merged to #18805
