### ISSUE TITLE
USER ISSUE: Mining while standing on rocks

### ISSUE THREAD

**Issue by dakre18** [StrangeLoopGames/EcoIssues#19569]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. Stand on rock to mine, works best when working at the top of a hill/cliff
2. Mine rocks that way until one throws you into the air
3. Hope you're not flung too high or you won't come down

**Expected behavior:**
It should just let you drop with the rocks you are standing on, as they fall.

**Actual behavior:**
Currently there's a chance the physics launches you into the air. I'm currently 536m above my campsite, and I am not falling.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report. Please ask your administrator to teleport you (/teleport targetto).
merged to #18805
