### ISSUE TITLE
USER ISSUE: Fahrzeug in der welt verguggt 

### ISSUE THREAD

**Issue by Yuzukii86** [StrangeLoopGames/EcoIssues#19568]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
duch das laden in der map ist das auto in den schichten verbuggt und man muss es suchen 

**Expected behavior:**
Fahrzeuge Auf der map anzeigen lassen

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Yuzukii86 Thank you for the report. 
merged to #15688
