### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Matjaz1309** [StrangeLoopGames/EcoIssues#19577]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Incompatible version.
User version:   0.9.1.8 beta release-130
Server version: 0.9.1.7 beta release-126

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Thibault-Brocheton** [comment]
downgrade you client version (it's easy in steam)
there's no bug here

**Comment by Matjaz1309** [comment]
How can I down grade in steam

V sre., 2. dec. 2020 18:07 je oseba Thibault Brocheton <
notifications@github.com> napisala:

**Comment by D3nnis3n** [comment]
Right click Eco while not running, choose Properties - Betas and select the version in the drop down. Revert to none when the server updated for autoupdates in the future.
