### ISSUE TITLE
[0.9.1.8] Wheelbarrow gets weird acceleration when u-turning

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19578]
I ran into a weird issue with the wheelbarrow. I was on a dirt road when I decided to turn the wheelbarrow around, so instead of being in front of me it would be behind me. As I was turning I noticed the vehicle started moving a bit faster than it probably should - it was doing a bit of a skid / drift sideways while turning. Then, my character started moving a bit faster than they should with the wheelbarrow - something like 1.5 times the speed? Something was a bit wonky there

So to reproduce:
- Take a wheelbarrow, start driving it
- Rather than trying to keep it in front of you, move past it and drag it behind you
- You should be moving noticeably faster. Doesn't work all the time, but it's somewhat consistent

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5633330/Player.log)

**Comment by SlayksWood** [comment]
merged to #19116
