### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by serg65956** [StrangeLoopGames/EcoIssues#19585]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Не удалось подключиться - время соединения истекло.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5636547/Game.zip)

**Comment by SlayksWood** [comment]
Can you provide more information?
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the 0.9.1.8 or you had it before?

**Comment by serg65956** [comment]
проблема возникла после обновления  до 9.1.4.
Антивирус (Dr.Web) включен, но в настройках была установлена блокировка брандмауэр, так как не подписано приложение.
Проблема решена.
