### ISSUE TITLE
USER ISSUE:  I flew upwards to black space when mining sandstones

### ISSUE THREAD

**Issue by ryanbzb** [StrangeLoopGames/EcoIssues#19586]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. stand on sandstone aea
2. begin to mine around without picking up sandstones
3. Unexplained force push me up to the sky, till everything turn black.

**Expected behaviour:**
I should continue mining sandstone undisturbed.

**Actual behaviour:**
Instead, I got push upwards suddenly and reached a black space.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![Screenshot](https://user-images.githubusercontent.com/75439507/101056515-047c8c00-35c6-11eb-8ef6-fda170eb31fa.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5637381/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5637382/Player-prev.log)

**Comment by SlayksWood** [comment]
@ryanbzb Thank you for the report.
This will be fixed in 0.9.2. It is possible that some cases will remain, but it will not be so easy to reproduce.
If you stucked, please ask your administrator to teleport you (/teleport targetto).
