### ISSUE TITLE
USER ISSUE: I can't see the text of a sign through a window

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoIssues#19584]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
No one, it's in the title

**Expected behavior:**
I think it's normal to see through a window

**Actual behavior:**
I can't see the text of a sign through the window, I need to go at the other side of the window to read the text on the sign

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #19248
