### ISSUE TITLE
Mouse blocker not closing 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19589]
/spawn registrar
Try to add a title to itself
![image](https://user-images.githubusercontent.com/3536496/101081315-bed8a880-355e-11eb-8308-1be850748273.png)

Get a popup, and when you close it the mouseblocker stays around
![image](https://user-images.githubusercontent.com/3536496/101080727-f98e1100-355d-11eb-8ce7-0f256f749da1.png)

It's failing due to this:
![image](https://user-images.githubusercontent.com/3536496/101081223-a49eca80-355e-11eb-8421-ccb1ac782d5f.png)

Go through the code and make sure all popups are opened properly so they close properly. Also make this an error instead of a warning as it breaks the game.

**Comment by serpopov** [comment]
dup #19581
