### ISSUE TITLE
USER ISSUE: Large corrugated steel door placement issue

### ISSUE THREAD

**Issue by MadWyvern** [StrangeLoopGames/EcoIssues#19593]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Attmept to place corrugated steel door

**Expected behavior:**
Displays correctly in placement ghost prior to placement, and appears in correct location when placed

**Actual behavior:**
appears in to separate places and parts in the ghost, and appears in random location when placed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup #19534
