### ISSUE TITLE
Accounts: improper style of Youtube icon

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19591]
youtube icon must have fa-youtube-square class
![youtube](https://user-images.githubusercontent.com/26339332/101088919-6c7ea280-35c5-11eb-98a9-e12a541c7aea.png)

**Comment by denysaw** [comment]
Fixed. Could be tested on staging: https://accounts.stagingland.strangeloopgames.com/ (ctrl+F5)
