### ISSUE TITLE
Create Discord channel+bot for reposting SLG dev statuses

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#19596]
@WeaselDog: 
```
A bot that posts updates in Discord when someone changes their status. Maybe this would end up with too much spam, but it would be nice to see. At one point we talked about putting this in Daily-Status
```

`dev-statuses` channel in `Company` section

**Comment by StallEF** [comment]
@denysaw  Isn't it easier to first implement discord binding and only then make a bot that will automatically assign roles?

**Comment by denysaw** [comment]
@StallEF Hm... Which roles? Binding? Hook? I'll make via hook for sure :)

**Comment by StallEF** [comment]
@denysaw  i am about:
- standart
- beta tester
- Bug hunter
- developer
- wolf tier

**Comment by denysaw** [comment]
Um... Bot is about SLG Developer's daily statuses. Not about tier purchases :)

**Comment by denysaw** [comment]
Done in `Company` -> `dev-status` channel
