### ISSUE TITLE
/claim not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19594]
![image](https://user-images.githubusercontent.com/3536496/101104769-bee9a000-3580-11eb-87d8-8478c3a1ab50.png)
Creates a lot of deeds instead of a single one

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/102583889-7f8d8880-4116-11eb-85a4-c3af4b834690.png)
