### ISSUE TITLE
white screen when loading

### ISSUE THREAD

**Issue by B1unRik** [StrangeLoopGames/EcoIssues#19599]
Previously, the game worked correctly, now when you start the game faced with the problem of a white screen, the game loads and only the white screen is visible, there are sounds, I can go to the settings menu, adjust them. On the recommendation of the support service, I reinstalled the game, deleted and reinstalled VC++. 
I play from a laptop and installed the launch from the main video card.
![ECO](https://user-images.githubusercontent.com/75469770/101133308-85b13e80-3619-11eb-8f2b-d07bfa081ea5.png)

**Comment by Thibault-Brocheton** [comment]
you're in version 0.6.4.0-alpha, ... that's a very very old version
install the lastest version (0.9.1.8), that should correct your issue

**Comment by B1unRik** [comment]
Oh sorry, I didn't look at the current version, thank you very much

**Comment by B1unRik** [comment]
I do not change the version, I set the steam version, the game was updated, but when you start the problem remains and the old version is displayed in the settings, reinstalled the game but the problem remains

**Comment by SlayksWood** [comment]
@B1unRik Can you rocide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by B1unRik** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5642996/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5642997/Player.log)

**Comment by redwyre** [comment]
@B1unRik What virus scanner are you using? Could you try verifying the files in steam?

**Comment by Thibault-Brocheton** [comment]
don't you have several installations of the game on your computer ?
you coulds try to delete the appdata strangeloop folder, and resintall the game

**Comment by B1unRik** [comment]
> @B1unRik What virus scanner are you using? Could you try verifying the files in steam?

Kaspersky

**Comment by B1unRik** [comment]
> @B1unRik What virus scanner are you using? Could you try verifying the files in steam?

1. Kaspersky
2. Yes, I checked all the files, everything is OK

**Comment by B1unRik** [comment]
> @B1unRik What virus scanner are you using? Could you try verifying the files in steam?

**Comment by mirasrael** [comment]
@B1unRik it seems like you have some strange mix of files from old version and new version. Can you try to completely uninstall the game and then remove game installation directory if it still has any files and then re-install game? If it won't help then you can try to download the game from site and run it from another directory.

**Comment by B1unRik** [comment]
> @B1unRik it seems like you have some strange mix of files from old version and new version. Can you try to completely uninstall the game and then remove game installation directory if it still has any files and then re-install game? If it won't help then you can try to download the game from site and run it from another directory.

thank you guys, I deleted all the game directories and installed a new one and everything worked

**Comment by mirasrael** [comment]
@B1unRik glad to know your problem fixed!
