### ISSUE TITLE
[9.4] Update Bug Hunter Icon to have background like other badge icons.

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19590]
@MilenkoTunjic Let's just update the sprite for the bug hunter icon please.

Inside UI_Icons_04.png, I think what we want is for this icon:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/ae39ff85-7880-4384-bfd1-35fa9916631a)

To have a background like these ones do, of whatever color looks best:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/454989d3-f46b-43fb-88a8-719fc82084f8)

**Comment by keegan-o** [comment]
@MilenkoTunjic Let's just update the sprite for the bug hunter icon please.

Inside UI_Icons_04.png, I think what we want is for this icon:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/ae39ff85-7880-4384-bfd1-35fa9916631a)

To have a background like these ones do, of whatever color looks best:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/454989d3-f46b-43fb-88a8-719fc82084f8)

**Comment by StallEF** [comment]
@keegan-o we have one -  https://play.eco/assets/images/icons/bugicon.png
![bugicon](https://user-images.githubusercontent.com/26339332/108458069-e3ead680-7284-11eb-92f8-0335b24e1d84.png)

**Comment by keegan-o** [comment]
fixed in develop, replaced bug hunter icon in UI_Icons with the icon with a background, to match all the others.
