### ISSUE TITLE
Cloud Worlds - auto-updated to version 0.9.3.0

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19607]
My Cloud World auto updated to version 0.9.3.0 , I'm guessing other Cloud Worlds might've done the same if they were set to auto-update:

![image](https://user-images.githubusercontent.com/964559/101179053-9d2efe00-35fe-11eb-98f2-44f07810a7bf.png)

**Comment by ThePiachu** [comment]
Also, trying to revert the server version back to 0.9.1.8 seems to be having some issues with the server starting up again. I do hope the Cloud World do a backup before doing an update...

**Comment by denysaw** [comment]
Solved the problem (added garbage builds filter) and downgraded your world to 0.9.1.8

**Comment by ThePiachu** [comment]
@denysaw my server doesn't appear to be up, this is what I see in my menu:

![image](https://user-images.githubusercontent.com/964559/101211170-92d72900-362b-11eb-9325-edd6255a09a2.png)

**Comment by denysaw** [comment]
I filtered in auto-update script only. Gonna update there I guess too, sec.
@j3fffff Can you check why his work isn't re-starting after version upgrade?

**Comment by denysaw** [comment]
@ThePiachu Try now please that version dropdown. Should be out of unreal versions now.

**Comment by ThePiachu** [comment]
Version dropdown seems fine, my server is not starting though after switching it to 0.9.1.7 and then back to 0.9.1.8. Gave it like 5 minutes and still nothing...

![image](https://user-images.githubusercontent.com/964559/101217247-e189c080-3635-11eb-86ca-2ea40e92adbb.png)

**Comment by denysaw** [comment]
I also did the same. @j3fffff could help us with that/

**Comment by j3fffff** [comment]
`[11:48:37] Failed to load server, Exception was Exception: InvalidOperationException
Message:Save is incompatible with current server version, you are staring a save from newer version on the older server version.`

**Comment by ThePiachu** [comment]
I figured it had something to do with 0.9.3 updating something on the map.

I guess the other big question would be - do Cloud Worlds have some sort of automatic backup when a version is updated to roll the server back to? Seems like it would be a nice feature to have in an event of such a problem. Heck, having some sort of daily backup wouldn't be too bad... But that might be another issue entirely.

> Or you could have your users get the client to match the strange version. or update to newest staging build.

That doesn't seem to be an option since that version was removed from the server options due to this bug, and yeah. I could probably wait for 0.9.2 to release and hope that would make the map work again. I guess I'd need some extension of the server lease in that case though.

**Comment by j3fffff** [comment]
@ThePiachu Oh that version is gone already. you should be able to upgrade to newest staging build, those happen every night. and are on steam. sounds like 3 weeks til next final release

there is a backup system, but it backups every few hours. maybe we can add one that stays around for 48 hrs after version updates. @mirasrael what do you think on that? @redwyre

**Comment by ThePiachu** [comment]
@j3fffff - I don't think I'm able to upgrade the Cloud World to that version, and since the world is stuck at "starting" I can't download the map. I talked with Dennis and apparently I need to talk with you about the backup.

Could be another part of the issue to toss onto the pile - you should be able to download world backups even if the world is not online or errored out like this one.

**Comment by j3fffff** [comment]
sounds like dennis has found a previous world save that will work.
we fixed the auto update issue. and working on solution for better backup access.

**Comment by ThePiachu** [comment]
Hey @j3fffff - I restarted my world for the first time since it was reverted to an older backup and it hasn't loaded for like, 15 minutes still. I'm guessing it might've loaded some wrong save or something again? Or maybe something new is wrong with the server. Not sure which because the screen doesn't tell me much...

**Comment by ThePiachu** [comment]
Okay, it works now. Not sure how long it took to boot back up, but it did take a long while, not sure why...
