### ISSUE TITLE
[0.9.1.8] "Bug" icon not supported in-game

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19608]
I recently received a lovely "Bug" icon for my account:

![image](https://user-images.githubusercontent.com/964559/101180200-20048880-3600-11eb-9446-01635bb98739.png)

However, when I checked the icon in-game it appears to be just the default icon:

![image](https://user-images.githubusercontent.com/964559/101180138-0bc08b80-3600-11eb-995e-28ec4ad57107.png)

So I'm guessing this icon might not be supported in-game at the time?

**Comment by StallEF** [comment]
@ThePiachu  you must do to:
1) https://play.eco/account
2) click on you current icon or change icon button
3) click on Bug hunter icon

for me on [0.9.2 staging-1862] icon work but have bug -  https://github.com/StrangeLoopGames/EcoIssues/issues/19590

**Comment by ThePiachu** [comment]
Hmm, could be the way the icons are assigned then - maybe there is a small bug that doesn't refresh the icons when staff push the changes?

**Comment by WeaselDog** [comment]
Hi. Sorry about the confusion. The in-game icon will not be implemented until 9.2. Thank you for all your help catching bugs, and you will see this new icon in game after that release.
