### ISSUE TITLE
[0.9.2 staging-1863] Ctrl+Click to create marker doesn't work

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19600]
Step to reproduce:
- want to create marker for court:
![image](https://user-images.githubusercontent.com/45708377/101139404-8ef2d900-3622-11eb-8423-14d00fbbed4e.png)
- press ctrl+ click on 'Court':
![image](https://user-images.githubusercontent.com/45708377/101139466-a336d600-3622-11eb-8de6-9af5a250b3c6.png)
- it opened minimap, but marker  wasn't created.

**Comment by gzatravkin** [comment]
It worked for me. 
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/4ed0e479-3499-47df-8f12-dca958740301)

**Comment by gzatravkin** [comment]
can you attach video with cursor of reproduction if you will be able to reproduce it again? I was checking it at staging

**Comment by SlayksWood** [comment]
I guess it's dup and was fixed with https://github.com/StrangeLoopGames/Eco/pull/7339
