### ISSUE TITLE
[Feature] More video memory budget

### ISSUE THREAD

**Issue by Sakarias411** [StrangeLoopGames/EcoIssues#19616]
Would be nice to have a settings in the graphics menu to allow more texture memory usage because this just makes modding really... difficult, meaning the more mods you add on a server, the ugglier the texture will be for everyone. (Once the memory budget goes above 100%, some item texture will become blurry).

Nowadays, most of us have a videocard capable of more than 1024mb of VRAM.

![image](https://user-images.githubusercontent.com/4887819/101247326-49fd9e00-3719-11eb-9fbb-d592432692c7.png)
![image](https://user-images.githubusercontent.com/4887819/101247328-508c1580-3719-11eb-9a3b-da86fefc8f91.png)

**Comment by BigWolfChris** [comment]
Adding support to this

**Comment by IgneusTempus** [comment]
I would have to agree on this. even my old GTX 680 has a support of 2gb of VRAM.

**Comment by redwyre** [comment]
Note the texture budget of 1GB is _for_ a 2GB card

**Comment by Sakarias411** [comment]
I am currently using a RTX2080Ti, my ingame memory budget is capped at 1024 and I see blurry textures on objects when I add mods.

**Comment by BigWolfChris** [comment]
> 
> 
> Note the texture budget of 1GB is _for_ a 2GB card (which is our minimum supported)

Totally get that - but I have an 8GB card, would be nice if either I can make the game use more, or the game detect it, and auto assign :)
