### ISSUE TITLE
USER ISSUE: door open again

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19617]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
mit der Schaufel in der Hand, eine Tür, das erste mal seit dem einloggen anklicken

**Expected behavior:**
die Tür öffnet sich

**Actual behavior:**
nichts passiert;
wenn man die Tür mit etwas anderem öffnet und danach es mit der Schaufel versucht, funktioniert es.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, No and No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #3868
