### ISSUE TITLE
USER ISSUE: Campsite gone

### ISSUE THREAD

**Issue by RobertKading** [StrangeLoopGames/EcoIssues#19613]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Level command

**Expected behavior:**
Said invalid command or left campsite untouched	

**Actual behavior:**
Completely removed campsite

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@RobertKading Thank you for the report. Do you use /level ? This is intended for this command. use /give Campsite to get Campsite back

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
