### ISSUE TITLE
Profile 30 minute slowdown, create issues

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19619]
The game slows down after 30 minutes of play in large worlds. Profile what is going on, and create issues. Fill the sprint up with these issues and fix as many as possible.

Reference to some old performance caps here:
https://github.com/StrangeLoopGames/EcoIssues/issues/15236

**Comment by mirasrael** [comment]
I found one issue and fixed which may be related to slowdown (#7410), but it also may be related to other things. Need more testing with big worlds in 9.3.

**Comment by mirasrael** [comment]
But testing with big worlds blocked by https://github.com/StrangeLoopGames/Eco/issues/7433 which totally consumes all frame time.

**Comment by WeaselDog** [comment]
Going to close as this is significantly improved in 9.3 and has more coming in 9.4. As we do more profiling we can create issues for these as we find them.
