### ISSUE TITLE
Design doc for new comments system

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19611]
should replace elections and eco tree comments.
uses eco accounts.
only in js
view recent comments

**Comment by denysaw** [comment]
@j3fffff But why it should fit both projects? We'll have different backend anyway, as in ElectionsUI backend is C# with own LightDB server. Client also will be different as refactored ElectionsUI will have frontend framework, which EcoAccounts don't have.
Design (HTML) you could already start to invent, btw. Then I'll do logic in both projects ;) There's no requirements for the HTML, except, that 1 comment should be in 1 container(`<div', `<article` or whatever, not the sequence of different tags).

**Comment by j3fffff** [comment]
lets just reuse as much as possible. maybe just html and css
