### ISSUE TITLE
USER ISSUE: Corrugated steel door

### ISSUE THREAD

**Issue by onehotday** [StrangeLoopGames/EcoIssues#19623]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
placing corrugated steel in a 4x5 area unable due to a bug the top of the door is 5 higher the placing

**Expected behavior:**
![Screenshot (82)](https://user-images.githubusercontent.com/72355177/101268119-fbea9980-371c-11eb-891c-d3e379a7aa9f.png)

place as a door

**Actual behavior:**
keeps saying blocked by objects.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods on the account.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/19534

**Comment by SlayksWood** [comment]
dup #19534
