### ISSUE TITLE
New CW Backup config

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19628]
{
  "Enabled": true,
  "MaxBackupsInLastHour": 2,
  "MaxHourlyBackups": 3,
  "MaxDailyBackups": 5,
  "MaxWeeklyBackups": 2,
  "BackupFrequencyInHours": 0.5,
  "HeadBackupEnabled": true
}

MaxDailyBackups increased from 4 to 5 (if space can do, do 7), MaxWeeklyBackups decreased from 100 (?) to 2. Noone will want to go back that much. MaxBackupsInLastHour is new and replaces MaxTenMinuteBackups.

**Comment by denysaw** [comment]
Eh =)) I can do it =)

**Comment by j3fffff** [comment]
@mirasrael where is the cw default config set?

**Comment by D3nnis3n** [comment]
Do it!

**Comment by mirasrael** [comment]
Location of default configs: Eco\Server\Workspaces\HostedWorlds

**Comment by denysaw** [comment]
@mirasrael I think it's about configs in our repo, they are in `assets/configs` ;)

**Comment by denysaw** [comment]
Fixed. Could be tested on Stagingland. If should be changed also on Prod, please DM me.
