### ISSUE TITLE
USER ISSUE: Big Steeldoor bug

### ISSUE THREAD

**Issue by Klegendaer** [StrangeLoopGames/EcoIssues#19629]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**

**Expected behavior:**
Cant place this, if it placed it will be transparent

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
will be fixed in 0.9.2
