### ISSUE TITLE
[staging] Accounts:  no lang flag on sticky header

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19626]
if friend send link on tech tree tab to you can not change Lang and if you first time on site you can not know about it on top

exemple:  https://accounts.stagingland.strangeloopgames.com/updates/life/animalbehavior

![lang_header](https://user-images.githubusercontent.com/26339332/101291842-c927ca80-381c-11eb-98ea-9fdad714a3e6.png)

**Comment by denysaw** [comment]
Done. Could be tested on Stagingland.
