### ISSUE TITLE
[0.9.2 staging-1862] Wrong max tier in contract notification.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19631]
Step to reproduce:
- place contract board and start to create contract.
- select build room clause, enter tier more than 5:
![image](https://user-images.githubusercontent.com/45708377/101335876-cf549000-388a-11eb-9713-b1000aaac3ea.png)
- press post
![image](https://user-images.githubusercontent.com/45708377/101334979-a1228080-3889-11eb-9631-c6aed03183b1.png)
Should be 'max tier is 4'.

**Comment by IcedForge** [comment]
Still an issue on staging where it returns 5 as max tier, this should not be the case? Unless there is a hidden obj somewhere that has a higher tier im missing? As far as i see it should return max possible tier from a block?

**Comment by IcedForge** [comment]
![Screenshot_70](https://user-images.githubusercontent.com/24981362/103769976-89275380-5025-11eb-9132-4253fd7098e6.jpg)
