### ISSUE TITLE
USER ISSUE: TO INFINTY AND BEYOND

### ISSUE THREAD

**Issue by Trav0493** [StrangeLoopGames/EcoIssues#19639]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
Stand on shale. Look down at shale. Use pickaxe to break shale. Welcome to space.

**Expected behavior:**
Once you break the shale block I flew into the sky!

**Actual behavior:**
I am 1600 meters from my base and I am not getting any closer. Me and my friends have been playing for 10 days I relogged hoping to fix the issue but here I am still in the sky. Can no longer play Eco with the boys.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Trav0493** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5653862/Player.log.copy.txt)

**Comment by tomsseisums** [comment]
This is actually a known bug, just started playing and also experienced the same.

`/unstuck` in chat will temporarily help.

**Comment by IcedForge** [comment]
Thank you for reporting.
will close as of Duplicate #18805
