### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by cernomorec** [StrangeLoopGames/EcoIssues#19640]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Неверная информация авторизации.

<size=60,00%>Failed to authenticate user ticket with Steam: Invalid parameter</size>
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Неверная информация авторизации.

<size=60,00%>Failed to authenticate user ticket with Steam: Invalid parameter</size>
```

**Comment by MishkaFur** [comment]
Please purchase the game
