### ISSUE TITLE
cw being charged twice at purchase time

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19648]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/12c449ee-7d2f-4724-9fed-e4e00f12a9a6)

In screenshot, subscription info shows that it paid $15 start up fee. 
And it seems to imply that '1 cycle' had completed and charged another $15 subscription fee.

Users was charged $15 twice, on day of purchase.

**Comment by denysaw** [comment]
Shouldn't bug now. Fixed on Staging and hotfixed on Prod.
