### ISSUE TITLE
'Restart' button not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19649]
![image.png](https://images.zenhubusercontent.com/5ecc5c35b608cc220cfb5b6d/32124f79-8411-4480-a329-605bb03db2bf)
- Disable auto-refreshing in Unity
- Run the game
- Make a client code change
- Hit the custom 'Restart' button (that P on the toolbar).

This is supposed to recompile and restart, but lately lots of times Unity will freeze in this case.
Experiment and find what needs to be done to prevent it - adding a delay off in the restart sequence is probably a good bet.

**Comment by ptitducanh** [comment]
It doesn't happen on my Unity. Maybe upgrading to 2020 fixed it.

**Comment by johnkslg** [comment]
Im still seeing it, youre clicking this P? 
![image](https://user-images.githubusercontent.com/3536496/106372856-d8ad2680-6328-11eb-8737-f4783c3968cb.png)
