### ISSUE TITLE
USER ISSUE: Fish teleported on my bridge

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoIssues#19646]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. Build a bridge toward a river with a fish under2. The fish will be certainly teleported on the top of the bridge, and doesn't die

**Expected behavior:**
It shouldn't have teleported the fish here, it's unrealistic

**Actual behavior:**
It teleported a fish on the top of the bridge

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Screenshots:
![image](https://user-images.githubusercontent.com/19348373/101412734-60575580-38e3-11eb-9bf8-fed353656df5.png)
![image](https://user-images.githubusercontent.com/19348373/101412971-c217bf80-38e3-11eb-9e28-888c139246db.png)

Logs: 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5655593/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5655594/Player-prev.log)

**Comment by SlayksWood** [comment]
dup #17184
