### ISSUE TITLE
[0.9.2 staging-1866] Сan make all chats inactive.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19653]
Step to reproduce:
- I have only one chat #General:
![image](https://user-images.githubusercontent.com/45708377/101451970-10f24300-393e-11eb-83a8-3c08feb07524.png)
- Thus, it must always be active, but I can deactivate it:
![image](https://user-images.githubusercontent.com/45708377/101452375-a988c300-393e-11eb-910c-f5a7dea59d7d.png)
- Just clicking on logging, welcome and notifications.
![2020 12 08 Сan make all chats inactive](https://user-images.githubusercontent.com/45708377/101453023-b78b1380-393f-11eb-9121-a8acd49acafd.gif)

**Comment by SlayksWood** [comment]
update: Click on General (nothing happens but you have to press), click on Logins (you will turn off it), click on Logins again (you will turn on it). General chat will turned off.

**Comment by SlayksWood** [comment]
The easiest way, just RMB on general to hide it.

**Comment by beastyn** [comment]
Will be solved with redesign #20852
