### ISSUE TITLE
[0.9.2 staging-1866] Connection 'Cancelled by user' when activate another window.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19652]
I hoped it will be fixed with this https://github.com/StrangeLoopGames/EcoIssues/issues/19405, but I still have this problem. So Step to reproduce:
- press start to join to any server
- alt+tab to activate another window, alt+tab to return to game.
- connection cancelled by user, but I didn't cancel anything. It happened when we delete cursor during loading.
https://drive.google.com/file/d/1C_ZACSTz58G2DpKxdJWccTfZ1lizSRQz/view?usp=sharing

As far as I know the only way to cancel connection is pressing ESC

**Comment by SlayksWood** [comment]
> Cursor hidden when loading, cant make visible
> ![image](https://user-images.githubusercontent.com/3536496/101688514-fc3aab80-3a20-11eb-809b-8b9b14b9f02b.png)
> Unity 2020 has different cursor behavior, and during the load screen you cant make the cursor appear without halting the connection process.

**Comment by SlayksWood** [comment]
@WeaselDog Still an issue and can't find any PR which should fix it

**Comment by SlayksWood** [comment]
@WeaselDog Still an issue and I can't find any PR which should fix it.

**Comment by tuha263** [comment]
Seem it doesn't happen on the editor.

**Comment by IcedForge** [comment]
Seems to work now will close it
