### ISSUE TITLE
[0.9.1.8] Unable to Export a Cloud World

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19656]
When I tried clicking Export Save in my Cloud World server, the screen just turned white, showed me some animated three dots and then nothing happened:

![image](https://user-images.githubusercontent.com/964559/101466300-d1076d80-38f5-11eb-8368-bcc2d5c1ed4f.png)

I tried that both when the server was running and when it was paused, I tried it after a Restart and got the same results.

In general, it would be nice to be able to download the world as it is right now, as well as be able to download some periodic backups of the world in case something needs to be rolled back.

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod. Ctrl+F5.

**Comment by ThePiachu** [comment]
Seems to work now, thanks!
