### ISSUE TITLE
[0.9.2.0 beta staging-1866]Tooltips broken in minimap 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19651]
![image](https://user-images.githubusercontent.com/3536496/101430273-87992d00-38b9-11eb-8be6-0a95beafbd5f.png)
Nothing pops up.

**Comment by gzatravkin** [comment]
Seems like some texts don't contains linkcomponent. Check them at MinimapObjectMap 
![image](https://user-images.githubusercontent.com/53317567/101703887-46904c80-3a62-11eb-93f8-3f5f910059a9.png)
