### ISSUE TITLE
Fish freaks out on end of line

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1967]

**Comment by craig-jong** [comment]
Whaaaat - people love this.

@keegan-o We might want to get some kind of fish moving animation. I might be able to reuse the swim if their head doesn't move too much otherwise we'll have a static fish attached to the end.

**Comment by johnkslg** [comment]
Probably will want to do this procedurally so the fist isnt stick-straight vertical while you pull it in.

**Comment by craig-jong** [comment]
we can try ragdolling the fish - that went extremely poorly last time I tried it.

**Comment by keegan-o** [comment]
Added a 'IsOnLine' bool to all the fish controllers to set when the fish are on the line, with a placeholder animation.

**Comment by keegan-o** [comment]
should be a lot better now, no more insane rotation.
