### ISSUE TITLE
Title on mint item dialog is wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19675]
![image](https://user-images.githubusercontent.com/3536496/101597554-b4c60800-39ab-11eb-8828-3efceb1f7a49.png)
Check all cases of this dialog

**Comment by SlayksWood** [comment]
Distribution station too:
![image](https://user-images.githubusercontent.com/45708377/101605623-77956080-3a13-11eb-904e-f7a1db69f3cf.png)
