### ISSUE TITLE
weird Exception on Pan Troglodytes #2 from just walking and gathering

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#19672]
**Version:** 0.9.1.8 beta release-130

![snap7759](https://user-images.githubusercontent.com/29383891/101564440-19409180-39c3-11eb-92c6-02c6ec975eb1.png)

Not sure exactly what caused this  joined back in with no trouble, quite a bit of Lag during gamplay
forgot to do GitHub straightaway from crash so doing it now after about 2 hours of game play
here are the Player.log and Player-prev.log
had to zip them up as the playerlog is a massive 132 Meg (don't think i have seen one this size for ages)
[Player logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5663096/Player.logs.zip)

Getting lag mainly from Mining, Hit Rock with Pickaxe, rock disappears occasionally then comes back with broken rubble
sometimes you hit the rock nothing seems to happen and then it quickly disappears and you have hit the rock behind.
often lag in Eco detecting that you have swapped tools,
but the lag is not always showing up with the red icon bottom right corner, when that shows up, you just hope it wont disconnect you if it stays for a long time.
also lag in Stockpile detecting and showing that you have placed something in there with Right click

**Comment by mirasrael** [comment]
Already fixed in 9.2.
