### ISSUE TITLE
Reduce set of mintable items

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19676]
You should only be able to mint items that are durable, that can exist as a coin without falling apart. Thus remove at least the following:

Biodiesel
Clay
Coal
Cement
Ores, rock types, and crushed rocks 
Logs and Hewn Logs (they need to be processed to boards)
Urchin, Kelp
Wood pulp

**Comment by IcedForge** [comment]
Close as finished (removed a bulk of them 9.5) but we are revising it slightly in the future.
