### ISSUE TITLE
[0.9.2 staging-1867] Some buttons lost frame in Ballot

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19679]
![image](https://user-images.githubusercontent.com/45708377/101611188-43716e00-3a1a-11eb-805d-a71a7c50e6aa.png)
![image](https://user-images.githubusercontent.com/45708377/101611224-4ec49980-3a1a-11eb-9e97-4030db17dca5.png)

**Comment by SpiritOfAncientWherewolf** [comment]
I think there's an error in the animator.
Example.
Entry point>IDLE.> Key press animation(background change)> exit point.

And here is the correct order.
Entry point>IDLE> Key press animation(background change)> IDLE

**Comment by gzatravkin** [comment]
CNR both at staging (steam) and Unity.

Tested with Became candidate, Withdraw and Start election

**Comment by gzatravkin** [comment]
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/562c8fbd-3f84-44b7-a0b0-c948b3c9bff8)

**Comment by Daniel-Magulado** [comment]
Build: Staging
Repo: Unable to reproduce. Appears to be fixed.

Screenshot:
![Missing button frame (Fixed).jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/b8baddf3-996a-4ec1-ba31-a98c64c6d005)

![Missing button frame (Fixed) etner election button.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/a4082527-5756-4b9d-bcb6-e8ac6f7b17eb)

Closing.
