### ISSUE TITLE
Civic actions are doubly posting

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19670]
![image](https://user-images.githubusercontent.com/3536496/101558924-d788fa00-3974-11eb-84b2-1187d9f6d1eb.png)

**Comment by SlayksWood** [comment]
hm yeah, I don't have this problem with every notification, but at least I have it with ratifying constitution:
![image](https://user-images.githubusercontent.com/45708377/101604985-aced7e80-3a12-11eb-89f6-61b764e31f66.png)
But can't reproduce with Title yet. possibly related to the first vote.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/102452007-a9797900-404a-11eb-9b90-acf82387879f.png)
![image](https://user-images.githubusercontent.com/45708377/102452019-aed6c380-404a-11eb-9bc0-b75ca58e9777.png)
Still and issue
