### ISSUE TITLE
[0.9.1.8] WIP projects provide wrong estimates for how many items will be needed

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19677]
When you look at a WIP project that benefits from Lavish Workspace or some efficiency modules, you may see that you don't have enough items to complete the project while the project is running:

![image](https://user-images.githubusercontent.com/964559/101598622-4f731680-39ad-11eb-8b89-3b546a8d0854.png)

However, when you get to the final repetition, you suddenly have all the items you need:

![image](https://user-images.githubusercontent.com/964559/101598640-54d06100-39ad-11eb-8bbc-a919d188795c.png)

It might have something to do with rounding and so on. One way or the other, it would be nice to have a look at how those numbers are estimated to be more accurate.

**Comment by SpiritOfAncientWherewolf** [comment]
After all, requests for another such thing are indicated there. That is, there are not enough resources for the 11th thing.
