### ISSUE TITLE
USER ISSUE: Water

### ISSUE THREAD

**Issue by SalTechCA** [StrangeLoopGames/EcoIssues#19688]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Build a road (3 blocks wide and at least 6 blocks long) partially submerged under water.  Then remove the road.	

**Expected behavior:**
The water levels back out after blocks removed.	

**Actual behavior:**
The water does not level out and acts as water falls on the sides of where the road was.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #19270.
