### ISSUE TITLE
Make the XPEffect show for other players on the minimap and by their avatar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19687]
When you use a skill, it shows you the icon on your screen.  I want to add it so when other players use a skill, it shows an icon next to their avatar, both in the world and in the minimap.  This way you can look at the minimap and see the different skills people are using, as they shoot off little icons from the avatars to show theyre crafting, chopping wood, hunting, etc.

**Comment by SlayksWood** [comment]
Will there be a lot of spam? Because one player can have many specialties and at the same time many crafts are started
