### ISSUE TITLE
Cursor hidden when loading, cant make visible

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19685]
![image](https://user-images.githubusercontent.com/3536496/101688514-fc3aab80-3a20-11eb-809b-8b9b14b9f02b.png)
Unity 2020  has different cursor behavior, and during the load screen you cant make the cursor appear without halting the connection process.

**Comment by SlayksWood** [comment]
I guess it's the same issues #19652. So I merge it.
