### ISSUE TITLE
[0.9.2 staging-1868] Hide items in Filter which are not added yet.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19694]
Start to create law, select place or pickup, open filter with Item Placed or Picked up:
![image](https://user-images.githubusercontent.com/45708377/101767073-ca931480-3af4-11eb-9eb1-0936cd73a7e8.png)

**Comment by WeaselDog** [comment]
This is already fixed with https://github.com/StrangeLoopGames/Eco/pull/7340 which hasn't merged yet.
