### ISSUE TITLE
9.1.8 Laws - Trigger Barter Trade is not aligned with others

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19699]
![image](https://user-images.githubusercontent.com/61889138/101831831-69883280-3b2e-11eb-9a2e-b44468e13441.png)

As per pic and title, it is not aligned

**Comment by SlayksWood** [comment]
Seems fine in 9.2:
![image](https://user-images.githubusercontent.com/45708377/101904963-b9670800-3bc7-11eb-99e1-2852a29d0c05.png)
I have this offsetting in 9.1.8 too, so it will be fixed with 9.2
