### ISSUE TITLE
[0.9.1.8] Large Corrugated Steel Door seems to be messed up for some reason...

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19691]
I've tried placing the Large Corrugated Steel Door, but they seem to be messed up for some reason:

![image](https://user-images.githubusercontent.com/964559/101744798-e4dedb00-3a7f-11eb-8a02-0d3607bd9f83.png)

I can't get them to align to anything, and then they flicker in and out of existence when placed. The problem persists even after relogging / restarting.

Log:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5671352/Player.log)

**Comment by SlayksWood** [comment]
fixed in 9.2
