### ISSUE TITLE
restart and reset option on 'loading' worlds

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19702]
Sometimes a world is 'loading' but it has crashed. need an option to restart or reset.
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/b7784cda-ee13-4fe1-8219-2a136faf2d4a)

**Comment by denysaw** [comment]
Done. Fixed on Staging. Tell me if it also needs to be hotfixed on Prod.
