### ISSUE TITLE
Review all audio

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19707]
Ensure all audio is up to par and any replacements are an improvement

**Comment by IcedForge** [comment]
linked to this report.
#19706

**Comment by freakydna** [comment]
@johnkslg Old review for audio, close out?

**Comment by freakydna** [comment]
Will create a new issue for audio if needed as report [#19706](https://github.com/StrangeLoopGames/EcoIssues/issues/19706) is closed.
