### ISSUE TITLE
Audio issues from user

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19706]
![image](https://user-images.githubusercontent.com/3536496/101944797-25cf1080-3ba2-11eb-93c1-acf214bbb960.png)

**Comment by IcedForge** [comment]
Will close this as full audio review is planned, also discussed this with the user in question. This seems to be related to the upgrade to 9.x and an effect of having a more clear / crisp audio sourcing then before making these oddities stand out more.
