### ISSUE TITLE
Bad grammar on skill fail display

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19700]
This appears when clicking a skill popup that you couldnt gain xp on:
![image](https://user-images.githubusercontent.com/3536496/101831972-8e0eeb00-3aeb-11eb-8288-a65ff639b5ec.png)

it should say 'when using a <tool name>', the current is bad grammar. However, the text cant simply be changed because its used for other purposes. Make a second function that returns the proper grammar, in the present tense for this case.

**Comment by IcedForge** [comment]
Shouldnt this be "When using **a** -tool insert-"
![Screenshot_64.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/24fd3ae3-be22-4a29-99b5-ce1740a10dac)

**Comment by abaza121** [comment]
> Shouldnt this be "When using **a** -tool insert-"
> ![Screenshot_64.jpg](https://camo.githubusercontent.com/018f191e29587202925db2d924b59f1bcb33a4ba54058eb03430b03f8e2bb804/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566356137666135393837386564393537613836313838362f32346664336165332d626532322d346132392d393962352d636531373430613130646163)

In this case should it be using an Steel Axe? or just "a" with whatever tool? also do we have tools that aren't single (probably not but just making sure)

**Comment by SlayksWood** [comment]
@abaza121 Still don't have any article here:
![image](https://user-images.githubusercontent.com/45708377/117001105-9bbb4c00-acea-11eb-8ff6-ae271be3f425.png)
![image](https://user-images.githubusercontent.com/45708377/117001326-e0df7e00-acea-11eb-91fc-46f0ad9211d9.png)
![image](https://user-images.githubusercontent.com/45708377/117001358-ec32a980-acea-11eb-991b-e6bdc8986960.png)

**Comment by SlayksWood** [comment]
Oh, I get it:
![image](https://user-images.githubusercontent.com/45708377/117002053-bfcb5d00-aceb-11eb-97b3-3e3babcd6f99.png)
It works only with English, not with Gibberish.
![image](https://user-images.githubusercontent.com/45708377/117002121-d1146980-aceb-11eb-8485-26a8872600f8.png)
