### ISSUE TITLE
Cant see top of fishing pole

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1970]
Should change it so you can see the whole thing. Also its left handed which drives me crazy :)
![image](https://user-images.githubusercontent.com/3536496/29727841-65688a14-898a-11e7-95ec-be15483df058.png)

**Comment by keegan-o** [comment]
Part of this is field of view-- all tools will look similar with sufficiently zoomed in FOV. On my default settings I see the whole thing. But I moved it out a bit so it's all there at 70 FOV.
