### ISSUE TITLE
[0.9.2 staging-1869] Law's triggers need localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19714]
given the fact that not all triggers do not have translation, it is likely that words were not added to Crowdin just
![0-1](https://user-images.githubusercontent.com/26339332/101955675-4f725100-3c0f-11eb-9da1-639f4ceee28d.png)
![1-1](https://user-images.githubusercontent.com/26339332/101955690-55683200-3c0f-11eb-8847-1d7647535a34.png)
![1-2](https://user-images.githubusercontent.com/26339332/101955695-5600c880-3c0f-11eb-8b1c-88f2842f31c0.png)
![1-3](https://user-images.githubusercontent.com/26339332/101955699-56995f00-3c0f-11eb-82c9-bbda3a28c270.png)
![1-4](https://user-images.githubusercontent.com/26339332/101955701-56995f00-3c0f-11eb-958c-96f7b6167526.png)
![1-5](https://user-images.githubusercontent.com/26339332/101955703-5731f580-3c0f-11eb-9cef-6185c2f1532b.png)
![2-1](https://user-images.githubusercontent.com/26339332/101955704-5731f580-3c0f-11eb-8b3d-a8138fb069b9.png)
![3-1](https://user-images.githubusercontent.com/26339332/101955705-57ca8c00-3c0f-11eb-82a9-2d78e5fc7250.png)

if set all options
![4-1](https://user-images.githubusercontent.com/26339332/101984374-28a92e80-3c92-11eb-8b35-6ebe29fcfbe1.png)
![4-2](https://user-images.githubusercontent.com/26339332/101984375-29da5b80-3c92-11eb-8634-804ab794abda.png)

**Comment by gabrielgindridev** [comment]
@WeaselDog I think this is a different issue.
![image](https://user-images.githubusercontent.com/65634950/104948698-77866a00-599c-11eb-81bf-5ae8abb67c50.png)

At least, code points these tags should not be seen by the user

**Comment by gabrielgindridev** [comment]
> @WeaselDog I think this is a different issue.
> ![image](https://user-images.githubusercontent.com/65634950/104948698-77866a00-599c-11eb-81bf-5ae8abb67c50.png)
> 
> At least, code points these tags should not be seen by the user. Checked TagDefinitions.cs
> 
> ```
>             // Hidden Tags: All tags below should not be visible to players. They are used for behind the scenes gameplay mechanics
> 
>             // Specialties: For use in skill system; specialties are displayed elsewhere in Skills UI & Ecopedia
>             new TagDefinition("Carpenter Specialty")            { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Chef Specialty")                 { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Engineer Specialty")             { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Farmer Specialty")               { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Hunter Specialty")               { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Mason Specialty")                { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Smith Specialty")                { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Survivalist Specialty")          { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Tailor Specialty")               { AutoHighlight = false, ShowInEcopedia = false },
> 
>             // Tools: Tags that define tool actions
>             new TagDefinition("Construction")                   { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Excavation")                     { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Harvester")                      { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Logging")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Planter")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Plow")                           { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Tamper")                         { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Tools")                          { AutoHighlight = false, ShowInEcopedia = false },
> 
>             // Blocks: Tags for interaction context with blocks
>             new TagDefinition("Block")                          { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Liquid")                         { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Constructable")                  { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Excavatable")                    { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("RoadType")                       { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Harvestable")                    { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Currency")                       { AutoHighlight = false, ShowInEcopedia = false },
> 
>             // Objects: Tags for interaction context with objects
>             new TagDefinition("Economy")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Housing Objects")                { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Modules")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Object")                         { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Polluter")                       { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Storage Container")              { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Tech")                           { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("World Object")                   { AutoHighlight = false, ShowInEcopedia = false },
> 
>             // Items: Tags for interaction context with items
>             new TagDefinition("Product")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Torch")                          { AutoHighlight = false, ShowInEcopedia = false },
> 
>             // Misc: Tags that should be hidden but do not fit a defined category
>             new TagDefinition("Climate")                        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Ingredient")                     { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("NotAllowedInInventories")        { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("NotInBrowser")                   { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Plant")                          { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Tree")                           { AutoHighlight = false, ShowInEcopedia = false },
>             
>             // Law: tag for law trigger property
>             new TagDefinition("Specialty")                      { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Profession")                     { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Plants")                         { AutoHighlight = false, ShowInEcopedia = false },
>             new TagDefinition("Animals")                        { AutoHighlight = false, ShowInEcopedia = false },
> ```
Unless it changed.

**Comment by SlayksWood** [comment]
fixed in gibberish.

**Comment by StallEF** [comment]
@gabrielgindridev  i find one not work here:
![2021-02-21 (8)](https://user-images.githubusercontent.com/26339332/108721834-8203c880-7533-11eb-90f4-cd2b8e2420a8.png)

on EN triggers => Add Resources To Work Order => Ctafting Table
'Crafting Table' have on crowdin - https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru?filter=basic&value=3#169060

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1940.

There are a lot more for this specific language in civics.

![Law Localization.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/b6f29cd5-01f1-4fe6-aba4-950b3c773ac2)

**Comment by StallEF** [comment]
@Daniel-Magulado  "Crafting table" have translate on Crowdin, but not work in Law UI and have problem.
other words on you screenshots have not translate on Crowdin now just, but i used custom.csv and it worked, I will make the translation on Crowdin and after updating it in the game it should work correctly =) i hope

**Comment by gabrielgindridev** [comment]
Fixed issue where Localization process was failing to extract some strings, like: `Hours Between Execution`
But we are only running the Localization Process in `staging`, which means that missing strings will be added then
