### ISSUE TITLE
Too much property spam

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19716]
![image](https://user-images.githubusercontent.com/3536496/101966881-44e39780-3bce-11eb-9cee-532062bd9f67.png)
- Make this text just say the property name
- Can make it a clickable icon after all

**Comment by johnkslg** [comment]
Ideally the text doesnt show unless its close

**Comment by SlayksWood** [comment]
Still a lot of spam:
![image](https://user-images.githubusercontent.com/45708377/102482532-6a601d80-4074-11eb-8c92-b4d3c39ba483.png)
![image](https://user-images.githubusercontent.com/45708377/102482568-7a77fd00-4074-11eb-9301-baed224d21e4.png)

**Comment by SlayksWood** [comment]
After last minimap optimization markers can be offsetted:
![image](https://user-images.githubusercontent.com/45708377/102752423-9f24eb00-437a-11eb-85da-21d8e5686307.png)
but to offset markers you should edit property with Edit mode and don't move:
![image](https://user-images.githubusercontent.com/45708377/102752898-56b9fd00-437b-11eb-9652-b3d4f0c0f580.png)
![image](https://user-images.githubusercontent.com/45708377/102752926-646f8280-437b-11eb-8212-d922713b1fae.png)
need to check it after fixing this issue and create a new one if this is still an issue.

**Comment by SlayksWood** [comment]
First issue was fixed. Still have one suggestion but if it is approved I will create a separate issue. 
Second check is still an issue, but need to wait for merging. I close this one, because original issue was fixed, but will check second part in a new build.
