### ISSUE TITLE
[0.9.2 staging-1872] The sound of an Industrial Elevator does not match its functionality and engine type.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19729]
Wooden Elevator too but this is another issue #17811

- [ ] 1. The elevator moves before it starts. So if we want to leave this sound we need to add delay:
https://drive.google.com/file/d/1kl5kDWMmgHFndzpukK2ldIRtgMknwbo5/view?usp=sharing

- [ ] 2. Sound more like activating the Elevator. If we had another button that turns on/off the elevator, this sound would go there. The easiest way to understand that something is wrong is to press the up arrow while moving down (or vice versa):
https://drive.google.com/file/d/15Zf_qH7tV2_YmvH53i5v-3VWgrfidETA/view?usp=sharing

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.

Appears to be fixed after testing. 
Closing.
