### ISSUE TITLE
USER ISSUE: Got moved into orbit when i dug down 

### ISSUE THREAD

**Issue by BlackKuro** [StrangeLoopGames/EcoIssues#19724]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
step 1 dig dirt, step 2 pick at the stone under it, step 3 break the double piece while standing on it , step 4 be unable to play game as you sit in the abyss of space while contemplating my actions.

**Expected behavior:**
Aquisition of Stone 

**Actual behavior:**
Sent to space, can't find Wilson!

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report.
Fixed in 9.2. Please ask your administrator to teleport you (/teleport targetto).
