### ISSUE TITLE
USER ISSUE: Ocean water don't feel empty spaces

### ISSUE THREAD

**Issue by marcianito999** [StrangeLoopGames/EcoIssues#19722]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Dig, with shovel, on the coast. Collecting sand.

**Expected behavior:**
That the water of the ocean, inmediately, fill the empty space

**Actual behavior:**
A cascade. Like a SCI-FI movie.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report. merged to #16648

**Comment by marcianito999** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5812063/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5812064/Player.log)
