### ISSUE TITLE
Economy Viewer [Creator name + Circulation count is incorrect)

### ISSUE THREAD

**Issue by Sakarias411** [StrangeLoopGames/EcoIssues#19723]
Hello !

On the economy viewer, it shows the currencies have been created by "Jimmy' (I believe I saw another post with the tag FIXED earlier, but maybe you guys already fixed it for the next update).

Also, the currency in circulation is shown as : 
![image](https://user-images.githubusercontent.com/4887819/102017818-70e75000-3d69-11eb-9dde-b9a306a6f3b8.png)

But in reality we have 10 000 in circulation :  
![image](https://user-images.githubusercontent.com/4887819/102017814-6c229c00-3d69-11eb-9500-0517e41d5b8f.png)

Version : 
![image](https://user-images.githubusercontent.com/4887819/102017834-88bed400-3d69-11eb-94f2-4ba0d802e296.png)

**Comment by SlayksWood** [comment]
yeah, it will be fixed in 9.2 with #19093
