### ISSUE TITLE
add new server versions for staging

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19738]
on accounts page
bleeding edge download.

Add  download for win32, osx, linux

**Comment by redwyre** [comment]
also you can replace "Bleeding edge" name with just "Staging"

**Comment by denysaw** [comment]
Done. Hotfixed on Prod. Renamed as @redwyre asked.

**Comment by SlayksWood** [comment]
I don't have links to download server 64bit and have link to download only Client 64bit.
![image](https://user-images.githubusercontent.com/45708377/102193316-02bb9e00-3ecd-11eb-8587-b67588829abf.png)
Currently we have all variants in staging.

**Comment by denysaw** [comment]
@SlayksWood Why is it re-open? This particular issue was ONLY about Bleeding Edge (Staging) builds.
Red rectangles are about `Release` versions. Please, read issue description once more.

**Comment by denysaw** [comment]
@SlayksWood Also it was not about Stagingland, but about Staging (Bleeding Edge) builds. So on Production should be all those cases in red rectangles. So behavior is correct. If there are no similar links on Stagingland, it's ok I guess.

**Comment by denysaw** [comment]
Changes were made on Production, please test there right away. And yeah, new things in new issue, to not mess everything up on Production.
