### ISSUE TITLE
[0.9.2 staging-1872] Can make title with errors.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19731]
![image](https://user-images.githubusercontent.com/45708377/102079255-64bcca80-3e1d-11eb-88ef-e1c76227e64b.png)

Step to reproduce:

- [ ] 1. Error with title requirement:
- Start to create a new title. Don't change name:
![image](https://user-images.githubusercontent.com/45708377/102079706-38ee1480-3e1e-11eb-96a0-8a8426f572dc.png)
- add this title 25(draft) to title requirement, I should have exclamation mark, but I don't have:
![image](https://user-images.githubusercontent.com/45708377/102079855-7783cf00-3e1e-11eb-9f33-1aea182ec4b3.png)
- A slightly different problem, but I think it's related - Rename this title, The title will change but will not change in the Title requirements:
![image](https://user-images.githubusercontent.com/45708377/102080827-312f6f80-3e20-11eb-8c8e-2ccf880e3b9c.png)
- start election and win, we have this title:
![image](https://user-images.githubusercontent.com/45708377/102080901-54f2b580-3e20-11eb-8bb2-83da15a40761.png)

- [ ] 2. Error with revision in Eligable Candidates:
- Revise New title, still have problem with title 25 (draft):
![image](https://user-images.githubusercontent.com/45708377/102081021-91261600-3e20-11eb-805e-520a57ed5cb5.png)
- change eligible candidates to this title (not draft):
![image](https://user-images.githubusercontent.com/45708377/102081286-101b4e80-3e21-11eb-8544-6e9bcf2f7ac8.png)
I should have exclamation mark again, but I don't have:
![image](https://user-images.githubusercontent.com/45708377/102081365-2aedc300-3e21-11eb-866c-9b3223d10dd0.png)
- start election and win it.
- start to revise again. Now I have 4 errors:
![image](https://user-images.githubusercontent.com/45708377/102081506-68525080-3e21-11eb-8feb-e96fe5a65e78.png)

**Comment by SlayksWood** [comment]
Also have error in server log with restart:
![image](https://user-images.githubusercontent.com/45708377/102082117-6fc62980-3e22-11eb-9eb4-f9041c79381b.png)

**Comment by IcedForge** [comment]
It is no longer giving errors on creating the title but it is still allowing me to create a title with itself as requirement which is bad behavior it should give error and not allow me to submit the object at all if it has itself as requirement.

It does update name on elections so its not auto refreshing immediately but im not sure how that would be possible  ( for using it as reference in the same window and changing name )

**Comment by olegshegai** [comment]
Self referencing is an intended behavior, discussed in DM
