### ISSUE TITLE
clear old builds from s3 once a month

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19736]
keep all release builds.
clear all other builds over a month old.

use s3 api and cron job
or open to suggestions

**Comment by denysaw** [comment]
@j3fffff But... But we wanted to leave staging, dev and playtest for admins, nope?
And release means `x.x.x.x-beta`, correct?

**Comment by denysaw** [comment]
@j3fffff why not once a week?

**Comment by redwyre** [comment]
I've done this in s3, builds older than 30 days will expire, then be deleted the next day
![image](https://user-images.githubusercontent.com/431728/102158644-968d6a00-3ecd-11eb-8b36-f8d24e22ae9f.png)

Note this is only for files in the `eco-releases-staging` bucket as nothing in the `eco-releases` bucket should be deleted automatically (though it does still require some manual clean up from old staging builds)
