### ISSUE TITLE
Add text formula game value

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19733]
![image](https://user-images.githubusercontent.com/3536496/102125300-54e1be00-3dfe-11eb-9d55-abd709ed15d0.png)
Players are getting into some complex formulas for stuff, and thats great! it starts to break down the template system though.

Create a new game value under Math category, 'Formula'. This should let you enter a string with variables and math operations, like:
```(NumberOfPlayers / 10) * (WorldAgeInDays ^ 2)```
Then it will auto generate slots for the variables in the equation which the user can then set below.

**Comment by IcedForge** [comment]
Looks awesome, we will need to expand the tooltips a bit when i get more adjusted into the inner workings of this but overall this will help sooooo much with more advanced calculations and law making ! Excellent work!
