### ISSUE TITLE
[0.9.1.8 beta release-130]Civics: When an election fails to determine a win or loss it does not apply civic trigger win/lose election on citizen

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19732]
As title says, when an election fails ( White tiger for example here, only 4% out of minimum 10% voted on a elected title ) the user participating in the election did not trigger a "lost election" civics trigger, which causes issues with laws.

Need to make sure regardless of what happens to an election, edits or deleting etc or just losing it via weird ways always triggers "lost election".

**Comment by SlayksWood** [comment]
Seems it was broken again. Tested on staging-1943

**Comment by SlayksWood** [comment]
create a separate task for double working
