### ISSUE TITLE
Hide all game cw versions that are not release

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19734]
currently, for non-admin accounts, i can see beta-dev and beta-playtest versions.
Update so on release site, non-admins only see release versions and nothing else.

**Comment by denysaw** [comment]
@j3fffff Hm... Where exactly? In ChangeVersion dropdown? Can you make a snapshot? Thanx

**Comment by denysaw** [comment]
Aha, yeah, I see it. In that dropdown, yeah

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod.
