### ISSUE TITLE
Civics causing all players to be unable to connect.

### ISSUE THREAD

**Issue by Bruno-DaSilva** [StrangeLoopGames/EcoIssues#19747]
Eco Version: 9.1.8 beta release-130

**Steps to reproduce:**
1. One of our players created a new civic (law? election? not sure)
2. Midnight hit and some things were recalculated? (again, not sure exactly what)
3. All players are now unable to connect, including admins, with the below error message.

Since we cannot connect by any means, and we have no easy way of manually modifying the database, we've had to roll back to a save before the civic existed.

**Expected Behaviour:**
Players should be able to connect succesfully to the server.

**Actual Behaviour:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.HoursPlayed.Description()
   at Eco.Gameplay.Civics.GameValues.GameValueExtensions.DescribeNullSafe(GameValue val)
   at Eco.Gameplay.Civics.GameValues.Compare.Description()
   at Eco.Gameplay.Civics.IfThenBlock.<>c.<DescribeFull>b__15_0(GameValue`1 x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eco.Gameplay.Civics.IfThenBlock.DescribeFull(Boolean isElse)
   at Eco.Gameplay.Civics.Laws.LawSection.<>c.<Description>b__22_1(IfThenBlock x, Int32 i)
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at Eco.Shared.Utils.StringExtensions.TextList(IEnumerable`1 e, String sep)
   at Eco.Shared.Utils.StringExtensions.NewlineList(IEnumerable`1 e)
   at Eco.Gameplay.Civics.Laws.LawSection.Description()
Outer Exceptions:
Error during packaging property 'Registrars' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'IdToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Sections' of 'Eco.Gameplay.Civics.Laws.Law'
Exception has been thrown by the target of an invocation.</size>
```

**Any mods installed?**
Nope! Vanilla install.

**Extra notes**
Because we cannot load into the game, I have no way of figuring out what civic caused it nor how to reproduce the civic that caused it. If a dev would like access to our game.eco and game.db files, I can provide via a google drive link. It fails to connect when running the same game.eco/game.db files locally, as well, so it should be easy to reproduce the connection error.

Note that we do not have much setup in civics, so there are very few things it could be if someone wants to investigate our save.

**Comment by Bruno-DaSilva** [comment]
The player who was modifying civics at the time provided us with this comment:
```might have something to do with a demographic related to hours played that I was proposing at the census bureau```

**Comment by Bruno-DaSilva** [comment]
Follow up from the player:

```I'm not convinced that a proposed law was the culprit, since a proposed law doesn't actually do anything yet. I'm guessing the problem was with the Executive Office, which I had proposed an executive order but then picked up the workstation. Some orphan check ran at midnight and, since the object didn't exist anymore, threw the null reference exception.```

Obviously we have no way of verifying whether that is exactly what's causing the issue, but I'm hoping it gives enough details for this to be looked into.

**Comment by IcedForge** [comment]
@Bruno-DaSilva Thank you for reporting, sorry for the very late reply, if you have any further idea on what the law contained that would be super helpful. Will keep testing it and see if i can find it but it looks like it is a very unique case situation.

**Comment by Bruno-DaSilva** [comment]
@IcedForge We ended up rolling back, and didn't encounter the issue again. We have no idea of any further details of the root cause.

**Comment by IcedForge** [comment]
Ok, ill close this for now then if you run into it again feel free to contact me directly on discord or reopen it and tag me here.
