### ISSUE TITLE
[0.9.2.0 beta staging-1872]Incorrect Wealth calculation

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19745]
Civics system is not calculating wealth properly, it is counting wealth of both managers and users, it should only count managers of an account

![Screenshot_43.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8273a0ad-132b-47c6-b6f9-082fd4f6e41c)

![Screenshot_44.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/aa58e9c4-c0d8-4848-b6f7-ff9c47b314a5)

**Comment by serpopov** [comment]
seems that not reproduced @IcedForge 
on pic above you are manager, not user
if account has no manager then all users count

**Comment by IcedForge** [comment]
It is not counting user wealth at all.  (with no managers) which is then a easy tax evasion since you have all same permissions as a manager except the ability to add more users.

![Screenshot_22.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/88fb6a05-fe1d-4be2-8fb3-72d3c99de9d5)

This account has 1.000 "Oil Barrels" in it but his personal account also contains 1.000 "Oil Barrels" so total wealth should account to 2.000 in total.
![Screenshot_23.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/6acf0dce-9a63-4bed-969a-fc0c83d5af50)

**Comment by serpopov** [comment]
@IcedForge We don't understand your last comment since you are saying it has 1000 barrels and screenshot shows None in Money in Account

**Comment by IcedForge** [comment]
Closing this after some further testing this seems to be working as intended on 9.3 - staging - 1961
