### ISSUE TITLE
[0.9.2 Staging] Hide Rent Game Actions from 9.2 release

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19759]
For 9.2, we will not be implementing rent. We either need to hide or remove the related game actions from staging. One we need to hide is **Pay Rent Or Move In Fee**. I will update the issue if I find more.

**Comment by SlayksWood** [comment]
also need to hide Could not pay Rent in Recidency changed trigger:
![image](https://user-images.githubusercontent.com/45708377/103077760-76525f00-45e1-11eb-8bd5-bf41c597cf28.png)

**Comment by SlayksWood** [comment]
and this 
![image](https://user-images.githubusercontent.com/45708377/103077999-f5e02e00-45e1-11eb-8140-4ccf4cf3355a.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/103078232-79018400-45e2-11eb-8fcc-7ebe842ed520.png)

**Comment by tuha263** [comment]
I will add notes  "(Note: this is only used in Eco 9.2 if the experimental feature 'Rent' is enabled)"  instead of hiding them according @johnkslg suggestion

**Comment by SlayksWood** [comment]
need to add here too:
![image](https://user-images.githubusercontent.com/45708377/103128801-c5fb5e00-46a7-11eb-9cc4-49d2a7fc7088.png)
