### ISSUE TITLE
Law trigger improvement

### ISSUE THREAD

**Issue by tuha263** [StrangeLoopGames/EcoIssues#19757]
- [ ] The categories in the trigger dropdown default to all being expanded. It might be easier for ease of navigation if they defaulted to all collapsed or perhaps remembered the way they were left. 
- [ ] With the option 'With Tool Used' - there is often the possibility of acting with no tool. Is there value in adding 'no tool' or 'Hands' as an option in this list when appropriate?
separate from https://github.com/StrangeLoopGames/EcoIssues/issues/16277

**Comment by tuha263** [comment]
- for the first one don't think we need to do it, or if we do that I need more detail
- For the second one, I need an Icon for "no tool" or "Hands"

**Comment by IcedForge** [comment]
I believe this would tie into our other discussion regarding Hunt/gather separation as well as item destruction via alternative means.
So having None / No tool or maybe add "By hand/Hands" as its own tool type? that way we can make laws a bit more user friendly and also explicitly set actions not performed with intention of using would be able to stay none vs action that is performed with the intent of usability as hands unless a specific tool is used.

As for the first one i dont really see a direct value of changing its behavior at the moment? Maybe needs to be further investigated and discussed? or possibly adding in a different filter / expand system inside it when using list and not grid display?

**Comment by tuha263** [comment]
@IcedForge can you help me to list out all Actions which can use "Hands", I only know the PlantSeeds and ConstructAndDesconstruct now.
