### ISSUE TITLE
setup cw auto scaling manifest

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19758]
Just to clarify, enabling auto-scaling through the UI only configures the cluster autoscaler. The cluster autoscaler however, needs to be told when to communicate with the DigitalOcean API by a horizontal pod autoscaler. That needs to be configured through a manifest file and is where you would specify which deployment to watch and what level of CPU usage to scale at. Have you created anything like that and applied it yet? Here's an example from our product docs: https://www.digitalocean.com/docs/kubernetes/resources/autoscaling-with-hpa-ca/

And this is Kubernetes official documentation on the HPA: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

Let me know if my explanation makes sense or if you have any follow up questions.

**Comment by redwyre** [comment]
I have no idea about any of this stuff

**Comment by mirasrael** [comment]
@j3fffff they says about horizontal scaling. It means it will create replicas of same pod if load is high enough. It may be useful if you have read-only DB, backend or any other service which need to be duplicated to reduce load. Usually combined with load balancer. It assumes we have identical pods (replicas) which may go up and down depending on CPU/Memory load per pod.
In our case we don't use replicas, each game server is unique and so we don't need this kind of scaling.

**Comment by j3fffff** [comment]
@mirasrael I confirmed with DO, that their auto scaling will not work for us.
They recommend updating our old custom scaling, or switching to https://agones.dev/site/
Guessing updating our custom scaler will be best fit for continuing cloud world release.

As I remember, the problem with our custom scaler was that it was mis calculating needed nodes.
So solution will be in that reopened issue: https://github.com/StrangeLoopGames/EcoIssues/issues/17822
