### ISSUE TITLE
9.2 Icon Request

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19763]
We need some icons for 9.2 in various categories. We can possibly reuse an existing sprite for some things in the short term, for example the Hunting Upgrade. Here is the full list

**Legal Actions**
- [x] InviteResidentLegalAction
- [x] TransferToAccountLegalAction

**Ecopedia:**
- [x] Residency

**Game Actions:**
- [x] ResidencyChanged
- [x] RecurringPayment
- [x] WorkedForWorkParty

**Upgrade:**
- [x] HuntingUpgradeItem

**Comment by RobertMangano** [comment]
need more info on what the hunting upgrade item is supposed to be

**Comment by WeaselDog** [comment]
Great job!
