### ISSUE TITLE
Jenkins builds timing out

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19767]
![image](https://user-images.githubusercontent.com/3536496/102541451-49dc9700-4065-11eb-8ba1-c0a6e15fa1a0.png)
If its caused by parallel building making builds take forever we can reduce parallel limit (or set to no parallel probably easiest and fastest results)
If its caused by a long queue of builds ahead of it, the build should never time out in this case when its just waiting.

**Comment by redwyre** [comment]
This was most likely caused by develop and staging having different unity versions, which was rebuilding lots of files. I've added separate jobs for now.

It would be useful to upgrade to a machine with SSDs though.
