### ISSUE TITLE
[0.9.1.8 beta release-130] Bank Account user permissions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19766]
Bank account users are not able to set an account in stores for usage to sell products for this account.

Create account
Set player to "User" 
Try to use the account for store sales

**Comment by tuha263** [comment]
seem it was fixed on staging
![Store](https://user-images.githubusercontent.com/9598614/105286349-a98c0c00-5be8-11eb-9b8e-16a8e4639c9d.png)
So I will mark it `Not Reproduce`

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/107323664-bef1a900-6ab7-11eb-89a8-89b1ebe900c9.png)
