### ISSUE TITLE
[0.9.2 staging-1876] "Edit Property" bugs

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19764]
- [x] 1. New property is created for plots that were claimed before editing.Step to reproduce:
- claim 3 plots: 
![image](https://user-images.githubusercontent.com/45708377/102460600-4989cf00-4058-11eb-8bdb-dba60967f668.png)
- start to edit 'Slayksford':
![image](https://user-images.githubusercontent.com/45708377/102460644-5ad2db80-4058-11eb-87ee-6d98830510db.png)
- claim some plots in Edit mode:
![image](https://user-images.githubusercontent.com/45708377/102460716-75a55000-4058-11eb-817d-6144950bb1eb.png)
- press submit and check property. First 3 plots became Slaysberg instead Slayksford:
![image](https://user-images.githubusercontent.com/45708377/102460759-85249900-4058-11eb-9bde-c0aed17ced78.png)

- [ ] 2. Somewhat strange 'Unavailable':
![image](https://user-images.githubusercontent.com/45708377/102460908-b2714700-4058-11eb-88c3-6d3a1319b87a.png)

- [x] 3. Incorrect spliting into different properties after editing if original property have some plots which not connected to it. Should we be able to do this at all? Step to reproduce:
- start to edit 'Slayksborough":
![image](https://user-images.githubusercontent.com/45708377/102461266-33c8d980-4059-11eb-98f1-db688a43c837.png)
- Draw 2 properties, They should not connected to each other:
![image](https://user-images.githubusercontent.com/45708377/102462460-dcc40400-405a-11eb-9899-6b275594ce43.png)
- I guess that with our new system I will have 3 different properties after submit and I have notification about it:
![image](https://user-images.githubusercontent.com/45708377/102462727-3b897d80-405b-11eb-9671-8ba72da6b12e.png)
- but I have 6 properties:
![image](https://user-images.githubusercontent.com/45708377/102462769-480dd600-405b-11eb-95c9-e2d4abe08609.png)

**Comment by gzatravkin** [comment]
fixed 1 and 3 at https://github.com/StrangeLoopGames/Eco/pull/7440.

'Unavailable' is map legend for parts you can't edit.
