### ISSUE TITLE
USER ISSUE: [9.1.8] Water on Aqueduct is blocked

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoIssues#19771]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. Make an aqueduct
2. Put blocks to stop the water
3. Remove these blocks
4. The water doesn't come back

**Expected behavior:**
It should have water like before the stopping water

**Actual behavior:**
Instead, there isn't water anymore

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and No

**Screenshots:**
![bug](https://user-images.githubusercontent.com/19348373/102556009-37e01000-40c8-11eb-83b5-f2e5aff41023.PNG)
![bug2](https://user-images.githubusercontent.com/19348373/102556010-37e01000-40c8-11eb-86da-0ed152515f07.PNG)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5712697/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5712696/Player.log)

**Comment by SlayksWood** [comment]
@lou-vier Thank you for the report. It will be fixed in 9.2 and we will continue to improve water in next updates.
