### ISSUE TITLE
Exception when placing a lot of wood blocks very quickly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1977]
"Cannot lock an inventory while already in another lock."

>	Eco.Gameplay.Items.InventoryLock.InventoryLock(inventories) Line 29	C#
 	Eco.Gameplay.Items.InventoryChangeSet.InventoryChangeSet(inventory, user) Line 87	C#
 	Eco.Gameplay.Items.InventoryChangeSet.New(inventory, user) Line 79	C#
 	Eco.Gameplay.Items.BlockItem.PlaceBlock(targetPos, player) Line 56	C#
 	Eco.Gameplay.Items.BlockItem.OnActRight(context) Line 47	C#
 	Eco.Gameplay.Players.Player.PlayerInteract.AnonymousMethod__1(inter) Line 331	C#
 	Eco.Gameplay.Players.Player.PlayerInteract(info) Line 342	C#

**Comment by metachronism** [comment]
cant repro
