### ISSUE TITLE
USER ISSUE: Flying to Space

### ISSUE THREAD

**Issue by Alisson-F** [StrangeLoopGames/EcoIssues#19775]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
1. Stand on top of rock
2. Mine It from top to botton

**Expected behavior:**
i stand in same place or at last drop a little

**Actual behavior:**
i'm rocket to space

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, i'm vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5713225/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5713226/Player-prev.log)

**Comment by SlayksWood** [comment]
Will be fixed in 9.2
