### ISSUE TITLE
Birds shouldn't land in thin air.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#1978]

**Comment by keegan-o** [comment]
This needs to be re-exported translated down, but I can't do that and freeze transforms or the animation will be broken. Ideally just have the animations re-done cleanly.

**Comment by keegan-o** [comment]
Milenko is working on new birds I'll hopefully hook up either today or tomorrow.

**Comment by MarjieAVolk** [comment]
Yeah they're still landing in the air

**Comment by keegan-o** [comment]
The art is now fine, the bug is from them landing on plant blocks iirc according to sean; un-assigning artists.

**Comment by SeanAtr0n** [comment]
They don't land in thin air anymore, they land on the tips of blades of grass and flowers >.>
