### ISSUE TITLE
Trying to close a window with UIManager that was not opened with UIManager

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19780]
press:
![image](https://user-images.githubusercontent.com/45708377/102452942-57395780-404c-11eb-9de6-dd5f4e8733d8.png)
and close this window:
![image](https://user-images.githubusercontent.com/45708377/102452966-615b5600-404c-11eb-99e5-39e7718fb080.png)
```
Trying to close a window with UIManager that was not opened with UIManager: MouseInputBlocker-1732960
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UI.UIManager:Close(GameObject)
ModalUI:OnDestroy()
```

_Originally posted by @SlayksWood in https://github.com/StrangeLoopGames/EcoIssues/issues/19288#issuecomment-747245720_

**Comment by IcedForge** [comment]
Added this to the player log pre 9.1

[09:48:50.430] OK
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
System.Action`1:Invoke(T)
Eco.Shared.Networking.<>c__DisplayClass22_0`1:<Call>b__0(Object)
System.Action`1:Invoke(T)
Eco.Shared.Networking.RPCManager:HandleQueryResponse(BSONObject)
NetworkManager:Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetworkClient:TryReceivePacket()
ClientPacketHandler:ReceiveWhile(NetworkClient, TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
RootMotion.Dynamics.BehaviourDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by beastyn** [comment]
@WeaselDog I was discussing it with Cabriel. Thing is, this is a design problem and do not break anything currently. And the problem not only in this place, but in a lot of places. And they should be checked after fix.
So, we can remove warning in the lot and leave it be only in editor and then for 9.3+ we need to redo it for all the places.

**Comment by beastyn** [comment]
Fast fix fro staging was made for this particular case.
But we have more places with this error.
-SelectionPopup maybe something else

**Comment by WeaselDog** [comment]
Issue that caused this will be fixed in https://github.com/StrangeLoopGames/EcoIssues/issues/19949
