### ISSUE TITLE
[0.9.2 staging-1878] Stuck on Entering world.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19781]
Step to reproduce:
- migrate this world: https://drive.google.com/file/d/1kAqhxV0yHz8pduL4hf2ZS5Bh7xgSQRxr/view?usp=sharing
- try to connect to server. I stuck on Entering world:
![image](https://user-images.githubusercontent.com/45708377/102598560-43b1ed80-412d-11eb-8db7-55c647433142.png)
- have a lot of warnings in server log:
![image](https://user-images.githubusercontent.com/45708377/102598587-4d3b5580-412d-11eb-9697-5bb0a27e50d7.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5714836/Player.log)
[log_201218120636.log](https://github.com/StrangeLoopGames/EcoIssues/files/5714843/log_201218120636.log)

**Comment by mirasrael** [comment]
It hanged because of infinite loop in Tag Parser. Thread starvation spam happens because server uses lot of memory and user's PC doesn't have enough memory so it spends lot of time in GC.
