### ISSUE TITLE
[0.9.1.8] Deer has some (headshot) hitbox issues

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#19784]
I think there is something up with Deer's heatshot hitbox. You can shoot right through its neck without doing any damage, some parts of the head also miss, and generally it's a pain to hit, more so than it should be. I think I saw someone else complain about hunting Deer as well, so maybe there is something off with its hitbox...

**Comment by SlayksWood** [comment]
will be fixed in 9.2 #13635
