### ISSUE TITLE
Add CDN cloudfront for game download s3 bucket

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19789]
speed up game downloads.
asses cost of cloudfront, setup cloudfront, appy to builds bucket

**Comment by Abhiw205** [comment]
Hi Jeff, 

As already discussed, implementing CDN cloudfront for game download s3 bucket, will cache large zip file. That will increase run time bandwidth cost. Please review this ticket. 


Thanks
Abhijee
