### ISSUE TITLE
Refactor TryClaimOrUnclaim to use a single game action pack 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19788]

**Comment by IcedForge** [comment]
Any clarifications on what was done here? Is it closable or not happening until 10.0 Should this be moved to backlog instead of ready for QA if so?

**Comment by gzatravkin** [comment]
It's some internal code stuff. Before it was creating game pack action per claiming plot, now it does it at single one. It's already done so I guess I can just close it
