### ISSUE TITLE
[0.9.2 staging-1880] Title Holders in registar component localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19794]
![register](https://user-images.githubusercontent.com/26339332/102695751-56feaf00-423a-11eb-96f2-5cb6b7b7109d.png)

**Comment by SlayksWood** [comment]
fixed in gibberish
![image](https://user-images.githubusercontent.com/45708377/107322726-0e36da00-6ab6-11eb-9187-b46a5a01ae7d.png)

**Comment by StallEF** [comment]
@gabrielgindridev  it have localization but not upload on crowdin now!
