### ISSUE TITLE
[0.9.2 staging-1880] Exchange component localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19793]
![Exchange](https://user-images.githubusercontent.com/26339332/102695252-12254900-4237-11eb-95cc-e3384d093ca0.png)

**Comment by SlayksWood** [comment]
fixed in Gibberish
![image](https://user-images.githubusercontent.com/45708377/107322804-38889780-6ab6-11eb-954f-679308d802b1.png)
