### ISSUE TITLE
[0.9.2 staging-1880] Barter in Economy viewer

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19792]
1) In 9.0 Barter was how 0 currency and was change to "Barter" but now add in Crowdin
2) Your Income & Expenses 

![2020-12-19 (2)](https://user-images.githubusercontent.com/26339332/102695005-c32ae400-4235-11eb-8881-cf21ac3d6986.png)

**Comment by SlayksWood** [comment]
@gabrielgindridev don't have any problem in Gibberish, but can you check it, sometimes we have such bugs with localization:
![image](https://user-images.githubusercontent.com/45708377/102743705-0f2a7580-4369-11eb-9835-126d913f0191.png)

**Comment by StallEF** [comment]
@SlayksWood  word "Barter" is absent on Crowdin just now

**Comment by gabrielgindridev** [comment]
Added word will add to Crowdin
