### ISSUE TITLE
[0.9.2 staging-1880] Text in Standing Steel Brick Sign

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19791]
Text in Standing Steel Brick Sign does not fit into the boundaries of the slab
![Text in Standing Steel Brick Sign](https://user-images.githubusercontent.com/26339332/102693583-c1105780-422c-11eb-9c78-a24b06485e3f.png)

**Comment by Sekor2600** [comment]
fixed in svn staging

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/102883202-ade5cd80-4460-11eb-826f-9aca3b998fb8.png)
