### ISSUE TITLE
Pollution not visible on terrain

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1979]
shows up on water, not visible otherwise on plants or anything

**Comment by SeanAtr0n** [comment]
Looks like material mapper broke the code that setup the link to the pollution map

**Comment by metachronism** [comment]
nooooooooooooo

**Comment by SeanAtr0n** [comment]
i'll just make it a global property for terrain

**Comment by SeanAtr0n** [comment]
fixed in svn
