### ISSUE TITLE
CSVLint detect error in defaultstrings.csv

### ISSUE THREAD

**Issue by JNordik** [StrangeLoopGames/EcoIssues#19790]
CSVLint detect error in defaultstrings.csv on line 83.
"Line 83 has formating error: double quote chars are not consistent"

Many editors break markup when parsing a file and preparing it for editing.

**Comment by IcedForge** [comment]
@JNordik Thank you for reporting.
Not entirely sure if i understand where this issue is happening? 
Checking through both develop, staging and release branch could you add some more information about where you are encountering this issue and which build you are using?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
