### ISSUE TITLE
Linking Steam account to slg account doesnt give icon

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19796]
User should get betaicon, doesnt get anything

**Comment by denysaw** [comment]
@SlayksWood Could you please reproduce it and tell me, what notification you'll get in the end (maybe PrtScr it) and gimme userId you tried, so I'll check what icons he'll get. Thank you very much! Will be very helpful!

**Comment by denysaw** [comment]
Or you @IcedForge could also do it ;) Thanx a lot!

**Comment by SlayksWood** [comment]
Confirm this, checking on staigingland. Step to reproduce:
- create a new account.
- log in.
- press link a steam account.
- link a steam account.
- check available icons:
![image](https://user-images.githubusercontent.com/45708377/102868639-791b4b80-444b-11eb-992f-04770f528e01.png)
to compare to creating a new account and buy game on our website:
![image](https://user-images.githubusercontent.com/45708377/102870213-c7c9e500-444d-11eb-9b94-9619b65ef7f7.png)

**Comment by denysaw** [comment]
Done. Could be tested on Staging (by editing urls).
