### ISSUE TITLE
[0.9.2 staging-1880] Exchange component Bug

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19798]
if add 101 currency exchange we have message "Can't have more than 100 exchanges listed." but exchange  add and 102 and 103 and any other
![bug](https://user-images.githubusercontent.com/26339332/102698543-2c6b2100-424f-11eb-9d4e-61e6ec1a9104.png)

**Comment by SlayksWood** [comment]
we have problem with restrictions:
![image](https://user-images.githubusercontent.com/45708377/102990226-1a77cf80-4528-11eb-8705-1af0bb8ce72a.png)
second player try to change:
![Uploading image.png…]()

**Comment by SlayksWood** [comment]
Restriction is fixed but still have not friendly UX here. will create a separate issue.
