### ISSUE TITLE
USER ISSUE: picked up a item in game on ECO and went flying into the sky, can't die tp or anything and spent hours on game and now I lost everything all my progress, my stream is disappointed on twitch because i was recording at the time for twitch, and the game auto saves so I can't go back to fix it :/

### ISSUE THREAD

**Issue by xxwhail12xx** [StrangeLoopGames/EcoIssues#19807]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by xxwhail12xx** [comment]
any ideas on how I can fix my game ?

**Comment by mirasrael** [comment]
@xxwhail12xx this issue fixed in latest build (upcoming 9.2 release), but if you can't revert to backup you can contact me in Discord, send your save and I can manually fix it and send your back (mirasrael#5137).

**Comment by SlayksWood** [comment]
@xxwhail12xx You can use admin command if you are admin like /fly or /teleport or ask your admin to teleport you (/teleport targetto).

**Comment by Diablo347** [comment]
I have the same Problem and the admin isnt active to solve the problem with me. Can you fix it for me or is this game lost for me?:/

**Comment by mirasrael** [comment]
@Diablo347 did you try `/unstuck` command? Unfortunately it can't be fixed without admin unless `/unstuck` works (because he should either use a command or provide game save file and replace it on the server after fix). But in 9.2 (next version not released yet) it should be fixed.

**Comment by IanMoroney** [comment]
I had the same issue, and the /unstuck command worked for me, it just brought me back to spawn, so i had to walk back home.

**Comment by Diablo347** [comment]
Yea worked for me too, thanks!

**Comment by IanMoroney** [comment]
Welcome! And happy Christmas :)

**Comment by IcedForge** [comment]
Will close this as its fixed for 9.2 and op's issue was resolved.
