### ISSUE TITLE
[0.9.2 staging-1880] Ashlar Stone Fireplace texture bug

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19804]
error in the parameters of the texture mapping on the model Ashlar Stone Fireplace
![2020-12-19 (11)](https://user-images.githubusercontent.com/26339332/102723428-e084ae80-4318-11eb-9d9e-465626ccfcd9.png)
![2020-12-19 (12)](https://user-images.githubusercontent.com/26339332/102723430-e1b5db80-4318-11eb-8021-fe5121f2b076.png)
![2020-12-19 (13)](https://user-images.githubusercontent.com/26339332/102723431-e24e7200-4318-11eb-9e2d-4bcc33d6bf8d.png)

**Comment by Sekor2600** [comment]
fixed in svn staging
