### ISSUE TITLE
Plow contract issue

### ISSUE THREAD

**Issue by EratoHeti** [StrangeLoopGames/EcoIssues#19803]
This happens on the most recent version of eco, 9.1.8. It happened to me earlier on another server, I'm erato. And it happened to Zirath on this one.

It happens once somebody tries to plow a field according to a work contract including 'plowing'. Then people are trapped from being able to rejoin the game until the whole contract is cleared.

I've posted the file bug below (it's huge).

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClausePlowField.ShouldOverrideAuth(GameAction action)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Eco.Gameplay.Economy.Contracts.ContractManager.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.GameActions.ActionUtil.ShouldOverrideAuth(GameAction action)
   at Eco.Gameplay.Players.Player.QueryAuth(Guid authId)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>

Edit: cleaned issue into a log.txt instead

**Comment by IcedForge** [comment]
Thank you for reporting. @EratoHeti 

Player Log
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5810068/log.txt)

Will further investigate the contracts to find all ways the plow and custom clauses are causing these issues.

**Comment by IcedForge** [comment]
Mentioning this in here as well #19737 as they are both plow contracts with crash issues.

**Comment by SlayksWood** [comment]
Contractor doesn't have authorization rights to hoe:
![image](https://user-images.githubusercontent.com/45708377/107031333-10055280-67c3-11eb-83e0-f29d540085ef.png)

**Comment by SlayksWood** [comment]
Contract is not crash server, so this is another issue.
