### ISSUE TITLE
[0.9.2 staging-1881] Disconnect Icon in many cases when connect to server first time

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19812]
I can't reproduce it 100%, but This problem have a lot of people - I am, Jens, Alex and Anna.
![image](https://user-images.githubusercontent.com/45708377/102767473-aa831100-4390-11eb-9731-31c921176621.png)
First time I have it last week. It's not high issue, because it's only visual bug, but we need to fix it before release.
So create a new world and connect to it, if you don't have problem repeat it a several times.

**Comment by IcedForge** [comment]
Seems like its fixed, will close it for now have not encountered it since.
