### ISSUE TITLE
USER ISSUE: Swinging tools at animals...

### ISSUE THREAD

**Issue by PeterFargo** [StrangeLoopGames/EcoIssues#19817]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Select any tool, hammer, axe, picaxe, does not do any damage to animals, which is un realistic and un-immerseive.

**Expected behavior:**
killed the animal or at least damaged the animal within the first 10 swings.

**Actual behavior:**
made a metal clink noise and the animal ran away everytime you swung at it....while not doing damage.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no I do not have any mods installed, nor does it happen when i have mods installed, b/c I wasn't aware that you could likely install mods to make this game better.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@PeterFargo Thank you for the report.
This is intended behavior for now. You can kill animals only with bow. You can use Torch or Axe to avoid the attack of predators. But you can't kill any animals with their.
