### ISSUE TITLE
Room Volume Bug

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1982]
I had a room with exactly 50 volume, and 2 tables that each took 25.  I placed a third one, and status for it said 25/50 used (i.e. it ignored the other 2 tables).  The other 2 tables each said 50/50 used.

**Comment by craig-jong** [comment]
I can't get this to reproduce. Thanks rooms.

**Comment by MarjieAVolk** [comment]
Oh I thought I put the high priority label on, oops well either way

**Comment by craig-jong** [comment]
Actually, I think I know what caused this and it may not be relevant anymore - rooms used to occasionally create a second, identical room on top of themselves which would cause this behavior. That was fixed, although I think I fixed that before this was made. Perhaps if the room was created prior to that fix, it might have still had two rooms?

**Comment by MarjieAVolk** [comment]
I did make the bug a good long while ago, and that explains it so.

**Comment by craig-jong** [comment]
I'm going to close this issue - if it happens again I'll pull the save and check it out.
