### ISSUE TITLE
Fast load not working

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19827]
![image](https://user-images.githubusercontent.com/3536496/102943374-a75d5300-446c-11eb-8c5f-982f1286f6fc.png)
It used to use a default renderer for the landscape, so you could still see it. Consult @mirasrael

**Comment by WeaselDog** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/19686
