### ISSUE TITLE
[0.9.2 staging-1883] Recipe name in tooltip lost localication 

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19832]
![2020-12-23 (1)](https://user-images.githubusercontent.com/26339332/102969130-366a7980-4506-11eb-8380-7128e139f19d.png)
![2020-12-23](https://user-images.githubusercontent.com/26339332/102969131-379ba680-4506-11eb-909d-ead444d49878.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/103067569-4482cd80-45cc-11eb-97a1-d2b2b4fc3a50.png)
