### ISSUE TITLE
Archive downloads sort by server version

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19839]
All versions 9.0 and above. Have 4 different versions of the Game Server based on OS
For example:
EcoServerPC_v0.9.0.0-beta.zip
EcoServerPC32_v0.9.0.0-beta.zip
EcoServerOSX_v0.9.0.0-beta.zip
EcoServerLinux_v0.9.0.0-beta.zip

Everything before v9.0 only has one server, and its for PC.
For example:
EcoServer_v0.8.3.0-beta.zip

On archived downloads page, this needs a little updating.
All the correct links are there,
but for v9 and up, they need a label like Server PC, Server PC32, Server OSX, Server Linux

**Comment by denysaw** [comment]
@j3fffff R U sure you've checked Staginlang first? :) Dennis made similar issue for me about 1-2 weeks ago. I've made that already.
But maybe something still needs to be changed. Check please.

**Comment by denysaw** [comment]
Fixed in issue clone.
