### ISSUE TITLE
[0.9.2 staging-1883] Currency name issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19834]
- [x] 1. Can't rename before crafting. Step to reproduce:
- place a new Mint:
![image](https://user-images.githubusercontent.com/45708377/102994557-5878f180-4530-11eb-8478-6cdc7a32a612.png)
- enter name for currency:
![image](https://user-images.githubusercontent.com/45708377/102994585-63cc1d00-4530-11eb-9ee2-5a54f9eb24f0.png)
- want to change it now (I didn't craft it), pay attention to top notification:
![image](https://user-images.githubusercontent.com/45708377/102994647-83634580-4530-11eb-84d4-c56b7942e886.png)
- craft a several times:
![image](https://user-images.githubusercontent.com/45708377/102994716-a2fa6e00-4530-11eb-94d4-44342a059293.png)
- Currnecy name was not changed:
![image](https://user-images.githubusercontent.com/45708377/102994738-af7ec680-4530-11eb-8119-3805c5fdc03e.png)

- [x] 2. If you solve first issue we will have this one. I can change currency name after crafting:
![image](https://user-images.githubusercontent.com/45708377/102994778-c7eee100-4530-11eb-820c-f29af439fdc5.png)

**Comment by SlayksWood** [comment]
"Changing currency name after creation should stay possible" @D3nnis3n. So don't need to fix second point.

**Comment by D3nnis3n** [comment]
Yeh, that's always been possible, actually. Not sure why we should remove that. It's hard to ever get rid of a currency, as you cannot 'delete' it. With this you at least have the possibility to rename it.

**Comment by SlayksWood** [comment]
Also Currency creation should be when you create currency first time, not when you enter its name. It cause somewhat strange notifications:
- Create law:
![image](https://user-images.githubusercontent.com/45708377/103087272-f84d8280-45f7-11eb-8e39-5d4b9e9cb44a.png)
- try to enter currency name I will have notification:
![image](https://user-images.githubusercontent.com/45708377/103087297-09968f00-45f8-11eb-99cd-e9dc8c00f157.png)
- but name still here. Try to craft currency:
![image](https://user-images.githubusercontent.com/45708377/103087314-1b783200-45f8-11eb-8b3d-71b1d79380a4.png)
- but I have currency name in window.

**Comment by D3nnis3n** [comment]
I actually reported that a year ago in some issue. When you can find it,
one more is closed :D

Kirill <notifications@github.com> schrieb am Do., 24. Dez. 2020, 12:56:
