### ISSUE TITLE
[0.9.1.9 beta release-136] User being launched 1500m into the air after breaking block

### ISSUE THREAD

**Issue by IanMoroney** [StrangeLoopGames/EcoIssues#19838]
If you break a block beneath you (such as breaking a yellow block on a tile below you (only way to reach it), you get launched 1500m into the air.
/unstuck is extremely inconvenient because you get put back to spawn.

**Comment by SlayksWood** [comment]
@IanMoroney Thank you for the report. It fixed in 0.9.2
