### ISSUE TITLE
Remove Note from Rent Game Actions

### ISSUE THREAD

**Issue by tuha263** [StrangeLoopGames/EcoIssues#19848]
Remove some notes from Rent Game Actions when the Rent function release
I.e: "(Note: this is only used in Eco 9.2 if the experimental feature 'Rent' is enabled)"

**Comment by IcedForge** [comment]
Also need to remove this comment in the economy tab in the server GUI in the bottom

![Screenshot_26](https://user-images.githubusercontent.com/24981362/107346788-645f4980-6ac5-11eb-8c78-7391f1b5134f.jpg)

Should also include a economy template file as per this issue.
#20213

**Comment by IcedForge** [comment]
It does seem like all civic actions and tooltips are correct so it is only these 2 things remaining.

**Comment by WeaselDog** [comment]
Other two things are fixed seperately.
