### ISSUE TITLE
[0.9.2 staging-1885] "Pay Rent or Move in Fee" trigger Icon is too big 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19852]
![image](https://user-images.githubusercontent.com/45708377/103128582-f7275e80-46a6-11eb-9aed-99adbf93f7a6.png)
![image](https://user-images.githubusercontent.com/45708377/103128704-6f8e1f80-46a7-11eb-8d56-97615e5da9c7.png)
![image](https://user-images.githubusercontent.com/45708377/103128742-93e9fc00-46a7-11eb-8d08-20d03aed0c12.png)

**Comment by WeaselDog** [comment]
Fixed with update in Eco.unity. We still need an icon for this: https://github.com/StrangeLoopGames/Eco/issues/7487
