### ISSUE TITLE
Add a slot somewhere on the skills page to show how many stars you currently have

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19859]
![image](https://user-images.githubusercontent.com/3536496/103161481-33d28300-4797-11eb-8842-701a2da3b1cf.png)
It should show the star and the count, and when theres none show an empty slot. It could be inset in a corner somewhere perhaps.

**Comment by johnkslg** [comment]
Check the new layout, below is a space for more info.   Get a signoff on design too

**Comment by keegan-o** [comment]
work has gone back and forth and passed off to another squad, open new issue for specific new needs from art team
