### ISSUE TITLE
USER ISSUE: Broken Wooden Hammer makes no broken noise

### ISSUE THREAD

**Issue by andyneff** [StrangeLoopGames/EcoIssues#19856]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Use a wooden hammer until it is broken
2. Continue using it.

**Expected behavior:**
It should use extra calories, but make the broken sound

**Actual behavior:**
It doesn't make that broken sound, but it is using a lot of calories

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Standard Game install only

**Comment by andyneff** [comment]
It might makes one breaking sound when it actually breaks, but only for that **one** hit. However, I feel like I was watching it break one time, and the UI popup said it broke and I didn't even here it that one time.

**Comment by SlayksWood** [comment]
0.9.2 staging-1895 I have broking sound only when pick up blocks, but It's spent calories when I place blocks too, but I don't have any breaking sound.

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm it has been fixed in the upcoming 9.6 update.
