### ISSUE TITLE
USER ISSUE: Beim Abbau von Sand fliest das Wasser nicht weiter

### ISSUE THREAD

**Issue by LuiMee** [StrangeLoopGames/EcoIssues#19853]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Sand im Wasser abbauen

**Expected behavior:**
Das Wasser sollte normalerweise weiterfliesen	

**Actual behavior:**
Im Meer ist dann ein Loch, wenn man den Sand abgebaut hat. Das Wasser fliest nicht weiter.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Eco hat aktuell noch keine Wasserphysik, das funktioniert also leider noch wie vorgesehen.
