### ISSUE TITLE
Hewn Log Windows Displays with the Name of Fence

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#19854]
Version:9.1.9
Steps,  Take Hewn Logs, Take a hammer, Click F,   View over the window spot,  The top says Window Grilles, but the "Pop-up" says Fence.

![image](https://user-images.githubusercontent.com/36024353/103140086-0bb82680-46a8-11eb-9492-5ff6d3f23dae.png)

**Comment by WeaselDog** [comment]
Thanks for letting us know. This will be fixed in Update 0.9.3.
