### ISSUE TITLE
[0.9.2 staging-1888] Profession tooltip header name localization

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19866]
{0} Profession not full used localization in Profession tooltip 

https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru?filter=basic&value=3#174424

![Profession tooltip](https://user-images.githubusercontent.com/26339332/103278005-74224300-49db-11eb-9f7c-ea5c240bb4b2.png)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 266
