### ISSUE TITLE
USER ISSUE: [0.9.1.9] Cart Bottom Text Display Error

### ISSUE THREAD

**Issue by lou-vier** [StrangeLoopGames/EcoIssues#19860]
\
**Version:** 0.9.1.9 beta release-136

![cart_error](https://user-images.githubusercontent.com/19348373/103163046-de2ec280-47f8-11eb-8ce0-35864dda2459.png)

**Steps to Reproduce:**
I don't know how to reproduce it, it's the name in the bottom that is bugged

**Expected behavior:**
It should have displayed the Text correctly

**Actual behavior:**
Instead it shows only a part of the text

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5744052/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5744053/Player.log)

**Comment by SlayksWood** [comment]
@lou-vier Thank you for the report, I can't reproduce it in 0.9.2 staging-1896. 
Can you provide your graphic settings? like this one:
![image](https://user-images.githubusercontent.com/45708377/104166770-56f26900-540c-11eb-8fb6-9a5bbde9f91b.png)

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
