### ISSUE TITLE
USER ISSUE: Kann nichts herstellen

### ISSUE THREAD

**Issue by Zerox-g** [StrangeLoopGames/EcoIssues#19867]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1.an die werkbank von jemand anderes wo man die erlaubnis zum herstellen hat.
2.etwas herstellen

**Expected behavior:**
ich kann was herstellen

**Actual behavior:**
Ich kann nichts herstellen und er zeigt an das das was ich herstellen will noch null sekunden braucht und und das sachen fehlen die aber vorhanden sind

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ich habe keine mods installiert

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Zerox-g Thank you for the report and sorry for the waiting. Can you provide more details? may be any screenshots or video?
Also don't forget to provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
Possible issue with Craft resourse modifier = 0
