### ISSUE TITLE
9.1.9 Hardwood icon very difficult to see due to brown contrast of chat

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19863]
Basically as per subject.

Very difficult to see due to the icon not having any kind of light border to give it definition.

![image](https://user-images.githubusercontent.com/61889138/103235426-0ffb7280-493a-11eb-941d-4d8f0b1cd433.png)

**Comment by keegan-o** [comment]
Added a glow to the hardwood tag to make it stand out more on dark backgrounds like chat. ![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/8a230d8c-122b-40bd-b048-c0065f2797d7)
