### ISSUE TITLE
USER ISSUE: Abfall & Kompost

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19864]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Zedernsamen & Eiche

beides gemeinsam auf den Boden werfen

**Expected behavior:**
beides wird zu Kompost

**Actual behavior:**
1 x Kompost
1 x Abfall

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/63196305/103244814-798d7800-495e-11eb-9fa7-ed26458791f2.png)

**Comment by SlayksWood** [comment]
merged to #19806
