### ISSUE TITLE
Make a Icon for PayWages action

### ISSUE THREAD

**Issue by tuha263** [StrangeLoopGames/EcoIssues#19871]
It's will be in the Finance category
![PayWages](https://user-images.githubusercontent.com/9598614/103282893-b6627900-4a09-11eb-8200-58d47608fef6.png)

**Comment by RobertMangano** [comment]
added icon to icon sheet misc., i don't see it on the list in items though.
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/58206f61-4ede-40ba-bc64-59456bf68630)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107734212-ed68c180-6d0d-11eb-863f-4e324025fd62.png)
