### ISSUE TITLE
[0.9.2.0 beta staging-1889]Civics:  Objects no longer turn inactive/disabled when constitution is missing

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19875]
titles, laws etc are no longer disabled on removing the constitution.

Add constitution
add titles ( via vote and so ) 
remove constitution and i can still be elected and all laws still work

**Comment by IcedForge** [comment]
Still an issue, even if i remove constitution and i no longer have permission to edit, draft or remove things i still have permissions to start elections, get elected i still have both all permissions of that title but i can still be elected and vote / start elections.

**Comment by IcedForge** [comment]
After a election with no constitution this message was a bit odd where it says it failed yet it still completed and worked.

![Screenshot_115](https://user-images.githubusercontent.com/24981362/103897383-c22df980-50f3-11eb-8c72-6616a70479de.jpg)
The ballot box still states i have permissions to vote etc for those titles that are available.

![Screenshot_114](https://user-images.githubusercontent.com/24981362/103897396-c78b4400-50f3-11eb-9fb1-a20f1be2a4b9.jpg)

Repro steps
place capitol, draft and pass an constitution.
place government office ( or spawn it ) and add X amount of titles
remove constitution and wait until it gets removed and now i can still vote for things and start elections etc.

**Comment by SlayksWood** [comment]
Still have an issue, laws still works:
![image](https://user-images.githubusercontent.com/45708377/104151334-d15fc080-53ed-11eb-8e53-d158ba73878e.png)
![image](https://user-images.githubusercontent.com/45708377/104151372-eccacb80-53ed-11eb-90a3-386d8c6ed436.png)

And I have one suggestion. Can you add civics tick when Capitol timer will be end? Because now all objects continue to work until civic tick occurs

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/105169756-0d50ff00-5b2d-11eb-9cf4-ed483e7c5d76.png)
But need to check second time adter fixing this one #20099
