### ISSUE TITLE
USER ISSUE: im stuck

### ISSUE THREAD

**Issue by YTAg64** [StrangeLoopGames/EcoIssues#19885]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. break a rock
2. stand on top of the rocks
3. make the rocks move
4. collect or break the broken down rocks
5. fly

**Expected behavior:**
keeps you on the ground

**Actual behavior:**
sends you into the sky at an alarmingly fast rate

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@YTAg64 Thank you for the reprort. This issue is fixed in 0.9.2. 
If you still  stuck and don't know how to fix it then refer to your server administrator to teleport you.
