### ISSUE TITLE
USER ISSUE: Waypoints

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#19881]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
delete Waypoint in the map (production waypoint)

**Expected behavior:**
Waypoint removed permanently

**Actual behavior:**
a few seconds later, the waypoint is again there

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #14717
