### ISSUE TITLE
Question: Why github?

### ISSUE THREAD

**Issue by Juksefantomet** [StrangeLoopGames/EcoIssues#19884]
Hello!

Just in general, why use github for the ingame bug reporting? Are you expecting every player that contributes to bug reporting to actually have a github account? Not all players are active in the world of repositories 😄

**Comment by D3nnis3n** [comment]
Because this is most effective to our workflow, using ZenHub. For many bugs we require a constant stream of communication with the reporter and that is not possible on other platforms. Searching bugs from a plentitude of different channels simply doesn't work out for us.
