### ISSUE TITLE
USER ISSUE: Look at meteor - tutorial step should not appear with meteor disabled

### ISSUE THREAD

**Issue by Juksefantomet** [StrangeLoopGames/EcoIssues#19883]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Host a new game with no meteor active

**Expected behavior:**
No tutorial step requiring you to look at the meteor	

**Actual behavior:**
Tells you to look up and spot the meteor, it took me several hours before i actually noticed the "x" to remove the tutorial step and clear it off my todo list.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting.
If world does not have meteor enabled it should disable the meteor tutorial step.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1939.

Tutorial for Meteor doesn't appear anymore if it is disabled upon server creation.
Closing.
