### ISSUE TITLE
"Fee and tax of 0 waived [...]"

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1988]
Unnecessary text in the next project message.  If the fee and tax is 0, it shouldn't show this part of the message

**Comment by MarjieAVolk** [comment]
Also, in this same message I'm seeing "Still needs 4 Dirts4 Dirts" - the missing ingredients are included twice?

**Comment by johnkslg** [comment]
Fixed.  The second part I couldnt repo though, maybe fixed

**Comment by MarjieAVolk** [comment]
I'm still seeing this - has the fix been merged?
