### ISSUE TITLE
[0.9.2 staging-1891] Register component bug

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19889]
1) if use mouse on scroll bar to focus on list reset it to first line
2) focus on delete [X] button reset it to first line
![register](https://user-images.githubusercontent.com/26339332/103441156-0be29400-4c5d-11eb-8172-504b9d67d370.png)

**Comment by IcedForge** [comment]
Thank you for reporting.
When mousing over any input element of the interface it resets to top of the UI so if you are not super quick on removing a title or adding a new ( plus icon ) then it will reset the screen to top.

This obviously can only occur if you have a longer registrar list.

**Comment by StallEF** [comment]
@IcedForge  in Bank if  you have long list of accounts it have problem too
