### ISSUE TITLE
USER ISSUE: Fehler an der Werkbank (German)

### ISSUE THREAD

**Issue by Realizin** [StrangeLoopGames/EcoIssues#19895]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Werkbank-Menü betätigen
2. Holz bearbeiten
3. Kann entweder nicht bearbeiten / -oder fertig bearbeitetes -in meinen Fall: "Hardwood Hewn Log" nicht von der Werkbank in die Hände nehmen
(Ich muss das Spiel neu laden damit es für eine kurze Zeit wieder funktioniert)

**Expected behavior:**
Holz bearbeiten können -oder dein erstelltes Material in die Hand/Inventar nehmen

**Actual behavior:**
ich kann es nicht benutzen oder verarbeiten

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein. Ich benutze keine Mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting. 
When this happens ( i.e cannot pickup materials ) could you provide your client logfile for me to go through as it might be some exceptions there that could explain this behavior.
