### ISSUE TITLE
USER ISSUE: ESC doesn't close some windows.

### ISSUE THREAD

**Issue by ssuLost** [StrangeLoopGames/EcoIssues#19891]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Open either your Backback or the campsite. Then hit ESC. 

**Expected behavior:**
Hitting ESC should close windows like it does for other things. 

**Actual behavior:**
It either stops the cursor mode or it opens the ESC menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That works as intended, as the majority of players wanted ESC to not close the backpack.
