### ISSUE TITLE
USER ISSUE: main menu

### ISSUE THREAD

**Issue by regctx** [StrangeLoopGames/EcoIssues#19893]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
start game

**Expected behavior:**
after moving backgroung screen starts, the menu should fade into exsistance	

**Actual behavior:**
the main menu buttons never appear

**Do you have mods installed? Does the issue happen when no mods are installed?:**
vanilla, no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by regctx** [comment]
this is random, some times this bug doesnt show up, sometimes it does. usually after i have played the game, closed it, then reopen it shortly after.

**Comment by SlayksWood** [comment]
@regctx Thank you for the report. I can't reproduce in 0.9.2 staging-1896. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
