### ISSUE TITLE
Starter camp isn't using the wood from it tiny stockpile  

### ISSUE THREAD

**Issue by Narufgg** [StrangeLoopGames/EcoIssues#19892]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Don't know how to reproduce it	

**Expected behavior:**
Tent crafting the workbench using the 20+ ceiba woods from the tiny stockpile			

**Actual behavior:**
Instead it saiding woods is missing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
I don't have any problem with it. Stockpile should be linked. So:
- open Campsite, select Storage tab:
![image](https://user-images.githubusercontent.com/45708377/104176670-adfe3b00-5418-11eb-85c4-734c36ed73c2.png)
- be sure stockpile is linked to it:
![image](https://user-images.githubusercontent.com/45708377/104176713-bf474780-5418-11eb-9514-8789dd5b2ec9.png)
Do you still have the issue?

**Comment by Narufgg** [comment]
it was link but i can make the workbench if i manual put the woods into the work order, the workbench that i made can use the wood in the start camp's tiny stockpile

**Comment by IcedForge** [comment]
When placing down the initial workbench, if it is placed inside the claim it will automatically link to any storage in its range, allowing it to automatically link.

While if you place it outside it will not auto link and require manually to do so via the "Storage" tab in the appliance.
Will close this for now, please reopen if this still an issue that is not resolved by the above mentioned solution.
