### ISSUE TITLE
USER ISSUE: Dead animal body appear above tunnel

### ISSUE THREAD

**Issue by wenjinghuan999** [StrangeLoopGames/EcoIssues#19898]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
use a bow to shoot a crab to death in a tunnel

**Expected behavior:**
the dead crab body should appear at the position the crab died

**Actual behavior:**
it appears on the surface above the tunnel

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@wenjinghuan999
Thank you for reporting.
Animal positioning (both dead and alive) is being worked on and improved upon in the upcoming updates of 9.2/9.3
