### ISSUE TITLE
9.1.9 Present boxes are larger than old crates collision wise

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19904]
Present boxes are larger than the default crates collision wise so ramps going to a flat surface at the top no longer has enough clearance.

Looks like it has made the truck about 20cm taller which is causing the collision

Removing the present boxes allows the truck to pass without issue so it is just the collision size of the present (looks like it is the bow), upon removing an extra line of blocks the truck is able to pass without issue

![image](https://user-images.githubusercontent.com/61889138/103557853-b5b76000-4eab-11eb-9001-ba55a8dcf910.png)

**Comment by keegan-o** [comment]
Fixed in develop anyways, for the next time we do holiday stuff (added a regular meter cube collider)
