### ISSUE TITLE
USER ISSUE: "Could Not Connect"

### ISSUE THREAD

**Issue by CuddlyDino900** [StrangeLoopGames/EcoIssues#19900]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Clicked "Your Worlds"
2. Clicked on a LAN server
3. Clicked "Join"

**Expected behavior:**
It should have joined the game. I was playing last night and had no connect issues.

**Actual behavior:**
The following error message popped up:
```
Connection Failed

Login info could not be verified. Our auth servers may be down.

The operation has timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have mods installed, and do not use them.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
I literally do not have a player.log file? https://prnt.sc/wfk9h8 <-- Screenshot.

**Comment by D3nnis3n** [comment]
Please just try again, this probably was a hickup with the auth servers.
