### ISSUE TITLE
Cancel project with too few material is bugged every table?

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#1990]
* you have 100x and 100y 
* start a project with 10z items you need for 1z = 11x and 10y
* cancel the project you get back all item minus the the too few material now you have 89x and 100y
* best way cancel the project if the time stop becaus items missing now you have 9z 89x 100y
You talk about it but i see no ticket

**Comment by MarjieAVolk** [comment]
Thanks for the example numbers - This is the bug we're tracking the issue on: https://github.com/StrangeLoopGames/EcoIssues/issues/1928  (Closing as a duplicate)
