### ISSUE TITLE
[0.9.2.0 beta staging-1891]Exchange trade confirm window missing entry

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19910]
When ever you complete a trade successfully it will prompt an empty/blank ui windows.

Reproduction
Use /test Exchange
successfully trade a currency for another.

![Screenshot_65.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f44c7b1f-b78c-4829-bfbe-8e91ec882ae3)

**Comment by IcedForge** [comment]
Its now returning a autopopulated msg which is also has a slight incorrect / odd syntax 
![Screenshot_9.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f6a4f06a-c17d-4d54-90c8-15548bf1f975)

Where did the transaction complete message get sent to?

**Comment by Mattprass** [comment]
Yes. It was decided to change to that message based on comments from this PR:
https://github.com/StrangeLoopGames/Eco/pull/7522

It's the same exact message that is displayed on the chat.

**Comment by IcedForge** [comment]
Closing this per discussion.
