### ISSUE TITLE
[0.9.2.0 beta staging-1891]Civics: Cannot ratify constitution due to articles not counting

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19911]
Cannot ratify constitution due to ratification not accounting for articles inclusions in its own election proposal.
https://cdn.discordapp.com/attachments/330136213841510410/795795450740867082/unknown.png

Made an issue for tracking, i believe oleg already have a fix for merging
by this https://github.com/StrangeLoopGames/Eco/pull/7513

**Comment by olegshegai** [comment]
Thanks for creating, will add the link to the PR
