### ISSUE TITLE
[0.9.2 staging-1891] Industrial Lift cabin size

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#19915]
Industrial Lift cabin size very big for a mine dug for him

![2021-01-05 (1)](https://user-images.githubusercontent.com/26339332/103693276-15943080-4faa-11eb-9b12-f5f67f2a0d5a.png)
![2021-01-05 (2)](https://user-images.githubusercontent.com/26339332/103693278-16c55d80-4faa-11eb-87cb-29ba22db8229.png)
![2021-01-05 (3)](https://user-images.githubusercontent.com/26339332/103693280-175df400-4faa-11eb-8e6b-ac3fd7efc250.png)
![2021-01-05 (4)](https://user-images.githubusercontent.com/26339332/103693282-17f68a80-4faa-11eb-991e-81f8a11657b6.png)
![2021-01-05](https://user-images.githubusercontent.com/26339332/103693286-17f68a80-4faa-11eb-9aa4-6bed415f72b4.png)

**Comment by IcedForge** [comment]
I believe we had some discussions regarding this issue with elevators in general and their proximity / adjacent tile placements on terrain forming and what to do about it? Was something ever decided on what to do ? @keegan-o

**Comment by SlayksWood** [comment]
merged to #16425
