### ISSUE TITLE
Allow collecting max possible from tax/pay

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19912]
Reference to this giant law, they had a number of provisions to detect max amount in account and pay that, we can simplify this common case:
https://cdn.discordapp.com/attachments/638407584189251604/795507362764947506/advancedtax.png

add options to 'pay' and 'tax' to:
Text 'collect max possible'  Description 'When the payer doesnt have enough funds, pay the amount remaining in their account.'

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11328
