### ISSUE TITLE
Placing stockpile on sand then deleting turns sand into dirt 6.0.0 #e34aa2e5 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1991]
i created a stockpile on sand, cleared some land away, removed stockpile to make way for my house and all the sand it was on turned into dirt

**Comment by metachronism** [comment]
this is intentional, the different soil types in the different biomes are all considered dirt, they just will look different over time

**Comment by MarjieAVolk** [comment]
Really, even the sand?

**Comment by Conchipedia** [comment]
we are using #cc778b68 as a Server, and when you place 4 pieces of stone in a hole (to fill it up so i could place a stockpile down) the ckpile turn this into Dirt, now that cannot be considered as dirt can it?
