### ISSUE TITLE
[0.9.2-staging] Distribution Station model missing

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#19917]
The Distribution Station model is missing on staging. It is likely related to Christmas update.

**Reproduction:** /give distribution station and place

![DistributionStationMissing](https://user-images.githubusercontent.com/47330823/103709427-5c146b80-4f67-11eb-9cc1-583ffb86ba56.png)

**Comment by IcedForge** [comment]
Works fine on the built client for staging-1892

Is this not a unity fast load issue?  or at least a unity issue 
![Screenshot_72.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/d9b5b632-8585-4a2f-bc33-6ec196e8f155)
