### ISSUE TITLE
Developer Tier (maybe other things as well) cannot be purchased with PayPal from russia

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19919]
![unknown](https://user-images.githubusercontent.com/25908592/103748072-ddb9d700-5003-11eb-97f6-fc9708cbc7fa.png)
"This transaction was rejected because it does not comply with legal requirements."

Setting account to USA _AND_ language to english fixes this.
Any sanctions or stuff ongoing?

**Comment by StallEF** [comment]
@D3nnis3n   https://esellercafe.com/paypal-bails-out-of-russian-domestic-payment-services/
you can place account and bank details for direct transfer without the participation of the payment system
and i know it problem was resolved with change region to USA just

**Comment by D3nnis3n** [comment]
Well, that link says that international buying still works as usual, though. It's only about sending money between russian people.

**Comment by StallEF** [comment]
yes, but from 01.01.2021 start work new antibitcoin law about any anonimus electron wallet and foreign agents law .
even steam posted a notification:
В связи с изменениями в законодательстве Российской Федерации начиная с января 2021 года прямое пополнение кошелька Steam может быть недоступно в течение некоторого времени

I think it is impossible to influence the situation with PayPal  now

**Comment by j3fffff** [comment]
Asking our paypal rep

**Comment by D3nnis3n** [comment]
@j3fffff Any news?

**Comment by j3fffff** [comment]
they just stopped talking after that question :)
kinda doubt were going to get a clear answer from them on this.
is it still being reported?
