### ISSUE TITLE
[0.9.2.0 beta staging-1891]Plot claim tooltip too aggressive

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19921]
Two issues here really.
1. Too big / aggressive tooltips that are kind of in your face even though you are holding a tool that has its sole use for this explicit purpose.
2. The bottom tooltip displaying Plot is already claimed is displaying regardless of ownership or permissions. This should ONLY display when you are holding a claim stake ( since thats the tool capable of altering a plot ) AND it is NOT your property or you do not have permissions to change plot size. Since the changes to elected titles and such this should not display on property owned by a title when the user has the title permissions as well.

It even displays even without tools which i think is incorrect behavior 

Sort of involved from #19137

The top display of the " Claiming property Plots" Completely out of place both in size and style as these 2 are the only UI element tooltips that are not contained inside a defining box of some sort but only this floaty weird out of place display that doesnt fit well with the rest of the HUD or UI elements.
![Screenshot_78.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8d0174b6-c134-47c5-aee7-6db69b6b4368)

And the bottom error being this one
![Screenshot_81.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/217a023b-ae51-4390-9bef-38e2e9fab692)

Without proper bordering or graphics to support the tooltip containment they look rather plain and more like place holders then actual game assets that are released hence why i think the issue is a medium priority BUT should be fixed for release. If nothing else or if there is a future change to them i would suggest hiding them or removing them from staging until that point.

@WeaselDog @johnkslg

**Comment by johnkslg** [comment]
This is going to be useful for settlements, can leave it assigned to me till then.

**Comment by IcedForge** [comment]
Could we tie this ui display to the settlement toggle in server settings? Would solve all problems in one go?
