### ISSUE TITLE
New s3 bucket for release builds

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#19928]
Update Jenkins so release builds  go to current s3 bucket (eco-releases in us-west-2) and are also duplicated to eco-builds-release in eu-central-1
This way user can download from closest server localtion.

**Comment by redwyre** [comment]
Could we rename the second bucket to something like `eco-release-eu` to match the original name?

**Comment by Abhiw205** [comment]
Hi @redwyre , 

Technically renaming of s3 bucket is not supported by AWS, in option creating a new bucket with desired name and sync data into new bucket is doable, Please suggest 

Thanks 
Abhijeet

**Comment by j3fffff** [comment]
its a lot of data to move, im not sure how much it will cost. and users wont see the name anyway. i recommended we make due without perfect naming convection on backend for these 2 buckets

**Comment by j3fffff** [comment]
currently jenkins uploads release builds to us-west-2. 
but i think jenkins is in eu, so it will be faster to first upload to eu bucket (eco-builds-release in eu-central-1)
and then copy over to eco-releases in us-west-2

The goal of all this is to increase download speeds (which are very slow) by allowing users to download closer to them (eu or ca)

**Comment by j3fffff** [comment]
I vote we skip ransferring to new renamed bucket

But we still need deployment to eu bucket (and usual usa bucket).
website is serving game download from both. will break on 9.3 release if we dont update this.

**Comment by redwyre** [comment]
If it's not being used in production yet, then it should be renamed. Once it's in production we will be stuck with the name for 5, maybe 10 _years_. We can copy to a new bucket, update accounts, then remove the old one. I'm happy to sync it up in preparation

**Comment by j3fffff** [comment]
@Abhiw205 can you setup new s3 bucket `eco-releases-eu` in eu-central-1
You can use this AWS CLI transfer code to transfer

aws s3 sync s3://eco-builds-release s3://eco-releases-eu --source-region us-west-2 --region eu-central-1

It takes a long time to transfer all the builds.

When thats complete, let denys know, and he can switch to eco-releases-eu bucket in accounts code.

**Comment by redwyre** [comment]
What might be a better strategy here is to trim down the `eco-releases` bucket and copy from there. There are still a lot of old staging builds in there. I'm happy to go through and remove anything that shouldn't be there.

**Comment by j3fffff** [comment]
i already remove all staging builds and non release builds when i first transferred it.

**Comment by redwyre** [comment]
Are you saying you removed them from `eco-releases` or `eco-builds-release`?

**Comment by j3fffff** [comment]
eco-builds-release

**Comment by redwyre** [comment]
ok, yeah, most of them have been removed but I did notice these ones:
![image](https://user-images.githubusercontent.com/431728/115383213-e633c780-a218-11eb-9696-47c468c7b138.png)

**Comment by Abhiw205** [comment]
Created eco-releases-eu and sync files from eco-builds-release.

**Comment by denysaw** [comment]
@j3fffff @redwyre @Abhiw205 Changed bucket on Sandbox and hotfixed on Prod. Please, check.

**Comment by j3fffff** [comment]
@redwyre can you confirm jenkins prod pipeline is updating both s3 buckets (us and eu)

**Comment by redwyre** [comment]
added with https://github.com/StrangeLoopGames/EcoIssues/issues/19928
