### ISSUE TITLE
[0.9.2.0 beta staging-1891]Urchin/Clam icons missing in filter selection

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19924]
They work with link sprites and interfaces but not in UI filter selections
![Screenshot_88.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/89c59c4c-01a6-44b8-acc6-12d78cdd687f)

![Screenshot_86.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/bae6f26d-b22f-4400-ab49-3e71ffe9e4c6)

**Comment by WeaselDog** [comment]
I can no longer reproduce this
![SpeciesFix](https://user-images.githubusercontent.com/47330823/104399608-da43b580-5505-11eb-8f20-46ff54b897d6.png)

**Comment by Daniel-Magulado** [comment]
Build: Staging
Repro:
1. In-game, spawn government buildings.
2. Proceed to do every necessary step to be able to draft a law using the **Court** table.
3. Draft law. Under the **Triggers**  drop-down menu, select **Harvest or Hunt**.
4. Then click the drop-down icon for the **With Species** option.
5. Observe the art display for Clam and Urchin.

![Missing Assets.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/a540fb0c-aaec-451a-b764-2c594be47615)

**Comment by WeaselDog** [comment]
Can you re-check in the next build? I made a change for these icons.

**Comment by Daniel-Magulado** [comment]
Build: Staging 9.2 - 1898
Resolution: Appears to be fixed. Closing.

![Urching and Clam Icons.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c87c404c-3c05-4680-9413-b9da4c74a9c8)
