### ISSUE TITLE
[0.9.2.0 beta staging-1891] Player Log duplicates error debug 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19920]
Getting duplicate names for a lot of different objects when loading up and joining a server in the player log, this needs to be checked why its happening (no error in server or actually playing but initial join ).

[01:11:34.820] Duplicate object name detected! [Bank Accounts]
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ModBundleManager:FindModObjectsRecursive(Object)
ModBundleManager:FindModObjectsRecursive(Object)
ModBundleManager:FindModObjectsRecursive(Object)
<ReceiveModData>d__47:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5776469/Player.log)

**Comment by serpopov** [comment]
Fixed via SVN
