### ISSUE TITLE
AWS: "Upgrade your RDS for MariaDB 10.0 and 10.1 databases before Feb 09, 2021"

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#19938]
> Upgrade your RDS for MariaDB 10.0 and 10.1 databases before Feb 09, 2021
The RDS for MariaDB 10.0 and 10.1 end-of-life date is approaching. You have 1 databases using these versions that must be upgraded to 10.3 or higher as soon as possible. We plan to automatically upgrade RDS for MariaDB 10.0 and 10.1 databases to 10.3 starting February 9, 2021 00:00:01 AM UTC.
>
> For more information, see the RDS for PostgreSQL deprecation timeline in the Amazon RDS forum.

**Comment by mirasrael** [comment]
@j3fffff  This issue should either be moved to Pumpkin squad or assigned to someone else :)

**Comment by j3fffff** [comment]
Because your the most experienced dev ops person we have and i dont want to break the accounts db.

**Comment by redwyre** [comment]
It should just be clicking a button, just have to make sure backups are working first ;)
