### ISSUE TITLE
[0.9.2.0 beta staging-1893]Avatar edit cancel button wrong color

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19937]
When you edit your avatars color/clothing after creation the cancel button is grey, it should be red to be unison with our other abort/cancel buttons.

![Screenshot_2.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/24dc52e4-c7d9-45c0-b41a-978dbba1c162)

**Comment by TwixterZ** [comment]
fix confirmed as of 9.4 develop 251
