### ISSUE TITLE
[0.9.2.0 beta staging-1893]Ramp placement height duplicate if incorrect if start placement is occupied

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19939]
If you select an already occupied tile to start building a ramp it will not calculate Y placement properly and place full height all the way if you place in a single line.

![Screenshot_9.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/77de9716-b9ad-4c4e-b198-21610a147b5d)

This is happening when starting the placement like this
![Screenshot_10.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f20a6e77-672a-46bd-98aa-df730a215f80)

which might be a nested issue with the block interaction detection for when placing / constructing stuff?

**Comment by gzatravkin** [comment]
Need a video, but it don't seems be a bug. 

You have rectangle selected, not line. 
It may be used to create various vertical lines. It have no much sense to build this kind of ramp, but it's exactly what you are selecting: 4 lines of ramps. I am not sure if here should be any additional restriction. It behaves this way without occupied blocks too:
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/dd5cfa22-612d-4e77-bfc2-df6c98694543)
