### ISSUE TITLE
USER ISSUE: I'm in space?

### ISSUE THREAD

**Issue by noaksey** [StrangeLoopGames/EcoIssues#19946]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. I was mining Redstone	
2. I started collecting it
3. I got fired into space

**Expected behavior:**
Collecting redstone	

**Actual behavior:**
Got shot into space

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank for your reporting.
This issue is fixed for 9.2 please refer to a server admin to help teleport you.
