### ISSUE TITLE
9.1.9 Compost is "sticky" unlike dirt, clay, sand etc

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19942]
Compost is sticky and does not require a block below it to be placed (like how clay used to be pre 9.0)

![image](https://user-images.githubusercontent.com/61889138/103955472-43aa7980-513e-11eb-82c0-14f30e6f0ab9.png)

**Comment by WeaselDog** [comment]
Thanks for letting us know. This will be fixed in 0.9.3
