### ISSUE TITLE
[0.9.2.0 beta staging-1893]Residency when being invited need more information

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19941]
When you get invited to a residence you should be notified where this is located as the only notification you get is this.
![Screenshot_31.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/27a4fbe3-18c5-4d70-95b9-9ef3759277c0)

I believe this should contain both a accept / decline button incorporated in that msg for ease of use, also "landlord/owner" is blank

**Comment by IcedForge** [comment]
Once you have accepted there is also 0 ways to find out where you are resident of in anyway so unless you try to move residency (to get the are you sure to move from X to Y claim ) into something else you have no idea where your residency is located.

**Comment by IcedForge** [comment]
Would also suggest adding a new command for /residence and it would display landlord(if renting) and location/property

**Comment by abaza121** [comment]
https://docs.google.com/document/d/1epQJ9RZd7pjXZDRqk_PS2ECRolc0WsELaSFdUGGBP5k/edit?usp=sharing Plan can be found here

**Comment by abaza121** [comment]
This is now waiting for this feature https://github.com/StrangeLoopGames/EcoIssues/issues/22213

**Comment by johnkslg** [comment]
Also add a tooltip on users that show where their residence is.  
And perhaps put a marker on the minimap for it.

**Comment by johnkslg** [comment]
The tooltip for the deedlocation in the residency notification should show you where in the map it is too.
