### ISSUE TITLE
USER ISSUE: Iron rocker box glitch

### ISSUE THREAD

**Issue by ZeeLO42** [StrangeLoopGames/EcoIssues#19944]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Mine over 300 Iron crush it and then put it in the rocker box the rocker box will then change the amount of crushed iron you need from 3 to 20 for some reason. don't know why this is happening.

**Expected behavior:**
it should have kept the amount of crushed Iron needed for the Iron concentrat the same as it says at 3

**Actual behavior:**
but it would start with 3 and change the amount of crushed Iron needed to 20 and use all my crushed Iron and then I would have used 300 Iron to get 3 Iron bars

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting. 
Could you clarify a few things and also include your log files?

Is this a single player world?
Are you using modules in the machine?
Are you changing any settings in difficulty ? Have you altered these in any way? If not what settings are you using?
Also what OS are you using and localization?( eng, ger, rus etc )?

**Comment by ZeeLO42** [comment]
I don't know where to get the logs sorry can you explain where.

I am on a multiplayer server
I am not sure what modules in the machine you are asking about
We have not changed any settings that I know of it looks like the XP
setting are higher than normal but I don't know
Also, I am using Win 10 and I can speak English living in South Africa

**Comment by IcedForge** [comment]
Yes the modules i am referring to is the reduction modules that are added into machines which reduce resource costs.

So if you have a basic upgrade / mining upgrade module applied in a machine it will reduce resource cost 
Which are affecting objects with a dynamic modifier by cost ( indicated by a green border when you have it applied) 

By default the cost ratio of iron ore -> concentrate -> iron bars are 120 -> 4 -> 6
Which is 20 iron ore per bar ( this is using arrastra and bloomery as smelting tool )
If you add in upgrade modules this is changed into  120 -> 8 -> 24
But if you remove a module in crafting progress it will stop using this bonus and use default values ( it updates for each next cycle of craft so you do not need to recreate the work order itself ).

Could you provide some screenshot on the material costs you are referring to? It sounds like either someone took upgrade modules from your machines or someone changed server settings ( as changing material cost is possible and would not directly affect XP rate ).

Also want to clarify the rocker box vanilla standard recipe cost is 5 crushed iron ore per iron concentrate, not 20 so if you are seing 20 here ( picture below ) someone has changed recipe costs from an admin side.

![Screenshot_57](https://user-images.githubusercontent.com/24981362/104076196-a589e280-5215-11eb-80a7-840798054181.jpg)

**Comment by ZeeLO42** [comment]
I did not take any screenshots of it when it happened we moved the machine
and that fixed our problem. I also now understand the understand how the
modules work so thanks about that.
As soon as it happens again I will remember to take a screenshot and show
you but just wanted to show a heads up about the problem we were having.
Thanks for helping.

**Comment by SlayksWood** [comment]
Closed for now. Reopen it if this problem occurs again.
