### ISSUE TITLE
Skills Green + sign lights up but wont go off even if you run out of points #e34aa2e5

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1994]
When you open skill window and you have enough points to use the little green + sign it stays lit and doesn't go out and makes the little ding sound as if it is adding levels, closing skill window is the only way to make the lit up + go off

**Comment by MarjieAVolk** [comment]
I think this may be fixed now - are you still seeing it?

**Comment by MarjieAVolk** [comment]
Okay, I am not seeing this happen anymore, so marking as fixed - feel free to reopen if you continue to see it
