### ISSUE TITLE
[0.9.2.0 beta staging-1894] UIManager opening things without itself

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19949]
I get this error 
[03:51:26.518] Trying to close a window with UIManager that was not opened with UIManager: SelectorPopup(Clone)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UI.UIManager:Close(GameObject)
SelectorPopupUI:TurnOff()
UI.UIManager:Hide(GameObject)
UI.UIManager:Close(GameObject)
SelectorPopupUI:TurnOff()
SelectorPopupUI:Update()

Or these types 

[03:55:03.510] Trying to close a window with UIManager that was not opened with UIManager: MouseInputBlocker-2511500
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UI.UIManager:Close(GameObject)
ModalUI:OnDestroy()

When ever i open / close a window of this filter type 
![Screenshot_38.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2afb1232-2af7-4c86-b329-b1cf80a67608)

In all civic instances, so laws for picking blocks, skill lists etc all of the same type filter UI window

**Comment by Mattprass** [comment]
Possible Duplicate: StrangeLoopGames/EcoIssues#19780
with Fix: https://github.com/StrangeLoopGames/Eco/pull/7555

Indicates a larger architecture problem.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop 175

Resolution: Closing, not happening anymore.
