### ISSUE TITLE
Can't sell/buy flour

### ISSUE THREAD

**Issue by Skylaria** [StrangeLoopGames/EcoIssues#19955]
Flour does not show in the store's available merchandise list for buying nor selling.

**Comment by SlayksWood** [comment]
@Skylaria Thank you for the report. Seems fixed, I can't reproduce it in 0.9.2 staging-1896:
![image](https://user-images.githubusercontent.com/45708377/104155143-94003080-53f7-11eb-98bf-d8f2be677f91.png)
Learn Milling, I can see it without 'Show undiscovered':
![image](https://user-images.githubusercontent.com/45708377/104156641-9ca63600-53fa-11eb-8871-847bc93a81f4.png)
So closed for now.
