### ISSUE TITLE
[0.9.2.0 beta staging-1894] No tooltip for block rotation

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19950]
We have no tooltip display for rotate blocks so players have to figure out that they can do this on their own, seems like a silly thing to not just have a informative HUD tip for especially since we have button tooltips for usage / labor adding etc .

This should be a "R(detect hotkey) to rotate"

![Screenshot_41.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/83b81d71-1f10-46d5-8257-f6842a70026a)

**Comment by IcedForge** [comment]
We have this for some objects but not all, this is inconsistent and means certain items have this specific condition ( this should be a universal thing on all objects that can be rotated.

![Screenshot_44](https://user-images.githubusercontent.com/24981362/104041346-3098b780-51d9-11eb-81db-5ba3fe750e5d.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 9.3 Staging-1948.

Rocker Box seems to have no issues about tooltip hinting rotation. Once picked up, it has the Q/R rotate tooltip.

Closing for now. Will reopen if QA or Users ever encounter/report such issues.
