### ISSUE TITLE
Fade to 'blur' and back is still noticeably jerky

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19956]
![animx22](https://user-images.githubusercontent.com/3536496/104081285-76a64900-51e2-11eb-875a-30465379c8ed.gif)
The fade should look better, it's jerky and pops. Use a DoTween on it with a nice tweenstyle, quadout maybe.

**Comment by johnkslg** [comment]
I suspect what's happening is this:
- The fade is being triggered multiple times through the fade, which resets the rate at which it fades each time, leading to the uneven progression.

**Comment by johnkslg** [comment]
This is broken again for opening world objects too.

**Comment by ptitducanh** [comment]
@johnkslg I've check some civic objects and the blur looks pretty fine to me :)
![blur.gif](https://images.zenhubusercontent.com/5f21cd42c75e8efdb4582cc7/2eb6b5a9-6344-41a6-942b-40ab7b3d9a51)

**Comment by TwixterZ** [comment]
Tested in 9.4 develop 242.

https://gyazo.com/ce6fc12ab1a4369538ef0272aef69944

Refer to above link, while fading in to blur is smooth, fading out from blur looks jerky towards the end.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

Closing as fixed.

https://user-images.githubusercontent.com/77248866/120895447-83bf4b00-c64f-11eb-9b68-620243326d38.mp4

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2009

![blur.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/aa9792d8-5711-4a8d-a05f-cd182b3afbf0)
