### ISSUE TITLE
[0.9.2.0 beta staging-1894]Civics: Description clarify message a bit

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19951]
When you have Send notice we should clarify a little bit to make it easier to read where the message starts.

![Screenshot_45.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2a9ffe07-59f3-4096-90ca-0c846f7ed76d)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-286.

Court UI now has a clear indication of message content/placement. Closing.
