### ISSUE TITLE
Launched into Outer Space! 

### ISSUE THREAD

**Issue by Helgabay** [StrangeLoopGames/EcoIssues#19953]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Stand on a mineable block (i.e. Granite, Basalt, Coal, Sandstone, etc.).
2. Break the block.
3. If standing in just the right spot on top of the block, player will be launched into space! Enjoy the view.

**Expected behavior:**
Block breaks and player may wobble as it falls.

**Actual behavior:**
Player usually wobbles, but on occasion will instead be launched upwards. When this happens, player usually leaves the atmosphere and goes to outer space. The planet can be seen shrinking as player gets farther away.

Most of the time, this lasts a few seconds to about 30 seconds, with the player eventually falling back down to land on the ground, often several meters away from launch site. However, I was launched from the planet about a day ago and was disappointed to find myself still floating in the vacuum of space, even after reconnecting to the server.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I think there are mods installed, and I have never played without mods, so I have no way of knowing if this happens elsewhere.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5789065/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5789066/Player-prev.log)

**Comment by IcedForge** [comment]
Thank for your reporting.
This issue is fixed for 9.2 please refer to a server admin to help teleport you.
