### ISSUE TITLE
[9.1.9] unstuck option is overuse by players 

### ISSUE THREAD

**Issue by zajcom** [StrangeLoopGames/EcoIssues#19962]
Currently unstuck option just move player to top surfece, that option is often overuse by people who dig to just jump to surface lvl, leave items and back down (e.g. with big hole jump from surface to underground)

unstuck option should not only be blocked as currently with some time period freez, but it should also teleport to e.g.:
- first place where player started
- or place where he put tenate
- or place where he has house
to avoid such easy way of manipulation

**Comment by Conchipedia** [comment]
it has a cool down so cannot be used as often, also not every unstuck will move you to the surface, so i don't see the problem

**Comment by zajcom** [comment]
Its cheating, additionally its a problem when you dig 1x1 hole to looks for resources like gold/cooper; such cold down system that we have currently is not so paintfull - just two palyer who dig in ston/shell  [each may dig 5 level to gather 20 pieces of ston] in 4 minutes may go down about 40-50 levels,

**Comment by D3nnis3n** [comment]
That's what we have the configurable cooldown for, it's not a bug.
