### ISSUE TITLE
Large Corrugated steel door cannot placed

### ISSUE THREAD

**Issue by Macs343** [StrangeLoopGames/EcoIssues#19960]
hello guys, 

i had installed eco again, and the following problem is currently exist.

when i try to place the door, its not on that point which i prefer, its over that point, 7 blocks. that mean, i must go deeper in the earth to place the door. 

i send a few screenshots

thanks guys
![20210109123224_1](https://user-images.githubusercontent.com/77195208/104091073-4eb6f400-527b-11eb-91b5-823f9cc005e0.jpg)

**Comment by IcedForge** [comment]
Thank you for reporting. This issue has been fixed for 9.2 (next update) as of #19534
