### ISSUE TITLE
Chat Bug

### ISSUE THREAD

**Issue by Rjritchie** [StrangeLoopGames/EcoIssues#19964]
It's been around for sometime. Believe it's a known bug. But when you change your building blocks to a different block, Chat will reaper in the chat log. Not sure how it's started, logging out and logging back in usually clears it. But again, you change your block while building, chat will appear in the chat log of something a person has already said.

**Comment by IcedForge** [comment]
@Rjritchie Thank you for reporting, i will close this one as i believe this to be a behavior duplicate in this issue #17990
