### ISSUE TITLE
world won't let me load back in.

### ISSUE THREAD

**Issue by ridferd** [StrangeLoopGames/EcoIssues#19963]
hey, 
i was afk, while friends where playing on my server and when i came back my pc had restarted (so i asume it crashed).
now the world that we where playing on doesn't wanna load. not on my pc, but also not on someone else's pc. 
so i was hoping someone here could maybe save the world? 

here are the wold files. 
https://drive.google.com/drive/folders/1aIyX2opcouAzdws0mNKw2K7yZkx0RO4z?usp=sharing

**Comment by D3nnis3n** [comment]
Your save has likely been corrupted by that ungraceful shutdown - try to always avoid this.
Eco does automatically save backups every 30 minutes by default for you, so try restoring a backup in the /Backups folder of the Storage folder. Unfortunately we cannot fix your savegame and for more investigation we'd need your logfiles, but this is a matter of support over at support@strangeloopgames.com. This channel is only for bug reports, which this is not.
