### ISSUE TITLE
[0.9.2 staging-1896] Player tooltip broken if player becomes non-resident by deleting Deed.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19978]
Step to reproduce:
- start a new server, have a good player tooltip:
![image](https://user-images.githubusercontent.com/45708377/104182137-09ccc200-5421-11eb-8d81-09ebdcf784ac.png)
- place campsite (you become a resident), delete deed with Ctrl+LMB with Land Claim Stake. Tooltip will broken:
![image](https://user-images.githubusercontent.com/45708377/104182258-40a2d800-5421-11eb-90aa-1c54978f617a.png)
- if you become a resident another time tooltip will be fixed again. But if you was resident 1 time and then you become non-resident then tooltip will be broken.

**Comment by abaza121** [comment]
This is fixed on Develop (Update 9.3)
