### ISSUE TITLE
Invalid Contract Termination Crash Server

### ISSUE THREAD

**Issue by salix-d** [StrangeLoopGames/EcoIssues#19972]
##Steps to reproduce bug :

- Make a contract with a 'gain permission clause', set it to a tiny stockpile for the duration of contract.
- During the contract, the person who made the contract removes the stockpile (this was done to bring it closer to where we were digging).
- When contract is done, mark as finish OR wait until time is elapsed and mark as failed. Both make the server crash, the second option gave me a crash report, the first one didn't.

##Expected Behavior :
Concluded the contract as expected OR since it could have been removed by the contracter, mark the contract as failed. Alternatively, maybe preventing storage included in a clause to be removed could be great to avoid these incident.

##Actual behavior : 
Server crashed.
[ServerCrash_InvalidContract.txt](https://github.com/StrangeLoopGames/EcoSuggestions/files/5774210/ServerCrash_InvalidContract.txt)

_Saw issue 19896 was similar, but I guess making vehicles non removable would be an issue since they an fall in ocean and such._

**Comment by D3nnis3n** [comment]
Moved to Issues from Suggestions.

**Comment by SlayksWood** [comment]
@salix-d Thank you for the report. Possibly fixed in 0.9.2.
Need to check this one with #19977, after merging this PR https://github.com/StrangeLoopGames/Eco/pull/7547
