### ISSUE TITLE
[0.9.2 staging-1896] Reset object draft name if you cancel renaiming.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19976]
Step to reproduce:
- start to rename any object, enter new name
- cancel renaiming.
- start to rename it another time. You will see new name instead of old one.
![2021 01 11 Renaiming](https://user-images.githubusercontent.com/45708377/104159562-9ca93480-5400-11eb-86e7-668bc1d8d795.gif)
When I click edit button it should be 'Name' instead of 'Another'

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop 175


Resolution: Fixed and closing.
