### ISSUE TITLE
Fix side notifications

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19971]
![image](https://user-images.githubusercontent.com/3536496/104150010-45b64780-538d-11eb-972b-ac756948a762.png)
- Each icon one should appear only when it contains something.  
- Each icon should have an entry for how many are contained in it
- When an icon appears/disappears, it should slide in/out from the side
- Add tooltips describing each 
- The election one at the bottom is extra weird, it has a built in circle and is a different size. Remove the circle and make it the same size.  Get the icon changed to be a ballot.
- They should behave like proper UI buttons, highlighting and a sound when you mouse over, using the same prefabs as everything else. 
- They should be visibly toggled.
- Add more polish than I have listed here. Make it a shiny diamond of a UI. 💎 

Post a video to the PR.

**Comment by TwixterZ** [comment]
checked in 9.4 Develop 242
