### ISSUE TITLE
small wooden cart seems to allow over stacks of items

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#1998]
#1992

then crashes when something tries to access it (using a tool or work bench)

Staging Alpha 6.0.0 #E34aa2e5

![capture](https://user-images.githubusercontent.com/30765409/29746273-34f1992c-8b18-11e7-8ea2-a6ff1102afc7.PNG)

**Comment by metachronism** [comment]
fixed
