### ISSUE TITLE
[0.9.2.0 beta staging-1897]Sign draw distance inconsistent

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19987]
Need to review all signs to make sure they are all having the same distance rendering as it is a mix between where some of them fades out before others by quite a distance.

This should also not be a factor of size but a factor of type of item, so even if some signs are half the size they should still render in at the same distance regardless as it is a very bad inconsistent behavior right now.

The red boxes contains 2 of the older signs that are dropping out way before the newest editions.

![Screenshot_18.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ebfa2ecd-291c-4299-809c-8418782fe14b)

**Comment by Sekor2600** [comment]
fixed culled System for Objects in svn staging

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Staging-1910

Issue: All signs fade out and in equally now. Appears to be fixed.

Video:
https://images.zenhubusercontent.com/47210472/78f9ae4b-c583-4d4d-bd3a-a1eb3f579ee2/2021_01_24_01_06_trim.mp4

Resolution: Closing
