### ISSUE TITLE
[0.9.2.0 beta staging-1897]Signs with icons oversizing not respecting borders.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19986]
A lot of the new signs limitations are not respected by icon usage and needs to be fixed so the icon doesnt fit inside them but expand way bigger and it looks very bad.

As a lot of players used signs with icons to advertise stores and such this should be considered a important user QoL fix

![Screenshot_16.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/5a78cf48-d260-4f81-b90d-59e3606ab1eb)

![Screenshot_15.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b5b4b185-38fb-40a9-8c0d-f668bffa43c2)

![Screenshot_14.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/562a8f43-17bb-4f89-8557-8425f801638a)

**Comment by Sekor2600** [comment]
Signs are updated in SVN Staging

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Stating-1910

Issue: Still happening for some sign. Mostly the **Lumber Sign**. It also depends on the icon to be displayed.

Screenshot:
![exceed border.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/700de296-b4bc-4b1f-9490-eedaa0c91769)

Video:
https://images.zenhubusercontent.com/47210472/a5124720-9e9c-480c-9198-749b70087f77/2021_01_24_01_19.mp4

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Release-141

Issue: Still happening.

Screenshot
![Untitled.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/cb30ccef-8656-4b6e-b5f0-9435599bb5cc)

**Comment by Sekor2600** [comment]
should be fixed in next build
updated in svn 24.01
but 141 build is from 23.

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Release-143.


Issue: Issue appears to be fixed. Tested on various signs including lumber, ashlar, mortared, steel, and glass.

Screenshot of Lumber Sign
![Lumber Sign.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c92964b4-7535-498a-a050-d115a2ac823d)

Resolution: Closing
