### ISSUE TITLE
Minimap is being cluttered up with icon names

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19982]
![image](https://user-images.githubusercontent.com/3536496/104248541-8f9b3e00-541e-11eb-9246-afe49d580fc4.png)
Why are these here?

**Comment by johnkslg** [comment]
These are names of minimap markers.  Probably dont want these visible in the minimap, but perhaps optionally in the full size map.  Figure out a solution that satisfies all needs and makes it feel very polished. 💎

**Comment by ptitducanh** [comment]
Some polish for this task.
https://images.zenhubusercontent.com/47210472/a42079e8-188b-4219-8866-328d6ce67ad7/new_minimap.mov

**Comment by TwixterZ** [comment]
https://images.zenhubusercontent.com/47210472/ae073002-548d-4a60-ba8a-00ab011b9374/905bb6c2361a07079ca3da01b959d79f.mp4

Tested this, while the polished is an improvement, I believe this can be improved further. 

couple of suggestions : 
1 - A hotkey setup to show/hide markers at a press of a button 
   - this should be a simple yet effective fix that gives players options on this matter
2 - Marker on mini-map disappear when player get close to said marker (25 meter range seems reasonable) 
   - This would be a more elegant way of dealing with this, if it is possible.

**Comment by TwixterZ** [comment]
@ptitducanh my idea is, only hide the markers on mini-map once player reach certain range but its still showing on world as per current. this is to reduce clutter on packed area like cities and towns.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Develop 297

Default shortcut key "=" 

![hiding.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ea9c83d4-2256-4c45-80cf-2ba1a1ff3606)
