### ISSUE TITLE
Something disabling tooltips on 'wages'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19981]
Open government viewer in action bar -> population -> click 'everyone', mouse over wages:
![image](https://user-images.githubusercontent.com/3536496/104247827-53b3a900-541d-11eb-9f77-ba48b8d97de5.png)

It doesnt show a tooltip. It has a component for it, but something disables it along the way:
![image](https://user-images.githubusercontent.com/3536496/104247777-41396f80-541d-11eb-8b37-30c0ccfc7682.png)

Figure out whats disabling it and why, then fix

**Comment by SlayksWood** [comment]
I guess it happens in develop:
![image](https://user-images.githubusercontent.com/45708377/104287049-f411d800-54c6-11eb-8764-b77b774923c1.png)
But I don't have wages tooltip when try to create a Demographic:
![image](https://user-images.githubusercontent.com/45708377/104287109-09870200-54c7-11eb-991f-a81217dacc83.png)

**Comment by abaza121** [comment]
This happens on pooled instances because it gets disabled due to no descriptions but then not re-enabled.
