### ISSUE TITLE
USER ISSUE: connection time out

### ISSUE THREAD

**Issue by RamisL** [StrangeLoopGames/EcoIssues#19991]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
join friend wolrd cant because time out

**Expected behavior:**
join the wolrd

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Échec de la connexion - Délais dépassé (timed out).
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@RamisL Thank you for reporting
If you can, ask your friend for the server ID (not IP) and use it for direct connection if you are trying to connect via steam.
The server host can find this by typing /serverui and opening the "network" tab of the interface there is currently some technical difficulties with steam friend joining. Let me know if this resolves your issue.

**Comment by RamisL** [comment]
we have no more problem to connect
