### ISSUE TITLE
[0.9.2 staging-1897] Last message in top notifications cutting off again.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19997]
I think this happens due to this strange spaces:
![image](https://user-images.githubusercontent.com/45708377/104428194-3bff3080-5595-11eb-994e-ee4f03a76253.png)

Step to reproduce:
- connect to server, all's right:
![image](https://user-images.githubusercontent.com/45708377/104428512-a2844e80-5595-11eb-9b54-2cbe4683b1eb.png)
- make different actions until you will have this strange spaces:
![image](https://user-images.githubusercontent.com/45708377/104428801-f1ca7f00-5595-11eb-9732-517fc8042ba0.png)

**Comment by abaza121** [comment]
this issue seems to happen with /civics winelection mostly due to the added line for civics updates.
