### ISSUE TITLE
Chat Data should be saved in multiple files

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#19990]
Currently ChatManager's ChatData saved in single file. It leads to high memory allocations, slow saves and high LOH defragmentation. Every time when new chat message added to ChatData it marks whole chat data as dirty and initiates serialization which in turn produced zip file entry. For long living servers (especially with non optimized system messages storing) it growth to 1 GB and more. It especially makes no sense, because ChatData always appended and we don't need to re-save old messages every time.

To avoid this we should make ChatData partitioning. It may be based on date or on size. Date approach seems better and simplifies old chat history clearing.

**Comment by IcedForge** [comment]
Could have it set to per days via setting in config and run it on server time?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/116849260-1b67ee80-abf7-11eb-9031-1f537cf3f426.png)
