### ISSUE TITLE
[0.9.2 staging-1897] Exception in tooltip with Wages

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19995]
Step to reproduce:
- start to create elected title:
![image](https://user-images.githubusercontent.com/45708377/104424415-64386080-5590-11eb-9384-e59ac794716c.png)
- don't change anything, vote for it. Check tooltip:
![image](https://user-images.githubusercontent.com/45708377/104424489-816d2f00-5590-11eb-9699-b156cc20d961.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5807341/Player.log)

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Stating-1901

Issue: This appears to be fixed. However, the text displayed now shows a period at the end of the word while the rest doesn't.

Resolution: Closing this ticket but created a new one for the inconsistent test display. Ticket -> #20038

Screenshot
![Active Tooltip Display.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/84fad411-b163-482b-8b5c-5771bcd08e05)
