### ISSUE TITLE
World marker not visible

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20004]
![image](https://user-images.githubusercontent.com/3536496/104496040-4d443f00-558d-11eb-9195-f14903cfca69.png)
you can see theres a marker called 'boards project' here, but its not showing in the world.

**Comment by SlayksWood** [comment]
This marker is an icon on the table. After discussion in the Вiscord, it was decided to add a new feature for markers, which will reduce spam on the minimap, so I close this one and open another issue #20058
