### ISSUE TITLE
[0.9.2 staging-1898] Some Skid steer controls are broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20008]
Skid steer should use this controls:
![image](https://user-images.githubusercontent.com/45708377/104554051-b17a0800-564c-11eb-9ccc-5e9b693f4a70.png)
but they don't work now. I can't rotate skid steer scoop at all. Skid Steer Arm use 'Vehicle Scoop rotate' instead of 'Vehicle Swing Arm Down/Up'

**Comment by Daniel-Magulado** [comment]
Build 0.9.2 Staging-1902

Issue: The changes on the default key settings for the **Vehicle Swing Arm Down/Up** appears to fix the issue. There isn't seem to be anything special when controlling the **Skid Steer Scoop Rotate**. By default, there's no key set for **Skid Steer Scoop Rotate** for this build but binding a key doesn't appear to have any sort of benefit other than aesthetics. It also doesn't alter the functionality of the **Skid Steer**.

Resolution: Closing.

![Skid Steer Control.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c723ba87-4b4f-449c-8397-8a3f351670c7)
