### ISSUE TITLE
USER ISSUE: Launched to space

### ISSUE THREAD

**Issue by marcianito999** [StrangeLoopGames/EcoIssues#20006]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
I was mining in a quarry.
I was on top of a rock and then use the stone pickaxes. I had a lots of rocks to recollect and I was on top of them.

**Expected behavior:**
stay on top of the rocks.

**Actual behavior:**
Launched to space.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by marcianito999** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5812066/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5812067/Player-prev.log)

**Comment by SlayksWood** [comment]
@marcianito999 Thank you for the report.
This issue is fixed for 9.2 please refer to a server admin to help teleport you.
