### ISSUE TITLE
[0.9.2.0 beta staging-1897]Industrial Elevator doesnt work with call post if spawned via test command

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20002]
New elevator wont operate with the call post if you spawn it via /test Industrialelevator  the callpost doesnt detect any nearby elevators.

**Comment by StallEF** [comment]
in [0.9.2.0 beta staging-1895] call post work with Industrial Elevato from /test Industrialelevator

**Comment by SlayksWood** [comment]
I guess it doesn't work with the same reason #20158
Need to check it after fixing this one #20158

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Release - 189.

Appears to be working now.
Call post works on all sides of the industrial elevator spawned via /test industrialelevator.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/828b7ea3-3462-4343-a057-e90ba04b9f82)

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/056fffab-89e5-4087-80f0-4f33675578af)

Closing.
