### ISSUE TITLE
[0.9.2.0 beta staging-1897]Industrial Elevator missing block interaction pickup on superstructure

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20001]
Inside this red zone is the only detection for hammer tool usage to pick up the elevator if it is in lowered state.

Another issue is that it is only detecting on the red part and the cage if it is in the lowered state trying to mouse over any of the general blue superstructure and it will not allow me to interact and pick it up.
![Screenshot_40.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c3ecf8e2-7ecf-4784-9c00-b5e44d3b5aa1)

As you can see im mousing over brick, not the elevator. I do get elevator detection if i mouse inside the red triangular area but anywhere else it just as if its not there.

![Screenshot_41.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/70b1d305-1fe1-4796-a41c-36b70196ba49)

**Comment by Sekor2600** [comment]
fixed in staging svn
