### ISSUE TITLE
Can't run for election

### ISSUE THREAD

**Issue by Manda1491** [StrangeLoopGames/EcoIssues#20007]
Tried to run for an election with the title we made and it kept booting us. There are no mods on this server. 

Please let me know what is wrong. We can't use treasury without someone having a title.

[06:29:35.725] Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: FileNotFoundException
Message:
Source:Eco.Gameplay

System.IO.FileNotFoundException: 
File name: 'NetFabric.Hyperlinq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Gameplay.Civics.CivicActionFuncs.GetConstitutionActionResult(User user, CivicAction action)
   at Eco.Gameplay.Civics.CivicActionFuncs.TryExecuteAction(User user, CivicAction action)
   at Eco.Gameplay.Civics.CivicActionFuncs.FullExecute(User user, CivicAction action, Boolean force, Boolean notify, Election forceAttachToElection)
   at Eco.Gameplay.Components.PerformCivicActionComponent.<>c__DisplayClass11_0.<Select>b__0(IController obj)
   at Eco.Gameplay.Systems.ViewEditor.Apply(Player player)

Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, Boolean)
Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass59_0:<Initialize>b__0()
System.Threading.ThreadStart:Invoke()
System.Action`1:Invoke(T)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadStart:Invoke()

**Comment by IcedForge** [comment]
@Manda1491 Thank you for reporting.
Could you provide some more details ( preferably some images on title names, conditions / permissions and such ) 
As well as what localization you are using (eng, rus, ger etc?) 

Is this happening as you click vote on the website? Or when you try to click vote ingame ?
And please upload the server & user logs directly.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
