### ISSUE TITLE
Changing from windowed to fullscreen with alt enter leaves black bars

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2000]
Staging Alpha 6.0.0 #E34aa2e5

![capture](https://user-images.githubusercontent.com/30765409/29746478-285432ae-8b1f-11e7-8249-d97203e0aebb.PNG)

I changed the size of the window to squish it (around half normal size)
than hit alt enter (toggle fullscreen)

and this is what came out o.O

![capture2](https://user-images.githubusercontent.com/30765409/29746481-2d0e9e10-8b1f-11e7-9cb9-2e7c380c9716.PNG)

**Comment by metachronism** [comment]
more graphics config things to worry about

**Comment by Nanders** [comment]
Fixed
