### ISSUE TITLE
[0.9.2 Staging-1898] Unable to close "Government" window.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20018]
Build: 9.2 Staging 1898

Issue: The Government windows become persistent after pressing the government hotkey "L" in quick succession. I am unable to close the government window even after clicking X multiple times.

Similar Issue: https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/19704

Repro Steps:
1. Log in to the game as usual.
2. Once inside any world, press "**L**" in quick succession. (Government Overview Window Hotkey)

Result: Multiple government windows will pop up but you will not be able to close one or two of them depending on how fast and how many times you pressed **L**.

Video Repro
https://images.zenhubusercontent.com/42199084/1e0bbb8a-4270-4db2-a7ff-c088a2cee454/pressing_l_in_quick_succession.mp4

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/7682
