### ISSUE TITLE
Can't remove wooden doors with the hammer

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2001]
Staging Alpha 6.0.0 #E34aa2e5

Related to #2012 

![image](https://user-images.githubusercontent.com/30765409/29746658-23463b8a-8b25-11e7-9e1f-220189746021.png)

**Comment by MarjieAVolk** [comment]
Alright, looks like when you hammer the door, it opens/closes instead

**Comment by MarjieAVolk** [comment]
Will be fixed in next build

**Comment by EmuLegs** [comment]
Thankyou ^_^
