### ISSUE TITLE
[0.9.2 Staging 1898] Players can submit and post an "Add/Remove Blocks" contract without any blocks selected.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20016]
Build: 9.2 Staging 1898
Issue: I can successfully post an "Add/Remove Blocks" contract despite having no items specified for blocks on the property clause.
Repro:
1. Log in to the game as usual.
2. Interact with a **Contract Board**. (Or get one using /give command)
3. Create a contract and change the first clause to **Add/Remove Blocks**.
4. Select a property and then click the ![plus add block.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8d4632a1-4960-4de6-b9be-274d5413756f) art display on blocks.
5. On the **CHOOSE BLOCKS TO ADD/REMOVE** Window, do not select any block and click **Submit**.
6. Then click **Post**.

### Video Repro
https://images.zenhubusercontent.com/47210472/93e79e86-aad3-4db8-9fde-4227bdb4678b/add_remove_contract_submission.mp4

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 277

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/658d3076-7db5-4759-973c-205693d14cfc)
