### ISSUE TITLE
[0.9.2.0 beta staging-1898]tables missing mouse over tooltip interactions

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20014]
The all tables are all missing mouse over tooltip interactions except the small wooden table.

This is what is going on.
![Screenshot_64.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/7ec8f85b-0477-4dbd-97d3-15e606c3a5ab)

vs what should be happening 
unless this is a behavior we want, but then we need it consistent either way.
But i feel that having mouse over tooltips on all items is more of a expected behavior as this is what happens on every other item ingame.
![Screenshot_67.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/94726794-1d63-4199-834c-1db6cdf2edfb)

**Comment by Moritur** [comment]
Fixed in SVN revision 7926, no code changes

**Comment by Daniel-Magulado** [comment]
Fixed on 0.9.4 Develop-195

Closing.![table tooltip.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/0442577e-2416-4d1b-b5dc-5f89497e4b5b)
