### ISSUE TITLE
[0.9.2.0 beta staging-1898] Industrial Elevator goes down on all buttons.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20026]
Industrial elevator moves downward on both Up/Down button If you have more then 2 vehicles on the platform, regardless of vehicle types.

https://i.gyazo.com/a2b1852c28669edd38cade9672524576.mp4

**Comment by Daniel-Magulado** [comment]
Build: [0.9.2 Staging-1907]

Issue: The original issue of this ticket is that the industrial elevator goes down after pressing the **up button** when there are more than 2 vehicles present inside the elevator's platform. Actually, the issue occurs when there's more than one. The fix seems to work for up to 3 vehicles only. However, when there are 4 vehicles on the platform, the issue still occurs.

Repro:
1. Log in to the game as usual.
2. Place or drive 4 vehicles inside the industrial elevator platform.
3. If the industrial elevator is at the top level, go down a little bit and try to go up.
4. If the industrial elevator is at the bottom level, try to go up.
5. Observe.

Video Repro:
https://images.zenhubusercontent.com/47210472/bb5eb0a1-395c-4bda-a3cc-957130801641/industrial_elevator_with_4_vehicles.mp4
