### ISSUE TITLE
Mask is off on minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20022]
![image](https://user-images.githubusercontent.com/3536496/104663801-9fb35780-5682-11eb-8d74-334408126088.png)
Can see the blue peeking out the left side.

**Comment by IcedForge** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/24981362/104952498-e677b900-59c4-11eb-8288-618ca8b4aaa4.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1981

Resolution: Appears to be fixed on the staging build. The mini global map is not exceeding its borders anymore.
