### ISSUE TITLE
Hidden background gui blocking clicks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20029]
If you mouse over in the X area here:
![image](https://user-images.githubusercontent.com/3536496/104762777-c375ac80-5719-11eb-9ab9-cd671f138e20.png)

The cursor will turn clickable.  Its also blocking clicks to other UIs.  
I looked in the scene and found this is the object catching it:
![image](https://user-images.githubusercontent.com/3536496/104762844-e1431180-5719-11eb-89d5-b80b085ef12f.png)

It seems to not have the chat errors disabled when theyre not visible. This is supposed to happen automatically when they fade out.

**Comment by johnkslg** [comment]
Also, when the infobox is up theres some weird behavior:
![image](https://user-images.githubusercontent.com/3536496/104764388-3122d800-571c-11eb-9d2e-33bf76f711db.png)

Here if I clicked directly on the infobox, it would close. But there seemed to be an area around the infobox that was eating clicks. I couldnt click the button here until the infobox went away.

**Comment by johnkslg** [comment]
Further more: pressing escape when an infobox is up should close it, but it was not. It was closing the GUI behind it.

**Comment by SlayksWood** [comment]
Only in develop
