### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by McMeggs** [StrangeLoopGames/EcoIssues#20020]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**

**Expected behavior:**
I was mining	

**Actual behavior:**
I was send to space

**Do you have mods installed? Does the issue happen when no mods are installed?:**
don`t think so

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@McMeggs Thank you for the report.
This issue is fixed for 9.2.0, please refer to a server admin to help teleport you.
