### ISSUE TITLE
One of these professions is not like the other

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20032]
![image](https://user-images.githubusercontent.com/3536496/104776096-5caebe00-572e-11eb-8d94-7599d3b58268.png)

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/19335

**Comment by StallEF** [comment]
and professions icons have very poor picture quality now, if use it on signs
![2020-12-21 (5)](https://user-images.githubusercontent.com/26339332/104806359-ef5f6380-57e7-11eb-9a33-655225bbc794.png)
![2020-12-21 (12)](https://user-images.githubusercontent.com/26339332/104806371-056d2400-57e8-11eb-9426-9092127fba4e.png)

**Comment by serpopov** [comment]
fixed via SVN

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Staging-1910

Issue: The odd one icon displayed inside the With Labor Profession window appears to fixed. The **Survivalist Profession** was also removed.

Screenshot:
![fixed 1.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/292ba4f4-c8f2-4240-b27c-c8122bd2875e)
