### ISSUE TITLE
offcenter tutorial icon 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20031]
![image](https://user-images.githubusercontent.com/3536496/104772911-1440d180-5729-11eb-8859-8630ca5b439c.png)

**Comment by SlayksWood** [comment]
0.9.2 staing-1902

**Comment by Moritur** [comment]
Can't reproduce, icon seems to be centered like on screenshot by @SlayksWood and not off center like on screenshot by @johnkslg.

![image](https://user-images.githubusercontent.com/44618240/106610968-ad644a80-6567-11eb-87b6-40ad671ac865.png)

Is this bug already fixed or needs some more specific steps to reproduce?
