### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Solkongen** [StrangeLoopGames/EcoIssues#20049]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation was canceled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StallEF** [comment]
similar problem
![error](https://user-images.githubusercontent.com/26339332/104878436-02e80700-596d-11eb-8dc7-14bd5068b60b.png)

fixed by server restart
