### ISSUE TITLE
[0.9.2.0 beta staging-1901] Vehicles teleport vertically on each block update 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20042]
Vehicles teleport when you have a block update happen inside its radius and this is very frustrating.

https://i.gyazo.com/aa111a53d6c06fc66b289a6ee698d77c.mp4

Get a cart, try dig block next to it ( or craft table outputs / takes material ) and vehicle will "reset" each update.

**Comment by Daniel-Magulado** [comment]
Additional Info: Also happening on a drivable vehicle such as the Skid Steer.

Build: 0.9.2 Staging-1902

Issue: The vehicle Skid Steer teleports vertically when removing blocks by means of the vehicle. However, the Skid Steer must be on an inclined plane for the issue to happen.

Repro:
1. Log in to the game as usual.
2. Create a road or drivable plane/road/platform that's inclined.
![Inclined platform road.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/74dbf791-836d-4885-9e89-1e4235d8fa6e)
3. Drive a Skid Steer and try to remove blocks using the vehicle while the vehicle is on the inclined platform/road/plane.
4. Observe.

Result: Skid Steer teleports vertically every block update while the vehicle is on an inclined platform.

Video Repro:
https://images.zenhubusercontent.com/42199084/13c22893-a701-4061-a82f-f55b71d07fdb/2021_01_19_18_16.mp4

**Comment by mirasrael** [comment]
It is important that you should move cart before terrain changes to be able to reproduce. If just put cart on the ground then everything is fine.
