### ISSUE TITLE
Removing Debris with an Axe Does not lower calories used even if you are lvl 5 #e34aa2e5

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2005]
After chopping down a tree, removing the Debris does not decrease in calories even if you are llevel 5 in logging, or even level 5 in logging Efficiency, so as far as i can see nobody will EVER remove them, and that defeats the objective in ECO to try and keep the land free of pollution as much as possible

**Comment by MarjieAVolk** [comment]
I saw AxeItem had Logging instead of LoggingEfficiency for it's calorie skill.  So that should be changed.  But also, the autogen subclasses of AxeItem (StoneAxeItem, etc) are re-overriding CaloriesBurn and resetting it back to Laborer

**Comment by Conchipedia** [comment]
so we can actually get a bonus to remove the debris if we increase Logging? (was hoping this was so, so that people can specialise in like a debris cleaning skill)

**Comment by MarjieAVolk** [comment]
Right now, Laborer skill is what does it.  We will fix it soon.

**Comment by Conchipedia** [comment]
thankyou
