### ISSUE TITLE
[Web] Need update logo on site

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20050]
![2021-01-17 (1)](https://user-images.githubusercontent.com/26339332/104854569-74499a80-5918-11eb-9a87-43a543da3b32.png)

to 

![logo](https://user-images.githubusercontent.com/26339332/104854577-8b888800-5918-11eb-980c-bc123b4031d0.png)

**Comment by denysaw** [comment]
Fixed on Staging.
