### ISSUE TITLE
[0.9.2 staging-1902] Crash when deleting with "-"

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20053]
I can reproduce in Contracts and WorkParties. Can't reproduce in Laws (because you always have confirm box when delete anything in it). Steps to reproduce:
- start to create workparty:
![image](https://user-images.githubusercontent.com/45708377/104880500-b7375c80-5970-11eb-9695-87332c83cfff.png)
- mouseover payment and press "-" 2 times:
![image](https://user-images.githubusercontent.com/45708377/104880575-d930df00-5970-11eb-98be-8544bb388baf.png)
- when I don;t have any payment I will still have "-" if I will not move mouse, 
![image](https://user-images.githubusercontent.com/45708377/104880670-0da49b00-5971-11eb-9359-067b5e67d6b6.png)
- press it another time. Crash:
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentOutOfRangeException
Message:Specified argument was out of the range of valid values. (Parameter 'index')
Source:System.Collections.Immutable

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.ItemRef(Int32 index)
   at System.Collections.Immutable.ImmutableList`1.get_Item(Int32 index)
   at Eco.Core.Utils.ThreadSafeList`1.GetAt(Int32 index)
   at Eco.Gameplay.Utils.RPCListExtensions.RemoveAt(IHasClientControlledContainers hasContainers, Player player, String listName, Int32 index)
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'index'))</size>
```
[Crast Workparty payment.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5828265/Crast.Workparty.payment.txt)

**Comment by gzatravkin** [comment]
Fixed crash at https://github.com/StrangeLoopGames/Eco/pull/7591
