### ISSUE TITLE
[0.9.2.0 beta staging-1902]Arrows hitting targets have mass flood of NREs for ArrowController

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20056]
1. Get a wooden/recurve/composite bow and arrows
2. Pick any animal target and fire at it.
3. If arrow hits it will cause a large NRE spam in playerlog.

Getting about 20.000 lines of these every time i hit an animal with an arrow.

NullReferenceException: Object reference not set to an instance of an object.
  at ArrowController.TryAttach () [0x00000] in <00000000000000000000000000000000>:0 
  at ArrowController.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by IcedForge** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5828596/Player.log)

**Comment by gzatravkin** [comment]
The problem was actually in re-creating arrows. 
So repro steps are: 
1) Hit some animal.
2) Go away so he will be unloaded from game
3) Find him again

After finding him again arrow will not be initialized correctly and it will cause these exceptions.
