### ISSUE TITLE
[0.9.2.0 beta staging-1901]Wood Cart does not link in chat, WoodCart does though.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20054]
I think Wood cart should properly link in chat it currently does not at the moment and require you to write it as 1 word.

![Screenshot_114.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/67f75bfd-f5dc-4235-913b-102ef9d5da0c)

**Comment by IcedForge** [comment]
Seems to be  a few different combinations that have lost their chat links when its spaced words.
Elk Wellington -> ElkWellington

**Comment by SlayksWood** [comment]
was merged to develop.
Check seeds too:
![image](https://user-images.githubusercontent.com/45708377/109927651-95eabf80-7cd5-11eb-8d0f-bca1a5c84299.png)

**Comment by Moritur** [comment]
@SlayksWood All seeds and spores that are not linked on screenshot seem to link just fine on develop

**Comment by IcedForge** [comment]
This needs to be applied on staging as well @Moritur

**Comment by Moritur** [comment]
> This needs to be applied on staging as well @Moritur

Looks like it was already applied on staging in StrangeLoopGames/Eco@e2fe5a8d0fd6b4735b24495f131055eeaa569d23

**Comment by IcedForge** [comment]
Sweet, yes confirmed working and closing.
