### ISSUE TITLE
[Web] SLG logo error on site

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20052]
![2021-01-17](https://user-images.githubusercontent.com/26339332/104872928-45efad80-5960-11eb-9e47-d895f48b964a.png)

https://www.strangeloopgames.com/wp-content/uploads/2013/06/strangeloop-logo-280w.png
REDIRECTS Error

**Comment by denysaw** [comment]
Fixed on Staging.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107320721-52c07680-6ab2-11eb-97a5-eff4f90ebdc8.png)
