### ISSUE TITLE
9.2 1902 Reinforced Concrete half slope A has a bump

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20069]
Half Slope A for reinforced concrete has a bump compared to Ashlar Slope A

![image](https://user-images.githubusercontent.com/61889138/104966404-b508e880-59d8-11eb-84c3-efd0b135c5e9.png)

**Comment by SlayksWood** [comment]
I guess this is intended behavior. This is not ramp, brick has the same:
![image](https://user-images.githubusercontent.com/45708377/105137471-68223080-5b04-11eb-89eb-75d00021e96b.png)
@keegan-o  isn't it?

**Comment by MishkaFur** [comment]
Corrugated steel it is flat to the surface so just seems to be a bit inconsistent then? also your pic shows the brick texture doesnt line up :D

**Comment by keegan-o** [comment]
Improving the look of various block material slopes is not out of the question but some of them being 'stepped' and others not is indeed intentional.
