### ISSUE TITLE
[0.9.2 staging-1902] Wrong highlight of unauthorized property

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20060]
I always have it:![image](https://user-images.githubusercontent.com/45708377/104916388-0d24f800-59a3-11eb-86a8-b3701d3d5419.png)
I should have just red highlight without hint. Earlier, I can have sometimes it when another player  claim property and you can have it a several second and then it changed or when it changed after moving.

**Comment by SlayksWood** [comment]
I have red highlight, but I still have a hint:
![image](https://user-images.githubusercontent.com/45708377/107745536-8525da00-6d25-11eb-8113-36f77fe43f3a.png)
I reopen it, because I should only have red highlight. This behavior was in 9.1 and earlier.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 259
