### ISSUE TITLE
[0.9.2 staging-1902] Housing value won't update if deed is removed

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#20061]
1. Build a house
2. Claim a deed
3. Place some furniture
4. Become a resident if you are still not a resident and have your nice housing value
![bandicam 2021-01-18 18-20-26-584](https://user-images.githubusercontent.com/27898520/104920993-83812480-59ba-11eb-8bcb-24fa5624d848.jpg)
5. Remove a deed completely
6. See that you are still have a nice housing value though there is no place for you to be a resident
![bandicam 2021-01-18 18-28-19-526](https://user-images.githubusercontent.com/27898520/104921306-f4284100-59ba-11eb-9d41-e374cadb1bb2.jpg)

Can be connected to #19978

**Comment by SlayksWood** [comment]
Still an issue in 9.3:
![image](https://user-images.githubusercontent.com/45708377/107741589-856ea700-6d1e-11eb-9863-23f2b55778cb.png)

**Comment by SlayksWood** [comment]
oh, it was moved to 9.4

**Comment by TwixterZ** [comment]
Tested on 9.4 Develop 248, issue persist as housing value remains despite house is unowned

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/a67cd532-bb55-4de8-8a79-8ee48b23a386)

**Comment by TwixterZ** [comment]
Adding to my comment above, if you reclaim the house and became resident, housing points become nil 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/bf925095-6470-439e-91fd-4727fd44565c)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2022
