### ISSUE TITLE
USER ISSUE: Rocker Box Model Mesh has a fliped face

### ISSUE THREAD

**Issue by relliken** [StrangeLoopGames/EcoIssues#20062]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
where the handle of the rocker box attachs to the box its self you can see thru the mesh while standing on the opposite side the handle is on

**Expected behavior:**
you can see thru the mesh

**Actual behavior:**
you should see the texture on the mesh of the model

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods used

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@relliken Thank you for reporting.
Could you provide a screenshot of the issue as well as your operating system?

**Comment by SlayksWood** [comment]
I guess this is dup of #18513. So closed for now, it fixed in 9.2
