### ISSUE TITLE
[0.9.2.0 beta staging-1902]Civics:District map editing does not save for re edit

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20063]
When you create a district map and fill out districts, tab out or submit changes to save and look at something else to verify etc and you reopen now you need to redraw the entire map again.

Reproduction steps.
1.Draft constitution
2.Place zoning office
3.Edit map by adding some districts anywhere
4.Close map and try to edit and change something, map will now be blank.

**Comment by IcedForge** [comment]
Another issue which should be fixed at the same time and might possibly either be a symptom of the above problem or vice versa.

Connect to server.
open zoning office
draft a map and add a district(or multiple doesnt matter) submit and save to an election and close interface.
Open zoning office again and edit map, make some changes or add new district etc and submit to save changes.
Now edit map a 3rd time and the entire interface breaks down and no districts are saved this now also causes weird problems and you need to reconnect to clear this.

Player log from editing first 2 times produces 0 errors, third edit produces whats in the log now.

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Release-141

Issue: There are a couple of issues here but all are related to editing the map using the **zoning office**.

1. Zoning Office only saves/accepts editing or submission of the district that was automatically generated during the draft.
2. Zoning office won't recognize or save other districts other than the initial district that was generated during the draft.
3. Adding a new district via "**Add New District**" button, the added district/s will not be saved.
4. With the existing issue, players are limited to 3 districts only which corresponds to the number of available drafting spots in the Zoning Office.
5. Player's are unable to edit the color of the district and the name of the district. It always reverts back to the initial color and the name of the district that was automatically generated during the creation of the draft.
6. Submitting a draft with more than 1 district, the added districts will be deleted and the marked area for each district will be gone.

Repro:
1. Proceed to the **Zoning Office**.
2. Interact with the **Zoning Office** table.
3. Proceed to **Draft District Map**.
4. Edit the Color and the name of the initial district.
5. Proceed to mark areas for that district.
6. Add a new district and mark areas for the second district added. Feel free to add more districts. Once done, submit to save the draft.
7. Edit the drafted map by clicking Edit under the Draft District Map.
Result: All the edits and configuration that the player have done are gone. If the draft went to the election and got passed, the results are the same. However, if you create a draft and you simply marked the area of the district generated by creating that draft, it will be saved.

Video Repro:

### Drafting District Map and editing the color/name of the initial district created during draft creation.
https://images.zenhubusercontent.com/47210472/547feaa0-afd5-4165-a50f-1f2c318a50a6/2021_01_27_04_44.mp4



### Drafting District Map with more than 1 district.
https://images.zenhubusercontent.com/47210472/7eba3252-37d2-48aa-90a9-a587429b4dfb/2021_01_27_04_45.mp4



### Drafting District Map with the initial district generated upon creation of the draft.
https://images.zenhubusercontent.com/47210472/bd9e07d6-071e-4261-a2b2-1d057acce1c8/2021_01_27_04_43.mp4

**Comment by Daniel-Magulado** [comment]
Build: 0.9.2 Release-143

Issue: Appears to be fixed.

Resolution: Closing.

Attaching a video recording for reference.

https://user-images.githubusercontent.com/77248866/105958224-494c0d00-60b5-11eb-9e1f-9197073fb728.mp4
