### ISSUE TITLE
Server browser fixes / improvements

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2006]
1) Never hide a favorite entry.  If the favorite is being pinged for a response, show some sort of spinning icon denoting that
2) Even if a favorite is whitelisted, and we are not on the whitelist, still show the favorite in the server listing.  (consider displaying whitelisted servers in a different fashion, instead of silently not showing them)

**Comment by MarjieAVolk** [comment]
You created a different bug earlier for server browser improvements (https://github.com/StrangeLoopGames/EcoIssues/issues/1612) - Gonna merge them
