### ISSUE TITLE
USER ISSUE: Left during lag spike cannot reconnect

### ISSUE THREAD

**Issue by OllieM3** [StrangeLoopGames/EcoIssues#20073]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
There was a huge lag spike in the server and i got kicked and now i cannot rejoin the server. not sure if this is a server issue or just a client side issue. Possibly me leaving during lag spike makes game think im still there?

**Expected behavior:**
It should have let me in the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```
Sometimes pops up as error 301 with similar message.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I have no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
we had troubles with auth servers, should work fine now.
