### ISSUE TITLE
9.2 1902 Map is considerably darker

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20072]
The map in 9.2 seems a fair bit darker/duller colour wise for an unknown (to me) design reason

9.2 1902 map (was also like this in previous 9.2 builds)
![image](https://user-images.githubusercontent.com/61889138/104972468-c1497180-59e9-11eb-90b1-987ddbf6adcb.png)

9.1.9
![image](https://user-images.githubusercontent.com/61889138/104972475-c9091600-59e9-11eb-85d8-fe02491ff212.png)

**Comment by johnkslg** [comment]
probably rendering a null overlay on top

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

Closing as fixed.
