### ISSUE TITLE
[0.9.2 staging-1902] Wrong notification when placing wrong item in storage.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20077]
When we had only Chest and stockpiles it was pretty easy to remember what and where can be stored, but now we add another sorage type - SIlo, and in next releases we will add anothers. So the message when you try to place wrong item type in storage should be clearly. Now:
![image](https://user-images.githubusercontent.com/45708377/105025612-a1a06080-5a5e-11eb-86a1-7730994243c8.png)
This message isn't right. It should be something like:
"This storage can't store this item".

**Comment by TwixterZ** [comment]
Still ongoing in 0.9.3 staging 1945

**Comment by Daniel-Magulado** [comment]
User Report:
![image](https://user-images.githubusercontent.com/77248866/115541374-a11f9c00-a2d1-11eb-9e5b-80efc0d284cd.png)

Blank error message when moving Cotton Boll to Silo.

**Comment by TwixterZ** [comment]
This issue is fixed as of 0.10.0.0 Develop-712
