### ISSUE TITLE
Hopefully this helps

### ISSUE THREAD

**Issue by GJevon** [StrangeLoopGames/EcoIssues#20080]
I am playing on the go a lot on my Mac OS laptop and I can no longer enjoy the game due to crashing. I am submitting information in hopes someone can help give me a solution. I had this same problem on my Windows computer but I was able to adjust the tessellation value with the AMD software and it works fine but on my Mac Powerbook it does not have working AMD software that can adjust the value, so maybe if the tessellation value can be adjusted within the game itself that would provide a solution.
![Screen Shot 2021-01-19 at 10 17 03 AM](https://user-images.githubusercontent.com/47157697/105063387-4dd34e80-5a41-11eb-8cf8-7098f148dda4.png)
[Eco_Crashreport.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5837251/Eco_Crashreport.txt)

**Comment by SlayksWood** [comment]
merged to #20322
