### ISSUE TITLE
Icon system updgrades

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20081]
Upgrade the icon system to be largely automatic.  
- [x] There should be a simple 'update icons' menu option artists can check.
- [x] This option should fully populate all needed icons into the scene, and add descriptions for each
- [x] When updating icons, it should separately highlight missing icons in the scene. These can be in a section above the rest of the icons, with a highlighted background, and a big warning at the top 'X missing icons'.  Re-running 'Update Icons' option should update it.
- [x] Educate artists how to use this.

**Comment by SlayksWood** [comment]
Closed for now. We will report all found problems in a new issue.
