### ISSUE TITLE
USER ISSUE: Car engine sound glitch

### ISSUE THREAD

**Issue by Whitescan** [StrangeLoopGames/EcoIssues#20082]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Sit in a car next to the driver
2. Let the driver stop the car
3. Leave the car

**Expected behavior:**
The sound of the engine should shut down

**Actual behavior:**
You still hear the sound unlimited...

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Noone

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Whitescan Thank you for the report.
fixed in 9.2 with https://github.com/StrangeLoopGames/Eco/pull/7566
