### ISSUE TITLE
[0.9.2 Staging-1907] Steam tractor text display exceeds text box.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20097]
Build: 0.9.2 Staging-1907

Issue: The text display for the steam tractor exceeds its text box area. Not happening on other vehicles.

Repro:
1. Log in to the game as usual.
2. Craft or interact with the **Steam Tractor** vehicle.
3. Interact with the **Steam Tractor's** engine and click on the Text tab.
4. Type in a very long sentence or word.
5. Click **Save** and close the window.
6. Observe.

Video Repro:
https://images.zenhubusercontent.com/42199084/8a77424a-457e-47a3-bcac-29e269254acc/2021_01_20_18_46.mp4

**Comment by Sekor2600** [comment]
fixed in develop svn

**Comment by Daniel-Magulado** [comment]
Build: 0.9.3 Develop 174

Issue: Appears to be fixed.

![Untitled.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/2f1b07b5-8fc0-47ed-8aba-c743a3d8b46d)

Resolution: Closing
