### ISSUE TITLE
Unable to see any public worlds or join friends private world

### ISSUE THREAD

**Issue by batwingssingthis** [StrangeLoopGames/EcoIssues#20095]
Hi I have just installed the game for the first time on windows. I clicked accept to all the prompts to allow the game network access but was not able to see or join any other worlds. I have fully reinstalled and rebooted multiple times (also tried manually deleting the game files in steam apps and user appdata), allowed every iteration of the app in my firewall settings, turned off my firewall and antivirus, and followed some advice online to delete the player files in localow. None of this worked. If I try to join a friend's world using the steam community tab it just takes me to the eco main menu.

Any ideas how to resolve this?

**Comment by SlayksWood** [comment]
@batwingssingthis Thank you for the report. it's known issue #19899, #19598
To solve this problem you can connect to server by ID.
So when your friend start server he can give you ID.
To get ID your friend should use '/serverui' command in chat.
It will have such a window open:
![image](https://user-images.githubusercontent.com/45708377/105158491-12a74d00-5b1f-11eb-9a85-1382c6f4e9a8.png)
Go to Network tab and copy this id:
![image](https://user-images.githubusercontent.com/45708377/105158695-500bda80-5b1f-11eb-8cec-62d1a8efb61c.png)
To connect to his server with ID you should start the game, press 'Your Worlds' and press "+":
![image](https://user-images.githubusercontent.com/45708377/105158835-77fb3e00-5b1f-11eb-9f4f-518476e0881e.png)
Paste ID here and press Join.
The next time you want to connect, you can skip these steps, This server will be in Recent. You can also add it to your favorites.

Did it help to you?

**Comment by D3nnis3n** [comment]
This is about no servers shown at all in the server list and categories. This is very important to investigate why it happens.
We had very few users having this issue in the past, but unrelated to the DNS change yesterday. Some users even without security software cannot see any servers in game.

**Comment by batwingssingthis** [comment]
Thanks for the responses!
@SlayksWood I will try what you suggest when my friend running the server is available again. 
But yes, I am unable to see any server, not just this particular private one. Dennis suggested on the discord that I upload my player logs here. (files attached)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5841738/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5841739/Player-prev.log)

**Comment by batwingssingthis** [comment]
Issue was resolved after switching to another DNS. Thanks to D3nni3n for the help!
