### ISSUE TITLE
(6.0.0 #E34aa2e5) Excavator not working

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#2009]
Excavator can be placed and you get a deed, opening the excavator window allows you to add fuel and shows its owner but there's no name on the back. trouble getting into the drivers seat and some don't allow you to get into the seat at all, none of them move even when fueled.
There's no icon showing how to change between the arm and driving.

**Comment by Stephenw92-git** [comment]
Same result whether its placed on claimed or unclaimed land too

**Comment by SeanAtr0n** [comment]
Just fixed, will be in next build
