### ISSUE TITLE
Server ping spikes for ~45 minutes then returns to normal

### ISSUE THREAD

**Issue by IceWarden** [StrangeLoopGames/EcoIssues#20090]
Been having an issue as of late, where the ECO Server will spike in ping into the 9,000s. I have 2 servers on identical hardware, in identical locations, having the same issues:

Specs - Ryzen 3800x, 128GB RAM, 1Gbps UP/DOWN unlimited, 1TB NVME, Windows Server 2019. 

Myself and my team have done a lot of troubleshooting:
1 - Tried clearing up all the debris such as stumps, rubble etc..
2 - Have tried flying around to see if there was a corrupt chunk
3 - have tested and verified it isn't due to large projects
4 - Verified all system resources are under utilized during the spike (CPU ~10%, RAM ~12%, Netspeeds ~10Mbps, No drive queue so I/O seems unaffected)
5 - Rebooting the server does not fix the issue. 

At a complete loss as to what is causing it and where to look next. 

We did recently get this error with the latest spike:
![image](https://user-images.githubusercontent.com/1186232/105120087-93beff80-5a9f-11eb-9ceb-39c4c4b01bf0.png)

**Comment by IceWarden** [comment]
Other information: This is unchanged between spike and no spike
![image](https://user-images.githubusercontent.com/1186232/105120140-b05b3780-5a9f-11eb-84b8-1fc0836b6635.png)

**Comment by IceWarden** [comment]
https://drive.google.com/file/d/1WkyX7URPP5H_Mbz0Hm5XmtHhJlWV7_s5/view?usp=sharing

Here is our latest backup file.

**Comment by D3nnis3n** [comment]
Raised priority. Assigned John.

**Comment by mirasrael** [comment]
Hi @IceWarden Thanks for report. How often it happens? Do you have any periodic laws other actions?

**Comment by IceWarden** [comment]
> Hi @IceWarden Thanks for report. How often it happens? Do you have any periodic laws or other actions?

I'm trying to get you the info about the laws now. I don't actually play the game just run the servers, so I honestly have no idea. As far as frequency, it went from not happening, to happening every 2-4 hours. As of late, sometimes it will happen back to back. The issue usually lasts about 30-45 minutes. Last night, I enabled "_ParallelWorldObjectTicks_" which looked promising but after ~6 hours the server had the issue again where everyone jumped to 9,000 ping.

**Comment by johnkslg** [comment]
Those view notifications alone would cause the slowdown.  Something related to contracts and inventories it looks like.

**Comment by thetestgame** [comment]
It might be totally unrelated but one the worst of the two servers we have a regular reason for DC/Error from the client relating to PlayerAccountAtEachLevel. I can get more details if you feel its related. Otherwise I can open a different issue.

![image](https://user-images.githubusercontent.com/2001527/105229187-2b1c6500-5b29-11eb-8514-c808df7aba54.png)

**Comment by mirasrael** [comment]
@thetestgame this issue already fixed in 9.2.

**Comment by mirasrael** [comment]
@thetestgame @IceWarden seems we already fixed bunch of issues which may be related to your issue in 9.2 which should be delivered soon to live servers. Not sure if we fully fixed your issue, but anyway it makes sense to test in on newer version. If issue will present after 9.2 release please update the issue and we will continue investigation. In this case we can apply some personal hot-fixes to your server and if needed include them in 9.2.x bugfix release.

**Comment by IceWarden** [comment]
Any idea on 9.2 Release? We just started a fresh vanilla server, 100 players online, day 4 (I believe) no mods, and we got the ping spike again. Only difference is a reboot fixed it this time.

**Comment by IceWarden** [comment]
Server is no longer spiking after 9.2 Release

**Comment by mirasrael** [comment]
Great news! Thanks for feedback!
