### ISSUE TITLE
Reafactor 'PlotPos'

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20102]
Property has become confusing with PlotPos meaning two different things.  Depending where in the code, it can mean:
- The position of the upper-leftmost block of a plot (returned by PlotUtil.NearestPlotPosInWorld)
- The x'th plot over and y'th plot down (returned by PropertyManager.GetDeedPlotPos)

Refactor away PlotPos and make everything query in a regular world pos.  Rename the functions to be 'PlotAtWorldPos' 
Rename members that map positions to plots to make this clear

**Comment by gzatravkin** [comment]
This issue was taked by MazonDel who already started this one
