### ISSUE TITLE
USER ISSUE:   Cant play game

### ISSUE THREAD

**Issue by Cyrenus** [StrangeLoopGames/EcoIssues#20106]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1)Start Game
2)Select server
3)Join game

**Expected behavior:**
Join server, game playable

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User doesn't have any assigned products</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This means you didn't buy the game. Please contact support@strangeloopgames.com for resolution, in case you did.

**Comment by Cyrenus** [comment]
I purchased the game on steam and also reached out to the link you provided already.

**Comment by D3nnis3n** [comment]
You should have recived an answer by now :)
