### ISSUE TITLE
Cannot resend invites

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20107]
![invites](https://user-images.githubusercontent.com/25908592/105323531-86eafa80-5bca-11eb-9530-4d337b31be21.png)

**Comment by denysaw** [comment]
Hotfixed on Prod.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/109265648-ef577800-7817-11eb-9c4f-5645566f234f.png)

**Comment by D3nnis3n** [comment]
Can you confirm you actually got the invite? Otherwise reopen, because all uses I had until now were not received at players end, but they also didnt receie the original one.
