### ISSUE TITLE
USER ISSUE: Unplayable issue 

### ISSUE THREAD

**Issue by Shadow3114** [StrangeLoopGames/EcoIssues#20104]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Shut off your pc mid game.

**Expected behavior:**
allowed you to join the world in the menu when you boot it back up again

**Actual behavior:**
it will literally not boot up the world.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and no. This is not that hard to understand, and im suprised it is still a thing.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hello,
we need logfiles to investigate this issue:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by D3nnis3n** [comment]
What has likely happened is that your savegame corrupted. Please never exit Eco ungracefully, it uses database technology that does not like that.

You can restore a backup by going to /Steam/steamapps/common/Eco/Eco_Data/Server/Storage/Backups and move the latest backup to the Storage folder.
