### ISSUE TITLE
Cannot edit users anymore

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20109]
Trying to set tier, amount or anything else does not save. It shows as bold but even after waiting ten minutes it doesnt really save, so is gone when searching for user again.

Website is fast, so dont see dos as issue.

**Comment by D3nnis3n** [comment]
More info:
This seems to happen for tier and amount when NONE has been set yet. If there is a value already set, i can change it.
I looked at the db and saw products are in their own table and have been adding them manually for now.

**Comment by denysaw** [comment]
@D3nnis3n Please, test. Hotfixed on Prod.

**Comment by D3nnis3n** [comment]
Confirmed fixed.
