### ISSUE TITLE
Linking Steam to SLG is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20108]
Users do neither get tier nor amount. 4 cases today after release of new website.

**Comment by denysaw** [comment]
Could be tested on Prod.

**Comment by D3nnis3n** [comment]
Test failed for some, but not for everyone. Not fixed.

**Comment by denysaw** [comment]
@D3nnis3n PLease, gimme 1 user who passed and 1 user who didn't. And tell if their Steam Eco ownership is somehow differs. Thanx.

**Comment by SlayksWood** [comment]
tested yesterday, it works.

**Comment by D3nnis3n** [comment]
Reopened, as not working for my support clients.
