### ISSUE TITLE
USER ISSUE: Chat window resize issue

### ISSUE THREAD

**Issue by FenrirWolff** [StrangeLoopGames/EcoIssues#20103]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Resize chat window and place in center like in image
![Screenshot 2021-01-20 235424](https://user-images.githubusercontent.com/56287928/105285867-d9042f80-5b7a-11eb-9f7e-433e342f587f.png)

**Expected behavior:**
Able to resize chat window

**Actual behavior:**
Chat window resizing and or moving window is ignored and treated as exiting chat entry when trying to resize or move window in any provided direction and is not interactable by user. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@FenrirWolff Thank you for the report. I can't reproduce it in 0.9.2 release-140. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and maybe any video?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
