### ISSUE TITLE
Purchases don't add products

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20110]

**Comment by denysaw** [comment]
Hotfixed on Prod. @SlayksWood , @D3nnis3n Please, test.

**Comment by D3nnis3n** [comment]
Test failed, not fixed.

**Comment by denysaw** [comment]
Yeah, was similar issue in another table. Please, test again ;)

**Comment by D3nnis3n** [comment]
Seems fixed.
