### ISSUE TITLE
User Crash (Sound related?)

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20111]
[Player (11).log](https://github.com/StrangeLoopGames/EcoIssues/files/5848514/Player.11.log)

**Comment by D3nnis3n** [comment]
User starts game, crashes after few seconds.

**Comment by Quadbro** [comment]
Looks like a driver issue. Can i ask for driver updates? Realtek/nvidia @D3nnis3n

**Comment by D3nnis3n** [comment]
Oh yeah, this has already been fixed.
