### ISSUE TITLE
[0.9.2 release-139] Wrong property highlight when place Starter Camp

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20115]
Step to reproduce:
- select Starteer Camp on Toolbar.
- rotate it on 180 degrees (press Q or R 2 times) and place like here:
![image](https://user-images.githubusercontent.com/45708377/105345605-82880700-5bf5-11eb-83e7-b87f03d1921a.png)
- but when you will place it will  move property to right:
![image](https://user-images.githubusercontent.com/45708377/105345733-a9ded400-5bf5-11eb-97f9-c23243d9d30a.png)
- The problem is that my tiny stockpile is now not on my property and isn't linked to my campsite. The newbie can have problem with it - we don't have tutorial how to link stockpile, someone can steal his stockpile. It also just confuses players.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 277 

https://images.zenhubusercontent.com/47210472/8aa88616-7419-4730-a37d-b80ccfe274d9/0bcddd6369265cfa49d997c3f2f9ad1f.mp4

**Comment by TwixterZ** [comment]
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/532f8637-1021-497f-9c31-79f49ccff02b)
