### ISSUE TITLE
[0.9.2 Release-139] Missing Art Icon For Advanced Crafting Button

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20113]
Build: 0.9.2 Release-139

Issue: The art icon display holder for the Advanced Crafting button is missing. The current art being displayed is a white Wheelbarrow Wheel.

Repro:
1. Log in to the game as usual.
2. Interact with a table that has advanced crafting options. For example, the **Workbench**.
3. Look for a craftable item that has an **Advanced Crafting** button near to its respective **Order** button.
4. Observe.

Screenshot 1
![1.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/3e4f5194-94fc-4eef-9fe4-5db6c2464829)

Screenshot 2
![2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/f648b222-67f0-43be-9429-206136ec4619)

Feedback: If the icon is intended to give an impression of an additional option is available, I recommend having a hammer icon instead for the advance crafting button. Personally, the gear icon gives an impression of in-game options or settings. With a hammer, it gives an idea that there's more crafting option to see.

**Comment by keegan-o** [comment]
Assigning @serpopov and @RobertMangano , I assume this is not something that can be hooked up in eco.unity.

If anyone in the know could confirm the description for this, perhaps @WeaselDog ?

**Comment by IcedForge** [comment]
Need to check in with crafting ui rework and make sure we don't do unintended extra work

**Comment by keegan-o** [comment]
De-assigning until confirmation can come from those doing the crafting rework.

**Comment by WeaselDog** [comment]
@keegan-o Do we have a sprite ready? We can get someone to plug in if so. I don't mind the gear so much myself.
