### ISSUE TITLE
PayPal Purchase Data no longer being added to users after purchase

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20129]
I used to be able to see amount of paypal payment and the payment ID for easy access, this doesnt seem to work anymore, for all recent purchases it shows empty.

**Comment by denysaw** [comment]
Should be fixed now. On Prod.

**Comment by D3nnis3n** [comment]
Issue confirmed fixed, i got my PayPal info back :)
