### ISSUE TITLE
Wrong Icons for Two Pack buyers

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20127]
They get 2packicon, should be getting betaicon and beta2packicon.

**Comment by denysaw** [comment]
Fixed (staging + prod)

**Comment by Daniel-Magulado** [comment]
Viewed on live ECO page https://play.eco/buy.
Two Pack now uses the following asset
[/assets/images/icons/beta2packicon.png](https://play.eco/assets/images/icons/beta2packicon.png)

Closing.
