### ISSUE TITLE
USER ISSUE: launch into space

### ISSUE THREAD

**Issue by Assassin31** [StrangeLoopGames/EcoIssues#20126]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. stand on a rock
2. break the rock

**Expected behavior:**
broken the block

**Actual behavior:**
launched me above the height limit and now im stuck

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Use /unstuck in chat. If that doesn't work and you're admin you can use /fly to get off or ask an admin to teleport you :)
