### ISSUE TITLE
Activating Invites does not add products

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20128]

**Comment by denysaw** [comment]
Fixed. Proof:
![image](https://user-images.githubusercontent.com/5720101/105555158-15659600-5d09-11eb-9fc9-19e54c16fda4.png)

![image](https://user-images.githubusercontent.com/5720101/105555192-26aea280-5d09-11eb-970e-ac9d75d691b6.png)

**Comment by D3nnis3n** [comment]
Seems fixed.
