### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by wheeze22** [StrangeLoopGames/EcoIssues#20123]
I am having an issue where I go to open my map and half the planet isnt loading, I have tried different video settings and nothing, I dont know what gives.

**Comment by D3nnis3n** [comment]
Can you add a few screenshots, your PC specs and your client logs?

https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by SlayksWood** [comment]
@wheeze22 We also need the size of the world you are playing on and the tessellation level of your video card.

**Comment by wheeze22** [comment]
My GPU is AMD Radeon RX 5700 XT my processor is AMD Ryzen 7 3700X 8-Core at 16 GB or ram.
I sadly cant find my client logs but will see what I can do.
And here is the issue in screenshot format

![20210122103425_1](https://user-images.githubusercontent.com/77816984/105512189-cbe06100-5c9e-11eb-9134-7dc5ea53aeaa.jpg)

**Comment by wheeze22** [comment]
> I am having an issue where I go to open my map and half the planet isnt loading, I have tried different video settings and nothing, I dont know what gives.

My GPU is AMD Radeon RX 5700 XT my processor is AMD Ryzen 7 3700X 8-Core at 16 GB or ram.
I sadly cant find my client logs but will see what I can do.
And here is the issue in screenshot format

![20210122103425_1](https://user-images.githubusercontent.com/77816984/105512189-cbe06100-5c9e-11eb-9134-7dc5ea53aeaa.jpg)

**Comment by wheeze22** [comment]
> @wheeze22 We also need the size of the world you are playing on and the tessellation level of your video card.

Please view the newly updated info, thank you

**Comment by D3nnis3n** [comment]
That information is not included.

We unfortunately need the logs, world size and tesselation level of your video card to go on with this issue.

**Comment by wheeze22** [comment]
> That information is not included.
> 
> We unfortunately need the logs, world size and tesselation level of your video card to go on with this issue.

Let me give you another point, it is only when I go online, playing on other servers, I sadly dont have the logs in turn, the world size I have no Idea how to get that info and my tesselation level of my graphics card is 367

**Comment by D3nnis3n** [comment]
We need the client logs, the link i posted above shows where you can get them - you always have them, it's not the server logs we need. You can find the world size on their web interface where they have the laws as well.

**Comment by wheeze22** [comment]
> We need the client logs, the link i posted above shows where you can get them - you always have them, it's not the server logs we need. You can find the world size on their web interface where they have the laws as well.

I have done everything the article told me to do to find the client logs and I get nothing it boots me straight to the internet
The world size is 1.25km²

**Comment by wheeze22** [comment]
> We need the client logs, the link i posted above shows where you can get them - you always have them, it's not the server logs we need. You can find the world size on their web interface where they have the laws as well.

I need help with the client logs if my game is not installed in my main disk does it change the location of them? I have looked to no avail and still need your help

**Comment by wheeze22** [comment]
> We need the client logs, the link i posted above shows where you can get them - you always have them, it's not the server logs we need. You can find the world size on their web interface where they have the laws as well.

I have found the client logs
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5870550/Player.log.copy.txt)

**Comment by SlayksWood** [comment]
@wheeze22 to check and change your tessilation level you need to install AMD Radeon Software. 
So you need to set 64.
![image](https://user-images.githubusercontent.com/45708377/105813169-7f5b9500-5fc0-11eb-8a3b-b752842fa9b6.png)
But in any case this issue fixed for all tesselation level in 9.2 with #18664. So you can just wait for 9.2 release.
Closed for now.
