### ISSUE TITLE
[0.9.2 Release-140] Form Block UI is Inaccessible if you move hammer (from stockpile) to active cell in toolbar.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20130]
Build: 0.9.2 Release-140

Issue: The third step on **Construction Tutorial**, where the player is asked to press and hold the F key to open the Form Block UI, doesn't work if the player places the hammer, required process on step 2 of the tutorial, in an already active/selected tool cell.

Repro:
1. Log in to the game as usual.
2. Follow tutorials until you reach the **Construction Tutorial**.
3. Finish the first step of the tutorial.
4. While carrying the **Hewn Logs**, proceed to follow the second step of the tutorial.
5. When retrieving the stone hammer from the storage, make sure to place the hammer in an already selected/active tool cell.
6. Observe and try to complete step 3 of the **Construction Tutorial**.

Result: The tutorial is asking me to press and hold F key, however, there aren't any F functions available.

Screenshot
![log.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/31f84108-369f-4877-b92f-611e0355bc08)

Video Repro
https://images.zenhubusercontent.com/42199084/77546843-238c-47e5-a249-534dfdebe466/hammer.mp4

**Comment by SlayksWood** [comment]
This is not Tutorial issue, this is UI glitch, when you don't have interface to chose fill type and form. Third point work fine if you reselect hammer.

**Comment by SlayksWood** [comment]
and You have this UI without hammer if you select hammer with construction blocks in hand and then move hammer to storage.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1928.

Resolution: Appears to be fixed on the said build. It's not happening anymore. Closing.

**Comment by Daniel-Magulado** [comment]
Reopening
Tested on 0.9.3 Staging-1944
The issue is happening again.

Attached video record for repro and result:

https://user-images.githubusercontent.com/77248866/109969074-6d42e400-7d2e-11eb-98e4-19cde51e047f.mp4

Screenshot (Holding Hammer but Missing F on carrying Box)
![hammer](https://user-images.githubusercontent.com/77248866/109969187-906d9380-7d2e-11eb-8a50-b737c7f9650c.jpg)
