### ISSUE TITLE
[0.9.2] Need banner for Ecopedia: Residency

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#20142]
With the new residency page in the Ecopedia, it needs a banner to match the format of the other entries in the Concepts section.

**Comment by RobertMangano** [comment]
banner is done and setup in unity![ecopedia_banner_residency.jpg](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/8a17d500-39db-4939-aa1a-f55a90a274c1)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267.

Residency Entry now has a banner.

Closing.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/7f7ec902-1e3f-4e27-95b3-c706fb439fad)
