### ISSUE TITLE
[0.9.2.0 beta release-141] You can no longer drag and swap same type tool in the Toolbench for repairs

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20149]
When you open the repair ui, and you have several tools possibly of the same type i would drag object into repair slot, repair and then drag the next broken object into the grid to swap the tools to repair while avoiding the drag out of and then drag into again, this is no longer possible if you use a tool of the same class/tier as already occupying the repair slot.

![Screenshot_92](https://user-images.githubusercontent.com/24981362/105630976-3b478380-5e4c-11eb-8ee1-0439fb70e807.jpg)

**Comment by Daniel-Magulado** [comment]
Build: 0.9.3 develop 174

Issue: Appears to be fixed. Able to swap tool of the same class/tier from the repair slot.
