### ISSUE TITLE
USER ISSUE: Resource Rocket

### ISSUE THREAD

**Issue by t2tw13** [StrangeLoopGames/EcoIssues#20147]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Mine rocks directly under feet.
2. Pickup rocks directly under feet.
3. Enjoy planetary orbit.

**Expected behavior:**
Pickup rocks.

**Actual behavior:**
Launched approximately 1500m into space.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed for 9.2.
