### ISSUE TITLE
USER ISSUE: No Main Menu UI

### ISSUE THREAD

**Issue by mikelittman** [StrangeLoopGames/EcoIssues#20154]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Launch Game

**Expected behavior:**
It should have some interface elements.

**Actual behavior:**
Instead it has no interface elements. I am able to hit escape and see my settings but I am unable to launch the server browser.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by being offline. You need to be online to play Eco, e.g. when steam is down it won't work.
