### ISSUE TITLE
(6.0.0 #E34aa2e5) /give command causing disconnect, inactivity

### ISSUE THREAD

**Issue by Stephenw92-git** [StrangeLoopGames/EcoIssues#2015]
tried spawning a pickaxe twice with the same result, not sure if its the item or the command. i have spawned one earlier in the day without any issues and a host of other things. came back online to check a few other things and /give seems to be kicking me atm

**Comment by MarjieAVolk** [comment]
Sounds like you are experiencing network problems with the server, not necessarily related to what you were doing.
