### ISSUE TITLE
[0.9.2 Staging-1910] NotAllowedInInventories text appears when selecting multiple skills across Profession and Specialties

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20153]
Build: 0.9.2 Staging-1910

Issue: When setting conditions under Skill Requirements and selecting multiple skills across the various professions and specialties, the text **NotAllowedInInventories** appears.

Repro:
1. Log in to the game as usual.
2. Interact with either **Government Office**, **Court**, or **Contract Board**.
3. When making **Title**, **Law**, or **Work Parties**, set the **If** condition to **Skill Requirement**s.
4. For Skills, select multiple professions and specialties.
5. Observe.

Result: The **NotAllowedInInventories** text appears which is unnecessary to show.
Expected: The text should just be respectful of the number of professions and specialties selected. For example, **3 Professions/4 Specialties**.
Removing the text and setting it to show **X Skills**, example **4 Skills**, instead is redundant. Since the left box already states the word "Skills."

Screenshot:
![Notallows.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/ce778a5d-4313-4818-a1af-35f867351284)

**Comment by StallEF** [comment]
1) Laws was reported earlier - https://github.com/StrangeLoopGames/EcoIssues/issues/19714
2) Status bar in filter windows is have not localization in all Ui where it used

**Comment by Daniel-Magulado** [comment]
Closing. Updates made on Clickup. https://app.clickup.com/t/10591183/ECO-11909
