### ISSUE TITLE
[0.9.2.0 beta release-141]Work Party: Can not pick left item under Condition requirement.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20150]
Reproduction
Add a crafting object and add a craft to a queue ( campfire for example add any object to start a craft )
spawn a contract board and start a work party
Now enter "prerequisite conditions" in the work party limitations and change the property into Comparison.

Can not open the left option for condition specification, while i can open the right option fine.

![Screenshot_89.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/863a4457-9797-4b22-a1a6-ce237ceff136)

**Comment by serpopov** [comment]
Probably was side bug of another issue, not actual now

**Comment by IcedForge** [comment]
Seems like i keep running into it every now and then but only ever as a side effect / symptom of other ui issues will close this for now.
