### ISSUE TITLE
USER ISSUE: No main menu

### ISSUE THREAD

**Issue by Le-Sten** [StrangeLoopGames/EcoIssues#20155]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
There is no main menu when starting up the game.

**Expected behavior:**
It should have...... a main menu?

**Actual behavior:**
Instead it......doesn't have a main menu.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed and yes, it happens when no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5862914/Player.log)

**Comment by Le-Sten** [comment]
[
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5862916/Player.log)
](url)

**Comment by Le-Sten** [comment]
Same issue than in 2018 : https://steamcommunity.com/app/382310/discussions/0/1699416432407806494/

**Comment by D3nnis3n** [comment]
Caused by being offline. You need to be online to play Eco, e.g. when steam is down it won't work.
