### ISSUE TITLE
USER ISSUE: Research Table Does not have a Module slot

### ISSUE THREAD

**Issue by Summersisle** [StrangeLoopGames/EcoIssues#20167]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Open research table
2. No Module Tab shown
3. Recipes are dynamic values and say they can be reduced

**Expected behavior:**
Should be able to put in an Upgrade Module to reduce the resources required.

**Actual behavior:**
Missing completely

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The research table not having a module slot is intended.
