### ISSUE TITLE
Campsite disappears

### ISSUE THREAD

**Issue by ptitducanh** [StrangeLoopGames/EcoIssues#20168]
Player's campsite disappears. 
There's no steps yet.
![image](https://user-images.githubusercontent.com/8966115/105795370-48d14a80-5fbf-11eb-8f1a-027be39739ea.png)

Player's log
[Player (3).log](https://github.com/StrangeLoopGames/EcoIssues/files/5870978/Player.3.log)
Server's log
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5870979/Logs.zip)

**Comment by SlayksWood** [comment]
@ptitducanh Seems he place it on another world side. (715 near to 720). So he need to cross border one time to see it or reconnect, sometimes it happens near world border, isn't it?

**Comment by SlayksWood** [comment]
#19797

**Comment by SlayksWood** [comment]
merged to #19797 to investigate
