### ISSUE TITLE
World doesn't get removed after subscription ended - new subscription cannot be made

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20174]
User mentioned in Discord cancelled his subscription which was then supposed to expire Jan 13, but he can still use the world.
At the same time he cannot create a new subscription as the button "Subscribe" just leads him to the overview of his worlds, where he still has his world.

**Comment by j3fffff** [comment]
@D3nnis3n which user is this?

**Comment by D3nnis3n** [comment]
That was the user that later had his world go missing as he couldn't pay after the fix and then on another order again had to servers. Afaik that was already fixed.
