### ISSUE TITLE
USER ISSUE: jump

### ISSUE THREAD

**Issue by Skyliespro** [StrangeLoopGames/EcoIssues#20178]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
collapse with stone 

**Expected behavior:**
just contact cant walk

**Actual behavior:**
jump into space can't return into earth

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non and yes i don't have mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Skyliespro Thank you for the report.
This issue is fixed for 9.2.0, please refer to a server admin to help teleport you.
