### ISSUE TITLE
[0.9.3.0 beta develop 167]Curtains needs distingushing features from carpets when in a free placed / stockpile 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20172]
It is a bit confusing with just glancing over a stockpile with which is which, or why things arent stacking ontop of each other.
![Screenshot_10.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/7556e1b8-95df-4291-8cca-c43174587164)

![Screenshot_8.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/cb3a999b-9890-4dad-94b5-d86da2b0434e)

**Comment by keegan-o** [comment]
Fixed in staging for 9.3, and shortly in master.
