### ISSUE TITLE
USER ISSUE: Can't vote

### ISSUE THREAD

**Issue by m-r-Gamez** [StrangeLoopGames/EcoIssues#20176]
![vote_bug](https://user-images.githubusercontent.com/4639977/105839278-8b038780-5fd1-11eb-8fe0-0a8d7b369dbd.jpg)
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Join Sea Otter
2. Get the title of Senator
3. Try to vote in 'Woodalnd Protection Revision Act 2' in Edge or Chrome web browsers

**Expected behavior:**
The vote should be registered

**Actual behavior:**
I get an error and the vote doesn't register

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Server is Sea Otter

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@m-r-Gamez Thank you for the report and sorry fo the waiting. I tried to reproduce you issue a several times and still can't( Did it happen after 0.9.2 release?

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response
