### ISSUE TITLE
Labor Party Miscalculations

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#20197]
Took me a while to figure out what is happening. Labor parties would run out of funs in escrow. What is happening is upon a restart the server removes parts of labor parties that have been completed and paid in full. Therefore when people contribute more it miscalculates their amount of contribution and pays based on the remaining weights. I wish I had screen shots of the party before the restart.

![image](https://user-images.githubusercontent.com/8082068/106081793-87fabb00-60e7-11eb-8c73-77e183685418.png)

**Comment by IcedForge** [comment]
Thank you for reporting. This should be fixed since 9.2 release.
