### ISSUE TITLE
[0.9.2 release-144] Empty second notification when try to unclaim a big property without required inventory space

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20198]
Step to reproduce:
- /give papers,1500:
![image](https://user-images.githubusercontent.com/45708377/106103912-b661b000-6152-11eb-8c4c-a3b40b306dec.png)
- claim a big property with 1500 plots:
![image](https://user-images.githubusercontent.com/45708377/106103967-cda09d80-6152-11eb-9af2-7e99036d5070.png)
- your inventory should have less 15 empty cells now:
![image](https://user-images.githubusercontent.com/45708377/106104115-0c365800-6153-11eb-9a6c-d97871f787f5.png)
- select Land Claim Stake and try to unclaim whole property (Ctrl+LMB), second notification is empty:
![image](https://user-images.githubusercontent.com/45708377/106104234-38ea6f80-6153-11eb-8388-2eeeac8b9743.png)

**Comment by TwixterZ** [comment]
tested in 9.3.0 beta staging-1954, no more second notification window

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c935d803-c62c-45c8-9642-5218e83f1c8d)
