### ISSUE TITLE
[0.9.2 release-144] Claiming/Unclaiming a big property cause a lags

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20199]
Step to reprodce:
- claim 1 plot:
![image](https://user-images.githubusercontent.com/45708377/106104892-1b69d580-6154-11eb-99ca-aad752a4d9fb.png)
- use edit mode to claim 1500 plots:
![image](https://user-images.githubusercontent.com/45708377/106104911-27559780-6154-11eb-93ef-81010c54b378.png)
- press submit, you will have disconect icon. At least I have. My CPU load (ECO Server) goes up from 1% to 25-30% and I guess this is cause this lag

**Comment by SlayksWood** [comment]
Seems this is regression. Because a lot of players complain.

**Comment by SlayksWood** [comment]
Testing with 2500 plots:
It fixed when I claim plots - I don't have disconnect icon, CPU loaded at 18-19%.
but still an issue when I unclaim big plot - I have disconnect icon, CPU loaded at 25%+

Compare with districts this is too much.

**Comment by SlayksWood** [comment]
I still have a problem with it. I still can have disconnect icon with claiming/unclaiming big property. But I also have lags when I just either claim a new property with 1 plot or unclaim it. It not a long lag but it happen all the time.
So steps to reproduce:
- I claimed 2 big properties with sum plots = 20000+ (This likely be on large servers)
- start claim a new property with stake one by one. I have a small lags every claiming/unclaiming.
video:
https://drive.google.com/file/d/1DDfZg3ucpnAse6moBlI-CXsTIn90jjcB/view?usp=sharing

The same problem with claiming/unclaiming big properties. If I claim 2500 plots in a fresh world I don't have any problem. But If I claim a big property in a world with already claimed 20000 plots I will have disconnect icon.

**Comment by SlayksWood** [comment]
I closed this one #20320, but I guess we still need to improve this system, perhaps we can push it to the next releases.

**Comment by gzatravkin** [comment]
https://github.com/StrangeLoopGames/Eco/pull/8134 - another bunch of improvements. After merging and testing let me know if it's good enough, there is still some stuff to improve.

**Comment by TwixterZ** [comment]
Tested on 9.4 Develop 266

while there is no spike in CPU usage when submitting or editing land claim sizes, game stutters when holding rmb to add or remove land claim area when editing.

**Comment by SlayksWood** [comment]
@TwixterZ I guess this is a problem with editing property, this is another issue #21744. 

But I still have lags when unclaim huge property, and seems the more my PC is loaded the bigger lags. I have a properties with total 5k+ claims. and I tried to unclaim property with 2k+ plots:
https://drive.google.com/file/d/1Y6veb8QrzYbuMtETkKM4o6YBXNC5RtU-/view?usp=sharing
When I don't record video I still have lags but they was less.

**Comment by TwixterZ** [comment]
@SlayksWood as discussed, tried to claim a large plot worth 4k+ resulted on blotched plots with more than 12 different claim zone

![image](https://user-images.githubusercontent.com/78054747/116858643-4b33e800-ac31-11eb-936c-23405a76e533.png)

**Comment by gzatravkin** [comment]
Please confirm if it's fast enough. If so https://github.com/StrangeLoopGames/EcoIssues/issues/21795 probably is unnecesary for now.

**Comment by TwixterZ** [comment]
this fix is tested on 9.4 Staging 2005. claiming 5k plots takes less than a second to complete on a private session.

**Comment by johnwalley340** [comment]
I'm still having lag spikes on the server and the client tends to crash. This is happening with as little as 5 claims being added to an existing plot. This happens both using the stake and via edit mode.
