### ISSUE TITLE
Store trade offers can be in bad states - migration issue?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2019]
The 'bad' offers have stacks with null items, thus they display no icon in the store UI

**Comment by MarjieAVolk** [comment]
The stores on marmot are not displaying, but locally it seems to work fine.

**Comment by MarjieAVolk** [comment]
Okay, this may actually be a migration issue - looks like the state on marmot stores happens to still be bad, but new stores work fine.

Should keep an eye on this if we migrate the pax saves to the new version

**Comment by johnkslg** [comment]
Stores now nuke their contents with 5.6 migration, but we're ok with that....

**Comment by johnkslg** [comment]
Just the tradeoffers, not the storage
