### ISSUE TITLE
[0.9.2 release-143] Large doors placement problem.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20192]
These are most likely 2 issues, but I will combine them since they are related.

- [ ] 1. When you place Large door (Large Windowed Lumber door, Large Lumber Door, Large Corrugated Steel Door) you have closing sound of these doors. Apparently it's worth either removing the sound or placing the doors initially open and closing them.
https://user-images.githubusercontent.com/45708377/105979024-4268ce80-60a4-11eb-9138-98d9a7901bc8.mp4

- [ ] 2. It happens because of the first problem. If, after placing the door, you do not wait for the sound finishing (in fact, the completion of the missing closing animation) and try to open the door, the door will open without animation.
https://user-images.githubusercontent.com/45708377/105979216-73e19a00-60a4-11eb-901f-bed70a9699c9.mp4

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267.

Re-opening. Issue number 1 still persists. Dropping or placing any large door type still plays the SFX for closing a large door. While dropping or placing a door such as a hewn door doesn't play any SFX which is the expected result.


Reopening.

https://images.zenhubusercontent.com/47210472/be866f1c-da3c-4463-af3c-86163e623121/eco_2021_04_27_22_26.mp4

**Comment by madpingui** [comment]
Prefabs of large door updated in SVN fixing audio problem
