### ISSUE TITLE
USER ISSUE: Mining now flying

### ISSUE THREAD

**Issue by BTNGaming** [StrangeLoopGames/EcoIssues#20190]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. Mine under water stone.
2. Collect it quickly.
3. Get thrown into outer space and never come back down.

**Expected behavior:**
Collect stone and continue on your way.	

**Actual behavior:**
Flew me into the sky and i've not seen the planet ever since...

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@BTNGaming Thank you for the report.
This issue is fixed for 9.2.0, please refer to a server admin to help teleport you.
