### ISSUE TITLE
USER ISSUE: Ich wollte aber in die Hölle :(

### ISSUE THREAD

**Issue by Abendschwingen** [StrangeLoopGames/EcoIssues#20191]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
Ich hatte einene Stein abgebaut, wollte ihn aufsammeln, bin jetzt bei Gott im HImmel, ich komme hier nicht mehr raus, und es gibt keinen Respawn, aka. ich kann diese Welt löschen, wenn niemand mir helfen kann und dann werde ich es deinstallieren.

**Expected behavior:**
Ich hätte den Stein aufsammeln dürfen

**Actual behavior:**
Ich wäre nicht zu Gott in den Himmel geflogen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Abendschwingen Thank you for the report.
This issue is fixed in 0.9.2. You can use /fly or /tp command to avoid it. If you don't have permissions then refer to your admin to teleport you.
