### ISSUE TITLE
9.2.0 - Yellow XP Multiplier does not update until a relog

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20205]
Add yourself to a residency, yellow XP multiplier bar does not update until relogging, tooltip is correct though

![image](https://user-images.githubusercontent.com/61889138/106135241-8ec51480-615f-11eb-9404-0c78010fe92b.png)

After a relog
![image](https://user-images.githubusercontent.com/61889138/106135306-a3a1a800-615f-11eb-8512-ad47ae48216d.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 251

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 251
