### ISSUE TITLE
[0.9.2.0 beta release-146] Main menu settings allow you to open settings twice with esc + settings button

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20209]
If you time / interact with the settings button as you are hitting escape to open settings you can manage to open 2x settings screens so you cannot terminate or exit them without restarting the client.

Reproduction
Enter game.
switch between settings and pressing escape on/off and eventually you will get locked with 2x settings screens that the same time.

**Comment by SlayksWood** [comment]
#19704
