### ISSUE TITLE
USER ISSUE: Crafting Hewn Logs

### ISSUE THREAD

**Issue by Pandraigon** [StrangeLoopGames/EcoIssues#20207]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.0 beta release-144

**Steps to Reproduce:**
Crafting Hewn Logs at Workbench or Sawmill

**Expected behavior:**
Select the recipe for Regular Hewn Logs

**Actual behavior:**
Can just craft Softwood Hewn Logs or Hardwood Hewn Logs instead of Regular Hewn Logs

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
