### ISSUE TITLE
SLG Client Login not possible

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20203]
Did we forget to switch staging to production db?
Credentials work in 9.1.9, but not 9.2.0. Many tickets.

**Comment by redwyre** [comment]
There was a check in the build to make this impossible, but it looks like I didn't bring it across in the last jenkins refactor. I'll add the check back in.

**Comment by D3nnis3n** [comment]
Thanks!

**Comment by D3nnis3n** [comment]
Fixed via Hotfix.
