### ISSUE TITLE
[0.9.2.0 beta release-144]Linux server crash on start

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20202]
User report crashing with Debian GNU/Linux 10 (buster)
Potentially mod/config breaking

[eco_error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5886313/eco_error.txt)

**Comment by FonzySF** [comment]
Server V9.2.0 carshed with mods: Nidtoolbox: Cleanserver, playermanager,rules.

**Comment by WeaselDog** [comment]
Let us know if you are still having an issue.

**Comment by TwixterZ** [comment]
Closing this issue as lack of response
