### ISSUE TITLE
EcoAccounts can't fetch latest 9.2.0 game version into DB

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#20206]
That's why users can't choose it or download.
It's cuzz another error of same `strict db mode` change:
![image](https://user-images.githubusercontent.com/5720101/106151150-5a138600-617c-11eb-912a-e4c6da5e27c4.png)

**Comment by denysaw** [comment]
Also hotfixed on Prod.

**Comment by D3nnis3n** [comment]
Versions show up.
