### ISSUE TITLE
USER ISSUE: Random Deed Rent related disconnect error while being idle

### ISSUE THREAD

**Issue by ErkiLuik** [StrangeLoopGames/EcoIssues#20208]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.0 beta release-144

**Steps to Reproduce:**
1. Stay idle and tabbed out of the game for ~15 minutes or more.
2. Return to game to find disconnect icon bottom right corner.

* Had no interaction with Deed rental system. 
* Had previously set Active Deed after server update, however multiple hours earlier.

**Expected behavior:**
Resumed gameplay after returning to game.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.get_IsRentable()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'RentableDeeds' of 'Eco.Gameplay.Property.PropertyManager'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5888071/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5888072/Player-prev.log)

**Comment by SlayksWood** [comment]
merged to #20209 20211
