### ISSUE TITLE
[0.9.2.0 beta release-144] Server list not properly displaying online status

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20201]
Server list seems to not wanting to detect status of servers in favorite / recent tabs 

![Screenshot_48](https://user-images.githubusercontent.com/24981362/106118894-e14d0380-6154-11eb-8c5f-2ce8d947c45b.jpg)

**Comment by MishkaFur** [comment]
Also having the same, thought it was just my server being slow to show as online but Sea Otter is showing as offline too in recent but not in officials.

![image](https://user-images.githubusercontent.com/61889138/106120833-c7102700-614e-11eb-8180-3b33ba54bba0.png)
