### ISSUE TITLE
[0.9.2.1 beta release-146] Invite Resident max Occupants with number None crash server

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20210]
Hello,
 if someone is changing the max Occupants and forget to put in any number and keep it "none" the server is going to crash in case you become a resident.

![image](https://user-images.githubusercontent.com/47274045/106162868-dc09ac00-6188-11eb-977f-8c842ca4ac0c.png)

**Comment by Alteraner** [comment]
Here the Exception in the error log:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Negative_GameValue.Value(IContextObject action)
   at Eco.Gameplay.Property.Residency.BecomeResident(User user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/106247136-2ab65500-6220-11eb-8366-7a539b1430ef.png)

**Comment by Mattprass** [comment]
This appears to be addressed already with an OkBox preventing the invited user in staging, however there's a very similar issue happening with Max Occupants being determined via Hours Played, so a PR will be opened to address this as well as slightly modifying the OkBox message.
