### ISSUE TITLE
9.2.1 All users kicked from server null reference is rentable

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20211]
All users kicked from server with the below, no one is saying they did anything specific.

![image](https://user-images.githubusercontent.com/61889138/106168130-da8ab480-6185-11eb-89ee-38be112c6b63.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5888622/Player.log)

![image](https://user-images.githubusercontent.com/61889138/106168276-fc843700-6185-11eb-9b8b-4ad91cbe01b0.png)

[ClientUpdateException Exception 01282353.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5888647/ClientUpdateException.Exception.01282353.zip)

**Comment by MishkaFur** [comment]
Seems same issue as https://github.com/StrangeLoopGames/EcoIssues/issues/20208 though mine affected all users

**Comment by SlayksWood** [comment]
> We are getting a lot of rent related crashes, regardless if experimental mode is enabled. I do not have clear reproduction steps at this time.
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Property.Deed.get_IsRentable()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
>    at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
> Outer Exceptions:
> Error during packaging property 'RentableDeeds' of 'Eco.Gameplay.Property.PropertyManager'</size>
> EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogWarning(Object)
> NetworkManager:OnClientDisconnected(String)
> System.Action`1:Invoke(T)
> Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
> UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
> Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
> Eco.Networking.ENet.ENetUdpPeer:HandleEvent()
> Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
> <>c__DisplayClass63_0:<Initialize>b__0()
> UnityEngine.DisplaysUpdatedDelegate:Invoke()
> System.Action`1:Invoke(T)
> System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
> System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
> UnityEngine.DisplaysUpdatedDelegate:Invoke()
> ```

**Comment by SlayksWood** [comment]
> **User Id: (Not logged user)**
> **Version:** 0.9.2.0 beta release-144
> 
> **Steps to Reproduce:**
> 
> 1. Stay idle and tabbed out of the game for ~15 minutes or more.
> 2. Return to game to find disconnect icon bottom right corner.
> 
> * Had no interaction with Deed rental system.
> * Had previously set Active Deed after server update, however multiple hours earlier.
> 
> **Expected behavior:**
> Resumed gameplay after returning to game.
> 
> **Actual behavior:**
> The following error message popped up:
> 
> ```
> Server encountered an exception:
> 
> <size=60.00%>Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Property.Deed.get_IsRentable()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
>    at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
> Outer Exceptions:
> Error during packaging property 'RentableDeeds' of 'Eco.Gameplay.Property.PropertyManager'</size>
> ```
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> No
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5888071/Player.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5888072/Player-prev.log)

**Comment by thetestgame** [comment]
Not sure if this is helpful/related but we see a spike in this particular error when splitting land claims.

**Comment by SlayksWood** [comment]
@thetestgame maybe related, but for now we have separate issue for it #20199.

**Comment by SlayksWood** [comment]
> **User Id: (Not logged user)**
> **Version:** 0.9.2.1 beta release-146
> 
> **Steps to Reproduce:**
> I picked up Hew Logs from the storage and placed it (underneath a floating Turtle after I dug tthe earth from underneath it)
> 
> **Expected behavior:**
> Kick from server
> 
> **Actual behavior:**
> The following error message popped up:
> 
> ```
> Server encountered an exception:
> 
> <size=60.00%>Exception: NullReferenceException
> Message:Object reference not set to an instance of an object.
> Source:Eco.Gameplay
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Eco.Gameplay.Property.Deed.get_Rent()
>    at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
>    at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
> Outer Exceptions:
> Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
> Error during packaging property 'Rent' of 'Eco.Gameplay.Property.Deed'</size>
> ```
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> no
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
