### ISSUE TITLE
USER ISSUE: Fish trap can't be opened

### ISSUE THREAD

**Issue by Anabella00geek** [StrangeLoopGames/EcoIssues#20218]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
Place fishing trap and press E

**Expected behavior:**
Should open to get fish out of it.

**Actual behavior:**
Have to use a hammer to pick up fish trap.  You then get fish.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.  Started with new update 9.2

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.

**Comment by Daniel-Magulado** [comment]
Adding a video repro:
https://images.zenhubusercontent.com/47210472/745c42e7-2449-4507-9291-fe45f7e1f40a/eco_2021_01_29_09_02_26.mp4

**Comment by SlayksWood** [comment]
fixed for 9.3. Next fixes here #20866
