### ISSUE TITLE
0.9.2.1 (Linux) "maximum height for a (7200, 7200) world is 40"

### ISSUE THREAD

**Issue by enexusde** [StrangeLoopGames/EcoIssues#20216]
Switch from version 0.9.1.9 to version 0.9.2.1 creates a Error on an existing Savegame:

```[18:08:23.752] [8] [Error] [Eco] Failed to load server, Exception was Exception: ArgumentException
Message:The maximum height for a (7200, 7200) world is 40. (Total world volume of 7200 x * 160 y * 7200 z = 8294400000 is larger than the max supported size of int.MaxValue (2147483647))
Source:Eco.Shared

System.ArgumentException: The maximum height for a (7200, 7200) world is 40. (Total world volume of 7200 x * 160 y * 7200 z = 8294400000 is larger than the max supported size of int.MaxValue (2147483647))
   at Eco.Shared.Math.WorldPosition3i.Initialize(Vector3i worldSize)
   at Eco.Shared.Voxel.ChunkGrid`1.SetWrappedVoxelSizeInternal(Vector3i value)
   at Eco.Shared.Voxel.ChunkGrid`1.set_WrappedVoxelSize(Vector3i value)
   at Eco.World.World.Initialize(Vector3i chunkSize)
   at Eco.WorldGenerator.WorldGeneratorPlugin.CreateWorld()
   at Eco.WorldGenerator.WorldGeneratorPlugin.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)^M
```

**Comment by enexusde** [comment]
The old version 0.9.1.9 works correctly. Does that mean that at some point there is a Out-of-Range error that kills the Savegame?

**Comment by D3nnis3n** [comment]
Yes. Somewhere that world has a block higher than 40, which is the max
height for that world size.

Peter Rader <notifications@github.com> schrieb am Do., 28. Jan. 2021, 22:22:

**Comment by enexusde** [comment]
I understand. Since the game has been used from about 11 players for +100h, would you try to fix the Savegame? 

I mean this limitation was unknown to us because it was a techincal detail that had not been validated during the creation process. I think it was not our fault.

**Comment by mirasrael** [comment]
@enexusde you really ran 52km2 world? This constraints exists for long time, so doesn't seems it was introduced in 9.2.

**Comment by enexusde** [comment]
The Map was generated by your Server version 0.9.1.9. This is a long time for you? 100h of playtime is long I guess.

**Comment by enexusde** [comment]
I mean I understand that this is work that produces no income for SLG but those 11 guys are sad right now!

Can I tell them that SLG is sorry about this inconvenience? They might forgive and start a new game within the limitation of the world.

**Comment by mirasrael** [comment]
@enexusde can you confirm you run 52km2 world? It seems like a bug for me. Default word size is 0.52km2 (720x720). Official servers are 4km2. Some experimented with 16km2, but it requires lot of memory and CPU power. So I really surprised if you run 52km2.

**Comment by enexusde** [comment]
I am able to send you the savegame for further inspection/fixing. The Savegame is huge, indeed.

**Comment by mirasrael** [comment]
Ok

**Comment by D3nnis3n** [comment]
Please attach the link to the save here :)

**Comment by enexusde** [comment]
https://e-nexus.de/eco.tgz

**Comment by mirasrael** [comment]
Checked your save file meta and it has world size 720x720 (not 7200x7200)
```
{"Dimensions":{"x":72,"y":72},"Version":"0.9.1.9 beta release-136"}
```
(dimension is in chunks which has 10x10 size).

**Comment by mirasrael** [comment]
So if you send me your whole server directory then layout seems invalid. It doesn't have Game.eco file in Storage directory
![image](https://user-images.githubusercontent.com/475445/106600426-798b2400-656b-11eb-832d-0e0686b3a174.png)
Instead it have it in Storage\Storage 
![image](https://user-images.githubusercontent.com/475445/106600492-8c9df400-656b-11eb-9879-d2d6894dfb1c.png)
And also it has invalid values in WorldGenerator.eco which prevents new world generation (you can reference for valid values in WorldGenerator.eco.template):
![image](https://user-images.githubusercontent.com/475445/106600549-a4757800-656b-11eb-92b7-fea6ed74eb32.png)

So what happens in your case:
1. It doesn't found Game.eco in Storage directory and tries to generate new world.
2. WorldGenerator.eco has invalid world size values (720x720 chunks which is 7200x7200 blocks) and it fails to generate so gigantic world.

To fix this:
1. Fix your WorldGenerator.eco (you can just remove it).
2. Fix your Storage layout (guess you should just move Storage\Storage one level above). Then your 9.1.9 world (with size 72x72 chunks) should start.

**Comment by enexusde** [comment]
Confirmed to be a OSI Model Layer 8 Problem.
