### ISSUE TITLE
USER ISSUE: Wood Cart issues

### ISSUE THREAD

**Issue by Anabella00geek** [StrangeLoopGames/EcoIssues#20215]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
Place a wood cart.  Target wood cart to place stuff in it.  Place dirt in cart with shovel.  Place brick in cart with hammer.  Remove brick in cart with hammer.  Walk around cart.

**Expected behavior:**
Should be easy to get things from and place things in cart.  Cart should not move super easy just from getting bumped.

**Actual behavior:**
Hitbox is super picky so keep placing dirt on ground, knocking out road blocks around the cart while trying to remove blocks with hammer in hand, and cart is gets pushed around by just moving near it.  

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.  This all started to happen with the new 9.2 update from today.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
It happens for more vehicles, need to further investigate this to come up with reproduction steps.
https://i.gyazo.com/1e98b47f37b17234cb83196f63344dc7.mp4

**Comment by Hydrohawk** [comment]
We've been encountering this bug on our current world, which was launched this past Friday.  Several players, (myself included), have been having issues with it as well.  Exiting the server and rejoining seems to fix the problem.

(Video from one of our players)
https://i.imgur.com/RKz0hdU.mp4

**Comment by Daniel-Magulado** [comment]
Merging with #20414
