### ISSUE TITLE
USER ISSUE: Work bench sounds continue after order cancelled

### ISSUE THREAD

**Issue by dnight71** [StrangeLoopGames/EcoIssues#20223]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.0 beta release-144

**Steps to Reproduce:**
1. Start order you cont have supplies for
2. Cancel order

Result: Workbench working sound continues

**Expected behavior:**
Sound should stop after order cancelled

**Actual behavior:**
Sound does not stop

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. 9.2.0

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.2.1, please update.
