### ISSUE TITLE
USER ISSUE: Problem

### ISSUE THREAD

**Issue by Dragendave** [StrangeLoopGames/EcoIssues#20220]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
I picked up Hew Logs from the storage and placed it (underneath a floating Turtle after I dug tthe earth from underneath it)

**Expected behavior:**
Kick from server

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.get_Rent()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
Error during packaging property 'Rent' of 'Eco.Gameplay.Property.Deed'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Dragendave Thank you fo the report. merged to #20211
