### ISSUE TITLE
USER ISSUE: Sleeping

### ISSUE THREAD

**Issue by StelanS** [StrangeLoopGames/EcoIssues#20229]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
1. When one player sleeps and wake up by pressing ESC dosen'd count it as woken up

**Expected behavior:**
The Player should be counted as woken up	

**Actual behavior:**
Instead when someone else is sleeping again the time is skipping all the time

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5891732/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5891733/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Thank you for reporting this.

**Comment by Daniel-Magulado** [comment]
Repro: Sleep and press ESC.

Video:
https://images.zenhubusercontent.com/47210472/06a1f820-3d3f-4e6c-8f38-4ea290e6a77e/eco_2021_01_29_14_21_26_trim.mp4

Logs: [https://app.zenhub.com/files/47210472/4cb4a24c-5f03-4266-869e-284c1fb0c5b8/download](https://app.zenhub.com/files/47210472/4cb4a24c-5f03-4266-869e-284c1fb0c5b8/download)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1928

Resolution: It's not happening on the staging build anymore. Appears to be fixed. Closing.
