### ISSUE TITLE
Server Crash 9.2.1 Vanilla

### ISSUE THREAD

**Issue by IceWarden** [StrangeLoopGames/EcoIssues#20224]
Server is currently crashing as players connect. There is no crash log. Windows Event viewer shows the following:
`Application: EcoServer.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.GameValues.Values.HoursPlayed.Value(IContextObject context)
   at Eco.Gameplay.Property.Residency.BecomeResident(User user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by SlayksWood** [comment]
@IceWarden Thank you for the report. Can you provide save file to investigate it? and may be provide more details what could have caused it.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information. 
We fixed a several issues with Wages and resident, so possible should be fixed.
