### ISSUE TITLE
[9.2.1] Everyone tag no longer works in authorization on deeds

### ISSUE THREAD

**Issue by kaitoyuuki** [StrangeLoopGames/EcoIssues#20227]
![image](https://user-images.githubusercontent.com/2185709/106227215-ab803d00-619d-11eb-9509-e227f8794df5.png)
as you can see, with just "Everyone" added in authorization, I'm unauthorized on this deed. adding the "everyone" tag to individual objects still works, however. we've tested this on both residency and non-residency plots with the same results
![image](https://user-images.githubusercontent.com/2185709/106227378-e97d6100-619d-11eb-8fef-d88b5a3af5d4.png)
adding a user by name to the plot also still works.

Using the Linux server with the latest version, downloaded at 12:00PM PST, all of us are on the latest windows version of the steam client

**Comment by SlayksWood** [comment]
@kaitoyuuki Thank you for the report. More like the Everyone demographic problem. Can you provide screenshot of this tab in Government? to check Everyone.
![image](https://user-images.githubusercontent.com/45708377/106240785-f0e05100-6215-11eb-9259-363b5269c88c.png)
And can you provide your save file to investigate this issue on your server. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by MrX13415** [comment]
I can confirm this. We also have this issue. It's the same for titles. Only direct player names work.

**Comment by MrX13415** [comment]
> Fix provided, but if you don't want to wait hot fix you can use this fixed executable compatible with 9.2.1: https://drive.google.com/file/d/1OQ4A5ES44HEVjsh7KHx0ef66iBF_ANHr/view?usp=sharing

The fix posted here, also seem to fix this issue as far as my tests show.

**Comment by WeaselDog** [comment]
Thanks for letting us know about this. It is fixed in the latest update.
