### ISSUE TITLE
Server fails to load after update to 0.9.2.1

### ISSUE THREAD

**Issue by Blue0ak** [StrangeLoopGames/EcoIssues#20225]
Hosted through steamCMD, the server fails to load after finishing initialization when using the most recent saved data. The same data still works well when running on a 0.9.1.9 server.

In the logs (attached to this ticket), following the first error message, elections are mentionned. An election to overthrow the constitution was ongoing at the time.

[log_210128070621.log](https://github.com/StrangeLoopGames/EcoIssues/files/5890926/log_210128070621.log)

In attempting to resolve the issue, the server successfully loaded when using the most recent backup preceding the election start. The following error however appears in the associated logs (not attached):

Error: Removing corrupted entry <b><link="ref:Election:1"><ecoicon item="Election"><style="Government">Ratify The Hoenn Constution</style> <style="ErrorLight">(removed)</style></ecoicon></link></b>: 2 errors:
Actions On Complete #1 / Element: Not contained by any object.
Actions On Complete #1 / Element: <b><link="ref:Constitution:2"><ecoicon item="Constitution"><style="Government">The Hoenn Constution</style> <style="ErrorLight">(removed)</style></ecoicon></link></b> is <style="ErrorLight">invalid.</style>: Not contained by any object.

**Comment by SlayksWood** [comment]
@Blue0ak Thank you for the report. Can you provide save file? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by IcedForge** [comment]
Will close this in lack of reply with relevant information please reopen if you still have this problem and attach the aforementioned files.
