### ISSUE TITLE
USER ISSUE: Game Freeze

### ISSUE THREAD

**Issue by Vareska** [StrangeLoopGames/EcoIssues#20222]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
16k world and if anyone claims land everyone freezes for 1-2 seconds and the person claiming freezes for upto 6 seconds.

**Expected behavior:**
claiming land doesent cause freezes

**Actual behavior:**
game freezes for 5-6 seconds when claiming land and everyone on the server freezes for 1-2 seconds

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed and issue happens even without mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please note that your world size is unsupported, the maximum supported world size is 4 km².
We'll take a look on the issue nontheless as it reminds me of an issue we had back a few versions, but in case its related to the world size, it might not be fixed.

**Comment by SlayksWood** [comment]
We have a problem with the claiming in smaller worlds too #20199. This may be related to your problem.
@Vareska Can your check CPU loading inserver machine when someone claim/unclaim. And please provide save file to investigate it more.
Instruction is here  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Vareska** [comment]
cpu load isnt going anywhere near over 30% when people are claiming, its not a hardware issue. also, theres no point in me uploading an empty 16k world with about 50 land claims and some holes people have dug.

Ive set the cpu tick usage to 1.0 from 0.2 in the config settings in the hopes that it would help... but its done nothing.

The box that is running the server has the following hardware:
Aorus B450 AORUS M
Ryzen 7 1700
ASUS GTX 1060 Dual OC 6gb
Sabrent 1tb NVME
Crucial Ballistix 3600 MHz 128GB 32GB x4

**Comment by D3nnis3n** [comment]
Please leave it to us on what we deem required to investigate an issue.
So, please attach your world file so we can investigate this issue further.

**Comment by Vareska** [comment]
https://www.dropbox.com/s/mto3lvjlfiif4yd/Storage.zip?dl=0
That is my current world (no db) + 2 backups with db's

**Comment by D3nnis3n** [comment]
Thank you.

**Comment by Vareska** [comment]
Is it possible to set the cpu tick above 1.0? Or is that 100%?

**Comment by SlayksWood** [comment]
make a little optimization for 9.2 with https://github.com/StrangeLoopGames/Eco/pull/7707, and will fixed in 9.3 with this issue #20320. closed
