### ISSUE TITLE
Client getting disconnected from server due to inactivity

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2023]
Client getting disconnected from server due to inactivity, when client is not inactive
Almost certain this is not a local networking problem.

**Comment by EmuLegs** [comment]
most of the time i see this bug after/as another bug happens
it would be very nice if this could give us a correct error message

**Comment by MarjieAVolk** [comment]
Yeah, as I understand it there are a lot of things that can cause this, such as the server being slow, or a player's action taking too long on the server.  So it's not really useful as an individual bug, without more information.

**Comment by metachronism** [comment]
closing without more details, hard to fix
