### ISSUE TITLE
[0.9.2.1 beta release-146] Titles or Demographic without wages prevent law creation/revision

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#20232]
This law evaluates a Title Requirements.  
The title had no wage when created but now old and new titles and demographics have the wage section added by default and set to none.  
This raises an error when using Titles or Demographics in laws and prevents adding changes to an election.  
It is still possible to create or revise Titles or Demographics with wages unset.
(Only showing screenshots of Titles window because it's the same with Demographics

![image](https://user-images.githubusercontent.com/33208603/106244686-96da8e00-620b-11eb-9421-05510ba50411.png)
![image](https://user-images.githubusercontent.com/33208603/106244928-f173ea00-620b-11eb-9be1-96a4d9ce68a5.png)
![image](https://user-images.githubusercontent.com/33208603/106245184-5c252580-620c-11eb-8dce-af35b6a80608.png)
![image](https://user-images.githubusercontent.com/33208603/106245221-6c3d0500-620c-11eb-91d3-853e31444162.png)

**Comment by SlayksWood** [comment]
@Asharas Thank you for the report. Did it happen after server migration to 0.9.2? Can you provide save file to investigate your problem? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Asharas** [comment]
Hi!
Yes it happened after the 9.2 update. Unfortunately I am not the server admin so I don't have access to the world save files.

**Comment by SlayksWood** [comment]
@Asharas we cought an exception with it in #20274. Possibly it will fix you issue too, but need to check it. So you should another feedback after 9.2.3 release.

**Comment by Asharas** [comment]
Partial fix.
For one law "book" (of 3 in the court) it did fix the problem, the error disappeared both for Title evaluated in law and Demographics required by said title.  
![image](https://user-images.githubusercontent.com/33208603/106599518-7b4bec00-6559-11eb-8eb1-2db36bf8d573.png)

For another law "book" it didn't change anything.
![image](https://user-images.githubusercontent.com/33208603/106598750-776b9a00-6558-11eb-8733-95e4ea4cc72f.png)  

Don't pay attention to the removed/proposed titles and related error, I messed up with the Government Office (and potentially uncovered 2 more bugs)

**Comment by Venopsis** [comment]
Hi,
For info I have the same issue regarding wages requiring amount and currencies error.
I rollback to 9.1.9 working backup and did the update to 9.2.3.
No luck. Still happening and cause lot of issue has break laws, titles, etc.

**Comment by Venopsis** [comment]
As a remark, if I try to set back to none for "Amount Per Hour" it stays on a manual value field:
![image](https://user-images.githubusercontent.com/949573/106629832-89126900-657b-11eb-81d5-facf3e7562d1.png)

**Comment by Venopsis** [comment]
Noticed another bug.

Amount set on 10
![image](https://user-images.githubusercontent.com/949573/106630639-4b621000-657c-11eb-9dea-4ab7f4c0cdee.png)

But notification shows 7 ...
![image](https://user-images.githubusercontent.com/949573/106630901-882e0700-657c-11eb-89ed-c6eab690f8b1.png)

But the amount is correct on popup regarding the elected title:
![image](https://user-images.githubusercontent.com/949573/106630804-7187b000-657c-11eb-8744-af451ad3fc90.png)

**Comment by SlayksWood** [comment]
@Venopsis What is 'Recuring Transfer Frequency' on the server?
![image](https://user-images.githubusercontent.com/45708377/106703848-1dbcab80-65fc-11eb-9b36-970195383ae3.png)
10 per hour does not mean that payments are made every hour it depend on server settings.

**Comment by Venopsis** [comment]
@SlayksWood Yep noticed this details as later while doing some other repairs on laws I noticed notification mentioning half the wage amount for 30 minutes.
So I assumed in my case the frequency was 30 minutes and in this case give the ratio of currency.
On server it's 30. That match with my observations.

**Comment by Venopsis** [comment]
So with 9.2.4 the object not found issue is gone. But I still have "issue" when I change "Payment type" as I cannot change from online hours to online/offline hours.

**Comment by SlayksWood** [comment]
@Venopsis Thank you for the all feedback. 
partial 'online / offline hours' was fixed here, but there is still a bug that it cannot be changed after the first assignment. Made a separate issue for this #20372.
Closed for now.
