### ISSUE TITLE
The server crashed

### ISSUE THREAD

**Issue by rmndmtrvch** [StrangeLoopGames/EcoIssues#20239]
My server crashes on startup when the world is converted to the new format. The problem appeared after the update 9.2.

World save: https://drive.google.com/file/d/1g7asyC-BGlGnIGzGbVUrcGXkSFkhB29T/view?usp=sharing
[log_210129054924.log](https://github.com/StrangeLoopGames/EcoIssues/files/5894548/log_210129054924.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5894550/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5894551/Player-prev.log)

![20210129175137_1](https://user-images.githubusercontent.com/78219080/106291434-a7ffbb00-625c-11eb-9405-ffb583d3d433.jpg)

**Comment by SlayksWood** [comment]
@rmndmtrvch Thank you for the report and sorry for the wait. There is a migration problem with your world. We will try to fix it asap.

**Comment by mirasrael** [comment]
Save was broken before migration, but migration during Convert world phase unpacks chunks which usually not touched. In this save they was broken and if in example you dig to 180,0,50 on 9.1.9 then server crash.

But I was able to recover the save (with some chunk data lose):
[Game-fixed.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5902945/Game-fixed.zip)
