### ISSUE TITLE
Arrastra Upgrade Modules NOT Working

### ISSUE THREAD

**Issue by Etep15** [StrangeLoopGames/EcoIssues#20233]
I was given an Arrastra in game and I set it up and put in a Basic Upgrade Module 3 into it. This should reduce the resource costs by 40%. Especially important for all that Crushed Limestone we need now in the Masonry tree (with Glass now needing it). 

Regardless if I have the Module in or not, it still says 12 Limestone is required to make 3 Crushed Limestone. Should it not show it as much less?

This is on the latest patch 9.2.1.

**Comment by SlayksWood** [comment]
@Etep15 Thank you for the report. This is intented behavior. In game we have some static value for some ingredients. They are all highlighted with a yellow border and have notification in the tooltip that they are not affected by modifiers:
![image](https://user-images.githubusercontent.com/45708377/106253664-d499df80-6228-11eb-9e42-e0036667769c.png)

**Comment by Etep15** [comment]
Ah ok. thank you very much. Sorry to add to your list of issues... that aren't issues.. :) 

Love the game and the concept. It's quite amazing what you guys are building!
