### ISSUE TITLE
Unable to set elected titles, demographics or registrar titles as registrar title managers

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#20237]
1. create a registrar title
![grafik](https://user-images.githubusercontent.com/34270661/106269630-0ca32180-622d-11eb-855a-3f4420e8fb9f.png)
2. set a title, demographic or registrar title that you have as the manager (in my case, all three for testing). I have the registrar title slave owner, the demographic "admins" and the elected title "big bob".
![grafik](https://user-images.githubusercontent.com/34270661/106269728-2b091d00-622d-11eb-8296-e559cee39ac1.png)
3. remove your name from the title managers, you should still have permissions to manage the title. Instead, I can no longer see the registrar title "slave"
![grafik](https://user-images.githubusercontent.com/34270661/106269840-5855cb00-622d-11eb-9e0e-4178e2df19d7.png)
the slave title still exists though
![grafik](https://user-images.githubusercontent.com/34270661/106269893-6efc2200-622d-11eb-9170-e5cf2e96030c.png)

**Comment by D3nnis3n** [comment]
Blocking a specific server we have that may start or not start today.

**Comment by SlayksWood** [comment]
the same with bank

**Comment by mirasrael** [comment]
Fix provided, but if you don't want to wait hot fix you can use this fixed executable compatible with 9.2.1: https://drive.google.com/file/d/1OQ4A5ES44HEVjsh7KHx0ef66iBF_ANHr/view?usp=sharing
