### ISSUE TITLE
Cloud World orders paid double

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20235]
Buying a cloud world costs $15 (without tax) immediate fee + $16.52 (with tax) as subscription fee on the same day.

It should only cost $16.52 (with tax) immediately and the next subscription fee should be one month later.

**Comment by denysaw** [comment]
https://media.discordapp.net/attachments/324611394463072257/804712725447704596/unknown.png?width=779&height=111

**Comment by denysaw** [comment]
Solved that on Staging for now. Proof:
![image](https://user-images.githubusercontent.com/5720101/106538002-c0d9cc00-64fb-11eb-9166-f3d82a01b97f.png)

There really was described problem. Now everything is ok, but needs to be tested. @SlayksWood can you help?
To test buying world with new account and then checking this: https://www.sandbox.paypal.com/myaccount/autopay/
Should be like on my snap. Thanx a lot! After confirmation we'll update prod with this logic.

**Comment by denysaw** [comment]
@SlayksWood Reminding about this one, cuzz of critical status :) Sorry to bother

**Comment by D3nnis3n** [comment]
Seems fixed.
