### ISSUE TITLE
Missing hover effect for "X" on Your Worlds

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20242]
https://cdn.discordapp.com/attachments/535462748981821442/804772448779370546/unknown.png

Delete Server has no hover effect, the other two have.

**Comment by SlayksWood** [comment]
I only don't have it when mouseover 'X' with selected world (local or officials) which I can't delete. In other case it works:
![image](https://user-images.githubusercontent.com/45708377/106422350-7f034400-646f-11eb-90b4-be9ca431f5f8.png)
