### ISSUE TITLE
Change minimum mouse sensitivity

### ISSUE THREAD

**Issue by Archbishop666** [StrangeLoopGames/EcoIssues#20244]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
using left and right mouse button

**Expected behavior:**
You can't rotate your character

**Actual behavior:**
Nothing happens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Seems like a bug with mouse sensitivity it's pre set to 0.1. Someone not smart enough to check this will assume the games broken and won't come back again, first impressions are everything even in early access. PS. add a problem description box for reports. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Archbishop666 Thank you for the report.
Default Mouse Sensitivity = 5, I tried to reprodduce your steps and can't. When I first time install game I have default sensitivity = 5. 
And without my intervention I can't set it to 0,1.
Can you provide more details how it happened to you and also provide your PC specification (include Operating System and its version)

**Comment by SlayksWood** [comment]
@WeaselDog @johnkslg @keegan-o 
maybe we worth changing the minimum value of Mouse Sensitivity to 1 or maybe 0,5? Because with sensitivity less 0,5 hard to play.

**Comment by SlayksWood** [comment]
John:
> ![image](https://user-images.githubusercontent.com/3536496/107863858-31da8700-6e0c-11eb-86c7-02498a6c6128.png)
> player prefs deleting yielded this
> ![image](https://user-images.githubusercontent.com/3536496/107863869-461e8400-6e0c-11eb-97d2-8ccd5122cee3.png)
>It shouldnt be allowed to go that low, you cant even move it
