### ISSUE TITLE
Server Crashes since 9.2 +

### ISSUE THREAD

**Issue by SirBlehhh** [StrangeLoopGames/EcoIssues#20240]
Hi All,

Issue: "Random" Server crashes since yesterdays updates, 9.2.0 & 9.2.1, all mods removed, and some mods (update) re added today. However my server is crashing both vanillia and modded.

[log_210129020559.log](https://github.com/StrangeLoopGames/EcoIssues/files/5894700/log_210129020559.log)

**Comment by SirBlehhh** [comment]
further crash report
[Part of Crash Log 2.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5897876/Part.of.Crash.Log.2.txt)

**Comment by WeaselDog** [comment]
Thanks for reporting this. This crash has been fixed in 9.2.2. Please let us know if you have this issue again.
