### ISSUE TITLE
USER ISSUE: probleme dans la liste des serveurs

### ISSUE THREAD

**Issue by GabyForester** [StrangeLoopGames/EcoIssues#20241]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
Lancer Eco > "mes mondes" , voir que certains serveurs sont offline, actualiser la liste des serveurs récents et favoris, et tous les serveurs passent offline, sauf mon serveur :" [FR] avance rapide constructions", qui est joignable uniquement en LAN / 

**Expected behavior:**
Les serveurs et mon serveur devraient être online.

**Actual behavior:**
Les serveurs sont pas tous online, et quand j'actualise la liste des serveurs dans "mes mondes" les serveurs deviennent tous offline, sauf mon serveur qui reste joignable en LAN uniquement, (les serveurs officiels n'ont pas de problèmes).

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Je n'ai pas de mods installés, j'ai re installer Eco Serveur, pour vérifier, et le problème persiste.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5895173/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5895174/Player-prev.log)
![report bug 2](https://user-images.githubusercontent.com/78224201/106306086-d5993400-625d-11eb-9ce8-2f963373a2ea.jpg)

**Comment by GabyForester** [comment]
j'ai également réinstallé entièrement Eco

**Comment by Nymrok** [comment]
Translation from french for dev team :
« _Servers should be online but they are offline when I open "Your Worlds". Official servers are not concerned by the issue, neither my local server_. »

To OP : Il y a un problème général d'authentification, tout le monde est concerné.

**Comment by SlayksWood** [comment]
@GabyForester Thak you for the report. This issue is fixed with 0.9.2.2 release https://github.com/StrangeLoopGames/Eco/pull/7690.
