### ISSUE TITLE
USER ISSUE: Unexpected game crash

### ISSUE THREAD

**Issue by SimplicitysStrength** [StrangeLoopGames/EcoIssues#20243]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
Pick up tomatoes with while on 0 food and game crashed.

**Expected behavior:**
Not crashed

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.Deed.get_Rent()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'Deeds' of 'Eco.Gameplay.Property.PropertyManager'
Error during packaging property 'Rent' of 'Eco.Gameplay.Property.Deed'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Maybe there are mods i'm not server admin.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Bugs are bad but you have a good report a bug feature.
Btw The popup for errors with the count of errors and animation in the latest 9.2 update is very annoying.

**Comment by SlayksWood** [comment]
@SimplicitysStrength Thank you for the report. This crash should be fixed in 0.9.2 with https://github.com/StrangeLoopGames/Eco/pull/7689
