### ISSUE TITLE
USER ISSUE: can't join a Server

### ISSUE THREAD

**Issue by SEKU-l** [StrangeLoopGames/EcoIssues#20245]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
1. Continue
2. error Message

1. Your Worlds
2. recent Sever joined
3. error Massage

**Expected behavior:**
It should have connected to a Server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Nymrok** [comment]
Same problem here.

Log file server-side : 
[serverside.log](https://github.com/StrangeLoopGames/EcoIssues/files/5895845/serverside.log)

Log file client-side :
[clientside.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5895844/clientside.txt)

**Comment by D3nnis3n** [comment]
There was a small hickup. Should be fine now? If not, please open a new issue :)
