### ISSUE TITLE
Cloud Worlds:  InvalidImageName

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20254]
slg185392-330 on sfo2 world is offline

`Error from server (BadRequest): container "eco-game-server" in pod "slg185093-333-7558677c7c-jzdsl" is waiting to start: InvalidImageName`

**Comment by j3fffff** [comment]
I was able to fix this world by reseting it with same serverid.
I notice in the db, this world was missing a server version.
@denysaw where would server version not be handed to db?

**Comment by denysaw** [comment]
@j3fffff in IPN (answered in DM)
@SlayksWood Could you please test what versions newly bought worlds have on staging? Cuzz for me world start worked perfectly.

**Comment by j3fffff** [comment]
fyi dennis confirmed he didnt manually edit this world

**Comment by denysaw** [comment]
On staging and hotfixed on Prod.
