### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by r0tt3ndr34m5** [StrangeLoopGames/EcoIssues#20251]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
Hunting an Animal

**Expected behavior:**
 Animal dies an can be picked up

**Actual behavior:**
sometimes it con not  be picked up

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes/yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@r0tt3ndr34m5 Thank you for the report. Can you provide log file when it happen next time?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #20414
