### ISSUE TITLE
USER ISSUE: Jump while falling

### ISSUE THREAD

**Issue by Regonoth** [StrangeLoopGames/EcoIssues#20260]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**
1. Fall a reasonable distance
2. jump mid-air	

**Expected behavior:**
probably should not be able to jump mid-air	

**Actual behavior:**
defys gravity comically

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for taking the time to report this. However, this is already a duplicate for #4021.
