### ISSUE TITLE
USER ISSUE: Minus XP modifiers

### ISSUE THREAD

**Issue by DarkEthanol** [StrangeLoopGames/EcoIssues#20268]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**
When using shared housing, after the update on the 30/01/2021 it apperas to go into the minuses for XP modifiers. Not sure if this is intentional, but a table and 4 chairs in a house caused -1million XP bonus	

**Expected behavior:**
Should be around 5 with a table and 4 chairs and a torch. 

**Actual behavior:**
Actually -1million. Also affected specialities.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting this, will close this particular as it is a duplicate you can follow the issue here #20296
