### ISSUE TITLE
USER ISSUE: I can't look around

### ISSUE THREAD

**Issue by Horaik** [StrangeLoopGames/EcoIssues#20263]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Horaik Thank you for the report. A few user have this problem. I guess it related with mouse sensivity. So just use reset defalts in controls tab or change mouse sensitivity:
![image](https://user-images.githubusercontent.com/45708377/106455052-ba683780-649c-11eb-8852-e4a5ce4f4660.png)
Also please provide your PC specification (include Operating System and its version).

**Comment by SlayksWood** [comment]
merged to #20244
