### ISSUE TITLE
Asian Font problem

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#20266]
Why didn't you fix the problem?

This issue was registered on GitHub before the 9.0 update
It was clearly resolved and reflected in 9.0
Still the same

ㅋㅋㅋㅋㅋ -> ㅁㅁㅁㅁㅁㅁ
Hello -> Hello

Hangul consonants don’t come out
![20210131003200_1](https://user-images.githubusercontent.com/61628364/106360509-15464580-635c-11eb-93ab-a7cbd9b167d8.jpg)

When will you solve it?
Do you need a Korean font?

**Comment by SlayksWood** [comment]
to check ㅂㅈㄷㄱㅅㅁㄴㅇㄹㅎㅋㅌㅊㅍㅛㅕㅑㅐㅔㅗㅓㅏㅣㅠㅜㅡ

**Comment by StoryNine** [comment]
> to check ㅂㅈㄷㄱㅅㅁㄴㅇㄹㅎㅋㅌㅊㅍㅛㅕㅑㅐㅔㅗㅓㅏㅣㅠㅜㅡ

Please solve it quickly
I'm uncomfortable

I believed it because I solved it...
Betrayal

**Comment by gzatravkin** [comment]
Fixed by SVN changes

**Comment by IcedForge** [comment]
![Screenshot_21.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0be8d7a1-2784-407e-985d-58e8cb134fab)

Tested in 0.9.3.0 staging-1949 (was this svn fix into staging or dev trunk?)

**Comment by StoryNine** [comment]
> ![Screenshot_21.jpg](https://camo.githubusercontent.com/bbdf5567523fd603a36aa3d952a64ad59e3cfe6efba90a8b8a19fc77be818776/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566356137666135393837386564393537613836313838362f30626538643761312d323738342d343037652d393835642d353865386362313334666162)
> 
> Tested in 0.9.3.0 staging-1949 (was this svn fix into staging or dev trunk?)

ㅁㅁㅁㅁㅁ << It should not come out like this
ㅋㅋㅋㅋㅋㅇㅇㅇㅇㄴㄴㄴㄴㄹㄹㄹㄹㄹㅎㅎㅎ

It should come out like this.

**Comment by gzatravkin** [comment]
Try 2, revision 8101 at staging SVN

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1960.

Appears to be fixed.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/6fee484c-1c49-4d50-97dd-7950a05b3cfc)

**Comment by StoryNine** [comment]
> Tested on 0.9.3 Staging-1960.
> 
> Appears to be fixed.
> 
> ![image.png](https://camo.githubusercontent.com/80d5f388e65bf4474e5758cec208b59707426dfb2a4128d8694777de6b63bfe2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666237356335616135633965326131323738653032342f36666565343834632d316334392d346435302d393764642d373935306130356233636663)

good! Thank you
Please do a quick patch!
