### ISSUE TITLE
[0.9.2.x beta] Pending Elections icon always visible

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#20262]
The Pending Elections icon on the right side of the screen is always visible since 0.9.2

Seen on two different servers (launched pre 0.9.2 then upgraded) and a fresh 0.9.2.2 (for testing purpose).

**Comment by SlayksWood** [comment]
I don't know why it appeared again. Seems it was fixed here #18393, but currently we have it again.

**Comment by SlayksWood** [comment]
#18380

**Comment by beastyn** [comment]
Could not reproduce on develop

**Comment by IcedForge** [comment]
Seems like its fixed as a side effect, its working correctly on both staging and develop so will close this for now.
