### ISSUE TITLE
USER ISSUE: Editing/making districts

### ISSUE THREAD

**Issue by RoronoaDroagon** [StrangeLoopGames/EcoIssues#20273]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.1 beta release-146

**Steps to Reproduce:**
1. make a district.
2. make another district for so to add on to the other district and keep adding on so it's a big district area.
3. exit out of the district editing window either the X button or submit button.

**Expected behavior:**
Exit out of the district editing window for so to end up in the district bench

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__70_3()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, i have mods but non are interfering with this system, all of em are recipie mods only. and yes it happens without mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@RoronoaDroagon Thank you for the report. CAn you provide your save file to investigate it? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
Can't reproduce. Closing for no response, reopen when you can provide us with necessary information
