### ISSUE TITLE
Not gaining Authorization on a plot when the "everyone" title is there.

### ISSUE THREAD

**Issue by KatFish08** [StrangeLoopGames/EcoIssues#20277]
On White tiger I cannot use any tools or place an object on the ground on a plot that has "everyone" listed under "who can access"
![382310_20210130185016_1](https://user-images.githubusercontent.com/78287358/106373217-3b53f180-632c-11eb-89c9-ea5a7a133089.png)
![382310_20210130185044_1](https://user-images.githubusercontent.com/78287358/106373222-3db64b80-632c-11eb-9df9-32019fb7772c.png)
![382310_20210130185049_1](https://user-images.githubusercontent.com/78287358/106373224-3f800f00-632c-11eb-9e2e-9b45da419ffe.png)
![382310_20210130185059_1](https://user-images.githubusercontent.com/78287358/106373227-4149d280-632c-11eb-9f0d-3f10608c10b6.png)

**Comment by Daniel-Magulado** [comment]
Hi there, thank you for reporting this. We are already aware of this issue and a fix for it is set for 0.9.2.3 release.
Duplicate for #20227
