### ISSUE TITLE
USER ISSUE: Small Wood Cart Bug

### ISSUE THREAD

**Issue by thomasgaragan** [StrangeLoopGames/EcoIssues#20278]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**
left my small wood cart alone while I traveled over to help my friend, When I came back i wasn't able to pick up or access the small wood cart. When I walked into it it just slid around.I used admin controls to give myself another one, and the same thing happend but I wasn't able to use it right away. The new cart was also bugged.

I put a third new cart on my property and was able to use it, but as soon as let go of, it is unusable

**Expected behavior:**
I should be able to pick up the cart and access the storage	

**Actual behavior:**
Slides around, can't pick up or access

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, bug continues after logging out and in

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Thibault-Brocheton** [comment]
a player of my server experience such issue. Deco / reco of the game fixed the isue

**Comment by pKoeni** [comment]
I have the same issue, too.

**Comment by IcedForge** [comment]
Thank you all for reporting, Can everyone please post their player logs which can be found if you run

**Comment by pKoeni** [comment]
Here is my player.log file.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5959954/Player.log)

**Comment by SlayksWood** [comment]
merged to #20414
