### ISSUE TITLE
server api key is acting up

### ISSUE THREAD

**Issue by Shadowknight441** [StrangeLoopGames/EcoIssues#20276]
My server is RG- Red Dragon| Noob Friendly and we have been experiencing disconnect issues I talked with my server provider and it wasnt on their end I upgraded thinking we were running low on memory. then I found this string of code the last time it did its disconnect. 

warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:18:55 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:19:55 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:19:55 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:21:06 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:21:06 +00:00". This could be caused by thread pool starvation.
fail: Eco.WebServer.Web.Filters.ExceptionFilter[0]
      Error during execution of /api/v1/elections/vote?authtoken=steamenc%3ACAEQpdS2jwEYACBAKnAnYFiSt5yZ3kDKTdE6sIs4fP5h9ZWKPEjuK%2BIAYJofO8iAV%2Bv3gVUVn9X42%2F1pna%2Bff04JiTcA%2BI9DUMPqNtnNWBhuE%2BEwl5zyDVaGhcIKmLweM1R5WpFVLi%2Ffjt9XH53oBcjS5eGzMHDRt%2BUkqBg7
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:22:12 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:22:12 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:23:13 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:24:25 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:24:21 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:24:25 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:25:19 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:28:24 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:28:24 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:29:40 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:29:40 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:29:40 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:30:52 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:30:52 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:30:52 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:31:57 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:32:49 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:32:49 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:33:39 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:33:35 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:33:39 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:34:49 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:34:49 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:34:49 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:35:07 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:35:08 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:35:11 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:35:41 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:36:19 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:36:19 +00:00". This could be caused by thread pool starvation.
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      Heartbeat took longer than "00:00:01" at "01/31/2021 01:36:16 +00:00". This could be caused by thread pool starvation.

**Comment by D3nnis3n** [comment]
The log is telling you that you are not having enough CPU resources, which is not a bug. You'll need to upgrade your CPU.
