### ISSUE TITLE
[9.2.2] UI Issue: Non-English Character causes reputation (clause) to dissapear

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#20286]
As titled, My name (Satsuki Shizuka 五月靜) is at a length where it would cover the reputation bracket entirely and thereby making it unselectable. Also as of 9.0, the Asian characters also have a kerned space in between them generated (making it look like 五 月 靜) and thereby lengthening it, perhaps exacerbating the issue.

**Comment by Daniel-Magulado** [comment]
Hi @SatsukiShizuka, thank you for reporting this. However, I am unable to reproduce this issue. Could you provide a screenshot of the issue, please?

**Comment by SatsukiShizuka** [comment]
https://imgur.com/a/IFeo5IW
Also highlighted is an example of how SOME players' mouseover summaries are bugged. My name is right underneath.

**Comment by Daniel-Magulado** [comment]
Confirmed Issue

Build: 0.9.2.2 Release-149

Repro:
1. Use a non-English character as your avatar's name. Example,  五月靜.
2. Observe your name under Objectives or by pressing O.
3. Have other players give you a reputation.
4. Observe your name again under Objectives UI.

Result: Using a non-English character as your avatar's name causes the Reputation clause to disappear. It also causes the player's name to completely disappear on Objective window UI if there's no English character in it. Additionally, players are unable to view the player tooltip for the affected players in Objective window UI.

![ffff.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/008fa2c8-74e7-42f7-9534-0f3f9f7caff5)

On the screenshot, the second and fourth name has the characters 五月靜 in them. The second name should have a displayed reputation of esteemed as seen on the image below:

![das.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/320afbde-1725-4160-9f75-1612a3bfe771)

**Comment by SatsukiShizuka** [comment]
Further update: As an alpha-backer, I usually get my Alpha-backer items in every round. However I have not received them in this version. This may also be a sign that non-Latin characters may be encoded or parsed differently somehow this round. Please investigate.

**Comment by SlayksWood** [comment]
Still an issue:
- /test makeuser Satsuki Shizuka 五月靜:
![image](https://user-images.githubusercontent.com/45708377/115524250-9b589500-a296-11eb-8d14-a5490b6fae7d.png)

**Comment by SlayksWood** [comment]
![Uploading image.png…]()
