### ISSUE TITLE
[0.9.2.2 Release-149] Changing Initial District Name/Color on District Editor doesn't get saved.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20287]
Build: 0.9.2.2 Release-149

Issue: The first District that appears under Contained Entries on Zoning Office doesn't allow the player to change its name. Nothing happens after changing the name and submitting it. It always reverts back to how the game named the district.

Repro:
1. Interact with the **Zoning Office**.
2. Revise any district map.
3. Click the name icon editor for the first district that appeared under Contained Entries to change its name. Change the name of the district.
4. Click submit.
5. View your submitted draft and observe the district's name.

Result: Changing the district's name and submitting it doesn't get saved. The district's name always reverts back to its original name.

Note: 
-It doesn't happen to other districts that get added via Add New District. The changes in the name get saved. However, the changes made on the added new district exhibit the same issue if players desire to change the name later while in draft form.
-Changing the color exhibits the same issue.

Video Repro:
https://images.zenhubusercontent.com/47210472/ae20bfcb-ded0-4fda-a581-a20e19f197e4/2021_02_01_02_31.mp4

QA Feedback: Related to #20063
User report: #20344, #20378

**Comment by Alteraner** [comment]
Besides the issue with the renaming and recoloring there is a further issue with the zoning office. once you have updated the district map, the counter behind the map is not increasing with +1. it's increasing with "number of maps" + 1. So if you have in one district map four zones with zone A, zone B, zone C and zone D. First time you update it will be renamed into zone A 1, zone B 2, zone C 3 and zone D 4. Next time it will be zone A 5, zone B 6, zone C 7 and zone D 8 and so on. From a logic point of view it should be zone A 1, zone B 1, zone C 1 and zone D 1. It is not the 8th version of zone D, its the 2nd one.

As discussed in another issue #20361 i would recommend replacing the existing id and do not count anymore as it confuses a lot of players and add the counter to the old versions.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.2.4 Release-162.
The issue is still happening. Furthermore, marking the world with the chosen color for the selected district doesn't work. You have to close the UI and open it again to see the marked areas.

Video Repro:

https://user-images.githubusercontent.com/77248866/108616593-9b304a80-7449-11eb-9765-639e4f554e1e.mp4

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Develop 279.

@Alteraner for your suggestion kindly raise a specific issue for that.
