### ISSUE TITLE
Hew Logs Project starts Regular, then switched to Hard/Soft version mid project

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20290]
I made a project for 1000 Hewn Logs at the Carp Table, I triple checked that it said Regular Hewn Logs.  It made about 2-3 hundred then switched to Hardwood Hewn Logs.  This is extremely Frustrating.  Especially since I am not a logger, I needed to have a logger come give the Calories for the job.  I Cannot cancel it becaues I can't get them to come back.  They are about 1.5Km away from our house.

If this is a Duplicate, please post like to Original Issue.

**Comment by SlayksWood** [comment]
@sirPattrick, Thank you for the report. I guess you made it with wrong way. Currentrly we have bad UI in this place. So to order only hewn logs you should:
- Enter number how much you want:
![image](https://user-images.githubusercontent.com/45708377/106569851-22bf2380-6546-11eb-9c48-5f2d267fb62f.png)
- then press gear:
![image](https://user-images.githubusercontent.com/45708377/106569891-32d70300-6546-11eb-9164-bb118b316ede.png)
- in opened window select Hewn log;
![image](https://user-images.githubusercontent.com/45708377/106569945-46826980-6546-11eb-9617-2bc0f9e5ef2f.png)
- and now press craft.
So it will always craft only hewn log.
If you just ented number and press order here:
![image](https://user-images.githubusercontent.com/45708377/106570043-6e71cd00-6546-11eb-81c9-334f87b1048a.png)
It will depend on what log you will add. Birch, Ceiba, Oak logs will give you hardwood hewn log; Cedar, Fir, Redwood, Spruce -  softwood hewn log; Joshua, Palm,Saquaro - Hewn logs

@sirPattrick did it help you?

**Comment by sirPattrick** [comment]
Sorry, I missed your response.   Those were the steps I took the first time, because I was making a job for 1000 hewn logs.  I wanted to make sure it was done right.  I clicked the gear, and then clicked the regular Hewn Logs.  And the job still switched after about 600 of the 1000 were completed.

**Comment by TwixterZ** [comment]
@sirPattrick I have tested this under 0.9.2.4 beta release-156 and unable to replicate your issue successfully, 

Do you still facing this issue on latest patch?

**Comment by sirPattrick** [comment]
I unfortunately have not been playing much, I am a Tax accountant, so it is our busy season at the moment.  As far as I know, this was the only time it happened where I specifically put in Regular hewn logs, and then the job made the other ones.  In all the other instances it seemed to work as intended.  I still think it should default to regular, unless you select hard wood or softwood.  (I believe that is the intention, it just got bugged this update)

**Comment by TwixterZ** [comment]
@sirPattrick, really appreciate your response. I will close this issue now,
