### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by QCsmaz** [StrangeLoopGames/EcoIssues#20293]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Informations de connexion invalides.

<size=60,00%>User doesn't have any assigned products</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting.
Please contact our customer service directly with details regarding this issue at
support@strangeloopgames.com instead for assistance.
