### ISSUE TITLE
[0.9.2.2 Release-149] Deed/property highlight gets carried over to New Game World

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20294]
Build: 0.9.2.2 Release-149

Issue: The highlight on the ground that appears when using the tool Land Claim Stake gets carried over to a newly created world if the player decides to disconnect and create a new game world.

Repro:
1. Create a new game and lay down the campsite.
2. Claim land with a different deed using the Land Claim Stake and Papers. Make sure the land/property/deed is not the same as your campsite deed.
3. Go back to your campsite and delete the Deed/property where the campsite is standing.
4. Disconnect and create a new world.
5. Observe.
6. Finish character creation and lay down the campsite.
7. Try to claim the land where the highlight appears or showing and observe.

Result:
1. The former claimed property/land/deed from the previous world before creating a new game gets carried over to the world created by making a new game.
2. Player's are unable to claim the land that's exactly in the same position where it was claimed on the previous game world.
3. Player's can claim the land from result number 2 by claiming the land around the highlighted area first then claiming the highlighted area.

Repro Video:
https://images.zenhubusercontent.com/42199084/4d00595f-1dae-4a4a-bf08-10675c19d70d/sample.mp4

Note: Possibly related to #20170.

**Comment by SlayksWood** [comment]
merged to #20170
