### ISSUE TITLE
Center and enlarge starburst

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20304]
![image](https://user-images.githubusercontent.com/3536496/106512764-e11b7380-6486-11eb-8d83-9d661b95d9c7.png)
Make the center the true center

**Comment by RobertMangano** [comment]
![image](https://user-images.githubusercontent.com/26705633/106536273-d70b7a80-6543-11eb-949c-9daf48a98584.png)
done

**Comment by RobertMangano** [comment]
it is 1 pixel off center on one side but should not be noticeable
