### ISSUE TITLE
USER ISSUE: Laws everything broke after this recent patch. (Was fine last patch)

### ISSUE THREAD

**Issue by SketchyPro** [StrangeLoopGames/EcoIssues#20312]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.3 beta release-150

**Steps to Reproduce:**
Many things, right now I can't even create pending elections, with or without adminship, unless I have someone come and edit the draft and start it for me. When I attempt to start and election, it doesn't show in pending elections. Another issue is that I get an error that should not be showing, and didn't show until this recent patch. "Errors, Position: Object is not set" Never ever have seen this before whilst trying to start an election to put someone under a title.

**Expected behavior:**
Allowed me to start and election, and allow someone to attempt at getting a title.

**Actual behavior:**
Showed me an error that has never existed before, and doesn't show up pending elections.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5908752/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5908753/Player-prev.log)

Another thing, this issue seemed to have start when I was using the Demographic table. But a bunch of other things within the law category also ended up braking. So maybe that might help?

https://drive.google.com/file/d/1dGqEU-CLCjeUuHakg9B2HXghGqJQFpUs/view?usp=sharing  <--- I tried to force default civics into the law tables so you can test out the issues. Hopefully this world download will help with solving the issue.

**Comment by SlayksWood** [comment]
@SketchyPro Thank you for the report. 
merged to #20315
