### ISSUE TITLE
USER ISSUE: Wierd camera angle after using drill.

### ISSUE THREAD

**Issue by TimoGiese** [StrangeLoopGames/EcoIssues#20316]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.3 beta release-150

**Steps to Reproduce:**
1. Use iron Rock drill and do not leave the inspection UI.
2. Enter a vehicle (I used the powered cart btw the camera could be lower so my head is not in the ceiling when in a 3 heigh tunnel).
3. Leave inspection UI by using the right mouse button.
4. Enjoy your freely rotating camera in the normal driver person.
5. Get automaticly kicked out of the vehicle after a few seconds

**Expected behavior:**
No wierd Camera

**Actual behavior:**
Wierd Camera

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TimoGiese** [comment]
To clearify point 4. The camera seems to be affected by gravity and is sort of rotating around the player which is not sitting in the vehicle somehow

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. I can confirm that this is happening.

Attaching a video repro.
https://images.zenhubusercontent.com/47210472/1c26db00-47ef-4245-904b-5e19163bba91/eco_2021_02_03_07_08_30_trim.mp4

Note: When the POV camera reaches the ground, if it is moved quickly enough the vehicle will be thrown off the ground.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 251
