### ISSUE TITLE
[0.9.2.3 beta release-150]UI: Stores listed in tooltips multiple times

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20313]
Item tooltip for store listings can happen multiple times if you pickup and place down the store faster then the server has time to process the pickup/placement action properly, leading to additional store listings even if it does react with stating that "object is removed"

![Screenshot_160](https://user-images.githubusercontent.com/24981362/106572655-fcdf5200-6538-11eb-8546-816846024ec4.jpg)

As you can see i place the store twice the amount of times that the store notifications actually push out to the server.

![Screenshot_161](https://user-images.githubusercontent.com/24981362/106572788-2a2c0000-6539-11eb-906a-48952abb14aa.jpg)

Reproduction
Place store, add items for sale
Pickup store, place down and repeat a few times.
Now store will be listed several times on the items added for sale.

**Comment by gzatravkin** [comment]
Check like of EconomyTracker            var buys            = this.Trades.Where(x => x.ItemTypeID == id && x.NumberWanted > 0);
Maybe you can just check x=>x.Store != null
