### ISSUE TITLE
[9.2.3] Laws - Object is not set

### ISSUE THREAD

**Issue by Venopsis** [StrangeLoopGames/EcoIssues#20318]
**Steps to Reproduce:**
Check law after migration from 9.1.9 to 9.2.3

**Expected behavior:**
Get this fixed to be able to use back this law.

**Actual behavior:**
Below is the affected law.

![image](https://user-images.githubusercontent.com/949573/106628626-4a2fe380-657a-11eb-9687-e849a7e1f74a.png)

![image](https://user-images.githubusercontent.com/949573/106628657-52881e80-657a-11eb-9edf-9c3e3eeeb9ad.png)

Initially before migration the law looked like this:

![image](https://user-images.githubusercontent.com/949573/106628768-6fbced00-657a-11eb-91a0-dc75d76312bd.png)

Even if I remove the condition and set it back I'm not able to submit it (even as admin). The display for the clause is different as location is no more shown.

![image](https://user-images.githubusercontent.com/949573/106629062-bc082d00-657a-11eb-8bca-9465d7df95af.png)

If I remove the second if regarding district the error is still preventing me to submit it.

![image](https://user-images.githubusercontent.com/949573/106629012-abf04d80-657a-11eb-9ae6-12a484120b05.png)

The other parts of the law are fine and show no error.

**Comment by Venopsis** [comment]
Last update:

I removed completely the section 1. Submit and law was working fine.

Then I edit it again with admin command.

Added te removed section as she must be. Submit and again error for law.

Edit with command and noticed I forgot the currency for the taxe. Not brilliant.

But also noticed the Location field appeared even if when "creating" the law and adding the missing section and set if condition to "Districts Requirements" this field didn't show.

![image](https://user-images.githubusercontent.com/949573/106632275-dabbf300-657d-11eb-8907-d8d29911d7a3.png)

I remove the second if condition about districts and use the cross to close the law.

I re-open it and this time, no more error message and submit button is green and can use it to submit the law.

Getting the message that now the law is valid:
![image](https://user-images.githubusercontent.com/949573/106632523-21115200-657e-11eb-90d5-34c38eb59fbd.png)

The problem is this is fixable with admin command but on long term I need this condition to be re-usable and also that end-user, players will not have to ask me to fix laws, etc. As if this field "Location" doesn't show up when you create the law to then submit to vote this is not good at all. Meaning they will need to submit it again for a second vote every time.

**Comment by IcedForge** [comment]
I believe most of this are symptoms from this #20315 and because it doesnt update fields correctly as you are creating the law ends up with being able to submit laws that are not yet properly populated by the system.

**Comment by Venopsis** [comment]
@IcedForge Yup seems UI issue as for ticket you mentioned. Was able to get the law working fine with condition regarding districts present if for almost each step I close before submit and disconnect/reconnect to the server (not for all step but some times even closing the law and re-open is not enough).
Then everything is present, no error and can click on submit.
Yeah!
Now waiting for 9.2.4 with big UI fix haha

**Comment by SlayksWood** [comment]
need feedback after 9.2.4 update

**Comment by Venopsis** [comment]
@SlayksWood When does the 9.2.4 will be available? Thx.

**Comment by ULiX80** [comment]
Validation of forms when changing parameters is not performed not only for laws, but also in other state workbenches. It is also impossible to accept an executive action, and on the contrary, you can accept incorrectly filled demographic groups or titles, which completely leads to the incapacity of the server. This makes the problem critical.

The law can also be adopted incorrect. First save the correct draft and then reopen it. After opening the draft, a check for correctness takes place and the button for accepting the law becomes active. Then enter the incorrect data into the law. The error check will not be refreshed, and the law accept button will remain active. by adopting such a law, you kill the server.

**Comment by Venopsis** [comment]
Fixed with 9.2.4!
