### ISSUE TITLE
[0.9.2.3 release-150] Civics UI update issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20315]
Step to reproduce:
- open court:
![image](https://user-images.githubusercontent.com/45708377/106593834-59a33280-6562-11eb-83a6-db440d36e58e.png)
- start to create a new law:
![image](https://user-images.githubusercontent.com/45708377/106593897-6cb60280-6562-11eb-8535-89e08599b705.png)
- I have error that I don't set trigger, that's right:
![image](https://user-images.githubusercontent.com/45708377/106594103-b4d52500-6562-11eb-8b6e-9c7ace46b7f9.png)
- select any trigger, I still have this error:
![image](https://user-images.githubusercontent.com/45708377/106594203-d8986b00-6562-11eb-8f3e-bd7d540d82f2.png)
- And I can't create a law without closing UI and reopening UI:
![image](https://user-images.githubusercontent.com/45708377/106594313-fbc31a80-6562-11eb-8f06-638a0132e599.png)

Another example want to join to election:
![image](https://user-images.githubusercontent.com/45708377/106594671-7d1aad00-6563-11eb-99e5-39731bb67237.png)

**Comment by Venopsis** [comment]
@SlayksWood Seems with 9.2 you have critical interface refresh and loading issue for sure.
Those issue below finally can be manage correctly if after each change I disconnect, reconnect to the server so information are loaded correctly.
#20318 - Laws - Object not set
#20317 - Constitution - Cannot specify a 'Uninitialized' Civic Article
#20232 - Titles or Demographic without wages prevent law creation/revision

**Comment by IcedForge** [comment]
This primarily has some blocking effects in starting elections and using executive actions where entry data is not stored, so closing the window to "update" removes input so they are unable to perform these actions completely.

**Comment by MystLeissa** [comment]
Also note: Executive Actions are impossible to preform because of this bug, since there is no way to "Save a draft" of a EA.

**Comment by MystLeissa** [comment]
Also I know it's a longshot - but in 9.2.3 there's an possibly related problem where the supposed "bug fix" for the registrar online and offline wages still don't allow you to change them to "Online Only"; Maybe have the programmers check the code segments around that fix location.

**Comment by SlayksWood** [comment]
fixed with 9.2.4

**Comment by ULiX80** [comment]
Validation of forms when changing parameters is not performed not only for laws, but also in other state workbenches. It is also impossible to accept an executive action, and on the contrary, you can accept incorrectly filled demographic groups or titles, which completely leads to the incapacity of the server. This makes the problem critical.

The law can also be adopted incorrect. First save the correct draft and then reopen it. After opening the draft, a check for correctness takes place and the button for accepting the law becomes active. Then enter the incorrect data into the law. The error check will not be refreshed, and the law accept button will remain active. by adopting such a law, you kill the server.

**Comment by ULiX80** [comment]
After several unsuccessful attempts to add an executive action, I was completely blocked from adding a new executive action. I press any "+" sign and there is no reaction. Another player can still work with the interface. Will this be fixed in 9.2.4?

![изображение](https://user-images.githubusercontent.com/6950252/106816702-7dc95580-66c1-11eb-9304-1b2d086e5cd2.png)

**Comment by ULiX80** [comment]
But the bug is not fixed in 0.9.2.4.
I still cannot perform the executive action.
