### ISSUE TITLE
[9.3] Missing Seize Bank Account Icon

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20325]
Build: 0.9.3 Develop-174

Issue: Under civics, the icon for condition "Seize Bank Account" is missing. Furthermore, its text display is color white and doesn't match the others.

Screenshot![seize bank account.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/ab6dcaf8-22e0-40a5-81c9-65c73b5a5f0a):

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/3c58484e-0e0f-4975-9583-60dc4588995b)
