### ISSUE TITLE
using Road Tool on undug Stone block turns stone into Stone Road, using pickaxe on this block make the block just Disappear

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2032]
i used the Road Tool on an un dug Stone block, this then turns that block into a Stone road, then i used pickaxe on this block and the block just disappears.
this is on build #bac3d6c8 as Builds have been coming often and our Test Server hasn't been updated to the latest yet.
![snap035](https://user-images.githubusercontent.com/29383891/29901656-1be5aabe-8df1-11e7-9974-e51b62ffbb63.png)
![snap036](https://user-images.githubusercontent.com/29383891/29901667-24a50a3c-8df1-11e7-8ca5-bdd564bbbf90.png)
![snap037](https://user-images.githubusercontent.com/29383891/29901671-2ce48ace-8df1-11e7-8bd0-7b8707b1f42e.png)

**Comment by MarjieAVolk** [comment]
This seems to be working on master - using a pickaxe on a stone road does not work; using a hammer on a stone road gives you a stone road block

**Comment by Conchipedia** [comment]
so is this how we make stone road now? using a road tool on untouched stone then picking up the converted block with a hammer? or will there be an option to craft this on a table?

**Comment by MarjieAVolk** [comment]
There is actually a bug for that here - https://github.com/StrangeLoopGames/EcoIssues/issues/2054

Think this stuff is still getting finalized
