### ISSUE TITLE
Constructed from Stoneroads and Asphalt Concrete

### ISSUE THREAD

**Issue by AndreK78** [StrangeLoopGames/EcoIssues#20327]
Hello,

i heard found a bug. If you want to build stone roads or asphalt roads, you make a mistake. The game does not "understand" that the roads have been built - if you want to dismantle the roads, you have more roads on hand but the roads are still "built up"
If you delete e.g. one block street with the dev tool, all built streets are gone.

Because of the problem, some laws don't work either. Such as. a road law for players who can get money for building the road.
The server is on version 9.2.3.

best regards
Andre Krause

**Comment by AndreK78** [comment]
I tested it again. The mistake comes from the law. If you write a law where you get money for laying roads - this error occurs (you cannot build or remove roads). If there is no law about this, road building works without any problems.

Best regards

![ecostreet](https://user-images.githubusercontent.com/54618826/106718256-16e46780-6601-11eb-9acc-32bfea8928cc.jpg)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/106727112-3210a080-661c-11eb-8eab-f327bffac8da.png)
