### ISSUE TITLE
Fix PR comments on property claiming

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20320]
https://github.com/StrangeLoopGames/Eco/pull/7707#pullrequestreview-581647750

Lets discuss how it could be done in a bulk action. We need to add this ability to actions in general in the game.

**Comment by SlayksWood** [comment]
#20199

**Comment by SlayksWood** [comment]
https://www.dropbox.com/s/mto3lvjlfiif4yd/Storage.zip?dl=0
world to test.
