### ISSUE TITLE
Stone Builder doesn't respect solid blocks above it properly.

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2033]

**Comment by Conchipedia** [comment]
![snap038](https://user-images.githubusercontent.com/29383891/29902013-5ed612a8-8df3-11e7-9c16-825c4ef04d15.png)

**Comment by Conchipedia** [comment]
the showing through piece makes player jump just a fraction when walking over but a cart seems to just go over without out any noticable difference.

**Comment by keegan-o** [comment]
It's a problem with the builders not thinking the ramp is a solid object. This may be due to the chunk not updating too.

**Comment by Conchipedia** [comment]
just seen this in 6.3.1 with coal
![snap949](https://user-images.githubusercontent.com/29383891/34654840-dfc0b56a-f3f8-11e7-967b-0213bffac231.png)
so looks like still needs the Artwork tweaked a bit, i don't remember these weird surface bumps in earlier versions
![snap950](https://user-images.githubusercontent.com/29383891/34654854-32392cc8-f3f9-11e7-9a9c-60dd3b41b423.png)
