### ISSUE TITLE
Industrial Elevator cant lift Excevator on dedicated Server

### ISSUE THREAD

**Issue by ZEROX7** [StrangeLoopGames/EcoIssues#20330]
hey there so i just installed my elevator and now i cant get the elevator up with the excevator on it

**Comment by Lamargo** [comment]
Also having this issue. The elevator does attempt to go up, but it's a fraction of a block at a time. Repeatedly choosing Up will get you raised eventually. Descending is no problem. Have tried emptying the excavator of inventory, changing boom/arm angles, but this doesn't affect it. It feels like it is detecting something directly in its path. Is the elevator moving and updating the vehicles afterwards so thinks the excavator's wheels are in the way?

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 268
