### ISSUE TITLE
USER ISSUE: cant create single player

### ISSUE THREAD

**Issue by DPWBFG** [StrangeLoopGames/EcoIssues#20339]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.3 beta release-150

**Steps to Reproduce:**
im trying to host world an keeps saying connection failed. i have the latest NET installed too??

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login failed
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@DPWBFG Thank you for reporting. 
 Please provide your server logs and player logs as detailed in the instructions.
 Also please state your localization (language settings for the game) and your operating system.

**Comment by IcedForge** [comment]
Closing this in lack of reply.
