### ISSUE TITLE
USER ISSUE: Glass Windows casting strange shadow on big glassfront

### ISSUE THREAD

**Issue by 0llowain** [StrangeLoopGames/EcoIssues#20334]
![20210203120639_1](https://user-images.githubusercontent.com/78479243/106738553-59656e80-6618-11eb-9456-53dfdcca0a32.jpg)
![20210203120645_1](https://user-images.githubusercontent.com/78479243/106738556-59fe0500-6618-11eb-8595-cf20572f8a60.jpg)

**User Id: (Not logged user)**
**Version:** 0.9.2.3 beta release-150

**Steps to Reproduce:**
Create a glass windowfront of atleast 5-6 Blocks length.
Just take glass blocks of type "window" and arrange them in a big "wall" 

**Expected behavior:**
The whole big window should be smooth and transparent

**Actual behavior:**
after 5-6 Blocks there is a vertical "shadow" through the whole height of the window. It looks like a bug in raytracing / lighting process. It does not look natural and its not very esthetic.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@0llowain Thank you for the report. We know about this problem.
merged to #18617
