### ISSUE TITLE
[9.3] New Tag Icons

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20335]
We need some new tag icons, specifically one for different 'Aquatic Carcasses'-- I'm thinking a clearly dead fish will do for this for now, it can be used on all sizes most likely since that's how the other carcasses work for terrestrial animals.

We also need a Clothes tag icon.

- [x] Aquatic Carcass Tag Icon
- [x] Clothes Tag Icon

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0146c21f-028a-4dbd-b51c-e7862f4f9dc5)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/606ed02b-ac07-4140-9549-f6373b1fd9fa)is research basic the same thing as research?

**Comment by keegan-o** [comment]
Sorry I should avoid posting un-needed screenshots, this task is just for aquatic carcass and clothes tag icons. Not sure about the research tag or if we actually need that for anything.

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/8bea6aa0-dbba-42e7-bc5b-9de489f41cea) clothes and aquatic carcass tag are check into develop and assigned
