### ISSUE TITLE
Store UI

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20331]
Ideas for Store UI Rework:

**Drag & Drop System:**
Gives the store the possibility to arrange the list by drag & drop.
Best Example would be the current System how you change the Order from Storages.

**Groups:**
The Player can create and name Groups for the Store List.
The respective items can then be dragged into the desired group.
Which you can then fold when shopping when they are not needed.

Maybe add a System to autogroup the items with the matching Tag.

![grafik](https://user-images.githubusercontent.com/37456949/106727778-1ac9b700-660c-11eb-90e6-d066344d2859.png)

**Comment by SlayksWood** [comment]
#13558
> This is just quality of life request.
> Rearranging store goods by clicking at up\down buttons is annoying...
> Please add "draggable" region, where store owner can grab row and drag onto new position.
> 
> ![e752272a004b062313848ed82a2d8796](https://user-images.githubusercontent.com/4980243/67595005-49e94b80-f76e-11e9-9894-34d8564ef7d0.gif)

**Comment by SlayksWood** [comment]
merged to #20365
