### ISSUE TITLE
[9.2.3] District Map cannot be renamed or colour changed

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20344]
![image](https://user-images.githubusercontent.com/47274045/106819217-c3fac680-6679-11eb-830e-6864eb1b632b.png)
It is not possible to rename a district inside a map. further, it does not matter what color you choose for the first district it will be always overwritten with a default value.

as mentioned in one of my other issue reports, the count behind any government object with +1 all the time you change something is mega frustrating. ;-)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are already aware of this issue.
#20287
