### ISSUE TITLE
Not possibile to get UI in reasonable size

### ISSUE THREAD

**Issue by Bullhill** [StrangeLoopGames/EcoIssues#20341]
When playing in resolution 5760x1080 the UI scale after with of screen and not height of screen. That result in the UI it getting very big, even on smallest settings. On image is interface scale set to 60%
![20210203212137_1](https://user-images.githubusercontent.com/17889566/106805168-a4a66e00-6666-11eb-8832-a01ce4e39377.jpg)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
I can confirm that the scaling of the GUI becomes too large at ultrawide resolution even at 60%.

**Comment by SlayksWood** [comment]
merged to #16535
