### ISSUE TITLE
[9.2.3] cannot start election

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20345]
![image](https://user-images.githubusercontent.com/47274045/106820870-6ae06200-667c-11eb-9385-6e20104f2246.png)
Position Object is not set error occurs even I have selected a position, so I cannot start the election...

**Comment by IcedForge** [comment]
Thank you for reporting, duplicate from #20315 and should be fixed in the upcoming 9.2.4 hotfix.
