### ISSUE TITLE
Executive Actions Bugs (9.2.3)

### ISSUE THREAD

**Issue by Simon8198** [StrangeLoopGames/EcoIssues#20340]
Hello,

I am currently getting two bugs on Eco when using Executive Actions I fill in the Action Title and the "Actions To Run Once" however I get a red exclamation mark next to the execute button saying they are not filled in and won't let me press the button.

The second problem happens when I close the executive actions menu by pressing escape after I have the above problem.
When I try to reopen the executive actions menu it will no longer let me press the green plus symbols.

The only way to fix this from what I've seen is to restart the server. 

![ExecAction](https://user-images.githubusercontent.com/13318213/106797120-20e38600-6654-11eb-85a3-58898a34e194.PNG)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Comment by Venopsis** [comment]
Hi,
Try to close the window.
Re-open the draft.
Do you still encounter the red marks?
If yes, ty disconnect/reconnect to server? What's the result?

We are few people to notice laws and co issue. All seems related to UI loading info issue. 

Check issue #20315 and mine #20318 .

**Comment by Simon8198** [comment]
Hello Venopsis,

According to someone else on the server closing and reopening does work for other goverment systems such as laws and also contracts. 
The problem with executive actions from what I know there is no draft.
Disconnecting and reconnecting does not fix the issue. Only restarting the server it self fixes it.

**Comment by SlayksWood** [comment]
@Simon8198 Thank you for the report. This should be fixed with in 0.9.2.4. #20315

**Comment by ULiX80** [comment]
But the bug is not fixed in 0.9.2.4.
I still cannot perform the executive action.
