### ISSUE TITLE
USER ISSUE: Unable To click on items

### ISSUE THREAD

**Issue by Whitestar23** [StrangeLoopGames/EcoIssues#20358]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Admin Command to add land with blocks over 15x15

**Expected behavior:**
To use everything

**Actual behavior:**
Cant use vehicle or pick animals 5 above and below height of the spawned area across whole map

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Whitestar23** [comment]
Fixed by going back to older backups

**Comment by IcedForge** [comment]
@Whitestar23 Thank you for reporting, I would need to know exactly which command you were using?
As using /bt or /bm will generate invisible blocks if you do not use correct syntax and these will act as actual blocks so interacting through them would not be possible?

Will drop this issue into need information please reply with any further information or if this answer was enough to fix your issue close the issue on your own.

**Comment by Whitestar23** [comment]
Hello, I used the / level 15,15 command to flatten an area @ 335,71,765. After I did this could not interact with vehicles, animals, elevaterbut could still use work bench, stockpiles. Once I went below 65 height everything returned. This has now happed 3 time each time I have to restore and back up to fix. Thank youRossRoss underhillOn 5 Feb 2021 06:00, Jens <notifications@github.com> wrote:
@Whitestar23 Thank you for reporting, I would need to know exactly which command you were using?
As using /bt or /bm will generate invisible blocks if you do not use correct syntax and these will act as actual blocks so interacting through them would not be possible?
Will drop this issue into need information please reply with any further information or if this answer was enough to fix your issue close the issue on your own.

**Comment by IcedForge** [comment]
Could you upload your player logs when this occurs if it happens again?

**Comment by Whitestar23** [comment]
Hello, Yes that I can do. If you like I can try to recreate over the next few days as I now the fix is to restore backup so not an issue to fix. Logs from the log folder? Ross underhillOn 8 Feb 2021 15:39, Jens <notifications@github.com> wrote:
Could you upload your player logs when this occurs if it happens again?

**Comment by IcedForge** [comment]
Will close as fixed by backup.
