### ISSUE TITLE
trying to dump stone in a cart with shovel will not let me if its not an exact number free space

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2035]

**Comment by Conchipedia** [comment]
i have a cart with 20 stone and 12 stone total weight 960kg /1500kg and trying to dump into cart with shovel the held stack will not round up the stacks as previously to an exact weight allowed, if i drag it manually to an empty it will update the weight to the maximum allowed but not place them in stacks of 20 and whatever is left over. Snap041 shows what i have already in cart, Snap042 shows what i get after dragging the stack of 20 to an empty slot. (doing this if Pictures show in wrong order) what i should see is 1st slot 20, 2nd slot 20 and the final slot 10, even dragging one on top of the other does not turn them into stacks of 20's like they used to but just swaps the slots around.
![snap041](https://user-images.githubusercontent.com/29383891/29902968-35d64304-8df9-11e7-8182-b08591937538.png)
![snap042](https://user-images.githubusercontent.com/29383891/29902977-407723d2-8df9-11e7-9d03-5404e186e172.png)

**Comment by Senbotsu** [comment]
The same occurs with logs.

**Comment by metachronism** [comment]
fix pending
