### ISSUE TITLE
Interface Scaling issue on 21:9 and 32:9 monitors

### ISSUE THREAD

**Issue by NubsMcGee** [StrangeLoopGames/EcoIssues#20352]
It seems the Interface Scale percentage is based off the games horizontal resolution.

This becomes problematic when a user is using a monitor that is Super Ultrawide (32:9) as the Interface will be twice as large as it would be on a common 16:9 monitor.

A common solution for FOV and GUI/HUD/Interface scaling issues in games on 32:9 monitors is to have the slider be based off of the vertical resolution rather than the horizontal resolution.

In theory, using the vertical resolution would result in the same interface size on 16:9, 21:9, 32:9 monitors and even multi-monitor setups.

If it's problematic to use the vertical resolution, simply providing a plain text variable in a config/ini file that can be edited by the user to define an Interface Scale % lower than the slider allows in the game settings menu (Currently the minimum is 60%) would at least be enough to get by on.

Using such a niche monitor resolution means these kinds of quality of life issues are overlooked and many times it simply doesn't occur to the devs that this might be an issue. Editing config files is something many passionate gamers that own ultrawide monitors are used to doing and it can sometimes be an easy way for developers to offer a workaround solution whiteout needing to do work on their menu systems in game.

I'm attaching two comparison images to help better understand the problem. The first one will be running the game at 2560x1440 on my 5120x1440 monitor with 60% Interface Scale (Hence the black bars on the sides).

The second image will be using 5120x1440 on the same setting of 60% interface Scale.

You'll notice I can see less than half the amount of inventories in my interface which means spending lots of time scrolling searching for the right one, then dragging the object while scrolling and trying to find the destination.

It's tedious and frustrating and it would really save a lot of headaches if you could look into it.

If you don't have access to a double wide monitor to test on, you can use two side by side 2560x1440 monitors and span the game across them.

https://i.imgur.com/dHr2Lk3.jpg

https://i.imgur.com/SwcvpOh.jpg

I really love the game and you guys are doing great work! Please consider trying to find a solution for us often overlooked niche with wider than normal resolutions. It would be greatly appreciated.

**Comment by SlayksWood** [comment]
@NubsMcGee Thank you for the report. Yes, we have already encountered this problem. merged to #16535
