### ISSUE TITLE
USER ISSUE: Failed to connect to server

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20350]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Click Continue, and wait for the server to load.	

**Expected behavior:**
Connect to work.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, No clue, but never happened Prior to the update.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@sirPattrick Thank you for the report. We need more details to investigate your problem:
1. Are you trying to connect to specific server or having this issue with every server?
Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System and its version).
6. Did you meet this issue after updating to the "latest build" or you had it before?

**Comment by sirPattrick** [comment]
1.  It was a specific server.  I had never had connection issues in the past.  Last night after downloading 9.2.4 I tried 3 times to connect.  The first 2 brought up that error message, Finally on the third attempt I connected.
2.  The server info looked fine.  I didnt go into the full list, but I clicked continue, but from what I could tell, it had all the standard info, 9 users online, what day it was, the ping,etc.
3. Windows defender is used, and has never caused an issue in the past.
4. The laptop uses Wifi.
5. It is a pretty cheap windows laptop from Walmart.  It struggles to load the game, but has never failed to connect like that.
6. I meant after downloading the new update, 9.2.4.  The owner of the server kicked us all out, we all updated, I waited like 20 minutes, connected, and twice I received that error.

**Comment by mirasrael** [comment]
@sirPattrick did you have other connection timeout issues after 3rd attempt? Or it was only for first 2 attempts?

**Comment by TwixterZ** [comment]
@sirPattrick did this issue eventually came up again on your girlfriend system or yours?

**Comment by sirPattrick** [comment]
I think we saw it once or twice.  But that was it.  I havent been playing much, work is taking up all my time at the moment.

**Comment by TwixterZ** [comment]
@sirPattrick, thank you for your response, we hope to see you get back into the game soon =)

I will close this issue now.
