### ISSUE TITLE
[9.2.4] Treasury Account cannot be used within Elected Title wages

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20354]
![image](https://user-images.githubusercontent.com/47274045/106872599-c2f68300-66d3-11eb-839e-990805d7b358.png)

Even i have full treasury banking access, i cannot set Treasury as Wages Source Bank Account within Elected Title.

**Comment by Alteraner** [comment]
It seems cannot be accessed by any government wages. When I try to set up wages within the demographic it is not working either.

**Comment by sirPattrick** [comment]
I also couldn't access it as the source for contracts.

**Comment by jamesyoung79** [comment]
From what I've noticed it seems to have issues with titles and demographics accessing accounts.
