### ISSUE TITLE
Invisible cactus in road blocking vehicle use and can not be cut down

### ISSUE THREAD

**Issue by killerpotatox-x** [StrangeLoopGames/EcoIssues#20351]
I play on a small private server with friends, this bug occurred on the version 9.2.3. When trying to drive through the dirt road that was put down 5 minutes prior we were blocked by something we couldn't see. We restarted the server (my husband runs it on his computer) and the issue was still in our way after reboot. I was able to place mortared stone in the same spot as the invisible cactus but not drive though it when visibly clear. I want through my tools to see if it was something I couldn't see and sure enough it was a cactus. I chopped at it for a while but it wouldn't chop down. we dug out more road around it to just drive around it, after a while it disappeared.

https://user-images.githubusercontent.com/78524779/106850005-935e6100-6668-11eb-9c79-d8c0b5d53867.mp4

.

**Comment by SlayksWood** [comment]
@killerpotatox-x Thank you for the repport. Can you provide save files  when this cactus still exists? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by killerpotatox-x** [comment]
I'm only seeing my personal game files and not the files for the server I
played on with the cactus issue. Should I get the server file from computer
that runs the server?

**Comment by Thibault-Brocheton** [comment]
We do have similar issue in our world too (don't know if it's a cactus or something else):
https://drive.google.com/file/d/1MZpIDKOFbOxVkT5TJ07n8bcuMj1H0wPR/view?usp=sharing
Location: 698,458
on the map we see a cactus, not in the world

**Comment by TwixterZ** [comment]
related to issue under [#20040](https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/20040)

Closing this issue, to follow-up on above issue instead
