### ISSUE TITLE
[9.2.4] Dual Permissions / Manager Set Error in Government System with object references.

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#20361]
I'm not quite sure, what this error tells me, but seams again it is facing a lot of reference issues with the current approach to always create a new instance of an government object as not all reference are been updated and some still point to the old one.

Below you can see, I had to update a elected title with some wages. The second picture shows the "#general" log throwing some errors. i assume it refers to one of my old issues I reported as the removed title still gets triggered during government tick.

The first picture shows an error when I'm setting up a demographic with title requirement using these updated elected titles. in the frontend i only see the newest title but seams in the backend it still refers to the old one wich comes down to this error.

![image](https://user-images.githubusercontent.com/47274045/106943649-fbbf4800-6725-11eb-8178-d6fb16376614.png)

![image](https://user-images.githubusercontent.com/47274045/106943679-0974cd80-6726-11eb-83bc-7675fa880f04.png)

Once again I strictly recommend to change your approach. This will solve a lot of your government problems. Do not replace an old government object with an new one and hope all references are updated well. Keep the existing one with its reference id, make a copy of these object and flag this with new id as old one and just update the existing one with the new values.

For now I will try to delete the old elected titles by admin command and hopefully this will help to get the demographic been setup.

**Comment by Alteraner** [comment]
After i deleted and restored some Objects, the bank accounts permissions are not been updated with the new reference to elected titles.

**Comment by IcedForge** [comment]
I agree with this.

When you draft an article, it can create a new draft id entry and once the object is enacted it should copy old content into a new id and completely replace the contents of the original ID as this would eliminate any potential problems with reference updates as it would never need to actually change the id its pointing towards unless its removed from its slot completely. Which means as long as its only replacing / updating it keeps the same id.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1955.

The old government object has now a reference id.

![reference](https://user-images.githubusercontent.com/77248866/111403390-d69bfd00-8707-11eb-84af-a5a2de5e5f86.jpg)

Closing.
