### ISSUE TITLE
Notifications for halted job drowning my chat window.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20368]
![image](https://user-images.githubusercontent.com/36024353/106966410-e0930f00-670a-11eb-860f-6da707c6278b.png)
The notifications keep popping up every 2 or so seconds.  It seems like the job thinks it received new materials even though it didn't, and then immediately halts again.  I haven't really had this issue until after 9.2 update.

**Comment by IcedForge** [comment]
@sirPattrick Thank you for reporting this.
Looks like a morphed variation of this issue #19420 and #16748

**Comment by SlayksWood** [comment]
> The ashlar stone projects are constantly spamming the notification bar that they are out of resources. See screenshot
> 
> **Version:** 0.9.0 staging-1605
> Steps to reproduce:
> 
> 1. Start an ashlar stone project in an advanced masonry table
> 2. Let it run out of resources
> 3. Check notification bar
> 
> **Expected behavior:** Notice once then stop and then notify again if a resource is added and it then runs out like all other crafts
> **Actual behavior:** Constant notification that it is out of resources even though no resources are added or withdrawn
> 
> [playerlog.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4798276/playerlog.zip)
> ![ashlar_spam](https://user-images.githubusercontent.com/39825431/85016437-0367b780-b16a-11ea-9630-a77e8c672591.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 250
