### ISSUE TITLE
0.9.2.4 Redwood Trees - wrong set of leaves falling when chopping branches

### ISSUE THREAD

**Issue by AquatikJustice** [StrangeLoopGames/EcoIssues#20366]
Fairly straightforward bug.

When you chop a branch of a standing redwood tree, the leaves that fall off are actually the ones 90° to the left of the branch.

![382310_20210204163945_1](https://user-images.githubusercontent.com/4640482/106964746-3619ec80-6708-11eb-8ac5-99a2c5228027.png)

**Comment by Lyrcaxis** [comment]
The LOD0 Mesh was not rotated properly on 'Redwood Leaves.prefab'.

Fixed and pushed into the 'trunk' branch in SVN.

**Comment by TwixterZ** [comment]
issue is fixed as of 9.4 develop-225
