### ISSUE TITLE
too much resources given from stone block and recipes not changed to reflect this new massive amount of items

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2036]

**Comment by Conchipedia** [comment]
If a recipe asks for 10 stone i would have to dig out 10 stone blocks in previous version, now that i get 4 stone from one block shouldn't the recipes now ask for 4 times the previous amount required? This seems to me to Not encourage players to mine like we had to in the previous versions, we will also get the same use less stone for higher Efficiency, but unless the stone recipes are increased with the amount needed, there is no point in getting a higher efficiency as we will always have too many easily gotten stone.

**Comment by EmuLegs** [comment]
maybe that is why they changed it, because the amount of stone you needed to collect was a pain?

**Comment by Senbotsu** [comment]
I would say the resources are already plenty high.   IE a stone tool (to craft, not repair) takes 20 stone with no efficiency rating.  Even the most novice survivalist could figure out how to lap a stone axe before burning through that many rocks :P

**Comment by craig-jong** [comment]
All stoneworking is going through changes. Most recipes need to be modified.
