### ISSUE TITLE
Skid Steer "dump" mechanic causes occasional issues

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoIssues#20379]
When you are using the skid steer (v 0.9.2.4) and you are dumping out material that has been picked up, if you hold the dump key and don't move it can begin placing the resource under the vehicle and therefore cause odd movement of the vehicle.

1) Pick up some resource with the skid steer
2) Try to continuously dump resource
3) Note that eventually dumping causes resource to appear below the vehicle thus moving the vehicle around

video: https://youtu.be/NYs60SefY0Y

slgid: slg188711 (primarily a steam user, fyi, I don't know how Steam/SLG accounts are linked so not sure if the icon will credit appropriately in both places)

PS: sorry about the bag ticket, I had searched "bag" and not "backpack".

**Comment by SlayksWood** [comment]
#8206

**Comment by SlayksWood** [comment]
merged to #12620
