### ISSUE TITLE
[0.9.3 develop-177] Missing part of bar in Skills UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20371]
0.9.3:
![image](https://user-images.githubusercontent.com/45708377/107016723-551f8980-67af-11eb-992c-93560782033a.png)
0.9.2:
![image](https://user-images.githubusercontent.com/45708377/107016751-5e105b00-67af-11eb-8e8a-6a92a32b2848.png)

**Comment by tuha263** [comment]
@johnkslg requested to update (remove the red bar) by then @RobertMangano did it. So scaled the bar to make it continuative.
![Uploading LevelBar.png…]()
