### ISSUE TITLE
[0.9.2 release-158] Can't change 'Online/Online and Offline hours' in wages after submit.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20372]
It changed visually but still pay with first settings. Step to reproduce:
- create a title with online payment:
![image](https://user-images.githubusercontent.com/45708377/107026004-332c0400-67bb-11eb-8918-632b1776262c.png)
- add 2 users to this title. Devqa - online and Test Client 1 - offline.
- check payment:
![image](https://user-images.githubusercontent.com/45708377/107026309-91f17d80-67bb-11eb-86ae-f713f67b2403.png)
- open advanced title settings and change online to online and offline:
![image](https://user-images.githubusercontent.com/45708377/107026383-ae8db580-67bb-11eb-8b30-d523623effd9.png)
- submit and check payment. It still pay only for online hours:
![image](https://user-images.githubusercontent.com/45708377/107026485-d1b86500-67bb-11eb-9897-f035b442ca01.png)

**Comment by tomsseisums** [comment]
@SlayksWood fixed it, and the fix also applies to the same issue preset on Demographics & Rent.

While fixing, I found places for more potential fixes:
- Both Wages/Rent are updated immediately not waiting for Submit button to be clicked in the UI.
- Updating something and clicking Close button in the UI won't reset.
- In other words, Submit and Close buttons actually do nothing.

Another one is that these changes will propagate only on EconomyManager Tick, which is statically set at 5 seconds. While it doesn't affect functionality much, the notifications sent to the players will be delayed by that amount of time. I don't know whether that can be counted as an issue or not, 5 seconds in an MMO is almost like instant anyways..

**Comment by tomsseisums** [comment]
John already made a separate issue for remaining improvement MVP: https://github.com/StrangeLoopGames/EcoIssues/issues/20520

**Comment by SlayksWood** [comment]
@tomsseisums Seems this is fixed but I have another problems now, perhaps one of them doesn't related with you changes.

**Comment by SlayksWood** [comment]
Closed this one and create another one.
