### ISSUE TITLE
[0.9.2.3] Stuck in Wood Cart if third person and no backpack

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#20373]
A player of my server experienced the following bug: He is stuck in his wood cart, unable to leave it.

Steps to reproduce:
- Start a new world
- Put your backpack to your inventory
- Spawn a Wood Cart
- Go in Third Person view
- Ride the Wood Cart

You'll be stuck without possiblity to leave it

Player.log of the user:

[Player (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5932137/Player.1.log)

precise issue:

```NullReferenceException: Object reference not set to an instance of an object.
  at MountSpot.BackpackActivate (System.Boolean isActive) [0x00000] in <00000000000000000000000000000000>:0 
  at MountSpot.DisMount (PlayerBase player) [0x00000] in <00000000000000000000000000000000>:0 
  at Player.set_Mount (MountSpot value) [0x00000] in <00000000000000000000000000000000>:0 
  at ThirdPersonController.RefreshThirdPerson () [0x00000] in <00000000000000000000000000000000>:0 
  at Player.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: currently not available on il2cpp Line: -1)

Animator.GotoState: State could not be found
UnityEngine.Animator:Play(String)
AvatarAnimationManager:InitState()
AvatarAnimationManager:Start()

[ line 1349] 
(Filename:  Line: 1349)

Invalid Layer Index '-1'
UnityEngine.Animator:Play(String)
AvatarAnimationManager:InitState()
AvatarAnimationManager:Start()```

**Comment by IcedForge** [comment]
@Thibault-Brocheton Thank you again for finding this one !
You can send your slgid to dennis in a pm on discord if you havent already gotten an bug icon reward.

**Comment by IcedForge** [comment]
Problem is most likely caused by the backpack removal when mounting a vehicle so just  nullcheck for making the animator skip in case you dont have a backpack?

**Comment by SlayksWood** [comment]
Also works with chairs and benches.
