### ISSUE TITLE
[9.2.4] Zoning Table Name Issues

### ISSUE THREAD

**Issue by Simon8198** [StrangeLoopGames/EcoIssues#20378]
The naming on the zoning table do not stick.

Steps to reproduce:
- Create a zone and try to name the entry
- Save and zone gets voted through.
- Zone no longer original name but default "District" name

Even when the actual name does stick. Whenever you revise the district map it increases the number on the name. Even if you dont want the number.

![ZoningTable](https://user-images.githubusercontent.com/13318213/107053530-d33b5a80-67c6-11eb-9803-6c889d1fc289.PNG)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are already aware of this issue.
#20287.
