### ISSUE TITLE
Player able to move vehicle from outside

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoIssues#20381]
I have run into this quite a few times, but it doesn't seem to be 100% reproducible.  I listed the steps below that work most of the time.

1) Place a vehicle in a space that  has some room around it (not a cart)
2) Sprint into the vehicle and then walk around a corner of it
3) Note that the vehicle is moved from its original position.

video: https://youtu.be/pXl3VybwTOg
In the video you can see once where it affected the pivot of the vehicle and actually lifted the front wheels off the ground, but in the primary example you can see me sprinting into the back of the vehicle and then rounding the corner and the vehicle actually flips over

slgid: slg188711 (primarily a steam user, fyi, I don't know how Steam/SLG accounts are linked so not sure if the icon will credit appropriately in both places)

PS: sorry about the bag ticket, I had searched "bag" and not "backpack".

**Comment by Daniel-Magulado** [comment]
Hello @JestinJae 
I'll be merging this with https://github.com/StrangeLoopGames/EcoIssues/issues/14761.
