### ISSUE TITLE
USER ISSUE: Arrastra

### ISSUE THREAD

**Issue by Carsi-83** [StrangeLoopGames/EcoIssues#20384]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Place upgrade in the Arrastra Upgade slot. (Mining basic Upgrade)

**Expected behavior:**
Cost reduction by 50%

**Actual behavior:**
No reduction at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Eco is best in Vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5935322/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5935324/Player-prev.log)

**Comment by D3nnis3n** [comment]
This works as intended.
