### ISSUE TITLE
USER ISSUE: Disappearing Wood Cart

### ISSUE THREAD

**Issue by Wattamaker** [StrangeLoopGames/EcoIssues#20383]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Attempt to place a cart in a tight area with lots of growth. I placed mine next to a huge old growth redwood.

**Expected behavior:**
Removed cart from inventory and placed the cart.

**Actual behavior:**
Removed the cart from inventory and did not place the cart. Causing the cart to just disappear.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Wattamaker** [comment]
Correction: The cart did not disappear, it was catapulted about 500m from where it was placed... Into an ocean.

**Comment by SlayksWood** [comment]
@Wattamaker Thank you for the report. It always happens with your cart? Can your make a video or screenshots?

**Comment by TwixterZ** [comment]
closing this issue due to lack of response and similar case reported as referenced above.
