### ISSUE TITLE
Add a way to remove specialties

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20388]
Add a way to remove specialties.  Refund a given % of the amount of XP it cost.

**Comment by gzatravkin** [comment]
So should it be just chat command? With which level of access? 
Or maybe some building\gov action?

**Comment by Mattprass** [comment]
task plan:
https://docs.google.com/document/d/1LMJ25llG3grxcfeEcxRnt1UE2HtrzxgRhpwB5iBzNb0/edit#

**Comment by Mattprass** [comment]
first phase merged into 9.5.

currently working on second phase as detailed in design doc
