### ISSUE TITLE
Improve filtering 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20399]
Apply the same super-cool filter prefab made here: 
https://github.com/StrangeLoopGames/Eco/pull/8643

To the economy viewer, replacing the existing one.

**Comment by TwixterZ** [comment]
Feature observed and confirmed as of 0.9.5 Develop-305

![filter2](https://user-images.githubusercontent.com/78054747/122663052-4a97e680-d1ca-11eb-88fd-8428ee8bb898.gif)
