### ISSUE TITLE
USER ISSUE: Map Doesn't Follow While Pulling Cart

### ISSUE THREAD

**Issue by Paultagoras** [StrangeLoopGames/EcoIssues#20397]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1.Set map to follow player.
2. See that it works (even while pulling cart)
3. Move map manually with mouse dragging
4. See that it stops following
5. Leave cart and move, map will follow player again

**Expected behavior:**
Followed me, even while pulling the cart

**Actual behavior:**
Doesn't, and stays frozen on where I left it

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Paultagoras Thank you for the report. Merged to #7853
