### ISSUE TITLE
Chat cannot be scrolled back a lot, no way to see what people chatted an hour ago if the chat was active. Chat is still jumping sometimes.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20395]

**Comment by gzatravkin** [comment]
Check it at live server (like White Tiger at steam).

**Comment by johnkslg** [comment]
Joe recently added some scrolling optimization for chat that may be relevant here, chat to him

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 259.
