### ISSUE TITLE
Yet Another White Tiger Crashloop

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20404]
--BEGIN DUMP--
Dump Time
02/06/2021 13:39:33

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.RentForProperty.ValidateAndGetFeeInfo(User user)
   at Eco.Gameplay.Property.Residency.BecomeResident(User user)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--

------
Log (Crash not in Log)
[log_210206031509.log](https://github.com/StrangeLoopGames/EcoIssues/files/5936817/log_210206031509.log)

**Comment by MonzUn** [comment]
Do you feel that you have the information you need on this crash?
We just had it on my server and a user managed to reproduce it, so I could give STR and our world file if you would find that helpful :)

**Comment by serpopov** [comment]
@MonzUn yes, would you kindly ;)

**Comment by MonzUn** [comment]
I think this is reproducible on any world, but I've linked the world file below:

STR:
1. Enable experimental rent feature in the server settings.
2. Start and join the server.
3. Open the Economy view and the Rent tab.
4. Click "RentHouse1"
5. Click "Become Resident"
6. When prompted to select an account, DO NOT select an account.
7. Accept to become resident.
8. Observer the server crash.

World file
https://drive.google.com/file/d/11W_wCl6P5wvu7JvmwXh9GQREaj7NKdSy/view?usp=sharing
