### ISSUE TITLE
USER ISSUE: Alex

### ISSUE THREAD

**Issue by LouLou68200** [StrangeLoopGames/EcoIssues#20408]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by MishkaFur** [comment]
Purchase the game.
