### ISSUE TITLE
9.2.4 Server log  Can't send string as localizable, because it has too many arguments

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20405]
WT and my server (probably also others) gets this in the log seemingly at random not able to reliably repro it but I am assuming its due to a bank or economy viewer due to the content.

This has only been happening that I can tell since 9.2.3, no evidence of this in 9.2.2 log files

[15:24:28.848] [39] [ Warn] [Eco] Can't send string as localizable, because it has too many arguments: 430. Max: 382. Converted to server-localized string: "

it shows the below somewhat then starts going to workbenches

```
[15:24:28.848] [39] [ Warn] [Eco] Can't send string as localizable, because it has too many arguments: 430. Max: 382. Converted to server-localized string: <b><link="ref:BankAccount:430"><ecoicon item="EconomyViewerItem"><style="BankAccount">Supervu's Empire Holdings Co.</style></ecoicon></link></b>: <pos=500><style="Currency">9,382.58</style></pos>
<b><link="ref:GovernmentBankAccount:168"><ecoicon item="EconomyViewerItem"><style="BankAccount">civil engineering</style></ecoicon></link></b>: <pos=500><style="Currency">8,947.73</style></pos>
<b><link="ref:PersonalAccount:3"><ecoicon item="EconomyViewerItem"><style="BankAccount">Mishka Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">8,703.6</style></pos>
<b><link="ref:PersonalAccount:72"><ecoicon item="EconomyViewerItem"><style="BankAccount">Donutathome Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">5,791.29</style></pos>
<b><link="ref:BankAccount:532"><ecoicon item="EconomyViewerItem"><style="BankAccount">WhiteWolf Industries</style></ecoicon></link></b>: <pos=500><style="Currency">5,612.69</style></pos>
<b><link="ref:PersonalAccount:1956"><ecoicon item="EconomyViewerItem"><style="BankAccount">PainCrafter Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">5,522.25</style></pos>
<b><link="ref:TreasuryBankAccount:1"><ecoicon item="EconomyViewerItem"><style="BankAccount">Treasury Bank Account</style></ecoicon></link></b>: <pos=500><style="Currency">4,960.18</style></pos>
<b><link="ref:PersonalAccount:692"><ecoicon item="EconomyViewerItem"><style="BankAccount">Bad_karma Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">4,305.99</style></pos>
<b><link="ref:PersonalAccount:611"><ecoicon item="EconomyViewerItem"><style="BankAccount">b0008.de Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">4,192.2</style></pos>
<b><link="ref:PersonalAccount:1159"><ecoicon item="EconomyViewerItem"><style="BankAccount">mike.zach86 Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">4,074.84</style></pos>
<b><link="ref:BankAccount:434"><ecoicon item="EconomyViewerItem"><style="BankAccount"><color=red>Chub</color><color=white>way</color></style></ecoicon></link></b>: <pos=500><style="Currency">3,952.25</style></pos>
<b><link="ref:PersonalAccount:326"><ecoicon item="EconomyViewerItem"><style="BankAccount">all-sl Personal Account</style></ecoicon></link></b>: <pos=500><style="Currency">3,819.32</style></pos>
<b><link="ref:BankAccount:1182"><ecoicon item="EconomyViewerItem"><style="BankAccount">Oil Tycoon Gavino Co.</style></ecoicon></link></b>: <pos=500><style="Currency">3,721.26</style></pos>


<b><link="WorldObject:8ad57bdf-911e-4421-bb3e-00a18658730d"><ecoicon item="Workbench">Workbench</ecoicon></link></b>
<b><link="WorldObject:b9458ad2-d991-4c64-9be5-4bf27bd2d0e8"><ecoicon item="Workbench">b.fix's Workbench</ecoicon></link></b>
<b><link="WorldObject:20e54bd2-c674-48a3-a828-a201250c686f"><ecoicon item="Workbench">Workbench</ecoicon></link></b>
<b><link="WorldObject:0a96db13-a64d-4b79-bc4d-22c469ef1c17"><ecoicon item="Workbench">b.fix's Workbench</ecoicon></link></b>
<b><link="WorldObject:fb4730b3-6b66-4217-b607-a76437d147cb"><ecoicon item="Workbench">Reclaimed Property's Workbench</ecoicon></link></b>
<b><link="WorldObject:bf49e30c-ec3e-4c50-a84e-e424a2a6075a"><ecoicon item="Workbench">Workbench</ecoicon></link></b>
<b><link="WorldObject:a522b68f-70c0-4f82-8308-95ac0afdd192"><ecoicon item="Workbench">Reclaimed Property's Workbench</ecoicon></link></b>
<b><link="WorldObject:cce7f3fa-93c6-42e3-9959-db367e1f708f"><ecoicon item="Workbench">Reclaimed Property's Workbench</ecoicon></link></b>
<b><link="WorldObject:7a1810b0-d8f6-4d17-955e-38a1e4548c98"><ecoicon item="Workbench">Workbench</ecoicon></link></b>
<b><link="WorldObject:0ea1c640-6e57-4b78-85de-05f2d0d1169b"><ecoicon item="Workbench">Cobra Phantom's Workbench</ecoicon></link></b>
<b><link="WorldObject:a86e0bb0-ceec-4072-ba49-ea2afffb6b2c"><ecoicon item="Workbench">Wufei's Workbench</ecoicon></link></b>
<b><link="WorldObject:9104cf65-b16a-4600-84df-12bf3c9b10e1"><ecoicon item="Workbench">WortNerve's Workbench</ecoicon></link></b>
<b><link="WorldObject:f5b21c43-b70e-4fbb-9772-aa56a2e940f6"><ecoicon item="Workbench">philawil's Workbench</ecoicon></link></b>
```

**Comment by D3nnis3n** [comment]
> Official Server Logs are spammed with this
> 
> > [19:14:53.032] [9] [ Warn] [Eco] Can't send string as localizable, because it has too many arguments: 452. Max: 382. Converted to server-localized string: <link="ref:User:102"><color=#99aab5>ben, <link="ref:ElectedTitle:86"><style="Government">Attorney General</style>, <link="ref:User:217"><color=#ccffcc>Jagon, <link="ref:User:249"><color=#7fff7f>Fully89, <link="ref:Demographic:36"><style="Government">Government Members</style>, <link="ref:User:34"><color=#4cff4c>Heiak, <link="ref:Demographic:28"><style="Government">Citizens of Unica</style>, <link="ref:User:428"><color=#99aab5>BIG jiefu, <link="ref:User:311"><color=#99aab5>BLOODWHALE, <link="ref:AppointedTitle:59"><style="Government">Federal Civil Servant</style>, <link="ref:AppointedTitle:161"><style="Government"><color=red>Owner</style>, <link="ref:User:561"><color=#99aab5>BunnyS, <link="ref:User:583"><color=#99aab5>FpsCasper, <link="ref:User:604"><color=#99aab5>HanRogue, <link="ref:User:307"><color=#99aab5>IamNIUX, <link="ref:User:187"><color=#99aab5>[QC/FR] Noam Chomsky, <link="ref:User:419"><color=#99aab5>ILITA, <link="ref:User:485"><color=#ccffcc>Cameros, <link="ref:User:141"><color=#4cff4c>HitTheMan, <link="ref:User:683"><color=#99aab5>KaiminsLV, <link="ref:User:774"><color=#99aab5>AlmondYeti, <link="ref:Demographic:26"><style="Government">Citizens of Balica</style>, <link="ref:User:76"><color=#19ff19>Kjell, <link="ref:User:427"><color=#99aab5>James, <link="ref:User:266"><color=#99aab5>Cross Forth, <link="ref:AppointedTitle:168"><style="Government">Federal Secretary of Media</style>, <link="ref:User:70"><color=#7fff7f>Keeper, <link="ref:User:372"><color=#99aab5>[KH]Mikola :?Úlairi, <link="ref:User:536"><color=#99aab5>ebk80, <link="ref:User:567"><color=#99aab5>Faile, <link="ref:User:356"><color=#99aab5>edo ?3, <link="ref:AppointedTitle:191"><style="Government">Avocados</style>, <link="ref:User:569"><color=#99aab5>Ellie, <link="ref:ElectedTitle:93"><style="Government">Governor of Sondaica</style>, <link="ref:User:168"><color=#99aab5>JordanT, <link="ref:User:329"><color=#99aab5>drayner, <link="ref:User:349"><color=#ffb2b2>BOOM, <link="ref:ElectedTitle:91"><style="Government">Deputy Prime Minister</style>, <link="ref:User:284"><color=#99aab5>cake_motoclassic, <link="ref:User:484"><color=#99aab5>florin.prisecariu, <link="ref:User:4"><color=#99aab5>Federal Government, <link="ref:User:448"><color=#99aab5>Emperio97, <link="ref:User:5"><color=#99aab5>Federal Bank, <link="ref:User:725"><color=#99aab5>Laplante, <link="ref:User:650"><color=#99aab5>DikkeBoktor28, <link="ref:User:299"><color=#99aab5>baileyjasmin, <link="ref:User:747"><color=#99aab5>K7 Avenger, <link="ref:AppointedTitle:159"><style="Government">Farmers Market</style>, <link="ref:User:265"><color=#99aab5>Franz81, <link="ref:User:511"><color=#99aab5>Drillhead, <link="ref:User:449"><color=#66ff66>eimaz, <link="ref:User:552"><color=#99aab5>How To Troll -Episode 1, <link="ref:User:610"><color=#99aab5>galaxycat, <link="ref:User:658"><color=#99aab5>Lamujertrampa, <link="ref:User:455"><color=#99aab5>KiwiNipCheese, <link="ref:User:283"><color=#99aab5>BNLid56, <link="ref:User:551"><color=#99aab5>Kyrie, <link="ref:User:616"><color=#99aab5>Flamedragon107, <link="ref:User:595"><color=#99aab5>Karlkojote, <link="ref:AppointedTitle:65"><style="Government">Government of Unica</style>, <link="ref:User:230"><color=#99aab5>Lark, <link="ref:User:512"><color=#99aab5>Fuffenstein, <link="ref:User:130"><color=#99aab5>[C-104]Fredrico K., <link="ref:User:367"><color=#ccffcc>f2marcs, <link="ref:User:590"><color=#99aab5>Cocaine, <link="ref:User:627"><color=#99aab5>Laredo, <link="ref:AppointedTitle:176"><style="Government">Boss Corp.</style>, <link="ref:User:6"><color=#99ff99>-=GoW=-Dennis, <link="ref:User:482"><color=#7fff7f>Komonyi, <link="ref:User:225"><color=#b2ffb2>Exacon, <link="ref:AppointedTitle:203"><style="Government">Legal Assistant</style>, <link="ref:AppointedTitle:153"><style="Government">HippoCo C-Suite</style>, <link="ref:ElectedTitle:89"><style="Government">Federal Judge 2</style>, <link="ref:User:404"><color=#99aab5>Der_Fiese_Fettsack, <link="ref:User:172"><color=#4cff4c>JC Hunter, <link="ref:User:267"><color=#99aab5>DeFacto, <link="ref:User:559"><color=#ff9999>838514626, <link="ref:AppointedTitle:57"><style="Government">Authorized for Executive Actions</style>, <link="ref:User:685"><color=#99aab5>gitty, <link="ref:User:66"><color=#99aab5>DW.Relicious, <link="ref:User:152"><color=#99ff99>Bacon 4ssassin, <link="ref:User:503"><color=#99aab5>GingerSnapz, <link="ref:User:381"><color=#99aab5>DeeKay, <link="ref:User:609"><color=#99aab5>Bunn, <link="ref:User:84"><color=#b2ffb2>Duruwa, <link="ref:User:83"><color=#b2ffb2>kovibali2, <link="ref:User:353"><color=#99aab5>KrakerJak, <link="ref:User:28"><color=#b2ffb2>Drewy, <link="ref:User:697"><color=#99aab5>gingerninja_03, <link="ref:User:259"><color=#99aab5>Killkat, <link="ref:User:596"><color=#99aab5>Colley, <link="ref:User:389"><color=#99aab5>Crocodylus Acutus, <link="ref:User:716"><color=#99aab5>Cthulhu, <link="ref:User:422"><color=#99aab5>Calito, <link="ref:User:621"><color=#99aab5>L'Anesthésiste, <link="ref:User:673"><color=#99aab5>[ interCostal ] * noisE™, <link="ref:User:705"><color=#99aab5>[1AD] KillerCake99, <link="ref:User:1"><color=#7fff7f>[PMD]Daniel93a, <link="ref:AppointedTitle:147"><style="Government">DUOKLITA</style>, <link="ref:User:519"><color=#99aab5>A moth, <link="ref:User:233"><color=#99aab5>Dolcini, <link="ref:User:753"><color=#99aab5>Gavyn, <link="ref:User:147"><color=#99aab5>LeathelMike, <link="ref:User:523"><color=#99aab5>8539Borito, <link="ref:User:439"><color=#99aab5>Cyph3r150, <link="ref:User:407"><color=#99aab5>DeMoN, <link="ref:User:702"><color=#99aab5>idrvblu, <link="ref:User:525"><color=#99aab5>Elektrik, <link="ref:User:58"><color=#66ff66>Hippo, <link="ref:User:491"><color=#99aab5>Jorgen, <link="ref:User:270"><color=#99aab5>iS4ckyou, <link="ref:User:676"><color=#99aab5>dashakiilo, <link="ref:User:376"><color=#99aab5>chrom ツ, <link="ref:User:236"><color=#99aab5>Grailer, <link="ref:User:154"><color=#99aab5>h24jensen, <link="ref:User:339"><color=#99aab5>FGArthur, <link="ref:User:668"><color=#ccffcc>4l4b4m4m4n, <link="ref:User:414"><color=#99aab5>-=Wyrmz=-, <link="ref:User:274"><color=#99aab5>Arium, <link="ref:User:183"><color=#99aab5>Kimbo Slice, <link="ref:User:615"><color=#99aab5>Anubis, <link="ref:User:189"><color=#99aab5>Evazin, <link="ref:User:768"><color=#99aab5>Joufflu, <link="ref:AppointedTitle:58"><style="Government">Candidate for Federal Judge</style>, <link="ref:User:305"><color=#99aab5>Jastrab66, <link="ref:User:247"><color=#99aab5>1320592469, <link="ref:User:462"><color=#99aab5>dupreeh, <link="ref:User:211"><color=#99aab5>greyfox2112, <link="ref:User:354"><color=#99aab5>Cybot, <link="ref:User:137"><color=#99aab5>John Down, <link="ref:User:258"><color=#99aab5>DracoKing2298, <link="ref:User:149"><color=#7fff7f>Gummybear, <link="ref:User:531"><color=#99aab5>El Csapo, <link="ref:User:29"><color=#32ff32>Dreamstate, <link="ref:User:612"><color=#99aab5>Almogàver, <link="ref:User:602"><color=#99aab5>FreeGen, <link="ref:AppointedTitle:144"><style="Government">BeleHoover Enterprises</style>, <link="ref:ElectedTitle:74"><style="Government">Federal President</style>, <link="ref:User:186"><color=#99aab5>DEUSVULT Bracesco, <link="ref:User:36"><color=#99aab5>KokkoJustus, <link="ref:User:335"><color=#99aab5>IronCove, <link="ref:User:164"><color=#99ff99>hoover2000, <link="ref:AppointedTitle:142"><style="Government">furniture dwarfs</style>, <link="ref:User:122"><color=#66ff66>fiscch3, <link="ref:User:170"><color=#99aab5>Hassel, <link="ref:User:498"><color=#99aab5>Hawkin, <link="ref:User:497"><color=#99aab5>haleymarie841, <link="ref:User:557"><color=#99aab5>Deathsquadie, <link="ref:User:250"><color=#99aab5>landi, <link="ref:User:231"><color=#66ff66>Alfalfa, <link="ref:User:180"><color=#99aab5>Atomic_Grind, <link="ref:User:488"><color=#99aab5>Chemical, <link="ref:User:408"><color=#99aab5>[BULL] Wizz, <link="ref:User:91"><color=#99aab5>chavis.suzuki, <link="ref:User:133"><color=#99aab5>JerrySpringer, <link="ref:User:382"><color=#99aab5>BumbleCrap, <link="ref:User:566"><color=#99aab5>Edw4rd, <link="ref:User:155"><color=#66ff66>cjbowm3, <link="ref:User:351"><color=#99aab5>El Yako, <link="ref:User:251"><color=#99aab5>456qwejos, <link="ref:User:631"><color=#99aab5>Csoki, <link="ref:User:332"><color=#99aab5>crycal, <link="ref:User:222"><color=#99aab5>[BB] Lucifer, <link="ref:User:252"><color=#99aab5>kertazy, <link="ref:User:216"><color=#99aab5>cosigma, <link="ref:User:43"><color=#99aab5>Kazan, <link="ref:User:483"><color=#99aab5>EnTrodoX, <link="ref:User:703"><color=#99aab5>Crazy Cranium, <link="ref:User:764"><color=#99aab5>jacksonsuckatfps, <link="ref:User:443"><color=#99aab5>KingTiger101, <link="ref:User:108"><color=#99ff99>Leki, <link="ref:AppointedTitle:181"><style="Government">D&S Supply</style>, <link="ref:User:191"><color=#99aab5>✯ VickeS ✯, <link="ref:User:513"><color=#99aab5>Andreia, <link="ref:User:159"><color=#99aab5>CharisisPD, <link="ref:User:38"><color=#ff4c4c>Cinea, <link="ref:User:457"><color=#99aab5>Al_Ashrad, <link="ref:User:243"><color=#99aab5>dirty_burke07, <link="ref:User:209"><color=#99aab5>J. Rees, <link="ref:User:135"><color=#99aab5>Hakeryuga, <link="ref:User:537"><color=#99aab5>Armored Eagle, <link="ref:User:343"><color=#99aab5>Jonana, <link="ref:User:363"><color=#99aab5>l3g1oOon, <link="ref:User:674"><color=#99aab5>Alt3Rn4tE, <link="ref:ElectedTitle:85"><style="Government">Chancellor of the Federal University</style>, <link="ref:User:479"><color=#99aab5>cat200, <link="ref:User:158"><color=#99aab5>Cherie, <link="ref:User:105"><color=#99aab5>Blue, <link="ref:User:450"><color=#99aab5>Cavias, <link="ref:User:131"><color=#99aab5>Jacco, <link="ref:User:562"><color=#ccffcc>Blue Button, <link="ref:User:670"><color=#ccffcc>Czerepara, <link="ref:User:106"><color=#99aab5>Jarisom, <link="ref:User:128"><color=#32ff32>Ith, <link="ref:User:584"><color=#99aab5>idurasmetalwood, <link="ref:User:510"><color=#99aab5>Jarius, <link="ref:User:197"><color=#ccffcc>Conesq, <link="ref:User:297"><color=#99aab5>Jenya, <link="ref:Demographic:1"><style="Government">Everyone</style>, <link="ref:User:591"><color=#32ff32>B.eep, <link="ref:User:200"><color=#99aab5>Idka, <link="ref:ElectedTitle:95"><style="Government">Governor of Balica</style>, <link="ref:User:145"><color=#99aab5>Dinosaur Dundee, <link="ref:User:308"><color=#99aab5>Jacan., <link="ref:User:360"><color=#99aab5>AleXtreme1, <link="ref:User:2"><color=#32ff32>Elmeye, <link="ref:User:194"><color=#99aab5>Imparfecto, <link="ref:User:286"><color=#99aab5>Lenning, <link="ref:User:165"><color=#66ff66>Kobi, <link="ref:User:82"><color=#99aab5>Clark, <link="ref:User:487"><color=#99aab5>Evangelinee ✔, <link="ref:User:420"><color=#99aab5>j.m.grady, <link="ref:User:662"><color=#99aab5>adly96, <link="ref:User:644"><color=#99aab5>Hissy, <link="ref:User:664"><color=#99aab5>CkairisZ28, <link="ref:User:226"><color=#99ff99>Burner, <link="ref:User:292"><color=#99aab5>IDefalt, <link="ref:User:698"><color=#99aab5>Dornase ?3 Being.Decoy, <link="ref:User:262"><color=#99aab5>Laz Mimar, <link="ref:AppointedTitle:111"><style="Government">GB-NEW-HOPE</style>, <link="ref:User:556"><color=#99aab5>123, <link="ref:User:208"><color=#99aab5>|GßS| Mr.Gato, <link="ref:User:291"><color=#ccffcc>CoastGuardsman, <link="ref:User:260"><color=#99aab5>Jim, <link="ref:User:59"><color=#ccffcc>Kuldiin, <link="ref:User:731"><color=#99aab5>.ØK Shaker :/, <link="ref:AppointedTitle:208"><style="Government">Janitor</style>, <link="ref:User:451"><color=#99aab5>? blank ?, <link="ref:User:533"><color=#99aab5>Damuall, <link="ref:User:436"><color=#99aab5>DeneWarChief, <link="ref:User:302"><color=#99aab5>asmodeouss, <link="ref:User:761"><color=#99aab5>Grand Admiral Gandalf, <link="ref:User:518"><color=#99aab5>✪Stazzii, <link="ref:User:438"><color=#99aab5>_m, <link="ref:User:459"><color=#99aab5>chunkypumpkin238, <link="ref:User:541"><color=#99aab5>JaxClayton, <link="ref:User:771"><color=#99aab5>F41c0NR, <link="ref:User:123"><color=#7fff7f>Frange, <link="ref:User:54"><color=#99aab5>Bobo, <link="ref:User:481"><color=#99aab5>EPICDUK987, <link="ref:User:40"><color=#66ff66>Jesus, <link="ref:User:784"><color=#99aab5>Iamstarlayla, <link="ref:Demographic:29"><style="Government">Citizens of Virgata</style>, <link="ref:User:727"><color=#99aab5>LayZey, <link="ref:User:550"><color=#99aab5>Aidanvlucifer, <link="ref:User:613"><color=#7fff7f>danadikay, <link="ref:User:153"><color=#99aab5>[PM] Century, <link="ref:User:547"><color=#99aab5>JasonSkillman, <link="ref:User:53"><color=#99aab5>kenix, <link="ref:User:645"><color=#99aab5>IAMTROLLMASTER, <link="ref:User:22"><color=#99aab5>DatBoi.RAT, <link="ref:User:489"><color=#99aab5>[OC] Dukan, <link="ref:AppointedTitle:132"><style="Government">[FF-State]</style>, <link="ref:User:109"><color=#7fff7f>john_ski, <link="ref:User:94"><color=#99aab5>Blury, <link="ref:User:769"><color=#99aab5>Darklord72, <link="ref:User:143"><color=#99aab5>Knut, <link="ref:User:224"><color=#66ff66>erjo5055, <link="ref:User:684"><color=#99aab5>[BS] Farmtool33, <link="ref:User:573"><color=#99aab5>Lerix, <link="ref:AppointedTitle:60"><style="Government">Federal Secretary</style>, <link="ref:User:163"><color=#99aab5>CentAtMoney, <link="ref:User:12"><color=#99aab5>d0nk3y, <link="ref:User:549"><color=#99aab5>Fireauto, <link="ref:AppointedTitle:192"><style="Government">Dictator 2</style>, <link="ref:Demographic:35"><style="Government">Federal Judges</style>, <link="ref:User:392"><color=#99aab5>I Love yoghurt, <link="ref:User:25"><color=#ff6666>Jabroni, <link="ref:User:619"><color=#ccffcc>Harry, <link="ref:AppointedTitle:151"><style="Government">GBS</style>, <link="ref:User:679"><color=#99aab5>DrDubs808, <link="ref:User:411"><color=#b2ffb2>JohnIsOn67, <link="ref:Demographic:3"><style="Government">Active</style>, <link="ref:AppointedTitle:167"><style="Government">Federal Secretary of Infrastructure</style>, <link="ref:AppointedTitle:146"><style="Government">Holy Cow</style>, <link="ref:AppointedTitle:145"><style="Government">Ecological Devastation and Sons</style>, <link="ref:AppointedTitle:187"><style="Government">AAA Consulting</style>, <link="ref:User:409"><color=#99aab5>Dark_Duty, <link="ref:User:169"><color=#99aab5>kim jin ho, <link="ref:User:542"><color=#99aab5>Grobag, <link="ref:User:162"><color=#99aab5>BobbyB, <link="ref:User:139"><color=#99aab5>AreYouReady2Die, <link="ref:User:606"><color=#99aab5>13-th_fighter, <link="ref:User:722"><color=#99aab5>Creep, <link="ref:User:593"><color=#99aab5>Kayz♛, <link="ref:User:426"><color=#99aab5>creepyabdul, <link="ref:User:520"><color=#99ff99>Detective Avocado, <link="ref:User:255"><color=#7fff7f>Doc Doe, <link="ref:User:740"><color=#99aab5>knightmaire, <link="ref:User:625"><color=#ccffcc>Kislota, <link="ref:AppointedTitle:177"><style="Government">basic Company</style>, <link="ref:AppointedTitle:202"><style="Government">Indian Delhi Trade Company</style>, <link="ref:User:92"><color=#b2ffb2>FrostyLazer, <link="ref:User:73"><color=#99ff99>Hubris, <link="ref:Demographic:25"><style="Government">Citizens of Altaica</style>, <link="ref:User:447"><color=#99aab5>fantom_legion, <link="ref:User:264"><color=#99aab5>-Doctor Who-, <link="ref:User:246"><color=#99aab5>John Bones, <link="ref:User:257"><color=#99aab5>aquiles7777, <link="ref:User:540"><color=#99aab5>Be Irish, <link="ref:User:638"><color=#99aab5>Batterdude, <link="ref:User:280"><color=#99aab5>Coop, <link="ref:User:275"><color=#99aab5>Grid, <link="ref:User:323"><color=#99aab5>Ceiba Brazier, <link="ref:User:317"><color=#99aab5>doug, <link="ref:User:333"><color=#99aab5>CharlieSheen_Aladeen, <link="ref:User:227"><color=#99aab5>CryingSkuare, <link="ref:User:199"><color=#99aab5>Commander Keen, <link="ref:User:575"><color=#99aab5>Elektronik, <link="ref:Demographic:2"><style="Government">Admins</style>, <link="ref:User:738"><color=#99aab5>Caladriul, <link="ref:AppointedTitle:61"><style="Government">Game Masters</style>, <link="ref:User:453"><color=#99aab5>Eversor, <link="ref:User:592"><color=#99aab5>✨(„ᓀᆺᓀ„), <link="ref:AppointedTitle:207"><style="Government"><color=grey>Steam powered Lawyer</style>, <link="ref:User:20"><color=#66ff66>Darkhope, <link="ref:User:468"><color=#99aab5>Korbka, <link="ref:User:729"><color=#99aab5>Kabasea, <link="ref:User:528"><color=#99aab5>Jorn, <link="ref:Demographic:27"><style="Government">Citizens of Sondaica</style>, <link="ref:User:687"><color=#ccffcc>Blackwater, <link="ref:User:718"><color=#99aab5>$d. Duke Darius, <link="ref:User:48"><color=#66ff66>Explosiv Muffin, <link="ref:User:350"><color=#99aab5>Joe, <link="ref:User:766"><color=#99aab5>alexgd0212, <link="ref:User:539"><color=#99aab5>LeeVanCleef, <link="ref:User:538"><color=#99aab5>Bitterness, <link="ref:User:111"><color=#99aab5>[GER] afisch (DE-de/EN-us), <link="ref:User:201"><color=#ccffcc>Conollio n' Cheese, <link="ref:ElectedTitle:96"><style="Government">Governor of Virgata</style>, <link="ref:AppointedTitle:121"><style="Government"><color=green>Gamer, Gamer, Gamer, Gamer & Sons</style>, <link="ref:User:89"><color=#99aab5>Chivas, <link="ref:User:285"><color=#99aab5>CrimsonTide2077, <link="ref:User:39"><color=#99ff99>Brewski, <link="ref:User:68"><color=#99aab5>Deancan, <link="ref:User:245"><color=#99aab5>Cyrain, <link="ref:User:737"><color=#99aab5>"Friendly" Trash, <link="ref:User:345"><color=#99aab5>Josh, <link="ref:User:120"><color=#99ff99>lacto, <link="ref:ElectedTitle:69"><style="Government">Deputy Mayor of Unica</style>, <link="ref:User:282"><color=#99aab5>Lemmiwinks, <link="ref:User:27"><color=#b2ffb2>GazzassDK, <link="ref:User:667"><color=#99aab5>Djinneus, <link="ref:User:127"><color=#99aab5>GeneralfeldmarschallvHindenburg, <link="ref:User:359"><color=#66ff66>almond, <link="ref:User:384"><color=#99aab5>Kal Skirata, <link="ref:User:624"><color=#99aab5>CyberPunk1992, <link="ref:User:146"><color=#99aab5>CherryBerry, <link="ref:ElectedTitle:75"><style="Government">Governor of Altaica</style>, <link="ref:User:461"><color=#99aab5>Lappel, <link="ref:User:295"><color=#99aab5>Chris, <link="ref:AppointedTitle:204"><style="Government">Client</style>, <link="ref:User:776"><color=#99aab5>Bandee, <link="ref:User:441"><color=#99aab5>Kiihas, <link="ref:User:435"><color=#99aab5>charlyboyblue, <link="ref:User:11"><color=#4cff4c>[BB] Nutriigrain, <link="ref:User:744"><color=#99aab5>Absydeus, <link="ref:AppointedTitle:103"><style="Government">Hydro</style>, <link="ref:User:86"><color=#99aab5>Corax, <link="ref:User:379"><color=#99aab5>JoVlaXes, <link="ref:AppointedTitle:133"><style="Government"><color=orange>ApeScience</style>, <link="ref:User:174"><color=#99aab5>Blue#2, <link="ref:AppointedTitle:150"><style="Government">HippoCo</style>, <link="ref:User:375"><color=#99aab5>Ernabella, <link="ref:User:720"><color=#99aab5>Dizel725, <link="ref:User:293"><color=#66ff66>Ed, <link="ref:ElectedTitle:100"><style="Government">Director of the Federal Bank</style>, <link="ref:User:279"><color=#99aab5>Brighthope, <link="ref:User:783"><color=#99aab5>iNvOiCe, <link="ref:User:124"><color=#ff7f7f>gande, <link="ref:User:223"><color=#99aab5>jbroyles07, <link="ref:Demographic:4"><style="Government">Abandoned</style>, <link="ref:User:452"><color=#99aab5>DavidGoru, <link="ref:User:374"><color=#99aab5>✪ DARYL DIXSON, <link="ref:User:140"><color=#99aab5>Efan, <link="ref:User:469"><color=#99aab5>KBS, <link="ref:User:166"><color=#b2ffb2>Emmental, <link="ref:User:678"><color=#99aab5>G0DlIkEDM, <link="ref:User:446"><color=#99aab5>Damahlyee, <link="ref:User:713"><color=#99aab5>3yvi01, <link="ref:User:358"><color=#99aab5>leonsturm, <link="ref:User:588"><color=#99aab5>Jay159753, <link="ref:User:699"><color=#99aab5>JeanKoba, <link="ref:User:175"><color=#66ff66>Goober1823, <link="ref:User:734"><color=#99aab5>Burry89, <link="ref:User:215"><color=#99ff99>jessraes, <link="ref:User:700"><color=#99aab5>Dennis, <link="ref:User:708"><color=#99aab5>AlexT2000, <link="ref:User:97"><color=#99aab5>Don Potato, <link="ref:User:115"><color=#99aab5>Joey_G, <link="ref:User:8"><color=#7fff7f>Belethor, <link="ref:User:322"><color=#99aab5>Batfamilyguy, <link="ref:User:728"><color=#99aab5>LASTEDOF, <link="ref:User:176"><color=#99aab5>Carstelli, <link="ref:User:534"><color=#99aab5>Ilia_sergeevich, <link="ref:AppointedTitle:200"><style="Government">EverBlues</style>, <link="ref:User:607"><color=#99aab5>BloodBunny, <link="ref:AppointedTitle:102"><style="Government">AS Construction inc.</style>, <link="ref:User:377"><color=#99aab5>Ecock, <link="ref:User:763"><color=#99aab5>Batu-San, <link="ref:AppointedTitle:62"><style="Government">In Jail</style>, <link="ref:User:475"><color=#99aab5>Kblu82, <link="ref:User:514"><color=#99aab5>Jooni, <link="ref:User:578"><color=#99aab5>DarkWarrior115, <link="ref:User:290"><color=#7fff7f>Gamer260, <link="ref:User:423"><color=#99aab5>D4RTH, <link="ref:User:779"><color=#99aab5>BlueberryWaltz, <link="ref:User:110"><color=#99aab5>Hedkrab_42, <link="ref:User:693"><color=#ffb2b2>Abhorrent Mu, <link="ref:User:248"><color=#99aab5>annagabriele, <link="ref:User:463"><color=#b2ffb2>BROADEX, <link="ref:ElectedTitle:92"><style="Government">Federal Judge 1</style>, <link="ref:User:649"><color=#99aab5>BU7777777777, <link="ref:User:635"><color=#99aab5>Fonzy, <link="ref:User:370"><color=#99aab5>Itsleotime, <link="ref:User:618"><color=#99aab5>Falloutgeek268, <link="ref:AppointedTitle:160"><style="Government">Dictator</style>, <link="ref:User:17"><color=#99ff99>Deathotic, <link="ref:User:19"><color=#4cff4c>Fireguard, <link="ref:User:694"><color=#99aab5>ishyishira, <link="ref:User:195"><color=#99aab5>KingPin, <link="ref:User:65"><color=#7fff7f>j0zh94, <link="ref:User:80"><color=#4cff4c>Kodvik, <link="ref:User:303"><color=#99aab5>DG, <link="ref:User:755"><color=#99aab5>Kairy, <link="ref:User:242"><color=#99aab5>2277580787, <link="ref:User:196"><color=#99aab5>Fray[Mortem], <link="ref:User:220"><color=#ccffcc>ExPLiCiT, <link="ref:User:301"><color=#99aab5>Le Sten [⇄], <link="ref:User:723"><color=#99aab5>Atom_Badger, <link="ref:User:212"><color=#99aab5>DeadlyBlade, <link="ref:AppointedTitle:115"><style="Government"><color=#4FEBDA>Pinguin</style>, <link="ref:User:640"><color=#99aab5>Kruherson, <link="ref:User:622"><color=#99aab5>Kayak, <link="ref:User:77"><color=#ccffcc>bruno17431, <link="ref:User:403"><color=#99aab5>fusiolate, <link="ref:User:675"><color=#99aab5>Ice Forge, <link="ref:AppointedTitle:169"><style="Government">Federal Building Inspector</style>, <link="ref:User:456"><color=#99aab5>Just Myself, <link="ref:User:396"><color=#99aab5>Azailiez, <link="ref:User:572"><color=#99aab5>BurningCub, <link="ref:User:425"><color=#99aab5>colton.rier, <link="ref:User:254"><color=#99aab5>DonVito, <link="ref:User:78"><color=#7fff7f>Andrius, <link="ref:User:471"><color=#99aab5>alethena, <link="ref:User:754"><color=#99aab5>Cucunghe, <link="ref:User:506"><color=#99aab5>IronyTroll, <link="ref:User:121"><color=#99aab5>Axehilt, <link="ref:User:362"><color=#99aab5>Hinker, <link="ref:User:544"><color=#99aab5>CapnDecap, and <link="ref:User:324"><color=#99aab5>Brigitte L'huitre.
> 
> A few thousand occurances per log, so making log files unreadable and too big. Needs to be fixed.

This needs to be fixed.

**Comment by SlayksWood** [comment]
closed as fixed
