### ISSUE TITLE
USER ISSUE: Tellaporting Carts To unreachable location.

### ISSUE THREAD

**Issue by dylanviey** [StrangeLoopGames/EcoIssues#20403]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
My wooden carts locations keep re-setting to 0.0.0 and they end up stuck underground. Happened 2 times on the default map I'm currently playing and 1 time on a different randomly generated map. Not sure about the randomly generated map but on the map I'm currently playing the cart has been inside my mine underground when they teleport. The mine shafts are 3 blocks wide by 5 blocks high. With stone road slopes for flooring. Right before it happened the first time all my carts (got about 10) stopped being interactable, movable, removable and I could just push them around by walking into them. A game restart fixed it but my first cart ended up underground at 0.0.0 and the 2nd cars ended up there randomly.

**Expected behavior:**
Not end up underground if location re-set was needed or not teleport at all. Or have a way to reset their location to the surface so they can be retrieved.

**Actual behavior:**
Carts are sent to 0.0.0 and are un retrievable and stuck underground. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. fully stock and basic game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5936230/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5936231/Player.log)

**Comment by SlayksWood** [comment]
@dylanviey Thank you for the report. I can't reporoduce it, but some players complain on cazy behaviour of some objects. 
Merged to #20414 to investigate it more.

**Comment by dylanviey** [comment]
Have a couple of updates. Had both of the carts randomly re appear near the original locations. One ended up suck in the ceiling of the mine and other just upside-down near where I last left it. I have since had another cart go to 0.0.0 but not sure which one or where I originally left it.

I think it's related to the loading and unloading of chunks (not sure what you guys call it but i know that's what's it's called in Minecraft) I feel like if a cart is left on the edge of a chunk when it spawns in from loading if the chunk next to it isn't loaded it falls out of the world then teleports but instead of just going to the surface like when I'm driving a steam truck and the chunks don't load fast enough they get sent to 0.0.0.
