### ISSUE TITLE
USER ISSUE: can't open my world

### ISSUE THREAD

**Issue by ItsJustYui** [StrangeLoopGames/EcoIssues#20410]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Start Eco 2. Click "Your worlds" (or what ever its called in english) 3. Scroll down to your 25h world 4. Try to load it. 5. Say YES 6. Nothing happens.

**Expected behavior:**
It should have done something to load my world or ask me again if i want to.

**Actual behavior:**
Instead it did nothing. It lets me watch the screen about my world(s) and some official servers for 29387 hrs. It does NOT crash or freeze, it just does nothing.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide your player and server logs:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by IcedForge** [comment]
Closing this in lack of reply, please reopen and add relevant information for further investigation @ItsJustYui
