### ISSUE TITLE
Can't give access to demographics (everybody, active, etc) on claimed land.

### ISSUE THREAD

**Issue by salix-d** [StrangeLoopGames/EcoIssues#20417]
Since the update I'm unable give access to any claim using the demographics categories. 

steps : 
- claiming land with the land claim stake
- pressing 'e'
- in tab 'who has access' select 'everyone' or 'active'

expected behavior : people have access and can build.
actual behavior : they can't.

I can only add people one by one and it's really annoying.
(This was also happening on our previous server without the mods the current one has)

**Comment by SlayksWood** [comment]
@salix-d Thank you for the report. What game version do you use? It should be fixed in 9.2.3 with #20227

**Comment by salix-d** [comment]
It was in 9.2.2 and 9.2.3. I'll check in 9.2.4 if it's still there.

**Comment by salix-d** [comment]
Since we updated the server this morning to 9.2.4 it's working 😄

**Comment by SlayksWood** [comment]
Well, I think I confused where it was fixed. Closed for now.

**Comment by salix-d** [comment]
Actually, it's not working anymore... It only worked with the mod folder from 9.2.3 even tho it wasn't working when we were running 9.2.3 with the same folder... Are the auth or demographics affected by files in that folder? Can't find that information anywhere, would like to know if it's our files or the game causing the issue, if the former, it would help fix it.

**Comment by salix-d** [comment]
To get more info, I tested on a local server (9.2.4; no mods) and invited a friend.
When I claimed land and set the auth to 'everyone', they couldn't dig sand.
![image](https://user-images.githubusercontent.com/31168746/107557093-2b97a100-6ba7-11eb-93ff-7f85b057ed0c.png)

Really confused.
