### ISSUE TITLE
[0.9.2.4 Release-159] Nutrition Pie Chart example during Food and Nutrition tutorial is not appropriately set to 25% each

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20418]
Tested on 0.9.2.4 Release-159

Issue: Minor issue. During the tutorial on Food and Nutrition, the Nutrition Pie Chart displayed as an example of optimal balance is not showing a chart of 25% cut for each Carbs, Protein, Fat, and Vitamins.

Repro:
1. Play through the Food and Nutrition tutorial.
2. Observe the Optimal Chart example.

Screenshot:
![nutrition chart.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/6d854ec6-0722-4a10-bea3-088575ffce68)

**Comment by Daniel-Magulado** [comment]
Build: 0.9.4 Develop-203

Note: I saw that commit [61fcdf9](https://github.com/StrangeLoopGames/Eco/pull/7960) which was the fix for this issue had a failed run for Develop 202.

The issue is still happening for this build. The food chart is not equally portioned to 25% each.

Resolution: Reopening and moving to the confirmed issue pipeline.

**Comment by gzatravkin** [comment]
Per John's comment at https://github.com/StrangeLoopGames/Eco/pull/7960 
"getting perfect 25% isnt achieveable, so I dont want to change this. It should look a little more realistic."

So it's Won't fix
