### ISSUE TITLE
USER ISSUE: Mouse Speed when first entering a game

### ISSUE THREAD

**Issue by Zanthorphs** [StrangeLoopGames/EcoIssues#20415]
Something that seems like a bug that the general group of people I've played with have noticed when joining a new server for the first time is the mouse sensitivity slider seems to always default to 0.01 making mouse movement for new players very difficult and very confused at why the controls are sluggish.  

This seems true for those I've communicated with recently and could be a simple fix of defaulting the mouse sensitivity slider to 2.00 thru 4.00 to solve this problem.

**Comment by salix-d** [comment]
Also happened to me and a bunch of new players, but not all of them.

**Comment by SlayksWood** [comment]
@Zanthorphs Thank you for the report. 
Merged to #20244
