### ISSUE TITLE
[0.9.2.4 Release-159]Button to set maximum number of order based on available resources

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20419]
This is more of a suggestion to improve the quality of life for the game.

Issue: As of 0.9.2.4 Release-159, when crafting, I have to either manually input the number of orders or click the increase order button that increases the order count by an increment of 1.

Suggestion: Set a button for crafting when clicked, it sets the maximum order count allowed based on available resources at hand.

For example, at the campfire, I have 50 corns and I want to craft 50 charred corns.  The fastest way to do that as of this build is to manually input the number of orders for 50 charred corns and it requires 4 sequential actions to do so.

1. Hover your mouse over to the order number box.
2. Click it with the left mouse button.
3. type in 5.
4. type in 0.

Recommendation: Implement a button where the game automatically sets the maximum number of orders available based on available resources at hand or in storage.

Something like this
![max.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/67bd5ebc-efa5-4701-ae66-af6c7700d5c7)

This gives players flexibility and options in crafting.

**Comment by SlayksWood** [comment]
Added to our Craft UI remake issue #13334
