### ISSUE TITLE
[0.9.2.4 beta release-156]Economy Viewer slow/unresponsive

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20413]
The Economy viewer is extremely slow due to listing large amounts of content when ever you open it.
Revise the possibilities to not instantly show everything ?
Adding filters and then submit to show to reduce the massive 5-30 second slowdown depending on market on the server?

**Comment by johnkslg** [comment]
Joe put in a fix for this (go joe)
