### ISSUE TITLE
Rob & friends feedback: Store bartering wasnt clear. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20428]
there should be a barter option clearly in the store currency list

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/107199357-5e0a9800-6a07-11eb-8608-2299d04cf522.png)

**Comment by TwixterZ** [comment]
Fix checked and confirmed as of 9.4 Develop 279

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/e4504afb-906a-4dba-9d57-25f9e02e276d)
