### ISSUE TITLE
USER ISSUE: Ich stecke fest!

### ISSUE THREAD

**Issue by champsista** [StrangeLoopGames/EcoIssues#20423]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Ich lief über mein Dach und buggte in die Decke

**Expected behavior:**
Ich wollte über das Dach laufen

**Actual behavior:**
Stattdessen buggte ich in die Decke

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@champsista Thank you for the report. For such cases, we have command '/unstuck', use it in chat.
