### ISSUE TITLE
Staging alpha 6.0.0 #cc778b68 - Trees growing over crops.

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2042]
Seems that trees are growing where crops were planted again.  This one ate part of my beet field:

![image](https://user-images.githubusercontent.com/30206504/29944192-57d4958e-8e51-11e7-9dee-63af6939f4c0.png)

**Comment by Senbotsu** [comment]
And 7 in my second field.  This is 4 plots of huckleberries and 4 plots of beans.  There are 4 trees in the bean section and 3 in the berry section:

![image](https://user-images.githubusercontent.com/30206504/29944345-137a8a14-8e52-11e7-9c11-29da11642aa5.png)

**Comment by MarjieAVolk** [comment]
Fixed in PR above ^
