### ISSUE TITLE
[9.2.4] Not working demograpic groups and titles in laws and property of claims 

### ISSUE THREAD

**Issue by BrannByorn1** [StrangeLoopGames/EcoIssues#20439]
When you select "demographic group" or "title" as a condition for implementing the law, it does not allow you to adopt the law and writes the error " you need to set both the currency and its amount when setting up. Hours in and out of the game." It also does not process demographic groups and titles for access to the territory (claim and districts)
![unknown](https://user-images.githubusercontent.com/78732086/107211434-9665a280-6a16-11eb-85a6-958e19ec2e52.png)

**Comment by SlayksWood** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/45708377/107490223-a60df400-6b9a-11eb-9291-77eb9b338cfc.png)
