### ISSUE TITLE
USER ISSUE: Couldn't get out of a chair

### ISSUE THREAD

**Issue by killer11million** [StrangeLoopGames/EcoIssues#20437]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
make a button to exit chairs.

**Expected behavior:**
sit in and stand out, by the click of 2 buttons.

**Actual behavior:**
sit in cant leave, had to leave the sever than go back in.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@killer11million Thank you for the report. Did you have a backpack on your back? And which camera mode was chosen from first person view or from third person view?

**Comment by killer11million** [comment]
I think i had my backpack off when I fist sat but I put it back on and I was able to switch povs from first to 3rd I just couldn't leave the chair.

**Comment by SlayksWood** [comment]
merged to ##20373

**Comment by killer11million** [comment]
No not a cart a chair
