### ISSUE TITLE
USER ISSUE: clicking on new tutorial does nothing

### ISSUE THREAD

**Issue by Aldjeron** [StrangeLoopGames/EcoIssues#20434]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Start a new game session. Complete the 1st tutorial. after tutorial completes try to click on the next one.

**Expected behavior:**
It should open the detailed info on the tutorial.

**Actual behavior:**
Highlights the circle, but no detail pop up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Aldjeron Thank you for the report. We have the same tutorial issue when you change resolution #20252. Have you done anything like that? Do you always have this problem?
Please provide log files when you come across it next time.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response.
