### ISSUE TITLE
[9.2.4] Executive Actions. Change of ownership does not apply to movable property. 

### ISSUE THREAD

**Issue by ULiX80** [StrangeLoopGames/EcoIssues#20436]
Change of ownership through Executive Actions does not apply to movable property such as vehicles and carts. 

But there is a possibility that allows you to change the owner of movable property through the law:
Event: Open Action
Action: Ignore access rights

If such a law is applied to a specific group of residents, they will be able to drive someone else's transport and change the owner of the transport. 

But this method makes you look for all the movable property of the inhabitant.

**Comment by SlayksWood** [comment]
@ULiX80 Thank your for the report. I will merge your issue to #17733, this will be changed by one refactoring.
