### ISSUE TITLE
Make us Mod Friendlier

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20433]
- [ ] Fill out a list of tasks needed to make us mod friendly in this bug.

**Comment by ProdigyGamingCanada** [comment]
been hosting games for a long time, i would say already eco is one of the easiest games to run mods on,  i dont know how you would get mod friendlier besides maybe a steam workshop

**Comment by WeaselDog** [comment]
We have made major progress on the modkit and we have a special pipeline for this now.
