### ISSUE TITLE
Just Too Many And Not Enough Tiger Crashes ... or so

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20448]
--BEGIN DUMP--
Dump Time
02/09/2021 00:07:27

Exception
Exception: SynchronizationLockException
Message:Object synchronization method was called from an unsynchronized block of code.
Source:System.Private.CoreLib

System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Eco.Gameplay.Items.InventoryLock.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Dispose()
   at Eco.Gameplay.Items.InventoryChangeSet.Finalize()

--END DUMP--

**Comment by redwyre** [comment]
This still happening @D3nnis3n ?

**Comment by mirasrael** [comment]
Guess it already fixed if not reproduced in latest versions

**Comment by D3nnis3n** [comment]
No, but most crashes on tiger only happen once. So cant say for sure its fixed, as i dont know what triggered it.

**Comment by mirasrael** [comment]
Close until it repeated. And if it happen another time please attach full log, because this kind of issue may happen if exception happened in another place.
