### ISSUE TITLE
Store various records in LiteDB so theres unlimited history

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20446]
Things like chat history and bank account transactions, etc can go in here

**Comment by MishkaFur** [comment]
Please can we have a cleanup util for this or at least a config for limits else the DB is going to balloon even moreso than it does on high population/longterm server, ie the below etc

Personal account limit
Govt account limit
Chat X days/messages

**Comment by D3nnis3n** [comment]
I would strongly suggest to not do this as long as we didn't switch the underlying database system.
The database is already slow, easy to corrupt and way too big. (Tiger is nearing 5 GB near day 10 this very government intensive cycle)

Adding all the chat and other transactions as well at this point of having LiteDB a lag-causing bottleneck does not seem like a good idea. Especially for chat we actually have Monzuns PR for a chat log system that I already very successfully use on all of our official servers as a mod. I don't think it needs double saving.

In any case, this shouldn't be done before DB is actually able to work with lots of concurrent writes and reads without corruption and without causing lags.
