### ISSUE TITLE
[Server Issue] Server is not launching anymore.

### ISSUE THREAD

**Issue by logimy** [StrangeLoopGames/EcoIssues#20442]
Yesterday i've rebooted my pc where i'm hosting my local ECO server for my friends. After this i've got this error in console when trying to launch a server:

`Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'Eco.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'Eco.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Server.MainClass.Main(String[] args)`

**Comment by logimy** [comment]
Also, 32 bit server is working normally.

**Comment by SlayksWood** [comment]
@logimy Thank you for the report. Can you provide save file. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and some more details your PC specification (include Operating System and its version).

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
