### ISSUE TITLE
[9.2.4] Laws. Ignore access rights not work in Law on Event: Inventory Action 

### ISSUE THREAD

**Issue by ULiX80** [StrangeLoopGames/EcoIssues#20450]
We have passed a law aimed at allowing certain individuals to collect tailings from other people's warehouses. But the law cannot circumvent the prohibition of property rights. 

![изображение](https://user-images.githubusercontent.com/6950252/107305393-a476fa00-6ace-11eb-8ea0-fa085d1b49b3.png)

**Comment by SlayksWood** [comment]
Simplier law in English:
![image](https://user-images.githubusercontent.com/45708377/107608639-9996a380-6c4d-11eb-9e97-45adeba65b7c.png)
