### ISSUE TITLE
[0.9.3.0 beta staging]Court UI Updating problems

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20456]
Seems like we still have some inconsistencies regarding UI updating still.

If you add a incorrectly operating law like this it will not allow you to close down the UI using ESC key
![Screenshot_28.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ed414662-a0e3-4672-a110-4d2f6ed5c57b)

However if you force it to react by adding a new section and remove it, it will now allow you to close it with escape without editing anything in the law that started this behavior.

Reproduction steps

Add a draft of a law, select a trigger (any really) add a IF condition and pick a type of condition and try to close with escape.
Now add a new section and remove this section, it will allow you to use escape.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1948

I am able to close the Law Making UI with the Esc button despite setting the required condition to reproduce this issue.

Resolution: Closing.
