### ISSUE TITLE
[0.9.3.0 beta staging(9.4 dev build 180)]Crafting stations not subscribing to user and only displays template

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20454]
All crafting stations have templates and not displaying ownership crafting.

![Screenshot_17.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/bbe8b38e-efae-4295-b41f-4ff4b2452945)

**Comment by SlayksWood** [comment]
check this one #18789 after fixing
