### ISSUE TITLE
[9.2.4] Incorrect grouping of plants when analyzing the map

### ISSUE THREAD

**Issue by ULiX80** [StrangeLoopGames/EcoIssues#20451]
After patch 0.9.2.0, animal and plant flags were grouped by name. Everything works right with animals. But for the plants, 2 groups were created.

Compare.
Animals (2 flags in one group): 
![изображение](https://user-images.githubusercontent.com/6950252/107306025-ce7cec00-6acf-11eb-8d16-75db38cca14f.png)
 
Plants (**Separate group for each flag**):

![изображение](https://user-images.githubusercontent.com/6950252/107306183-2a477500-6ad0-11eb-9e03-d35099a04ba5.png)

**Comment by SlayksWood** [comment]
Need to check with a new staging build, should be fixed with https://github.com/StrangeLoopGames/Eco/pull/7726

**Comment by SlayksWood** [comment]
fixed in 9.3
