### ISSUE TITLE
USER ISSUE: low FPS

### ISSUE THREAD

**Issue by Marcoxdh1** [StrangeLoopGames/EcoIssues#20458]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
shutting down al back grond progamrs, lower setting	

**Expected behavior:**
at least 100 FPS

**Actual behavior:**
my frames keep droping down til at last 30 but somtimes down to 10 frames i am running the game on a I7700K SSD and RTX 3080 and still low FPS and videos drivers are update to date

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Marcoxdh1** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5951194/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5951195/Player-prev.log)

**Comment by MishkaFur** [comment]
what are your graphics settings in eco set to be?

**Comment by Marcoxdh1** [comment]
![image](https://user-images.githubusercontent.com/74473560/107367129-3850c200-6adf-11eb-9014-0b4798da201a.png)

**Comment by Marcoxdh1** [comment]
![image](https://user-images.githubusercontent.com/74473560/107367189-4b639200-6adf-11eb-8163-920b5182a2c0.png)

**Comment by Marcoxdh1** [comment]
any update?

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are unable to reproduce the issue. Would it be alright for you if we request more information? If so, kindly answer/do the following:

1. For us to be able further investigate the issue, please provide, if possible, a video recording of the whole situation. A recording from when you launch the game until the issue starts happening would be great.
2. Along with the game player logs, please also upload game server logs. To do so, simply navigate to the installed storage files of the game and look for a folder named Eco_Data. Inside that folder, open the Server folder and then the Logs folder. Select the most up to date logs to upload. Please upload logs where the issue has occurred. 
3. Is the issue of FPS drop always happening? 
4. Have you recently upgraded your graphics card to GTX 3080? If so, what was your previous graphics card, and is the FPS drop happening before you upgraded to GTX 3080?

**Comment by Marcoxdh1** [comment]
1. recording wil follow. After i start the game and load in to the server it takes about 2 min for my fps to drops down to 25 til 30 fps.
2. [Eco.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5977998/Eco.zip)
3. after the loading in to the server fps starts dropping right away
4. i have never run this game on any ochter Video kaart i got my RTX 3080 in December and before this i had GTX 1080 and i used DDU to dellet the old drivers and then install the new one from nvidea from ther website. i dont have and probleems in any ochter game only in ECO.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for replying and uploading the game logs. It appears that this is not a driver issue.
We have an existing issue of frames dropping. I will be merging your report with it.

Issue #11248
