### ISSUE TITLE
USER ISSUE: Plow speed glitch (Squirrellzy boost)

### ISSUE THREAD

**Issue by Squirrellzy** [StrangeLoopGames/EcoIssues#20457]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. get plow & set plow down nice flat area
2. preferably run but can walk at the plow from the back
3. last second grab plow
4. hold on for dear life (looking down just a little seems to make it faster)

**Expected behavior:**
walk normally with plow (but i also like this method)

**Actual behavior:**
plow gains 10,000 horsepower and takes off (.... its really fun)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods just a bored farmer with a plow....

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Squirrellzy** [comment]
https://user-images.githubusercontent.com/78796513/107357344-ca78ac00-6a86-11eb-8f07-8a0f114d7276.mp4

**Comment by Squirrellzy** [comment]
also plow will continue to plow even when you let go of left click

**Comment by Squirrellzy** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5951046/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5951047/Player-prev.log)

**Comment by SlayksWood** [comment]
@Squirrellzy Nice catch. I will merged your issue to our big hand plow issue #12046.
