### ISSUE TITLE
[0.9.3.0 beta staging] Missing icons in the Court

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20455]
Missing icon for seizing action in civics.

![Screenshot_25.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b5f130c7-07cd-4ebe-8fac-9e901faea3d9)

**Comment by SlayksWood** [comment]
Hands
![image](https://user-images.githubusercontent.com/45708377/107359630-f7a87700-6ae5-11eb-8b3b-3a07155c46cc.png)

**Comment by keegan-o** [comment]
https://app.zenhub.com/workspaces/saguaro-squad-5f814a78372287000f08fb57/issues/strangeloopgames/eco/7656

The hands icon was made already, or at least a start

**Comment by keegan-o** [comment]
https://app.zenhub.com/workspaces/saguaro-squad-5f814a78372287000f08fb57/issues/strangeloopgames/ecoissues/20325

annnnd here's the other one which is more descriptive, closing this as a duplicate and upping priority of the seizure icon.
