### ISSUE TITLE
Law Issue Item Select

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20465]
You can not select Soft/Hardwood Boards in Laws
![grafik](https://user-images.githubusercontent.com/37456949/107422967-0d389380-6b1c-11eb-9ff7-88b39f27ca7c.png)

**Comment by SlayksWood** [comment]
This is not only Board issue, You can only select ParentItem in laws. The same issue with Hewn Logs, Mortared Stones and etc.

**Comment by WeaselDog** [comment]
Fixed in 9.5 release
