### ISSUE TITLE
USER ISSUE: Doors/Carts/Trucks will ragdoll/non interactable after constant playing.

### ISSUE THREAD

**Issue by TheScopedOne** [StrangeLoopGames/EcoIssues#20467]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Play enough that you start having 30ish frames, and the lighting stops working/becomes bugged. Carts/Cars and doors can then be walked through, non interactable and carts/cars will be pushable, non interactable. Leaving the server and reconnecting doesn't fix. (Atleast that's whats happening to me). Only restarting the game fixes the issue. This only happened because of recent patches, was not a problem before 9.2 was released.

**Expected behavior:**
Even if playing for a long time, i should still be able to interact with doors, carts and cars and not be allowed to push them around, like ragdolls.

**Actual behavior:**
Cars, carts and doors become uninteractable, Carts/cars becomes ragdolls and cannot be interacted with. (But other players can).
For them, they are still affected by the cart/truck/door.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods, This only happens for the client, other people can only witness the chaos, not partake. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5954733/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5954735/Player-prev.log)

**Comment by TheScopedOne** [comment]
I forgot to mention, but Animals has a similar behavior. If they get killed and get stuck, and get teleported, they will also go into a ragdoll state, in which i cannot pick them up, only push them around like a ragdoll.

**Comment by TheScopedOne** [comment]
But whats wierd, is itll go off and on, sometimes it'll let me interact and i cannot push, but then it happens again. so it doesnt seem constant. But still a bug, that is 100% trollable if not fixed.

**Comment by SlayksWood** [comment]
@TheScopedOne Thank you for the report. We will investigate this issue here #20414. You can send all the information there to fix it faster, thanks again.
merged to #20414
