### ISSUE TITLE
Make White Tiger Ecopedia icon into a user icon

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20463]
Approved by John

**Comment by denysaw** [comment]
@SlayksWood Um... Could you please provide the icon file and tell me what rules of giving it? Thanx ;)

**Comment by D3nnis3n** [comment]
![WhiteTiger128](https://user-images.githubusercontent.com/25908592/107499850-c1c2cb80-6b95-11eb-9cf9-10a5f26e81f8.png)
Will be given manually.

**Comment by D3nnis3n** [comment]
Needs implementation on web and in the game.
Code: whitetigericon or tigericon

**Comment by denysaw** [comment]
@j3fffff Renamed your file to be have standard `icon` postfix and added `tigericon` row to a mapping so it would know what to show from DB. On sandbox.

**Comment by D3nnis3n** [comment]
@j3fffff Has this also been implemented IN-GAME?

**Comment by j3fffff** [comment]
made seperate issue for it
