### ISSUE TITLE
Add option for admins or players to remove currency.

### ISSUE THREAD

**Issue by RobertMangano** [StrangeLoopGames/EcoIssues#20479]
A piece of feedback received was, early on in the game players were donating their own currency to everyone in large amounts. When those people leave the server and a dominant currency is established there is no way to remove the donated currency. The concern being that new players joining the server might think that currency is being used.

**Comment by WeaselDog** [comment]
There is a possibility to dump currency at a Treasury. Is this different than what you want?

**Comment by WeaselDog** [comment]
It is also possible for all stores to switch to one persons credit, and then have that person give out the credit to others.

**Comment by IcedForge** [comment]
The treasury object can tax all available currency of a specific type and then you can dump it via its functionality as well.

**Comment by D3nnis3n** [comment]
Also part of this suggestion, hence closing.
