### ISSUE TITLE
[0.9.3 staging(develop-180)] A lot of things are offsetted  in Contract tab of Economy Viewer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20472]
![image](https://user-images.githubusercontent.com/45708377/107503546-25a3bf00-6bab-11eb-90ef-7c14918d0fc4.png)

**Comment by SlayksWood** [comment]
link #18284

**Comment by serpopov** [comment]
Waiting for review visible when waiting for review, otherwise it will say "Removed"
