### ISSUE TITLE
Migration issue 9.0.X > 9.2.4 and 9.1.X > 9.2.4 (Old Sea Otter saves)

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20477]
Unable to boot up a copy of Sea Otter Cycle 20 or 21 for testing things, World files are in Dennis' google drive

Cycle 20 (9.0.x) (Cycle ended 13th Oct)
[log_210210083044.log](https://github.com/StrangeLoopGames/EcoIssues/files/5961460/log_210210083044.log)

Cycle 21 (9.1.x) (Cycle Ended 30th Oct)
[log_210210082356.log](https://github.com/StrangeLoopGames/EcoIssues/files/5961465/log_210210082356.log)

**Comment by TwixterZ** [comment]
Heya @MishkaFur, Iam closing this issue as this is now and old version of ECO (currently at 0.9.6.3 Release)
