### ISSUE TITLE
Glass Visual Bug

### ISSUE THREAD

**Issue by Simon8198** [StrangeLoopGames/EcoIssues#20473]
I'm trying to make a big glass window for my home but there seems to be some kind of visual glitch/shadowing issue.
This happens on the boundary of the chunk. But not consistently as the glass window is in 3 chunks

Here are images of the glitch and my graphic settings.

![Glass Line](https://user-images.githubusercontent.com/13318213/107508465-f5532500-6b98-11eb-8c2c-abfe8134b984.PNG)
![Glass](https://user-images.githubusercontent.com/13318213/107508467-f6845200-6b98-11eb-878e-9aa4d0648185.PNG)
![Graphics](https://user-images.githubusercontent.com/13318213/107508484-fc7a3300-6b98-11eb-9285-375ddc71e952.PNG)

**Comment by SlayksWood** [comment]
@Simon8198 Thank you for the report. This is known issue, merged to #18617
