### ISSUE TITLE
USER ISSUE: District 

### ISSUE THREAD

**Issue by Tbear1825** [StrangeLoopGames/EcoIssues#20481]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Creat a district Map and edit text

**Expected behavior:**
Submitted map with edited text for district names

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__70_3()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Tbear1825  Thank you for the report. CAn you provide your save file before submiting it to investigate your issue? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by SlayksWood** [comment]
#20273

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
