### ISSUE TITLE
I am not sure if this is a bug

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2048]
However i can't figure out or find information on what this is, or why it is making my skill cost increase so much >_<

![new bitmap image](https://user-images.githubusercontent.com/30765409/29954300-30e6f61e-8f1a-11e7-8534-8d16308c5499.jpg)

**Comment by Senbotsu** [comment]
That is intentional.  The more 'trees' you buy skill points in, the more expensive everything gets.  This was implemented to try and force more communal interaction with each person having only one or two specializations.

**Comment by EmuLegs** [comment]
so by Trees do you mean the stuff at the top?

![image](https://user-images.githubusercontent.com/30765409/29955377-902b5d7e-8f22-11e7-89b3-ce7d79f4c9d8.png)

**Comment by EmuLegs** [comment]
what happens when i'm the only one on my server -.-?

**Comment by REPOSEECO** [comment]
In my opinion this is not a solo player game.

**Comment by EmuLegs** [comment]
in my opinion i shouldn't have to enter console commands to play a game

**Comment by noblackthunder** [comment]
you don't need to use commands, but playing alone will just take allot longer then if you play with friends. I general i would recommend to increase the Meteor impact time if you play alone unless you are super fast and can manage to stop the meteor alone =P 

Anyway ! this does not look like a bug so closing this her for now
