### ISSUE TITLE
[Web] Can't seee final cost of upgrade

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20483]
Step to reproduce:
- buy Eco.
- want to upgrade ECO to higher tier. I see calculations, but the final cost is cutted:
![image](https://user-images.githubusercontent.com/45708377/107628701-120f5b80-6c72-11eb-9f67-a8e7d8cc1c5d.png)

**Comment by j3fffff** [comment]
on staging
