### ISSUE TITLE
Account Icons on SLG Website

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20490]
![Screenshot_20210211-140524_Chrome](https://user-images.githubusercontent.com/36024353/107692493-7e8a5a80-6c72-11eb-9396-ea5b4be76e1f.jpg)
It seems like the Hare and Banner icon are the same as Wolf.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/18103
