### ISSUE TITLE
Stockpile plant growth

### ISSUE THREAD

**Issue by JestinJae** [StrangeLoopGames/EcoIssues#20494]
v0.9.2.4 r156

1) Place a stockpile in the grasslands
2) Note that it clears the ground
3) Come back some time later
4) Note that plants have grown below the stockpile and displaced items in the stockpile

image: https://imgur.com/a/jL4RNO1

I don't have exact reproduction steps for this, I just listed roughly what I have noticed.  Its actually quite odd.  It only seems to be happening with one stockpile and (in the picture) it is only those two spots, the rest are normally not growing anything.  This is the first time I've noticed this, but it seems quite odd.  I have cleared the plants once only to have them regrow again, and its the exact same plants.

slgid: slg188711 (primarily a steam user, fyi, I don't know how Steam/SLG accounts are linked so not sure if the icon will credit appropriately in both places)

**Comment by SlayksWood** [comment]
Confirmed. 0.9.3 staging-1931:
![image](https://user-images.githubusercontent.com/45708377/108037292-75bacf80-704a-11eb-85d8-8d46516bd08a.png)
Just place a few stockpile. Use /ff 1, /ff 0 and  I waited maybe 30 minutes (I tested another stuff)

**Comment by Daniel-Magulado** [comment]
Still happening on 0.9.3.1 Release-204
![image](https://user-images.githubusercontent.com/77248866/115115571-ce193980-9fc7-11eb-8955-9bfc357e1f43.png)

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this is fixed in the upcoming 9.6 release.
For linking your account, if your Steam account is linked to your play.eco account then whatever icon you set on play.eco will apply to both.
