### ISSUE TITLE
[0.9.2.4] Resident can't open door on residency they are invited on

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#20495]
A user has reported not being able to open a door on a deed they are an invited resident of while having "Resident access permitted" displayed.  
![bratik_bug](https://user-images.githubusercontent.com/33208603/107719576-d6f44300-6cd8-11eb-850e-38471e7b5f48.png)  

I am awaiting an answer about other objects being usable or not.  
I can provide server files if needed.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
I can confirm that this issue is happening. Tested on 0.9.2.4 Release 164 and 0.9.3 Staging 1935.

**Comment by IcedForge** [comment]
Works as of develop-281
