### ISSUE TITLE
Stockpile is eating resources again.

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2049]
Current staging build.  Stockpiles are eating resources just like they were when stockpiles were first introduced.  I think it's because the rubble takes up more space.  

This can be replicated by filling a stockpile about halfway full with stone/ore and then adding a different block such as dirt or logs. The first 3-5 stacks of dirt/logs will be fine, but after that adding a stack of dirt/logs will erase several stacks of rubble.

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2050

**Comment by metachronism** [comment]
fixed
