### ISSUE TITLE
[0.9.3 staging-1928] Property window: transfer and blur issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20503]
- [x] 1. I don't have blur when open Property window:
![image](https://user-images.githubusercontent.com/45708377/107744536-ed73bc00-6d23-11eb-91a7-723e9adb987a.png)

- [x] 2. Try to transfer property to another player (press cog). You have blur and notification here:
![image](https://user-images.githubusercontent.com/45708377/107744730-44799100-6d24-11eb-9f62-8662cb07977f.png)
- select any player. The UI is broken I can't see whom did I choose:
![image](https://user-images.githubusercontent.com/45708377/107744779-59562480-6d24-11eb-8465-ae24a09572d0.png)
And Seems I have another blur effect, or just some background, because I should click 2 times to select apple.

- [x] 3. I can't transfer Property to another Player. After all manipulations I still the owner.

**Comment by Daniel-Magulado** [comment]
The last windows UI where it states "This will only be permitted if you own the property" opens twice too. Just an update.  Tested on 0.9.3 Staging 1931
