### ISSUE TITLE
9.3.0 1928 - Missing recipes for the 9.2 signs

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20508]
Recipes are missing for the new signs that came in 9.2

![image](https://user-images.githubusercontent.com/61889138/107776464-806b2100-6d39-11eb-91ce-6e3cc7a61ee1.png)

worldobject files for the signs do not have any recipe in them like they do in 9.2 and nothing in the recipes folder, standing glass sign used for examples

![image](https://user-images.githubusercontent.com/61889138/107776652-bf997200-6d39-11eb-87a3-059949e2f9ce.png)

![image](https://user-images.githubusercontent.com/61889138/107776562-a4c6fd80-6d39-11eb-91bb-0f81f7e0bed6.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging 1931.
Fixed and closing.
