### ISSUE TITLE
9.3.0 Staging 1928 - Users.eco does not work, users.eco.template old template not new

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20506]
An existing users.eco will not work in 9.3, users.eco.template is still the old template so had to generate one via server GUI

The new users.eco puts all the admin, blacklist,whitelist etc at the bottom whereas template and existing users.eco it is at the top

Files below from a fresh install of 9.3.0 1928, users.eco was generated via serverGUI with my steamID+SLGID for admin

[users.eco files.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5971888/users.eco.files.zip)

**Comment by WeaselDog** [comment]
Will be fixed as part of https://github.com/StrangeLoopGames/EcoIssues/issues/20177
