### ISSUE TITLE
[0.9.3 Staging-1928]Carriable materials used as Land Claim Stake tool

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20500]
Tested on 0.9.3 Staging-1928.

Issue: Carriable materials such as logs, rocks, gasoline, etc, can be used to claim land area as if you were using a Land Claim Stake tool. However, doing so causes an abnormal in-game behavior where the players are prevented to carry any items.

Repro:
1. Pickup either a wood log or rock such as Hewn Log or Granite.
2. Place a Land Claim Papers on your active toolbar and make sure that it is selected.
3. Put down the item that you are carrying.
4. Observe.

Result: Land area is claimed without using a Land Claim Stake tool.

5. Try to pick up other carriable material that is not the same species you used in step 1.
6. Observe.

Result: Players are unable to carry other items because of this issue.
Screenshot Error:
![Carry.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8a5850a1-8e02-49d7-a8d6-e0fa8a71becb)

Video Repro:
https://images.zenhubusercontent.com/47210472/8f3d761c-18ac-4ecf-ad4a-afd05207e550/2021_02_12_12_19.mp4

Note:
- In this video, I am carrying a gasoline while a Land Claim Papers is selected on my active toolbar. After placing the gasoline down, the land where I placed the gasoline gets claimed, and the Land Claim Papers gets consumed. Furthermore, I am unable to pickup the gasoline afterward.
- You also won't be able to remove the used carriable material unless you are carrying the same material on hand.

**Comment by SlayksWood** [comment]
need to check with constructed blocks

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-203.

Appears to be fixed. Unable to select claim papers while holding or carrying an item.

Resolution: Closing.
