### ISSUE TITLE
USER ISSUE: Stockpile Disappeared 

### ISSUE THREAD

**Issue by dylanviey** [StrangeLoopGames/EcoIssues#20502]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Not sure how it disappeared. Went to place a broken sickle inside by right clicking then got the message "you can't pick up items inside another world object" Then I stepped back and noticed the stock pile was gone but all the items that where inside where still there. Not sure if that caused it or if there was a load error and I just didn't notice as I was walking up to it. 

A log off and log on fixed the issue.. (playing solo all day) probably related to how long the game has been running continually  been going for about 13hours. (I walk away and let things process a lot as I do other things)

**Expected behavior:**
Should still be here and allowed me to place an item inside.

**Actual behavior:**
It disappeared and the items inside are still there.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope stock game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5969896/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5969898/Player-prev.log)
![20210212004845_1](https://user-images.githubusercontent.com/64542696/107735399-97742980-6ccd-11eb-83f0-6e74a4613e66.jpg)

**Comment by SlayksWood** [comment]
@dylanviey did it appear after restarting the game?

**Comment by dylanviey** [comment]
Yes it did. I didn't do a full restart just disconnected and rejoined. (playing solo so it restarted the server when I did that.) I was thinking maybe the game has been running to long and maybe was starting to have issues keeping track of objects.

**Comment by SlayksWood** [comment]
merged to #19797 to investigate.
