### ISSUE TITLE
USER ISSUE: Waxed Hewn Benches can't be made

### ISSUE THREAD

**Issue by nlducker47** [StrangeLoopGames/EcoIssues#20505]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Hewn Benches are in inventory with wax but do not show as available in the recipe. Hewn Benches have been readded to storage and to the hotbar but neither worked.

**Expected behavior:**
Ability to upgrade Hewn Benches to Waxed Hewn Benches.

**Actual behavior:**
Waxed Hewn Benches cannot be made,

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MishkaFur** [comment]
Please can you confirm what waxed hewn benches are? the game has the below

Hewn Bench
Softwood Hewn Bench
hardwood Hewn Bench

**Comment by jamesyoung79** [comment]
Waxed hewn benches are part of the [ https://forum.play.eco/filebase/file/272-beekeeping-mod/](beekeeping mod). This is an issue to be taken up with the mod creator.

**Comment by IcedForge** [comment]
Closing this as jamesyoung mentioned, it is a mod problem need to take it to the mod author.
