### ISSUE TITLE
9.3.0 1928 Cotton plant's Branch near invisible after about 4metres

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20513]
Cotton plants branch goes invisible (other plants do similar ie corn which can be seen in the pic) which from a distance makes it look rather......odd

![image](https://user-images.githubusercontent.com/61889138/107782681-41d96480-6d41-11eb-814a-0760ce53b4dd.png)

![image](https://user-images.githubusercontent.com/61889138/107782897-86650000-6d41-11eb-8f55-c3e0d8e99d59.png)

**Comment by keegan-o** [comment]
Yeah the LOD just overall does not look good. I tweaked it (and corn to be more generous and still have a shadow on the LOD 1 since it's an overall skinny plant.
