### ISSUE TITLE
9.3.0 1928 Cotton description text says "Copper thread" not cotton thread

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20510]
![image](https://user-images.githubusercontent.com/61889138/107779059-c5dd1d80-6d3c-11eb-8a65-5fed8042479a.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1930

It now says **Cotten** Thread. Should be Cotton Thread.
![Cotten Thread](https://user-images.githubusercontent.com/77248866/107888781-81729d00-6f49-11eb-92ab-c0ae87cec122.jpg)
