### ISSUE TITLE
9.3.0 1928 Picking up wool/cotton/nylon curtains shows as "Nylon Carpet"

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20511]
Cotton, Nylon or Wool Curtains in stockpile then picking them up via hammer says you received Nylon Carpet though the icon is correct the text is not

![image](https://user-images.githubusercontent.com/61889138/107780196-47817b00-6d3e-11eb-8b3a-b97cff449891.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging 1931.
Fixed and closing.
