### ISSUE TITLE
9.3.0 1928 - Unable to migrate from 9.1.x

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20515]
Unable to migrate WT Cycle 9 or Sea Otter Cycle 22 to 9.3 1928

My server on 9.2.4 did migrate to 9.3 though

Appears to be both related to Economy Manager
![image](https://user-images.githubusercontent.com/61889138/107790464-b1078680-6d4a-11eb-83cb-fabd5e7aba63.png)

WT Cycle 9 log
[log_210212034645.log](https://github.com/StrangeLoopGames/EcoIssues/files/5972860/log_210212034645.log)
[2021-02-12.log](https://github.com/StrangeLoopGames/EcoIssues/files/5972855/2021-02-12.log)

Sea Otter Cycle 22
[log_210212035106.log](https://github.com/StrangeLoopGames/EcoIssues/files/5972879/log_210212035106.log)
[2021-02-12.log](https://github.com/StrangeLoopGames/EcoIssues/files/5972880/2021-02-12.log)

**Comment by tomsseisums** [comment]
@MishkaFur do you have a save file you could provide for you world?

**Comment by MishkaFur** [comment]
> 
> 
> @MishkaFur do you have a save file you could provide for you world?

Please ask Dennis for access to the historical official server worlds on google drive, I had it on White Tiger Cycle 9 and Sea otter Cycle 22
