### ISSUE TITLE
9.3.0 1928 - Flagged by Avast AV software 

### ISSUE THREAD

**Issue by LeonHarl** [StrangeLoopGames/EcoIssues#20516]
**Observed Issue:**
When opening 9.3.0 1928 for the first time Avast anti virus detected that the application was suspicious (It is not scanned on subsequent re-installs). An automatic scan of the application was performed and no issue are found. 
When ECO 9.3.0 1928 is closed Avast alerts again only this time its deemed too suspicious and marked for removal.  

**Evidence:**
![image](https://user-images.githubusercontent.com/78972689/107793139-42c8c100-6d56-11eb-935d-ba7cd571d350.png)

**Testing Method:**

Pass 1
Installed 9.3.0 1928 (Steam)
Opened ECO - Flagged As suspicious
Closed ECO - Flagged as suspicious and removed.
Pass 2
Reinstalled ECO 9.3.0 (Via a repair on Steam)
Opened up ECO - No issue observed on subsequent tests.
Closed ECO - Flagged as suspicious and removed. 
Pass 3
Reinstalled ECO 9.3.0 (Via a repair on Steam)
Opened up ECO - No issue observed.
Closed ECO - Flagged as suspicious and removed.

**Comment by LeonHarl** [comment]
This is irrespective if a server is joined or not.

**Comment by D3nnis3n** [comment]
This is a false-positive. We've tried to work with AV developers to get such issues sorted in the past and their collaboration was miniscule to say at best, I'll try to do the same this time, but do not expect any better result.

My recommendation: Get rid of that.
