### ISSUE TITLE
9.3.0 1928 Unable to shift drag items in storage

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20512]
Unable to shift drag seeds from tractor into storage silo as it just shows the below, silo obviously had space.

![image](https://user-images.githubusercontent.com/61889138/107781357-b9a68f80-6d3f-11eb-85d5-cff8c0d41319.png)

Shift dragging say a stack of land claim papers only moves the stack I dragged (no error message)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. I can confirm that this issue is happening. Tested on 0.9.3 Staging-1930.

Added a video repro below:

https://images.zenhubusercontent.com/47210472/5ff10817-73a5-4b9b-8ce7-036a0f8caa33/2021_02_16_10_58.mp4

**Comment by AndriusRimk** [comment]
Hi, any progress on this issue as it's still in 9.3.1 release-204

**Comment by IcedForge** [comment]
closing as this should be fixed in upcoming hotfix (0.9.3.2)
