### ISSUE TITLE
Hoe, Bow, Soil Sampler don't get damaged on use

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2051]

**Comment by Senbotsu** [comment]
Add the scythe to that list.  (Legacy Scythe though, I haven't made a stone scythe since mine isn't breaking)

**Comment by MarjieAVolk** [comment]
Oh, closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1940 - I'll move this list over there
