### ISSUE TITLE
Water in spring changes color, maybe according to sun

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20519]
![image](https://user-images.githubusercontent.com/25908592/107804853-c7224080-6d64-11eb-95be-ef7ea8e81b83.png)
![image](https://user-images.githubusercontent.com/25908592/107804861-c9849a80-6d64-11eb-80f7-c85109ba1bc9.png)
![image](https://user-images.githubusercontent.com/25908592/107804868-cb4e5e00-6d64-11eb-8461-361d5a1aa71b.png)
![image](https://user-images.githubusercontent.com/25908592/107804875-cc7f8b00-6d64-11eb-8e14-0a11cf469e05.png)
![image](https://user-images.githubusercontent.com/25908592/107804877-cdb0b800-6d64-11eb-959b-7fd70dd14c5b.png)

**Comment by Jason-Skillman** [comment]
After investigating I found that the atmosphere's color was dominantly being applied to the water and foam color at certain times of the day. Time: 6-7 (Dawn), 17-18 (Dusk) where the strongest times affected.

### Solution
I removed `_LightColor0` from both the water and foam color variables in the `CalmWater.cginc` shader. All changes were on SNV. Commit # 8334

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.

The main issue seems to be fixed but it somehow removed the liveliness of the water and made it dull looking. It also made the foam almost invisible at certain times of the day. Maybe brighten up the color of the foam? 

See the comparison below:

https://user-images.githubusercontent.com/77248866/120484150-5e2f0900-c3e5-11eb-9249-7e91a15c3724.mp4

**Comment by Jason-Skillman** [comment]
I just added `_LightColor0` back into the shader but left out the color. The brightness seems to have come back, and the color based on time of day should be gone.

**Comment by TwixterZ** [comment]
Fix observed on fountains and sea. Confirmed as of 9.4 Staging 2009

![water4.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/33bb1dc2-30b0-4d9d-9725-26320ee42137)

**Comment by D3nnis3n** [comment]
Thanks!
