### ISSUE TITLE
USER ISSUE: where is the sign?

### ISSUE THREAD

**Issue by TimoNuernberg** [StrangeLoopGames/EcoIssues#20525]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
einen Dampfwagen aufstellen,
den Text im Feld Text eintragen	

**Expected behavior:**
am Heck, sollte der Text stehen

**Actual behavior:**
kein Text, kein Schild; bereits bekannt?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/63196305/107833716-74607d00-6d94-11eb-9ce5-eb5a2f7ce1ae.png)

**Comment by Daniel-Magulado** [comment]
Hallo, Vielen Dank für die Berichterstattung. 
Leider können wir das Problem nicht reproduzieren.

Könnten Sie weitere Informationen zum Problem bereitstellen?

Eine Videoaufnahme hilft uns, das Problem zu bestätigen. Wir empfehlen außerdem, die Spielprotokolldateien hochzuladen. Sie können dies tun, indem Sie den Anweisungen hier folgen https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Haben Sie nach dem Melden dieses Problems eine Unterbrechung oder einen Serverabsturz festgestellt?

Haben Sie versucht, die Verbindung zu trennen und erneut herzustellen, um das Problem zu beheben?

Ist das Problem konsistent oder kommt es nur manchmal vor?

Der Fehler könnte dieser Ticketnummer ähnlich sein. #20144

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
