### ISSUE TITLE
USER ISSUE: Mining Bug

### ISSUE THREAD

**Issue by MaxWam** [StrangeLoopGames/EcoIssues#20529]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Mine into an area that is only 2 blocks high
2. Mine straight up
3. Glitch to the surface

**Expected behavior:**
Nothing

**Actual behavior:**
Glitch throught the ground to surface

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes im on ALL CAP server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are already aware of the issue. Thank you for your time in reporting this.
The report will be merged to #10345.
