### ISSUE TITLE
Khord user feedback: "You should be able to just hit escape on any given menu and have it close."

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20539]
This should be the case already? check menus
https://docs.google.com/document/d/1nFnxlEBwzV4lkEiE6BhzuS-p0obhNJO7GrjTNvUZxVQ/edit

**Comment by D3nnis3n** [comment]
Before applying this to the backpack, give the backpack a pin function that disables this behaviour as we have at least a 50:50 situation on people playing with backpacks opened.

**Comment by IcedForge** [comment]
I believe this works for all items / ui's except campsite and backpack.
The backpack is intended as per last issue with it 
#20369 - issue for not closing it with esc
 #18045 - issue for it being closed with esc

As it is like dennis mentions a pretty large split in the community where both sides wants the opposite effects.
Players that wants to keep backpack open to keep track of inventory contents and easy access do not want to close it when they close other ui's

And the opposite side that wants to close it with esc together with the rest of the opened UI's.

This needs to have a PIN function before this behavior is changed.

**Comment by IcedForge** [comment]
Making separate issues, i couldn't find one for the campsite UI issue

**Comment by IcedForge** [comment]
#20617 - Issue for making the backpack Pinnable.
Campsite UI closable by ESC is fixed in 9.3.

Will close this in favor of this.
