### ISSUE TITLE
Unable to log in staging cc778b68

### ISSUE THREAD

**Issue by Ridededog** [StrangeLoopGames/EcoIssues#2053]
Having an error message comes up whenever I try and log in, (not getting onto a server, just entering username and password) 

"Error getting response stream (ReadHeaders): ServerProtocolViolation"

It only seems to happens on 6.0. I can log in on 5.6.1, website, forum.

I have even deleted the Eco folder in appdata on Pam's suggestion.

Pam also said that the authentication server was not having an issue.

Only seems to be happening to me.

**Comment by noblackthunder** [comment]
Only info i found was this her on the error .. not allot of help for me but maybe you ? not sure if the the fix needs to be done on the server. I guess Eric might know. https://stackoverflow.com/questions/6237734/how-to-request-only-the-http-header-with-c

**Comment by Ridededog** [comment]
Still does not work with latest staging (#2ed68eec)

**Comment by Fank** [comment]
Confirmed and linked, @Ridededog which os are you using?

**Comment by Ridededog** [comment]
Window 10

**Comment by metachronism** [comment]
guessing this is a .net46 compatibility issue, downgrading back to 3.5

**Comment by Ridededog** [comment]
Tested with 9e7f060. Problem been fixed. Many thanks
