### ISSUE TITLE
USER ISSUE: Build menu - "Roof Peak Set" and "Roof Corner" are displayed with the wrong image whn choosing them

### ISSUE THREAD

**Issue by marcel-ruoff** [StrangeLoopGames/EcoIssues#20532]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Build a house with lumber. If you choose the second time someting between "Roof Peak Set" and "Roof Corner" there are the images shown in the wrong way. You automatically then try the build the wrong of them.

**Expected behavior:**
If you choose one of the two options there should be built the right one

**Actual behavior:**
You try the build the wrong part, although you have choosen the right one

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed. Latest version.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are unable to reproduce this issue.
For us to further investigate this issue, we would like to request more information.
Kindly provide us the game log files after the issue has occurred. To do so, please follow the instruction here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Additionally, we also would like to request you to upload a recorded video of the issue as it happens.
Thank you.

**Comment by marcel-ruoff** [comment]
in this screenshots you can see the error. You used the wrong images (icon) behind the button. The mouse-over is correct what I then can use, but not the image over which is my mouse. Both the screenshots show that the mouseover is not the same as the icon, the are the wrong way round.

![2021-02-15 15_44_56-Eco](https://user-images.githubusercontent.com/52975172/107960586-1bb3fe80-6fa5-11eb-9105-b2651cfbcd46.png)
![2021-02-15 15_44_23-Eco](https://user-images.githubusercontent.com/52975172/107960601-1eaeef00-6fa5-11eb-8d32-e1f385a31495.png)

**Comment by marcel-ruoff** [comment]
I've talked with some players of my current servers. Some see it as an annoying bug and always type on the wrong of them. If you look for the roof top, then picture 5 (yellow, from left) seems right. Some not, when building a house. You can close the report.
