### ISSUE TITLE
[0.9.3 Staging-1929]Vehicle Auto Moving gets halted when pressing enter successively

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20533]
Tested on 0.9.3 Staging-1929

Issue: Auto moving vehicles get halted sometimes after pressing Enter key. The issue is easier to reproduce when pressing Enter successively.

Note:
- The chatbox must be open for the issue to happen.
- Once the vehicle stops after pressing Enter, closing the chatbox allows the vehicle to auto move again without pressing the auto move key.
- Happens on all vehicles.
- The issue is unreproducible if the avatar is set to auto move while walking.

Repro:
1. Ride a vehicle such as Steam Truck, Wood Cart, etc.
2. Bind a key to Auto Move on the settings.
3. Press the Auto Move key to auto-drive the vehicle.
4. Press Enter successively and observe.

Note: It's easier to reproduce if you open the chatbox first and then press Enter successively. So that at the end of every successive press, the chatbox is open.

Video Repro:
https://images.zenhubusercontent.com/42199084/2751d4b8-716d-460a-8a44-b4046fc772a0/untitled.mp4

On the video, I have set F3 as my auto move key. I also tried to bind auto move on other keys such as G and J. The issue still occurs.

Logs
- [Player](https://app.zenhub.com/files/42199084/e3795b6a-98a6-42f5-88c0-f6fdcec21a12/download)
- [Server](https://app.zenhub.com/files/42199084/e84dcd46-e162-470b-9520-f7926b4adcbc/download)

**Comment by MishkaFur** [comment]
Also happens in 9.2.4 I believe, soon as you start trying to chat ingame it stops vehicle auto move

**Comment by WeaselDog** [comment]
Same with opening the map or pressing tab

**Comment by StanKryvenko** [comment]
Fixed in SVN

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2021
