### ISSUE TITLE
9.3.0 1929 Clicking on a deed always defaults to bottom of window

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20534]
it always has you scrolled down to the bottom, should be at the top

Below is what opens when clicking on a deed name, just incase, screen res is 3840x2160 and interface scale 70%
![image](https://user-images.githubusercontent.com/61889138/107858934-96a6d900-6e2e-11eb-8627-d2857e8ac1e1.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-203.

Appears to be fixed. Opening the DEED UI, the window pop-ups with the scroll bar starting at the top.

Resolution: Closing.
