### ISSUE TITLE
[0.9.2.4] USER ISSUE: The tool does not change while dragging. 

### ISSUE THREAD

**Issue by ULiX80** [StrangeLoopGames/EcoIssues#20548]
\
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
The backpack contains a working shovel.
There is a broken shovel in the quick slot.
Try replacing a broken shovel with a working one, or vice versa by dragging and dropping. 
(Pickaxes or others tools can be used instead of shovels. )

**Expected behavior:**
Prior to patch 0.9.2.x, such actions allowed quickly replacing broken tools with serviceable ones, for example, during repairs. 

**Actual behavior:**
There is no replacement in the current version of the game.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Mods not installed.

[Video](https://youtu.be/Mq1fSNkVmNM)

https://youtu.be/Mq1fSNkVmNM

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. We are already aware of this issue. #20149
