### ISSUE TITLE
Stone Road missing?

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#2054]
Is there anyway to make stone into road after moving the stone ?

**Comment by MarjieAVolk** [comment]
Currently you can make a road from a placed stone block, then pick that up and put it elsewhere.  You can't turn stone rubble back into stone to make a road.  Which is a bit odd.

Maybe we can add a crafting recipe for a stone road?

**Comment by EmuLegs** [comment]
it never entered my mind to dig the premade road o.O

**Comment by Frozen-byte** [comment]
indeed receipts for stoneroad would be a cool step between dirt and concrete!

**Comment by craig-jong** [comment]
dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/2232
