### ISSUE TITLE
Declunkify: User feedback: Consider faster movement

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20540]
"Movement. Oh boy. This is actually one of the two reasons I've since stopped playing this. Why do you move so very, VERY slow? Even when "sprinting" I'm slow as molasses. Then, I can jump higher than my entire body height and PLEASE DON'T CHANGE THAT it's great to just leap up the side of a cliff to a few key points. Make the sprinting speed the walking speed and the sprinting speed about tripled and it might feel close to okay though."
https://docs.google.com/document/d/1nFnxlEBwzV4lkEiE6BhzuS-p0obhNJO7GrjTNvUZxVQ/edit

**Comment by IcedForge** [comment]
For references in movement.
Using 56 tiles length to track.

On movement speed 1.0 ( default dirt/packed dirt )
Walking : 18.57s
Running : 12.17s
Steam Truck : 12.17s
Truck : 11.05s

Not really sure what the user wants from this game? This is not a super fast paced shooter FPS game?
Movement is rather rapid considering other comparative games such as wurm, minecraft, astroneer, empyrion etc 
The alternative model that most other games ( not included the mentioned ones)  offer a LIMITED sprint functionality vs our no stamina limit. In which users are allowed to sprint at a much more improved rate but only for a hard limit time of 5-10s and need to gain stamina back to be able to sprint again, which makes the medial distance over time the same just in a different approach.

**Comment by johnkslg** [comment]
Let's add a more pronounced sprint-mode:
- [ ] When sprinting, have a stamina bar pop up that goes down rapidly.
- [ ] Make a skill for sprinting
- [ ] Increase speed for sprinting
- [ ] Increase speed for walking
- [ ] Reduce penalty for bushes somewhat

**Comment by j3fffff** [comment]
Also, using tools has an uncomfortable few second delay.
compare with other games, should be near instant when i click mouse button.

**Comment by johnkslg** [comment]
@j3fffff made separate issue for that: https://github.com/StrangeLoopGames/EcoIssues/issues/20604

**Comment by IcedForge** [comment]
Its very susceptible to looking very slow depending on what your other games you play are, if you look at things like Satisfactory for instance where you have a lot of utility movement aiding systems like exo legs/flight makes it a night/day situation and if you are used to these very rapid movements coming into this game ( and similar movement titles like medieval engineer/space engineer(unless you use jetpack) it doesnt really differ that much on land movement wise.

I think experimenting with perhaps a 10-15% movement increase at the maximum just to give a "boost" to it if this is something we want ( so current "sprint speed" would be normal walk speed and sprinting would be slightly faster) but trying this out makes it feel very unatural and "forced" so im not really sold on the idea that making the character move faster = "Faster" in a good way.

**Comment by johnkslg** [comment]
Before closing can you up the sprint speed too?

**Comment by IcedForge** [comment]
Updated SVN for sprint speed as well.

**Comment by IcedForge** [comment]
Stamina bar for sprinting and limiting it via this way will take a bit design perspective UI wise as i am not sure where this should be displayed, in what way; do we need new walk/run animations for out of breath situations? 
First person UI display of stamina vs 3rd person view ? Will make a new issue specifically for Stamina Bar and sprint limitations.
