### ISSUE TITLE
USER ISSUE: Roots to strong to dig

### ISSUE THREAD

**Issue by BigDCowboys22** [StrangeLoopGames/EcoIssues#20549]
![20210214114156_1](https://user-images.githubusercontent.com/27888102/107882971-28a7f380-6eba-11eb-843a-c3b82f6f206d.jpg)
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Digging ramp.  3x3 grid with no plants, roots, or tree stumps nearby that won't let me dig or mine.

**Expected behavior:**
Allowed me to dig

**Actual behavior:**
Gives me a roots too strong warning

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5978076/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5978077/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are unable to reproduce this issue.
If it's alright with you, could you please provide a recorded video of how you encountered this problem?
Thank you.

**Comment by sirPattrick** [comment]
Big D, attempt to smack the area where a tree would be with an axe, the tree may be invisible.   I have had that happen in the past.

**Comment by BigDCowboys22** [comment]
Unfortunately I didn't get a video of the issue.  I did attempt to axe all around the area to no avail.  I came back a while later (few hours I think) and there was a fully grown tree in the spot that was giving the issue.  I was able to cut down the tree and roots and then I could dig up as expected.  I wasn't smart enough to capture the grown tree later.  Sorry about that.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for sharing with us some additional information. We are currently aware of some disappearing or invisible issues in-game. I'll include this report in the earlier-filed similar issue.

Thank you for your time and for this report.
