### ISSUE TITLE
Mouse sensitivity was default to 0.01

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20542]
![image](https://user-images.githubusercontent.com/3536496/107863858-31da8700-6e0c-11eb-86c7-02498a6c6128.png)
player prefs deleting yielded this
![image](https://user-images.githubusercontent.com/3536496/107863869-461e8400-6e0c-11eb-97d2-8ccd5122cee3.png)

**Comment by johnkslg** [comment]
It shouldnt be allowed to go that low, you cant even move it

**Comment by SlayksWood** [comment]
merged to #20244
