### ISSUE TITLE
Server browser doesnt go away when joining

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20553]
![image](https://user-images.githubusercontent.com/3536496/107895377-fc0ad080-6ee7-11eb-9d64-d41c7c41e5b9.png)
Instead it gets overlapped by the loading text and looks like crap.

**Comment by johnkslg** [comment]
Also, add a darkened box behind it so it doesnt clash with the background:
![Uploading image.png…]()

**Comment by SlayksWood** [comment]
dup #20249
