### ISSUE TITLE
Broken work order stuck in top right corner

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20559]
![image](https://user-images.githubusercontent.com/3536496/107896315-c2879480-6eea-11eb-89d9-b11ab1acf2b6.png)

**Comment by SlayksWood** [comment]
Need to fix/test on 0.9.4 develop

**Comment by TwixterZ** [comment]
Issue tested on 0.9.4 and 0.9.5 builds and unable to reproduce. 

Closing issue now, to re-open when issue arise again.
