### ISSUE TITLE
Declunkify: Change tutorial to be cleaner

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20555]
The tutorial text box hangs awkwardly from the bubble:
![image](https://user-images.githubusercontent.com/3536496/107895979-f57d5880-6ee9-11eb-86f8-62f98b6bf399.png)

Make it integrated into the bubble more, like it belongs there and is the expanded view of it. Something like this perhaps, but better:
![image](https://user-images.githubusercontent.com/3536496/107895982-f9a97600-6ee9-11eb-906c-f3fa13999af6.png)

It can push out a little but and then fold out.

**Comment by MilenkoTunjic** [comment]
Can we fix the font size (make it smaller and fix spacing) and remove bold from the font. It always feels that the font is unnecessarily large. and adjust boxes to fit as per mock up sketch, to start with.

**Comment by MilenkoTunjic** [comment]
And ah yes, we can do the integration and opening of the tute as one piece. If someone wants to ping me I can steer it there :)
