### ISSUE TITLE
Opening the settings when the minimap is small breaks it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20560]
![image](https://user-images.githubusercontent.com/3536496/107896466-2dd16680-6eeb-11eb-96ed-607d164d26d0.png)
It should expand out of the box, and never off the edge of the screen.

**Comment by SlayksWood** [comment]
Can't reproduce in staging-1930. On which branch did this happen?
![image](https://user-images.githubusercontent.com/45708377/107909920-619fa100-6f6a-11eb-88cf-d4825010da2a.png)

**Comment by SlayksWood** [comment]
Need to fix/test on 0.9.4 develop

**Comment by beastyn** [comment]
Could not reproduce (though I have made minimum size wider so gear will fit to the window)
