### ISSUE TITLE
[0.9.3 staging-1930] Markers has wrong position after changing Camera mode.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20569]
Step to reproduce:
- Create a several markers:
![image](https://user-images.githubusercontent.com/45708377/107918618-12ae3780-6f7b-11eb-9822-43ae4e05dfab.png)
- Change Camera mode to 3D and don't mpve map:
![image](https://user-images.githubusercontent.com/45708377/107918668-248fda80-6f7b-11eb-8e43-490d5699abdf.png)
- move minimap a little:
![image](https://user-images.githubusercontent.com/45708377/107918688-2fe30600-6f7b-11eb-9b81-b6e89b370538.png)
- change camera mode to 2D:
![image](https://user-images.githubusercontent.com/45708377/107918739-44bf9980-6f7b-11eb-87cc-094b50616d74.png)
- move minimap a little:
![image](https://user-images.githubusercontent.com/45708377/107918761-5012c500-6f7b-11eb-84cc-e63417d110bd.png)
- player icons have the same problem.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-297.
Closing as fixed.
