### ISSUE TITLE
Version 9.2.4 crashing on Windows randomly "Faulting application name: Eco.exe, version: 2019.4.15.62311, time stamp: 0x5faf2fe3"

### ISSUE THREAD

**Issue by zerbey** [StrangeLoopGames/EcoIssues#20563]
Faulting application name: Eco.exe, version: 2019.4.15.62311, time stamp: 0x5faf2fe3
Faulting module name: d3d11.dll, version: 10.0.19041.746, time stamp: 0xfc177b9d
Exception code: 0xc0000005
Fault offset: 0x000000000012c370
Faulting process id: 0x33f8
Faulting application start time: 0x01d703408ab7b3d1
Faulting application path: D:\SteamLibrary\steamapps\common\Eco\Eco.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d11.dll
Report Id: 31e42a51-b440-4bf2-a1e1-25f7db8b5ccc
Faulting package full name: 
Faulting package-relative application ID: 

Possible error with Direct3D library?

nVIDIA GTX 970 with Ryzen 5 3600X processor.  Running latest GeForce drivers.

Please let me know if you need anything, no game log was generated but I'm not sure if there's a way to enable this?

**Comment by IcedForge** [comment]
@zerbey Thank you for reporting.

Please include playerlog / server logs as these should be generated on game launch.
Also please include pc specifications and a Dxdiag file as well.

And is this just happening intermittently or in specific cases?

**Comment by zerbey** [comment]
Attaching server logs and dxdiag output.  I did not see any player logs in either the AppData location or the game's install folder.  Please let me know where these are located.  Of note, only Eco seems to have this issue, other Steam games using Direct3D run fine.

PC specifications are in my original report, is also has 16GB of RAM and is running Windows 10.

If you need anything else please let me know.

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5997305/DxDiag.txt)
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5997307/Logs.zip)

**Comment by zerbey** [comment]
Noticed it was running an older feature release of Windows, I'll update to that also and if issues persist I'll report here.

**Comment by IcedForge** [comment]
Will close this issue as per OP made changes and never replied, will assumed it as solved.
