### ISSUE TITLE
USER ISSUE: Election Not Ending

### ISSUE THREAD

**Issue by czach8** [StrangeLoopGames/EcoIssues#20565]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Created a new elected title for the treasury.
Approved the new elected title.
Started an election for the new treasurer title.
Only one candidate was entered.
Four of six people on the server voted in favor of the candidate.

**Expected behavior:**
The candidate should have been elected into office or the election should have ended.

**Actual behavior:**
The vote has gone on for more than 24 hours but the candidate has not been given the title nor has the election ended. The "Since" timer is still going up and the "Voting will end in" timer is staying on 0 secs. Looking at the votes all 4 people voted for the single candidate and the other 2 people on the server abstained.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@czach8 Thank you for the report. Can you provide more details? some screenshots of you Elected title setting, election settings and etc. or just provide your save file to investigate your issue.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by IronyTroll** [comment]
We are still experiencing an ongoing issue where elections do not end unless the server has been rebooted. If the election were to run for 24hrs, it has been up to 100 hours before it 'completed' when the server got rebooted.

Below is a list of possibly related tickets.

#20565
#22200
#22201
#20311

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/22200
