### ISSUE TITLE
Respawn /Spread of new Plants/Trees

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20567]
Fix the Spawns of new Plants & Trees. 
After removing from Plants or Tree they spawn new ones. Trees are particularly affected. Because you can fell them without consequence if new one spawns without use of Seeds. 

The Old Redwood respawns too

Example:
Cut down some Trees and some time later a crazy amount of new Trees Spawns 
![grafik](https://user-images.githubusercontent.com/37456949/107915101-18e4e980-6f64-11eb-801c-4e83962ab2ce.png)
![grafik](https://user-images.githubusercontent.com/37456949/107915437-c48e3980-6f64-11eb-96b1-1facf3e9bb6e.png)

**Comment by mirasrael** [comment]
I changed spawn logic. Now it won't grow partial plants (this is main reason of popping up plants right after their removed).
I wasn't able to reproduce issue with Old Redwood respawn. Can you make a repro case and attach the world?

**Comment by TwixterZ** [comment]
fix tested and confimed on 9.4 develop 250 

trees felled now spawned tree sprouts on moderate rate instead of partially grown trees.
