### ISSUE TITLE
[0.9.3 staging-1930] Transaction window doesn't work

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20574]
Step to reproduce:
- make some money transfers, buy/sell something or just create currnecy in mint.
- open Transaction window by clicking on account name.
- transaction window is empty:
![image](https://user-images.githubusercontent.com/45708377/107933738-33cd5300-6f90-11eb-85dc-50da01175f43.png)

**Comment by mirasrael** [comment]
Probably after my changes for max transactions lengths.

**Comment by mirasrael** [comment]
Checked. Related to @olegshegai commit:
https://github.com/StrangeLoopGames/Eco/commit/ef5f9eec780436a5f9a087ca47fbf3c5190bda97
There no call to AccountLedger.AddTransaction in code after the refactoring.

**Comment by SlayksWood** [comment]
Mint here #19847

**Comment by IcedForge** [comment]
fixed in 9.3 staging 1937
