### ISSUE TITLE
[0.9.3.0 beta staging-1930]Statistics gone from web interface

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20571]
Missing an entire element of the web UI with the statistics
![Screenshot_1](https://user-images.githubusercontent.com/24981362/107920050-97458980-6f6c-11eb-90a8-2b66235b800b.jpg)

**Comment by denysaw** [comment]
Created a PR. Hopefully it'll be approved/merged soon.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/111120886-0074e880-857d-11eb-82a8-fd85d4e11f09.png)
