### ISSUE TITLE
9.3.0 1930 - Tree foliage vanishes at about 125metres distance

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20580]
Tree foliage disappears at about 125m distance making screenshots ugly :(

This might be related to #20513 where Cotton does the same but at 4m.

![image](https://user-images.githubusercontent.com/61889138/107972306-908a3700-6fab-11eb-9cbc-27d8c0fff53b.png)

![image](https://user-images.githubusercontent.com/61889138/107972431-bca5b800-6fab-11eb-91a9-f87fdef393e6.png)

**Comment by Daniel-Magulado** [comment]
This is actually happening to me too. Tested on 9.3 Staging 1930. Could also be related to #20501

**Comment by SlayksWood** [comment]
[ ]  2. Сhanging shadows:
![image](https://user-images.githubusercontent.com/45708377/109263930-34c67600-7815-11eb-8758-223f6d28059a.png)
make the trees behind:
![image](https://user-images.githubusercontent.com/45708377/109263993-4c9dfa00-7815-11eb-8a3f-1f6d5e10c584.png)
[ ]  3. Leaves start blinking when cross world border:
https://user-images.githubusercontent.com/45708377/109264059-68090500-7815-11eb-9328-e960d9cb418f.mp4

**Comment by mirasrael** [comment]
May be related to change when tree foliage was changed to IndirectRendering. It may be culled out by occlusion culling. Probably occlusion culling should be disabled for tree foliage.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/110099535-75dcfe00-7db2-11eb-9a35-f96647e1d2b8.png)
and some interesting videos with cutting it:

https://user-images.githubusercontent.com/45708377/110099997-fb60ae00-7db2-11eb-908f-d32b8e15eb22.mp4

https://user-images.githubusercontent.com/45708377/110100170-26e39880-7db3-11eb-997c-1dfd92ab130e.mp4
The same with other trees.
Perhaps related with

**Comment by mirasrael** [comment]
It should be shader variable for IndirectRenderingPreprocess.compute which disables IsOCVisible check. This variable should be set to `false` by default, but for tree foliage it may be set to `true`.

**Comment by SlayksWood** [comment]
Still exist this 2 problem.
- [ ] 1. Сhanging shadows:
![image](https://user-images.githubusercontent.com/45708377/109263930-34c67600-7815-11eb-8758-223f6d28059a.png)
make the trees behind:
![image](https://user-images.githubusercontent.com/45708377/109263993-4c9dfa00-7815-11eb-8a3f-1f6d5e10c584.png)

- [ ] 2. Strange tree crowns
![image](https://user-images.githubusercontent.com/45708377/110099535-75dcfe00-7db2-11eb-9a35-f96647e1d2b8.png)
and some interesting videos with cutting it:

https://user-images.githubusercontent.com/45708377/110099997-fb60ae00-7db2-11eb-908f-d32b8e15eb22.mp4

https://user-images.githubusercontent.com/45708377/110100170-26e39880-7db3-11eb-997c-1dfd92ab130e.mp4
The same with other trees.

**Comment by SlayksWood** [comment]
after fix  need to check tree loading, foliage appears earlier now:
![image](https://user-images.githubusercontent.com/45708377/112110896-91bf0d00-8bc4-11eb-83a4-aedd3fe1a35f.png)

**Comment by namquang93** [comment]
I've reverted tree leaves to normal MeshRenderers because the performance improvement was not very bug and IndirectRenderer needs lots of modifications to draw them correctly. This should be fixed for now. We'll use IndirectRenderer for tree leaves later when it's fully updated.
