### ISSUE TITLE
[0.9.3 Staging-1930]Repercussions/consequences of strange animal carcass behavior

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20581]
Tested on 0.9.3 Staging-1930

Issue: In this build, the animal carcass behaves very oddly.  After killing an animal, its body or the carcass keeps moving around like it's still searching for a path to follow. It moves very oddly and it shouldn't behave like this. Because of this issue, there are a couple of consequences that can happen to the players:

1. Animals' carcasses are behaving like they are in the water or being trampled over.
2. If a player gets close to a dead animal, there's a possibility that he/she will be thrown way up in the sky which is known as the space flight bug.
3. Some animals like the fox and otter doesn't exhibit any death animation after being killed. They simply stop moving.
4. In some instances, I am unable to pick up the carcasses and the tooltip that states "Pick Up" doesn't appear.
5. In some instances, the green ball cursor of the player when pointed to the animal carcass blinks consecutively.

Repro:
1. Kill an animal.
2. Get close to the carcass and observe.
3. Try to walk over it.

Video of space flight bug and a fox without death or dying animation.
https://images.zenhubusercontent.com/42199084/9f9ebdb7-b38c-4314-8600-c335cfde7d56/2021_02_15_18_20_trim__4_.mp4

Screenshot of an unpickable carcass
![sss.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/fbdf6dc5-9afd-4eba-8447-d5f739512008)

**Comment by keegan-o** [comment]
I've broken this issue down into different parts to make it more manageable:
https://app.zenhub.com/workspaces/saguaro-squad-5f814a78372287000f08fb57/issues/strangeloopgames/eco/8128
https://app.zenhub.com/workspaces/saguaro-squad-5f814a78372287000f08fb57/issues/strangeloopgames/eco/8129
https://app.zenhub.com/workspaces/saguaro-squad-5f814a78372287000f08fb57/issues/strangeloopgames/eco/8130
