### ISSUE TITLE
New builds kill mod updates

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20583]
"every time the eco server updates, it overwrites all the plant AutoGen maturity days I set, any way I could prevent it from doing that?"

This is a core problem with our mod design; mod files can change, overwritting existing mods.

We need to come up with a design that addresses this.  Using 'partial' classes on a case by case basis can only get us so far.  Some initial ideas:
- Lines tagged with a specific ```//mod``` marker are preserved during update
- others?

**Comment by mirasrael** [comment]
We can't control how files updated, because it is Steam update process. So only way it can be implemented is making modifications in other files. Best way in C# to achieve this - partials.

**Comment by redwyre** [comment]
@mirasrael is this case handled now?

**Comment by mirasrael** [comment]
Yes. In 9.4 all modifications should be done in non-Steam files and shouldn't be overwritten during Steam update process.

**Comment by IcedForge** [comment]
This is handled here #9655 and is working properly now.
