### ISSUE TITLE
Prevent empty contact support messages

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#20582]
Right now someone's edit request (in browser) and sends empty support messages. @D3nnis3n:
![image](https://user-images.githubusercontent.com/5720101/108002554-47100b00-6ff0-11eb-97dc-eb8f8035d621.png)
Add additional server check, if fields aren't empty.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/108033944-d1cf2500-7045-11eb-8d74-cd69a78168bf.png)
