### ISSUE TITLE
Improve crafting use of storage. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20585]
- [ ] And ability to designate input and output stockpiles for crafting stations and storefronts. Aka: designate a stockpile that the crafting station pulls its materials from, and a separate option for where you want the product to go afterwards.  This can be done via 'input' and 'output' check boxes in the storage tab. 
- [ ] When a crafting bench produces an item that can fit into a storage chest, prioritize placing it in one, rather than taking up inventory slots in a stockpile.  Otherwise, use the order defined in the list of storages.
Make a mockup first. 

Add: Task https://docs.google.com/document/d/1rDuakzTBI8G1Q4Lv0YIdNutB4YtzbleG4ObxZhvie0w/edit?usp=sharing

**Comment by TwixterZ** [comment]
Feature tested and observed as of 0.9.5 Develop-340

In the event where multiple storages is selected for output, storages on the top of the list will be selected if no similar output product is present in any of the storages.

IF there are similar product exist in one of the storages, crafting output will go to ones with the most amount of item, despite how storages was sorted in the list.

GIFs depicting above can be find :
https://app.clickup.com/t/10591183/ECO-12361
