### ISSUE TITLE
USER ISSUE: Authentication Server down.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#20592]
I do have the crash log.  Should I post it here?  I noticed I could not connect after downloading the newest Steam update.
[Eco Error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5986084/Eco.Error.txt)

**User Id: (slg976)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Click Continue,  Wait about 30 seconds.  Then error pops up.

**Expected behavior:**
Should connect to server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>No such host is known. No such host is known.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, unknown.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sirPattrick** [comment]
It was working this morning.  Not sure what was going on last night.  Like 10 people on our server had that error.  (The server is hosted in Texas, maybe the storm messed with something)

**Comment by D3nnis3n** [comment]
We didn't see any outage yesterday, so I can only imagine there has been a local connectivity issue to the auth servers.
