### ISSUE TITLE
Mint Should Only Show User's Account

### ISSUE THREAD

**Issue by Etep15** [StrangeLoopGames/EcoIssues#20591]
We have a Mint setup to be accessibly by Everyone.

The idea is people can go to the Mint, bring the resource, and mint more currency. It should default to their own account. But it defaults to my account (which they should not have access to it according to the Bank). They have to change it to their account under Target Account or the minted money goes to me. 

Please Note : I have a law setup so everyone can only mint X amount of currency per day. This manages inflation and let's people mint their own currency each day to slowly bring the currency into circulation and get's the citizens involved with that. But this issue is causing people to mint currency and not getting it because it goes into my account.

Any solution to resolve this?

**Comment by SlayksWood** [comment]
@Etep15 Thank you for the report. Player should have access to his bank accounts and bank account which the owner of Mint set. This is intented behavior. But the bug for now that bank account always changes to the owner bank acccount. 
This is dup. So merged to #17403
