### ISSUE TITLE
''Item crafted'' pop-ups crash the game

### ISSUE THREAD

**Issue by Lazeeee** [StrangeLoopGames/EcoIssues#20602]
My game updated this morning (16/02/21) and ever since I get pop-ups in the top right corner of the game for each item I have crafted since the three days I have been playing. There's over 150+ pop-up notifications and it lag my game to the point that I get 2-3 frames per second.
When I try to click on the pop-ups to make them disappear, the game crash. Verifying the files on steam didn't work and there is no option in the settings to disable those pop-ups.

**Comment by Lazeeee** [comment]
I play the Vanilla version on a private server. No mods. No one else is having that issue in the server.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for filing a report about this.
We apologize for any inconvenience that this might have caused you.
For us to be able to investigate this matter, can you upload and share with us the game log files and if possible, a recorded video of the issue.

When uploading log files, it would be great if you can start a new game, reproduce the issue, and upload the most recent log files generated by the game.

To upload game log files, please follow the instruction found here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information: log and if possible saved files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
