### ISSUE TITLE
USER ISSUE: can not create world

### ISSUE THREAD

**Issue by Retarded-Australian** [StrangeLoopGames/EcoIssues#20611]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**
fresh install game (this happened the firsttime i installed it)
create new world (i called mine "world1")
keep all the settings prompted default

**Expected behavior:**
say "connection failed"

**Actual behavior:**
The following error message popped up:
Failed to establish connection - no response from remote host host`` host```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by SlayksWood** [comment]
@Retarded-Australian Thank you for the report. Update to the latest version and reopen the issue if it happens again. Closed for now.
