### ISSUE TITLE
Tooltip goes off screen

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2061]
![image](https://user-images.githubusercontent.com/3536496/30137697-645766d4-9319-11e7-8c10-652cc80a4e00.png)
This is on civics/tailoring skill

**Comment by MarjieAVolk** [comment]
Hm, I have to turn up the interface scale pretty high before the Tailoring tooltip gets too tall for the screen

**Comment by MarjieAVolk** [comment]
But maybe there needs to be better handling for tooltips that are too tall, in general

**Comment by Conchipedia** [comment]
![snap623](https://user-images.githubusercontent.com/29383891/33290920-2345411e-d3bc-11e7-8207-9388c3d6393a.png)
![snap624](https://user-images.githubusercontent.com/29383891/33290931-2c78f69a-d3bc-11e7-9b06-0889558cb59a.png)
Adding this here as it seems related.
On Research Efficiency there are 61 more benefits, but no matter where i place that window as soon as i move mouse over the 61 to see what they all are the window opens in same place every time, and i cannot see any of the higher ones.

**Comment by MarjieAVolk** [comment]
Fixed on staging
