### ISSUE TITLE
Game crashes and system errors

### ISSUE THREAD

**Issue by rmndmtrvch** [StrangeLoopGames/EcoIssues#20615]
At the stage of "loading Eco 90%" when entering the world or directly at the stage of "entering the world 56%" the game crashes. Tried to enter different worlds, there is the same problem. This crashes not only Eco, but also Steam client (sometimes it just freezes), Internet browser, AIMP, for example, if they are opened in the background.  Updating video drivers allowed me to enter the world, but only once. After that I was able to enter the world, but only for a few seconds. I can hear the background sounds, but there is no image on the screen, then the game crashes. The next day after another attempt to enter the world the game crashed again with all backgrounds and the resolution on my screen changed to 800x600. Other games runs fine. 

Logs of some attempts (in Russian).
[log_210215043725.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994567/log_210215043725.log)
[log_210216045810.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994568/log_210216045810.log)
[log_210216124354.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994569/log_210216124354.log)
[log_210217113154.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994570/log_210217113154.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994571/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5994572/Player-prev.log)

**Comment by IcedForge** [comment]
@rmndmtrvch Thank you for reporting. Could you include a Dxdiag file? Windows key + R, type in dxdiax hit enter, save information and upload it here.

**Comment by rmndmtrvch** [comment]
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5994796/DxDiag.txt)

**Comment by IcedForge** [comment]
Looks like a general not enough RAM memory, could you screencap your ram memory task manager window?

**Comment by rmndmtrvch** [comment]
![ram](https://user-images.githubusercontent.com/78219080/108199781-90ff0b00-712e-11eb-9f38-999f576a682d.png)

**Comment by rmndmtrvch** [comment]
I should add that a couple of days ago everything was fine, and I played normally. No changes were made to the system.

**Comment by rmndmtrvch** [comment]
I decided to observe the RAM graph when the game starts. There is enough memory to start the game. A couple of seconds after entering the world the game crashes and a small window appears with some kind of error, then quickly disappears and the game closes.
![ram2](https://user-images.githubusercontent.com/78219080/108229713-1d222a00-7151-11eb-8309-325cae43998e.png)

**Comment by rmndmtrvch** [comment]
The problem doesn't appear after rolling back to an old restore point in the system. However, I have not found the cause of the error.
