### ISSUE TITLE
[0.9.3 staging-1931] Gain experience icons overlap again.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20618]
Something broken with gain expirience icons, this changes doesn't work in staging https://github.com/StrangeLoopGames/Eco/pull/7539 
![image](https://user-images.githubusercontent.com/45708377/108192319-2bf2e780-7125-11eb-8375-0991ec380d1e.png)
![image](https://user-images.githubusercontent.com/45708377/108192372-3a410380-7125-11eb-8eb1-748e9ec86c0d.png)

**Comment by WeaselDog** [comment]
This was removed from develop due to a conflict. Unfortunately the PR will have to be recreated.

**Comment by IcedForge** [comment]
This is now the current behavior, i assume this to be correct then otherwise reopen this @SlayksWood @WeaselDog 
and we can revisit it for 9.4 or later.
![Screenshot_16.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2178e7c4-e33a-4431-90ff-617e933b6f89)
