### ISSUE TITLE
USER ISSUE: Player becoming unable to interact with world

### ISSUE THREAD

**Issue by dsa321t** [StrangeLoopGames/EcoIssues#20627]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Unsure what caused it, only know that it happened

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Addition note:
Link to video showing what is happening- https://youtu.be/SyrnHGHfI3o
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5999027/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5999029/Player-prev.log)

**Comment by dsa321t** [comment]
My friend was still able to interact with the cart in the video. Also i wasnt able to collect any dead animals, however my friend was.
The issue was resolved after I closed the game (not going into the main menu), and restarting the game.

**Comment by dsa321t** [comment]
Ah forgot to add; This only happening after I stopped interacting with a hand cart. However this wasn't the first time I've interacted with one

**Comment by SlayksWood** [comment]
@dsa321t Thank you for the report. merged to #20414
