### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Zaphityr** [StrangeLoopGames/EcoIssues#20623]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Trying to connect to a server

**Expected behavior:**
Connecting to the server I'm playing on.....

**Actual behavior:**
It begins connecting, shows the message for it, then brings back the main menu and nothing happens. And the cursor no longer works. If I want to play the game now I have to clear the local files in AppData and potentially reinstall the game. Which is too much hazzle to do every time you have to restart the application. Other servers work fine at this point but I don't play on the

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No manually installed mods. Unless my server automatically installs them for me.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@Zaphityr Thank you for reporting. Please include log files detailed in the template.
Also include a Dxdiag file by using windows key + R, and run "dxdiag" save information and upload the .txt file here.

**Comment by Zaphityr** [comment]
Was resolved with a server update.

**Comment by IcedForge** [comment]
Thank you for your reply, will close this as it stated as resolved by update.
