### ISSUE TITLE
Buying Eco Beta shouldnt be shown if you already own the beta, but for a lower price

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20622]
![image](https://user-images.githubusercontent.com/25908592/108219855-6749e200-7136-11eb-90b6-c04698bf937a.png)

This user already owns Beta, acquired through kickstarter for a special price of 20$ - he shouldnt see an upgrade option to Beta for $30.

**Comment by denysaw** [comment]
Could be tested on Staging.

**Comment by D3nnis3n** [comment]
Seems fixed.
