### ISSUE TITLE
USER ISSUE: Lumber Doors Don't open

### ISSUE THREAD

**Issue by nlducker47** [StrangeLoopGames/EcoIssues#20633]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I've placed and replaced Lumber Doors multiple times and they still won't open or close. I have to completely remove them to get out of a room.

**Expected behavior:**
For the doors to function like an actual door.

**Actual behavior:**
Won't open/close.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Mods are installed in the Sawmill. I'm not wasting more Lumber to end up with more doors that don't work.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@nlducker47 Thank you for the report. Mod - modification for server.
We need more details to investigate your issue:
1. Please provide your PC specification (include Operating System and its version).
2. Does it happens after restart game? 
3. Can you provide log files when it happens next time? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
4. Any unusual information to help us get your problem. You can make videos.

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
