### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by murasakisuki** [StrangeLoopGames/EcoIssues#20632]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Try and skip tutorials after playing for a short amount of time the property authorization and food tutorials will get stuck and wont respond to interaction

**Expected behavior:**
Tutorials should be passable when completing the specified actions

**Actual behavior:**
Tutorials simply sit on screen and can not be completed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods have been installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this. However, we are unable to reproduce this issue.
Could you provide additional information such as a recorded video of the issue as it happens and the latest game log files after the issue occurred? This will help us investigate the issue further.

To upload game log files, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
