### ISSUE TITLE
Make Jenkins and CI work on client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20630]
I want to extend our tests to run on the client side as well.  We will do this in phases:
- [x] As part of CI tests, Jenkins will build the client, run it, and connect to the server.
- [x] Jenkins will log any exceptions and file them to the PR as warnings
- [ ] We will make issues to fix these
- [ ] Begin running a suite of tests from the client, make those exceptions warnings too
- [ ] Once we get to 0 exceptions being generated by jenkins, we will make warnings into errors
- [x] We will make more client side tests

**Comment by redwyre** [comment]
* First run server CI tests locally
* Run CI tests locally with client active
* Report any test failures - create issues to get fixed
* Create branch from develop (abhi/ci_tests)
* Create a PR for your branch (this will trigger a jenkins build, and again for every commit)
* Get client running outside of jenkins service context

**Comment by Abhiw205** [comment]
A new Jenkins job is create "GUI-Test", this task will launch client on GUI mode, on administrator screen. 
Need to discuss about integration in main pipeline.

**Comment by Abhiw205** [comment]
@johnkslg  @redwyre , 

client test pipeline is updated, with following changes 
1. Launch the client application. 
2. Print eco.exe PID,for reference, (this case also include auto close application after sometime). 
3. Print runtime log on console. 

Please check and let me know. Any further modifications is required.

**Comment by Abhiw205** [comment]
SAMPLE OUTPUT:- 

Started by user Abhijeet Srivastava
Running as Abhijeet Srivastava
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Start client)
[Pipeline] node
Running on friend rice in C:\Jenkins\workspace\client-test
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] bat

C:\Jenkins\workspace\client-test>powershell -ExecutionPolicy Bypass .\client.ps1 

TaskPath                                       TaskName                          State     
--------                                       --------                          -----     
\                                              Automation                        Ready     


[Pipeline] }
[Pipeline] // script
[Pipeline] echo
windowsNode: friend rice, NODE_NAME: friend rice
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Get Some Rest)
[Pipeline] node
Running on friend rice in C:\Jenkins\workspace\client-test
[Pipeline] {
[Pipeline] echo
Start
[Pipeline] sleep
Sleeping for 5 sec
expected to call WorkflowScript.sleeping but wound up catching sleep; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (ECO PID)
[Pipeline] node
Running on friend rice in C:\Jenkins\workspace\client-test
[Pipeline] {
[Pipeline] bat

C:\Jenkins\workspace\client-test>powershell -ExecutionPolicy Bypass Get-Process cmd -IncludeUserName 

Handles      WS(K)   CPU(s)     Id UserName               ProcessName                                                  
-------      -----   ------     -- --------               -----------                                                  
     70       4216     0.06   6164 STRANGELOOPGAME\Adm... cmd                                                          
     80       4248     0.00  11844 STRANGELOOPGAME\Adm... cmd                                                          
     80       4420     0.02  13084 STRANGELOOPGAME\Adm... cmd                                                          
     80       4208     0.03  21472 STRANGELOOPGAME\Adm... cmd                                                          
     80       4188     0.00  23812 STRANGELOOPGAME\Adm... cmd                                                          


[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Print runtime output)
[Pipeline] node
Running on friend rice in C:\Jenkins\workspace\client-test
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo
Current workspace is C:\Jenkins\workspace\client-test
[Pipeline] readFile
[Pipeline] echo
log = [Mono path[0] = 'C:/Jenkins/workspace/Eco Test Pipeline/Build/Client/win-x64/Eco_Data/Managed', Mono config path = 'C:/Jenkins/workspace/Eco Test Pipeline/Build/Client/win-x64/MonoBleedingEdge/etc', Initialize engine version: 2020.1.17f1 (9957aee8edc2), [Subsystems] Discovering subsystems at path C:/Jenkins/workspace/Eco Test Pipeline/Build/Client/win-x64/Eco_Data/UnitySubsystems, GfxDevice: creating device client; threaded=1, Direct3D:,     Version:  Direct3D 11.0 [level 11.1],     Renderer: Intel(R) HD Graphics 630 (ID=0x5912),     Vendor:   ,     VRAM:     32659 MB,     Driver:   24.20.100.6290, Begin MonoManager ReloadAssembly, - Completed reload, in  0.086 seconds, D3D11 device created for Microsoft Media Foundation video decoding., <RI> Initializing input., , XInput1_3.dll not found. Trying XInput9_1_0.dll instead..., <RI> Input initialized., , <RI> Initialized touch support., , UnloadTime: 1.063500 ms, TypeManager.Initialize took: 598ms, DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. , (Filename:  Line: 627), , WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349. , (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35), , WwiseUnity: Setting Plugin DLL path to: C:/Jenkins/workspace/Eco Test Pipeline/Build/Client/win-x64/Eco_Data\Plugins\x86_64 , (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35), , WwiseUnity: Sound engine initialized successfully. , (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35), , The referenced script on this Behaviour (Game Object 'Camera') is missing! , (Filename:  Line: 334), , The referenced script on this Behaviour (Game Object 'Table') is missing! , (Filename:  Line: 334), , DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. , (Filename:  Line: 627), , Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI , (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35), , MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead , (Filename:  Line: 320), , MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead , (Filename:  Line: 320), ]
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by Abhiw205** [comment]
Changes in client-test
1. Client application start on build server. (both in GUI & Batch mode)
2. Login to client application. 
3. CI wait for 2 min to get run time log. 
4. Stop client application 
5. Storing run time log as build artifact. 

Please let me know if any mode modifications are required.

**Comment by Abhiw205** [comment]
fixed

**Comment by Abhiw205** [comment]
Updated "Jenkins will log any exceptions and file them to the PR as warnings"

**Comment by johnkslg** [comment]
Closing in favor of https://github.com/StrangeLoopGames/EcoIssues/issues/21354
