### ISSUE TITLE
USER ISSUE: Kitchwen Doesn't give bonus

### ISSUE THREAD

**Issue by nlducker47** [StrangeLoopGames/EcoIssues#20634]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Item KITCHEN built on the Sawmill gives no housing bonus. According to the info when hovered over, it's supposed to be a bonus of 3. The room meets all requirements for the bonus.	 It seems as if there is a problem with furnishings built on the Sawmill.

**Expected behavior:**
Given a housing bonus.

**Actual behavior:**
No housing bonus.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Advanced Upgrade 1

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@nlducker47 Thank you for the report. I can't reproduce it:
![image](https://user-images.githubusercontent.com/45708377/108315431-78453280-71cc-11eb-8ec0-a654010de045.png)
Can you provide more details? Any screenshot with your problem, or just provide save files with this furniture.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
Also provide log file when it happens next time. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
