### ISSUE TITLE
Icons for server browser

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20631]
I've changed our server browser so it shows icons based on properties of the servers youre looking at, which players can use to choose a good one. I need icons to fill in the slots that are shown on each server, like so:
![image](https://user-images.githubusercontent.com/3536496/108289422-38863880-7143-11eb-9ece-ddbb0eae49ae.png)

The icons should read well small, theyre 32x32 typically.  The list is:

- [ ] Some Players Online        
- [ ] Many Players Online
- [ ] Lots of Players Online
- [ ] Unmatched Times             - (negative) Playtimes you have chosen don't match well with the server
- [ ] Matched Times               - Playtimes you have chosen match well with the server
- [ ] Admin Online                - An admin is online.
- [ ] Server Description          - Server description is set.
- [ ] Immigrants Needed           - Immigrants needed due to abandoning players!
- [ ] Growing Population          - Initial set of citizens still growing to capacity.
- [ ] Full                        - (negative) Is already full of active citizens.
- [ ] New Server                  - Day X of a beginner server (score reduced by 20 per day).
- [ ] New Hard Server             - Day X of an experienced server (score reduced by 5 per day).
- [ ] Post-Meteor Society         - A world building a utopia after the meteor has been destroyed.
- [ ] Friends Online              - Server has friends of yours playing.
- [ ] Great Ping                  - Server has a great ping X
- [ ] Bad Ping                    - (negative) Server has a slow ping X
- [ ] Disconnected                - (negative) Server did not respond to ping.
- [ ] Newbie Friendly - Has special structures to help new players.
- [ ] Discord - Has a discord server assigned.
- [ ] Unmatched Hours Per Day - The server's setting for an exhaustion limit does not match the 'hours per day' you have set.
- [ ] Matched Hours Per Day - The server's setting for an exhaustion limit matches the 'hours per day' you have set.

The servers should be named exactly as listed so the code will find them.
Ones marked negative make them red or something

**Comment by RobertMangano** [comment]
Icons have been added to icon sheet UI_Icons_small_01, named exactly as they appear in the list above.

![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/b1e2b21e-7383-46b0-acb3-272f6ab935e8)

**Comment by johnkslg** [comment]
@serpopov can you finish this one off when you get time

**Comment by IcedForge** [comment]
Looks good, like the clarity over the match score now and displays.
