### ISSUE TITLE
Tilled Dirt after Harvest

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20641]
Normally, after a harvest farmer would plow his fields again. Currently, the fields remain plowed. No need for tractor plow, hand plow or hoe.

maybe give Fields a new Art after Harvest?
![grafik](https://user-images.githubusercontent.com/37456949/108343144-e34a3580-71db-11eb-9cf6-69721beb49bb.png)
Dry Earth with some Plantsparts?

**Comment by WeaselDog** [comment]
Duplicate issue
