### ISSUE TITLE
9.2.4 Upgrade's do not get pluralised

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20644]
Upgrades do not get pluralised like other items.

It should probably say 0 out of 250 Modern upgrade 2's added
![image](https://user-images.githubusercontent.com/61889138/108382384-b0666880-7200-11eb-96a8-78a61659332a.png)

**Comment by johnkslg** [comment]
These need to use the Localizer.Plural[Loc] functions

**Comment by WeaselDog** [comment]
For this fix, I did update the naming convention for specialty upgrades to be more clear.

With the plural name on the numbered upgrades, it is intentionally without an "s". I tried with " 's " and it looks a bit off.

We can consider the upgrade with numbers an uncountable noun, similar to rice.
