### ISSUE TITLE
[0.9.3 staging-1934] need add "Fireplace" on Сrowdin

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20649]
![2020-12-21](https://user-images.githubusercontent.com/26339332/108421676-918ac500-7246-11eb-951f-08f8bae7db55.png)

Сrowdin have not "Fireplace"

**Comment by gabrielgindridev** [comment]
Seems that this was removed. Popup design was changed. Check code and there is no trace of this.
currently in develop:
![image](https://user-images.githubusercontent.com/65634950/110528400-e0fe3b80-80f6-11eb-8afc-957dc94db668.png)

**Comment by gabrielgindridev** [comment]
Fixed the code issue. But the "Fireplace" + a bunch of other words will only be added in `staging`. We've been running localization process only there.

**Comment by StallEF** [comment]
@gabrielgindridev  'Fountain‏' not upload on Crowdin too

the lack of code in DEV version planned or was it is error?

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 develop 266
