### ISSUE TITLE
[0.9.3 staging-1934] missing space in DisplayName

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20648]
MountainGoat
MoonJellyfish
PacificSardine
SnappingTurtle
BighornSheep
BlueShark

**Comment by SlayksWood** [comment]
Fixed in species but still have 5/6 in minimap:
![image](https://user-images.githubusercontent.com/45708377/108589044-7f577680-736d-11eb-81a9-4e207070ce04.png)

**Comment by WeaselDog** [comment]
> This wont localize, can do GetLocDisplayName on the type and that should work

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/113671670-58f05f00-96bf-11eb-948b-ad26c363b765.png)
