### ISSUE TITLE
USER ISSUE: Tutorial box

### ISSUE THREAD

**Issue by Justin-Perry-2127** [StrangeLoopGames/EcoIssues#20650]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I have a wide screened monitor and I cant read the tutorial box because it wraps all the way through the bottom of the screen :(
Resolution 3440x1440

**Expected behavior:**
Went further into the center of the screen to make reading available

**Actual behavior:**
goes through the bottom of the screen making it unreadable

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Justin-Perry-2127 Thank you for the report. We are aware of this problem, merged to #20252
