### ISSUE TITLE
[Client] Logging level 6 Cleanup Crew talent still costs calories to clean up debris

### ISSUE THREAD

**Issue by coderatchet** [StrangeLoopGames/EcoIssues#20652]
__Version__: 0.2.9.4 beta release 156
__Expected Behavior__: with Cleanup Crew talent in logging skill tree, I won't spend calories to clear tree branch debris
__Actual Behavior__: Clearing debris costs the same as chopping wood (currently 10 calories at logging level 7).
__Steps to reproduce__: Achieve level 6 logging and select Cleanup Crew talent. attempt to chop a tree and clear debris then note calorie reduction amounts.

The talent states that cleaning up tree debris costs no extra calories, however i still use (currently level 7 logging) 10 calories per debris cleanup. Is this a bug with the talent or am i misunderstanding the talent ability?

**Comment by SlayksWood** [comment]
@coderatchet Thank you for the report.
Merged to #20184
