### ISSUE TITLE
[0.9.3 staging-1935] Water pump sounds

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20654]
- [x] 1. Electric water pump starts with awful loud sound.
- [x] 2. Working Crank sound is louder in Electric water pump too - this is next generation device it should work quieter than Mechanical water pump, at least crank sound.
- [x] 3. Don't have any sounds when open Mechanical water pump UI.

Video: https://drive.google.com/file/d/12K0U2p3hc5A27-69O4iDP_dmYiVUoNK4/view?usp=sharing

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1992.

1. Electric Water Pump has now a mellow/subtle sound when operating.
2. Mechanical Water Pumo now has audio when opened and while operating.
3. Electric Water Pump doesn't have an awful start-up sound anymore.


Closing.
