### ISSUE TITLE
Monitor cw backups metrics

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20651]
Need a general log for which worlds are saving, how often, how big of files.

**Comment by j3fffff** [comment]
so goal is to get a price estimate of cw backups.

@mirasrael could you describe how the backup system works, and best place in system to put our monitor. and how it would get backup file size?

Then well pass that info to @thetestgame monitor system. And ideally we can correlate that data with AWS's data transfer costs. To get an idea of how much these backups are costing in data transfer.
plus s3 storage costs.
Jordan any ideas on that?

**Comment by mirasrael** [comment]
Can't you just get these metrics from AWS? Technically all S3 operations done with S3Storage which implements IStorage and may be wrapped with something for monitoring or S3Storage may be extended for metrics support.

**Comment by j3fffff** [comment]
@thetestgame add this to the high pri for monitor system.
we need ability to assess the cost of cw, and this is key to that.
