### ISSUE TITLE
Dark skinned avatars don't look as nice :(

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2065]
They have grey shadow looking things around the facial details.  I also noticed they have strange colored fingernails.

![image](https://user-images.githubusercontent.com/23460210/30185605-05b395bc-93d7-11e7-9646-012ff1fbf6f3.png)

**Comment by MarjieAVolk** [comment]
Update on the fingernails, it seems that color is random, and also it is present on the light skinned avatars as well, just much harder to see

**Comment by keegan-o** [comment]
Fixed it, had to nuke some of the shadow details in the face, but light skinned avatars still look good so it seems fine.
