### ISSUE TITLE
[0.9.3.0 beta staging-1935]Civics: cannot select move in / move in fee initially as first option 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20656]
When you setup an law using the Pay Rent or Move in Fee
you cannot select either sub options in IF section when you first add an IF addition as seen below
![Screenshot_66.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c59e0213-ab46-4e7d-aa49-90c9c3b4a55d)

It will just not let you pick it at all, you can select it if you do add something else first as detailed below so if i add currency in circulation i can switch this into pay rent/move in fee afterward but i can never select it as the first option.

![Screenshot_67.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/777a0715-23cb-41f9-9598-1be3a966323f)

Reproduction steps
Start drafting a law and add "Pay Rent or Move in Fee" Trigger
Now add a IF section item and try to select either "Pay Rent" or "Move in Fee" and you will be unable to do so.

**Comment by SlayksWood** [comment]
Still have a small bug. So the right behavior, for example take Constuct or Deconstruct.
- select trigger "Constuct or Deconstruct":
![image](https://user-images.githubusercontent.com/45708377/110440741-0d4f9300-80ca-11eb-8d3a-7c2461c56eba.png)
- add condition. When you add it you have None here and exclamation mark:
![image](https://user-images.githubusercontent.com/45708377/110440877-32440600-80ca-11eb-9178-f2c7c0f49504.png)

But it doesn't wotk the same with "Pay Rent or Move in Fee":
- select trigger "Pay Rent or Move in Fee":
![image](https://user-images.githubusercontent.com/45708377/110441042-628ba480-80ca-11eb-97bb-4d7d16e17e20.png)
- add condition:
![image](https://user-images.githubusercontent.com/45708377/110441128-77683800-80ca-11eb-8acd-748b6a4aa9a9.png)
- you can see that I don't have error, the more I have 'Move In' in law text description.
You need to do it in a template way.

**Comment by Daniel-Magulado** [comment]
The fix [PR-8868c8e](https://github.com/StrangeLoopGames/Eco/pull/7990) was already implemented to 9.3 Staging1949 build.
I can still reproduce the issue commented by SlayksWood on 1952 build.

Reopening.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1966.

All issues have been fixed. Closing
