### ISSUE TITLE
[web] [Accounts] dowload staging version need update

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20669]
![2021-02-19](https://user-images.githubusercontent.com/26339332/108550992-5351dc00-7300-11eb-8865-12b5d77d1e44.png)

**Comment by denysaw** [comment]
Fixed on Prod. Updated to 0.9.4

**Comment by StallEF** [comment]
@redwyre can you rename v0.9.4.0-beta-staging-1932 to 9.3 for correct script work here? 

current version v0.9.3.0-beta-staging-1952 but can not be dowload from play.eco
