### ISSUE TITLE
Fix skill migration 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20668]
![image](https://user-images.githubusercontent.com/3536496/108549131-a0529580-72a1-11eb-8b13-f05e5b4197db.png)

**Comment by WeaselDog** [comment]
Can ask Alex if needing help to get correct schema number, though it should be available in 0.9.4 migration namespace

**Comment by WeaselDog** [comment]
The fix described in this issue has been implemented, but skill migration is still not working. Will need another pass.

**Comment by gabrielgindridev** [comment]
@WeaselDog can I have the save for this issue?
