### ISSUE TITLE
Missing items in law trigger "Currency Trade"

### ISSUE THREAD

**Issue by Cicrocoft** [StrangeLoopGames/EcoIssues#20665]
Hi,

Im unable to select eg plastic under the Currency Trade Trigger -> With Items Traded. Another Eco user posted that 927 items you can sell in a store, buy only 827 items you can select in this tab.

**Comment by SlayksWood** [comment]
At least we don;t have Research Papers, Upgrades (like Advanced Upgrade 1)

**Comment by TwixterZ** [comment]
Fix observed and confirmed as of 9.4 Staging-2047
