### ISSUE TITLE
Online/offline and online section in wages broken

### ISSUE THREAD

**Issue by Cicrocoft** [StrangeLoopGames/EcoIssues#20666]
Hi, this is a to issues, but maybe connected, so ill merge it into one.

I cant select between online/offline and online hours in the wages section at the registar. The same issue is for the leader titles, I need to vote through the leader title, and after that, I can change it to online hours.

When connecting a title to a law, I get the error: "Must set both currency and amount when setting online hours", all though there are no wages selected for the title (ref attached screenshot)
![error](https://user-images.githubusercontent.com/20983572/108542423-0102c200-72e4-11eb-96b7-3a6c3b0ac27f.png)

**Comment by SlayksWood** [comment]
@Cicrocoft Thank you for the report.
We still have a problem with it. Step to reproduce:
- place court and registrar.
- start to create law with title requirements. Seems all's right:
![image](https://user-images.githubusercontent.com/45708377/108590556-386d7f00-7375-11eb-916f-3b243b5706de.png)
- don't add this law to election. Just close it.
- open registrar -> advanced settings for 'Test Title':
![image](https://user-images.githubusercontent.com/45708377/108590583-5d61f200-7375-11eb-94ae-6554e1fb9a3d.png)
- select any currency insted of None:
![image](https://user-images.githubusercontent.com/45708377/108590598-710d5880-7375-11eb-9717-b37e2b2e6522.png)
- close this UI.
- open the law:
![image](https://user-images.githubusercontent.com/45708377/108590618-8b473680-7375-11eb-800d-3297a3456ad9.png)
- I can't create a law now.
- So without submit changes for title I have this error.
