### ISSUE TITLE
Cancle project /crafting queue can crash the server 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2066]
http://plays.tv/video/59a9617d8f4ddb294b/crashing-server-after-cancel-project

http://ecoforum.strangeloopgames.com/topic/2814/list-of-improvements

**Comment by MarjieAVolk** [comment]
Is this on 5.6?  It might already be fixed in staging

**Comment by johnkslg** [comment]
This should be fixed now.
