### ISSUE TITLE
9.3.0 1930 > 1935 users.eco migration failure removing users.eco in its entirety

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20663]
Starting up the server and got the below

This was using a version of users.eco that was generated by 1930 GUI 

![image](https://user-images.githubusercontent.com/61889138/108509491-3512be80-72b5-11eb-977c-cd8ac0efac39.png)

I do not have a copy of the original users.eco to upload as example as it has deleted the file, it should probably make a copy IE Users.eco-19-02-2021-MIGRATION

using a users.eco from 9.2.4 was fine migrating and with all data intact.

**Comment by beastyn** [comment]
All Users.eco will be imported to the new version. It will make a copy of your current file, add a new structure for the users lists and create a new file with it. So it's not like something was wrong here, It's just outdated by default. But I will make a copy of the old file for testing, checking and sanity. Thank you for the report!

**Comment by MishkaFur** [comment]
The biggest issue was that because it flagged it as invalid it wiped it without making a copy, so banlist, whitelist etc would have been lost.
 
 A 9.2.4 to 9.3 1935 was fine and worked correctly

**Comment by beastyn** [comment]
I see, something went wrong with versioning. Will check it, thanks.

**Comment by beastyn** [comment]
@MishkaFur can you show your current User.eco.template?

**Comment by MishkaFur** [comment]
[Users.eco.template.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6014683/Users.eco.template.zip)

see above, it looks like it was edited at same time 1935 came out so should be the valid one, the users.eco i made that got wiped was one that was made in the 9.3 1930 build.

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/109114431-ae476100-774e-11eb-9896-a3d4b96662d6.png)
![image](https://user-images.githubusercontent.com/45708377/109114440-b43d4200-774e-11eb-805b-681afd8976fb.png)
