### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by jardah201** [StrangeLoopGames/EcoIssues#20679]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
Could you provide us more information about this issue? 
Please describe to us when and how did you encounter this issue.
Once you encounter this issue again, please upload the game log files here. To do so, please follow the instructions here  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

It would also help us investigate the issue further if you could provide us with steps to reproduce it.

Thank you.

**Comment by D3nnis3n** [comment]
This is an issue for support, hence please contact our support over at support@strangeloopgames.com with your SLG ID.
