### ISSUE TITLE
Mac shader issues 2 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2067]
2017 MacBook Pro which has a 2.3 GHz Intel Core i5. 
<img width="1440" alt="screen shot 2017-09-01 at 4 19 41 pm" src="https://user-images.githubusercontent.com/1668416/30186541-42a5e49e-9426-11e7-9d0a-646915b2e7c6.png">

**Comment by noblackthunder** [comment]
![screen shot 2017-09-04 at 10 40 25](https://user-images.githubusercontent.com/1668416/30186560-5eb3b3aa-9426-11e7-8f7b-8de56929f639.png)
![screen shot 2017-09-04 at 10 39 37](https://user-images.githubusercontent.com/1668416/30186563-613c41fa-9426-11e7-8935-b01901acfb77.png)

after upgrading from el capiten to MacOS Sierra ? 


MacOS Sierra  10.12.6
iMac late 2012
Processor: 3,2 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: NVIDIA GeForce GTX 675MX 1024 MB

**Comment by SeanAtr0n** [comment]
Really need the log files for this... could you ask them to send us
`/Users/<username>/Library/Logs/Unity/Player.log`

if they can't find it then open a console and run
`cp ~/Library/Logs/Unity/Player.log ~/.`
then send us
`/Users/<username>/Player.log`

**Comment by noblackthunder** [comment]
[Player.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1293753/Player.txt)

**Comment by SeanAtr0n** [comment]
Can't currently reproduce this and the log files aren't leading me anywhere, going to push this back
