### ISSUE TITLE
USER ISSUE: Time fastford

### ISSUE THREAD

**Issue by Simxrnator** [StrangeLoopGames/EcoIssues#20672]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Sleep in a bed, Wake up from the bed. 

**Expected behavior:**
It should only speed up time when you sleep.

**Actual behavior:**
It continues to speed up time when you get out of bed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope and Nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Simxrnator Thank you for the report. I assume you press ESC when trying to wake up? Yeah, we have such a problem in 9.2.4 and it will be solved in 9.3 with https://github.com/StrangeLoopGames/Eco/pull/7769
To stop fastforwarding you can sleep again and press Wake up button:
![image](https://user-images.githubusercontent.com/45708377/108585047-1f55d580-7357-11eb-8954-db33e9fc30ab.png)
Did it help you?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
