### ISSUE TITLE
Graphics issue with Lumber walls and glass window form

### ISSUE THREAD

**Issue by AquatikJustice** [StrangeLoopGames/EcoIssues#20675]
When placing a glass window on a lumber wall, you cannot see any textures on the lumber apart from the front one. All other sides become see through.
![382310_20210219200019_1](https://user-images.githubusercontent.com/4640482/108579787-301e3100-72ee-11eb-9ce4-9f3bc815e3ac.png)

**Comment by SlayksWood** [comment]
@AquatikJustice Thank you for the report.
dup #19427
