### ISSUE TITLE
USER ISSUE: Sleeping Bug affecting in game time

### ISSUE THREAD

**Issue by thedash52** [StrangeLoopGames/EcoIssues#20677]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
In single player local host, sleep in bed in tent.

**Expected behavior:**
After waking up, day night cycle goes back to normal

**Actual behavior:**
Day night cycle is faster than when asleep with a cycle of about 5 secs and it seems to get slowly faster as time goes on. Everything seems to be running at double speed at least

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are install, this is a brand new world with random world generation and no colab settings on

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@thedash52 Thank you for the report. I assume you press ESC when trying to wake up? Yeah, we have such a problem in 9.2.4 and it will be solved in 9.3 with [StrangeLoopGames/Eco#7769](https://github.com/StrangeLoopGames/Eco/pull/7769)
 To stop fastforwarding you can sleep again and press Wake up button:
![image](https://user-images.githubusercontent.com/45708377/108585047-1f55d580-7357-11eb-8954-db33e9fc30ab.png)
Did it help you?

**Comment by thedash52** [comment]
Yep that seemed to work. Thanks for the help. It was annoying having to either not sleep or relog after sleeping

**Comment by SlayksWood** [comment]
you're welcome.
