### ISSUE TITLE
[0.9.3 staging-1935] Connecting to {0} lost localization 

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20680]
it was on 9.0.x work but on [0.9.3 staging-1935] it not work more 

![2021-02-20](https://user-images.githubusercontent.com/26339332/108594334-89d43900-738a-11eb-9053-2629268f03af.png)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
I can confirm that the term "Connecting To" is not following localization when language is changed from English.
Tested on 0.9.2.4 Release-162 and 0.9.3 Staging 1936.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/115513991-5596cf00-a28c-11eb-892c-2d900bd1ace4.png)
