### ISSUE TITLE
USER ISSUE: King's Bed not crafting

### ISSUE THREAD

**Issue by nlducker47** [StrangeLoopGames/EcoIssues#20686]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I've selected to craft 2 King's Beds in the crafting table twice and they didn't craft either time. All materials show as being available.

**Expected behavior:**
For item to craft.

**Actual behavior:**
Item not crafting.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
However, we are not certain about the item you are referring to as "King's Bed".
If possible, please include a screenshot of the item with its tooltip displayed.
Please also upload the latest game log files after the issue happened again.
You can upload the game logs by following the instructions here: Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @ndlucker47, we haven't received any reply from you for more than 2 weeks now.
We're closing the ticket for now. Please feel free to reopen it again if you even encounter the same issue.

Thank you.
