### ISSUE TITLE
USER ISSUE: Dampfmaschine (German) 

### ISSUE THREAD

**Issue by Chefkoch123** [StrangeLoopGames/EcoIssues#20682]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Wir haben mehr Strom gebraucht und deswegen eine Dampfmaschine gebaut. Das Problem ist nur, er geht auf Ressourcen sparen da keine Energie von anderen Maschinen gebraucht wird (Wasser und Abluft sind angeschlossen und funktionieren). Im endeffekt steht jetzt alles auf Störung da niemand die Dampfmaschine sieht und somit die Energie Fehlt. 				

Wir haben selber nach möglichen lösungen gesucht: 
- Es wurde alles geclaimt
- Wir haben alle gerätschaften im selben raum 
- Es werden alle anforderungen bis auf Strom erfüllt 
- Die Dampfmaschine hat genügend Brennstoff & Wasser, Abluft
- Alle Freigaben für Mitspieler sind gegeben
- Als letztes haben wir die Wasserpumpe verlegt damit Sie von wo anders wasser liefert (nun gab es 0W Strom, keine energie aber die Dampfmaschine ist immernoch auf Ressourcen sparen)
- Außerhalb vom gebäude Funktioniert es ebenfalls nicht
	

**Expected behavior:**
1000+W und alle Maschinen haben ausreichend Strom.

**Actual behavior:**
Störung keine bzw. 200W Strom verfügbar (Generator wird nicht als Quelle gesehen). 

Hochstwarscheinlich ein Bug da der Generator nicht als Stromquelle erkannt wird (egal wo)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hallo Chefkoch123,
kannst du uns bitte dein Savegame und die Koordinaten der problematischen Maschinen zur Verfügung stellen? Einfach auf Google Drive o.ä. hochladen. Die Speicherstände finden sich im Storage Ordner.

Dazu bitte auch die Logs des Servers.

**Comment by Chefkoch123** [comment]
Es hat sich erledigt, wir wussten nicht das es Stufe 2 Strom gibt. Der Wasserfilter hatte trotz gegebenen1400W keinen Strom jedoch ist plötzlich der Generator losgegangen und liefert nun die 1000W von sich aus lol... wir sind zwar verwirrt aber froh das es nun geht ^^

**Comment by Chefkoch123** [comment]
Also wir sind mega verwirrt, gibt es Stufe 2 Strom ?? Wir haben jetzt einen Filter hinzugefügt, der wie die Elektrische Wasserpumpe offensichtlich die Dampfmaschine als quelle sieht. Alle anderen Geräte (Drehmaschine, Spindelpresse) die Strom als Kraftstoff brauchen jedoch nicht..

**Comment by D3nnis3n** [comment]
Es gibt zwei Arten von Energie - mechanische und elektrische. Unterschiedliche Maschinen brauchen unterschiedliche Energie und die wird auch von anderen Dingen bereitgestellt.

Die Dampfmaschine erzeugt elektrische Energie, die Spindelpresse braucht aber mechanische, die wird nur durch Windräder und Wasseräder zur Verfügung gestellt.

Es handelt sich hier also tatsächlich nicht um einen Fehler.
