### ISSUE TITLE
USER ISSUE: Small Cart and logs

### ISSUE THREAD

**Issue by JLow11** [StrangeLoopGames/EcoIssues#20691]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
chopped down an old growth redwood

**Expected behavior:**
Cant use small wood carts inventory and also cant pick logs up or chop up trees once on the ground

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by jamesyoung79** [comment]
I have experienced this as well a few times. I when it effects me others can chop the felled trees or use the carts. It seems the dynamic object are all inaccessible, but 'static' things like plants and such and be interacted with. While having the issue other people can interact with them fine. I have found exiting the client and reloading eco corrects the problem.

**Comment by SlayksWood** [comment]
@jamesyoung79 @JLow11 Thank you for the report.
merged to #20414
