### ISSUE TITLE
USER ISSUE: Tutorial Thin, Tall, and off Screen

### ISSUE THREAD

**Issue by PortableTech** [StrangeLoopGames/EcoIssues#20696]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Start game, follow Tutorial, all Tutorials on screen already work fine, but once a new one enters the game, the description rather than being a normal rectangle will be very thin and very tall, often so bad the bottom is offscreen and unreadable.  This can be corrected by disconnecting and recommecting at which time all ones on the screen already work fine, but noew ones will have the same issue.  I suspect this has something to do with the odd screen resolution I have of 3840x1600	

**Expected behavior:**
Be readable	

**Actual behavior:**
Off Screen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PortableTech** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6018881/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6018882/Player.log)
![Eco-Tut-Issue](https://user-images.githubusercontent.com/12549279/108643323-1f012b80-7478-11eb-99c8-1907e64ba75d.PNG)

**Comment by SlayksWood** [comment]
@PortableTech Thank you for the report.
dup #20252
