### ISSUE TITLE
Exhaustion Limit extra bits

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20702]
- [ ] Make flags in Balance Manager that define what general activities are affected by exhaustion. Make them all on by default. Should be: farming, transport (vehicles), labor on tables, starting work order
- [ ] Make picking vegetables and starting work orders check exhaustion limit if flags set. 
- [ ] Add a warning message that appears every couple minutes for the last 10 minutes

**Comment by WeaselDog** [comment]
Merged in ClickUp
