### ISSUE TITLE
[0.9.3.0 beta staging-1937]Civics: Time Range in hours allow any GameValue picking

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20705]
We can select any type of game value inside the time in hours value which is very strange.

![Screenshot_105](https://user-images.githubusercontent.com/24981362/108814238-be2a3e00-75b2-11eb-9bf1-6e06306f87c9.jpg)

**Comment by WeaselDog** [comment]
Agree it can seem strange, but it is intended behavior for now to allow more options for this.
