### ISSUE TITLE
[0.9.3 staging-1937] Switch Description EN text 

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#20711]
it have localization, but on Crowdin was upload text - Click to switch this object's state.
https://crowdin.com/translate/eco-by-strange-loop-games/46/en-ru?filter=basic&value=3#q=Click%20to%20switch
how you can see in game it have [Click to switch this object's state.] not know [] it is error or not
![2021-02-23 (2)](https://user-images.githubusercontent.com/26339332/108829750-9bf7e680-75d9-11eb-8cb5-ebef6fc94771.png)

**Comment by Quadbro** [comment]
Need to change such cases on "()" if they do not work

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 279 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/25032c6e-dd19-4a0b-bef8-cf1efd8f41fc)
