### ISSUE TITLE
LOD Cross-Fading is broken, only works on moving away, not on getting closer!

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#20717]
![Broken LOD Fade.gif](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/390fefba-c862-467e-94e7-6c2ecb35545f)

As Title says, when you move away from LODS on plants which are supposed to cross fade, you only see the cross fade as you move away, but not as you get closer. This is a big popping effect that fixing would make just walking around the world a lot more smooth. 

I tried changing settings in plant prefabs, but nothing there worked, I'm pretty sure this is related to how plants are optimized and rendered in the chunks or DOTs system or something.

**Comment by redwyre** [comment]
@keegan-o your gif broke (you can attach mp4 now)

**Comment by SlayksWood** [comment]
@redwyre he probably just sent a message before the Gif loaded.

**Comment by WeaselDog** [comment]
@keegan-o What version was this bug introduced in? Can you put it in title?

**Comment by TwixterZ** [comment]
fix tested and confirmed on 9.4 develop 249

https://i.gyazo.com/466e5b58da03f650fbb4b46e2c57bb87.gif
