### ISSUE TITLE
USER ISSUE: disaperaing cards and stockpile

### ISSUE THREAD

**Issue by joewei2** [StrangeLoopGames/EcoIssues#20714]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
sometimes cards and stockpiles dont load from the server when you walk away and come back to the position
but they´re shown in stockpiles or card around it
by reloading throug relogin or go and come back they are back as expected

its also on a server within a local network

**Expected behavior:**
cards dont disappere

**Actual behavior:**
cards disappere on server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
For us to be able to investigate, please provide us with your game logs.
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Kindly make sure to reproduce the issue first. Once successful, you can then send us the latest game-generated log files.
It would also help us if you could provide us with a recorded video of the issue.

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response
