### ISSUE TITLE
[0.9.3 staging-1937] Wild Stew icon has strange texture

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20710]
![image](https://user-images.githubusercontent.com/45708377/108823941-29cfd380-75d2-11eb-809d-5c743fe8dbcd.png)
![image](https://user-images.githubusercontent.com/45708377/108823959-2f2d1e00-75d2-11eb-8d6d-ef75ce1e9ca8.png)
Also we have this icon for Campfire in ECOpedia:
![image](https://user-images.githubusercontent.com/45708377/108824035-49ff9280-75d2-11eb-981b-032ef0c3f528.png)

**Comment by keegan-o** [comment]
fixed in develop, not sure it's worth it to merge to staging at this point for this issue.
