### ISSUE TITLE
[0.9.2.4 beta release-156] Game Crashes or Video feed for game freezes,

### ISSUE THREAD

**Issue by ACryInShame** [StrangeLoopGames/EcoIssues#20716]
The game will just completely crash on me while I'm playing or the Video feed freezes. Like I can move around and my friends can see me moving but my screen stops updating.

These issues usually occur when something visual updates like I mine or place a block.

I'm unsure where the log files are to add them here.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
For uploading game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
When uploading game logs, please make sure that you reproduce the issue first and then upload the latest game-generated logs so we can see what's going on.
Furthermore, it would greatly help us in our investigation if you could upload a recorded video of the issue.

Thank you.

**Comment by ACryInShame** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6056352/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6056353/Player.log)

**Comment by ACryInShame** [comment]
Pulled log right after crash

**Comment by ACryInShame** [comment]
Any further info needed for this issue?

**Comment by ACryInShame** [comment]
I had both the stopping of visuals followed by a full crash. maybe this data can help 
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6073649/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6073650/Player.log)

**Comment by TwixterZ** [comment]
Same issue raised under [#20406](https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/20406)

I'm closing this issue, you may follow up on this issue at link above.
