### ISSUE TITLE
Laws: Craft list of laws should include all currently craftable things, and only craftable things

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2071]
Currently it includes uncraftable things, like acorns, and doesnt include craftable things, like workbenches.
Theres a Discovered list you can start with, then pare down to things that have a recipe.

**Comment by MarjieAVolk** [comment]
This is going to be an awkward task because of how stats work, as I said in person earlier.  I'll plan to work on it as part of the migration of stats to a database, which will not be for the alpha 6 release.
