### ISSUE TITLE
[0.9.4 Develop-192/0.9.3 Staging-1937]Large Corrugated Steel Door is intangible

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20718]
Tested on both 0.9.4 Develop-192 and 0.9.3 Staging-1937.

Issue: Players can pass through a closed Large Corrugated Steel Door.

Repro:
1. Place a Large Corrugated Steel Door.
2. Make sure it's closed.
3. Passthrough it and observe.

Video Repro:
https://images.zenhubusercontent.com/42199084/88a8e91c-d4af-4b5b-816b-27d5c133c5e2/2021_02_24_09_24.mp4

Related: #19534

**Comment by IcedForge** [comment]
There is also a pure visual problem when looking down as well.
https://i.gyazo.com/92dfec2e01d33e08c185229935482f4c.mp4

**Comment by IcedForge** [comment]
Seems like the branches / leaves on trees have the same issue as the corrugated door in its shader behavior with going awol on looking down. Easily visible when walking through a forest.
https://i.gyazo.com/1eabc9cb38e28d78ebef1bceced7285f.mp4

**Comment by IcedForge** [comment]
#20880 linked problem

**Comment by keegan-o** [comment]
Updates were made yesterday to totally refactor the door into regular rather than skinned renderers, which use scaling rather than morph targets-- so hopefully this issue should be resolved in the latest builds of staging.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1955.

The main issue is fixed. I am unable to pass through the large corrugated steel door anymore. 

Resolution: Closing.

However, on [PR 8016](https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/eco/8016), it says that the Large Corrugated Steel Door now has a new model. On this build, the Large Corrugated Steel Door still uses the same old model.

Will make a ticket once tested on newer staging builds.
