### ISSUE TITLE
[0.9.4 Develop-192/0.9.3 Staging-1937] Large Windowed Lumber Door vanishes from Player's view

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20720]
Tested on both 0.9.4 Develop-192 and 0.9.3 Staging-1937.

Issue: The Large Windowed Lumber Door when viewed at a certain angle vanishes completely from the player's view. When tested on Large Lumber Door, the issue is not happening.

Repro:
1. Place a Large Windowed Lumber Door.
2. Open the Large Windowed Lumber Door.
3. Look up and try to move around under the area of the opened Large Windowed Lumber Door.
4. Observe.

Note: Issue is not happening with Large Lumber Door.

Video Repro:
https://images.zenhubusercontent.com/47210472/cac0c42a-b3fb-42a6-9e29-b3d300345eec/2021_02_24_09_48.mp4

**Comment by Jason-Skillman** [comment]
### Solution
Updated `Skinned Mesh Renderer` to show mesh when facing away from object.
SVN commit 8334 (Staging)

https://user-images.githubusercontent.com/35405997/120823697-aead8000-c525-11eb-8b35-82515de9864e.mp4

**Comment by IcedForge** [comment]
Is this a new large corrugated steel door problem all over again?
https://i.gyazo.com/01a4d0690c851f2eaaf7085b7e020219.mp4

**Comment by Jason-Skillman** [comment]
Cannot seem to reproduce. Try double checking if you have SVN commit 8399 (Staging). Let me know if you still are running into the issue.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Staging 2009

![lumber door.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/5a53a688-792e-425f-a5e2-65ee4b223ebb)
