### ISSUE TITLE
[0.9.4 Develop-192/0.9.3 Staging-1938] QoL: Set vehicles to be limited by weight and not item count.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20724]
Tested in both 0.9.4 Develop-192 and 0.9.3 Staging-1937.

Issue: Vehicles have two sets of limitations when carrying items and those are item count and weight. As of this point, it's redundant to have an item count limitation if there's an existing weight limitation.

It's best to remove item count limitations and simply have weight limitations.

For example:
Powered Cart can only carry 360 pieces of granite with a total weight of 2340kg out of 3500kg maximum capacity. It's best if the limitation is solely based on weight capacity.

Screenshot:
![weight 2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/33e99c1c-bf0e-48fd-881a-7c2acd3b1804)

**Comment by danisani1** [comment]
Disagree: There should be a volume limitation and that is accomplished by slots.

**Comment by WeaselDog** [comment]
There are reasons we want this behavior
