### ISSUE TITLE
Viewing a civics object doesnt look readonly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20734]
Click the view:
![image](https://user-images.githubusercontent.com/3536496/109079113-514a9d00-76b3-11eb-9fba-293a85d27524.png)

You get this
![image](https://user-images.githubusercontent.com/3536496/109079099-498af880-76b3-11eb-9e6c-321ba35150c9.png)
- There's a big apply button. There should be no button.
- The dropdown icons arent enabled.
You cant edit things here, so its not broken, just looks wrong.

**Comment by SlayksWood** [comment]
I don't have Apply button, and can't change anything, but I have dropdown icons too in staging-1939:
![image](https://user-images.githubusercontent.com/45708377/109109413-59075180-7746-11eb-897d-c96d79f3b1a2.png)
Seems this issue in develop

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 279

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ba17ea00-181e-475d-a656-e353dbcf8975)
