### ISSUE TITLE
[0.9.3.0 beta staging-1938]Tags being inconsistent in chat linking

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20732]
Following tags are not properly detected.
Crop Seed
Fertilizer
Clothes
Crop
CrushedRock
Metal
Fuel
Tool
Housing
Upgrade
Food
Tools
Seeds
Crafting Table(hidden?)
Animal
Liquid
vehicles

![Screenshot_8](https://user-images.githubusercontent.com/24981362/108987890-1c7b1d80-7694-11eb-8a31-350330913803.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/24981362/108987903-20a73b00-7694-11eb-9c95-40e9a250b511.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/24981362/108987919-23a22b80-7694-11eb-848f-7b2bdbe008ec.jpg)

**Comment by WeaselDog** [comment]
This will be fixed in 9.6, thanks!
