### ISSUE TITLE
[0.9.3.0 beta staging-1938]Tooltips still affected by issues with mouse over due to simply too large.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20736]
Appliances should probably truncate properly to avoid these situations where tooltips have the same result as #20135 if things apply to enough tables making the tooltip longer then has a potential fit on the screen due to being too tall overall.

![Screenshot_23.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/77d71ab9-693a-4578-b899-26d93c5c725a)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/110763212-ae715180-8262-11eb-98e8-94d901f360b1.png)

**Comment by WeaselDog** [comment]
Still an issue for me in release when trying to view tooltip inside of a tooltip.

**Comment by WeaselDog** [comment]
This issue is fixed, my mistake
