### ISSUE TITLE
Move Cotton Gin to Farming Table

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20739]
Need to shift over the cotton ball processing into the farmers table as to include them for a number of reasons.

**Comment by keegan-o** [comment]
fixed in develop and staging, tested in staging before commit to be sure!

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/c6a88a56-5bba-4661-b31c-82c55f3e3069)
