### ISSUE TITLE
Industrial Elevator synchronization in multiplayer

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20738]
@SlayksWood So what happens is that the elevator moves on his screen but not on mine, for him the elevator is one place and for me, it is in another place for me.

[image of my friend standing on the elevator in his game client](https://cdn.discordapp.com/attachments/410443397065867284/812796312676335646/unknown.png)

Note: It sometimes works and other times it doesn't.

_Originally posted by @killerfrienddk in https://github.com/StrangeLoopGames/EcoIssues/issues/20158#issuecomment-785076922_
![image](https://user-images.githubusercontent.com/45708377/109112972-86ef9480-774c-11eb-9026-fe2435228a4c.png)

**Comment by Hydrar** [comment]
Hitting same issue in release, seems like the vehicles follow the client last driven them or something, the ones I've not driven last fall through the elevator or start shaking violently.
So works fine only for the player that uses it and their "used" vehicles, everyone else is desynced from it and see them flying away without the elevator.

**Comment by Dave247** [comment]
I've had this happen with the wooden elevator as well (which was where it was first noticed) which would lead me to believe that it is something up with how elevators work in general.

**Comment by vini2003** [comment]
I'm having this same issue and it is fairly problematic. Synchronization completely breaks when multiple playears are nearby.

**Comment by fabm3n** [comment]
We have the same issue and it's really annoying...
Hoping for a fix ASAP

**Comment by TheRisenPhoenix** [comment]
Same problem here, the elevator (regardless which one) isn't synced at all. It's simply not usable by multiple persons at one time, you can't use it together. It's like everyone is having their own one. That's really annoying.
Also, carts in there are sometimes causing the elevator to stop, or fall under it, causing it to get blocked when descending to the ground

**Comment by askaret** [comment]
Yup, same issue here as well (not with the industrial elevator, haven't built that yet - but with the first one.)

One person drives the elevator down, it remains stationary for me. I can see his character moving jerkily down the shaft. Another interesting experiment is to have one person drive the elevator down while another drives it up, even better if there are vehicles on both - chaos ensues :)

Hoping for a fix to this soon

**Comment by vini2003** [comment]
I wouldn't hold your hopes up, seems like a very low priority issue.

**Comment by vini2003** [comment]
Fellas, as a developer, I understand the difficulty and pain of dealing with this, but... please, it's been a year.

**Comment by IcedForge** [comment]
Almost all elevator issues have been fixed for 9.6, ill see what i can do to get them cherry picked for 9.5 but they are fixed in a future version.

**Comment by WeaselDog** [comment]
This has been fixed in the upcoming 9.6 release. Thank you for your patience with this one.
