### ISSUE TITLE
Computer crash with new update

### ISSUE THREAD

**Issue by sitissoui** [StrangeLoopGames/EcoIssues#20745]
As of yesterday my computer now crashes after joining my server for 30 seconds. Seems to be an update error.

**Comment by IcedForge** [comment]
@sitissoui Thank you for reporting, unfortunately there is little we can do without further information from your end.

Need to provide the following.
Server logs ( if you are playing single player or hosting yourself )
Player logs

Server log found in: ...\Eco\Eco_Data\Server\Logs or ...\Steam\steamapps\common\Eco\Eco_Data\Server
Player log found in: C:\Users\[YOUR_USERNAME]\AppData\LocalLow\Strange Loop Games\ECO or %USERPROFILE%\AppData\LocalLow\Strange Loop Games\ECO

Also would like a dxdiag dump for pc specifications and driver dates
Can be acquired by windows key + R, and type "Dxdiag" then in the dialog that opens at the bottom you have a "save information" which allows you to save it as a text document and upload here.

**Comment by TwixterZ** [comment]
Closing issue due to lack of response
