### ISSUE TITLE
[0.9.3 Staging-1939/0.9.4 Develop-192]Remove F character for when carrying items with forms that cannot be changed by Hammer

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20746]
Tested on both 0.9.3 Staging-1939 and 0.9.4 Develop-192.

Issue: When holding a hammer, pressing F enables players to alter the shape/form of the item currently carried by the player. However, this is not the case for Stone Road, Stone Ramp, Gasoline, Dirt Ramp, etc. So it's best to remove F if the functionality of it is unusable. 

Repro:
1. Hold a hammer and carry a Stone Road.
2. Press F and observe. Nothing happens.

If this is by design, then it's best to remove the F character when carrying items with forms that cannot be changed by a hammer. This gives false pretense for players most especially new ones. 

![F road.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/1c6c9ce8-0bf6-489e-9944-efa7d822c432)

**Comment by karlthepagan** [comment]
Repro'd and found in the issues list! Placing stone road tiles with a hammer I see "F" indicating block placement options (i.e. so i can place a contiguous shape like a line), however I do not get a placement menu when pressing F.

I would like to be able to place straight lines and flat squares of road tiles.
