### ISSUE TITLE
[0.9.4.0 beta develop-195]Civics broken via constitution not possible to add articles in

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20742]
Can not add articles, and there is no prefab populated ones inside the capitol upon placement.
![Screenshot_40](https://user-images.githubusercontent.com/24981362/109141924-8e1f9e00-775e-11eb-8d02-c5e88f71137d.jpg)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 267
