### ISSUE TITLE
[0.9.3 staging-1939] Elevator call post linking issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20740]
- [ ] 1. Elevator should have linking point in center, or +/- 1 block from center.
- [ ] 2. When linking call post we should include calculation with elevator size.

And so now what's the problem. Currently we have that call post is linking to the nearest center of Elevator. But we can have a strange situation, when one elevator is closer, but the Call Post will link to another:
![image](https://user-images.githubusercontent.com/45708377/109124512-0df83900-775c-11eb-9204-61adcee92a39.png)
Call post will be linked to Industrial Elevator №2, because his center is closer.
But if we change center we still need to include elevator size, because we have smaller version (Wooden Elevator):
![image](https://user-images.githubusercontent.com/45708377/109125442-23ba2e00-775d-11eb-81fd-3d43055e7c42.png)
So The center of Wooden elevator is closer, but Call post must link to the nearest Elecator(Industrial)

**Comment by TwixterZ** [comment]
Fix tested on 9.4 Staging 1992 

Call post need to be put very close to the industrial elevator if I wishes to put the call post in front. 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9396ac87-c40c-4831-9b31-f0a7a3ff0211)
_Put down call post 2 block in front of the elevator and call post failed to work, error message shown as above_

no issue if call post is put on the side

**Comment by SlayksWood** [comment]
Still an issue, Seems call post connects with offsetted center.
