### ISSUE TITLE
Laws: Mark various verbs with law UI in game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2074]
Feature request: 
Anywhere in the law where you can do something affected by a law, we should find a way to make it marked as such in the game.  We can put law icons on things, and mousing over them will describe the law

IE: 
Buying something restricted, place a Law icon above the trade offer
Accepting a contract, a law icon above the contract
Crafting something, a law icon above the recipe on the table
Claim Property, an icon above the property claim item 
Gain Skill, an icon on the skills
Harvesting things: icons in world perhaps?
etc

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#375
