### ISSUE TITLE
[0.9.3 Staging-1939]Blank error pop up when trying to store/move logs to a non-stockpile storage

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20744]
Tested on 0.9.3 Staging-1939

Issue: A blank error pop-up appears when trying to move logs to a non-stockpile storage or storage type that doesn't accept carriable materials.

Repro:
1. Move logs or granite to non-stockpile storage like Campsite storage.
2. Observe.

Result:
![blank error.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/b4c3cffb-8285-46b2-85cc-6d8b03e1b801)

**Comment by madpingui** [comment]
This is fixed in develop branch
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/46fe9e1e-1533-4459-9d49-38581e9d1d96)
It is related to this closed PR
#20198

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-281

Tested with various storage types including /preset storages.
Fixed. Closing.
