### ISSUE TITLE
Auth: look for user's tier in `user.tier_id` instead of `users_products.product_id`

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#20759]
Due to Accounts refactoring next change in Auth should be performed:
Remove all usages of `users_products` table, check user's tier/product in: `user.tier_id` from now on.
Price and transactionId could be found as before that in `all_purchases` table.

P.S. to avoid gap between both Auth and Accounts deployed to prod, it could be written like that:
check if `user` table has `tier_id` column, if it has, check only for `user.tier_id` if no (means not yet deployed), fallback to old check in `users_products.product_id`.

P.P.S was unable to find `Category: Auth` label for some reason and dunno which squad is that. Maybe @SlayksWood or @WeaselDog will help me with that ;) thanx!

**Comment by redwyre** [comment]
This is going to be pretty complicated to do, it will be easier to just update auth and accounts/db at the same time.

**Comment by j3fffff** [comment]
@mirasrael @redwyre can we get this on next week's sprint. we got a backlog of things that need to go out to production.
