### ISSUE TITLE
USER ISSUE: Tutorial GUI windows scaling issue

### ISSUE THREAD

**Issue by Fikzy** [StrangeLoopGames/EcoIssues#20750]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Large screen resolution (3440*1440)

**Expected behavior:**
Clearly not that.

**Actual behavior:**
Long and slim tutorial window that goes out of screen, making it impossible to read the content.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, fresh install

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![image](https://user-images.githubusercontent.com/38251360/109238135-41c27580-77d3-11eb-936b-12cd5afe9ead.png)

**Comment by SlayksWood** [comment]
@Fikzy Thank you for the report. Merged to #20252
