### ISSUE TITLE
[0.9.2.4] Waste Filter water output still flowing after pipe removal

### ISSUE THREAD

**Issue by jzeyn** [StrangeLoopGames/EcoIssues#20757]
Hi,

What you need to reproduce it: Waste Filter, Pipes, Input Source for the Waste Filter

When you setup a Waste Filter, everything works fine, but if you remove the Input Source from the Waste Filter, the water at the output pipe is still flowing. Resulting in some strange interactions, you can even remove all pipes and the water flow is still there. 

If you remove the Waste Filter, everything will reset. If you add the input again, everything will reset.

The setup:
![image](https://user-images.githubusercontent.com/44209119/109279340-ecf61d80-7819-11eb-80d4-5325a0408cbd.png)

Remove pipe from input:
![image](https://user-images.githubusercontent.com/44209119/109279429-072ffb80-781a-11eb-8300-0714561a3d94.png)

Remove all pipes:
![image](https://user-images.githubusercontent.com/44209119/109279490-17e07180-781a-11eb-90a2-6e70540acb82.png)

And just for the fun:
![image](https://user-images.githubusercontent.com/44209119/109279723-6261ee00-781a-11eb-8536-258a12063169.png)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. However, we are aware of a number of issues related to Water Filter and abnormal in-game behaviors related to it. For now, we will merge this ticket to ticket #18583.

Thank you.
