### ISSUE TITLE
[0.9.3 stagin-1940] Failed to handle RPC method: StopPropertyClaimingMode

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20758]
Step to reproduce:
- first player connect to server.
- second player connect to server.
- first player select land claim stake or land claim papers on toolbar.
- first player change active cell to something else(modern hammer)
- second player will be disconneted with this notification:
![image](https://user-images.githubusercontent.com/45708377/109284133-921bf080-7830-11eb-95c2-5bea84d73023.png)
[RPC.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6048721/RPC.txt)

**Comment by SlayksWood** [comment]
The same with openGraphs (one of 2 players press G to open graphs)

**Comment by TwixterZ** [comment]
same thing happens when trying to shoot an animal within property.

![image](https://user-images.githubusercontent.com/78054747/110758648-b42d5e00-8287-11eb-928d-41b73cad6456.png)

**Comment by IcedForge** [comment]
Removed the fixed label as it still has an open PR and is not fixed/deployed on staging.

**Comment by abaza121** [comment]
> same thing happens when trying to shoot an animal within property.
> 
> ![image](https://user-images.githubusercontent.com/78054747/110758648-b42d5e00-8287-11eb-928d-41b73cad6456.png)

I can't reproduce this, did u have 2 players online or more? were they far from each other? what was the situation like that made this error happen?

**Comment by TwixterZ** [comment]
@abaza121 this was tested with 2 players online in the session, we are during this incident less than 10 blocks away from each other. 

SituatioN : indoor area, in another user's property, shot at random rabbit jumping around

**Comment by abaza121** [comment]
> @abaza121 this was tested with 2 players online in the session, we are during this incident less than 10 blocks away from each other. 
> 
> SituatioN : indoor area, in another user's property, shot at random rabbit jumping around

I think it could be related to the rabbit, did the other player have bows or arrows? Will try to repro that then

**Comment by abaza121** [comment]
Also does that happen consistently?

**Comment by TwixterZ** [comment]
@abaza121 we have performed more test today, ultimately we are unable to consistently reproduce this error 100% of the time, 

from today testing session, while im getting the error message @SlayksWood was actually booted out during our testing with same message as i shared above.

![image](https://user-images.githubusercontent.com/78054747/111121124-38912100-85a7-11eb-8e49-6c0b6ddb45a7.png)

while im getting error message as follow in game

![image](https://user-images.githubusercontent.com/78054747/111121071-29aa6e80-85a7-11eb-9162-ddd832065818.png)

![image](https://user-images.githubusercontent.com/78054747/111121161-45ae1000-85a7-11eb-91ac-8d137037ba96.png)

**Comment by SlayksWood** [comment]
I was in qamode https://github.com/StrangeLoopGames/Eco/pull/8037, so this is intended behavior.

**Comment by SlayksWood** [comment]
first and second was fixed. Still have third. Closed this one and start a new issue.

**Comment by abaza121** [comment]
I think I'm not able to reproduce due to no lag on local server, I think I found the issue though, I will ask for the best way to simulate lag and will do a pr with a potential fix for this.
