### ISSUE TITLE
USER ISSUE: Can't connected to online server

### ISSUE THREAD

**Issue by Gael-GBC** [StrangeLoopGames/EcoIssues#20754]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**
i should have connect xD

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>Could not load file or assembly 'System.Net.WebHeaderCollection, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
Are you still unable to connect to an online server?
If so, please kindly provide us with your most recent generated game logs.
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.

**Comment by TwixterZ** [comment]
Closing issue due to lack of response.
