### ISSUE TITLE
[0.9.3.0 beta staging-1940]Tooltip mouse over flickers once before calming down on initial display

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20763]
When i'm mousing over civic duties articles sometimes they will flicker once on initial display of information
this will happen regardless of which tooltip style you have chosen.

Just calmly mouse over each article and go onto the next, usually catch it every few popups.

![Screenshot_69](https://user-images.githubusercontent.com/24981362/109320631-80e2dc00-7850-11eb-834f-6271030384ad.jpg)

**Comment by tomsseisums** [comment]
Can't seem to replicate the way you described, but can replicate in Ecopedia/Civics (Dialogs) by hovering, quickly hovering out and then back on.

If done fast enough, will flash multiple times.

Video:
https://user-images.githubusercontent.com/1030080/109322240-b8ef1c80-785a-11eb-9a67-f8a01b1c382a.mp4
