### ISSUE TITLE
Tied Elections fix

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20769]
Currently tied elections leave the office empty, causing severe drawback on servers.

If an election is tied a winner should be chosen randomly by an equal number dice roll.
If the incumbent is one of the people tied, we could also make that one win.

**Comment by olegshegai** [comment]
Extended election process' settings with two flags:
![image.png](https://images.zenhubusercontent.com/5edf842d257e177769a92a3c/94bfcd87-0bc7-4f56-a570-5ee94d9c9f37)

But can't test it (left a message in the squad channel).

**Comment by tuha263** [comment]
it's will be fix with: https://docs.google.com/document/d/1n1vcpEaUnTLOlmCTFTEjCup1bCNpSRj8mB28OJDW1-4/edit#heading=h.fpxjsxjtjbyx
