### ISSUE TITLE
USER ISSUE: Character camera is tilted

### ISSUE THREAD

**Issue by Melvintehu** [StrangeLoopGames/EcoIssues#20765]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Went to bed to sleep, after pressing escape and leaving the bed, the camera was tilted. 

**Expected behavior:**
It should not be tilted, it should be normal.	

**Actual behavior:**
tilted camera 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
There's an existing issue where if a player chose to sleep and presses the Escape button to wake the player's avatar,  the in-game time fast-forwarding doesn't stop. It has the same reproduction steps that you have provided for this report.

If it's alright with you, could you provide us with more information about the issue in this report? This will let us investigate this issue further. Unfortunately, the reproduction steps that you have provided triggers a known different issue.

It would be great if you could provide us a recorded video of the issue as it happens.
We will be waiting for your response. Thank you.

**Comment by Melvintehu** [comment]
Hi Daniel, 

I'm sorry but I already refunded the game in steam, so I cannot reproduce the problem. 

What basically happened: 
I went to bed ingame, and the character just stood beside the bed, but the camera was tilted like the player was laying in the bed. 

After I stepped out of the bed, the camera stayed in that position. 

I can't recall doing anything else than that. Hope this helps. 

Ill buy the game again once the game is more playable. Goodluck with the development!

**Comment by Daniel-Magulado** [comment]
Hi Melvintehu,

Thank you so much for giving our game a try. We deeply regret that we couldn't do much for you to enjoy the game. I hope you can grant our game, Eco, another chance. We pride ourselves on giving our 100% every day to polish the game and ensuring that it's a fun game to play with your friends. So we apologize for any inconvenience it might have caused or any form of unsatisfactory experience that led you to file a refund.

Additionally, thank you for providing even more information about the issue. I was able to reproduce it and will now forward the issue to our development team.

### Issue
![sleep](https://user-images.githubusercontent.com/77248866/109990259-34156e80-7d44-11eb-9a19-db11d6ab6cd1.jpg)

Description: The camera view of the player becomes messed/tilted if the player sleeps in 3rd person view then presses Tab twice in quick succession.

Repro:
1. Set view to 3rd person view.
2. Sleep.
3. Move the camera around a bit.
4. Press Tab twice in quick succession.
5. Observe.

Video Repro:
https://user-images.githubusercontent.com/77248866/109989459-79856c00-7d43-11eb-9340-fc42afb9e579.mp4

Note:
Pressing F5 fixes the camera view back to the first-person view. Pressing F5 again brings back to a normal 3rd person view.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267.

Fixed and closing.
