### ISSUE TITLE
Key activation with link doesn't work if you create a new account.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20762]
Step to reproduce:
- Use link with key to activate game: https://play.eco/game/key/'keyhere'
- click 'here' to register a new account:
![image](https://user-images.githubusercontent.com/45708377/109301960-b89a5580-7849-11eb-9c3f-7e719d4b169d.png)
- register a new account in opened form:
![image](https://user-images.githubusercontent.com/45708377/109302025-ce0f7f80-7849-11eb-8ead-99a5643d1357.png)
![image](https://user-images.githubusercontent.com/45708377/109302188-01eaa500-784a-11eb-8cee-0deb3cf2e958.png)
- you don't own ECO:
![image](https://user-images.githubusercontent.com/45708377/109302289-1d55b000-784a-11eb-8dbf-7a2086d31d86.png)

But of course you can enter Game Key and activate it here:
![image](https://user-images.githubusercontent.com/45708377/109302505-6a398680-784a-11eb-8cbe-3ae062257aa6.png)

**Comment by denysaw** [comment]
Fixed on Sandbox
