### ISSUE TITLE
Jobs.RecurringTransfer object reference is null - Wage Crash

### ISSUE THREAD

**Issue by Thalassicus** [StrangeLoopGames/EcoIssues#20768]
Steps to reproduce:
1. Click continue on the main menu.

Are you using mods:
No

Context:
I was experimenting with titles and demographics last night before signing out of my private game. I was specifically creating and removing these to try different settings, including wages for government titles and a newcomer demographic.

I'm attempting to find a way to recover the world.

# LOG FILE

<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Jobs.RecurringTransfer.get_ServiceMarkedUpName()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.SyncPropertyInfo`1.<>c__DisplayClass16_0.<.ctor>b__1(Object obj)
   at Eco.Core.Controller.SyncPropertyInfo`1.GetValue(Object obj)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'IncomeAndExpenses' of 'Eco.Gameplay.Players.User'
Error during packaging property 'ServiceMarkedUpName' of 'Eco.Gameplay.Economy.Jobs.RecurringTransfer'</size>

Edited out the entire log into a text file instead for readability.
[log1.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6060018/log1.txt)

**Comment by devpikachu** [comment]
Can confirm, same issue.

**Comment by IcedForge** [comment]
@Thalassicus Thank you for reporting, could you perhaps upload your save file and either link i there or send it to me via mail Jens@strangeloopgames.com or on Discord "Ice Forge # 5886"

**Comment by IcedForge** [comment]
Closing this issue as it should be resolved in the next hotfix (0.9.2.5)
