### ISSUE TITLE
CW auto update not working for dev tier

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20767]
testing world is on previous  release-dev version:
http://eco-testing-server.eco.hw.sfo2.do-slg.com/info

I ran the auto update task
which said it would update realease-dev to newest version `    [release-dev] => 0.9.2.4-beta-release-162-dev`

but the test world did not update.
this is on production

**Comment by denysaw** [comment]
The answer is here:
![image](https://user-images.githubusercontent.com/5720101/109580875-a3e4e880-7afb-11eb-953d-b6f811de7162.png)

@j3fffff But I found another problem while was testing:
![image](https://user-images.githubusercontent.com/5720101/109580923-b9f2a900-7afb-11eb-96bb-38e1b25c1b84.png)
