### ISSUE TITLE
USER ISSUE: [UI] [Tooltip] [Low severity] Experience bar of untrained professions displays uninitialised experience points.

### ISSUE THREAD

**Issue by PPJMM** [StrangeLoopGames/EcoIssues#20766]
\
**User Id: (slg195577)**
**Version:** 0.9.2.4 beta release-156
**Environment:** Windows 10 (x64), locally hosted server.

**Steps to Reproduce:**
1. Start or load the game [in-game issue].

2. Press "Z" to open the Skills menu.

3. On the left side of the menu, select any of the professions which are already discovered but where no stars are invested (e.g. being level 0).

4. On the right side of the menu, hover over the experience bar until the respective tooltip appears.

**Expected behavior:**
The tooltip should (perhaps) read:

"Experience
You are level 0 with no experience. You will level-up automatically when investing a star."

**Actual behavior:**
The tooltip reads instead:
"You are level 0 with NaN experience. [...]"

While NaN cannot logically be 0, it might be more readable to use descriptive text (see above) instead of displaying "not a number".

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, there are no mods installed (thus any behaviour regarding active mods is untested).

**Logfiles:**
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6053041/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6053042/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
However, this issue is similar to ticket #17022.

I will be merging your report to that ticket number.

Thank you.
