### ISSUE TITLE
Need pages for Keys activation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20761]
Step to reproduce:
- Use something instead of key in URL  (https://play.eco/game/key/randomkeyhere):
![image](https://user-images.githubusercontent.com/45708377/109290280-74eb2000-7838-11eb-8517-321905ad63ae.png)
-press okay and login in any account:
![image](https://user-images.githubusercontent.com/45708377/109290057-2ccbfd80-7838-11eb-81ad-3f987832dfa3.png)

**Comment by SlayksWood** [comment]
If you try to login to account where you have already activate key:
![image](https://user-images.githubusercontent.com/45708377/109290739-107c9080-7839-11eb-8d16-0353f7effc98.png)

**Comment by SlayksWood** [comment]
Use one key second time:
![image](https://user-images.githubusercontent.com/45708377/109291703-5423ca00-783a-11eb-9131-97cb89cdc093.png)

**Comment by SlayksWood** [comment]
If you don't create a new account, just login in already exist one:
![image](https://user-images.githubusercontent.com/45708377/109292163-02c80a80-783b-11eb-89f9-97fb3df24155.png)

**Comment by denysaw** [comment]
Fixed on Sandbox
