### ISSUE TITLE
Index out of bounds causing hard crash on Animal.SetMemory Dict.TryInsert

### ISSUE THREAD

**Issue by devpikachu** [StrangeLoopGames/EcoIssues#20771]
An `IndexOutOfRangeException` was thrown on `Dictionary.TryInsert`, under `Animal.SetMemory`. See logs attached below.

Upon manually restarting the server executable, the server ran without issues. Perhaps add graceful handling of the exception so as to not cause a hard crash? We haven't been able to reproduce the issue.

Exception thrown in console:
![image](https://user-images.githubusercontent.com/30475873/109386576-31f67e80-7904-11eb-85fe-5cfeb70baa24.png)

Log file:
[log_1.log](https://github.com/StrangeLoopGames/EcoIssues/files/6054348/log_1.log)

**Comment by mirasrael** [comment]
Happens because 
```csharp
this.Brain.Memory ??= new Dictionary<string, object>();
```
uses non thread safe Dictionary without locks which may be re-allocated in another thread.

**Comment by StanKryvenko** [comment]
This issue is fixed already in Develop, so I think no reason for moving it on staging branch

**Comment by IcedForge** [comment]
will close this since agreed to keep in 9.4
