### ISSUE TITLE
USER ISSUE: ecology start up failure - Connection Failed

### ISSUE THREAD

**Issue by james6078** [StrangeLoopGames/EcoIssues#20777]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
trying to join server and get this message

**Expected behavior:**
start up

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no	

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@james6078
Thank you for reporting,  please follow the template instructions to provide log files.
Also can you fill in and clarify a bit more on how you are joining a server? Is it your own? Someone elses?
What operating system are you using, what language and so on?

**Comment by TwixterZ** [comment]
Closing issue due to lack of response
