### ISSUE TITLE
Sounds for meteor destruction process

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20774]

**Comment by WeaselDog** [comment]
Here is a player created video to showcase the meteor destruction. You can see which parts still need audio: https://www.youtube.com/watch?v=PIxaC-_4TjE

**Comment by freakydna** [comment]
@SlayksWood fixed with https://app.clickup.com/t/10591183/ECO-13144, can close out when completed QA.

**Comment by freakydna** [comment]
Closed with QA https://app.clickup.com/t/10591183/ECO-13144
