### ISSUE TITLE
Cereal Germ

### ISSUE THREAD

**Issue by Jengerbread** [StrangeLoopGames/EcoIssues#20776]
Our millers are not producing cereal germ at the mill.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. However, we are unable to reproduce this issue.
We tested milling both Corn and Wheat and we get Cereal Germ every time.

For us to further investigate this matter, we would like to request more information about it.
Could you provide us with a recorded video as the issue happens, please?
It would also be great if you could upload game logs.
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

When uploading game logs, try to reproduce the issue first and then find the latest game logs generated by the game. Once you do, please select the most updated one and upload it here.

Thank you.

**Comment by TwixterZ** [comment]
Closing issue due to lack of response
