### ISSUE TITLE
[0.9.3 Staging-1941] Crafting should respect decimal value, otherwise remove it and set whole number value.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20782]
Tested on 0.9.3 Staging-1941.

Issue: In-game, there are certain items that can be crafted using their respective crafting table. However, the game does not respect or follow the value materials needed to craft the items. For example, crafting paper requires 0.5 Cellulose Fiber. This means players can craft 2 pcs of paper with 1 pc of Cellulose Fiber. However, upon crafting, the game consumes 1 pc of Cellular Fiber if set to craft 1 pc of Paper and does not respect decimal value.

Repro:
1. Find an item that only requires less than 1 pc of the required material to craft. Example, Paper.
2. Observe the crafting tooltip and craft the item.
3. Observe the consumed materials and the crafted item.

Result:
Crafting paper consumes 1 Cellulose Fiber despite the game stating that it only needs 0.5 Cellulose Fiber.

Note:
1. Player can craft up to 2 pcs of paper with 1 pc of cellulose Fiber. However, crafting 1 consumes 1 Cellulose Fiber. The game should respect the decimal value all throughout.

Screenshot:
![paper.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/81a0cc77-8274-4b24-8e00-c2507a566940)

Video Repro:
https://images.zenhubusercontent.com/47210472/c1217817-0c04-405b-9888-0a56df385d03/2021_03_01_03_15_trim.mp4

Suggestion:
If setting the game to respect decimal value all throughout might be too complex for its worth. I recommend following the same structure set for other craftable materials such as making it as a default/standard that players will receive 2 papers per craft instead of 35 labor and 1 Cellulose Fiber instead of one pc of paper per craft that consumes the same amount.

Note: The craftable item Paper is a good example here. There are many more craftable items that use a decimal material value in-game such as 
![desk.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/08243471-ee32-4690-b69e-6750e4af0e6b) and more.

**Comment by WeaselDog** [comment]
It does benefit, but only when crafting multiple items. For example, something that costs 0.5 will only cost 1 when crafting 2. For now, we will leave this behavior be.
