### ISSUE TITLE
[0.9.3 staging-1942] Wrong cotton highlight after collect cottons.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20785]
Step to reproduce:
- find any cotton with 100% maturity:
![image](https://user-images.githubusercontent.com/45708377/109459575-1d36f980-7a70-11eb-9ccb-df97c2f185f7.png)
- pick up it:
![image](https://user-images.githubusercontent.com/45708377/109459591-2758f800-7a70-11eb-9c2e-4f3dcb4f79d6.png)
- highlight is wrong, you need to reconect or reload chunk to fix it:
![image](https://user-images.githubusercontent.com/45708377/109459650-48214d80-7a70-11eb-8719-2dad13403c51.png)

**Comment by Lyrcaxis** [comment]
Fixed by adjusting the Scale Curve to have max height be on 0.5 age.
Commited to Trunk SVN.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 251
