### ISSUE TITLE
Laws: Add government controllable values

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2078]
Feature request:
Add clauses for laws to set the following government parameters when a law is passed:
- Election duration
- Law voting duration
- Minimum votes for law to be applied
- Percent majority to determine laws
- Dictator: A server leader's vote will immediately pass/fail a proposed law/determine an election
- Number of property claims to grant to new players
- Number of property claims to grant on level up

Also add ways to see all these values on the web page, and perhaps in game.

**Comment by SlayksWood** [comment]
@johnkslg 
Can you check this issue we have 5/7 points completed. I don't know should we need another 2?

**Comment by johnkslg** [comment]
Wow thats a blast from the past. We got most of those, and more changes will come in towns and cities update. Lets close for now.  Done!
