### ISSUE TITLE
USER ISSUE: ChainSaw Sound Stuck on Road

### ISSUE THREAD

**Issue by Rjritchie** [StrangeLoopGames/EcoIssues#20784]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Player jumped ontop of SteamTruck with Chainsaw in hand, while steamtruck on stampped dirt road. He then placed Chainsaw in authorized steam truck while ontop of steam truck. 

**Expected behavior:**
No lasting chainsaw sound	

**Actual behavior:**
Chainsaw sound stuck in same spot on road

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. However, we are unable to reproduce this issue.

For us to further investigate, kindly provide us with more information such as a recorded video of the issue as it happens.

Thank you.

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response
