### ISSUE TITLE
USER ISSUE: "Connection Timed Out"

### ISSUE THREAD

**Issue by ChangesInBold** [StrangeLoopGames/EcoIssues#20780]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Try connecting to 73.36.182.219:3000.

**Expected behavior:**
Allolwed connection

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6057459/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6057461/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
Are you still encountering this issue? Still unable to connect to your stated IP address of 73.36.182.219:3000?

**Comment by ChangesInBold** [comment]
I haven't attempted it again since filing the bug report.
Thanks for your response.
-- Shawn Metcalf 

    On Thursday, March 4, 2021, 04:34:16 AM EST, Daniel Moises Dizon Magulado <notifications@github.com> wrote:  
 
 


Hi, thank you for making a report about this.
Are you still encountering this issue? Still unable to connect to your stated IP address of 73.36.182.219:3000?

**Comment by TwixterZ** [comment]
@ChangesInBold, thank you for your response, are you still facing this issue since your comment?

**Comment by TwixterZ** [comment]
Thank you
