### ISSUE TITLE
Cloud World Configuration field have white text on white background in firefox

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20781]
![image](https://user-images.githubusercontent.com/25908592/109431164-600fb780-7a05-11eb-8d80-436019f8cf69.png)
![image](https://user-images.githubusercontent.com/25908592/109431117-12934a80-7a05-11eb-8411-05b58fc195cf.png)

**Comment by j3fffff** [comment]
on staging
