### ISSUE TITLE
USER ISSUE: Server Owner is a pedophile

### ISSUE THREAD

**Issue by ryannadell** [StrangeLoopGames/EcoIssues#20795]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Found out from other players that the main staff had been communicating to underage girls in the server and giving them stuff in exchange for them to hang out with him and other things, I then called him out on it and he banned me instead of doing what he had to do and quitting his actions.

**Expected behavior:**
For him to not be a subhuman disgusting piece of garbage

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

You have been banned from this server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is not the right place for such a report. If you feel there has been illegal action, please contact your local police about it and provide it with necessary evidence you have. You can provide the same evidence to dennis@strangeloopgames.com (including name of server and owner) for us to investigate if there has been a violation of ToS.
