### ISSUE TITLE
Work order notification erroneously visible on new world start

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20809]
![image](https://user-images.githubusercontent.com/3536496/109711503-cb679f80-7b53-11eb-90ba-c8288941c7b1.png)

**Comment by SlayksWood** [comment]
Need to fix/test on 0.9.4 develop

**Comment by SlayksWood** [comment]
link #20559

**Comment by Mattprass** [comment]
does not seem to be happening on latest develop:
![ss](https://user-images.githubusercontent.com/31013483/111384293-b6c0f680-867f-11eb-8bb7-8592a147ab06.png)

**Comment by TwixterZ** [comment]
tested on 5 new world generated on 9.4 Develop 268, didn't face this bug.
