### ISSUE TITLE
[0.9.3 staging-1943] Not clear purchase and selling message at one time

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20802]
Step to reproduce:
- buy something for 5 credits and sell something for 2. Trade result: -3
![image](https://user-images.githubusercontent.com/45708377/109619259-9ce4c700-7b49-11eb-983d-a1d70035d671.png)
- You have this message:
![image](https://user-images.githubusercontent.com/45708377/109619300-ac641000-7b49-11eb-9863-f4b0cf485481.png)
- buy something for 2 credits and sell so,ething for 5 credits. Trade result: +3
- but you still have the same message:
![image](https://user-images.githubusercontent.com/45708377/109619519-eaf9ca80-7b49-11eb-93d1-fc6ed8c2d922.png)

So we need to add 'gained' (+) and 'spent' (-). Something like that:
![image](https://user-images.githubusercontent.com/45708377/109619909-593e8d00-7b4a-11eb-8097-9ef3f96de236.png)

**Comment by Daniel-Magulado** [comment]
Closing. Updates made on Clickup. https://app.clickup.com/t/10591183/ECO-12333
