### ISSUE TITLE
[0.9.3 staging-1943] Unity Crash when closing game

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20803]
It happens very often, but randomly:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6067266/Player.log)
https://drive.google.com/file/d/1tAMQJwVa_xeo1WXmg-kUrYbRq81jxqOS/view?usp=sharing

**Comment by IcedForge** [comment]
This started happening to me after that windows update a few weeks back never had it before and now it happens on all branches.

In particular on 9.3 but i also have it occur when switching between servers on live release and the occasional just exit game.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/20162
