### ISSUE TITLE
Following wonky for map when zoomed in far

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20818]
![anim](https://user-images.githubusercontent.com/3536496/109759873-99315e80-7ba2-11eb-98b6-e751eace80b6.gif)

Its worse in the docked one too.

**Comment by TwixterZ** [comment]
fixed as of 9.4 develop 225
https://gyazo.com/ff1d6100012c532d9c20c2f692181c15
