### ISSUE TITLE
Game fade in is not smooth

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20811]
![anim](https://user-images.githubusercontent.com/3536496/109719700-e3442100-7b5d-11eb-8d20-0ee2ff89f1a7.gif)
It should be perfectly smooth, it hitches. Propbably the lerp being started multiple times again, like in https://github.com/StrangeLoopGames/EcoIssues/issues/19956

Overfix this so it never comes back and cannot even be accidentally done!

**Comment by madpingui** [comment]
Tested on develop branch unity editor, my fade doesn't look like its hitching.
https://images.zenhubusercontent.com/47210472/784926ef-b1da-4ab3-93f2-8098b8652c61/fade.mp4

**Comment by TwixterZ** [comment]
fix observed and confirmed as of 9.4 Staging 288
