### ISSUE TITLE
USER ISSUE: Skid Refuse to empty inventory anymore

### ISSUE THREAD

**Issue by FuzzyWuff** [StrangeLoopGames/EcoIssues#20822]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Take dirt from world or stock pile
press RMB to dump content
Nothing happen, either in world and in stock pile

**Expected behavior:**
the content should be emptied, filling the world hole/space or stocking the stock pile

**Actual behavior:**
it just do nothing, it remain in the skid inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mod installed, and it happen with no mod installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by FuzzyWuff** [comment]
It seem that pressing third person break the placement ghost and the ability to place dirt. Only way to fix it is to restart the server, but it immediately break soon after.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
Unfortunately, we are unable to reproduce this issue.
For us to further investigate this issue, please upload a recorded video of the issue as it happens and game logs after successfully reproducing the issue. 

To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response
