### ISSUE TITLE
[0.9.3 staging-1943] Bank accounts in Bank issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20823]
- [x] 1. Unnesesary Advanced settings. You can only add description here, but this discriptiuon none will see because this uses nowhere:
![image](https://user-images.githubusercontent.com/45708377/109793503-c83ce400-7c25-11eb-8990-e8fdae7d887c.png)
Previous you could made government  account here (just adding check mark). But currently we have other option to create government account:

- [x] 2. No difference in bank between Users account and Government bank accounts:
![image](https://user-images.githubusercontent.com/45708377/109794442-ec4cf500-7c26-11eb-8ae7-fd20f4045e2c.png)
There is not even a tooltip in front of the name which can clarify this
![image](https://user-images.githubusercontent.com/45708377/109794594-0dade100-7c27-11eb-9a64-42e37f08cb7a.png)
![image](https://user-images.githubusercontent.com/45708377/109794610-143c5880-7c27-11eb-8692-c7fb84490da5.png)

**Comment by Daniel-Magulado** [comment]
Closing. Update is done on Clickup.
