### ISSUE TITLE
Highlight Color of Pickable vs. Not Pickable Stone and Ore not Color Blind Friendly

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2082]
my friend plays Eco (loving it) BUT in the latest staging (6) the Green outline (around blocks you can pickup) and browny yellow colour (around blocks you have to hit again with pickaxe) look exactly the same to him, so he can ONLY work out which ones he has to hit again by the size.
 (the rest of the game is fine to him, only these fine colours in the green, yellow and red spectrum are a problem)
Changing the colour of these couldn't hurt so we don't cause people with Colour Blindness any great difficulties.

![snap8165](https://user-images.githubusercontent.com/29383891/110477247-d9c93480-80da-11eb-96d3-98b9c2b88af3.png)
![snap8166](https://user-images.githubusercontent.com/29383891/110477258-dc2b8e80-80da-11eb-9b07-1904683d8c49.png)
![snap8167](https://user-images.githubusercontent.com/29383891/110477267-de8de880-80da-11eb-8b64-b878fb6dd09c.png)

**Comment by keegan-o** [comment]
I could use your help in altering this @redwyre ! I assume what we would want to do is alter the yellow outline to be something else, not totally sure what the best option is honestly. Maybe we consider adding some kind of other UI element that replaces the cursor or something.

**Comment by redwyre** [comment]
we could make the colours user configurable, or have a colour blindness mode

**Comment by redwyre** [comment]
Also I recommend we create a filter (could be developer only) that simulates the different types of colour blindness: 
![image](https://user-images.githubusercontent.com/431728/110453362-d00ef380-8111-11eb-9070-38ab6a1072df.png)

**Comment by Conchipedia** [comment]
![snap8164](https://user-images.githubusercontent.com/29383891/110476132-8e625680-80d9-11eb-8d28-8491baca530f.png)

You already have an Option For Arachnophobia in Settings, adding one there for Colorblindness would work .

but its finding out which one is the most common that might be the issue

**Comment by IcedForge** [comment]
Need to make sure this covers texts & all interfaces etc where things might be weirdly colored out or faded due to this.

**Comment by R4wizard** [comment]
I've only recently just discovered that some item frames are yellow, some are green - this difference is impossible for me to see.

I recommend an alternative to solving this with different colours - or selectable colours. As a colourblind person, I often relegate colour in terms of an identifying factor (why trust a sense that doesn't work properly?), and as a result, I personally prefer solutions that handle this with solutions not involving colour, for example:
- Shapes (change the item frame shape as well as the colour?)
- Patterns (dotted colour, dashed colour)
- Icons / Text (add an upgrade icon on the frame, maybe with a number indicating the level)

Just my 2cents :)

**Comment by Daniel-Magulado** [comment]
Closing, updates done on Clickup and is fixed on 0.9.5 Develop-362. https://app.clickup.com/t/10591183/ECO-13821
