### ISSUE TITLE
Trying to start the election for a constitution on tiger leads to darkened screen with no hint whats going on

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20827]
![image](https://user-images.githubusercontent.com/25908592/109833707-c7b24680-7c41-11eb-8e88-fac9160eabcc.png)

**Comment by D3nnis3n** [comment]
ESC makes it go light again. I found hidden in notifications I had not enough online time.

**Comment by Daniel-Magulado** [comment]
Changes made on Clickup. https://app.clickup.com/t/10591183/ECO-11880
