### ISSUE TITLE
[0.9.3 Staging-1943] Unable to Dump Contents to any Lumber Stockpile using Skid Steer

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20824]
Tested on 0.9.3 Staging-1943

Issue: Unable to Dump Contents to either Lumber Stockpile or Large Lumber Stockpile using Skid Steer Dump Contents function.

Repro:
1. Use Skid Steer and Dig up some stuff.
2. Dump the contents you dug on step 1 to any Lumber Stockpile.

Result:
Blank Error.

NOTE: I am not encountering any issues when dumping contents to a small stockpile or stockpile.

![ss.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/69d4715d-8eb5-4257-978b-f8ba4961264a)

**Comment by Quadbro** [comment]
Fixed in svn in develop branch

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267.

Fixed and closing.
