### ISSUE TITLE
USER ISSUE: Sleeping Bug

### ISSUE THREAD

**Issue by chye76** [StrangeLoopGames/EcoIssues#20834]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Go to sleep on the bed.
Hit ESC to wake up.

**Expected behavior:**
Just woken up and gone back to playing normally.

**Actual behavior:**
Caused player to be up and moving and playing with the same day/night cycle speed as sleeping.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report.Yeah, we have such a problem in 9.2.4 and it will be solved in 9.3 with StrangeLoopGames/Eco#7769
To stop fastforwarding you can sleep again and press Wake up button:
![image](https://user-images.githubusercontent.com/45708377/108585047-1f55d580-7357-11eb-8954-db33e9fc30ab.png)
closed for now.
