### ISSUE TITLE
hostname not supported

### ISSUE THREAD

**Issue by Talamar1** [StrangeLoopGames/EcoIssues#20833]
Using a FQDN instead of IP fails to connect to hosted server despite the FQDN working and validated through DNS tools.  Input says ip address or hostname but it doesn't resolve hostnames.

**Comment by D3nnis3n** [comment]
Hello Talamar,
I cannot reproduce this issue. Even our official servers use hostnames and they work fine.
Can your provide any additional detail you may have?

**Comment by TwixterZ** [comment]
Closing issue due to lack of response
