### ISSUE TITLE
USER ISSUE: Can't remove permission from bank account

### ISSUE THREAD

**Issue by Ailithic** [StrangeLoopGames/EcoIssues#20836]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Unselect permission from user select menu

**Expected behavior:**
Remove the permission of unsleceted user

**Actual behavior:**
User or demographic is not removed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I dont think the server is modded no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ailithic** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6090507/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6090510/Player.log)

**Comment by Ailithic** [comment]
Bug persists after Validating files and clearing Mods folder at %LOCALAPPDATA%Low/Strange Loop Games/Eco

**Comment by TwixterZ** [comment]
Thank you for reporting this @Ailithic I have tested this in my private game, and seems that I do not face this problem.

Does this happens to you in a public server or your private game? Have this happen to you again since?

Appreciate you providing these additional information for us to pinpoint the cause of this issue.

**Comment by IcedForge** [comment]
Can you post a screenshot or a video detailing what you mean specifically, im a bit confused.

Is this in relation to X missing from the registrar/bank object?

**Comment by IcedForge** [comment]
Please reopen this issue if this still occurs and please add in the aforementioned additional information when this is done.
