### ISSUE TITLE
[0.9.4 Develop-198]Localization Error for trying to place ground intended items to walls

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20830]
Tested on Develop-198

Issue: When trying to place/attach items, that are designed to be placed on solid ground, to walls, an error appears that's not localized for players.

Screenshot:
![lozalization.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/1aea6683-796e-415a-b79d-b9ae5914bcaa)

Cannot be tested on Staging and Release, blocked by #20145.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1971

Also happens on this build.

![image](https://user-images.githubusercontent.com/77248866/113729130-4e6aaf80-9729-11eb-9134-c71ecd48fe99.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/115514128-79f2ab80-a28c-11eb-8837-7bc57d687198.png)
