### ISSUE TITLE
USER ISSUE: Untransferable Amount of money preventing bank account deletion

### ISSUE THREAD

**Issue by Ailithic** [StrangeLoopGames/EcoIssues#20837]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Have 17.8 or so money
Transfer that money to another account
For some reason 0.00000381 was left in the account. (The amount shown in the Account screen is 0)

Cannot transfer the difference into the account to round the number out, so no I can't delete the account.

**Expected behavior:**
Money to not slide into tens of thousandth decimal place

**Actual behavior:**
Number is rounded no matter what to acceptable transferable decimal place

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I don't think so

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ailithic** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6090504/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6090506/Player.log)

**Comment by StallEF** [comment]
/money deleteaccount BankAccount  - Deletes an account even if there is still currency on it.

**Comment by TwixterZ** [comment]
Thank you for reporting this @Ailithic I have tested this in my private game, and seems that I do not face this problem.

Does this happens to you in a public server or your private game? Have this happen to you again since?

**Comment by StallEF** [comment]
@TwixterZ  it problem was on version 8 too. UI in game show only 2-3 digits after decimal point, but any arifmetics operation how tax or fine under the law where interest is used all 8 digits after decimal point.

**Comment by TwixterZ** [comment]
@StallEF I have tested this against account that was taxed, by government, and still able to close said account after transferred all the funds to another account, if you know anyone else facing this issue, maybe you can assist by sharing their save file here? so we can look into this better.

**Comment by IcedForge** [comment]
This originates from this #12626 problem so will use that for tracking and bumping priority and closing this as the problem like mentioned is because its decimals not accessible by the player and not included in all transfers.
