### ISSUE TITLE
[0.9.3 Staging-1945]Reset Tutorial box button doesn't get highlighted when mouse icon hovers over it

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20840]
Build: 0.9.3 Staging-1945

### Issue
The Reset Tutorial button found in the settings UI under the tutorial tab does not get highlighted when the mouse icon hovers over it while the rest of the clickable buttons gets highlighted.

Repro:
1. Proceed in the game.
2. Press the Esc key and proceed to the tutorial tab.
3. Hover the mouse icon over the Reset Tutorial box button.
4. Observe.

Video Repro:
https://images.zenhubusercontent.com/42199084/3d28ee04-abfd-4821-825a-7663c575c5c0/2021_03_06_03_22_trim.mp4

**Comment by TwixterZ** [comment]
fixed as of 9.4 develop-225

https://gyazo.com/872a770e5b2d172ecae03c15212341e4
