### ISSUE TITLE
[0.9.4 Develop-203]Missing sleep animation for first-person camera view

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20848]
Build: 0.9.4 Develop-203

### Issue
Missing going to bed animation when players try to sleep.

Note:
- Issue only occurs with a first-person camera view.
- There's a sleeping animation when in 3rd person view.
- **There's also an adverse effect where the player gets stuck momentarily after waking u**p.

Repro:
1. Try to sleep.
2. Wake up and try to move out quickly.
3. Observe.
4. Change camera view to 3rd person view (press F5).
5. Try to sleep.
6. Observe.

Video Repro:
https://images.zenhubusercontent.com/47210472/0e1252da-42b4-4a88-a4f2-3574ca7fe4fd/2021_03_07_19_20_trim.mp4

**Comment by Quadbro** [comment]
Fixed in Latest sleep changes in develop
