### ISSUE TITLE
[0.9.2.4 beta release-156]All objects on all plots removed when evicted

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20860]
White tiger objects vanished.
Bank
Board of Elections
Capitol
Census Bureau
Court
Government office
Mint
Registrar
Real Estate Desks
Treasury
Zoning Office

No clue as to why this is happening

**Comment by IcedForge** [comment]
After some digging it seems like a problem with eviction from renting where if you rent and have access to another plot, it removes all objects on all plots even if you are not renting the other one.

**Comment by IcedForge** [comment]
This seems to also happen on leaving a rented plot as well.

**Comment by tuha263** [comment]
@IcedForge I can't reproduce it, maybe it was caused by another case.

**Comment by IcedForge** [comment]
Resolved in 9.3 - staging 1964 verified
