### ISSUE TITLE
[0.9.3.0 beta staging1949] Garage Doors tooltip incorrect for open/close

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20868]
All the large doors points to "Turn Off" or "Turn on" which is also weird and not open/close

On that point (overfixing)- Do we want all doors to state their functional state? IE only list "Open" if the door is closed? Or do we want it to say both "Open/Close"?

![Screenshot_6.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/cd84541c-0cea-464f-b685-7e125c54b481)

This is all the large doors (corrugated steel, windowed lumber, lumber door)
![Screenshot_7.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/9356fae1-3a6f-485a-8da7-9694cec01296)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267

2 issues are fixed.
Large doors now use Close/Open and doors now state the opposite action.
If the door is open, it states click to close and vice versa.
Fixed and closing.
