### ISSUE TITLE
USER ISSUE: Holding items while claiming land - odd behaviour

### ISSUE THREAD

**Issue by sekman99** [StrangeLoopGames/EcoIssues#20863]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Hold for example Hewn Logs
2. Claim Land
3. Land get claimed but a hewn log will be placed on the ground that you can't pick up. After loggin out and in the log will be gone

**Expected behavior:**
Land should be claimed without dropping what is held in hand	

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, not tested without logs

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. However, we are already aware of this issue.
You can learn more about it here #20500.
Marking as duplicate.
