### ISSUE TITLE
USER ISSUE: No Ore

### ISSUE THREAD

**Issue by BenxProductionz** [StrangeLoopGames/EcoIssues#20879]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
/

**Expected behavior:**
Ore should be in the World.

**Actual behavior:**
Just Coal there.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6111291/Player.log)

**Comment by D3nnis3n** [comment]
How do you know there is no ore?

**Comment by SlayksWood** [comment]
@BenxProductionz Thank you for the report. unlikely, usually ores lies at a depth. But can you provide your world for investigation? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by BenxProductionz** [comment]
Yes, the zip file contains the .db file and the .eco file.

[World.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6113825/World.zip)

**Comment by IcedForge** [comment]
Sorry for the long hold, but you have ore on your world.
![Screenshot_83.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/fbc75b81-619d-46ec-97d2-8284dc75de0e)

will close as resolved.
