### ISSUE TITLE
Economy Viewer's tables wont scale properly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2088]
An issue with the table layout is preventing the tables of the economy viewer from scaling properly, couldn't figure out the right setup we need, can you take a look when you have a chance?
![image](https://user-images.githubusercontent.com/3536496/30293067-22d30b96-96ed-11e7-9e69-ca412896773a.png)

**Comment by MarjieAVolk** [comment]
The problem is that the currency text is wrapping?

**Comment by johnkslg** [comment]
No I fixed that actually. The problem is that the scroll box containing the entries doesnt maintain the correct size as you resize the economy viewer.

**Comment by MarjieAVolk** [comment]
Fixed

**Comment by MarjieAVolk** [comment]
The error you're showing is not the same as this bug.  I will take a look at that

**Comment by Conchipedia** [comment]
i think what might be needed is the Item column auto extending to fit the longest entry, no matter how much you change the size of the main window it never changes the sort of overlap i am getting
