### ISSUE TITLE
Prevent RPC exceptions from disconnecting the client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20889]
Two reasons:
1. Disconnecting the client as means of drawing attention to a bug is not acceptable, as it punishes the users for what may be innocuous bugs.  Need to take another approach in a separate task to draw attention to RPC exceptions.
2. Disconnecting in debug mode loses the state youre debugging in and adversely affects development

**Comment by mirasrael** [comment]
For DEBUG mode we can use Assert, in --qamode we can keep disconnect to get QA attention, in release mode we should ensure it reported to Bug Reports server. Also it makes sense to add in-game UI element which appear when any error written to log and user may easily report an issue with associated error log.

**Comment by abaza121** [comment]
> For DEBUG mode we can use Assert, in --qamode we can keep disconnect to get QA attention, in release mode we should ensure it reported to Bug Reports server. Also it makes sense to add in-game UI element which appear when any error written to log and user may easily report an issue with associated error log.

my only takeaway for that is that we should let QA know that this disconnection won't happen without --qamode

**Comment by SlayksWood** [comment]
With QA - was disconnected, without qa - have notification. That's right.
