### ISSUE TITLE
[0.9.4 develop] Clarify Estimated Play Time UI

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#20883]
The UI for Estimated Hours Played Per-Day is not clear what this related to. From my interpretation, it is just matching people with similar estimated playtime. This is one of the first UI screens a new player is presented with, and entering a low playtime value could accidently get them in a server with settings they don't want.

It should be more clear that the servers it will recommends will have a limit for playtime so a first time Eco player can make a more informed choice.
![EstimatedHoursUI](https://user-images.githubusercontent.com/47330823/110588850-7109a880-812a-11eb-8f79-41113f8b946c.png)

**Comment by IcedForge** [comment]
New tip for it looks better and a lot more descriptive, i still dont like that it is baked into the same playtime button as the other feature but have a separate issue for that.
![Screenshot_85.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/3e265b45-b6de-4b1b-83bb-6854ba576af6)
