### ISSUE TITLE
9.3 1949 Tree shade varies depending on camera angle 

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20880]
![image](https://user-images.githubusercontent.com/61889138/110552309-027b1980-812f-11eb-8775-70a773dab3e5.png)

![image](https://user-images.githubusercontent.com/61889138/110552342-10c93580-812f-11eb-9eb3-14f09938dd4e.png)

It is massively more noticable in first person

![image](https://user-images.githubusercontent.com/61889138/110552402-2f2f3100-812f-11eb-8a07-39c52b25e9bc.png)

![sunny shade](https://user-images.githubusercontent.com/61889138/110552548-761d2680-812f-11eb-9a38-006b3ca5991b.JPG)

GPU Settings
![image](https://user-images.githubusercontent.com/61889138/110552587-8a612380-812f-11eb-843f-d8dc22266458.png)

**Comment by TwixterZ** [comment]
Thank you @MishkaFur for reporting this, will have our developer to have a look

**Comment by keegan-o** [comment]
It's the camera movement affecting time of day bug again, looks like!

**Comment by Jason-Skillman** [comment]
Unable to reproduce this issue on 0.9.4. Looks like another previous issue may have fixed this already. Tree shade seems to be working as intended.

**Testing environment:**
- I tested with both first and 3rd person
- Matched provided graphic settings
- Tried with different graphic settings
- Tested with various times of the day
- Different screen resolutions

**Comment by redwyre** [comment]
Were you able to repro it in 0.9.3?

**Comment by MishkaFur** [comment]
I cant repro in 9.3.1 release 204
