### ISSUE TITLE
Make star pulse more gently

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20892]
![anim](https://user-images.githubusercontent.com/3536496/110727113-7b31b280-81cf-11eb-8264-f9b43be2d6ca.gif)
It should be a gentle on-hold-off like it used to be, like breathing.  
Also make it centered.

**Comment by TwixterZ** [comment]
Changes completed

https://gyazo.com/7d825041596418d81127174315750c9b
