### ISSUE TITLE
AutoUpdate version stopped working cause of S3 went private

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20897]
Should be 0.9.3 staging-1951:
![image](https://user-images.githubusercontent.com/45708377/110789368-d8d20780-8280-11eb-89c3-b7cd0d0d8012.png)

**Comment by StallEF** [comment]
@SlayksWood  https://github.com/StrangeLoopGames/EcoIssues/issues/20669

**Comment by redwyre** [comment]
@j3fffff / @denysaw you can just delete the 9.4 staging build(s) from s3

**Comment by j3fffff** [comment]
sandbox is not kept up to date with builds. so can ignore that.

**Comment by j3fffff** [comment]
Oh i guess there is also a bug for produciton too

**Comment by redwyre** [comment]
I've deleted the offending objects

**Comment by redwyre** [comment]
but /cron/scanDownloadServer is returning 500

**Comment by denysaw** [comment]
@redwyre On staging (sandbox) or on Prod? It's fixed only on Staging right now. Prod still requests public bucket object list. Which is closed now

**Comment by redwyre** [comment]
@denysaw I deleted the files from S3, so both prod and staging accounts should be getting the proper eco versions now. Prod returns 500 on a scan (is the 500 from an S3 error?), and sandbox returns 200 but doesn't update.

**Comment by denysaw** [comment]
As I said in my last comment, we didn't yet deploy to Prod. So we do know it still returns 500. Thank you. And seems you didn't delete it from `eco-releases-staging` in `eu-central-1`, cuzz I'm still getting it on Staging.
