### ISSUE TITLE
ecoauth unable to enter username

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2089]
![image](https://user-images.githubusercontent.com/1900106/30293228-1591c994-9739-11e7-87bb-5969d688392c.png)

If i enter my username and press enter, it does nothing, no request or something else.

I don't know where to file that issue, so i choosed this here.

**Comment by noblackthunder** [comment]
@rainfarmer have you had a look to the account page?

**Comment by Fank** [comment]
sure, and thanks for helping

**Comment by noblackthunder** [comment]
possible cache issue btw ? just got the mail for github invite

**Comment by rainfarmer** [comment]
Fixed issue, added you to GitHub @Fank 

Thanks for letting us know
