### ISSUE TITLE
[Web sandbox] ECO invitation has wrong info

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20898]
![image](https://user-images.githubusercontent.com/45708377/110794507-e094aa80-8286-11eb-86ea-60c3b609dfba.png)
We don't have this functionality, and this is looks strange. When you send invite to Email, but someone else can registrar into your e-mail (we don't nned to confim it now) and then change it).
I guesss just delete this info.

**Comment by denysaw** [comment]
Done on sandbox
