### ISSUE TITLE
[0.9.3 staging-1951] Can't interact with big object from all side.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20893]
For example court:
![image](https://user-images.githubusercontent.com/45708377/110745006-aa860500-824b-11eb-819f-f01c0413099e.png)
Center point in orange. You can interact with court in green zone, but in red you will have message:
![image](https://user-images.githubusercontent.com/45708377/110745063-c7223d00-824b-11eb-8314-9928b429cfb3.png)
With trees happens the same you can't chop branhes on high:
![image](https://user-images.githubusercontent.com/45708377/110745175-ef11a080-824b-11eb-86e0-ae04520140fb.png)
you can just chop tree in green zone:
![image](https://user-images.githubusercontent.com/45708377/110745240-00f34380-824c-11eb-8fb9-ce98c4af6b05.png)

**Comment by WeaselDog** [comment]
Introduced by https://github.com/StrangeLoopGames/Eco/pull/7964

**Comment by IcedForge** [comment]
This is still a large problem for taller trees with wood cutting as most of the times these fall way outside the radius range detection.

**Comment by SlayksWood** [comment]
Seems better, but still have issue with Industrial Elevvator:
![image](https://user-images.githubusercontent.com/45708377/112112139-342bc000-8bc6-11eb-989b-6f106e492379.png)

**Comment by SlayksWood** [comment]
Still have a problem with Industrial Elevator: The buttons are not used when you go down on it:
![image](https://user-images.githubusercontent.com/45708377/112458198-9c68d600-8d6d-11eb-8167-9331f975b9d7.png)

**Comment by SlayksWood** [comment]
Also need to check occupancy check for doors. SO currently when you try to close door on maximum distance:
![image](https://user-images.githubusercontent.com/45708377/113099998-7a56d400-9203-11eb-953d-25caff95554b.png)
you should have warning in command line (server log):
![image](https://user-images.githubusercontent.com/45708377/113100023-8347a580-9203-11eb-916b-9e21693b1cc9.png)
After this fix StrangeLoopGames/Eco#8179 it should be fixed too. 
If there is any warning with occupancy, then we need to create an issue

**Comment by SlayksWood** [comment]
Industrial elevator was fixed. Door occupancy still exist. Open a new issue #21218
