### ISSUE TITLE
[Web sandbox] Links for downloading the game in "How to start playing" mail is wrong.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20895]
Register a new account, you have message:
![image](https://user-images.githubusercontent.com/45708377/110781638-35302980-8277-11eb-9189-be1c93388bce.png)
but seems links for downloading were changed. 
Wrong link from mail: https://s3-us-west-2.amazonaws.com/eco-releases/EcoPC_v0.9.2.4-beta.zip
Link from account in prod: https://play.eco/s3/release/EcoPC_v0.9.2.4-beta.zip
Link from account in sandbox: https://sandbox.play.eco/s3/eco-releases/EcoPC_v0.9.2.4-beta.zip

**Comment by SlayksWood** [comment]
and change totorials in Youtuve link to https://www.youtube.com/results?search_query=eco+game+tutorial

**Comment by denysaw** [comment]
Done on sandbox.
