### ISSUE TITLE
[Web Sandbox] White links on white background

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20896]
Step to reproduce:
- select white theme.
- go to archived downloads:
![image](https://user-images.githubusercontent.com/45708377/110788313-83e1c180-827f-11eb-8c69-e3d6ed337cff.png)
- expand any version:
![image](https://user-images.githubusercontent.com/45708377/110788445-ab388e80-827f-11eb-9f85-b118223af698.png)
- in dark theme works fine:
![image](https://user-images.githubusercontent.com/45708377/110788847-33b72f00-8280-11eb-8f4f-6881b63e5efe.png)

**Comment by j3fffff** [comment]
on staging
