### ISSUE TITLE
[0.9.3 staging-1952] Notifications is behind the Drill UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20909]
regression,can check on regress here: #13641.
Step to reproduce:
- /work until you don't have any calories
- /give Modern rock drill, select it and try to drill. You have notification that you don't have calories:
![image](https://user-images.githubusercontent.com/45708377/110902950-b808c100-8317-11eb-935a-0c9dde6252b1.png)
- /give tomato and eat it:
![image](https://user-images.githubusercontent.com/45708377/110903021-d53d8f80-8317-11eb-80e7-013cece0d203.png)
- drill until you will lost all calories. You should have notification, that you are hungry, but you don't have it. It is worth noting that you hear the sound of notifications appearing. So they are just hidden behind Drill UI: 
![image](https://user-images.githubusercontent.com/45708377/110903191-1fbf0c00-8318-11eb-8050-0a7e98bd588b.png)

**Comment by Lyrcaxis** [comment]
@WeaselDog I had this fixed in https://github.com/StrangeLoopGames/Eco/pull/8053 (for develop) before being assigned this issue. 
Fixing it for staging will probably leave conflicts when merging to develop. What should I do?

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 251
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/6e8b05d4-388f-413b-ac46-7931d32fa9ab)
