### ISSUE TITLE
[0.9.3 Staging-1951]Civics: Able to pass empty Law

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20900]
Build: 0.9.3 Staging-1951

### Issue
Able to pass, enact, execute a Law that does not contain any section. An empty law.

Repro:
1. Interact with Court.
2. Draft a law.
3. Remove all sections.
4. Submit or Execute with Executive order.

Expected result:
The CIVICS Court Law UI should inform the player that he/she cannot submit an empty law if the player tries to do so.

Actual Result:
Court Law UI allows it and the empty law can be executed.

Screenshot:
![empty law.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/adaa0032-15ee-47f6-a84a-0bdd1146686a)

**Comment by WeaselDog** [comment]
This is actually intended behavior to allow laws that do nothing but enact server policy.
