### ISSUE TITLE
[0.9.3.0 beta staging-1951]Claim papers no longer merging stacks

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20906]
If you have 2 individual stacks of land claim papers these will not merge.

So for example, learn skill - gain 5 claim papers.
Place claim papers in a chest, now learn another skill and try to place them in the same stack.

(Can also just split a stack and they will not merge back)

**Comment by SlayksWood** [comment]
Still an issue.

**Comment by SlayksWood** [comment]
fixed in 0.9.3 release-186
