### ISSUE TITLE
Develop in unity with lags even at local server

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#20904]
Repro steps: /give campfire and try to put it and pick up it. 

https://user-images.githubusercontent.com/53317567/110850556-ac24ec80-828e-11eb-94c3-ac5243fe796b.mp4

**Comment by IronyTroll** [comment]
Is this an issue with the campfire or the admin hammer?

Have you tried this using /give Iron Hammer

**Comment by gzatravkin** [comment]
> Is this an issue with the campfire or the admin hammer?
> 
> Have you tried this using /give Iron Hammer

No, it happens with anything. Open campfire, open economy viewer, eat something etc
