### ISSUE TITLE
Out Of Memory , while starting Server for the first Time

### ISSUE THREAD

**Issue by luccajaeger** [StrangeLoopGames/EcoIssues#20916]
Hi, im experiencing an OOM, when I try to start my ECO-Gameserver on a Linux Server.
OS: Ubuntu 18.04.5 LTS
64bit architecture .
Free Memory 48 GB, 
12 Cores.

All dependencies updated and complete.
Freshly clean Installed and validated serverfiles.

Any suggestions what i need to swap. to get that running?

Best Regards 
Lucca

DUMP log:
[ServerCrash OutOfMemoryException 03122108.log](https://github.com/StrangeLoopGames/EcoIssues/files/6131056/ServerCrash.OutOfMemoryException.03122108.log)

**Comment by mirasrael** [comment]
Hi. Can you attach your save and configs?

**Comment by luccajaeger** [comment]
Hi, do you want all config files? and i dont get the server started so i dont have a save.

**Comment by mirasrael** [comment]
Yes, all config files. You can exclude Users.eco and Network.eco because they may contain info you don't like to share. Also please attach screenshot of your Storage and Configs directories content.

**Comment by mirasrael** [comment]
Most interesting is WorldGenerator.eco, because I assume it may have huge world dimension.

**Comment by luccajaeger** [comment]
[Disasters.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165235/Disasters.eco.template.txt)
[EcoSim.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165236/EcoSim.eco.template.txt)
[Localization.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165237/Localization.eco.template.txt)
[ModKit.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165238/ModKit.eco.template.txt)
[Network.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165239/Network.eco.template.txt)
[Pause.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165240/Pause.eco.template.txt)
[Profanity.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165241/Profanity.eco.template.txt)
[Rooms.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165242/Rooms.eco.template.txt)
[Sleep.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165243/Sleep.eco.template.txt)
[Stats.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165244/Stats.eco.template.txt)
[Storage.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165245/Storage.eco.template.txt)
[Voice.eco.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165246/Voice.eco.txt)
[World.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165247/World.eco.template.txt)
[WorldGenerator.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165248/WorldGenerator.eco.template.txt)
[WorldGenerator.eco.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165249/WorldGenerator.eco.txt)
[WorldObjects.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165250/WorldObjects.eco.template.txt)
[Backup.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165251/Backup.eco.template.txt)
[Civics.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165252/Civics.eco.template.txt)
[Difficulty.eco.template.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6165253/Difficulty.eco.template.txt)
![Config](https://user-images.githubusercontent.com/19946252/111651461-89eb1b80-8806-11eb-9a0c-07a0e429bcf4.jpg)
![Storage](https://user-images.githubusercontent.com/19946252/111651669-b99a2380-8806-11eb-8295-ef673e9effca.JPG)

**Comment by mirasrael** [comment]
I checked config files. Everything seems fine. If you copy all configs to Windows and start server then will it work for you? Can you put full log (not just crash) and also may be video/screens with memory usage dynamic when server started.

**Comment by IcedForge** [comment]
Will close as there were no reply, please reopen and add the above mentioned requested information.
