### ISSUE TITLE
[0.9.3 staging-1952] Infinity tool animation in 3rd person view.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20913]
Just use any tool 1 time and you have animation all time.

**Comment by SlayksWood** [comment]
> Viewing character in third person view while holding a tool while cause character to animate work related to said tool (mining if holding pickaxe, chopping if holding axe, shoveling while holding a shovel, etc..)
> 
> example
> https://gyazo.com/7585a6661d22b4d53bd73fbb485a15a2
> 
> Reproduce :
> 
> 1. Hold any tool
> 2. Change view to third person
> 3. Observe

**Comment by Lyrcaxis** [comment]
I believe this is fixed. A different issue remains when equipping Drills now.
![image](https://user-images.githubusercontent.com/32474602/112665672-fcda3f00-8e63-11eb-94a4-b33e7f084845.png)
