### ISSUE TITLE
Ignore Blocktier

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20912]
There should be the possibility that certain blocks are not included in the calculation of rooms.

![grafik](https://user-images.githubusercontent.com/37456949/110908738-88ee5180-830f-11eb-84c1-6dce76143e26.png)

Like this you could build a T4 House and would not be pulled down from the Tier of the curtains. They should have no Tier and not be calculated in Roomvalue
Same with the Pipes which currently use Tier 1 & 2

**Comment by WeaselDog** [comment]
Converted to https://github.com/StrangeLoopGames/Eco/issues/8340
