### ISSUE TITLE
[0.9.3.0 beta staging-1952]Sweeping hands no longer picking debris in radius all the time

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20917]
Sweeping hands perk for mining to pickup all rubble in range no longer properly picking up in radius, it detects incorrectly.

Reproduction - 
Have mining level 6+ pick sweeping hands. Mine a bunch of rocks and try picking them up, sometimes it ignores rubble im even touching.

**Comment by IcedForge** [comment]
It is also picking up "Chunks" as well, if you have 2 rubble + 1 yellow non broken chunk rubble ( 4 ore in total ) it will pickup all 3 pieces but you will only have 3 in your hand.

Correct behavior should be not picking up yellow chunks.

**Comment by IcedForge** [comment]
https://i.gyazo.com/275e5e6cfdce52832a00ce20b5b68442.mp4

It is also ignoring rubble type, and just collecting everything it can regardless

**Comment by Quadbro** [comment]
Fixed proper rubble pickup, but nearest plots will be fixed after some auth refactors. Reasons are described in comments of https://github.com/StrangeLoopGames/Eco/pull/8091

**Comment by IcedForge** [comment]
Reopening this as it is still ignoring rubble type
So if i have 5 Limestone, 5 Sandstone, 10 Iron ore and i pick iron ore it will take all other types and give me 20 iron ore.
Same if i pick the limestone i will get 20 limestone as per the video showing limestone/sandstone transmutation.
