### ISSUE TITLE
USER ISSUE: Industrie Fahrstuhl

### ISSUE THREAD

**Issue by Silverstone37** [StrangeLoopGames/EcoIssues#20928]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**
Fährt durchgehend bis runter

**Actual behavior:**
Stockt mitten in der fahrt obwohl nichts im weg ist
(Lehmziegelwand ringsrum)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
hi @Silverstone37 thank you for your report

can you share a video of this happening for us to reproduce your issue to find its cause?

as of now, I have tested this and doesnt seems to have any issue with it.

**Comment by Silverstone37** [comment]
Entschuldigung da weis ich nicht wie ich das machen soll :(

**Comment by TwixterZ** [comment]
@Silverstone37 Have you tried putting the elevator at different location? if you have, is it working?

**Comment by IcedForge** [comment]
Will close this as a duplicate you can follow the investigation at #18809
