### ISSUE TITLE
USER ISSUE: Can't turn camera

### ISSUE THREAD

**Issue by kkoivistoinen** [StrangeLoopGames/EcoIssues#20937]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Start the game and try to move camera

**Expected behavior:**
I could look around...now can only walk forward that the moment. 

**Actual behavior:**
When I move my mouse, cant move camera

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @kkoivistoinen, thank you for making a report about this.
We recommend checking the in-game setting for the mouse sensitivity. To do so, please press **Esc key** inside the game and proceed to the **Controls** tab. Look for Mouse Sensitivity and make sure it's set to 5.00.

If this doesn't fix the issue, please let us know and provide us with a recorded video as the issue happens.

Thank you.

**Comment by karlthepagan** [comment]
When playing on a PC with a touchpad I experience this behavior.

**Comment by kkoivistoinen** [comment]
Thanks,

Mouse sensitivity was the issue.

Kari

su 14. maalisk. 2021 klo 18.58 Daniel Moises Dizon Magulado (
***@***.***) kirjoitti:

**Comment by Daniel-Magulado** [comment]
Hi @kkoivistoinen,

We're glad that we could be of help.
Let me know if there's anything else we could assist you with.
Regarding this issue, we're currently aware of it and a fix is on its way in the coming game updates.

Thank you and enjoy playing Eco.

#20244
