### ISSUE TITLE
USER ISSUE: Mouse movement does not move the camera

### ISSUE THREAD

**Issue by arnemertz** [StrangeLoopGames/EcoIssues#20935]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Log into the game for the very first time I get the "Setting up Camp" quest. Try to move the camera with the mouse.

**Expected behavior:**
The camera should move when I move the mouse.

**Actual behavior:**
Moving the mouse results in a tiny wiggle of the camera, that's it.
I can move around with WASD, but I can not move the camera with the mouse. I can press tab to move the cursor with the mouse, but I can not move the camera. Changing controls to use keys to move the camera works (with slow camera movements) but that's tedious to play.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, fresh installation via steam.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by arnemertz** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6136736/Player.log)

**Comment by arnemertz** [comment]
Update: the mouse _soes_ move the camera, but very litte. I need to move the mouse roughly 3m to get a ~90 degree rotation. I need to move it slowly, or the rotation goes backwards.

**Comment by arnemertz** [comment]
seems something had reset the mouse sensitivity to 0.01 - maybe during installation.

**Comment by Daniel-Magulado** [comment]
Hi @arnemertz, thank you for making a report about this. We apologize if we couldn't get to you soonest. We also apologize for any inconvenience that this might have caused.
We're currently aware of this issue which you can learn more about here https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/20244 and a fix is already on its way in the coming updates.

**Comment by arnemertz** [comment]
Thanks for getting back to me. I can't open the issue on zenhub as it needlessly wants me to grant access to my private data and repositories.
