### ISSUE TITLE
Add virtual language to see what strings are added to translations

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#20934]
Standard in-game brackets `[ ]` would show us, that string is translated:
![image](https://user-images.githubusercontent.com/5720101/111212542-00520880-85d0-11eb-9e6e-0a5f831ac6df.png)

Add flag of SLG to a flag list on Sandbox. Don't add onProd.

**Comment by StallEF** [comment]
@denysaw  add new lang 'gibberish' with SLG logo on flag as an option just

**Comment by denysaw** [comment]
Replaced degree symbol with a standard in-game brackets `[ ]`:
![image](https://user-images.githubusercontent.com/5720101/111212464-e9abb180-85cf-11eb-8020-c3514abd6756.png)

**Comment by denysaw** [comment]
> 
> 
> @denysaw add new lang 'gibberish' with SLG logo on flag as an option just

Nice idea =) Changed Gibraltar flag to SLG logo. But if someone would give me same size/aspectRatio as the other flags, I will be glad to replace it ;)
