### ISSUE TITLE
My computer died midgame and now I'm unable to load a local server

### ISSUE THREAD

**Issue by johnpbushiii** [StrangeLoopGames/EcoIssues#20941]
I was playing in a local server and my computer died. When I plugged it back in and went to load the server, it will not load. It will load other servers, but not that one. That was my first server and losing it is very upsetting.

**Comment by TwixterZ** [comment]
hi @johnpbushiii, thank you for rising this up to us, 

kindly clarify, when you say server will not load is there any error message?

**Comment by IcedForge** [comment]
Will close as there were never a reply with requested information.
Please reopen if you still have this problem with the related information.
