### ISSUE TITLE
Inventory system can't recover from this bad state

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2094]
I've got a kiln with a stack of 23 coal in it's power supply.  In FuelSupplyComponent.LoadFuel, an exception is thrown (because it's calling Modify and not TryModify) when it tries to remove one.  In this case, it should probably call the change set valid, since the diff is more valid than the previous state.

**Comment by Fank** [comment]
Related to #2085 ?

**Comment by MarjieAVolk** [comment]
Hm interesting thought, that could be.  Did you have a stack that was bigger than the intended limit when you saw that exception?

**Comment by Fank** [comment]
I were disconnected from the server and a popup opened only with that error, i copy pasted in the issue thats all.

**Comment by Fank** [comment]
About the stack i got, i don't know, it could be larger than normal. i know that something weird happend due the kiln building.

**Comment by MarjieAVolk** [comment]
Oh wait, yours is a null ref, nah that's not the same exception after all
