### ISSUE TITLE
[0.9.2.4]Harvesting Plants with a shovel does not give Gathering XP

### ISSUE THREAD

**Issue by a-nop** [StrangeLoopGames/EcoIssues#20940]
When harvesting Taro plants with a shovel, the player does not gain any XP.

The expectation is that harvesting Taro plants with a shovel gives Gathering XP.

To reproduce, harvest a Taro plant with a shovel.  Calories are burned, but no XP is gained.

**Comment by TwixterZ** [comment]
@a-nop  Thank you for reporting this, I can confirm this is an issue and will get our developer to have a look.

**Comment by TwixterZ** [comment]
tested on 9.4 Develop 251 on Taro and Camas, still no exp gained whether gathering skill is learned or not.

**Comment by WeaselDog** [comment]
Please retest in next build

**Comment by TwixterZ** [comment]
tested on 9.4 Develop 257 on Taro and Camas, no exp gained from gathering camas.

however, exp is gained from gathering Taro.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 257
