### ISSUE TITLE
USER ISSUE: local server will not load

### ISSUE THREAD

**Issue by johnpbushiii** [StrangeLoopGames/EcoIssues#20942]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
i was playing on my local server and my computer died. when i plugged my laptop back in and tried loading the server, it will not load. it will load other servers but not my local server. 

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
@johnpbushiii Thank you for reporting, unfortunately there is little we can do to assist unless we get your playerlogs and server logs as described in the link in the template ( and in your post ).

**Comment by IcedForge** [comment]
Closing this as there were never a reply after initial contact.
