### ISSUE TITLE
[0.9.2.4 veta release-156]Mortared fireplaces missing firewood texture

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20948]
Mortared fireplaces still missing firewood texture on staging.
Ashlar fireplaces are fixed and looks good.

![Screenshot_46](https://user-images.githubusercontent.com/24981362/111161996-fe6e5200-859b-11eb-904e-836a167ff6df.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1955

Mortared fireplace of each model now has firewood texture present on the said build.

https://images.zenhubusercontent.com/47210472/9abded48-0690-4b6f-b521-c4663815c86b/2021_03_17_12_01.mp4

Closing.
