### ISSUE TITLE
[0.9.3 staging-1954] Failed to handle RPC method: Attach

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20945]
same thing happens when trying to shoot an animal within property.

![image](https://user-images.githubusercontent.com/78054747/110758648-b42d5e00-8287-11eb-928d-41b73cad6456.png)

_Originally posted by @TwixterZ in https://github.com/StrangeLoopGames/EcoIssues/issues/20758#issuecomment-796565489_

**Comment by SlayksWood** [comment]
>@abaza121 we have performed more test today, ultimately we are unable to consistently reproduce this error 100% of the time, 

I'd say that this is not hard to reproduce it. But we can';t reproduce it with 100%. Basic things: 2 client, shooting and reconnection. So it will be easy to reproduce. During 20 minutes testing we got it at least 5 times.
@abaza121 So I will assign you to this, you can ask any of QA to help you to reproduce it while you debug it

**Comment by SlayksWood** [comment]
But we will try to find the reason too.

**Comment by abaza121** [comment]
@SlayksWood I found a way to reproduce it, it seems to be related to having lag between the client and the server that is why I wasn't able to reproduce but I got a way to reproduce it I will do a PR for it today.
