### ISSUE TITLE
[0.9.3 staging-1954] Missing notification "The roots are too strong" in Skid Steer and Excavator.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20943]
Try to dig near tree:
![image](https://user-images.githubusercontent.com/45708377/111117097-1502b200-8578-11eb-9685-c63a117295a7.png)
You can't, but you don't have any notifications why. Should be:
![image](https://user-images.githubusercontent.com/45708377/111117134-2946af00-8578-11eb-904e-eddc1640318b.png)
like with shovel.

**Comment by Quadbro** [comment]
Vehicles are using different Dig request method, so you need to check there

**Comment by MazonDel** [comment]
We may want to discuss if big industrial equipment like the excavator and skidsteer should maybe be able to destroy non-Old Growth Redwood trees. Like, instantly trigger the FellTree code but also destroy the stump.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-267.

Now has an error message.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/fc9626dd-38dd-497c-abe4-b0f7fc8437e2)

Closing.
