### ISSUE TITLE
Logging Skill Lvl 6 - Calories Lost

### ISSUE THREAD

**Issue by AxiomaticCloud** [StrangeLoopGames/EcoIssues#20959]
When you choose the Specialty under logging for level 6. It states you will not lose calories when you clean up debris. 

You still lose calories when cleaning up debris and stumps.

**Comment by TwixterZ** [comment]
@AxiomaticCloud thank you for your report,
Merged to [#20184](https://github.com/StrangeLoopGames/EcoIssues/issues/20184)
