### ISSUE TITLE
Ability to trade p2p

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2095]
We need an ability to trade player to player, maybe by dropping items or open a local trading window

**Comment by johnkslg** [comment]
Agreed. pushing to beta though

**Comment by ClayC90** [comment]
Will a command do for the time being ?

**Comment by MarjieAVolk** [comment]
That sounds like it would enable instantaneous transit around the world.

**Comment by ClayC90** [comment]
@MarjieAVolk I agree, but maybe we can have trades be active for as long players are close to eachother, similar to how the cart is linking to storage chests and stock piles?

**Comment by MarjieAVolk** [comment]
Guess a chat command could check distance too

**Comment by D3nnis3n** [comment]
Dropping items is now possible, should suffice.
