### ISSUE TITLE
Migrations for some changed stats

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20954]
With the World Progress PR, the names of some statistics were changed.  We will need to add support to our stat database to allow this.  Additionally since these values are serialized, we'll need to set them up in the regular migration system too.

The stats changed were:
```
    //TemperatureDelta -> TemperatureTotalDelta
    //TemperatureChange -> TemperatureDayDelta
    //SeaLevelChange -> SeaLevelDayDelta
    //Past24HoursCO2ppmDelta => CO2DayDelta
```

**Comment by WeaselDog** [comment]
Ask @mirasrael for help on this one if needed.
