### ISSUE TITLE
[0.9.2.4 beta release-156] Vehicle deeds can be claimed by anyone

### ISSUE THREAD

**Issue by devolore** [StrangeLoopGames/EcoIssues#20950]
Any player is able to claim ownership of any vehicle without needing prior authorization or admin privileges.

Reproduction steps:
- Look at the vehicle so that the name badge appears at the top of the screen
- Activate cursor with Tab, shift-click the vehicle name, this opens the deed
- Click the cogwheel next to the owner's name
- You can change the owner to anyone

**Comment by WeaselDog** [comment]
Thank you for reporting this. We are currently working on a hotfix for this one which should be out soon.

**Comment by SlayksWood** [comment]
Seems fixed, need another check after fixing this one #21138

**Comment by SlayksWood** [comment]
fixed in 0.9.3
