### ISSUE TITLE
[0.9.3 staging-1955] Renter can steal Landlord objects.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20967]
Step to reproduce:
- Landlord place some furniture:
![image](https://user-images.githubusercontent.com/45708377/111287561-64b6ab80-8654-11eb-93c5-dce0a5c2cde1.png)
- landlord invite renter to residency:
![image](https://user-images.githubusercontent.com/45708377/111287714-89ab1e80-8654-11eb-95ab-59031af1b0b1.png)
- renter become resident:
![image](https://user-images.githubusercontent.com/45708377/111287770-992a6780-8654-11eb-9230-cad9ee9d94f3.png)
- take modern hammer and pick up all things:
![image](https://user-images.githubusercontent.com/45708377/111287892-b7906300-8654-11eb-8e8c-a77f0baa14c9.png)
- also can steal items from storages:
![image](https://user-images.githubusercontent.com/45708377/111287947-c6771580-8654-11eb-92c6-0296d040fc39.png)

**Comment by johnkslg** [comment]
They shouldnt be able to pickup stuff, that should be fixed
But using contents should be permitted, so they can use the objects.
(ie, if my landlord leaves a fridge full of food i'm gonna eat it)

**Comment by IcedForge** [comment]
As per johns comment regarding content of storages, and its behavior it looks pretty good.
