### ISSUE TITLE
Add more information to generated mod files

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#20969]
We can help modders by adding some more documentation to the generated files

Adding named parameters would help modders understand what the parameters are:
```cs
this.GetComponent<MinimapComponent>().Initialize(category: Localizer.DoStr("Crafting"));
```

Also adding some comments around the various components to explain what they do would be good too

**Comment by WeaselDog** [comment]
ClickUp ID: ECO-12492
