### ISSUE TITLE
Refine Ocean Spray Destroy Effect

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20966]
The ocean spray destruction does a weird pirouette that causes some reported users with nausea and should behave like all other brush

https://i.gyazo.com/c7a7e59864575a6827ebaedf95d23383.mp4

**Comment by z-73** [comment]
![OceabnSray.gif](https://images.zenhubusercontent.com/60a3593a199750a6f2fe297d/8e32868e-1b81-41b6-a5ef-46b80647ca64)

**Comment by z-73** [comment]
Checked into staging on SVN

**Comment by keegan-o** [comment]
Thanks!
