### ISSUE TITLE
Alpha.6 [Cc778b68] Laggs when walking dirtramps upstairs

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2096]
Our game file: http://fankservercdn.com/spectrum/Game.eco
Location:
![image](https://user-images.githubusercontent.com/1900106/30390679-3670a5ac-98b7-11e7-9497-912d7ba4e45a.png)

Walking down without issues, but walking up causes laggs.

**Comment by SeanAtr0n** [comment]
Pretty sure this is fixed
