### ISSUE TITLE
USER ISSUE: Connection Failure

### ISSUE THREAD

**Issue by TomHaycraft** [StrangeLoopGames/EcoIssues#20972]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Try joining server on top menu or in your world menu

**Expected behavior:**
Joined server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>No such host is known. No such host is known.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@TomHaycraft thank you for your report,

have you tried connecting to a server via IP directly instead?

**Comment by Daniel-Magulado** [comment]
Closing due to lack of reponse.
