### ISSUE TITLE
Eco tree, header images are pointing to old url.

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20974]
setup redirect or manually fix all old header image urls

for example, they are pointing to
https://api.strangeloopgames.com/wp-content/uploads/2019/11/WorldSimulation.png
but should be https://wp.play.eco/wp-content/uploads/2019/11/WorldSimulation.png

Need redirect like this api.strangeloopgames.com/wp-content/uploads/* goes to 
wp-.play.eco/wp-content/uploads/*

**Comment by denysaw** [comment]
Solved (via replace in DB, cuzz every redirect is a minus for SEO).
