### ISSUE TITLE
[0.9.3 Staging-1955] Fishing Pole broken on staging

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20977]
Build: 0.9.3 Staging-1955

### Issue
Unable to use the Fishing Pole on the said build. Clicking LMB or RMB doesn't do anything. Setting up secondary key bindings doesn't work.

Repro:
1. Get Fishing Pole.
2. Try to fish.

Actual Result:
Unable to use Fishing Pole.

Expected Result:
A working fishing pole.

**Comment by WeaselDog** [comment]
Fixed via SVN

**Comment by Daniel-Magulado** [comment]
Fixed on 9.3 Staging 1958. Closing
