### ISSUE TITLE
Alpha.6 [Cc778b68] Huge lag when linking storage (enable/disable)

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2097]
Client side only.
same map as in #2096

**Comment by MarjieAVolk** [comment]
I tried this on your save, and I'm not having any problems with it.  Mysterious.  Could this also be an operating system thing?

**Comment by Fank** [comment]
Im using linux client os, you?

Am 14.09.2017 9:36 nachm. schrieb "MarjieAVolk" <notifications@github.com>:

**Comment by SeanAtr0n** [comment]
There are changes in master that should make linked storage UI perform better, especially when reopening

**Comment by MarjieAVolk** [comment]
I don't think this is related to initialization, if that's what you mean - they're talking about checking/unchecking the link check boxes

**Comment by Fank** [comment]
Marjie do we may can contact faster, slack, discord or something else?

**Comment by MarjieAVolk** [comment]
Sure, ping me on discord if you like, I'm Marjie there too

**Comment by SeanAtr0n** [comment]
If UpdateLinked gets called when priority/linkedness changes then my change would make a difference there

**Comment by MarjieAVolk** [comment]
I haven't been able to repro this at all.  Is this still happening?

**Comment by Fank** [comment]
Will validate with next staging version

**Comment by Fank** [comment]
Fixed in latest staging thanks
