### ISSUE TITLE
Alpha.6 [Cc778b68] Items could not be repaired

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2098]
If i collected then after completed they are still at the same values (totaly damaged).
Linux mono server only.

**Comment by MarjieAVolk** [comment]
This should be fixed in the next staging release

**Comment by Fank** [comment]
This is only affected by mono server, current windows server version is fine

**Comment by MarjieAVolk** [comment]
That's weird, because I don't think it's fixed in the current staging build?

**Comment by Fank** [comment]
Cc778b68 server eco.fankserver.com working fine running on windows 2016 with .net 3.5 and 4.5

**Comment by MarjieAVolk** [comment]
Okay, I could be mistaken about the state of the bug, guess we'll take another look

**Comment by D3nnis3n** [comment]
No longer happening.
