### ISSUE TITLE
[Accounts] Clicking Complete Order brings up a redundant notification

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#20988]
Reproduce:
1. Select any Eco tier to buy either logged in or not
2. Finish the Paypal process
3. Click on Complete Order

![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/a07421bc-6fbe-4b56-a159-a53973f74c65)

**Comment by denysaw** [comment]
@Ry4ndrew Fixed on Sandbox, please test there ;)

**Comment by Ry4ndrew** [comment]
Retested and fixed. Thanks.
