### ISSUE TITLE
[0.9.3 Staging-1955]Blurred screen after closing UI when account tooltip is clicked

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20982]
Build: 0.9.3 Staging-1955

### Issue
If you open a UI with an available *Credit* tab such as Workbench or Store table, clicking the tooltip popping up on any account when hovering the mouse icon on an account under the Credit tab causes the screen to be blurred once the UI is closed via the X button.

Repro:
1. Interact with a table that has a Credit tab such as Workbench or Store.
2. Proceed to the Credit tab and hover the mouse icon over any account with the orange text color.
3. Once the ToolTip pops up, click anywhere on the ToolTip box and close the UI by clicking the X button.
4. Observe.

Video Repro:
https://images.zenhubusercontent.com/47210472/fe7e2f08-ada0-43ac-b709-611c1780b6c0/2021_03_18_05_43.mp4

**Comment by madpingui** [comment]
Tested on Develop unity editor
![Blur.gif](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/ba14ef42-cfd4-4fb0-af50-e7f595e392f4)

**Comment by Daniel-Magulado** [comment]
Unable to reproduce on 0.9.4 Develop-251.

However, I can still reproduce on 0.9.3 Release-189.

Video:
https://images.zenhubusercontent.com/47210472/437d5d21-cf21-44ef-91e1-0431722f46e7/2021_04_14_00_23_trim.mp4
