### ISSUE TITLE
User using invite doesn't get icons

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#20992]
Tested not working for normal tier 4 beta invite.
![image](https://user-images.githubusercontent.com/25908592/111636044-691bc980-87f8-11eb-9589-335784ff6b7c.png)

**Comment by D3nnis3n** [comment]
This seems to be working given yesterdays tests. @denysaw If you can confirm that, please close it.

**Comment by denysaw** [comment]
Yeah, retested on Sandbox, everything's fine.
