### ISSUE TITLE
USER ISSUE: Text on Tutorial

### ISSUE THREAD

**Issue by mrmcmerrill** [StrangeLoopGames/EcoIssues#20997]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Click on any tutorial objective on the left side of the screen.

**Expected behavior:**
It should be readable and fit on screen.

**Actual behavior:**
Over extends passed the usable space on screen.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed. But my resolution is 2560:1080

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![image](https://user-images.githubusercontent.com/31187579/111715735-dfd1ba80-882a-11eb-91ed-60ffe755c18c.png)

**Comment by SlayksWood** [comment]
@mrmcmerrill Thank you for the report.
dup #20252
