### ISSUE TITLE
USER ISSUE: Door into Objects

### ISSUE THREAD

**Issue by cachemiss000** [StrangeLoopGames/EcoIssues#21002]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Create a house
2. The door swings into a wall, perpendicular to it (e.g. it opens into a narrow hallway
3. Open the door when standing near it

**Expected behavior:**
Moved me back or something

**Actual behavior:**
Moved me into the wall, and now I can't get out

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@cachemiss000 thank you for reporting this.

Able to reproduce this issue by opening door in a small corridor while moving forward towards the door.

https://gyazo.com/81c00e5ae8b27de261c1e2efbef9706d
