### ISSUE TITLE
[0.9.3 staging-1959] Hint issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21007]
- [x] 1. Mouse is too big:
![image](https://user-images.githubusercontent.com/45708377/111761073-84e2a680-88b0-11eb-81de-1c324a96deae.png)

- [x] 2. Q/R buttons beacame smaller:
![image](https://user-images.githubusercontent.com/45708377/111761144-9c219400-88b0-11eb-9e3b-dffac6b7323e.png)

**Comment by SlayksWood** [comment]
ALso was broken buttons in vehicles:
![image](https://user-images.githubusercontent.com/45708377/111947734-14759880-8aef-11eb-8524-f9bf873e1246.png)

**Comment by johnkslg** [comment]
yes this looks very bad and should never have been submitted.

**Comment by Quadbro** [comment]
Actuall estimates were planned if there will be a discussion on sprites with art team and so on. But a few prefab tweaks were able to fix all the issues without any hardcoded variables in code

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1966

- Mouse Icon being too large fixed.
- Q and R button for rotate rescaled.
- Excavator button issues fixed.


Resolution: Closing.
