### ISSUE TITLE
Multi-Winner Ranked Choice Vote selects incorrect runners-up [Giant Panda "senate" election]

### ISSUE THREAD

**Issue by karlthepagan** [StrangeLoopGames/EcoIssues#21003]
We have an office "Wise Panda" with maximum of 5 seats available.

The web view of the results indicates a single winner, but this view indicates that the RCV continued until there was a single plurality winner and a tie for the 2nd place:
![single winner - schack](https://user-images.githubusercontent.com/308745/111734705-d3079380-8837-11eb-8717-8763174018e6.PNG)

The specification for Ranked Choice Voting (via single transferable vote) indicates that the voting rounds should halt as soon as there is a number of winners equal to or fewer than the open office seats. https://www.fairvote.org/multi_winner_rcv_example

In the case of allowing an election with the office occupied this feature offers an inconsistency to the players. If the election will complete before the end of the term then the most senior office holder should be replaced in order to allow all winning candidates to assume the office. Thus in order to create a predictable rotating roster of office holders the vote to induct new senators might be restricted to a maximum number of winners. This could be an attribute of the Elected Title "Maximum Winners Per Election" which could be integrated into the solution for the multi-winner bug.

Inside the game client the results indicate that some kind of random selection from the candidates to office was performed after the winner was selected:
![election result](https://user-images.githubusercontent.com/308745/111735509-5ecdef80-8839-11eb-94e9-6363a04fb14f.PNG)

**Comment by karlthepagan** [comment]
Possible alternative explanations:
* because Boroghor and myself were tied one of the tying players might be randomly selected. In this case neither tied player won.
* the election proceeded to round 3 (the first election round which fits the open offices without overflow), and instead of the runners-up being inducted the eliminated candidates were inducted.

**Comment by D3nnis3n** [comment]
Ties lead to noone of them being elected in elections for only one office position, so this might be very well part of this issue.

**Comment by karlthepagan** [comment]
> Ties lead to noone of them being elected in elections for only one office position

In this possible case k0mixus is also a potential winner as of round 3.

**Comment by IcedForge** [comment]
After discussing with Tu and Sergey we came to the conclusion that the best way to solve it and as per request by dennis as well is for Yes/No voting on laws, we keep the old logic but for multiOccupant elections it should dice roll on ties to prevent election mishaps but also solve potential multi seat titles from only accepting a few or skipping tied individuals.

**Comment by tuha263** [comment]
After investigating, I figured out that the election chose the winners from the bottom (except for the Highest vote candidate (Schack)). It doesn't relate to Tied.
