### ISSUE TITLE
[0.9.3.0 beta staging-1958] Third person view animation bug

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21004]
Viewing character in third person view while holding a tool while cause character to animate work related to said tool (mining if holding pickaxe, chopping if holding axe, shoveling while holding a shovel, etc..)

example
https://gyazo.com/7585a6661d22b4d53bd73fbb485a15a2

Reproduce :
1. Hold any tool
2. Change view to third person
3. Observe

**Comment by SlayksWood** [comment]
merged to #20913
