### ISSUE TITLE
[Accounts] Art Pack url 404 error 

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#21018]
@denysaw Art Pack url https://play.eco/s3/eco-public-files/ECO_ArtPack.pdf  show 404 error - Not Found

![2021-03-20](https://user-images.githubusercontent.com/26339332/111859547-b9a73a00-8952-11eb-9d2e-1fcf549178fd.png)

**Comment by Ry4ndrew** [comment]
Hi Stall, this issue has already been raised a week ago https://github.com/StrangeLoopGames/Eco/issues/8003, the devs have yet to look into it. But thanks for raising the issue.
