### ISSUE TITLE
Alpha.6 [Cc778b68] Optical glitches

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2101]
![image](https://user-images.githubusercontent.com/1900106/30397974-f1261c80-98ce-11e7-887a-59c82d3963e6.png)

**Comment by Fank** [comment]
Happend directly after placing, after some time it ok no glitch

**Comment by keegan-o** [comment]
Face remover stuff, not builder stuff. Or Chunk building stuff or something, so not something I can fix.

**Comment by metachronism** [comment]
fixed
