### ISSUE TITLE
[0.9.3 Staging-1960] Missing asset line peeking on Hunting Skills icon in Skill UI

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21021]
Build: 0.9.3 Staging-1960

### Issue
A missing asset line is peeking on the top of the hunting skill icon in the Skills UI.

![hunting.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8a59e5dc-34f2-4697-8e7c-c687c192d32a)

Repro:

1. Open Skills UI by pressing Z.
2. Proceed to Hunter Profession page.
3. Observe the hunting icon located above the hunting levels.

Note:

- Only happens on the Hunter Profession page.

**Comment by madpingui** [comment]
Fixed in develop branch, just update SVN 
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/e69a5b82-0040-439c-bc7d-b032e4aced89)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3.2 Release-212.

Fixed. Closing.

![image](https://user-images.githubusercontent.com/77248866/115724842-e2887800-a3b3-11eb-9349-741d259fb29b.png)
