### ISSUE TITLE
exception when subscribing on server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21035]
Got this when running /civics spawngov:
![image](https://user-images.githubusercontent.com/3536496/111896861-ac815e00-89d9-11eb-8eee-b6dbb4f9a506.png)

Must be a case of 'ss.Subscriptions' being a List but being accessed mutlithreaded

Maybe these two threads?
![image](https://user-images.githubusercontent.com/3536496/111896909-0550f680-89da-11eb-9f65-c56aa37b132a.png)

Other callstack:
![image](https://user-images.githubusercontent.com/3536496/111896913-0bdf6e00-89da-11eb-8cb0-fd91f76043a8.png)

**Comment by mirasrael** [comment]
No. These two threads non-related. Guess it happens in same method invoked in parallel thread. Nested subscriptions isn't thread safe.

**Comment by WeaselDog** [comment]
Closing as fixed
