### ISSUE TITLE
Just Another Yet Crash Tiger - DB related, transaction limit reached

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21031]
[log_210320031509.log](https://github.com/StrangeLoopGames/EcoIssues/files/6176579/log_210320031509.log)

**Comment by gzatravkin** [comment]
This PR may help with issue cause https://github.com/StrangeLoopGames/Eco/pull/8134 what you think @mirasrael ? Should it be switched to staging?

**Comment by mirasrael** [comment]
@gzatravkin if it happens often enough then it makes sense. Can you help QA with test plan to ensure everything tested and we won't introduce any regression into staging?

**Comment by SlayksWood** [comment]
closed as fixed.
