### ISSUE TITLE
Tooltip not working in laws

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21039]
![image](https://user-images.githubusercontent.com/3536496/111887910-728e6880-8995-11eb-98f0-6d22fb6e5bce.png)
Tooltip on 'citizen' failing here

**Comment by tuha263** [comment]
Seems we didn't implement tooltips for GameValueContext yet. I checked the release version and it doesn't have tooltip for GameValueContext neither.
