### ISSUE TITLE
Add bed

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2104]
e.g.:
- to lower calories need per skill points tick rate (for casual player)
- ?

**Comment by MarjieAVolk** [comment]
Thanks for the suggestion - we are actually planning something similar to this for beta: https://docs.google.com/document/d/1e3i7yyqzxFJQ3ZGkFV1SF0GShj_X7HjyTRaXJ20OEGg

Closing this for now, as we'll be tracking progress on this feature somewhere else
