### ISSUE TITLE
 [0.9.3 staging-1961] Excavator movement breaks on toggle dig mode

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21048]
When toggle out from dig mode you will not be able to move as its frozen in place as if its still inside a dig mode immobile state

Reproduction
1. Enter fueled excavator
2. toggle dig mode 
3. Switch to advanced mode then back to simple mode
4. toggle to Drive mode

**Comment by IcedForge** [comment]
If you toggle back into advanced mode and switch to driving you can do so without problems
But if you are in simple mode now and try to switch to drive, it will not be possible to move.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1966

Able to drive again after switching to advance and back to simple mode.
Also tested both modes and a mixture of modes changing to dig and drive.
All seems working.

Closing.
