### ISSUE TITLE
USER ISSUE: TP/BLOCKED

### ISSUE THREAD

**Issue by Daffal** [StrangeLoopGames/EcoIssues#21045]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Be between two blocks (upper/behind) place block on the player

**Expected behavior:**
Block cannot be placedPlayer die by suffocatingPlayer brock a bone and need medical assist(new gameplay possible that solve blocking situations)

**Actual behavior:**
Player tp on the first upper free place

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Daffal thank you for reporting this, however this is working as intended.

for suggestions you may create issues at following link https://github.com/StrangeLoopGames/EcoSuggestions
