### ISSUE TITLE
[Accounts] (Prod) Unable to download any of the builds from Staging - Beta 9.4.0 #1932

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21041]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/bc4e6dfa-5ed3-4751-a534-978f8e1f657b)

**Comment by SlayksWood** [comment]
#20669

**Comment by j3fffff** [comment]
@denysaw guessing this is from the new game download security?
suppose we should support testing game downloads on staging.
so when we get a chance lets update game security to work for staging too.
and can you send simon the staging query to call for updating staging game db listing?

**Comment by denysaw** [comment]
@j3fffff That's because we are still looking for staging builds on EU-central-1 and as I remember it's still empty. So this is actually the correct behavior. Not bug

**Comment by j3fffff** [comment]
@redwyre i though staging was going to eu now?
