### ISSUE TITLE
[0.9.3 staging-1961] Excavator controls bugs.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21042]
Bugs:
- [x] 1. Delete "Pick up items" in Excavator controls. Didn't report it in previous issue. 
You don't need to press LMB to pickup items with Excavator, but we have this in Controls:
![image](https://user-images.githubusercontent.com/45708377/111948082-a54c7400-8aef-11eb-8bbb-88174ba87214.png)
But be careful you need to press button when dig with Skid Steer.

- [x] 2. Buttons size is broken, but I guess that it related with #21007
Mouse wheel should look like mouse with highlighted wheel:
![image](https://user-images.githubusercontent.com/45708377/111948476-450a0200-8af0-11eb-9295-f74696b79b6d.png)
![image](https://user-images.githubusercontent.com/45708377/111948998-fd37aa80-8af0-11eb-8444-694ab25c3cbb.png)
and the mouse should be less.
WASD button is overlaped:
![image](https://user-images.githubusercontent.com/45708377/111948620-7edb0880-8af0-11eb-8fad-b7510043f2f7.png)

**Comment by Quadbro** [comment]
Icon sizes will be fixed by Marcus @SlayksWood

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1966.

Every issue has been addressed. Closing.
