### ISSUE TITLE
[Play.Eco] Art pack link 404

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#21051]
The link to the art pack on play.eco returns 404.
https://play.eco/s3/eco-public-files/ECO_ArtPack.pdf

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/21018

**Comment by TwixterZ** [comment]
@MonzUn thanks for reporting, I will close this issue as existing issue exist under [#8003](https://github.com/StrangeLoopGames/Eco/issues/8003)

**Comment by MonzUn** [comment]
I don't know why I didn't check for duplicates.
Sorry >.<
