### ISSUE TITLE
add white tiger and streamer icon to game

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21055]
![streamericon.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/f908fda8-b170-41d6-8378-dc215eaec56a)![tigericon.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/3fd9a066-3737-4d2f-900c-969cdf4423fb)

auth will return icon as `tigericon` and `steamericon`

**Comment by D3nnis3n** [comment]
I hope you mean streamericon, not steamericon :D

**Comment by ThePiachu** [comment]
> tigericon

"I survived on the hardest server" ;)

**Comment by D3nnis3n** [comment]
Is there info on when those will make it to the game?

**Comment by WeaselDog** [comment]
Both will be in 9.5 release
