### ISSUE TITLE
USER ISSUE: Tutorial Window View Width Very Small

### ISSUE THREAD

**Issue by ollowNC** [StrangeLoopGames/EcoIssues#21052]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Click on Tutorial
2. Click on one of the Tutorial Icons
	

**Expected behavior:**
The Tutorial window will expand wide enough to view the entire block of information / list or provide a scroll option	

**Actual behavior:**
A very long menu and list that has a very short width and expands past the bottom of the game display w/ no option to scroll.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Zero mods installed, just installed the game today.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ollowNC** [comment]
Image attachment 
![20210322_tutorial_view_stretched](https://user-images.githubusercontent.com/38573474/112035139-a395a700-8b15-11eb-93f1-3663b00cb920.jpg)

**Comment by ollowNC** [comment]
Tried the view reset in game
![20210322_tried_reset](https://user-images.githubusercontent.com/38573474/112035349-d5a70900-8b15-11eb-82c8-022ccd1fdefc.jpg)

**Comment by TwixterZ** [comment]
@ollowNC thank you for reporting this.

There is an existing report for this issue under [#20252](https://github.com/StrangeLoopGames/EcoIssues/issues/20252) 

as such I will close your issue, you may refer to above issue link to follow-up
