### ISSUE TITLE
USER ISSUE: Desert Road

### ISSUE THREAD

**Issue by tobruh** [StrangeLoopGames/EcoIssues#21057]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Stamp a road in the desert

**Expected behavior:**
It should stay as a road

**Actual behavior:**
Instead it disappears after a certain amount of time

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and no clue

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended, dirt roads in the desert need to be heavily used or will decay fast.
