### ISSUE TITLE
Alpha.6 [Cc778b68] Waterwheel produce energy out of nowhere

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2105]
This produces 200W
![image](https://user-images.githubusercontent.com/1900106/30402847-5e565f94-98df-11e7-9ab2-a4d86368c1a3.png)

**Comment by D3nnis3n** [comment]
Can also be placed so that the wheel is in the ground.

**Comment by IcedForge** [comment]
I would suggest just adding a water check the way fishtraps works and just offset the model to be "higher" then the placement point, so the detection tile / placement tile is placed in water but the animation / model is still above like intended.
