### ISSUE TITLE
[0.9.4.0-223] Beta Develop Missing Skybox

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21064]
As per title, skybox is missing in 9.4 world. 

World is freshly created 
https://gyazo.com/815f66265760699ae871539b7c935c68

**Comment by abaza121** [comment]
![image](https://user-images.githubusercontent.com/17747441/112117410-034a8b80-8bc4-11eb-82f4-da8e51182459.png)
Currently in develop this error happens on init and adding this null check fixes it 
![image](https://user-images.githubusercontent.com/17747441/112117488-18bfb580-8bc4-11eb-96cb-e2a001aac310.png)
it could be related
