### ISSUE TITLE
Alpha.6 [2ed68eec] Stuck on logging in

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2107]
Mac client used for the first time.
Normally i use linux, cant test it right know.

![image](https://user-images.githubusercontent.com/1900106/30406640-684c1318-98f3-11e7-8d63-21483b9ead38.png)

**Comment by Fank** [comment]
duplicate of #2107

**Comment by Fank** [comment]
Still stuck with latest staging build

**Comment by peternightingale** [comment]
I have this as well, with Alpha 6.0 released today. The gear just spins forever. I can get into the menu by hitting ESC, but it just never logs in.

**Comment by SeanAtr0n** [comment]
Still not sure whats going on here... bad login info gives the same behavior, no error msg

inputManager.eco was successfully created so it doesn't appear to be a filesystem issue

**Comment by SeanAtr0n** [comment]
Only useful data in the log file:
Trying to autoconnect but no login information stored in...
RPC lookup took....

then nothing unless you fiddle w/ escape menu

**Comment by SeanAtr0n** [comment]
Looks like it's a unity bug fixed in the next release, need to update build server to:
https://unity3d.com/unity/whats-new/unity-2017.1.2

**Comment by metachronism** [comment]
will be fixed in next staging
