### ISSUE TITLE
[0.9.2.4] Turning off Deeds doesn't refresh the map

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21071]
I recently tried figuring out how to turn off the ownership icons on the map (#21061). However, I wasn't able to find how to do it. Turns out, when you turn Deeds off in the map menu, the map doesn't refresh, so it appears as if that option is doing nothing until you rotate the map:

https://youtu.be/7VriyHo7_vA

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6193446/Player.log)

How to reproduce:

1. Go to map
2. Turn Deeds on - the ownership icons will appear
3. Turn Deeds off - nothing changes
4. Rotate map - ownership icons disappear

**Comment by SlayksWood** [comment]
@ThePiachu Thank your for the report. This is fixed in 9.3
