### ISSUE TITLE
Multi-person editing problems for Law's (and probably all other multi-editor cases)

### ISSUE THREAD

**Issue by tomsseisums** [StrangeLoopGames/EcoIssues#21077]
> [..] The editor should support multi-person editing.

_Originally posted by @johnkslg in https://github.com/StrangeLoopGames/Eco/pull/8050#discussion_r593805995_

I checked for some edge cases on Law multi-person editing, and found:

- [ ] Server Crash scenario
    1. _User 1:_ Create a draft for a Law
    2. _User 2:_ Open the said draft for Editing
    3. _User 1:_ Remove the draft
        - _User 2:_ The draft still remains open for Editing (possibly a problem on it's own, and the editor should be closed if the editable entry gets removed - needs discussion)
    5. _User 2:_ Edit Trigger - the server will crash
- [ ] It is possible to send a removed draft entry for election
    1. _User 1:_ Create a draft for a Law
    2. _User 2:_ Open the said draft for Editing
    3. _User 1:_ Remove the draft
    4. _User 2:_ Submit the draft for election (this will pass, starting an election for a removed draft)
        ![image](https://user-images.githubusercontent.com/1030080/111207237-047f2580-85d2-11eb-8ebb-3dd61d9dead2.png)
- [ ] As _User 2_ (who did not create the draft) I could also start an election in this state and <kbd>/fin</kbd> finished it.
    ![image](https://user-images.githubusercontent.com/1030080/111207242-077a1600-85d2-11eb-9d6b-995792ee8445.png)

**Comment by tomsseisums** [comment]
@WeaselDog I laid out a basis for issue coming from a discussion in PR, could you, please, finalize the issue setup with labels and stuff?

**Comment by johnkslg** [comment]
```Server Crash scenario```
- Send a message to all UI users to close the UI. There is a mechanism to do this with World Object UIs I believe, refactor and share that code. Add an investigation to a task plan for pre-review.

- Additionally, find the source of the crash when editing a deleted thing, and make sure this fails gracefully. 

``` It is possible to send a removed draft entry for election```
Should be helped by above, and also you can force-close the UI in most cases.

```As User 2 (who did not create the draft) I could also start an election in this state and /fin finished it.```
Only the creating user should be able to edit the election. This was fixed before so is a regression.

**Comment by johnkslg** [comment]
Added 'Needs Task Plan', would like to see a brief plan after an investigation of the best way to implement this.

**Comment by Moritur** [comment]
@tomsseisums I can't reproduce server crash on develop. Can you make sure it still happens and if it does share more specific reproduction steps and/or video of how to reproduce that crash?
I can reproduce all other parts of this issue, but I just can't get server to crash.

**Comment by tomsseisums** [comment]
@Moritur nope, the crash doesn't happen anymore. 🎉
