### ISSUE TITLE
[0.9.3 staging-1963] Failed to handle RPC method: OpenUI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21079]
I have 100% steps only with command, so Step to reproduce:
- use /contracts spawn
- try to open spawned contract board
- have disconnect (or notification without mode):
[RPC.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6196052/RPC.txt)

**Comment by serpopov** [comment]
custom clause broken

**Comment by abaza121** [comment]
yea this is related to this issue https://github.com/StrangeLoopGames/EcoIssues/issues/21080

**Comment by SlayksWood** [comment]
Today I catch it again with Campsite:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6264204/Player-prev.log)
So my campsite was broken:
1. Double storage in UI
![image](https://user-images.githubusercontent.com/45708377/113702961-ded1d180-96e2-11eb-89e5-7d835dd5e168.png)
2. Craft tab is broken at all:
![image](https://user-images.githubusercontent.com/45708377/113703034-f90baf80-96e2-11eb-9d0c-f961addeeeb8.png)
3. 2 sleep button:
![image](https://user-images.githubusercontent.com/45708377/113703056-0032bd80-96e3-11eb-9a26-d20ca00399b2.png)

I don't know how to reproduce it, but I used Alt+Z a lot to hide/show UI when open Campsite. Add to investigation it to next release.

**Comment by SlayksWood** [comment]
@abaza121 it would be nice if you could take a look too, maybe I won't be able to reproduce it myself.

**Comment by SlayksWood** [comment]
merged to #21450
