### ISSUE TITLE
[9.4 Develop] Shovel is deselected with pick up

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#21070]
Currently the shovel is deselected when you pick up a block like Dirt etc.
The Shovel is no longer displayed with Blockmaterial and you can not select back to the Shovel.
![grafik](https://user-images.githubusercontent.com/37456949/112225533-3ecd7000-8c2d-11eb-8c9b-d31067577c4b.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 277
