### ISSUE TITLE
[0.9.4.0 - Develop 224] Multiple RPC issue

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21082]
Multiple RPC error sighted in 9.4 

1. XPEffect & Sound Action RPC
   Reproduce : 
- Picking up random edible plants and eat
- No action sound, and RPC notification shows
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/4ab05721-0cac-4633-822b-613edec26fa2)

2. Sound Action RPC when picking up and placing building materials
   Reproduce : 
- /give corrugated steel & /give modern hammer
- use hammer to place steel as building block/fences & pick up with hammer  
- No action sound, and RPC notification shows
https://gyazo.com/30072c7b9468bb87c32d1858d403a13b
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/edecef5f-83b1-4a2f-979f-9da42729613a)

3. AttemptPlaceObject
 Reproduce : 
- /give flat steel door 
- attempt to place door anywhere  
- unable to place door down & RPC error shown
 (*issue can be reproduced with any items that was able to place down, statues, vehicles, carts, furnitures)
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/e3c34458-5fd5-41f6-8cde-dbad9e70a3c0)

**Comment by TwixterZ** [comment]
Re-tested on 9.4.0 develop-225, issues is not fixed

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/fef1d083-853e-48ca-92f0-ecf9abdfe7c2)

**Comment by TwixterZ** [comment]
adding on to this, below issue also exist under develop stopping player from being able to interact with tables, storages (boxes and plotted), unable to drill, 

Drill not usable :
https://gyazo.com/51edef4849c2ca2b347c030ccdf1365d

Failed to interact with table :
https://gyazo.com/9c847d37e88e38f7313d4987ef7c4b2f

Failed to interact with storages:
https://gyazo.com/fe34239580d44937a8cdf9f56de8f056

[#21079](https://github.com/StrangeLoopGames/EcoIssues/issues/21079)

**Comment by Daniel-Magulado** [comment]
Fix was merged to 0.9.3 Staging 1966 and not develop.

**Comment by WeaselDog** [comment]
It has been merged to staging since this time. We need to fix this one as it is blocking testing.

**Comment by serpopov** [comment]
ArgumentNullException: Value cannot be null.
Parameter name: uriString
  at System.Uri..ctor (System.String uriString) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.LoginUser (System.String serverUri, System.String accountIdUri, System.String vivoxAccessToken) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by TwixterZ** [comment]
this is fixed as of 9.4 develop 242
