### ISSUE TITLE
USER ISSUE: Skill books and skills not functional

### ISSUE THREAD

**Issue by Alterious1** [StrangeLoopGames/EcoIssues#21086]
\
**User Id: Alterious**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Craft a skill book and right click, and right click a skill scroll.

**Expected behavior:**
Right mouse function should produce a skill scroll, which should be right click-able to learn a skill.

**Actual behavior:**
Right mouse click does not produce a skill scroll, and right clicking the skill scroll does not learn resultant skill.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
tested on 0.9.2.4 beta release-156

@Alterious1 thank you for reporting this, please help to answer following questions:

1. Is this happening to a specific type of skill book/scroll?
2. Are actions performed while said skill book/scroll is located in your inventory or somewhere else(please specify)?

**Comment by Alterious1** [comment]
Issue has been resolved on my end, @TwixterZ. A program I had been testing somehow resulted in conflicts with mouse inputs, resulting in aforementioned problem, game has had no issues

Thank you for a speedy reply and continue the good work!
