### ISSUE TITLE
Stats save data that maybe is not necesarry

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#21098]
Now stats are saving all detailed information from action, like position, crafted item and so on. 

It seems like it's never used, since there are only Citizen id and time params, that are actually used by Stats.cs class. 

So add toggle which will disable saving data for all but Citizen/time params, to prevent db be so big. It seems like this data may be usefull in the future (like when web site of server will be able to make custom queries, like "Animals hunted by modern bow"), but not right now. 

I suggest to not save data that can't be used now for perfomance reasons

**Comment by johnkslg** [comment]
If you disable it, make it easy to bring back in the future when we need it.

**Comment by IcedForge** [comment]
This could potentially have larger impact in regards to player laws, as i know location querying in stats is used in limiting transactions and other stuff.
Any removal of stats are to be considered dangerous and needs more planning and assessment before this is done.

**Comment by gzatravkin** [comment]
> This could potentially have larger impact in regards to player laws, as i know location querying in stats is used in limiting transactions and other stuff.
> Any removal of stats are to be considered dangerous and needs more planning and assessment before this is done.

Could you attach sample? As I saw it it's not used in any way, laws are using location of GameAction before it's stored in db. 
There are no any method that uses anything besides time and citizen in interface of accesing to db.

**Comment by gzatravkin** [comment]
![image](https://user-images.githubusercontent.com/53317567/112674978-597a3180-8e45-11eb-88e5-ea8959230e68.png)

**Comment by gzatravkin** [comment]
So I added grouping of actions. It can group together stats like "worked on X" and "worked on Y". QA, can you test if it really don't affect existed/possible laws based on stats?

**Comment by IcedForge** [comment]
Will close this, will reopen or create a new one  once we are able to migrate over and test white tiger in 9.4
