### ISSUE TITLE
[0.9.3.0 beta staging-1964]Residency/Rent: When leaving property(renting) for another property, missing lose object ownership prompt

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21090]
Leaving a residency - Just leaving it 
Gives me information about all objects  i am about to lose once i leave this plot.

If i leave a residency by opting in to rent another object i do not get this prompt window.

Reproduction
Rent property and place furniture/items
Try to rent another property and you will only get warning and not this new prompt about what you lose.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/117004240-85af8a80-acee-11eb-9f12-f14f6b189b68.png)
