### ISSUE TITLE
9.3 1964 - Claiming first plot (one plot only) shows total land 0 square metres

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21095]
Claiming an individual plot shows Total land 0 square meters, which then when claiming a second plot shows total land 25 square meters

![image](https://user-images.githubusercontent.com/61889138/112548386-099f5a00-8db4-11eb-894c-4f1ec534ac6e.png)

**Comment by WeaselDog** [comment]
Fixed in 9.5
