### ISSUE TITLE
Grass destroying new planted plants 

### ISSUE THREAD

**Issue by Hanan09** [StrangeLoopGames/EcoIssues#2110]
while farming notice that grass grow in the unplanted  and planted soil, the only way to get rid of them was shovel the dirt after that place it back and then use the hoe again 

I suggest making it part of the soil but to not to destroy the poor plants and make a way (tool or action) to clean the weed out of the plant or the yield become less

**Comment by stormoffires** [comment]
for the love of farming please fix this! haha there is way to much work with grass and trees spawning in fields...

**Comment by MarjieAVolk** [comment]
Think I found a fix
