### ISSUE TITLE
9.3 1964 - Vehicle controls WASD info overlaps button icon edges

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21108]
Bit difficult to see, font size might need to be ever so slightly smaller so it fits in the button artwork?

![image](https://user-images.githubusercontent.com/61889138/112652920-d5747980-8e45-11eb-9a54-a8590e252dd6.png)

**Comment by MishkaFur** [comment]
Seems to be fine in 9.3 1971 so can probably get closed?

UI scaling 70% 4k screen

![image](https://user-images.githubusercontent.com/61889138/113788742-968fcf00-9735-11eb-8071-3ec2b4ca33d8.png)

**Comment by WeaselDog** [comment]
Thanks for the follow up.
