### ISSUE TITLE
9.3 1964 - District map does not become orphaned if zoning office picked up

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21106]
Was trying to move a zoning office, it gave the alert about it being orphaned will disable etc, placing the zoning office down again does not give the prompt for importing the orphaned district map.

District map also instantly vanishes off the world layers so i think its just being deleted instantly.

Edit, does not seem to happen if the district map was made in 1964, seems to have just been ones made in previous 9.3 builds that would'nt orphan

**Comment by TwixterZ** [comment]
@MishkaFur as this is working properly as of 9.3 staging-1964,we are closing this issue for now.

if similar are to happen in the future please assist to re-raise issue.
