### ISSUE TITLE
USER ISSUE: chopping wood.

### ISSUE THREAD

**Issue by SPEAJA** [StrangeLoopGames/EcoIssues#21100]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
GET IN FRIENDS SERVER	
CHOP DOWN A TREE.
LET TREE HIT GROUND
TRY CHOPPING WOOD INTO SMALLER PIECES	

**Expected behavior:**
IT SHOULD LET ME CONTINUE CHOPPING WOOD WHEN TREE HITS GROUND(IN A FRIENDS SEVER)

**Actual behavior:**
NOTHING HAPPENS. DOESNT EVEN HIGHLIGHT.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS
HAPPENS WHEN NO MODS ARE INSTALLED

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@SPEAJA thank you for reporting your issue

in order for us to pinpoint the culprit, kindly assist to provide below information
1. Are you using Windows, Mac or Linux system?
2. The area where the tree fell down, is it a unowned land or owned by one of your friends?
3. Can you share your log file when this happens? _Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file_
4. If possible, a video or screenshot this happening would be helpful too.

**Comment by IcedForge** [comment]
Will close due to lack of reply. Please reopen and fill out the above mentioned list if this is still occuring for you.
