### ISSUE TITLE
9.3 1964 - Unable to edit store items unless game restarted

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21107]
Place down a store, try to add items via edit for sale/purchase the button does nothing, restart game then try to edit and it seemingly works.

Possibly related to https://github.com/StrangeLoopGames/EcoIssues/issues/20737 ?

**Comment by TwixterZ** [comment]
@MishkaFur thanks for finding this out. 

Re-Production : 
1. Place down store (make sure to fulfill all status requirement)
2. Set up currency and bank account for store usage
While store is "Closed" status
- Attempt to edit Sale and Purchase list
- Observe nothing happens.
https://gyazo.com/99b99c47822d5dc1157d2d97b855b292

While store is "Open" status
- Attempt to edit Sale and Purchase list
- Observe nothing happens.
https://gyazo.com/2811d0fc1b1e010b513686566e4c0525

**Comment by TwixterZ** [comment]
@MishkaFur I'm closing this issue as store is behaving as expected now, if this issue rise up again, please raise a new issue. 

thank you! =)
