### ISSUE TITLE
9.3 1964 - Economy Viewer alignment niggles if resizing window

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21109]
If you resize the window chances are the columns will become slightly misaligned with where some text is centred but others is aligned to left/right in particular Distance, currency and Balance.

Item name also ends up with a very wide column despite being massively longer than the longest ingame item name and store name is quite thin for the default type of CHARNAME's Store

![image](https://user-images.githubusercontent.com/61889138/112655875-bf1bed00-8e48-11eb-8bf3-0d377efd50f7.png)

![image](https://user-images.githubusercontent.com/61889138/112655897-c5aa6480-8e48-11eb-8a17-cd77e9844187.png)

Interface scale 75% on a 2560x1440p monitor

**Comment by TwixterZ** [comment]
thank you for catching this @MishkaFur

https://gyazo.com/66e7c7f62cf21cc2402f89e2e3e45dd1

**Comment by TwixterZ** [comment]
@MishkaFur good news, Issue is now fixed in 9.5 version of ECO (staging)
