### ISSUE TITLE
No shift+Click functionality for Tools in Toolbench or upgrade modules in ANY bench.

### ISSUE THREAD

**Issue by Hursay** [StrangeLoopGames/EcoIssues#21112]
Tools and bench upgrades do not have the same shift+click functionality that most other resources have... Can it be changed so tools can be shift+clicked into the repair slot, and back to your backpack? Also is it possible to add the shift+click functionality to the upgrade slot?

**Comment by WeaselDog** [comment]
Thank you for your report. We will merge it into this issue which we plan to prioritize: https://github.com/StrangeLoopGames/EcoIssues/issues/10248
