### ISSUE TITLE
9.3 1964 - Carpet does not merge into terrain like other blocks

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21111]
Carpet does not merge into the terrain like other blocks do, not sure of the proper term for this.

![image](https://user-images.githubusercontent.com/61889138/112660381-4bc8aa00-8e4d-11eb-9553-c2bd04fdb7ed.png)

**Comment by Daniel-Magulado** [comment]
Hi MishkaFur, thank you for making a report about this.

Tested on 0.9.3 Staging-1964.
I can confirm that this is happening.

Oddly enough, if you put a block above the carpet while surrounded by other blocks such as sand, this happens.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/0f35e29d-5813-41c3-8eb1-69b548da629a)

**Comment by MishkaFur** [comment]
I would not expect raw asphalt to merge in though as it is same as if you just placed a log on the ground? @Daniel-Magulado

**Comment by keegan-o** [comment]
yeah I don't think we want raw items merging in with terrain, but will fix for the carpet blocks since they are built and perfect cubes.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/d8081546-efaa-41ea-8e6c-dbb8c158a269)

fixed in develop branch for 9.4
