### ISSUE TITLE
Property highlights in world are too faint again

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21115]
![image](https://user-images.githubusercontent.com/3536496/112704593-63f1f680-8e58-11eb-8204-7a28f6f8d780.png)

**Comment by SlayksWood** [comment]
poorly visible only at midday (/time set 12)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-287.

The highlight is noticeable now and has a significant improvement. Closing.
