### ISSUE TITLE
Invisible stone axe?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2111]
"also stone axe (given by learning laboring) doesn;t show as proper icon in toolbar, also couldn't even see it being held in the hand"

![image](https://user-images.githubusercontent.com/23460210/30451316-1f4fcef2-9948-11e7-97fa-e189caf3ecad.png)

**Comment by SeanAtr0n** [comment]
might be a svn issue? I can see mine

although I did notice a different issue... it doesn't produce the particle effect when chopping

**Comment by craig-jong** [comment]
I don't think this is an issue anymore - reopen it if it is, but the stone axe seems fine in master currently.
