### ISSUE TITLE
[0.9.3 Staging-1964]First task for World View Tutorial completed without opening Map

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21122]
Build: 0.9.3 Staging-1964

### Issue
The first task for the **World View** tutorial is already completed without even opening the map.

Repro:
1. Play through the tutorial.
2. Finish the **The Meteor** tutorial.
3. Expand the **World View** tutorial and observe.

Video Repro:
https://images.zenhubusercontent.com/42199084/5ad073bc-0f73-470a-bd5f-d8e829f79594/2021_03_27_12_48.mp4

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/118092942-693ddd00-b3d5-11eb-9d39-8aa6df812dea.png)
