### ISSUE TITLE
[0.9.2.4 release-156] USER ISSUE: Wake Up Using Escape

### ISSUE THREAD

**Issue by amilious-ba** [StrangeLoopGames/EcoIssues#21123]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Sleep in a bed
2. Press ESCAPE to exit the bed

**Expected behavior:**
The skybox should not cycle after getting up if exiting the bed.

**Actual behavior:**
The skybox keeps cycling day to night very fast as if you were sleeping.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by amilious-ba** [comment]
This problem does not happen if you click on the "wake up" button.  It only happens if you press "Escape".  My guess is that you are listening to the button click event and not for the escape keypress.  This should be very easy to fix.

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm it has been fixed in the upcoming 9.6 release
