### ISSUE TITLE
[0.9.3 Staging-1966]Hint indicates Papaya can be picked up as an item via LMB when hammer is active

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21133]
Build: 0.9.3 Staging-1966

### Issue
When picking up plants or fruits, it's usually via letter E as per Hint Tooltip suggestion. However, if you set Hammer as an active tool and come close to a Papaya, Hint shows LMB to pick up the fruit and not the key E.

Note:

- Getting even closer to a Papaya changes the Hint tip from LMB to E.
- Unable to reproduce on other types of plants and fruits.
- Pressing LMB triggers an audio effect but nothing else happens.

Repro:

1. Select Hammer as an active tool.
2. Slowly come close to a Papaya.
3. Observe.

Screenshot:

https://images.zenhubusercontent.com/42199084/fdc8e7be-6b55-40a4-a0fa-fda4a0fda29c/2021_03_29_00_03_trim.mp4

**Comment by WeaselDog** [comment]
Fixed in 9.5
