### ISSUE TITLE
USER ISSUE: Industrial Elevator

### ISSUE THREAD

**Issue by chopperprop** [StrangeLoopGames/EcoIssues#21136]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
BUILD ELEVATOR MAKE SURE IT WORKS

**Expected behavior:**
it goes up and down and can be seen by all players

**Actual behavior:**
some players can not see the elevator unless they disconnet and come back and it still does not work correctly

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@chopperprop thank you for reporting this issue to us, 

however this is a known issue reported under https://github.com/StrangeLoopGames/EcoIssues/issues/20738 

hence I will close your issue due to duplicate, you may refer to above link to follow up on this issue
