### ISSUE TITLE
9.3 1966 - Rent currency does not default to what treasury has set

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21135]
As per subject, rent's currency does not default to the currency that the treasury has set.

![image](https://user-images.githubusercontent.com/61889138/112759764-69804580-8fec-11eb-9894-1dedeb3620bf.png)

![image](https://user-images.githubusercontent.com/61889138/112761713-7dc84080-8ff4-11eb-8761-b2a99d0954ad.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/118944177-fdbbb880-b95c-11eb-8d06-081abc8b9af4.png)
fixed in 0.9.4 staging-1988
