### ISSUE TITLE
USER ISSUE: time speed made

### ISSUE THREAD

**Issue by SINKY7** [StrangeLoopGames/EcoIssues#21137]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1 sleep 
2 press esc

**Expected behavior:**
sleep then wake up like normal

**Actual behavior:**
now time is passing at the speed it dose when you sleep

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no not you do you know if one could fix this 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@SINKY7 Thank you for reporting this, I will close this due to duplicate

https://github.com/StrangeLoopGames/EcoIssues/issues/21123
