### ISSUE TITLE
[0.9.3 staging-1966] Can't link storages in store when title ownes property.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21139]
Step to reproduce:
- place registrar and make title:
![image](https://user-images.githubusercontent.com/45708377/112802821-52d4ff80-907b-11eb-8707-02ec166e0acb.png)
- claim property and transfer owner to this title:
![image](https://user-images.githubusercontent.com/45708377/112802908-6aac8380-907b-11eb-88eb-c024edeb8612.png)
- place chest, store and farmers table here:
![image](https://user-images.githubusercontent.com/45708377/112802984-8021ad80-907b-11eb-9bc1-2513167ad0bd.png)
- add acorn and 10 beet to chest:
![image](https://user-images.githubusercontent.com/45708377/112803016-89ab1580-907b-11eb-82f4-cea506416152.png)
- open farmers table and limk storage to it:
![image](https://user-images.githubusercontent.com/45708377/112803131-a3e4f380-907b-11eb-88c0-26a39563d90c.png)
- you can craft beet seed.
- open store and link chest here:
![image](https://user-images.githubusercontent.com/45708377/112803302-d0007480-907b-11eb-89bb-b1b57bdc06fd.png)
- add beet and acorn to sale list:
![image](https://user-images.githubusercontent.com/45708377/112803388-e3abdb00-907b-11eb-82b7-00f8f8cc97ee.png)
It should not be sold out, because I should link storage as title owner, not like just a player.

the first fix of this issue #18530

**Comment by SlayksWood** [comment]
check elected title and demographic

**Comment by IcedForge** [comment]
Works well for 
Users
Demographics owned store
Title owned store
Elected title owned store.

Good job // Staging-1968 tested
