### ISSUE TITLE
[9.4 Develop-228] ECO steam client failed to launch

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21141]
Launching ECO client via steam (develop build) will fail

Logs as below :
[https://app.zenhub.com/files/47210472/4d711d4c-a61a-4381-a14e-db8271bd5d04/download](https://app.zenhub.com/files/47210472/4d711d4c-a61a-4381-a14e-db8271bd5d04/download)

**Comment by TwixterZ** [comment]
issue still ongoing on 9.4 develop 230

**Comment by mirasrael** [comment]
Investigated issue. It happens in STOVE
![image](https://user-images.githubusercontent.com/475445/112972223-b5e89400-9158-11eb-915b-a7263b1e8470.png)

The reason of crash this part of code:
```csharp
var stoveCallbacks = new StovePCCallback
            {
                OnError = this.OnError,
                OnInitializationComplete = this.OnInitializationComplete,
                OnOwnership = this.OnOwnership,
                OnToken = this.OnToken,
                OnUser = this.OnUser
            };
```
for test I removed all callbacks
```csharp
var stoveCallbacks = new StovePCCallback
            {
/*                OnError = this.OnError,
                OnInitializationComplete = this.OnInitializationComplete,
                OnOwnership = this.OnOwnership,
                OnToken = this.OnToken,
                OnUser = this.OnUser*/
            };
```
and crash stop happening.

It is known issue for IL2CPP callbacks (which used internally by STOVE). 
Callback passed to native code should be attributed and should be static like:
```csharp
[AOT.MonoPInvokeCallback(typeof(ENet.InterceptCallback))]
    public static int IL2CPPIntercept(ref ENet.Event @event, ref ENet.Address address, IntPtr receivedData, int receivedDataLength) => originalInterceptCallback(ref @event, ref address, receivedData, receivedDataLength);
```

**Comment by TwixterZ** [comment]
latest crash log for 9.4-beta-develop-233

[Crash_2021-04-01_061500148.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6241404/Crash_2021-04-01_061500148.zip)

**Comment by TwixterZ** [comment]
latest build of develop now shows a different error, log attached 
9.4.0-beta-develop-239

[Crash_2021-04-03_031736871.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6251817/Crash_2021-04-03_031736871.zip)

**Comment by WeaselDog** [comment]
Fixed in build 249.
