### ISSUE TITLE
USER ISSUE: Bug when sleeping

### ISSUE THREAD

**Issue by superdregon** [StrangeLoopGames/EcoIssues#21146]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Sleep
2. Press key Esc

**Expected behavior:**
You'll see that the game thinks you are sleeping because the sun is moving very fast, but you aren't sleeping

**Actual behavior:**
You'll see that the game thinks you are sleeping because the sun is moving very fast, but you aren't sleeping

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't know how to remove mods and add mods, so all the mods and plugins that I have are the mods and plugins that when I bought the game had. I'm new to this, sorry!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@superdregon thank you for raising this issue.

This is however already been raised by another player under [#21123](https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/21123).

I will close this issue as duplicate and you may follow up on this on above ticket.
