### ISSUE TITLE
Multiple mymod.unity3d issue

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#2115]
Having multiple x.unity3d mod file doesn't let user connect to the server. The server load normally.
I have tried to put the unity3d in different folder and in the same folder, nothing changed. Adding the models in the same unity3d file lets the user connect to the server.

**Comment by Phlo123** [comment]
I forgot to say that this doesn't create any dump file as it kicks the player for inactivity.

**Comment by ClayC90** [comment]
Please add high priority to this as countless hours of work from both me, emmeck and phlo has been put into mods that will simply not work without this fixed.

Thanks!

**Comment by ClayC90** [comment]
any updates on this please?

**Comment by Arend90** [comment]
would love to see the insane amount of mods implemented when 6 released 🌊

**Comment by ecoemmeck** [comment]
please make this happen in time for alpha 6 release day
we need to run multiple mods at the same time

**Comment by KarmaChamelonn** [comment]
Mods are the only thing that make this dodgy game runable, do the right thing and start on the right foot. #hotfixrelease

**Comment by KyeEco** [comment]
deffinatly need this as it makes alot of different items usable that weren't as well as allowing us to enhance the play style of each user and allow them a full feel of different aspects,
