### ISSUE TITLE
[0.9.2.4] Demographic unable to own a Store

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21150]
I'm not sure if this is intended, or a limitation that more than one person "owning" a store, but I think I discovered an issue where if I set the owner of a deed to a demographic, and that deed contains a store, then citizens are unable to sell to the store as they get the error that there is no available storage. Also any items that are listed for sale will show as being sold out, even though they are in a linked stockpile, and even has a notification that the item is available for sale.

**Comment by SlayksWood** [comment]
Thank you for the report. try to link/unlink storages, but this is broken in 0.9.3 staging-1966. merged to #21150

**Comment by Dave247** [comment]
> Thank you for the report. try to link/unlink storages, but this is broken in 0.9.3 staging-1966. merged to #21150

I assume there was a typo in the issue ticket number? As the one you wrote is for this issue itself.

**Comment by Dave247** [comment]
> Thank you for the report. try to link/unlink storages, but this is broken in 0.9.3 staging-1966. merged to #21139

I have tried but it doesn't seem to work. it could also be due to a separate issue where object ownership will sometimes not update to the new owner when updating it on the deed.

For what it's worth though, it works if it's a title with a single person in them.
