### ISSUE TITLE
[0.9.3.0 beta staging-1966]Need new Item - Modern Tailoring upgrade

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21152]
Need a new Item for the new and modern tailoring equipment

- [x] Add item 

- [x] Icon 

Intended to be used in
Spin melter
Advanced tailoring table
Automatic Loom

**Comment by keegan-o** [comment]
So this is just one new icon for a new upgrade module, only one tier needed?

**Comment by RobertMangano** [comment]
added new icons to develop
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/66d5a73f-5786-4225-94f5-8f36f44558f8)

**Comment by IcedForge** [comment]
Looks amazing good job!
