### ISSUE TITLE
[0.9.3 Staging-1967]Industrial elevator controls can stop working and malfunction permanently

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21166]
Build: 0.9.3 Staging-1967

### Issue
Player's can accidentally spam industrial elevator controls by simply pressing and holding the E key when the action pointer is at the right position.

Note:

- Once the bug triggers, it permanently disables the Industrial Elevator.
- Relogging in doesn't fix the issue.
- Restarting the game client doesn't fix the issue.
- Player's has to manually climb their way up.

Repro:

1. Install Industrial Elevator.
2. Position the player's interaction point at the top boarder of the Down button which is almost in between the stop and the down button.
3. Press E and observe the alternating call function for each button.
4. Try to move away and keep trying. Eventually, you'll get locked out from the controls with an error message **"You Should Be Closer To Interact."**

Video Repro:
https://images.zenhubusercontent.com/42199084/79903971-6ca8-445f-8cd3-d13d83fc9cf5/2021_03_30_22_14_trim__2_.mp4

Relaunching the Client
https://images.zenhubusercontent.com/47210472/7b9011b5-75f8-4732-8901-82d058158138/untitled.mp4

**Comment by SlayksWood** [comment]
dup #20893
