### ISSUE TITLE
[0.9.3 staging-1967] Glitch of Constructed blocks shadowplacement when change fill type.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21161]
Step to reproduce:
- take any block and hammer:
- select any fill type:
![image](https://user-images.githubusercontent.com/45708377/112970895-58a01300-9157-11eb-95ff-7e432f742ada.png)
- change fill type without moving mouse:
![image](https://user-images.githubusercontent.com/45708377/112970936-62297b00-9157-11eb-8e6d-7ed51e91681f.png)
- shadowplacement is missing, try to place block nothing happens.
video: https://drive.google.com/file/d/1CfhZg4NChUSeImdsfJW9TJSCG5C6CeP2/view?usp=sharing
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6228125/Player.log)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2020

Closing as fixed.
