### ISSUE TITLE
USER ISSUE: Login In issues

### ISSUE THREAD

**Issue by Whitestar23** [StrangeLoopGames/EcoIssues#21169]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Log in to the server after being DCed

**Expected behavior:**
Conection Failed

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b906456-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes & Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
