### ISSUE TITLE
[0.9.3 staging-1967] Joshua's crown behaves strangely when cutting down

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21160]
https://user-images.githubusercontent.com/45708377/110099997-fb60ae00-7db2-11eb-908f-d32b8e15eb22.mp4

_Originally posted by @SlayksWood in https://github.com/StrangeLoopGames/EcoIssues/issues/20580#issuecomment-791316722_

This is not a regression

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2030.

To reproduce, cut the branches of the Joshua tree. Not the tree itself.
Still happening on the said build.


https://user-images.githubusercontent.com/77248866/123192059-c0ef5e00-d4d4-11eb-9c63-a0c268ef04e9.mp4

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 0.9.4 Staging-2040 

https://user-images.githubusercontent.com/78054747/123921306-7597ec80-d9b9-11eb-8f19-724bda83a9a4.mov
