### ISSUE TITLE
USER ISSUE: Login Failure - Unable to play

### ISSUE THREAD

**Issue by JDBooker** [StrangeLoopGames/EcoIssues#21168]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Through Steam: Load game, then try to enter any server.
Through SLG Client: Load Game and try to log in.

**Expected behavior:**
Login should authenticate and work.
This is the 2nd time this has happened in a few days.
Tested with a few friends(4) and all our accounts are acting the same.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b905df7-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
