### ISSUE TITLE
USER ISSUE: Cant join any server

### ISSUE THREAD

**Issue by lan1hotspots** [StrangeLoopGames/EcoIssues#21176]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I just try to join any server

**Expected behavior:**
Joining a Server

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (502) Bad Gateway.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
