### ISSUE TITLE
USER ISSUE: Connection Failed 

### ISSUE THREAD

**Issue by PapaFatBat** [StrangeLoopGames/EcoIssues#21170]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Try to log into any server. 4 of my friends are having the same issue at the same exact time	

**Expected behavior:**
Let me log into the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b906c5a-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
