### ISSUE TITLE
USER ISSUE: Auth failed 502 error

### ISSUE THREAD

**Issue by Tbear1825** [StrangeLoopGames/EcoIssues#21179]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Try logging into game

**Expected behavior:**
Been able to log into the game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (502) Bad Gateway.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Auth servers are on maintenance currently.

**Comment by Tbear1825** [comment]
Sounds good, thank you!  Keep up the good work.
