### ISSUE TITLE
USER ISSUE: Suddenly can't enter any world

### ISSUE THREAD

**Issue by KatKorpen** [StrangeLoopGames/EcoIssues#21175]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Trying to enter the world I played in yesterday. 
When that failed I:
1. Checked my connection
2. Then tried several other worlds. Including offical Eco server
3. Checked the file integrity on Steam
4. Restarted everything
5. Loged in to the eco-site to check my account just in case
6. Repeated the steps above because ... desperation.

**Expected behavior:**
Well I expected to have gotten into at least one world. I have about 660+ hours of Eco played and this is the first time I can't get in anywhere while everything else is working and I can find no faults/solutions.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b907c12-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed as far as I know. I have at least not installed any to my knowledge.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hey Kat,
I can't say yet, we're working on it. Hopefully soon.
Up-to-date information can always be found on our discord at discord.gg/eco in the news channel.

**Comment by D3nnis3n** [comment]
It's up again :)
