### ISSUE TITLE
USER ISSUE: I can't connect?

### ISSUE THREAD

**Issue by wong-johnathan** [StrangeLoopGames/EcoIssues#21173]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b907782-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
