### ISSUE TITLE
USER ISSUE: ECO disconnect/cannot join

### ISSUE THREAD

**Issue by ErnieZed** [StrangeLoopGames/EcoIssues#21172]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
I was disconnect while in game and could not rejoin. I also could not join a server that I was on earlier. I have restarted the game. Checked for updates. Restarted Steam. Restarted my computer. I have Internet access. I still cannot join.

**Expected behavior:**
Should not have disconnected. Should be able to join.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: |7b90717b-4efaedc68634d3ab.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nothing on my end, just the basic ECO install and play.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ErnieZed** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6230260/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6230261/Player-prev.log)

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.
