### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Etherus91** [StrangeLoopGames/EcoIssues#21177]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**i have this game for over 1 mounth , and until now i didnt have this problem..error 502

**Expected behavior:**
i try to login on many servers but i cant ..all the servers that i want to enter tell's me error 502 until 2-3 h ago i didnt have this problem after i shutdown my computer and left home all was good when i camed back and try to re-enter the game this error started to come (name in game is Beelzebub)

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (502) Bad Gateway.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Authentication servers are undergoing maintenance.

**Comment by Etherus91** [comment]
what wait ..if your servers ar undergoing maintenance then how on the server that i play and the rest of them ..there ar players on ..and i cant enter

**Comment by D3nnis3n** [comment]
People that are already on a server are not affected.

**Comment by UniversalSuperBox** [comment]
@Etherus91, it seems like the *login* servers are down. Every game server contacts Eco's login servers to make sure the people connecting are allowed to play. So, the game server can be up, but if the login servers are down then no one can play.

It seems like there might be some temporary cache of "is a user allowed to play?" that is stored by each game server, meaning that everyone is getting kicked off at different times.

**Comment by Etherus91** [comment]
And how long it will take to be back up and running ..because i really want to enjo some time on this game (the time i have left because of work and other things )

**Comment by D3nnis3n** [comment]
I can't give an ETA, unfortunately.
