### ISSUE TITLE
[0.9.3 Staging-1967]Tallow Wall Lamp doesn't radiate light when switched ON

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21171]
Build: 0.9.3 Staging-1967

### Issue
For some reason, the Tallow Wall Lamp doesn't radiate or illuminate light when turned ON and is facing North or West but it works perfectly fine when facing South or East.

Repro:

1. Get a Tallow Wall Lamp.
2. Set it facing either North or West (Opposite side of the wall attachment)
3. Supply fuel and switch it ON.
4. Observe.

Actual Result:
Tallow Wall Lamp doesn't radiate or illuminate light when facing either North or West.

Video Repro:
https://images.zenhubusercontent.com/42199084/af1b264e-06d7-4e9a-867d-0223f21354ca/2021_03_30_23_24.mp4

**Comment by Jason-Skillman** [comment]
Can't reproduce this issue on staging 0.9.4. All lamps light up in all directions as expected.

https://user-images.githubusercontent.com/35405997/120819017-24631d00-c521-11eb-9a54-30f9ae413f22.mp4

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

The issue is not happening anymore. Closing for now.
