### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Maverick044** [StrangeLoopGames/EcoIssues#21182]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. start game
2. continue on day 5 of my server

**Expected behavior:**
I should have been able to log into my 5 day old private server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: 00-377252cc7abc314cabb4c05e294c11e4-9da7a266cf981542-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
none.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Auth servers are on maintenance currently.
