### ISSUE TITLE
9.3 1967 - UserCode readme.md has incorrect formatting for example code

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21194]
Has some incorrect formatting on the example code, has the ```` from copying in Discord code....which on github formats itself

Issue stolen off Jens :D  

![image](https://user-images.githubusercontent.com/61889138/113067787-ecec9300-91b4-11eb-8376-f8d28ba3e35b.png)

```csharp
namespace Eco.Mods.TechTree

**Comment by IcedForge** [comment]
Grrr! :D
Yeah we need to remove the discord code part

**Comment by thetestgame** [comment]
The formatting used by the README is correct for Github as well. What exactly are you referring to about the code markdown block?

**Comment by mirasrael** [comment]
It is MarkDown syntax and file is README.md where .md is MarkDown. So it totally legal to use markdown syntax inside. Shouldn't be changed.
