### ISSUE TITLE
9.3 1967 - Ecopedia Cotton Boll says it can be planted

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21191]
Cotton Boll says that it can be planted but it cannot, only way to plant cotton is via the seed you get from making thread at farmers table

![image](https://user-images.githubusercontent.com/61889138/113065176-58803180-91b0-11eb-9aea-09c1a76c539c.png)

**Comment by WeaselDog** [comment]
Thanks for catching this!
