### ISSUE TITLE
[Hosted Worlds] Attempting to download the worlds server shows a web error.

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21198]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/114b8bde-38d2-4af8-ad02-b3761f64d021)
Side note: The "Link has been copied to clipboard" only disappears when closing the "How To Start" tab

![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/cd5203d9-647b-4029-80b0-40c15e311903)

**Comment by j3fffff** [comment]
Seems like this is error related to our new security on game download.
Realizing this might be a block for schools that need to download eco for 30+ computers.
Any ideas on how to support them but keep security? @denysaw

**Comment by denysaw** [comment]
@denysaw No, we just still hadn't correct links fixed in /worlds on prod. That was fixed only on dev. So it should work only now.

**Comment by denysaw** [comment]
@j3fffff It's still unsigned url on the snapshot as you can see.

**Comment by denysaw** [comment]
@j3fffff Just checked. It's not even on prod. Will check/fix and upload it there 👍🏻

**Comment by denysaw** [comment]
@j3fffff I guess priority should be higher, right? ) Those links are incorrect for everybody

**Comment by denysaw** [comment]
@j3fffff There won't be a problem for teachers to share link with their students. It'll be stable link to play.eco/s3, and inside it'll be signing each request.

**Comment by Ry4ndrew** [comment]
Retested and fixed. Thanks.
