### ISSUE TITLE
Check if user gets correct amount after linking steam to slg

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21206]

**Comment by denysaw** [comment]
@D3nnis3n Fixed on staging and Prod.

**Comment by j3fffff** [comment]
@Ry4ndrew seems maybe this one slipped past qa tests

**Comment by Ry4ndrew** [comment]
@j3fffff i'm not able to link a test slg account to a test steam account in the sandbox to confirm the fix.

**Comment by Veredior** [comment]
Hello, i checked with the person impacted by this bug, it's fixed on his side. The price is correctly updated now on the web interface and on paypal.

**Comment by j3fffff** [comment]
@Ry4ndrew there is a way to test steam linking on staging. you just alter steam's return url to staging domain.
I added instructions for it on Web Qa doc. for next time.
