### ISSUE TITLE
Check invited members are getting correct amount paid

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21207]
User reported that he sent his friend an invite, the person accepted, but didnt get tier - but everything else.
![image](https://user-images.githubusercontent.com/25908592/113124398-c6ab0f80-9215-11eb-8bc9-29f9843160d6.png)

**Comment by D3nnis3n** [comment]
User 198642 on the other hand, also invited by the same user - got tier, but not amount paid, still null.

**Comment by denysaw** [comment]
@D3nnis3n Yeah, checked and there was no transaction creation. Fixed on Sandbox and Prod.

**Comment by j3fffff** [comment]
@Ry4ndrew seems maybe this one slipped past qa tests.

**Comment by Ry4ndrew** [comment]
Retested with user 198628 inviting user 198629 in Sandbox and it is fixed. Thanks
