### ISSUE TITLE
Item dupe glitch (internet disconnect)

### ISSUE THREAD

**Issue by SpiceyNoodles** [StrangeLoopGames/EcoIssues#21215]
A dupe glitch exists involving disconnecting from your internet. This only works on servers when an internet connection is required. 

It can be used with stockpiles or vehicles. Disconnecting your internet keeps you temporarily on the server. During that brief moment you are able to move items between stockpiles/vehicles. Once you fully disconnect from the server, reconnect internet access, join the server again and you then have duplicated items. It is sometimes a bit finicky with timing. But this can duplicate any item - from resources to end game items like advanced workbenches, lasers, etc. 

I’m not entirely sure why it happens, although it appears to be due to a difference in client side interaction vs server side interaction.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are unable to reproduce this issue.
It would help us to further investigate this problem if you could provide us with more information such as your player game logs and a recorded video of the issue as it happens.
To provide your game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Looking forward to your response.

**Comment by Daniel-Magulado** [comment]
merging this to [8278](https://github.com/StrangeLoopGames/Eco/issues/8278)
