### ISSUE TITLE
Workorder status messed up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2121]
![image](https://user-images.githubusercontent.com/3536496/30505631-c0b70854-9a2a-11e7-9f88-a6ec6e4d4e04.png)

**Comment by MarjieAVolk** [comment]
lol pretty sure I assigned a similar issue to you a couple weeks ago, and then no one could repro it

**Comment by MarjieAVolk** [comment]
Okay, think @metachronism just fixed this one
