### ISSUE TITLE
[0.9.3 staging-1968] Notification that I lose furniture if I try to leave my residencе

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21212]
![image](https://user-images.githubusercontent.com/45708377/113126608-7be2c500-9220-11eb-9908-fc5224fb2b88.png)
I guess only players who leave someone else's residence must have this message. I will not lose access to this items.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-287.

Leaving your own residency now prompts the correct message.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/d8b602a1-ffdb-4f1a-8b82-5b294dbcdb13)

You also will not lose access to your items. Closing.
