### ISSUE TITLE
[0.9.2.4] Buying / selling things create three different logs

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21219]
It seems that whenever you buy / sell things you get 3 different logs per transaction:

![image](https://user-images.githubusercontent.com/964559/113263354-820b8c80-9286-11eb-8fc4-9fcca2f40fff.png)

Those could be condensed into 1: "ThePiachu sold 1 Log at Shop to Jamie for $1 from ThePiachu's Personal Account into Jamie's Personal Account".

**Comment by SlayksWood** [comment]
Thank you for the report, this should be improvement in 0.9.3 with #12425
![image](https://user-images.githubusercontent.com/45708377/113397412-a7db8300-93a5-11eb-8a60-701e044c85db.png)
But we still have some discussion about our new system, and it will be change in next updates with chat update.
