### ISSUE TITLE
9.3 1968 - NRE Object reference not set to an instance of an object - Contracts but works in older 9.3 builds

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21214]
Think this is solely related to contracts, edit subject as required please :)

Server is fine in 9.2.4 and was fine in previous builds of 9.3 (builds around end of Feb, which i think was about 1930?) 

9.3 Build 1930 WILL boot this world though, 1967 and 1968 will not and give the error below

DM me on discord for the save file, it is 700MB as a warning and will suckup about 15-20GB of ram but am happy to get you onto my physical server remotely to check things

![image](https://user-images.githubusercontent.com/61889138/113208443-b58bee00-9269-11eb-84cc-ede5f0e40fa2.png)

**Comment by SlayksWood** [comment]
Save file: https://drive.google.com/file/d/1Iu7XtIsZE609sF2Z7qgdazpNie9UiMry/view?usp=sharing
@MishkaFur I shared only with SLG it.

**Comment by WeaselDog** [comment]
Caused by https://github.com/StrangeLoopGames/Eco/pull/7998

**Comment by SlayksWood** [comment]
@MishkaFur  I can start your server in release-186. Fixed.
