### ISSUE TITLE
Transactions are no longer true to the real paid amount

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21227]
Since the latest changes, when changing the amount paid (to fix an issue, f.ex.) the last transaction gets an updated price as well, in conclusion no longer mirroring the actual payment that was made via paypal. That makes the transaction log useless to check what a user paid, so paypal needs to be opened every time.

Possible solutions:
1. Add a column 'initial_price' that shows the price of that transaction that was actually paid, then the other value is no problem, but this seems a bit weird.
2. Instead of changing the last transaction when editing amount paid add a new transaction with a flag "by admin" that adds or subtracts the amount the admin added or subtracted at amount paid. This seems to be the 'best' solution.

**Comment by denysaw** [comment]
Done. Implemented 2nd solution as much more logical and reliable. But just on Staging (sandbox) for now. I'll inform you when it'll be released to Prod.

**Comment by D3nnis3n** [comment]
It is and works :)
