### ISSUE TITLE
[0.9.2.4] Can't climb onto a road 1 tile underwater

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21223]
On Sea Otter we had some flooding and roads that used to be on the waterline are now 1 tile below:

![image](https://user-images.githubusercontent.com/964559/113370984-078c4c80-931a-11eb-943b-36aeb83ab7c3.png)

For some reason, you can't swim or get onto them from water, while earlier you could get onto them when the water was 1 lower. It would be nice if you could climb these.

**Comment by SlayksWood** [comment]
merged to #8873
