### ISSUE TITLE
Changing a misspelled invite in admin backend and then resending leads to a invalid invite being sent

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21229]
I changed a invite that used a misspelled e-mail in the backend to the correct email, then resent.
The user received a invite e-mail with a hash that is not in the db, hence invalid.

**Comment by D3nnis3n** [comment]
Only medium, as i can disable invites like i did before that feature.

**Comment by denysaw** [comment]
Fixed on Sandbox, gonna release to Prod soon.

**Comment by Ry4ndrew** [comment]
Retested and can confirm fix on sandbox. Thanks.
