### ISSUE TITLE
[0.9.3 staging-1969] Doors should take more occupancy

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21222]
And prevent to place objects in front of them:
![image](https://user-images.githubusercontent.com/45708377/113270857-95e4dc00-92e2-11eb-854b-c8a01d37bd3b.png)
Should work like with Large doors.
![image](https://user-images.githubusercontent.com/45708377/113271252-f83ddc80-92e2-11eb-82bf-924c2d3138d5.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 256

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/edb32bc6-2d7d-4f59-a6fd-14d4e518eba8)
