### ISSUE TITLE
Zfighting on primitive axe

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2122]
![image](https://user-images.githubusercontent.com/3536496/30505706-4574966a-9a2b-11e7-8f66-ac416c0d7715.png)

**Comment by metachronism** [comment]
![image](https://user-images.githubusercontent.com/3150561/30569702-2fbf59a0-9c91-11e7-8278-a47c6e025932.png)

**Comment by keegan-o** [comment]
fixed
