### ISSUE TITLE
[0.9.3 Staging-1970] Sleep Timer modal flickers the time acceleration condition modal

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21234]
Build: 0.9.3 Staging-1970

### Issue
When waking up, the Sleep Timer modal that appears when the player decides to sleep flickers an error momentarily. The error appears to be an informative modal that informs the player about the condition to activate in-game time acceleration. If playing Solo, this modal should not appear at all.

Repro:

1. Sleep.
2. Wake up.
3. Observe the Sleep Timer window.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/fef15f64-0546-47fc-b4f0-ffca8eddca90)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Develop 256

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/380ecda1-c8cc-4451-b514-2809d19fda1d)
