### ISSUE TITLE
USER ISSUE: Arrastra not working

### ISSUE THREAD

**Issue by AlbertBence** [StrangeLoopGames/EcoIssues#21231]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Arrastra's all upgrade not effect the resource cost.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MishkaFur** [comment]
If it has a yellow border it will not affect the resource usage as per the tooltip

![image](https://user-images.githubusercontent.com/61889138/113436431-98c3f780-93dc-11eb-99fc-dfb40e8472e6.png)

**Comment by TwixterZ** [comment]
hi, @AlbertBence. as explained by MishkaFur above, this is working as intended and not an issue.

Hence I will close this ticket
