### ISSUE TITLE
[0.9.2.4] Residency should default to something if you have no housing XP

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21230]
While playing on the Sea Otter, I built my house and was wondering why my house XP didn't update like it used to. Turns out I didn't click that I wanted residency on my only property:

![image](https://user-images.githubusercontent.com/964559/113426396-422cce00-9388-11eb-8169-2a10c4c2c7f2.png)

It would be nice if the residency defaulted to something, anything if you have no housing value and you start placing furniture. This would probably solve the majority of use cases for people, maybe with the main caveat being some cooks with shops that are outside of their one residence.

At the very least, the game should probably prompt you and say "hey, you have a nice house here but you haven't set your residency, maybe you should do that?".

**Comment by IcedForge** [comment]
Don't think this is feasible to have it constantly scan property for property value, especially if it gets a bit bloated with properties could have some significant performance costs.

I think it is simply an issue of player knowledge and a bit of a mishmash UI (which is being reorganized) to make it more apparent that the user perhaps is missing residency completely or maybe the overlay tooltip when mousing over housing chart have a better explanation regarding why your property has no housing.

**Comment by ThePiachu** [comment]
You could try scanning things on when a furniture item is placed outside of a residence - "if housing value on this plot is higher than residence or residence is not set, ping person if they want to switch residences", or at least "if no residence set, on place furniture, prompt to set residence".

**Comment by IcedForge** [comment]
Closed #22132 as its not technically an outright duplicate but it falls in the same problem and should be solved with the same solution.

1. A industrial furnishing is blocking house points.
2. Confusing residency not yielding house points as expected.

Possible solution would be to have a way to directly see where you are resident of, either in the HUD or something. Same thing for the house rooms as well which we do have in the HUD but if its industrial, i believe we need to make a room actually declare it is industrial so it displays on said HUD information.

**Comment by IcedForge** [comment]
Merging #22153
By @johnkslg 
https://www.reddit.com/r/EcoGlobalSurvival/comments/nqn0xv/why_is_this_room_not_giving_xp_im_having_a_real/
Make it so this user would have instantly known what was wrong.

**Comment by TwixterZ** [comment]
Feature tested and confirmed as of 0.9.5 Develop-348

Player without any residency will now automatically became resident of the 1st land they claim
