### ISSUE TITLE
USER ISSUE: [9.2.4 release-156] Auth connection issue

### ISSUE THREAD

**Issue by Lodge106** [StrangeLoopGames/EcoIssues#21232]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60,00%>The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Lodge106 thank you for reporting, does this issue happens to you this one time, or is this a recurring issue?

**Comment by IcedForge** [comment]
Will close in lack of reply, please reopen if you still have this problem.
