### ISSUE TITLE
[0.9.4.0 develop-241] Minimap has strange visual bug

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21243]
Something changed in the minimap so it has very strange visuals. There are lots of lines everywhere and trees look lower quality. We need to find out what was tweaked and get it looking like the normal minimap again.

**Here is what it looks like now:**
![StrangeMinimap](https://user-images.githubusercontent.com/47330823/113495010-fd498a00-94a2-11eb-8ea1-83d9d2dd5ec0.png)

For all the heatmaps, they also look strange. There is lines around the border of the heat maps, and it is not the normal color patterns.

![HeatMapBug](https://user-images.githubusercontent.com/47330823/113494954-4cdb8600-94a2-11eb-90f0-c078b91f1a5c.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 260

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/fc9a7fed-2634-4b8d-ba1f-f380e2047a9a)
