### ISSUE TITLE
Sign letters don't display underwater

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21246]
The signs have issues displaying characters underwater / through water:

![image](https://user-images.githubusercontent.com/964559/113504005-3eb15800-94ea-11eb-8f92-cf47e84ac348.png)

![image](https://user-images.githubusercontent.com/964559/113503999-39eca400-94ea-11eb-9331-ec85704a564e.png)

**Comment by MishkaFur** [comment]
Might be related to #19248

**Comment by redwyre** [comment]
Duplicate of #19248
