### ISSUE TITLE
[0.9.4.0 develop-240] Can't connect to servers on Steam build: Failed Authentication

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21242]
When using the Steam develop build, when you try to connect to a server, it fails and gives an invalid login info error.  When loading the build outside of Steam,  you can log in and out at the main menu but you will still get this error when trying to connect. This issue is critical because it prevents testing the build.

**Steps to Reproduce:**
- Set Eco Client + Server tool on Steam to Develop branch
- Launch Server
- Once server has loaded, join with client
- Error with invalid login info

**In Client Log:**
Disconnected with error: Invalid login info

**In Server UI:**
![FailedToAuthenticate](https://user-images.githubusercontent.com/47330823/113493392-bb651780-9493-11eb-923b-44304c6ce065.png)

### Related Issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/21141

**Comment by redwyre** [comment]
Not related to #21141

Fixed in https://github.com/StrangeLoopGames/Eco/commit/8ade066e483d2ad692ef18090eeb662421e7dce3

**Comment by WeaselDog** [comment]
Fixed in develop-241
