### ISSUE TITLE
[0.9.4.0 develop-241] Skills UI: Education is displayed even when disabled.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21248]
For the Skills UI remake, it shows the education information regardless of it is enabled. This should be disabled when education is disabled.

To replicate
- Launch Develop with default configs (Education Enabled: False)
- Press Z to bring up skills UI

![SkilsUIWhenDisabled](https://user-images.githubusercontent.com/47330823/113519041-c0cb6c00-953e-11eb-8815-c40c91d4dc7b.png)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 260 (tested on vanilla steam client)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/6bf91700-946d-4aef-9731-c2bcf02f9baa)
