### ISSUE TITLE
Cannot name districts.

### ISSUE THREAD

**Issue by Tomboeg** [StrangeLoopGames/EcoIssues#21247]
As elected official, whenever I try to rename districts in the zoning office, the district names do not change and instead they change to their original name e.x. district 1. However, the variable number behind the district does increase. I'll get district 17 for example.

You should be able to reproduce is by trying to rename a district i reckon. 
Version 9.2.4
Running no mods

**Comment by IcedForge** [comment]
Thank you for reporting.
Closing as a duplicate, tracking it in #21277 but this might be resolved in 9.4
