### ISSUE TITLE
[0.9.4.0 develop-241] Skills UI: Profession icon should never be hidden if profession is discovered

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21249]
With the new Skills UI, the profession and specialty icon are hidden until they are discovered.

The profession icon should not hide when the selected specialty isn't unlocked but the profession is.  It should be tied to if the profession is discovered

![ProfessionSkillsUI](https://user-images.githubusercontent.com/47330823/113519327-54ea0300-9540-11eb-9b10-91498e4659b1.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 266
