### ISSUE TITLE
[0.9.4.0 develop-241] Current Populations tooltip in chat welcome message is broken

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21244]
When you highlight the tooltip to see all species, it returns an error "Not Found: This Object No Longer Exists".

To replicate: 
- Log in to server and check welcome message in chat
- Hover mouse over tooltip at bottom of Current Populations: "and # more species"

![BrokenSpeciesTooltip](https://user-images.githubusercontent.com/47330823/113495132-08e98080-94a4-11eb-99ee-0768d8367f6c.png)

**Comment by mirasrael** [comment]
Fixed

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 256

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/135cb40c-f2fc-4704-96b5-a5e41f926c9a)
