### ISSUE TITLE
Need a better law icon notification

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2124]
![image](https://user-images.githubusercontent.com/3536496/30505857-1e216010-9a2c-11e7-8702-277a1f28ea6b.png)

**Comment by keegan-o** [comment]
So this is something to go behind the 10, right?

**Comment by MarjieAVolk** [comment]
Yeah

**Comment by keegan-o** [comment]
updated it to be a circle and made the text white, looks better for now I think!
