### ISSUE TITLE
[Accounts] Linking SLG account with a bought game to Steam does not give the Steam account the game

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21255]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/7e2f6db2-702e-452d-a576-f757553bf844)
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/d66fbf4c-ec3d-42fe-966c-f4d72e3e297c)
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/a48ad9d1-29ea-4ebc-b439-aae7af4fb965)

**Comment by denysaw** [comment]
@Ry4ndrew sorry, tried a lot, but still can't reproduce the case. I hope you were testing on Production also. Here's proof:
![image](https://user-images.githubusercontent.com/5720101/115632612-68e78000-a308-11eb-8dbd-85bae2dd0a06.png)

Whatever part-cases I try, always getting the game. Just mind, that game appears only after linking on `play.eco`, not on `sandbox`.

**Comment by Ry4ndrew** [comment]
Oh okay, I was doing sandbox testing when this issue occurs. Never mind then, as long as it still works in prod it should be no issue.
