### ISSUE TITLE
USER ISSUE: xv

### ISSUE THREAD

**Issue by Coolzozo2** [StrangeLoopGames/EcoIssues#21259]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
Eco is currently open to alpha and beta backers only. Upgrade your account to join.

Log File:
Initialize engine version: 2019.2.17f1 (8e603399ca02)
[XR] Discovering subsystems at path D:/Telechargement internet/ECO.v0.8.3.2/ECO.v0.8.3.2/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f82)
    Vendor:   
    VRAM:     3962 MB
    Driver:   27.21.14.5752
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.424900 ms
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 280)

**Expected behavior:**
xdv

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does issue happen when no mods are installed?:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Comment by D3nnis3n** [comment]
You need to buy the game and play a recent version.
