### ISSUE TITLE
{Accounts] Upgrade to Dev Tier doesn't update the additional amount paid in the Admin backend

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21254]
Reproduce:
1. Log in or create an account to buy Eco
2. Account in db should update the amount paid to $30.00
3. Upgrade the same account to any tier.
4. Account in db still stays at $30.00

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod.

**Comment by Ry4ndrew** [comment]
Retested and can confirm fix. Thanks.
