### ISSUE TITLE
USER ISSUE: House rooms

### ISSUE THREAD

**Issue by Pakka77** [StrangeLoopGames/EcoIssues#21256]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Made and adjustment to a room (was a bedroom) and my Pie went to 3 not 4 slices.  

**Expected behavior:**
Reading it looks like the house has 5 rooms.  Industral, Bedroom, Bathroom, Kitchen and Living room.  

**Actual behavior:**
Only is showing Industral, Bathroom, Kitchen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods ever installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Pakka77 can you share pictures of your rooms setup? this does not sound like a game issue

**Comment by Pakka77** [comment]
Thank you for getting back to me.
Attached are a screenshot of the General room points, the Bedroom, and
Living Room which are providing zero points but do show to be rooms. and
are on my plots of land.

Bedroom:
Bed, Med. Carpet, Hewn Hardwood Cair, Stone Wolf

Living Room:
Desk, Chairs x2, Elk Mount, Med Carpet, Round Pot + Plant, Stone Owl, Stone
Brazier (running)e

Thank You,
Ben Stickney
***********************************************
*       Pakka77@Gmail.Com                    *
*                                                               *
*  Funny Thing About Real Life,              *
*  Reality Has Nothing To Do With It.      *
***********************************************

**Comment by Daniel-Magulado** [comment]
Merging #21208.
