### ISSUE TITLE
[0.9.3 Staging-1971]World View Tutorial: Able to complete task without expanding Environment Data

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21266]
Build: 0.9.3 Staging-1971

### Issue
You can complete the task **"Open the right panel and expand 'World Layers/Environment Data'. Select an option to view it on the map."** without expanding the Environment Data section. In computer literate terms, _World Layers/Environment Data_ is a path. Therefore, the player must not be able to complete the said task without following it.

Repro:

1. Proceed to the World View tutorial.
2. Open Map.
3. Click World Layers.
4. Check the Property and observe.

Actual Result:
3rd task of the World View tutorial gets completed.

Expected Result:
3rd task of the World View tutorial should not be affected.

Video Repro:
https://images.zenhubusercontent.com/42199084/90e1306c-ee8c-4342-8eea-9b9537838c03/2021_04_06_18_15.mp4

**Comment by SlayksWood** [comment]
#20507
