### ISSUE TITLE
Invites do not give tier

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21260]
A user that already had an account got an invite, which leads to this:
![image](https://user-images.githubusercontent.com/25908592/113624645-2ebb8480-9660-11eb-942f-1e6373d82e34.png)

The user was only added amountpaid and the icon, but not the tier, it is still null. User 19861

So either:
1) Invites in general are still broken OR
2) Invites sent to mails that already have a account without tier ("Upgrade" instead of "Invite Link to click" are broken.

Please check and fix. User has been fixed manually.

**Comment by D3nnis3n** [comment]
Confirmed that no invites give tier, made critical.

**Comment by denysaw** [comment]
Hotfixed and tested on Prod.

**Comment by D3nnis3n** [comment]
Confirmed fixed.
