### ISSUE TITLE
USER ISSUE: Vehicle Hitboxes (Green Highlight) --Annoyance but doesn't prevent gameplay  

### ISSUE THREAD

**Issue by Ploto999** [StrangeLoopGames/EcoIssues#21264]
\
**User Id: Ploto999**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
It happens ~10 hours, after frequent interactions with a vehicle (pushing it around and such) in singleplayer the vehicle becomes lightweight and harder to interact with

**Expected behavior:**
Inventory section (such as truckbed, back of cart ect.) should be highlighted in green allowing for the opening of the vehicle inventory UI

**Actual behavior:**
The highlight doesnt appear, and when the curser is over the inventory section of a vehicle it acts as if the vehicle doesnt exist. The only way to interact with it is to find a very small area that might allow you to interact (such as small parts of the bottom of the bed, rear wheels ect)
**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO. Im currently playing in vanilla singleplayer

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6263169/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6263170/Player-prev.log)

**Comment by SlayksWood** [comment]
merged to #20414
