### ISSUE TITLE
Exhaustion Limit: Let players save calories for 7 days

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21278]
Currently the exhaustion limit seems to reset per day, allow players to save up on calories for seven days and only remove those that were acquired before, so they can save for longer weekend sessions when they cannot play on week days for example.

**Comment by Engimage** [comment]
The most of important activity on a server happens in the first 3-4 days. If the exhaustion limit will not have a daily effect it will almost completely lose its sense.

**Comment by WeaselDog** [comment]
We also need a buffer at the start, like 7 days.
I suggest the way it works is that we start capped for exhaustion with 7 days of playtime (2 hours/day = start with 14 hours of playtime). Then each day we regain 2 hours worth of exhaustion.

**Comment by johnkslg** [comment]
I'm not sure it should work like this.  We could make it an option (ie, an 'exhaustion minutes rollover' checkbox), but I want to make it so players who can only contribute a reasonable amount of time per day (say, an hour) arent left in the dust from the beginning.  

I'm open to adding options to how its implemented, though.  Nice thing about our 'multiverse' we can let a thousand experiments happen and we use the one that works best (It's like quantum computing 😊)

**Comment by johnpmayer** [comment]
Seems like the obvious thing is to have multiple settings:

- Exhaustion enabled (flag)
- Exhaustion limit (calories)
- Exhaustion period (hours)

So an admin can make the choice between 2000 cals per 24 hours or 14000 per 168 hours

**Comment by WeaselDog** [comment]
Implemented in 9.5
