### ISSUE TITLE
Composite Lumber Column Texture Issue

### ISSUE THREAD

**Issue by UltraFRS** [StrangeLoopGames/EcoIssues#21275]
I would like to request that we change the Standard Composite Lumber BlockType because it really messes with my OCD due to the fact that the color's are mismatched on the bottom of a columns as opposed to any column block above it (please see attached picture). [https://drive.google.com/file/d/1agPm7jmLppBoNCkpdjW-om3aL-pWdYG9/view?usp=sharing](url)

**Comment by StallEF** [comment]
reupload picture from discord - https://cdn.discordapp.com/attachments/312991502697627658/829379705383813190/Screenshot_28.png

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/a4a400af-333a-4bd9-95d6-af32ec6c01ef)

Went through and did a bunch of improvements to the cleanliness of these meshes and textures, went with solid grain now as well instead of the boards.
