### ISSUE TITLE
9.3 1971 Plants dieing (Plants are alive in 1970)

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21276]
Plants are dieing in 1971 build, eco system could not support it, in 1970 the plants are alive though

Tested with Todd and Jens, both are identical worlds and Todd sent link to the savegame pre death

Below pics same plant and location

1970,
![image](https://user-images.githubusercontent.com/61889138/113774479-40b02c80-971f-11eb-9b57-42073a036059.png)

1971
![image](https://user-images.githubusercontent.com/61889138/113774493-473ea400-971f-11eb-8339-6304692105b2.png)

**Comment by WeaselDog** [comment]
Some screenshots:
![Screenshot_114](https://user-images.githubusercontent.com/47330823/113794189-d6878f80-96fe-11eb-8b08-c1bbcac95d3e.jpg)
![Screenshot_112](https://user-images.githubusercontent.com/47330823/113794200-dbe4da00-96fe-11eb-942a-fc1a2a74d2a9.jpg)

**Comment by WeaselDog** [comment]
I reproduced this bug myself on staging-1971, but I can no longer do it on release-184. Please check and ask me for save if needed.

**Comment by IcedForge** [comment]
Been testing world migration for the large part of today, and ran simulations and force ticks as well as letting it sit naturally to run on 9 different worlds and i have not encountered it again.

**Comment by MishkaFur** [comment]
My world running for a few days now in release 184 has not had plant death so can probably close this?

**Comment by IcedForge** [comment]
Closing this as it seems to have gone away completely, can reopen if it resurfaces
