### ISSUE TITLE
USER ISSUE: Can't connect to server

### ISSUE THREAD

**Issue by ColorMeSurprised** [StrangeLoopGames/EcoIssues#21273]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Leave the server
2. Come back after a couple of hours and try to connect

**Expected behavior:**
I should have joined the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I personally don't but the server might

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6267056/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6267057/Player.log)

**Comment by IcedForge** [comment]
Thank you for reporting, it seems as if it is not establishing any connection to the server, are you sure it is online?
Could you contact the host and see if there is a downtime or other issue?

**Comment by ColorMeSurprised** [comment]
today when i tried to join it was fixed (yesterday the server was on I know that since someone was playing on it)
