### ISSUE TITLE
Amounts not calculating correctly

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21270]
user 197995 that has dev tier and should have amount paid $185

Amount Paid:
![image](https://user-images.githubusercontent.com/25908592/113738378-21a1a280-96ff-11eb-8337-c5cbfef71be2.png)

Transactions:
![image](https://user-images.githubusercontent.com/25908592/113738417-29f9dd80-96ff-11eb-975b-baec821d63b5.png)

Fixing Amount Paid manually:
![image](https://user-images.githubusercontent.com/25908592/113738457-341bdc00-96ff-11eb-8ec4-970e3bb536ce.png)

Breaks Transactions:
![image](https://user-images.githubusercontent.com/25908592/113738479-3b42ea00-96ff-11eb-93fc-749085d093ce.png)

**Comment by Ry4ndrew** [comment]
Retested and confirmed fixed on the database.
