### ISSUE TITLE
[0.9.2.4] Level-up sounds continue going even after logging out of single player server

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21283]
So I was messing around with the various `/skill` commands. I called `/skills levelupall`, which triggered a lot of skills to start levelling up. After logging out of the server, I still kept hearing the "bings" over and over in the main menu:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6269616/Player.log)

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm it has been fixed in the upcoming 9.6 update
