### ISSUE TITLE
Can't examine claim with claim stake

### ISSUE THREAD

**Issue by tuha263** [StrangeLoopGames/EcoIssues#21288]
Hold a claim stake, pressing e to examine claim but nothing happens!
![Examine claim](https://user-images.githubusercontent.com/9598614/113834784-6c7df180-97b5-11eb-9671-3fb7bf97eaf8.png)

**Comment by TwixterZ** [comment]
@tuha263 

Tested and confirm bug as at 9.4 Develop 266

Repro step:
- Create a fresh world
- /give land claim stake
- /give land claim paper,5
- claim a plot of land, tries to examine

Logging out and rejoin does fix this issue
