### ISSUE TITLE
[0.9.2.4] River sand spawns beneath an aqueduct

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21286]
Just found this on Sea Otter:

![image](https://user-images.githubusercontent.com/964559/113834047-39008000-973f-11eb-875d-296d1cf71883.png)

Turns out Dirt can turn to River Sand beneath an aqueduct. It probably shouldn't do that all things considered...

**Comment by MishkaFur** [comment]
Duplicate of #19606

**Comment by IcedForge** [comment]
Closing this as per comment above is correct. Tracking this behavior in that issue.
