### ISSUE TITLE
[0.9.3 staging-1971] Gloves issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21289]
- [x] 1. Can't change color for Farmers gloves:
![image](https://user-images.githubusercontent.com/45708377/113837791-da66f080-9796-11eb-9702-697d8a741864.png)
![image](https://user-images.githubusercontent.com/45708377/113837835-e652b280-9796-11eb-96cc-6a5f9180293d.png)
Change only one color in Smith and Builder gloves.

- [x] 2. Hands go beyond the gloves when moving. A lot with farmer gloves, when touch head with Builder gloves
![image](https://user-images.githubusercontent.com/45708377/113837932-f9658280-9796-11eb-95c9-bf7add608cc7.png)
![image](https://user-images.githubusercontent.com/45708377/113838696-afc96780-9797-11eb-85f9-9d9dd9d0b7c6.png)

- [x] 3. Farmers gloves and Smith gloves should have some inside texture:
![image](https://user-images.githubusercontent.com/45708377/113839228-2cf4dc80-9798-11eb-8488-0b262bc8546e.png)
![image](https://user-images.githubusercontent.com/45708377/113840172-1438f680-9799-11eb-87c4-1793647396fa.png)

- [x] 4. Smith gloves has strange texture on right hands, only this texture depend on gloves color on right hand:
![image](https://user-images.githubusercontent.com/45708377/113840875-d25c8000-9799-11eb-970c-1c41d4aaa921.png)

**Comment by keegan-o** [comment]
Stanislav and Milenko are helping me to resolve these issues, it is in progress except for the lack of color changes on particular pieces which will be addressed differently or not addressed based on certain pieces which might not have tintable elements.

**Comment by keegan-o** [comment]
At last all these are resolved
