### ISSUE TITLE
9.2.4 - Unable to give players with "s in name reputation

### ISSUE THREAD

**Issue by AquatikJustice** [StrangeLoopGames/EcoIssues#21285]
There is a player on a server I play on that nobody is able to give reputation to, and I believe it's b/c their name has "s in it (Red "the Clover" Umbreon). The reasoning for it is obviously a theory on my part, but no other players have had issues receiving reputation.

[Image attached](https://user-images.githubusercontent.com/4640482/113831397-2ee57e00-974d-11eb-8554-53f71a9f6717.png)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I can confirm that this issues is reproducible and all it takes is having a single quotation mark on the player's name.

Tested on both
0.9.2.4 Release-156 and 0.9.3 Release-184.

Attached is a video of the said issue.
https://images.zenhubusercontent.com/47210472/feef7f1a-ad71-4589-afc5-1c4dfd806354/2021_04_10_22_03_trim.mp4

Screenshot:
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8245708a-571d-494d-a52f-c9d928aaca1b)

**Comment by AquatikJustice** [comment]
Just want to point out that we are NOT seeing the issue with the function code on our server. Just the issue with the rep not being able to find the object.

**Comment by gzatravkin** [comment]
Probably tag parser thing

**Comment by madpingui** [comment]
I think its because the link of the textmesh pro (https://docs.unity3d.com/Packages/com.unity.textmeshpro@1.3/api/TMPro.TMP_LinkInfo.html) includes quotations so if the name of the player becomes the link and it has quotations in the name it cuts the link, like this post i found.
https://forum.unity.com/threads/literal-quote-in-link-tag.1099942/

**Comment by gzatravkin** [comment]
Like some possible workaround for that - we can use “ ” then at UI side. Maybe we can add it to TagParser system, so it will replace first " to “ and second to ”

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.4 Staging-2053

![reps](https://user-images.githubusercontent.com/78054747/125259130-9ead6b00-e331-11eb-8a09-5beb11de5c55.gif)
