### ISSUE TITLE
[0.9.3 Staging-1971]Put Items In Container Contract doesn't update Still to Add: section

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21295]
Build: 0.9.3 Staging-1971

### Issue
The Still to Add: section for the Put Items In Container clause in Contract doesn't show the items needed to be stored until an update to the contract is made.

Repro:

1. Accept a contract for Put Items In Container.
2. Observe the Still to Add: section.
3. Make progress to the contract. Do not complete it yet.
4. Observe the Still to Add: section.

Actual Result:
The Still to Add: section for the Put Items In Container clause in Contract doesn't show the items needed to be stored until an update to the contract is made.

Expected Result:
The Still to Add: section should display the items needed to be stored the moment a player accepts the contract.

Video:
https://images.zenhubusercontent.com/42199084/958ba71b-c4c9-4048-8c2f-2d5a818711c5/2021_04_07_19_54.mp4

**Comment by SlayksWood** [comment]
I guess the same issue #18031
