### ISSUE TITLE
[0.9.2.4 beta staging-156] Charcoal missing in inventory action trigger.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21298]
Charcoal is not select able inside inventory action trigger

**Comment by IcedForge** [comment]
Its unfortunately seemingly missing on develop build 281
![Screenshot_90.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/52318304-3463-4330-b35a-b27b20a7ab64)

**Comment by IcedForge** [comment]
Noticed the fix went into staging in hindsight, didnt we have a back marge to develop recently ? need to check if this didnt get overruled by something?

**Comment by Lyrcaxis** [comment]
@IcedForge merge just happened today https://github.com/StrangeLoopGames/Eco/pull/8578
Can you please re-check?

**Comment by IcedForge** [comment]
Showed up in the dev-288 build, looks good.
