### ISSUE TITLE
[0.9.3 staging-1971] Can't change color of Smith Apron

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21291]
![image](https://user-images.githubusercontent.com/45708377/113846218-ea82ce00-979e-11eb-9ead-f52766105aa1.png)
![image](https://user-images.githubusercontent.com/45708377/113846234-ef478200-979e-11eb-9f4f-c3bfb9a17c38.png)

**Comment by keegan-o** [comment]
This one may be a 'won't fix' thing as it is leather and not plastic or fabric. But we will check based on Milenko's opinion. Keep in mind there is always room for a future tint-able plastic or fabric apron :)
