### ISSUE TITLE
USER ISSUE: Iron pipes don't transfer water

### ISSUE THREAD

**Issue by pwolfeb** [StrangeLoopGames/EcoIssues#21297]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Set up iron pipes to go through a mechanical water pump and into a steam engine
2. Look at the status of the mechanical water pump

**Expected behavior:**
It should be flowing water through the mechanical water pump.

**Actual behavior:**
Instead it shows the water input as "Disconnected", while the animation shows the pump working and outputting water.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

Not sure if logs will help because I am playing on a friend's server, but It is included nonetheless.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6272314/Player.log)

**Comment by IcedForge** [comment]
Thank you for reporting an issue.
Could you provide some screenshots of your setup and include both status window of the pump,/power tab and also of the pipe network?

Do you have any open ends of your outlet side?

**Comment by pwolfeb** [comment]
Welp, It seems that I had done something wrong the whole time, because replicating the same pathing and structures in my own administrated world has them working perfectly fine. I'm just going to close this as user error, apologies for taking up your time.
