### ISSUE TITLE
[0.9.2.4] Economy Viewer Contracts screen needs to be in a strict table

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21306]
I've recently had a look at the Contracts viewer on White Tiger and this is how it looked:

![image](https://user-images.githubusercontent.com/964559/113967991-0e6a0200-97e7-11eb-8158-9dca271ad820.png)

It seems that the Distance cell on some of the contracts appeared, and when it did, it distorted the other cells in that table, making it look pretty bad.

I think for the Viewer to look good, all the various fields need to be in a strict table, with each cell width being the same across all rows. This way even if one cell is bigger in one Contract the rest of them will still look aligned.

**Comment by SlayksWood** [comment]
This is fixed in 9.3 #20472
