### ISSUE TITLE
9.3 1971 - Tier reward items disappear if you do not take them all out of void storage at once

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21304]
new world in 9.3 1971

Edit - Also happens in 9.2.4, might be a good idea for migrations into 9.3.X when this is fixed it has a check if player has the items on them and replace if not? ie so i'd get my now vanished Shard and goggles due to the fact Dev tier even with admin cannot spawn in items they are entitled to due to SLG lockdown of tier items only being spawnable by SLG accounts (Unless SLG will hop onto servers with missing tier items, ask for admin, spawn items in then disappear :D

Logged in, looked at tier rewards but did not take them out
Reboot server
Tier rewards still exist
Reboot server
Look at tier rewards take one out
Reboot server

Meteor shard and goggles vanished

![image](https://user-images.githubusercontent.com/61889138/113932537-a36efa00-97eb-11eb-80f7-431da1d59eaf.png)

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Staging 288
