### ISSUE TITLE
9.3 1971 - Quit whilst connected to a server causes unity crash during quitting

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21302]
Quit the game whilst connected to a server, unity crashes upon exit

I was connected to a local copy of Sea Otter cycle 26 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6274212/Player.log)

**Comment by IcedForge** [comment]
Seems to happen by just opening the client and closing it.

**Comment by MishkaFur** [comment]
> 
> 
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6274332/Player.log)
> Seems to happen by just opening the client and closing it.

It didnt for me, if i load client leave it running for a few min then quit it (clicking the button)

**Comment by SlayksWood** [comment]
#20162

**Comment by SlayksWood** [comment]
Quit buttom is fixed, tried maybe 20 times and never have unity crash. Closed for now.
