### ISSUE TITLE
Unintended mechanic of housing function.

### ISSUE THREAD

**Issue by Tralolol** [StrangeLoopGames/EcoIssues#21312]
Hi, I am quite busy with personal aspirations and responsibilities in life, but I will try to post enough of what I have to display this bug/mechanic I am concerned about for your team to understand/see the issue.

By building "industrial housing" and taking the "sharing walls" to another level, I have figured out how to share rooms with seperate deeds without interfering with the housing bonus/room restrictions. This would allow for me to build a very large industrial house for multiple people at a very efficient cheap cost.

![Deeds](https://user-images.githubusercontent.com/82172525/114067259-3a769900-9862-11eb-8070-d698a7dabaac.png)

You can see here the image of the building I am describing and the separate deeds where the separated residence's will be living for their housing bonus. Now, let me show you the problem on the inside.

![Inside](https://user-images.githubusercontent.com/82172525/114068007-0c458900-9863-11eb-87e5-fefab73d44dd.png)

You can see my character standing in the middle of my house in between the two other of the 3 deeds. You can also see that the deed I am standing on has a kitchen and some furniture placed over my deed, but no walls. If you take a look at the deeds next to the middle one, there is a room with bathroom furniture, and the other room has bedroom furniture. However, I am benefiting from the two side deeds walls, but since the furniture on my deed is only kitchen stuff, I am getting a kitchen room bonus, and the material used on the walls of the outside deeds is technically enclosing my room.

Here is a picture of my kitchen bonus while residency is in the middle.
![Kitchenbonus](https://user-images.githubusercontent.com/82172525/114068115-27b09400-9863-11eb-9154-6bdd997e70fe.png)

now here is a picture of my bathroom bonus (technically for another residence) but I switched over to this residence to display the bug.
![Bedroom](https://user-images.githubusercontent.com/82172525/114068258-5890c900-9863-11eb-964a-85af6b1a91ad.png)

I am not certain, but if I were to guess, I would believe this is not an intended feature of the game, and may be considered a broken mechanic/bug.
If you would like me to elaborate on any of the information, provide more data/screen shots feel free to message me on discord, I am in the Eco official server @tralolol#3295 and my email is kevlev651@gmail.com

**Comment by IcedForge** [comment]
While this is working as intended, i believe it could be triaged for "Do we want this behavior"? Or should rooms require a separator if they are different deeds for a long term plan/solution? ( for updated room calculations ) 
@WeaselDog @D3nnis3n @johnkslg

**Comment by Engimage** [comment]
This is a long term problem for "optimized housing".
I think something like forcing a room to be completely covered by a deed including walls, could fix the issue.
Looking at the shared houses, maybe the room should actually be covered in full but excluding walls, but I would better look at full room coverage

**Comment by SlayksWood** [comment]
dup #12736
