### ISSUE TITLE
[0.9.3.0 beta release-184]Migration:Breaks all titles by missing backup owner

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21310]
Migration of
9.2.4 -> 9.3
Will invalidate all titles since they are missing a entry of the new backup owner field.
Not sure the best way to solve this, perhaps a null check and if so then default to admin?
@serpopov @WeaselDog

**Comment by WeaselDog** [comment]
For now, allow a null check and keep current behavior when this happens: it transfers to everyone. Same behavior as Demographic with null.
