### ISSUE TITLE
[0.9.2.4 Release-156/0.9.3 Release-184]Update visual fire effect of Bakery Oven

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21318]
Build:
- 0.9.2.4 Release-156
- 0.9.3 Release-184

### Issue
Most of the objects that display a fire or burning effect now have some really good flame art/design visual. Except for the Bakery Oven.

Screenshot
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/37ef7cc9-9c77-4083-bf43-c743e657419f)

**Comment by Phlo123** [comment]
Updated the Bakery Oven with better fire effect.
![1.gif](https://images.zenhubusercontent.com/5edf279448c519fc438646f4/5e04c921-ba50-4a41-a755-a70c6e68a660)

**Comment by keegan-o** [comment]
@Phlo123 Bakery Oven now does not appear in-game, check to see if anything you did caused this and fix please!

**Comment by keegan-o** [comment]
Now all object placement seems broken so disregard phlo.
