### ISSUE TITLE
Failure to interact with blocks

### ISSUE THREAD

**Issue by wrosc** [StrangeLoopGames/EcoIssues#21314]
![asdadasd](https://user-images.githubusercontent.com/82184237/114103231-a7208080-98c0-11eb-9bf6-fba076839fc9.PNG)
![dasdsada](https://user-images.githubusercontent.com/82184237/114103246-b1db1580-98c0-11eb-9e24-1b92e2adbfb6.PNG)
![weqeqweq](https://user-images.githubusercontent.com/82184237/114103251-b69fc980-98c0-11eb-9226-f019ccf45e5c.PNG)
Above is a few examples of how some blocks that I placed cannot be interacted with. This is on a server and ive had 3 different people attempt to also interact with it but with no luck. Have only had this issue once and the blocks are still registering as part of the room. Some people on discord suspect this was a collider issue.

**Comment by IcedForge** [comment]
The block in question is "Under Slope Peak" and has broken collision in a specific direction.
![Screenshot_29](https://user-images.githubusercontent.com/24981362/114273341-eca49100-9a19-11eb-9548-caf45ed78601.jpg)

3 directions works fine but the last one to the right is broken
Thank you for reporting this.

**Comment by IcedForge** [comment]
![Screenshot_28](https://user-images.githubusercontent.com/24981362/114273365-0940c900-9a1a-11eb-85a4-dc5f0006fda2.jpg)

**Comment by IcedForge** [comment]
We also got more flat steel graphic display issues on several blocks. Make sure to revise all block forms in all directions to get a full fix on these.
![Screenshot_30](https://user-images.githubusercontent.com/24981362/114273437-4efd9180-9a1a-11eb-92af-6faf7f382466.jpg)

**Comment by Sekor2600** [comment]
Missing Collider is fixed and the Texture from IcedForge Screenshot ( Under Inner Peak )

**Comment by IcedForge** [comment]
Collisions were fixed as well as the missing texture, will create a new one regarding all odd misbehaving ones
