### ISSUE TITLE
Cant start the game ECO - AKSounds crash

### ISSUE THREAD

**Issue by Pompenanna** [StrangeLoopGames/EcoIssues#21311]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6280179/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6280181/Player-prev.log)

When i start to start the game it crashes. Tried reinstall it, restart the computer. Verify the files nothing works.

**Comment by Pompenanna** [comment]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/6280197/error.log)

**Comment by IcedForge** [comment]
Thank you for reporting It is related to a audio problem.
Make sure to update your drivers and please post a dxdiag file as well to help investigate this problem.

```
0x00007FFA47C46AFD (AkSoundEngine) AK::GetWwiseXAudio2Interface
0x00007FFA47B30905 (AkSoundEngine) AK::SoundEngine::WakeupFromSuspend
0x00007FFA47B30F73 (AkSoundEngine) AK::SoundEngine::GetDeviceSpatialAudioSupport
0x00007FFA47B2793F (AkSoundEngine) AK::SoundEngine::GetDeviceList
0x00007FFA47B278EF (AkSoundEngine) AK::SoundEngine::GetDeviceList
0x00007FFA47B86233 (AkSoundEngine) CAkSpeakerPan::GetDecodingMatrixShape
0x00007FFA47B859CB (AkSoundEngine) CAkSpeakerPan::GetDecodingMatrixShape
0x00007FFA47B5A2D7 (AkSoundEngine) AK::MemoryMgr::StartProfileThreadUsage
0x00007FFA47B586E2 (AkSoundEngine) AK::MemoryMgr::StartProfileThreadUsage
0x00007FFA47B7815D (AkSoundEngine) AkTlsSetValue
0x00007FFABF6D7034 (KERNEL32) BaseThreadInitThunk
0x00007FFAC0E02651 (ntdll) RtlUserThreadStart
```

**Comment by IcedForge** [comment]
Will close due to lack of reply, please reopen if you still have this issue and can provide the above mentioned information
