### ISSUE TITLE
[0.9.2.4 Release-156/0.9.3 Release-184]Add toggle switch for Fireplace

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21320]
Build:
- 0.9.2.4 Release-156
- 0.9.3 Release-184

### Issue
Most light-emitting objects that require fuel such as fats, gas, and wood have switches to turn them ON and OFF. Examples are lamps, candles, and such. However, Fireplace objects such as Ashlar Fireplace, Mortared Fireplace, and Brick Fireplace don't have any switch to turn them ON or OFF.

Maybe add one? Would be nice to be able to switch ON and OFF from time to time.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/f9c86ba2-2dfa-4b72-b667-51a7f65b3fb7)

**Comment by WeaselDog** [comment]
Added in 9.6.2
