### ISSUE TITLE
[0.9.2.4 Release-156/0.9.3 Release-184]Lupine appears to be missing even after achieving full growth

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21321]
Build: 
- 0.9.2.4 Release-156
- 0.9.3 Release-184

### Issue
The Lupine plant appears to be missing. Planting it as a seed doesn't show any seedling art design and waiting for it to achieve full growth 100% maturity still shows an empty plot. Disconnecting and reconnecting fixes it.

Note:

- Only happens to the Lupine plant.

Repro:

1. Plant a Lupine seed.
2. Observe.

Actual Result:

- Plot appears to be empty even after planting a Lupine seed.
- Waiting for it to reach full growth still shows an empty plot.
- You have to disconnect and reconnect to fix the issue.

Expected Result:

- Planting Lupine seed should show a seedling art design.

Video Repro:
https://images.zenhubusercontent.com/47210472/b602fdc8-a868-4864-895c-26cb4878df7f/2021_04_09_21_36.mp4

Note: On this video, the fully grown Lupine next to the empty plot where I planted the Lupine seeds was not there before, I mean, it's the first Lupine plant I planted where I discovered this issue. I disconnected and relog in to reproduce the issue. Doing so made that specific Lupine plant show its assets.

**Comment by Jason-Skillman** [comment]
## Cause of issue
Found what was causing the lupine plant to not show up. When you would use the `Lupine Seeds` on farmland the plant was there but the scaling of the instantiated object was incorrectly being calculated in the `PlantGrowth.cs`. The plant was microscopic and could not be seen by the player.

If you zoom in you can start to see the lupine plant
![Inkedsmall_lupin_LI](https://user-images.githubusercontent.com/35405997/117049172-d40a5c80-ace1-11eb-83d7-23d9fe6ad1c1.jpg)

`PlantGrowth.cs` Line 89
```c#
var scale = this.ScaleCurve.Evaluate(this.Age);
```

## Solution
I set the `ScaleCurve` to match the other plants and the plant shows up just fine now.

<img width="653" alt="fix_missing_lupine" src="https://user-images.githubusercontent.com/35405997/117049339-fdc38380-ace1-11eb-80b0-4941fd41a2a5.png">

Only the prefab was changed and no PR was needed.
