### ISSUE TITLE
[0.9.2.4 beta release-156] Cannot swap 2 items with the same name on the repair slot of tool bench

### ISSUE THREAD

**Issue by Lyrcaxis** [StrangeLoopGames/EcoIssues#21335]
1) Carry two Wooden Axe which aren't at max durability
2) Open the Tool Bench and put one of them on the repair slot
3) Try to put the other one on the same slot

Expected result: The Wooden Axe that was dragged to the slot last should be on the slot, while the other is on your inventory
Actual result: 

https://user-images.githubusercontent.com/32474602/114318198-a5e79180-9b14-11eb-9f14-6c0542e96f4c.mp4

Notes: It is possible they swap but the durability isn't updated.

**Comment by WeaselDog** [comment]
This was fixed in update 9.3
