### ISSUE TITLE
USER ISSUE: Car does not respond / cannot interact with Car

### ISSUE THREAD

**Issue by TheRealBrainbug** [StrangeLoopGames/EcoIssues#21330]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
no idea, just happened after exiting my car	

**Expected behavior:**
should be able to target and interact with my Steam Truck

**Actual behavior:**
cannot target, enter, open inventory etc. - the inventory shows up on nearby stockpiles though

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheRealBrainbug** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6290218/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6290219/Player-prev.log)

**Comment by TheRealBrainbug** [comment]
Found some other similar reports. Leaving the server and re-entering did not help, but closing the game and restarting helped. Car interactable again. FYI.

**Comment by IcedForge** [comment]
Thank you for reporting, will close as duplicate and tracking of the issue is over at #20414
