### ISSUE TITLE
[9.4 Develop 250] Property icon strange behavior on map

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21332]
Store & campfire icon showing up on world map despite located at another place.

https://gyazo.com/85cf31ea2ae498af51b1a8afd6cee7cd

**Comment by SlayksWood** [comment]
I guess this is related with https://github.com/StrangeLoopGames/EcoIssues/issues/21766#issuecomment-831865061

**Comment by TwixterZ** [comment]
re-tested on 9.4 Develop 287, issue no longer exist. closing this issue now
