### ISSUE TITLE
[0.9.3.0 beta release-186]Flat Steel textures misbehaving

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21337]
There is some misalignment happening / mirroring that is incorrect for a lot of the flat steel blocks.
All variations of the below, depending on angulation of the block.

- Basic slope corner
- Basic slope turn
- Under slope corner
- Under slope turn

![Screenshot_6](https://user-images.githubusercontent.com/24981362/114367308-9b60e280-9b7c-11eb-88d9-2f6684450283.jpg)

The rest seems fine.

**Comment by keegan-o** [comment]
Very simple fix for this, material just had the wrong mask texture. Applied fix to release branch.
