### ISSUE TITLE
[0.9.3 release-186] Color point is offseted in marker.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21338]
Step to reproduce:
- place any marker and want to chenge its color:
![image](https://user-images.githubusercontent.com/45708377/114381877-58126e00-9b94-11eb-8d67-e982f5866017.png)
- bottom left position:
![image](https://user-images.githubusercontent.com/45708377/114381957-711b1f00-9b94-11eb-9ece-0cc76742db67.png)
- top right:
![image](https://user-images.githubusercontent.com/45708377/114382021-86904900-9b94-11eb-89ad-8235d09e8e79.png)
- the position must be inside the whole color square

**Comment by TwixterZ** [comment]
This issue is now fixed in latest develop build
