### ISSUE TITLE
Make string extractor warn about unstranslated strings

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21331]
I came across this in the code randomly: 
![image](https://user-images.githubusercontent.com/3536496/114285715-2ec7d580-9a0e-11eb-9ce5-965eeb2768c3.png)
Untranslated strings, which are pretty rare, and if we're only relying on QA to find these as untranslated before they get fixed they will take ages to repair. 

We need an overfix for detecting strings that should be translated but arent.  Augment the string extractor to detect strings that are likely untranslated, and list a bunch of warnings.  This could simply look for untranslated string literals with letters in them.

While youre doing that, you can also detect translated strings with bad characters in them: tags, leading/trailing spaces, etc.

You may want a system to tag valid cases in the code that are erroneously generating a warning.

**Comment by gabrielgindridev** [comment]
Possible improvements:

## 1. Display all literal strings (with valid text and not localized)
save a report containing each string, file name, line

Finding all string literals and ignoring comments ones (regex): https://vosseburchttechblog.azurewebsites.net/index.php/2014/12/16/find-all-string-literals-in-c-code-files-but-not-the-ones-in-comments/

**pros:** won't rely only in QA to spot missing localization
**cons:** manual check, can take a lot of time, especially if used in every localization process

## 2. Usage of extensions to isolate/help manual check

### Setting normal string
```
for (int i = 0; i < 10000000; i++)
{
    _ = "abcdfg";
}
```
10 samples: 20~21ms

### Setting from static func
```
using static NoLocTest;

for (int i = 0; i < 10000000; i++)
{
    _ = NoLoc("abcdfg");
}

public static string NoLoc(string s) => s;
```
10 samples: 24~26ms


### Setting from extension

```
for (int i = 0; i < 10000000; i++)
{
    _ = "abcdfg".NoLoc();
}

public static string NoLoc(this string s) => s;
```

10 samples: 24~26ms

pros: narrows down the number of strings to search (we can exclude strings with this tag), making it easier to spot missing localization
cons: affects performance and can bloat code. Does not rule out human error, still possible to use it wrong, and would still rely on QA to check these cases.  

## 3. Detect bad localization
detection for tags, leading/trailing spaces/whitespace in localized strings

**Comment by Quadbro** [comment]
First one looks good, also we can make a pseudo remembering system (file that will track the ones we need to ignore, same like prefab localizer work) should be preatty easy to even add a UI for that (can reuse old one) 
@johnkslg What do you think?

**Comment by johnkslg** [comment]
Instead of calling a function, how about just a comment tag for the stringextractor of //noloc at the end of the line.

**Comment by gabrielgindridev** [comment]
Possible improvements:

## 1. Tweak StringExtractor to display all literal strings (with valid text and not localized)
save a report containing each string, file name, line

Finding all string literals and ignoring comments ones (regex): https://vosseburchttechblog.azurewebsites.net/index.php/2014/12/16/find-all-string-literals-in-c-code-files-but-not-the-ones-in-comments/

## 2. Using comments to clear/isolate manual check
use // noloc or /*noloc*/ in solution 1 to decrease number of strings to look

## 3. Detect bad localization
detection for tags, leading/trailing spaces/whitespace in localized strings
