### ISSUE TITLE
USER ISSUE: Fuel supply used as resource and storage

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#21352]
\
**User Id: (slg140915)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
V0.9.2.4
Place a workbench and stone brazier on a claimed ground.
Put some fir logs (10) in the brazier.
Start a project hew log on workbench.

**Expected behavior:**
a project should not be able to start because there are no resources.

**Actual behavior:**
fir logs are taken from brazier and hew logs are put back.
Same with campfire and possibly other devices.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Nicolausi113 Thank you for the report. merged to #20793
