### ISSUE TITLE
Spawning civics not updating room tier for objects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21358]
type /civics spawngov
Notice that the objects are disabled because they think the room tier is 0 but it shows 1 in the status panel:
![image](https://user-images.githubusercontent.com/3536496/114621637-ca9d4f80-9c61-11eb-8a57-cefa73303bc0.png)

Removing and adding a block didnt fix it.

Figure out what broke in addition to fixing this.

**Comment by Moritur** [comment]
It's not about room tier. Object in the screenshot thinks it's not inside any room
![image](https://user-images.githubusercontent.com/44618240/115389185-1198c100-a1dd-11eb-852f-df016e5ee564.png)

**Comment by tuha263** [comment]
This happens because the object was spawned out of the room.  Seem it happen because some change in the object's occupancy

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 266
