### ISSUE TITLE
CI Tests Failure only causing Warnings

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21350]
When a CI Test is failing, this is only causing a warning in Jenkins. This should cause an error and cause the CI Test to fail, along with the exception appearing as a comment on the PR.

PR with failed test: https://github.com/StrangeLoopGames/Eco/pull/8295
Log from Jenkins:
> 17:34:21  [12:34:21] Running test craftfailtest
17:34:21  Warning: Exception Caught in Test craftfailtest - System.Exception: TEST FAILED AS IT SHOULD
17:34:21  Taking 1.7ms
17:34:45  Finished testing with 1 exceptions.
17:34:45  Warning: Exception Caught in Test craftfailtest - System.Exception: TEST FAILED AS IT SHOULD

**Comment by mirasrael** [comment]
run tests

**Comment by mirasrael** [comment]
fixed in develop
