### ISSUE TITLE
USER ISSUE: Stealing from chest bug - Contracts

### ISSUE THREAD

**Issue by atillathehungry** [StrangeLoopGames/EcoIssues#21359]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Player A creates a contract on a contract board that requires player B to accept and then deposit an item into a chest.
2. Chest must have all item slots full
3. Player B tries to deposit the requested item into the chest and puts it into a slot containing an item belonging to Player A. Player B then receives that item from player A's chest. 
4. Player B is me in the log and I was putting bison into the shop owners chest

**Expected behavior:**
It should not have allowed Player B to receive Player A's item since player B is not normally permitted to take things from player A's chest as it is not stipulated in the contract. The contract is supposed to only authorize player B to place things into player A's chest and not take from it. 

**Actual behavior:**
It allowed Player B to take whatever they wanted from Player A's chest as long as they were putting an item in that fulfilled the contract.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6307129/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6307130/Player-prev.log)

**Comment by TwixterZ** [comment]
This is no longer an issue on our latest develop iteration. 
@atillathehungry if you still having similar issue, please let us know! =)
