### ISSUE TITLE
[0.9.4.0 develop] Excavator spamming dig action when unable to dig a block

### ISSUE THREAD

**Issue by Moritur** [StrangeLoopGames/EcoIssues#21351]
**Reproduction steps**

1.  Place an excavator next to a tree
2. Enter it and switch to dig mode
3. Place the scoop on top of a dirt block next to the tree
4. Don't move mouse or press any keys and wait for ~2 seconds

Expected behavior: Error message will appear only once
Actual behavior: Error message will be spamming until you move the scoop

If those reproduction steps don't work for you then try using setup presented on this video

https://user-images.githubusercontent.com/44618240/114514632-c827ff00-9c3b-11eb-8af2-8a7fb4d2e506.mp4

This issue was discovered in https://github.com/StrangeLoopGames/Eco/pull/8272 PR, but it existed before, it just wasn't so easy to spot. 
The issue here is not just error spamming in UI, but server being spammed with dig action that fails each time.

**Comment by IcedForge** [comment]
Need to check civics debug and see if it runs a check for each of these messages, if it does repeat action infinite we might want to bump priority as it could have some significant impact on servers using dig/place laws.

**Comment by Moritur** [comment]
> Need to check civics debug and see if it runs a check for each of these messages, if it does repeat action infinite we might want to bump priority as it could have some significant impact on servers using dig/place laws.

I looked into the code behind this and it turns out that if digging a block is prevented by tree roots it fails before reaching laws, auth, contracts etc.
