### ISSUE TITLE
[0.9.3 Release-189]Inconsistent Call Post activation distance for Elevators

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21353]
Build: 0.9.3 Release-189

### Issue
This issue is just for uniformity. For Wooden Elevator, the call post can be activated as far as 9 blocks away for North, 12 blocks away to South, 9 blocks away to East, and 12 blocks away to West. However, for the Industrial Elevator, the call post can be activated within the 12 blocks distance to North, 1 Block to South, 5 Blocks to East, and 12 Blocks distance to West. Noticed that the South portion side of the Industrial Elevator only allows 1 block away distance to link with a call post. At 2 blocks, the call post doesn't link with the elevator. That's a significant number of blocks distance for the Industrial Elevator.

Repro:

1. Set Industrial Elevator. Best to spawn it via /test industrialelevator
2. Set a call post at the south section of the elevator about 3 blocks away from the elevator.
3. Observe.

Wooden Elevator Call Post Distanct Activate
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/b2b01dda-e137-4e86-893c-42a986d9c731)

Industrial Elevator Call Post Distance Activate
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/e8ece499-132d-4187-97da-750036aafe3f)

Screenshot Number 2
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/ac10d331-46cc-4ad9-ba1c-89bafe1fc779)

**Comment by SlayksWood** [comment]
merged to #20740
