### ISSUE TITLE
[0.9.3.0 beta release 189]Property transfer caches ownership of objects until server restart

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21364]
Reproduction
1.Transfer property(vehicle for example) to another user.
2. Now open inventory / components and test add users or transfer items 

The deed is transferred correctly and sets permissions and i can not interact with it and works as intended
but i still have ownership of the item itself, giving me permissions to add users or remove/take items until a server restart takes place.

**Comment by SlayksWood** [comment]
check this one after fixes #16384

**Comment by tuha263** [comment]
I can't reproduce it, maybe that build doesn't have the PR from staging.
![VehicleOwner](https://user-images.githubusercontent.com/9598614/119641491-e9d3f300-be43-11eb-80ae-c353f0e2ff63.png)

**Comment by SlayksWood** [comment]
Checked on staging-1993, seems fixed.
