### ISSUE TITLE
[0.9.3 Release-194]Sewage: Update Sewage entry in Ecopedia

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21365]
Build: 0.9.3 Release-194

### Issue
The Sewage entry in Ecopedia somehow contains Constitution content which was the same content removed for #20905.

![image](https://user-images.githubusercontent.com/45708377/114823575-5fbc5780-9dcc-11eb-9db3-a31ea5ab17d3.png)

Additionally, I think it's better to just remove the images inside the green highlight box. Sewage entry does not contain much information and should be displayed similarly to how the Power entry is configured.

Power Entry in Ecopedia
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/fbfe27f0-7936-4857-a9d9-ae38c0e4b082)

**Comment by SlayksWood** [comment]
Can't see first image, so add another one
![image](https://user-images.githubusercontent.com/45708377/114821890-ecb1e180-9dc9-11eb-8a5f-a8b062b1ee04.png)

**Comment by Daniel-Magulado** [comment]
Odd, first image is showing on zenhub. 

https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/21365

**Comment by WeaselDog** [comment]
There is a bug here that Ecopedia entries with no text have this phrase appear. I have deleted most of them but this, which is just an image with no text.
