### ISSUE TITLE
[0.9.3 Release-194/0.9.4 Develop-252]Issues connecting pipes when Water Pump is turned ON.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21366]
Build:
- 0.9.3 Release-194
- 0.9.4 Develop-252

### Issues
When trying to connect Pipes to a Water Pump output when it's powered ON, the pipes end up being disconnected. Furthermore, if you already have a current Pipe connection layout and you will be making an update or changes to it, doing so while the Water Pump is turned ON causes pipes to disappear. This issue also prevents any pipes to be connected to the Water Pump output.

Observe this video recording:
https://images.zenhubusercontent.com/42199084/4e31e40d-8f92-454a-a920-4d576930d2a9/2021_04_14_23_06_trim__2_.mp4

However, if you turn off the Water Pump, you are unable to connect any pipe from the output of the Pump. This can be fixed by connecting another pipe.
![1](https://user-images.githubusercontent.com/77248866/114823394-1123b300-9df6-11eb-8544-ca3f2381b334.jpg)

Lastly, if you already have existing pipe connections, making an update to your pipe connecting while the Water Pump is powered ON causes some pipes to disappear or vanish. Like it's been deleted.
https://images.zenhubusercontent.com/42199084/e1e942f9-a27d-49e9-b715-6f07f0e0085d/2021_04_14_23_11.mp4

### Note

- Issues can be reproduced on both stated builds.
- Issues can be reproduced with Wooden Water Pump and Electric Water Pump.
- Issues can be reproduced with Iron Pipe, Steel Pipe, and Copper Pipe.

**Comment by Daniel-Magulado** [comment]
User Report: #21374

**Comment by SlayksWood** [comment]
need to check with smog too.

**Comment by shakee2** [comment]
To add this: This also happens with the furnace smog out pipe. If the work stops, the end pipe with its open end will vanish and may break your production.

**Comment by Daniel-Magulado** [comment]
Closing as it is fixed. Tested on 0.9.3.1 Release-204.

This includes pipe connection for Smog, Sewage output, and Water Pumps.
Will keep an eye and will reopen if the issue is encountered again.
