### ISSUE TITLE
[0.9.4 Develop-254]Food Tutorial: Food Pie Chart animation expands the Pie instead of shrinking it

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21372]
Build: 0.9.4 Develop-254

## Issue
During the Food Pie Chart introduction where the Pie is supposed to shrink when calorie is mentioned, just before the start of the Food tutorial, expands the Pie instead.

### Repro
1. Complete tutorials until Food tutorial.
2. Observe the introduction of the Food Pie.

### Actual Result
![Pie Chart 2](https://user-images.githubusercontent.com/77248866/114845467-5ce25680-9e0e-11eb-8dd4-57746ff21a9a.gif)

### Expected Result:
![Pie Chart 9-33](https://user-images.githubusercontent.com/77248866/114845491-6370ce00-9e0e-11eb-8a74-9cfa38db56b6.gif)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 266
