### ISSUE TITLE
9.3 Skill Icon

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#21378]
![grafik](https://user-images.githubusercontent.com/37456949/114856954-fea27d00-9de7-11eb-923c-7197711e39f1.png)

False Icon for Tailoring

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/114860819-23e9b800-9df5-11eb-901b-3f86f99fb07a.png)

**Comment by madpingui** [comment]
It's fixed on 9.4 develop unity editor
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/ab3bf866-5812-42d1-a01a-5757b3675aa0)

**Comment by TwixterZ** [comment]
fix checked and confirmed as of 9.4 Develop 266

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ed159da4-2157-4e5d-adf5-c6ee8897afa2)
