### ISSUE TITLE
[0.9.3.0 beta release-194] USERISSUE Pipes acting strange

### ISSUE THREAD

**Issue by dterbeest** [StrangeLoopGames/EcoIssues#21374]
Hello Devs,

Placing pipes connected to water makes the pipe piece disappear. What we found so far is that when you place 1 piece of pipe connected to a water source it will either not align correctly, or work fine. When you attach another pipe the first pipe will disappear (and sometimes the second one disappears as well)

I will update as we find out more about this issue, for now we tested with both iron, copper and steel pipes.
Pipes not connected to a watersource seem to behave as expected

Removing previously existing pipes (placed pre 9.3 update) will make a bunch of them disappear (you get 1 in your inventory, but 6 pipes were removed in our case)

Thanks in advance for looking into this. Please let me know if you need more info

**Comment by dterbeest** [comment]
update: this issue only occurs when there is water flowing through the pipes, turning the pump off allows us to edit pipes like normal

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. We are already aware of this issue.
Closing this ticket and merging it with the existing one.
https://github.com/StrangeLoopGames/EcoIssues/issues/21366
