### ISSUE TITLE
[9.3 194] Advanced Tailoring Table bugged out

### ISSUE THREAD

**Issue by Vogeldreck** [StrangeLoopGames/EcoIssues#21377]
![Eco Screenshot 2021 04 15 - 12 08 26 02](https://user-images.githubusercontent.com/82581318/114856198-1decda80-9de7-11eb-998d-64440ee9198a.png)

Was messing around whit the new Stuff and after a while the Table bugged out and you can't do anything whit except replacing it.

**Comment by SlayksWood** [comment]
@Vogeldreck Thank you for the report. Can your provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Does it happens after game restart?

**Comment by Vogeldreck** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6317469/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6317472/Player-prev.log)


> Does it happens after game restart?
No.

**Comment by IcedForge** [comment]
Seems like a very unique conditioning, so far havent been able to replicate. Will close for now please reopen if you run into this post 9.3.3
