### ISSUE TITLE
USER ISSUE: Title Owned store says it is disabled after 9.3 patch

### ISSUE THREAD

**Issue by missilerock** [StrangeLoopGames/EcoIssues#21375]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
1. Land is owned by the title 'Treasure Panda'. Same for store on the deed before the patch hits.
2. Patch hits
3. Store says it is disabled.
Tried; Picking up and dropping, crafting a new store, opening and closing, confirming it is set to the right account, confirming auth is set to everyone. I am still Treasure Panda at this time too.

**Expected behavior:**
Let people sell land claim papers for 80$

**Actual behavior:**
Store is disabled when they try.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
This is on the official Giant Panda server. Store in question is at the deed 'BankLand'. There is another store at 'BankLand2' but that one probably also doesn't work.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting
Does the title itself have authorization to the bank account it is using ?

**Comment by missilerock** [comment]
The title Treasure Panda should have access to Government accounts. The account says it is a government one at least. I am able to transfer money in the TreasurePandaFund to another player so I assume that the title is still giving me access. The title is the sole manager of the TreasurePandaFund,  

I haven't seen anyone selling landclaims to the store since the patch so I am assuming that this is still an issue. Apologies for delayed response.

**Comment by IcedForge** [comment]
This should have been fixed with the 9.3.1/9.3.3 update please feel free to reopen if its still an issue sorry for not getting back earlier.
