### ISSUE TITLE
9.3 194 - Unable to shift drag between stockpiles

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21370]
As per title, unable to shift drag between stockpiles IF the item is already in the other one ie granite in the pic below but sand is fine

![image](https://user-images.githubusercontent.com/61889138/114840950-3b15af00-9dcf-11eb-92bc-def8b029676a.png)

![image](https://user-images.githubusercontent.com/61889138/114840973-41a42680-9dcf-11eb-87c5-62d5c13704f5.png)

**Comment by MentalMonk** [comment]
Move a stack from one slot to another slot in the stockpile splits by max carry limit (10).  Bulk transferring from Stockpile to stockpile transfers maxcarry (10).  Bulk transferring to cart then to stockpile does the full weight transfer, bulk transferring from cart to stockpile transfers the entire carts weight.  All stockpiles are affected.  Admin weightless inventory acts the same way as cart and can bulk transfer without error. Bug is not block dependant. Bug seems restricted to blocks only ie. inventory items do bulk transfer without error.

![image](https://user-images.githubusercontent.com/81957057/114860704-ee59c480-9e1e-11eb-8965-c70f369d5b23.png)
