### ISSUE TITLE
[0.9.4 Develop-254]Missing Arm animation for the Avatar.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21380]
Build: 0.9.4 Develop-254

## Issue
The Avatar's Arms doesn't play any form of animation including running, jumping, and use of tools. Driving works as intended though.

### Repro:
1. Play the game using the said build.
2. Change camera view to 3rd person via F5.
3. Run, Jump, Walk, Swim, and use some tools. Observe as well while at it.

### Actual Result - Steady still arms with no animation
https://images.zenhubusercontent.com/47210472/33333661-a039-44b6-ba46-4e689cb8cd8f/2021_04_15_18_56_trim.mp4
### Expected Result - Arms has appropriate animation to each action
![Arms animation 3.gif](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/6d270a1f-54fb-41b2-9086-95cb80010c19)

If images don't load, please view at https://app.zenhub.com/workspaces/qa-5f8154006cdb830012c16d10/issues/strangeloopgames/ecoissues/21380

**Comment by MazonDel** [comment]
This was corrected by setting the Emote-Layer's "Blending" setting to Additive. Commit sent to the SVN.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 266

https://images.zenhubusercontent.com/47210472/d7ca859a-449e-476c-bf0a-885bbcd9235e/035acc06e3024f3395d55fb7b6c25557.mp4
