### ISSUE TITLE
[0.9.4 develop-254] Missing some Graphics setting

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21386]
![image](https://user-images.githubusercontent.com/45708377/114868252-619f0e80-9dfe-11eb-8329-c76760a6bfb2.png)
0.9.3:
![image](https://user-images.githubusercontent.com/45708377/114868338-754a7500-9dfe-11eb-9ad4-361a1035f351.png)

**Comment by ptitducanh** [comment]
Is this a AMD thing? because I'm running on develop with a Nvidia and it's all good.
@SlayksWood

**Comment by SlayksWood** [comment]
No, I have nvidia too, second screenshot was maden in another PC to not switch version. Seems it was fixed:
![image](https://user-images.githubusercontent.com/45708377/116878830-90075100-ac28-11eb-9f88-d1686e316e0b.png)
