### ISSUE TITLE
Stockpiles annoying to place

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2138]
Highlight is really hard to see
![image](https://user-images.githubusercontent.com/3536496/30506447-d845d6ca-9a30-11e7-8f61-a8417b85b69e.png)

**Comment by keegan-o** [comment]
@metachronism Do you think there will be a way to add a subtle overlay of a cube of the occupancy of placed objects? Otherwise for this, I suppose I could have the dirt on the bottom of the stockpile be part of the object, but that could end up a bit weird.

**Comment by keegan-o** [comment]
Added a dirt cube to them to make them easier to place.
