### ISSUE TITLE
[9.3] Pipes disappearing

### ISSUE THREAD

**Issue by EBaalhuis** [StrangeLoopGames/EcoIssues#21395]
The Iron Pipe that is the chimney on a Cement Kiln keeps disappearing. It makes the chimney invalid (kiln stops working), so it is not just invisible. The pipe is nowhere to be found.

**Comment by mkoeppen** [comment]
I have the same issue with with all pipes (not only on cement kiln). 
Some pipes were missing. Therefore I tried to replace this pipes but then the pipe next to it disappear.

**Comment by ZeUnlucky** [comment]
Turn off the machine before placing pipes. There's an open issue on this already

**Comment by SlayksWood** [comment]
@EBaalhuis @mkoeppen Thank you for the report. It should be fixed in next hotfix
merged to #21366
