### ISSUE TITLE
USER ISSUE: I got kicked out of a server

### ISSUE THREAD

**Issue by Gpeg007** [StrangeLoopGames/EcoIssues#21396]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
I was looking through the economy interface for Hardwood Hewn Logs, Hewn Logs, and Softwood Hewn Logs and had them sorted by distance. I moved my mouse to the search bar to search for something else, got a phone call, ignored it, and returned to the title screen asking if I would like to report a bug

**Expected behavior:**
I expected to not be kicked out of a server to the title screen

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and Idk

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Gpeg007 Thank you for the report. this issue should be fixed in next hotfix.
merged to #21162
