### ISSUE TITLE
USER ISSUE: Crashes frequently usually when clicking something

### ISSUE THREAD

**Issue by reubenjohn** [StrangeLoopGames/EcoIssues#21399]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Play the game normally, and every 30min or so, when you click something the game will crash	

**Expected behavior:**
It should not have crashed.

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
The admins said no mods were installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@reubenjohn Thank you for the report. this issue should be fixed in next hotfix.
merged to #21162
