### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by StrikeZoneZero** [StrangeLoopGames/EcoIssues#21398]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Opening up the list of for sale goods on the server and sorting by amount for sale.

**Expected behavior:**
Ability to browse selected wares.

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@StrikeZoneZero Thank you for the report. this issue should be fixed in next hotfix.
merged to #21162
