### ISSUE TITLE
USER ISSUE: Ошибка

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#21392]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Зайти на сервер

**Expected behavior:**
начать играть

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
чистый клиент

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21382
