### ISSUE TITLE
USER ISSUE: continual failed to handle rpc response

### ISSUE THREAD

**Issue by Mel724Games** [StrangeLoopGames/EcoIssues#21393]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
not sure happens randomly

**Expected behavior:**
not crashed?

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, still happens with no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Mel724Games** [comment]
it won't let me attach the log files...

**Comment by SlayksWood** [comment]
@Mel724Games Thank you for the report. this issue should be fixed in next hotfix.
merged to #21162
