### ISSUE TITLE
USER ISSUE: Bug while building

### ISSUE THREAD

**Issue by GrimmMachine** [StrangeLoopGames/EcoIssues#21390]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
1. Building tool in hand
2. Hewn Logs
3. Wall Selecteld
4. Building Quickly

**Expected behavior:**
Client Crashes

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21382
