### ISSUE TITLE
USER ISSUE: Bug when browse Y panel

### ISSUE THREAD

**Issue by Jhynx** [StrangeLoopGames/EcoIssues#21397]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Open Y panel, then filter by price, and scroll down

**Expected behavior:**
Shut down

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Jhynx Thank you for the report. this issue should be fixed in next hotfix.
merged to #21162
