### ISSUE TITLE
Void Storage issues

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21407]
1. The window is too small, cannot be resized or scrolled within and items lower down the list do not move up when upper ones are taken, e.g. you have no access to them at all.
2. Void storage can only be accessed in a extremely limited area (one block) that also might be inaccessible. This needs to become a bigger area.

**Comment by D3nnis3n** [comment]
The first is critical to me, the second is not.

**Comment by SlayksWood** [comment]
> I am currently on a modded server "Redemption - An Eco Story" and I was on a friends residence plot. I eventually began to create my own house and only set up a tiny stock pile at the new location. I left the residence and all my items that I have ever added to his plot went into the void storage. There were roughly 400+ items and I was only able to access the first 17.5 rows as this new window that opens into the void storage is vertical and has a width of 5ish rows horizontally. Please let me know if you need me to provide more information.

**Comment by SlayksWood** [comment]
fixed in staging, have scroll and can resize:
![image](https://user-images.githubusercontent.com/45708377/116356608-2b9d5980-a804-11eb-8ae3-7a2fafff98ca.png)
![image](https://user-images.githubusercontent.com/45708377/116356618-2f30e080-a804-11eb-8035-ce31e79196f6.png)
need to merge in release.
