### ISSUE TITLE
USER ISSUE: Lumber Door Recipe differs by type [hardwood/softwood/normal]

### ISSUE THREAD

**Issue by missilerock** [StrangeLoopGames/EcoIssues#21404]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Craft a hardwood lumber door VS a softwood lumber door VS a regular lumber door.

Regular lumber door recipe is 4 lumber and 8 boards.
Hardwood lumber door; 2 lumber and 6 nails.
Softwood lumber door; 2 lumber and 6 nails.

https://imgur.com/CxZ5SgG

**Expected behavior:**
All of the recipes should cost the same [other than the lumber type required].

**Actual behavior:**
The hardwood and softwood versions of the lumber doors are cheaper to make / not consistent with the regular version of the door.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, this is vanilla eco. Can try it on one of the official servers if you want.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@missilerock Thank you for the report. 
merged to #20875
