### ISSUE TITLE
Modules in workbenches will not go to void storage on eviction but be destroyed

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21408]

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-274.


Upgrades are now stored in void storage once evicted from rented space.
However, this fix might have caused another issue.
I wasn't actually able to place the module the normal way. I did a workaround by placing the table and module before giving the property to another account.
I created it here #21711

**Comment by Moritur** [comment]
> However, this fix might have caused another issue.
> I wasn't actually able to place the module the normal way. I did a workaround by placing the table and module before giving the property to another account.

Issue https://github.com/StrangeLoopGames/EcoIssues/issues/21711 was present before I fixed https://github.com/StrangeLoopGames/EcoIssues/issues/21408
