### ISSUE TITLE
USER ISSUE: Excavator Storage

### ISSUE THREAD

**Issue by RaphaelBalse** [StrangeLoopGames/EcoIssues#21402]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
1. Use excavator2. Open it3. No storage

**Expected behavior:**
You can open excavator storage

**Actual behavior:**
You can't acces to excavator storage

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
This change / alteration also does not extend to skid steer, so now we are in a weird limbo stage between what everyone used and now something that was removed without any explanation and only affects the excavator and not the skid steer.

While i agree with that it is a change towards a more direct interaction gameplay elements and not just UI hopping it needs to be consistent and applied on all elements around it.
