### ISSUE TITLE
Skillpoint view settings reset in UI after relog

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#21406]
Version 9.2.4 and 9.3.0
When restarting connection to server, the view of skillpoint in the UI is reset to default settings.

To reproduce:
![Step 1](https://user-images.githubusercontent.com/82637840/114982342-9d35e900-9e8f-11eb-828d-fc089c44f66f.png)
![Step 2](https://user-images.githubusercontent.com/82637840/114982335-9a3af880-9e8f-11eb-9f05-0c6551dbafda.png)
![After relog](https://user-images.githubusercontent.com/82637840/114982338-9c04bc00-9e8f-11eb-86ec-ef58e937f435.png)

**Comment by SlayksWood** [comment]
@M3n5ch Thank you for the report. This is known issue. merged to #21268
