### ISSUE TITLE
USER ISSUE: Pipes disappearing 

### ISSUE THREAD

**Issue by DatPlatypus** [StrangeLoopGames/EcoIssues#21401]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Place pipeline starting from polluter.
Start crafting.

**Expected behavior:**
Nothing should happen (pipe at end stays).

**Actual behavior:**
Pipe at end of the line disappears and doesn't go to any stockpile.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files.**
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6321270/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6321271/Player.log)

**Comment by learntheirtools** [comment]
The same. Tried steel and iron pipes, any of them disappears as soon as smoke starts to come out

**Comment by SlayksWood** [comment]
@DatPlatypus Thank you for the report.
merged to #21366
