### ISSUE TITLE
Smith clothes should not have Nylon!!!!

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#21405]
I was just going through and looking at the new tailoring recipes tonight, and I was shocked to see that nylon fabric was included in some of the smith clothing.  As blacksmith myself, I can say from personal experience that you NEVER want to be wearing most synthetic material when working with a forge.  I know there are non-organic heat resistant gloves out there (like Kevlar and fiberglass), but those are not nylon.

Anyway, at the very least, I would recommend at least replacing the nylon from the Boots and Bandana recipes.

**Comment by WeaselDog** [comment]
Thank you for the feedback. We will make some adjustments here.

**Comment by MishkaFur** [comment]
Should they have some leather too perhaps? cotton leather combo?

**Comment by Hydrohawk** [comment]
> 
> 
> Should they have some leather too perhaps? cotton leather combo?

Most have leather in them already.  The problem is the "fabric" used is nylon.

In reality, cotton or wool would both be reasonable replacements.   Heck, even fiberglass in the gloves would probably work, as variants of fiberglass have been used in some high-heat gloves.
