### ISSUE TITLE
Create example of CustomBlockSet mod and publish on Wiki

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#21416]
* Check if @redwyre example is working
* Fix it if necessary 
* Publish it to Mods wiki as example

Also should fix https://github.com/StrangeLoopGames/EcoIssues/issues/18879

**Comment by thetestgame** [comment]
A "working" example has been made however it has highlighted an issue different then the original issue found at https://github.com/StrangeLoopGames/EcoIssues/issues/18879
