### ISSUE TITLE
[0.9.3.1 Release-204]Ecopedia: Crafting page showcases UI crafting table with no time unit

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21417]
Build: 0.9.3.1 Release-204

## Issue
The Crafting page in Ecopedia displays the UI of the Electric Machinist Table. However, the crafting time doesn't have any unit measurement such as Seconds "s" or Minutes "m." It only displays a number which is confusing.

#### Repro:

1. Open Ecopedia.
2. Search Crafting Entry.

#### Actual Result
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/ad8bb7cf-e6fa-4c53-b26c-c660e8a30676)

#### Expected Result
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/7c560e67-33d7-4c29-933b-292e0b69d7ef)

**Comment by IcedForge** [comment]
Which branch was this fixed on? staging? develop? ( 9.4? )

**Comment by Daniel-Magulado** [comment]
Tested on the following builds:
- 0.9.4 Develop-268
- 0.9.3.3 Release-219
- 0.9.3.2 Staging-1980

The issue still persists. 
Reopening.

**Comment by gabrielgindridev** [comment]
Just checked `develop` in the editor:
![image](https://user-images.githubusercontent.com/65634950/116717633-7e674480-a9af-11eb-8445-4c540153f090.png)

Maybe SVN wasn't updated in the build?

**Comment by WeaselDog** [comment]
Will be redone cleaner on develop, but SVN update on release will get us fixed until then.
