### ISSUE TITLE
Wrong System requirements for Linux, took from Unity page

### ISSUE THREAD

**Issue by JanzenJohn** [StrangeLoopGames/EcoIssues#21410]
The Unity engine on Linux does need gnome running as the Desktop Enviroment to function

This could be turning players away that don't want to run gnome on their system
(To be fair Linux users that don't use gnome and are Eco players are probably not many)

The requirement is in reality gtk [Gimp Toolkit] that is used for most gnome UI

How do I know this ?
I'm not running gnome / only using gtk for theming my install, and it runs

+ [I don't have gnome installed at all]

I know this is taken from the Unity page for system requirements, and I have contacted Unity support.
Still wanted to have this changed here, as you are probably faster with this.

Why is this relevant ?
For most users of other Desktop Enviroments, Gnome looks ugly and uses too many system resources.

**Comment by D3nnis3n** [comment]
We do not officially support either Linux nor Mac - the system requirements are hence not valid for them, as we don't support those OS at all.

What exactly are you seeking?

**Comment by D3nnis3n** [comment]
I guess youre not talking about the system requirements on website or steam? Those don't mention gnome at all.

**Comment by JanzenJohn** [comment]
https://github.com/StrangeLoopGames/EcoIssues/wiki/Eco-on-Linux-(0.9.0.x)

I was talking about this page, on this repo

**Comment by JanzenJohn** [comment]
> We do not officially support either Linux nor Mac - the system requirements are hence not valid for them, as we don't support those OS at all.
> 
> What exactly are you seeking?

Wierd, I could install it on steam without any compatibility layer (aka runs native)

**Comment by IcedForge** [comment]
Just to clarify, We do not support it does not mean we do not offer a linux / mac client however any issues these may have outside of the game specific issues that is not a side effect from the OS client itself is not expected to be worked on in the same priority.

**Comment by D3nnis3n** [comment]
I added a note with link to this issue.
