### ISSUE TITLE
[0.9.3,1 Release-204]Treasury UI: Text Exceeds Button Border

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21419]
Build: 0.9.3.1 Release-204

## Issue
The words **Manage** and **Dump** found inside the _Treasury UI_ exceeds the button border.

#### Repro:
1. Interact with Treasury Table.
2. Observe.

#### Actual Result
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/ef2aa58f-94a0-4c0b-95a2-b9797ca030e4)
#### Expected Result
The words **Manage** and **Dump** found inside the _Treasury UI_ should not exceed the button border and should be properly centered.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/5698def4-19ab-44e8-a665-a55fae40abe0)

**Comment by SlayksWood** [comment]
Still and issue with Dump:
![image](https://user-images.githubusercontent.com/45708377/116844941-2fa6ee00-abed-11eb-96f1-d9edfea9065c.png)
Also font size of "Dump" and "Manage" should be the same.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-281.

Closing, issues is fixed.
