### ISSUE TITLE
9.3 194 - Large amount of objects in tooltip, cannot see entire list of objects

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21412]
Cannot see the entire list of  "And XYZ more objects"

its only showing around 100 or so :D

![image](https://user-images.githubusercontent.com/61889138/115006654-0d009f80-9ea1-11eb-943e-0fd4a5a12d68.png)

![image](https://user-images.githubusercontent.com/61889138/115006741-20136f80-9ea1-11eb-8af4-5dbbaa2e986d.png)

**Comment by SlayksWood** [comment]
At least seems it display all objects in Ecopedia:
![image](https://user-images.githubusercontent.com/45708377/115009772-4b07be80-9eb5-11eb-8ec5-e2f845cf900d.png)
