### ISSUE TITLE
USER ISSUE: Economy Viewer Crash

### ISSUE THREAD

**Issue by KlausT** [StrangeLoopGames/EcoIssues#21413]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
Open Economy Viewer
Sort by name
scroll down
crash

**Expected behavior:**
scroll down

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6325069/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6325070/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. However, we are currently aware of the issues happening when scrolling the Economy viewer.
A fix will be implemented in the upcoming updates.
Merging with #21385.
