### ISSUE TITLE
USER ISSUE: Lag

### ISSUE THREAD

**Issue by RaphaelBalse** [StrangeLoopGames/EcoIssues#21428]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
1. play2. Lag(Same computer client/server)

**Expected behavior:**
No error

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6328282/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6328283/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of the issues going on with the "Failed to Handle RPCResponse" error and client crashes that go with it.

Linking this ticket to #21162.
