### ISSUE TITLE
USER ISSUE: von nitroda

### ISSUE THREAD

**Issue by Darki23** [StrangeLoopGames/EcoIssues#21422]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
https://prnt.sc/11j2dcf

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
We do not provide support for mods, you will need to contact the mod author.
