### ISSUE TITLE
[0.9.3.1 release-204] Steamtractor can no longer shift-drag / drag stacks correctly

### ISSUE THREAD

**Issue by mdegel** [StrangeLoopGames/EcoIssues#21424]
Starting with 0.9.3.1 release-204 the steam tractor is no longer able to move items out of the tractors inventory via shift drag, instead causing an error message like this:

`( x2)`

![tractor_error](https://user-images.githubusercontent.com/33593618/115068828-11ee3f00-9ef3-11eb-906b-d01dc6bf6369.PNG)

Attempting to normally drag or alt-drag the inventory for some reason results in x30 stacks.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I can confirm that this issue is happening with Steam Tractor internally moving stored items to nearby storage via Shift-Drag.
The issue is similar to #21389.
