### ISSUE TITLE
USER ISSUE: Crash

### ISSUE THREAD

**Issue by bibomaster** [StrangeLoopGames/EcoIssues#21420]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by bibomaster** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6326705/Player.log)

**Comment by bibomaster** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6326707/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please update to 9.3.1, the issue has been fixed.
