### ISSUE TITLE
Fix docker and s3 uploads on jenkins release pipeline

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21427]
they are both failing for some reason.

**Comment by redwyre** [comment]
There is no issue with release pipeline, the real problem is https://github.com/StrangeLoopGames/SLG/issues/1

**Comment by redwyre** [comment]
Duplicate of https://github.com/StrangeLoopGames/SLG/issues/1

**Comment by j3fffff** [comment]
this issue happened after, abhi's credentials fix from https://github.com/StrangeLoopGames/SLG/issues/1

so seems to be secondary issue with uploads

**Comment by redwyre** [comment]
They are still failing for the same reason, nothing has been fixed

**Comment by Abhiw205** [comment]
[fixed]  https://github.com/StrangeLoopGames/SLG/issues/1

Unable to test because Jenkins permission level changed for my user, due to which i can't rerun the failed job with modification.
