### ISSUE TITLE
USER ISSUE: objects don't spawn in save game

### ISSUE THREAD

**Issue by h4wk555** [StrangeLoopGames/EcoIssues#21423]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
objects don't spawn in save game

**Expected behavior:**
objects don't spawn in save game

**Actual behavior:**
objects don't spawn in save game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hello,
unfortunately your bug report is very unclear and not very helpful.

Please open a new issue with a better description in case your issue, whatever it is, persists.
