### ISSUE TITLE
[0.9.3.1 release-204] Vehicles an interaction distance check failed (occupancy based). Fallback to default check.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21421]
![image](https://user-images.githubusercontent.com/45708377/115060536-a60ad700-9ef0-11eb-9f3e-2a04b4ce5971.png)

**Comment by Sekor2600** [comment]
Its form different Vehicles too
like Steam Truck

**Comment by IronyTroll** [comment]
Can confirm. we started getting the same console notification after updating to [0.9.3.1 release-204]

Message occurs every time the vehicle is interacted with.

![image](https://user-images.githubusercontent.com/71368607/115112328-68797d00-9fc8-11eb-91fd-ebd9f89cc554.png)

**Comment by SlayksWood** [comment]
Still have issue with crane, create a new one
