### ISSUE TITLE
USER ISSUE: Tranctor transfer bug

### ISSUE THREAD

**Issue by coldbeer115** [StrangeLoopGames/EcoIssues#21438]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Drag or shift drag stacks from tractor to any other storage or sell at store		

**Expected behavior:**
It should transfer or sell the stack

**Actual behavior:**
Instead it will only do thirty at a time.  I get and empty error message box when atteempting to do more than thirty.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and I dont know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Tbear1825** [comment]
I have this same issue with the skid steer.  Only moves stacks of 30.  Once you get all the stacks in the bucket to lower than 30 the shift+click transfer will work.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. We are currently aware of the issue with transferring items via Shift-Drag on selected vehicles.
Merging with #21424
