### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Gudedorf** [StrangeLoopGames/EcoIssues#21439]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Load up my server

**Expected behavior:**
Server loads properly and can play

**Actual behavior:**
Server crashes and throws an exception

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No
[log_210416123356.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329227/log_210416123356.log)
[log_210417070931.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329228/log_210417070931.log)
[log_210417071746.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329229/log_210417071746.log)
[log_210417072501.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329230/log_210417072501.log)
[log_210417073019.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329231/log_210417073019.log)
[log_210417073236.log](https://github.com/StrangeLoopGames/EcoIssues/files/6329232/log_210417073236.log)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Gudedorf Thank you for the report. please provide some information:
1. Your PC specification (include Operating System and its version).
2. Save files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Gudedorf** [comment]
@SlayksWood 

PC Specs:
Processor: AMD Ryzen 5 3550H with Radeon Vega mobile Gfx 2.10 GHz
RAM: 8.00 GB
System 64-bit OS x64
Windows 10 Home

Drive with files:
https://drive.google.com/drive/u/0/folders/0AEz9i0_PAQbKUk9PVA

**Comment by Daniel-Magulado** [comment]
Hi @Gudedorf,

Are you still experiencing this issue?
Unfortunately, the Ryzen 5 3550H has a slower computing performance than our minimum recommended specs of Ryzen 5 1500X.

Is this the first time you played this game or you've been playing ECO with the same PC for a while now?
If you're still experiencing this issue, we recommend playing at a lower display resolution.

Do let us know if this works for you.

**Comment by Gudedorf** [comment]
I can play on other servers just fine. I was able to make and load my own
server twice and now i cant at all

**Comment by IcedForge** [comment]
Try to reset your config files eco/eco_data/server/config
by removing the .eco files ( not the .eco.template ) as its a json error meaning there is probably a corrupt or misconfigured setting in one of them.
Have you changed any server settings before this happened? (added admin user, blacklist, other settings etc)

And as always when changing/removing files always make a backup of both saves and configs just in case.

**Comment by TwixterZ** [comment]
hi @Gudedorf 

Have you tried to perform the above? 
Do you still facing the same issue after performing the above?

**Comment by Gudedorf** [comment]
Sorry for the late reply, I did try it and it worked.

**Comment by Daniel-Magulado** [comment]
Hi @Gudedorf,

Glad to know that it worked for you.
We'll be closing this ticket now but don't hesitate to file a ticket anytime you encounter any issues or game bugs.

Happy playing!
