### ISSUE TITLE
USER ISSUE: Shift-drag from tractor does not work

### ISSUE THREAD

**Issue by syhrus** [StrangeLoopGames/EcoIssues#21434]
\
**User Id: Syhrus**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Harvest your best 1000 plant crop with a tractor
Shift-drag your crops to any storage container.
Weep and start manually dragging them across manually in stacks of 30.	

**Expected behavior:**
Moved all 3000 beets to the silo

**Actual behavior:**
Error message pops up, and you have to manually drag them one stack at a time, except it only drags 30.	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6328632/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6328633/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We're currently aware of the issues regarding vehicles and shift-dragging items to other storage.
Merging with #21424
