### ISSUE TITLE
Need consistency with build naming

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21430]
Website currently determines build type using naming convention.
https://docs.google.com/document/d/1gjBZflxqgBfoaRoBH6u_tnAZj-rHg8WTVQL15aomyqE/edit

Simon im sure knows this now, but sometimes other dev might start build and no know.
Is there a way to make this extra clear or automatic via jenkins?

**Comment by redwyre** [comment]
I don't understand what the issue is. Is there a specific build you are saying is named incorrectly?

All builds are automated.

**Comment by WeaselDog** [comment]
We do actually have naming convention with updating production that will check for mistakes. I think issue is this so I will merge it here: https://github.com/StrangeLoopGames/SLG/issues/1

**Comment by redwyre** [comment]
Any proper release has the correct naming, so it would only ever be an issue with special releases. But I don't see any incorrectly named files except for `EcoModKit_v0.9.3.0-beta-194.zip` which was probably from manual copying. Do you know the exact file that caused it? Where did you see the file with version `0.9.3.1-beta-release-204` ?

If the website saw a file with the version `0.9.3.1-beta-release-204` and considered it a staging build, then the website got it wrong. As stated in the document staging builds are `x.x.x.x-beta-staging-#`. Problems we have had in the past have been other branches being picked up incorrectly. The document also says what builds should be in which buckets so anything else should just be ignored.

**Comment by WeaselDog** [comment]
Going to re-close. The issues asks to make this process automated through Jenkins, which it is. Jenkins will pick the correct naming convention automatically. The described example was because Update Production was not functioning as mentioned, requiring us to not use our automated process. We have this covered in the linked issue.

**Comment by j3fffff** [comment]
happened again
![image](https://user-images.githubusercontent.com/7343272/116475355-96638a80-a82e-11eb-95df-86a81e7f065b.png)

**Comment by j3fffff** [comment]
this seems to be current issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/21637
