### ISSUE TITLE
Laws Broken

### ISSUE THREAD

**Issue by Tbear1825** [StrangeLoopGames/EcoIssues#21433]
We have laws on our server that allow property transfers from abandonded players.  We also have a law that allows for admin to access players vehicles and transfer vehicles.  Neither of these laws appear to be working.

**Comment by SlayksWood** [comment]
@Tbear1825 Thank you for the report. Can you provide save file or law examples?

**Comment by IcedForge** [comment]
To clarify a bit, vehicle transfer does not fall under property transfer currently which is a known issue and will be fixed eventually. And the window interaction not working is also logged on github. But as Kirill above says it would help to have some form of screenshots or save file of the laws to be able to see what is going on.

**Comment by IcedForge** [comment]
Will close due to lack of response but we have separate closely related issues for tracking some of this.
