### ISSUE TITLE
USER ISSUE: FAILED TO HANDLE RPCResponse

### ISSUE THREAD

**Issue by Shanith15** [StrangeLoopGames/EcoIssues#21435]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
when i enter a door or open inventory or my store , this happens and i get kicked with this message

**Expected behavior:**
It should not have kicked me or gave me any error message

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i dont know if there is mods , im playing on a server i joined

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of the issues going on with the "Failed to Handle RPCResponse" error and client crashes that go with it.
We would appreciate if you could provide us with your game log. To do so, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Linking this ticket to #21162.

**Comment by SlayksWood** [comment]
@Shanith15 Do you have this issue in 9.3.1 release-204 version?

**Comment by Shanith15** [comment]
Hi
No its been fixed now with your 9.3.1 release , however why is the character now like its zoomed out ?

Its making hunting difficult and I always play in 3rd person... even trying to find fiddleheads and ingredients is hard now as trees are blocking my view. Its never done that. 

i tried setting the settings in the game to zoom in on character a bit more , but as soon as I went out , it just defaulted back to what it was. 

Should i logg a different issue for that ? 


Love your game by the way - very addicted to it :)
Kind RegardsJanine Du Toit (Shanith) 


Life is a journey, not a destination.  

 
 

    On Monday, 19 April 2021, 10:44:53 SAST, Kirill ***@***.***> wrote:  
 
 


@Shanith15 Do you have this issue in 9.3.1 release-204 version?

**Comment by IcedForge** [comment]
I will close this as resolved with 9.3 update.
As for the 3rd person view this is a new feature that is adjustable with holding ALT + scrolling to zoom in and out.
