### ISSUE TITLE
[0.9.3.1 Beta Release-204] Government Store Not Working

### ISSUE THREAD

**Issue by SoullessCreature** [StrangeLoopGames/EcoIssues#21436]
On the server that I'm playing on the store work just fine except for the government store. When someone tries to sell something to a store using a government account, the trade button does nothing when pressed. The store has been replaced a few times, players have re-logged (server also restarted since the previous update) but still nothing. The currency of the store has also been changed to using a player currency (the one where the player has infinite if it's their currency) and still nothing. The store is on land that is own by the people who are in the government.

I haven't included any pictures because it's essentially the same bug as this thread https://github.com/StrangeLoopGames/EcoIssues/issues/21391, but I believe it to be ever so slightly different seeing as we've tried it with a non-government account.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for providing more information about this issue.
We will link this with #21391.
