### ISSUE TITLE
USER ISSUE: Drag and drop with tractor

### ISSUE THREAD

**Issue by RondyNatla** [StrangeLoopGames/EcoIssues#21442]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
since the last update, we can no longer drag and drag any item with the shift key. an error message will appear

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@RondyNatla Thank you for the report. Can you provide more details? What kind of error appears? and what you are trying to move and what inventory did you use. And what is the current weight in these inventories?
I guess it related with #21444

**Comment by AndriusRimk** [comment]
It seems this is the same issue reported here in February [Issue 20512](https://github.com/StrangeLoopGames/EcoIssues/issues/20512), with reproduction video even.

**Comment by Daniel-Magulado** [comment]
This should be fixed by now. Please, feel free to let us know again if this issue persists.
