### ISSUE TITLE
[0.9.3.1] Renaming my bank account causes issues with transfers

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21447]
I had an account named "Meat account". I renamed it to "#Meat account" and then tried creating a transfer. However, it seems there was an issue when selecting the account from the list:

https://youtu.be/pKoyt0p-B6A

I'm guessing the list of names and the list of accounts might be stored separately, so when the names got reordered they didn't link properly with the accounts they were attached to?

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6330404/Player.log)

**Comment by SlayksWood** [comment]
@ThePiachu  Thank you for the report. Does the problem still exist after restarting the client / server?

**Comment by ThePiachu** [comment]
I think it might've persisted until I did another rename after a restart. Don't remember if I checked it straight after a full client restart, so might be wrong.

**Comment by TwixterZ** [comment]
@ThePiachu, Do you still see this issue happening in 9.3.5? 

I have tried to reproduce this error at my end on 9.3.5 Release 231, but unsuccessful

**Comment by TwixterZ** [comment]
Closing the issue as this is not happening on latest patch, to re-open if issue come up again.
