### ISSUE TITLE
[0.9.3.1] " GameAssembly.dll caused an Access Violation" when exiting the game?

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21448]
It seems whenever I exit the game there is a brief error window trying to load right before the application exits. I checked the crash log folder and sure enough, there are some readouts there:

[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6330407/Crashes.zip)

Not sure what this might be caused by, they just happen whenever I exit the game.

**Comment by SlayksWood** [comment]
merged to #20162
