### ISSUE TITLE
[9.3.1] - WorkBackPack item has incorrect MaxCarryWeight value in WorkBackPack.cs

### ISSUE THREAD

**Issue by Darkhand81** [StrangeLoopGames/EcoIssues#21457]
The description of the Work Backpack says that it should provide an additional 5kg of carry capacity in addition to calorie reduction, but the carry capacity is the same as the basic backpack.

This can be confirmed by comparing the `MaxCarryWeight` variable in the WorkBackPack.cs file and comparing it to the value in other Backpack files.  Both the Basic backpack and the Work Backpack have a `MaxCarryWeight` of `5000`, while the Bear Pack (which provides 10kg extra capacity) has a value of `15000`. The value of the Work Backpack should most likely be `10000`:

![PackBug](https://user-images.githubusercontent.com/1334381/115162246-0ec88f80-a068-11eb-97ac-e53f8f65d2c3.png)

**Comment by WeaselDog** [comment]
Hey thanks for the report.

Sorry for the confusion here. The Basic Backpack also provides +5kg as indicated by its description. There are some items for this slot that are not backpack and provide no extra weight capacity. The Big Backpack adds +10kg which is in between Basic Backpack and Bearpack.

**Comment by Darkhand81** [comment]
Thanks for the clarification! I did consider the basic backpack the 'Default' and didn't realize that it's already considered above the baseline of no backpack at all. :)
