### ISSUE TITLE
USER ISSUE: stuck in terrain

### ISSUE THREAD

**Issue by ErrMoniker** [StrangeLoopGames/EcoIssues#21456]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
dig a tunnel 3 tall, 1 wide, start stacking blocks and when they stack beneath you, it forces you upwards into / through the ceiling block and you get stuck

**Expected behavior:**
pushed me backwards out of the way or not let me put down the block	

**Actual behavior:**
clipped me into the ceiling and i can't break the block i am "inside" and can't continue

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed, just vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Darkhand81** [comment]
Not exactly a 'fix', but this is what the /unstuck chat command is for.

**Comment by SlayksWood** [comment]
@ErrMoniker Thank you for the report. Yes we have some problems with getting stuck, and as @Darkhand81 wrote above, you can use the command /unstuck  to free yourself. But according to your description at the moment there should be a different behavior - you should have been teleported to the surface #10345. Can you provide more information, maybe video?

**Comment by IcedForge** [comment]
Will close due to lack of reply. Please reopen if you can add the requested information.
