### ISSUE TITLE
Test failing in Jenkins 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21458]
May be not 100% reproducible. 

Test run Existing world CI failed!
landremoveallbut: Test Failed with 1 exceptions.

=====EXCEPTION 0=====
Warning: Exception Caught in Test landremoveallbut - System.InvalidOperationException: Operation is not valid due to the current state of the object.
Exception: InvalidOperationException
Message:Operation is not valid due to the current state of the object.
Source:Eco.World

**Comment by Quadbro** [comment]
May be not reproduced, need to double check if so
