### ISSUE TITLE
[9.4 Develop 256] Failed to handle RPC method: OpenUI

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21450]
RPC error when using contract board, booting player out of the server.

https://images.zenhubusercontent.com/47210472/9e8b7d24-e01a-471d-922a-8f185cc86541/1702924b801375d4bccdca80db760090.mp4

**Comment by SlayksWood** [comment]
more details from #21079:
> Today I catch it again with Campsite:
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6264204/Player-prev.log)
> So my campsite was broken:
> 
> 1. Double storage in UI
>    ![image](https://user-images.githubusercontent.com/45708377/113702961-ded1d180-96e2-11eb-89e5-7d835dd5e168.png)
> 2. Craft tab is broken at all:
>    ![image](https://user-images.githubusercontent.com/45708377/113703034-f90baf80-96e2-11eb-9d0c-f961addeeeb8.png)
> 3. 2 sleep button:
>    ![image](https://user-images.githubusercontent.com/45708377/113703056-0032bd80-96e3-11eb-9a26-d20ca00399b2.png)
> 
> I don't know how to reproduce it, but I used Alt+Z a lot to hide/show UI when open Campsite. Add to investigation it to next release.

**Comment by abaza121** [comment]
The main issue here is happening on develop and doesn't happen on release, will see this and the camp site issues on develop
