### ISSUE TITLE
Void Storage Issue - Cannot Scroll

### ISSUE THREAD

**Issue by VictoriaVonDoom** [StrangeLoopGames/EcoIssues#21463]
I am currently on a modded server "Redemption - An Eco Story" and I was on a friends residence plot. I eventually began to create my own house and only set up a tiny stock pile at the new location. I left the residence and all my items that I have ever added to his plot went into the void storage. There were roughly 400+ items and I was only able to access the first 17.5 rows as this new window that opens into the void storage is vertical and has a width of 5ish rows horizontally. Please let me know if you need me to provide more information.

**Comment by WeaselDog** [comment]
Thanks for letting us know and sorry this happened. We improve the usability of the void storage UI.

**Comment by SlayksWood** [comment]
merged to #21407
