### ISSUE TITLE
[9.4 Develop 259] Labor requirement bugs

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21462]
Player can perform labor for skill book research on Research Table whether they have required specialization unlocked or not.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9c7e8218-d2e4-4896-aa64-b721dc3683cd)
https://images.zenhubusercontent.com/47210472/228f8bcc-6d54-47fa-9d3c-961137ccf0bd/d8d8512a49c1d038d6a8f7c1286012c8.mp4

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/d26a9b53-7b28-48e0-ac59-4eb9c4d44d75)
_*to prove none of the specialization required is unlocked._

**Comment by TwixterZ** [comment]
To add on, other research after below highlighted items are working properly. 
![image](https://user-images.githubusercontent.com/78054747/115191248-c074c880-a11b-11eb-9b68-ac2214da1d71.png)

player can still put labor for cutting edge cooking research book even without advanced cooking unlocked.
![image](https://user-images.githubusercontent.com/78054747/115191426-fd40bf80-a11b-11eb-9717-3f2dbed79ecb.png)

Advanced baking is working as intended (it is placed after highlighted item above) 
![image](https://user-images.githubusercontent.com/78054747/115191524-219c9c00-a11c-11eb-9e39-90cd982cde3a.png)

**Comment by TwixterZ** [comment]
Same issue identified and confirmed happening to following tables : 
**Machinist Table
Electric Machinist Table
Oil Refinery
Kitchen
Stove
Shaper
Pump Jack
Robotic Assembly Line
**

**Comment by WeaselDog** [comment]
I can't replicate this. With Smelting Skill Book, it only requires Mining 0 so anyone can research this. I am not able to add labor to the other items listed without skill.

When you use command `/spawn research table` you will learn Cooking. I wonder if this is what is happening here.

**Comment by TwixterZ** [comment]
retest done on 9.4 Develop 287 and confirms issue no longer exist, will close this now.
