### ISSUE TITLE
Users banned from voting, but not playing ingame.

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21468]
fixed by linking their steam account to slg
https://www.reddit.com/r/EcoGlobalSurvival/comments/msjdmi/prevented_from_voting/

@WeaselDog 
There might be bug with how voting uses auth, in game server. can you assign someone to check that part?
Otherwise we need help to setup situation for duplicating error. @Ry4ndrew

**Comment by WeaselDog** [comment]
duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/21469
