### ISSUE TITLE
USER ISSUE: All Partikels are black

### ISSUE THREAD

**Issue by Zerox-g** [StrangeLoopGames/EcoIssues#21464]
![20210419122720_1](https://user-images.githubusercontent.com/75671733/115222434-ffe6e900-a10a-11eb-950a-18be114838fd.jpg)
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
i don't know

**Expected behavior:**
Normal Partikels

**Actual behavior:**
Black Partikels

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Zerox-g Thank you for the report. DO you have this issue after restarting game?
did you have any kind of teleport or a problem with loading chunks?
seems need merge to #14042.

**Comment by IcedForge** [comment]
Will close in lack of response but looks like the same broken shader problem as the abovementioned issue.
