### ISSUE TITLE
Users banned from voting, but not banned from playing ingame or loading election page.

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21469]
happening for all users on server.
fixed by linking their steam account to slg
https://www.reddit.com/r/EcoGlobalSurvival/comments/msjdmi/prevented_from_voting/

needs more info

**Comment by j3fffff** [comment]
I tested steam (not conneted to slg) login on infected server ().
It logs into election page with normal steam token.

auth's verifyc3 response is like this:
```
{
    "product_id": "4",
    "user_id": null,
    "username": null,
    "citizen": null,
    "selected_icon": null,
    "reward": null,
    "steam_id": "76561197962315748",
    "status": true
}
```

I see in game server code, the reported error `$"User '{user.Name}' is banned on this server."`
is located in ControllerUtils.cs

Seems like something is getting mixed up in the game server code with steam tokens. making server think they are on blacklist.

On the infected server, i see in user.eco it has an entry in blacklist that is missing a username. 
```
{
              "ReleaseDate": new Date(
                1780905577921
              )
            },
            ```
@D3nnis3n is confirming with server that removal of strange blacklist entry will fix issue.

possible that @mirasrael original ban bug fix, may have left these ban entries without usernames?

**Comment by jamesyoung79** [comment]
I can confirm what J3ffff found. It seems when migrating the old users.eco file to the new format it adds an extra entry with no username. I corrected the file manually and rebooted, waiting to hear back from one of the effected players.

**Comment by jamesyoung79** [comment]
After removing the entry with no username it resolved the issue.
