### ISSUE TITLE
[9.3.1] inventoryRestrictions Misspelled No Add Restictions

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#21478]
The inventoryRestrictions _**No Add Restictions**_ is misspelled.

Note: Data is to be displayed on Wiki.

**Comment by TwixterZ** [comment]
@ZeelNightwolf thanks for raising your concern, kindly advise which part of the game are you referring to here? 

could use more information for us to understand this issue better

**Comment by IcedForge** [comment]
Still not sure where this correlates to? Is this a type ingame, the ecopedia or the play.wiki page? The later one is community operated and is not really our responsibility to manage.

**Comment by ZeelNightwolf** [comment]
There is an inventoryRistriction in the code called No Add Restictions. I was pointing out that it's missing an r.

 InventoryRestrictions happen when a player gets a message because they move an item into an inventory and it is restricted. They dont actually see what these restrictions are called just the message that goes with it.

InventoryRistrictions I know of:
No Add Restiction
Not Carried Restriction
Seed Restriction
Silo Restriction
Specific Item Types Restriction
Stack Limit Restriction
Stockpile Stack Restriction
Weight Restriction

It's not really seen by players but we would like to get this data and show it on the wiki to show items like the Silo and what inventoryRistriction it has and the message that will pop up.
