### ISSUE TITLE
[0.9.3.0 beta release-204]Personal Inventory moving items when inventory is full / weight capped

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21470]
When you are trying to move an item that is of  total weight higher then your empty inventory capacity it will cause issues of only being able to move 1 item at the time it will not account for the fact that the items you are moving is already taking up weight capacity.

Carry 30kg of items, move stack of 10kg food into another slot, error

**Comment by SlayksWood** [comment]
dup #21444
