### ISSUE TITLE
Basic Upgrade 4 Does Not Reduce Resource Cost in Arrastra

### ISSUE THREAD

**Issue by proviancy** [StrangeLoopGames/EcoIssues#21476]
I have a basic upgrade 4 in an arrastra. The work time is being decreases by 45% as listed, but the resource cost is not reduced by 45% like it should be.

**Comment by IcedForge** [comment]
Thank you for reporting. This is working as intended if you mouse over the icon resource cost it states that this is a static resource modifier which means that there is no reduction for this ( indicated by a yellow border ).
