### ISSUE TITLE
Severe Lag, Followed By Crash Error on Client RPCResponse 

### ISSUE THREAD

**Issue by MystLeissa** [StrangeLoopGames/EcoIssues#21474]
My Girlfriend was playing with me recently, and she suffered from massive FPS/Net Lag and it seems that at it's culumination the game froze and spit out this error, I am reporting it for her because she's the one having the issue but she's a bit shall we say, shy:

"Failed to handle RPCResponse

Log File:
Initialize engine version: 2020.1.17f1 (9957aee8edc2)
[Subsystems] Discovering subsystems at path D:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
Version: Direct3D 11.0 [level 11.1]
Renderer: AMD Radeon(TM) Vega 8 Graphics (ID=0x15d8)
Vendor:
VRAM: 7124 MB
Driver: 26.20.14042.2
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.729400 ms
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
(Filename: Line: 627)

WwiseUnity: Wwise(R) SDK Version 2019.2.5 Build 7349.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: D:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing!
(Filename: Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing!
(Filename: Line: 334)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
SteamManager:Awake()

[ line 627]
(Filename: Line: 627)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
(Filename: Line: 320)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
(Filename: Line: 320)

[05:52:32.660] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[05:53:32.804] Connecting to 24.159.144.116:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
AddServerUI:OnAddServer()
UnityEngine.LowMemoryCallback:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
ItemWithValueAction`2:Invoke(T, TValue&)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'LayerViewer') is missing!
(Filename: Line: 334)

Unable to open archive file: D:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/desc.unity3d
(Filename: Line: 588)

Failed to read data for the AssetBundle 'StreamingAssets\desc.unity3d'.
(Filename: Line: 450)

[05:54:38.599] Missing sprite in MiscIconMap.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
ModBundleManager:Setup"

**Comment by IcedForge** [comment]
Thank you for reporting. 
Linking to main tracked issue #21162
