### ISSUE TITLE
Ability to drop items into the world

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#2148]
With all games having this, this should be a thing in eco,

Drop items on the ground and also, pick up items from the ground.

**Comment by ClayC90** [comment]
Oh and no de-spawn of items would be nice, so people cannot trash like this.

But if people drop tailings they will still pollute for example ;)

**Comment by MarjieAVolk** [comment]
We have plans to implement a trash system for this purpose - probably dropping things on the ground will create trash blocks, or something similar.  I am going to close this issue for now, since we are tracking this task elsewhere

**Comment by ClayC90** [comment]
Dropping items and trashing is different, trashing is not something I strongly agree with as people will find a loophole to trash tailings since they pollute ;)
