### ISSUE TITLE
Interaction with Cart shows Server Errors

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#21485]
V9.3.1
![server](https://user-images.githubusercontent.com/38510829/115382759-56205e80-a1d5-11eb-98cb-916dc194615f.PNG)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6342826/Player.log)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6342828/output_log.txt)

**Comment by SlayksWood** [comment]
@Nicolausi113 Thank you for the report. This issue will be fixed with #21421. Only crane have this problem now.
