### ISSUE TITLE
Goverment accounts not working on real estate desks

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21489]
![image](https://user-images.githubusercontent.com/25908592/115389809-d5199500-a1dd-11eb-9569-d973f0647ac1.png)

**Comment by IcedForge** [comment]
With upcoming hotfix 9.3.2 

Using a government account, owned by title 1, and managed by title 1
And the title in question has a user / client holding this title.

![Screenshot_18](https://user-images.githubusercontent.com/24981362/115390471-90422e00-a1de-11eb-9f80-ee01a58280b7.jpg)

Now if the title 1 is no longer held by a user, this means no player can be connected to the sale it will prompt the following
![Screenshot_19](https://user-images.githubusercontent.com/24981362/115390635-c2ec2680-a1de-11eb-946d-d66852a90479.jpg)
