### ISSUE TITLE
[0.9.3.1] Blank error when moving cotton to a silo

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21484]
I tried moving the raw, harvested cotton to a Silo and got this weird looking error:

![image](https://user-images.githubusercontent.com/964559/115378276-3d885800-a185-11eb-871d-784b1f6d392f.png)

Not sure what's up with that, usually the error is a bit more descriptive.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6342618/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
Although the outcome is different, the reproduction steps are the same.
I'll be linking this issue with #20077.
