### ISSUE TITLE
[0.9.3 release-207] You should be closer to interact

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21482]
- [x] 1. Excavator. 
- place excavator like on screen:
![image](https://user-images.githubusercontent.com/45708377/115366199-c7f4aa00-a1cd-11eb-858d-8a071ddf4798.png)
![image](https://user-images.githubusercontent.com/45708377/115366230-ccb95e00-a1cd-11eb-89c4-1ad1de295695.png)

- [ ] 2. Crane:
![image](https://user-images.githubusercontent.com/45708377/115366278-d9d64d00-a1cd-11eb-82e9-2611b50a5653.png)
![image](https://user-images.githubusercontent.com/45708377/115366347-eb1f5980-a1cd-11eb-974a-586a560077d1.png)

**Comment by SlayksWood** [comment]
fixed with https://github.com/StrangeLoopGames/Eco/pull/8379

**Comment by SlayksWood** [comment]
Still an issue if you try to interact with Crane Arm and this arm is far enough:
![image](https://user-images.githubusercontent.com/45708377/115703384-bc8eb380-a372-11eb-8d74-fedab9826452.png)
![image](https://user-images.githubusercontent.com/45708377/115703396-c0bad100-a372-11eb-8fe6-ccf82e2a6425.png)
It this is pretty basic position all works fine:
![image](https://user-images.githubusercontent.com/45708377/115703627-037ca900-a373-11eb-9b09-55bedc4d3778.png)

**Comment by SlayksWood** [comment]
Exca fixed here https://github.com/StrangeLoopGames/Eco/pull/8379

**Comment by WeaselDog** [comment]
Fixed in 9.6
