### ISSUE TITLE
Changing auth settings on object needs to trigger linked inv updates

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2149]

**Comment by johnkslg** [comment]
This exists in LinkComponent line 158:
            obj.GetComponent<AuthComponent>()?.OnAuthChanged.Add(this.NotifyChanged);

Perhaps its not working as expected?

**Comment by johnkslg** [comment]
Actually I suppose it needs to also call LinkedInventoryUpdated

**Comment by MarjieAVolk** [comment]
Oh yeah, that should be handling the issue I saw >> Hmmm.  Maybe it is a ui caching thing after all. But I will add the call to LinkedInventoryUpdated as you suggested, that's needed too.
