### ISSUE TITLE
[0.9.3.1] Unable to reassign vehicles in a law

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21494]
Currently, a good deal of servers have a law for reclaiming property and so on when people enter the Abandoned demographic. However, as easy as that law is to create, as far as I can tell, we don't have a way to automatically reassign vehicles that the person owns. Only workaround I managed to find for that was some roundabout way of ignoring authorisation when you look at the "deed" the vehicle is on.

We should have a way to target all vehicles / vehicle deeds owned by a given individual in a law so we can clear them out from abandoned plots.

**Comment by SlayksWood** [comment]
@ThePiachu Thank you for the report, merged to #17733
