### ISSUE TITLE
USER ISSUE: Removing Items from Tractor

### ISSUE THREAD

**Issue by frankn1** [StrangeLoopGames/EcoIssues#21495]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
1. Have large stacks of items in Steam Tractor
2. Try shift-dragging items out of inventory (won't work)
3. Only 30 items will move into inventory selectes (I used silo)

**Expected behavior:**
When shift dragging all the seeds/crops selected should move into targeted storage

**Actual behavior:**
Only groups of 30 items drag over at a time

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Playing 9.3 update

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@frankn1 Thank you for the report. THis issue will be fixed in next hotfix. closed.
