### ISSUE TITLE
[0.9.3.1 Release-207]Double Error for Put Item in Container contract if target storage is full

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21505]
Build: 0.9.3.1 Release-207

## Issue
Double error when trying to store/swap required item for **Put Item in Container** contract in target storage if the target storage is full.
![image](https://user-images.githubusercontent.com/77248866/115552177-9586a200-a2de-11eb-9a26-579947ce1e81.png)

### Repro
1. Take **Put Item in Container** Contract.
2. Target Storage should be full.
3. Store the required item stated on the contract to the target storage. Swap with one of the items stored in the target storage.
4. Observe.

### Actual Result:
https://user-images.githubusercontent.com/77248866/115552454-f01ffe00-a2de-11eb-80fb-24e9832a085d.mp4

### Error when taking an item
![image](https://user-images.githubusercontent.com/77248866/115552511-01690a80-a2df-11eb-8af3-42fd62fd8c6a.png)

### Error when storing an item
![image](https://user-images.githubusercontent.com/77248866/115552604-16de3480-a2df-11eb-8892-df38aef6a691.png)

**Comment by tuha263** [comment]
Seem it worked properly now:
![ErrorLog](https://user-images.githubusercontent.com/9598614/117238686-98919e80-ae57-11eb-8f89-1143f2bb9ba3.png)

**Comment by Daniel-Magulado** [comment]
Tried to reproduce on  0.9.4 Develop-287.
I am unsuccessful. Closing for now.
