### ISSUE TITLE
USER ISSUE: Server thinks I'm on the wrong version.

### ISSUE THREAD

**Issue by LadyNasse** [StrangeLoopGames/EcoIssues#21509]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-209

**Steps to Reproduce:**
Manually select the 9.3.1 beta in Steam, t
[ServerErrorECO.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6352899/ServerErrorECO.txt)
ry to connect to a 9.3.1 server.

**Expected behavior:**
It should connect.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Incompatible version.
User version:   0.9.3.2 beta release-209
Server version: 0.9.3.1 beta release-204

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
9.3.2 wasn't supposed to be released. Please restart steam, you will get the correct old version again.
