### ISSUE TITLE
[0.9.3.2 Release-212]Missing asset line peeking on Hunting Skills icon during level-up animation

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21518]
Build: 0.9.3.2 Release-212

## Issues
Related to #21021
The missing asset line is also peeking for the hunting skills icon during level-up specialty animation.
![image](https://user-images.githubusercontent.com/77248866/115725264-4743d280-a3b4-11eb-9fe4-26bbbb3a4674.png)

#### Repro
1. Get a Hunting specialty.
2. Level up hunting specialty.

**Comment by madpingui** [comment]
Fixed filter in Icon Sprites, update SVN in develop branch to check fix.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develo-267.

Fixed and closing.
