### ISSUE TITLE
[0.9.3.1] Laws can't see all titles

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21511]
Similar to #19240 - you can't see all the titles when setting a law:

![image](https://user-images.githubusercontent.com/964559/115606850-18850980-a299-11eb-8da1-05cee16c4545.png)

![image](https://user-images.githubusercontent.com/964559/115607008-45d1b780-a299-11eb-918b-f34f090dab30.png)

Which can be rather inconvenient at times.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2021.

All titles are now listed when drafting a law.
Even those titles that are still in draft, owned by other players, and private titles that has no access to Everyone demograpic.

Closing as fixed.
