### ISSUE TITLE
[0.9.3.2 Release-212]Disconnect closes the client instead of returning to lobby

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21517]
Build: 0.9.3.2 Release-212

## Issue
Pressing the **Disconnect** button closes the client. That should not happen. It should return the player to the in-game eco lobby.

#### Repro
1. Start a new game.
2. Press ESC and click Disconnect.
3. Observe.

#### Actual Result
https://images.zenhubusercontent.com/42199084/493129f1-497a-430a-9cc8-caad16d83410/2021_04_22_19_16_trim.mp4

I'm also getting this on my log:

> [07:17:31.022] Injection detected. Please, stop using third-party software for code injections or you will be reported and permanently banned on all servers.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.<>c:<Register>b__1_0(Scene, LoadSceneMode)
UnityEngine.Events.UnityAction`2:Invoke(T0, T1)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

[Player Log](https://app.zenhub.com/files/42199084/2f5de894-28c0-4d52-ba76-f6c6ed1660dd/download)

#### Expected Result
Returns to lobby.

**Comment by Martino80** [comment]
I've tried this issue in Steam Client as also in Direct Client, booth Clients will stop the game after disconnect from any server.

**Comment by namquang93** [comment]
I believe this has the same root cause with https://github.com/StrangeLoopGames/EcoIssues/issues/21302 which is fixed last sprint.

**Comment by mirasrael** [comment]
No. It is another false positive from InjectionPreventer :(
