### ISSUE TITLE
USER ISSUE: pas de mise a jours 9.3.2 sur steam 

### ISSUE THREAD

**Issue by malvile7** [StrangeLoopGames/EcoIssues#21510]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Impossible d'installer la mise a jours 9.3.2 sur steam 

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Incompatible version.
User version:   0.9.3.1 beta release-204
Server version: 0.9.3.2 beta release-209

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
9.3.2 wasn't supposed to be released. Please restart steam, you will get the correct old version again.
