### ISSUE TITLE
[0.9.3.1] Weird behaviour when creating a split deed

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21515]
So I used an old habit of mine to create a split deed - I had a full store and house on one plot of land, I clicked "edit" and claimed some land somewhere else. I got a warning that this will split my deed, which was expected. What followed however:

- My deed was split as expected
- My original deed was renamed to a default name
- My residency was moved to the new part of the deed (empty land), rather than defaulting to staying where it was. Housing XP didn't change however (probably handled on a different process), nor was I kicked out of my government position for being in the wrong district (again, probably different process) until a few minutes later when I have re-set my residency.
- I got a notification that my store stopped working since I didn't have access to its custom account (wut?). I had to re-set the account and currency to proper ones

I think that feature should be a bit safer to execute:
- Residency should stay with the half of the deed that has the highest housing value
- Stores should remain unaffected

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6355632/Player.log)

To reproduce:
- Have a well developed land with a store, house, etc.
- Click edit
- Claim area that is not connected to the original deed
- Confirm
- Panic

**Comment by SlayksWood** [comment]
@ThePiachu Thank you for the report.
House value update issue here #21208.  I guess your house value has changed, it was just displayed incorrectly in UI.
The other issue seems regression, this behavior was not like this after fixing this issue #19764.
So when you split deed the original deed should save name.

**Comment by gzatravkin** [comment]
For spliting:
Check which of "islands" contains the majority of old points and use this one as original deed, while the other ones will be created as new deeds.
Afair it uses the deed with biggest number of point now to be "original" one.

**Comment by gzatravkin** [comment]
Changes should be made at 
Deed.TrySplitDeed
