### ISSUE TITLE
[0.9.3.1] Can't view property and edit district at the same time

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21514]
I wanted to do some road zoning on White Tiger, and I ran into the issue of having to constantly switch between the property view and the district view to ensure I wasn't encroaching on someone's property. It would be nice to be able to toggle various views / district maps / etc. as "visible" / "invisible" layers and be able to paint on a new district while looking at something from the other district / the properties.

**Comment by SlayksWood** [comment]
Yes, this is a known issue. But at the moment only 1 layer can be displayed. For this, a function has been added using Ctrl.
So you can select Property then Viewing Map and switch one to another with holding Ctrl.
Closed this one and merged to #12946 for discussion.
