### ISSUE TITLE
[0.9.3.1] Can't forgive debts

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21522]
I recently tried my hand at giving out a loan for the first time. Someone took it and accidentally sent me a transfer instead of repaying the loan, so I tried forgiving them the debt, but for some reason I couldn't do it:

https://youtu.be/jT3xb84uhu0

I tried it a few times, I finished the contract manually, tried forgiving them again, still nothing.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6360860/Player.log)

**Comment by SlayksWood** [comment]
will be fixed in 9.3.5
