### ISSUE TITLE
USER ISSUE: Crash while running through the village

### ISSUE THREAD

**Issue by SuperDulli** [StrangeLoopGames/EcoIssues#21523]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
No idea?
Maybe has to do with animal running around while I did something.

**Expected behavior:**
It should have crashed to the menu.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__71_2()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
merged to #20612
