### ISSUE TITLE
9.3.1 One users contracts are always orphaned and has no host

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21536]
One user on my server is always getting the below, this happens on a new contract board, picking up and placing back down again does not allow import of orphaned either.

If the contract expires, the player (tlaine) cannot cancel the contract due to it being orphaned.

Other contracts are fine for other players.

![image](https://user-images.githubusercontent.com/61889138/115866969-59fcec80-a432-11eb-9a39-639e1b08a0ba.png)

**Comment by TwixterZ** [comment]
@MishkaFur as discussed, putting this issue to be under investigation as this only happens to one specific player and said players have left your server.

adding further, seems that most of the contract posted by same person is now working
