### ISSUE TITLE
[Hosted Worlds - Advanced Options] UserPermission missing labels

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21530]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/ab0e8883-d255-4042-98d4-fe3163355b1f)
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/68a881cd-ec3e-40b2-8346-50128a246529)

**Comment by Ry4ndrew** [comment]
Upon further testing, inputting anything in the highlighted sections will produce an error.
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/a1cdf977-ba87-42c0-8c19-f491fdce53d1)

**Comment by j3fffff** [comment]
first issue, we already have github issue for.
2nd issue, @denysaw sounds related to your last fix?

**Comment by denysaw** [comment]
@j3fffff It's same new configs, yep, but it's not cuzz of my last change it was before it. Trying to fix it, yep. But yeah, there is issue-clone reported by Dennis

**Comment by j3fffff** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/21598
