### ISSUE TITLE
Desync with server

### ISSUE THREAD

**Issue by learntheirtools** [StrangeLoopGames/EcoIssues#21539]
Steps to Reproduce:

1. Play in the eco.mmozg.net (old, long-term world). World must be launched at least before 9.3.0
2. Update the game to 9.3.0 and higher
3. Go to the distance of the "View distance" setting to one of the several anomalies that have appeared in the game world. Anomalies have a permanent location in the game world, do not disappear with a reboot of the client or server, and it is not yet clear what the places are connected with, either the degree of changes in the world or the objects located in them are different. Most of the suspicion falls on a large number of 5x5x5 warehouses, some forms of blocks of Mortared Stone, or 5x5x5 warehouses filled with Mortared Stone. There is also a suspicion that warehouses and blocks placed after updates behave normally.
4. Wait several minutes

Expected behavior:

The game should normally respond to the player's actions, such as: get in the truck, choose another tool in your hands, open the stockpile inventory, open the store interface.

Actual behavior:

Instead, if the character is within sight of the anomalous zone, it seems that the player's actions get into some kind of queue of requests to the server, which is spammed by something else. After a while, sometimes in a few minutes, this turn comes and all the actions of the character are performed almost at once, in the same sequence in which the player pressed the keys. None of the actions are lost, but can be applied not to the object that the player pointed to, but to the one that he is looking at at the moment when the server's reaction occurred. If you lose the anomalous zone from the view distance, everything returns to normal.

**Comment by SlayksWood** [comment]
merged to #21437
