### ISSUE TITLE
Tutorial box overlaps other buttons in an awkward way

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21549]
![image](https://user-images.githubusercontent.com/3536496/115937461-f03e0c00-a44c-11eb-9c6d-bf31999472f1.png)

Also change the font so not everything is bold, make it look nice.  I think the text could be smaller too, see what point size it is.  Try out some ideas and see what feels better/cleaner.

**Comment by MilenkoTunjic** [comment]
I thought we had a solution for this?
Also, other than bold not being used, font size overall can be smaller (18-20 whichever works better) and font spacing can be adjusted. the box does not need to be this big, just feels a bit amateurish as it is.

**Comment by johnkslg** [comment]
Whoever works with this get milenkos sign off (this is from release it may be different in develop)

**Comment by johnkslg** [comment]
Dupe of https://github.com/StrangeLoopGames/EcoIssues/issues/20555
