### ISSUE TITLE
Electronics Assembly Icon

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#21543]
The Working Animation for Electronics seems missing + new Icon

Seems like there is only a Start Animation 

https://user-images.githubusercontent.com/37456949/115932949-45e6d880-a48e-11eb-8433-08a4a2528408.mp4

**Comment by keegan-o** [comment]
Investigate if this has a new icon made for it or not, if not, let's get one made!

**Comment by Phlo123** [comment]
Fixed the animations for Using and Operating, and removed the keyframe compression. Uploaded to SVN
