### ISSUE TITLE
Can change store prices, despite everything looks like i shouldnt be able to

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21558]
![image](https://user-images.githubusercontent.com/25908592/115971687-244b2700-a54a-11eb-948b-e3c4c48147da.png)
![image](https://user-images.githubusercontent.com/25908592/115971691-29a87180-a54a-11eb-8e7f-76250d38df7d.png)
![image](https://user-images.githubusercontent.com/25908592/115971696-2f05bc00-a54a-11eb-9917-206ff6d37e84.png)
![image](https://user-images.githubusercontent.com/25908592/115971698-32994300-a54a-11eb-8438-3894d4d54354.png)

Dev tool not selected, makes no difference if its in hotbar or not.
I could buy a truck at a different store just fine without being able to edit the store.

**Comment by D3nnis3n** [comment]
Possible Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20401

This seems to be a frequent error and can cause bad effects, can we try provocating it somehow to get reproduction?
People report it happens all the time until client restart, which doesn't look safe to me.

**Comment by WeaselDog** [comment]
When it happens, it only happens to one store and other stores are unimpacted. It is fixed by rejoining server.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/20401
