### ISSUE TITLE
Sea Otter dead due to database locks

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21559]
Cant connect, server just freezes, process running

[log_210424090357.log](https://github.com/StrangeLoopGames/EcoIssues/files/6370574/log_210424090357.log)

**Comment by D3nnis3n** [comment]
Save file: https://drive.google.com/file/d/1U290l6IAQMGx_ouRnu2kVFWjNJQO0eqn/view?usp=sharing

Trying DB backup

**Comment by D3nnis3n** [comment]
DB backup worked so far

**Comment by D3nnis3n** [comment]
Maybe related to https://github.com/StrangeLoopGames/EcoIssues/issues/21309
But didnt have any of the errors there.

**Comment by SlayksWood** [comment]
closed as fixed.
