### ISSUE TITLE
[0.9.3.2 Release-213]Hide Pending Tutorial for UI's that opens on full screen

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21554]
Build: 0.9.3.2 Release-213

## Issue
The pending tutorial shown on the upper left corner of the screen should be hidden when interacting with UIs that opens on the full screen. Example, Map and Talent Book. It works perfectly with Ecopedia opened.

Ecopedia
![image](https://user-images.githubusercontent.com/77248866/115955428-e984c700-a528-11eb-9cbe-98f1177c3b9f.png)
Map
![image](https://user-images.githubusercontent.com/77248866/115955439-fd302d80-a528-11eb-8f00-169ca7e90f41.png)
Talent Book UI
![image](https://user-images.githubusercontent.com/77248866/115955451-0c16e000-a529-11eb-9a62-1d9a89e03169.png)

Player's don't need to see the pending tutorial if interacting with these UIs. The only time I needed to see them was when doing the tutorial for specialties as well as the tutorial for the map.

**Comment by gzatravkin** [comment]
Maybe it will be easier to have something like "Hide Tutorial" in UI windows option. Because it could turn messy to change sort order of different UIs

**Comment by WeaselDog** [comment]
Converted to Clickup
