### ISSUE TITLE
[0.9.3.1] Can't transfer property to X or Y based on district

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21569]
On White Tiger we like being particular about our laws. We implemented a simple property reclamation process of transferring abandoned property to the Prime Minister, but there is a small issue - for plots within our Capital, we wanted to transfer that property to the Mayor, instead of the Prime Minister. However, that would be kind of a nested statement:

- On demographics change, IF entering abandoned demographic, FOR EACH property owned by the user, IF property is within Capital transfer to Mayor, OTHERWISE, transfer to Prime Minister

Kind of feels like there should be better support for this.

**Comment by IcedForge** [comment]
Thank you for reporting as always @ThePiachu will close and merge with #17733 as it falls into that curfew i believe.
