### ISSUE TITLE
MediumWoolyCarcass tag not cookable on campfire

### ISSUE THREAD

**Issue by MarcelBostelaar** [StrangeLoopGames/EcoIssues#21566]
Version 0.9.3.1 Beta 204

Incorrect/unexpected behavior: Items with the tag "MediumWoolyCarcass" (Bighorn Carcass & Mountain Goat Carcass) are not cookable on the campfire like other animals.

Correct/expected behavior: Item should be cookable, as items with tag "MediumCarcass" do have corresponding "medium animal" recipe in campfire (Campfire animal medium recipe). All other animal carcasses have a corresponding campfire recipe.

Steps to reproduce:
1 Get a Bighorn Carcass
2 Try to cook it on a campfire
3 You can't, no recipe applies.

Suggestions for possible solutions:
- Make "campfire animal medium recipe" accept items with either "MediumCarcass" or "MediumWoolyCarcass" tag
- Create separate tags for campfire cooking only, to separate butchery and campfire-cooking logic, and keep a singular "campfire animal medium recipe" recipe.
- Add extra comparable recipe for the WoolyMediumCarcass tag to the campfire
- Tag all MediumWoolyCarcass items with MediumCarcass as well. (Will not play nicely with butchery table recipes, as the same item would be usable in both "Butcher Medium Animal" and "Butcher Medium Woolly Animal" recipes. The woolly version is a straight up better recipe with more end products, will cause confusion/loss of resources.)

----

Steam profile for crediting: https://steamcommunity.com/profiles/76561198041750390

**Comment by WeaselDog** [comment]
Thanks for reporting this. For next patch, we will include a recipe for all medium carcass on the campfire. We plan to improve how crafting works with tagged ingredients in general.
