### ISSUE TITLE
Make 'amount' in db backend only count game and invite purchases (game, upgrades, tiers, invites), but not CW

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21562]
It's more sueful to me to see game purchases at one look (to recognize tier as well) than seeing the amount with cloud worlds - they have no effect on upgrades or anything - i dont need it.

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod.

**Comment by Ry4ndrew** [comment]
Retested and confirmed fixed. Thanks
