### ISSUE TITLE
[0.9.3 release] Cotton Plant needs visual adjustments

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21560]
While I am playing, I notice there is something different with Cotton plant that makes it stand out from other plants. It looks like it has less details than the other plants, and it is more blocky. It does not blend well with Bulrush which is the dominate plant in wetlands.

I am not sure if there is a problem with LOD settings or something else. The plant just feels out of place visually. 

To be fair in this picture the amount of wild cotton should be tuned down, but you can see how it looks different from other plants.
![CottonPlantArt](https://user-images.githubusercontent.com/47330823/115972602-35714500-a504-11eb-94be-72b999f94ab7.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/31256263-20ea-4c21-85b1-d9ca5e86131a)

Fixed in develop, will look at merging to staging actually as well I think, since it didn't break wind at all to make the change and it's only the speed tree file plus a new ref mesh.

**Comment by keegan-o** [comment]
fixed in staging for 9.4 as well
