### ISSUE TITLE
[0.9.3.2 Releasw-213]Pump Jack crafting table lacks information about its pipe output

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21572]
Build: 0.9.3.2 Release-213

## Issue
I understand that there's a lot of changes going on with the mechanics for Oil as stated on #16714. However, with this build set to be released for prod, it just doesn't make sense as to why a Pumpjack would have a pipe output port. It has no explanation or information about it. There's also no Pipe tab that details the need for pipes.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/5f45cb2c-8ccd-4633-9e72-b358dab10e02)

It doesn't even connect with pipes too. This is quite confusing, especially for players.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/82e39f86-3c15-473a-a48b-7a3ab40f1a2e)

It would also be great if the output pipe is repositioned near the stuffing box.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/07ba6172-415a-4516-bcda-d87b94389406)
Such as:
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c9eb799d-9691-431a-ae7e-dcb2a15fa653)

**Comment by WeaselDog** [comment]
This is actually part of the pipes remake and will add an explanation for this when this happens.
