### ISSUE TITLE
Election POPUP "RUN for an office" Firefox 55.0.3 (32-Bit) closed direct

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2157]
you cant edit. What a Brower you support ?

**Comment by REPOSEECO** [comment]
IF i put the Adress in MS Edge --> 
![grafik](https://user-images.githubusercontent.com/26040573/30511200-29384114-9ad4-11e7-8a6e-14fb659811bc.png)

**Comment by rainfarmer** [comment]
It means you are not logged in.
You need to login to the game and connect to your server. 
Then use the election buttons in the bottom right of the game.

That will open the browser with you logged in.

We will add a login feature from the browser in the future.
