### ISSUE TITLE
[0.9.3.2 Release-213]Cvics: Changing Property Owner should have more options

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21574]
Build: 0.9.3.2 Release-213

## Issue
As of this build, the clause 'Change Property Owner' only has one option for the set of property and that's 'All Property'. We should offer a flexible option here. There might be player's who owns scattered properties from small to large land area. For a given server with established players and government, such as the currently owned servers; White Tiger, etc, people in position would probably want flexibility in claiming abandoned properties. For example, properties with areas less than 30m^2 owned by an abandoned account -> transfer to new owner 'President' | properties with more than 30m^2 area, transfer property owner to 'Vice President'. 

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/71e089c3-492a-4e3e-8b73-71992ae44e3b)

**Comment by SlayksWood** [comment]
merged to #17733
