### ISSUE TITLE
[0.9.3.2 Release-213 | 0.9.4 Develop-266]Mouse icon pointer flickers endlessly

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21579]
Build:
- 0.9.3.2 Release-213
- 0.9.4 Develop-266

## Issue
The mouse icon pointer flickers endlessly when pointed around the border of a text with a hint pop up.

#### Repro:
1. Look for a large text word. You can find one inside the Court UI when creating a law.
2. Hover the mouse icon just outside the border of the text.
3. Observe.

#### Video - 0.9.3.2 Release-213
https://images.zenhubusercontent.com/42199084/dad8e12b-23b4-4b68-8082-bc68c5e04c64/2021_04_25_23_56_trim.mp4

#### Video - 0.9.4 Develop-266
https://images.zenhubusercontent.com/42199084/4ebb0e43-7812-4d9d-b9d5-58d280279170/2021_04_26_00_04.mp4

Possibly related to #20135 but the option for hold-ctrl to select sub-tooltips is not enabled.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1995.

Appears to be fixed as I am unable to reproduce it.
Closing.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

Reopening.
The issue can still be observed.
Hover your mouse icon over the Ecopedia icon on the lower right corner of the screen. Next to the minimap.


https://user-images.githubusercontent.com/77248866/120895149-3f7f7b00-c64e-11eb-9e4b-9df707af5886.mp4

**Comment by madpingui** [comment]
Cant reproduce it, idk why would it happen tho, ecopedia button doesnt have a tooltip.

**Comment by Daniel-Magulado** [comment]
After further investigation, found out that something else is causing it entirely since the Ecopedia icon doesn't have a tooltip as mentioned.
Made a separate issue for it #22127 and closing this ticket.
