### ISSUE TITLE
[0.9.3.2 Release-213]Hovering the mouse icon pointer to any buttons on the lobby triggers a clicked sound once

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21575]
Build: 0.9.3.2 Release-213

## Issue
While in the lobby, if you hover your mouse icon pointer on any buttons or at the news Icon, it triggers the audio that plays when you click a button.

https://images.zenhubusercontent.com/47210472/cf8076dd-ed63-4060-a215-3f2b654f7a3c/2021_04_25_22_37.mp4

Only happens once. If you move your mouse pointer icon to others, it will not trigger the audio unless you click the LMB.
If this is an effect design, it should be consistent. If not, then it shouldn't be doing that.

**Comment by madpingui** [comment]
In develop this should be already solved thanks to this PR (https://github.com/StrangeLoopGames/Eco/pull/8377), with the overfixed new component Hover Cursor Switcher it includes the hovering sound.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-287.

Fixed and closing.
