### ISSUE TITLE
[0.9.4 develop] Old tree icons can use an update

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21583]
Some of the older trees have icons that don't match the new theme. We should get them all with same style.

![TreeIcons](https://user-images.githubusercontent.com/47330823/116017844-8dd43f80-a5f5-11eb-8c3c-db6f6ee2c9e3.png)

**Comment by keegan-o** [comment]
Which ones specifically do you mean? If you look at icon then look at real tree in game, they match the different styles we have in-game as well.

**Comment by keegan-o** [comment]
Cedar needs an update to be a conifer, but the actual tree itself needs that update too.

**Comment by WeaselDog** [comment]
If this is the art style we go with, can mark as won't fix and close. The block style trees just look significantly different to me.

**Comment by keegan-o** [comment]
I agree, it's just that... so do the actual trees in-game! Someday we may upgrade their look and in that case we would change the icons too. I will close for now.
