### ISSUE TITLE
[0.9.4.0 develop] Huckleberry Species missing icon

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21584]
The Huckleberry species has no unique icon. It just reuses the Huckleberry item.

![HuckleberriesIcon](https://user-images.githubusercontent.com/47330823/116018200-67fb6a80-a5f6-11eb-862f-b2b6e0597784.png)

**Comment by keegan-o** [comment]
Daria I am assigning this to you as a first test so we can see if you will be a good fit for helping with icons in Eco-- it would be very nice to have another artist on the team who can work on icons.
