### ISSUE TITLE
[0.9.4 develop] Education Information in Skills Overview in Ecopedia should hid when disabled

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21582]
All this information about education in Skills Overview should be hidden for 9.4 when EducationEnabled is set to false. It is disabled by default. 

![EducationInfo](https://user-images.githubusercontent.com/47330823/116017161-ad6a6880-a5f3-11eb-8b9e-927f14ff04e1.png)

**Comment by gabrielgindridev** [comment]
Will be like so:
Off: ![image](https://user-images.githubusercontent.com/65634950/117190497-e1911680-adb5-11eb-9cf1-5561c234a365.png)
On: ![image](https://user-images.githubusercontent.com/65634950/117190626-0eddc480-adb6-11eb-934d-ee7e36eaa8be.png)
