### ISSUE TITLE
[0.9.4 develop-266] Objects are not always displayed in the world

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21591]
There are places where whatever you place, it is not displayed. This is register on the server, but not visually visible. If you try to place something else there, it will be an error that another object cannot be placed here.
Client restart is not fix this issue, we can't check server restart.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/21449
