### ISSUE TITLE
Modkit: Modkit documentation and DLL reference site

### ISSUE THREAD

**Issue by thetestgame** [StrangeLoopGames/EcoIssues#21594]
Currently modders have very little information to go off for modding. There is currently an open issue to copy the xml docs with the dlls we ship with the modkit. However we could take this a step further and have a full fledged documentation site we automatically generate from those dlls with hand written pages for tutorials and other things worth documenting about the modding process. 

XML issue: https://github.com/StrangeLoopGames/EcoIssues/issues/21024

**Comment by StallEF** [comment]
we have one abandoned place where everyone will be comfortable, I think
https://github.com/StrangeLoopGames/EcoModKit/wiki
