### ISSUE TITLE
Feature Request: Copy whole stack of item from chest to backpack and vise versa

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2159]
By using ctrl key for example

**Comment by MarjieAVolk** [comment]
I take it this is a feature request and not a bug?

**Comment by Fank** [comment]
Yep

**Comment by MarjieAVolk** [comment]
Closing in favor of https://github.com/StrangeLoopGames/EcoIssues/issues/4280 since there is more discussion there
