### ISSUE TITLE
CW Config manager needs description for new users.eco format

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21598]
![image](https://user-images.githubusercontent.com/25908592/116195279-4bfce380-a732-11eb-9ba3-3bc32850dedf.png)

Got three sections to add user ids too, but you dont know which one is mutes, which is bans and which is admins, as they are just empty without any description.

**Comment by j3fffff** [comment]
i think its a css dark mode issue

**Comment by D3nnis3n** [comment]
Doesnt have any text for me in light mode there either

**Comment by j3fffff** [comment]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/9a47d215-2fd1-4ec6-b301-f0a3fb443298)
@denys probably related to config changes.

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod. But guys, make the nesting standard! Thanx ;)

**Comment by Ry4ndrew** [comment]
Retested and confirmed fixed. Thanks.
