### ISSUE TITLE
USER ISSUE: [0.9.3.2] I have not been cheat moving, just auto running

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21608]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
Auto run for a while I guess?

**Expected behavior:**
Should not be kicked out for running

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60,00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@ThePiachu Thank you for the report. merged to #21609
