### ISSUE TITLE
[0.9.4 Develop-267]Missing icon art display for Beaver, Marmot, and Prairie Dog

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21603]
Build: 0.9.4 Develop

## Issue
Missing Icon Art for Beaver, Marmot, and Prairie Dog.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/3fc3f40e-0748-4e98-8402-feb9d958ec4b)
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/f5ef8067-f086-4389-bfe6-dd0b51872291)

**Comment by keegan-o** [comment]
fixed in master, not sure why these got nuked when they have existed for ages, something about them finally existing for real now @WeaselDog @serpopov
