### ISSUE TITLE
Inactivity Popup on Staging Server after action with inventory

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2160]
Log in and after a few minutes you get an inactivity Popup an you kicked out.

**Comment by REPOSEECO** [comment]
Hint ?
![grafik](https://user-images.githubusercontent.com/26040573/30519604-eb1c6172-9b9a-11e7-82e0-e018c84272c0.png)

**Comment by metachronism** [comment]
any info on what you were doing beforehand?

**Comment by SeanAtr0n** [comment]
I was also getting inactivity every time i attempted to place a farmers table.

**Comment by REPOSEECO** [comment]
@metachronism no Idea
What you can do is reboot the Server an than i inform you if it happen again :-)

**Comment by metachronism** [comment]
these should be fixed in upcoming build
