### ISSUE TITLE
[0.9.4 Develop-267]Error when trying to vote | Game thinks I'm not logged in

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21605]
Build: 0.9.4 Develop-267

## Issue
When trying to vote, the website page for voting shows an error stating 'Error: You are not logged in' but I am logged in and it is clearly stated on the menu bar on the left side of the website page.

#### Repro
1. Initiate an election.
2. Vote manually.
3. Observe.

#### Actual Result
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/47088d41-5aa8-40cd-b7a0-c756675a04bd)

**Comment by Ry4ndrew** [comment]
This might be related to the recently reopened issue #8041.

**Comment by j3fffff** [comment]
its on develop build.
possible mixup with develop auth.

@Ry4ndrew can you repeat it for develop? and if so on that, what about staging?

**Comment by Ry4ndrew** [comment]
@j3fffff I just ran it on the same build and I'm not able to produce the issue.
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/a54930b6-4dd7-4fe8-bd31-b11c478925eb)

I speculate that it is related to the issue that I linked it to as sometimes I am not able to touch Advanced Options due to some authentication issue then it gets fixed and I am once able to start messing with Advanced Options.

**Comment by j3fffff** [comment]
auth for cw ui, and elections page are quite different and usually unrelated. but its possible.
Also, the issue you linked, is closed, is it still an issue?

@Daniel-Magulado is this still happening for you?
could also be related to your account specifically not being in develop accounts db

**Comment by Daniel-Magulado** [comment]
@j3fffff 

Yes, it's still happening on my end. The screenshot below with the latest build of develop 290.
![image](https://user-images.githubusercontent.com/77248866/119063163-02d74100-ba0b-11eb-8d29-9f286e1ccc9b.png)

**Comment by Ry4ndrew** [comment]
@Daniel-Magulado have you logged into the server before voting?

**Comment by Daniel-Magulado** [comment]
@Ry4ndrew 

This is via Steam.
I tested on 0.9.3.4 Release-226 and I was able to vote.
![release](https://user-images.githubusercontent.com/77248866/119065736-c870a280-ba10-11eb-8f5e-821f9b6281e6.jpg)

However, I tested on both Staging-1988 and Develop-290. I got the same error.

I reproduced doing the same repro steps.
1. Start game on Steam.
2. Spawngov
3. Vote manually on the website.

So I'm not certain what you mean about logging into the server before voting. :)

**Comment by Ry4ndrew** [comment]
@Daniel-Magulado oh I meant to log into the server through the client.

@j3fffff can confirm the issue does happen on both Staging-1988 and Develop-290.

**Comment by j3fffff** [comment]
@Daniel-Magulado just synced staging db with production db, 
so if there was issue with your account missing on staging db, that might fix this issue.

@redwyre for develop branch builds, what auth is it using?

**Comment by Daniel-Magulado** [comment]
@j3fffff 
I tried on Steam with build 0.9.4 Staging-2004.
Still the same issue.
![image](https://user-images.githubusercontent.com/77248866/120500675-9dfced00-c3f3-11eb-8b13-3fa21e5ce95e.png)

**Comment by j3fffff** [comment]
ok, so its not an accounts issue.

ironically, we just finished a complete elections refactor.
so thinking all election issues like this should be retested in the new system. 
what do you think @Ry4ndrew ?

**Comment by Ry4ndrew** [comment]
@j3fffff yep, I believe a retest is in order. I'll get started on it soon.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2021.

Tested with multiple accounts including accounts of @TwixterZ and @SlayksWood. The issue is still happening. The game still thinks that I'm not logged in.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/52c64707-388f-4356-8600-a988735b6fa2)

**Comment by j3fffff** [comment]
It means, that gameServer rejects authtoken which it just send to ElectionsUI by pressing G in game...
@WeaselDog Need to ask GameDev to ask why authtoken stops to be accepted by GameServer
Probably Game generates authtoken incorrectly for Steam accounts.

**Comment by denysaw** [comment]
@redwyre @mirasrael Assigning you guys, cuzz as you know ElectionsUI is just a "proxy", which passes received by pressing `G` in-game `authtoken` with each request to GameServer. So we can do nothing on our side to fix the problem, that authtoken for steam users doesn't fit in anyway into GameServer. So probably it's GameServer or Auth issue. But if you'll need my help (to receive/pass some new parameter or if you'll see, that authtoken stops to pass somehow), please create an issue with a description of what is need to be done on my side and I'll implement it ASAP. Thanx ;)
