### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Krisbran** [StrangeLoopGames/EcoIssues#21613]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
use the powered cart when pressing E on it upon getting off it it shoudl immediately kick you with the given error

**Expected behavior:**
let me off the powered cart

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods are installed or plugins only things different from earlier today was that we updated to 9.3.2

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Krisbran Thank you for the report. merged to #21609
