### ISSUE TITLE
USER ISSUE: Detect as a Cheat while running

### ISSUE THREAD

**Issue by Kosmicray** [StrangeLoopGames/EcoIssues#21615]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
I don't  know just running as usual

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No differents mods since previous update

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Kosmicray  Thank you for the report. merged to #21609
