### ISSUE TITLE
USER ISSUE: Litteraly just crafting things in my base and getting banned

### ISSUE THREAD

**Issue by BenoitRichard1212** [StrangeLoopGames/EcoIssues#21610]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
As soon as I do anything at all I get booted of servers for movement cheating. YET, I do not have mods nor cheat installed.		

**Expected behavior:**
Not kick me, I payed 30 dollars for this lol what is wrong.

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@BenoitRichard1212 Thank you for the report. merged to #21609
