### ISSUE TITLE
USER ISSUE: [0.9.3.2] Failed to handle RPCResponse

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21618]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
I was going through EcoWiki, trying to refresh Asphalt Concrete. Didn't see any response, so I clicked it multiple times and now this.

**Expected behavior:**
Not this.

**Actual behavior:**
The following error message popped up:
```
Failed to handle RPCResponse
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I'll be merging this with the other similar issues.

Thank you.

#21486
