### ISSUE TITLE
USER ISSUE: Cheatmovement Jumping around

### ISSUE THREAD

**Issue by Martino80** [StrangeLoopGames/EcoIssues#21614]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
First Jumping over a Wall, then jumping over a Wood Cart and now jumping over a Chest is registered as Cheat movement. What crazy gamebehaviorregestry did you guys implemented with this update 0.9.3.2 beta release-217

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Idea about Mods. Its an open Server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Martino80 Thank you for the report. merged to #21609
