### ISSUE TITLE
USER ISSUE: I'm not cheating

### ISSUE THREAD

**Issue by Brodaag** [StrangeLoopGames/EcoIssues#21612]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
Start game

**Expected behavior:**
Not kick me out

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Brodaag Thank you for the report. merged to #21609
