### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Kriigare** [StrangeLoopGames/EcoIssues#21617]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.2 beta release-217

**Steps to Reproduce:**
I don't know because it happens anytime 

**Expected behavior:**
I can play normaly

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Kriigare Thank you for the report. merged to #21609
