### ISSUE TITLE
Minor bugs/QoL notes 9.3.1 

### ISSUE THREAD

**Issue by armyofskankz** [StrangeLoopGames/EcoIssues#21624]
Have put a few hours into the newest version - wanted to point out a few things, nothing game-breaking or high priority.

1. Moon Jellyfish - can no longer be processed by the fishery as it does not have the appropriate tag.
2. Balance- need to butcher a lot of meat to feed the population. But there is very little use for the leather and furs, so it ends up where I'm just stockpiling those.
3. Seeds, when throw out, become trash. These are organic - shouldn't they become compost? 
4. Having pipes in a building /building blocks. Visually, is there any way to create a wall/roof with a pipe running through it that would function as both a building block and pipe. I just don't like have the open space around the pipes when building it into a wall.

**Comment by IcedForge** [comment]
Thank you for reporting.

1. Thank you for alerting this, will create a separate issue for this.
2. Balance is something we are constantly working on improving and tweaking so much appreciated input.
3. Seeds turns into compost if they are one type of object in a trash bag and if you have multiple different types even if they are compost items they might cause trouble.
4. We are looking into upgrading our utility system completely in the future so there will be improvements made in the future to remove this.


Will close this and add comments and create new issues for relevant parts.
