### ISSUE TITLE
USER ISSUE: Void Storage

### ISSUE THREAD

**Issue by nkartapanis** [StrangeLoopGames/EcoIssues#21620]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.1 beta release-204

**Steps to Reproduce:**
Evicted -> Stuff in Void Storage

**Expected behavior:**
I should be able to take my stuff

**Actual behavior:**
Took stuff from top --> didnt refresh empty slots
Cant scroll downCant see bottom bar slots going over it

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@nkartapanis Thank you for report, will be fixed in 9.3.x hotfixes
