### ISSUE TITLE
Invite overwrote my tier

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21626]
Had an invite sent out, but copied it browser first. Hours later, when i logged in the possibly set cookie triggered and 'upgraded' my account from developer status to beta tier 4.

**Comment by Ry4ndrew** [comment]
Can confirm the issue happens:

Step to reproduce:
1. Create an Admin invite
2. Use it @http://play.eco/game/key/GAMEKEY (_Make sure you are logged out_)
3. Click on the link to Register new account
4. Close the Registration tab (_Don't create a new account_)
5. Open a new play.eco site
6. Log in to any Dev Tier or Wolf Tier Account
7. Account is "Upgraded" to Beta Tier

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod.

**Comment by Ry4ndrew** [comment]
Rested and fixed, but I feel like this popup shouldn't appear.
![image](https://user-images.githubusercontent.com/49683923/116840531-c503ab80-ac08-11eb-8b22-8745c4726236.png)

The user should just log in as if nothing happened.
