### ISSUE TITLE
9.3.3 - Multiple users kicked at once NRE contracts

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21628]
Multiple users all kicked at once

--BEGIN DUMP--
Dump Time
04/28/2021 18:10:05

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'NameToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Clauses' of 'Eco.Gameplay.Economy.Contracts.Contract'
Error during packaging property 'Contents' of 'Eco.Gameplay.Economy.Contracts.ContractClauseTransport'

--END DUMP--

![image](https://user-images.githubusercontent.com/61889138/116444987-434d0000-a84d-11eb-81d2-3a13cb76b14f.png)

![image](https://user-images.githubusercontent.com/61889138/116445009-49db7780-a84d-11eb-9d75-2138c368bc4b.png)

**Comment by IcedForge** [comment]
Need to do a proper overhaul over contracts in general as there seems to be a lot of weird behavior going on both with permissions, payouts and assorted systems.

**Comment by SlayksWood** [comment]
the same issue #19906, but we have it for a long time
