### ISSUE TITLE
Carved Pumpkin new art + icon + update lighting effects in prefab (Phlo)

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21629]
Build:
- 0.9.3.3 Release
- 0.9.4 Develop-268

## Issue
Tested on both stated builds. The Carved Pumpkin object doesn't really appear to be a carved pumpkin.
![image](https://user-images.githubusercontent.com/77248866/116457149-a2366780-a895-11eb-80a5-9b6ef4a8e665.png)
The lines around the Pumpkin can be seen behind the spooky face/mask. It can be most visible during the day as if it appears that there's no form of carvings at all.

#### Expected Result
![image](https://user-images.githubusercontent.com/77248866/116458314-16bdd600-a897-11eb-814a-65c5a3df902d.png)
- Can we get a new and better-looking carved pumpkin? Right now, it's a good item to have as a light source with unlimited fuel especially for starting players. It's more useful than the Torch and the Torch Stand.
- Its Icon also needs some update. It should display the actual appearance of the item. The current icon uses a simple pumpkin asset with a different background color.
![image](https://user-images.githubusercontent.com/77248866/116458999-db6fd700-a897-11eb-86a0-1d900ad2c05d.png)

**Comment by keegan-o** [comment]
@WeaselDog Maybe we should consider requiring fuel for pumpkins so they don't become default light sources lol

**Comment by keegan-o** [comment]
Once Daria is finished with the updated art, finish the lighting set-up in the prefab please @Phlo123
