### ISSUE TITLE
[0.9.3.3 Release-219 | 0.9.4 Develop-268]Food for Forage tutorial can be triggered after completing Empty Stomach tutorial

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21633]
Build:
- 0.9.4 Develop-268
- 0.9.3.3 Release-219

## Issue
The **Food for Forage** tutorial can still appear after completing the **Empty Stomach** tutorial. This should not happen as both tutorials teach players the same thing. The only difference is the requirement to trigger them. Once either of them is triggered, the other one should never appear unless if the triggered tutorial is skipped.

**Note**: This issue requires certain steps to trigger. Simply completing the **Empty Stomach** tutorial will not cause this issue to occur.

#### Reproduction Steps
1. Do not pick up any food and empty your avatar's calories reserve to trigger **Empty Stomach** tutorial.
2. The tutorial will require you to pick up 4 different crops for food. Obtain only 3 of them.
3. Before obtaining the 4th crop to complete the tutorial, try to look for a nearby crop that was not requested in step 2.
4. Complete the **Empty Stomach** tutorial and immediately pick up the nearby crop that you spotted on step 3.
5. Observe.

#### Actual Result
After completing the **Empty Stomach** tutorial, the **Food for Forage** tutorial can still appear.
https://images.zenhubusercontent.com/42199084/487144e2-4ac3-4d24-a8ff-886fb20d0a39/eco_2021_04_29_04_46_trim.mp4

#### Expected Result
If the player triggers the **Empty Stomach** tutorial, then the **Food for Forage** tutorial should never appear unless if skipped as stated at #19350.

**Comment by madpingui** [comment]
Cant replicate it, because everytime i finish the empty stomach tutorial the Food for Forage tutorial shows but its completed immediatly.
https://images.zenhubusercontent.com/47210472/8b7e2aa5-982d-4f5d-a6d2-02a8a36fc75f/2021_05_24_15_58_25.mp4

**Comment by Daniel-Magulado** [comment]
@madpingui 

Tested on 0.9.4 Staging-1990.

To reproduce it, try to do it in an area where there is a lot of variety of crops.

Attached is a video of the reproduced issue on the stated build.

https://user-images.githubusercontent.com/77248866/119441246-625d8580-bd58-11eb-8ec9-e55f2d073e50.mp4

What happened in your video is that there isn't much of a variety of pickable crops in the area. So when Food for Forage appeared, it immediately got completed because it selected crops that you already picked.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.
It's far easier to reproduce this issue now.
Simply follow the empty stomach tutorial and there's a good chance that you will trigger the Food for Forage tutorial.

**Comment by johnkslg** [comment]
Its ok that these appear in different orders, they teach different things.
