### ISSUE TITLE
USER ISSUE: PAID TO WIN

### ISSUE THREAD

**Issue by Twinkiees** [StrangeLoopGames/EcoIssues#21638]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
server paye to Wins

**Expected behavior:**
server paye to Wins + abus des admin ++

**Actual behavior:**
ne devrais pas etre en ligne

**Do you have mods installed? Does the issue happen when no mods are installed?:**
server paye to Wins

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please send details about this - including which server it is and how they offer 'pay to win' - to dennis@strangeloopgames.com.
