### ISSUE TITLE
USER ISSUE: Disconnect Button close the Game

### ISSUE THREAD

**Issue by nickbrick03** [StrangeLoopGames/EcoIssues#21630]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
1. Join on any Server
2. press ESC
3. click on Disconnect

**Expected behavior:**
you disconnect from the Server and get back to the Main menu

**Actual behavior:**
instead the game closes

**Do you have mods installed? Does the issue happen when no mods are installed?:**
It issues with and without Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6394700/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6394701/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of this issue.
You can track the latest update about this issue here #21517.
A fix will soon be rolled out in the next following game updates.

Thank you.
