### ISSUE TITLE
Declunkify: Storage Filters

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21635]
Add the same filter dialog available in the economy viewer to the storage tab.  This will be added in multiple places

- Add a 'display filter' button, which will show only storages containing the given element. The filter should be described visually as well, so its easy to see that youre viewing a filtered view.  Should also have a button to clear it. 
- Add a 'contents filter' on each storage, this can be set to allow only the given types to be stored in it. 

Make a mockup of how this will work first.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.5 Develop 298

![filter.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/995643cd-3174-46e6-a462-7e4e372f005d)
