### ISSUE TITLE
USER ISSUE: [0.9.3.3 beta release-219] Work Party - Disconnect - Could not find setter SetObjectToEdit

### ISSUE THREAD

**Issue by leachiml** [StrangeLoopGames/EcoIssues#21631]
Username: leachiml
User ID: slg110968

When Creating a Workparty, if you change the "Payment" Parameter in the Configure Payment Window to something else like "Knowledge Share Payment" you get a Disconnect with following error:

![Error#1](https://user-images.githubusercontent.com/34484044/116474525-e7986c00-a878-11eb-82c2-6ca84fedbea4.PNG)

Log File:
[Error log#1.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6394874/Error.log.1.txt)

**Comment by Daniel-Magulado** [comment]
Merging with #21718
