### ISSUE TITLE
[0.9.3.3 beta release-219]Zoning office / District maps only detect first district map in bundle elections whith multi references

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21641]
When refering multiple districts inside 1 district map the election only detects the initial district and not any other.

Reproduction

1. Place zoning office and draft a district map, add 3 districts.
2. add a census table and add 3 demographics, set each different demographic limits to required of to resident in each district.
![Screenshot_64](https://user-images.githubusercontent.com/24981362/116530304-2a405f80-a8de-11eb-8d98-c8f40882b000.jpg)
3.Add all these objects into the same election bundle and notice that the initial district is not included in the error "References set but not included in the current election"

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/117959858-14428e00-b325-11eb-9092-a4594cc2b013.png)
![image](https://user-images.githubusercontent.com/45708377/117959758-fe34cd80-b324-11eb-8165-a165e0bcf983.png)
