### ISSUE TITLE
USER ISSUE: Resetting Carts

### ISSUE THREAD

**Issue by Acritika** [StrangeLoopGames/EcoIssues#21645]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
1. Position Cart on ramp (dirt ramp used)
2. Mine a block at the declining end of the ramp

**Expected behavior:**
The cart should retain the position and angle that it was left in

**Actual behavior:**
When inside a tunnel, mining blocks at the end of the ramp cause the cart to reset its position a block above where it was left and sometimes collide with the adjacent walls/ceiling.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6399165/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6399166/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I'll be merging it with the already reported issue.
#20764
Thank you.
