### ISSUE TITLE
[9.4 Develop 269] Character Creation camera angle

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21642]
When joining a new world, immediate camera angle on character creation screen shows the back of the character instead of front 

_p/s: theres also report from other QA mentioning they had camera angle from below character instead._

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/556de978-b9cc-4d48-9453-5fc9ac14765e)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/119089723-46ce4400-ba13-11eb-86c7-4bd3a93e1e7d.png)
