### ISSUE TITLE
[0.9.4 develop-270] Local Server match score issue

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21643]
Local server show ping -, so it reduces score for my own server. So I have -1993:
![image](https://user-images.githubusercontent.com/45708377/116539014-f589d380-a8f0-11eb-942b-6b26ab6f4c57.png)

**Comment by madpingui** [comment]
I can't reproduce it. Tested in staging branch editor and in staging build in steam
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/ef5d844b-7761-4280-853a-497eca4653c4)

**Comment by SlayksWood** [comment]
Hm, can't reproduce it too in 0.9.4 staging-1988. Closed for now.
