### ISSUE TITLE
Better movement keys for inventory 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21658]
![image](https://user-images.githubusercontent.com/3536496/116597149-172b9080-a8da-11eb-9504-a76e41869d80.png)

'Moving all' should be a main one, and on shift or control.

**Comment by beastyn** [comment]
@johnkslg did not quite get what do you mean. Moving all is already with Shift (Shift and drag) though I can place it on top of a tooltip.

**Comment by beastyn** [comment]
No reason to change hotkeys like that, we should make setup for them in the control settings
with this
StrangeLoopGames/EcoIssues#21658

**Comment by TwixterZ** [comment]
Fix observed and confirmed as of 0.9.5 Develop-305.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/49c94ea0-a406-4a56-bb2a-55bdfa48db21)
