### ISSUE TITLE
Audio of river is cutting out

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21650]
https://drive.google.com/file/d/16_FSyBXOJdNdHv8fTvUlfuaotUb1iq0Y/view?usp=sharing

It's also too loud

**Comment by gzatravkin** [comment]
@Quadbro seems like it's related to this one https://github.com/StrangeLoopGames/EcoIssues/issues/16980 which afaik requieres big refactoring

**Comment by madpingui** [comment]
The loudness is preferences and its duplicated with this #16980
