### ISSUE TITLE
Animal get-up delay time is not happening. They go skidding off while half standing.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21652]
This used to work.  Saw it on a fox.

**Comment by TwixterZ** [comment]
Fix observed and confirmed as of 9.4 Staging 2008

![Turkey.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/a2b8e1ed-3862-4c34-ac0d-3d104a7ce244)

![Ram.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ef038484-34aa-4cb7-a619-39aaf6789476)

![Deer.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/0609dd70-1625-41d9-b512-2966632bb249)
