### ISSUE TITLE
Declunkify: Animals constantly shoving me around

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21668]
Make them not able to do so.

**Comment by TwixterZ** [comment]
Fix tested as of 9.4 Staging 2021, animals still able to shove player, but I have not encounter where animals able to shove me continuously.

Further observation required

**Comment by SlayksWood** [comment]
Well, there seems to be improvements, but it rarely works. In 80% cases animal will run through player.
So I find a point where a lot of animal run. Spawn more animals and check 
video: https://drive.google.com/file/d/1mD6EKWYyTK3CEEik_m5B4meMuovIvedY/view?usp=sharing
