### ISSUE TITLE
Chopping tree sound broken

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21660]
https://drive.google.com/file/d/1OrY6WiVBCn7t2Jkou5ZZFfoC5rcBWpcC/view?usp=sharing
- The tree chop sound isnt heard at all
- When the tree falls over, you just get super loud glitchy sounds. It doesnt sound like a tree falling at all.

**Comment by gzatravkin** [comment]
Maybe it's related to lag or other players
