### ISSUE TITLE
Tutorial movement glitch when one is finished. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21661]
![anim](https://user-images.githubusercontent.com/3536496/116598258-763dd500-a8db-11eb-926b-dce01f893aeb.gif)
When a tutorial finishes, the other tutorial icons jerk around.
Make them smoothly transition where they're supposed to go.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

The glitch appears to be fixed but this introduced some kind of flicker for the newly added tutorial banners. It flickers once before it settles in.

Reopening.

The flicker happens around 3 seconds in the video below.

https://user-images.githubusercontent.com/77248866/120832206-f8807f80-c592-11eb-95bb-adaf8f2cb2c0.mp4

**Comment by TwixterZ** [comment]
Fix checked and confirmed as of 9.4 Staging 2012

![tuto2.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/2463c57e-1656-454e-a439-0d23d4a890d3)

![tuto.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f3aa3ae1-3deb-499e-915e-259fbd9e95cc)
