### ISSUE TITLE
Improve title UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21665]
![image](https://user-images.githubusercontent.com/3536496/116599759-58716f80-a8dd-11eb-965c-6d7715625691.png)
- Shrink all UI except the Eco title by 50%-70%, its annoyingly big.
- The giant blue bars + dark background stripes dont work for me.   Lets make it just a darkened gradient.
- The 'Logged in as JohnK' is unreadable because it has no background.
- Remove vivox label and stick it in the escape menu somewhere instead. 
- Add Depth of Field to the title screen camera so it fades the distance some more, and maybe the foreground. Make it look nice.
- Give the camera some slight continuous motion, probably looking left to right very slowly on a loop.
- Make the metor rise through the middle of the screen after a couple seconds.

**Comment by TwixterZ** [comment]
Improved title screen observed as of 9.5 Develop-368
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ae89f8d3-3e84-434e-b274-14632d72a78b)
