### ISSUE TITLE
Declunkify: Work-order popups and action-popups need to be integrated

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21676]
![image](https://user-images.githubusercontent.com/3536496/116603232-8ce72a80-a8e1-11eb-91ff-71910bac7368.png)
They overlap here and it looks bad.  We need to make them part of the same system somehow. 
Its also just really cluttered looking.  Need to redesign this.

**Comment by ptitducanh** [comment]
This ticket is now being track here: https://github.com/StrangeLoopGames/EcoIssues/issues/22216
