### ISSUE TITLE
Speed up hammer pickup animation

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21672]
Its quite slow atm

**Comment by SlayksWood** [comment]
we can change speed with tier too:
#13115
> Maybe its better to make speed like
> stone = 1
> iron = 1.1
> steel = 1.2
> modern = 1.3

**Comment by SlayksWood** [comment]
We can increase hammer speed with tier too:
#13115
> Maybe its better to make speed like
> stone = 1
> iron = 1.1
> steel = 1.2
> modern = 1.3

**Comment by WeaselDog** [comment]
Some tools you only need to press and it completes the full action. It should be like this with the hammer too.

**Comment by Quadbro** [comment]
Adjusted hammer speed to 1.8 for all,, looks fast and do not breaks anything. REmoving that animation completely is possible,, but i think its not needed with such speed.
(Modern hammer had 1.6 in speed). 3-rd person is adjusted too.

**Comment by SlayksWood** [comment]
@Quadbro Animation in 3rd person view is weird and wrong. I picked up 20 times, but animation was near 27 times.
Also it looks  too fast for me in 1st person view.

**Comment by SlayksWood** [comment]
Previous comment is for another issue #https://github.com/StrangeLoopGames/EcoIssues/issues/19058

**Comment by SlayksWood** [comment]
I'd not to close this one. I don't like to have 1.8 speed for hammer in any person view. It looks unnatural.
But with a new controls in 3rd person view (And I guess in 9.3 without new 3rd person view controls) using hammer with speed 1.8 is uncomfortable. 
Want proof? /bt 2,10,4,10,1,1  ; /give stockpile; /give stone hammer and pick up this house in stockpile in 3rd person view:
![image](https://user-images.githubusercontent.com/45708377/119124003-da663b80-ba38-11eb-91b1-bfd575d7e1f9.png)
With such a speed, if you want to pick up block with each hit you have to try.
