### ISSUE TITLE
Clicking rapidly led to placement errors that shouldnt have been displayed.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21673]
![image](https://user-images.githubusercontent.com/3536496/116602413-8a380580-a8e0-11eb-9275-d36db60be431.png)
while placing with hammer

**Comment by Moritur** [comment]
Reproduction steps:

https://user-images.githubusercontent.com/44618240/119334749-c23a2a80-bc8b-11eb-994a-17d6b1756bca.mp4

Looks like rapidly placing too many blocks makes client stop synchronizing blocks with server until client restart
