### ISSUE TITLE
[9.3.3 Release-219 | 9.4 Develop-270] Stockpile UI stuck after opening Form UI 

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21678]
Build:
- 0.9.3.3 Release-219
- 0.9.4 Develop-270

## Issue
The Stockpile UI can get stuck if you open the Form UI while Stockpile UI is still active. Clicking the X button to close the UI doesn't close it.

#### Reproduction Steps
1. Get a hammer and make it your active tool. (any hammer will do)
2. Store a Hewn Log into a Stockpile. (Not specific to hewn log, any carryable item with form option)
3. Interact with the Stockpile in step 1.
4. Drag the Hewn Log into the Carrying active box.
5. Do not close the Stockpile UI. Drag your mouse icon and hover it over the Floor form and click it.
6. Close the Form UI.
7. Close the Stockpile UI and observe.

#### Actual Result
https://images.zenhubusercontent.com/47210472/49a025c7-4482-4db9-8445-04369a8f4c37/eco_2021_04_30_03_39.mp4

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2021
