### ISSUE TITLE
Some recipie / efficiency / quantity combos don't work

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2167]
Camas Mash w/ lvl 4 campfire cooking efficiency never completes when cooked in bulk. Probably a bug w/ the code that figures out when to output items. Cooking 5 mash gives an equation that isn't easily divided
9 camas + 4 tallow -> 5 camas mash

Cooking a single camas mash works for me, but then i'm wasting ingredients.

**Comment by MarjieAVolk** [comment]
Fixed
