### ISSUE TITLE
Pick new font

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21686]
One of the reasons our UI feels clunky is because all the elements are so large and make the interface feel busy.  The fonts contribute to this: they are often displayed directly over the game, and thus have a shaded background to the letters.  

Most of the time this isn't needed.  Introduce a new thinner font that is used in 90% of places, leaving the shadowed-font only where it overlaps the game world. And even in those cases, we will experiment with adding shaded backgrounds for the whole sentence, rather than each individual letter.

**Comment by MilenkoTunjic** [comment]
the font we use can be much improved just by removing the bold option (which is randomly used everywhere) and setting the font size to a reasonable size
which is in our case random and unnecessary big- i.e. we use 18- 35 font sizes which is pretty damn big. If you try typing the document at those font sizes it would look like kids letter
another thing is our spacing- distance between the letters in the word, distance between the words and distance between rows of text.
If we would clean those up, it would look neat even with the current font, and if it does not get fixed, whichever font you chose would look equally silly.
that is my opinion of which I am certain about 75 %
So, setting regular text to be somewhere in the range of 12-14 size, Subtitles to be 16-18 font size and titles in 18-22 range (experimenting until it looks right and then locking it in) and then doing the same for spacing between letters, words and rows of text would much improve the overall look. And getting rid of all the text effects (bold/underline/drop shadow) and deciding on the uniform approach (perhaps only titles get bold treatment) but test it out to see if it is better like that.

**Comment by johnkslg** [comment]
Changed font and removed bold.
Next step it to go through UIs and adjust sizings.

**Comment by D3nnis3n** [comment]
While we are at this, we still have massive complaints about the Constitution Font not being readable - and I can't read it myself either. Handwriting in Italic is a pain for disabled people and for most normal people nowadays, not really their fault. We should pick a constitution font that looks old and is actually readable by our audience.

**Comment by D3nnis3n** [comment]
Also some random stuff:
![image](https://user-images.githubusercontent.com/25908592/117385903-3c299000-aee6-11eb-9892-190858d8b95e.png)
![image](https://user-images.githubusercontent.com/25908592/117385910-3f248080-aee6-11eb-9a51-c1d4ac8b2762.png)
![image](https://user-images.githubusercontent.com/25908592/117385927-477cbb80-aee6-11eb-8a86-e43d085bc35b.png)

Which for me certainly is a problem.

![image](https://user-images.githubusercontent.com/25908592/117385971-5b282200-aee6-11eb-87b6-84766bea7d27.png)
![image](https://user-images.githubusercontent.com/25908592/117385988-62e7c680-aee6-11eb-8715-beb32bb810b7.png)

**Comment by johnkslg** [comment]
> Also some random stuff:
> ![image](https://user-images.githubusercontent.com/25908592/117385903-3c299000-aee6-11eb-9892-190858d8b95e.png)
> ![image](https://user-images.githubusercontent.com/25908592/117385910-3f248080-aee6-11eb-9a51-c1d4ac8b2762.png)
> ![image](https://user-images.githubusercontent.com/25908592/117385927-477cbb80-aee6-11eb-8a86-e43d085bc35b.png)
> ![image](https://user-images.githubusercontent.com/25908592/117386912-0ab1c400-aee8-11eb-8a61-1248e4ab2bb2.png)
> 
> Which for me certainly is a problem.
> 
> ![image](https://user-images.githubusercontent.com/25908592/117385971-5b282200-aee6-11eb-87b6-84766bea7d27.png)
> ![image](https://user-images.githubusercontent.com/25908592/117385988-62e7c680-aee6-11eb-8715-beb32bb810b7.png)

I'd like to leave this out of this issue, can be separate.

**Comment by johnkslg** [comment]
Closing this since new font is in, will make separate ones for remaining UI tasks

**Comment by D3nnis3n** [comment]
Moved the others.
