### ISSUE TITLE
USER ISSUE: Oil Refinery Bug with MU2

### ISSUE THREAD

**Issue by AvrCdavr** [StrangeLoopGames/EcoIssues#21688]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
If you use an MU2 on an oil refinery to make plastic, epoxy, and rubber but only queue one item to be made it will give you back all three barrels instead of consuming one of them. If you queue any number after one the recipe is correct.

**Expected behavior:**
It should consume 1 barrel and give back 2 .

**Actual behavior:**
It gives back all three barrels not consuming 1.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
However, this issue regarding about Oil Refinery with Modern Upgrade 2 as its module is not a bug.
It's by design and is intended to do that.

Thank you, and hope you have a wonderful day ahead.
