### ISSUE TITLE
Cant move minimap to edge

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2168]
It pops it out to here:
![image](https://user-images.githubusercontent.com/3536496/30570033-504955e8-9c93-11e7-90ac-241db7ffce52.png)

**Comment by MarjieAVolk** [comment]
Intended behavior - I put a margin around the screen to keep things from going slightly over, and because I thought a small margin looked better - although some UIs are further outside their borders than others, so that's something we might want to work on.
