### ISSUE TITLE
[0.9.3.3] If you spam the sell button during lag, you might do multiple sell orders

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21690]
So we're currently on White Tiger where the government is paying into a meteor store every hour. People are queueing up to it and mashing the "sale" button for minutes on end. I wanted to sell 7 items, but since the store had enough money for twice that, I sold 7 items twice:

![image](https://user-images.githubusercontent.com/964559/116658808-68bd3500-a945-11eb-9af4-d2d5bb4fc2dc.png)

Normally, I'd expect the trade amount to reset back to 0 after a single trade, but nope. I'm guessing the game should do something like creating a unique trade ID when people try to sell something and if the same trade goes in more than once only one of them gets executed.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of issues that go with lag and connection stability.
I'll be merging this to [8278](https://github.com/StrangeLoopGames/Eco/issues/8278)
