### ISSUE TITLE
9.4 Dev 272 - Cannot fuel vehicles

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21699]
The /fuel command is not working on vehicles, on tables it is working without issue ie a kiln

Cannot put fuel into vehicles as it does not accept that fuel type

![image](https://user-images.githubusercontent.com/61889138/116735838-fbfa7700-a9e6-11eb-9305-5e02cf014b48.png)

**Comment by IcedForge** [comment]
Seems like all vehicles have wrong fuel selection format, need to update the tech templates for them.
