### ISSUE TITLE
9.4 Dev 272 - Char ragdoll effect on crossing world border

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21698]
Cross world border whilst in 3rd person and your characters ragdoll freaks out/falls over?

![image](https://user-images.githubusercontent.com/61889138/116735355-45969200-a9e6-11eb-95fc-928f5377b771.png)

**Comment by IcedForge** [comment]
Interesting world wrap effects.

https://i.gyazo.com/73fb2119fa24f93bf545b5555c072ebd.mp4

**Comment by SlayksWood** [comment]
This is still slightly noticeable, but the regression has been removed.
