### ISSUE TITLE
USER ISSUE: Game crash back to desktop

### ISSUE THREAD

**Issue by espencapable** [StrangeLoopGames/EcoIssues#21707]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
Random, 5min into the game to 8h in the game.

**Expected behavior:**
Kept on playing

**Actual behavior:**
Game freezes for 2s and quits. Ends up at desktop.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
For us to investigate this issue, we would kindly request that you upload your game logs.
You can follow the instructions here to provide the log files: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.

**Comment by Daniel-Magulado** [comment]
Hi @espencapable,

Due to a lack of response, we'll be closing this ticket.
Feel free to reopen it if you encounter this issue again.
