### ISSUE TITLE
Unusual election results.

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#21705]
We just had an election and the results seemed off. Its happened a few times in the past as well. the following link is a decent example of instant runoff with multiple victors. https://www.wjporter.com/misc/irvtest1.htm use the following data https://pastebin.com/stdqwQsf (the format was getting ruined). The following are the screen shots of the results in game.

![image](https://user-images.githubusercontent.com/8082068/116750430-72d84580-a9d0-11eb-84d9-4270a9bb4fb3.png)
![image](https://user-images.githubusercontent.com/8082068/116750175-0eb58180-a9d0-11eb-80bc-fb29ee0075a4.png)
![image](https://user-images.githubusercontent.com/8082068/116750305-3efd2000-a9d0-11eb-8fbf-d7ae1b28d650.png)
![image](https://user-images.githubusercontent.com/8082068/116750346-50dec300-a9d0-11eb-9e0c-7a3081fcc7c2.png)

**Comment by jamesyoung79** [comment]
Also, the election information erroneously states it was passed via executive action by twistedfate1886.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
However, this is the result due to ties in voting.
Merging with #21003
