### ISSUE TITLE
9.4 Dev 272 - Tooltip - size is difficult to read due to dark grey X on black

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21701]
Difficult to read due to dark grey text on a very dark grey/black background

![image](https://user-images.githubusercontent.com/61889138/116737186-d0788c00-a9e8-11eb-9510-17968753e5e3.png)

**Comment by Daniel-Magulado** [comment]
Hello, thank you for making a report about this. However, we are currently aware of this issue.
I'll be merging this report to #21502.
