### ISSUE TITLE
USER ISSUE: Crash when Grant Title is selected for Work Party payment

### ISSUE THREAD

**Issue by andrey-zakharov** [StrangeLoopGames/EcoIssues#21718]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
1. i've creating contract working group
2. choosing "grant title", got crash

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
Source:Eco.Gameplay

System.Exception: Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
   at Eco.Gameplay.Utils.ClientSetViewExtensions.SetClassOfProperty(Object controller, Player player, String newClassName, String propertyName, Int32 listIndex)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I can confirm that this is happening.
I'll be forwarding this to our development team.

## Issue
Build: 0.9.3.3 beta release-219
Exception and game crash if **Grant Title** is selected as part of the payment for Work Party.

#### Reproduction Steps
1. Interact with the Contract Board.
2. Create a Work Party.
3. Configure payment. Either add or change one of them to **Grant Title**
4. Observe

#### Video Recoding
https://images.zenhubusercontent.com/47210472/608cf436-cf99-495e-9bde-ad7778d1af98/eco_2021_05_02_04_52_trim.mp4

[Game Logs](https://app.zenhub.com/files/47210472/1b7c15df-bebf-4738-97b7-7ea8e4e6202f/download)

**Comment by Daniel-Magulado** [comment]
Additional Info:

The crash also occurs when selecting **Knowledge Share Payment**, **Currency Payment**, and **Reputation Payment.**

[Crash Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6412964/Crash.Log.txt)


>Server encountered an exception:

><size=60.00%>Exception: Exception
>Message:Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
Source:Eco.Gameplay

>System.Exception: Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
   at Eco.Gameplay.Utils.ClientSetViewExtensions.SetClassOfProperty(Object controller, Player player, String newClassName, String propertyName, Int32 listIndex)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>


https://user-images.githubusercontent.com/77248866/116843368-4f9cd880-ac12-11eb-962e-6a261e083704.mp4

>
