### ISSUE TITLE
[0.9.4 Develop-274]Missing Skill Book Recipe Name and broken mechanics for research table UI

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21710]
Build: 0.9.4 Develop-274

## Issue
Missing recipe name for each skill book recipe on the research table.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/691bf8ab-319b-4d4b-8c51-0d420758c8fd)
Furthermore, the crafting time for all recipes inside the research table is the same.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/31823d2a-56ef-47d1-a474-02edb3f6a711)
Labor also ended up being the same and doesn't use certain professional labor anymore.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/2514101e-8030-4d9c-ac92-35f4dc978a29)
Note: This happened after the fix for #21537

**Comment by thetestgame** [comment]
I was able to patch this and make a PR for it last night. Its up for review currently.
