### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by azualspoon** [StrangeLoopGames/EcoIssues#21715]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
Source:Eco.Gameplay

System.Exception: Could not find setter SetObjectToEdit on type ViewEditor for ObjectToEdit property.
   at Eco.Gameplay.Utils.ClientSetViewExtensions.SetClassOfProperty(Object controller, Player player, String newClassName, String propertyName, Int32 listIndex)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
May we ask what prior steps have you done or did before this happened? 
Also, we would like to request that you provide your game logs.
A recorded video of the issue as it happens will also be helpful if possible.

To provide game logs, kindly follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Merging to #21718
