### ISSUE TITLE
[0.9.3.3] Law web UI needs some word wrapping

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21717]
Someone recently proposed a law that is a lengthy text - http://gs1.play.eco:3031/elections.html?election=106 . Turns out the law WebUI likes to display it as one continuous line, rather than wrapping the text:

![image](https://user-images.githubusercontent.com/964559/116793556-4843c680-aa7c-11eb-9890-b7ca29526c8c.png)

Feels like it should do some word wrapping.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
However, we are currently aware of this issue.
Merging with #20970
