### ISSUE TITLE
[0.9.3.1] Election complete, motion failed, senator elected

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21714]
The notification for elections is really confusing at times:

![image](https://user-images.githubusercontent.com/964559/116779209-c88d0c00-aa29-11eb-919e-de969cd3c38e.png)

"Election complete. ThePiachu elected. Motion Failed. Action will not be executed"

which is really weird for a clear election:

![image](https://user-images.githubusercontent.com/964559/116779224-e195bd00-aa29-11eb-8b88-19b95dc704e5.png)

The message should be clearer and not give conflicting impressions.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
I can confirm that this is happening.
I'll be forwarding this to our development team.


## Issue
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/5e5ae337-2e17-416c-8bb6-49464b4cf1e7)

Recommend to remove the statement that indicates the removal of the Election Process for the selected title.
Simplify the notification by stating the outcome of the election.

**Comment by Dave247** [comment]
IU also noticed this happen on 9.2.4 and just assumed it was part of the bug where elections go into negative time remaining, though that might just be a coincidence.

**Comment by Daniel-Magulado** [comment]
Closing. Update is made on Clickup. https://app.clickup.com/t/10591183/ECO-11826
Fixed in the upcoming game updates.
