### ISSUE TITLE
USER ISSUE: Sewage filter issue

### ISSUE THREAD

**Issue by LibraHammer** [StrangeLoopGames/EcoIssues#21720]
[log_210501022319.log](https://github.com/StrangeLoopGames/EcoIssues/files/6410304/log_210501022319.log)
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
If more than 5 sewage filters are hooked up to any amount of sewage outflow, they will "break" and throw an "Output can't handle sewage output" status to anything producing said sewage. Before 0.9.3.3, the mass sewage plant I made would run with no issues whatsoever.

**Expected behavior:**
It should take in sewage on more than 5 waste filters and output water like normal.

**Actual behavior:**
Instead if you have more than 5 hooked up to the same sewage line it will give can't handle output status to all sewage producers.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed at all. Yes this happens with no mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
However, we are unable to reproduce this issue.
Can you provide a recorded video of this issue as it happens, please? Please also provide you waste filter setup. We tried to hook up 7 waste filters to one blast furnace and everything went well on our end.

**Comment by LibraHammer** [comment]
I have more than one blast furnace hooked up to the sewage system I have. I am using steel and iron pipes for separation. Steel is inflow and iron is outflow. I have 12 waste filters hooked up to, 3 blast furnaces, 1 froth flotation cell, and 1 oil refinery. The other items that are hooked up are not running. The issue seems to take several hours to trigger. After about 1 hour of having 5 hooked up to the system, they threw the status of cant handle sewage output. I back tracked to make sure everything is direct as well as tried making an entire new system and it will only work for a what seems to be random amount of time depending on the amount of waste filters hooked up. I assume pipes do not have any flow limits, thus I am running all sewage through 1 steel pipe route and all water output through 1 iron pipe route. I am also hosting a server with the eco server files downloaded through steamcmd so I am not sure if that plays any part in the issue.

**Comment by LibraHammer** [comment]
I will try to make a short video of the issue and upload it.

**Comment by LibraHammer** [comment]
https://youtu.be/NfOIboImzic

Here is a link to the short video I made. It shows twice that I had the issue. I start out running on 1 sewage filter, then add on 5 more to make 6 running filters. I then add on an identical row of 6 more filters totaling 12 filters running. I have all water output running out a single pipeline as I show. Also I have all sewage running through a single pipeline as shown. This issue has come with the latest update as I never had it prior. The entire system has not changed in any way before or after the update.

**Comment by LibraHammer** [comment]
The latest update with the bug fix for pipes seems to have resolved the issue. Thank you!
![image](https://user-images.githubusercontent.com/35210389/117568382-c3a50980-b074-11eb-9704-455e35ac7d4e.png)
