### ISSUE TITLE
USER ISSUE: Wood cart bug

### ISSUE THREAD

**Issue by elbert5770** [StrangeLoopGames/EcoIssues#21730]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
leave a wood car for a while and it should flip upside down. when you try to use it you flip over and your legs go into your body. this has seemed to happen more common on dirt ramps

**Expected behavior:**
Not flipped over in the first place

**Actual behavior:**
it flips it over when you leave it alone 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6412020/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6412024/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @elbert5770, thank you for making a report about this.
I can confirm that this is happening.
I'll be forwarding this to our development team so they can look further into this.

Build: 0.9.3.3 Release-219

## Issue
Wood Cart Flips Upside Down if left on road Ramp.

#### Video Recording

https://user-images.githubusercontent.com/77248866/116844350-7577ac80-ac15-11eb-87e3-47e9c4127f5e.mp4

#### Reproduction Steps
1. Leave a wood cart on any Ramp road such as dirt ramp or stone ramp.
2. If you use any chat command, make sure to interact with the Wood Cart first. Then move it to the Ramp manually.
3. Move around the world or walk away from the cart. Make sure it's a distance.
4. Go back and observe.

**Comment by Daniel-Magulado** [comment]
Merging this report with #15688
