### ISSUE TITLE
Server 'Edit and Continue' broken

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21736]
Says it cant apply changes to Eco.Mods even when there are none. 

To repro, make an innocuous change in another project like gameplay and try to apply Edit and Continue, it will complain about mods.

**Comment by mirasrael** [comment]
Hmm. Works fine in Rider.

**Comment by redwyre** [comment]
what "new mods build processes" are you referring to @johnkslg ?

**Comment by mirasrael** [comment]
Tested with recently released 16.11 Preview 1 and hot reload works. It still doesn't work in 16.10. Seems like VS  issue which fixed in latest version. If you need hot reload feature then you can just use Preview version which seems stable enough.

**Comment by johnkslg** [comment]
great! we can close this then.

**Comment by johnkslg** [comment]
Switched to preview build and its still failing.
To replicate, change something in the Eco.Gameplay project while running is paused.  Change a number somewhere. It then says: 
![image](https://user-images.githubusercontent.com/3536496/121981225-2065a500-cd42-11eb-9a9c-8eb5b524e255.png)

And gives no other details. Might be specific to Eco.Gameplay project.

**Comment by mirasrael** [comment]
Checked on latest version and now it doesn't work :\ Not sure what we can do with this. Probably report to VS team somehow?
