### ISSUE TITLE
Crash with Radeon Software

### ISSUE THREAD

**Issue by kevinsmouts** [StrangeLoopGames/EcoIssues#21732]
I can play for between 10 to 30 min until this crash appears. Game freezes, and blue stripes appear from the right. Attached are the player logs.
[Player - crash logs.log](https://github.com/StrangeLoopGames/EcoIssues/files/6412207/Player.-.crash.logs.log)

**Comment by Daniel-Magulado** [comment]
Hi @kevinsmouts,

Thank you for making a report about this.
May we ask if you have the latest Radeon Software from AMD?
It appears that the graphics driver you currently is crashing.
We recommend to perform a clean install of your graphics driver.
Let us know if this helps.

**Comment by kevinsmouts** [comment]
The PC is freshly reinstalled with the latest graphic drivers installed as a clean install. As a matter of fact, the PC only has Chrome, Steam and ECO on it. 

I will try a fresh driver install again just for the sake of testing.

**Comment by kevinsmouts** [comment]
I cleanly reinstalled the drivers. Here's another crash ~5min in the game.
[Player - Crash log2.log](https://github.com/StrangeLoopGames/EcoIssues/files/6417147/Player.-.Crash.log2.log)

**Comment by kevinsmouts** [comment]
FYI I just did two stress tests with 3D Mark, one on DX11 and the other on DX12, no crash whatsoever.

**Comment by Daniel-Magulado** [comment]
Hi @kevinsmouts,

Can you provide your complete PC specification, please? As well as your operating system and its version.
On the latest game log you've provided, your system is still experiencing driver crash with lesser lines this time before it completely crash the game.

**Comment by kevinsmouts** [comment]
Please find report attached
[DESKTOP-3C8E9MF.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6417416/DESKTOP-3C8E9MF.txt)

**Comment by Daniel-Magulado** [comment]
Hi @kevinsmouts 

As it appears, your system is slightly lower than our minimum system specification requirement.
We recommend to play the game at a lower resolution. 
We also recommend to lower in-game graphics such as level of details, shadow, and disabling intensive graphics features such as Global Illumination, Volumetric Fog, Sunshafts, and Ambient Occlusion.

**Comment by kevinsmouts** [comment]
Thank you for the suggestion. I had already done this to ensure Performances of around 30-40fps. I tried other games today that push the graphic card to its limits and in 2 hours of gameplay I didn’t encounter any crash. 

There is something in ECO that triggers this; it’s seems very similar to issue #20406

**Comment by Daniel-Magulado** [comment]
Hi @kevinsmouts,

If that's the case, I'll be merging this to #20406 since it's AMD specific.
Thank you and we apologize for any inconvenience that our game might have caused.
