### ISSUE TITLE
"Input string was not in a correct format" Error when creating custom demographics from a census bureau.

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#21739]
I've tested and confirmed a bug with creating custom demographics. For our server, It's been happening when you create a custom stat, set it, then use a condition in a demographic requiring that custom stat to be greater than, less than, etc. When the demographic updates on its normal tick, or by /civics updatedems, the server will crash.

We've done some further testing on this bug and narrowed it down to the names of the custom stats. Adding "int" into a custom stat name will crash the server, understandably. Oddly enough, also adding "vote" to the name of a custom stat caused the same crash with the same error in the logs. The server will not restart without loading a backed up civics file. In one instance, the file was from 12:00pm on april 30th, when the law had gone into effect and crashed the server at 12:00pm on may 2nd. These tests were performed on a new world, with only one player, and only the necessary civics world objects spawned into the world. Nothing else was done in that world.

Further trials on the public server have still produced the same crash/error despite using the names that the game accepted on the test server.

Log is attached
[log_210502110707.log](https://github.com/StrangeLoopGames/EcoIssues/files/6412738/log_210502110707.log)

**Comment by IcedForge** [comment]
Thank you for reporting.

Could you grab a screenshot of the demographic example to further explain what you are using, names and so on.

**Comment by ChickenHacker1** [comment]
These are numbered in order. All intended to be used together. 1-3 would be the law on the court establishing the custom stat used to determine their eligibility for the demographic. 4 is the demographic itself. 5 is a voting process using that demographic. The voting process does not seem to be affecting the crash.
Further testing shows that any combination of custom stats used with a demographic will cause a crash on the public server.
We've tested this by copying the world from the public server and loading it on a private LAN server and consistently reproduced the crash by creating any combination/format using custom stats in conjunction with demographics.

On a brand new world, the crash was only consistently reproduced based on certain "trigger" words in the name of the custom stat. Those words were "int" or "vote" being added anywhere in the name. For example "RegInt" would produce a crash, while "Reg" would not. "VoterInt" would produce a crash, "Voter" would produce a crash, VInt would produce a crash, while "V" would not.

![1](https://user-images.githubusercontent.com/80280848/116937751-b54f8b80-ac37-11eb-9efc-f396c2183d34.png)
![2](https://user-images.githubusercontent.com/80280848/116937757-b680b880-ac37-11eb-86d3-1bb5b9c2e397.png)
![3](https://user-images.githubusercontent.com/80280848/116937762-b7b1e580-ac37-11eb-8c74-476bfa49c962.png)
![4](https://user-images.githubusercontent.com/80280848/116937765-b84a7c00-ac37-11eb-94c8-e6f3fcf4fbdd.png)
![5](https://user-images.githubusercontent.com/80280848/116937768-ba143f80-ac37-11eb-89ea-988354a416d1.png)

**Comment by TwixterZ** [comment]
I have tested this issue on 9.3.5 Release 231 and I can confirm this is happening.

Using the String "VoteRegInt" in demographic will cause server to crash. 

I would confirm using such string on Laws does not cause any issue. 

Repro:
- Civics Spawngov
- Use Census Bureau to Enact a demographic
- Tested String :
 VoteRegInt = Crash
 Reg = Crash
 Vote = Crash
 Int = Crash
 V = Crash

**Comment by IcedForge** [comment]
Just to clarify, this is crashing when it is trying to call a custom statistic which has a coding variable entry in its name.

**Comment by TwixterZ** [comment]
Adding clarification, issue will not happen if custom stat recorded (at least 1) prior to demographic added.

![image](https://user-images.githubusercontent.com/78054747/120918518-63db6600-c6e7-11eb-83dd-577b5b314c23.png)

![image](https://user-images.githubusercontent.com/78054747/120918489-3ee6f300-c6e7-11eb-82d2-5246b533fde2.png)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.3.6 Release 234

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f2d56360-39fa-4d24-ba13-675bfd937185)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/2714a635-6f2b-4fe4-89a2-369ab2398526)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b18a31a2-83cc-4501-a061-8ea9b6e5de00)
