### ISSUE TITLE
Materials on store/other objects appearing black

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2173]
![image](https://user-images.githubusercontent.com/3536496/30570632-405f516a-9c97-11e7-9652-df3d0ee3c2dd.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2134, which was also closed, although I'm not sure if it should have been closed ( @metachronism )

**Comment by metachronism** [comment]
yes, metallic objects reflect the environment.  if you have reflections off, you will not see these metallic objects
