### ISSUE TITLE
Multiple civic options presented to player despite not being valid.

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21743]
Currently observed on 0.9.3.3 beta release-291, though also seen on 0.9.2.4 beta release-156
**Steps to Reproduce:**

- Create an amendment for any action that does not apply to the active player (eg. a title, demographic, etc).
![Eco_2021-05-03_17-19-55](https://user-images.githubusercontent.com/10183015/116850650-589ea180-ac34-11eb-980f-3ca724eee912.jpg)
- Perform the action yourself, and notice the game asking you for multiple ways to perform the action, despite one of them not applying to you.
![Eco_2021-05-03_17-21-23](https://user-images.githubusercontent.com/10183015/116850660-5ccabf00-ac34-11eb-8019-831d7f3a4dda.jpg)

While nothing happens if you select to use the other civic article, the game should not be presenting you with it in the first place if it is not even valid as it can create unnecessary confusion for the player.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2021.

Closing as fixed.
Invalid civics are not shown anymore upon performing an action that meets the set of requirements to trigger it.
