### ISSUE TITLE
[0.9.4 develop-277] Doesn't allow editing districts/ properties on the whole map 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21744]
Step to reproduce:
- start to edit any District or Property.
- set map in one position.
- you can draw district only inside this square:
![image](https://user-images.githubusercontent.com/45708377/116852683-6edd3b00-abfd-11eb-9c9d-ca8fead35a22.png)

**Comment by gzatravkin** [comment]
Check minimap raycaster. Maybe some changes at settings are needed (like set lods in base of world size, so first lod will be always like 60% of world)

**Comment by Mattprass** [comment]
passing this to @ptitducanh since it's more up their speed 👍

**Comment by TwixterZ** [comment]
Tested this fix in 9.4 Staging 2012 

Land Claim edit :
![image](https://user-images.githubusercontent.com/78054747/121155862-c3b64600-c87a-11eb-935f-0915e16ac106.png)
Area in yellow box above are not accessible (land claim edit square refuse to reach) especially when using size 1 (area are still claimable if using bigger sized, eg size 10 would claim such area despite the center of the square will not reach these areas)

![land claim](https://user-images.githubusercontent.com/78054747/121155835-bc8f3800-c87a-11eb-9b10-8a975476ab79.gif)
Observe how land claiming behaves erratically.

Will continue testing this with zoning office.

**Comment by TwixterZ** [comment]
Zoning Office :
![image](https://user-images.githubusercontent.com/78054747/121157025-ca918880-c87b-11eb-9156-b9707ada6f81.png)
Similar behavior observed when using zoning office.

![zoning](https://user-images.githubusercontent.com/78054747/121157314-03c9f880-c87c-11eb-92f2-83b5563dff13.gif)
Even when using size 10 box, player only able to claim area when the center of the square does not exceed the line as shown in above picture

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2026.

Closing as fixed.
