### ISSUE TITLE
[0.9.3.3 beta release-219] Game crashes on Disconnect

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21747]
I've noticed that the game will consistently crash for me when disconnecting from any server. online or offline While have I previously noticed this happen on 0.9.2.4 as well, it was a lot less consistent and would only trigger if I have had the game open and running for a long period of time.

Attached is my player.log file from after a crash happened when I attempted to disconnect from a local world.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6413639/Player.log)

In case it's any different, here is the log file after when attempting to disconnect from a online server that I am currently playing on.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6413666/Player.log)

**Comment by SlayksWood** [comment]
@Dave247 Thank you for the report. merged to #21517
