### ISSUE TITLE
[0.9.3.3 beta release-219] Hard crash when attempting to quit and connected to a server.

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21749]
I'm unsure if this is related to the current issue of crashing on disconnect (#21747) or another previously reported bug (#21302) so I'll tag both, upload my crash dump and leave it for you guys to have fun deciding what to do with it. 😛 
[Crash_2021-05-03_091631039.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6413963/Crash_2021-05-03_091631039.zip)

**Comment by IcedForge** [comment]
@namquang93 tagging you since it contains dumps and assorted stuff and your working on the weird unity crashes feel free to unassign if incorrect

**Comment by TwixterZ** [comment]
@Dave247 apologies this took a while, we have fixed this issue for future patches
