### ISSUE TITLE
[0.9.3.3 beta release-219] Laws issue with multiple triggers of same type in section.

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21748]
Create a simple law that has the same trigger listed twice in the same section, but with different specifications (Eg, the tool or block), but the action will only work for the first trigger and not the second.
![Eco_2021-05-03_18-01-56](https://user-images.githubusercontent.com/10183015/116857678-8db0f100-ac40-11eb-92e5-78636de2ce37.jpg)

---
The reason for wanting to do this is a bit of a story. The purpose is to have a law that pays a citizen when they dig or mine a block in a district, but takes into account the tool used (ie getting paid 0.2 for hitting Granite with a stone pick, and 0.1 for Iron steel and modern). In order to try and be efficient but also not having actions double up the result was a law int he screenshot below, however we noticed that only ever the first event line was triggering in each section and none of the others.
![Eco_2021-05-03_18-55-57](https://user-images.githubusercontent.com/10183015/116858667-17ad8980-ac42-11eb-80c4-64a7537789cb.jpg)

As a workaround we instead had to split the actions up into their own sections in order for it to work, and while I feel like there would be another way to do this whole process that I can't think of, I still think that this is a bug in the game as I can't see any logical reason why it shouldn't work the way we originally made it.

**Comment by IcedForge** [comment]
Thank you for reporting. This is unfortunately a technical limitation and will not be changed at this time because of how the properties of a certain trigger is conditioned so you cannot call the unique conditions of 1 trigger over the other hence why you need to use different sections.

**Comment by Dave247** [comment]
> Thank you for reporting. This is unfortunately a technical limitation and will not be changed at this time because of how the properties of a certain trigger is conditioned so you cannot call the unique conditions of 1 trigger over the other hence why you need to use different sections.

Fair enough, thanks for clarfying.
