### ISSUE TITLE
[0.9.4 develop-277] Strange Blur Effect with Highlighted Items

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21745]
Step to reproduce:
- /time set 12
- find any cotton in world and claim some property:
![image](https://user-images.githubusercontent.com/45708377/116853786-4ce4b800-abff-11eb-957f-9bd8d67ed119.png)
- open any window that cause Blur effect. for example property window:

https://user-images.githubusercontent.com/45708377/116854198-fe83e900-abff-11eb-986a-635fe0d63891.mp4

**Comment by SlayksWood** [comment]
Workbench:
![image](https://user-images.githubusercontent.com/45708377/117262802-51f17380-ae5a-11eb-9f9e-51c0581a0f93.png)
![image](https://user-images.githubusercontent.com/45708377/117262836-57e75480-ae5a-11eb-8522-25ec24a909f7.png)

**Comment by SlayksWood** [comment]
> Build: 0.9.4 Develop-287
> 
> ## Issue
> If you open a different UI while holding a land claim item such as **Land Claim Papers** and **Land Claim Stake** prompts a flashing of pattern on the player's screen. Placing this as high since this can potentially cause seizures for those who are suffering from photosensitive epilepsy. Especially that there's no visible warning around the game about flashing of lights.
> 
> #### Reproduction Steps
> 1. Hold and land claim item.
> 2. Press ESC or open a different UI such as pressing L.
> 3. Observe.
> 
> #### Actual Result
>  Eco_2021.05.17-13.56.mp4

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2040.

![image](https://user-images.githubusercontent.com/77248866/123975293-caeef080-d9ef-11eb-9b91-a02b4fef10d1.png)
 Closing as fixed.
