### ISSUE TITLE
[0.9.3.3 beta release-219]Jellyfish recipe missing in fishery

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21750]
Jelly fish recipe missing on fishery since it no longer processes fish tag it needs its own recipe listing.
It has a campfire recipe but no meat recipe

![Screenshot_65](https://user-images.githubusercontent.com/24981362/116873152-77426f80-ac17-11eb-8cbf-1154adf24117.jpg)
![Screenshot_66](https://user-images.githubusercontent.com/24981362/116873153-78739c80-ac17-11eb-8d1b-47e3cdd02707.jpg)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2028.

Closing as fixed.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/b250c15c-acf0-4347-96b3-e2cad8100c98)
