### ISSUE TITLE
Create cw buying tiers on website

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21759]

**Comment by j3fffff** [comment]
waiting for playtest results, but initial estimate:
1gb 5players
2gb 10players
4gb 25players
6gb 30players+

**Comment by j3fffff** [comment]
we dont know tiers yet, but setup buying system for 4 tiers.
and let me know when to plugin ui

**Comment by denysaw** [comment]
Done. Let's merge it only when needed. https://github.com/StrangeLoopGames/Eco-Accounts/pull/225
