### ISSUE TITLE
[0.9.3.1] Reclaiming properties via a law / excecutive action merges them into a single property by player

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21758]
On White Tiger we have the usual "reclaim abandoned properties" law:

![image](https://user-images.githubusercontent.com/964559/116931836-5af20300-ac16-11eb-83ac-7d8af23678bd.png)

Since residency has been a major push lately, I would imagine any property reclaimed like this would remain separated, but as far as I've seen, multiple properties owned by a single player tend to get merged into one. I've noticed that when I edit some of those properties to cut down their size I get notifications along the lines of "are you sure you want to split the property into 2?", even though I'm not splitting them myself.

I would expect the properties that were separate to remain separate even after the reclamation.

**Comment by IcedForge** [comment]
Thank you for reporting, will close as duplicate of #17733
