### ISSUE TITLE
[9.4 Develop 277] Ground Layer 7 and more does not load 

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21751]
Freshly generated world only have 1st 6 block layer of ground, 7th layer onwards does not load

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/de277583-7b4c-4f3b-9dd9-dc5dbcf2d1ab)

same applicable from seafloor

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/aa44e7f0-8e89-437a-bdeb-475f666b6897)

**Comment by Quadbro** [comment]
Started to look at issue and found that all chunks downside in range of 5 blocks from top are not rendered (probably an optimized renderer)
![image](https://user-images.githubusercontent.com/6802030/117919462-3b925e80-b317-11eb-8eff-e21066805ed0.png)
CanBuild is false for them, and it resets to true on reconect, so probably smth broke in just update of this value on block  place/destroy for neighbors
Do not know much about chunk system in our project, so hope this info would help

**Comment by mirasrael** [comment]
Happened because when chunk was unencased then it didn't update chunk encasement on client.
