### ISSUE TITLE
USER ISSUE: Networking Issues

### ISSUE THREAD

**Issue by Measion** [StrangeLoopGames/EcoIssues#21754]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.3 beta release-219

**Steps to Reproduce:**
You cant really reproduce it or atleast I havent the faintest clue how.

**Expected behavior:**
No delays and opening or getting into cars should be instant

**Actual behavior:**
large delays being that of my mate is over by a stockpile on his screen but on mines hes still digging over at a hill and opening a menu or getting into a truck takes legit 2 or 3 minutes to register and let me see the menu or drive.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed and am playing the base game havent even touched a thing except load it up on install also I have good internet with every other game being just fine and my ping is fine to at around 19ms.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of this issue.
I'll be merging it with #21437
