### ISSUE TITLE
[0.9.4 develop-277] Failed to handle RPC method: InventoryChanged

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21768]
Step to reproduce:
- player 1 connect to server and place some furniture
- player 2 connect to server
- player 1 pick up or place more furniture
- player 2 will be kicked with PRC:
![image](https://user-images.githubusercontent.com/45708377/117003714-decaee80-aced-11eb-9880-0d368ec04663.png)
Also just enough to use /give command

**Comment by Mattprass** [comment]
tested at current staging version, seems to be fixed

**Comment by SlayksWood** [comment]
Still in issue:
![image](https://user-images.githubusercontent.com/45708377/120804421-4d010c00-c54d-11eb-9344-e4afa5c41918.png)
try to use staging client.
