### ISSUE TITLE
[0.9.4 develop-277] Camera rotates on 180 degrees when start moving with bottom/top camera position in 3rd person view.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21767]
Step to reproduce:
- set camera to bottom/top position:
![image](https://user-images.githubusercontent.com/45708377/116994700-b937e800-ace1-11eb-8c6a-2e757dd31172.png)
![image](https://user-images.githubusercontent.com/45708377/116994709-bc32d880-ace1-11eb-835f-02476219ff05.png)
- start/ stop to move.
Video:
https://drive.google.com/file/d/1dr93UxSdkpGBrgJ_22vTAsnPXyuEK0jE/view?usp=sharing

Also check how rotates avatar in minimap.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2020.

Closing as fixed.
