### ISSUE TITLE
Law - Inventory Action trigger + Ignore Auth not functioning

### ISSUE THREAD

**Issue by tarnar** [StrangeLoopGames/EcoIssues#21769]
On 9.3.3

Attempting to create a series of laws for vehicle sharing on a small trusted server.  The third section of the law is:

Trigger = Inventory Action
With Item Moved = Any
With Storage Container = All Vehicles Items

Then = Ignore Authorization

It doesn't work, says "you are not authorized to do that" when trying to add or remove blocks from another player's vehicle.

Tried the law with If conditions = If Put or If Take)
Tried the law with If conditions = If Not Owner of Property.

Unfortunately none of these work.

Reported in #law-help on Discord, confirmed by another user, who says it doesn't work with a plain Stockpile either.

![vehicle-law2](https://user-images.githubusercontent.com/37849620/117020563-ca6a0000-acb3-11eb-98a8-bc88bac14eea.jpg)

**Comment by IcedForge** [comment]
Thank you for reporting, seems like inventory action is eluding the civics system again.

**Comment by tuha263** [comment]
This was fixed by https://github.com/StrangeLoopGames/Eco/pull/8291

**Comment by SlayksWood** [comment]
fixed in 9.4 develop, but it has release 9.3.x.
@WeaselDog reopen or leave the fix for 9.4?

**Comment by IcedForge** [comment]
Will close as to avoid new bugs potentially in release branch and leave fix on 9.4
