### ISSUE TITLE
[0.9.4 develop-277] Minimap is always shown 3D after relog.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21766]
Step to reproduce:
- connect to server, open minimap, Settings, set Camera mode to 2D:
![image](https://user-images.githubusercontent.com/45708377/116983021-407d5f80-acd2-11eb-959f-13afae314646.png)

- restart client and connect to server. Minimap is 3D, but you can see that it's still set 2D mode.
![image](https://user-images.githubusercontent.com/45708377/116982970-2ba0cc00-acd2-11eb-8283-0f40071457ae.png)

**Comment by SlayksWood** [comment]
or it was not completely fixed #20275 or it was broken again.

**Comment by SlayksWood** [comment]
And until player reselect some of this camera modes icons on minimap are glitch
![2021 05 04 Minimap icon glitch2](https://user-images.githubusercontent.com/45708377/116995937-619a7c00-ace3-11eb-8f56-bcf9208ada0a.gif)

**Comment by madpingui** [comment]
Tested after staging develop merge, tested on staging branch in editor, and it looks fine.

**Comment by madpingui** [comment]
Staging branch
https://drive.google.com/file/d/18wYKywl9gd84p2lm87MMxl9bZgBwE9So/view?usp=sharing

**Comment by TwixterZ** [comment]
@madpingui 

tested on 9.4 Staging 1987 I can confirm this is still happening 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b8626c24-17da-46ec-abfe-b9f06a7c5e6f)

**Comment by SlayksWood** [comment]
Checked on 0.9.4 staging-1992 seems fixed.
