### ISSUE TITLE
[0.9.4 develop-277] Wrong notification when eating with FoodTastinessMulriplier disable

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21764]
![image](https://user-images.githubusercontent.com/45708377/116972610-f2615f80-acc3-11eb-872c-29c4e33ed3fa.png)
![image](https://user-images.githubusercontent.com/45708377/116972691-0f962e00-acc4-11eb-9fe7-fcdd02e41f18.png)

**Comment by WeaselDog** [comment]
When this setting is set to false, there should be no display for tastiness.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 1991
