### ISSUE TITLE
[0.9.3.3 Release-219 | 9.4 Develop 279] Some Plants appear too big on Pot

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21778]
Build:
- 0.9.3.3 Release-219
- 0.9.4 Develop-279

## Issue
Certain plants like Papaya and Fern appear too big on Pot.
Fern
![fern](https://user-images.githubusercontent.com/77248866/117102993-0da79a00-adac-11eb-90cb-71707788e184.jpg)
Papaya
![papaya](https://user-images.githubusercontent.com/77248866/117103032-244df100-adac-11eb-984e-5bc5682efa69.jpg)

#### Reproduction Steps
1. Get a Round or Square Pot.
2. Store Papaya seed or Fern spore.
3. Observe.

#### Expected Result
Most plants actually appear quite on a large size scale when displayed on a pot. However, trees end up being minuscule.
![image](https://user-images.githubusercontent.com/77248866/117103182-6f680400-adac-11eb-871f-fe499f4c3020.png)
Hope we could have the option to set the sizes of plants/trees shown on the pot. Large sizes of plants appear quite fine with taller buildings but not so much with 4 blocks height.

**Comment by SlayksWood** [comment]
merged to #17129
