### ISSUE TITLE
[0.9.3.3 Release-219] Tooltip Buy it at | Sell it at section displays old and duplicate listing

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21773]
Build: 0.9.3.3 Release-219

## Issue
When you hover your mouse icon over an item, a tooltip will pop up with a section showing where you can purchase or sell that specific item. It's under **Buy it at** and **Sell it at** section. However, both section somehow displays old listing and sometimes, duplicate listing. Hovering your mouse icon over it sometimes shows an error **Not Found This object does not exist.**

#### Reproduction Steps
1. Join a world with stores already set. Example, SLG Playtest server.
2. Hover your mouse icon over an item. Eg. Huckleberry.
3. Observe the Tooltip Buy it at and Sell it at section.

#### Actual Result
Old and duplicate listing.
![image](https://user-images.githubusercontent.com/77248866/117067055-1e302400-ad5c-11eb-9291-d0f87062c370.png)
![image](https://user-images.githubusercontent.com/77248866/117067328-75ce8f80-ad5c-11eb-9fce-3833ecae9c80.png)

#### Expected Result
No old and duplicate listing.
![image](https://user-images.githubusercontent.com/77248866/117067178-4586f100-ad5c-11eb-8e96-c12f71ba8bb4.png)

**Comment by SlayksWood** [comment]
regression #20313

**Comment by tuha263** [comment]
I can't reproduce it in staging after trying some case:
- Pickup and Place store object multiple times 
- Build and Sell item

**Comment by Daniel-Magulado** [comment]
Tested 0.9.4 Staging-2035.

Moving to investigate pipeline for now as I am unable to reproduce this issue on staging build.
