### ISSUE TITLE
[9.4 Develop 277] Crafting Table Fee

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21777]
Applying fee at crafting table affects table owner (illogical behavior)

tested on both **fee per item** and **fee per minute**

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c813d002-2af7-48ff-b215-f46e5bb434eb)

**Comment by TwixterZ** [comment]
Fix tested on 9.4 Staging 2012 

For some table this issue is fixed, but there are still tables that have this issue

Issue remain :
- Workbench
- Arrastra
- Kiln
- Mill
- Bakery Oven
- Bloomery
- Cast Iron Stove
- Sawmill
- Screening Machine
- Screw Press
- Stamp Mill
- Lathe
- Shaper
- Blast Furnace
- Cement Kiln
- Electric Machinist Table
- Advanced Carpentry Table
- Advanced Masonry Table
- Automatic Loom
- Electric Stamping Press
- Spin Melter
- Stove
- Oil Refinery
- Pump Jack
- Rolling Mill
- Froth Floatation Cell
- Robotic Assembly Line
- Sensor Based Belt Sorter
- Jaw Crusher
- Laboratory
- Electric Lathe
- Electric Planer

**Comment by madpingui** [comment]
I tested most of the tables you pointed out there and for me it works just fine.
Make sure you are the **Owner** of the table.

I tested them by spawning them, and automatically it claims an area and I appear as the owner, and it works correctly for me.

**Comment by TwixterZ** [comment]
Re-tested on 9.4 Staging 2016

I can confirm below tables are still having issue 

Repro :
1. use /bt 4,30,10,30 (to build large enough room for all table)
2. Claim the whole room.
3. Proceed to use /give each table and put them down
4. go to each table, add fees and observe

Workbench
- Campfire
- Arrastra
- Kiln
- Mill
- Bakery Oven
- Bloomery
- Cast Iron Stove
- Sawmill
- Screening Machine
- Screw Press
- Stamp Mill
- Lathe
- Shaper
- Blast Furnace
- Cement Kiln
- Electric Machinist Table
- Advanced Carpentry Table
- Advanced Masonry Table
- Automatic Loom
- Electric Stamping Press
- Spin Melter
- Stove
- Oil Refinery
- Pump Jack
- Rolling Mill
- Froth Floatation Cell
- Robotic Assembly Line
- Sensor Based Belt Sorter
- Jaw Crusher
- Laboratory
- Electric Lathe
- Electric Planer

**Comment by TwixterZ** [comment]
Attached save file for reference :
[https://app.zenhub.com/files/47210472/a043d542-4041-41c2-bca3-94fea495ffaf/download](https://app.zenhub.com/files/47210472/a043d542-4041-41c2-bca3-94fea495ffaf/download)

**Comment by SlayksWood** [comment]
I have this bug when change the order:
- place workbench:
![image](https://user-images.githubusercontent.com/45708377/121675771-850fce00-cabc-11eb-9bd7-b8d2e77e762d.png)
- add tax fee:
![image](https://user-images.githubusercontent.com/45708377/121675807-8e993600-cabc-11eb-8627-7e8ead38506f.png)
- check crafting tab (not sure if there is no owner then tax fee displaying is correct):
![image](https://user-images.githubusercontent.com/45708377/121675926-b8eaf380-cabc-11eb-8f2d-38a7631c59e8.png)
- claim workbench:
![image](https://user-images.githubusercontent.com/45708377/121676031-d0c27780-cabc-11eb-847a-c8a1725394a5.png)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2020
