### ISSUE TITLE
[0.9.3.3 beta release-219] /civics spawngov command broken

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21771]
Previously on 0.9.2.4 I recall when using the spawngov command, eight buildings would appear, one for each of the civic objects. .But now. only five building would be created, with the the missing buildings being for the Ballot Box, Executive Office. and Amendments. Maybe this was a deliberate change, though an odd one if so.
![Eco_2021-05-05_03-03-47](https://user-images.githubusercontent.com/10183015/117042269-16b64e00-ad4f-11eb-9f33-d956ad119ae2.jpg)

Furthermore, some of the civic objects aren't placed correctly, the worst being the Court as it is placed inside one of the walls, making the building not a room, and picking it up will make the affected blocks disappear.
![Eco_2021-05-05_03-04-23](https://user-images.githubusercontent.com/10183015/117043094-1ff3ea80-ad50-11eb-98bb-49ea9dfefec1.jpg)
![Eco_2021-05-05_03-04-59](https://user-images.githubusercontent.com/10183015/117043102-22564480-ad50-11eb-9190-6a6248a823a1.jpg)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We are currently aware of this issue and a fix will soon be released in the coming updates.
Merging with #21358
