### ISSUE TITLE
And one more WT crash - Invalid Data, LiteDB

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21780]
[log_210505031510.log](https://github.com/StrangeLoopGames/EcoIssues/files/6426033/log_210505031510.log)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/20405

**Comment by WeaselDog** [comment]
We would need a save for this one. Please make a new report if you experience this again.
