### ISSUE TITLE
View Apply property is slow with big lists

### ISSUE THREAD

**Issue by gzatravkin** [StrangeLoopGames/EcoIssues#21795]
![image](https://user-images.githubusercontent.com/53317567/117350035-76f9dc80-ae82-11eb-9711-ae2d7220509b.png)
Deed with thousands of plots is updating very slowly

In game you can notice it by client freeze at deeds updates

**Comment by SlayksWood** [comment]
#20199

**Comment by StallEF** [comment]
there is also a delay in the adoption of the law on the introduction of a new district, most sensitively when the creating district has the right to add without a vote
