### ISSUE TITLE
[0.9.4 develop-279] Hide "api-rcon-admin" user

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21791]
![image](https://user-images.githubusercontent.com/45708377/117293697-66456880-ae7a-11eb-9f58-c02dfc08a554.png)

**Comment by WeaselDog** [comment]
It must be more than hidden. It must not count towards the total player count.

**Comment by mirasrael** [comment]
Have separate collection for system users which will only be checked on login as fallback if general Users collection doesn't have a match. It also will require migration for old saves.

**Comment by TwixterZ** [comment]
Tested fix and confirmed as of 9.4 Staging 2024

Rcon does not show up in player list and when use /manage playerlist 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f0ce7b0a-307d-4b07-a5bd-1454d13ab892)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/3fe9eb8e-1f1d-4af2-a0f6-7ce4aca82cee)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/06fec023-73b6-41fc-9e6b-a30c8fc999df)
