### ISSUE TITLE
[0.9.3.4 beta release-226] Invalid Work Order Stuck

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21792]
I was cancelling a number of Glass work order on multiple Kilns I have, and noticed that one of them was stuck at 0 seconds, and on further inspection states it is invalid as the object is destroyed.
I can't cancel it again and picking up the Kilns where the order was one doesn't seem to do anything either, so I'm a little worried I'm going to be stuck with the gaming thinking the order still exists until the very end.
The wasn't anything too special I did, other then just cancel 4 orders quickly one after the other that were close but not yet completed due to missing materials.

![Eco_2021-05-06_23-16-36](https://user-images.githubusercontent.com/10183015/117305232-e7741e00-aec1-11eb-8386-92330f45258e.jpg)
![Eco_2021-05-06_23-18-51](https://user-images.githubusercontent.com/10183015/117305240-e8a54b00-aec1-11eb-8f82-aa18211c1cfa.jpg)

**Comment by IcedForge** [comment]
Hey! Thanks for reporting.
For a solution that might work ( make sure to backup any save files when interacting with admin commands )
/objects remove work orders,8068 
should remove the work order per say ( you will likely not get your materials back though )

**Comment by IcedForge** [comment]
As alternatively it might also remove it on a server restart if it re verifies the work order and finds it invalid.

**Comment by Dave247** [comment]
Ah thanks for the information. We'll see about the server restart, as our admin has set it up to restart the server if there's a memory leak which does happen occasionally,

**Comment by Daniel-Magulado** [comment]
Hi @Dave247,

Are you still having issues with this?
This is just a follow-up so we can know the status of this report.

**Comment by Dave247** [comment]
@Daniel-Magulado So I logged in to check after not having played for a week and logging back in the server (which very likely would have reset at least once since then) it looks like it has fixed itself, and this is without having yet updated to 9.3.5 mind you.
So with it more or less being complete/resolved I'll close the issue myself as I don't believe there's anything more left to do here.
