### ISSUE TITLE
[0.9.3.4 Release-226] Brown blocks get double capacity with lumber stockpile except for Blue and Green items

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21796]
Build: 0.9.3.4 Release-226

## Issue
Blue items such as Lumber, Plant Fibers, Fabric, Wood Pulp, etc, as well as Green items that are usually food, are still limited to 100 stacks in Lumber Stockpile, including Large Lumber Stockpile, while other blocks (brown blocks) get doubled capacity such as Sand from 5 to 10, Hewn log from 15 to 30. 

![image](https://user-images.githubusercontent.com/77248866/117368464-2754f880-aef6-11eb-8047-4fc6fbb6c7c5.png)

#### Expected Result
Everything should be given double capacity with a Lumber stockpile. Including Blue and Green items. If not, maybe increase the storage capacity for both Blue and Green to 150%? This will be helpful in managing storage.

**Comment by ThePiachu** [comment]
Related to #18619 and should be fixed with https://github.com/StrangeLoopGames/Eco/pull/8203 (if that change is still in). I can pinpoint the exact lines that needed to be changed to fix this :D

**Comment by WeaselDog** [comment]
Closed as duplicate
