### ISSUE TITLE
[0.9.3.4 Release-226] Difficult to tell how the Avatar will seat on hewn bench and lumber bench

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21802]
Build: 0.9.3.4 Release-226

## Issue
Benches that don't have a backrest such as Hewn Bench and Lumber Bench make it difficult in placing them since there's no way to tell how the Avatar will seat on the mentioned benches. I always end up seating facing the wall and had to 180 degrees turn these benches just to get the seating direction right. Unlike other benches that have a backrest.

![image](https://user-images.githubusercontent.com/77248866/117381300-5a0aeb00-af0e-11eb-99ef-3c68c012281c.png)

#### Actual Result

https://user-images.githubusercontent.com/77248866/117381551-e9b09980-af0e-11eb-9f0a-0102598b2988.mp4

#### Expected Result
I should be sitting facing where I approach the bench and not always in one seating direction.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1997.

I am now able to seat on either side of the bench, however...

Reopening with an issue with the avatar orientation after standing up as well as the camera doing a 360-degree swoop around the avatar in 3rd person view

It somehow triggers my motion sickness and feeling a little bit nauseated on the first try due to the fast movement and blurring of the camera.

See the video below:

https://user-images.githubusercontent.com/77248866/120230074-1ee7a780-c281-11eb-9cb5-6673f4c910f3.mp4

Reproduction steps:
1. Seat on a lumber bench.
2. Switch to 3rd person view.
3. Stand up.
4. Observe.

Expected Result:
Regardless of the camera position, the avatar should be facing the direction of where it was facing while seated.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2020.

Closing as fixed.

**Comment by SlayksWood** [comment]
Found a small bug) that happens when you start to rotate Benches with Q/R. Step to reproduce:
- select motrared stone bench:
![image](https://user-images.githubusercontent.com/45708377/121886158-c226cb00-cd1d-11eb-983a-31b91b1c761e.png)
- place and sit without rotation:
![image](https://user-images.githubusercontent.com/45708377/121886191-ce128d00-cd1d-11eb-83e6-6de7321e5b0d.png)
- pick up bench and place with rotation on 180 degrees and sit again:
![image](https://user-images.githubusercontent.com/45708377/121886259-e4b8e400-cd1d-11eb-96ed-1dbb00c359ff.png)

IF you use Hewn bench and rotate it, so you will sit  the wrong side.

**Comment by Quadbro** [comment]
SVN fixed.

**Comment by TwixterZ** [comment]
Tested on 0.9.4 Staging-2030 

Below issue is still happening

> Found a small bug) that happens when you start to rotate Benches with Q/R. Step to reproduce:
select motrared stone bench:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/db93cbb3-c79e-4cd1-adad-aaaf8cb62805)
place and sit without rotation:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/196d07f0-007a-4b09-96fa-50a94b7f3eb5)
pick up bench and place with rotation on 180 degrees and sit again:
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c024a536-b87a-46e7-98a9-8fd6efe74f39)
IF you use Hewn bench and rotate it, so you will sit the wrong side.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/68d9bde7-c516-424a-bd89-0422cec26041)

**Comment by Quadbro** [comment]
Looks like Eco.scene got overrided by someone..( will redo my changes
