### ISSUE TITLE
[0.9.4.0 beta develop-280]Broken icons in 279/280 develop builds

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21806]
Something broke icons in 279/280 somewhere
![Screenshot_4](https://user-images.githubusercontent.com/24981362/117480802-5903a900-af62-11eb-8aa4-e19b37109eee.jpg)

**Comment by IcedForge** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/24981362/117481663-9583d480-af63-11eb-8c34-f3aa8b860471.jpg)

**Comment by Sekor2600** [comment]
fixed in Svn

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-281. 
Checked all crafting tables via /preset crafting.
All icon works now. Closing.
