### ISSUE TITLE
[0.9.4.0 beta develop-180] Missing icons for law triggers

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21809]
Missing some law trigger icons for experimental education as well as create tree debris
![Screenshot_23](https://user-images.githubusercontent.com/24981362/117496088-d33e2880-af76-11eb-9dae-6893383edfa5.jpg)

**Comment by Daniel-Magulado** [comment]
As well as Icon for Action Location

![image](https://user-images.githubusercontent.com/77248866/117783307-ffa6bd00-b274-11eb-8a05-aba72419910f.png)


With cleanup debris, both trigger and action location use the same icon.

![image](https://user-images.githubusercontent.com/77248866/117783466-25cc5d00-b275-11eb-94fc-47d903747b50.png)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/ee970b33-0630-4100-a00d-079152612e9f)

**Comment by RobertMangano** [comment]
icons are checked in
