### ISSUE TITLE
Declunkify: First chat not appearing after refactor; need cleanup on AnimatedVerticalList

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21800]
- [x] The first chat message wont appear due to AnimatedVerticalList hiding it. Couldnt figure out algorithm to see why. Simplify algorithm in there and make it work without special casing.  Things to fix:
  - It's not clear from comments what the purpose of AnimatedVerticalList is or how it works.
  - Animated Vertical List would work better with no public functions.  Then the user just puts it on a gameobject that is a list container and it subscribes to everything it needs automatically.
- [x] Close button on cards not clicking right.  Need to sort out click-order of elements on there.
- [x] Overflow text on NotificationCard needs re-setting up
- [x] Notification window should shrink to fit number of displayed notifications.

**Comment by johnkslg** [comment]
is a bug that needs fixing

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2009

Reopening with jerky animation issue.

### Jerky Notification Bar Animation
If the notification window has few messages at a certain point, it removes the scrollbar and uses that space to expand the messages. However, there's kind of a glitch/flicker animation when that happens. See a super slow-mo video below:


https://user-images.githubusercontent.com/77248866/120916774-fbd45200-c6dd-11eb-81ad-f3128262dcd4.mp4

The rest of the message banner goes up and then goes back down momentarily. At a normal speed, it appears as if it flickered for a moment.


https://user-images.githubusercontent.com/77248866/120916937-1e1a9f80-c6df-11eb-87f0-e4687013da57.mp4
