### ISSUE TITLE
[0.9.4 Develop-281]Jerky Map highlight marker (lag)

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21816]
Build: 0.9.4 Develop-281

## Issue
The highlight market when you try to edit a deed property or draft a district at the zoning office is lagging pretty badly.

#### Reproduction Steps
1. Open the UI of one of your properties.
2. Click Edit.
3. Move your mouse icon.
4. Observe.

#### Actual Result

https://user-images.githubusercontent.com/77248866/117534671-0fc85d80-b025-11eb-88e8-455896d5548e.mp4

This makes it difficult to edit your land property as most of the time, the highlight marker tends to get stuck at one point.

**Comment by SlayksWood** [comment]
dup #21744
