### ISSUE TITLE
[0.9.4 Develop-281] Missing icon art for Fabric Tag

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21817]
Build: 0.9.4 Develop-281

## Issue
Missing icon art for fabric tag.
![image](https://user-images.githubusercontent.com/77248866/117535528-cb3ec100-b028-11eb-8d3a-7f4b6245fdd8.png)

Note: Not sure if we have plans to change the icon art but there's an existing icon art for fabric tag.
Here's the icon for Fabric Tag on 9.3.4 Release-226
![Fabric2](https://user-images.githubusercontent.com/77248866/117535625-3dafa100-b029-11eb-8040-cf7bb8700c4b.jpg)

**Comment by Sekor2600** [comment]
fixed in Develop SVN

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-286.

Closing. Fabric tag now has icon.
