### ISSUE TITLE
CW playtest connection setup not showing ping

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21811]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/24eca309-1cd6-419d-96cb-277e7da369ad)
The behaviour of not showing ping and refusing some people to connect I have only seen on servers with wrong network configuration.

@Ry4ndrew can you test to see if this is the case with a fresh cloud world?

**Comment by Ry4ndrew** [comment]
@j3fffff unable to replicate with a fresh cloud world
