### ISSUE TITLE
[0.9.4.0 beta develop-280]Applying fertilizer has no tooltip 

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21813]
When holding a fertilizer there is no tooltip or button indication on how to apply it.
![Screenshot_54](https://user-images.githubusercontent.com/24981362/117515691-42c41000-af97-11eb-962e-9e849a4757d5.jpg)

**Comment by SlayksWood** [comment]
It looks a little wrong, so for me if you add name it should be with link:
![image](https://user-images.githubusercontent.com/45708377/119119575-fc10f400-ba33-11eb-865f-5645397b3517.png)
But then it looks a little cluttered. I'd like to have only one world Fertilize, to be short and understandable like other hints (Use, Reap, Hoe ground and etc.)
Only one hint I found with such proplem is Plant any seed:
![image](https://user-images.githubusercontent.com/45708377/119119960-65910280-ba34-11eb-8234-9813f0ea5508.png)
So I'd remove Seed in it too. Just "Plant"

**Comment by Quadbro** [comment]
Updated pr link (fixed in elevator fixes)
