### ISSUE TITLE
Declunkify: Give texture to our flat-shaded panels

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21828]
![image](https://user-images.githubusercontent.com/3536496/117586113-e9f59400-b0ca-11eb-8f81-129bd3873c58.png)
In these places and others, give a slight texture so its not just flat shaded.

**Comment by MilenkoTunjic** [comment]
I have added a new tiling sprite
Content\Art\UI\TilingSprites
called
UI_Texture_Graphic
This one replaces background texture but has to be set to tile
I made it white, so it is tintable
and do not worry if the look is not perfect, once it is plugged in, I can make it whatever looks good, as long as it is on my end to control
