### ISSUE TITLE
Gold and Copper Bar icons could use improvement (they should be more precious looking)

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#21826]
![3_147](https://user-images.githubusercontent.com/26339332/117576121-449fe780-b0ed-11eb-8ed1-27f32d5f85c5.png)
![3_148](https://user-images.githubusercontent.com/26339332/117576123-45387e00-b0ed-11eb-8e46-3fdd108f0766.png)

**Comment by keegan-o** [comment]
I kind of agree that these look a little bit too dull compared to the previous art we had for shiny bars of metal-- I think it is ok if we go back to a single bar rather than full stack too, if that is needed in order to capture the precious-ness of these items.

**Comment by WeaselDog** [comment]
Iron Bar and Iron Concentrate is also an issue. It looks too similar to dark rocks and Crushed Basalt. I can make a separate issue for this if needed.
