### ISSUE TITLE
User Issue: Objects are invisible or not accessible until client restart

### ISSUE THREAD

**Issue by Nicolausi113** [StrangeLoopGames/EcoIssues#21825]
V9.3.3 + 9.3.4
Some times objects are not visible at all
and accessing the stockpile leads to: “Can’t pick up block within another world”
![mine,](https://user-images.githubusercontent.com/38510829/117574229-6c3a8400-b0dc-11eb-8998-53c0aee0ee17.PNG)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. We are currently aware of the said issue.
Mering with #17803
