### ISSUE TITLE
ARRRG if you over load the Stockpile all item of the last add go to walhalla

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2182]

**Comment by REPOSEECO** [comment]
![grafik](https://user-images.githubusercontent.com/26040573/30603259-4038b64c-9d67-11e7-805a-5227339e8f9a.png)

**Comment by Fank** [comment]
If you live in a dungeon and do that the items which goes to walhalla will appear on top if the dungeon.
/cc @Frozen-byte

**Comment by Fank** [comment]
Got some reports from other player that it also disappear some other items in the stockpile, by interacting with it.
Also items will disappear over time. (unable to validate it)

**Comment by REPOSEECO** [comment]
correction --> only one part disappears with dirt is the same

**Comment by Frozen-byte** [comment]
When I put a new stack on the pile another stack disappears.
I've played around and found that it mostly vanish the first stack after an empty slot.

This happens more likely in underground and when loose items floating on the pile.

**Comment by Fank** [comment]
Additional information https://github.com/StrangeLoopGames/EcoIssues/issues/2223#issuecomment-331099102

**Comment by metachronism** [comment]
fixed
