### ISSUE TITLE
[0.9.4 Develop-280] Client crash when opening Objective "O"

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21822]
Crashes client when hitting objective button.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6446673/Player-prev.log)

Edit, seemed to open eventually, but crashed 6 times before i managed to open.

**Comment by Daniel-Magulado** [comment]
Merging with #21756
