### ISSUE TITLE
9.4 Develop 281 - Resizing crafting window results in bars going iffy

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21835]
Unsure how to word this one, resizing the window size breaks the highlighting and causes some overlapping

![image](https://user-images.githubusercontent.com/61889138/117650393-8df14500-b188-11eb-95c4-4653dc624cf1.png)

![image](https://user-images.githubusercontent.com/61889138/117650427-95b0e980-b188-11eb-867e-762111da1eda.png)

**Comment by Daniel-Magulado** [comment]
Hi, MishkaFur.

Thank you for making a report about this.
I'll be forwarding this to our development team so they can look into it further and make necessary fixes.

I can confirm that resizing any crafting UI causes recipe names and highlight bar to overlap and loss their alternating design.
Tested on 0.9.4 develop-281.

In some cases, the recipe losses its name and ends up displaying **Recipe Name**
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/dbaa59f3-cea2-488a-86a1-445b3644a037)
Furthermore, it messes up icons and buttons to be missplaced.

**Comment by gzatravkin** [comment]
Probably some problem with fast layout, like not getting update
