### ISSUE TITLE
Storage QOL: general output-input trigger

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#21833]
Add output-input trigger that will trigger all storages at once.
https://docs.google.com/document/d/1rDuakzTBI8G1Q4Lv0YIdNutB4YtzbleG4ObxZhvie0w/edit?usp=sharing!
![storage_link_3_general_link](https://user-images.githubusercontent.com/27898520/117646415-272e5480-b1a5-11eb-9ec6-bfae3babb7da.jpg)

It should toggle all storages into a chosen state. If any storage is changed after that, general toggles should show that they are currently inactive (some additional color effect)

**Comment by TwixterZ** [comment]
Feature tested and confirmed as of 0.9.5 Develop-340

![universal flick](https://user-images.githubusercontent.com/78054747/126963797-db2f3fb5-0090-446b-94f6-f0d0ae804e2a.gif)
