### ISSUE TITLE
[Hosted Worlds] Purchasing Cloud Worlds in Sandbox takes a long time to process.

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21831]
Purchased Cloud Worlds for users 199680 and 199681 but the time taken to process it is longer than usual.

Upon looking at the database it shows that no Cloud Worlds or Citizens has been purchased despite going through the entire purchasing process through Paypal.

**Comment by denysaw** [comment]
It started to send IPNs about a month ago, but sometimes takes a while, yep

**Comment by j3fffff** [comment]
paypal never sends the ipn. i dont see any in ipn history for staging, after 4/28/21

**Comment by denysaw** [comment]
> paypal never sends the ipn. i dont see any in ipn history for staging, after 4/28/21
 
Maybe in history. But buying worlds started to work on our sandbox, means paypal sends ipn. Try yourself ;)

**Comment by j3fffff** [comment]
@Ry4ndrew can you confirm?

**Comment by Ry4ndrew** [comment]
@j3fffff retested with a new account as user 199682, still no changes. For users 199680 and 199681 the payment is still processing.

**Comment by denysaw** [comment]
I also confirming PayPal stopped to fire IPN again (( Crazy. It was like that about month ago, but 3 weeks ago it started to work and now again. Very strange... It uses same code as on Prod, where it worx, so probably can't be code issue (wrong formed PayPal request etc).

**Comment by j3fffff** [comment]
weird the purchase is being made on paypal, and subscription created. but no ipn sent.

I'll reach out to paypal support.

I have a feeling ipn was broken for a bit.
Cause couple days ago i checked and there were no IPNs after 4/28/21
But now, I look and there are many IPNs after after 4/28/21 but none of them are for cloud world. only game buys.

in that case, @Ry4ndrew could you please test one more time, with new account?

**Comment by Ry4ndrew** [comment]
@j3fffff I've retested it with a new account 199683. Still an issue with the long processing time after purchasing a Cloud World and Citizens. Buying Eco seems to have no issue on the matter as I can purchase any tier, but once I attempt to purchase a cloud world the ipn does not go through.

**Comment by j3fffff** [comment]
ok asked paypal

**Comment by Ry4ndrew** [comment]
Fixed as of current web release.

**Comment by j3fffff** [comment]
have a feeling this was a paypal sandbox bug, that they eventually fixed. happens time to time

**Comment by j3fffff** [comment]
![image.png](https://images.zenhubusercontent.com/5ee7b64c2edca519271c634b/78d6aafe-3a50-4817-8c43-25d2366d0de5)
