### ISSUE TITLE
9.4 Develop 281 - Turning right in steam truck = chest burster

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21836]
Turning right in steam truck = chest burster

![image](https://user-images.githubusercontent.com/61889138/117656736-98afd800-b190-11eb-9a03-9b6b7f8794c1.png)

**Comment by Daniel-Magulado** [comment]
Hi @mishkafur,

Thank you for making a report about this.
We're currently aware of this issue.
I'll be merging this to #21820.
