### ISSUE TITLE
Incompatible version of ModKit Component "Collections preview6 0.9.0. June 16 2020 with version Unity 2020"

### ISSUE THREAD

**Issue by SpiritOfAncientWherewolf** [StrangeLoopGames/EcoIssues#21847]
Hi everyone. Tooday i was created new project and find this issue.
This is actual for modkit 9.3.4
ProjectVersion
m_EditorVersion: 2020.1.17f1
m_EditorVersionWithRevision: 2020.1.17f1 (9957aee8edc2)

And this version of unity cant see very important component of any mod.  "Collections preview6 0.9.0. June 16 2020" Because in unity asset store i think its older version for 2019.

Who knows how many BUG'S it can provoke OR FIX, but i think need update components of game to new version. Ofcource with backups.

**Comment by redwyre** [comment]
Unity changed how the package manager works.
You need to manually add the package to manifest.json:
`"com.unity.collections": "0.14.0-preview.16",`

**Comment by redwyre** [comment]
Actually the instructions on the wiki are already updated: https://wiki.play.eco/en/Installing_the_ModKit
