### ISSUE TITLE
USER ISSUE: Tailoring

### ISSUE THREAD

**Issue by Pakka77** [StrangeLoopGames/EcoIssues#21842]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Using the Tailoring  Table or Loom.  Make any of the new Items.

**Expected behavior:**
Player Skill and Table Upgrades should  reduce to greatly reduce the calorie count used for making item.

**Actual behavior:**
It appears to cost nearly double the expected Caliories to make any of the new items.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Pakka77,

We're closing this ticket due to a lack of response.
Please feel free to reopen it if you ever encounter this issue again.

**Comment by Daniel-Magulado** [comment]
Hi @Pakka77,

We're closing this ticket due to a lack of response.
Please feel free to reopen it if you ever encounter this issue again.
