### ISSUE TITLE
Dockerfy Accounts

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#21854]

**Comment by redwyre** [comment]
I'm going to have to push this one back to you guys as I don't know much about accounts.

**Comment by j3fffff** [comment]
how you think it would look @denysaw ?

**Comment by denysaw** [comment]
I've already done that once ☺️ On the very start of working here ) Then moved to Xampp cuzz of light cpu/ram loading in comparison to Docker ) It'll be based on standard docker images of php with composer. It'll be in a single docker-compose.yml file

**Comment by denysaw** [comment]
@redwyre done. Run it with usual: `docker-compose up -d`

**Comment by j3fffff** [comment]
i think to complete this task, we need to migrate accounts to docker
