### ISSUE TITLE
[0.9.4 develop-284] Icons with low resolution

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21866]
Some specialty icons in Skill UI:
![image](https://user-images.githubusercontent.com/45708377/118095643-ffbfcd80-b3d8-11eb-8aea-1c1d5e7af162.png)
![image](https://user-images.githubusercontent.com/45708377/118095700-0ea68000-b3d9-11eb-8d84-f061f8ecb5a7.png)
![image](https://user-images.githubusercontent.com/45708377/118095711-136b3400-b3d9-11eb-8dae-e8dca75db2ae.png)
![image](https://user-images.githubusercontent.com/45708377/118095718-16662480-b3d9-11eb-9029-9cb37153c9c9.png)
![image](https://user-images.githubusercontent.com/45708377/118095738-1c5c0580-b3d9-11eb-985a-de9ea5c37545.png)
![image](https://user-images.githubusercontent.com/45708377/118095749-20882300-b3d9-11eb-83f2-7c012d935fd9.png)
![image](https://user-images.githubusercontent.com/45708377/118095775-267e0400-b3d9-11eb-8a4d-4a4ef20a0cb3.png)
![image](https://user-images.githubusercontent.com/45708377/118095794-2aaa2180-b3d9-11eb-875c-3deabc3f8ab2.png)

Stars available in skill UI:
![image](https://user-images.githubusercontent.com/45708377/118095677-08b09f00-b3d9-11eb-9a92-d056f007b1a4.png)

**Comment by SlayksWood** [comment]
Start in Learn now window in skill UI:
![image](https://user-images.githubusercontent.com/45708377/118095977-74930780-b3d9-11eb-9558-027dc0c7cb6b.png)

**Comment by SlayksWood** [comment]
"+" buttons everywhere:
![image](https://user-images.githubusercontent.com/45708377/118103850-0a7f6000-b3e3-11eb-8fda-c17b3f2231b1.png)
![image](https://user-images.githubusercontent.com/45708377/118103867-11a66e00-b3e3-11eb-925b-7a99a5c12120.png)

**Comment by SlayksWood** [comment]
filter:
![image](https://user-images.githubusercontent.com/45708377/118478267-59493480-b718-11eb-864b-af05faacc87b.png)

**Comment by TwixterZ** [comment]
Fix observed on 9.4 Staging 2021 and confirmed

Skills UI: 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c3ae17b0-c30c-48e8-a2ff-63daa9c7ce7e)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/4ff42778-17e4-4a45-9607-55f004245a4a)

"+" Buttons
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9ee907c9-a45a-4949-a46d-b8492b69b57b)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/26c034e8-c90f-4f43-81c9-95918fa287b0)

Item Filter
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ee77dad7-981e-4adf-b55b-cd57e78de4c1)
