### ISSUE TITLE
Icon is weird

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21869]
![image](https://user-images.githubusercontent.com/3536496/118173829-ea4fa100-b3e2-11eb-9801-c61f1ae4af3e.png)
There are some parts of it that are transparent and some that are not
Also the perspsective is weird compared to other icons, which are isometric, like:
![image](https://user-images.githubusercontent.com/3536496/118173888-02bfbb80-b3e3-11eb-97c3-2c304b3cc847.png)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/b3ce0abe-97bc-4388-9b94-f16f2db40a45) this icon was done quite a while ago unless you want another made?

**Comment by RobertMangano** [comment]
what is the icon called?

**Comment by RobertMangano** [comment]
updated house icon and assigned to tutorial sprite sheet
