### ISSUE TITLE
PayTax trigger not working

### ISSUE THREAD

**Issue by IronyTroll** [StrangeLoopGames/EcoIssues#21868]
As the title says, Pay Tax trigger no longer triggering. 

TEST: simple law that taxes you $1, which should trigger PayTax to give you back $1. 
Steps to reproduce:

1) make new world (done 2, one for 9.3.3 & 9.3.4, images below from 9.3.4)
2) do this:
/give hewn log
/give court
/give capitol
/give devtool

make box with hewn log + devtool, put items in, make constitution /fin 1 then make law (see image), then /fin 2 

![image](https://user-images.githubusercontent.com/71368607/118137805-f66e4980-b448-11eb-9d76-88db6017827e.png)

![image](https://user-images.githubusercontent.com/71368607/118137975-2584bb00-b449-11eb-90da-f9742441ee22.png)

**Comment by Daniel-Magulado** [comment]
Hi @IronyTroll,

Thank you for writing a report about this.
I can confirm that **Pay Tax** trigger clause is not working.
Furthermore, the Citizen clause for THEN is treated by the law as a no recipient.

Tested both on 0.9.3.4 Release-226 and 0.9.4 Develop-286.


https://user-images.githubusercontent.com/77248866/118363581-a5389400-b5c7-11eb-9c73-1564c454273b.mp4

Additionally, forcing to pay tax via /money tax results in an error where section 2 of the law that indicates Pay Tax as the trigger states "Payment without receiver skipped" despite having Citizen as the clause.

#### Reproduction Steps
1. Setup a law where **Pay Tax** is the trigger.
2. Trigger the law you set up on step 1.
3. Observe.
