### ISSUE TITLE
USER ISSUE: Pwer -Consumption

### ISSUE THREAD

**Issue by DoJos** [StrangeLoopGames/EcoIssues#21862]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Put fuel-tags (coal) in machines (oil refinery) 2. go to sleep for a few hours (4-8)

**Expected behavior:**
It should have consumed

**Actual behavior:**
it says that there is no fuel in it. You have to switch positions of both slots or replace them. we mentioned that especially on the oil-refinery that leads into a stopping production

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @DoJos,

Thank you for writing a report about this issue.
However, we couldn't reproduce this issue, and following the provided steps to reproduce it did not result in the stated actual behavior.
A recorded video of the issue as it happens would help us further investigate this issue.
Furthermore, we would also like to request your game log files after reproducing the issue.
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.

**Comment by Daniel-Magulado** [comment]
Hi @Dojos,

Due to lack of response. I will be closing this ticket for now.
Do not hesitate to reopen again if you encountered the same issue.

Thank you.
