### ISSUE TITLE
[0.9.4 develop-284] Camera glitches if you press ESC in the beginning of Meteor Tutorial

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21865]
Step to reproduce:
- start Meteor Tutorial.
- find Meteor in the sky.
- Press ESC when camera starts focus on meteor.

Actual Result: 
- try to move out camera, you can't do it 2-3 second( as far as I understand until the focus time passes)

Expected Result:
- after pressing ESC I can move the camera freely

video:

https://user-images.githubusercontent.com/45708377/118093677-760f0080-b3d6-11eb-93aa-3b50b233ad98.mp4

**Comment by johnkslg** [comment]
Reopening this because the PR for it was reverted. See details why in comment: https://github.com/StrangeLoopGames/Eco/pull/8821
