### ISSUE TITLE
USER ISSUE: Map not save settings

### ISSUE THREAD

**Issue by Tavren** [StrangeLoopGames/EcoIssues#21864]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
1. Set map settings to 2D view
2. Leave from game
3. Start game again

**Expected behavior:**
Map should save desired settings like 2D view

**Actual behavior:**
Reset to default 3D view

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Tavren,

Thank you for writing a report about this. However, we are currently aware of this issue.
I'll be merging this report to #21766.
