### ISSUE TITLE
USER ISSUE: Disconnect closes the program

### ISSUE THREAD

**Issue by Pakka77** [StrangeLoopGames/EcoIssues#21861]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Hit Esc
Click the Disconnect button

**Expected behavior:**
Back to the worlds Menu

**Actual behavior:**
Closes the program completely might be an  actual crash to desktop not sure.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@Pakka77 Thank you for the report. merged to #21517
