### ISSUE TITLE
USER ISSUE: Blast Furnace disappearing

### ISSUE THREAD

**Issue by TheRealBrainbug** [StrangeLoopGames/EcoIssues#21878]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Don't really know, after putting some distance (~100 Blocks) between me and a "placed item" like a Blast Furnace (initially working as intended) and coming back, the item is not visible any more (as if it was not there). Other players can see it as normal. Relogging fixes this.

**Expected behavior:**
Placed items should always be / load where they had been placed for every player in the same way.

**Actual behavior:**
Placed items (currently only observed with the Blast Furnace) disappear / do not load in.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, @TheRealBarinBug,

Thank you for writing a report about this. However, we are currently aware of the said issue where objects, including crafted items as well as world objects, tend to disappear and not rendered at all resulting in either an invisible object or missing object.
Merging #19797
