### ISSUE TITLE
[0.9.4 develop-285] Waterwheel issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21874]
- [x] 1. Block check problem if you turn the wheel 90/270 degrees during placement.
Step to reproduce:
- take waterwheel, want to place:
![image](https://user-images.githubusercontent.com/45708377/118230550-85558300-b496-11eb-925c-17993efb062a.png)
- I need to rotate it, press Q or R:
![image](https://user-images.githubusercontent.com/45708377/118230576-91414500-b496-11eb-8ddc-9d8ae8ce64ba.png)
- place waterwheel and check status:
![image](https://user-images.githubusercontent.com/45708377/118230611-9dc59d80-b496-11eb-901c-b87d7482668c.png)
- try to find this block:
![image](https://user-images.githubusercontent.com/45708377/118230699-c188e380-b496-11eb-8262-57c1f1d36d20.png)
- you can see that this block inside rock, seems check is not change during rotation.

- [x] 2. Is it possible to remove the rotation animation if the waterwheel has the wrong status? so it will be visually clear that it does not work. I place waterwheel in ocean and it still have the same animation. it takes time for the player to realize that it doesn't work. And stopping the rotation will surely indicate that the wheel is not working.

- [x] 3. I read the information in the PR about how the waterwheel should work, but without this information it's pretty hard to understand what this string in status mean:
![image](https://user-images.githubusercontent.com/45708377/118231141-58ee3680-b497-11eb-809b-64b91f0ad9f4.png)
"Waterwheel is generating 200W due to 1 side (max 2) being in water flow"
What is water flow? How to make a second flow of water appear? In game we have nothing about it. 
So we need to update at least our ECOpedia where we provide description of this and also add a few screenshot how to place waterwheel to have 1 flow and 2 flows.
![image](https://user-images.githubusercontent.com/45708377/118232222-ebdba080-b498-11eb-9b1b-490fccfeb034.png)
![image](https://user-images.githubusercontent.com/45708377/118232185-e2eacf00-b498-11eb-9139-ece4f9fda580.png)
If this is not your task, you can make a separate issue for this.
But we can a little improve our status, so you can show something like this:
![image](https://user-images.githubusercontent.com/45708377/118232056-b040d680-b498-11eb-9c7a-210e7dc705f4.png)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2009

Status when placed on river : 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/e0d28c8d-7085-44fd-83ea-0e4f274e4b2e)

Status when placed on waterfall : 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/e5e847e4-6618-470c-adaa-a287fb3b1f78)

Status when placed on a waterfall and river : 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/192d123c-a978-4230-be9d-81a05089111d)

Waterwheel placement with 90 degrees rotation working :
https://youtu.be/c_c-Lw5ewyY
_Waterwheel water detection takes time as seen in video_
_This Video also proves fix for 2nd issue where waterwheel did not turn when its in bad status (eg : not in water)_

**Comment by TwixterZ** [comment]
Further testing done for cause of waterwheel took few second before became function (as per video) , seems to be caused by water displacement when waterwheel is placed down
