### ISSUE TITLE
[0.9.4.0 develop] /spawn Assembly Line doesn't work

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21873]
Using command /spawn Assembly Line does not work. It also causes a server exception:

`World object not enabled after spawning
`
![StuckAssemblyLine](https://user-images.githubusercontent.com/47330823/118214535-be550f80-b424-11eb-8151-18ee60eaf49f.png)

Command /spawn Robotic Assembly Line does work

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1997.

Closing as fixed.
