### ISSUE TITLE
Civics Tick and other server processing should not cause lag

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21870]
There are reports that long civics ticks, doing things like rebuilding demographics, will cause the server to lag for everyone.

There must be something going wrong with our multithreading, because the server is built to allow that to run in the background while the rest of the server processes normally.  In fact it used to be the case that the WorldLayer tick would freeze the server, but then I believe Alex changed the thread settings and made it run in the background fine.

For this task, investigate applying that same thread-fix that was done for world layers to all other background-tick threads in the server, like civics, but also look for others.

**Comment by SlayksWood** [comment]
closed as fixed, pretty hard to test on local world.
