### ISSUE TITLE
Power usage ignoring authorization

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#21877]
Power usage ignores authorization. The radius for power supplied is very large for generators. I logged in to find out someone about 9 claims away was running a very long run time for several pumpjacks. I noticed it because the pollution layer glowed like the sun. I get the power grid stuff but it should not ignore authorization

**Comment by Daniel-Magulado** [comment]
Hi @jamesyoung79,

Thank you for writing a report about this. However, we are currently aware of this issue where other neighboring players can steal power from you.
Merging with #12483
