### ISSUE TITLE
USER ISSUE: Ich melde einen Bug 

### ISSUE THREAD

**Issue by Gamer22gamer** [StrangeLoopGames/EcoIssues#21888]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Meine lagger sind immer weg und die sachen die dren sind sehe ich aber ich kann nix rein legen oder raus holen und im haus sind die sachen dann weg kollege kann die sehen ich nicht ich muss das Spiel dann neu starten dann sehe ich meine sachen und das lagger wieder 

**Expected behavior:**
Sachen verschwinden einfach 

**Actual behavior:**
Kopf sehr oft vor 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Bitte einmal DXDiag hochladen. (Betriebssystemsuche -> DXDiag - Anweisungen folgen)
Außerdem, nachdem das Problem auftrat, die Logfiles wie hier beschrieben hochladen: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Darüber hinaus bitte mehr Informationen: Tritt das im Singleplayer bei dir auf, einem Public Server, bei einem von einem Freund gehosteten Server? Wo wird der Server gehostet?

**Comment by IcedForge** [comment]
Unfortunately due to lack of response from the author of the issue we will be closing this as we cannot further assist without the above mentioned information. Please reopen this issue and address them for further help if you are still having problems.
