### ISSUE TITLE
[0.9.3.4 Release-226 | 0.9.4 Develop-286] Fishing pole fishing line is offset/displaced in first person view

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21880]
Build:
- 0.9.3.4 Release-226
- 0.9.4 Develop-286

## Issue
The fishing line of the **Fishing Pole** is offset/displaced when in first-person view.

![image](https://user-images.githubusercontent.com/77248866/118347757-3b44ce00-b578-11eb-87e6-d84fdd844966.png)

It's visually displeasing to look at but it's fine when in 3rd person view.

![image](https://user-images.githubusercontent.com/77248866/118347809-8bbc2b80-b578-11eb-845c-6fdbe43ecc4a.png)

**Comment by SlayksWood** [comment]
[Uploading... image.png]
