### ISSUE TITLE
[0.9.4 Develop-286] Codes appearing on Reputation UI under Player's Opinion

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21885]
Build: 0.9.4 Develop-286

Somewhat related and can also be seen here #21066 and #21799.

## Issue
On the Reputation UI just under the Player's Opinion section, some codes are starting to appear if the characters (including the player's name) get long enough.

![image](https://user-images.githubusercontent.com/77248866/118355469-bd49ec80-b5a2-11eb-93f7-5fedb6c733d1.png)
![image](https://user-images.githubusercontent.com/77248866/118355554-26316480-b5a3-11eb-99b2-777718262d7f.png)

#### Reproduction Steps
1. Participate in Work Parties with long titles.
2. Make sure that you've contributed to the word party you participated on step 1.
3. Press O key and hover your mouse icon over the reputation title of your avatar.
4. Observe the Reputation UI most especially the Player's Opinion section.

#### Actual Result

https://user-images.githubusercontent.com/77248866/118355690-e1f29400-b5a3-11eb-97de-66d24059df6a.mp4

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2020

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/c1ca01c0-385c-4cae-ac39-87dcb8010143)
