### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Solkongen** [StrangeLoopGames/EcoIssues#21884]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.IsNotRelevant(INetObjectViewer viewer)
   at Eco.Core.Agents.WorldObserver.RemoveIrrelevantObjects()
   at Eco.Plugins.Networking.Client.Update()
   at Eco.Plugins.Networking.Client.<.ctor>b__71_2()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Solkongen, 

Thank you for writing a report about this error.
May we ask how this happened? This will help us to investigate what caused this issue.
Detailed reproduction steps, your game logs, and a recorded video as the issue happen if you have 100% steps to reproduce this issue will greatly help us.
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
hi @Solkongen 

Do you still face this issue? if so, can you provide more information as requested above.

**Comment by TwixterZ** [comment]
Closing issue due to no response
