### ISSUE TITLE
[0.9.4.0 beta develop-287] Incorrect description of setting for Max Active players in server GUI

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21897]
Should not have the 2nd sentence as it does not limit specialtys only active players on the server.
![Screenshot_153.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/1ae0cac7-af11-43e3-b0e0-a1760e855383)

**Comment by WeaselDog** [comment]
It appears Max Active Players is not implemented
