### ISSUE TITLE
[0.9.4 Develop-287] Holding land claim items while on other UI induces flashing patterns

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21892]
Build: 0.9.4 Develop-287

## Issue
If you open a different UI while holding a land claim item such as **Land Claim Papers** and **Land Claim Stake** prompts a flashing of pattern on the player's screen. Placing this as high since this can potentially cause seizures for those who are suffering from photosensitive epilepsy. Especially that there's no visible warning around the game about flashing of lights.

#### Reproduction Steps
1. Hold and land claim item.
2. Press ESC or open a different UI such as pressing L.
3. Observe.

#### Actual Result

https://user-images.githubusercontent.com/77248866/118439332-5bab8e80-b718-11eb-8c7c-a369d84ece1b.mp4

**Comment by SlayksWood** [comment]
merged to #21745
