### ISSUE TITLE
Investigate Cloud World Subscriptions not cancellable

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21896]
Users:
46130
131254

Both have no active world displayed in the admin backend. (Empty = No worlds)
Both see a subscription they cannot cancel, as the update subscription button is not clickable when setting subscriptionsto 0.
The latter also had to pay the world again, despite it being cancelled and removed a month ago by me by setting expiry date.

**Comment by denysaw** [comment]
@D3nnis3n But `46130` has no `billing_profile_id` at all, how he could see subscription? 
Btw, did you set `renew = 1` when you were setting expire date for those worlds? Cuzz only those worlds will expire, which have `renew = 1`.

**Comment by denysaw** [comment]
@D3nnis3n Second guy even has no subscription menu:
![image](https://user-images.githubusercontent.com/5720101/118558487-fcc13600-b766-11eb-86b8-f7ddec840e6d.png)

Or you already deleted his world manually (that's why)? Did you do the same for the first guy?

**Comment by denysaw** [comment]
Done. Please, tell 131254 to go to Subscription. Now he'll be able to decrease it and cancel ;)

**Comment by Ry4ndrew** [comment]
Confirmed fixed as Cloud World subscriptions cancellable as of the current web release.
