### ISSUE TITLE
[0.9.4 develop-287] Remove items from sale/purchase list in store breaks its UI

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21898]
Step to reproduce:
- add something to sale list:
![image](https://user-images.githubusercontent.com/45708377/118482313-3cfbc680-b71d-11eb-9dfb-0e3804758d05.png)
- try to delete only advanced update 4:
![image](https://user-images.githubusercontent.com/45708377/118482374-513fc380-b71d-11eb-945e-219778410aec.png)
- add something to purchase list and delete 3rd string:
![image](https://user-images.githubusercontent.com/45708377/118482406-5d2b8580-b71d-11eb-8a8c-8b2e1c6b435e.png)

I'll have this glitch until cache updates

**Comment by TwixterZ** [comment]
Fix checked and confirmed as of 0.9.4 Staging-2034

https://user-images.githubusercontent.com/78054747/123338806-061a9b00-d57c-11eb-8108-613461db21ee.mov
