### ISSUE TITLE
9.4 Dev 287 - World objects invisible

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#21906]
World Objects are invisible, can see them on map, place new ones down they go invisible! :D

This room should have store, loom, kiln etc in it.

Server and client have both been restarted several times.

![image](https://user-images.githubusercontent.com/61889138/118563688-ee731a00-b766-11eb-9178-ab5765b11dac.png)

![image](https://user-images.githubusercontent.com/61889138/118563820-2da16b00-b767-11eb-9a2f-76d4cb80260f.png)\\

![image](https://user-images.githubusercontent.com/61889138/118564208-d2bc4380-b767-11eb-83b2-542fd6c13eb3.png)

**Comment by TwixterZ** [comment]
closing this issue as duplicate with https://github.com/StrangeLoopGames/EcoIssues/issues/21449
