### ISSUE TITLE
USER ISSUE: void storage bug

### ISSUE THREAD

**Issue by codoje** [StrangeLoopGames/EcoIssues#21908]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
idk i just have alot of stuff in void storage
its a 4 wide storage thing that extends past my screen and i cant see the stuff in the void storage

**Expected behavior:**
a scroll or an expand

**Actual behavior:**
is a thin screen that i cant see the bottom of and i cant get my items out of void sotrage

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @codoje

Thank you for writing a report about this.
We are currently aware of this issue and a fix is set in the coming game updates.
Refer to #21407 for more information.
