### ISSUE TITLE
USER ISSUE: Stockpiles and tables disappear

### ISSUE THREAD

**Issue by Cellolide** [StrangeLoopGames/EcoIssues#21902]
**There is normally a carpentry table:**
![Screenshot (5)](https://user-images.githubusercontent.com/33907318/118558505-03e84400-b767-11eb-9734-979400e9efa1.png)
**There is normally a stockpile:**
![Screenshot (6)](https://user-images.githubusercontent.com/33907318/118558513-05b20780-b767-11eb-9b53-cc8965f9ae82.png)

\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
After some random time periods some objects (in my case especially stockpiles and objects like carpentry tables and also storage chests) disappear. They still exist but i can't interact with them. In case of stockpiles i can see them in Linked inventorys tab though. After I restart the game everything is visible again

**Expected behavior:**
It should be visible and interactable

**Actual behavior:**
Objects not interactable or visible

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6496957/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6496958/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @Cellolide

Thank you for writing a report about this.
We are currently aware of the said issue.
I'll be merging this report to #19797.
