### ISSUE TITLE
[0.9.3.4 beta Release-226] Can't reach news service Unable to complete SSL connection

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21911]
Issue starting a server due to following error and getting stuck in a limbo where its not actually connecting just sitting in loading screen.
[Player(6).log](https://github.com/StrangeLoopGames/EcoIssues/files/6498623/Player.6.log)

```
Curl error 35: Handshake did not perform verification. UnityTls error code: 7
 
(Filename:  Line: 815)

[01:35:32.433] Can't reach news service Unable to complete SSL connection
```

**Comment by IcedForge** [comment]
![Screenshot_178](https://user-images.githubusercontent.com/24981362/118596544-c6f27080-b7ab-11eb-8c0c-68b1eaf9aa5f.jpg)

**Comment by IcedForge** [comment]
Have another user with similar problems, stuck in limbo trying to connect to a self hosted server from inside the game.
[Player(7).log](https://github.com/StrangeLoopGames/EcoIssues/files/6500337/Player.7.log)
[log_210518114634.log](https://github.com/StrangeLoopGames/EcoIssues/files/6500338/log_210518114634.log)

**Comment by j3fffff** [comment]
@Ry4ndrew can you replicate this?

**Comment by Ry4ndrew** [comment]
Hey @j3fffff I've been to replicate it since yesterday and I'm unable to get the same results as I'm always able to connect to the server whether it is self-hosted or cloud hosted.

**Comment by j3fffff** [comment]
@Ry4ndrew so you are saying it can't be repeated?
