### ISSUE TITLE
ich habe gerade ne stein abgebaut und jetzt hange ich in der wand fest kann nix mehr machen 

### ISSUE THREAD

**Issue by Gamer22gamer** [StrangeLoopGames/EcoIssues#21910]
hallo zusammen ich hange in der wand fest habe alles versucht mit commandos vom addmen es bring alles nix ich kann nix mehr machen ich brauche hilfe

**Comment by IcedForge** [comment]
Thank you for reporting an issue, only suggestion i can really give is either having an admin teleport you or test /unstuck

**Comment by IcedForge** [comment]
Admin command
![Screenshot_180.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8d47a20c-28e5-4c22-ab81-fe7d778dc587)

Player command
![Screenshot_181.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/31aaf334-b148-48da-b4dc-7d4c0f758d60)

**Comment by TwixterZ** [comment]
Hi @Gamer22gamer

Please let us know if commands provided by IcedForge above able to solve your issue?

_Bitte lassen Sie uns wissen, ob die oben genannten Befehle von IcedForge Ihr Problem lösen können._ - by google translate

**Comment by TwixterZ** [comment]
Closing this issue due to lack of response.

If issue persist, you may open a new issue for us to look into.
