### ISSUE TITLE
Hewn Nightstand shadowplacent has another furniture in it

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21917]
This Table looks similar with Hewn Dresser:
![image](https://user-images.githubusercontent.com/45708377/118615970-f1532680-b7c9-11eb-8d86-364cfc140660.png)
- place:
![image](https://user-images.githubusercontent.com/45708377/118616265-3414fe80-b7ca-11eb-8703-3c100613d0e4.png)

**Comment by Sekor2600** [comment]
fixed in staging Svn

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 1987
