### ISSUE TITLE
[0.9.4 Develop-288] Migration resets housing value

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21915]
Build: 0.9.4 Develop-288

## Issue
Migrating an existing game from 0.9.3.4 Release-226 to 0.9.4 Develop-288 causes the housing value to reset or drop to 0. Each room requires a furniture update to register again. Meaning, if you have 3 bathrooms, 3 bedrooms, 3 kitchens, and 3 general rooms, you need to pick up one piece of furniture from each room and place them again to make these rooms register the housing value.

#### Reproduction Steps
1. Have a game from 0.9.3.4 Release-226 migrate to 0.9.4 Develop-288. Make sure the game has a housing value for the player.
2. Play the game.
3. Observe the housing value.

#### Recorded Video
In this video, I have 3 rooms set up, a bathroom, a bedroom, and a general room.

https://user-images.githubusercontent.com/77248866/118611116-15752e80-b7ef-11eb-8717-ec5273593a64.mp4

I've already made an update to my bathroom thus the housing value on the video. In the video, I am making an update to my general room.

2nd Video - In this video, I manually did each room. Observe the housing value.

https://user-images.githubusercontent.com/77248866/118621896-625e0280-b7f9-11eb-9207-c4000b25ba39.mp4

[You can download my non-migrated world here](https://github.com/StrangeLoopGames/EcoIssues/files/6499828/Migrate.Test.Housing.zip)

**Comment by WeaselDog** [comment]
From migration log:
```
~ class[Eco.Gameplay.Rooms.RoomData] migration:
  - removed rooms: enumerable[class[Eco.Gameplay.Rooms.Room]].
  + added Rooms: enumerable[class[Eco.Gameplay.Rooms.Room]].
```

Need to make `rooms` migrate into `Rooms`

**Comment by Daniel-Magulado** [comment]
Tested through the following migrations:
0.9.3.4 Release-226 to 0.9.4 Staging-2035
0.9.3.5 Release-231 to 0.9.4 Staging-2035


The main issue of home property value resetting to zero appears to be fixed. However, I'm encountering #22341.
Closing as fixed.
