### ISSUE TITLE
Canning Assembly after placement seems have huge collider

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21918]
It creates invisible walls and roof around it:
![image](https://user-images.githubusercontent.com/45708377/118624973-47c46300-b7d2-11eb-9b30-72aa86609c37.png)
And i'm not in fly mode. you can place objects inside, but without /fly you can't go in it.

I can interact with it:
![image](https://user-images.githubusercontent.com/45708377/118625601-d507b780-b7d2-11eb-9dc5-499d57485d2d.png)

![image](https://user-images.githubusercontent.com/45708377/118626276-6b3bdd80-b7d3-11eb-9119-e5aaa4f140f9.png)

**Comment by Sekor2600** [comment]
fixed in staging svn

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 1987

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ab5a14ce-8224-4f58-9af5-06a1833cca62)
