### ISSUE TITLE
[0.9.4 staging-1987] Title screen issues

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21922]
- [x] 1. Unable to press some buttons on the home screen
Step to reproduce:
- start game:
![image](https://user-images.githubusercontent.com/45708377/118764745-afd28200-b882-11eb-81db-970650533d5b.png)
- you can click any buttons
- press Your worlds:
- press ESC
- you can't click red buttons now, you can click only Settings and Quit:
![image](https://user-images.githubusercontent.com/45708377/118764882-dc869980-b882-11eb-93f1-2c8f82cedb3c.png)
Seems something overlap their.

- [x] 2. Overlap during connection:
Press host a world, press esc, press continue:
![image](https://user-images.githubusercontent.com/45708377/118767466-7439b700-b886-11eb-833b-12e8df99a3ed.png)

**Comment by beastyn** [comment]
Could not reproduce any of them, though will fix an issue with switching menu options with keys. It was giving an error when switching from the last option to the first (continue).

**Comment by Daniel-Magulado** [comment]
Hmm, moving back to investigate pipeline.
I can't reproduce on 9.4 Staging-2026 as well.
