### ISSUE TITLE
Frequent Freezing / Crashing V9.3 - 2gb Vram

### ISSUE THREAD

**Issue by SAnzivino** [StrangeLoopGames/EcoIssues#21923]
Copy and paste from the original message posted to discord...

My game freezes or produces an error (and effectively crashes) every once and a while. Its varied. This can be within a minute of loading the world, or about an hour. Or it can occur before I load into a world. I had a problem for a while where the buttons to select a world wouldn't appear. It does not seem to be correlated with the number of people on the server or other events. I have tried changing all my settings, making sure things are at minimums or maximums.

I am running a windows laptop. and the game is downloaded / running from Steam.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6509064/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6509065/Player-prev.log)

**Comment by IcedForge** [comment]
Thank you for reporting an issue, it looks like there is an issue with your graphics card not fully capable of handling the load of textures, are you playing on a default world? Or are you playing on a live open world with activity on it?

**Comment by SAnzivino** [comment]
Sorry for the delay.
I am unsure of how to answer the question due to my unfamiliarity with the
game.
I am playing on a publicly hosted server. The last time I checked there
were about 125 players who had joined the world at some point.
A graphics card problem does make sense. When the screen freezes as far as
I can tell I am still able to move around for a few moments and interact
with the server.

Thank you for the help.

**Comment by TwixterZ** [comment]
Hi @SAnzivino if you feel that response from IcedForge is satisfactory, we will proceed to close this issue.

If you need further help from our end with your issue, you may re-open this ticket.
