### ISSUE TITLE
[9.3+] Amanita Mushroom Spores Icon lost picture

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#21926]
it game now:  
![Amanita Mushroom Spores Icon](https://user-images.githubusercontent.com/26339332/118865261-6f5a1f00-b8e9-11eb-8f22-d8a057b30d31.png)
but must be:
![AmanitaMushroomSpores_Icon](https://user-images.githubusercontent.com/26339332/118865412-93b5fb80-b8e9-11eb-928c-956c8bd98f38.png)

**Comment by TwixterZ** [comment]
New icon assigned to Amanita Mushroom Spores and applied as of 9.5 Develop-348

![image](https://user-images.githubusercontent.com/78054747/128446908-57f10d7a-bfe2-4d04-acc3-13df6637265c.png)
