### ISSUE TITLE
[9.4.0 staging] Update item description for world objects that have special power restrictions

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21920]
With the updates to power generation, it needs to be clear how the waterwheel and other items work. The descriptions for these items will need to be updated in the tech tree so the restrictions can be visible when looking at the tooltip before placing.

Here is a possible example for Waterwheel which adds to the existing text: "Uses the power of flowing water to produce mechanical power. Must be placed in a river and produces double power when under a waterfall." 

Items needing updates:
- Waterwheel
- Windmill
- Wind Turbine
- Solar Panel

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2037.

Closing as fixed.
Each power generator now has a new description.

Windmill: Uses wind to produce mechanical power. Requires clear space for 10 blocks in front of the blades for full power generation. Gains a small output boost when placed at higher elevations.

WindTurbine: Uses wind to produce electrical power. Requires clear space for 10 blocks in front of the blades for full power generation. Gains a small output boost when placed at higher elevations.

Waterwheel: Uses the power of flowing water to produce mechanical power. Must be placed in fresh water and produces double power when placed in both a river and waterfall.

Solar Generator: Generates electrical power from the sun! Requires a clear view of the sky above the generator for full output. Internal batteries ensure generation during nighttime.
