### ISSUE TITLE
[0.9.4 Staging-1986] Water block glitch with Fish Trap

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21921]
Putting down fish trap or "smite" underwater weed causing water block graphical glitch (shown below)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/543b0dee-91be-4efa-a6e8-1ee5cc862744)

https://i.gyazo.com/d7eec43780b70934fae38d59eb3e0853.gif

the fish trap are still underwater, hence tagging this as graphical glitch

There are also below glitches on water surfaces, might be related.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/295a4bff-5870-4b7c-b617-ca46fe85b639)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/6486b1cd-1425-441d-a817-eb4513ed47ba)

**Comment by SlayksWood** [comment]
Hole in water here #12080. I don't have it more then usual 
![image](https://user-images.githubusercontent.com/45708377/118941889-e085ea80-b95a-11eb-90d6-060666f3dd66.png)
But fish trap is regression, I guess it's related with fixing WaterWheel.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.4 Staging-2047

https://user-images.githubusercontent.com/78054747/124573226-ec325f80-de7b-11eb-86cc-59707c9876b8.mov
