### ISSUE TITLE
Game Settings and ingame UI preferences uses sysregit, should maybe use another save means for this

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21934]
This seems like a very odd way of saving UI settings and game settings overall.

1. Player messes up graphic settings to a non restorative state
 - We need to direct them and try to guide them into the mess that is the windows sys registry to remove/reset if they are unable to open the game. This is bad from every possible standpoint as i do not feel comfortable trying to get users to edit their system registry without potentially also breaking their entire windows installation in the process.

2. This also seems like a very bad and bulky way of storing data and i would assume it would potentially be better cached via our own saving structure inside "%userprofile%\appdata\LocalLow\Strange Loop Games\ECO"

![Screenshot_22.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2bd159e1-a12e-4a73-b396-91934ff18e2b)

**Comment by WeaselDog** [comment]
Converted to clickup
