### ISSUE TITLE
[Hosted Worlds - Advanced Options] Clicking on SettlementsPlugin does nothing

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#21938]

**Comment by denysaw** [comment]
@Ry4ndrew Investigated. On our end everything worx fine. You should create another issue titled "SettlementsPlugin has no config" as when we are requesting it GameServer returns no config:
![image](https://user-images.githubusercontent.com/5720101/121051172-876ee100-c7b9-11eb-9491-13093ea5f411.png)

Here's direct GameServer call example:
![image](https://user-images.githubusercontent.com/5720101/121051209-9190df80-c7b9-11eb-9a01-21a868849888.png)

Though the plugin presents in available GameServer's plugin list:
![image](https://user-images.githubusercontent.com/5720101/121051358-ae2d1780-c7b9-11eb-964c-4674811f3774.png)

Setting this issue to `Fixed` as new one should not relate to web not about interaction with any UI elements.

**Comment by Ry4ndrew** [comment]
Yep merging this issue with https://github.com/StrangeLoopGames/EcoIssues/issues/22174
