### ISSUE TITLE
Holding shift should accelerate tooltips

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2194]
Interface idea: when holding shift, tooltips should come up instantly, and not go away when you mouse-out of them.  Since tooltips are our 'manual' this will make it much easier to quickly go through stuff

**Comment by metachronism** [comment]
seems puntable to beta

**Comment by metachronism** [comment]
not go away?  how would you close them

**Comment by johnkslg** [comment]
release shift
And yeah tis puntable

**Comment by metachronism** [comment]
fwiw shift+click is generally context sensitive item moves, eg, if you open a storage chest and shift+click on something, it would move it to your inventory.

the tooltip opening to me seems way to slow in general with the .75s delay too, might also be contributing to this.

also games like WoW allow you to click on tooltip-giving text in chat, and that will open a tooltip window that stays open and is closable.  Might be one other idea

**Comment by MarjieAVolk** [comment]
I think a tooltip browser is a good solution, like what Eric is saying.  So when a tooltip pops up, there will be a button on the tooltip, maybe with an arrow up and to the right icon, that would open the same tooltip in a window.  That window could also have a search bar for searching for other tooltips.

Clicking on the tooltip link to go to the tooltip window sounds nice if we do want to do that.  We are already doing a thing where clicking on a tooltip link does different things for each type of link, like the skill one opens it in the skills UI.  But honestly that is kind of bizarre, we could move that behavior to a separate thing that's in the tooltip maybe.  Or have like special action links as a separate thing.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#374
