### ISSUE TITLE
[0.9.3.4] Parallel Processing vs Focused Workflow for different tables of the same specialty

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21941]
So we have two core skill perks:

![image](https://user-images.githubusercontent.com/964559/119078987-1d2e0200-b9ac-11eb-9b50-389293592082.png)
![image](https://user-images.githubusercontent.com/964559/119079000-20c18900-b9ac-11eb-90d3-891485f2b834.png)

From what I was expecting, Focused Workflow gives you a bonus if you have only one table of a given type in a room to double your speed, and Parallel Processing works if you have two or more identical tables. However, then I heard someone point out that it's not how that works - it applies to all tables of the same profession. So a Screw Press and a Machinist Table give this with Focused Workflow:

![image](https://user-images.githubusercontent.com/964559/119079152-6da55f80-b9ac-11eb-83e7-6f4db3ce7d8b.png)

while a Screw Press that is alone with Focused Workflow does this:

![image](https://user-images.githubusercontent.com/964559/119079197-7dbd3f00-b9ac-11eb-87f1-573dd290be36.png)

which to me is very misleading and pretty much means Focused Workflow is 99% useless for Mechanics and Industry.

Either the perks should specify they check for any table of a given specialty, or Parallel Processing should only look at identical tables. The latter would probably be preferrable.

**Comment by TwixterZ** [comment]
Hi @ThePiachu 

On my testing, I only have Focused Workflow talent chosen for Mechanic 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/95cf93e8-c7b5-4960-ab7a-d846ef3fbde7)

I'm checking on this issue, and please see my finding below :
 
With 1 Screw press and a machinist table, time required to craft 100 iron plate is 1 hr 40mins
https://images.zenhubusercontent.com/47210472/0c89f0b1-d1fc-42ef-9839-b2923142e4de/1_screw_press.mp4

When there are 2 screw press and a machinist table, time required to craft 100 iron plate are doubled to 3hr 20mins, which is equivalent to mechanic without focused workflow talent.
https://images.zenhubusercontent.com/47210472/35eaf5a2-c8d6-4f9d-bc47-448e470ad2ee/2_screw_press.mp4

Taking this test further by adding Lathe into a room with Machinist table and a screw press:
https://images.zenhubusercontent.com/47210472/506a53ec-95fa-4ae7-86f1-b5d38d36671f/screw_press___lathe.mp4
_Time required to craft 100 iron plate remains at 1 hr 40mins (with focused workflow)_

**Comment by TwixterZ** [comment]
As per my above comment, I can conclude that focused workflow talent is working as intended.
