### ISSUE TITLE
[0.9.4 Staging-1989] Tutorial doesn't automatically continue after Sleep Tutorial

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21947]
Build: 0.9.4 Staging-1989

## Issue
Tutorial doesn't continue automatically after completing the Sleep Tutorial.

#### Reproduction Steps
Note: You will encounter #21779 if it's still not fixed. So give yourself 4 pcs of land claim papers to bypass it.
1. Play through the tutorial.
2. Observe.

#### Actual Result

https://user-images.githubusercontent.com/77248866/119128022-ad7d4d00-ba67-11eb-9aee-0cd0439171bf.mp4

#### Expected Result
The game should continue opening up the dialogue box of the pending tutorial as a fix for #21552. If meteor tutorial becomes a hindrance for this, I recommend setting it as last to open once the rest of the tutorial is completed.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2024
