### ISSUE TITLE
[0.9.4 staging-1989] "Chop" hint is very high on Saguaro Cactus

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21944]
![image](https://user-images.githubusercontent.com/45708377/119091153-4cc52480-ba15-11eb-9984-dd15031bcf9e.png)
Seems it was not completely fixed with #15229

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2036.

Closing as fixed.
