### ISSUE TITLE
Carpet/Curtain Block broken

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#21948]
![grafik](https://user-images.githubusercontent.com/37456949/119145362-d8f13f00-ba49-11eb-916c-5248ac1cf808.png)

It spawns white blocks and has no shadowplacement

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1989.

This is true for Cotton Carpet, Nylon Carpet, and Wool Carpet.

**Comment by keegan-o** [comment]
fixed in staging, the blockset list in eco.unity was just entirely missing 'Fabric Blocks'.
