### ISSUE TITLE
[0.9.3.4] Blast Furnace doesn't recognise Anvil or Blast Furnace for Focused Workflow (smelting)

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21943]
I was testing some Focused Workflow vs Parallel Processing on a Blast Furnace and an Anvil in light of #21941 . There is something weird going on.

1) Anvil recognises another Anvil for Parallel Processing and Focused Workflow
2) Anvil doesn't recognise Blast furnace for Parallel Processing or Focused Workflow
3) Blast Furnace does recognise an Anvil and Blast Furnace for Parallel Processing, but not for Focused Workflow (Focused Workflow applies all the time, Parallel Processing applies if there is an Anvil present)

I've tested this with Parallel Processing on Advanced Smelting and Focused Workflow on Smelting.

To reproduce - place 1-2 blast furnaces and 1-2 anvils inside of the same building and see which times update (may need to increase and decreate recipe repetitions to update the ETAs).

**Comment by Daniel-Magulado** [comment]
Hello @ThePiachu,

Thank you for writing a detailed report about this issue. We also thank you for investing time to further test the issue.
We are currently aware of this and there's an open issue that affects parallel processing especially for crafting tables that has no room requirement.

Merging with #12407
