### ISSUE TITLE
Server Advanced Options Not Recognizing Login

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#21965]
![image](https://user-images.githubusercontent.com/33853005/119248804-e2190380-bb50-11eb-8d8f-0dc6d3b3301a.png)

**Comment by Ry4ndrew** [comment]
@ECO-ExPLiCiT Thank you for the report. Does the problem still persist after attempting a re-login?

**Comment by ECO-ExPLiCiT** [comment]
YesSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ryan Andrew ***@***.***> Date: 5/24/21  12:13 AM  (GMT-07:00) To: StrangeLoopGames/EcoIssues ***@***.***> Cc: ECO-ExPLiCiT ***@***.***>, Mention ***@***.***> Subject: Re: [StrangeLoopGames/EcoIssues] Server Advanced Options Not Recognizing Login (#21965) 
@ECO-ExPLiCiT Thank you for the report. Does the problem still persist after attempting a re-login?

**Comment by j3fffff** [comment]
fixed, the world was quite old. so configs were missing a newer option.
