### ISSUE TITLE
[0.9.3.4 beta release-226] WP details doesnt update to correspond with craft project.

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#21960]
Wp doesnt update the information to correspond with the actual craft project.
![Screenshot_28](https://user-images.githubusercontent.com/24981362/119239871-5d2beb00-bb4c-11eb-992e-132cfa98d4b8.jpg)

**Comment by TwixterZ** [comment]
Feature tested and confirmed as of 9.4 Staging 2024

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/4d103980-6e9b-4529-be53-8354a0667c73)
