### ISSUE TITLE
USER ISSUE: Trees of the same species planted in the exact same soil conditions behave differently

### ISSUE THREAD

**Issue by venetum** [StrangeLoopGames/EcoIssues#21963]
\
**User Id: (Not logged user) IG Nickname: Venetum**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
1. Find a place where Spruce trees grow
2. Use soil sampler underneath each tree to locate a spruce that is 100% happy in its soil
3. Find a spot nearby with all of the same conditions as that plot of soil.
4. Plant a spruce there
5. Analyse the soil under the new spruce
6. Temp suitability shows as 0% because it is under the minimum, despite having the same temp as the tree with all 100%s

**Expected behavior:**
When planting two of the same species, on soil with the exact same conditions, the health/condition of both trees should be the exact same.

**Actual behavior:**
One tree is happy with soil temp, the other tree is unable to grow with that soil temp.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6527149/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6527150/Player-prev.log)

Screenshots if they help: 

Tree 1:
![image](https://user-images.githubusercontent.com/36553360/119240862-8a779980-bb4a-11eb-82c5-6c0dbe2bfe5d.png)

Tree 2:
![image](https://user-images.githubusercontent.com/36553360/119240868-919ea780-bb4a-11eb-9efc-27aef9d5a1da.png)

**Comment by Daniel-Magulado** [comment]
Hi @Venetum,

Thank you for writing a report about this.
We are currently aware of the inconsistencies with the data shown by the soil sampler.
I'll be merging this ticket with #4410.
