### ISSUE TITLE
[0.9.4 staging-1990] Glass does not look solid at the chunk border

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21969]
It's differ from #18617, but now we can see it because we don't have black mesh:
![image](https://user-images.githubusercontent.com/45708377/119323103-02e37500-bc87-11eb-8bba-52dff832b84d.png)
Something similar to #13940, but but not so bad.

**Comment by TwixterZ** [comment]
This issue no longer prevalent as of build 0.10.0.0 Develop-712 of the game.
