### ISSUE TITLE
USER ISSUE: /manage whoami returns steam ID for a different user on the server

### ISSUE THREAD

**Issue by venetum** [StrangeLoopGames/EcoIssues#21964]
\
**User Id: (Not logged user) IG Nickname: Venetum**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
1. Run /manage whoami as a member on a server (steam only)
2. Hover over the steam ID

**Expected behavior:**
Should show your own stats

**Actual behavior:**
Shows a different members stats.
There are 4 of us on this server, we all tried it, happened for all of us.
Two of us got the same steam ID, two of us got different IDs.

Screenshot:
![Screenshot 2021-05-22 222408](https://user-images.githubusercontent.com/36553360/119241168-76349c00-bb4c-11eb-8e31-455cc09f63cf.jpg)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6527185/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6527186/Player-prev.log)

**Comment by IcedForge** [comment]
Hello, thank you for reporting an issue. Could i ask you to upload the save file somewhere and link it here? Or if you do not want it public you can mail it to jens@strangeloopgames.com or send a link via discord ( official Eco server ) Ice Forge #5886

**Comment by TwixterZ** [comment]
Hi @venetum could you share your save file as requested by IcedForge above for us to look into this further?

**Comment by TwixterZ** [comment]
closing this issue due to lack of response

@venetum feel free to re-open this issue when you are able to provide us with the save file.
