### ISSUE TITLE
[0.9.3.4] Clicking coordinate tooltip will always add map marker if the option for only nesting tooltips if CTRL is held is enabled

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#21970]
STR:
1. Enable the setting for only nesting tooltips if ctrl is held.
2. Go ingame and open a tooltip containing a coordinate.
3. Hold CTRL to prevent the tooltip from disappearing when you hover the tooltip.
4. Press the coordinate to show the position on the map.
5. Notice that a map marker was placed on the clicked coordinate.

I know this is the intended behavior for both functions, but having them on the same key causes a conflict which ends up with the user having a LOT of map markers they do not want.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.5 Develop-307

New key combination : "CTRL+Shift+Click" 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/8dfcae0b-b1f1-427d-9f7d-c1767a2abc53)
