### ISSUE TITLE
Declunkify: Add 'Law Guide' etc for view editor dialog 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21975]
In the editor for laws, demographics, etc: the dialog can be pretty intimidating:
![image](https://user-images.githubusercontent.com/3536496/119391603-679cd080-bc83-11eb-82d6-daef50913bca.png)

Let's add a link to a 'Law Guide', 'Demographic Guide', etc. It can be a large labeled book icon in the top left, and it's initilized to go to whatever help page is relevant to the type that is being edited. It should have a label too, to make it clear its a link to a guide.

**Comment by TwixterZ** [comment]
Features tested and confirmed as of 9.5 Develop-337
