### ISSUE TITLE
Campfire Recipes give 100 per craft instead of one!

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2197]
Newest staging, I just queued up 5x campfire beans, 5x corn, etc. to research cooking.  However I got 100-stacks of everything instead of a single craft.  max rank campfire cooking, 4/5 efficiency in case that's the cause:

![image](https://user-images.githubusercontent.com/30206504/30626659-2ae2209e-9d80-11e7-94cf-cb0299627175.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2201
