### ISSUE TITLE
[Art] Tall boots have wrong model and icon

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#21978]
Tall boots and Work boots have one model and icon now
![2021-05-23 (3)](https://user-images.githubusercontent.com/26339332/119401942-dc542700-bce4-11eb-88d3-f7b893a4da5d.png)

**Comment by StallEF** [comment]
I didn't see the old model but the icon was like this
![TallBoots_Icon](https://user-images.githubusercontent.com/26339332/119402340-787e2e00-bce5-11eb-8be6-f471609b0140.png)

**Comment by Daniel-Magulado** [comment]
Merging with #20845
