### ISSUE TITLE
[9.3.4] Ecopedia and tooltip not used color filter in icons

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#21977]
example:
1) Research papers must have yellow and green color on appropriate icons in Ecopedia
![2021-05-24 (4)](https://user-images.githubusercontent.com/26339332/119400827-5daaba00-bce3-11eb-9574-f4d34992671a.png)
2) Camo Pants and Camo Shirt must have green color in tooltip 
![2021-05-24 (2)](https://user-images.githubusercontent.com/26339332/119401320-0527ec80-bce4-11eb-9bde-06e5861ec074.png)

**Comment by SlayksWood** [comment]
Icons was changed https://github.com/StrangeLoopGames/EcoIssues/issues/18125, but I'd leave color difference too.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2030

Closing as fixed.

**Comment by StallEF** [comment]
@Daniel-Magulado  in Staging 9.5.0 it Bug back
See pipes also
