### ISSUE TITLE
Declunkify: Tune exhaustion feature

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21973]
- [ ] Optional settings for rollover minutes and extra starting-time minutes
- [ ] When first joining a server with an exhaustion limit, we inform the player of this more directly
- [ ] A visual representation of exhaust limits inside the game HUD somewhere to inform you of its status.
- [ ] Broken display
![image](https://user-images.githubusercontent.com/3536496/120872667-34482480-c554-11eb-9425-9cc727b18783.png)
- [ ] Make it send a mail when youre online and your time gets to 10 minutes, then another when it completes.

**Comment by WeaselDog** [comment]
Need to convert into an epic and fill in some of the design details.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.5 Develop-343
