### ISSUE TITLE
[0.9.4 Staging-1990] Moon Jellyfish not affected by water block shaders/effects

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21980]
Build: 0.9.4 Staging-1990

## Issue
The Moon Jellyfish doesn't seem to be affected by the water block effects and its shaders. Once you spot one, it always appears as if it's floating above water compared to fishes.

Screenshot 1
![jellyfish](https://user-images.githubusercontent.com/77248866/119462851-c0e42d00-bd73-11eb-86de-b787975ca2a0.jpg)
Observe how the shark gets affected by the water blocks.

Screenshot 2
![jellyfish 2](https://user-images.githubusercontent.com/77248866/119462878-c8a3d180-bd73-11eb-853e-8266f8658d54.jpg)

Screenshot 3
![jellyfish 3](https://user-images.githubusercontent.com/77248866/119462909-cf324900-bd73-11eb-99e2-6d90b8af552f.jpg)

Note: These screenshots are taken from my world as a fresh game and I have not done any commands.

#### Reproduction Steps
1. Start a new fresh world to emphasize the issue.
2. Look for some Moon Jellyfish.
3. Observe.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/124894471-5b2ac800-dfe4-11eb-9dc3-2e3316eba309.png)
![image](https://user-images.githubusercontent.com/45708377/124894480-5e25b880-dfe4-11eb-9003-d70c2858b74f.png)
