### ISSUE TITLE
Can't build on owned land due to conflicting laws

### ISSUE THREAD

**Issue by Senbotsu** [StrangeLoopGames/EcoIssues#2198]
Current build, marmot test server.  There is a law that says you can build on land you own, and another law called save the bunnies which prevents building.  When trying to place a log on my own property It is prevented:  

![image](https://user-images.githubusercontent.com/30206504/30626712-77dfb1c2-9d80-11e7-90a2-8a6a95fa16af.png)

**Comment by MarjieAVolk** [comment]
Working as intended.
