### ISSUE TITLE
Korean/Japanese Marketing Plan

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21987]
Create one! It should have:
- A hire of a firm or contractors that have a great understanding of Japanese and Korean social media and marketing, and experience with games. Can be two separate firms. 
- A schedule for launch in these regions, with a plan to build up hype for them.

**Comment by j3fffff** [comment]
duplicate https://app.zenhub.com/workspaces/lattice-mushroom-squad-5f69508d4c9949000fed0256/issues/strangeloopgames/slg/21
