### ISSUE TITLE
[0.9.4 Staging-1991] Issues with skipping all tutorials after skipping Nutrition Meter introduction

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21983]
Build: 0.9.4 Staging-1991

## Issues
If you skip all tutorials after skipping the **Nutrition Meter Unlocked** introduction modal, the game will not recognize it and still thinks you have not skipped the tutorials. You will end up having the graphics interface of the calorie and housing looking like the image below.
![image](https://user-images.githubusercontent.com/77248866/119490636-a5871b00-bd8f-11eb-92d3-26d482d625b6.png)

#### Reproduction Steps
1. Trigger Food for forage or Empty stomach. Anything of the two is fine.
2. Complete your selected tutorial on step 1.
3. Do not watch and skip the **Nutrition Meter Unclocked** introduction modal. You can do so by pressing Tab.
4. Skip all tutorials.
5. Observe.

**Note:** I have to disconnect and reconnect to fix the issue.

#### Actual Result

https://user-images.githubusercontent.com/77248866/119492927-36f78c80-bd92-11eb-9af0-f2382708c93a.mp4

[Fresh game logs](https://github.com/StrangeLoopGames/EcoIssues/files/6539004/Player.log)

#### Expected Result
The game should behave accordingly when skipping tutorials.

**Comment by Ry4ndrew** [comment]
The issue reappears in 0.9.4 Staging-2022, but it was fixed in 0.9.4 Staging-2021.
