### ISSUE TITLE
NetPort.Disconnect stuck forever, can't reconnect

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2199]
I logged in w/ another client and got kicked via

` Eco.Shared!Eco.Shared.Networking.NetPort.Disconnect() Line 164	C#`
` Eco.Plugins!Eco.Plugins.Networking.Clients.Client.Disconnect(string reason) Line 175	C#`
`Eco.Plugins!Eco.Plugins.Networking.Clients.ClientManager.VerifyClient(Eco.Plugins.Networking.Clients.Client newClient) Line 146	C#`
` Eco.Plugins!Eco.Plugins.Networking.Clients.Client.Authorize(Eco.Shared.Authentication.LoginSession sessionInfo, string version) Line 194	C#`

Now it's stuck w/ sendPackets never clearing... probably need a timeout in that loop

**Comment by SeanAtr0n** [comment]
ClientManager.Update is also stuck on lock.clients, looks like VerifyClients locks and then sleeps forever

**Comment by metachronism** [comment]
I'll fix, any easy repro?

**Comment by SeanAtr0n** [comment]
Could wait for the expired token to kick you or trigger it manually using edit and continue... although I'm not sure what I did to make the sendPackets never get sent. Maybe my client was paused.
