### ISSUE TITLE
USER ISSUE: Fps prob

### ISSUE THREAD

**Issue by evos112** [StrangeLoopGames/EcoIssues#21998]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
in restarrt low fps "15 fp"

**Expected behavior:**
75 fps normal to high grafic

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods only 1 mods server its talllins

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@evos112 thank you for raising this issue,

please clarify here :
- Are you using macOS or Windows?
- Is your game running at 75 fps prior to this issue? 
- Is this happening to all game mode (private and other servers) or only happening to this one server?
- Was there any changes before you had this issue? (driver update etc..)

**Comment by evos112** [comment]
1. im Windows 10 pro
2. if start game its 15 fps,  
3. both single and private server only 15 fps
4. driver update all done 
5. sreenshot its https://steamcommunity.com/sharedfiles/filedetails/?id=2499211927
6. my pc "Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz , Ram 32,0 GB, Gtx 980 TI "6gb" "

**Comment by TwixterZ** [comment]
@evos112 thanks for your response, 

can you share me screenshot of your graphic setting? 
also your dxdiag

**Comment by evos112** [comment]
https://snipboard.io/CBFQMm.jpg
https://snipboard.io/tBR4lQ.jpg
screenshot game or ?

**Comment by evos112** [comment]
my game "eco" its grafic https://steamcommunity.com/sharedfiles/filedetails/?id=2499909960

**Comment by TwixterZ** [comment]
@evos112 thanks for the informations, I have similar PC setup to you and tried the same settings but did not face this issue. 

can you help to provide below informations:
- is any overlay enabled on your game? (steam, nvidia, discord, etc.)
- how is your PC usage when ECO is running? (CPU, GPU and Ram)

**Comment by evos112** [comment]
1, no have overlay at all
2. https://snipboard.io/sn8GoD.jpg
3. my internet its fiber 1000/1000

**Comment by TwixterZ** [comment]
@evos112 looking at your GPU usage per your screenshot, it looks like your graphic card is not fully utilized while ECO is running (GPU usage at 38%), while normally my GPU would be running at 90-100% when running ECO. 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/8ec6c10e-aab4-49c5-92c4-424a0d05d149)

**Comment by SlayksWood** [comment]
@evos112 try to change settings a little for example disable Antialaizing and Global Illumination, also try to reduce Shadows:
![image](https://user-images.githubusercontent.com/45708377/120758739-dc40fc00-c51a-11eb-9be3-2d19d7cab762.png)

**Comment by TwixterZ** [comment]
Hi @evos112 have you tried as what SlayksWood suggested, if so does this helped with your issue?

**Comment by TwixterZ** [comment]
Closing this issue due to no response received from last comment, 

thank you again @evos112 for raising this, if you find this issue happening again, do let us know by raising new issue.
