### ISSUE TITLE
Declunkify: Split-stack needs to disappear as soon as you start dragging

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21996]
Otherwise you get this clunkiness where it blocks places you may want to drop it:
![anim](https://user-images.githubusercontent.com/3536496/119745490-13d8e580-be43-11eb-9566-17fd576b0392.gif)

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 9.4 Staging 2020

![drag.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ca7121f0-7364-45d5-80db-8a75661ea739)
