### ISSUE TITLE
Animal movement and death totally broken = Hunting broken

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#220]
Animals warp rather than walk, float halfway down into terrain, don't play death animations on death. Makes it very lucky to shoot an animal enough times to kill it before it warps.

**Comment by stett** [comment]
Eco Animal Suppression Manifesto:

- [ ] Pass the Animal Teleportation Prohibition bill. They are not yet intelligent enough to use the technology wisely.
- [ ] Pass the Animal FTL Drive Prohibition bill. They have wrapped the around the world irresponsibly (and incorrectly), crashing through houses and causing general disarray.
- [ ] Correct animals with code disorders which cause them to be capable of only absurd, jerky motions. It is unpleasant for regular citizens to watch and makes killing them for sport more difficult.
- [ ] Put an end to the strange running-in-place fad with which the animals of the forest have become so taken. It's more idiotic than planking.
- [ ] Animals have been showing unnaturally low levels of anxiety - they should run in fear when players are nearby, not brazenly face up to those who encroach upon their space. We must break their spirits before it is too late.

**Comment by metachronism** [comment]
regarding FTL - you should just be able to use ClosestWrappedPosition on interpolated positions to interpolate to the "correct" one

**Comment by stett** [comment]
Hm... Teleportation still happens near world borders some times. Less frequent now, but still there.
