### ISSUE TITLE
Input/Output mode for chest/storage link

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2200]
It's required if you want to build a crafting chain.   
E.g.:   
Food preparation -> First Tier -> Second Tier -> .... -> Store (because we only want to sell the last one)

**Comment by MarjieAVolk** [comment]
Yep, been talking about this for a while

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2190
