### ISSUE TITLE
[0.9.4 staging-1993] Can't place Dirt with shovel in 3rd person view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22001]
Step to reproduce:
- go to 3rd person view take shovel and dig something:
![image](https://user-images.githubusercontent.com/45708377/119800568-931ef580-bee5-11eb-8706-fb9590f6fbb4.png)
- press PRM, nothing happens
- If suddenly you place it, jump and repeat

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

Closing as fixed.
