### ISSUE TITLE
[0.9.4 Staging-1993]Missing Audio and Unable to use Fishing Pole in 3rd person view

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22006]
Build: 0.9.4 Staging-1993

## Issue
The fishing pole has a couple of issues with this build when used in 3rd person view.
1. Audio sound effects (SFX) are missing.
2. Unable to use the Fishing pole tool.
3. Casting the fishing pole tool in 3rd person view then switching to the first-person view causes the fishing pole tool to appear disabled.

#### Unusable fishing pole tool and missing sound effects
1. Obtain a fishing pole tool.
2. Switch to 3rd person view camera.
3. Use the fishing pole tool by click-holding the left mouse button for a few seconds then let it go.
4. Observe.

https://user-images.githubusercontent.com/77248866/119826258-6b9e4c00-bf2a-11eb-9549-21b91adfa4e9.mp4

**Note:** While in 3rd person view, the animation when using the fishing pole works properly but the functionality of the fishing pole tool is rendered unusable.

#### Fishing pole gets disabled
1. Obtain a fishing pole tool.
2. Switch to 3rd person view camera.
3. Cast the fishing line by click-holding the left mouse button for a few seconds then let it go.
4. Switch to the first-person view.
5. Try to use the fishing pole tool.
6. Observe.

https://user-images.githubusercontent.com/77248866/119826639-cf287980-bf2a-11eb-8b1a-3ac5a6e77573.mp4

**Note:** I have to switch between tools to fix the fishing pole being disabled or unusable.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2020

Note: 
1. SFX is back in 3rd person view.
2. Fishing pole is still unusable in 3rd person view.
3. If you cast in the first person then switch to 3rd person, the fishing pole becomes disabled. Have to switch tool to make it usable again.

### Unusable Fishing Pole
1. Switch camera to 3rd person view.
2. Try to fish.
3. Observe.

### Fishing Pole Disabled
1. Switch camera to the first person view.
2. Cast the line to start fishing. (Press LMB)
3. Switch camera to 3rd person view.
4. Reel the fishing line. (Press LMB)
5. Try to fish again but this time in 3rd person view.
6. Observe.

**Comment by TwixterZ** [comment]
Fix tested on 9.4 Staging 2024

While fishing pole is now usable on 3rd person view, there is a delay in between animation to cast line and when line is "spawned" and going out to the water,

![fishing23](https://user-images.githubusercontent.com/78054747/122370471-aa577d00-cf91-11eb-9bed-2b8d9b2710d6.gif)

If player were to change view during that window, this would cancel the action and no line will go out. 
However, if player were to cast the line in first person and then change to third person, this will not happen.


https://user-images.githubusercontent.com/78054747/122371734-ab3cde80-cf92-11eb-811a-57815168019a.mov

Reeling audio does not stop immediately if player were to change quick slot selection (accidently or not) when reeling in the line.
Repro :
- Cast out line 
- Hold LMB to reel in
- Immediately switch to different quick slot
- Audio will continue playing for short while till end of loop.

**Comment by WeaselDog** [comment]
We have a separate issue for the animation delay

**Comment by TwixterZ** [comment]
Audio fix is observed and confirmed as of 0.9.4 Staging-2034
