### ISSUE TITLE
Declunkify: Land selection washed out again

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22013]
From grigori's PR video which I assume has your latest changes: 
![image](https://user-images.githubusercontent.com/3536496/119901907-5eb63400-befb-11eb-940c-91229f6ccd65.png)

**Comment by TwixterZ** [comment]
Fix observed on 9.4 Staging 2022 as below

![land highlight](https://user-images.githubusercontent.com/78054747/122193240-ebcf2600-cec6-11eb-9601-16f9d38b8d68.gif)
