### ISSUE TITLE
USER ISSUE: no cotton

### ISSUE THREAD

**Issue by ivory04** [StrangeLoopGames/EcoIssues#22014]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
have an exsisting world, look for cotton. only see potential cotton but dont actually find cotton	

**Expected behavior:**
i should be able to find cotton

**Actual behavior:**
there is no cotton in my world. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. most updated version. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by jakeasmith** [comment]
Hi @ivory04, 

Since you mentioned this is an existing world I want to make sure you saw this info from [the 9.3 release notes](https://store.steampowered.com/news/app/382310/view/5078347424863181062):

> IMPORTANT NOTE: Cotton will not spawn on already existing worlds, that means that you either need to spawn in cotton seeds via the /give command and plant them or need to start a new world if you want to use cotton. Cotton being absent does not affect progression, though.

**Comment by Daniel-Magulado** [comment]
Hello @ivory04,

Thank you for writing a report about this. However, this is mentioned in our [9.3 Release notes](https://store.steampowered.com/news/app/382310/view/5078347424863181062).

Closing this ticket.
