### ISSUE TITLE
Port Confusion on docker-compose

### ISSUE THREAD

**Issue by ceriath** [StrangeLoopGames/EcoIssues#22015]
Dear Eco-Team,

today set up an eco server via docker which worked completely fine until i was trying to connect. After some troubleshooting i found out, that the example docker-compose.yml shown on https://hub.docker.com/r/strangeloopgames/eco-game-server has the protocols for the two ports confused. 3000 should be udp and 3001 tcp, then it works perfectly well :)

Kind regards,
Ceriath

**Comment by redwyre** [comment]
Yes, you are right! I have fixed it. Thanks
