### ISSUE TITLE
Change RCon to not be a user

### ISSUE THREAD

**Issue by thetestgame** [StrangeLoopGames/EcoIssues#22017]
This is needed to solve https://github.com/StrangeLoopGames/EcoIssues/issues/21791. This issue is a lot deeper rooted and is needed to hide other internal API users not just RCON.

**Comment by johnkslg** [comment]
Dont just hide the user, it will still get picked up in zillions of calculations. Make rcon not use User class at all.

**Comment by johnkslg** [comment]
Some notes on how to do this:
- Make a IChatCommander that RCON and User classes derive. It should have functions for responding with a single message (or just return a string in the chat command)
- Make chat command system accept either a user, or IChatCommander.  
- Chat commands that need access from RCon can be updated to accept IChatCommander

There are lots of commands we dont want RCON calling anyway, and this will have the bonus of removing them from being accesible. For example anything that requires a position will currently just break if called by RCON.  The functions shouldnt even be avaialble.
