### ISSUE TITLE
[0.9.4 Staging-1993] Issues with Drill tools in 3rd person view

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22010]
Build: 0.9.4 Staging-1993

## Issue
There are a couple of issues when using any drilling tool such as Iron Rock Drill and Modern Rock Drill in 3rd person view.
1. Both tools are not working in 3rd person view.
2. Both tools have no sound effects and are missing audio.
3. Modern Rock Drill ends up using a different animation when switching to it while hold-clicking the left mouse button.
4. In number 3, it causes the Modern Rock Drill to work but in a very odd way.

To reproduce number 4:
1. Switch to 3rd person view.
2. Obtain a Modern Rock Drill and then set it to one of the boxes in the active toolbar.
3. Select another tool (any) on the active toolbar and hold-click the left mouse button to use it.
4. While hold-clicking the left mouse button, switch to the Modern Rock Drill.
5. Observe.

#### Actual Result
I have included all issues stated above in the video below.

https://user-images.githubusercontent.com/77248866/119837961-9b068600-bf35-11eb-84f2-4ab1d0e46877.mp4

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008

1. Both tools are now working in 3rd person view.
2. Both tools now have SFX.

However, the Modern Rock Drill still uses the hammering animation when switching to it.
Additionally, this also caused a new issue which causes both tools to loop the prospecting action as long as you press-hold the left mouse button. This was not the case in 0.9.3.5 Release-231.

Comparison: 
0.9.3.5 Release-231 vs 0.9.4 Staging-2008
In release, drilling stops after one run of prospecting but it loops in Staging.
In release, the animation is not affected when switching to Modern Rock Drill but not for Staging.


https://user-images.githubusercontent.com/77248866/120846696-15be4980-c5a5-11eb-892b-361747a2cea3.mp4

**Comment by SlayksWood** [comment]
another case: https://drive.google.com/file/d/1Oc5QMynduYqTDdevZDZwAezvtkkdCP2e/view?usp=sharing

**Comment by Quadbro** [comment]
@Daniel-Magulado All tools are using 1 take animation. This is animation problem for art team, other issues are fixed.

**Comment by SlayksWood** [comment]
check after fixing this one #22232

**Comment by Daniel-Magulado** [comment]
Created a separate issue for the animation.

Tested on 0.9.4 Staging-2026.
Found a couple of issues but will create a separate issue as it does not require to be in 3rd person view anymore.

Closing as fixed.
