### ISSUE TITLE
USER ISSUE: Water issues

### ISSUE THREAD

**Issue by TheCowMooooo** [StrangeLoopGames/EcoIssues#22026]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Not sure how to reproduce, it is a random thing.

**Expected behavior:**
Not had a crack in the water

**Actual behavior:**
Has a crack in the water that makes it look like a corner is being lifted up

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/58637685/120085866-84287680-c090-11eb-9587-4437453f0b3d.png)

**Comment by Daniel-Magulado** [comment]
Hello @TheCowMooooo,

Thank you for writing a report about this.
We are currently aware of this issue.
I'll be merging this report to an early existing one.
Merging to #12080
