### ISSUE TITLE
White block issue

### ISSUE THREAD

**Issue by ShadedFlash** [StrangeLoopGames/EcoIssues#22027]
Having an issue with mysterious white blocks that cant be erased, smited, picked up or otherwise.
![9c0015d65e7cc4dcb35084e1d6fd14c1](https://user-images.githubusercontent.com/85042649/120088099-85bb6400-c0bb-11eb-96fd-117eec444966.jpg)
![85c6bac0ba8a849998cd133d89fbb192](https://user-images.githubusercontent.com/85042649/120088103-9370e980-c0bb-11eb-8ba5-a68682c0f553.jpg)

**Comment by Daniel-Magulado** [comment]
Hi @ShadedFlash,

Thank you for writing a report about this issue.
Please provide us with your game logs, complete pc specification, and the version of Eco where you encountered this issue. This will allow us to look into this further.
Please also provide reproduction steps or procedures on how or where did you first encounter this issue.

**Comment by ShadedFlash** [comment]
Do you want the pc specifications of my computer or the host server? It was visible to all users on the server. 

Eco version was the current version
[log_210529010014.log](https://github.com/StrangeLoopGames/EcoIssues/files/6572177/log_210529010014.log)

**Comment by SlayksWood** [comment]
@ShadedFlash Can you provide save files to investigate it? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
Also have a question do you have mods installed or use some game commands maybe?

**Comment by TwixterZ** [comment]
Hi @ShadedFlash, can you share your save file and answer question asked by SlayksWood above?

**Comment by TwixterZ** [comment]
Closing issue due to lack of response from user
