### ISSUE TITLE
Editing constitution font color

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#22024]
It's already hard to read the italic old writing font, but add this color on edit on top and your head explodes:
![image](https://user-images.githubusercontent.com/25908592/120084424-4c412380-c0d0-11eb-9c3d-7084a71258a7.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1995.


This is actually the case for all civic UIs such as the constitution, amendments, court, demographics, government, and elections.


![image](https://user-images.githubusercontent.com/77248866/120100782-3174ba80-c175-11eb-912e-6736f8dda278.png)
