### ISSUE TITLE
[0.9.4 Staging-1995] Crafting time is worded and not working

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22029]
Build: 0.9.4 Staging-1995

## Issue
The time shown for crafting items in crafting tables is worded and it is also not working. It does not show a numerical value.

#### Reproduction Steps
1. Interact with any crafting table.

#### Actual Result
![image](https://user-images.githubusercontent.com/77248866/120096386-bce25180-c15d-11eb-836a-efc7c9b3b39d.png)

The same issue can also be observed with the sleep timer, welcome message for day timer, and meteor timer.
![image](https://user-images.githubusercontent.com/77248866/120157466-a56e9b80-c225-11eb-8f8a-1e718e4ecb0a.png)

![image](https://user-images.githubusercontent.com/77248866/120099943-c5905300-c170-11eb-8537-54b39a5a6582.png)

**Comment by madpingui** [comment]
Duplicated, closing this one https://github.com/StrangeLoopGames/EcoIssues/issues/22042
