### ISSUE TITLE
[0.9.3.5] Chat messages disappear after a bit

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22032]
After playing on White Tiger for a bit I noticed my chat messages started to disappear. I would talk to someone, see their message pop up, and then it would vanish. Someone mentioned it might be a memory leak that requires a restart. After a restart I could see the various messages that were sent.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6566024/Player.log)

**Comment by IcedForge** [comment]
Thank you for your report, will attach it to the chat upgrade epic

**Comment by WeaselDog** [comment]
We have a chat remake coming in 9.5 that will address this.
