### ISSUE TITLE
[0.9.4 Staging-1995] Missing icon for MediumLeatherCarcass Tag

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22036]
Build: 0.9.4 Staging-1995

## Issue
The **MediumLeatherCarcass Tag** has no icon. It uses the default gear icon.

#### Screenshot
![image](https://user-images.githubusercontent.com/77248866/120111792-ede67480-c1a5-11eb-8098-39b19d2e915b.png)

**Comment by WeaselDog** [comment]
Fixed in SVN

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.

Closing as fixed.
