### ISSUE TITLE
[0.9.4 Staging-1997] Avatar spawns issue

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22047]
Build: 0.9.4 Staging-1997

## Issue
I've started to notice, after the fix for #18927, starting a new game has a decent chance that the avatar will spawn facing blocks. This should not be happening. Starting a new game should always spawn the avatar in a place where it is free of any visual blockage or limits the movement of the camera. (Excluding ground)

#### Reproduction Steps
The reproduction step is fairly simple, all you have to do is start a new game.

#### Actual Result
I've tested it and 4 out of 20 tries, my avatar spawned facing blocks.
![image](https://user-images.githubusercontent.com/77248866/120197529-a0c0dc00-c253-11eb-8719-fde947927ce3.png)

https://user-images.githubusercontent.com/77248866/120197657-c5b54f00-c253-11eb-958d-38c459d359cf.mp4

![image](https://user-images.githubusercontent.com/77248866/120889827-975bb900-c631-11eb-806f-1088fc484a68.png)

**Comment by SlayksWood** [comment]
#12625
