### ISSUE TITLE
[0.9.3.5]Property does not allow authorization of demographics

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#22049]
When authorizing an entire demographic to a property (admin demographic in our case), the demographic still does not have permission to place world objects within the property.
![Screenshot (39)](https://user-images.githubusercontent.com/80280848/120268384-b34b0d80-c273-11eb-9b59-5ebc6b95a0bf.png)
![Screenshot (40)](https://user-images.githubusercontent.com/80280848/120268385-b3e3a400-c273-11eb-9d29-64bc0c940d8c.png)

**Comment by TwixterZ** [comment]
Closing this issue as duplicate with https://github.com/StrangeLoopGames/EcoIssues/issues/21587

@ChickenHacker1 Please follow-up on this issue on link above.
