### ISSUE TITLE
[0.9.4 staging-1997] Shorts are broken

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22042]
In craft stations:
![image](https://user-images.githubusercontent.com/45708377/120169953-24091000-c209-11eb-8ca5-b69b234e71a3.png)
I guess it was broken here https://github.com/StrangeLoopGames/Eco/issues/8528
And I think in all UIs where this was used there will be a problem.

**Comment by SlayksWood** [comment]
check this one https://github.com/StrangeLoopGames/Eco/issues/8528 after fixing.

**Comment by SlayksWood** [comment]
![Uploading image.png…]()

**Comment by TwixterZ** [comment]
Fix Tested on 9.4 Staging 2010

Sleeping Timer : 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/6d6aea5c-7b68-4e73-aa0b-22fc3affbcd1)

Benches :
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/9f5fe86e-5a5b-4cac-916c-6609b9631f9e)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/70a90df1-46b4-4f7e-9dad-f539572d5d81)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/fdb9a92b-76c2-4df2-b347-8d37df728f48)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/d45b0e89-e9e2-45f1-90a6-02c942e2e30d)

**Comment by SlayksWood** [comment]
distance still has a problem, create a new issue for that #22145
