### ISSUE TITLE
[0.9.4 staging-1997] Impossible to continue actions if you re-hold LMB on the first animation

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22043]
Step to reproduce:
- take any tool (I used stone axe).
- press and release LMB to start animation
- hold LMB while the animation of the first swing is going
- Expected behavior: you keep chopping
- Actual behavior: you stop chopping. You need to rehold LMB after first animation.

**Comment by Daniel-Magulado** [comment]
Can confirm it's happening. The action gets halted despite pressing LMB. You have to repress it again.
