### ISSUE TITLE
[0.9.4.0 staging] Move Small Wood Cart recipe to Logging specialty

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#22050]
Prior to 9.0, the Small Wood Cart was crafted by Hewing which was a starting specialty requiring no research. This is now locked behind the Carpentry specialty which requires research. We want to restore the Small Wood Cart being a recipe tied to a true starting specialty. This is especially important for smaller servers. The most logical way to do this is to give it to Logging, who will now sell Logs, Hewn Logs, and Small Wood Carts.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/120433518-feecdc80-c383-11eb-9a3f-154bfc76c37d.png)
