### ISSUE TITLE
USER ISSUE: River Sand below aquaduct

### ISSUE THREAD

**Issue by TheRealBrainbug** [StrangeLoopGames/EcoIssues#22053]
![riversand](https://user-images.githubusercontent.com/39854299/120385727-14ccb400-c328-11eb-8745-87caf5dbd4a5.png)
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Build an aqueduct over dirt.

**Expected behavior:**
It should have no effect on the dirt below.

**Actual behavior:**
Instead the Dirt below turned into River Sand.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @TheRealBrainbug,

Thank you for writing a report about this.
We are currently aware of this issue and I'll be merging this report to #19606.

Thank you.
