### ISSUE TITLE
Glass in FlatSteel double window blocks float above when further away

### ISSUE THREAD

**Issue by Hottentotten** [StrangeLoopGames/EcoIssues#22052]
![image](https://user-images.githubusercontent.com/33907318/120355969-1be1cb00-c304-11eb-9ba3-d2e165a75f4f.png)
![Screenshot (33)_LI](https://user-images.githubusercontent.com/33907318/120356572-c5c15780-c304-11eb-8ee9-d297370c3fb4.jpg)

The closer you get to them the more the glass moves into place
Important: This only happens with FlatSteel DOUBLE window blocks. As you can see on the screenshot there are also brick window blocks that behave normally.

**Comment by Sekor2600** [comment]
fixed staging

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.

Closing as fixed.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/21f34a09-fae9-45fc-a78d-17f899c33941)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004.

Closing as fixed.
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/21f34a09-fae9-45fc-a78d-17f899c33941)
