### ISSUE TITLE
[0.9.4 Staging-2003] Objective Window UI bug

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#22058]
Pressing "O" (objective window shortcut) would show objective while World Progress tab selected.

![43c3f8df683d0f862dc9da46a6a4841f.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/a1257820-4a93-497c-9105-89c910fa95c8)

Expected Behavior : showing objectives window with objective tab selected OR showing world progress with world progress tab selected.

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/120438805-7a518c80-c38a-11eb-8f3d-1cd42e868f95.png)
should be:
![image](https://user-images.githubusercontent.com/45708377/120438837-82113100-c38a-11eb-8db7-77dcd0413479.png)
Also add for a while saving the selected tab
