### ISSUE TITLE
[0.9.4.0 staging] Vehicle recipes do not require skilled labor

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#22051]
Currently all the vehicle recipes in staging do not require skilled labor, only the skill to be researched. This is a result of the tech templates changing.

**Comment by SlayksWood** [comment]
fixed:
![image](https://user-images.githubusercontent.com/45708377/120433586-13c97000-c384-11eb-8519-1b45676fe266.png)
![image](https://user-images.githubusercontent.com/45708377/120433900-71f65300-c384-11eb-8dd8-ff1e821478d7.png)
![image](https://user-images.githubusercontent.com/45708377/120433994-905c4e80-c384-11eb-8f1d-3495d4512e70.png)
![image](https://user-images.githubusercontent.com/45708377/120434026-9b16e380-c384-11eb-8c93-7071a4243467.png)
