### ISSUE TITLE
Declunkify: Better effects when picking up blocks with vehicles

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22066]
https://streamable.com/me1n9t
They just disappear right now. 
(ignore the acrobatics in that video)

**Comment by z-73** [comment]
Clay was missing effects so I created some based on the dirt ones and added them to the block set. Committed on SVN Rev. 8422
Will talk to @keegan-o about if we need an overhaul for these or specific vehicle effects.
