### ISSUE TITLE
[0.9.4 Staging-2004] Repair tooltip everywhere

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22069]
Build: 0.9.4 Staging-2004

## Issue
The Computer Lab's activate button shows a non-related tooltip. Hovering your mouse icon over the **Activate** button shows a different tooltip and it's about tool repair.

#### Reproduction Steps
1. Either craft the computer lab or use /give computer lab command.
2. Place it and interact with it.
3. Observe the Activate button

#### Actual Result
The **Activate** button shows a different tooltip.
![image](https://user-images.githubusercontent.com/77248866/120534321-4458ea80-c414-11eb-951c-deb4ba15eee7.png)

**Comment by SlayksWood** [comment]
![Uploading image.png…]()

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/120968953-3daed800-c772-11eb-8475-1bd807cd9a0c.png)
![image](https://user-images.githubusercontent.com/45708377/120968973-430c2280-c772-11eb-8bec-b5f0dc146964.png)
![image](https://user-images.githubusercontent.com/45708377/120969004-50291180-c772-11eb-9bc7-02b8a12a7065.png)

**Comment by SlayksWood** [comment]
Need to check max count of buttons that looks like this one:
![image](https://user-images.githubusercontent.com/45708377/120969116-6e8f0d00-c772-11eb-9a85-092b2b328c61.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2026.

Checked all paperbutton on all economy table and it appears to be fixed. Including Computer Lab.
Closing as fixed.
