### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Aedollon** [StrangeLoopGames/EcoIssues#22070]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Aedollon,

Thank you for writing a report about this.
For us to be able to assist you, kindly provide us with more information about this issue.

Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Additionally, kindly answer the following questions:
1. Is this the first time you're playing Eco?
2. Are you trying to connect to a local server, public server, or to one of our official servers?
3. What things have you done before you encounter this issue? Are you starting a game? Have made changes with the game settings? 
4. Please provide us with a speed test of your Internet speed.
5. Please provide us with complete details of your computer's specifications including the operating system and its version.

This will help us troubleshoot the problem and narrow the possible causes.

Thank you.

**Comment by Ry4ndrew** [comment]
Closing issue due to lack of response.

If this issue happens again, kindly raise a new issue. Thanks.
