### ISSUE TITLE
USER ISSUE: Animals lagging around while running

### ISSUE THREAD

**Issue by Jkrazor** [StrangeLoopGames/EcoIssues#22071]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. Find animal
2. Have an animal notice you
3. Watch animal run

**Expected behavior:**
They should move around smoothly and you should be able to hit them with arrows.

**Actual behavior:**
Instead, they vanish and reappear in different places and don't seem to be in the place that it looks like they're in.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, unknown.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Jkrazor Thanks for raising this issue to us, may I know your ping to the server when you notice this? 

Does lag only effecting animals movement, or do you notice any other?

**Comment by Jkrazor** [comment]
> @Jkrazor Thanks for raising this issue to us, may I know your ping to the server when you notice this?
> 
> Does lag only effecting animals movement, or do you notice any other?

My ping sits around 40 or 50, and it only seems to affect the animal movement.

**Comment by Daniel-Magulado** [comment]
Merging with #21838
