### ISSUE TITLE
USER ISSUE: Animals Vanishing

### ISSUE THREAD

**Issue by MSKI8877** [StrangeLoopGames/EcoIssues#22072]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Fire at or scare any animal until they begin to run

**Expected behavior:**
animal should have ran smoothly down the beach or general area

**Actual behavior:**
They'll run around, but if you're near them, they'll vanish for a second, then reappear a few feet further in the direction they were running as if they went through a portal

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
will merge this issue with another one reported earlier @ https://github.com/StrangeLoopGames/EcoIssues/issues/22071

kindly refer to above issue for updates
