### ISSUE TITLE
Declunkify: Double-team on harvesting effects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22088]
https://media.discordapp.net/attachments/849445634909667349/850179411559055370/2021_06_04_10_58_12.gif
Need to help Toby with getting things setup for harvest animation, including:
- Supplying the position and rotation and scale of the plant to the effect system
- Making the effect happen instantly, via client-side prediction, when the scythe contacts the plant. Right now it works off of serverr message and is poppy and laggy (the gif shows a concept of what it could look like with proper timing)
- For a scythe on a bulk of grass: it would be awesome if the effect could trigger linearly as the scythe swings, so nearby grass triggers it effect when the scythe passes it before far grass does
- Whatever else Toby needs. Get him setup to do all the harvesting effects for everything and make them amazing.

**Comment by z-73** [comment]
Some additional requirements as mentioned to @Quadbro in PM,

- When plants are harvested and they are dead, they still play the harvest effect and they should really play the delete effect and have the material parameters passed to the material on the effect
- Plants that are picked eg, tomatoes, don't play any effect currently. Should play the harvest effect.

**Comment by Quadbro** [comment]
TODO: Check double effect spawn too

**Comment by z-73** [comment]
I've added some notes in the MapConfig changes. Currently, it's checking if the plant is fully grown rather than if it's above its PickableAtPercent parameter on the species.
