### ISSUE TITLE
Need collision on tree debris blocks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2208]

**Comment by MarjieAVolk** [comment]
I thought this was deliberately removed

**Comment by johnkslg** [comment]
I believe it was removed because it was a performance problem, but gameplay wise we'll need to support it, so it's a bug. Can push to beta if we have to.

**Comment by MarjieAVolk** [comment]
I think it was removed for gameplay reasons, because its crazy hitbox was annoying.

**Comment by SeanAtr0n** [comment]
We mainly can't have trees collide with it... it can launch felled trees into orbit when it gets generated

**Comment by MarjieAVolk** [comment]
I just heard Keegan complaining about how annoying it was a lot, if I recall.  Not being able to walk through it and stuff

**Comment by metachronism** [comment]
yeah these cant have collsion, will cause trees to pop up explode into the air
