### ISSUE TITLE
[0.9.4 Staging-2008] Moonwalking with Hand Plow

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22094]
Build: 0.9.4 Stating-2008

## Issue
If you're holding a Hand Plow tool and you try to move backward, the avatar doesn't walk backward instead it moonwalks.

https://user-images.githubusercontent.com/77248866/120836256-f240d200-c597-11eb-8125-515dcea67fb5.mp4

**Comment by Quadbro** [comment]
Should be fixed in current staging, forgot to add to to pr.
