### ISSUE TITLE
[0.9.3.5 Release-231 / 0.9.4 Staging-2008] Migration: Map vanishes/disappears with Migration to 0.9.4 Staging-2008

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22096]
Build: 0.9.3.5 Release-231 to 0.9.4 Staging-2008 (Migration)

## Issue
Migrating a game created with version 0.9.3.5 Release-231 to 0.9.4 Staging-2008 causes the map in mini-map as well as in Map UI to disappear/vanish.

Your mini-map corner is left with this:
![image](https://user-images.githubusercontent.com/77248866/120847798-8dd93f00-c5a6-11eb-82d7-0f833bc73570.png)

Reconnecting does not fix the issue.

Video Recording:

https://user-images.githubusercontent.com/77248866/120848400-53bc6d00-c5a7-11eb-9366-23a4d5e3cdb9.mp4

Reproduction Steps
1. Create a new game with version 0.9.3.5 Release-231.
2. Make a small progression. (Not necessary but something to solidify the world for migration)
3. Migrate world to 0.9.4 Staging-2008.
4. Observe mini-map.

**Comment by SlayksWood** [comment]
I have this problem on my server:
https://drive.google.com/file/d/1miK3uMZlGbwUH_AyGvr1BfRGcFwp3g4R/view?usp=sharing
