### ISSUE TITLE
[0.9.4 staging-2008] Glitch with placing/ pickupping objects/blocks on RMB/LMB

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22090]
Step to reproduce:
- take any hammer and any blocks(stone hammer + Bricks)
- select Point and try to place 1 Block. You will place 4 times
video: https://drive.google.com/file/d/1AbH1IDU73BQTZQDpdGDZhPdDU3i2oVh5/view?usp=sharing
- take 99 chests, try to place 1. You place 1 and have notification that you can't place 4 more here:
![image](https://user-images.githubusercontent.com/45708377/120802795-82a4f580-c54b-11eb-9481-30e2a452ffbc.png)

**Comment by Daniel-Magulado** [comment]
Adding:

The same issue can also be observed when interacting with items that can be turned ON/OFF.
For example, if you try to turn OFF a modern street light, it flickers like it's been turned OFF and ON and OFF again in a split second.


https://user-images.githubusercontent.com/77248866/120823310-e221f600-c589-11eb-99da-6f243afd055f.mp4

**Comment by Daniel-Magulado** [comment]
The issue has a greater effect on other tools such as sickle that tries to harvest multiple times as reported here #22104 as well as picking up construction materials with a hammer tends to pickup multiple at one click.

![image](https://user-images.githubusercontent.com/77248866/121139063-ee989e00-c86a-11eb-8a0d-f7d1d5fcc03f.png)


![image](https://user-images.githubusercontent.com/77248866/121139076-f2c4bb80-c86a-11eb-8189-78adc86f5df9.png)

**Comment by Quadbro** [comment]
Original issue described by Kirill is fixed already at the end of prev sprint. The issue with phantom triggers can't be reproduced on my side, can qa confirm its still reproducible? (this should be fixed too by that changes, but anyways)

**Comment by Quadbro** [comment]
Adding this issue tp PR to ensure in will be checked

**Comment by Quadbro** [comment]
Just had a call with Ice Forge and we was able to repro this issue on playtest, working on it to fix

**Comment by WeaselDog** [comment]
Fixed on playtest
