### ISSUE TITLE
[0.9.3.5] Debug.bindings.h crash?

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22105]
I was testing some stuff on my offline server, then tried logging into White Tiger and got this crash:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6601693/Player.log)

**Comment by ThePiachu** [comment]
[Crash_2021-06-05_000508574.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6601700/Crash_2021-06-05_000508574.zip)

**Comment by TwixterZ** [comment]
Hi @ThePiachu, apologies for our late respond on this issue, do you still facing this in 0.9.3.6 version?

**Comment by ThePiachu** [comment]
I don't think I ran into this issue since.

**Comment by TwixterZ** [comment]
Thanks for the update, I will proceed to close this issue for now, if such issue arises again do let us know =)
