### ISSUE TITLE
Declunkify: unify size and settings of all text in the game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22101]
- Titles should be 22 point, and 'SC' setting (small caps)
- Text should be 18 point
- No bolds

Example:
![image](https://user-images.githubusercontent.com/3536496/120871226-e4fff500-c54f-11eb-86f4-d3580f21a173.png)

**Comment by WeaselDog** [comment]
Moved to ClickUp
