### ISSUE TITLE
Declunkify: tutorials are fading in as they arrive, should not be the case. 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22100]
![anim](https://user-images.githubusercontent.com/3536496/120870545-0a8bff00-c54e-11eb-98ed-c59eac544282.gif)

**Comment by TwixterZ** [comment]
Confirmed issue introduced in staging, a regression as this is not the case in release

**Comment by madpingui** [comment]
It should be solved now thanks to this PR https://github.com/StrangeLoopGames/Eco/pull/8715

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2021.

Closing as fixed.
