### ISSUE TITLE
Lines rendering on minimap are back again

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22122]
![image](https://user-images.githubusercontent.com/3536496/120908125-265dd680-c61c-11eb-8327-cae0fcb9faea.png)
- [ ] Fix, again
- [ ] Find out why it broke
- [ ] Tell that person they have done a bad bad thing
- [ ] Overfix it so it can never break again

**Comment by mirasrael** [comment]
may be related to anti-aliasing or lightning changes?

**Comment by johnkslg** [comment]
![anim](https://user-images.githubusercontent.com/3536496/122522618-05599600-cfcb-11eb-9c0a-a54ba360d752.gif)
Looks like its something to do with alpha, you can see the game behind those lines.
