### ISSUE TITLE
Declunkify: tooltips lock too easy

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22125]
If youre dragging the mouse it shouldnt advance the counter. This makes it lock tooltips as youre moving around the cursor slowly. 
![anim](https://user-images.githubusercontent.com/3536496/120908970-b56eec80-c624-11eb-99d6-283c3c97c58d.gif)

**Comment by TwixterZ** [comment]
Fix observed and confirmed as of 0.9.5 Develop-306
 
![tooltip2.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f1db38ee-a9ac-4ea7-b5f5-d7c506ba4c80)
