### ISSUE TITLE
Stopsigns are stackable but road signs are not

### ISSUE THREAD

**Issue by Hottentotten** [StrangeLoopGames/EcoIssues#22134]
Shouldn't be both stackable?
This way road signs fill up a lot of storage space.
![image](https://user-images.githubusercontent.com/33907318/120934437-a5c3d680-c6fe-11eb-98f5-638a95f6d196.png)

**Comment by WeaselDog** [comment]
merged with https://github.com/StrangeLoopGames/EcoIssues/issues/18753
