### ISSUE TITLE
[9.4 Staging 2009] Block type text overlap

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#22130]
There is a line overlapping with block type text when using any hammer,

Repro:
- Hold a hammer with any material
- Hold "F" to change block shape / fill types 
- Observe block shape text

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/e04dc311-aac8-4934-80c8-51d55d91d182)
_Zoomed in view :_
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ca8a7987-d8f4-48df-b471-4d278a50e3cc)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2027.

Closing as fixed.
