### ISSUE TITLE
[9.3.5 - build 231] copying a law with the copy button allows direct editing of existing law through draft

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22133]
Steps to reproduce:
1. have a law that mentions a district e.g. "Altaica" here
![grafik](https://user-images.githubusercontent.com/34270661/120932816-a442e000-c6f7-11eb-9fb8-5c0bf50ed7ce.png)
2. copy this law into another law using the middle button ("create from copy" next to "view" and "remove" when hovering over the law draft)
![grafik](https://user-images.githubusercontent.com/34270661/120932834-c8062600-c6f7-11eb-90ad-57a64057167d.png)
3. change the district mention in the NEW law to anything. You do NOT need to pass it as election, it can stay as a draft
![grafik](https://user-images.githubusercontent.com/34270661/120932885-eb30d580-c6f7-11eb-8d42-6ec6069af942.png)
Still a draft:
![grafik](https://user-images.githubusercontent.com/34270661/120932914-056ab380-c6f8-11eb-9c23-3d438b987eab.png)
4. the existing OLD law that was copied has the changes of the draft applied even though the draft is for another law
![grafik](https://user-images.githubusercontent.com/34270661/120932924-10bddf00-c6f8-11eb-92d0-907709c2c8e5.png)

**Comment by TwixterZ** [comment]
Fix Tested and confirmed as of 9.3.6 Release 234
