### ISSUE TITLE
Typing in a comma instead of a dot in the shop price crashes the game.

### ISSUE THREAD

**Issue by CrazyIvanTR** [StrangeLoopGames/EcoIssues#22148]
The issue has a simple test step. Set up any shop, type in "0,1" instead of "0.1" to the price for buying an item. It should be reproducible with any item / currency combo but I'm not sure. I was using Coins in the server and I was setting the price of a Ceiba Log for buying.

I don't have the log for when I set the price, but I have the log from when I logged in later to edit the price, which ended up in a crash again.
[Price-Edit-Crash.log](https://github.com/StrangeLoopGames/EcoIssues/files/6608424/Price-Edit-Crash.log)

I was able to outright remove the item and it ended up modifying the price of the item above it to 1. 

Version: 0.9.3.5 release 231

slgid: slg202595

**Comment by CrazyIvanTR** [comment]
Well, it's not happening now. Not sure what the issue was. Something to do with mixed localizations maybe?

**Comment by CrazyIvanTR** [comment]
I realize that while I was trying to type in the price, I might have put some strange unseen characters in there. Those could have been the reason. I normally use the dot to put the price in but at some other computer with Turkish localization, those characters seem to have not put anything in there. So, that's why I was surprised by the comma working now.

**Comment by Daniel-Magulado** [comment]
Hi @CrazyIvanTR,

Thank you for writing a report. Based on the game log you've provided, it seems that your graphics card is crashing which results in the game crashing as well.
Kindly provide us the following information as this will help to further investigate the issue:
1. Complete PC specification.
2. Version of the operating system.
3. If possible, try to repeat the issue until the game crashes and upload the game logs to us.
4. If possible, a recorded video would be helpful as well.

I'd also like to take this opportunity to provide the minimum system requirements of Eco:
OS: Windows 10
Processor: AMD Ryzen 5 1500X 3.5 GHz Quad-Core or Intel i5-6500 3.2 GHz Quad-Core or similar
Memory: 8 GB RAM
Graphics: AMD Radeon HD 7850 or NVIDIA GeForce GT 640 or Intel HD Graphics 540 or similar (2 GB memory recommended)
DirectX: Version 11
Network: Broadband Internet connection
Storage: 4 GB available space

Additionally, there is an error on the game log with code 887a0005. If you have a system that's capable enough than our minimum system requirements, it could possibly be the graphics driver. If you have an NVIDIA or AMD graphics card, we recommend reverting back to an older driver that work and you did not encounte this issue before.

**Comment by CrazyIvanTR** [comment]
Checked this again on a few different computers, it must have been the low system.
