### ISSUE TITLE
[0.9.3.5] Powered Cart text floats in the distance

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22142]
Since we had Powered Carts on for so long on White Tiger, I noticed the text tends to float if you are far enough from them:

![image](https://user-images.githubusercontent.com/964559/120943304-fe857600-c6e2-11eb-865f-65d8226c1f4a.png)

![image](https://user-images.githubusercontent.com/964559/120943313-03e2c080-c6e3-11eb-88aa-599f857f7ce9.png)

![image](https://user-images.githubusercontent.com/964559/120943317-0a713800-c6e3-11eb-814f-473df255fce5.png)

Which is similar to #18928 .

**Comment by SlayksWood** [comment]
dup #5602
