### ISSUE TITLE
[0.9.3.5] Some of Steam Truck's tires is on backwards

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22141]
While I was driving a Steam Truck, I noticed one of its tires is facing the opposite direction than the rest:

![image](https://user-images.githubusercontent.com/964559/120943207-43f57380-c6e2-11eb-8499-a6fbe5667f17.png)

However, from what little googling I did, I think the 3 tires are on backwards based on their patterns, at least in comparison to:

![image](https://user-images.githubusercontent.com/964559/120943245-90d94a00-c6e2-11eb-9e72-0e8440ae9bb5.png)

![image](https://user-images.githubusercontent.com/964559/120943250-9b93df00-c6e2-11eb-8768-3f2f73d7825e.png)

So something needs fixing for sure, just not sure which part ;).

**Comment by SlayksWood** [comment]
Interesting... You need to start drive the tractor to have this bug.
Just place tractor:
![image](https://user-images.githubusercontent.com/45708377/120972042-fd515900-c775-11eb-9773-7cd36f831fb2.png)
Start to drive:
![image](https://user-images.githubusercontent.com/45708377/120972061-03473a00-c776-11eb-84b6-c4ccebd47c41.png)
when you leave you still have this problem:
![image](https://user-images.githubusercontent.com/45708377/120972213-2f62bb00-c776-11eb-92ad-dbbf55ecb429.png)
3 wheels has wrong direction now.

**Comment by keegan-o** [comment]
If it's correct before using, and then the vehicle code flips them, it's a code issue to be resolved (if a programmer determines some update to FBX is needed to fix, they can let us know, but flipping them in FBX as is would just result in the opposite wheels being broken on driving)
