### ISSUE TITLE
[0.9.2.4 beta release-231] Pressing enter on "Loading World" shows chat UI on top of loading screen

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22147]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/a86c1e27-76ab-4515-9268-00bc0f8fcb15)

**Comment by SlayksWood** [comment]
Checked in 0.9.4 staging-2021 still an issue:
![image](https://user-images.githubusercontent.com/45708377/122002896-fef4cf80-cdba-11eb-9bf8-d81b106b9a5b.png)

**Comment by madpingui** [comment]
just tested in staging editor branch, and last staging steam version and i spammed enter and / neither of them oppened up the chat UI.

**Comment by Daniel-Magulado** [comment]
@madpingui 

I also tested on 9.4 Staging-2021 (Steam) and V0.6.4.0-alpha (Develop-Steam). I am able to reproduce on both builds.

Attaching a video.

To reproduce:
1. Start a new game.
2. During the world loading window, wait for the phase where the loading sentence is saying **Loading world** with a percentage number. **Loading world 28%** etc...
3. Press Enter
4. Observe.

Staging Recording:

https://user-images.githubusercontent.com/77248866/122077344-3cdf0b80-ce2e-11eb-9756-ee4fcc9c4c15.mp4

Develop Recording:

https://user-images.githubusercontent.com/77248866/122077696-8891b500-ce2e-11eb-8297-5bcea458b4ce.mp4

**Comment by Ry4ndrew** [comment]
Just tested on 9.4 Staging-2022 in steam. The chat UI does not show on top of the Loading Screen but it still appears during Avatar creation.

![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/e2e68eb6-347b-4c88-8a1c-e4725c3059ec)

Chat should only function after avatar creation just like the other UIs.
