### ISSUE TITLE
[0.9.4 staging-2010] Distance buttons are broken.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22145]
![image](https://user-images.githubusercontent.com/45708377/120972815-d47d9380-c776-11eb-8b0a-3c46cb18f9cd.png)
![image](https://user-images.githubusercontent.com/45708377/120972835-d8a9b100-c776-11eb-9c9c-142e7559e8c5.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2034.

Closing as fixed.
