### ISSUE TITLE
[0.9.3.6 beta release-234] Unable to see Land Claim Stake highlight when near the border

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22159]
Reproduce:
1. Claim land near the border
2. Point the cursor to the other side of the border

![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/56c90480-c248-4784-a5aa-712113011441)

**Comment by SlayksWood** [comment]
#22074
