### ISSUE TITLE
[0.9.3.6 beta release-234] Attempting to put logs or hewn logs into backpack creates blank error

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22157]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/687ef6a1-0fd1-471f-b3d3-01f8b21bbbed)

**Comment by SlayksWood** [comment]
fixed in staging with https://github.com/StrangeLoopGames/Eco/pull/7938
