### ISSUE TITLE
[0.9.4 staging-2012] Starter camp placing issue when overlapping another property/ Papers loss.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22158]
So 0.9.3.5 release when you overlap another property during Starter camp placement you have notification:
![image](https://user-images.githubusercontent.com/45708377/121152381-cfd7de80-c84d-11eb-8ed2-a64f01f0365c.png)
But now you have notification that you will lost access to it:
![image](https://user-images.githubusercontent.com/45708377/121152479-eaaa5300-c84d-11eb-9634-7067024948d0.png)
But this is not a right information, because you will have access to it if you place it in this way and can't place if you want to place any object to another player property:
![image](https://user-images.githubusercontent.com/45708377/121152746-25ac8680-c84e-11eb-839e-39c4d77f9b99.png)
![image](https://user-images.githubusercontent.com/45708377/121154579-bdf73b00-c84f-11eb-8797-eafc51ee59c7.png)
You just lost 2 Papers. The fact that you lose 2 papers and leads to the issue. So what should happen? We already have issue when we asked to have possibility to do it but you should return 2 Papers to inventory. Issue here #17409

Also when you overlap you own propertry you don't get papers too.

So to fix both issues (this one and #17409):
- if Campsite and tiny doesnt place on another player property then give possibility to place Starter Camp and return Land Claim Papers that was not used. So if you claim 3/4 plots during placement you should return 1 Papers to player inventory.
- When you try to place starter camp on you own land (there are cases when, let's say, someone gave you property) you should return Papers too.

To fix only this issue:
- prevent to place starter camp if one plot overlap another player property.
- When you try to place starter camp on you own land (there are cases when, let's say, someone gave you property) you should return Papers too.

**Comment by gzatravkin** [comment]
Check StarterCampItem

                if (plot.Owners == player.User) { this.bonusPapers++; continue; } // Already claimed, increase amount of bonus papers.               

And 

                if (!this.IsPlotAuthorized(plotPosition, player.User, out var canClaimPlot))
                    return;

**Comment by TwixterZ** [comment]
Feature tested as of 0.9.4 staging-2037 and it is working as intended.

Another player will be given extra land claim paper in the starter camp
