### ISSUE TITLE
Industrial Elevator getting stuck

### ISSUE THREAD

**Issue by Theshock220** [StrangeLoopGames/EcoIssues#22155]
I have dug out a mine shaft that i have put an industrial elevator on. The Elevator has gone up and down the shaft multiple times, but every now and then it decided to get stuck as if its blocked by something and my Truck ( the fuel one) moves sideways as if its getting pulled by something. Eco version is latest update available, i think version 9.3.5
 i have a video file available but it is apparently too big to upload.
![20210608165952_1](https://user-images.githubusercontent.com/4928707/121138514-20196580-c87b-11eb-8a4e-ba07ac979673.jpg)
![20210608165957_1](https://user-images.githubusercontent.com/4928707/121138526-23acec80-c87b-11eb-8b7f-f153d096526f.jpg)

**Comment by SlayksWood** [comment]
@Theshock220 Thank you for the report. We need some more details.
1. Can you provide log files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Please provide your PC specification (include Operating System and its version).
3. Does it always happen? Try to restart game/server and check it again.
4. If you still have a problem can you provide save file? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Hottentotten** [comment]
I also had this issue a single time and was very confused what was happening, but as it just happened one time I ignored it.

**Comment by Theshock220** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6615202/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6615204/Player-prev.log)

Windows 10
geforce RTX 2060 Super 8gb
32gb ram
500gb ssd
4tb hdd
intel I7-10700F 2.9GHZ

happens randomly, when i relog it goes away but comes back again.

**Comment by D3nnis3n** [comment]
Merge with https://github.com/StrangeLoopGames/EcoIssues/issues/23983
