### ISSUE TITLE
9.3.5/6 - Text being highlighted in console causes server to pause some tasks/issues

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22164]
If you have text highlighted in the console the server ends up in an odd state.

During startup it will just not load further until the text is unhighlighted

![image](https://user-images.githubusercontent.com/61889138/121324254-74b6f200-c908-11eb-8a1e-483779f560a7.png)

see below, its where i had highlighted Loading mods for a min n bit
![image](https://user-images.githubusercontent.com/61889138/121324300-826c7780-c908-11eb-8589-d978ba9e06f6.png)

Due to this, if a server crashes and you highlight the text AS it crashes, the server goes into a half crashed half running state during which everything appears fine to the end user but soon as console is touched the server crashes.

I had the crash issue on my server with github #21966 which caused my server to have to have a rollback of 2 days due to corrupted save files but being blissfully unaware as server was running smoothly.

**Comment by IcedForge** [comment]
Thank you for reporting as always !

@mirasrael @WeaselDog This is semi bad bad, if its possible id like to see a fix for it in 9.4 but if it potentially breaks things we could push it to 9.5 if you think its safer.

**Comment by mirasrael** [comment]
I assume it isn't something new in 9.3 and exists in very old versions Eco as well (like 7.x)? This behavior is default for Windows console and freezes app when it tries output to console until selection finished, because app may change console output. Not sure if it may be fixed somehow unless somehow selection disabled in console. But not sure if it is better and user can always change console selection mode by his own.

**Comment by IcedForge** [comment]
The main problem is that it causes a desync in behavior as the server keeps running, yet background systems such as savings etc seems to be frozen? It should freeze everything if thats the case if possible?

**Comment by TwixterZ** [comment]
Re-tested as of 0.10.0.0 Develop-712, this behavior have changed, even when you highlight the server console, the program continues to run and server will run as normal
