### ISSUE TITLE
Declunkify: Player movement rotation

### ISSUE THREAD

**Issue by Quadbro** [StrangeLoopGames/EcoIssues#22165]
From a comment on this PR: <https://github.com/StrangeLoopGames/Eco/pull/8728>
![image](https://user-images.githubusercontent.com/6802030/121331200-d98e3e80-c940-11eb-883e-6dcaf522e410.png)
A separate issue for that case to fix in next pr
https://user-images.githubusercontent.com/6802030/121019926-11bf4100-c7ca-11eb-8ac8-e298ad60fc10.mp4

**Comment by johnkslg** [comment]
Also to note: I would like to have orbit mode be default, i dont want to have to hold a key for it, otherwise people will never discover it.   It should work as it was: player turns towards movement when they start moving.
