### ISSUE TITLE
USER ISSUE: i cant remove or use my truck / cart

### ISSUE THREAD

**Issue by Samzix** [StrangeLoopGames/EcoIssues#22162]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
hover over the cart

**Expected behavior:**
able to use or pick up with a hammer

**Actual behavior:**
can't access it at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @Samzix

Thank you for raising this issue and apologies for this happening to you.

Can you help by providing additional information for us to check this issue further?
- Is this happening on Public Server or during your private session?
- Can you please share your save game data for us to investigate? 
You may refer below link for instruction to get your save file.
https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Daniel-Magulado** [comment]
Hi @Samzix,

Are you still encountering this issue?
Do note that Trucks and Cart have weight and contribute to the maximum weight limit that your avatar can carry.
It's possible that you're bag is already carrying heavy items which prevent you from picking up either the Cart or Truck.

**Comment by TwixterZ** [comment]
Closing this issue due to no response received
