### ISSUE TITLE
USER ISSUE: Natural Gatherer talent REDUCED how many plant fibers I get from Big Bluestems

### ISSUE THREAD

**Issue by Drake333** [StrangeLoopGames/EcoIssues#22173]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. Reach Gathering specialty level 5
2. Harvest a fully-grown big bluestem using a sickle (I used an Iron Sickle)
3. Note the amount of plant fibers you get
4. Reach Gathering specialty level 6 and take the Natural Gatherer talent
5. Again harvest a fully-grown big bluestem using a sickle (again I'm using an iron one)
6. Note the amount of plant fibers you get

**Expected behavior:**
The amount of plant fibers would be higher in step 6 than step 3

**Actual behavior:**
The amount of plant fibers was lower
Step 3 = 9 plant fibers
Step 6 = 8 plant fibers

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6627527/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6627528/Player-prev.log)

**Comment by Drake333** [comment]
Ok update, I've found some are worth 10 plant fibers, but I'm not sure why. Some of them were on tilled land so they may have counted as "farmed plants", but not all of them. A little confused. They still shouldn't be worth less.

**Comment by IcedForge** [comment]
Out on a limb there is the possibility that the nutrients were lower in that grid, or were lowered due to collective harvesting across which reached a certain bracket causing you to get a lower yield. Did you use a soil sampler to compare yield information?

**Comment by Drake333** [comment]
No I did not. So yeah it could have been a coincidence in timing. I don't
know much about farming mechanics. I've just been gathering.

**Comment by TwixterZ** [comment]
Issue retested on 0.9.3.6 Release-235 and confirmed talent is working as intended, retested following steps provided using iron sickle on bigbluestems with same number of yield
