### ISSUE TITLE
USER ISSUE: BUG au lancement d'une partie privée

### ISSUE THREAD

**Issue by captainerouge** [StrangeLoopGames/EcoIssues#22178]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**

**Expected behavior:**
Ma partie créée doit se lancer

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Server encountered an exception:

<size=60,00%>Exception: BadImageFormatException
Message:Index not found. (0x80131124)

System.BadImageFormatException: Index not found. (0x80131124)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
The type initializer for 'Eco.Shared.Authentication.UserAuthentication' threw an exception.
Could not load file or assembly 'System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Index not found. (0x80131124)</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @captainerouge,

Thank you for writing a report.
Are you still encountering this issue when starting a new game?
Are you running the game on Steam?
Based on the logs you've provided, it appears that you're running the game on the x64 platform on an x86 system.
Are you running the game on Windows? If so, could you provide your complete PC specification including the operating system and its complete version. Including if it's 32 bit or 64 bit.

Thank you.

**Comment by TwixterZ** [comment]
hello @captainerouge can you provide the additional information asked by Daniel above?

**Comment by TwixterZ** [comment]
Closing this as no response received from player.
