### ISSUE TITLE
USER ISSUE: Log collision bug

### ISSUE THREAD

**Issue by Faxer56** [StrangeLoopGames/EcoIssues#22170]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Stand on top of a log, chop it, and If you've done it correctly the bug will occure, but It can be very random some times.

**Expected behavior:**
Launched up in the air to the point where you can't see the earth below.

**Actual behavior:**
It's a odd occurance but shouldn't launch you up in the air haha

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods present and I've never installed mods in the past

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Faxer56,

Thank you for writing a report about this.
We are aware of this issue so I'll be merging it with #21830.
