### ISSUE TITLE
USER ISSUE: Occasional black frame

### ISSUE THREAD

**Issue by IAmTimborn** [StrangeLoopGames/EcoIssues#22172]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Unsure

**Expected behavior:**
Normal visiom

**Actual behavior:**
Occassional black frame

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @IAmTimborn, thanks for reporting on this issue.

Can you provide us steps on how to reproduce the issue along with a recorded video of it happening? 

This will help us further investigate this issue and what's causing it.

**Comment by TwixterZ** [comment]
Hi @IAmTimborn, are you able to provide requested additional information asked above?

A brief description on how and when does this happen to you might help us too.

**Comment by TwixterZ** [comment]
Closing issue due to lack of response from issuer
