### ISSUE TITLE
[0.9.4 staging-2015] Learning a specialty gives a skill point instead of taking it away

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#22182]
When attempting to learn a specialty with default settings, it will give an extra star instead of costing one, resulting in being able to learn all specialties.

To replicate:
- Start a fresh world on staging
- Learn a starting specialty (Logging)
- See that an extra star has been provided

**Comment by SlayksWood** [comment]
@WeaselDog Can't reproduce, maybe you just forgot that we stiil have bug when you start with 3 stars? https://github.com/StrangeLoopGames/EcoIssues/issues/21763
So when you learn skill you still have 2 stars?

**Comment by WeaselDog** [comment]
I misunderstood the issue. Thanks for checking
