### ISSUE TITLE
9.3.5 Stone road tool repair requirement not working

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22189]
Stone Road Tool has repair requirement below but does not actually need Basic Engineering L1 to repair it.

    [RepairRequiresSkill(typeof(BasicEngineeringSkill), 1)]

**Comment by Sekor2600** [comment]
Its the same with the other tools

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2026.

Higher tier tools now require the profession to get fixed. Closing as fixed.
