### ISSUE TITLE
Issues with Voice chat

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#22191]
[ecologs_and_screenshot (1).zip](https://github.com/StrangeLoopGames/EcoIssues/files/6640346/ecologs_and_screenshot.1.zip)

1. Changing voice chat from off to a different option doesnt work without restart for the users I had test that, see logs above.
2. Users dont necessarily expect 'off' to also mean they cant hear other people. Maybe make that more clear.
3. All users see a range in the voice chat menu, and its different for everyone of them.

**Comment by D3nnis3n** [comment]
![image](https://user-images.githubusercontent.com/25908592/121734008-7cd38500-caf4-11eb-9876-a887919d6477.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2026.

I can confirm that changes with voice chat options don't get applied until the game restart.
