### ISSUE TITLE
stockpile rendering out of sync

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2219]
![image](https://user-images.githubusercontent.com/774628/30672457-62af3b0a-9e21-11e7-931e-5d9b96bcfa9e.png)

**Comment by SeanAtr0n** [comment]
logs probably got taken by a workorder

**Comment by metachronism** [comment]
fixed

**Comment by Fank** [comment]
Got this with 6.0.1 51df7483
![image](https://user-images.githubusercontent.com/1900106/31196537-6f13fd26-a94e-11e7-82b0-6221f5c6c528.png)
![image](https://user-images.githubusercontent.com/1900106/31196539-7231d172-a94e-11e7-8dd4-00acf7f5e14a.png)
