### ISSUE TITLE
[0.9.4.0 beta staging-2017] can not change language in server UI

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#22209]
new server not create Localization.eco and have not active language change in server UI

**Comment by SlayksWood** [comment]
only can change it in debug or with qa modificator
![image](https://user-images.githubusercontent.com/45708377/121850125-f934b680-ccf4-11eb-8cdc-4d55e7f3f607.png)

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/123252069-8ac1d680-d4f4-11eb-8c7c-2904e15dcec0.png)
![image](https://user-images.githubusercontent.com/45708377/123252908-77fbd180-d4f5-11eb-870d-febb33a129af.png)
