### ISSUE TITLE
[0.9.5 Develop-297] Tooltip Bug

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#22206]
Some tooltip does not show properly, but instead flickering causing player unable to read tooltip

![tooltip bug.gif](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/5d6eaece-f610-4033-87c8-2022a6261195)

**Comment by Moritur** [comment]
This issue was fixed in PR https://github.com/StrangeLoopGames/Eco/pull/8725 some time ago and now I can't reproduce it on develop, so I think it's already fixed

**Comment by TwixterZ** [comment]
Issue checked in 9.4 Develop 300, and tooltip does not show anymore
![tooltip](https://user-images.githubusercontent.com/78054747/122170579-4cebff00-ceb1-11eb-9e54-45f0c4bcacbb.gif)

**Comment by Moritur** [comment]
> Issue checked in 9.4 Develop 300, and tooltip does not show anymore

I checked history in git and it turns out that this issue was introduced by merging PR https://github.com/StrangeLoopGames/Eco/pull/8644 and is not related to issue https://github.com/StrangeLoopGames/EcoIssues/issues/20430

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.5 Develop 306
