### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by rikardo84** [StrangeLoopGames/EcoIssues#22205]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Falha na Ligação</size>

Invalid login info.

<size=60,00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @rikardo84,

Thank you for writing a report about this.
It appears that you've tried to log in to an account using an incorrect username or password multiple times.
Have you recovered your account back yet?

**Comment by rikardo84** [comment]
how is this possible if i'm starting the game from steam

**Comment by Ry4ndrew** [comment]
Please contact support@strangeloopgames.com for the resolution of this issue. Thanks.
