### ISSUE TITLE
Make the ability to embed clickable buttons inside text

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22213]
From review on: https://github.com/StrangeLoopGames/Eco/pull/8730#pullrequestreview-682435266

Lets add a new feature to our text system, that allows you to insert buttons directly via text (this will take some exploration and can be a new task).  You can make a new function ButtonFoldout, which works just like RPCFoldout but instead of putting a text link, it displays a button.  (RPCFoldout works by embedding a view id and rpc name that gets called when the button is pressed, so it removes the need for handlers, though we'll need to update the view system to have persistent IDs across server instances).

Two parts: 
Make controller ID's persistent: https://github.com/StrangeLoopGames/EcoIssues/issues/22211
Add embedded buttons: https://github.com/StrangeLoopGames/EcoIssues/issues/22212

**Comment by johnkslg** [comment]
This is a hard one that I think we need sergeys support on due to his extensive experience in textmeshpro

**Comment by serpopov** [comment]
I think I have a tricky and nice solution, will answer in two days
