### ISSUE TITLE
[Hosted Worlds] Clicking "Start New World" causes error to pop up

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22223]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/df920786-2736-4662-bac1-45d987c3cd35)

**Comment by denysaw** [comment]
Fix has been deployed onto Sandbox.

**Comment by Ry4ndrew** [comment]
Confirm fixed
