### ISSUE TITLE
[0.9.4 staging-2020] Missing Fishing pole in 3rd person view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22234]
Step to reproduce;
- be in 1st person view
- select fishing pole:
![image](https://user-images.githubusercontent.com/45708377/121884415-8f7bd300-cd1b-11eb-8a71-f2d8acbc6879.png)
- press F5:
![image](https://user-images.githubusercontent.com/45708377/121884424-93a7f080-cd1b-11eb-8db8-6e278444e67f.png)

video: https://drive.google.com/file/d/1I1s8I0Iw3nDJJbX7u9wiIj5Fim5nsncc/view?usp=sharing
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6647914/Player.log)

**Comment by TwixterZ** [comment]
Issue checked in 9.4 Staging 2022, fishing pole is showing accordingly in 3rd person view.

![fishing2](https://user-images.githubusercontent.com/78054747/122202077-42406280-cecf-11eb-9d3e-117a621dd9e7.gif)
