### ISSUE TITLE
Alpha.6 [B1f481ec] All tailings disappeared by world migration

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2223]
Old save: ftp://eco.fankserver.com/Game_latest_cc778b68.eco
New save: ftp://eco.fankserver.com/Game.eco

**Comment by Frozen-byte** [comment]
@Fank This is related to another bug, not migration:
I moved them to Valhalla due a Bug in the older version: Drop the Tailing above a Markettable, with no other space around. It will disappear.

**Comment by Fank** [comment]
Closed due bug abuse
