### ISSUE TITLE
[0.9.4 staging-2020] Tool animations are broken in 3rd person view.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22232]
Something happened to the left hand:
![image](https://user-images.githubusercontent.com/45708377/121871259-951dec80-cd0c-11eb-8b06-2876b2d6ba68.png)
![image](https://user-images.githubusercontent.com/45708377/121871276-99e2a080-cd0c-11eb-9604-d016251bae30.png)
https://drive.google.com/file/d/1dneO9DQdplCGzU1136b0Qa7Q6oBePj43/view?usp=sharing

**Comment by Quadbro** [comment]
svn fixed

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2026.

Closing as fixed.
