### ISSUE TITLE
[0.9.4 staging-2020] A small delay when shot with bow

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22230]
Step to reproduce:
- take any bow and arrows:
- hold LMB and wait 5 sec:
![image](https://user-images.githubusercontent.com/45708377/121868058-37d46c00-cd09-11eb-993c-f5d817924323.png)
- release LMB, you have a small delay to shot.
- pretty hard to hit animal now.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2028.
Closing as fixed.
