### ISSUE TITLE
[0.9.4 staging-2021] Can't use tool after switching from 3rd person view to 1st one

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22257]
Can't use tool after switching from 3rd person view to 1st one:
Step to reproduce:
- take any hammer or axe
- select empty cell on toolbar ot another tool.
- switch to 3rd person view
- select hammer or axe
- switch to 1st person view
- use LMB to use tool. Nothing happens.

**Comment by SlayksWood** [comment]
> I have found several ways to cause the problem:
> 
> 1 way:
> 
> 1. go to 3-person view;
> 2. select Land Claim Stake;
> 3. point it at a few nearby sectors, but do not use it;
> 4. select your shovel, and you cannot dig with it;
> 5. switch to any other tool;
> 6. select your shovel again, and now you can dig.
> 
> 2 way:
> 
> 1. go to 3-person view;
> 2. select any free slot in your inventory and type the command "/give wooden shovel";
> 3. you will not be able to dig with it.
> 
> Sometimes it may not work, just move to another chunk or repeat the steps again.

**Comment by TwixterZ** [comment]
Unable to use shovel after using fishing pole in third person on latest build
