### ISSUE TITLE
[0.9.4 staging-2022] Citizens objective UI bugs

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22267]
- [ ] 1. Words that are objects/items in the game do not stand out
- [ ] 2. Font size is very small compare to other text in game.
![image](https://user-images.githubusercontent.com/45708377/122165187-86584680-ce80-11eb-8814-e00e63093577.png)

How it looked in 0.9.3.5:
![image](https://user-images.githubusercontent.com/45708377/122165242-996b1680-ce80-11eb-9d1c-04c3ae68d057.png)

**Comment by Daniel-Magulado** [comment]
Closing. Update has been made on Clickup.
Fixed and working for 0.9.4 Staging-2059.
