### ISSUE TITLE
Setup cw buying limit

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#22262]
We are going to soft release by number of cloud worlds owned.
so start with max of 50 worlds, fix bugs, then upgrade to max of 100 worlds, fix bugs, then max of 200 worlds, etc.

Need a system to set this max worlds owned.
If max is met, then cw sales page and subscription page will say "This service is not yet available. Check back soon."
We may already have a system like this?

I can do design elements and text. lmk

**Comment by denysaw** [comment]
Pushed to Sandbox. Could be cherry-picked into Prod.
