### ISSUE TITLE
Void Storage Issues

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#22264]
If the a person is evicted and they have a lot of storage items or a silo full of stuff then the void storage has unreachable items in it. Void storage needs scrollbars. Attached screenshot sent from player.

![image](https://user-images.githubusercontent.com/8082068/122156182-76b41000-ce36-11eb-9dbe-3d0d56e96f43.png)

**Comment by SlayksWood** [comment]
@jamesyoung79 Thank you for the report, this issue will be fixed in 9.4 with https://github.com/StrangeLoopGames/EcoIssues/issues/21407
![image](https://user-images.githubusercontent.com/45708377/122162675-9ff78f00-ce7c-11eb-8bf9-b76a6cdc9d7e.png)
