### ISSUE TITLE
[9.4 Staging 2022] Land claim stake graphic bug

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#22272]
While holding land claim stake, odd graphic bug can be clearly seen on the stake.

Possibly caused by lighting effects / land highlight effect

![stake ](https://user-images.githubusercontent.com/78054747/122195128-a57ac680-cec8-11eb-8605-818d0624096b.gif)

**Comment by SlayksWood** [comment]
merged to #9191
