### ISSUE TITLE
Repair Station works on every place ignore Room Requirements

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2227]

**Comment by johnkslg** [comment]
Fixed with tiers?

**Comment by knexer** [comment]
Nope, not fixed with tiers.

**Comment by metachronism** [comment]
this looks fixed to me

**Comment by metachronism** [comment]
the repair component doesnt seem to care whether the object is enabled or not, it repairs anyway.
need to make that component not allow the repair when its components arent functioning

**Comment by ClayC90** [comment]
This has been fixed with my pull request, please close accordingly,
