### ISSUE TITLE
[Hosted Worlds] Choose world tier is empty

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22277]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/3bf26fbf-0ac1-4b7f-8aff-a880b7cf7a5a)

**Comment by denysaw** [comment]
@Ry4ndrew correct. We are rebuilding word tiers now and it's could be tested only on Staging, that's why please, for now stop testing world tiers on staging ;) Thanx

**Comment by Ry4ndrew** [comment]
Ah alright then, if that is the case I shall close this until we are able to fully test the tier system.
