### ISSUE TITLE
USER ISSUE: bug report

### ISSUE THREAD

**Issue by rikardo84** [StrangeLoopGames/EcoIssues#22282]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
i try to get in a server or a word and i get this error	

**Expected behavior:**
i should get on the server or world to start paying

**Actual behavior:**
The following error message popped up:
```
<size=150%>Falha na Ligação</size>

Invalid login info.

<size=60,00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Responded in #22205
