### ISSUE TITLE
[Hosted Worlds] Renaming a World that is starting up shows an unknown error

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22286]
![image.png](https://images.zenhubusercontent.com/604031039e20f5d1b4f6e523/1bafe136-8384-4e4b-81ee-d5ad19e7e501)

**Comment by denysaw** [comment]
Deployed onto Sandbox.

**Comment by Ry4ndrew** [comment]
Confirm fixed
