### ISSUE TITLE
Room Calculation dont works with StoneBlocks 

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2228]
no room ?
![grafik](https://user-images.githubusercontent.com/26040573/30705895-0dc3e132-9ef7-11e7-95ed-68b750fa3021.png)
After Build one wood it is a Room
![grafik](https://user-images.githubusercontent.com/26040573/30705966-49c538c0-9ef7-11e7-8609-dd7a4c489fd5.png)

**Comment by metachronism** [comment]
this is intentional I believe

**Comment by Frozen-byte** [comment]
have you tried roadtool to make a road of it? This may work.

**Comment by johnkslg** [comment]
Fixed!
