### ISSUE TITLE
[0.9.4 Staging-2026] Deed name doesn't update

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#22299]
Editing deed name does not update in the Authorization UI until server restart

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/dc6e2982-c818-4e8d-8a54-5d186ca816e4)

**Comment by tuha263** [comment]
It will be updated when you restart the Client.

**Comment by TwixterZ** [comment]
Fix tested and confirmed as of 0.9.4 Staging 2045
