### ISSUE TITLE
[0.9.4 Staging-2026] Drill tools gets stuck and becomes unusable

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22293]
Build: 0.9.4 Staging-2026

## Issue
Both drill tools, Iron Rock Drill and Modern Rock Drill, get stuck when activated in the air. To fix it, you have to switch tools or press enter.

### Reproduction Steps
1. Obtain any Drill tools.
2. Select it and activate it while pointing in the air (not on land).
3. Try to stop it and observe.
4. Switch tools.
5. Observe.

### Recorded Video

https://user-images.githubusercontent.com/77248866/122580877-04873980-d089-11eb-91c7-f2a5605dea55.mp4

**Comment by TwixterZ** [comment]
Issue is fixed as of 9.4 Staging-2092
