### ISSUE TITLE
Extreme lagspikes when claiming plots

### ISSUE THREAD

**Issue by jagyCZ** [StrangeLoopGames/EcoIssues#22300]
As title says, when someone claims new plot of land it spikes cpu uitilization to 100% and lags the server for a second, 

ver: 0.9.3.5 Beta, release-231
nick: jagy (slg203061)

Server specs:
Linux Debian 10 Buster
CPU: Ryzen 9 3900x 4 cores
RAM: 8GB
SSD

**Comment by Daniel-Magulado** [comment]
Hi @jagyCZ,

Thank you for writing this bug report.
We are currently aware of this issue so I'll be merging this report to #20933.
