### ISSUE TITLE
Eco crashing immediately after Tessellation Message (MacOS)

### ISSUE THREAD

**Issue by jordyleigh** [StrangeLoopGames/EcoIssues#22310]
Just purchased the game today. I was able to play for about an hour with no issues on my Macbook Air (March 2020 version, before the M1 chip). Playing on the latest version of eco (beta-0.9.3.5)

When a friend joined the server, my game crashed immediately  and I haven't been able to rejoin since. We tried to get them to leave the server and see if it fixed my issue, it didn't.

The first crash was sudden, and I had received the message about GPU tessellation on joining the world, but had no issues whilst in game apart from my tools being help upside down. (I cannot obtain an image of this now as I cannot load into a game). 

Every time I have tried to join now, the GPU tessellation message appears, and then the game crashes within 2-10 seconds. I have tried to look at other issues reported here to find a fix, but haven't been able to. I also understand MacOS isn't technically supported yet.

Thank you!

Update: Straight after writing this issue, I tried to join via clicking on my friend's name and hitting 'join game'. I was able to get into the game but within 10 seconds the game crashed.

Update 2 [16:42]: I revalidated the game files to ensure nothing was wrong. I tried to create my own server and it failed. On trying to join my friend's server, I was able to play for about 1 minute before it crashed again. I have been unable to locate any crash logs.

**Comment by Daniel-Magulado** [comment]
Hi @jordyleigh 

Thank you for writing this bug report.
We deeply apologize for any inconvenience that this might have caused.
However, if I am not mistaken, Macbook Air doesn't have enough graphical processing power to meet the minimum requirements set by the game. MacBook Air 2020 uses an Intel Iris graphics card that has low graphical processing power compared to our minimum requirement which is the HD 7850.

Can you try playing the game at a lower setting and see if this improves anything? I recommend lowering the rendering value, resolution, and disabling all graphic enhancing options.

If possible, please provide us with the MacBook Air's complete hardware specification.
Please also upload your game save, to upload, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

Additionally, it will also help us understand what's going on if you can upload your game logs. Instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi, @jordyleigh were you able to provide the files requested above? 

also, does lowering your graphic settings help with your issue?

**Comment by D3nnis3n** [comment]
Closing issue do required feedback not provided. Please feel free to open a new report if your issue persists.
