### ISSUE TITLE
[0.9.4.0 staging-2028]Infinite claims by random plots / claims

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#22311]
When claiming plots as usual we get these random non associated claims and when you try to unclaim them they are not removed and yield claim papers 
![Screenshot_106](https://user-images.githubusercontent.com/24981362/122824516-0ba88480-d2e1-11eb-8427-ff09630c6f84.jpg)

**Comment by Sekor2600** [comment]
![grafik](https://user-images.githubusercontent.com/37456949/122825043-b751d480-d2e1-11eb-967a-213e38a84384.png)
The small Deed is the same like the Orginal big one. You can unclaim it with the Tool, have Claimpapers but it is not removed from the map and you can create endless numbers of Claimpapers.
it has no Impact to the Original Deed

**Comment by IcedForge** [comment]
Start server
Spawn claim papers and a claim stake; Claim 40-50 plots either manually or via map interface; 
Restart Server and ghost claims will appear.
![Screenshot_107](https://user-images.githubusercontent.com/24981362/122828671-3fd27400-d2e6-11eb-8201-f0d1e6de4622.jpg)

**Comment by Sekor2600** [comment]
Addition: If you try to place a RealEstateTable you crash the Server with it.

**Comment by WeaselDog** [comment]
Nice fix
