### ISSUE TITLE
[0.9.4 staging-2029] Eco server take a lot of CPU

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22314]
It almost all time take 30%+ of my CPU. previous it always take less 5%, sometimes when you claim a big land or other big calculation it can use near 20%:
![image](https://user-images.githubusercontent.com/45708377/122877459-4d681800-d33f-11eb-8c37-a295c5fd3ba0.png)
This is a new server.
I noticed first time it yesterday.

**Comment by SlayksWood** [comment]
Compare with 0.9.3.6 server:
![image](https://user-images.githubusercontent.com/45708377/122881176-85715a00-d343-11eb-8d56-4de944a9d6b3.png)

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/123645060-a7c91300-d82e-11eb-82bf-bf775d694491.png)
almost 50% of CPU usage is RCon polling.

**Comment by mirasrael** [comment]
another source of heavy CPU usage is UserManager.TickAll
![image](https://user-images.githubusercontent.com/475445/123645451-07272300-d82f-11eb-907c-2249d661edea.png)
