### ISSUE TITLE
[0.9.4 staging-2030] Can unclaim another player's property.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22324]
with Land claim Stake:
![2021 06 23 Can unclaim another player's property](https://user-images.githubusercontent.com/45708377/123044336-2e7e8a00-d402-11eb-9809-eae455ae0c4d.gif)

**Comment by SlayksWood** [comment]
check this one after fix #22110

**Comment by madpingui** [comment]
QA please test unclaiming abandoned plots command, and all test you can think of unclaiming, thanks!
