### ISSUE TITLE
[0.9.4 staging-2030] Not all items in the store have a icon with big list

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#22320]
Step to reproduce:
- open another player store which have a lot of items:
![image](https://user-images.githubusercontent.com/45708377/122928249-59210200-d372-11eb-9b0f-a5b10b6b3ce8.png)
![image](https://user-images.githubusercontent.com/45708377/122928540-a69d6f00-d372-11eb-9a58-482c9e8f1a8d.png)
So I can't see tooltip of this item, because icon is missing

**Comment by TwixterZ** [comment]
Adding on to this issue, editing price for an item part of a long buy/sell list will cause bug where price will show differently 

Repro: 
- Have a long list of item on sell and/or buy
- Edit price on one item
- Use mouse scroll to scroll list
- Observe some items price have changed 
- Quit menu and check on tooltip to see the actual/correct pricing

**Comment by TwixterZ** [comment]
Issue no longer prevalent as of 0.9.4 Staging-2043, closing issue now
