### ISSUE TITLE
Stone Road able to make with road tool and pickup with hammer #b1f481ec

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2232]
I used road tool on natural Stone block (not on placed stone blocks as i would have thought), this then turned into Stone Road, i was then able to pickup with the hammer and place into a stockpile also it can now be placed into the world, also as seen in Snapshot there is no recipe on tool tip.
![snap347](https://user-images.githubusercontent.com/29383891/30718036-8bbc9bdc-9f16-11e7-8ebf-8ef51bcbc01d.png)

**Comment by Conchipedia** [comment]
this i also mentioned in issue #2032 but on that one the newly made Stone road block Disappears when hit with pickaxe. Only hammer can be used on newly created Stone road block (not sure if both issues should be merged with this being the Newer one as we can actually have stone road now, just not by crafting

**Comment by Conchipedia** [comment]
quick question: did i do the correct thing with the linking of the other issues in here so they can be dealt as one issue?

**Comment by MarjieAVolk** [comment]
Looks good to me, thanks for linking them
