### ISSUE TITLE
USER ISSUE: Vehicle no longer interactable

### ISSUE THREAD

**Issue by ASammyA** [StrangeLoopGames/EcoIssues#22325]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
I left my vehicle (powered car) for about 15 minutes, and when I came back it was not interactable and I could push it around like it was paper. This happened to me at least 5 times in my 2 days playing the game with my wooden carts.

**Expected behavior:**
Vehicle should be interactable and not be pushed around as if it's weightless

**Actual behavior:**
Vehicle is interactable pushed around as if it's weightless

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6700104/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6700105/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6700106/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @ASammyA,

Thank you for writing this bug report.
I'll be merging your report with an early existing report about the same issue.(#20414)
If you ever encounter other issues, please do not hesitate to report them.
