### ISSUE TITLE
[0.9.3.5 beta release-231] FPS increased when deleting all notifications

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#22327]
I was just playing the game normally and the game became a bit sluggish as it does after a while. I was probably sitting at around 50 fps (didn't check). Saw i had a notification on the bell icon so I clicked it. Took a long time (probably 10 seconds) to open the notifications so I figured I probably need to clear them. Clicked on delete all and the game felt smooth like after a restart of the game client. Esc showing I had 100+fps like I only have after a fresh restart of the game.

Not sure what a lot of notifications has to do with FPS but felt I need to report the find.
Don't think I had ever clicked on delete all after the whole playthrough (White Tiger day 26) until now

Version 0.9.3.5 beta release-231
OS: Windows 10 Pro 64
CPU: AMD Ryzen 7 5800X
RAM: 32GB
GPU: RTX 2070 Super

[PlayerLogs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6701760/PlayerLogs.zip)

**Comment by gzatravkin** [comment]
Maybe something related to scroll list of Unity. Maybe some pooling is needed

**Comment by Daniel-Magulado** [comment]
Similar to #22259.

**Comment by WeaselDog** [comment]
Thanks for reporting this! We have optimizations coming in 9.4, but there will be a major improvements for notifications optimization in 9.5. Closing the issue as fixed.
