### ISSUE TITLE
[0.9.4 Staging-2030]Butchery table issues with Housing Skill value

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22332]
Build: 0.9.4 Staging-2030

## Issues
The butchery table seems to have some kind of issues with housing value. By default, it has a skill value of 2 for Kitchen rooms. So basically, if you place a butchery table inside an empty room, that room should be counted as a Kitchen. Just like every furniture. However, that's not the case.

### Butchery Table
![image](https://user-images.githubusercontent.com/77248866/123189362-43295380-d4d0-11eb-9d31-cd76879c4dad.png)

### Room with 1 Butchery Table
Placing a butchery table in an empty room:
![image](https://user-images.githubusercontent.com/77248866/123189426-62c07c00-d4d0-11eb-8e48-f2693a93c4ae.png)

### Room with 2 Butchery Table
Here's the behavior of the housing skill value if you place down 2 butchery tables.
![image](https://user-images.githubusercontent.com/77248866/123188945-833c0680-d4cf-11eb-815d-9948ef77a3d0.png)

### Room with 3 Butchery Table
Now, here's the behavior of the room if you place down 3 butchery tables.
![image](https://user-images.githubusercontent.com/77248866/123189025-a797e300-d4cf-11eb-813e-014bc3101c8f.png)

As you can see, one of the butchery tables is still ignored and disabled for some reason.

### 3 Butchery Table with 1 Kitchen Furniture
It doesn't help if you try to place more furniture. One of the tables is still disabled.
![image](https://user-images.githubusercontent.com/77248866/123189281-20973a80-d4d0-11eb-9545-de9893d2b56f.png)

### 2 Butchery Tables are Disabled
Here's what happens if you try to place down 3 butchery table and then pickup the first table you placed down and place it down again.
![image](https://user-images.githubusercontent.com/77248866/123191173-6b668180-d4d3-11eb-8adb-2889ca8fde86.png)
Two butchery table becomes disabled. If you try to do the same thing on the second butchery table, the same issue persists causing 3 butchery tables to become disabled.

![image](https://user-images.githubusercontent.com/77248866/123191285-9e107a00-d4d3-11eb-87e5-07f99efe6a4f.png)

## Reproduction Steps
The steps indicated here are steps to emphasize the issue greatly. These are not specific or exclusive steps for the issue to get triggered.
1. Obtain at least 3 butchery tables.
2. Place down all of them in an empty room.
3. Pick up the first table you placed down and place it down again.
4. Do the same thing on the second table.
5. Observe the housing value.

### Recorded Video

https://user-images.githubusercontent.com/77248866/123191623-255ded80-d4d4-11eb-9f31-caf5b6ed2a2c.mp4

**Comment by SlayksWood** [comment]
Check with server restart.
