### ISSUE TITLE
Migrate all server related projects to .net standard

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2234]
To load them in both .net framework (client, server (windows)) and .net core (server (linux, future)):   
![.net overview](https://i.stack.imgur.com/tE1ny.png)

**Comment by SeanAtr0n** [comment]
Looks like unity will support .net standard in 2018.1... we would either need to wait for 2018.1 or build Eco.Shared.dll targeting 2 different frameworks.

@metachronism is it OK to build Eco.Shared.dll twice and not really be sharing the exact same code?

**Comment by arvalaan** [comment]
@SeanAtr0n Milestone mentions 7.1, now with the Steam Release Linux Servers have become a highly demanded feature. I know that this isn't done yet but I'd like to see it reprioritized to a more logical milestone

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#372
