### ISSUE TITLE
[0.9.3.5] Self Improvement skill shouldn't go up based on your XP rate

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#22365]
So recently I noticed there was something weird going on with the Self Improvement skill. On White Tiger I had maxed out 6 professions and I was level 5 Self Improvement:

![image](https://user-images.githubusercontent.com/964559/123531565-6e6f9680-d6ba-11eb-99b9-2ada506525cf.png)

I figured that was as high as I could go based on the weird progression that skill has - #19528 .

However, I checked someone else and they had a level 6 Self Improvement while also having 6 max level professions:

![image](https://user-images.githubusercontent.com/964559/123531584-a4147f80-d6ba-11eb-8c32-8a9ac6a71efa.png)

So I'm guessing the rate you earn the Self Improvement XP is multiplied by your XP rate, which mostly punishes you for levelling anything until you have some high XP rate available (if you grind your first skill without housing, you will have much less Self Improvement than if you wait to take any skill and then level once you do have a house).

While this isn't much of a problem on normal servers, it's an issue on White Tiger since the XP rates are rather low. Ideally, we would have the skill give flat XP that isn't modified by the XP rate based on the skill levels you have, so anyone who reaches 6 Level 7 skills should have the same amount of XP in Self Improvement.

Or as #19528 suggests - the skill in general needs triage so it's not something weird. Maybe just give people XP for using a hammer or a shovel, or some flat XP each food tick to make it entirely passive?

**Comment by Daniel-Magulado** [comment]
Hi @ThePiachu 

Thank you for writing this bug report.
I'll be forwarding this to our development team so they can look into it further.

Thank you.

**Comment by SlayksWood** [comment]
merged to #19528
