### ISSUE TITLE
Alpha.6 [B1f481ec] No Wolf, Fox and otter

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2236]
Current animal stats:
```
Animals:
- Bison:          216 alive, 0 dead, 0 visible
- Elk:            218 alive, 0 dead, 2 visible
- Hare:           483 alive, 0 dead, 1 visible
- Salmon:         544 alive, 0 dead, 1 visible
- Trout:          555 alive, 0 dead, 3 visible
- Tuna:           556 alive, 0 dead, 3 visible
- Turkey:         392 alive, 0 dead, 0 visible
```

**Comment by SeanAtr0n** [comment]
seems fixed already but requires generating a new world or repopulating by drawing in the world layer or using spawnanimal.
![image](https://user-images.githubusercontent.com/774628/30721956-57773b44-9ee3-11e7-8bb7-af9fe0575b93.png)

**Comment by Fank** [comment]
Updated to latest staging fixed wolf + foxes

**Comment by Fank** [comment]
otter?

**Comment by MarjieAVolk** [comment]
Otters are not finished yet, so sounds like it's fixed
