### ISSUE TITLE
USER ISSUE: Cant create world

### ISSUE THREAD

**Issue by dakj0326** [StrangeLoopGames/EcoIssues#22370]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. Host A Private World
2. Press "Start"

**Expected behavior:**
It should have created a new world after a few minutes

**Actual behavior:**
The world was never created but was stuck at the "connecting" process of the world generation

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
@dakj0326 Thank you for reporting.
Please provide your server logs and player logs as detailed in the instructions.
Thank you.

**Comment by Ry4ndrew** [comment]
Closing issue due to lack of response.

If this issue happens again, kindly raise a new issue. Thanks.
