### ISSUE TITLE
[9.3.5] Parallel Processing: Milling Talent doesn't change craft times.

### ISSUE THREAD

**Issue by Greyhawk0** [StrangeLoopGames/EcoIssues#22373]
1. Gain Milling proficiency.
2. Level Milling to 3.
3. Choose Parallel Processing: Milling talent.
4. Build a big enough tier 1 room, and place 4 Mills and 800w power source.
5. Notice the craft times haven't changed, even after starting the work order or changing craft quantities.

**Comment by Daniel-Magulado** [comment]
Hi @Greyhawk0 

Thank you for writing this bug report.
We are currently aware of the issues with parallel processing.
I'll this report with #12407.

Thank you.
