### ISSUE TITLE
Iron hammer says it is A broadheaded Axe #b1f481

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2238]
Created an Iron Hammer, this has tool-tip for an axe, and does exactly what an axe should do, it is not visible in players hand also has no proper icon in toolbar
![snap348](https://user-images.githubusercontent.com/29383891/30720590-073a0bc4-9f20-11e7-90ce-4b9a25606c23.png)

**Comment by Conchipedia** [comment]
also as can be seen i replace a broken hammer, the square it was in is still showing red even if another item is placed there

**Comment by MarjieAVolk** [comment]
I will file a separate bug for that

**Comment by MarjieAVolk** [comment]
I will file a separate bug for that

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2243
