### ISSUE TITLE
Wrong coloring on durability items

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2239]
"as can be seen i replace a broken hammer, the square it was in is still showing red even if another item is placed there"

![image](https://user-images.githubusercontent.com/23460210/30721004-c5bcfcec-9ede-11e7-85b1-ef414642079b.png)

**Comment by Conchipedia** [comment]
that red colour is same on #4c637828 but on relog the colour disappears

**Comment by johnkslg** [comment]
Couldnt repro this. Steps? May be fixed?

**Comment by MarjieAVolk** [comment]
Okay I started playing with this, and I'm seeing a lot of problems (though not this particular one):

- If you drag a broken item into another slot in your inventory (or dragging another item onto it), it will turn red, but it will stop flashing.  It looks like it starts flashing only if you drag it into your selected slot.
- Dragging a broken item onto a non broken durability item (a) does not swap the two items as expected, and (b) resets the broken item's color to normal blue.

**Comment by MarjieAVolk** [comment]
Ah wait, it is only supposed to flash when selected I guess?  So that's not a bug

**Comment by MarjieAVolk** [comment]
Oh, I got this original bug to work, specifically by replacing the item with an Iron Hammer

**Comment by johnkslg** [comment]
Fixed!
