### ISSUE TITLE
USER ISSUE: Camera bugs out when sleeping in third person

### ISSUE THREAD

**Issue by kellenbeck** [StrangeLoopGames/EcoIssues#22396]
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. Turn on third person mode
2. Sleep in a bed
3. Get out of bed

this can be fixed by going out of third person mode.

**Expected behavior:**
You should be able to see yourself sleep in bed or something, or revert to first person mode.

**Actual behavior:**
The camera goes crazy until you turn third person mode off.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and Yes. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Screenshots provided:
![Screenshot 1](https://user-images.githubusercontent.com/13484635/123701487-86b0f400-d827-11eb-8b86-ed35ffe992d3.PNG)
![Screenshot 2](https://user-images.githubusercontent.com/13484635/123701551-9c261e00-d827-11eb-8748-81c0b0b3538e.PNG)
![Screenshot 3](https://user-images.githubusercontent.com/13484635/123701599-aea05780-d827-11eb-83e2-0b462d74bf1d.PNG)

**Comment by Daniel-Magulado** [comment]
Hi @kellenbeck 

Thank you for writing this bug report.
However, we are currently aware of this issue so I'll be merging your report with #22321.
If you ever encounter other issues, please do not hesitate to make a report about it.

Thank you.
