### ISSUE TITLE
Biome tracker excepting on reconnect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22402]
![image](https://user-images.githubusercontent.com/3536496/123723055-735d5300-d83e-11eb-8c5a-4f6affb3101d.png)
To repro:
- Start client in Unity and connect to running server
- Restart server. Client will reset as well.
- Exception, and cascading problems if you bypass it.

**Comment by mirasrael** [comment]
it should be already fixed in staging
