### ISSUE TITLE
Allow stores to use tags (categories of items)

### ISSUE THREAD

**Issue by CrazyFluffyPony** [StrangeLoopGames/EcoIssues#22405]
Example:
Carpentry store is buying logs. He might want to buy all logs for the same price. He is forced to create a buy/sell entry for every type (Oak wood, Birch wood, ...). It should be an option to buy/sell items within a tag (e.g. every type of log) for the same price.

This makes it much easier to setup a simple shop.

Yes, sometimes you WANT to have different prices for different variants, but OFTEN, people do not care about the variant (e.g. needing boards for crafting a waterwheel) and especially new people don't know, that when they place a buy entry for "Boards" it DOES NOT include "Hardwood Boards".

**Comment by Daniel-Magulado** [comment]
Hi @CrazyFluffyPony,

Thank you for writing this bug report.
I'll be merging this report with #14630.

Thank you.
