### ISSUE TITLE
USER ISSUE: Scroll in Store

### ISSUE THREAD

**Issue by kleshchevand** [StrangeLoopGames/EcoIssues#22404]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. Create a small sales list
2. Create a large buy list, it should scroll till sales list is out of view
3. Scroll buy list down
4. Aim at sell list and try to scroll (mouse wheel)

**Expected behavior:**
To scroll to the top

**Actual behavior:**
Nothing happens
P.S. Would be nice to have a way to organize things in store, either a sort feature or at least to be able to reposition elements by drag-n-drop

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods (official server)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @kleshchevand 

Thank you for writing this bug report.
We currently have ongoing development and upcoming changes with the Store UI.
You can refer to #20392 for more information.
A lot of issues and changes regarding store UI will be addressed there. With this, I will be closing this report.

Thank you.
