### ISSUE TITLE
Pipes giving weird readings when being Viewed #b1f481ec

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2240]
looking at pipes on Blast furnace that is creating iron Ingots have such massive changes in the output window and even saying at times Max 100 (Full) , this is the ONLY thing that is crafting even though all tables share the same pipe System, the same information can be viewed from Non crafting tables

**Comment by Conchipedia** [comment]
The light top left of crafting table is flashing red and green
![snap349](https://user-images.githubusercontent.com/29383891/30721268-2332ba4e-9f23-11e7-84e1-b30f7cb9a8ac.png)
![snap350](https://user-images.githubusercontent.com/29383891/30721272-233c7480-9f23-11e7-8ed4-0babdca5fcfa.png)
![snap351](https://user-images.githubusercontent.com/29383891/30721269-23331c8c-9f23-11e7-8c00-ad5b10264090.png)
![snap352](https://user-images.githubusercontent.com/29383891/30721267-2330577c-9f23-11e7-8b60-90903c1c3993.png)
![snap353](https://user-images.githubusercontent.com/29383891/30721270-233ade90-9f23-11e7-91b1-ec3f7143b60e.png)
![snap354](https://user-images.githubusercontent.com/29383891/30721271-233b0208-9f23-11e7-8392-221de292cd1f.png)
![snap355](https://user-images.githubusercontent.com/29383891/30721273-23493792-9f23-11e7-8a5a-10fc8f0ac446.png)

**Comment by Conchipedia** [comment]
even changing the Output at the end of the pipe to more exits doesnt change erratic behaviur
![snap357](https://user-images.githubusercontent.com/29383891/30721374-9b1023c6-9f23-11e7-9944-615af50c081e.png)

**Comment by Fank** [comment]
Can confirm that behaviour in a stove too.

**Comment by SeanAtr0n** [comment]
Looks like the tank size is getting set too low when servers start up, Picking up & placing the furnace/stove might fix it.
