### ISSUE TITLE
USER ISSUE: stuck inside stockpile ? 

### ISSUE THREAD

**Issue by joshua-mcfield99** [StrangeLoopGames/EcoIssues#22419]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
walk on top of stockpile

**Expected behavior:**
walked over

**Actual behavior:**
i got sucked into hell itself

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
@joshua-mcfield99 thank you for the report. 
Entering the command /unstuck should help you with this issue. If not please provide us with a recorded video of the issue as it happens.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response. However, do not hesitate to reopen or file a new ticket if you encounter any form of bugs.
