### ISSUE TITLE
Alpha.6 [B1f481ec] Unlearning skills does not refund skill points

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2241]
Unlearned some skills, but did not receive any skill points.

**Comment by Fank** [comment]
The value was set to `0`:   
![image](https://user-images.githubusercontent.com/1900106/30784761-bbb68126-a15b-11e7-89db-628006859d5c.png)

Should be 1 by default

**Comment by johnkslg** [comment]
Zero is the default I want, so there's a penalty for changing skills
