### ISSUE TITLE
USER ISSUE: I can't start Eco

### ISSUE THREAD

**Issue by chigeek61** [StrangeLoopGames/EcoIssues#22415]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Just starting the game

**Expected behavior:**
connected to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
@chigeek61Thank you for the report.
According to your error, it's assumed that you pressed ESC during the connection, but can you provide more details?

1. Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you attempt to connect to official servers and provide log files too? Instructions are here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Can you see the server list normally with ping and server info?
4. Do you have Firewall or Antivirus enabled?
5. What kind of internet connection are you using?
6. Please provide your PC specification (include Operating System).
7. Have you experienced this issue after updating to 0.9.3.5 or you had it before?

**Comment by TwixterZ** [comment]
hello @chigeek61, would you able to provide information requested by Ryan above?

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
