### ISSUE TITLE
Game server error:  failure to find assembly. cw log bug

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#22414]
cloud world logs are full of this error: failure to find assembly

@thetestgame can you add any extra context to this bug

@WeaselDog this is a game side issue, who to assign?

**Comment by WeaselDog** [comment]
Can you include a copy of the log?

**Comment by thetestgame** [comment]
Unfortunately during my efforts to fix logging on CloudWorlds we lost the logs in question and I've ben unable to get the logging functional again to discover it through Elastic. I'd need to hunt for the pods in question to get the logs.

**Comment by WeaselDog** [comment]
Closing as not reproduced. Please open an issue with logs if you encounter this problem again
