### ISSUE TITLE
[0.9.3.5] Game eventually chushes

### ISSUE THREAD

**Issue by foxnorth** [StrangeLoopGames/EcoIssues#22410]
Game crushes and I can't find the reason. 
I've updated all drivers, dx, .net, game files, ran memtest several hours. Can you help me?

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6735555/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6735557/Player-prev.log)
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6735559/DxDiag.txt)
[winEvent.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6735589/winEvent.txt)

Server log said that: [13:29:16.688] [41] [ Info] [Eco] Parent process exited, shutting down.

Thank you.

**Comment by Ry4ndrew** [comment]
@foxnorth thanks for the report. Can you provide save files? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by foxnorth** [comment]
https://drive.google.com/file/d/1STHUe9aGOh7aLe-wlGMS1sjebWpSq7JO/view?usp=sharing

**Comment by Ry4ndrew** [comment]
@foxnorth was there any actions that you've done on the server prior to the crash?

**Comment by foxnorth** [comment]
I'm trying to find any pattern. 
The time from start to crush is varying. Game can crush in any activity - building, walking, just standing.

I don't have such issues with other games in system.

I even clean installed OS - crushes persist without drivers and with fully updated drivers and software. I just hoped to save this world, but if you don't have any suggestions about it's nature feel free to close the issue.

**Comment by Ry4ndrew** [comment]
Do you have any crash dumps / callstacks at 
C:/Users/foxnorth/AppData/Local/Temp/Strange Loop Games/Eco/Crashes then please upload them as well.
We'll be able to get additional info on what goes on from there.

**Comment by foxnorth** [comment]
[Crash_2021-07-01_202715927.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6752802/Crash_2021-07-01_202715927.zip)

**Comment by foxnorth** [comment]
Bug has been fixed with last update. Thank you. Also Road workbench disappeared.
