### ISSUE TITLE
USER ISSUE: Tutorial menu is bugged and doesn't expand horizontally, but vertically.

### ISSUE THREAD

**Issue by starwind30** [StrangeLoopGames/EcoIssues#22420]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Do the tutorial.

**Expected behavior:**
The tutorial menu has horizontal margins that are wide and show the full text.

**Actual behavior:**
The horizontal margin is 1 word wide and because of that, the menu goes vertically completely down my screen, and I can't even read most of it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. This was my first map.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by starwind30** [comment]
![Eco screenshot](https://user-images.githubusercontent.com/65248851/124047519-3d98a580-d9c9-11eb-9f56-8ae526c9bdaf.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6744609/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6744610/Player-prev.log)

**Comment by Ry4ndrew** [comment]
Thanks for the report @starwind30 .
We are currently aware of this issue and a fix is already set soon in the coming updates.
Merging with #20252
