### ISSUE TITLE
USER ISSUE: GUI bug

### ISSUE THREAD

**Issue by MoneyNitch** [StrangeLoopGames/EcoIssues#22430]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Sobald man was Träg ist links neben den Kasten ein kleine Farbfläche

**Expected behavior:**

**Actual behavior:**
Immer beim Tragen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Kannst du bitte einen Screenshot anhängen?

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
