### ISSUE TITLE
USER ISSUE: Crash when looking through inventory

### ISSUE THREAD

**Issue by nicole-caldwell** [StrangeLoopGames/EcoIssues#22432]
\
**User Id: (slg202528)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
1. I don't have any repro steps except I was getting a lot of notifications in the (N) view that said something like "failed to call RPC".  I think it was while I was looking in my inventory and dragging items around.  I was also making hardwood hewn logs out of oak and clicking quickly to fulfill the work required for it.

**Expected behavior:**
It should have not crashed nor had failed RPC call in the feed.

**Actual behavior:**
Instead, the game crashed to the login screen.  I'm sorry I don't have a useful repro setup, but I do have a log dump.  I am attaching both the log I got from following the instructions and a log I got when I clicked the button that said something like "get log" when the crash happened.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I'm not sure.  I think there are mods installed, but I'm not sure if we got them up in time.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6757904/Player-prev.log)

[LOG_DUMP_CRASH.TXT](https://github.com/StrangeLoopGames/EcoIssues/files/6757905/LOG_DUMP_CRASH.TXT)

**Comment by nicole-caldwell** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6757914/Player.log)

**Comment by ChickenHacker1** [comment]
This is on our server, there are 2 mods installed. Big shovel and colorful vehicles. All other "mods" are just tweaked integer variables to the vanilla CS files. I'd try to pull the server logs, but I don't think I'd be able to find the time this crash instance occurred. We do commonly get the RCP errors, though

**Comment by Daniel-Magulado** [comment]
Hello @nicole-caldwell,

Thank you for writing this bug report.
We are currently aware of this issue and a fix is on its way in the coming game updates.
For now, I'll be merging this report to #21454
