### ISSUE TITLE
USER ISSUE: Metaphysical doorway that blocks nothing?

### ISSUE THREAD

**Issue by Sage-Geas** [StrangeLoopGames/EcoIssues#22435]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
I have no idea. I just fell asleep while playing last night, and now my door figures it doesn't exist. This is very near the start of gameplay. I just got level 3 for instance. Sorry I can't be more helpful yet. 

**Expected behavior:**
It should be letting me interact with it.

**Actual behavior:**
Lets me walk right through it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Base game only, so far.BTW. I'm literally standing inside the door right now as I type this.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

My log files.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6759172/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6759173/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @Sage-Geas,

Thank you for writing this bug report.
Are you still experiencing this issue? Have you tried to restart the game? If so, did it fixed itself?
If you're still suffering from this issue, kindly provide us your saved game file and a recorded video that pertains the reported issue. This will help us determine the issue.

Looking forward to your reply.

**Comment by Sage-Geas** [comment]
Hello Daniel. Thank you for your reply. Fair heads up, I'm a confusing fella apparently according to some people. So my apologies in advance if they are right.

------------

It turns out that the problem seems to solve itself with a reset of the game. This seems to be the case for most crashes and bugs I've been running into thus far. I would love to document them all for you, but... that's almost a full time job on its own when they occur. For instance, I just had it crash on me not long ago today, all because I was picking up sandstone I had just hit with my pickaxe too fast I guess. 

(I was picking it up and mining it at the same time. I guess it didn't like this too much, because it gave me a quick error that I couldn't catch fast enough and a full shut down of the game.)

I have a 2nd computer being built here in a week, so I should have more resources to make use of to better track some of this going on. My current system is can run many games, but... the gpu just doesn't seem to want to play ball all the time. So that's the next thing. This problem could just be my Radeon Pro WX5100 being a pain. So once I plunk my old 290x in again, and have a 2nd rig to test that against, I can give some better details of all the other bugs I come across. 

I mentioned the door one to you, because it seemed like something that might happen to anyone who stays logged in for too long. 

J.Moireibh

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Daniel-Magulado** [comment]
Hi @Sage-Geas,

Thank you for providing more information about this bug report.
We are currently aware of issues such as objects becoming not interactable.
I'll be merging this report with #20414.
