### ISSUE TITLE
0.9.3.5 Can't place blocks on authorized property when authorized through title instead of as person

### ISSUE THREAD

**Issue by AriePelt** [StrangeLoopGames/EcoIssues#22438]
On white tiger server when I'm authorized through the Senate title I can't place any blocks. I can access items, containers and stores like expected, but placing (or removing) blocks the game tells me I'm not authorized to do so.

When authorized on the claim though the Senate title (it also says Authorized in the bottom right)
![image](https://user-images.githubusercontent.com/77667688/124398911-88435600-dd18-11eb-9c49-9c53faabe48e.png)

Then the Senate title was removed and added directly as person I could place and pickup blocks
![image](https://user-images.githubusercontent.com/77667688/124398947-b7f25e00-dd18-11eb-9090-6a34d63a15d0.png)

**Comment by Daniel-Magulado** [comment]
Hello @AriePelt 

Thank you for writing this bug report.
We are currently aware of this issue so I'll be merging this report to an earlier report of the said issue.
You can track the said report at #21587.
