### ISSUE TITLE
USER ISSUE: Picked up item not added to inventory

### ISSUE THREAD

**Issue by InoukSamson** [StrangeLoopGames/EcoIssues#22431]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
(AS CLIENT)
1. make sure your inventory is full
2. pickup an item not already in inventory
3. Item is not added to inventory even if message says it was added.
--- Note
Even attempting to pickup the same type of item after making room in inventory, the previously picked up item type will not appear in inventory

**Expected behavior:**
I should get an error message when attempting to pick up item.

**Actual behavior:**
Item doesn't appear in inventory
-- Note
Even attempting to pickup the same type of item after making room in inventory, the previously picked up item type will not appear in inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @InoukSamson,

Thank you for writing this bug report.
Unfortunately, we are unable to reproduce this issue.
Could you provide us with a recorded video of the issue as it happens, your game logs, and your saved game files?
To upload game logs, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
To upload saved files, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by InoukSamson** [comment]
Hi Daniel,

Thanks for coming back to me. I finally figured out the issue. My issue was
that I wasn't aware of the backpack. I'm thinking that a feedback when
something is added to the backpack would help the player better understand
that he has a backpack. Or making the backpack UI opened by default would
solve this problem.

Thanks for coming back to me.

**Comment by TwixterZ** [comment]
@InoukSamson glad everything worked out for you. 

If you went thru in game tutorial quests, it will apparent that backpack is available from the moment you joined in.

that being said, if you think we can improve this further, we would be more than happy to read your suggestion @ [EcoSuggestions](https://github.com/StrangeLoopGames/EcoSuggestions/issues)
