### ISSUE TITLE
Stone hammer says its a broadheaded axe and wont remove blocks #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2243]
Basic Stone Hammer is really an axe so we cannot remove building blocks, the tool-tip says broadheaded Axe same as issue #2238 
![snap071](https://user-images.githubusercontent.com/29383891/30756026-a7b15a80-9fc0-11e7-91f4-9216956ad43a.png)

**Comment by Conchipedia** [comment]
it works on logs (as an axe would) but cannot remove anything else like dirt ramps for example

**Comment by Timmay24** [comment]
Same issue with Wooden Hoe.
![wooden-hoe](https://user-images.githubusercontent.com/5476826/30830767-6ee6e97c-a245-11e7-8f36-3e817419b4fb.png)

**Comment by Timmay24** [comment]
Iron Hoe as well - I assume it has become a hoe-wide issue.
![hoe](https://user-images.githubusercontent.com/5476826/30830954-11beaf4a-a246-11e7-8217-9ab3ec823374.png)

**Comment by MarjieAVolk** [comment]
@craig-jong Okay, I fixed this in the excel sheet - waiting for food things to be ready in order to export the .csv

**Comment by craig-jong** [comment]
Everything is an axe! 

I'm going to go through and do a large description pass which should catch all these issues.

**Comment by MarjieAVolk** [comment]
👍 It wasn't just a description problem though, it was actually inheriting from axe.  A bunch of tools were, game is basically unplayable right now because of that

**Comment by craig-jong** [comment]
this is fixed, though. I'm assuming you pushed the fixed XLSM because it worked fine when I tested it.
