### ISSUE TITLE
3440x1440 Resolution Causes Tutorial Text to become squashed

### ISSUE THREAD

**Issue by ItsKodas** [StrangeLoopGames/EcoIssues#22434]
3440x1440 Resolution Causes Tutorial Text to become squashed
![image](https://user-images.githubusercontent.com/43526329/124357245-d34c6300-dc5d-11eb-88c3-cefd27e4af34.png)

**Comment by SlayksWood** [comment]
@ItsKodas Thank you for the report. This issue is fixed in 0.9.4 version with #20252.
