### ISSUE TITLE
[9.3.5] Fees on tables effect self and trigger noop when not enough money of currency is available

### ISSUE THREAD

**Issue by lifezoned4** [StrangeLoopGames/EcoIssues#22433]
# Bug
When playing 9.3.5 on official white-tigger server (also seen this on own private server) when a owner of a table has not enough currency to pay set fees on table, a work order operation is not started and no error is displayed UX wise. 

Is this intend?

### Steps
1) Set fees on table to a currency (tested with minted one)
2) Start a work order while not having enough money to pay the fee

### Excepted behavior: 
Either UX message with error case or granting privilege because owner?

**Comment by TwixterZ** [comment]
Hi, @lifezoned4 thank you raising this issue. 

I'm happy to inform you that this is fixed in version 9.4 of ECO. 

Kindly look forward to the upcoming patch =)
