### ISSUE TITLE
Being Disconnected Every 5 - 10 minutes.

### ISSUE THREAD

**Issue by 0xide0ri0n** [StrangeLoopGames/EcoIssues#22444]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6766700/Player.log)
Here is the player log. Thank you!

**Comment by TwixterZ** [comment]
Hi @0xide0ri0n , thank you for raising this issue. 

Can we have more information?
- Is this happening on your personal session or public server?
- Was there any mod applied to said server?

**Comment by TwixterZ** [comment]
@0xide0ri0n Can I have a response on my questions? or does this issue still happening at your end?

**Comment by Daniel-Magulado** [comment]
Closing for now. Server issues have been fixed. Feel free to reopen if you encounter any issues with the network while in-game.
