### ISSUE TITLE
Korean translation correction

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#22441]
I want to translate Korean again

While I'm busy with work
Did you hear that Steam doesn't support Korean?

I don't know who, but someone messed up the Korean translation 
So I'm going to fix it with my team
Tell me how

**Comment by D3nnis3n** [comment]
You can help translate korean on Crowdin: https://crowdin.com/project/eco-by-strange-loop-games

As for marking Korean as supported on Steam, it needs a higher translation completion progress, as users that buy a game based on a language marked as supported expect a well translated game.

**Comment by StoryNine** [comment]
> You can help translate korean on Crowdin: https://crowdin.com/project/eco-by-strange-loop-games
> 
> As for marking Korean as supported on Steam, it needs a higher translation completion progress, as users that buy a game based on a language marked as supported expect a well translated game.

Then, after re-translation, we will request Korean language support.

Thank you.
