### ISSUE TITLE
[Client] Buggy Door and Small Wooden Cart UI not showing up

### ISSUE THREAD

**Issue by MrG11tch** [StrangeLoopGames/EcoIssues#22449]
**ECO version -** _9.3.5_

**Expected behavior -** _Door should be able to be opened/shut (and when shut be a solid obj), Small Wooden Cart UI should show up and be useable_

**Actual behavior -**  _Door UI not showing up and is able to be walked through (when closed), Small Wooden Cart UI doesn't always show up and I rendered useless during these times (random intervals of time)_

**Steps to Reproduce -** _All I did was play the game normally but I did have it running for a straight 11 hours (what can I say, Ima gamer). around the 8-hour mark is when the UI started messing up (for the cart). And around the 10-hour mark, the door messed up_

**Operating system -** _Windows 10_

**System specs -** _AMD Ryzen 7 3700X, Radeon RX 580_

**Screenshots or videos -** _I closed the game before I came here. But if it happens again I will record it_

_(Sorry if this doesn't make sense I am currently writing this @ 3:45 am and I've had a long day)_

**Comment by Ry4ndrew** [comment]
@MrG11tch thanks for the report.
Will close as duplicate and tracking of the issue is over at #20414
