### ISSUE TITLE
USER ISSUE: Cotton Boll

### ISSUE THREAD

**Issue by DamonStamper** [StrangeLoopGames/EcoIssues#22448]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Item's spelled wrong yo.

**Expected behavior:**
cotton boll = cotton ball

**Actual behavior:**
cotton boll = cotton ball

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Is server I dunno

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @damonStamper, thanks for the report.
Cotton Boll is the proper spelling for it since it grows into a rounded seed-bearing capsule. https://en.wikipedia.org/wiki/Cotton
