### ISSUE TITLE
USER ISSUE: The Inifnite Water Visiblity Bug

### ISSUE THREAD

**Issue by SirePufferfish** [StrangeLoopGames/EcoIssues#22454]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Go to a wall.
2. Go as close to it as possible and it should appear as if the water is gone.
3 (optional). Go to the surface where your vision is half underwater and half above water. This will make it appear as if the water dissapear too.

**Expected behavior:**
Nothing should've happened.

**Actual behavior:**
The watrer appears to dissapear but you continue floating.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Thanks for the report @sirepufferfish
We are currently aware of this issue and a fix is on its way in the coming game updates.
For now, I'll be merging this report to #22184
