### ISSUE TITLE
USER ISSUE: The Kelp Glitch

### ISSUE THREAD

**Issue by SirePufferfish** [StrangeLoopGames/EcoIssues#22452]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Go to a body of water with Kelp in it. 
2. Go towards the Kelp. 
3. Try to collect some Kelp.

**Expected behavior:**
A "pick up" icon should've appeared letting you pick up the Kelp.

**Actual behavior:**
All that happens is the word "Kelp" and it's icon appear at the top of the screen, but it is impossible to collect the Kelp as their is no "pick up" icon.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods and yes it happens when they aren't installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @SirePufferfish , thanks for the report.
Kelps can be harvested by using a Sickle or a Scyth.
The icon issue will be raised as a separate issue.

**Comment by SirePufferfish** [comment]
> Hi @SirePufferfish , thanks for the report.
> Kelps can be harvested by using a Sickle or a Scyth.
> The icon issue will be raised as a separate issue.

Thankyou!
