### ISSUE TITLE
USER ISSUE: "Failed to handle RPCResponse"

### ISSUE THREAD

**Issue by krys-k89** [StrangeLoopGames/EcoIssues#22456]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Affects all actions attempted 

**Expected behavior:**
Interactions with my environment

**Actual behavior:**
Nothing. Nothing happens.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @krys-k89 

Thank you for writing this bug report.
We are currently aware of issues triggering **Failed to handle RPCResponse** error.
A fix is on its way in the coming game updates. For now, I'll be merging this bug report to #21486.

Thank you.
