### ISSUE TITLE
USER ISSUE: Frequent crashes, unclear why

### ISSUE THREAD

**Issue by BobbieGoede** [StrangeLoopGames/EcoIssues#22458]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
It's not clear how the crashes are triggered, it happens when walking with cart, when mining, or just crafting in a workbench

**Expected behavior:**
No crash

**Actual behavior:**
Crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed and I'm playing on a vanilla multiplayer server with often 4 players online or so

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6790726/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6790728/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @BobbieGoede,

Thank you for writing this bug report and thank you as well for providing us with your game log files.
Are you still experiencing this issue?
If so, may we have your complete PC specification, Operating System, and Crash Dump files. You can find your game crash dump files at /Users/(username)/AppData/Local/Temp/Strange Loop Games/Eco/Crashes. Kindly upload the latest crash files.

It would also help us greatly if you could send us a video recording of the crash as it happens. This will help us narrow down the causes.

Looking forward to your reply.

**Comment by BobbieGoede** [comment]
There's nothing I can pinpoint as to what is triggering the crash, sometimes I can play for hours without a crash and sometimes it happens within minutes of starting.

Windows 10 Pro x64
AMD Ryzen 5 2600
48GB RAM
RTX 3080

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/6796704/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6796706/Player.log)
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6796707/crash.zip)
(couldn't upload .dmp file so I zipped it)

**Comment by Daniel-Magulado** [comment]
Hi @BobbieGoede 

A closer look at your game logs and crash dump file, it appears that some of your programs installed are causing a 0xc0000005 error for the unity engine. We highly recommend disabling all background programs when playing Eco and allowing the game through Firewall if prompted. It is also possible that your Anti-Virus program if you have any, is treating Eco as malware. Kindly try making an exception for it as Eco uses an outbound connection so you can connect to our official game servers.

**Comment by Daniel-Magulado** [comment]
Merging with #22499
