### ISSUE TITLE
M1 mac crash after joining server.

### ISSUE THREAD

**Issue by mjart** [StrangeLoopGames/EcoIssues#22457]
Mac Version: Mac mini M1, Mac OS Big Sur 11.4
Eco Version: 0.9.3.5 Beta Version 231
Repro steps:
1. Open Eco
2. Join server
3. While loading into server the Tessellation issue message appears
4. loads correctly into the server with message still on screen (also happens when accepting the message)
5. Rendering on the minimap seems okay, just the old redwood trees look like toothpicks (no foliage rendering)

Expected:
6. Game runs without crashing
Result:
6. Game crashes after 2 - 60 seconds

Attached is the error dump that mac os gave me. 
Let me know if you need any more info from my side. I know that eco is not supported on mac officially, but getting it to not crash consistently would be ace.
[EcoCrash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6790489/EcoCrash.txt)

**Comment by Daniel-Magulado** [comment]
Hi @mjart 

Thank you for writing this bug report. Unfortunately Eco currently does not officially support Mac nor Linux.
I will, however, merge this bug report with an existing similar report.
You can track its progress through #20322.
We deeply apologize for the inconvenience.
