### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by minec87** [StrangeLoopGames/EcoIssues#22468]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connessione non riuscita</size>

Impossibile connettersi, timeout della connessione.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @minec87,
Thank you for writing this bug report.
Are you unable to connect to any server or is this a specific server?

**Comment by Daniel-Magulado** [comment]
Hi @minec87 

This issue should be fixed now. Kindly check and let us know if you're still having difficulties connecting to a friends server.

**Comment by minec87** [comment]
i can't change the currency or remove it. how do i do it?

Il Gio 5 Ago 2021, 22:33 Daniel Moises Dizon Magulado <
***@***.***> ha scritto:

**Comment by Daniel-Magulado** [comment]
Hi @minec87 

To make a new currency, you need to use the Mint item that will let you create a new currency.
Since the main issue is fixed, I'll be closing this ticket for now. Feel free to write a new one if you encounter any issues in-game.
