### ISSUE TITLE
USER ISSUE: meteor

### ISSUE THREAD

**Issue by bigboy793** [StrangeLoopGames/EcoIssues#22463]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**
the metor should impact in 27 days

**Actual behavior:**
instead it impacts in 14 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @bigboy793 

Thank you for writing this bug report. However, we would need more information to understand what's going on.
Kindly provide us more information about the issue as well as supporting documents such as game log files after the issue occurred, a recorded video, reproduction steps, the complete specification of your system, and a detailed report of the issue containing the issue, what happened, the things you have done, and more information about the issue.

Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
