### ISSUE TITLE
USER ISSUE: Inventory to heavy

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#22464]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6796832/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6796833/Player-prev.log)

\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Hand slots empty
2. Move Hammer to slot 1
3. Move item Hoe to slot 2

**Expected behavior:**
Store Hoe on slot 2

**Actual behavior:**
TO HEAVE message alert appear.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. I don't have mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi, @Crazy-Spy.

thank you for raising this issue, 

For us to understand this issue better, we are seeking your help to provide below informations :
- While you have mentioned that your hand slots are empty, is your bag full when doing this?
- If your bag is not full, does it already hit the weight limit? (see example below)
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/54b6b559-ba90-47a1-8e17-82bfe5b11eee)
- If your answer for the above is no, would you able to provide a video or a picture of this happening? 
- You can also provide us with your save file for us to try reproduce this ourselves. (steps below) 
Save files:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Crazy-Spy** [comment]
Hi there... That is something that I wasn't aware about it... The itens are in the backpack not in the handslots.

Really sorry for that. 

The game is working as expected.
