### ISSUE TITLE
USER ISSUE: Dirt ramps dont link to dirt

### ISSUE THREAD

**Issue by redmoogle** [StrangeLoopGames/EcoIssues#22469]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Place a dirt ramp
2. Upon placing the ramp the dirt at the end point/upper side doesnt link causing you not to be able to move up and off

**Expected behavior:**
Dirt should link

**Actual behavior:**
Dirt doesn't link to allow you to make a functional road

**Do you have mods installed? Does the issue happen when no mods are installed?:**
A stack modfying mod

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6815991/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6815992/Player-prev.log)

**Comment by PixlRainbow** [comment]
did you try turning the dirt into a dirt road?

**Comment by redmoogle** [comment]
> did you try turning the dirt at the upper side into a dirt road with a road tool?

Yes, while that works; It's in a desert so it just turns back.

**Comment by PixlRainbow** [comment]
alternatively you can place "solid cube" blocks like hewn log, mortared stone, etc. They will look ugly and out of place, but they should align.
