### ISSUE TITLE
USER ISSUE: Truck and Skid Steer are inactionable

### ISSUE THREAD

**Issue by coldeli** [StrangeLoopGames/EcoIssues#22460]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
I cannot reproduce it.	

**Expected behavior:**
Truck and Skid steer are actionable.

**Actual behavior:**
Suddenly truck and skid steer can't be actioned. Theya re just pushed around. Cannot enter, nor deposit materials.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Do have mods installed, have not tried without mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello, @coldeli 

Thank you for writing this bug report.
We are currently aware of issues with objects including vehicles becoming not interactable objects.
I'll be merging this report to #20414

Thank you.
