### ISSUE TITLE
USER ISSUE: Tooltips stay on too long

### ISSUE THREAD

**Issue by janosdebugs** [StrangeLoopGames/EcoIssues#22479]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Hover over any item with the mouse accidentally.	

**Expected behavior:**
Tooltips should disappear much quicker when moving mouse away

**Actual behavior:**
The tooltip obscures the interface for too long.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6834898/Player.log)

**Comment by TwixterZ** [comment]
Hello @janosdebugs, 

Thank you for raising your concern on this matter.

I apologies I could not give any timeline as to when this will come. 

However, as tooltip UI is currently being reworked, you should no longer have this issue in future patch.

**Comment by janosdebugs** [comment]
Awesome, thank you! Keep up the good work!
