### ISSUE TITLE
Wooden shovel holds dirt like a ballon #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2247]

**Comment by Conchipedia** [comment]
Digging up dirt with wooden shovel looks way wrong, also quite difficult to see
![snap072](https://user-images.githubusercontent.com/29383891/30761467-403da438-9fd6-11e7-93e3-c235ed5979a8.png)

**Comment by keegan-o** [comment]
Fixed the carry location.
