### ISSUE TITLE
USER ISSUE: Can't cook Charred Mushrooms

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#22474]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Open Campfire
2. Create a Project of cook 10 Mushrooms
3. I have 62 Mushrooms in my inventory
4. Over the project to get the info about it. 
5. Card says that 9 required and 0 avilable in the storage

**Expected behavior:**
Start the project

**Actual behavior:**
Project Halted

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6823021/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6823022/Player.log)

![image](https://user-images.githubusercontent.com/67368828/125787361-031a9799-b4a8-47d9-b180-9409839416be.png)

**Comment by Motakl** [comment]
Everything working as intended here. Halted cause you didn´t put work in yet and put the resources in linked storages (Chest or Stockpile) not your own inventory. The Workbenches always only take in resources for 1 repetition.

**Comment by Daniel-Magulado** [comment]
Hello @Crazy-Spy 

Thank you for writing this bug report. However, based on the screenshot you provided, you haven't placed any labor to start the cooking yet. Please click the **Work** button and keep doing so until the green bar fills up the empty bar space or reaches 100%.

I also recommend checking your storage tab and check if the inventory where your mushrooms are store is linked with the Campfire you are using to cook. To do so, please open the UI of your Campfire and click Storage. Look for the inventory that contains your Mushrooms and click on the little empty box on the upper left corner of the inventory to link it with the Campfire.

Let me know if this helps you.

Looking forward to your reply.

**Comment by Crazy-Spy** [comment]
Thanks for the reply... I will take that as a closed item. I had tried many times and them I decided to created the screenshot... and indeed in the screenshot I didn't put any work on it since I was "losing" the kcal that I was assiging to that. 
I will try that again and if occurs I will create that item again.
