### ISSUE TITLE
USER ISSUE: Failed to handle RCPResponse - Claiming a Property

### ISSUE THREAD

**Issue by krys-k89** [StrangeLoopGames/EcoIssues#22477]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Attempting to claim a proper

**Expected behavior:**
Set up my starter camp

**Actual behavior:**
Waiting a half hour.Severl different attempts to interact. Nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @krys-k89 

Thank you for writing this bug report.
Are playing with a friend's server? 
Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Additionally, if you could provide us with a recorded video of the issue, that would help.
Looking forward to your response.

**Comment by krys-k89** [comment]
Hi @Daniel-Magulado 
I have been playing on my own server. I can see what I can do about a video, it would be recorded from my phone as the time from initial interaction to action lags significantly and frustrating, so hopefully I can capture that for you. But here as the log file for you.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6904306/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6904307/Player-prev.log)
The property itself has finally been placed (it only took an hour of wait time)
But the original issue (#22456) hasn't been remedied yet as far as I can tell. Hopefully there will be a release of v. 9.4 soon and it will fix the interaction issues.

**Comment by Daniel-Magulado** [comment]
Hi @krys-k89 

Based on the logs you provided. Your running Eco on a system that's below the minimum requirements.
Eco's minimum requirements are:
OS: Windows 10
Processor: AMD Ryzen 5 1500X 3.5 GHz Quad-Core or Intel i5-6500 3.2 GHz Quad-Core or similar
Memory: 8 GB RAM
Graphics: AMD Radeon HD 7850 or NVIDIA GeForce GT 640 or Intel HD Graphics 540 or similar (2 GB memory recommended)
DirectX: Version 11
Network: Broadband Internet connection
Storage: 4 GB available space

We recommend playing Eco on a much powerful hardware.
Closing this as this is a hardware issue.
