### ISSUE TITLE
USER ISSUE: Arrows moving head as well as body

### ISSUE THREAD

**Issue by kaythehawk** [StrangeLoopGames/EcoIssues#22478]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
move character using arrow keys, does not matter if first person or third person POV

**Expected behavior:**
move character forward, backward, side to side without moving character head/field of view

**Actual behavior:**
forward arrow makes head move up while walking, back arrow makes head move down while walking backwards, side arrows move character in circle due to nature of how pov affects side to side movement

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no personal mods though mishka has moded this world, this is only world I play in.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hello, @kaythehawk

Thank you for raising this issue. However, I have not been able to reproduce this issue at my end.

Can you assist to provide us a recording of this happening? 

Are you by any chance playing on a laptop? and on what operating system?

**Comment by kaythehawk** [comment]
I tried getting video of it but today it’s not happening now. Probably something with my computer, Mishka asked earlier in discord if I’m on a laptop so I assume she passed on the information that I am and it’s a Lenovo yoga

Sent from my iPhone

On Jul 18, 2021, at 04:43, Khairi ***@***.***> wrote:

﻿

Hello, @kaythehawk<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaythehawk&data=04%7C01%7C%7C82ec15ba24174abeb82808d949c80f9e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637621945866091168%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cG4eeYTdkPJfjBRr1hESPiqZ6VRjWhl1m3SdweKe6FU%3D&reserved=0>

Thank you for raising this issue. However, I have not been able to reproduce this issue at my end.

Can you assist to provide us a recording of this happening?

Are you by any chance playing on a laptop? and on what operating system?

**Comment by TwixterZ** [comment]
Hi @kaythehawk between your last comment till date, do you still face this issue at you end?

**Comment by TwixterZ** [comment]
Closing this issue as no further response received, in case where this issue happens again, please do not hesitate to re-open.
