### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by krys-k89** [StrangeLoopGames/EcoIssues#22473]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Unable to place my tent
Cannot see the nutritional stats of the food in my toolbar
Items load once I've shut the game down and started it back up 

**Expected behavior:**
To be able to put down the tent wherever I choose
Be able to see the nut. stats
Actionable items should react in realtime

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__71_4()</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @krys-k89 

Thank you for writing this bug report.
Are you playing this game for the first time?
To view the nutritional stats of the food in your toolbar, you have to hover your mouse icon over the food icon. A tooltip will appear showing all the details and information about the food.

Are you referring to the Starter Camp? The be able to place the starter camp, you need to make sure that the area where you wish to place the tent is flat ground for the tent and has no obstructions such as trees.

Could you provide us a screenshot or a recorded video of this issue about the tent? This will help us see a clearer view of the issue.

Are you also able to reproduce the same steps where you encountered the exception error? If you, could you provide us a recorded video of it as well as your game log files.  Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @krys-k89 

Are you still experiencing the issues in this report?

**Comment by krys-k89** [comment]
Hi @Daniel-Magulado, the tent finally placed itself, but see #17292 because usability of the game is impossible and I've essentially given up for now :(
