### ISSUE TITLE
USER ISSUE: Trapped inside large lumber stockpile

### ISSUE THREAD

**Issue by CookBG88** [StrangeLoopGames/EcoIssues#22470]
\
**User Id: (Not logged user)** (c_silverwind on steam)
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Stand on large lumber stockpile and load it with goods	

**Expected behavior:**
just depositing goods	

**Actual behavior:**
deposits goods & traps you inside the hitbox of the stockpile	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @CookBG88 

Thank you for writing this bug report.
This can happen sometimes due to the algorithm set for the lumber where it considers that actual numbers of slots used and visually represent it as well. If you get stuck inside of it, I recommend using **/unstuck** command.

**Comment by CookBG88** [comment]
Thank you!
I did figure out that part. Just wanted to contribute to helping the dev
team. I'm absolutely loving this game!

Thank you!
Brandon
