### ISSUE TITLE
USER ISSUE: Vehicles

### ISSUE THREAD

**Issue by petranika** [StrangeLoopGames/EcoIssues#22486]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Leave a vehicle alone for a few hours

**Expected behavior:**
no effect on rotation. Stand right side up on its wheels

**Actual behavior:**
flips for no apperant reason

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @petranika 

Thank you for writing this bug report.
We are currently aware of this issue and a fix is already set in the coming game updates.
I'll be merging this report with an earlier report at #15688
