### ISSUE TITLE
USER ISSUE: "Finish the tutorial or skip it before you can access your skills." dialog can be opened indefinitely

### ISSUE THREAD

**Issue by SevenDeLeven** [StrangeLoopGames/EcoIssues#22488]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1: Join a World as a beginner player in a tutorial
2: Press Skills button (Z for me) repeatedly

**Expected behavior:**
It should block the input or close the dialog

**Actual behavior:**
Instead it opens the dialog and stacks it above the previously opened dialog(s)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have mods

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6866069/Player.log)

No Player-prev.log file (brand new never closed the game)

**Comment by TwixterZ** [comment]
Hi @SevenDeLeven, thank you for raising this issue to us. 

Happy to inform you this issue is fixed in 9.4 version. 

Look forward to future patch and enjoy =)
