### ISSUE TITLE
[PC] Xbox One Controller-Unterstützung

### ISSUE THREAD

**Issue by SnakeEate98r** [StrangeLoopGames/EcoIssues#22480]
Wird es bald Controller Unterstützung geben?

**Comment by TwixterZ** [comment]
Hi @SnakeEate98r, Dies ist der falsche Kanal, um Fragen zu stellen. Sie können unserem öffentlichen Discord beitreten, um Fragen dieser Art zu stellen

Controller-Unterstützung ist geplant, aber kein Zeitplan.

Apologies for any mistranslation, used google translate.
