### ISSUE TITLE
[0.9.3.6 beta release-235] When overthrowing a constitution, new civics still subject to existing constitution's rules

### ISSUE THREAD

**Issue by thomasfn** [StrangeLoopGames/EcoIssues#22481]
For example, when attempting to overthrow a "dictatorship" constitution with a "democratic" constitution, it is impossible to propose any civics alongside the new "democratic" constitution ratification, because the overthrowing player is still subject to the civic articles of the "dictatorship" constitution while drafting the overthrow.

Steps to reproduce:
1. Ratify a "dictatorship" constitution (e.g. all civic articles only have Admin as executor)
![overthrow_issue_1](https://user-images.githubusercontent.com/2463967/126048740-0aa216b1-5237-4362-b047-52ef6a1828b6.png)

2. As someone who does not have any civic privs from the "dictatorship" (e.g. in above example, a non-Admin), build a new Capital with a higher room value and overthrow the previous constitution with a new "democratic" one
![overthrow_issue_2](https://user-images.githubusercontent.com/2463967/126048763-baa76204-f802-4d32-bcb9-52f0ae47d982.png)
(note above that the election is the default one with no changes, all articles are Basic Election, and it is drafted)

3. As the same player, attempt to draft any other civic, with the intention of referencing that civic from the "democratic" constitution and bundling it along with the ratification draft election
![overthrow_issue_3](https://user-images.githubusercontent.com/2463967/126048798-9b0011a6-3f96-41be-8cc9-60e146fdac46.png)

Observe that the overthrow "democratic" constitution has _not_ granted any temporary rights, and the player attempting the overthrow is still subject to the rules of the "dictatorship" constitution, forcing them to push through a vanilla "Basic Election" constitution.

Expected that the overthrow "democratic" would grant temporary rights to draft new civics with the condition that they must be bundled along with the new constitution in the overthrown ratification draft.

**Comment by TwixterZ** [comment]
Hi @thomasfn , thank you for raising your concern here. 

However, this is currently working as intended. 

You may raise an issue at [EcoIssues](https://github.com/StrangeLoopGames/EcoSuggestions/issues) for bundled laws for overthrowing governments.
