### ISSUE TITLE
USER ISSUE: Connection timed out

### ISSUE THREAD

**Issue by Emendiel** [StrangeLoopGames/EcoIssues#22489]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Try to connect to a friend's world

**Expected behavior:**
Can't join my friend's world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Emendiel 

Our development team has addressed this issue. Kindly check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
