### ISSUE TITLE
USER ISSUE: Lost connecting

### ISSUE THREAD

**Issue by sangsung0475** [StrangeLoopGames/EcoIssues#22483]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. try join friends server
2. Loading...3. disconnecting(too long time)
4. agains...

**Expected behavior:**
i'll try restart my pc

**Actual behavior:**
다음과 같은 오류 메시지가 떴습니다:
```
<size=150%>연결 실패</size>

연결 실패 - 연결 시간 초과.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i don't have mod anything but i was change language to Korean and this error is comming

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @sangsung0475 

Thank you for writing this bug report.
We apologize for any inconvenience that this has caused.
For us to be able to figure out what's causing the issue, kindly provide us with your game log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @sangsung0475 

Our development team has addressed this issue. Kindly check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
