### ISSUE TITLE
USER ISSUE: cant access friends world 

### ISSUE THREAD

**Issue by realhorizon** [StrangeLoopGames/EcoIssues#22484]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1.click continue to open friends world

**Expected behavior:**
it shoulkd have loaded up the world 

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @RytterKnejt 

Thank you for writing this bug report.
We apologize for any inconvenience that this has caused.
Our auth servers may get down from time to time.
Are you still unable to load the saved file of your friend's world?
If so, kindly upload your game log files here as well as the saved file of your friend's world.
To upload the game log, please follow the instructions here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
To upload saved files, please follow the instructions here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

You can also forward the saved file to daniel@strangeloopgames.com.

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
