### ISSUE TITLE
USER ISSUE: can not join friend 

### ISSUE THREAD

**Issue by RytterKnejt** [StrangeLoopGames/EcoIssues#22482]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**
i should be able join him

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i dont have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @RytterKnejt 

Thank you for writing this bug report.
We apologize for any inconvenience that this has caused.
For us to be able to figure out the issue, kindly provide us with your game log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @RytterKnejt 

Our development team has addressed this issue. Kindly check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
