### ISSUE TITLE
USER ISSUE: Connection Failure

### ISSUE THREAD

**Issue by kappetta** [StrangeLoopGames/EcoIssues#22485]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Shift+tab to open steam pannel;
2. Right click on friend's name to open the options pannel;
3. Select to join friend's game;
4. "Connection to the server";
5. "Failed to connect".

Observations: This error only occurs when my friend or I try to join each other's server. We can join the public avaiable servers but not each other's private one. Other friends of mine can't join my server too.

We both already tried:
1. Disable antivirus and/or firewall;
2. Use a VPN.

**Expected behavior:**
Connect to each other's server without failures

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
We don't have any mods installed and the issue continues to persist

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6844178/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6844179/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @kappetta 

Our development team has addressed this issue. Kindly check if you're still encountering or having difficulties with establishing, connecting, or playing with a friend. Do let us know if any issue arises. Looking forward to your reply.

**Comment by Daniel-Magulado** [comment]
Closing for no response. Assuming the issue is fixed for the player.
