### ISSUE TITLE
Wooden Elevator Post flavor text

### ISSUE THREAD

**Issue by Valderg** [StrangeLoopGames/EcoIssues#22491]
Change "Wooden Elevator Call Post" To "Elevator Call Post" as well as the flavor text from "Used to call a nearby Wooden Elevator" to "Used to call a nearby Wooden Elevator or Industrial Elevator".

**Comment by Daniel-Magulado** [comment]
Hi @Valderg 

Thank you for writing this bug report.
Your suggestion request for the Wooden Elevator Call Post is already set and will be coming in the future game updates.
Hope you look forward to it.
Thank you.
