### ISSUE TITLE
USER ISSUE: Stockpile linking is per-player

### ISSUE THREAD

**Issue by janosdebugs** [StrangeLoopGames/EcoIssues#22493]
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Start a game with 2 players.
2. Join the same town
3. Link a stockpile to a campfire.
4. Start cooking one recipe (e.g. charred tomatoes) drawing from the stockpile.
5. Have the other player start a second recipe (e.g. charred fish) drawing from the stockpile.
6. Realize that the linking is per-player

**Expected behavior:**
Linking should be per-stockpile, not per player, to allow for collaborative crafting.

**Actual behavior:**
The stockpiles are linked per-player.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6896435/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6896436/Player-prev.log)

**Comment by D3nnis3n** [comment]
This works as intended.
