### ISSUE TITLE
[STAGING] Icon for Hanging Wood and Standing Wood signs not showing properly

### ISSUE THREAD

**Issue by m-r-Gamez** [StrangeLoopGames/EcoIssues#22496]
Version: Staging.
Description: Small Hanging Wood Recipe and Small Standing Wood Recipe icons in skill tree for Carpentry appear as basic salads icons.
![image](https://user-images.githubusercontent.com/4639977/127735801-e3b87b96-4422-4c29-b387-c9f10bba4306.png)

**Comment by Daniel-Magulado** [comment]
Hi @m-r-Gamez 

Thank you for writing this bug report.
The SLG Dev Team is currently aware of this issue and a fix is already set in the coming game updates.
Please look forward to it.

Merging this report with #22077.

Thank you,
