### ISSUE TITLE
USER ISSUE: Can't host world

### ISSUE THREAD

**Issue by Jakobanana** [StrangeLoopGames/EcoIssues#22494]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Try to host world

**Expected behavior:**
World gets hosted

**Actual behavior:**
Says "Connecting" forever

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide your log files to support@strangeloopgames.com as mentioned here:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

Please also include if you're trying to host an existing world or a new world.
