### ISSUE TITLE
USER ISSUE: some windows off screen

### ISSUE THREAD

**Issue by TwinVariable** [StrangeLoopGames/EcoIssues#22490]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**
game menu windows should be on screen	

**Actual behavior:**
Windows are off the screen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @TwinVariable

Thank you for raising this issue, 

Can you share screenshot or video of this happening on your end? This would help us understand this issue better.

**Comment by TwixterZ** [comment]
closing this issue as no further response received. 

if you are still facing this issue, please submit a new issue with evidences to help us investigate.
