### ISSUE TITLE
[0.9.3.6] Can place multiple stockpiles on top of each other

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22498]
A stockpile requires "solid ground", however apparently another stockpile beneath it counts as "solid ground", even though the stockpile on top is clearly not stable...

![grafik](https://user-images.githubusercontent.com/2777158/127778563-0eb2f4b8-a0bc-4558-9a9f-47b5686037ac.png)

**Comment by Daniel-Magulado** [comment]
Hi @Azzurite 

Thank you for writing this bug report.
We are currently aware of this issue so I'll be merging this report with #17741.

thank you.
