### ISSUE TITLE
USER ISSUE: Can't see any transaction history

### ISSUE THREAD

**Issue by Richardvd1** [StrangeLoopGames/EcoIssues#22506]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. open Y
2. hover / click on any wallet
3. See 'click to see history' 
4. nothing happens 

**Expected behavior:**
it should actually show the history

**Actual behavior:**
does nothing 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
not that I know of, playing on seaotter. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Richardvd1 

The transaction history which is accessible via the Economy Viewer only records your avatars' earnings and expenses.
I tested this on my end and it works for me. I recommend trying to make a currency transfer and see if the transaction history did not record it. I also recommend recording it as this will help us verify the issue.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response from the reporter.
Feel free to reopen it again if this issue still persists.
