### ISSUE TITLE
USER ISSUE: Inside Stone

### ISSUE THREAD

**Issue by WildTom1** [StrangeLoopGames/EcoIssues#22508]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Be in corner
have animal push in

**Expected behavior:**
Push me into the corner but not clip in the wall

**Actual behavior:**
cliped me into the wall

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @WildTom1 

Thank you for writing this bug report.
We are currently aware of the issues with animals and the chances of getting stuck in objects because of them.
I'll be merging this report with #21668 and a fix will soon be rolled out in the coming game updates.

Thank you.
