### ISSUE TITLE
USER ISSUE: Sudden crash while loading container

### ISSUE THREAD

**Issue by bpmckinnon** [StrangeLoopGames/EcoIssues#22502]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClauseTransport.get_Contents()
   at Eco.Core.Utils.CoreReflectionUtils.<>c__DisplayClass18_0`2.<FuncMethodHelper>b__0(TTarget target)
   at Eco.Core.Controller.ControllerManager.PackageProperty(IMvcNetClient boundClient, IController controller, ISyncPropertyInfo propertyInfo)
Outer Exceptions:
Error during packaging property 'NameToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Clauses' of 'Eco.Gameplay.Economy.Contracts.Contract'
Error during packaging property 'Contents' of 'Eco.Gameplay.Economy.Contracts.ContractClauseTransport'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @bpmckinnon 

May we know your complete PC specification as well as its operating system?
Are you experiencing this issue every game restart?
Is this the first time you'll be playing Eco?
Can you provide us with your saved file and game log files?

Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Daniel-Magulado** [comment]
Closing due to no reply from the reporter.
