### ISSUE TITLE
USER ISSUE: i got stuck

### ISSUE THREAD

**Issue by leomekteo2** [StrangeLoopGames/EcoIssues#22509]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
place a wall then a workbench beside it when you jump on between them you get stuck

**Expected behavior:**
just let me slide out

**Actual behavior:**
it made me stuck and this is only if you dont own the area

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file sorry cant find it

**Comment by D3nnis3n** [comment]
You can use the command /unstuck in the chat to free yourself.
