### ISSUE TITLE
USER ISSUE: Tutorial window is 8 characters wide on first run of client

### ISSUE THREAD

**Issue by sethveale** [StrangeLoopGames/EcoIssues#22501]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Hosted a new server to learn the game.
3440x1440 resolution - default settings from installing the game.
Changed to 2560 to see if it would fix it and it didn't

Edit: This was my very first time starting up the game client. After restarting the client once it is fixed.
I verified the game files prior to the second run of the game through steam and there was nothing wrong so this seems to be a first run problem only.

**Expected behavior:**
be wide enough to read

**Actual behavior:**
is 8 characters wide

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sethveale** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6915437/Player.log)

**Comment by sethveale** [comment]
Reloaded the game after looking at the log file (layers something something was missing) and it's fixed.
Additionally, the game looks a lot better - fonts are smoothed, FXAA is working, UI is fixed and scaled correctly etc etc.
Log from second run attached.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6915463/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @sethveale 

Thank you for writing this bug report.
A fix for this bug is already on its way in the coming game updates. I'll be merging this report with #21734.


Thank you.
