### ISSUE TITLE
TIMEOUT: Some players can connect via listing (if they first join another server) but not via continue or directly from the list

### ISSUE THREAD

**Issue by Zackey** [StrangeLoopGames/EcoIssues#22500]
We host a lightly modded server (please don't run away yet!) which is having issues with roughly 30-40% of the playerbase not being able to connect. Clients simply recieve a timeout error after a sucessful nat establishment and firewall punchthrough, but server logs indicate nothing is wrong. They can work around this issue by first joining another server, and then ours. 

Wireshark shows clearly on the client in question, that the connection does take place, but we only recieve one UDP packet with what looks like nothing in it. If required, I can post the wireguard log but privately to a dev (to protect my player)

To be clear, if any of the players having an issue simply join another server first from the direct list, then our server, they have no issues joining. 

I have confirmed no end to end connectivity issues or firewall configuration issues. Ports are forwarded and working (I am a junior network engineer IRL) 
![Successful firewall punchthrough from client](https://user-images.githubusercontent.com/5611682/127816027-7d425568-965a-416d-99a8-f5c6859d59c6.PNG)

Attached is a client and server log of the testing we did.

In addtion, this particular client is recieving a crash when doing the work around mentioned earlier. After the game crashes from joining our server after another one, it works just fine. This may be a red herring, or the core of the issue. I don't know.

Please can we get some support for this issue, as it has killed our population by quite a margin. 

Any issues let me know. 

Server is: eco.thesyndicus.org (OR: 203.86.204.182)
Feel free to join or request logs etc.

Mods:
-Nutriview
-ECO Cost calculator
-30 stack size on all carried items 
-3x air pollution 
-Laser/computer lab is more expensive 
-Discordlink 
-Chronicler
-EM Framework

[CLIENT LOG.txt](https://github.com/StrangeLoopGames/EcoIssues/files/6914880/CLIENT.LOG.txt)
[SERVER LOG.log](https://github.com/StrangeLoopGames/EcoIssues/files/6914907/SERVER.LOG.log)

[CLIENT CRASH.log](https://github.com/StrangeLoopGames/EcoIssues/files/6914984/CLIENT.CRASH.log)
[CLIENT CRASH DUMP.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6914985/CLIENT.CRASH.DUMP.zip)

**Comment by mirasrael** [comment]
Do you use RemoteAddress in Network.eco?

**Comment by Zackey** [comment]
> Do you use RemoteAddress in Network.eco? You can set your external IP there to avoid auto-discovery for IP which may get wrong IP address.

We do use RemoteAddress in Network.eco sir! Absolutely. We changed that day 1 of this issue. I can't possibly list all the things I've tried to get this resolved :) 

It's set to our static ip - which has never changed in the 3 years of the servers operation. Additionally as you can see from our firewall image, the client is hitting the correct address.

**Comment by Zackey** [comment]
Any ideas??

**Comment by mirasrael** [comment]
I reproduced the issue locally and debugged it. It seems like after NatPunch message from client server never respond back. For me it seems like something wrong with network configuration. Either firewall or network buffering issues or something blocking initial request and then blocks other requests from same port (may be antivirus?).
But if ping request send before NAT introduction then everything works fine. Actually you don't need to enter other server, but just need to open any screen where ping request will be send to your server. I.e. if you just go to Your Servers to see Recent list, then go back to Main menu and click Continue then it will work. But if you first try to connect and then go to Recent list you will see no ping for the server.

**Comment by Zackey** [comment]
> I reproduced the issue locally and debugged it. It seems like after NatPunch message from client server never respond back. For me it seems like something wrong with network configuration. Either firewall or network buffering issues or something blocking initial request and then blocks other requests from same port (may be antivirus?).
> But if ping request send before NAT introduction then everything works fine. Actually you don't need to enter other server, but just need to open any screen where ping request will be send to your server. I.e. if you just go to Your Servers to see Recent list, then go back to Main menu and click Continue then it will work. But if you first try to connect and then go to Recent list you will see no ping for the server.

I will do some more debugging, however I would like to point out that we did not have this issue before patch 9.3.6 release-235 
I've double checked the configuration, nothing's blocked and eco has admin / exceptions for it.

**Comment by mirasrael** [comment]
Nothing related to network was changed in 9.3.6 as far as I remember. Have one theory why it may happen.
It uses NAT punch though method to avoid problems when server not available directly. 
Idea is following: if server and client both doesn't have external IP then they only may be connected if establish connection from it's side. Using man-in-the-middle (master server) we can establish connection to this master server from both sides assuming port won't change when peers communicate with other servers (i.e. if I access google.com from a browser to receive results I need to allocate random port, say 2345, when I access microsoft.com I assume the browser will use same port for same page, but different target host). It isn't always true though (i.e. for symmetric NAT). But if it is true and if client send data to this port and server send data from this port to client port then connection will be established from one of peers and they can communicate directly.
And now the theory. When NAT negotiation starts server and client both send packets to each other, but if server has explicit remote endpoint then client will send to this endpoint, not to endpoint from which server connected to master server.
Now we have following endpoints:
SEP (Server End Point) - endpoint from which server connected to master server, it may have different port allocated on router for incoming traffic even if router configured to direct incoming traffic on port 3000 to the server endpoint. Basically it may have random port.
REP (Remote End Point) - endpoint which declared as remote for the server.
CEP (Client End Point) - same as SEP, but for a client.
For NAT Punch happens folllowing:
Client sends: CEP -> REP
Server sends: SEP -> CEP
If REP == SEP then all is fine, in most cases if SEP != REP it is fine as well, but probably depending on router configuration, hardware or software it peers SEP<->CEP and when traffic received from same CEP but to REP just drops it.
It describes why everything works fine after Ping request. Because Ping send one-way from client to server (CEP->REP) and makes proper peer REP<->CEP which then when NAT Punch happens accepts client request normally and initiates connection.

**Comment by Zackey** [comment]
> Nothing related to network was changed in 9.3.6 as far as I remember. Have one theory why it may happen.
> It uses NAT punch though method to avoid problems when server not available directly.
> Idea is following: if server and client both doesn't have external IP then they only may be connected if establish connection from it's side. Using man-in-the-middle (master server) we can establish connection to this master server from both sides assuming port won't change when peers communicate with other servers (i.e. if I access google.com from a browser to receive results I need to allocate random port, say 2345, when I access microsoft.com I assume the browser will use same port for same page, but different target host). It isn't always true though (i.e. for symmetric NAT). But if it is true and if client send data to this port and server send data from this port to client port then connection will be established from one of peers and they can communicate directly.
> And now the theory. When NAT negotiation starts server and client both send packets to each other, but if server has explicit remote endpoint then client will send to this endpoint, not to endpoint from which server connected to master server.
> Now we have following endpoints:
> SEP (Server End Point) - endpoint from which server connected to master server, it may have different port allocated on router for incoming traffic even if router configured to direct incoming traffic on port 3000 to the server endpoint. Basically it may have random port.
> REP (Remote End Point) - endpoint which declared as remote for the server.
> CEP (Client End Point) - same as SEP, but for a client.
> For NAT Punch happens folllowing:
> Client sends: CEP -> REP
> Server sends: SEP -> CEP
> If REP == SEP then all is fine, in most cases if SEP != REP it is fine as well, but probably depending on router configuration, hardware or software it peers SEP<->CEP and when traffic received from same CEP but to REP just drops it.
> It describes why everything works fine after Ping request. Because Ping send one-way from client to server (CEP->REP) and makes proper peer REP<->CEP which then when NAT Punch happens accepts client request normally and initiates connection.


What you are describing would only take place if ECO had an external master server to route against (which to be fair, it does and it has broken servers like this before) 

To test your theory, I have enabled UPnP which will allow total control of the eco server. Despite port forwarding a 1:1 static mapping (which every other game in my inventory is perfectly happy with) perhaps eco does not want to use port 3000. 

It has some weight, as the first thing the server did when it started was open port 33000. Perhaps this is an unlisted port that eco needs?

**Comment by Zackey** [comment]
@mirasrael 
Players are still dropped at the continue button just as before. 
I dont know what more I can do for ECO, it can open whatever port it wants and still does not work correctly.

**Comment by Zackey** [comment]
I have improved the issue by:

UPnP enabled with firewall responding to any port forward requests by eco (allowing whatever in, big security issue but anyways) 
And disabling remote address in the network config menu. 

This has allowed a player who had previously been unable to connect via continue to join. But with the following caveat: 

"works and its double loading, first connection gets dropped but it automatically tries to reconnect without outputting a error and the second connection always goes through"

This is still a far from ideal configuration / work around.

**Comment by SlayksWood** [comment]
will be fixed in 0.9.4

**Comment by Zackey** [comment]
Hi there, 

Good to hear it's not our fault & that it's to do with an issue which will be resolved in 0.9.4 
Do we have any idea when this vital fix will be released? Our player population has more then halved since this patch with the connection bug. It's difficult to run a community of players if they can't connect :(

I understand it takes time to fix things. If you could just give an idea of a rough timeframe that would go a long way to improve morale here 👍

**Comment by mattwithoos** [comment]
Just adding that we're experiencing it too. It seems the current wisdom is to make the network conditions as generous as possible for Eco.

What would be the most helpful is a clear indication (if possible and if time permits!) of exactly what Eco needs in the most ideal situations. What ports, what router/network configurations, etc. Right now I'm just shotgun scatter-shot'ing to fix and praying no one gets blocked again.
