### ISSUE TITLE
[Server Bug] Mortared Stone do not stay in inventory following order completion

### ISSUE THREAD

**Issue by nlep1367** [StrangeLoopGames/EcoIssues#22516]
*I think this issue is server related, as I play the host account on the PC version , but feel free to let me know if it is not the case; I will update this ticket.

OS : Microsoft 10 enterprise (10.0.17763)

When ordering stones at the masonry table (any type), they do not appear subsequently in any inventories close by (as listed by the masonry table's Storage).  This problem is not 100% reproducible, as I was able to create some mortared stones before experiencing the issue. It is not hard to reproduce, but I honestly do not know what suddenly triggers this problematic behavior.

Steps to reproduce : 
- Have a masonry table (Masonry skill level : 5)
- Link it to a small storage containing 1 full slot of rocks (limestones in my case), another slot full of Mortar, all other 2 slots are free.
- Run an order of Mortared stones.

Result : Mortared stones do not appear in the small storage. 

Additional Comments : 
- When closely looking while the table completes the mortared stone order, I noticed for a brief moment that a mortared stone would appear in one of my chest, but then would immediately disappear (even before I can click on it).
- I am the host of the world (only 1 other friend in the game with me online)
- If there is a known workaround for the moment, it would be nice to know; many rocks have been wasted to produce non-existent mortared stones by now. :(

Client version : 0.9.3.6 beta release-235

I hope this helps! :D

**Comment by nlep1367** [comment]
FYI, I found my temporary workaround : If my friend builds Mortared stones for me and then I put them in my inventories, they do not disappear. And when retrying to build my owns, it is now back to normal and I do not experience the issue for the moment.

**Comment by Daniel-Magulado** [comment]
Hi @nlep1367 

Thank you for writing this bug report.
It appears that the server and your client are having issues with syncing.
If you encounter this issue again, kindly provide us with a recorded video of the issue as it happens, the game log files, the server log files, and your save files.
To upload game log files, please follow the instructions here:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file. To upload world save files, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save.

I tried to reproduce the issue but I was not successful.

It would also helps us if you could indicate your systems complete specification such as processor model, RAM, graphics card, and internet speed.

Thank you.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
