### ISSUE TITLE
Little Trees don't seem to be growing (checked soil sampler horrendous hours) #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2251]
we have been chopping down trees all seems fine, little wild trees appearing but dont seem to be growing checked some with soil sampler, really horrendous hours, as you can see
![snap360](https://user-images.githubusercontent.com/29383891/30773897-0d8cdd00-a072-11e7-8916-0ecf0dc37ea0.png)
![snap361](https://user-images.githubusercontent.com/29383891/30773901-17f94ba2-a072-11e7-9762-430e266472ce.png)
![snap362](https://user-images.githubusercontent.com/29383891/30773905-24eb9f5e-a072-11e7-9625-aee93350e399.png)

**Comment by Conchipedia** [comment]
![snap363](https://user-images.githubusercontent.com/29383891/30773917-7f072c38-a072-11e7-85ec-ebd9f125bdff.png)

added this last one as all trees seemed to be birch but this is also for Cedar (didn't realise we cut any of those down)

**Comment by REPOSEECO** [comment]
180h to max !!  do you check if the time goes down ?

**Comment by Conchipedia** [comment]
ok, also this as well
![ice_screenshot_20170923-172116](https://user-images.githubusercontent.com/29383891/30773961-3d8a663e-a073-11e7-9761-425c3f9f8923.png)

it says chop off branches there isn't any

**Comment by Conchipedia** [comment]
![snap364](https://user-images.githubusercontent.com/29383891/30774020-2c297e4c-a074-11e7-9750-28e8063d0885.png)

yes the timer is going down this is the same little tree as first Snapshot

**Comment by Conchipedia** [comment]
also u cannot hit them with axe (as we used to be able to) to get rid of them , but you can dig up the dirt and they go.

**Comment by Conchipedia** [comment]
ok this is weird, just checked the same tree AGAIN, its now gone up 0.1 hours
![snap365](https://user-images.githubusercontent.com/29383891/30774167-11cb7d50-a076-11e7-9bfb-9c141ac61ade.png)

**Comment by SeanAtr0n** [comment]
Just chopped down a tiny tree and it took a bunch of swings, had to remove stump and turned into this:
![image](https://user-images.githubusercontent.com/774628/30890233-8583065c-a2e0-11e7-855d-12ad2413c2fc.png)

**Comment by metachronism** [comment]
this was an intentional change; tree full growth time changed from 1 day in ideal conditions to 5 days
