### ISSUE TITLE
Washing Machines sound

### ISSUE THREAD

**Issue by SVZh** [StrangeLoopGames/EcoIssues#22514]
The last update made washing machines sound so loud, it's almost impossible to be near a working washing machine. Could you lower it a bit, please? :)

Also wolf barking. Those two sounds are way too loud compared to the usual Eco sound levels.

**Comment by Daniel-Magulado** [comment]
Hi @SVZh 

Thank you for writing this report.
You can lower the in-game SFX volume on the settings. This should lower the volume of the wolf barking and the washing machine.

**Comment by SVZh** [comment]
Hello! I think you misunderstood me. Washing machines and wolves are too loud in comparison with other sounds in-game. So if I were to lower the overall sound volume - all other sounds will be too quiet.

**Comment by Daniel-Magulado** [comment]
Hi @SVZh 

Noted on this. I'll forward this to our development team so they can look into it further.

**Comment by freakydna** [comment]
Resolved: https://app.clickup.com/t/10591183/ECO-14532
