### ISSUE TITLE
USER ISSUE: Build TechTree

### ISSUE THREAD

**Issue by kodyroy** [StrangeLoopGames/EcoIssues#22517]
[log_210808111429.log](https://github.com/StrangeLoopGames/EcoIssues/files/6950170/log_210808111429.log)
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
1. Create new local world
2. Use command '/build techtree'

**Expected behavior:**
Tech Tree buildings load into world

**Actual behavior:**
The server crashes and the following error message popped up:
```
Failed to receive views from the server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have any mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @kodyroy 

Thank you for writing this bug report. However, we are currently aware of this issue.
I'll be merging this report to an earlier reported case. #21570
