### ISSUE TITLE
PROBLEMA DEL USUARIO: 

### ISSUE THREAD

**Issue by Beatriz155** [StrangeLoopGames/EcoIssues#22510]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Ha aparecido el siguiente error:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This means you entered a wrong username or password. If you have forgotten your password, you can use this URL to get a new one: https://play.eco/forgot

If you still have issues with logging in afterwards, please contact support@strangeloopgames.com and we'll sort it out :)
