### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by lesnic82** [StrangeLoopGames/EcoIssues#22515]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta staging-2077

**Steps to Reproduce:**

**Expected behavior:**
Version:** 0.9.4.0 beta staging-2077

**Actual behavior:**
no main menu picture, app version January 2018

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @lesnic82 

Thank you for writing this report.
This should be fixed by now with the latest staging version 2079.
I'll be closing this ticket but do not hesitate to file a new report if you even encounter any unusual in-game behavior.
