### ISSUE TITLE
USER ISSUE: Error while saving a land deed

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22519]
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
Don't know really, I edited a deed on the map and this exception happened exactly when saving it

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

Exception: InvalidOperationException
Message:Invalid Query - Query never existed or was already processed
Source:Eco.Shared

System.InvalidOperationException: Invalid Query - Query never existed or was already processed
   at Eco.Shared.Networking.RPCManager.HandleQueryResponse(BSONObject bson)
   at Eco.Plugins.Networking.NetworkServer.Eco.Shared.Networking.INetworkEventHandler.ReceiveEvent(INetClient client, NetworkEvent netEvent, BSONObject bsonObj)
   at Eco.Plugins.Networking.Client.<.ctor>b__71_4()
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

Happened on official server, I don't have any mods except maybe ones downloaded when I joined a modded server.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6961245/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @Azzurite 

Thank you for writing this report.
When this happened, are you playing on an online server hosted by other players?
Can you provide use your save file?
To upload save file, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Azzurite** [comment]
This was on Giant Panda.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23821
