### ISSUE TITLE
Trees are not being drawn Correctly they have gaps #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2252]
![snap369](https://user-images.githubusercontent.com/29383891/30774291-3d05bb82-a078-11e7-8f23-be2d36eff509.png)
![snap368](https://user-images.githubusercontent.com/29383891/30774297-5398563e-a078-11e7-9bcb-3373c01912f6.png)

Just noticed that the trees have gaps in them and that the branches are not joined to the main trunk (i only noticed this as i was doing #2251 issue, as i normally spend my life digging underground, so i think might be a possible link here ( i asked another player if he could see what i could and the answer is yes) i had also quit the game and come back and they still the same.

**Comment by Arend90** [comment]
trees can be removed by the "Hoe"  for 1 call

**Comment by REPOSEECO** [comment]
oh yes on the Marmot Server example at (325,65,750)

**Comment by Fank** [comment]
Not sure if migration issue from older alpha.6 staging versions but noticed this on Alpha.6
![image](https://user-images.githubusercontent.com/1900106/30979727-d7eadfba-a47e-11e7-8503-ea6a7b8be449.png)

**Comment by Fank** [comment]
Hm looks like its related to #2319 because after a reconnect:
![image](https://user-images.githubusercontent.com/1900106/30982226-09957860-a487-11e7-9672-9c58e8240e52.png)
