### ISSUE TITLE
USER ISSUE: Tutorial Text

### ISSUE THREAD

**Issue by FilixDark** [StrangeLoopGames/EcoIssues#22528]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
I just logged in, everytime the first tutorial screen is easy to read, the next is like 3 cm wide and wordwrap make it go beyond the bottom of the screen. I have to disconnect from the server every time I get a new Task to be able to read it. Higly annoying first time experience

**Expected behavior:**
It should be readable

**Actual behavior:**
text goes beyond screen borders

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I am sure the server has mods, didnt try without, just trying to follow your recommendation and choose a server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by FilixDark** [comment]
https://i.imgur.com/pDu16WD.jpeg

**Comment by Ry4ndrew** [comment]
@FilixDark Thank you for the report. This issue is fixed in 0.9.4 version with #20252.
