### ISSUE TITLE
9.4 staging 2086 some api rcon admin connected on my server

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22529]
I didn't set a password for rcon, so I thought it wouldn't be active, like description says. But someone connected this night to the server. Now I set a password for it to prevent people to connect over rcon.
![asdasdasdasds](https://user-images.githubusercontent.com/82637840/129518926-4acbd0d7-ba64-43f3-a252-74c80f3bdcba.JPG)

**Comment by M3n5ch** [comment]
[2021-08-16 00:50:55.594][ Info] --> api-rcon-admin logged in. 
[2021-08-16 00:50:55.594][ Info] --> api-rcon-admin logged in.

**Comment by Daniel-Magulado** [comment]
Hi @M3n5ch 

Thank you for writing this bug report.
Could you provide us with your server's complete log, game log files, and if possible, the saved world file of your server? This will help us further investigate this issue.

To upload world saved file, please follow the instruction here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

To upload game log files, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Lastly, to upload server log files, open the file location of the game and open the Eco_Data folder.
Open the Server folder and then open the Logs folder. Select the most latest file and upload it here.

**Comment by M3n5ch** [comment]
https://1drv.ms/u/s!Aj1HY4QC9oi7g4smmlsBbToNaNyk0w?e=c1zKkC
I just uploaded the files

**Comment by Daniel-Magulado** [comment]
@M3n5ch 

Thank you very much for providing the files. I've created a report about this and have forwarded this issue to our development team.

**Comment by D3nnis3n** [comment]
Fixed.
