### ISSUE TITLE
Crushing log

### ISSUE THREAD

**Issue by VolodymyrB** [StrangeLoopGames/EcoIssues#22523]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6986293/Player.log)

**Comment by VolodymyrB** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6986296/Player-prev.log)

**Comment by D3nnis3n** [comment]
Moved to clickup https://app.clickup.com/t/10591183/ECO-14671
