### ISSUE TITLE
Staging 9.4 2086 cannot place door on stone block

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22525]
![2021-08-15 (1)](https://user-images.githubusercontent.com/82637840/129475224-437504a9-fef7-403f-bad1-e11dbe6dd344.jpg)

Placing on wood block works, but not on stone block. Message says "Need solid ground to place"

**Comment by Daniel-Magulado** [comment]
Hello @M3n5ch 

Thank you for writing this bug report.
We are currently aware of this issue. I'll be merging this report with an earlier report of this issue.
#22336
