### ISSUE TITLE
(0.9.4.0 beta-staging 2087) DisplayMessage RPC error and chat in broken state

### ISSUE THREAD

**Issue by thomasfn** [StrangeLoopGames/EcoIssues#22537]
Unsure what the actual trigger is but after around 1 hour of play in a busy server like White Tiger, most chat notifications (like trades) stop working and the notifications bar at the top is spammed with "Failed to handle RPC method: DisplayMessage". This can be reproduced by just sitting in WT until it happens. The only way to restore normal functionality after it happens is to restart the client.

![image](https://user-images.githubusercontent.com/2463967/129759571-75a57d21-9267-4d25-8454-29f9b610256f.png)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7001363/Player.log)

**Comment by TwixterZ** [comment]
hi @thomasfn thank you for raising this issue, 
The recent fix comes with 9.4 Staging-2088 have fix this issue

**Comment by thomasfn** [comment]
I'm still experiencing this issue in 0.9.4.0 beta release-237.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7020686/Player.log)
