### ISSUE TITLE
Login Screen Crash To Desktop

### ISSUE THREAD

**Issue by Rustdog24** [StrangeLoopGames/EcoIssues#22536]
Every time I attempt to launch the game it instantly crashes to desktop. Posted this issue first on Steam discussions here: https://steamcommunity.com/app/382310/discussions/4/5015307809829993528/ file Dropping in files as requested by developer.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7000597/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7000598/Player-prev.log)

**Comment by Rustdog24** [comment]
This is happening again where the game will not load so, not understanding why it was closed without a proper response to the problem? The steam discussion was only marked as answered as the GitHub is supposed to be where I can get help for this issue which I have had no response or answer for why the game will not launch.

Sent from Mail for Windows

**Comment by D3nnis3n** [comment]
In this case, please send an e-mail to support@strangeloopgames.com as you were originally asked, containing your log files.
