### ISSUE TITLE
USER ISSUE: Crash when clicking inside of transaction menu

### ISSUE THREAD

**Issue by ACrazyCat1** [StrangeLoopGames/EcoIssues#22533]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta staging-2086

**Steps to Reproduce:**
1. look at a players transaction history
2. click on someone elses account inside of this menu
3. crash

**Expected behavior:**
It should show the account of the person you click, not crash.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key 'PersonalAccount' was not present in the dictionary.
Source:System.Private.CoreLib

System.Collections.Generic.KeyNotFoundException: The given key 'PersonalAccount' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Eco.Gameplay.Systems.TextLinks.ReferenceIDTranslator.GetLinkTarget(String linkId)
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.OnLinkClicked(String linkId, TooltipContext context)
   at Eco.Gameplay.Players.Player.HandleLinkClicked(String linkId, Boolean cntrPressed, Boolean shiftPressed, TooltipOrigin origin)
Outer Exceptions:
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, there are mods. haven't tested without them though.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@ACrazyCat1 thank you for raising this issue, this was fixed as of 9.4 Staging-2088
