### ISSUE TITLE
UI : Unable to edit sales list in store

### ISSUE THREAD

**Issue by GreybackCoder** [StrangeLoopGames/EcoIssues#22542]
Version : 9.4

The store sales list cannot be changed. The purchase list works fine.
The store in question has a fairly long list, but less than 100

Also, rendering of items in the list when scrolling sometimes fails, showing blank areas.

**Comment by D3nnis3n** [comment]
Hello,
have you tried if this also occurs on a newly crafted store?

**Comment by TwixterZ** [comment]
Closing this, as no response received.
