### ISSUE TITLE
ChatCommandService.cs Bug causes any CustomCommandProcessor to throw exception and not load.

### ISSUE THREAD

**Issue by FyreAus** [StrangeLoopGames/EcoIssues#22541]
In the method for replacing the Command Handler with a custom one, the method checks the parameters of the command handler for a User type. This needs to be updated to IChatClient type as this is now the delegate signature.

Line 30 ChatCommandService.cs - Delegate declaration
``` private Func<ChatCommand, IChatClient, bool>  commandProcessor```

Line 651 ChatCommandService.cs - parameter check will throw error as parameter is now of type IChatClient
```
 if (parameters[1].ParameterType != typeof(User))
throw new InvalidOperationException("Command processor method must take a User as the second argument.");
```

**Comment by WeaselDog** [comment]
Thank you for letting us know. We do have a fix ready for this that will make it into the next update.

**Comment by D3nnis3n** [comment]
This has been fixed in the meanwhile and is released.
