### ISSUE TITLE
USER ISSUE: cant join server

### ISSUE THREAD

**Issue by denkata10** [StrangeLoopGames/EcoIssues#22540]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
i click on a server to join and in is not allowing me

**Expected behavior:**
to join normally

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>Internal Server error, Trace ID: 00-f8a570a510bcc34fafc525273bcaaf83-768497eb8a5f0b43-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i dont have any mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please send an e-mail to support@strangeloopgames.com and make sure you have bought the game.
