### ISSUE TITLE
Localization on server changes language of client

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22549]
Actually the hole translations make no sense, because of the localization settings on server.
When I set Localization on Server in English and the Game client on German, then I will have a mix between english and german language. Same problem in the other direction with localization german and client in english.
Only if I change localization on server also on german, the hole game is in german language.

English/German mix
![2021-08-21](https://user-images.githubusercontent.com/82637840/130316040-5793936e-e78c-4daf-8855-a7ff5819d47b.jpg)

PS: After restarting game client in german, the language mix is still there, somethings really weird here.

**Comment by D3nnis3n** [comment]
This works as intended, server language is separate from the client language.
