### ISSUE TITLE
[0.9.4] Skill reset command bug

### ISSUE THREAD

**Issue by Smooblymoobs** [StrangeLoopGames/EcoIssues#22551]
Hi there,

We are reseting people's skills on our new 9.4 server and the "/skills reset" command no longer refunds the skillpoint, it just clears the skill. Meaning people are still level 1, but are without a point to spend until levelling up.

We also tried to fix this with the "/skills givepointsto" command but this doesnt doesnt send skillpoints, just XP.

Thanks,

Smoobs

**Comment by D3nnis3n** [comment]
This works as intended, it's nids-player manager that refunds the skillpoint, not our vanilla command.

**Comment by Smooblymoobs** [comment]
Is there a vanilla command intended to award lost skill points without levelup?

**Comment by D3nnis3n** [comment]
No, that is only possible with nid-playermanager mod currently.
