### ISSUE TITLE
[9.4.0] Seed craft time not reduced by Focused Workflow or Farmers Upgrade Module

### ISSUE THREAD

**Issue by Krukubar** [StrangeLoopGames/EcoIssues#22552]
Client : Steam - Windows 10
Version : 9.4.0 beta release-237

Expected behaviour : Skill and Module should reduce seed crafting time.
Actual behaviour : Skill and Module do not reduce seed crafting time.

Steps to Reproduce : 
1.  Have level 3 Farming
2.  Take Focused Workflow
3. Place Farmer's Table in suitable room alone.
4. Apply Farmers Upgrade module (Or don't as it's the same time either with or without)

Added Notes : It seems it's just the seeds craft time being affected, both material cost and non seed items on the farmers table are both reduced(Non seed both time and material reduced) Doesn't seem to be a UI issue as they are taking the stated 1 minute to craft. 

If I missed anything important please let me know, this is my first bug report.

Cheers

Edit : Changed client data

**Comment by aritchie05** [comment]
Can confirm, resource costs are reduced by Basic Upgrade but the craft time is always 1 minute for various seeds

**Comment by Daniel-Magulado** [comment]
Hi @Krukubar and @aritchie05 

Thank you for writing this bug report and confirming it.
I also can confirm that this issue is happening on the latest build.
I'll be writing a report about this and will forward it to our development team so they can roll out a quick fix in the next game update.

**Comment by SlayksWood** [comment]
fixed in 9.4.1
