### ISSUE TITLE
Random crashing to desktop

### ISSUE THREAD

**Issue by SybilGlendevon** [StrangeLoopGames/EcoIssues#22558]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7027937/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7027938/Player-prev.log)

Since the update crashing before and after accessing my dedicated server.

**Comment by SlayksWood** [comment]
@SybilGlendevon Thank you for the report. merged to #22539
