### ISSUE TITLE
For White Tiger

### ISSUE THREAD

**Issue by VolodymyrB** [StrangeLoopGames/EcoIssues#22559]
Suddenly my truck stopped to move on the highway crossroad when I come out it, it fell through the ground, under the water
The same was for the hero when I moved to my base.
So no my truck is underground underwater like the water level is 62, but my truck is 57.

**Comment by VolodymyrB** [comment]
2 others guys had this spot problem with the higway crossroad near Volody's

**Comment by D3nnis3n** [comment]
Related to bermuda issue, reported internally, hence closing.
