### ISSUE TITLE
USER ISSUE: Leaked water doesn't disappear

### ISSUE THREAD

**Issue by itumanov** [StrangeLoopGames/EcoIssues#22553]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
1) place water pump and connect it to water and power 
2) add few more output pipes to pump
3) launch pump
4) observe water flowing from pipe
5) water "pile" created from leaked water 
![Capture](https://user-images.githubusercontent.com/4203260/130333895-a7ec8d04-4277-4e31-96ee-8ea878d26bed.JPG)
![Capture](https://user-images.githubusercontent.com/4203260/130333936-2df8451f-25d0-4bec-8891-0953ac8efc62.JPG)

6) turn off pump

**Expected behavior:**
leaked water should disappear over time or could be pumped out

**Actual behavior:**
creates several cubes of water, which doesn't disappear. tried to connect pipe to it to drain, but water pile increased in size now. its near my house and still growing, I'm scared :)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here 
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7026158/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7026160/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @itumanov 

Thank you for writing this report. We are currently aware of this issue and will be merging it with an earlier report.
#22343
