### ISSUE TITLE
Law Passed that should NOT be allowed EVER!! #4c637828

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2256]
Someone on our Server made this law and it just got passed
![snap396](https://user-images.githubusercontent.com/29383891/30783138-03346f48-a136-11e7-9d2a-f2f831d836aa.png)

This leaves any server wide open to Griefers, Please do NOT make this possible!

at the moment the ONLY way i think to get rid of it is to get our Admin to remove the laws Server side (sadly he is AFK at the moment)

**Comment by Fank** [comment]
I can confirm it should only be possible that a given amount of such restricrictions can be active

**Comment by MarjieAVolk** [comment]
You can pass a law to repeal this law.  Also it is possible to pass laws to restrict who can propose laws.  So these things can help make this better.

But I will review how law voting works; maybe laws should need a server majority, like elections, so a single person can't just do this while everyone is away.

**Comment by Conchipedia** [comment]
would it be possible to implement like a whitleist for those that can propose laws?

**Comment by MarjieAVolk** [comment]
Possibly - I've been thinking about how to define 'citizenship', we can try to include a whitelist/blacklist option in the design of that, won't be for the Alpha 6 though.

I'm thinking for now I will have new servers start with a default law to restrict who can propose laws - possibly by amount of play time.

**Comment by MarjieAVolk** [comment]
I've added a default law, as described, and there should be plenty of support for customizing this how you want; more options will be added in the next release.
