### ISSUE TITLE
[Audio] Cricket Ambience Adjustment

### ISSUE THREAD

**Issue by NJAldwin** [StrangeLoopGames/EcoIssues#22566]
The cricket audio has an unpleasantly loud high pitch when played through a quality amplifier and speakers.  The sound can be adjusted with the Ambience slider, but lowering it to an acceptable level effectively mutes all other ambience sounds.  Please consider adjusting the cricket volume relative to the other ambience sounds, adding a low-pass filter, or otherwise attenuating this sound.

Here's a screen grab from a spectrum analyzer showing the high frequency peak, as audible sitting in front of my speakers.  The only difference between the red/upper line and the green/lower line is the position of the Ambience slider in an open game of Eco `0.9.4.0 beta release-237` while in an area with crickets.

![image](https://user-images.githubusercontent.com/145036/130534397-2a464176-5e60-42ac-93d1-093b708768bc.png)

After several hours playing in Eco, the noise can start to really ring in my ears, diminishing my enjoyment of the game 😞.  Hope something can be tweaked 😃.

## Relevant Context

The issue has been raised before.  A couple of years ago, "Master: cricket sound issues" ticket #13135 was closed as "Fixed" despite really being a wontfix per the comment noting that a sound pass would be done later.

Last year, the cricket sound was moved to Ambience: #17909 but I am not sure if that involved any other adjustments.  From what I can hear, it seems not.

**Comment by WeaselDog** [comment]
Thank you for letting us know and great graph to show the issue. We will make sure to take care of this.

**Comment by freakydna** [comment]
Fixed in svn develop commit #8880 - Notched out resonant frequency band with crickets in audio data.
