### ISSUE TITLE
USER ISSUE: Skid Steer Mining

### ISSUE THREAD

**Issue by jensen040** [StrangeLoopGames/EcoIssues#22560]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
Mine with skid steer

**Expected behavior:**
Mined the blocks like the past update

**Actual behavior:**
It takes an eternity and some adjustment to the skid jsut to get it to mine the blocks. It just touches the stones. Like its 1000ping

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Playing on slightly modded server but i heard many others have same issue on other servers. And idk

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @jensen040 

Thank you for writing this bug report.
I tried to reproduce this issue by mining using a Skid Steer but it seems everything works fine on my end. I am able to mine as fast as how Skid Steer was on the previous version of the game.
Could you provide us with more information?
- Please provide your game log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file.
- We would also like to request that you provide us with a recorded video of the issue as it happens. This will help us in our investigation.
- Please also provide a screenshot of your latency with the server you are playing on.

**Comment by irose999** [comment]
I've been having the same issue on 9.4. I also play on a modded server, but the only things modded with regard to the skid steer are stack sizes and number of slots. 

Video of issue (I was holding left click for the entire duration):
https://drive.google.com/file/d/1kQjPmWLF0ISSEilJF6YLu9E2Ss1sBJr8/view?usp=sharing

You can see at various points during the video that digging abruptly stops. I was still holding left click at these points. It wasn't until I backed up and then proceeded forward that I was able to dig more of the blocks out.

Image of latency:
https://drive.google.com/file/d/1IrPmw-QQhFK0rQ5ErXROBPl5QxsuoW91/view?usp=sharing

Log Files:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7071650/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7071651/Player.log)

**Comment by D3nnis3n** [comment]
We've been able to reproduce this issue and it's logged internally.

https://app.clickup.com/t/10591183/ECO-14769

**Comment by Daniel-Magulado** [comment]
Closing. A fix is set to be rolled out in the upcoming game updates.
