### ISSUE TITLE
0.9.4: Projects started on table by authorized non-owner, don't have access to stockpiles that non-owner DOESN'T have auth on  

### ISSUE THREAD

**Issue by PhoenixBirdWingQc** [StrangeLoopGames/EcoIssues#22569]
Eco Version: 0.9.4.0 beta release-237

Issue: Found on public community server on Aug. 23: nhstoner-eco.nodecraft.gg

Owner of a table gave me authorization on the table. I (authorized, non-owner) started a project on the table and provided all labor (but did not check that materials/ingredients were provided in any linked stockpiles). Later, we found the project remained halted because I didn't have authorization on stockpiles the owner had linked to the table (those stockpiles had all material needed for the project). On the owner's screen (streamer), he had made sure all stockpiles with needed material were linked to the table for the project - but the project remained halted. Once he gave me authorization on the stockpile, I saw it pop up in the 'Storage' tab for the table (displayed as unlinked). I then had to link the stockpile (on my screen) and move needed material from one slot to a neighboring one; then the project resumed. 

Expected Result: Projects started on table by non-owner should still be able to draw from linked storages that the table owner has access to (even if project starter doesn't have auth on those storages).

Steps to reproduce (re-counted from our specific use case):
1. Owner (of property and Kiln) added me (non-owner of property and Kiln) to authorization list for Kiln
2. I started a Glass Project for 120 glass and provided all labor (I didn't check status of linked stockpiles and contents)

3. Later, owner (streamer who's screen I could observe) found that the Glass Project was halted (on 1 out of 120); the halted project indicated that both sand and crushed limestone were missing. 
4. Owner checked that 2 stockpiles were already correctly linked to the Kiln (only 1 stockpile contained sand and crushed limestone needed for project)
5. I viewed the 'Storage' tab of the Kiln and saw only 1 stockpile was available and linked to the Kiln (this was the stockpile without either sand or crushed limestone) - i.e. I was only authorized on the one stockpile that didn't contain the needed materials
6. Owner then authorized me on the other stockpile containing crushed limestone and sand
7. I saw this stockpile pop-up in the 'Storage' tab of the Kiln, un-linked.
8. I linked this stockpile to the Kiln, and dragged sand and crushed limestone to neighboring empty slots within the stockpile
9. Project resumed and was no longer halted.

Additional Note: Between steps 2 & 3 - it's possible I was authorized on all stockpiles linked to the Kiln before starting the Glass Project and providing all labor; at the time, none of those stockpiles contained crushed limestone or sand needed by the project. The owner may have then picked up all but 1 stockpile and placed it back down, removing my authorization on all but 1 stockpile. Just adding this note in case Steps 1-9 don't reproduce the issue.

There's also a Twitch VOD demonstrating this - I don't know how useful it will be given that it only captures the owner's screen but not mine (non-owner of Kiln, but owner of Glass Project).
https://www.twitch.tv/videos/1127557181  (start 2:38:25)

slgid: slg207272
SLG Discord: Amblix1108 (Nickname: PhoenixBirdWing [Qc])
In-game/Steam Name: PhoenixBirdWing [Qc]

**Comment by D3nnis3n** [comment]
Thanks for the report - this behaviour is intended, the project starter needs to link stockpiles, as they are configured per user, this is necessary to support authorization like public tables for a fee or fine-grained control where specific players do have access to stockpiles nearby and others do not.
