### ISSUE TITLE
Hand powered carts can't make it up ramp 

### ISSUE THREAD

**Issue by Hecfret** [StrangeLoopGames/EcoIssues#22562]
Both the small cart and regular cart will be going too slow to make it up dirt or stone ramps after I let got and re grab it will very slowly crawl up

**Comment by Xenoamor** [comment]
I've found this, without a 3 block run up you can't get up them

**Comment by Daniel-Magulado** [comment]
Hello @Hecfret and @Xenoamor 

Thank you for writing this bug report and confirming it.
We are currently aware of this issue with carts having difficulties going up ramps.
I'll be merging this report with an earlier report at https://github.com/StrangeLoopGames/EcoIssues/issues/22545.
We will be working on a fix that should soon be rolled out in the next game updates.
Please look forward to it.
