### ISSUE TITLE
USER ISSUE: stuck in wall

### ISSUE THREAD

**Issue by BenHaze122** [StrangeLoopGames/EcoIssues#22564]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
build wall while stuck in other wall croner

**Expected behavior:**
pushed me out of the way

**Actual behavior:**
got stuck couldnt get out

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, server has "qol" mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi, @BenHaze122.

thank you for raising this issue, I have not been able to reproduce the same issue at my end, 
Are you able to provide screenshot or even better a video of this happening at your end? this would help us understand the issue better.

**Comment by D3nnis3n** [comment]
For the meanwhile, if you ever happen to have this issue again, please use /unstuck in the chat to free yourself.
