### ISSUE TITLE
USER ISSUE: Run into vehicle bug - "Truck"

### ISSUE THREAD

**Issue by RuanFarquhar** [StrangeLoopGames/EcoIssues#22573]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
Run into your vehicle from certain angles and youll see that you will flip your truck on its side - might be related to jumping onto your truck when it has a load or no load - the car will fall over at certain angels 

**Expected behavior:**
It must be like real life and the car should not move

**Actual behavior:**
it rolls over on its side at stages

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @RuanFarquhar 

Thank you for writing this bug report. However, we are currently aware of this issue. So I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/14761
