### ISSUE TITLE
Cannot Load any worlds following 9.4 Update.

### ISSUE THREAD

**Issue by AdmiralYuzuki** [StrangeLoopGames/EcoIssues#22570]
I recently started a new world on 9.3 and was getting the groundworks to my city going and stopped for a few days to do other things. When I heard the 9.4 update came out, I went back to continue my world (and in the event it didn't load, start a new one) but it keeps giving me a connectivity error stating that the "Auth servers might be down" but I'm not sure how that can be when other players seem to playing fine (and having their own in game issues nonetheless). This happens with all currently existing and freshly made worlds

Do keep in mind I have freshly reinstalled the game and have made NO modifications to the games files other the copy and past of my worlds to the desktop (which probably doesn't count)

I have attached a log that it presents me when the error occurs.
[log_210824124343.log](https://github.com/StrangeLoopGames/EcoIssues/files/7037439/log_210824124343.log)

**Comment by PixlRainbow** [comment]
I am also having this problem, seems to only affect local worlds. I guess it might be that the local server is unable to contact the regional auth relay (for me, Southeast Asia), but the official SLG servers continue to work because they are in Europe and those can connect to the EU auth servers.

**Comment by D3nnis3n** [comment]
Please contact support at support@strangeloopgames.com with your logs :)
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
> I am also having this problem, seems to only affect local worlds. I guess it might be that the local server is unable to contact the regional auth relay (for me, Southeast Asia), but the official SLG servers continue to work because they are in Europe and those can connect to the EU auth servers.

This is very likely, we do not have regional auth servers - there have been issues in the past with Asia region not being able to use our auth server due to provider restrictions, in such cases only a VPN can help, but we can take a look on this via support, it's not likely to be a bug though.
