### ISSUE TITLE
user friendliness --> UserProperty Claim Flag & Construction Post have the Same Icon

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2257]
![grafik](https://user-images.githubusercontent.com/26040573/30783444-39faa1b6-a143-11e7-839e-28058765fe8d.png)
Change Color form the ring for example

**Comment by Frozen-byte** [comment]
same is for Tech-Receipts they look all the same.
Hard one to spot one specific.

**Comment by keegan-o** [comment]
hooked it up
