### ISSUE TITLE
[0.9.4.0-Linux] Can't adjust gpu memory limit in settings

### ISSUE THREAD

**Issue by 99thGamer9** [StrangeLoopGames/EcoIssues#22572]
There is a Slider to adjust the Gpu memory limit but the value and slider are just stuck at 2,0GB

**Comment by PixlRainbow** [comment]
related to #20298

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20298
