### ISSUE TITLE
USER ISSUE: When crossing 0 point of the map entities fall through the ground

### ISSUE THREAD

**Issue by JU11111** [StrangeLoopGames/EcoIssues#22575]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.0 beta release-237

**Steps to Reproduce:**
cross 0 point of coordinates	

**Expected behavior:**
nothing should happen

**Actual behavior:**
The cars and several entities just fall through the world and players can fly and bug around.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @JU11111 

Thank you for writing this bug report. However, I can't seem to reproduce this issue on my end. I am able to pass through any 0 coordinates without any issues. Can you provide us a recorded video of the issue as it happens?

**Comment by Daniel-Magulado** [comment]
Merging this to an earlier report - https://github.com/StrangeLoopGames/EcoIssues/issues/22568
