### ISSUE TITLE
9.4 Issue Renting car 

### ISSUE THREAD

**Issue by Koriclo** [StrangeLoopGames/EcoIssues#22589]
User Id: [CRG]Kori
Version: 0.9.4.1 White tiger

Steps to Reproduce:

    Go in car property
    Set the rent for everyone
    Another rent the car 

Expected behavior:
Tenant take the car and drive it, can use it to transport  log or dirt.

Actual behavior:
Tenant isnt able to drive or acess to inventories, got the "not authorized" message

**Comment by Maistho** [comment]
I've seen the same issue with renting a Skid Steer as well, so it is probably all vehicles.
