### ISSUE TITLE
Quicklime glass no longer giving 2.

### ISSUE THREAD

**Issue by Chickenw** [StrangeLoopGames/EcoIssues#22581]
User Id: (Not logged user)
Version: 0.9.4.0 beta release-237

Steps to Reproduce:
Go to the Kiln and Check Quick limeglass Should be giving 2.

Expected behavior:
In 9.3 Quicklime glass gave 2. In 9.4 its only giving 1 which doesn't make it worth to craft. 

Actual behavior:
Only gives 1 quicklime glass.

Do you have mods installed? Does the issue happen when no mods are installed?:
No mods

**Comment by TwixterZ** [comment]
hi @Chickenw, thank you for reaching out. This however, is an intended change that comes with update 9.3.6
