### ISSUE TITLE
[Client] 9.4.1 Environment statistics missing from web interface

### ISSUE THREAD

**Issue by Xenoamor** [StrangeLoopGames/EcoIssues#22582]
The "Pre-Made Graphs" "Air Pollution" option in the web interface no longer functions and clicking it does nothing:
![image](https://user-images.githubusercontent.com/7109951/130764558-85b23762-fabb-4eb5-adf6-cfd0f8f27265.png)

There is also lots of statistics missing from the Environment tab:
![image](https://user-images.githubusercontent.com/7109951/130764630-44c0fc9c-eb89-4795-8012-cc32b710f5c8.png)

Here is how it looked on 0.9.3.6:
![image](https://user-images.githubusercontent.com/7109951/130764777-8a5e70c6-acec-4bb3-86eb-3ff0552bec64.png)

I have tested this on two different servers so I believe it is not a server issue

My user id is: slg204596

**Comment by Daniel-Magulado** [comment]
Hello @Xenoamor 

Thank you for writing this bug report. We are currently aware that some data are missing on the Election web UI. Developers are already looking into this. We'll keep you updated once the earlier report gets an update.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14740)

**Comment by Daniel-Magulado** [comment]
Closing this report. A fix is set to be rolled out in the coming game updates.
