### ISSUE TITLE
USER ISSUE: неисправность погрузчика

### ISSUE THREAD

**Issue by xKriGx** [StrangeLoopGames/EcoIssues#22586]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
добыча на погрузчике

**Expected behavior:**
в прошлых обновлениях копал на 1 блок вниз при максимально опущеном ковше, не упирался в блоки при добыче

**Actual behavior:**
не копает на 1 блок вниз при максимально опущеном ковше, упирается в блоки при добыче

**Do you have mods installed? Does the issue happen when no mods are installed?:**
нет, да. ссылка на видео с демонстрацией https://youtu.be/zzf_LN5HwsU

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/22560

**Comment by Daniel-Magulado** [comment]
Hi @xKriGx 

Thank you for writing this bug report.
I'll be merging this report to an earlier report with https://github.com/StrangeLoopGames/EcoIssues/issues/22560.
