### ISSUE TITLE
USER ISSUE: Action after clicking out of UI

### ISSUE THREAD

**Issue by darkhouse54** [StrangeLoopGames/EcoIssues#22583]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Open UI where you have mouse pointer.
Close UI by clicking outside the UI and into the "game world" while having a tool equipped and selected.

**Expected behavior:**
Close UI and remove mouse pointer without triggering the tool use action. 

**Actual behavior:**
Closes UI, removes mouse pointer, and uses the current selected tool. (IE: Hammer removing a block)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods and yes it happens.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @darkhouse54 

Thank you for writing this bug report.
I can confirm that there is an extra action occurring upon clicking outside the UI.
I'll go ahead and write a report about this so our development team can look into it further.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14823)

**Comment by Daniel-Magulado** [comment]
Internally Reported. Closing.
