### ISSUE TITLE
Bakery Oven does not show up on the store list or the economy viewer.

### ISSUE THREAD

**Issue by TeppyTV** [StrangeLoopGames/EcoIssues#22580]

**Comment by TwixterZ** [comment]
hi @TeppyTV 

thank you for reaching out to us for this issue, I have tested this in release version and I find them working as intended

in scenario where bakery oven is yet to be discovered, you need to select "Show Undiscovered" for it to show in the list.
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/7e537671-4ea
4-499d-a259-5c8a0ced86c2)

**Comment by TwixterZ** [comment]
please let us know the above does not help with your situation and share us your save file for us to investigate further

**Comment by TwixterZ** [comment]
Closing this issue as no further response received
