### ISSUE TITLE
Alpha.6 [4c637828] >1 refund rate will cause negative skill points

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2259]
Current:   
![image](https://user-images.githubusercontent.com/1900106/30784833-0a4456fa-a15d-11e7-8724-19e325b6104a.png)

Lower Basic crafting:   
![image](https://user-images.githubusercontent.com/1900106/30784851-518023d2-a15d-11e7-9e96-e9ddcd0cda87.png)

Higher negative skill points:   
![image](https://user-images.githubusercontent.com/1900106/30784869-84948b32-a15d-11e7-9695-b14a99dfc1a7.png)

Higher Basic crafting:   
![image](https://user-images.githubusercontent.com/1900106/30784873-9327cfd8-a15d-11e7-9625-2902be0f00eb.png)

Should be same as current, but don't:   
![image](https://user-images.githubusercontent.com/1900106/30784881-a96d5bfa-a15d-11e7-8738-ba0e980a5a62.png)

**Comment by johnkslg** [comment]
Fixed, once I can push
