### ISSUE TITLE
USER ISSUE: Can't log into local server

### ISSUE THREAD

**Issue by Chandestra** [StrangeLoopGames/EcoIssues#22599]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Try to log into a local server

**Expected behavior:**
Start the game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7069042/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7069043/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please contact support at support@strangeloopgames.com with your logs :)
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
