### ISSUE TITLE
Users can only propose one law, and the server should inform the user of the failure if they try to do a second

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#226]
Currently it fails with 'undefined'.  In fact it should always show the error result rather than undefined.

{message: "User already has a law being proposed."}
message
:
"User already has a law being proposed."

**Comment by johnkslg** [comment]
I notice if attempting to create a law with no authentication, it also fails with 'undefined'

**Comment by johnkslg** [comment]
Also fix: the username is not being propoaged to the AddLaw call

**Comment by rainfarmer** [comment]
Are these errors when making laws from the web browser or the game?
