### ISSUE TITLE
USER ISSUE: Cant see when player removes clothes

### ISSUE THREAD

**Issue by JamesCliffwood** [StrangeLoopGames/EcoIssues#22604]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Have a friend in a hosted game remove an item(s) of clothing

**Expected behavior:**
I should see this player remove their clothing and see their character update accordingly	

**Actual behavior:**
Instead I see the players original character, no change to their player

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7070603/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7070604/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @JamesCliffwood 

Thank you for writing this bug report. We are currently aware of this issue.

**Comment by Daniel-Magulado** [comment]
[ClickUp](https://app.clickup.com/t/10591183/ECO-14389)
