### ISSUE TITLE
USER ISSUE: Roots to strong

### ISSUE THREAD

**Issue by McScrew1** [StrangeLoopGames/EcoIssues#22606]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Don´t know

**Expected behavior:**
be able to remove or place a block at the end of my first dirtroad		

**Actual behavior:**
can´t remove ore place block

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PixlRainbow** [comment]
if you see a tree or the leftover stump of a tree or cactus, you have to chop them up to remove the roots first

**Comment by Daniel-Magulado** [comment]
Hi @McScrew1 

Thank you for writing this bug report.
Could you provide a screenshot of the issue?
Furthermore, kindly provide us with a complete specification of your system including its operating system.

**Comment by TwixterZ** [comment]
@McScrew1 please provide further information to your issue for us to help you with. 
unless like mentioned by PixlRainbow above that there is a tree stump close by that preventing you from removing dirt, this would be intended purpose.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
