### ISSUE TITLE
USER ISSUE: Rounding Error

### ISSUE THREAD

**Issue by calculusfish** [StrangeLoopGames/EcoIssues#22601]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Made various transactions with a particular store for the player's credit. The reported amount of credit was 129. 
2. Then, sold 77 plant fibers at 0.2 credits/fiber. Transaction cost is listed as 15.4 credits (correct), but balance was then listed (incorrect) at 144.39 credits. (There are no relevant taxes). 

Probably something to do with floating point errors - good luck with that!

**Expected behavior:**
Balance after selling the plant fibers should have been 144.4. 

**Actual behavior:**
Balance after selling the plant fibers was 144.39.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. 

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7070061/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7070062/Player-prev.log)

**Comment by Xenoamor** [comment]
They should use a fixed point class implementation to replace the floats used for currency. Probably with bankers rounding or something

**Comment by Daniel-Magulado** [comment]
Hi @calculusfish 

Thank you for writing this bug report. I can confirm that this issue is happening.
I've created an internal report about this.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14933)

**Comment by D3nnis3n** [comment]
Already fixed.
