### ISSUE TITLE
USER ISSUE: "Quit" button in settings, wrong behavior

### ISSUE THREAD

**Issue by Djekke** [StrangeLoopGames/EcoIssues#22608]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Open settings
2. Press "Quit" button

**Expected behavior:**
Exit settings to main menu

**Actual behavior:**
Exit game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PixlRainbow** [comment]
The settings menu is an overlay over the top of the game. It is not part of the main menu or a submenu of the main menu; it is the same menu that shows up when you press "Esc" while in a world. Pressing quit is intended to exit straight to desktop. When you are in-world, a "disconnect" button will also appear which will leave the server and return to main menu.

I think the button should be more specifically labelled as "Quit to Desktop" though. And pressing escape again should not be the _only_ way to close the settings overlay, there should be a UI button for that as well.

**Comment by D3nnis3n** [comment]
That's correct, this is working as intended, but we should definitely introduce dedicated buttons to close menus, there is already a suggestion open for that here, though: https://github.com/StrangeLoopGames/EcoSuggestions/issues/1515
