### ISSUE TITLE
Stockpile selection as a resident

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#22607]
I'm playing ECO with a friend and we are colaborating. 
I'm a resident on his deed.
Once he start a work on a table/machine... the Stockpile selection that I do doesn't take effect.
Only the stockpile selection that HE does.
Example.
We have a stock pile with the resources that we need for the stampmill work and a Stampmill.
At the time he create the work on the Stampmill the stockpile wasn't selected (checked) once we access the machine and go to the STORAGE tab.
If I go to the machine and select the stockpile... the machine doesn't start the work.
Since HE was the one that started the job HE must go there and select the stock pile. Only on that moment the stampmill will start work.

What I can see here is that Stockpile selection is based on USER not on DEED.
I think this is a bug. I think that a player that configure a machine to work with the storage shouldn't be associated with the one that started/requested the job into the machine/table.

**Comment by D3nnis3n** [comment]
This works as intended, the selection is based on the user to allow fine-grained permissions, as crafting tables can be made public for a fee and players may wish to authorize specific stockpiles to only specific people.
