### ISSUE TITLE
USER ISSUE: Cant see bow aiming animation with friends

### ISSUE THREAD

**Issue by JamesCliffwood** [StrangeLoopGames/EcoIssues#22603]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Have friend aim a bow and arrow

**Expected behavior:**
I should see the same animation as my friend does on his screen.

**Actual behavior:**
I see no animation at all, only hear the sound

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @JamesCliffwood 

Thank you for writing this bug report.
I can confirm that bow aiming animation is not prompting on other players' screens. This issue also affects all tool animation excluding emotes.
I've created an internal report about this.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14917)

**Comment by Daniel-Magulado** [comment]
Hi @JamesCliffwood 

A fix is already set to be rolled out in the coming game updates. Please look forward to it. Closing this report.
