### ISSUE TITLE
[Client] (Eco 9.4.1) Passing a certain block line will cause trees and vehicles to disappear and the character starts floating

### ISSUE THREAD

**Issue by AbandonLandon** [StrangeLoopGames/EcoIssues#22617]
This happens every time I travel across a certain coordinate. If in my truck I get teleported and stuck seeing the earth, but my Y level stays the same and /unstuck doesn't work, the only way to fix is to cross back the same line on the other side. If on foot when crossing the same block, you go up like 4 blocks and every time you press spacebar you go up one block, trees, vehicles and certain plants disappear. I can't go towards my oil field, nor my mines because this happens.

I for some reason can't drop files, so I clipped on medal and then put two links, they are the following.

https://medal.tv/clips/63360156/d1337oTPk8FI  - This was when it first happened

https://medal.tv/clips/63360435/d1337l1g8Q9n  - And this is me replicating the glitch a few short moments after

After both these clips, we restarted the server and I was able to pass through fine, but the next time I went back it happened again. I have not had any of my friends try and pass through this area.

**Comment by Daniel-Magulado** [comment]
Hi @AbandonLandon 

Thank you for writing this bug report. We are currently aware of this issue and I'll be merging this report to an earlier submitted report at https://github.com/StrangeLoopGames/EcoIssues/issues/22568.
