### ISSUE TITLE
World map shows up in light blue

### ISSUE THREAD

**Issue by Dennis1108** [StrangeLoopGames/EcoIssues#22610]
whole World Map shows up in light blue. Layers still working.
To solve the problem game need a restart.

![2021-08-29 17_40_44-Eco](https://user-images.githubusercontent.com/48776335/131256584-7fe3e775-cc0b-4fe3-9693-3aabc5ca81e0.png)

**Comment by Daniel-Magulado** [comment]
Hello @Dennis1108 

Thank you for writing this bug report.
We would like to request more information from you about this issue.
1. Kindly provide us with your complete PC specification including the operating system and its version.
2. Please upload the game logs. This will help us further investigate this issue.
3. How frequently do you encounter this issue?
4. Any prior activity in-game before you first noticed this issue?
5. If you can reproduce this issue, could you provide us with steps or a recorded video of it? If so, please upload it here.

Looking forward to your reply.

**Comment by TwixterZ** [comment]
Closing issue due to no response received
