### ISSUE TITLE
USER ISSUE: Sand that is not sand

### ISSUE THREAD

**Issue by MrPOG878** [StrangeLoopGames/EcoIssues#22612]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**

**Expected behavior:**
If you break sand, you get sand. Common sence.

**Actual behavior:**
Not in Eco. In Eco, only sometimes you get sand. However if you break desert sand or ocean sand, you get dirt! This is dumb.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Hello, thank you for your report. However this is working as intended as detailed inside the descriptions of the different types of sand.
The "Sand" used for glass-working and mortar is a specifically fine sand with high concentration of silicates and quartz based materials necessary for these products which normal "Sand/Dirt" does not contain as they are very contaminated by other materials such as silt, clay and gravel.
