### ISSUE TITLE
[0.9.4.1 beta release-242] Invisible Players

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#22611]
Myself and a number of other players on our server have noticed that every so often, you will find that when another player is talking to you in VoIP, they are invisible for you. If you check the map it shows their location as somewhere else, specially where they were a short while before they moved to your current location. I did discover if you move away from them and then move back the world will update their location and you will be able to see them again.

 If I was to make a guess it might have something to do with the change the game loads world chunks, as none of us have ever experienced an issue like this before (having played the game since 9.2), and how it seems to be a update issue.

**Comment by fighter777** [comment]
I confirm, and other objects like workshop, stockpile or cart can also be invisible and that with a rate configuration of 20.

When a player passes through your cart without seeing you, it flies in the background

**Comment by Crazy-Spy** [comment]
I also confirm this behavior. More than once we need to re-join the world to be able to see other players.

**Comment by Daniel-Magulado** [comment]
Hello @Dave247 , @fighter777 and @Crazy-Spy 

Thank you all for taking the time to write and confirm this report. We are currently aware of this issue and it has been internally reported. I'll be closing this ticket but if you guys would like to share a recorded video and game/server logs, we will highly appreciate it and thank you in advance for setting aside some time to do it.

**Comment by fighter777** [comment]
what server/client you need ?

**Comment by Dave247** [comment]
> Hello @Dave247 , @fighter777 and @Crazy-Spy
> 
> Thank you all for taking the time to write and confirm this report. We are currently aware of this issue and it has been internally reported. I'll be closing this ticket but if you guys would like to share a recorded video and game/server logs, we will highly appreciate it and thank you in advance for setting aside some time to do it.
> 
> [ClickUp Report](https://app.clickup.com/t/10591183/ECO-14759)

Will do, though I'll send my logs via email just as a precaution due to containing player IP addresses.

**Comment by fighter777** [comment]
![image](https://user-images.githubusercontent.com/5146649/131488021-a0af8817-3fbd-4dc2-ba6d-c3755a2fe243.png)
Hello, a visual example of a bug loading a stockpile
