### ISSUE TITLE
USER ISSUE: Completing Food tutorial leaves food node waypoints

### ISSUE THREAD

**Issue by Narananas** [StrangeLoopGames/EcoIssues#22614]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Do 'Food' tutorial
2. Tutorial provides waypoints to food nodes e.g. 'Bolete Mushrooms (931m)'
3. Collect food from different nodes to the ones directed by tutorial
4. This satisfied the tutorials requirements and completes the tutorial	

**Expected behavior:**
Cleared the food node waypoints e.g. 'Bolete Mushrooms (931m)'

**Actual behavior:**
The waypoints remain, even after restarting the game, e.g. 'Bolete Mushrooms (931m)'

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes there are plenty of mods installed. I am new and have not tried a non-modded world. This server is 9.3.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @Narananas , thank you for reporting this. However, we are unable to reproduce this issue.
Could you provide additional information such as a recorded video of the issue as it happens and the latest game log files after the issue occurred? This will help us investigate the issue further.

To upload game log files, please follow the instructions here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Narananas** [comment]
Hi, a few things:
This was actually 9.4, sorry.
I discovered I can just click on waypoints to delete them so that was a solution to them being there.
To test my issue though, I'd have to make a new character or go through the tutorial again if possible, and try on a non-mod server. If I get around to that, I can make the report again then, and include video/screenshots/logs.
