### ISSUE TITLE
Alpha.6 [4c637828] Server crash by shooting a bison in water

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2261]
![image](https://user-images.githubusercontent.com/1900106/30805973-2bdb82a6-a1f4-11e7-8b15-0e190e91d5bc.png)

My last action was shooting a Bison which walked into the water:   
![image](https://user-images.githubusercontent.com/1900106/30805985-42e042a2-a1f4-11e7-9d42-d62d49753668.png)

The other guy on the server cut down some trees.

**Comment by MarjieAVolk** [comment]
Uh, have any stack traces or anything?

**Comment by Fank** [comment]
Nothing, only the 1. pic sorry

**Comment by MarjieAVolk** [comment]
Rough.  I'm thinking we can't really do anything with just this, but just in case, assigning :P

**Comment by Fank** [comment]
Can you tell me how i enable a debug mode or something like that, to ensure ill always get some usefull output?

**Comment by MarjieAVolk** [comment]
The only way I know of is just to run the server in Visual Studio

**Comment by metachronism** [comment]
need better repro case, could not repro with the above

**Comment by Fank** [comment]
Will attach info if i got more about it.
