### ISSUE TITLE
Stamp mill / Arrastra : upgrade not calculated

### ISSUE THREAD

**Issue by fighter777** [StrangeLoopGames/EcoIssues#22613]
Hello, the advanced modules used in the stamp mill are not supported

for 100 crafts, the number of iron ores does not decrease and remains at 2000 and not at 1800 (10%).

Regards. 

EDIT : same for Arrastra ..

![image](https://user-images.githubusercontent.com/5146649/131267616-2016dff6-3641-4273-adef-a4f5fe3788e0.png)

**Comment by D3nnis3n** [comment]
This works as intended, see the yellow border, it means (when you hover over it), that these materials are not affected by modules.
