### ISSUE TITLE
USER ISSUE: Kan mich nicht amelden

### ISSUE THREAD

**Issue by BULLDOG1230** [StrangeLoopGames/EcoIssues#22624]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Ich kann mich nicht anmelden 

**Expected behavior:**
bitte um Rückmeldung

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You need to buy the game to be able to play. If you think you did that, please contact support@strangeloopgames.com with your SLG ID.
