### ISSUE TITLE
Game keeps crashing in Single player since latest update 9.4 / 9.4.1

### ISSUE THREAD

**Issue by SpicyShakshuka** [StrangeLoopGames/EcoIssues#22626]
[log_210831095728.log](https://github.com/StrangeLoopGames/EcoIssues/files/7086606/log_210831095728.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7086611/Player.log)

**Comment by D3nnis3n** [comment]
Please send an e-mail to support@strangeloopgames.com, this issue will be handled there. Attach the logs to that mail.
