### ISSUE TITLE
Alpha.6 [4c637828] Sometimes water is missing around waterweed

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2262]
![image](https://user-images.githubusercontent.com/1900106/30806106-b1fdf314-a1f4-11e7-971a-f67affa93423.png)

![image](https://user-images.githubusercontent.com/1900106/30821454-c6afcb08-a225-11e7-9607-ed1e825fa1df.png)

**Comment by keegan-o** [comment]
Isn't this a migration issue?

**Comment by Fank** [comment]
We generated the world 15 days ago in a alpha.6 version, so maybe, but don't know.

**Comment by keegan-o** [comment]
Yeah, this is migration-- closing since there is nothing more to do for A6.
