### ISSUE TITLE
USER ISSUE: Random crash

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22622]
I have no idea why it happened. There was no option to automatically report it. I attached the crash dump and my player.log/error.log:

This is from `C:\Users\***\AppData\Local\Temp\Strange Loop Games\Eco\Crashes`
[Crash_2021-08-31_130226969.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7084094/Crash_2021-08-31_130226969.zip)

And this was in `C:\Users\***\AppData\Local\CrashDumps` (I don't know what system actually created this):
[Eco.exe.13520.dmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7084082/Eco.exe.13520.dmp.zip)

**Comment by Azzurite** [comment]
Another one:

[Crash_2021-08-31_192709026.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7086371/Crash_2021-08-31_192709026.zip)

[Eco.exe.19848.dmp.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7086373/Eco.exe.19848.dmp.zip)

**Comment by TwixterZ** [comment]
Hi @Azzurite, we apologize this happen to you and thank you for reporting this. 

There is similar issue raised by another player under [@22539](https://github.com/StrangeLoopGames/EcoIssues/issues/22539) which possibly related, can you try to shut off all overlays (as commented on that issue) and let us know if that helps?

**Comment by D3nnis3n** [comment]
Closing issue due to old age and never having been reproduced, assuming TwixterZs tip helped. If it reappears, please feel free to create a new issue :)
