### ISSUE TITLE
USER ISSUE: Crash when trying to exchange currency

### ISSUE THREAD

**Issue by Menacer20** [StrangeLoopGames/EcoIssues#22621]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
trying to exchange currency,
tried 3 times in a row. crashed all 3 times

**Expected behavior:**
exchanged currency

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Titles.ElectedTitle.Contains(IAlias alias)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.TreasuryBankAccount.CanAccess(IAlias alias, AccountAccess access, Boolean sendNoticeOnFail)
   at Eco.Gameplay.Economy.Transfers.Transfer(GameActionPack pack, TransferData data)
   at Eco.Gameplay.Components.ExchangeComponent.Purchase(Player player, BankAccount purchaserAccount, Single amount, ExchangeEntry entry)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7083859/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7083860/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @Menacer20 

Thank you for writing this bug report.
However, we are unable to reproduce this on our end.
Trading currency using the Currency Exchange works properly for us.
Are you playing on an online server hosted by other players?
Could you provide us a recorded video of the issue including a screenshot of the status of the Currency Exchange? This will help us isolate the issue.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
