### ISSUE TITLE
Feature request: Add crossbow

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2263]
A crossbow should:
- Take longer to reload or same as a bow.
- Cause more damage then a bow.
- Less "bullet drop" than a bow.
- Need iron or steel, and boards to be crafted, same for repair.

The current problem is that hunting with a bow takes a lot of time, and there should be an option to speed this up.

**Comment by MarjieAVolk** [comment]
I'm going to pass these ideas on to everyone, and close this issue for now.
