### ISSUE TITLE
USER ISSUE: Failed to Connect

### ISSUE THREAD

**Issue by mwolf89** [StrangeLoopGames/EcoIssues#22630]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Try to join a server
Try to Host a server

**Expected behavior:**
Join server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @mwolf89 

Thank you for writing this report. Are you still encountering this issue? If so, how frequent?
Kindly provide us with your game logs so we can investigate the issue.
Please also include your complete PC specification including the operating system.

**Comment by Daniel-Magulado** [comment]
Hello @mwolf89 

I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22653
