### ISSUE TITLE
USER ISSUE: Dissapering Objects

### ISSUE THREAD

**Issue by Dwarvendova** [StrangeLoopGames/EcoIssues#22631]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
I was building a stockpile and Rocker box beside a water wheel. both objects dissapered after a few minutes. the water wheel is perfectly fine.

**Expected behavior:**
Placed objects like Stockpile and Rocker box should be there until picked up.		

**Actual behavior:**
After a few minutes the objects dissapered. and the place where i had placed them is no longer buildable on.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @Dwarvendova 

Thank you for writing this bug report. I'll be merging it with an earlier report of the issue at https://github.com/StrangeLoopGames/EcoIssues/issues/19797
