### ISSUE TITLE
User issue - Law created which crashes client upon joining server

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22639]
User Quinn#2371 on discord was having issue that after a law was created users joining the server were crashing.

Corrupted law does not appear in the web UI

![image](https://user-images.githubusercontent.com/61889138/132206939-2a7ebeb6-6b9a-43ef-8b1b-65433381354d.png)

Server dump file when a player tries to join even a new player who had never been on the server before, they are not sure what the law was that was attempted

--BEGIN DUMP--
Dump Time
09/06/2021 11:54:05

Exception
Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'input')
Source:System.Text.RegularExpressions

System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Eco.Shared.Utils.MathParser.MathParser.ReplaceVariable(String expression, String variableName, String value)
   at Eco.Gameplay.Civics.GameValues.TextFormula.Description()
Outer Exceptions:
Error during packaging property 'Registrars' of 'Eco.Gameplay.Systems.GlobalData'
Error during packaging property 'IdToObj' of 'Eco.Core.Systems.Registrar'
Error during packaging property 'Sections' of 'Eco.Gameplay.Civics.Laws.Law'
Error during packaging property 'IfThenBlocks' of 'Eco.Gameplay.Civics.Laws.LawSection'
Error during packaging property 'If' of 'Eco.Gameplay.Civics.IfThenBlock'
Error during packaging property 'List' of 'Eco.Gameplay.Civics.GameValues.SetOfConditions'
Error during packaging property 'Right' of 'Eco.Gameplay.Civics.GameValues.Compare'
Exception has been thrown by the target of an invocation.

--END DUMP--

See below for player log file

[lawcrash quinn.txt](https://github.com/StrangeLoopGames/EcoIssues/files/7115426/lawcrash.quinn.txt)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for writing this bug report.
I'll be merging this to an earlier report https://github.com/StrangeLoopGames/EcoIssues/issues/22585
