### ISSUE TITLE
USER ISSUE: Digging down in Mountain teleports me on top

### ISSUE THREAD

**Issue by RefusesNames** [StrangeLoopGames/EcoIssues#22635]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Dig into the mountain horizontally.
2. Start digging straight down at some point (it was happened after hitting sandstonde in granite, the hole is 2x1 blocks)

**Expected behavior:**
When breaking the rocks I should stand on broken rocks that can be picked up.

**Actual behavior:**
When breaking the rocks, they do break and transform to rocks that can be picked up, but I get teleported straight up on top of the mountina.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PixlRainbow** [comment]
if the game thinks that you may sink into the pit of rubble like quicksand and get stuck, it will teleport you away to "unstuck" you

**Comment by TwixterZ** [comment]
@RefusesNames thanks for raising this issue, as mentioned by PixlRainbow above this is unstuck mechanic that we have in place, and this is working as intended.
