### ISSUE TITLE
[0.9.4.1 beta release-242] Pressing "send" button when paying debt does nothing

### ISSUE THREAD

**Issue by ungauss** [StrangeLoopGames/EcoIssues#22634]
The "Send" button when paying a debt to another player does not work. 

The cursor changes to a pointer like on other buttons, but pressing it does not visually darken the button or send any currency. Nothing happens.

This was on White Tiger.

**Comment by Daniel-Magulado** [comment]
Hello @ungauss 

Thank you for writing this bug report but we're currently aware of this issue and it has been reported internally.
A fix should be rolled out soon in the coming game updates.
