### ISSUE TITLE
USER ISSUE: Cannot connect to worlds hosted by me on this machine

### ISSUE THREAD

**Issue by seraph676** [StrangeLoopGames/EcoIssues#22637]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1) Select "Host a World"
2) Using any combination of settings (multiple tested), attempt to create a new world.
3) Wait for the world to be created and for it to attempt to join the world hosted on this machine.
4) Be rejected from joining the world, with the attached error message popping up.

**Expected behavior:**
As the world was created locally, there should be no reason that the game is refusing to let me join my own freshly made server.
Joining worlds created by other individuals (namely a server created by a friend) gives no such errors, and allows me to join without issue.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @seraph676

Thank you for writing this report. Are you still encountering this issue? If so, how frequent?
Kindly provide us with your game logs so we can investigate the issue.
Please also include your complete PC specification including the operating system.

**Comment by Daniel-Magulado** [comment]
Hello @seraph676 

I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22653

**Comment by Daniel-Magulado** [comment]
@seraph676 

Hey, are you still experiencing this issue? If possible, could you allow us to connect to your server by providing your server ID?

**Comment by seraph676** [comment]
Hi,

Sorry, just saw these emails.
This issue has resolved, though I'm not sure why.


Thanks,

Nathan A. Ferron
