### ISSUE TITLE
SAVE ISSUE: Not able to reload World

### ISSUE THREAD

**Issue by herniklanger** [StrangeLoopGames/EcoIssues#22638]
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
We are not sure of the cause of the crash. 
The server keeps running without any errors, but all the save games get corrupted. We only noticed the corruption after a server restart, when we couldn't load many of the backups in the Storage folder.

**Expected behavior:**
Loadet the save.

**Actual behavior:**
The sever creashes with error message:  
[log_210906120651.log](https://github.com/StrangeLoopGames/EcoIssues/files/7115098/log_210906120651.log)

 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and Yes

**Comment by herniklanger** [comment]
Right before the corruption of save games started the only admin command we did was '/chat clearhistoryolderthan 2'. Maybe that could be related.

**Comment by Ry4ndrew** [comment]
Hi @herniklanger 

Thank you for writing this bug report. We are currently aware of this issue and I'll be merging this report to an earlier submitted report at #22591.

Until the fix delivered you can open Game.eco file (it is just a zip) and remove files with 0 length from Chat directory.
