### ISSUE TITLE
USER ISSUE: Cant Dig

### ISSUE THREAD

**Issue by Orbitalcrayon41** [StrangeLoopGames/EcoIssues#22640]
\
**User Id: Orbitalcrayon41
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Dig Anywhere

**Expected behavior:**
Pick up dirt, sand, etc.

**Actual behavior:**
Nothing happens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7117458/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7117459/Player-prev.log)

**Comment by TwixterZ** [comment]
@Orbitalcrayon41 thank you for raising this issue, I can confirm this is happening on current release build and will inform our developers for possible fix.

**Comment by TwixterZ** [comment]
you may follow up on this under [#22257](https://github.com/StrangeLoopGames/EcoIssues/issues/22257)
