### ISSUE TITLE
USER ISSUE: Rooms built around 0,0 get calculated incorrectly

### ISSUE THREAD

**Issue by AKA-Steve** [StrangeLoopGames/EcoIssues#22649]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Find 0,0 on the map - Or really any spot where the wrap around boundary is
Claim 2 areas, one on either side of the dividing line
Build a structure in those two areas
Separate structure into at least two rooms with the dividing wall at the wrap around boundary

**Expected behavior:**
Should have two rooms in your house

**Actual behavior:**
Variable, currently 78 in a two room structure

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Logs**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7131620/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7131621/Player-prev.log)

**Comment by AKA-Steve** [comment]
Interestingly upon restarting the server the correct room quantity/quality appears (at least in this simple test case).
Modifying the structure does appear to create variable number of rooms again

**Comment by Daniel-Magulado** [comment]
Hi @AKA-Steve 

Thank you for writing this bug report. This has been reported internally. A fix is set to roll out soon.
Closing this.

Adding reference for other SLG staff.
[ClickUp Report.](https://app.clickup.com/t/10591183/ECO-14967)
