### ISSUE TITLE
Alpha.6 [4c637828] Ramp should not be able to place on top of tree stump

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2264]
![image](https://user-images.githubusercontent.com/1900106/30821543-047175d6-a226-11e7-9de3-910c3a03edd6.png)

**Comment by MarjieAVolk** [comment]
Was that a stump?  Or a loose log?

**Comment by Fank** [comment]
stump, there is a root near the axe

**Comment by SeanAtr0n** [comment]
I couldn't place a ramp on a freshly cut-down tree's stump... probably has something to do w/ the tree batching code Eric added recently

**Comment by Fank** [comment]
The road is about 5 days old i think so it may be outdated, will validate with current version and close.

**Comment by Fank** [comment]
Ok just works:   
![image](https://user-images.githubusercontent.com/1900106/30823665-4ae3c9d6-a22d-11e7-93e5-5e88b3e1edaf.png)

![image](https://user-images.githubusercontent.com/1900106/30823679-5626184e-a22d-11e7-9126-4c879e0ce5d8.png)

Savegame: ftp://eco.fankserver.com/Game-2264.eco position in screenshop above

**Comment by Nanders** [comment]
I checked on this world with the new server and client, can't reproduce.

**Comment by Fank** [comment]
Will do now, updated server to latest staging ~15min ago.

**Comment by Nanders** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/2306
