### ISSUE TITLE
USER ISSUE: First person Player camera is not on the player model

### ISSUE THREAD

**Issue by helldragger** [StrangeLoopGames/EcoIssues#22646]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Go to sleep2. Have a wild bison push your camera out of bed3. Wake up

**Expected behavior:**
The FPS camera should still be on the player model

**Actual behavior:**
Instead, it keeps the offset due to the bison pushing it during sleep

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @helldragger 

Thank you for writing this bug report. I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/21668
