### ISSUE TITLE
USER ISSUE: Cart and Log Glitched

### ISSUE THREAD

**Issue by danivastus** [StrangeLoopGames/EcoIssues#22645]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Not sure, it just happens at some point. It happened before and fixed itself. Logging out of my friend's dedicated server doesn't fix the issue. 

**Expected behavior:**
I should be able to interact with logs and carts, and they shouldn't be pushed around like they are weightless.

**Actual behavior:**
I can't access cart inventory or pull them. I can't chop logs or pick them up, and I can push them through terrain. I can walk into both objects and they push without resistance like normal. I can also walk through doors like they don't exist.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I haven't played with mods either.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @danivastus 

Thank you for writing this bug report. I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/20414.
