### ISSUE TITLE
USER ISSUE: Animal KI gets stuck in Basement

### ISSUE THREAD

**Issue by BL00DYHUN73R** [StrangeLoopGames/EcoIssues#22642]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Build an Basement under my House
Basement is 5 Blocks high and 15 Blocks wide

![Animals stuck in basement](https://user-images.githubusercontent.com/90220016/132260239-89911755-53c8-4ce7-88ef-669a8f8b4324.PNG)

**Expected behavior:**

**Actual behavior:**
Animals can't leave the basement once they are in, they always turn around when about to exit

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @BL00DYHUN73R 
Thank you for writing this bug report. I'll be merging this to our internal report which is to improve animal PathFinding. https://github.com/StrangeLoopGames/EcoIssues/issues/17397
