### ISSUE TITLE
CTD after ~15 min of game running

### ISSUE THREAD

**Issue by matotes** [StrangeLoopGames/EcoIssues#22655]
Game crashes to desktop after approximatly 15 minutes of it running, the exact number of minutes varies. This happens both in main menu and in game. Seemingly unrelated to whats going on ingame.

- Version: 9.4.1
1. Start game
2. Wait ~15 minutes
3. Crash

Steps taken to test prevention:
- Shutdown
- Reboot
- Graphics drivers ranging from NVIDIA 459 to 471
- Reinstall / Verify cache
- Temp folder cleanup

Probably either memory related with invalid virtual adresses or DirectX unable to create staging 2D texture.
Did also get a crash.dmp file produced, can not attach here unfortunately.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7148321/Player.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/7148323/error.log)

**Comment by Daniel-Magulado** [comment]
Hi @matotes 

Thank you for writing this bug report. Do you have any other application that's potentially also using unity? Like Citrix perhaps? 
We recommend to disable or uninstall applications running on background that's also using unity. Furthermore, try to make an exception for Eco on your Anti-virus program. Please also make sure that Eco is allowed to pass through your system's Firewall.

Let us know if things improved for you.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
