### ISSUE TITLE
USER ISSUE: Home Value Details Not Showing

### ISSUE THREAD

**Issue by jakl** [StrangeLoopGames/EcoIssues#22650]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Build a 6x6x4 symetric 2 story house with a bathroom/bedroom/kitchen/general room on each story. Mouse over pie chart shows blank, no details on which rooms give what or are tier capped. Completely blank. Also thinks I have 4 shops, with only 1.

**Expected behavior:**
It should give me details about my house when I mouse over the pie chart.

**Actual behavior:**
It shows completely blank popup for Home Value popup.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no client mods installed. Unsure about server but it seems normal otherwise.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by AKA-Steve** [comment]
Do you have all the land claimed?

**Comment by jakl** [comment]
Yes, and several blocks extra all around, and I do get xp multi, the description is just missing, and it thinks I have 4x as many shops as I do.

**Comment by jakl** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7141173/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7141174/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @jakl 

Thank you for writing this report. Could you send us a screenshot of your properties, residency, the rooms, and the deed?
Or a recorded video showing all of it including the locations of your property via the Map UI.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
