### ISSUE TITLE
USER ISSUE: Talent Bug - Logging

### ISSUE THREAD

**Issue by Oceyking** [StrangeLoopGames/EcoIssues#22651]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Achieve level 6 logging, choose "Cleanup crew - Logging" as your perk, then attempt to clear debris.

**Expected behavior:**
The level 6 logging "Cleanup Crew - Logging" talent making debris cleaning no longer consume calories.

**Actual behavior:**
Debris still consumes the same amount of calories as before.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed.

**Please provide log files. 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7146063/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7146064/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @Oceyking 

Thank you for writing this bug report. I'll be merging this report to an earlier report of the same issue. https://github.com/StrangeLoopGames/EcoIssues/issues/20184
