### ISSUE TITLE
USER ISSUE: crash

### ISSUE THREAD

**Issue by Ianco9** [StrangeLoopGames/EcoIssues#22654]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
just after 10-15 minute the game close with a unity error	

**Expected behavior:**
play

**Actual behavior:**
crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Ianco9 

Thank you for writing this bug report.
Kindly upload your game logs here so we can look into this issue further. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Ianco9 

Just a follow-up. Is the game still crashing for you? If so, do you have any other application that's potentially also using unity? Like Citrix perhaps?
We recommend disabling or uninstall applications running on a background that's also using unity. Furthermore, try to make an exception for Eco on your Anti-virus program. Please also make sure that Eco is allowed to pass through your system's Firewall.

Let us know if things improved for you.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of response.
