### ISSUE TITLE
USER ISSUE: Falsche Beschreibung kleine Steinschilder

### ISSUE THREAD

**Issue by earlofavalon** [StrangeLoopGames/EcoIssues#22659]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Steinmetztisch: kleines stehendes und hängendes Steinschild haben in der Beschreibung "Holzschild" stehen

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@earlofavalon Thank you for raising this issue, I can confirm this is happening. 

We will let our developer know.

**Comment by TwixterZ** [comment]
@earlofavalon for your further information, English to Deutsch translation is performed by our communities. 

you can create an issue in crowdin at https://crowdin.com/project/eco-by-strange-loop-games
