### ISSUE TITLE
9.4.1 wrong translation taken from crowdin

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22665]
Wrong translation taken:
![Screenshot 2021-09-14 165242](https://user-images.githubusercontent.com/82637840/133280961-54a87f05-1ff8-4b41-861f-95a752053ae6.jpg)
![Screenshot 2021-09-14 165339](https://user-images.githubusercontent.com/82637840/133281106-16dba599-3b3e-405b-bf02-07497a79297e.jpg)

**Comment by Daniel-Magulado** [comment]
Hi @M3n5ch 

Thank you for writing this report. I'll make an internal report about this.

**Comment by WeaselDog** [comment]
Thanks for the report. This will be fixed in the upcoming 9.5 release
