### ISSUE TITLE
USER ISSUE: Mining upgrade in Arrastra doesn't reduce ressource costs

### ISSUE THREAD

**Issue by helldragger** [StrangeLoopGames/EcoIssues#22663]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. place a mining upgrade in an Arrastra

**Expected behavior:**
Both time needed and ressource cost should be reduced by half for all mining based recipes

**Actual behavior:**
Only time needed is reduced by half

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @helldragger 

Thank you for writing this report.
However, this works as intended. There should be a yellow border around the items indicating that these materials are not affected by modules.
