### ISSUE TITLE
USER ISSUE: Digging impossible without switching to hammer beforehand

### ISSUE THREAD

**Issue by helldragger** [StrangeLoopGames/EcoIssues#22667]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. have a hammer, a shovel and anything else in the toolbar (let's say fiber) and switch to shovel
2. dig dirt with shovel
3. switch to hammer
4. place dirt anywhere (storage / on the ground)
5. switch to shovel
6. dig dirt with shovel
7. switch to fiber
8. place dirt anywhere 
9. switch to shovel
10. dig dirt with shovel

**Expected behavior:**
@10, the player should dig a new dirt block

**Actual behavior:**
@10, the player cannot dig.
To be able to dig anew, he has to switch to hammer, and reswitch to shovel. then it works as expected.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, only happens to one player on the server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @helldragger 

Thank you for writing this bug report. A fix is already set to roll out in the coming game updates.
Merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22257
