### ISSUE TITLE
Craving for a food that already has a craving satisfied

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22669]
![image](https://user-images.githubusercontent.com/2777158/133467824-269c67d0-6a48-4e25-8133-1147adf128aa.png)

Don't know how to reproduce. Just happened while playing.

**Comment by Daniel-Magulado** [comment]
Hello @Azzurite 

Thank you for writing this bug report. However, this is not a bug. There are timers implemented before the next craving prompts. Food selected for cravings is randomized and the selection follows the criteria that food must be in the avatar's stomach. So it's not impossible to crave food that's already been satisfied.
