### ISSUE TITLE
USER ISSUE: Unable to build chimney with pipe inside

### ISSUE THREAD

**Issue by askaret** [StrangeLoopGames/EcoIssues#22661]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Build house and throw some steel pipe through the roof
Try to build a chimney around it (I used ashlar granite)
No dice, I can make 1 chimney block with pipe in it, but no more.

**Expected behavior:**
Should be able to build chimneys with pipe inside to the moon if I wanted to :)

**Actual behavior:**
Not able to build chimney as intended

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope
![20210913191731_1](https://user-images.githubusercontent.com/14834410/133130254-9b90bcaf-a100-48ad-82b3-723e2727eadb.jpg)
![20210913191852_1](https://user-images.githubusercontent.com/14834410/133130259-6cf9e090-4523-487f-9a43-0fe49e7230af.jpg)

**Comment by StallEF** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/13561

**Comment by Daniel-Magulado** [comment]
Hi @askaret 

Thank you for writing this report.
I'll be merging it with an earlier report of this issue.
https://github.com/StrangeLoopGames/EcoIssues/issues/13561

Thank you @StallEF for posting the link to the earlier report.
