### ISSUE TITLE
9.4.1 missing translation in crowdin

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22660]
The tab Camera Behavior is missing for translation in crowdin
![Screenshot 2021-09-13 181155](https://user-images.githubusercontent.com/82637840/133119466-16d23502-c439-4dc5-9c1d-3fcaf1265309.jpg)

**Comment by M3n5ch** [comment]
![Screenshot 2021-09-13 182639](https://user-images.githubusercontent.com/82637840/133121535-4ceb283a-6d33-4c1d-bc6a-5258325af5c6.jpg)
Same here, I didn't find it in crowdin

**Comment by Daniel-Magulado** [comment]
Hi @M3n5ch,

Thank you for writing this report.
I created an [internal report](https://app.clickup.com/t/10591183/ECO-15012) about this.

**Comment by M3n5ch** [comment]
![Screenshot 2021-09-14 125656](https://user-images.githubusercontent.com/82637840/133247110-d23db1ac-1175-4677-9dfc-3ac9b7f6c24b.png)
![Screenshot 2021-09-14 125748](https://user-images.githubusercontent.com/82637840/133247115-7e27f749-42e0-41f4-b373-4db9b4d17de3.png)
Here next ones missing, should I make a new ticket for everything?

**Comment by M3n5ch** [comment]
![Screenshot 2021-09-14 133439](https://user-images.githubusercontent.com/82637840/133250448-03b261ec-e858-444c-93a7-8cab3bab7f82.png)
![Screenshot 2021-09-14 132400](https://user-images.githubusercontent.com/82637840/133250459-b548d679-615e-4026-9933-f8438683f89d.png)

**Comment by StallEF** [comment]
Law, Item Traded was report here - https://github.com/StrangeLoopGames/EcoIssues/issues/20700

**Comment by M3n5ch** [comment]
Ok ticket #20700 is closed, so it's not implemented yet in 9.4.1?

**Comment by Daniel-Magulado** [comment]
Closing, a fix is already set to be rolled out soon.
