### ISSUE TITLE
USER ISSUE: Cannot interact with truck, it lost any weight too

### ISSUE THREAD

**Issue by helldragger** [StrangeLoopGames/EcoIssues#22672]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. have truck next to a capitol
2. add the needed ingredients in the truck to produce every capitol related recipes
3. craft them all
4. return to truck
5. switch to hammer
6. focus the truck and pick it up

**Expected behavior:**
@ 4, the truck should behave as usual and weight the same as usual when the player collides with it
@ 6, the truck should be focusable and picked up.

**Actual behavior:**
No selection possible, the hammer goes straight through it ( for example, selecting the road underneath the truck ) and there is no focus when looking at it ( neither at the back, nor at the front )
No weight, when the player collides with the truck, he's not slowed down at all, the truck is pushed around instead.
Truck inner storage is still available from nearby tables (here the capitol), I could extract the crafted tables using the capitol storage tab from it
Happens even after deco-reconnexion.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by helldragger** [comment]
Turns out the truck isn't the only one affected, my hoeing tool also has the same problem: not focusable, not pickup-able, not use-able, weightless

**Comment by helldragger** [comment]
Restarting the client solved the issue on my side. 
The game was previously running for a few hours already, could be a memory corruption issue

**Comment by Daniel-Magulado** [comment]
Hi @helldragger 

Thank you for writing this bug report.
I tried to reproduce this issue by following your steps to reproduce but it did not happen on my end. WE do, however, have reports and cases where vehicles losses its weight and interaction feature. Since I am unable to reproduce using the steps provided, I'll be merging this with https://github.com/StrangeLoopGames/EcoIssues/issues/20414 as it falls under the same issue.
