### ISSUE TITLE
USER ISSUE: Soil sampler and Oak Trees

### ISSUE THREAD

**Issue by FairyHibiki** [StrangeLoopGames/EcoIssues#22678]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1.  plant an oak tree or go to any grown oak tree in the world
2. try to use the soil sampler on the soil below your tree to see the growth of your tree

**Expected behavior:**
you should be able to select the soil-panel under the tree to use your soil sampler on

**Actual behavior:**
you can't select the soil below the tree, so you can't use your soil sampler on it (normally, when using the soil sampler on any other tree or plant, the soil below the plant should be marked in green, so you know that you can select it -> here it isn't the case)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have any mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192297/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192298/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @FairyHibiki 

Thank you for writing this bug report. I'll be merging this report with an earlier report of the same issue at https://github.com/StrangeLoopGames/EcoIssues/issues/12554
