### ISSUE TITLE
USER ISSUE: Adding a new section to an existing Law

### ISSUE THREAD

**Issue by CAlbers** [StrangeLoopGames/EcoIssues#22679]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Have an existing lawRevise and add a new section
Submit Law

**Expected behavior:**
Exit the Law screen and continue the game

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Collection was modified; enumeration operation may not execute.
Source:System.Private.CoreLib

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Eco.Shared.View.SubscriptionsExtensions.UnsubscribeAll(ISubscriptions ss, Boolean release)
   at Eco.Shared.View.Subscriptions.Unsubscribe()
   at Eco.Shared.View.SubscriptionsExtensions.UnsubscribeAll(ISubscriptions ss, Boolean release)
   at Eco.Gameplay.Systems.ViewEditor.Apply(Player player)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Serversided we run EM, some Nidtools and furniture mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192800/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192801/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @CAlbers 

Thank you for writing this bug report. This exception error is actually triggered by something else. I'll be merging this to an earlier open report https://github.com/StrangeLoopGames/EcoIssues/issues/20939
