### ISSUE TITLE
[9.4.1] Invisible players in server

### ISSUE THREAD

**Issue by Infinituum17** [StrangeLoopGames/EcoIssues#22674]
When I'm playing in a server (with a lot of players), I've noticed that sometimes players disappear, but I still can hear their voice if they talk.

Usually players disappear with their vehicle, and every now and then reappear.

I don't know the exact cause of this problem.

**Comment by Daniel-Magulado** [comment]
Hello @Infinituum17 

Thank you for writing this bug report. This issue has already been reported internally.
Rest assured that a fix will be rolled out soon in the coming game updates.
