### ISSUE TITLE
USER ISSUE: Menu Fails to Load if a Player Launches Game and Alt Tabs then Waits Several Minutes

### ISSUE THREAD

**Issue by Solomon7589** [StrangeLoopGames/EcoIssues#22677]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Open game via Steam,
2. While in initial loading alt+tab to another app,
3. Walk away from computer for several minutes (at least 5+),
4. Come back to game.

**Expected behavior:**
Main menu should load and be functional.

**Actual behavior:**
The main menu background appears and is animated, but the main menu does not appear and cannot be interacted with.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fil
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7191084/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7191085/Player-prev.log)
e

**Comment by Daniel-Magulado** [comment]
Hi @Solomon7589 

Thank you for writing this report. However, a closer look at the game logs that you provided, it appears that you processor is below our minimum system requirements.

Eco requires a 6th gen Intel processor, atleast an i5-6500, as the minimum requirements.
Having a system lower than the minimum requirements can result to unusual game behavior.
