### ISSUE TITLE
USER ISSUE: Vehicles glitch through blocks on world seam

### ISSUE THREAD

**Issue by ItsKodas** [StrangeLoopGames/EcoIssues#22676]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Drive vehicle accross world seam that has openings below it

**Expected behavior:**
Safely passed accross the seam

**Actual behavior:**
It glitches below the blocks, sometimes it passes safely

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ItsKodas** [comment]
https://user-images.githubusercontent.com/43526329/133881997-11dbc996-cddb-4242-8ff3-ea795350910b.mp4

**Comment by Daniel-Magulado** [comment]
Hello @ItsKodas 

Thank you for writing this bug report.
Is this near a 0, 0 world border?

**Comment by ItsKodas** [comment]
That clip was from a player crossing the Y axis 0 border, I haven't tested it an anyone have issues with the X axis border yet but I'll test it today.

**Comment by Daniel-Magulado** [comment]
Hi @ItsKodas 

Thank you for the update. I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22568
