### ISSUE TITLE
USER ISSUE: Unable to dig

### ISSUE THREAD

**Issue by tegaines** [StrangeLoopGames/EcoIssues#22670]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. After not digging with the wooden shovel for a little while, with the shovel equipped the tip of "LMB dig" comes up but clicking does nothing, no animation is shown and no warning comes up. I definitely do not have anything on the shovel.
2. I switch to anything (eg the axe), and swing it at the ground, the animation happens but obviously nothing happens.
3. I switch back to the shovel and suddenly I can dig as normal uninterupted.

**Expected behavior:**
I should be able to dig without having to swing an axe first!

**Actual behavior:**
Digging does not happen without weird intervention.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Elixer mod pack installed. Have not played game without them (friends server)

**Please provide log files. Instruction is here [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7173764/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7173765/Player.log)

**Comment by Daniel-Magulado** [comment]
Hi @tegaines 

Thank you for writing this bug report. A fix is already set to roll out in the coming game updates.
Merging this report with #22257
