### ISSUE TITLE
USER ISSUE: Lightweight vehicles and animal / can't interact / auth issues with placing

### ISSUE THREAD

**Issue by AlexDocking** [StrangeLoopGames/EcoIssues#22671]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
This is the second vanilla 9.4.1 server I've experienced this, and once it starts it stays like this for a while or until I've restarted the game, though I can't quite remember how it's played out before. This time I tried disconnected and reconnecting but it didn't fix it. It seems to crop up of the blue with no cause I can work out.
I had flux running at the time to dim the screen, on this occasion at least, but whether that could interfere I have no idea.

**Expected behavior:**
Vehicles should give access to the storage, cab, etc, and not be pushed around easily. There shouldn't be any auth problems placing on unclaimed land either.

**Actual behavior:**
In this case a truck, but on the other server it was with a wood cart, became almost weightless, which results in being able to push them around no trouble but can't interact with them. I can still access the storage through other nearby objects however. After enough time or pushing around I can usually pick the vehicle up again (though it is still weightless), but when I come to place it it either says I need auth even where there is no property, or it becomes weightless again immediately.

Before it occurred this time, I noticed that an animal I had hunted couldn't be picked up or interacted with and was virtually weightless, so I went back to the truck and found that also bugged out in the same way. The problems with a cart on the other  server, from what I remember, only  happened straight after I placed a cart and then only seldom were there problems.

I can place the truck down again in some areas but not others, since the auth blocks some areas off with no apparent rhyme or reason. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7174751/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7174752/Player-prev.log)

The first video shows that the truck can't be interacted with, the second that the truck is bugged as soon as it's placed down again, and the last that some nearby yet still unclaimed areas give auth problems that block placement.

https://user-images.githubusercontent.com/23241891/133549714-b6913929-e8de-441e-baa9-8e951e60a354.mp4

https://user-images.githubusercontent.com/23241891/133550054-db3b7cee-a826-4532-ae08-7a0920396546.mp4

https://user-images.githubusercontent.com/23241891/133551172-124c4dc9-4586-4af2-b74d-9394ddd73a30.mp4

**Comment by Daniel-Magulado** [comment]
Hello @AlexDocking 

Thank you for writing this bug report as well as providing videos and documentation of the issue.
I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/20414.
