### ISSUE TITLE
USER ISSUE:  Shovel

### ISSUE THREAD

**Issue by jemmotion** [StrangeLoopGames/EcoIssues#22675]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
Equip shovel and try to dig

**Expected behavior:**
Should dig ground

**Actual behavior:**
Nothing happens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
I couldn't figure out how to get the log file, sorry.

**Comment by Daniel-Magulado** [comment]
Hello @jemmotion 

Thank you for writing this bug report.
I'll be merging this report with an earlier report of this issue.
https://github.com/StrangeLoopGames/EcoIssues/issues/22257
