### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by drspencer124** [StrangeLoopGames/EcoIssues#22688]
\
**User Id: (slg171638)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. Trying to login

**Expected behavior:**
It should have entered the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to receive views from the server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @drspencer124 

Thank you for writing this bug report. Could you upload your game logs here? This will help us see what's going on.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing issue do to required information not provided - the respective error message later hinted at this being when trying to join a server via the "Continue" button that is on a older game version and has since been fixed.
