### ISSUE TITLE
0.9.4.1 Trucks, Steam Trucks, Carts and Players flying

### ISSUE THREAD

**Issue by simonsolberg** [StrangeLoopGames/EcoIssues#22683]
### Bug: 
- Trucks, Steam Trucks, Carts flying / clipping through roofs and the ground. 
- Player can fly when entering the most built-up area on the server. 
- Whole world clips in/out of view from one of the players at certain points. 

### Game version, server info
Game version: 0.9.4.1 beta release-242, Tuesday, August 24, 2021 5:59 PM
Server runs with the dedicated server tool in Steam, on Windows 10. 
One of the players plays on the same computer. CPU/Memory utilization ~40% so that shouldn't be the issue. 

### Description of events
We're not sure what caused this bug. 

We recently made a road around the world and drove around in Steam Trucks. No bugs.

The following happened during the last 24 hours: 
- Made the modern Truck. First player (Simon) drove into town from across the sea (bottom of ramp in town). Floating truck/steam truck bug triggered. Not sure if included in logs. Player alone on server at the time. 
- Second player (Eketri) drives around town in a Truck without experiencing any bugs. Not sure if included in logs. Player alone on server at the time. 
- Third player (Saksas) drove into town from across the sea. Floating truck/steam truck bug triggered. Should be included in logs. All 3 players were online at the time. 
- We shut down the server, restarted server. 
- After all 3 rejoins server. 
- Flying bug happens to Saksas while walking around town. 

### Some clips: 
[Steam Truck Clipping](https://youtu.be/uyQYqe09Ct0) 
[Player entering bug area from bottom of ramp and flying](https://youtu.be/hPsr69HoyV8)
[Player entering bug area from topside](https://youtu.be/A0IMFwmi03E)
[Player entering area from sea bridge](https://youtu.be/xiwsNpBNIIg)

### Logs: 
[Serverlog log_210920080924.log](https://github.com/StrangeLoopGames/EcoIssues/files/7198162/Serverlog.log_210920080924.log)
[Simon - Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7198160/Simon.-.Player.log)
[Saksas - Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7198163/Saksas.-.Player.log)
[Eketri - Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7198164/Eketri.-.Player.log)

### Pictures
![Car after floating](https://user-images.githubusercontent.com/31542525/134061583-630e248e-9d15-4ae7-b0f2-6ef95b40f87b.png)
![Floating player](https://user-images.githubusercontent.com/31542525/134061593-943b05bd-9213-4fca-981a-ae2345b6507d.png)

**Comment by simonsolberg** [comment]
### Possible reason/solution discovered:

We filled in underneath our highway across the sea and it seems to have fixed it. See screenshots: 


![Possible solution 1](https://user-images.githubusercontent.com/31542525/134219854-10b053fa-c922-41f3-85dc-44b41d90becd.png)
![Possible solution 2](https://user-images.githubusercontent.com/31542525/134219857-19908cff-8a9c-48ce-8d68-f1d47ad92fef.png)
![Possible solution 3](https://user-images.githubusercontent.com/31542525/134219859-42c76948-2a8b-4f0d-89f2-8481a4664d38.png)

**Comment by Daniel-Magulado** [comment]
Hi @simonsolberg 

Thank you for writing this bug report. I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/22683
