### ISSUE TITLE
USER ISSUE: World Corruption

### ISSUE THREAD

**Issue by Archknight12** [StrangeLoopGames/EcoIssues#22680]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
No idea it suddenly started happening today on 19/09/2021 after we managed to create a excavator, crane, truck and skid steer

**Expected behavior:**
Able to move over road happens predominantly after you far away and then come back

**Actual behavior:**
Cars/Carts and even the player falls through the world and the player randomly can fly for no reason

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fil
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192879/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7192880/Player-prev.log)
e

**Comment by Daniel-Magulado** [comment]
Hi @Archknight12

Thank you for writing this bug report. The issue where vehicles and players fall through pavements and through the world has been reported internally. I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22568. The second issue where players can randomly fly has also been reported internally.
