### ISSUE TITLE
Alpha.6 [4c637828] Blocks disappear if it will be blocked

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2268]
Not related to #2182 there are different issues!

![image](https://user-images.githubusercontent.com/1900106/30825287-b1d444b8-a232-11e7-8dc7-5a24ab6dc2ea.png)
![image](https://user-images.githubusercontent.com/1900106/30825298-b6337f88-a232-11e7-8816-99958248a414.png)

The tree blocks the space which will be used for the next items, which will be dropped in to the stockpile.
But its blocked so it will disappear.

**Comment by metachronism** [comment]
fixed with other stockpile fixes
