### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Khightian** [StrangeLoopGames/EcoIssues#22681]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Ry4ndrew** [comment]
Hi @Khightian

Please contact support at support@strangeloopgames.com with your logs
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thank you.
