### ISSUE TITLE
Game is unplayable keeps crashing 

### ISSUE THREAD

**Issue by edgaralmighty1** [StrangeLoopGames/EcoIssues#22689]
The game keep crashing as you start a server to play in . It kicks you out after about 2 minutes  It’s become unplayable at this point . I have no mods installed or anything just bought the game yesterday .

**Comment by Daniel-Magulado** [comment]
Hi @edgaralmighty1 

Thank you for writing this report. Could you provide us your game logs? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Please also provide your PC's complete system specification.

**Comment by edgaralmighty1** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214546/Player.log)

**Comment by edgaralmighty1** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214548/Player-prev.log)

**Comment by edgaralmighty1** [comment]
AMS FX(TM) 4300 Quad core processor 3.80GHz
16.0 GB ram
64 Bit operating system x64 based processor

**Comment by Daniel-Magulado** [comment]
Hi @edgaralmighty1 

Thank you for providing more information about your system.
Unfortunately, your processor doesn't meet the games minimum system requirements.
The minimum system requirements set for Eco is AMD Ryzen 5 1500X 3.5 GHz Quad-Core or Intel i5-6500 3.2 GHz Quad-Core.

**Comment by D3nnis3n** [comment]
Closing, as not meeting minimum requirements and third party unity issue related.
