### ISSUE TITLE
Anvil & Smithing Tool Shelf (icon not match to world object) use the same world object 

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2269]

**Comment by MarjieAVolk** [comment]
To clarify, Smithing Tool Shelf has an icon, but is using the Anvil model - does Smithing Tool Shelf have its own model yet?

**Comment by keegan-o** [comment]
This is a craft table we have no art for yet. Closing, unless you want to use this list to add ~20-30 bugs for the other tables too. https://docs.google.com/spreadsheets/d/1RuGcytI8iWv7mEITpe7Wkxl58qQukEBpZKZ7sWP8Wts/edit#gid=1593163464
