### ISSUE TITLE
Coordinate link syntax is too aggressive

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22697]
When you write `(421,72,444,Saw Bros) is selling Rebars now! Please consider selling me the first Reinforced Concrete you create :)` this is what you get in the chat:

![grafik](https://user-images.githubusercontent.com/2777158/134538478-f018b5fa-bc03-45c4-9fb0-c92ee28af623.png)

The two closing parenthesis in the message are confusing the coordinate link rendering. It should probably be `.*?` in your regex, not `.*` ;D

**Comment by TwixterZ** [comment]
@Azzurite thank you for reporting this, I have forwarded this to our developer for them to look into.

**Comment by WeaselDog** [comment]
Thanks again for your report. I can confirm this will be fixed in the upcoming 9.5 release
