### ISSUE TITLE
USER ISSUE: Crash when reaping

### ISSUE THREAD

**Issue by rawwrrob** [StrangeLoopGames/EcoIssues#22691]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
Attempt to reap a reap-able plant with a stone sickle. Unknown if other sickle types cause the same issue.

**Expected behavior:**
Plant should be harvested and give resources to player.

**Actual behavior:**
Causes a crash to desktop with no error message.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Behavior began after updating to v9.4.2.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by rawwrrob** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214738/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214739/Player-prev.log)

**Comment by rawwrrob** [comment]
PC SPECS:

CPU: AMD Ryzen 5800X
GPU: ASUS Strix 1080TI (driver v471.96)
RAM: 32GB DDR4
Storage: Samsung 970 970 EVO 1TB
OS: Windows 10

**Comment by Rexhunter99** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214769/Player-prev.log)
I don't have a Player.log because I'm currently in a game right now, but there's the prev log.
Additionally I am unable to see the player's who are nearby me, their character model doesn't render at all.  Not sure why.
I did transfer over from the 9.4.1 version I downloaded from the play.eco website, to the Steam version as that unlocked last night for me.

**Comment by Daniel-Magulado** [comment]
Hi @rawwrrob 

Thank you for writing this bug report.
This has been reported internally.
Only happens with Modern Scythe, and other sickle tools.

**Comment by Rexhunter99** [comment]
@Daniel-Magulado It happens with the Stone Scythe tool for me.

**Comment by D3nnis3n** [comment]
Tracked internally here @Daniel-Magulado: https://app.clickup.com/t/10591183/ECO-15140

**Comment by Dragonsmen83** [comment]
I have an Iron Sickle with the same issue although it only happens with Wheat i didn't have a problem reaping Sunflower

**Comment by AdmiralYuzuki** [comment]
[log_210922075051.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214880/log_210922075051.log)

Log attached of most recent crash with reaping bug. Grass near my lumber mill building was reaped using an iron scythe so it can be confirmed to occur with different scyth

**Comment by Rexhunter99** [comment]
The issue occurs with reaping wheat too.

**Comment by nightmarezzx** [comment]
im having the same issue. doesnt matter what i reap (grass, wheat...) or which tool i use. it even crashes when i try to mow the grass with a tractor

**Comment by MishkaFur** [comment]
Harvester+tractor will crash game too if it is grass/wheat, same as what Nightmarezzx reports

**Comment by Quadbro** [comment]
Fix for crash will be delivered asap, thanks for your reports and logs!

**Comment by TwixterZ** [comment]
Issues related to reaping is fixed and roll out with 0.9.4.3 patch, please let us know if issue persists

Thank you everyone for informing this to us.
