### ISSUE TITLE
USER ISSUE: game crashes when harvesting

### ISSUE THREAD

**Issue by steveosten2** [StrangeLoopGames/EcoIssues#22695]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
Use a Sickle on anything

**Expected behavior:**
It should harvest

**Actual behavior:**
It crashes the game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None, fresh install

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@steveosten2 thank you for the report, we know about this issue and work on fixing it. merged to #22691
