### ISSUE TITLE
USER ISSUE: crash

### ISSUE THREAD

**Issue by RAMENATTE** [StrangeLoopGames/EcoIssues#22699]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
couper de l'herbe avec une sicle

**Expected behavior:**
reccupérer des fibres

**Actual behavior:**
crash et fermeture du jeu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @RAMENATTE 

Thank you for writing this bug report. This has been reported internally and I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22691
