### ISSUE TITLE
USER ISSUE: Players are invisible in multiplayer.

### ISSUE THREAD

**Issue by Badnick1000** [StrangeLoopGames/EcoIssues#22698]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
I dont know. It happened right after the new update.

**Expected behavior:**
We can see each other.

**Actual behavior:**
Playermodels are invisible but the names are still floating around.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![20210923182722_1](https://user-images.githubusercontent.com/33238781/134546749-994b0e94-06e7-4852-81b5-7068f3bb9b7f.jpg)

**Comment by Badnick1000** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7219791/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7219793/Player-prev.log)

**Comment by TwixterZ** [comment]
hi @Badnick1000 thank you for reporting this, we are aware of this and have roll out fix in patch 0.9.4.3.

Please let us know if issue persist after latest patch

**Comment by IronyTroll** [comment]
This is still a persistent issue in 0.9.4.5 beta release-278. Players are invisible to other players without the name plate visible at all. Even when player is using a cart. We find this seems to happen more regularly when players are joining/passing each other on the road when travelling some distance.

**Comment by TwixterZ** [comment]
@IronyTroll  Apologies for late respond, we have another cause and made a fix for 9.5 patch, sincere apologies for this
