### ISSUE TITLE
Camera view not linked to vehicle orientation anymore

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22690]
On the very recent patch, `0.9.4.2 beta release-256`, the player's view camera does not rotate with the vehicle they drive anymore.

https://streamable.com/vul1l7

This is very disorientating and annoying, having to adjust the camera with the mouse all the time.

**Comment by TwixterZ** [comment]
@Azzurite thank you for your report. 

we have roll out fix for this issue with 0.9.4.3, please let us know if this issue persist.
