### ISSUE TITLE
USER ISSUE: game crush on harvest grass

### ISSUE THREAD

**Issue by lordcerber** [StrangeLoopGames/EcoIssues#22696]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
1 savegame from last week, before last patch
2 harvest field grass with scythe
	

**Expected behavior:**
plant fiber is collected, grass size decreases or is harvested whole

**Actual behavior:**
game client crush	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods, clean client, local server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/7216160/error.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7216161/Player.log)
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7216164/crash.zip)

**Comment by SlayksWood** [comment]
@lordcerber Thank you for the report, we know about this issue and work on fixing it. merged to #22691
