### ISSUE TITLE
USER ISSUE: Title Crashes when Player attempts to Reap Switchgrass

### ISSUE THREAD

**Issue by NewNakiruna** [StrangeLoopGames/EcoIssues#22692]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
1. Navigate to area with fully mature Switchgrass present
2. Equip Stone Sickle
3. Direct cursor over fully mature Switchgrass so that Reap option appears
4. Press indicated input
5. Character performs reap animation
6. Title crashes

Repro: 3/3, two separate clients tested

**Expected behavior:**
Reaping Switchgrass should have returned it to a 0% growth state and yeild plant fibers (or other loot) to the player's inventory. The player should have also remained connected to the server.

**Actual behavior:**
Instead the title crashes. There were 3 plant fibers in the player's inventory upon re-connecting to the server, but it is unclear whether they came from the Switchgrass. It is also unclear whether the Switchgrass returned to a 0% growth state.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed and server and all clients are up to date. Server is a dedicated server hosted on Nitrado and all clients are connected through steam. None of the clients that crashed were connected to a vpn at the time of the crash. Switchgrass was able to be cleared, just not reaped.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fil
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214840/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7214841/Player-prev.log)
e

**Comment by NewNakiruna** [comment]
Update: When the player crashes, so does anyone within net relevance. I took out my entire with one swipe.

**Comment by Daniel-Magulado** [comment]
Hi @NewNakiruna 

Thank you for writing this bug report. I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/22691
