### ISSUE TITLE
Ramps Not Removable

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#227]
Dirt, Stone, and Asphalt ramps not removable with hammer.
![untitled-2](https://cloud.githubusercontent.com/assets/14983165/15940271/281154f4-2e30-11e6-8887-d59155f96d4e.jpg)

**Comment by craig-jong** [comment]
For whatever reason, this is still broken for ramps spawned with the /spawnroad command.
