### ISSUE TITLE
USER ISSUE: Camera Displacement

### ISSUE THREAD

**Issue by juma2410** [StrangeLoopGames/EcoIssues#22707]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
1. Get an tiger angry on you
2. Go to sleep in you campsite
3. wait for the tiger to attack you

now you have you camera displaysment

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods Installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@juma2410 Thank you for raising this issue, I can confirm this issue and will raise this to our devs

**Comment by Daniel-Magulado** [comment]
Merging with https://github.com/StrangeLoopGames/EcoIssues/issues/21668
