### ISSUE TITLE
USER ISSUE: Rocker 1 Concentrate Production Bug

### ISSUE THREAD

**Issue by SirAtlas7** [StrangeLoopGames/EcoIssues#22709]
\
**User Id: (Sir_Atlas)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
put one crushed ore into rocker and put in labor
have one partially filled stockpile nearby
have everything maxed for world settings

**Expected behavior:**
deposited wet tailings and iron concentrate into stockpile

**Actual behavior:**
didn't deposit wet tailings and iron concentrate into the stockpile and now cannot be picked up and collected from rocker due to having to pick up both tailings and concentrate

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fil
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7232263/Player.log)
e
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7232264/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @SirAtlas7 

Thank you for writing this report. Are your stockpile and rocker linked together? To do this, you need to open the storage tab of the Rocket UI and check the small box on the upper left corner of the stockpile.
Let us know if this helped you.

**Comment by SirAtlas7** [comment]
Well before I reported the bug a friend of mine used it to make more than
one and the tailings and concentrate were both deposited into a stockpile
after it was completed while there was a single concentrate locked in the
rocker. Hopes this helps.

**Comment by SirAtlas7** [comment]
Sorry you were correct it was because the stockpile wasn't checked thank
you for the help

**Comment by Daniel-Magulado** [comment]
@SirAtlas7 

Anytime, glad that I could be of help.
Closing this report.
