### ISSUE TITLE
USER ISSUE: 9.4.2 bugs

### ISSUE THREAD

**Issue by Acromatic** [StrangeLoopGames/EcoIssues#22700]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.2 beta release-256

**Steps to Reproduce:**
Use a reaper to reap grass

**Expected behavior:**
reap grass 

**Actual behavior:**
crashes instantly

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have a mod on another server SUSTAINABILITY but nothing is active on my server it's nearly vanilla settings

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Acromatic** [comment]
There is also typos in every other part of the game.. I will compile a list and post it for you

**Comment by Daniel-Magulado** [comment]
Hi @Acromatic 

Thank you for writing this bug report. This has been reported internally and I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/22691
