### ISSUE TITLE
Do not allow "Pickup or drop" for stone road/ramp (& other blocks?) in law

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22705]
If you select "Drop or pickup block" for Stone Road or "Drop of pickup object" for Stone Ramp as a trigger for a law, this does not trigger at all. Only "Construct of Deconstruct" does anything for Stone Road & Stone Ramp.

If it doesn't do anything, it shouldn't even be selectable. This could be the case for other blocks too, I haven't tested them all.

**Comment by Daniel-Magulado** [comment]
Hi @Azzurite 

Thank you for writing this bug report. We are currently aware of this issue so I'll be merging this report with https://github.com/StrangeLoopGames/EcoIssues/issues/21916.
