### ISSUE TITLE
USER ISSUE: Ocean water not despawning

### ISSUE THREAD

**Issue by CraftyRebel** [StrangeLoopGames/EcoIssues#22701]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
1. Built tunnel under ocean water
2. Build ceiling with glass roof panels and concrete in underwater tunnel by digging out dirt/sand blocks under the water
3. Logged out/in and then fully shut down and relaunched the game to double check this was not just a graphical glitch

**Expected behavior:**
Was expecting the water to disappear once disconnected from other flowing ocean water blocks.

**Actual behavior:**
The water not only stayed where it was (i.e. suspended in the air below the ceiling tile, not flowing), but when attempting to remove the water blocks with dirt, the water starts flowing down once the dirt is removed, creating more water.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, but this is a privately hosted server if that changes things.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7224946/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7224947/Player.log)
![file 1](https://user-images.githubusercontent.com/91320333/134659820-a27b110b-ff39-420b-ad0d-f2adf0aa6f59.png)
![file 2](https://user-images.githubusercontent.com/91320333/134659825-f7a5670a-3ab6-44a3-b2a1-d46e4708e02b.png)

**Comment by Daniel-Magulado** [comment]
Hi @CraftyRebel 

Thank you for writing this bug report.
I'll be merging this report with  https://github.com/StrangeLoopGames/EcoIssues/issues/22330
