### ISSUE TITLE
Civics "Construct or Deconstruct" with "Ramps" does not work when unauthorized on property

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22711]
The "Item Used" is just "none" when trying to place down/pick up ramps:

![image](https://user-images.githubusercontent.com/2777158/134885348-b50d6e5c-6e3f-4634-86fd-7bfd5405a64d.png)

This works for some reason when you have access to put the stone ramp down (it still says "none" in `/civics debug`???) - but when you try to place it down on unauthorized property and **ignore** the authorization, with something like this law:

![grafik](https://user-images.githubusercontent.com/2777158/134936364-d3f737f4-57c4-4e05-b025-6e26252a92ed.png)

that does not work, the law just doesn't trigger at all.

**Comment by Daniel-Magulado** [comment]
Hi @Azzurite 

Thank you for writing this bug report. I've created an internal report for this.

**Comment by WeaselDog** [comment]
Thanks again for your report. This will be fixed in the upcoming 9.5 update
