### ISSUE TITLE
USER ISSUE: Cannot connect to local server

### ISSUE THREAD

**Issue by Hikaru2008** [StrangeLoopGames/EcoIssues#22715]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
1. Start Eco through Steam
2. Navigate to 'Local worlds' in 'Your Worlds' Menu.
3. Try to join local world.

**Expected behavior:**
Should have logged me into my local server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7245836/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7245837/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hello @Hikaru2008 

Thank you for writing this report. Please contact support@strangeloopgames.com with your SLG ID and game logs.
