### ISSUE TITLE
Room duplication

### ISSUE THREAD

**Issue by DarkDaskin** [StrangeLoopGames/EcoIssues#22717]
I was rebuilding one of my rooms and suddenly my housing value went up! The details show that there are now 2 kitchens with the same furniture, while in fact there is still only one.
Eco version: 9.4.3
Server: Sea Otter
Time: around 2021-09-29 17:00 UTC
![20210929195610_1](https://user-images.githubusercontent.com/200260/135315725-0e604367-d6f9-4f58-9672-35b242bf6f24.jpg)

**Comment by DarkDaskin** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7253812/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @DarkDaskin 

Thank you for writing this bug report.
We are currently aware of the issue and it was reported internally.
