### ISSUE TITLE
Rubble and vehicles teleport to coordinates (0,0)

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#22714]
Version: 0.9.4.3 beta release-259

On "Coast Redwood" and "White Tiger" official servers I've noticed now that a lot gets teleported to (0,0).

![image](https://user-images.githubusercontent.com/2777158/135082861-736e97e2-b672-4735-9e7c-60339309b13e.png)

The steam truck and all that rubble in the image were certainly not moved there by any players. No idea how to reproduce it, it just seems to happen a lot.

**Comment by Daniel-Magulado** [comment]
Hi @Azzurite 

Thank you for writing this bug report. This has been reported internally and a fix is already set to be rolled out soon in the coming game updates.

**Comment by IronyTroll** [comment]
I can confirm this is still an issue even with 0.9.4.6 beta release-285

If anything, the vehicle position reset was tolerable with on average 1 vehicle moving every 2 says, however after this last patch we found 50% of the worlds vehicles stacked up at 0, 0 just like in other images from #19458 & #20991.
![55gud3h](https://user-images.githubusercontent.com/71368607/153512802-11bbb94a-cd9c-4729-8611-7f640ec7dc3f.png)
