### ISSUE TITLE
USER ISSUE: Carretto invisibile

### ISSUE THREAD

**Issue by MatCim98** [StrangeLoopGames/EcoIssues#22718]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
non so mi sono ritrovato in questa situaizone	

**Expected behavior:**
Dovrebbe apparire

**Actual behavior:**
é invisibile

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, e no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MatCim98** [comment]
User Id: MatCim98
Version: 0.9.4.3 beta release-259

Steps to Reproduce:
non so mi sono ritrovato in questa situaizone

Expected behavior:
Dovrebbe apparire

Actual behavior:
é invisibile

Do you have mods installed? Does the issue happen when no mods are installed?:
no, e no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @MatCim98 

Thank you for writing this bug report. I'll be merging this report to an earlier report at https://github.com/StrangeLoopGames/EcoIssues/issues/20414
