### ISSUE TITLE
USER ISSUE: Véhicules invisible...

### ISSUE THREAD

**Issue by Thorghar31** [StrangeLoopGames/EcoIssues#22721]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Les véhicules ont tendance à disparaitre, invisible et inacceble. J'ai déco et reco plusieurs, j'ai également relancé le jeu deux fois.

**Expected behavior:**
Il faudrait corriger ce bug qui est vraiment pénible..

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Un mod vélo.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @Thorghar31 

Thank you for writing this bug report. I'll be merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/20414
