### ISSUE TITLE
Router Shutoff when playing

### ISSUE THREAD

**Issue by nicolopozzato** [StrangeLoopGames/EcoIssues#22726]
Hi, when i'm playing i have a strange effect...

My router shutoff, i have removed everything else on the network, only my pc hard wired with eco open (after 30/60minutes it shutoff my router, i have to remove and insert again power to power back up).

I have left my pc doing other things, youtube, netflix, some coding and online research all from this morning to 8pm and never had a problem...
Normally i have around 10 wifi devices, a nas, a small server, two ethernet pcs, and a lot of smart thing around the house and didn't have any problem anytime before using Eco...

I will suspect some left open connection that throw off my router... (thinking about nat or some sort of upnp (i don't know upnp much)) this are only my thinking about of this problem.

I use the latest version in a server with I think 2/3 mods.

**Comment by Acromatic** [comment]
I may be able to solve this one, but I need to know your router. I can look up the UPNP settings... most of the time upnp is already in play. youtube/streaming is not going to cut it.. you want lots of tiny UDP connections... like TORRENTS for example, which is tcp usually. the mods aren't the issue, but if you can tell what they are it may be helpful. The fact that you're running a smart home shows your router is either getting overwelmed ( not likely in this case that stuff is jenky I recently installed myself) OR that it's good enough to handle it and it's an ENET issue, which is very likely considering ENET is open source software and you have to code in encryption and things yourself.. so it could very well be Eco or just unity enet.  DO you have other unity games without custom networking you can try? around circa 2015??

**Comment by Daniel-Magulado** [comment]
Hi @nicolopozzato 

Thank you for writing this report. However, this seems to be a hardware-related issue and not a game bug issue or a certain game bug that causes this unusual behavior of your router. In most cases, we recommend trying it with a different router. If it still shuts off when playing Eco, do let us know.

Otherwise, this will mostly be an isolated case as this is the first time we heard anything like this.

**Comment by D3nnis3n** [comment]
Closing issue due to old age.
