### ISSUE TITLE
Tortoise and blue shark backflips

### ISSUE THREAD

**Issue by Kodvik** [StrangeLoopGames/EcoIssues#22728]
Hello, so I don't know if that can be described as a bug but it's a strange behavior... when head shooting tortoises they launch forward and do a backflip every time, leaving you to find their carcass almost aways behind you, and sometimes you don't even find it anymore... blue sharks also sometimes (a lot less) do backflips too when dying.

as a side note, when chasing a blue shark they sometimes also just enter the ocean floor... like if the solid blocks were of water, leaving you with no clue of where they went... also (a headshot hitbox would be very welcomed for the blue shark xP I've tried almost every possible angle of a headshot and never got one).

Hope it helps in something, if any clarification is needed let me know... I can try to make a small clip of it happening if needed too.

**Comment by Daniel-Magulado** [comment]
Hello @Kodvik 

Thank you for writing this bug report but it has been reported internally.
