### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by StephenB13013** [StrangeLoopGames/EcoIssues#22723]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @StephenB13013 

Thank you for writing this report. Please contact support@strangeloopgames.com so we can further assist you with this.
