### ISSUE TITLE
Building Block Bug

### ISSUE THREAD

**Issue by Acromatic** [StrangeLoopGames/EcoIssues#22733]
Client restart required to fix a bug when placing building blocks, sometimes it will only place stackable slabs instead of desired building block.

**Comment by Acromatic** [comment]
I'm not sure of the steps to reproduce yet, I've had it happen 2 times for sure and I think a 3rd. The only fix was to reload the client, disconnect did not work. One thing I think helps cause it is using /fly command, this creates a different bug where the animated sprites turn black, such as with waterfalls.

I will update when I figure out what's causing it. right now I think it's a combination of /fly and alt+tabbing out of the game. At least that's the only thing I did different then. Probably not a major issue unless modding a server (alt+tabbing and using fly a lot??)  Will update if I discover the recipe

**Comment by D3nnis3n** [comment]
Closing this issue due to not being reproducable. If it pops up again, please feel free to open a new issue :)
