### ISSUE TITLE
USER ISSUE: dirt roads dissapearing

### ISSUE THREAD

**Issue by UwUfluff28** [StrangeLoopGames/EcoIssues#22736]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1:make dirt road in desert 2:wait

**Expected behavior:**
not dissapeared

**Actual behavior:**
dissapears when i walk away

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PixlRainbow** [comment]
this is normal behaviour. The wind blows desert sand over the path and slowly degrades it over time. You don't even have to walk away, the dirt paths will disappear even if you are looking directly at them.
