### ISSUE TITLE
Rentals with Vehicles does not provide authorization to use the vehicle

### ISSUE THREAD

**Issue by vnguyen13** [StrangeLoopGames/EcoIssues#22740]
Eco version: 9.4.3
Server: SnepServ - Saeculum 7.4KM - Longterm Server

When setting up rentals for a vehicle (e.g. a Skid Steer, Steam truck), the renter does not actually get access to use/get in the vehicle. It will still pop up the notification saying that the user does not have authorization. 

To set up the rental, I:
1. Went into the Authorization tab of the vehicle
2. Went into the Deed of the vehicle
3. Clicked on the Property tab
4. Set up the Rent via the Manage Rent window
5. Set the "invite" to everyone so that everyone can rent

Once a user agrees to the rent, they can be seen as a resident of the property, but still cannot use the vehicle.

**Comment by LuminaryXion** [comment]
I also want to see this fixed. Or some law workaround to allow me to ignore auth when resident of vehicle deed.

**Comment by Deweyoxberg** [comment]
I would also like to see this fixed, and concur with Luminary's idea of a workaround to ignore auth. The rental system for housing works as-is, so it stands to logical reason that the vehicle system should be able to follow the same workflow.

Is there a roadmap as to what future patch this will be part of? I appreciate devs may be volunteers or hobbyists and a timeline isn't always possible, yet I see that awareness was acknowledged in October. Are we talking on the scale of 4-6 months? A year?
