### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by igor98markovic** [StrangeLoopGames/EcoIssues#22747]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Eco is currently open to alpha and beta backers only. Upgrade your account to join.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @igor98markovic 

Thank you for writing this report. Please contact support@strangeloopgames.com so we can further assist you with this.
