### ISSUE TITLE
Metalness turns wierd green color

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2275]
Turning Global Illumination On does this to my view:
![image](https://user-images.githubusercontent.com/3965439/30827109-4f271aaa-a239-11e7-9d7d-dbc76418c2f5.png)

**Comment by metachronism** [comment]
I think thats just uranium

**Comment by Fank** [comment]
Nope it isn't.
Its in our mine, only iron, copper and gold:
![image](https://user-images.githubusercontent.com/1900106/30883756-810e40c8-a30d-11e7-897a-cf3c99cac451.png)
![image](https://user-images.githubusercontent.com/1900106/30883767-88827c2a-a30d-11e7-832e-0f1cb8f7b94b.png)

**Comment by metachronism** [comment]
my old intel GPU laptop does this as well, but its not related to GI as far as I can tell, happens with it on or off

**Comment by KyeEco** [comment]
id also like to point out a few bugs with the global illumination ive had, 
![pic1](https://user-images.githubusercontent.com/29281156/31373542-374c0f90-ade6-11e7-920a-8d6ad3f788b0.PNG)
![pic2](https://user-images.githubusercontent.com/29281156/31373543-377e8042-ade6-11e7-9010-3a108f92c720.PNG)
![pic3](https://user-images.githubusercontent.com/29281156/31373544-37ad1bf0-ade6-11e7-83f6-08fdeb316bd4.PNG)
![pic4](https://user-images.githubusercontent.com/29281156/31373545-37dbda76-ade6-11e7-94a8-6ae5f939fd55.PNG)

**Comment by metachronism** [comment]
how did you enchant your fishing pole?

**Comment by metachronism** [comment]
new shaders dont repro the same issue anymore, so closing this.

GI is a separate issue, can make another bug for that if need be
