### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Marcoxdh1** [StrangeLoopGames/EcoIssues#22754]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
I was cutting word and putting it in to a stockpile

**Expected behavior:**
not this

**Actual behavior:**
The following error message popped up:
```
Login token changed.

<size=60.00%>Internal Server error, Trace ID: 00-443ce0b47786af42b6fd1434efb616cb-546ffb1da022134a-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing issue due to required information not provided.
