### ISSUE TITLE
USER ISSUE: uncontrollable water and without any behavioral reality

### ISSUE THREAD

**Issue by py-Thony** [StrangeLoopGames/EcoIssues#22763]
\
**User Id: (py-Thony)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
place a block in contact with water.
seek to direct the water.
Building in relation to water.

When installing a block, the water will be blocked instead of passing, then the same action will let the water pass instead of blocking it, later the water will shift without ever being able to correct the direction.

**Expected behavior:**
It lacks a 'gravity tic' or the ability to recharge the gravity effect.

I'm trying to create a hydraulic dam, and after FOUR hours of getting in my way I still can't just make the water fall straight across the width of the dam.

It would be handy to be able to summon a gravity tic, or have gravity recharged every X seconds (or minutes or hour)

Or as a dressing solution, to have a detailed tutorial on the reactions of water in order to understand its mechanism and to be able to manage it as a player uninitiated to the code and routines of the internal programs.

**Actual behavior:**
The water is not subjected to an effect of gravity, it is autonomous and does not react to the decorations but to a block installation. removing this block does not return the water to its initial state but to a random state.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods,
config alieware M15R6
params game: high quality

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by py-Thony** [comment]
![image](https://user-images.githubusercontent.com/57870398/139510659-8158691b-6ba4-4727-9727-ea39e465c4fd.png)


Another illustration.

It is unmanageable.

The 'sources' (block from which the water flows) are duplicated ad infinitum,

We should be able to dry up a stream just by blocking a waterfall. But instead you have to fill each block like in minecraft, and at the slightest forgotten block, we find ourselves at the starting point.

Unmanageable, a shame.

**Comment by Daniel-Magulado** [comment]
Hello @py-Thony 

Thank you for writing a detailed and progressing report. This issue has been reported internally and we are on the progress in improving water mechanics. I'll be closing this report but I'll tag your report to our internal one for our devs to look into.

Thank you.

**Comment by py-Thony** [comment]
Thank you!

If it can help developers understand the complaint, the synthetic idea in pseudo code is:

IF water block touches an occupied block at the upper level:
    - WHILE water block does not touch an occupied block at the lower level, then water spreads to the lower block.
    - WHILE the water block does not touch an occupied block at the same level AND touches an occupied block at the lower level, then propagates horizontally.
ELIF water block does not hit an occupied block at the same level AND water block does not hit an occupied block at the lower level AND water block does not hit an occupied block at the upper level:
    - then propagates by one only space horizontally
    - WHILE water block does not touch an occupied block at the lower level, then water spreads to the lower block.


Hoping to help make this fabulous experience more immersive
