### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by trungnguyen2k9** [StrangeLoopGames/EcoIssues#22769]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by trungnguyen2k9** [comment]
ko by

**Comment by Daniel-Magulado** [comment]
Dup https://github.com/StrangeLoopGames/EcoIssues/issues/22765
