### ISSUE TITLE
USER ISSUE: wheelbarrow stuck under land

### ISSUE THREAD

**Issue by hafizalias4484** [StrangeLoopGames/EcoIssues#22775]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
use unstuck, but vanishes underwater

**Expected behavior:**
appear on land

**Actual behavior:**
appear under land

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @hafizalias4484 

Thank you for this report but could you upload a screenshot and more detailed reproduction steps?
We are unable to replicate this issue and a screenshot or a video will help us to see the issue.

Thank you.

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
