### ISSUE TITLE
Deed Sales get removed when server is restarted

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22776]
On White Tiger, we have a Real Estate Desk on a property owned by a title with more than one person in it.
Everytime the server reboots, the "Deed Sales" window empties and all deed sales we put into that Real Estate Desk have to be entered again.
This has been observed every day on the last WT iteration and has also occurred on the recent server reboot in the current iteration.

**Comment by WeaselDog** [comment]
Thank you for reporting this. We will hopefully get this fixed soon.

**Comment by WeaselDog** [comment]
Thanks again for your report. This is fixed in the upcoming 9.5 release
