### ISSUE TITLE
9.5 Dev 2141 - Graphics options for Minimap detail has chinese? string

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22772]
Graphics options for minimap detail has a chinese string that is showing despite client being english

![image](https://user-images.githubusercontent.com/61889138/140104937-21f5b7d3-0c5c-45b3-b7d6-913db5ea7b1e.png)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for writing this report. However, this has been reported internally.
I'll be closing this ticket. Let me know if there's anything else I can help you with.
