### ISSUE TITLE
USER ISSUE: TUTS WONT GO AWAY

### ISSUE THREAD

**Issue by mrcalzon02** [StrangeLoopGames/EcoIssues#22778]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @mrcalzon02 

Thank you for writing this bug report however, we are unclear as to what you are referring. Please briefly elaborate so we can understand what this report refers to.

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)

If the tutorial is stuck at any point you can hover over the tutorial and click the "X" to skip it.
