### ISSUE TITLE
Text formula law does not allow editing, bugs out and gets replaced by "test"

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22777]
tested on a local server without any config changes or mods

1. spawn a government
2. make a law looking like this
![grafik](https://user-images.githubusercontent.com/34270661/140591261-960bb117-54e5-481d-851a-261b341a3a92.png)
3. look at the law by pressing the view icon
4. press "revise" and "edit". No changes to the law needed
5. the law code is replaced by a "test" and the law also does not auto-rename itself again
![grafik](https://user-images.githubusercontent.com/34270661/140591333-bc3286a6-46c0-4f73-bd68-81e1eaf0ce82.png)
6. if the bug doesn't occur after viewing and opening for the first time just open the law for edit a second time and it occurs

**Comment by TwixterZ** [comment]
@DanielKispert Apologies for lack of response for your issue here, I have forwarded this to our developers and this is now fixed for future patch (9.5).
