### ISSUE TITLE
USER ISSUE: Can't connect to any multiplayer sever

### ISSUE THREAD

**Issue by Sardonyck** [StrangeLoopGames/EcoIssues#22779]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
1. Open the game
2. Select New Game
3.Select any server

**Expected behavior:**
The game should connect to the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login failed
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have any mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @Sardonyck 

Kindly contact support at support@strangeloopgames.com with your logs :)
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
