### ISSUE TITLE
9.5 Dev 2141 - Unable to migrate from 9.4.3 Work party NRE

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22771]
Unable to migrate my existing 9.4.3 world to 9.5 Dev 2141 due to the below

![image](https://user-images.githubusercontent.com/61889138/140096902-88c3ce52-9128-485a-84e8-94b49661d16e.png)

Also get a lot of spam of Failed to load object of typeworldObject it will be ignored
![image](https://user-images.githubusercontent.com/61889138/140102236-22fedfb4-8b67-482a-9b97-5a9efbc43b9a.png)

Log File
[log_211103042114.log](https://github.com/StrangeLoopGames/EcoIssues/files/7469178/log_211103042114.log)

Migration log
[2021-11-03.log](https://github.com/StrangeLoopGames/EcoIssues/files/7469181/2021-11-03.log)

Prod me on discord mishka#1337 for copy of the world if needed

**Comment by Daniel-Magulado** [comment]
Thank for providing the save file. I retested with 0.9.5 Staging-2142. World ended up crashing as well with the same error
Failed to load object of type 'WorldObject'. It will be ignored, but may cause inconsistency and errors in other entities: : System.NullReferenceException: Object reference not set to an instance of an object.

I have created an internal report about this.

**Comment by MishkaFur** [comment]
closing as server is migrating without issue now in 9.5 2176
