### ISSUE TITLE
USER ISSUE: 123

### ISSUE THREAD

**Issue by trungnguyen2k9** [StrangeLoopGames/EcoIssues#22770]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
ko bt

**Expected behavior:**
ok

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ýe

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by trungnguyen2k9** [comment]
ok

**Comment by trungnguyen2k9** [comment]
ok

**Comment by Daniel-Magulado** [comment]
Hi @trungnguyen2k9 

Thank you for writing this report. Kindly contact support@strangeloopgames.com so we can further assist you with this.
