### ISSUE TITLE
[9.4.3+] Need add Species to Crowdin

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#22783]
Moon Jellyfish Species
Tarantula Species
Elk Species
Fox Species
Hare Species
Jaguar Species
Mountain Goat Species
Otter Species
Prairie Dog Species
Wolf Species
Turkey Species
Snapping Turtle Species
Tortoise Species
Pacific Sardine Species
Salmon Species
Trout Species
Tuna Species

**Comment by Daniel-Magulado** [comment]
Hi @StallEF 

Thank you for this report. I've created an internal report for it.

**Comment by WeaselDog** [comment]
Thanks for the report. This will be fixed in the upcoming 9.5 release
