### ISSUE TITLE
9.5 Staging 2156 - "Minimap detail" setting still has chinese

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22795]
Minimap detail still has chinese string despite game and PC both being in english.

![image](https://user-images.githubusercontent.com/61889138/143040180-abf95ad5-bd6b-4cfb-bf32-a8a4997674c2.png)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for the report but this has been reported internally.
