### ISSUE TITLE
9.5 Staging 2156 - devtool can only place single block at a time

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22793]
Devtool can only place single block at a time, just prompts to upgrade the tool to get the better forms, if I have the item in hand, switch to a hammer then back to devtool i can access all the forms

![image](https://user-images.githubusercontent.com/61889138/143036147-d7b99a5e-9bfc-49aa-b3ff-db7f5b8a4f7a.png)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for this report but this has been reported internally.
