### ISSUE TITLE
9.5 Staging 2156 District map 1 claim is actually 2x2, 2x2 is actually 3x3 etc

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22792]
"Single" claim is actually 2x2. 2x2 is actually 3x3 etc

![image](https://user-images.githubusercontent.com/61889138/143035384-26be7219-3b5c-410e-8f17-d73a36854689.png)

![image](https://user-images.githubusercontent.com/61889138/143035697-53f29ea8-c277-4f68-b8ed-8c7466b86bef.png)

**Comment by TwixterZ** [comment]
@MishkaFur Thank you for your report, I have forward this to our developers

**Comment by TwixterZ** [comment]
@MishkaFur Issue is not fixed on 9.5 staging of the game, however issue with mouse pointer offset from the highlight square is being handled currently
