### ISSUE TITLE
9.5 Staging 2156 - Brick Window thin is only south/east aligned

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22794]
Brick window thing is only placeable if its on the South or east side of the block, it does not rotate (no option) to be north or west edge of the block

Brick Wall thin has the rotate ability.

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for this report but this has been reported internally.
I'll tag your report as a user report to the official report.
