### ISSUE TITLE
9.5 staging 2157 - Hanging steel framed sign emits insane amounts of light

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22802]
![image](https://user-images.githubusercontent.com/61889138/143296072-48b3e9b3-c5ef-44c5-bf16-0228193d4fe0.png)

![image](https://user-images.githubusercontent.com/61889138/143296102-04317e4a-5a38-468b-b072-17d677985148.png)

Its emitting insane amounts of light for some reason

![image](https://user-images.githubusercontent.com/61889138/143296159-2567cee6-bfbe-46eb-9603-d2881373cb18.png)

**Comment by TwixterZ** [comment]
thanks @MishkaFur for reporting this, I can confirm this is happening and have forwarded this to the devs

**Comment by TwixterZ** [comment]
@MishkaFur This is now fixed in staging. Thank you for your continuous support!
