### ISSUE TITLE
9.5 Staging 2157 - Offset when Editing a claim via Map

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#22819]
When editing a deed (adding/removing claims) the claim that you add (including the hover effect) is not centered on the cursor, but instead one claim North-East.

The screenshot didn't capture my mouse, but it is display like shown whenever the mouse is inside the red box (e.g. at the X).

![image](https://user-images.githubusercontent.com/8270201/143319248-3d18adbe-72c6-4fdb-be55-d5cafdbc5732.png)

Nickname: Zokora

**Comment by Daniel-Magulado** [comment]
Hi @DragonDev1906 
Thank you for writing this bug report but this has been reported internally. A [fix](https://app.clickup.com/t/10591183/ECO-16317) is soon to be rolled out.
Closing.
