### ISSUE TITLE
9.5 Staging 2157 - Ecopedia Housing objects "Beds" should be renamed to Bedroom due to new items

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22817]
Due to the new items hewn Nightstand and lumber dresser, "Beds" should be renamed to Bedroom and have these tables in it

Also the dressers are under "Decoration" but Nightstand is under table category

**Comment by tomesc99** [comment]
Thank you very much for your observation. A ticket has been created.

**Comment by IcedForge** [comment]
clickup issue for it
https://app.clickup.com/t/10591183/ECO-16298

**Comment by IcedForge** [comment]
Closing as done for 9.5
