### ISSUE TITLE
9.5 Staging 2157 - Large bath mat is not in Washroom category

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22815]
Large Bath mat in the ecopedia is under the "Decoration" section in housing objects not Washroom like the Small bath mat

![image](https://user-images.githubusercontent.com/61889138/143317457-34339bc5-c638-425a-9896-3b6f0fc1d061.png)

**Comment by tomesc99** [comment]
Thank you very much for your report, Mishka! A ticket has been created.

**Comment by IcedForge** [comment]
Fixed for 9.5!
Thank you as always mishka for paying attention :D
