### ISSUE TITLE
Bison is too good at running straight up mountains

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2281]
https://imgur.com/a/1ZUy5
Need to reduce mountain-climbing ability for all animals, but even more so for bisons.  Having different thresholds for different species would be a good thing.

**Comment by SeanAtr0n** [comment]
Could do this as part of a patch to 6, it'll probably take a while to implement and test.

**Comment by WeaselDog** [comment]
Fixed with https://github.com/StrangeLoopGames/Eco/pull/5401
