### ISSUE TITLE
9.5 staging 2157 - Spotlight still emits light even when off/visual hitbox error too

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22813]
Spotlight still emits light even when turned off, visually the hitbox is also showing up as huge for some reason

![image](https://user-images.githubusercontent.com/61889138/143316488-805f103c-e97d-4d87-bb91-cb31421e93f3.png)

**Comment by TwixterZ** [comment]
Hi @MishkaFur  tested this as of 0.9.5 Staging-2159 and this is not happening

https://user-images.githubusercontent.com/78054747/143536493-f5dda220-ace7-4155-b787-4d4211552739.mp4
