### ISSUE TITLE
Progressive Percent does not accept 0 as a value

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22826]
if you use a "progressive percent" law block and use 0 as a threshold, like in here, the calculation will always return 0
![grafik](https://user-images.githubusercontent.com/34270661/143952346-b1ee4d66-7731-4102-af0e-57f8c88b2e71.png)
if you replace the 0 with a 1, the calculation works properly
![grafik](https://user-images.githubusercontent.com/34270661/143952376-28ad5b54-c8a1-4530-9128-a2cb1efffddf.png)

**Comment by Daniel-Magulado** [comment]
Hi @DanielKispert 

Thank you for this report.
Is this a modded server? It seems that we do not have the "Smart Tax" section on the official version of Eco.

**Comment by DanielKispert** [comment]
Hi @Daniel-Magulado

yes, we first experienced it on a modded server. However, I was also able to replicate it in unmodded singleplayer.
Steps:
1. make some currency, I called it "Randoms"
2. make yourself a bank so you have 2 accounts
3. make a law like this, it will send the receiver of money (always you if you send it between 2 of your accounts) a message:
![grafik](https://user-images.githubusercontent.com/34270661/145967654-6f65c5dc-f43b-4038-bc63-aa02850c0832.png)
4. send yourself 5000. Expected behavior: message tells you it would tax 80 (2% of 5000-1000). Behavior: it says 0 (Invalid)
![grafik](https://user-images.githubusercontent.com/34270661/145967946-43d59d56-a2fe-4c73-ab81-42e15c1e64a9.png)
If hovering over invalid, this appears: 
![grafik](https://user-images.githubusercontent.com/34270661/145967994-f2e16800-17e5-45be-aa91-5900d0272572.png)
5. fix the law to have a 1 instead of a 0
![grafik](https://user-images.githubusercontent.com/34270661/145968064-fdb05748-b454-43a3-8937-7e477e35248a.png)
6. expected behavior happens
![grafik](https://user-images.githubusercontent.com/34270661/145968241-65223267-330a-40ae-9466-724836834319.png)
![grafik](https://user-images.githubusercontent.com/34270661/145968266-2eea9bab-211a-4a05-878d-0f4041a84c6b.png)

**Comment by Daniel-Magulado** [comment]
Hi @DanielKispert 

Thank you for the detailed additional information. I'll go ahead and forward an internal report about this.

**Comment by Daniel-Magulado** [comment]
https://app.clickup.com/t/1xj10ub

**Comment by TwixterZ** [comment]
@DanielKispert Apologies for the late update on this issue. 

Happy to inform you that this is now fixed for patch 9.5
