### ISSUE TITLE
9.5 staging 2160 - Failed to receive views

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22823]
Server itself starts but unable to join it.

![image](https://user-images.githubusercontent.com/61889138/143767899-4250e122-4043-4f70-af5e-9fe3b7a5c2dd.png)

See log file
[unable to receive views log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7613533/unable.to.receive.views.log.zip)

**Comment by SlayksWood** [comment]
https://app.clickup.com/t/1vc8ynp

**Comment by SlayksWood** [comment]
fixed in 0.9.5 staging-2161/2162
