### ISSUE TITLE
9.5 Staging 2167 - Your worlds server description alignment issue

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22836]
Text is not aligned

![image](https://user-images.githubusercontent.com/61889138/144923965-fe62eac6-888e-4084-a942-0f2acdf98105.png)

![image](https://user-images.githubusercontent.com/61889138/144924000-95e27c40-7d88-437b-93b2-7f3b30ec0989.png)

![image](https://user-images.githubusercontent.com/61889138/144924030-5df73c0c-281b-4540-a7fb-7cdfabc27f13.png)

**Comment by TwixterZ** [comment]
@MishkaFur Thank you for reporting, I have forwarded this to our developer

**Comment by TwixterZ** [comment]
@MishkaFur Issue is now fixed for future patch
