### ISSUE TITLE
USER ISSUE: Rolling Mill Issue Connecting To Power

### ISSUE THREAD

**Issue by Samantic666** [StrangeLoopGames/EcoIssues#22832]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Have power, then place rolling mill near the power and make sure the room tier is at least 1.8

**Expected behavior:**
Turned on, and be connected to the power so long as you have enough

**Actual behavior:**
Does not power no matter how close to the source

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are a few mods on the server but its a fairly vanilla server 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hey @Samantic666,

Thank you very much for your feedback. Have you experienced this issue more than once? Also, did you meet this issue after updating to the "latest build" or you had it before?

It would be very useful if you could include your log files. Here are the instructions to get them.

https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Samantic666** [comment]
Hey, no it seemed to only happen then there was a small server restart and
its fixed it seemed my steam engine had bugged into having mechanical power
not electrical which was strange but the issue has fixed now thanks!

Sam
