### ISSUE TITLE
USER ISSUE: tentar abrir menu de construção

### ISSUE THREAD

**Issue by JuniorSidnei** [StrangeLoopGames/EcoIssues#22833]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
apertar 'F' na missão de tutorial de construção

**Expected behavior:**
abrir o menu de construção

**Actual behavior:**
menu não abre, mudei a tecla de atalho para 'J' e mesmo assim não abre também

**Do you have mods installed? Does the issue happen when no mods are installed?:**
não tenho nenhum mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hi, @JuniorSidnei 

Thank you very much for your feedback. Have you experienced this issue more than once? Also, are you having this issue on every server?

Please, it would be appreciated if you could add your logs.

https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
