### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by SteveyBlack** [StrangeLoopGames/EcoIssues#22831]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
ich bin zu einer anderen insel und seit dem ist bei mir ein schwarzes bild und sehe nur den charakter

**Expected behavior:**
Die behebeung schnellst möglich

**Actual behavior:**
Schwarzes bild sehe nur charakter
![Screenshot 2021-12-03 164024](https://user-images.githubusercontent.com/95490531/144635901-41e633ee-d231-4d1d-8a7f-74beafd4b5f9.png)
![Screenshot 2021-12-03 164024](https://user-images.githubusercontent.com/95490531/144635927-02bbbe4f-7321-4c51-86cc-20b83161eafb.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @SteveyBlack ,

Thank you very much for your feedback. Have you experienced this problem more than once?

Please, I would like to ask you more details regarding your PC specs (include Operating System and its version) and this issue, including some video if possible.

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
