### ISSUE TITLE
9.5 staging 2169 - Brick windows not snapping to alignment

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22839]
Brick windows that are on the north/south side are not snapping together

![image](https://user-images.githubusercontent.com/61889138/145050647-e35e3802-0dd5-42c1-b01b-06bd68a3a267.png)

![image](https://user-images.githubusercontent.com/61889138/145050688-0ffc8a35-7757-41fd-99b8-41b9a8f342cf.png)

**Comment by SlayksWood** [comment]
Brick windows are rotatable now and you need to replace them. there is a problem if you use the build command

**Comment by MishkaFur** [comment]
@SlayksWood these were placed by a player in 9.4.3 then world migrated to 9.5 was not using the /bm command

East/west it is seemingly fine

**Comment by SlayksWood** [comment]
It is impossible to replace 1 block during migration with 4 different ones.
> East/west it is seemingly fine
If you look closely, they are different. This blocks is not symmetrical, they all placed in the same direction.
I will clarify, but it seems to me that this is unrealistic to do, and you need to replace brick windows after migration.

**Comment by TwixterZ** [comment]
@MishkaFur as explained by @SlayksWood this is currently working as intended where brick windows are now rotate-able.
