### ISSUE TITLE
USER ISSUE: Auth server down

### ISSUE THREAD

**Issue by hurtubis17** [StrangeLoopGames/EcoIssues#22848]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Attempting to log into server

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7739785/Player-prev.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/7739786/Player.log.copy.txt)

**Comment by TwixterZ** [comment]
@hurtubis17 Thank you for raising this issue, we can confirm this no longer persist.
