### ISSUE TITLE
USER ISSUE: After loading saved game the zones of previous game are visible

### ISSUE THREAD

**Issue by Sixgate76** [StrangeLoopGames/EcoIssues#22843]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Start up Eco.
Load a local game.
Disconnect the game
Load an excisting game. (For me it was an offical server ) 
Disconnect the game
Load the first saved game (The fist local game I started)After loading the second time for the local game the zones of the second loaded game (Official server) where visible.

**Expected behavior:**
No data of other previous games should be visible.

**Actual behavior:**
It showed the zones of my previous game on map and also in screen. There was no option to turn on screen off.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hi @Sixgate76 ,

Thank you very much for your feedback. Have you been able to reproduce this issue again? If so, could you send us some screenshots or videos?

Also I would like to ask you to provide your log files in case it is possible. 

Here are the instructions to do it:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Sixgate76** [comment]
Yes, able to reproduce it.
1. Started eco for clean start.
- Loaded mij local game (Continue).
- Disconnect local game.
- Go to 'Your Worlds' and select de SLG sea otter server to load.
- Game Crashes.
- Start Eco
2. Click continue to load the SLG sea otter game.
In SLG sea otter I have the Land claim stake equipped
- Disconnect SLG sea otter game
3. Your Worlds
- Load my local world.
On screen there are zones that do not exist in that game/load.

As far as I can see it has to do when I disconnect the SLG sea otter game while having the Land claim stake equipped and then load the local game.  When the local game is loaded there is nothing equipped in hands and i see the  'ghost' zones. When i equip the Land claim stake the 'ghost' zones disappear.
When I unequip the Land claim stake in the SLG sea otter game before disconnecting I can  load my local game without the issue. Also step 2 and 3 I can do without crashing the game. Crash seems to occur between with step 1 and 2 (starting Eco)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7695525/Player.log)
![Original zones on saved local game](https://user-images.githubusercontent.com/95923688/145642461-af528808-ef7c-4e6a-ab03-6eb362e7bbf1.jpg)
![Screenshot after loading 3th  tie with strange zones](https://user-images.githubusercontent.com/95923688/145642465-9a4082d1-0955-4082-bb27-1a10604b9a6f.jpg)
![Screenshot first game_load](https://user-images.githubusercontent.com/95923688/145643864-a2482d18-6813-4c99-9fce-23a0f03484bd.jpg)

**Comment by tomesc99** [comment]
A ticket has been created. Thank you very much for your feedback.

https://app.clickup.com/t/1tt8vxy
