### ISSUE TITLE
9.5 Staging 2169 - third person tree foliage goes missing at certain angle

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22841]
Foliage exists

![image](https://user-images.githubusercontent.com/61889138/145071340-34a313e3-b6c9-4b92-9afc-6d5168ceae02.png)

Foliage gone!

![image](https://user-images.githubusercontent.com/61889138/145071377-21294e4e-cdc5-4a61-a7f1-76ebd748a9f1.png)

GPU settins just incase
![image](https://user-images.githubusercontent.com/61889138/145071432-94e1011c-510c-4abf-ae5b-d828cb84f280.png)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 

Thank you for this report. This is actually a new feature in-game that tends to hide parts of trees, plants, etc that may cause certain views to be blocked in 3rd person. I'll be closing it since this is not bug but feel free to reopen if there's something odd with this behavior.
