### ISSUE TITLE
USER ISSUE: Tractor Despawns

### ISSUE THREAD

**Issue by ock666** [StrangeLoopGames/EcoIssues#22845]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
Create a tractor
place it, logout for a couple of dayslog back in

**Expected behavior:**
for the tractor to remain where it is

**Actual behavior:**
it disappears

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, entirely vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @ock666, thank you for raising this to us, when you mentioned tractor disappear, did you check if its teleported to 0,0? or you unable to locate it in your server?

Can you share us your save file for us to look into further?

**Comment by ock666** [comment]
I'd checked 0,0 as well as the deed table as stated in a few posts I could find around the web. I no longer have the save as shortly after this my group lost motivation to continue playing and I deleted the container I was hosting the world in.

**Comment by TwixterZ** [comment]
@ock666 that is very unfortunate, we hope to see you and your friends return to ECO in the future, as of now, I will close this ticket.
