### ISSUE TITLE
USER ISSUE: Capitol - constitution

### ISSUE THREAD

**Issue by TwistBurn** [StrangeLoopGames/EcoIssues#22842]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.3 beta release-259

**Steps to Reproduce:**
I changed one piece of the window from the government building and after that, that constitution was wiped out with all the Laws. 
When I Checked the Capitol Status was mentioning room requirement was zero, I removed few times walls and windows to have back Tier 1 to the room.
I asked GM to help me because everything was wiped (Laws, amendments, councilor).

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7688409/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7688411/Player-prev.log)

**Comment by tomesc99** [comment]
Hey @TwistBurn ,

Thank you very much for your feedback and for sending your logs,. Have you been able to reproduce this issue again? If so, could you send us some video or screenshot?

We will be working on trying to reproduce this issue. Please, let us know if you are able to reproduce again.

**Comment by TwistBurn** [comment]
Hey @tomesc99 
I try to reproduce this issue and not happen again,

Next time I will keep in mind to record. 

It first time when I post.

**Comment by Daniel-Magulado** [comment]
I'll be closing this for now but do not hesitate to reopen this issue if you encounter it again.
