### ISSUE TITLE
9.5 Staging 2179 - Store UI Item categories

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22854]
Item categories need to be revised somewhat, bars showing as "Currency", vehicles and also crafting tables etc show as "World Object"

![image](https://user-images.githubusercontent.com/61889138/146795617-045cbc95-bbc1-4fab-8102-3e7669f366be.png)

It is not possible or at least obvious how to make another category I can only edit existing ones or add another item that then makes another category

**Comment by tomesc99** [comment]
Thank you very much for your feedback. The issue has been reported successfully.
