### ISSUE TITLE
9.5 Staging 2179 - Workbench items labour tooltip mentions specialty

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22851]
Mentions specialty despite the item needing nothing specific ie storage chest, stockpile etc

![image](https://user-images.githubusercontent.com/61889138/146792683-dd299085-4a3e-45c4-b79d-dccec387772a.png)

**Comment by tomesc99** [comment]
Thank you for your feedback! A report has been created.
