### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object. (Small Stockpile)

### ISSUE THREAD

**Issue by Jolanxbl** [StrangeLoopGames/EcoIssues#22858]
Since December 16, been receiving a crash to menu when placing a 3x3 Stockpile. Upon returning to the game, that space is unusable in any form. Only happening on this server; the server is not using mods.
[Server Crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/7752122/Server.Crash.txt)
.

**Comment by TwixterZ** [comment]
Hi @Jolanxbl, thank you for raising this issue to us. 

Since this issue only happens on this particular server, would you be able to provide the server save files? also help specify the co-ordinate where this happens

**Comment by Jolanxbl** [comment]
Admin updated the server to the christmas patch and now it's working, so
I'll close the report.

**Comment by Jolanxbl** [comment]
Admin updated & now it's working. Whatever it was, it's in the past until it happens again.
