### ISSUE TITLE
9.5 Staging 2179 - Store - buying crashes game

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22855]
Buying a world object crashes game, its fine buying blocks ie bars but steam truck, cement kiln etc crashes game

Edit also happened on trying to just buy a brick

Below is the player log
[Player.zip](https://github.com/StrangeLoopGames/EcoIssues/files/7746701/Player.zip)

**Comment by SlayksWood** [comment]
Thanks for the report.
known issue https://app.clickup.com/t/10591183/ECO-16725

**Comment by TwixterZ** [comment]
@MishkaFur Happy to inform this is fixed as of 0.9.5 Staging - 2183
