### ISSUE TITLE
9.5 Staging 2180: Can put 5 Upgrade Modules into crafting tables

### ISSUE THREAD

**Issue by Mkorny** [StrangeLoopGames/EcoIssues#22859]
\
**User Id: (slg183077)**
**Version:** 0.9.5.0 beta staging-2180

**Steps to Reproduce:**
1. Have 5 "Smelting Upgrade Module" in the inventory
2. Open a Blast Furnace and go to Modules tab
3. Add the 5xModules stack into it
4. Confirm the 5 modules will be in the Furnace
(Tested with other types of tables - will add more in detail on comments)

**Expected behavior:**
Blocked from adding more than 1

**Actual behavior:**
Lets you add 5 (then says - no more space in destiny inventory)	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

There's even a "counter" apparently
![image](https://user-images.githubusercontent.com/34373753/146930179-df32482c-50bd-4058-b4d2-8f4972ce6fbd.png)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Mkorny** [comment]
Seems to happen with many other types of modules.

![image](https://user-images.githubusercontent.com/34373753/146931419-53353d3d-8fca-4c19-9060-9c3aea0c9f15.png)

![image](https://user-images.githubusercontent.com/34373753/146931433-ec93ea0f-b982-49e2-b640-9bdcb884b835.png)

![image](https://user-images.githubusercontent.com/34373753/146931462-3bc9924a-23a2-4fca-80ca-ae9e83a1c711.png)

**Comment by tomesc99** [comment]
Hello @Mkorny ,

Thank you very much for your feedback. This issue has already been fixed for the following updates.
