### ISSUE TITLE
9.5 Staging 2179 - Fur pelt issues in store (does not go into the "basket" area

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22856]
Fur Pelt does not go down into the "items i want to buy" area, despite having multiple in the basket so to speak

![image](https://user-images.githubusercontent.com/61889138/146810109-c82c5fa7-f878-474b-aff0-8a2af6faf832.png)

**Comment by TwixterZ** [comment]
Hi @MishkaFur , I have just tested this on 0.9.5 Staging - 2180 and im able to add Fur pelt into cart and change amount to purchase. 

Can you help provide video of this happening? also, is fur pelt the only item in the cart when this happens?

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
