### ISSUE TITLE
9.5 Staging 2179 - Cast Iron Stove moves

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22853]
Cast iron stove moves if you interact with it

![image](https://user-images.githubusercontent.com/61889138/146793635-11352a82-f110-4952-8290-6e9ac20aa098.png)

Interacted with it and its moved "back" one block, when it is in this moved state another player can walk into the block with no collision

![image](https://user-images.githubusercontent.com/61889138/146793719-52d31553-b94c-4801-887d-c20e5424ef06.png)

**Comment by tomesc99** [comment]
Thank you very much for your feedback. A ticket has been created.
