### ISSUE TITLE
9.4.4 - unable to click on the "+" icon when managing bank accounts or registrar titles

### ISSUE THREAD

**Issue by DanielKispert** [StrangeLoopGames/EcoIssues#22865]
Steps to reproduce:
1. Create a new Registrar Title or Bank Account
![grafik](https://user-images.githubusercontent.com/34270661/147173208-cc385afc-b1de-425d-b3de-a27e3e0dc0d1.png)
2. add a title or demographic where you are in (admins in this case, as I'm an admin in singleplayer) to the managers
![grafik](https://user-images.githubusercontent.com/34270661/147173247-b90f61e8-f3e1-4189-a9e6-f16f6e5a946c.png)
3. you can still click the + to add managers or holders
4. remove yourself from the title managers but keep "Admins" in there. Expected behavior: you can still change the title because you are an admin and therefore a manager. Observed behavior: when clicking on either + at managers or holders, nothing happens. The popup to select a person/title/thing to add does not show up
![grafik](https://user-images.githubusercontent.com/34270661/147173316-1ae35362-dfe3-4920-b6c6-52bf33f8080c.png)

**Comment by Daniel-Magulado** [comment]
Hi @DanielKispert 

Thank you for writing this report. I'll go ahead and write an internal report as I was able to confirm it.

https://app.clickup.com/t/10591183/ECO-16805

**Comment by TwixterZ** [comment]
@DanielKispert apologies for the delay in responding, we have released a fix for this issue now.
