### ISSUE TITLE
USER ISSUE: My tent dissapeard

### ISSUE THREAD

**Issue by Reecus** [StrangeLoopGames/EcoIssues#22866]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.4 beta release-273

**Steps to Reproduce:**
I was following the tutorial, and was trying to put down my tent in som place nice, and I just could not do it, suddenly my tent disappeard from my inventory without being placed, and I cant keep going with the tutorial

**Expected behavior:**
Placed the tent 

**Actual behavior:**
the tent just dissapeard 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Reecus 

Thank you for this report.
Could you provide us with a video recording of the issue as it happens and your game log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
