### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Junix43** [StrangeLoopGames/EcoIssues#22861]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.4 beta release-273

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Ungültige Anmeldeinformationen.

<size=60,00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hallo @Junix43 ,

Danke für Ihre Rückmeldung. Könnten Sie weitere Informationen zu dem Problem bereitstellen? Ist es passiert, nachdem etwas Bestimmtes getan wurde? Kannst du es nochmal reproduzieren?

Bitte, es wäre sehr nützlich, wenn Sie die logs teilen könnten

https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
