### ISSUE TITLE
9.5 staging 2181 - Missing localization for tutorial tasks

### ISSUE THREAD

**Issue by fmateus2** [StrangeLoopGames/EcoIssues#22864]
Some texts need to be uploaded to Crowdin:

![1-make_a_workbench_task](https://user-images.githubusercontent.com/95154065/147164192-b8fddb37-71f5-4623-955e-8dc332fb47f9.png) ![2-prepare_logs_for_building_task](https://user-images.githubusercontent.com/95154065/147164214-6099bff9-2094-4237-9f3a-f16707a0a9d7.png)![5-carve_a_path_task](https://user-images.githubusercontent.com/95154065/147164240-3f76d216-b771-44e1-99e6-8c4a4cfb1508.png)
![3-build_with_a_hammer_task](https://user-images.githubusercontent.com/95154065/147164227-c3f79ffd-afd6-4d80-9475-68f9df4a880b.png)![6-share_your_property_task](https://user-images.githubusercontent.com/95154065/147164242-629ad6ec-7899-40d5-9eb2-b8b45e4d4c44.png)!
![4-how_to_level-up_panel](https://user-images.githubusercontent.com/95154065/147164229-02d042a7-f397-489e-a121-b99b22b699f3.png)

**Comment by Daniel-Magulado** [comment]
Hi  @fmateus2 

Thank you for writing this report. I've created an internal report about this.
A fix should be rolled out in the coming game updates.
