### ISSUE TITLE
USER ISSUE: STUCK

### ISSUE THREAD

**Issue by seaglassfoxen** [StrangeLoopGames/EcoIssues#22868]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.4 beta release-273

**Steps to Reproduce:**
Build a structure 30+ blocks underground to hold a stockpile. Then add a roof above it to hold a second stockpile but have unbroken rock in the way3 blocks above where you want to place the second stockpile. Attempt to clear said stone but run out of energy/food. Glitch through rock on your way back to the surface and find yourself stuck next to the lower portion of the structure between a wall and rocks with no way out, unable to remove walls or break rocks to escape. And no one to rescue you due to solo play. 

**Expected behavior:**
Some kind of "I'm STUCK," rescue function that places the player on/near a bed or the nearest sea-level open space. 

**Actual behavior:**
Irrevocably stuck underground with no means of escape. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PixlRainbow** [comment]
Does the /unstuck command help or does it just put you back into the same trap?

**Comment by Daniel-Magulado** [comment]
Hi @seaglassfoxen 

Thank you for this report. We are currently aware of this issue and we implemented the command /unstuck to get your avatar removed from being stuck in unusual events. Feel free to reopen this again if the issue still persists despite the command.

**Comment by seaglassfoxen** [comment]
Thank you, all! 
Finally found the /unstuck command after some more digging through Google. It would be helpful if this kind of information was somewhere in the game menus. Or easier to spot if it already is because I haven't been able to find it. *shrug* (Like a HELP tab or something?)
