### ISSUE TITLE
Alpha.6 [B8ce025e] Shovel missplacement on player

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2287]
![image](https://user-images.githubusercontent.com/1900106/30831962-b4d4b866-a249-11e7-9c96-455a2a9e8cca.png)
![image](https://user-images.githubusercontent.com/1900106/30831964-b75b624c-a249-11e7-8e35-b9825da4f562.png)

**Comment by SeanAtr0n** [comment]
Fixed in svn
