### ISSUE TITLE
0.9.5 Staging #2187 - Can't log in to game with StrangeLoop account

### ISSUE THREAD

**Issue by sebastians17** [StrangeLoopGames/EcoIssues#22883]
I can't log in to Eco with my StrangeLoop account.

**Comment by Daniel-Magulado** [comment]
Hi @sebastians17 

Kindly contact support at support@strangeloopgames.com with your logs :)
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Feel free to reopen this if you still need some assistance.
