### ISSUE TITLE
9.5 2191 - Chat Notifications config text alignment issue

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22888]
Text is not correctly aligned

![image](https://user-images.githubusercontent.com/61889138/147881139-f3ad1360-b40b-4dac-8bc5-38926aa1fd68.png)

**Comment by TwixterZ** [comment]
@MishkaFur  Thank you for reporting your finding, I have forwarded this to our developers to look into.

For internal use : https://app.clickup.com/t/10591183/ECO-16983

**Comment by TwixterZ** [comment]
@MishkaFur Happy to inform issue is fixed for 9.5 patch

**Comment by MishkaFur** [comment]
Still got issues but on the new UI

![image](https://user-images.githubusercontent.com/61889138/153777793-39064674-5865-4937-9a7a-fd7a6a5f2b33.png)
