### ISSUE TITLE
Alpha.6 [B8ce025e] Chest/Stockpile rename will not update "Storage" tab

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2289]
First time i open it: 
![image](https://user-images.githubusercontent.com/1900106/30832974-629aeca6-a24d-11e7-8059-5767f0fc9552.png)

After someone edit the name:
![image](https://user-images.githubusercontent.com/1900106/30832995-7ac2bda4-a24d-11e7-9573-a20e2d22d2bf.png)

Reopen the dialog does not change anything, only a reconnect to server.

**Comment by MarjieAVolk** [comment]
Fixed in next staging
