### ISSUE TITLE
9.5 Staging 2191 - Store search - does not show "last" typed character

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22897]
if you hit for items to sell, then type for example Stea it will only show "Ste" until you click into the search box

Additional example type S, nothing appears, type T then the S will appear

**Comment by tomesc99** [comment]
Hello @MishkaFur ,

A ticket has been created. Thank you very much for your report.

**Comment by IcedForge** [comment]
Closed as fixed
