### ISSUE TITLE
9.5 Staging 2192 - Glass icon is not aligned when carrying it

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22907]
Glass icon is not centered when carrying the block

![image](https://user-images.githubusercontent.com/61889138/148236854-1b7f991d-7c1d-4386-837c-ef630a61eb14.png)

**Comment by tomesc99** [comment]
Hello @MishkaFur ,

Thank you very much for your report. A ticket has been created.

* For internal use purpose: https://app.clickup.com/t/1vr937k

**Comment by TwixterZ** [comment]
Issue is now fixed in 9.5, @MishkaFur really thank you for your support
