### ISSUE TITLE
9.5 Staging 2192 - Land Claim Stake icon in store has durability?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22910]
It for some reason has a durability bar

![image](https://user-images.githubusercontent.com/61889138/148269299-78840aef-9b70-4690-b782-9bcb36ca8390.png)

No durability

![image](https://user-images.githubusercontent.com/61889138/148269398-bd9b0cd6-fccd-49f5-8bbf-0fd8eb40c170.png)

![image](https://user-images.githubusercontent.com/61889138/148269444-34bb7c1f-3471-450d-9f22-7fad2668a349.png)

**Comment by TwixterZ** [comment]
@MishkaFur  Thank you for reporting this, I can confirmed this is a bug and have forwarded this to our developers

Internal Use : https://app.clickup.com/t/21fpkp7
