### ISSUE TITLE
9.5 staging 2194 - Unable to vote and webui says forbidden

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22917]
![image](https://user-images.githubusercontent.com/61889138/148545944-260d4608-0e7f-466e-8856-8517c6cd4bbd.png)

Just sticks on submitting, nothing shows ingame

![image](https://user-images.githubusercontent.com/61889138/148545983-38795800-121a-4cc0-96ec-1a6ff6d1d6a6.png)

**Comment by TwixterZ** [comment]
@MishkaFur thank you for raising this to us, I can confirm this is happening and have raised the same to our developers. 

For internal use : https://app.clickup.com/t/21nnahv

**Comment by TwixterZ** [comment]
This is now fixed @MishkaFur , thank you your continuous support
