### ISSUE TITLE
Doing literally anything with Eco bluescreens my entire computer

### ISSUE THREAD

**Issue by whydoineedthisthing** [StrangeLoopGames/EcoIssues#22924]
Trying to boot it up? Bluscreen
Trying to download it? Bluescreen
Trying to uninstall it? Bluescreen
Trying to move the game files? Bluescreen

This literally only happens with Eco; it only started after I started downloading it and my other games and files work fine.
I've disabled my antivirus. I've updated my drivers. I have no idea why interacting with the game or its files in ANY capacity crashes my entire PC.
The specific crash reason given: UNEXPECTED_KERNAL_MODE_TRAP

**Comment by tomesc99** [comment]
Hello @whydoineedthisthing ,

Thank you very much for reporting your issue. This one looks like a local issue, have you been able to solve it already?

If not, could you share your PC specs?

**Comment by whydoineedthisthing** [comment]
Hi, sorry for late reply. I eventually got it working by having to manually enter Safe Mode and deleting a faulty antivirus file that was unable to be closed or removed otherwise.
