### ISSUE TITLE
9.5 Staging 2194 - Hitting Escape when editing district map instantly exits it

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22920]
Hitting escape whilst editing a district map just instantly exits it, it does not alert that it will not be saved which you get if you click the X

So lost work on a district map due to this as it did not save any draft

![image](https://user-images.githubusercontent.com/61889138/148644631-286491bf-a45f-42c7-9bd9-26bba3cf3bb1.png)

**Comment by TwixterZ** [comment]
@MishkaFur thank you for reporting this, I can confirmed this and have informed our developers

For internal use : https://app.clickup.com/t/21nnb3g

**Comment by TwixterZ** [comment]
@MishkaFur We have now fix this issue for future patch. Appreciate all the support you have given =)
