### ISSUE TITLE
0.9.4.5 beta release-278 Waterwheel removes water blocks

### ISSUE THREAD

**Issue by IronyTroll** [StrangeLoopGames/EcoIssues#22929]
![20220111084926_1](https://user-images.githubusercontent.com/71368607/148851471-8210be78-6cb9-4fad-afe7-6681f2cb4865.jpg)

Waterwheels remove water blocks, requiring admin to replace water using devtool.

**Comment by TwixterZ** [comment]
Hi @IronyTroll thank you for raising this issue to us, this however have been fixed in future patch. Look forward to it! =)
