### ISSUE TITLE
9.5 Staging 2197 - Bed Component - Does not list the newer beds

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22936]
Bed Component does not list the Cast iron nor Nylon Futon bed

![image](https://user-images.githubusercontent.com/61889138/149038829-facae9e0-73b0-436c-9e15-86272039e63b.png)

**Comment by tomesc99** [comment]
Hello @MishkaFur ,

Thank you very much for your report. A ticket has been created.

_* For internal use purpose: https://app.clickup.com/t/10591183/ECO-17345_
