### ISSUE TITLE
Eco Crashes on Server creation, no mods

### ISSUE THREAD

**Issue by DominikAvecUnK** [StrangeLoopGames/EcoIssues#22930]
As the Title states, as soon as the server reaches the lading modkitplugin loading phase, it just crashes. no mods installed, nothing
Eco 9.4.5, moved to several different Folders, because i thought maybe the SSD was faulty, but that does not seem to be the issue.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7847475/Player.log)

[log_220111034134.log](https://github.com/StrangeLoopGames/EcoIssues/files/7847479/log_220111034134.log)

Any Idea?

**Comment by DominikAvecUnK** [comment]
![image](https://user-images.githubusercontent.com/97534525/148966128-0073b09c-98f3-477b-8dc2-64848df52df3.png)
That is the ingame message i get, and i dont get a logfile, that only happens when i start the server from the server.exe, which then closes the console fairly quickly

**Comment by DominikAvecUnK** [comment]
![image](https://user-images.githubusercontent.com/97534525/148966775-2fa1d561-f1e5-47af-8f0b-d5a652bcd84e.png)
This error message does not result ina .log file, but when i start the server from the server.exe, it does

**Comment by Daniel-Magulado** [comment]
Hi @DominikAvecUnK 

Checking the game logs that you provided, it did not pertain to any crash info. It simply stops providing logs which isn't helpful. Could it possibly be that you're firewall is preventing the game to connect to its server? Have you allowed Eco as an app to pass your systems Firewall? Otherwise, could you launch the game and try again then send us the latest gaming logs.

**Comment by DominikAvecUnK** [comment]
i recorded what happened, and this time at least ingame it got further than before
https://youtu.be/SRwZaoaB_u0
video is unlisted, i thought this might be the easiest way

**Comment by DominikAvecUnK** [comment]
also the red windows security badge is because i entirely disabled the firewall for the pc

**Comment by DominikAvecUnK** [comment]
Protokollname: Application
Quelle:        .NET Runtime
Datum:         12/01/2022 10:50:32
Ereignis-ID:   1023
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      Fortillian
Beschreibung:
Application: EcoServer32.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 60CE78B3 (60B70000) with exit code c0000005.

Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-12T09:50:32.1257944Z" />
    <EventRecordID>731</EventRecordID>
    <Correlation />
    <Execution ProcessID="12952" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Fortillian</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EcoServer32.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 60CE78B3 (60B70000) with exit code c0000005.
</Data>
  </EventData>
</Event>
Protokollname: Application
Quelle:        .NET Runtime
Datum:         12/01/2022 10:52:20
Ereignis-ID:   1023
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      Fortillian
Beschreibung:
Application: EcoServer.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 00007FFA992FA4A7 (00007FFA99130000) with exit code c0000005.

Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-12T09:52:20.6667646Z" />
    <EventRecordID>741</EventRecordID>
    <Correlation />
    <Execution ProcessID="5572" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Fortillian</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EcoServer.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 00007FFA992FA4A7 (00007FFA99130000) with exit code c0000005.
</Data>
  </EventData>
</Event>

**Comment by DominikAvecUnK** [comment]
This can be closed, it was just the precursor signs of my cpu's I/O die slowly burning out...

**Comment by D3nnis3n** [comment]
Closing issue due to being 'resolved' - hope you got a beefy replacement CPU :)
