### ISSUE TITLE
9.5 Staging 2197 - Missing glass rotation (Edge wall turn and thin wall turn)

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22931]
Glass is missing one of its turns, after the er L one (bottom left) you have to hit R twice to get the next one

![image](https://user-images.githubusercontent.com/61889138/149033440-84bed58c-abf4-48cc-b27a-742abd6ecf1f.png)

**Comment by MishkaFur** [comment]
Also thin wall turn, missing top right 

![image](https://user-images.githubusercontent.com/61889138/149033905-6767f06c-9f3b-4b2f-8d51-546f92eb4b24.png)

**Comment by Daniel-Magulado** [comment]
@MishkaFur 

Thank you for the report. So this is the ordinary Tier 2 Glass right? Seem to be working fine on my end. I also tested on the build you mentioned and it works fine. Am I missing something?

![image](https://user-images.githubusercontent.com/77248866/149140767-c75aa638-588e-406b-b156-0d8cc9d09d31.png)

**Comment by MishkaFur** [comment]
This appeared to be from the changes Jens' is making for the balance bits and bobs, his PR also includes new glass forms

**Comment by MishkaFur** [comment]
Closing as resolved in 2267
