### ISSUE TITLE
USER ISSUE: Report the game

### ISSUE THREAD

**Issue by PantACRO4life** [StrangeLoopGames/EcoIssues#22945]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta staging-2205

**Steps to Reproduce:**
Buy the game
Install the game
Play the game
Get fuck by the game

**Expected behavior:**
NONE
ONLY BUGS

**Actual behavior:**
BUUUUUGS

**Do you have mods installed? Does the issue happen when no mods are installed?:**
YES and YES

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Z3bre-QC** [comment]
oh for real my too when i play on your server !!!!

**Comment by D3nnis3n** [comment]
You're playing on staging - a development version, expected to have bugs. 
Your report unfortunately is totally meaningless, as it neither contains logfiles nor any description of an issue.
Hence closed.
