### ISSUE TITLE
USER ISSUE: Shop Bug

### ISSUE THREAD

**Issue by guybrushh** [StrangeLoopGames/EcoIssues#22943]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
Buying and selling from shops

**Expected behavior:**
You pay the money u get the material or u sell the material u get the money

**Actual behavior:**
You pay the money you dont get the material or you get the money and you keep the material

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
