### ISSUE TITLE
Alpha.6 [B8ce025e] Large Butchery Efficiency should increase output instead if decrease input

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2294]
![image](https://user-images.githubusercontent.com/1900106/30852026-ba393a1e-a2aa-11e7-8610-84c64970ce2b.png)

Because it will still show the same output & input amount in Butchery Table:
![image](https://user-images.githubusercontent.com/1900106/30852079-eb14e200-a2aa-11e7-9600-09b3d2885833.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#371
