### ISSUE TITLE
[Bug] Failed to load world

### ISSUE THREAD

**Issue by mimic2300** [StrangeLoopGames/EcoIssues#22958]
**Version**: 0.9.4.5

The server was up and running for about 5 days. A preventive restart was performed every day. However, the server did not start on the last day and ended with this error.

```
[12] [Error] [Eco] Failed to start the server. Exception was Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:System.Private.CoreLib

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Voxel.HashChunkContainer`1.Set(Vector3i pos, T val)
   at Eco.Shared.Voxel.ChunkGrid`1.AddChunk(TChunk chunk)
   at Eco.World.PersistentChunkPack.ForEachChunk(Action`1 action)
   at Eco.World.PersistentChunkGrid.<Load>b__11_0(PersistentChunkObject obj)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass45_1`1.<LoadAsync>b__1()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Index was outside the bounds of the array.)
```
For the last 20 hours or so, strange high-rise columns of blocks have begun to appear on the map. I think that's it.

2km planet and 180m water level (max height 280m) (3x increased deep of map)
The world generator is adjusted and the ratio is left to match the original setting of only 3 increments.

**Attachments**:
[Save](http://share.ophite.cz/share/minecraft-world-s3.rar)
[Screenshot](http://share.ophite.cz/share/2022-02-01%2020_43_20-Eco.jpg)

**Comment by mirasrael** [comment]
I checked the save and issue happens because of chunk (0, -1, 6). It isn't clear how it appeared, but I added check to prevent it in future and logging for troubleshooting.

**Comment by WeaselDog** [comment]
Thanks for your report. This should have been fixed with a previous update. Let us know if you are still having issues.
