### ISSUE TITLE
Changing residence deletes owned stockpiles and tables

### ISSUE THREAD

**Issue by KingKrimmson** [StrangeLoopGames/EcoIssues#22962]
Since the most recent update (`9.4.6`), we've noticed a new bug/feature. If you remove someone from a residence (or outright delete the property), all of their tables and stockpiles (as well as the contents) are deleted from the world. This has been an issue when trying to move residences from one property to another and all of a players belongings are destroyed, forcing admin intervention.

**Comment by D3nnis3n** [comment]
This is actually working as intended and has always worked like this, also see this: https://github.com/StrangeLoopGames/EcoIssues/issues/22976

Does the player have the items in void storage? If not, please report back, because that would indeed be a bug.
