### ISSUE TITLE
USER ISSUE: won't load.

### ISSUE THREAD

**Issue by flowergardener23** [StrangeLoopGames/EcoIssues#22963]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
Game won't load when I start it. It is very slow even when typing this.

**Expected behavior:**
It should load in a more reasonable amount of time. This game isn't playable as it is right now.

**Actual behavior:**
Very slow loading. It only runs at 12.5 fps.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @flowergardener23 

Thank you for submitting this report.
Could you kindly provide us with the game logs?  Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

May we also request you to provide us with your complete system specification including the operating system.

**Comment by flowergardener23** [comment]
Hi,
So the game is working now. I think I needed to update my driver for my PC.
Thank you so much for responding. Should I leave an update on my post?
Thank you,
flowergardener23

**Comment by D3nnis3n** [comment]
Closing due to seemingly being resolved, glad it works now! :)
