### ISSUE TITLE
Tool durability wrong

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2296]
when my hatchet or other tools degrade in health, I go to repair them and they never repair (Stone tools) and when I go to make a new hatchet for example instead of being full durability it has the same as the original one at 0%

**Comment by MarjieAVolk** [comment]
Fank was seeing this too apparently - https://github.com/StrangeLoopGames/EcoIssues/issues/2098

**Comment by johnkslg** [comment]
Skill requirements not updating also

**Comment by johnkslg** [comment]
dup closing
