### ISSUE TITLE
9.5 staging 2221 - "Build a house" tutorial step does not complete in multiple cases

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#22971]
The step before "Build a house" tells the player that they should build the foundation on owned land, but does not remind the player on how to check what they own and not. It also accept a single block only being placed on owned land.

The "Build a house" step then requires them to have the entire building enclosed, but does not tell the player that this is the case.
If the house is first built and then claimed, they also need to remove and replace one block from the wall, or else the tutorial step trigger won't activate.

![image](https://user-images.githubusercontent.com/11805935/152680141-6e39449d-6e61-4a03-9484-2b62e23ac9b5.png)

**Comment by Daniel-Magulado** [comment]
Hi @MonzUn 

Thank you for writing this report. We are currently aware of this issue and will be merging this report with our internal one.

[Thank you](https://app.clickup.com/t/10591183/ECO-13504).
