### ISSUE TITLE
USER ISSUE: Sand/Water Dirt Texture under aquaducts

### ISSUE THREAD

**Issue by kommandantjut** [StrangeLoopGames/EcoIssues#22975]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
Build Brick Aquaduct elevated above grassy dirt
Have water flow through it

eventually it turns to the water dirt texture

**Expected behavior:**
Should be regular grass

**Actual behavior:**
wrong texture

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods / happens without mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello @kommandantjut 

Thank you for submitting this report. Upon checking our database, we already have an internal report of this issue. I'll be merging this report to that one. Rest assured that our developers are looking into this issue. A fix should be rolled out in future game updates.

[QA Ref.12580](https://app.clickup.com/t/10591183/ECO-12580)
