### ISSUE TITLE
USER ISSUE: Bug

### ISSUE THREAD

**Issue by BrotherMan12** [StrangeLoopGames/EcoIssues#22979]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
idk 

**Expected behavior:**
Let me switch wood types

**Actual behavior:**
Set the amount of selected to be crafted back to one

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @BrotherMan12 

Thank you for submitting this report. However, may we ask for clarification of the issue reported here? Are you referring to the option where you can choose which type of hewn log you can craft to? If not, kindly provide more information for us to be able to look further into this issue?

Looking forward to your response.

**Comment by D3nnis3n** [comment]
Closing issue due to required information not having been provided. If it reappears, please feel free to create a new issue :)
