### ISSUE TITLE
9.5 staging 2221 - Game doesn't explain how to get out of sleep UI

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#22970]
I accedentally laid down in my bed while I was taking things out of my tent during the tutorial and realized that the player needs to know that TAB is how to get the mouse cursor or that escape gets them out, or else they can't get out of the bed UI.

The prompts shown on screen also don't work in this state.

![image](https://user-images.githubusercontent.com/11805935/152679854-a016d09e-c87c-42b8-8ddf-3092a8f3f41e.png)

**Comment by Daniel-Magulado** [comment]
Hi @MonzUn 

Thank you for this report but we are currently aware of this issue. I'll be merging this report with our internal report.

[Thank you](https://app.clickup.com/t/10591183/ECO-16578).
