### ISSUE TITLE
9.5 staging 2221 - "Housing Panel Unlocked" tutorial info box insinuates that bricks is a tier upgrade from lumber

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#22972]
Lumber and bricks are the same tier building block, yet this info box has arrows between them like if bricks would be an upgrade from lumber.

![image](https://user-images.githubusercontent.com/11805935/152680354-7eae954e-7e24-4b52-af3b-ff869e24aac1.png)

**Comment by Daniel-Magulado** [comment]
Hi @MonzUn 

Thank you for this report. I've gone ahead and created an internal report for this.

[Thank you](https://app.clickup.com/t/10591183/ECO-17868).

**Comment by TwixterZ** [comment]
Hiya @MonzUn, happy to inform we have changed this on our latest build (develop). 
In future patches this will be shown correctly.
