### ISSUE TITLE
[9.4.5/9.4.6] Client confused with multiple servers on the same IP address

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#22982]
Hi SLG,

We currently have two Eco servers running on our dedicated machine.
I'm not entirely sure where the issue comes from, but the client gets confused with which of the two servers it was last connected to.

This becomes apparent when using the "Continue" button. At times, it will have our players continue on our test server, which they had never been in before.

The test world is running 9.4.6, while the main world is running 9.4.5

The only thing different we are doing on this server, is using one of the machine's secondary assigned IP addresses. As in, not it's primary IP address, but an additional IP address that has been bound to that machine.
This IP address has been added into the network config file on both Eco Servers:
  "IPAddress": "154.27.85.181",

I'm not sure if that might be the cause of the issue or not. We'd always ran multiple servers on the same machine but never had this issue before until using this new setup. When switching to the new setup (the machine with multiple IPs), is when we'd also updated to 9.4.5.
So I can't say for certain if it's a bug specific to 9.4.5 and later, or something that has been there before that with the multiple IP machines.

**Comment by ChickenHacker1** [comment]
A second glance at our network.eco file, and I think the ID, and Passport are the same.

I suppose this could be the cause of the confusion?

**Comment by mirasrael** [comment]
@ChickenHacker1  yes, these should be unique per server

**Comment by ChickenHacker1** [comment]
Gonna go ahead and close this, seems to be alright with the unique ID
