### ISSUE TITLE
USER ISSUE: cant play at all....

### ISSUE THREAD

**Issue by J0lly0n3** [StrangeLoopGames/EcoIssues#22987]
\
**User Id: (slg216265)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
create a game try to join a game cant do anything

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by J0lly0n3** [comment]
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>

Log File:
Initialize engine version: 2020.1.17f1 (9957aee8edc2)
[Subsystems] Discovering subsystems at path R:/games/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX 570 Series (ID=0x67df)
    Vendor:   
    VRAM:     8171 MB
    Driver:   30.0.13023.1012
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.669400 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Ignoring invalid [UpdateBefore] attribute on Unity.Scenes.LiveLinkRuntimeSystemGroup targeting Unity.Scenes.SceneSystemGroup.
This attribute can only order systems that are members of the same ComponentSystemGroup instance.
Make sure that both systems are in the same system group with [UpdateInGroup(typeof(Unity.Entities.InitializationSystemGroup)],
or by manually adding both systems to the same group's update list.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Unity.Entities.ComponentSystemSorter:FindConstraints(Type, SystemElement[])
Unity.Entities.ComponentSystemGroup:GenerateMasterUpdateList()
Unity.Entities.ComponentSystemGroup:RecurseUpdate()
Unity.Entities.DefaultWorldInitialization:AddSystemToRootLevelSystemGroupsInternal(World, IEnumerable`1, Int32)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Ignoring invalid [UpdateAfter] attribute on EcoEngine.Rendering.LOD.LODSystem targeting EcoEngine.Rendering.CameraTrackingSystem.
This attribute can only order systems that are members of the same ComponentSystemGroup instance.
Make sure that both systems are in the same system group with [UpdateInGroup(typeof(Unity.Entities.InitializationSystemGroup)],
or by manually adding both systems to the same group's update list.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Unity.Entities.ComponentSystemSorter:FindConstraints(Type, SystemElement[])
Unity.Entities.ComponentSystemGroup:GenerateMasterUpdateList()
Unity.Entities.ComponentSystemGroup:RecurseUpdate()
Unity.Entities.DefaultWorldInitialization:AddSystemToRootLevelSystemGroupsInternal(World, IEnumerable`1, Int32)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects. 
(Filename:  Line: 627)

WwiseUnity: Wwise(R) SDK Version 2019.2.9 Build 7459.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Setting Plugin DLL path to: R:/games/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

The referenced script on this Behaviour (Game Object 'Camera') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Table') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Glow') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Glow') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'Glow') is missing! 
(Filename:  Line: 334)

Version: 0.9.4.6 beta release-285
RAM: 65463MB Total / 52557MB Free
OS Version: Windows 10  (10.0.0) 64bit
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 Cores - 3.693 Ghz
System bit-ness: 64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename:  Line: 320)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead 
(Filename:  Line: 320)

The referenced script on this Behaviour (Game Object '<null>') is missing!
DG.Tweening.DOTween:InitCheck()
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, T2, Single, ABSTweenPlugin`3)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Single, Single)
UI.Scripts.LoadingMessageUIManager:ClearMessages()
UI.ConnectionUI:GotoState(ConnectState)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()

[ line 334] 
(Filename:  Line: 334)

[11:25:04.975] OnEncryptedAppTicketResponse: Not connected to Steam
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
SteamAuthHandler:OnEncryptedAppTicketResponse(EncryptedAppTicketResponse_t, Boolean)
Steamworks.APIDispatchDelegate:Invoke(T, Boolean)
Steamworks.CallResult`1:OnRunCallResult(IntPtr, Boolean, UInt64)
Steamworks.CallbackDispatcher:RunFrame(Boolean)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Curl error 56: Receiving data failed with unitytls error code 1048578
 
(Filename:  Line: 815)

Curl error 56: Receiving data failed with unitytls error code 1048578
 
(Filename:  Line: 815)

Curl error 56: Receiving data failed with unitytls error code 1048578
 
(Filename:  Line: 815)

Curl error 56: Receiving data failed with unitytls error code 1048578
 
(Filename:  Line: 815)

[07:38:14.959] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
RunLoop:Invoke(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:16:41.537] Connecting to 10.0.0.217:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ExtendedServerInfo)
System.InternalCancelHandler:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.Data.DataRowCreatedEventHandler:Invoke(Object, DataRow)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:16:51.638] Disconnected with error: Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Unity.Properties.Generated.m_Handle:.ctor()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass71_0:<Initialize>b__0()
System.InternalCancelHandler:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.InternalCancelHandler:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 8 Unused Serialized files (Serialized files now loaded: 0)

Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 114808.
Total: 106.806100 ms (FindLiveObjects: 4.860900 ms CreateObjectMapping: 4.585400 ms MarkObjects: 97.221700 ms  DeleteObjects: 0.137600 ms)

[08:18:32.835] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:18:32.835] Connecting to 127.0.0.1:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:18:32.835] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:18:42.893] Disconnected with error: Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Unity.Properties.Generated.m_Handle:.ctor()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass71_0:<Initialize>b__0()
System.InternalCancelHandler:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.InternalCancelHandler:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 114808.
Total: 132.105900 ms (FindLiveObjects: 4.559300 ms CreateObjectMapping: 4.900400 ms MarkObjects: 122.518000 ms  DeleteObjects: 0.127500 ms)

[08:18:43.054] Nat introduction received with token = 328f0630-1f45-438a-8b09-e6d35e98c2c1
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Unity.Entities.Function:Invoke(SystemState&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(Address&, IntPtr, Int32, Boolean&)
Eco.Networking.ENet.ENetUdpPeer:Intercept(Event&, Address&, IntPtr, Int32)
ENet.InterceptCallback:Invoke(Event&, Address&, IntPtr, Int32)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass71_0:<Initialize>b__0()
System.InternalCancelHandler:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.InternalCancelHandler:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:19:41.988] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:19:41.988] Connecting to 127.0.0.1:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:19:41.988] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:19:52.054] Disconnected with error: Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Unity.Properties.Generated.m_Handle:.ctor()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass71_0:<Initialize>b__0()
System.InternalCancelHandler:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.InternalCancelHandler:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 104213.
Total: 108.427400 ms (FindLiveObjects: 7.219900 ms CreateObjectMapping: 4.565300 ms MarkObjects: 96.515400 ms  DeleteObjects: 0.126300 ms)

[08:20:00.480] Trying to add Handle (UnityEngine.UI.Image) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.UI.CanvasUpdateRegistry:InternalRegisterCanvasElementForGraphicRebuild(ICanvasElement)
UnityEngine.UI.Graphic:SetVerticesDirty()
UnityEngine.UI.Graphic:OnRectTransformDimensionsChange()
UnityEngine.RectTransform:set_anchorMin(Vector2)
UnityEngine.UI.Scrollbar:UpdateVisuals()
UnityEngine.UI.Scrollbar:set_size(Single)
TMPro.TMP_InputField:ON_TEXT_CHANGED(Object)
System.Action`1:Invoke(T)
TMPro.FastAction`1:Call(A)
TMPro.TextMeshProUGUI:GenerateTextMesh()
TMPro.TextMeshProUGUI:OnPreRenderCanvas()
TMPro.TextMeshProUGUI:Rebuild(CanvasUpdate)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
Unity.Entities.WithCodeAction:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:28:00.943] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:28:00.944] Connecting to 127.0.0.1:3000...

EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:28:00.944] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[08:28:11.007] Disconnected with error: Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
System.Threading.WaitOrTimerCallback:Invoke(Object, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider, UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
Unity.Properties.Generated.m_Handle:.ctor()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass71_0:<Initialize>b__0()
System.InternalCancelHandler:Invoke()
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.InternalCancelHandler:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 104213.
Total: 105.358600 ms (FindLiveObjects: 7.610700 ms CreateObjectMapping: 5.000500 ms MarkObjects: 92.618100 ms  DeleteObjects: 0.128900 ms)

**Comment by D3nnis3n** [comment]
Please make sure that Eco is explicitly exempted from any of your anti-virus software, it may also help to try turning it off completely. This error basically says that you cannot connect to our authentication servers, so somewhere on the way there it is blocked, most likely due to security software or provider restrictions.

This is not a bug, though, but a support issue. If you need more help, feel free to reach out to support@strangeloopgames.com.

**Comment by J0lly0n3** [comment]
so its not my security nor is it a firewall... i have tryed at multiple locations on multiple computers want to actually look this time?
