### ISSUE TITLE
Minimap text appears when changing settings

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2299]
When I checked the "Storage" checkbox in the minimap settings panel, the storage icons appeared with text showing.  Scrolling in or out on the minimap made the text disappear.

**Comment by Fank** [comment]
Did some testing, its for all of them, not only "Storage":   
![image](https://user-images.githubusercontent.com/1900106/30878624-7e8c2d5c-a2fd-11e7-9c8c-bed43e77acdc.png)

**Comment by Fank** [comment]
You don't need to scroll its enough if you just check the ceckboxes. Everytime you check a checkbox the last checked once's text will disappear.

**Comment by SeanAtr0n** [comment]
fixed
