### ISSUE TITLE
9.5 Staging 2237 webclient missing auth for voting

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22999]
When opening the webclient for a vote I cannot vote for something. Looks like Auth is missing
![Screenshot 2022-02-23 192110](https://user-images.githubusercontent.com/82637840/155382903-9f0ac27f-c3db-4e59-ac45-26dd240db63c.jpg)

**Comment by tomsseisums** [comment]
Hey, @M3n5ch!

Elections web interface can only be authed with by opening it via Game, either by using the Button in Toolbar near the Map, Shift + G shortcut, or clicking on any Election item in-game where all of the actions will ask to open browser.

The tokens are then stored in browsers LocalStorage.

If you open the Elections web interface without having never opened it (in the given Server's Cycle) from in-game actions, no tokens will be stored, and you won't be authed.

If you clear storage of your web browser, either via browser itself or a tool like CCleaner or maybe you have an extension/setting that does it automatically, or you opened in Incognito window/session, the tokens will be removed/not saved, and again, returning back directly from browser won't authenticate you.

Does opening from within the game still present you with this issue? None of use internally has had such problem, so it might be your local setup.

**Comment by M3n5ch** [comment]
I used to go through the game, but it didn't identify my client. Right now it looks like it works like it should.
