### ISSUE TITLE
New server not listed public

### ISSUE THREAD

**Issue by Ripx8912** [StrangeLoopGames/EcoIssues#22990]
I've followed Wiki as well as searching in discord and github but not able to fix my issue.
-Server is hosted on own hardware Dell R620, mikrotik router. Windows server 2022 original license
-Ports are forwarded (i host other game servers as well)
-3 of us are able to connect directly using IP or ddns followed by port, however server not listed in public list
-No mods , even with mods the same
-Windows firewall is disabled just to test out

Server network tab
![aaass](https://user-images.githubusercontent.com/84700861/154180162-d0861e69-da6c-450f-92aa-8ae97fe0c111.png)

This always shows on Game Launch (basically u launch your game)
![aass](https://user-images.githubusercontent.com/84700861/154180257-ed5eee04-37f4-4e39-945d-f640c203c279.png)

However when u click something else and return to "Your World" the Servers goes offline but if relaunch ECO it will appear as above pic. Even showing offline, if you Direct Connect it works fine.
![aasss](https://user-images.githubusercontent.com/84700861/154180263-57ff945d-d5c8-46ac-a069-ca236f9845eb.png)

**Comment by TwixterZ** [comment]
Hi @Ripx8912, thank you for raising this ticket, when trying to look for your server I have been able to find your server without issue 
![image](https://user-images.githubusercontent.com/78054747/154936211-a46c1526-44db-47c5-b1d8-b49f98f3f836.png)
Did this issue resolved itself since you last reported this? 
(always nice to see SEA server coming up)

**Comment by Ripx8912** [comment]
Yes somehow managed to solved it.
Sorry for replaying late, been away for a week.

**Comment by TwixterZ** [comment]
glad to hear it! I will close this ticket for now then =)
