### ISSUE TITLE
[PC] Xbox One Controller support

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#23]
I tested playing Eco with my controller but the controls don't fully work.

Left joystick: Walking
Y : Jumping

That's it, Looking, attacking etc have no buttons linked on the controller.

Sugestion:
Left joystick: walking
Right joystick: Looking
A: Jumping
Right bumper: Cycle toolbar right
Left Bumper: Cycle toolbar left
Right Trigger: Attack

Did I miss something?

**Comment by klimSLG** [comment]
In fact, Eco use mouse a lot. 
this is not that easy to do(especially with all the UIs.)
How you switch in between windows, how you move from this toolbar to that toolbar, how you chat, etc.

**Comment by metrotyranno** [comment]
The controller moves the mouse when it is presented with the option inside games, you just have to assign a button for the tab menu, say, the back button, and start for the escape menu.

**Comment by noblackthunder** [comment]
i must agree with k. its not easy .. and when they do it they need to do it right

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/727/xbox-controller

**Comment by metachronism** [comment]
This is probably not going to happen
