### ISSUE TITLE
Contract board occupancy incorrect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2300]
![image](https://user-images.githubusercontent.com/3536496/30878516-ba1cc2ec-a2b1-11e7-81e8-19465e77c85f.png)
Maybe run through others too?  Spawn em all with a debug command?

**Comment by Nanders** [comment]
Fixed here: https://github.com/StrangeLoopGames/Eco/pull/1816

Will check the other occupancies, I think this is the only thing broken though.
