### ISSUE TITLE
USER ISSUE: Enter Election = Crash White Tiger

### ISSUE THREAD

**Issue by jakeasmith** [StrangeLoopGames/EcoIssues#23010]
\
**User Id: @jakeasmith**
**Version:** 0.9.5.0 beta staging-2240

**Steps to Reproduce:**
1. Click on Enter Election
2. Crash straight out of the server to the Eco welcome screen

**Expected behavior:**
1. Click on Enter Election and write an awesome speech
2. Get elected as Ruler of White Tiger
3. ???
4. Profit

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Civics.Constitutional.CivicDutyUtils.GetSubmitButtonText(CivicDuties civicDuties, Type type, LocString actionText, LocString typeName)
   at Eco.Gameplay.Components.PerformCivicActionComponent.Select(Player player, Type type)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, just WT

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8146294/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8146295/Player-prev.log)

**Comment by TwixterZ** [comment]
@jakeasmith We thank you for reporting this issue, and apologies for lack of response from our end for this. 

We can confirmed this is now fixed. =)
