### ISSUE TITLE
USER ISSUE: Compte suspendu

### ISSUE THREAD

**Issue by Zielno** [StrangeLoopGames/EcoIssues#23033]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
Héberger un monde

**Expected behavior:**
Lancer une nouvelle partie

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Informations de connexion invalides.

<size=60,00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non aucun mod

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Bonjour @Zielno ,

Avez-vous pu résoudre votre problème ? Si ce n'est pas le cas, veuillez nous en informer. Je recommanderais d'essayer de vous connecter sur play.eco et de voir ce qui se passe. Et toi, as-tu déjà joué ? Ou ça a toujours été comme ça ?

Comme dernière alternative, je suggérerais de créer un nouveau compte sur play.eco et de réessayer.

**Comment by D3nnis3n** [comment]
Closing this issue, as it is not a bug but an account issue. If it still persists, please reach out to support@strangeloopgames.com, they'll be able to assist you with it :)
