### ISSUE TITLE
Why is the Korean translation not reflected?

### ISSUE THREAD

**Issue by StoryNine** [StrangeLoopGames/EcoIssues#23035]
Current work progress is high, but nothing really reflects that.
Any other issues?

Can I get all the files I need for translation?
I want to translate it and post it separately

**Comment by D3nnis3n** [comment]
It seems not even half of the strings are approved by a proofreader and those don't make it to the game.
So once the approval progress is higher, we can put it on the sales pages. If you need Proofreader access, you can contact me directly.
