### ISSUE TITLE
9.5 Playtest 2246 - Brick Small Corner hitbox is offset

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#23045]
# Brick Small Corner hitbox is offset by 0.5 blocks
## Difference to #22803
I'd like to revive an older issue #22803 that still exists in a slightly different way. While the block targeting bug has been resolved the hitbox is still offset, affecting players and vehicles. Adding this to the previous issue didn't seem right, so I've created a new issue. If that was the wrong move, I'm sorry.

Contrary to what I said in #22803 the hitbox does not seem to be rotated by 128° but instead offset by 0.5 blocks on X and Z (and perhaps even on Y).

## Description
It appears that the hitbox of the Small Corner form for bricks is offset by 0.5 blocks in each direction.

## Expected behavior
The hitbox (physics) should match the visible part of the block

## Actual behavior
As shown in the Images below the hitbox seems to be offset by 0.5 blocks in X and Y (and potentially slightly higher than a full block), as indicated by the red outline in this image:
![image](https://user-images.githubusercontent.com/8270201/157498606-07aa2479-0b4c-4883-a67f-5bbb2ee0de64.png)

## Additional Details
If only a single brick small corner block is placed a vehicle clips through it when driving by at the front.
![brick-bug-1](https://user-images.githubusercontent.com/8270201/157495368-9c08b6d4-b5ee-4de2-8e89-1145abfaae6c.PNG)

When driving by on the back you hit an invisible hitbox. In the screenshot I can drive forwards but not left.
![brick-bug-2](https://user-images.githubusercontent.com/8270201/157495394-afd83e44-fb48-4d2a-9178-d673ec7c057e.PNG)

This is especially annoying if you're using these blocks as one block high barrier between a road and a pathway. The sum of these hitboxes behave like a full block that is offset by 0.5 in X and Y. In this image it is impossible to move the truck further left, the same hitbox applies for player movement.
![brick-bug-3](https://user-images.githubusercontent.com/8270201/157495422-9647055a-93fd-4160-bbd1-b41b35717a49.PNG)

**Comment by TwixterZ** [comment]
@DragonDev1906 happy to inform you this issue is now fixed in our latest staging build.
