### ISSUE TITLE
Remove block 'souls' effect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2304]
I'd like to keep the game in the simulation realm, and these feels like it doesn't fit there.

**Comment by keegan-o** [comment]
More detail helps with requests like this as I remember when we had the cube shaped soul puff effect that you referred to in the same way and which was removed a long time ago. Do you mean just the puff of soft dust now when things are destroyed?

**Comment by keegan-o** [comment]
And perhaps it is on some blocks but not others? Like which blocks were you seeing it on? There are many different effects.

**Comment by Nanders** [comment]
I see it on dirt when using the shovel

I think that's what @johnkslg  is referring to

**Comment by keegan-o** [comment]
Ahh, it must have gotten turned back on somehow! Deleted it so it will never come back.
