### ISSUE TITLE
USER ISSUE: Server wont load

### ISSUE THREAD

**Issue by b1xndie** [StrangeLoopGames/EcoIssues#23054]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
When I try to load it says it crashed.

**Expected behavior:**
It should load

**Actual behavior:**
Doesn't and says it crashed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I installed one mod big shovel, It could be removed if needed, I removed it but there may be a copy of the mod in the files somewhere i am missing.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @b1xndie 

Thank you for submitting this bug report. Are you still experiencing this issue? If so, could you provide us your game log? Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by b1xndie** [comment]
No, I am no longer experiencing this  issue and It was something with the
host I was using. Thanks for the follow up.

**Comment by Daniel-Magulado** [comment]
Hi @b1xndie 

Thank you for the update. I'll be closing this then but feel free to submit another bug report if you ever encounter one.

**Comment by b1xndie** [comment]
Will do, thanks!
