### ISSUE TITLE
9.5 Staging 2264 - Sign UI changes while writing text

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#23059]
# 9.5 Staging 2264 - Sign UI changes while writing text
## Description
When writing text in a text component (e.g. on a sign) the sign UI changes when pressing Shift+1 ... Shift+5.
This may be a new feature (or may have existed for a long time, I don't know). But it is slightly irritating that it changes the UI while writing text. At least on the German keyboard layouts this for example happens while writing `"` or `%`, both useful when adding markdown formatting.

## Expected Behavior
When the text field is not in focus do the UI change (I assume that's an intended feature) and when the text field is in focus do not change the UI

## Actual Behavior
The UI always changes when pressing Shift+[1-5]

## Screenshots

![image](https://user-images.githubusercontent.com/8270201/160258369-1ed9b741-1498-46d2-8934-a32c8f4d7b59.png)
![image](https://user-images.githubusercontent.com/8270201/160258371-7acf0625-90d3-4949-81cc-cc14d48f8a91.png)
![image](https://user-images.githubusercontent.com/8270201/160258441-3febdafe-5904-47cf-9ab0-5be22688d3a0.png)

**Comment by TwixterZ** [comment]
Thank you @DragonDev1906 for reporting this, we can confirm that this issue is now fixed =)
