### ISSUE TITLE
Creative flight movement keys are hard-coded and can't be changed in the Controls options

### ISSUE THREAD

**Issue by Tergiver** [StrangeLoopGames/EcoIssues#23050]
When you type /fly and begin flying, the movement keys are hard-coded to WASD. If you rebind the move keys to something else, say ESDF (a common alternative to WASD), walking around uses ESDF, but /fly sill uses WASD. Entering flight mode also introduces keybinding conflicts as you might have changed what the 'W' and 'A' keys do.

Simple fix, make the movement during flight consistent with movement when not flying.

I know this is not a serious issue as it's a pretty niche problem, but it's really difficult to swap between ESDF and WASD when playing in and out of flight mode, and this seems like a very simple thing to fix.

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6 update

**Comment by Tergiver** [comment]
I just saw the patch notes. You folks are awesome. Thank you!
