### ISSUE TITLE
Connecting to server crashes the computer

### ISSUE THREAD

**Issue by Shinhan** [StrangeLoopGames/EcoIssues#23055]
Version 9.4.6

Games has been working find the last couple days, it was only this morning it started having problems. I'm playing on **Sea Otter** now. First time this happened was after about hour of playing the computer just turned off on its own, as if somebody unplugged it from the power. So I tried bypassing the UPS and connecting directly to mains power which didn't help. 

Next couple of times I turn on the computer, start the game, start connecting to the server and somewhere in the connecting to server process it just turns off the computer. 

I have Ryzen 7 3700X and RTX 3080.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8313496/Player.log)

I don't think the temperature was high, but I've also attached the temperature monitor log, it logged the data from before the steam was started to when the computer crashed:
[OpenHardwareMonitorLog-2022-03-21.csv](https://github.com/StrangeLoopGames/EcoIssues/files/8313500/OpenHardwareMonitorLog-2022-03-21.csv)

**Comment by Shinhan** [comment]
I forgot to mention previous time but I did verify integrity of files in Steam.

This morning I also updated my graphics drivers to 511.79

The problem is still happening.

But I did try connecting to some other server and on another server it does connect, it seems its only the problem with Sea Otter. And it happens right after the last step of loading the game.

**Comment by Daniel-Magulado** [comment]
Hi @Shinhan 

Thank you for submitting this bug report. Based on the game log that you provided, it appears that this is a hardware problem or a driver problem and not a game problem. The game log shows that the game is proceeding as expected but the log gets cut-off which we would believe that its the same time where your PC shuts off. It's safe to assume that it is not from temperature problem but other factors can affect and cause this issue such as malware, power supply failing, or others.

I'll be closing this report for now as it seems that this is not a game bug or in-game causing problem. However, feel free to reopen this anytime if you can provide more proof or credible source that its the game that causes this problem.
