### ISSUE TITLE
USER ISSUE: Can't load save or create a new one

### ISSUE THREAD

**Issue by fin-core** [StrangeLoopGames/EcoIssues#23067]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
When I click on Continue nothing happens.
I restored a backup von the files, same result.
I reinstalled the game, same result. 
When I create a new save the game throws me back to the mainmenu after clicking start.
So there is no way to play the game for me. I did not try to join a server, because I want to play singleplayer.

**Expected behavior:**
Start the save.

**Actual behavior:**
Didn't start the save.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, not a single one.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by fin-core** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8379329/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8379333/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hello @fin-core 

Thank you for submitting this bug report. Could you provide your saved file? So we can take a look at it.

**Comment by fin-core** [comment]
Hi Daniel, 

sorry I forgot to close this thread in Time. 2 days ago I reinstalled windows. After that I was able to create a new save and I am able to load it again. I do not have the the save anymore. 

But thanks for your reply.
