### ISSUE TITLE
USER ISSUE: Elevator not found

### ISSUE THREAD

**Issue by KevinGelking** [StrangeLoopGames/EcoIssues#23060]
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
1. Make a building
2. Place an elevator going through the middle of the building on 3 floors
3. Place an industrial elevator next to the building with floors going down
4. Place down Elevator Call Posts on each floor, right next to each elevator

**Expected behavior:**
Each elevator call post will call the nearest (horizontal!!!) elevator or can be 'edited' to specify which elevator to affect.

There's a horizontal limit for exhaust pipes. Can't elevator call posts simply strongly prefer the horizontally closest elevator? It may be 50 blocks above or just 4 blocks above.

Say you have 2 elevator shafts on either end of a tall building. You would want the call posts next to the shaft to call that particular elevator.

**Actual behavior:**
Half the elevator call posts don't work because they seem to look both horizontally + vertically. So if you have an elevator, say, 10 blocks right above the call post and another elevator 10 blocks away horizontally, it will complain that it can't find any elevator. In fact, though, it appears it's finding two and then just breaks out of the function with no result.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, though none that affect elevators.
It also happened before we even had mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Pic of Error:
![Eco_5tLVFvMRL0](https://user-images.githubusercontent.com/30538130/160278141-daa053d2-89ba-438c-97e5-4377e028dbed.png)

Pic of Setup:
Emoji's are the corner the Elevator Call Posts are set up on (on each floor). The Middle one had a problem on ground zero (roughly same height as Ind. Elevator) before the one on the right was even built. When I built another elevator on the right side, the problem got even worse.
![Eco_SPvXUtfflF](https://user-images.githubusercontent.com/30538130/160278379-3c387451-0329-4717-93c2-afd16eac371d.png)

**Comment by KevinGelking** [comment]
![image](https://user-images.githubusercontent.com/30538130/160278638-6b5858c3-38b3-4556-a2f9-969134e1a457.png)

**Comment by D3nnis3n** [comment]
Closing due to no required information provided.
