### ISSUE TITLE
Cart and rubbles bug becoming untargetable

### ISSUE THREAD

**Issue by oubould** [StrangeLoopGames/EcoIssues#23073]
I had the same problem yesterday before and I'm sending the logs now that it happened again.
My wood cart has become untargetable, just as my 2 wheelbarrows. I can interact with its storage if I access another storage nearby, but can't use it or hammer it.
Sometimes yesterday, disconnection mades it work again for a few seconds, goving me the opportunity to gather a few stones or putting them in the cart, then I had to dc again to repeat the process.
Now the cart is untargetable even with a dc. For the rubbles, I had the bug with stone and wood trunks rubbles yesterday and today I had the bug with wood trunks again.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8402727/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8402728/Player-prev.log)
.

**Comment by D3nnis3n** [comment]
Thanks! Tracked internally: https://app.clickup.com/t/10591183/ECO-20218
