### ISSUE TITLE
9.5 Staging 2275 - Unable to give water (used to work)

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23078]
Unable to do /give water anymore, was working in previous staging build like er 2260 or so? if not earlier

Does not appear if you search the devtool either

![image](https://user-images.githubusercontent.com/61889138/161641320-c14afa8a-017b-419b-b83e-64f7e62935bb.png)

**Comment by TwixterZ** [comment]
@MishkaFur Thanks for alerting me, issue is informed to our developer for fix

Internal use : https://app.clickup.com/t/2jfatk5

**Comment by MishkaFur** [comment]
Appears to be working in 2278

**Comment by TwixterZ** [comment]
@MishkaFur This was fixed on 2278 build
