### ISSUE TITLE
WT playtest, wheelbarrow became uninteractable [0.9.5.0 beta staging-2269]

### ISSUE THREAD

**Issue by missilerock** [StrangeLoopGames/EcoIssues#23074]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403096/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403097/Player.log)

Was shoveling clay / dirt into a wheelbarrow. First time I've had this happen to me. Can kick around the wheelbarrow, but no interacting options when mousing over. Believe I wasn't on any deed at the time, just close to the capital. Logging back in I can interact again after closing out of the game, and the wheelbarrow is at the location I pushed it to.
server id: 1901d46d-d6e9-4bd6-8c66-c05d59e69

**Comment by missilerock** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403130/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403131/Player.log)
it happened again, same general area. I stepped into the road district this time / transferred from a stockpile of clay into the wheelbarrow and it became uninteractible.

**Comment by missilerock** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403136/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8403137/Player.log)
ok got it to replicate within 30s. If you transfer items in or out of a stockpile on a road district, my wheelbarrow behind me becomes uninteractible. So idk if its all storage containers, some law bugging out around the road permissions stuff or what. Not going to post any more on here unless you guys want more info

**Comment by D3nnis3n** [comment]
Thanks! Tracked internally: https://app.clickup.com/t/10591183/ECO-20218

I'm closing this, but you can go on posting logs and updates, we'll still monitor and put into our internal issue.
