### ISSUE TITLE
9.5 Staging 2275 - Unable to give devtool 

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23080]
Doing /give devtool says it couldn't find a match, might be related to #23078 

Other admin commands are fine ie /give brick

![image](https://user-images.githubusercontent.com/61889138/161642936-cd604636-2ae6-4fd5-9a6d-871024311bb4.png)

**Comment by TwixterZ** [comment]
@MishkaFur Thanks for alerting me, issue is informed to our developer for fix

Internal use : https://app.clickup.com/t/2jfatk5

**Comment by MishkaFur** [comment]
Appears to be working in 2278

**Comment by TwixterZ** [comment]
@MishkaFur This was fixed on 2278 build
