### ISSUE TITLE
Alpha.6 [B8ce025e] Pipes: Open ends are working indoor

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2308]
![image](https://user-images.githubusercontent.com/3965439/30887647-8bb67a40-a31c-11e7-947a-600b5d632ad6.png)

**Comment by MarjieAVolk** [comment]
Think that's fine, @craig-jong?

**Comment by Fank** [comment]
@MarjieAVolk Pipes should not be allowed to output smog in rooms.

**Comment by MarjieAVolk** [comment]
I don't see why not
