### ISSUE TITLE
9.5 Staging 2290 - "Mortared Stone Door" no icon in Z skills menu

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23095]
Mortared Stone door has no icon in the skills Z menu, it does in ecopedia and other places

![image](https://user-images.githubusercontent.com/61889138/163876526-52a408bc-5a00-49ca-ad7f-5eb52ac8c147.png)

**Comment by Daniel-Magulado** [comment]
Hello @MishkaFur 

It's been a while and I hope you're doing great :D. Thanks for the report. Upon checking our internal database, a fix is already set and should be rolled out in the next build update. I'll keep this open for the meantime though just incase it doesn't fixed this specific spot/issue.
