### ISSUE TITLE
9.5 UI Server/Player Issues

### ISSUE THREAD

**Issue by rustysbro2** [StrangeLoopGames/EcoIssues#23098]
Player:
1: When you go to settings under the general tab and click **Set Play Time** The Number of the hour does not show up on the top of the graph.

Server:
1. If you set a playtime table on your server the server options are no longer visible such as Age, Online Players, WorldSize Etc
2. However if you don't have a playtime  table (server side) these options reappear.

**Comment by rustysbro2** [comment]
Update: When removing Detailed Description it also gets fixed

**Comment by D3nnis3n** [comment]
Thanks for the report, we are already tracking this one internally at https://app.clickup.com/t/10591183/ECO-21279.
