### ISSUE TITLE
USER ISSUE: Title Authorization not authorized to dig / build

### ISSUE THREAD

**Issue by gabgab01** [StrangeLoopGames/EcoIssues#23099]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.6 beta release-285

**Steps to Reproduce:**
1. make a new title
2. give person title
3. give claim authorization to that title
4. let person try to build / dig in that claim

**Expected behavior:**
since the title is authorized, that authorization should allow the title holder to do the same as if that title holder was given authorization directly

**Actual behavior:**
when trying to dig or build, even though the block appears green, digging is not possible, and the message "you are not authorized" pops up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and yes, since the mods only add items and don't mess with the title system or authorizations.
tested it on an unmodded server, same results

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be fixed in 9.5, please reopen if it reoccurs.
