### ISSUE TITLE
Property off by 1 in minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2309]
![image](https://user-images.githubusercontent.com/3536496/30888160-e352a06a-a2d3-11e7-8426-29cceb65d1ee.png)
I'm standing at 103,118, but the property extends to 104,119.  Need to increment x and z for property.

Note that the claim rendering in the world is correct.

**Comment by SeanAtr0n** [comment]
good catch, although why are your minimap settings so low?
