### ISSUE TITLE
9.5 2287 - Missing right margin for sensitivity options

### ISSUE THREAD

**Issue by Veredior** [StrangeLoopGames/EcoIssues#23094]
In the controls options , "Mouse sensitivity" and "Scroll sensitivity" have no right margin and overlap with the options border.
![eco_controls_sensitivity](https://user-images.githubusercontent.com/5888795/163771712-8407d2bd-7b26-48f1-8865-33e705016b85.jpg)

**Comment by tomesc99** [comment]
Hello @Veredior !

A ticket has been created and the issue will be fixed very soon. Thank you very much for your report!

_* For internal usage purpose: https://app.clickup.com/t/2kqfywg_

**Comment by Veredior** [comment]
Hello,

it's fixed on the playtest version.
