### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by StrawberryIchigo** [StrangeLoopGames/EcoIssues#23097]
I am on 0.9.4.6 Beta release-285, playing on a local server. Twice I hard crashed to desktop within 15 minutes. The first time was while looking at data in the skills screen, and the second time was just after opening a carpentry table. No one else on the server has crashed. Logs are attached.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8540974/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8540975/Player.log)
[log_220422084819.log](https://github.com/StrangeLoopGames/EcoIssues/files/8540989/log_220422084819.log)

**Comment by rustysbro2** [comment]
Have you tried to verify your steam  files or re-download

**Comment by StrawberryIchigo** [comment]
I'll try now. Didn't crash at all yesterday, I'll comment if I crash again.

**Comment by D3nnis3n** [comment]
I'm closing this as this is on the old version, please open a new issue if this issue reappears on 9.5.
