### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by nowy7o** [StrangeLoopGames/EcoIssues#23101]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
click continue

**Expected behavior:**
let me connect

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thank you, this is due to the server not having updated yet. I've created an internal issue to make the message more clear.
