### ISSUE TITLE
USER ISSUE: Cannot Join Server - Verison Mismatch?

### ISSUE THREAD

**Issue by Reztopian** [StrangeLoopGames/EcoIssues#23105]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Update to 9.5

Try and join a server that hasn't been updated.

**Expected behavior:**
Error message saying "Cannot join server" or "Server version is out of date"

**Actual behavior:**
Nothing happens. "Join" button is greyed out and doesn't give any reason as to why.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thanks for the report. The button actually is replaced by a greyed out version number that shows exactly which version is required to connect. So this works as intended and is not a bug, I'll note down the feedback for adding a "Version Mismatch" note above it, though.
