### ISSUE TITLE
USER ISSUE: Server Connection Error

### ISSUE THREAD

**Issue by emoore36** [StrangeLoopGames/EcoIssues#23104]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
1. On main menu screen, click 'Continue'

**Expected behavior:**
It should have connected me to the server:Guardian Gaming - Pre-set - Infrastructure - 5X Carry Weights - Med Collab - 4km - day 2 - 1 users online

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Player log**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8579104/Player.log)

**Comment by D3nnis3n** [comment]
Thank you, this is due to the server not having updated yet. I've created an internal issue to make the message more clear.
