### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by G14Chemical** [StrangeLoopGames/EcoIssues#23116]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
tried to log in to eco error pops up

**Expected behavior:**
should of opened allowed play

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mod installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This was likely related to the server that you tried to join not being updated to 9.5 yet while you used the 'continue' button. Please reopen the issue with more details if this issue persists.
