### ISSUE TITLE
USER ISSUE: Stuck in space

### ISSUE THREAD

**Issue by Fififux** [StrangeLoopGames/EcoIssues#23115]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Touched a bugging rabbit corpse

**Expected behavior:**
Flying a "little" bit	

**Actual behavior:**
Beeing stuck at 1582 blocks and not falling down, i can even jump to get some blocks higher

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can try /unstuck to get out, otherwise using the teleport command on singleplayer or as admin (or by an admin on multiplayer). The issue itself is a known rare one, similar to https://github.com/StrangeLoopGames/EcoIssues/issues/22947.

Keeping this one open for QA.
