### ISSUE TITLE
USER ISSUE: Stuck at 1669 blocks above ground.

### ISSUE THREAD

**Issue by SREILLIC** [StrangeLoopGames/EcoIssues#23119]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Climb ladder on rock, get stuck between ladder and rock, jump or move or something, get propelled into infinity...now stay. No, jumping only makes you go higher. Stay! Good boy (give doggy treat).

**Expected behavior:**
Not that

**Actual behavior:**
Witchcraft.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can try /unstuck to get out, otherwise using the teleport command on singleplayer or as admin (or by an admin on multiplayer). The issue itself is a known rare one, similar to https://github.com/StrangeLoopGames/EcoIssues/issues/22947.

**Comment by SREILLIC** [comment]
Thanks a bunch! Great game, btw. Glad I can keep playing it.

Yours truly

Charl
