### ISSUE TITLE
USER ISSUE: Arrastra sound bug

### ISSUE THREAD

**Issue by generalen18** [StrangeLoopGames/EcoIssues#23113]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Run the Arrastra.

**Expected behavior:**
At some point once it has finished it's job, the sound will continue looping

**Actual behavior:**
The sound should stop after animation has ended

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hey  @generalen18 ,

Thank you very much for your report! A task has been created and we will be working on it very soon.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-21627_

**Comment by generalen18** [comment]
Awesome, thank you very much :-)
I suppose you've already seen it, but I now see that 'expected' and 'actual behavior' is switched around :-/

**Comment by tomesc99** [comment]
Of course, no worries. Thank you once again for your report, this helps us to make the game better every day.

**Comment by generalen18** [comment]
Great :-D
You're very welcome :-)

Do we/I just close this now or how do this work? XD

**Comment by vysmirnov** [comment]
Sound bugged not only on arrastra but other machines: Kiln, Screening machine, Stamp mill

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! This has been fixed in the upcoming 9.6 release
