### ISSUE TITLE
USER ISSUE: Tree can't break

### ISSUE THREAD

**Issue by CaptainHamBeard** [StrangeLoopGames/EcoIssues#23128]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
1. Chop down tree
2. try to chop into logs

**Expected behavior:**
It should make logs and be green

**Actual behavior:**
It is indestructable and wont moke logs then a relog makes it disapeer

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Bazzi89** [comment]
Some players get this sometimes too at my server.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20414
