### ISSUE TITLE
USER ISSUE: serveur authentification en panne 

### ISSUE THREAD

**Issue by Eternios** [StrangeLoopGames/EcoIssues#23125]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
serveur authentification en panne

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Les informations de connexion n'ont pas pu être vérifiées. Nos serveurs d'authentification peuvent être en panne.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non,et non ...

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please make sure that Eco can reach our authentication servers, especially make sure that any antivirus software is disabled or an exception for Eco is created. This error is a network error between you and our servers and not related to a game bug.
