### ISSUE TITLE
Alpha.6 [d9d6f47c] Log should show nothing on join

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2312]
![image](https://user-images.githubusercontent.com/1900106/30904251-b89b8f8c-a371-11e7-8aa1-a5472eb81472.png)

**Comment by MarjieAVolk** [comment]
This used to work, so I'd say it's a bug

**Comment by MarjieAVolk** [comment]
Apparently this is because WorldTime.Seconds is not initialized yet when chat gets initialized
