### ISSUE TITLE
USER ISSUE: Why is there no way to turn off motion blur?

### ISSUE THREAD

**Issue by Gameboy4ever** [StrangeLoopGames/EcoIssues#23122]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Play the game

**Expected behavior:**
There should be a way to turn off motion blur, it is nauseating!

**Actual behavior:**
There is no way to turn off motion blur. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Eco does not have motion blur, hence there is no way to turn it off.
Please check if there is any settings via your graphics card driver that manipulates Ecos graphics settings.
In any case, this is not a bug.

**Comment by D3nnis3n** [comment]
So, I was intrigued by this, because Motion Blur is the first thing I turn off in any game but was not able to get any motion blur in Eco. Can you send me a video of where you think you see motion blur to dennis@strangeloopgames.com? I'd take a look if I get that as well.
