### ISSUE TITLE
USER ISSUE: server search does not work

### ISSUE THREAD

**Issue by no1s1a** [StrangeLoopGames/EcoIssues#23127]
\
**User Id: slg218480**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
opening the game
I open the server search
There are no servers in the search
When trying to connect to the server via IP, it gives an error
Search in other games work

**Expected behavior:**
server search 

If I change connections from the router to the phone, then the search starts working, but I 
don't understand why! Everything works in other games

**Actual behavior:**
The following error message was received:
```
<size=150%>Connection error</size>

Failed to connect - the connection time has expired.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Game without modifications

**[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8597819/Player.log)

**Comment by D3nnis3n** [comment]
Your router or security software is blocking our authentication servers, please make sure that our authentication servers can be reached.
