### ISSUE TITLE
USER ISSUE: Wanted: Max button

### ISSUE THREAD

**Issue by Zaanzabar** [StrangeLoopGames/EcoIssues#23133]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
When crafting, due to changes in ratio due to skill, sometimes it is very difficult to figure out how many orders you can produce.

**Expected behavior:**
Button to make max orders you can with current available inventories

**Actual behavior:**
guess and check

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing due to not being a bug. Noted as suggestion.
