### ISSUE TITLE
Contract board & distribution station form bugged

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#23139]
U can't insert a number in the amount field, we want 100 Arrows to deliver to the newcomers -> have to click the "+" button for amount, if put 100 in the amount field it falls back to 1

Same issue at contract board

**Comment by Daniel-Magulado** [comment]
Hi @Bazzi89 

Thank you for submitting this bug report. We tested this issue on our end and it seems to be working fine. The only issue we have seen so far is when you click on the + button after manually typing the value like 100. It adds 1 to the former value which is 1. Could you provide us with a recorded video of this issue that you are encountering so we can investigate further?

Looking forward to your response.

**Comment by Bazzi89** [comment]
Hey @Daniel-Magulado 

here a link for the distribution station: https://drive.google.com/file/d/1kiV_RsINz36kzX5pCvkBGhPMszZ0iid-/view?usp=sharing

**Comment by Bazzi89** [comment]
and this one for contract board: https://drive.google.com/file/d/1jYOgXMi1cuGhHcTMWPYH9QPHafdfC41j/view?usp=sharing

**Comment by bobbahbrown** [comment]
This may be related to network latency, if that helps. My server has experiencing fairly regular latency, so maybe that factors in to sending the updated quantity to the server properly.

**Comment by D3nnis3n** [comment]
Has been fixed in 9.5.1.
