### ISSUE TITLE
USER ISSUE: storage link distance reverts to default after restart (single player).

### ISSUE THREAD

**Issue by Micro753** [StrangeLoopGames/EcoIssues#23135]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
1. Create new single player world with a storage link distance greater than 1
2. Place and link a crafting station and a stockpile at a distance that is greater than the default linking distance
3. Restart game.

**Expected behavior:**
Linked inventories remain linked after restart.

**Actual behavior:**
Reverts to default distance, which causes stations beyond the default distance to not show in the storage tab of previously linked crafting stations. Issue can be fixed by picking up and replacing crafting stations and/or stockpiles.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Aaronc0123** [comment]
Same issue occurs in multiplayer dedicated servers, same steps as listed above to reproduce in a multiplayer server.

**Comment by BartonsGit** [comment]
Reproduced this with a fresh installation:

- Starting multiplier for linked inventories was set to 5x.
- Placed 2 storage chests and 2 Campfires at a random interval.

Before:
![1](https://user-images.githubusercontent.com/1343858/166842774-ed6758fc-cf10-4dc3-9f31-ca52e2cfe1a3.png)


After the game was restarted:
![2](https://user-images.githubusercontent.com/1343858/166842792-bc014367-305f-4f56-aa65-70d35406efdb.png)


After Campfire was picked up and placed:
![3](https://user-images.githubusercontent.com/1343858/166842892-8f21ca8d-0bf1-4177-a75c-038546595c6e.png)

**Comment by BartonsGit** [comment]
Is this an object pooling issue for linked inventories? Noted the following in my player log.

```log
[07:37:50.523] LinkedInventory doesn't support pooling. It may cause problems in runtime. 
Either add [SupportsPooling] attribute to all it's and it's children components or implement pool supporting interface(s) (IPoolRentAware, IPoolReturnAware). For third-party components you can use PoolingExtensions.RegisterPoolableType. 

List of components missing pooling support: 
LinkedInventory (StorageManualTooltipSwitcher), TransparencyParent (FastGameObject), Header (FastGameObject), ArrowParent (FastGameObject), Controllers (FastGameObject), Weight (FastGameObject), TogglesLayout (Comments), TogglesLayout (FastGameObject), Storage (FastLayoutGetPreferredSizeForDisabledObject)
```

**Comment by Rambo99** [comment]
I confirm. I had something similar. True, not horizontally (horizon), but vertically. One storage (stokpil) stood on the ground, and the second at the height of the 3rd floor (1st floor - 5 blocks in height), approximately at a height of 12-15 blocks. There were several different machines (workstations) around, and when the game and the server were restarted, some machines (stations) "did not see" the upper storage (stockpile) (they lost connection, configuration), it was necessary to reconfigure (reconnect) the workstations (machines).

**Comment by ShadedFlash** [comment]
Can also confirm this bug. Players must empty the stock pile, pick it up and put it back down after every server restart. Very inconvenient.

**Comment by ShadedFlash** [comment]
Please give this bug attention, this is becoming very aggravating to players and causing them to not want to play.

**Comment by D3nnis3n** [comment]
Should be fixed.
