### ISSUE TITLE
USER ISSUE: Chat off screen

### ISSUE THREAD

**Issue by csneon2000** [StrangeLoopGames/EcoIssues#23136]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Log into a server. Half of chat is off the screen. 
Go into option and adjust GUI scale or reset graphics options. Chat goes back to normal.
Log out of game and back in and chat is cut off again.

**Expected behavior:**
All of chat on the monitor.	

**Actual behavior:**
Half of chat is cut off

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8600727/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8600728/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @csneon2000 

Thank you for submitting this bug report. Could you provide us with a screenshot and a recorded video? 
It will help us investigate this issue further since it seems to only occur in certain conditions that we are still not aware of.
Looking forward to your response.

**Comment by csneon2000** [comment]
![20220505150849_1](https://user-images.githubusercontent.com/26682732/167025949-d1349965-1f59-40d5-b59f-62c3f4cbf55b.jpg)

https://user-images.githubusercontent.com/26682732/167031778-f5de0476-3838-4f96-bf18-7e5b22943dc1.mp4


I did forget to mention that I am on an ultrawide monitor.

**Comment by Daniel-Magulado** [comment]
Hi @csneon2000 

Are you able to drag the chat? You can do so by hovering your mouse cursor over at the top of the chatbox. You can then click hold to drag the chat. It's a new feature of the chat that allows you to reposition the chat wherever you please on the display.

If not, let me know and we will investigate if chat is having issues with the ultrawide display.

**Comment by csneon2000** [comment]
I am able to move the chat and it stays where I put it. I have both exited the game and to the main menu.

**Comment by Daniel-Magulado** [comment]
Hi @csneon2000 

That's great. Just to verify, are you still experiencing this 'Log out of game and back in and chat is cut off again.' after moving the chat out of the initial position it was?

**Comment by csneon2000** [comment]
I am no longer experiencing chat being cut off. Thank you for you time.

**Comment by Daniel-Magulado** [comment]
Hi @csneon2000 

I'm glad to know that we have addressed your concern. Thank you for taking the time to submit this report. If you ever still find this issue recurring for you from time to time or find anything that may annoy you or a bug, please do not hesitate to submit a report. If there's anything else I can do for you please do let me know. For now, I'll go ahead and close this thread.
