### ISSUE TITLE
[Bug] Brick wall not connecting to brick block

### ISSUE THREAD

**Issue by jemmotion** [StrangeLoopGames/EcoIssues#23144]
The brick wall will not connect to the brick block to form a corner and thus leaves a huge annoying gap.

![20220502182054_1](https://user-images.githubusercontent.com/90909384/166338351-4b04ea88-19d3-4e19-b445-05c95af5d848.jpg)

**Comment by D3nnis3n** [comment]
Thanks for your report. Unfortunately this works as intended and hence is not a bug. We already received a suggestion to change the wall block, so no further action is needed :)

**Comment by D3nnis3n** [comment]
Hey, thanks for your answer - just to make sure:
This works as intended and is not a bug. There is no plans to change this behaviour, but it was suggested before. So I cannot guarantee that this will ever be changed. If we do, we might actually rather introduce other wall types that do connect.
