### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Sarah4Violets** [StrangeLoopGames/EcoIssues#23147]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Cannot log into game.

**Expected behavior:**
Normally game runs.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please make sure you are online and disable any antivirus you are using (or make an exception for Eco) as well as anything else that might block your connection. This is not a bug, but a local issue, so further help may be seeked via support@strangeloopgames.com.
