### ISSUE TITLE
You can place two modules in machine's module slot instead of one module

### ISSUE THREAD

**Issue by vysmirnov** [StrangeLoopGames/EcoIssues#23149]
Version: 0.9.5.0 beta release-301 
Single player game
Steps to reproduce: 
1) Place 2 or more modules in single inventory cell
2) Open modules tab of machine
3) LMB on modules in inventory
=> two modules will be placed in the module slot instead of one module. You also can pick up all those modules from that slot.

**Comment by BartonsGit** [comment]
@vysmirnov - I attempted to reproduce this with a Campfire and Basic Upgrade 1.

I was able to drag a stack of 5 Basic Upgrade 1 into the Module for the Campfire, but only 1 was deposited into the slot.

Can you add the type of machine and the module you are using?

**Comment by vysmirnov** [comment]
@BartonsGit - I tried to drag a stack of 4 Basic upgrade 4 into Campfire and 2 was deposited. 
Maybe it's not obvious, but there is no count mark in Modules slot. And size of stack reduced by 2.
You can also Alt+Click on Module slot and take back one of two modules.
Here is video: https://youtu.be/D3vJSV3fWw8

**Comment by ShadedFlash** [comment]
I can confirm this issue happens across all crafting tables. When putting basic upgrades into arrastras, rocker boxes, etc, or putting advanced upgrades into anvil, kiln or bloomery, they had to be put in 1 at a time or it would stack them all into the crafting table and not show the number of modules in it

**Comment by D3nnis3n** [comment]
Should be fixed.
