### ISSUE TITLE
USER ISSUE: Things not usable

### ISSUE THREAD

**Issue by marcelmuecke** [StrangeLoopGames/EcoIssues#23146]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Issues:**
I'm in a singleplayer world having multiple issues that are quite similar:

1. When I chop down a tree, sometimes I can't cut it into smaller pieces - the tree isn't even highlighted. I can remove the stump and pulp, though. Sometimes I can do it again a few minutes/hours later. It seems quite random, but it seems to happen more often as I go further in the game.

2. Some doors "disappear" from time to time and come back some time later. They are visible, but I can't interact/remove with it and I can just walk through it without opening.

3. Same with my wooden cart.

4. When I cut down stones, I can collect the pieces and/or cut down the yellow higlighted ones only after they didn't move for a few seconds - otherwise they aren't even highlighted and I can just use my pickaxe on the stone behind the one I try to cut into smaller chunks. This didn't happen for the first few hours in the game, but now it does for every single stone.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods at all.

**Log files:**
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8612048/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8612049/Player.log)

**Comment by marcelmuecke** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8612048/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8612049/Player.log)

**Comment by marcelmuecke** [comment]
Restarting the game solved the issue for now, I'll keep you updated.

**Comment by D3nnis3n** [comment]
QA, likely dup of: https://github.com/StrangeLoopGames/EcoIssues/issues/20414
