### ISSUE TITLE
Game is almost to dark to play even during the day #d9d6f47

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2315]
i don't even have Dark Nights chosen (trying setting on even lowest), and have Stone braziers down, finding it almost impossible to see to do much and thats during daylight hours as well

**Comment by Conchipedia** [comment]
linking to #2314

**Comment by Conchipedia** [comment]
![snap434](https://user-images.githubusercontent.com/29383891/30913040-ad004234-a386-11e7-826c-9a4b9e5bb52c.png)
![snap435](https://user-images.githubusercontent.com/29383891/30913098-e3bbd054-a386-11e7-89e9-e40ae6749ef7.png)

**Comment by Conchipedia** [comment]
![snap437](https://user-images.githubusercontent.com/29383891/30913147-0a621e70-a387-11e7-8380-4507d82d2092.png)

could do with set time to Noon back (saw it was removed)

**Comment by Conchipedia** [comment]
![snap438](https://user-images.githubusercontent.com/29383891/30913219-5d8dbd5c-a387-11e7-954b-6b9dd88fab97.png)
![snap439](https://user-images.githubusercontent.com/29383891/30913225-630494cc-a387-11e7-8175-0df8ba25fd6d.png)

**Comment by Conchipedia** [comment]
this like selecting away door is facing inside a room even lit with 4 stone brazier is almost impossible to see which way its facing 
![snap440](https://user-images.githubusercontent.com/29383891/30913475-3d0c5fec-a388-11e7-800d-7c61d12b943a.png)
![snap441](https://user-images.githubusercontent.com/29383891/30913476-3d2b1590-a388-11e7-86e1-96430f8f942f.png)
![snap442](https://user-images.githubusercontent.com/29383891/30913474-3d0ad00a-a388-11e7-943b-f88d41806152.png)

was a bit better coming out of the room to see which way door was facing

**Comment by Conchipedia** [comment]
![snap443](https://user-images.githubusercontent.com/29383891/30913617-c7dd1b48-a388-11e7-98ec-63031400fd5b.png)
![snap444](https://user-images.githubusercontent.com/29383891/30913630-cf029e7a-a388-11e7-86b6-1364389b09ef.png)
same place with torch on and off

**Comment by Conchipedia** [comment]
would it be possible to implement slider for brightness and/or contrast to the slider menu? (it could also help playerd who have dark or overbright monitors)

**Comment by metachronism** [comment]
try new changes in upcoming build - trying to find the right balance for lighting

**Comment by Conchipedia** [comment]
ok, will do, just out of curiousity when we changed settings are they stored on PC? if they are where? that way i can delete old ones and just let it choose default (i dont really want to change too much stuff and lose what is basic)
