### ISSUE TITLE
Mashine dependences updates only when other mashine placed/removed or restart server.

### ISSUE THREAD

**Issue by vysmirnov** [StrangeLoopGames/EcoIssues#23150]
Version: 0.9.5.0 beta release-301
Single player game
Steps to reproduce:
1) Make tier 2 room
2) Place machinist table => it requires shaper and screw press
3) Place shaper in same room => machinist table updates status, but shaper didn't.
=> Machinist table sees shaper, but shaper sees no machinist table.
4) Pick and replace machinist table
=> now shaper sees machinist table, but machinist table sees no shaper
5) Restart server => all dependences works until replacing one of those machines

**Comment by vysmirnov** [comment]
Also state updates when placing other machine with no dependences in room

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23162
