### ISSUE TITLE
[9.5] - Debts don't clear out when repaid of forgiven then reset to full amount

### ISSUE THREAD

**Issue by Asharas** [StrangeLoopGames/EcoIssues#23156]
When players pay their debt or debt is forgiven, the line stays present with amount at 0.  
The amount is reset to full after the player who offered the loan logs out and in again and the borrower still sees it aswell.  
Job contract has been marked as finished.  

Loans were 168H long with 10% interests of personal currency.  

Tested with a 10 credits/24H/0% loan on the spot with a player, didn't have the issue and debt disappeared as soon as it's forgiven.  
I currently don't know what triggered this.  

Admin command /money cancelalldebtfromplayer <player> does clear the debt.  

World save link (valid 1 month): https://demo.jirafeau.net/f.php?h=3-QR0UZh

**Comment by Asharas** [comment]
I accepted a minted currency loan a few hours ago and bug is triggered again.  
The server has been restart between accepting and trying to repay so that might be the trigger.

**Comment by D3nnis3n** [comment]
This should be fixed in 9.5.1, please reopen if it reoccurs.
Attention: The fix is NOT retroactive.
