### ISSUE TITLE
USER ISSUE: Some World objects with fuel inventories consume fuel at an alarming rate

### ISSUE THREAD

**Issue by suniahk** [StrangeLoopGames/EcoIssues#23151]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.0 beta release-301

**Steps to Reproduce:**
Not entirely sure, but here's the setup.
 - 1 Steam Engine, originally unowned but now on a single plot. 
 - 2 Blast Furnaces on a different player's property.  Both Blast Furnaces created by the same player, one placed by the creator and one by the owner of the property.  Both have Advanced Smelting Upgrades in them.
 - 1 Mechanical Water pump powered by a water wheel.
 - 1 Waste Filter.
 - Waste Filter and Blast Furnace are linked to a Large Lumber Stockpile; Both blast furnaces are also linked to a chest (both storages allow both input and output of materials/goods)

**Expected behavior:**
Consumed fuel at a normal rate, more-or-less in line with estimates.

**Actual behavior:**
 - Steam Engine would use 2 coal/charcoal per minute regardless of who added the fuel, and regardless of how it was added (ctrl alt click, shift drag, etc), while unowned.  Fixed once plot was claimed.  Started after patching to 9.5.
 - One blast furnace is fine, the other has the same fuel consumption rate as the previously mentioned Steam Engine.  Rapid fuel consumption on blast furnace only started within the last 12 hours.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.  Both local install and remote server are vanilla.

Logs:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8627835/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8627836/Player.log)

Screenshot of current fuel state, Only quicklime is queued (396) and status shows all green except for the "Out of Fuel" status.
![Screenshot 2022-05-04 184956](https://user-images.githubusercontent.com/2336805/166837977-99a0c40a-bdde-4056-aeb6-1234c512d568.png)

**Comment by suniahk** [comment]
Update: Picking the Blast Furnace up and putting it back down in the same spot fixes the issue, will update if it occurs again.

**Comment by D3nnis3n** [comment]
Were any of the new difficulty settings like fuel multiplayer modified and is this reproducable for you?

**Comment by suniahk** [comment]
No difficulty settings were touched.  The only modification to default settings is an increase to the points multiplier to increase xp gained by 25%.
This only happened after the update to 9.5.  There were no issues prior to that.  
Currently I'm not entirely sure what causes the bug to happen.  I've tried various fuels while accessing the blast furnace, as well as various ways to add full stacks in.  I'll play around with it a bit more; if I can figure out how to reproduce it consistently I'll update the ticket.

**Comment by D3nnis3n** [comment]
Can you pack me your /Steam/steamapps/common/Eco/Eco_Data/Server/Configs folder?
