### ISSUE TITLE
USER ISSUE: World not loading and removde stockpiles

### ISSUE THREAD

**Issue by Smokiiee** [StrangeLoopGames/EcoIssues#23166]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.1 beta release-310

**Steps to Reproduce:**
Restarted server and still no proggress 

**Expected behavior:**
Loaded and showd

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/23169
