### ISSUE TITLE
USER ISSUE: elevators

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#23167]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.1 beta release-310

**Steps to Reproduce:**
2 people on a elevator  or 2 people and a vechile psh the button to go up or down but only 1 person goes or the vechile falls through the elevator

**Expected behavior:**
both people and vechiles should go down and up at the same time

**Actual behavior:**
second person doesnt go down wiith elevator	vechile falls through elevator

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/20738
