### ISSUE TITLE
[Bug][0.9.5.0] Invisible Machinist table

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#23162]
Screw press , Lathe , Shaper do not see already installed Machinist Table during installation.
Bug reproduction procedure:
1. install Machinist table;
2. install Screw Press;
3. inctall Shaper;
4. install Lathe.

Explanation:
The first and second points work together without problems (they see and work perfectly with each other), the problems begin with point 3. If you try to reinstall Machinist Table , then the problem appears everywhere.
![20220511202252_1](https://user-images.githubusercontent.com/1098421/167914761-1d0045ee-f747-4b75-977b-698c95829136.jpg)
![20220511202258_1](https://user-images.githubusercontent.com/1098421/167914796-ed0f7f99-1cd3-4618-bd16-722373fcb681.jpg)
![20220511202119_1](https://user-images.githubusercontent.com/1098421/167915265-2d2cd79c-4655-4c4f-b1ed-03e101c9f8bc.jpg)
![20220511202311_1](https://user-images.githubusercontent.com/1098421/167915300-c5b7dc34-8e8f-46ad-b536-79c3ee836344.jpg)
![20220511202344_1](https://user-images.githubusercontent.com/1098421/167915320-80fcdbce-47cc-47c7-9fd0-c7c1d2ff3a2d.jpg)
![20220511202413_1](https://user-images.githubusercontent.com/1098421/167915346-8e330211-d4a3-40de-8aee-50de47010e6e.jpg)
.

**Comment by vysmirnov** [comment]
Same as mine:
https://github.com/StrangeLoopGames/EcoIssues/issues/23150
You can place any block or machine in the room to call update action.

**Comment by Rambo99** [comment]
> Same as mine: #23150 You can place any block or machine in the room to call update action.

Yes, I agree. Can be combined into one theme. However, the addition of the desktops I mentioned (shaper and lathe) amplifies this bug, showing it in all its beauty.

**Comment by Rambo99** [comment]
In the latest patch (game version 0.9.5.1), the bug has not been fixed.
Additionally - if you try to move the specified equipment to another place, the bug appears again from point No. 2 indicated in the first post. After restarting the server, the bug disappears, but only until the moment the player tries to move the equipment to another location
![20220514181334_1](https://user-images.githubusercontent.com/1098421/168439904-9de11809-b180-4b8a-8670-49b918162210.jpg)
![20220514181213_1](https://user-images.githubusercontent.com/1098421/168439923-60f8d215-de68-4f82-be70-2b8dee5e571a.jpg)
![20220514181521_1](https://user-images.githubusercontent.com/1098421/168439934-4151bcdd-6db5-476e-8d3f-ef9209da70fa.jpg)
![20220514181712_1](https://user-images.githubusercontent.com/1098421/168439946-4d2f293d-126a-4e18-94fe-a05adaca412e.jpg)
.

**Comment by D3nnis3n** [comment]
Should be fixed.
