### ISSUE TITLE
USER ISSUE: Inventory Max Weight Bug

### ISSUE THREAD

**Issue by ShadedFlash** [StrangeLoopGames/EcoIssues#23177]
Version: 0.9.5.1

We set the item weight multiplier on our server to 0.01. Items will weigh almost nothing, but when relogging onto the server after a server restart, the player's max weight will register as 208kg of 35kg max weight and cannot lower this amount by removing items or relogging. Even when inventory is completely empty, weight will remain over max weight and player cannot pick up any new items.

It occurs around a server restart and reproducible in these steps and screenshots:

Inventory weight before server restart:
![image](https://user-images.githubusercontent.com/85042649/168531425-df936565-165c-451a-a98d-a60bad25d122.png)

Inventory weight after server restart:
![image](https://user-images.githubusercontent.com/85042649/168531405-2cb880b8-1102-44cd-ac89-a7f08fe31bf5.png)

Inventory weight after emptying inventory:
![image](https://user-images.githubusercontent.com/85042649/168531382-c0ea9587-f81d-4586-afc5-f697cf35acb7.png)

**Comment by PvtJokers** [comment]
This is an issue that has brought 3 servers I have been on to a halt. Everyone is stopping game play to wait for this fix. It needs some urgency.

**Comment by Rosesfromno1** [comment]
This is a huge issue! Was hoping for a fix with the last update. Seriously why is this not fixed yet? Have not been able to play normally since this broken 9.5 update! Please resolve it asap!

**Comment by tomesc99** [comment]
Hey everyone,

Thank you very much for your reports and we apologize for the problems caused. The good news is that this issue has been found and fixed. The fix will be applied very soon.

**Comment by ShadedFlash** [comment]
Cheers, look forward to the update.

**Comment by D3nnis3n** [comment]
Should be fixed.
