### ISSUE TITLE
9.5.1 - Proposed law says "passed by executive action"

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23179]
![image](https://user-images.githubusercontent.com/61889138/168675297-8cee0538-f761-443a-b26e-a87618e96a83.png)

law is proposed and using Basic election, it has not been passed by an executive action

**Comment by tomesc99** [comment]
Hey @MishkaFur ,

Thank you very much for your report! A ticket has been created.

_* For internal usage purpose: https://app.clickup.com/t/2rj00yg_

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! This has been confirmed to be fixed in the upcoming 9.6 release
