### ISSUE TITLE
USER ISSUE: Erro ao carregar o mundo proprio.

### ISSUE THREAD

**Issue by Boguhez** [StrangeLoopGames/EcoIssues#23184]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
1. Seleciono o mundo, clico em carregar e ele dá mensagem de erro.

**Expected behavior:**
Deveria abrir o meu servidor, mas da essa mensagem de erro, impossibilitando que eu continue a jogar com o meu proprio mundo. Consigo conectar em Servidores Oficiais, mas não consigo conectar no meu proprio mundo.

**Actual behavior:**
A seguinte mensagem de erro apareceu:
```
<size=150%>Falha na Conexão</size>

As informações de login não puderam ser verificadas. Nossos servidores de autenticação podem estar offline.

<size=60,00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Não. Nenhum MOD instalado.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Boguhez** [comment]
- Já tentei acessar o jogo utilizando a conta da steam (como sempre fiz, antes de aparecer esse erro) como tambem fui na "play.eco" e criei uma conta e vinculei a minha conta steam na conta criada.
- Tentei tambem executar em modo administrador, e não consegui.

Esse erro apareceu depois que um amigo meu disse que não estava conseguindo conectar no meu servidor e informou que tinha um update pra fazer... depois de aguardar o update automatico da steam e não dar em nada, verifiquei os arquivos pela propria steam, baixou dois arquivos e depois disso, não consigo mais conectar na minha cidade.

- Tentei tambem executar um mundo antigo como tambem criar um novo mundo, e não consegui tambem.

**Comment by Boguhez** [comment]
![image](https://user-images.githubusercontent.com/26682564/169187914-ad27a3b9-b44f-41e4-9142-379d679755c9.png)

**Comment by D3nnis3n** [comment]
This is a networking problem of you reaching our authentication servers.
Please make sure you have not antivirus active or an exception for Eco made and ensure that connectivity is present.
You can test connectivity via a VPN. In general, this is a support issue, not a bug, so feel free to reach out to support@strangeloopgames.com.
