### ISSUE TITLE
Alpha.6 [d9d6f47c] Sunshine in Dungeon

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2318]
![image](https://user-images.githubusercontent.com/1900106/30916368-878e3746-a399-11e7-9043-6756140fe58b.png)
![image](https://user-images.githubusercontent.com/1900106/30916374-8ac3feaa-a399-11e7-973b-56da44d9164f.png)

**Comment by metachronism** [comment]
fix pending
