### ISSUE TITLE
USER ISSUE: No assigned products

### ISSUE THREAD

**Issue by AtemShane** [StrangeLoopGames/EcoIssues#23195]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
1. Launch Game
2. Try to join or create a world

**Expected behavior:**
start or join a world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User doesn't have any assigned products</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Contact support@strangeloopgames.com with your SLG ID to resolve.
