### ISSUE TITLE
Broken Toolbar

### ISSUE THREAD

**Issue by AlwaysquANtuM** [StrangeLoopGames/EcoIssues#23190]
Version of Eco 0.9.5.2

Added custom item class file to the UserCode folder on a LAN server. Upon loading the server and placing the item, the toolbar broke and still displayed the item as still in the hotbar.

Server/player logs:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8747148/Player.log)
[log_220520085516.log](https://github.com/StrangeLoopGames/EcoIssues/files/8747146/log_220520085516.log)
e

slgid: slg218530

**Comment by D3nnis3n** [comment]
Mod caused issue, hence closing.
