### ISSUE TITLE
Alpha.6 [d9d6f47c] Weird block/chunk behaviour

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2319]
https://loli.temel.me/yXbZ4tYNMxmtMzAHqhmMIQjCcM7p3nXi.gif    
https://loli.temel.me/AS4oa7y9lvXcvMrcmwK48n7y0SLQrYMm.gif

**Comment by Fank** [comment]
![image](https://user-images.githubusercontent.com/1900106/30920892-64345e0e-a3a5-11e7-91e0-3ee4f184e745.png)

**Comment by Fank** [comment]
You can walk over it, but you'll get no walking sound and no interaction highlighting.

**Comment by Fank** [comment]
Also some people noticed that if you walk a longer way buildings won't appear, reconnect will fix it.

**Comment by Fank** [comment]
After some reconnects its fine again:
![image](https://user-images.githubusercontent.com/1900106/30927875-2f8f2a66-a3ba-11e7-850d-b6aff774c1ac.png)

**Comment by metachronism** [comment]
fixed
