### ISSUE TITLE
Crushed Mixed Rock Sticks to Ceilings

### ISSUE THREAD

**Issue by SparkitusMax** [StrangeLoopGames/EcoIssues#23198]
I am playing on the White Tiger server and have noticed that Crushed Mixed Rock does not behave as normal Crushed rock.  You can place it unsupported on a ceiling and it stays there

**Comment by tomesc99** [comment]
Hello @SparkitusMax , 

Thank you very much for your report! A task has been created and it will be fixed very soon.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-22087_

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm it has been fixed on the latest playtest build.
