### ISSUE TITLE
USER ISSUE: Grass/trees on top of dirt stockpiles

### ISSUE THREAD

**Issue by Tindog33** [StrangeLoopGames/EcoIssues#23203]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
Put dirt in stockpile until it is full. Then wait for the grass to grow. Remove all the dirt. The grass stays behind and doesn't go away.

**Expected behavior:**
The grass should have died and not floated in the air.

**Actual behavior:**
The grass wouldn't die after the dirt was removed and continued to float in the air. This happens on stockpiles of dirt only.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @Tindog33 ,

Thank you very much for your report! The issue has been confirmed and a task has been created, it will be fixed very soon.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-22088_

**Comment by Tindog33** [comment]
Thank you, love the work you do hope we can make it better!

**Comment by SlayksWood** [comment]
I close this issue as dup #6902. All information will be in that task
