### ISSUE TITLE
USER ISSUE: Animal going through the ground

### ISSUE THREAD

**Issue by ReiParasita** [StrangeLoopGames/EcoIssues#23204]
User Id: Rei_Parasita
Version: 0.9.5.2 beta release-315

Steps to Reproduce:
Unknow

Expected behavior:
The animal should be on top, not inside the ground.

Actual behavior:
The animal was resting inside a ground block and the block was affected by the Steel Road Tool.

Do you have mods installed? Does the issue happen when no mods are installed?:
No

Footage of the happening*:
https://drive.google.com/file/d/1qwND8TyoJ6MlZxycbBz_eH8DyIdAp4Rv/view?usp=sharing

*The FPS is low at the beginning of the video but it was due to the video recording.

**Comment by SlayksWood** [comment]
merged to this issue https://github.com/StrangeLoopGames/EcoIssues/issues/23206
