### ISSUE TITLE
USER ISSUE: Crab death put his body at solid ground, even while swimming

### ISSUE THREAD

**Issue by ReiParasita** [StrangeLoopGames/EcoIssues#23207]
User Id: Rei_Parasita
Version: 0.9.5.2 beta release-315

Steps to Reproduce:
Simply kill a crab while it's swimming above ground.

Expected behavior:
The crab should stay in the same position after its death.

Actual behavior:
The crab is put on solid ground, no matter how deep is the ground.

Do you have mods installed? Does the issue happen when no mods are installed?:
No

Footage of the happening:
https://user-images.githubusercontent.com/25543840/170716250-fe306224-efa2-43a2-85d0-531995751c01.mp4

**Comment by SlayksWood** [comment]
@ReiParasita Thank you for the report add this bug to Crab improvement issue.

_*For internal usage purpose:_ https://app.clickup.com/t/10591183/ECO-12907
