### ISSUE TITLE
USER ISSUE: Canceling bow attack leaves its red trail visible

### ISSUE THREAD

**Issue by ReiParasita** [StrangeLoopGames/EcoIssues#23208]
User Id: Rei_Parasita
Version: 0.9.5.2 beta release-315

Steps to Reproduce:
A simple click on the mouse (don't hold it) will make the character pull the bow and put it away but its red trail (the aiming arc) will remain visible near the character's position.

Expected behavior:
The red trail should only be visible while pulling the bow.

Actual behavior:
The trail remains visible till you complete the bow's pulling animation completely.

Do you have mods installed? Does the issue happen when no mods are installed?:
No

Footage of the happening:
https://user-images.githubusercontent.com/25543840/170718946-dbf30ecc-a410-43f5-a577-4f66d1d2f44b.mp4

**Comment by SlayksWood** [comment]
@ReiParasita Thank you for the report. This issue is fixed in 9.6 version. Closed.

_*For internal usage purpose:_ https://app.clickup.com/t/10591183/ECO-17843
