### ISSUE TITLE
Alpha.6 [d9d6f47c] Curved/Standard issues with torch

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2321]
![image](https://user-images.githubusercontent.com/1900106/30922142-8c824ab2-a3a8-11e7-9f00-55636005d823.png)
![image](https://user-images.githubusercontent.com/1900106/30922157-954c7f64-a3a8-11e7-8b40-817b2f2c4c72.png)

**Comment by MarjieAVolk** [comment]
Is this separate from https://github.com/StrangeLoopGames/EcoIssues/issues/2222?

**Comment by Fank** [comment]
Not really but, it could be reproduced with torch so i separated it.

**Comment by MarjieAVolk** [comment]
Okay thanks, I'm going to move it over there, will probably be useful context there
