### ISSUE TITLE
[0.9.5.2 beta] [Ecopedia] eat not in right category

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#23217]
- Roast Pumpkin
- Worldly Donut
- Huckleberry Fritter

Requires Baking Skill, but in Ecopedia Cooking category

@WeaselDog

**Comment by SlayksWood** [comment]
@StallEF Thank you for the report, the issue was confirmed

_*For internal usage purpose:_ https://app.clickup.com/t/10591183/ECO-22108

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! It has been fixed in the upcoming 9.6 update
