### ISSUE TITLE
USER ISSUE: Sardine and Jellyfish vanishes

### ISSUE THREAD

**Issue by ReiParasita** [StrangeLoopGames/EcoIssues#23220]
User Id: Rei_Parasita
Version: 0.9.5.2 beta release-315

Steps to Reproduce:
Unknown. Spawning any of them through the command line creates a push in the player, which seems to come from the collider of the new animal, and sometimes they are visible for the first seconds. Their visibility seems to have a direct correlation with the camera Transform.

Expected behavior:
They should be visible at all times.

Actual behavior:
Both animals are invisible during the playthrough. The jellyfish only appears a few rare times for a couple of seconds. The Pacific Sardine was never seen. 

Do you have mods installed? Does the issue happen when no mods are installed?:
No

Footage of the happening:

https://user-images.githubusercontent.com/25543840/170915442-5b907466-813c-41a5-a1fc-27a679ad945f.mp4

https://user-images.githubusercontent.com/25543840/170915902-831a8621-773d-42a8-a74f-326359e8fd93.mp4

**Comment by SlayksWood** [comment]
@ReiParasita Thank you for the report. The distance of showing MoonJelly fish was slightly increased. I guess these changes will be added in 9.5.3. Moonjellyfish and PacificSardine as another small animals depends on Level of Details setting. So to increase it's distance you need to change this setting. For some reason, this information disappeared in the description of Level of Details. But it still is. We will return this information to the description.
![image](https://user-images.githubusercontent.com/45708377/170946172-31c9bbcf-4902-405c-8aca-89b00d66f7cb.png)
![image](https://user-images.githubusercontent.com/45708377/170946278-631f915f-9ce1-42b2-bcbd-238e5b437c03.png)

Internal link of fixed moonjellyfish: https://app.clickup.com/t/10591183/ECO-14875
