### ISSUE TITLE
User Problem: Kicks out of the game with an error!

### ISSUE THREAD

**Issue by xottab-slg** [StrangeLoopGames/EcoIssues#23228]
Hello. Such a problem. When you try to stake the territory, it throws you out of the game with an error, when you re-enter the game, the claim sheet disappears and the territory is not in private! I believe that this is due to my nickname in the game ( }{0ТТ@6b)4 ). There was no such problem before
![Clip2net_2022-05-31_22_15_48](https://user-images.githubusercontent.com/77971206/171267246-9353f44b-d9b4-4278-bca8-a38b22296f3e.png)
!

**Comment by D3nnis3n** [comment]
This issue is no longer relevant for Update 10 due to changed claiming mechanics.
