### ISSUE TITLE
USER ISSUE: Tutorial Stuck at Press Space to Jump

### ISSUE THREAD

**Issue by Possemaster** [StrangeLoopGames/EcoIssues#23227]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
Start new game
Press WSAD
Press SPace
STUCK

**Expected behavior:**
COntinue Tutorial

**Actual behavior:**
STuck

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hey @Possemaster ,

Thank you very much for your report. What do you exactly mean with 'stuck'? Please, could you provide more information? It would be very useful for us.

However, it is known that the tutorial jumping task was not working for some users. This issue has been fixed and will be patched really soon for users.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-21580_

**Comment by Possemaster** [comment]
Hey. I figured out after 15 minutes I could skip the step. So not stuck anymore. But still the jump step is bugged.Op 1 jun. 2022 18:11 schreef Tom Escalante ***@***.***>:
Hey @Possemaster ,
Thank you very much for your report. What do you exactly mean with 'stuck'? Please, could you provide more information? It would be very useful for us.
However, it is known that the tutorial jumping task was not working for some users. This issue has been fixed and will be patched really soon for users.
* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-21580

**Comment by D3nnis3n** [comment]
Thanks for the report, the issue was identified internally and fixed, hence I'm closing this issue.

For QA, the issue: https://app.clickup.com/t/10591183/ECO-21580
