### ISSUE TITLE
(9.5.2) Broken Store Offers

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#23232]
It is possible to end up with store offers that throw nullref exceptions in the tooltip when hovering. These entries also don't behave properly when the stack changes and on other actions.

STR:
1. Set up a store.
2. Set up a new category with a new offer.
3. Remove the offer from the category.
4. Pick up the store.
5. Place the store.
6. Add an offer into the existing (empty) category.
7. Hover the offer and see that it's throwing nullreference exception.

Me and @julianma have a fix and will make a PR

**Comment by tomesc99** [comment]
Hello @MonzUn ,

First of all, thank you very much for your report! A ticket has been created and it will be fixed soon.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-22231_

**Comment by MonzUn** [comment]
I'm waiting for my other store fixes to be merged first to avoid conflicts, then I will make the PR for this issue :)

**Comment by MonzUn** [comment]
This issue has already been fixed in an unreleased version.
