### ISSUE TITLE
Alpha.6 [d9d6f47c] Torch will disappear if to close to something

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2323]
https://loli.temel.me/WnoTzh9ACGTiRk3DUstzcD5ZkySa3ekm.gif

**Comment by keegan-o** [comment]
This is the case for all tools and the solution is not an easy fix, so will probably not be in alpha 6.1.

**Comment by MarjieAVolk** [comment]
Really?  The gif shows it not happening for other tools, only the torch.  I assumed it was a prefab change, like putting it on a different layer or something, but idk

**Comment by metachronism** [comment]
fixed
