### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by natasajacobs** [StrangeLoopGames/EcoIssues#23233]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The operation has timed out.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @natasajacobs ,

Thank you very much for your report. Please, it would be very useful if you could provide more information. In what platform are you playing the game? Also, could you share the logs? Instructions are here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Thanks in advance.

**Comment by D3nnis3n** [comment]
Hello natasajacobs
this error says that you are unable to reach our authentication servers.

Authentication is checked by the server, not the client, hence when creating a local game this issue may appear while it does not on multiplayer servers.

General suggestions are to check your antivirus software and make an exception for Eco, check any firewalls or provider restrictions and try a VPN to see if it is working when using one.

For additional assistance please contact [support@strangeloopgames.com](mailto:support@strangeloopgames.com), as this is a support issue, not a bug.
