### ISSUE TITLE
USER ISSUE: House not giving XP

### ISSUE THREAD

**Issue by DarkMerc89** [StrangeLoopGames/EcoIssues#23249]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
Build a house with a floor, walls, roof, one door and no windows. Make sure that it is in your claimed land completely and it shows you as the resident.

**Expected behavior:**
To give XP multiplier as normal

**Actual behavior:**
Shows a zero in the bottom left and in the the resident menu.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is
![Claim4](https://user-images.g
![Claim3](https://user-images.githubusercontent.com/107787568/174470490-45f8987c-c0f5-4289-9ce5-c64ef10e789a.PNG)
ithubusercontent.com/107787568/174470488-4d38582e-c32e-4ece-8266-8d9fa3410e07.PNG)
 here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![Claim2](https://user-images.githubusercontent.com/107787568/174470498-ad2356be-b57c-4487-9d0e-9ce83f7b2862.PNG)
![Claim1](https://user-images.githubusercontent.com/107787568/174470502-2897a36b-efba-4b7d-be8a-1c9edcc27915.PNG)
![Residency](https://user-images.githubusercontent.com/107787568/174470503-2db42a10-e966-40
![House Multiplier](https://user-images.githubusercontent.com/107787568/174470506-ef14415f-c3a0-4612-9bcf-74ba46811ade.PNG)
3e-9f2c-1ef26db47d04.PNG)
![House Roof](https://user-images.githubusercontent.com/107787568/174470511-0fa71224-ce4a-4030-a69a-abb8eb409c39.PNG)
![House Roof](https://user-images.githubusercontent.com/107787568/174470513-4ee0f774-3e4a-496c-97f3-7a3e811d88a7.PNG)
![House L side](https://user-images.githubusercontent.com/107787568/174470514-0a83144e-527e-42c0-b67a-e9d090b03a09.PNG)
![House Back](https://user-images.githubusercontent.com/107787568/174470515-e31c2bdd-2abf-43f5-8b83-8b94b78227db.PNG)
![House R side](https://user-images.githubusercontent.com/107787568/174470516-e78067d9-a33c-4387-bbd9-3341a92a5c69.PNG)
![House front](https://user-images.githubusercontent.com/107787568/174470518-c931e82f-0931-408e-8e46-83b836992f01.PNG)
![Residency](https://user-images.githubusercontent.com/107787568/174470555-21736c24-2a35-458f-b33d-7ce7865ff2a8.PNG)

**Comment by D3nnis3n** [comment]
Closing due to necessary information not provided.
