### ISSUE TITLE
MINOR ISSUE: Spruce seed description incorrect

### ISSUE THREAD

**Issue by FaceNommer** [StrangeLoopGames/EcoIssues#23243]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
Look at description to spruce seed

**Expected behavior:**
It should state "Plant to grow a spruce tree"	

**Actual behavior:**
Instead it says "Plant to grow a fir tree" despite firs being their own tree type.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and yes.

**Log files unnecessary, this is a item description issue.

**Comment by tomesc99** [comment]
Hello @FaceNommer ,

Thank you very much for your report! A task has been created and the issue will be fixed soon.

_* For internal usage purpose: https://app.clickup.com/t/2wv7qr1_

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this is fixed in the upcoming 9.6 update
