### ISSUE TITLE
USER ISSUE: adrian

### ISSUE THREAD

**Issue by adrianmagureanu593** [StrangeLoopGames/EcoIssues#23244]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
adrianmagureanu

**Expected behavior:**
what join- Player

**Actual behavior:**
what - Player

**Do you have mods installed? Does the issue happen when no mods are installed?:**
u_u

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the most recent version and in case your problem is still appearing, give us a more detailed description of the problem :)
