### ISSUE TITLE
9.5.2 Beta Release-315 Shops on the map showing multiple times 

### ISSUE THREAD

**Issue by KevinLinders1904** [StrangeLoopGames/EcoIssues#23242]
We have shops on the server and some of the shops are shown multiple times in the buy windows

![image](https://user-images.githubusercontent.com/2630343/172345486-d72883e5-b01d-465e-8dd0-172b2962752c.png)

This is the same shop just with different names.

**Comment by tomesc99** [comment]
Hello @KevinLinders1904 ,

Thank you very much for your report. I'm glad to let you know that the issue has been fixed and it will be patched on future versions.

_* For internal usage purpose: https://app.clickup.com/t/10591183/ECO-15041_
