### ISSUE TITLE
USER ISSUE: Water don´t flow correct

### ISSUE THREAD

**Issue by ToedlichesAuge** [StrangeLoopGames/EcoIssues#23248]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
1. dig a hole line
2. flood the hole line

**Expected behavior:**
it shold flood the hole line

**Actual behavior:**
instead it topps random

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended for now, Eco doesn't have water physics.
We'll take a look at those in a later Update to determine if and how extensively we want to implement such a system.
