### ISSUE TITLE
9.6 Staging 2320 - Claim stake size 1 is actually 2x2

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23257]
Size 1 claim stake setting is actualyl 2x2

![image](https://user-images.githubusercontent.com/61889138/175565426-928ec6bd-aaa5-42aa-af6d-d02b1a59dfe6.png)

**Comment by tomesc99** [comment]
Hey @MishkaFur ,

Thank you very much for reporting this issue! A ticket has been created and it will be solved really soon.

_* For internal usage purpose: https://app.clickup.com/t/31g2dnm_

**Comment by WeaselDog** [comment]
This has been fixed in the upcoming 9.6 release. Thank you for your reporting this bug!
