### ISSUE TITLE
USER ISSUE: Login auth failed

### ISSUE THREAD

**Issue by kiroba** [StrangeLoopGames/EcoIssues#23252]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
Launched the game through steam.
clicked continue
erroroflogin auth failed

**Expected behavior:**
launched the loading sequence to jump on to the server and play the game.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The remote server returned an error: (530) .</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Vanilla version.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hello Kiroba,
this error says that you are unable to reach our authentication servers.

Authentication is checked by the server, not the client, hence when creating a local game this issue may appear while it does not on multiplayer servers.

General suggestions are to check your antivirus software and make an exception for Eco, check any firewalls or provider restrictions and try a VPN to see if it is working when using one.

For additional assistance please contact [support@strangeloopgames.com](mailto:support@strangeloopgames.com), as this is a support issue, not a bug.
