### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by goatbuild** [StrangeLoopGames/EcoIssues#23251]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/8936224/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/8936225/Player-prev.log)

Game is playable for up to an hour, but will often stutter and freeze. Sometimes a freeze occurs after playing for a short while.

**Comment by D3nnis3n** [comment]
Hello goatbuild,
the error hints at this being a problem with the amount of VRAM your card has. With 2 GB it is on the lowest limit of our minimum requirements intended for the game on absolute minimum settings on solo servers without much stuff going on. There is not really anything we could do to solve the problem, it unfortunately would be a good point to update to a graphics card that has more VRAM, even though I know it's currently not the best time for graphic card purchases.
