### ISSUE TITLE
game's crashing when i go to load into any world.

### ISSUE THREAD

**Issue by mundanejester** [StrangeLoopGames/EcoIssues#23268]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9024547/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9024548/Player.log)

I can load up the game go through the menus and load screen look at all my settings etc. but i cannot load into a single world including a local one i've verified the files integrity through steam and uninstalled and reinstalled but im getting the same issue. when i should pop into the world the screen goes black and a pop up window comes up with the game logo with a red exclamation mark with the title of the window saying " Eco - Unity 2020.3.31f1_6b54b7616050" i'd appreciate any help with this as it's doing the same thing to all my games that run off of unity.

**Comment by mundanejester** [comment]
I don’t think it’s unity, I installed the previous driver for my graphics card and it works fine now, I have a radeon 6700 xt if that helps at all

**Comment by D3nnis3n** [comment]
Thanks for that info, unfortunately that didn't work for the other people with this Unity issue, but it's helpful information for our report at them. I'm closing this issue specifically, given you have solved your problem, which is great to hear :)
