### ISSUE TITLE
Unable to select multiple items in menu for work parties 

### ISSUE THREAD

**Issue by merlay** [StrangeLoopGames/EcoIssues#23260]
Version 9.5.3

I'm trying to select multiple items for a work party but I can only select one, despite holding down shift or ctrl when clicking on the other items. 

![image](https://user-images.githubusercontent.com/53235880/175831732-193c3fed-2af8-4f10-8d9a-4c247678c45e.png)

**Comment by TatharNuar** [comment]
I can confirm this was not present in Beta 9.5.2, and I believe it is related to my issue #23261.

**Comment by D3nnis3n** [comment]
Fixed in 9.5.4 which I just released.
