### ISSUE TITLE
USER ISSUE: Version Mismatch

### ISSUE THREAD

**Issue by tubgoatstugboats** [StrangeLoopGames/EcoIssues#23266]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
1. Update Server
2. Update Game
3. Try to log in

The Server Specifically states that the Server Version is for 9.5.3 and my Game version is 9.5.4

**Expected behavior:**
not been a version mismatch

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
```
![Screenshot (773)](https://user-images.githubusercontent.com/108421125/176484875-dd33b7e6-9661-471e-8249-f03b9fcaef78.png)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server has not updated yet, either you wait until they did that or revert back to an older version via the steam beta branch feature.
