### ISSUE TITLE
Game doesn't allow progress

### ISSUE THREAD

**Issue by Tindog33** [StrangeLoopGames/EcoIssues#23276]
I have an issue where the game in order to make an electric planer requires an electric stamping press, but I made one and as you can see, it doesn't let me progress. I used admin commands to give me more steel to remake it again, but again the same result. 

\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
I am using another players machines table and made the electric stamping press, however, it says I don't have one, I have put one on my property and even crafted another one. But nothing.

**Expected behavior:**
Should have after crafting the electric stamping press made the electric planer.

**Actual behavior:**
Does not allow me to progress I have the industry profession.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![20220710005617_1](https://user-images.githubusercontent.com/46406955/178135369-b2e78e78-2efb-4a40-9141-d48aa2c96329.jpg)

**Comment by Tindog33** [comment]
BTW I did place it in its room and had been using it, but it says I still don't have it.

**Comment by Tindog33** [comment]
So we put them in the same room and that fixed the requirements, we had had them in rooms stacked on top of each other to save space, we took some spots out of the floor and then the requirement went away as you requested (above), so it appears that being in the same room fixes the issue. The issue was they weren't in the same room.

**Comment by D3nnis3n** [comment]
Yep, that works as intended, glad you got it sorted :)
