### ISSUE TITLE
USER ISSUE: Wont load eco

### ISSUE THREAD

**Issue by b1xndie** [StrangeLoopGames/EcoIssues#23285]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
WOnt load eco.

**Expected behavior:**
To load eco

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, it was fine till the restart, 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tomesc99** [comment]
Hello @b1xndie ,

Thank you very much for your report. Have you been able to play the game or reproduce the issue again? How is it going? If you could provide more details and the logs it would be very useful.

Thanks in advance,
Tom

**Comment by D3nnis3n** [comment]
Closing due to no response.

**Comment by b1xndie** [comment]
I got it working through g portal, and file zilla. Thanks though.
