### ISSUE TITLE
USER ISSUE: Can't find the copper wiring recipe

### ISSUE THREAD

**Issue by chlobou** [StrangeLoopGames/EcoIssues#23297]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
The recipe doesn't exist in the electric machinist table like said in the wiki page

**Expected behavior:**
The electric machinist table should have the copper wiring recipe

**Actual behavior:**
It doesn't exist

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Copper Wiring has been moved to the normal Machinist Table in a recent update.
The wiki is community made, hence can be outdated when noone has updated it yet.
