### ISSUE TITLE
[9.6.0-2363][Bug] Property Editor - Brush size

### ISSUE THREAD

**Issue by DinosaurDundee** [StrangeLoopGames/EcoIssues#23307]
Default brush size is set to 1, but you cannot place a single claim if you carry more than 1 claim in your inventory.

1. have **more than 1** land claim paper in your inventory (e.g. 2)
2. click on your property name
3. the brush is larger than 1 claim
4. try to change the brush size in the bottom left corner
5. notice you cannot go down to single claim

**Comment by tomesc99** [comment]
Hello @DinosaurDundee ,

Thank you very much for your report. Fortunately, this has been fixed and will be included on the next version!

_* For internal usage purpose: ECO-22731_
