### ISSUE TITLE
Alpha.6 [d9d6f47c] Cast Iron Stove recipe has no ingredients

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2330]
![image](https://user-images.githubusercontent.com/1900106/30924567-6bf8b734-a3af-11e7-8117-7d213ee8648c.png)

And do not craft:    
![image](https://user-images.githubusercontent.com/1900106/30924602-8fbcd83a-a3af-11e7-8ade-facdb6189f1a.png)

**Comment by craig-jong** [comment]
fixed in master
