### ISSUE TITLE
Alpha.6 [d9d6f47c] Cement kiln pipe connection wrong placed

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2331]
![image](https://user-images.githubusercontent.com/1900106/30925081-fadf10c8-a3b0-11e7-92fe-12e8c1beb90a.png)

**Comment by MarjieAVolk** [comment]
Not sure what the state of pipe connections is right now - if that hasn't been started yet then this issue can probably be closed

**Comment by keegan-o** [comment]
Should be fixed (will also be updated when cement kiln art is added)
