### ISSUE TITLE
Rubble teleports to the surface frequently

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2334]
need to come up with a sleeping RB solution

possible solution:
1) when RB goes to sleep, freeze it in this state, even between network reconnections
2) when an active RB hits a frozen object, wake it back up

**Comment by Fank** [comment]
Do you mean something like "rubberbanding" of players?

**Comment by SeanAtr0n** [comment]
Seems similar to https://github.com/StrangeLoopGames/EcoIssues/issues/2004

Another option would be to group world objects by chunk and enable physics once all objects in a chunk are loaded.

**Comment by Fank** [comment]
Reproduction:
- Download savegame ftp://eco.fankserver.com/Game-2334.eco
- Start server with savegame
- Move to 954, 35 on that corner
  - ![image](https://user-images.githubusercontent.com/1900106/31032634-09d31a36-a55d-11e7-99e9-de8b4589ecb7.png)
  - ![image](https://user-images.githubusercontent.com/1900106/31032642-15ef8c5a-a55d-11e7-92be-01f49b8769c9.png)
- Set view distance to 60
  - ![image](https://user-images.githubusercontent.com/1900106/31032662-3732f618-a55d-11e7-85b6-cdd4f3cd1ef0.png)
- Shutdown server and client
- Start server
- Start client and connect to server look at south and see stone falling again and again
  - ![image](https://user-images.githubusercontent.com/1900106/31032702-64bc4fbc-a55d-11e7-83ff-2dfcc2e5ad92.png)

**Comment by johnkslg** [comment]
A lot of complaining about this on discrod, removing low priority flag.
