### ISSUE TITLE
USER ISSUE: BUG 

### ISSUE THREAD

**Issue by steph290989** [StrangeLoopGames/EcoIssues#23346]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
je suis bloquée dans un plafond et ne peut plus rien faire, les murs sont noires et impossible de jouer

**Expected behavior:**
réparer le bug pour que je puisse jouer

**Actual behavior:**
bloquer sans pouvoir bouger

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use /unstuck to unstuck yourself or just use admin commands like /tp to teleport yourself somewhere.
