### ISSUE TITLE
Server issues when hosting old world.

### ISSUE THREAD

**Issue by MitsukiAkina** [StrangeLoopGames/EcoIssues#23358]
Old Version of World: 0.9.2.4
Version of playing: 0.9.5.4

When starting Server/World following issue occures:
![image](https://user-images.githubusercontent.com/68381694/185765686-d911b928-6c8b-4e09-b4a9-7a3b444c12e6.png)

Here ist the log for the server:
[log_220820105059.log](https://github.com/StrangeLoopGames/EcoIssues/files/9388006/log_220820105059.log)

No mods installed.

**Comment by D3nnis3n** [comment]
You will need to update the world to the latest version of 9.3, then 9.4 and then 9.5 for it to work. You can find all these versions in Steam via right clicking Eco -> Properties -> Betas in the dropdown. Direct migration is not supported.
