### ISSUE TITLE
Impossible to resize display all the accounts

### ISSUE THREAD

**Issue by CedricDx** [StrangeLoopGames/EcoIssues#23364]
Hello, it is impossible to resize the bottom pane to display all the accounts

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99500332/186760910-d34c4a13-be5f-4b4e-bf53-ac06e40039da.png">

**Comment by CedricDx** [comment]
V 0.9.6

**Comment by D3nnis3n** [comment]
Fixed in 0.9.6.
