### ISSUE TITLE
[Staging 2425][Bug] Items Can't Be Picked Up If Not Interactable

### ISSUE THREAD

**Issue by TheKye** [StrangeLoopGames/EcoIssues#23366]
In Unity there is a setting on the World Object Script: Bool Interactable

If this is false the hammer can't pick up the item when placed, 

This is set to false on some of my mods that we don't think need the interaction ui because it doesn't fit, (Tables, Rugs) as we try to remove the highlight from the items for cleaner ui and play

Is this intended or a bug? as it wasn't an issue in prior versions

**Comment by TheKye** [comment]
https://user-images.githubusercontent.com/29281156/187096244-49f0b2d4-999b-4731-85cd-fd94252f0395.mp4

Video by PadmaN for example

**Comment by TheKye** [comment]
image for setting reference
![StoneTable](https://user-images.githubusercontent.com/29281156/187096271-9e22aada-93f4-4d5c-8f30-a77a61328d6b.PNG)

**Comment by D3nnis3n** [comment]
That's intended, as via DM :)
