### ISSUE TITLE
Contract UI lots of text clipping

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2336]
![image](https://user-images.githubusercontent.com/6262198/30929326-fba64582-a372-11e7-9c9c-3d46dba91874.png)
![image](https://user-images.githubusercontent.com/6262198/30929341-0c39bcda-a373-11e7-8db4-f3cadede6e30.png)
![image](https://user-images.githubusercontent.com/6262198/30929354-18531c32-a373-11e7-8a89-9b1701dd13d4.png)
![image](https://user-images.githubusercontent.com/6262198/30929381-3561b518-a373-11e7-9719-218edb366e1a.png)

**Comment by johnkslg** [comment]
Fixed these
