### ISSUE TITLE
9.6 Staging 2411 -Docker

### ISSUE THREAD

**Issue by superbjorn09** [StrangeLoopGames/EcoIssues#23360]
When i try to start the server in the docker container it keeps restarting with the following message:

`The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      **The application 'EcoServer.dll' does not exist.**
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:`

My docker-compose.yml:
![image](https://user-images.githubusercontent.com/32303582/185777559-3c14dc38-7516-41a4-9b8b-88011ba59282.png)

I got the same error for the version 9.5.4, but i had a workaround by overwriting the "command" in the docker-compose file to "/app/EcoServer". Sadly, this doesnt work anymore. Nor does the way described here: https://hub.docker.com/r/strangeloopgames/eco-game-server

Edit: Same for the image tag 0.9.6.0-beta-staging-2413

**Comment by D3nnis3n** [comment]
Fixed in Update 9.6.1.
