### ISSUE TITLE
USER ISSUE: Can't login to Eco 9.5.4-beta

### ISSUE THREAD

**Issue by p-coded** [StrangeLoopGames/EcoIssues#23369]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
Hello Eco Team,
yesterday i started a local server on my Eco 9.5.4-beta installation. I closed the game and shutted down my pc. Now, when I start Eco again (i'm starting it from downloaded/extracted zip version, not from Steam) i'm stuck in the login screen and it says "Too many failed attempts. Blocked for 2 hours." 
To test if it's working with another version, I downloaded the 9.6.0-staging version, unzipped it and startet it. With this version i'm logged in again und it's running fine. But returning to 9.5.4 it always pops the login error message.

Is there any known solution for this?

Thx and kind regards
Patrick

**Expected behavior:**
I should be logged in automatically

**Actual behavior:**
The following error message popped up:
```
Too many failed attempts. Blocked for 2 hours.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Happens with and without installed mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Wrong tracker and fixed in the meanwhile :)
