### ISSUE TITLE
USER ISSUE: Player Character moving animation freeze

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#23378]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
1. Go and pick up the cart
2. Change your look to 3rd Person view
3. Exit from the cart and your character freeze in T-shape

**Expected behavior:**
It should move like before I took the cart

**Actual behavior:**
The character freezes in T-shape

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I didn't have any mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ActuallyHappy** [comment]
This happens without the cart in some instances too

**Comment by tomesc99** [comment]
Hey there @Zozoom !
Thanks for bringing this to our attention! 
We have recently confirmed this bug and passed your case along to our developers so they can continue to investigate this issue. When we have more updates on this bug we'll be sure to keep you updated.
Here is the report ID for reference: ECO-23994

Thank you!

**Comment by Zozoom** [comment]
.
