### ISSUE TITLE
USER ISSUE: Waterwheels broken in last update

### ISSUE THREAD

**Issue by ActuallyHappy** [StrangeLoopGames/EcoIssues#23377]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
Waterwheels do not work in places they did work before the most recent update.

**Expected behavior:**
They produced power before the most recent update, which I was expecting them to still do

**Actual behavior:**
Instead they just don't, and say there's not any water flow around the waterwheel even though the wheel is in a flowing river

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_220831075016.log](https://github.com/StrangeLoopGames/EcoIssues/files/9464939/log_220831075016.log)

**Comment by TwixterZ** [comment]
Hi, @ActuallyHappy 
Thank you for reporting this issue, I have tested this on my end and confirmed its an issue with migration, I have passed this information to our developer for possible fix.

Report reference : ECO-24034

**Comment by D3nnis3n** [comment]
This has been fixed.
