### ISSUE TITLE
USER ISSUE: After using the Cart, it is not possible anymore to use tools

### ISSUE THREAD

**Issue by user-na** [StrangeLoopGames/EcoIssues#23376]
\
**User Id: (slg143335)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
Using the Cart.

**Expected behavior:**
After cart usage is done, it is possible again to use tools.

**Actual behavior:**
Hands are still in the cart using orientation. Collecting stuff and interacting with storages is still possible. Usage of tools however ist not possible. Restart needed to fix it. I don't know if it is related, but the game crashes on exit (It did not do it with the previous 9.5)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
currently not.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.6.1.
