### ISSUE TITLE
Eco crashing PC into starting

### ISSUE THREAD

**Issue by Nostr0** [StrangeLoopGames/EcoIssues#23371]
From what I've seen the game looks very promising but I can't play it properly because it restarts my pc which no other game does to my PC. Sometimes I can make a new world and play for a few minutes and sometimes it crashes 3 seconds into launching the game. I specifically did stress tests for hours for the GPU and CPU and tested the RAM. I even send my PC to a PC repair company and they tested it thoroughly but they couldn't find anything that was wrong with it. Windows 10 is freshly installed with nothing on it but Eco and it still has the same behaviour. When I told them to try to start Eco they had the same results, crashing the pc within a few seconds or minutes. I have no idea what causes this but it seems to be a software issue as far as I can tell. If the system requirements aren't out of date then I don't know.

Specs:
Motherboard: MSI B450 TOMAHAWK MAX
CPU: AMD Ryzen 5 2600
GPU: NVIDIA GeForce GTX 1660 SUPER
RAM: 16 GB

The temperature doesn't really go over 75°C if it runs for more than a few minutes.
The stress tests I've done made it go up to 77°C (100% CPU,CPU,RAM and the SSD) for 2 hours

Logs:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9448385/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9448386/Player.log)

If you need more information just tell me what to give you because I am really hyped to play it but it just doesn't seem to be working sadly.

**Comment by D3nnis3n** [comment]
Very often when this happens the PSU is too weak. Unfortunately, in no case it is a bug in the game, so you'd be better off to write to support@strangeloopgames.com. Keep in mind that they cannot do a lot either with such issues, as they're pretty much always hardware related.

**Comment by Nostr0** [comment]
I just bought a new PSU but it's not here yet. Hopefully this will actually be the solution
