### ISSUE TITLE
USER ISSUE: Cannot log into server

### ISSUE THREAD

**Issue by LoneReaper76** [StrangeLoopGames/EcoIssues#23381]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
1. Attempt to log on to server
2. Got connection failed message

**Expected behavior:**
I was just in the server and now can't get back into it

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, providing your client and server logs as described here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world
