### ISSUE TITLE
Skid Steer can not dump in LLS

### ISSUE THREAD

**Issue by Dan-Gecko** [StrangeLoopGames/EcoIssues#23386]
Version: 0.9.6.0 beta release-334
problem: The skid steer can not dump it's content into a large lumber stockpile (lls) any more (possible in prior versions).
expected behavior: before, the skid's blade could be brought over the walkways on the side of a llls, which would highlight the lls green as a suitable place for the skid to offload it's content via the integrated r-klick. 
solution: ad the ability back so the skid steer is able to mark the walkways of a lls as a valid dumping area for the lls.

_personal opinion:_ It gets harder and harder to do things in this game efficiently. everything costs time and with every change tasks get more time intensive (for example the change to the pick, because 2% of players would do some sort of a speed trick, 98% of all players are inconvenienced from the consequences. This is NOT an MMO, where you want to keep players in the game to make more money off of their monthly subscription. I already paid for the game! twice actually, since I gave a copy to my friend. Please SLG, can you for a change add/revert some things to make the game more fun for the player (and yes, 'fun' in this instance is the opposite of 'time intensive' and 'tedious')?

**Comment by D3nnis3n** [comment]
That's not intended. Merging with https://github.com/StrangeLoopGames/EcoIssues/issues/23395 to deal with it there.
