### ISSUE TITLE
USER ISSUE: Shadow is not in sync with the tools

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#23390]
\
**User Id: (slg205663)**
**Version:** 0.9.6.0 beta release-334

**Steps to Reproduce:**
1. Grab hammer
2. Do the action of hit something while you can see your shadow.

**Expected behavior:**
Shadow should match the character	

**Actual behavior:**
There is TWO hammers in the shadow. One in the and o the character and one floating around. While swinging the hammer you can see the two shadows.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://user-images.githubusercontent.com/67368828/188171322-1564aa64-a03c-4e48-86d6-0231e919918f.png)
![image](https://user-images.githubusercontent.com/67368828/188171354-c7995d73-f025-4857-b6ef-7c7c4d19b3be.png)

**Comment by TwixterZ** [comment]
Hello @Crazy-Spy , thank you for reaching out, we are happy to inform that this issue is fixed for the upcoming patch, look forward to it! =)
