### ISSUE TITLE
USER ISSUE: Treasury SetDefaultCurrency and OpenAllocateTaxUI permission error

### ISSUE THREAD

**Issue by muzs1** [StrangeLoopGames/EcoIssues#23397]
\
**User Id: (slg161915)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
1.	Open Treasury with Elected Title assigned.
2.	Click Manage next at a currency. (Nothing happens, server logs show permissions error)
3.	Change the default currency. (UI updates and shows the change but server logs show error and the currency is not really changed)

Tested in 9.6 and 9.6.1 from a new world both have the same issue.

Went back to 9.5 did the same setup in another new world, works fine then updated the save to 9.6.1 and it was broken again.

**Expected behavior:**
Ui Should open in game

**Actual behavior:**

Nothing happens in game server log shows a permission error.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, I first spotted the with mods but I have created a fresh server with no mods and still had the same issue. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9482394/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9482395/Player-prev.log)

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6.2 update which will be released soon. We appreciated your contribution.
