### ISSUE TITLE
USER ISSUE: Cant log into server

### ISSUE THREAD

**Issue by tanaej84** [StrangeLoopGames/EcoIssues#23394]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You just need to wait until the server has updated to your version :)
