### ISSUE TITLE
USER ISSUE: Skid steer and crane bug

### ISSUE THREAD

**Issue by nighthawk968** [StrangeLoopGames/EcoIssues#23395]
\
**User Id: (slg134150)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
For the skid steer fill the inventory as normal and unload into stockpile or truck

For the crane use as normal on stockpile or truck

**Expected behavior:**
For the skid steer items in inventory transferred to stockpile or truck

For the crane remove items from stockpile or truck

**Actual behavior:**
For the skid steer will fill inventory from truck and stockpile but will not empty inventory into truck or stockpile

For the crane nothing happens at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/9481654/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9481655/Player-prev.log)

[my server log_220902095345.log](https://github.com/StrangeLoopGames/EcoIssues/files/9481663/my.server.log_220902095345.log)

**Comment by ViewableGravy** [comment]
I've also had this issue (With Crane). It shows as "must attach to ground" despite being on mortared stone without issue. Moving over any inventory won't pick up the items or allow any sort of interaction with the world either (other than just moving around)

**Comment by D3nnis3n** [comment]
Fixed in 9.6.3.
