### ISSUE TITLE
USER ISSUE: Skid Steer continues to reverse

### ISSUE THREAD

**Issue by CaptainGlad** [StrangeLoopGames/EcoIssues#23402]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
1. Get into Skid Stter
2. Push - not hold - "S" to start reverse
3. Skid Steer will continue reverse without hold "S"
4. Hold "W" to brake and go forward

**Expected behavior:**
Skid Steer should back up while holding "S" not tapping

**Actual behavior:**
Skid Steer will reverse until it runs out of fuel

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, game is great without mods :)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hello @CaptainGlad thank you for reporting this to us, I can confirm this is happening and have informed our developer for a possible fix. 

Issue reference : ECO-24144

**Comment by Daniel-Magulado** [comment]
Hi @CaptainGlad 

Thank you for submitting this bug report.
This issue has now been fixed in the latest version of Eco. I'll be closing this but please feel free to let us know if you encounter any issues about Skid Steer or the game.

Issue reference : ECO-24144
