### ISSUE TITLE
Crashing server (connection) while trying to continue game

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [StrangeLoopGames/EcoIssues#23409]
Github interfacing disabled at main menu level.

Version: 0.9.6.1 beta release-337

**Steps to reproduce**
1. Start the game from Steam.
2. Wait for the main menu.
3. In case you have last game, continue that game.
4. The server connection will crash

**Expected behavior**
The last played game will load normally so I can continue the game at the point I ended the last time.

**Actual behavior**
On requesting to load the last game with the continue button the server crashed. The game was stored normally and exited normally.

**Mods and game behavior without mods installed**
No mods installed and vanilla game play.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9484908/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9484910/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9484911/Player-prev.log)
[log_220904043503.log](https://github.com/StrangeLoopGames/EcoIssues/files/9484913/log_220904043503.log)

**Comment by D3nnis3n** [comment]
The savegame that was loaded here seems to have an issue, which is also a case for support@strangeloopgames.com. Please attach the affected savegame in your e-mail.
