### ISSUE TITLE
Contract board sub-windows don't close with distance

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2340]
Other windows do
![image](https://user-images.githubusercontent.com/6262198/30929911-e0050938-a374-11e7-94af-230fd87c6e07.png)

**Comment by metachronism** [comment]
all of these UIs need to be encapsulated within the world object ui and not have their own windows

**Comment by MarjieAVolk** [comment]
Yeah there are others that have this problem too, like search and select.  Might even be a bug for that, can't find one though

**Comment by johnkslg** [comment]
Requires some bigger changes to UI, punting for now

**Comment by MarjieAVolk** [comment]
This is less important now that all windows will close when you hide your cursor anyway

**Comment by johnkslg** [comment]
Punting to a post beta UI pass.

**Comment by SlayksWood** [comment]
I assume this issue is no longer occurring, we don't have this window in 0.9.0. Closed for now.
