### ISSUE TITLE
Eating while driving a wood cart causes weird behaviour

### ISSUE THREAD

**Issue by iuriguilherme** [StrangeLoopGames/EcoIssues#23403]
While driving a wood cart, the backpack is still present in the screen.

When clicking a food item in the backpack, the eating animation will be played, and then the last selected tool will be displayed in the screen, while the wood cart can still be driven.

When exiting the wood cart drive mode, in first person the legs animation is freezed and in third person the character is stuck into "t mode".

Eating again while not driving seems to reset the freeze.

**Comment by D3nnis3n** [comment]
Fixed in Update 9.6.1.

**Comment by iuriguilherme** [comment]
T pose has been fixed but tool appearing after eating still happening at 9.6.1
