### ISSUE TITLE
Eco randomly crashes to desktop (corrupting a file)

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#23417]
Version: 0.9.6.1

# Description
In this version Eco has crashed 4 times now (I have not heard of other players having such a random crash to the desktop). The game crashes completely (not throwing me in the main menu, then shows a black screen when restarting and does not continue from there:

![image](https://user-images.githubusercontent.com/8270201/188506670-55ed603d-e0fd-46bb-ad15-74f9f6ebce08.png)

Solution: Stop Eco and let steam check the files for any problems (it finds one file and downloads it again), after that Eco starts normally again (sometimes I must restart the PC to get steam to write the file again, so it might be that some process still accesses the file after Eco crashed (or steam has a bug there, I don't know)

Nickname: Zokora

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9491850/Player.log)
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/9491897/DxDiag.txt)

**Comment by D3nnis3n** [comment]
Do you use any antivirus software? It's possible that the SoundEngine file is getting deleted by it.

**Comment by HellionZA** [comment]
I have the same issue, already posted a issue here

**Comment by DragonDev1906** [comment]
> Do you use any antivirus software? It's possible that the SoundEngine file is getting deleted by it.

Good point, It did actually put that file into quarantine, but when I explicitly tell it to scan the file it doesn't complain, nor does any other one on VirusTotal.

**Comment by D3nnis3n** [comment]
> I have the same issue, already posted a issue here
You do have a different problem in your logfiles.

> > Do you use any antivirus software? It's possible that the SoundEngine file is getting deleted by it.
> 
> Good point, It did actually put that file into quarantine, but when I explicitly tell it to scan the file it doesn't complain, nor does any other one on VirusTotal.
WWise is a third-party sound engine used by Eco, which is used in many games. It is unfortunately not uncommon that after each new Update security softwares tend to block parts of Eco, which is not avoidable without paying a few lump sums to all the different security software creators to get on their whitelists. The issue typically goes away by itself after their AI analysis will notice there is no actual problem after a few weeks, hence there is little we could do about it.
