### ISSUE TITLE
Persistent server connection error

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [StrangeLoopGames/EcoIssues#23413]
Reporting tool of the game disabled or disfunctional in the main menu of the game.

**Steps to reproduce**
Unknown to me how to reproduce this error.

**Expected behavior**
Server connection establishes flawless and transparently in the background. When in error it comes with suggestions to handle the situation on the side of the player. 

**Actual behavior**
The message displayed contains just the message to that the server connection is failing and points at the server log.

**Do you have mods installed? Does this issue happen when no mods are installed?**
No mods installed. Vanilla game play.
[log_220905105312.log](https://github.com/StrangeLoopGames/EcoIssues/files/9488420/log_220905105312.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9488423/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9488424/Player-prev.log)

**Comment by D3nnis3n** [comment]
There is a connectivity issue in your logs both for Discord and Unity, which hints at a security software or other local network problem being the cause. That makes this not a bug, but rather a support issue. Our support can try to help you with getting the local network corrected over at support@strangeloopgames.com. Just note that they only have limited options when a local issue is the problem.
