### ISSUE TITLE
All district maps empty after updating from 9.5.4 to 9.6.1

### ISSUE THREAD

**Issue by Maistho** [StrangeLoopGames/EcoIssues#23420]
After migrating from 9.5.4 to 9.6.1 all of our district maps are now empty.

Attaching the migration log

[2022-09-07.log](https://github.com/StrangeLoopGames/EcoIssues/files/9505727/2022-09-07.log)

Near the bottom:
```
! class[Eco.Gameplay.Civics.Districts.DistrictMap] migration:
  ! changed Districts: enumerable[class[Eco.Gameplay.LegislationSystem.District]] -> dictionary[int,class[Eco.Gameplay.LegislationSystem.District]]. No migration available!
```

**Comment by Daniel-Magulado** [comment]
Hi @Maistho 

Thank you for submitting this bug report.
I've created an internal report for this issue.
You may use the ID ECO-24235 if you wish to make a follow-up or request an update for this issue.

**Comment by Daniel-Magulado** [comment]
Hi @Maistho 

This is now fixed and will be patched in the upcoming game updates. Closing this report.
