### ISSUE TITLE
All laws broken after migrating from 9.5.4 to 9.6.1

### ISSUE THREAD

**Issue by Maistho** [StrangeLoopGames/EcoIssues#23421]
All of the "cogwheel" targets are emptied after migration from 9.5.4 to 9.6.1

This is what the law looks like:
![image](https://user-images.githubusercontent.com/2260305/188868315-1a79dcd8-7fe3-4f41-884f-9796fcb41f40.png)

This is what the if-cases should look like (after a manually editing the law, I forgot to fix the change owner statement)
![image](https://user-images.githubusercontent.com/2260305/188868345-eb2e3ed1-feaa-4044-985e-96efcecb325d.png)

Attaching the migration logs
[2022-09-07.log](https://github.com/StrangeLoopGames/EcoIssues/files/9505768/2022-09-07.log)

**Comment by Daniel-Magulado** [comment]
Hi @Maistho 

Thank you for submitting this bug report.
Could you provide us with your save file before migrating to 9.6.1? 
This will help us investigate this issue further.
Looking forward to your response.

**Comment by Maistho** [comment]
Hey @Daniel-Magulado

Is there a way I can send you the save file without sharing it publicly? Don't want to share it with everyone since we didn't find the Ecko Statue yet 😅

**Comment by Daniel-Magulado** [comment]
@Maistho 

Sure, you can either email me the save file at daniel@strangeloopgames.com or send me a drive link where I can download the savefile on discord. Nielzx#6566

**Comment by Daniel-Magulado** [comment]
Hi @Maistho 

Thank you for providing the savefile.
I've created an internal report for this issue.
If you wish to follow up about the issue or ask for an update, you may do so by using this
reference ID report number ECO-21573.

**Comment by Daniel-Magulado** [comment]
Hi @Maistho 

Happy to let you know that this is now fixed. The fix will come in the next game update. Please look forward to it.
