### ISSUE TITLE
Tool not equiped after restart/relog

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#23439]
After restarting/relogging you cannot immediately use the tool you had selected before and instead have to switch to a different slot on the hotbar and back.

### Steps to reproduce
- Join a server
- Hold a pickaxe (optionally mine a block to see it works)
- Quit the server (e.g. to main menu)
- Join the same server again
- Try to use the pickaxe without switching to another tool first.

### Expected Behavior
You should be able to use the tool normally

### Actual Behavior
You cannot use the tool, it is as if you have an empty slot selected.

**Comment by tomesc99** [comment]
Hey there @DragonDev1906  !
Thanks for bringing this to our attention!
We have recently confirmed this bug and passed your case along to our developers so they can continue to investigate this issue. When we have more updates on this bug we'll be sure to keep you updated.
Here is the report ID for reference: ECO-24287

Thank you!

**Comment by TwixterZ** [comment]
Hey there @DragonDev1906, This behavior was changed on 9.6.2, where quickslot no longer selected on login, hence this bug will no longer happens,
