### ISSUE TITLE
ecoicon tag with transparent background broken

### ISSUE THREAD

**Issue by mstrwiz** [StrangeLoopGames/EcoIssues#23447]
Version: 0.9.6.1 beta release-337

It used to be the case that if you use a lower-case item name, you'd get the same icon with a transparent background. With a camel-case name, you'd get a gradient background. However, the lower-case version is broken now, rendering part of some unrelated icon.

Lower-case:
![382310_20220912155028_1](https://user-images.githubusercontent.com/2541009/189772891-b0b13401-88ea-478c-95dc-30709da9619d.jpg)
![382310_20220912155021_1](https://user-images.githubusercontent.com/2541009/189772903-7908dcba-577b-460d-a4a5-36ba43520b41.jpg)

Camel-case:
![382310_20220912155041_1](https://user-images.githubusercontent.com/2541009/189772954-27c839ec-3dc7-4ac5-b85e-7349108335c9.jpg)
![382310_20220912155046_1](https://user-images.githubusercontent.com/2541009/189772978-10f4bd1b-1d20-4cdc-9375-2787744122f4.jpg)

**Comment by mstrwiz** [comment]
This applies at least to: wood carts, any of the buildable signs

**Comment by tomesc99** [comment]
Hey there @mstrwiz !
Thanks for bringing this to our attention! 
We have recently confirmed this bug and passed your case along to our developers so they can continue to investigate this issue. When we have more updates on this bug we'll be sure to keep you updated.
Here is the report ID for reference: ECO-24285

Thank you!

**Comment by TwixterZ** [comment]
Hi @mstrwiz happy to inform a fix for this behavior will be released in future patch
