### ISSUE TITLE
USER ISSUE: Treasury section for accounts not accessible after updating from 9.5.4 to 9.6.1

### ISSUE THREAD

**Issue by schiroky** [StrangeLoopGames/EcoIssues#23442]
I cannot manage any account anymore on the treasury table, for instance send money to a particular user, because clicking on the corresponding button (manage) does nothing.
![Steuertresor](https://user-images.githubusercontent.com/45030137/189652301-8dbe6344-c1be-4eeb-99a7-4aa80b787900.png)

**Comment by Daniel-Magulado** [comment]
Hi @schiroky 

Thank you for submitting this bug report.
Could you provide us with your 0.9.5.4 save file for us to investigate this issue further?
We are unable to reproduce this on our end.
Looking forward to your response.

For privacy concerns, you may send me your save file at daniel@strangeloopgames.com or via discord Nielzx#6566

**Comment by D3nnis3n** [comment]
This issue is fixed in Update 9.6.2.

**Comment by schiroky** [comment]
Hallo Dennis,

Danke für die Hilfe/Info. Wann wird denn Update 9.6.2 veröffentlicht werden?
Und sind darin dann ggf. auch noch diese Probleme gelöst?:

https://github.com/StrangeLoopGames/EcoIssues/issues/23420

https://github.com/StrangeLoopGames/EcoIssues/issues/23421

Und denn die beide oben nicht enthalten sind, wann wird es dazu Fixes geben?
Mein Projekt steht damit auf der Kippe, da ohne diese Funktion es gar nicht umgesetzt werden kann. Parallel arbeite ich zwar mit Hochdruck an einer alternativen Welt/Aufgabe, aber das wird knapp.

Viele Grüße

Claus Schiroky
Ährenweg 6 | 85375 Neufahrn | Tel.: +49 8165 4094272| Mobil: +49 175 9883461

[Web]<https://www.schiroky.com/>[Signal]<https://www.signal.org/de> [Teams] ***@***.***>  [Discord] <https://discordapp.com/users/500365437922443268>  [Skype] <https://www.schiroky.com/schiroky>  [XBOX] <https://account.xbox.com/social?xr=schiroky>  [Facebook] <https://www.facebook.com/claus.schiroky>  [Twitter] <https://twitter.com/clausschiroky>  [Instagram] <https://instagram.com/claus_schiroky/>  [Stayfriends] <https://www.stayfriends.de/Personen/Nuernberg/Claus-Schiroky-P-6MJGE-P>  [Github] <https://github.com/schiroky>  [Xing] <https://www.xing.com/profile/Claus_Schiroky>  [LinkedIn] <https://www.linkedin.com/pub/dir/%20/Schiroky>





Von: Dennis Scholz ***@***.***>
Gesendet: Mittwoch, 14. September 2022 10:34
An: StrangeLoopGames/EcoIssues ***@***.***>
Cc: Claus Schiroky ***@***.***>; Mention ***@***.***>
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Treasury section for accounts not accessible after updating from 9.5.4 to 9.6.1 (Issue #23442)


This issue is fixed in Update 9.6.2.

**Comment by D3nnis3n** [comment]
Hallo Klaus,
Update 9.6.2 sollte heute oder spätestens diese Woche erscheinen, wenn alles funktioniert.

Die beiden anderen von dir erwähnten Fehler werden noch untersucht, es hat noch keine Arbeit an deren Behebung begonnen, daher kann ich dir da leider nicht wirklich sagen, wann diese behoben werden. Ihrer Natur nach kann ich dir leider nicht mal sagen, ob es möglich ist, diese rückwirkend zu beheben.
