### ISSUE TITLE
[9.6.2] Getting teleported while building

### ISSUE THREAD

**Issue by KouramaProject** [StrangeLoopGames/EcoIssues#23455]
Since the last update, we get teleported a few block when building or destroying block with the hammer.
It seems to happen more often when you are close to a block. The angle you destroy or place a block have some impact too.

https://user-images.githubusercontent.com/10963029/190474094-c3837b8b-98e9-4971-908c-da9d6eacdb7d.mp4

**Comment by Daniel-Magulado** [comment]
Hi @KouramaProject 

Thank you for submitting this bug report. We are currently aware of this issue and a fix is set to roll out in the coming game updates. For reference, you can use ID ECO-24229 if you ever wish to follow up or request an update on this issue.

**Comment by GFA-SkyRanger** [comment]
Yeah its nearly unplayable now. Its on digging and building.
If u go to ur mine, its possible to be teleported into the stone and then fell throught the map.
and while building itspossible to be teleported away from the platform where its be build to build so u fall down.

**Comment by DigitalNikki** [comment]
It's unplayable for me. I get teleported when eating, building, digging, mining, or most things. I get teleported through walls, off buildings, under the map. Getting stuck wasn't a major issue because of /unstuck and just not standing under what is being mined/dug, but this is game breaking as it makes most things virtually not possible to really do.

**Comment by ZachBora** [comment]
Getting the same issues. Even had another player tell me that HE was getting teleported to ME when I was mining next to him.

**Comment by mstrwiz** [comment]
I'd ask that this fix not wait for a normal release cycle. It's game breaking as far as we're concerned. It is extremely disorienting, especially for miners and it happens more often than not when breaking blocks or interacting with inventories.

**Comment by D3nnis3n** [comment]
The fix will be released once it is ready, no worries :)

**Comment by D3nnis3n** [comment]
Fixed in 9.6.3.
