### ISSUE TITLE
[Eco Version 9.6.2] Opened Map to Alter my property claim and when I closed it my entire game was black.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23459]
![20220916013448_1](https://user-images.githubusercontent.com/1329717/190573257-e41cf7d1-a93f-47e4-b080-2c514a3e6f78.jpg)
![20220916013453_1](https://user-images.githubusercontent.com/1329717/190573266-6b3e07aa-6556-4e3b-b77b-374b68a336d9.jpg)
![20220916013513_1](https://user-images.githubusercontent.com/1329717/190573276-6d97190d-7ccf-490b-bd17-484d0a65dee4.jpg)

So..... I don't really know what caused this here to be quite honest. I had just collected land claim papers from my spouses tent that she wanted me to use to ensure that we would have the property that we wanted on the server we are playing on and I was standing in front of my tent and edited the claim using the method that utilizes the world map and when I closed and submitted the change my screen was completely black but I could still interact with my tent, my small stockpile, and my workbench. I could also walk around to an extent but could not see terrain or anything to navigate where I was.

**Comment by RemonRamy** [comment]
Hello,

Thank you for taking the time to report the exact steps that lead to it! If you're still encountering this problem, would it also be possible to share your Eco logs files by following the steps provided here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Internal reference: ECO-24374

**Comment by RemonRamy** [comment]
Hello again,

Can you try disabling Steam Overlay before running the game?

Let us know if it works.

Cheers,

**Comment by RemonRamy** [comment]
Hello again,

This issue has been resolved for everyone encountering it. If you're still having the problem, feel free to open another ticket or contact me directly through our official Discord server.

 Internal reference: ECO-24374.

Closing as fixed.
