### ISSUE TITLE
Game Crashed repeatedly - Even after Patch today - Nope

### ISSUE THREAD

**Issue by PreshusRoze** [StrangeLoopGames/EcoIssues#23453]
Monday, Sept 12th after 7:30pm.
I was in a jungle section south of our build and gathering taro and mushrooms on Core Eco - Season 14 hosted server.
The game kicked me - nothing too unusual but nothing that usually happens frequently. I was gathering taro and the occasional mushrooms and kept going along. A few minutes later - kicked 2nd time. A few minutes after getting back in - kicked again (3). Figured I needed to get back to the house relog, verify files and try again. Never made it back to house. Was kicked a 4th time. Got back in and barely saw the scenery and load in and was kicked again. I've not been able to get back in since.
I've been able to log onto [SLG] Sea Otter Official Server & create my own & get into those w/o issue. I've not been into a jungle area or tried to harvest taro or mushrooms yet - but I CAN get INTO them. Which is more than I can do on Core Eco at this point.
I verified Steam files for the game - 4k+ files are fine. Still couldn't* get in.
Uninstalled the game, deleted the steam folder for Eco - powered computer off then back on (not a restart) installed the game, verified files. Everything good.
Still can't get into Core Eco but I can get into the Sea Otter and private game.
Have since uninstalled the game 1 other time, reverified files and still: nope.

I tried once more this evening and the attached logs are after that failed attempt into Core Eco map.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9570709/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9570710/Player-prev.log)

**Comment by PreshusRoze** [comment]
*Eastern US time zone for error/issue start

**Comment by PreshusRoze** [comment]
Even after the patch today about the crashes - I still can NOT enter Core Eco map.

**Comment by PreshusRoze** [comment]
Uninstalled the game again. Found & deleted all folders left behind.. and the mod folder.
Installed the game & tried to get into Core Eco. Still can't get out of the main menu screen.

Latest log.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9579666/Player.log)

**Comment by PreshusRoze** [comment]
Tried getting into Core Eco but was immediately bounced back to the menu screen after it said I was entering the world. It did NOT list the server under "Continue" on the menu screen.
Tried accessing [the Official server SLG] Sea Otter. Got a black screen and I waited about 5 minutes when it started to load in the server then it promptly kicked me back to the menu screen.  It DID list the server under the "Continue" on the menu screen.
Log after trying to get into Sea Otter ... 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9590777/Player.log)

**Comment by RemonRamy** [comment]
Hello!

I've reached privately to request more information. Please only share the information I've requested from you privately, and do not post them to this thread. We should be able to get this sorted out for you very soon.

Cheers!

**Comment by RemonRamy** [comment]
Hello,

This should be resolved now, waiting on your feedback!

**Comment by RemonRamy** [comment]
Hey again!

Thank you for getting in touch again privately, glad we could help.

Closing as resolved.
