### ISSUE TITLE
Game Crashed and It won't let me play the game anymore

### ISSUE THREAD

**Issue by TheDrDenson** [StrangeLoopGames/EcoIssues#23451]
\
**User Id: (slg222513)**
**Version:** 0.9.6.1 beta release-337

**Steps to Reproduce:**
I was digging up taro. It crashed on me 4x this day on a server, just me, and just when I was digging up taro and gathering it. Somehow when it happened the 4th time I it crashed and now it won't let me join any server or my own world. Just shows me a black screen and I hear the sound of animals but can't do anything. 

**Expected behavior:**
The game won't work or play at all

**Actual behavior:**
Everytime I join a server or my own world there is just a black screen (only the escape menu works)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have mods and yes it happens when I have no mods installed 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9560757/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9560758/Player-prev.log)

**Comment by TheDrDenson** [comment]
Oh! And this may help! I was trying to clean my appdata of the game to see if that would fix it, but I didn't delete it yet so I have the old Player log from before cleaning it when the error actually happened
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9560781/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9560782/Player-prev.log)

**Comment by idahoHATES** [comment]
Same for us. People start crashing everywhere and we are not able to join the server again, always crashing in "entering world".
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9569053/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9569054/Player-prev.log)

**Comment by RemonRamy** [comment]
Thank you for your reports! I am taking a look at this at the moment, for the time being I'm also getting in touch to request more information.

Internal reference: ECO-24315

**Comment by RemonRamy** [comment]
Hello again,

I've followed up with you regarding a fix for the problem. Do give it a try and let me know if your players are now able to join the server normally.

Will wait on your feedback!

Cheers!

**Comment by RemonRamy** [comment]
Looks like all is well now, glad you're all back to the game.

Enjoy!
