### ISSUE TITLE
[0.9.6.1] Client crashes due to html added to signs

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#23452]
A line of html was added to a sign on our server:

`<img src = " https://cdn.britannica.com/60/8160-050-08CCEABC/German-shepherd.jpg" height = " 50" width = "50">`

This caused any client that was loading the chunk containing the sign to crash.

**Comment by Daniel-Magulado** [comment]
Hi @ChickenHacker1 

Thank you for submitting this bug report. We are already aware of this issue and fortunately, a fix is already set
to roll out in the coming game updates. Please look forward to it.
You may use this ID ECO-24126 as a reference if you ever encounter this bug again after game patches.
I'll go ahead and close this issue.
