### ISSUE TITLE
USER ISSUE: Black Screen

### ISSUE THREAD

**Issue by TheTrueLM** [StrangeLoopGames/EcoIssues#23468]
\
**User Id: (slg222456)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
1) Develop a broken game
2) Skip over unfinished game content to work on content no one asked for.
3) Break game with broken, untested updates
4) Release more content no one asked for and assure they too are untested.
5) Take a well deserved break while the community suffers.

**Expected behavior:**
A well thought out game that works perfectly with a community that loves and adores you.

**Actual behavior:**
A game that has caused people to literally chuck their computer off a bridge into on coming freeway traffic, then hucking themselves off that same bridge into the same oncoming traffic.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, cause mods make Eco worth playing with little suicidal thoughts and yes cause I had to do actual troubleshooting to try and fix your game without any support. Also your support on your discord sucks and you shouldn't waste peoples time with having one up.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
I understand your personal frustration, but your report is obviously little helpful to help you solve your problem.

There is a few black screen issues tracked in other issues here:
https://github.com/StrangeLoopGames/EcoIssues/issues/23385
https://github.com/StrangeLoopGames/EcoIssues/issues/23459
https://github.com/StrangeLoopGames/EcoIssues/issues/23453

Our developers are already working on identifying the issue and have for that reason manually fixed some occurances of this as well. Feel free to reach out to @RemonRamy on Discord (or me). Closing this issue though, as it's not valuable for the purpose of fixing an issue.
