### ISSUE TITLE
USER ISSUE: Player Displacement

### ISSUE THREAD

**Issue by 117ksk** [StrangeLoopGames/EcoIssues#23462]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
Break/Place a block within 3 blocks from player (especially while underground)

**Expected behavior:**
Player's location should not change when placing/destroying block.

**Actual behavior:**
Player's location gets instantly displaced (player teleports) to new location within 2 blocks. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Fresh install.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9591074/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9591075/Player-prev.log)

**Comment by Micro753** [comment]
I've been getting this bug as well. This needs to be a priority bug. It makes mining and building very annoying.

**Comment by Daniel-Magulado** [comment]
Hi @117ksk 

Thank you for submitting this bug report. We are currently aware of this issue where actions and constructions done teleports the player. I'll be merging this report with an already existing one.

https://github.com/StrangeLoopGames/EcoIssues/issues/23455
