### ISSUE TITLE
USER ISSUE: Teleporting

### ISSUE THREAD

**Issue by maddgik** [StrangeLoopGames/EcoIssues#23463]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
Surround yourself with chunks of rock so there is no space to move an any direction but up and then mine the rocks above you while jumping to be teleported outside the map and teleport to the surface.

**Expected behavior:**
The rocks should have moved out of the way when jumping.

**Actual behavior:**
It clips you through the ground and you are teleported to the surface and when mining from then on you can be teleported randomly.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have any mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @maddgik 

Thank you for submitting this bug report. We are currently aware of this issue where actions and constructions done teleports the player. I'll be merging this report with an already existing one.

https://github.com/StrangeLoopGames/EcoIssues/issues/23455
