### ISSUE TITLE
USER ISSUE: ISSUE WITH TELEPORTING ME WHEN BREAKING/ PLACING BLOCKS

### ISSUE THREAD

**Issue by zerofelero** [StrangeLoopGames/EcoIssues#23469]
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
build or break anything

**Expected behavior:**
not push me

**Actual behavior:**

push/ teleport me involuntary

**Do you have mods installed? Does the issue happen when no mods are installed?:** 
NOPE

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9602343/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9602346/Player-prev.log)

**Comment by zerofelero** [comment]
Sorry. Appears as though this is a duplicate ticket same issues as #23455

**Comment by D3nnis3n** [comment]
It indeed is, fix is scheduled for 9.6.3.
