### ISSUE TITLE
USER ISSUE: Kicked for "cheating"

### ISSUE THREAD

**Issue by Sladyn** [StrangeLoopGames/EcoIssues#23461]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
Was laying down hewn logs while building base and got kicked.

**Expected behavior:**
Was expecting to be able to finish building base.

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The anticheat feature in the server configuration is turned off by default as it is still experimental. You can ask your server administrator to turn it off for now, if you see more problems with this, while we're looking into how to improve the feature further.
