### ISSUE TITLE
USER ISSUE: Build Asphalt and you will dropped away

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#23460]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
1. Try to build a 10 piece road (asphalt) 
2. Select the 10 blocks (build it at once - inline)
3. Click on build (right click) 
4. You will dropped away from where you are standing
5. Doesn't matter you are in the way or not

**Expected behavior:**
Don't drop me away 2-3 block where I stood

**Actual behavior:**
Drop me away at lease 2-3 block

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Zozoom** [comment]
https://user-images.githubusercontent.com/4950285/190702683-bd151c45-4b1c-445d-bee3-12d0891d940f.mp4

Here is a short video about this issue to make it more easy to reproduce and see that strange behavior.

**Comment by Daniel-Magulado** [comment]
Hi @Zozoom 

Thank you for submitting this bug report. We are currently aware of this issue where actions and constructions done teleports the player. I'll be merging this report with an already existing one.  

https://github.com/StrangeLoopGames/EcoIssues/issues/23455

**Comment by Zozoom** [comment]
Thank you for the quick respond :)
