### ISSUE TITLE
USER ISSUE: Low FPS 

### ISSUE THREAD

**Issue by GrilleGustav** [StrangeLoopGames/EcoIssues#23467]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
Playing game with own server.
I have Ryzen 5900x 3600MHz Ram, and RTX 3090.
I use Windows 11 with newest updates.Also i have the newest graphics driver

**Expected behavior:**
100 FPS+

**Actual behavior:**
<30 FPS 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9594885/Player.log)

**Comment by D3nnis3n** [comment]
This is not a specific issue, but part of a ongoing performance refactor that will take a longer time, hence closing this.
