### ISSUE TITLE
USER ISSUE: No load old world

### ISSUE THREAD

**Issue by Spectrum1985** [StrangeLoopGames/EcoIssues#23474]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
i try to connect then nothing

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.Avatar.get_Clothing()
   at Eco.Core.Controller.SyncPropertyInfo.GetValue(IMvcNetClient client, Object obj)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Avatar' of 'Eco.Gameplay.Players.User'
Error during packaging property 'Clothing' of 'Eco.Gameplay.Players.Avatar'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com with the full logs of server and client, the savegame of the world and which version it was created on.

**Comment by Spectrum1985** [comment]
What a problem what are you doing man ????
My ticket closed ????
whats ????

ср, 21 сент. 2022 г. в 03:00, Dennis Scholz ***@***.***>:

**Comment by D3nnis3n** [comment]
This tracker is for bug reports, the issue you are having is a support issue though, hence my request to contact support and closing of this issue :)

**Comment by Spectrum1985** [comment]
Ok, thank you.

чт, 22 сент. 2022 г. в 17:33, Dennis Scholz ***@***.***>:

**Comment by Spectrum1985** [comment]
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of
an object.
   at Eco.Gameplay.Players.Avatar.get_Clothing()
   at Eco.Core.Controller.SyncPropertyInfo.GetValue(IMvcNetClient client,
Object obj)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient
boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Avatar' of 'Eco.Gameplay.Players.User'
Error during packaging property 'Clothing' of
'Eco.Gameplay.Players.Avatar'</size>

Log File:
Initialize engine version: 2020.3.35f1 (18e4db7a9996)
[Subsystems] Discovering subsystems at path D:/Program Files
(x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:
    VRAM:     4043 MB
    Driver:   31.0.15.1694
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.996600 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Assets.Scripts.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

DontDestroyOnLoad only works for root GameObjects or components on root
GameObjects.
WwiseUnity: Wwise(R) SDK Version 2021.1.6 Build 7774.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: D:/Program Files
(x86)/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

Shader 'Curved/Triplanar Obscure Glass': fallback shader
'Curved/TriplanarMasked' not found
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script (NotificationsController) on this Behaviour is
missing!
The referenced script on this Behaviour (Game Object 'Camera') is missing!
The referenced script on this Behaviour (Game Object 'Table') is missing!
The referenced script on this Behaviour (Game Object 'Notification') is
missing!
Initializing platform: SteamPlatform
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
PlatformManager:AddPrimaryPlatform(Object[])

Failed to initialize social platform: DiscordSocialNetwork.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

Uploading Crash Report
ResultException: InternalError
  at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags)
[0x00000] in <00000000000000000000000000000000>:0
  at DiscordSocialNetwork.Initialize () [0x00000] in
<00000000000000000000000000000000>:0
  at SocialNetworkManager.AttemptAddSocialPlatform (System.Type
socialPlatformType, System.Object[] p) [0x00000] in
<00000000000000000000000000000000>:0
  at SocialNetworkManager.AddSocialPlatforms () [0x00000] in
<00000000000000000000000000000000>:0
  at SocialNetworkManager.Awake () [0x00000] in
<00000000000000000000000000000000>:0
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

Initialized social platform: SteamSocialNetwork
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

OvrLipSync Awake: Queried SampleRate: 48000 BufferSize: 16000
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
OVRLipSync:Initialize()
OVRLipSync:Awake()

Authenticating with our primary platform.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Login(String, String, Boolean)
NetworkManager:Start()

Ambiguous UI component types ignored:
SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI,AutoModalUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.UIManager:Start()

[07:51:13.920] The desired audio input device is not available on the
system.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoiceManager:SetActiveVoiceInputDevice(String, AsyncCallback)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncNoResult:SetComplete()
VivoxUnity.Private.<>c__DisplayClass31_0:<BeginRefresh>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
System.Threading.InvocationEntryDelegate:Invoke(IntPtr)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

[07:51:18.034] Received login result from our primary platform. (Succes:
True | Message: )
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
System.Action`1:Invoke(T)
<>c__DisplayClass18_1:<PerformPlatformLogin>b__0(LoginSession, String)
System.Action`2:Invoke(T1, T2)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:51:18.065] Account isn't developer tier.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Authentication.DevAuthentication:ValidadeSession(LoginSession)
DevAuthenticationLogin:<Awake>b__2_0()
UnityEngine.UIElements.SavePersistentViewData:Invoke()
NetworkManager:HandleLoginResult(LoginResult)
System.Action`1:Invoke(T)
<>c__DisplayClass18_1:<PerformPlatformLogin>b__0(LoginSession, String)
System.Action`2:Invoke(T1, T2)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:51:19.370] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
System.AsyncCallback:Invoke(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
System.Threading.InvocationEntryDelegate:Invoke(IntPtr)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

The referenced script on this Behaviour (Game Object '<null>') is missing!
DG.Tweening.DOTween:InitCheck()
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, T2, Single,
ABSTweenPlugin`3)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Color, Single)
DG.Tweening.DOTweenModuleUI:DOColor(Graphic, Color, Single)
HighlightableUI:Highlight(Boolean)
System.Action`2:Invoke(T1, T2)
Eco.Shared.Utils.ArrayExtensions:ForEachIndex(T[], Action`2)
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.Xml.Serialization.XmlElementEventHandler:Invoke(Object,
XmlElementEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData,
EventFunction`1)
UnityEngine.EventSystems.BaseInputModule:HandlePointerExitAndEnter(PointerEventData,
GameObject)
UI.EcoInputModule:ProcessMove(PointerEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[ line -1340611336]

[07:51:38.929] Connecting to 192.168.1.5:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(String, Int32)
Eco.Shared.Networking.NetworkClient:Connect(ExtendedServerInfo)
SelectedServerUI:Join()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
System.Xml.Serialization.XmlElementEventHandler:Invoke(Object,
XmlElementEventArgs)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData,
EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData,
GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

Shader 'Curved/Triplanar Obscure Glass': fallback shader
'Curved/TriplanarMasked' not found
Shader 'Curved/Triplanar Obscure Glass': fallback shader
'Curved/TriplanarMasked' not found
The referenced script on this Behaviour (Game Object '') is missing!
[07:52:03.338] Upgrading sprite asset [Emoticon_Large_Chicken] to version
1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.361] Upgrading sprite asset [Emoticon_Large_Elk] to version 1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.362] Upgrading sprite asset [Emoticon_Large_Fire] to version
1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.362] Upgrading sprite asset [Emoticon_Large_No] to version 1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.362] Upgrading sprite asset [Emoticon_Large_PickAxe] to version
1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.362] Upgrading sprite asset [Emoticon_Large_Meteor] to version
1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:03.362] Upgrading sprite asset [EmojiFaces] to version 1.1.0.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
TMPro.TMP_SpriteAsset:UpgradeSpriteAsset()
TMPro.TMP_SpriteAsset:UpdateLookupTables()
SpriteAssetLoader:BuildSprite(TMP_SpriteAsset)
SpriteAssetLoader:BuildSpriteAssets()
<BuildItems>d__57:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[07:52:04.877] Disconnected with error: Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of
an object.
   at Eco.Gameplay.Players.Avatar.get_Clothing()
   at Eco.Core.Controller.SyncPropertyInfo.GetValue(IMvcNetClient client,
Object obj)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient
boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Avatar' of 'Eco.Gameplay.Players.User'
Error during packaging property 'Clothing' of
'Eco.Gameplay.Players.Avatar'</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
System.Action`2:Invoke(T1, T2)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
UnityEngine.Experimental.Audio.SampleFramesHandler:Invoke(AudioSampleProvider,
UInt32)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection,
DisconnectReason)
UnityEngine.AddressableAssets.<>c:.cctor()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
<>c__DisplayClass67_0:<Initialize>b__0()
UnityEngine.UIElements.SavePersistentViewData:Invoke()
SimpleFileBrowser.OnRenameCompleted:Invoke(String)
System.Threading.ExecutionContext:RunInternal(ExecutionContext,
ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback,
Object)
UnityEngine.UIElements.SavePersistentViewData:Invoke()

Unloading 7 Unused Serialized files (Serialized files now loaded: 2)

Unloading 6272 unused Assets to reduce memory usage. Loaded Objects now:
178250.
Total: 607.677700 ms (FindLiveObjects: 9.460300 ms CreateObjectMapping:
21.630700 ms MarkObjects: 572.222100 ms  DeleteObjects: 4.364100 ms)


what is it

чт, 22 сент. 2022 г. в 19:30, Ilias Port ***@***.***>:
