### ISSUE TITLE
USER ISSUE: bug when doing an action standing on a ramp/built block

### ISSUE THREAD

**Issue by Femidahl** [StrangeLoopGames/EcoIssues#23470]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.2 beta release-342

**Steps to Reproduce:**
stand on a ramp or a roof you've built. Try to hack stone with pickaxe or place a block with hammer. 

**Expected behavior:**
stand completely still on the spot

**Actual behavior:**
makes you jump and throws you backwards a little. if you stand completely still after the first time it happend, it wont happen again (before you move). if you move to target something further away, it will happen again.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.6.3.
