### ISSUE TITLE
USER ISSUE: Typo in reinfroced concrete

### ISSUE THREAD

**Issue by Red463** [StrangeLoopGames/EcoIssues#23485]
\
**User Id: (slg166381)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
See reinforced concrete description

**Expected behavior:**
It should say sturdy (I think?)

**Actual behavior:**
It says study

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Red463 Thank you for reporting this, I have forwarded this to our developer to 'study' it =D 

Issue reference : ECO-24537

**Comment by D3nnis3n** [comment]
Fixed in Update 10.
