### ISSUE TITLE
[Eco Version 9.6.3] MountAction doesn't seem to trigger when mounting a vehicle/object

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#23486]
I remember that before 9.6, we used OpenAction to allow specific users to access vehicles of anyone.

With 9.6 and introduction of WoodShopCart, the MountAction has been added. However, It doesn't seem to be able to trigger a MountAction using a law. We are trying to allow some policeman to access any Vehicles, but we're not able to, MountAction laws never trigger.

Using a simple SendNotice in a Law with MountAction, and mounting on a steam truck, doesn't display the notice.

Using the old OpenAction doesn't work either, it allows to access the Vehicles Popup, but doesn't allow to mount on the vehicle.

**Comment by Daniel-Magulado** [comment]
Hi @Thibault-Brocheton 

Thank you for submitting this bug report. I can verify that the trigger "Mount Action" is not working.
I created an internal report for this.
You may use this reference ID: ECO-24546 if you ever wish to make a follow-up or request an update of the status of this bug.

**Comment by jwmc80** [comment]
This prevents the Mount/Unmount action from being used in laws to "Ignore Auth" on illegally parked vehicles.
