### ISSUE TITLE
USER ISSUE: status windows open nearly everytime i use the elevator

### ISSUE THREAD

**Issue by Night-Sky1970** [StrangeLoopGames/EcoIssues#23484]
\
**User Id: (slg214809)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
simple use the elevator.. on near every push.. up down or stop it opens the status window.. wasnt it possible to use the elevator aswell with richt mouse button ? that also doesnt work anymore.. it got to be Eit doesnt matter what i hold in my hand.. it always opens..

**Expected behavior:**
that the elevator goes up n down without getting a opening of the status window

**Actual behavior:**
it opens status window to auth. ppl

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes,, also happens without mods in a single player game

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
hi @Night-Sky1970 Thank you for reporting this issue to us, happy to inform that this issue is already fixed for future patch, if you still facing this issue in the future, please let us know
