### ISSUE TITLE
USER ISSUE: World Conversion BUG

### ISSUE THREAD

**Issue by CAHbKA-IV** [StrangeLoopGames/EcoIssues#23480]
\
**User Id: (slg182865)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
Use save from old server 9.4.6

**Expected behavior:**
Start Game

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.Avatar.get_Clothing()
   at Eco.Core.Controller.SyncPropertyInfo.GetValue(IMvcNetClient client, Object obj)
   at Eco.Core.Controller.ControllerManager.PackageMember(IMvcNetClient boundClient, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Error during packaging property 'Avatar' of 'Eco.Gameplay.Players.User'
Error during packaging property 'Clothing' of 'Eco.Gameplay.Players.Avatar'</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
1. No mods
2. Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You will need to update to version 9.5.4 first, then to 9.6.3. You can do so by setting the version in Steam to 9.5.4 first by right clicking Steam, Properties -> Betas -> 9.5.4.
