### ISSUE TITLE
Arrastra not affected by Upgrades

### ISSUE THREAD

**Issue by Delta1136** [StrangeLoopGames/EcoIssues#23491]
As shown in the attached Video the amount of ore needed doesn't change when installing an Upgrade.

https://youtu.be/517qRRox3o8 

Version 0.9.6.3 Beta release-343 

ServerID- 9473dac5-Oc35-4737-aec8-7d5ed566d38e

**Comment by Daniel-Magulado** [comment]
Hi @Delta1136 

Thank you for submitting this bug report however, this is intended and by design. Arrastra only benefits from upgrades by reducing the crafting time. It does not benefit from resource reduction. This will also be the case for other refining tables. I'll be closing this.

**Comment by mirasrael** [comment]
Can we add Tutorial for Arrastra and static ingredients to avoid confusion? (It may popup when user first time open crafting station with static ingredients)
