### ISSUE TITLE
Lighting issues + eye adjustment

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2349]
It would be better if the sun made a big flare if you looked at it, and the terrain wasnt black. This is taken after typing /day
![image](https://user-images.githubusercontent.com/3536496/30936933-3aad2716-a38a-11e7-8073-01bbb1ab0e1c.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/30937136-bf014880-a38a-11e7-8fad-9361567f9bcf.png)
Heres what it looks like standing on that mountain

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/30937279-29db74f0-a38b-11e7-91a8-1795111578b2.png)
With softsunlight = .1 and sky intensity = .2

**Comment by metachronism** [comment]
you are not on latest if you are getting these issues, lots of changes checked in to svn for this

soft sunlight doesn't work and blooms out caves and indoor areas

**Comment by metachronism** [comment]
dark side of a mountain, after eyes adjust:
![image](https://user-images.githubusercontent.com/3150561/30941799-2c2ba14c-a39c-11e7-9550-d900b9d756ce.png)

**Comment by metachronism** [comment]
with sun in view:
![image](https://user-images.githubusercontent.com/3150561/30941809-3d95fc84-a39c-11e7-9dc5-87b359758d53.png)

**Comment by metachronism** [comment]
other mountain, looking in sun:
![image](https://user-images.githubusercontent.com/3150561/30941895-8f082588-a39c-11e7-8408-b450622ff969.png)

**Comment by metachronism** [comment]
before eyes adjust:
![image](https://user-images.githubusercontent.com/3150561/30941904-9a230014-a39c-11e7-8e1d-a2ec44bafb03.png)

**Comment by metachronism** [comment]
after:
![image](https://user-images.githubusercontent.com/3150561/30941911-a0d78db2-a39c-11e7-9b13-d9b295bdc675.png)

**Comment by MarjieAVolk** [comment]
Does this mean we're gonna need sun hats?

**Comment by Conchipedia** [comment]
would it be possible to get "Lock to Noon" back as some of us miners are having real problems (having to make the game really chuky to get rid of shadows)
