### ISSUE TITLE
USER ISSUE: Black screen and loading time

### ISSUE THREAD

**Issue by Rasmus04Larsson** [StrangeLoopGames/EcoIssues#23492]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
Try to join my local server	

**Expected behavior:**
To join the world

**Actual behavior:**
Needs to restart like 10 times to get in and when i do there is a black screen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Rasmus04Larsson 

Thank you for submitting this bug report.
Is this consistently happening to you?
Could you provide us a recording video of it as it happens?
We would also like to request your log file after it happens. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Lastly, kindly provide us the complete specification of your system.
We would also appreciate if you could provide us the player preference files in Eco folder registry if you can.
To get the player preference;
Open Windows search and type RUN.
Click on the RUN app and type Regedit.
Navigate your way to \HKEY_CURRENT_USER\SOFTWARE\Strange Loop Games\Eco and then export the whole Eco folder.
Once done, please upload here.
This will help us investigate this issue further.

Looking forward to your response.

**Comment by D3nnis3n** [comment]
Closing due to no response.
