### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by neotheaven** [StrangeLoopGames/EcoIssues#23500]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
Tried to log into my single player world

**Expected behavior:**
It should have logged in.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9748406/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @neotheaven 

This could be an issue with our auth server or could be something with your account. If you're still having this issue, I highly recommend getting in touch with our support at [support@strangeloopgames.com](mailto:support@strangeloopgames.com).
