### ISSUE TITLE
Item duplication when laggy

### ISSUE THREAD

**Issue by Altaric** [StrangeLoopGames/EcoIssues#23506]
Playing on official White tiger, I had the issue when removing a stockpile with a hammer and there is something still in it that leads to duplicated items.

Steps to replicate:
* Place a stockpile on the ground
* Fill it with 20 coal (or anything that is not shown as a box)
* Hammer the stockpile twice (once to pick up content, and once to pick up the stockpile)
* If you were faster than lattency, the stockpile and content gets picked up, but the blocks remain, so they can be picked up 

It also works with a full stockpile if you empty it via inventory screen shift drag and hammer it before the server notices.

Also, it happened to me when dumping my car content on a stockpile (unfortunately on the road) which lead to boxed that can't be picked up.
It is pretty easy to trigger from my experience.

Eco version 0.9.6.3 beta r343

Discord @Altaric#6865

**Comment by Daniel-Magulado** [comment]
Hi @Altaric 

Thank you for submitting this bug report. We are currently aware of this issue and a fix is already set to be rolled out in the next game patch. Please look forward to it.

Referece ID ECO-23487.
