### ISSUE TITLE
USER ISSUE: Disparition d'ateliers

### ISSUE THREAD

**Issue by Lehmatork** [StrangeLoopGames/EcoIssues#23515]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
1. Placer un atelier
2. Partir chasser, ou récolter assez loin, revenir proche de notre maison/poste de travail.	

**Expected behavior:**
Il devrait y avoir les ateliers visible et pas seulement les ordres de travail.	

**Actual behavior:**
Les ordres de travail sur mes ateliers sont visible mais certain atelier ont disparus/ne sont pas visible.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non, aucun.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23603
