### ISSUE TITLE
USER ISSUE: Black Screen

### ISSUE THREAD

**Issue by Frabilll** [StrangeLoopGames/EcoIssues#23513]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
Log into world

**Expected behavior:**
should be able to see world

**Actual behavior:**
see black screen, can pull up the escape menu, and everynow and then the mouse but nothing else, music is playing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Frabilll** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/9897087/Player-prev.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9897086/Player.log)

**Comment by RemonRamy** [comment]
Hello again @Frabilll,

We can confirm with a high degree of certainty that the steps above will resolve the issue. If you're still having problems, feel free to give us an update either here or through Discord.

Closing as resolved, internal reference: ECO-25271.

Kind Regards,
Remon
