### ISSUE TITLE
USER ISSUE: Holding 'E' will not continue to pickup blocks

### ISSUE THREAD

**Issue by CozyKittenTV** [StrangeLoopGames/EcoIssues#23524]
\
**User Id: (slg164040)**
**Version:** 0.9.6.4 beta release-354

**Steps to Reproduce:**
Hold E and attempt to pickup stone

**Expected behavior:**
picks up stones

**Actual behavior:**
picks up 1 stone

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, tried in singleplayer without mods, same issue

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @CozyKittenTV 

Thank you for submitting this bug report. I'll be merging it to an earlier similar submitted bug report.
