### ISSUE TITLE
USER ISSUE: Cannot fast pick up ores anymore

### ISSUE THREAD

**Issue by ReindH** [StrangeLoopGames/EcoIssues#23523]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.4 beta release-354

**Steps to Reproduce:**
Keep the interact button (E) held down.

**Expected behavior:**
Should pick up ores as long as it's held down

**Actual behavior:**
It only picks up the first ore

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. The recent update today broke it

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/23524

**Comment by Daniel-Magulado** [comment]
Hi @ReindH 

Thank you for submitting this bug report. We are currently aware of this issue and our developers are working on a
a quick fix to push in the next game update.
Fix ID: ECO-25240

**Comment by D3nnis3n** [comment]
Fixed in 9.6.5.
