### ISSUE TITLE
USER ISSUE: boxes left behind ehen moving stockpile

### ISSUE THREAD

**Issue by jarhead44512** [StrangeLoopGames/EcoIssues#23522]
\
**User Id: (Not logged user)**
**Version:** 0.9.6.3 beta release-343

**Steps to Reproduce:**
small stock pile had objects in itDrag objects to a different stockpile before the animation was complete for an empty small stockpile pick it up.Boxees left behind and cannot interact 

**Expected behavior:**
move stockpile and the stuff in it

**Actual behavior:**
read above

**Do you have mods installed? Does the issue happen when no mods are installed?:**
not sure im on a server 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @jarhead44512 

Thank you for submitting this bug report. This is actually similar to the duplication bug based on the steps to reproduce you provided. A fix is already set to be patched out in the next game update. Please look forward to it.
I will be closing this for now with fix ID reference ECO-23487. Do not hesitate to report this bug again if you ever encounter it again on the next game update.
