### ISSUE TITLE
Glass is not visable (even with glass reflection on), and being able to jump through glass

### ISSUE THREAD

**Issue by DiendaPhoenix** [StrangeLoopGames/EcoIssues#23525]
This looks just like there is no glass in here at all and we have floating doors.... both during day and night time. Please try to find something inbetween if need be... 
Meanwhile if you jump against the glass you still jump straight through it, even if you have no authorization to be there...

![20221107180140_1](https://user-images.githubusercontent.com/117671550/200370303-6730e149-a736-42e7-a33b-c95870486dd4.jpg)
![20221107175105_1](https://user-images.githubusercontent.com/117671550/200370308-0dc5f3c9-d9d2-4ea7-8e99-c2172085f507.jpg)
![20221107175104_1](https://user-images.githubusercontent.com/117671550/200370325-dbd65dd7-0904-4802-9b45-0d9bd4b59cd2.jpg)
![20221107175025_1](https://user-images.githubusercontent.com/117671550/200370336-b16920ff-73b8-4cc6-a6a5-10496f8c9b10.jpg)
![20221107180333_1](https://user-images.githubusercontent.com/117671550/200370707-5cfc4294-3a21-49a2-90ac-57df3b470bd4.jpg)
![20221107175044_1](https://user-images.githubusercontent.com/117671550/200370344-0d6358d1-6705-4dd6-a373-98d029792782.jpg)

**Comment by TwixterZ** [comment]
@DiendaPhoenix thank you for bringing this to our attention, I have forwarded this to our developer for tweaking 

Case reference : ECO-25254

**Comment by D3nnis3n** [comment]
Fixed in 9.6.6.
