### ISSUE TITLE
Alpha.6 [E80b350f] Trees still spawning in stockpiles

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2352]
![image](https://user-images.githubusercontent.com/1900106/30937548-6bce50a2-a3d7-11e7-9751-8a499bc5f28a.png)

**Comment by Fank** [comment]
Not only trees
![image](https://user-images.githubusercontent.com/1900106/31038522-8e85381c-a577-11e7-8bf4-876df34ce222.png)

**Comment by stormoffires** [comment]
will this fix in 6.1. also fix trees in crop fields?

**Comment by metachronism** [comment]
fixed for stockpiles
