### ISSUE TITLE
Hitting a stockpile or Dirt ramp with hammer just throwing into empty slot not stacking with others carried ##e80b350f

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2353]
Not sure if this is doiung for other items as this was the only 2 i just tried

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/1945

**Comment by Conchipedia** [comment]
i tried searching for it under stacks (apologies)

**Comment by MarjieAVolk** [comment]
no problem :)
