### ISSUE TITLE
USER ISSUE: impossible de se connecter

### ISSUE THREAD

**Issue by LilZloty** [StrangeLoopGames/EcoIssues#23535]
\
**User Id: (slg224070)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
connexion impossible

**Expected behavior:**
se connecter

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Mot de passe incorrect.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This means the password you entered for the server is incorrect, please ask the respective server admin for the correct password.
