### ISSUE TITLE
USER ISSUE: Mots de passe incorecte

### ISSUE THREAD

**Issue by LuminoseSan** [StrangeLoopGames/EcoIssues#23534]
\
**User Id: (slg224004)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
Je me connecte avec omgleleak en mdp 

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Mot de passe incorrect.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Wrong password, not a bug.
