### ISSUE TITLE
USER ISSUE: Selling in a Barter Shop Wood (Autocrafter)

### ISSUE THREAD

**Issue by lifezoned4** [StrangeLoopGames/EcoIssues#23537]
\
**User Id: (slg202514)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
1. Put Wood in Hand
2. Pay less or equal than needed price
3. Buy Product
4. Crash
5. Things are sold and bought after crash

**Expected behavior:**
Things are sold and bought and no crash happens

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink[T](ILinkableParameterized`1 linkable, T param)
   at Eco.Gameplay.Components.StoreComponent.StoreTradeDescription(PurchaseData purchaseData, Boolean describeToTradeInit)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player tradeIniator, BSONObject tradeData, BankAccount purchaserAccount)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes we have some mods but I can not test it with out mods atm

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/9998518/Player.log)

**Comment by TwixterZ** [comment]
@lifezoned4  for reporting this issue to us, we will merge your issue to another existing issue here : https://github.com/StrangeLoopGames/EcoIssues/issues/23552
