### ISSUE TITLE
USER ISSUE: Electricity consumed by Neighbour on other property

### ISSUE THREAD

**Issue by Paxilein** [StrangeLoopGames/EcoIssues#23546]
\
**User Id: (slg179898)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
- Have Steam Generator and Combustion Generator on one property
- Place some electricity consumer on another property that's closeby
- Put Fuel into the generators
- power on the consumers

The combustion generator is fueled but turned off and about 50m away from consumers on other property. The steam generator is fueled and running and about 55m away from consumers on other property. There're two unclaimed claims space between the properties.
The steam generator on the other property is not running and only turns on when the steam generator on my property is being turned off.
![mapview](https://user-images.githubusercontent.com/24937322/202531275-97009d19-1d1e-4b59-8f90-c8f92b21fe69.JPG)
Blue cross is the steam generator, black cross is the combustion generator...
When I remove the combustion generator the connection is separated.

**Expected behavior:**
Power should only be consumed by authorized consumers within range

**Actual behavior:**
Power is consumed by consumers on other property 50m away without any connection between them	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, mods installed but as it's running on a public server I no idea how to test that without mods currently. Something for the bug hunters to try out?
The server has extended ranges but I think ownership and authorization should also apply to generators?

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is working as intended. We do plan to make power a thing that can be sold and depends on authorization, but for now it works basically like a Zigbee network, once any producers or receivers are in range of each other, the network will expand, which supports global electricity networks for big servers that offer public electricity via taxes.
