### ISSUE TITLE
USER ISSUE: Chat vocal qui ne fonctionne pas

### ISSUE THREAD

**Issue by Tylee83** [StrangeLoopGames/EcoIssues#23543]
\
**User Id: (slg223923)**
**Version:** 0.9.6.6 beta release-357

**Steps to Reproduce:**
Se connecter au jeu avec le chat activé et les bon périphériques choisi

**Expected behavior:**
Chat vocal qui fonctionne et une bonne comunication en jeu

**Actual behavior:**
je n'entend personne et personne ne m'entend je ne vois pas d'icone saficher lors d'une interaction vocal (j'ai desinstaller reinstaller le jeu a 2 reprise mais rien a faire)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23581
