### ISSUE TITLE
[playtest] Game not responding

### ISSUE THREAD

**Issue by JohnyDaison** [StrangeLoopGames/EcoIssues#23549]
I was moving Agouti Carcass from Tent Storage to Small Stockpile and the game went not responding for like 15 seconds. Windows asked if it should kill it or wait, I clicked wait for it to respond and it recovered.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10045284/Player.log)

**Comment by D3nnis3n** [comment]
Was adressed in final release.
