### ISSUE TITLE
Second crash

### ISSUE THREAD

**Issue by HighlyWobbly** [StrangeLoopGames/EcoIssues#23544]
Crash upon being in the game for some time. Timing seems to be inconsistent, but it usually happens every few hours? No idea what is causing it, the game crashes completely, but doesn't close, just freezes. I hear a little windows sound to indicate that it has crashed though.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10026639/Player-prev.log)
https://drive.google.com/file/d/1ciKLU4CADLDjBXeyFvCWsn4QOuF-iWpE/view?usp=share_link

^Second file is 423mb for some reason, so couldn't upload it normally.

**Comment by D3nnis3n** [comment]
Adressed in final release.
