### ISSUE TITLE
[Playtest  0.9.7.0 staging-2494][CTD][Giant Panda] Player Logs

### ISSUE THREAD

**Issue by DinosaurDundee** [StrangeLoopGames/EcoIssues#23545]
Hello,

Happened on Giant Panda.

Crash_2022-11-17_010605977 - happened while walking around spawn area
Crash_2022-11-17_021150244 - happened while walking in desert close to 564.68.1464
Crash_2022-11-17_030320087 - happened while walking in desert close to 564.68.1464 (second time)
[Crash_2022-11-17_010605977.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10027420/Crash_2022-11-17_010605977.zip)
[Crash_2022-11-17_021150244.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10027421/Crash_2022-11-17_021150244.zip)
[Crash_2022-11-17_030320087.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10027422/Crash_2022-11-17_030320087.zip)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10027424/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10027425/Player-prev.log)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-17_043743690 - happened while walking in desert close to 564.68.1464 (third time)
[Crash_2022-11-17_043743690.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10027782/Crash_2022-11-17_043743690.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-17_045424089 - jumping in the woods
[Crash_2022-11-17_045424089.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10028140/Crash_2022-11-17_045424089.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-17_050350537 - harvesting tree in the same area as the crash before
[Crash_2022-11-17_050350537.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10028183/Crash_2022-11-17_050350537.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-17_050731300 - harvesting tree at the same location as last crash
[Crash_2022-11-17_050731300.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10028204/Crash_2022-11-17_050731300.zip)

**Comment by D3nnis3n** [comment]
Adressed in final release.
