### ISSUE TITLE
[Playtest 0.9.7.0 staging-2495][CTD][Giant Panda] Player Logs

### ISSUE THREAD

**Issue by DinosaurDundee** [StrangeLoopGames/EcoIssues#23548]
Hello,

Crash_2022-11-18_001242104 - harvesting wood
[Crash_2022-11-18_001242104.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10036646/Crash_2022-11-18_001242104.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-18_002919154 - harvesting wood close to previous crash location
[Crash_2022-11-18_002919154.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10036690/Crash_2022-11-18_002919154.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-18_004154617 - Harvesting wood, same area
[Crash_2022-11-18_004154617.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10036731/Crash_2022-11-18_004154617.zip)

**Comment by DinosaurDundee** [comment]
Crash_2022-11-18_014129896 - planting tree, same area
[Crash_2022-11-18_014129896.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10036985/Crash_2022-11-18_014129896.zip)

**Comment by D3nnis3n** [comment]
Adressed in final release.
