### ISSUE TITLE
[Eco 9.6.6] Client crash during Barter trade

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#23552]
Following Micado's message on discord: https://discord.com/channels/254025510651297802/258380724518912000/1043268279164215417

When executing a Barter trade (with Barter currency defined in the shop), the user who make the action crash.
![image](https://user-images.githubusercontent.com/7646137/202862638-f5f28809-c2d1-4bce-b5ae-26143ddacedc.png)

By looking at the code, I can confirm there is an issue (regression from 20/09/2022 by Yatim)

File StoreComponent.cs, function StoreTradeDescription
In case of Barter trade, "var currency      = this.creditComponent.CreditData.Currency" is null
then, the call to currency.UILink causes an NRE

**Comment by TwixterZ** [comment]
@Thibault-Brocheton Thank you for all the information provided, we have informed the same to our devs for a possible fix.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23585
