### ISSUE TITLE
cant drive in tunnel underwater

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#23559]
![image](https://user-images.githubusercontent.com/31536813/203310315-4981ff62-1220-499e-8fcd-c9e54edc3254.png)

**Comment by CharlyLeth** [comment]
We have this issue too - tried with multible vehicles. Worked fine before the latest update.

**Comment by TwixterZ** [comment]
@Arend90 @CharlyLeth Thank you for writing to us about this, we are aware of this issue and a fix is being developed

**Comment by D3nnis3n** [comment]
Fixed in 9.7.2.
