### ISSUE TITLE
USER ISSUE: App authentication failed on local server through steam

### ISSUE THREAD

**Issue by LaureBedu6** [StrangeLoopGames/EcoIssues#23558]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.0 beta release-374

**Steps to Reproduce:**
I played 60 hours on a local server through steam. Today I tried loggin the same as usual, and got this error :"App authentication failed: Both -user and -passwordOrToken should be provided in command line". In the corner at the right of the main screen, I can see "Logged in as '[MY STEAM NAME]'"

**Expected behavior:**
Being able to loggin

**Actual behavior:**
Server crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_221122125935.log](https://github.com/StrangeLoopGames/EcoIssues/files/10067186/log_221122125935.log)

**Comment by JoVodK** [comment]
same problem plz help me :)

**Comment by D3nnis3n** [comment]
Fixed in 9.7.1
