### ISSUE TITLE
Unable to join or create my own session

### ISSUE THREAD

**Issue by KennyClan01** [StrangeLoopGames/EcoIssues#23557]
right after the update, will not allow me to make my own session, or join a current one I made, stating unable to join due to user name and password, when I launch the game with 0 issues. Game is unplayable at this state

**Comment by JoVodK** [comment]
same

**Comment by LaureBedu6** [comment]
Same here :
https://github.com/StrangeLoopGames/EcoIssues/issues/23558#issue-1459733613

**Comment by SlayksWood** [comment]
Thanks you for the report, the fix will be in a few hours, sorry for that. merged to #23558

**Comment by D3nnis3n** [comment]
Fixed in 9.7.1

**Comment by JoVodK** [comment]
Thank you

Vankerckhoven Jonas

Le mar. 22 nov. 2022, 19:35, Dennis Scholz ***@***.***> a
écrit :
