### ISSUE TITLE
USER ISSUE: Sleeping Doppleganger

### ISSUE THREAD

**Issue by echoAwoo** [StrangeLoopGames/EcoIssues#23560]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.0 beta release-374

**Steps to Reproduce:**
Lie in bed
See Doppleganger

**Expected behavior:**
Not have Doppleganger

**Actual behavior:**
Sleeping Doppleganger

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@echoAwoo Thanks for the report.
Can you provide more details? What bed did you use? Perhaps you can do the video.
Also please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed.
