### ISSUE TITLE
USER ISSUE: Invisible Plant Fiber

### ISSUE THREAD

**Issue by ianjirka** [StrangeLoopGames/EcoIssues#23562]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.1 beta release-376

**Steps to Reproduce:**
Not sure.  First cutting of a plant produced 2 in my inventory, everything after that doesn't go into my inventory, but I can craft with it (the proper quantity shows when I look at a recipie that takes it)

**Expected behavior:**
It should have gone into my inventory where I can see it.	

**Actual behavior:**
It is apparently invisible.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
We're not able to reproduce and would need additional info, for example a video.

**Comment by ianjirka** [comment]
I figured it out - the fibers were going in my backpack, which I forgot I had.  The first hour I didn't need it because everything went into the quickbar and building inventories showed all other inventories I had so - I just forgot it existed.

**Comment by D3nnis3n** [comment]
Thanks for getting back to us and glad you got it solved.
