### ISSUE TITLE
USER ISSUE: Authentifizierungsserver nicht verfügbar?

### ISSUE THREAD

**Issue by Andreas-Schaefer** [StrangeLoopGames/EcoIssues#23576]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
Starten eines bestehenden Spiels oder Erstellen einer neuen Welt und dann beim Starten kommt der Fehler.

**Expected behavior:**
Das Spiel startet, und bekommt kein Timeout nach 10 Sekunden!

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Die Anmeldungsinfomation konnte nicht verifiziert werden. Unsere Authentifizierungsserver könnten außer Betrieb sein.

<size=60,00%>The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein, keine Ahnung, hab ja keine Mods... also vermutlich ja auf die zweite Frage...

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hallo Andreas,
der Fehler erscheint, wenn du unseren Authentifizierungsserver nicht erreichen kannst.

Das ist entweder der Fall, weil du offline bist oder weil eine Sicherheitssoftware den Zugriff blockiert (Firewall, Antivirus, etc.).
Das bitte mal prüfen und ggf. bei support@strangeloopgames.com melden, dies ist aber kein Fehler im Spiel.
