### ISSUE TITLE
Eco Server wiederherstellen und updaten

### ISSUE THREAD

**Issue by Columbus994** [StrangeLoopGames/EcoIssues#23579]
Hallo,

ich habe dir gestern den Text bei Steam geschrieben.
__________________________________

ich habe erst vor kurzem meinen pc neu aufgesetzt und um meinen eco Server zu sichern habe ich den gesamten Ordner Storage gesichert.
Nun habe ich den Ordner in den neuen Dateien durch meine gesicherten Daten ersetzt und ich kann keine Verbindung zum eco Server herstellen.

Dabei ist mir auch aufgefallen, dass der Server nicht mehr den ursprünglichen namen hat sondern den Namen des PC´s hat.

hätte ich noch mehr Daten sichern müssen oder kann man da noch etwas retten...

Beim updaten des Servers hatte ich auch ein paar probleme, weshalb er noch auf der Version 9.4.6 läuft. Der Server ist nicht gestartet ist als ich sowohl eco Server als auch eco selbst geupdatet habe. Was muss ich dabei machen, dass der Server wieder wie gewohnt funktioniert und ich die neuen Funktionen Nutzen kann?
Ist das überhaupt möglich, wäre ein bisschen schade auf die neuen Funktionen zu verzichten und jedes mal neu anzufangen macht auf dauer auch keinen Spaß

ich hoffe mir kann jemand helfen und bedanke mich schon mal im vorraus
LG Columbus

__________________________________

Hier sind die Logs, die du brauchst.

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10094653/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10094654/Player.log)

Also der die alten Dateien sind ja bereits gelöscht, da der PC ja schon neu aufgesetzt ist. Ich wusste leider nicht, dass man den Configs Ordner auch benötigt, drum hab ich den nicht gesichert. 
Besteht ohne diese Dateien, also nur mit den Dateien aus Storage, die Möglichkeit den Server überhaupt wieder zum laufen zu bekommen?

Und wegen dem Thema mit dem Updaten, wie funktioniert das denn, gibt es dafür eine Anleitung, wie genau das Update gemacht werden muss?
Jedes mal, wenn ich updaten wollte ist der Server nicht gestartet. Bzw: Die Updates in der Version 9.4 haben alle Funktioniert, erst ab 9.5 gab es Fehler.
Ich habe sogar vor dem Update alle Mods deaktiviert und den Server nochmal ohne die Mods  gestartet. Selbst dann hat der Server Fehler angezeigt und ließ sich nicht starten. 

Ich hoffe es lässt sich noch etwas machen um meinen Spielstand zu retten und vielen dank für deine Hilfe
LG Columbus

**Comment by D3nnis3n** [comment]
Das sind leider die falschen Logs, ich brauche die Server Logs: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

Ich hatte übrigens gemeint, dass du die in Steam posten sollst, dieser Tracker ist nur für Bugs. Daher schicke die Logs doch bitte zu support@strangeloopgames.com. Der Server läuft auch ohne die Config-Dateien, aber du musst alle Einstellungen die du vorher mal gesetzt hattest, erneut einstellen.

Wir empfehlen, Steam zu verwenden - die Updates für Client und Server funktionieren dort in der Regel problemlos. Wenn du zwingend den heruntergeladenen Server auf unserer Webseite verwenden möchtest, musst du bei einem Update die Configs und Storage Ordner in den neuen Server kopieren, sonst nichts.
