### ISSUE TITLE
USER ISSUE: Map Marker Issues 9.7.2

### ISSUE THREAD

**Issue by echoAwoo** [StrangeLoopGames/EcoIssues#23578]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
Open Map after 9.7.1 -> 9.7.2 update (unsure if important)
See prior created map markers lose their names
Attempt to assign a color

**Expected behavior:**
Map marker names should be preserved through updates
Color should assign under 9.7.2

**Actual behavior:**
Resets color to white
Deletes name on update

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This was a one-time occurance that was necessary for the included update, sorry for that.
