### ISSUE TITLE
USER ISSUE: Shop set to barter currency kicks the player

### ISSUE THREAD

**Issue by ReindH** [StrangeLoopGames/EcoIssues#23574]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
Sell anything to a shop set to barter currency

**Expected behavior:**

**Actual behavior:**
The user gets kicked out of the server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23585
