### ISSUE TITLE
USER ISSUE: Crash lors d'un échange non équivalent

### ISSUE THREAD

**Issue by Samsuffi** [StrangeLoopGames/EcoIssues#23585]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
0. Dans une boutique (ne) proposant (que) le troc
1. Sélectionner un objet à vendre (demandé par le vendeur) : cadavre de lapin (reproduit avec d'autres objets, parfois multiples)
2. ne rien sélectionner en achat (don) (reproduit en sélectionnant des objets en contrepartie)
3.l'échange n'est pas parfaitement équitable ; il est à l'avantage du vendeur
4. valider la transaction
5.valider le message d'information "échange non équitable" > Yes

**Expected behavior:**
L'échange est effectué, même si l'échange n'est pas parfaitement équitable, l'aventure continue sans crash

**Actual behavior:**
L'échange (don) est bien réalisé
Note : lors d'un échange troc précédent, les objets on bien été vendus (disparus de mon inventaire) et la contrepartie achetée (appareu dans mon inventaire)

Crash + Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Systems.TextLinks.UILinkExtensions.UILink[T](ILinkableParameterized`1 linkable, T param)
   at Eco.Gameplay.Components.StoreComponent.StoreTradeDescription(PurchaseData purchaseData, Boolean describeToTradeInit)
   at Eco.Gameplay.Components.StoreComponent.PerformTrade(Player tradeIniator, BSONObject tradeData, BankAccount purchaserAccount)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Pas de mods, version Steam 9.7.2

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.7.3
