### ISSUE TITLE
USER ISSUE:the game does not work offline

### ISSUE THREAD

**Issue by Kulibin552** [StrangeLoopGames/EcoIssues#23586]
Hello, the game does not work offline, it used to work without the Internet. At the moment, I go into the game without the Internet one splash screen
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10097767/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/10097768/Player.log.copy.txt)

**Comment by Daniel-Magulado** [comment]
Hi @Kulibin552 

Thank you for submitting this report. Unfortunately, the game requires an internet connection to work.
You can learn more about the game's system requirements here: https://wiki.play.eco/en/System_Requirements

**Comment by Kulibin552** [comment]
hi Denis
There is a single player mode, why is the Internet for a single game,
before they played without the Internet, it enters the game screensaver to
appear there is no menu, no entry, no exit, we did not have the Internet I
played the game for 10 days in the eco game. We sometimes have the
Internet, sometimes we don’t,

пн, 28 нояб. 2022 г. в 18:22, Daniel Moises Dizon Magulado <
***@***.***>:
