### ISSUE TITLE
USER ISSUE: Spawn at 0,0 on every login

### ISSUE THREAD

**Issue by muzs1** [StrangeLoopGames/EcoIssues#23582]
\
**User Id: (slg161915)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
This seems to be caused by my unity file in https://eco.old.mod.io/road-mixer created this unity file so can provide more info if required.

**Expected behavior:**
Login spawn at last location

**Actual behavior:**
Spawn at 0,0 on every login for all players.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mod code happens even on a blank server once you add the unity file from https://eco.old.mod.io/road-mixer it start to happen. Remove the unity file and it goes back to normal.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by muzs1** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10096485/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10096486/Player-prev.log)

**Comment by muzs1** [comment]
The cause of this issue has been found, if an item is left active in the unity project when it is bundeled it will cause every user to login at the location 0,0 every time. This has only started happening since 9.7+ as it never had this resault in 9.6.
If this is left in its current state you may have other new modders causing the same bug when releasing mods.

**Comment by D3nnis3n** [comment]
This is a developer error, as the log file actually notes, so a wontfix.

"[02:30:54.802] Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/Murrey/AppData/LocalLow/Strange Loop Games/Eco\Mods\EcoBeeMixer.unity3d" is not.  This can cause many problems, you should disable the object by default."
