### ISSUE TITLE
USER ISSUE: Players crash when selling at my Store

### ISSUE THREAD

**Issue by bnema** [StrangeLoopGames/EcoIssues#23584]
\
**User Id: (slg225265)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
 I just moved the store and renamed it.

Idk how to reproduce this bug, but on another server someone had this bug on his store, and now its on mine (and on another server).

**Expected behavior:**
At the moment when player clic "complete trade" the deal should be set

**Actual behavior:**
The player crash with error "null reference"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by bnema** [comment]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/5212137/204148404-457d9d2a-21c1-44ea-b675-c776a8015c3f.png">

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23585, fixed in 9.7.3.
