### ISSUE TITLE
USER ISSUE: [9.7.2] Store reverts to "barter" on logout

### ISSUE THREAD

**Issue by coilysiren** [StrangeLoopGames/EcoIssues#23595]
## **User Id:**

slg220419

## **Version:**

0.9.7.2

## **Steps to Reproduce:**

1. setup a shared title for 2 people
2. setup a shared bank account for 2 people. DO NOT give the title access to the account
3. setup a house with a store in it
4. transfer the store's claim to the shared title
5. set store to use currency from the shared bank account
6. log off for 1 ~ 3 hours and leave the server running
7. store reverts from using currency to using "barter"

## **Expected behavior:** 

store retains usage of the shared bank account

## **Actual behavior:**

store reverts purchase method to "barter"

## **Workarounds:**

give the shared title access to the shared bank account

## **Do you have mods installed? Does the issue happen when no mods are installed?:**

Just DiscordLink, which I highly doubt is causing this

**Comment by coilysiren** [comment]
+1 case of someone mentioning this: https://discord.com/channels/254025510651297802/312991502697627658/1046686788548300851

**Comment by DiendaPhoenix** [comment]
+1, However we have it with the treasury bank account so I'm afraid we can't do the workaround, right?

**Comment by coilysiren** [comment]
Should be resolved by 9.7.4
