### ISSUE TITLE
USER ISSUE: Disappearing furniture

### ISSUE THREAD

**Issue by Berard93** [StrangeLoopGames/EcoIssues#23599]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
1. build room, rent out to others
2. Have renters place furniture
3. Remove claim

**Expected behavior:**
It should return the furniture to the renters

**Actual behavior:**
Instead it disappeared

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods in use

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Berard93** [comment]
The whole deed was removed in an attempt to fix my other bug with the house registering as unclassified and not giving bonus. All furniture disappeared, but I will check the void inventory next time I log on.

**Comment by D3nnis3n** [comment]
It will go to the void inventory of the person that has placed it, not the ones that owned the deed.

**Comment by Berard93** [comment]
> It will go to the void inventory of the person that has placed it, not the ones that owned the deed.

That makes sense. We will all check our void inventories. If it does not pop up then, I will make a new ticket and refer to this one. For now I'll assume this will fix it. Maybe refering to the void inventory in the tutorial or give a popup when a lease is broken would help noobs like us.

Thanks for the help!
