### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by RfBurn2015** [StrangeLoopGames/EcoIssues#23590]
Just installed the game.  Played about 30 mins.  Was just starting to make stuff in the work bench for the first few times, when the game had a pop-up error and locked up.  Then it closed the game, went back to desktop.  Nothing else happened.  Log Files attached.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10099454/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10099457/Player-prev.log)

**Comment by D3nnis3n** [comment]
This should be fixed in 9.7.3. If it reappears please attach a new log, I'll then reopen the issue.
