### ISSUE TITLE
USER ISSUE: Updatefehler

### ISSUE THREAD

**Issue by Roccy0815** [StrangeLoopGames/EcoIssues#23597]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
automatisches update auf Version 9.7.3 von Version 9.7.2 Server ist auf Version 9.7.3

**Expected behavior:**
Spiel und Verbindung funktioniert.

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no
seit 2 Monaten hat noch nicht ein Update zur erfolgreichen spielbaren Fortführung eines Serverspiels geführt. Das frustriet. Zumal man nicht einmal frei das release mit welchem man spielen möchte wählen kann.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Dein Client ist, wie in der Fehlermeldung angegeben, noch auf 9.7.2 und wurde daher noch nicht aktualisiert. Ggf. Steam neustarten wenn das Update nicht gleich kommt. Auch die freie Wahl der Version ist mittels der Betas in Steam und des Archivs auf unserer Webseite problemlos möglich.
