### ISSUE TITLE
USER ISSUE: Connection Failed - Auth Servers Down?

### ISSUE THREAD

**Issue by hiimk3v** [StrangeLoopGames/EcoIssues#23594]
\
**User Id: (slg157234)**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
Pressed continue on the main menu to join my last joined server.

**Expected behavior:**
Joined the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Login info could not be verified. Our auth servers may be down.

<size=60.00%>Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, I have mods installed. The specific server would not let me join without mods. Other servers will let me join, so it is this specific server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
There is no authserver downtime observed. This issue appears whenever you cannot access our authentication servers, which includes routing problems, any security software or other problems on the route. Reach out to support@strangeloopgames.com if the issue persists.
