### ISSUE TITLE
Double skill benefits listed in plant tooltips

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2360]

**Comment by Arend90** [comment]
learning and unlearning skills that gives you tools makes you keep the tools dont know if this the right place

**Comment by MarjieAVolk** [comment]
That should be its own bug

**Comment by MarjieAVolk** [comment]
Okay... not seeing this now.  And don't see any way in which it could happen >>

**Comment by MarjieAVolk** [comment]
Well can't repro anymore, gonna close for now
