### ISSUE TITLE
USER ISSUE: Account disabled ?

### ISSUE THREAD

**Issue by Nabusius** [StrangeLoopGames/EcoIssues#23602]
\
**User Id: ()**
**Version:** 0.9.7.2 beta release-381

**Steps to Reproduce:**
I try to connect and my account is disabled ... Why ?

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Informations de connexion invalides.

<size=60.00%>Votre compte a été désactivé.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
See support mail.
