### ISSUE TITLE
USER ISSUE: House not registering

### ISSUE THREAD

**Issue by Berard93** [StrangeLoopGames/EcoIssues#23600]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
1. Build house, claim area
2. Place furniture

**Expected behavior:**
Registered the room as a functional room

**Actual behavior:**
Instead it shows as "uncategorized". We see no early game option to specialize the room, so we appear to be soft locked for 24 hours or until cheats are used

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You need to place furniture of exactly one room type without having any industrial furniture in the room. What did you put there?

**Comment by Berard93** [comment]
A table, chair and statue. I'm guessing that that is support furniture. But how does one make a general room? On our server we have a campfire cook, logger, miner and mason. From what I could see we need the mason to reach lvl 5 before we can make any room with designation with a fireplace? Is that correct or did I miss something? Seems like quite the softlock when your server is smaller.

**Comment by IcedForge** [comment]
Hi!
I will look into adjusting the fireplace skill level requirement but you can look in the housing reference in ecopedia to see all furniture associated rooms (as each page for the room types contains each piece)

The general professions that have housing type specifics early on is
Carpentry, Hunting, Farming, Tailoring, Masonry.

**Comment by Berard93** [comment]
Thank you for your help. I will investigate all early unlockable items, but unfortunately only masonry is a profession we currently have and designating a room type requries level 5. Once reached we can spam out a lot of furniture, so it should speed up then.

We'll see the fastest route. But for now I know it is not a bug, but at most a balancing issue.
