### ISSUE TITLE
lokaler server absturz

### ISSUE THREAD

**Issue by yannicx17** [StrangeLoopGames/EcoIssues#23604]
mein lokaler server stürtzt ab 
siehe log files
[log_221202114758.log](https://github.com/StrangeLoopGames/EcoIssues/files/10140442/log_221202114758.log)

**Comment by D3nnis3n** [comment]
Korrupte Datenbank, einfachste Lösung:
/Steam/steamapps/common/Eco/Eco_Data/Server/Storage und dort die .db Datei des Savegames löschen.
Das entfernt allerdings auch alle Statistiken, die für Gesetze verwendet werden, die aber normal lokal nicht verwendet werden.

Ist allerdings kein Bug, daher schließe ich den Report - das wäre eher etwas für support@strangeloopgames.com.
