### ISSUE TITLE
Bad performance since 9-7 and testserver snapshots

### ISSUE THREAD

**Issue by TrasHC** [StrangeLoopGames/EcoIssues#23615]
Hello, since 9-7 in all iterations the game runs very sluggish for me. With 9-6 I had the degenerating performance most players experience, but a least on a fresh start it performed way better than now with 9-7. The FPS jump between 20-70, but the game feels very sluggish all the time. I took some snapshots on the testserver to hopefully help you guys figure out what's causing it. 

First two snapshots are F6 snapshots the third one is a savetransformstats. If it helps I could also send you a 9-6 snapshot for comparison.
Also I noticed some of the trees seem to have messed up LoD, but I bet that's known. (see second screenshot)

Edit: I also played around with the disableobjects command, but to my supprise that didn't really seem to have an effect even when disabling the trees in that dense jungle.

[EcoProfilingData-2022-08-07T19-53-10.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10179405/EcoProfilingData-2022-08-07T19-53-10.zip)
[EcoProfilingData-2022-12-07T19-57-00.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10179410/EcoProfilingData-2022-12-07T19-57-00.zip)
[EcoProfilingData-2022-12-07T19-58-07.zip](https://github.com/StrangeLoopGames/EcoIssues/files/10179412/EcoProfilingData-2022-12-07T19-58-07.zip)
![TransformsScreen](https://user-images.githubusercontent.com/18727081/206278239-0ee93aa9-aed7-4675-b9ca-7d3c490cb8c1.jpg)
![Tree LoD](https://user-images.githubusercontent.com/18727081/206278345-88de9643-b77b-4323-9a84-58c770bf8c2a.jpg)

**Comment by TrasHC** [comment]
Logged in on the new testserver WhiteTiger and it felt a lot smoother! If you want a snapshot from there anyway, let me know.

**Comment by mirasrael** [comment]
> Logged in on the new testserver WhiteTiger and it felt a lot smoother! If you want a snapshot from there anyway, let me know.

Hi. Thanks for feedback. Glad to know you have the problem fixed with last update! No, I don't need other snapshot atm. I close the issue. If you will experience same problem feel free to reopen or open new issue. Thanks for help with troubleshooting!
