### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by TyGamess** [StrangeLoopGames/EcoIssues#23618]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.3 beta release-391

**Steps to Reproduce:**
stand near a wall and let wild life push you

**Expected behavior:**
animal pushed away from player

**Actual behavior:**
player is forcfully pushed into the wall, sometimes rendering them stuck 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.7.5.
