### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by dictor93** [StrangeLoopGames/EcoIssues#23625]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.4 beta staging-2522

**Steps to Reproduce:**
Just install the required dev version 0.9.7.4 and try to connect to the White tiger-#34 Official ECO server

**Expected behavior:**
Successfully enter the game

**Actual behavior:**
Error message:
```
<size=150%>Connection Error</size>

Version mismatched.
```

Seems to me - required a 2521 commit, but steam just today at 7:52AM UTC installed updates with 2522 commit changes

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Seems - the log file does not generate for the current session, just existing ones for previous entries

**Comment by D3nnis3n** [comment]
You need to use playtest, not staging branch :)
