### ISSUE TITLE
USER ISSUE: Crash after eating food

### ISSUE THREAD

**Issue by IazLur** [StrangeLoopGames/EcoIssues#23623]
All is in the title

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10211338/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10211339/Player-prev.log)

**Comment by D3nnis3n** [comment]
Should be fixed in 2525 staging, report if not.
