### ISSUE TITLE
USER ISSUE: Need ability to search and sort crafting recipes in crafting windows

### ISSUE THREAD

**Issue by CiberX15** [StrangeLoopGames/EcoIssues#23631]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.4 beta release-404

**Steps to Reproduce:**
1. Open crafting win
2. Observe there are like fifty items in alphabetical so basically random order based on their function

**Expected behavior:**
It would be nice if crafting recipes were sorted based on function. This is particularly noticeable in the research table where you have books and papers you need to craft the books all jumbled together. And optimally it would be nice if the player could click the bar at the top to change the sorting filter. Additionally it would save a significant amount of tedium if users could search the crafting window for the recipes they are looking for, similar to how the storage item search already works.

**Actual behavior:**
Crafting win is not sorted and is not searchable leading to great tedium.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merging with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1572
