### ISSUE TITLE
Unable to load singleplayer local world

### ISSUE THREAD

**Issue by Ejevff** [StrangeLoopGames/EcoIssues#23639]
I'm able to join a public server no issue but singleplayer login attempt results in: "Failed to connect to the local server. It may be because of a server crash. You can check the server logs in [...]steamapps/common/Eco/Eco_Data\Server\Logs for more details."

Most recent log: 
[log_221210023609.log](https://github.com/StrangeLoopGames/EcoIssues/files/10300145/log_221210023609.log)

**Comment by D3nnis3n** [comment]
Hello Ejevff,
the logfile is from 9.7.3 and does not contain any relevant errors.

Can you please go to /Steam/steamapps/common/Eco/Data/Server, execute the EcoServer.exe manually and see if that boots? If not, please attach the newest log after that.

**Comment by Ejevff** [comment]
Trying to execute the EcoServer.exe in that way only brings up what looks like a command prompt for a millisecond and then closes. No new log is created.

**Comment by D3nnis3n** [comment]
Please save /Steam/steamapps/common/Eco/Data/Server/Storage and Configs directories, uninstall the game, delete the whole /Steam/steamapps/common/Eco folder and the AppData/LocalLow/Strange Loop Games folder and do a fresh install of Eco. Also make sure you got the latest Visual C++ Redistributables and are using Windows 10 or newer, it seems you miss some basic prerequisites to start the server.
