### ISSUE TITLE
USER ISSUE: BUG

### ISSUE THREAD

**Issue by ProductionEXP** [StrangeLoopGames/EcoIssues#23648]
\
**User Id: (slg216391)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
/give wood sign
save and exit server
crash

**Expected behavior:**
run

**Actual behavior:**
crash

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by RemonRamy** [comment]
Hello @ProductionEXP,

Apologies and thank you for your report. We'd like to get this fixed as soon as possible, can you please [share your client and server logs](https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world) with us if possible?

Looking forward to hearing back from you.

**Comment by RemonRamy** [comment]
Hello again @ProductionEXP,

We've managed to reproduce the issue and are working on getting this fixed soon. Thank you for your report. There's no need to share your logs.

Internal reference: ECO-26189

**Comment by ProductionEXP** [comment]
Also we have found that if you type on the sign and then save it crashes your game

**Comment by D3nnis3n** [comment]
The sign you spawned is a unavailable item that cannot be gotten via normal means, you are not supposed to have it or use it. Until we fixed the issue, please don't spawn / use or do anything with it.

**Comment by ProductionEXP** [comment]
Will do

**Comment by RemonRamy** [comment]
Fixed in 9.7.7. Thank you for your report.

Any previously spawned invalid items or objects (Such as the sign you spawned) will be replaced, and any broken save files you had will be automatically fixed.

Cheers!
