### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by XIII-th-coder** [StrangeLoopGames/EcoIssues#23640]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Неверная информация авторизации.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please make sure there is no security software, firewall or ISP (especially from russia there is multiple ISPs known that block Cloudflare) blocking the connection to the auth server and if necessary, use a VPN.
