### ISSUE TITLE
Constant Game Crashes

### ISSUE THREAD

**Issue by chikady** [StrangeLoopGames/EcoIssues#23649]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/10326725/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10326726/Player-prev.log)

**Comment by D3nnis3n** [comment]
Your GPU is below our minimum requirements, which is also causing this issue. There unfortunately is no other solution than upgrading the hardware in this case.
