### ISSUE TITLE
USER ISSUE: Fish stew has the wrong tooltip description and the wrong resulting product

### ISSUE THREAD

**Issue by halloweenharry** [StrangeLoopGames/EcoIssues#23645]
![Clipboard01](https://user-images.githubusercontent.com/121639625/210005920-46eca33b-034c-428d-863d-824ee528076c.jpg)

As seen on the picture, the fish stew has the wrong icon, the wrong tooltip, but uses the correct ingredients.

I wanted to cook some fish stew and the result was meaty stew. But the ingredients of fish stew have been consumed.

No mods installed - Vanilla Eco 0.9.7.6. beta release 420

nickname: halloweenharry

**Comment by TwixterZ** [comment]
hi @halloweenharry, this is not a bug, but rather a different recipe of making a meaty stew that instead of using meat, uses fishes. 

As per tooltip, showing "Crafted at" part, there are 2 separate recipe for it.

**Comment by halloweenharry** [comment]
Thank you! I never knew this :D

**Comment by TwixterZ** [comment]
Happy to help!
