### ISSUE TITLE
USER ISSUE: Keeped geting kicked for cheating when i am not.

### ISSUE THREAD

**Issue by Deniablesole** [StrangeLoopGames/EcoIssues#23642]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
i guess I start lagging and it kicks me for cheating.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This feature is experimental and disabled by default, you can turn it off in the meanwhile in Users.eco:   "MovementHackDetection": false,
