### ISSUE TITLE
9.7.6 /land remove is reversed with the blocks it removes

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#23655]
the /land remove command is reversed, if do /remove IronOreBlock it should only remove IronOreBlock but its removing everything BUT IronOreBlock

![image](https://user-images.githubusercontent.com/61889138/210272514-f723d648-2b59-429b-bfa7-afad2d428ad9.png)

**Comment by Daniel-Magulado** [comment]
Hi @MishkaFur 
Thank you for submitting this bug report.
I can confirm that the command does the opposite of what it's supposed to do.
I created an internal report so our development team can look further into it.

Reference No: ECO-26235

**Comment by Daniel-Magulado** [comment]
Update, this should already be fixed.
