### ISSUE TITLE
USER ISSUE: Duplicate player model and actions

### ISSUE THREAD

**Issue by underclockd** [StrangeLoopGames/EcoIssues#23657]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
Upon joining the server initially, there was no unexpected behavior. However, when reconnecting about 5-10 minutes later, the duplicate model appeared.

**Expected behavior:**
The game should show a single player model and only attempt to perform player actions once.

**Actual behavior:**

The game duplicates all actions my player character performs, including but not limited to: firing two arrows at a time, giving the "cannot dig while holding dirt" warning despite not initially holding anything, and giving the "no more room in inventory" warning when grabbing from a stockpile with empty hands. Additionally, when in thrid-person, there are two player models displayed (which is particularly noticeable when pushing a cart or other vehicle, as only one model actually has the cart animation applied).

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Logs:**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10339016/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10339017/Player-prev.log)

Additionally, I believe this is the latest server log:
[log_230101050107.log](https://github.com/StrangeLoopGames/EcoIssues/files/10339156/log_230101050107.log)

**Comment by underclockd** [comment]
I've seen issues like this with Unity before—if you guys are using the Netcode library, this behavior typically happens when both the server and client spawn separate instances of the player prefab. Let me know if there's anything else you need to help isolate the issue!

**Comment by D3nnis3n** [comment]
We know about this issue, but have never been able to reproduce it, it also does seem to only happen to specific people while others doing the exact same things have no issues. We're still looking into it, but so far without luck.

**Comment by underclockd** [comment]
One additional detail—I started this particular world with the Host feature within the game, before copying the world files to the server. Is there any chance that when the client creates those files it causes an issue with the server and client running in the same instance?

I'm just speculating, maybe there's a common thread.

**Comment by D3nnis3n** [comment]
No, this also happens on normal dedicated servers that have never been on a client.

**Comment by ZachBora** [comment]
This problem is still happening in 9.7.8
Server was restarted, client just opened ECO and just logged to 1 server, press F5 I have a clone of myself not doing the actions that I am performing.

**Comment by ZachBora** [comment]
Also it might be related to the clone, when i right-click while in inventory it also sometimes right-click through the internet and makes me pickup from when's in front of me. E.g. it will remove coal from a bakery oven, or remove the first item from a chest.

**Comment by renatokuipers** [comment]
Soooo... a Year later....

I have this issue too on the latest version of Eco.
I played with a pal of mine on my own server and everything was fine.
then I had to restart the server for some maintenance (performed some backups and stuff) and started the server again...
When I joined the server again, I have a doppleganger model that is sometimes exactly in sync, but for example if I use a wheelbarrow, 1 model is using the wheelbarrow, while the other model shows the "running" animation without using the wheelbarrow...

I am breaking my mind on this, but can't seem to solve this issue....
What's the problem? Whats the solution?

Please fix this asap if possible.... pretty please :)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24772
