### ISSUE TITLE
Alpha 6.0 Stable Crashing Multiple Times on Creation on many servers 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2365]
Alpha 6.0 Stable Crashing Multiple Times on Creation

https://www.dropbox.com/s/7nvb3i8h7f57yv4/UK_Public_Server_Crash_Dump.7z?dl=0

https://www.dropbox.com/s/peg3e3cwfzt3yua/Pams%20Test%20Server%20Dump.zip?dl=0

**Comment by pamduncan** [comment]
Server still crashing https://www.dropbox.com/s/io481slt6k43ywb/Houston%2001Server.zip?dl=0

**Comment by metachronism** [comment]
fixed by marjie earlier
