### ISSUE TITLE
USER ISSUE: serveur local Lumynya

### ISSUE THREAD

**Issue by sebdu301** [StrangeLoopGames/EcoIssues#23650]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Informations de connexion invalides.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non aucun mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sebdu301** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10327522/Player-prev.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/10327523/Player.log.copy.txt)

**Comment by sebdu301** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10327524/Player.log)

**Comment by D3nnis3n** [comment]
This means that you are not able to reach our authentication server, typically an issue with antivirus or security software, can also be caused by VPN or ISP settings. This is hence not a bug, but rather a support issue for support@strangeloopgames.com, where you can reach out to.
