### ISSUE TITLE
USER ISSUE: Fix youre voting website!!!

### ISSUE THREAD

**Issue by DekiLaYT** [StrangeLoopGames/EcoIssues#23666]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
1.Try to create a constitution
2.Vote it
3.Vote Website doesnt work

**Expected behavior:**
The Website should function

**Actual behavior:**
The Website doesnt work.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No i dont have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you be more specific about the problem you have with the website, e.g. what does "does not function" mean?

**Comment by DekiLaYT** [comment]
The Website Times out

**Comment by D3nnis3n** [comment]
Sounds like the server owner did not correctly port-forward the web page, which is not a eco bug, but a configuration error. Closing here, feel free to reach out to support@strangeloopgames.com for any further help needed.
