### ISSUE TITLE
USER ISSUE: Cast Iron Stove Lighting Issue

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#23662]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.6 beta release-420

**Steps to Reproduce:**
Place a Cast Iron Stove in a room

**Expected behavior:**
It should look nice

**Actual behavior:**
It looks very dark

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![Screenshot of cast iron stove in a room that shows the lighting issue](https://user-images.githubusercontent.com/395810/211013526-d7666e29-8bb6-443f-85de-e0d398ce3cd4.png)

**Comment by TwixterZ** [comment]
Hi @Yogu thank you for reporting this back to us, this is currently intended, and in near future there will be a new model for cast iron stove, hence I will proceed to close this issue for now =)

**Comment by Yogu** [comment]
Just gotta say: the new model looks awesome!
