### ISSUE TITLE
Alpga.6 Wrong icons

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2367]
![image](https://user-images.githubusercontent.com/1900106/30962545-8707437e-a44a-11e7-87ad-01af65656636.png)

**Comment by MarjieAVolk** [comment]
@keegan-o Stuff like this, do you want me to leave open or not?  Because presumably you won't make a new icon just for this, so it doesn't belong on the art list.

**Comment by keegan-o** [comment]
This is a legit bug because the candlestick icon is obviously wrong. But I fixed it a while ago.
