### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by matthewschenk6** [StrangeLoopGames/EcoIssues#23672]
Version mismatch

\

**User Id: (Not logged user)**
**Version:** 0.9.7.7 beta release-431

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server you tried to connect to has likely not updated yet. You can either wait until it did that or temporarily revert your version to 9.7.6 in Steam by right clicking Eco -> Properties -> Betas and selecting the respective version of the server from the Betas dropdown.
