### ISSUE TITLE
USER ISSUE: Bug objekte

### ISSUE THREAD

**Issue by Mortenmanor** [StrangeLoopGames/EcoIssues#23686]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.6 beta release-235

**Steps to Reproduce:**
any time (10 day ago) 

**Expected behavior:**
MobileObjekte not avilebar over world and new spawn MobileObjekt  

**Actual behavior:**
can not Target, interact objet on caracter, object is passiv,  inventory avillible 

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You are using a severely outdated version of Eco, please update to version 9.7.7 and open a new issue if the problem persists.
