### ISSUE TITLE
USER ISSUE: Unable to connect to Giant Panda

### ISSUE THREAD

**Issue by Jocktor** [StrangeLoopGames/EcoIssues#23680]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.7 beta release-431

**Steps to Reproduce:**
Crash on giant panda
Be unable to connect	
get Failed to recieve views from server message

Can connect to any other offical or non offical server.

**Expected behavior:**
connect to giant panda
make nice things until lag takes you
crash
reconnect to giant panda
rinse repeat.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to receive views from the server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Only mod is nidtoolbox.unity3d

I did try connect on to the server after going on WT and it then just hangs on downloading mods. Removed (WTmods) mods and back to the same failed to connect error issue.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Jocktor** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/10482806/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10482807/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed
