### ISSUE TITLE
Alpha.6 trees growing on stockpile

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2368]
![image](https://user-images.githubusercontent.com/1900106/30962912-e32d4e04-a44b-11e7-8b83-597bf8e2b966.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2352

**Comment by Fank** [comment]
:man_facepalming:
