### ISSUE TITLE
USER ISSUE: Je ne peux pas me connecter

### ISSUE THREAD

**Issue by Nico-GS** [StrangeLoopGames/EcoIssues#23696]
\
**User Id: ()**
**Version:** 0.9.7.7 beta release-431

**Steps to Reproduce:**
Lors de la connexion à un serveur ça me dit que mon compte a été désactivé

**Expected behavior:**
Me connecté au serveur

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Informations de connexion invalides.

<size=60,00%>Votre compte a été désactivé.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non aucun

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Reach out to support@strangeloopgames.com with your SLG ID.
