### ISSUE TITLE
[CLIENT] 0.9.7.7 Sign icons for Square and Round Pots not working

### ISSUE THREAD

**Issue by Bonsai555** [StrangeLoopGames/EcoIssues#23690]
I was setting up a Pottery building and put icons on signs. While trying to put **Square Pot** or **Round Pot** icons on them, they do not show up. Others like Bricks or Small Sinks or others work fine.

I tried different versions of text:
<icon name='RoundPotItem'>
<icon name="RoundPotItem">
<ecoicon name='RoundPotItem'>
All of these did work for all the other signs i put icons on.

![grafik](https://user-images.githubusercontent.com/12842716/215458683-56a043b3-1ed0-4d24-ac8e-e841b14a1ec7.png)
![grafik](https://user-images.githubusercontent.com/12842716/215458757-096b7dba-f118-465f-99d1-9704daca3e4d.png)
![grafik](https://user-images.githubusercontent.com/12842716/215458793-9cb6065e-6a44-43a3-ae05-0a7a87d6b472.png)

**Comment by Bonsai555** [comment]
i did not try with the "space" in between the two words.

**Comment by TwixterZ** [comment]
Hi @Bonsai555, the issue here is the actual name for those pots are 
"PlanterPotRoundItem"
"PlanterPotSquareItem"
