### ISSUE TITLE
"Ghost Vehicles" blocking world block placements.

### ISSUE THREAD

**Issue by jwmc80** [StrangeLoopGames/EcoIssues#23693]
We are a heavily modded server but are we the only one who is experiencing "ghost" vehicles.

Basically, what happens is some stores will have multiple ghost vehicles in front of shops.
This blocks the placement of constructable block placements, I've found the way to fix it is to spawn water over the location in question and it will clear the ghost vehicle.

Once I get a picture of what it looks like I'll post it as an update

**Comment by TwixterZ** [comment]
Hi @jwmc80 thank you for reaching out, do you able to get the screenshot of this?

**Comment by jwmc80** [comment]
Yeah I will see what I can do for you
