### ISSUE TITLE
unplayable due to graphic errors

### ISSUE THREAD

**Issue by BennoHase** [StrangeLoopGames/EcoIssues#23694]
I have strange issues atm and the game is not playable therefor.
First: when I log into the game I have nearly all interactive items (like trees, stones, hammer, pickace, tent and so one) are white with gray, but not colored. I fixed that by relogging, but it happens every time when I log in.
Second: I used my pickace to get stones. Sometimes the stone behaves like it should. It breaks into 4 (or 3 with yellow) items and I can pick up them. But most of the time the stone breaks into the 3 or 4 parts, but still remains there. I can pick up the parts and I can pick the stone again, but it won't break anymore. It ist
Third: When I use my shovel and pick up some sand or dirt the sand or dirt isn't there anymore, but when I place it, it won't appear. I have an invisible sand or dirt block there. I can pick the next sand or dirt and try to lay it where the first is, but it isn't possible. I have to guess where no dirt or sand is and put it there. And the dirt or sand is still in the shovel after placing it.

**Comment by BennoHase** [comment]
Issues seems to be gone after the 4th or 5th relog to the world. Is it prossbily a problem with data loading ? I start my own server on the same machine.

**Comment by D3nnis3n** [comment]
Full client logfiles and screenshots please:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by BennoHase** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10664311/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10664312/Player-prev.log)

**Comment by D3nnis3n** [comment]
Seever Logs?

**Comment by BennoHase** [comment]
sorry, forgot them :-D 
[log_230203091835.log](https://github.com/StrangeLoopGames/EcoIssues/files/10672689/log_230203091835.log)

**Comment by BennoHase** [comment]
![grafik](https://user-images.githubusercontent.com/62522744/217183725-dcf7dfb2-0fbd-48f2-918a-9a336774bcb9.png)

other server logs needed ?

**Comment by BennoHase** [comment]
![grafik](https://user-images.githubusercontent.com/62522744/217184121-787ece7c-36b6-448e-a692-12c19de56d5d.png)

**Comment by BennoHase** [comment]
screenshot of the not working pick of a stone is useless because you see a stone before and after picking it.

**Comment by D3nnis3n** [comment]
You are playing on a in-development build (staging) instead of release. Can you please try to play on release and see if the same issue happens? Staging is in-development builds that naturally have issues.

**Comment by BennoHase** [comment]
no issues with 0.9.7.7
