### ISSUE TITLE
USER ISSUE: Server Down

### ISSUE THREAD

**Issue by CricketXO** [StrangeLoopGames/EcoIssues#23709]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.8 beta release-442

**Steps to Reproduce:**
Log into server.Doesn't Connect.Offers to file a bug.	

**Expected behavior:**
Server loads. Character appears in world where i left it with all my stuff. And my pet crab is still alive.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Choco ECO Server day 8

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
So you're trying to join Choco's streamer server and cannot? The message just states that you cannot connect to it from networking side, which is something the server would need to fix if you can join other servers. Is the server down completely? We'd probably need to get a view from the server admin, user reports are typically not very helpful here.

**Comment by D3nnis3n** [comment]
Closing due to outdated.
