### ISSUE TITLE
Random game crashes

### ISSUE THREAD

**Issue by Tmoney7777** [StrangeLoopGames/EcoIssues#23702]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10690267/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10690270/Player.log)

**Comment by D3nnis3n** [comment]
Your issue is caused by the VRAM running full. Please note that you're at the lowest end of our minimum requirements with just 4 GB of VRAM - for that to work you'll need to use very low graphics settings and make sure that you don't have any other consumers for VRAM running at the same time.
