### ISSUE TITLE
USER ISSUE: Bug

### ISSUE THREAD

**Issue by NARVELLE** [StrangeLoopGames/EcoIssues#23701]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.8 beta release-442

**Steps to Reproduce:**
J'essaie de lancer ma partie sur mon serveur héberger, en vain.

Le lancement reste bloqué sur " Chargement des objets 0% ".

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Annulé par l'utilisateur
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by NARVELLE** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/10689328/Player.log.copy.txt)

**Comment by NARVELLE** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10689335/Player-prev.log)

**Comment by D3nnis3n** [comment]
Your installation seems corrupted, try verifying your files.

If that doesn't help, do a full uninstall - save your savegame (Steam/steamapps/common/Eco/Eco_Data/Server/Storage) first, then uninstall Eco, delete the whole /Eco folder manually and then reinstall.

**Comment by NARVELLE** [comment]
> 

Merci de la réponse, ça a marché.
