### ISSUE TITLE
USER ISSUE: Can't move any vehicles

### ISSUE THREAD

**Issue by CipherNova** [StrangeLoopGames/EcoIssues#23700]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.7 beta release-431

**Steps to Reproduce:**
I enter any vehicle (Steam Truck, wooden cart, shop cart, etc.) 

**Expected behavior:**
It should drive around and move

**Actual behavior:**
It starts, i can turn the wheels on vehicles that have them but cannot drive.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by CipherNova** [comment]
Before anyone asks:
Yes i have relaunched the game
Yes we have restarted the server
Yes i have restarted my PC
Yes i have validated my files
Other people can drive my vehicles and i can't driver theirs
No one else is having the issue on our server that we know of

**Comment by D3nnis3n** [comment]
Do you have a controller connected? Try removing it.

**Comment by D3nnis3n** [comment]
Closed due to no further information provided, feel free to open a new issue with the requested details if the issue reoccurs.
