### ISSUE TITLE
USER ISSUE: Oil Refinery eates barels

### ISSUE THREAD

**Issue by Kevengg** [StrangeLoopGames/EcoIssues#23708]
\
**User Id: (slg208708)**
**Version:** 0.9.7.8 beta release-442

**Steps to Reproduce:**
que up more than one of recepies in the Oil Refinery, that returnes barrels

**Expected behavior:**
20 barels of petrolium in, 20 empty barels and product out

**Actual behavior:**
20 barels of petrolium in, less than 20 empty barels and expected product out

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10724335/Player.log)

**Comment by D3nnis3n** [comment]
This works as intended, 25% of barrels get lost as wear and tear.
