### ISSUE TITLE
USER ISSUE: Missing food items

### ISSUE THREAD

**Issue by Rewbles** [StrangeLoopGames/EcoIssues#23704]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.8 beta release-442

**Steps to Reproduce:**
Start cooking charred beans

**Expected behavior:**
Produced charred beans

**Actual behavior:**
beans go missing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce, needs information.

**Comment by D3nnis3n** [comment]
Closed due to no further information provided, feel free to open a new issue with the requested details if the issue reoccurs.
