### ISSUE TITLE
USER ISSUE: White Tiger Down

### ISSUE THREAD

**Issue by Rlbregant** [StrangeLoopGames/EcoIssues#23710]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.8 beta release-442

**Steps to Reproduce:**

**Expected behavior:**
Server shouldn't have died.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10739927/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10739928/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed
