### ISSUE TITLE
USER ISSUE: Ошибка при подключении к учетной записи

### ISSUE THREAD

**Issue by Tilk123** [StrangeLoopGames/EcoIssues#23729]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
1. Запуск игры от имени администратора.
2. Ввод логина и пароля.

**Expected behavior:**
Запуск игры

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Failed to login

Unable to complete SSL connection
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Чистый клиент

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a connection issue, with you not being able to connect to our auth or master servers.

This is known to happen for some russian ISPs that block Cloudflare. You can write to support@strangeloopgames.com for potential solutions like VPN, but it's not a bug.
