### ISSUE TITLE
USER ISSUE: I didn't cheat

### ISSUE THREAD

**Issue by RibCodes** [StrangeLoopGames/EcoIssues#23726]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
Walk with land claimer on i guess lol

**Expected behavior:**
It should have let me continue to walk

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This feature is experimental and disabled by default, you can turn it off in the meanwhile in Users.eco: "MovementHackDetection": false.
