### ISSUE TITLE
USER ISSUE: Legasy control is wrong

### ISSUE THREAD

**Issue by Noneforu** [StrangeLoopGames/EcoIssues#23734]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
Push a cart

**Expected behavior:**
Should behave like a truck pushing a trailor

**Actual behavior:**
changes controls to some sort of crappy 'driving' controls

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No but if there is a mod to fix thing PLEASE TELL ME This is Ruining the game for me!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Works as intended.
