### ISSUE TITLE
USER ISSUE: pilha com problemas

### ISSUE THREAD

**Issue by DanielMarega** [StrangeLoopGames/EcoIssues#23749]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
A pilha só pega uma terra, porém pra madeira e pedra pega uma quantidade maior.

**Expected behavior:**
uma pilha maior para pedra.

**Actual behavior:**
somente pega uma pedra por vez

**Do you have mods installed? Does the issue happen when no mods are installed?:**
não, sem mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by DanielMarega** [comment]
Isto acontece no mapa criado no meu micro, não em outros servidores.

**Comment by DanielMarega** [comment]
I'm from  Brazil.

**Comment by D3nnis3n** [comment]
This works as intended, hence closing.
