### ISSUE TITLE
USER ISSUE: Soil Sampler yield display is wrong (1, 2, 3, 30)

### ISSUE THREAD

**Issue by cnschu** [StrangeLoopGames/EcoIssues#23743]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
1. Plant a Tree or Cactus
2. let it grow a few days
3. sample the Tree/Cactus with soil sampler
4. at 66% grow the sampler shows a yield of "3"
5. Harvest the Tree

**Expected behavior:**
The Soil Sampleer should show the yield that is actually expected by harvesting the Tree / Cactus.

**Actual behavior:**
You get 20 wood from the tree or cactus, the sampler shows only a yield of 3. The value in the sampling display is correct only at 100%

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.7.11.
