### ISSUE TITLE
Alpha.6 Missing following objects

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2374]
From Player.log:
```
Missing following objects: AirPumpObject, AtmosphereRegulatorObject, AtmosphereTesterObject, ButtonObject, CastIronStoveObject, CompostPileObject, CurrencyExchangeObject, FisheryObject, GasGeneratorObject, LogicGateObject, MeteorExplodes, MeteorExplodesInAtmo, SteamGeneratorObject, SwitchObject
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
- [ ] AirPumpObject
- [ ] AtmosphereRegulatorObject
- [ ] AtmosphereTesterObject
- [ ] ButtonObject
- [ ] CastIronStoveObject
- [ ] CompostPileObject
- [ ] CurrencyExchangeObject
- [ ] FisheryObject
- [ ] GasGeneratorObject
- [ ] LogicGateObject
- [ ] MeteorExplodes
- [ ] MeteorExplodesInAtmo
- [ ] SteamGeneratorObject
- [ ] SwitchObject

**Comment by MarjieAVolk** [comment]
Known
