### ISSUE TITLE
USER ISSUE: Displayed amout of Credits in Store after BuyAction

### ISSUE THREAD

**Issue by thewolfofeco** [StrangeLoopGames/EcoIssues#23744]
**User Id:** Any User
**Version:** 0.9.7.10 beta release-474 (did not happen with 0.9.7.9)

**Steps to Reproduce:**
- Player A provides a sell order in a store using Player A Credit as currency.
- Player B buys any item in Player A store

**Expected behavior:**
Player B sees the correct amount of Player A credits after the buy action.

**Actual behavior:**
Player B sees the amount of Player A Credits before the buy action, as if he didn't buy. Buying something else again shows the amount before this very buy action, after the former one.

As one player reports, this prevents other buy actions, as the unrefreshed value seems to be used to check if the trade is possible.

**Do you have mods installed? Does the issue happen when no mods are installed?**
We reproduced this error on three servers, two of them unmodded.

**Comment by TwixterZ** [comment]
@thewolfofeco thank you for reporting this to us, I have highlighted this issue to our developer for a possible fix. 

Our reference : 27825

**Comment by D3nnis3n** [comment]
Fixed in 9.7.11.
