### ISSUE TITLE
USER ISSUE: No text on main menu to select

### ISSUE THREAD

**Issue by calinus** [StrangeLoopGames/EcoIssues#23747]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
1. Run Eco
2. See main menu animated background
3. Wish that you could play the game... at all.

**Expected behavior:**
Displayed menu options such as "Play Game", etc.

**Actual behavior:**
Displayed ONLY the animated background and played the menu sounds

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NONE

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by calinus** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11175556/Player.log)

**Comment by D3nnis3n** [comment]
This happens when network connection to authentication servers is blocked, sometimes restarting Steam helps, otherwise will need to check antivirus and firewall, especially antivirus after an update. Not a bug, though. Feel free to reach out to support@strangeloopgames.com for further info :)
