### ISSUE TITLE
Unlearning a skill doesn't handle tools given well

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2375]
"learning and unlearning skills that gives you tools makes you keep the tools dont know if this the right place"

**Comment by MarjieAVolk** [comment]
I don't really see a good solution for this actually.  The only thing I can think is to not allow refunds for a skill that gives you items.

**Comment by KyeEco** [comment]
why would someone unlearn basic skills as such as these? maybe take away the refund ability for those particular skills, im sure people wont mind.
