### ISSUE TITLE
USER ISSUE: unable to complete ssl connection

### ISSUE THREAD

**Issue by Ivan178500** [StrangeLoopGames/EcoIssues#23769]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
Не появляется меню при запуске игры

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Unable to complete SSL connection
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
нет и да

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a connection issue, with you not being able to connect to our auth or master servers.

This is known to happen for some russian ISPs that block Cloudflare. You can write to [support@strangeloopgames.com](mailto:support@strangeloopgames.com) for potential solutions like VPN, but it's not a bug.
