### ISSUE TITLE
USER ISSUE: Waste Filter cannot output processed sewage into Blast Furnace

### ISSUE THREAD

**Issue by effleurager** [StrangeLoopGames/EcoIssues#23763]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**
1. Connect Blast Furnace to water
2. Connect Blast Furnace sewage output to Waste Filter input
3. Connect Waste Filter output to water input concurrently

**Expected behavior:**
Blast Furnace should continue to run

**Actual behavior:**
Blast Furnace stops, claiming sewage is flowing into input

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11187751/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11187750/Player.log)

**Comment by D3nnis3n** [comment]
This works as intended, you are not supposed to make such loops, but need to use fresh water.

**Comment by effleurager** [comment]
Surely this requires reclassification/documentation that this isn't actually water then?

**Comment by D3nnis3n** [comment]
The Blast Furnace does note the water isn't usable, but the output is not sewage, nor clean water.
This limitation is for balance reasons and not worth implementing a whole new liquid type which would not be efficient.
I'll suggest changing the error message on the Blast Furnace to make clear that the output of Sewage Filters cannot be used, which seems like a working compromise.
