### ISSUE TITLE
USER ISSUE: Blocks have suddenly started to not let things be placed on them V9.7.10

### ISSUE THREAD

**Issue by Zedekial** [StrangeLoopGames/EcoIssues#23765]
As of the latest version I cannot place blocks or more specifically dirt in certain spaces, it gives me an error and won't let it be placed

It is not too high or low. Seems about level with all other ground

**Comment by D3nnis3n** [comment]
What error does it give?

**Comment by Zedekial** [comment]
![image](https://user-images.githubusercontent.com/36537324/230924872-f38b44e0-bcc5-47ef-a128-0fe0a5bab895.png)

Simply this. Nothing verbose

**Comment by D3nnis3n** [comment]
Can you place blocks there after the server restart?

**Comment by D3nnis3n** [comment]
Can you give me a coordinate for such a space?

**Comment by Zedekial** [comment]
![image](https://user-images.githubusercontent.com/36537324/230936442-b4e55996-2b2e-4d98-a1ff-1582df4a9a29.png)
Ok so this was somehow related to the debris bug. When I logged back on it suddenly showed what must have been invisible debris which was blocking the spots I was trying to place dirt on. So it is fixed now.

Issue seems to be with debris. Perhaps the showing of the debris is not in sync with the actual game side debris locations?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23764
