### ISSUE TITLE
USER ISSUE: not able to ride powered cart or pick it up with hammer

### ISSUE THREAD

**Issue by adrianhzx** [StrangeLoopGames/EcoIssues#23778]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.11 beta release-478

**Steps to Reproduce:**
1. spawn a powered cart
2. put full storage in the powered cart
3. move the powered cart through a ramp (dirt ramp)
4. get out of the powered cart

**Expected behavior:**
it should have the options to ride or open the storage.

**Actual behavior:**
no option to ride and open the storage in the powered cart. futhermore, the cart can be easily flipped by pushing.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by adrianhzx** [comment]
[https://youtu.be/qC9xk_8kaUM]

**Comment by D3nnis3n** [comment]
Fixed in 9.7.12.
