### ISSUE TITLE
USER ISSUE: <size=60,00%>Your account has been disabled.

### ISSUE THREAD

**Issue by Talindor2** [StrangeLoopGames/EcoIssues#23777]
\
**User Id: ()**
**Version:** 0.9.7.11 beta release-478

**Steps to Reproduce:**
Habe versucht mich auf einen Server einzuloggen.

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Invalid login info.

<size=60,00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein, keine Mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com with your SLG ID.
