### ISSUE TITLE
USER ISSUE: Carts, Chopped Logs, and Carcasses not Interactable

### ISSUE THREAD

**Issue by AmyntasSynth** [StrangeLoopGames/EcoIssues#23779]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.11 beta release-478

**Steps to Reproduce:**
Perform mining and wood chopping for an extended while.
Randomly, rubble pieces may disappear, or fly around, causing players to not pick them up. (Sometimes that stuff just falls through the ground)
After a while enough of them amass in the world, seemingly triggering the bug at some point. (It took us not even two days)

I managed to fix the issue by entering fly-mode, and spamming the /land clearrubble command everywhere - eventually the issue was fixed.

**Expected behavior:**
Objects should remain interactable, regardless of rubble amount in the world.
Alternatively, rubble that is out of a player's reach should get removed properly... or in general, after a certain time.

**Actual behavior:**
Certain rubble-like objects become un-interactable - such as carts, animal carcasses, and chopped logs.
When logging back in, these objects will be briefly interactable for a few seconds. (Perhaps once the game loads enough of these objects in, the bug triggers?)

My server logs also show a possibly related error message (?):
 SmallWoodCartObject [Amynta's Small Wood Cart] an interaction distance check failed (occupancy based). Fallback to default check.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11235883/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11235884/Player.log)
[log_230414092346.log](https://github.com/StrangeLoopGames/EcoIssues/files/11235902/log_230414092346.log)

**Comment by D3nnis3n** [comment]
Fixed in 9.7.12.
