### ISSUE TITLE
Can't open world from old version (server crash)

### ISSUE THREAD

**Issue by Caerum5** [StrangeLoopGames/EcoIssues#23776]
I have a world saved from version v9.4.1 and I wanted to play it again in v9.7.11, but it crashed.

Crash Log:
[log_230414113217.log](https://github.com/StrangeLoopGames/EcoIssues/files/11231578/log_230414113217.log)
Migration Log:
[migration_2023-04-14.log](https://github.com/StrangeLoopGames/EcoIssues/files/11231581/migration_2023-04-14.log)

**Comment by D3nnis3n** [comment]
Hello,
the savegame you are trying to migrate is unfortunately corrupted and hence cannot be migrated.

You could look into the backups folder in your storage folder and try to see if any of these work and can be migrated, by moving them to the main folder and loading them.
