### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Nevsoriginal** [StrangeLoopGames/EcoIssues#23771]
\
**User Id: (slg127716)**
**Version:** 0.9.7.10 beta release-474

**Steps to Reproduce:**

**Expected behavior:**
Holzspan/Äste sollen auf den Boden fallen und mit der Axst ab zu bauen sein

**Actual behavior:**
bleiben in der luft hängen und man kann sie nicht abbauen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11216000/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11216001/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23764
