### ISSUE TITLE
USER ISSUE: mismatched when its not mismatched

### ISSUE THREAD

**Issue by ellie8288** [StrangeLoopGames/EcoIssues#23782]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.11 beta release-480

**Steps to Reproduce:**
its saying the server version is 0.9.7.11 and ive checked my steam and thats what my current eco game is, i tried going back to an earlier version and then going back to 9.7.11 but its still saying mismatched

**Expected behavior:**
it should of worked fine

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Version is actually mismatched, as we had to update the build of an existing version to prevent a major issue to spread to further servers before we could react correctly with a new Update, so this unfortunately worked as "intended". There is 9.7.11-478 and 9.7.11-480. Issue will resolve via update of server or next update in a bit.
