### ISSUE TITLE
[10 - 2595] Female Avatar version selected on join

### ISSUE THREAD

**Issue by Xavia1991** [StrangeLoopGames/EcoIssues#23789]
0.10.0.0 beta staging-2595
I created a male avatar, did the photo etc and then joined a server.
When I spawned my character was female an looking nothing like what I created.
Restarting the game and going into avatar creation again showed me the female avatar.
Switching gender to mal showed my male char as I created it.
Problem remained, after join it was the female avatar again.

**Comment by Xavia1991** [comment]
Workaround:
Open Edit menu in Inventory, this will load the character corrctly

**Comment by D3nnis3n** [comment]
Thank you, please note that we currently do not yet accept bugs for Update 10.
Please report any issues you have until start of White Tiger playtest in discord channel #bug-testing.
As of our announcement, Update 10 is a preview in very early stage, so all these issues are known.
