### ISSUE TITLE
USER ISSUE: Odd Physics with Mining. 

### ISSUE THREAD

**Issue by NewToThis** [StrangeLoopGames/EcoIssues#23781]
Version: 0.9.7.11
User ID: slg222689

I myself and many others on the server I am playing on are dealing with blocks disappearing or exploding when mining. Note we are also experiencing the Tree Physics issue and the Vehicle hit box issue so these issues maybe related to those. The server is almost vanilla minus a carry size mod that allows double carry in hands and vehicles but maintains normal stack sizes in stockpiles. 

I thought it was just on my server but I have jumped to a few others and loaded up a local world and find that I am running into the same issue. 

Replicate issue: have mining lvl 6-7 with Lucky Break (does not seem to effect those with sweeping hands) 
Mine Granite (90% occurrence) 
Mine Iron Ore (50% occurence) 
all other rock seems to be maybe 10% occurence. 
(gold and copper node unknown at this time)

When mining a rock or ore node there is a chance the node will provide you with 0-4 blocks of the corresponding rock/ore type.
Issue happens regardless of mining from the side or top of the block. 
Issue seems to occur less when strip mining down and occur more when mining horizontal tunnels. 

Most reliable way to replicate issue: 

Mine a 2 tall 3 wide tunnel in granite. Watch rock explode across the tunnel and blocks disappear. expected 32 rocks blocks. 

Cases:
![Screenshot 2023-04-14 195705](https://user-images.githubusercontent.com/5943442/232172104-8414dc52-d07a-4e12-80b4-0dc70c77bf3d.jpg)
CASE 2: Mined order (1,2,3,4,5,6)
1. 1 block flew down the hallway roughly 20 blocks away. Only received 15 blocks. 
2. 1 block flew down the hallway roughly 24 blocks away. only received 11 blocks.
3. no flying rocks. Only received 14 blocks

CASE 2: Mined order (4,5,6,1,2,3) 
1. no flying rocks. Only received 13 blocks. 
2. block fly 7 blocks away. Only 14 block
3. no flying rocks. Only received 14 blocks

Maybe 1 - 5 rocks did show up when returning to the mine or when checking the ground above.

**Comment by D3nnis3n** [comment]
Fixed in 9.7.12.
