### ISSUE TITLE
If a law prevents you from creating a law, it doesn't tell you why you can't

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2378]
Can't make a law because a law prevents me from doing so.

I can open up the web page and fill out the form, I'm prevented from ever posting it. Nowhere does it say why (as opposed to not filling out the form completely, etc)

**Comment by MarjieAVolk** [comment]
I believe it should say why in a red bar at the top of the web page >> Thought that was working

**Comment by Nanders** [comment]
I see a little blip of a red bar, but no text inside

**Comment by MarjieAVolk** [comment]
Real quick - does the behavior change if you force refresh the page?

**Comment by Nanders** [comment]
I don't know, can't reproduce because it's legal for me to make laws now

**Comment by MarjieAVolk** [comment]
Yeah this is working fine for me

**Comment by MarjieAVolk** [comment]
I'm going to guess this is a page refresh thing, which is annoying but I don't think we can do anything about that?

**Comment by SeanAtr0n** [comment]
refresh issues are usually for cached images... not code like this, could probably do something about it

**Comment by MarjieAVolk** [comment]
Should I assign it to the web team?

**Comment by Nanders** [comment]
Could this be designed better too?

I feel like the law should prevent me for opening the page to make the law, not let me go through the whole process to make one then preventing me at the last step.

**Comment by MarjieAVolk** [comment]
I believe it stops you if you try to navigate to the add law page while already on the web site, but when clicking the add law button to bring you there it doesn't work; and that is probably the more common use case.

**Comment by rainfarmer** [comment]
OK, @syuzan-yeranosyan can the law page so it first checks if the user can make a law or not. 
If not, then display error.

**Comment by rainfarmer** [comment]
fixed
