### ISSUE TITLE
USER ISSUE: Cant pick up Wood logs and dead animals

### ISSUE THREAD

**Issue by anzysart** [StrangeLoopGames/EcoIssues#23780]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.11 beta release-478

**Steps to Reproduce:**
Can't tell how this happened but i cut some trees and after the 6th i can't pick them up anymore also not clear the stomp. Effects the whole Game also animals and we can't open and close doors on the server anymore. Tried loading backup, but error occured again after some playtime. Also we can't pickup doors with hammer too.

**Expected behavior:**
We should be able to pickup cut wood and open and close door and pick up with hammer and pickup animals.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No just vanilla game on GPortal Server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 9.7.12.
