### ISSUE TITLE
Increase money through bug in voting system

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#23785]
Hello,

we have found a bug from the game on our server: When you vote, you get an amount X. If someone now clicks several times on the button "Yes" or "No", this law is triggered each time so that you can quickly click money. The law says that it gets per vote an amount X and not per click infinitely much and often. In-game you can only cast one vote but every click on the button counts as a vote. 

Please take a look at this. So we have to remove the law to animate voting for now until further notice. 

Greetings

**Comment by D3nnis3n** [comment]
This works as intended, each change of vote is a new vote, your law needs to consider that by limiting the output to a number of votes in the last time X. There is only one thing to clarify: Do people actually switch between votes to achieve it or click the same again, the latter shouldn't be possible, but given you can switch between votes intendedly wouldn't be a solution to your problem when fixed.

**Comment by Enel300** [comment]
Good morning Dennis, I understand. If you take real life as a reference, then you can't change your vote after you've cast it. The ballot disappears in the box and I can't go back and say "oh, get my ballot out, I've changed my mind". This shouldn't be possible with Eco either. Players have found out about this bug and saved themselves a lot of money by clicking "Yes" several times. There is enough time to think about it so I see no need why you should be able to change your vote. I'll see if I can limit it by law. Would be nice if you deliver/improve something there per fix.

**Comment by D3nnis3n** [comment]
That is actually not correct, there is several countries in which changing votes is possible, especially when voting via letter before the election day. In any case, Eco is an abstraction in a game, being able to change your vote as long as the election is running is intended in Eco. As far as the pressing multiple times "Yes" goes, I've unfortunately not been able to reproduce this. I'm only able to switch my vote to the opposite, which works as intended as stated above.

**Comment by Enel300** [comment]
I see. Too bad, then I have to remove the financial subsidy.

Should be reproducible: pass a law "per vote there is number of money", then start a vote and click several times on Yes or No. For each click money is distributed.

**Comment by D3nnis3n** [comment]
We use a similar law on White Tiger for years and have just limited it to a single vote in a specific timeframe. In our case there is only one general election every Sunday, though. Please also note that our voting feature is generalized - it is not only for candidate elections and elections of parliaments, but can also be used in councils or whatever idea players have. I know of a lot of election types beyond general political elections for offices or parliament-like that can make use of that. Given the voting timeframe is also configurable, it is very possible to have votes that run much longer than a week and can cause a need for such election.

In eco within the voting timeframe a lot more stuff can happen than it typically does in real life in the time between letter voting start and election day - so the ability to change your vote if new stuff comes up during election period is pretty vital.
