### ISSUE TITLE
[9.7.11-840] Workbench not accepting Stone Tag (Sandstone) from adjacent Stockpile

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23783]
I was attempting to craft a couple of Store items at the Woxrkbench and the Workbench refused to take the Sandstone stored in the adjacent stockpile to craft the Stores. I had to manually take it out and add it to the Workbench in order to complete the task.

**Comment by D3nnis3n** [comment]
Did you link the stockpile?

**Comment by Sarah-Graesyn** [comment]
yes; it was indeed linked

**Comment by Sarah-Graesyn** [comment]
not able to reproduce in 9.7.12 after further testing.
