### ISSUE TITLE
USER ISSUE: False accusation of cheating!!!

### ISSUE THREAD

**Issue by spike8888** [StrangeLoopGames/EcoIssues#23799]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
I am not able to provide steps to reproduce - I had issue with server connection - red big icon was flashing from time to time and after that I was thrown out of the game with message I use cheats!!! It is nonsense.

**Expected behavior:**
I would like to play normally

**Actual behavior:**
I am not able to connect to any server - they are even not visible.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods on my side, only the one on server - I do not even know what are they.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11300644/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11300645/Player-prev.log)

**Comment by D3nnis3n** [comment]
This feature is experimental and disabled by default, you can turn it off in the meanwhile in Users.eco: "MovementHackDetection": false.
