### ISSUE TITLE
USER ISSUE: Steam Version not showing mouse cursor when no internet connection

### ISSUE THREAD

**Issue by xCliede** [StrangeLoopGames/EcoIssues#23795]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
1. Disable network traffic (e.g. disconnect LAN cable, stop network adapter)
2. Start the game from Steam

**Expected behavior:**
It should have the mouse cursor visible, allowing to quit the game.

**Actual behavior:**
Instead it just shows the main menu scene, with no UI whatsoever.
Pressing 'Esc' opens the menu, but doesn't allow any interaction due to missing cursor.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Additional info:**
The problem by itself usually reproduces successfully, but not always.

Not allowing the game to take focus, by focusing on some other background application, consistently leaves the mouse cursor visible. Thus quitting the game is still possible via 'Esc' menu.

Having the dedicated server running in the background helps to mitigate the consistency of the issue, without un-focusing the game at startup.

When the game is started not from Steam, it shows the login dialog with the cursor enabled 100% of the tests.

I would assume that the problem lies in the cursor being hidden when the main scene is loaded and it probably expects any form of UI to trigger the cursor to show back again. The common denominator to all solutions seem to either show some UI or make the game skip hiding the mouse.

I failed to find any errors in the logs (apart from no authentication and failed analytics calls).

Consider maybe adding a dialog that states that the game is not playable without internet connection, thus solving multiple issues at once.

**Logs**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11253677/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11253588/Player-prev.log)

**Screenshot**
![eco_screenshot](https://user-images.githubusercontent.com/42871649/232567205-428fa9e6-7d17-4b25-8ab3-1595b8e0c989.png)

**Comment by D3nnis3n** [comment]
Thanks for the really sophisticated report, unfortunately it's a well known issue and a duplicate so I'm merging it with https://github.com/StrangeLoopGames/EcoIssues/issues/23718
