### ISSUE TITLE
Alpha.6 Missleading tooltip for Electric generator

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2379]
Say it converts mechanical energy to electricity but requires Petroleum or Gasoline
![image](https://user-images.githubusercontent.com/1900106/30986698-9fa445ae-a494-11e7-8293-99b72524045d.png)

**Comment by Fank** [comment]
Also other question, what is the right behavior? Burning fuel or converting energy?

**Comment by peternightingale** [comment]
agreed, this is very misleading. It's actually a gasoline generator. I was expecting it to convert energy from a windmill to electricity.

**Comment by MarjieAVolk** [comment]
Obsolete, as this object was removed
