### ISSUE TITLE
USER ISSUE: Bug

### ISSUE THREAD

**Issue by Y1em** [StrangeLoopGames/EcoIssues#23798]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
1. Try to cut tree

**Expected behavior:**
Cut tree

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by spike8888** [comment]
I have exact same issue but I was just running

**Comment by D3nnis3n** [comment]
This feature is experimental and disabled by default, you can turn it off in the meanwhile in Users.eco: "MovementHackDetection": false.
