### ISSUE TITLE
User Issue: Geistergras & Geisterwurzeln

### ISSUE THREAD

**Issue by Saschalpmit** [StrangeLoopGames/EcoIssues#23792]
Eco ver. 0.9.7.12 beta release-482
Wie reproduziert man den Fehler:

1. warten 
2. rumlaufen 
Erwartetes Verhalten:
Kein Gras / Wurzeln wird an Stellen angezeigt, wo vorher keins da war.

Actual Behavior:
Gras wird an Orten, wo vorher keins war angezeigt. Dies trifft auch Orte zu wo dieses abgebaut wurde.
Die Ansichtsprobleme treten bei mehreren auf dem gleichen Server auf:

Mods installiert?
ja

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23754
