### ISSUE TITLE
USER ISSUE: Connection Timed Out

### ISSUE THREAD

**Issue by LFShadowStorm** [StrangeLoopGames/EcoIssues#23797]
Mention which version of Eco this bug is occurring in: Latest Version 9.7.12
Add the steps to reproduce the bug (screenshots and videoclips/gifs help a ton as well):
Attempt to Open Application, Try to Connect to Server, Attempts to Connect, Connection Failed: Connection Timed Out
Error Log:
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2021.3.19f1 (c9714fde33b6)
[Subsystems] Discovering subsystems at path D:/Windows Games/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2060 (ID=0x1f15)
    Vendor:   NVIDIA
    VRAM:     5968 MB
    Driver:   31.0.15.3161
Version: 0.9.7.12 beta release-482
RAM: 32557MB Total / 25787MB Free
OS Version: Windows 11  (10.0.22621) 64bit
CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 12 Cores - 2.592 Ghz
System bit-ness: 64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 2.286800 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
WwiseUnity: Wwise(R) SDK Version 2021.1.6 Build 7774.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: D:/Windows Games/SteamLibrary/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script (NotificationsController) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Camera') is missing!
The referenced script on this Behaviour (Game Object 'Table') is missing!
The referenced script on this Behaviour (Game Object 'Notification') is missing!
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Initializing platform: SteamPlatform
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
PlatformManager:AddPrimaryPlatform(Object[])

Initialized social platform: DiscordSocialNetwork
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

Initialized social platform: SteamSocialNetwork
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
SocialNetworkManager:AddSocialPlatforms()
SocialNetworkManager:Awake()

OvrLipSync Awake: Queried SampleRate: 48000 BufferSize: 16000
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
OVRLipSync:Initialize()
OVRLipSync:Awake()

Authenticating with our primary platform.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Login(String, String, Boolean)
NetworkManager:Start()

Ambiguous UI component types ignored: SeriesPopupUI,BaseUI,ViewEditorUI,AutoViewUI,AutoModalUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.UIManager:Start()

[09:56:40.789] The desired audio input device is not available on the system.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoiceManager:SetActiveVoiceInputDevice(String, AsyncCallback)
VivoxUnity.AsyncNoResult:SetComplete()
VivoxUnity.Private.<>c__DisplayClass31_0:<BeginRefresh>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[09:56:41.663] Received login result from our primary platform. (Succes: True | Message: )
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, String)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[09:56:41.663] Account isn't developer tier.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Authentication.AppAuthentication:SetIdentity(AppIdentity)
NetworkManager:SetSessionAndIdentity(LoginSession)
NetworkManager:HandleLoginResult(LoginResult)
<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, String)
<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[09:56:42.093] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

The referenced script on this Behaviour (Game Object '<null>') is missing!
DG.Tweening.DOTween:InitCheck()
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, T2, Single, ABSTweenPlugin`3)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Color, Single)
DG.Tweening.DOTweenModuleUI:DOColor(Image, Color, Single)
PulseObject:StartImageAnimation()
PulseObject:OnEnable()
News.NewsController:UpdateNewsCounter(List`1)
News.NewsController:SetNews(List`1)
News.<SetNews>d__3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[ line 730782136]

[09:56:52.260] <Login>b__0: vx_req_account_anonymous_login_t failed: VivoxUnity.VivoxApiException: No Messages Currently Available (-1)
  at VivoxUnity.VxClient.EndIssueRequest (System.IAsyncResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Private.LoginSession+<>c__DisplayClass87_0.<Login>b__0 (System.IAsyncResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.AsyncResult`1[T].SetComplete (T result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.VxClient.InstanceOnMainLoopRun (System.Boolean& didWork) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Client.RunOnce () [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass87_0:<Login>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

[09:56:52.261] VivoxUnity.VivoxApiException: No Messages Currently Available (-1)
  at VoiceManager.<LoginUser>b__59_0 (System.IAsyncResult ar) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.AsyncNoResult.SetComplete () [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Private.LoginSession+<>c__DisplayClass87_0.<Login>b__0 (System.IAsyncResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.AsyncResult`1[T].SetComplete (T result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.VxClient.InstanceOnMainLoopRun (System.Boolean& didWork) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Client.RunOnce () [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Shared.Utils.Log:WriteException(Exception, Boolean)
VoiceManager:<LoginUser>b__59_0(IAsyncResult)
VivoxUnity.AsyncNoResult:SetComplete()
VivoxUnity.Private.<>c__DisplayClass87_0:<Login>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

Uploading Crash Report
VivoxApiException: No Messages Currently Available (-1)
  at VoiceManager.<LoginUser>b__59_0 (System.IAsyncResult ar) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.AsyncNoResult.SetComplete () [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Private.LoginSession+<>c__DisplayClass87_0.<Login>b__0 (System.IAsyncResult result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.AsyncResult`1[T].SetComplete (T result) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.VxClient.InstanceOnMainLoopRun (System.Boolean& didWork) [0x00000] in <00000000000000000000000000000000>:0 
  at VivoxUnity.Client.RunOnce () [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: perf-events.cloud.unity3d.com
[09:57:08.484] Warning/GameAnalytics: Event queue: Failed to send events to collector - Retrying next time
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
GameAnalyticsSDK.Net.Events.GAEvents:ProcessEvents(EGAHTTPApiResponse, JSONNode, String, String, Int32)
GameAnalyticsSDK.Net.Events.GAEvents:ProcessEvents(String, Boolean)
GameAnalyticsSDK.Net.Events.GAEvents:ProcessEventQueue()
GameAnalyticsSDK.Net.Threading.GAThreading:Run()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

Curl error 56: Receiving data failed with unitytls error code 1048578
[09:57:21.972] Connecting with NAT Punch Through to 8af87f2a-d8ad-4374-92f2-7c8970e15ba3...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:TryConnectWithNATPunch(ConnectionAttempt)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()

[09:57:36.975] Connecting with relay 54.244.203.197:3300 to 8af87f2a-d8ad-4374-92f2-7c8970e15ba3...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:TryConnectWithRelay(ConnectionAttempt)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()

[09:57:51.982] Disconnected with error: Failed to connect - connection timed out.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()

Unloading 6 Unused Serialized files (Serialized files now loaded: 3)
Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 137358.
Total: 115.719700 ms (FindLiveObjects: 6.068100 ms CreateObjectMapping: 11.673400 ms MarkObjects: 97.680300 ms  DeleteObjects: 0.297400 ms)

This error kicks my WiFi out and i am unable to connect to anything again until i reboot my computer.

**Comment by D3nnis3n** [comment]
```
Curl error 6: Could not resolve host: wp.play.eco
Curl error 6: Could not resolve host: perf-events.cloud.unity3d.com
```

This is not a Eco problem, something's off with your WiFi / hardware.
