### ISSUE TITLE
[10 - 2595] Crashes when returning to Main-Menu

### ISSUE THREAD

**Issue by Xavia1991** [StrangeLoopGames/EcoIssues#23790]
0.10.0.0 beta staging-2595

Created Avatar
Joined world Server: a09c02fa-3a62-4627-a766-1e64f0bf59dd
Escape => Exit to Main Menu

Screen freezes without error.

**Comment by D3nnis3n** [comment]
Thank you, please note that we currently do not yet accept bugs for Update 10.
Please report any issues you have until start of White Tiger playtest in discord channel #bug-testing.
As of our announcement, Update 10 is a preview in very early stage, so all these issues are known.
