### ISSUE TITLE
USER ISSUE:Player cannot interact with the world

### ISSUE THREAD

**Issue by Saschalpmit** [StrangeLoopGames/EcoIssues#23796]
Version: 0.9.7.12 beta release-482
Player cannot interact with the world

I recorded the error and attached it here
https://user-images.githubusercontent.com/76811293/233116812-7ca4ed3e-53ef-4d01-9302-90e60d31e4d6.mp4
Log Player
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11274569/Player.log)
[Player2.log](https://github.com/StrangeLoopGames/EcoIssues/files/11274577/Player2.log)
Log Server 
[log_230415082909.log](https://github.com/StrangeLoopGames/EcoIssues/files/11274591/log_230415082909.log)
[log_230418104258.log](https://github.com/StrangeLoopGames/EcoIssues/files/11274613/log_230418104258.log)

**Comment by D3nnis3n** [comment]
Looks like someone on the server used the dummy command?

**Comment by Saschalpmit** [comment]
> Looks like someone on the server used the dummy command?

@D3nnis3n Excuse me, i dont understand what a dummy command is. Could you please tell me what you mean? 
Thank you very much

**Comment by D3nnis3n** [comment]
It looks like the command for creating dummies was used on the server: /avatar dummy

**Comment by Matikari** [comment]
Don't know if its related, But our server believes this was occuring to us each time the excavator ran out of fuel.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided and cause likely being a developer command.
