### ISSUE TITLE
[9.7.12] Floating Grass

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23793]
In the swamp biome; it was a traumatic time on earth when the grass grew floating above the other grass

But in reality though; short story time over; my wife and I found double stacked grass in the swamp

![20230416215927_1](https://user-images.githubusercontent.com/1329717/232368559-9351a27d-5e3d-43ee-bffc-148bcf29af47.jpg)
![20230416220002_1_-_Copy](https://user-images.githubusercontent.com/1329717/232368701-1a736a2c-a4ee-43c1-95cc-c203865eef3e.jpg)

**Comment by SlayksWood** [comment]
thanks for the report dup #23754
