### ISSUE TITLE
USER ISSUE: stuck in hole

### ISSUE THREAD

**Issue by joostverbakel** [StrangeLoopGames/EcoIssues#23807]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
someone owns de area and has dug a hole and I fell in. Cant unstuck. Trapped.

**Expected behavior:**
respawn in other area	

**Actual behavior:**
keep spawning in the hole

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the most recent version, you're on a older one.

If the issue persists, please reopen the issue.
