### ISSUE TITLE
Alpha.6 Everything which consume Petroleum should return Barrel

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2380]

**Comment by Deantwo** [comment]
This bug should be fairly easy to fix now.
Just copy the way tailings are made, so number of barrels is reduced with efficiency skill. That should make it possible to return barrels equal to petroleum units used.

Do however watch out for possible backwards rounding.

**Comment by WeaselDog** [comment]
We have updated this so barrels are returned for all crafting recipes except fuels.
