### ISSUE TITLE
USER ISSUE: Cant star singleplayer worlds

### ISSUE THREAD

**Issue by EightyEight25** [StrangeLoopGames/EcoIssues#23805]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

my in game username is powerpoint.exe

**Steps to Reproduce:**
Launching any world

**Expected behavior:**
load normally

**Actual behavior:**
crashes before loading a world

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_230425105332.log](https://github.com/StrangeLoopGames/EcoIssues/files/11328520/log_230425105332.log)

**Comment by D3nnis3n** [comment]
The logfile hints at the world you are trying to start being of a newer version, likely Update 10 playtest. You cannot play a world from a newer version with a older version.

**Comment by D3nnis3n** [comment]
Closing issue due to no more response.
