### ISSUE TITLE
USER ISSUE: Bug vehicule - impossibilité de jouer

### ISSUE THREAD

**Issue by Salenders** [StrangeLoopGames/EcoIssues#23810]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
entrer sortir d'un véhicule / get in and out of a vehicle

**Expected behavior:**
quand on sort on doit avaoir linterface joueur / when we exit we must have the player interface

**Actual behavior:**
quand on sort du vehicule linterface reste celle du vehicule et le vehicule est toujours en marche / when you leave the vehicle the interface remains that of the vehicle and the vehicle is still running

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ranchingerc hewlogover9000compressed coalelectric take overbpf4road signgas pumpsteamfrontdisassemblyerc gatesaltered housing utilitaireelixir modbig shovelmixerfree solarerc universaltailing processing

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide a video of the issue and the respective logfiles as mentioned here:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by D3nnis3n** [comment]
Closing due to requested information not provided, feel free to reopen once you can provide the info if the issue persists.
