### ISSUE TITLE
USER ISSUE: Cheat movement

### ISSUE THREAD

**Issue by Selsuns** [StrangeLoopGames/EcoIssues#23811]
\
**User Id: (slg2582)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
Walk

**Expected behavior:**
Not kick me for walking

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This feature is experimental and disabled by default, you can turn it off in the meanwhile in Users.eco: "MovementHackDetection": false.
