### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Pronoiaparty** [StrangeLoopGames/EcoIssues#23819]
\
**User Id: (slg201212)**
**Version:** 0.9.7.12 beta release-482

**Steps to Reproduce:**
Try connect to any server, even after a fresh install

**Expected behavior:**
Should connect to a sever

**Actual behavior:**
The game stays on the "connecting..." screen for a while with no leaves loading on the tree and then crashes with the error below.

The following error message popped up:
```
<size=150%>Connection Failed</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, fresh install. Yes is occurring with no mods installed.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11467904/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11467913/Player-prev.log)

**Comment by D3nnis3n** [comment]
This error just says that you are unable to connect to the server, which is a networking problem, not a game problem. Logfile also hints at you being unable to connect to Vivox. Likely a security software or VPN issue.

Closing this issue, but feel free to reach out to support@strangeloopgames.com if your issue persists after checking the above.
