### ISSUE TITLE
USER ISSUE: Eco not letting me join my server

### ISSUE THREAD

**Issue by DarkWolfaf** [StrangeLoopGames/EcoIssues#23825]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
join

**Expected behavior:**
Not joining

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@DarkWolfaf Hi, You have upgraded to a new version, but the server owners have not ypdated the server yet. You can change the game version in steam
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/45708377/47df996c-6f5c-42ca-858f-30b0842fc25a)

**Comment by D3nnis3n** [comment]
Not a bug, see response of my colleague :)
