### ISSUE TITLE
Incorrect Spelling - Tastiness Bonus: (Calorie-Weigthed Average of Bonuses)

### ISSUE THREAD

**Issue by jwmc80** [StrangeLoopGames/EcoIssues#23829]
Incorrect Spelling - Tastiness Bonus: (Calorie-Weigthed Average of Bonuses)
Scroll down on the Food Tastiness Multiplier all the way to the bottom

Weighted is spelled incorrectly

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/91993280/f37ee5da-e767-4c6b-bc87-57e60484882d)

**Comment by jwmc80** [comment]
Still broken...
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/91993280/2644ec08-b577-4fc0-a299-f5012774ce9f)

**Comment by D3nnis3n** [comment]
Added to internal typo list, closing.
