### ISSUE TITLE
Stuck on Connecting to Server

### ISSUE THREAD

**Issue by Loutrinos** [StrangeLoopGames/EcoIssues#23830]
I am trying to load 2 game servers that were working some months ago.
After that something happened and there not seem to be able to connect to the servers and start the worlds.

Part of the player log:
```
NullReferenceException: Object reference not set to an instance of an object.
  at SteamSocialNetwork.IsSteamInitialized () [0x00000] in <00000000000000000000000000000000>:0 
  at SteamSocialNetwork.ClearRichPresenceStatus () [0x00000] in <00000000000000000000000000000000>:0 
  at PlatformUtils.VerifyPlatformAction (System.Action action, System.String actionName, System.Type platformType) [0x00000] in <00000000000000000000000000000000>:0 
  at SocialNetworkManager.ClearRichPresence () [0x00000] in <00000000000000000000000000000000>:0 
  at SocialNetworkManager.Shutdown () [0x00000] in <00000000000000000000000000000000>:0 
EcoEngine.Logging.LogManager:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
PlatformUtils:VerifyPlatformAction(Action, String, Type)
SocialNetworkManager:ClearRichPresence()
SocialNetworkManager:Shutdown()
```

server logs don't show any sign of issue.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11522571/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11522572/Player-prev.log)
[log_230520054429.log](https://github.com/StrangeLoopGames/EcoIssues/files/11522583/log_230520054429.log)
[log_230520053829.log](https://github.com/StrangeLoopGames/EcoIssues/files/11522584/log_230520053829.log)

**Comment by D3nnis3n** [comment]
Unfortunately none of the logs contain any hints towards a crash, hence we're not able to investigate the problem with these logs. The description is also lacking what actually happens when you try to load a world.

What I can already say though is that your hardware is below our minimum requirements and hence not supported. To take any look we'd need logs that actually contain the crash or problem, though.

**Comment by Loutrinos** [comment]
@D3nnis3n the issue is that it hangs on both local world and remote world and never passed the screen of Connecting to Server.
On the client log the last message before getting stuck is this:
```
[03:07:49.182] Nat introduction received with token = 1e25853e-a896-436e-984f-bbeba6c8becf
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(Address&, IntPtr, Int32, Boolean&)
Eco.Networking.ENet.ENetUdpPeer:Intercept(Event&, Address&, IntPtr, Int32)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__78_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

```

After that there is no other log on client and server log.
It seems that this might be an issue with the connectivity from the pc to the network. There was no network change during this time so it seems to be something from the game update.

From the hardware specification point, you are correct but the game was functioning properly till recently (around 3 months ago was working) so it could not be a specification point (I see the vga is the main point under the specifications).

**Comment by D3nnis3n** [comment]
The game is not responsible for the network connection, but your network is. The logs indicate you cannot make contact with any network services, which means there is a problem on your PC preventing it. Mostly that is due to security software.

**Comment by D3nnis3n** [comment]
What you do have in the earlier log is a potential steam update related issue of having different files though, so I would recommend saving your storage and configs directory in /steamapps/common/Eco/Eco_Data/Server, then uninstall Eco via Steam, remove the whole /steamapps/common/Eco folder and the AppData/Local Low/Strange Loop Games folder, then install Eco again and restore the backupped folders. This might solve the local loading, but you still have blocks for Vivox network connection, so can't promise this can help for online servers.

**Comment by D3nnis3n** [comment]
And yes, your VGA is problematic in regards to minimum requirements, as it only offers 2 GB of VRAM, which for most people leads to instant crashes, given 4 GB is the absolute minmum. I'm surprised that worked for you and hope it continues to do, but in case you ever experience crashed with D3D11 log lines, it's the VRAM being too little.

**Comment by D3nnis3n** [comment]
Also if all that failed, please try renaming your save file in /Storage to Game.db and Game.eco, then start the EcoServer.exe manually and let me know what happens.

**Comment by Loutrinos** [comment]
It will take a bit of time to try those out as the PC is not close by and I am not the one playing, but will let you know how the above suggestions helped. Thanks a lot for the time you invested in this.

**Comment by D3nnis3n** [comment]
All good, just let me know so we know the state of the problem :)

**Comment by D3nnis3n** [comment]
Any news?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
