### ISSUE TITLE
USER ISSUE: crsash 

### ISSUE THREAD

**Issue by broamego** [StrangeLoopGames/EcoIssues#23839]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
launch single player game 

**Expected behavior:**
should have launched 

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed

keep having one large sttockpile disappear while in game.</size>

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
We'll need a crash log provided to do anything, unfortunately with the information given there is nothing we can do.
