### ISSUE TITLE
 Eco LiteDB ENSURE: page type must be collection page serveur local

### ISSUE THREAD

**Issue by TowerEvent** [StrangeLoopGames/EcoIssues#23849]
\
**User Id: (towerevent.1906)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Démarrée le serveur local zeteerte't

**Expected behavior:**
il aurait du se lancée

**Actual behavior:**
Au lieu de celà, il affiche "LiteDB ENSURE: page type must be collection page"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Pas de mods
Le problème apparrait alos qu'il n'y a aucun mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11655388/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11655392/Player-prev.log)
[log_230605075028.log](https://github.com/StrangeLoopGames/EcoIssues/files/11655402/log_230605075028.log)

**Comment by D3nnis3n** [comment]
Looks like a corrupted database file. In /Steam/steamapps/common/Eco/Eco_Data/Server either restore the latest working .db file from the backup directory of your save to the Storage directory. Or delete the .db file for your save in the Storage folder.
