### ISSUE TITLE
USER ISSUE: Stockpiles and machines wanish after evicting from residency

### ISSUE THREAD

**Issue by Rajcze33** [StrangeLoopGames/EcoIssues#23845]
\
**User Id: (slg119790)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Create residency for second person, but chest or anyting that holds items inside and try to evict that person several times.	

**Expected behavior:**
Getting residency back

**Actual behavior:**
Wanishing of all Inventories and machines

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There is big shovel and maybe something more but mostly its vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Works as intended, objects placed by a resident go into their void storage when they are removed from residence.
