### ISSUE TITLE
USER ISSUE: Stuck at "Loading Items 0%"

### ISSUE THREAD

**Issue by DinoHorvat96** [StrangeLoopGames/EcoIssues#23854]
\
**User Id: (slg167604)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Attempt connection to server
2. Get stuck at "Loading Items 0%"

**Expected behavior:**
Loaded the items and let me play on the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods clientside, however the server has mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[eco log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/11713343/eco.log.txt)

**Comment by D3nnis3n** [comment]
You'll need to wait for a while, depending on the amount of mods the server has. The log is of no help, as it just reports it being cancelled by user and it's modded as well. Feel free to reach out to support@strangeloopgames.com for further help, this is not a bug.
