### ISSUE TITLE
[9.7.13] Fish Trap only Fresh Water?

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23850]
More a question than an issue I suppose but:

I saw that Fish Traps only function in Fresh Water now and I had to wonder what the reasoning was as I thought that they were sometimes used (though I don't know the environmental impact of it to be honest) in tropical and subtropical fisheries located in reefs. 

https://www.sciencedirect.com/science/article/abs/pii/S0165783619302875

**Comment by D3nnis3n** [comment]
Works as intended, Fish Trawlers will replace their functionality in 10.
