### ISSUE TITLE
USER ISSUE: Objekte verschwinden

### ISSUE THREAD

**Issue by Spassvogel1** [StrangeLoopGames/EcoIssues#23862]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Während des Spielen verschwinden Objekte. Zum Beispiel der Aufzug, Handkarren, oder Produktionsobjekt wie der Ofen oder das Sägewerk. Es kann aber über ein Lager auf deren Inventar zugegriffen werden. Nach einem Neustart des Speicherstandes sind die Objekte wieder da.

**Expected behavior:**
Bitte korrigieren dass keine Objekte mehr unsichtbar sind

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Dieses Problem tritt sowohl mit als auch ohne Mods auf

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11849964/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11849965/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23107
