### ISSUE TITLE
Alpha .6 Wrong calculated Stomach Content

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2386]
Server was migrated, I logged in, my Stomach content was empty. Ate 2 Fooditems, Now my Content is full. Macaroon is 250, Huckleberry Pie is 1300.
![image](https://user-images.githubusercontent.com/3965439/30994803-6fca6828-a4b6-11e7-86e4-7ef539c25ab9.png)

**Comment by Dr-Hardware** [comment]
I was under the impression that stomach content lasts 24 hrs max, whereas calories leach away at a fairly slow rate when you're inactive (or offline)

hence I would expect that it should be quite possible that you still had calories whilst not having eaten in the last 24 hrs....?

**Comment by MarjieAVolk** [comment]
I assumed you meant that your calories were empty when you logged in?

**Comment by Frozen-byte** [comment]
yes on logging in stomach and calories where  empty.

**Comment by craig-jong** [comment]
I couldn't get this to reproduce. My guess is this is a migration issue.

Please reopen this is it can be reproduced on 6.0.
