### ISSUE TITLE
Small paper machine have no tab for crafting

### ISSUE THREAD

**Issue by maate21** [StrangeLoopGames/EcoIssues#23866]
Game version: 0.10.0.0 beta playtest-12

Small paper machine have no tab for crafting, so its impossible to craft paper lanterns
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2510111/a013138a-6334-4e56-873c-8d1bea1fc70f)

**Comment by maate21** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2510111/cd056ef2-6e48-46bf-9050-67076a67b538)

**Comment by SlayksWood** [comment]
Fixed in 0.10.0 playtest-16:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/45708377/2ef805f0-af8d-4a0e-b3af-ab6ee27ddd0d)

**Comment by SlayksWood** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/45708377/ed3dc05b-ec10-496e-b979-47abf5614999)
fixed in 0.10.0 playtest-16
