### ISSUE TITLE
USER ISSUE: spawn system not functioning

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23868]
\
**User Id: (slg230830)**
**Version:** 0.10.0.0 beta playtest-16

**Steps to Reproduce:**
load into server

**Expected behavior:**
should have loaded map with spawn locatiions

**Actual behavior:**
no spawn locations are present on map

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
