### ISSUE TITLE
USER ISSUE: unclaim crash

### ISSUE THREAD

**Issue by kozel** [StrangeLoopGames/EcoIssues#23869]
\
**User Id: (slg230766)**
**Version:** 0.10.0.0 beta playtest-16

**Steps to Reproduce:**
take claim tool, try to unclaim land

**Expected behavior:**
unclaim a plot

**Actual behavior:**
1/ lower2/ full client crash
<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at E</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**


**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in -19.
