### ISSUE TITLE
USER ISSUE: Picking up log crashes game

### ISSUE THREAD

**Issue by SweetChristmas** [StrangeLoopGames/EcoIssues#23860]
\
**User Id: (slg154242)**
**Version:** 0.10.0.0 beta staging-2671

**Steps to Reproduce:**
1. Cut down tree
2. Slice log from trunk
3. Attempt to collect the log

**Expected behavior:**
Added to inventory

**Actual behavior:**
Crashes the game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_230620050710.log](https://github.com/StrangeLoopGames/EcoIssues/files/11812355/log_230620050710.log)

**Comment by SweetChristmas** [comment]
Proposed solution:
id is not a byte[], use newGuid(id.ToString()) instead
On TreeObject.cs :
    public void PickUp(Player player, InteractionTriggerInfo trigger, InteractionTarget target) { if (target.TryGetParameter("id", out var id)) this.PickupLog(player, new Guid(id.ToString()), target.HitPos); }

**Comment by D3nnis3n** [comment]
Should be fixed by https://github.com/StrangeLoopGames/Eco/pull/12605
