### ISSUE TITLE
USER ISSUE: Pickaxe mines twice per swing

### ISSUE THREAD

**Issue by tclasen** [StrangeLoopGames/EcoIssues#23876]
\
**User Id: (slg222569)**
**Version:** 0.10.0.0 beta playtest-22

**Steps to Reproduce:**
No idea. I was mining, internet died, and I came back as a super human.

**Expected behavior:**
A single left click while holding an iron pickaxe should consume X calories and break a single rock block into pieces.

**Actual behavior:**
The first half of the animation break the rock under my cursor and I consume X calories, then the second half of the animation also breaks the next rock now under my cursor and consumes another X calories.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods on my end, but I'm playing on the WT 10.0 Playtest server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11943700/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11943701/Player-prev.log)

**Comment by Dimossa** [comment]
Happens with mining and logging. Mostly happens after restart, works for a few minutes after joining the server. Might be related to packets being lost and server trying to makes sense of it.

**Comment by D3nnis3n** [comment]
Fixed.
