### ISSUE TITLE
USER ISSUE: Cannot Hoe ground in Desert

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23877]
\
**User Id: (slg56161)**
**Version:** 0.10.0.0 beta playtest-22

**Steps to Reproduce:**
1. Make a Hoe
2. Hoe the ground in the Desert	

**Expected behavior:**
Should have created a spot to plant seeds	

**Actual behavior:**
Did nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/28ac4f8f-6c06-44e5-b33b-e864088ab07d

**Comment by TwixterZ** [comment]
hi @Sarah-Graesyn thanks for informing us of this issue, we have informed our developer of the same.

Issue ref : 29227

**Comment by D3nnis3n** [comment]
This should be fixed.
