### ISSUE TITLE
USER ISSUE: Character Stuck

### ISSUE THREAD

**Issue by flybfree** [StrangeLoopGames/EcoIssues#23879]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Fell between log and rock.  now i can't move

**Expected behavior:**
should not have gotten stuck

**Actual behavior:**
My character is trapped

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Use /unstuck to get out of there.
