### ISSUE TITLE
long entering and get darkscreen.

### ISSUE THREAD

**Issue by Najorine** [StrangeLoopGames/EcoIssues#23870]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-19

**Steps to Reproduce:**

**Expected behavior:**
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11915822/Player.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11915817/Player.log)

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Will be fixed with next update.
