### ISSUE TITLE
USER ISSUE: Disappeared Cart

### ISSUE THREAD

**Issue by Morranr** [StrangeLoopGames/EcoIssues#23873]
\
**User Id: (slg166445)**
**Version:** 0.10.0.0 beta playtest-19

**Steps to Reproduce:**
1. Have a cart (happened with normal Wood Cart for me)
2. Put something in the cart (in my case a stack of food that took most of my carry capacity)
3. Try the new feature to "move" the cart (in my case a couple of blocks away to test)

**Expected behavior:**
Cart appears at the destination location, or fails with an error message and cart does not move/change

**Actual behavior:**
Food that was in the cart got picked up and put in my inventory, and cart disappeared; it is not visible to me or other players. Possibly just deleted, or possible the game tried to pick it up after the food got put in my inventory and failed due to weight? Deed for the cart appears to be gone as well, or at least is not linked from my character tooltip.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Whatever is installed on the WT playtest

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11924179/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11924180/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed.
