### ISSUE TITLE
Moving the marker leaves a ghost behind

### ISSUE THREAD

**Issue by bpmckinnon** [StrangeLoopGames/EcoIssues#23884]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/ab45bb71-e112-40b1-a0e3-6eadbe907ab4)
I moved my homestead claim stake a little to the left and I now can't place anything in the spot where it was.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/9b487da1-3a97-4414-9364-205b428eb033)

**Comment by TwixterZ** [comment]
@bpmckinnon does this issue persist even after server restart? 
does this issue happens to you on local?

**Comment by bpmckinnon** [comment]
After the update to playtest-37 the issue was fixed when I rejoined the game.  I assume a server restart happened overnight.
Moving the marker a little more to the left still causes the issue
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/fad77f94-2a59-40da-93f3-fb180a458b75)

**Comment by bpmckinnon** [comment]
I've confirmed that it happens locally as well.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/bcbf7198-fa2a-43c2-b180-9b72b1d67324)

**Comment by TwixterZ** [comment]
@bpmckinnon , can you share your log file for when this happens? 

location : C:\Users\**username**\AppData\LocalLow\Strange Loop Games\Eco
File : player.log

also your local server log 
location : F:\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Logs
File : refer to "date modified", grab the latest one

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/23928
