### ISSUE TITLE
USER ISSUE: "Tool Strength: Logging" Perk is nonfunctional

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23880]
\
**User Id: (slg56161)**
**Version:** 0.10.0.0 beta playtest-23

**Steps to Reproduce:**
1. Acquire a Stone Axe or Iron Axe
2: Examine the basic tool durability
3. Take Logging Skill
4. Level Logging Skill to Level 3
5. Take "Tool Strength: Logging" Perk
6. Examine Tool Durability after Perk

**Expected behavior:**
Expected the tools to "upgrade" (show the stat increases of) the next tier of tool (i.e. Stone Axe shows the equivalent durability and base damage of an Iron Axe etc...)

**Actual behavior:**
The tools are unaffected by the perk and retain their base damage and durability; I do notice that the damage increases slightly but not to the level of the next tier tool like the Perk states.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/7eaba840-618b-4f01-bed4-2014d3e252ad) - Conversation with a non-logging player to compare the tools. 

https://www.dropbox.com/s/nk10hfx6mc6z4vn/Eco%202023-07-05%2019-24-55.mp4?dl=0 - Screen Recording of me testing it

**Comment by D3nnis3n** [comment]
This should be fixed.
