### ISSUE TITLE
USER ISSUE: Eviction causes loss of items

### ISSUE THREAD

**Issue by Triplight** [StrangeLoopGames/EcoIssues#23887]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
invite someone to residence
decide to change land claim
told have to kick residents
kick residents
all their stuff is deleted

**Expected behavior:**
HAD A WARNING

**Actual behavior:**
Screwed us out of half a days work

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Works as intended. Stuff is in void storage.
