### ISSUE TITLE
USER ISSUE: IRON DRILL

### ISSUE THREAD

**Issue by GazzassDK** [StrangeLoopGames/EcoIssues#23881]
\
**User Id: (slg165243)**
**Version:** 0.10.0.0 beta playtest-23

**Steps to Reproduce:**
Only works down.

**Expected behavior:**
dosent work to sides or up.

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Normal yes, but not on playtest 10 here. :-) 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be fixed.
