### ISSUE TITLE
Inventory is filling when empty

### ISSUE THREAD

**Issue by bpmckinnon** [StrangeLoopGames/EcoIssues#23883]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/cc80cf06-f00e-4eab-a484-c1298f654de6)
My inventory is filling up with with weight but not emptying.  In the picture below I have nothing on me and I am carrying 25kg
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/09d6c705-0003-489a-a040-43d9e0ec90dd)
First it was 15kg, then it went to 25kg.  So I think it might have something to do with unloading my canoe and cart.  I'm currently playing on this server so I have nothing to share other than pictures.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/4360155/e8e7f82f-980b-49d7-9112-e11e0a1ce2b5)
Also, I'm wearing a bear backpack that came as part of my initial character setup if that is at all interesting.
The issue persists after quiting and rejoining.

**Comment by bpmckinnon** [comment]
After the update to playtest-37 and I assume a server restart the issue has reset.  I'll update if it keeps happening.

**Comment by Dimossa** [comment]
started happening here after update as well.

**Comment by bpmckinnon** [comment]
Sorry, forgot to update.  I'm still experiencing this as well.

**Comment by D3nnis3n** [comment]
This should be fixed.
