### ISSUE TITLE
Need growth animations or something to prevent invisible tomatoes

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2388]
They are invisible when not fully grown.
Check other plants too if you can.

**Comment by keegan-o** [comment]
They are there at 0 on the growth slider, so not an art thing I don't think. 
![image](https://user-images.githubusercontent.com/14983165/30996121-1b0133e6-a473-11e7-8920-3205f66f0714.png)

**Comment by craig-jong** [comment]
I can look into this, but I'm not exactly sure how to reproduce it.

**Comment by johnkslg** [comment]
It could be some other problem

**Comment by craig-jong** [comment]
Diagnosed a saving issues/desync with plantsim and the world

**Comment by johnkslg** [comment]
Fixed
