### ISSUE TITLE
Town Mayor with "Can Use Treasury Bank Account" misses access to Treasury.

### ISSUE THREAD

**Issue by Ovvnage** [StrangeLoopGames/EcoIssues#23885]
I just edited the Title name, and added "Can Use Treasury Bank Account" to town mayor Title. I still cant spend or add the treasury account to the shop. 

The Town is Peculiar (0.10.0.0 beta playtest-37)

Attached are screenshots. I dont think client profile/logs are relevant.

https://cdn.discordapp.com/attachments/606205030344687616/1126481801762844813/image.png
https://cdn.discordapp.com/attachments/1121328045710647296/1126482749717495869/image.png
https://cdn.discordapp.com/attachments/606205030344687616/1126481802052243506/image.png

**Comment by Ovvnage** [comment]
As Elmeye suggested, I created a new gov account. I noticed after that, the original town treasury account got unlocked!

**Comment by D3nnis3n** [comment]
Closed as resolved by user.
