### ISSUE TITLE
Issue with selling full inventory to store and then returning to sell more

### ISSUE THREAD

**Issue by aiartificer** [StrangeLoopGames/EcoIssues#23893]
![WT_Bug_Cannot_Sell_Crops_I_Have](https://github.com/StrangeLoopGames/EcoIssues/assets/59231695/e89a1440-16e7-4ec1-bf71-e55d4d810b27)

I'm seeing an issue where you can sell your full inventory of an item to a store and then not be able to sell more when you come back to that store later.  I noticed this issue on White Tiger while using version 0.10.0.0 beta playtest-39 of Eco.

To replicate the issue, one must sell their full inventory of an item to a store.  At this point the store can purchase more of that item but you lack any more of that item in your inventory.  One the goes off to fetch more of the item and then return to the store to sell more of said item.  Upon returning, the store will indicate that "you don't have any of this item to sell" when in fact you do.

**Comment by D3nnis3n** [comment]
This should be fixed.
