### ISSUE TITLE
USER ISSUE: Printing press, print quantity bug

### ISSUE THREAD

**Issue by Dimossa** [StrangeLoopGames/EcoIssues#23899]
\
**User Id: (slg230589)**
**Version:** 0.10.0.0 beta playtest-41

**Steps to Reproduce:**
if input 1> output is always 1, no matter the input quantity.

**Expected behavior:**
print a picture with more than 1 poaper placed in the tray.

**Actual behavior:**
outputs 1 picture, instead of multiple.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/12862
