### ISSUE TITLE
USER ISSUE: fixing land claim of homestead of kozlito

### ISSUE THREAD

**Issue by kozel** [StrangeLoopGames/EcoIssues#23892]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-39

**Steps to Reproduce:**
1. on day one magically loose homestead claim stake2. on day eight, realize you want more than 20 plots. 3. create another claim stake4. realize you cannot use it to add to your current plots5. unclaim 20 plots, with last unclaim boom crash

**Expected behavior:**
i should've not crashed :D

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at E</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This issue should be fixed in the newest playtest builds.
