### ISSUE TITLE
USER ISSUE: Can't Log into any server

### ISSUE THREAD

**Issue by TopSecretPorkChop** [StrangeLoopGames/EcoIssues#23890]
\
**User Id: (slg40279)**
**Version:** 0.10.0.0 beta playtest-39

**Steps to Reproduce:**
Choose New Game from the main menu.
Choose White Tiger (or any other server it seems) from the first page of server listings.

**Expected behavior:**
The client should log into the server and show the location selection map screen.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.Item.GetItemByString(User user, String item)
   at Eco.Gameplay.Ite</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closed as resolved by user.
