### ISSUE TITLE
Cannot Load Local World after Crash

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#23894]
![20230708192528_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/9f7b777e-8b3e-452b-a380-eaea9d4731d1)

I was attempting to load my local world to retest another bug I have encountered and my computer crashed out on me and I have completely re-installed Eco fresh but I continually get the above message now when trying to load into any local world, even a completely new local world from the original.  I have no mods installed. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11993997/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/11994011/Player-prev.log)

**Comment by D3nnis3n** [comment]
Wrong log, need the server log. Likely you need to restore a backup, crash while game running causes savegame to corrupt.
