### ISSUE TITLE
Law emptied gov account when someone buy from gov shop.

### ISSUE THREAD

**Issue by Ovvnage** [StrangeLoopGames/EcoIssues#23897]
Greetings.

Created a shop in town hall (town foundation deed) with the town treasury euro account. When the shop buy stuff everything works as intended, but if the shop sells the law will empty the account, with my company account as destiny. 

The Deed belongs to mayor, shop belongs to the deed, gov account belongs to the mayor.

I try creating a new gov account, but with the same result. The issue seems to be in the law or some inner working.
Peculiar Town Hall Shop

Attached a screenshot of the transfers.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/12295506/dfd5b9e9-8151-48d5-9cca-9fa0a794b2f1)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/12295506/b3259ccf-a25a-411c-9480-6e63ea0e4cdc)

**Comment by D3nnis3n** [comment]
Reported internally.

**Comment by Ovvnage** [comment]
The shop in Zen State Office Deed dont have this problem. I suspect it has to do with how Jnpox (deed owner) is not part of a company, so the law doesnt hit him.
