### ISSUE TITLE
USER ISSUE: Claim generation window blank in the foundation

### ISSUE THREAD

**Issue by Dimossa** [StrangeLoopGames/EcoIssues#23898]
\
**User Id: (slg230589)**
**Version:** 0.10.0.0 beta playtest-41

**Steps to Reproduce:**
m,ultiple time moving the foundation at diff locations.

**Expected behavior:**
eventually generation claim window becomes without slots, so new claims generated for new players.

**Actual behavior:**
eventually generation claim window becomes without slots, so new claims generated for new players.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Internally reported, please only ever report on Discord or here.
