### ISSUE TITLE
USER ISSUE: Crash picking up hewn log after build roads

### ISSUE THREAD

**Issue by bpmckinnon** [StrangeLoopGames/EcoIssues#23903]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-44

**Steps to Reproduce:**
pick up roads and build with stripe
pick up hewn log from storage using hammer

This based on momentatrily seeing the road construction options after picking up hewn

**Expected behavior:**
Switch to hewn

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:All inventories must be known before creating a change set
Source:Eco.Gameplay

System.Exception: All inventories must be known before creating a change set
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, ChangedStack changedStack, Int32 old</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by bpmckinnon** [comment]
I was able to repeat this exact process and reproduce the crash.  If it changes anything I had an iron hammer and was unloading from a steam truck.

**Comment by bpmckinnon** [comment]
I just reproduced it without the road part.  I'm building barrel docks.  If I open the storage and move the hewn into may hands then it doesn't crash.  When I use my hammer it always crashed.

**Comment by D3nnis3n** [comment]
Fixed.
