### ISSUE TITLE
USER ISSUE: Can't Log In to WhiteTiger Public Server

### ISSUE THREAD

**Issue by aiartificer** [StrangeLoopGames/EcoIssues#23907]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-46

**Steps to Reproduce:**
Attempt to log into WhiteTiger public server.  I am thrown out of the "Entering Server" step almost immediately.  I was on the server but then received this bug and can't seem to get back in.

**Expected behavior:**
When logging in, I should not be thrown out of the "Entering Server" step almost immediately.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>Internal Server Error, Trace ID: 00-1a8140e3de418fd626ad71737f63f898-0561a9b6d8e28457-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.  Haven't tried to install mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That was a temporary auth server failures, should be resolved.
