### ISSUE TITLE
USER ISSUE: client crashed from server and back into menu

### ISSUE THREAD

**Issue by MissandeiVR** [StrangeLoopGames/EcoIssues#23902]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12022338/Player.log)
\
**User Id: (slg69660)**
**Version:** 0.10.0.0 beta playtest-43

**Steps to Reproduce:**
either try to join and it will crash or just playing

**Expected behavior:**
client side crash in server

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: Exception
Message:All inventories must be known before creating a change set
Source:Eco.Gameplay

System.Exception: All inventories must be known before creating a change set
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, ChangedStack changedStack, Int32 old</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12022331/Player.log)

**Comment by MissandeiVR** [comment]
seems like i crash when using my hammer on a storage like a steam truck.

**Comment by D3nnis3n** [comment]
This has been fixed.
