### ISSUE TITLE
USER ISSUE: Changing exchange currency

### ISSUE THREAD

**Issue by Dimossa** [StrangeLoopGames/EcoIssues#23900]
\
**User Id: (slg230589)**
**Version:** 0.10.0.0 beta playtest-41

**Steps to Reproduce:**
Using excnahge currency, setting currency to trade

**Expected behavior:**
currencty should be set without crash.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Missing RPC call SetCurrency for ExchangeEntry
Source:Eco.Core

System.InvalidOperationException: Missing RPC call SetCurrency for ExchangeEntry
   at Eco.Core.Controller.ControllerManager.HandleViewRPC(INetClient client, Int32 universalID, String me</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello,

This is fixed for 0.10.0.0 beta playtest-107.
Closing this.

Ref: ECO-28846
