### ISSUE TITLE
USER ISSUE: Weird Inventory Error

### ISSUE THREAD

**Issue by Tombo3006** [StrangeLoopGames/EcoIssues#23901]
\
**User Id: (slg197014)**
**Version:** 0.10.0.0 beta playtest-42

**Steps to Reproduce:**
Went to pick up Hewn Logs using the building tool and this error popped up

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: Exception
Message:All inventories must be known before creating a change set
Source:Eco.Gameplay

System.Exception: All inventories must be known before creating a change set
   at Eco.Gameplay.Items.InventoryChangeSet.ModifyStack(ItemStack stack, ChangedStack changedStack, Int32 old</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
