### ISSUE TITLE
USER ISSUE: Mechanic power is too high for all machinist's tables and above

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#23908]
\
**User Id: (slg39186)**
**Version:** 0.10.0.0 beta playtest-46

**Steps to Reproduce:**
Any tables(like Shapers,Assiable, Scew Press, etc) is useing the old 9.X verson of it, instead of 10.X

**Expected behavior:**
instead of needing 250W it should need 25W

**Actual behavior:**
but it has not been edited, so instead we need 250W which would need more than 13 waterwheels

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, but i did have to edit the code to fix this, so I could play

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended, you are not supposed to use waterwheels and windmills for anything but the most basic stuff, afterwards you need steam generators, which now provide high mechanical energy.
