### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by MissandeiVR** [StrangeLoopGames/EcoIssues#23904]
\
**User Id: (slg69660)**
**Version:** 0.10.0.0 beta playtest-46

**Steps to Reproduce:**
try to join server and it crashed

**Expected behavior:**
join server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MissandeiVR** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12044320/Player.log)

**Comment by MissandeiVR** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12044322/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed.
