### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by maksim9938** [StrangeLoopGames/EcoIssues#23906]
\
**User Id: ()**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Неверный логин или пароль.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Reach out to support@strangeloopgames.com if you own the game and are unable to reset the password through website.
