### ISSUE TITLE
USER ISSUE: Placed Claim Stake in Water, Claimed Land, Claim Stake Not Placed Leadint to Invalid Situation

### ISSUE THREAD

**Issue by aiartificer** [StrangeLoopGames/EcoIssues#23909]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-46

**Steps to Reproduce:**
(1) Place a claim stake in an invalid location (in my case, I accidentally placed it in water
(2) Claim Stake won't place because it's an invalid location but the land will be claimed for you.  Naturally, this creates difficulties.
(3) Attempt to unclaim the plot and the game crashes.  FYI, before this, I successfully placed my claim stake next to the invalid claim.

**Expected behavior:**
Placing a claim stake in an invalid location should claim the land.  Also, the crash is problematic.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at E</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods and I don't know what happens with mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hello, 

This is fixed for playtest 0.10.0.0 beta playtest-107
I'll be closing this.

Ref: ECO-29325
