### ISSUE TITLE
USER ISSUE: Allow Players to go Back and Play Older Version Types

### ISSUE THREAD

**Issue by EBoyWarrior** [StrangeLoopGames/EcoIssues#23911]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I know ECO's team prefers to actually play newer versions of the game, but I'd really enjoy playing my past times. I normally play the previous version when any major updates to the game. I'm currently trying to play 8.3.3 but the log in isn't letting me into the game. I do this to play my childhood nostalgia and embrace what ECO had to offer then and now in a compare and contrast paper.

**Expected behavior:**
Allowed me to log in.

**Actual behavior:**
Error message

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods have been installed

**Comment by D3nnis3n** [comment]
We do support playing older versions by allow to download a limited amount of them on Steam and our website. Some versions you can no longer play, as we made major changes to our infrastructure inbetween and authentication is no longer possible. We're not going to introduce legacy authentication servers for versions we don't want players to play on, though, and I hope for your understanding for that.
