### ISSUE TITLE
USER ISSUE: No menu

### ISSUE THREAD

**Issue by Dubs73pp3r** [StrangeLoopGames/EcoIssues#23910]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Start game.  No menu

**Expected behavior:**
it should have menu

**Actual behavior:**
The following error message popped up:
```
Cannot resolve destination host
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a local networking problem being unable to resolve the host of authentication servers. As usual, check for any VPN's, security software, firewalls and ISP issues. support@strangeloopgames.com might be able to help you out beyond, but this is not a bug.
