### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by CaptNik** [StrangeLoopGames/EcoIssues#23917]
\
**User Id: (slg46177)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
Try to connect to server	

**Expected behavior:**
It should have let me into the server.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Server encountered an exception:

<size=60,00%>Exception: IOException
Message:The filename, directory name, or volume label syntax is incorrect. : 'D:\Servers\Eco\Sea Otter\Storage\UserTextures\Unreviewed\192697-Capt. NiK ?3-1367,9868698120117.jpg'
Source:System.Private.CoreLib

System.IO.IOException: The filename, directory name, or volume </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by CaptNik** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12197701/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12197702/Player.log)

**Comment by D3nnis3n** [comment]
Fixed.
