### ISSUE TITLE
USER ISSUE: cRASH WHEN BUYING AND THEN Leaving property

### ISSUE THREAD

**Issue by chris-9999** [StrangeLoopGames/EcoIssues#23922]
\
**User Id: (slg127055)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
Buy something

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidCastException
Message:Specified cast is not valid.
Source:System.Private.CoreLib

System.InvalidCastException: Specified cast is not valid.
   at Eco.Gameplay.Players.Player.QueryAuthStatus(Player player, Deed deed, Vector3i blockPos, INetObject netObj, AccessType requiredAcce</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Sea Otter

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
