### ISSUE TITLE
USER ISSUE: Keep on crashing Sea Otter but don't know why beyond that

### ISSUE THREAD

**Issue by aiartificer** [StrangeLoopGames/EcoIssues#23924]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
(1) Log into Sea Otter
(2) Walk a short bit
(3) Crash to front screen or entirely out of Eco

On Sea Otter using Eco version 0.10.0.0 beta playtest-67

**Expected behavior:**
Not crashing several times in a couple minutes

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidCastException
Message:Specified cast is not valid.
Source:System.Private.CoreLib

System.InvalidCastException: Specified cast is not valid.
   at Eco.Gameplay.Players.Player.QueryAuthStatus(Player player, Deed deed, Vector3i blockPos, INetObject netObj, AccessType requiredAcce</s
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12207101/Player.log)
ize>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue ha
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12207102/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12207103/Player.log)
ppen when no mods are installed?:**
No mods installed.  Yes, this issue happens when no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by aiartificer** [comment]
Some more info:

- Face tracking is not enabled (I just checked)
- Saw a suggestion that uninstalling and reinstalling the specific beta version fixes the issue.  Ultimately, I tried this and it did not fix the issue.

**Comment by D3nnis3n** [comment]
Fixed.
