### ISSUE TITLE
USER ISSUE: Server is kicking out

### ISSUE THREAD

**Issue by DigitalPinkRabbit** [StrangeLoopGames/EcoIssues#23920]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
Happens randomly after log in or after few minutes in

**Expected behavior:**
just not happening

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidCastException
Message:Specified cast is not valid.
Source:System.Private.CoreLib

System.InvalidCastException: Specified cast is not valid.
   at Eco.Gameplay.Players.Player.QueryAuthStatus(Player player, Deed deed, Vector3i blockPos, INetObject netObj, AccessType requiredAcce</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MissandeiVR** [comment]
i got the same issue https://github.com/StrangeLoopGames/EcoIssues/issues/23921

**Comment by MissandeiVR** [comment]
just love ow it ask you expected behavior. and your just like not to crash?

**Comment by D3nnis3n** [comment]
Fixed.
