### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by MissandeiVR** [StrangeLoopGames/EcoIssues#23921]
\
**User Id: (slg69660)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
join server and turn around and then i crash

**Expected behavior:**
join server and not crash due to something?

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidCastException
Message:Specified cast is not valid.
Source:System.Private.CoreLib

System.InvalidCastException: Specified cast is not valid.
   at Eco.Gameplay.Players.Player.QueryAuthStatus(Player player, Deed deed, Vector3i blockPos, INetObject netObj, AccessType requiredAcce</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no i joined the sea odder server

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12205516/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12205517/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed.
