### ISSUE TITLE
USER ISSUE: Mining a block S.O.

### ISSUE THREAD

**Issue by chris-9999** [StrangeLoopGames/EcoIssues#23926]
\
**User Id: (slg127055)**
**Version:** 0.10.0.0 beta playtest-72

**Steps to Reproduce:**
Try to mine a 2 hit or more block

**Expected behavior:**
Pick should be able to hit multiple times

**Actual behavior:**
Pick will hit once then not strike any more untill character targets something else.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed
