### ISSUE TITLE
USER ISSUE: [PlayTest] Crash after login

### ISSUE THREAD

**Issue by rdegelo** [StrangeLoopGames/EcoIssues#23925]
\
**User Id: (slg185837)**
**Version:** 0.10.0.0 beta playtest-67

**Steps to Reproduce:**
I log in and crash

**Expected behavior:**
No crash

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidCastException
Message:Specified cast is not valid.
Source:System.Private.CoreLib

System.InvalidCastException: Specified cast is not valid.
   at Eco.Gameplay.Players.Player.QueryAuthStatus(Player player, Deed deed, Vector3i blockPos, INetObject netObj, AccessType requiredAcce</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
