### ISSUE TITLE
USER ISSUE: Moving objects with hammer

### ISSUE THREAD

**Issue by Pacmud** [StrangeLoopGames/EcoIssues#23928]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-71

**Steps to Reproduce:**
Moving an object in a land claim using Ctrl + Left Click will move furniture to new location.

**Expected behavior:**

**Actual behavior:**
The objects are moved visually and can be interacted with, but workbenches and queued tasks popup circles would remain on the same old place and the space of origin remains occupied.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This issue should be fixed in the newest playtest builds.
