### ISSUE TITLE
USER ISSUE: While holding a tool the player doesnt stop picking up after button release

### ISSUE THREAD

**Issue by wilhelmines** [StrangeLoopGames/EcoIssues#23936]
\
**User Id: (slg230897)**
**Version:** 0.10.0.0 beta playtest-74

**Steps to Reproduce:**
1. Select tool in inventory
2. Pick up a something. Tested with, stone road block, granite and wood

**Expected behavior:**
Pick up one block or keep picking up as long as the button is pressed and stop then.

**Actual behavior:**
After releasing the button to pick something up the game keeps picking up stuff and stops after switching to another inventory slot or using the tool again.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by wilhelmines** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12232910/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12232911/Player-prev.log)

**Comment by wilhelmines** [comment]
Same happens with other tools and items. Eg axe and carcass

**Comment by D3nnis3n** [comment]
Fixed.
