### ISSUE TITLE
[0.10.0.0 beta playtest-74] Excess items lost when dragging on project

### ISSUE THREAD

**Issue by ZachBora** [StrangeLoopGames/EcoIssues#23938]
When you queue a recipe and it's missing resources. If you have them in your back and you drag to the recipe the excess items are lost.

Project before dragging:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/1097596/7180e2e3-bd1b-44bb-bae0-0774831cf2ec)

After dragging, 11 get added and the 1 extra is gone. It's not in void storage, its not in regular storage. 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/1097596/ca5d4149-d596-4c39-8d89-66c75a33bddc)

**Comment by D3nnis3n** [comment]
This should be fixed.
