### ISSUE TITLE
USER ISSUE: Stairs are rotated by 90 degree after loading a 9.7.x world in 10.0

### ISSUE THREAD

**Issue by wilhelmines** [StrangeLoopGames/EcoIssues#23935]
\
**User Id: (slg230897)**
**Version:** 0.10.0.0 beta playtest-74

**Steps to Reproduce:**
1. Load world created in 9.7.x in 10.0

**Expected behavior:**
Blocks shouldnt be rotated

**Actual behavior:**
Stairs are rotated by 90 degrees

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by wilhelmines** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12232915/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12232916/Player-prev.log)

**Comment by D3nnis3n** [comment]
We do not support migration to Update 10, as with most major updates but we'll see what we can do.

**Comment by D3nnis3n** [comment]
Closing this issue, it's impossible to migrate these, as the core files for them changed.
