### ISSUE TITLE
Unable to play local host game

### ISSUE THREAD

**Issue by RevSteveW** [StrangeLoopGames/EcoIssues#23933]
I have just tried to create a single player, locally hosted work.  The world was created, and I can interact with it.  I can gather pumpkins etc without a problem.  As soon as I place the tent as my first base however the "connection" is lost, and the game eventually crashes back to the main menu.  I've verified the files on Steam with no issues.  I have no mods installed. I've tried to create another world, with the same problem.  Client and Server logs attached.
[log_230731095653.log](https://github.com/StrangeLoopGames/EcoIssues/files/12222307/log_230731095653.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12222316/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12222317/Player-prev.log)

**Comment by D3nnis3n** [comment]
Unable to reproduce, create a new issue if it happens again.
