### ISSUE TITLE
USER ISSUE: Currency Transfers

### ISSUE THREAD

**Issue by Pacmud** [StrangeLoopGames/EcoIssues#23932]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-72

**Steps to Reproduce:**
Open economy viewer, try make a transaction. Trying to open any of the dropdown menu, [currency, source account, target account], would not open the dropdown menu. Only a small search bar will appear in top left part of the screen but does nothing. Cannot make any transactions at all.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
