### ISSUE TITLE
Build misplacement due to animation delay

### ISSUE THREAD

**Issue by dmdelor** [StrangeLoopGames/EcoIssues#23941]
**User Id:** (Not logged user)
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
Take out the hammer and attempt to build something, but look in a different direction as you're placing it.  The thing being constructed will be placed where you're looking after the (rather significant) animation delay rather than where you clicked to place it.

**Expected behavior:**
Item should be placed where it was when I clicked the mouse.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Comment by dmdelor** [comment]
Axes do this when cutting wood too... sometimes.  Sometimes they cut instantly at the start of the button click before the animation visibly starts playing, and it's hard to re-create but occasionally they'll cut at the start AND the end of the animation.  I assume there's a lot of other actions this applies to too.

**Comment by dmdelor** [comment]
If that's true, versus just "expected and we don't have the resources to fix it," you should change your intent.  Nobody designs a mouse-driven interface around the concept that when a user clicks the mouse, their intent is that they want the system to query where the mouse is a half second later and interpret that as the thing they want to click on, for obvious reasons.

**Comment by D3nnis3n** [comment]
Actions are executed once the animation is done - this has never been different in Eco. It seems like you're expecting placement to happen the very moment you click, not when the animation is actually done, but that's how it works in Eco and is insofar intended. If you would want a different behaviour, that would be something for our suggestion tracker, but the behaviour at least as far as I could understand it with your description seems not like a bug.
