### ISSUE TITLE
Right click eat breaks toolbar/equipped item

### ISSUE THREAD

**Issue by dmdelor** [StrangeLoopGames/EcoIssues#23944]
**User Id:** (Not logged user)
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
Take out a tool, then hit TAB to enable mouse control and right-click eat some food.  You will see food in your character's hand, the toolbar will continue to show the selected tool, and left-clicking to use your item will neither use the tool nor eat the food.  (although it will trigger a food eating animation)  Additionally, you will be unable to re-equip the tool using its hotkey number.

**Expected behavior:**
IMHO, eating food with right-click should just use it and skip any animation.  However, if we must equip the item and go through the animation then right-click eating food should actually equip the item and trigger the animation instead of eating it with no animation and trapping the user in a broken toolbar/equipped item state.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Comment by dmdelor** [comment]
(amusingly, this can also leave you visually holding food you don't have in your inventory any more if you eat the last piece of food this way...)

**Comment by D3nnis3n** [comment]
This should be fixed.
