### ISSUE TITLE
Cant see players / Invisible players 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2394]
Joined greenleaf server to day and all i could see was floating names but no players

Please advise how to troubleshoot this more =P

**Comment by Fank** [comment]
We also got this multiple times, looks like it only appears to linux clients, that they dissapear

**Comment by Phlo123** [comment]
there is a issue with /dump command, it remove everything(blinkeyelids, hiphophips...)  but that is not the case on greenleaf because /dump is a admin command.  i just wanted to put this information out there 😄

**Comment by noblackthunder** [comment]
@Fank not only linux =) i got the same issue .. i think i have an idea why it might happen .. so not a big issues .. it seems to fix it self after some time ...

**Comment by RowanJones** [comment]
![yudodis](https://user-images.githubusercontent.com/30301814/31044849-cabedc08-a594-11e7-9215-fd712e109ada.jpg)

I am invisible!

**Comment by Fank** [comment]
#2418 contains reproductions steps
