### ISSUE TITLE
USER ISSUE: Cannot mining without looking away and looks back

### ISSUE THREAD

**Issue by NekofreedomDev** [StrangeLoopGames/EcoIssues#23940]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-74

**Steps to Reproduce:**
1. Mining stone like normal
2. Cannot mining that stone again until you look away and click on it.

**Expected behavior:**
Player can hold click to mine block continually until they release

**Actual behavior:**
Player need to look away from block/item to mine it again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, we didn't installed mod in play test

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
This bug is now fixed and will be patched in for ongoing Sea Otter playtest soonest possible. 
thank you for your reports @dmdelor & @NekofreedomDev
