### ISSUE TITLE
Playtest 79, Keep gettintg disconnected after removing a Town Stake

### ISSUE THREAD

**Issue by keenkrozzy** [StrangeLoopGames/EcoIssues#23946]
Crashed upon removing a town stake on sea otter for the town "Nowhere".

Now it takes 10+ tries to get reconnected, and then I keep getting disconnected after a minute or two. Attached is the disconnect log.

[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/12256735/log.txt)

**Comment by keenkrozzy** [comment]
I tried Restarting ECO, Restarting Steam, and then Verifying Game Files through steam, but the issue persisted. 
Restarting my PC seems to have resolved it though.

**Comment by D3nnis3n** [comment]
This should be fixed.
