### ISSUE TITLE
USER ISSUE: Unclaim menu kick

### ISSUE THREAD

**Issue by kozel** [StrangeLoopGames/EcoIssues#23942]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-74

**Steps to Reproduce:**
Want to reposition settlement claim stake1. Game tells you that you have to unclaim plots one by one.2. You do it.3. Boom menu kick, unable to log in again

**Expected behavior:**
Not do that.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Duplicate [#23931](https://github.com/StrangeLoopGames/EcoIssues/issues/23931)
