### ISSUE TITLE
USER ISSUE: Why i was banned?

### ISSUE THREAD

**Issue by Stillwut** [StrangeLoopGames/EcoIssues#23949]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Why?

**Expected behavior:**
i do nothing

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

You have been banned from this server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can request ban appeals via DM to me on Discord or support@strangeloopgames.com
