### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Maxafrost** [StrangeLoopGames/EcoIssues#23953]
\
**User Id: (slg132583)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does
 the issue happen when no mods are installed?:**

**Please provide log 
files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12268880/Player.log)
[log_230806090946.log](https://github.com/StrangeLoopGames/EcoIssues/files/12268883/log_230806090946.log)

**Comment by D3nnis3n** [comment]
This is a local networking problem, make sure you are not using any VPN and turn off any security software. It's also known that Starlink does currently not work with Eco. For further assistance please reach out to support@strangeloopgames.com.
