### ISSUE TITLE
USER ISSUE: I absolutely own eco

### ISSUE THREAD

**Issue by SplatterTank** [StrangeLoopGames/EcoIssues#23957]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
1. Turn on game2. Try to log into server

**Expected behavior:**
I get into the server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
