### ISSUE TITLE
USER ISSUE: Join Server

### ISSUE THREAD

**Issue by Mausi117** [StrangeLoopGames/EcoIssues#23958]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
Join Server

**Expected behavior:**
Should join the Server

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
