### ISSUE TITLE
USER ISSUE: Unable to log in 

### ISSUE THREAD

**Issue by Sararainmaker** [StrangeLoopGames/EcoIssues#23959]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
1. Log In to any server.

**Expected behavior:**
Let me log in :)

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
