### ISSUE TITLE
USER ISSUE: Can't join server

### ISSUE THREAD

**Issue by ZigmantasD** [StrangeLoopGames/EcoIssues#23956]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
After some time got kicked out of server for login issue and now i'm not able to join.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ZigmantasD** [comment]
https://steamcommunity.com/id/ZigmantasDuoba/
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/12789824/ad2ab246-5221-44fd-b1c0-2bbce8f54b01)

**Comment by D3nnis3n** [comment]
Fixed.
