### ISSUE TITLE
USER ISSUE: Disconnect and unable to log back in, "User does not own Eco"

### ISSUE THREAD

**Issue by BGSwor** [StrangeLoopGames/EcoIssues#23960]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
Tried to start up our Dev build world that myself and my 2 kids have been building over the last 2 days, we all have bought Eco on 3 separate computers, but one by one they disconnected, with this message, after playing for ~9 hours on this server of just us.

It just happened to myself now as well, and we can't start our world again

**Expected behavior:**
loaded the world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, just the beta build vanillaplaytest - 10.0 Playtest - Sea Otter

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
