### ISSUE TITLE
USER ISSUE: User does not own Eco

### ISSUE THREAD

**Issue by Ighnot** [StrangeLoopGames/EcoIssues#23961]
\
**User Id: ()**
**Version:** 0.10.0.0 beta playtest-79

**Steps to Reproduce:**
Log in to any server	

**Expected behavior:**
It should have logged me in.  I do own Eco.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>User does not own Eco</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
