### ISSUE TITLE
USER ISSUE: Не могу войти в игру

### ISSUE THREAD

**Issue by LapkaDocD** [StrangeLoopGames/EcoIssues#23964]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
после входа в учетную запись вылазит эта ошибка

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Failed to login

Unable to complete SSL connection
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
на чистом клиенте без дополнительных модификаций

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a networking issue, assuming you are from russia, try using a VPN. Many providers in russia block cloudflare, which we use for all of our services, often leading to such issues.
