### ISSUE TITLE
USER ISSUE: Failed auth

### ISSUE THREAD

**Issue by teagan75** [StrangeLoopGames/EcoIssues#23966]
\
**User Id: slg231450
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
load singleplayer game

**Expected behavior:**
should be able to load a new world in

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by teagan75** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/12485764/d2e6fd97-5d79-445a-94e5-c25652f8a04e)

**Comment by teagan75** [comment]
[log_230813122015.log](https://github.com/StrangeLoopGames/EcoIssues/files/12330024/log_230813122015.log)

**Comment by teagan75** [comment]
I’ve done everything on my end. Removed mods. Validated files. Gone back a version. I don’t know what else to do

**Comment by teagan75** [comment]
I uninstalled and reinstalled and have the same issue. It is only when I try to start a local sp game. I am able to play on the server I play on. It has a lot of mods too so that’s not the issue.

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach authentication servers. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to support@strangeloopgames.com. This is not a bug, though.
