### ISSUE TITLE
USER ISSUE: keine Serververbindung

### ISSUE THREAD

**Issue by Vogelsang18** [StrangeLoopGames/EcoIssues#23973]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
jeder Versuch ins Spiel zu kommen endet im Ladebildschirm.
	Verbinden mit Server
          Welt wird betreten
ist das Ende des Ladevorgangs und bleibt so stundenlang

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Vom Benutzer abgebrochen
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ich nutze keinerlei  Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Vogelsang18** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/12359595/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12359597/Player-prev.log)

**Comment by D3nnis3n** [comment]
Leider ist in dem Logfile kein Fehler, da der Vorgang durch den Spieler abgebrochen wurde. Das Logfile zeigt aber, dass der verwendete PC die Mindestanforderungen für Eco nicht erfüllt - es ist daher unwahrscheinlich, das Spiel damit ans Laufen zu bekommen.
