### ISSUE TITLE
USER ISSUE: Getting Crashed ingame...

### ISSUE THREAD

**Issue by Leonardjaeg** [StrangeLoopGames/EcoIssues#23978]
[](url)I get midgame Crashes.
 Playing for a bit and then a small Unity window opens and after 1-2 sec game crashes.
User Id: (Not logged user)

Do you have mods installed? Does the issue happen when no mods are installed?:
yes [](url)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12372346/Player.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12372351/Player.log)

**Comment by Leonardjaeg** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12372353/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12372354/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi @Leonardjaeg 

Thank you for submitting this bug report. Unfortunately, we are unable to determine what's causing the crash for you with the logs you have provided. Have you tried verifying the integrity of the game files using Steam?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
