### ISSUE TITLE
USER ISSUE: Performance

### ISSUE THREAD

**Issue by Yodaluc** [StrangeLoopGames/EcoIssues#23971]
\
**User Id: (slg143992)**
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
1. Démarrer le jeu
2. mettre tous les paramétre graphique au minimum
4. bloquer les fps max a 60 FPS
3. ce déplacer sur une planéte

**Expected behavior:**
Je posséde un ordinateur portable avec 16Go de ram, un I7-8750H et une nvidia 1070. En théorie cette ordinateur est loin d'étre mauvais, il fait tourner une grande parti des jeu en qualité maximal. 

J'attend donc avoir une stabilité graphique a 60FPS sans trop de probléme sur tous les jeux aprés quelque réglage graphique si necessaire. Cependant dans cette version du jeu, lorsque je met tous les paramétre graphique au minimum (c'est à dire des graphisme des années 80), j'observe des chutes réguliére de fps allant sous les 30 voir 20 FPS. Aprés avoir observer les status de mon pc il s'avére que le jeu utilise en permance 50% de mon CPU et 5Go de ram peu importe ce que je fait. et la carte graphique ne semble pas dépasser les 50% d'utilisation en pique. 

D'un autre coté ma carte graphique ne dépasse pas les 50°C et n'est donc absolument pas surchargé. 

Le processeur quant à lui semble avoir un peu chaud au contraire, le probléme semble en effet venir de lui, avec une utilisation permanent a plus de 50% de ca capacité, même en idle, cela me semble normal. J'aimerais savoir si vous avez des solutions ou qu'es qui peu causer ce probléme handicapant ? 

**Actual behavior:**
Des graphisme stable a 60FPS 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your system is barely fulfilling the minimum requirements, an expectation of 60 fps is unrealistic until later down the road, when optimizations for such systems were made.
