### ISSUE TITLE
EcoPC_v0.10.0.0-beta-staging-2717 in Grafik nicht richtig dargestellt 

### ISSUE THREAD

**Issue by Saschalpmit** [StrangeLoopGames/EcoIssues#23976]
Guten Tag 
Fehler beim Menü wird die Grafik nicht richtig dargestellt und bei den Inventaren das gleiche und dieser Fehler passiert auch nur wenn man auf dem Server dann ein Objekt was neu hinzugefügt wurde und das ich mit dem Befehl "/build tech tree all" wurde.
Nach einem Neustart des Spiels ist das erstmal weg, aber wenn man wieder auf den Server geht, wo ich das bei mir ausprobiert habe, dann kommt der Fehler wieder.
Version EcoPC_v0.10.0.0-beta-staging-2715/2717
            EcoServerLinux_v0.10.0.0-beta-staging-2715/2717
![Screenshot 2023-08-16 215034](https://github.com/StrangeLoopGames/EcoIssues/assets/76811293/a40753a8-3618-41dc-aec8-10d25e6a620b)
![Screenshot 2023-08-16 215050](https://github.com/StrangeLoopGames/EcoIssues/assets/76811293/f604066c-462a-42ac-b019-982aa69acde9)

**Comment by D3nnis3n** [comment]
Wir akzeptieren keine Bugreports von staging Versionen, insbesondere nicht wenn developer commands verwendet wurden.
