### ISSUE TITLE
USER ISSUE: Campfire missing upon load

### ISSUE THREAD

**Issue by datnasus** [StrangeLoopGames/EcoIssues#23975]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-63

**Steps to Reproduce:**
Campfire not visible/selectable upon load. 		

**Expected behavior:**
Campfire should be selectable and the item campfire should be visible

**Actual behavior:**
Can see there is job on the campfire, but campfire is not selectable

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by datnasus** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12362884/Player-prev.log)

**Comment by D3nnis3n** [comment]
Outdated playtest version.
