### ISSUE TITLE
[0.10.0.0] [Linux] [AMD Radeon RX 5600 XT] Crashed game after start

### ISSUE THREAD

**Issue by linfo** [StrangeLoopGames/EcoIssues#23984]
After start game is crashed
Output to console:
`ERROR: ld.so: object '/home/*/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/*/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/*/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/*/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/*/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 13247 != 13243, skipping destruction (fork without exec?)
pid 13252 != 13243, skipping destruction (fork without exec?)
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
08/22 07:36:49 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230728184426)/tid(13375)
08/22 07:36:49 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(13375)
Game 382310 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 382310 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 382310 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / HTMLSurface
Game 382310 created interface STEAMHTTP_INTERFACE_VERSION003 / HTTP
Game 382310 created interface STEAMINVENTORY_INTERFACE_V003 / Inventory
Game 382310 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 382310 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 382310 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 382310 created interface STEAMREMOTEPLAY_INTERFACE_VERSION001 / RemotePlay
Game 382310 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION016 / RemoteStorage
Game 382310 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 382310 created interface STEAMUGC_INTERFACE_VERSION016 / UGC
Game 382310 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / UserStats
Game 382310 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 382310 created interface SteamController008 / 
Game 382310 created interface SteamFriends017 / Friends
Game 382310 created interface SteamInput006 / 
Game 382310 created interface SteamInput006 / Controller
Game 382310 created interface SteamMatchGameSearch001 / GameSearch
Game 382310 created interface SteamMatchMaking009 / Matchmaking
Game 382310 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 382310 created interface SteamNetworking006 / Networking
Game 382310 created interface SteamNetworkingMessages002 / 
Game 382310 created interface SteamNetworkingSockets012 / 
Game 382310 created interface SteamNetworkingUtils004 / 
Game 382310 created interface SteamParties002 / Parties
Game 382310 created interface SteamUser021 / User
Game 382310 created interface SteamUtils010 / 
Game 382310 created interface SteamUtils010 / Utils
Game 382310 method call count for IClientNetworkingSocketsSerialized::GetSTUNServer : 2
Game 382310 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicketCount : 1
Game 382310 method call count for IClientNetworkingSocketsSerialized::GetCertAsync : 1
Game 382310 method call count for IClientHTTP::ReleaseHTTPRequest : 1
Game 382310 method call count for IClientHTTP::SendHTTPRequest : 1
Game 382310 method call count for IClientHTTP::SetHTTPRequestHeaderValue : 1
Game 382310 method call count for IClientHTTP::CreateHTTPRequest : 1
Game 382310 method call count for IClientRemoteStorage::FileExists : 1
Game 382310 method call count for IClientUserStats::RequestCurrentStats : 1
Game 382310 method call count for IClientAppManager::GetAppStateInfo : 1
Game 382310 method call count for IClientUtils::RecordSteamInterfaceCreation : 32
Game 382310 method call count for IClientUtils::InitFilterText : 1
Game 382310 method call count for IClientUtils::IsSteamChina : 1
Game 382310 method call count for IClientUtils::GetLauncherType : 1
Game 382310 method call count for IClientUtils::GetAPICallResult : 2
Game 382310 method call count for IClientUtils::GetAppID : 35
Game 382310 method call count for IClientUtils::GetServerRealTime : 3
Game 382310 method call count for IClientFriends::ClearRichPresence : 2
Game 382310 method call count for IClientFriends::SetRichPresence : 3
Game 382310 method call count for IClientUser::RequestEncryptedAppTicket : 1
Game 382310 method call count for IClientUser::GetSteamID : 3
Game 382310 method call count for IClientUser::BLoggedOn : 1
Uploaded AppInterfaceStats to Steam

(process:13375): GLib-GObject-CRITICAL **: 07:37:07.948: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`

Computer:
OS: openSUSE Tumbleweed 20230819
KDE Plasma: 5.27.7
KDE Frameworks: 5.109.0
Qt: 5.15.10
Kernel: 6.4.11-1-default (64-бита)
Graphic platform: X11
CPU: 8 × Genuine Intel® CPU 6400t @ 2.20GHz
Memory: 31,3 ГиБ
GPU: AMD Radeon RX 5600 XT

**Comment by D3nnis3n** [comment]
We don't officially support linux and macos for Eco. During playtest issue reports with unsupported systems will unfortunately not be accepted.
