### ISSUE TITLE
USER ISSUE: claim stake game breaker

### ISSUE THREAD

**Issue by medic-crypto** [StrangeLoopGames/EcoIssues#23982]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
1.have wood stone or any carrying item in hand
2. have a stake claim in hand
3. attemt to place steak claim

**Expected behavior:**
claim stake is placed as normal

**Actual behavior:**
server desync
claim stake disapears
unable to interact with anything

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
