### ISSUE TITLE
Moved items prevent placement in previous location

### ISSUE THREAD

**Issue by dmdelor** [StrangeLoopGames/EcoIssues#23988]
**User Id:** (Not logged user)
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
Move an item such as a door using the hammer and CTRL-left click.  Try to place another item where the first item previously was.  You will be unable to.

This appears to be server side- the client logging out and in will not fix it, but if you shut down and restart the server the space becomes available again.

**Expected behavior:**
Once moved, the the empty space an item formerly occupied should not block item placement.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Comment by D3nnis3n** [comment]
Outdated playtest version.
