### ISSUE TITLE
USER ISSUE: mining problem

### ISSUE THREAD

**Issue by ikubuki** [StrangeLoopGames/EcoIssues#23995]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-107

**Steps to Reproduce:**
pickaxe
1. selecet pickaxe
2. mine stone
3. pick up stone by press E
4. can't mine any stone while carry stone
shovel
1. selecet shovel
2. dig up dirt by left click
3. place dirt by right click
4. start pick up dirt after place without left click

**Expected behavior:**
pickaxe
1. can mine stone while carry objected
shovel
1.don't pick up any oblected after place objected with shovel without input from user

**Actual behavior:**
pickaxe
1. can't mine stone while carry stone
shovel
1. pick up dirt after place dirt without input from user

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mod installed in my PC

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
