### ISSUE TITLE
All stockpiles destroyed upon migration

### ISSUE THREAD

**Issue by dmdelor** [StrangeLoopGames/EcoIssues#23994]
**User Id:** (Not logged user)
**Version:** 0.10.0.0 beta playtest-107

**Steps to Reproduce:**
 This can't be re-created by a Steam user anymore because the previous branch is gone, but I was running a server on the update 10 publictest branch.  It was up to date as of yesterday, -95 or -97 or whatever the latest release was.  This morning, that branch was gone, so I switched to the "white tiger" branch as the only update 10 version available on Steam.  Upon rejoining the server, all of my storage containers have nothing in them even though the stockpiles visibly still contain the stuff they used to have.

**Expected behavior:**
  If this was a known update that broke past save compatibility file under "known issue", although some warning and the option to stick to the previous version and not lose 100+ hours of play over the past month would have been nice.  Otherwise, obviously, updating server versions should not significantly break the world state.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Migration Log File**
[2023-08-24.log](https://github.com/StrangeLoopGames/EcoIssues/files/12433784/2023-08-24.log)

**Comment by D3nnis3n** [comment]
Not a bug, we specifically stated that playtest is NOT suitable for hosting private servers at this point and break at any time. This will not be the last time with breaking changes either.
