### ISSUE TITLE
Enhancement: Add a reticle/crosshair

### ISSUE THREAD

**Issue by dreatern** [StrangeLoopGames/EcoIssues#2399]
As recommended by @Metachronism on Discord, I'm posting it here copied from discord

 

> This should be included as an option by default since it is one of the biggest design flaws in the game.
On several occasions I have seen people complaining about the lack of it. One updating after another and no sign of intention to add such a simple and useful element.
The game is in first person and there is a lot of interaction with everything. selection can be inaccurate with a great chance of positioning failure due to lack of a reticle in conjunction with the minimum lag.
Here https://i.imgur.com/BoaESc1.jpg is a image if you do not know what it is, with 3 examples, but there are many ways to create it.

since this affects immensely the game experience because this is UX, it is something very important.

**Comment by Conchipedia** [comment]
i asked this ages ago, if i remember correctly the reason a crosshair was hard to do is because of the curvature of the world, so not really able to have a fixed point in space

**Comment by dreatern** [comment]
Hi @Conchipedia,
Well, it works 100% if you use any overlay software to add a simulated reticle/crosshair, regardless of the game world curvature, the game window will always have a center because it's flat and there is always a hit point.

Take a look
One of the many ways to overlay https://www.youtube.com/watch?v=RkBxOpyxFNs
You can also use Overwolf

The problem is to always have to use an additional app for something so simple which could be included in the game in the simplest form as an experimental feature activated by code If the problem of curvature is something so serious.
In general everyone is playing on maps so large that curvature in most cases is not visible

**Comment by MarjieAVolk** [comment]
Crosshairs are made significantly more difficult by the curvature of the world.  Not to say that it's impossible to implement.

**Comment by dreatern** [comment]
@MarjieAVolk I can understand the world curvature but I cannot understand why a simple central dot is difficult.  

My suggestion here is to have a central point, a dot or something to guide the screen center (https://i.imgur.com/BoaESc1.jpg).
Just a unity canvas with a little dot in the center of the screen.
When you use a bow, a giant central crosshair appears, so it is possible to have a little dot all the time as a center guide.

As I said before, I'm using it with an overlay app https://gfycat.com/OrganicDecentConey.   
Every interaction, mining, dig, pick up, etc is close to the camera, there is no curvature, it is flat. 
The reticle only guides me so I always know where the center is (hit point)

The lack of a center dot, cross, square, mark, etc. makes everything less accurate. 
Digging is a good example
Most of the time you try to dig in a place and end up digging another, you try to place the dirt in a place and the dirt goes to another place because we don't have a center guide.
When I use the overlay, I never miss place/dig/build because I know exactly where I'm pointing.

**Comment by MarjieAVolk** [comment]
Okay, good to know a simple overlay feels good enough to you, I'm not sure whether we've tried it out or not.

An overlay is not difficult, what is difficult is making the overlay match the curvature - with a simple one like you have, it will be less accurate the further away the thing you are targeting is.

**Comment by SeanAtr0n** [comment]
IMO the problem with https://gfycat.com/OrganicDecentConey is the lag.

Ideally there shouldn't be a delay between moving the cursor and a new highlight/block preview showing. In that case you don't need a crosshair. We could potentially do some client-side prediction to speed up highlights/block previews when lag is high.

**Comment by dreatern** [comment]
@SeanAtr0n Yes, the problem was the lag plus I used ShareX to record the gif
Here you can see it without lag or delay https://streamable.com/o7362

**Comment by SeanAtr0n** [comment]
Fixed in staging
