### ISSUE TITLE
clouds-22USER ISSUE: 

### ISSUE THREAD

**Issue by CLOUDS-22** [StrangeLoopGames/EcoIssues#23993]
\
**User Id: ()**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid username or password.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not a bug, account details wrong. Reach out to support@strangeloopgames.com if you need help restoring access to your account.
