### ISSUE TITLE
you have to be online to play privately? why?

### ISSUE THREAD

**Issue by Eclipse8264** [StrangeLoopGames/EcoIssues#23999]
(my posts on steam from my Discussion)
1) why are private worlds acting like your playing online? i'm not looking to play on a server on my worlds, and private played worlds can still kick you out for losing being online are it getting slow.
i have to wait for the world to be maed, then load, then play a short time befour getting kicked out of my world, then loading it all up again and doing that loop over and over and over. why, what is the point here?

2) not all players want to play online all the time, and i can play for the best part of 30 seconds befour being kicked out. halo uses anti-cheat and multiplayer, but you can play solo without getting kicked out of your own solo game.

3) all i do once in the world is gather some food and placed the starting tint, then tryed to pick it back up to turn it around, and the game kicks me. i have to load the world and do it all over again.
that is it, over and over.

(Discussion is here)
https://steamcommunity.com/app/382310/discussions/7/3811787666535016110/?tscn=1693075080

(requested logs)
[log_230820101415.log](https://github.com/StrangeLoopGames/EcoIssues/files/12447118/log_230820101415.log)
[log_230820102756.log](https://github.com/StrangeLoopGames/EcoIssues/files/12447119/log_230820102756.log)

**Comment by D3nnis3n** [comment]
There is a error in your log:

[22:17:54.802] [42] [Error] [Eco] System.ComponentModel.Win32Exception: An error occurred trying to start process 'netsh' with working directory 'F:\(Steam)\steamapps\common\Eco\Eco_Data\Server'. The operation was canceled by the user.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Eco.Plugins.Networking.Firewall.AddRuleAsAdmin(IRule rule)
   at Eco.Plugins.Networking.Firewall.AddRule(IRule rule)
   at Eco.Plugins.Networking.Firewall.EnsureRule(String serviceName, ProtocolType protocolType, Int32 port)
   
It seems something is blocking Eco to open the respective ports on firewall. Is there any security software you use or any special settings that could prevent Eco to make a connection?

**Comment by Eclipse8264** [comment]
i use AVG (free), but i didn't show a thing once i closed the game.

**Comment by D3nnis3n** [comment]
You'll need to fully disable / uninstall your antivirus and check again, it's well known that antivirus software doesn't play well with small indie games. It can help to report a false positive.

**Comment by D3nnis3n** [comment]
Closing, no further information provided and no hint at a bug.
