### ISSUE TITLE
USER ISSUE: Excavator don't dig

### ISSUE THREAD

**Issue by RedAlex** [StrangeLoopGames/EcoIssues#23990]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
Tried to dig with excavator not working

**Expected behavior:**
Remove soil where the bucket touches and store it in the excavator

**Actual behavior:**
Nothing happens the bucket presses the ground but does nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mod
![Eco_GmaCKX1Vgc](https://github.com/StrangeLoopGames/EcoIssues/assets/855331/8769d208-4577-4215-8745-5dff25b7a814)

**Comment by RedAlex** [comment]
Excavator can't place dirt too.
![Eco_95H8fpJpzH](https://github.com/StrangeLoopGames/EcoIssues/assets/855331/3301f9e5-c9e8-41fa-9b65-5310418b6364)

**Comment by D3nnis3n** [comment]
Outdated playtest version.
