### ISSUE TITLE
USER ISSUE: Tutorial not regognising that I have now build 2 rooms

### ISSUE THREAD

**Issue by tenpigs** [StrangeLoopGames/EcoIssues#23992]
\
**User Id: (slg110466)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Craft hewn logs
Place floor
Place walls
Place roof
Add Windows
Add doors
Repeat.
No gaps in walls or doors. Tutorial still tell me to craft logs and build a room

**Expected behavior:**
Tutorial should have completed after room no 1 was completed

**Actual behavior:**
Turorial has not updated

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Is the house claimed?

**Comment by D3nnis3n** [comment]
It needs to be claimed to work, it's part of the step before. :)
