### ISSUE TITLE
USER ISSUE: interaction bug

### ISSUE THREAD

**Issue by captinfubuki** [StrangeLoopGames/EcoIssues#23991]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-95

**Steps to Reproduce:**
play for about a hour then you wont be able to interact with cars and boats 

**Expected behavior:**
it should still let me interact and drive them 

**Actual behavior:**
they wont highlight and i cant drive them or interact with thier inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods   and i dont know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Outdated playtest version.
