### ISSUE TITLE
Invitations to Existing Accounts not working

### ISSUE THREAD

**Issue by Treasuryofwe** [StrangeLoopGames/EcoIssues#23998]
I have an existing Eco Account and was gifted an invite via the same email that's connected to my account. - The "log-in" link doesn't work. It opens my Eco account but still says I do not own the game. 

How do I fix this?

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143289153/cbc1b54f-00c9-4448-a08a-8b26aeb7eb22)

**Comment by D3nnis3n** [comment]
Reach out to support@strangeloopgames.com, they'll deal with that.
