### ISSUE TITLE
Building requirement issues

### ISSUE THREAD

**Issue by g1franc** [StrangeLoopGames/EcoIssues#24]
On the screenshot we can see I can finish the building at it show a volume of huge value (max_int ?) even if i'm still building it

![image](https://cloud.githubusercontent.com/assets/1684721/11702820/07e58e92-9eda-11e5-9cb9-2e554789d44a.png)

Version is 
![image](https://cloud.githubusercontent.com/assets/1684721/11702832/1dcdc26a-9eda-11e5-9d98-380106d13b24.png)

**Comment by nfullersl** [comment]
fixed
