### ISSUE TITLE
USER ISSUE: Cannot shoot an Arrow

### ISSUE THREAD

**Issue by datnasus** [StrangeLoopGames/EcoIssues#24002]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-107

**Steps to Reproduce:**
Load game, draw error, shoot at anything, game crashes. 
This occurs for both myself and a guest

**Expected behavior:**
Game should continue		

**Actual behavior:**
Arrow releases and then game ends

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-fil
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12448529/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12448530/Player-prev.log)
e

**Comment by da-rein** [comment]
Same error for me.

A shot with an arrow takes me back to the main menu.
[error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/12452185/error.txt)

**Comment by da-rein** [comment]
Fixed in version: Eco Server 0.10.0.0 beta playtest-117
(At least it works for me again.)
Thank you very much.

**Comment by D3nnis3n** [comment]
Fixed.
