### ISSUE TITLE
Food consumption values capped when using ALT to add labor

### ISSUE THREAD

**Issue by LocoTheDM** [StrangeLoopGames/EcoIssues#24005]
Ember Eco Server currently operating on 9.7.13

Reported by one of my players, I am unable to verify because I'm at the hospital with my wife.

Checking your stomach calories before and after each step, if adding labor to a work order by clicking on the button in a crafting table:
Clicking adds 100 calories to the job, burns 50 calories at level 7. (Normal)
Holding control adds 500 calories to a job, burns 250. (Normal)
Edit 2: Holding alt to add labor adds Stomach Capacity / (1 - labor reduction ) to the job, but subtracts only 2000 calories from the stomach. This means jobs over 4000 labor do not function as expected for costs.

Tested on:
Mortar at campfires
Milling rice
Cloth at tailoring table
Cellulose fiber at tailoring table 
Iron plates at screw press

Players involved in testing:
Stan
KhisanthMagus
Rod
Waltup369er

**Comment by LocoTheDM** [comment]
Follow-up from a player:
"i tested on a clean local server.  max calories with self improvement: 4500.  Logging level 7, so 50% reduction in labor on job.  1000 hewn logs: 15000 calorie job.  Alt clicked: applied 8000ish calories.  Cost 2000 calories."

**Comment by StanreGit** [comment]
TEST 1 Tailoring
Stomach content before laboring
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/088630f8-7359-4b2b-b5cf-267a307ced20)
The job being labored
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/6d91771c-4013-4536-8f00-af1d0cb7c09a)
Cals added using alt 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/95d69b32-27df-468d-a627-dbe323b428de)
Stomach content after 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/303809eb-2693-4e01-8212-9c0e5609c426)


TEST 2 Milling 
Stomach content before laboring
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/dcbdcb00-9a3c-40db-9307-8eba79b778e8)
The job being labored 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/19711aa9-f6a1-4597-9460-af87e11afdbb)
Cals added using alt 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/613fd2b4-bef7-4849-8472-60ce8ce04e23)
Content in stomach after
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/143562954/2e8e4990-6f28-4a17-9373-26ea45c4bc89)

**Comment by KhisanthMagus** [comment]
2 tests on a clean local server:
Test 1: 1000 campfires on a campsite, no skills
Initial calories:
![20230829183447_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/89b65a97-5ecf-4fb2-bf9f-d0d6e3cbee87)
Calories applied with alt+click:
![20230829183458_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/04f8a535-c7a4-4bc8-9305-1e85aa102941)
Remaining calories:
![20230829183502_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/a4af4083-790d-4ed1-8008-17c84b7dfda7)
Result: 2,999 calories applied with alt+click, 2,000 calories deducted from stomach.  This is a ~33% reduction in calorie cost with no skills.

Test 2: 1000 boards on carpentry bench, Carpentry level 7 Self Improvement level 7
Initial Calories:
![20230829182507_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/ba1f6d12-d3b5-49be-8397-08cd32b1541a)
Calories applied with alt+click = 8,499
![20230829182524_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/91a50da6-7cf2-42e7-a833-7139993d8b41)
Calories remaining 2499: 
![20230829182528_1](https://github.com/StrangeLoopGames/EcoIssues/assets/70003415/5e8cf610-2548-4f2e-8baf-4b9f330d7f4d)
Result: 8,499 calories applied with alt+click, 2000 calories deducted from stomach.  This is a ~75% reduction in calorie cost.

**Comment by KhisanthMagus** [comment]
After many rounds of testing, this is the best I can determine:
It uses your skill level discount and the calories in your stomach to determine how much labor to apply with alt+click.  This is working correctly.  However, it caps the amount of calories that can be deducted at 2000, regardless of how much is applied.

**Comment by LocoTheDM** [comment]
So, it's a bug on a normal server, which is going to be a problem for large jobs (crushing, hewn logs, smelting, etc) - 4500 capacity means 9000 labor for 2000 calories.

But on a server with extra stomach capacity it is absolutely crippling. 15000 size means 30000 labor for 2000 calories cost. I'm going to have to remove my mod until this is fixed, or prevent ALT usage with a law.

**Comment by LocoTheDM** [comment]
Looking into the code with devtier access... I have no clue what's causing stomach calories to only drop by 2000 on an alt click. WorkOrder.Labor feeds into Stomach.BurnCalories, and it looks like it should dump stomach contents to 0 with an ALT trigger. Something is hard capping Calorie change to 2000 on a clock, but I don't see it.

Hobbyist programmer has no clue, good luck with a trace I guess?

**Comment by D3nnis3n** [comment]
We do not plan to release another update for release aside of a last one for migration fixes shortly before release of Update 10, but I made staff aware they can accept your PR for that one in case it passes review. Technically this bug is already adressed though, hence I'm closing this issue.
