### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by BKgamesoficial** [StrangeLoopGames/EcoIssues#24003]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
fewsfjsfolsjf

**Expected behavior:**
sfeiks

**Actual behavior:**
ff

**Do you have mods installed? Does the issue happen when no mods are installed?:**
f

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
frwrwerwer
