### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by owaimer41** [StrangeLoopGames/EcoIssues#24000]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to login

Unknown Error
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Switch to the most recent version, that one is years old.
