### ISSUE TITLE
USER ISSUE: Orthographe

### ISSUE THREAD

**Issue by 0Wyzz0** [StrangeLoopGames/EcoIssues#24004]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Feu de camp -> cuisson viande

**Expected behavior:**
minuscule

**Actual behavior:**
minucule

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non, serveur officiel

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Translation issues with foreign translations need to be reported at https://crowdin.com/project/eco-by-strange-loop-games, as they are made by community members, not us.
