### ISSUE TITLE
Small wood cart will appear empty even with itens inside.

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#24007]
I have itens in my Small Wood Cart but I'm not seeing the items when I'm pulling the cart... Looks like the cart is always empty. Previous versions would have the same behavior of the stockpile. In this case, the logs, when moved to a stockpile will be displayed normally in the world.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/67368828/344f67e5-12ef-401c-ad92-9fcfe2246d0d)

Development Build - Whitetiger playtest

**Comment by D3nnis3n** [comment]
Tracked internally, thanks for reporting. This has been like that forever, though, so unlikely to be adressed during playtest.
