### ISSUE TITLE
Able to pick an non-empty Small Wood Cart

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#24009]
I had some dirt stored in my Small Wood Cart and GM Bill Taggers on White Tiger Playtest asked us to pick the card. Just hit the cart with the hammer.

I had 15 Hwen in my hand and some dirt stored in the cart.

I hit the cart with the hammer. I was able to "destroy the cart" and place it into my pocket.

Once I deployed the cart again. It was empty.

I think the correct behavior here would not me able to pick the cart since I didn't have room for pick the content of the cart

**Comment by D3nnis3n** [comment]
Thanks for reporting, will be fixed by https://github.com/StrangeLoopGames/Eco/pull/13024 in one of the next playtest updates.
