### ISSUE TITLE
USER ISSUE: Bug on Launch the Game

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#24012]
\
**User Id: (slg205663)**
**Version:** 0.10.0.0 beta playtest-120

**Steps to Reproduce:**
1. Turn ON PC
2. Open Steam
3. Open ECO
4.  CONTINUE on [SLG] White Tiger - #36 - Official ECO Server (Playtest)
5. Respaw in the world

**Expected behavior:**
Be able to play.

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

But I do see 19 users and I already had a play of couple of hours without problems.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12491679/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12491680/Player-prev.log)

**Comment by D3nnis3n** [comment]
Network issue, not a bug.
