### ISSUE TITLE
USER ISSUE: Cant enter large canoe

### ISSUE THREAD

**Issue by AndriusRimk** [StrangeLoopGames/EcoIssues#24017]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-123

**Steps to Reproduce:**
Unknown, I am trying to enter the canoe and forced out. Can access the inventory

Note: I saw a red icon near the minimap, and this started happening after dropping me out

**Expected behavior:**
Click e to enter the canoe and move 	

**Actual behavior:**
Click e on canoe, and i am dismounted

**Do you have mods installed? Does the issue happen when no mods are installed?:**
WT no mods
[Player-prev.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12504123/Player-prev.zip)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by AndriusRimk** [comment]
Restarting the game helped, and the canoe was so far away that swimming got me to shore.

**Comment by D3nnis3n** [comment]
Should be fixed.
