### ISSUE TITLE
USER ISSUE: Town foundation when user joining crashes server

### ISSUE THREAD

**Issue by Gal1leox** [StrangeLoopGames/EcoIssues#24013]
\
**User Id: (slg36749)**
**Version:** 0.10.0.0 beta playtest-120

**Steps to Reproduce:**
When I invited a user to our town, He came over to the town foundation, clicked the citizen tab clicked join and the entire white tiger server crashed

**Expected behavior:**
he should join our town

**Actual behavior:**
crashed the server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
this is on white tiger
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12492123/Player-prev.log)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12492122/Player.log)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.

**Comment by Whitey89** [comment]
@D3nnis3n - Issues seems to be ongoing as he just tried again and server crashed.
