### ISSUE TITLE
Country stake showing -1 plot left

### ISSUE THREAD

**Issue by Altaric** [StrangeLoopGames/EcoIssues#24011]
I've gotten my hands on a country stake, I placed it down but then it says plots available:-1. I add 4 LCP, still -1.
I can hammer it down (didn't try to unclaim the initial plot as instructed in Dennis' announcement) and got the 4 LCP and stake back, but the plot remains claimed in game
location (317, 64, 102) on WT

**Comment by D3nnis3n** [comment]
This should be fixed in latest playtest.
