### ISSUE TITLE
USER ISSUE: HTTP connection issue

### ISSUE THREAD

**Issue by Gal1leox** [StrangeLoopGames/EcoIssues#24024]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-123

**Steps to Reproduce:**
open the game

**Expected behavior:**
popped up game menu

**Actual behavior:**
The following error message popped up:
```
HTTP/1.1 503 Service Unavailable
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
