### ISSUE TITLE
USSER ISSUE: Homestead and city stake claims

### ISSUE THREAD

**Issue by Kertazy** [StrangeLoopGames/EcoIssues#24021]
User Id: (Not logged user)
Version: WT playtest

Steps to Reproduce:
Went to move my homestead stake but picked up instead  when replaced down lost all but 1 claim and when town claims added was unable to expand claim as the area was showing red but if you pick it up it leaves plot claimed.If you use a town stake same. 

Expected behavior:
Land stake should be placed in back pack with claims then placed back down to reclaim area.

Actual behavior:
Makes it so you have multiple claims making any housing bonus you have null en void. This has happened to a few people on the server. Jagon had it happen to him but it has been fixed.

![Screenshot 2023-09-03 161920](https://github.com/StrangeLoopGames/EcoIssues/assets/143924081/b2c04e80-9fe4-43ed-a304-24e23cec2842)

**Comment by Kertazy** [comment]
Ended up placing my homestead stake on one of my town plot claims and it turned it into a homestead and showed that i had 1/20 plots claimed and was able to start reclaiming the area

**Comment by D3nnis3n** [comment]
This should be fixed in latest playtest.
