### ISSUE TITLE
My server does not start big error 

### ISSUE THREAD

**Issue by plex68** [StrangeLoopGames/EcoIssues#24026]
Good morning;

My server no longer wants to start since last night, during the automatic restart the server generates an error that we had not noticed before.

The server is used with words, however no modifications were made to the server file during its execution. Those why we don't understand why it restarts anymore.

I tried absolutely everything locally to restart the backup but impossible.

I come to you because you are my only hope of not losing all the work done on the backup but also of succeeding in restarting the server with the players.

I'll leave you with the log file and the list of words and modifications to make to the server.

Please help us get our game back!

AlteredMods
Elixr Mods pack
NidToolbox
UserCode : ERC-Garden; ERC-Gates; ERC-HewnLogExpansion; GasPump; Painting; Disassembly; RoadExtension; RoadObjects; RoadSigns; WorldEdit; BeekeepingMod

I am able to provide you with all server files, a complete copy or the backup if necessary.
[log_230906022918.log](https://github.com/StrangeLoopGames/EcoIssues/files/12537243/log_230906022918.log)

**Comment by D3nnis3n** [comment]
This is a corrupted save file and a highly modded game, the only way to restore the state is reloading a backup that was not yet corrupted. We unfortunately cannot restore modded games.
