### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by BritishGamingHub** [StrangeLoopGames/EcoIssues#24020]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-123

**Steps to Reproduce:**
i tried to join my dedi server

**Expected behavior:**
let me connect

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Should be fixed.
