### ISSUE TITLE
Building outline doesn't show when building over some plants

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2402]
Works for salal
![image](https://user-images.githubusercontent.com/3536496/31037659-f8cd4e04-a526-11e7-9601-405a6ed15698.png)

Not for tomatoes
![image](https://user-images.githubusercontent.com/3536496/31037664-ff2fa864-a526-11e7-995b-474cc50c68aa.png)

Verify it works properly for all plants

**Comment by MarjieAVolk** [comment]
looks like it's because of targeting

**Comment by SeanAtr0n** [comment]
You can pick tomatoes without a tool and picking takes priority over building... imo this is correct behavior

**Comment by SeanAtr0n** [comment]
guess this isn't too confusing
![image](https://user-images.githubusercontent.com/774628/31040275-2d6f50ea-a53a-11e7-8aa3-77b2e694dbee.png)
