### ISSUE TITLE
USER ISSUE: river are little buged

### ISSUE THREAD

**Issue by 1Electrum** [StrangeLoopGames/EcoIssues#24039]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-134

**Steps to Reproduce:**
just look for river on random created world

**Expected behavior:**
just normal fine looking rivers

**Actual behavior:**
wird generation bugs floating fish and missing water

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no no mods

![20230915004454_1](https://github.com/StrangeLoopGames/EcoIssues/assets/145073398/ace6da62-42ce-41e6-bca3-ec1ab9222a2d)

**Comment by D3nnis3n** [comment]
Should be fixed.
