### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by hehe677** [StrangeLoopGames/EcoIssues#24031]
\
**User Id: ()**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
接下来的错误消息弹窗：
```
无效的用户名或密码。
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com if you have a problem recovering your account data.
