### ISSUE TITLE
USER ISSUE: Cannot open world

### ISSUE THREAD

**Issue by Bubz0288** [StrangeLoopGames/EcoIssues#24037]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. opened the game thru the "continue" button2. error happened.

**Expected behavior:**
opened up the world with no errors

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
If this is happening persistently, it's always a local network issue. Make sure to not have any antivirus software or VPN's installed and reach out to support@strangeloopgames.com if the issue is persisting, it's not a bug.
