### ISSUE TITLE
USER ISSUE: WT playtest v10 - Remove resident from claim 

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#24038]
\
**User Id: (slg28118)**
**Version:** 0.10.0.0 beta playtest-134

**Steps to Reproduce:**
Remove resident from claim.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.Components.HomesteadFoundationComponent.OnPickup(Player player</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be fixed in newest playtest versions.
