### ISSUE TITLE
ECO Erfahrungspunkte und Sterne

### ISSUE THREAD

**Issue by sg-claptraxx** [StrangeLoopGames/EcoIssues#24034]
Hallo zusammen mein problem liegt darin das ich im game erst ganz normal levelen konnte und dann auf einmal nicht mehr das die Erfahrungspunkte sowie die anzahl der Sterne wie sau an Rattern sind sprich am durchlaufen sind und bekomme dieses Problem nicht behoben
![Ashampoo_Snap_Mittwoch, 13  September 2023_19h54m32s_001_Eco](https://github.com/StrangeLoopGames/EcoIssues/assets/144066979/c323b2ce-bd55-4969-977c-8c6738ee11fd)

**Comment by D3nnis3n** [comment]
Bitte wende dich an support@strangeloopgames.com und hänge deinen Configs-Ordner in einer .zip Datei an, zu finden in Steam/steamapps/common/Eco/Eco_Data/Server.
