### ISSUE TITLE
USER ISSUE: Unclaim plot with plot claim 

### ISSUE THREAD

**Issue by valoudi** [StrangeLoopGames/EcoIssues#24032]
\
**User Id: (slg92643)**
**Version:** 0.10.0.0 beta playtest-131

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at E</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be fixed in newest playtest versions.
