### ISSUE TITLE
USER ISSUE: Workbenches gone after quiting and rejoining my own world

### ISSUE THREAD

**Issue by Noahmagnum** [StrangeLoopGames/EcoIssues#24035]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
i have no idea. but the hitboxes seem to still be there because i cannot place anything where my workbenches were. the workbenches in my house were the only ones that dissapeared.

**Expected behavior:**
It should have still been here

**Actual behavior:**
it dissapeared

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is fixed in Update 10.
