### ISSUE TITLE
Water spreading/replacing mechanics problems

### ISSUE THREAD

**Issue by elsid** [StrangeLoopGames/EcoIssues#24030]
**User Id**: elsid
**Version**: 0.10.0.0 beta playtest-131
**Server**: White Tiger

Is there a specific mechanics about how water changes when its tiles are replaces with other blocks? There is some weirdness with water I was trying to fix around my house. The issue I was trying to fix looks like a kind of water bump:

![water_bump](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/385181d7-9110-4cf5-96c4-23081238cc46)

![flooded_dock](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/621f2c3c-530e-4fe9-a28f-3f1e6ca5bf81)

To fix I cover the place with mortared stone starting with outer bounds:

![flood_fix](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/15388ede-0651-415f-9cf8-287135430975)

and then remove it:

![fixed_dock](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/b0dcb551-a143-4707-8460-d6ecf0eb87f7)

The problem is that in some places this breaks water surface rendering and leaves river shores "dry":

![shore_desert](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/3ed9f144-5c68-45cd-97fb-8b3f844be049)

![broken_water](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/3fa8b27b-f1f7-47a9-8678-3099d4bd736e)

Lower part of the shore is not covered by the water. Overall this makes it hard to build a dock on a river. I also can't place a canoe there:

![blocked_canoe](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/42a69ada-7e90-4408-ad37-ad9196ada9ce)

but can on the water bump:

![placed_canoe](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/e8f2a0ae-faf7-4ae1-89d3-f7ac4621256b)

Sailing to the place where it's not possible to place the canoe makes it float above the water surface:

![flying_canoe](https://github.com/StrangeLoopGames/EcoIssues/assets/764107/96c3c84d-c6fb-45a1-9f60-05519271b905)

The mentioned place is located at White Tiger server around 150, 64, 680.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/9971
