### ISSUE TITLE
USER ISSUE: No carga la partida

### ISSUE THREAD

**Issue by PowerKasaya** [StrangeLoopGames/EcoIssues#24041]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-145

**Steps to Reproduce:**
No me carga la partida.

**Expected behavior:**
Debería cargar la partida

**Actual behavior:**
Ha aparecido el siguiente error:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Items.WorldObjectItem.Place(Player player, Vector3i pos, Quaternion rotati</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Playtest-144 and following is not retroactively compatible with prior playtest versions and requires a new game.
