### ISSUE TITLE
Unable to connect to a server

### ISSUE THREAD

**Issue by ImperatorDecens** [StrangeLoopGames/EcoIssues#2404]
After having two successful days on my main server I was playing on - For some reason this morning it was lagging really bad without any internet issues on my end. I DC'd and it won't let me log back into that server.

I have been working with the Admins of the server and they even deleted my data on the server to no avail. I am able to log onto any other server ... just not 327th.  I was advised to create this ticket to see what can be done.

I uninstalled and reinstalled. I restarted my PC and router.

**Comment by RowanJones** [comment]
Server Co-Owner for the 327th here: The steps we took were:

1) ask the payer to uninstall/reinstall 6.0
2) deleted the player user file in our vultr host (8 gigs ram)
3) checked the player's internet connection
4) restarted server

we're flummoxed, we don't know why Decens can't log into us. He is the only user we have with this issue currently.

**Comment by SeanAtr0n** [comment]
Can you connect to other servers?

**Comment by ImperatorDecens** [comment]
Yes

**Comment by RowanJones** [comment]
If anyone can help us get Decens back to us that would be great. We don't know why this is happening. We've done everything to our knowledge to remedy this, except wipe the server. And obviously, we don't want to wipe when players are just getting established.

**Comment by SeanAtr0n** [comment]
Could you send us output_log.txt in  C:\Users\(username)\AppData\LocalLow\Strange Loop Games\ECO

**Comment by SeanAtr0n** [comment]
Make sure you open the game, try to connect to the server and close the game before sending the output log.

**Comment by metachronism** [comment]
the game save from the server and the name of the affected player will also help, if thats possible to stick on dropbox or otherwise

**Comment by ImperatorDecens** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1346079/output_log.txt)
Playername: ImperatorDecens

**Comment by ImperatorDecens** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1346082/output_log.txt)

Actually a much better log to use

**Comment by ImperatorDecens** [comment]
Caught exception: Caught exception invoking RPC CollideWithTerrain on TreeEntity!

Object reference not set to an instance of an object.


Stack:
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at TreeEntity.CollideWithTerrain(Player player, Vector3i position)

**Comment by ImperatorDecens** [comment]
I managed to join the server but upon trying to cut down a tree caused this exception.

**Comment by RowanJones** [comment]
We deleted the store (on a whim) and Decens was able to rejoin us:

https://github.com/StrangeLoopGames/EcoIssues/issues/2427

**Comment by ImperatorDecens** [comment]
Could it be a situation where if certain users with a different NAT type than mine might be screwy? I have a strict NAT type that usually when connecting with friends in parties -- Unless they or the host is Open, I cannot connect.

I do not know how this scales with hosted servers however.

**Comment by ImperatorDecens** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1354175/output_log.txt)

We tried having myself join in with nobody else on the server and it made it to 2% before stopping and booting me back to the server list -- It is showing I am joining the game and then leaving it.
Other servers -- Eco Nation, are working fine for me.

I live 8 hours from Chicago (Where the server is based -- I am the second closest.) I live in Ohio whereas the Eco nation is in United Kingdom.

**Comment by ImperatorDecens** [comment]
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC JobFinished on Contract!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.<>c.<ToDict>b__1_0(ItemStack x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.ToDict(IEnumerable`1 stackList)
   at Eco.Gameplay.Items.EnumerableItemStackExtensions.Contains(IEnumerable`1 stackList, IEnumerable`1 testList)
   at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.<Test>b__17_0(StorageComponent x)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.Gameplay.Economy.Contracts.ContractClauseItemsInContainer.Test(User contractor, User client)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Eco.Core.Utils.ResultExtensions.Merge(IEnumerable`1 list)
   at Eco.Gameplay.Economy.Contracts.Contract.JobFinished(Player player)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by ImperatorDecens** [comment]
This error popped up when I clicked on the job finished icon for a contract ----It kicked me out to the server list.

**Comment by MarjieAVolk** [comment]
" https://github.com/StrangeLoopGames/EcoIssues/files/1358035/output_log.txt

I try and log into our Server and I'm no longer able to. In the off chance I do connect I'm soon disconnected. I've tried deleting the C:\Users\Sarumann\AppData\LocalLow\Strange Loop Games folder. I've tried fresh game files. unplugging router/modem. Restarting my pc. Even having the server admin delete my character."
-- Siegeofavalo

"I will add that we see him log in, we see his char standing there and as long as he sits on the "entering World" screen it keeps his char in the game. As soon as he closes out of that it shows him logging off and his char disappears."
-- Dreconic

**Comment by MarjieAVolk** [comment]
Okay I think this bug is really big and has lots of different problems in it, some of which are already fixed (like the store login problem).

I'm going to at least move the contract exception posted by ImperatorDecens to a separate bug: https://github.com/StrangeLoopGames/EcoIssues/issues/2479

**Comment by metachronism** [comment]
usually when they get "stuck" on loading its because the client threw an exception, which breaks the normal login process.

this looks to have been related to the store specifically, so closing as that has been fixed in 6.0.1
