### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by jeanleroie** [StrangeLoopGames/EcoIssues#24042]
\
**User Id: ()**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Nom d'utilisateur ou mot de passe invalide.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please use the "Forgot Password" feature or reach out to support@strangeloopgames.com if you forgot your password.
