### ISSUE TITLE
USER ISSUE: Beta Build Fishing Rod Issues

### ISSUE THREAD

**Issue by conninator2000** [StrangeLoopGames/EcoIssues#24046]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-148

**Steps to Reproduce:**
1. Create a fishing rod
2. Equip and try to cast

**Expected behavior:**
Should cast the bobber to fish

**Actual behavior:**
The animation gets stuck and the bobber is never launched forward

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12678426/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12678427/Player-prev.log)

The fishing rod also takes on a slightly commical look in third person
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/68338085/d931c48c-74c1-448b-a111-05cbf9bab4a0)

**Comment by D3nnis3n** [comment]
Already fixed.
