### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by DerTanta** [StrangeLoopGames/EcoIssues#24049]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Ungültige Anmeldeinformationen.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by DerTanta** [comment]
Ich bitte um Hilfe bei dem Thema. Hab keine Ahnung woran es liegt.

**Comment by D3nnis3n** [comment]
Dieser Fehler ist, wenn er persistent auftritt, immer ein lokales Netzwerkproblem. Bitte sicherstellen, dass keine Antivirensoftware installiert ist, ebenso keine VPN-Software genutzt wird. Bei Weiterbestehen des Problems bitte an support@strangeloopgames.com schreiben, da dies kein Spielfehler ist.
