### ISSUE TITLE
USER ISSUE: Sand dug is placed as dirt

### ISSUE THREAD

**Issue by conninator2000** [StrangeLoopGames/EcoIssues#24044]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-148

**Steps to Reproduce:**
1. Create a new world with the beta, place the camp and grab the shovel
2. dig a piece of "desert sand"3. place it back down 

**Expected behavior:**
Should place a sand block

**Actual behavior:**
Places dirt

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12677503/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12677504/Player-prev.log)

**Comment by D3nnis3n** [comment]
This works as intended, desert sand IS a type of dirt.
