### ISSUE TITLE
USER ISSUE: spiel startet nicht

### ISSUE THREAD

**Issue by MadF72** [StrangeLoopGames/EcoIssues#24047]
\
**User Id: (slg225068)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
<size=150%>Verbindung fehlgeschlagen</size>

Vom Benutzer abgebrochen
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Leider fehlen die grundlegend notwendigen Informationen, der Hinweis sagt nichts weiter aus, als dass der Benutzer die Verbindung zum Server getrennt hat. Bitte mit mehr Informationen an support@strangeloopgames.com wenden, das ist wie dargestellt jedenfalls kein Fehler.
