### ISSUE TITLE
USER ISSUE: Can`t access spawn points

### ISSUE THREAD

**Issue by vlourie** [StrangeLoopGames/EcoIssues#24051]
\
**User Id: (slg226577)**
**Version:** 0.10.0.0 beta playtest-165

**Steps to Reproduce:**
1. Joined a new server

**Expected behavior:**
need to drag a globe to spawn at spawn point

**Actual behavior:**
Stuck at 0.0 without option to spawn

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, but don`t know which ones

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Known issue that was announced as known issue when playtest started.
