### ISSUE TITLE
Seaotter development branch: No map, not as a minimap and nothing happens on pressing m either

### ISSUE THREAD

**Issue by Dudelmicha2** [StrangeLoopGames/EcoIssues#24059]
[Eco1.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12809225/Eco1.zip)
[Eco2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12809221/Eco2.zip)
[Eco3.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12809223/Eco3.zip)
[Eco4.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12809224/Eco4.zip)
![20231004232146_1](https://github.com/StrangeLoopGames/EcoIssues/assets/147002422/cda229e3-739c-4bfd-bb3d-12c8e8f9f327)
As in 20231004232146_1.jpg I don#t have a minimap. I tried to attach my logfiles but they are to big so I needed to split them, since zip.001, zip.002 etc arent allowed to upload you need to rename the files
Eco1.zip --> "Eco.zip.001"
Eco2.zip --> "Eco.zip.002"
Eco3.zip --> "Eco.zip.003"
Eco4.zip --> "Eco.zip.004"

**Comment by Dudelmicha2** [comment]
I am Fray on Discord

**Comment by Dudelmicha2** [comment]
Problem fixed after relog

**Comment by D3nnis3n** [comment]
Reported internally as ECO-31031
