### ISSUE TITLE
Unable to start new  or rejoin existing solo game

### ISSUE THREAD

**Issue by Ohnix-Ahnul** [StrangeLoopGames/EcoIssues#24057]
Last Sunday night I closed down my solo Eco game and was perplexed to find a "Failed to connect to the local Server. ..." popup appear when I tried opening it the next morning.

After chasing multiple leads I find that there is an Unhandled Exception reference to something called "Eco.Shared" which it indicates it cannot find.

A bit more detail and a couple screen shots in the attachment..
[ECO Failure Document.docx](https://github.com/StrangeLoopGames/EcoIssues/files/12795265/ECO.Failure.Document.docx)

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com. The error description indicates a corrupted installation, not a bug.

**Comment by Ohnix-Ahnul** [comment]
Thnx for the response,

Tbc, I was simply reporting my experience and did not, in any universe, expect a solution ( or even a reasonable suggestion) from the community.

I’ve uninstalled/reinstalled multiple times, wiped Steam ECO and User/*/LocalLow/SLG folders each time and even cleaned the registry of pertinent entries.  The game reinstalls fine and was able to join some random multiplayer game(s) – but when it came to starting a solo game I get the ‘…cannot connect to server…’ popup.  And no log folder under Steam/*/ECO.   And trying to launch EcoServer.exe from the command prompt tells me that  it cannot find a file named “ Eco.Shared“ after reporting it experienced an “Unhandled exception.  System.IO.FileNotFoundException” tells me that something is not right in ECOland.

So, last week I uninstalled and wiped all ECO references on my PC and unfortunately will not be returning to extend my 4.3k hours on enjoyment.

Best of luck on adventures.

John Aichholz

Btw, and have a nice day.

**Comment by D3nnis3n** [comment]
Hence I asked you to reach out to support. A common cause for this is antivirus software that blocks access or removes files while being accessed, like most do, for example. Reinstalling will then not help at all, as as soon as the files are accessed it will be removed again. There is more reasons that can cause this, but it's never Eco. Support can help out with that.
