### ISSUE TITLE
USER ISSUE: SteamCMD

### ISSUE THREAD

**Issue by forestfire97** [StrangeLoopGames/EcoIssues#24053]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-169

**Steps to Reproduce:**
1. install server using steamCMD inside a linux docker with the install flag -beta soplaytest
2. make sure all settings and ports are set correctly.
3. set client version in steam to soplaytest
4. attempt to connect to server.

**Expected behavior:**
connect to game.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Version mismatched.
User version: 0.10.0.0 beta playtest-169
Server version: 0.10.0.0 beta playtest-165

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by forestfire97** [comment]
to add more information it is running in pterodactyl, a docker server management tool.

**Comment by D3nnis3n** [comment]
We don't currently provide up-to-date linux builds for every build during playtest to speed up build creation. Typically they will be synced, but there is no guarantee for that. Note the playtest is currently solely intended for Sea Otter.
