### ISSUE TITLE
USER ISSUE: erreur de charrette

### ISSUE THREAD

**Issue by sav73** [StrangeLoopGames/EcoIssues#24050]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-154

**Steps to Reproduce:**
remplir une charrette petite , tapez au marteau dessus jusque a retire le dernier objet dedans.

**Expected behavior:**
que la charrette reste visible et sur la terre

**Actual behavior:**
la charrette disparait avec le dernier materiel retire et atterir dans l inventaire ou disparait nul part 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended, when you can pickup the cart and all its contents, it will do so when hammering it - it's not a bug.
