### ISSUE TITLE
v10 SO playtest: Map is a Black Orb

### ISSUE THREAD

**Issue by MonteCrisply** [StrangeLoopGames/EcoIssues#24058]
This bug happened after the server restart. At first, the map wouldn't open up at all. I exited to main menu and rejoined the server. Now my map looks like this.
Someone mentioned that another person may have been discussing this issue and they were having trouble reproducing it, but I didn't see a similar issue open after a quick look through.

Uploading both player logs in case both may be useful.

![20231003214053_1](https://github.com/StrangeLoopGames/EcoIssues/assets/114702346/b4bddb92-3779-4730-a710-e8d36871276e)
![20231003214102_1](https://github.com/StrangeLoopGames/EcoIssues/assets/114702346/a67116ad-3f77-46e4-9cc0-4092017509a3)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12798803/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12798804/Player.log)

**Comment by D3nnis3n** [comment]
Reported internally as ECO-31031
