### ISSUE TITLE
USER ISSUE: Strange wording in description for "Hands"

### ISSUE THREAD

**Issue by Anarchynachos** [StrangeLoopGames/EcoIssues#24054]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Hover mouse over the word "Hands"

**Expected behavior:**
Maybe something like:"When you're not using tools for a job, you put these to work"
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12774537/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12774538/Player-prev.log)

**Actual behavior:**
"When you're not using tools are used for a job, you put these to work"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Added to internal typo list, closing.
