### ISSUE TITLE
USER ISSUE: No map

### ISSUE THREAD

**Issue by leoyulee** [StrangeLoopGames/EcoIssues#24060]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-174

**Steps to Reproduce:**
Logged on via fresh game

**Expected behavior:**
It should have a map that's openable and immediately viewable on the bottom right.

**Actual behavior:**
Instead it isn't seen anywhere and the "map" keybind doesn't do anything.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods as far as I'm aware. This is on Sea Otter.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by leoyulee** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825715/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825716/Player.log)

**Comment by leoyulee** [comment]
Re-logging partially fixes it. Instead, it appears black.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/56608247/6e975154-8160-4411-822f-dc107799e2f5)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/56608247
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/12825721/Player.log.copy.txt)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825722/Player.log)
/938f8faa-7c4f-412c-93d4-a9ee81303074)

**Comment by leoyulee** [comment]
![Capture](https://github.com/StrangeLoopGames/EcoIssues/assets/56608247/74afc129-d444-463d-a2aa-e596b7d2366f)

**Comment by leoyulee** [comment]
I've closed my game. to have the log file's timestamp be updated, and it went missing again.

I've re-logged into the server, and it's still gone.

I've re-logged once more, and now it's fine.

**Comment by leoyulee** [comment]
Latest logs, although the log's timestamp doesn't match the recent re-log attempt.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825738/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825739/Player.log)

**Comment by leoyulee** [comment]
I take it back, it's not fine. The map didn't render the world properly.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/56608247/cf0416c2-a4ba-4504-bfc8-a84c117638ac)

**Comment by leoyulee** [comment]
I've decided to relog once again, and it's normal now. Log time stamps don't seem to be updating, but here they are regardless.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/56608247/dd0761d0-7ed7-4903-b3cc-e2c1d63d0ca3)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825807/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12825808/Player.log)

**Comment by D3nnis3n** [comment]
This is already fixed, though the absence of icons on the map still persists and is handled here: https://github.com/StrangeLoopGames/EcoIssues/issues/24131
