### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by LBmaster001** [StrangeLoopGames/EcoIssues#24068]
\
**User Id: (slg132055)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Happened randomly when opening the Assembly line

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to receive views from the server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Report doesn't contain enough information, this issue can happen pretty randomly and without client logs from the time it did happen, it's not fixable.
