### ISSUE TITLE
Server crash on startup with unhandled exception "No process is at the other end of the pipe."

### ISSUE THREAD

**Issue by swi-da** [StrangeLoopGames/EcoIssues#24067]
Server is starting for a few seconds and stops at "Starting TimePlugin", then throws the exception "No process is at the other end of the pipe."
Up until a month ago it worked fine, then after just recently starting it up again it won't start anymore.
Server version is 9.7.13.
[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/12910278/Dump.zip)
[log_231015072924.log](https://github.com/StrangeLoopGames/EcoIssues/files/12910279/log_231015072924.log)

**Comment by swi-da** [comment]
I did some digging around now and it seems to be related to Windows Update KB5030649. I uninstalled KB5031356 from October 12 -> reboot -> no change. Then uninstalled KB5030649 -> reboot -> Eco Server is starting again.

**Comment by D3nnis3n** [comment]
Is a MS issue, released a statement on it:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/90dd563a-6dc1-4162-a82e-75f2f6b27dd1)
