### ISSUE TITLE
USER ISSUE: Crashed on first start.

### ISSUE THREAD

**Issue by leoyulee** [StrangeLoopGames/EcoIssues#24062]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-176

**Steps to Reproduce:**
1. Turn off game last night
2. Computer went to sleep
3. Open game in the morning

**Expected behavior:**
It should have started the game

**Actual behavior:**
Instead it showed a Unity notification window with the "Eco" logo and a warning symbol. When the bar on the window was full, it closed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/12847748/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/12847749/Player.log)

**Comment by D3nnis3n** [comment]
That is a sound engine crash, likely due to a failure in some sound related driver or hardware piece.
