### ISSUE TITLE
USER ISSUE: Error when launching game

### ISSUE THREAD

**Issue by Xearnce** [StrangeLoopGames/EcoIssues#24065]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-188

**Steps to Reproduce:**
Launch The Game

**Expected behavior:**
I should have Main Menu selections

**Actual behavior:**
The following error message popped up:
```
HTTP/1.1 503 Service Unavailable
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
