### ISSUE TITLE
USER ISSUE: Banned from a server after leaving to restart game

### ISSUE THREAD

**Issue by EmuLegs** [StrangeLoopGames/EcoIssues#24079]
\
**User Id: (slg61283)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
No fucken clue

**Expected behavior:**
Game shoulda restarted with out banning me from a server

**Actual behavior:**
Server admin has no clue how this ban was applyed and is trying to fix this asap

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no clue server uses mods not the client that joins 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by EmuLegs** [comment]
Not really anything to go on in my report, just letting you know something fucked up...

**Comment by D3nnis3n** [comment]
Thanks for your report, unfortunately there is not really any flow existing that could cause that, hence without a reproducable case provided we are not able to investigate this at all. The only way this can happen is if the ban was manually added to the banlist and the server rejected you on next connection. If you ever happen to get a reproducable case, so we can look into it, please let us know. For now, with this information, i unfortunately have to close the issue.

**Comment by EmuLegs** [comment]
I assumed that would be the case, thankyou :)
