### ISSUE TITLE
USER ISSUE: Getting DC while laying down Asphalt with stonehammer

### ISSUE THREAD

**Issue by Visiju** [StrangeLoopGames/EcoIssues#24076]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-209

**Steps to Reproduce:**
dc while building

**Expected behavior:**
worked

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Placement.BlockPlacementUtils.PlaceBlockUnstacked(Player player, Vector3i </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Should be fixed.
