### ISSUE TITLE
bug with swimming, vehicles, and mined materials

### ISSUE THREAD

**Issue by steelmenace** [StrangeLoopGames/EcoIssues#24078]
I play on the Civeco server 
0.10.0.0 beta playtest-213 
Server ID: 99b844df-e8dd-4363-af4f-f6c326c37deb
Currently, vehicles: like skid steers, are popping up from underground when rocks and such fall on them, while accessing the inventory occasionally, or just when leaving the skid steer and it appears up on the surface, and while mining or using the skid steer some of the rocks will pop up on the surface. Also for some reason, I have a bug where I will have 2000+ calories and I will go into the water and instantly get the no calories to swim please go back to land notification and if I don't I instantly drown and lose all my calories. It seems to be a hit or miss on the swimming bug when I log in like bugs tend to be.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13194628/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13194629/Player-prev.log)

**Comment by steelmenace** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/149225167/41900876-1fe1-4ff9-b4aa-de9d1128cc6d)
this is the mined materials bug issue along with an issue with trucks also popping up on the surface, i dont have the water or skid steer pic/vid though

**Comment by D3nnis3n** [comment]
Fixed.
