### ISSUE TITLE
USER ISSUE: Bow unable to see arrows

### ISSUE THREAD

**Issue by OJW1988** [StrangeLoopGames/EcoIssues#24071]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-196

**Steps to Reproduce:**
attempt to use a bow and arrow

**Expected behavior:**
be able to shoot the arrow

**Actual behavior:**
"You have no arrows in Inventory" even with the arrows right next to the bow. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nothing, straight vanilla from recent SO patch

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24184
