### ISSUE TITLE
USER ISSUE: Random Crash

### ISSUE THREAD

**Issue by Soundwavesghost** [StrangeLoopGames/EcoIssues#24073]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-199

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thank you, unfortunately that is not a crash, but just a timeout from the server.
