### ISSUE TITLE
USER ISSUE: Can't login due to 2 hour timer apearing even on correct credentials.

### ISSUE THREAD

**Issue by Valderg** [StrangeLoopGames/EcoIssues#24074]
\
**User Id: ()**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Wont let me log into my account. Have entered password correctly severla times, the first time i punched in my information it was correct and told me i was blocked for 2 hours.

Standalone version.

**Expected behavior:**
Let me log in.

**Actual behavior:**
The following error message popped up:
```
Too many failed attempts. Blocked for 2 hours.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes. Fresh Install.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Valderg** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13062502/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13062503/Player.log)

**Comment by D3nnis3n** [comment]
Hello Valderg,
please let us know your IP address via mail to support@strangeloopgames.com, referencing this issue, when the issue appears.

**Comment by D3nnis3n** [comment]
Closed due to no further information provided.
