### ISSUE TITLE
Ctrl drag and dorp generator causes issue

### ISSUE THREAD

**Issue by klinoah** [StrangeLoopGames/EcoIssues#24077]
Used ctrl left click and drop to move my generator. 
When connecting a water pipe to it, the water source was not being recognised (shows as disconnected).
Asked to relay the info and my latest log for bugs etc - here ya go.
[log_230828063808.log](https://github.com/StrangeLoopGames/EcoIssues/files/13191686/log_230828063808.log)

**Comment by D3nnis3n** [comment]
Already fixed.
