### ISSUE TITLE
[9.7.13]Server won't start InvalidDataException

### ISSUE THREAD

**Issue by teagan75** [StrangeLoopGames/EcoIssues#24086]
Game file corrupted and wouldn't start. The only backup that started was before I restarted the server for its scheduled reboot
[log_231106025228.log](https://github.com/StrangeLoopGames/EcoIssues/files/13274317/log_231106025228.log)

eco file https://drive.google.com/file/d/1PsAtmy9nvnTVlBEMmRG8Bhs22igkvwHu/view?usp=sharing

db file https://drive.google.com/file/d/1518aEns6KzL-OvZuCI8MIEtdEkpIT-xR/view?usp=sharing

**Comment by D3nnis3n** [comment]
The error does not hint at any specific problem, just a general savegame corruption which we unfortunately can't do anything.

If you got a reproduction case on how to achieve this without user error, please let us know and reopen the issue :)
