### ISSUE TITLE
USER ISSUE: Ошибка входа в игру. 

### ISSUE THREAD

**Issue by MyrZlo** [StrangeLoopGames/EcoIssues#24085]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Захожу в игру 2. Пытаюсь подключиться к локальному миру. 

**Expected behavior:**
1.Захожу в игру
2.Подключаюсь к локальному миру.3. Играю в игру. 

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
<size=150%>Ошибка подключения</size>

Неверная информация авторизации.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Нет

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The error states that you can't reach our authentication servers. Those are protected by Cloudflare - which is banned by some providers in russia. It's possible you need to use a VPN to be able to connect to the authentication servers.
