### ISSUE TITLE
USER ISSUE: NESSUN SERVER NELLA LISTA SERVER

### ISSUE THREAD

**Issue by MicoITA** [StrangeLoopGames/EcoIssues#24088]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-218

**Steps to Reproduce:**
NESSUN SERVER NELLA LISTA SERVER

**Expected behavior:**
NESSUN SERVER NELLA LISTA SERVER

**Actual behavior:**
NESSUN SERVER NELLA LISTA SERVER

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your playtest version is outdated, the current version is playtest-228, that's why you don't see any server.
