### ISSUE TITLE
tweak weight on stone

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2408]
stone was changed from 1 stone/m3 to 4 stone/m3 but the weight was not adjusted

meaning its incredibly hard to carry large stacks of stones in carts now

**Comment by metachronism** [comment]
(btw can we please remove weight yet???)

**Comment by MarjieAVolk** [comment]
Wait I thought you were the one who didn't want to remove weight

**Comment by johnkslg** [comment]
I dont want to remove weight :)

**Comment by metachronism** [comment]
looks like this was fixed
