### ISSUE TITLE
USER ISSUE: Failure to join White Tiger

### ISSUE THREAD

**Issue by espencapable** [StrangeLoopGames/EcoIssues#24087]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-227

**Steps to Reproduce:**
Click join, starts to load, after 5s it reverts back to menu with no error message.

**Expected behavior:**
Load in and join server

**Actual behavior:**
Starts loading in, stops and reverts back to menu without any error

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13292881/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13292882/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please recreate your avatar in "Your avatar", that will fix the issue. Make sure to use new clothes.
