### ISSUE TITLE
USER ISSUE: gefällte Bäume werden nicht mehr erkannt

### ISSUE THREAD

**Issue by thunder312** [StrangeLoopGames/EcoIssues#24082]
\
**User Id: (slg222646)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
Fälle einen Baum, während des Fallens, hacke weiter auf den fallenden Stamm, sodass gleich 1 oder 2 Stücke noch im Fallen abgetrennt werden.Wenn der Stamm am Boden liegt, wird er nicht gelb/grün umrandet, das heisst er kann nicht weiter gehackt werden und auch nicht aufgesammelt werden. DIe Kollisionsabfrage funktioniert aber noch.- Ich kann den Stamm vor mir her schieben.

**Expected behavior:**
Baumstamm kann weiter zerkleinert und gesammelt werden.

**Actual behavior:**
Baum kann nicht weiter zerkleinert und aufgesammelt werden.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23934
