### ISSUE TITLE
USER ISSUE: Issue while joining a server or local world

### ISSUE THREAD

**Issue by rewindtm** [StrangeLoopGames/EcoIssues#24094]
\
**User Id: (slg208195)**
**Version:** 0.10.0.0 beta playtest-244

**Steps to Reproduce:**
Joining a server or loading local world

**Expected behavior:**
Simply joining a server or create a local world

**Actual behavior:**
During loading word send me back main menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13395235/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13395236/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please recreate your avatar in "Your avatar", that will fix the issue.

**Comment by rewindtm** [comment]
Hi @D3nnis3n.
Not working, already recreated my avatar but nothing change.

Still have a problem

**Comment by D3nnis3n** [comment]
Post fresh log after new avatar creation, the log you posted is avatar related.

**Comment by rewindtm** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13396605/Player.log)

With new clothes seems fixed

Thanks
