### ISSUE TITLE
Need to Block logins or not show server in browser until world is created and saved

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2409]
per johnK I am adding this as an enhancement:

For some reason I have been hit with support tickets from everyone who upgraded from 5.6.1 to 6.0 and creating new servers if the server was a public server and could be accessed while the world was creating.  Each time the crash logs looked like one or more logins while the world was generating caused the crash.  To fix them I set them as private server and white-listed them so anyone who had the server as a favorite could not get in and then generated the world.  This worked and the world created and saved without crashing.  (I could then set it back to public without a white list).   Is there going to be a way in the future that either the server will not show in the browser, or the server will not allow connections, while the world is creating?  This was a small issue in 5.4 and 5.5 and happened more often in 5.6 but really seems to be an issue now in 6.0

**Comment by MGrand3** [comment]
For reference this is what closed the issue last time this was suggested: https://github.com/StrangeLoopGames/Eco/pull/1531

Would also really like to see this feature added.

**Comment by noblackthunder** [comment]
john mentioned to have a fix for this issue for the next patch since this is becoming a large issue now if i am not wrong
