### ISSUE TITLE
Cant Join Any World in 10.0 wtplaytest beta branch

### ISSUE THREAD

**Issue by patchell13** [StrangeLoopGames/EcoIssues#24091]
When attempting to join any server on this branch it begins to load the server, but once world loading begins it kicks me back to the main menu.

No mods or anything. White Tiger official server, but same with any attempted to join. Even personally hosted.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13344719/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13344720/Player-prev.log)

**Comment by patchell13** [comment]
Please let me know if there is any additional information I can provide to assist getting this issue resolved for myself and others who are unable to assist with playtesting.

**Comment by D3nnis3n** [comment]
Please recreate your avatar in "Your avatar", that will fix the issue.

**Comment by patchell13** [comment]
Yep, hitting the random button on the Avatar let me load the game up. Thanks!
