### ISSUE TITLE
USER ISSUE: Store says I have no items to sell

### ISSUE THREAD

**Issue by NielsH** [StrangeLoopGames/EcoIssues#24097]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Place items from my stockpile into my truck
2. Drive to store
3. Attempt to sell items

**Expected behavior:**
I am able to sell the items located in my truck

**Actual behavior:**
I cannot sell the items, the store says I do not have any items to sell

Relogging fixes the issue. 

It does not always happen but when transporting it happens frequently enough to require a relog every 2-3 times when attempting to sell items

I do see the items through the "Storage" tab -> Linkable Inventories.

A store next to it *does* work which buys items from the same truck.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13402987/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13402988/Player-prev.log)

**Comment by D3nnis3n** [comment]
This is fixed in Update 10.

**Comment by NielsH** [comment]
Hi @D3nnis3n 
Good to hear this will be fixed in Update 10!
Could you perhaps share some details (perhaps another GH issue?) about the bug?

I'm wondering if there's something we can do on our side to help reduce the impact on our version, as it seems that some stores are a lot more susceptable to this bug than others.

Thank you!
