### ISSUE TITLE
USER ISSUE: Unable to interact with world in White-Tiger Playtest

### ISSUE THREAD

**Issue by saladan0** [StrangeLoopGames/EcoIssues#24090]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-233

**Steps to Reproduce:**
Simply join White-Tiger Playtest and join or create any server

**Expected behavior:**

Can pickup fruit, complete tutorial, or place starter camp

**Actual behavior:**
Unable to do any of the above. Unable to interact with world 

at all. No starter camp ghost is seen when selected in hotbar.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, this happens on fresh install and mods disabled

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13324631/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13324632/Player-prev.log)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24545
