### ISSUE TITLE
USER ISSUE: Latest Update

### ISSUE THREAD

**Issue by Gallaxyman** [StrangeLoopGames/EcoIssues#24108]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-275

**Steps to Reproduce:**
Log in to world

**Expected behavior:**
Animals should move. 
Bow should shoot arrows.
Power generators should shut off to conserve power when not needed.

**Actual behavior:**
Animals are frozen in place. 
Bow animates firing but does not shoot arrows.
All generators running. (Demand is 7 times lower than supply. only 2-3 gens should be running. including steam engine for mechanical power) 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. Never used Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Should be fixed.
