### ISSUE TITLE
Alpha.6 Oil Refinery producing smog, but isn't crafting

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2410]
![peek 2017-09-30 12-451](https://user-images.githubusercontent.com/1900106/31045153-59dc382a-a5dd-11e7-8626-3b1141eb8538.gif)

**Comment by Fank** [comment]
Same for Cement Kiln but has no work queue
![peek 2017-09-30 12-53](https://user-images.githubusercontent.com/1900106/31045196-7007738e-a5de-11e7-9234-8a091e95ef9e.gif)

**Comment by MarjieAVolk** [comment]
@craig-jong Thought this was an Operating bug, but it's kind of not - looks like PipeComponent has never checked whether the world object is Enabled/Operating when ticking its pipes?  Not sure what the intended behavior is there, since ticking does other things as well.
