### ISSUE TITLE
USER ISSUE: Assign a store to an unauth credit crashes 10. server

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24105]
\
**User Id: (slg233066)**
**Version:** 0.10.0.0 beta playtest-273

**Steps to Reproduce:**
Player 1 Create a plot
Player 1 auth PLayer 2 to use plot

Player 2 place store on plot
PLayer 2 set currency to Player 2 credit using player 2 account
make sure player 1 does not have player 2 credit 

PLayer 3 sell something to store
Crash because Player 1 cannot give player 3 credits from player 2 and cant access player 2's account

**Expected behavior:**
NOT CRASHED - show error with credits instead

How do you not have top level error traps to stop server killers yet

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
