### ISSUE TITLE
[Sea Otter PT] Crash occurred when trying to edit deed 

### ISSUE THREAD

**Issue by axinom-erki** [StrangeLoopGames/EcoIssues#24106]
Encountered a crash on client side when attempting to "Edit" Deed during Play Test on Sea Otter.

Steps before the crash

1. Opened `Claim stake`
2. Selected `Authorization` tab
3. Clicked on `Open Deed`
4. Clicked on `Edit` in the opened window
5. Experienced a crash 

Logs: [crash-log.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13532260/crash-log.zip)

Reproducibility: 10/10 

Additional details: Claim is 5x plots currently, with only one added to beginning 4x, by using the Claim Tool

**Comment by axinom-erki** [comment]
Video capture: https://drive.google.com/file/d/13bO9A4HhBElutwuO6HPJhKYNsCuVWutC/view?usp=drive_link

**Comment by D3nnis3n** [comment]
Fixed.
