### ISSUE TITLE
USER ISSUE: DX12 very slow

### ISSUE THREAD

**Issue by kittle31** [StrangeLoopGames/EcoIssues#24100]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta playtest-262

**Steps to Reproduce:**
start game in Dx12 mode

**Expected behavior:**
FPS 60+ 

**Actual behavior:**
FPS 15-30 with frequent dips below 10.
GPU: GTX 4090, 64gb ram

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @kittle31 thank you for your report
unfortunately DX12 is not supported yet, and we have that option for experimentation purposes only.
