### ISSUE TITLE
USER ISSUE: Wood pulp does not disappear

### ISSUE THREAD

**Issue by MrVanq** [StrangeLoopGames/EcoIssues#24115]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-521

**Steps to Reproduce:**
1) Chop down the tree
2) Chop the wood pulp

**Expected behavior:**
After chop the wood pulp - texture disappeared

**Actual behavior:**
After chop the wood pulp - texture dont disappeared

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I play at ver. 10 "playtest"

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed.
