### ISSUE TITLE
0.10.0.0 beta release-521 : Crash when opening influence page of ecopedia

### ISSUE THREAD

**Issue by Veredior** [StrangeLoopGames/EcoIssues#24116]
Create and join a default private world, open the ecopedia and go to the influence page. Then the server crashes.
[log_231209043404.log](https://github.com/StrangeLoopGames/EcoIssues/files/13624570/log_231209043404.log)

**Comment by D3nnis3n** [comment]
Internal: 32352

**Comment by D3nnis3n** [comment]
Fixed in 10.0.1
