### ISSUE TITLE
USER ISSUE: Connection Issues (local)

### ISSUE THREAD

**Issue by leomide** [StrangeLoopGames/EcoIssues#24129]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
I installed a graphics card update, while the game was running. After installation, the game went black and froze. After restart, I couldn't open my local save anymore

**Expected behavior:**
Should have opened my save

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
We are experiencing extremely high load currently that is affecting our services. We are working on remedying the situation and keep you updated. If you see an issue like "No response from auth server" or a empty menu screen, it's due to this. Sorry for the inconvenience.
