### ISSUE TITLE
USER ISSUE: login failed

### ISSUE THREAD

**Issue by Nastril** [StrangeLoopGames/EcoIssues#24127]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13651615/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13651616/Player-prev.log)
\
**User Id: ()**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
essayer de se connecter au serveur

**Expected behavior:**
Je veux me connecter à un serveur

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Invalid login info.

<size=60.00%>L'utilisateur n'a pas de produits assignés</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non ,et non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
We are experiencing extremely high load currently that is affecting our services. We are working on remedying the situation and keep you updated. If you see an issue like "No response from auth server" or a empty menu screen, it's due to this. Sorry for the inconvenience.
