### ISSUE TITLE
USER ISSUE: No land claim papers

### ISSUE THREAD

**Issue by Aurora0044** [StrangeLoopGames/EcoIssues#24120]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Full inventory
2. Make engineering book for the first time
3. Make scroll from book

**Expected behavior:**
Given me 5 land claim papers

**Actual behavior:**
Gave me nothing even after I tried to recreate the scroll and read it again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Closing due to Update 10 removing this system.
