### ISSUE TITLE
USER ISSUE: Guide book influence crash

### ISSUE THREAD

**Issue by TryHarderrr** [StrangeLoopGames/EcoIssues#24125]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Open guidebook
Go to the town section
press influence
game crash

**Expected behavior:**
exits world with error code

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
none

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TryHarderrr** [comment]
Singleplayer world

**Comment by TwixterZ** [comment]
@TryHarderrr thank for reporting this, I have checked and confirmed this is the situation.

Internal ref : 32352

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24116
