### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by GadgetPaPa** [StrangeLoopGames/EcoIssues#24123]
\
**User Id: (slg232908)**
**Version:** 0.10.0.0 beta release-528

**Steps to Reproduce:**
1. Open map.
2. click land claim name link at bottom of map
3. click edit button.

**Expected behavior:**
should have been able to edit land claim. 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13640064/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13640065/Player.log)

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Property.DeedEditingUtil.CanClaimAtPos(User user, Settlement claimingSettl</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes. and yes happens with no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13640072/Player-prev.log)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24106
