### ISSUE TITLE
USER ISSUE: Connection Failed, Invalid login info on joining Game

### ISSUE THREAD

**Issue by Fischkjopp** [StrangeLoopGames/EcoIssues#24124]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.13 beta release-506

**Steps to Reproduce:**
1. Try joining a World

**Expected behavior:**
The game should let me join a world and let me play the game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13644671/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13644672/Player.log)

**Comment by D3nnis3n** [comment]
Fixed.
