### ISSUE TITLE
Alpha.6 Unwanted placement of repair station

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2413]
![image](https://user-images.githubusercontent.com/1900106/31046227-860924fe-a5f5-11e7-9a0a-7b751fa369d7.png)
![image](https://user-images.githubusercontent.com/1900106/31046228-88e9be54-a5f5-11e7-8194-afb24ecc146f.png)
I don't know how they did this, but they did. And i think its not intended to place something in walls.

**Comment by Frozen-byte** [comment]
Thats my Repair station: point to a wall and press Rotate until it's in the Wall, then place it.

**Comment by Nanders** [comment]
https://github.com/StrangeLoopGames/Eco/pull/1882
