### ISSUE TITLE
0.10.0: Unable to pick up tomate with empty hand

### ISSUE THREAD

**Issue by b-steiner** [StrangeLoopGames/EcoIssues#24135]
Tomatos (and some other plants) cannot be harvested by pressing E while an empty hand slot is selected. With Pickaxe, Hammer, Axe, ... selected it works

**Comment by TwixterZ** [comment]
was there any error message pop-up or anything show up in your player log when this happen? can you share your player log to me the next time you have this?

**Comment by talonos2** [comment]
Happened to me, too. Did not happen reliably. Sometimes I couldn't pick it up, but then a few minutes later I could.

**Comment by b-steiner** [comment]
There is no error message or player log when it happens. I can reproduce it quite consistently (but not always) when starting a new single player world, then
- set up tent, take out tools
- select a hand slot that doesn't contain anything
- try to pick up tomato, nothing happens
- switch to hand slot that contains a tool, picking up works

The plant does show the "Press E to pick up" message.

**Comment by TwixterZ** [comment]
@b-steiner & @talonos2  thanks for the additional info, I manage to replicate this issue and have forwarded the same to our developer to check 

Internal ref : 32544

**Comment by D3nnis3n** [comment]
Fixed in Update 10.3.
