### ISSUE TITLE
USER ISSUE: Abbruch bei Welt laden

### ISSUE THREAD

**Issue by Purzely** [StrangeLoopGames/EcoIssues#24132]
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
beim Einlogen auf Brachstadt Testrunde lädt es bis Welt betreten und dann kommt die Fehlermeldung
Neustarten von PC hat auch nichts gebracht
War aber schon auf der Welt und hatte ne halbe Stunde schon gespielt

**Expected behavior:**
Welt sollte betreten werden

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
``
Error happened during processing incoming message

[Fehler.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13652801/Fehler.txt)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24143
