### ISSUE TITLE
Menu character editor keeps crashing my game.

### ISSUE THREAD

**Issue by Southern2003** [StrangeLoopGames/EcoIssues#24130]
Every time I open the avatar editor my game crashes. This issue occurred on the Playtest branch earlier and now has migrated with the update. It means I can't edit or change my character.

**Comment by D3nnis3n** [comment]
Logs from the crash required: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world
