### ISSUE TITLE
USER ISSUE: Bow & Arrow don't shoot

### ISSUE THREAD

**Issue by Petrus-Rock** [StrangeLoopGames/EcoIssues#24133]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
attempt to shoot the bow and arrow in first person vieuw

**Expected behavior:**
the bow should able to aim and visibly shoot

**Actual behavior:**
Partial animation for drawing the bow. The hand works, the bow doesn't
No aim guide
Upon firing you loose an arrow but it doesn't shoot the arrow

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Comment by TwixterZ** [comment]
Thank you for reporting this to us, I confirm this bug reproducible when taking out bow from table or storage. 
I have informed our developer for possible fix. In the meantime, when you facing this bug, you may select other tool in your quickslot and back to bow, it would work correctly again.

Internal ref: 32195

**Comment by Rambo99** [comment]
> Thank you for reporting this to us, I confirm this bug reproducible when taking out bow from table or storage. I have informed our developer for possible fix. In the meantime, when you facing this bug, you may select other tool in your quickslot and back to bow, it would work correctly again.
> 
> Internal ref: 32195

The recommendation to change the bow to another tool and go back to the bow and arrow does not help fix this bug.

**Comment by Michiel7077** [comment]
For make the bow worked again when I switched to one bow to another bow on the toolbar

**Comment by D3nnis3n** [comment]
Fixed in Update 10.0.2.
