### ISSUE TITLE
USER ISSUE: Cannot pick up the bull which after hunt

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#24138]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Hunt a bull with bow
2. Try to pick up

**Expected behavior:**
Able to pick up the bull	

**Actual behavior:**
Cannot pick up the dead bull just able to puh it away

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Zozoom Thank you for your report, I have confirmed this behavior and developer is informed of the same

Internal ref : 29138

**Comment by Zozoom** [comment]
.
