### ISSUE TITLE
0.10.0: Cannot place dirt on workbench when picked up before required

### ISSUE THREAD

**Issue by b-steiner** [StrangeLoopGames/EcoIssues#24136]
Reproduce:
- Open workbench, start > 2 dirt ramps.
- Dig dirt, place directly on workbench. Works until the dirt for the first ramp is delivered.
- **Before** the first dirt ramp has finished crafting dig a new dirt
- **After** the first ramp has finished, try to deliver dirt to workbench. Expected: Get's added to second ramp. What happens: Dirt can't be added

**Comment by TwixterZ** [comment]
hi @b-steiner , that is currently working as intended. you need to collect the result from previous project before placing ingredient  for the next project in. Would recommend you using stockpile linked to your crafting table for seamless crafting.

**Comment by b-steiner** [comment]
Maybe my description wasn't good enough: The resulting ramp is placed automatically in a stockpile. The workbench isn't clogged or busy and states that it requires additional dirt. When the problem happens, the only thing that needs to be done is drop the dirt, dig it up again, then it can be added.
