### ISSUE TITLE
0.10.0: Dirt Ramp cannot be remove by hammer

### ISSUE THREAD

**Issue by b-steiner** [StrangeLoopGames/EcoIssues#24134]
Left-clicking with the hammer on a dirt ramp does nothing. The ramp can be removed with a shovel, but only when the hands are empty (which means ramps need to be removed, then placed in storage, then next ramp can be removed)

**Comment by TwixterZ** [comment]
Hi @b-steiner thank you for reaching out to us, however, this was intended change and not a bug.
