### ISSUE TITLE
USER ISSUE: Cannot see building parts with using Line build tool

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#24142]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Wanted to place a wall using the Line tool
2. It's very hard to find the spot where the Line shows up
3. You have to play a little to find the right spot always and it takes too much time
4. In the previous version (v9) there was not that hard it worked perfectly

**Expected behavior:**
Not able to place walls with the line build tool

**Actual behavior:**
Works like the previous version, without any issue. can place walls and etc with line build tool

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @Zozoom thank you for your report, i have confirmed this issue and forward it to our developer for possible fix.

Internal ref : 32434

**Comment by D3nnis3n** [comment]
Already fixed.
