### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by no1s1a** [StrangeLoopGames/EcoIssues#24144]
\
**User Id: (slg218480)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Disconnect

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Login token changed.

<size=60,00%>Внутренняя ошибка сервера, Trace ID: 00-dce43f3c963f3353901f38f1aad68a6d-42216a9f26931259-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Have modification

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by steam maintenance.
