### ISSUE TITLE
USER ISSUE: Build-Mode Speed

### ISSUE THREAD

**Issue by Datsun-Drift** [StrangeLoopGames/EcoIssues#24145]
\
**User Id: (slg214322)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Place/Remove Block

**Expected behavior:**
Matching Action to Animation timing

**Actual behavior:**
Adding and removing blocks from the game world is near instant, instead of timed within the animation swing.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Works as intended.
