### ISSUE TITLE
USER ISSUE: Aiming with arrow not showing for the first time

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#24141]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Cerate a new bow
2. Try to aim
3. you wont able to see the red line (aim)
4. You have to change tool and back to arrow than you see it

**Expected behavior:**
Able to aim with bow

**Actual behavior:**
Not able to aim with the bow

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Closing this report as the same already reported here https://github.com/StrangeLoopGames/EcoIssues/issues/24133, you may follow up your issue there.
