### ISSUE TITLE
USER ISSUE: Cannot unclaim a single plot in a homestead that's not in a settlement

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24147]
\
**User Id: (slg233066)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Claim free land outside a settlement
Add plots
Try to remove a plot

**Expected behavior:**
Unclaimed the plot

**Actual behavior:**
Tells you that half  or more of your land needs to be in the parent settlement

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @TheEvilGreebo Thank you for submitting this bug report.
This issue has been fixed and we will be rolling it out in the next coming updates.
