### ISSUE TITLE
USER ISSUE: Build-Mode Cancel Placement

### ISSUE THREAD

**Issue by Datsun-Drift** [StrangeLoopGames/EcoIssues#24146]
\
**User Id: (slg214322)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Place 1 block.
2. Select line mode.
3. Place starting location above first block.
4. With crosshair on first block, while 'Cancel' option is listed, click to cancel.

**Expected behavior:**
Cancel block placement & hologram overlay

**Actual behavior:**
Placement and overlay close, but the block in front og the crosshair is also removed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13654291/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13654292/Player-prev.log)

**Comment by TwixterZ** [comment]
Hi @Datsun-Drift. thank you for your report. I have confirmed this buggy behavior and have forwarded the same to our developer for possible fix. 

Internal ref: 32435

**Comment by D3nnis3n** [comment]
Already fixed.
