### ISSUE TITLE
USER ISSUE: server login

### ISSUE THREAD

**Issue by econutzerdulli** [StrangeLoopGames/EcoIssues#24143]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
komme nicht mehr auf den server 

**Expected behavior:**
normaler server login erwartet 

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein habe keine mods.
problem tritt auf ohne mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @econutzerdulli, thank you for your report, we are aware of this issue, and a possible fix is underway. 

Internal ref : 30050

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24380
