### ISSUE TITLE
USER ISSUE: When I wanted to report another bug the perviou bug is still there

### ISSUE THREAD

**Issue by Zozoom** [StrangeLoopGames/EcoIssues#24140]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Report a bug
2. After you submitted it you still see the prev one

**Expected behavior:**
Get a clean report bug UI

**Actual behavior:**
I see my previou bug report

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @Zozoom Thank you for your report, I have forwarded the same to our developer for a possible fix. 

Internal ref : 32360

**Comment by D3nnis3n** [comment]
Already fixed.
