### ISSUE TITLE
Unchoppable newly spawned cactus in the middle of a road after update to V10

### ISSUE THREAD

**Issue by swi-da** [StrangeLoopGames/EcoIssues#24150]
Version: 0.10.0.0 beta release-532

Steps to Reproduce:
Upgrade from 9.7 to V10. In 9.7, there was no cactus at that location, especially not that large.

Expected behavior:
Chop it, it surrenders to the axe, player is happy.

Actual behavior:
Cactus wins and can't be chopped. ALso not chopable by chainsaw.

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods installed

Logs:
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13654543/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13654545/Player.log)

Server Log (same Windows 10 PC)
[log_231212073244.log](https://github.com/StrangeLoopGames/EcoIssues/files/13654578/log_231212073244.log)

Screenshot and Video:

![20231213013202_1](https://github.com/StrangeLoopGames/EcoIssues/assets/113461081/0b5c784c-4504-4f84-ab0d-ce302e47e335)

https://youtu.be/3S5F2Og1RS0

**Comment by D3nnis3n** [comment]
Migration from 9.7 to 10 is not supported beyond loading, hence this issue will not be addressed.
There is too many things changed that cannot be migrated, unfortunately.

**Comment by swi-da** [comment]
I meant to write 9.7.13, is that also not supported?

**Comment by D3nnis3n** [comment]
No, we only support migrations between the same major version, e.g. 9.X to 9.X and 10.X to 10.X.
