### ISSUE TITLE
USER ISSUE: Wrong text when building

### ISSUE THREAD

**Issue by Datsun-Drift** [StrangeLoopGames/EcoIssues#24157]
\
**User Id: (slg214322)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
When placing hewn logs:1. Select line mode
2. Exceed the block count of what you are carrying3. See pop-up message 

**Expected behavior:**
Message about 'missing x blocks' or 'not enough materials'

**Actual behavior:**
Message: Not attached to the ground

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @Datsun-Drift Thank you for your report, this issue is known at our end and possible fix will be made by developer for future patches.

**Comment by D3nnis3n** [comment]
Already fixed.
