### ISSUE TITLE
Coastline is listed as "Deep Ocean", unable to build

### ISSUE THREAD

**Issue by Castellanox7** [StrangeLoopGames/EcoIssues#24156]
Started up a new 10 server, area at coastline is a deep ocean biome, when it's adjacent to land and unable to build.

This is vanilla v10, no mods.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/14277596/d76ba775-1889-4beb-acdf-11c72909ea61)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/14277596/11f8b083-bf97-42d8-8cbb-3d5a3fb312a3)

**Comment by D3nnis3n** [comment]
Deep Ocean is generated randomly, areas where that is directly at the beach are possible, that works correctly.

**Comment by Castellanox7** [comment]
So is there any way to determine at worldgen/early game where is the best place to put in docks and the like? Having these spawn wherever (or at least without a config to disable) seems a bit of a kick in the backside if you have a place you want to build, but for whatever reason, one little square makes the game go "Nah".

**Comment by D3nnis3n** [comment]
You could check the worldgen in the server ui that appears when booting the server, it shows the biomes roughly, but I don't know out of my head if the different ocean biomes do have separate coloration.

The generator will not usually place deep ocean directly at beaches, that depends on the generation and the configs set, especially when ocean mass is too little or land masses too big.

You also can enable the building on deep ocean in Difficulty.eco.

**Comment by Castellanox7** [comment]
Thank you!

**Comment by D3nnis3n** [comment]
Also, please don't get me wrong - the world generator is using a multitude of complexity to generate the worlds, some spots of deep ocean near beaches are hence normal. That doesn't work as intended, but is within acceptable error margin, hence "working correctly" as far as developed goes. If you see this like on every coast block, then we'd have an issue but I could not find such on my reproduction tries.
