### ISSUE TITLE
USER ISSUE: Cannot place on top location

### ISSUE THREAD

**Issue by Datsun-Drift** [StrangeLoopGames/EcoIssues#24158]
\
**User Id: (slg214322)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
When placing blockss:1. Place 2 blocks in a column
2. Select line mode3. From ground level, attempt to place block on top of column 

**Expected behavior:**
Block to snap to top location, as it did prior and does with single mode.

**Actual behavior:**
No snap point unless camera is above top block.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Heya @Datsun-Drift  Thanks for the feedback, I have forwarded this to our developer for a possible fix.

Internal Ref: 32439

**Comment by D3nnis3n** [comment]
Already fixed.
