### ISSUE TITLE
USER ISSUE: torch audio

### ISSUE THREAD

**Issue by SeanCrifasi** [StrangeLoopGames/EcoIssues#24155]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Equip a torch, then after you begin to hear the torch sound, unequip the torch for any other tool/item.

**Expected behavior:**
the torch shouldn't make any noise when not equipped

**Actual behavior:**
the torch audio remains even for other players nearby until you logout/login again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Hi @SeanCrifasi thank you for reporting, issue is known and possible fix will be made for future patches.

Internal ref : 32413

**Comment by D3nnis3n** [comment]
Already fixed.
