### ISSUE TITLE
Alpha.6 Wrong icons

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2415]
- I don't think this i the right icon ![image](https://user-images.githubusercontent.com/1900106/31046323-bd1d1b34-a5f6-11e7-8019-5afa58252eec.png)
- ![image](https://user-images.githubusercontent.com/1900106/31046336-d3941c8c-a5f6-11e7-8a58-ec79d2aea2d2.png)

**Comment by noblackthunder** [comment]
i think they are most likely place holders if i am not wrong

**Comment by Fank** [comment]
Placeholder are those white gears or am i wrong?

**Comment by noblackthunder** [comment]
sometimes they select a random icon for items until an actual icon has been created by the art team

**Comment by Fank** [comment]
Thanks for the info

**Comment by MarjieAVolk** [comment]
Don't you see, a Polishing Station is like a Fishing Pole because both have "Pol" in them :P
