### ISSUE TITLE
USER ISSUE: Error when dig a coal

### ISSUE THREAD

**Issue by linfo** [StrangeLoopGames/EcoIssues#24163]
Linux
\
**User Id: (slg165449)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
dig a coal

**Expected behavior:**
not a error

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Simulation

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Simulation.Agents.Animal.get_Active()
   at System.Linq.Enumerable.WhereArrayIterator`...

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce, assuming fixed. Please open a new issue if you encounter this issue again.
