### ISSUE TITLE
Game Crashes with Unity Error when I try to load world

### ISSUE THREAD

**Issue by Krazywaya** [StrangeLoopGames/EcoIssues#24161]
When I join a server it shows that it is connecting to server and then loading the world it gets to about 23-24% and then a Unity error pops up and the game crashes to desktop. I have updated my Nividia graphics drivers. I have shut down and restarted my pc multiple times. I uninstalled and re-installed the game twice. I changed all of the graphic settings to be lowest and I have tried medium settings. I am unsure why I am unable to connect to the game. The main menu graphics of the game run smoothly. I tried joining my friend's server and I tried joining a public server with the same error. 
![Capture](https://github.com/StrangeLoopGames/EcoIssues/assets/153700412/896f1fb8-ddf7-48c0-8e4d-e8bd769fbb64)

**Comment by D3nnis3n** [comment]
Please attach your client log files and crash dumps after such crash as described here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
