### ISSUE TITLE
Hitting the base of an un-felled tree consumes calories but does nothing.

### ISSUE THREAD

**Issue by talonos2** [StrangeLoopGames/EcoIssues#24169]
To Reproduce:

- Go to an oak tree
- look at the bottom of the tree, such that the entire tree is highlighted
- Chop the tree 100 times.
- Calories are consumed, but tree does not fall.
- Look upwards a bit so that *only* the trunk highlighs
- Chop tree for a while
- Tree falls as normal.

Expected:
- Either:
 - Tree falls OR
 - No calories are consumed, because the chop is invalid and doesn't do anything.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24532
