### ISSUE TITLE
USER ISSUE: The title disables the mouse on the title screen upon attempting to joining a password protected server

### ISSUE THREAD

**Issue by Son-of-Space** [StrangeLoopGames/EcoIssues#24160]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Launch the title
2. Select 'Your Worlds'
3. Click the 'Plus Button' in the upper right input box
4. Input the I.P. and port forwarding information for a password protected server
5. Input the server's password and press the Enter key.
6. Observe the title resets the 'Main Menu' cinematic and disables the mouse, preventing interaction with the title.

**Expected behavior:**
The title should allow the user to connect to the password protected server or display an appropriate error message, gracefully allowing the user to continue.

**Actual behavior:**
The title instead does not display an appropriate error message, forcing the user to terminate and relaunch the title to enable mouse input.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13655666/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13655667/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
