### ISSUE TITLE
USER ISSUE: My crafting table dont detect ressources in my storage

### ISSUE THREAD

**Issue by Waltyty** [StrangeLoopGames/EcoIssues#24175]
\
**User Id: (slg223815)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1 Put storage and put wood / other ressources
2 Put crafting table
3 Crafting table detect  0 ressources

**Expected behavior:**
It should detect the number of wood in my storage so i can craft

**Actual behavior:**
It detect 0 wood and i can't craft anything???

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mod installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Is the storage linked?

Please provide a screenshot.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
