### ISSUE TITLE
USER ISSUE: Item's icon disappear can caused it can't use that item.

### ISSUE THREAD

**Issue by Nekofreedom** [StrangeLoopGames/EcoIssues#24177]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Open any stockpiles or chests.
2. The item icon randomly disappears.
3. Cannot use an item that icon disappeared.

**Expected behavior:**
Open any stockpiles or chests, see an item with its icon, and use it without any problem.

**Actual behavior:**
Cannot use an item that the icon disappears.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24429
