### ISSUE TITLE
USER ISSUE: Anzeige Speicher

### ISSUE THREAD

**Issue by Feedaca** [StrangeLoopGames/EcoIssues#24170]
\
**User Id: (slg169407)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Anzeige Speicher beim kleinen Wagen

**Expected behavior:**
Anzeige aller Lager in unmittelbarer Nähe

**Actual behavior:**
Keine großen Lager in der Anzeige zu sehen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Nicht reproduzierbar, irgendwelche weiteren Infos wie man das nachstellen kann?
