### ISSUE TITLE
USER ISSUE: Town foundation not available at crafting table

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24174]
\
**User Id: (slg233066)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Create a settlement crafting table
Try to make a town foundation

**Expected behavior:**
Been in the menu

**Actual behavior:**
Isn't

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not reproducible, this seems to be happening at some hosts that may have not updated correctly.
Make sure to delete the full /Mods folder and then get a new one. Also make sure you have a fresh world, it will not work with migrated worlds from either playtest or 9.7.

If you need additional help thereafter, please send a mail to support@strangeloopgames.com.

**Comment by TheEvilGreebo** [comment]
No mods, world was generated on 10 soplaytest

**Comment by D3nnis3n** [comment]
Migrating worlds from playtest is not supported, sorry.

**Comment by D3nnis3n** [comment]
There seems to be a community made document how you can still get the world to work, but you need a backup prior to the migration to release and we do not support this approach: https://docs.google.com/document/d/1Bd4g_5WShLOtuv4VBgp_9TGGby6e-iBD8SrtCZZty7E/

**Comment by TheEvilGreebo** [comment]
Yeah sorry my reply was meant as confirmation.

I have regenerated the world with the same seed and the everybody bug was
fixed, I expect this will be too when we get there.
