### ISSUE TITLE
USER ISSUE: Verdrehte Blöcke nach Update auf V10

### ISSUE THREAD

**Issue by zweitadresse** [StrangeLoopGames/EcoIssues#24180]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
ständiger Zustand, keine Reproduktion nötig

**Expected behavior:**
die Strukturen sollten nachvollziehbar funktional sein. Beispielsweise Dächer und Treppen

**Actual behavior:**
Blöcke von Dächern und Treppen sind um 90 Grad gedreht

**Do you have mods installed? Does the issue happen when no mods are installed?:**
es sind keine Mods installiert. Einige Fotos sind angehängt. Es wäre großartig, wenn ihr mir die Blöcke zurückdrehen könntet. Vielen Dank
![Screenshot 2023-12-13 1851321](https://github.com/StrangeLoopGames/EcoIssues/assets/153762601/dca2e489-b799-4098-97d4-0aa7638ab908)
![Screenshot 2023-12-13 185509](https://github.com/StrangeLoopGames/EcoIssues/assets/153762601/7bff1af7-e634-4b76-8180-16bdf794132c)
![Screenshot 2023-12-13 1854221](https://github.com/StrangeLoopGames/EcoIssues/assets/153762601/e8c68ea4-bc52-49fb-8ad5-994b956f5847)
![Screenshot 2023-12-13 1853101](https://github.com/StrangeLoopGames/EcoIssues/assets/153762601/142ee36c-f9c0-4905-a255-f4a227ed59cc)
![Screenshot 2023-12-13 1852201](https://github.com/StrangeLoopGames/EcoIssues/assets/153762601/edcfd8bd-1e09-43fc-95a5-5113a9af8ee9)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Das ist ein Effekt der eingeschränkten Migration von 9.7 zu 10.0 und nicht vermeidbar, wird daher leider auch nicht behoben. Wir empfehlen bei Major Versions grundsätzlich eine neue Welt zu starten, auch wegen der neuen Weltgeneration.
