### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by FeniRisin** [StrangeLoopGames/EcoIssues#24181]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.4 beta release-327

**Steps to Reproduce:**
Trying to sign in to my world and it keeps saying there is a connection error

**Expected behavior:**
Logged me into my world

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Not currently

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Severely outdated version, please update to a recent version.

**Comment by FeniRisin** [comment]
Updated and still getting the message

**Comment by D3nnis3n** [comment]
You will need to start a new game and make sure your whole game is correctly reinstalled.

Uninstall the game, remove /Steam/steamapps/common/Eco/ and AppData/LocalLow/Strange Loop Games and then reinstall it.

If you have further problems, reach out to support@strangeloopgames.com.

**Comment by FeniRisin** [comment]
I am able to join other worlds just not the one I was on
