### ISSUE TITLE
USER ISSUE: Crash when looking at Influence

### ISSUE THREAD

**Issue by Destroyerchen** [StrangeLoopGames/EcoIssues#24187]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Open the Ecopedia in the bottom right.2. Go the Settlements tab.3. Go to the Influence tab.

**Expected behavior:**
It should just show the info for Influence like the other pages too, for example the Culture page.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666396/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666397/Player-prev.log)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/24116
