### ISSUE TITLE
USER ISSUE: Large Camas plants can't be harvested

### ISSUE THREAD

**Issue by chemilog** [StrangeLoopGames/EcoIssues#24183]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
When trying to dig up camas plants, the large plants won't fully highlight with the shovel equiped. Smaller plants work fine and can be harvested.

**Expected behavior:**
Adult camas plant should be harvestable with a shovel.

**Actual behavior:**
Plants highlighting flickers, but not enough to actually harvest the plant.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Base Eco 10 game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
hi @chemilog  thank you for reporting this back to us, while it is not highlighting the large camas , you can still harvest it with shovel. 

I will however forward this to our developers for possible fix.

**Comment by fmauNeko** [comment]
Hello,

I ran into the same issue, and interacting with the plant is not possible as it's not highlighted, the dirt block below is highlighted and using the shovel will result in the dirt being dug and the camas plant is lost.

Here's an example video: 
https://github.com/StrangeLoopGames/EcoIssues/assets/46060/99dddd9b-b464-4df5-9bcd-919f0468c9f8

**Comment by D3nnis3n** [comment]
Already fixed.
