### ISSUE TITLE
USER ISSUE: You have no arrows in inventory

### ISSUE THREAD

**Issue by chemilog** [StrangeLoopGames/EcoIssues#24184]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
With a bow equiped and 40 arrows in slot beside it or in backpack an error message appears "You have no arrows in inventory". Removing bow and arrows from inventory and re-equiping makes no difference. Making and equiping new arrows makes no difference.

**Expected behavior:**
When using equiped bow with arrows in inventory the bow should be able to fire on animals.

**Actual behavior:**
No bow animation and an error message appears.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. Base Eco 10 game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Kegath88** [comment]
I had the same issue. Restarting the game was the only thing that worked for me.

**Comment by Krisocka** [comment]
This can reliably be reproduced for me when changing servers without restarting the client.
After server changes I can't get Bows to recognize arrows no matter what I do.

**Comment by D3nnis3n** [comment]
Fixed in 10.3.

**Comment by AlexZan** [comment]
This is still an issue, or once again an issue. Same cause.

**Comment by D3nnis3n** [comment]
> This is still an issue, or once again an issue. Same cause.

Update 10.3 hasn't been released yet?

**Comment by AlexZan** [comment]
> > This is still an issue, or once again an issue. Same cause.
> 
> Update 10.3 hasn't been released yet?

Oops, just looked at the date and assumed it was an old release.
