### ISSUE TITLE
USER ISSUE: Settlement influence crash

### ISSUE THREAD

**Issue by g4rgam3l** [StrangeLoopGames/EcoIssues#24186]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Go on Ecopedia, search for settlement and then go into the settlement section, when I click the influence section the game just crashes.

**Expected behavior:**
It should have shown me how influence works I suppose

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, fresh install with latest patch update

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666080/Player.log)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/24116
