### ISSUE TITLE
USER ISSUE: Cheat Movement Detected when logging in

### ISSUE THREAD

**Issue by DrunkMunki** [StrangeLoopGames/EcoIssues#24189]
\
**User Id: (slg208594)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
logging into 27.50.70.229:3000
get a black screen

**Expected behavior:**
should have loaded in

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
DiscordLink, removed mod, same issue
deleted data in local appdata folder, same issue
deleted world and increased its size, same issue

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666439/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13666432/Player-prev.log)

**Comment by D3nnis3n** [comment]
Server is using a experimental setting, they need to turn it off in Users.eco
"MovementHackDetection": false,
