### ISSUE TITLE
USER ISSUE: Galaxing Gaming server kicked for cheating

### ISSUE THREAD

**Issue by ommfgwtfits** [StrangeLoopGames/EcoIssues#24188]
\
**User Id: Chaosspirit**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Join the server

**Expected behavior:**
Join the server with no issues

**Actual behavior:**
Join the server and the following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Server is using a experimental setting, they need to turn it off in Users.eco
  "MovementHackDetection": false,
