### ISSUE TITLE
Crash when joining a game

### ISSUE THREAD

**Issue by Eldodo** [StrangeLoopGames/EcoIssues#24182]
Version: 0.10.0.0 beta release-532

Step to reproduce: join a game server

Whenever I try to join a server, be it hosted locally or externally, my game crashes at the end of the loading. Its about a missing dll file apparently but I don't know which one.

[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13665684/crash.zip)

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, thanks :)
