### ISSUE TITLE
USER ISSUE: Work Orders disappeared

### ISSUE THREAD

**Issue by araymond3** [StrangeLoopGames/EcoIssues#24194]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
create work order

**Expected behavior:**
work orders are still there after restart

**Actual behavior:**
the work orders are not on the workbench anymore, the items are missing but the work order still appears in the top right on the screen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no books

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Unknown cause and not reproducable, could have been stuff going to void storage due to unclaiming or similar.
