### ISSUE TITLE
USER ISSUE: Server not responding

### ISSUE THREAD

**Issue by Tollwutmolle** [StrangeLoopGames/EcoIssues#24196]
\
**User Id: (slg166425)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Es läuft immer gleich ab,
egal welchen erver ich joinen will bob privat oder Offiziel, ich versuche zu joinen, er lädt die map runter, und bleibt dann bei "Lädt Welt 100%" stehen, nach ein paar sekunden kommt dann die meldung "Server not responding". Danach sind auch meisten keiner server mehr in der serverliste, ich muss das spiel neustarten damit die server wieder angezeigt werden.

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein und nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Tollwutmolle** [comment]
[log eco.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13669735/log.eco.txt)

**Comment by D3nnis3n** [comment]
We have fixed a potential issue related to this. Please reopen if you get it again.

**Comment by Tollwutmolle** [comment]
problem is not solved, i reopen it

 
 

Gesendet: Dienstag, 19. Dezember 2023 um 20:52 Uhr
Von: "Dennis Scholz" ***@***.***>
An: "StrangeLoopGames/EcoIssues" ***@***.***>
Cc: "Tollwutmolle" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Server not responding (Issue #24196)


 

We have fixed a potential issue related to this. Please reopen if you get it again.
