### ISSUE TITLE
USER ISSUE: Camera Snaps North When Operating Wheelbarrow

### ISSUE THREAD

**Issue by adamlibby** [StrangeLoopGames/EcoIssues#24198]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Have a wheelbarrow 
2. "Push" the wheelbarrow (aka operate) 

**Expected behavior:**
Camera Either doesnt change, or it points in the "forward" direction of the wheelbarrow

**Actual behavior:**
Instead the camera always snaps to point "north" 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and yes. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by adamlibby** [comment]
Also does this with wooden carts as well

**Comment by NJAldwin** [comment]
I can reproduce this issue as well

**Comment by KironaDragryph** [comment]
I can also confirm this behavior. It also occurs when using a plow.

**Comment by Yogu** [comment]
Pushed a few carts off a ramp by pressing W immediately after picking up a wooden cart before I understood this bug

**Comment by D3nnis3n** [comment]
Fixed in playtest.
