### ISSUE TITLE
Log Block interruptions in a road make carts sink.

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2419]
Mostly noticed from player if they walk over wood bridges
![image](https://user-images.githubusercontent.com/1900106/31048761-bfe867aa-a624-11e7-867d-f1b50fcc76ac.png)
![image](https://user-images.githubusercontent.com/1900106/31048764-c3493c76-a624-11e7-9ae1-8a8a0f6a1754.png)

**Comment by SatsukiShizuka** [comment]
I noticed the same situation when going over 1-tile wide regular material as well, such as aqueduct.

However, wood does slow down the cart significantly if used as a bridge material, at about 40% speed. Seconded.

**Comment by SeanAtr0n** [comment]
Hmm either this was already fixed or it's related to network lag, having a hard time reproducing

**Comment by stormoffires** [comment]
we have the same issue on our server MAB when taking carts over wood bridges, you might get one or two passes fine but it seems to get caught in the bridge sometimes too.

**Comment by keegan-o** [comment]
This should be easy to fix when we get custom collision on blocks-- or maybe even when I update the log builder which I'm working on now.

**Comment by keegan-o** [comment]
This block is going to be totally deprecated as well when we replace Logs with Log Floor, Log Walls, Log Roof, etc-- there won't be a generic built log block in the future. So I'm going to put this on the Beta timeline for completion when we complete that revamp (currently in progress).
