### ISSUE TITLE
USER ISSUE: Fishing bug

### ISSUE THREAD

**Issue by FrostTheWolf24** [StrangeLoopGames/EcoIssues#24195]
\
**User Id: (slg190290)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Cast Fish line	

**Expected behavior:**
for line to cast into water

**Actual behavior:**
Nothing happens. You act like you're casting, but you dont hear the cast sound and no line reaches the water

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, N/A

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13669662/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13669663/Player-prev.log)

**Comment by mynamaneet** [comment]
Having the same problem

**Comment by D3nnis3n** [comment]
Fixed.
