### ISSUE TITLE
USER ISSUE: flashing screen

### ISSUE THREAD

**Issue by jxnpeters** [StrangeLoopGames/EcoIssues#24190]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
im not sure

**Expected behavior:**
it should not flash	

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Needs more information, especially a video.

**Comment by D3nnis3n** [comment]
Closing due to not reproducable and no further information provided.
