### ISSUE TITLE
USER ISSUE: Game crashes after loading the world

### ISSUE THREAD

**Issue by 8bitMicroFan** [StrangeLoopGames/EcoIssues#24202]
**Version:** 0.10.0.0 beta release-532
**OS:** Arch Linux

I'm running a fresh install of the game and created a new local world for 0.10. After the world has loaded, the game quits and returns to the desktop.

**Steps to reproduce:**
1. Click on "Your Worlds" menu
2. Select the local world
3. Click load

**Expected behavior:**
The loading screen should disappear and the loaded world should be visible.

**Actual behavior:**
After loading the world, the game quits and returns to the desktop.

**Installed Mods:**
None

**Logs:**
Server Log: [log_231214074010.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677325/log_231214074010.log)
Client Log: [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677350/Player.log)

**Comment by D3nnis3n** [comment]
We don't support Linux for client OS, unfortunately.
