### ISSUE TITLE
USER ISSUE: Tent bug

### ISSUE THREAD

**Issue by Githubuseer123** [StrangeLoopGames/EcoIssues#24201]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Two players are in a world2. One player places a tent on which the other is not authorized3. The unathorized player presse 'e' to sleep4. A "ghost player" appears in the bed. The bed is now unuseable.5. Restart the World6. Time will be fastforwarded as if someone is sleeping7. Remove the tent, the bug is fixed

**Expected behavior:**
The unauthorized player cant sleep in the tent and nothing happens.

**Actual behavior:**
A "Ghostplayer" appears

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N0, i dont have mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Githubuseer123 
Thank you for submitting this bug report.
I've gone ahead and created an internal report for this issue. Our development team should roll out a fix soon in the coming game updates. Please look forward to it.

QA Ref: [ECO-32435](https://app.clickup.com/t/10591183/ECO-32436)

**Comment by D3nnis3n** [comment]
Already fixed.
