### ISSUE TITLE
USER ISSUE: Game Crashes on attempting to enter a world

### ISSUE THREAD

**Issue by dylanclements2** [StrangeLoopGames/EcoIssues#24209]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Start Game (via Steam)
Select New Game
Select a Game Server
Game Crashes

**Expected behavior:**
Entered the selected Game

**Actual behavior:**
Crashes

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Tried both with modded worlds and with unmodded worlds.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by dylanclements2** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13679692/Player-prev.log)

**Comment by D3nnis3n** [comment]
Hello,
this is due to your very old CPU (from 2009):
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0e28ecef-1849-4112-ab04-5bbadfc8f580)
