### ISSUE TITLE
Can't change avatar

### ISSUE THREAD

**Issue by Druxus2214** [StrangeLoopGames/EcoIssues#24203]
Unable to interact with avatar button on main screen
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677450/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13677451/Player-prev.log)

Video: https://youtu.be/FANJ5cb1p0c

**Comment by D3nnis3n** [comment]
Log states path C:\Users\druxu\Documents\ECO\Photos is not allowed to be accessed.
Make sure file permissions are set correctly and no antivirus software is interfering, not a bug.
