### ISSUE TITLE
SmithingSkill Unlearn Issue

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#2420]
One player was unlearning a Smithing Skill, while a order was running and it required a smithing skill to be available / crafted and that crashed the server, few times in a row; every time he tried doing it. We didn't try to stop the work order to see if that was the main cause of the crash.

Dump File
[Crash 09305705.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1346744/Crash.09305705.txt)

**Comment by MarjieAVolk** [comment]
Based on the stack trace & the story, it looks like the person 'unlearned' Smithing all the way down to -1, causing an array index out of bounds exception

**Comment by Dreconic** [comment]
I will say with mine I did not have any projects going at time of crashes or unlearning.

**Comment by MarjieAVolk** [comment]
Yeah I don't think it's because of the project; I am suspicious that the lag you described is related though.

I've been trying to repro this and haven't been able to

**Comment by Dreconic** [comment]
Join us on MAB and I can reproduce it for you all day long lol

**Comment by MarjieAVolk** [comment]
Haha - so does everyone experience it?  Or only certain people?  I know you said it was only for certain skills.  Can you attach the save file?

**Comment by Dreconic** [comment]
On our server it is only me it seems. I know on other servers it seems to also be the Smithers that are having it effect the most.

**Comment by stormoffires** [comment]
here is our game file with Deconic user still in it, crashing every time he unlearns.
https://drive.google.com/open?id=0B7I4FfX-IJY9RXJfQzByVlpLSXc

deleting him and letting him rejoin with a fresh char fixed the issue.

**Comment by ecoemmeck** [comment]
This same issue happened to me today. I tried to unlearn metalworking and froze the server several times. It might be important to note that I have unlocked steelworking and that might have something to do with the server freezing

**Comment by Dreconic** [comment]
Ecoemmeck I think that is what it is, I tried to also undo metalworking first, and after that it crashed the server no matter what I did.

**Comment by MarjieAVolk** [comment]
Well I still haven't been able to repro this.  I am going to commit some locking around learn/unlearn skill methods, since my theory was some kind of threading issue from clicking on the button repeatedly

**Comment by MarjieAVolk** [comment]
ooh I got it to happen!  And indeed it was by clicking the button a lot, and getting the level down to -1
