### ISSUE TITLE
USER ISSUE: Crash when opening influence

### ISSUE THREAD

**Issue by XanderTDark1** [StrangeLoopGames/EcoIssues#24210]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
hit p to open the ecopedia, click settlements, click influence

**Expected behavior:**
opened the information tab for influence	

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
   at </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and unknown

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116
