### ISSUE TITLE
Linux Fullscreen issue / input issue 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2421]
http://ecoforum.strangeloopgames.com/topic/2806/fullscreen-on-linux/8

**Comment by SeanAtr0n** [comment]
Sounds like they don't have nvidia drivers installed, can't tell which drivers are used from the log... should say at the very top of the log but it appears that was cut out

**Comment by noblackthunder** [comment]
user claims issue resolved. cant see more complains about this. closing this for now
