### ISSUE TITLE
USER ISSUE: Influence tab crash

### ISSUE THREAD

**Issue by Duplo52** [StrangeLoopGames/EcoIssues#24212]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. Click on the ECOpedia
2. Click on the Settlements tab in the left hand side.
3. Click on the Influence tab on the top selection.
4. Crash

**Expected behavior:**
let me read about Settlements and how Influence works

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
   at </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I do not, so yes it happens with vanilla settings.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Sarah-Graesyn** [comment]
Came here to create this issue but found it already created, so instead I will drop my crash logs for ya'll
>>>
>>
>

<- 
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13680970/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13680989/Player.log)

**Comment by D3nnis3n** [comment]
Duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116
