### ISSUE TITLE
/build road command ignores buildTypeVal and BottomType

### ISSUE THREAD

**Issue by Darkhand81** [StrangeLoopGames/EcoIssues#24214]
Hi!

According to the game, `/build road` has this format:

> /build road **length** (Int32), **width** (Int32), **buildTypeVal** (Int32), **bottomType** (Int32), **flatRoad** (Boolean)

However, `buildTypeVal` and `bottomType` seem to be ignored, and roads are always dirt.  Neither the old /spawnroad method works (1=Stone, 2=Concrete), nor using the ID number of the material you want to use.

`flatRoad` _does_ work. If you set the fifth variable to True or False, you can correctly make the roads be flat or follow the terrain. But the third and fourth variables don't seem to work, and the roads are always dirt.

Is this a bug, or am I completely mis-using the command?

Thanks!

**Comment by D3nnis3n** [comment]
QA command, hence not supported for bug reports, but as noted on reddit i made an internal note.
