### ISSUE TITLE
USER ISSUE: Inventar

### ISSUE THREAD

**Issue by Kendo41** [StrangeLoopGames/EcoIssues#24216]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Inventar ist leer denoch ist im leeren Inventar  Bohnen Maissamen und Flachssaat

**Expected behavior:**
Leeres Inventar

**Actual behavior:**
belegt mit Inhalt ogne Sichtbarkeit und Zugriff

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24429
