### ISSUE TITLE
USER ISSUE: Open Ectopia causes crash when opening influence tab

### ISSUE THREAD

**Issue by Richard-Santiago** [StrangeLoopGames/EcoIssues#24211]
\
**User Id: (slg32158)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Open Ectopia and clich on influence causes crash

**Expected behavior:**
open the influence section to read the influence info

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
   at </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, and we have not been able to test that with the server admins yet 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116
