### ISSUE TITLE
USER ISSUE: Random disconnect on Ecopedia Influence Entry

### ISSUE THREAD

**Issue by vicosurge** [StrangeLoopGames/EcoIssues#24213]
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
Was looking at how Influence works and suddenly got disconnected while reading the entry

**Expected behavior:**
Not getting disconnected

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.EcopediaSettlementConfigData.GetEcopediaData(Player player, EcopediaPage page)
   at </size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by vicosurge** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13681059/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13681063/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/24116
