### ISSUE TITLE
BUG: Law System not recognizing completed law properly.

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#24219]
Steps to Replicate:

1: Propose new Law Draft.
2: Complete New Law Draft and add to Election.

![20231215092608_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/ae310f5d-0a59-4d2b-b346-eb8a3a0ba612)
![20231215092622_1](https://github.com/StrangeLoopGames/EcoIssues/assets/1329717/67b9b0ed-e09b-454e-a091-dae84771f0e0)

in specific the law I was trying to create for this one was to prevent non-citizens of a town from dropping tailings and garbage in the world within that towns influence while discouraging citizens from doing the same via a tax.

**Comment by D3nnis3n** [comment]
We were never able to reproduce this and there haven't been any other reports, hence closing. Please reopen if you ever see it again.
