### ISSUE TITLE
USER ISSUE: 3rd person not working 

### ISSUE THREAD

**Issue by FroZenEscape** [StrangeLoopGames/EcoIssues#24228]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
At random

**Expected behavior:**

**Actual behavior:**
Sometimes trying to switch into 3rd person doesn't work but then will work later, its off and on

**Do you have mods installed? Does the issue happen when no mods are installed?:**
(NO MODS)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce. Please reopen if you have reproducible steps.
