### ISSUE TITLE
USER ISSUE: First-Person Camera Glitch - Camera Enters Player's Head

### ISSUE THREAD

**Issue by mchamplain** [StrangeLoopGames/EcoIssues#24221]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Go to sleep in the tent sleeping bag, disconnect from the server.
Reconnect to the server.
(The player is standing on the sleeping bad in his underware.)
Pressing 'E' to wake up puts me in first-person view.
Attempt to look upwards by moving the mouse.

**Expected behavior:**
Upon waking up and being in first-person view, the camera should allow clear and unobstructed vision, including when looking upwards, without any graphical glitches.

**Actual behavior:**
After waking up from sleep in the tent, attempting to look upwards causes the camera to enter the player character’s head. This results in a graphical glitch where the interior of the character's head, including eyes and teeth, becomes visible, obstructing the normal view.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/759989/672e0d03-3901-455f-bdef-7582c32c12e6)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/759989/9cdbb8ad-78df-439c-acc1-45e117acbd24)

**Comment by D3nnis3n** [comment]
Duplicate.
