### ISSUE TITLE
USER ISSUE: Can't Host A New World

### ISSUE THREAD

**Issue by Micro753** [StrangeLoopGames/EcoIssues#24229]
\
**User Id: (slg42306)**
**Version:** 0.10.0.1 beta release-535

After updating from 9.x to 10.0.1, I can no longer make a new world with random generation. Selecting the "Host World" option in the main menu brings me to the correct screen, but clicking start does nothing. If I uncheck the "Generate Random Landscape" option, it still does nothing, then clicking it again says a world with that name already exists.

After quitting and relaunching, the world that had the random generation option turned off now shows in the local worlds section, but I still cannot create a world with the random generation turned on.

Issue persists after deleting and reinstalling the game. I also tried deleting everything Eco related in my AppData folders and in my documents folder, and the issue persists.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

https://drive.google.com/drive/folders/1UtGKZr9Svr9L_3wMHHXp0ItpJ1Upn8We?usp=drive_link

**Comment by borodac** [comment]
+  after 10.0.0.1 stopped creating a new world

**Comment by borodac** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13699630/Player.log)

**Comment by D3nnis3n** [comment]
Fixed in Update 10.0.2.
