### ISSUE TITLE
USER ISSUE: Unity error + camera glitch

### ISSUE THREAD

**Issue by ScrapsPrograms** [StrangeLoopGames/EcoIssues#24227]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. Go to sleep
2. Quit the game
3. Experience Unity error
4. Boot up the game and join the same server
5. "Wake up"

**Expected behavior:**
1st person displays like normal

**Actual behavior:**
1st person camera is slightly behind where it should be, causing the inside of the head to show

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
