### ISSUE TITLE
USER ISSUE: Many Bugs with 10.0

### ISSUE THREAD

**Issue by FroZenEscape** [StrangeLoopGames/EcoIssues#24225]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**

**Expected behavior:**
Its expected

**Actual behavior:**
-learning new skills dont give land claim papers.
-items dissapearing apon picking up with hammer have to restart then they will show up.
-the bow breaks not being able to shoot or animation playing but arrows still disapear.
- picking up logs can be very slow or very fast like the older versions,its at random.
-shoveling items into a storage container does not play the animation,bug or feature?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
(NO MODS)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by NJAldwin** [comment]
I can reproduce dropping items from a shovel not playing the animation

**Comment by D3nnis3n** [comment]
Please dont report multiple bugs per issue.

Learning new skills does no longer give claimpapers in Update 10, works as intended.
Bow is a duplicate. Droopping items from shovel is also. The other issues seem latency related.
