### ISSUE TITLE
Game runs in “slow-mo” if *not* being screen captured

### ISSUE THREAD

**Issue by e2cool** [StrangeLoopGames/EcoIssues#24222]
The game only runs properly when screen sharing in discord or using OBS. Is there a game setting I might have accidentally tweaked that could be causing this? (Video example of the issue attached)
Tested on numerous servers, vanilla and modded.

Version 10.0 — 10.0.1

GPU: nvidia 4070

Attempted fixes with no success:
-relog/relaunch/reboot 
-verify game files 
-uninstall/reinstall 
-tweaked various nvidia control panel settings relating to GPU 
-updated drivers 
-updated bios

https://github.com/StrangeLoopGames/EcoIssues/assets/48392679/45725ff8-eaca-4615-9ceb-0814bcefd3b4

**Comment by D3nnis3n** [comment]
We have not been able to reproduce this. If you find steps on how to achieve this, please open a new issue. There also has not been any other reports, making this the only one.
