### ISSUE TITLE
USER ISSUE: Impossible d'héberger un monde

### ISSUE THREAD

**Issue by DimClt** [StrangeLoopGames/EcoIssues#24223]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Héberger une monde, créer

**Expected behavior:**
Créer un nouveau monde

**Actual behavior:**
Aucun, reste sur la page de création de monde

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non aucun

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24229
