### ISSUE TITLE
USER ISSUE: what happened?

### ISSUE THREAD

**Issue by HexZadark** [StrangeLoopGames/EcoIssues#24230]
\
**User Id: ()**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
so i start to rubber banded around.  i think it was from network stuff. i was trying to go somewhere and wound just send me back this has happend beofre and left  me in the ocean to drown. no its daying my account has been dissabled? 

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com with your user account details.
