### ISSUE TITLE
Settlement "Property Crisis" Error 10.01

### ISSUE THREAD

**Issue by ChickenHacker1** [StrangeLoopGames/EcoIssues#24231]
If citizens do not leave a settlement before it is destroyed, a property crisis will be triggered when they join a new settlement.

In our case, we had created a settlement, then dissolved it from the settlement foundation.
We then created a new settlement, and were met with property crises on the old settlement. Each player that was a part of the old settlement that had joined the new settlement produced a property crisis. The old settlement no longer existed, so there was no way to resolve the property crisis.

It's important to note that this was not a property crisis with our new settlement, but a property crisis with the old, non-existent settlement.

![Capture](https://github.com/StrangeLoopGames/EcoIssues/assets/80280848/b4c675cd-464f-490f-b60f-fba7ee3c362d)

**Comment by johnkslg** [comment]
@HassenBenAbid looks like we need some cleanup when settlements are destroyed with regards to property crises

**Comment by johnkslg** [comment]
Fixed in next hotfix!
