### ISSUE TITLE
USER ISSUE: Welten erstellen

### ISSUE THREAD

**Issue by JimmyBeam1990** [StrangeLoopGames/EcoIssues#24237]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Eine zufällig generierte Welt erstellen	

**Expected behavior:**
Ein ladebildschirm oder ähnliches

**Actual behavior:**
nichts, man klickt auf start und es passiertt nichts mehr

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein keine mods installiert

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24229
