### ISSUE TITLE
USER ISSUE: Werkzeug nicht auswählbar

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24236]
\
**User Id: (slg222333)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. verfeinte Poorige auf die 0 legen und in die hand nehmen
2. axt auf die 5
3. axt auswählen

**Expected behavior:**
axt ausgewählt

**Actual behavior:**
nichts, leere schüssel bleibt in der hand.
und ist das euer Ernst mit den Upgrades??Man kann die Benötigten materialien nicht mehr per Upgrade reduzieren? Die sind alle sau teuer geworden und der abstand zwischen 3/4 und spezial lohnt sich damit garnicht mehr? Das habt ihr echt kaputt gepatcht

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Danke, der Fehler mit den Animationen ist bereits bekannt.

Die neuen Upgrades funktionieren wie gewollt.
