### ISSUE TITLE
USER ISSUE: No character animation

### ISSUE THREAD

**Issue by Michiel7077** [StrangeLoopGames/EcoIssues#24234]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Sleep in wooden stray bed that is next to wooden walls. Log back in and wake up.

**Expected behavior:**
You clip through the wall and when moving you sometimes see your eyes and teeth and no walking animation, just arms and legs spread

**Actual behavior:**
When waking up spawn on top of bed or next to it, where there is room. (Relogging while not in the bed fixed the issue)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I don't

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Michiel7077** [comment]
Log files:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13692566/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13692568/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate.
