### ISSUE TITLE
[SERVER ISSUE] Objects disappearing when removing residents.

### ISSUE THREAD

**Issue by Ketrai** [StrangeLoopGames/EcoIssues#24248]
VERSION : 0.10.0.1 beta release-535

Simply, when removing residents, any objects they placed down like chests, workstations will get deleted irrevocably.

This is a pretty game breaking issue!

**Comment by D3nnis3n** [comment]
Works as intended, they get put into the void storage of the users that placed them.

The users that placed them can get them back by opening it, its the swirly icon in the bottom right corner, to the left of the map area.

**Comment by Ketrai** [comment]
> Works as intended, they get put into the void storage of the users that placed them.
> 
> The users that placed them can get them back by opening it, its the swirly icon in the bottom right corner, to the left of the map area.

It might be worthwhile to notify players of this somehow because everyone thought their stuff had disappeared. It's quite easy to miss the void storage icon.

**Comment by D3nnis3n** [comment]
We do, there is a popup when you kick people notifying that, I just tried and got it as expected.

**Comment by Ketrai** [comment]
> We do, there is a popup when you kick people notifying that, I just tried and got it as expected.

When my friend kicked us he must've clicked that away. We never got a notification as residents. So it was very confusing.
