### ISSUE TITLE
USER ISSUE: hammer hits to early

### ISSUE THREAD

**Issue by SirPatschiii** [StrangeLoopGames/EcoIssues#24244]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
if you hit any block with the hammer to break it, the block pops without any delay

**Expected behavior:**
should break after the hammer hits in the animation

**Actual behavior:**
hits when I hit left klick

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I haven't installed any mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Works as intended.
