### ISSUE TITLE
USER ISSUE: eco.exe crashing

### ISSUE THREAD

**Issue by Winterveil** [StrangeLoopGames/EcoIssues#24249]
\
**User Id: (slg236004)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Load into a serve, any server.

**Expected behavior:**
Should load the server

**Actual behavior:**
After the world is 100% loaded the loginscreen freezes for a while an then the eco.exe file stops working.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, none

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by too old CPU, we are looking into if we can do something:
![Uploading image.png…]()

**Comment by Winterveil** [comment]
I see.
Because I ran version 9 on the same architecture without issue. Has something changed in the upgrade to version 10?
