### ISSUE TITLE
USER ISSUE: Baum fällen

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24242]
\
**User Id: (slg222333)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1 Baum fällen
2 versuchen Baum klein zu machen

**Expected behavior:**
Baum sollte anvisierbar sein und man sollte sie klein machen können

**Actual behavior:**
Baum ist nicht anvisierbar und man kann ihn viel zu leicht wegschiebenman kann den baum weder klein hacken noch aufnehmen

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/20414
