### ISSUE TITLE
USER ISSUE: cart tp out of mine and fall throuth the map

### ISSUE THREAD

**Issue by KillitsGaming** [StrangeLoopGames/EcoIssues#24252]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
hi my cart has tp to the top of the Mountain as im ming. and i have gotten stuck between two rocks and fell through the map

**Expected behavior:**
cart stay put as im mining 

**Actual behavior:**
tp out of my mine 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by LamMods** [comment]
I've noticed this can be triggered with a block update (mining rock nearby). When block is broken, cart goes top-side.
Also happening with Powered Carts and Steam Truck.
Using 10.0.2 release-544

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24363
