### ISSUE TITLE
USER ISSUE: canoe turns wrong way

### ISSUE THREAD

**Issue by kittle31** [StrangeLoopGames/EcoIssues#24250]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. paddle canoe for a while
2. press A or D to turn.
3. wait
4. press D or A to turn the oposite dir

**Expected behavior:**
boat turns according to A or D press

**Actual behavior:**
boat turns the oposite dir

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in Update 10.0.2.
