### ISSUE TITLE
USER ISSUE: broken bows

### ISSUE THREAD

**Issue by Vace200026** [StrangeLoopGames/EcoIssues#24254]
\
**User Id: (slg225304)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
grab bow, hunt animals, grab animal, switch to animal in toolbar and put animal in stock. Breaks bow when you go back to it to continue hunting.

**Expected behavior:**
should be able to return to hunting without issues

**Actual behavior:**
cannot shoot bow after doing said actions.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no server is update 10 and no mods at all.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
