### ISSUE TITLE
USER ISSUE: "Your account is Disabled"

### ISSUE THREAD

**Issue by Tyllrrrr** [StrangeLoopGames/EcoIssues#24258]
\
**User Id: ()**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
I Just purchased the game a few days ago. I finally had time to log in and play. Once I had tried to join a server. It said I was disabled!

**Expected behavior:**
I should be able to join the server and play.

**Actual behavior:**
The following error message popped up
```
Invalid login info.

<size=60.00%>Your account has been disabled.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods or anything. Fresh install of the game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please send a mail to support@strangeloopgames.com from the email linked with your SLG account.
