### ISSUE TITLE
SERVER ISSUE: Server does not start

### ISSUE THREAD

**Issue by belaveltrup** [StrangeLoopGames/EcoIssues#24255]
I am hosting an eco server as a vserver from a common website and on startup it does not get past Initializing registrars for InitialSpawnPlugin. It claims it is done after 0,00 seconds but just does not continue. Copying the server files from my local steam server does not help either although it works when i run it from my machine.

**Comment by D3nnis3n** [comment]
Is your operating system Windows instead of Windows Server? Check this:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/3275dc02-864b-45bf-b613-49dc794a46f5)
