### ISSUE TITLE
Alpha 6.0 Server keeps crashing after a restart

### ISSUE THREAD

**Issue by Vigmundr** [StrangeLoopGames/EcoIssues#2425]
One of my members was having an issue picking up a torch from a storage box he made then a wood cart. So i tried to restart the server and it never would load back up. 

https://www.dropbox.com/s/q2p23xtz3ir3hq1/Crash%2009305526.ecodmp?dl=0

https://www.dropbox.com/s/xt17kgvgeecpm2s/Get%20Started%20with%20Dropbox.pdf?dl=0

**Comment by pamduncan** [comment]
Note:  We have had this same issue (either related to torches or wooden carts) causing a crash and then the server stays in a crash state after that.  Santos posted an issue withe  game world regarding this.  Had this same complaint from discord chatters with crash issues on their server forced to start new worlds over and over.  Have asked them to add bug reports with game files and crash logs but many are not doing this

**Comment by metachronism** [comment]
@Vigmundr do you have the server game save available?

**Comment by Vigmundr** [comment]
SantosWorld.eco
  
|  
|    |  
SantosWorld.eco
   |  |

  |

 
 

    On Wednesday, October 4, 2017 1:35 PM, Eric Anderson <notifications@github.com> wrote:
 

 @Vigmundr do you have the server game save available?—

**Comment by Timmay24** [comment]
You need to drag & drop. Not copy & paste! :)

**Comment by metachronism** [comment]
oh this is the santos world?  been working with @pamduncan and we've solved this for now
