### ISSUE TITLE
USER ISSUE: Не создаётся новый мир

### ISSUE THREAD

**Issue by xRAYNERx** [StrangeLoopGames/EcoIssues#24261]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. Нажимаю на "Создать новый мир"
2. Пишу название
3. Ставлю галочку на создание случайного мира
4. Выставляю настройки сервера
5. Нажимаю на "Начать"
6. Вылезает окошко о том, что я хочу создать случайный мир и это может быть долго
7. Нажимаю "Да"

**Expected behavior:**
Начинается генерация нового мира по заданным мной параметрам

**Actual behavior:**
Окошко изчезает, ничего не происходит. Я остаюсь в окне настроек нового мира

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Модификаций нет. Клиент чистый, начал играть пару дней назад. Первый раз мир создался без проблем, через пару дней возникла проблема, я удалил клиент, удалил все оставшиеся данные из папки Steam, но проблема не решилась

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13706105/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13706093/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate.
