### ISSUE TITLE
USER ISSUE: Significant Frames loss

### ISSUE THREAD

**Issue by Duplo52** [StrangeLoopGames/EcoIssues#24263]
\
**User Id: (slg236252)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1. Have a tool or something in hand that will render the green "placement" marker.
2. Switch between open hand and the tool to check frames.	

**Expected behavior:**
It should keep my frames steady 80 like it does when not holding anything.

**Actual behavior:**
FPS becomes erratic, and fluctuates significantly causing distruptive lag by comparison with nothing held.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Duplo52** [comment]
Upon further testing, it happens with each tool when you are looking at their respective uses that generates the green marker. Such as a shovel looking at dirt, however when looking at something the tool cannot harvest the FPS steadies back out.

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)
