### ISSUE TITLE
USER ISSUE: Spook insides / i can see my teeth and eye holes in first person

### ISSUE THREAD

**Issue by adri0477** [StrangeLoopGames/EcoIssues#24266]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
I am not sure
But i joined, played, left, joined, got into my bed in the shack and left to eat.
Now i can see the inside of my own face when in first person

**Expected behavior:**
Should have first person view	

**Actual behavior:**
I can see my the inside of my face teeth eye holes and hair too

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not think so, i joined public server.  Coast redwood

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Update**
i rejoined and now its gone

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13708118/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13708119/Player-prev.log)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/6208803/158d7736-8d7f-4927-852a-2b693d1a3a4f)

**Comment by D3nnis3n** [comment]
Duplicate.
