### ISSUE TITLE
USER ISSUE: Cancel building - doesnt work

### ISSUE THREAD

**Issue by LadyAlicja** [StrangeLoopGames/EcoIssues#24262]
\
**User Id: (slg234459)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
When i want to cancel building i should be able to leftclick in the air so i am able to start my first block again. Now it doesnt work i have to switch tools to cancel.

**Expected behavior:**
cancel buidling on lefclick

**Actual behavior:**
nothing happened

**Do you have mods installed? Does the issue happen when no mods are installed?:**
it happened without mods as well

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed.
