### ISSUE TITLE
Cast IRON STOVE / HOME Cooking missing --> Recipe

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2426]
![grafik](https://user-images.githubusercontent.com/26040573/31056012-bbe4db82-a6cb-11e7-8e8a-a7c4ce55c488.png)

**Comment by Fank** [comment]
Duplicate of #2373

**Comment by REPOSEECO** [comment]
upps soory i search for Cast IRON STOVE / HOME Cooking nothing was found

**Comment by MarjieAVolk** [comment]
Yep probably because it's already been fixed on master.  Will be fixed in the next release
