### ISSUE TITLE
USER ISSUE: Salmon going extinct on Day 1 and 2

### ISSUE THREAD

**Issue by occultsoftworks** [StrangeLoopGames/EcoIssues#24267]
\
**User Id: (slg196528)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
No Reproduction, Salmon are going extinct extremely quickly, I've now been on multiple servers where Salmon are going extinct in Day 1 and Day 2, there's no way we're having that big an impact yet.

**Expected behavior:**
Salmon should not go extinct on day 1 or day 2

**Actual behavior:**
Salmon go extinct on Day 1 or Day 2.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.

**Comment by Zygus42** [comment]
You closed this as a duplicate, but the only item i can find that's even similar is a comment on crocodiles from 2021.  

We have a grand total of 3 people on a large world on our server and we put 3 fish traps in a lake in the jungle and another 3 fish traps in a different lake quite some distance away, and a real world day later we got the salmon have gone extinct message.  

When you look at the populations they used to be in all kind of lakes and rivers all over the world.  

I believe you ought to reopen this issue.

**Comment by D3nnis3n** [comment]
We do have two trackers, this one we just to gather issues from the public. It's in the internal one from playtest.

**Comment by Zygus42** [comment]
Update:  despite the extinction message, I just caught a Salmon while ocean fishing with a fishing rod.  So maybe just the message is bung ?

**Comment by D3nnis3n** [comment]
Yes, the issue is only the message, nothing is actually extinct.
