### ISSUE TITLE
Deadeyes-LP: wasser bug

### ISSUE THREAD

**Issue by Deadeyes-LP** [StrangeLoopGames/EcoIssues#24265]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
ich wollte wasserräder zur energy gewinnung mit ein aquaduckt und einer pumpe aufbauen dabei habe ich eins der rohre abgebeut ,dabei ist mir das wasser durch die blöcke in denn boden gelangt jetzt bekomme ich das wasser was jetzt ein block hoch auf dem boden wabelt nicht mehr weg weder wenn ein raum drum baue noch wenn ich es mit erde aufschütte

**Expected behavior:**
das wasser was ich mit dem pumpen nach oben zu dem wasserräden pumpe treiben die räder danach sollte das wasser durch das aquaduckt wieder in meer gelangen 

**Actual behavior:**
das aquaduckt habe ich um sonst gebaut da das wasser vor dem wasserräden einfach in denn boden geht und jetzt nach dem abbau sich nicht mehr enternen lässt . ich habe es versucht auf zuschütten  und es versucht in ein raum es auf zuschütten selbst mit dem dev tool lässt es sich nicht entfernen .

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein, und ja

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Bereits behoben.
