### ISSUE TITLE
USER ISSUE: Bow & Arrow not firing correctly

### ISSUE THREAD

**Issue by LunaFirebear** [StrangeLoopGames/EcoIssues#24269]
\
**User Id: (slg235564)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
After knocking an arrow and lining up a shot, you don't get the trajectory line to indicate where your arrow is aimed. There's really no sure way to recreate this bug.

**Expected behavior:**
It should have given the line of sight to showcase where the arrow is going.	

**Actual behavior:**
Does nothing, and an arrow is wasted.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes mods, yes it still happens with them not installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
