### ISSUE TITLE
USER ISSUE: Barrows that contained Tails were teleported from underground to the surface above

### ISSUE THREAD

**Issue by sanisenk** [StrangeLoopGames/EcoIssues#24268]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Barrows were standing in a big underground hall, 30+ deep to the surface, non overlapping and stable positions. They were standing on unclaimed territory

This happened while I was offline
**Expected behavior:**
They stay where they were

**Actual behavior:**
they teleported to the surface exactly above their previous location

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
