### ISSUE TITLE
USER ISSUE: says invalid login

### ISSUE THREAD

**Issue by Nolanwest** [StrangeLoopGames/EcoIssues#24278]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
login to a server	

**Expected behavior:**
i should normally just login

**Actual behavior:**
it wont let me

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by mberatsanli** [comment]
same issue

**Comment by Nolanwest** [comment]
with as little people that it says are online. I think alot of people are having this problem. normally there are 100's of ppl. the most active server today said 16 people online. (not sure how they got the game to work though.)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
