### ISSUE TITLE
Alpha 6 - Crashed servers, store related 

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#2427]
Discovered server crashed when using the store and forced continuous crashes until i removed the stores from the game.eco file. For now it seems stores can not be used as this keeps happening, but we can not duplicate it exactly it just seems to happen during transactions. Players also reported not receiving the item they bought but the quantity they purchased in another item. (ie bought 7 meat, 1 store.. received 7 stores even tho only 1 store was removed from the crate and no meats removed)
seems like 2 different issues, unknown at this time. 
[Crash 10011811.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1347298/Crash.10011811.txt)

spoke with other server owners, they reported similar issues crashing their servers and had to remove stores from their game.eco as well.

**Comment by RowanJones** [comment]
Can confirm, we had this issue. 

When we deleted the Store on the 327th server, Decens was able to rejoin us.

**Comment by excedra** [comment]
#2433

**Comment by noblackthunder** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2434

**Comment by RowanJones** [comment]
The 327th server is now having this issue, we can't have folks log in without it crashing. 

[327_Server_DumpFolder.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1354033/327_Server_DumpFolder.zip)

**Comment by stormoffires** [comment]
Temp work around for all is open game.eco and delete all stores inside worldobjects

**Comment by MarjieAVolk** [comment]
Think I've got a fix for this - it seems this happens only if the store is unowned
