### ISSUE TITLE
USER ISSUE: Défaut de chargement de la partie

### ISSUE THREAD

**Issue by landryc31** [StrangeLoopGames/EcoIssues#24276]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Chargement de la partie

**Expected behavior:**
il aurait du démarrer

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by landryc31** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718016/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718019/Player-prev.log)

**Comment by landryc31** [comment]
j'ai trouvé 3 fichiers corrompus (en vérifiant les fichiers installés avec Steam).
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718124/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718127/Player-prev.log)

meme issue : crash du chargement

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
