### ISSUE TITLE
USER ISSUE: can't create a new local world

### ISSUE THREAD

**Issue by krakhot** [StrangeLoopGames/EcoIssues#24275]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
clicking host a world
change the generation to be random
try to create the world

**Expected behavior:**
start the generation process

**Actual behavior:**
nothing happens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods. nothing else running on the computer. i've been able to do this step multiples time before without an issue

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in Update 10.0.2.
