### ISSUE TITLE
USER ISSUE: Kein Titelbildschirm

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24279]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Spiel Starten

**Expected behavior:**
Hauptmenü 

**Actual behavior:**
nichts!

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NEIN

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
