### ISSUE TITLE
USER ISSUE: no main menu

### ISSUE THREAD

**Issue by EnderButter1** [StrangeLoopGames/EcoIssues#24284]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
open game, no main menu.

**Expected behavior:**
popped up.

**Actual behavior:**
no buttons. just background and noise.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
