### ISSUE TITLE
USER ISSUE: Kein Menü

### ISSUE THREAD

**Issue by McZachi** [StrangeLoopGames/EcoIssues#24286]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Starte Steam
2. Starte Eco

**Expected behavior:**
Das Hauptmenü von ECO erscheint und ich kann mit der Maus mein gewählten Punkt auswählen.

**Actual behavior:**
Es ist nur der Hintergrund zu sehen. Das Menü ist nicht dort und ich kann die Maus nicht bewegen. Nur ESC drücken und Einstellungen vornehmen ist möglich.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NEIN

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
