### ISSUE TITLE
USER ISSUE: No Menu

### ISSUE THREAD

**Issue by Chefromancer** [StrangeLoopGames/EcoIssues#24285]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Launch Game

**Expected behavior:**
It should have shown the main menu.

**Actual behavior:**
Instead it shows no menu.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
