### ISSUE TITLE
Alpha.6 Excavator balance recommendations

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2428]
Currently it requires Lumber to build:
![image](https://user-images.githubusercontent.com/1900106/31056500-d87bf44a-a6d2-11e7-9106-cff6e2a70216.png)

We worked with the excavator some days and noticed that following should be changed:
- Recipe:
  - [ ] Steel instead of Lumber
  - [ ] Gearboxes instead of gears
- [ ] More receipts because its a powerfull tool to mine materials (large amount).
- [ ] Longer building time, 5 min is quite to short for such large and usefull vehicle.
- [ ] More weight? currently its has a weight of 25kg, this should be increased.
- [ ] A better icon would be nice.

**Comment by stormoffires** [comment]
I changed ours to require steel and most gears, i do like gearboxes thats a good idea. also increased time. Most of these can be changed per server easily but i agree this should be base for the excavator.
