### ISSUE TITLE
USER ISSUE: Menu principal qui ne s'affiche pas

### ISSUE THREAD

**Issue by ludohypermobile** [StrangeLoopGames/EcoIssues#24280]
\
**User Id: (slg98599)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Dès le démarrage du jeu depuis la 10.0.2 problème avec le menu principal 

**Expected behavior:**

**Actual behavior:**
Il ne s'affiche pas et seul le fond d'écran reste

**Do you have mods installed? Does the issue happen when no mods are installed?:**
oui big shovel

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ludohypermobile** [comment]
Sorry, I just read that it's a server problem

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
