### ISSUE TITLE
USER ISSUE: several bugs

### ISSUE THREAD

**Issue by 3punt1415** [StrangeLoopGames/EcoIssues#24287]
\
**User Id: (slg55038)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Auth server doesn't seem to be working, connected to a private server that I just updated to 0.10.0.2 through steamcmd.
Also the main menu doesn't work 90% of the time, even after validating the game files, reinstalling the game, restarting the pc and updating the video drivers

**Expected behavior:**
main menu shows when starting the game and being able to connect to servers

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718318/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718319/Player-prev.log)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
