### ISSUE TITLE
USER ISSUE: No response from auth server/Invalid login info after 10.0.2

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#24283]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Trying to log into my server.

Other details:
I was able to log in when it was 10.0.1, I own and manage the server.

When the update happened to 10.0.2, I got kicked from the server and then upon trying to rejoin, realized there was an update as I could no longer join bceause the versions were different.

I closed Eco, waited for Steam to trigger the update, and then logged back in.

Now I get this error every time I try to join.I've tried restarting the server, I've tried disabling authentication, the error still comes up.

**Expected behavior:**
I should be able to log in

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IneaFaedyn** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718205/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718206/Player.log)

**Comment by IneaFaedyn** [comment]
From the server, /Logs/Eco.WebServer.Web.EcoAuthentication
[2023-12-19.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718230/2023-12-19.log)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
