### ISSUE TITLE
USER ISSUE: Hotfix 10.0.2 Broke the Game

### ISSUE THREAD

**Issue by cjblaney0** [StrangeLoopGames/EcoIssues#24282]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Download latest hotfix and launch the game.

**Expected behavior:**
Main Menu loads and I'm able to join a server.

**Actual behavior:**
Opening background loads (docks, boats going by) but the menu does not appear.  

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13718160/Player-prev.log)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
