### ISSUE TITLE
USER ISSUE: i keep getting Invalid Login info.

### ISSUE THREAD

**Issue by Mariona42** [StrangeLoopGames/EcoIssues#24289]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
after the 10.0.2 update I then back installed 10.0.1 and now when I try and login I get this message "Invalid Login info."

**Expected behavior:**
it should have just logged into the server I have been playing on

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
