### ISSUE TITLE
USER ISSUE: Pas de menu

### ISSUE THREAD

**Issue by MerciMathieu** [StrangeLoopGames/EcoIssues#24297]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Allumer le jeu, vouloir jouer

**Expected behavior:**
Un menu pour pouvoir lancer une partie

**Actual behavior:**
Il n'y a pas de menu permettant de pouvoir jouer au jeu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non pas de mods d'installés²

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by MerciMathieu** [comment]
J'ai retrouvé le menu principal du jeu en modifiant le paramètre graphique: [fenêtré, sans bordures, ... ] et en appliquant le paramètre

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
