### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Sheo42** [StrangeLoopGames/EcoIssues#24290]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. try to connnect after last patch
2. invalid login info

**Expected behavior:**
logged into the server

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods as far as I know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
