### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Vinkatsukii** [StrangeLoopGames/EcoIssues#24293]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
Lancer le jeu tout simplement lol

**Expected behavior:**
avoir un menu et une souris qui bouge

**Actual behavior:**
aucun menu et souris bloqué au millieu de l'écran

**Do you have mods installed? Does the issue happen when no mods are installed?:**
rien de rien, desinstaller réinstaller, fermer steam, redémarer le pc j'ai eu le menu 2 fois sur 20 et quand je l'ai j'ai "invalid login info" mdrr en plus quand il y a une mise à jour ça full bug les server acheté, impossible de faire les maj server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
