### ISSUE TITLE
USER ISSUE: Invalid login info

### ISSUE THREAD

**Issue by Mariona42** [StrangeLoopGames/EcoIssues#24295]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
i keep getting "Invalid login info" every time I try and connect to any server and I have resinstalled 3 times, and checked the integrety 6 times, while also changing the version around 3 times. i keep getting "Invalid login info"

**Expected behavior:**
it should have just logged me in

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
