### ISSUE TITLE
USER ISSUE: No main menu after update 10.0.2

### ISSUE THREAD

**Issue by Nirmaeth** [StrangeLoopGames/EcoIssues#24306]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Just downloaded update 10.0.2 released today
2. Launch the game
3. Arrive at the main page with the harbor cinematics displaying	

**Expected behavior:**
There should be a main menu with the possibility to create or join a world, like "new game", "continue", "host a world", etc ...

**Actual behavior:**
Instead, there is no main menu ; hence I cannot create or join a world.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed - Please note I have 3 other friends who reported me the same problem at the moment

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Darkhand81** [comment]
Related, no users are able to authenticate after this patch either, all are failing with auth timeouts:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/1334381/7d198dc6-f5b9-4fdd-8344-64e0b3c3e501)

**Comment by TL044CN** [comment]
> Related, no users are able to authenticate after this patch either, all are failing with auth timeouts:
> 
> ![image](https://private-user-images.githubusercontent.com/1334381/291671776-7d198dc6-f5b9-4fdd-8344-64e0b3c3e501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTM3MjYsIm5iZiI6MTcwMzAxMzQyNiwicGF0aCI6Ii8xMzM0MzgxLzI5MTY3MTc3Ni03ZDE5OGRjNi1mNWI5LTRmZGQtODM0NC02NGUwYjNjM2U1MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTkxNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFlYTYwZWMxMjM0ZGU4ZjY5OWNkODFkZWRhYjA3ZTJjZGMyYzA5Yjk5NWMyODA4OGUwYzAxMmMwOWY2MjhmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O5lsL9MLwtd1ESCGdB4gnY3pQSKxsWS1p7whnv9daC0)

It might be wise to not expose verify tokens. But I don't host a server so I don't know if it is relevant here.

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
