### ISSUE TITLE
USER ISSUE: Das Startmenü feht

### ISSUE THREAD

**Issue by TalonZorch** [StrangeLoopGames/EcoIssues#24309]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Starte das Spiel. Kein Startmenü da!

**Expected behavior:**
Startmenü sollte da sein

**Actual behavior:**
Kein Startmenü da!

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Keine Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
