### ISSUE TITLE
USER ISSUE: No Menu

### ISSUE THREAD

**Issue by duckkyz** [StrangeLoopGames/EcoIssues#24308]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Open game client

**Expected behavior:**
To show main menu

**Actual behavior:**
Just the animated town behind menu shows. Unable to join game or do anything unless I hit escape, even then all I can do is report bugs or exit.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
