### ISSUE TITLE
USER ISSUE: Main menu literaly gone+cant connect to any server

### ISSUE THREAD

**Issue by exiom123** [StrangeLoopGames/EcoIssues#24300]
\
**User Id: (slg97121)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Downloaded newest update 10.0.2
Enjoy not having menu and watch the video in background endlesly

**Expected behavior:**
earesed whole main menu

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods vanilla only

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
