### ISSUE TITLE
USER ISSUE: Game has no menu on homescreen since latest patch

### ISSUE THREAD

**Issue by r4z0rw1r3** [StrangeLoopGames/EcoIssues#24303]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Installed latest micropatch 19th Dec 2023, loaded game through Steam

**Expected behavior:**
Play the game

**Actual behavior:**
Game loads to main screen but no menu there to interact with. Had to press Esc and keep clicking mouse for a while until the pointer/cursor actually appeared.  THat's how I was able to write this report. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I've only just begun to play (2 days), I have nothing other than the base game installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
