### ISSUE TITLE
USER ISSUE: Failed to log into server

### ISSUE THREAD

**Issue by Kuronymous** [StrangeLoopGames/EcoIssues#24307]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Failed to load server, error occured while still at loading screen.

**Expected behavior:**
Should have connect me to server to play.

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods at all.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by borodac** [comment]
add
[log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13718922/log.txt)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
