### ISSUE TITLE
USER ISSUE: No MENU

### ISSUE THREAD

**Issue by Pozzi98** [StrangeLoopGames/EcoIssues#24305]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
START THE GAME

**Expected behavior:**
MENU APPEAR AFTER THE LOADING

**Actual behavior:**
I ONLY SEE THE BACKGROUND IMAGE, NO BUTTON AT ALL

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Pozzi98** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/70700124/77d4c1bd-8083-40cc-bcb7-7f993c83cd48)

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
