### ISSUE TITLE
reputation points not resetting "daily"

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#2430]
Is this an issue across the board? or isolated.

**Comment by Emguy158** [comment]
An issue across the board I believe. We are having the same issue

**Comment by MarjieAVolk** [comment]
So when you say "daily" in quotes, why is that?  It's not resetting daily; how often is it resetting?

Based on the code it looks like it should reset everyone once every 24 hours; should be based on the age of the server, so it may not be the same time of day if the server goes down for some amount of time.  Is that not what you are seeing?

Just throwing out a theory, do you think restarting the server messes up the reset time?

**Comment by stormoffires** [comment]
I would say yes BUT our server has finally gone 2 days with no restarts and i am still sitting at 0 rep points to hand out after my initial 10.

**Comment by ecoemmeck** [comment]
I can confirm this issue on our 2 public Aussie servers I haven't been able to give reputation since the first time I gave reputation

**Comment by johnkslg** [comment]
Thanks guys, found the problem and got a fix coming

**Comment by johnkslg** [comment]
Fixed
