### ISSUE TITLE
USER ISSUE: game broken

### ISSUE THREAD

**Issue by iverhvidsten** [StrangeLoopGames/EcoIssues#24301]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. launch game
2. not launched game
3. report bug
4. somehow it works 
5. generate random seed
6. after 2 min generation 
7. failed
8. game not work anymore, but esc button do

**Expected behavior:**
worked

**Actual behavior:**
crashing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
