### ISSUE TITLE
USER ISSUE: Unable to access main menu

### ISSUE THREAD

**Issue by RobertKloster** [StrangeLoopGames/EcoIssues#24319]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Start the game

**Expected behavior:**
Shown me options like "new game", "continue game", etc.

**Actual behavior:**
Doesn't.  Hitting escape still brings up the settings menu, at least.  

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have mods installed. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
