### ISSUE TITLE
Alpha.6 Very high jumps near glas

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2431]
https://loli.temel.me/BBiyqs2uBXE0Hk1MsasDcniClg7zmd6B.mp4

**Comment by MarjieAVolk** [comment]
Think this is a side effect of clambering probably.

**Comment by Fank** [comment]
But its turned off, shown in end of video

**Comment by MarjieAVolk** [comment]
Oh, didn't see that
