### ISSUE TITLE
USER ISSUE: Main menu not loading

### ISSUE THREAD

**Issue by ben-piggott** [StrangeLoopGames/EcoIssues#24315]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Open the game with the new 10.0.2 Hotfix

**Expected behavior:**
Main menu GUI loads in

**Actual behavior:**
The menu world loads but no GUI loads. Settings can be accessed by hitting ESC.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
