### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Pakka77** [StrangeLoopGames/EcoIssues#24314]
\
**User Id: (slg235845)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
