### ISSUE TITLE
USER ISSUE: Невозможно войти в локальный мир

### ISSUE THREAD

**Issue by FerretWM** [StrangeLoopGames/EcoIssues#24311]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Сценарий 1:
1) Открыть ваши миры
2) Выбрать локальный мир созданный на текущей версии

Сценарий 2:
1) Нажать новая игра
2) Создать новый локальный мир

**Expected behavior:**
Успешный вход в локальный мир

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Модификаций нет. Используется чистый клиент

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
