### ISSUE TITLE
USER ISSUE: Linux no Ingame Voice chat at all

### ISSUE THREAD

**Issue by TL044CN** [StrangeLoopGames/EcoIssues#24313]
User Id: (Not logged user)
Version: 0.10.0.1 beta release-535

Steps to Reproduce:
1. start the game
2. enter any world with voice chat activated
3. proceed to not hear anything and be unable to talk.

Expected behavior:
Hearing Voice chat when someone nearby is talking
Being able to talk by pressing and holding 'T'

Actual behavior:
No Voice chat

Do you have mods installed? Does the issue happen when no mods are installed?:
No
Yes

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13719170/Player.log)

# Hardware:
```
 $> neofetch
 tl044cn@tl044cn-spectre 
 -----------------------  
 OS: KDE neon 5.27 x86_64  
 Host: Z790 UD AX 
 Kernel: 6.2.0-39-generic 
 Uptime: 8 mins 
 Packages: 2589 (dpkg), 14 (flatpak) 
 Shell: fish 3.6.4 
 Resolution: 2560x1440, 2560x1440, 1920x1080 
 DE: Plasma 5.27.10 
 WM: KWin 
 Theme: [Plasma], Breeze [GTK2/3] 
 Icons: Lyra-blue-dark [Plasma], Lyra-blue-dark [GTK2/3] 
 Terminal: konsole 
 Terminal Font: CaskaydiaCove Nerd Font Mono 12 
 CPU: 13th Gen Intel i9-13900K (32) @ 5.500GHz 
 GPU: Intel Device a780 
 GPU: NVIDIA GeForce RTX 3080 Ti 
 Memory: 4611MiB / 64060MiB
```

**Comment by D3nnis3n** [comment]
Voice chat doesn't work on linux clients, as its not available from Vivox.
Linux clients also aren't supported for Eco.
