### ISSUE TITLE
USER ISSUE: Unable to join a game

### ISSUE THREAD

**Issue by Ephasius** [StrangeLoopGames/EcoIssues#24312]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
New game - select any. Attempt to join

**Expected behavior:**
Connects to host

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and not tested

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
