### ISSUE TITLE
USER ISSUE: Cannot enter game. No main menu

### ISSUE THREAD

**Issue by knesru** [StrangeLoopGames/EcoIssues#24316]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Update to the last version 10.0.2
Run game

**Expected behavior:**
I should see main menu	

**Actual behavior:**
I don't see any controls at all. Only ESC + settings are avail

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.

**Comment by Flamester** [comment]
Same issue.
