### ISSUE TITLE
USER ISSUE: Can't connect to server!

### ISSUE THREAD

**Issue by Higgs1** [StrangeLoopGames/EcoIssues#24310]
\
**User Id: (slg189320)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Open Eco client
2. Wait for client to reach main menu
3. Try to connect to server
4. **** **** **** ****

**Expected behavior:**
Connect to server and play

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
