### ISSUE TITLE
USER ISSUE: Main menu options are missing

### ISSUE THREAD

**Issue by crazytwelve** [StrangeLoopGames/EcoIssues#24318]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.1 beta release-535

**Steps to Reproduce:**
1.start the game
2.you will see options are missing

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.
