### ISSUE TITLE
USER ISSUE: "No response from Auth Server"

### ISSUE THREAD

**Issue by regctx** [StrangeLoopGames/EcoIssues#24323]
\
**User Id: (slg186070)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. click on join server

**Expected behavior:**
logged into server

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS Fresh server OS install. steamCMD to install game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now. If it persists for you, please reach out to support@strangeloopgames.com.
