### ISSUE TITLE
USER ISSUE: Kicked from games and can't log back in

### ISSUE THREAD

**Issue by FeniRisin** [StrangeLoopGames/EcoIssues#24326]
\
**User Id: (slg124207)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Play Eco

**Expected behavior:**
kept me in the world

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by FeniRisin** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13721528/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13721531/Player-prev.log)

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/24380
