### ISSUE TITLE
Enhancement Request for 6.0

### ISSUE THREAD

**Issue by RowanJones** [StrangeLoopGames/EcoIssues#2432]
Could we please have:

1) /Unrestrict  be returned to the game, for admin purposes.
2) A way to delete items, as was able in 5.6 with the Devtool, for admin purposes.

Thank you <3

**Comment by MarjieAVolk** [comment]
I'm going to add some variants on /dump that can help admins get rid of things more easily: /dump selected, and /dump carried (should be self explanatory?).

**Comment by RowanJones** [comment]
that would actually be radical, the only reason i ever use dump is to get rid of excess. We used to use the devtool to delete storage chests and items contained therein to do so. Having a way to delete items is handy for admin purposes.

**Comment by MarjieAVolk** [comment]
@metachronism Do we want to continue to support /unrestrict or not?

**Comment by metachronism** [comment]
sorry, unrestrict was only valid with the old inventory system - the way things have been restructured makes unrestrict non-viable
