### ISSUE TITLE
Using Legacy Civics Constitution Nullifies after 30 Minutes

### ISSUE THREAD

**Issue by Necrodemus** [StrangeLoopGames/EcoIssues#24324]
Version: 0.10.0.2 beta release-544

Steps to Reproduce:
1. Disable New Settlement Features in Features.eco via "SettlementSystemEnabled": false,
2. Place Capitol in Appropriate Building
3. Create / Ratify Constitution with either /elections win or with majority vote.
4. Wait for Civics update to occur.
5. All other civic buildings are disabled due to lack of constitution.

Expected behavior:
Constitution / Civics remain in place when new settlement system is set to false.

Actual behavior:
Constitution / Civics show "Constitution *deleted* Old (removed) is not currently active."

Do you have mods installed? Does the issue happen when no mods are installed?:
Have attempted on 2 servers one with and without mods. Happens regardless of mods.

Server Log:
[log_231219025534.log](https://github.com/StrangeLoopGames/EcoIssues/files/13720199/log_231219025534.log)

ScreenShot:
![eco_civics_issue_10 2](https://github.com/StrangeLoopGames/EcoIssues/assets/8109367/7e1ca24f-10a0-4679-b71a-d9f910a55b21)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
