### ISSUE TITLE
USER ISSUE: 71b per second??????

### ISSUE THREAD

**Issue by theronhh** [StrangeLoopGames/EcoIssues#24322]
\
**User Id: (slg125001)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
load lokal server created with version 9

**Expected behavior:**
quick downloading of the world map at lokal server

**Actual behavior:**
max download bitrate at 20% of world downloading at 71byte per sec :(

**Do you have mods installed? Does the issue happen when no mods are installed?:**
vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Opening a migrated world can take a time, you are not actually downloading anything.
