### ISSUE TITLE
USER ISSUE: No menu

### ISSUE THREAD

**Issue by JoshuaASears** [StrangeLoopGames/EcoIssues#24320]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Launch Game from Steam 

**Expected behavior:**
To see the background and a top level menu where I can select options like, "continue," "new world," "settings," or "exit game"

**Actual behavior:**
I just see the background animation. No menu options. Can't play, have to alt+f4 to exit.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods. this is top level. I just installed the update. This happened, and so I restarted my computer. Same issue. Can't play the game.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by an attack on our backend systems, should be resolved now.

**Comment by FrederikP** [comment]
Same is happening to me right now. I can press escape to see the options and quit the game. No main menu though. Worked fine about 1,5h ago
