### ISSUE TITLE
USER ISSUE: Broken settlement system.

### ISSUE THREAD

**Issue by BlueDevil89** [StrangeLoopGames/EcoIssues#24327]
\
**User Id: (slg233916)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Claims are not working with settlement turned off. Claims I need to have 50% inside parent settlement.

**Expected behavior:**
Should let me claim as much area as I want with settlement turned off.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at E</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
