### ISSUE TITLE
USER ISSUE: Game is missing Poutine

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24339]
\
**User Id: (slg233066)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Look through recipies for Poutine

**Expected behavior:**
Have Poutine

**Actual behavior:**
Does not have Poutine.
Why do you all hate deliciousness?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, and no Poutine!

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not a bug?
