### ISSUE TITLE
USER ISSUE: Everyone demographic missing / deleted

### ISSUE THREAD

**Issue by Larslol140** [StrangeLoopGames/EcoIssues#24336]
\
**User Id: (slg136695)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Unsure, but we did the recent things:
1. Created a settlement
2. Turned off settlements in the server settings
3. Reverted most buildings etc.

**Expected behavior:**
Everyone demographic should still be there.

**Actual behavior:**
Everyone demographic is deleted.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13730471/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13730472/Player-prev.log)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25729499/5b3d979c-6f60-441f-8025-acc9998eff1d)

**Comment by Larslol140** [comment]
Demographic came back after a restart with Settlements Feature enabled again. I wasn't able to start the Server and needed to revert the setting back to disabled.

**Comment by D3nnis3n** [comment]
Settlements off has multiple issues currently that were already reported, including contained civics not considered valid. You can set a really high amount of minuts in Civics.eco for  "AllowInvalidCivicContainerTimeInMinutes", to prevent them to get deleted. Issue has already been reported, so closing as duplicate.
