### ISSUE TITLE
USER ISSUE: Server not Responding, not solved

### ISSUE THREAD

**Issue by Tollwutmolle** [StrangeLoopGames/EcoIssues#24331]
![20231220101835_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153803425/cc69c4f5-4e1d-4d5a-bcf6-f0bd97b740de)
![20231220101839_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153803425/543591ec-7246-4d68-aa50-0e3d4c077848)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13725460/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13725461/Player-prev.log)
\
**User Id: (slg166425)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Connect to any server, official or private,
server download all, and freeze/ stays at "Load world 100%"
after a few seconds come the error "Server not responding" 

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Tollwutmolle** [comment]
Ok, i find out, the error only comes, if i use my Handy as a hotspot for my PC, if i use a router, the error not comes

**Comment by D3nnis3n** [comment]
It is possible that the provider for the mobile internet does not allow connection to our services or that cloudflare blocks such connections due to them being shared. Unfortunately there is nothing we can do about that.
