### ISSUE TITLE
USER ISSUE: Voice chat displays non talking players

### ISSUE THREAD

**Issue by Larslol140** [StrangeLoopGames/EcoIssues#24335]
\
**User Id: (slg136695)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Join on server
2. Play a bit, on the right side names appear, including "Player name"

**Expected behavior:**
Do not show any names since voice chat is not utilized on the server, means no one is or was talking.

**Actual behavior:**
List increases over time and names won't disappear even when going away from the player.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13730329/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13730330/Player.log)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25729499/1d7bfc91-cd4d-4a10-b4b9-ff5425b95a2e)

**Comment by D3nnis3n** [comment]
Duplicate.
