### ISSUE TITLE
USER ISSUE: 100% WT stuck

### ISSUE THREAD

**Issue by VolodymyrB** [StrangeLoopGames/EcoIssues#24338]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
1. Load WT
2. Loading stucks on 100%

**Expected behavior:**
Loading WT

**Actual behavior:**
The following error message popped up:
```
Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by VolodymyrB** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13732641/Player.log)

**Comment by VolodymyrB** [comment]
Seems I had so test branch, the game previously moved me to the main branch and now back to so

**Comment by D3nnis3n** [comment]
Reported fixed in 10.0.3
