### ISSUE TITLE
Settlement picture doesn't show updated picture name

### ISSUE THREAD

**Issue by DragonDev1906** [StrangeLoopGames/EcoIssues#24337]
## Steps to reproduce
- Make a picture (e.g. taken with an easel in this case)
- Rename the picture
- Put it into the foundation as a settlement picture
- Go into the tooltip of the settlement

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/8270201/f22c4c85-eb12-40a8-9455-10bd642ef3bb)

**Comment by D3nnis3n** [comment]
Was the server restarted since then and did that fix it?

**Comment by DragonDev1906** [comment]
Wasn't restarted yet, I'll be able to answer the second part tomorrow after the restart.

**Comment by iuriguilherme** [comment]
I have that and server restarts "fixes" it. Tooltips don't get updated until server restart. Chat markups and opening the picture window shows the correct name.

**Comment by DragonDev1906** [comment]
Can confirm, the server restart fixed this (since some tooltips are re-generated when something changes I thought this would be the case with this, too).
