### ISSUE TITLE
USER ISSUE: Kein Material auf der Schaufel

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24345]
\
**User Id: (slg222333)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Schaufel aurüsten
Material abbauen

**Expected behavior:**
Material wird unten angezeigt und kann von der Schaufel zb auf einen Wagen geladen werden	

**Actual behavior:**
Es wird kein Material angezeigt und man kann es nicht mehr verladen, nach einem Relog wird das Material auf der Schaufel (inklusive anzeige) wieder anzeigt und kann verladen werden

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24499
