### ISSUE TITLE
Boat Mooring rope showing pink overlay

### ISSUE THREAD

**Issue by LamMods** [StrangeLoopGames/EcoIssues#24343]
10.0.2 - Playing Single Player game (no collab) and on launching the game today my boats are showing the mooring ropes as well as a pink overlay, as if debugging was showing the bounding area or the raycast.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/13630899/f0d3c3b4-6527-4a95-9f70-ddbbf77ee5a7)

Unticking the ropes from the mooring post does not remove the rope. Moving the boat is possible, however, the rope is still attached. Pink rope does not move as if it where still connected to boat at original position.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/13630899/c0786da6-73d3-4c44-b0a4-9c7ededf9dab)

-edit
Removing the boat or the mooring post does not remove the rope from the world. Reloading from main menu fixes regular ropes rendering, not pink ropes. Quit client and reload world: pink ropes gone, although persistent rope issue remains.

**Comment by LamMods** [comment]
Likely related to [issue 24114](https://github.com/StrangeLoopGames/EcoIssues/issues/24114)

**Comment by LamMods** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13741650/Player.log)

**Comment by D3nnis3n** [comment]
Not reproducible, still persistent for you?

**Comment by LamMods** [comment]
Pink rope appears to be gone, however, the rope still appears attached to the boat after unticking it in the moorage post and I can drive the boat with the rope attached until I next log out/in.

**Comment by D3nnis3n** [comment]
Alright, that is tracked in https://github.com/StrangeLoopGames/EcoIssues/issues/24114
