### ISSUE TITLE
USER ISSUE: Account disabled after refunding the game and repurchasing

### ISSUE THREAD

**Issue by IrvNation** [StrangeLoopGames/EcoIssues#24342]
\
**User Id: ()**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Own game on steam and refund. 3 days later repurchase game. Attempt to join server.

Account seems to be disabled both in game and on website.

**Expected behavior:**
Should be able to enter a server without issue		

**Actual behavior:**
Error Message: Invalid Login Info   -   Account Disabled.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IrvNation** [comment]
[Error Details.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13738343/Error.Details.txt)

**Comment by D3nnis3n** [comment]
Accounts will automatically unlock within 24 hours after repurchase once ownership is confirmed by Steam, reach out to support@strangeloopgames.com, they may be able to speed that up.
