### ISSUE TITLE
USER ISSUE: Resource Gathering

### ISSUE THREAD

**Issue by Watrbouy** [StrangeLoopGames/EcoIssues#24348]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
When chopping down trees i am not always able to select logs to "break down"  

**Expected behavior:**
Allow me to select item to "break down further".  This mostly happens when chopping down trees, but sometimes when I am Mining as well. 

**Actual behavior:**
The log in question does not highlight or become selected

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13744307/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13744309/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate.
