### ISSUE TITLE
USER ISSUE: Disappearing items after buying from shop

### ISSUE THREAD

**Issue by RHAtHome** [StrangeLoopGames/EcoIssues#24349]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Go to a shop and buy goods. I noticed (after the trade) my inventory was full (as in max weigtht was reached, there were still empty slots). It probably got full while buying the goods. A small part of the goods were put in my inventory. All others were sold (the logs confirm this) but are not in my inventory, not in the shop and not on the floor. They also did not teleport to the roof above the store.

**Expected behavior:**
It should have all been in my inventory, or not have been sold and gave me a message i could not carry this load.

**Actual behavior:**
I paid for all the good, the goods were sold, but only a part of them were put in my inventory, all others are probaby in a parallel universe chilling on the beach while drinking cocktails and watching a beautiful sundawn.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13744367/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13744368/Player-prev.log)

**Comment by D3nnis3n** [comment]
It's possible they were sent to an accepting vehicle or storage around, was there anything like that?

**Comment by RHAtHome** [comment]
Yes there was. We just found out this person had a wheelbarrel i had access to. You are completely correct! Consider this issue as solved.

**Comment by D3nnis3n** [comment]
Thanks for letting me know, happy playing!
