### ISSUE TITLE
USER ISSUE: Florida zoning/law not working. 

### ISSUE THREAD

**Issue by Mystical777Jasper** [StrangeLoopGames/EcoIssues#24357]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
try digging the dirt block at 420,61,1063. this is not in a zone of florida and should not be restricted

**Expected behavior:**
i should be able to dig it

**Actual behavior:**
i cant dig it, says i am in a zone. i am not in the zone

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please contact your server administrator about this and check the law. If they note a bug, please let them report it, as we are unable to investigate with the information given here, not even knowing what "Florida" is or what server this might be on or who its owned by.
