### ISSUE TITLE
USER ISSUE: bloqué sur une ile

### ISSUE THREAD

**Issue by plan-e-sphere** [StrangeLoopGames/EcoIssues#24353]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
aller sur une île de biome désertique, quand on a trop faim on ne peut pas repartir on est bloqué sur l'ile, on ne peut pas chasser, il y a aucune nourriture

**Expected behavior:**
utiliser un bateau ne devrait pas couter de l'énergie

**Actual behavior:**
toutes les actions coute de l'énergie je suis bloqué sur l'île sans pouvoir rien faire

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
If you are using singleplayer, you have access to admin commands like /fly and /tp for teleporting. On multiplayer servers an admin should be able to help you.
