### ISSUE TITLE
USER ISSUE: Übersetzung

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24354]
\
**User Id: (slg222333)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Medium Wooden Ship Frame Item - Mittler Holzschiffsrahmen wird aber immoment mit Großer Holzschiffsrahmen übersetzt bitte ändern

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Die Übersetzungen werden von der Community erstellt, darauf haben wir keinen Einfluss, bitte ggf. hier melden oder korrigieren: https://crowdin.com/project/eco-by-strange-loop-games
