### ISSUE TITLE
Alpha.6 Chat text will shown on both location until pressing "c"

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2435]
After connect:
![image](https://user-images.githubusercontent.com/1900106/31078904-34e09090-a784-11e7-8ccc-b5f9559807ff.png)

If i press "c":
![image](https://user-images.githubusercontent.com/1900106/31078914-3ebc7746-a784-11e7-8922-515166aab5d7.png)

If i press "c" again:
![image](https://user-images.githubusercontent.com/1900106/31078922-45f0ec0e-a784-11e7-9a8e-f4a04afc0159.png)

**Comment by MarjieAVolk** [comment]
This is already fixed on master, will be fixed in next release
