### ISSUE TITLE
USER ISSUE: Extreme einbrüche bei Glaswänden

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24368]
\
**User Id: (slg222333)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Dünen Glaswände verbauen

**Expected behavior:**
normale FPS

**Actual behavior:**
Statt 90fps 17fpsBei einer 4080

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
If the performance issues persist for you, feel free to open an issue whenever you can provide the requested data.
Without the requested data we are not able to investigate the issue.
