### ISSUE TITLE
USER ISSUE: Constant Disconnects

### ISSUE THREAD

**Issue by Pakka77** [StrangeLoopGames/EcoIssues#24360]
\
**User Id: (slg235845)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Login

**Expected behavior:**
To be able to do something	

**Actual behavior:**
Get the disconnect warning every 5 seconds unable to do anything

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No idea

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, so we can get more information.
