### ISSUE TITLE
USER ISSUE: Анимация персонажа пропала

### ISSUE THREAD

**Issue by RusFor** [StrangeLoopGames/EcoIssues#24365]
\
**User Id: (slg237042)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Леч спать. Выйти с сервера. Зайти обратно.

**Expected behavior:**
У персонажа есть анимация движений

**Actual behavior:**
Отсутствие анимации персонажа.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Не знаю

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
