### ISSUE TITLE
USER ISSUE: Fell through the earth

### ISSUE THREAD

**Issue by Ozzy2** [StrangeLoopGames/EcoIssues#24367]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
I was walking on the ground and fell through.
As I was trying to dig myself out, I got squished into the wall and fell deeper. 	

**Expected behavior:**
To walk from point A to point B without falling through the earth. 

**Actual behavior:**
I fell through the earth. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed. Yes. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use the command /unstuck when getting stuck. To deal with this issue we'd need more information and reproducible steps. Please let us know if you can provide such, we're unable to reproduce this issue.
