### ISSUE TITLE
USER ISSUE: Server Crash on /settlement spawn

### ISSUE THREAD

**Issue by E39LP** [StrangeLoopGames/EcoIssues#24366]
\
**User Id: (slg178290)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
I used command /settlement spawn (setting config of 0 and 1)

**Expected behavior:**
Spawn a Settlement

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server encountered an exception:

<size=60,00%>Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:Eco.Gameplay

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.Settlements.SettlementSpawnHelper.GetChildCount(Int32 settlementType)
   at Eco.Gameplay.Se</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a QA command not intended to be used by players. The actual bug is being able to use it, but that was already reported :)
