### ISSUE TITLE
Multiple scrolls sold to store not working correctly.

### ISSUE THREAD

**Issue by goertzenator** [StrangeLoopGames/EcoIssues#2436]
1. I had a store up and running with offers to buy a variety of scrolls which I did not have.
2. I watched an individual walk up and sell a single Masonry and Engineering scroll.
3. I saw the message on screen saying something to the effect "Swiftbiscuits sold Masonry scroll and Engineering scroll to goertzenator's Store".
4. Upon inspecting my inventory, I found 2 Masonry scrolls and no Engineering scrolls.  I expected to find one of each.

The same thing happened again moments later with two other types of scroll.

Notes:
- Version 0.6.0.0
- Server "New Eden" (appears to be down at the moment).
- This happened on 1 Oct 2017.

**Comment by MarjieAVolk** [comment]
I couldn't repro this, and then I realized I think this is already fixed in the latest staging build.
