### ISSUE TITLE
flying canoe

### ISSUE THREAD

**Issue by Numb3r13** [StrangeLoopGames/EcoIssues#24369]
I have found a repeatable bug where if you sail with a canoe in a dock with dock ramp it start to fly until it hit the roof I made.
[Eco flying canoe.webm](https://github.com/StrangeLoopGames/EcoIssues/assets/97838989/3b97a962-a214-4908-bac7-fc025d672332)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24148
