### ISSUE TITLE
USER ISSUE: Elevator(and -post) buttons ignore auth

### ISSUE THREAD

**Issue by DiendaPhoenix** [StrangeLoopGames/EcoIssues#24370]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
- Put a title or demographic requirement on an elevator (or -post). - Click on Elevator button > still able to control Elevator
- Missing option in the laws to select the buttons themselves, when on event selecting Elevator Buttons are missing.
-Tried creating laws, seperate deeds, seperate districts...

**Expected behavior:**
When Authorization is put on an Elevator or Elevator post you shouldn't be able to control/move the Elevator

**Actual behavior:**
It Ignores Authorization on the buttons themselves

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods Installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
