### ISSUE TITLE
White screen after game loaded

### ISSUE THREAD

**Issue by kosstbarz** [StrangeLoopGames/EcoIssues#24374]
After last update 24.12.2023 get white screen after game loading. 
After Esc I can get to settings screen, but any graphic changes doesn't help.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13762602/Player.log)
<img width="1500" alt="Screenshot 2023-12-24 at 7 48 20 PM" src="https://github.com/StrangeLoopGames/EcoIssues/assets/16974471/d6555017-0dcf-46a8-a8fb-5ec55c8f287e">

**Comment by D3nnis3n** [comment]
Mac is not supported by Eco, hence closing this issue.
