### ISSUE TITLE
USER ISSUE: FPS drop

### ISSUE THREAD

**Issue by leomide** [StrangeLoopGames/EcoIssues#24376]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Just by playing, after some time it occurs 

**Expected behavior:**
stable fps

**Actual behavior:**
the fps drop after some time. sometimes down to even 7, but a default of about 15 fps. if you hold still, it gets back up to like 60, but move again and they drop again. I have a high end gaming pc and this shouldn't happen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
