### ISSUE TITLE
USER ISSUE: Typo 

### ISSUE THREAD

**Issue by Revolos55** [StrangeLoopGames/EcoIssues#24373]
\
**User Id: (slg235283)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Hover mouse over Residency Property Value display in the lower left HUD, the word 'multiplier' is spelled incorrectly in the popup

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Added to internal typo collection, closing.
