### ISSUE TITLE
Deleted deeds can excessively build up

### ISSUE THREAD

**Issue by KironaDragryph** [StrangeLoopGames/EcoIssues#24371]
I realize this isn't technically a "bug" but it's certainly annoying - deleted deeds never really stop existing, and can build up horribly in some cases. As an example, people in my server often pick up carts/wheelbarrows/etc. with a hammer when they're empty, as it's easier to move them around that way. But every time one of these is placed back down, rather than reoccupying the same deed, it generates a *new* deed.

I personally have ownership of 20+ deleted cart deeds, all for the one cart I own.

I understand keeping a record of land/settlement deed history, but maybe vehicle deeds should be somehow modified to persist even when a vehicle isn't in an "in the world" state, and link to the inventory item version when they've been picked up?

**Comment by D3nnis3n** [comment]
This works as intended, I did note an internal suggestion though.
