### ISSUE TITLE
Deserialization errors 

### ISSUE THREAD

**Issue by ncottrill** [StrangeLoopGames/EcoIssues#24379]
We consistently have this deserialization error reported when shutting down the multiplayer 10.0.3 server. 

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/14022160/4f21ed16-0047-4853-8405-0596747b8997)

On startup, some dictionary shows deserialization errors, as well. These errors are no doubt related. However; neither the name of the dictionary nor the id are reported in the console or in the logs. It probably would be helpful to have those params outputted to the log. (For instance:  Dictionary "Tools" deserialization error ...) and (ID " 7 " already existed in universal id table)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/14022160/203640f1-e41c-4ab8-a358-27a789b4c556)

**Comment by D3nnis3n** [comment]
You can ignore that.
