### ISSUE TITLE
USER ISSUE: Unable to Shoot Arrows

### ISSUE THREAD

**Issue by redun45** [StrangeLoopGames/EcoIssues#24378]
\
**User Id: (slg237360)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
arrows in backpack or toolbar are not being seen as being in inventory, when you shoot an arrow, it says "no arrows in inventory"

**Expected behavior:**
arrows should be seen and should fire	

**Actual behavior:**
having arrows is not allowing you to use arrows	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
