### ISSUE TITLE
Cart lost after pickup (again)

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2437]
Full inventory -> Hammer cart -> no more cart

**Comment by MarjieAVolk** [comment]
OMG I swear this was fixed lol

**Comment by MarjieAVolk** [comment]
OMG I was adding the item into the cart inventory instead of the user inventory lol

**Comment by Timmay24** [comment]
Implosion!! :1st_place_medal: 
;)
