### ISSUE TITLE
Should not be able to delete default settlement title, demographic and election processes

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#24372]
it is possible to completely lock yourself out of any civic actions in a settlement, if you delete the mayor title and associated citizens demographic then there is no way to perform any civic actions. The only way forward would be to dissolve and create a new town. For that reason i consider this to be a bug.

It should be changed so that the default civic objects that are created can not be deleted/removed, but they can still be edited.

**Comment by D3nnis3n** [comment]
This works as intended, while it can cause issues that is very rare as deleting them is a purposeful action.
If deleting these was not possible, you couldn't use different than default titles while removing those.

I did make an internal note to ask for extra confirmation on deletion of used civic objects, though.
