### ISSUE TITLE
USER ISSUE: Main menu 

### ISSUE THREAD

**Issue by Zavislakk** [StrangeLoopGames/EcoIssues#24383]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**

**Expected behavior:**
It should work :D

**Actual behavior:**
Doesnt show main menu cant join server 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by tehfreak** [comment]
Same issue
