### ISSUE TITLE
USER ISSUE: Twitch interlocking is not working.

### ISSUE THREAD

**Issue by Rema-rque** [StrangeLoopGames/EcoIssues#24382]
\
**User Id: (slg237700)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
When you click interlock in the game, the web only outputs HTTP ERROR 500 this message.

**Expected behavior:**
No message appears when you refresh.

**Actual behavior:**
No message appears when you refresh.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no. Mode is not installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce, please reach out to support@strangeloopgames.com.
