### ISSUE TITLE
USER ISSUE: don't show main menu

### ISSUE THREAD

**Issue by JSinx** [StrangeLoopGames/EcoIssues#24388]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
start game

**Expected behavior:**
i should see main menu

**Actual behavior:**
I didn't look to main menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ncottrill** [comment]
The main menu on the client side does not show because the ECO authentication servers are malfunctioning. 

Strange Loop developers, please add a timeout message to the client side display whenever the client cannot connect to the ECO authentication servers after x ms.

Here is a very crude mock-up of a message that could help users understand the issue much better than a blank screen: 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/14022160/14f3d123-6ad5-453d-9450-37b79d685d35)

**Comment by Radmation** [comment]
I was able to log in. Here is how.
1.) Browse local files and launch the Eco.exe. (Here you should see a sign in form at the bottom of the scree, we will come back to this)
2.) In a web browser, log into the strange loop website [https://play.eco/account](https://play.eco/account) and create an account if you don't already have one.
3.) Link your steam account so it says you own the game.
4.) Go back to the eco game instance and log into your account.

**Comment by ncottrill** [comment]
> I was able to log in. Here is how. 1.) Browse local files and launch the Eco.exe. (Here you should see a sign in form at the bottom of the scree, we will come back to this) 2.) In a web browser, log into the strange loop website https://play.eco/account and create an account if you don't already have one. 3.) Link your steam account so it says you own the game. 4.) Go back to the eco game instance and log into your account.

This ^^ is a work around for a GUI fail, right? 

My point is that many player-users are confused upon seeing a blank screen when they start the game. Some complain loudly on Discord. Some leave to play another game. If I were a game publisher, I would not want either of these things to happen.

When the authentication servers are down, it is simply logical to have message that pops up to alert the user. Sure, I can do the work-around, but not all users have the same computer science education that I do or the knowledge about the game that you do. 

You know, you all could just write a fall-back script that would do the work-around you posted for the user, as well, whenever the auth server is down.

**Comment by D3nnis3n** [comment]
The user you are quoting is not a member of our development team. The workaround also is no workaround, as this would not have worked when the authentication servers were down either. The outage simply was already over when they did that.

We already have a internal issue to fix the bug that the main menu doesn't display the correct error but instead goes blank.
