### ISSUE TITLE
USER ISSUE: Game menu not showing

### ISSUE THREAD

**Issue by ScottEco** [StrangeLoopGames/EcoIssues#24390]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Opening the game.

**Expected behavior:**
I should have the menu where I can select the world, create one, go to options, etc.

**Actual behavior:**
I see the background animation with the barge circulating, the windmill moving and all, but no menu shows up. I can use the ESC key to access the set-up menu, but that is all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed locally no.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ScottEco** [comment]
It appears the game says I'm not connected. But I open it from Steam.

**Comment by ScottEco** [comment]
Auth server issue

**Comment by Radmation** [comment]
I was able to log in. Here is how.
1.) Browse local files and launch the Eco.exe. (Here you should see a sign in form at the bottom of the scree, we will come back to this)
2.) In a web browser, log into the strange loop website [https://play.eco/account](https://play.eco/account) and create an account if you don't already have one.
3.) Link your steam account so it says you own the game.
4.) Go back to the eco game instance and log into your account.
