### ISSUE TITLE
Tilled soil grows common grass which cannot be tilled

### ISSUE THREAD

**Issue by Valtornac** [StrangeLoopGames/EcoIssues#24394]
If a tilled soil block is left for a period of time, a plant has a chance to grow on it. Sometimes, this plant is the common grass species. When the tilled block with common grass growing on it is tilled again, nothing happens and the common grass remains on tilled dirt. The dirt block must be picked up with a shovel and replaced to remove the grass.

All other wild plants (from what I've seen) can be tilled to be removed, as the wild plant removes the tilled status from the dirt.

Version 10.0.3

**Comment by Maelstromeous** [comment]
I read this should have been fixed in 0.10.1.0, it has not been. https://i.imgur.com/Je4Gko5.jpeg

**Comment by D3nnis3n** [comment]
Fixed in Update 10.1.

@Maelstromeous Please provide a new issue if you're unable to remove grass on tilled dirt - I was able to.

**Comment by Maelstromeous** [comment]
@D3nnis3n  for clarification, was the fix the removal of grass from tilled dirt, or the prevention of grass growing on tilled dirt?

**Comment by D3nnis3n** [comment]
The inability to remove grass from tilled dirt was fixed.
