### ISSUE TITLE
USER ISSUE: Main Menu doesn't load

### ISSUE THREAD

**Issue by LouisPujol** [StrangeLoopGames/EcoIssues#24391]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Start game
2. Main menu animation loads in
3. Main menu options do not load in

**Expected behavior:**
Options appear to allow you to play the game

**Actual behavior:**
No options appear and I can only see the main menu animation or push Esc to change settings or quit game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, this occurred after both verifying files and reinstalling the game

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13772933/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13772934/Player-prev.log)

**Comment by Radmation** [comment]
I was able to log in. Here is how.
1.) Browse local files and launch the Eco.exe. (Here you should see a sign in form at the bottom of the scree, we will come back to this)
2.) In a web browser, log into the strange loop website [https://play.eco/account](https://play.eco/account) and create an account if you don't already have one.
3.) Link your steam account so it says you own the game.
4.) Go back to the eco game instance and log into your account.
