### ISSUE TITLE
Trees should not collide with other tree branches

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#244]
Makes them pop and explode when you cut them down because of other branches

**Comment by metachronism** [comment]
can't do selective collision between parts of a rigidbody, so this isn't really feasible without disabling collision between trees entirely which looks even more wierd

**Comment by johnkslg** [comment]
We need to fix it, they explode currently and it looks super buggy.  Please find a solution.
I imagine you could somehow create a separate collision group for them

**Comment by metachronism** [comment]
most of this bug is because of trees spawning right next to each other, which no longer occurs

**Comment by johnkslg** [comment]
Need to just make branches->trunks not collide, but both branches and trunks collide with the ground, and trunks will collide with other trunks

**Comment by johnkslg** [comment]
This answer seems to imply children rigidbodies can have different collision layers:
http://answers.unity3d.com/questions/566731/ignore-collisions-between-a-certain-collider-and-a.html
