### ISSUE TITLE
USER ISSUE: Stahlbarren

### ISSUE THREAD

**Issue by JimmyBeam1990** [StrangeLoopGames/EcoIssues#24406]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Stahlbarren in Kompaktlader geladen und eingestiegen, mein betätigen der rechten maustaste erscheinen weiße Blöcke die man nicht mehr entfernen kann

**Expected behavior:**
Stahlbarren auf den boden legen

**Actual behavior:**
Weiße Blöcke erscheinen auf dem boden

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24497
