### ISSUE TITLE
USER ISSUE: Camera inside head after sleeping

### ISSUE THREAD

**Issue by Hopewow** [StrangeLoopGames/EcoIssues#24405]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1/2. Have an ultra wide? No idea if this is also an issue with regular screens
1. Sleep
2. After sleeping wake up
3. Camera is now inside head

**Expected behavior:**
Camera should work like normal.

**Actual behavior:**
Camera stuck inside head having to look straight down for camera to be normal looking up makes you go third person kinda weird.	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Same issue on modded and non modded servers.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Hopewow** [comment]
Logs here:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13784611/Player.log)

**Comment by D3nnis3n** [comment]
Duplicate.
