### ISSUE TITLE
Unable to join or create a server.

### ISSUE THREAD

**Issue by TheDevilYouKnow123** [StrangeLoopGames/EcoIssues#24404]
When I try to join a server, ANY server, be it official or unofficial mods/no mods, it will get stuck and either stop dl'ing completely or trickle down to ~40b/s as you can see in the screenshot.
  I have already tried reinstalling, verifying, full logout of steam, cleared steams cache, uninstalled and destroyed eco from the registry, full opened up all firewalls/ports, turned off my AVG, graphics driver is updated, linked my steam to my SLG account on the website and tried the standalone version and last but not least I have used the on/off button multiple times. As my system has Imperial technology in it I have even tried hitting it but Han's quick fix didn't work either. 
![Untitled1](https://github.com/StrangeLoopGames/EcoIssues/assets/155040085/d2cab038-8f24-43a0-93cd-6047028ccdc1)
[Mr. Stoners Eco Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13783069/Mr.Stoners.Eco.Log.txt)
Also I just tried to create a local server and it said Invalid Login info. No response from auth server.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/155040085/09ce4cd8-93f4-4d2b-af2c-88d325616e90)

**Comment by TheDevilYouKnow123** [comment]
UPDATE: If I stay connected for around 25 - 30 minutes I eventually get in....... hope this gets fixed soon, didn't have a problem when I tried this game on my friend account earlier this year on this computer.

**Comment by TheDevilYouKnow123** [comment]
Here's a log of joining a server, lot's of errors when trying to connect for roughly 10-15 min, some to do with discord? which I don't even use while playing games.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13810149/Player.log)

**Comment by rojamet** [comment]
Same issue. It's mighty annoying to not be able to play a game I own in solo because an online service is down.

**Comment by D3nnis3n** [comment]
Our services have stabilized after the rush and DDoS attacks and haven't had any downtimes since. If this issue persists, please reach out to support@strangeloopgames.com, given then a local problem is the cause.
