### ISSUE TITLE
USER ISSUE: unity crashes

### ISSUE THREAD

**Issue by arrrmin** [StrangeLoopGames/EcoIssues#24402]
Hey, I am getting unity crashes mid game.
Sometimes playing for hours without a problem and then crashing a couple of times in minutes.
Playing on a vanilla server (only discord mod I think).

I verified the game files more than once, but that did not change anything.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13777438/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13777439/Player-prev.log)

**Comment by arrrmin** [comment]
I am using the multiple desktop feature in Win 11. ECO is running on one desktop and I am sometimes doing something else on another for some time.
And I noticed that when I switch back to ECO after a while, there is a good chance it crashes.

**Comment by WhosGamingNow** [comment]
This seems very this seems very similar to the crashes I am getting please post if you find any kind of fix or workaround or whatever and I will be following this thread!

> "Hey, I am getting unity crashes mid game. Sometimes playing for hours without a problem and then crashing a couple of times in minutes. Playing on a vanilla server"

**Comment by D3nnis3n** [comment]
Log hints at system instability, please reach out to support@strangeloopgames.com with as much details as you have, including full system specs and list of installed software. Note any changes to specifications, including if you use memory profiles.
