### ISSUE TITLE
USER ISSUE: Sawmill says not contained in room - is in room

### ISSUE THREAD

**Issue by Aether42** [StrangeLoopGames/EcoIssues#24401]
![sawmil bug4](https://github.com/StrangeLoopGames/EcoIssues/assets/11468445/384a13ed-d4b3-4c69-a6a7-29a5d8120171)
![sawmil bug3](https://github.com/StrangeLoopGames/EcoIssues/assets/11468445/2387081f-3a1b-44ff-9d43-b574302dde4b)
![sawmil bug2](https://github.com/StrangeLoopGames/EcoIssues/assets/11468445/6be9f46e-6100-4c2a-aee9-34d911995520)
![sawmil bug1](https://github.com/StrangeLoopGames/EcoIssues/assets/11468445/09cbaca9-5504-4e8a-845c-e77ebc4c0f56)
\
**User Id: (slg6011)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Don't know how it happened, or how to reproduce.This particular sawmill says it is not contained in a room, even when I pick it up and place it in diffrent places - includeing room that have other workstations that are working.Tried putting the sawmill in a stockpile I didn;t own, picked it up, and it still was going this.I exited game and then back in, still is doing it.

I have never encountered a bug like this before playing Eco. I can;t tell if this is server side or client side issue.

**Expected behavior:**
detect that it is contained in room.

**Actual behavior:**
Says it is not contained in room, even when it is. (as verified by other workstations in room that report correct staus.)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, vanilla server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Aether42** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13774477/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13774478/Player-prev.log)

**Comment by Aether42** [comment]
Tried diffent rooms, also had same issue.

**Comment by aritchie05** [comment]
This is probably this issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/24362

Rooms don't update their status, newly placed tables don't detect a room, transferring items between stockpiles doesn't update the game world. Server restart is required.

**Comment by Aether42** [comment]
That was it! Thanks you! Server restart resolved.
