### ISSUE TITLE
Game Crashes when loaded to 100%

### ISSUE THREAD

**Issue by Seriousike** [StrangeLoopGames/EcoIssues#24403]
Hello my game has been loading to 20% then shoots to 100 and crashes. There was a previous fix for this when renaming a DLL file for backup but after reinstalling a fresh windows and the game again, the file isn't there anymore.
[log_231227092520.log](https://github.com/StrangeLoopGames/EcoIssues/files/13782656/log_231227092520.log)

**Comment by D3nnis3n** [comment]
Caused by too old CPU, see here:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/c60fc21a-1044-4d99-b30e-36cc7a7a2b15)

**Comment by Seriousike** [comment]
Is there any work around currently? was fine until I did my fresh windows install now there’s a file not there when there was before. Or just upgrade the cpu?

On Dec 28, 2023, at 12:43 PM, Dennis Scholz ***@***.***> wrote:

﻿

Caused by too old CPU, see here:
image.png (view on web)<https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/c60fc21a-1044-4d99-b30e-36cc7a7a2b15>

**Comment by D3nnis3n** [comment]
There is a steam branch called old_hardware_test_1 that could resolve the issue for you. Note that this is not kept up-to-date.
