### ISSUE TITLE
USER ISSUE: Campfire upgrade doesn't affect campfire 0 recipes

### ISSUE THREAD

**Issue by TheEvilGreebo** [StrangeLoopGames/EcoIssues#24407]
\
**User Id: (slg233066)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Insert any Basic Upgrade into a campfire (I used the specialized upgrade for campfire cookign)
Cook a campfire 0 recipe like charred fish

**Expected behavior:**
Resource consumption should be reduced

**Actual behavior:**
Resource consumption is not reduced

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Only DiscordLink

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended.
