### ISSUE TITLE
USER ISSUE: Fill mode with hammer can only be cancelled when pointing at a valid location

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24418]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
- Use the "Line" fill type with the hammer
- Click somewhere to start building
- Aim at the sky
- Try to cancel the action, e.g. by left-clicking

**Expected behavior:**
- There should be a persistent hint that you are currently in fill mode and have selected the first location
- It should be possible to cancel the action no matter where you point
- There should be a persistent hint how to cancel the action (like there is when you point at a valid location)
- Left-clicking inventories should not interact with them - it should just cancel the fill mode

**Actual behavior:**
- There is no way of knowing that you have selected the first location if you do not point at a valid location (the UI looks exactly like if you did not select the position yet)
- It is not possible to cancel the action, except from switching tools
- Left-clicking an inventory takes items out of the inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

I was quite specific with the "expected behavior" above. There are probably other ways to improve UX here. My main issue is that it requires a lot of attention on the mechanics to build: If you misclicked the first block, you subconsiciously left-click to cancel it. Now there is a chance that it did not work, so you might click again - but if it had worked the first time, that second click will now remove a block.

**Comment by D3nnis3n** [comment]
Duplicate.
