### ISSUE TITLE
Steam Tractor Engine sound effects stop after turning

### ISSUE THREAD

**Issue by LamMods** [StrangeLoopGames/EcoIssues#24410]
10.0.3

On initial load of world, engine sound effects play for the Steam Tractor. As soon as you try to turn left our right, the sound effect which plays on turning seems to cut off the sound effect of the engine. To reset this, the game client must be quit to desktop and relaunched.

**Comment by D3nnis3n** [comment]
Cannot reproduce, needs reproduction steps.

**Comment by LamMods** [comment]
Launch Client 10.0.3
Start Local Game (no-collab)
Drive Tractor (with or without module, it makes no difference)
Observe engine noise
Drive forward
Observe engine noise
Turn left or right while driving forward
Observe engine noise has stopped and does not return until client restart.

**Comment by D3nnis3n** [comment]
I cannot reproduce the issue with those steps unfortunately.

**Comment by LamMods** [comment]
So turning doesn't seem to be the cause after all. It's like a tyre-scratch noise that's triggering the silence. I've captured a video:

https://github.com/StrangeLoopGames/EcoIssues/assets/13630899/4819f3e9-aef7-405d-aec3-8df9d31e39d6

**Comment by D3nnis3n** [comment]
Does this persist on Update 10.2 for you?

**Comment by LamMods** [comment]
No, I can't reproduce. I'll close.
