### ISSUE TITLE
USER ISSUE: Zoning office 

### ISSUE THREAD

**Issue by JohnSaylar** [StrangeLoopGames/EcoIssues#24412]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**

Paramétrage du serveur avec aucune colonie (colonie unique)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/155075061/e32312a1-7420-4b0b-b1ab-62aca3fc2e2f)

Crée une constitution et l'activée avec un vote forcé.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/155075061/e09450c8-7df3-465e-aa36-03b51c0524f7)

Installer un bureau du territoire (pour créer des quartiers)

**Expected behavior:**
Pouvoir utiliser le bureau du territoire (zoning office))

**Actual behavior:**
le bureau est inactif impossible de l'utiliser
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/155075061/33b21a22-a8fd-4878-b40c-944eb0b8a512)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate, issue is known for settlements off.
