### ISSUE TITLE
USER ISSUE: Map Icons Missing

### ISSUE THREAD

**Issue by chris-9999** [StrangeLoopGames/EcoIssues#24411]
\
**User Id: (slg127055)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Load into a world.

If relog the map can reset to be correct.

**Expected behavior:**
All map items should be able to be toggled

**Actual behavior:**
Map items do not show up to be toggles or actually show up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
With and without mods. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
