### ISSUE TITLE
USER ISSUE: Moving an object considers current location as blocked

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24417]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
- Ctrl-click with the hammer to move an object
- Choose a spot that is (partly) within the original position of the object
- Alternatively, try to rotate the building on the spot (e.g. a stockpile)

**Expected behavior:**
The original position should not be considered blocked - it should be possible to place the object there

**Actual behavior:**
It is not possible to move the object if the new location overlaps with the old location

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Rotating stockpiles on the spot would be especially useful if you want to change in which direction the contents are placed (if there are different materials in the stockpile, two sides shows the different materials while the other two sides mostly show one material)

![20231228181652_1](https://github.com/StrangeLoopGames/EcoIssues/assets/395810/1c6a896d-4f74-4621-8574-0b398e6ea17e)

**Comment by D3nnis3n** [comment]
This works as intended. I noted an internal suggestion for allowing this, though.
