### ISSUE TITLE
Client freeze - placing ramps, but aiming under water

### ISSUE THREAD

**Issue by LamMods** [StrangeLoopGames/EcoIssues#24427]
10.03
When placing ramps on the ground, using the floor fill type, the 2nd marker will give the range of the intended ramp when mousing over other blocks on the surface. If you go under water and look at blocks more than 1 block below the surface, the client will freeze and windows will report it as not responding. Waiting long enough and the game will resume. Takes about 2 minutes to recover. Feels like an exponential calculation is happening when trying to figure out how large to make the preview.

I've attached a video to make it clearer. I've sped up the frozen part by 4 times to bring file size down (and reduce boredom!), however, the original video shows a 2 minute recovery time.

https://github.com/StrangeLoopGames/EcoIssues/assets/13630899/a5aa3990-1af8-4a8a-bc2f-b03a46e4a1f1

**Comment by jwmc80** [comment]
Yes I've seen this happen as well with the fill tool on ramps.

**Comment by D3nnis3n** [comment]
Merge with https://github.com/StrangeLoopGames/EcoIssues/issues/24599
