### ISSUE TITLE
USER ISSUE: Districts broke in laws sometime after an update.

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24425]
\
**User Id: (slg232257)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Have many laws that have some districts in it. Make some change to the district and sometime, your law will not linked anymore. They will have the tag (removed/old, something like that). Than in your laws you will need to relink every district to fix it.

**Expected behavior:**
Update without any problem like it does something.

**Actual behavior:**
You get the error message beside laws because they don't link.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, playing on WT

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
