### ISSUE TITLE
Alpha 6.0.1 [51df7483] Order amount does not check for Keyboard inputs

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2442]
Went to Blast Furnace typed "999" clicked on "Order" only one item was added to queue.

**Comment by Fank** [comment]
![peek 2017-10-03 15-08](https://user-images.githubusercontent.com/1900106/31126677-c1b17f5c-a84c-11e7-97ea-6bdd280ec5b3.gif)
