### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by htrobles** [StrangeLoopGames/EcoIssues#24421]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Join a previously joined server.

**Expected behavior:**
I get connected and I can play

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I believe there are mods installed in the server. I don't have any

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
