### ISSUE TITLE
USER ISSUE: says there's no arrows in inventory when there really is.

### ISSUE THREAD

**Issue by GeekyProductions** [StrangeLoopGames/EcoIssues#24424]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Create the arrows and place in inventory.

**Expected behavior:**
it should have allowed me to hunt using the bow and arrows once i placed the arrows in my inventory

**Actual behavior:**
instead it keeps giving me a warning saying i don't have any arrows in my inventory

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I do not have mods installed

Log: 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13790400/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13790401/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate

**Comment by Yogu** [comment]
@D3nnis3n  can you link the issue this one duplicates? I also experience inventory issues and would like to check if it's the same one.

**Comment by D3nnis3n** [comment]
Depends on what the inventory issues are, arrow errors are known.

**Comment by Yogu** [comment]
Thanks for clarifying. My issue is not related to arrows, so I opened a new issue: #24429
