### ISSUE TITLE
USER ISSUE: Missing footstep sounds

### ISSUE THREAD

**Issue by hastenfist** [StrangeLoopGames/EcoIssues#24422]
\
**User Id: (slg204456)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Launch the game and join a server.
2. Walk around.

**Expected behavior:**
Footstep sounds should play.

**Actual behavior:**
No footstep sounds are heard. Other animals make footstep sounds, but my player doesn't. Additionally, after long play durations, other sounds have stopped before, like digging clay sound a few days ago, but that sound returned once I restarted the game.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24433
