### ISSUE TITLE
USER ISSUE: Fehlermeldung bei Server beitritt 

### ISSUE THREAD

**Issue by GNCLORD-MDB** [StrangeLoopGames/EcoIssues#24423]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. auf Server verbinden.

**Expected behavior:**
Verbinden ohne probleme.

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method57357(Closure, Object)
   at Eco.Core.Contr...

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GNCLORD-MDB** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13789520/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13789521/Player.log)

**Comment by D3nnis3n** [comment]
Das ist ein serverseitiger Fehler, ist das Singleplayer?

**Comment by GNCLORD-MDB** [comment]
Die Fehlermeldung ist inzwischen weg ,  nachdem der Server wohl neugestartet wurde

**Comment by D3nnis3n** [comment]
Danke für die Rückmeldung, teile dem Admin gerne mit, dass er sich mit den Logs hier melden kann. Ohne den Admin können wir hier leider nichts tun.
