### ISSUE TITLE
USER ISSUE: Main menu not appearing

### ISSUE THREAD

**Issue by marex-git** [StrangeLoopGames/EcoIssues#24435]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Start the game
2. Can't see the menu and the cursor is flashing for a time.

**Expected behavior:**
I can play the game....

**Actual behavior:**
I cannot play the game because the start menu doesn't appear.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13798477/Player.log)

**Comment by Kro55f1r3** [comment]
Nice we are together :)

**Comment by marex-git** [comment]
I thought it might be because of an error response on my last server and so the didn't handle well the exception when trying to display the menu. Sadly this was a fluke and was just pure luck. I checked carefully the logs and it seems to be related to their auth service being down.

```
[10:47:42.673] Received login result from our primary platform. (Succes: False | Message: HTTP/1.1 503 Service Unavailable)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
Eco.Client.Platforms.Steam.<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, String)
Eco.Client.Platforms.Internal.Utils.<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by IneaFaedyn** [comment]
Well, throwing my two sense it, but it would be awesome if the game didn't become unusable when an external service is down. I don't particularly care if the game is checking to see what cosmetics I own before I'm allowed to join my server with friends where we don't use any of that.

**Comment by marex-git** [comment]
> Well, throwing my two cents in, but it would be awesome if the game didn't become unusable when an external service is down, it seems like this is going to be an ongoing issue, it was the same at launch of 10.

Yes I agree, it would be nice to have a fallback akin to steam offline mode.

**Comment by Yogu** [comment]
There was some information related to this in the discord recently:

> PSA: Our auth server is currently suffering a few issues and we are investigating it.
> Will update when we have more information.
