### ISSUE TITLE
Server Crashing trying to load world objects - 

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2443]
This server had other crash issues as posted by vigmundr,  He has been editing skill rate  on that instance and after having him not change the rate the server was up and running most of the weekend.  Just crashed in the past hour and now will not restart saying it cannot load World Objects

https://www.dropbox.com/s/jji4br3p2ustzo7/Crash%2010024923.ecodmp?dl=0
https://www.dropbox.com/s/1q873vhbav9yzq0/Santis10_2_Dump.7z?dl=0
https://www.dropbox.com/s/ouh9geu7axqg6em/Santos10_2.eco?dl=0

**Comment by MarjieAVolk** [comment]
Did you just upgrade your server version?  It looks like you have a bunch of "Objects" in your "WorldObjects" folder, along with the real WorldObjects.  Not sure if that's a bug or not.

**Comment by MarjieAVolk** [comment]
So you can continue playing - here is your save file with the extraneous objects removed: https://drive.google.com/file/d/0B4kJEcFjfDpjN0JBbkxPNTU0dkk/view?usp=sharing

**Comment by pamduncan** [comment]
That was a fresh install of 6.0 and a freshly created world for 6.0, not a migration from 5.6.1.  I saw those extraneous objects and wondered if removing them would fix it.  Thank you!

**Comment by pamduncan** [comment]
HI there.  Installed the fixed Game.eco and the server continues to crash:  https://www.dropbox.com/s/g6wake9v0zdpfvp/Santos_AfterFixDump.7z?dl=0

**Comment by metachronism** [comment]
so i dont know how this happened, but some rubble objects got saved into the world object folder - its possible you closed the server or it crashed mid way through the initial migration, or something?

Anyway to fix this you can move or delete the rubble objects in the game save, that is all the files with just random guid names to them in the WorldObjects folder (not the ones prefixed with a name, the ones without a prefix like ag39s7d79efewfsffsgeer)

**Comment by MarjieAVolk** [comment]
Yeah that's what I did in the 'fixed' version I gave up there.... but maybe when I opened the save on master it updated some other stuff, didn't think about that.
