### ISSUE TITLE
USER ISSUE: Some audio SFX not heard

### ISSUE THREAD

**Issue by nzkfc** [StrangeLoopGames/EcoIssues#24433]
\
**User Id: (slg93937)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Installed ECO
2. Went through settings to suit my setup
3. I adjusted SFX up too 100% from default and turned off music, then when I went to run around I noticed the only SFX I hear are:
- Sometimes wind in tree leaves
- Animals hitting "shrubs" sound
- UI sounds
- Hitting trees/stones etc with tools

**Expected behavior:**
General world ambiance like breeze, distant animals/insects, my players footsteps?

**Actual behavior:**
Not 100% sure if these SFX are in ECO or not, but it feels odd not hearing them and i'm pretty sure I heard footsteps a year or so back.

Here is a recording of my in-game, you can hear random sounds, but the audio silence between them is deafening and feels very odd, is this normal?

https://www.youtube.com/watch?v=tptS6CBvRpw

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

My PC specs:
Intel 13th Gen i7-13700F (running factory spec)
32GB DDR5
1TB Samsung 990 Pro SSD
nVidia 4080 running latest drivers
Monitor running 3840×2160 @ 120Hz on 42" LG C2
Windows 11 Pro (10.0.22621 Build 22621)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13798052/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13798053/Player-prev.log)

**Comment by hastenfist** [comment]
I'm having the same issue (#24422), the game is so very silent. I hear myself pass through bushes, and I can hear other animal footsteps, but I have no footsteps and other sounds stop working sometimes like shoveling clay, operating a boat, etc. The lack of sound makes the game feel like I'm playing as a ghost.

**Comment by nzkfc** [comment]
Yeah someone in our server said they had similar issues since the 10.0 patch or something, but said he played music and muted most sounds while playing so wasn't 100% sure.

Looking back at older gameplay videos, you can hear the normal ambience such as breeze, chirping crickets as well as the player footsteps: https://youtu.be/AtOLw01UJCs?t=304

**Comment by D3nnis3n** [comment]
Should be fixed with Update 10.2, please make a new issue with any remaining issues if there are any.
