### ISSUE TITLE
USER ISSUE: Gesicht von Innen zu sehen

### ISSUE THREAD

**Issue by xRivado** [StrangeLoopGames/EcoIssues#24432]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Eingeloggt
2. Aus dem Bett mit "E" aufgestanden
3. Normal durch den Raum bewegt
4. Bemerkt dass das gesicht verzieht und einige zentimeter zu weit nach vorne absteht

**Expected behavior:**
Umgebung normal wahrnehmen

**Actual behavior:**
Gesicht ist wie eine bizarre Maske von innen zu sehen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
