### ISSUE TITLE
USER ISSUE: Basic Engineering

### ISSUE THREAD

**Issue by Hawkertech** [StrangeLoopGames/EcoIssues#24430]
\
**User Id: (slg47055)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Basic engineerinng requires advanced geology which mortared stone which requires sand, Cant get sand without a rocker box which requires basic engineering, unless I am missing something.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by CosmoD41** [comment]
You can get sand on any shore or within desert biomes by just collecting it with a shovel?

**Comment by IneaFaedyn** [comment]
Mortared stone needs mortar, you can make that from sand, but you can also make some at a campfire with plant fibers and wood pulp

**Comment by Hawkertech** [comment]
Found the campfire bit about later, I don't know how I missed it in the
campfire menu. I kept looking. I knew we could do it in the past.

**Comment by D3nnis3n** [comment]
Not a bug, as you already found out :)
