### ISSUE TITLE
Enter key on password screen locks up game

### ISSUE THREAD

**Issue by fohdron** [StrangeLoopGames/EcoIssues#24431]
Version: 10.0.3
Reproducible: Yes

When trying to join a server using the "+" icon, typing in the URL then type in the password. If you hit the enter key on your keyboard it will lock up the game. Clicking submit however, will work.

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24160
