### ISSUE TITLE
USER ISSUE: game chat

### ISSUE THREAD

**Issue by mugger103** [StrangeLoopGames/EcoIssues#24479]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
i press my push to talk button to talk the mic icon popos up when i talk but noone can hear me

**Expected behavior:**
i can talk in game chat

**Actual behavior:**
i cant talk in gmae chat

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13800590/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please check with your server admin or reach out to support@strangeloopgames.com. Vivox is a third party implementation and does work fine here, so I can't assume a bug here.
