### ISSUE TITLE
USER ISSUE: Collecting items

### ISSUE THREAD

**Issue by DrNanfran85** [StrangeLoopGames/EcoIssues#24478]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. During hunting animals will go down but be unable to get picked up until on a certain level in the game. I'll have to literally push the body down 3 - 4 levels just to be able to pick it up.

**Expected behavior:**
Dead animal = able to pick up at any angle on any level

**Actual behavior:**
Have to push body all the way down a couple of levels in order to be able to pick it up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes. Also, yes. Have tried it on a blank server of my own and it's exactly the same thing.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by DrNanfran85** [comment]
The same thing happens when picking up rocks as well.

**Comment by D3nnis3n** [comment]
Duplicate interaction issue.
