### ISSUE TITLE
Game crashing when joining any world

### ISSUE THREAD

**Issue by Dozaskillz** [StrangeLoopGames/EcoIssues#24472]
![PXL_20231231_034937563](https://github.com/StrangeLoopGames/EcoIssues/assets/155280592/f14ca500-bbc4-42bc-928c-dc9dd1c0bc7c)

Game crashes every time I try to join a world. Doesn't matter which one. That unity thing pops up for a few seconds then Eco closes.

**Comment by D3nnis3n** [comment]
Caused by too old CPU likely:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/79bb7f48-4805-448b-bcea-7e78d5b4abc8)

If you feel that is not the case, please reach out to support@strangeloopgames.com.
