### ISSUE TITLE
USER ISSUE: Clicking into the game after tabbing out performs the left-click action

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24471]
\
**User Id: slg238555**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Equip a hammer
2. Press Tab to show the cursor
3. Click into a different window (with a multi-monitor setup)
4. Click into the game window again

Alternative to step 2 and 3: Alt-Tab into a different window (with a multi-monitor setup)

**Expected behavior:**
The game should focus, but nothing should happen in the game

**Actual behavior:**
The game focuses, and then the left-click action is performed (the hammer swings)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file (probably not needed)

I think this is a bug because if you skip step 3 (i.e. if you press tab, then click into the game), the left-click action is not performed. I think it's relevant because you need to do extra steps (e.g. equipping nothing) before tabbing out to make sure you don't do anything unintended.

You can also make sure that you always press Esc before alt-tabbing out, but then you need to press Esc again once you're in the game, and you don't see your screen anymore (relevant if you want to check something related to on-screen content)

**Comment by D3nnis3n** [comment]
Won't fix.

**Comment by Yogu** [comment]
Ah simple workaround is just to middle-click into the game. Also lets you appreciate the avatar every once in a while 😅 

![20240101135226_1](https://github.com/StrangeLoopGames/EcoIssues/assets/395810/44370a9e-d461-4933-a029-c2120977d6b2)
