### ISSUE TITLE
USER ISSUE: Sample Soil on Tree

### ISSUE THREAD

**Issue by Pyroblastouille** [StrangeLoopGames/EcoIssues#24485]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Used Sample Soil on a fallen tree

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Mods.TechTree.SoilSamplerItem.SampleSoil(Player player, InteractionTriggerInfo triggerInfo, InteractionTa</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
