### ISSUE TITLE
Graphical leftovers at stockpile

### ISSUE THREAD

**Issue by Timmay24** [StrangeLoopGames/EcoIssues#2448]
![unbenannt](https://user-images.githubusercontent.com/5476826/31128595-92e9d3e4-a852-11e7-9d52-4fc5b26e8881.png)
![2017-10-03 2](https://user-images.githubusercontent.com/5476826/31128643-b0fd0b4e-a852-11e7-8c44-18dbcf072be2.png)

They don't block. At least :]

**Comment by Timmay24** [comment]
Randomly.
This remained from an immediate consumption of dirt from a farmers table's job

**Comment by metachronism** [comment]
fixed already for 6.0.1 coming soon
