### ISSUE TITLE
USER ISSUE: Cannot pick up food items

### ISSUE THREAD

**Issue by BrandyCrumbz** [StrangeLoopGames/EcoIssues#24489]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Join game
2. Try to pick up item (food items)
3. Option for clicking 'E' becomes available but no food is picked up upon pressing button
4. Game must be reloaded to fix bug

**Expected behavior:**
Item should be picked up with 'E' is pressed

**Actual behavior:**
No item is picked up, the food item remains on the ground with no method of retrieval 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13803751/Player-prev.log)

**Comment by D3nnis3n** [comment]
Do you mean animal corpses?

**Comment by BrandyCrumbz** [comment]
Animal corpses but also vegetables. Not often farmed ones (I am not very
good at farming) but when wild harvesting it would go to grab to plant and
then it would just stay on the ground or plant.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24726
