### ISSUE TITLE
USER ISSUE: Says 'no arrows' when I AM carrying arrows

### ISSUE THREAD

**Issue by Kobogen** [StrangeLoopGames/EcoIssues#24483]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
I cannot use my recurve or beginning bow at all. I am the hunter. So I can't do anything.

**Expected behavior:**
Allowed me to hunt

**Actual behavior:**
Does not allow me to hunt

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes mods, no I cannot re-create

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate
