### ISSUE TITLE
USER ISSUE: Keep loosing authorisation on the city hall deed

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24482]
\
**User Id: (slg232257)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Hard to know, I have access to the city hall deed of our town and I keep loosing it the authorisation on the deed without anyone taking out from me. It has been the third time it happened on the White Tiger cycle.

**Expected behavior:**
I should be able to keep it.

**Actual behavior:**
After x days, it's really randomly, I loose the auth.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Needs more information. Is that a company, given its on WT?

**Comment by Lord-Schwartzy** [comment]
Sorry for the late response. No, not a company. If that can help in any way, it's the town : Evergreen Garden. We had that problem many times through the cycle and it's still happening.

**Comment by D3nnis3n** [comment]
Not reproducible so far, hence closing.
Notify us on next WT cycle if it happens again.
