### ISSUE TITLE
Purple line above mooring rope

### ISSUE THREAD

**Issue by fohdron** [StrangeLoopGames/EcoIssues#24488]
![Purple](https://github.com/StrangeLoopGames/EcoIssues/assets/73034504/00ee0ba7-9b07-4f1b-b46b-b898c1ee6f9e)

Get a rending issue above mooring ropes that shows it as purple. 

Game restart did not fix.

V10.0.3

**Comment by fohdron** [comment]
Probably should add: 

Nvidia RTX3090 Driver 546.33

**Comment by D3nnis3n** [comment]
Duplicate
