### ISSUE TITLE
USER ISSUE: Phantom Cart and Log

### ISSUE THREAD

**Issue by TheDarkMaw1** [StrangeLoopGames/EcoIssues#24487]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Chopped down a Ceiba tree
2. make 2 slices from the tree
3. it breaks

**Expected behavior:**
It should have fallen over and allowed me to slice into pieces which I would then store in my cart

**Actual behavior:**
The tree fell over, and I was no longer able to highlight or interact with it. Walking through it just pushes the object around. I go to deposit my carried wood and realise I can't interact with my cart either. I am also able to push the cart around by walking into it. The minimap shows the cart has not moved, but updates to the correct location when I place a marker on it. After pushing the log around, it glitched into the ground and allowed me to chop it again once. It immediately became incorporeal again. The entire log fell through the ground after pushing it around some more.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheDarkMaw1** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13802566/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13802567/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate interaction issue.
