### ISSUE TITLE
USER ISSUE: CaNOPE

### ISSUE THREAD

**Issue by DrNanfran85** [StrangeLoopGames/EcoIssues#24480]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Place canoe on water and try to get in.

**Expected behavior:**
"Press E for Paddle" = Get in canoe	

**Actual behavior:**
Pushing it around the map like it's a dead bison I shot and couldn't pick up either...	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yep. Also Yep...

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate interaction issue.
