### ISSUE TITLE
USER ISSUE: Début d'une partie

### ISSUE THREAD

**Issue by LigaultMaths** [StrangeLoopGames/EcoIssues#24481]
\
**User Id: (slg227318)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Créer un serveur privé et le lancer

**Expected behavior:**
Il aurait du me permettre de pouvoir placer mon point de départ.

**Actual behavior:**
La carte ne s'enlève pas, je ne peux pas choisir de localisation pour entrer dans le jeu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Aucun mod n'est installé

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you please attach the logfiles as noted in the issue?

**Comment by Thibault-Brocheton** [comment]
@D3nnis3n  I saw this problem. When the server is configured in French, by default, the spawn points does not appear.
Players must disable/enable them in the maps layers

**Comment by D3nnis3n** [comment]
Closing due to no further information provided, we're unable to reproduce and need logfiles from players affected.
