### ISSUE TITLE
USER ISSUE: IDK waht is causing it would like to report it to the right person

### ISSUE THREAD

**Issue by ZEROX7** [StrangeLoopGames/EcoIssues#24486]
\
**User Id: (slg3997)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Operation is not valid due to the current state of the object.
Source:System.Collections.Immutable

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Collections.Immutable.ImmutableList`1.En</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

https://gist.github.com/ZEROX7/6a3c8668e0e09d585e45d695dca8292c

**Comment by D3nnis3n** [comment]
We'd need the full log from the server admin, the client log isn't complete for server-side exceptions.

**Comment by D3nnis3n** [comment]
Fixed in playtest.
