### ISSUE TITLE
USER ISSUE: Admin Title Creation

### ISSUE THREAD

**Issue by Uniphix** [StrangeLoopGames/EcoIssues#24484]
\
**User Id: (slg59138)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Try adding a new Title by using /edit command

**Expected behavior:**
Allowed you to add a new title

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: MissingMethodException
Message:Cannot dynamically create an instance of type 'Eco.Gameplay.Civics.Titles.Title'. Reason: Cannot create an abstract class.
Source:System.Private.CoreLib

System.MissingMethodException: Cannot dynamically create an instance of type 'Eco.Gameplay.Civics.Ti</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes this is using the core system, no mods are overriding the civics what-so-ever.  As you can see in the exception

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Adding a title via /edit is not possible.
