### ISSUE TITLE
USER ISSUE: In some building spots, the block to be placed flickers between two locations

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24493]
\
**User Id: (slg238555)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Equip the hammer and a material
2. Aim at a place where there are multiple possible locations to place a block (e.g. in a corner)

**Expected behavior:**
If you don't move the mouse cursor, the block to be placed should not change 

**Actual behavior:**
In some spots, the block to be placed flickers / flashes between two locations rapidly, without moving the mouse cursor. You can still place the block.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

In some situations, this happens more frequently than in others. In the attached video, I needed to look for a location where it happened. In other situations, there were way more pixels that triggered the behavior than there where were id didn't flash, so it was quite hard to place a block.

https://github.com/StrangeLoopGames/EcoIssues/assets/395810/6a19d16d-195e-4035-9526-5e0f711eca6f

I think the recording affected the performance a bit. Without recording, it's very regular and fast-flickering.

Not sure if it could potentially be relevant, but my screen is scaled to 150%.

**Comment by Yogu** [comment]
Here on the roof, it happens all the time

Uploading flickering2.mp4…

**Comment by D3nnis3n** [comment]
Fixed in 10.3 via https://github.com/StrangeLoopGames/Eco/pull/13932.
