### ISSUE TITLE
world layers creating holes 

### ISSUE THREAD

**Issue by ThatBlackKid1** [StrangeLoopGames/EcoIssues#24498]
Has anyone ever had a bug or a setting when it says, World tick layers...
took... tick seconds or minutes..

Then it removes blocks globally around the map everytime it does that.. is it a bug or a setting?
All I have changed is wiped the map and it started doing it....

**Comment by D3nnis3n** [comment]
Where does it say that? What does get removed?

That line typically happens at server boot before anyone can join.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
