### ISSUE TITLE
Alpha.6 Server crash

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2449]
ftp://eco.fankserver.com/Crash_10031649.ecodmp

Last entry in log:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.TableTracker.Finalize()
```

I don't know what happend

**Comment by Fank** [comment]
Happend again

Savegame: ftp://eco.fankserver.com/Game-2449.eco
Crashfile: ftp://eco.fankserver.com/Crash_10033532.ecodmp

**Comment by MarjieAVolk** [comment]
Ah yeah, we saw this too.  It will be fixed in https://github.com/StrangeLoopGames/Eco/pull/1859

**Comment by MarjieAVolk** [comment]
For avoiding it now, it is caused by picking up world objects
