### ISSUE TITLE
USER ISSUE: Skid accepts log in inventory and spawn white square block

### ISSUE THREAD

**Issue by mchamplain** [StrangeLoopGames/EcoIssues#24497]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
put log in the skid inventory
use the skid to unload the logs

**Expected behavior:**
should not accept log, or spawn the correct model/object

**Actual behavior:**
spawn a white square block

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, also tried on a game without mods and it does the same thing.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by mchamplain** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/759989/72737ed6-c89b-41c6-8ce7-e081d2064d38)

**Comment by mchamplain** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/759989/2ed6a830-caf9-4211-a648-865582abdfaf)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
