### ISSUE TITLE
[0.10.0.3] WorldGenerator needs to be updated when the game updates

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#24504]
I wanted to check out some world generation updates that I heard happened in 0.10. However when I generated a new world everything seemed unchanged. Only after chatting with StalEF did I learn that the WorldGenerator file needs to be updated separately from the game being updated.

This is not an ideal behaviour. Most people playing ECO would not know about it let alone know which file to fix. I consider myself to be a very dedicated player and this is the first time I'm hearing about it.

Perhaps if the generation file is so important we could get backups with the old version number so players can fix it if something goes wrong, but by default the file should update along with the new game version.

**Comment by Yogu** [comment]
oh really? Can you explain what you did to update the file or how you can check if the file is up to date? Does this apply to the dedicated server, to singleplayer, or both?

**Comment by ThePiachu** [comment]
> oh really? Can you explain what you did to update the file or how you can check if the file is up to date? Does this apply to the dedicated server, to singleplayer, or both?

You find the WorldGenerator.eco file and replace it with the file right next to it, WorldGenerator.eco.template which has the updated code. It's somewhere in the main ECO directory. It applies to whenever you're generating a random world, so both single and multiplayer.

**Comment by D3nnis3n** [comment]
This works as intended and cannot be improved without overwriting user configuration - which we specifically do not want to do. Server owners need to make sure their configs are adjusted from the template files.

**Comment by Yogu** [comment]
Maybe it would be possible to show a hint when generating a new world? I installed the game in version 9, later updated top version 10 and wanted to generate a new singleplayer world from within the game. I never touched the WorldGenerator.eco. Does that mean I started my new world with an outdated world generation, just because I happened to install the game in an earlier version? How would I have known that I need to make sure my config was adjusted from template files?

**Comment by Yogu** [comment]
A possible solution would be a third file:

- a *template* file - gets updated by game automatically
- a *generated* file - gets created by the game itself when you use game UIs to configure some things, like the world generation UI
- a *custom* file - only ever created by users manually. Will never be changed by the game

Then, you would only need to update your files if you actually created a (custom) file manually to begin with.

**Comment by D3nnis3n** [comment]
No, if you use the ingame feature to create a randomized world it will rewrite the WorldGenerator file.

**Comment by ThePiachu** [comment]
Maybe it would be good if we had separate configuration for custom world generation vs vanilla. If the user doesn't specify a custom world generation but uses the version default maybe that ought to update.

Or maybe when you generate a world with a WorldGenerator file that is not identical to the newest one you should get a popup telling you so and letting you keep the custom generation vs new generation.

At least some kind of indicator that something is up would be nice.

**Comment by D3nnis3n** [comment]
If the user doesn't use custom world generation, he will always get the same standard world everyone else gets that is made by us automatically with every new build, it will not even use world generation then at all.

**Comment by ThePiachu** [comment]
I meant that if people do randomize their world in the game but don't mess with WorldGenerator file. I tend to do that.
