### ISSUE TITLE
USER ISSUE: Tax does not apply to all accounts managed by target

### ISSUE THREAD

**Issue by Psojed** [StrangeLoopGames/EcoIssues#24501]
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1) Have the target player create new bank account (let's call it "account 2"). Make sure the target player is set as Manager of this account.
2) Fill "account 2" with an amount of selected currency.
3) Make sure the target's personal account (the default one) has 0 of selected currency.
4) Create a Law that taxes the target player with an amount of selected currency.
5) Wait for the Law to trigger.

**Expected behavior:**
"Account 2" is taxed, the specified amount of currency is taken.

**Actual behavior:**
No money is taken, system message states that "none was available" even when there is money available. See screenshots:

![tax_law_hudral](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/ab9500af-d21e-4369-86d3-3e5b25c8ed95)
![hudral_tax_message](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/488ee283-0b0a-404c-8939-2321bdee811a)
![hudral_bank_account](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/32daf406-1042-4f0e-a87a-2d5b6520850b)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None

**Comment by Psojed** [comment]
Seems to be the same issue as #11037

**Comment by johnkslg** [comment]
This is intended, because determining which account tax should come from automatically is too problematic, accounts might be government owned/shared and shouldnt be automatically targeted.  Perhaps later we create a way to specify which account to pay tax from, but for now I'd make the law block the action when they cant pay, so they have to put some money in their account.

**Comment by Psojed** [comment]
If this is intended, please correct the description on the Tax action. There, it specifically states that Tax takes money from all accounts the target manages except government accounts.

![2024-01-02_085501](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/185801cf-1f0c-474a-a62e-bf7309f0cdb1)
