### ISSUE TITLE
USER ISSUE: Game freezes on SteamDeck

### ISSUE THREAD

**Issue by Kreastr** [StrangeLoopGames/EcoIssues#24502]
\
**User Id: (slg187872)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Install game.
Select proton 8.0.4
Start local server
Run around for 3 minutes
or attempt to join White Tiger

**Expected behavior:**
game shluld respond to controls

**Actual behavior:**
freezes the system. requires powercycling

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Steam Deck is not supported by Eco.
