### ISSUE TITLE
USER ISSUE: "Skills" dialog tells you to craft advanced books at Research Table instead of Laboratory

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24508]
\
**User Id: (slg238555)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
- Open the Skills dialog
- View a skill like *Electronics* that you did not learn yet

**Expected behavior:**
- The dialog tells you to craft the skill book at the laboratory

**Actual behavior:**
- The dialog tells you to craft the skill book at the research table

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

<img width="1279" alt="image" src="https://github.com/StrangeLoopGames/EcoIssues/assets/395810/3d657777-3a2e-4d23-ada4-4f6e16399464">

**Comment by D3nnis3n** [comment]
Duplicate.
