### ISSUE TITLE
Alpha.6 Induction Generator issues

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2451]
- Only the generator part hat a hitbox https://loli.temel.me/LKoQzS2ERGtQ0U4IvWnSYyrkSooGAxMg.mp4
- Wrong tooltip, we expected to use stuff like biodiesel and all log stuff too.
![image](https://user-images.githubusercontent.com/1900106/31136908-cca58008-a869-11e7-9f28-3eadebdb9c85.png)
- Currently Electric Generator and induction will do both same, same input same output.

**Comment by MarjieAVolk** [comment]
Okay so I see that the hitbox is wrong.  But what is wrong with the tooltip?

**Comment by MarjieAVolk** [comment]
So this is kind of 3 different issues, but I am too lazy to split it up lol:

-@craig-jong do you know what the difference between the Electric and Induction Generators is supposed to be?
-@Keegan can you fix the hitbox?
- I'll see what's up with the tooltip

**Comment by MarjieAVolk** [comment]
Oh I see, you think the flavor text is wrong.  Man I don't know enough about generators to even know lol.  So I guess that's in Craig's court too actually
