### ISSUE TITLE
USER ISSUE: Auth server down

### ISSUE THREAD

**Issue by rojamet** [StrangeLoopGames/EcoIssues#24512]
\
**User Id: (slg239588)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Try to log in, either to a local server, or a server hosted on LAN

**Expected behavior:**
I should get into the game

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by rojamet** [comment]
Update: 
Loading normally: not working
Loading with Firewall disabled entirely (it should already normally enable ECO but anyway): not working
Using a VPN to connect in the same country I already am in (France): suddendly it works

**Comment by D3nnis3n** [comment]
We haven't had any auth server issues yesterday. This means there is a local network issue on your side preventing connection to the server. Typical causes are security software, firewalls and VPN's.
