### ISSUE TITLE
USER ISSUE: Problème après manger

### ISSUE THREAD

**Issue by Shasarel14** [StrangeLoopGames/EcoIssues#24513]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. manger quelque chose
2. vouloir utiliser un outil (ex: une hache)

**Expected behavior:**
avoir la hache en main et pouvoir couper un arbre

**Actual behavior:**
la gamelle reste dans la main et impossible utiliser outil (mais possibilité de planter quelque chose)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non et oui

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
