### ISSUE TITLE
USER ISSUE: Minerals become intangible

### ISSUE THREAD

**Issue by Marethyu61** [StrangeLoopGames/EcoIssues#24518]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Collect ore 

**Expected behavior:**
By right-clicking, the resource is transported by the player.

**Actual behavior:**
Minerals can no longer be selected for collection. They can be moved by stepping on them (they are very light), and they can sink into the scenery.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13820624/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13820635/Player-prev.log)

I've tried disconnecting and reconnecting, but the bug persists.

**Comment by D3nnis3n** [comment]
Duplicate interaction issue.
