### ISSUE TITLE
USER ISSUE: Map markers for work stations and players missing upon connecting to server.

### ISSUE THREAD

**Issue by 26chairs** [StrangeLoopGames/EcoIssues#24514]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1. Connect to a server.
2. Look at map.
3. Icons for players and work stations are missing.

**Expected behavior:**
map markers for work stations and players should be properly shown on the map after connecting to the server.

**Actual behavior:**
About half the time I connect to a server, the icons for work stations and players do not load on my map. This is a major issue as not knowing where people and work stations are makes the game difficult to play. The only fix seems to be to disconnect and reconnect, and then again, the same issue may occur on 2nd and 3rd connection. Since disconnecting and reconnecting is time-consuming, this work around is very impractical. Note that when the player and work station markers are missing on the map upon connecting, players who join the game after the fact and work stations added after the fact tend to properly appear on the map. It's as if only the initial state wasn't properly initialized upon connecting in some random cases.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by 26chairs** [comment]
Note that this is not a map configuration issue; enabling/disabling the markers does not fix the problem when you connect to a server and the markers are missing.

**Comment by D3nnis3n** [comment]
Duplicate.
