### ISSUE TITLE
USER ISSUE: Black Screen When joining server

### ISSUE THREAD

**Issue by schroe91** [StrangeLoopGames/EcoIssues#24515]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
Log back into the server

**Expected behavior:**
I can play the game and actually have visuals

**Actual behavior:**
There is a black screen but I am loaded into the game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Mods from the server yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13815123/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13815124/Player-prev.log)

**Comment by D3nnis3n** [comment]
Is it fully black or can you see HUD?

**Comment by D3nnis3n** [comment]
Merging with https://github.com/StrangeLoopGames/EcoIssues/issues/24511 due to no response.
