### ISSUE TITLE
USER ISSUE: Fehlerhafte Aufzüge

### ISSUE THREAD

**Issue by XxSlade82xX** [StrangeLoopGames/EcoIssues#24525]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Mit Fahrzeugen in die Aufzüge fahren			

**Expected behavior:**
Aufzug fährt korrekt auf und ab mitsamt der Fahrzeuge		

**Actual behavior:**
Die Fahrzeuge fallen einfach beim Fahren durch die Aufzüge nach unten, oder die Aufzüge werden auf einmal rasend schnell. Für mich erklärt sich das nur dadurch, dass die Fahrezuge Ihre Positionsdaten verlieren

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein, passiert selbst bei einer Server neukonfiguration

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
