### ISSUE TITLE
USER ISSUE: Exception after set owner as demographic group in a small canoe boat

### ISSUE THREAD

**Issue by TheJustLink** [StrangeLoopGames/EcoIssues#24521]
\
**User Id: (slg226523)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Create demographic group
2. Change owner to this demographic group
3. Get exception

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TheJustLink** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13821637/Player.log)

**Comment by D3nnis3n** [comment]
We'll need the full exception on the server, can you ask your admin to provide it?

**Comment by D3nnis3n** [comment]
Merged to https://github.com/StrangeLoopGames/EcoIssues/issues/24536, due to that having the server exception.
