### ISSUE TITLE
Crash on /give (comment told me to do this)

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#2452]
![image](https://user-images.githubusercontent.com/18184943/31143838-882b591a-a833-11e7-9907-36a383fbd0f3.png)

did the following:
/dump
/give tallow,1

**Comment by MarjieAVolk** [comment]
O.o Bet dump did something weird.  Also it's possible this PR already fixes it https://github.com/StrangeLoopGames/Eco/pull/1859

**Comment by MarjieAVolk** [comment]
Ah no I see, Clear doesn't update the components, yep that's a separate problem
