### ISSUE TITLE
Game crashes after attempting to change deed on Truck

### ISSUE THREAD

**Issue by wmattbrown16** [StrangeLoopGames/EcoIssues#24531]
Tried changing the deed on a Truck. As soon as i confirm the change, the game crashes and the change does not occur. Also happened with my friend when she tried to change the deed, as well. 
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13826557/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13826558/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24521
