### ISSUE TITLE
USER ISSUE: Aiming at the bottom of a tree shows "Left click to chop" but that does nothing

### ISSUE THREAD

**Issue by Yogu** [StrangeLoopGames/EcoIssues#24532]
\
**User Id: (slg238555)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
- Stand in front of a tree and equip an axe
- Aim at the bottom (the part that would be the stump if the tree were felled)

**Expected behavior:**
You can either fell the tree, or there should be no message indicating that you can

**Actual behavior:**
The tree highlights up, and there is a message "Left click to chop"

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

It's probably a good thing that the tree is highlighted even when aiming at the bottom. maybe just allow chopping down trees while aiming at the bottom as well? Would even make it easier to immediately after chop down the tree stump because you're already aiming at it.

![20240104105506_1](https://github.com/StrangeLoopGames/EcoIssues/assets/395810/1366064d-e490-4670-b5e2-6a36695cf8e7)

**Comment by D3nnis3n** [comment]
Fixed in Update 10.2.
