### ISSUE TITLE
USER ISSUE: Server is down

### ISSUE THREAD

**Issue by Moon9505** [StrangeLoopGames/EcoIssues#24538]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Help us

**Expected behavior:**

**Actual behavior:**
Ha aparecido el siguiente error:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not the right channel, please reach out to the server administration.
