### ISSUE TITLE
Crash a few minutes after joining a server

### ISSUE THREAD

**Issue by VincentCharpentier** [StrangeLoopGames/EcoIssues#24535]
I've been playing Eco for some time and so far everything was good until today.
Starting today the game will crash within 5 min after joining a world.
I tried to have a look at the crash logs but couldn't find anything specific except some memory allocation failures.

Here is the latest crash log file attached, is there anything I can do to get the game running again ?

Thank you

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13833870/Player.log)

**Comment by D3nnis3n** [comment]
Your laptop is below our system requirements - the log notes out of memory errors.
The only thing possible to do here is to lower the graphic settings notably and try playing on a server where not too much stuff is going on.
