### ISSUE TITLE
USER ISSUE: Low FPS on high end PC

### ISSUE THREAD

**Issue by TeamMM3** [StrangeLoopGames/EcoIssues#24537]
\
**User Id: (slg199603)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
PC is 3080 Ti, 9700k, 32 GB 3200 MhZ, running on an NVME.
Tested on high graphics settings at 4k, 2k, and 1080p.
Tested on lowest graphics settings and low FPS still occured generally when looking at certain stockpiles. 

**Expected behavior:**
~160 FPS during normal gameplay

**Actual behavior:**
FPS anywhere from 18-25 at certain times. Mostly occurs when looking at stockpiles and randomly throughout the world. Makes the game unplayable.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13837204/Player.log)

**Comment by muehan** [comment]
Same issue on 7900X3D with 4070Ti and 64Gb Memory.
>100 FTP and then it dropps to 5-16 FTP.
Just had this and now the login Servers are down...

**Comment by Coffee4cr** [comment]
Same issue with a 5700X, 3080 and 32 GB of RAM

**Comment by Coffee4cr** [comment]
> Same issue with a 5700X, 3080 and 32 GB of RAM

My issue has been somewhat fix by switching to exclusive fullscreen instead of borderless

**Comment by AndyofBorg** [comment]
I have this issue now on the current version on Steam. The performance starts good, 120+ fps, and within 1-3 hours it drops to 7.5 fps and then sometimes will go back up some, but always stays poor. Restarting the game will help temporarily but it comes back. IT feels like if I reboot my PC it can go longer before it blows up on me. It feels like a memory leak. It's always good for a while and eventually it becomes unplayable without a reboot.

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
If the performance issues persist for you, feel free to open an issue whenever you can provide the requested data.
Without the requested data we are not able to investigate the issue.
