### ISSUE TITLE
USER ISSUE: Server connection crash after changing vehicle owner

### ISSUE THREAD

**Issue by Hybris95** [StrangeLoopGames/EcoIssues#24534]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Open a vehicle you own
2. Try to change the owner

[Tested with 2 different vehicles and multiple destination owners]

**Expected behavior:**
Changed the vehicle owner and not crash

**Actual behavior:**
Server connection crash

The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumer</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Hybris95** [comment]
[EcoLog_withException.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13833190/EcoLog_withException.txt)

**Comment by Rambo99** [comment]
Very often the EcoServer.exe file is identified as a malicious Trojan. Here is the report from the Kaspersky Anti-Virus antivirus program:
Event: Malicious object detected
Program: EcoServer
User: RAMBO-SERVER\Rambo
User type: Active user
Component: Activity Monitoring
Result Description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object Type: Process
Path to object: g:\steamlibrary\steamapps\common\eco\eco_data\server
Object name: ecoserver.exe
Reason: Bases
Database release date: Today, 01/04/2024 2:19:00

**Comment by D3nnis3n** [comment]
> Very often the EcoServer.exe file is identified as a malicious Trojan. Here is the report from the Kaspersky Anti-Virus antivirus program: Event: Malicious object detected Program: EcoServer User: RAMBO-SERVER\Rambo User type: Active user Component: Activity Monitoring Result Description: Detected Type: Trojan Name: PDM:Trojan.Win32.Generic Threat level: High Object Type: Process Path to object: g:\steamlibrary\steamapps\common\eco\eco_data\server Object name: ecoserver.exe Reason: Bases Database release date: Today, 01/04/2024 2:19:00

That is a false-positive of Kaspersky.

**Comment by Rambo99** [comment]
> Do you mind making your own issue rather than sending your infos into my own which has nothing to do with your own ?

Nobody sent you anything. I just added information that it is quite possible that the problem described above is due to the fact that sometimes the server executable file behaves like a “Trojan virus” due to the fact that some function inside it is not programmed correctly. That's all. Nothing more.

**Comment by Rambo99** [comment]
> That is a false-positive of Kaspersky.

Maybe. But this did not happen on game versions 10.0.1 and 10.0.3.

**Comment by D3nnis3n** [comment]
> > Do you mind making your own issue rather than sending your infos into my own which has nothing to do with your own ?
> 
> Nobody sent you anything. I just added information that it is quite possible that the problem described above is due to the fact that sometimes the server executable file behaves like a “Trojan virus” due to the fact that some function inside it is not programmed correctly. That's all. Nothing more.

That is incorrect - it's merely because it takes a while for Kaspersky to notice it's normal software after an update. We have this problem with many antivirus for ages, after a few days they get it's fine. We could buy us onto a whitelist as many other software does, but we neither want to nor have the resources to. This problem is solely on their side and we hence also don't accept reports about it. Doing what you did will already help to get it recognized correctly earlier.
