### ISSUE TITLE
USER ISSUE: Private start

### ISSUE THREAD

**Issue by PlehmA** [StrangeLoopGames/EcoIssues#24546]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
I start a private game and i cant select a place to start

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods all vainilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
When you are in the spawn menu, on the top right side in the map settings (cogwheel) you should be able to select to display objects, if you do that, does it fix it?

**Comment by PlehmA** [comment]
Yes. Thanks.

**Comment by D3nnis3n** [comment]
Thanks, issue is tracked internally, hence closing.
