### ISSUE TITLE
Corruption detected in Storage\Game.eco! Exception: Could not read Storage\Game.eco as a zip file

### ISSUE THREAD

**Issue by ErythroCraft** [StrangeLoopGames/EcoIssues#24544]
Hello

I was running a server after setup and got a file mistake.

I edited files in the Configs folder and selected a default program (VSCode) to open the .eco file type. The following error occurred when the server was shut down.

    [16:13:44.513] [22] [Error] [Eco] Corruption detected in Storage\Game.eco! Exception: Could not read Storage\Game.eco as a zip file 
    [16:13:44.529] [22] [Error] [Eco] Restoring backup 'C:\Users\moton\Desktop\Eco Server 10.0.4\Storage\Backup\Game-2024-01-05 
    13.19.19' ...

This error arose because two different file formats are used for the .eco file extension.

In the configs the files with .eco are a text file and in the Backup/Game-.../Game.eco folder the file is a ZIP file.

I hope this bug can be fixed in the next updates.

An example of a quick fix could be to change [.eco.template] to [.eco.edited]. Instead of [.eco.template] to [.eco]

**Comment by D3nnis3n** [comment]
This is not a bug. Savegames are archives. Don't open savegames, ever.
