### ISSUE TITLE
USER ISSUE: Waking up in T-Pose

### ISSUE THREAD

**Issue by meierdesigns** [StrangeLoopGames/EcoIssues#24543]
\
**User Id: (slg17771)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Get into any bed and quit the game
Start the game and wake up from bed
get up and walk around
No animations happen anymore	

**Expected behavior:**
Normal animations after waking up

**Actual behavior:**
no animations and you can see inside of the skull

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate, logged internally.
