### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by aomiiiiiii** [StrangeLoopGames/EcoIssues#24541]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
次のエラーメッセージがポップアップ表示されました：\ n``` \ n Version mismatched.
User version: 0.10.0.4 beta release-557
Server version: 0.10.0.3 beta release-547
 \ n```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your server hasn't updated to the newest version yet. You can rollback your client to the prior version via steam betas until they updated. Right click Eco in your steam library -> properties -> betas and select 10.0.3 from the dropdown.
