### ISSUE TITLE
Currency Exchange trade button

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2454]
https://cdn.discordapp.com/attachments/338476711798898690/364892540001976320/unknown.png
https://cdn.discordapp.com/attachments/338476711798898690/364892872933113867/unknown.png
got no trade button at the currency exchange :heart:

**Comment by MarjieAVolk** [comment]
Looks like it is there and is just off the screen O.o  If you make your window wider you will see it
