### ISSUE TITLE
USER ISSUE: MICROPHONE NOT WORKING AND NO SOUND FROM OTHER PEOPLE

### ISSUE THREAD

**Issue by Mathiasleb** [StrangeLoopGames/EcoIssues#24551]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
IT WAS WORKING FOR 4 WEEKS PLAYING FINE. BUT FOR THE LAST 3 DAYS IT DOESNT ANYMORE. EVEN AFTER RESTART GAME REINSTAL THE GAME

**Expected behavior:**
MICROPHONE NOT WORKING PROXIMITY CHAT NOT WORKING

**Actual behavior:**
MICROPHONE WORKING IN WINDOWS DISCORD STEAM TEST EVERYTHING IS FINE. I CAN SEE MY MICROPHONE IN ECO AUDIO MENU TRIED DIFFERENT OPTION BUT NONE ARE WORKING

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS INSTAL . THANK YOU FOR YOUR HELP

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This can happen when the server looses connectivity to Vivox, a server restart should fix it.
Please reach out to support@strangeloopgames.com if you need further assistance.

**Comment by Mathiasleb** [comment]
HI D3nnis3n 

Unfortunately I did some restart server and it didn't change anything.
