### ISSUE TITLE
USER ISSUE: connexion error

### ISSUE THREAD

**Issue by JisatsuShiro** [StrangeLoopGames/EcoIssues#24556]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta playtest-310

**Steps to Reproduce:**
trying to join server

**Expected behavior:**
connect to server

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This just means you couldn't connect to the server, we cannot figure out why that is and it is not a bug.
There is tons of reasons why this couldn't work, both on the client and the server side. Please reach out to support@strangeloopgames.com :)
