### ISSUE TITLE
Game Crashes on loading server

### ISSUE THREAD

**Issue by TFTManus** [StrangeLoopGames/EcoIssues#24553]
The game crashes to desktop whenever it's done loading a server and attempts to enter it. No Error message.

It happens on all servers, modded and unmodded. Privately hosted too. I have already tried dialing my graphics down to minimum.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13849873/Player.log)

**Comment by TFTManus** [comment]
At the advice from some fellow players I tried the 10.0.5 beta version due to it fixing issues for older PC's and I can report that the issue is fixed when I am playing on this version.

**Comment by D3nnis3n** [comment]
Caused by non-supported too old CPU, workaround available in 10.0.5.
