### ISSUE TITLE
USER ISSUE: glitch durch blöcke

### ISSUE THREAD

**Issue by SmaxyHx** [StrangeLoopGames/EcoIssues#24567]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
erd block abgebaut, drüber gelaufen und durch alle blöcke auf höhe 7 durch geglitcht. 

**Expected behavior:**
an der oberfläche zu bleiben, auf BODEN

**Actual behavior:**
durch den boden gefallen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
keine mods vorhanden

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate. If you ever get stuck, please use /unstuck to get free.
