### ISSUE TITLE
Craft of items not right

### ISSUE THREAD

**Issue by twistchess** [StrangeLoopGames/EcoIssues#24566]
Hello,

I will make a list of crafts that are not crafting the right item.

Large Nylon Bunting Green : Creates Large Nylon Bunting Yellow
Small Nylon Bunting Green : Creates Small Nylon Bunting Yellow

All Wide frames : See https://github.com/StrangeLoopGames/EcoIssues/issues/24549

I will post other items we discover in the comments.

Good luck

**Comment by D3nnis3n** [comment]
That is a side effect of how automatic crafting is chosen, which will always show the name of the recipe you craft, but craft one of the items that are possible automatically that are part of a parent recipe. We assigned all frames to be the same parent recipe to not have a thousand of recipes in the list, which makes it possible to get a different form than you had expected. The same also applies to your other issue.

If you want a specific item, you need to select the specific recipe:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/34a86bf5-c436-417e-8ee4-b3c16a88f544)

While this definitely doesn't work as we want it to, it does work as developed and is hence not a bug. But we plan to find a better solution for that.
