### ISSUE TITLE
USER ISSUE: Seil beim Anlegeplatz nach losbinden sichtbar

### ISSUE THREAD

**Issue by Kassiopeija1308** [StrangeLoopGames/EcoIssues#24565]
\
**User Id: (slg238305)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Wenn man das angebundene Kanu am Schiffsanlegeplatz (herstellbar vom Schiffsbauer) losbindet, ist das Seil noch immer sichtbar und man zieht es hinter sich her.

**Expected behavior:**
Seil sollte unsichtbar bzw nicht da sein nach losbinden.

**Actual behavior:**
Seil sichtbar nach dem losbinden.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ja, aber das Problem tritt auch ohne Mods auf.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate.
