### ISSUE TITLE
USER ISSUE: stockpile stucking

### ISSUE THREAD

**Issue by schnepg1** [StrangeLoopGames/EcoIssues#24564]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
stockpile Window is gone but im still stuck and cant move

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes , dont know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use the command /unstuck for such cases. For investigation we'd need full reproduction steps though, that haven't been provided, hence closing the issue.
