### ISSUE TITLE
I crash when specific friend joins a server and when I hover over there name in ANY server

### ISSUE THREAD

**Issue by digitaldomino-coder** [StrangeLoopGames/EcoIssues#24569]
Hello.
- We do have two separately purchased eco accounts.
- Mine was not linked, but I have done so now and it persists.
- We are not on the same network.
- We played on Giant Panda. (Note, however, this all started happening after she joined our own server. Before update 10 we didn't get this error.)
- My exact name is DigitalDomino, her name is Missing_Aria
[Uploading Player-prev.log…]()
[Uploading Player.log…]()

**Comment by D3nnis3n** [comment]
Was reported resolved after a full reinstall, including AppData files, hence closing.
