### ISSUE TITLE
USER ISSUE: Coal and Granite Chunks are Invisible

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#24573]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta playtest-316

**Steps to Reproduce:**
1. Mine Coal or Granite
2. The chunks are invisible
3. When placed in a stockpile or on ground they are no longer invisible

**Expected behavior:**
The chunks should be fully visible

**Actual behavior:**
Instead the chunks are invisible and only have a green outline

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I think my server only uses nid toolbox

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest-317.
