### ISSUE TITLE
USER ISSUE: We killed it

### ISSUE THREAD

**Issue by CricketXO** [StrangeLoopGames/EcoIssues#24570]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. join eco
2. try to play eco
3. server dies

**Expected behavior:**
it lets you play eco (i know this isn't helpful just a :))

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes. I haven't tried it without mods we are playing in a group server. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Is the server you are trying to join actually dying or can you just not establish connection?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
