### ISSUE TITLE
the game crashes and other software crashes

### ISSUE THREAD

**Issue by BCL15** [StrangeLoopGames/EcoIssues#24576]
Version: 0.10.0.4 and now playtest version (our server went into playtest because our save file was corrupted and that was the only way to get it running again)

it happens unpredictably,  immediately after connecting to the server or after `5 / `10 / `30 ... minutes, each time the interval is different. The crash of the game was both on the version before the playtest and on the playtest, in fact it has been observed since the very release of version 10.
Together with the game, Discord, the browser (Chrome), sometimes even Steam are crashed too
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13881235/Player.log)
[Crashes.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13881241/Crashes.zip)
.

Do you have mods installed? Does the issue happen when no mods are installed?: no mods

**Comment by D3nnis3n** [comment]
Does this still persist on 10.1?

**Comment by BCL15** [comment]
yes, crash continue.
did you find any useful information from the logs, maybe you understood the reason?

**Comment by BCL15** [comment]
what ticker did you combine mine with? the link leads to it!
