### ISSUE TITLE
USER ISSUE: Soil Sampler on a cut tree crash

### ISSUE THREAD

**Issue by muffinorc** [StrangeLoopGames/EcoIssues#24571]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Cut the tree
2. Use the Soil Sampler on the dead tree part (except the tree stump)

**Expected behavior:**
should have done nothing

**Actual behavior:**
Game kicks you to the Main Menu with an error
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Mods.TechTree.SoilSamplerItem.SampleSoil(Player player, InteractionTriggerInfo triggerInfo, InteractionTa</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
only mod is discordlink on the server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13873708/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13873711/Player-prev.log)

**Comment by D3nnis3n** [comment]
Duplicate, already reported internally.
