### ISSUE TITLE
USER ISSUE: Bugged stockpile

### ISSUE THREAD

**Issue by CocoJambo23CZ** [StrangeLoopGames/EcoIssues#24589]
\
**User Id: (slg239804)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Hello if someone do a labor on your machine and dont set the destination of ending product you cant change it in your own and you must call the first man who must set it or you visualy can set it but nothing happens and the work is stoped only works for someone who do the labor

**Expected behavior:**
have a nice day ! 	

**Actual behavior:**
ECO is a life 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
one mod for clearing of chunks in world 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That works as intended, inputs and outputs are always determined by the person starting the work order.
