### ISSUE TITLE
USER ISSUE: Town influence radius moving

### ISSUE THREAD

**Issue by Uriang-Khadai** [StrangeLoopGames/EcoIssues#24586]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Found a town with 3 citizens.
2. Distribute some land claim papers and stakes
3. Play for several days without a problem
4. Hang some paintings in the town hall	

**Expected behavior:**
The influence radius should be centered on the town foundation.

**Actual behavior:**
Instead it is located far southeast in the jungle where no one lives.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Uriang-Khadai** [comment]
![Skärmbild 2024-01-10 233127](https://github.com/StrangeLoopGames/EcoIssues/assets/15888805/906b2030-f490-4f6d-a056-8c4598382e6c)
![Skärmbild 2024-01-10 234643](https://github.com/StrangeLoopGames/EcoIssues/assets/15888805/93967ea0-6ef9-4772-8197-564670a930bb)

**Comment by D3nnis3n** [comment]
Fixed in playtest, will be released with Update 10.0.5 somewhen next week.
