### ISSUE TITLE
USER ISSUE: Holz sammeln nicht möglich

### ISSUE THREAD

**Issue by McZachi** [StrangeLoopGames/EcoIssues#24584]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Baum fällen

**Expected behavior:**
Ich kann anvisieren, in Stücke teilen und aufnehmen

**Actual behavior:**
Ich kann den Baum nicht anvisieren. Aber dennoch gegen laufen und verschieben

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate interaction problem, reported internally.
