### ISSUE TITLE
USER ISSUE: Painting bug

### ISSUE THREAD

**Issue by randomO9** [StrangeLoopGames/EcoIssues#24587]
\
**User Id: (slg228299)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Try to save a painting on a linux dedicated host

**Expected behavior:**
it should save

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: DllNotFoundException
Message:Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/steam/.net/EcoServer/DUHYGO9</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
As of the exception, the installation was not followed through fully, you are missing libgdiplus.

Please install that and open a new issue with the full server log if that does not fix it :)

**Comment by randomO9** [comment]
steamcmd was used for the install, has the install process changed in update 10?

**Comment by randomO9** [comment]
Figured it out, forgot to run install.sh in the install dir
