### ISSUE TITLE
USER ISSUE: Shadow o1. goto graphic setting

### ISSUE THREAD

**Issue by andsim** [StrangeLoopGames/EcoIssues#24588]
\
**User Id: (slg80709)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. goto graphic setting
2. turn up shadow option tro max

**Expected behavior:**
max shadow depend on hardware 
3070ti should be able handle it

**Actual behavior:**
it drop frame to the floor as 1 fps

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes this no mod 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Coffee4cr** [comment]
I have a 3080 12GB   and a Ryzen 5700X   with 32 GB of ram,
same issue, anything above medium shadows, after an hour or so of playing I will go to certain places and go from 100+ fps to 1-6fps.

The biggest culprit is my house, in the basement I'm digging which borders the river. If I look at the wall that's against the river it tanks my fps

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24830
