### ISSUE TITLE
USER ISSUE: Soil Sample Palm Leaf

### ISSUE THREAD

**Issue by SohamSaha** [StrangeLoopGames/EcoIssues#24583]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1) Have a palm species leaf (?) available in front of you
2) Use the soil sample tool on the leaf

**Expected behavior:**
Not worked (?)

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Mods.TechTree.SoilSamplerItem.SampleSoil(Player player, InteractionTriggerInfo triggerInfo, InteractionTa</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest-318.
