### ISSUE TITLE
USER ISSUE: Game crashed while using soil sampler on a tree

### ISSUE THREAD

**Issue by ScottEco** [StrangeLoopGames/EcoIssues#24582]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Aim at a tree and left click with a soil sampler in hand.

**Expected behavior:**
We should see a pop up with information on tree and soil.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: InvalidOperationException
Message:Nullable object must have a value.
Source:System.Private.CoreLib

System.InvalidOperationException: Nullable object must have a value.
   at Eco.Mods.TechTree.SoilSamplerItem.SampleSoil(Player player, InteractionTriggerInfo triggerInfo, InteractionTa</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and I don't know.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest-318.
