### ISSUE TITLE
USER ISSUE: Transfering vehicle deed in a settlement

### ISSUE THREAD

**Issue by XanderTDark1** [StrangeLoopGames/EcoIssues#24597]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
create a law allowing vehicle transfer of property
bring up the vehicle deed, in this case it was for a large canoe, select the settings cog wheel and transfer ownership to another player or titled played in the settlement. yes to confirm

**Expected behavior:**
should have transfered ownership 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumer</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
unknown

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
