### ISSUE TITLE
Playtest-320 Client error on attempting to connect to server

### ISSUE THREAD

**Issue by Dave4291** [StrangeLoopGames/EcoIssues#24593]
Using playtest-320 with settlements set to false (ie. using pre v10 system).

Connecting to server results in attached error and failed connection. This happens on both a pre-existing world from playtest-316 and earlier, and a newly created world on playtest-320.

No issues with settlements enabled, however not compatible with an existing settlements disabled save as the server fails to start.

Client log, server log, and save files attached.

[message.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13905126/message.txt)
[server_error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13905127/server_error.txt)

[world-2024-01-11.zip](https://github.com/StrangeLoopGames/EcoIssues/files/13905130/world-2024-01-11.zip)

**Comment by D3nnis3n** [comment]
Fixed in playtest-321.
