### ISSUE TITLE
USER ISSUE: Cart disappearing suddently

### ISSUE THREAD

**Issue by Ehrendil** [StrangeLoopGames/EcoIssues#24590]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Add something in the cart with an iron shovel

**Expected behavior:**
pile actually added

**Actual behavior:**
but the cart completely disappeared, but the stockage can be seen threw an other stockpile near

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nope

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce this, is there any reproduction steps?

**Comment by Ehrendil** [comment]
I don't know what to add more... I just added sand to a cart in a "mine", they it disappeared and nowhere to be found...

**Comment by D3nnis3n** [comment]
Can you find it via typing the name of the cart in the chat? So far not reproducible.

**Comment by D3nnis3n** [comment]
Closing due to not being reproducible, no further reports and no additional information provided.
