### ISSUE TITLE
USER ISSUE: NPE when opening someone else's deed and attempting to transfer ownership

### ISSUE THREAD

**Issue by skner-dev** [StrangeLoopGames/EcoIssues#24596]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Go to someone's Shop and in the Authorization tab, open Deed.
In the deed's authorisation, click the cog icon to change the owner.
Select yourself.
Crash occurs.

**Expected behavior:**
I'm not sure, maybe display a message saying I'm not authorized?

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
