### ISSUE TITLE
[10.0..4] Server Crush on starting

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#24594]
I'm trying to start my server to play with friends over a local network, but the process crashes to the desktop either without any error messages at the startup (initialization) stage, or with the message "out of memory". I tried to change the size of the world from 72x72 to 360x360, the result is always the same and is described above. I am attaching the log files (latest).
[log_240111073139.log](https://github.com/StrangeLoopGames/EcoIssues/files/13906144/log_240111073139.log)

**Comment by D3nnis3n** [comment]
A world size of 360x360 is massively beyond our supported maximum size which is 160x160, the issue is caused by this. You are trying to generate a bigger than 8km² world, with 2.56 km² being the maximum supported size.

**Comment by Rambo99** [comment]
I won’t argue with you, I’ll just say that you’re wrong. Try to run a server with a world size of 380x380, the program will throw an error and write itself what the maximum size of the world can be generated. If you carefully read the information given there, you will understand everything. Nevertheless, the server works STABLE with a world size of 256x256 (6.5 sq. km.). But thanks anyway for the answer.

**Comment by D3nnis3n** [comment]
I don't need to argue, as I am the person that determined the supported world sizes that are also documented publicly on our wiki, which will confirm what I said: https://wiki.play.eco/en/Server_Configuration#Change_World_Size

Any size above 2.56 km² does not get support by us, any size beyond 4km² is not eligible for bug reports.

**Comment by Rambo99** [comment]
> I don't need to argue, as I am the person that determined the supported world sizes that are also documented publicly on our wiki, which will confirm what I said: https://wiki.play.eco/en/Server_Configuration#Change_World_Size
> 
> Any size above 2.56 km² does not get support by us, any size beyond 4km² is not eligible for bug reports. That was obviously the case as shown in your log, as such the usage is unsupported and the issue was closed. The article also states that you can try to generate bigger ones, but that this is not supported and issues can appear - as they did here.

I'm not going to argue with you. But you don't seem to read user messages. Read the first message carefully. It says that the server crashes at ANY SIZE of the generated world from 72x72 to 360x360. And the log file is from the last attempt to generate the game world. Also in the article to which you refer it is said that to generate worlds exceeding an area of 4 square meters. km. you need to download a separate special version of the program from your website, which was done. As a result, we have what we have (described above). I understood your train of thought. Thanks for your time.

**Comment by D3nnis3n** [comment]
With all due respect, but the very log you attached shows that you used an unsupported world size in your last crashing try:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/12b0beec-4366-479e-bda4-0c4361f7b8a5)

There is zero evidence in your post of stuff below that crashing (and it is for noone else) and you have just confirmed that a 6km² world did work.

And no, the wiki nowhere states you need to download a special program for more than 4km². It states that we only offer support up to 2.56 km² and bug report acceptance up to 4 km². Which the world in the logfile was clearly beyond?
