### ISSUE TITLE
black lines on road texture

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#246]
![image](https://cloud.githubusercontent.com/assets/3150561/15946534/19c7d550-2e4c-11e6-8c12-34ab61541eef.png)

mipping issue?

**Comment by metachronism** [comment]
![image](https://cloud.githubusercontent.com/assets/3150561/15946591/5c865ce0-2e4c-11e6-8c39-e1b492867333.png)

**Comment by keegan-o** [comment]
Fixed along with some other visual tweaks
