### ISSUE TITLE
USER ISSUE: Eco freezes when I open the Avatar tab in Settings

### ISSUE THREAD

**Issue by Chriwro** [StrangeLoopGames/EcoIssues#24604]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Open Settings
2. Press the tab that says Avatar

**Expected behavior:**
The tab opens so I can customize my avatar

**Actual behavior:**
The game freezes. Nothing can be clicked on or operated in any way anymore. Sound continues to play. Eco is shown as "inactive" in Task Manager.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I don't have any mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide log files as instructed in the report form :)

**Comment by Chriwro** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13933471/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13933472/Player-prev.log)

**Comment by D3nnis3n** [comment]
Is this persisting in Update 10.1 and can you provide new logs for it?

**Comment by Chriwro** [comment]
Hello, yes the Issue still exist in the 10.1.1 Update
 Here the new log Files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13994838/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13994839/Player-prev.log)

**Comment by D3nnis3n** [comment]
Can you try to open the program run, enter "%UserProfile%\AppData\LocalLow\Strange Loop Games" and delete the folder "Eco"? Does that help?

Are you using any antivirus software?

**Comment by D3nnis3n** [comment]
Do you have any type of real or virtual webcam?

**Comment by Chriwro** [comment]
> Do you have any type of real or virtual webcam?

Yes, I am using a Logitech C920 webcam (mostly not plugged in) and Nvidia Broadcast is installed.

**Comment by D3nnis3n** [comment]
Have you tried opening the avatar creator with the webcam and its drivers removed?

**Comment by Chriwro** [comment]
Hello, i deactivated the virtual cameras one by one. I had an old version of the Software VseeFace installed with its drivers, which caused the error. i had not used it since years so i forgot that it was installed. I updated the software and its driver and actually it works. Problem should be solved 👍🏻
