### ISSUE TITLE
USER ISSUE: Could not select anything after restart/ login

### ISSUE THREAD

**Issue by CricketXO** [StrangeLoopGames/EcoIssues#24603]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Often times select is not responsive when harvesting in this case I was just trying to E on the seed table and couldn't select it. Logging out and in tends to fix but it never did this last year when we played. 			

**Expected behavior:**
Let me access the table with E

**Actual behavior:**
No error no response at all just nothing logged out back in and it works

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes server mods can't test without because isnt my server sorry

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate interaction issue, already logged internally. Thanks for the report.

**Comment by CricketXO** [comment]
🙂 np thanks! I really hope they fix the country/ city laws it adds a whole lvl of unnecessary complexity and makes the game almost unplayable for those of us that do foraging and farming ...
________________________________

**Comment by D3nnis3n** [comment]
Those aren't broken - it's part of our extended settlement system, allowing more localized governance. It's not unnecessary either, we purposefully tied in the government system much more deeply with Eco, it's one of the base pillars this game is developed on, next to Ecology and Economy.

If you are having issues with local laws, communication is absolutely key in Eco, basically always.
