### ISSUE TITLE
/Util Invisible command still leaves the player visible on the minimap

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#24607]
I was looking into a supicious player who was flying around the map and they logged out when I teleported to them while invisible.
I asked my partner if she could see me on the map and she could (saw it on her screen).

So the /util invisible command is currently not fully functional as admins can't observe suspicious players without them spotting you.

STR:
1. Use /util invisible
2. Have a second player look at your location on the map.
3. Observe that the second player can see the invisible player on the map.

**Comment by D3nnis3n** [comment]
Thanks, already got this reported internally from playtest, hence closing. (We only use this tracker to take bugs, they're handled on the internal now)

This will likely not be fixed quickly, though, given this feature was specifically introduced to fulfill chinese government regulations and our china build is currently on hold.
