### ISSUE TITLE
USER ISSUE: Gamebreaker and Computer freeze

### ISSUE THREAD

**Issue by Nemesssis** [StrangeLoopGames/EcoIssues#24602]
\
**User Id: (slg222333)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Steinstraßen im Invantar haben 20 stk
2. Eisenhammer auswählen
3. Rampe C auswählen
4. An 3 Rampe B ansetzen
5. 5-8 Blöcke rückwärts laufen bis man ins meer tritt

**Expected behavior:**
Spiel und PC laufen weiter

**Actual behavior:**
Spiel und PC frieren ein und man kann nichts mehr machen.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ja und JA

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Nemesssis** [comment]
![20240113201152_1](https://github.com/StrangeLoopGames/EcoIssues/assets/30659759/22b58bcd-19b9-4cf1-8256-26070fbb1010)
![20240113201157_1](https://github.com/StrangeLoopGames/EcoIssues/assets/30659759/e3bbec68-4ab3-4daa-9574-e2087750aad7)
![20240113201205_1](https://github.com/StrangeLoopGames/EcoIssues/assets/30659759/29fb5771-968d-4514-9875-d9083c3a8a36)
![20240113201213_1](https://github.com/StrangeLoopGames/EcoIssues/assets/30659759/77d6bde1-e0f4-48e4-8b7c-05d3053c5e9f)

![20240113201159_1](https://github.com/StrangeLoopGames/EcoIssues/assets/30659759/0dd9c352-c814-4eef-ae52-958e030d9c64)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24599
