### ISSUE TITLE
USER ISSUE: Remap of keyboard keys

### ISSUE THREAD

**Issue by madndm** [StrangeLoopGames/EcoIssues#24600]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
1. Open settings
2. Controls
3. Try to remap keyboard's keys assign from Q to W (for AZERTY keyboard)		

**Expected behavior:**
We can reassign control from Q to W

**Actual behavior:**
There are many control assign to Q, but when we reassign one of them, we can't assign the others : popup message warns us about the keys yet used for other action and we can't bypass this

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24064
