### ISSUE TITLE
Store inventory formatting is broken when you have tens of thousands of something for sale

### ISSUE THREAD

**Issue by orborde** [StrangeLoopGames/EcoIssues#24605]
![Screenshot 2024-01-13 173311](https://github.com/StrangeLoopGames/EcoIssues/assets/804638/c430442c-3ed8-4529-a393-04632f4a54ea)

We have over 20,000 granite in the attached stockpiles, and this is what the store selling it looks like as a result.

**Comment by D3nnis3n** [comment]
Fixed in Update 10.2.
