### ISSUE TITLE
Bug: Balance Issue: Geology Research Paper Modern Glass

### ISSUE THREAD

**Issue by jwmc80** [StrangeLoopGames/EcoIssues#24610]
Bug/Update needed:
change Glass input to dynamic for Geology Research Paper Modern Glass

Geology Research Paper Modern Glass
Glass input is static

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/91993280/536c1428-536d-4b99-9a80-916ee6e1db99)

Geology Research Paper Modern (brick)
Brick input is dynamic

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/91993280/97f16332-9ce3-4ed6-b727-390b62e403b2)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
