### ISSUE TITLE
USER ISSUE: "Login token changed" causing exit

### ISSUE THREAD

**Issue by IceLordUlmo** [StrangeLoopGames/EcoIssues#24619]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
sailing a wooden boat? nothing in particular

**Expected behavior:**
just let me keep sailing the boat? idk, seems like an authentication issue probably unrelated to in-game behavior as I was not activating anything

**Actual behavior:**
The following error message popped up:
```
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13956583/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13956584/Player-prev.log)

Login token changed.

<size=60.00%>Internal Server Error, Trace ID: 00-e0f80042e5a4244e0e572341be90fef2-1700da9279a87a87-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13956583/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13956584/Player-prev.log)

**Comment by D3nnis3n** [comment]
This is not a bug, but the disconnect at 0:00 CET from Tuesday to Wednesday when Steam does maintenance and disconnects players for a few minutes until their connection manager servers are up again: https://steamstat.us/
