### ISSUE TITLE
crash when try to change ownership of a steam truck who's not mine 

### ISSUE THREAD

**Issue by Kotarik** [StrangeLoopGames/EcoIssues#24612]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
enter in authorisation tab of a steam truck who's not mine, but to a cityzen of my city. i'm a authorised user on the steam truck. when i click on the gear wheel to change the owner, and change for me, the connection to the serveur encounter an exeption.

**Expected behavior:**
popup an error message say "you don't have the right to steal the steam truck" 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13950553/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13950554/Player.log)

Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed in playtest.
