### ISSUE TITLE
Client crash on treasury "show government accounts"

### ISSUE THREAD

**Issue by Dave4291** [StrangeLoopGames/EcoIssues#24618]
0.10.1.0 beta-release-570 and 0.10.1.0 beta-release-574

When using the treasury, on clicking "show government accounts" the client is disconnected from the server.

Same issue for another player. New settlements system is off.

Log attached.
[Server encountered an exception.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13956285/Server.encountered.an.exception.txt)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
