### ISSUE TITLE
Jerky, buggy in-game voice chat

### ISSUE THREAD

**Issue by Jimbnl74** [StrangeLoopGames/EcoIssues#24626]
Hello,

I have a problem with the voice chat in the game. I can hear the other players jerkily and they can hear me jerkily too. 
This is not due to the connection as I have fibre and I have tried on another less powerful computer and it works.
Is it possible that there is an incompatibility with one of the drivers on my PC?
The game sound works fine apart from the voice chat.
Thanks

Pilote realtek audio 6.0.9597.1
MSI KATANA 15 B12V 

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13970145/Player-prev.log)
[Player.log](https:/
[error.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13970150/error.txt)
/github.com/StrangeLoopGames/EcoIssues/files/13970146/Player.log)

**Comment by D3nnis3n** [comment]
Our voice chat system is using external software, Vivox. The logs do not give any hint to what happens here.
If the issue persists, please reach out to support@strangeloopgames.com, they will be able to redirect the report to Vivox.
