### ISSUE TITLE
Alpha 6.0.1 [51df7483] Drag & drop errors

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2462]
Sometimes we have the problem that drop will cause an error:
- Item Icon will stop moving
- Cursor still have drop animation

![image](https://user-images.githubusercontent.com/1900106/31196936-bf9c6dd6-a94f-11e7-96ea-e252c9920022.png)

We noticed by moving stuff from stockpile to stockpile as fast as possible, because on some clients it happens exactly at the same time.

It's rare, unable to reproduce appears randomly

**Comment by MarjieAVolk** [comment]
How long does it stay like that?  A couple seconds, or longer?

Do you have any client error logs?

**Comment by Fank** [comment]
As long as the client is running, only a close and reopen will fix this.

**Comment by Dreconic** [comment]
I have had this happen several times myself. Even when moving slowly if I hid a square to drop it in at the wrong angle etc it seems to do this, I can get it to revert without a reboot by dragging something else to where the item was, thus swapping it, then dragging the original bugged item to the storage/stockpile.

**Comment by RowanJones** [comment]
I had this with the scrolls. Even with restarting the game, it stayed in the center of my screen. I had to reinstall the game on my personal end before it went away. The weird thing was, I could still drag and drop and get infinity scrolls.

**Comment by metachronism** [comment]
punting this to beta as it is hard to repro

**Comment by metachronism** [comment]
still can't repro this; going to close till a reliable repro case is found

**Comment by Gringar** [comment]
I know this is closed but this exact thing happens to me sometimes in 7.0.5. It seems to happen most often near my own house. When it happens it's like the mouse is being clicked rapidly. You can see it open and close very fast. When you try to drag something it ends up jumping into a slot along the way or getting stuck like in the picture.

It may have something to do with having a project running on the workbench. That's when I notice it most. Order something on the workbench and take that time to arrange inventory.

**Comment by MarjieAVolk** [comment]
There is currently a different bug open for this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/3841

I will paste your comments over there
