### ISSUE TITLE
Lasers don't shoot meteor

### ISSUE THREAD

**Issue by Csuhi81** [StrangeLoopGames/EcoIssues#24624]
Hello! I have four lasers and want to shoot the meteor. I push the activate button. 4 lasers are targeting the meteor, then one of them lost the focus, and the destruction is cancelled. I have 42k W. I'm trying for hours. Do you know about this bug? What can I do now to complete the mission?

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com for user questions, the provided data doesn't follow the requirements for a bug report. For the meanwhile: Have you made sure you have enough power generators dedicated to the lasers? It would normally do this if the available power for a moment is no longer high enough for whatever reason.
