### ISSUE TITLE
USER ISSUE: Deleted an entire world after crash

### ISSUE THREAD

**Issue by MijjMijj** [StrangeLoopGames/EcoIssues#24627]
\
**User Id: (slg144120)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
crashed to main menu with 'could not reach server' error message after game froze when property claimingafter loading world again (single player) game loads on ' choose starting location' map as if it was a new gamedays of building and crafting lost 

**Expected behavior:**
not have deleted an entire worldmade me happy

**Actual behavior:**
deleted an entire worldmade me sad

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed / active

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Eco cannot delete worlds without you manually doing that, more likely is it automatically being restored from a backup, if not something entirely different happened. You'd need to reach out to support@strangeloopgames.com for deeper investigation, this report does not provide any starting points for a bug.
