### ISSUE TITLE
USER ISSUE: Изменение владельца

### ISSUE THREAD

**Issue by SentilONE** [StrangeLoopGames/EcoIssues#24623]
\
**User Id: (slg101815)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Попытка изменит ьвладельца собственности тележки.

**Expected behavior:**
Владелец собственности изменяется корректно.

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:System.Linq

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumer</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Выделенный сервер с модификациями.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest.
