### ISSUE TITLE
USER ISSUE: Cannot join Servers

### ISSUE THREAD

**Issue by Duncey2024** [StrangeLoopGames/EcoIssues#24632]
\
**User Id: (slg241586)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Cannot join servers both official and unofficial. i have uninstalled and reinstalled the game, i have verified my files but i keep getting an error

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Players.User.Login(Player player, INetClient client, Boolean allowDisconne</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Duncey2024** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13977031/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13977032/Player-prev.log)

**Comment by Duncey2024** [comment]
with new update i cant even attempt to join servers anymore, i load ECO and it just gives me the background and nothing else

**Comment by D3nnis3n** [comment]
The log hints at a corrupt installation. Please uninstall Eco via Steam, then remove the full /Steam/steamapps/common/Eco folder. (Backup the folders "configs" and "storage" in /Steam/steamapps/common/Eco/Eco_Data/Server if you have singleplayer worlds you want to restore later by copying them in again)

Afterwards also remove the AppData/LocalLow/Strange Loop Games folder, it is hidden by default, you can get there by opening "run" and typing `%UserProfile%\AppData\LocalLow\` quickly.

After this please try again and if it still fails, provide a new logfile.

**Comment by Duncey2024** [comment]
Thanks for the reply.

i have tried as you said but nothing changed
i am still having the same issue where i only see eco background and nothing else. i cannot attempt to load servers anymore
![main menu eco](https://github.com/StrangeLoopGames/EcoIssues/assets/157027475/e05a9fda-035d-44a2-ae27-39508c94b253)

**Comment by D3nnis3n** [comment]
Please attach new logs and a screenshot from the ESC menu.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
