### ISSUE TITLE
USER ISSUE: Citizen timer LAW 

### ISSUE THREAD

**Issue by CocoJambo23CZ** [StrangeLoopGames/EcoIssues#24631]
\
**User Id: (slg239804)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
Hello citizen timer with bad combination  in law shutting down server in a infinity loop 

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by CocoJambo23CZ** [comment]
![bugeco](https://github.com/StrangeLoopGames/EcoIssues/assets/156304788/30ba6524-33da-493b-b129-eb8b271abc92)
this law

**Comment by D3nnis3n** [comment]
Fixed in playtest.
