### ISSUE TITLE
null reference -registrar

### ISSUE THREAD

**Issue by teagan75** [StrangeLoopGames/EcoIssues#24630]
After a daily restart, players cannot enter game and server throws this error. Backup will not allow players to load in either.
[crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13973659/crash.txt)
[log_240118120030.log](https://github.com/StrangeLoopGames/EcoIssues/files/13973676/log_240118120030.log)

**Comment by D3nnis3n** [comment]
Please attach save game.

**Comment by teagan75** [comment]
https://drive.google.com/file/d/1qafIXqY53a8TgUYGpLBCxYZwm0D-FX0p/view?usp=sharing

**Comment by teagan75** [comment]
For context, a backup from 2 days ago won’t load either. I do not have a clue as to what happened

**Comment by teagan75** [comment]
I assume this save is a loss. I was able to get a backup from 2 days ago to load after loading a backup from last week successfully. I wasn’t able to do that before loading the week old backup. So very strange. Is there something I can do to prevent this happening again?

**Comment by gzatravkin** [comment]
Do you have mods on your server?

It seems like the issue is some law refering item that was existing at your server before migration but doesnt exists after (most likely some modded item).

**Comment by teagan75** [comment]
i do but this save wasn't migrated. The cycle started on 10.0.4 and just failed to allow players to load into the world after a restart. But i will keep this in mind thank you

**Comment by D3nnis3n** [comment]
Object this seems to refer to:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/fed92766-cab1-46e1-bb30-056d4ec11839)

**Comment by teagan75** [comment]
Thanks for the info.
