### ISSUE TITLE
Huckleberries tooltip text repeats skills

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2463]
![image](https://user-images.githubusercontent.com/3536496/31204296-1064dd64-a920-11e7-9b33-a4921fd3f429.png)
(havent synced in awhile could be a false positive)

**Comment by MarjieAVolk** [comment]
Oh lol, I had a bug for this and just closed it as no repro.  How did you get it?  Any like world regeneration or anything weird like that?

**Comment by johnkslg** [comment]
perhaps starting and stopping the server did it? ill try some things

**Comment by johnkslg** [comment]
restarting it, rather

**Comment by MarjieAVolk** [comment]
Think this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/2594, which was fixed
