### ISSUE TITLE
USER ISSUE: v10.1.0 Regression: Contract tooltips no longer activate on the Contracts menu within Economy view

### ISSUE THREAD

**Issue by Maelstromeous** [StrangeLoopGames/EcoIssues#24635]
\
**User Id: (slg217343)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
1. Press Y
2. Go to Contracts
3. Hover over a contract

**Expected behavior:**
It should have opened a tooltip with information about the contract

**Actual behavior:**
It does not open the tooltip any more

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
@Maelstromeous thank you for reporting this to us, I have forward this issue to our developer to look into.

internal ref : 32828

**Comment by D3nnis3n** [comment]
Will be fixed in Hotfix 10.1.2.
