### ISSUE TITLE
USER ISSUE: Tooltips don't work when hovering over items in a "Put items in container" contract

### ISSUE THREAD

**Issue by Maelstromeous** [StrangeLoopGames/EcoIssues#24639]
\
**User Id: (slg217343)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
1. Create a "Put items in container" contract, adding an item to it
2. View the created contract
3. Hover over an item within the contract

**Expected behavior:**
It should show a tooltip of the item, the skills required to manufacture it etc as it does in various other places in the game. Other functions you'd expect to have tooltips e.g. the deposit location etc there's no tooltip, making it difficult to know where to drop off the goods.

**Actual behavior:**
Does nothing at all, pretty sure it used to.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Contract created by others:
https://github.com/StrangeLoopGames/EcoIssues/assets/1776058/4c3ee9ca-1afd-4eab-88f4-4fef4d858217

Contract created by me:
https://github.com/StrangeLoopGames/EcoIssues/assets/1776058/53937b43-2380-4bd5-9dfc-6776260ab9ab

**Comment by D3nnis3n** [comment]
Will be fixed in Hotfix 10.1.2.
