### ISSUE TITLE
Steamtruck stuck on barge when trying to drive off

### ISSUE THREAD

**Issue by JoshuaStelten** [StrangeLoopGames/EcoIssues#24638]
Version: 10.1.0
Self hosted eco server

Ever since the new update all barges on the server somehow break the steam truck.
I can drive the steam truck on the barge, close the ramp and untie the rope. Then I move the barge to the destination port. I tie the barge up again, open the ramp and get in the steam truck. I can hear the engine and it is using fuel. But it refuses to move. It does not even turn its wheels.

What did I try already to fix it?

- /freecar does not do anything
- Using the hammer does not do anything
- Restarting my client seems to unlock it, when I moved it with the hammer before it is now showing up in that new position. I can drive it, but sometimes I get the message that I cannot interact with the vehicle while it is on a ship(I'm in the middle of a city). But sometimes I can also pickup my steam truck off the ocean floor after restarting the game
- Restarting the server unlocks the vehicles as well, but that might also be because I restarted the client

There are no server logs because it does not generate any errors. But it does render the server unplayable as we rely heavily on a barge to move resources between islands. It just seems like the client is not updated properly to unlock the vehicle after the ramp has been opened.

If any more info is needed I'm happy to provide

**Comment by JoshuaStelten** [comment]
Rolling back to 10.0.4 does seem to fix the issue for now

**Comment by D3nnis3n** [comment]
Fixed for 10.1.2.
