### ISSUE TITLE
USER ISSUE: Contract Board: Creating a draft prevents opening the opposite menu

### ISSUE THREAD

**Issue by Maelstromeous** [StrangeLoopGames/EcoIssues#24636]
**User Id: (slg217343)**
**Version:** 0.10.1.0 beta release-576 (also same in 0.10.0.x)

**Steps to Reproduce:**
1. Open a contract board
2. Open a contract, close it (don't delete it)
3. Attempt to open a work party, notice the Contract UI is open, it will continue to open the wrong UI until you delete the contract
4. Delete the contract
5. Open the work party UI, the correct UI opens.
6. Same in reverse

**Expected behavior:**
It should prompt the user to delete the draft of the contract / work party 

**Actual behavior:**
Opens the wrong UI leaving the user very confused

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That actually works as intended. You cannot make multiple contract drafts at once, hence you need to remove a draft that is still open before being able to start a new contract. We received feedback that the prompt was confusing and didn't allow to reach the  draft that needs to be removed, hence we now directly open it for the user.

**Comment by Maelstromeous** [comment]
Appreciate the response @D3nnis3n , I'd reconsider adding a prompt to the user to consider deleting the draft contract / work party though. I've started playing with a group of new players, and every single one of them got confused by it, including myself. 

A prompt saying "You already have a draft [contract/work party] open, do you wish to delete it? [Yes/No]"

Currently unless you intrinsically know the UI that opener was not the UI you intended, it's super confusing. It harms the new player experience quite considerably and it feel like a glaring bug to them.

**Comment by D3nnis3n** [comment]
We'll monitor this to see if and where improvements can be made - but the UI opening already does tell you what the problem is and why it opens:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/ececba33-3928-46f5-bd01-a4c5a448f248)

The text message is not super visible though, as it is behind the darkening layer, which we will fix. The general working as mentioned is not a bug, but given on further player feedback may be adjusted - I have added your feedback as a suggestion for our team.

**Comment by TomyKalm** [comment]
Have had the same issue
Would like this "fixed" or changed to be more clear.

Currently when you have a draft for a work order and try to make a new contract then it is really confusing why it opens a work order. For me that looks like a UI bug.

**Comment by Maelstromeous** [comment]
Ok I see it, I'm on a 4K monitor and the toast is quite hard to see, I must have missed it multiple times.

If we could improve this, and put the toast right in the center of the UI or in a much more prominent place, this would address the confusion for sure. The fact it's semi "greyed out" also doesn't help :-/ 

For reference here's how it looks at my resolution:

https://github.com/StrangeLoopGames/EcoIssues/assets/1776058/e55de134-1bb4-4387-9af7-de39536aecda
