### ISSUE TITLE
Serrver fails to start after 10.1 update

### ISSUE THREAD

**Issue by typhado** [StrangeLoopGames/EcoIssues#24644]
Playing on a nodecraft private eco server (no mods). Updated to 10.1 and server fails to start.

[log_240118122557.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982583/log_240118122557.log)

Game File: https://drive.google.com/file/d/1YdkDgzrhdLQXNP5kTJn6kEPv_mpYxXCi/view?usp=drive_link

**Comment by gzatravkin** [comment]
Requested the access to save file

**Comment by typhado** [comment]
> Requested the access to save file

Granted

**Comment by petr-motejlek** [comment]
Our dedicated server is also affected by this. This might be a red herring, but it seems to us that the patch itself doesn't break the game when launching it for the first time (after installing the patch). However, stopping and starting the game later, is when the server fails to start.
