### ISSUE TITLE
USER ISSUE: admin owning a car

### ISSUE THREAD

**Issue by collinticer** [StrangeLoopGames/EcoIssues#24647]
\
**User Id: (slg204049)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
1) own a cart that has already granted access to other citizens by original cart owner. 2) notice how you can't remove access to these citizens (this is the bug) 3) transfer the deed back to the original owner 4) notice how you can now remove the first authed user from authed users list (another bug?)

**Expected behavior:**
if i own the cart i should be able to removed authed users from a cart no matter who added them. i also should not be able to remove them if i don't own the deed.

**Actual behavior:**
i can not remove someone once i own a cart (via /ownit admin command) but i can remove just the one person once i transfer the deed out of my ownership.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
discord link.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by collinticer** [comment]
actually appears to maybe be UI related. if i close the cart UI and re-open after i own the cart, i seem to be able to remove authed users

**Comment by collinticer** [comment]
seems rather buggy overall. i now can't add authed authorized consumers via the cart UI under certain circumstances.

**Comment by collinticer** [comment]
> Fixed: After using /ownit on a vehicle, players authorized on it could no longer be reliably removed

This is mentioned in the latest patch notes for 10.1.3 so this may now be resolved. I'll close this tonight after updating my server and verifying, if y'all don't. 

Thanks for all y'all do to support this game! :D

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
