### ISSUE TITLE
USER ISSUE: Grass floats above stockpiles when dirt has been moved

### ISSUE THREAD

**Issue by Maelstromeous** [StrangeLoopGames/EcoIssues#24646]
\
**User Id: (slg217343)**
**Version:** 0.10.1.0 beta release-576 (possible regression of 0.10.0.x)

**Steps to Reproduce:**
1. Create a stockpile
2. Put dirt within the stockpile
3. Wait until grass grows on top of the dirt
4. Move the dirt out of the stockpile
5. Observe grass floating

**Expected behavior:**
The stockpile should not have grass above it

**Actual behavior:**
Instead the grass remains where the dirt blocks once were, not despawning.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

![Image](https://i.imgur.com/pFNWUfg.jpeg)

**Comment by D3nnis3n** [comment]
Closing as won't fix, this has been around forever - including for saplings, and is kind of a meme by now. We may address this somewhen in the future, but not in the forseeable one. It also already has a internal issue that is iceboxed.
