### ISSUE TITLE
No recipe for cast iron stove

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#2464]
???

**Comment by Fank** [comment]
I crafted it some staging versions ago at the anvil

**Comment by Fank** [comment]
Staging 0.6.0.1 E6396fad :
![image](https://user-images.githubusercontent.com/1900106/31249880-4edf5a66-aa19-11e7-98e4-8e34de145fc5.png)

Were 20 IronIngot before:
https://github.com/StrangeLoopGames/Eco/commit/2e4c7d139ffe95fa53acd8b345887952f31ee849#diff-396046a22138d640242fbaf4fbbb2afbL536
