### ISSUE TITLE
USER ISSUE: Crane freeze game on use

### ISSUE THREAD

**Issue by ZwiebelTVDE** [StrangeLoopGames/EcoIssues#24642]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
Build crane
Place crane
Pickup stockpile
freeze. ¯\_( ͡° ͜ʖ ͡°)_/¯

**Expected behavior:**
Able to pick up items without game freezing

**Actual behavior:**
game freezes and only a restart of the game is able to play again

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes we have fishing mod installed, yes the issue still happens without mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by esperadus** [comment]
reproduced on my pc aswell in singleplayer
crane works without an hinch until you pickup a stockpile.
In my case with some stones in a brand new world. 
I cheated the crane.

Regards
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982390/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/13982391/Player.log)

**Comment by ZwiebelTVDE** [comment]
Update: Issue persists in 10.1.2

**Comment by Maxafrost** [comment]
Is there a way to remove the crane? I placed it to test how it works and now it's in my way, trying to pick it up results with "Cannot pick up the crane while its claw is carrying something.", entering is an immeadiate crash.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/48632438/48c74775-8e03-46ff-8c85-c0823844448f)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
