### ISSUE TITLE
USER ISSUE: Cannot connnect to server

### ISSUE THREAD

**Issue by Duplo52** [StrangeLoopGames/EcoIssues#24649]
\
**User Id: (slg236252)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
Not sure, I was trying to joina  friends server.
Validated game files.
Tried to join Planet Legion server.
Pops me out and says invalid session but I'm watching them play. 

**Expected behavior:**
let me connect.

**Actual behavior:**
The following error message popped up:
```
Invalid session.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no idea at this point. I have joined servers that say they have mods but the game gives ZERO menu options to check mods added or the ability to remove them. I cant even filter out servers using mods to avoid them.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide client logs as describe in the issue form.

**Comment by D3nnis3n** [comment]
Closing due to no further necessary information provided.
