### ISSUE TITLE
Payment for titles

### ISSUE THREAD

**Issue by MisterrBrown** [StrangeLoopGames/EcoIssues#24658]
Mods:
DiscordLink
Road Objects 
EM Framework 
NidToolbox 
NidToolbox: Laws Module 

Titles created since the last update seems to not get recurring payments, we have titles created before the updates that are identical and gets their recurring payments 

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/96807882/61816252-7553-469d-9831-d8946ff0c76a)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/96807882/c3e386ff-bc44-43f4-884d-5bfe83058996)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
