### ISSUE TITLE
Chunks not loading or something

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2465]
I fell through the world a lot while here, but not all the time.  Also my computer froze, like hard restart frozen, and here I thought I was all done with that.
![image](https://user-images.githubusercontent.com/23460210/31206295-ccf542ce-a92b-11e7-92a6-63023422e0bf.png)

**Comment by Fank** [comment]
related or duplicate of #2319 ?

**Comment by MarjieAVolk** [comment]
Yeah think you're right, closing as duplicate
