### ISSUE TITLE
0.10.1.1 beta release-579 - New Loan Contracts Showing as Clauses fulfilled.

### ISSUE THREAD

**Issue by IronyTroll** [StrangeLoopGames/EcoIssues#24659]
![ERROR_ERROR](https://github.com/StrangeLoopGames/EcoIssues/assets/71368607/64a4d220-7d2d-487e-81a4-d1c73ab71043)

Unable to loan money via contracts.

Error message reads "Contract not accepted: All clauses are already fulfilled"

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/71368607/df6329a8-e92c-47f8-8bd4-726433e6e959)

Also Tested with basic 'put plant fibre in stockpile' contract. Passed. 

Tested with 1 AUR loan, with payment, to test fulfilled clauses, failed. 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/71368607/9ef5885e-5ffa-4cbb-b780-f3e3269be387)

**Comment by orborde** [comment]
If the contract creator unchecks "Auto-Accept", the bug doesn't trigger, and someone can accept the loan contract.

**Comment by D3nnis3n** [comment]
Already fixed in 10.1.5.
