### ISSUE TITLE
USER ISSUE: Asphalt Incline road white edge

### ISSUE THREAD

**Issue by panikchef** [StrangeLoopGames/EcoIssues#24651]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.0 beta release-576

**Steps to Reproduce:**
Go to place asphalt road inclne edge as image shows one line like edge rotate.

Go to place block and shows 2 edges that dont match up with white line rotate edge. 

Image of white ramp edge shows one edge, please fix.

**Expected behavior:**
Should have one edge for inclines to match with white line rotate edge

**Actual behavior:**
Shows 2 lines when placing down road incline.

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide a screenshot.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
