### ISSUE TITLE
USER ISSUE: BUG

### ISSUE THREAD

**Issue by HaroldBrad** [StrangeLoopGames/EcoIssues#24652]
\
**User Id: (slg240557)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Déco reco, ou serveur qui crash

**Expected behavior:**
Voir les joueurs et les objets

**Actual behavior:**
on ne voit pas les anciens joueurs de connectés mais les joueurs qui se connecte par après. et on ne voit aucun shop,objet ou autre sur la carte. la carte est toute plate 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Aucun mod installé sur mon Eco et sur le serveur.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24131
