### ISSUE TITLE
Barge and Tractor

### ISSUE THREAD

**Issue by Atroxkeep** [StrangeLoopGames/EcoIssues#24650]
![Barge issue](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/818f3e48-d97e-420c-9166-8c6bf48f8c39)
 
Eco version 10.1.0

With this new update my tractor is getting stuck as I drive it onto the barge. I tried once forward and once backwards and it gets stuck in the same spot each time. When its stuck I cant access the inventory directly through the tractor and it gives me me a pop up saying " can't interact with vehicle while navigating". When i attempt to move the vehicle using my hammer I get the green ghost image and i have enough calories to move it but when i right click nothing happens. The only way I can interact with the items inside the vehicle is to place a stock pile near the tractor and remove everything from the tractor by accessing it through the stockpile. The only was i was able to get it unstuck was removing everything from inside it and picking it up with the hammer. 

the barge and tractor were working fine in the previous patch. No mods on the server im playing on.
![Barge issue](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/a17a882c-534e-4e79-90c4-7678fe50ee4f)

**Comment by Quadbro** [comment]
Will be fixed in next update, thanks for report.

**Comment by D3nnis3n** [comment]
Fixed for 10.1.2.
