### ISSUE TITLE
USER ISSUE: Exception thrown

### ISSUE THREAD

**Issue by cybercronx** [StrangeLoopGames/EcoIssues#24656]
\
**User Id: (slg140458)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Just trying to log in to my SP world.

**Expected behavior:**
Load into world

**Actual behavior:**
[17] [Error] [Eco] Failed to start the server. Exception was Exception: MissingMethodException
Message:Attempted to access a missing method.
Source:System.Private.CoreLib

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes I do, but this update wouldnt effect these mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the full logfile and the savegame.

**Comment by cybercronx** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]Save game.zip<https://1drv.ms/u/c/e604470692197ce8/Ea54zrz0rZRLlOwfpnJyeV8BDh9AJHo8voqm9p9l1mysOw>

Here you go. Save game is a onedrive link since its to big.
________________________________

**Comment by D3nnis3n** [comment]
The savegame loads fine on a unmodded instance of Eco 10.1.1:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/ba314989-fd23-4f6a-975c-863b0bc9ef61)

Please make sure to remove the full Mods folder in /Steam/steamapps/common/Eco/Eco_Data/Server/ and then verify integrity via Steam to redownload the game's core files.
