### ISSUE TITLE
Settlement giving insane reputation amounts.

### ISSUE THREAD

**Issue by whompratt** [StrangeLoopGames/EcoIssues#24660]
# Summary
When the settlement in question gives a user reputation through laws, the reputation amount given is both extreme and seemingly random.

# Details
The settlement has a law that gives the Reputation Sender +1 rep when they give a citizen positive reputation.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2126241/0847f6c3-1012-440f-b501-564237207617)

Before patch 10.1 this worked as expected, however now it gives seemingly random amounts of reputation, with the value being ridiculously high or low.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2126241/54e42545-5278-4e58-b341-192e830b4800)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2126241/c076d6cc-b576-43d9-90ac-780e386bb49a)

**Comment by D3nnis3n** [comment]
Issue is not reproducible, can you provide the save game?

**Comment by whompratt** [comment]
> Issue is not reproducible, can you provide the save game?

I didn't take a manual save at the time this bug occured, and I do not own the server this issue occurred on.
I can ask if a backup around that time exists but I can't guarantee.
Would a backup of the save suffice?

**Comment by D3nnis3n** [comment]
I assumed this is happening frequently?

**Comment by D3nnis3n** [comment]
We were finally able to get this, it only seems to happen on migrated worlds. Should be fixed in 10.1.3.
