### ISSUE TITLE
USER ISSUE: I can't connect to any server

### ISSUE THREAD

**Issue by Beibarsov** [StrangeLoopGames/EcoIssues#24669]
\
**User Id: (slg201032)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Connect to any server	

**Expected behavior:**

**Actual behavior:**
Very long connect, after nothing

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Beibarsov** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14000445/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14000446/Player-prev.log)

**Comment by Beibarsov** [comment]
Is it stuck on around 24-26%. 
It was some kind of temporary problem. After about three hours, everything worked by itself.

**Comment by D3nnis3n** [comment]
Seems like a networking issue in that case, closing given there is no reproduction case.
