### ISSUE TITLE
USER ISSUE: some kind of elevator problem

### ISSUE THREAD

**Issue by CocoJambo23CZ** [StrangeLoopGames/EcoIssues#24667]
\
**User Id: (slg239804)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
cars bugging trough and elevator sometimes dissapear

**Expected behavior:**
both elevators

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![20240121051816_1](https://github.com/StrangeLoopGames/EcoIssues/assets/156304788/78bc3053-14aa-4e35-8926-4a49c404817f)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
