### ISSUE TITLE
Unauthorized User Able to pull claim papers

### ISSUE THREAD

**Issue by SCETheFuzz1** [StrangeLoopGames/EcoIssues#24668]
By default on the town foundation, all players have access to the claim paper spawn tab as the Everyone demographic is used.  This means that both citizens of the town and non-town members by default can come and take any number of claim stakes/claim papers out unless access is modified to restrict. If you restrict the authorization from everyone to just citizens, players can not join your town and town members are still able to pull out all available claim stakes/papers.  Removing access to all dose not allow anyone to leave town forcing them to use chat commands to leave, and unable to join town. 

The papers tab ( both spawned and claimed) should use deed access/owner demographic to protect the town resource ( claim papers ) by default.

**Comment by D3nnis3n** [comment]
Not reproducible, needs reproduction steps.

**Comment by SCETheFuzz1** [comment]
I'll grab a video as soon as possible.

**Comment by SCETheFuzz1** [comment]
Please see https://youtu.be/by4lq6EaPqc

**Comment by D3nnis3n** [comment]
But this works as intended - only on "Everyone" the claims are restricted to Mayor. It's what you should use.
The problem we cannot reproduce is that players cannot use the civics section when "everyone" is set, do you have a video of that?

**Comment by SCETheFuzz1** [comment]
It looks like all tabs follow the authorized tab, could the civics be changed/limited by an immigration policy?

**Comment by SCETheFuzz1** [comment]
All the ones I found reporting unable to access are because the town has changed the default from everyone to citizens only or mayor only to keep people from pulling papers out as I had shown.

**Comment by D3nnis3n** [comment]
Still persisting on 10.2? We never found the cause of this, but the permission system was refactored in that update.

**Comment by SCETheFuzz1** [comment]
I have not attempted to replicate the issue in 10.2 I'll give it a try
tonight. I do appreate the team following up on this though.

**Comment by SCETheFuzz1** [comment]
@D3nnis3n  looks like the permissions update fixed how I was able to do it prior.

**Comment by D3nnis3n** [comment]
Thanks for getting back and great to hear!
