### ISSUE TITLE
USER ISSUE: Homestead support papers

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24662]
\
**User Id: (slg232257)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Set a buy order in your own shop to buy those.

**Expected behavior:**
Everyone should be able to sell you those papers since on the paper on the buy order it says "no settlement needed".

**Actual behavior:**
You still need to select the settlement where they came from or the seller won't be able to sell it to you.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope, it's on Giant Panda. Thanks for your work, we really appreciate the updates :)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.
