### ISSUE TITLE
USER ISSUE: main menu not loading on steamdeck

### ISSUE THREAD

**Issue by RampagingFido** [StrangeLoopGames/EcoIssues#24663]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
launch game and wait forever for the menu to load

**Expected behavior:**
load menu so I can launch into a server.

**Actual behavior:**
background loads but the menu is absent

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed, tried to switch to proton experimental but no chanve. also tried deleting prlton files. was working on eco 10.0.3 but not working after update to10.1.1

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Steam Deck isn't supported - not seeing the main menu means that a connection to steam could not be established, which is typically a network issue.
