### ISSUE TITLE
USER ISSUE: Steam truck gets stuck on both barges

### ISSUE THREAD

**Issue by ShawnTheShadow** [StrangeLoopGames/EcoIssues#24675]
\
**User Id: (slg186919)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Drive industrial/wooden barge to dock
drop ramps
drive steam truck into ramp

**Expected behavior:**
Should be able to go on or off the barge

**Actual behavior:**
When driving onto the industrial barge, the steam truck stops on the ramp and cannot be moved, also shows the cannot interact while navigating
When trying to remove from the wooden barge the truck cannot be removed with the same message

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes i have mods installed, none that should effect it, but also happens when the mods are removed. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![20240121202005_1](https://github.com/StrangeLoopGames/EcoIssues/assets/22384794/57125478-c25d-4057-8b5c-0543fd211bbd)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14003983/Player.log)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.2.
