### ISSUE TITLE
USER ISSUE: spawn

### ISSUE THREAD

**Issue by chris77590** [StrangeLoopGames/EcoIssues#24678]
\
**User Id: (slg219056)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
spawn invisible sur toutes mes maps créés

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide your logfiles as described in the issue form :)

**Comment by chris77590** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14074188/Player.log)


[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14074193/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed in 10.0.4.
