### ISSUE TITLE
USER ISSUE: Glowing Pink Rice

### ISSUE THREAD

**Issue by Chasedoesstuff** [StrangeLoopGames/EcoIssues#24676]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
1. Eat Boiled Grains

**Expected behavior:**
A texture of the falling grains

**Actual behavior:**
Shows glowing pink grain particles instead of the intended grain texture.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14005504/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14005506/Player-prev.log)

Video of Issue: (quality lowered so I can upload it to GitHub)
https://github.com/StrangeLoopGames/EcoIssues/assets/101988897/2e5766b8-42c7-4e95-98a2-26d82e0ddbdf

**Comment by D3nnis3n** [comment]
Fixed in 10.1.2.
