### ISSUE TITLE
USER ISSUE: Lagging When Moving

### ISSUE THREAD

**Issue by Smugllar** [StrangeLoopGames/EcoIssues#24679]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
1. Move around

**Expected behavior:**
Moving around the map with good FPS at high GPU utilization

**Actual behavior:**
Low fps (about 20) and GPU utilization at about 40% when moving. High fps (120+) and high GPU utilization at about 90% when stationary

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14015813/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14015815/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)
