### ISSUE TITLE
USER ISSUE: Game is in Frenglish (mixed french and english)

### ISSUE THREAD

**Issue by Dani1973** [StrangeLoopGames/EcoIssues#24677]
\
**User Id: (******)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
Set you game in english and join a french server

**Expected behavior:**
My game is supposed to be in total english like all other games I have played before do work (biggest example world of warcraft or any big title)

**Actual behavior:**
Some parts are in english and some in french

**Do you have mods installed? Does the issue happen when no mods are installed?:**
the server has mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That works as developed, the server has its own language settings and anything served by the server will be in the server language.
