### ISSUE TITLE
[10.1.1][Standalone Eco Client] Graphical glitches on certain UI elements.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24670]
- **This only happens on standalone Eco client downloaded from play.eco website!** 
- There's no glitch on Steam version. 
- Tested on 2 diffrent PCs.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/14f617a3-95c6-48bf-9b96-0f8a6ba120a1)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/b41ce98f-03c0-476b-934d-d575d2c0192a)

- Happens also on fresh world,
- no mods installed,
- visible right after login on the text of News Feed and some buttons like Enact Law button inside Court.

https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/18ffb11d-48c2-4ba2-be68-66bb6dc2ec26

**Comment by TwixterZ** [comment]
Hi @padmanek , I have checked this issue locally using build downloaded directly in ECO website but not getting the same result as you have here, may I know if this issue still persist for you?

**Comment by padmanek** [comment]
yes and I know what is causing it, it's Eco's UI. See my explaination video:

https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/b7c1445f-ccb0-4855-9ca2-9bff80462740

**Comment by padmanek** [comment]
It also happens on Steam version btw and sometimes either of the globes doesn't immediately show up.
Sometimes you have to ESC to see the settings menu globe and then it shows up. Sometimes the globe on the right side shows only after relog. Somtimes it's there from first login.

**Comment by TwixterZ** [comment]
@padmanek there was a possible fix added for this issue into 0.10.2, are you still having it?

**Comment by padmanek** [comment]
yes, the issue is still there and all my players can see it eventually
The problem is reproducing it. The issue **doesnt always appear immediately.** It sometimes takes a few minutes of running around to make it appear. Sometimes one of the 2 "globes" immedaitely. Skip to 0:45 to avoid loading screen.


https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/cb89058f-5c90-40c4-931b-191ad1c1f465



![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/0e6eef6c-8215-473e-9b6e-7ba70e66aa3b)

**Comment by padmanek** [comment]
Here at it takes 3min40s since login for the first "globe" to appear https://www.youtube.com/watch?v=pBsZ6ZWdI20

**Comment by padmanek** [comment]
Is it visible in Unity Editor? Yes. 
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/6a5912cb-3722-44fa-ac55-6a514707b03a)

**Comment by TwixterZ** [comment]
@padmanek does this issue happens on a vanilla setup? or only on a modded server?

**Comment by padmanek** [comment]
As we spoke on Discord in PMs, the bug is caused by spawning and placing down an object that doesn't have a model so the default white box appears. 
So, yes you can technically do it on an unmodded vanilla server. Just do` /give culture` and place it down. 
The bug appears right away.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/f258e1e1-347c-4879-bcf1-6293b8656d36)

That being said, you can likely close the ticket.

**Comment by TwixterZ** [comment]
Hi @padmanek, as discussed, I will proceed to close this issue as you have mentioned in your command. 

Thank you for the assist! =)
