### ISSUE TITLE
USER ISSUE: fall underground

### ISSUE THREAD

**Issue by Katepompom** [StrangeLoopGames/EcoIssues#24674]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
1. Place wood on pile
2. Got stuck in the pile of wood
3. Fall underground

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24352
