### ISSUE TITLE
contracts crash

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2467]
Game crashed with an error about economy. Removed the economy folder from game.eco, the server started but players that were close to a Contract Board got a error (see 1.png) then i removed the contract board from world objects folder and the server is running fine now.
here you find the dump file creaded with the crash, the game.eco and a image of the second error
https://www.dropbox.com/s/p3ggqh9qremzav6/error%20GreenLeaf.rar?dl=0

**Comment by johnkslg** [comment]
Fixed in latest
