### ISSUE TITLE
USER ISSUE: не может соеденится с серфисами

### ISSUE THREAD

**Issue by leon1980051** [StrangeLoopGames/EcoIssues#24689]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Empty bug report, closing. Please provide at least the minimum required information.
