### ISSUE TITLE
Labor contract issue with multiple queued items in sawmill

### ISSUE THREAD

**Issue by Atroxkeep** [StrangeLoopGames/EcoIssues#24682]
![Contract bug 1](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/4d276887-fca2-4a83-baad-4e88197f6316)
![Contract bug 2](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/3c55f0c9-43ab-41ef-b7e2-849516ec1e94)
![Contract bug 3](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/bae5cea0-c4c2-4c62-884d-0305c5016add)
![Contract bug 4](https://github.com/StrangeLoopGames/EcoIssues/assets/157091019/6b1ec5f7-08ac-449c-8e1d-72c78902bd22)

Hello, 

I noticed someone on the server i play on was having issues with adding labor to a sawmill so i went to have a look and give them a hand. In our town we have a sawmill with two large projects queued up ( particle boards and saw boards). The particle boards is before the saw boards in the sawmill. Both projects still require labor. A contract was made to add labor to the Saw boards project, only one member has selected it so far and they have managed to put some labor into Saw boards project in the sawmill (Shift + right click and Alt + right click), But we noticed that he could only add labor when the owner was online and when the owner is offline he cant add labor. When he tried to add labor when the owner is off line, It says you are not authorized to do that. Now that we are looking more closely at it we noticed it says add labor for the particle board project instead of the saw board project. There is only one contract and its for saw boards not particle boards and we don't have access to the machine other then adding labor.

We got the owner to move the saw boards project in front of the particle boards project in the table and it looks like the original person who accepted the contract can finally put more labor in when the owner of the sawmill is offline. 

No mods on server

**Comment by D3nnis3n** [comment]
Do you have a savegame of this state or any reproduction steps?

**Comment by Atroxkeep** [comment]
Hello,

The server owner provided me with the save game file.

Currently the Sawmill and contract are still in game but the owner of the
saw mill has moved the Saw boards to the top of the queue and particle
boards is on the bottom.

Munroe
 Game-2024-01-23-17.22.10.zip
<https://drive.google.com/file/d/1GYLeY5FKJfSCXp0q-Tv0zjD2HCcqXd4i/view?usp=drive_web>
