### ISSUE TITLE
USER ISSUE: Menu

### ISSUE THREAD

**Issue by whyfuu** [StrangeLoopGames/EcoIssues#24685]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Launch game

**Expected behavior:**
Click continue

**Actual behavior:**
Stare at background image while the Menu isn't showing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com.
