### ISSUE TITLE
A connection to our internal servers could not be established.

### ISSUE THREAD

**Issue by Cerber424** [StrangeLoopGames/EcoIssues#24687]
ABOUT
A connection to our internal servers could not be established.
If this problem persists after restarting the game, our services may
be interrupted. Please check https://status.play.eco/ if this is the case and if so,
any news can be found in our Discord: https://discord.gg/eco.
If our status page indicates that our services are working correctly, please contact
to our support team at supportestrangeloopgames.com so we can help
to you with diagnostics and solution to the problem.
FINE
RG
![Uploading 20240125110825_1.jpg…]()

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com.
