### ISSUE TITLE
Client can't login near deep mine

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2468]
In the PAX cowboy server Near 600, 180 there is a deep mine, approaching it throws this exception. World loading never finishes if you try to login in the area. 

NullReferenceException: Object reference not set to an instance of an object
ChunkRenderer+CombinedChunkGroup.Combine (ShadowCastingMode shadowCastMode) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:438)
ChunkRenderer.UpdateChunkCombos (.ChunkRender chunk, UnityEngine.Material mat, System.Collections.Generic.List`1 meshes, Int32 layer, ShadowCastingMode shadowCastMode) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:579)
ChunkRenderer.ApplyBuiltMesh () (at Assets/VoxelEngine/Core/ChunkRenderer.cs:780)
ChunkRenderer+ChunkJobQueue.ProcessFinishedJob (.ChunkRenderer job) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:336)
StaticChunkUpdate.Update () (at Assets/VoxelEngine/Core/StaticChunkUpdate.cs:73)

There are a bunch of weird things going on underground.

![image](https://user-images.githubusercontent.com/774628/31247483-9a0486a0-a9c5-11e7-8730-3646630d2067.png)

**Comment by SeanAtr0n** [comment]
Also something else near this area causes Unity's memory to spike to over 10gb in a few seconds

**Comment by Fank** [comment]
I got reports of my players too, It looks like an issue with holes in mountains, doesn't matter which height.
Maybe @Frozen-Byte can contribute information about it too?!

Savegame: ftp://eco.fankserver.com/Game-2468.eco
Will provide location if i'm home

**Comment by metachronism** [comment]
fixed in 6.0.1
