### ISSUE TITLE
USER ISSUE: Impossible retirer objet posé

### ISSUE THREAD

**Issue by Shasarel14** [StrangeLoopGames/EcoIssues#24684]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Poser une grue
Retirer la grue avec marteau

**Expected behavior:**
l'objet revient dans l'inventaire

**Actual behavior:**
l'objet reste en place

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non et oui

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14028981/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14028982/Player-prev.log)

**Comment by Shasarel14** [comment]
I can add too if you try to use the crane, the game crash !
What can i do? is there some admin command i can try on it ?

**Comment by Shasarel14** [comment]
i have to precise that it's not me who put the crane in game. I'm just another player and admin of the game.. but my interactions are the same as him

**Comment by D3nnis3n** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/24642
