### ISSUE TITLE
[0.10.1.2 beta release-584] Unexpected water-flow behavior during worldgen (under-documented worldgen params?)

### ISSUE THREAD

**Issue by shardwolfdotnet** [StrangeLoopGames/EcoIssues#24688]
I'm selfhosting a server where we're trying to generate a "archipelago"-style map (i.e. multiple smaller islands/continents) to emphasize the use of boats added in Update 10.

To do this, we've tuned the `NumContinentsRange` and `NumSmallIslandsRange` to increase the number of continents/islands (6-8 continents, 8-16 small islands). Terrain-editor preview suggests a reasonably-distributed set of islands, with some mountain lakes/rivers as one might expect:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/76196468/db685849-31d5-402a-ab2c-81e76639d701)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/76196468/3c2ef821-05a6-4d43-b52d-ffdc03f824b6)

However, after worldgen occurs, these rivers/lakes are either empty or mostly-empty (closeup on the continent in the lower right):
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/76196468/5c8641fd-82de-43b2-a230-aba16b5da887)

Experimenting with the values of `MaxElevationOceanDistance` and `ElevationPower` appears to have some effect on water distribution, but:
* The functionality of these parameters is not well-documented (past inline descriptions in the dedicated server) - [the wiki](https://wiki.play.eco/en/Server_Configuration#WorldGenerator.eco) lists these as "Unknown".
* The effect of the Autoscale settings (also undocumented on the page above) against an inherently exponential-scale parameter are are unknown
* It's not clear what expected behavior is even supposed to _be_ here: naively speaking, seeing rivers in the biome/terrain map but said rivers then lacking water post-generation feels like a bug.
* Inability to view the effect of these settings in the terrain editor means deleting the world/waiting for world-gen (~10m interval per iteration), which complicates ad-hoc testing

**Comment by D3nnis3n** [comment]
The world generator is a very complex system with a multitude of settings that haven't been fully implemented, aren't functioning correctly and / or are unused or working only in our default parameters - when experimenting with those more obscure settings, admins do so on their own risk - we don't offer support for that. I'm hence closing this report, as we are not working on the World Generator aside of actual bugs with the common settings for the forseeable future.

Please note that the wiki while hosted by us, is a community wiki. The information there is provided by other players and can be edited by anyone - we don't manage the wiki nor do we maintain it.
