### ISSUE TITLE
USER ISSUE: Probleme constitution

### ISSUE THREAD

**Issue by Toms0666** [StrangeLoopGames/EcoIssues#24698]
\
**User Id: (slg181232)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
je veut ouvrire la constitution

**Expected behavior:**
editer la constitution

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60,00%>Exception: ArgumentException
Message:Object of type 'Eco.Gameplay.Civics.GameValues.GamePickerList' cannot be converted to type 'Eco.Gameplay.Civics.GameValues.GamePickerListAlias'.
Source:System.Private.CoreLib

System.ArgumentException: Object of type 'Eco.Gameplay.Civics.GameValues.GamePickerList' cannot be converted to type 'Eco.Gameplay.Civics.GameValues.GamePickerListAlias'.
   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.Run</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please attach the full logfile of the crash on server side and note on if this is with settlements on or off.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/24709 - please provide the information there.
