### ISSUE TITLE
USER ISSUE: [Eco 10.1.2] bug: Composite Bow (and modern tools) steel repair cost

### ISSUE THREAD

**Issue by Cayune** [StrangeLoopGames/EcoIssues#24699]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
1. Acquire a Composite bow (or any modern tool: Axe, Hammer, Hoe, Pickaxe, Scythe, Shovel, or Machete)

2. Fully break tool (0 durability remaining)

3. Tool repair cost for above tools are all 15 Steel Bars at 0 Durability

**Expected behavior:**
It should have a repair cost based on the materials to craft it for the Bow and the modern tools might not be intended to be 100% of the steel crafting cost.

**Actual behavior:**
They all require 15 Steel Bars to repair, which might be intended for Modern Tools (which is 15 to craft and thusly 100% of that input to repair). Unclear if it is intended to be 100% of the steel input (all are 10 Fiberglass and 15 Steel to craft) and figured I'd include to confirm.

However the ***Composite Bow*** doesn't use Steel at all in crafting it and instead should cost Fiberglass (to be in line with the other bows that repair with the non-string material) or Nylon Thread (to be in line with the modern tools that use the non fiberglass part)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Comment by D3nnis3n** [comment]
This works as intended.
