### ISSUE TITLE
[10.1.2] Revoke Citizenship Server Crash on next Civics Tick

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24697]
![image3](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/dfbc38bd-94c9-4f18-b108-e4a26f078a4f)

What the mayor did:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/4126cd34-2358-437b-a308-b11363d6f670)

server log: 
[log_240126060036.log](https://github.com/StrangeLoopGames/EcoIssues/files/14069500/log_240126060036.log)

Also, after server booted **almost all Federation claims were returned to the President the Federation**. Even from owners completely unrelated to the town that was dissolved.

Our Federation immigration policy settings:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/ce6d78c9-b23d-4a7d-9d77-e3099e8b5011)

**Comment by D3nnis3n** [comment]
Can you attach a savegame prior to this happening with exact reproduction steps on what needs to be done to achieve this outcome?

**Comment by padmanek** [comment]
unfortunately can't since the backup from that day was deleted, closing for now
