### ISSUE TITLE
USER ISSUE: transport  bac inéfficasse

### ISSUE THREAD

**Issue by Toms0666** [StrangeLoopGames/EcoIssues#24694]
\
**User Id: (slg181232)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
les chariot reste pas sur le bac et finisse dans l'eau

**Expected behavior:**
que les chariot a moteur puisse rester sur le bateaux

**Actual behavior:**
les véhicule finisse dans l'eau au bout de 2 minute et ne reste pas sur le bateau

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not reproducible, needs reproduction steps.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
