### ISSUE TITLE
Water is behaving wierd

### ISSUE THREAD

**Issue by Kuroooooooooooooooooooo** [StrangeLoopGames/EcoIssues#24707]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Worked on a ship port, taking away and adding sand etc and building docks. 

**Expected behavior:**
Water levels itself back out

**Actual behavior:**
Water seems to get pushed away from the docks and the new shore and cant refill spaces properly.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods at all

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Eco doesn't have water physics currently, so removed blocks will not fill up. That is not a bug.
You can try to work around it by using aqueducts.
