### ISSUE TITLE
USER ISSUE: Login fehler

### ISSUE THREAD

**Issue by Purzely** [StrangeLoopGames/EcoIssues#24702]
\
**User Id: (slg235023)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**

**Expected behavior:**
spiel sollte starten

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
ich versuche auf den Server Brachstadt zu gelangen und bei !Welt laden! kommt die Fehlermeldung, habe aber da schon gespielt stundenweise

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24380

We did notice that most of these reports were from Brachstadt, wondering if that server is modded / has anything else that is special. Please feel free to add any info on that in here or the issue linked above.

**Comment by Purzely** [comment]
Ja auf Brachstadt gibt es Mods

**Comment by Purzely** [comment]
[FEhler Eco1.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14075482/FEhler.Eco1.txt)
