### ISSUE TITLE
USER ISSUE: Main menu doesnt load

### ISSUE THREAD

**Issue by bar5098** [StrangeLoopGames/EcoIssues#24708]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Launch game

**Expected behavior:**
Main menu

**Actual behavior:**
Background theme without menu

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and I tried reinstalling the game, update the drivers, etc... nothing change
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14076471/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14076472/Player-prev.log)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by xNccPlay** [comment]
I have the same behavior. I also tried to reinstall the game. I have no mods installed.

**Comment by D3nnis3n** [comment]
Were you able to see it before? What changed between, if so?

**Comment by D3nnis3n** [comment]
Can you try to open the program run, enter "%UserProfile%\AppData\LocalLow\Strange Loop Games\Eco" and in that folder delete player.eco? Does that help?

**Comment by bar5098** [comment]
it works, thx, but I lost my solo world

**Comment by bar5098** [comment]
Ok so now I can't create a new world, the game dosnt display any spawn point.
If I put back the player.eco, main menu dosnt show up anymore.
I've tried reinstalling the game.
So HOW can I have a clean configuration please ?

**Comment by D3nnis3n** [comment]
The reason for this problem is likely that the save file the "Continue" button refering to a save file that does no longer exist.

If the game doesn't show a spawn point, select the cogwheel in the map settings top right and enable "Spawn" in the world layers.

**Comment by bar5098** [comment]
Oh ok its all good now, thank you very much for your prompt replies
