### ISSUE TITLE
Printing press missing Credits tab

### ISSUE THREAD

**Issue by Borimino** [StrangeLoopGames/EcoIssues#24703]
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
Place a Printing Press
Open the UI
Look for the Credits tab

**Expected behavior:**
Being able to rent out the functionality of the Printing Press via the Credits tab

**Actual behavior:**
Only able to either let people have free access to Printing Press or not let people have access at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Comment by D3nnis3n** [comment]
As with other tables, the Printing Press as a special table does not have a credit tab, that is not a bug.
I have added a internal suggestion for this instead.
