### ISSUE TITLE
USER ISSUE: Sand texture looks wrong (like water)

### ISSUE THREAD

**Issue by Larslol140** [StrangeLoopGames/EcoIssues#24706]
\
**User Id: (slg136695)**
**Version:** 0.10.1.2 beta release-584

**Steps to Reproduce:**
1. Pick up or dig sand 
2. Hold a shovel

**Expected behavior:**
Sand should have the normal sand texture

**Actual behavior:**
Sand looks like it has water on it. The texture seems wrong.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14075890/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14075891/Player-prev.log)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25729499/bdb88c86-e044-47b7-a228-be2fa599ef47)

**Comment by D3nnis3n** [comment]
Not reproducible - is there any additional steps to get this?

**Comment by Larslol140** [comment]
The issue started occurring when the oil pump and refinery was built near water (including generator, pump and pipes)  and the server has settlements turned off.

**Comment by padmanek** [comment]
had it happen on my server too, unable to repoduce on demand tho

**Comment by padmanek** [comment]
https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/4b1308cb-c8aa-492f-8fbc-1fa471934bba

It happens always. Just emptied entire Mods folder except __core__ to be sure and it still happens without mods.

save file: https://drive.google.com/file/d/1emmPe3bsev8l8RBc-_HHXg8FQaslpS93/view?usp=sharing

graphics settings:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/1054a11c-094a-4236-be09-bee9433cc852)

**Comment by D3nnis3n** [comment]
The save is not necessary here, given that is a graphics issue. I have asked the art team to look into it, given I can't get it.

**Comment by D3nnis3n** [comment]
Art has found a potential cause that will be addressed in 10.1.4.
