### ISSUE TITLE
USER ISSUE: Metalic sand

### ISSUE THREAD

**Issue by Kanra2123** [StrangeLoopGames/EcoIssues#24717]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
1. Take sand on wooden shovel

Graphic settings:
VSync: off
Shadow quality: Good
lvl of details: 160%
Render scale: 60%
Brightness: 166%
GPU memory limit: 9,7
Antialiasing: FXAA
Volumetric lighting: medium
Bloom: Medium
Ambient occlusion: omGlas refraction: off
Reflections: on

**Expected behavior:**
sand look like a sand

**Actual behavior:**
sand look like metalic sand (has sand colour and shape, but is like somebody change roughness [smoothness map] to ultra smo
![Metalic sand 1](https://github.com/StrangeLoopGames/EcoIssues/assets/73336272/3bd77fc0-2c91-4e5a-b2a0-9dcf293b640d)
![Metalic sand 2](https://github.com/StrangeLoopGames/EcoIssues/assets/73336272/5c2f595c-78c0-4230-8a67-203e104d32c6)
oth)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have mods. Server that i am on have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14118254/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14118255/Player-prev.log)

**Comment by D3nnis3n** [comment]
Already fixed in 10.1.4.
