### ISSUE TITLE
[0.10.1.3] Claim filter inverted when claiming for recreated town via map

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#24712]
As you can see in the image, I'm putting down a town foundation and attempting to claim via the map, but I'm only allowed to claim in other towns. Not inside of my new town and not outside any town. Claiming works fine when using the claim tool.

STR:
1. Load the server from here: https://drive.google.com/file/d/1pkIaJiltJDc3gCr_-m0Oc3WpQdtiHpBq/view?usp=sharing
2. Teleport to (840,400)
3. Invalidate the town building (Remove the door or similar)
4. Wait for the timout via/ff
5. When the timeout has occurred and the town and country has been destroyed, attempt to place a new town foundation in the same place as the previous one (I also used the same name if that matters)
6 Open the deed for editing
7. Notice that you are only allowed to claim in the influence range of other towns.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/11805935/394276f0-fd5e-4529-a7e3-ba01e279bc92)

**Comment by MonzUn** [comment]
Same thing does not happen for countries it seems.
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/11805935/30e13aef-bd7d-4ba4-b002-1e3ca8196bd5)

**Comment by padmanek** [comment]
Same happens for Federation. Been a problem since 10.1

**Comment by D3nnis3n** [comment]
Fixed in 10.1.4.
