### ISSUE TITLE
[0.10.1.3] Bank accounts duplicate contents upon being destroyed by town invalidation

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#24713]
STR: 
1. Load the server from here: https://drive.google.com/file/d/1pkIaJiltJDc3gCr_-m0Oc3WpQdtiHpBq/view?usp=sharing
2. Check the contents of account "Monz & Kim" and note the users to be Monzun and Kimmissar.
3. Teleport to (840,400)
4. Invalidate the town building (Remove the door or similar)
5. Wait for the timout via/ff
6. Check personal accounts of the previous account users and find that both have the full content of the destroyed bank account and that the contents thereby have been duplicated.

Complete minting record
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/11805935/8eb700c5-01ab-43ea-b078-b359d9ac43a3)

Curreny report (Note that any curreny that was held in the "Monz & Kim" now has the wrong number in circulation comapred to how much was minted)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/11805935/591339bf-423a-42fa-8b67-dc485b3f6686)

**Comment by D3nnis3n** [comment]
Fixed in playtest.
