### ISSUE TITLE
Server Issue: Meteor Hours changes with commands does not persist after server restart

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#24711]
Version: 10.1.2

Behaviour:
We use the /meteor removehours 48  ( or /meteor addhours -48 ) to reduce the meteor timer by two days.
After a server restart, the timer goes back to original time.

Expected Behaviour: Meteor timer should not be reset after a server restart.

Steps to Reproduce:
Start a new server, launch command  /meteor removehours 48
restart the server
the meteor timer will still be 30 days

Note:
We can, only sometimes, not sure how it works, still reduce meteor timer by reducing the MeteorImpactDays in Disasters.eco

**Comment by D3nnis3n** [comment]
This works as intended. To change the timer permanently it is necessary to change the "MeteorImpactDays" in Disasters.eco, which only supports full days. The command is only supposed to be used for QA purposes and can be used for "last minute" extensions that aren't supported via the config. I'm not able to find any issue with the config setting, it adjusts the meteor time correctly in all cases. Please open a new issue if you have a reproducible case where that doesn't work.
