### ISSUE TITLE
USER ISSUE: cant connect to any server

### ISSUE THREAD

**Issue by Tollwutmolle** [StrangeLoopGames/EcoIssues#24719]
\
**User Id: (slg166425)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Join a Server, it download all, world and mods,
then load the world, and stop at 100%, after a few seconds
"Server not responding"  and its on all server

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Server not responding

**Comment by D3nnis3n** [comment]
You already had an issue reported for this and it was attributed to mobile internet here: https://github.com/StrangeLoopGames/EcoIssues/issues/24331

As noted there, this is not caused by us, but your internet situation.
