### ISSUE TITLE
USER ISSUE: Constitution is changing itself

### ISSUE THREAD

**Issue by VseOdbornik** [StrangeLoopGames/EcoIssues#24722]
\
**User Id: (slg153495)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
I was messing with my board of elections that broke my elected title election process, so I changed that and the constitution changed.

**Expected behavior:**
Not changing the constitution

**Actual behavior:**
Changes the constitution to the default state that gives everybody voting rights, which is really slow and hard to fix, especially if you need the 10 % of voters to vote with like 100+ citizens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended. If a title mentioned in the constitution is broken and it is no longer possible to make changes due to that, the constitution will reset itself to fix the problem.
