### ISSUE TITLE
USER ISSUE: Unoccupied vehicles/carts jumping to surface when underground

### ISSUE THREAD

**Issue by IneaFaedyn** [StrangeLoopGames/EcoIssues#24724]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Frequently, leaving a vehicle like the powered cart, or just normal wood carts, on an underground tunnel ramp while mining in the nearby surrounding rocks causes the vehicle to jump up to the surface.Breaking the rock seems to cause some kind of physics issue.I've seen similar problems with rocks randomly disappearing, but then later finding them scattered around on the surface.

**Expected behavior:**
The vehicles should be able to exist underground and on ramps without glitching to the surface level.

**Actual behavior:**
Jumps through the ceiling to the surface level.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14141540/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14141541/Player-prev.log)

**Comment by IneaFaedyn** [comment]
It's not reliably reproducible, I'm guessing it's something physics related so there might be specific conditions needed, but I think the effect of the vehicle "jumping" is more common than it jumping and also appearing on the surface. Sometimes it just jumps and lands back on the ramp.

I can try to get a video if I notice it happening.

**Comment by D3nnis3n** [comment]
Thanks for the report. This issue is already reported internally.
