### ISSUE TITLE
USER ISSUE: Land Massinteract does not work

### ISSUE THREAD

**Issue by jacob28348** [StrangeLoopGames/EcoIssues#24733]
\
**User Id: (slg236027)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
type /land massinteract with any tool in your hand.

**Expected behavior:**
Tool will be used

**Actual behavior:**
Tool is not used. Nothing happens.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14155415/Player.log)

**Comment by D3nnis3n** [comment]
This is a development command not intended for use for administrators.
Such commands only get updated as we need them for QA.
