### ISSUE TITLE
USER ISSUE: Too few Barrels produced by Plastic recipe

### ISSUE THREAD

**Issue by steellynx** [StrangeLoopGames/EcoIssues#24738]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
1. Setup Oil Refinery with Modern Upgrade 2 (25% reduction)
2. Add 3 Petroleum to attached storage
3. Craft 1 Plastic

**Expected behavior:**
3 Barrels should be crafted according to the recipe information in-game

**Actual behavior:**
Only 2 Barrels are crafted

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes: Polychrome. This has not been tested without the mod (not my server)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended, there is a 25% loss of barrels in crafting, which will be rounded.
The preview display may not correctly take into account this rounding, which is a known issue already reported elsewhere.
