### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by leon1980051** [StrangeLoopGames/EcoIssues#24735]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
connection to backnd servers couldn t bi established

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by leon1980051** [comment]
![Снимок экрана (3)](https://github.com/StrangeLoopGames/EcoIssues/assets/157700597/ee038b16-3d08-4b74-85c4-e58665569897)

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com.
