### ISSUE TITLE
USER ISSUE: Water Bug

### ISSUE THREAD

**Issue by benny4444** [StrangeLoopGames/EcoIssues#24731]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Run pipe to anywhere  from a pumped source that is at least one block above ground. 

**Expected behavior:**
Water gushed from pipe creating "pond". Cutting off water source should clear water point created.

**Actual behavior:**
Cutting off water source does not remove water point created. And there appears to be no way to get rid of it.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by benny4444** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14155366/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14155367/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.4.
