### ISSUE TITLE
Big chunk of chadded dirt on placing wood

### ISSUE THREAD

**Issue by Timmay24** [StrangeLoopGames/EcoIssues#2473]
Well. How shall I say...

![2017-10-06](https://user-images.githubusercontent.com/5476826/31273878-de08bbd4-aa90-11e7-8656-1d6838ca52c0.png)
You see this castle of dirt?

First I tried building some sort of tower of stockpiles.
After nearly finishing stockpile 5 in the height of a little above 100, logs seemed to turn in to dirt chunks.

![2017-10-06 1](https://user-images.githubusercontent.com/5476826/31273950-2cd05bd2-aa91-11e7-8a61-df9f1397c0fa.png)
When ever I placed a log...

![2017-10-06 2](https://user-images.githubusercontent.com/5476826/31273971-394b1fd2-aa91-11e7-9a15-95af381bd1f1.png)
...it turned into a big chunk of dirt with some notches.

I'll let it check again by @Fank and after that we can upload the current save file.

**Comment by Fank** [comment]
As requested savegame: ftp://eco.fankserver.com/Game-2473.eco

**Comment by Timmay24** [comment]
Additional glitches (leads into app hang when approaching):
![2017-10-06 3](https://user-images.githubusercontent.com/5476826/31280497-cfea0f46-aaac-11e7-9cf5-c61ce1f51b29.png)
![2017-10-06 4](https://user-images.githubusercontent.com/5476826/31280499-d1868f3c-aaac-11e7-8bde-a77df3368102.png)

**Comment by Frozen-byte** [comment]
(c) Frozen_byte's 3d Storage.

**Comment by Fank** [comment]
Maybe related to #2468

**Comment by Timmay24** [comment]
@Frozen-byte yes. no copyright infringement intended. ;)

**Comment by Fank** [comment]
@MarjieAVolk Critical recommended ;)

https://loli.temel.me/5n2suMmao4nntb4PnlrDGNhyT3enK7Ey.mp4

**Comment by Timmay24** [comment]
...glorious

**Comment by metachronism** [comment]
fixed for 6.0.1
