### ISSUE TITLE
USER ISSUE: не конектится

### ISSUE THREAD

**Issue by leon1980051** [StrangeLoopGames/EcoIssues#24734]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
не подключается к сервисам.меню нету

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com.
