### ISSUE TITLE
USER ISSUE: New to Eco but cant play

### ISSUE THREAD

**Issue by Christopher9335** [StrangeLoopGames/EcoIssues#24745]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
I am new to eco but I logged in to join my solo server and it said something about "A crash has happened and you can't play" so I restart my computer and steam but when I got on eco the menu options are all gone it doesn't have new game or load game or anything else... so I uninstalled the game and that didn't work either so idk what to do and I Don't use mods or anything... thanks for your time.  

**Expected behavior:**
should have seen menu options. 

**Actual behavior:**
got no menu options. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, and yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14182795/Player.log)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14182798/Player-prev.log)

**Comment by D3nnis3n** [comment]
Open "run" via system search, enter "%UserProfile%\AppData\LocalLow\Strange Loop Games\Eco" and delete player.eco file there. To investigate the issue with the server please reach out to support@strangeloopgames.com.
