### ISSUE TITLE
USER ISSUE: Sunk/Capsized Boat Bug

### ISSUE THREAD

**Issue by benny4444** [StrangeLoopGames/EcoIssues#24743]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Boats will capsize or spawn underwater/under docks. It is hard to reproduce because it happens randomly. It does occur when either leaving a server then returning or staying logged in for x amount of hours without actually playing, but not every time.

**Expected behavior:**
Boats should not randimly capsize or sink regardless of either leaving game and returning, or just staying in game without playing for any amount of time.

**Actual behavior:**
Randomly will be capsized or underwater/under docks etc.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by benny4444** [comment]
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14169224/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14169225/Player-prev.log)

**Comment by D3nnis3n** [comment]
This issue is not reproducible and was made for version 10.1.3, with 10.1.4 containing multiple fixes for boats.
I'm hence closing this issue - please feel free to reopen it if you still see the behaviour, but we'd need a reproduction case to investigate it.
