### ISSUE TITLE
USER ISSUE: fell through floor now stuck

### ISSUE THREAD

**Issue by Taylorious69** [StrangeLoopGames/EcoIssues#24744]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use /unstuck to unstuck yourself. Report not containing any useful info, hence closing.

**Comment by Taylorious69** [comment]
Sorry I didn't know how to use the GitHub side of things as was first time. It's ok I just restarted but know for next time thanks. Just started playing Eco and trying to work it all out
