### ISSUE TITLE
[10.1.3] moving placed item blocking themselves

### ISSUE THREAD

**Issue by GitKagu** [StrangeLoopGames/EcoIssues#24741]
Hi,

Moving an already placed item isn't possible if part of the place is used by the selected item.
I can move a stockpile 2 blocks on a side, i need to move it far away to replace it where i want because it see itself as un obstacle.

![20240204222835_1](https://github.com/StrangeLoopGames/EcoIssues/assets/158855811/211a43d3-3b53-4bf8-8e24-4ad7e92f5a2f)
![20240204222951_1](https://github.com/StrangeLoopGames/EcoIssues/assets/158855811/d6b90403-aeea-48bf-a299-910543b776d0)

Items should be movable without their own space

**Comment by D3nnis3n** [comment]
This works correctly, I made a internal suggestion for this instead.
