### ISSUE TITLE
USER ISSUE: Version Mismatch when there shouldn't be.

### ISSUE THREAD

**Issue by Shadow-Dracul** [StrangeLoopGames/EcoIssues#24747]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.1 beta release-579

**Steps to Reproduce:**
click continue while having your version and the server version different to the current version

**Expected behavior:**
The server version is actually set to 0.10.1.1 so The expected behavior was for it to default to the servers actual version/ the users version so that the error does not occur

**Actual behavior:**
The following error message popped up:
```
Version mismatched.
User version: 0.10.1.1 beta release-579
Server version: 0.10.1.3 beta release-592

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Shadow-Dracul** [comment]
Unfortunately to fix the issue you must load the current version up and run the continue until it prompts you to join the actual server at which point you have to go back to the older version to join (so 2 downloads every time this error occurs)

**Comment by D3nnis3n** [comment]
Under which circumstances does this appear? A server should _never_ revert a version. It seems this issue only appears when the server was played on on a newer version than went back to an older one. If that is the case, this would be a won't fix. Can you describe how to get the problem?

**Comment by Shadow-Dracul** [comment]
It is likely that it is a server hosting issue as the server was crashing a few times throughout the playthrough. But as I said I loaded the game clicked continue and the issue was there.
