### ISSUE TITLE
USER ISSUE: Cant load into single player world

### ISSUE THREAD

**Issue by haladslader** [StrangeLoopGames/EcoIssues#24754]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Launch single player world and crashed when it was connecting to server

**Expected behavior:**
Connected me to my single player world

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I dont know for sure if i have mods installed, im new and i joined a server that said it installed a mod for mega barrels or something but dont know how to check

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14225184/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14225187/Player-prev.log)

**Comment by D3nnis3n** [comment]
Your GPU doesn't fulfill the minimum requirements. The crash hints at OOM for VRAM, which is not surprising with only 3 GB, while 4 is the absolute minimum required for low graphic settings and a small local world without a lot going on.
