### ISSUE TITLE
USER ISSUE: Can't connect to friends world

### ISSUE THREAD

**Issue by sonnenpelzx** [StrangeLoopGames/EcoIssues#24758]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
1. Click on friends steam profile and connect to their world

**Expected behavior:**
connect to world

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hello sonnenpelzx,
the error message only states that a connection could not be established, which is not a bug, but a error message.
Your friend may want to reach out to support@strangeloopgames.com to see if there is a potential cause that can be found for the connection failing.
