### ISSUE TITLE
USER ISSUE: Torch Audio

### ISSUE THREAD

**Issue by Lazarus1395** [StrangeLoopGames/EcoIssues#24752]
\
**User Id: (slg63165)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
1. Quickly equip the torch and then swap to another tool.

**Expected behavior:**
The sound of the lit torch should stop when switching to another tool.

**Actual behavior:**
The sound of the lit torch continues even after switching to another tool.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, issue persists in both modded and unmodded.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24155
