### ISSUE TITLE
USER ISSUE: Character control

### ISSUE THREAD

**Issue by Wykentie** [StrangeLoopGames/EcoIssues#24765]
\
**User Id: (slg177649)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
just try to jump during running
Hold SHIFT + W and Press SPACE

**Expected behavior:**
should jump

**Actual behavior:**
not jumping

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce, I can jump fine while running with Shift + W.
