### ISSUE TITLE
USER ISSUE: Electricity Grid Issue

### ISSUE THREAD

**Issue by benny4444** [StrangeLoopGames/EcoIssues#24767]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14285844/Player-prev.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14285849/Player.log.copy.txt)

**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Each time I leave the game and reopen world later it causes my electric power grid to stop functioning for seemingly no reason. 

**Expected behavior:**
Electric power grid has sufficient electric power plants setup with sufficient water(I have 4 electric water pumps and 4 plants) and burnable fuel going to them.

**Actual behavior:**
Each time I quit and come back to game, I have to setup a mechanical power pump and power supply to jumpstart the electrical power source to turn electrical water supply to retsart electric grid. Its annoying, tedious and happens for no rhyme or reason.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Needs savegame an location of machinery not starting.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
