### ISSUE TITLE
USER ISSUE: Bug with flycommand

### ISSUE THREAD

**Issue by Varga45** [StrangeLoopGames/EcoIssues#24763]
\
**User Id: (slg188538)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
use /fly command in game, and press many times different arrow keys to moove the character

**Expected behavior:**
fly command should have a constant speed, sould be 'slow/smooth' enough to handle mooving arround a house to build the blocks 

**Actual behavior:**
the speed of fly increase more and more, reaching a point where mooving with the arrow keys become uncontrollable, because the speed is too fast to moove arround a single point, in example, a small area arround a house for building in details

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods, vanilla world

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14256901/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14256902/Player-prev.log)

**Comment by D3nnis3n** [comment]
Issue was not reproducible for me, neither for any of the QA staff. Needs reproduction steps.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided and issue not reproducible.
