### ISSUE TITLE
USER ISSUE: Wheelbarrows are not working after the latest update

### ISSUE THREAD

**Issue by agudmund** [StrangeLoopGames/EcoIssues#24762]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. click push rather than use on any red wheelbarrow.
2. two things will happen, either it does not move at all, or the left and right turn axis is set to ca. 1% means it would take a minimum 600-1000 cubes to take a turn
3. This makes me very sad because 99% of this game is the red wheelbarrow, and to be honest, I love this game sooooo much but like, respectufully to the devs then just dont mention that wooden carts suck balls in how they drive....  so its not an option to switch them i only ever use them as stationary because they are soooooo annoying to drive, the wheelbarrow however is cute and I can ride it literally for days.  Please fix this.

**Expected behavior:**
It should have a working red wheelbarrow

**Actual behavior:**
It doesnt have a working wheelbarrow, which is the only reason this game is so loved as opposed to the other 200 clones of the same types of games, heh

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None that Im aware of.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed for next hotfix.

**Comment by agudmund** [comment]
Cool, I just tried it on the latest dev build 10.1.4 i think it is.  There is still no turn axis on wheelbarrows, they are on rails, only go straight, or dont move at all.  am on a vanilla server.
