### ISSUE TITLE
USER ISSUE: network issue ?

### ISSUE THREAD

**Issue by Kay001Peepcrew** [StrangeLoopGames/EcoIssues#24773]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
happens randomly when playing

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
``
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This means the server is not responding and is not a bug. Check with the administrator of the server.
