### ISSUE TITLE
USER ISSUE: Calories popup lag

### ISSUE THREAD

**Issue by SparklesReal** [StrangeLoopGames/EcoIssues#24779]
\
**User Id: (slg231132)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. Go into a any work table
2. press the work button
3. lag starts and only stops when the -calories are not showing
(Note: Running on linux GE-Proton8-30)

**Expected behavior:**
Well no lag and calories that you lose show

**Actual behavior:**
Lag when calories are showing

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Linux is unfortunately not supported by us, hence we don't accept performance related reports.

**Comment by SparklesReal** [comment]
For anyone having this problem, switch to proton 9
