### ISSUE TITLE
USER ISSUE: amendement table not working

### ISSUE THREAD

**Issue by Lord-Schwartzy** [StrangeLoopGames/EcoIssues#24770]
\
**User Id: (slg232257)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Set it so another elected title can execute changes without an election. It won't work. Yesterday it started to work randomly and than stop again today.

**Expected behavior:**
Should let execute laws, it was working before.

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
On White Tiger

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Lord-Schwartzy** [comment]
![image 1](https://github.com/StrangeLoopGames/EcoIssues/assets/50409479/5f30c274-4032-45c1-9926-73c370d1fdcb)

For some reasons, sometime we can execute and sometime no without making any changes to the law.

Screenshot of the law, having the priority at 0 doesn't change anything either. A work around I think that I have found when trying to pass a law and having no options to execute directly beside starting an election is clicking on the "x" on the tab on the right, clicking on "edit" like I wanted to change the law and sending it again. Than I was able to execute.

**Comment by D3nnis3n** [comment]
Not reproducible - a video again would be useful showing all steps from start to end. Alternatively you could see if GM Weylin has a bit of time to see if they can get repro steps.

**Comment by weylint** [comment]
https://youtu.be/OK8NDGIdsCc
Video as requested.

Server: White Tiger
Amendment was created ~10 min before video. Server was not restarted in between.
Assigning the mayor title works (original constitution)
Assining the Game Masters title doesn't work (amendment)

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
