### ISSUE TITLE
[Settlements OFF] New players joining world are not authorized on Distribution Station.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24771]
10.1.4

Steps to reproduce:
1. With Settlements disabled, create and join a world, place a tent, place a distribution station and set it to distribute something to players like the starter tomateos.
2. Have another person join the server and try access the distribution station, they are unauthorized and can't access it.

What I noticed.
1. Adjusting the "Max total days as citizen to be eligible" so the "Apply" button appears and pressing the "Apply" button suddenly makes the new joinee authorized to pick stuff up from the Distribution Station.
2. People that joined after the Apply button was pressed won't be authorized on the Distribution Station.

**Comment by padmanek** [comment]
Looks like it got fixed with https://github.com/StrangeLoopGames/Eco/pull/13815

**Comment by D3nnis3n** [comment]
Will be fixed via https://github.com/StrangeLoopGames/Eco/pull/13815
