### ISSUE TITLE
USER ISSUE: Oil Head Lamp gets brighter and brighter over time and causes my graphics card (RTX 3080) to run hotter and hotter as it gets brighter, also significantly drops frame rate.

### ISSUE THREAD

**Issue by snmr1345** [StrangeLoopGames/EcoIssues#24774]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Wear oil headlamp.  Doesn't seem to matter if it's on or off, just the longer I play it gets brighter and brighter.  After an hour or more when I turn it on it'll will be so bright it physically hurts my eyes and washes out the entire screen.  My GPU core temp will increase like 20% when turning it on.

**Expected behavior:**
Should have not done the prior mentioned behavior.	

**Actual behavior:**
Did what I described.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-
[log_240217043737.log](https://github.com/StrangeLoopGames/EcoIssues/files/14321378/log_240217043737.log)
file

**Comment by snmr1345** [comment]
I should have mentioned, leaving to the menu fixes it but it's usually bright enough to be annoying in 20-30 min, might be a bit longer... I don't have a good sense of time while playing this game...lol.

**Comment by snmr1345** [comment]
I'm told by others on my server that this happens with the Carbide Helmet Lamp as well.

**Comment by D3nnis3n** [comment]
Fixed in 10.1.5.
