### ISSUE TITLE
USER ISSUE: integration discord bug ?

### ISSUE THREAD

**Issue by Bouy1975** [StrangeLoopGames/EcoIssues#24777]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Différents bug, dont celui de objets et liste Display sur le plan.Avatar des autres transparent. Buche de bois texture manquante à l'inverse de ma position regardant.. Freeze et difficulté de charger l’environnement quand distance de vue maximum (test), mais ça arrive aussi à distance de 100 (mon normal par choix).J'ai nettoyer le cache du jeu (dans les fichiers personnels de c:user..), le fichiers cache et les mods auto téléchargés..Pas de bug en suite..  Puis,, Autre lancement du jeu âpres petit sommeille, le bug de la liste de gents en vocal intégration discord.

**Expected behavior:**

**Actual behavior:**
Affichage freezé de la liste des joueurs en vocal ingame.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Rien. Pas de mods sur ce serveur.C:\Users\bouy2023\AppData\LocalLow\Strange Loop Games\Eco\Mods..vide..

**Please provide log files. Instruction is here [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14335643/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14335645/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14335646/Player-prev.log)

Bonjour à tous :) .. 568 heures sur Eco depuis le 7 janvier 2024 :)

**Comment by D3nnis3n** [comment]
Please only create one issue per bug, we cannot efficiently deal with a list of multiple bugs - though as far as the translator goes all of the ones mentioned have been already reported, as such I'm closing the issue as duplicate.
