### ISSUE TITLE
USER ISSUE: Freez, perte de puissance ?

### ISSUE THREAD

**Issue by Bou-E** [StrangeLoopGames/EcoIssues#24778]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Bonjour. à un moment de la journée, ça semble ne plus vouloir charger l’environnement, mon personnage avance très très lentement car il rame de trop. Cest l'affichage, car il suffi que je marche en regardant le sol, pour ne plus avoir le problème. Si je regarde a nouveaux le ciel, le freeze recommence.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Bouy1975** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14336815/Player.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14336816/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14336817/Player-prev.log)

**Comment by D3nnis3n** [comment]
Please follow the steps outlined here and attach the files required either here or via mail as mentioned:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0c576bcf-446e-4535-8576-eccf234d034f)

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
