### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Malenkei** [StrangeLoopGames/EcoIssues#24776]
\
**User Id: (slg113420)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.Settlement.<Initialize>b__171_0()
   at Eco.Gameplay.Items.WorldObjectItem.Move(Player player, Vector3i pos, Quaternion rotation, INetObject woNetObject)
Outer Exceptions:
One or more errors occurred. (Object reference not set to an instance of an object.)</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
What did you do when getting it?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided. Please feel free to reopen when you are able to provide information on cause of or activity related to the issue.
