### ISSUE TITLE
Enhancement for new shovels

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#2477]
Enhancement of the new shovels to dig more than 1 block of dirt or sand at a time

**Comment by KyeEco** [comment]
we have noticed the big shovel is in the game still but no way to craft it!. thanks guys

**Comment by SatsukiShizuka** [comment]
Since we have four tiers of shovels (wood-iron-steel-modern), perhaps we should have a gradual increase in the amount that it can shovel in one go (1-5-8-10?), while keeping the "carry max" to 10 (or 20) as we have it now?

**Comment by ecoemmeck** [comment]
i like that idea but i was more thinking 1 for wood shovel, 3 for iron shovel, 5 for steel shovel and 10 for modern shovel.
but at the end of the day its up to the devs

**Comment by Conchipedia** [comment]
Axe held can carry 10 logs, Pickaxe held can Carry 20 Stone/ore and Hammer held can pickup 10 blocks also if you pickup dirt from Stockpile it selects Shovel and lets you carry 10 dirt/sand , so why can we NOT dig up 10 at once?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#369
