### ISSUE TITLE
Iron hammer has no in hand model

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#2478]
I made the iron hammer today and started using it and noticed it doesn't have a model in your hand while swinging it

**Comment by Conchipedia** [comment]
this is also True of the iron Hoe, all the other iron Tools (shovel, pickaxe ,Axe and Scythe all show hand held models)

**Comment by MarjieAVolk** [comment]
@keegan-o IMO we should have something for these for beta, even if they are like a recolored version of the other tools

**Comment by keegan-o** [comment]
Oh no I had thought this was about a lack of hands in first person models, not the tools themselves! Yeesh. 

After so long, this should finally be fixed in master and release, and so will be in the next build.

**Comment by MarjieAVolk** [comment]
:O so there was art for it this whole time?

**Comment by keegan-o** [comment]
Well, we don't have unique art for them yet, no, but the model was there the whole time. They were just about 600-1700 meters above you. I blame the curved world, and myself :(

**Comment by Conchipedia** [comment]
just stick with Blaming the World, that works for most people 😉

**Comment by MarjieAVolk** [comment]
omg lol
