### ISSUE TITLE
USER ISSUE: Gray Screen

### ISSUE THREAD

**Issue by smeethan** [StrangeLoopGames/EcoIssues#24788]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Log in and join a friends game through steam. And then gray screen.

**Expected behavior:**
See the world and select a respond point.

**Actual behavior:**
Gray screen.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please attach a screenshot / photo and the logfiles as described in the issue form.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided.
