### ISSUE TITLE
USER ISSUE: CHASSE

### ISSUE THREAD

**Issue by FredKorrig** [StrangeLoopGames/EcoIssues#24787]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
JE NE PEUT PAS PRENDRE LES ANIMAUX;;;; TOUCHE INTERACTION NE MARCHE PAS POUR LES BISONS

**Expected behavior:**
METTRE DANS MON INVENTAIRE

**Actual behavior:**
LAISSE LE BISON SUR PLACE JE NE PEUT PAS LE PRENDRE

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NON

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24138
