### ISSUE TITLE
0.10.1.4 Skillbook Craft Cost Setting to Expert is not balanced to new skillbooks mini game profession changes. 

### ISSUE THREAD

**Issue by KaneHart** [StrangeLoopGames/EcoIssues#24786]
So if you select Expert mode you actually get super easy mode. It does not have all the cross profession page requirements. Some how someone missed / forget about the expert setting. 

I should mention dedicated server of course, idk if SP has such a feature.

**Comment by D3nnis3n** [comment]
Fixed in 10.2.
