### ISSUE TITLE
USER ISSUE: Rice missing from Food -> Produce

### ISSUE THREAD

**Issue by Coffee4cr** [StrangeLoopGames/EcoIssues#24781]
\
**User Id: (slg204381)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Open Ecopedia
Go to Food
Select Produce
Rice is missing

**Expected behavior:**
Rice should show up there with the rest like sunflower and even the flowers

**Actual behavior:**
Rice doesn't show up there, doesn't even have an Ecopedia entry

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Coffee4cr** [comment]
Camas Bulbs are also missing under FOOD -> Produce

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/13864
