### ISSUE TITLE
USER ISSUE: Sound

### ISSUE THREAD

**Issue by Ighnot** [StrangeLoopGames/EcoIssues#24785]
\
**User Id: (slg216860)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Start Eco.  Wait. Listen.

**Expected behavior:**
It should have played sounds like music and UI and whatnot. It does not.	

**Actual behavior:**
It does not.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You are not on the most recent version of Eco, please update.
Also make sure you have sound device configured, drivers are up to date and sound is actually on.
If all fails, we will need your logfiles as described in the issue form - please open a new issue in that case.
