### ISSUE TITLE
Wool Curtains use Cotton Thread

### ISSUE THREAD

**Issue by jwmc80** [StrangeLoopGames/EcoIssues#24797]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/91993280/77d86081-325c-4c41-8623-733dd859b341)

Cotton Curtains use Cotton Thread
Nylon Curtains use Nylon Thread
Wool Curtains use cotton?? Thread

**Comment by D3nnis3n** [comment]
Not sure what the bug is supposed to be here, we do not have sheep and so the recipe needs to use a wool equivalent recipe. This works as intended.

**Comment by jwmc80** [comment]
It is an inconsistent recipe and should use wool thread instead of cotton
thread.

**Comment by D3nnis3n** [comment]
But we don't have "Wool Thread" as an item in the base game, hence it uses cotton thread. That works as intended.
Adding another item without a plausible way to get it makes no sense? It might come with animal husbandry, but for now it's exactly how it should be?

Sorry, I may just be confused today?

**Comment by jwmc80** [comment]
It's good I'll look in game for additional detail.
