### ISSUE TITLE
USER ISSUE: Game keep crashing

### ISSUE THREAD

**Issue by JulienAqui** [StrangeLoopGames/EcoIssues#24793]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Just playing.. and the game still crash. I can't play more than 8-9 minutes... It's impossible to play...

**Expected behavior:**
Don't crash...

**Actual behavior:**
Crash...
All the storaged items are disappeared in all of my stockpiles.... I've no more items !! Completely empty

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes : easyminingGame keep crashing with removing this mod...

**Please provide log 
[Player-prev.log](https://github.com/
[log_240224062517.log](https://github.com/StrangeLoopGames/EcoIssues/files/14393789/log_240224062517.log)
StrangeLoopGames/EcoIssues/files/14393787/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14393788/Player.log)
files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by JulienAqui** [comment]
Player-prev log

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14393799/Player-prev.log)

**Comment by JulienAqui** [comment]
My last savegame : 
[La Prospérité-2024-02-24-18.34.45.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14393855/La.Prosperite-2024-02-24-18.34.45.zip)

**Comment by JulienAqui** [comment]
Game crash on my solo world, on creating a new world (solo), and even when i'm playong online on public server's...

**Comment by D3nnis3n** [comment]
The crash reports an out of memory exception, given the system does seem to have sufficient memory that is a a very strong hint at the memory being unstable. It is not a bug, though. You can reach out to support@strangeloopgames.com for further questions.

Please make sure that you drivers are up to date, you are not overclocking any components (including the memory - XMP / EXPO profiles _are_ overclicking) and that the memory is not defective.
