### ISSUE TITLE
USER ISSUE: Crash solo server

### ISSUE THREAD

**Issue by JulienAqui** [StrangeLoopGames/EcoIssues#24796]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Just playing and searching in crafts tables some receipe to do.	

**Expected behavior:**
Don't crash...

**Actual behavior:**

Le message d'erreur suivant est apparu :
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14402939/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14402940/Player-prev.log)

**Comment by D3nnis3n** [comment]
Likely caused by this: https://github.com/StrangeLoopGames/EcoIssues/issues/24793

The error message itself says nothing else than the server has closed. A server log would be required for deeper investigation. Please reach out to support@strangeloopgames.com.
