### ISSUE TITLE
crash server at launch

### ISSUE THREAD

**Issue by Moneyyy0** [StrangeLoopGames/EcoIssues#24791]
Version: 10.1.3
The the server crashed and I can't reopen it also when I put a backup.

[log_240223103508.log](https://github.com/StrangeLoopGames/EcoIssues/files/14390329/log_240223103508.log)

I send the log.

What can I do?

**Comment by D3nnis3n** [comment]
The logfile you have attached shows that the server is running on a very outdated version:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/1f0b15cd-d9bc-4db1-8c0e-6e3f3b13dca8)

Please make sure to update your game to the most recent version 10.1.4 - that may already resolve the issue.
In case it does not, please open a new issue, provide new logs and the savegame itself.
