### ISSUE TITLE
Placing a Country Foundation can brick your town when the Mayor is removed from office.

### ISSUE THREAD

**Issue by codyrandall** [StrangeLoopGames/EcoIssues#24799]
On Sea Otter we had the following happen:

1. A standard law where non-citizens can not pick up or place objects.
2. The mayor placed a country foundation and then had to replace it to move it.
3. The mayor got removed as a citizen of the city and could no longer place the country foundation
4. No new mayor could get voted for as we could not hit the minimum and the old mayor could not rejoin the town.

**Comment by D3nnis3n** [comment]
I assume the bug here is that when picking up the draft country, the town citizenship was retracted?
Was that the case, or why did it get retracted? The rest of the post doesn't look like a bug, but user settings working as they were intended by the users.

**Comment by D3nnis3n** [comment]
So, we were not able to reproduce loss of citizenship when picking up a country foundation as mayor, as such we cannot reproduce this issue and need more information. QA will check another time with the Sea Otter savegame and may reach out to you in Discord via the Sea Otter channel.

We'll only be able to continue investigating once we are able to reproduce this issue.

**Comment by codyrandall** [comment]
I think I may have selected the option to become a direct citizen of the country before picking it up

**Comment by D3nnis3n** [comment]
That would explain it, in that case it's a very unfortunate chain of decisions and events leading to this outcome, but not really a bug. We'll take the experience to discuss about if and how we can make some things more clear, though. Thanks!
