### ISSUE TITLE
Occupancy penalty either incorrectly calculated or incorrectly explained.

### ISSUE THREAD

**Issue by talonos2** [StrangeLoopGames/EcoIssues#24794]
In eco 10.1.4, When you hover over the residency pie chart, then hover over occupancy penalty, it says that the amount of XP you get is equal to `Housing Value / Number of Residents + Crowding Factor`. This is not how it is being calculated. Instead, it is being calculated as 
`(Housing Value + Crowding Factor) / Number of Residents.`

To reproduce:
- Get a house.
- Occupancy penalty is 0
- `/shackup 1`
- Occupancy penalty is reported as 40%, meaning you're getting 60% the XP. It would be 70% XP if the formula used was the formula described.
- `/shackup 1`, now you have two invisible friends as roommates.
- Occupancy penalty reported is 62%, meaning you're getting 38% the XP. It would be 48% if the formula used was the formula described.

**Comment by D3nnis3n** [comment]
The calculation as displayed is correct, we have changed the display to make it easier to understand the impact at a glance:
![image](https://github.com/user-attachments/assets/94d39df2-b8ac-4b94-80b6-362ad0fd4dc3)
