### ISSUE TITLE
USER ISSUE: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pedrurr** [StrangeLoopGames/EcoIssues#24803]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
try to enter server
this happens

**Expected behavior:**
to successefully log into the server

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method24025(Closure, Object)
   at Eco.Core.Controller....

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I think it auto installed by log in the server but I dont know how many mods or what mods
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14475062/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14475063/Player-prev.log)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This seems to be a server side error, so we would need the full server log, any installed mods and likely the savegame of the server. Additionally the admin can try to teleport you to somewhere else while logging in to see if that helps. In any case to investigate this we need the help of the admin, is that you or can you reach out?

**Comment by pedrurr** [comment]
I just waited and it worked, maybe it just need a server restart, ty regartheless
