### ISSUE TITLE
USER ISSUE: Local server crash

### ISSUE THREAD

**Issue by JulienAqui** [StrangeLoopGames/EcoIssues#24802]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Playing... No special things

**Expected behavior:**
No crash

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_240303022214.log](https://github.com/StrangeLoopGames/EcoIssues/files/14473171/log_240303022214.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14473174/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14473175/Player-prev.log)

**Comment by D3nnis3n** [comment]
This just means the server does no longer respond, the information unfortunately is not sufficient for a bug report. Please reach out to support@strangeloopgames.com to describe your issue in more detail.
