### ISSUE TITLE
Skills Window Not Expandable

### ISSUE THREAD

**Issue by rachaelfosner** [StrangeLoopGames/EcoIssues#2480]
![image](https://user-images.githubusercontent.com/26284408/31301637-5dc6ba82-aab0-11e7-9142-68c34259ed65.png)

Drag function doesn't activate over skill window in any corners. Can't enlarge it. :(

**Comment by MarjieAVolk** [comment]
:O The hitboxes are just all in the center of the window, I don't see what the problem is :P
