### ISSUE TITLE
USER ISSUE: Everyone in Admins

### ISSUE THREAD

**Issue by bkim346** [StrangeLoopGames/EcoIssues#24807]
\
**User Id: (slg242790)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**

**Expected behavior:**
Only person on Users.eco should be admin

**Actual behavior:**
Everyone online is an admin. And is no longer an admin when logged off. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[player.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14486808/player.zip)
server config files that includes user.eco
[Configs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14486895/Configs.zip)

**Comment by D3nnis3n** [comment]
Not reproducible, please provide a full server log and any additional information.
If that would be a general issue, we'd certainly already heard of this, there must be something else going on.

**Comment by bkim346** [comment]
Yeah I didn't think it was a general issue, rather a config issue on my end. But I how to resolve the issue. I figured it would be something in the user.eco file. I've attached the entire server file just to make things easier.

Logs: 
[Logs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14499565/Logs.zip)

Server files:
https://drive.google.com/file/d/1fLOKS_4yH8tQTnqm5hKqYEuvalnp03sJ/view?usp=sharing

I've also taken screen shots of my friend logging in and out to show what it looks like in game.

1. Looking at /manage_listadmins
![manage_listadmins](https://github.com/StrangeLoopGames/EcoIssues/assets/30411952/761596f6-911b-462c-a51f-531a2a075069)

2. Friend being online and being admin.
![admins](https://github.com/StrangeLoopGames/EcoIssues/assets/30411952/141f0183-429f-4b2d-9948-59795629a479)

3. No longer admin after leaving.
![after leaving](https://github.com/StrangeLoopGames/EcoIssues/assets/30411952/525dbfec-0042-4293-a1d1-29fe06134373)

4. Status is no longer attached when not online.
![Status](https://github.com/StrangeLoopGames/EcoIssues/assets/30411952/5d3a26d6-5f30-42cd-830c-ae3cf8822d20)

5.Admin again after logging back in.
![admins_again](https://github.com/StrangeLoopGames/EcoIssues/assets/30411952/e3c1be8d-011b-44e3-93a1-3595eabc1513)

Let me know if I can provide any other files or context to solve this issue. Thanks.

**Comment by bkim346** [comment]
Im running the server on a computer, ubuntu,  seperate from my client. Port forwarding is disabled by my ISP, so I have the port 3000 and 3001 open through ssh tunneling.

So i think me and my wife show as local IPs but the rest of the players are external.

**Comment by D3nnis3n** [comment]
That will be the problem, when Eco detects a user as connecting locally it will automatically assign administrator rights, which is working as intended. The skimmed log files show local IP's for everyone that joined:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/0a372bc5-df39-4e7b-a08b-a0acb91b8478)
It's three IP's and all three are local or private range IP's.

You'll need to fix that on the networking side, but I'm not able to help you with that unfortunately. It is not a bug, though.

**Comment by bkim346** [comment]
Ohhhh that makes a lot of sense. Is there a way to disable that or get around that issue?

**Comment by D3nnis3n** [comment]
No, Eco does always automatically assign admin rights for the session if the user is detected to be local.
That is intended to make the singleplayer experience seamless and easy and cannot be turned off - you'd need to make changes so the server sees the players are not connected locally.

**Comment by bkim346** [comment]
That makes sense. Thank you Dennis for helping me figure it out and at least i have a path to solving the issue.
