### ISSUE TITLE
USER ISSUE: In der 3rd Person ansicht werden 2 blöcke gebaut

### ISSUE THREAD

**Issue by Askahain** [StrangeLoopGames/EcoIssues#24800]
\
**User Id: (slg195543)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
3rd Person ansicht nutzen
hammer ausrüsten
z.b. holzblock bauen

**Expected behavior:**
Es sollte nur eine Block plaziert werden (funktioniert in der 1st Person Ansicht)

**Actual behavior:**
Es werden 2 Blöcke plaziert

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Keine Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24761
