### ISSUE TITLE
USER ISSUE: WT40 Unclaiming

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#24808]
\
**User Id: (slg77967)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Unclaimed Deed from Raw Lobster.
step1: Executive Action to move all property to Unica Governor title
step2: hammer the Homestad
(here the first odd thing happened: the deed did not disappeared)
step3: kick RawLobster as resident
step4: unclaim the last plot.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(Player player, InteractionTriggerInfo triggerInfo, InteractionTarget target)
   at InvokeStub_ClaimToolBaseItem.Unclaim(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
WT40 mods

**Please provide log files.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14487526/Player.log)

**Comment by D3nnis3n** [comment]
Thanks, that issue has already been reported and is tracked internally.
