### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Nytetears** [StrangeLoopGames/EcoIssues#24801]
\
**User Id: (slg242299)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. run a game as a private server on your own computer
2. have 2 friends join the game
3. set up a government
4. try to vote on the constitution, you cant because it gives the hosts local IP, only the host can vote

**Expected behavior:**
let me vote in game not take me to an outside address that does not work

**Actual behavior:**
it takes my friends to a page that does not connect

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You need to forward port 3001 (or whatever you have set in the config) for this to work, that is not a bug.
