### ISSUE TITLE
USER ISSUE: Schubkarre lässt sich nich lenken

### ISSUE THREAD

**Issue by daonware** [StrangeLoopGames/EcoIssues#24815]
\
**User Id: (slg242916)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Die Schubkarre lässt sich nicht mehr lenken, also es geht nur die Taste W,S (Vorfährts, Rückwärts)		

**Expected behavior:**
Schubkarre sollte sich lenken lassen mit der Taste "A,D"

**Actual behavior:**
Lässt sich leider nicht lenken, in der alten Version von Eco war dies Möglich, nun aber nicht mehr.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein, keine Mods vorhanden

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24762
