### ISSUE TITLE
USER ISSUE: Meteor Shard not rendering properly

### ISSUE THREAD

**Issue by TrooperHX** [StrangeLoopGames/EcoIssues#24813]
The model for the Meteor Shard is not rendering properly. It doesn't render properly in hand, when attached and it doesn't render properly for others as well.
I gave it to a friend as well and while attached to the backpack, the shard wasn't emiting the sparkles and was still transparent.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/31357092/be29860f-d76e-4b19-8026-efc34fd4a236)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/31357092/3abac72f-b1db-44a8-bc44-708314ce2380)

Tested and it's the same on different servers, so I assume it's an issue from the game's code.
PS. Instructions for how to attach it to the backpack in the tooltip of the item would be helpful! :D

EDIT: This is on the latest version:
0.10.1.4 beta release-603

**Comment by D3nnis3n** [comment]
Fixed in Update 10.2, thanks for the report!
