### ISSUE TITLE
USER ISSUE: All furniture, machines, shop and stockpiles deleted from claim

### ISSUE THREAD

**Issue by Ki-Tan2934** [StrangeLoopGames/EcoIssues#24816]
\
**User Id: (slg181583)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
/ownit
Go to residency and remove the old player residents
Allow plots unclaiming while rentingIncrease max occupants to 1Invite a player

**Expected behavior:**
residents removed

**Actual behavior:**
Everything that's not a block is deleted and base is unclaimed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes, not sure. It happens once but not another.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That works as intended, when a resident is kicked, everything they placed goes into their void storage.
