### ISSUE TITLE
USER ISSUE: Placing blocks on click and release in building mode

### ISSUE THREAD

**Issue by EvilOnd** [StrangeLoopGames/EcoIssues#24818]
Hello there!
I have an issue with my game placing one block when I click the button and another one when I release it and same when deleting blocks.
I have tried my main mouse, a Steelseries, my old mouse a Logitech, and tested a keyboard bind. All with the same results.
I have also tried on a public server and on a local server with no difference. I also tried reinstalling the game also not making any difference.

Version: 0.10.1.4 beta release-603

Steps to Reproduce:
Place building block

Expected behavior:
Place 1 block on click

Actual behavior:
Place 1 block on click and 1 on release.

[log_240308123731.log](https://github.com/StrangeLoopGames/EcoIssues/files/14537814/log_240308123731.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14537822/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14537823/Player-prev.log)

**Comment by D3nnis3n** [comment]
Seems like a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24761.
