### ISSUE TITLE
USER ISSUE: FPS drops und Fahrzeuge bug

### ISSUE THREAD

**Issue by RedPandaSaBu** [StrangeLoopGames/EcoIssues#24811]
\
**User Id: (slg241430)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Fahrzeuge bugen nach oben sobald die unter der erde auf erdrampen stehen. desweiterm gibt es ein problem mit den fps drop, die  selten von alleine auf normal wert hoch gehen.

**Expected behavior:**
fahrzeuge beiben an ort und stelle stehen wo man sie parken tut. fps drops reduzieren

**Actual behavior:**
geparkte fahrzeuge bugen sich an die oberfläche. fps steigen nach einem drop selten von selbst auf den normal wert so dass man das spiel teilweise neustarten

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Danke für die Meldung, das Problem mit den Fahrzeugen wurde bereits gemeldet.

Für die Untersuchung von FPS Problemen ist es notwendig, die folgenden Schritte durchzuführen:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/8c98efd7-52ab-4780-a064-9c891a50b376)

Die benötigten Daten dann bitte an support@strangeloopgames.com senden.
