### ISSUE TITLE
USER ISSUE: Connection

### ISSUE THREAD

**Issue by gard3** [StrangeLoopGames/EcoIssues#24822]
\
**User Id: (slg217235)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
Lors de l'ouverture du jeux je ne voie aucun monde. J'ai même désinstallé et réinstallé le jeux et rien n'a changer

**Expected behavior:**
voire mes mondes

**Actual behavior:**
ne voie aucun monde même pas les serveures de base

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Should be fixed.

**Comment by gard3** [comment]
Nop
Dominik

Le 12 mars 2024 à 08:15, Dennis Scholz ***@***.***> a écrit :

﻿

Should be fixed.
