### ISSUE TITLE
Running diagonally is slower

### ISSUE THREAD

**Issue by voodoozulu** [StrangeLoopGames/EcoIssues#24827]
I tried a quick search and I could not find this mentioned. You run slower while running in an inter cardinal direction (North-west, North-East, South-West, South-East). You run faster while running in a cardinal direction. 

To reproduce: 
Run in a cardinal direction holding W. press D or A to run NE, NW, SE, or SW. You will slow down

Run in an inter cardinal direction (NE, NW, SE, SW) holding W. Press A or D to run in a cardinal direction. You will speed up.

**Comment by D3nnis3n** [comment]
Not reproducible, closing.
