### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by magneticmc123** [StrangeLoopGames/EcoIssues#24825]
\
**User Id: (slg201578)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This just says that you couldn't connect to a server - reasons can be anything, mostly network issues.
It's also a known issue with some russian ISP's that don't support cloudflare, in that case a VPN can help.
You can reach out to support@strangeloopgames.com for more help, but this isn't a bug.
