### ISSUE TITLE
USER ISSUE: player connection issues

### ISSUE THREAD

**Issue by dalandroid** [StrangeLoopGames/EcoIssues#24829]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. player A login 
2. A logout 
3. reconnerction issues ( player avatar remains )

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
none mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This issue doesn't have enough information to be investigated. Please reopen the issue with logfiles and as much additional data as possible so understanding of the issue of possible.
