### ISSUE TITLE
Game Crashes when changing server.

### ISSUE THREAD

**Issue by KyeEco** [StrangeLoopGames/EcoIssues#2482]
hey guy i don't know if this has been mentioned as i couldn't find anything, but when changing servers the game crashes and throws out a dump file, sometimes its fine and others its not, i noticed in 5..5.4- 5.6.1 that if you refreshed the server list it would be fine to change, but that doesn't seem to work all the time anymore either, is there a way to maybe have the game force refresh server list when you leave a server ?

**Comment by MarjieAVolk** [comment]
Can you attach your output log file?  It should be in your Eco_Data folder

**Comment by SeanAtr0n** [comment]
Not much info to work with here... I suspect this was due to the builder thread issues we were seeing a month ago so I'll pass it on to meta! 😺
