### ISSUE TITLE
USER ISSUE: Unable to sign in to official server

### ISSUE THREAD

**Issue by stephenengland** [StrangeLoopGames/EcoIssues#24828]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. Try to login to dusky robin
2. Get error while loading the world

**Expected behavior:**
Loaded the world/server

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method41554(Closure, Object)
   at Eco.Core.Contr...

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Is this persisting?

**Comment by stephenengland** [comment]
> Is this persisting?

The error started right after the server did a reset and until the next reset. Once the server restarted again, the error went away. It happened with at least two other people on the server. Those people were across different professions, houses, and towns.

**Comment by D3nnis3n** [comment]
Alright, that is already known.
