### ISSUE TITLE
6.0.1 staging e3696fad causing crash loop on loading

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2483]
https://www.dropbox.com/s/vzpbrf3ey5zxfb0/JayL_dump.zip?dl=0
https://www.dropbox.com/s/c3g0b8glx4qk9e0/JayL_Game.zip?dl=0

**Comment by MarjieAVolk** [comment]
Got another case of object in the worldobjects folder

**Comment by MarjieAVolk** [comment]
Here is a fixed version of your save, hope that works: https://drive.google.com/file/d/0B4kJEcFjfDpjd0ZST1NrSFVtblE/view?usp=sharing

**Comment by metachronism** [comment]
this should only happen if someone connects before the migration finishes, which isnt possible anymore
