### ISSUE TITLE
USER ISSUE: FPS drops extremely low and then eventually crashes

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoIssues#24830]
\
**User Id: (slg182316)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
Play for 10-20 minutes

**Expected behavior:**
FPS should stay the same it was when first loading into the world

**Actual behavior:**
Drops from 80-90 to 6-15, changes depending on which direction you are looking

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Not sure, on Dadspeed server at the time of this report.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14608145/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14608147/Player-prev.log)

Crashes have happened 3-4 times in a row now.

**Comment by ShoppyCodes** [comment]
Crash folder dump, latest two crashes:

Latest crash:
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14608234/Player.log)
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/14608235/crash.dmp)

One before that:
[crash.dmp](https://github.com/StrangeLoopGames/EcoIssues/files/14608247/crash.dmp)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14608248/Player.log)

**Comment by D3nnis3n** [comment]
Please follow these steps and provide the necessary data:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/da9ffff2-4595-40e0-a670-0f5970fb7978)

**Comment by ShoppyCodes** [comment]
Downloaded the release_dev branch. I will update on the next major FPS drop/crash - thanks Dennis

**Comment by ShoppyCodes** [comment]
FPS went from 80-100 to 7-15.Turning and looking in different directions seems to make it go up and down, but only in the 7-15 range.

The requested files: https://drive.google.com/file/d/1SwSh5eP3RaCwNhF_yCQ-JlGXKoonPlB7/view?usp=sharing

**Comment by gzatravkin** [comment]
Thanks. The profiler shows some problems with shadows.
Could you please now do following
1) Check if shadow quality have impact on that
2) Record a video of using command /DisableObjects command to see if some particular objects have bigger impact on that (with options /DisableObjects trees, worldobjects, rubbles, animals)

**Comment by ShoppyCodes** [comment]
Seems that changing the shadow settings from max to min helps the problem, but FPS still doesn't go as high as it was before. When using the lowest shadow setting, it seemed that the problem did not occur - though potentially more time playing with the lowest shadow setting is necessary.

Using /disableobjects seemed not to help the FPS, as you can see in the video. I did the 4 options you said with it.

Video: https://drive.google.com/file/d/1OYaX6Prd3bUCbxoAQeJeOd_rzDSJ0R7s/view?usp=sharing

**Comment by ShoppyCodes** [comment]
After spending more time with the shadows set to the lowest setting, this issue does not occur. Definitely the shadows.

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14132 in 10.3.
