### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by agudmund** [StrangeLoopGames/EcoIssues#24837]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. click play in steam
2. click play in game

**Expected behavior:**
I would have expected a game to appear, the one i paid for.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method99420(Closure, Object)
   at Eco.Core.Controller....

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
probably, im not an admin.  looks like a missing game asset error though

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the full client logs when this happens and more details on what exactly you are doing when the error appears.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided. The error in question should no longer happen after a server restart in any case.

**Comment by agudmund** [comment]
Confirmed, reason for not updating was playtesting version 10.2 on a live
public server, and have not seen the issue come up since the latest, quite
lovely and most stable in eco history so far, 10.2 version.

And thank you
  -Aevar
