### ISSUE TITLE
Blank characters in nickname

### ISSUE THREAD

**Issue by WaneTol72** [StrangeLoopGames/EcoIssues#24832]
Version: 0.10.1.5 beta release-619

Steps to Reproduce:
Playing on the any server with a nickname in Steam: " " (Yes, just a blank character) and try to send different messages (of different lengths) to any chat room or any player

Expected behaviour:
You can leave the obscure characters in the nickname, but prevent accidentally sending messages to that player

Actual behaviour:
In the game it is displayed as: "☐☐☐☐☐☐", Because of this, ALL players have problems when trying to write a message - they are sometimes sent to my friend. Also he sometimes sends messages to himself because of this bug. Most likely his blank name is the keyword that the chat responds to.
This problem also occurs with players whose nickname in Steam consists of unusual characters.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/35455247/eb583a16-141d-459c-9b6d-14328564eb45)

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14239
