### ISSUE TITLE
Mining Basic Upgrade not working in Arrastra and yes I have lvl7 mining.

### ISSUE THREAD

**Issue by Felddagryph** [StrangeLoopGames/EcoIssues#24842]
Instead of 50% reduction in resources used it is 0% reduction. I am playing on Giant Panda official server. I've tried moving the Arrastra, removing and re-inserting the Mining Basic Upgrade, exiting and re-entering the game. Game Version is 0.10.1.5 beta release 619

**Comment by D3nnis3n** [comment]
Recipes with a yellow border get no reduction in ingredient cost, that works as intended.
