### ISSUE TITLE
Settlement Foundations can be moved arbitrary distances.

### ISSUE THREAD

**Issue by codyrandall** [StrangeLoopGames/EcoIssues#24841]
1. Create a line to move your foundation on (must stay inside the deed at all times)
2. Move click the foundation a couple times to your desired location
3. Enjoy your arbitrarily moved bubble

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3419725/ef55a7df-d90f-49df-adaf-8499b5492a8e)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3419725/fb1eb370-cd3c-43a2-88aa-7d81e8c5f181)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3419725/44d3a0d6-ee6e-4292-b2c9-7fec72e9a397)

This can be used to move a foundation into another town or a country next to a town foundation to completely cover it in a couple minutes.

**Comment by D3nnis3n** [comment]
Already fixed via https://github.com/StrangeLoopGames/Eco/pull/13789
