### ISSUE TITLE
USER ISSUE: Server not respondinG

### ISSUE THREAD

**Issue by hans1224** [StrangeLoopGames/EcoIssues#24844]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
WENN ICH AUF DEN  SVERER MÖCHTE BEI 100 % COMT Server not responding

**Expected behavior:**
DER SVER SOLTE LAUFEN OHNE FEHLER

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NEI

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Does not contain sufficient information for investigation, the error simply says the connection to the server was lost and doesn't hint at any bug. Please reach out to support@strangeloopgames.com instead.
