### ISSUE TITLE
USER ISSUE: [Error] [Eco] System.AggregateException:

### ISSUE THREAD

**Issue by Sharky213** [StrangeLoopGames/EcoIssues#24847]
\
**User Id: (slg158347)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
21:53:12.191] [28] [Error] [Eco] System.AggregateException: One or more errors occurred. (LiteDB ENSURE: page type must be index page)
 ---> System.Exception: LiteDB ENSURE: page type must be index page

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Sounds like a corrupted database, but not enough information and no hint towards a bug.
Feel free to reach out to support@strangeloopgames.com for further assistance.
