### ISSUE TITLE
Survival Tree should be exempt from SP inflation

### ISSUE THREAD

**Issue by SatsukiShizuka** [StrangeLoopGames/EcoIssues#2484]
Enhancement suggestion: This way, it would encourage people to focus on gathering, without penalty to developing the material processing trees - and everyone would be more willing to help each other out in gathering resources.

**Comment by SeanAtr0n** [comment]
oh, cool... looks like craig is working on it

**Comment by craig-jong** [comment]
This should be in the latest staging builds.
