### ISSUE TITLE
USER ISSUE: Sea Otter Playtest: Cart right-click option not always showing

### ISSUE THREAD

**Issue by steplica** [StrangeLoopGames/EcoIssues#24845]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.0 beta playtest-370

**Steps to Reproduce:**
Hold a block in your hands (log, dirt, stone, etc.) and aim at a cart to try and quick-deposit it with right-click.

**Expected behavior:**
Right-click deposit option should always appear when I'm holding something and aiming at a cart or other depositable inventory.

**Actual behavior:**
Right-click deposit option is randomly not available when I try to deposit what I'm holding. This changes in a matter of seconds if I dig something new. It's annoying having to manually open the inventory so much.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Forzy30** [comment]
This issue always occurs when loading into a server and you get the "Notifications: Failed to handle RPC method: SyncDeltaControllerHashSet". If you load into a server and don't get that notification in chat, then you will be able to use right click on vehicles, stockpiles, and other forms of storage. Often times you can quit the game completely and relaunch and it fixes this issue. However, today I restarted about 15 times and I cannot get this issue to go away. It makes it very hard to mine rocks, chop trees, or gather a lot of dirt.

**Comment by D3nnis3n** [comment]
Will be resolved by https://github.com/StrangeLoopGames/Eco/pull/13885.
