### ISSUE TITLE
USER ISSUE: cant enter server anymore

### ISSUE THREAD

**Issue by felesial** [StrangeLoopGames/EcoIssues#24846]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
while playing the game suddenly i was kicked out of the server. and cant enter anymore. im getting wrong password error but i play with steam dont  have a password and itsa free official server	

**Expected behavior:**
it shouldt have kicked me out of the server at first place but it doesnt let me enter anyore

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60,00%>Internal Server Error, Trace ID: 00-8cbbcea2d70839a81c59df22b313afa9-0ca177b801a0e258-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Caused by Steam Maintenance which happens every Tuesday to Wednesday at 23 / 0:00 CET, depending on if its summer or winter time.
