### ISSUE TITLE
USER ISSUE: Bug : cant move and screen blur

### ISSUE THREAD

**Issue by NDeleu** [StrangeLoopGames/EcoIssues#24849]
\
**User Id: (slg243087)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
I Can t move my character and my screen, my interface is clear, bug the HUD is disapear, and the rest of my screen is Blur. My view is considering 3th person when i check B, but the actuel view is first person. Te server reset but the bug is always here. I have this bug only on this server, i can play normaly on the other servers. Thanks 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
The server has some mod (as Elixir) but i'm not admin.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
It's unlikely to be a game issue when it only happens on a specific server, but in any case we'd need an actual visual view of what you're seeing, your logs and the full information on server mods.

**Comment by D3nnis3n** [comment]
Issue is not reproducible and no further information was provided, hence closing.
Feel free to reopen the issue once you can provide requested information.
