### ISSUE TITLE
USER ISSUE: Не заходит на сервер

### ISSUE THREAD

**Issue by Zernom** [StrangeLoopGames/EcoIssues#24851]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. Подлючение к серверу

**Expected behavior:**
Подключение к серверу

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
да, нет

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Zernom** [comment]
[log_240331091400.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14814370/log_240331091400.txt)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24853
