### ISSUE TITLE
USER ISSUE: Auth error

### ISSUE THREAD

**Issue by SentilONE** [StrangeLoopGames/EcoIssues#24852]
\
**User Id: (slg101815)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
Standard connection to the server.

**Expected behavior:**
Log in.

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Have mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SentilONE** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814372/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814373/Player-prev.log)

**Comment by SentilONE** [comment]
[log_240331092343.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814380/log_240331092343.log)

**Comment by Pro100-Adm** [comment]
The same issue.
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814936/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814937/Player.log)
[log_240331110403.log](https://github.com/StrangeLoopGames/EcoIssues/files/14814942/log_240331110403.log)

**Comment by D3nnis3n** [comment]
What is the range of your computers public IP? Need first and second field, e.g. 123.123.X.X.
Please post in issue https://github.com/StrangeLoopGames/EcoIssues/issues/24850, which this is a duplicate of.
