### ISSUE TITLE
USER ISSUE: Plow Field Contract does not work with Plow-Tool

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#24858]
\
**User Id: (slg77967)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
PlayerA Create Plow field contract.
PlayerB accept and put down hand plow
PlayerB tries to plow the field with hand plow

**Expected behavior:**
Plowing field should work with all tools

**Actual behavior:**
Plowing field only works with Hoe

**Do you have mods installed? Does the issue happen when no mods are installed?:**
White Tiger 41

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3965439/d35f6fe1-1824-42b9-b142-da9b32b409af)

**Comment by Frozen-byte** [comment]
Same seems valid for sowing with a Tractor Module.

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14065 in 10.3.
