### ISSUE TITLE
USER ISSUE: Crash after trying to open Stockpile

### ISSUE THREAD

**Issue by KYordanov** [StrangeLoopGames/EcoIssues#24857]
\
**User Id: (slg182607)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
In server hostet on the same PC. I am the only player enterd the server ever.Crash after trying to open Stockpile.
Can not load the world anymore :(

**Expected behavior:**
Not to crash.

**Actual behavior:**
The following error message popped up:
```
[Crash_Log_0.10.1.5_beta_release-619.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14827321/Crash_Log_0.10.1.5_beta_release-619.txt)

Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.Yes the crash happen when no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the server logfiles and the Difficulty.eco config file as well.

**Comment by KYordanov** [comment]
The world loaded and now I am plaing into it.
