### ISSUE TITLE
USER ISSUE: Free Automatic Loom Cotton Buntings

### ISSUE THREAD

**Issue by Chasedoesstuff** [StrangeLoopGames/EcoIssues#24855]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
1. Setup an Automatic Loom
2. Press the hammer icon for specific Variations on the Weave Cotton Bunting (large or small) recipe at an automatic loom
3. Versions other than the default red one will cost only tailoring labor

**Expected behavior:**
It should cost as much as the default red one 

**Actual behavior:**
Instead of actually taking resources it only takes a little bit of tailoring labor

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't have mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14817059/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14817060/Player-prev.log)

**Comment by D3nnis3n** [comment]
Fixed in Update 10.2.
