### ISSUE TITLE
USER ISSUE: FPS drop

### ISSUE THREAD

**Issue by espencapable** [StrangeLoopGames/EcoIssues#24861]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
Play the game for 2h or more.

**Expected behavior:**
Be stable with around 100 fps

**Actual behavior:**
Drops down to 2fps and is unplayable

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please follow these steps and provide the necessary data:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/da9ffff2-4595-40e0-a670-0f5970fb7978)

**Comment by D3nnis3n** [comment]
Closing due to necessary information to investigate report not provided.
