### ISSUE TITLE
USER ISSUE: No Highlight visible for land plotting	

### ISSUE THREAD

**Issue by Tombo3006** [StrangeLoopGames/EcoIssues#24862]
\
**User Id: (slg197014)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
When using to the claim tool, it does not highlight the plot tiles.

**Expected behavior:**
Show the highlighted are of where you want to claim land.

**Actual behavior:**
It does not show the highlighted color.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please attach the log files after the occurance and provide context around the action - what were you trying to claim with the claim tool, a homestead? In a town? Anything you did before?

**Comment by Tombo3006** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14908290/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14908291/Player-prev.log)
 
This was happening during when I was claiming land for an outpost stake. It seems to be happening for whatever you are claiming land for. Whether it was Homesteade/Outpost it does not shot the plots being highlighted when claim/unclaim.

**Comment by D3nnis3n** [comment]
With outpost stakes you are referring to the unrestricted stakes in singleplayer, is that what you are playing?

**Comment by D3nnis3n** [comment]
Not reproducible here, unfortunately:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/7de438ca-58b8-401d-976e-a4bcad6a6c73)

We'll need a clearly reproducible case, otherwise we're unfortunately unable to investigate.

**Comment by Tombo3006** [comment]
![20240409221359_1](https://github.com/StrangeLoopGames/EcoIssues/assets/139152135/28d1df31-d053-47f2-893b-ab9c389c657f)
![20240409221415_1](https://github.com/StrangeLoopGames/EcoIssues/assets/139152135/e8c9a017-1810-4956-a76d-0ad5f025f10d)

First Photo is when I equip the Claim tool. Second photo is when I went to unclaim a plot of land.

**Comment by D3nnis3n** [comment]
Does the other player also have the issue?

**Comment by Tombo3006** [comment]
The player also has the same issue.

**Comment by D3nnis3n** [comment]
So far not able to reproduce and no other reports either. I fear if there doesn't come someone up with some breakthrough observation issue will not be able to be adressed.

**Comment by Tombo3006** [comment]
Darn that stinks. Hopefully it can randomly pop up or more reports so it can be addressed.

**Comment by D3nnis3n** [comment]
Closing due to not reproducible. If anyone else gets this and can provide a reproduction case, please open a new issue!
