### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by TGIFlowen** [StrangeLoopGames/EcoIssues#24867]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
1.  Drag an item from your hotbar to the bottom right icon in the set of 6 items on the bottom right of the screen, next to the minimap.

**Expected behavior:**
It should have done nothing.  Or the item should've snapped back to the toolbar.

**Actual behavior:**
The items gets stuck on top of that set of buttons.  The buttons and the item become un-interactable.  The backpack can no longer be opened with B.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
dup https://github.com/StrangeLoopGames/EcoIssues/issues/24866
