### ISSUE TITLE
USER ISSUE: Cheat window appeared, not cheating

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoIssues#24864]
\
**User Id: (slg182316)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
Try to join a server in 10.2

**Expected behavior:**
Joined the server

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Not that I am aware of. Joined "Greenleaf Vanilla" server.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server is using an experimental feature that is not yet functioning correctly and disabled by default, please let them know to set "MovementHackDetection": false, in their Users.eco.
