### ISSUE TITLE
USER ISSUE: Can't delete bank account I created myself

### ISSUE THREAD

**Issue by Mkorny** [StrangeLoopGames/EcoIssues#24860]
![BankAct-04042024](https://github.com/StrangeLoopGames/EcoIssues/assets/34373753/9789089a-906f-4488-ab68-d726679cb503)
\
**User Id: (slg183077)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
Quick note - this only happened to me in White Tiger.

1. Go to the Bank
2. Create a Bank Account
3. Click the X option to delete that same account
4. get error message "You don't have access to do that"

(also tried adding myself as account user)

**Expected behavior:**
The account should have been deleted

**Actual behavior:**
Prevented me from deleting the account

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, this was on WT.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Mkorny** [comment]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14877667/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14877668/Player.log)

**Comment by Mkorny** [comment]
If you want a Video repro - https://1drv.ms/v/s!AlwkS4BRguXxugRXzCnmAHKIojS-?e=comwHE

**Comment by D3nnis3n** [comment]
Does that account still exist on save and does the issue persist in 10.2?

**Comment by Mkorny** [comment]
Hey @D3nnis3n , yeah still happening exact same repro steps on current WT season.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/34373753/049b50d5-51b3-42cb-bbe8-d319caab47da)

**Comment by D3nnis3n** [comment]
Will be addressed in hotfix via https://github.com/StrangeLoopGames/Eco/pull/13933.
