### ISSUE TITLE
USER ISSUE: Tool Stuck in the UI

### ISSUE THREAD

**Issue by Tsubael** [StrangeLoopGames/EcoIssues#24866]
![image_2024-04-08_233729319](https://github.com/StrangeLoopGames/EcoIssues/assets/110587379/fd9f5f87-0be9-464d-91dc-030e5496a6f8)
\
**User Id: (slg234778)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
Drag and drop a tool in between one of the 6 icons by the minimap

**Expected behavior:**
Nothing

**Actual behavior:**
Tool gets stuck in the UI

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 10.2.1.
