### ISSUE TITLE
USER ISSUE: Server Migration V9 to V10 KeyNotFoundException DataMigrations.MemberDataInput

### ISSUE THREAD

**Issue by FastFelix771** [StrangeLoopGames/EcoIssues#24865]
I tried updating using the docker image from 0.9.7.13-release-511 to 0.10.2.1-release-642.
Got the following log output and the server does not successfully start.

[_eco_server.1.yvblujjvmh0tn29mwaponrsk1_logs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14910792/_eco_server.1.yvblujjvmh0tn29mwaponrsk1_logs.txt)

I think the relevant part is this:
> Failed to start the server. Exception was Exception: KeyNotFoundException
> Message:The given key 'Eco.Core.Serialization.Migrations.DataMigrations.MemberDataInput' was not present in the dictionary.

I could not find the migrations.log file, seems like it doesnt get saved to any data volumes (/app/Storage or /app/Configs).

No mods installed whatsoever.

**Comment by D3nnis3n** [comment]
Migration from Update 9 to 10 is not supported.
