### ISSUE TITLE
USER ISSUE: Server schmeißt mich raus

### ISSUE THREAD

**Issue by SonGokuPower** [StrangeLoopGames/EcoIssues#24871]
\
**User Id: (slg91126)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
1. Besitzpflock platzieren
2. Claim Papers einfügen
3. Error bekommen

**Expected behavior:**
Wollte einfach nur den Pflock verlegen, da er mich dort gestört hat und ich immer mit dem Auto angestoßen bin. Eigentlich wollte ich nur erneut mein Gebiet abstecken, damit ich meine Bonis bekomme.

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.PlotsComponent.DescribePlotsClaimed()
   at InvokeStub_PlotsComponent.DescribePlotsClaimed(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Ja aber keine die da stören könnten. Vor dem Update hat alles noch funktioniert.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24863
