### ISSUE TITLE
User issue: Chat window "out of bounds"

### ISSUE THREAD

**Issue by Windowsfreak** [StrangeLoopGames/EcoIssues#24876]
Playing 10.2.1 on Windows

My playmate just couldn't find his chat window. Apparently controlling it with the keyboard by hitting Enter to write a message completely blindly and hitting Enter again to submit works, but the chat window can't be seen anywhere on the screen. I assume that the chat window somehow managed to be out of bounds and there doesn't seem a way to restore its location. As we don't know _why_ the chat window is invisible, we're just assuming things here.

Expected behaviour:

A chat window is on screen, shows incoming messages and gets interactable with border and everything when pressing the Tab key and moving the mouse towards it.

**Comment by D3nnis3n** [comment]
Open "run" and type "%LOCALAPPDATA%Low/Strange Loop Games", in there delete the Eco folder (will reset user settings), then see if its back.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided, assuming the noted steps helped.

**Comment by Windowsfreak** [comment]
Thank you @D3nnis3n, your instructions fixed all the problems :)
Apparently it was possible to drag the chat window to the bottom left of the screen and it's hard to find it again.
