### ISSUE TITLE
USER ISSUE: Ressourcen werden bei Produktionsabbruch in falsche Lager gelegt

### ISSUE THREAD

**Issue by Askahain** [StrangeLoopGames/EcoIssues#24873]
\
**User Id: (slg195543)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
1. Starten eine Produktion z.b. (Walzwerk) (Hinzugefügt wurden 2 Stahl aus dem Inventar)
2. Abbruch der Produktion.

**Expected behavior:**
Die Ressourcen sollten entweder in einem inventar laden in das der Tisch ablegen darf, oder im Tisch verbleiben zum einsammlen

**Actual behavior:**
Die Ressourcen werden in das ersten inventar gelegt aus dem der Tische Rohstoffe entnehmen darf. Es wird ignoriert ob tiefer noch ein inventar ist in das er ablegen dürfte.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/13992
