### ISSUE TITLE
USER ISSUE: Fliegende Steine

### ISSUE THREAD

**Issue by Askahain** [StrangeLoopGames/EcoIssues#24875]
\
**User Id: (slg195543)**
**Version:** 0.10.2.0 beta release-640

**Steps to Reproduce:**
1. In einem Unterirdischen Raum liegen nicht aufgesammlete Steine auf dem Boden. (Raum 5x5x5)
2. Man baut ein Lager (5x5x5) darauf.
3. Man füllt das Lager
4. Steine werden nach oben verschoben und landen auf dem nächsten freien Feld. (Oberfläche)
5. Nach einem Serverneustart schweben die Steine in der Luft mal mehr und mal weniger hoch.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/58778836/3bc7d286-9f9a-4533-b845-34358a87a1d5)

**Expected behavior:**
Die Steine sollten weiter an der Oberfläche liegen bleiben und nicht schweben.

**Actual behavior:**
Siehe Beschreibung

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/13850, releasing with next minor update.
