### ISSUE TITLE
USER ISSUE: Server Crashed

### ISSUE THREAD

**Issue by CricketXO** [StrangeLoopGames/EcoIssues#24877]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**
 No idea. Sorry this is not going to be a helpful one. 

**Expected behavior:**
Does not crash

**Actual behavior:**
Earth was flat found edge of world fell off.  

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
For a crash the minimum information necessary is always at least the crash message and server logs, given both aren't provided there is no way to investigate the issue.
