### ISSUE TITLE
[A-6.0.0]Hammering on the cart can permanently increase your weight until server restart.

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2488]
So it turns out when you use a hammer on a cart that you cannot pickup can increase your weight and will remain until you restart the server. I haven't done much testing on this since I cannot restart the server every time when others are playing.
All you need to reproduce this (That we used) is a normal wooden cart and a hammer, Make sure you don't have the deed in your inventory or it won't work then you just hammer away on the cart.

Others have reported the same issue on the forum but haven't named the issue of the cart hammering that we had.
http://ecoforum.strangeloopgames.com/topic/2875/personal-inventory-filled-to-47-of-50-kg-despite-empty-backpack-and-hotbar

![inventory](https://user-images.githubusercontent.com/4078460/31356745-6c6ba6d8-ad3f-11e7-8e0c-fdc6af637d0e.PNG)

**Comment by MarjieAVolk** [comment]
Is this on 6.0?  This should already be fixed in the latest staging build.

**Comment by wiloxe** [comment]
Ah sorry for forgetting that important part. And yeah this is 6.0.0

**Comment by MarjieAVolk** [comment]
Okay cool, yeah this should be fixed already
