### ISSUE TITLE
USER ISSUE: Can't play the game

### ISSUE THREAD

**Issue by HeXX700** [StrangeLoopGames/EcoIssues#24887]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
Report bug: Object reference not set to an instance of an object

**Expected behavior:**
Start a game

**Actual behavior:**
Crashes with a text: Object reference not set to an instance of an object

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the full log of the error and note if its a local or multiplayer game.

**Comment by D3nnis3n** [comment]
Closing due to required information for investigation not provided. Please feel free to open a new issue once you can provide the necessary information,
