### ISSUE TITLE
Freshness handling by a store is not convenient for store owners trying to buy an item.

### ISSUE THREAD

**Issue by rigeborod** [StrangeLoopGames/EcoIssues#24885]
Currently, item freshness serves two purposes related to the store:

1) Any item being sold is checked to ensure its freshness falls within the minimum and maximum acceptable levels. This is appropriate.
2) Any item in storage connected to the store is checked to ensure its freshness falls within the minimum and maximum levels to count towards the inventory needs. This is problematic.

Example:
I intend to purchase some wheat for later use in crafts. I prefer it relatively fresh, so I use the default freshness settings of 50-100%. Someone sells me all the wheat I need at 50% freshness. Within a few minutes, the freshness drops to 49%, and the store begins to purchase more wheat, although I do not need any more since I haven't used the previous batch. I cannot lower the minimum freshness requirement because I need the wheat sold at the shop to be fresh.

Solutions:
1) Simple, but not ideal: Ignore the freshness parameters when calculating the required inventory for items purchased by the store. This solution would satisfy most players, except for resellers who buy and resell the same items at a premium.

2) Better solution: Introduce an additional range for freshness that is used exclusively for calculating the required inventory.

**Comment by D3nnis3n** [comment]
This works as intended, but there is already a suggestion up for the change.

**Comment by rigeborod** [comment]
@D3nnis3n I’m sorry to hear that. Any chance it can be reconsidered? Current implementation is objectively not correct (check the provided example) even if it is not correct by design.

**Comment by D3nnis3n** [comment]
The suggestion hasn't been considered yet, it is tracked and will be considered for a future Update. The purpose of this tracker specifically is only for reporting bugs, which this is not as it works as intended - hence the issue was closed.
