### ISSUE TITLE
When trying to join a town, getting a message that Homestead Support Papers are inside a stake but there aren't any.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24882]
Our server settings makes towns **not spawn any Homestead Support Papers at all** due to Global Federation Setup.
We have _Claim Papers from Skill Scrolls Enabled_ so players are using those inside their Homestead Stakes.
There's a player that wants to join a Town but he's getting this popup that he's supposedly using Homestead Support Paper items:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/4b3f8f08-06b9-408a-8c5f-e78046787851)

But he's not:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/7233edb4-83db-4568-9e60-b7110a82eeca)

**Comment by D3nnis3n** [comment]
Will be fixed via https://github.com/StrangeLoopGames/Eco/pull/13936.
