### ISSUE TITLE
Wondering how and why you don't test anything?

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#24888]
did you test the exhaustion system at all? I don't understand how you can add something this broken....

**Comment by D3nnis3n** [comment]
Please open a bug report with relevant information.

**Comment by Arend90** [comment]
If I where you I would just try to touch your own system.... I can't believe you can take yourself serious or feel that you accomplish anything. Just with a few seconds of touching you can find 5 or more bugs with the system. GAME BREAKING ones. but like you love to say it doesn't affect the majority of the players. You should be deeply ashamed of yourself claiming you released ""improved Exhaustion""... at this point it almost feels like you are intentionally giving up and don't care anymore or just trolling the community....
this system should NEVER been released in this state.

**Comment by D3nnis3n** [comment]
The system has been tested in public playtest and is working fine on multiple servers.
As mentioned before, please have a bug report opened with relevant information.

**Comment by rozczarowanyorzel** [comment]
I don't think it's surprising that he is so disappointed. He's absolutely right that this should never have been released.

each option in the config file causes a different crash.

"AllowPlaytimeSaving": false,
  "MaxSavedHours": 0,

this at 0 = crash
  "BonusHoursOnExhaustionEnabled": 0,

this at 0 = also a crash

the 2 hours bonus you only expect to get on day one.
but if you log out at hour 4.59 you will get the 2 hour bonus again the next day.

Until you're exhausted you'll never get it again. 
That is 14 hours a week more then the players that get exhausted.

and the other report about the time reset point of the day.

this is not > D3nnis3n commented yesterday •
The system has been tested in public playtest and is working fine on multiple servers.

**Comment by Arranoa-jolasten** [comment]
> The system has been tested in public playtest and is working fine on multiple servers. 

If this is how Strange loop games test things then I wonder how delusional those claims for release in December are: https://store.steampowered.com/news/app/382310/view/4174344193742545599?l=english

**Comment by D3nnis3n** [comment]
Please stop abusing bug reports for personal remarks. This tracker's sole purpose is to report bugs with the necessary information in respective separate issues, which none of you have done despite that having been requested in this issue. If bugs are reported, they can be addressed - if they don't surface during public playtesting, they also don't stop a public release - that is normal operation.
