### ISSUE TITLE
USER ISSUE: At random, crafting tasks are displayed wrong and cannot be interacted with

### ISSUE THREAD

**Issue by SilverjetPlane** [StrangeLoopGames/EcoIssues#24886]
When starting certain crafting tasks, sometimes the task icon in the crafting GUI is wrong, the time is always 13 seconds and the repetitions 1234 (at least that is visible), the bars for time and resources are not shown and neither the x to cancel the task (cancelling the task with right-clicking it in the right upper corner of the user GUI worked). The task cannot be interacted with as in adding time or materials, but switching it with other tasks seems to update it and it behaves normally. It could be related to the repetitions of the task, e.g. trying to make 10 mortar works, but 11 does not, or with missing materials for the task. Starting the same task again however works.
May be related to issue #24429, but started with version 0.10.2 (server is running for longer). 

Affected recipes were at least: 
- Mortar at Masonry Table
- Ashlar Sandstone at Advanced Masonry Table (200 repetitions with missing material)

\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
- Start a crafting task (very random if it happens)

**Expected behavior:**
- GUI showing correctly and being interactive

**Actual behavior:**
- GUI not showing, but updating when dragging and switching the tasks

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

First occurrence with the mortar task: 
![20240411140630_1](https://github.com/StrangeLoopGames/EcoIssues/assets/71390652/c843f943-a45b-489b-b562-f794f8516bcf)

Log: 

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14980556/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14980560/Player-prev.log)

**Comment by SlayksWood** [comment]
https://app.clickup.com/t/10591183/ECO-33365

**Comment by SilverjetPlane** [comment]
Happened again today, I took some more screenshots: 
Starting a 3x Sweet Salad at the Kitchen (all ingredients missing): 
![20240418211612_1](https://github.com/StrangeLoopGames/EcoIssues/assets/71390652/9d333495-6093-4c85-8847-8a0834921deb)
After starting the tasks for the missing ingredients, the upper right icon updates, but not the faulty task in the Kitchen GUI: 
![20240418211715_1](https://github.com/StrangeLoopGames/EcoIssues/assets/71390652/3364de9b-9e8b-43ac-bf3b-ad22e6902e2c)
Adding a second task to the kitchen (Hosomaki) updates the Sweet Salad task: 
![20240418211731_1](https://github.com/StrangeLoopGames/EcoIssues/assets/71390652/d1179c7e-4e51-4fdd-a390-2df1930a2831)
In the log (which I cannot upload for some reason) three NullReferenceException crashes are mentioned, two concerning Minimap, one resembles the WorldMarker one that can also be found in the log uploaded on April 15th.

**Comment by SilverjetPlane** [comment]
Still an issue in update 11
![20240817022501_1](https://github.com/user-attachments/assets/5a5fea90-1226-47d5-b898-1ce26e9ca2bd)

**Comment by D3nnis3n** [comment]
This was fixed in 11.1.
