### ISSUE TITLE
USER ISSUE: Law activation on non-citizen outside of town's influence

### ISSUE THREAD

**Issue by Kyanto** [StrangeLoopGames/EcoIssues#24890]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
1. Create town A and town B
2. Set up a store in town B
3. Create a law on town A which says "on money transfered, tax the citizen who transfered the money"
4. Have a citizen of town A sell something in the store of town B 

**Expected behavior:**
The owner of the store in town B should not be taxed since he's not a citizen of town A and his store isn't under the influence of town A

**Actual behavior:**
The owner of the store in town B get taxed by the law of town A
(if the tax amount is set to "wealth of citizen", someone can grab all the money of people outside of his town just by selling them 1 item)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Vanilla server, no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15000937/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15000938/Player.log)

**Comment by D3nnis3n** [comment]
Are you sure it's actually taxing the owner in a technical sense? A town always has jurisdiction over their citizens, even outside the influence. Transfer money is not a location based action as there is no location affiliated with it, so the location cannot be used - only citizenship. If a citizen of town A now transfers money to someone else in whatever way, that money will be taxed. So if the transfer from Citizen A to Citizen B was taxed (money reduced), that was working as I would have expected.

Maybe you got a screenshot?

**Comment by D3nnis3n** [comment]
Oh, I just noted you talked of selling to the store, e.g. a transfer from the store owner to the citizen. So do I understand correctly that what is happening is that the law from town A triggers due to the store interaction being started by its citizen, then taxing the store owner from town b as he is the sending participant in the action due to things being sold to him?

**Comment by D3nnis3n** [comment]
Will be fixed in the next Maintenance Update (not Hotfix, as it needs more extensive testing) via https://github.com/StrangeLoopGames/Eco/pull/13950.
