### ISSUE TITLE
Exhaustion hours incorrectly refreshed and capped when AllowPlaytimeSaving is false

### ISSUE THREAD

**Issue by bkromberg** [StrangeLoopGames/EcoIssues#24892]
**When AllowPlaytimeSaving is false, the following issues occur when using RefreshLocalHours / RefreshLocalMinutes:**

**Issue 1:** 
- The exhaustion hours cap changes during midnight according to the system clock, not during refresh time.

Example: 

- A server has an offset of 18 hours (6:00pm). 
- It assigns 6 hours of playtime for Sunday, and 3 hours of playtime on Monday.
- A player is playing Sunday, and logs in at 11:55pm. They have 6 hours of playtime. 
- At midnight, this player now has 3 hours of playtime, because the playtime cap is now 3 hours for Monday, despite the refresh time being 6:00pm.

**Issue 2:**

- Players who are not logged in between the offset hour and midnight according to the system clock, will not receive exhaustion time.

Example:
- A server has an offset of 18 hours (6:00pm). 
- It assigns 6 hours of playtime for Sunday, and 3 hours of playtime on Monday.
- A player is playing Saturday, and plays 6 hours becoming exhausted.
- This player does not log in again until Monday, at 1:00am. 
- The player does not receive time from Sunday, and remains exhausted until 6:00pm Monday.
- (They only receive that time on Monday if they log in after 6pm, and before midnight)

### Reproduction:

1. Set Exhaustion.eco to:
`  "RefreshLocalHours": 23,
  "RefreshLocalMinutes": 59,
  "MondayExhaustionRefreshHours": 3.0,
  "TuesdayExhaustionRefreshHours": 3.0,
  "WednesdayExhaustionRefreshHours": 3.0,
  "ThursdayExhaustionRefreshHours": 3.0,
  "FridayExhaustionRefreshHours": 6.0,
  "SaturdayExhaustionRefreshHours": 6.0,
  "SundayExhaustionRefreshHours": 6.0,
  "AllowPlaytimeSaving": false,
  "MaxSavedHours": 15.0,
  "AllowExhaustionPauseOnRest": true,
  "BonusHoursOnExhaustionEnabled": 2.0,
  "BonusRetroactiveHoursAfterStart": false,
`

2. Enable exhaustion in Features.eco
3. Set system Clock to 11:50pm on Sunday
4. Start Fresh Server
5. Log in Client A
6. Log in Client B
7. Use /exhaust on both client A & B. (Prior to 11:59pm)
![Step1](https://github.com/StrangeLoopGames/EcoIssues/assets/111952428/90ab8680-38f2-4866-b6fd-266e7f0d8483)
8. Log out Client B (Prior to 11:59pm)
9. At 11:59 Client A will receive 6 hours.
![Step2](https://github.com/StrangeLoopGames/EcoIssues/assets/111952428/8ff2e1d5-8ac6-4993-99dc-2d934dafd2d8)
10. At Midnight the UI will not display the change in hours even though it has occurred. Log out of Client A. 
![Step3](https://github.com/StrangeLoopGames/EcoIssues/assets/111952428/6b0dbe7b-cc63-46e9-bbed-265c86eb3f98)
11. Log both Clients in after midnight.
12. Client A now has 3 hours. Client B will remain exhausted. 
![Step4](https://github.com/StrangeLoopGames/EcoIssues/assets/111952428/61bba6a8-7772-4cf6-9162-ef814aa7cf71)

SLGID: slg222993

**Comment by Arranoa-jolasten** [comment]
[D3nnis3n](https://github.com/D3nnis3n) commented [yesterday](https://github.com/StrangeLoopGames/EcoIssues/issues/24888#issuecomment-2058596826) • 
The system has been tested in public playtest and is working fine on multiple servers.

**Comment by D3nnis3n** [comment]
Both are going to be fixed by https://github.com/StrangeLoopGames/Eco/pull/13940

**Comment by D3nnis3n** [comment]
Has been merged, hence closing.

**Comment by kernohad** [comment]
I think Issue 2 above may still be an issue. I have a player on my server who skipped an entire day of playing and it appears did not get the 1 hour he was supposed to get that day. 

We have Refresh Local Hours = 2 so the refresh happens at 2am local time. 

Is there any logs to show Exhaustion time granted/used/rested I can look at to try to confirm if this happened to us? I got all the players login/logout logs, but that does not include if they rested as we have the Allow Exhaustion Pause On Rest = true.
