### ISSUE TITLE
USER ISSUE: Printing Press

### ISSUE THREAD

**Issue by LightOracle** [StrangeLoopGames/EcoIssues#24898]
\
**User Id: (slg184948)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
1. Printed a picture2. Renamed it.3. Pressed enter to save the name and it printed a 2nd picture using up 2 printing supplies.

**Expected behavior:**
One picture printed.

**Actual behavior:**
Two pictures printed

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide a video of the problem if you can.

**Comment by LightOracle** [comment]
Pressing the enter button prints a picture. This could lead others to accidentally use printing supplies after changing the name of the picture. Most people press enter to set the name change.

**Comment by D3nnis3n** [comment]
Fixed in Update 10.3 via https://github.com/StrangeLoopGames/Eco/pull/14010.
