### ISSUE TITLE
Linux ,Everything turns pink when using fire 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2490]
http://ecoforum.strangeloopgames.com/topic/2887/linux-mint-everything-turns-purple-when-fire

**Comment by MarjieAVolk** [comment]
I believe this will be fixed in the next staging build (sounds like the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/2222)

**Comment by noblackthunder** [comment]
ohhh .. .naming .. good naming would be cool .. like Pink.. or linux issue =P okey

**Comment by Fank** [comment]
No its domination purple :D

**Comment by robbanl** [comment]
Thanks guys for creating this :-) I can be in assistans of testing if needed. Tried the staging build 2 days ago, but there were no test servers available so I couldn't really verify :-)

**Comment by Fank** [comment]
Eco.fankserver.com always latest staging build

**Comment by robbanl** [comment]
@Fank Great, I will give that server a try. I'm guessing there is no way to cheat to create a fire where I am? Or is it possible to modify config file to get allowed into an older server where I got my fire and trouble? :)

**Comment by Fank** [comment]
@robbanl thanks for validating :+1:
