### ISSUE TITLE
Game Launch Crash

### ISSUE THREAD

**Issue by CrispOwly** [StrangeLoopGames/EcoIssues#24909]
When i am Trying to launch the game on steam. It opens, I see the loading sign in the bottom left and sometimes I see the photo of the city, then the games turns blue and it stays like that until I click on it and it says that the game is not responding. I'll get the sound playing but nothing more.

It does not help waiting and in the end crashes. I have tried doing different versions but that does not help and the same thing just keeps happening. I have also tried verifying integrity of files and reinstalling it, but again nothing.

![image_2024-04-25_142059132](https://github.com/StrangeLoopGames/EcoIssues/assets/164175771/0ef41ab6-56ba-400a-93f2-5414951ab332)

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15109634/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15109637/Player.log)

**Comment by D3nnis3n** [comment]
Neither logs contain an error, so there is a problem happening before it even gets to Eco.
Check you have installed the most recent drivers. Try to disconnect any virtual and real cameras from the PC.
Make sure you have installed VC++ Redistributables in most recent version: https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by CrispOwly** [comment]
> Neither logs contain an error, so there is a problem happening before it even gets to Eco. Check you have installed the most recent drivers. Try to disconnect any virtual and real cameras from the PC. Make sure you have installed VC++ Redistributables in most recent version: https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Hey So i did all the stuff, Made sure everything was updated of drivers, disconnected the cam's and went thru your link to make sure i had the right one installed. downloaded the x64 But it's still not working

**Comment by D3nnis3n** [comment]
Anything in Windows Event Log?

**Comment by D3nnis3n** [comment]
It does look like there is an issue with some webcam (virtual or real) driver. The logs end when it tries to find a camera and we have seen similar issues with outdated, very old or incompatible cameras before. A good start for further investigation would hence to be remove all traces of any camera software and drivers you have installed one by one until you find the culprit.

**Comment by D3nnis3n** [comment]
Given there was no further response, I'm assuming the issue is resolved. If not, please reach out to support@strangeloopgames.com, as this doesn't look like a bug but a problem with drivers / hardware as mentioned above.
