### ISSUE TITLE
Joining towns with claim papers from skill scrolls the server crashes

### ISSUE THREAD

**Issue by yourihemelrijk** [StrangeLoopGames/EcoIssues#24906]
if a player joins a town and this player already has a homestead claim stake with claim papers (which the player got from learning skill scrolls) in it. The Server will crash. This issue only happens with those claim papers the other 2 types (gotten from a foundation)

to go around this bug:
If you want someone to join your town, Than replace the papers (from skill scrolls) with both the town and homestead papers found in your settlement foundation. Than after the player has joined you can switch the papers back to the original ones

**Comment by D3nnis3n** [comment]
Should be fixed in next Update via https://github.com/StrangeLoopGames/Eco/pull/13954, please reopen if it persists then.
