### ISSUE TITLE
player gets teleported underground

### ISSUE THREAD

**Issue by pauliukas97** [StrangeLoopGames/EcoIssues#24904]
![20240422220048_1](https://github.com/StrangeLoopGames/EcoIssues/assets/167813651/b38bfbb9-c043-4e08-a0fc-9581174d9276)
player gets stuck in corner by crushed limestone and then if there is a cave under it teleports you there i was teleported 50 blocks underground

**Comment by D3nnis3n** [comment]
Same cause as https://github.com/StrangeLoopGames/EcoIssues/issues/24352
