### ISSUE TITLE
USER ISSUE: Fishing Crashes server

### ISSUE THREAD

**Issue by cooljaz** [StrangeLoopGames/EcoIssues#24908]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
Fishing regularly
Fishing line has fishFishing line snaps
Server Crashes

**Expected behavior:**
Not crashed server and let me continue fishing	

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the server logs of such a server crash, see here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

**Comment by cooljaz** [comment]
[log_240424090033.log](https://github.com/StrangeLoopGames/EcoIssues/files/15139122/log_240424090033.log)

**Comment by D3nnis3n** [comment]
That logfile contains no crash.

**Comment by cooljaz** [comment]
Hmm I apologize than I am new to the game and when it had popped up the server crashed; I assumed it was because of the fishing because the other person I was playing with also reconnected with me. I have since been playing and realize that it could have been a disconnect between me and the server.

**Comment by D3nnis3n** [comment]
That is also what the message itself suggests, I do not see any hint for an issue there.

If you happen to get this repeatedly for fishing in a reproducible manner, please feel free to open a new issue and we'll take a deeper look, but from what is here so far there is no hint to an issue existing.
