### ISSUE TITLE
USER ISSUE: Can't play on my local server

### ISSUE THREAD

**Issue by Kumik50** [StrangeLoopGames/EcoIssues#24914]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
I was playing on my singlepalyer world when it suddently crashed after I tried crafting a bookcase, and then a shelf cabinate. Before this I occasionally had problems when crafting, as it showed a campfire icon that only turnd into the proper object when I added another project. I also couldnt see my claimed plots when holding tha claiming tool.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
You were prevented from playing on this server by law:
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no mods installed and I'm playing on 10.2.1

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15167093/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15167121/Player.log)

**Comment by D3nnis3n** [comment]
Can you attach the savegame? This message appears when a law is being made that contains a play prevention clause - which by default is disabled on servers, especially on singleplayer.

**Comment by Kumik50** [comment]
I tried but this file type isn't supported here. When it comes to server configs the only one I changed is the amount of players needed to have a town. I also don't remeber creating a law that had both play and prevent

**Comment by D3nnis3n** [comment]
You can put the .db and .eco file into a .zip and upload here or on any website that allows us to download with an account, like Google Drive.

**Comment by Kumik50** [comment]
Alright, here you go.
[World data.zip](https://github.com/StrangeLoopGames/EcoIssues/files/15169073/World.data.zip)

**Comment by D3nnis3n** [comment]
I was able to login fine into that world and it seems there is no law that would prevent play. Just to make sure, what does the entry   "AllowLawsToPreventLoginOrPlay" in /Steam/steamapps/common/Eco/Eco_Data/Server/Configs/Civics.eco say for you? If it says true, try changing to "false".

**Comment by Kumik50** [comment]
AllowLAwsToPreventLoginOrPlay is set to false, and despite updating my game version to the newest one I still can't load. However I think I found something interesting at the end of the server log.
[Server Log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/15177497/Server.Log.txt)

**Comment by D3nnis3n** [comment]
Can you try rolling back to a backup created before that crash happened - it might have corrupted your player data.
You can find backups in /Steam/steamapps/common/Eco/Eco_Data/Server/Storage/Backups - copy over the .db and .eco file from a backup folder that was before that crash to the Storage folder and try again.

**Comment by Kumik50** [comment]
That seems to be the case. I rolled back and it load fine. You can close the issue if you want, because I'm not sure if you only close it when the cause was fixed. Other then that my problem might have something to do with the issue #24886

**Comment by D3nnis3n** [comment]
Thanks for getting back, server crashes always have the risk of corrupting data in some form as they shouldn't happen. The real interesting part would be the server log of when the crash actually happened (if it was a server crash), that would potentially allow to prevent this to begin with. Do you by chance have any data on the crash that caused it to start with? Otherwise I'd indeed close the issue, as data corruption resulting from a crash is not preventable on persistently saving worlds and that's what the backups are for. Preventing the original crash if possible would be good, though.

Your description sounds more like it could have been a server crash instead of a client crash.

**Comment by Kumik50** [comment]
Sadly I don't have the first log, but it I remember that I was crafting myself a bookcase and a shelf cabinet for the newly build rooms, and then experienced the campfire project issue. Thankfully after playing a bit the crash hasn't happened again. Good luck finding that problem then.

**Comment by D3nnis3n** [comment]
Alright, thanks. It's unlikely to find that issue without having logs, especially as just doing what you describe doesn't cause any issue in local testing, but usually when crashes happen they do get reported, so if it happens for anyone else I do assume it will be reported :)
