### ISSUE TITLE
crash every 2 minutes

### ISSUE THREAD

**Issue by LogicLH18** [StrangeLoopGames/EcoIssues#24911]
[Uploading Player.log…]()

**Comment by LogicLH18** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15142371/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15142372/Player-prev.log)

**Comment by LogicLH18** [comment]
![Uploading IMG_0817.jpg…]()

**Comment by LogicLH18** [comment]
![IMG_0817](https://github.com/StrangeLoopGames/EcoIssues/assets/168351607/0a08e3cc-50f1-4730-925b-b1f06ce7f637)

**Comment by D3nnis3n** [comment]
Could you please attach the crash dumps saved on your PC for Eco?

To do so, open the program "run", enter "%UserProfile%\AppData\Local\Temp\Strange Loop Games\Eco" and package the contained .dmp files, uploading them here.

**Comment by D3nnis3n** [comment]
Closing due to necessary information not provided. Please feel free to open a new issue when you can provide the requested information :)
