### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by SkandalNudel** [StrangeLoopGames/EcoIssues#24918]
Steps to Reproduce:
I was playing yesterday in a new world without any issues. Today i can't even load it.

The following error message popped up:
App authentication failed: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.

[log_240502071453.log](https://github.com/StrangeLoopGames/EcoIssues/files/15192175/log_240502071453.log)

Hilfe ich bin ein Lappen und versteh garnix D:

**Comment by D3nnis3n** [comment]
Der Fehler sagt, dass der Server sich nicht mit unseren Backend-Servern verbinden kann.

Das kann an Sicherheitssoftware oder Netzwerkproblemen liegen - es kann aber auch einfach sein, dass Cloudflare deine IP-Range aus Sicherheitsgründen vorübergehend blockiert hat. Du kannst versuchen entsprechende Software abzuschalten oder einen VPN zu benutzen.

**Comment by D3nnis3n** [comment]
Closing due to no further response and no hint at a bug.
