### ISSUE TITLE
Game crashed while playing.

### ISSUE THREAD

**Issue by GauHelldragon** [StrangeLoopGames/EcoIssues#24912]
Game crashed seemly at random after a while of playing. 
Was constructing some blocks at the moment.
Version : 10.2.1

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15145037/Player.log)

**Comment by GauHelldragon** [comment]
Was playing on official MP server Dusky Robin.

**Comment by GauHelldragon** [comment]
When I logged back in, I had somehow fallen off the platform I was building on, even though I seemed to be standing on it before crash.

**Comment by D3nnis3n** [comment]
Could you please attach the crash dumps saved on your PC for Eco?

To do so, open the program "run", enter "%UserProfile%\AppData\Local\Temp\Strange Loop Games\Eco" and package the contained .dmp files, uploading them here.

**Comment by GauHelldragon** [comment]
[Crash_2024-04-20_005910548.zip](https://github.com/StrangeLoopGames/EcoIssues/files/15172132/Crash_2024-04-20_005910548.zip)

**Comment by GauHelldragon** [comment]
erm ignore filename date on zip file, its actually 4/28/2024, not 4/20

**Comment by D3nnis3n** [comment]
The crash dump doesn't refer to Eco, but an issue with DirectX. We're looking into if that has anything to do with Eco and will get back afterwards.

**Comment by D3nnis3n** [comment]
We've not been able to make out any reason in Eco. Does this issue happen often or was it a one-off?

**Comment by D3nnis3n** [comment]
Just checking if you saw my last message, DirectX issues typically hint at incompatibilitites in drivers - so if you have these regularly, a full uninstall of graphics drivers with DDA and then a fresh reinstall should be the first thing tried.

**Comment by GauHelldragon** [comment]
Thanks for the advice! I have only seen this happen once, but ill give that
a try if happens more often.

**Comment by D3nnis3n** [comment]
I'm closing this issue for now, as there is no reproduction case and seemingly not a regular issue either.
If you get it again or it ever becomes something not a one-off, please open a new issue.
