### ISSUE TITLE
Unable to join a server after server restart

### ISSUE THREAD

**Issue by Xenoun1234** [StrangeLoopGames/EcoIssues#24916]
Was playing on a server, server hit a scheduled restart and after it came back up im unable to log in.

Have verified integrity of files, reinstalled game, deleted all mods and files in cache in appdata, verified integrity of game files again. Same error still persisting.

Logs attached.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15172508/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15172509/Player-prev.log)

**Comment by Xenoun1234** [comment]
Since posting this ive also uninstalled > deleted files in mods and cache folders > rebooted PC > Installed > get same error when joining server.

**Comment by D3nnis3n** [comment]
What error do you actually get ingame? It is interesting as either it's still too early or I'm not seeing a connection attempt erroring in either log.

**Comment by Xenoun1234** [comment]
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/168605791/59056cec-aa77-44bf-b58d-a595dba18851)


Here's the error

**Comment by D3nnis3n** [comment]
That looks like a rare known issue that should go away after the server restarts another time - can you ask the admin to restart once more to verify?

**Comment by Xenoun1234** [comment]
Server restart fixed it, thanks :)
