### ISSUE TITLE
Slow resizing of UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2491]
UI with a lot of internal elements is slow, because it rebuilds it each tick.  Lets change to a model where it hides the slow internals, so that you can resize it, then it rebuilds them once?  Or otherwise speed this up.
UI affected:
- Economy Viewer
- Objective Dialog
- World Object UI

**Comment by johnkslg** [comment]
Noticed the chat window somehow avoids this

**Comment by MarjieAVolk** [comment]
I think chat window is a lot less complex, in terms of layout

**Comment by johnkslg** [comment]
Economy viewer is way faster to resize now!

**Comment by GophTheGreat** [comment]
Is this still an issue?

**Comment by D3nnis3n** [comment]
Resizing seems smooth for me, reopen if this is not fast enough.

**Comment by mirasrael** [comment]
@D3nnis3n  Did you test Objective dialog with hundreds of users? (i.e. on official server)
