### ISSUE TITLE
Game locked up while bringing up store page.

### ISSUE THREAD

**Issue by GauHelldragon** [StrangeLoopGames/EcoIssues#24915]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15168559/Player.log)

A screenshot of the game while locked up :
![eco1](https://github.com/StrangeLoopGames/EcoIssues/assets/2829037/5be9bcb0-9af0-4071-9d8e-77572a2b5eed)

Playing on version 10.2.2
On Official Server Dusky Robin

**Comment by D3nnis3n** [comment]
Could you please attach the crash dumps saved on your PC for Eco?

To do so, open the program "run", enter "%UserProfile%\AppData\Local\Temp\Strange Loop Games\Eco" and package the contained .dmp files, uploading them here.

**Comment by GauHelldragon** [comment]
[Crash_2024-04-29_040441730.zip](https://github.com/StrangeLoopGames/EcoIssues/files/15172144/Crash_2024-04-29_040441730.zip)
I am not sure if this is the right crash log or not. There were two crash/lock ups at around the same time, and theres only 1 log file. Its possible one wasnt created for it.

**Comment by D3nnis3n** [comment]
Does this happen regularly or was it a one off? We were not able to reproduce this issue, but it might be related to the face tracking feature.

**Comment by GauHelldragon** [comment]
This was not a regular issue, it only happened once. I haven't seen it since.

**Comment by D3nnis3n** [comment]
I see, I'm going to close this issue, assuming that was a hickup. There is no way to reproduce here.

Please feel free to open a new issue when you get another case.
