### ISSUE TITLE
Nylon Futon Couch is Invisible.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24910]
version: 0.10.2.1
issue: Nylon Futon Couch is Invisible.

Steps to reproduce:
1. Place down Nylon Futon Couch

No mods. Clean server files.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/cbe443b3-c505-48a5-a4c9-975bdf0e307a)

**Comment by D3nnis3n** [comment]
Already fixed in 10.2.2.
