### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by DarkestTiger** [StrangeLoopGames/EcoIssues#24928]
\
**User Id: (slg178832)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
1.shop
2.purchase
3.crash

**Expected behavior:**

**Actual behavior:**
다음과 같은 오류 메시지가 떴습니다:
```
Failed to process a request. Probably the client incompatible with the server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24539
