### ISSUE TITLE
Unrestricted Claim Papers stack on top of Settlement Claim papers when Skill Scroll is read and turn into Settlement Claim Papers.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24922]
eco 10.2.2, like in the title
video below:

https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/dcf24137-66db-43f2-ac93-3a16ef525c17

**Comment by D3nnis3n** [comment]
Fixed in Update 10.3 via https://github.com/StrangeLoopGames/Eco/pull/14012.
