### ISSUE TITLE
Unrestricted Claim Papers sold in stores turn into Settlement Specific claim papers.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24921]
10.2.2

This player had 55 unrestricted claim papers in store + 1 settlement specific claim papers but the store shows it has 56 unrestricted claim papers to sell and when you proceed to buy all 56, reading the tooltip that they can be indeed used in anywhere you end up getting 55 unrestricted papers and 1 settlement specific papers.

Demonstrated with the video below:

https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/b32309aa-b4fb-4f9d-ab25-f9d44c93e03a

**Comment by D3nnis3n** [comment]
Fixed in Update 10.3 via https://github.com/StrangeLoopGames/Eco/pull/14013.
