### ISSUE TITLE
USER ISSUE: Printing press 'always working'

### ISSUE THREAD

**Issue by SilverjetPlane** [StrangeLoopGames/EcoIssues#24930]
Minor cosmetic issue and caused by the printing press not being a normal crafting station with tasks (which may be changed in the future), but the repetitive clanking sound becomes annoying after some time. 
\
**User Id: (Not logged user)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
Place printing press in closed room with enough room value

**Expected behavior:**
It should stand still and wait for opening UI, like it does when the room requirements are not set (e.g. placing it outside).
When printing, there could be like a 10-second phase of animated printing press to symbolize it did a printing task.

**Actual behavior:**
It animates and makes a working sound even if not interacted with

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None

**Comment by D3nnis3n** [comment]
This works as intended, I have instead created a suggestion for this internally. Given we do not link animations to anything else but work orders so far and changing that would be a notable technical effort for little benefit, it is unfortunately unlikely that would make it into the game, though.
