### ISSUE TITLE
Ignore Authorization funktioniert nicht

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24936]
User Id: (Not logged user)
Version: 0.10.2.3 beta release-669

Steps to Reproduce:
Erstelle ein Gesetz welches wie im Anhang zu sehen konfiguriert ist. 
![2024-05-14 23_40_56](https://github.com/StrangeLoopGames/EcoIssues/assets/106102715/22ab0fdb-7ae6-4678-9ad1-4fde54dd58f3)

Expected behavior:
Wenn ich auf ein fremdes Stockpile klicke, sollte ich Zugriff haben. 

Actual behavior:
Es kommt die Fehlermeldung "you are not authorized to use..."

Do you have mods installed? Does the issue happen when no mods are installed?:
Nein, Ja

**Comment by D3nnis3n** [comment]
Nicht reproduzierbar - bist du auch Citizen der Stadt in der das Gesetz gilt und befindet sich der Stockpile dort?

**Comment by D3nnis3n** [comment]
Wir haben nun ein Problem in manchen Konstellationen gefunden und gucken uns das an.

**Comment by Enel300** [comment]
> Nicht reproduzierbar - bist du auch Citizen der Stadt in der das Gesetz gilt und befindet sich der Stockpile dort?

Ja es gibt ein Global Settlement in den alle sind. Auch ich. Auch das Ziel-Stockpile. Gesetz gilt ebenfalls für das Global Settlement.

**Comment by D3nnis3n** [comment]
Danke für die zusätzliche Info, Problem tritt tatsächlich aber auch mit Settlements enabled auf.

**Comment by Enel300** [comment]
Danke dir für die schnelle Antwort auch in meinen anderen issues!

Wäre super wenn die Prio für dieses Issue erhöht werden kann da es eine signifkante Funktion als Admin ist, dass man bspw. Tailings aus Stockpiles rausholen muss ohne das komplette Stockpile direkt zu löschen.

**Comment by D3nnis3n** [comment]
Ich habe das tatsächlich bereits als Hotfix vorgemerkt und hoffe, dass es bis morgen behoben werden kann.
Der offizielle Server "White Tiger" braucht das am Freitag eigentlich auch vollfunktionsfähig.

**Comment by D3nnis3n** [comment]
Fixed in Hotfix 10.2.4 via https://github.com/StrangeLoopGames/Eco/pull/14029.

**Comment by Enel300** [comment]
Ich muss hier zu diesem Bug noch etwas hinzufügen, was vielleicht mit dem bug zusammenhängt: 

Man kann, trotz im Gesetz aktiviert, keine World Items in Stockpiles moven. Siehe Screenshot. 

![2024-05-16 23_09_58](https://github.com/StrangeLoopGames/EcoIssues/assets/106102715/f8dae622-4703-45aa-a62a-18ec2daabb0b)

Ich drücke auf einem Nicht-Autorisiertem Lager auf den Button "Consolidate" und bekomme die Fehlermeldung "You dont have access to do that". Ebenfalls kann ich kekne Items raus oder rein moven...?

**Comment by D3nnis3n** [comment]
Ich hab das Problem aber bereits gefunden, deinem Gesetz fehlt "or event Inventory Action" - um Sachen in Storages manipulieren zu können, brauchst du das auch :)
