### ISSUE TITLE
USER ISSUE: Two server crashes with an interval of 4 hours, with the same error

### ISSUE THREAD

**Issue by D3vil787** [StrangeLoopGames/EcoIssues#24933]
Two server crashes with an interval of 4 hours, with the same error
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/82601468/09106646-2bf9-4590-8135-efaa2e3e02d9)

**Comment by D3vil787** [comment]
@TwixterZ 
Thanks for your response!
We read the notes for today's patch, interviewed players and realized what the problem was:
Fixed: Placing a waterpump could lead to a crash or the waterpump becoming invisible, the savegame becoming corrupted afterwards.

**Comment by D3nnis3n** [comment]
Closing due to already fixed in 10.2.3.
