### ISSUE TITLE
USER ISSUE: 	Kann nichts mehr ernten

### ISSUE THREAD

**Issue by Abraxas2206** [StrangeLoopGames/EcoIssues#24934]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
Kann nach einiger Zeit spielen keine Sachen mehr ernten. Die Animation ist zwar da aber ich plücke es nicht. Nach Neustart funktionierte es zwar wieder aber danach fehlten mir die Sachen in meinem Lager. Ca 500 Holzblöcke. 

**Expected behavior:**
Pflücken von Früchten und ähnlichen. Nach erneutem Laden alle Stockpiles leer.

**Actual behavior:**
Nur Animation aber nicht geerntet. Nach erneutem Laden Stockpiles voll

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Gegenstände können aus Lagern nur verschwinden, wenn das Speichern des Weltzustands unterbrochen wurde (und auch dann fehlen nur die letzten 5 Minuten).

Für das Problem mit dem Harvesten würden wir ein Video benötigen. Uns ist nur ein Problem bekannt, bei dem mit Pflanzen nicht mehr interagiert werden kann, aber keines bei dem die Animation noch gezeigt wird.

**Comment by D3nnis3n** [comment]
Da wir leider keine weiteren Informationen bekommen haben, schließe ich diesen Issue.

Solltest du die entsprechenden Informationen in der Zukunft bereitstellen können, öffne bitte einen neuen Issue.
Mit der aktuellen Informationslage ist es uns leider nicht möglich, das Problem nachzustellen oder weiter zu untersuchen.
