### ISSUE TITLE
Anzeigefehler im Wainwright Table wenn Stone Road produziert werden

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24938]
User Id: (Not logged user)
Version: 0.10.2.3 beta release-669

Steps to Reproduce:
Stelle im Wainwright Table Stone Road her. 

Expected behavior:
Unten unter Projects wird korrekt Stone Roads angezeigt. 

Actual behavior:
Falsches Bild. Siehe Screenshot: 
![2024-05-15 00_09_48](https://github.com/StrangeLoopGames/EcoIssues/assets/106102715/a4ddb275-a3e8-44f9-8448-418606f2ea68)

Do you have mods installed? Does the issue happen when no mods are installed?:
Nein, Ja

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24886
