### ISSUE TITLE
Incorrect distance calculation when moving objects across the coordinate border

### ISSUE THREAD

**Issue by Ferrothrax** [StrangeLoopGames/EcoIssues#24941]
When using the Ctrl+LMB move function to move an object the distance is incorrectly calculated when moving it across the coordinate border - e.g. when moving it from x=1 to x=1399 the distance will be calculated as 1398m instead of 1m. This makes it impossible to move objects across the border even though the actual distance moved is within the 20m limit.

![20240518085342_1](https://github.com/StrangeLoopGames/EcoIssues/assets/3790114/3caa2a89-767a-40ef-8d9f-c4fbd7cd2181)

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
