### ISSUE TITLE
USER ISSUE: E Use when hovering over Laboratory is very far off screen.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24949]
\
**User Id: (slg207757)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Place Laboratory2. Hover over it

**Expected behavior:**
E Use is above Laboratory

**Actual behavior:**
E Use is somewhere faaar away off screen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by padmanek** [comment]
After "chasing" the E Use a bit, found out it's pointing at (0, 0, 0).
![Eco_93a26gtiFd](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/7ddd3742-fc33-46d3-a98b-a9985d60cae0)

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
