### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by sad-username-231** [StrangeLoopGames/EcoIssues#24943]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. начать игру
2. подождать минуту
3. увидеть справа снизу красный значек о проблеме с соединением
4. вылететь с сервера

**Expected behavior:**
не должно быть таких явных проблем с соединением с самим собой

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
нет и да

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, this doesn't look like a bug but a support issue. In any case provided information is not sufficient to address.
