### ISSUE TITLE
Disabling InitialSpawnSelection triggers a strange log-in bug.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#24942]
This config setting was completely bugged since 10.0 until 10.2 which I reported and [JohnK put a task for fixing it](https://discordapp.com/channels/254025510651297802/1192163429918712030/1200822626889781288).
Now since it was allegedly fixed in 10.2 we went ahead and tried 2 cycles with it. And then strange things started happening:

How to setup the bug:
InitialSpawnSelection set to false.

The bug:
If you logged out above any kind of cave, natural or dug, or inside any kind of building, upon log-in you will be teleported either inside that cave or on the roof of that building. Eventually to another floor of that building. Sometimes you'll just crash on log-in.

On my video here the bug happens on **2nd, 4th and 6th** relog but **on a live server it pretty much happens 9/10 times.**

https://www.youtube.com/watch?v=8VU8xgiQSIQ

On the video I log into a freshly generated world, you can skip the room building if u go to 1:30

Mods? No.
Version? Since 10.2, currently10.2.4

_**Bonus bugs:**_

Setting InitialSpawnSelection to true on a server that has been running for a while without it will trigger on Everyones next log in the window to choose a spawn point as if they just joined the server for the first time!! Players can chose to spawn in a completely diffrent settlement than they are currently in and they will magically join it and now their homestead in their old settlement will show influence from the new settlement:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/3693125/ef4053c1-6426-4bf9-84ec-4e76c5073fee)

**Comment by padmanek** [comment]
@TwixterZ I think https://github.com/StrangeLoopGames/Eco/pull/14104 will fix the **Bonus** issue I've listed. 
Any word about the main issue?

**Comment by D3nnis3n** [comment]
Not reproducible anymore in staging, hence closing as fixed.

"Bonus issue" is fixed in 10.3 via https://github.com/StrangeLoopGames/Eco/pull/14080.
