### ISSUE TITLE
USER ISSUE: mittelgroße werft lässt sich nicht platzieren

### ISSUE THREAD

**Issue by AniKitsune** [StrangeLoopGames/EcoIssues#24945]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
habe eine Plattform gebaut, 10x17 Blöcke groß, versuchte es dadrauf zu platzieren, aber entweder er meckert rum, dass es nicht solide platziert wurde oder er meckert rum, dass es nicht im wasser steht. Es ist ein Block unterschied.

**Expected behavior:**
Es sollte platziert werden

**Actual behavior:**
es platziert sich nicht und ich weiß nicht warum

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by AniKitsune** [comment]
![20240520170859_1](https://github.com/StrangeLoopGames/EcoIssues/assets/163330327/f0e9669a-268b-4ecb-b9c4-d481cb23958e)
![20240520170902_1](https://github.com/StrangeLoopGames/EcoIssues/assets/163330327/e1c4a757-0bf3-42dc-9f46-86001b07721b)

**Comment by D3nnis3n** [comment]
Das ist kein Fehler, die Fehlermeldungen die du bekommst sind korrekt - die Front der Werft muss im Wasser sein, der Rest an Land **auf der selben Ebene**. Wasser und Land muss auf der selben Höhe sein, wie hier:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/1f5b0fd9-ebf1-4c28-80b1-f661cbe8af65)

Deine Plattform müsste also _im_ Wasser sein, sieht auf dem Bild aber so aus, als wäre sie eins darüber.

**Comment by AniKitsune** [comment]
Hey Dennis,ahh, okay das war mir nicht klar aber macht Sinn. Danke für die schnelle Antwort! :)-AnnikaAm 20.05.24, 17:28 schrieb Dennis Scholz ***@***.***>:

   
  Das ist kein Fehler, die Fehlermeldungen die du bekommst sind korrekt - die Front der Werft muss im Wasser sein, der Rest an Land auf der selben Ebene. Wasser und Land muss auf der selben Höhe sein, wie hier: 
  image.png (view on web) 
  Deine Plattform müsste also im Wasser sein, sieht auf dem Bild aber so aus, als wäre sie eins darüber.
