### ISSUE TITLE
USER ISSUE: Can´t place Start Camping Tent

### ISSUE THREAD

**Issue by burnsy85** [StrangeLoopGames/EcoIssues#24940]
\
**User Id: (slg103730)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Joined on server after Update 10.2.4 and Technikfragen got a Tent that is not placeable, is also repeatable for me so it should be the item itself. 

**Expected behavior:**
Be placeable

**Actual behavior:**
Shows Errormassage only placeblae from Test Client 0

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes - don´t know / just a player no admin :)

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you post the exact error message and potentially ask your admin to provide the savegame - and your exact username ingame?

Not reproducible on any world we have.

**Comment by burnsy85** [comment]
can be closed - solved it with server admin (mod related) please close and sorry! :)

**Comment by D3nnis3n** [comment]
Hello @burnsy85,
could you let us know about which mod caused the issue?
