### ISSUE TITLE
USER ISSUE: ich kann keine Marker mehr anklicken

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24954]
\
**User Id: (slg62171)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
ich habe mir Marker gesetzt und diese sind nach einiger Zeit nicht mehr anwählbar oder löschbar. 

**Expected behavior:**
man sollte Marker ein und ausschalten sowie löschen können

**Actual behavior:**
Marker lassen sich nicht aktivieren oder löschen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein, ja

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Lässt sich leider nicht reproduzieren, benötigen einen Reproduction-Case.

**Comment by D3nnis3n** [comment]
Da hier keine Reproduzierbarkeit vorliegt und auch keine Reproduktionsschritte zur Verfügung gestellt werden konnten, schließe ich diesen Issue als nicht reproduzierbar. Sofern es dir möglich ist, Schritte zur Verfügung zu stellen, mit denen wir das Problem ebenfalls auslösen können, erstelle bitte gerne einen neuen Issue. Ohne Reproduzierbarkeit können wir das Problem leider nicht nachvollziehen und entsprechend auch nicht beheben.

**Comment by Enel300** [comment]
Ich kann nichts anderes machen als es so zu beschreiben. Ich kann es dir ingame zeigen per Bildschirmübertragung. Aber Marker lassen sich nicht deaktivieren oder löschen. Dies muss behoben werden.

**Comment by D3nnis3n** [comment]
Das hilft uns leider nicht weiter - wir müssen in der Lage sein, einen Fehler selbst zu reproduzieren, um ihn beheben zu können. Es gibt außer von dir auch keine weiteren Meldungen zu diesem Problem, entsprechend können wir ohne Schritte zur Reproduktion auf einem beliebigen System hier nichts weiter tun.
