### ISSUE TITLE
USER ISSUE: Large Corruagted Steel Door kann man nicht von unten bedienen

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24959]
\
**User Id: (slg62171)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Baue eine Mauer oder ein Zaun der drei Blöcke hoch ist. Setze dann ein Large Corrugated Steel Door rein. Dieses kann man nicht von unten bedienen. Man muss immer hochspringen. 

**Expected behavior:**
Das Tor sollte von unten erfassbar sein damit man es schließen kann. 

**Actual behavior:**
Man bekommt keinen Erfassungspunkt und kann das Tor nur durch hochspringen schließen. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no,yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
