### ISSUE TITLE
USER ISSUE: Standing Glass Sign Anzeigefehler mit Icons

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24957]
\
**User Id: (slg62171)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Platziere ein Standing Glass Sign. Füge ein Icon als Text hinzu wie bspw. "ecoicon name="Carpenter" (ich kann hier nicht den genauen Code rein posten da er von github gelöscht wird)

**Expected behavior:**
Das Icon sollte aus egal welcher Entfernung zu sehen sein. 

**Actual behavior:**
Das Icon ist nur zu sehen, wenn man dicht dran steht. Ansonstn verschwindet es. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Der Fehler ist bereits bekannt (Intern: ECO-31443). Da er nur die niedrigste Priorität hat, ist mit einer Behebung innerhalb der näheren Zukunft leider nicht zu rechnen.
