### ISSUE TITLE
USER ISSUE: Distribution Station Spam

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24956]
\
**User Id: (slg62171)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Platziere eine Distribution Station. Füge Items hinzu. 

**Expected behavior:**
Die Meldung "Collect Items..." sollte einmal kommen. Wenn man diese Items in die Station legt, sollte der Marker und die Meldung verschwinden. 

**Actual behavior:**
Der Marker erscheint immer wieder. Obwohl Sachen in die Station gelegt werden verschwindet er nicht. Manuelles löschen des Markers bringt auch nichts. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Der Marker zeigt an, dass an der Station Items abgeholt werden können, mit reinlegen hat das nichts zu tun. Mir ist nicht ganz klar, was der Fehler sein soll - die Station soll per Marker anzeigen, dass sie sich dort befindet und Gegenstände dort abgeholt werden können.

**Comment by Enel300** [comment]
Richtig, so habe ich es auch verstanden. Ich selbst habe allerdings die Station aufgebaut und die Items hinzugefügt und bekomme nach jedem Neustart des Spiels immer wieder die Meldung "Collect Items" angezeigt. Ebenso lässt sich der Marker nicht entfernen. Mich interessiert der Marker nicht und ich kann ihn nicht löschen. Das ist der Fehler.

**Comment by D3nnis3n** [comment]
Ich verstehe - das funktioniert leider wie es soll. Bestimmte Marker sind System-Marker und können nicht gelöscht werden, die Marker für Work Parties / Orders funktionieren ähnlich. Es gibt aber bereits einen Vorschlag diese Funktion zu verbessern, ob und wann das umgesetzt wird, kann ich dir aber leider nicht sagen.
