### ISSUE TITLE
USER ISSUE: White tiger server sending errors.

### ISSUE THREAD

**Issue by Felddagryph** [StrangeLoopGames/EcoIssues#24950]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. click the Continue option for the white tiger server.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.Contracts.ContractClausePayment.get_PaymentTaxString()
   at Eco....

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Whatever ones White Tiger uses.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/15421554/Player.log.copy.txt)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15421560/Player-prev.log)

**Comment by D3nnis3n** [comment]
This should already be resolved.
