### ISSUE TITLE
Moving vehicles with the hammer 

### ISSUE THREAD

**Issue by rickleberg** [StrangeLoopGames/EcoIssues#24955]
I had to move my powered cart with the hammer and this weird bug happened where if i moved it to the right it would say 0.1m 19 calories, but if i wanted to move it to the left it would say 1599m +30k calories required. 

![20240529012102_1](https://github.com/StrangeLoopGames/EcoIssues/assets/47508156/31c0ded2-4862-4ed7-845b-764afd290225)
![20240529012100_1](https://github.com/StrangeLoopGames/EcoIssues/assets/47508156/90d341ca-0fa7-41b0-9545-d52e3a24c65d)

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24941
