### ISSUE TITLE
weight bug in stores and can only sell one stack and when buy more then one stack get only one

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2495]
https://cdn.discordapp.com/attachments/367065974324854794/367070405887918100/unknown.png
https://cdn.discordapp.com/attachments/367065974324854794/367070670192115715/unknown.png
https://cdn.discordapp.com/attachments/343053904608493568/367071311647866880/unknown.png
stores have a few problems with stacking and weight @MarjieAVolk @johnkslg

**Comment by Arend90** [comment]
you can only sell 20 and not 22 then she made a order that takes the stone then i can sell an other 20 but when there is no order and there is one stack in a stockpile you can never sell anymore

**Comment by Arend90** [comment]
ow yeah weight bug, when you sell anykind of weight form you backpack in stays in the backpack after selling, we avoid it by selling true carts but then i tried stone and then it got the cart to bug with weight. so we sell hand items true hand backpack items true carts to workaround it, bug "solved" by a server restart

**Comment by MarjieAVolk** [comment]
I'm not having any trouble buying/selling more than one stack at a time.  You can only carry one stack at a time in your personal inventory though - does the seller have any inventories linked to the store, on the store's Storage tab?

As for the weight bug, this should already be fixed in the current staging build.

**Comment by Arend90** [comment]
storage is linked
because i can sell 20
 but with huckleberry you can hold more then 100 and in carts you can hold more then 20

**Comment by johnkslg** [comment]
http://ecoforum.strangeloopgames.com/topic/2886/store-stockpiles-not-accepting-more-than-10-blocks-server-bug
I think this is a discussion of this bug

**Comment by Arend90** [comment]
when there is no order auto taking it i can drag it out of the linked stockpile/chest then they can sell an other stack

**Comment by Arend90** [comment]
and ofcourse when i buy 500 huckleberry link the cart  i only get 100 and not 5 stacks of 100

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/31362745-6ed386e6-ad5a-11e7-9e49-868b83370c1c.png)

![image](https://user-images.githubusercontent.com/31536813/31362761-82edc6f0-ad5a-11e7-8e9d-2e709a965f5e.png)

![image](https://user-images.githubusercontent.com/31536813/31362783-972ec394-ad5a-11e7-91e8-2b4e1c54f198.png)

**Comment by MarjieAVolk** [comment]
Yeah I'm definitely not seeing this issue on master right now.  It might already be fixed in the current staging build.  I assume you're on 6.0?

**Comment by Arend90** [comment]
greenleaf 6.0 yeah

**Comment by Arend90** [comment]
think you have the save of last week

**Comment by MarjieAVolk** [comment]
Okay I'll look at it in the greenleaf save

**Comment by MarjieAVolk** [comment]
Yeah I don't see this problem there either - I couldn't find the store pictured in your screenshot, but I sold 150 huckleberries at one of your stores, no problem.  So I think this is fixed in the current staging build.

**Comment by Arend90** [comment]
lovely thanks for looking at it

**Comment by MarjieAVolk** [comment]
Uh oh wait a sec, I just reproed it!  Buying 101 meat and selling 101 huckleberries at your store, it thinks my inv is full but it's not >>

**Comment by MarjieAVolk** [comment]
Okay yeah, we're good, I'm gonna close this :) :P
