### ISSUE TITLE
USER ISSUE: Error	

### ISSUE THREAD

**Issue by Chellieeeeee** [StrangeLoopGames/EcoIssues#24951]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
The game does not want to load into any server

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Error happened during processing incoming message
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24380

**Comment by Chellieeeeee** [comment]
Good day.
How can I fix the problem?

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com for deeper investigation into your specific issue.
