### ISSUE TITLE
USER ISSUE: dropped underground when placing a stockpile on solid ground

### ISSUE THREAD

**Issue by Dubie7910** [StrangeLoopGames/EcoIssues#24958]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
I don't know how you would reproduce this - I might have been in the way of the stockpile, but I'm used to it either building around Me (empty) or saying blocked by player		

**Expected behavior:**
Placed on ground

**Actual behavior:**
It dropped me undergound to alt 7

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Don't know and Don't know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That is a known issue that should be resolved in develop.
