### ISSUE TITLE
black screen when joining a server

### ISSUE THREAD

**Issue by Enel300** [StrangeLoopGames/EcoIssues#24965]
like the titel said: black screen with sound when loading on a server wit. any suggestion?

**Comment by D3nnis3n** [comment]
This is a bug tracker to report bugs with steps to reproduce, not a support channel. For support requests please reach out to support@strangeloopgames.com.

When getting a black screen on joining a server that is typically a corruption of player data. Sometimes it can help to teleport the player somewhere else and have them reconnect. It might also help to delete the folder %UserProfile%\AppData\LocalLow\Strange Loop Games\Eco (type into run to open the folder).

If neither of that helps, a backup for the savegame would need to be restored, as the corruption is then in the world data.

**Comment by Enel300** [comment]
delete the whole folder?

%UserProfile%\AppData\LocalLow\Strange Loop Games\Eco

**Comment by D3nnis3n** [comment]
Yes. You can open that folder by typing the whole text into "run".
