### ISSUE TITLE
USER ISSUE: Can't connect to local server

### ISSUE THREAD

**Issue by sobchak420** [StrangeLoopGames/EcoIssues#24966]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
any attempt to create or join a local server ends in failure

**Expected behavior:**
should be able to connect to local server

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com and provide your client logfiles as described in the issue form above.
