### ISSUE TITLE
game crash after server connect

### ISSUE THREAD

**Issue by Turner86** [StrangeLoopGames/EcoIssues#24961]
maybe this will help ? 

[Player-prev.log](https://github.com/user-attachments/files/15513165/Player-prev.log)
[Player.log.copy.txt](https://github.com/user-attachments/files/15513168/Player.log.copy.txt)

**Comment by D3nnis3n** [comment]
Has this been a one-time issue or something you always get? Do you only get it on that one server or on all servers if it's recurring?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided, crashlog doesn't contain any useful information either.
