### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by just-w** [StrangeLoopGames/EcoIssues#24963]
\
**User Id: (slg211542)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
steel pipe	

**Expected behavior:**
smelt	

**Actual behavior:**
NEED FUCKIND POWERHUMMER WHEN THEY STAY NEAR 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
vanila

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Sorry, there is no way with the description you have given to understand what the problem is - please provide a new bug report with the necessary information.

**Comment by just-w** [comment]
Several blast furnaces are installed in a brick room. They work for everything except rivets of reinforcement and steel pipes, which require the presence of a power hammer. Which in turn is installed in the same room. Both work by themselves, but in the blast furnace, orders requiring a power hammer do not work.
I assembled similar rooms made of reinforced concrete and glass nearby - it works there. The old room does not work.

**Comment by D3nnis3n** [comment]
Make sure they are both in a single room that is sufficiently separated from all rooms and then try to replace each of the objects and replace it.
