### ISSUE TITLE
USER ISSUE: Crashed

### ISSUE THREAD

**Issue by RJU65** [StrangeLoopGames/EcoIssues#24968]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
creating a hosted world on Linux

**Expected behavior:**
play the game

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: DllNotFoundException
Message:Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/rrr/.net/EcoServer/DGSGjuz+bFo9GEucTBqMVCymJfuJ67Y=/libgdiplus.so: cannot open shared object file: No such file or directory
/home/rrr/.local/share/Steam/steamapps/common/Eco/Eco_Data/Server/libgdiplus.so: cannot open shared object file: No such file or directory
/home/rrr/.net/EcoServer/DGSGjuz+bFo9GEucTBqMVCymJfuJ67Y=/liblibgdiplus.so: cannot open shared object file: No such file or directory
/home/rrr/.local/share/Steam/steamapps/common/Eco/Eco_Data/Server/liblibgdiplus.so: cannot open shared object file: No such file o</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have NOT installed anything

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You didn't install "libgdiplus" (check install script in server folder). Please note that the Linux Client is not supported, that includes hosting a game via the client.
