### ISSUE TITLE
[Client side?] Shop constantly adds categories every frame after opening the shop

### ISSUE THREAD

**Issue by Gibibit** [StrangeLoopGames/EcoIssues#24964]
Eco version: 0.10.2.4 beta release-674
Server: Giant Panda
Client Unity log: [Player store bug.log](https://github.com/user-attachments/files/15521419/Player.store.bug.log)

When I opened my store the game keeps adding empty categories with the name "Product", seemingly every frame. Like so:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/1710540/b4f805d2-7003-4f7d-8c84-462c297dd81b)

Closing the store does not resolve the issue. New categories keep being added. After relogging, the empty categories have vanished and they are no longer being added automatically, indicating a client side bug. I was not holding down any button.

PS: the only notable thing that happened beforehand was that I added some items to a shop category, and they did not appear. I walked around a bit, opened the store again, and then the empty categories started flooding in. Might be unrelated though.

**Comment by D3nnis3n** [comment]
Cannot reproduce, any information on how it can be recreated?

**Comment by Gibibit** [comment]
Sorry, I don't have any reproduction steps. I did not do anything out of the ordinary beforehand and it has never happened more than this one time. I mostly posted the report since I thought the logs maybe tell something interesting.

**Comment by D3nnis3n** [comment]
Unfortunately not, but someone seemingly was able to provoke the same issue in playtest by moving an item into a collapsed category, so merging with that issue: https://github.com/StrangeLoopGames/EcoIssues/issues/24993
