### ISSUE TITLE
Alocating money has no limit

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2497]
https://gyazo.com/74d751138a6be991abd7e0e77bfe7a6f

this law ended up giving a person 9999999999 tax from the treasury and ofcouse there wasnt that much in there then 3 players got NAN currency that was kinda unlimeted 

https://cdn.discordapp.com/attachments/289135704263360513/366949635605921793/unknown.png

**Comment by Phlo123** [comment]
The game save with the error active.
https://www.dropbox.com/s/9lhz5t6rj4elio2/Game.rar?dl=0

**Comment by MarjieAVolk** [comment]
Hm, haven't reproed this yet.  Are you sure it was the law that caused it?  What else what taxing/allocating that currency?  Any other laws or manual allocating going on?

**Comment by Arend90** [comment]
yeah i saw int he server that the law alocated 99999999999 the chat just said nan

**Comment by MarjieAVolk** [comment]
Okay so wait, the screenshot of the law that you sent looks like it's during the law creation, not the final law.  Did the final law say allocate 99999999999 Greenleafs?

**Comment by Arend90** [comment]
2 final law should be visable

**Comment by MarjieAVolk** [comment]
No luck on this, I see the NaNs in your save but I can't get it to happen again.

**Comment by MarjieAVolk** [comment]
Going to close this as no repro for now, since as far as I know no one else ever complained of this issue again.
