### ISSUE TITLE
USER ISSUE: lose of fps

### ISSUE THREAD

**Issue by SkirlX** [StrangeLoopGames/EcoIssues#24976]
\
**User Id: (slg243814)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
all you need to do is scroll in a menu quickly adn you will drop fps

**Expected behavior:**
no loss of fps

**Actual behavior:**
large fram drop

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please follow these steps and provide the necessary data:
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/25908592/ed54e28e-9b76-4242-8410-8038f9b6d096)

**Comment by D3nnis3n** [comment]
Closing due to necessary data not provided, feel free to open a new issue if you can provide the required data for investigation.
