### ISSUE TITLE
USER ISSUE: Invalid login info

### ISSUE THREAD

**Issue by FroZenEscape** [StrangeLoopGames/EcoIssues#24970]
\
**User Id: ()**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
when continuing a saved world the following message appears not allowing me to play

had to restart my game because memory leak is still a thing many years later now my world is gone

**Expected behavior:**
should be able to continue saved game

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, never installed mods, 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
Invalid login info.

<size=60.00%>No response from auth server</size>

Log File:
Initialize engine version: 2021.3.25f1 (68ef2c4f8861)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3060 Ti (ID=0x2489)
    Vendor:   NVIDIA
    VRAM:     8024 MB
    Driver:   31.0.15.5244
Version: 0.10.2.4 beta release-674
RAM: 16225MB Total / 10312MB Free
OS Version: Windows 11  (10.0.22631) 64bit
CPU: 12th Gen Intel(R) Core(TM) i7-12700F - 20 Cores - 2.112 Ghz
System bit-ness: 64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.608300 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
WwiseUnity: Wwise(R) SDK Version 2021.1.6 Build 7774.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: E:/SteamLibrary/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

The referenced script (NotificationsController) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Notification') is missing!
The referenced script on this Behaviour (Game Object 'Exchange') is missing!
OvrLipSync Awake: Queried SampleRate: 48000 BufferSize: 16000
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
OVRLipSync:Initialize()
OVRLipSync:Awake()

Ambiguous UI component types ignored: ViewEditorUI,BaseUI,CalibrationSequenceUI,SeriesPopupUI,AutoViewUI,AutoModalUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.UIManager:Start()

[02:40:16.215] Initializing platform: SteamPlatform
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Platform.PlatformManager:AddPrimaryPlatform(Object[])
Eco.Client.Platforms.Framework.Platform.PlatformManager:Start()

[02:40:16.323] Initialized social platform: SteamSocialNetwork
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[02:40:16.333] Initialized social platform: DiscordSocialNetwork
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[02:40:16.394] Authenticating with our primary platform.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Login(String, String, Boolean)
NetworkManager:Start()

[02:40:16.606] [Discord] ResponseError { code: InvalidPermissions, message: "Not authenticated or invalid scope" }
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Client.Platforms.Discord.DiscordSocialNetwork:DiscordLogHook(LogLevel, String)
Discord.Discord:RunCallbacks()
Eco.Client.Platforms.Discord.DiscordSocialNetwork:Update()
PlatformUtils:VerifyPlatformAction(Action, String, Type)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:Update()

[02:40:47.073] Received login result from our primary platform. (Succes: True | Message: )
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
Eco.Client.Platforms.Steam.<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, ValueTuple`2)
Eco.Client.Platforms.Internal.Utils.<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[02:40:47.074] Account isn't developer tier.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Authentication.AppAuthentication:SetIdentity(AppIdentity)
NetworkManager:SetSessionAndIdentity(LoginSession)
NetworkManager:HandleLoginResult(LoginResult)
Eco.Client.Platforms.Steam.<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, ValueTuple`2)
Eco.Client.Platforms.Internal.Utils.<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[02:40:47.568] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

[02:40:48.243] Event data successfully sent.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ServerBrowser.<PushEvent>d__3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[02:41:08.420] Launching server: 'E:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe -nogui -consoleIPC -parentPID=3076 -loadSave="New 2024 again" -language="English" -seed=0 -clientActive -sleepEnabled -playTime'.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LocalServerManager:LaunchServer(ClientServerStartParameters, Action`1, String, Boolean)
ContinueUI:ConnectAndContinue()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[02:41:35.487] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:41:35.488] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:41:35.488] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Write(LocString)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:41:35.520] Loading... Pending packets: 0, DownloadHandler: 0, UserTextureManager: False
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.DownloadWarning:Update()

[02:41:45.603] Disconnected with error: Invalid login info.

<size=60.00%>No response from auth server</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

Unloading 6 Unused Serialized files (Serialized files now loaded: 3)
Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 109840.
Total: 68.407200 ms (FindLiveObjects: 3.262700 ms CreateObjectMapping: 4.320800 ms MarkObjects: 60.634900 ms  DeleteObjects: 0.188600 ms)

[02:41:59.913] Nat introduction received with token = 339f62f7-93b3-4d79-9d8f-458faaac29d0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(Address&, IntPtr, Int32, Boolean&)
Eco.Networking.ENet.ENetUdpPeer:Intercept(Event&, Address&, IntPtr, Int32)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[02:42:03.880] Launching server: 'E:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe -nogui -consoleIPC -parentPID=3076 -loadSave="New 2024 again" -language="English" -seed=0 -clientActive -sleepEnabled -playTime'.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LocalServerManager:LaunchServer(ClientServerStartParameters, Action`1, String, Boolean)
ServerListingLocalUI:<LoadLocal>b__16_0()
PopupDialogUI:OnYesClick()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[02:42:25.888] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:42:25.888] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:42:25.888] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Write(LocString)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:42:25.913] Loading... Pending packets: 0, DownloadHandler: 0, UserTextureManager: False
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.DownloadWarning:Update()

[02:42:35.974] Disconnected with error: Invalid login info.

<size=60.00%>No response from auth server</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

Unloading 0 Unused Serialized files (Serialized files now loaded: 3)
Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 109841.
Total: 69.792800 ms (FindLiveObjects: 2.886100 ms CreateObjectMapping: 3.266400 ms MarkObjects: 63.455400 ms  DeleteObjects: 0.184800 ms)

[02:42:36.177] Nat introduction received with token = 339f62f7-93b3-4d79-9d8f-458faaac29d0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Networking.NetworkClient:HandleCompleteUnconnectedDataMessage(UdpDataMessage&)
Eco.Shared.Networking.NetworkClient:HandleUnconnectedDataMessage(UdpDataMessage&)
Eco.Networking.ENet.ENetUdpPeer:OnRawDataReceived(Address&, IntPtr, Int32, Boolean&)
Eco.Networking.ENet.ENetUdpPeer:Intercept(Event&, Address&, IntPtr, Int32)
ENet.Host:Service(Int32, Event&)
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[02:42:38.817] Trying to add Handle (UnityEngine.UI.Image) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.UI.CanvasUpdateRegistry:InternalRegisterCanvasElementForGraphicRebuild(ICanvasElement)
UnityEngine.UI.Graphic:SetVerticesDirty()
UnityEngine.UI.Graphic:OnRectTransformDimensionsChange()
UnityEngine.RectTransform:set_anchorMin(Vector2)
UnityEngine.UI.Scrollbar:UpdateVisuals()
UnityEngine.UI.Scrollbar:set_size(Single)
TMPro.TMP_InputField:ON_TEXT_CHANGED(Object)
TMPro.FastAction`1:Call(A)
TMPro.TextMeshProUGUI:GenerateTextMesh()
TMPro.TextMeshProUGUI:OnPreRenderCanvas()
TMPro.TextMeshProUGUI:Rebuild(CanvasUpdate)
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()

[02:46:18.014] Launching server: 'E:/SteamLibrary/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe -nogui -consoleIPC -parentPID=3076 -loadSave="New 2024 again" -language="English" -seed=0 -clientActive -sleepEnabled -playTime'.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LocalServerManager:LaunchServer(ClientServerStartParameters, Action`1, String, Boolean)
ContinueUI:ConnectAndContinue()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[02:46:43.229] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:46:43.230] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:46:43.230] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Write(LocString)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[02:46:43.259] Loading... Pending packets: 0, DownloadHandler: 0, UserTextureManager: False
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.DownloadWarning:Update()

[02:46:53.314] Disconnected with error: Invalid login info.

<size=60.00%>No response from auth server</size>
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

Unloading 0 Unused Serialized files (Serialized files now loaded: 3)
Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 109842.
Total: 77.726100 ms (FindLiveObjects: 3.324900 ms CreateObjectMapping: 3.562300 ms MarkObjects: 70.665900 ms  DeleteObjects: 0.172600 ms)

**Comment by D3nnis3n** [comment]
There was a temporary maintenance at that time, the issue should already be resolved.
