### ISSUE TITLE
USER ISSUE: Fehlermeldung Invalid login info

### ISSUE THREAD

**Issue by Lapadula98** [StrangeLoopGames/EcoIssues#24978]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Ich starte das Spiel.
2. Ich wähle unter ,,Weiter" meinen Server
3. Server beginnt zu Laden
4. Ab ,,Verbindung wird Hergestellt" kommt die Fehlermeldung 
Invalid login info no response from auth server

Ich habe mein das Spiel und auch mein PC mehrfach neugestartet, und auch unter ,,Deine Welten" versucht den Server zu laden. Jedoch blieb dies erfolglos und der selbe fehler wird angezeigt.

**Expected behavior:**
Das Spiel sollte normal starten ohne Fehlermeldung wie es sonst auch war

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein ich habe noch nie Mods für Eco Installiert, also ja der Fehler tritt ohne Mods auf.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Das ist kein Fehler in der Software, die Meldung sagt lediglich aus, dass keine Verbindung zu den Authentifizierungsservern hergestellt werden konnte.

Das kann durch alles mögliche verursacht werden: Fehlende Internetverbindung, Antivirussoftware, DNS-Filter (PiHole, Adguard), Routing Probleme, ISP Verbindungsprobleme, DNS Probleme, Temporäre Sicherheitsmaßnahmen von Cloudflare, etc.

Es ist für uns leider nicht möglich zu identifizieren, welches Problem in deinem Fall vorliegt. Du kannst an support@strangeloopgames.com schreiben, die können dir ein paar Tipps geben, was du dir ansehen kannst - eine Diagnose können die aber ohne in deinem Netzwerk zu sein ebenfalls nicht machen.

**Comment by Lapadula98** [comment]
Vielen Dank für die Info. Es lag an dem VPN Programm WARP welches ich mir vergangende Woche für ein anderes Spiel runterladen musste. Als ich das programm deaktiviert habe konnte ich mein Eco Server wieder starten
