### ISSUE TITLE
Bug: multiplying claim papers

### ISSUE THREAD

**Issue by UniSaJ** [StrangeLoopGames/EcoIssues#24972]
\
**User Id: (slg147136)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Create real estate desk
2. There are rectangles with the coordinates of your properties. Clicking to 'X' will give you claim paper.
3. Your Claim Tool limit still have a limit 16 plot but you also have a claim papers 

**Expected behavior:**
Unclaim the properties in real estate desk should decrease  max limit of Claim Tool and gives you respective numbers of the Claim  Papers

**Actual behavior:**
You got claim papers  but the limit of the claim tool still 16

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. It was found on official server Sea Otter

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @UniSaJ 

Thank you for submitting this bug report.
I can confirm this bug and have created an internal report.
A fix should be rolled out in the coming future game updates.

QA Ref. [ECO-34473](https://app.clickup.com/t/10591183/ECO-34473)

**Comment by D3nnis3n** [comment]
Fixed in 10.3.
