### ISSUE TITLE
USER ISSUE: Stuck in a weird state, cant click any action hotkeys

### ISSUE THREAD

**Issue by github-center** [StrangeLoopGames/EcoIssues#24977]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
I was bulding some benches and not sure what hapened

**Expected behavior:**

**Actual behavior:**
I can no longer click on action hotkeys, from my wife's perspective it shows me non stop hammering with my hammer. I can tab and I can open my bag, but I can't do much else. It's like a partial crash.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Does the issue persist after a restart? Can you provide the logs as noted in the issue template?

**Comment by github-center** [comment]
A restart, or even just going to main menu and coming back resolves it. I have had it happen 2 or 3 times now, usually when I am placing a building of sorts. latest was a lumber stockpile. It may be when I place it then try to pick it back up again while having a hammer in hand.

**Comment by D3nnis3n** [comment]
Issue is not reproducible and requested logfiles unfortunately weren't provided, hence closing this issue.

Please feel free to open a new issue if you can provide the necessary logfiles for this issue.
