### ISSUE TITLE
USER ISSUE: No response from auth server

### ISSUE THREAD

**Issue by a-kushnir** [StrangeLoopGames/EcoIssues#24983]
\
**User Id: (slg238685)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Start server locally
2. Click Continue to play on the server

**Expected behavior:**
Connected to server; Can play the game

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

No response from auth server
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nope

[client.log](https://github.com/user-attachments/files/15897722/Player.log)
[server.log](https://github.com/user-attachments/files/15897675/log_240619020139.log)
Note: 192.168.1.240 is localhost IP address

**Comment by a-kushnir** [comment]
The game self healed 8 hours later

**Comment by D3nnis3n** [comment]
Not a bug, but a local network issue - please reach out to support@strangeloopgames.com if you ever have the issue again.
