### ISSUE TITLE
USER ISSUE: застрял в текстурах

### ISSUE THREAD

**Issue by AngelSaints** [StrangeLoopGames/EcoIssues#24988]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Нахождение на складе во время его пополнения

**Expected behavior:**
Атоматически подниматься по появляющимся материалами

**Actual behavior:**
Застрял в новых материалах склада взаимодействие со складом не возможно

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Нет

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24352
