### ISSUE TITLE
Negative camas population on greenleaf server

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2498]
![image](https://user-images.githubusercontent.com/3536496/31360997-ec5e1dd8-ad05-11e7-8c3b-2734d0a438b5.png)

**Comment by johnkslg** [comment]
Save is here: https://www.dropbox.com/s/p3ggqh9qremzav6/error%20GreenLeaf.rar?dl=0

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/31362533-453af392-ad59-11e7-9b3e-74b7636b13bf.png)

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/31363769-fa73f63a-ad60-11e7-9fa3-83c1aa8ea410.png)
found one of the -2606

**Comment by craig-jong** [comment]
this should be fixed in latest staging
