### ISSUE TITLE
Collider of the Steam Truck is active in the ghost of the Move function

### ISSUE THREAD

**Issue by Thibault-Brocheton** [StrangeLoopGames/EcoIssues#24987]
Eco version: 10.2.4

Looks like the collider of the ghost of the steam truck is active when we try to move it
it allows to unstuck a steam truck without spending callories
I guess it works with other vehicles.

https://github.com/StrangeLoopGames/EcoIssues/assets/7646137/f9ecc925-850d-4275-a70f-5b46b80aca36

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/24944
