### ISSUE TITLE
USER ISSUE: void storage

### ISSUE THREAD

**Issue by github-center** [StrangeLoopGames/EcoIssues#24980]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. get evicted as a resident (was done to try to fix a different bug) and have any item (not made by you) that you moved to place put in your void storage
2. put some things out of the void storage, go to put a stack of rocks back in because you don't have a place to put them, get an error
3. all remaining items in the void storage are gone. the void inventory is now blank. the void storage icon remains and says from eviction, no items appear in the void storage	

**Expected behavior:**
continued to show the items in the void storage while keeping the rocks on my cursor

**Actual behavior:**
made us have to remake many types of crafting tables

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
Report made for internal checks under 34775
