### ISSUE TITLE
USER ISSUE: cannot connect to newly made solo world

### ISSUE THREAD

**Issue by FisherManTC** [StrangeLoopGames/EcoIssues#24982]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
try to join a newly made solo world from host a world menu

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2021.3.25f1 (68ef2c4f8861)
[Subsystems] Discovering subsystems at path S:/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 4070 (ID=0x2786)
    Vendor:   NVIDIA
    VRAM:     12012 MB
    Driver:   32.0.15.5599
Version: 0.10.2.4 beta release-674
RAM: 32509MB Total / 21501MB Free
OS Version: Windows 11  (10.0.22631) 64bit
CPU: 12th Gen Intel(R) Core(TM) i9-12900K - 16 Cores - 3.187 Ghz
System bit-ness: 64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.623800 ms
start of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

end of EcoBootstrap.Initialize
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)
Unity.Entities.AutomaticWorldBootstrap:Initialize()

DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
WwiseUnity: Wwise(R) SDK Version 2021.1.6 Build 7774.
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: S:/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkWwiseInitializationSettings:InitializeSoundEngine()
AkInitializer:OnEnable()

The referenced script (NotificationsController) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Notification') is missing!
The referenced script on this Behaviour (Game Object 'Exchange') is missing!
OvrLipSync Awake: Queried SampleRate: 48000 BufferSize: 16000
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
OVRLipSync:Initialize()
OVRLipSync:Awake()

Ambiguous UI component types ignored: ViewEditorUI,BaseUI,CalibrationSequenceUI,SeriesPopupUI,AutoViewUI,AutoModalUI
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.UIManager:Start()

[08:18:31.919] Initializing platform: SteamPlatform
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Platform.PlatformManager:AddPrimaryPlatform(Object[])
Eco.Client.Platforms.Framework.Platform.PlatformManager:Start()

[08:18:32.004] Initialized social platform: SteamSocialNetwork
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[08:18:32.011] Initialized social platform: DiscordSocialNetwork
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[08:18:32.076] Authenticating with our primary platform.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:Login(String, String, Boolean)
NetworkManager:Start()

[08:18:32.366] The desired audio input device is not available on the system.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
VoiceManager:SetActiveVoiceInputDevice(String, AsyncCallback)
VivoxUnity.AsyncNoResult:SetComplete()
VivoxUnity.Private.<>c__DisplayClass31_0:<BeginRefresh>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

[08:18:32.515] [Discord] ResponseError { code: InvalidPermissions, message: "Not authenticated or invalid scope" }
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Eco.Client.Platforms.Discord.DiscordSocialNetwork:DiscordLogHook(LogLevel, String)
Discord.Discord:RunCallbacks()
Eco.Client.Platforms.Discord.DiscordSocialNetwork:Update()
PlatformUtils:VerifyPlatformAction(Action, String, Type)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:Update()

[08:18:32.635] Received login result from our primary platform. (Succes: True | Message: )
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
NetworkManager:HandleLoginResult(LoginResult)
Eco.Client.Platforms.Steam.<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, ValueTuple`2)
Eco.Client.Platforms.Internal.Utils.<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[08:18:32.636] Account isn't developer tier.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Authentication.AppAuthentication:SetIdentity(AppIdentity)
NetworkManager:SetSessionAndIdentity(LoginSession)
NetworkManager:HandleLoginResult(LoginResult)
Eco.Client.Platforms.Steam.<>c__DisplayClass18_0:<PerformPlatformLogin>b__0(LoginSession, ValueTuple`2)
Eco.Client.Platforms.Internal.Utils.<AuthenticatePlatformUser>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[08:18:33.233] LoginSession: connectorHandle=C0
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VivoxUnity.VivoxDebug:DebugMessage(Object, vx_log_level)
VivoxUnity.Private.<>c__DisplayClass89_0:<BeginLogin>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.<>c__DisplayClass12_0:<BeginGetConnectorHandle>b__0(IAsyncResult)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()

[08:18:33.906] Event data successfully sent.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ServerBrowser.<PushEvent>d__3:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[08:18:45.000] Launching server: 'S:/Steam/steamapps/common/Eco/Eco_Data\Server\EcoServer.exe -nogui -consoleIPC -parentPID=2980 -loadSave="SOLO" -language="English" -seed=0 -clientActive -sleepEnabled -playTime'.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
LocalServerManager:LaunchServer(ClientServerStartParameters, Action`1, String, Boolean)
ServerListingLocalUI:<LoadLocal>b__16_0()
PopupDialogUI:OnYesClick()
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse(PointerEventData, GameObject)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[08:19:10.103] Connecting to local host.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[08:19:10.104] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[08:19:10.106] Connection complete.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Write(LocString)
Eco.UI.ConnectionUI:LoadingWorldUpdate()
Eco.UI.UIManager:Update()

[08:19:13.117] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[08:19:16.121] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[08:19:19.125] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[08:19:22.129] Connecting to 127.0.0.1:3000...
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:ConnectRoundRobin()
Eco.Shared.Networking.NetworkClient:HandleDisconnected(Object, DisconnectReason)
Eco.Networking.ENet.ENetUdpClient:OnDisconnected(ENetConnection, DisconnectReason)
ViewData:CreateView()
Eco.Networking.ENet.ENetUdpPeer:Service(Int32)
NetworkManager:<StartServiceThread>b__69_0()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)

[08:19:25.122] Disconnected with error: Failed to connect - connection timed out.
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String, Boolean)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()

Unloading 6 Unused Serialized files (Serialized files now loaded: 3)
Unloading 20 unused Assets to reduce memory usage. Loaded Objects now: 109847.
Total: 82.099700 ms (FindLiveObjects: 4.269200 ms CreateObjectMapping: 5.439100 ms MarkObjects: 72.169000 ms  DeleteObjects: 0.222100 ms)

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com and provide your full client and server logs, the message only states that a connection could not be established and as such does not hint at a bug.
