### ISSUE TITLE
USER ISSUE: Bug magasin, déplacements d'objet d'une catégorie à une autre

### ISSUE THREAD

**Issue by RazHalGuhl** [StrangeLoopGames/EcoIssues#24993]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. magasin actif
2. ouvrir magasin
3. créer 4 catégories d'objets à vendre
4. placer des objets dans la première catégorie
5. les autres catégories sont 'repliées'
6. déplacer des objets d'une catégorie à une autre

**Expected behavior:**
les objets sont déplacées dans la catégorie visée, qu'elle soit repliée ou non

**Actual behavior:**
ne déplacer pas l'objet
voire pire : il copie la catégorie en boucle (ce qui crée en quelques mintes des miliers de catégorie avec le même nom)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Aucun mod installé

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please attach your logfiles when you had that issue.

**Comment by D3nnis3n** [comment]
Merging with https://github.com/StrangeLoopGames/EcoIssues/issues/25092, due to no necessary information provided.
