### ISSUE TITLE
USER ISSUE: Imposinbility set any object on the ground

### ISSUE THREAD

**Issue by RonePi** [StrangeLoopGames/EcoIssues#24992]
\
**User Id: (aadd6365-a6ba-48b5-3129-08dc77297b37)**
**Version:** 0.10.3.0 beta playtest-416

**Steps to Reproduce:**
Launch game
Put starter in k1
Set Starter camp on the ground
All green but impossibility to set it.

Same with /give Ballo

But set brick with hammer is ok.

**Expected behavior:**
Set items on the ground

**Actual behavior:**
Imposibly to set starter camp or any item on the ground

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Any

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the logfiles as mentioned in the issue template.

**Comment by SlayksWood** [comment]
@RonePi thanks for the report, We need some details for investigation.
1. Can you provide your PC specification (include Operating System and its version)?
2. As my colleague asked, we need log files.
3. Can you add a couple screenshots or maybe video with your issue? 
4. Does this always happen to you? Or were you able to solve the problem? for example after restarting the game or when you ran far away and tried to do it again?

Currently we have some bugs with shadowplacement, so it can be show wrong. Try to level ground and place world objects again.

**Comment by RonePi** [comment]
Sorry.

1 - PC specification
    . Processor Intel(R) Core(TM) i9-14900KF   3.20 GHz
    . RAM memory  64,0 Go (63,7 Go utilisable)
    .  Windows 11

2  logfiles as mentioned in the issue template.
[Player.log](https://github.com/user-attachments/files/16073776/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16073777/Player-prev.log)


3 -  video with my issue
I've made several attempts but the video is too heavy. Here's a Youtube link. Sorry about that : 
> https://youtu.be/oy0z5aw1Ais
+ And for the video, the animals seem more passive and there's a white ball visible.


4 - 
This problem persists on this computer. The last updates were done today to be sure, uninstalling and reinstalling the game. Launching a new single-player game on this computer.

**Comment by D3nnis3n** [comment]
Should be fixed by https://github.com/StrangeLoopGames/Eco/pull/14191
