### ISSUE TITLE
USER ISSUE: Bug

### ISSUE THREAD

**Issue by Vinvin1812** [StrangeLoopGames/EcoIssues#24996]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Me sortir du bug

**Expected behavior:**

**Actual behavior:**
Coincé sous terre

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use /unstuck to free yourself from being stuck.
