### ISSUE TITLE
USER ISSUE: Stockpile range different per object

### ISSUE THREAD

**Issue by Jalefe** [StrangeLoopGames/EcoIssues#24999]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Place a large lumber stockpile
2. 7 blocks away place an electric planner, a chest and a robotic assembly line
3. try to access the stockpile from each object

**Expected behavior:**
All objects should see the stockpile because range of large lumber stockpile is 10 blocks (horizontalle and vertically)

**Actual behavior:**
Only electric planner sees stockpile. Robotic assembly line and chest do not. Why do objects interact differently with fixed range of stockpile?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16134348/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16134349/Player-prev.log)

**Comment by D3nnis3n** [comment]
Each of the objects has a single block in its "hitbox" that determines the distance and also if it is covered by a claim, as such the objects that do not have access have the single block outside range.
