### ISSUE TITLE
USER ISSUE: Ich kann kein Spiel erstellen

### ISSUE THREAD

**Issue by Inu54862** [StrangeLoopGames/EcoIssues#24991]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Ich möchte ein Spiel erstellen, dann lädt es und ich bekomme den Fehler.
 VPN deaktiviert und Windows Firewall auf Standardeinstellungen und ECO hat volle Rechte, andere Online-Spiele funktionieren auch ohne Probleme.  

**Expected behavior:**

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Invalid login info.

<size=60,00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Das ist kein Fehler in der Software, die Meldung sagt lediglich aus, dass keine Verbindung zu den Authentifizierungsservern hergestellt werden konnte.

Das kann durch alles mögliche verursacht werden: Fehlende Internetverbindung, Antivirussoftware, DNS-Filter (PiHole, Adguard), Routing Probleme, ISP Verbindungsprobleme, DNS Probleme, Temporäre Sicherheitsmaßnahmen von Cloudflare, etc.

Es ist für uns leider nicht möglich zu identifizieren, welches Problem in deinem Fall vorliegt. Du kannst an [support@strangeloopgames.com](mailto:support@strangeloopgames.com) schreiben, die können dir ein paar Tipps geben, was du dir ansehen kannst - eine Diagnose können die aber ohne in deinem Netzwerk zu sein ebenfalls nicht machen.

**Comment by Inu54862** [comment]
Ich habe schon viel probiert, fehlende Internetverbindung kann es nicht sein, Antivirus mehrfach komplett deaktivieren, DNS-Filter liegen im Heimnetzwerk nicht vor, der Rechner ist jetzt auch privilegierter Nutzer, ich weiß halt nicht, woran es liegen könnte
