### ISSUE TITLE
USER ISSUE: Desert Sand turning into dirt

### ISSUE THREAD

**Issue by bekkahh** [StrangeLoopGames/EcoIssues#24997]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Dug desert sand in desert.
Picked up, changed to dirt, put down still dirt. Regular sand seems fine.
Unsure if this is intentional but feels odd.

**Expected behavior:**
Stayed as sand/desert sand.

**Actual behavior:**
turned to dirt.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16117776/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16117777/Player-prev.log)

**Comment by D3nnis3n** [comment]
This is working as inended, it's dirt in different colours and will return to normal colour after a while. Sand is a separate block.
