### ISSUE TITLE
USER ISSUE: Game won't start

### ISSUE THREAD

**Issue by tand112** [StrangeLoopGames/EcoIssues#24990]
\
**User Id: (slg171021)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
I have shut down multiple times, attempted to reinstall multiple times and the game won't start.

**Expected behavior:**
it won't load any freaking game. 

**Actual behavior:**
The following error message popped up:
```
Failed to process a request. Probably the client incompatible with the server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com, your report doesn't contain any necessary information and likely is a technical issue, not a bug.
