### ISSUE TITLE
Mouse sensitivity adjustment

### ISSUE THREAD

**Issue by Danl2620** [StrangeLoopGames/EcoIssues#25]
On the mac client, patch 0.2, the mouse is too sensitive. 

Ideally, the game would have an options menu to adjust mouse sensitivity. However, the full set of customization options probably won't be known for quite awhile, so I'd recommend reading a configuration xml file on startup.

Also, as it's nearly unplayable atm this issue could also be fixed by just adjusting the code.

Thanks!

**Comment by tbbw** [comment]
Also maby while your at tweaking the mouse maby add a toggle to invert the scroller.
It feels back to front to scroll down to... scroll upwards in the toolbar.
