### ISSUE TITLE
USER ISSUE: Infinite "youre too hungry" notification

### ISSUE THREAD

**Issue by pipe08** [StrangeLoopGames/EcoIssues#25006]
\
**User Id: (a463eac6-1c89-43b8-8223-08dc8d1bff58)**
**Version:** 0.11.0.0 beta playtest-452

**Steps to Reproduce:**
1. be hungry
2. hit a rock

**Expected behavior:**
One notification per hit

**Actual behavior:**
infinite notification and no hits

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already reported in discord.
