### ISSUE TITLE
Clams should give resources independent of growth percentage

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2500]
/ not have growth percentage?

**Comment by johnkslg** [comment]
Seems like small clams could give less clamminess?

**Comment by MarjieAVolk** [comment]
There are no small clams, that's the problem

**Comment by metachronism** [comment]
clams can scale for growth

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#368
