### ISSUE TITLE
USER ISSUE: righ click stockpile bug	

### ISSUE THREAD

**Issue by pipe08** [StrangeLoopGames/EcoIssues#25007]
\
**User Id: (a463eac6-1c89-43b8-8223-08dc8d1bff58)**
**Version:** 0.11.0.0 beta playtest-452

**Steps to Reproduce:**
1. just log on
2. try to put something directly on a stockpile

**Expected behavior:**
The thing should go to the stockpile

**Actual behavior:**
No action

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already reported in discord.
