### ISSUE TITLE
USER ISSUE: Possibly Wrong Ingredient In Crafting Recipe

### ISSUE THREAD

**Issue by MegaChibisX** [StrangeLoopGames/EcoIssues#25001]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Open up a Research Station
2. Look for the Basic Upgrade 2 recipe

**Expected behavior:**
It should have relevant research papers as the ingredients listed

**Actual behavior:**
A ship haul piece seems to be one of the ingredients. That seems to be unrelated, and may be an incorrectly listed ingredient

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thanks for the report, that is working as intended - it is indeed a temporary ingredient supposed to be replaced with something else once that has been developed.
