### ISSUE TITLE
USER ISSUE: Wrong (infinite value) of food needed when moving a cart only the the up/down direction (no horizontal offset)

### ISSUE THREAD

**Issue by DJTgeekk** [StrangeLoopGames/EcoIssues#25002]
\
**User Id: DJTgeek**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1 - Put a cart below the ground with a roof on top (tested with a wooden cart) - With the hammer move the cart and aim the block above it

**Expected behavior:**
The food amount shoud display the real value an allow to move it

**Actual behavior:**
The food amount is displayed as 0 and looks like infinite

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Comment by D3nnis3n** [comment]
Fixed in Update 11.
