### ISSUE TITLE
server connection issue

### ISSUE THREAD

**Issue by kuveln** [StrangeLoopGames/EcoIssues#25005]
the server stops responding after 5-10 minutes (infinite reconnecting), after trying to rejoin\relaunch the game nothing changes still not responding. When the server restarted there were 5 minutes of normal response after which it again started 
![image](https://github.com/user-attachments/assets/ab3f8ac2-07df-4045-a934-0b9d2d151298)
0.10.2.4 beta release-674 (steam)

**Comment by D3nnis3n** [comment]
Please have the administrator reach out to support@strangeloopgames.com.
