### ISSUE TITLE
USER ISSUE: Tools after Patch 7/8

### ISSUE THREAD

**Issue by Caldrena** [StrangeLoopGames/EcoIssues#25000]
\
**User Id: (36a3d481-05b4-453b-40c2-08dc9ba1882d)**
**Version:** 0.10.3.0 beta playtest-432

**Steps to Reproduce:**
make iron tools before and after patch

**Expected behavior:**
been fully reparied and listed in the store 

**Actual behavior:**
tools made before patch are reduced from 750/750 to 100/100 max durability and not repairable (80% reduced) making them useless. These tools were never used. Tools made after patch have max dura at 750 and do not list in store.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Caldrena** [comment]
[Player.log.copy.txt](https://github.com/user-attachments/files/16134519/Player.log.copy.txt)
[Player-prev.log](https://github.com/user-attachments/files/16134520/Player-prev.log)

**Comment by D3nnis3n** [comment]
Already reported on Discord - please don't report bugs twice.
