### ISSUE TITLE
crashes more frequesnt and fps drops

### ISSUE THREAD

**Issue by computerchy** [StrangeLoopGames/EcoIssues#25014]
i believe we do some have some narrow , intense content like i built a tall building with 4 stories 3 rooms X 4 types , bur i notice game FPS drops really hard , esp im at town center middle of many buildings but there are surely smaller than my building , i notice when camera got glitches and end at jaw and eye character revealing position , game became smoother , or might be its coincidence , and later on game start randomly crashes , some time like 2 or more times in row , some times stays longer , so id i hope better optimization , i was playing at server ( eco world ) server , uses discord link and some other mods 
[Crash_2024-07-25_190823505.zip](https://github.com/user-attachments/files/16382895/Crash_2024-07-25_190823505.zip)

**Comment by D3nnis3n** [comment]
Crash log indicates system instability, but no bug to be found. Probably reach out to support@strangeloopgames.com.

Make sure to update all of your drivers as well.
