### ISSUE TITLE
USER ISSUE: Wooden Barge Not working in 11

### ISSUE THREAD

**Issue by oithatguy** [StrangeLoopGames/EcoIssues#25017]
\
**User Id: (360440b2-73ac-4fc7-5a69-08dc8d11157e)**
**Version:** 0.11.0.0 beta playtest-469

**Steps to Reproduce:**
You place a barge you can drive it the moment you drop the doors and lift them it does not move as iff its still down

**Expected behavior:**
You place a barge you can drive it the moment you drop the doors and lift them it does not move as iff its still down

**Actual behavior:**
You place a barge you can drive it the moment you drop the doors and lift them it does not move as iff its still down

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already reported in Discord.
