### ISSUE TITLE
Cannot drop items into inventory using right click

### ISSUE THREAD

**Issue by MrMcMiller** [StrangeLoopGames/EcoIssues#25012]
as the title says, cannot right click to insert items into inventories,
occured after relogging 

version: 0.11.0.0 beta playtest-456 (on white tiger)
[Player.log](https://github.com/user-attachments/files/16352777/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16352779/Player-prev.log)

**Comment by D3nnis3n** [comment]
Already reported on discord.
