### ISSUE TITLE
USER ISSUE: Moving workbench does not move its indicator

### ISSUE THREAD

**Issue by Gdumaire** [StrangeLoopGames/EcoIssues#25016]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Have a workbench running at least an ongoing task if not a long task
2. Move the workbench with a hammer
3. Move it again

**Expected behavior:**
The task indicator should be with the workbench

**Actual behavior:**
The task indicator stays at the original workbench location

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/16400280/Player.log)

**Comment by D3nnis3n** [comment]
Already reported internally, ECO-30603.
