### ISSUE TITLE
USER ISSUE: Visibility of inventory items 

### ISSUE THREAD

**Issue by Daronius** [StrangeLoopGames/EcoIssues#25029]
\
**User Id: (slg230235)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
1. Add an item to the inventory or an item was added by a workstation

**Expected behavior:**
The item should be shown with its icon

**Actual behavior:**
The icon is invisible only the couter is visible.
It's possible to grab the invisible item and move it to another slot and there it's visible with its icon.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23628
