### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by LOX-X** [StrangeLoopGames/EcoIssues#25025]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>Internal Server Error, Trace ID: 00-097a15faeff7373648d8ef22e5561b90-8cc1ff6e15265da3-00</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Hello LOX-X,
if this issue still persists, please reach out to support@strangeloopgames.com. This issue might need access to account data which is not possible via GitHub.
