### ISSUE TITLE
USER ISSUE: Rock Drops

### ISSUE THREAD

**Issue by RagnarokPrime** [StrangeLoopGames/EcoIssues#25033]
\
**User Id: (04eec862-ff50-40b5-d87b-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Break any rock. I've been breaking Sandstone.

**Expected behavior:**
It should drop a combination of four rocks.

**Actual behavior:**
It drops anywhere between 0-4 rocks and if it does its often delayed by quite a while, like 30 secs or more, and scattered around the area sometimes far off.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes, I have tried without mods and with mods and on multiple servers. No matter what it always happens.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25037
