### ISSUE TITLE
USER ISSUE: NO MAIN MENU	

### ISSUE THREAD

**Issue by DjSapsan** [StrangeLoopGames/EcoIssues#25031]
\
**User Id: (Not logged user)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
START A GAME	

**Expected behavior:**
SEE A MENU	

**Actual behavior:**
NO MENU VISIBLE, NOT POSSIBLE TO START A GAME.
ONLY ESCAPE WORKS

**Do you have mods installed? Does the issue happen when no mods are installed?:**
BRAND NEW ABSOLUTE FRESH INSALL AND REINSTALL

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by DjSapsan** [comment]
Just checked the older issues.
Yes, I restarted Steam and game multiple times. I tried to run default Linux install and with Steam Proton without any difference.
It happened many years ago few times but game restart resolved the issue each time.

**Comment by DjSapsan** [comment]
Running with Proton experimental version probably fixed the issue

**Comment by D3nnis3n** [comment]
Should be resolved, was a hickup at deployment of new backend servers.
