### ISSUE TITLE
USER ISSUE: Server rejoin bug

### ISSUE THREAD

**Issue by Steffi386** [StrangeLoopGames/EcoIssues#25032]
\
**User Id: (a57fb8a0-3bc3-44d1-bff2-08dcbd51a712)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
leave then rejoin player server that is still running

**Expected behavior:**
let me rejoin

**Actual behavior:**
The following error message popped up:
```
The requested server was not found (ID = a3a35fd6-fd2a-446d-98dc-0a9af7afb88d). It either doesn't exist, or is not registered on the master server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be addressed with Hotfix 11.0.1, if the issue persists please create a new issue and attach your logfiles as noted in the issue template.
