### ISSUE TITLE
USER ISSUE: Worlds not loading on first attempt

### ISSUE THREAD

**Issue by Wrizzler** [StrangeLoopGames/EcoIssues#25035]
\
**User Id: (ffb32b0d-5c2c-4354-2a4e-08dc8cbaa722)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Generating any world to host

**Expected behavior:**
loaded world so that I can have friends join

**Actual behavior:**
The world does not load, it locks up and the network speed drops to under 20B/s but never continues to actually load anything that I can tell. Once I cancel and attempt to hit continue to join world that was generated it works, but nobody can join me.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be addressed with Hotfix 11.0.1, if the issue persists please create a new issue and attach your logfiles as noted in the issue template.
