### ISSUE TITLE
USER ISSUE: Ghostly Voices

### ISSUE THREAD

**Issue by WardenGeneral** [StrangeLoopGames/EcoIssues#25034]
\
**User Id: (6e13ac65-969e-40da-6aa6-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1: Be on a single, private player server. 
2: Speak with open mic turned on. 
3: Maybe hear other peoples as well. 

**Expected behavior:**
Not do any of that. 

**Actual behavior:**
Does exactly that. Seems to be mixing up player communication servers or something. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No I have no mods. I'm not smart enough in the game to use mods yet. I can barely play this game default. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
\Steam\steamapps\common\Eco\Eco_Data\Server\Configs\Voice.eco

Please post the line "ServerVoiceIdentifier" and delete it afterwards, it should address the issue.
