### ISSUE TITLE
USER ISSUE: disappearing rocks

### ISSUE THREAD

**Issue by Thunkly** [StrangeLoopGames/EcoIssues#25037]
**User Id: (3cef06ce-96fd-49b8-7ee9-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
mine any rocks or ores
watch as half or more disappear

**Expected behavior:**
give me 4 rocks per block hit (or 2 + a double rock)

**Actual behavior:**
usually gives none, 1, 2, but rarely gives all 4 (&sometimes 2 + 1 med rock)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i think they run the discordlink mod on this server. everyone on here is complaining about missing rocks. I copied this for you to trace the server: User ID: 3cef06ce-96fd-49b8-7ee9-08dc8d1bff58
Server ID: 671f309d-3174-4fb2-8187-35574f0e95ab

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Dekoser** [comment]
Kinda same issue
just want to add that the mission stone reappear where i mined before and that it tracks the stone type
As when i mine sandstone like 50% drops where i mined the last sandstone, and that can be chunks away and dont matter if i mined granite in between
tested in fresh vanilla U11 offline world

**Comment by konstantinkuehn** [comment]
Placing walls on the location will force them to appear. Also sometimes I noticed stones say they can't be picked up cause of no access to the Homestead of someone else. Even if the stone is on the own homestead.

**Comment by Blackmanni** [comment]
This is kinda bonkers. Some Eco servers are terrible with this bug, some are better. but it has pretty much halted any progress that i need to make in any case. So, given this is still a decent sized issue thats still open, this is super disappointing. Hopeful this is fixed soon.

**Comment by globrm** [comment]
Come on guys, you got this!
Waiting for the fix <3
**Love u!**

**Comment by D3nnis3n** [comment]
Fixed in 11.0.2.
