### ISSUE TITLE
USER ISSUE: Vanishing Stone

### ISSUE THREAD

**Issue by RevButcher** [StrangeLoopGames/EcoIssues#25036]
\
**User Id: (7772b65e-2a99-4b44-d7cd-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Mine any stone with a pickaxe.

**Expected behavior:**
Stone block should turn into stone chunks on place it was mined.

**Actual behavior:**
Stone chunks vanish after block is mined and sometimes reappear in other areas, sometimes clipping with another block.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, I have no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25037
