### ISSUE TITLE
USER ISSUE: SP World won't load

### ISSUE THREAD

**Issue by Spiffor** [StrangeLoopGames/EcoIssues#25044]
\
**User Id: (4622d76c-e1b6-4155-ce23-08dcbdf315bf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1. Start a Singleplayer World.
2. quit game
3. try to continue playing

**Expected behavior:**
game world should load

**Actual behavior:**
Game World "loads" at 79 B/s which takes hours

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You currently need to restart the game after leaving a world, that is a known issue that will be addressed in the first hotfix.
