### ISSUE TITLE
Sever crashed

### ISSUE THREAD

**Issue by Isuya030** [StrangeLoopGames/EcoIssues#25041]
[log_240816081621.log](https://github.com/user-attachments/files/16637527/log_240816081621.log)
Hi,I copied the save data on my old pc to my new pc ,but I can't open the sever due to crash everytime.

**Comment by D3nnis3n** [comment]
Your server is corrupted. Please remove the /Mods/__core__ folder from your server (If local it's at /Steam/steamapps/common/Eco/Eco_Data/Server) and then verify files via Steam.
