### ISSUE TITLE
Projects in Research Bench sometimes don't show

### ISSUE THREAD

**Issue by robthomp** [StrangeLoopGames/EcoIssues#25046]
Sometimes the projects in the Research bench don't show up at the bottom of the crafting interface. See the attached screenshot. There is also another bug where the queued projects show up without the correct symbol and a time of 1234, but I'll be making a separate bug for that soon.  
![Screenshot 2024-08-16 102946](https://github.com/user-attachments/assets/7b1d8af5-ee7a-461b-aa54-60d70d59ecd2)

**Comment by Daniel-Magulado** [comment]
Hi @robthomp 

Thank you for submitting this bug report.
I can verify the issue and have created an internal report for tracking.

Ref: ECO-36249

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14529 in Update 11.1.
