### ISSUE TITLE
USER ISSUE: Welt laden bricht ab

### ISSUE THREAD

**Issue by Ngar1** [StrangeLoopGames/EcoIssues#25042]
\
**User Id: (96f4a396-1211-464a-6f47-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Laden einer Welt die in der vorgehenden Verison erzeugt wurde stockt, Download Rate sinkt auf 80 Byte bei unterschiedlichen Ladeständen (zB 24%, 42%)

**Expected behavior:**
Normales laden

**Actual behavior:**
Die folgende Fehlermeldung trat auf:
```
Vom Benutzer abgebrochen
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Mods hab ich deinstalliert

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the logfiles for client and server after trying to connect, as described here: https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-server-and-client-log-files-for-local-world

Also please note there is a known issue that reconnecting to a server is not currently possible - you need to restart the game, this will be addressed in the first hotfix.

**Comment by Ngar1** [comment]
close, If known than this is usless
