### ISSUE TITLE
USER ISSUE: PERTE D4OBJET

### ISSUE THREAD

**Issue by MONACO293** [StrangeLoopGames/EcoIssues#25049]
\
**User Id: (352f7ae6-5fe4-4d30-d554-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
JE REVIENS SUR MA PARTIE APRES AVOIR EU DU MAL A ME CONNECTER DEPUIS VOTRE MISE A JOUR ET LA MOITIER DES CHOSES DE MES INVENTAIRE ON DISPARUE.......

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com.
