### ISSUE TITLE
Project queue at the top right of player window doesn't show up correctly

### ISSUE THREAD

**Issue by robthomp** [StrangeLoopGames/EcoIssues#25047]
Sometimes when I queue up a project on a crafting table it will show up incorrectly. This can happen both in the top right of the screen when not in a crafting table, and also in the crafting table. See screenshot, it's the one that has the campfire symbol. This should have been a Dendrology Basic Research Paper but I've seen this happen with all sorts of objects/projects.
![Screenshot 2024-08-16 102946](https://github.com/user-attachments/assets/6933890c-a75a-472a-860d-5732df76363b)

**Comment by D3nnis3n** [comment]
This was fixed in 11.1.
