### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Oleganio** [StrangeLoopGames/EcoIssues#25043]
\
**User Id: (cd408473-6a6c-4abe-f5e8-08dcbcb28326)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method20813(Closure, IMvcNetClient, Object)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Cannot Convert Argument Type: Eco.Gameplay.Settlements.Settlement to BSON.

Error during packaging property 'Leader' of 'Eco.Gameplay.Settlements.Settlement'
Error during packaging property 'ElectionProcess' of 'Eco.Gameplay.Civics.Titles.ElectedTitle'
Error during packaging pr</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Oleganio** [comment]
[Player.log.copy.txt](https://github.com/user-attachments/files/16638709/Player.log.copy.txt)
[Player-prev.log](https://github.com/user-attachments/files/16638712/Player-prev.log)

**Comment by D3nnis3n** [comment]
Same root cause as https://github.com/StrangeLoopGames/EcoIssues/issues/25039, restart server should help as workaround.
