### ISSUE TITLE
USER ISSUE: Cannot join server, possibly because I'm a town leader

### ISSUE THREAD

**Issue by NickCaplinger** [StrangeLoopGames/EcoIssues#25050]
\
**User Id: (144b8ac5-aeb0-42aa-d502-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1. Become town leader of a draft town with an election in-progress
2. Disconnect from the game
3. Join the game

**Expected behavior:**
Allowed me to join the game.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method30396(Closure, IMvcNetClient, Object)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Cannot Convert Argument Type: Eco.Gameplay.Settlements.Settlement to BSON.

Error during packaging property 'Leader' of 'Eco.Gameplay.Settlements.Settlement'
Error during packaging property 'ElectionProcess' of 'Eco.Gameplay.Civics.Titles.ElectedTitle'
Error during packaging pr</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I have no client mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Same root cause as https://github.com/StrangeLoopGames/EcoIssues/issues/25039, restarting server works as workaround.

**Comment by NickCaplinger** [comment]
Cheers!
