### ISSUE TITLE
USER ISSUE: pb connection avec mon serveur

### ISSUE THREAD

**Issue by petithomme37** [StrangeLoopGames/EcoIssues#25053]
\
**User Id: (9e1587ef-3e98-4c9a-6d09-08dc8d11157e)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
bonjour,
le jeu ne se connecte pas au serveur a l'adresse ip 88.211.214.226:25565, il me dit qu'il est hors ligne. je l'ai ping pars l'intermédaire de la console il répond pas de paquet perdu.
merci de voir pourquoi il est injoingnable
cordialement

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
This server is in offline mode, but you are not - you cannot join it until it has been restarted in online mode.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server is in offline mode, likely because no credentials to login with a play.eco account were provided. You cannot join offline servers with a online client. This is not a bug. Make sure your server is correctly logged into a play.eco account.
