### ISSUE TITLE
USER ISSUE: Error After second joining to Sea Otter Official Server

### ISSUE THREAD

**Issue by globrm** [StrangeLoopGames/EcoIssues#25051]
\
**User Id: (c442f04d-db0e-4167-7bb1-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Log into Sea Otter Server

**Expected behavior:**
Log in successfully

**Actual behavior:**
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method26214(Closure, IMvcNetClient, Object)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Cannot Convert Argument Type: Eco.Gameplay.Property.Deed to BSON.

Error during packaging property 'Ownables' of 'Eco.Gameplay.Property.Deed'
Error during packaging property 'IsAuthorized' of 'Eco.Gameplay.Property.PropertyPlot'</size>

```

![image](https://github.com/user-attachments/assets/1b83e2ce-acec-40b4-817d-507d67c53e41)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO

**Please provide log files.

[Player.log](https://github.com/user-attachments/files/16641381/Player.log)

I've already try to verify files integrity, reinstall the game, delete local files %appdata%, rejoin, reset graphics configuration, changing windows system region and language, etc.

**Comment by globrm** [comment]
[Player.log](https://github.com/user-attachments/files/16641386/Player.log)

**Comment by globrm** [comment]
[player.eco.txt](https://github.com/user-attachments/files/16641591/player.eco.txt)

**Comment by D3nnis3n** [comment]
Same root cause as https://github.com/StrangeLoopGames/EcoIssues/issues/25039
