### ISSUE TITLE
USER ISSUE: Char hängt in der Werkbank fest

### ISSUE THREAD

**Issue by Greece62** [StrangeLoopGames/EcoIssues#25056]
\
**User Id: (51cf4bd8-10a5-4e20-76ab-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Ausgeloggt, wieder eingeloggt.
Char hängt weiterhin in der Werkbank fest.
Passiert auch in Baumstämme.

**Expected behavior:**
Der Char sollte nicht festbuggen, sondern wieder weg gehen können

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Bitte einmal /unstuck in den Chat eintippen. Das Problem selbst ist bereits bekannt.
