### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kazadrek78** [StrangeLoopGames/EcoIssues#25055]
Hello,
My game crash, i don't now why.
can you help me please.
[log_240817035351.log](https://github.com/user-attachments/files/16645335/log_240817035351.log)
[Player.log](https://github.com/user-attachments/files/16645336/Player.log)

**Comment by D3nnis3n** [comment]
Potential fix in staging via https://github.com/StrangeLoopGames/Eco/pull/14463..
