### ISSUE TITLE
Update 11: Random Crashes - Unknown Cause

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25054]
Have been getting completely random crashes.

I personally have not been able to figure out what is causing them as of yet but am working on it but they seem not to be related to my eye; thus I am starting this thread to throw logs into.

[Player.log](https://github.com/user-attachments/files/16645088/Player.log)

**Comment by Sarah-Graesyn** [comment]
[Player.log](https://github.com/user-attachments/files/16645771/Player.log)

Picked up Adobe and was walking to place it. (Server was modded so it is possible it was a mod conflict, Silverleaf Server)

**Comment by Sarah-Graesyn** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/25055 - adding the link for this one here

**Comment by Sarah-Graesyn** [comment]
[Player.log](https://github.com/user-attachments/files/16647245/Player.log)
picking tomatoes

**Comment by D3nnis3n** [comment]
Your crash is a memory access violation, your system just barely fulfills the minimum requirements.
Try to lower the graphic settings as low as any possible and if you have an SSD available and Eco isn't installed yet there, try to move it there - as of other players that was helpful in some cases.
