### ISSUE TITLE
USER ISSUE: After Exiting a world, game freezes when reconnecting	

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#25061]
\
**User Id: (be322995-342e-4507-733b-08dc8bebe8f1)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
Exit Server to Main Menu

Select Continue

Watch the game start to load

**Expected behavior:**
Game should connect to the server
[Player.log](https://github.com/user-attachments/files/16650073/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16650074/Player-prev.log)

**Actual behavior:**
Game gets stuck at 24% Game Downloading

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No Mods installed, except Discord Link on server (I think).   No local mods, My wife had the same issue yesterday.

[Player.log](https://github.com/user-attachments/files/16650073/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16650074/Player-prev.log)
**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/user-attachments/files/16650073/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16650074/Player-prev.log)

**Comment by D3nnis3n** [comment]
Already fixed in Hotfix 11.0.1.
