### ISSUE TITLE
Further server hosting impossible thanks to changes in update "beta 11"

### ISSUE THREAD

**Issue by Antaiir** [StrangeLoopGames/EcoIssues#25060]
Thanks to the changes coming with "beta 11" regarding authentication i can no longer maintain a dedicated server for my friends. 

Great job.

My friends wanna play ECO together, but none of them have the skills for setting up and maintaining a server, so they asked me for help. I did in the past until "beta 10".

Until "beta 10" the most stupid thing i've seen was hiding the _server_ files behind the paywall for the _client_, together with an annoying captcha checkback. I run all my servers on a headless linux vm. There's no working way to handle those f***n captchas, when you need to download updated server files at the command line.

Thus i always had to ask one of the guys that own the _client_, if he can log in and download the _server_ for me, send me the files, and i have to transfer them onto the server vm via an unnecessary circuitous way, instead of just downloading them directly onto the machine, where i need them.

At least i was able to start the server then, and my friends could play. Now with "beta 11" things are even more stupid, i can't even start the _server_ anymore, since i don't own the _client_. 

Since i don't own the client, i have of course no credentials for the server to pass the auth, and i also can't create a steamToken for that server. I even won't ever create such a token, because i would need register my smartphone with steam to be able to create a token. Hell will freeze, before steam will contaminate my phone!

And i can't even ask my friends if they can create such a token for me, since Valve doesn't allow to provide that token (or the login credentials) to a third party (me in this case).

Conclusion: my friends can't play ECO anymore, since there's no legit way for me to run a server for them.

Of course i could buy the game, just to get the needed credentials for running a server. But why should i do that? NO WAY! I don't wanna play ECO, so i won't buy it. Who on earth thought it's great idea, to force _server_ admins to own the _client_? Why on earth are the files for running a dedicated server not just available for everyone? I mean... seriously, you still need the client to play the game, don't you? It works for so many other games pretty well (Minecraft for example, no need of credentials for online mode). I've never came across any other game, that handles the server thing in such a annoying restrictive manner.

Thus i gave up in hosting the server for my friends for the time being, expect their complaints pretty soon. 

Well done...

**Comment by D3nnis3n** [comment]
To be able to efficiently enforce our terms of service and know who is responsible for the server we have decided that worlds that are not locally hosted via the game ("dedicated server") or in offline mode require a registration - that is the same as for example Valve does with their games, just that they - as you noted - require a token from a Steam account with mobile phone verification.

For Eco it is only required that someone that owns the game creates an account on the website and logs in with that on the server, tokens will be available soon as well - so one of the players playing on the server would be able to give you the token to start the server in the near future.

I understand your frustration, but any of the players that own the game could host the server with their credentials.

**Comment by Antaiir** [comment]
As i already said "Minecraft for example, no need of credentials for online mode", i rate this as an design issue with the ECO server.

As i also said "none of them have the skills for setting up and maintaining a server", i doubt, your advise "any of the players that own the game could host the server with their credentials" would help any one in any way. Do you really believe, they get the abilities for setting up and maintaining a dedicated server out of nowhere, just because you throw a club between our legs? Why might they have asked me for support?

And i also said, i don't play the game, so i won't buy it. Thus, i (have to) stop hosting a server for your game and the guys (just have to) play something else then. In case that was the goal of such a design decision, i would say: mission accomplished.

It's no frustration on _my_ end, since i'm not playing ECO. The decision to hide the server packages behind the paywall for the client is the main reason for my aversion, just saying.

I host dedicated servers for several games, but ECO is the first server i stop hosting because of it's nerve-racking behavior... and it's not even out of it's early access phase. Even the process of just updating it on a headless server environment via remote SSH connection on the command line was pain in the... well, you know.

However, thanks for your answer. But it doesn't seem, this situation will change in the (near) future, when i read between the lines.
