### ISSUE TITLE
Request rate is large

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25064]
[19:53:17.154] [496] [Error] [Eco] Internal Server Error

Status: 500
Response: 

Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: 42187810-a80b-427b-9d61-8ea0802670b3; Reason: (
Errors : [
  "Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"
]
);
 
Response: 

Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: 379e2735-bb8b-488b-986e-d3af7b9831de; Reason: (
Errors : [
  "Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"
]
);
 

Status: 500
Response: 

Response status code does not indicate success: TooManyRequests (429); Substatus: 3200; ActivityId: 136be15b-0314-4a96-904a-aefd9b832a5c; Reason: (
Errors : [
  "Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"
]
);

**Comment by D3nnis3n** [comment]
Was fixed yesterday after report.
