### ISSUE TITLE
NullReferenceException after logging out while holding claim tool

### ISSUE THREAD

**Issue by AWL-Gaming** [StrangeLoopGames/EcoIssues#25075]
User Id: b3731f52-8996-40cf-6a17-08dc8d1bff58
Version: 0.11.0.0 beta release-693

**Steps to Reproduce:**
Logout while claim tool is equipped then try to rejoin the server.

**Expected behavior:**
Join the server back with no exceptions

**Actual behavior:**
The following error message popped up:

```properties
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Anonymously Hosted DynamicMethods Assembly

System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method93198(Closure, IMvcNetClient, Object)
   at Eco.Core.Controller.ControllerPacker.PackageMember(BsonSerializationContext& context, IController controller, ISyncMemberInfo memberInfo)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Cannot Convert Argument Type: Eco.Gameplay.Settlements.Settlement to BSON.

Error during packaging property 'Parentage' of 'Eco.Gameplay.Settlements.Settlement'
Error during packaging property 'ChildrenSettlementRoster' of 'Eco.Gameplay.Settlements.SettlementParentage'
```

![Screenshot (2)](https://github.com/user-attachments/assets/864ab0ed-04f5-4ab9-805a-fe224879e517)
![Screenshot 2024-08-19 055405](https://github.com/user-attachments/assets/b7372da8-35eb-4f89-9027-e425908c13ab)

**Workaround:**
Restart server.

Crash log:
[Server encountered an exception copy.txt](https://github.com/user-attachments/files/16656097/Server.encountered.an.exception.copy.txt)

**Comment by D3nnis3n** [comment]
Already fixed in Hotfix 11.0.1.
