### ISSUE TITLE
Day 12 server only loading 48% on login

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2507]
This is a day 12 server that was running fine yesterday and allowing logins.  Today, day 12 when users are trying to log in the process stops at 48% and just hangs.  I don't know if this world has become a water world and that is the issue or if there is another problem,  It is not generating any dump files and appears in console to be running normally.  I was on this server on day 11 checking it out for issues that might mean it was headed to be a flooded world and everything was normal and fine and no problems.  Now on day 12 no one can access it.  We have restarted a few times.
https://www.dropbox.com/s/ts2g4slu4gngf41/BW_Storage.zip?dl=0

This is a 6.0-alpha server - 200X200 size - otherwise no mods or other edits

**Comment by pamduncan** [comment]
A second server in same state.  I was on yesterday and so were others and the world was fine.  Now reached day 12 and server will no allow any player to access the server - it hangs at exactly 48% when you try and log in.  No idea what state the world is in an if its become another water world because there is no way to get in. There are no dump files created and console looks normal

https://www.dropbox.com/s/jjse0xj25ojiel6/UK_killservers_Storage.7z?dl=0

**Comment by johnkslg** [comment]
Probably flooding issue, large flooded world would break. Working on it.

**Comment by johnkslg** [comment]
Flooding would do this, should be fixed now.
