### ISSUE TITLE
World Objects can take very long time to update their status.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25079]
We've had a major performance degradation last night where suddenly all world objects worldwide would take upwards of 2-3 minutes to update their status after placing down. This happend with around 80-90 people online at the time and roughly 2-3 hours after restart.

What I mean is for example a Butchery Table placed down would claim it's not inside a room for solid 2-3 minutes.

**Server restart fixed this** and the issue did not reoccur yet but it feels like objects do take longer than usual to detect they are in a room.

For example now we have 83 people online and it has been 2.5 hours since restart and it takes roughly 3-4 seconds for a Research Table to realize that it is inside a room. 

I hope it doesnt get worse over time.

There was nothing in the server Log indicating an issue and I'm not able to reproduce it on demand.

Jut putting the info out there.

**Comment by D3nnis3n** [comment]
We'd need a profiling when that happens, otherwise there is nothing we could investigate. We've not seen a similar issue on official servers so far, but there is a inventory freezing issue that stops timers that sometimes appear we're looking into. If you could provide a profiling when the issue appears again, that would be helpful.

**Comment by D3nnis3n** [comment]
Assuming its the same issue as here, merging: https://github.com/StrangeLoopGames/EcoIssues/issues/25119

**Comment by padmanek** [comment]
> Assuming its the same issue as here, merging: #25119

Yes, I just couldn't provide profiling anymore since your reply took a while and we finished a wipe before that.

**Comment by padmanek** [comment]
And yes the issue was reoccurring throughout the entire 2 week wipe. Only scheduled restarts every 6 good hours would keep the roomd in workable state.
