### ISSUE TITLE
USER ISSUE: I am not cheating?

### ISSUE THREAD

**Issue by MehmetCakirkaya** [StrangeLoopGames/EcoIssues#25072]
\
**User Id: (396b4ef9-b793-4d52-d6ae-08dcbd395caf)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server you play on has a experimental movement hack detection active, you can tell the admin to disable it in Users.eco: "MovementHackDetection": false.
