### ISSUE TITLE
USER ISSUE: World download extremely slow

### ISSUE THREAD

**Issue by NjitRam83** [StrangeLoopGames/EcoIssues#25076]
\
**User Id: (c1ffa4d3-235e-4965-ba91-08dcbe0ab005)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
1. Try to join a world
2. World gets downloaded
3. Starts at couple MB/s
4. Download speed slows down to 50B/s (yes thats BYTES per second)

**Expected behavior:**
World download speed should be normal

**Actual behavior:**
The following error message popped up:
```
Cancelled by user
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
It has happened at all servers I am trying to connect to for the past few days. At least 4

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be addressed with Hotfix 11.0.1, if the issue persists please create a new issue and attach your logfiles as noted in the issue template.
