### ISSUE TITLE
USER ISSUE: freezing at 25% 

### ISSUE THREAD

**Issue by Mdye99** [StrangeLoopGames/EcoIssues#25074]
\
**User Id: (6be1f443-6b26-49ba-6780-08dc8d1bff58)**
**Version:** 0.11.0.0 beta release-693

**Steps to Reproduce:**
login

**Expected behavior:**
enter the server

**Actual behavior:**
loading server stops at 25%

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and i don't know

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This should be addressed with Hotfix 11.0.1, if the issue persists please create a new issue and attach your logfiles as noted in the issue template.
