### ISSUE TITLE
Consolidate button makes items disappear

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25078]
https://github.com/user-attachments/assets/f296ec88-a18c-4bea-90a1-35d0c12be477

Claim paper from read Skill Scroll + Town Claim Paper  disappeared when Consolidate button pressed.

0.11.0.0 beta release-693
fresh server files, no mods, default config except Claim Papers from Skill Scrolls enabled

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14499 in staging.
