### ISSUE TITLE
Crash right after loading local server

### ISSUE THREAD

**Issue by manson87** [StrangeLoopGames/EcoIssues#25085]
![eco1](https://github.com/user-attachments/assets/8412f1c1-67b7-4402-a4a4-63ea36ed2fbf)
[log_240820060800.log](https://github.com/user-attachments/files/16678680/log_240820060800.log)

Hi there,

i updated Eco to V11.0.1.
Since the update i can´t load my local server.
I have one mod installed, the mod is up to date (mod was updated today).
I get the error after a few seconds if i click on continue (don´t know the exactly english button name, have the game in german).

Hardware
CPU: Ryzen 9 3900x
RAM: 32gb DDR4
GPU: GTX1080TI
HDD: Game is installed on HDD (not SSD), had no issues before

Any other questions? Feel free to ask :)

I hope you can help, have a nice day

**Comment by D3nnis3n** [comment]
Please upload the savegame somewhere and link it here - make sure it's available without registration.

**Comment by D3nnis3n** [comment]
I was able to start, migrate and play on the save without issues.
Try the migrated savegame: [savegame.zip](https://github.com/user-attachments/files/16685862/savegame.zip)

**Comment by manson87** [comment]
it seems working. at 1st try there was an error, 2nd try it works. i close the case, if i have another issues i will open a new one.
thanks a lot for your super fast help :D
