### ISSUE TITLE
USER ISSUE: Animal pelt marketplace items are slightly mechanically different.	

### ISSUE THREAD

**Issue by DeciusBrutus** [StrangeLoopGames/EcoIssues#25087]
\
**User Id: (94e3416a-ad9f-4d9a-c85e-08dcbd8319be)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**
View Hare pelt recepies. View marketplace variants of the Hare Pelt recepies. Observe that they use different materials. 

**Expected behavior:**
Marketplace recepies should use materials identical to the base recepies, and produce outputs mechanically identical. Recipes which are mechanically different should not be restricted to marketplace items. 

**Actual behavior:**
The various marketplace recipies each use different materials. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No known mods, issue is independent of mods. 

Log file omitted intentionally.

**Comment by D3nnis3n** [comment]
Fixed in 11.0.2, they will now all take medium carcasses, thanks for making us aware.
