### ISSUE TITLE
[Suggestion] New Store features - QoL Improvements

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25088]
I would like to propose some quality of life (QoL) improvements for the store UI in ECO:

1. Enhanced Buy Order Information:

- When a buy order is placed, display two numbers: one for the desired quantity and another for the maximum quantity the buyer can handle based on their current storage capacity (which could be expanded with credits).
- This feature would prevent the frustration of transporting materials to a buyer who cannot complete the transaction due to insufficient storage. It ensures that sellers can make informed decisions before expending resources and calories.

2. Sell Max Button:

- Introduce a “SELL MAX” button when fulfilling a buy order. This button would automatically fill the quantity field with the total amount of the item the seller currently possesses.
- This addition would streamline the selling process, making it more efficient and user-friendly.

**Comment by D3nnis3n** [comment]
Please note that this is a bug tracker, you can create suggestions on our feedback tracker: https://feedback.play.eco.
