### ISSUE TITLE
Need collapsible sub-categories and expandable separator for graphs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2508]
The 'humans' stat is miles long, need to make each sub category collapsible.  Also need to make that mid-bar movable so you can see the whole text.
![image](https://user-images.githubusercontent.com/3536496/31403136-1453fd60-adad-11e7-8101-f8ed20c75d73.png)

**Comment by MarjieAVolk** [comment]
Yeah - also I've always intended you to be able to show a graph for the parent keys, eg. you can show a graph for All/Sell/Asphalt, or you can show a graph for just All/Sell.  I believe the server side code is all there to do that
