### ISSUE TITLE
USER ISSUE: Mabye its a mistake	but still ask.

### ISSUE THREAD

**Issue by WookyCS** [StrangeLoopGames/EcoIssues#25081]
\
**User Id: (8f66fa92-58b0-44a2-bf29-08dcbd51a712)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**
I just byz another coins from you to help with game  but it did not came to my acc. first time when i buy them after card pusuase was in a minute. now i pursuase another coins but no coins came to my acc ... my bank on screen show me i paid but nothing hapend ... plese can you check it because i dont got much money but still want to help with this great game... Thank you ... 

**Expected behavior:**
Plesae check it 

**Actual behavior:**
If nothing i want money back or bigger bonus on coins.... 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I dont know its a new version on server and developer already said there are problems.... 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com with the e-mail of your play.eco account or note your Steam account if you purchased via Steam. Account issues can only be resolved there.
