### ISSUE TITLE
USER ISSUE: work party

### ISSUE THREAD

**Issue by Mdye99** [StrangeLoopGames/EcoIssues#25083]
\
**User Id: (6be1f443-6b26-49ba-6780-08dc8d1bff58)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**
after taking a work party the table stays red

**Expected behavior:**
the table should turn green indicating access has been given to the table	

**Actual behavior:**
the table remains red as if no access has been given, but you can still add labor

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and idk

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Mdye99 

Thank you for submitting this bug report.
I can confirm the issue and have created an internal report for tracking.

Ref: ECO-36253

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14514 in staging.
