### ISSUE TITLE
USER ISSUE: Tractor scoop not listable in store

### ISSUE THREAD

**Issue by Makkari** [StrangeLoopGames/EcoIssues#25094]
\
**User Id: (c0283e61-9ad9-4aba-8cf7-08dc8d1bff58)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Open menu to add item to store page, seach for Steam Tractor Scoop

**Expected behavior:**
Find the item steam tractor scoop so it can be selected

**Actual behavior:**
The scoop does not shop up in the list

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Makkari 

Thank you for submitting this bug report.
We are currently aware of this issue and we're working on a fix to be implemented in the upcoming game updates.

Ref: ECO-35501
