### ISSUE TITLE
USER ISSUE: The server says that it's online but when I join it kicks me

### ISSUE THREAD

**Issue by NoahFortune** [StrangeLoopGames/EcoIssues#25096]
\
**User Id: (fd4d4fb1-8972-4c4b-562f-08dcbfacb854)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Wait aprox 1-2 minutes so it say's that it's online.
Join and wait aprox 20-40 seconds.
Then it will kick you.

**Expected behavior:**
It should've loaded me into the game instead of kicking me.
It happenes to all my friends aswell.

**Actual behavior:**
The following error message popped up:
```
Failed to connect - connection timed out.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, the server is vanilla

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
There is no information hinting to a bug, the error simply states that a connection could not be established.
Likely the reason is networking issues, support@strangeloopgames.com may be able to provide some tips.
