### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Nateagoff** [StrangeLoopGames/EcoIssues#25091]
\
**User Id: (bd74b604-03a9-4339-3652-08dcc0749632)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**

**Expected behavior:**
se connecter au serveur

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Failed to get world ticket:

Internal Server Error

Status: 500
Response: 

User does not own Eco.

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The account you try to play with doesn't own Eco or your steam account is linked to an SLG account that doesn't own Eco - in both cases only customer support at support@strangeloopgames.com can help with that, as it needs access to sensitive data. Please reach out there.
