### ISSUE TITLE
USER ISSUE: haus bau

### ISSUE THREAD

**Issue by Denno32** [StrangeLoopGames/EcoIssues#25099]
\
**User Id: (1defb831-fc00-42f2-3d56-08dcc0749632)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
man kann keine häuser bauen um tische zu bauen muss man eine haus besitzen 

**Expected behavior:**
	aktuell nicht spiel bar weill man nur kochen kann und kein zimmerman tische oder so bauen kann 		
	

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Kann ich nicht nachvollziehen, du kannst Häuser aus Adobe bauen. Bitte an support@strangeloopgames.com wenden, wenn du damit Probleme hast.
