### ISSUE TITLE
Figure out world size constraints and disallow invalid worlds

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2510]
I'm guessing the resulting world mainly needs to be divisible by all the layer voxel sizes?

**Comment by metachronism** [comment]
shouldn't world layers handle worlds of any size instead?

**Comment by SeanAtr0n** [comment]
how would that work? VoxelsPerEntry=4 ... so for odd voxel sizes you'd have 2 missing voxels

**Comment by SeanAtr0n** [comment]
seems like making world layers work with any size would be much more difficult than restricting sizes

**Comment by metachronism** [comment]
restricting sizes is way too limiting when the variability of world layers is high

having one set of voxels on the edge that are slightly off doesn't seem like a big deal

**Comment by SeanAtr0n** [comment]
So should we also allow 10x1000 worlds?

**Comment by knexer** [comment]
Then let's have less variable world layer resolutions.  If we limit those to {1, 5, 10, 20, 40} we could limit worlds to a multiple of 4 chunks - pretty reasonable.

**Comment by knexer** [comment]
This is done
