### ISSUE TITLE
USER ISSUE: cart doesnt move

### ISSUE THREAD

**Issue by TheCableMan24** [StrangeLoopGames/EcoIssues#25101]
\
**User Id: (37c2513a-9696-4357-d11c-08dcbfa534f2)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
i cant move a cart, powered cart or anything. others can no issue

**Expected behavior:**
to move the cart

**Actual behavior:**
cart doesnt move for me, no one else on server has issue

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not reproducible, please check if you have any sort of controller connected and remove it. If that doesn't help, please reach out to support@strangeloopgames.com.
