### ISSUE TITLE
Visual Glitch in Giant Panda

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25106]
I encountered a visual glitch while playing in the Giant Panda biome.

Steps to Reproduce:

I was eating a Beet Campfire Salad.
While the eating animation was still on the screen, I started paddling my small canoe.
This resulted in my fork getting stuck into the paddle.
Additional Information:

When I hopped off and then back into the canoe, the fork disappeared, and the animation worked as expected.

![20240826060545_1](https://github.com/user-attachments/assets/be0d4ada-56b7-48e3-a4bc-7f2b8352eee5)

**Comment by Daniel-Magulado** [comment]
Hi @Crazy-Spy 

Thank you for submitting this bug report.
I was able to verify and have created an internal report.
A fix should be implemented soon.

Ref: ECO-36242
