### ISSUE TITLE
Parts tab is showing wrong information.

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25103]
![image](https://github.com/user-attachments/assets/c443145b-eac7-4360-a688-a422e16eef6f)
![image](https://github.com/user-attachments/assets/daf0fdab-230e-40ab-96c6-fab1e4d20df7)

issue should be self explaining

**Comment by Daniel-Magulado** [comment]
Hi @padmanek 
Thank you for submitting this bug report.
I am able to verify this issue and have created an internal report for tracking.

Ref. ECO-36256

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14452 in staging.
