### ISSUE TITLE
USER ISSUE: Wrong direction of movement direction arrow on map

### ISSUE THREAD

**Issue by Daronius** [StrangeLoopGames/EcoIssues#25114]
\
**User Id: (f2803899-4920-4815-7acf-08dc8d1bff58)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
1. Align with the grid in N/S direction (red arrows)
2. look at the map to that little yellow arrow (blue arrows)

![grafik](https://github.com/user-attachments/assets/9b86bb76-a309-4915-a997-078c7ea23c7b)

**Expected behavior:**
Arrow should point into the correct direction

**Actual behavior:**
Arrow points ~45° to the left

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thank you, that has already been tracked internally, as such I'm closing this issue.
