### ISSUE TITLE
USER ISSUE: dariy2287

### ISSUE THREAD

**Issue by dariy2287** [StrangeLoopGames/EcoIssues#25117]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.1 beta release-310

**Steps to Reproduce:**
правельный пароль а не могу войти

**Expected behavior:**
сменить пароль

**Actual behavior:**
Было получено следующее сообщение об ошибке:

Неверный логин или пароль.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**


**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You are using an extremely outdated Eco version, please update to the most recent one.
