### ISSUE TITLE
6.0.1 Correctly blocking login during world creation - needs to say that

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2511]
Latest staging of 6.0.1 #F0606345 is blocking log in attempts while world is creating - this is as expected and is working correctly but I think that instead of just giving a 'connection failed' message which does not let anyone know if the build has failed or other problem the message should say "World is Currently Under Contruction.  Please try again soon!"

**Comment by SeanAtr0n** [comment]
Did the players manually enter the IP address to find it or did it actually appear in the server browser?
