### ISSUE TITLE
USER ISSUE: Tracteur

### ISSUE THREAD

**Issue by Skeatex** [StrangeLoopGames/EcoIssues#25118]
\
**User Id: (08f3065e-4d52-4958-3630-08dcc0749632)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Installer un module fourche sur un tracteur	

**Expected behavior:**
le tracteur se comporte normalement

**Actual behavior:**
Le tracteur ne peut pas tourner à gauche. Il peut par contre tourner à droite	

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Unable to reproduce with the given steps, can you provide a video?

**Comment by D3nnis3n** [comment]
Closing due to not being reproducible and no further information provided. Feel free to open a new issue if you can provide more information.
