### ISSUE TITLE
USER ISSUE: debut 

### ISSUE THREAD

**Issue by bastsoub** [StrangeLoopGames/EcoIssues#25112]
\
**User Id: (slg122198)**
**Version:** 0.10.0.4 beta release-557

**Steps to Reproduce:**
lancer le monde

**Expected behavior:**
choisir un point d'apparition

**Actual behavior:**
aucun interaction possible pour le realiser

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non je n'est pas de mods installés

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update your game to the most recent version, you are many versions behind.
