### ISSUE TITLE
USER ISSUE: twitch int is broken	

### ISSUE THREAD

**Issue by TacticalSoure** [StrangeLoopGames/EcoIssues#25123]
\
**User Id: (423741f1-9c41-4797-b0aa-08dcc77f38a5)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
go to settings, twitch/then sent to a 4040

**Expected behavior:**
opened up the integration approval page through twitch api

**Actual behavior:**
recieved a 404 error

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in playtest via https://github.com/StrangeLoopGames/Eco/pull/14421.
