### ISSUE TITLE
Medium shipyard causes crash.

### ISSUE THREAD

**Issue by pondobruin85** [StrangeLoopGames/EcoIssues#25128]
We had a player place a medium shipyard, which then caused a fail to compile on reboot.  I was told to post the server files here.  Attached is the crash log.  My workaround was to comment out the parts section of medium shipyard in an override file.
[log_240901095602.log](https://github.com/user-attachments/files/16830085/log_240901095602.log)

I have the gamestate save, but it is 92MB, and github has a 25MB limit.  I am pondobruin85 on discord for any followup.  I can transfer via drive or other means if requested.  

Cheers
-Seth

**Comment by pondobruin85** [comment]
Per the player, the shipyard disappeared immediately when he placed it.

**Comment by D3nnis3n** [comment]
Caused by a mod as per Jens, hence closing.
