### ISSUE TITLE
USER ISSUE: stuck while planting a sedar

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [StrangeLoopGames/EcoIssues#25120]
\
**User Id: (1afcab0b-84f2-4e69-080b-08dcc69e5b43)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Unable to describe the steps to reproduce in detail. I will provide an account of actions taken. Due to the underdeveloped functionality of this GUI element this text has to be in one big blob. I went up a ridge where cedars can be planted. I planted one and made a hoed patch for an other one. I planted that and that's when I caught stuck.	

**Expected behavior:**
I expected to be able to move through the terrain freely with the various direction and jump keys. 

**Actual behavior:**
Video effects are shown. No change in position is recorded by the game nor shown.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. No clue since I have no mods installed. It happened without any mods installed. Which means is a problem within the game engine.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GeertJanVanDerWolf** [comment]
[Player.log](https://github.com/user-attachments/files/16816831/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16816834/Player-prev.log)

**Comment by D3nnis3n** [comment]
You can use /unstuck to free yourself in the meanwhile, unfortunately without repeatable reproduction steps there is no way to investigate the issue, but several issues potentially stucking players are known.
