### ISSUE TITLE
USER ISSUE: Server Excaption thrown when trying to log in to WT

### ISSUE THREAD

**Issue by MNight75** [StrangeLoopGames/EcoIssues#25125]
\
**User Id: (6c72faa5-0705-4bc2-16b2-08dcb1a2d5c1)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Try to log in.

**Expected behavior:**
it should log in. 

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60,00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Economy.BankAccount.CanAccess(IAlias alias, AccountAccess access, Boolean ...

Check log file to see full message.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
standard stock White Tiger. 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Was this a one-time occurance? It seems logged as a single occurance on the server logs.

**Comment by D3nnis3n** [comment]
Potentially caused by renamed personal bank accounts (which was only possible for a short time), added additional debug information for next update if it reappears on a new save, but no fix found as issue not reproducible.
