### ISSUE TITLE
Frequent game crashes even when idling

### ISSUE THREAD

**Issue by AWL-Gaming** [StrangeLoopGames/EcoIssues#25124]
Game is crashing a lot after the v11 update. These crashes appear to be the same for everyone regardless of the hardware or type of gameplay. 
Occurs randomly so can't replicate.

**Player 1 log (Crash when switching servers):**
[Player.log](https://github.com/user-attachments/files/16825277/Player.log)
**Player 2 log: (Crash when playing normally):**
[Player-prev (3).log](https://github.com/user-attachments/files/16825287/Player-prev.3.log)
**Player 3 log (Crash when idling):**
[Player-prev.log](https://github.com/user-attachments/files/16825291/Player-prev.log)

All of these logs were taken from different PCs each with their specific configs and settings.

**Comment by AWL-Gaming** [comment]
Crashes are less frequent now with Hotfix 11.0.3. The crash on rejoining a server still persists and is similar to what's mentioned above.

**Comment by AWL-Gaming** [comment]
**Additional logs (v0.11.0.4:**
[Crash_2024-09-07_211632491.zip](https://github.com/user-attachments/files/16920684/Crash_2024-09-07_211632491.zip)

**Comment by D3nnis3n** [comment]
Potential fixes in staging via https://github.com/StrangeLoopGames/Eco/pull/14463.

The logs contain tons of bad mod related errors that can cause crashes, though:
![image](https://github.com/user-attachments/assets/e86a7251-8556-4c7a-8756-28d48ede8104)

These problems should be addressed in the mods.
