### ISSUE TITLE
USER ISSUE: Store Checkout Bug

### ISSUE THREAD

**Issue by MNight75** [StrangeLoopGames/EcoIssues#25126]
\
**User Id: (6c72faa5-0705-4bc2-16b2-08dcb1a2d5c1)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Select item at store, add quantity to buy click purchase. 
When the Black dialogue with Green YES and Red NO button appears, pressing ENTER causes a consistent crash EVERYTIME.	

**Expected behavior:**
In the past pressing enter selected YES and finished the sale. 

**Actual behavior:**
The following error message popped up:
```
Failed to process a request. Probably the client incompatible with the server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods except White Tiger Mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @MNight75 

Thank you for your bug report. Our QA team has confirmed and reproduced the issue. We appreciate your support in helping us improve the game.

Ref. ECO-36298

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14489 in 11.0.7.
