### ISSUE TITLE
USER ISSUE: User does not own Eco

### ISSUE THREAD

**Issue by unlmtdcrtvty** [StrangeLoopGames/EcoIssues#25129]
\
**User Id: (fe095d10-b840-40b0-a2b7-08dccb33c04c)**
**Version:** 0.11.0.3 beta release-715

**Steps to Reproduce:**
try to join literally any world. I just purchased through steam, steam is connected to Eco accorcding to eco website. My only hunch is that I purchased Eco several years ago and had it refunded

**Expected behavior:**
join the world

**Actual behavior:**
The following error message popped up:
```
Authentication handshake failed with exception:
User does not own Eco.

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods, just downloaded game

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
That is caused by the refund, it takes up to 24 hours until the SLG account recognizes that the game was rebought on Steam. You can quicken that up by sending a mail to support@strangeloopgames.com with your SLG ID from the website.
