### ISSUE TITLE
USER ISSUE: Game crash when clicking on unauthorized chat channel

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#25121]
\
**User Id: (be322995-342e-4507-733b-08dc8bebe8f1)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
I selected a chat that was referenced by a citizen of town, to see if I could join it.    The moment I clicked it, the game booted me and gave me the below error.  I used the Referenced by section below the persons name.

**Expected behavior:**
I would have excpected it to give a warning about not being added to that channel.

**Actual behavior:**
The following error message popped up:
```
Server encountered an exception:

<size=60.00%>Exception: ArgumentNullException
Message:Value cannot be null. (Parameter 'source')
Source:System.Linq

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Eco.Gameplay.Systems.Messaging.Chat.Channels.Channel.CanAccess(User user, AccountAccess access)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatSettings.EnsureTabExistsForReceiver(User user, IChatReceiver receiver, Boolean activateTab, Boolean activateChat)
   at Eco.Gameplay.Systems.Messaging.Chat.ChatManager.SetChatReceiver(Player player, IChatReceiver receiver, Boolean activateChat)
   at Eco.Gameplay.Systems.Mess</size>...

Check log file to see full message.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by sirPattrick** [comment]
[Player.log](https://github.com/user-attachments/files/16820177/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16820178/Player-prev.log)

**Comment by sirPattrick** [comment]
![image](https://github.com/user-attachments/assets/4318ff18-57f3-42aa-800a-9752a5985dfe)
Please note that if I select the top version, it puts the #Buildingth as my chat, but if I select the bottom one it crashes.   The Channel was created by this individual.

**Comment by Daniel-Magulado** [comment]
Hi @sirPattrick 

Thank you for your bug report. Our QA team has confirmed and reproduced the issue. We appreciate your support in helping us improve the game.

Ref: ECO-36297
