### ISSUE TITLE
USER ISSUE: bug

### ISSUE THREAD

**Issue by Lady79Gamer** [StrangeLoopGames/EcoIssues#25132]
\
**User Id: ()**
**Version:** 0.10.1.5 beta release-619

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>Failed to decrypted and authenticate Steam ticket</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the most recent version of Eco.
