### ISSUE TITLE
Can't put the object "Store"

### ISSUE THREAD

**Issue by CoblGP** [StrangeLoopGames/EcoIssues#25131]
Normally, when you get an interactable object, you get a UI that contains rotation or where to build a screen, but in my case, I don't get any screen. The object function doesn't even start.

I will drop the log files and video of the problem.

[https://www.youtube.com/watch?v=np_eA0dCc6w](url)

[Player.log](https://github.com/user-attachments/files/16852336/Player.log)
[Player.log.copy.txt](https://github.com/user-attachments/files/16852337/Player.log.copy.txt)
[Player-prev.log](https://github.com/user-attachments/files/16852338/Player-prev.log)

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25131
