### ISSUE TITLE
USER ISSUE: Recipies not working, wrong tool

### ISSUE THREAD

**Issue by Serraff** [StrangeLoopGames/EcoIssues#25136]
\
**User Id: (9e97a479-31e7-440d-512d-08dc8d11157e)**
**Version:** 0.11.0.3 beta release-715

**Steps to Reproduce:**
1. Craft Bathtub, small sink and Toilet recipe at Kiln
2. Craft Rivet recipe at blast furnace

**Expected behavior:**
Craft the item wanted

**Actual behavior:**
1. A Pottery table is needed to craft x
2. A Power hammer is needed to craft Rivet recipe

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is not a bug, you need the respective tables to be present in the same room to craft the recipes.
