### ISSUE TITLE
6.0.1 #F0606345 staging hanging on login at 100%

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2513]
6.0.1 #F0606345 staging haning on login at 100% on a couple of severs.  No dump file is created and no issue seen on client.  This is happening to all attempted logins from various players.  World is created and showing idel on console but just loads up to 100 and stays there - does not let anyone in game.  Attaching game.eco from both servers - there are no dump files

https://www.dropbox.com/s/91eqzeehsiexisu/Game.zip?dl=0

https://www.dropbox.com/s/uwx416c4rcbxt7b/Game2.zip?dl=0

**Comment by pamduncan** [comment]
I found out this happens if you use 'disconnect' to leave a server and then try to connect to another one.  If you Quit out completely and restart the game you can log into the worlds.

**Comment by metachronism** [comment]
should be fixed in upcoming staging.
