### ISSUE TITLE
Shovel/s config

### ISSUE THREAD

**Issue by pflannigan** [StrangeLoopGames/EcoIssues#25144]
Howdy folks, having trouble understanding how to change the default shovel max in the configs, every time i do it either reverts or throws an exception. any help would be appreciated

**Comment by D3nnis3n** [comment]
There is no configuration settings for the shovel carry capacity, you are likely trying to mod some files - we cannot offer support for that, but you may find help in the modding channels of our discord at https://discord.gg/eco.
