### ISSUE TITLE
USER ISSUE: We can not trigger the tractor on digging trigger

### ISSUE THREAD

**Issue by kingplay98** [StrangeLoopGames/EcoIssues#25147]
\
**User Id: (c02f20bc-73d8-4dd6-6aff-08dc8cbaa722)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
Write a law with trigger"dig or mine"

Select the tool used.

**Expected behavior:**
We should be able to trigger the tractor with the bucket.

**Actual behavior:**
We can only trigger skid and excavator

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.
Yes.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14515 in staging.
