### ISSUE TITLE
Pipes showing spraying water after being disconnected do not stop showing spraying water after being reconnected

### ISSUE THREAD

**Issue by MNight75** [StrangeLoopGames/EcoIssues#25145]
This is on White Tiger, in Unica at the public laboratory. My understanding is Pandadono had moved the lab or otherwise disconnected the water at some point in the setup, causing the water to spray. Once the connections were fixed and the lab was working, the water on both input and output side continue to show a visible spray such as when the pipes are connected to a pump on one end and open on the other. 
![Screenshot (428)](https://github.com/user-attachments/assets/d607015f-ee85-4d04-b12c-75d6b9dc3ad5)

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14480 in 11.0.6.
