### ISSUE TITLE
USER ISSUE: Removing Homestead Claim Stake unclaims land but does not delete Deed

### ISSUE THREAD

**Issue by M4XoR** [StrangeLoopGames/EcoIssues#25149]
\
**User Id: (ae2c7393-30a2-4a31-b846-08dccd5ea5d2)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
1. Place Homestead Claim Stake -> Deed gets created
2. Remove Homestead Claim Stake -> Warning is displayed
3. Click yes 
4. Land gets unclaimed, but Deed is still existent

**Expected behavior:**
Unclaiming the Land should delete the Deed

**Actual behavior:**
Empty Deed is still existent.
Effects are e.g. prevention of creation of new Deed with same name (This is how I noticed that the Deed is still existent)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in staging via https://github.com/StrangeLoopGames/Eco/pull/14456.
