### ISSUE TITLE
USER ISSUE: CANT EXIT THE CRANE

### ISSUE THREAD

**Issue by mxtxhxsd** [StrangeLoopGames/EcoIssues#25140]
\
**User Id: (395d155a-c282-41aa-f5f7-08dcbcb28326)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
enter the crane white E
not being able to exit the crane 
have to exit whit /unstuck

**Expected behavior:**
well i shold be able to exit whit E

**Actual behavior:**
cant exit

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO and yes 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed in staging via https://github.com/StrangeLoopGames/Eco/pull/14415.

**Comment by mxtxhxsd** [comment]
your link is not working
