### ISSUE TITLE
USER ISSUE: Buying Credits

### ISSUE THREAD

**Issue by WhiteHowler02** [StrangeLoopGames/EcoIssues#25146]
\
**User Id: (1df83b23-6579-409f-c922-08dcbd8319be)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
1. Open Eco on Steam
2. Go to any server (I've tried my usual server I play on and a local server with 0 mods)
3. Go to Marketplace and attempt to buy coins
4. it doesn't matter if you cancel the transaction or complete all the steps, gives you an error the second it opens up the steam tab

**Expected behavior:**
It should work

**Actual behavior:**
gives an error about an expected non null value in Line 1 spot (insert number between 730-735, it varies)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Tried on a modded server and even non modded, have tried validating game file integrity, still doesn't work

**Please provide log files**
[Player-prev.log](https://github.com/user-attachments/files/16921228/Player-prev.log)
[Player.log.copy.txt](https://github.com/user-attachments/files/16921229/Player.log.copy.txt)

**Comment by D3nnis3n** [comment]
Fixed in 11.0.5.

**Comment by Predulus** [comment]
Not fixed for me.
