### ISSUE TITLE
6.0.1 #F0606345 staging:  "Quit"  Will not close game down/ Disconnecting from server blocks getting into another server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2514]
You can 'disconnect' to the menu but clicking Quit will not close the game down, I have been having to right click the game in the task bar and use 'close window' to leave the game.

Also there seems to be a problem if you are in a server and use 'disconnect' to leave and then try to log into another server it will hang at 100% and not let you in.  Closing the game browser and restarting the game and then you can get in.  Not a big deal but its nice when you can disconnect from one server and log in another without having to restart the entire game

**Comment by metachronism** [comment]
closing as dupe of #2513
