### ISSUE TITLE
USER ISSUE: Unable to interact	with natural objects

### ISSUE THREAD

**Issue by geistesblitz10** [StrangeLoopGames/EcoIssues#25159]
\
**User Id: (84d1e475-14f7-4aba-6e25-08dc8d1bff58)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
I updated to latest version last night, made a new avatar and played a few hours. Closed the game and when I opened the game again it asked to create an avatar.
I go on the server I was and camera is weirdly close up on my avatar's neck, I try to move to see if it's because of structures near me and my wasd controls are reversed to something like dsaw, after doing F5 twice camera position resets to normal third person and controls work as usual.
I try to harvest some huckleberrie and I can't select the bush, I try to use the sickle on some rice and grab some pumpkins and nothing happens, sickle on grass and it doesn't work.
I move around and interact with workbench, chest and stockpiles just fine and can move things around, but can't interact with the others.

Note: I have logged off the server, logged back on, closed the game and entered and the same happened.	

**Expected behavior:**
It shouldn't have asked to make an avatar again.
Camera should have kept the settings from when I last played and shouldn't have been up so close.
Controls should have stayed as usual WASD.
I should be able to interact with objects and object highlighting should occur when facing the object.

**Actual behavior:**
None of the above happened.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes I have some mods installed, I'm going to be testing in single player, mod-free soon.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by geistesblitz10** [comment]
[Player.log](https://github.com/user-attachments/files/17002111/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17002112/Player-prev.log)

**Comment by geistesblitz10** [comment]
I tried making a clean single player game and this happened:

![imagen](https://github.com/user-attachments/assets/4e093eac-dc3e-4f09-8a66-d4d8757fd1c5)

**Comment by geistesblitz10** [comment]
[06:29:41.847] [16] [Error] [Eco] Failed to start the server. Exception was Exception: BadImageFormatException
Message:0x8013110E
Source:System.Private.CoreLib

[log_240914062912.log](https://github.com/user-attachments/files/17002159/log_240914062912.log)

**Comment by geistesblitz10** [comment]
I uninstalled, then reinstalled the game, everything worked fine at first.

I closed the game. I reopened the game and same thing happened, camera zoomed in, couldn't interact.

**Comment by D3nnis3n** [comment]
The errors in the log indicate a corrupted .NET installation.
You can try the following tool to repair it: https://support.microsoft.com/en-us/topic/microsoft-net-framework-repair-tool-is-available-942a01e3-5b8b-7abb-c166-c34a2f4b612a

Otherwise please reach out to support@strangeloopgames.com, as this is not a bug in the game.
