### ISSUE TITLE
USER ISSUE: Intersecting worktables

### ISSUE THREAD

**Issue by Daronius** [StrangeLoopGames/EcoIssues#25154]
\
**User Id: (f2803899-4920-4815-7acf-08dc8d1bff58)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
1. Place Paper Machine
2. Place Cement Kiln

**Expected behavior:**
Placement blocked

**Actual behavior:**
both worktables intersecting

**Do you have mods installed? Does the issue happen when no mods are installed?:**
yes and yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![grafik](https://github.com/user-attachments/assets/c161e231-eea5-4c6b-8404-ebc7a50d6241)

**Comment by Daniel-Magulado** [comment]
Hi @Daronius 

Thank you for submitting the bug report! Our QA team has verified the issue and created an internal report to address it. We appreciate your help in improving the game!

Ref. ECO-5933

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14476 in staging.
