### ISSUE TITLE
USER ISSUE: Marketplace Coin too much but not working

### ISSUE THREAD

**Issue by Akimika11** [StrangeLoopGames/EcoIssues#25155]
\
**User Id: (ef080e09-e335-43b9-2a87-08dcbd2fb3f8)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
Just Start the game and view the Marketplace

**Expected behavior:**
0 Credits

**Actual behavior:**
something about 11000 Credits but cant use them

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes and maybe

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you post a screenshot of the marketplace view and the error you get when you try to use them?
The account indeed doesn't own any credits.

**Comment by Akimika11** [comment]
![Eco Bug Report](https://github.com/user-attachments/assets/b130ad13-3752-4793-849b-ff7ad93518f9)
[Player.log](https://github.com/user-attachments/files/16985015/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16985016/Player-prev.log)

**Comment by Sarah-Graesyn** [comment]
It occurred to me as well; just now at approx 1600-1615 Central Time US

![20240914160307_1](https://github.com/user-attachments/assets/49f0b070-0c05-417a-9a62-d2e1e0d4e840)

[Player.log](https://github.com/user-attachments/files/17003840/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17003841/Player-prev.log)
