### ISSUE TITLE
Room related server crash after 11.0.5 hotfix

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25168]
Server log:
[log_240918060022.log](https://github.com/user-attachments/files/17050203/log_240918060022.log)

We have not had a single server crash since our new wipe launched on Friday 13th of September. 
I've not seen a crash error like this before.

The server did reboot correctly and there seems to be no issues for now.

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14520 in staging.
