### ISSUE TITLE
USER ISSUE: I have this problem every 10 minutes. Can you help me?

### ISSUE THREAD

**Issue by ntwtog** [StrangeLoopGames/EcoIssues#25160]
\
**User Id: (134dac6d-97ae-42f4-52c9-08dcd0d683b2)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
I have this problem every 10 minutes. Can you help me?

Disconnected.

Booted by Strange Cloud

User NTWTOG is logged into 4Netplayers Eco Server NTW (3f786124-6a76-435e-ad18-613dec12e40e) while also logged into another server 4Netplayers Eco Server NTW (c0996b8f-ec9e-43d2-b7f1-db18b048fa7f) owned by NTWTOG.

**Expected behavior:**
I have this problem every 10 minutes. Can you help me?

Disconnected.

Booted by Strange Cloud

User NTWTOG is logged into 4Netplayers Eco Server NTW (3f786124-6a76-435e-ad18-613dec12e40e) while also logged into another server 4Netplayers Eco Server NTW (c0996b8f-ec9e-43d2-b7f1-db18b048fa7f) owned by NTWTOG.

**Actual behavior:**
The following error message popped up:
```
Booted by Strange Cloud

<size=60.00%>User NTWTOG is logged into 4Netplayers Eco Server NTW (3f786124-6a7e-435e-ad18-613dec12e40e) while also logged into another server 4Netplayers Eco Server NTW (c0996b8f-ec9e-43d2-b7f1-db18b048fa7f) owned by NTWTOG.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you reach out to @johnk on discord? We'd need additional information.

**Comment by johnkslg** [comment]
Got it fixed I think
try restarting server too
