### ISSUE TITLE
[11.0.5] Unable to utilize purchase Marketplace Blueprints

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25169]
After 11.0.5 dropped I went from being able to not purchase credits through steam to being unable to use my purchased marketplace blueprints to craft items in game.

**Steps to Reproduce:**

1. Buy Eco Credits
2. Purchase Marketplace Item
3. Attempt to Craft Marketplace Item

**Expected Behavior:**
Job creates as normal except it is a marketplace variant of the item.

**Actual Behavior:**
I get an error message telling me I do not own the blueprint when I do in fact own it

**Screenshots:**
![20240917211739_1](https://github.com/user-attachments/assets/9336f992-91f7-4830-8f76-982e9632c1f5)
![20240917211743_1](https://github.com/user-attachments/assets/afc85bc9-3ba3-4c6c-a091-a8af57113a1c)
Above Screenshots show every marketplace item I own
![20240917211004_1](https://github.com/user-attachments/assets/9dc1b73d-4fb4-400a-9f60-36f0bbe368d8)
![20240917211159_1](https://github.com/user-attachments/assets/89734d70-2435-4e42-adcb-271c9952eac7)
![20240918181337_1](https://github.com/user-attachments/assets/00048c2b-f3ac-4821-8610-7938a728e7a9)

**Comment by D3nnis3n** [comment]
Already fixed in 11.0.6.
