### ISSUE TITLE
USER ISSUE: Contract not fulfilling tool order

### ISSUE THREAD

**Issue by kayliels** [StrangeLoopGames/EcoIssues#25167]
\
**User Id: (6f8d079e-7def-4801-c851-08dcbd8319be)**
**Version:** 0.11.0.5 beta release-733

**Steps to Reproduce:**
1. Set up contract requesting tools. (1 iron hammer, 1 iron hoe, 1 iron shovel, 1 iron sickles) to a chest, recieving property rights for that area.
2. When the contractor tried to deliver the tools it popped up saying a tool was delivered but one more was remaining. Even putting in additional tools just repeated this message, so it never fulfilled the request.

**Expected behavior:**
When the tools were delivered, it should have let the contract been completed.

**Actual behavior:**
Instead it doesn't count the tools as being added and therefore won't complete the contract.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @kayliels 

Thank you for submitting your bug report. We have reviewed and successfully confirmed the issue. An internal report has been created, and the fix will be addressed in an upcoming game update. We appreciate your support.

QA Ref: ECO-6495

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14598 in 11.1.3.
