### ISSUE TITLE
Certain players cannot contribute to certain work parties

### ISSUE THREAD

**Issue by Morlark** [StrangeLoopGames/EcoIssues#25164]
User ID: 75262e7e-b9f1-4df8-900c-08dc8d1bff58
Game version: 0.11.0.4 beta release-722 and earlier versions of 0.11

Steps to reproduce:
1. Have another player create a project to make quicklime at a blast furnace, and create a work party for that project.
2. Join the work party created by the other player.
3. Go to the blast furnace containing the quicklime project, and hover the mouse cursor over the blast furnace.

Observed behaviour:
The button prompt to add labour and materials to the project is not displayed, and as a result it is not possible for the player to contribute to the work party.

Expected behaviour:
The button prompt to add labour and materials should be displayed, and functioning as normal.

Reproduction rate:
Server 1: 1/1
Server 2: 1/1 (same player)

Notes:
1. On server 1, the affected player had been able to contribute to other work parties.
2. On server 1, after encountering this bug, authorisation was granted to the affected player to access the blast furnace. Thereafter, the usual button prompt appeared, and it was possible to add labour and materials to the work party in the usual way (i.e. without needing to open the blast furnace UI).
3. On server 2, another player on the server was able to contribute labour to the work party.
4. On both servers, the bug persisted after rebooting the client.

Installed mods: DiscordLink, Price Calculator
Mods are server-side, cannot check without mods

Log file attached:
[Player-prev.log](https://github.com/user-attachments/files/17020186/Player-prev.log)
Attached log file is from after the work party had already been joined, as the previous log file was wiped out when restarting to troubleshoot.

**Comment by Daniel-Magulado** [comment]
Hi @Morlark 

Thank you for your bug report. We are already aware of the issue and are actively working on a fix. Your feedback is valuable, and we appreciate your understanding as we address this in a future update.

QA Ref.

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14514 in staging.
