### ISSUE TITLE
Room not been recognized after server restart (SEA OTTER Server)

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25165]
I was playing normally and my store was working fine.

Then the server has been restarted.

I've check my store and it was OFF and the status complained about the room.

![image](https://github.com/user-attachments/assets/89f2a439-5ec1-49e6-9185-a99578af1e1f)

I remove and I place one mortared stone block back and it was been recognized again as a room.

![image](https://github.com/user-attachments/assets/d2ae5317-f5fd-4f42-addb-d393a0e4d3af)

**Comment by D3nnis3n** [comment]
Likely related to https://github.com/StrangeLoopGames/EcoIssues/issues/25119

**Comment by Crazy-Spy** [comment]
I confirm that after the last hotfix (11.0.6). The room is now working properly after the server restart.
