### ISSUE TITLE
Settlement Foundation removes player from Parent Federation

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25162]
**Steps to Reproduce:**

1. Craft Settlement Crafting Table
2. Craft Town Foundation
3. Place Foundation
4. Pickup Foundation (Not Ctrl-Click to move, actually pick it up)
5. Attempt to place Town Foundation

**Expected Behavior:**
- Able to replace Town Foundation without issue

**Actual Behavior:**
- Player was removed from the Parent Federation and then unable to place the Town Foundation again.

**Mods Installed? Occurs Without Mods?**
Yes, mods are installed. I am unsure at the moment if it occurs without mods being installed I will be testing it in vanilla soon as I am able.

**Server/Player Info:**
Logged in as Draggynfyre
User ID: b3a00080-774a-4d53-fc0d-08dc8cbaa721
Server ID: 6ebd1a7c-79ac-4e0b-b297-050e56d9574b

![20240915000704_1](https://github.com/user-attachments/assets/9f8bd914-b952-475a-b804-9268e04a6bb1)

**Comment by D3nnis3n** [comment]
That works as intended - the moment you pick up a settlement you are destroying it, as you are warned about.
Given the settlement you were a direct citizen of is destroyed, you loose your citizenship in that town and as such all indirect citizenships that came with it.
