### ISSUE TITLE
USER ISSUE: Windows username gets exposed	

### ISSUE THREAD

**Issue by JJJJJHGDF** [StrangeLoopGames/EcoIssues#25179]
\
**User Id: (be850440-1966-4032-b924-08dcd72ba347)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
load game

**Expected behavior:**
C:username gets exposed

**Actual behavior:**
stop recording or stop streaming

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Can you provide more information on what is exposed where?

**Comment by D3nnis3n** [comment]
Closing due to no further information provided. Feel free to open a new issue once you can provide more information.
