### ISSUE TITLE
Meteor Keeps Reappearing 

### ISSUE THREAD

**Issue by Ohnix-Ahnul** [StrangeLoopGames/EcoIssues#25177]
I have now Lasered the meteor 3 times ... playing a solo game with very easy server settings.  1st time Meteor was laser was about 2 days 18 hours into game with a bit over 2 days and 6 hours till it would crash, the second time was about 6 hours later... then I log in this morning to see it once again looming overhead.  The server is only up and running when I start it through Steam and the game is not running when I leave.

I have just attempted to deselect the meteor in the games settings but when I go back to verify it is once again enabled.

This morning I logged into my solo game to find that the electric power grid oscillating on / off. This is from the same 46kW+ solar generator farm that was used to laser the Meteor on two previous times the day before.

Other Issues ::

frequently, during normal game play, I notice that sometimes new items do not show up and no icon is being displayed or it is obscured - moving the space where the icon would be or moving another icon on top sometimes forces the hidden icon to be displayed but not always.

checking how to get log files to you ... here you go.
[log_240923123844.log](https://github.com/user-attachments/files/17103954/log_240923123844.log)
[log_240923124704.log](https://github.com/user-attachments/files/17103955/log_240923124704.log)

**Comment by D3nnis3n** [comment]
Thanks, we already have this issue tracked internally as ECO-2955.
