### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by EugeneTennesie** [StrangeLoopGames/EcoIssues#25173]
\
**User Id: (fe67b1bb-39db-454d-7820-08dcc2f971c4)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
je suis bloque sous terre comment me sortir de la

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You can use the command /unstuck to free yourself or request an admin to teleport you. If you are an admin yourself (like on a local game) you can also use the /fly command.
