### ISSUE TITLE
[11.0.5] Marketplace items such as Far East Lumber presents error message on placement

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25170]
After 11.0.5 dropped the Far East Lumber now presents a message that there aren't enough blueprints on the server for it to be placed however it doesn't seem to have any effect on gameplay

**Steps to Reproduce:**
1. Buy Far East Lumber from Marketplace
2. Craft Far East Lumber
3. Place Far East Lumber

**Expected Behavior:** 
- Lumber places like normal with no error message

**Actual Behavior:**
- Error Message pops up

**Additional Info:**
Unsure if related but may potentially be related to https://github.com/StrangeLoopGames/EcoIssues/issues/25169
**Screenshots:**
![20240917211134_1](https://github.com/user-attachments/assets/0b03554d-0577-4b35-ae3a-59325725708d)

**Comment by D3nnis3n** [comment]
Already fixed in 11.0.6.
