### ISSUE TITLE
USER ISSUE: Gamebreaking Forced Wanted Order Bug	

### ISSUE THREAD

**Issue by Ajuhzee** [StrangeLoopGames/EcoIssues#25181]
\
**User Id: (a6cd3d95-dc61-4289-2b99-08dcbfc1e3b1)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
Have a Tree log in your inventory and drag it onto the Wanted Area on any shop a few times. 

**Expected behavior:**
Nothing should happen.

**Actual behavior:**
Sometimes suddently a Wanted Order for exactly this type of Tree log appears. Now you can sell logs there for 1$ each. 
This way you can basically force a shop to buy stuff from you.
I stumbled on it on accident a few hours ago and was very confused. I tried to reproduce it to figure out what caused this weird interaction and was successful at this point. This is very gamebreaking and can be abused.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't really know. I only play on the official White Tiger server, which is modded I think.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14491 in 11.0.7.
