### ISSUE TITLE
Stuck in tutorial - Play Test on Coast-Redwood

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25188]
Looks like the tutorial is stuck for me. 

I've just joined the world and I got the following:

![image](https://github.com/user-attachments/assets/28298898-f9d3-4d7b-84df-b867e8271d47)

I can click everywhere and nothing happen. The only thing that I didn't do was click on SKIP.

**Comment by D3nnis3n** [comment]
Should be resolved.
