### ISSUE TITLE
corners of terrain shouldnt look like this

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2518]
![image](https://user-images.githubusercontent.com/3150561/31466302-9254a4e2-ae8b-11e7-9ed2-e987bc2a522a.png)

normals?  tangents?  something with the mesh?

**Comment by keegan-o** [comment]
I think we will need to work on our shader, for both use with a building triplanar variant shader and to remedy various things with terrain. Will look into now though in-case it can be fixed with the mesh or mesh import settings.

**Comment by keegan-o** [comment]
At least made it better for now (also fixed forest floor not transitioning to dirt).

**Comment by keegan-o** [comment]
closing this since this specifically is fixed
