### ISSUE TITLE
Hewn Nightstand

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25187]
This is how Hewn Nightstand looks in game:
![image](https://github.com/user-attachments/assets/03a84ca8-f5da-405e-b8f8-9fdaaae32c78)

This is the icon it has:
![image](https://github.com/user-attachments/assets/33c21309-a928-4ecb-b4c4-bb7dc3f45743)

What icon it should have:
![image](https://github.com/user-attachments/assets/9bed652f-e689-48d6-b0ab-d6611785656a)

What Hewn Nightstand **icon** is likely representing:
![image](https://github.com/user-attachments/assets/fc111308-c81f-48ee-a40f-51c052c2e45a)
(found this in SVN)

**Comment by D3nnis3n** [comment]
Fixed in staging.
