### ISSUE TITLE
USER ISSUE: Japanese Font is terrible	

### ISSUE THREAD

**Issue by JJJJJHGDF** [StrangeLoopGames/EcoIssues#25180]
\
**User Id: (be850440-1966-4032-b924-08dcd72ba347)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
Open the game and suffer near-unredable Japanese font
This font also breaks outer shadow making it even harder to read

**Expected behavior:**
Beautiful font for a beautiful game	

**Actual behavior:**
Eye-burning font like the third world buring coals nonstop

Use more readable font like Noto Sans JP

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This would be better suited for our suggestion tracker here: https://feedback.play.eco
