### ISSUE TITLE
Endless stars

### ISSUE THREAD

**Issue by anonim22** [StrangeLoopGames/EcoIssues#25197]
https://github.com/user-attachments/assets/372b97dd-f9fd-4309-879b-5fb64001feae

**Comment by D3nnis3n** [comment]
Issue is not reproducible this way. Can you provide your logfile? Does it happen every time or was that a one-off occasion?
You shouldnt be able to see the refund mark on specialties you don't have.

**Comment by anonim22** [comment]
I play on my own server and I am its administrator. In the server config, the CanAbandonSpecialties option is enabled and the experience return is set to 1. If I hover over the area where the button with the cross should be, then my mouse cursor changes the icon, which tells me that I can click on the button, although the button is hidden. If I click there, then a window appears confirming the reset of the specialty.
The first time I noticed this, when I actually tried to reset the smelting specialty. But then I found out that the button was hidden and can be clicked again.
Now I see that I can click on this button even for a specialty that I never took, although the button is still hidden
I tried the same thing on a second computer that is connected to my server. The problem is reproduced on it too. I have not tested it on other servers
I play on version 0.11.0.6 beta release-741 from Steam

**Comment by anonim22** [comment]
[Player.log](https://github.com/user-attachments/files/17382639/Player.log)
[log_241015105158.log](https://github.com/user-attachments/files/17382647/log_241015105158.log)
I thought it was mods, deleted everything, pasted a clean mods folder from EcoServerPC_v0.11.0.6-beta.zip, but it didn't help. There's nothing extra in the logs. I started the server, started the game, connected, reset the campfire cooking specialization 3 or 4 times, which I never spent stars on, exited the game, sent the logs

**Comment by D3nnis3n** [comment]
Can you reproduce the issue on playtest-11.1.0 branch on Steam? It likely is already fixed, just not sure where.
