### ISSUE TITLE
USER ISSUE: HUD Issues - Playtest 11.1

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25190]
\
**User Id: (b3a00080-774a-4d53-fc0d-08dc8cbaa721)**
**Version:** 0.11.1.0 beta staging-2991

**Steps to Reproduce:**
1. Hover over an item like Farming Skill Scroll to see where it is available on Coast Redwood Server.
2. Wait for the pop-up to lock.
3. Attempt to click on any store below the very top listed

**Expected behavior:**
It should have allowed me to click the name of the lower stores to show on map, set marker, etc.

**Actual behavior:**
I was unable to even click on any store below the very top one

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I don't think Coast Redwood has any mods as its a playtest server; yes it does happen with no mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed.
