### ISSUE TITLE
water walker

### ISSUE THREAD

**Issue by Godzkonga7016** [StrangeLoopGames/EcoIssues#2519]
im on version 6.0.1 #F0606345 and i noticed that i have the power to walk on water,  plus unable to use jump while on top the water, either neat bug or new hidden feature? 
https://www.dropbox.com/s/om4fanfdlvnrsz8/ClientNetworkException%2010112645.ecodmp?dl=0   plus when i tried to use the hammer on my tool repair table i also get kicked from game, then when i get back in, i cant select other tools or do anything, just walk around,,  on US public killserver

**Comment by craig-jong** [comment]
I believe this is an intended feature. 

I guess it could be made more obvious whats happening, but you now need to press "ctrl" to dive.

**Comment by MarjieAVolk** [comment]
@craig-jong - there is also a second bug described in the second half of the bug, might want to create a separate bug for it
