### ISSUE TITLE
USER ISSUE: Items showing false or no icon

### ISSUE THREAD

**Issue by numerfolt** [StrangeLoopGames/EcoIssues#25193]
\
**User Id: (8de05a76-6449-42a3-3d24-08dc8cbaa722)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
1. Play on a server
2. play normal and move things from and to stockpiles

**Expected behavior:**
the items get transferred

**Actual behavior:**
the items get transferred most of the time, but quite often in the process, they lose their icon, become invisible or show up as different items

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/23628
