### ISSUE TITLE
USER ISSUE: 오프라인

### ISSUE THREAD

**Issue by yoon160923** [StrangeLoopGames/EcoIssues#25196]
\
**User Id: (00000000-0000-0000-0000-000000000000)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Has no content, please try again?
