### ISSUE TITLE
[Beta 11.1.0] Placing Window Shutters Left or Right on Ashlar shifts shutters into ashlar block

### ISSUE THREAD

**Issue by Praefator** [StrangeLoopGames/EcoIssues#25206]
As per title. While I expected to be able to place window shutters adjacent to my windows to give off the impression that they were currently "open", instead the shutters become invisible, disallowing further placement on that block. That part seems to work. 

Where the bug occurs, is where those shutters are actually visible. Removing the blocks these shutters are supposed to be placed **on**, the shutters find themselves **in** the block instead.

![20241025011250_1](https://github.com/user-attachments/assets/489af2b8-de36-4207-b43c-309ab1703f93)

**Comment by D3nnis3n** [comment]
Fixed. Might be in 11.1.3 already, otherwise the one after.
