### ISSUE TITLE
USER ISSUE: Missing icons

### ISSUE THREAD

**Issue by amyscotteng** [StrangeLoopGames/EcoIssues#25204]
\
**User Id: (5761e749-9039-49db-d282-08dce294c1e5)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
Create arrows at tool station

**Expected behavior:**
Icon should be showing

**Actual behavior:**
Icon does not show and item cannot be searched for. This also happens with other objects randomly.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed in staging.
