### ISSUE TITLE
Reconnecting chunk exceptions

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2520]
Disconnect & reconnect, also get exceptions for normals/tangents

Mesh.uv is out of bounds. The supplied array needs to be the same size as the Mesh.vertices array.
UnityEngine.Mesh:SetUVs(Int32, List`1)
MeshData:ToMesh() (at Assets/VoxelEngine/Core/MeshBuilder.cs:172)
MeshBuilder:ToMeshes() (at Assets/VoxelEngine/Core/MeshBuilder.cs:294)
ChunkRenderer:ApplyBuiltMesh() (at Assets/VoxelEngine/Core/ChunkRenderer.cs:797)
ChunkJobQueue:ProcessFinishedJob(ChunkRenderer) (at Assets/VoxelEngine/Core/ChunkRenderer.cs:383)
StaticChunkUpdate:Update() (at Assets/VoxelEngine/Core/StaticChunkUpdate.cs:71)

**Comment by SeanAtr0n** [comment]
results in weirdness like:
![image](https://user-images.githubusercontent.com/774628/31478705-1dc5919a-aec7-11e7-9141-0666d583695e.png)

**Comment by metachronism** [comment]
grrrrrrrrrrrrrewah

**Comment by metachronism** [comment]
feexed
