### ISSUE TITLE
USER ISSUE:Erro ao abrir servidor/modo solo

### ISSUE THREAD

**Issue by Hyeer97** [StrangeLoopGames/EcoIssues#25205]
\
**User Id: (f43d692a-aebe-401f-7ef2-08dcec7de103)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**

### ### ### ****
**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/17480836/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17480837/Player-prev.log)

**Comment by D3nnis3n** [comment]
Thanks for the report, unfortunately it doesn't contain an error or description of the issue you are facing.
Please open a new issue with the respective information :)
