### ISSUE TITLE
Boat speeds not changeable in AutoGen Files

### ISSUE THREAD

**Issue by pondobruin85** [StrangeLoopGames/EcoIssues#25209]
It seems that the unity assets for boats arent attached to the VehicleComponent MaxSpeed Variable.  Changing the number in an override file has no effect.  Not sure if intended or overlooked, or something else.  
![image](https://github.com/user-attachments/assets/cc0d9371-04cc-4664-8796-5b738d3d66c4)

**Comment by pondobruin85** [comment]
pondobruin85 in discord if followup wanted

**Comment by D3nnis3n** [comment]
That works as intended.
