### ISSUE TITLE
USER ISSUE: Kran Verlassen

### ISSUE THREAD

**Issue by commander82** [StrangeLoopGames/EcoIssues#25202]
\
**User Id: (c599baf2-22ce-44a3-77ae-08dc8d1bff58)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
1. Kran Besteigen
2. Kran kann jetzt nicht mehr verlassen werden 

**Expected behavior:**
bei drücken von E sollte ich den Kran verlassen können

**Actual behavior:**
Nichts bleibe im Kran

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25140, already fixed in staging.
