### ISSUE TITLE
USER ISSUE: in game store item 

### ISSUE THREAD

**Issue by Scubulls** [StrangeLoopGames/EcoIssues#25200]
\
**User Id: (fa83caf3-25bb-432c-2d67-08dcce89dbe7)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
1. I craft a store item.
2. I take store item my backpack.
3. When i take my hand for put somwhere in building all cursors are lost.

**Expected behavior:**
To make alignment guides visible and adjustable.

**Actual behavior:**
The alignment guides don't appear, the previous tool's guides remain on the screen, and the store item cannot be placed.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
By chance also a turkish user? Issue is known with something specific to turkish and unfortunately not reproducible for us: https://github.com/StrangeLoopGames/EcoIssues/issues/25172
