### ISSUE TITLE
USER ISSUE: Medium Shipyard ruining outdoor room bonus.

### ISSUE THREAD

**Issue by AngryW1zard** [StrangeLoopGames/EcoIssues#25217]
\
**User Id: (b095b6f1-e78d-416a-97b5-08dc8d1bff58)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
1. Place a medium shipyard on your property
2. Attempt to encase it in a "building"
3. only way to close it entirely is to cut it off from the water making the building no longer work.

**Expected behavior:**
Allow for the building to be outside.

**Actual behavior:**
Ruins outdoor bonus while requiring to be connected to the ocean.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This works as intended. You are supposed to use separated deeds for your housing and industrial needs.
