### ISSUE TITLE
USER ISSUE: 72 bits download speed on a local server on LAN with a 1 gig connection ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#25215]
\
**User Id: (55127337-ca07-44b6-5b3c-08dc8bf77f69)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
create LAN Server on a Dedicated Machine 
dedicated Machine is m2 drive 4tb with 64 16 core cpu 64 gigs ram 1 gig connection speed....

local client machine m2 drive 4tb 64 8 core cpu 16 gigs ram 1 gig connection speed

LAN side operations intial log in download client getting is 72 bits secound

takes three hours to load all chunks why ?

**Expected behavior:**
should load chunk on server faster and it should download chunks faster than 72 bits secound

**Actual behavior:**
slow to slow might as well start loading in before you go to work so when you get home maybe you be on server i guess. ?

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The speeds shown there don't really represent your internet connection, such a slow speed rather hints at some form of issue with connection to begin with. You may want to reach out to support@strangeloopgames.com for that, as the problem isn't reproducible.
