### ISSUE TITLE
USER ISSUE: issue with research table 	

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#25213]
\
**User Id: (55127337-ca07-44b6-5b3c-08dc8bf77f69)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
build adobe building that walls are two blocks high and then put ceiling as third block above it then place research table in the room.  the ceiling is more than tall enough the research table does not take up four blocks of research table is only two blocks tall so it should fit in a normal size height room ?

**Expected behavior:**
should be able to be placed in a normal size room.  

**Actual behavior:**
cant be placed in a nomral size room

**Do you have mods installed? Does the issue happen when no mods are installed?:**
 no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The research table requires a height of at least 3 blocks, that is working correctly.
