### ISSUE TITLE
USER ISSUE: Stump Bed Can't Be Slept On

### ISSUE THREAD

**Issue by Narshero** [StrangeLoopGames/EcoIssues#25224]
\
**User Id: (96ca55ef-e5d6-4050-b53c-08dcbed6b42e)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
1. Place Stump bed in room
2. Mouse over different parts of bed and press interact key

**Expected behavior:**
It appears the intended behavior is that selecting the bedframe allows the player to "use" the bed (access its permissions etc.) while selecting the mattress allows the player to "sleep" in the bed.

**Actual behavior:**
Selecting either the frame or the mattress gives the "use" option; neither allows the player to select "sleep".

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Already fixed in 11.1.1.
