### ISSUE TITLE
Using /edit and deleting chat channels corrupts save file.

### ISSUE THREAD

**Issue by pondobruin85** [StrangeLoopGames/EcoIssues#25223]
corrupts the save file into an unrecoverable state.

**Comment by D3nnis3n** [comment]
/edit is a dangerous command that allows us to do anything necessary - any changes made there must be done with good care and a backup. Also note that any changes done in there to laws become active immediately, without pressing an apply button.

There is plans to fix this command up for more general admin usage after final release, but for now it is basically a development command that needs the respective caution.
