### ISSUE TITLE
Animal Carcass icons on wrong layer?

### ISSUE THREAD

**Issue by pondobruin85** [StrangeLoopGames/EcoIssues#25222]
I know the carcass icons are older, and I'm not sure I knw the exact issue.  When converting a fish or animal carcass to a FoodItem or a PartItem, the stats and expiration are handled correctly, but the durability bar cannot be seen.  The durability bar is properly displayed on newer and custom icons.

**Comment by D3nnis3n** [comment]
I did ask Art team and they said there is no differences that could cause that.

I assume this issue happens during modding, which is why this doesn't seem to be a fit for this tracker, but do you have an example we can use to reproduce?

**Comment by pondobruin85** [comment]
Yes I am trying to mod carcasses to have an expiration date.  I was successful in all except a bar on the UI.  Here are some pics...

![image](https://github.com/user-attachments/assets/3004e233-01dd-46db-adad-ab3f68185832)
File structure

![image](https://github.com/user-attachments/assets/16364561-a788-4b3c-87c4-9978d51373a6)
Vanilla Bass

![image](https://github.com/user-attachments/assets/3c1ae8a6-d93a-4329-8e30-eed12f4f0895)
Vanilla Bison Carcass

![image](https://github.com/user-attachments/assets/cce66bd5-a5e6-463a-b619-43b4c55216bf)
Vanilla Beet

![image](https://github.com/user-attachments/assets/4936c172-6e37-4747-b059-cafbfc627b79)
Modded Clothing

![image](https://github.com/user-attachments/assets/7d83e9af-ade9-46e0-a03a-538d3c25858e)
Beet as a Part

![image](https://github.com/user-attachments/assets/ab6c2db1-79f6-4a71-b22e-21534a9935c1)
[Bass.override.txt](https://github.com/user-attachments/files/17580791/Bass.override.txt)
Bass as food

![image](https://github.com/user-attachments/assets/454cabd3-bc7a-444c-b696-9773c2fd32fd)
[BisonCarcass.override.txt](https://github.com/user-attachments/files/17580797/BisonCarcass.override.txt)
Bison as food

![image](https://github.com/user-attachments/assets/9e370891-7861-451b-b9af-24fb49f9f8a6)
Modded asset as a part.

So it seems its every icon, regardless.  Since the bar disappeared for the beet as well.  Again, Im super new to this, and not sure if its something worth chasing or not.  The modded bass and bison can be eaten, and do expire into spoiled food.

**Comment by D3nnis3n** [comment]
Can you provide the mod doing that?

**Comment by D3nnis3n** [comment]
So, I checked back with the team and the good news is, this is not your fault - there is a longstanding issue where modded food items don't show durability bars which seemingly also applies to parts.

However, the bad news is that fixing that would require intense investigation for its cause which we don't have the resources for currently given this is a sole modding issue, which is why as before it is unfortunately a Won't fix for now. Sorry :(

**Comment by pondobruin85** [comment]
Thanks for the update!  Bad news handled very professionally, Kudos to the devteam :)
