### ISSUE TITLE
USER ISSUE: Wooden Sliding Door not sealing room

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#25225]
\
**User Id: (b3a00080-774a-4d53-fc0d-08dc8cbaa721)**
**Version:** 0.11.1.0 beta release-750

**Steps to Reproduce:**
1. Build a Room with material of choice (Door is Tier 3)
2. Craft a Wooden Sliding Door
3. Place Wooden Sliding Door

**Expected behavior:**
The door should have closed off the open room and turned it into an uncategorized room

**Actual behavior:**
The door does not seem to register as a door at all.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes; I play on the AWL High Collab Server primarily; I am also going to test this on Vanilla.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Sarah-Graesyn** [comment]
Just tested this on a completely new, freshly generated vanilla world. This does indeed occur without mods installed. The Wooden Sliding Door does not complete a room.

**Comment by Atome6** [comment]
I concur

**Comment by D3nnis3n** [comment]
Already fixed in 11.1.1.
