### ISSUE TITLE
world connection taking toooooo long

### ISSUE THREAD

**Issue by kash1967** [StrangeLoopGames/EcoIssues#25227]
download seems be dropping to BYTES/s.....
[Player.log](https://github.com/user-attachments/files/17578980/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17578982/Player-prev.log)

**Comment by D3nnis3n** [comment]
When download speed display drops that low and connecting isn't possible or taking extremely long that is actually not a sign of any issues related to connection, but on some other problem. The log you provided contains tons of errors, many mod related, like this:

> [08:48:36.628] Loaded objects should start as DISABLED, but object "Items" in bundle "C:/Users/kawis/AppData/LocalLow/Strange Loop Games/Eco\Mods\RoadExtension.unity3d" is not.  This can cause many problems, you should disable the object by default.

Please make sure to give the game a full reinstall (including clearing C:/Users/kawis/AppData/LocalLow/Strange Loop Games/) and remove all modifications, we can't accept reports that contain modifications.
