### ISSUE TITLE
[Website] Archived Downloads Server Builds

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#25221]
There's an issue with the website, where you can;t download any past server builds due to what I assume is a JaveScript bug? As when clicking on what OS, it will just close the drop down window instead of expanding it. I tested on both Firefox and Chrome with the same result.

Below is a short video showing the problem

https://github.com/user-attachments/assets/7399a543-50c1-4aec-b917-5597963ca58b

**Comment by D3nnis3n** [comment]
Fixed.
