### ISSUE TITLE
USER ISSUE: Power Hammer nimmt keine Aufträge an

### ISSUE THREAD

**Issue by AniKitsune** [StrangeLoopGames/EcoIssues#25237]
\
**User Id: (4df21243-7e0a-4548-5ac0-08dcbefc6db7)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
Power Hammer platzieren, alle Inventare anschließen, Projekt starten wollen

**Expected behavior:**
Es sollte die Projekte bearbeiten

**Actual behavior:**
passiert nichts

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Wir benötigen bitte eine genauere Fehlerbeschreibung. 

Welches Projekt soll gestartet werden, welcher Fehler wird angezeigt, wie sieht der Status Tab des Objekts aus?

**Comment by AniKitsune** [comment]
Hallo, Es sollten die modernen Werkzeuge gestartet werden, es hat bei keinem funktioniert. Auch bei den Stahlwerkzeugen nicht. Es wird kein Fehler angezeigt. Anbei sende ich 3 Screenshots. Viele Grüße Annika --Gesendet mit der WEB.DE Mail AppAm 04.11.24, 04:08 schrieb Dennis Scholz ***@***.***>:

Wir benötigen bitte eine genauere Fehlerbeschreibung.
Welches Projekt soll gestartet werden, welcher Fehler wird angezeigt, wie sieht der Status Tab des Objekts aus?

**Comment by D3nnis3n** [comment]
Leider sind hier keine Screenshots sichtbar.

**Comment by D3nnis3n** [comment]
Leider immer noch keine Screenshots sichtbar - vielleicht mal direkt auf Github versuchen.

**Comment by AniKitsune** [comment]
Ich habe einen Post bei Github erstellt mit der Nummer 25237. Vielen Dank. Viele Grüße, Annika --Gesendet mit der WEB.DE Mail AppAm 07.11.24, 12:51 schrieb Dennis Scholz ***@***.***>:

Leider sind hier keine Screenshots sichtbar.

**Comment by D3nnis3n** [comment]
Danke, ich hab den Post aber geschlossen - eigentlich hättest du im bestehenden Issue antworten sollen.

Es sieht so aus, als wäre einfach kein Blacksmith Table im selben Raum, der wird aber benötigt. Bitte prüfen.

**Comment by AniKitsune** [comment]
Hey, Omg danke, ja, das stimmt. Viele liebe Grüße. Annika --Gesendet mit der WEB.DE Mail AppAm 08.11.24, 21:43 schrieb Dennis Scholz ***@***.***>:

Danke, ich hab den Post aber geschlossen - eigentlich hättest du im bestehenden Issue antworten sollen.
Es sieht so aus, als wäre einfach kein Blacksmith Table im selben Raum, der wird aber benötigt. Bitte prüfen.

**Comment by D3nnis3n** [comment]
Wunderbar, dann mach ich hier zu, weil kein Fehler vorliegt.
