### ISSUE TITLE
"Storage" tab filter/search breaks when switching between containers

### ISSUE THREAD

**Issue by Azzurite** [StrangeLoopGames/EcoIssues#25230]
**Version:** 0.11.1.1 beta release-758

When first starting the game, the storage tab filter/search works great. 

However, with the newest feature of "saving" your filtered view, when you use the filter/search in one container, don't clear it (so it gets saved) and then open *another* container with the previous filter/search still active, the new container will have the text you entered, but no filtering applied. When you then try to change this new container's filter/search, nothing happens. 

Only reloading the container will fix this.

When you filter/search something, but then clear it before closing the storage tab, the filter/search continues working even in other containers. So the new "saving feature" is what breaks this.

**Comment by Daniel-Magulado** [comment]
@Azzurite 
Thank you for submitting this bug report.
We were able to confirm this issue. A fixed should be rolled out in the future game updates.

**Comment by D3nnis3n** [comment]
Fixed in 11.1.2.
