### ISSUE TITLE
Joining a settlement with a 16/16 homestead "locks" already deposited claim papers and doesn't increase your plot count

### ISSUE THREAD

**Issue by CAlbers** [StrangeLoopGames/EcoIssues#25231]
Currently running 0.11.1.1 beta release-758

Was toying around with increasing my plot outside of settlement influence before joining the settlement and after some trial and error came across a bug that would inhibit me to claim beyond my 16/16 homstead claim even with additional papers in my claim stake. The setup is a bit niche but it is reproducible, atleast when I did it on the Might Moose server.

Steps to reproduce bug:

1. Setup a homestead claim on the edge of a settlement
2. Extend the homestead to 16/16 plots.
3. Deposit Claim Papers of said settlement in your homestead stake
4. Join the settlement
5. Homestead will still say 16/16 even with 4 additional papers in them
6. Try to enlarge your claim beyond 16 or try to remove the papers from the stake
7. Message that papers are in use already and you won't be able to increase your claim size beyond the default 16

Goodluck fixing it :)

**Comment by Daniel-Magulado** [comment]
Hi @CAlbers 

Thank you for submitting this bug report.
We were able to confirm this and a fix should be rolled out in the future game updates.

Ref: ECO-8465

**Comment by D3nnis3n** [comment]
Fixed in 11.1.2.
