### ISSUE TITLE
USER ISSUE: Metor shard no longer able to hang off back packs ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#25236]
\
**User Id: (55127337-ca07-44b6-5b3c-08dc8bf77f69)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
get a back pack
try to add metor share as a clothing peice 

**Expected behavior:**
use to be able to hang them off of the back packs as deceration and they would also glow providing light source 

**Actual behavior:**
metor shareds can not be used any more the ones that the alpha players got.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Which backpack? Did you out the meteor shard in the hotbar?

**Comment by D3nnis3n** [comment]
Seems working fine here:
![image](https://github.com/user-attachments/assets/e9d6bd3a-c2f7-4e4d-ad6c-9fc5ee85cdbc)
