### ISSUE TITLE
USER ISSUE: cheat

### ISSUE THREAD

**Issue by Weljelbel** [StrangeLoopGames/EcoIssues#25233]
\
**User Id: (6074abd0-a44c-4d95-d887-08dcbd395caf)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
Logged in

**Expected behavior:**
enter server

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server you play on has a experimental movement hack detection active, you can tell the admin to disable it in Users.eco: "MovementHackDetection": false.
