### ISSUE TITLE
Loading into a server is taking really long, 62 b/second

### ISSUE THREAD

**Issue by chidy28** [StrangeLoopGames/EcoIssues#25239]
I've tried a friends server, my own server, public servers, the same thing happens. I've tried verifying, clearing files and verifying, firewall adjustments, internet reset via pc and my router. I cannot figure out the issue and even had a IT buddy trying to help out.

I also removed any vpn and hamachi from my pc and still nothing. Also tried to reinstall on both my main ssd and secondary.
[Player.log](https://github.com/user-attachments/files/17613413/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17613414/Player-prev.log)

**Comment by D3nnis3n** [comment]
The log shows literally no data transfer, as if it would simply freeze when trying to establish connection and no longer do anything. That hints at security software interfering.

**Comment by D3nnis3n** [comment]
Reported to be fixed in Discord by using:

```
ipconfig /release
ipconfig /renew
```
