### ISSUE TITLE
Erreur lors de l'annexion

### ISSUE THREAD

**Issue by Grosseloche** [StrangeLoopGames/EcoIssues#25249]
![Capture d'écran 2024-11-09 234639](https://github.com/user-attachments/assets/8e514bcd-37ec-4cc8-9a76-da27cda10858)

Bonsoir.
Deuxieme wype ou nous avons le problème suivant (voir le screen ) . Nous avons beau tout faire dans les règles. Impossible d'annexer :/ si quelqu'un a déjà eu le bug. 

Merci d'avance

**Comment by Grosseloche** [comment]
![image](https://github.com/user-attachments/assets/6e3b7f5e-2525-4111-b4ef-a70f4f2d0b46)

**Comment by Daniel-Magulado** [comment]
Hello @Grosseloche 

Is this a non-official server? Are you able to provide a save file copy of the server?
If so, mind sending us a copy? It will greatly help in investigating this issue.

**Comment by Daniel-Magulado** [comment]
Reproduced. Ref. ECO-8499

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14606 in 11.1.3.
