### ISSUE TITLE
USER ISSUE: Server not responding to anything I do

### ISSUE THREAD

**Issue by OwenTheBowen** [StrangeLoopGames/EcoIssues#25243]
\
**User Id: (44b1e575-f82a-4c73-defd-08dcf890ae91)**
**Version:** 0.11.1.1 beta release-758

**Actual behavior:**
I can see what other people are doing - starting work orders, moving around on the map, etc. - But I can't do anything.

Walking a bit shows that terrain refuses to load in, I can just fall through the world.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
There are mods on the server, I haven't installed any personally.

I have restarted the game multiple times, and restarted my PC, and validated game files, but it's still bugged.

**Log files:**
[Player.log](https://github.com/user-attachments/files/17657088/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17657090/Player-prev.log)

**Comment by D3nnis3n** [comment]
Unfortunately your computer doesn't fulfill the minimum system requirements for Eco **and** the log is full of mod related errors.
We unfortunately can't offer support in that case.

**Comment by OwenTheBowen** [comment]
What's confusing is that this only started happenning today. I've played previously on the server for days and it's worked just fine.
