### ISSUE TITLE
Player Shadow Doesn't Match with Player Actions

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25259]
When using the Bow, the player's shadow does not consistently match their actions.

Steps to Reproduce:

1. Equip the Bow.
2. Run or walk while the Bow is selected.
3. Observe the player's shadow.
4. Stop and get ready to shoot with the Bow.
5. Observe the player's shadow again.
6. Walk/Run with the bow ready to shoot. 
7. Observe the player's shadow.

With Bow selected:

![20241116170454_1](https://github.com/user-attachments/assets/8a6a7efc-7f76-4ed3-b9d5-9826845de326)

With Bow ready to shoot:
![20241116170601_1](https://github.com/user-attachments/assets/dd1fa241-6389-4380-9e40-548f4260cfdd)

Expected Behavior: 

The shadow should consistently match the player's actions, whether running, walking, or aiming the Bow.

Actual Behavior:

When running or walking with the Bow selected, the player's shadow does not match the action.
When aiming and ready to shoot, the shadow correctly matches the player's stance.

**Comment by D3nnis3n** [comment]
Thanks for the report, I talked with the art team about this and we do already have an existing issue for it, but that was acknowledged as a Won't fix, given the resources it would take for improved shadow behaviour and the little benefit that provides. I'm hence closing this issue.
