### ISSUE TITLE
USER ISSUE: Text Chat non Functional

### ISSUE THREAD

**Issue by DAN-3I42** [StrangeLoopGames/EcoIssues#25252]
\
**User Id: (d4652621-19af-44cc-e009-08dcf890ae91)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
Use the text chat, multiple times

**Expected behavior:**
Be able to type in the text chat

**Actual behavior:**
Only able to resize the text chat

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide your player.log file as noted in the issue template when this issue occurs and any steps that could allow us to reproduce the issue.

**Comment by D3nnis3n** [comment]
Issue is not reproducible and no further information was provided, hence closing this issue. Feel free to open a new issue when you can provide the necessary data.
