### ISSUE TITLE
Contracts (Loans) can be edited by other players

### ISSUE THREAD

**Issue by CosmoD41** [StrangeLoopGames/EcoIssues#25254]
I create a loan offer on a contract board that is within my claim with everyone in Authorization so they can access it. 

The issue is, everyone who opens the loan offer can edit all the values in there not only the ammount they wanna loan. 
So they can set different currencies, accounts, allowed ranged, interested and hours to complete and then accept those without any option for me to control these changes. 

I dont think that it is intended for other users to do so. 
This issue has also been mentioned by another player in the official Discord: #https://discord.com/channels/254025510651297802/448531486313021459/1302927283996332073
 
![image](https://github.com/user-attachments/assets/6a4992c4-d067-4e73-a41e-9db729f74fa8)
![image2](https://github.com/user-attachments/assets/bfc6a792-059d-4bb3-9274-53ecdc95798e)

**Comment by Daniel-Magulado** [comment]
Hi @CosmoD41 

Thank you for submitting this bug report.
We were able to confirm the issue.
A fix will be patched out soon in the future game updates.

Ref: ECO-8533

**Comment by D3nnis3n** [comment]
Fixed in 11.1.3.
