### ISSUE TITLE
Law Place or Pick Up Object triggers multiple times on placing certain objects

### ISSUE THREAD

**Issue by gmt2001** [StrangeLoopGames/EcoIssues#25258]
Version: 0.11.1.1 beta release-758

When placing certain objects, the **Placing Object** trigger of **Place or Pick Up Object** triggers multiple times. The trigger for **Pick Up Object** correctly triggers only once

I have confirmed this issue on:

- Windmill
- Transmission Pole
- Wind Turbine

Here are some demo screenshots when placing a Transmission Pole

----------

_Law_
![Screenshot 2024-11-16 112725](https://github.com/user-attachments/assets/4ca598f0-ba9d-4ec3-b5e7-7333d194e72f)

----------

_Place Transmission Pole_
![Screenshot 2024-11-16 112749](https://github.com/user-attachments/assets/054316cb-e820-4dda-8731-d01616926d8d)

----------

_Pick Up Transmission Pole_
![Screenshot 2024-11-16 112821](https://github.com/user-attachments/assets/9c0f1f8c-5b3d-4b37-9e23-a0fad7c0631b)

**Comment by Daniel-Magulado** [comment]
Hi @gmt2001 

Thank you for taking the time to submit this bug report! We’ve reviewed your feedback and were able to verify the issue. Your help is invaluable in making the game better, and we truly appreciate your support!

Ref: ECO-8546

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14564, release version pending.
