### ISSUE TITLE
USER ISSUE: join button greyed out on many servers

### ISSUE THREAD

**Issue by adisciple50** [StrangeLoopGames/EcoIssues#25255]
\
**User Id: (036e7b61-a882-4782-f971-08dc8cbaa721)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
go to server browser its greyed out

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
The requested server was not found (ID = ed945fec-e656-450d-905d-05c5b3e59970). It either doesn't exist, or is not registered on the master server.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Not reproducible, make sure to wait a few seconds until the list got all necessary data, before that the join button is not available. If the issue persists, please reach out to support@strangeloopgames.com, potentially you have some local issue.
