### ISSUE TITLE
Housing Rent charges 0 with dynamic calculated values

### ISSUE THREAD

**Issue by gmt2001** [StrangeLoopGames/EcoIssues#25251]
Version: 0.11.1.1 beta release-758

Rent for housing charges 0 if a dynamic calculated value is used, but works as expected with a hard-coded value or a static calculated value

When a calculated value which is dynamic is used, the game does not prompt the renter to select a bank account to pay from, and then charges 0 credits as the rent, even though the calculated value correctly generates a valid number

I also tried setting the rent directly to _Housing Value In Districts_ instead of using a formula and got the same result

Setting the rent to a calculated value which is static, such as _Arithmetic 1+2_ will work

----------

Expected result if fixed is one of (Whichever approach devs prefer):
- Dynamic value is calculated and displayed at time of starting rent and then does not change for resident unless they leave/evict and then re-rent
- or Dynamic value is calculated and charged at each rent interval based upon current numbers at the time of the interval
- or Dynamic Calculated Values block clicking the _Set Rent_ button and display error if devs do not intend to ever allow it

---------

The intended use-case here is to set rent based upon the housing value of the house being rented by automatic calculation

---------

**_Hard-Coded Value Working_**
![Screenshot 2024-11-10 100451](https://github.com/user-attachments/assets/25f251ff-e47d-4dd6-9d27-ec47283c80ed)
![Screenshot 2024-11-10 100432](https://github.com/user-attachments/assets/7010c953-1e92-40d4-84f4-a7830c86a8d2)

----------

**_Static Calculated Value Working_**
![Screenshot 2024-11-10 101531](https://github.com/user-attachments/assets/7552dd4b-c033-4c94-8f7a-3b2a135ad96b)
![Screenshot 2024-11-10 101617](https://github.com/user-attachments/assets/667ff906-cc08-42de-b1ac-eae42cdcd8a7)

----------

**_Dynamic Calculated Value Not Working_**
![Screenshot 2024-11-10 100318](https://github.com/user-attachments/assets/1060a73e-4f2b-456c-aba7-e1d1a9f0b37e)
![Screenshot 2024-11-10 100257](https://github.com/user-attachments/assets/b1f84c69-1f0a-4600-a1a0-ed8b75701ff9)

----------

**_Housing Value and District_**
![Screenshot 2024-11-10 100329](https://github.com/user-attachments/assets/29f28ee5-3427-4335-8a56-f289faf0595c)

----------

**_Same Calculation Displayed by a Law_**
![Screenshot 2024-11-10 101001](https://github.com/user-attachments/assets/6f4890e6-4c4b-4f7a-bf19-e4c943eb5ae9)
![Screenshot 2024-11-10 100949](https://github.com/user-attachments/assets/713ef122-246b-4942-90ef-164a92872dd7)

**Comment by Daniel-Magulado** [comment]
Hi @gmt2001 

Thank you for submitting this bug report.
We were able to confirm and verify the issue.
A fix should rolled out in the future game updates.

Reg. ECO-8485

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14598 in 11.1.3.
