### ISSUE TITLE
USER ISSUE: 2 Iron Pickaxe pretends to be 1.

### ISSUE THREAD

**Issue by CB-Gamer** [StrangeLoopGames/EcoIssues#25256]
\
**User Id: (c4d29384-b3b4-498c-0200-08dc8cbaa722)**
**Version:** 0.11.1.1 beta release-758

**Steps to Reproduce:**
Dont know if i can reproduce it. No easy way since i play on OfficialServer.
Bought x2 Iron Pickaxe from Shop. Bought them at the same time, as a total of "2"
Had both on the Hotbar. 1 on Key 1 and the 2nd on Key 4.

**Expected behavior:**
Bought x2 Iron Pickaxes. Got 2. Should be 1 gets used to 0% Durability, then still have 100% durab on the 2nd.

**Actual behavior:**
Both Pickaxes acted as 1. Did i take 1 out and mined, durability loss on both. Same with "Max Durab" lowered. They shared everything.
Tried give one away to test if changing hands did something. He could also see durability loss on his, when i mined with the other one. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, dont think so. Official Server Dusky Robin #7.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/user-attachments/files/17778771/Player.log)

[Player-prev.log](https://github.com/user-attachments/files/17778772/Player-prev.log)

**Comment by CB-Gamer** [comment]
Note: I do have the pickaxes still on me on mentioned server if "Admin" wants to have them for bug checking. You will owe me one Pickaxe tho ;) 
// OfficialGamerno1

**Comment by D3nnis3n** [comment]
Fixed in 11.1.2.
