### ISSUE TITLE
Ignore Authorization does not work on claims owned by players

### ISSUE THREAD

**Issue by gmt2001** [StrangeLoopGames/EcoIssues#25264]
Version: 0.11.1.2 beta release-767

The Ignore Authorization action does not work at all on claims owned by players

------

_Law_

![Screenshot 2024-11-18 194507](https://github.com/user-attachments/assets/050b948d-cb2f-435f-b2d0-3654259e9654)

------

_Authorization, Location, and Owner_
![Screenshot 2024-11-18 194529](https://github.com/user-attachments/assets/498ff7b3-6218-448a-af84-1cd43d3b97f0)
![Screenshot 2024-11-18 194536](https://github.com/user-attachments/assets/31f489e0-29ec-405d-84ba-6223c15e9189)

------

_Cleanup Tree Debris Result_

Ignore Authorization failed

Send Notice succeeded

![Screenshot 2024-11-18 194544](https://github.com/user-attachments/assets/f4bb959a-0ee5-4c27-96d0-6cf5664d79cd)

**Comment by Daniel-Magulado** [comment]
Hi @gmt2001 

Thank you for submitting this bug report.
We were able to confirm the issue.
A fix will be rolled out in the future game updates.

Ref: ECO-8503

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14598 in 11.1.3.
