### ISSUE TITLE
USER ISSUE: World Objects / Placed Objects not visible or interactable 

### ISSUE THREAD

**Issue by Jondawg** [StrangeLoopGames/EcoIssues#25268]
\
**User Id: (be4729dc-26fa-4312-b120-08dcfdbdc43c)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
Currently stuck like this. Can't see or interact with certain trees and placed objects in an approximate 4 chunk area. Others have verified they are there for them. I simply walk through them.

**Expected behavior:**
I should be able to see and interact with these things

**Actual behavior:**
Stockpile is gone and I can't interact with it, but can see all the items stored within in. Cart is invisible, tree is invisble, plaque, contract board, etc. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed, playing on official Dusky Robin server

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Jondawg** [comment]
[error.txt](https://github.com/user-attachments/files/17839911/error.txt)
[Player.log](https://github.com/user-attachments/files/17839912/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17839913/Player-prev.log)

**Comment by Jondawg** [comment]
View during bug: https://youtu.be/XALDq7tzhBw

Post bug view: https://youtu.be/haMFyt26p_k

**Comment by D3nnis3n** [comment]
Wondering if related to https://github.com/StrangeLoopGames/EcoIssues/issues/25279, but unfortunately no repro for me either.

**Comment by D3nnis3n** [comment]
Seems to be the same issue, merging with https://github.com/StrangeLoopGames/EcoIssues/issues/25279.
