### ISSUE TITLE
Placeholder Text ("%WornParts%") Appears When Interacting with Steam Truck Using Pickaxe

### ISSUE THREAD

**Issue by Crazy-Spy** [StrangeLoopGames/EcoIssues#25260]
When attempting to interact with the Steam Truck using a Pickaxe, a placeholder text "%WornParts%" briefly appears on the screen.

Steps to Reproduce:

1. Equip the Pickaxe.
2. Approach the Steam Truck.
3. Left-click on the Steam Truck to attempt to pick up its contents.
4. Observe the screen for any messages or text that appear.

Expected Behavior:

No placeholder text should appear; the appropriate message or interaction result should display.

Actual Behavior:
The message "%WornParts%" briefly flashes on the screen when interacting with the Steam Truck using the Pickaxe.

![Eco 2024-11-17 10-00-31 mp4_snapshot_00 04 509](https://github.com/user-attachments/assets/4d5e24ea-e096-44bf-8879-beb270660a24)

https://github.com/user-attachments/assets/098460e8-1265-4861-bee1-d80ecae906d3

**Comment by Daniel-Magulado** [comment]
Hi @Crazy-Spy 

Thank you for submitting this bug report.
We were able to confirm this issue.
A fix should be out in the future game updates.

Ref: ECO-8504

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14598 in 11.1.3.
