### ISSUE TITLE
USER ISSUE: Download speed decrease		

### ISSUE THREAD

**Issue by MaxDevas** [StrangeLoopGames/EcoIssues#25263]
\
**User Id: (8904c0cb-ea62-4bba-b851-08dcfdbdc43c)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
Join a private server

**Expected behavior:**
It should download world at a decent speed

**Actual behavior:**
It downloads the world at 180kB/s, and once the loading is at about 25% it collapses to less than 60B/s

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your system unfortunately doesn't fulfill the minimum requirements for Eco:

Processor: AMD Ryzen 5 1500X 3.5 GHz Quad-Core or Intel i5-6500 3.2 GHz Quad-Core or similar
Graphics: AMD Radeon R9 290 or NVIDIA GTX 970 or similar (Minimum: 4 GB VRAM)

This is likely the cause for the issue you are encountering.
