### ISSUE TITLE
USER ISSUE: Anything with wheels can not move

### ISSUE THREAD

**Issue by Alexandermp87** [StrangeLoopGames/EcoIssues#25269]
\
**User Id: (5a541730-844a-4668-7237-08dc8bebe8f1)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
1.Get a cart/wheel barrel or a powered cart
2.get in/hit the action button 
3.Try and move with WASD
4.Nothing happends

**Expected behavior:**
It should move

**Actual behavior:**
Does not move at all

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods are installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/17843728/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17843729/Player-prev.log)

**Comment by D3nnis3n** [comment]
Not reproducible. If you have any sort of controllers attached to your PC, please try to plug them out before starting Eco.
Otherwise please reach out to support@strangeloopgames.com. It is very unlikely for this to be a bug.

**Comment by Alexandermp87** [comment]
thanks you, that fix my problem. I usually have my HOTAS plugged in but I will keep it unplugged when I play Eco. thanks for your help.
