### ISSUE TITLE
Consolidating Town Claim Stakes from different town fuses them and gives you 2 of one town instead of keeping them separated

### ISSUE THREAD

**Issue by Casasbellas** [StrangeLoopGames/EcoIssues#25276]
I'm playing on an unofficial server at the moment (Dadspeed) and I put my two claim stakes from different town, let's call them "Town A" and "City B" in a Storage Chest.

I did some consolidation of the inventory for other stuff from a shop and I came to check a day earlier to take the stake out and found they were both sharing a same slot and they both came Town Claim Stake from "Town A", so I lost the "City B".

Initial situation: 
- 1 Town A Stake
- 1 City B Stake

Replicating the issue:
- Place 2 town stakes in storage chest from different towns.
- Use consolidate from a Store.
- Open the chest and the stake will fuse.

Results:
- 2 Town A Stake
- 0 City B Stakes

**Comment by Daniel-Magulado** [comment]
Hi @Casasbellas 


Thank you for taking the time to submit this bug report! We’ve reviewed your feedback and were able to verify the issue. Your help is invaluable in making the game better, and we truly appreciate your support!


Ref. ECO-8547

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14564, release version pending.
