### ISSUE TITLE
USER ISSUE: Server not responding after a few minutes

### ISSUE THREAD

**Issue by Zuikis121** [StrangeLoopGames/EcoIssues#25274]
\
**User Id: (35e468b2-ad52-46a0-dc37-08dd0b3bb4a7)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
1. Join friend's server hosted through "Host a world"
2. Wait / Play for a few minutes
3. You lose connection, but on the server's side you just stop moving

**Expected behavior:**
Not kicked me from the server

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, fresh install of game

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please provide the client and server logfiles as described in the issue template.

**Comment by D3nnis3n** [comment]
Closing due to necessary information not provided. Please feel free to open a new issue when you can provide the information required.
