### ISSUE TITLE
USER ISSUE: Part durability degrades when building is paused

### ISSUE THREAD

**Issue by ZPanic0** [StrangeLoopGames/EcoIssues#25271]
\
**User Id: (421ef73d-ec04-43e6-b100-08dcfdbdc43c)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
1. Build a structure that provides mechanical power (windmill, water wheel, etc).
2. Connect the structure to a device that uses mechanical power (rocker box, etc).
3. Queue work in the structure that CONSUMES the mechanical power (copper concentrate, etc).
4. Ensure that there is enough material in accessible inventories for the task to begin, BUT NOT ENOUGH TO COMPLETE THE TASK.
5. Wait for the task to halt for materials.
6. Observe the parts on the structure providing mechanical power.

**Expected behavior:**
The parts installed in the structure providing mechanical power should not take damage as the structure is technically not providing a resource.

**Actual behavior:**
The parts installed in the structure providing mechanical power will degrade as if in constant use.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @ZPanic0 

Thank you for submitting this bug report! We've reviewed it and were able to confirm the issue. We appreciate your help in improving the game!

A fix will be included in an upcoming game update.

Ref. ECO-8544

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14564, release version pending.
