### ISSUE TITLE
USER ISSUE: crash after 5 or 10 min of playing in coop

### ISSUE THREAD

**Issue by bigolithetird** [StrangeLoopGames/EcoIssues#25272]
Log File:
[Physics::Module] Initialized MultithreadedJobDispatcher with 15 workers.
Initialize engine version: 2023.2.13f1 (70197a359f36)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/UnitySubsystems
kGfxThreadingModeSplitJobs is not supported on Direct3D 11. Reverting to kGfxThreadingModeClientWorkerJobs instead.
GfxDevice: creating device client; kGfxThreadingModeClientWorkerJobs
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon RX 7800 XT (ID=0x747e)
    Vendor:   ATI
    VRAM:     16152 MB
    Driver:   32.0.12011.1036
D3D11 device created for Microsoft Media Foundation video decoding.
Version: 0.11.1.2 beta release-767
RAM: 32693MB Total / 23866MB Free
OS Version: Windows 11  (10.0.22631) 64bit
CPU: AMD Ryzen 7 2700X Eight-Core Processor  - 16 Cores - 3,7 Ghz
System bit-ness: 64
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
UnloadTime: 0.850100 ms
start of EcoBootstrap.Initialize
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)

end of EcoBootstrap.Initialize
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.ComponentSystem.Bootstrap.EcoBootstrap:Initialize(String)
Unity.Entities.DefaultWorldInitialization:Initialize(String, Boolean)

WwiseUnity: Wwise(R) SDK Version 2023.1.4 Build 8496.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
AkSoundEngineInitialization:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Setting Plugin DLL path to: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data\Plugins\x86_64
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkCommonPlatformSettings:get_AkInitializationSettings()
AkSoundEngineInitialization:InitializeSoundEngine()
AkInitializer:OnEnable()

WwiseUnity: Sound engine initialized successfully.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
AkSoundEngineInitialization:InitializeSoundEngine()
AkInitializer:OnEnable()

The referenced script (Unknown) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Notification') is missing!
Ambiguous UI component types ignored: ViewEditorUI,BaseUI,CalibrationSequenceUI,SeriesPopupUI,AutoViewUI,AutoModalUI
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.UI.UIManager:Start()

[06:47:44.430] Initializing platform: SteamPlatform
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Platform.PlatformManager:AddPrimaryPlatform(Object[])
Eco.Client.Platforms.Platform.PlatformManager:Start()

[06:47:44.559] Initialized social platform: SteamSocialNetwork
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[06:47:44.570] Initialized social platform: DiscordSocialNetwork
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AttemptAddSocialPlatform(Type, Object[])
Eco.Client.Platforms.Framework.Social.SocialNetworkManager:AddSocialPlatforms()

[06:47:44.618] Authenticating with our primary platform.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)... (591Korestants)

**Comment by D3nnis3n** [comment]
Please provide the client and server logfiles as described in the issue template.

**Comment by D3nnis3n** [comment]
Closing due to necessary information not provided. Please feel free to open a new issue when you can provide the information required.
