### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Truecrusher** [StrangeLoopGames/EcoIssues#25275]
\
**User Id: (f1049f8d-29f5-40e3-2d5f-08dcce89dbe7)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
try to load a world and it only loads at 72b/s

**Expected behavior:**
load a world at a muuuuch faster rate

**Actual behavior:**
no actual error message the world would never load if i let it continue since it's at 72bits a second cancelled by user

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25277
