### ISSUE TITLE
Weight Calculation missing for Shorn Wool

### ISSUE THREAD

**Issue by Kisami119** [StrangeLoopGames/EcoIssues#25270]
![image](https://github.com/user-attachments/assets/ab33890b-8b1c-4c85-9630-ada0cb9feba3)
As you can see in this image, the weight bar is correctly full, but the displayed carrying capacity is wrong. Looks like the offender in this case is "shorn wool". I am carrying 75 shorn wool, but it is not displayed in the chart.

**Comment by D3nnis3n** [comment]
Not reproducible. Any mods installed or commands used?

Needs reproduction steps to be looked into.

**Comment by Kisami119** [comment]
Can no longer recreate it after server restart. Can't recreate it elsewhere. The Ecophoria server is running a handful of mods:
- DiscordLink
- Trade Assistant
- Global Currency
- NidToolBox
- Chronicler
