### ISSUE TITLE
USER ISSUE: Various Items dont stack anymore

### ISSUE THREAD

**Issue by Teax20** [StrangeLoopGames/EcoIssues#25288]
\
**User Id: (cbe6dbb2-7947-49a4-6923-08dc8d11157e)**
**Version:** 0.11.1.3 beta release-795

**Steps to Reproduce:**
craft more than 1 Stockpiles i.e

**Expected behavior:**
Should stack

**Actual behavior:**
Dont stack anymore

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/25293
