### ISSUE TITLE
USER ISSUE: bug or crash 544

### ISSUE THREAD

**Issue by Mamone-eco** [StrangeLoopGames/EcoIssues#25289]
\
**User Id: (121cd207-1b85-4cd0-8703-08dcec7de103)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
when i drive i can crash, when i get suck in the middle of the earth = bug my computer turn off!!! in so many situation i crash the list is so long.

**Expected behavior:**
nothink with the crash, but i hope the game will improve shop tradding. one example be able to make a list from the shop you visit to be able to delibery it later. or being able to ask player shop directly like make a wish list. being able to use the Y menu and had many request like currency+distance+currency player available.

**Actual behavior:**
The following error message popped up:
```
Server not responding
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
serveur have many mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by antaeusdk** [comment]
It sounds more to me like there is a problem with your power supply and the draw on it exeeds what its capable of. If it has been able to previously, it might be down to its age.

**Comment by D3nnis3n** [comment]
Sorry, to investigate crash issues we do require the logfiles from the crash.
If a crash leads to the computer turning off, that is extremely unlikely to be caused by Eco - that is typically a hardware defect, most often of the PSU.
