### ISSUE TITLE
USER ISSUE: Failed to handle RPC Method: OpenUI

### ISSUE THREAD

**Issue by RastaTux** [StrangeLoopGames/EcoIssues#25283]
\
**User Id: (e0c31512-7a27-4862-98c7-08dc8d1bff58)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
on local singleplayer server with a friend joining via steam, the picture items stay white when we open them.

**Expected behavior:**
picture items should show up

**Actual behavior:**
the picture frame stays white

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Fixed via https://github.com/StrangeLoopGames/Eco/pull/14564, release version pending.
