### ISSUE TITLE
Feedback: Rework item search

### ISSUE THREAD

**Issue by SilverjetPlane** [StrangeLoopGames/EcoIssues#25281]
Before/with the bug #25230, when searching at any crafting table or container for something in the connected inventory, all containers not having the item(s) [with the string in it that was searched for] were not shown at all, providing only the containers with the desired items in it. Now, all containers are shown, and if there is no matching item, it's displayed with [...]. This makes the search quite impractical as you have to scroll a lot before actually finding something, on top of that the list seems to jump when being updated by a crafting table or another player consuming or finishing items. At least, an option to hide all containers that don't have the desired items in them would be nice. 
I guess this is not so much a bug than a not-feature because of fixing #25230, but maybe the log tells otherwise. 

\
**User Id: (0a0a79a8-6ba0-4fca-bec1-08dcbd51a712)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
Search the inventory tab for something (via text string) in a container or a crafting table.

**Expected behavior:**
Show all items in the connected inventory matching with the search term, ignoring containers that don't contain the desired item

**Actual behavior:**
Showing all connected containers, those that don't have the desired item with the [...] icon signifying there are other items in it which mostly is irrelevant when searching. The list also jumps when being updated by processes changing items in inventories so you have to scroll a lot and cannot sort items easily. 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. 
[Player.log](https://github.com/user-attachments/files/17940262/Player.log)

**Comment by D3nnis3n** [comment]
This is indeed not a bug, but I added it as improvement suggestion internally.
