### ISSUE TITLE
Character Screen - White background

### ISSUE THREAD

**Issue by WpFeltac** [StrangeLoopGames/EcoIssues#25296]
Version : latest (11.1.3)
Steps to reproduce : Launch the game (for the first time)

Screenshot : 
![image](https://github.com/user-attachments/assets/c517bb28-cfbb-4729-ae2e-84b18f5addda)

UI works fine (right panel changes according to what is selected on the left one) but I have ne preview and clicking the ">>" button doesn't work

**Comment by D3nnis3n** [comment]
Already fixed in Hotfix 11.1.4, releases in a few hours.
