### ISSUE TITLE
Campfire does not work

### ISSUE THREAD

**Issue by konstantinkuehn** [StrangeLoopGames/EcoIssues#25295]
User Id: (2ea9192f-e481-4f8b-f60c-08dcbcb28326)
Version: 0.11.1.3 beta release-795

Steps to Reproduce:
1. Build Campfire
2. Place it
3. Craft food
4. Apply work
5. nothing happend

Expected behavior:
That crafting starts

Actual behavior:
Campfire does not process the food. Timer does not run even if work is applied, campfire is on and the resources are in storage
This issue does not affect everyone on the server, for some player it does work.

Do you have mods installed? Does the issue happen when no mods are installed?:
U Cat Price Calc -  not tested yet 

![image](https://github.com/user-attachments/assets/a51ea814-a919-41b5-afe3-276d6ff213bc)
[Player.log](https://github.com/user-attachments/files/18013066/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/18013067/Player-prev.log)

**Comment by konstantinkuehn** [comment]
https://github.com/user-attachments/assets/d004177d-5db4-490d-81de-dcb2ab58f76d

**Comment by Mkorny** [comment]
Can repro even with the actual ingredients in the inventory.

If the Project is created, then you right click on the campfire directly, it does feed the ingredients in.

**Comment by TwistedGate** [comment]
This happens not to just the Campfire, but *everything*. Having the same issue with anything that makes stuff depsite chests and/or stockpiles being marked as Input.

**Comment by D3nnis3n** [comment]
Fixed in 11.1.4.
