### ISSUE TITLE
Right clicking food that has been dragged from chest to toolbar or backpack eats one and destroys all the rest

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#253]

**Comment by craig-jong** [comment]
Items crafted at the same time (repeated work orders) are all assigned the same guid

**Comment by craig-jong** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/commit/a903664339b1e7cdfc0b7e408ef2d0d63b700773
