### ISSUE TITLE
We need to talk about Toilets

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25309]
Mods? No.

https://github.com/user-attachments/assets/fc4f920c-27a6-4fab-94f2-4cb48879e69c

![image](https://github.com/user-attachments/assets/b2914ce7-d671-421b-a1a5-0d468a6952f3)

**Comment by D3nnis3n** [comment]
Fixed in SVN, either 11.1.5 or 11.1.6.
