### ISSUE TITLE
USER ISSUE: i can not play eco

### ISSUE THREAD

**Issue by seelenhol** [StrangeLoopGames/EcoIssues#25306]
\
**User Id: (00000000-0000-0000-0000-000000000000)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
You are in offline mode, but this server is not - you cannot join it until your connection to the Strange Loop servers has been restored.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
You are in offline mode, make sure you are online, no security software is blocking access and no VPN is active. Also note that there is known reports about Starlink internet not functioning with Eco. This is not a bug though, so if the issue persists you better reach out to support@strangeloopgames.com.
