### ISSUE TITLE
USER ISSUE: Apparence invisible

### ISSUE THREAD

**Issue by Ciderjix18** [StrangeLoopGames/EcoIssues#25302]
\
**User Id: (fea0b53d-e763-4072-7ab4-08dcc2f971c4)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
Toujours sur tous les serveurs

**Expected behavior:**
Retrouver mon apparance, être visible

**Actual behavior:**
Invisible, sur tous les serveurs sauf mon pseudo et mes outils 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non, le problème survient lorqu'aucun mod n'est installé.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/25298
