### ISSUE TITLE
USER ISSUE: pick up picture frame doesnt work - eco crashed - cant do anything after crash (even dont write) after 5 relogs

### ISSUE THREAD

**Issue by Noobin69theFirst** [StrangeLoopGames/EcoIssues#25318]
\
**User Id: (968f8d55-b465-4e61-a5cb-08dcbd61e506)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
i tried to pick up an unowned picture frame from the wall. but i couldnt, instead my game crashed every time i tried. now i closed my game and tried it again. my game crashed again. i restarted steam/eco again (about 5  times). now i cant pick up ANYTHING. not the frame, not a carpet, nothing. i even cant use /unstuck or something. my workingorders in the top right are running. chat (other player are chatting) is up to date. but i cant type anything. not even "hello" in chat.

**Expected behavior:**
pick up the unowned picture fram/carpet/things/react to chat (cant write anything)

**Actual behavior:**
it does nothing. cant write in chat, cant use my car, cant /unstuck, cant take anything

**Do you have mods installed? Does the issue happen when no mods are installed?:**
there  are mods for eco????? im player on a server. i dont know what/if mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @Noobin69theFirst 

Thank you for taking the time to report this bug! A fix has already been implemented and will be included in the next game update. We appreciate your support in helping us improve the game!

ECO-8584
