### ISSUE TITLE
USER ISSUE: Character Invisible And Character Creation Screen Doesnt Load	

### ISSUE THREAD

**Issue by Kujopawz** [StrangeLoopGames/EcoIssues#25311]
\
**User Id: (db82143a-20df-4783-8a54-08dc8d1bff58)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
1. Loaded game and was prompted to create character
2. After customizing character, when going to select clothing, character turned pink with no texture
3. No changes would get the character to return to normal
4. Exiting the game and restarting left character as pink icon with no texture
5. Entering into any world the character is invisible and the pink character icon shows on the map
6. Trying to go back into avatar editor on the main screen shows a blue screen and avatar doesnt load	

**Expected behavior:**
The avatar creation should work normally and let you customize your character

**Actual behavior:**
The character creation leaves you with an invisible character

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

Images:

Avatar Editor: <img width="2555" alt="Avatar Editor" src="https://github.com/user-attachments/assets/2162bde1-78f8-48da-ab0f-0f27a36a10ba">
Invisible Character: <img width="1114" alt="Invisible Character" src="https://github.com/user-attachments/assets/f274bc10-27a7-44d7-9732-ac9d3bde8089">
Character Icon: <img width="98" alt="Character Icon On Map" src="https://github.com/user-attachments/assets/b38ade76-94d3-406c-9afc-4dd50339ed85">

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Log File: [Player-prev.log](https://github.com/user-attachments/files/18054332/Player-prev.log)

**Comment by Kujopawz** [comment]
So after removing my character from my registry, I was able to load the game with the avatar creation screen. It appears the issue happens when you choose messy hair and then attempt to put a hat on. When you do that, it renders the character invisible without a texture. Hopefully this helps with bug testing

**Comment by TannicArturo98** [comment]
> So after removing my character from my registry, I was able to load the game with the avatar creation screen. It appears the issue happens when you choose messy hair and then attempt to put a hat on. When you do that, it renders the character invisible without a texture. Hopefully this helps with bug testing

Where is located the character files to delete?

Thanks

**Comment by Kujopawz** [comment]
> > So after removing my character from my registry, I was able to load the game with the avatar creation screen. It appears the issue happens when you choose messy hair and then attempt to put a hat on. When you do that, it renders the character invisible without a texture. Hopefully this helps with bug testing
> 
> Where is located the character files to delete?
> 
> Thanks

In the registry at HKEY_CURRENT_USER\Software\Strange Loop Games\Eco
