### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Rmnbv** [StrangeLoopGames/EcoIssues#25315]
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
\
**User Id: (Not logged user)**
**Version:** 0.9.5.2 beta release-315

**Steps to Reproduce:**
foreater400.xcx@gmail.com

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Внутренняя ошибка сервера, Trace ID: 00-dbd838d335670bcdc0eb6b202c3e2471-b70f6db86fc3d412-00
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Внутренняя ошибка сервера, Trace ID: 00-f58a545896005ec245d87b7e3302e8c9-64fd700d6bea96b4-00
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the most recent version of Eco.
