### ISSUE TITLE
USER ISSUE: Blacksmith and Smelting in Wrong display order?

### ISSUE THREAD

**Issue by Nid01** [StrangeLoopGames/EcoIssues#25317]
\
**User Id: (02d97cc3-f21d-43bc-dec8-08dd109b83cd)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
Smelting is required to research Blacksmith, but the display order in the profession seems to be reversed.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Thanks for the report.

The tree visualizes the position of specialties based on multiple factors, not only their requirements which can lead to odd positioning, this issue is already reported in ECO-8577, as such I'm closing this one.
