### ISSUE TITLE
USER ISSUE: Kann keine Welt erstellen

### ISSUE THREAD

**Issue by Lislipur** [StrangeLoopGames/EcoIssues#25312]
\
**User Id: (bcb6a7d2-7ae2-4c1a-d47c-08dcbd395caf)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
Wenn man eine Welt erstellt egal ob man was einstellt oder nicht kommt eine Fehlermeldung: exception has been thrown by the target of an invocation.
Auch bei einem alten Spielstand sind wir raus geflogen mit der Meldung: Server not Responding

**Expected behavior:**
Er sollte die Welt laden	

**Actual behavior:**
Die Fehlermeldungen

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Nein

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Lislipur** [comment]
[log_241209125810.log](https://github.com/user-attachments/files/18067566/log_241209125810.log)

**Comment by D3nnis3n** [comment]
The issue in the log file indicates a corrupted database. If you don't use laws you should be able to just remove the database from /Steam/steamapps/common/Eco/Eco_Data/Server/Storage/ by deleting the .db file of the savegame. Alternatively you can try to restore backups from the backups folder until you find one that is still working.
