### ISSUE TITLE
USER ISSUE: I didn't cheat

### ISSUE THREAD

**Issue by RascleCat** [StrangeLoopGames/EcoIssues#25313]
\
**User Id: (e6c1c2d7-0609-4124-eb5b-08dd109b83cd)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
Tried to join FoxFamHub Server.

**Expected behavior:**
Let me load and join

**Actual behavior:**
The following error message popped up:
```
Cheat

<size=60.00%>Cheat movement detected. Report the issue if you're not cheating.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Maybe and maybe?

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server is using an experimental feature that is not yet functioning correctly and disabled by default, please let them know to set "MovementHackDetection": false, in their Users.eco.
