### ISSUE TITLE
USER ISSUE: Meteor destroyed my map and it wasstn supposed to.

### ISSUE THREAD

**Issue by Arich85** [StrangeLoopGames/EcoIssues#25310]
\
**User Id: (d1c4a5ff-9105-44f0-36f2-08dcdd209dca)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
i havent played since september. i saw that there were new features with update 11, so i updated and loaded my world. The meteor hit immediately upon loading.	

**Expected behavior:**
This map was created with no meteor

**Actual behavior:**
Somehow, in world settings, the "Has Meteor" option was ticked, and one loaded and fell as soon as my game initialized.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i do have polychrome mods installed, have never had this issue before. 

[Player.log.copy.txt](https://github.com/user-attachments/files/18053801/Player.log.copy.txt)
[Player-prev.log](https://github.com/user-attachments/files/18053802/Player-prev.log)

Is there any way to recover this world from a previous date?
Please let me know. my email is andy.rich2010ss@gmail.com. id really love to know what happened.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
There was changes to how the meteor settings work in Update 11 and it seems you haven't updated the settings according to that. You can restore a backup of the world from /Steam/steamapps/common/Eco/Eco_Data/Server/Storage/Backups and before loading edit Difficulty.eco in the configs directory to set the meteor time to the time you priorly had configured in Disasters.eco to prevent the meteor impact. (999 will likely do in any case)
