### ISSUE TITLE
USER ISSUE: Cant transfer funds from Town Treasury (draft)

### ISSUE THREAD

**Issue by mike1-2989** [StrangeLoopGames/EcoIssues#25329]
\
**User Id: (1ae652cf-d39e-4b04-66ea-08dc8cbaa722)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
1. Put a Town Foundation (keet it as a draft)
2. Create a currency
3. Send some currency to Town Treasury (draft)
4. Try to send currency from Town Treasury to anywhere else

**Expected behavior:**
Funds should be transferred

**Actual behavior:**
Nothing happens

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I'm on Sea Otter

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @mike1-2989 

Thank you for submitting this bug report.
We're able to verify this issue and a fix should be patched out in the future game updates.

QA Ref: ECO-8599
