### ISSUE TITLE
USER ISSUE: Disconnect

### ISSUE THREAD

**Issue by BBQAbiza** [StrangeLoopGames/EcoIssues#25326]
\
**User Id: (629aab80-dde1-4195-b791-08dcd72ba347)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**

I get disconnected every 15 minutes
I don't do anything special I make my house Where I cut trees 

**Expected behavior:**

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Booted by Strange Cloud
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
non

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please update to the current version 0.11.1.5 and see if the issue persists - if so, please create a new issue attaching the client logfiles as described in the issue template so we can investigate.
