### ISSUE TITLE
'desposit' typo

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2532]
![image](https://user-images.githubusercontent.com/609510/31559436-7130cf86-b005-11e7-89b5-9af802536865.png)

**Comment by MarjieAVolk** [comment]
I think that's correct.  It's confusing wording perhaps, but deposit is a noun there, not a verb, as in 'payment of 100 collected from Metachronism, deposit of 0 collected from Knexer'

**Comment by MarjieAVolk** [comment]
Probably shouldn't display the second half if it's zero also

**Comment by knexer** [comment]
No no, it says 'deSposit' instead of 'deposit'.  Grammar's fine.

**Comment by MarjieAVolk** [comment]
oh lolol I didn't see that

**Comment by johnkslg** [comment]
Fixed, and removed when 0

**Comment by johnkslg** [comment]
In the big contract PR
