### ISSUE TITLE
USER ISSUE: Authentication failed

### ISSUE THREAD

**Issue by JanGalek** [StrangeLoopGames/EcoIssues#25322]
\
**User Id: (Not logged user)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**
Start game linux version

**Expected behavior:**
can login

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:** No, downloaded clear game

[Player.log](https://github.com/user-attachments/files/18142485/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/18142486/Player-prev.log)
![Screenshot_20241215_233329](https://github.com/user-attachments/assets/438819b0-c48b-4851-b0ee-760e984ae845)

**Comment by D3nnis3n** [comment]
Please reach out to support@strangeloopgames.com if that is a persistent issue and note if you are using the SLG or Steam client, account related issues cannot be dealt with here.
