### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by RazielSoule** [StrangeLoopGames/EcoIssues#25323]
\
**User Id: (d10e0008-3270-4ee1-e9d2-08dd109b83cd)**
**Version:** 0.11.1.4 beta release-802

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
Было получено следующее сообщение об ошибке:
```
Booted by Strange Cloud

<size=60,00%>User Steam:76561197995188543 is logged into <color=white>R<color=blue>U<color=red>S <color=#FFA500>NEW<color=#00FF00>GREEN<color=#FFFF00>WORLD <color=red> Lite s2 <color=white> (1b83d30d-7075-44bb-b640-f08409cdc844) while also logged into another server <color=white>R<color=blue>U<color=red>S <color=#FFA500>NEW<color=#00FF00>GREEN<color=#FFFF00>WORLD <color=red> Lite s2 <color=white> (418ad6b8-031b-4e39-985a-2351389713f9) owned by Bes20.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by RazielSoule** [comment]
[Player.log](https://github.com/user-attachments/files/18143426/Player.log)

**Comment by D3nnis3n** [comment]
This will automatically resolve after the original server is no longer cached - for some reason the server changed it's unique ID which they should not do.
