### ISSUE TITLE
USER ISSUE: Issue #25325

### ISSUE THREAD

**Issue by Bou-E** [StrangeLoopGames/EcoIssues#25336]
\
**User Id: (558b824e-527c-4ffd-9b93-08dc8d1bff58)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
test next day, game langue FR, or EN is same bug. server french, or serveur EN (SLG) is same bug... (i have dellect all temporaly data from locallow forlder...... i creat this 2nd bug-repport for send you actuel files.

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your new issue unfortunately doesn't contain any files, not sure what you intended to send?
Feel free to just add that in a comment to the original issue https://github.com/StrangeLoopGames/EcoIssues/issues/25325.
