### ISSUE TITLE
USER ISSUE: Kicked from server by strange cloud

### ISSUE THREAD

**Issue by Mkorny** [StrangeLoopGames/EcoIssues#25333]
\
**User Id: (a876802f-4d5e-4c89-4df5-08dc8d11157e)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
Was playing in this same server before wipe/restart
Admin recreated the server after wipe
I got this the first time, been wiping my tokens on the play.eco website and I still get the same error.

Note: the server seems bugged and doesn't appear in the server list either... also doesn't seem to ping correctly...	

**Expected behavior:**
-

**Actual behavior:**
The following error message popped up:
```
Booted by Strange Cloud

<size=60.00%>User Tenebrarum is logged into [<color=green>Day 2</color> - <color=orange>Season 1.1</color>] <color=yellow><i>New Community</i></color> | Medium-Collab | <color=green>Global Fed.</color> + <color=grey>Currency</color> | <color=orange>Large World</color> | <color=red>Meteor on</color> (abcc2969-fabb-4d99-9c09-f47872b09322) while also logged into another server [<color=green>Day 1</color> - <color=orange>Season 1.1</color>] <color=yellow><i>New Community</i></color> | Medium-Collab | <color=green>Global Fed.</color> + <color=grey>Currency</color> | <color=orange>Large World</color> | <color=red>Meteor on</color> (a93cc537-6a6e-4a95-9b8a-44d06356ae93) owned by huptiq.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Mkorny** [comment]
btw... a LOT more critical than this issue I am having personally, is the fact that the server is getting stuck, not appearing for anyone in the list... 

It's kinda killing our community ... we had 150+ active players ... now we're down to 30-40 ....... :|

**Comment by Mkorny** [comment]
[Player.log](https://github.com/user-attachments/files/18222763/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/18222764/Player-prev.log)

**Comment by D3nnis3n** [comment]
The server is displayed in the server list just fine:
![image](https://github.com/user-attachments/assets/a6cd7915-ca12-4e54-8bf1-169d80136cfc)

The reason why it doesn't show ping is likely a misconfiguration:
![image](https://github.com/user-attachments/assets/46daad79-623e-4737-a686-0f3587113374)

The reason for the kick is that the server changed it's unique ID which should not really be happening for an existing server, I assume that might have happened due to the wipe that was done where it was forgotten to keep the Network.eco credentials for the server identification. That issue will automatically resolve once the old server is no longer cached.

For further questions feel free to reach out to support@strangeloopgames.com.

**Comment by Mkorny** [comment]
Hey @D3nnis3n that's the problem, this was the old name of the server. (we're actually now on day 2, and only have 39 total players ... (this issue killed our community basically :( ...)

We've been going around non-stop for 2 entire days around this :| totally out of ideas ...


Currently the network.eco file looks like this.
(no old ID, Id/pass are in place, ports are ok, it's really the oddest I have ever seen really ... it's like the server name/stats/player/etc... is all stuck in the status when we shut it down... )


{
  "PublicServer": true,
  "Playtime": "",
  "DiscordAddress": "discord.gg/Qz3XeMFJVz",
  "Password": "",
  "Name": "[<color=green>Day 2</color> - <color=orange>Season 1.1</color>] <color=yellow><i>New Community</i></color> | Medium-Collab | <color=green>Global Fed.</color> + <color=grey>Currency</color> | <color=orange>Large World</color> | <color=red>Meteor on</color>",
  "DetailedDescription": "Welcome to New Community! <br><color=#4CAF50><i>hello everyone, and welcome to the start of something special—season 1 of our brand-new eco game server and community!</i></color> <br>this is the perfect place to play, learn, and grow together in a friendly and supportive environment. <br><color=#2196F3>**server location:**</color> hosted in the eu, but players from all over the world are welcome to join the adventure. <br><color=#FFC107>**what to expect:**</color> <br>- <i>active admins</i> to ensure a smooth experience <br>- mods to enhance gameplay: <br>  - trade assistant: <color=#00BCD4>https://mod.io/g/eco/m/trade-assistant</color> <br>- a collaborative environment that values teamwork and creativity <br><color=#E91E63>**server rules:**</color> <br>- be respectful to all players. treat others as you'd like to be treated. <br>- do not harass others—this includes claim griefing, stealing, breaking roads, or spamming. <br>- groups and corporations are allowed but should collaborate and engage in the market with others. <br>- use english in general chat for better cooperation. <br>- avoid claiming land right next to others to prevent blocking expansion. <br>- claims inactive for more than 4 days will be automatically removed. <br><color=#8BC34A><i>let’s build something amazing together. jump in and be part of the journey!</i></color>",
  "ServerCategory": "Beginner",
  "IPAddress": "Any",
  "RemoteAddress": "89.163.213.89:3000",
  "WebServerUrl": "",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "RconServerPort": 3002,
  "SteamServerPort": 3003,
  "RconIPAddress": "Any",
  "RconPassword": "XXX",
  "Rate": 20,
  "DefaultSlots": -1,
  "ReservedSlots": 5,
  "MaxUsersLoadingAtSameTime": 20,
  "ID": "XXX",
  "Passport": "XXX",
  "UPnPEnabled": false,
  "RelayServerAddress": ""
}

**Comment by Mkorny** [comment]
And as a side note, look how I see it:

In the main menu:
![image](https://github.com/user-attachments/assets/fd69498d-5ab5-456d-ba76-2177b2f9b4b8)


In the "your worlds" listings:
![image](https://github.com/user-attachments/assets/ff9bba09-75dc-453a-a1ed-5e7c082e4005)
(this seems to be the closest to the correct info actually)

**Comment by D3nnis3n** [comment]
Well, your server is registered ten (sic!) times under different ID's. I wonder how or why you would change the unique ID of the server ten times. You should continue this request via support@strangeloopgames.com, it's easier to handle through there as it affects account data, not the game.

Unfortunately we already are on Christmas Holidays, so I can't promise you a quick solution. But something went seriously wrong when setting that server up. I can't find any other server with such a number of registrations - for at least 4 different users as well.

In the meanwhile please make sure that the server does not change ID again - that will certainly not help the problem and prevent any autoresolving of the problem.

**Comment by D3nnis3n** [comment]
I went ahead and removed all the duplicate entries from the database manually, it looks correct now:
![image](https://github.com/user-attachments/assets/16c1597c-27dd-4781-a539-c743ab7f29b0)

Just make sure to not change the unique id and hosting user again as long as you use the same world.
If you still do, clearance should now be faster, but when there is constantly new servers created with different ID's the caching process simply takes a while to get rid of all of them, as there is a grace time.
