### ISSUE TITLE
User Suggestion: Improve receipt filter drop down menu 

### ISSUE THREAD

**Issue by kleshchevand** [StrangeLoopGames/EcoIssues#25332]
Each time I want to check what resources are needed for things I can build I have to look those receipts up manually. 'Craftable' option is Very convenient for campfire cooking, but it is not enough when carpentry table has dosen options and i have to go over them one by one to see which ones I can add, but need resources for.

Suggestion: 
Add two more options to the menu.
1. Option to match user's specialization (ideally there needs to be an option to match level and option to see everything for that specialization)
Ex: if a carpenter without logging skill selects specialization option, carpenter will see only carpenter related receipts.
2. Option that shows receipts that user has resources for, but has no skill for (for ease of cooperation).
![image](https://github.com/user-attachments/assets/ae51f38d-b09a-483c-8f90-d32f56be756b)

**Comment by D3nnis3n** [comment]
Hello,
as I can see you already have posted a suggestion for your request on the correct tracker, given suggestions are not intended for this bug tracker I'm closing this issue.

**Comment by kleshchevand** [comment]
Yeah, sorry, I was told about canny after I created this ticket.
