### ISSUE TITLE
USER ISSUE: Cant join local server

### ISSUE THREAD

**Issue by ArSharlahy** [StrangeLoopGames/EcoIssues#25334]
\
**User Id: (a7d69131-93c2-4c9a-60f4-08dc8cbaa722)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
Start game with local custom server

**Expected behavior:**
Server starts, client connects

**Actual behavior:**
Server start
Client in  infinite loading

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/user-attachments/files/18223220/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/18223221/Player-prev.log)

**Comment by D3nnis3n** [comment]
There is CRC errors in your logs:

```
CRC Mismatch. Provided a6c308f4, calculated c06010b0 from data. Will not load AssetBundle 'aa\StandaloneWindows64\items-food_assets_all_1bd8fdb2df3d0e016629f9c98ff81640.bundle'
[11:52:29.516] RemoteProviderException : Invalid path in AssetBundleProvider: 'C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/StreamingAssets/aa\StandaloneWindows64\items-food_assets_all_1bd8fdb2df3d0e016629f9c98ff81640.bundle'.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.AddressableAssets.AddressablesImpl:LogException(AsyncOperationHandle, Exception)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:Complete(TObject, Boolean, Exception, Boolean)
UnityEngine.ResourceManagement.AsyncOperations.ProviderOperation`1:ProviderCompleted(T, Boolean, Exception)
UnityEngine.ResourceManagement.ResourceProviders.AssetBundleResource:LocalRequestOperationCompleted(AsyncOperation)
```

I'm not even sure that is from the base game at all, as such please conduct a full reinstall of Eco:
1. Uninstall the game via Steam.
2. Remove /Steam/steamapps/common/Eco folder. (Backup any savefiles from the contained Eco_Data/Server/Storage folder beforehands, if you want to keep and restore them later)
3. Remove AppData/LocalLow/Strange Loop Games folder. (Easiest to do by opening run tool and entering %LOCALAPPDATA%Low, brings you directly to the folder)
4. Open Registry Editor, and delete the key folder:
![image](https://github.com/user-attachments/assets/7f37247e-91dc-4ea3-a084-65a4343ac960)
5. Reinstall the game and try again without installing any mods.

If you need further help after that, please reach out to support@strangeloopgames.com.

**Comment by ArSharlahy** [comment]
It worked with one extra step, i repited 3rd step with game running to force clean what ever steam cloud loaded. Thank you.
