### ISSUE TITLE
USER ISSUE: Booted by strange cloud error

### ISSUE THREAD

**Issue by JDTaupiac** [StrangeLoopGames/EcoIssues#25343]
\
**User Id: (3c1bfde9-08fb-4f83-5bf9-08dc8d11157e)**
**Version:** 0.11.1.6 beta release-826

**Steps to Reproduce:**
Surrends suddently for each player, the hex code linked to each mentionned server is the same for each crash... (see the log)

**Expected behavior:**
... let us play :D

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Booted by Strange Cloud

<size=60.00%>User Broopyn is logged into On derange (4c21756e-d65f-47ca-9053-9bc1be65ab93) while also logged into another server On derange (7d4f05df-2551-4b93-abeb-83d40948b929) owned by Broopyn.</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your server "On derange" is registered multiple times with different unique ids. Make sure that the unique id in Network.eco is preserved and not changed while playing the same world and that the world is started by the same user. The error will self-resolve once the older servers are no longer cached.
