### ISSUE TITLE
When following a link to vote on a law, expand the left nav bar

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2535]
The left nav bar is completely collapsed.  It should have Laws and Proposed Laws expanded

**Comment by syuzan-yeranosyan** [comment]
Could you please share a screenshot with explanation how it should be. 
It has this look on my local http://prntscr.com/gznue0 and I'm not sure what should be changed

**Comment by MarjieAVolk** [comment]
Yeah your screenshot is how it should be... guess that's not what I saw, I saw the bar on the left completely collapsed.  That's only when I navigate there from in game.

**Comment by syuzan-yeranosyan** [comment]
If you are about this server http://5.175.16.88 I have checked, the code is not updated there. 
Also the APi should be updated there, as it returns ""An error has occurred." in most of Api calls. 

I think when the updates are there, the shared issue will be solved

**Comment by MarjieAVolk** [comment]
I don't understand.  What server are you linking too?  The link doesn't work for me.  Are you requesting an update of the web server API?

However I just tested it again on master and it seems to be working, so if you think it is fixed I guess we can close this
