### ISSUE TITLE
Fix the security popup thing when running the client

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2536]
That is, the windows security popup that tells you the eco client is unsafe or whatever

**Comment by metachronism** [comment]
I dont know what this is?

**Comment by MarjieAVolk** [comment]
I don't either >>

**Comment by SeanAtr0n** [comment]
The warnings about how untrustworthy the download is?
Probably needs code signing

**Comment by MarjieAVolk** [comment]
Oh yeeeeeeah lol

**Comment by metachronism** [comment]
I dont know why we would do this.  won't need it once steam is done and you have to pay for a certificate, seems like a huge hassle
