### ISSUE TITLE
More animals

### ISSUE THREAD

**Issue by gloddox** [StrangeLoopGames/EcoIssues#2539]
I think we could add a alot more variety of animals to Eco. Adding a skill tree that allows us to tame them and feed them and over time they would make more animals would be great so we don't need to hunt the wild life all the time. Also adding wagons that ( ox's, horses, or donkey's) could be attached to would be nice so we had a better mode of transportation that can move big loads quicker than normal carts but are still eco friendly.

**Comment by MarjieAVolk** [comment]
I'll convey your ideas to the team :)  We have added many more plant and animal species in the most recent release, and will continue to add more.  We hope to have animal taming eventually, but it is not high on our priority list right now.
