### ISSUE TITLE
Player kick while hovering over player name on map

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#254]
getting kicked(possible exeption) while hovering over other players name on the minimap

**Comment by stett** [comment]
@noblackthunder Did this happen every time? I can't seem to reproduce the problem. I'll wait to close the issue until our next playtest

**Comment by noblackthunder** [comment]
happent everytime for me at least even on restart of the game

**Comment by newzealdan** [comment]
When a player leaves the server, their icon remains on the minimap. Mousing over them causing the game to crash. Happens everytime. Of the minimap icons on the attached screenshot, only 2 represent online players, the rest are those that have left.

![image](https://cloud.githubusercontent.com/assets/6193670/16898721/e8b3506e-4c39-11e6-8bf5-762f3297499f.png)
