### ISSUE TITLE
A pointer/compass that points towards an area of interest

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2540]
Instead of using x, y, z coordinates to direct a player to a location, have a small gui arrow or marker that points to where they need to go.

Accepting a contract would point you towards where the contract is focused to, 
You can drop a marker on the minimap to be directed towards it,
Tooltip on players - instead of location - would allow to direct yourself to them

Essentially anywhere the XYZ coordinate is exposed to the player, make it possible to drop a marker

![image](https://user-images.githubusercontent.com/6262198/31562519-9a1d727c-b010-11e7-8fc7-2b5c53e6e8a7.png)

**Comment by johnkslg** [comment]
World Markers will help with this

**Comment by MarjieAVolk** [comment]
This has been implemented
