### ISSUE TITLE
Need better progress tracking on contracts

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2541]
Would be nice to have a % complete element somewhere. Maybe something similar to durability, but on the contract icon.

The contract could also list out elements of the contract like:

67 / 100 iron ore delivered
or
15 tree debris remaining

**Comment by johnkslg** [comment]
It does track it now per-clause.  Perhaps we could make a nice number bar visible on the UI, I like that idea.

**Comment by johnkslg** [comment]
Pushing to post beta

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#367
