### ISSUE TITLE
'off' streetlamps are on when loaded

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2546]
I unchecked the on box for a streetlamp, when i logged back in it's turned on. The other streetlamps are flickering due to low power and all the ones i turned off are on.

**Comment by SeanAtr0n** [comment]
seems to be a server side issue
![image](https://user-images.githubusercontent.com/774628/31568875-bb851a12-b02b-11e7-9a5b-0ea8b5b65308.png)

**Comment by MarjieAVolk** [comment]
Fixed in svn

**Comment by SeanAtr0n** [comment]
whys it say consuming 100w if its purely svn related?

**Comment by MarjieAVolk** [comment]
Yeah there are other issues as well, but if it's turned off with the on off component, it won't be lit up anymore
