### ISSUE TITLE
Adding stack to stockpile on a project requiring a lot adds more to project than is placed in stockpile

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2552]
i had a player queue 1000 iron ingots for me which required 790 iron ore and when i added 20 iron ore to the stockpile it just kept adding the same stack to order until the order didn't need anymore, this is not a one off happening, it can also happen when adding stone to a project at a kiln (but not fill the order just add more to the project than i placed in stockpile) i tired this with the stockpile window open and dragged from carrying slot to the stockpile slot, the stack disappears and appears again, then disappears as its automatically added.

I searched as best i could to see if this was already posted (didnt finf anything open or closed) by the way this is on Normal realease and NOT staging.

this also can happen if its an order i have placed at a table and not just from another player adding

**Comment by MarjieAVolk** [comment]
Was this the 6.0 release or the 6.0.1 release?

**Comment by MarjieAVolk** [comment]
This sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/2387, which was fixed in 6.0.1

**Comment by metachronism** [comment]
yeah this bug was specifically fixed in 6.0.1

**Comment by Conchipedia** [comment]
6.0.0
