### ISSUE TITLE
[0.6.0.1] Spam will kill servers?

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#2553]
With the new release I noticed the chat is slow, so to see how slow it actually is, we spammed the chat with random text, the text started appearing slowly, 1 line at a time, and the world stopped loading.

The server crashed and was not connectable.

To replicate, join any server and spam their chat, the server will lagg and eventually stop working.

**Comment by ClayC90** [comment]
The issue has been found, the chat needs to be wiped, for this to work nicely, so a busy server will most likely suffer crashes because of this..

Solution, maybe load the last 500 chat messages, or load all buy then have a new list/array of messages that users write into, when message is sent to all, throw it into the big array?

The following file is the save with the chat and everything:
https://www.dropbox.com/s/m2rxlm9coai1k4k/chat-issue.eco?dl=0

**Comment by MarjieAVolk** [comment]
I've been trying to repo this, but no luck so far.  I'm guessing it has to do with having more people on the server?  Like at least two, one to send and one to receive?  I can reduce the number of backlog messages that get sent over on connect, but that doesn't sound like it will fix the problem.

**Comment by ClayC90** [comment]
@MarjieAVolk when you have tens of thousands of messages in the log, and server has been running for a while, at least, when sending multiple short messages this gets slowed down,

We were only 2 people online at the time of testing. not sure if this is related though, might be helpful to try to have a few people on to see if it slows down ;)

**Comment by WeaselDog** [comment]
Chat has been optimized since this was posted and it seems fixed.

@D3nnis3n I made a macro that spams chat faster than humanly possible on sea-otter official after it had been abandoned with 500 total players. It did not cause any issues.
