### ISSUE TITLE
Enhancement: tool repair cost efficiency

### ISSUE THREAD

**Issue by jroovers** [StrangeLoopGames/EcoIssues#2557]
Right now, repair costs are static, e.g. to repair a steel axe from 0% to 100% you need 10 steel.
When you have tool smithing efficiency 5 the same steel axe costs only 2 boards and 5 steel to craft from scratch.

Would it be possible to lower the repair costs based on your tool smithing efficiency skill (or a new skill specifically for repairing).

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#366
