### ISSUE TITLE
[6.0.1] Plants no longer reduce CO2

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2558]
So since the new update of 6.0.1, we have noticed something odd that our CO2 increased very quickly and now with nearly nothing running it's stuck at 500 CO2 Parts Per Million.

Someone on the server noticed that plants are not really doing anything compared to 6.0.0 where it jumped from -29.(Something) to like -0.0555555559694767 (Thanks, Jimpen).
And the numbers won't change from that one specific value that it's stuck at.

![co2 plants](https://user-images.githubusercontent.com/4078460/31624958-aab47162-b2a4-11e7-8475-6b5ba6e6ea70.PNG)

![co2 plants 2](https://user-images.githubusercontent.com/4078460/31625122-3c0851a6-b2a5-11e7-9cd4-a92e7d38eda1.PNG)

**Comment by craig-jong** [comment]
These graphs always have had weird behavior like that - not sure if its reflected in the actual gameplay. This is an extremely old version, though, so I'm going to close this.

Please reopen this if it occurs in 7.6+
