### ISSUE TITLE
Power system fluctuations

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2559]
generators powering lights when out of power will flicker the entire power grid

**Comment by MarjieAVolk** [comment]
What do we want a power grid to do when there is not enough power for everything?  Should it not power anything?  Should it randomly pick a subset of things it can power and power those?

**Comment by wiloxe** [comment]
Hmm. One option would be to automatically disable the machines that the generators can't produce enough to and then leave the machines it has enough power for being enabled. Once another generator is detected then it checks if the grid can now support the offline machines to be turned on?
If I made any sense that is.

**Comment by ZebZ** [comment]
Hello! I'm pretty new here and haven't yet gotten to power grids though the case catched my eyes and in my opinion the generators should try give power to everything though maybe instead have something to control the power with? So have some kind of controller block that checks the power input and if it is to low then reject.

As told i'm new and not sure if this exists but else.. Problem solved?

**Comment by ZebZ** [comment]
`--BEGIN DUMP--
Dump Time
10/16/2017 22:00:18

Exception
System.Exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC MoveItems on ToolbarInventory!

Objektreferensen har inte angetts till en instans av ett objekt.


Stack:
   vid Eco.Gameplay.Items.InventoryChangeSet.MoveStacks(ItemStack source, ItemStack destination)
   vid Eco.Gameplay.Items.Inventory.MoveItems(ItemStack sourceStack, ItemStack targetStack, Player player)



Stack:
   vid Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   vid Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   vid Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

   vid Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   vid Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   vid Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   vid Eco.Shared.Networking.NetPort.ProcessBuffer()
   vid Eco.Shared.Networking.NetPort.Update()
   vid Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_0()

--END DUMP--`
