### ISSUE TITLE
the new unlearn BREAKS the game

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2564]
![image](https://user-images.githubusercontent.com/31536813/31709003-f8b646a4-b3f0-11e7-8edc-3ce499409b62.png)

100% of your points back and no limit on how many time you unlearn. its even easier to lonewolf now then before 👎

**Comment by ZebZ** [comment]
"UnlearnRefundRate": 1.0 ?

**Comment by ZebZ** [comment]
difficulty.eco config

**Comment by Arend90** [comment]
that doesnt work

**Comment by SeanAtr0n** [comment]
doh, yeah it doesnt
