### ISSUE TITLE
water glowing

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2565]
![image](https://user-images.githubusercontent.com/774628/31738225-cdb1a6e8-b3fe-11e7-9bea-2f01f8e96455.png)

**Comment by SeanAtr0n** [comment]
Disappeared after I removed a 3rd party lib

**Comment by SeanAtr0n** [comment]
happening again! 🐙

**Comment by metachronism** [comment]
fixed with svn, checked in a change too early
