### ISSUE TITLE
Alocating Causes Lag on the server

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2571]
![image](https://user-images.githubusercontent.com/31536813/31805786-ecc78d8e-b563-11e7-90bf-7d50dfc8de91.png)
these messages plus or min tax making driving a cart or picking up debris or harvest fruit not easier

it takes a liitle bit to long for the server to calculate 

love the system 👍

**Comment by MarjieAVolk** [comment]
Hm I'm less sure how to fix this one; at least for the messages.  Maybe you want allocations to show up in a graph instead of in the chat log?

**Comment by beastyn** [comment]
Should be better with the new law system
