### ISSUE TITLE
Mines now Flooding 6.0.1 (Water Source Blocks at height of sea level appearing in Underground Chambers)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2572]
Water Source Blocks at height of sea level appearing in Underground Chambers

**Comment by Conchipedia** [comment]
We are now we are Producing Co2 (from Blast Furnace and Cement Kiln) and the water levels will rise (that i can understand) But in the mine i have started at level 102 (the sea level for this world is 96) i have been having water Appear and Disappear in the mine roughly every 9 minutes, Now When logging in to day the water has totally flooded the mine, but if i add blocks at level 96 (Stone roof as i have loads) the water below this block Disappears. The Entrance is protected by a door so no water coming in from that way, the Room that is Below Sea level hasn't Flooded and is safe. This will Cause REAL problems for Mining as all Raw Materials are below sea level. there is no other way for water to enter the mine, so cannot understand why it flooded (only possible thing is Eco checking for open spaces below Sea level and deciding to spawn a water Source block at lvl 96, i have another floor below this BUT water did NOT fill that bit.
![snap484](https://user-images.githubusercontent.com/29383891/31819496-c8b5e5a4-b594-11e7-8018-f5263a23ebdb.png)
![snap485](https://user-images.githubusercontent.com/29383891/31819497-c8d2dc72-b594-11e7-95a1-78c001ffc110.png)
![snap486](https://user-images.githubusercontent.com/29383891/31819498-c8eb6472-b594-11e7-9e04-bdc0811e2b8a.png)
![snap487](https://user-images.githubusercontent.com/29383891/31819500-c9043268-b594-11e7-89ef-723a90f7a37f.png)

**Comment by Conchipedia** [comment]
the Water that flooded the ABOVE mine and not this room Stopped at the top of the stairs.
![snap488](https://user-images.githubusercontent.com/29383891/31819596-4a6db0fe-b595-11e7-8410-a1fdb9a08d74.png)

**Comment by knexer** [comment]
I believe this is fixed for *new* worlds, at least, in staging.  Ideally flooded caves would un-flood if sea level simulation were disabled.

**Comment by SeanAtr0n** [comment]
disable it for 6.0.2 there is still a bug though, whenever it's re-enabled it shouldn't do dumb things like this

**Comment by Conchipedia** [comment]
is there a way an Admin can disable this in server? if so What does he have to do to do this?

**Comment by SeanAtr0n** [comment]
in 6.0.2 it'll be disabled automatically... I think right now setting MaxSeaLevelRise to 0 will stop it but not fix existing flooding

**Comment by SeanAtr0n** [comment]
I added DevFloodToolItem to help fix your flooded mine, use it on blocks touching the water in your mine to unflood it quickly. (or get an admin to do that)

**Comment by knexer** [comment]
This is all fixed up, water level rise has been re-added in a way that won't flood mines any more.

**Comment by MarjieAVolk** [comment]
Man, you had a lot of unclosed bugs

**Comment by Conchipedia** [comment]
i think a lot you kept adding to different Milestones so some may have been missed
