### ISSUE TITLE
Factory power demand in alpha 6.0.1

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#2573]
while the factory isnt in use the power demand switches between 0W and 2500W every second or so causing the light on the top left on the table craft list to switch between green and red

![image](https://user-images.githubusercontent.com/29722757/31823835-1e75fa42-b5f9-11e7-8501-987aebae3c62.png)

![image](https://user-images.githubusercontent.com/29722757/31823858-329e1680-b5f9-11e7-9298-cac2dd094d51.png)

**Comment by Arend90** [comment]
Think thats because you dont have enough watts?

**Comment by metachronism** [comment]
I think marjie already fixed this

**Comment by MarjieAVolk** [comment]
Yeah I just fixed this, will be fixed in next release
