### ISSUE TITLE
to many messages

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2574]
https://cdn.discordapp.com/attachments/258375026435162112/366303574025699328/unknown.png
![image](https://user-images.githubusercontent.com/31536813/31835486-002a8ae8-b5d2-11e7-9a4b-73daed38541c.png)

![image](https://user-images.githubusercontent.com/31536813/31832032-bb66595c-b5c5-11e7-88ab-fadf6638d45c.png)
the law of the first picture was  0.1 coins.
the law if the second 1 but was a second try

the 0,1 was devided in to 100? bits and where 3 times a second in chat  causing lag in the whole game for all players

**Comment by MarjieAVolk** [comment]
Yeah I think it's polluting just a tiny bit.  I was already thinking of aggregating all the tiny pollution actions into a single action that happens less frequently, which would also fix this.

**Comment by MarjieAVolk** [comment]
The current staging build should aggregate these into a much smaller number of messages
