### ISSUE TITLE
[6.0.1] UpdateClientException, No player is able to enter server

### ISSUE THREAD

**Issue by Limelill** [StrangeLoopGames/EcoIssues#2576]
Hi! No one is able to enter my server and an exception "UpdateClientException" is generated each time but the server itself do not crash. Have tried to restart it but the error comes back after a while.

Dumpfile: https://www.dropbox.com/s/fqen7301yxz9jbp/EmilS_Dump.zip?dl=0
Save game: https://www.dropbox.com/s/j27ea47951p0l61/EmilS_Game.zip?dl=0

**Comment by metachronism** [comment]
property seems corrupted - you could delete that in your gamesave to work around this issue in the interim

**Comment by metachronism** [comment]
can't reproduce this with 6.0.2 - its likely been already resolved

**Comment by wiloxe** [comment]
If you updated your server from an old version (Can't remember what version) you need to delete your configs and put in fresh ones.
