### ISSUE TITLE
Wood pulp should be burnable as fuel

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2577]

**Comment by metachronism** [comment]
perhaps add a "combustible" attribute to things to make it easier?  then make all fire-based fuel use that?

**Comment by MarjieAVolk** [comment]
thought wood pulp was supposed to be bad

**Comment by peternightingale** [comment]
it would be great to have a better use for all of that wood pulp. Maybe it could be used to make wood pellets or something which could be burned.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#365
