### ISSUE TITLE
Long contract tooltips go off screen

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2578]
![image](https://user-images.githubusercontent.com/6262198/31845599-42e53966-b5b7-11e7-9a0e-5b4b5329a631.png)

**Comment by Nanders** [comment]
Also dont seem to appear in the right place

**Comment by MarjieAVolk** [comment]
Yeah for raw text in tooltips like this, you need to enable line wrapping for that tooltip item.  This can be done by returning a TooltipSection from the tooltip method, like so:

```
        [Tooltip(100)] public TooltipSection HelpTooltip => new TooltipSection(this.HelpText).WithLineWrapping();
        protected abstract string HelpText { get; }
```

**Comment by MarjieAVolk** [comment]
As for the tooltip positioning, the tooltip system just kind of gives up if it can't find a valid position that is entirely on screen, so that should be fixed for free.

**Comment by johnkslg** [comment]
Fixed!
