### ISSUE TITLE
[Staging Alpha 6.0.2 #9b520533] "Put items in container" Contract Function is Broken

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2579]
So.. It appears that the "Put items in container" function for contract board is currently broken with the staging build we have. 
When you select a stockpile it will still show "None" as selected, and when you select what item type you want to put into the stockpile, the icon won't be shown unless you restart the game I heard.
And for some reason, the "Remaining" will only show the current items within the stockpile and the type that is inside it.
I hope I made sense in some way.
![contract](https://user-images.githubusercontent.com/4078460/31845678-b7a3a8fe-b603-11e7-91bc-a235ac920878.PNG)

**Comment by wiloxe** [comment]
Just tested this again on Staging Alpha 6.0.2 #B1558d69. The issue still there.

**Comment by johnkslg** [comment]
Fixed! Thanks a lot for the detailed report.
