### ISSUE TITLE
Server invisible / Offline bug V6.* (Found Fix)

### ISSUE THREAD

**Issue by fizzy6868** [StrangeLoopGames/EcoIssues#2580]
I did post this on forum but seen that StrangeLoop Rather them here so i copied my Forum post here sorry if it is long

Hey Guys here is my story of banging my head on the table for a good 8 Hrs I am a Computer Engineer and host many servers and websites. I know this is not about the issue but you will see why this is relevant for you to know. Anyway I bought the game and downloaded 6.0.1 game loads fine server runs its setup fine but then I notice i cant find my server and if I manually add it low and behold the darn thing says Offline look for anything I may of missed. Then started Looking all over Google and the forums could not see anything. Only every telling people that they need to check Ports and blaming their hardware ( that is why I said i'm and Engineer I knew it was not the ports ). Then thought I will download 6.0.2 as it might have a fix guess what nope. so i started looking at the configs then I tried this below "here is probably all you want to know The Fix"

Fix / Bug:
Setting server to private with a white list locks the hole server out

If you want to have it kinda private the best way i have found it take the server off the List under Network Tab Public Server = False

But make sure you leave the Private Server = False

You will not be able to find the server in the list, but you can give your Friends your IP and it will work wonder

Hope this helps every and the devs read this.

**Comment by metachronism** [comment]
This is a known issue - if the server is whitelisted, and your logged-in account is not on the whitelist, then it automatically hides that server in the server browser UI

**Comment by MarjieAVolk** [comment]
I feel like that's what it should do - although if you ARE whitelisted, it should probably display the server more prominently.

**Comment by fizzy6868** [comment]
Ye it would make sense to hide the server to only the whitelist accounts. Unfortunately my account nor my partners account are unable to see the server until I turned off private server even though we are in the whitelist. If you get what I am trying to say :)

**Comment by metachronism** [comment]
the server browser improvements are tracked in a separate issue
