### ISSUE TITLE
cement kiln not visable in alpha 6.0.2

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#2581]
a small issue with the cement kiln not showing up in alpha 6.0.2 it cant be seen or interacted with
the only thing i can see is a small pipe sticking up in the air

Edit this has been tested on both a fresh install of the server files and on a server with the files just placed over the top of the 6.0.1 files

![image](https://user-images.githubusercontent.com/29722757/31849041-ac5240ee-b687-11e7-9fd4-2db75ae3505e.png)

**Comment by REPOSEECO** [comment]
Same error on a normal Server
![grafik](https://user-images.githubusercontent.com/26040573/31862741-3bf29774-b743-11e7-8e2a-bc8a30fa8728.png)

**Comment by metachronism** [comment]
keegan/nick fixed
