### ISSUE TITLE
Crash on harvesting/planting beans 6.0.2

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#2582]
Crashes when attempting to harvest beans, haven't tried any other crops yet.

**Comment by Quicksilv3r710** [comment]
Generates no dump file, client crash. The whole server lags out when it happens but recovers.

**Comment by metachronism** [comment]
Do you have any strange laws associated with beans?  Not reproducing this with just those steps.

If you have a gamesave file that would help as well
