### ISSUE TITLE
Trees not showing on minimap 6.0.2

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#2584]
After updating to 6.0.2, all the trees on the western hemisphere of the world are not showing on the minimap.  They are still there in game.
![eco1](https://user-images.githubusercontent.com/32985820/31854388-2fc53606-b666-11e7-9c9f-a5fd12a2f361.png)

**Comment by ecoemmeck** [comment]
To add to this a lot of things aren't showing on the mini map.
Any tables and chests that were placed before you connected to the server also dont show on the mini map

**Comment by SeanAtr0n** [comment]
Was due to fallen name change
