### ISSUE TITLE
Chat input history scrolling

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2585]
Hey! As a server admin i do allot of commands and it would be a pretty nice with a feature allowing you to scroll through the latest inputs made by you to easily do the same command over and over again such as in unclaiming.

So basicly, lets say the client stores the 5 latest messages you made. By only opening up the chat you and selecting the input field. You can then press the up key. You will then get the last input and by continuing it keeps scrolling the history.. And to add up on that, being able to press the down key to go the opposite way in history.

**Comment by ecoemmeck** [comment]
Though that feature might be somewhat nice, it's not that difficult to just copy and paste a command that's how I do the /unclaim

**Comment by MarjieAVolk** [comment]
We've been meaning to add this for a long time :P

**Comment by MarjieAVolk** [comment]
Added in 8.0
