### ISSUE TITLE
Placing world objects janky with plants

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2587]
![image](https://user-images.githubusercontent.com/3536496/31867053-5fe563a6-b73d-11e7-897e-aa82c233b426.png)

I'm trying to put a chair down, but the outline only appears when I'm selecting bare ground. It should always appear, even on plants.

**Comment by metachronism** [comment]
Not seeing this issue locally, plants don't highlight when you have the chair selected.

Any specific repro steps?

**Comment by MarjieAVolk** [comment]
I placed a chair in the grass fine, hmm
