### ISSUE TITLE
stone roof :(

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2588]
![image](https://user-images.githubusercontent.com/31536813/31880631-6858ca92-b7e1-11e7-983b-ebb318443394.png)

At Greenleaf they use StoneRoof for EVERYTHING, Floor, walls. roads 

they use it for everything because its the only stone that doesnt use Pitch

"sollution" maybe put some pitch in the recepi or remove it as there is new mortared stone

**Comment by Arend90** [comment]
maybe not remove it 🗡

**Comment by keegan-o** [comment]
Please describe the bug when you report a bug. What is the bug? 

I can say that eventually legacy blocks will be removed.

**Comment by MarjieAVolk** [comment]
I think this will be fixed by the hammer updates, which will remove the Stone Roof block.

**Comment by Arend90** [comment]
dont know if this was a bug
