### ISSUE TITLE
Need to do something about gif layers

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2590]
marmot has over 1GB of layer GIFs

these would only be like 10MB if they were mp4's or something similar - we should look into using FFMPEG or something similar

**Comment by metachronism** [comment]
disagree with the priority - accessing these gifs via the webpage induced massive lag; some servers you have to download 100MB gifs just to display them

**Comment by SeanAtr0n** [comment]
Fixed in 7.5
