### ISSUE TITLE
seed yield tooltip insanity

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2594]
![image](https://user-images.githubusercontent.com/774628/31915239-968bced4-b802-11e7-9dc1-73d55ec072e4.png)

**Comment by MarjieAVolk** [comment]
:O

**Comment by metachronism** [comment]
looks like its adding a benefit per-item or per-user

**Comment by metachronism** [comment]
Crops.Set(discoveredItems.Where(x => x.Type.HasAttribute<YieldAttribute>()));

this is the cause in SelectionInventories.cs
