### ISSUE TITLE
More missing sprites

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2596]
![image](https://user-images.githubusercontent.com/6262198/31916371-4097fb1a-b807-11e7-92d8-97e2a0c50a5c.png)

**Comment by MarjieAVolk** [comment]
that 'plus' icon is not in a sprite asset

**Comment by MarjieAVolk** [comment]
I was thinking I would go fix this, but what even is that item?

**Comment by Nanders** [comment]
Its the control 'item' for the excavator, kinda weird how it works

**Comment by MarjieAVolk** [comment]
Not more button items!

**Comment by MarjieAVolk** [comment]
Fixed in svn
