### ISSUE TITLE
OS X: Wrong version (alpha -> alpha 0.2) 

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#26]
http://ecoforum.strangeloopgames.com/topic/413/os-x-wrong-version-alpha-alpha-0-2

**Comment by metachronism** [comment]
mono I hate you

**Comment by metrotyranno** [comment]
osx, plz

**Comment by noblackthunder** [comment]
windows is the winner ! <3

**Comment by tpowellcio** [comment]
I am seeing this same issue. Any traction on this?

**Comment by metachronism** [comment]
http://ecoforum.strangeloopgames.com:4567/topic/413/os-x-wrong-version-alpha-alpha-0-2

you can patch it with a DLL provided from that link, its fixed in releases going forward otherwise though
