### ISSUE TITLE
Pressing 'e' to collect loose stone rubble with fern nearby quickly resulted in this server Debugger.Break

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#2603]
At least I assume that's what caused it, something with putting the stone into my inventory?
Could have been the fern nearby as well and confusion with pressing 'e' to harvest the fern.

![image](https://user-images.githubusercontent.com/14983165/31962545-b882aad4-b8b2-11e7-9067-2ca74bf62b10.png)
![image](https://user-images.githubusercontent.com/14983165/31962566-c2e36216-b8b2-11e7-8211-166a078f1153.png)

**Comment by MarjieAVolk** [comment]
It might also have been from the previous thing you did with your inventory - had you just moved something else around in your inventory?  Or placed something?

**Comment by keegan-o** [comment]
I think it was the ferns, as the only other thing I had done was place the rubble in a stockpile. Try holding stones and picking ferns?

**Comment by metachronism** [comment]
pretty sure this was because of the broken dump command?  Can't repro :/
