### ISSUE TITLE
trees sometimes get baked at wierd points in their animation, causing gaps

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2604]
Well as the title says, in a new fresh spawn server with no altered files i found this fella:

![tree](https://user-images.githubusercontent.com/32855684/31966265-646fdb4e-b90a-11e7-9d82-174b5d11725e.png)

**Notice:** This also occurred after updating to the _B155???_

**Comment by Nanders** [comment]
This might be a problem with tree batching

**Comment by metachronism** [comment]
only occurs when the first tree sent to the client is beyond the initial view distance and disabled.

something wierd with baking the animation
