### ISSUE TITLE
Completed contract says 'Unassigned' after server restart

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2606]
I created a contract on one account, logged in to another and accepted and completed it.  Then I created a second contract, then restarted the server.  When I logged back in to the first account, the second contract appeared as expected (so I know the contract data got saved), but the first contract now says 'Unassigned' instead of completed.

![image](https://user-images.githubusercontent.com/23460210/31967577-29000792-b8c3-11e7-8804-b2aad272dc17.png)

**Comment by johnkslg** [comment]
Not able to repro this one, tried a few times, not sure how this could happen.

**Comment by johnkslg** [comment]
Propose close no-repro?

**Comment by MarjieAVolk** [comment]
I guess, I can create a new one if I get more information

**Comment by johnkslg** [comment]
ok cool.
