### ISSUE TITLE
(Staging Alpha 6.0.3 #9f1ab189) - Unclaim does not exist

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2607]
Well hello again! Back with another issue..

![unclaim](https://user-images.githubusercontent.com/32855684/31968194-a08364ce-b910-11e7-8bf1-d0e4dc9bed37.png)

**Comment by SeanAtr0n** [comment]
works for me, did you save your admin settings? you have to explicitly do file save while on the Users tab or else they can get lost

**Comment by ZebZ** [comment]
I can do other commands, haven't worked for a while now. Since **B155???** i think

**Comment by MarjieAVolk** [comment]
This seems to be working.  The chat system has been redone since this bug was filed, so I will assume the issue is fixed
