### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#261]
i get over time pretty high performance issue , my ping is around 400 ms ++ 

the game starts with a good fps but over time ( within 30 minutes) i get down to 3 fps ,

 i have a general cpu usage of 28-25% ( balanced over all cores) and 6.5 gb ram usage 

internet speed from me is 80Mb/s

      Time of this report: 3/9/2016, 23:23:02
             Machine name: NBT-TITAN
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release_inmarket.160222-1549)
                 Language: Norwegian Bokmål (Regional Setting: Norwegian Bokmål)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: BIOS Date: 04/19/13 19:28:05 Ver: 40.04
                Processor: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 CPUs), ~3.2GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32712MB RAM
                Page File: 9335MB used, 28241MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10586.0000 64bit Unicode
Display Devices
---------------
          Card name: NVIDIA GeForce GTX 980 Ti
       Manufacturer: NVIDIA
          Chip type: GeForce GTX 980 Ti
           DAC type: Integrated RAMDAC
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_10DE&DEV_17C8&SUBSYS_85461043&REV_A1
     Display Memory: 22404 MB
   Dedicated Memory: 6047 MB
      Shared Memory: 16356 MB
       Current Mode: 1920 x 1080 (32 bit) (60Hz)
       Monitor Name: Generic PnP Monitor
      Monitor Model: ASUS VG278HE
         Monitor Id: ACI27E3
        Native Mode: 1920 x 1080(p) (60.000Hz)
        Output Type: DVI
        Driver Name: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
Driver File Version: 10.18.0013.6447 (English)
     Driver Version: 10.18.13.6447
        DDI Version: 12
     Feature Levels: 12.1,12.0,11.1,11.0,10.1,10.0,9.3,9.2,9.1
       Driver Model: WDDM 2.0
Graphics Preemption: DMA
 Compute Preemption: DMA
           Miracast: Not Supported
Hybrid Graphics GPU: Not Supported
     Power P-states: Not Supported
  Driver Attributes: Final Retail
   Driver Date/Size: 03.03.2016 00.00.00, 17368232 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: 
  Device Identifier: {D7B71E3E-5488-11CF-DC6A-4BA51CC2C735}
          Vendor ID: 0x10DE
          Device ID: 0x17C8
          SubSys ID: 0x85461043
        Revision ID: 0x00A1
 Driver Strong Name: oem0.inf:0f066de3672d1ed2:Section045:10.18.13.6447:pci\ven_10de&dev_17c8
     Rank Of Driver: 00D12001
        Video Accel:

**Comment by metachronism** [comment]
http://ecoforum.strangeloopgames.com/topic/598/framerate-game-using-100-cpu

i also note that i have a 4 gen Core i/ 4930 and a 980 ti and i get pretty low fps ( starts at 20) goes down to 5 and less after a wile.

this is way to low for a high end gaming rigg.
