### ISSUE TITLE
Point of interest markers on minimap not positioned correctly

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2611]
They visibly move when you zoom in and out.  They seem to be more accurate when you are more zoomed in.

**Comment by SeanAtr0n** [comment]
it was only 'POI' icons? not other icons?

**Comment by SeanAtr0n** [comment]
also was the thing underground?

**Comment by MarjieAVolk** [comment]
Yeah I think it's just those - they move with respect to my player icon for example.

And no I don't think any of these were underground.  Some of them might have been inside.  This happened even when I was standing right next to the position - my player icon would look pretty accurate and the point of interest thing would be far away from it, then slowly approach it as I zoomed in.

**Comment by SeanAtr0n** [comment]
fixed
