### ISSUE TITLE
Contract UI: Inventory contents (and many other strings) need to wrap

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2612]
![image](https://user-images.githubusercontent.com/23460210/31972414-7b9cb650-b8d5-11e7-808d-eff5dc98a3cc.png)

**Comment by MarjieAVolk** [comment]
If you like, I would do a layout pass on all the new contract UI stuff.  It needs a lot of help with margins and line wrapping and text overflow just in general.

**Comment by johnkslg** [comment]
That would be awesome!  This info box would be nice to integrate into the contract too.  Want to take this bug then?
