### ISSUE TITLE
Beans and beets clip at much too small a view distance

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2614]
I've filed a few issues similar to this, which have been marked as fixed, but like this category of problems keeps happening; personally I find it very confusing and annoying while playing.  Can we fix this at a systemic level?

![image](https://user-images.githubusercontent.com/23460210/31972593-46926b7a-b8d6-11e7-963e-1eacd29d34c4.png)

**Comment by metachronism** [comment]
this is intended from a performance standpoint, you can tweak this with higher foliage detail in the slider

**Comment by MarjieAVolk** [comment]
Okay I don't really understand what is going on here; I get that it's for performance, but the way that is works is strange and the settings are confusing Like the corn being way different from the beets feels really weird, imo it should just be the same for all plants.  Also at the very least, the name of the setting is weird - I would expect 'foliage quality' to change how detailed the plants are, not their view distance.  Especially since there is a separate setting for view distance.

**Comment by metachronism** [comment]
foliage quality is how detailed the plants are, it changes the LOD bias for everything in the game, which affects which detail level is used for all the plants.

**Comment by metachronism** [comment]
tweaked lods
