### ISSUE TITLE
Reduce intensity of property view mode

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2619]
Should be able to see some detail in the geometry.  Fade it in partially instead of fully flat-shading it?
Also, should remove the max-distance: let it display property all the way out the horizon

![image](https://user-images.githubusercontent.com/3536496/31973828-e0d55642-b8dc-11e7-8dd9-b61777de9d6a.png)

**Comment by johnkslg** [comment]
I would remove the pulsing as well

**Comment by MarjieAVolk** [comment]
What if it were not completely covered in color; like if it were construction-warning style diagonal stripes of color.  I think that would make it easier to tell what the actual property color is when it's semi-transparent, so you can compare to what's underneath it.  Same could be true on the minimap.
