### ISSUE TITLE
player can put his game in a state where they cant progress at all

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#262]
Case: 

i joined a server, i clicked random skills i wanted to learn , mining, logging and other useless skills i build a house and put a workbench in it and a campfire, and i entered a state where i can not progress,

i could only harvest huckleberry , could not campfire because i did not research hammer and could not advance my skills without the right food skills basically putting me in to a state where i can not progress .

Temporary fix would be a on scree tutorial first time you join a new server with some direction you should learn and how the game works in its basics

**Comment by craig-jong** [comment]
This should be fixed in the above commit.
