### ISSUE TITLE
Minimap was disappearing on zoom in

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2620]

**Comment by SeanAtr0n** [comment]
who what when where worldsize?

**Comment by MarjieAVolk** [comment]
I assume this was the weird thing that was on Marmot; when you zoom in far enough, the ground disappears

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/31974824-54fef3a2-b8e2-11e7-8d33-bc8bc67c2067.png)
Here's a case, when youre zoomed in next to something tall, it will clip.
Not sure if that's the same thing happening on Marjie's.

**Comment by SeanAtr0n** [comment]
oh, yeah i'll fix that eventually... not for 6.0.3

**Comment by MarjieAVolk** [comment]
Nope not the thing I was seeing lol

**Comment by johnkslg** [comment]
Marjie can you file a separate bug and repro for what you were seeing?  Able to repro it? Sean pushed this to beta

**Comment by MarjieAVolk** [comment]
I didn't file a bug because I assumed it was related to the issue with the whole minimap being grey and weird, which I thought was already being handled

**Comment by SeanAtr0n** [comment]
Added https://github.com/StrangeLoopGames/EcoIssues/issues/2621 for the glitch thing... i suspect it's because Eric cheated
