### ISSUE TITLE
Most building builders should ignore stairs as a type

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2624]
![image](https://user-images.githubusercontent.com/3150561/32013697-c260f1d2-b970-11e7-8247-445319cc283d.png)

building stairs inside a building does annoying stuff like this

**Comment by johnkslg** [comment]
Hammer time?

**Comment by keegan-o** [comment]
This will go in when we finally update lots of builders-- right now it is another change that would affect things a little un-predicatably for lots of servers that have been building lots of stuff, so will put it in with the hammer or when we get the new logs in.

**Comment by keegan-o** [comment]
trying out one version of this for the patch, though... we'll see if it's as simple as having the wall builders just connects to the 'building' category.
