### ISSUE TITLE
colliders on tree branches are broken

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2625]
Work with Nick and the tree wizard to see them, but they are quite broken and result in branches 'popping' off the tree when you cut them

**Comment by Nanders** [comment]
This shouldn't be tree wizard stuff, Cedar and Birch didn't get run through the wizard.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/2868?
