### ISSUE TITLE
For front page graphs - toggling from lines to bars causes graph to break sometimes

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2627]
In Populations premade graph, switch from bar to line, then back to bar.  Usually at this point the bars are not displayed and never load.  Switching back and forth does not seem to fix it.

**Comment by MarjieAVolk** [comment]
It would also be nice if the graphs had a loading icon while loading - seeing them initialize is confusing

**Comment by syuzan-yeranosyan** [comment]
It's done

**Comment by MarjieAVolk** [comment]
If it's fixed, you can close the issue.  I don't know what your guys' workflow is - I didn't see any PRs.  Is it fixed on master, or on a branch somewhere?

**Comment by syuzan-yeranosyan** [comment]
It's fixed on 'web-teacherdashboard' branch.
