### ISSUE TITLE
Amanita and Crimini Mushrooms Spores trying to plant Causes Exception 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2629]
I just harvested some Crimini Mushroom's and got some Crimini Mushroom Spores, I then Attempted to Plant these and Got this:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.SeedItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

i then relogged and tried again and 2nd time i tried to see if if it could be Duplicated the server seemed to actually crash as well (not sure if this was me doing this or just bad luck)

**Comment by Conchipedia** [comment]
![snap086](https://user-images.githubusercontent.com/29383891/32020266-86a0623e-b9c7-11e7-9eb0-441e19edff20.png)

Trying to get this law in Force so Players dont even get the Crimini Mushroom Spore when harvesting (i think this should work)

**Comment by Conchipedia** [comment]
![snap086](https://user-images.githubusercontent.com/29383891/32020266-86a0623e-b9c7-11e7-9eb0-441e19edff20.png)

Trying to get this law in Force so Players dont even get the Crimini Mushroom Spore when harvesting (i think this should work)

**Comment by Conchipedia** [comment]
Same happens with Amanita mushroom spores:
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Items.SeedItem.OnActRight(InteractionContext context)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by MarjieAVolk** [comment]
@craig-jong Looks like this is because these plants don't have a plant group.

**Comment by Conchipedia** [comment]
will the work around laws i put in place actually work? i mean if we stop people gathering mushrooms we won't have random people planting and crashing

**Comment by MarjieAVolk** [comment]
Sure, unless they already have them in their inventory
