### ISSUE TITLE
Web map sliders are hard to work with

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2631]
Trying to have small ranges is very difficult w/ the current slider setup.
![image](https://user-images.githubusercontent.com/774628/32023792-37d1f646-b98f-11e7-9f05-c34ef710fe6e.png)
The left slider is dragged past the right slider in that picture.

The slider positions are offset so you can drag the left one past the right one, we definitely should get rid of that behavior.

We need to be able to set small time ranges in an intuitive way. Ideally if the markers touch the time range should be 0.

**Comment by syuzan-yeranosyan** [comment]
It's done
