### ISSUE TITLE
[Art] Identical Icons of Blocks in Crafting table and Stockpiles causes Confusion #6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2632]
we now have New blocks in 6.0.3 called Mortared Stone Roof and Mortared Stone wall, nice that we have them BUT if anyone is like me and tries to keep stockpiles full all the time, seeing all these identical icons is getting really confusing (you have to hover mouse over each one to make sure it is what you think it is)

![duplicate icons](https://user-images.githubusercontent.com/29383891/32031917-177412c2-b9fc-11e7-9417-525519110121.png)

Please can we have NEW and different icons

**Comment by Conchipedia** [comment]
<img width="564" alt="snap081" src="https://user-images.githubusercontent.com/29383891/32032040-ed5709c6-b9fc-11e7-806e-bb84603c75fb.png">

this is an Example Stockpile view (without me naming the stockpiles there is no way i can tell how many i will require to make to fill up the stockpile without hovering over the icons to make sure the right ones are in the right stockpile) other items are fine as u can see you have mixed Contents

**Comment by johnkslg** [comment]
Hammer will help here

**Comment by keegan-o** [comment]
Anything that is a unique item will eventually get a unique icon, but it's true we don't want to go and author a ton of art that will then be obsolete with the hammer-- so we should wait on making icons for these I think.

**Comment by Conchipedia** [comment]
i understand to need to save you work making a lot of art, can text be added as a temporary measure?
not sure what is meant by "Hammer will help here","Obsolete with the hammer"

**Comment by MarjieAVolk** [comment]
Yeah it's a feature we're about to start working on, haven't announced it yet I guess.  Basically you will be able to craft just 'mortared stone' for example, and using a new feature on the hammer you can select whether it looks like a wall/floor/roof when you place it.  But it will be the same item in your inventory.

**Comment by Conchipedia** [comment]
that sounds an interesting idea, so the 10 carried blocks can be turned into 10 different looking blocks without the need of  keep returning to a stockpile and getting a block you  need?

**Comment by MarjieAVolk** [comment]
Exactly, that's the idea.  Hopefully it will be so in the not too distant future.

**Comment by Conchipedia** [comment]
i was just thinking on doing
![snap568 edited](https://user-images.githubusercontent.com/29383891/32755404-fdd3d3ae-c8cc-11e7-8f15-4719a60c88e1.png)
for now to save on artwork :)

**Comment by MarjieAVolk** [comment]
Hammer is in now, so a lot of these issues are resolved
