### ISSUE TITLE
Current Events api is passing more events when the time selection is narrower

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#2633]
If I set the time selection to 0 - 1.15 days I see one event:
https://gyazo.com/c419d0c4ef394879e9a2790cda6e15f1

If I set the time selection to .4 - 1.15 days I see two events:
https://gyazo.com/1d20b86986e2d99e708e9d01234d4ecc

If more time is selected, then I would think more events should display.

**Comment by MarjieAVolk** [comment]
Guess this is do to how the population change event is calculated... which might be weird right now.
