### ISSUE TITLE
Claiming land sometimes causes all clients to disconnect and/or crashes server.

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#2634]

**Comment by Quicksilv3r710** [comment]
![ecodeed](https://user-images.githubusercontent.com/32985820/32062273-06cf9734-ba42-11e7-8e38-f7a9a58e681e.png)

**Comment by Quicksilv3r710** [comment]
A player on my server just sent me this, not sure if its related to his deed being bugged but it crashes when he tries to claim land.

**Comment by Quicksilv3r710** [comment]
As i was typing this, he made a new deed and tried claiming with the new one and it worked fine.  Seems like the deed was just bugged. lool

**Comment by wiloxe** [comment]
Duplicate of #2599 and could be the same as #2537.

**Comment by MarjieAVolk** [comment]
Yep, duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2599 as wiloxe said.  We discovered the problem is a bad deed, but not sure what makes deeds go bad yet
