### ISSUE TITLE
Top of some Blocks are transparent (Position 791,69,377)

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2636]
Any idea what the admin can do ?
Server = (GER) Gamerpard.com

![grafik](https://user-images.githubusercontent.com/26040573/32069369-42a5392a-ba89-11e7-9497-0e6e320e8d9f.png)
IF you pick up the bock the transparent move

**Comment by REPOSEECO** [comment]
Is saw in Discord that we are not allone :-(
FraMzi - gestern um 18:43 Uhr
Hello, I have a big problem, I have an invisible block that prevents me from asking blocks ...
ClayC - gestern um 19:02 Uhr
@FraMzi  what version are you on?(bearbeitet)
MW - gestern um 19:17 Uhr
I kinda have the same problem, 6.0.3 has to do with Mortar Stone flat roof. I thought removing the file would do it, but nope. Basically it like the old Steel bug, makes parts of the world go poof. I can not get close to where the item is to delete it, nor can I even see it/target it.

**Comment by metachronism** [comment]
this is caused by an incomplete server install - make sure to install the server to a fresh folder, otherwise you could have leftover files from the previous version causing issues like this
