### ISSUE TITLE
Ability to remove another users orders from public craft table after some time.

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2638]
Hello again! Me and my friends have realized a pretty annoying _feature/missing feature_. The owner of a workstation such as Workbench or Carpentry Table can quickly fill the table with materials by right clicking it. A none owner with permission to the table "can" fill it but must enter the table and drag it in manually..

Would be pretty handy for all the users with permission, to be able to quickly add items to the projects :D

**Comment by MarjieAVolk** [comment]
What is supposed to happen is that you can right click to add to any project that belongs to you - But I think I also saw some problems with right click to add, so it's likely there is a bug

**Comment by ZebZ** [comment]
Then maybe add some way of letting others have access for you'r projects in a workstation of you'r choice? =)

**Comment by WeaselDog** [comment]
From #7209
>Found an issue where I could not add the missing resources to any table after the job has started working if I am not the owner of it. In this case, I attempted to make a mint using an Unowned Anvil. I had the bricks and lumber handy, but because I couldn't hold both at once I had to start with one. Afterwards, however, I could not proceed to add it. No error message, it just doesn't accept it.
>
>EDIT: Logging in to play today I found I could again add resources to projects on my own property by dragging them into the project window.

**Comment by WeaselDog** [comment]
From https://github.com/StrangeLoopGames/EcoIssues/issues/4631

>I would add that if a table is shared, items [can't] be removed when they are completed - it seems currently the game works on the basis that it won't allow you to collect any of your project you have made if the previous project created by another player hasn't collected it.

You can't collect projects that someone else creates on a shared or public crafting table, leaving that crafting spot occupied.

**Comment by SlayksWood** [comment]
#14708
> Table owner should have ability to remove another users orders. 
> Otherwise, e.g. if you provide paid workbench, anyone can block it.
> ![изображение](https://user-images.githubusercontent.com/4980243/74312436-c0907000-4d82-11ea-8886-7c9726f32bb4.png)
> ![изображение](https://user-images.githubusercontent.com/4980243/74312452-c7b77e00-4d82-11ea-835d-b92726d0416c.png)
> 
> Just made 5 short orders and not grab it.
> So, only admin with devtool can remove this bench.
> 
> As i think, eco need configurable timer (in server options) 24h (real) in default.
> This timer start after order has been complited, after timer expired, table owner can gather completed product.
> If table has no owner (unowned) anyone can grab product after timer expired.
