### ISSUE TITLE
(Staging Alpha 6.0.3 #79df8a11) - Stockpile icon not showing in inventory

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2640]
Once again another bug ^^

After picking up a already placed stockpile the stockpile icon will not show in the inventory. I have experienced this since 6.0.1 but never really gotten a good look at whats going on.

I am not sure if this only happens when picking one up but that's what happened now.

![stockpile](https://user-images.githubusercontent.com/32855684/32077520-faa731a8-baa3-11e7-987d-01303e78d5cd.png)

**Note:** _As you can see i am currently targeting spot 9, that is told empty but should not be._

**Comment by ZebZ** [comment]
Another icon not showing up. (currently carrying dirt)

![dirt not showing](https://user-images.githubusercontent.com/32855684/32078025-a9734f4a-baa5-11e7-9249-c301eb7ba624.png)

**Comment by metachronism** [comment]
need a reliable repro, could not reproduce this
