### ISSUE TITLE
(Staging Alpha 6.0.3 #79df8a11) - Certain linked inventorys does not show

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2641]
Another one.

I experienced this earlier when trying to browse linked inventorys from my cart where no linked inventorys was shown even though i was standing next too atleast 4 stockpiles.

Like shown in this picture i have a stockpile outside of my house.

![linkedinv2](https://user-images.githubusercontent.com/32855684/32078839-b060d914-baa8-11e7-8154-f6094844eec8.png)

And like in this one i am browsing linked storages from my house that is shown to the right in the last image. As you can see there is no stockpile shown with any wood and dirt even though it is literally touching the walls to the house. The table i am browsing from is even at the same wall that is shown on image one.

![linkedinv](https://user-images.githubusercontent.com/32855684/32078909-f9a5b64e-baa8-11e7-8ff0-d8dc6b7e08e7.png)

**Comment by metachronism** [comment]
cant repro this - if you have a gamesave that recreates this issue can you link it here and reopen?
