### ISSUE TITLE
[6.0.3 Stable] Uncommon Crash When Right-Clicking Stockpile

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2642]
So this appears to happen few times on my server, but since I don't know what caused it I haven't really bothered reporting it but now while playing alone it happen again.
So it turns out that sometimes when you right-click on stockpile to drop off items you can cause the server to crash, I don't know if this is because of something.

[Crash 10270652.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1421827/Crash.10270652.txt)

**Comment by Quicksilv3r710** [comment]
This happened on my server also multiple times. Here is the dump file from my instance.
[Crash 10280639.ecodmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1424690/Crash.10280639.ecodmp.txt)
