### ISSUE TITLE
(Staging Alpha 6.1.0 #4e325355) Claiming land

### ISSUE THREAD

**Issue by Toooxic** [StrangeLoopGames/EcoIssues#2643]
When i claim land the server asigns the land to another player.

**Comment by MarjieAVolk** [comment]
Do you have a deed belonging to someone else in your inventory?

**Comment by Toooxic** [comment]
No i don't have a deed that belong to another player.

**Comment by wiloxe** [comment]
Could this be related to #4626?

**Comment by MarjieAVolk** [comment]
Could you provide your server save file?  And/or some screenshots of your deed(s), and the status panel showing the owner of the land after you've claimed it?  I need some more context.

**Comment by Toooxic** [comment]
The day after this happened i joined the server and it was my land so i cant really provide any more information.

**Comment by MarjieAVolk** [comment]
So the issue isn't still happening?

**Comment by Toooxic** [comment]
It isnt happening anymore.

**Comment by MarjieAVolk** [comment]
Okay well without more information there's not much I can do, so closing for now; feel free to reopen if you have more problems
