### ISSUE TITLE
(6.1.0 #4e325355) - Invisible block

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2644]
They say there is a block here. When they digg it they agree there is no block there. When we then try to place a block there, it won't place it. When another user comes to try the impossible he still claims we have gone insane and realizes fast that when digging the block he then cant place something there anymore.

![deasfgfh](https://user-images.githubusercontent.com/32855684/32128871-242e25f2-bb82-11e7-84d7-56b787534f3a.png)

**Comment by MarjieAVolk** [comment]
Just this one block is messed up?  The rest of the server is working?

**Comment by ZebZ** [comment]
What we know about.

**Comment by ZebZ** [comment]
If it makes things easier i can send the ip for it. I sure makes it easier for me to not open up ftp consoles and such xP (it won't show as public even if i have made it so)

**Comment by MarjieAVolk** [comment]
You're having that bug where the server won't show up in the list too?

**Comment by MarjieAVolk** [comment]
A save file would probably be easier

**Comment by ZebZ** [comment]
yes, opened up a thread for it.. Apperantly i guess it already was a thread for it.

**Comment by ZebZ** [comment]
RAR files is not supported....

**Comment by ZebZ** [comment]
We think it could be the spawn point but have no one to test it with.

**Comment by wiloxe** [comment]
I can say that this also happens on our server but it's more client side thats the problem. Everything you dig wont be updated on your screen and walking away from the area where this issue appeared will result falling thru the wold due to it not loading anymore. The solution is to reconnect but in 6.0.2 the game client would crash when you disconnected but that appears to be fixed in 6.0.3

**Comment by ZebZ** [comment]
Reconnecting does not help. Restarting tmdoes nor help. On any sides, we have not had any problems by falling oyt of the world.

**Comment by wiloxe** [comment]
Thats very odd. Now I'm intrested in what it could be. Hmm..?

**Comment by ZebZ** [comment]
The problem is still there and i can still not upload any .rar files to share a world file.

**Comment by MarjieAVolk** [comment]
Yeah, you will have to use a file hosting service like Dropbox or Google drive in order to share it here

**Comment by wiloxe** [comment]
If you compress the file in .zip instead of .rar you will be able to upload the file.

**Comment by ZebZ** [comment]
http://thegoldyiron.se/downloads/Storage.rar

Works as well (the file is currently uploading but will soon exist)

**Comment by ZebZ** [comment]
The file is now uploaded.

**Comment by johnkslg** [comment]
Probably the worldblock/plantblock desync, eric?

**Comment by metachronism** [comment]
yes, fixed
