### ISSUE TITLE
(6.1.0 #4e325355) - Server not showing up as public.

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2645]
Our server was public a while back until we started updating it. As we have not changed much in the configs we just overwrite them and update the settings again. So we know that the public setting is enabled. Even though so is the case it won't show as public..

**Comment by metachronism** [comment]
your server also has to be accessible via http request (web server must not fail to start - check startup errors)

make sure you have all the ports open and forwarded if need be as well

**Comment by ZebZ** [comment]
3000-3001 is open, http access is possible. We use ir pretty often

**Comment by ZebZ** [comment]
Basicly. Yes the webclient is open

**Comment by ZebZ** [comment]
The server was earlier hosted on my private PC. we updated to a new version and it stopped showing. shortly after this we moved it to our official server for 24/7 uptime. The only thing that changed then was the IP and that we changed to a port range instead of seperate ports.

We user the port range 3000-3001 that i found on google :)

**Comment by metachronism** [comment]
can't really repro this, will need more info to get a fix
