### ISSUE TITLE
Unable to place Research table

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2647]
Built a house 20X5X3 has wooden floor try to place research table and get message "cant place here BLOCKED. So i removed all other chests and tables house is totally EMPTY Still get same message

**Comment by Conchipedia** [comment]
Research table is 3 blocks high, so not sure if your 20x5x3 is the walls and roof

**Comment by cuda70** [comment]
Ohhhhh ok time to redesign the house THANKS

**Comment by cuda70** [comment]
Made house one layer higher and that did the trick the table installed just fine Thanks again
