### ISSUE TITLE
Tree sunk to bottom of the water in #6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2648]
Do tree NOT float anymore? when i chopped a tree down it fell into the water standing upright, then i chopped at the tree in the water now ALL pieces are at the bottom
![snap525](https://user-images.githubusercontent.com/29383891/32138480-5be7a7a8-bc2b-11e7-8f44-ba3acba373dd.png)

**Comment by Conchipedia** [comment]
![snap526](https://user-images.githubusercontent.com/29383891/32138618-a9616a9e-bc2d-11e7-9fde-afea98b06c31.png)
added a new one actually in daylight this time

**Comment by metachronism** [comment]
buoyancy was removed as an optimization for 6.0.3, we can investigate adding it back once its optimized a bit
