### ISSUE TITLE
[0.6.0.3 stable] Oil item not recognized as fuel

### ISSUE THREAD

**Issue by Thengen** [StrangeLoopGames/EcoIssues#2650]
Oil item is not recognized as fuel in candle-like objects that are supposed to accept it (tallow wall lamps, ceiling candles, etc.) In-game notification says: 'Inventory only accepts fuel'.

**Comment by wiloxe** [comment]
This issue can be temporarily solved by adding own fuel value in Oil.cs file that can be found inside mods folder. Go to Tallow.cs and copy the fuel live and paste in the Oil.cs then tweak the values you want.
