### ISSUE TITLE
[6.0.3 Stable] Unable to buy/sell Fiberglass in shops. Item not there

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2653]
So when attempting to add Fiberglass to buy or sell option you won't be able to find it. By manual search or typing it in you won't be able to find it. (Thanks Dargendarg for finding this)

![fiberglass](https://user-images.githubusercontent.com/4078460/32184960-2ff428a0-bd9e-11e7-8539-e05fdea97b59.PNG)

**Comment by MarjieAVolk** [comment]
This is working fine for me.  We do hide items from this view that have not been 'discovered' yet - meaning that if nobody on the server has the skills required to craft an item, it will be hidden.  Is that what's happening here?

**Comment by wiloxe** [comment]
It looks like that. We just researched electronics and now we can see it. But there are other things that we can select that we haven't discovered yet so it's kinda confusing.
You should maybe make an option to see "Undiscovered" and "Discovered" items.

**Comment by MarjieAVolk** [comment]
Okay, thanks for the feedback

**Comment by MarjieAVolk** [comment]
Okay we're going to expand the definition of 'discovered' a bit, so that items will show up in this list if they are required for any researched recipes (as well as the current behavior of showing up if their recipe has been researched).  Hope that's less confusing.

**Comment by wiloxe** [comment]
I guess that could work!
