### ISSUE TITLE
Sometimes Gov Activity and User Activity don't display on page load

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2655]
Sometimes when I refresh the Citizen Activity page, Government Activity will look like this:
![image](https://user-images.githubusercontent.com/23460210/32188010-d2d81170-bd63-11e7-8929-e0522dae2e9a.png)

Moving the slider and moving it back makes it display the actual data:
![image](https://user-images.githubusercontent.com/23460210/32188035-eaca647c-bd63-11e7-9d5e-6fdf3f30f8d6.png)

Same is true for User Activity

**Comment by rainfarmer** [comment]
Gov activity and user activity are being removed for dashboard v2. 
Being replaced by student activity page and current events articles.

The same bug for current events was fixed.
