### ISSUE TITLE
(6.1.0 #4e325355) - Swedish letters not supported in chat

### ISSUE THREAD

**Issue by ZebZ** [StrangeLoopGames/EcoIssues#2656]
Hello! Just realized that swedish letters is not supported in the chat. This is pretty annoying as most of my users are swedish (not realized it as we mostly use teamspeak)..

The letters that are not supported is: **å ä ö**

**Comment by MarjieAVolk** [comment]
O.o Hm, this might be hard to fix, as we're using third party software for our text & text boxes.

I assume you mean you have a method of entering those characters, but they aren't displayed in the text box and/or the chat log correctly?

**Comment by wiloxe** [comment]
When attempting to write these letters you get the following orders: **å ä ö**
![aao](https://user-images.githubusercontent.com/4078460/32191567-d5458700-bdb1-11e7-9e9a-0f715c3221bc.PNG)
And when writing with capitals things can become even more confusing
![capital aao](https://user-images.githubusercontent.com/4078460/32191634-1256ed64-bdb2-11e7-8a99-e693283d4904.PNG)
If you open any text document and press ¨ then o you will get ö. I tried doing this in the game as well but it didn't work.

**Comment by ZebZ** [comment]
yeah i know how to the letters manualy but it's pretty annoying as we got the letters on our keyboards...

**Comment by REPOSEECO** [comment]
The Same for German special Chars Ö Ü Ä ß and we use them -> 1,6 %  letter frequency

**Comment by MarjieAVolk** [comment]
Hm yeah here in the US we don't even have umlaut on our keyboards so, I can't personally test it >>

So just to double check, you enter in the letter and these strange symbols appear; if you actually send them in chat, does it display the same way in the log?

**Comment by MarjieAVolk** [comment]
Okay I realized I can paste the characters in.  So I see the behavior you're talking about.  I wonder if this problem is because of our font...

**Comment by ZebZ** [comment]
![adsgf](https://user-images.githubusercontent.com/32855684/32195365-62f29b5a-bdbd-11e7-82bd-f8a7a7d0f7ca.png)

**Comment by ZebZ** [comment]
or maybe that it does not recognize the keycode? hmm

**Comment by MarjieAVolk** [comment]
We checked and it is not the font.

**Comment by Nanders** [comment]
Bumping this priority because of our popularity in Europe.

**Comment by MarjieAVolk** [comment]
Oh yeah, and also because I think we know how to do it now :P

**Comment by MarjieAVolk** [comment]
@MilenkoTunjic I believe we have to add these special characters into our font asset somehow, I was told you can do that?

**Comment by Nanders** [comment]
I added support for Extended ASCII today. Should sufficiently cover English, German, French, Swedish.
