### ISSUE TITLE
Game is still too dark in shadow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2659]

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32199140-875e2e94-bd88-11e7-8a54-d1ed8c761f37.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32199177-a9fed2dc-bd88-11e7-8145-39548b09d905.png)
At night its especially bad, spawning into the game and this is the first experience is too hard

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32299166-d1fc4b86-bf11-11e7-91b8-8b17a5c9719a.png)

**Comment by johnkslg** [comment]
Example that includes latest changes to lighting
![image](https://user-images.githubusercontent.com/3536496/32299174-da5572d0-bf11-11e7-9bd2-c8bad24df0d6.png)

**Comment by johnkslg** [comment]
Reopening, still too dark in master.  Here's current master, after typing /day.

I realize there is a subjective quality to this, that you don't mind the level of darkness in this, but I find it too dark and not contributing to the experience of the game in a positive way.  Let's involve Milenko to get this tuned up.

![image](https://user-images.githubusercontent.com/3536496/32568165-53aa998e-c472-11e7-8b71-f0018274cc70.png)

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32575971-5de8ed02-c48a-11e7-86c4-9f7438bdd573.png)
We wont be able to rely on the eye adjuster to fix things, shadows will need to be reduced in contrast, or light from the sky more prominent.  In this scene it goes from a visible house when youre looking at to very dark when you have the light area on the screen.

**Comment by metachronism** [comment]
yeah I think you are in the wrong here.  you can either have contrast in the scenes with light/dark areas or you can have washed out lighting everywhere.

I would prefer the contrasted lighting which is what we have now.  eye adaptation is used in every game there is, so us 'relying' on a bad thing

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32683720-4d760686-c632-11e7-8882-9191454aaf5b.png)
Imagine starting a game of Eco and you login to this. I would think the game is broken.

**Comment by MilenkoTunjic** [comment]
These screenshots look pretty dark.
Let me take a look and i will give you my thoughts shortly.

**Comment by MilenkoTunjic** [comment]
Eh, I played around, and I get where both of you are coming from.
I will play a bit more, and get some notes,

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/32972169-b2759506-cba5-11e7-9305-391fc028b578.png)
Heres a pretty stark difference
daylight hours, looking at a wall. Left is with lighting, right is without.

**Comment by metachronism** [comment]
you cant take SS without eye adaptation on

**Comment by johnkslg** [comment]
This is looking better, but would still like to tweak. Removing high priority.

**Comment by johnkslg** [comment]
Game seems pretty decent lately, closing.
