### ISSUE TITLE
Skill specialization take 2: Roles

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2665]
Taylor's doc here:
https://docs.google.com/document/d/1OvfaS8krc-vaNgJHKR1_YraRFfIrIyaKqIgFpwA8V98/edit

**Comment by Arend90** [comment]
I love the idea that a capenter cannot be a cementblock maker 2. but it can be a bit painfull 2 to play when you have to wait 3 days on your cement because the cement person goes a weekend away for example.

**Comment by Dr-Hardware** [comment]
-	what I’d like to see is remove the ability to see the whole representation of skills as it stands, leave skill point earning the way it is, but integrate the "learn what you use system" to give you 3 options for your next "assignment of points" based on your recent usage of existing skills. That way you have to work at your chosen craft to advance in it, without impacting the Dev's line of - you don’t have to play 15 hrs a day to earn skills

**Comment by johnkslg** [comment]
Thats a cool idea.

**Comment by johnkslg** [comment]
I put together a design that works from Taylor's document:
https://docs.google.com/document/d/1WVxhMW022SSOVkQP4u34F5_QBfaFFLIqY7X3HwsMhwk/edit#

**Comment by MarjieAVolk** [comment]
This has been addressed
