### ISSUE TITLE
Halting server after placing WorldObject can leave occupancy but no worldobject

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2668]
This is because they are saved in different databases. PlantSim handles this by checking every plant and only adding those that have the matching world blocks, should do same for worldobjects.

**Comment by metachronism** [comment]
not really a feasible solution; cant check every block in the world for a matching world object, for example

**Comment by metachronism** [comment]
(the plant solution doesn't really work either, cause you have the same problem in reverse)

**Comment by metachronism** [comment]
fixed
