### ISSUE TITLE
Deeds tweaking out their scroll bars

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2670]
Scrollbars were appearing and disappearing continuously while this was open.
![image](https://user-images.githubusercontent.com/3536496/32250967-05cbe35c-be4c-11e7-85f9-68798cb97e94.png)

**Comment by MarjieAVolk** [comment]
Looks like the 'auto hide' option isn't working >> but 'auto hide and expand viewport' is fine so.
