### ISSUE TITLE
Contracts disappear from their contract boards on server reload

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2671]
Only happens once in a while.  This was with unposted contracts; they still appeared for me in the panel on the right, but disappeared from the board.

**Comment by MarjieAVolk** [comment]
(1) create contract
(2) stop and restart server, repeat as necessary

Just about every save I've got has some of these on it now.  1 minute

**Comment by MarjieAVolk** [comment]
https://drive.google.com/open?id=0B4kJEcFjfDpjN0JBbkxPNTU0dkk

**Comment by johnkslg** [comment]
Thanks!

**Comment by johnkslg** [comment]
Contract board was tracking GUIDs which could get out of sync with the economy manager if the saves didn't line up. Changed contract board to not track guids, and rely only on economy manager, so no sync needed.
Also made contracts not show up until they're 'posted', so unposted contracts will appear only in the clients personal contract bar.
