### ISSUE TITLE
Fuel Supplies Authorisation

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2676]
•	Fix Auth Issues with "power" supplies - currently you can raid anyone’s base by driving up with a cart, linking with their furnaces and campfires and making off with a load of coal. Even through walls and doors (when they remember to close them)

**Comment by Conchipedia** [comment]
maybe take off the open linked power tab (viewable by other storage) and just have the power tab/storage  linked with the fuel you want to be automatically taken from a stockpile you have linked
