### ISSUE TITLE
Stairs Rotation

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2677]
•	Fix Stairs so that they are rotatable akin to Tables - place them next to a stockpile currently and they move every time something changes. - not to mention how useless they are beyond decorative with "clambering" turned on, and even useless as decorative when you can't tell them which way to face

**Comment by ZebZ** [comment]
#438

**Comment by MarjieAVolk** [comment]
Yep, closing as duplicate.  (We should be working on some decorative building improvements fairly soon, which will cover this 👍 )
