### ISSUE TITLE
Contract ENHANCEMENT

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2678]
•	Add options to contracts for removing blocks (dirt, stone etc) from a given volume co-ordinates - Allows for land clearing, mine digging etc - removed Blocks can be left alternately with either contract party

**Comment by MarjieAVolk** [comment]
This is already supported - add an "Add/Remove Blocks" clause, and select "less" in the drop down to switch it to remove.
