### ISSUE TITLE
Land Claim ENHANCEMENT

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#2680]
•	Perhaps a limit on claiming land Immediately adjacent to existing claims - would reduce griefing and town planning issues 
-	Alternately a "public domain" land claim option - perhaps through voting to either make a plot "unclaimable" or to remove someone’s claim by popular demand.

**Comment by MarjieAVolk** [comment]
This is actually possible to do with laws right now, through 'zones' - which are currently somewhat hard to find, and we are working on an improved version of this feature.  But for now, what you can do is this:

Propose a law 'when attempting to claim property, prevent'.  Then add a zone to the law by clicking the 'add zone' button, which is down near the comment box.  This will make a map appear, where you can color in the area you want.  This law will now prevent claiming property only in the area you defined.

We may also want to support property belonging to the government at some point, but it is not on our immediate road map.
