### ISSUE TITLE
Placing world objects intersecting with built blocks either deletes blocks or intersects with them

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#269]
![untitled-1](https://cloud.githubusercontent.com/assets/14983165/15954027/e6a613b8-2e86-11e6-9c6d-69ddc4c90e3f.png)

Should just not allow them to be placed is the ideal behavior. Bring back the red ghost?

**Comment by metachronism** [comment]
this is why world objects need to block out the space they use

**Comment by craig-jong** [comment]
They do block out the space they use, but I don't think it stops you from placing them conflicting.

I guess I'll fix that.

**Comment by metachronism** [comment]
WorldObjectBlock doesnt have a block on the client, someone needs to add it and set it to be solid so the block collider will be generated

**Comment by craig-jong** [comment]
World Objects ignore occupancy on the first placement.

**Comment by craig-jong** [comment]
Adding the worldobjectblock played poorly with the custom buildings, therefore I left it out. But they can no longer intersect with previously placed blocks.
