### ISSUE TITLE
[Enhancement] Server Admin Commands

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2697]
It feels like some admin commands are missing that should be there and those are the following:

- Remove all rubble on the ground
- Bypassing claims that you are not authorized without needing to do /unclaim
- Blacklist or whitelisting from in-game without needing console access
- Remove all CO2 particles per million in the air

**Comment by Conchipedia** [comment]
not sure about the rubble as it may also remove from underground the ones that people are working on collecting

**Comment by wiloxe** [comment]
True but before use you tell everyone before doing the command would solve that. Theres no reason to cause lots of rubble then just leave it there to cause lots of lag for everyone else.

**Comment by Conchipedia** [comment]
would it be possible to have a Complete list of the current Admin commands and how they work, i for one cannot seem to workl out how to faltten an area and make it grass, also the create a building and then the option to enter 0 or 1 for windows or no windows it generates a building with ALL windows as the walls (when i chose windows option)

**Comment by Conchipedia** [comment]
https://eco.gamepedia.com/Chat_Commands
![snap111](https://user-images.githubusercontent.com/29383891/32606492-699d2de8-c54d-11e7-8404-10d89a0efbab.png)

I found this list of commands are these accurate?

**Comment by Conchipedia** [comment]
any Detailed help with these would be very much appreciated
