### ISSUE TITLE
[Enhancement] Electrical Wires

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2699]
One thing that has been annoying me a little is the fact electricity is wireless. They should be connected using wires, quite similar to what Immersive Engineering Mod for Minecraft did.

![2017-11-01_23 19 25](https://user-images.githubusercontent.com/4078460/32300720-2bbf4620-bf5b-11e7-907d-edd30e82c26b.png)

**Comment by johnkslg** [comment]
Agreed! Would add a lot.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#390
