### ISSUE TITLE
need ability to specify # of contracts or unlimited contracts

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2703]
When I make a contract I want to be able to specify the number of times it can be taken, or allow it to be used a certain number of times before expiring

for example, if I need 100 trees chopped down, its safer/easier if I make one contract to chop 10 trees down, and allow it to be taken 10 times (no player can have the same contract more than once, unless he completed the last one)

and some contracts are good to have limitless #'s of as well

**Comment by johnkslg** [comment]
Good idea. Will think how it could work. Some contracts it wont make sense for.
