### ISSUE TITLE
Long objectives don't display correctly in the textbox

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2704]
The last two letters should be 'es' but they're invisible.  That corresponds exactly to what is visible when the cursor is all the way to the left of that text.

![image](https://user-images.githubusercontent.com/609510/32302563-935122d0-bf20-11e7-841c-e7b5975d9ec4.png)

**Comment by MarjieAVolk** [comment]
This is weirding me out O.o

**Comment by MarjieAVolk** [comment]
I decided to compare this with the input box in chat log; I compared and compared and tried copying over the few differences that I saw, to no avail.  But copying over the whole input box fixed it. >>
