### ISSUE TITLE
Objectives screen text box sometimes doesn't have a cursor

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2707]
This seems to depend on the width of the text in the box; an empty textbox one doesn't have one, add an 'M' and it does, add a subsequent 'ining' and it does not. :confused:

![image](https://user-images.githubusercontent.com/609510/32302998-134e9830-bf23-11e7-8ed9-ea8aa013a060.png)

**Comment by MarjieAVolk** [comment]
Yeah this is super super obnoxious, it's a tmp internal thing, like a UI scaling thing; only fix I have found is to make the cursor wider, thus reducing the likelihood that it will disappear.
