### ISSUE TITLE
[Enhancement] Masonry

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2708]
Pitch Making Skills and efficiency is ALL in masonry Skill tree (the speed for this is Never really needed as the basic craft speed is 6 seconds anyway) 

Existing methods:
Sand to Pitch = Quarry (either with grind to Stone (handy if owning more than 1 quarry or rob a beach)
Wood pulp to pitch = Campfire
Wheat to Pitch = Bakery Oven (A masonry player can grow his own wheat for pitch or sell/give to bakers)

Bakery Oven is made on a Quarry (player has to learn Baking, but put zero points in this), this seems a bit silly as a Masonry player would just like to Sell or craft for other players who actually do baking, and the ONLY reason he would need a Bakery Oven is to make Pitch, Possibly move the Wheat to Pitch recipe to campfire like the wood pulp one (and make ALL recipes in Bakery oven need Baking or other cooking skills (which i think the rest require anyway))

People who do NOT Specialise in Masonry dont seem to realise how hard it is at times to get enough pitch to do the harder crafting (which will get better the higher efficiency they have) as other players want the better materials and as far as i can see Pitch is now used in More recipes.

Stone Roof is a Masonry player's basic building block, still keep the same recipe BUT make the Block look more basic and a bit uglier (not look like Mortared Stone as this is often confusing for players adding Mortared Stone to a room for table requirments)(personally i liked the OLD stone road blocks that looked reasonable as a Stone makers building), this way a masonry player will replace these horrible looking blocks with something much nicer that they can craft later on with better skills and Re-use these blocks for other basic building/flooring/ceiling/walls in a mine.

I was going to add about Masonry player having to learn lvl 1 Carpentry to make a Quarry (but then i checked the other recipes he will unlock: doors,signs,boards etc, so didnt think this needed to be changed as they are often useful in a mine, especially the Doors stopping unwanted players entering and signs if a player gets lost or forgets which tunnel leads to which Source of raw material)

**Comment by Conchipedia** [comment]
![snap092](https://user-images.githubusercontent.com/29383891/32303112-76c7ffe2-bf5e-11e7-8646-88788fc31144.png)

**Comment by Conchipedia** [comment]
wasn't to sure about doing this but i did see Metachronism did Ask for Enhancement labels for things in Github in Eco Discord (and saw other added in here as well)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#356
