### ISSUE TITLE
Can't craft a carpentry skillbook even though I have basic crafting 2

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2710]
Picking up and replacing the table seems to fix the issue.

![2017-11-01 3](https://user-images.githubusercontent.com/609510/32304702-7a8f0baa-bf2e-11e7-9194-5467e52aeb70.png)

**Comment by MarjieAVolk** [comment]
Hm this is working fine for me.  Did you maybe have other exceptions that were preventing this from working?

**Comment by MarjieAVolk** [comment]
I think I repro'ed this; gained a skill and my open crafting ui didn't update.  I saw this in my error log:

NullReferenceException: Object reference not set to an instance of an object
SkillUI+<DisplaySkillTree>c__AnonStorey0.<>m__0 () (at Assets/UI/Scripts/SkillUI.cs:158)
GameObjectExtensions+<InOneFrame>c__Iterator0.MoveNext () (at Assets/Scripts/GameObjectExtensions.cs:74)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:1

**Comment by wiloxe** [comment]
This could be related to the issue that sometimes you have to relog after either adding addon for an example sawmill or gaining a skill.
