### ISSUE TITLE
[0.6.0.3 stable] Farmed tomatoes won't grow

### ISSUE THREAD

**Issue by Thengen** [StrangeLoopGames/EcoIssues#2713]
Once planted, tomato seeds won't grow into plants. The soil sampler doesn't seem to detect the plant growing on it. The block is labelled "TomatoesBlock", and doesn't seem to be recognized as a farmed land. The plant cannot be picked up with 'E', but can be "cleaned" with the shovel.

![aaa](https://user-images.githubusercontent.com/29948377/32319905-5638f458-bfbc-11e7-8ec5-a277a691e8fc.jpg)

**Comment by craig-jong** [comment]
I can't get this to reproduce in the current build.

**Comment by Conchipedia** [comment]
i have them growing on 6.0.3 (all planted at same time within a few blocks of each other),some get to maturity and some don't (but was sort of expecting that Not ALL plants will grow where i am, or take a long time to mature)

**Comment by craig-jong** [comment]
I cannot get this to reproduce and tomoatos seem to grow fine currently. Please reopen this if the issue continues.
