### ISSUE TITLE
[Enhancement] Information Management (Mailbox, Pinboard, News, Clipboard, Internet)

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2714]
- One thing that would be very interesting to see is some form of information management like a mailbox to leave letters instead of placing a sign outside of the house.
- Pinboards would be nice to put up posts or something that is not a contract, like advertisements for one's shop or articles.
- Newspapers would also be interesting where one can write things that are happening in the world of ECO or something related.
- Clipboards to write down information for yourself to keep track of instead of alt-tabbing to make a new document could be nice and also shared directly in game.
- Internet allows for E-Mail, Online pinboard and online news sites and such using computers (Same time giving them more purpose) instead of walking over the few hundred blocks to read the board.

This could be very interesting to have and allows for more things to do in the world.
What does everyone else think of this?

Suggested by Jimpen and Wiloxe.

**Comment by johnkslg** [comment]
I like this idea, enhanced communication.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#391
