### ISSUE TITLE
New mortared stone may not contribute to room requirements

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2716]
From discord discussion:

iRage2Win - Yesterday at 11:03 PM
anyone know why a building made with mortered walls and roofs arent trigging kiln?
https://gyazo.com/0245e85fdf40003d1de21dbb6f8cd8b3

Conchita - Yesterday at 11:04 PM
according to that piccy you have 0 mortared stone (the NEW mortared stone blocks do NOT count as mortared stone)
iRage2Win - Yesterday at 11:05 PM
:open_mouth:
thats lame
all that work for nothing
Conchita - Yesterday at 11:05 PM
u have to actually craft the one that says Mortared stone
just replace the floor or ceiling
iRage2Win - Yesterday at 11:06 PM
easier said than done
I actually had a design D:

**Comment by johnkslg** [comment]
Fixed!

**Comment by SeanAtr0n** [comment]
err guess this got unfixed, need a new solution

**Comment by knexer** [comment]
Looks like at least some of the new mortared stone blocks (mortared stone floor) don't even count as room blocks at all.  But in a really weird way - the status tab says 'not in a room' but /checkroom disagrees.

**Comment by johnkslg** [comment]
@metachronism fixed with tiers?

**Comment by metachronism** [comment]
this is a @craig-jong issue if still broken, but pretty sure its fixed
