### ISSUE TITLE
Young trees are phantoms

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2719]
They disappear with no trace when they're struck with an axe.  Full-grown trees aren't affected.  If I log out and back in they're still gone.

**Comment by MarjieAVolk** [comment]
What is the desired behavior here?

**Comment by metachronism** [comment]
thats intended.  young trees get murdered if you axe them

**Comment by knexer** [comment]
Yeah, that's not communicated very well; they should do something other than disappear instantly.  Even some particle effects + giving a bit of wood pulp would help a lot.

**Comment by metachronism** [comment]
there is a wood chip effect and the tree disappears, what else do you want?
also a young tree giving any resources doesn't make sense either

**Comment by knexer** [comment]
Ah, yeah, the wood chip effect isn't happening on my client.  Perhaps that's because I'm striking the leaves instead of the trunk?  When the tree is very small it's difficult to hit anything but the leaves.

Wood chip effect when the tree disappears would be/is perfect 👌

**Comment by wiloxe** [comment]
Leaving behind wood pulp on the ground would maybe be something?

**Comment by Nanders** [comment]
They play wood chip effect now.
