### ISSUE TITLE
Disconnecting for Inactivity any time an item is picked up, placed, or transferred between inventories

### ISSUE THREAD

**Issue by Alixstotle** [StrangeLoopGames/EcoIssues#2722]
I have 20 stone in my carried slot. I am able to open benches and inventories, just cannot transfer any items to or from my inventory.

I think it is related to a particular cart, as the cart can be moved, but the inventories shown to be in range do not update no matter where I take it. I am disconnected any time I attempt to move items in the cart's inventory as well. This applies to all carts. Another user is able to see the correct linked inventories and can transfer items to and from the cart, but is also disconnecting on interaction with the world.

I am able to move items around in other inventories so long as I do not transfer anything from my inventory or the cart's.

**Comment by MarjieAVolk** [comment]
Could you share your Game.eco save file?

**Comment by Alixstotle** [comment]
I apologize for the delayed response, I was out of town for the weekend.

The server owner fixed the issue somehow while I was away, so I no longer know how to further explore the problem.

I would still like to help though, so I will try to find out what the owner did to fix the problem. Would it still be useful to upload my client-side Game.eco file?

**Comment by MarjieAVolk** [comment]
Hm, probably not unless you can get a backup version that is still broken.  Can you find out what they did to fix it?

**Comment by Alixstotle** [comment]
Turns out they just restarted the server, and that was enough to fix it. Could have just been a chance corrupted temp file or something.

Let me know if there is anything else I can do to track down the issue.

**Comment by johnkslg** [comment]
Closing for now as no-repro.
