### ISSUE TITLE
[Staging 6.1.0 #5eff2565] World holes everywhere!

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2723]
So, We thought of giving the staging version of 6.1.0 a try on our server as everyone agreed to it. But thing's weren't that smooth as you would expect when changing versions as we ended up with the following issue all around different places.

![world hole](https://user-images.githubusercontent.com/4078460/32371294-9721b6b0-c090-11e7-8ec7-80b819cee3bc.PNG)

If you need the save files please feel free to request it.

**Comment by metachronism** [comment]
should be fixed in latest staging.
