### ISSUE TITLE
[Enhancement] Road Railings

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2724]
One thing that we find to need in many cases is road railings since you can drive off the road and end up in the water or somewhere where you have to hammer the cart to get it back.
So, for now, we are currently stuck with this solution.
![road railings](https://user-images.githubusercontent.com/4078460/32385622-0cc7f2fc-c0bf-11e7-84dd-0590cd51494e.PNG)

**Comment by MarjieAVolk** [comment]
What is wrong with this solution?  I don't see why we would support anything more specific than placing blocks on either side of the road.

**Comment by MarjieAVolk** [comment]
Did you want a block that looks more like a railing?

**Comment by wiloxe** [comment]
Yeah. A block that looks more like a railing. Also while on the topic maybe some form of road paint to paint parking areas would be nice too :D

**Comment by Huntermeign** [comment]
Well we have a fence version of Lumber, Why not make the fence version of corrugated steel be like railings.

**Comment by elfl0rd** [comment]
@BlazeGuy2 suggestion?

**Comment by keegan-o** [comment]
I'm going to assign this to Rob as his first new block to make! These should be Metal road railings that can be a form which will be added to the Corrugated Steel building material.

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/6a5d4b6c-e6f3-48f0-9a3e-2bbd761114ca)

**Comment by keegan-o** [comment]
https://www.youtube.com/watch?v=nMyXd3B2ao8 😂

**Comment by RobertMangano** [comment]
road barrier is checked in and hooked up with rules. But still needs to be implemented.

**Comment by elfl0rd** [comment]
A small request, can we get two types of barriers?
Located in the center, for lane separation and located closer to the outer side of the block for installation at the edge of the road.

**Comment by beastyn** [comment]
@keegan-o is it for you for the implementation?

**Comment by keegan-o** [comment]
Should be done now that it was added to the tech tree!
