### ISSUE TITLE
Got some late game items showing up in search and select

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2726]
...at the beginning of the game; because their recipes don't have skill requirements.  These include:
- Copper pipe recipe
- Steel pipe recipe
- Industial furnace recipe
- Industrial robot recipe
- Quality controller recipe
- Smithing tool shelf recipe
- Thermal cracking unit recipe
- Gas generator
- Button
- LogicGateItem
- Switch
- Transmission pole
- Petrol
- Wire

(The latter few seem to not have recipes at all actually, so maybe they should just be hidden?)

There also seem to be several food items that have no way to get them in game normally, such as rice, milk, and sugarcane.

**Comment by MarjieAVolk** [comment]
Do you think this should be fixed in autogen actually?  Or in the search and select system?  (Eg. we could have items be discovered only if the ingredients to their recipes are also discovered, recursively)

**Comment by wiloxe** [comment]
I hope you will add support to see things that aren't researched yet in stores so you can prepare to buy them before it's researched so the person can see what to aim first for and such.

**Comment by Conchipedia** [comment]
for example i needed a sawmill to make lumber, i had learned the recipe for lumber but needed another skill to learn to make the sawmill, so i put in the shop under wanted a sawmill number required 1, and some kind player sold me one, and now i put this into my room and i can happily make lumber
