### ISSUE TITLE
Invalid contracts can be posted

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2727]
![image](https://user-images.githubusercontent.com/609510/32390878-54d9d678-c08d-11e7-8f5a-f75dde004f7d.png)

**Comment by johnkslg** [comment]
In this case the construction post was removed after the contract was posted.  Made the picker object survive this case, using the lastpicked position:
![image](https://user-images.githubusercontent.com/3536496/32570860-60949a20-c47a-11e7-9814-83b51616a10f.png)
It will remember this even if the construction post is removed after placement.
I'll make a better property selector someday.
