### ISSUE TITLE
Trees growing on dirt stockpiles end up floating after emptied.

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2733]
So when you have a stockpile full of dirt, sometimes a sapling can spawn on the stockpile of dirt since it's a placed object but when you remove the dirt from the stockpile you end up with floating trees like these.

![floaty trees](https://user-images.githubusercontent.com/4078460/32396835-43fd995c-c0e7-11e7-8bd1-88a9eed13b97.PNG)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6902
