### ISSUE TITLE
Room detection is broken

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2735]
See Nanders' awesome room in the 6.0.3 playtest save (available on svn).  Room detection doesn't detect it as a room.  Placing blocks in the room occasionally seems to fix the issue, but it's unreliable/unpredictable.
In this pic, placing the circled blocks caused room detection to accept the room (probably fewer than that many would suffice).  As you can see they're not even part of the external walls in any way.
![2017-11-03 6 _li](https://user-images.githubusercontent.com/609510/32400063-fc808162-c0b8-11e7-9a62-9aec9e2bface.jpg)

**Comment by craig-jong** [comment]
This likely has to do with the room being "too big" and the reason some blocks work and others dont just have to do with how far away the detection has to go.

Could be wrong - that's just a hunch.

**Comment by johnkslg** [comment]
Correct you are. Fixing.
