### ISSUE TITLE
Transparent surface of pipes under the water surface next to each other

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2738]
![grafik](https://user-images.githubusercontent.com/26040573/32415341-b5046c96-c238-11e7-9288-ef1215b23720.png)

**Comment by Conchipedia** [comment]
that's due to the Air that surrounds a pipe you can see this effect as a pipe is not a Full solid block

**Comment by johnkslg** [comment]
PIpes need to work under water.

**Comment by Conchipedia** [comment]
i also think any None Full block also gives this effect of air surrounding them, i did also notice this when i placed glass into water (added a glass wall into a room i had dug down normally so when i was crafting i could see the fish swim by)  Fish can detect you even if you are on the other side of the glass and swim away. would be nice if they couldn't detect you through the glass and then we can maybe also have the option of perhaps building and indoor Aquarium??

**Comment by Conchipedia** [comment]
this seems to be liked to this issue
https://github.com/StrangeLoopGames/EcoIssues/issues/2354

**Comment by BlazeGuy2** [comment]
seems to be working on my end, closing
