### ISSUE TITLE
dawn switch for outside lamps [Enhancement]

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#2739]

**Comment by MarjieAVolk** [comment]
Sorry, what's a dawn switch?  Do you want it to have like a light sensor?

**Comment by johnkslg** [comment]
Keep in mind housing only works when items are on.

**Comment by MarjieAVolk** [comment]
It does?  That doesn't seem right

**Comment by Nanders** [comment]
Incase people don't know: Dawn switch = the light sensor on outdoor lamps that make them turn on at night, and off during the day.

**Comment by Nanders** [comment]
Incase people don't know: Dawn switch = the light sensor on outdoor lamps that make them turn on at night, and off during the day.

**Comment by peternightingale** [comment]
light sensor would be awesome for lights.

**Comment by Dreepa** [comment]
If the user could set it to auto in the properties of the object, that would be awesome. Sometimes you might want to run stuff at day for aesthetic purposes.

**Comment by craig-jong** [comment]
Should go into the Eco Suggestions project.
