### ISSUE TITLE
Harvest field clause squishes if you shrink the window

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2741]
![image](https://user-images.githubusercontent.com/3536496/32470874-59335ef4-c30f-11e7-9599-8a1ccc600b7a.png)
Can check other clauses too

**Comment by johnkslg** [comment]
Also, the second pick button was hard to press

**Comment by MarjieAVolk** [comment]
Oh didn't realize there was already a bug for this, just tried to fix this by increasing the min width of the window
