### ISSUE TITLE
Content size fitter kills performance

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2742]

**Comment by MarjieAVolk** [comment]
I don't really think I can do anything about this.  Have to wait for a fix from unity.  But since it only happens in the editor, it doesn't block release.

**Comment by MarjieAVolk** [comment]
Verified this does not happen in the build.  Also I haven't been noticing it much in the editor either, not sure why as I don't think I got any unity patches
