### ISSUE TITLE
Kill Default Unity Launch Window

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2746]
Apparently most of the options on this window don't do anything anyway. 
Should identify the ones that do and move them into runtime.

**Comment by metachronism** [comment]
would need a lot of work to remove this

**Comment by Nanders** [comment]
What is on there that would be a lot of work? Looks like the only thing that uses any sort of parameter from it is screen resolution which can be changed at runtime.
