### ISSUE TITLE
Interaction distance not calculating correctly when placing blocks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2748]
It appears that interaction distance is testing the distance of the ray, instead of the distance to the resulting block that would be created.  

That is, I can target this block and a ghost image will appear:
![image](https://user-images.githubusercontent.com/3536496/32522892-f2e93942-c3cd-11e7-9182-dd4cdc24f451.png)

But if I move the mouse slightly up, targeting the same block, because the ray is slightly longer the block will not allow placement:
![image](https://user-images.githubusercontent.com/3536496/32522903-fc6632ea-c3cd-11e7-9c48-7ed0e5adcd9b.png)

I think this is what's happening but haven't checked.  It also feels like a really short distance.

**Comment by metachronism** [comment]
objects that dont override distance use the default which is 2, IIRC.

tools have higher interact distances, so placing things with tools won't have this issue.

**Comment by MarjieAVolk** [comment]
Unify the distance!

**Comment by SeanAtr0n** [comment]
pushing back to go w/ the delayed client side interactions
