### ISSUE TITLE
Picking up and putting down rocks effects are too much

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2751]
Should be a subtle cloud of physics-based dust, if anything. Shouldnt have rock chips.
![image](https://user-images.githubusercontent.com/3536496/32523326-aec15f9a-c3cf-11e7-9a8b-129480f9463e.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#355
