### ISSUE TITLE
Placement is janky

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2753]
For some reason placing things feels really flakey and annoying. Check out this gif:
https://imgur.com/a/vW24I

As I move side to side, the placement fluctuates wildly, jittering between different blocks.  A few things could be happening here:
- The casting ray is colliding with the grass, placement that ignores plants should not collide with them.
- Funny colliders on the blocks
- Something else?
[](url)

**Comment by metachronism** [comment]
I believe this mostly stems from the fact that world objects arent centered when authored, so placing them aligned to the grid feels janky

simple 1x1x1 objects are probably a simple fix like an offset of .5 somewhere, but larger objects might need more work.

Would really like to investigate a free place solution, for most objects they don't need to be aligned to the grid.  would also help a lot for placing things like signs or pictures on walls

**Comment by johnkslg** [comment]
I dont think this is that issue, because you can see how the selected location flicks back and forth.  This is something with the choosing of the block position.

**Comment by MarjieAVolk** [comment]
I almost want to put this on high priority, buuuut it's a high medium I guess :P
