### ISSUE TITLE
Clean up Eco termination

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2756]
Steam client very frequently does not like how Eco exits, registers as a non-responsive program.

**Comment by Conchipedia** [comment]
windows oftens tells me that Eco.exe is not responding when i choose to exit. 

Operating System: Windows 10 64bit ( i play on 3 different PC's (All windows 10 64bit (my own and my friends) with various memory and graphics card) but it always seems to do the same, Not sure if this is 64bit related or a problem with the exit code, i think i also have Eco.exe added to my steam as a non steam game (so i can get the steam overlay to display fps) and i think it also does the same on exit)

so i have given up exiting the proper way and just have task manager open in 2nd monitor and close the process.

**Comment by SeanAtr0n** [comment]
I'm pretty sure this has something to do w/ the multi threaded code

**Comment by metachronism** [comment]
it closes fast for me now, what is an unreasonable amount of time?  I have no idea what unity is doing to delay it, all the threads get closed when you disconnect
