### ISSUE TITLE
'Name cannot begin with the '3' character'

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#2760]
I think the error is caused by players renaming a deed to something that starts with # symbol.
The error usually crashes the server, but not always.
https://cdn.discordapp.com/attachments/301803988313964544/377933477158322198/unknown.png

Game Save:
https://www.dropbox.com/s/jikejbtgsdwigjj/game%20save_name%20issue.rar?dl=0

**Comment by Conchipedia** [comment]
i think we might also need a better way of detecting/showing "Deed" names, as the only way of finding name of a deed is to either log on to the server and manually drag around the world map, highlighting each highlighted deed on map (showing the name) or using the map option in the graphic web browser that displays a map and doing the same, and there is no way a Cart deed can ever be found.
Possibly adding an option in the Server itself to display "All deed names" of both carts and claimed land with possibly an option for The Server Admin to rename them , as often people Might use rude names. Maybe even allow the viewing names of tables and especially carts (as i have once seen a cart with the name "penis") which thankfully was found as all deeds was removed when the World was checked and cleaned up for the entry to "PAX 2017"
The names of Deeds,tables,storage, and  text in signs and on carts MUST be stored somewhere, so giving this EXTRA control to a Server Admin will NOT do any harm, maybe even help the poor teachers whose "lovely" pupils will insist on creating "rude names" for most things if they have that option (i know i was once a "lovely" pupil and MIGHT have done that)

**Comment by Conchipedia** [comment]
just as an afterthought, to help with Server control and Over population, maybe a way for deeds/claimed land to become FREE if a player hasn't logged into a server for over a week this would help other players that get blocked in by inactive players (with the option for Admin to turn this on/off and adjust the time)

**Comment by MarjieAVolk** [comment]
@Conchipedia Moving your suggestions to a separate bug

**Comment by MarjieAVolk** [comment]
I've been trying to reproduce this by naming deeds to things like "#", "#3", "3" etc, and can't get it to happen.  Your save file link is not working for me.  Do you have any crash dumps from the server crashes?

**Comment by Conchipedia** [comment]
i was asked to search the world and couldn't find any Land Deeds called anything unusual only thing it might have been on was a "Cart Deed" but not sure how to find that if its not in a Chest but in a players backpack.

**Comment by MarjieAVolk** [comment]
Oh, didn't try with a cart deed, will try that now

**Comment by Conchipedia** [comment]
with a world save would a Players Inventory be visible to you or is that just gone?

**Comment by MarjieAVolk** [comment]
I can log in as anyone in my dev environment (not on a real server), so yes I could look at people's inventories with a save

**Comment by MarjieAVolk** [comment]
Okay, renaming cart deeds and world objects hasn't caused an issue for me yet either

**Comment by MarjieAVolk** [comment]
Oh but wait... the error is happening on save, not on rename?

**Comment by Conchipedia** [comment]
Maybe it can be renamed anything you like but only comes up with error when it has been saved and the Server tries to reload it back in (but maybe you already did that)

**Comment by MarjieAVolk** [comment]
By the way guys, Sean found this happens when you try to create a law while there's a property with that name.  So will re-examine this shortly with that in mind.

**Comment by MarjieAVolk** [comment]
Okay well, been trying to repro this every way I can think of and still no dice.  If you guys had a game save where I could repro the problem, it might let me fix it (The initial link that was given has never worked for me).  So until I hear back or get a repro, decreasing the priority on this
