### ISSUE TITLE
Disabling authentication makes Unity freeze when connecting to the server sometimes.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2761]
Need this feature for development, and other things like school testing.

**Comment by metachronism** [comment]
I can't debug this, it doesn't happen on my machine

**Comment by MarjieAVolk** [comment]
Really, even when you disable require authentication on both the server and the client?  Might have to try connecting several times, since it's off and on.

**Comment by metachronism** [comment]
I had it disabled for an entire day and never encountered any issues

**Comment by metachronism** [comment]
(and even then, we are all programmers here...  we should be able to do some basic debugging and figure out the problem...  without offloading it to someone else immediately)

**Comment by johnkslg** [comment]
This seems to have gone away.
