### ISSUE TITLE
Server Browser needs to support potentially thousands of entries

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2764]
Make a UI list modification that can handle this many entries, testing it (could not populate till scrolling down, for example)

**Comment by MarjieAVolk** [comment]
I did just recently add a coroutine based initialization thing, which I added for search and select.  Might help

**Comment by MarjieAVolk** [comment]
On the other hand, if there are thousands, we probably need to focus on how to filter them.  And maybe paginate or something.

**Comment by johnkslg** [comment]
Yeah pagination, hiding of off-screen entries might help, etc.  Will be good to be prepared for whatever case.

**Comment by MarjieAVolk** [comment]
Went with a 'load more' button at the bottom of the list for now, with a default cap of 40 entries showing.  Seems to improve performance quite a lot, despite still requiring a similar amount of network traffic.

**Comment by johnkslg** [comment]
Hooray!
