### ISSUE TITLE
Need security on our server browser

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2766]
Right now, a hacker could spam the server list with millions of entries, preventing anyone from playing the game.  We need to anticipate and prevent this scenario.

**Comment by metachronism** [comment]
I don't see any reliable way around this without requiring users to log into an account on the hosted server

**Comment by ClayC90** [comment]
Server browser behavior should be:

When no authentication is present, Display some basic information about the server, (This data should be cached, maybe even a noauth.html page that is auto regenerated every hour by the server?)
When authentication is present, Display the usual website with all information and law systems etc.

**Comment by metachronism** [comment]
@ClayC90 I think you are talking about a separate issue.  this is just the server browser listing service.

**Comment by rainfarmer** [comment]
switching to new server browser
