### ISSUE TITLE
Difference between Mechanical and Electrical Power is very unclear

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2767]
The mechanical "power grid" shouldn't be called "power grid" and it certainly shouldn't share the same name as Electrical.

**Comment by MarjieAVolk** [comment]
There's a difference? >>

**Comment by metachronism** [comment]
mechanical energy is meant to be piped into the world objects, but none of the art has been updated as such yet

**Comment by metachronism** [comment]
closing as dupe of #1328
