### ISSUE TITLE
Stackoverflow in routeprobing creation during server migration

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2768]
Save file: https://www.dropbox.com/s/qi1k2w80naloyx1/server.zip?dl=0

Stack:
>	Eco.Simulation.RouteProbing.RouteRegions.AddWaklableWithUnknownRegionID(pos) Line 90	C#
>	Eco.Simulation.RouteProbing.RouteRegions.AddWaklableWithUnknownRegionID(pos) Line 90	C#
>	Eco.Simulation.RouteProbing.RouteRegions.AddWaklableWithUnknownRegionID(pos) Line 90	C#
(infinity)

**Comment by SeanAtr0n** [comment]
works for me in master
