### ISSUE TITLE
[Enhancement] bamboo as a building material

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2770]
Bamboos include some of the fastest-growing plants in the world,[4] due to a unique rhizome-dependent system. Certain species of bamboo can grow 91 cm (36 in) within a 24-hour period, at a rate of almost 4 cm (1.6 in) an hour (a growth around 1 mm every 90 seconds, or 1 inch every 40 minutes).[5] Giant bamboos are the largest members of the grass family. Bamboos are of notable economic and cultural significance in South Asia, Southeast Asia and East Asia, being used for building materials, as a food source, and as a versatile raw product. Bamboo has a higher specific compressive strength than wood, brick, or concrete and a specific tensile strength that rivals steel.

this bit was from wiki (possibly to give an idea of which biome they would be best suited growing in.
![house made entirely from bamboo](https://user-images.githubusercontent.com/29383891/32590618-2236d902-c513-11e7-9775-4cf40eeb75a9.jpg)
![bamboo rafts](https://user-images.githubusercontent.com/29383891/32590625-2da4b64c-c513-11e7-9bd2-09c20189eeaf.jpg)

**Comment by Conchipedia** [comment]
maybe [Enhancement] might not have been the right label? maybe we can have one for [Crafting Ideas]?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#354
