### ISSUE TITLE
[Enhancement] basic boats from natural materials

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2771]
![dug out tree canoe](https://user-images.githubusercontent.com/29383891/32590646-502fbe96-c513-11e7-88a0-88f10b87e920.jpg)
![bamboo rafts](https://user-images.githubusercontent.com/29383891/32590653-55efd398-c513-11e7-80ac-9509f562d9c6.jpg)

just some basic Ideas, linking this as well here 
https://github.com/StrangeLoopGames/EcoIssues/issues/2770
as the raft is a boat made from bamboo
![kayak-skin](https://user-images.githubusercontent.com/29383891/32590787-f9561092-c513-11e7-907d-5f1daeb0d8cb.jpg)
Skin on frame refers to a method of boatbuilding that has been around for a very long time. Typically a light frame often made of wood is assembled. This is then covered by a waterproof membrane (can be animal skin). The resulting boat is light and econonmical of material

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#388
