### ISSUE TITLE
Unlearn giving wrong or way to less SP back 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2772]
i learned "Elections" which cost me 108sp, but if i try and unlearn it it will only say that I can only get 3sp back, surely it would be 27 which is 25%?
Would the unlearn be based on 25% of the original value (which i'm Not sure what it is)  or the value you learned the skill at?
![snap112](https://user-images.githubusercontent.com/29383891/32608900-ba61a65c-c555-11e7-8eae-98ee8f4d63a0.png)

**Comment by Conchipedia** [comment]
![snap113](https://user-images.githubusercontent.com/29383891/32609031-24244ab8-c556-11e7-99b9-90075f49d12c.png)
![snap114](https://user-images.githubusercontent.com/29383891/32609038-2a139384-c556-11e7-8c25-c875556a2c3f.png)

**Comment by Conchipedia** [comment]
these are the Unlearn and normal learn for the rest of my skills

**Comment by MarjieAVolk** [comment]
'unlearning' has been re-written with the new specialties stuff, so this is obsolete now.  I did test out unlearning specialties, and I think it is correct now.
