### ISSUE TITLE
No limit on how much text can be placed in a sign and too much gives sky writing 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2773]
i think we need a way of having a maximum number of words/characters that can be placed in signs, normally when something is typed if small amount of text the letters appear large and fill the sign, but as you will see in these Extreme Example snapshots the writing Doesn't shrink down it just draws on the area above and below
![snap544](https://user-images.githubusercontent.com/29383891/32615592-10cd2c34-c568-11e7-8d9b-24e4650c075a.png)
![snap545](https://user-images.githubusercontent.com/29383891/32615678-43a35098-c568-11e7-8fe7-5517b4520296.png)
Oh and the text is from what my friends on my server suggested as my "Theme Tune" as i'm always underground Mining.

https://www.youtube.com/watch?v=ytWz0qVvBZ0 (bet you mine faster while listening to this)

**Comment by ClayC90** [comment]
This should be tackled like minecraft, 4 lines with 20 characters each line maximum

**Comment by MarjieAVolk** [comment]
Fixed the rest of the way in 7.7 (not the next major release, but the one after).  (It has already been fixed in that text can no longer go off the edge of the sign, it just gets tinier and tinier.  The coming fix will also add a character limit.)
