### ISSUE TITLE
Dont display too much in the skill window

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2774]
"the user interface on the skill trees could be improved upon to be a bit less overwhelming when the player first opens it. "
From a refunding customers feedback, and I tend to agree.  We should take the same approach as the searchandselect dialog, where we only display the current level + the next level, including for the top categories.  It should be a cool event when new categories of skills get unlocked.

I'd also like to get the research-required nodes in the skill tree to look more special, different from the advancement requirements.   

We could have a 'show all' toggle that still shows everything, greyed out potentially.

**Comment by knexer** [comment]
Would also be affected significantly by https://github.com/StrangeLoopGames/EcoIssues/issues/2665; it would be less overwhelming if the skill pages were more numerous and smaller/focused, and all but survival were locked at the start.

**Comment by MarjieAVolk** [comment]
This has been addressed
