### ISSUE TITLE
Chests' contents disappeared

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2777]
On hoary marmot, all of my chests were empty when I logged in to playtest.  They were on my property, in inherited mode and nobody else was on the deed.
So either a) somebody managed to take the stuff (and the test server isn't public right now, so speak up if you did so we know what kind of bug we're looking at here!), or
b) the chest's contents were lost, presumably when the server was updated or restarted.

**Comment by SeanAtr0n** [comment]
I noticed this as well... but in my migrated save chests still have stuff (including books) so maybe it's resolved?

**Comment by metachronism** [comment]
cant really do anything about this with no repro steps

**Comment by knexer** [comment]
Just happened again when marmot was restarted, so I guess it probably happens on every server restart now.

**Comment by wiloxe** [comment]
Have had this also happen to us when the server crashed. I wasn't online at that moment so I thought someone took it from the chest but this could very well be what happened.

**Comment by Snooy** [comment]
I am also on WIloxe's server. 
i can add that all chest was Empty for me, **Even chest name's reset.**

**Comment by wiloxe** [comment]
Any news on this?

**Comment by SeanAtr0n** [comment]
whoops, has been fixed for a few days now
