### ISSUE TITLE
Can't remove clauses from a law if they wrap to next line

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2780]
![2017-11-09_li](https://user-images.githubusercontent.com/609510/32631178-49790170-c554-11e7-8dfe-41825074c820.jpg)

Look, the little x is in the wrong spot and therefore can't be clicked on.

**Comment by MarjieAVolk** [comment]
x is also not quite positioned right even when on the same line these days

**Comment by syuzan-yeranosyan** [comment]
On web-develop branch
