### ISSUE TITLE
You can use Excavator to remove debris without having to pick it up.

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2781]

**Comment by SeanAtr0n** [comment]
Intentional, excavators R powerful

**Comment by MarjieAVolk** [comment]
>> That doesn't sound right

**Comment by SeanAtr0n** [comment]
why not?

**Comment by MarjieAVolk** [comment]
Why wouldn't it give you the same materials as if you picked it up by hand?  Not intuitive and doesn't make sense imo
