### ISSUE TITLE
Debris removal contract claims there's debris where there is none

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2782]
![2017-11-09 3](https://user-images.githubusercontent.com/609510/32633448-6f92783e-c55c-11e7-9f32-4acc7bfc8b21.png)
My x, y, z coordinates match those in the popup dialog, but there's no debris in the voxel at my feet.

**Comment by knexer** [comment]
Right, so it's pointing at the trunk the next voxel over.  If the popup said 'debris or stump' it would've been perfectly clear.

**Comment by johnkslg** [comment]
Changed text to debris/stumps
