### ISSUE TITLE
Cart's deed "erased"

### ISSUE THREAD

**Issue by dmorchard** [StrangeLoopGames/EcoIssues#2783]
After placing a cart, right clicking on the cart with the deed in hand results in a new blank deed in the cart which can't be used to recover the cart.
![image](https://user-images.githubusercontent.com/30359271/32633521-78adfdb0-c56d-11e7-9041-37aa0e516ba3.png)
The same thing occurs if it's a chest that the deed is clicked into, and with both sizes of wood cart.

**Comment by MarjieAVolk** [comment]
:O  Been trying to repro this for a long time, thanks for repro steps!
