### ISSUE TITLE
Negative weight cart inventory

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2785]
![image](https://user-images.githubusercontent.com/609510/32632266-ce912f6a-c557-11e7-9583-c91f0a78af95.png)

**Comment by MarjieAVolk** [comment]
noooooooo

Remember what you were doing with this inventory before this?

**Comment by knexer** [comment]
I did basically everything it's possible to do with an inventory before
noticing the negative weight:
Moved dirt and stone in and out of the cart with a shovel; moved them in
and out via dragging from/to linked inventories; hooked the cart up to a
crafting table, which took the dirt to compress it into ramps for storage.

**Comment by MarjieAVolk** [comment]
Well this bug isn't super helpful and hasn't been reproed in a long time
