### ISSUE TITLE
[Enhancement] Filter for Pollution Output

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2786]
So I've already suggested this idea in the Ideafactory channel on discord but I thought why not also make a GitHub post as well.

There should be a way to filter your pollution output from your polluting machines to keep blast furnaces running without causing too much pollution and such. Here's an example:
http://www.gcsescience.com/pse11-electrostatic-chimney-pollution.htm
but it won't be easy to make and requires electricity to function, It will also require regular cleaning as the plates can be filled up with carbon and won't function anymore and leaving you with another waste product, Ash.
Ash is pretty much burnt carbon and it could be used in some application of things but that will be for another idea suggestion.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#353
