### ISSUE TITLE
[6.1.0 Staging #2bfcd2da] Arrows only goes north

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2787]
(Thanks, Jake Rockwell for finding this)
https://im.ezgif.com/tmp/ezgif-1-33bca8d4d9.gif
So it turns out that arrows only go one direction shown in the gif making hunting impossible.

**Comment by Conchipedia** [comment]
one of the BEST bugs i've seen, maybe we can paint a target on a players back and then ALL arrows would target them :)

**Comment by SeanAtr0n** [comment]
fixed in latest

**Comment by wiloxe** [comment]
@Conchipedia Here you go http://gph.is/2iNPuv6

**Comment by Conchipedia** [comment]
@wiloxe ty <3
