### ISSUE TITLE
[Suggestion] Ability to sit down in chair or possibly interact with other furniture

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2788]
Would be nice to have the Ability to sit down in a crafted chair becuase at the moment if players want to AFK we used to stand ON the chairs to make it look as we was resting (with possibly the game going to a 3rd person view so player can be seen) maybe even adding a rest bonus or something, if this is possible maybe the introduction of beds and the ability to lay down, rest etc (with the option of rest bonuses). 
I see at the moment we are getting a housing Bonus for having chairs table and bookshelves in them (great idea) so giving Furniture an extra function of some sort cannot hurt (would encourage more people to craft/buy/sell them)
maybe we could even STORE the Skill Books that we craft in a Bookshelf, which would save on space (and make them more of  useful object)
maybe even have a piece of furniture or something to Store the Scrolls in (but somehow be able to link this storage so scrolls can be used/removed and visible from the Store (if they are for sale)

**Comment by MarjieAVolk** [comment]
@SeanAtr0n seems like it wouldn't be too hard to allow sitting in chairs, using vehicle code?

**Comment by Conchipedia** [comment]
would that possibly allow a 3rd person view? 
would be nice to see me sat down, as i can only see what i look like if i open the Avatar window (and sometimes i forgot how cool or boring i made myself)

**Comment by Conchipedia** [comment]
renamed title as you had added the "Suggestion" label

**Comment by SeanAtr0n** [comment]
Fixed
