### ISSUE TITLE
Contracts disappearing / getting in weird state

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2789]
On the current marmot staging save (I'll upload to svn) my three contracts are all a) not visible on my contract board b) unassigned c) accepted by me:
![2017-11-10](https://user-images.githubusercontent.com/609510/32676300-fe4daabe-c60e-11e7-9371-cff27e4a3d27.png)

**Comment by MarjieAVolk** [comment]
Same as this, which was marked as fixed: https://github.com/StrangeLoopGames/EcoIssues/issues/2671

Fix might not be in staging yet?

**Comment by knexer** [comment]
Yeah it's still in CR.  K, resolving this as a dupe
