### ISSUE TITLE
Minimap Feedback

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#279]
https://docs.google.com/document/d/19eazdPVKCHde3SPdoEGRYezMJhNd1BASTEA06YGYIig/edit
- [x] Icons should move without lag when panning
- [x] Icons should shrink more when zooming out and be smaller
- [x] Text on icons should be at 30% as big as it is
- [x] Filter text goes outside the bounds, shrink it and make it autosize
- [x] Property panel should go away, in it’s place we will show the property at the center of the view ( where it says “Center: x,y”, it should say “x,y: John Town” or just “x,y” if it’s public land.
- [x] Only players should display text for their names, and there should be a ‘show player names’ filter box
- [x] No craft tables should display their name (that can be seen in the tooltip)
- [x] On player names, display beneath them their top skill as a career name ie, “(Logger)” or “(Researcher)”.  This should be per-skilltree, work with Craig to get career names added to all Skill Trees
- [x] Add color to the tooltips. Numbers and names should be rendered in colors as other tooltips do.  When there is no fee, it should say ‘none’ in color. Use the Text class, Text.Info, Text.Name, etc
- [x] Your player icon should correspond exactly with your position.  Make it immune from the server update, instead forcing it to the correct position on the client as a special case.
- [x] Make tree scale vary based on age, and make the max size bigger than current
- [x] Clamp tree random rotation 0,90,180,270,
- [x] The Gui panel besides the ‘Center’ text is messed up should frame the text properly
- [x] Reduce lod aggressiveness at max levels. Zooming out after already revealing the full map should not reduce the lod quality.
- [x] When zoomed out, things at the horizon cull out too early, before they finish curving around to the backside. Mainly when the minimap window is allowed to change it's aspect ratio.
- [x] Add a ‘show trees’ checkbox to the minimap
- [ ] Current player’s icon should look different than other players
- [x] Trees do not disappear from the minimap once they’re cut down
- [x] Trees should fade out instead of just popping from existance
- [ ] Meteor! Should be able to just have it moving above the map, slowly rotating, being wrapped as usual.

**Comment by johnkslg** [comment]
Some more:
- [ ] Replace star background with old blue background (we'll need an atmosphere, clouds etc before we can do stars)
- [ ]  Icon disappears after moving a long distance
- [ ]  If a table doesnt have an icon associated with it, choose a default one, or use text (all tables should show up on the minimap)
- [ ]  Text showing the property name (bottom of minimap frame) is too small and overlaps the text area
