### ISSUE TITLE
Campfire continues burning animation when out of fuel

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2790]
It still stop if it has no orders it can progress on.  I'm guessing this might be related to the recent changes to power grid code.

**Comment by MarjieAVolk** [comment]
Ah... this is because of the Crafting animated state being an out of date partial duplication of the Operating state... removing the Crafting state now

**Comment by MarjieAVolk** [comment]
Fixed in SVN
