### ISSUE TITLE
Helpful hints for a NEW ISSUE in github

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2791]
When a player puts in a github "New Issue" would any of the Following things be of help if added to the title:

[Art] = art related things
[Enhancement] = improvements on exisiting things already here
[Suggestion] = a new idea for something to be possibly thought about and possibly added to eco
[other possible heading] = anything that would be helpful to pinpoint what it is about

I already try and "search" keywords for an issue i spotted so i try and NOT duplicate anything, also that would give me something related in name to the issue i have seen and to be able to comment or add to it.

any other helpful suggestions by you would be very much appreciated

**Comment by MarjieAVolk** [comment]
I'm not sure how these bracket title labels got started, but I usually just put the matching github label on the issue as step 1, we don't have rules about labels in the title.  We just now added the 'Suggestion' label, that's gonna be what we use for player suggestions now, so basically if it's a suggestion putting that label on it will be helpful, otherwise it doesn't really need a label.  I would go through and sort new bugs anyway, and change up any labels that are wrong etc, so not a big deal.

**Comment by Conchipedia** [comment]
thanks for the answer,  i think it started with a suggestion by @metachronism in Discord, i will try and NOT use labels unless it really needs it, can see why you closed this as it can get a little bit confusing as its a question not an issue, but i will also try and put in the version i'm playing on (which normally is the current version 6.0.3) unless i get really bored on there i don't normally use the staging versions, unless something is really new coming then i try my best to test it.

**Comment by MarjieAVolk** [comment]
Yeah version is good.  I've been meaning to add an in-game bug report button that would have like a little form to fill out so people remember about that stuff.

**Comment by Conchipedia** [comment]
it can't hurt saves us trying to remember that long hex number :)
just have a tick box for latest release or staging plus other bits like Player, Admin, dev etc

**Comment by MarjieAVolk** [comment]
Well if it submits from in game actually it can add that stuff to the bug report automatically.  Would be pretty nice

**Comment by Conchipedia** [comment]
won't that be extra work for you guys?

**Comment by MarjieAVolk** [comment]
To make the in game bug report tool?  Yeah I mean we'd have to make it.  Won't be too hard though I don't think.

**Comment by Conchipedia** [comment]
if anyone can you guys can <3

**Comment by MarjieAVolk** [comment]
awwwww
