### ISSUE TITLE
Tree debris doesnt block new tree growth.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2793]

**Comment by MarjieAVolk** [comment]
The trampled biome should reduce the amount of plants that can grow.  (Tree debris shouldn't necessarily always prevent all plants from growing).

**Comment by MarjieAVolk** [comment]
I believe you've already fixed this @knexer ?

**Comment by knexer** [comment]
This is fixed, yeah
