### ISSUE TITLE
[Suggestion] Sinkholes and Water Leaks!

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2797]
So we have two different types of disasters at this moment and one of them turning the planet into a wasteland and the other floods everything. Why not add sinkholes if you mess around too much underground without building proper supports. 
And with sinkholes in place, Having pipes with a % of a quality when made will determine the chance of it leaking and so if it does, it will cause a sinkhole if underground in the end.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#351
