### ISSUE TITLE
[Suggestion] Item Quality!

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2798]
There's been one thing I've been wondering about for a little. Would it work to have item quality?
To explain it simply, if you craft something we say a wooden chair without any special skill or such you will receive low item quality and the more you craft within the same item class for this example wood, like table or anything else you will gain specialization on but the learning speed of that specialization can be affected depending on your efficiency and speed skill combination.

Making this "Specialization" system it's own from the skill system where you have to start crafting stuff and such.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#350
