### ISSUE TITLE
Transmission Poles are not in the tech tree

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2799]
The object and art exists, but you can't create them in game etc.

The mod files should be autogen'd etc.

**Comment by Dr-Hardware** [comment]
find me on discord if you want that file Meta, we've had it created and running for a while now.

**Comment by elfl0rd** [comment]
@D3nnis3n in 0.8 - more electrical machinery... Not bad if poles included to 0.8 or 0.8.1...

**Comment by WeaselDog** [comment]
Should not rush to add them until this is addressed: https://github.com/StrangeLoopGames/EcoIssues/issues/12483

**Comment by WeaselDog** [comment]
They have been added now.
