### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#28]
actually I think it's a little more complicated then that.
the password encoding algorithm seems to be different depending on where you setup your account from.

If you click reset password and set a password that way you can't use it to login to eco. Once logged in on the website you can edit your password but you won't be able to login on the website, you will however be able to login on the eco servers.

http://ecoforum.strangeloopgames.com/topic/414/cant-login

**Comment by rainfarmer** [comment]
Fixed.
