### ISSUE TITLE
[Art] Fishery has no design Artwork 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2803]
i searched in github for this and couldn't find anything open or closed
 (so hoping not somehow duplicating this)
![snap118](https://user-images.githubusercontent.com/29383891/32683401-d4ee1654-c672-11e7-99bd-bffbdae122f8.png)
as you can see its just a plain white box with X,Y,Z on it
it works fine as a table, all the inside stuff is there (just no design for the surface)
![snap119](https://user-images.githubusercontent.com/29383891/32683459-395e77be-c673-11e7-942b-d8c073cf3757.png)
Am using the extra [Art] in title as that all seems to be wrong with this

**Comment by elfl0rd** [comment]
@D3nnis3n fixed.
