### ISSUE TITLE
owning more than one mint wont allow making of the same currency 6.0.3

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2806]
i have a mint on the surface in my house/store/bank so players can come and deliver gold and i can make the chosen currency, but due to the fact i have gold underground which is over 100 levels lower i was going to make a mint down there to save myself the hassle of moving MY gold ore/ingots up to the one on the surface but at the moment if i move the mint (we have had this problem before) the Currency can break and we have to start again with a NEW Currency and all the currency in circulation would be wasted (this could be fixed when the new currency exchange is up and running) but for some reason (not sure why this would be) if i have more than one mint owned by me on the same Deed i cannot choose to make the same currency in another mint (i think i get some of the reasons behind this as you wouldnt want other players making the same currency as you at their own mints) but if the mint is on my land wouldnt it be possible to have it make a check to say Conchita owns this Mint is Authorised to use this Mint and has chosen to make a currency called Greenleafs ?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#348
