### ISSUE TITLE
[Suggestion] Giving more control and information in server for Admin

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2808]
Expanding on a comment i made in another Github (just in case this was overlooked)
----------------------------
https://github.com/StrangeLoopGames/EcoIssues/issues/2760
----------------------------
i think we might also need a better way of detecting/showing "Deed" names, as the only way of finding name of a deed is to either log on to the server and manually drag around the world map, highlighting each highlighted deed on map (showing the name) or using the map option in the graphic web browser that displays a map and doing the same, and there is no way a Cart deed can ever be found. (especially if a player doesn't play any more)
Possibly adding an option in the Server itself to display "All deed names" of both carts and claimed land with possibly an option for The Server Admin to rename them , as often people Might use rude names. Maybe even allow the viewing names of tables and especially carts (as i have once seen a cart with the name "penis") which thankfully was found as all deeds was removed when the World was checked and cleaned up for the entry to "PAX 2017"
The names of Deeds,tables,storage, and text in signs and on carts MUST be stored somewhere, so giving this EXTRA control or Information to a Server Admin will NOT do any harm, maybe even help the poor teachers whose "lovely" pupils will insist on creating "rude names" for most things if they have that option (i know i was once a "lovely" pupil and MIGHT have done that myself)

NOTE: also the extra control on Deeds Server side would make it easier for the "admin" to be able to remove Claimed land or get control over it for players that Don't play anymore . (the only way we have at the moment for an Admin to change something on a players Claimed area is for the player to add the Admin to a deed) 

Maybe also a way for deeds/claimed land to become FREE if a player hasn't logged into a server for over a week this would help other players that get blocked in by inactive players (with the option for Admin to turn this on/off and adjust the time)

This Suggestion i think deserves more comments and discussion from both Players/Admins and Developers. (because as a player i can see some problems that Admins often face, but Admins and Developers may see other issues that i cannot see) 

Also Some Admins or hosters of Server do not have the time to come into the game itslef and search physically for possible problems

Hoping this will not be closed and dismissed as an unimportant Suggestion, this i feel also could be important for the Schools as the more control they have over how the children play and learn here would seem to be a very basic thing that teachers need.

Apologies if this may seem a bit long winded but i do think this is important, and a place for a discussion and ideas as a lot of people involved in Eco (one way or another) do read these github's more than Discord and the forums.

Going to try and have Comments after as Suggestions (to possibly pick out separate points to make the desired powers a bit clearer)

**Comment by Conchipedia** [comment]
Suggestion 1:
Ability For an Admin to see inside Storage (Chests and Stockpiles) and to Modify Content Without Having to be inside the game.

**Comment by Conchipedia** [comment]
Suggestion 2:
Full Control Over ALL Deeds (land or Cart ) (Handy for viewing and changing names, if they happen to be offensive or any other problem that might arise from the name) without Having to be given Permission (with the option possibly to turn on and off)

**Comment by Conchipedia** [comment]
Suggestion 3: On Deeds have the option to make it Become FREE after a Default Period of 7 days of a player being Offline (with possibly the ability to change the amount of time, also turning this on and off)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#347
