### ISSUE TITLE
power requirements/use fluctuating

### ISSUE THREAD

**Issue by peternightingale** [StrangeLoopGames/EcoIssues#2810]
My factory is drawing power from the grid intermittently, even when not crafting. It is draws for about a second, then does not draw for 1 second, and loops like that. First item I placed that needed power, and I could see the demand fluctuating even before I placed a generator.

Using staging fc7c8529

**Comment by peternightingale** [comment]
After further review, it seems that everything that consumes electricity is fluctuating whether it is crafting or not. I have placed several streetlamps, and they are fluctuating between requiring power or not, which means even if I have my generators turned off, they will still illuminate intermittently.

Similar to #2551 except with electricity instead of mechanical power.

**Comment by MarjieAVolk** [comment]
This seems to be working now - Think this was fixed here: https://github.com/StrangeLoopGames/Eco/pull/1965
