### ISSUE TITLE
Property Claims audit log

### ISSUE THREAD

**Issue by Ronnie21093** [StrangeLoopGames/EcoIssues#2811]
Can we possibly get a "Claims" layer to see how claims expand and who owns what claims? It would be useful for providing proof of someone claiming an area and then griefing that area in case an admin cleans up the mess before taking screenshots.

**Comment by knexer** [comment]
I don't think we should use world layers for this - they're specifically meant to be more of a tool for ecosystem and climate simulation - but it would make sense to have a bit more auditing on some of that kind of stuff.  I wonder if the stats database has information on historical claiming and unclaiming of property with appropriate context?

Also, renaming the issue.

**Comment by MarjieAVolk** [comment]
Yeah agreed, should not be a world layer, but it might be cool to be able to play an animation of property somehow.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#346
