### ISSUE TITLE
[Suggestion] Rails & Trains

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#2812]
Is adding trains into Eco could be something that will add value to the game?

![image](https://user-images.githubusercontent.com/7052045/32739706-b17f342a-c86e-11e7-9d78-aa0f03d8fd7f.png)
Credit: http://traincraft-mod.com/
![image](https://user-images.githubusercontent.com/7052045/32739756-dcab4f62-c86e-11e7-9205-7c3d203a4cf9.png)
Credit: http://traincraft-mod.com/

**Comment by Nanders** [comment]
Those are awesome screens

**Comment by knexer** [comment]
What Minecraft shader mod is that?

**Comment by fillion07** [comment]
@knexer Traincraft ^^

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#345
