### ISSUE TITLE
Chat message time not showing sometimes

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2813]
![image](https://user-images.githubusercontent.com/23460210/32742915-ace9df14-c85f-11e7-8c7a-7540668f56d2.png)

**Comment by Conchipedia** [comment]
i wondered where this screenshot went, I somehow managed to turn on/off that D20 Time bit somehow with i think a key press, is there a hidden one like we have for UI (ALT Z) because i have hot keys for my Screenshot program, and usually after i use that it might appear

**Comment by MarjieAVolk** [comment]
Oh, I left a message on the other bug, but then I deleted it.  Thought you would get the email.  Sorry about that

**Comment by MarjieAVolk** [comment]
There is no key to control this, it's only based on when the message is sent.  Actually it looks like it only shows the time sent for older messages, if you log on and see messages > 10 minutes old.  Which is kind of odd behavior

**Comment by Conchipedia** [comment]
no problem
nobody has really seen this D and time come up (or didn't notice) i see it come and go and thought it was me turning it on and off

**Comment by Conchipedia** [comment]
i see it come and go when i'm logged in (without logging on and off)

**Comment by MarjieAVolk** [comment]
hm okay

**Comment by Conchipedia** [comment]
i wasnt sure where to put this thats why it went in that OLD open github, as i thought it was being turned on/off via keys, so it looks like it might be something else, thanks for replying <3

**Comment by MarjieAVolk** [comment]
Yeah if it's not the same issue then it should be a new bug.  Thanks for playing :)

**Comment by Conchipedia** [comment]
i'm sometime not sure about some issues/bugs i try and search to make sure i'm not duplicating any, and if i think its related to something i will try and comment in them, but i'm glad you are on the ball and check, and made this a separate issue (and you cannot keep me away from ECO )

**Comment by WeaselDog** [comment]
I have never seen these D20 times. Is this still a thing?

**Comment by Conchipedia** [comment]
why sometimes do we get these times?
its not on every load of a server

**Comment by SlayksWood** [comment]
It seems that time is shown only in the chat history. If you write message, then time absences:
![image](https://user-images.githubusercontent.com/45708377/71507889-078bda00-2897-11ea-95f4-7587730fc63b.png)
![image](https://user-images.githubusercontent.com/45708377/71507899-12df0580-2897-11ea-8a34-630409c10edc.png)

**Comment by WeaselDog** [comment]
Will be redone with chat refactor
