### ISSUE TITLE
Server deletes message log history from save files on each restart

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2814]
Server should keep a copy of the message log even after a restart with all message like land mark post etc ( message logs are important because they can provide important information when greifing / harassment happens on a server) 

Message logs should also not save profanity as ****** but as clear text instead in the server logs

**Comment by Arend90** [comment]
******** ***** **** ******

**Comment by MarjieAVolk** [comment]
Hm, it shouldn't be deleting messages, if it is that's a bug.  But it won't show the whole chat log on the client, only the latest 1000 messages is what you should see when you log in.

Do you know about the chat export feature?  It's a menu option in the server window.

**Comment by noblackthunder** [comment]
Digging into it and playing around it seems that the LoadOrCreate new function seems to not work as it should . 

when the file shoult load it fails on 
                    using (var stream = entry.OpenReader())  
                    { //code her }
                    entry.openReade / stream fails with ReadTimeout = 'stream.ReadTimeout' threw an exception of type 'System.InvalidOperationException'

i guess thats causing the creation of a new chat file

**Comment by ClayC90** [comment]
MarijeAVolk, 
Leave this one to me, I am adding more features to the chat, while at it I will fix this one aswell,

Thanks,

**Comment by MarjieAVolk** [comment]
My server is loading chat messages on restart as expected.  So not sure what's different.  Deprioritizing this for now, especially since CalyC90 is apparently working on it.

**Comment by metachronism** [comment]
closing as no repro
