### ISSUE TITLE
Law web UI doesn't handle this format string with a list correctly

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2823]
`"<this type=\"list\"><section><child field=\"Result\"></child></section>"`

![image](https://user-images.githubusercontent.com/23460210/32812182-a48c12d4-c958-11e7-8f00-bb8c2a4aa90b.png)

UI shows first list title, then 'Result' child, then the rest of the list content.  It should show all list content, then 'Result' child. (eg. the Accept Contract line should be on the same line as "When attempting to")

**Comment by MarjieAVolk** [comment]
Both of these law UI issues are easily reproducible on branch marjie-statDatabase - if you want to fix them on that branch, that might work out well.

**Comment by MarjieAVolk** [comment]
This is how this bug is manifesting most obviously on marjie-statDatabase now:
![image](https://user-images.githubusercontent.com/23460210/33098863-a425bd3e-cec3-11e7-8d91-42ee4eb702ab.png)

It should say "When attempting to Accept Contract (all) Allow", but instead it has "Accept Contract (all)" at the bottom.

This has happened for every case where I tried to use a format string similar to `"<this type=\"list\"><child field=\"Result\"></child"` - that is, a list tag, followed by any other content.

**Comment by syuzan-yeranosyan** [comment]
fixed on 'marjie-statDatabase' branch
