### ISSUE TITLE
Law web UI doesn't handle this format string with a plaintext prefix correctly

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2824]
`"(<this type=\"dropDown\"> <child field=\"SelectedData\"></child>)"`

Every time I change the selection of "<this type=\"dropDown\">", another "(" is added into the string
![image](https://user-images.githubusercontent.com/23460210/32813937-99f4a878-c961-11e7-9d63-6955757b334c.png)
![image](https://user-images.githubusercontent.com/23460210/32813970-b81ea024-c961-11e7-8521-5436af48ad89.png)

**Comment by MarjieAVolk** [comment]
Refreshing the page resets to the correct # of '('

**Comment by MarjieAVolk** [comment]
Both of these law UI issues are easily reproducible on branch marjie-statDatabase - if you want to fix them on that branch, that might work out well.

**Comment by MarjieAVolk** [comment]
This is how the bug is manifesting most obviously on marjie-statDatabase now:
![image](https://user-images.githubusercontent.com/23460210/33099009-309eda70-cec4-11e7-815d-c979982796e8.png)

Start with the default law draft.  Change the "(All)" drop down to "where".  Change the 'performed by' drop down to any other value.  There should always be 1 open parenthesis '('.  Instead, every time the drop down with 'performed by' is changed, a new '(' is added.

![image](https://user-images.githubusercontent.com/23460210/33099091-8473879a-cec4-11e7-9c43-19220cc79fb5.png)

**Comment by syuzan-yeranosyan** [comment]
fixed on 'marjie-statDatabase' branch
