### ISSUE TITLE
[suggestion] having Version number appear in ECO Configuration window

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2826]
![snap148](https://user-images.githubusercontent.com/29383891/32846725-eeeab296-ca1f-11e7-8287-345e51938684.png)

I normally have more than one version of Eco on my PC and the only way i know what version it is that i have chosen is when the main window comes up 
![snap149](https://user-images.githubusercontent.com/29383891/32846741-f7638902-ca1f-11e7-8556-3014ac4d0234.png)

This extra info can't hurt

**Comment by Nanders** [comment]
This window was killed, is now displayed in escape menu
