### ISSUE TITLE
A5885a30 picking up stones from other players land 

### ISSUE THREAD

**Issue by Hanan09** [StrangeLoopGames/EcoIssues#2829]
in A5885a30 I can pick up stones from other people land while I'm not on their deed, not sure if that works with ore

**Comment by Conchipedia** [comment]
i think the loose ore and stone is not classed as owned

**Comment by Hanan09** [comment]
if it is,  why wood pulp classed as owned? :\

**Comment by Conchipedia** [comment]
because debris (wood pulp) never moves (and is shown on mini map as stationary), Stone/Coal/Ore Rubble has a life of its own and can move anywhere it so desires on redrawing of the world when a player logs in

**Comment by MarjieAVolk** [comment]
Yeah we just discovered this yesterday, haha.  There's already a fix written, not released yet obviously
