### ISSUE TITLE
Currency Exchange Invisible 6.1.0

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#2830]
Just converted to the new version from 6.0.3, currency exchange is invisible and can't be placed or used.

**Comment by MarjieAVolk** [comment]
The Currency Exchange was invisible while I was trying to place it, but after I placed it, it worked fine.

**Comment by goertzenator** [comment]
The behavior MarjieAVolk describes was also present in 6.0.3.
