### ISSUE TITLE
Law drop downs with a lot of options go to the edge of the page

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2834]
I noticed it looked a little funny with the drop down going up over the browser nav bar.  Maybe the drop downs can have a maximum height?
![image](https://user-images.githubusercontent.com/23460210/32910124-4553387c-cabd-11e7-835a-79c82e8903b8.png)

**Comment by syuzan-yeranosyan** [comment]
On web-develop branch
