### ISSUE TITLE
6.1.0 falling through the ground, serve crash

### ISSUE THREAD

**Issue by goertzenator** [StrangeLoopGames/EcoIssues#2835]
I just upgraded my 6.0.3 server to 6.1.0 and am experienced severe problems:

1. The server updated the world and started without error.
2. Upon joining with my client, I fell through the ground and landed on a dirt plain some distance down.
3. Rock debris continuously rained down around me.  Rocks would fall through the dirt plain I was standing on and then fall again.
4. I took a short walk around and saw carts and an excavator fall.  These stopped at the dirt plain I was standing on however.
5. Another user who logged reported the absence of trees.

I then tried my the upgrade again by wiping the 6.1.0 world and putting the 6.0.3 world back in:
1. The server updated the world and started without error.
2. After about 15 seconds I closed the server.
3. Upon restarting the server I was greeted with:
![image](https://user-images.githubusercontent.com/605072/32910075-e02513ce-cacd-11e7-89c0-d1c01e00d552.png)

See [Game.eco from 6.0.3](https://www.dropbox.com/s/emvwrntw906v37a/Game.eco?dl=0)

**Comment by metachronism** [comment]
try letting the server stay up for ~60s before closing after the first load

**Comment by goertzenator** [comment]
1. I started the upgrade again with the 6.0.3 world.
2. I waited 2-3 minutes before shutting it down.
3. Upon restarting I now get this:
![image](https://user-images.githubusercontent.com/605072/32910906-28815ea0-cad0-11e7-90f7-b3d4f8edb484.png)

4. Restarting again yields the same error.
