### ISSUE TITLE
Crash when placing blast furnace

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2837]
System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
>	Eco.Gameplay.Wires.WirePlugin.GetStatus() Line 29	C#
 	Eco.Server.PluginManager.GetPluginsStatus() Line 217	C#
 	Eco.Server.PluginManager.GetDisplayText() Line 236	C#
 	Eco.Server.UI.ServerMainForm.BuildDisplay.AnonymousMethod__0(obj2, args2) Line 120	C#

**Comment by metachronism** [comment]
no repro
