### ISSUE TITLE
Allow contracts for single individuals, in which case it allows specifying stuff they own.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#2841]
Make a formal process to owner to request some action be taken on an object on property that you do not own.
Example Situation: You own a store on a popular route. Person B owns property at the edge of your property, and leaves tree debris, and logs and stone lying around, somewhat obstructing the best walking path and decreasing aesthetics.
Proposal: You should be able to "take out a contract" on the items you don't own, where you message the owner, ask them if they will clear out the specific selected items, and be able to offer to pay them for doing so.

**Comment by johnkslg** [comment]
Pushing to post beta

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#344
