### ISSUE TITLE
trees acting weird

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2845]
Chopped down a tree  it fell to the ground and  disappeared but it left all the wood pulp. So i chopped down another it fell down cut it up picked up 10 wood took them home came back and nothing but wood pulp rest of tree missing

**Comment by MarjieAVolk** [comment]
"Repeatable on our server. Server opened 9th Nov 2017 (v6.0.3) and we just updated to v6.1.1. When trees are cut they are repeatedly completely vanishing. Sometimes I cut a tree and it vanishes immediately after falling. Sometimes it vanishes while in the middle or chopping into smaller logs. Can provide more examples if needed.

short version of the bug
https://www.youtube.com/watch?v=tSjBjCHXmDQ&feature=youtu.be

long version (restarting client does nothing)
https://www.youtube.com/watch?v=AgUcuQXJq3Y&feature=youtu.be

Settings I use:
https://i.imgur.com/Fjvtt2G.png"

-- @brad992
