### ISSUE TITLE
We all float in here

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2846]
Why are we floating and bobbing like a cork? I can no longer sink the bottom  i just float. need to make a way you can dive under water to work

**Comment by Dr-Hardware** [comment]
Control key to dive, Space to surface.   Can't swim with no Calories, Uses extra Calories while underwater.

**Comment by MarjieAVolk** [comment]
Yes, diving now costs calories, thus why you float by default.  The controls may be unclear, hopefully that sort of thing will be fixed along with https://github.com/StrangeLoopGames/EcoIssues/issues/2776
