### ISSUE TITLE
Adjust the display of time

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2847]
change all things displayed as "days" to the player to instead be "years"
by default 1 game year = 1 real world day

**Comment by MarjieAVolk** [comment]
Where do we display the word days?  Is it just skill points per day?

**Comment by metachronism** [comment]
yeah its just SP/day now
we might want to add a year indicator after we do this somewhere

**Comment by metachronism** [comment]
passing this off to craig/john
things in game referring to "days" consistently is confusing to new players who assume that is in-game days

**Comment by johnkslg** [comment]
Closing for now, may readdress later.  Problem is that scale is different for lots of things: real time, plant growth time, research advancement time, etc
