### ISSUE TITLE
right clicking w/ seeds equipped throws server exception

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2848]

**Comment by MarjieAVolk** [comment]
:O probably a side effect of my right clicking to eat food

**Comment by tkerkering** [comment]
I don't know if this belongs here, but if I m2 with a tree seed in my hand on ground that wasn't
prepared with a hoe before, it crashes me to the main menu.

**Comment by MarjieAVolk** [comment]
yep same bug

**Comment by MarjieAVolk** [comment]
Fixed in staging
