### ISSUE TITLE
Server restarts break rooms

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2850]
Arend - GreenLeaf Servers - Today at 1:41 PM
Hey SLG Restarts break the rooms saw somebody say this before but i can comfirm :smile:

**Comment by Arend90** [comment]
as they break house items like chairs and tables has to be placed again (at least one) to get the bonus again

**Comment by johnkslg** [comment]
Verified this is fixed and working in staging.
