### ISSUE TITLE
Fuel inventory displayed strangely

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2851]
On the excavator I was able to see the fuel inventory from the storage tab, and when I put gas in there it disappeared, but was still visible in the fuel tab.
![image](https://user-images.githubusercontent.com/3536496/32971774-aa1f0452-cba3-11e7-87c6-3930cac96547.png)

**Comment by MarjieAVolk** [comment]
Hrm, that's basically how the fuel supply works though.  The current fuel isn't in the inventory.

**Comment by Dr-Hardware** [comment]
a second gas can would have remained visible.   what is strange about those screenshots is that the excavator storage is actually duplicated.
