### ISSUE TITLE
Add a menu option to the server window to save and exit

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2853]
There's not really a clear way to shut down a server.  It's also not clear whether 'save and flush' has completed successfully or not when you select it.  A 'save and quit' option would solve both of these problems

**Comment by metachronism** [comment]
save and flush is a blocking call (so its done more or less really fast), plus the server saves every 60s, and the GUI isnt intended to be final, so closing this
