### ISSUE TITLE
Trying to run for office with user not from server - missing error message in api

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#2854]
Trying to run for office with user not from server or not logged in.
Error message is "Object reference not set to an instance of an object."

query and response:
https://gyazo.com/8583398deaa01da98827218c7b15c26b

**Comment by MarjieAVolk** [comment]
Looks like I already fixed this one, along with the similar issue you filed earlier.  Should be fixed on master.  Are you still seeing it?
