### ISSUE TITLE
Status tab Displaying Tier#+ instead of Required Blocks 6.1.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2855]
Table requirement is logs but saying this:
![snap171](https://user-images.githubusercontent.com/29383891/32976010-5b4bfaac-cc06-11e7-9785-62182ac0ea5d.png)
Table requirement is Brick but saying this:
![snap170](https://user-images.githubusercontent.com/29383891/32976011-691aa746-cc06-11e7-9623-13a691b39b95.png)
Mortared Stone is Correct as shown:
![snap172](https://user-images.githubusercontent.com/29383891/32976028-aa6c8e8a-cc06-11e7-9d2a-18538fec9532.png)
Havent got High enough to check other table requirements (think its just logs and Bricks so far)

This is checked on thel tables i can craft that need logs (so far)

**Comment by Conchipedia** [comment]
This is confusing Newer Players (not knowing what the required block for the table is)

**Comment by julrich1** [comment]
I suggest having a tier tooltip that lists all the materials in a particular tier. Otherwise I don't see how a player would know what tier a material falls into.

**Comment by Conchipedia** [comment]
if you hover the mouse pointer over the Word Tier, it shows what it is and what's in it (6.3.0)

**Comment by MarjieAVolk** [comment]
Yes this feature is already implemented now, hopefully that addresses your problems
