### ISSUE TITLE
Picking up rubble on my land getting Notification:Unauthorised to do this  (6.1.1)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2856]
In my Mine (My Owned Land) picking up rubble, but getting Annoying Notifications saying Unauthorised to do this on (Wizz'z property), but i can still pick it up.

![snap174 edited 2](https://user-images.githubusercontent.com/29383891/32976941-99887304-cc1a-11e7-8c64-0908ff775542.png)

NOTE: Wizz was the last person to claim land on the server, before this had no problem.

Edited Snapshot with text showing my Property and Wizz's

**Comment by MarjieAVolk** [comment]
Think a fix for this is already being worked on

**Comment by MarjieAVolk** [comment]
Fixed in staging
