### ISSUE TITLE
Unable to make Enigneering Skill Book

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2858]
It states "Time:0 Resources:100%
below it shows a timer 15M but 30 minutes later no change. I canceled took stone out of stock pile and restarted so now it say i need stone gave it stone and it now says same thing but still wont make the skill book  The box with 15M never advances or shows any activity

**Comment by Dr-Hardware** [comment]
what does the status tab show?

**Comment by cuda70** [comment]
18/18 tier 1 material 
contained within a room
50m/195 used by objects in room: research table

**Comment by MarjieAVolk** [comment]
Could you share your save file?

**Comment by MarjieAVolk** [comment]
Closing due to no repro/no response/out of date now probably
