### ISSUE TITLE
Crash on Combustion Generator placement

### ISSUE THREAD

**Issue by juur** [StrangeLoopGames/EcoIssues#2859]
Whilst trying to place a Combustion Generator in 6.1.1, item was built in 6.1.1. World config files from 6.1.1. World converted from 6.0 -> 6.0.2 -> 6.0.3 -> 6.1.0 -> 6.1.1. No 3rd party mods.

> [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at Eco.Gameplay.Components.PowerGridComponent.Tick () [0x00030] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at Eco.Gameplay.Objects.WorldObject+<>c.<TickComponents>b__172_0 (Eco.Gameplay.Objects.WorldObjectComponent x) [0x00000] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00035] in <1fd744d936be4a229b315d57c3b96c68>:0
>   at Eco.Gameplay.Objects.WorldObject.TickComponents () [0x00006] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at Eco.Gameplay.Objects.WorldObject.Tick () [0x00000] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at Eco.Gameplay.Objects.WorldObjectManager.TickObject (Eco.Gameplay.Objects.WorldObject worldObject) [0x00032] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T] (System.Collections.Generic.IEnumerable`1[T] enumeration, System.Action`1[T] action) [0x00010] in <344444b5605740a098c202c5686efa4b>:0
>   at Eco.Gameplay.Objects.WorldObjectManager.Run () [0x0011c] in <a060bbd4a491443a91e1e95ae409b063>:0
>   at Eco.Server.PluginManager+<>c__DisplayClass16_0.<StartPlugins>b__0 (System.Object x) [0x00000] in <6041093ff0f24defaf2a3b54d30c56fc>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x0002c] in <1fd744d936be4a229b315d57c3b96c68>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <1fd744d936be4a229b315d57c3b96c68>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <1fd744d936be4a229b315d57c3b96c68>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <1fd744d936be4a229b315d57c3b96c68>:0
>   at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00012] in <1fd744d936be4a229b315d57c3b96c68>:0

**Comment by MarjieAVolk** [comment]
Hm, haven't seen this exactly, but I have seen a slightly different exception in FuelConsumptionComponent.Tick after placing a Combustion Generator sometimes.  I guess it's the same thing probably?  Tick happening too soon after placing it or something.  Or initialization taking too long before the tick happens.

**Comment by MarjieAVolk** [comment]
I committed a fix for this, will be available in next staging release... hopefully it actually fixes it, if not please reopen this.
