### ISSUE TITLE
Cannot purchase

### ISSUE THREAD

**Issue by Izunundara** [StrangeLoopGames/EcoIssues#286]
Site seems to be requesting the Paypal Sandbox instead of normal Paypal. Need to fix the links on the site.

**Comment by rainfarmer** [comment]
Thanks, just switched to our new server. forget to change that. updated now.

**Comment by Izunundara** [comment]
Thanks, because I've been following this game for a while now and today I just decided "I WANT TO GIVE YOU MY MONEY" but it literally wouldn't let me XD
