### ISSUE TITLE
Extremly long loading times (ref greenleaf server ) 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2865]
loading times can be over 3-10 minutes when loading times where allot faster before

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33153265-55b757f6-cfe1-11e7-8a94-73d9a18f72cb.png)
is 250 normal? before it was less i think

**Comment by knexer** [comment]
Main contributors from the above ss:
WorldPlugin takes 140s
EcoSim takes 62s
World layers take 17s

Ran a copy of the greenleaf through the profiler on my machine... it only took 70 seconds to start the server but the time spent in each plugin was (very) roughly in the same proportions.

I am having a lot of trouble interpreting the profiler results for this though... VS profiler can't follow our server init code I guess :/  It does appear that it might be thawing and refreezing the same chunk multiple times during the init process.

**Comment by metachronism** [comment]
this was an intentional change.  lots of things have to be "fixed up" on initial server load, and that can take some time
