### ISSUE TITLE
Invisible saplings - Cant dig up dirt with shovel 

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2866]
I am stuck unable to expand my house. I dug up a long patch of dirt 40X30 all is clear and flat but 5 blocks of dirt when i try to dig them up says "unable to move roots are too strong" these blocks are not next to each other and the ground around them is 1 block lower no plants or trees anywhere near them or on top of them

**Comment by Dr-Hardware** [comment]
they are re-growing tree saplings.   sometimes these glitch and are invisible.   i suggest placing  dirt on top of the block.  if you can't, place a pillar of dirt next to  them, which will enable you to place dirt above, which will then fall onto the top of the block.   this should delete the sapling and allow you to dig out the original dirt block

**Comment by MarjieAVolk** [comment]
@SeanAtr0n @metachronism Didn't one of you fix something like this recently?

**Comment by metachronism** [comment]
this is fixed in 6.2
