### ISSUE TITLE
Chopping trees can make them explode

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2868]

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33044459-5829f9d8-ce49-11e7-9705-6cb600035dde.png)
 
this tree "bottleflipped" form over the grass there in the background

**Comment by SeanAtr0n** [comment]
Notice anything unsual about the tree before that happened? not much to work with here... guess the game save might help if the tree still exists in it

**Comment by Arend90** [comment]
not really was a full grown tree maybe we where standing to close and it got against the player and flew away

**Comment by Phlo123** [comment]
Greenleaf main server save.
Hope it helps.
https://www.dropbox.com/s/20cc59e7zo3t9af/Game.eco?dl=0

**Comment by noblackthunder** [comment]
Could this be related to the same issue that people report where trees disappear ?

**Comment by ECO-ExPLiCiT** [comment]
I notice this when the tress are too close together and the tops are colliding. 

The one that is bugging me the most is when the logs won't chop down to the point of being outlined in green where you can pick them up but stay yellow and then sometimes just disappear when chopping.

**Comment by SeanAtr0n** [comment]
Found the tree and inspected it... looks like it was ~98% fully grown so I suspect tree colliders might be misaligned at some growth percents

**Comment by SeanAtr0n** [comment]
Nick just did a bunch of work on some tree tools, maybe he can figure this out.

**Comment by ECO-ExPLiCiT** [comment]
I think I may have found a clue that may lead to finding solution. The problem trees seem to be mainly, if not exclusively, tied to ones that transferred over from 6.0.3. I have not had any problems in an area where I cleared out all the trees and then re-harvested them but I do have issues on cutting down trees that I have not cut down since I updated the server to 6.1.1.
