### ISSUE TITLE
Add ability to mark species as 'Filler' or something

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2871]
Eg. CommonGrass, and now possibly Waterweed.  Various things such as the welcome message and the web graphs manually exclude CommonGrass.

**Comment by knexer** [comment]
So how exactly do you see filler species differing from non-filler species?  Is it purely a display thing, or would their involvement in the ecosystem be different as well?

In some ways, this already exists - CommonGrass is alone in its own PlantGroup, and the argument could be made that waterweed belongs in that group as well.  I've removed plant groups on my branch, but even after that they'd be unique in that they don't occupy space on the ShrubSpace world layer, only on the FertileGround layer.

**Comment by MarjieAVolk** [comment]
They differ in that they're designed to visually fill up their particular biome, and not to really affect the ecosystem.  Thus most ecosystem analysis things don't really care about them, despite having the largest numbers and thus tending to be sorted to the top of everything without manual intervention.

Although now that I say that, maybe our analysis tools are not right, since really you want to keep a closer eye on things with smaller populations in general

**Comment by WeaselDog** [comment]
We could consider treating grass and shrubs differently for laws and actions, but for now we do not want plant species to be filtered out of the data.
