### ISSUE TITLE
placed the industrial furnace and is invisible and unremovable

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2874]
![image](https://user-images.githubusercontent.com/31536813/33051520-98c1ced2-ce6a-11e7-8850-72d5bf79a2b2.png)
the furnace is 5 meter infornt of me not removeble

**Comment by dmorchard** [comment]
This is still an issue in 6.1.2, and placed industrial furnaces cannot be interacted with via the E key... that's my experience anyways.

**Comment by keegan-o** [comment]
Should be back to having placeholder art in SVN now.
