### ISSUE TITLE
Crafting Stations not usable after server restart

### ISSUE THREAD

**Issue by S3D4T3** [StrangeLoopGames/EcoIssues#2876]
So far I have this this happen to a few crafting stations after a server restart and require to be picked up and placed back down.

Mint
Machine Shop
Kiln

This  meaning that under status it shows that you do not meet the room requirements.  Have double checked to verify that items are within the requested Tier of building pieces.

**Comment by craig-jong** [comment]
I can't get this to reproduce: is there anything special about the room that the objects are in?

**Comment by S3D4T3** [comment]
Brick building with mortared stone floors .. few windows and a door.  

This only appears to happen after a server crash or a restart cant confirm as generally the only time there is a drop on server is during an error or crash. 

Works fine for a bit then I need to pick up with hammer and replace back down to get working again.

**Comment by craig-jong** [comment]
The room isn't broken, though (you can still see the room information on the bottom left). It's just the detection on the world object, correct?

**Comment by S3D4T3** [comment]
Correct the room is not broken.. when looking at the status page of the
crafting station or world object it shows the items with a red X .. hit
with hammer to pick up and replace its all good

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SlayksWood** [comment]
Checked on 0.8.2.9. Wasn't able to reproduce. Seems fixed.
