### ISSUE TITLE
Combustion Generator placement cursor has weird offset

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2880]
When trying to place a Combustion Generator, the default placement and rotation is way off on the side of the player, so it's hard to tell where you're placing it

**Comment by MarjieAVolk** [comment]
When you rotate it it changes quite a bit, I guess the issue is that the canonical location is on a corner of this really large object, rather than in the middle

**Comment by SlayksWood** [comment]
Seems this issue is no longer occur. Closed for now
