### ISSUE TITLE
Chopping Trees can make them vanish

### ISSUE THREAD

**Issue by tkerkering** [StrangeLoopGames/EcoIssues#2881]
If I chop down a tree and not every branch breaks from the fall,
so one branch is still connected, if i hit the log itself it suddenly
vanish.

**Comment by SeanAtr0n** [comment]
Did you destroy the stump before this?

**Comment by tkerkering** [comment]
I'm not sure anymore and when I tried to do it again the branches always broke from the fall (wasn't able to reproduce it proberly). 
But I always destroy the stump before I handle the log so I guess I destroyed it before, yes.

**Comment by SeanAtr0n** [comment]
Will be fixed in 6.2
