### ISSUE TITLE
Saplings look too big

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2882]
![image](https://user-images.githubusercontent.com/774628/33100107-126a2c40-cec8-11e7-9b5f-9323bdf16d3d.png)
This apparently is a sapling that gets killed with one chop

**Comment by metachronism** [comment]
I think this is intended, though the animation could be tweaked

**Comment by MarjieAVolk** [comment]
Think those leaves should be smaller
