### ISSUE TITLE
Contract: Clause: Put Items in Container

### ISSUE THREAD

**Issue by Regitus** [StrangeLoopGames/EcoIssues#2883]
Version 6.1.1

The items of the clause are lost after a restart and the contract is listed as invalid.

**Comment by Regitus** [comment]
I have one thing to add here.

There is no Butchery Table in the list for this clause.
![butcherytable](https://user-images.githubusercontent.com/33863615/33231287-9f76b298-d1f2-11e7-8e33-462539880172.PNG)

**Comment by MarjieAVolk** [comment]
Butchery Table appeared for me on a save with everything researched.  I'm guessing you don't have Butchery researched in your save?

**Comment by Regitus** [comment]
At the moment of the screenshot the book was in the making(as you can even see in the screenshot). I need to take another look now.

**Comment by MarjieAVolk** [comment]
So yeah you didn't have it researched, so that's expected behavior

**Comment by MarjieAVolk** [comment]
Gonna delete unrelated comments

**Comment by LiaungYip** [comment]
Duplicate of #4129, which has since been fixed and closed.

**Comment by MarjieAVolk** [comment]
Thanks, closing in that case.
