### ISSUE TITLE
[Suggestion] Server generating Crash Report and sending it to SLG

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2888]
Would it be possible to have the option in the Server for when Server Crashes to Autogenerate a Crash Report and Automatically send this to SLG?.
I would like to see if OFF by Default and then ONLY Admins who know what they are doing can enable this option (to avoid SLG getting flooded with Errors that are caused by inexperienced Admins)

**Comment by MarjieAVolk** [comment]
Hm well I don't think we'd reeeally want automatic, but maybe we could write some kind of tool for packaging up crash dumps and opening github or something

**Comment by Conchipedia** [comment]
was just a thought, as i think sometimes when you read what was in crash not everything can make sense unless your a programmer

**Comment by Conchipedia** [comment]
anything that makes life simpler and gets you the Information you need is always handy

**Comment by pamduncan** [comment]
I know it was mentioned that it would be off by default and only admins that knew what they were doing could enable it, but how do you really control that - most Server Admins really think they know what they are doing and would turn it on and github would get spammed :0  .  Given that all you have to do is zip up all the crash logs and then drop them in a dropbox and link them to an  issue its pretty simple as it is.  It does mean that the person creating the issue and link does have to provide some information and the devs get some information.  Sometimes its better that things require people to take an active step or two to do something so they can impart the important information needed.  On top of that, in many cases the devs need the game save and follow up information as to what is happening and a big dump of crashlogs with no information about what was observed when the crash happened kind of leaves the devs in the dark :)

**Comment by Conchipedia** [comment]
maybe Make it like Apply for a Special Admin Licence that can Get you a key that will Unlock Special options, i'm sure that Normal players wouldn't even bother but Serious Admins might

**Comment by pamduncan** [comment]
There should be something I guess - just don't want to inundate the devs with more crash files then they know what to do with - or that they even have a symptoms of reports for.  I know that often we will get a server that will get stuck in a crash loop and produce 100's of crash logs before the admin notices it crashed and all of those going in to the devs without someone to tell them what the symptoms were or available to provide a world save - that is a lot of crash files to look through and you would have to check each one to see if it was all the same thing and i can see that really cutting into a devs time, especially if its an issue that the server admin knows what to do for it and can fix it and does not need the devs help.  The other things is that if the admin has to upload it to an issue they create or one that has been created it keeps it all together - like we are asked to not post multiple reports but to just post it all on one bug report not sure how a packaging tool would be able to to that as it would have to know what issue to post it too, so while it definitely could package up the crash report and a copy of the world save - it would still, I think, have to be uploaded by the admin so it got posted to the correct issue.  Maybe there is a way that a tool could also scan the issues for matches on symptoms maybe?

**Comment by Conchipedia** [comment]
So for example when a Server Crashes it generates a Crash Report, then an SLG released tool could then be run externally to scan this report and maybe give you the Exact Name of the reason for the Crash. this would Then Show up as the Title of the Issue (maybe even add the Version check of the Server), also maybe add a method to collect the Crash Report and World Save and Automatically Add this to a ZIP.
Example: 
Title (Crash found by package) (Version Found)
name of Zip (Crash)(version).zip
obviously allowing for the correct naming of zip files with no unusual Characters.

**Comment by metachronism** [comment]
we have support for this now, at least enough to close this bug out
