### ISSUE TITLE
[Suggestion] Cart parking area

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2889]
Maybe have an area like a stockpile size 5x5, that you drive your cart onto so its classed as parked (locked to that Area) as Carts NEVER stay where you leave them when you log off.
something like this
<img width="1280" alt="snap082 edited" src="https://user-images.githubusercontent.com/29383891/33158655-bdaecd72-d003-11e7-81c1-370f84422127.png">
This is obviously very basic, will leave the Artwork to the Professionals

reason for 5x5 i think that A powered cart Might fit on this area, maybe also make it for parking Excavator, but Not sure of the best size.

maybe start as a basic recipe for like the Stockpile flat design with the option to unlock later recipes and better designs later on so they have walls and maybe a roof.

**Comment by Conchipedia** [comment]
![parking-sign-k-7197](https://user-images.githubusercontent.com/29383891/33160490-d8a131d6-d014-11e7-9e1c-9dd1564a1a94.gif)

**Comment by brad992** [comment]
I like the idea

**Comment by pamduncan** [comment]
That is actually a great idea!!  We have made our own parking areas for carts but they are just paved areas and not something especially coded for carts so while they help the cart kind of stay where we leave it it does not always work and we still have to hunt it - but if there was a way to make parking zone like that that would 'hold' a cart so it did not go off on its own that would be really great.  It gets pretty frustrating to search carts down everyday

**Comment by Conchipedia** [comment]
i found a cart will stay in the exact same place even on a restart if i park my cart inside a room (obviously i sue double doors to get it in and out)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#343
