### ISSUE TITLE
Wood can no longer be obtained on our server

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#2890]
Please fix the tree disappearing bug, wood can no longer be obtained on our server. We have to cut 10 complete trees down just to obtain a minuscule amount of wood. This is destroying our forests for no reason and hurting our planet. It's getting really annoying that we cannot use wood anymore, a lot of recipes require wood and we are forced to not use them

Here is footage of multiple trees disappearing in a short space of time. No debris is around the trees as seen.
https://www.youtube.com/watch?v=KK1baORDuy8&feature=youtu.be

**Comment by SeanAtr0n** [comment]
This is already fixed in the current staging build. You can also avoid it by not destroying the stump until the wood is harvested.
