### ISSUE TITLE
Contract: Add/Remove Blocks

### ISSUE THREAD

**Issue by Regitus** [StrangeLoopGames/EcoIssues#2891]
The "Add/Removes Blocks" clause does not work for us if the property has more than 100 Mortared Stone. However, he recognizes less than 65 wood.

![Screenshot](https://user-images.githubusercontent.com/33863615/33189390-7912d3b2-d0a2-11e7-9250-5bdb5c9fc33d.png)

**Comment by WeaselDog** [comment]
Still an issue in staging-1565. It only counts blocks on the floor, not that are stacked.

**Comment by WeaselDog** [comment]
This will be fixed in the upcoming 9.5 release. Thanks for your report.
