### ISSUE TITLE
Planting trees issue

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#2894]
I am planting rows of trees and have found that there are invisible plants around the place that are preventing me from planting. I can locate the exact blocks that have the invisible plant but I cannot figure out how to remove the plant so I can plant a tree there. It keeps saying that there is a nearby plant when trying to plant the tree. 

This is in multiple places, can provide pictures and videos if needed

**Comment by MarjieAVolk** [comment]
I believe this has already been fixed

**Comment by metachronism** [comment]
should be fixed as of upcoming 6.2
