### ISSUE TITLE
Destroying a sapling - Dirt still believes there is a tree on it.

### ISSUE THREAD

**Issue by Regitus** [StrangeLoopGames/EcoIssues#2896]
I wanted to plant corn seed on a place where a tree sapling was before.
After destroying I could not plant a new seed. The soil sampler tells me there is a dead tree.

Digging up the dirt and put it back there did not help.

Already had another case like this yesterday and it was resolved after a server restart.
Picture 1: Dirt with "dead tree" on it.
![ecobaum1](https://user-images.githubusercontent.com/33863615/33231005-fefe5b9e-d1ed-11e7-9ee3-84d7022f4b4d.PNG)

Picture 2
I destroyed a sapling like this one.
![ecobaum2](https://user-images.githubusercontent.com/33863615/33231016-1c2d49fa-d1ee-11e7-9534-e5f370288dcf.PNG)

**Comment by pamduncan** [comment]
I can verify this happens fairly often now that we are doing a lot of farming - so we are clearing land and planting crops.  About every 10th tree or so we get a 'dead tree' that is not there but the block thinks it is.  You can remove the block and put fresh dirt down and it still thinks the tree is there.  Restarting the server does clear it so we have just been planting until we are done with that section pretty much - at least plan no more tree removal and then we restart the server and go back and plant where the dead tree was.  There does not seem to be an error log written in association with it.

**Comment by MarjieAVolk** [comment]
Fixed by PR ^ Fixed in next release
