### ISSUE TITLE
cart crashed server

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#2897]
![image](https://user-images.githubusercontent.com/31536813/33241780-fa30d5fa-d2ca-11e7-80b6-4dcdf7432461.png)
driving form 1500 to 0

**Comment by efflixi** [comment]
I had this same issue as well as my server being completely non-functional now after the cart caused it to crash.

I made the cart, put it in my inventory, chose a place to put it and as soon as i clicked to place it i was ejected from the server. The server runs on my home network so I looked at it and it was at the console, having crashed. I restarted the server but it simply crashed again and will not start up now.
![screenshot from 2017-11-26 22-52-55](https://user-images.githubusercontent.com/19391165/33263290-42983c9a-d337-11e7-85d0-7ee818be2b0c.png)

**Comment by SeanAtr0n** [comment]
The 2nd one looks like a different issue, moving efflixi's issue here https://github.com/StrangeLoopGames/EcoIssues/issues/2905

**Comment by SeanAtr0n** [comment]
Having a hard time reproducing this... any other details you remember?

**Comment by Arend90** [comment]
yeah its always on the same place
we drive form the 1500 point to the 0 point and you just jump in the air and your cart drives on
then it has to load that you at the other side of the world at 0 
and that takes to many time and it crashes

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33288415-7ef1c5c8-d3bc-11e7-86e2-65e584f94ffe.png)
`this speaks for it self

im not on the cart anymore its far away form me even droped true the world this time

**Comment by SeanAtr0n** [comment]
still having a hard time reproducing, you can make this happen regularly? can you do it with a wood cart or only powered cart?

**Comment by Arend90** [comment]
it happens more then often yes 
![image](https://user-images.githubusercontent.com/31536813/33340619-e3073fa0-d47c-11e7-97ad-b906e39f1369.png)
most of the time on this spot

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33401078-6a96326a-d558-11e7-84e0-fc3a45d41d73.png)

**Comment by SeanAtr0n** [comment]
It's still pretty unclear exactly how this happens, so more description would be helpful... I'm not sure what the last picture is supposed to be showing. Were you using /fly while driving?

**Comment by Arend90** [comment]
im just driving from 1500 to 0 and my caracter stays at 1500 cart goes to 0 and its all stuck

**Comment by Arend90** [comment]
maybe the crash and the freezing at 1500 to 0 or 0 to 1500 are not the same

**Comment by ClayC90** [comment]
SeanAltOn, I think logically this is what is happening,

The player co-ordinates (cords) are going to 0 as they should but the cart is being seen as 1501, than when you try to see if there is a block under it, you're looking for 1501 whatever cords are the rest.

Can you try to see while debugging if the cords are being updated properly when moving with powered carts from x-max to x-min and z-max to z-min?

I didn't look at code but I wanted to atleast help logically

**Comment by SeanAtr0n** [comment]
Yeah, the exception above couldn't be related to powered carts, that code only gets executed for wood carts.

Seems like the main complaint from this bug is about behavior driving across world borders. I'm guessing you are driving into unloaded chunks? (driving off the edge of the world?)

It seems like chunk loading is more heavily influenced by lag than it should be and chunks seem to get loaded even more slowly across world borders.

**Comment by SeanAtr0n** [comment]
already fixed, github didn't auto-close
