### ISSUE TITLE
have to eat a ridiculous number of berries in early game

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#290]
![image](https://cloud.githubusercontent.com/assets/3150561/16128535/ec095a0c-33b5-11e6-8c38-b9a973bd8389.png)

**Comment by craig-jong** [comment]
I guess it DOES say huckleberries, not huckleberry. I'll increase the calorie gain from eating them.

**Comment by metachronism** [comment]
you could also make eating them happen in bunches, like 300 calorie chunks or something

**Comment by craig-jong** [comment]
You still need to eat a lot, but I'm going to close this because early food is intentionally not efficient.

Can be revisited later.
