### ISSUE TITLE
Deed crash?

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2900]
I used a deed it crashed and now i can not enter the server
 i received this message after using the deed
Caught exception: Object reference not set to an instance of an object.

**Comment by MarjieAVolk** [comment]
When you say 'used' a deed, you mean you tried to open the deed window for that deed?  I don't suppose you got the full stack trace, apart from just "Caught exception: Object reference not set to an instance of an object."?

What happens now when you try to enter the server?

**Comment by cuda70** [comment]
I OPENED THE DEED (RIGHT CLICK) THAN I PRESSED CLAIM DEED THAN PRESSED ATTACH CURRENT PLOT AND CRASH TODAY I WAS ABLE TO GET BACK ON OK

**Comment by MarjieAVolk** [comment]
Aha okay.  While you're here, do you remember any details about where you were standing when you clicked Attach Current Plot?  Were you on claimed or unclaimed land?  Who did the land belong to?  Etc.

Regardless, I will start looking at this again.

**Comment by cuda70** [comment]
i WAS RIGHT NEXT TO MY STOCKPILE AND IT WAS UNOWNED LAND

**Comment by MarjieAVolk** [comment]
well, not seeing any problems with attach current plot so far.  This is going to be hard to look into without a crash dump

**Comment by MarjieAVolk** [comment]
Closing as no repro
