### ISSUE TITLE
Fish Trap Not even in Water Catches Fish (maybe New Flying Fish?) 6.1.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2904]
Spotted this mentioned in Discord so i thought i would see if this was Possible
![snap621](https://user-images.githubusercontent.com/29383891/33277200-b8525dbe-d38f-11e7-8d6f-34d0164e5a19.png)

**Comment by Conchipedia** [comment]
Still catching too many Fish in a short period of time Refencing https://github.com/StrangeLoopGames/EcoIssues/issues/2815

**Comment by craig-jong** [comment]
Should be fixed - there were a few fixes done to fish traps in the past.

World layer changes will require more anyway.
