### ISSUE TITLE
Place for admin to view list of property/object names

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2906]
@Conchipedia: "i think we might also need a better way of detecting/showing "Deed" names, as the only way of finding name of a deed is to either log on to the server and manually drag around the world map, highlighting each highlighted deed on map (showing the name) or using the map option in the graphic web browser that displays a map and doing the same, and there is no way a Cart deed can ever be found. (especially if a player doesn't play any more)
Possibly adding an option in the Server itself to display "All deed names" of both carts and claimed land with possibly an option for The Server Admin to rename them , as often people Might use rude names. Maybe even allow the viewing names of tables and especially carts (as i have once seen a cart with the name "penis") which thankfully was found as all deeds was removed when the World was checked and cleaned up for the entry to "PAX 2017"
The names of Deeds,tables,storage, and text in signs and on carts MUST be stored somewhere, so giving this EXTRA control to a Server Admin will NOT do any harm, maybe even help the poor teachers whose "lovely" pupils will insist on creating "rude names" for most things if they have that option (i know i was once a "lovely" pupil and MIGHT have done that)

NOTE: also the extra control on Deeds Server side would make it easier for the "admin" to be able to remove Claimed land or get control over it for players that Don't play anymore . (the only way we have at the moment for an Admin to change something on a players Claimed area is for the player to add the Admin to a deed) i know when i start playing on a New world or maybe creating a New Deed i always add the main Admin to it (which just so happens to be Phlo)

just as an afterthought, to help with Server control and Over population, maybe a way for deeds/claimed land to become FREE if a player hasn't logged into a server for over a week this would help other players that get blocked in by inactive players (with the option for Admin to turn this on/off and adjust the time)"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#342
