### ISSUE TITLE
Shelves seem to have invisible extra block on left (wont place tight against wall) 6.1.1 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2909]
![snap626](https://user-images.githubusercontent.com/29383891/33291343-6a52a960-d3bd-11e7-82f9-3325bc6cb212.png)
When trying to place against a left wall says Blocks as shown.
![snap627](https://user-images.githubusercontent.com/29383891/33291390-88b750c2-d3bd-11e7-8e5a-02f3a986f9f9.png)
When placing against a right wall it fits tight against it.

as far as i can see visibly it should be like bookcase and can be placed next to each other with no gap

**Comment by Conchipedia** [comment]
Maybe add Dimensions of the Table/Furniture to this window
![snap629](https://user-images.githubusercontent.com/29383891/33291523-040616aa-d3be-11e7-825c-3696f6090bcc.png)

**Comment by Nanders** [comment]
closed with https://github.com/StrangeLoopGames/EcoIssues/issues/2842
