### ISSUE TITLE
[Suggestion] Rules on posting github issues

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2911]
Would be nice to have a way to KNOW which section to put Issue under
 (to avoid Duplicating already posted issues)
Examples: 
Tables for anything to do with tables
Server Crashes (obvious)
Furniture (for non Table objects)
UI (for user interface issues)
Vegetation (plants and Trees)
Rooms (room detection problems etc)

also adding the Version number to an issue (i try to do this especially if i'm using Staging or a Newer version has just come out)

reason for this is mainly due to slightly different spellings of an object:
examples are https://github.com/StrangeLoopGames/EcoIssues/issues/2842
and https://github.com/StrangeLoopGames/EcoIssues/issues/2909
same issue but Different Spelling. (so made Search of Duplicate a bit hard)

**Comment by MarjieAVolk** [comment]
We will need to sort through all incoming bugs either way.  Don't worry about it.

I am working on an in-game bug report form that will automatically add your version info for you. (https://github.com/StrangeLoopGames/Eco/pull/2022)

**Comment by Conchipedia** [comment]
cool, would be interesting to have read it, but it's private and i'm thick, so maybe better not :P

**Comment by MarjieAVolk** [comment]
Ah sorry, forgot what the privacy settings were

**Comment by Conchipedia** [comment]
not a problem, at least i know something cool might be in the pipeline <3
