### ISSUE TITLE
Create a property view mode in the main game view

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#292]
BUG BOUNTY - 10 points

Currently property only displays in the minimap, we need a mode that renders a projection onto the world when enabled.

**Comment by metachronism** [comment]
Should be able to use unity projectors to do this fairly easily (I guarantee nothing)

**Comment by johnkslg** [comment]
This issue was moved to StrangeLoopGames/EcoBugBounties#1
