### ISSUE TITLE
Server fails to generate new world 6.2.0 #33539bb0

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2920]

**Comment by MarjieAVolk** [comment]
So what exactly happened with these?  I'm trying to generate a fresh world from staging branch now (in VS, not built server), and no issues at least thus far.

**Comment by MarjieAVolk** [comment]
Yeah I had no problems locally, gonna try from the steam build now.

**Comment by MarjieAVolk** [comment]
Okay with the steam build I am seeing the world not being there, as I think you mentioned, after generating a new world

**Comment by metachronism** [comment]
no repro in current stagin
