### ISSUE TITLE
Have your starting property claim flags start on your toolbar

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2932]
Moving these is step one for any new player

**Comment by Conchipedia** [comment]
Possibly also make Deed that's first created go into backpack, to try and make sure New players keep it there and not accidently place in a chest, same for Cart Deeds (a lot of new players put the deeds in chest and end up with a NEW deed everytime they claim land)

**Comment by MarjieAVolk** [comment]
Yeah that makes sense.  IMO deeds should just not be items though.

**Comment by Conchipedia** [comment]
maybe give Deed a tooltip as a suggestion of what to do with and where best place to store

**Comment by Conchipedia** [comment]
i know some players like to place deed back in a chest, and then create a new one specifically for a new area and give it a different name

**Comment by Conchipedia** [comment]
getting back to the main point of the Property claim flags auto going to toolbar, i always have mine at at the far Right and only put NEW stuff in 8 and 9 (the tools always go into the same slots)
<img width="463" alt="snap095" src="https://user-images.githubusercontent.com/29383891/33407488-766a2874-d569-11e7-83a4-31c960a693fb.png">

**Comment by pamduncan** [comment]
Maybe you could have a wallet item that just held deeds?  If this wallet was just for deeds maybe it could allow the setting of the 'active' deed you did not even have to go to a chest and shift through deeds to get the one you want to use and drop off the one you don't want used.  You could just open your 'wallet' and set the deed to the property you are working on as your 'active; deed.  Then you could move on and go to other property and just switch to another deed and set it active without having to go back to base an switch out the deeds?

**Comment by Conchipedia** [comment]
sounds like a Good idea, would make handling of all the deeds much easier and players wouldn't have that occasional problem of not being able to find Deeds as they would all be in the same place

**Comment by MarjieAVolk** [comment]
Guess we are not going to be moving property claim flags to the toolbar
