### ISSUE TITLE
Can get a blank tooltip

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2933]
- Drag an item
- After release, leave the mouse stationary and wait for the tooltip
![image](https://user-images.githubusercontent.com/3536496/33353186-5c2e7162-d461-11e7-923a-35f16412c16a.png)

**Comment by MarjieAVolk** [comment]
Yeah :/ Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2922
