### ISSUE TITLE
Dragging items from the quantity-selection UI twice before it closes causes exception

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2935]
Turn up the lag simulator to allow this one.
Need to close the quantity selector as soon as the drag happens

**Comment by MarjieAVolk** [comment]
Is this like the stack splitter?

**Comment by johnkslg** [comment]
yeah thats what I meant

**Comment by MarjieAVolk** [comment]
Not seeing any problems with the stack splitter thing
