### ISSUE TITLE
[Art][Suggestion] Standalone Program (possible Screensaver) to Showcase your Amazing Game Artists

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2940]
I have Been Enjoying anything ECO and had this thought, we already get the Loading/Login Screen that shows Various Biomes and Animals (as seen Below)
![snap187](https://user-images.githubusercontent.com/29383891/33405347-cfd7cc86-d55f-11e7-9708-ce1e05805b3e.png)
Would it be possible at some Future Date to have a program that can be standalone (just loaded from Desktop or maybe can also be chosen as a screensaver) Displaying the Amazing work that your Artists and Animators Do.
Maybe with a little menu to choose Biome (and maybe also have an option as well to Randomly Choose)
Also the same for the Animals (would be nice to see them just relaxing rather than just seeing them from a distance or them running away when you come near, getting a bit fed up of just seeing their Bums) the choice of animals can be how many, which type etc (also that may have option for random Choice)
Obviously Somehow protect the ingame Graphics from being extracted edited etc.
maybe also somehow set it up that ONLY registered Game owners can use (to save it getting out as FREE software)
Also having like the loading menu choosing graphics quality, screen Resolution and Which Monitor (if like me they have more than one) that it will be displayed on.
Maybe also the Underwater Biome could be shown, with Fish etc.
also maybe ability to choose time of day as well (that also can be set as random choice)
Obviously i'm a bit of an Ecoholic :)

**Comment by Conchipedia** [comment]
talking with @MarjieAVolk gave me the idea to have option on Loading Screen, with Two Buttons, 1st Button "Play Game" 2nd Button "the idea i had above"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#340
