### ISSUE TITLE
Unable to place any block in a space (6.1.1) 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2942]
<img width="1280" alt="snap087" src="https://user-images.githubusercontent.com/29383891/33406232-c8d2f61e-d563-11e7-93ca-d6d1b9f93887.png">
<img width="1280" alt="snap086" src="https://user-images.githubusercontent.com/29383891/33406245-d4c82a02-d563-11e7-9e51-c94b02e0117a.png">
The second Snapshot is reverse View from below of the above Picture.
As far as i am aware i didn't have a tree/sapling growing under here as it was already open space (was ONLY sand) since removed and used.
i have even dug down a few levels below the hole and then filled back in with dirt (to try and see if anything was possibly hidden there)
Did try and search this issue (so apologies if its a duplicate)

The sign does say DIRT, but i can't place ANY type of block in the hole

**Comment by MarjieAVolk** [comment]
Sounds like a phantom plant block thing?  Is that fixed?

**Comment by Conchipedia** [comment]
i left Sign there to remind me to ask Admin next time he comes on to possibly use  devtool all blocks below to see if this can fix the issue

**Comment by Conchipedia** [comment]
but i could place one object below the hole as seen by stone roof and another one above the hole that's how i got the sign to be there, just not in the Hole

**Comment by metachronism** [comment]
need game save to debug this more

**Comment by metachronism** [comment]
also if you can use a soil sampler below the block you are trying to remove, it should say what block is above it

**Comment by MarjieAVolk** [comment]
Game save was linked in another bug: https://www.dropbox.com/s/6h0tb51x6yo0jfj/prime%20save.eco?dl=0
