### ISSUE TITLE
How to make Tiny Tree Go away? (without it becoming possibly Invisible) 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2943]
<img width="1280" alt="snap091" src="https://user-images.githubusercontent.com/29383891/33406747-43f60992-d566-11e7-882a-c01e603f1ba0.png">
showing tiny tree in place
<img width="1280" alt="snap092" src="https://user-images.githubusercontent.com/29383891/33406762-54e578e6-d566-11e7-8a8d-8af451201932.png">
Digging out Dirt, tree still there
<img width="1280" alt="snap093" src="https://user-images.githubusercontent.com/29383891/33406773-64443eda-d566-11e7-9f44-3a8fcd555b4b.png">
Tried Using Hoe, tree still there
<img width="1280" alt="snap094" src="https://user-images.githubusercontent.com/29383891/33406782-738c50da-d566-11e7-8800-95a5b8df7a3b.png">
As can be seen it is possible to select tree then destroy with an Axe.

is this the only way it can be removed? and also doing it this way will it possibly be seen as still be there when planting?

**Comment by Nanders** [comment]
These tree nuggets have since been removed
