### ISSUE TITLE
ØÆÅ and other country specific characters don't work in eco

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2944]
Ref slack feedback of not wroking non US standard characters.. Because we all wanna say : "sån går nå dagane uten brød i magen =P"  Or "Hvordan er været ?" <--- ABSOLUTE CLASSIC THING TO SAY !

**Comment by MarjieAVolk** [comment]
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2656 ?

**Comment by MarjieAVolk** [comment]
Or did you not mean in chat?

**Comment by noblackthunder** [comment]
in chat
but yes it is a dublicate !
