### ISSUE TITLE
Cast Iron Stove in 6.1.2

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2945]
Lussian posted about 2 hours ago reply quote  0 
Hey, Cast Iron Stoves suddenly don't have a visual or physical effect after updating to 6.1.2 hotfix :O
I can still find it in the storage tab from other items nearby... xD but can't actually access it.. makes salad making a bit hard o.o Oh and my crispy bacon!

**Comment by Conchipedia** [comment]
i just noticed the same (no Art for placing)
<img width="1280" alt="snap097" src="https://user-images.githubusercontent.com/29383891/33412643-9d5548d6-d584-11e7-9eb3-ca7feb10b2e9.png">
and when placed No Art at all but it is there effecting my room bonus
<img width="1280" alt="snap098" src="https://user-images.githubusercontent.com/29383891/33412669-ccc3c41c-d584-11e7-875f-23f3f0c17db7.png">
so its invisible, and Cannot be used (pressing E does nothing at all) you cannot place any blocks in the space occupied by it, so it is taking up some space

**Comment by Conchipedia** [comment]
The Fuel Storage can be seen from other Storage and Coal can also be added to it and removed, buts thats as far as it goes.
<img width="515" alt="snap100" src="https://user-images.githubusercontent.com/29383891/33412853-04fb52d6-d586-11e7-8939-0306faf52c54.png">
<img width="514" alt="snap101" src="https://user-images.githubusercontent.com/29383891/33412854-05139d0a-d586-11e7-8e0d-35c921571333.png">

**Comment by MarjieAVolk** [comment]
Fixed in next release
