### ISSUE TITLE
Windmill removed Rooms Furnishing value (failed room) 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2946]
according to Eco i have a Windmill thats in a room that removed a Room's Furnishing Value ,as you can see i have 2 and they are both outside
<img width="1280" alt="snap103" src="https://user-images.githubusercontent.com/29383891/33413192-10075f9c-d588-11e7-98b4-0b6ea8e0de9f.png">
This seemed to have just Happened as i had a Cast Iron Stove that broke my Kitchen
referencing https://github.com/StrangeLoopGames/EcoIssues/issues/2945
i since then Closed off that little room with stove in to fix my kitchen (as i cannot see it to remove it) also relogging didn't make any difference (Might ask Admin when available to restart the server)

**Comment by Conchipedia** [comment]
not sure whats happening now, i reopened the little room with Cast Iron Stove in, as a doorway into another room, Now Windmills are back to normal and the Cast iron Stove is in a kitchen all on it's own
<img width="288" alt="snap104" src="https://user-images.githubusercontent.com/29383891/33414769-9d7a4720-d58a-11e7-94b9-c6601be64178.png">

**Comment by Conchipedia** [comment]
totally confused with this Issue, will try and Add the "World Save" here when i next talk to Admin

**Comment by Phlo123** [comment]
Prime Save.
https://www.dropbox.com/s/6h0tb51x6yo0jfj/prime%20save.eco?dl=0

**Comment by Conchipedia** [comment]
This save has small signs in place for the Issues i have put in 
(Hope this makes life a little bit easier for you)

the Issues are as Follows

https://github.com/StrangeLoopGames/EcoIssues/issues/2895
https://github.com/StrangeLoopGames/EcoIssues/issues/2904
https://github.com/StrangeLoopGames/EcoIssues/issues/2913
https://github.com/StrangeLoopGames/EcoIssues/issues/2942
https://github.com/StrangeLoopGames/EcoIssues/issues/2945

There is also 2 that are linked together for How hard the invisible Iron Hoe is to use in game
(Also the Iron Hammer) this was added as struggling to Hoe the dirt
https://github.com/StrangeLoopGames/EcoIssues/issues/2478
https://github.com/StrangeLoopGames/EcoIssues/issues/2877

**Comment by Conchipedia** [comment]
Iron hammer has no in hand model #2478

**Comment by Conchipedia** [comment]
apologies for all the links but they make sense when you load up the world i found them all in

**Comment by Conchipedia** [comment]
![snap727](https://user-images.githubusercontent.com/29383891/34075177-8bc3cdf6-e2b6-11e7-9304-5edf4ed1e901.png)
Now seem to get Waterwheel is breaking the room Furnishing Value and that is outside!!

**Comment by Conchipedia** [comment]
![snap770](https://user-images.githubusercontent.com/29383891/34259088-c47ec4c0-e658-11e7-9095-9872bcfc8fb1.png)
![snap771](https://user-images.githubusercontent.com/29383891/34259102-d4710f3c-e658-11e7-8618-20ab6547465e.png)
https://www.dropbox.com/s/bm4ph0mwqt3t4lz/PRIME-Game.eco?dl=0
this is the save for it ,this is also the same one that is in #3172)

**Comment by Conchipedia** [comment]
i'm playing on a new world my windmill was fine and not breaking any room score, but for some reason it now does, i have tried placing it on different places on my land and it still breaks the scoring, i now have unclaimed some land in the middle and built it there and all my rooms are now working (hoping that a windmill that i do not own still will power the mills)
![snap884](https://user-images.githubusercontent.com/29383891/34594297-0db15ba6-f1c8-11e7-987e-7c580d3b19aa.png)
as you can see it is unowned and not effecting my room score 
![snap887](https://user-images.githubusercontent.com/29383891/34594397-a3dd5dfa-f1c8-11e7-9837-a9210e0a6efb.png)
i now claim the land and i lose a massive 17.09 from the windmill
![snap886](https://user-images.githubusercontent.com/29383891/34594409-bcaec9e0-f1c8-11e7-9d16-b39d2ba61589.png)
i'm still confused as to how this effects the room score when the thing is outside, only thing that shows up it cannot be on my owned land

**Comment by johnkslg** [comment]
Outdoors no longer counts as a room, since materials of a room determines its value. Closing for now.
