### ISSUE TITLE
[Suggestion] Special skill bonus for Industry Items

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2948]
we already have a SP bonus in place for furniture (Great idea), maybe have a "special" industry one that is not for SP but may add a bonus Efficiency for crafting, or maybe have another one for having ALL the extra tables that you need for Carpentry  (Cooper's Tool Shelf, Fletcher's Tool Shelf, Sanding Block and Saw Mill).

**Comment by Conchipedia** [comment]
maybe make the bonus ONLY happen when the items are being used and not just made and placed in a room

**Comment by MarjieAVolk** [comment]
Sounds kind of like what modules were originally supposed to be

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#339
