### ISSUE TITLE
[Art] Work Backpack and Work Boots not visible when worn 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2949]
<img width="198" alt="snap105" src="https://user-images.githubusercontent.com/29383891/33429954-96ea7a42-d5c6-11e7-971a-3b14f9daa869.png">
Putting on Work Backpack and Work Boots, neither are showing up , i think also other players cannot see them either.
Not checked any other Tailoring items, as this was the only 2 i wanted and crafted

**Comment by MarjieAVolk** [comment]
Looks like this is fixed now
