### ISSUE TITLE
targeted objects dont unhighlight until you look at a block

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2950]
regardless of the distance you move away from the object

![image](https://user-images.githubusercontent.com/3150561/33447502-608e2ae2-d5b8-11e7-9e05-581590212d2a.png)

look at a tree trunk, then scoot away from it being careful to not look at any blocks or anything else nearby.  it is supposed to un-highlight once you move out of interaction range

**Comment by SeanAtr0n** [comment]
works for me so far... anything else you did?

**Comment by BlazeGuy2** [comment]
Can't reproduce, closing.
