### ISSUE TITLE
tooltip for laws appears in seemingly random screen position

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2952]
(hover over Law button in lower right)

![image](https://user-images.githubusercontent.com/3150561/33448457-f6024c6e-d5ba-11e7-8b3c-69374e257b47.png)

**Comment by MarjieAVolk** [comment]
>> ??

**Comment by MarjieAVolk** [comment]
Hm not seeing this on master

**Comment by MarjieAVolk** [comment]
I just saw something like this and then fixed it, although I doubt it was the same bug.  Gonna close this for now, if it happens again look for client exceptions
