### ISSUE TITLE
Did not get permissions for property with contract

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2954]
Accepted two similar contracts:
![image](https://user-images.githubusercontent.com/23460210/33452350-cd6c6850-d5c6-11e7-93ae-720122644935.png)

All construction posts were on the same property.  They were also underground (in a mine).  I got no permissions on the property at all as far as I can tell.

**Comment by johnkslg** [comment]
Fixed in next pr
