### ISSUE TITLE
[Linux]  Syntax error in ecomap.js

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2960]
ecomap.js Line 752 is where its being caught (appears it probably somewhere above that) if we comment out that line the error moves again.    PlotMap.prototype.SetPixel = function (vec, size=1) {

 This is being ignored in windows.    The map file is where Linux is crashing for us so it appears that windows is skipping the error and the plotmap can still load but apparently Mono is having issues with the error breaks on it which has been leading us back to the syntax error.  If we remove anything in the file that causes a syntax error to be reported Linux will run but of course the map is broken.

**Comment by SeanAtr0n** [comment]
I'm not seeing this error after fixing the static gifs
