### ISSUE TITLE
Can't see torch on other players anymore

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2961]
try /thirdperson and equip a torch

**Comment by SeanAtr0n** [comment]
looks like nothing in the Eco.unity changed... might have something to do w/ marjies last edit

**Comment by SeanAtr0n** [comment]
seems related to:
            foreach (var stack in this.ToolbarView.Stacks.Where(stack => stack.Item is DurabilityItemView))

torches don't have a durability so either that line should change or torches should have a durability

**Comment by Arend90** [comment]
i go for durability for the torch <3

**Comment by Conchipedia** [comment]
is that /thirdperson a player option? if so would be nice

**Comment by MarjieAVolk** [comment]
Think it's available yeah.  But just FYI it's not fully working, was designed for debug.

**Comment by Conchipedia** [comment]
ok, but would make a nice option if its left in <3
