### ISSUE TITLE
Wood Cart not requiring dirt roads 6.1.2

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#2962]
The Wood Cart (normal one, not small) doesn't seem to have road efficiency penalties, it's showing as 100% on grass/dirt and other non road blocks.

**Comment by WeaselDog** [comment]
Wood Cart now has a 50% penalty on grass in 0.8.3 release, just like Small Wood Cart & Steam Truck. No vehicles have a move penalty on cleared dirt.

![WoodCartInGrass](https://user-images.githubusercontent.com/47330823/71116778-96a73c80-2189-11ea-882d-28c3e8d7a799.png)
