### ISSUE TITLE
Hovering Mouse over deed, window Displaying locations to small cannot see them all 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2963]
![snap188](https://user-images.githubusercontent.com/29383891/33500501-e7273102-d6d0-11e7-82ee-0cab1b937b8c.png)
as the title describes not all locations can be seen on window, possibly need a new window that can stay open with a scroll bar
did do a search but couldnt find anything for deed specific window only one for hovering mouse over Skills

**Comment by MarjieAVolk** [comment]
ew yeah that needs to go away

**Comment by Conchipedia** [comment]
can we have it just appear in right click of deed menu? as its not really much use showing up the locations, maybe have the window popup say Right click to view locations, as it already has the crafted at and right click to change access rights

**Comment by Conchipedia** [comment]
all that would look good on hover window is Total area owned
