### ISSUE TITLE
[web] When going to web to run for leader speach window appears then goes, need to refresh to make it stay (Firefox)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2964]
if i want to run for world leader i open law window click on choose to run then that takes me to web page, the enter speech window appears then disappears, i have to refresh the page and it opens and works normally from then on (havent checked on laws, as i havent wanted to make any)
this is on Firefox (latest 64bit version)

**Comment by Conchipedia** [comment]
is this fixed in Staging? as it still does it in 6.3.1

**Comment by MarjieAVolk** [comment]
I assume it's only fixed on her dev branch.  @syuzan-yeranosyan which branch is this fixed on?  When is it going in?

**Comment by Conchipedia** [comment]
Still having this same problem in Version: 0.7.0.0 beta staging-71fcbff4

**Comment by rainfarmer** [comment]
firefox bugs fixed
