### ISSUE TITLE
[Suggestion] Ability to show when player AFK or too busy to chat

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2967]
would be nice to have an option to show up as AFK if you are inactive for a period of time, or can choose this in game, maybe put the option in Objectives Window, maybe have like a Green light for playing and a red one for Busy/AFK, was thinking about putting something above players head but unless you are next to them you cannot see it.
one of the main reasons for this if you get called away from the game by a telephone call, toilet or drinks break but do NOT want to log out, this way people can see that you are busy or not there and wont keep spamming chat at you, just like the option we have in Discord.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#338
