### ISSUE TITLE
[Suggestion] Making tables Inherited (protected) by default

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2968]
Would it be possible to have placed tables Inherited (if on owned land) as sometimes people can forget to do this and things can be taken, Example: friend had stoves and someone pinched the coal from the power tabs, this shouldnt happen if we already own the tables and they are protected, we can choose to make a table public if we are making an area that we own already to be a public crafting zone, but we still want to own the land.
Chests and Stockpiles are instantly Inherited and protected as soon as you place them, why not for tables as well (please)

**Comment by MarjieAVolk** [comment]
It used to be you couldn't remove things from the fuel supply unless you were the owner.  That's a bug.

**Comment by Conchipedia** [comment]
didnt realise that, is there any reason why tables are Public by default?

**Comment by MarjieAVolk** [comment]
I guess to encourage using table fees and such rather than having each player make their own copy of the table

**Comment by MarjieAVolk** [comment]
Fixed on staging
