### ISSUE TITLE
Disconnecting or exiting Eco will just make Eco sit there not doing anything (64bit client) 6.1.2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#2969]
i play on 3 Different PC's (all windows 10 and 64bit )(two at friends house one at home) am finding that Eco will Not Disconnect properly (sometimes i get lucky and it will go back to servers list, other times it will go back to servers list and no servers showing), and i have NEVER manged to quit Eco via the quit option (have to just end Eco in the task manager)
all PC's used are various Nvidia Cards (just as added information)
Disconnecting causes freezing/crash #1440
Game freezes when disconnecting #1170
Referenced these two as this was all i could find searching "Disconnecting"

**Comment by efflixi** [comment]
I have the same issue on Linux as well, it's not just Windows. I can disconnect fine from a server but trying to exit the game just results in the game hanging. I've started just disconnecting from the server and then Alt-F4 to exit. It still hangs, but eventually Linux kills it.

**Comment by metachronism** [comment]
This seems related to all the in-flight webrequests sent out for the server browser

those threads not getting killed off or something

**Comment by metachronism** [comment]
should be fixed in 7.3
