### ISSUE TITLE
Stockpiles losing first 4 slot with dirt

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#2970]
When filling a stockpile with dirt which subsequently turns to grass it will purge/delete the first 4 occupied slots of the stockpile.

**Comment by Yorkforce** [comment]
Not sure if it's related but I have also noticed on the odd rare occasion a single stack (any type of block) will disappear when moving stacks from one stockpile to another, can't seem to find any reliable way of reproducing it but so far I have noticed a stack of concrete went missing and a stack of stone so it seems it can happen to any block type. (no dirt in the stockpiles when it occurs)

**Comment by MarjieAVolk** [comment]
Oh sounds like this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/3182

I know yours is older, but closing this one as there is more stuff over there now
