### ISSUE TITLE
Currency Exchange Broke

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#2971]
I am trying to set up the economy for our server and I put a currency conversion of 2 Explicit Credits for 1 EOG Dollar coin which I created in the mint. One of my players reported to me that he was able to to receive the number of coins he requested in exchange but it didn't remove any of the Explicit credits from his account.

I now have just upgraded the server to 0.6.1.2 and the name is ExPLiCiT Online Gaming. I do not have the exchange public now for obvious reasons so if you want to test on my server you will have to do it when I am on.

I can't attach the world saves because they are too big.

**Comment by metachronism** [comment]
possible dupes of
#2623 #2830 #2831

**Comment by Dr-Hardware** [comment]
Not duplicates of #2623 #2830 #2831.

Currency exchange seems to work nicely as long as the seller does not sell 100% of their currency.

as soon as a seller tries to sell either 100% or MORE than 100% of thier currency, they get the new currency, but lose NONE of the old, therefore can basically drain the exchange owner down to holding limits 

I tested the holdings and they work at least

So its just the "test if seller has enough money" and the "take this money from the seller" sections of the code that are ...glitched...

**Comment by Dr-Hardware** [comment]
Perhaps an "exchange all" button to let the computer do the calculations to remove 100% exactly .

There seems to be some ~0.001 calculation / rounding errors as doing a 1-1 exchange with no fees or taxes has resulted in one currency having a .999 balance

perhaps in addition to the holdings limits, a minimum / maximum amount per transfer?

**Comment by johnkslg** [comment]
Fixed!
