### ISSUE TITLE
Add tooltip to material tiers 

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2972]
Made a kiln put in a room made of mortared stone says 0/32 tier 2+ materials What on earth are tier materials you used to say PLAIN AND SIMPLY need 32 mortared stone why change to such cryptic wording you need to put a pop box explaining what are tier 1,2,and 3 materials what do i need to make this room out of

**Comment by Dr-Hardware** [comment]
mortared stone is tier 2.   if it shows 0/32 then your room is not complete somehow.

**Comment by MarjieAVolk** [comment]
This is already implemented, available in the next release
