### ISSUE TITLE
Cast Iron Stove Disappeared In 0.6.1.2 and Can't Place Another

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#2976]
I noticed my Cast Iron Stove disappeared and when I place a new one it just disappears too.

**Comment by Yorkforce** [comment]
#2945

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate ^

**Comment by MarjieAVolk** [comment]
(Also this should be fixed in 6.2, released today)
