### ISSUE TITLE
alpha 6.1.2  - right clicking on a chest doesnt store my coal,stone,wood or dirt ?

### ISSUE THREAD

**Issue by Masonic64** [StrangeLoopGames/EcoIssues#2977]
hi there, not sure if im missing anything here but  right clicking on a chest doesnt store my coal,stone,wood, iron ore or dirt ? Its all piled up outside my shack at the mo. When i open the chest and drag the wood from what im holding to the spare slot it says "inventory only accepts non-carried items"

Kind Regards

**Comment by ECO-ExPLiCiT** [comment]
You have to use a Stockpile for those items.

**Comment by Masonic64** [comment]
what a ledgend, cheers mate , have a good evening :)
