### ISSUE TITLE
Rouse bug: Clicking above a greyed out square was confusing on the skill tree

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2979]

**Comment by johnkslg** [comment]
Closed with new skills ui, marjie?

**Comment by MarjieAVolk** [comment]
Don't think this is any different, no

**Comment by WeaselDog** [comment]
It looks good to me with the new skill UI:
![SkillsUI](https://user-images.githubusercontent.com/47330823/71285112-39da8c00-2319-11ea-80ea-f9675b690df1.png)
