### ISSUE TITLE
Rouse bug: Add recenter on me button to minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2981]
The globe map is very cool in functionality, but I have a very hard time finding anything on it - particularly myself.  It'd be nice if there was a "recenter on me" button.  Also my position indicator is yellow, which blends in with a lot of your other colors.   Also some way to find my workbench would have been nice (see below for more about that).

**Comment by BlazeGuy2** [comment]
This feature exists by toggling follow player checker.  Also player is the triangle with red/white.  However, the workbench finder isn't in.

**Comment by BlazeGuy2** [comment]
gonna close since we have the new bug posted.
