### ISSUE TITLE
Rouse bug: Default settings for high, medium, low performance

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2984]
I wish in here there were some broad defaults to pick from, and I could just pick "make it run faster" and it would change some stuff.   You still want the specific options, of course, for the PC tuner crowd, but for someone who just wants to jump in and play and maybe doesn't know what those options are, something simpler would be nice.  In the end, I was unsure if anything I was doing was helping.

**Comment by SlayksWood** [comment]
merged to #12151
