### ISSUE TITLE
Rouse bug: Frame rate degrades over time

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2985]
"As I mentioned the frame rate started out at 12-14, but it just degraded as I played.  By the time I stopped it was 7-8 or worse.  And this wasn't even looking at a lot of stuff.  I would be staring off over the water at nothing and still the frame rate would be that bad.  It felt like it was just the longer it had been running the slower it got, regardless of what I was doing."

**Comment by ShaydenMac** [comment]
http://steamcommunity.com/id/clutchdaddydick/recommended/382310/

Although it looks like a game anyone could run, as soon as you have multiple structures, 16 frames. It ruins the online experience. I play Arma 3 KOTH and I get bugged by the frame rate in this game.

**Comment by SeanAtr0n** [comment]
uhhhhhhhhh ok this could be like a 6 month bug

**Comment by SeanAtr0n** [comment]
dropping priority, this is a long-term issue

**Comment by D3nnis3n** [comment]
Merging with https://github.com/StrangeLoopGames/EcoIssues/issues/11357, a more recent fps degrade over time bug.
