### ISSUE TITLE
Write modding documentation!

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2987]
Supporting mods from beta will be a huge value-add for the community and really give extra longevity to the game.  Add documentation for all aspects of modding.
- [ ] Clothing on avatars (Sean)
- [ ] Builders (Keegan)
- [ ] Tutorials
what else?

**Comment by Phlo123** [comment]
- light sources ( with curved shader, or equivalent)
- animals
- plants with and without animations from SpeedTree
- UI modding
- more than one "[RequiresSkill(typeof(X), 1)]" in skills
- adding a Skill Icon
- how to use StateMachine from unity on WorldObject and AnimalEntity
- how to make tools (with extra how to make the Hydrometer, effects and all)
- how many variants does one building block have, and how to make it spawn the correct one when building.
- "WorldObjectOccupancyAutoGen.cs" what? why? and how to use it...
Sorry if this was the wrong place to post this...

**Comment by metachronism** [comment]
closing this out for now - as this is the plan for an upcoming sprint and otherwise documented there.
