### ISSUE TITLE
Rouse bug: Couldnt figure out digging

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2989]
Took me a long time to figure out how to dig for dirt.  Maybe around the hour mark.  I had restarted the tutorial several times.  Finally I saw some help text that said "Go look at the skill tree and find something that will help you dig."  I feel like the help text is mocking me with an instruction like that - early on, I think it just needs to be more explicit about what I had to do - and when I got to the skill tree it self there was no additional help to know.  I eventually figured it out, but trying to figure out how to dig for ~30 minutes made me feel dumb.  Probably I am dumb, but probably some of your players will be too.

**Comment by MarjieAVolk** [comment]
That's interesting.  With that text I was trying to get people to actively engage with the skill tree (I'd already instructed them to put a point in a specific skill earlier).  I figured with the shovel icon on the skill it would be pretty obvious; but it isn't called digging or anything, so idk maybe it's not as obvious as I thought.

**Comment by johnkslg** [comment]
Closing with addition of control popups explaining digging
