### ISSUE TITLE
COPPA compliance

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2990]
Ensure we meet all these standars
https://www.ftc.gov/tips-advice/business-center/guidance/childrens-online-privacy-protection-rule-six-step-compliance#step1

**Comment by metachronism** [comment]
since we don't collect any personal information, does this even apply?

**Comment by rainfarmer** [comment]
ya the only thing we take is username.

which COPPA says can't function as online contact information.
Which it doesn't so i think were good.
