### ISSUE TITLE
Can't run for office in 6.2

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2994]
no error is shown, but in the console it shows
Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://192.168.1.3:5001/api/v1/elections/canaddcandidate?username=SeanAtr0n

**Comment by metachronism** [comment]
you have to be a citizen on the server first

**Comment by MarjieAVolk** [comment]
"When running the Eco Server in debug mode - Clicking "Run for office" in the web GUI, I get an unhandled exception:

System.Exception: '<style="Error">Cannot violate law 'Citizenship'.</style> Your Play actions Ever (1.26) is less than 2; Action not allowed.' from Line 80 in ControllerUtil.cs"

Looks like this is a problem with web client not handling the exception

**Comment by syuzan-yeranosyan** [comment]
I can't received the error but as the issues related to ControllerUtil.cs I think that it is not a problem with web cilent handeling the exception. 
Can you describe more deeply?

**Comment by rainfarmer** [comment]
fixed
