### ISSUE TITLE
Chunk loading depends too much on latency

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#2995]
Try moving around on high latency servers or with emulated lag turned up, it's pretty easy to reach the edge of the world.

There any easy fix for that?

**Comment by metachronism** [comment]
I dont think this is worth optimizing for; high lag (anything above 500ms or so) isn't worth killing ourselves over optimizing for

**Comment by SeanAtr0n** [comment]
seems like there are likely easy fixes for this but ok don't look

**Comment by SeanAtr0n** [comment]
Fixed, keepalive was reducing update rate for laggy clients
