### ISSUE TITLE
Change wording on store notifications

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2997]
![image](https://user-images.githubusercontent.com/6262198/33581592-440f3450-d906-11e7-8c9f-da9851d03929.png)

To me, "for sale" and "wanted for purchase" have similar inferred meanings. Change "Wanted for purchase" to just "wanted"

**Comment by MarjieAVolk** [comment]
Actually these should both use an active sentence structure - "Nanderson's Store is now selling Logs"

**Comment by Nanders** [comment]
Oh yeah that's so much better. Was hard to point out what was wrong with the original wording, just that it was awkward.
