### ISSUE TITLE
Limit deed title length

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3002]
![unknown](https://user-images.githubusercontent.com/6262198/33585843-4b57e80a-d91b-11e7-8b4e-d1519ab639d7.png)
Create some way to truncate or limit long deed names,

**Comment by Conchipedia** [comment]
maybe just have a text box appear with a maximum amount of letters and spaces to use, and maybe show this in bottom right.
No limit on how much text can be placed in a sign and too much gives sky writing 6.0.3 #2773
maybe this can be worked out for Both problems (as both have no limit on text written)

**Comment by MarjieAVolk** [comment]
Fixed in 7.7 (not the next major release, but the one after)
