### ISSUE TITLE
Meteor will fly under you when you're at high y coordinates

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3003]
Saw it happen in the mountain settlement on Marmot. The meteor "orbits" below where the highest points on the map are.

**Comment by Hanan09** [comment]
![ice_screenshot_20171205-192104](https://user-images.githubusercontent.com/31784528/33618353-6137ff38-d9f3-11e7-9218-6d66e8d7c90c.png)
![ice_screenshot_20171205-192354](https://user-images.githubusercontent.com/31784528/33618361-65bb8e94-d9f3-11e7-9aaa-828790a80adf.png)

**Comment by SeanAtr0n** [comment]
fixed w/ meteor changes
