### ISSUE TITLE
Server icon duplicates minimap icon, has ping on it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3006]
![image](https://user-images.githubusercontent.com/3536496/33586778-f1ffb094-d91f-11e7-9c38-39c184bc3ce1.png)
Need to put the ping somewhere else, perhaps under the coordinates.

**Comment by metachronism** [comment]
art can change the icon if they want

**Comment by redwyre** [comment]
Changed long ago
