### ISSUE TITLE
Simplify main UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3007]
In the interest of a more solid new user experience:

Action bar:
- [ ] Remove Player Objectives, make it a pull out menu from the chat window
- [ ] Remove economy viewer if there are no stores on the server
- [x] Remove avatar button, make it a pullout on the backpack
- [ ] Change the backpack icon to show a player wearing a backpack

Time of Day:
- [x] Make the Co2 meter start disabled if its under a certain amount.  

Nutrition Panel:
- [x] Implement Marjie's fancy new UI

Avatar:
- [x] Make character creation dialog take up the full screen, and have a nice layout.

**Comment by Nanders** [comment]
Can we change how the contract icons display under this task as well? They've always felt out of place and clutter-y. I'm sure there's a better place/way to show them

**Comment by MarjieAVolk** [comment]
Character creation dialog already takes up the whole screen.  Not sure if you are concerned about its layout

**Comment by metachronism** [comment]
backpack is useful as its own thing, I generally want to have it open all the time and leave it on the screen - adding the avatar to it would be a hinderance

**Comment by MarjieAVolk** [comment]
If it's a slide out menu, it won't be taking up hardly any screen space

**Comment by MarjieAVolk** [comment]
Think we've done what we were gonna do with this
