### ISSUE TITLE
tool tiers need better tool tips

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3008]
Can't really tell the difference between tool tiers, there should be some way to tell what benefit tools provide

also you can still make a regular 'Hammer'? (pulled off discord)
![image](https://user-images.githubusercontent.com/774628/33590682-dd286f9c-d935-11e7-858c-50048a41a022.png)

**Comment by elfl0rd** [comment]
@D3nnis3n looks as fixed\removed

**Comment by D3nnis3n** [comment]
Yeh, the hammer is no longer craftable but the different tiers of tools still don't show any difference in their tooltips. They are limited to uses but if you hover over them in the crafting menu they don't show the amount of uses - and that was the main part of this issue.

**Comment by WeaselDog** [comment]
All items here are fixed. It will show you the uses remaining if it is in your inventory.
![StonePickaxe](https://user-images.githubusercontent.com/47330823/71784166-3a278800-2fa5-11ea-8ce0-ddbf3f063d28.png)
