### ISSUE TITLE
Planter pots need "Masonry 1" 6.2.0 #737b5d74

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3009]
<img width="517" alt="snap112" src="https://user-images.githubusercontent.com/29383891/33592528-624d6022-d983-11e7-9a5e-f6242349b17e.png">
Think this might be a Mistake as Masonry is a skill tree not a Skill level, think this possibly should be "Stoneworking"
<img width="275" alt="snap113" src="https://user-images.githubusercontent.com/29383891/33592555-7ff93f88-d983-11e7-8174-6f6d1892e17f.png">
As the Stone Decreases with better Stoneworking Efficiency
<img width="349" alt="snap114" src="https://user-images.githubusercontent.com/29383891/33592669-ff0e1064-d983-11e7-90a2-1f77b5be50ce.png">
<img width="349" alt="snap115" src="https://user-images.githubusercontent.com/29383891/33592672-021854a4-d984-11e7-86ba-adec12b58f8f.png">

**Comment by MarjieAVolk** [comment]
I believe that just means you have to have learned Masonry with a scroll.  Maybe we should display that differently?

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/33628001-976596d6-d9ff-11e7-99a0-ed4108463c27.png)

**Comment by craig-jong** [comment]
They're right. It's incorrect. I'll fix this asap.

**Comment by Conchipedia** [comment]
reason it looked weird was it reminded me of the Chimney that nobody could ever make
