### ISSUE TITLE
Inability to Drag from Backpack or Toolbar to Fill order 6.2.0 #737b5d74

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3010]
cannot drag items from toolbar or backpack to fill an order:
this one is mine
<img width="521" alt="snap116" src="https://user-images.githubusercontent.com/29383891/33593659-3e854416-d988-11e7-92c0-40cfa9b8d077.png">
and this one is friends order on my Table (hasn't linked storage so i MUST drag to fill order)
<img width="520" alt="snap117" src="https://user-images.githubusercontent.com/29383891/33593690-63acb0f8-d988-11e7-9c21-f1243e65ca1e.png">

**Comment by Conchipedia** [comment]
for some unknown reason, i can NOW drag to fill orders

**Comment by MarjieAVolk** [comment]
You're saying you quit and logged back in, and still couldn't do it.  But then somehow now you are able to?

Yeah I've seen stuff like this too, keep thinking I'm going crazy because it comes and goes like that.

**Comment by Conchipedia** [comment]
glad its just not me ❤️

**Comment by D3nnis3n** [comment]
Old issue.
