### ISSUE TITLE
[Art] Cast iron Stove now working (placing and art) 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3014]
Art When placing
![snap659](https://user-images.githubusercontent.com/29383891/33636159-f83acd92-da12-11e7-898d-b0fdca617d12.png)
Art when 1st placed
![snap660](https://user-images.githubusercontent.com/29383891/33636182-110e7558-da13-11e7-8cd3-5bb4b97e2799.png)
Art when Eco settles down
![snap661](https://user-images.githubusercontent.com/29383891/33636334-9a8defc0-da13-11e7-8edc-9c13a9f2aa80.png)

also the size of the model is smaller than the required space it needs (model size 2block high, 2 block long, 1 block wide) space needed (2 block high, 3 block long, 2 block wide) 

can now see why i was having problems working out placement in
Cast Iron Stove in 6.1.2 #2945

**Comment by MarjieAVolk** [comment]
wait is this a bug for something working? lol

But yeah @Nanders occupancy is wrong

**Comment by Conchipedia** [comment]
i did put [Art] 😄
