### ISSUE TITLE
"Press 'E'" should hover over usable items

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3015]

**Comment by MarjieAVolk** [comment]
I've always wanted this, and also there should be an icon of what kind of tool you can use to interact with it

**Comment by Nanders** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2776

**Comment by MarjieAVolk** [comment]
Ah yes, I thought that might exist

**Comment by MarjieAVolk** [comment]
Okay closing
