### ISSUE TITLE
New update 6.2.0 cant transfer from cart to stockpile

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#3016]
have 5 copper ingots in cart have stockpile with 5 stone in it when i try to put copper in it says no room in inventory. Also it placed a stack of 61 iron ingots in my cart and wont let me split or transfer them anywhere

output_log
 Initialize engine version: 2017.2.0f3 (46dda1414e51)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4058 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.035 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

Setting up 8 worker threads for Enlighten.
  Thread -> id: 4990 -> priority: 1 
  Thread -> id: 36e4 -> priority: 1 
  Thread -> id: 4908 -> priority: 1 
  Thread -> id: 36d8 -> priority: 1 
  Thread -> id: 53e4 -> priority: 1 
  Thread -> id: 3a24 -> priority: 1 
  Thread -> id: 1b38 -> priority: 1 
  Thread -> id: 3fc8 -> priority: 1 
UnloadTime: 1.917699 ms
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
RPC lookup took: 3304.4445ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1510)

The referenced script on this Behaviour (Game Object 'PingTimer') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1753)

Missing following icons: CastIronSpigotItem, GraphsItem, PlanterPotRoundItem, PlanterPotSquareItem, RugLargeItem, RugMediumItem, RugSmallItem, SaltBasketItem, SmallTableItem, WoodenFabricBedItem, WoodenLattrineItem, WoodenStrawBedItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, AtmosphereRegulatorObject, AtmosphereTesterObject, ButtonObject, CompostPileObject, FisheryObject, GasGeneratorObject, LogicGateObject, MeteorExplodes, MeteorExplodesInAtmo, PlanterPotRoundObject, SteamGeneratorObject, SwitchObject, WoodenLattrineObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
Couldn't find mapping for object 'FisheryObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.UI.Scripts.CursorManager.SetCursorDrag (System.String ownerKey) [0x00000] in <filename unknown>:0 
  at Assets.UI.Scripts.CursorManager.SetCursor (CursorType type, System.String ownerKey) [0x00000] in <filename unknown>:0 
  at Assets.UI.Scripts.HoverCursorSwitcher.SetCursor () [0x00000] in <filename unknown>:0 
  at Assets.UI.Scripts.HoverCursorSwitcher.UnlockCursor () [0x00000] in <filename unknown>:0 
  at Assets.UI.Scripts.HoverCursorSwitcher.OnDestroy () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by MarjieAVolk** [comment]
Hmmm sounds like maybe the weight in your cart got off from what's actually in it.  Can you send a screenshot of what's in your cart?

**Comment by cuda70** [comment]
Today it let me place everything in my stockpiles and chests Guess everything is working ok today But having one stack of 61 iron ingots 5 copper ingots 5 sand and 5 iron ore in one cart is a bit much LOL

**Comment by MarjieAVolk** [comment]
Alright well, without more information I don't think I can debug this.  I believe we still have some problems with inventory weight getting off, but I haven't been able to find them
