### ISSUE TITLE
[6.3.0 #29dea612] Server Name overwrites Headings on Webpage

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3017]
[Staging Alpha 6.3.0 #29dea612] Server Name overwrites Heading on Webpage making it difficult to see what is at the top of the webpage

[![Screenshot from Gyazo](https://gyazo.com/146ed1b0dc3654987ae214a8c62485aa/raw)](https://gyazo.com/146ed1b0dc3654987ae214a8c62485aa)

and

[![Screenshot from Gyazo](https://gyazo.com/6b5d80f183613fed7fd7c26238ffe2b5/raw)](https://gyazo.com/6b5d80f183613fed7fd7c26238ffe2b5)

**Comment by syuzan-yeranosyan** [comment]
fixed on 'web-develop' branch,
we should cut servername if it is longer than 70 chars and adding title to server with real name (which is showen  when cursor hovering on server name)
