### ISSUE TITLE
[Art] Town hall Occupancy is not right (also breaks scoring of a room) 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3020]
table model shows when placing and placed that it is 5 block long, 2 block wide and 2 block high, but in truth it needs 3 block high space to place
![snap196](https://user-images.githubusercontent.com/29383891/33684783-5b9361c4-dac7-11e7-8030-ff09d572e464.png)
![snap197](https://user-images.githubusercontent.com/29383891/33684793-655b6b2a-dac7-11e7-9036-6bc5949503f5.png)

**Comment by Conchipedia** [comment]
Also when placed in a room it will break all the other furnishing for that room 
![snap198](https://user-images.githubusercontent.com/29383891/33685117-70bc0546-dac8-11e7-8198-ab77d9201263.png)

but doesn't say in description that it will like other Tables (example Saw mill)
![snap199](https://user-images.githubusercontent.com/29383891/33685123-76df99d8-dac8-11e7-9af1-8b8753a7081b.png)
![snap200](https://user-images.githubusercontent.com/29383891/33685128-7a9ef1d6-dac8-11e7-8711-fd9f3a27784e.png)

**Comment by Nanders** [comment]
Fixed Occupancy here https://github.com/StrangeLoopGames/Eco/pull/2067
