### ISSUE TITLE
admin chat command error /giveskillpoints

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3022]
When i attempt to do /giveskillpoints i get an error and kicked from the server

```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Could not parse string "Stormoffires"


Stack:
   at Eco.Gameplay.ChatManager.InvokeCommand(MethodInfo method, String args, User user)
   at Eco.Gameplay.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

this seems to be the only admin chat command that gives me issues.

**Comment by ClayC90** [comment]
Related to Case Sensitivity of usernames,
Will be fixed with 3046

**Comment by ClayC90** [comment]
This has been fixed with my pull request, please close accordingly,

**Comment by metachronism** [comment]
this debug command should tolerate bad usernames, instead of throwing an exception.  Nick can you update?
