### ISSUE TITLE
[Suggestion] Putting Size of Table/object in Description

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3023]
I think it would be very helpful Adding the size of the Table or item to be placed, (especially on Large Objects like the  Blast Furnace) on this Description Window
![snap663](https://user-images.githubusercontent.com/29383891/33722570-3dffb892-db62-11e7-8f8e-6002c65a9f99.png)
So Room designs can be worked out ahead to make space for desired object , rather than getting the object and then having to re-design an existing room to make room for it.
Not sure how it could be written (as not everyone will know the x,y,z  and which order they are written  length, width or  height, unless they have knowledge of how 3D models are described)

I think this may also help with New objects that are designed that might end up having incorrect Occupancy (as the object size will have something for the Modellers/Artists to check against), and may help in reducing the need for New issues about them.

**Comment by Nanders** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/6
