### ISSUE TITLE
Improvements to Hunting

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3025]
From Facebook:

"For hunting. Will animals have a bleed effect. In real life, most large animals can be shot but still run off and die later. Also, will area damage be a thing. Shooting an elk in the rump wont be as effective as shooting them in the heart. Will hunting rifles be a thing?"

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#337
