### ISSUE TITLE
All generated worlds are snow

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3029]

**Comment by metachronism** [comment]
verified this happens in staging.

**Comment by knexer** [comment]
Reproduced.  When it's happening, the various biome layers are all 0 everywhere, except for tundra for some reason which is at 0.4 everywhere.  /shrug
After the first tick, all the biome layers are updated and all surface blocks are changed to the correct biome.  So it's an init order thing.

**Comment by knexer** [comment]
Fixed
