### ISSUE TITLE
Client prediction todos

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3030]
Reminder... still need to handle quick placement more gracefully (ignore chunk updates that remove predicted changes)
Also probably need to store the last reliable received state for blocks to help resolve multiplayer collisions.

**Comment by seccombew** [comment]
@metachronism thinks this is no longer an issue.

**Comment by SeanAtr0n** [comment]
high priority? it's still an issue...

**Comment by WeaselDog** [comment]
This is related to https://github.com/StrangeLoopGames/EcoIssues/issues/3189. It might be resolved; it is being investigated.

**Comment by D3nnis3n** [comment]
This is no longer occuring in the current version. If this issue reappears please open a new issue.
