### ISSUE TITLE
Furniture does not enforce room requirements

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3031]
As stated in title you can basically place furniture either outside or in any room with out it enforcing room size requirements, most don't even display they are using any space in the room and will show 0 m3 / xxx m3

**Comment by stormoffires** [comment]
![2017-12-08](https://user-images.githubusercontent.com/20627148/33766484-e16d9832-dbda-11e7-9ee6-dab75885e4b1.png)

nothing in the room but 2 beds.. beds dont register as taking up space but are contributing points

**Comment by stormoffires** [comment]
Just to add a side note due to this error, folks are reporting 300+ sp/day houses. Correct this should fix daily sp with out need to rebalance furniture.

**Comment by johnkslg** [comment]
Fixed
