### ISSUE TITLE
 A room Across Deeds (Furniture only scores on each part that is owned by a person)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3032]
I Built a test Room that crosses across Deeds, if i place the chair on other Side of room (another deed) that person scores that chair
![snap673](https://user-images.githubusercontent.com/29383891/33768567-778355e4-dc1e-11e7-995e-b95ce9d2b503.png)
NataSha's Original score
![snap668](https://user-images.githubusercontent.com/29383891/33768766-443afc04-dc1f-11e7-9504-8c3e2bfb7a05.png)

If i Place chair on my side of the room i score that chair
![snap674](https://user-images.githubusercontent.com/29383891/33768601-90aedf34-dc1e-11e7-8d71-4a0c68585734.png)
my original score
![snap669](https://user-images.githubusercontent.com/29383891/33768741-2e059d0e-dc1f-11e7-8d23-a774db15b73e.png)

is this correct? i thought that if we shared deeds each person could score points from same rooms (think this was mentioned as possible in Discord)

**Comment by MarjieAVolk** [comment]
That sounds like reasonable behavior.  Are you saying both people were authorized on both deeds?

**Comment by Conchipedia** [comment]
yes we are sharing deeds, so it seemed logical to have a room crossing both deeds

**Comment by BlazeGuy2** [comment]
Doesn't seem like a bug.  Closing.
