### ISSUE TITLE
Run for office exception

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3033]
When running the Eco Server in debug mode - Clicking "Run for office" in the web GUI, I get an unhandled exception:

System.Exception: '<style="Error">Cannot violate law 'Citizenship'.</style> Your Play actions Ever (1.26) is less than 2; Action not allowed.' from Line 80 in ControllerUtil.cs

**Comment by MarjieAVolk** [comment]
Actually this is a duplicate of this: https://github.com/StrangeLoopGames/EcoIssues/issues/2994

Copying your comment over there
