### ISSUE TITLE
Latency in store window when editing prices, quantities, and position

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3035]
When clicking rapidly in a store window to adjust price, quantity, or position, you can get a strange behavior where the number will jump up and down, as well as the position of the item you are trying to edit. 

Either the game should assume the server will grant permission to change properties and update if told otherwise, or the + and - buttons along with ^ and v buttons should be disabled until a server response has been given.

**Comment by ClayC90** [comment]
A better solution will be timeout,

When user stops clicking or pressing buttons to adjust price for 1s, send the new data to the server, that way you do 1 request to the server and avoid any hip-hop-ing :)
