### ISSUE TITLE
[Suggestion] Show Room Type in the same window that shows Room Volume

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3038]
![snap194](https://user-images.githubusercontent.com/29383891/33790323-1d8d7336-dc77-11e7-925e-a45d2042bb47.png)
Would be nice to see the Room type when we enter a room, this way it will be easier to work out which room is which, rather than guessing which room we need to fix or improve

**Comment by brad992** [comment]
This drives me insane, such a simple idea, why is this still not added to the game?

**Comment by Conchipedia** [comment]
maybe this can be added a the same time (while in that window)
[Suggestion] Updating how much Free space is available in a room (calculations are already in place) #3024

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#387
