### ISSUE TITLE
Mini-map zoom stops rendering land/water

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3039]
If zoomed out too far, the mini map stops rending land/water. 

![image](https://user-images.githubusercontent.com/27159777/33790556-f2a23d82-dc35-11e7-82f8-6cacce2b2313.png)

**Comment by julrich1** [comment]
This is particularly noticeable on a small world. To repro, create a 10x10 dimension world and climb up to a mountain. The minimap will stop rendering properly and won't return to a normal state, even on lower ground.

![image](https://user-images.githubusercontent.com/27159777/34054179-973650ac-e17e-11e7-8854-3746ed8dc3c1.png)

**Comment by SeanAtr0n** [comment]
fixed 7.3
