### ISSUE TITLE
Unlearn / Learn toggle doesn't work after unlearning a skill

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3040]
After unlearning a skill, toggling back to learn seems to be broken. The only fix is to reopen the GUI and toggling seems to work fine until unlearning another skill.

![image](https://user-images.githubusercontent.com/27159777/33790738-aa501caa-dc37-11e7-8111-440b70bae0d3.png)

**Comment by Nanders** [comment]
This ui has been rewritten, so this bug is unlikely to exist anmore
