### ISSUE TITLE
Scientific data map blending issue

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3041]
One the web console, the mini map has a blending issue between land elements.

3D mode:
![image](https://user-images.githubusercontent.com/27159777/33790916-97fc3686-dc39-11e7-98f7-5e43468691bd.png)

2D mode: 
![image](https://user-images.githubusercontent.com/27159777/33790924-a58eafa4-dc39-11e7-8ac5-0e7964ca6cd0.png)

**Comment by MarjieAVolk** [comment]
This looks a lot like what I was seeing here, and lost the screenshot of: https://github.com/StrangeLoopGames/EcoIssues/issues/2959

**Comment by MarjieAVolk** [comment]
I don't even know, do web and unity maps share much code?

**Comment by rainfarmer** [comment]
old issue
