### ISSUE TITLE
Propose new law when not logged in from web interface throws an exception

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3042]
If you navigate to the server without authenticating correctly (ex. http://localhost:3001/index.html) and try to propose a new law, the server throws exception "System.Exception: 'null is not a user on this server.'" in ControllerUtil.cs line 87

**Comment by MarjieAVolk** [comment]
Yeah that's expected behavior actually - the web server code throws exceptions as its method of propagating error messages to the web client in a lot of places.  It's a bit strange when debugging, but if you hit continue you'll see the error message in the web client as expected
