### ISSUE TITLE
Hair anchored to the body/backpack instead of head

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3044]
A particular hair style seems to be improperly anchored and clips into the players head. This seems to only happen for the masculine body type.

![image](https://user-images.githubusercontent.com/27159777/33791197-3db1ce26-dc3d-11e7-892e-87a790b04923.png)

**Comment by MarjieAVolk** [comment]
Yeah that's been there for a while O.o Avatar art is getting completely redone though, that's already in master now, so closing this as out of date

**Comment by MarjieAVolk** [comment]
Ah yes, here is the duplicate bug: https://github.com/StrangeLoopGames/EcoIssues/issues/1423

Closing that one too actually :P
