### ISSUE TITLE
Refresh the entire law logic tree when changing a drop down selection

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3047]
I had specified earlier that when changing a drop down selection, the web client could just refresh that drop down node and its children.  But for stats and districts, I'm finding that is no longer the case, and the whole tree needs to be refreshed.  On the marjie-statDatabase branch, I've updated the queries listed below to return the root LawLogicNode, instead of the edited LawLogicNode.  Can you update the UI to refresh the root node also?

* logicDraft/list/setIndex
* logicDraft/list/remove
* logicDraft/list/add
* logicDraft/number/set
* logicDraft/dropdown/set

**Comment by syuzan-yeranosyan** [comment]
done on "marjie-statDatabase" branch
