### ISSUE TITLE
Chat window taking focus

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3049]
When the chat window is open behind another window (such as a work bench), if a message comes in, the chat window becomes the top most window.
That can be problematic when stacking windows or having some slight overlap as the chat window will now obstruct your view.

![image](https://user-images.githubusercontent.com/27159777/33791674-70164606-dc44-11e7-8145-c30344732e41.png)

**Comment by MarjieAVolk** [comment]
Oops, I fixed this a little while ago, the fix is already released 👍
