### ISSUE TITLE
Property claim tutorial pops in and out

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3050]
The property claim tutorial behaves in an odd way. It appears to only pop up when you are near and looking at the workbench. If you get too close to the workbench is disappears and generally seems to be confusing. It should probably trigger and stay up until the user puts a property claim flag down.

**Comment by MarjieAVolk** [comment]
All of the tutorials are context sensitive, so yes it will only be up if you are near an object that belongs to you.

If the popup disappears when you are too close to the object, that is a bug.  I'm guessing what's happening is that it's getting placed over in the upper right when you get too close to the table?  If that is confusing, maybe we should animate that movement.

**Comment by julrich1** [comment]
I think the biggest issue right now is that with the property claim tutorial in particular, it's not based on radius to the player, it's based on is the player looking toward/at the workbench. It should probably be changed to radius which would eliminate some of the confusion of it popping up/hiding when looking around near a workbench.

**Comment by johnkslg** [comment]
Replaced tutorial
