### ISSUE TITLE
Backpack closing constantly

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#3053]
The backpack is no longer staying open like it did in 6.1.1 and previous versions. Now whenever you do anything is closes instantly. This is annoying for any gathering task because you have no idea how full your inventory is. It also is making it very hard to keep track of the items I am currently holding. 

Secondly, every time you want to access a stockpile or chest, you now have to get in the habit of pressing b every single time.

**Comment by MarjieAVolk** [comment]
It seems a lot of people like the backpack to stay open

**Comment by Yorkforce** [comment]
Just to add as it's likely related, deed windows also close when moving, this makes unclaiming via deed frustrating as you have to reopen the deed each time.

**Comment by MarjieAVolk** [comment]
Ah yeah, well deed unclaiming should be changed anyways O.o

**Comment by cuda70** [comment]
I agree this is very frustrating backpack needs a option stay open or close on movement I like to have it open all the time
