### ISSUE TITLE
Unable to see room information when you have too many rooms

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#3054]
When you reach about 15 rooms, when you hover over the skill point boost, you can no longer see all of your rooms and it looks weird. Maybe putting this information somewhere else would be a good idea and have the hover just give an overview?

**Comment by Conchipedia** [comment]
getting the same problem
<img width="1280" alt="snap129" src="https://user-images.githubusercontent.com/29383891/33818334-2423302a-de3c-11e7-91dd-015fe59c3208.png">
and i have less than 15 rooms, we need it to open a separate window with possibly a scroll bar

**Comment by brad992** [comment]
Exactly what I am talking about, agree with your suggestion too

**Comment by Conchipedia** [comment]
this seems to be the same sort of Problem as this:
Tooltip goes off screen #2061
maybe related

**Comment by MarjieAVolk** [comment]
Yeah that is not working too well.

**Comment by johnkslg** [comment]
We have scroll bars on tooltips now.
