### ISSUE TITLE
Server Selector should be less heavy

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3057]
With the scene in the background, some pcs may not cope with this well as it seems to have high quality graphics,

This should either mimic the design of the website or have a simple design for the server selection screen,

**Comment by kicker22004** [comment]
I feel like that screen is a great test to see if your machine is up to the task of running ECO. You can change your settings on that page to make it smoother. It uses the same textures that is seen in-game.

**Comment by ClayC90** [comment]
I agree kicker, but when you are just browsing for servers, your machine shouldn't be used that much, this is also used on all other games, as they implement more search functions and it has to handle many changes across the screen,

Producing less lag :)

**Comment by metachronism** [comment]
the background is barely more than 100 draw calls, its already super light and lower quality compared to in-game
