### ISSUE TITLE
[6.1] Moving items in storage/pack cause graphical error

### ISSUE THREAD

**Issue by TreeNuts** [StrangeLoopGames/EcoIssues#3058]
When moving items around storage boxes and backpack the item icon locks up on the screen and becomes unviable until the game

**Comment by TreeNuts** [comment]
... until the game looses focus (alt+tab out).

**Comment by cuda70** [comment]
Reported this 10 days ago #2955

**Comment by TreeNuts** [comment]
I'll post updates to #2955. Thanks

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate
