### ISSUE TITLE
Server needs New Build Popup Message

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3059]
Add a popup to server browser/launcher that will let users know when a new client/server build has been released.  Not all server owners see console (on hosted servers) or may not always be checking the console but would like a notice to pop up somewhere on server browser to show what is the latest stable release and what is the most current staging that is available.  I know its possible to tell that if you click 'show incompatible' and others have installed a build that has just been released but that means you have to count on someone having installed a build that was just released.  Even if it was just a small text line at the bottom of the browser listing the most current would be very helpful

**Comment by kicker22004** [comment]
I agree with this, I know when I used to try to join my server and it's missing I automatically assumed the server was down before I started checking Incompatible list.

**Comment by metachronism** [comment]
This is likely going to be irrelevant after steam release

**Comment by MarjieAVolk** [comment]
I would think it would be more relevant after steam release.  Since clients would get updated automatically, but servers wouldn't

**Comment by pamduncan** [comment]
I agree with MarjieAVolk and actually it was because of discussion about how things would be handled once the game releases on steam that this came up.  Unless you set a game not to update it will update and a user might not even know that happened but would be unable to find their server (if it was not updated) and not know why.  This also brings up another concern.  Once a release build is pushed to Steam and auto updates the client if the admin chooses not to update right away for whatever reason (and many do wait) will there be a mechanism where players can opt into 'beta' (what they usually call it) and choose an alternate version such as dropping back to the previous version - or if wanting to play on staging can do that also.  On steam, if you not opted into the game's alternative version program (aka beta)  you can tell it not to auto update your client but that just means it does not run the update until you hit 'play' and then you get the latest version.  At that point, if you are not already set to be opted into beta and have selected the version you want/have installed you have to opt into whatever you will call the programs that allows for alternate versions and roll back to the version your server is still running.  Having some message in the server browser  that lets players know what is currently the stable release  and when that was released is about the only way I can see to help avoid the confusion of people trying to figure out if a new version has been released or what is going on.  If steam noted a game it update with a 'recently update' flag of some sort so that people knew they got an update that would be great but they don't and most players don't know about or how to check tehir download queue to see if a new version has recently been pushed to them.

**Comment by MarjieAVolk** [comment]
To answer your question (if that was a question), you will be able to select beta/staging as an option on steam.

**Comment by pamduncan** [comment]
Yes I did wonder if there will be an option to opt into staging via steam for the server although we are jot sure if steam updates will be the direction we go or not if the downloads are also going to continue being available through the Eco website.  Steam is not always the most hospitable way to download/install updates for a server provider

**Comment by metachronism** [comment]
passing this off - I dont think this is necessary to be done, it has marginal benefit
