### ISSUE TITLE
[Enhancement] Server Browser Refresh Timer

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3060]
Is there anyway to show a bar/counter for when 'refresh' is running when you log into the server launcher - its frustrating to be scrolling through the browser and be halfway down the list and refresh repopulates with more servers and then as you are halfway through again the same thing happens again.  I know it stops after a few minutes and does not happen again unless you hit refresh but there is no way to know that the 'refresh' has finished counting through servers and the list is refreshed.  If there was a bar or a counter that showed that the refresh was complete that would be helpful

**Comment by kicker22004** [comment]
Please yes!

**Comment by ClayC90** [comment]
actually this is not the ideal solution,

The solution is first time loading it will add servers, but servers that are being added next should go on the bottom not to interfere with users' browsing, we should have sort by ping which will allow users to then decide to sort the list by ping,

on update the list will not re-generate, but instead will update the coresponding ping value of the servers, and if it goes offline, the offline message appears, any new servers found, will be added to the list using the above mentioned logic,

Yes it is complex, but this is the end goal of the server browser, so better start implementing it properly :P

**Comment by MarjieAVolk** [comment]
In the 7.4 release, there is now a spinning gear icon that shows whether the browser is still working.  As for @ClayC90 's response, the new default is for the list to appear unsorted (thus new entries will be added to the end of the list).  Sorting by ping, world age, and online players is supported via buttons in the column headers, though enabling sorting will cause the list to behave as before, inserting new entries in sorted order.  However, refreshing will still cause the list to be completely regenerated.  Hopefully that addresses most of the concerns.
