### ISSUE TITLE
[Art] Windmill Power Unit can be hidden with a Block 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3062]
As seen here No block (just power unit showing)
![snap696](https://user-images.githubusercontent.com/29383891/33846104-839a3d30-de9d-11e7-96b9-1729374b85b1.png)
With block (slight graphic glitch)
![snap697](https://user-images.githubusercontent.com/29383891/33846127-96943e54-de9d-11e7-97bd-3de7f2f6328c.png)
Views from Front (with and without block)
![snap699](https://user-images.githubusercontent.com/29383891/33846164-ab30f9f6-de9d-11e7-8d49-ee7baa389f14.png)
![snap700](https://user-images.githubusercontent.com/29383891/33846180-b40a9320-de9d-11e7-9e8d-3ad2a197ac68.png)
This can also be done with a Brick block (probably others as well)
![snap701](https://user-images.githubusercontent.com/29383891/33846206-cdffc426-de9d-11e7-911a-e71e13ef1e18.png)
![snap702](https://user-images.githubusercontent.com/29383891/33846212-d71c4c3c-de9d-11e7-9b4f-bb144ac655d2.png)
Personally i like the way that a block can hide the Power unit (the square opening at times looks a bit ugly)

**Comment by Conchipedia** [comment]
Not sure if this is a bug or something that is Possible to do, possibly leave it available to do, but just hide the slight glitch at the back part

**Comment by MarjieAVolk** [comment]
I am not sure either, @Nanders & @keegan-o this belongs to one of you... either add occupancy there, or fix the clipping in back.

**Comment by WeaselDog** [comment]
Windmill power unit now occupies the block:
![WindmillOccupancy](https://user-images.githubusercontent.com/47330823/71283116-1c56f380-2314-11ea-8191-d3045e67a505.png)
