### ISSUE TITLE
Reduce bonus from housing skill

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3063]
https://cdn.discordapp.com/attachments/258375026435162112/389750463278612482/unknown.png
It gets pretty nuts now. We can do this by reducing the value of duplicate rooms/objects from 75% to 50%, and adding multipliers for room materials, and turning down values.

**Comment by MarjieAVolk** [comment]
Sounds like the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/3068?  Closing that one

**Comment by stormoffires** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3031

Does not need rebalancing simply fix furniture to exist physically in the room. Right now it does not take up any space

**Comment by johnkslg** [comment]
Rebalanced and changed how capping works.
