### ISSUE TITLE
Player arrows look like a bunch of male symbols

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3065]
![image](https://user-images.githubusercontent.com/3536496/33852658-44e4f7b0-de70-11e7-945d-ebd6a6ba029b.png)

**Comment by Huntermeign** [comment]
then tell them to look south to make it more feminine?

**Comment by BlazeGuy2** [comment]
@johnkslg is this related to the icons not changing the direction that they are facing?

**Comment by WeaselDog** [comment]
They look much nicer now:
![PlayerArrows](https://user-images.githubusercontent.com/47330823/70764623-ef4f8300-1d0c-11ea-8996-c8fcee17ba35.png)
