### ISSUE TITLE
Chat notices are annoying

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3067]
![image](https://user-images.githubusercontent.com/3536496/33853647-83a44f2a-de73-11e7-8adc-811e44dc57f8.png)
Maybe just the most recent per player?

**Comment by metachronism** [comment]
you can just disable the channel if you find them annoying

**Comment by MarjieAVolk** [comment]
That's what we all do :/  I am for reducing number of messages sent.  And/or world space notifications, which would mean you wouldn't see these unless you were near the table.  Or moving this information to a world object log that's visible only in the world object UI.

**Comment by brad992** [comment]
I like these messages, it keep me completely up to date with what everyone is doing. If there are no messages, I get suspicious

**Comment by elfl0rd** [comment]
@D3nnis3n can you look? this and https://github.com/StrangeLoopGames/EcoIssues/issues/10295

**Comment by SlayksWood** [comment]
@johnkslg 
Are you planning  remaking? or it's good for now.
![image](https://user-images.githubusercontent.com/45708377/68668800-12deac80-055a-11ea-87bc-47463390c914.png)

**Comment by WeaselDog** [comment]
There was big chat remake since this issue was opened and notifications are different. We have a Chat UI Overhaul epic we can put specific issues into.
