### ISSUE TITLE
 Separate notices from user chat, chat scrolls off screen too quick

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3072]
We should have chat stay on the screen longer than notices, and in a separate display

**Comment by MarjieAVolk** [comment]
Oh you mean like world space notifications? :P

**Comment by metachronism** [comment]
given that this is already configurable, why not leave it as is?

**Comment by elfl0rd** [comment]
@D3nnis3n ? https://github.com/StrangeLoopGames/EcoIssues/issues/10295
