### ISSUE TITLE
 After placing down a block, it highlights red for interaction

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3073]
Noticed this several times while building

**Comment by MarjieAVolk** [comment]
I've seen false negatives on the interaction highlight a lot in general

**Comment by Huntermeign** [comment]
I've seen then in any property that was owned that I had perms in, even the ones I own. It takes a second or so to become green.

**Comment by BlazeGuy2** [comment]
fix was merged but this wasn't closed
