### ISSUE TITLE
Interaction effects spawn before interaction actually happens

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3076]
Dig => See effect spawn => turn to drop dirt => interaction actually performed on block as you're spinning.

**Comment by SeanAtr0n** [comment]
I'm guessing you are actually seeing the block placement preview fill in the new hole immediately... in that case the issue is that the block placement preview is too opaque

**Comment by Nanders** [comment]
Naw its definitely a delay in interaction, can see it happen in current staging
![dig bug](https://user-images.githubusercontent.com/6262198/33909829-babb3324-df41-11e7-83ed-f51e4a5d9a71.gif)

**Comment by Huntermeign** [comment]
This is definitely something that happens even after hearing the sound queue. Dig, spin to drop into cart, put in cart. Turn around to find out I dug a hole in the wall and not at the spot I thought I was digging.

**Comment by SeanAtr0n** [comment]
In the gif above you are turning while digging and the effect spawns in the location you ended up digging... i don't see an early spawn effect.

**Comment by Nanders** [comment]
Might just be the audio then, but that should be happening at the same time as the interaction.

**Comment by SeanAtr0n** [comment]
i suppose this is fixed
