### ISSUE TITLE
Unchopped down trees highlight yellow, they should be green

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3079]
I assume this is something to do with client side interactions

to clarify, it should be:

target tree with axe -> green
tree is felled and is choppable, but not pickupable -> yellow
tree is pickupable -> green
tree on someone elses property -> red

**Comment by SeanAtr0n** [comment]
twas yellow before, i thought that was intentional if you want yellow to mean 'you can chop this'

**Comment by BlazeGuy2** [comment]
seems to be working when I tested, closing issue.
