### ISSUE TITLE
Some Actions not registring due to fast clicking?

### ISSUE THREAD

**Issue by sLesage** [StrangeLoopGames/EcoIssues#3080]
When terraforming (picking up dirt using the shovel) I had a lot of issues that it just didn't regsiter. After some more playtime I noticed it's actually a strange issue happening in game. When I click slower it works, when I click too fast, it sometimes doenst (yes I could replicate this).

To me it seems like it needs ot regsiter a certain amount of time between the OnMouseDown and OnMouseUp events, or a longer period of time the mouse button has to be pressed. Not sure if that's intended, but I did notice that when clicking slower i got rid of that annoything thing.

I'll try to record a little video showing the issue and upload it to my YouTube channel. I'll update this thread when I do.

**Comment by MarjieAVolk** [comment]
Not sure if I understand, but you do need to hold down the mouse button in order to dig.

**Comment by sLesage** [comment]
Do you need to hold the mouse button down, or do you have 
to click? If a simple click isn't enough then that's 
probably the issue I've been encountering. Let me try to 
record a sample video to demonstrate what I mean.


On Mon, 11 Dec 2017 16:17:07 -0800
  MarjieAVolk <notifications@github.com> wrote:
> Not sure if I understand, but you do need to hold down 
>the mouse button in order to dig.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/StrangeLoopGames/EcoIssues/issues/3080#issuecomment-350901928

<div id="_htmlarea_default_style_" 
style="font:10pt arial,helvetica,sans-serif">Best 
regards,<br>Stefaan
Lesage<br>__<br><br>Devia<br>Software Development &amp; 
New Media Technologies<br>Boekweitbloemstraat 9 - 9940 
Ertvelde
- België<br>http://www.devia.be</div>

**Comment by sLesage** [comment]
The question then is ... for how long ? And is it the same 
for any gathering of materials ( wood / stone / dirt / ... 
)

On Tue, 12 Dec 2017 11:29:51 -0800
  MarjieAVolk <notifications@github.com> wrote:
> Yeah, as I said, you need to hold the mouse down
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/StrangeLoopGames/EcoIssues/issues/3080#issuecomment-351166689

<div id="_htmlarea_default_style_" 
style="font:10pt arial,helvetica,sans-serif">Best 
regards,<br>Stefaan
Lesage<br>__<br><br>Devia<br>Software Development &amp; 
New Media Technologies<br>Boekweitbloemstraat 9 - 9940 
Ertvelde
- België<br>http://www.devia.be</div>

**Comment by MarjieAVolk** [comment]
Deferring the question to @SeanAtr0n - Did this change recently?  Are the timings set up right for all the tools?
