### ISSUE TITLE
Make random avatars less ridiculous

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3087]
Suggestions:
- Hard code a set of starting clothing colors
- Make hair color be darker than skin color

**Comment by WeaselDog** [comment]
Issue moved to [StrangeLoopGames/EcoSuggestions #1125](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1125) via [**ZenHub**](https://www.zenhub.com/)
