### ISSUE TITLE
Mow contract discrepancy

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3089]
After finishing mowing all the blocks for a mowing contract, the contract wouldn't let me mark it as finished due to unmowed grass. Everything appeared to be mowed on the client, but it looks like one block was being registered as unmowed still. After going back and mowing the mowed tile again, it let me complete the contract, so there may be a sync bug between the server and client.

**Comment by BlazeGuy2** [comment]
Just tested on 7.4.6, seems to be working now.  If it comes up again, let me know.
