### ISSUE TITLE
Missing chunks

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3091]
Saw this a couple times just now on marmot.  In this case, we had 2 different people who saw this same chunk as missing, but a for a third person it loaded fine.

![image](https://user-images.githubusercontent.com/23460210/33910171-acc0ee8e-df42-11e7-95ad-e166d0d1a7ff.png)

**Comment by craig-jong** [comment]
I had this happen to be when I cancelled a work order - may or may not be related.

**Comment by metachronism** [comment]
not a real bug, problem with branching.
