### ISSUE TITLE
User shouldn't be able to accept and complete their own contract

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3094]
Current it is possible to accept and complete your own contract.

**Comment by johnkslg** [comment]
This is enabled for devs by design.

**Comment by MarjieAVolk** [comment]
For devs only?  This guy is seeing it, and he's not a dev

**Comment by johnkslg** [comment]
Was admin or dev, fixed to 'dev' only. In next PR
