### ISSUE TITLE
Brodie Bug: Avatar screen had a gray color behind the avatar

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3096]
.., which made it feel less alive and a little unfinished.

**Comment by MarjieAVolk** [comment]
Not sure what would fix this, just like a different color?  Or are we thinking like some kind of simple scene with grass or something?  Think an artist should think about that

**Comment by MarjieAVolk** [comment]
closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3097
