### ISSUE TITLE
Brodie Bug: Clutter in roll over tool tips - maybe hide "top users?"

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3101]
Perhaps we put more tooltips into sub-lists

**Comment by metachronism** [comment]
top users is just the tip of it.  almost everything in a lot of tooltips is pretty useless information

**Comment by WeaselDog** [comment]
We have had significant updates to tool tips, including sub-lists. If there are any remaining tool-tips we can make an issue for them.
