### ISSUE TITLE
Brodie Bug: Skill points icon too small

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3102]
-the skill points icon is super small but is actually the #1 most important thing to do when starting. Make it a bigger deal and call to action.

**Comment by MarjieAVolk** [comment]
I have been planning to make this an action bar button.  Could be a special looking action bar button though

**Comment by Nanders** [comment]
Agree skills should be an actionbar item. Can still be glowy/special.

**Comment by MarjieAVolk** [comment]
By the way, Milenko is working on new HUD art which will include a special skills button in the action bar.  Will be larger and in the far right corner of the screen
