### ISSUE TITLE
Brodie Bug: Icon contrast isn't high enough

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3104]
Wish this map was more legible - for example it was hard to figure out that the tan square was my position - contrast isn't high enough
The map could have more "points of interest" on it to to lead me around the planet. Nothing really stands out as exciting or important at a glance.

**Comment by keegan-o** [comment]
No more image, not sure if any of this is relevant anymore since player icons have been updated.
