### ISSUE TITLE
Brodie Bug: Meteor needs calling out

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3105]
-I saw in the descriptions of some worlds in the server browser that there is a meteor of some kind. I wish this goal or event was called out, as right now I feel a bit rudderless. That would at least give me a sense of urgency to do things. Night came and there wasn't much conflict, so I know that it is not about surviving the night. That said you don't want to drive the tension up as it may stop people from being creative/explorers so that probably isn't the right solution. Micro goals I can get excited about likely are.

**Comment by knexer** [comment]
I'm thinking this is probably resolved by the recent tutorial changes
