### ISSUE TITLE
Brodie Bug: Left/Right click to use was confusing/unintuitive

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3106]
"Perhaps it has a bit to do with that I am not totally grokking the control metaphor right now. My instinct is to left click on things, but many times right-click is the actual "action" button. Other items are in my bar, like a tomato, and when I select it, it doesn't bring up the tomato in my hand. And I can't seem to do anything with the tomato, like eat it. The mixing of what objects do, and how I can control them is confusing. On screen prompts like on Minecraft Xbox360 would likely help here, so that I know my possible actions at all times.

Clean up the usability, and find ways to unify the interactions for each item. Make left and right click do the same thing, or give clearer feedback when an item is different."

John: I would like to have controls appear on screen for this stuff.

**Comment by Nanders** [comment]
> John: I would like to have controls appear on screen for this stuff.

Same as https://github.com/StrangeLoopGames/EcoIssues/issues/2776?

I don't think that solves the problem with the interaction design, need to normalize the control scheme so things always work as people expect them to. The most problematic being the ambiguity between "Interact Left", "Interact Right", and "Interact".

**Comment by MarjieAVolk** [comment]
Yeah I basically was going to say the same thing, almost closed as a duplicate.

I feel like our control system isn't too bad in general - that is left click to break/take, right click to use/place.  'E' is kind of everything else though, which is weird.  For me, 'E' to harvest with no tool is one of the worst things.  Wonder if we could have left click with empty hand show a hand grabbing animation and take the plant, or something?  That would be more consistent.

**Comment by Nanders** [comment]
>  Wonder if we could have left click with empty hand show a hand grabbing animation
This is my favorite solution to this problem, why haven't we thought about that

**Comment by MarjieAVolk** [comment]
Lol thank you for clarifying.  At first I didn't realize you were quoting me, so I was gonna say jinx.

**Comment by MarjieAVolk** [comment]
Is there anything else that uses 'E' besides world object ui and harvesting plants?  We might be able to remove 'E' completely.

...And then use it for the skills UI hot key ;)

**Comment by Nanders** [comment]
Doors, accessing UI without placing your carrying slot into the table.

**Comment by MarjieAVolk** [comment]
Oh yeah, putting items into the table, that's right.  It was too good to be true.

**Comment by MarjieAVolk** [comment]
Well anyway, all those random things that get picked up with 'E' though should become left click

**Comment by Nanders** [comment]
Agree

I would argue E is still useful for some things, but as it's used now its a little too band-aid-y

**Comment by MarjieAVolk** [comment]
how about Left click = break/take, Right click = consume/place, E = interact/get details

**Comment by johnkslg** [comment]
Closing with addition of control popups.
