### ISSUE TITLE
Inventory snap too restricted

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3107]
Not sure if this was mentioned before because I wasn't exactly sure how to word it, but I feel the drag and drop method of moving inventory items around should be more liberal when snapping into an inventory space. Right now I have to be almost directly above the intended space before dropping for the game to register where I am dropping it.

**Comment by MarjieAVolk** [comment]
Might help also if the inventory space you are over would highlight, so you can tell whether you can let go now or not

**Comment by metachronism** [comment]
I think this is more because the mouse cursor has to be in the target position in order for the drag 'n drop to work.  It would work better if it did a rect collision test to find the target slot to move the item into

**Comment by MarjieAVolk** [comment]
You think?  That seems weird, but idk.  Well the cursor position has less lag than the rect position for one thing.

**Comment by elfl0rd** [comment]
@Quadbro it looks as your inventory changes :D

**Comment by WeaselDog** [comment]
It is very flexible with inventory snap now. In this picture it will move the berries from the left block to the right block if I release the mouse. The cursor is just barely into the right block.
![InventorySnap](https://user-images.githubusercontent.com/47330823/71288805-5d550500-2320-11ea-8c53-8154cbbd3c63.png)

**Comment by WeaselDog** [comment]
Thanks for the info all. The primary issue is fixed. The suggested improvements has been merged: https://github.com/StrangeLoopGames/EcoIssues/issues/6354
