### ISSUE TITLE
Saw mill, Fletchers Tool Shelf, Coopers Tool Shelf and Sanding Block (modules?)not there 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3108]
Occasionally for some unknown reason i get that these tables are NOT in a room (they show up on Crafting menu as being required) only way i found to fix this is to remove and replace the carpentry table.
as seen they are in My room
![snap707](https://user-images.githubusercontent.com/29383891/33914718-672e5b40-df97-11e7-954f-31013aa48453.png)
and the Room is certainly big enough and Not broken
![snap708](https://user-images.githubusercontent.com/29383891/33914734-804bff7e-df97-11e7-90fb-ffdcff57fee2.png)
not sure how to describe this Error (i think modules might be the right name for them) wasn't sure so just said all the ones that i lose

**Comment by MarjieAVolk** [comment]
It's possible the crafting UI is messed up, as in this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3078

I was just fixing this for the next release.  You could try this to see if it's the same bug - While you have the offending crafting UI **open**, open the skill UI also and put a point in any skill.  If it's the same bug, this should trigger a refresh and make the module show as present in the crafting UI.

**Comment by Conchipedia** [comment]
i moved the table so it fixed itself, i think it glitches after a restart, but if it happens again, will try and do what you said

**Comment by MarjieAVolk** [comment]
Okay well I'll assume that this is the same bug for now... if you get confirmation that that doesn't work, then I will look at this issue more closely

**Comment by MarjieAVolk** [comment]
If it's the same issue, will be fixed in next release

**Comment by brad992** [comment]
Pretty sure it is a completely different issue. I was happily making lumber in the carpentry table with the saw mill and then it stopped working. I already had the skill. I had to destroy and place again my carpentry table to get it to work again

**Comment by MarjieAVolk** [comment]
http://ecoforum.strangeloopgames.com/topic/3128/carpentry-table-loose-contact-to-sawmill/2

**Comment by craig-jong** [comment]
The sawmill no longer is a module - it functions as a normal workbench in the latest staging.
