### ISSUE TITLE
Not Able To Walk Around With Land Deed Open To Quickly Pull Up Land Stakes

### ISSUE THREAD

**Issue by MeatHex** [StrangeLoopGames/EcoIssues#3109]

**Comment by MeatHex** [comment]
White Land Stake Makers are also staying up in the world even after reloading game  and unclaiming land.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3053 (The bug is about the backpack, but deeds closing is discussed in the comments)
