### ISSUE TITLE
Opening a craft window is too slow

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3110]
Takes a few seconds, feels very unresponsive.

**Comment by brad992** [comment]
Yeah, I get this every time. It's a good 3-5 second wait, I've slowly gotten used to it

**Comment by MarjieAVolk** [comment]
Didn't this used to work better at one point?  Like at least the second time you opened it, because of the caching.

**Comment by johnkslg** [comment]
@serpopov solved this!
