### ISSUE TITLE
[Enhancement] Admin command to add reputation points

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3111]
Could we get an admin command where the admin can either give themselves reputation points to use on players as rewards for their helpfulness etc or a command that would just award a reputation point to a player

**Comment by MarjieAVolk** [comment]
idk about this specifically, but maybe admins and/or server leader could get more reputation points to spend per day?

**Comment by Nanders** [comment]
This just got added as a QA command
