### ISSUE TITLE
Different text style used for skill tree name

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3113]
![image](https://user-images.githubusercontent.com/6262198/33966487-9e4304c8-e014-11e7-81e0-a076c6c047ad.png)

Note the visual difference between "Skills" and "Cooking Tree"

**Comment by MarjieAVolk** [comment]
Yeah think it just needs small caps turned on basically.  This whole UI is getting redone, so I'll keep that in mind.
