### ISSUE TITLE
[Enhancement] Add reputation color variable to reputation config settings in User.eco

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3117]
Add the variable for the color of a reputation level to the reputation section in Users.eco.  Currently it appears that rep level colors are either green or yellow - some server owners that are configuring their reputation levels to be more themed with their server would like to know if there is a way to set the color for each reputation level

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#335
