### ISSUE TITLE
Invalid placement of carry item causes ghosted item

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3123]
Normally when placing a carry item in an invalid location the user gets a prompt of "Invalid location" and the item is returned to their carry slot. If you place a carry item in an invalid location and it's the only one in the stack, it will still say invalid location but the item doesn't display in your inventory until you pick up another object. 
This can lead to some weird issues where you can pick up both stone and logs at the same time.

Here is a gif of the issue-
https://imgur.com/a/3Fyrb

**Comment by SeanAtr0n** [comment]
Nice, thanks for the ez repro example

**Comment by julrich1** [comment]
There is a similar version of this bug if you use a pickaxe on stone. It will disappear from the world and be ghosted in your carry item inventory.

**Comment by julrich1** [comment]
A little bit more detail around this - as soon as you place an invalid block like in the gif above, any future block placements will show up like they work as normal, but upon disconnecting/reconnecting, everything is reverted back to before the invalid block was placed. This includes digging / placing dirt, log placement, stone placement, etc.

**Comment by SeanAtr0n** [comment]
This should be fixed now, github just doesn't close issues that go into staging... are you still seeing it? (reopen if so)
