### ISSUE TITLE
Block placement below player can cause problems

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3126]
If the player places a block below their feet when they are near a wall, they can become trapped inside the wall. Players could become completely trapped like this if they didn't have enough calories to hatchet their way out.

Gif example - https://imgur.com/a/eY9Fn

**Comment by Nanders** [comment]
Does the /unstuck command handle this case?

New controller seems less prone to getting stuck too.

**Comment by julrich1** [comment]
Unstuck does teleport you out

**Comment by Nanders** [comment]
This is fixed with the new controller
