### ISSUE TITLE
Still unable to change tools and after 30 seconds I get kicked off server

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#3130]
Error box shows up says "Inactivity" (SAVE TO CLIPBOARD) I am active as i can eat food and open inventories I just cant use or select any tool 

Initialize engine version: 2017.2.0f3 (46dda1414e51)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
    Vendor:   NVIDIA
    VRAM:     4058 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.050 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

Setting up 8 worker threads for Enlighten.
  Thread -> id: 2eb4 -> priority: 1 
  Thread -> id: 1f6c -> priority: 1 
  Thread -> id: 69c -> priority: 1 
  Thread -> id: 287c -> priority: 1 
  Thread -> id: 23fc -> priority: 1 
  Thread -> id: 2c70 -> priority: 1 
  Thread -> id: 3bb8 -> priority: 1 
  Thread -> id: 3b64 -> priority: 1 
UnloadTime: 1.850755 ms
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
RPC lookup took: 3642.0176ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1510)

The referenced script on this Behaviour (Game Object 'PingTimer') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1753)

Missing following icons: CastIronSpigotItem, GraphsItem, PlanterPotRoundItem, PlanterPotSquareItem, RugLargeItem, RugMediumItem, RugSmallItem, SaltBasketItem, SmallTableItem, WoodenFabricBedItem, WoodenLattrineItem, WoodenStrawBedItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, AtmosphereRegulatorObject, AtmosphereTesterObject, ButtonObject, CompostPileObject, FisheryObject, GasGeneratorObject, LogicGateObject, MeteorExplodes, MeteorExplodesInAtmo, PlanterPotRoundObject, SteamGeneratorObject, SwitchObject, WoodenLattrineObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
GfxDevice: creating device client; threaded=1
Couldn't find mapping for object 'FisheryObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour (Game Object '<null>') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[System.String].VerifyState () [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1+Enumerator[System.String].MoveNext () [0x00000] in <filename unknown>:0 
  at ModBundleManager+<Cleanup>c__Iterator1.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1510)

The referenced script on this Behaviour (Game Object 'PingTimer') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'WorldObjects') is missing!
 
(Filename:  Line: 1753)

Missing following icons: CastIronSpigotItem, GraphsItem, PlanterPotRoundItem, PlanterPotSquareItem, RugLargeItem, RugMediumItem, RugSmallItem, SaltBasketItem, SmallTableItem, WoodenFabricBedItem, WoodenLattrineItem, WoodenStrawBedItem
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Missing following objects: AirPumpObject, AtmosphereRegulatorObject, AtmosphereTesterObject, ButtonObject, CompostPileObject, FisheryObject, GasGeneratorObject, LogicGateObject, MeteorExplodes, MeteorExplodesInAtmo, PlanterPotRoundObject, SteamGeneratorObject, SwitchObject, WoodenLattrineObject
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Couldn't find mapping for object 'FisheryObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

The referenced script on this Behaviour (Game Object '<null>') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1753)

InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[System.String].VerifyState () [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1+Enumerator[System.String].MoveNext () [0x00000] in <filename unknown>:0 
  at ModBundleManager+<Cleanup>c__Iterator1.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout
Ping: Error performing ICMP transmission. Possibly because of a timeout

**Comment by cuda70** [comment]
Still having the same problem 12/18/17 unable to play

**Comment by MarjieAVolk** [comment]
So is the problem to do with the toolbar?  You can't make any selections on the toolbar?  Or is it that you specifically can't equip tools, as opposed to other items?  If you drag a tool into the default selected space, does that work?

**Comment by cuda70** [comment]
cant select any tool also my cart is also frozen cant transfer from cart to storage hit number 1-0 cant select a different tool (shovel is currant selection and showing) cant dig also tried selection tool with mouse (no change) unable to grab and drag tool to backpack than i get kicked off says inactivity (copy to clipboard)

**Comment by MarjieAVolk** [comment]
Okay so sounds like you can't do anything.  What version of the game are you on?  Were you able to play on a previous version?  Are you able to play on a different server?  Are you able to play on a different computer?

**Comment by cuda70** [comment]
I am running 6.3.1 have been playing for about a year only have this computer this is only happening on this server

**Comment by MarjieAVolk** [comment]
Okay, it's specific to the server then.  So it's probably connection problems?
