### ISSUE TITLE
Marking a position should be a hotkey, not a chat command

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3131]
This is a useful feature that we shouldn't obfuscate

**Comment by metachronism** [comment]
it can still be a chat command, but really the functionality should be part of the minimap

**Comment by GophTheGreat** [comment]
It's part of the minimap now, but you have to move your minimap camera to center on the intended point. I think you should be able to place one on your first-person cursor.

**Comment by WeaselDog** [comment]
Players have the option to use the mini-map now. The mini-map is the more user-friendly way but still have chat commands.
