### ISSUE TITLE
Stockpile should stack when near capacity

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3132]
Scenario: Stockpile has every slot full but one of the stacks isn't at max capacity (see below image)

Behavior: User tries to add additional materials to a stockpile that would exceed max stack size. For example, trying to add 5 logs to the below stockpile, nothing happens under the current behavior and no error is shown.

Suggested behavior: If the user tries to add 5 logs, 2 of them should be removed from their inventory and added to the stockpile stack, and a message should be presented to the user that the stockpile is full.

![image](https://user-images.githubusercontent.com/27159777/34059026-0e10ce4c-e192-11e7-93bf-e330b757bb86.png)

**Comment by MarjieAVolk** [comment]
Hm I thought it already did this.  Will have to check on all the different methods of adding things to inventories.
