### ISSUE TITLE
Escape key should close backpack

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3133]
Escape currently closes all open windows except chat, mini-map, and backpack. It seems like escape should also close the backpack unless this behavior is intended? Maybe an option in settings would make sense here.

**Comment by MarjieAVolk** [comment]
Yeah I set it up to close the backpack originally, and everybody complained, so now backpack stays open :P

We were talking about having a 'pin' feature that would allow you to select whether a UI stayed open or not when you hit escape.  So everybody could be happy.  I thought there was an issue for that, but I can't find it, so I guess I'll leave this issue open.

**Comment by WeaselDog** [comment]
For using a controller this is an important feature
