### ISSUE TITLE
Tooltips have "Right Click to Consume" on icons that cannot be consumed

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3142]
![image](https://user-images.githubusercontent.com/6262198/34066341-45b8e8ae-e1c2-11e7-95b7-1edbe05dbe0f.png)

**Comment by MarjieAVolk** [comment]
oh yeah, the Controls type needs to be filtered out from the tooltip in that situation.

**Comment by D3nnis3n** [comment]
This issue is no longer there in 7.7, closing therefore.
