### ISSUE TITLE
Server constantly crashes / Restarts

### ISSUE THREAD

**Issue by Serynthara** [StrangeLoopGames/EcoIssues#3144]
Hello!
My server (vanilla) keeps crashing, and resetting the configurations I set (aka: It turns on the meteor again, etc).
The server is rented from a hoster, I'll post the most recent crash logs below.

[Crash IOException 12164701.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1564902/Crash.IOException.12164701.txt)
[Crash IOException 12164012.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1564903/Crash.IOException.12164012.txt)
[Crash IOException 12163335.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1564904/Crash.IOException.12163335.txt)

Thanks!

**Comment by Serynthara** [comment]
[Crash AggregateException 12160755.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1564957/Crash.AggregateException.12160755.txt)

**Comment by metachronism** [comment]
the first error is a file contention error, is the hosting service mucking with the gamesave?
the 2nd error looks like a bad config file.  make sure the formatting is correct for loading the users config
