### ISSUE TITLE
Pump jack comes up with weird fee,tax and message and wrong timer (but will craft) 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3145]
Just placed Steam Generator (needs art) and filled with coal
![snap719](https://user-images.githubusercontent.com/29383891/34072477-0b881d62-e280-11e7-8a46-4df9fc36d4d8.png)
placed Pumpjack (more than once)
![snap720](https://user-images.githubusercontent.com/29383891/34072482-1c6016ee-e280-11e7-9758-4360446e3c60.png)
then i open the window to craft and see this (more than once)
![snap721](https://user-images.githubusercontent.com/29383891/34072488-3a067094-e280-11e7-91c2-67eba65e4325.png)
The Fee i never entered (just appears as this)
The Tax i never entered (just appears as this)
the timer is wrong says 30 seconds to craft but in reality is 9 minutes 30 seconds (tried to get a snapshot as quick as i could to show this)
![snap723](https://user-images.githubusercontent.com/29383891/34072505-83e74f6c-e280-11e7-9c24-1279cdd8716c.png)
the fee and tax is the same no matter how many times i remove and replace pumpjack.

**Comment by Conchipedia** [comment]
just went and collected some iron ore, cam back to do another petroleum, this is now what i see

**Comment by MarjieAVolk** [comment]
What you are seeing is placeholder text.  Which means there was an exception while trying to initialize the UI.  Could you attach your client error log?

**Comment by Conchipedia** [comment]
i didn't get any errors with this so no log to attatch, and sadly now world is gone i cannot see it it could be duplicated

**Comment by MarjieAVolk** [comment]
Well I'm not able to repro this just with a pumpjack and a steam generator.  So guess this will go on the back burner until it can be repro'ed.

**Comment by Conchipedia** [comment]
it might have just been a hiccup that happened, it might not happen again 🤞

**Comment by MarjieAVolk** [comment]
Okay closing this due to no repro, if you see it again let me know
