### ISSUE TITLE
Steam Generator (cannot see any other storage or this storage be seen from elsewhere) 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3146]
![snap726](https://user-images.githubusercontent.com/29383891/34073181-b9bd9b36-e28b-11e7-8011-71419e92b923.png)
Also has No in game Art 
[0.5.6.1] No texture on Steam Generator Object #1779

**Comment by MarjieAVolk** [comment]
Looks like it doesn't have a LinkComponent on it.  Should have StorageComponent require LinkComponent.

**Comment by Conchipedia** [comment]
It also cannot left you Right click on it with fuel in hand (example Coal) to refill, maybe thats also the same thing

**Comment by MarjieAVolk** [comment]
Okay turns out this object is getting removed, so closing as obsolete
