### ISSUE TITLE
GiveSkillPoints Bugged

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#3147]
If you attempt to GiveSkillPoints to a player it crashes your client and you get the following error:

Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Could not parse string "ExPLiCiT"

Stack:
   at Eco.Gameplay.ChatManager.InvokeCommand(MethodInfo method, String args, User user)
   at Eco.Gameplay.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.ChatManager.SendChat(ChatMessage msg, String text, User user)

Maybe it is due to the combination of caps and lower case in the name? Unless they are used it doesn't recognize the player.

**Comment by pamduncan** [comment]
Don't think its a problem with mixed case in the name.  Happened to me in 6.2 also.  However I am able to GiveSkillPoints in 6.3, both to players and myself without errors or crashing

**Comment by stormoffires** [comment]
they have addressed this

https://github.com/StrangeLoopGames/EcoIssues/issues/3022

**Comment by Nanders** [comment]
This is fixed in new staging

**Comment by metachronism** [comment]
this hasnt been fixed.  FindUser needs to be tolerant of case for names, in some instances

**Comment by Nanders** [comment]
Well this specific bug is fixed, making finduser case insensitive is a different bug
