### ISSUE TITLE
Flying Trees are back?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3150]
I thought this had been resolved, if not I apologize for posting about it again.  I was chopping down trees in version Staging Alpha 6.3.0 #05f67449 and when the tree falls it goes flying away some distance (about 3/4 of the way to the horizon).  Also the debris and many of the broken branches go flying with it too.  I was clearing land along the beach and all my trees (as well as branches and debris) ended up in the ocean.  Great way to get rid of branches and debris but I sort of needed the logs and once they are in the water you can't get them.

**Comment by Huntermeign** [comment]
I notice this is 1.6.2 as well, sometimes when leaving an area for a good amount of time and returning the tree seems to be unaffected by gravity.

**Comment by SeanAtr0n** [comment]
This was fixed along w/ tree gaps
