### ISSUE TITLE
Items no longer listed for trading in stores

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3152]
can not see tree seeds in stores when trying to list for sale or buy.

**Comment by stormoffires** [comment]
updated - found more items not listed, Coal is another that can not be trade via stores

**Comment by Conchipedia** [comment]
think this is due to not having the skill unlocked ,it seems to NOT let you list something that you Don't know (why this should include coal not sure unless mining not unlocked)

**Comment by stormoffires** [comment]
mining is unlocked for me.. hmm another item not item is excavator isnt showing.

**Comment by Huntermeign** [comment]
I also don't see why it would matter if something was skill related or not. Shop owners in real life sell things they themselves do no make all the time.

**Comment by Conchipedia** [comment]
wasn;t sure why this was skill related but someone mentioned this before that it might be related to skills learned/not learned

**Comment by MarjieAVolk** [comment]
The unlocking is server wide, so it should not prevent individuals from trading.  It is based on server wide research level only.

**Comment by MarjieAVolk** [comment]
Although I feel like we should probably have a way of finding starting items, other than manually adding that attribute.

**Comment by Conchipedia** [comment]
for some reason Coal is not in Shop list either, i understand that some items cannot be sold or wanted till they are unlocked server wide, but wouldn't that be better to have ALL items available in the "wanted" side and only the ones unlocked in the for sale side?

**Comment by MarjieAVolk** [comment]
Hm, I was looking at this, and I think there's an easy case we can add for discovery - that is, when items don't have any recipes, they should start discovered.  Since we're using recipe skill requirements to determine what is discovered, some basic materials like that get left out.
