### ISSUE TITLE
6.2 can not see some steel and or iron tools in hands

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3153]
as the title says, they are there, as i can use them. However i can not see animation or the tool itself. 
so far i have seen the steel hammer and iron hoe, have not tested the rest just yet. will update as we find out

![2017-12-17](https://user-images.githubusercontent.com/20627148/34081917-92fa61e6-e312-11e7-9984-f9e86f73aa8f.png)

**Comment by Conchipedia** [comment]
same as
Iron hammer has no in hand model #2478
and
Iron Hoe doesnt show in hand and only shows green out line not clickeble #2877

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate ^
