### ISSUE TITLE
exclude stockpile changes from spawn block effects

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3156]
todo... or just reduce the number of simultaneous effects allowed

**Comment by mirasrael** [comment]
Remove  MapConfig.BlockChanged (which spawns block effect) from ChunkGridView.UpdateChunks and instead add RPC SpawnBlockEffect to AtomicActions.PlaceBlock and DeleteBlock. We don't want to have spawn effects for non player interaction initiated world changes (like /level or Stockpile changes). It probably will require to add spawnblockeffect to some other places after QA.

**Comment by johnkslg** [comment]
I actually like this effect, it looks cool when a big bunch of effects happens when you drop a bunch of items in a stockpile.

Instead just cap it so it doesnt hurt performance.

**Comment by mirasrael** [comment]
@johnkslg can you describe exact expected behavior?

**Comment by namquang93** [comment]
@johnkslg looks like it's already being capped at 5.
https://github.com/StrangeLoopGames/Eco/blob/develop/Client/Assets/Scripts/View/ChunkGridView.cs#L137

**Comment by johnkslg** [comment]
They were already capped at 5 so this bug should have been closed.

**Comment by redwyre** [comment]
The cap is just a bandaid solution, there's no guarantee how it will work in the game, and probably in many cases is just hidden (blocks inside stockpiles)
