### ISSUE TITLE
Some skills do not give you benefits at level 0

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3157]
ex. Buy skill, tooltip reads "+0%, next level +20%"

Confirmed is the case for Woodworking efficiency 1, but have seen it elsewhere too.

**Comment by craig-jong** [comment]
Tooltips do not update immediately. This needs to be checked to determine if this is the issue.

Woodworking efficiency I is properly giving me 20% cost reduction on the test server.

**Comment by MarjieAVolk** [comment]
Did somebody add caching for tooltips?  As far as I knew they updated immediately.

Nick is talking about level 0 though right?  As in researched but no skill points in it yet.  In which case +0% seems reasonable to me.

**Comment by craig-jong** [comment]
should be fixed
