### ISSUE TITLE
Need better server backups

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3162]
"Our server lasted 12 days before data got corrupted and none of my backups worked"

**Comment by MarjieAVolk** [comment]
This doesn't sound like something we can fix without more information.  My backups always work.  Maybe we need to save more backups and/or save them less frequently?

**Comment by metachronism** [comment]
this is already configurable and supported with the backup plugin

**Comment by MarjieAVolk** [comment]
Lots of people have started complaining about this recently.  We were talking about using a different strategy for how long to save backups (eg. expontential backoff) to help alleviate it.  We may also want to investigate what is causing them to get corrupted more frequently

**Comment by metachronism** [comment]
yeah, its already configurable though.  you can do backups on a different frequency if you want.

I changed the default now to 6 backups, once every 4 hours
