### ISSUE TITLE
Interactive component to skill gain

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3164]
"skills being gained via time/ nutrition are great. He liked how that worked. However he felt that an interactive component would be more satisfying as a second layer. (Even if minimal) Experience or a charge up buff of some sort for doing your specialized tasks."

**Comment by Huntermeign** [comment]
I was going to suggest something like this too. I came up with something along the lines of entertainment or mood values.

Sure the game is fun for us, but our avatars are doing hard labor all the do-da. Maybe creating entertainment objects and then interacting with them could increase a 'mood' value that diminishes over time. Could be simple early on, such as a ball made out of hide, and people could smack it around and this would increase it as well as promote interaction with other people on the server. Later on it could be interacting with technologies more akin to our day and age. Or it could be something like a puzzle book printed on the paper we make and we can solve them which increases the mood bar as well (Then again people may not want to play Sudoku just for skill points) Either way, Im suggesting an entertainment value that increases and decreases based on how long ago someone took the time to relieve stress.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#334
