### ISSUE TITLE
Fertilizer tune-up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3165]
"Fertilizer was not something we ended up using it was confusing and weak without the semi-instant gratification they were unwilling to try and change his farms into better soil due to the incredible amount of effort it would have required"

**Comment by knexer** [comment]
+1 to fertilizer is not communicated well.
That will of course be fixed with worldlayer introspection; and I'll be making / have made significant simplifying changes to soil nutrients as well.
