### ISSUE TITLE
Beans Missing From Tech Tree

### ISSUE THREAD

**Issue by MoonSong543** [StrangeLoopGames/EcoIssues#3166]
I have just noticed in 6.2 that Beans are not listed under the Gathering tech tree at all, but Rice is without actually being in the game.  Beans used to be under the Forest Forager a long time ago but I cannot find them listed anywhere now.

**Comment by TreeNuts** [comment]
Agriculture > Grassland Seed Yeild (4th column, 3rd row)

Beans are their own seed so you benefit from that perk. Is that what you're referring to?

**Comment by craig-jong** [comment]
As TreeNuts has said, they're classified as seeds.

We're doing a restructure of the skill trees so those two skills will likely be condensed into one.

**Comment by MoonSong543** [comment]
Did not see that there at all...so sorry for wasting your time! I guess I
was just used to it being under forest that I didn’t look closely enough
under grassland. Thanks for the quick response. Absolutely love the game!
KystonEco
