### ISSUE TITLE
Small wooden cart completely unusable after placing

### ISSUE THREAD

**Issue by efflixi** [StrangeLoopGames/EcoIssues#3167]
I placed a small wooden cart in a mine underground and it automatically got text on the back "EcoSWC" and is completely unclickable or even selectable. There were no actual errors on the server (my personal server). The area that you can't select also extends beyond the cart a bit as you can't even mine or select anything under the cart either.
![screenshot from 2017-12-19 05-50-25](https://user-images.githubusercontent.com/19391165/34153553-7cc9c19a-e480-11e7-8906-9225c51334d8.png)

**Comment by SeanAtr0n** [comment]
Is this server using mods to the cart? I'm not sure how the license plate would get set, looks like that info isn't saved currently.
