### ISSUE TITLE
Server Crash when Claiming Land - Unnamed Area bug

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#3168]
I saw this issue in a closed ticket here: #2566 

We are still experiencing this in 6.2.0, we have had 2 players get the 'Unnamed Area' deed bug which continues to crash the server with a Object Reference not found error. They are able to claim again if they remove the offending deed from thier inventory.

https://pastebin.com/5GJk3zj0

**Comment by stormoffires** [comment]
I had the same issue when trying to claim land with a blank deed. Took me taking ownership of the deed by clicking the button before I could claim land without crashing the whole server.

**Comment by Huntermeign** [comment]
I also noticed this if someone had two deeds in their inventory

**Comment by MarjieAVolk** [comment]
Fixed in next staging release
