### ISSUE TITLE
No Time showing for Power Consumption 6.2.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3169]
![snap734](https://user-images.githubusercontent.com/29383891/34168551-afbde7aa-e4dc-11e7-9786-37821d1d4960.png)
![snap735](https://user-images.githubusercontent.com/29383891/34168554-b3d86d06-e4dc-11e7-8428-f784239dac62.png)
As you can see on these two examples we don't have any time showing (we used to) so how long fuel will last for is a bit of Guesswork

**Comment by MarjieAVolk** [comment]
Oh it's because the thing isn't running.  When it starts running you will see it.

**Comment by elfl0rd** [comment]
@D3nnis3n 
![default](https://user-images.githubusercontent.com/4980243/49964328-4587bb80-ff2b-11e8-8164-f17c448726ff.png)

**Comment by D3nnis3n** [comment]
But your table is running? It's about when they don't run.

**Comment by Conchipedia** [comment]
as far as i have seen this should be working now as this is an old github so i will close this
