### ISSUE TITLE
ensure all controls are customizable

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#317]

**Comment by Conchipedia** [comment]
hey guys i keep noticing this happen
![snap566](https://user-images.githubusercontent.com/29383891/32738976-742ddfea-c896-11e7-8ac4-bd07933b8216.png)
The D20 (Age of the World ) and 4:45AM (i think time of the day for world cycle) I'm Not sure if i'm accidentally pressing a hidden key combo (like ALT Z for hiding/showing UI) and help on this appreciated.
Asking here as this is open issue for controls (and you had linked here my OLD key list #2736 )

**Comment by Nanders** [comment]
That sounds like a new issue

**Comment by MarjieAVolk** [comment]
There are no controls related to this, this is an unrelated issue.  Moving to https://github.com/StrangeLoopGames/EcoIssues/issues/2813
