### ISSUE TITLE
Sometimes plants don't update until you try to harvest them

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3170]
![plantbug2](https://user-images.githubusercontent.com/6262198/34181209-35afa022-e4c6-11e7-9c79-695e298a1a87.gif)

**Comment by Huntermeign** [comment]
I noticed this too. I think its chunk specific because I had a farm that was several chunks big, some updated and others didn't until I updated a block next to/in the 5x5 chunk

**Comment by WeaselDog** [comment]
fixed with https://github.com/StrangeLoopGames/EcoIssues/issues/14252
