### ISSUE TITLE
Stone Roof (because you have removed from game) gives Error 6.3.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3172]
Because You have removed Stone Roof as a Building Block, all World Saves that have it already as part of buildings cannot remove or replace this and we get the Following Error:

Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Object reference not set to an instance of an object.

Stack:
   at Eco.Gameplay.Items.UsableItemUtils.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Item fallbackGiveItem, IAtomicAction[] additionalActions)
   at Eco.Gameplay.Items.ToolItem.PlayerDeleteBlock(Vector3i blockPosition, Player player, Boolean addToInventory, Single calorieMultiplier, Item fallbackGiveItem, IAtomicAction[] additionalActions)
   at HammerItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

But it is still there Displaying it as seen in the Following Snapshots
![snap749](https://user-images.githubusercontent.com/29383891/34209123-da93a6a2-e588-11e7-9509-dabb6620b6d0.png)
![snap750](https://user-images.githubusercontent.com/29383891/34209136-e4e9cf3c-e588-11e7-8205-c84e2bf5f928.png)
![snap751](https://user-images.githubusercontent.com/29383891/34209148-ef23d6b4-e588-11e7-8ae0-bfc4a827d36d.png)

Those of us on Existing Worlds would so much need a FIX to help solve this issue, at least let us Remove it somehow, and replace it with another building Block or at least Replace ALL thats in the World already with a Block that IS in the game (Please)

**Comment by noblackthunder** [comment]
Comment from discord : because they removed "Stone Roof" from the game (even though we can still see it) the NEW hammer Crashes the game EVERY time you attempt to hit a block of it!

**Comment by Conchipedia** [comment]
https://www.dropbox.com/s/6h0tb51x6yo0jfj/prime%20save.eco?dl=0
this is A previous "Greenleaf Prime" Save but this should work as the Stone Roof was used earlier

**Comment by Phlo123** [comment]
Prime current save:
https://www.dropbox.com/s/bm4ph0mwqt3t4lz/PRIME-Game.eco?dl=0

**Comment by Conchipedia** [comment]
This is the Current Save showing ALL the Stone Roof that's in place, so you have at least something to test on

**Comment by craig-jong** [comment]
Working a fix for this now - probably'll just replace them all with a mortared stone variant.

**Comment by Conchipedia** [comment]
will be much appreciated, will this be possible for all the blocks that are placed in the world?

**Comment by craig-jong** [comment]
Yes, it should replace every instance of the "StoneRoof" block with something valid.

**Comment by Conchipedia** [comment]
thats great, Normal Mortared Stone would be perfect as that looks identical when placed as the old Stone Roof

**Comment by Conchipedia** [comment]
![snap753](https://user-images.githubusercontent.com/29383891/34231223-0a7c01a8-e5d3-11e7-9812-1374aaa8e7b9.png)
as you can see From this Snapshot the old looking"MortaredStone" is Still visible, But on the positive Side it will let you replace it with the New one you have created, so maybe have it Detect the old "MortaredStone"in the Fix as well and replace that as well with the New one.

**Comment by Conchipedia** [comment]
Seeing as on the Subject of "MortaredStone" it still displays in the Stockpile(s) as the Old type
![snap754](https://user-images.githubusercontent.com/29383891/34231639-c55ee3b8-e5d4-11e7-916d-f7a699db4c10.png) so this is just an [Art] issue.
Note: the wall seen surrounding it is still "StoneRoof" 
(Apologies for keep adding to this Github, but it does seem All "MortaredStone" related.

**Comment by metachronism** [comment]
mostly a tech tree issue, handing off to craig

**Comment by knexer** [comment]
This was hotfixed ages ago
