### ISSUE TITLE
Calorie tooltip disconnects the client

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3173]
When hovering over the calorie tooltip, the client instantly gets disconnected. No relevant errors in unity or the server console to help troubleshoot.

**Comment by MarjieAVolk** [comment]
I assume you mean the one for the nutrition pie chart / calorie bar in the bottom left?  That is very weird, not seeing that on master.

**Comment by julrich1** [comment]
This was fixed last week so you can close it out. 😀

**Comment by MarjieAVolk** [comment]
Oh great lol
