### ISSUE TITLE
[Art] Cast Iron Spigot and Cast Iron Stove seems to have a pipe Connection in unusual place 6.3.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3178]
![snap755](https://user-images.githubusercontent.com/29383891/34232474-5b4cb212-e5d8-11e7-9a74-5d04978ab84b.png)
![snap756](https://user-images.githubusercontent.com/29383891/34232494-6a5f6e0c-e5d8-11e7-9281-15dd4d3fca4b.png)
As you can see in the First snapshot this is how it looks when placed, the Second one lets me place a pipe on the top.
but as you can see in the Next Shot of the table menu, nothing is there to need a pipe
![snap757](https://user-images.githubusercontent.com/29383891/34232588-deef19c0-e5d8-11e7-9437-a274c81241d0.png)
![snap760](https://user-images.githubusercontent.com/29383891/34232670-4ccb0648-e5d9-11e7-88f5-b3b7560c204a.png)
The last one actually makes it Clearer that a Pipe will Join to it
![snap761](https://user-images.githubusercontent.com/29383891/34232767-c5ff96c8-e5d9-11e7-859a-e288d8858e48.png)

![snap759](https://user-images.githubusercontent.com/29383891/34232706-74c12f92-e5d9-11e7-8f4b-5cea3863d265.png)
hoping this is something NEW that you are working on ❤️

**Comment by keegan-o** [comment]
Fixed the cast iron stove, spigot will need it in code looks like.

**Comment by keegan-o** [comment]
cast iron spigot is actually not in the game atm but it will be added back in when we do water piping, and fixed then!
