### ISSUE TITLE
Logs disappearing from hand 

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#3179]
Picking up logs, suddenly, they are gone from hand, no log icon in holding slot, but still have a lot number. If I pick up an individual log from my house wall, it restores the logs in hand. Build is Alpha 6.3

**Comment by MarjieAVolk** [comment]
Sounds like maybe a hammer problem?

**Comment by BlazeGuy2** [comment]
Can't reproduce, I'll close for now.
