### ISSUE TITLE
[Feedback] Seeds eating vs planting

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#3181]
it seems that seeds can be eaten by accident and cause an annoying moment when you try to plant them. Maybe it is possible to solve this that this does not happen so easy by accident ? 
http://ecoforum.strangeloopgames.com/topic/3085/misplacing-seed-makes-you-eat-it

**Comment by MarjieAVolk** [comment]
Yeah I was worried about this.  It's possible I could prevent you from eating seeds with right click at all.  But this is annoying for plants like Camas where the seed is the same as the food.

The other solution we have thought of is to have an eating animation, like mining or digging, and the eat operation would not complete until the end of the animation, so you can stop holding down the button before you actually eat the seed.  I'm not sure how much work that would be - @SeanAtr0n what do you think about that?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#333
