### ISSUE TITLE
Skills UI starts way too small 

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3185]
Currently the skills UI starts as a tiny window which is especially noticeable on a higher resolution monitor. Could it be scaled to start at a relative width/height depending on resolution?

**Comment by MarjieAVolk** [comment]
This has been updated along with a new layout for the skills ui

**Comment by MarjieAVolk** [comment]
Will be available in the next staging release, coming today or tomorrow
