### ISSUE TITLE
Placing a stone block while landing can push you into a wall

### ISSUE THREAD

**Issue by julrich1** [StrangeLoopGames/EcoIssues#3188]
By jumping and placing a stone block right before landing, you can push yourself into a wall.

Example: https://imgur.com/a/RSJlY

**Comment by julrich1** [comment]
Also can cause the player to fall through the world - https://imgur.com/a/T4nLm

**Comment by MarjieAVolk** [comment]
@Nanders Any chance this will be magically fixed by the new character controller?

**Comment by Nanders** [comment]
this behavior should be fixed with the new controller
