### ISSUE TITLE
New Lag Free Building

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#3189]
May be lag free but blocks when placed;
get placed
get un-placed
get re-placed

link to video of placing road blocks:
https://drive.google.com/open?id=11bEuibfrkKaef0uaLvEnPULdW8L9VjoT

when blocks are dug up you can actually dig 11 (or sometimes 12) and then it re-builds the over quantity

**Comment by WeaselDog** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3429#issuecomment-375085552

**Comment by D3nnis3n** [comment]
This is no longer occuring in the current version. If this issue reappears please open a new issue.
