### ISSUE TITLE
Fireworks - oh its a "splash"?

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#3190]
What is with these fireworks graphics????

Video link:
https://drive.google.com/open?id=1IZtMXKBvXB5BFjFlWrJWGCa4J7OAjYsv

**Comment by keegan-o** [comment]
I've never been able to repro this.... changed this effect a lot since then so I'm closing this but feel free anyone to re-open if they can get it to show up again.
