### ISSUE TITLE
Remove right-click to eat selected food, and open deed.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3194]
It conflicts with right-click to place

**Comment by MarjieAVolk** [comment]
People have been asking for this feature for a long time, and they have commented on liking it, and they are asking for it for more things

**Comment by johnkslg** [comment]
Theres a core problem with it though, ie if youre trying to plant a field and mis-click, you eat the seeds instead.

**Comment by MarjieAVolk** [comment]
That is true, there is not a problem with the deed though.

I'd been hoping to fix this by having an eating animation or something, similar to how minecraft solves this problem.  Because showing the cursor and right clicking on the icon is annoying and hard to find.

**Comment by MarjieAVolk** [comment]
My current intention is to minimize this issue by having edible seeds and non edible seeds differentiated by whether they have nutrients: https://github.com/StrangeLoopGames/EcoIssues/issues/3250

That would be the beta solution, and we could discuss better options later.  Sound alright?
