### ISSUE TITLE
the Show All top right on Skill Tree will Not remember being chosen 6.3.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3196]
Even if i don't logoff and back on, just opening and Closing Skill window the  "Show All" will NOT remember to stay ticked (its a bit annoying, as i would like to see what i need to learn without having to keep ticking the box)

**Comment by knexer** [comment]
I think this is working as intended - we didn't want players to tick 'show all' and ever thereafter feel confused and overwhelmed by the scope of the game :P

Now that the new skill UI is in, we might want to reevaluate this decision.
