### ISSUE TITLE
When Sorting Storage into an order you like sometimes leave an outline on main screen that cannot be removed 6.3.0

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3197]
![snap773](https://user-images.githubusercontent.com/29383891/34315342-45c8c1b6-e776-11e7-9ef8-6be265d3c238.png)
Even a Disconnect sometimes will not clear this from the screen and only a total exit and log back in will clear it (alt z will make it turn off and on so it is to do with the UI)

**Comment by Conchipedia** [comment]
proper name would be 
UI element stuck on screen #3180
so linked to this issue

**Comment by TreeNuts** [comment]
#2955 seems to be the most active for this issue.

**Comment by MarjieAVolk** [comment]
I am assuming this is a different issue at this time, since it's not an item icon, but they may turn out to be the same

**Comment by MarjieAVolk** [comment]
Wait a sec... I just realized this is probably related to drag and drop.  Because while you are dragging something, it's become unattached to its parent ui in unity.

**Comment by MarjieAVolk** [comment]
And also in which case this would be the same issue as those linked above

**Comment by MarjieAVolk** [comment]
Okay yeah I wasn't thinking about this bug right.  Anyway you guys are right, I'll close this as a duplicate
