### ISSUE TITLE
6.3.1 Is using a great deal more RAM then 6.3.0 to load/run the server

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3198]
6.3.1 Is using a great deal more RAM then 6.3.0 to load/run the server.  A 4X world server was using 5.5 GB RAM for 6.30 and is not maxing out over 13.3 GB RAM.  Looks like its running a conversion pass each time it loads instead of just the first time on a new version

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/3199?

**Comment by metachronism** [comment]
this is intended, once the other bug is fixed this wont be an issue.

after gc runs/world is saved once, ram usage should go down to normal
