### ISSUE TITLE
World converting on every server restart 6.3.1

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#3199]
fresh world zero mods, no logins ever,  generated, closed, restarted  "CONVERTING". Does this every time the server program is restarted.

[game.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1584353/game.txt)

**Comment by MarjieAVolk** [comment]
Is it possible the world has not finished saving after converting, before you shut it down?

**Comment by SeanAtr0n** [comment]
It's converting repeatedly because StoneRoof still exists as a block type so every time you restart it looks like the schema changed

**Comment by craig-jong** [comment]
Stone roof shouldn't exist anymore - it's not in the xlsm at the very minimum.
