### ISSUE TITLE
Blocks placed become ghosts

### ISSUE THREAD

**Issue by robo336** [StrangeLoopGames/EcoIssues#3201]
Sometimes after playing a while, placing new blocks or planting seeds, leaves ghosts.
The block can be walked thru as if it isn't there, but you can pick it up up again.
![image](https://user-images.githubusercontent.com/17105244/34326328-e1e97c5a-e8a9-11e7-926a-88e1be6dd3e5.png)

**Comment by robo336** [comment]
Restarting the client fixes the problem until it appears again.

**Comment by metachronism** [comment]
my recent hotfix should fix this.  in 6.4.1
