### ISSUE TITLE
Tree shouldn't be able to be planted in a Planter also some still giving Gaps 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3206]
![snap799](https://user-images.githubusercontent.com/29383891/34327952-3618d062-e8ca-11e7-9067-396d05307994.png)
![snap800](https://user-images.githubusercontent.com/29383891/34327991-ef94d702-e8ca-11e7-9427-84b8fa94aff5.png)

As can bee seen a Tree (both types) can be grown in a Planter ( if you still allow trees in planters maybe give the tree an arguement that it will grow no bigger than a sapling)  
also the trees are getting gaps again, which will also be shown when they are chopped down, but this is Not all trees as loads still look normal

**Comment by elfl0rd** [comment]
@D3nnis3n i think can be closed, due to "fake plants" in pot in 0.8.

**Comment by Conchipedia** [comment]
how will fake plants work in pots? are they planted with seeds and turn into something else when it detects that its placed in a pot? most plants are OK in Pots its just Trees in pots don't work, and i haven't seen gaps in trees for ages.

**Comment by elfl0rd** [comment]
Plants in pots no more simulated, plots have storage, accepted seeds, if seed in storage - pot have plant on top.

**Comment by Conchipedia** [comment]
so it pretends to be a plant if a seed is in its storage?
sounds interesting 🌱

**Comment by elfl0rd** [comment]
In addition, this is not happens in current release version :D 
![default](https://user-images.githubusercontent.com/4980243/51077612-20b56e00-16ba-11e9-8b70-e2ea147630cf.png)
