### ISSUE TITLE
Planting information seems very erratic 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3207]
this is how my wheat farm looks (and they was planted with a few seconds of each other)
![snap804](https://user-images.githubusercontent.com/29383891/34328069-cfad4404-e8cc-11e7-9218-c6144146b9db.png)
and various readings for blocks
![snap801](https://user-images.githubusercontent.com/29383891/34328077-036c82c8-e8cd-11e7-8818-959bc07c05dc.png)
![snap802](https://user-images.githubusercontent.com/29383891/34328084-153e3884-e8cd-11e7-92fe-42495d42639b.png)
![snap803](https://user-images.githubusercontent.com/29383891/34328085-1557bf3e-e8cd-11e7-9623-9e12961349eb.png)
as far as i can tell i am not across two biomes
![snap805](https://user-images.githubusercontent.com/29383891/34328107-79efa9ac-e8cd-11e7-9ef9-943f732dce66.png)
![snap806](https://user-images.githubusercontent.com/29383891/34328109-7a0a5d38-e8cd-11e7-90fb-18f7555fa1ea.png)
![snap807](https://user-images.githubusercontent.com/29383891/34328110-7a242d80-e8cd-11e7-8d40-1fd536bcba4e.png)
![snap808](https://user-images.githubusercontent.com/29383891/34328128-fe2a6752-e8cd-11e7-8d64-30cad3e4cdfd.png)
![snap809](https://user-images.githubusercontent.com/29383891/34328129-fe44e3de-e8cd-11e7-942e-a18a32dcde0a.png)
![snap810](https://user-images.githubusercontent.com/29383891/34328137-6527508c-e8ce-11e7-8c6c-4d514e200c28.png)
![snap811](https://user-images.githubusercontent.com/29383891/34328148-a61c5f60-e8ce-11e7-8e08-e5ce4dcda3e8.png)
![snap812](https://user-images.githubusercontent.com/29383891/34328149-a6334be4-e8ce-11e7-9793-0a39e8220038.png)
![snap813](https://user-images.githubusercontent.com/29383891/34328150-a64a21ac-e8ce-11e7-8593-dd2305a9db87.png)

**Comment by knexer** [comment]
From the world layer views you included, it looks like the farmland is very nutrient-depleted.  Try applying some fertilizer.

Re: the bug, the problem is mostly one of poor communication of how the layers operate.  I'm working on a big backend feature that will address that holistically for all the world layers, so check back in a couple of weeks :)

**Comment by knexer** [comment]
It also may be worth applying doing some interpolation when pushing from world layers to plants, like biomes does, so you don't see such obvious square sections where things are different.
