### ISSUE TITLE
Clothing/Backpacks not visible/working

### ISSUE THREAD

**Issue by Nalelvon** [StrangeLoopGames/EcoIssues#3208]
![eco1](https://user-images.githubusercontent.com/1555735/34345788-037f1516-e9f2-11e7-9af1-41fa7dcdb81d.jpg)
![eco2](https://user-images.githubusercontent.com/1555735/34345789-039963f8-e9f2-11e7-8632-aa655ff7c143.jpg)
![eco3](https://user-images.githubusercontent.com/1555735/34345790-03b1c8b2-e9f2-11e7-9fd1-e01f223397c5.jpg)
![eco4](https://user-images.githubusercontent.com/1555735/34345791-03ccbc26-e9f2-11e7-904c-098be70b5137.jpg)
![eco5](https://user-images.githubusercontent.com/1555735/34345792-03e6edbc-e9f2-11e7-95a3-d809d42d4b00.jpg)

As you can see in the picture i am wearing camo shorta and a camo shirt as well as running shoes and a bearback. They all show no skin and seem to not work, i cant tell any difference in running speed and i see no increase in carry weight. As for the funcion of the camo gear it doesnt feel like it works but i cant tell for sure

**Comment by metachronism** [comment]
lowering priority pending clothing asset dump from milenko

**Comment by keegan-o** [comment]
Added the camo pants and shirt to master, at long last. Other items are assigned to previously existing art, they will be updated when we get a fresh load of avatar clothing art.
