### ISSUE TITLE
[Art] Amanita Mushroom won't Draw growing unless right over the plant 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3209]
<img width="1280" alt="snap141" src="https://user-images.githubusercontent.com/29383891/34352355-f3dda3fc-ea19-11e7-9650-556d9d807875.png">
<img width="1280" alt="snap142" src="https://user-images.githubusercontent.com/29383891/34352379-16283eea-ea1a-11e7-8416-2323c1d7d28d.png">

if i walk forward the next Mushroom will show, but the previous one will just disappear

**Comment by MarjieAVolk** [comment]
If you increase your foliage quality slider in the escape menu settings, the view distance for these should increase.

But @metachronism this is bad behavior.  Plant view distance should never be this small, and settings should be more clear.

**Comment by Conchipedia** [comment]
I couldn't check this on the world We had (it Blew up from the Meteor) but doing it on this one seems to make everything show, sadly if i have set my World to Fantastic (as i always do) this should have maxxed as well, but didn't )so dragged it manually)

**Comment by metachronism** [comment]
this is an art bug
