### ISSUE TITLE
Player display name is capitalized ingame

### ISSUE THREAD

**Issue by copygirl** [StrangeLoopGames/EcoIssues#3210]
I've registered my account as "copygirl" and it's being displayed as such on the account page, too. Ingame this appears to be capitalized into "Copygirl".

I'm in the odd position of being very irrationally bothered by name being adjusted by a game or service (like MediaWiki). For me, my name is very intentionally "copygirl", any variation on it such as "Copygirl", "Copy Girl" doesn't really *look right*. I realize how silly this issue is, though I feel the need to mention it as it does affect my enjoyment with this game whenever I'm reminded of it.

Alternatively, this issue could be solved by allowing players to change their display name - as long as capitalization is respected, of course.

**Comment by Nanders** [comment]
This is no longer the case
