### ISSUE TITLE
Alpha 6.3.1 - Polution from tailings goes through many layers of stone

### ISSUE THREAD

**Issue by ixolan** [StrangeLoopGames/EcoIssues#3211]
I have create a mine in a mountain .. there is a cavern which I use for stockpiling tailings. The stockpile is completly encased in stone/ore -- all walls, flors and ceilings are either stone or ore.  Around 30-40 blocks on top of the mine is the spring of a river - and its 30% poluted and no longer blue. I dont think that the polution should go through 30-40 blocks uphill.

**Comment by knexer** [comment]
No, it shouldn't go through 30-40 blocks uphill.  Is there any part of the tailings stockpile (maybe just a corner of it?) that's nearer to the surface?  How about the distance to the bottom of the spring?

If you could upload your save that repros the issue I could take a look, I can't reproduce the problem locally.
