### ISSUE TITLE
Inventory showing full even though it isn't.

### ISSUE THREAD

**Issue by Galen1972** [StrangeLoopGames/EcoIssues#3213]
I keep having an issue where it says my inventory is full even though I have two open slots in my back pack and one in my hot bar. This has happened more than once and on different servers.

**Comment by MarjieAVolk** [comment]
Is your inventory near the weight limit?  That will also cause it to be full

**Comment by Conchipedia** [comment]
try a snapshot if possible (without hiding UI) this will show all relevant Info (especially the weight limit on the right end of toolbar)

**Comment by MarjieAVolk** [comment]
Okay well, since it seems likely that this was a misunderstanding, I'm going to close this for now.  If it is really a problem, feel free to respond with more information.
