### ISSUE TITLE
Inactivity. boot from server

### ISSUE THREAD

**Issue by Robert-Blacklidge** [StrangeLoopGames/EcoIssues#3214]
I can not interact with any objects, when I do I am booted from the server for Inactivity. I have restarted my computer and have re-downloaded the game to no avail.

**Comment by cuda70** [comment]
been having this problem on and off for a while see post #3130

**Comment by cuda70** [comment]
I am having this problem again today 01/01/2018 cant open any inventory cant select any tool on my tool bar and get kicked off server for inactivity after 30 seconds or so

**Comment by vannucci16** [comment]
Restarting the server fixed this for me

**Comment by CuAnnan** [comment]
We have to restart our server several times for this. Sometimes three or four times an hour, sometimes hours will pass.

**Comment by CuAnnan** [comment]
I don't know if it's related, but this will often happen if I'm passing a law. It's not that I spend 30 seconds on the law. It's that I press l, press the propose law button, click back into the game to tell people what I'm doing and it's already doing the whole "Nope, not accepting commands from you, not letting you do a thing" thing.

**Comment by CuAnnan** [comment]
It has happened twice today. Both times while I was trying to pass a law.
I think there is a problem with the token sharing system you have in place for user logins between the Web Server and the game.
