### ISSUE TITLE
Dot in username when added to admin causes bug

### ISSUE THREAD

**Issue by mbenitezmeiss** [StrangeLoopGames/EcoIssues#3215]
Two changed config files: 
difficulty.eco : https://pastebin.com/aavHU8Jv
users.eco : https://pastebin.com/XUVb3pxF

My in-game username is "Meia.benitez"

Server version: 0.6.2.0-alpha
Operating system: Windows 7 x64
Specs:
CPU: intel i7-4790K CPU @4.00GHz
RAM: 16.0GB
GPU: NVIDIA GeForce GTX970
Harddrive 1: SSD 256GB
Harddive 2: HDD 3TB

Reproducible: Yes.
Steps to reproduce: Change configs to match mine. The difficulty.eco is probably unnecessary but I did make that change, so I will share again.

Behavior: The GUI with the skills, tool belt, map, etc all no longer work, and neither do the key-binds to bring those up. I did not even get the character customization screen popping up.

**Comment by mbenitezmeiss** [comment]
I suspect the dot in my username is causing an issue when granting perms. I asked NoBlackThunder to update my in-game username to deadcode and I'll retest to try again. I don't have issues when joining servers where I am not granted perms (even my own hosted servers where I'm not an admin).

**Comment by mbenitezmeiss** [comment]
Got my username changed to "Deadcode" and all works well now. 

Never had an issue until I tried adding myself to one of the userlists (e.g. whitelist, admin).

**Comment by mbenitezmeiss** [comment]
Also, note: Issue occurred in 0.6.3.1 as well.

**Comment by elfl0rd** [comment]
@D3nnis3n lol, strange bahavior still there... can you check?
And need to check possibility creating SLG user with dot in name...

**Comment by WeaselDog** [comment]
Thanks for your report.

I can't replicate in the latest version and it appears to have been fixed in a previous update.
