### ISSUE TITLE
Report button Doesn't do anything 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3216]
Not sure if this has been Implemented yet, or the button is just a placeholder for now

**Comment by MarjieAVolk** [comment]
It should open a page in your browser, like the server button.  Maybe it doesn't maximize the browser when you click it?

**Comment by Conchipedia** [comment]
i have tried this on 3 PC's 2 running Mozilla and 1 Internet Explorer (my friend prefers this one for some reason) as the Default Web browser and nothing happens

**Comment by Conchipedia** [comment]
i'm not overly concerned as i prefer github search and edit anyway ❤️

**Comment by MarjieAVolk** [comment]
Okay I'm seeing it too, someone has messed up the ui prefab list.  Will be fixed soon.

**Comment by MarjieAVolk** [comment]
Okay well somebody has fixed this, lol, will be fixed in next staging release, coming today or tomorrow
