### ISSUE TITLE
[Suggestion] making sure repaired tool gets returned after Repairing them

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3217]
If tool doesn't need repairing it will automatically not go in the Repair Slot, but if you get busy and repair a tool, quite often it's possible to forget to take tool out of the repair slot and then realise a few minutes later when you want to use it that you have forgotten to get it back, this can also help in NOT losing tools to other people if you forget to get it back when using other players Repair Stations (just forgot to get tool back for at least second time in an hour 🤦‍♂️ )

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#331
