### ISSUE TITLE
[Suggestion] have a message window come up in the Centre of the screen Saying Tool is about to break

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3218]
would be nice if a Window pops up in the centre of the screen saying that tool is about to break i know the tool glows red when its broken, but if you are concentrating hard on something its easy to miss the tool breaking and get hit by a massive usage of Calories

**Comment by knexer** [comment]
A sound effect and/or a change to the tool's model or texture could be a nice way to communicate this as well.

**Comment by MarjieAVolk** [comment]
+1 sound effects would be great

**Comment by Nanders** [comment]
Yeah this should be communicated visually/aurally

Having a UI is ham-fisted, but might work until we have the assets for it.

**Comment by Nanders** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/5
