### ISSUE TITLE
Water bobbing is fast and jittery

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3220]
When sitting at the surface of the water, you jitter up and down quickly, instead of bobbing slowly

**Comment by Conchipedia** [comment]
still doing this in 6.4.1

**Comment by Conchipedia** [comment]
still a problem in **Version:** 0.7.0.0 beta staging-71fcbff4

**Comment by Nanders** [comment]
Fixing this today

**Comment by SeanAtr0n** [comment]
fixed in next build
