### ISSUE TITLE
[Art] Logs and Mortared Stone will not join together nicely 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3221]
<img width="1280" alt="snap148" src="https://user-images.githubusercontent.com/29383891/34450225-d5ce04d0-ecfb-11e7-8a8c-23c81f65df06.png">

**Comment by MarjieAVolk** [comment]
I believe we will be replacing the log block with something else, which will have different behavior, so this bug can probably be closed.

**Comment by Conchipedia** [comment]
ok,
<img width="1280" alt="snap149" src="https://user-images.githubusercontent.com/29383891/34450493-2d159ef0-ed02-11e7-9d9a-075e2fa31ce1.png">
also this i want to add the corner piece above and below is great, just needs the middle one to be the same if a space is made next to it (maybe an arguement can be added if blocks are the same above and below have middle block appear the same)

**Comment by Conchipedia** [comment]
if they do replace log block, don't let them make the same mistake like they did with Stone Roof that was a nightmare trying to get fixed and replace in existing worlds

**Comment by knexer** [comment]
We're replacing logs with hewn logs; closing this accordingly.
