### ISSUE TITLE
[Suggestion] Tailoring Figure to Model Clothes 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3223]
Might be nice to have a Figure that can be dressed in the created items in Tailoring
Something like this for example:
![artist posing figure](https://user-images.githubusercontent.com/29383891/34451369-18545128-ed1b-11e7-81a0-1011c1c56ad2.jpg)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#330
