### ISSUE TITLE
[Suggestion] Auto Filler of Fuel Tabs (stockpile and chest type crafted items)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3225]
Would be nice to have new Higher End Storage craftable Items that can Auto fill Fuel tabs for later in the game (available in Storage Skill obviously)

1: Coal Auto Fueler (Possible Recipe: Coal and Stockpile + other items?) 
Will hold auto fill Fuel tabs with Coal  (ability to be linked)

2: Charcoal Auto Fueler (Possible Recipe: Charcoal and Storage Chest + other items?)
Will hold auto fill Fuel tabs with Charcoal  (ability to be linked)

3: Gasoline/Petrol Auto Fueler (Possible Recipe: Gasoline and Storage Chest + other items?)
Will hold auto fill Fuel tabs with Gasoline or Petrol  (ability to be linked)

Unsure of a design (leave that to the experts) but having the ability to see how full they are would be helpful (easier to fill these than selecting each table and filling them with Fuel as this often can take ages to do)

I think i covered most of the Fuel that tables require.

Reason for possibly other items in recipe's is to not make it too easy to make as they won't be needed until later in game until a production line is going. 

example of this: , making Reinforced Concrete = 3 Blast Furnaces (1st Making Iron Ingots, 2nd making Steel and the 3rd making Rebar), 2 Cement Kilns (1st Making Concrete and 2nd making the Finished Product of Reinforced Concrete)
This would require 5 Power tabs to be filled manually (main reason for the idea of Auto filler of Fuel tabs)

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/12
