### ISSUE TITLE
[Suggestion] when sharing Deeds let another player use storage already linked to table and in the order main Player has decided on Output

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3227]
The most common annoyance is you have someone on your deed that you let share your rooms and tables, but that player has to make their own links to storage and decide which storage the item is output to, this can be so annoying if you have loads of storage linked and the stuff they crafted can go to the wrong storage and may be accidently used by another table for crafting something else entirely.
I know that the arguement can be have public storage but if you are in a group you don't want everything open to anybody not on the deed.

Sometimes you may decide to totally redesign your house/workshop and have tables and storage in new places, but this would mean that the shared player would have to relink everything again just to help you craft something, Also sometimes a player that is crafting may forget to link any storage at all and you can end up with a table of maximum projects that need to be collected (nobody but the person who ordered it can collect these items, only thing the main player can do is cancel the project to make space which you wouldn't want to do if it has been completed)

**Comment by MarjieAVolk** [comment]
Yes I agree this is very annoying when playing cooperatively.  That's a good idea to have authorized users use the owner's settings... will think about it more.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#329
