### ISSUE TITLE
Wrong mouse key highlighted for open/close door in 6.4

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3228]
When you place a door in 6.4, it gives you the option to Open/Close or Setup/Lock.  It shows you a mouse and the left mouse button highlighted for open/close.  However, its the right mouse button that opens and closes the door:. The Setup/Lock click "E" works except it does not really make it very clear how you can lock it.  There used to be a little check box in the corner that you could tick to lock one specific door but that no longer appears available

[![Screenshot from Gyazo](https://gyazo.com/0fc7d71f62dc2f406aef9d755d450bd3/raw)](https://gyazo.com/0fc7d71f62dc2f406aef9d755d450bd3)

**Comment by MarjieAVolk** [comment]
@johnkslg are these hard coded?
