### ISSUE TITLE
Tier 1 materials seem to be just stone road not logs as it should be 6.4.0 #4142876a

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3229]
This is very confusing Github to make as Stone Road seems to be the ONLY item that is being shown for Tier 1, and you need to use a Wainwright Table to craft this, but to make a Wainwright Table  you need to craft this at a Carpentry Table, but to get that to work you need a room of tier 1 materials (stone road) , this is like being caught in a logic loop 😄 
see below for my Room
![snap821](https://user-images.githubusercontent.com/29383891/34453877-2ccb135e-ed56-11e7-9f41-52d1d5ae7ac0.png)
and in the Tooltips for ALL the Four Tiers no Logs
![snap822](https://user-images.githubusercontent.com/29383891/34453902-affbfa4a-ed56-11e7-96f2-fe0c908f2c3d.png)
![snap823](https://user-images.githubusercontent.com/29383891/34453903-b013aa6e-ed56-11e7-9016-ae9262012a53.png)
![snap824](https://user-images.githubusercontent.com/29383891/34453904-b02c9fc4-ed56-11e7-8e97-033a6943c4cc.png)
![snap825](https://user-images.githubusercontent.com/29383891/34453905-b043cb90-ed56-11e7-8930-5f6627a97633.png)
i came back to this after it was updated from previous Staging and the tables i have in room are all broken as it doesn't see the logs as tier 1
![snap826](https://user-images.githubusercontent.com/29383891/34453942-6645b5de-ed57-11e7-91d1-d558e13d2447.png)
![snap827](https://user-images.githubusercontent.com/29383891/34453943-665e87d0-ed57-11e7-8607-ab45874bfdaa.png)
 maybe this works on a New world, as i don't see any other way of getting a room to work unless you are an admin and just create Stone road out of thin air

**Comment by craig-jong** [comment]
The tooltips display incorrectly as they do not currently pick up the various forms of blocks.

All hewn log variants should be T1 along with mortared stone variants.

We'll be updating the tooltips to properly display this information, but the actual construction of buildings using those materials should still work in the current build.

**Comment by MarjieAVolk** [comment]
Fixed on staging
