### ISSUE TITLE
Research is not working in 6.4/Not showing correct amounts for recipe/skills not showing what is unlocked

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3230]
The required amounts in the recipes in the research are all showing as 1 of each is needed but when you click 'order' it tells you the correct number it needs and that those are missing.  Even if you have the correct number it still says the items are missing and will not run research
[![Screenshot from Gyazo](https://gyazo.com/a64b6e025fa3b0a21de8818eb3b4d886/raw)](https://gyazo.com/a64b6e025fa3b0a21de8818eb3b4d886)

In the skill tree many of the skills just have a blank next to what is unlocked

**Comment by MarjieAVolk** [comment]
Realized this is due to the research efficiency benefit being more than 100%: https://github.com/StrangeLoopGames/EcoIssues/issues/3266

Closing as duplicate.  Should be an easy fix.
