### ISSUE TITLE
Dirt vanishing in stockpile

### ISSUE THREAD

**Issue by Convieo** [StrangeLoopGames/EcoIssues#3234]
I had about 20 or so dirt at the bottom of my stockpile, along with 2 sand. I think when the stockpile repositioned the things inside the dirt vanished, leaving just the 2 sand.

**Comment by Huntermeign** [comment]
This happens because the dirt becomes grass i believe. Im guessing there is no 'grass block' that you can carry so the item simply disappears.

**Comment by Convieo** [comment]
I thought that as well, but I have seen dirt become grass in my stockpile when there was grass already at the same hight next to it.
