### ISSUE TITLE
Server browser gets cut off in low resolutions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3242]
![image](https://user-images.githubusercontent.com/3536496/34508326-c70d7670-eff2-11e7-8321-ceeb1bbc91f3.png)

**Comment by MarjieAVolk** [comment]
Sounds like a job for layouts

**Comment by MarjieAVolk** [comment]
So, are we redoing this whole UI now?  Is this bug obsolete?

**Comment by MarjieAVolk** [comment]
I'm going to assume so
