### ISSUE TITLE
Sawmill can lose connection to carpentry table

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3243]
http://ecoforum.strangeloopgames.com/topic/3128/carpentry-table-loose-contact-to-sawmill/2

**Comment by MarjieAVolk** [comment]
Sounds like duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3108

**Comment by MarjieAVolk** [comment]
pasting discussion link there
