### ISSUE TITLE
[Art/Text] When typing in the search word in the shop the cursor is above the writing 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3248]
![snap849](https://user-images.githubusercontent.com/29383891/34543168-7c796ade-f0d7-11e7-8bda-11df9958fab7.png)
i couldn't get the flashing | to show up but i managed to select what i was typing to show how its not centered on the actual text

**Comment by MarjieAVolk** [comment]
Yeah I have seen this, I have tried to fix it to no avail :(  Wonder if I have another bug for it somewhere.

It seems like it is a bug in the third party text code we are using, but it's possible I just haven't found it yet

**Comment by Conchipedia** [comment]
all other typing, as in the name of deeds and Storage works fine, it is just in the Store Search bar

**Comment by MarjieAVolk** [comment]
Yeah I know, it has me baffled

**Comment by MarjieAVolk** [comment]
I found another bug which references this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/3122

So closing as duplicate.
