### ISSUE TITLE
Molecular Gastronomy and Laboratory Tool tips show weird stuff 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3251]
![snap851](https://user-images.githubusercontent.com/29383891/34545732-b874bdfe-f0e6-11e7-96e2-6b4a99d049fa.png)
![snap852](https://user-images.githubusercontent.com/29383891/34545733-b8906040-f0e6-11e7-8ed6-b85d5678776a.png)
![snap853](https://user-images.githubusercontent.com/29383891/34545734-b8abd62c-f0e6-11e7-8401-dbb70dc17a55.png)
![snap854](https://user-images.githubusercontent.com/29383891/34545735-b8c8ee6a-f0e6-11e7-8b38-0b7d59f179a3.png)
![snap855](https://user-images.githubusercontent.com/29383891/34545736-b8e585de-f0e6-11e7-9ffa-e91a71cc1b71.png)

  only found this out as someone was asking if Molecular Gastronomy did anything so i had a peek, and i still don;t know if it does 😆

**Comment by MarjieAVolk** [comment]
Looks like the UI_Circle icon is messed up.  ARTISTS!  :P

**Comment by MarjieAVolk** [comment]
@rachaelfosner This is what it looks like when you do the sprite asset wrong :P

**Comment by Conchipedia** [comment]
Bad @keegan-o  now go apologise to @rachaelfosner  😄

**Comment by MarjieAVolk** [comment]
I was just educating her lol.  Observe these mistakes, and learn from them :P

**Comment by Conchipedia** [comment]
just be the that little voice inside her head 😄
