### ISSUE TITLE
Automated release notes generation

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#3253]
Now that we have a pull request template with a release notes section, we can write a simple script to generate a list of release notes for us using github's api.  That way we could publish release notes on time and with less time investment.

General process:
- https://developer.github.com/v3/repos/commits/#compare-two-commits enumerates the commits between two treeishes
- follow the breadcrumb in the commit description to get to the PR, if it exists
- pull out the text section for the release notes using a regex / trivial string processing
- concatenate
- publish to S3

The script can either be a standalone thing or part of the build workflow on Jenkins

**Comment by SeanAtr0n** [comment]
sounds good but whats publish to S3?
We probably still want a human to read/edit the notes before publishing them anywhere

**Comment by knexer** [comment]
Publish to S3 = put it in a bucket on Amazon S3 and make it publicly accessible, like we do with our releases.
I think there's a distinction between the release notes and the marketing blurb / blog post.  We shouldn't need a human to read the release notes, but of course we'll want a nice description and summary for the post on our website/facebook/steam news/etc.

**Comment by MarjieAVolk** [comment]
Oh, this has been written for a while
