### ISSUE TITLE
[6.4]  Columns not in build window

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3254]
WIndows are built in the build window so it seems like doors should be there too. There are also some other structures that seem like they should be in the build window rather then still in tables. Also columns are still presently found in the code but no longer show up to be built in the table but also do not yet show up in the build window.

**Comment by MarjieAVolk** [comment]
Doors can't be moved, because they are not blocks and have special behavior on them.  I'm not sure about columns.

**Comment by johnkslg** [comment]
Requires setting tech tree
