### ISSUE TITLE
[Feature Request] Command line/in game command to export chat log

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3255]
A command line that will fire off the chat log export so that people with hosted servers, and no console access, could be given a script that would export their chat log, or an in game admin command that would cause that log to be generated  and they could then download it from their game directory later?  The chat log does not seem to save from reboot to reboot and some Admins would like a way to preserve the chat log before they reboot their server if they have comments they want to keep a record of.

**Comment by MarjieAVolk** [comment]
Note that the chat log not saving between reboots is a bug: https://github.com/StrangeLoopGames/EcoIssues/issues/2814

But yes, being able to export/download the chat log, stats log, or especially the error log from the client sounds really useful.

**Comment by metachronism** [comment]
marjie already added this
also most the stats can be viewed with any litedb viewer tool

**Comment by MarjieAVolk** [comment]
I don't think I did?  This request is for accessing the export tools that we have from the client.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#328
