### ISSUE TITLE
Low power makes objects flicker

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3259]
https://media.discordapp.net/attachments/324610765392969739/398684783623798785/anim.gif

Should just shut em all down, or shut some down.

**Comment by MarjieAVolk** [comment]
I have fixed this at least 3 times :/

**Comment by MarjieAVolk** [comment]
Actually the low power case I may not have.  Anyway since Craig was working on power, think I'm going to hand this over

**Comment by elfl0rd** [comment]
Looks fixed

**Comment by MarjieAVolk** [comment]
Oh yeah, I think we shut down some object now.  Thanks!
