### ISSUE TITLE
[Art] Wording on Signs/Carts disappears when behind glass 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3263]
As you can see in the Following Examples the text Disappears when you are looking from behind glass (this can be annoying if you want something to be read from behind glass (as sometimes the sign looks better behind it) 
Example: i had a shop showroom setup behind glass displaying Different game blocks that were placed then a sign next to them saying what they were, then placed glass to make the showroom complete and all the Text went invisible (this was in The Greenleaf PAX competition entry) had to move signs outside to be read.

![snap906](https://user-images.githubusercontent.com/29383891/34615645-8009bf30-f22d-11e7-899c-9284500b409a.png)
![snap907](https://user-images.githubusercontent.com/29383891/34615647-80247a64-f22d-11e7-9e18-bcd087081b38.png)
![snap908](https://user-images.githubusercontent.com/29383891/34615649-803b4104-f22d-11e7-9b1e-cd2073a96028.png)
![snap909](https://user-images.githubusercontent.com/29383891/34615650-8056d02c-f22d-11e7-8020-d4d03b8daf98.png)

**Comment by WeaselDog** [comment]
This has been fixed so we can see through glass now.
![GlassText](https://user-images.githubusercontent.com/47330823/71287250-b6229e80-231c-11ea-900d-971769623ab9.png)
