### ISSUE TITLE
[Suggestion] Lifts for deep level Mining (as making Ramps down can take a Huge amount of Time and Calories)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3264]
I normally Dig one block Shafts to search for ore and coal at different levels, when i have found some i normally drop down the shaft and then dig out enough space to place a stockpile with the option of digging out and collecting/storing here and then making Rooms close enough above to see the stockpile below, or making Storage Above to then move the stock between them.
 (to get down i just drop down the shaft and work, and to get out i use /unstuck) it would be nice to be able to make use of the shaft i have made to be able to send stuff up or down to different levels, the mechanical workings could be hidden in a solid containing tube (saves on graphics) and then just have an opening at any floor where the lift can be called to or sent from
The smaller version could be chest size or even just one block square (this in real life is called a Dumb Waiter)
example of an opening on a Floor (leaving this to the Artists)
![waupaca-dumbwaiter-residential-1-895x590](https://user-images.githubusercontent.com/29383891/34626484-bef78a3e-f254-11e7-9178-8292efe20a05.jpg)
obviously this would allow ingots and small Items to be sent to other floors (maybe add a weight limit)
Then also in the same idea but Larger for more bigger items like Stone, Ore and Coal.
Also the possible Option to be able to Move players between floors in the larger ones.

Not Sure how we can power this, maybe using a Waterwheel or Windmill to generate the Power need to drive the lift motor.
  
If i remember correctly the Old miners used to did vertical pits and then use ladders to get up and down, then when they found the ore they then dug Horizontally in the Pit face, later on the vertical shafts were then converted to lifts, for getting men in and out and also the Dug ore.

**Comment by MarjieAVolk** [comment]
I believe we want to create something like this eventually.

**Comment by Conchipedia** [comment]
would be cool, as i always end up Down deep underground anyway, even if i start farming i end up mining 😄

**Comment by knexer** [comment]
Yep something like this is definitely on the roadmap.
Actually, it's on the trello roadmap here: https://trello.com/c/E49SX9sD/26-buildable-vehicles

**Comment by knexer** [comment]
(In that case, the elevator would have a platform you can build on, and you can either slap a stockpile onto it or build a custom interior for passengers)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#327
