### ISSUE TITLE
Tomato Growthrate unbalanced

### ISSUE THREAD

**Issue by Convieo** [StrangeLoopGames/EcoIssues#3268]
Planted a field of tomatos, other crops grow in about 12 hours, the soil sampler says these tomatos will grow in 170 hours or so. 75% temp match 100% moisture match. 0 polution. Growthrate only 14%

**Comment by knexer** [comment]
@craig-jong is in the process of rebalancing all the plants with the new nutrients right now, so this should be fixed in 7.0/beta.
