### ISSUE TITLE
Control tooltips dont respect render scale

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3269]
![image](https://user-images.githubusercontent.com/3150561/34644822-eb10c5e2-f2f2-11e7-96c4-f2560fd2e50a.png)

set render scale to anything other than 1

tooltips show in wrong location

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/34903041-5580b7c2-f7dd-11e7-9926-ab2ef0d7f375.png)
Working great in staging, someone must have fixed it with another change.
