### ISSUE TITLE
Many object ghosts are busted

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#327]
![image](https://cloud.githubusercontent.com/assets/3536496/16167368/ed19d61c-34a8-11e6-87b8-bcf50435715e.png)
This is an oven attempting to place

**Comment by stett** [comment]
Seems like it has to do with just not setting the materials properly on ghosted objects... Not sure where this happens, but:

![bad](https://cloud.githubusercontent.com/assets/5872141/16399455/6710def8-3c87-11e6-8548-c2ab811d0cdd.png)

![good](https://cloud.githubusercontent.com/assets/5872141/16399460/6c831cac-3c87-11e6-8efa-41e5048e1102.png)
