### ISSUE TITLE
NullReferenceException in ClassSerializer

### ISSUE THREAD

**Issue by lordmampf** [StrangeLoopGames/EcoIssues#3270]
Hello =)

I try to create a mod, which modifies the world, sometimes a huge amount (10k) of blocks.

For example I use the following code:
```
   for (int x = vectors.Lower.X; x <= vectors.Higher.X; x++)
         for (int y = vectors.Higher.Y; y >= vectors.Lower.Y; y--)
                for (int z = vectors.Lower.Z; z <= vectors.Higher.Z; z++)
                       Eco.World.World.SetBlock(blockType, new Vector3i(x, y, z));
```

I have a sometimes appearing race condition that results in a NullReferenceException.

Because I couldn't find a crashdump file here are some screens from VS ;)

[https://prnt.sc/hx6vq1](https://prnt.sc/hx6vq1)
[https://prnt.sc/hx6y3f](https://prnt.sc/hx6y3f)

To reproduce the Exception you can change the StorageManager.Config.SaveFrequency to 5 or something, so the chance is much higher to get it.

Maybe I forgot to use a lock or something. But I couldn't find an easy to use lock object in the source. 

Tested Version
Commit 70472a1f
05.01.2018 19:33:12

My Mod which causes this problem:
https://github.com/lordmampf/EcoWorldEdit

**Comment by metachronism** [comment]
You should be fine setting blocks like that.

Are you perchance calling SetBlock with type of EmptyBlock?  This is not supported.  If you want to remove a block, call DeleteBlock instead.

**Comment by metachronism** [comment]
Nice mod BTW :P
