### ISSUE TITLE
Server Was hit by a meteor at 30 day even though it was disabled when generated

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3271]
https://drive.google.com/open?id=1QD5W2VAn9S8LHNlygnMakCuRQ7nZeRM3

Above is our game.eco file to the world hit by a meteor even tho when i generated the world i had it disabled. 

I have tried going into the file and could not locate Meteor within worldobjects. Not sure why or how this happened but encase yall have any ideas whats up that be great! 

world generated in 6.1 and died 6.3.1.

**Comment by D3nnis3n** [comment]
Old issue, no occurance since then.
