### ISSUE TITLE
[Art] Clothing Not seen on Avatar 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3272]

**Comment by Conchipedia** [comment]
these items can be seen as Worn
Derpy Hat
Gigot Sleeve Shirt
Notch Belt (looks identical to Square belt)
Square Belt (default item)
Trousers (Default Item)
Henley (Default item)
Tall Boots (Default item)
Backpack (Default item)
Fabulous pants
Low Top Shoes

These Items cannot be seen:
Work Boots
Work Backpack
Camo Shirt
Camo Pants
Running Shoes
Basic Backpack
Big Backpack
Light Backpack

Note: on Derpy hat it seems to come with its own hairstyle, so default choice of hair won't work with it.
Note: Belts have no wear slot they have to be dragged to the main Avatar

**Comment by SeanAtr0n** [comment]
fixed
