### ISSUE TITLE
Interact key UI does not always display

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3273]
Holding an axe, some trees give the prompt to click to chop, others do not.

**Comment by Nanders** [comment]
Actually looks like its on a timer, I think it can be a little quicker

**Comment by MarjieAVolk** [comment]
Oh, is this not an issue then?  I agree the timer is a bit slow

**Comment by Nanders** [comment]
I redact, it looks like it is indeed still a problem
