### ISSUE TITLE
Interact Key UI does not update with re-bound keys

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3275]
I changed my interact key to "P" instead of "E" (for testing purposes, I'm not a heathen), UI does not update to reflect this.

**Comment by Nanders** [comment]
This also should be honored in the tutorial
![image](https://user-images.githubusercontent.com/6262198/34699816-5214668e-f494-11e7-9093-febd45b74df9.png)

**Comment by Nanders** [comment]
Also making a note on this bug
![image](https://user-images.githubusercontent.com/6262198/34699969-3dd2c7a0-f495-11e7-9ddb-e76eba8499ba.png)
Right clicking is not the only way to add items to work projects. Consider including clicking and dragging as well

**Comment by johnkslg** [comment]
Can you take care of this one?
