### ISSUE TITLE
No Interact Key UI for several common actions

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3279]
Harvesting Carcasses
Planting Seeds
Shooting an Arrow

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/71240214-9ccc2300-2319-11ea-8033-a7e3f9b263bc.png)
![image](https://user-images.githubusercontent.com/45708377/71240310-d4d36600-2319-11ea-8a14-104eea2ae9b6.png)
For shooting an arrow without any selection I think we don't need interaction
