### ISSUE TITLE
Tutorial prompt oriented a funky way

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3280]
![image](https://user-images.githubusercontent.com/6262198/34699876-ac0432dc-f494-11e7-845e-1258bbd9446c.png)
If we're doing this, the mouse should be pointed 180 degrees the other way.

I'd suggest simply an arrow though (or something similar), I don't think we need to hold the player's hand so much as to show them how to click on a button.

**Comment by johnkslg** [comment]
Fixed in staging
