### ISSUE TITLE
Improve World Layer dropdown on Minimap

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3283]
Having the dropdown reset to 0 every time is frustrating, should store last position when closed

Perhaps have a search function to allow you to select the desired selection faster

**Comment by MarjieAVolk** [comment]
I think Optimization is supposed to be used for performance optimization, thus the change

**Comment by knexer** [comment]
Going to resolve this in favor of the related issue - this UI just needs to be reworked
