### ISSUE TITLE
Save/close buttons on avatar creation UI are in bizarre places 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3284]
![image](https://user-images.githubusercontent.com/6262198/34701560-d473311a-f49d-11e7-968b-6dbe79af86da.png)
I expect close to be the [x] box in the top right, and the save to be somewhere in the bottom right (or at least more prominent)

**Comment by MarjieAVolk** [comment]
Yep they used to be over there, idk what happened to it over Christmas

**Comment by MarjieAVolk** [comment]
I am not allowing this to be released, for the record :P
