### ISSUE TITLE
Contract creation UI opens off-screen

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3285]
![image](https://user-images.githubusercontent.com/6262198/34701722-9ab1d9f8-f49e-11e7-92d2-fa19ce98377e.png)
Confirmed repeatedly happening

**Comment by MarjieAVolk** [comment]
Hm, that should be clamped to the screen by UIManager I would think

**Comment by Nanders** [comment]
I will add that if I try to resize the window, it will pop into the screen. Close the UI and reopen, and its off screen again.

**Comment by MarjieAVolk** [comment]
actually that sounds like an exception during initialization

**Comment by johnkslg** [comment]
Fixed in next pr
