### ISSUE TITLE
Change the wording from "citizen" to the player's username

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3289]
![image](https://user-images.githubusercontent.com/6262198/34701915-b382cb08-f49f-11e7-981d-9c0d7b4b20c2.png)
"Welcome to Eco, citizen"
I think the word "citizen" is a little goofy, consider changing this string to be the players username instead.

**Comment by Nanders** [comment]
While Im at it:
![image](https://user-images.githubusercontent.com/6262198/34702074-a76d9a5e-f4a0-11e7-8ee6-eda18a825a5d.png)
The first paragraph might be weird if a player reads it while playing single player. Just a consideration.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#326
