### ISSUE TITLE
Eco Configuration Not remembering my Graphics Quality 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3292]
when i load i always get this
![snap960](https://user-images.githubusercontent.com/29383891/34735876-edf0da4a-f568-11e7-9e94-6b9177944f1e.png)
it Never remembers that i always choose Fantastic
![snap961](https://user-images.githubusercontent.com/29383891/34735897-021cb818-f569-11e7-974e-cde8e1ffabfc.png)

this is after exiting Game properly (i would understand this if i had problems closing the game and it not remembering the settings)

also could it be possible to have the Version Number showing on this window??

**Comment by Nanders** [comment]
This window is going away soon, but I'll leave this bug open until it is officially removed.

**Comment by Conchipedia** [comment]
so when we launch (example steam) we go straight into the game part? or another special window? only put this in as i had to keep telling Eco what i wanted it to load at as it didn't seem to want to remember my settings

**Comment by Nanders** [comment]
Yes, it will launch straight into Eco.

It will be like a big boy game and not use the default unity launch window, All graphics settings will be handled in the game

**Comment by Nanders** [comment]
This is fixed, graphics setting dropdown did nothing anyway,
