### ISSUE TITLE
Text on Contract UI frequently breaks

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3295]
![image](https://user-images.githubusercontent.com/6262198/34738400-b59b5836-f52d-11e7-93b2-1164d4bea84f.png)
Confirmed repeated multiple times, happens when reopening an incomplete/unposted contract.

**Comment by MarjieAVolk** [comment]
Yeah it does this if the content is too wide to fit otherwise.  I tried to avoid it being too wide instead of trying to fix that.  But I guess I was not successful.  I'm thinking that window can just have a much higher minimum width.  It's pretty small right now, for no particular reason

**Comment by Nanders** [comment]
Also
![image](https://user-images.githubusercontent.com/6262198/34746278-463a346a-f548-11e7-94a5-f8bc17e672cd.png)

**Comment by MarjieAVolk** [comment]
Why does it say Put Items in Container but have a Reputation drop down?

**Comment by Nanders** [comment]
Because there are lots of problems with contracts

**Comment by MarjieAVolk** [comment]
lol yeah I see now, when you select something it creates a new clause instead of changing the existing one O.o

**Comment by MarjieAVolk** [comment]
Hopefully fixed.  May still pop up from time to time... if it's still an issue I'll look into a better fallback for the layout

**Comment by Nanders** [comment]
This is still occurring

**Comment by MarjieAVolk** [comment]
Fixed for real, instead it will now just overflow horizontally, hiding the right part of the content, if the window is too small.
