### ISSUE TITLE
Contract does not detect my construction post if it is not on my property

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3296]
I think this should be possible.

**Comment by johnkslg** [comment]
Problem is contracts give you rights on the property of stuff you specify.  Whats the use case for posts on not-your-property?

**Comment by Nanders** [comment]
Most any instance of building a road

**Comment by Nanders** [comment]
Or if I'm a mayor and want to designate areas for where new buildings should be built in the city, I shouldn't have to own them.

If its public property, it should be ok.
