### ISSUE TITLE
Tons of missing script warnings

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3300]
Many say 'The referenced script on this Behaviour (Game Object 'MeteorChunk (10)') is missing!'

There are also some 'The referenced script on this Behaviour (Game Object 'SHOCK_WAVE_MESH') is missing!'

**Comment by johnkslg** [comment]
Probably fixed with your changes?

**Comment by MarjieAVolk** [comment]
Not seeing these anymore, may or may not have been a prefab import problem
