### ISSUE TITLE
World marker overlay should track around the screen

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3301]
![untitled-1](https://user-images.githubusercontent.com/6262198/34739376-ed7ef67e-f530-11e7-8f21-bcb974a4eacd.png)
The pointer should travel smoothly around the screen, like (crappily) illustrated. It currently only snaps to the right or the left side of the screen.

**Comment by elfl0rd** [comment]
@D3nnis3n 
![default](https://user-images.githubusercontent.com/4980243/49964574-e2e2ef80-ff2b-11e8-9545-ba1edcc28abd.png)

**Comment by D3nnis3n** [comment]
Yeh, it works with single ones, but if you have multiple ones it's still snapping weirdly while it could show better afaik.
