### ISSUE TITLE
There should be default text on tabs where nothing is detected

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3302]
![image](https://user-images.githubusercontent.com/6262198/34739682-e49f61f0-f531-11e7-88a6-07bdbeebcc12.png)
I think it is confusing when I click a tab and the content window is blank. 

In this instance, we should display something like "No storage detected"

**Comment by MarjieAVolk** [comment]
agreed, been confused by this too recently
