### ISSUE TITLE
Interaction Key UI sometimes displays impossible actions

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3305]
![image](https://user-images.githubusercontent.com/6262198/34740542-a07eaa96-f534-11e7-9517-23da0613cdf9.png)
I cant pick up the chest with a deed.

**Comment by MarjieAVolk** [comment]
I think take in this case means take something out of the chest.  Which you also can't do with deeds, but is more reasonable

**Comment by Nanders** [comment]
Ah ok that makes more sense, but is still impossible

**Comment by johnkslg** [comment]
You can take logs out of stockpiles with left click. For chests I suppose it should be disabled.  Or maybe you should take out the first item in them?

**Comment by SlayksWood** [comment]
We still have some problems, but this issue is out of date. We have some iteration problem with tools and torch, but we have separate issue for this problem #13612, #11979.
So we can close this issue.
