### ISSUE TITLE
Store UI element alignment nitpicks

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3306]
![image](https://user-images.githubusercontent.com/6262198/34740842-a0648430-f535-11e7-8cf3-2da052298ae3.png)
This horizontal bar is misaligned by several pixels on the left, and by one or two pixels on the right
Also I'm pretty sure the vertical bar is set too far up

![image](https://user-images.githubusercontent.com/6262198/34740952-fab08916-f535-11e7-9c5f-3e0d475b34d9.png)
This horizontal bar is shifted to the left by one pixel

**Comment by MarjieAVolk** [comment]
I was under the impression that those horizontal bars were supposed to stick out a bit, but you are right that it is inconsistent.

**Comment by johnkslg** [comment]
Closing for now as we have a UI pass planned for art.
