### ISSUE TITLE
Need better consistency across all worldobject UIs

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3307]
Consider the elements and design used in treasury
![image](https://user-images.githubusercontent.com/6262198/34741100-6e2c9902-f536-11e7-84f0-b357cfa79a8e.png)

vs store
![image](https://user-images.githubusercontent.com/6262198/34741149-905beb5e-f536-11e7-9c3c-dabc7282605b.png)

The horizontal dividers look much more finished on the ladder, and pretty ugly on the former.

This is just one example, but this kind of inconsistency can be found all over the place, even between tabs on the same UIs.

**Comment by Nanders** [comment]
Probably need a style guide and do a pass over all UIs to normalize them.

**Comment by Nanders** [comment]
Also taking this opportunity to point out the bad justification and line spacing on Treasury. e.g. the line "(nanderson credit) 0"

**Comment by johnkslg** [comment]
We will address this with an art pass on the full UI soon, so closing this for now.
