### ISSUE TITLE
Cursor for search and select UI is too high

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3308]
![image](https://user-images.githubusercontent.com/6262198/34741466-97be63ee-f537-11e7-99a1-7b8e550cc592.png)

**Comment by MarjieAVolk** [comment]
I swear there is another bug for this but I can't find it.  Yeah long time issue... I have tried and failed to fix it, I don't understand it

**Comment by SlayksWood** [comment]
Seems fixed, but it happens sometimes in other UIs. But we can open new issue if it happen again.
![image](https://user-images.githubusercontent.com/45708377/71239712-46121980-2318-11ea-8bd7-c7b1e9dba9ec.png)
