### ISSUE TITLE
Fix wording and misspelling

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3311]
![image](https://user-images.githubusercontent.com/6262198/34742366-cde222fa-f53a-11e7-9032-9f8476e44922.png)
"This block" - Id change this to 'This clause" because thats what it is referred to everywhere else.

"Depoists" - "Deposits"
  

![image](https://user-images.githubusercontent.com/6262198/34745742-59c115e6-f546-11e7-8d3b-1f2b8469711d.png)
"You've run completely out of  calories" - "You've completely run out of calories"

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/34746326-65e51a32-f548-11e7-8124-18be832be1cc.png)
"Reuptation" - Reputation

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/34745891-f2868090-f546-11e7-8f6d-24b2d78afa71.png)
"The average nutrients in your food increases your skill rate" - This wording makes me go cross-eyed Perhaps " Eat foods with more nutrients, and eat a balanced amount of each nutrient in order to increase your skill gain"

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/34748853-78a4d666-f553-11e7-96d7-13c6f642b9e9.png)
"Lattrine" - Latrine

**Comment by Nanders** [comment]
![unknown](https://user-images.githubusercontent.com/6262198/34897980-9fdc742e-f7a5-11e7-90f7-a399f38ba7fb.png)
Fix run-on sentence "A table for basic wooden crafts for home improvement and progress"

**Comment by johnkslg** [comment]
Removing high priority

**Comment by WeaselDog** [comment]
Reputation clause & Wooden Latrine are fixed:
![ReputationClause](https://user-images.githubusercontent.com/47330823/70867174-5052a300-1f27-11ea-85f7-30c07743556f.png)
![WoodenLatrine](https://user-images.githubusercontent.com/47330823/70867175-5183d000-1f27-11ea-9ee9-a53b586abf14.png)
