### ISSUE TITLE
Contract UI help does not always display the correct help

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3312]
![image](https://user-images.githubusercontent.com/6262198/34742555-5f17466a-f53b-11e7-8f98-818df2dbb5b5.png)
This displays "Harvest Field" for "Mow Lawn"

**Comment by johnkslg** [comment]
Fixed in next PR

**Comment by GophTheGreat** [comment]
I assume this was fixed because it appears to be fine now.
