### ISSUE TITLE
Contract Clause UI has overlapping elements

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3315]
![image](https://user-images.githubusercontent.com/6262198/34742775-39e8041e-f53c-11e7-8c53-83f777cb3006.png)
The four buttons partially obscure the drop down arrow for the clause selection

**Comment by MarjieAVolk** [comment]
Yeah I was aware of this also.  I'm not sure how to reconcile it, since John really wants those little buttons but rearranging the UI to make them look good both there and not there will be hard and weird

**Comment by Nanders** [comment]
Why cant they always be there?

We don't have buttons that appear on hover-over in the UI anywhere else in the game.

**Comment by Nanders** [comment]
>make them look good both there and not there will be hard

![3e666535e1d1ae2cef3b2104427e004b--random-things-quotations](https://user-images.githubusercontent.com/6262198/34743042-326dbd9a-f53d-11e7-9200-8bc7c1018907.jpg)

**Comment by MarjieAVolk** [comment]
I don't know, this is what John wanted.  I agree, they should be actually a part of the UI.  Right now these buttons have their own separate prefab that is used in lots of places and gets automagically added by this big confusing system.

**Comment by MarjieAVolk** [comment]
Maybe I should just put a margin at the top of each clause.  I guess they could have a title bar.  Although it would most likely be redundant with the first drop down and take up a lot more space

**Comment by Nanders** [comment]
Could just scoot the right bounds of the dropdown to the left, fast and dirty. 🤢

**Comment by MarjieAVolk** [comment]
yeah that's a similar solution.

**Comment by SlayksWood** [comment]
seems fixed
![image](https://user-images.githubusercontent.com/45708377/71240566-88d4f100-231a-11ea-8514-3e9e2f06830a.png)
