### ISSUE TITLE
Interaction Key UI still remains after UI is opened.

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3320]
![image](https://user-images.githubusercontent.com/6262198/34746050-7e2aacac-f547-11e7-9ce4-10e96593a93c.png)

Consider making this disappear, as once you've opened the UI, opening the UI again is not valid. I almost think that the Interact Key UI should not appear when you're tabbed

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#324
