### ISSUE TITLE
Missing script on something in ClientObjectMap

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3321]
The referenced script on this Behaviour (Game Object '<null>') is missing!
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ClientObjectMap:InstantiateFromType(String) (at Assets/Scripts/ClientObjectMap.cs:62)
GenericClient`1:SpawnObject(Int32, BSONObject, String) (at Assets/Scripts/Networking/GenericClient.cs:164)
PlayerClient:SpawnObject(Int32, BSONObject, String) (at Assets/Scripts/Networking/PlayerClient.cs:23)
GenericClient`1:NewNetworkObject(Int32, BSONObject) (at Assets/Scripts/Networking/GenericClient.cs:207)
Eco.Shared.Networking.NetObjectManager:GetObject(Int32, BSONObject, Boolean)
Eco.Shared.Networking.NetObjectManager:UpdateObjects(BSONObject)
NetworkManager:ReceiveEvent(INetClient, NetworkEvent, BSONObject) (at Assets/Scripts/Networking/NetworkManager.cs:331)
Eco.Shared.Networking.NetObject:ReceiveEvent(INetClient, NetworkEvent, BSONObject)
Eco.Shared.Networking.NetPort:ProcessBuffer()
Eco.Shared.Networking.NetPort:Update()
NetworkManager:Update() (at Assets/Scripts/Networking/NetworkManager.cs:287)

**Comment by elfl0rd** [comment]
@D3nnis3n too old...

**Comment by D3nnis3n** [comment]
Old issue.
