### ISSUE TITLE
Sometimes the [x] box on the tutorial disappears

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3322]
Makes them impossible to interact with and close

![image](https://user-images.githubusercontent.com/6262198/34746431-d8a36772-f548-11e7-8f8a-a38dc0ab5347.png)
(I'm hovering over them in this picture, the screen cap just does not capture the cursor)

**Comment by Nanders** [comment]
Might be related to #3323 3323

**Comment by johnkslg** [comment]
Hasnt happened, I believe this was fixed with 3323.  Reopen if still reproable.
