### ISSUE TITLE
Sometimes tabbing out makes all UI uninteractable. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3323]
I was in a contract UI, then tabbed out to make a bug report, reentered the game and now I cant click on anything.

**Comment by MarjieAVolk** [comment]
Is this in editor or in the build?

**Comment by MarjieAVolk** [comment]
Because if it's in editor then I feel like stuff like that is more likely to happen harmlessly

**Comment by Nanders** [comment]
Its in the build

**Comment by MarjieAVolk** [comment]
Oh well that sounds bad then

**Comment by MarjieAVolk** [comment]
Could this be related to https://github.com/StrangeLoopGames/EcoIssues/issues/3328?

**Comment by MarjieAVolk** [comment]
Also do you have an error log?

**Comment by MarjieAVolk** [comment]
IDK how to work on this.  Can't repro :'(

**Comment by MarjieAVolk** [comment]
Okay I have a question.  You say you can't click on anything.  I've been seeing a thing where you can't click to hide your cursor, but you can hit tab.  Is that what you saw here?

**Comment by MarjieAVolk** [comment]
I'm thinking that the thing I'm seeing is a problem in NetworkManager, which is the thing that opens and closes PlayerUIMouseInputToggler.

**Comment by MarjieAVolk** [comment]
Is there a chance that that block of NetworkManager.Update that marks finishedLoading = true might not get called in some circumstances?

**Comment by MarjieAVolk** [comment]
Okay nvm I take it back, just saw this happen while I had breakpoints down in NetworkManager.  I clicked to hide the cursor, then hit tab to show it, and then when I clicked again the thing was gone and it didn't work.

**Comment by MarjieAVolk** [comment]
Okay.... just had it happen again, and I had a breakpoint on UIManager.Close.  So... something else is destroying this object.  It's not destroying itself.  What would do such a thing?

**Comment by metachronism** [comment]
dropping priority due to repro status
