### ISSUE TITLE
Objectives are not passed through the profanity filter

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3325]

**Comment by Yorkforce** [comment]
Would like to also add that Names, Carts and Signs are also not passed through the profanity filter, as a public server this is proving challenging ensuring the server is suitable for all ages.

**Comment by D3nnis3n** [comment]
Government Allocation Reasons are also not passed through the profanity filter.

**Comment by WeaselDog** [comment]
all of these are fixed in 9.0
