### ISSUE TITLE
Skills UI tooltips block me from clicking on other skills

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#3327]
![image](https://user-images.githubusercontent.com/18184943/34751687-e9acb5ea-f562-11e7-8e66-c40bb8293124.png)

I can't click on farmer once I've hovered over carpentry

**Comment by MarjieAVolk** [comment]
Right yeah this was bugging me a lot too.  I tried to fix this by increasing the delay until tooltips came up.  But I had to compromise with @metachronism lol so it's still shorter than the value that I found worked well.

I guess I could try to fix this particular instance by like making these prefer to be placed to the left or something.  Which might or might not be pretty easy to do.
