### ISSUE TITLE
6.4 - if you open the escape menu in game, after closing it you can no longer move

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3328]

**Comment by metachronism** [comment]
this seems to be only if you are in third person mode

**Comment by SeanAtr0n** [comment]
happens after opening the advanced menu for me

**Comment by MarjieAVolk** [comment]
You know I'm wondering if this and https://github.com/StrangeLoopGames/EcoIssues/issues/3323 are prefab import issues too?  Just about to go debug

**Comment by MarjieAVolk** [comment]
nvm it's because the advanced settings menu object has a script on it that is a ModalUI, which wasn't getting closed properly to release it's input focus.  Going to both remove ModalUI from there and ensure that ModalUI always releases focus when closed/destroyed/minimized
