### ISSUE TITLE
Skills migration (6.4)

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#3332]
I logged onto marmot and I still had some skills earned from the 6.3 playtest.  I could spend skillpoints in skills that required those even when I didn't have the associated specialization (e.g. I could add points to woodworking efficiency, but not woodworking, without having the hewing specialization).

**Comment by MarjieAVolk** [comment]
Hm I kind of think that's okay?  Not sure how we would fix that easily, and it's not like game breaking or anything right

**Comment by metachronism** [comment]
this wasnt a clean migration from 6.3->6.4, you had a partial migration afterwards between stagings, so your skills were only correctly reset the first time
