### ISSUE TITLE
Crouch no longer works

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3334]
Are we going to include crouch at all? Can disable it if no.

**Comment by MarjieAVolk** [comment]
IMO it's not very useful.  Unless we also support not falling off of things

**Comment by SeanAtr0n** [comment]
Thought the consensus was to remove it... crouching was doing ridiculous things w/ physics, also we need animations if we do crouching

**Comment by Nanders** [comment]
Leaving this open until I I remove the control UI from the escape menu

**Comment by Nanders** [comment]
Fixed
