### ISSUE TITLE
Tree debris is tier 0?

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#3336]
![image](https://user-images.githubusercontent.com/609510/34753257-d15a9b84-f56b-11e7-8e19-9228a01b9dde.png)
Seems pretty weird.

Also, asphalt road is tier 0, but stone road is tier 1?

**Comment by Arend90** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/329
https://github.com/StrangeLoopGames/EcoIssues/issues/3229
cries out loud!
