### ISSUE TITLE
Interact Key UI should display property restrictions 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3339]
If an action is valid, but I can't complete the action because of property permissions, the UI should either not display, or display that I cant because of permissions.

**Comment by elfl0rd** [comment]
@D3nnis3n hmm... sounds as red\green highlight.

**Comment by WeaselDog** [comment]
There is a red outline now with the correct error message. The UI does not open.

![UINotAuthorized](https://user-images.githubusercontent.com/47330823/70856472-b2ad9400-1e92-11ea-82d3-7c97b4c678dd.png)
