### ISSUE TITLE
Dancing tree pieces

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3340]
![tree bug](https://user-images.githubusercontent.com/6262198/34754895-9041cd48-f575-11e7-8c61-4a9521af0b50.gif)

**Comment by SeanAtr0n** [comment]
Did someone login just after this happened or did it say like that for a long time?

**Comment by Nanders** [comment]
This was happening for the entire play session, between logins/logouts

**Comment by johnkslg** [comment]
You ant chop these, so upping to critical

**Comment by MarjieAVolk** [comment]
is it because the logs are like stuck under those other blocks?  I'm not seeing this issue for all trees or anything like that

**Comment by Nanders** [comment]
I don't think that's the case, getting stuck under blocks, It was happening elsewhere in the open.
