### ISSUE TITLE
Need a way to reset law creation page to default state

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3341]
I was messing around in this menu, found out there was no way to get back to the default set-up without completing the form and starting a new one

**Comment by MarjieAVolk** [comment]
Hm yeah that is true.  I saw saving the state as being kind of a small benefit, but it is weird how only part of the state is saved right now.  Didn't even think about wanting to reset.  Although it should be pretty easy to just choose a different option for one of the higher up drop downs and delete everything that way

**Comment by rainfarmer** [comment]
its being added
