### ISSUE TITLE
Tree Sapling growing in Woodpulp Box

### ISSUE THREAD

**Issue by RapidestFlame** [StrangeLoopGames/EcoIssues#3345]
Issue is fairly obvious.

https://imgur.com/a/WpN5k

**Comment by Conchipedia** [comment]
I think this is due to the modded models having no collision detection, so things will grow into it or show through it, same happens for Christmas tree(s) and the extra Farmers shop, also i think there might be some other ones that do the same can't remember them all) I think these models are only on greenleaf Servers as i don;t think any other servers have had them added.

**Comment by MarjieAVolk** [comment]
Ah so this is a mod object, right.  Yeah, my first thought was that it didn't have proper occupancy.  @Nanders could you help them figure out how to fix the occupancy for their mod object?  I'm not sure who the mod owner is.

**Comment by Nanders** [comment]
Ah, yes. Need some way to get mod objects added to worldobject occupancy. Should be easy I think.

**Comment by Phlo123** [comment]
I built the mod, but without any world occupancy knowledge i didn't mess with that file. Mods will be better after Beta, from what I understood from JohnK, because SLG will have more time for modders then and I will get the information needed to build object.

**Comment by FyreAus** [comment]
You can probably close this issue:
Occupancy can be added easily enough already.
Add a static constructor to the WorldObject class file
Example below would for instance give occupancy of 3 blocks high (in the Y-axis)

`
static _Name_Object()
        {
            WorldObject.AddOccupancy<_Name_Object>(new List<BlockOccupancy>(){
                new BlockOccupancy(new Vector3i(0, 0, 0)),
                new BlockOccupancy(new Vector3i(0, 1, 0)),
                new BlockOccupancy(new Vector3i(0, 2, 0))
	   });
        }
`

I Imagine everyone in this thread already knows this by now. If I get time I'll add it to a tutorial somewhere.
Sorry for the necro guys, but I don't see why this issue should still be open.
