### ISSUE TITLE
Can't access escape menu while 'Entering World'

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3350]
If you ever get stuck 'entering world' there is no way to cancel

**Comment by Conchipedia** [comment]
seems to also not let you press ESC if you accidentally click on Continue it just sits there with that rotating Cog (been doing that for at least 10 minutes (its still sitting there while i'm typing this) ALT+F4 seems the only way to quit, or just end process on Task manager

**Comment by metachronism** [comment]
someone else fixed this
