### ISSUE TITLE
USER ISSUE: Any Table that requires tier 1 not working in log room 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3354]
**Version:** 0.6.4.0 alpha staging-6091a509

**Steps to Reproduce:**
build a wooden house/room , make a table on workbench, place created table inside house/room.

Room Volume 80
102 Logs, 22 Sand, and 42 Dirt

**Expected behavior:**
table should work

**Actual behavior:**
table won't work as no Tier 1 found and seeing as logs/dirt/sand are the only things we can make a room from Game Doesn't work.

this i also wanted to test the Report a bug from inside game
this is a duplicate of:
Tier 1 materials seem to be just stone road not logs as it should be 6.4.0 #4142876a #3229

**Comment by MarjieAVolk** [comment]
Good to see the report button works now!  What do you think of it?

We are working on the tier issues, should be fixed in the next staging build.  Gonna close this as a duplicate.

**Comment by Conchipedia** [comment]
it does seem good that all the relevant Information about game version is added at the top and that it is clearly set out and duplicated here the information as was entered in game, so we can further edit in Github
