### ISSUE TITLE
Disconnecting and reconnecting doesnt seem to detroy the old land on the client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3356]
![image](https://user-images.githubusercontent.com/3536496/34804569-2620c95a-f62e-11e7-8e4f-c5252c16a26a.png)

With the far plane turned up you can see it as above.

**Comment by SeanAtr0n** [comment]
looks pretty similar to a small world wrapping issue ive seen before

**Comment by johnkslg** [comment]
Could be that too

**Comment by metachronism** [comment]
this is caused by the wierd prefab importing issue everyone is seeing - reimport your assets
