### ISSUE TITLE
starting new world generation shuts down server power ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3357]
so i generated world with 6.4.0 #4142876a there are no issues

I then deleted the world and files and reverted back to older version and server crashed during world generation of landscape.

I deleted all game files tried it again crashed.

I then deleted that went to theEcoPC_v0.6.4.0-alpha-staging-6091a509 and it now crashes also during the world generation

there is no game log file being generated but there is a server event being generated ever time eco trys to do world generation.

vent filter with query "SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA "Win32_Processor" AND TargetInstance.LoadPercentage > 99" could not be reactivated in namespace "//./root/CIMV2" because of error 0x80041003. Events cannot be delivered through this filter until the problem is corrected.

I am not sure why it would work one time create a world and run fine and then all of sudden stop working being able to generate new world.??

it seems that eco so far is only dedicated server software that causes the server hardware to crash and shut down and it only does it when it hits about 40% of the world generation.

**Comment by midn8t** [comment]
hardware is running on 2008 Server software, other games and software do not seem shut down server, eco does not shut it down till it gets to world generation part.
--
I am trying to run eco server software by it self with out any other game software running.

**Comment by midn8t** [comment]
hardware is running on 2008 Server software, other games and software do not seem shut down server, eco does not shut it down till it gets to world generation part.

I am trying to run eco server software by it self with out any other game software running.

**Comment by midn8t** [comment]
![image](https://user-images.githubusercontent.com/15990789/34895610-30268b36-f7ac-11e7-9270-3ecd76cf9cb3.png)

above is screen shoot to show what its doing, this is with the latest alpha build EcoServer_v0.6.4.0-alpha-staging-9d99a945   it just hanging there and eventual it just crashes.

**Comment by midn8t** [comment]
I added screen shoot show what it is doing it just hangs there at generating landscape 
![image](https://user-images.githubusercontent.com/15990789/34895771-bcdb1f1a-f7ac-11e7-87cd-1e430122a313.png)

after while it will just crash the whole server.  this is with the latest EcoServer_v0.6.4.0-alpha-staging-9d99a945

**Comment by metachronism** [comment]
this is intended, though it might change a bit to give more feedback during generation.  world gen was setup to dump info to the console while it was doing work, once it is finished the server will be up and running as normal
