### ISSUE TITLE
USER ISSUE: Choose Roles Tutorial (showing a mouse shape would look better as an arrow)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3358]
**Version:** 0.6.4.0 alpha staging-9d99a945

**Steps to Reproduce:**
Follow Tutorial

**Expected behavior:**
only because i know where the Skill menu is i know what to click

**Actual behavior:**
![snap989](https://user-images.githubusercontent.com/29383891/34840628-80d3148c-f6fd-11e7-93ca-43f82bc24b3e.png)

**Comment by knexer** [comment]
See also #3280

**Comment by johnkslg** [comment]
Fixed in staging
