### ISSUE TITLE
USER ISSUE: Skill points way to high for basic tools

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3359]
**Version:** 0.6.4.0 alpha staging-9d99a945

**Steps to Reproduce:**
learned logging 0 points (given axe)
learned mason 5 points (given pickaxe)
Digging 38 points (to get a shovel)
Gathering 38 points (to get a scythe)

**Expected behavior:**
it should Not need this many points for basic tools

**Actual behavior:**
will take two days just to get another basic tool

wouldn't it be more sensible to just unlock the tools as before with 1 point for each tool?

**Comment by Arend90** [comment]
Lonewolf -100 :p what about you make your tools in the workbench

**Comment by Conchipedia** [comment]
just following tutorial, so havent even gotten to placing a workbench yet

**Comment by Arend90** [comment]
I like it that you need 5 to 10 persons to start a city/group to kill the meteor

**Comment by Arend90** [comment]
Tutorial should start in survival with the hammer and work bench I guess you started with mining

**Comment by Conchipedia** [comment]
i followed it (i automatically try and get all the baisc tools first) i also normally gather before finding a place to live

**Comment by Conchipedia** [comment]
because i have played before i forgot about this bit on workbench
![snap995](https://user-images.githubusercontent.com/29383891/34841983-fea1deda-f701-11e7-8398-be8822abbde5.png)

**Comment by Conchipedia** [comment]
but what i can see if you make a mistake after you get axe for 0 points, and havent learned mining to get a pickaxe you will have to wait a while to make the other tools

**Comment by MarjieAVolk** [comment]
I am not sure whether this is intentional or not.  I think we want to encourage people to specialize more, to the point of not necessarily getting all the basic tools.

**Comment by MarjieAVolk** [comment]
But yeah it might be really easy to screw yourself over right now

**Comment by Arend90** [comment]
we will never get the lonewolf out of conchita 🗡 but i really love the idea people just have one specialization and have to trade for the other stuff <3 as cook you can trade food for a nice house

**Comment by craig-jong** [comment]
Removed the level requirement for repairing T1 tools - we'll have to figure out something for stopping people from screwing themselves over.
