### ISSUE TITLE
tier 1 not showing in tables latest staging

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#3360]
no tier one or any other tier in the starter tables
https://cdn.discordapp.com/attachments/367065974324854794/400949454577860618/unknown.png

https://cdn.discordapp.com/attachments/381992834384789504/400949701127700490/unknown.png

https://cdn.discordapp.com/attachments/381992834384789504/400950319938273280/unknown.png

Tier 2 does work https://cdn.discordapp.com/attachments/381992834384789504/400950499760668692/unknown.png

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3229
