### ISSUE TITLE
USER ISSUE: Repairing basic Tools need to learn Stoneworking 1 and woodworking 1 (thats a massive 78 skill points)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3363]
**Version:** 0.6.4.0 alpha staging-9d99a945

![snap1006](https://user-images.githubusercontent.com/29383891/34843413-593324cc-f706-11e7-9d8c-557e0f8a35f7.png)
![snap1007](https://user-images.githubusercontent.com/29383891/34843414-594ff750-f706-11e7-8d0b-aa14fbc455ce.png)
as you can see to repair a stone tool i need to learn stoneworking 1(1 point) but before i can learn that i need Mortaring (38 points)
![snap1005](https://user-images.githubusercontent.com/29383891/34843566-b1a78c60-f706-11e7-87b2-2496c8799645.png)
![snap1004](https://user-images.githubusercontent.com/29383891/34843588-c21b91c2-f706-11e7-9d27-373872a9e8ca.png)
as you can see to repair wood tool i need to learn woodworking 1 (1 point) but before i can learn that i need hewing (38 points)

so only way to play is to just make loads of extra tools and find a place to store them until i can get 78 points and at basic 22.7 a day that will be in about 3 and a half days.

**Comment by Arend90** [comment]
lonewolf -10000 Conchita 🍡 work together with your friends 🗡

**Comment by Arend90** [comment]
get a friend for food and you have more then 20 from food a day

get a friend to carpent furniture for you and you have an other 50 points a day

get a friend that repairs your tools and you dont need the 80 points anymore

**Comment by Conchipedia** [comment]
its not a case of lonewolfing its basic tool repair, i would have broken the tools just making my tools and a few extra bits for crafting other basic stuff

**Comment by Conchipedia** [comment]
just a thought about making tools why cannot we repair them if we can make them?
we have enough skill to make a repair station, we can craft tools on a workbench with raw materials but we need to learn more skills to repair what we just made.

**Comment by craig-jong** [comment]
I've removed the skill req for repairing stone and wooden tools. The repair requirements for later tools is still there, though.

Should be reflected in the next staging build.

**Comment by Conchipedia** [comment]
sounds good to me, if we can make them we should be able to repair the basic ones, and repairing higher level tools soon sorts itself out anyway as by the time you get to the level of making them a player is normally on good SP a day anyway and it shouldn't be that hard to unlock the next level
