### ISSUE TITLE
[Suggestion] Underground Fan System or Exhaust piping For Excavator Air Pollution

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3368]
Note: Both are Air pollution leftmost is caused by Excavator and Right is output through pipe system from all tables generating Pollution
![snap1016](https://user-images.githubusercontent.com/29383891/34853526-2334fa8c-f72c-11e7-9fd9-1b3c327715ad.png)
![snap1017](https://user-images.githubusercontent.com/29383891/34853527-234d943e-f72c-11e7-8aaa-f8ea2b5a5ff8.png)

I am using an Excavator for the first time should the Air pollution it gives off underground be the exact same % 40 levels above on the surface?
i would have thought that going through solid rock/ore and dirt would dissipate this effect

two possible suggestions:
1. Fan System sucking Air pollution generated by Excavator and then using a Pipe system to move this elsewhere.
2. having a hose system attached to Exhaust of Excavator to an Extractor that can use pipe system to move this elsewhere.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#323
