### ISSUE TITLE
Minimap will need an update for when the meteor destroys rivers

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3369]
Works great and updates super fast, just needs to be able to destroy rivers
![image](https://user-images.githubusercontent.com/3536496/34856313-4f40bde2-f6f9-11e7-8a54-e844acfa1383.png)

**Comment by SlayksWood** [comment]
still an issue

**Comment by redwyre** [comment]
What is the problem? That the river sticks out into the crater?

**Comment by Daniel-Magulado** [comment]
Seems to be fixed on 0.9.5 Develop-348. Minimap now shows properly destroyed terrains including rivers.

![image](https://user-images.githubusercontent.com/77248866/128414372-3f425466-465c-4fa8-a655-0a71abf63da5.png)
