### ISSUE TITLE
World Layer selection needs polish

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3371]
![image](https://user-images.githubusercontent.com/3536496/34859044-bbdc55ba-f708-11e7-8249-e5b73ef0be02.png)

This list is miles long, the scroll box is tiny, and its hard to know what stuff is in there.  
Let's have collapsible groups and a large selection area.

**Comment by Nanders** [comment]
Partially related to #3283 

We should create a more proper Dropdown UI prefab. One that handles searching by string. This goes along with better UI normalization.

**Comment by knexer** [comment]
I think having a hierarchy (with collapsible groups, either nested or just flat) is preferable to searchability (though we can, time and usability permitting, just do both).  Users will be in wasd + mouse mode when they encounter this UI, so we shouldn't force them to move both hands to the home row.

**Comment by knexer** [comment]
As #3283 describes we could bandaid this by just not resetting the dropdown position each time it's closed.

**Comment by Nanders** [comment]
> I think having a hierarchy...

This is a good point. Having a more robust dropdown is still needed, but its probably not best for this case.
