### ISSUE TITLE
Getting a shovel is still pretty confusing

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3374]
Digging doesn't belong under Farmer.  I actually think digging should be a free specialty under Survivalist.

Also, we can have as many starting specialties as we want now, so we could split the survivalist specialty up if desired.

**Comment by craig-jong** [comment]
I'm hesitant to agree with this, though I do agree the shovel is one of the more "utility" tools. Still, you don't need the skill to get a shovel, nor do you need the skill to use it.

Might consider pushing this to survival but I don't think this is medium priority.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#322
