### ISSUE TITLE
Unified color scheme for skills

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3379]
![image](https://user-images.githubusercontent.com/3536496/34901732-404c6eec-f7c3-11e7-8bf5-1e7c45293a35.png)

The green shade of professions makes it really clear which ones I hold.  I suggest propagating that to specialties and skills as well, rendering a green background when i hold at least one level in them.  

Specialties especially could use it. Right now, the one I have is 'mortaring', but at a glance it has the red circle on it which communicates that I dont have it, while the one I dont have (mining) is marked with a green circle.

**Comment by johnkslg** [comment]
Another suggestion:  draw lines that show the nature of professions to specialtes, that specialties exist beneath professions as a group.

![image](https://user-images.githubusercontent.com/3536496/34901745-8ecfd374-f7c3-11e7-89e9-bd57b9133fe7.png)

**Comment by MarjieAVolk** [comment]
Yeah I chose to have the specialties look like the skills instead of like the professions, since I thought they were more similar to skills.  But if we want all 3 to look like professions, I could see that working well.
