### ISSUE TITLE
Roadtool no longer kills plants

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3385]
![image](https://user-images.githubusercontent.com/6262198/34910893-e78a1e16-f872-11e7-8bd6-498455768df3.png)

**Comment by Subtra** [comment]
Thats not actually right, most of the time its a login problem, like server synchronization with your client, you need to relog and look if its still there. If its still there, you can work around it by digging it out and put the earth back in.

**Comment by MarjieAVolk** [comment]
Looks like the code no longer explicitly deletes plants.  @Subtra maybe what you are seeing is that after a tick the plant is killed, since it's no longer on fertile soil.  Relogging takes enough time that a tick might often happen in that time.

**Comment by MarjieAVolk** [comment]
Well looks like @Subtra was right after all, now that I've started working on this.  The plants are getting deleted by something.  Locally mine are taking a second or two to disappear.  But I guess that is okay.  Wondering if this got changed with the plant changes that just went in
