### ISSUE TITLE
Storage Improvements From Benches

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3386]
Allow the player to select which containers the workbench can take from and to which to output to.

http://ecoforum.strangeloopgames.com/topic/3228/manuheel-s-list-of-improvement-ideas

**Comment by MarjieAVolk** [comment]
I have been meaning to add this feature for a long time also.  It won't be in for beta, but I may get a chance to work on it shortly after.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2190
