### ISSUE TITLE
Sliding on Roof

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3387]
There is an issue when placing roof, you tend to slide off it, unless you are able to pinpoint the very small area at which you won't slide on.

This leads to very hard building of roofs.

http://ecoforum.strangeloopgames.com/topic/3228/manuheel-s-list-of-improvement-ideas

**Comment by MarjieAVolk** [comment]
Don't really know what the solution to this is, thus why I assigned everyone :P

Could/should this be solved with colliders?  Or a character controller change?  Or some other physics shenanigans?

**Comment by Nanders** [comment]
Fixed, this is no longer the case
