### ISSUE TITLE
Wooden Sign Improvements / Fixes

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3388]
First of all, "Wood Sign" should be called "Wooden Sign

Then there is the character limitation of it's text, the problem is, there is none, please add limitation to the lines/characters a player can write on each wooden sign.

http://ecoforum.strangeloopgames.com/topic/3228/manuheel-s-list-of-improvement-ideas

**Comment by Conchipedia** [comment]
No limit on how much text can be placed in a sign and too much gives sky writing 6.0.3 #2773
linking this

**Comment by MarjieAVolk** [comment]
It's true we've got Wooden Shovel vs Wood Sign and Wood Cart.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#320
