### ISSUE TITLE
[6.3.1 Server] Taking over 12.0 GB RAM  to load server - "Stones Raining from Heaven"

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3389]
There appears to be an issue with this game save, there are no error or crash logs but the RAM used to try and load this server is over 12.0 GB which is extremely high and hard to a dedi host to support.  After server loaded and came only, and rand for about 5 minutes RAM dropped to 3.4 GB RAM, a more normal amount for a 200X200 dimension world.  Link to Game.eco here:  https://www.dropbox.com/s/6quyf2wd4j96cn5/arkadiaBackupGame.eco?dl=0

Just to give you a idea of why i think this servers is taking too much RAM during load times.  Running several other servers on the same hardware, with the same world dimensions but more citizens and more world objects created and saved in game, but these are taking less then 4.0 GB RAM to start up and load the world.  I can provide, short term, enough RAM to allow them to load but long term this is no sustainable if all servers are going to start needing more the 12 GB to load a game - not without addition server costs.  Its a lot of RAM for a game to load.  We are loading games like ARK and Conan which are reading and loading over 100,000 game files and only require 3GB RAM to load.  I know that is comparing apples and oranges when you have only 192 GB of RAM, allot 12 GB per game is a great deal of overhead.  I am hoping that there is a bug plaguing this server that can be fixed and that the behavior of the other servers is the more consistent behavior.

**Comment by Subtra** [comment]
I can actually add to that, its possible there is an error in the Object Creation, it has to do how mining works in this Game. If you mine Stone and other Materials the split up in up to 4 different objects. Its possible that the Game thinks it needs to create even more objects and add them after it creates a major RAM Usage cause it drom them from Heaven (Its raining Stones hallelujah) So you got more Objects then the Server initially saved, need to amount the ragdoll effects, they can be heave and restart with problems. So it takes heavy intial Load and even out at the end after all the additional Objects finished loading and rolling around like frolicking bunnies. Its just theory base on how we cant evade stone on montain where they shouldnt be. And i mine a horrifying amount of stone to get streets running. So look there please if you time my lovely Developers :P

**Comment by pamduncan** [comment]
Ah, Subtra, the "stones raining from heaven" You mentioned?  Note to devs:  Subtra is a player on the server linked her so would be able to report what is happening in game.

**Comment by pamduncan** [comment]
Here is another world, on a different server and this one is driving us crazy trying to get it enough RAM it when it stops and needs to start again.  It required 14GB of RAM to load without crashing with Out of Memory  error.  These worlds are really not something that a hosting provider can support without charging a customer a great deal more for this RAM - but then again they don't need it except when trying to start up the game.  https://www.dropbox.com/s/2i2jhgu2n4v0jon/01-22-2018-11.08.03.eco.zip?dl=0

**Comment by metachronism** [comment]
fixed with earlier optimizations
