### ISSUE TITLE
USER ISSUE: Placing a Dirt Block on top of Debris locks up player toolbar (caanot choose anything on it)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3390]
**Version:** 0.6.4.0 alpha staging-d2f49058

**Steps to Reproduce:**
place a dirt block on top of debris

Only Disconnecting and logging back in fixes this

**Comment by MarjieAVolk** [comment]
Tried this out for a bit, and found when you place the dirt block there, you get a message saying you're not allowed to do that.  And then your inventory gets out of sync with the server.  So this is a client side interactions rollback issue

**Comment by SeanAtr0n** [comment]
fixed
