### ISSUE TITLE
USER ISSUE: Clambering not working on Stone blocks can only jump

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3391]
**Version:** 0.6.4.0 alpha staging-d2f49058
cannot get up stone steps, even tried rubble steps, also turning clambering on and off, only way to get up them is by jumping

**Comment by Conchipedia** [comment]
![snap1125](https://user-images.githubusercontent.com/29383891/35016426-5b78d2c8-fb10-11e7-9c00-f6c7498e4ae3.png)
if my old world gets updated to 6.4 with jumping only on steps that will be super annoying

**Comment by Nanders** [comment]
This is intentional
