### ISSUE TITLE
USER ISSUE: A chooped tree will stay in mid air and let you collect from it

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3392]
**Version:** 0.6.4.0 alpha staging-d2f49058

Not sure if it happens if someone else touches the tree you have chopped down
![snap1059](https://user-images.githubusercontent.com/29383891/34921087-50bf5e8e-f975-11e7-80de-dd7c127b8ce2.png)
![snap1060](https://user-images.githubusercontent.com/29383891/34921098-689b4392-f975-11e7-8c11-3eda698bb118.png)

**Comment by Conchipedia** [comment]
have noticed on Staging -a6a22be6 a tree will be sitting in the air or pieces of one then when a player gets close it all starts to drop, would have given a snapshot showing this, but it all fell before i was ready (wasn't expecting that to happen)

**Comment by SeanAtr0n** [comment]
fixed
