### ISSUE TITLE
USER ISSUE: Placed Rubble is being Counted as part of a room

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3401]
**Version:** 0.6.4.0 alpha staging-a6a22be6

**Steps to Reproduce:**
Just place 4 pieces of rubble to make a block in a room

**Expected behavior:**
it counts Dirt as part of a room but it will not count raw Stone

![snap1070](https://user-images.githubusercontent.com/29383891/34932592-56efa664-f9cb-11e7-9aea-ed532c9309c3.png)

**Comment by MarjieAVolk** [comment]
Working as intended.  A stack of 4 rubble will count as a wall made of stone
