### ISSUE TITLE
USER ISSUE: No Mortared Stone Recipe, we Need this to Continue

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3402]
**Version:** 0.6.4.0 alpha staging-a6a22be6

![snap1077](https://user-images.githubusercontent.com/29383891/34937143-9f9a133a-f9db-11e7-94e7-882b77fbd719.png)
As you can see above i have unlocked it all and Quarry has No Mortared Stone Recipe
![snap1078](https://user-images.githubusercontent.com/29383891/34937174-c79bf8a8-f9db-11e7-9787-e5e548b23e3c.png)
![snap1079](https://user-images.githubusercontent.com/29383891/34937198-d8c5c320-f9db-11e7-9ad1-b0a707dafc01.png)
And the Kiln i have built Needs it for the Room
![snap1080](https://user-images.githubusercontent.com/29383891/34937224-fb09b7ac-f9db-11e7-9ce6-a064669cff05.png)
![snap1081](https://user-images.githubusercontent.com/29383891/34937244-1128efd0-f9dc-11e7-81e1-8230c577444e.png)
Also We need it for the Skill Books to be made

**Comment by metachronism** [comment]
craig fixed this
