### ISSUE TITLE
USER ISSUE: Carrying too many logs

### ISSUE THREAD

**Issue by jc300570** [StrangeLoopGames/EcoIssues#3404]
**Version:** 0.6.4.0 alpha staging-d2f49058

**Steps to Reproduce:**
If you use the hammer to remove wooden housing items like walls/roofs it is possible to carry more than 20 items.  This then makes it imposible to interact with other items like the workbench (even if you place all of the objects).  A restart resolves this.

**Expected behavior:**

**Actual behavior:**

**Comment by metachronism** [comment]
This looks like an issue with prediction.  Server side rejects the change, but client side thinks it happened without issue.

**Comment by MarjieAVolk** [comment]
Oh, yet another client side rollback problem huh
