### ISSUE TITLE
USER ISSUE: Jumping and Clambering Needs Tweaking

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3405]
Version: 0.6.4.0 alpha staging-d2f49058

Cannot Clamber up any single dirt blocks you need to Jump.

Jumping up double Dirt blocks is jump followed by a little jump.

Cannot jump up double blocks of stone at all.

Jumping out the water is awkward, if you dive under the water then attempt to get out it makes sounds as if hitting the surface as a solid from underneath and the only way to get out is to dig a block out from the side so it is almost level with the surface and then you can get out.

Stairs are working fine with no sliding back down if you stop on them 👍 

We need the allowing of just going up single blocks as hunting animals and chasing is a pain enough as it is without the extra hassle of jumping all the time

**Comment by Conchipedia** [comment]
Main Reason for the idea of allowing us to just go up one block without jumping, a lot of players make natural steps into dirt or stone .
this one is just wood stopping dirt from falling down
![steps](https://user-images.githubusercontent.com/29383891/34999083-ae03c97c-fad8-11e7-846a-3f11d51948f3.jpg)
Even natural Tree Roots are used as steps when the soil erodes
![tree roots](https://user-images.githubusercontent.com/29383891/34999098-c28ad39a-fad8-11e7-8ac4-274e2db6d3c1.jpg)
A person Naturally walks up then like Stairs they don't Jump from root to root, and seeing as the World is created with loads of natural steps it makes sense to be able to use them

**Comment by Nanders** [comment]
Fixed
