### ISSUE TITLE
USER ISSUE: Minimap won't let you search if follow player is ticked

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3406]
Version: 0.6.4.0 alpha staging-d2f49058

If you want to search the minimap and drag it to look at other places it always starts moving back to center on player, i liked the old way that you could search but the map **ONLY** centered back over your player if you had map open and started to move around

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3367
