### ISSUE TITLE
[Suggestion] Adding Store to workbench with no requirements so anyone can make

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3410]
Seeing as the recipe for a Store is exactly the same materials as Basic tools, it would encourage players earlier on to have one and then start a trade system going, at the moment you need woodworking level 1 to unlock, maybe even add this as part of the Tutorial.

**Comment by Conchipedia** [comment]
would encourage a lot more friends and strangers interaction

**Comment by LiaungYip** [comment]
I believe this is implemented as of 0.7.0.0 - the Store is now unlocked by Basic Crafting 4.

**Comment by Conchipedia** [comment]
it looks as it is so will close this
