### ISSUE TITLE
Worlds spawning with almost no plants now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3412]
![image](https://user-images.githubusercontent.com/3536496/34960887-b08ac994-f9f1-11e7-853c-9638b0da2f3b.png)
![image](https://user-images.githubusercontent.com/3536496/34960897-b611da9c-f9f1-11e7-99d8-2bbe9195ac34.png)

**Comment by metachronism** [comment]
seems to be working fine here
verified both on a tiny world (20x20) and normal (100x100)
