### ISSUE TITLE
Login error text unreadable

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3413]
![image](https://user-images.githubusercontent.com/3536496/34962049-f97053ae-f9f6-11e7-8b87-603ba075a7b1.png)

**Comment by Conchipedia** [comment]
might be linked to this window
When i was kicked from Server with an Error Weird Window #3399

**Comment by MarjieAVolk** [comment]
Yep, duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3399

I can up priority if desired
