### ISSUE TITLE
Debris showing up as blocks instead of debris mesh

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3414]
![image](https://user-images.githubusercontent.com/3536496/34962747-e7549470-f9f9-11e7-9c67-73ca46f71cba.png)

**Comment by metachronism** [comment]
fixed for a while now, get svn

**Comment by MarjieAVolk** [comment]
I didn't see this until this morning, and I've synced svn

**Comment by MarjieAVolk** [comment]
well I guess something weird was going on, maybe it looked broken on master because of svn branch issues
