### ISSUE TITLE
[Suggestion] Soil Sampler allowed to be crafted with no skills

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3415]
Reason for this, some people will be planting gathered seeds, and seeing as we can make and repair all basic tools now under the Survivalist Skill, it would be nice to it have so players can inspect land to see when a plant is ready to be harvested (as often a plant looks full grown but isnt until it is checked), also if someone is smithing they will need one to check Pollution from Tailings, also handy for Players to check their own land for Pollution if someone close by has stored Tailings incorrectly or causing Air Pollution.

Will also give the players an idea of how plants and land works, possibly add this to a tutorial??

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#319
