### ISSUE TITLE
Client froze while looking into cache of blocks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3416]
![image](https://user-images.githubusercontent.com/3536496/34966037-9db8eec4-fa0d-11e7-8b5d-1655c45d9b27.png)
https://media.discordapp.net/attachments/265945766785187850/402613183459753987/unknown.png

Was digging and placing dirt when it happened.  I'm able to stop unity in the debugger and see that its failing to return from that function.  Happened in the editor.

**Comment by metachronism** [comment]
the exception is fixed
looking at large collections while debugging unity has always crashed it, we can't do much there
