### ISSUE TITLE
Shovel should be able to discard dirt by right clicking into space

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3417]
![animx](https://user-images.githubusercontent.com/3536496/34966352-e7d0a0ae-fa0f-11e7-994d-f43e481ebe23.gif)

**Comment by johnkslg** [comment]
![animx](https://user-images.githubusercontent.com/3536496/34966347-e03bd6d8-fa0f-11e7-9233-5b567a9f5070.gif)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/703
