### ISSUE TITLE
Water is invisible when looking through block preview

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3418]
![image](https://user-images.githubusercontent.com/6262198/34969608-70e2c1ec-fa24-11e7-9f6b-af99ff4ebf85.png)

**Comment by Conchipedia** [comment]
Water appears and Disappears depending on angle looking out. Did these 4 showing what i mean
![snap1500](https://user-images.githubusercontent.com/29383891/35710588-4565e23a-07b0-11e8-8b5e-7e6d512436b3.png)
![snap1501](https://user-images.githubusercontent.com/29383891/35710589-4585dc8e-07b0-11e8-87dd-9dbc565c7431.png)
![snap1502](https://user-images.githubusercontent.com/29383891/35710590-45a10aa4-07b0-11e8-9700-9196c0a2609b.png)
![snap1503](https://user-images.githubusercontent.com/29383891/35710591-45c0fcba-07b0-11e8-9c50-449215054e54.png)

**Comment by Conchipedia** [comment]
also Glass will Not show lighting
![snap1511](https://user-images.githubusercontent.com/29383891/35741406-a5e7d6ca-082f-11e8-97c2-e4ff314da5a2.png)
![snap1512](https://user-images.githubusercontent.com/29383891/35741408-a600eac0-082f-11e8-9ff0-b0dc3831b4cf.png)

**Comment by Conchipedia** [comment]
Glass showing bright in Minimap, but Framed Glass just showing as grey blocks
![snap1513](https://user-images.githubusercontent.com/29383891/35741858-c583d370-0830-11e8-853a-88a74e8d0040.png)

**Comment by Amphysbaenas** [comment]
i comfirm that bug
![desktop screenshot 2018 02 27 - 02 21 00 24](https://user-images.githubusercontent.com/29807119/36705417-457c3422-1b65-11e8-8463-d44832dd11ce.png)
![desktop screenshot 2018 02 27 - 02 20 57 98](https://user-images.githubusercontent.com/29807119/36705420-4781d308-1b65-11e8-9371-ff8843391776.png)

**Comment by Conchipedia** [comment]
i think it doesn't matter what type of window, its all to do with the glass that is used in it

**Comment by ClayC90** [comment]
This seems like the issue fixed in this post
https://answers.unity.com/questions/609021/how-to-fix-transparent-rendering-problem.html

**Comment by keegan-o** [comment]
Ah yes this was all the glass shader, should be fixed now.
