### ISSUE TITLE
It's not clear what "Play Actions" are

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3422]
![image](https://user-images.githubusercontent.com/6262198/34972401-266f1022-fa36-11e7-98ac-be4479e7e34d.png)

**Comment by MarjieAVolk** [comment]
I believe the districts branch addresses this.  Puts units on it.  I think.  I will check

**Comment by MarjieAVolk** [comment]
Fixed in above PR
