### ISSUE TITLE
Unable to properly save(?) world on staging server GUI.

### ISSUE THREAD

**Issue by NDKilla** [StrangeLoopGames/EcoIssues#3426]
Server version EcoServer_v0.6.4.0-alpha-staging-ca25d17a downloaded from website.

I noticed this at the same time as #3245

I asked how to stop the server gracefully and was told to flush things to the disk before clicking file -> save and then just closing the server.

On my GUI the open, save, and save-as buttons under file are all always grayed out and unusable.

I also noticed the terminal stays open after closing the opened GUI.

This might not be a valid bug, but if it isn't, how do I gracefully stop the server?

**Comment by MarjieAVolk** [comment]
Yeah those greyed out ones don't do anything, the options you want are actually under the Storage menu.

@metachronism Can we make this less confusing?  Like could we move the Storage menu options over into File or something?

**Comment by NDKilla** [comment]
@MarjieAVolk for clarification:
- Should i be able to just close the server after flushing to disk?
- Should I force save and flush?
- Should I close the GUI then the terminal or the terminal then the GUI?

**Comment by MarjieAVolk** [comment]
You should do force save and flush to disk, and then you can close the GUI - I think closing either will also close the other.  But FYI some things don't get saved when you do that and are only saved on a timer (fixing this here: https://github.com/StrangeLoopGames/Eco/pull/2232)

**Comment by NDKilla** [comment]
@MarjieAVolk ty for the response. in my experience, closing the GUI doesnt close the terminal, but I haven't tried the other way around. Also i cant see StrangeLoopGames/Eco#2232

**Comment by MarjieAVolk** [comment]
Oh right sorry, I keep forgetting about that!  Anyway, it was a fix for saving that just went in, so it will be available in the beta release

**Comment by metachronism** [comment]
yes, things are saved on a timer, generally 60s.  If you wait at least 60s, generally you'll be fully saved and can close the server at will.

I'll add a save and close option that uses marjies other changes

**Comment by metachronism** [comment]
sean added support for this (typing 'exit' to the console)

**Comment by MarjieAVolk** [comment]
Oh didn't know about this.  Would still be great to have an option in the GUI though.
