### ISSUE TITLE
USER ISSUE: Masonry Table and Carpentry Table Has Tier 0 For Requirements

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3427]
**Version:** 0.6.4.0 alpha staging-ca25d17a

![snap1092](https://user-images.githubusercontent.com/29383891/34994542-ca31f068-facb-11e7-93c4-3272ad36d540.png)
![snap1093](https://user-images.githubusercontent.com/29383891/34994555-d637fa88-facb-11e7-9260-0253e1b3df9d.png)
![snap1091](https://user-images.githubusercontent.com/29383891/34994586-f4bc5b52-facb-11e7-9a0e-272485d7b264.png)
I Understand the use of Tier 0 (raw stone, coal and ore) for the Masonry Table as it is often pla ced underground in dug out rooms, but NOT the Carpentry Table that should be Tier 1 (as you would be on woodworking to use it)

**Tree Debris definitely an error**

Dirt Should also be on this list as it is being shown as part of the room in the description
![snap1099](https://user-images.githubusercontent.com/29383891/34997127-82ce513c-fad3-11e7-8ae9-9a35992cfa60.png)

not entirely sure about the Stone Road and Asphalt Road (both are crafted on a Wainwright table)

**Comment by MarjieAVolk** [comment]
This is intentional, as Tier 1 is a bit harder to get to now, so these first two room required tables are allowed to use Tier 0.
