### ISSUE TITLE
USER ISSUE: Placing Mortared Stone occasionally getting a pause or double placing of block

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3429]
**Version:** 0.6.4.0 alpha staging-ca25d17a

When placing Mortared Stone block getting an odd behaviour sometimes it will take the block off then place it again, i think this is also doing for other blocks (not entirely sure on that yet as i'm only playing with Mortared stone at the moment)

**Comment by Conchipedia** [comment]
i think is the same issue:
 try and place Mortared stone in a single column going as high as you can (easiest with /fly) , about every 10th block nothing happens (this is with devtool or a hammer) but if you look at the blocks and fly backwards you can see the block you just place appear, come back and continue, then you get the same problem happening again, i think the flying backwards lets the chunk you are building in refresh (not 100% sure of what it is called) there (i was trying to build as high as i could so i caould work out the height of a maximum build project, i even flew so high i could see the meteor below me and still keep building upwards).
this is on a 1km world with water at height 40 and highest land is at 42 (wanted a flat area with growth, but if i went 40 and 40 all i got was a World that was nothing but Beach)

**Comment by D3nnis3n** [comment]
This is no longer occuring in the current version. If this issue reappears please open a new issue.
