### ISSUE TITLE
USER ISSUE: Water Plants appearing really quickly when sand removed near water and also a FISH!!

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3431]
**Version:** 0.6.4.0 alpha staging-ca25d17a

![snap1104](https://user-images.githubusercontent.com/29383891/34999872-cbbb4344-fada-11e7-9fcf-3c8b05b91baf.png)
and then placing it back and removing it does make for some interesting ideas as the Fish has stayed
![snap1105](https://user-images.githubusercontent.com/29383891/35000099-628ed7ae-fadb-11e7-9cc6-6c73298c7007.png)

**Comment by Conchipedia** [comment]
This Fish is still here even after logging off and coming back on later

**Comment by craig-jong** [comment]
Poor fish probably can't path anywhere because its all not water.

**Comment by Conchipedia** [comment]
now if only i had a fish tank 😄

**Comment by GophTheGreat** [comment]
Reopen this if it happens again, please.
