### ISSUE TITLE
USER ISSUE: Why Would Unlocking bricklaying and Lumber require Cloth?

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3434]
**Version:** 0.6.4.0 alpha staging-ca25d17a

![snap1116](https://user-images.githubusercontent.com/29383891/35004068-bab16f2c-fae6-11e7-84b5-d4a45ee478a7.png)

I understand the Pitch and the Mortared Stone but i do not understand why we need Cloth, as making brick does not require any cloth to make.
Maybe change this ingredient to Extra Stone and Sand or Even Dirt (something at least based in the area of Masonry, Brickworking and Stoneworking)

**Comment by Conchipedia** [comment]
this seems also a requirement to unlock Lumber

**Comment by MarjieAVolk** [comment]
I am not sure what the reasoning is behind it, but maybe the intention is just to make Tailoring more relevant?  The way it is seems fine to me, cloth is used for a lot of random things you might not think of and is a pretty basic technology.

**Comment by Bob-Clarke** [comment]
Maybe the idea was as the binding?

**Comment by Huntermeign** [comment]
"...as making brick does not require any cloth to make."

If the idea was for binding then wouldn't the cloth have to become a normal part of the recipe? If cloth is something they want more sued, then they need to at least make stations/module that require cloth in the recipe, or an item in the skill that require cloth to make,

**Comment by Bob-Clarke** [comment]
That would make so much sense

**Comment by Senlarus** [comment]
Right now, on the current 7.0 staging build, the only way to advance to Tier 3 materials is by building a room with 32 glass(Because its the only Tier 3 items that doesn't require another Tier 3 item for the bench to work) This seems very restrictive and really holds back smaller servers if no one is going make glass. This should be changed before the steam launch as it is really impacting.

**Comment by MarjieAVolk** [comment]
I am going to make a separate issue for that

**Comment by Senlarus** [comment]
Making the clothing bench not require Tier 3 materials would fix all of these issues and still allow tailoring to be relevant. If you want to keep the progression to higher end backpacks and items that provide benefit like work boots and camo clothing maybe increase the skill point requirements inside of the tailoring skills and put those items at the top level?

**Comment by craig-jong** [comment]
We're trying out weaving non-related materials into research costs. I'm going to close this for now (it's a known thing) and we can revisit it later if it doesn't work out.
