### ISSUE TITLE
Block placement shadow is not transparent enough, cant tell difference when placing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3436]
This is an unplaced block:
![image](https://user-images.githubusercontent.com/3536496/35010663-761b8f74-fab8-11e7-83c2-33e4a28a9c72.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3239
