### ISSUE TITLE
Minimap LODs should be based on vertex count, not zoom level

### ISSUE THREAD

**Issue by stett** [StrangeLoopGames/EcoIssues#344]
Right now it's totally based on zoom level. This results in overly aggressive LODing on small planets

**Comment by metachronism** [comment]
you could do it the unity way and base it on screen-size of the bounding volume and its % variance

**Comment by stett** [comment]
@metachronism Wish I had seen your comment earlier... anyway, it works now based on vertices. Do you think the screen-size measurement would be a better strategy? I think this will be evolving for a while.
