### ISSUE TITLE
Districts change color when another map is in comments of a law

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#3440]
Propose a district law, and go to the view law page.
The district colors are correct until I make a map in the comments.
Then the colors are incorrect on the map, 
The colors are correct on the districts key
https://gyazo.com/31e25b3b164b60ceb3a906f986a43f05

**Comment by SeanAtr0n** [comment]
not seeing this behavior
![image](https://user-images.githubusercontent.com/774628/35016813-2275b6a8-facf-11e7-88c3-b25f8b60a774.png)
