### ISSUE TITLE
USER ISSUE: Cannot remove a chair once it is placed

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3441]
**Version:** 0.6.4.0 alpha staging-9e63c2fa

i wanted to move my chairs as making a New room, nothing i do can do will let remove them
they will not highlight green
![snap1121](https://user-images.githubusercontent.com/29383891/35014150-9231b0ea-fb07-11e7-8d09-9c37dc79cd76.png)
![snap1122](https://user-images.githubusercontent.com/29383891/35014151-92511408-fb07-11e7-848f-dc93b9c57ec1.png)
![snap1123](https://user-images.githubusercontent.com/29383891/35014152-926b433c-fb07-11e7-88d1-b42ca30ab181.png)

this is showing me moving across from one object to another

**Comment by metachronism** [comment]
fixed
