### ISSUE TITLE
[6.4] Cannot pick some furniture items back up

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3443]
Some furniture items once placed cannot be picked back up.  They have no green outline around them when you center on them - and therefore the hammer strikes nothing and the furniture cannot be picked up.

**Comment by MarjieAVolk** [comment]
Do you know which objects these are?

**Comment by MarjieAVolk** [comment]
(sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3380)

**Comment by Conchipedia** [comment]
just checked some furniture, Chair and Table cannot be removed 
also checked small table, round pot, square pot, wooden straw bed and wooden latrine and they are fine

**Comment by metachronism** [comment]
fixed
