### ISSUE TITLE
World markers for players

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3447]

**Comment by johnkslg** [comment]
World market system = feature
World markers on a new object = not a feature

**Comment by elfl0rd** [comment]
@johnkslg hmm... markers added... auto markers added too (campsite).

**Comment by elfl0rd** [comment]
@D3nnis3n this looks as realized.

**Comment by D3nnis3n** [comment]
Seems so, yes.
