### ISSUE TITLE
Tune Single Player Skill Specialization Settings

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3448]
Didnt get time to add 'fast forward', so we'll have to tune single player with skill point gain/specialization alone.

Whatever solution we come up with should allow players to alter settings if their friends join later, so they don't have to restart to support specialization (maybe it does this automatically, maybe it's manual).

**Comment by johnkslg** [comment]
Adding specialization = feature
Tuning that = not a feature

**Comment by MarjieAVolk** [comment]
Adding UI and client side behavior is definitely a feature, and is not tuing

**Comment by johnkslg** [comment]
Setting as high priority, a 'must ship with' feature.
