### ISSUE TITLE
Balance housing

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3451]
Polish the system, make materials affect it.

**Comment by Huntermeign** [comment]
And maybe have a chart that could help us understand how to balance it better? I see the balance multiplier but I have no idea how it could be balanced. 

Also, sometimes items get broken(?) I would log in, and half my skill point gain would be gone from house. I would have to remove a piece and replace it to get the score back. also, sometimes I remove and item and the score increases even though said item initially increased my room score.

**Comment by MarjieAVolk** [comment]
Making materials affect housing is a feature.  And is not balance

**Comment by FoolishCrok** [comment]
If I may
Room detection
if room has % of tier 0 materials used - add 0% (or x%) value of all furniture
if room has % of tier 1 materials used - add 8% (or x%) value of all furniture
if room has % of tier 2 materials used - add 16% (or x%) value of all furniture
if room has % of tier 3 materials used - add 25% (or x%) value of all furniture
if room has % of tier 4 materials used - add 40% (or x%) value of all furniture

**Comment by Nes112** [comment]
In 6.4.2, all furniture items give diminishing returns, regardless of type. For example, 1 bed, 1 chair, and 1 table will give 1, 0.75, and 0.56 points respectively. Can we confirm that this is not intended behavior? Wasn't the intended behavior to have diminishing returns for every additional furniture of the same type, to encourage furniture diversity? I thought this was the case, but just wanted to make sure so it is factored into balancing.

**Comment by johnkslg** [comment]
Balance pass 1 complete!
