### ISSUE TITLE
6.3.1 world crashing over and over when trying to upgrade to 6.4

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3452]
World was fine in 6.3.1 but after upgrading to 6.4 the server is crashing before it even builds the .db files.  Fresh world build fine but owner would like to have his old world continue on 6.4 so they do not have to start over again.  World save files and crash logs are linked

https://www.dropbox.com/s/8u01yj7zuuaqeel/RobertL_Dump.zip?dl=0

https://www.dropbox.com/sh/4nf5tg5bin7ra63/AAC7_9pBYzMgApU3pF86fc89a?dl=0

**Comment by Amphysbaenas** [comment]
Exactly same Dump file with crash for me on Ecotopia.
Can we really upgrade from 0.6.3.1 to 0.6.4 ???

**Comment by metachronism** [comment]
hotfixed

**Comment by pamduncan** [comment]
Hotfix was applied and the same issue exists
