### ISSUE TITLE
6.4 Local (Single Player) still not working after Hotfix

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3456]
Installed the client side hotfix  and tried loading local game again.  The db files and the game saved world were created but the game will not start, just sits there with the spinning wheel on the screen

https://www.dropbox.com/s/it4deaso909qnu0/SimpleWorld_Storage.zip?dl=0

**Comment by MarjieAVolk** [comment]
Yeah :'( We reopened your previous issue: https://github.com/StrangeLoopGames/EcoIssues/issues/3438
