### ISSUE TITLE
Need a control pop-up for hewing logs

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3460]
![image](https://user-images.githubusercontent.com/6262198/35064032-8ff06562-fb7d-11e7-851d-bd3789771378.png)
"Left click to hew"

**Comment by elfl0rd** [comment]
Hm... Looks as removed feature, this is still need? @D3nnis3n

**Comment by D3nnis3n** [comment]
Feature has been removed, Hewn Logs are crafted nowadays.
