### ISSUE TITLE
Cursor hiding inconsistent & annoying

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#3462]
Sometimes the cursor gets hidden in game but not locked to the screen so you can end up moving the mouse outside of the window.

We also shouldn't lock the cursor based on events the player doesn't have direct control over (like loading the world)

**Comment by MarjieAVolk** [comment]
I've noticed the cursor going outside the window also, I always assumed that was editor only, but I never actually tried it I guess
