### ISSUE TITLE
USER ISSUE: Graphics dont update that they are mined and have to disconnect to let them show again

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3469]
**Version:** 0.6.4.0 alpha
stone mined but not showing
![snap1136](https://user-images.githubusercontent.com/29383891/35066768-b3fd5504-fbc9-11e7-9f75-ea93cee63157.png)
have to disconnect for them to update
![snap1137](https://user-images.githubusercontent.com/29383891/35066820-d7ac342a-fbc9-11e7-83f5-4c0462e2b23b.png)
and when i reconnect they and i are on the surface

**Comment by metachronism** [comment]
prediction

**Comment by SeanAtr0n** [comment]
rubble isn't predicted, just the removal of rubble... if you can target through the ghost stone like that then the physics chunk builder succeeded and the visible builder did not for some reason

**Comment by metachronism** [comment]
closing as sean made updates to this system
