### ISSUE TITLE
USER ISSUE: Shop,skillscrolls,Cant sell,

### ISSUE THREAD

**Issue by Zaskersky** [StrangeLoopGames/EcoIssues#3472]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
No steps as selling skill scrolls is no longer a option in the game, resulting in not being able to easy/offline share skillscroll true trade. slowing teamplay and gameprogress.

**Expected behavior:**
Expect to be able to add skillscrolls to the Store,

**Actual behavior:**
Not able to sell skill scrolls in the Store,

**Comment by Conchipedia** [comment]
what our shops can see so far
![snap1148](https://user-images.githubusercontent.com/29383891/35073829-bb9e1596-fbe2-11e7-9a63-fec7cb88b768.png)

we can sell the books (which we would never sell) but no scrolls as mentioned above

**Comment by MarjieAVolk** [comment]
Thanks, was going to check that
