### ISSUE TITLE
USER ISSUE: pipes in water gives a slight glitch

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3474]
**Version:** 0.6.4.0 alpha

this is right against pipe
![snap1141](https://user-images.githubusercontent.com/29383891/35072226-9c5d91f4-fbdb-11e7-900a-ed5a95c0e329.png)
and this is slightly away from pipe
![snap1145](https://user-images.githubusercontent.com/29383891/35072264-c81c74e0-fbdb-11e7-82b8-8806a804f017.png)
but depending where you are in the water its not always visible
![snap1143](https://user-images.githubusercontent.com/29383891/35072287-dcece3a0-fbdb-11e7-9a94-ef31413a9093.png)

**Comment by metachronism** [comment]
reprioritizing.  would take quite a bit of a refactor to support this case

**Comment by metachronism** [comment]
setting as wont-fix for now (its mostly working as intended, would need a special case to fix this one instance and probably not worth it), might come back in a later polish pass
