### ISSUE TITLE
devtool can't select dirt

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#3475]
![image](https://user-images.githubusercontent.com/31536813/35072337-70b6e4de-fbe4-11e7-97fe-073c47a72a93.png)

**Comment by Conchipedia** [comment]
nothing ever can be selected when carrying dirt
![snap1146](https://user-images.githubusercontent.com/29383891/35073651-ddbe7176-fbe1-11e7-9596-88bf5e21133b.png)

**Comment by SeanAtr0n** [comment]
fixed 7.2
