### ISSUE TITLE
New law with the same name as an old deleted law is blocked

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#3476]
Make a law, delete it by the proposer or admin
Then try to make a new law with the same name, get error 'law with that title already exists'

Not sure if this is intended.
But seems annoying if you have a good name and its taken by a law not in use.

This may also happen with failed to pass laws? 

Also, can we add capitalization and period to all error messages?

**Comment by MarjieAVolk** [comment]
Hm, yeah failed and deleted laws are still saved on the server for things like the teacher dashboard.  Mostly that.  In which case two laws with the same name is still bad, even if one is not active anymore
