### ISSUE TITLE
USER ISSUE: text glitch on tooltip on Steel

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3481]
**Version:** 0.6.4.0 alpha

![snap1194](https://user-images.githubusercontent.com/29383891/35078518-8262b1b6-fbfa-11e7-941c-8592bbfabc47.png)
![snap1195](https://user-images.githubusercontent.com/29383891/35078832-195c8b36-fbfc-11e7-90f6-8febdada721e.png)

**Comment by Conchipedia** [comment]
Molecular Gastronomy and Laboratory Tool tips show weird stuff 6.3.1 #3251
but this time Steel

**Comment by MarjieAVolk** [comment]
Oh I just saw your link, yeah this is the same bug as that: "UI_Circle" sprite is misconfigured
