### ISSUE TITLE
USER ISSUE: Brightness issues

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3482]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
the sun saturation of bright nice destroys most of all color in game specially in the early AM, also it makes night time way way to bright which makes the player created light sources point less.

Global Illumination use to make it so game was dark at night and day time during day time making use of player lighting worth while.

**Expected behavior:**
game should be darker, or at least give admins control over the world darkness and brightness settings so that we can control this. a 50% brightness lower brightness value would probably help.  its like someone took gamma setting on my monitor and just cranked it all way up.

**Actual behavior:**
no control over this setting sucks. - game just feels like art and color is washed out with bleach even with viberance on it just makes it worse - it seems that the Global Illumination setting is just broken now.

**Comment by MarjieAVolk** [comment]
Wow @metachronism gets his way :P

**Comment by metachronism** [comment]
@MarjieAVolk is right.  This is my new favorite bug!

**Comment by metachronism** [comment]
brightness setting was added earlier, this is fixed
