### ISSUE TITLE
USER ISSUE: Disconnect after joining a server, which was updated from previous version.

### ISSUE THREAD

**Issue by Andrey-Anatolyevich** [StrangeLoopGames/EcoIssues#3484]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
1) Join the server at version EcoPC_v0.6.3.1-alpha
2) Play for few weeks at the server
3) Update the server to version 0.6.4.0 alpha
4) Join the server using client version 0.6.4.0 alpha
5) Let the game load the world for ~ 5-10 seconds

**Expected behavior:**
Expected to have no crashes on joining the server and being able to play the game.

**Actual behavior:**
1) Receive after 5-10 seconds after joining the server game crashes with the following message: "Caught exception: Exception has being thrown by the target of an invocation."
2) Frustration from the fact, that progress is lost due to a bug.

Please, fix the first point so that second will be solved as well. =)

NOTE: If I join new server, game doesn't crash.

**Comment by MarjieAVolk** [comment]
Was there any more to the error message that you saw when you were disconnected?  I assume you were disconnected from the server, and not that the server went down?

**Comment by Andrey-Anatolyevich** [comment]
I haven't seen any additional messages or details.

Yes, I was disconnected and was able to reconnect to the same server (with the same result though).

From what I was able to observe over those seconds before disconnect, I assume, world was loading around the player position. And at some area some items in the world may have caused the crash. Maybe some block or object was placed somewhere at a place, where some event or handler was fired and then exception was thrown resulting in disconnect from the server.

I wish I was able to collect some additional data, but I do not own the server and have no access to it.
* If you'd add some console parameter or some other way to collect or log extra data on crashes or disconnects, it will help you to save a lot of time.

**Comment by HunterAshh** [comment]
Getting the same error when I tried joining a friend's server that just updated to 6.4. I load in and within 5 seconds i get booted. Here is what the console says to him.
![screenshot_185](https://user-images.githubusercontent.com/28711491/35120082-94f22f20-fc5c-11e7-8fb6-4cc153026eb0.png)

**Comment by metachronism** [comment]
need the error .dmps (look in dump folder)
