### ISSUE TITLE
[6.4] Support issue with "Continue showing SP game.

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3486]
This has come up quite a few times in chat support.  Please loves the idea that they had a 'continue' button like they had asked for that would link them to the last server they played on so they did not lose a server.  However they then found out that if they played a single player game it was what got logged into "Continue" and the server they had been playing on was no longer remembered.

Many point out that they are never going to 'lose' there SP game and so there is no real purpose for continue to retain the link to there SP game.  They can find that very easily by clicking :Load"  BUT they would like to be able to still have the last server they played on so when they are ready to go back online that server is remembered.

"_Why are they saving the solo game to the continue link in the menu when it is saved to the load area already? I was playing on a server and it was great that every time I came back it was there under the continue button.  Then I decided to take a break and play the solo game to see what it was like and so I tried it out for a few minutes.  Then I went to log back into the server I had been on and OH NO!  The continue link now linked to my solo game and not the server I had been on!  Another server game lost!  Does it make sense to need to remember to continue a solo game that you have saved on your local computer, one you named so you most likely to remember it and is logged in your load list?  Doesn't it really make more sense to leave the last server logged into as the persistent continue link? Do you think they could change this_?"

**Comment by metachronism** [comment]
this is working as intended.  continue is always going to show you the last place/world you were on, be that singleplayer or otherwise
