### ISSUE TITLE
Custom Controls Issue with vehicles

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3487]
This taken from a Facebook group.

"I'm having a but of an issue with the custom controls. I'm left-handed so I remap my movement keys, but the vehicle movement isn't linked to the same key binds. They're locked to default binds. Are there plans to give them separate bindable options... or at the very least link them to the character movement binds?"

**Comment by Nanders** [comment]
Fixed in SVN
I just made sure they were mapped to the player movement bindings.

When we have more complicated vehicle behavior / more vehicles we'll probably add vehicle-specific key bindings
