### ISSUE TITLE
Huckleberries do not highlight

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#349]

**Comment by noblackthunder** [comment]
you sure ? had same issue .. but resoveld it self after i got a tool in my hand normaly .. it seems from before that if you did not at first had a valid item in your hand highlight would not work =). just an idea

**Comment by craig-jong** [comment]
Yes, likely has to do with the new cursor.

**Comment by noblackthunder** [comment]
feedback from a4 eu server: people need to take items in hand to be able to use thinks like doors and other stuff after a relog ( same cursor issue)
