### ISSUE TITLE
First time entering a world Avatar window to Large hides the tutorial press Tab to get pointer

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3490]
**Version:** 0.6.4.0 alpha
![snap1202 edited](https://user-images.githubusercontent.com/29383891/35113494-80d40a8c-fc79-11e7-987b-f89229379640.png)

unless you know that tab brings up the pointer this can be confusing for a new player, maybe make the avatar window smaller or don't open this first just add this to Next tutorial after Movement keys
examples:
Tutorial 1: Movement ( W A S D and space)
Tutorial 2: Create Avatar (Press Tab to bring up game pointer and then an arrow saying click on Avatar Icon)

**Comment by MarjieAVolk** [comment]
Yeah this is a problem O.o However, we have just created a new avatar edit experience thing, which solves these problems and also looks a lot nicer.  It will be available in the next full release.  So I think we are not going to solve this for 6.4
