### ISSUE TITLE
Price for an invitation changes

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3492]
![](https://cdn.discordapp.com/attachments/258375026435162112/403620240451174402/unknown.png)
![](https://cdn.discordapp.com/attachments/258375026435162112/403620345933987844/unknown.png)

**Comment by knexer** [comment]
So, none of the prices are wrong here, these are two different offers.  Upgrade your account to a two-pack (which costs $70) or buy extra keys (for $35 each) are two unrelated transactions.  I guess it is confusing sometimes though.

**Comment by Nanders** [comment]
Yeah, If this is intended, it might go a long way to just clarify.

**Comment by MarjieAVolk** [comment]
Oh okay, I misunderstood
