### ISSUE TITLE
[6.4] Console is not opening until server comes online

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3493]
John asked me to post this as apparently it is not the behavior wanted:

The Console does not open up on desktop until after the world generation/server load is compete and the port opens to make game available. Once the game is online the console will also load but it sort of removed a major tool for system admins to know what the server is doing/what state it is in other then just by watching CPU behavior in the task manager, especially at this time when we are having many different issues trying to get the servers to load.

**Comment by metachronism** [comment]
the console should open immediately, its really odd that you arent seeing this behavior?

**Comment by metachronism** [comment]
![image](https://user-images.githubusercontent.com/3150561/35134908-731add84-fc8e-11e7-9aa9-8a345f2191e3.png)

**Comment by johnkslg** [comment]
Made this happen in single player if you pass 'showserver' to the client (I think this is what they wanted)
