### ISSUE TITLE
USER ISSUE: Log House issue

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3494]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
you need hwen logs that are made in the carpentry table but to make a house, but you cant use the carpnety trable unless you already have a house ? so how you make a log house ?

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Adding @craig-jong to see the confusion :P

So first, you can make hewn logs without a carpentry table.  There is a special way to do it right now, basically you put a regular log in the world and then hit it with an axe, it will be picked up as a hewn log.

Second, you don't need hewn logs to get the carpentry table working.  It only requires tier 0 which can be dirt or stone.

**Comment by Arend90** [comment]
few days ago the hewn logs where in the workbench now they are in the carpentry table that needs 18 level 0  
![image](https://user-images.githubusercontent.com/31536813/35118307-a952488a-fc91-11e7-9ca4-5b61f894f734.png) but all these are not building blocks

**Comment by MarjieAVolk** [comment]
Uh I thought Dirt was in tier 0 O.o  Well you can make it out of stone by digging into stone >> O.o

**Comment by midn8t** [comment]
yah i have no idea about any of it, i know what tire 0 items are it says on table what u can build house out of so it says stone and i thought just plain logs, in game it says put down ur stone or tire 0 item and then hit it with hammer not axe. so i put down bunch of logs where i want them and i hit them with hammer nothing. i place bunch of stones stack them up to make a house hit them with hammer nothing.

carpentry table has to be put in a room, and sense you can no longer seem to build room by just place items down or using the hammer as it says in game it becomes really frustrating honestly. most of people own our server have already quit cuz majority of us couldnt figure it out.

**Comment by MarjieAVolk** [comment]
Ah, yeah you don't hit it with a hammer, you have to place it using the hammer.  But also that tooltip is not 100% accurate either lol >>  So for some blocks, you need to use the hammer to select a 'construction' to place them as - that is using the hammer you can place for example a hewn log as either a wall, window, stairs, or roof.  This is not true for all the blocks however.  Most of the tier 0 ones you just have to place them.  For blocks that stack into piles, like stone, you have to fill up the pile in order for the block to count as a wall.  So in this case you would have to place 4 stone into one block to have that block count as a wall.

We are still playing with this stuff so it's a bit confusing right now.  I think we are going to remove hewing the logs by hitting them with the axe, and go back to only crafting them regularly.  If you guys have any suggestions about how to either make the tooltips / tutorials more clear, or how to make the gameplay more intuitive, please let us know.

I'm thinking in the tooltip we may want to separate the different blocks into their different placement types and have a different little instruction text for each.  Eg. for this one you might see the following:

To create a Tier 0 wall:
Create any of the following blocks using a Road Tool:
Asphault Road
Stone Road

Stack any of the following blocks into full stacks:
Stone
Copper ore
Coal
Gold ore

Use a Hammer to place Constructions of the following blocks:
Log

**Comment by midn8t** [comment]
I am not sure what place it with hammer means ??

so i have stack of 20 stone or logs for example i can only place it by right clicking not left clicking and left clicking uses the hammer right click does not use hammer cuz i can place them with or with out hammer on me.

so how do u place it with a hammer ?

**Comment by MarjieAVolk** [comment]
Yeah, so while you are holding hewn logs, also select your hammer.  You should see another icon appear near your Carry slot.  If you hold down shift and use the mouse scroll wheel, then you can select which 'construction' you want.  Now you can place the hewn logs with right click, and they will appear as the construction you selected.

That is how you place things 'with' the hammer.  As for the stone, you are right to just stack it like that.  Since stone is just a raw resource, it can't be placed into forms.  Once you make Mortared Stone you will be able to place it with the hammer, like Hewn Logs.

**Comment by craig-jong** [comment]
The hewn log recipe has been moved to the workbench.

There is a faster version available on the carpentry table.
