### ISSUE TITLE
Tree Debris is Tier 0

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3495]
Should not be tier anything

**Comment by Conchipedia** [comment]
i did show this in my github
USER ISSUE: Masonry Table and Carpentry Table Has Tier 0 For Requirements #3427

**Comment by MarjieAVolk** [comment]
Ah yeah, I guess that part got misplaced, sorry about that.  It is better to create more separate bugs for things that are going to be separate tasks for us, but I usually try to take care of that, this time I forgot it.

**Comment by Conchipedia** [comment]
seeing it only from game side it's not always easy to seperate stuff into other bugs, it all seems related
