### ISSUE TITLE
Block cursor is wrong when using Hammer + partial stack

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3497]
I'm holding a hewn log and a hammer, and looking at a stacked hewn log.  The block cursor for the hewn log form overlaps the stacked hewn log, looking as if I could place it in that shape, but if I right click it places it into the partial stack.
![image](https://user-images.githubusercontent.com/23460210/35122792-d09e9d2c-fc54-11e7-9e7c-fc4950172f9a.png)

**Comment by SeanAtr0n** [comment]
this seems to be fixed
