### ISSUE TITLE
[Client Bug] Scaling issue in full screen mode

### ISSUE THREAD

**Issue by Metaphis** [StrangeLoopGames/EcoIssues#35]
Under Windows 10, screen resolution is 2560x1440, game setting set to 1280x720 (non-windowed).
Display scalling is set to 200%. See pictures below

![scalling_issues](https://cloud.githubusercontent.com/assets/16102946/11901631/7168bf46-a561-11e5-8c75-44a30f980b2c.png)

![scalling](https://cloud.githubusercontent.com/assets/16102946/11901659/9f0600a8-a561-11e5-94fc-113b062fa31d.PNG)

**Comment by klimSLG** [comment]
it's fine on current master branch, will check for next release version
