### ISSUE TITLE
6.4 new world forms holes

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3507]
unknown reason why or how, but this guys house just disappeared and we have a hole in the ground now. restarts will not fix nor roll backs.
![hole](https://user-images.githubusercontent.com/20627148/35126846-7c983734-fc6c-11e7-9803-9e06fcfdfa68.png)

**Comment by MarjieAVolk** [comment]
Did the house have hewn logs in it?  Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3453 (just gonna close this as a duplicate unless I hear otherwise)
