### ISSUE TITLE
Why can't Road Tool still be called Road Tamper?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3508]
'Road Tool' sounds less cool and less finished to me

**Comment by Nanders** [comment]
Used to be called this, but was changed - iirc - due to worry that people wouldn't know what a tamper was.

I think it should be called Road Tamper

**Comment by MarjieAVolk** [comment]
I think so too.  IMO even if you don't know the word Tamper, you can guess pretty well because of the word Road.  And you will learn some vocabulary, very educational :P

**Comment by metachronism** [comment]
the correct term is just "Tamp"

**Comment by MarjieAVolk** [comment]
oh you seem to be right.  Look how educational this is!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#318
