### ISSUE TITLE
Excavator/Powered Cart Suggestions

### ISSUE THREAD

**Issue by FoolishCrok** [StrangeLoopGames/EcoIssues#3509]
(6.3.1 thoughts) 
It's a PAIN, it takes so much time to learn how to control it and in addition You need to create roads of 8 wide to actually make use of it, just like Powered Cart.
(http://ecoforum.strangeloopgames.com/topic/3095/few-thoughts-about-excavator)

a) Increase vehicle (excavator, powered cart) maneuverability by 20% or more
b) add hand brake to excavator as it rolls down of the ramp (tested on asphalt)
c) add horsepower to excavator to climb properly, do not get stuck by 1x1x1 hole

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#317
