### ISSUE TITLE
[6.4.1][Suggestion] "Starting with Tools"  needs to be a configurable option

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3512]
Please make "starting with tools" on a server a configurable option so Server Admins can choose whether they want to have a world that facilitates lone wolf game play or a server that builds  community.  Give tools if "noCollboration" is configured, but keep tools as they were - ones you got when you got skills, for low, medium and high Collaboration settings. Many were very happy to see this in 6.4 as they have been working hard to build communities and this really played into that whole aspect.  I know you heard from many players that prefer to play alone and don like the community or social interaction of the game and don't want to cooperate in a community but for some reason don't want to play a Solo game.  I guess they like to see other people walking around?  Many admins have worked hard to get laws going to build communities etc and now 6.4.1 just hands new players coming on tehir server all the help they need to go do their own thing and not try contacting the community and working with them.  It would be very helpful if this could be turned off for those servers that want to build communities and when the game gives the player the mechanics to not play cooperatively it makes it hard for the admin to facilitate a community.  I don't think it would hurt to have this configurable.  If an admin does not care one way or the other the option is there.  If they really want new players to use the community to make progress they can choose to toggle the tools off.  And this does not hurt the player - if they want a lone wolf experience and want to do their own thing they can play solo or find a server with "No Collaboration" set - otherwise they know that they are joining a server that supports community development.

**Comment by MarjieAVolk** [comment]
Apparently you can edit this in the PlayerDefaults file, but it would be nice if there were a more user friendly way to do it

**Comment by Conchipedia** [comment]
i don't see how one shovel and one free axe can encourage lonewolfing, as soon as u have unlocked a workbench u have access to making an infinite number of these tools (instant lonewolfing) , all you need is raw materials as ingredients, and if someone is selling tools (basic and higher grade) then they are encouraging players to lonewolf as well.
 The High Points needed to learn other professions and Specialities is the thing that Stops the lonewolfing and forces people to work together

**Comment by MarjieAVolk** [comment]
I also suspect that giving tools is not going to allow people to run off alone forever - just for a little while while they are getting started, which is okay.

Will be good to see how the balance of specialty skills works out.  Possibly the price curve is too steep.

**Comment by Conchipedia** [comment]
was looking at Server 50% when unlearning (that's fair) and 60% increase to next skill that's horrendous when you start getting past double figures

**Comment by pamduncan** [comment]
Well, the thing is, I am sure many don't see a shovel and an axe promoting 'lonewolfing' but if that is the feeling that server owners have that this is the case and that people joining their server are going off on their own instead of contacting the community then I think its only fair to listen to their concerns too and maybe address them.  Obviously players who did not like a slower start of having to wait for sps to get it themselves or relying on the community to help them were heard and their needs addressed but there are now those on the other side of the issues that really think the initial decision to start with noting was a much better way to go.  Neither side has to like how the other views it but I don't see why it can't be easily configurable for an admin to make their own choice.  Its not like its not already something you can to - they are just asking for it to be an easy setting for them to make so they do not have to edit a .cs file if not good at doing s and so it can be an option they can set and not have to edit again with every update.  On anything that is a configurable option i don't think anyone should be saying that it should not be configured one way or the other - if a game lets it be changed then its just a matter of choice and no one should be saying that one setting or the other is right or wrong.  The fact that they feel that it supports lonewolfing (which is what they were saying - not encouraging)  maybe right or it maybe wrong - but that does not matter. That they feel this way does matter and that they are simply asking for an easy way for them to have it as they would prefer seems to me to be much more constructive then arguing whether players should have starter equipment or should not.  And the argument that it is not fair to players, is again up to the individual player to decide - if they don't like not having starter equipment then they will just go elsewhere, if they don't have a problem with it they will stay and play.  This is one of those arbitrary settings that no one needs to argue it in defense of 'all players'.   It seems to me that it makes more sense and would take less time to just make it a toggle of off/on and let the admin have it the way they wish to then having a  running argument in chat and forums over who is right and who is wrong about lonewolfing and beginner tools

**Comment by johnkslg** [comment]
The player starts with all the basic tools in their backpack now.
