### ISSUE TITLE
6.4.1 New Server Failing to Load possibly crashing ??

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3513]
This is a 6.4.2 fresh install attempting to generate a new world default settings.  It seems to get as far as creating the db files but no idea what it does after that as the server uI no longer loads until world is generates so we have no insight as to what the server is doing.  It appears that its crashing and restarting but no files are being created and that is simply a guess from monitoring windows even logs.  This is the same issue this server had in 6.4

Faulting application name: EcoServer.exe, version: 1.0.0.0, time stamp: 0x5a601e19
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x3348
Faulting application start time: 0x01d3908e3eb2e59c
Faulting application path: D:\TCAFiles\Users\PamelaD\2613\EcoServer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 80baadb8-fc81-11e7-80e1-002590a3d803
Faulting package full name: 
Faulting package-relative application ID:

**Comment by metachronism** [comment]
no repro
