### ISSUE TITLE
[6.4.1] Cant connect to new server with 200x200 dimensions

### ISSUE THREAD

**Issue by darkmyregaming** [StrangeLoopGames/EcoIssues#3514]
Tried to setup a clean install 6.4.1 server with dimensions set to 200x200. Server loads successfully and appears to be running (web panel can be accessed no issues). Server is running on a dedicated machine in a datacenter.

Trying to connect to the server after it was up and running, my client (also clean install 6.4.1) was constantly booted for 'inactivity': https://gyazo.com/dba96d7fd28b04f26bf87b59a4738b29

Dropping the dimensions down I was able to connect without issue. Yesterday I was able to connect to a 6.4.0 world at 200x200 with same client/server combo without any issue. I've been able to successfully connect on 6.4.1 by dropping the world size down to 174x174

**Comment by metachronism** [comment]
verified as working in 7.0.0
