### ISSUE TITLE
Are not all these Skills to Unlock already available FREE with a Hammer?

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3515]
**Version:** 0.6.4.1 alpha
![snap1205](https://user-images.githubusercontent.com/29383891/35160016-e5b46310-fd33-11e7-9737-ed0c0d8d9588.png)
![snap1207](https://user-images.githubusercontent.com/29383891/35160017-e5d1ccfc-fd33-11e7-9328-fd5a2c457f58.png)
![snap1208](https://user-images.githubusercontent.com/29383891/35160018-e5f1159e-fd33-11e7-8bfa-89cc9689b807.png)
![snap1209](https://user-images.githubusercontent.com/29383891/35160019-e6101034-fd33-11e7-8d30-41a533f0b80f.png)
![snap1210](https://user-images.githubusercontent.com/29383891/35160020-e62a4562-fd33-11e7-8bcb-bc520f3ac07a.png)
![snap1211](https://user-images.githubusercontent.com/29383891/35160021-e647e1c6-fd33-11e7-90a4-6a621fa42d4b.png)
![snap1212](https://user-images.githubusercontent.com/29383891/35160022-e699c0c2-fd33-11e7-8865-fcfe5c978e23.png)
I have already learned the Skills to make the Blocks
![snap1214](https://user-images.githubusercontent.com/29383891/35160230-7a32dbca-fd34-11e7-9780-f8a381371690.png)
but by looking at what these are supposed to do i will have to learn this to make different items with the hammer
![snap1213](https://user-images.githubusercontent.com/29383891/35160293-a3bc9b0c-fd34-11e7-8935-85f5809fd709.png)

and if you are going to remove the FREE building block choice from Hammer charging someone 600 Sp to allow them to make the extra stuff  (Stairs,roof etc) it will KILL creativity in Eco.
![snap1215](https://user-images.githubusercontent.com/29383891/35160495-31cacbc6-fd35-11e7-9f0b-70ac7c6dcd1f.png)

If I have read what these skills are for wrong then please tell me what they are @craig-jong , as a chat in Discord has still left me confused

**Comment by MarjieAVolk** [comment]
Honestly I am not sure what these do either.  There are definitely going to be different constructions (what you place with the hammer) that are unlocked with later skills.  Although I imagine stairs would be one of the basic ones.  And I'm not sure if these skills are what unlocks those or not.  We need some tooltips for that stuff

**Comment by MarjieAVolk** [comment]
It looks like the efficiency skills are actually what unlock the constructions, generally

**Comment by Conchipedia** [comment]
if they charge people sp to unlock constructions made hammer that will annoy the people used to hammer giving it all to start with.
i liked the old method with unlocking recipes to make other types of building blocks but only drawback was having to store it all

**Comment by MarjieAVolk** [comment]
If you liked the old way, I don't see why you would have a problem with this?  It's basically the same thing.  Except that you don't have to store the different types of blocks :P

**Comment by Conchipedia** [comment]
i would like to have that as a part skill somehow and not so expensive to do

**Comment by Conchipedia** [comment]
but, i dont see how it can work, if i unlock the skill to make better blocks how do i give them to others?

**Comment by MarjieAVolk** [comment]
Ah that is true, you can't sell the forms.  You would have to go place them for someone else.  Hmmmm

**Comment by Conchipedia** [comment]
i like the other new blocks but how would they be picked up if you don't have the skill they would turn back to plain blocks

**Comment by Conchipedia** [comment]
its all to do with Creativity, and @johnkslg  didn't want that to stop

**Comment by johnkslg** [comment]
I suppose theyre not mutually exclusive.  Could have placeable roof items, in addition to hammer + log = roof

**Comment by johnkslg** [comment]
It can get annoying managing all the materials is the issue

**Comment by johnkslg** [comment]
Letting players make cooler buildings with more skills seems fair to me, you dont like that?

**Comment by Conchipedia** [comment]
i want players to make extremely cool buildings and designs (remember i did pixel art)  but not charge then 1000+ sp to do this

**Comment by craig-jong** [comment]
While I do think this conversation has merit, a github issue isn't really a good place for design discussion.

I think there is merit to selling forms, however it isn't something that going to happen in the immediate future.
