### ISSUE TITLE
Unable to Start Eco 6.4.1, but still can run Eco 6.3.1

### ISSUE THREAD

**Issue by KingKorihor** [StrangeLoopGames/EcoIssues#3516]
This is an effort to reopen Issue #3461 
https://github.com/StrangeLoopGames/EcoIssues/issues/3461

Like 6.4.0 I simply get get past starting the program after the Unity engine loads even though the earlier version of Eco works just fine on my computer.  The crash dump files are below:

[crash.dmp.log](https://github.com/StrangeLoopGames/EcoIssues/files/1647333/crash.dmp.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1647334/error.log)

I had to rename the crash dump file because GitHub doesn't recognize a "dmp" file.  I hope it transferred properly.  If there are other files from my installation of Eco that could be sent and useful to help resolve this issue, please respond here but there were no other files in the crash folder for me to send than these.

**Comment by KingKorihor** [comment]
After talking to Pam about this issue, she suggested I look in the Windows Event Viewer and examine the log files for Windows itself.  After clearing out the logs for Windows itself, I ended up getting a kernel error and the following files were generated by Windows:


[Report.wer.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1647803/Report.wer.txt)
[WD-20180119-1256.dmp.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1647804/WD-20180119-1256.dmp.txt)
[WER-176470031-0.sysdata.xml.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1647819/WER-176470031-0.sysdata.xml.txt)
[WERB947.tmp.WERInternalMetadata.xml.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1647820/WERB947.tmp.WERInternalMetadata.xml.txt)

I do think that this is related to the issues I'm seeing here and gives a bit more information about the system I'm using that might help you in tracking this down.  Probably more information than you need, but I'm including it in this bug report.

**Comment by KingKorihor** [comment]
Whatever changes seem to have happened with the 7.0.5 version seem to have fixed this issue.  I'm now actually able to use the current version of the client.

As far as I'm concerned, you can close this bug report as successfully fixed.  If I have problems in an upcoming version I'll open up another bug report.

**Comment by MarjieAVolk** [comment]
Glad to hear it - Sorry that you went so long without being able to play!
