### ISSUE TITLE
Basic Crafting gives Workbench and Stone hammer, already have them free from Starting New game or Server

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3517]
![snap1219](https://user-images.githubusercontent.com/29383891/35164743-8893097e-fd43-11e7-83fe-394b5e12562f.png)
no need to give items a second time.

Great Idea for Giving FREE items as start of game (no way to NOT to be able to do anything) 👍

**Comment by MarjieAVolk** [comment]
The giving of the items was like a special kind of config only hotfix I guess, so this couldn't be changed along with it.  Will definitely be cleaned up in the next release

**Comment by Conchipedia** [comment]
its a good idea to give the FREE tools as there is no possible way to learn a wrong skill that gave you something, and never be able to unlearn it again, so should stop people making that basic mistake, PLEASE keep this in.
