### ISSUE TITLE
More Skill books and scrolls in game than there are recipes for them

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3519]
just did a Store in Marmot and added ALL skill Scrolls to it, to give me an idea of which ones we were missing and it gives "out of Stock" next to ones we don't have, but looking through them to see why i haven't got them loads are professions and have no recipe.

tried searching for duplicate couldn't find

**Comment by MarjieAVolk** [comment]
Here it is :)  https://github.com/StrangeLoopGames/EcoIssues/issues/3479
