### ISSUE TITLE
USER ISSUE: Shelves seems to be missing from game now

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3521]
**Version:** 0.6.4.1 alpha

cannot find it anywhere, tried typing name in chat, even search store and not even on /give command
has it been removed?
New Carpentry Table Recipes
![snap1221](https://user-images.githubusercontent.com/29383891/35169522-bab4abd6-fd54-11e7-98d4-bcff0cc9aa2a.png)
Old  Recipe
![snap1222](https://user-images.githubusercontent.com/29383891/35169706-72ccb7e0-fd55-11e7-9633-13821ec2f044.png)

**Comment by MarjieAVolk** [comment]
I presume they were removed, yes
