### ISSUE TITLE
[Client] Chat message inputs trigger other hotkeys

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#3522]
Version 0.6.4.1

If you type a message to chat quickly enough and send it with Enter, the most recent letters that were typed could trigger another one of the UI hotkeys.

For example, typing a sentence that ends in "M" and hitting enter immediately after will open the world map. The time window for this occur is likely less than half a second, though I haven't tested it too precisely.

It seems the time window necessary to reproduce this bug was reduced in 6.4. But this bug is still quite common for those of us who are chatty and speedy typists.

**Comment by MarjieAVolk** [comment]
Yeah we have known about this for some time.  It annoys me too.  Think no one has looked into it because we are assuming it's a problem in the third party text box software we are using.

**Comment by KitRedgrave** [comment]
This has apparently gotten worse on Linux, at least for 7.0.4. I literally cannot type in any text boxes even intentionally typing slowly without hotkey events firing and stealing focus away.

**Comment by huin** [comment]
I've been playing mostly on Windows with versions 7.2 and 7.3+, and have not encountered this issue until I tried running 7.3.3 under Linux (on the same hardware), and then encountered this problem.

**Comment by SlayksWood** [comment]
#10182
> Often when i chat and type in the hotkeys they open up. Especially when typing extremely fast, e.g. pressing chat button and starting to type immediatley when the chat not even has opened yet - but it still registered it was typed in.

**Comment by beastyn** [comment]
Hotkeys are not working now.

**Comment by beastyn** [comment]
hotkeys don't work witj gibberish. Will create separate issue
