### ISSUE TITLE
[Client] Room not detected after server restart

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#3523]
Version 0.6.4.1

This is a common bug I have seen playing across different servers.

**Expected behavior:** An enclosed room should still be considered an enclosed room after server restart.

**Actual behavior:** After restart, some rooms are no longer considered rooms, disabling crafting stations. Removing and re-placing any block in the room resolves the issue.

This does not happen for _all_ rooms after _every_ restart. However, in my experience it does happen for _some_ rooms after _every_ restart. Further testing is needed to determine what attributes cause a room to exhibit this behavior.

**Comment by KingKorihor** [comment]
A common source (although not exclusive) of this kind of behavior is from rooms with double doors.  In other words, two doors side by side to provide a larger opening for something like a cart.

It can also frequently happen in rooms with multiple kinds of materials (logs and lumber, to give an example).

Another potential source of problems is a tree which grows and has branches which extend into the room space from outside.

**Comment by Nes112** [comment]
Yes, as Korihor said, this bug is 100% reproducible when rooms have double doors. These rooms always fail on restart. Replacing one of the doors solves the issue. However, I've had the issue in rooms without double doors as well. Perhaps the double door issue should be treated separately since we know the underlying cause of that one.

**Comment by metachronism** [comment]
fixed
