### ISSUE TITLE
[Suggestion] Hitting a Small Tree with Axe don't make it just disappear

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3525]
**Version:** 0.6.4.1 alpha
when a player hits a small tree, don't make it just disappear give us at least 1 Debris so it looks like we allowed to do this

**Comment by MarjieAVolk** [comment]
+1 think others have commented on this too.  Or maybe it was you earlier, can't remember lol

**Comment by Conchipedia** [comment]
was me, but now you know it is ❤️

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#315
