### ISSUE TITLE
Meteor completion (succeed, fail) needs sound effects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3530]

**Comment by SeanAtr0n** [comment]
Might be useful reference for picking audio
https://drive.google.com/file/d/1c5-Ufe6MvPov2Vi-v-vfOd0SPkbQ9i_8/view?usp=sharing (requires slg account to view)

**Comment by beastyn** [comment]
Faile: Didn't hear anything special, just sound of meteor fall
Success: the same, only sound of destruction

**Comment by beastyn** [comment]
Sound is still the same :*(

**Comment by freakydna** [comment]
@Quadbro Fixed with https://github.com/StrangeLoopGames/Eco/pull/9420 & svn develop #8880.
