### ISSUE TITLE
Law creation error text is awkward

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3533]
![image](https://user-images.githubusercontent.com/6262198/35175484-b860224c-fd28-11e7-94e7-d5996ebea6ce.png)

"Play (hours) actions [...]"

Id suggest "Play actions (hours)"

**Comment by MarjieAVolk** [comment]
yaaaaaa it's just kind of haaaaard

**Comment by MarjieAVolk** [comment]
maybe I should add an option to all actions, whether or not to show their units... so that the parent can add that part of the string in.....

**Comment by MarjieAVolk** [comment]
(because this whole string is dynamically generated you see)

**Comment by MarjieAVolk** [comment]
I feel like all of the action query text is awkward too, and don't know how to make it better (that is, 'where' and friends)

**Comment by Nanders** [comment]
Yeah I was going to comment on that, Its really hard to understand, especially with longer laws. 

Probably requires lots of love.

**Comment by MarjieAVolk** [comment]
It's a difficult problem, like it's basically a programming language trying to sound like spoken English.  Maybe should do some research to see if this has been done more successfully elsewhere.
