### ISSUE TITLE
Harvested corn stayed visible until relog

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3534]
I harvest a bunch of corn, most of it worked fine.  But two in a row, when I harvested them I got the items but the corn stayed visible.  It was no longer targetable.  Relogging made it go away.

**Comment by SeanAtr0n** [comment]
Any error msgs in your log file? Not much to go on here as harvesting isn't a predicted action... was most likely a builder issue?

**Comment by MarjieAVolk** [comment]
Eh yeah I'm playing on steam, so not actually sure where that file is.  Don't see anything obvious either in the installation folder or in AppData...

**Comment by MarjieAVolk** [comment]
Well I looked through this and didn't see anything that looked super relevant, but here it is.  I harvested the corn, idk somewhere around the middle of that log I would say.  Which is not super helpful I know.

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1648327/output_log.txt)

**Comment by metachronism** [comment]
cant repro this
