### ISSUE TITLE
Hide placement cursors while holding down left click?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3537]
For example, while I am chopping to hew a bunch of wood, the block placement cursor for the wood I just picked up is always right on top of what I'm trying to do

**Comment by metachronism** [comment]
was thinking it shouldnt appear unless you hold still for .5 seconds or something

**Comment by MarjieAVolk** [comment]
Hm idk about that, block placement is pretty hard already, that would basically negate all the benefit we got from client side interactions

**Comment by SeanAtr0n** [comment]
seems like what we really need is a fix for their opaqueness

**Comment by MarjieAVolk** [comment]
That would also help a lot

**Comment by MarjieAVolk** [comment]
But IMO original suggestion would still be worthwhile

**Comment by metachronism** [comment]
closing as the "opaqueness" fix is in and seans other fixes seem to make this a non issue now
