### ISSUE TITLE
buying things from the store doesn't take the item from you

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#354]
it removes the item from the store, and gives the store the item, but doesnt remove it from your inventory - effectively duping the item

**Comment by Nanders** [comment]
Probably related, while the inventory counter goes up every trade, you'll still only actually have as much as you could have traded for.

**Comment by craig-jong** [comment]
This is likely GUID related, I pushed a fix that may fix this. Needs to be tested a bit more.

**Comment by craig-jong** [comment]
WE FIXED IT
