### ISSUE TITLE
Prickly Pear did not get new world 6.4.1

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3542]
anyone else notice this? our world generated without any prickly pears. 

is it possible to spawn worlds without some things?
![2018-01-20](https://user-images.githubusercontent.com/20627148/35184398-4b704c40-fdb2-11e7-9e20-5796e3655182.png)

**Comment by MarjieAVolk** [comment]
Yes, things like this have happened for a long time unfortunately.  There will be some major changes to plant spawning in the next release, so this might be obsolete, @knexer ?

**Comment by knexer** [comment]
Prickly pears should spawn more consistently.
