### ISSUE TITLE
Many modded objects are invisible

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3543]
Some images as proof of this,

NOTE: These worked flawlessly with the last ECO Version.

![image](https://user-images.githubusercontent.com/8785758/35184805-a1659932-fdfa-11e7-9201-f9cf14935d5f.png)
![image](https://user-images.githubusercontent.com/8785758/35184807-a4894910-fdfa-11e7-8dd0-e050a3d8c38f.png)
![image](https://user-images.githubusercontent.com/8785758/35184809-a9be0588-fdfa-11e7-96c1-57c59c98a093.png)

**Comment by SeanAtr0n** [comment]
Looks like it's probably a problem with unity versions, we updated to 2017.3.0f3 (i just updated the wiki) could you try building with an updated unity version?
