### ISSUE TITLE
Coal can not be viewed in stores for trading

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3544]
its listed but other players can not see it listed
![2018-01-20 2](https://user-images.githubusercontent.com/20627148/35184868-30fce6ba-fdb8-11e7-8979-817862752725.png)

**Comment by MarjieAVolk** [comment]
That is odd.  Is it possible that Zalizzar has two stores?  If not, my guess would be that the economy viewer is out of date, that is that the coal listing was recently deleted.

**Comment by kkusch** [comment]
[6.4.1] We had same issue but with all Items. If a user put's it into it's store, other clients need to reconnect to have it displayed in shop.

**Comment by MarjieAVolk** [comment]
O.o

**Comment by stormoffires** [comment]
i saw the same issue kkusch, once users reconnected items began to display properly.

**Comment by johnkslg** [comment]
Fixed! Thanks folks.
