### ISSUE TITLE
Tutorial gives temp tools

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3548]

**Comment by Conchipedia** [comment]
If they are going to be temporary make them last long enough to craft New tools to replace them

**Comment by MarjieAVolk** [comment]
I am not sure what you are picturing exactly, but it sounds a bit odd to me?  Couldn't we have the tool related tutorials not trigger until you've chosen that specialization or something?

**Comment by johnkslg** [comment]
This was the solution we came up with in the design meeting, you were out sick that day I recall. The problem was that the players cant do the base level stuff without tools, but they cant get tools without specializing, and now thats really expensive.  The solution we decided was to give out tools through the tutorial.

**Comment by MarjieAVolk** [comment]
Huh okay, sounds weird to me

**Comment by Conchipedia** [comment]
start a new world and learn something that doesnt give you an axe or a pickaxe then try and make a tool that needs logs and stone, without those two tools you are totally stuck (obvously dont use admin powers)
