### ISSUE TITLE
Backpack and belt arrows dont do anything in avatar creation.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3549]
![image](https://user-images.githubusercontent.com/3536496/35187077-f71089aa-fdd2-11e7-8f59-0ccb977be875.png)
Lets hide these if theres no options.

**Comment by MarjieAVolk** [comment]
That's because there is only one option.  Guess we can just make them invisible for now.

**Comment by GophTheGreat** [comment]
Arrows removed, so this shouldn't be a problem anymore.
