### ISSUE TITLE
USER ISSUE: Dedicated Tool Set Gameplay Request asking?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3553]
**Version:** 0.6.4.1 alpha

**Steps to Reproduce:**
probably getting sick of me already lol, me and my friends where wondering if we could in future get request so that admin or server in dedicated tool set could, 
1A change the number of land markers you start 
2A ability to change distance that stock piles or chest link to tables so that these two things could be more tailored to the game worlds that they are part of. ?  - "that way worlds that are larger KM could extended the range and worlds that are smaller could shorten it."

**Comment by midn8t** [comment]
Gameplay Feature request from my community 
I am adding this because we where talking on discord and in game chat and came up with some features or game play options that be nice to be able to include or have part of admin dedicated tool set or maybe could be used to enhance game play.

1. Fog of War where you do not see every thing on mini map till you explore it your self.

2. ability to turn off in game Spam, for example player x add log to workshop - player n learned skill B the more players on server more annoying this seems to get.

3. Sat mode ability for server admin to hide player icons unless you can see that player or if you are friends.

3. mini map information we thought it be cool if the in game information that is provided by mini map or stats would be something that is provided to player who has specialist for that skill. so for example you would not be able to just see where resources are on the mini map unless  you had a certain level of skill at doing that job that requires those resources, you could then use your skill to bring the chart and information to gether and provide feedback as a report to other players. just like the crime and punishment system is suppose to work.  - this would be a good way to get players to form community's 

4. players dropping out of the game, if player does not come back online for x number of days then his house and land becomes marked as abandon and could start to fall apart or decay also allowing people to loot it or claim the area.

5. instead of just having a world laws - how about regional laws where players can create smaller community in the game like states and create there own laws in those states. - then latter on those states could from UN style world thing. instead of having a one world leader. - could also then have state style regional monies systems.

**Comment by MarjieAVolk** [comment]
Lots of good ideas.  You make a strong case for supporting multiple governments.

1A: You can technically do this by editing the PlayerDefaults file (with a mod basically).  I am not sure of the details of how to do this - @metachronism ?

2B: Individuals can turn off categories of messages in their own displays.  Open the full chat log with 'C', and then on the left you will see all the channels listed.  The green ones are automated server messages.  Click on them to toggle them on and off.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#312
