### ISSUE TITLE
[Suggestion] Add an option to /give command to output all items available to a text file

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3556]
I am testing CTK and needed to /give myself a Storage Closet
I type the name in chat and got this
![snap1243](https://user-images.githubusercontent.com/29383891/35187826-64b5ab80-fe22-11e7-889d-d1bcf311959a.png)

so i typed /give StorageCloset it came up with not known
i then type /give and it showed me ALL items
![snap1246](https://user-images.githubusercontent.com/29383891/35188051-9f5068e4-fe26-11e7-8ce6-0a21dc94b2f2.png)

but this only stays up on the screen for a few Seconds so a snapshot was required

now going through this list was time consuming and difficult to do but still i couldnt seem to find what i was looking for
Eventually i found out the name was this by typing part of it /give ose
![snap1244](https://user-images.githubusercontent.com/29383891/35187863-51f2835a-fe23-11e7-8684-d8843cb86296.png)
So would it be possible to give and arguement to give for example:
/give >Name.txt
so the output is then written to a text file which would be much easier to search through
or maybe even another command that is specifically designed to just do this.

**Comment by Conchipedia** [comment]
on a side note reading through this i can see all the Profressions Skill Books and Skill Scrolls that are not needed so linked this part to this
There are skill books for many of the professions #3479

**Comment by metachronism** [comment]
Take a look at the option already on the server ModKit -> Export Item List
will create a folder called ItemDump with all the items in it
