### ISSUE TITLE
Harvest field clause no longer includes logs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3558]

**Comment by WeaselDog** [comment]
Logs are back in Harvest Field, but it does not function anymore due to different kinds of logs. The Log in the contract clause should likely be replaced with the "Logs" tag.

**Comment by WeaselDog** [comment]
In SearchAndSelectItemSets.cs the last line of code has to be changed to check for the tag. It currently checks if the display name is "Log".

**Comment by johnkslg** [comment]
Logs listed again, the fix was just as you said, thanks!
![image](https://user-images.githubusercontent.com/3536496/71924115-33367c00-3143-11ea-967a-f813d4ec1043.png)

**Comment by beastyn** [comment]
Well, if you are creating a contract with some live trees, they will be counted for logs, but contractor can't chop them down (he can take a contract though),

**Comment by johnkslg** [comment]
This used to work, find the old code paths and see why they're failing.
