### ISSUE TITLE
USER ISSUE: missing longs

### ISSUE THREAD

**Issue by maximus2155** [StrangeLoopGames/EcoIssues#3559]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
pick up hew logs 

**Expected behavior:**
does not show a picture and text in carry.

**Actual behavior:**
is does not show that you are carrieng hews, there is even no text, but it shows that you are carrieng someting.

**Comment by MarjieAVolk** [comment]
Sounds like, eg. https://github.com/StrangeLoopGames/EcoIssues/issues/3531

**Comment by elfl0rd** [comment]
@D3nnis3n fixed loong time ago.
