### ISSUE TITLE
Remove dark shading on water?

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3563]
If there's a way to change the material that adds that black shading there it would look a lot better. Should look much more translucent in general for rivers especially.
![image](https://user-images.githubusercontent.com/3536496/35189455-8f462064-fdff-11e7-96e3-2941c7f5cffe.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#310
