### ISSUE TITLE
Planter Pot Round Broken again, Planter Pot Icons are also messed up [6.4.1] [Art]

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3565]
![image](https://user-images.githubusercontent.com/4082137/35190200-23038b5a-fe2a-11e7-86db-ab14c362a75b.png)

![image](https://user-images.githubusercontent.com/4082137/35190208-4e421408-fe2a-11e7-9677-57e3aca290c7.png)

Pics say it all

**Comment by Huntermeign** [comment]
Apparently a lot of icons got messed up as well in carpentry

**Comment by keegan-o** [comment]
Worry not my friend, Framed Glass is indeed planned and locked in-- For beta we may only get Walls and Floors for it, but stairs and slopes that allow the pyramid will 100% happen! :)
