### ISSUE TITLE
Land Claim Issue/Suggestion: Trees encroaching other claimed territories undestructible

### ISSUE THREAD

**Issue by ReiRay** [StrangeLoopGames/EcoIssues#3566]
//Reproduce
User1 grows tree in own claimed, and the branches/leaves grow into User2's territory
User2 cannot chop off the branches/leaves in territory
User2 ragequits

//Footnote
Consider making the tree fully destructible if it encroaches on someone else's claimed territory, unless the branch is permanently removed.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#309
