### ISSUE TITLE
Cement Tree - Recipe Misplaced?

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#3568]
Hi,
I was wondering about the cement line. The recipe seems to be locked under the Stone Construction Tree rather than the Cement Tree. It seems odd since Bricks and Mortared Stone have their own trees which the recipes are unlocked there and the Stone construction is just for speed and efficiency. 
Why is the recipe there rather than the cement tree? Thought it might be misplaced.

Note: This is 6.4.1 Version.

![image](https://user-images.githubusercontent.com/29911902/35197083-ea2313ea-ff2e-11e7-98fd-2769014d03a3.png)

![image](https://user-images.githubusercontent.com/29911902/35197096-0483b1fe-ff2f-11e7-8ac5-f64782ffb2da.png)

**Comment by ZeelNightwolf** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3643

**Comment by MarjieAVolk** [comment]
Thanks, leaving both bugs open as they have different additional details/suggestions

**Comment by craig-jong** [comment]
this is fixed in current staging (or near current)
