### ISSUE TITLE
Need way to config admin and other options for singleplayer

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3569]
![screenshot_20180121-103624](https://user-images.githubusercontent.com/3536496/35197647-10d81b18-fe97-11e7-869a-5bd2df30f410.png)
Cheat code maybe?

**Comment by MarjieAVolk** [comment]
Maybe you should just be admin by default if you create a server locally.

**Comment by MarjieAVolk** [comment]
Although there should be controls too I suppose

**Comment by johnkslg** [comment]
Yes was thinking we just have the server open as task, which they can tab over to and muck with. Thoughts?

**Comment by MarjieAVolk** [comment]
So you are saying, don't have it run headless?  IDK about the technical requirements, but yeah I would say if we can manage to show the normal server UI, we should do so.

**Comment by jarckn** [comment]
I guess it would be better to just keep the server console and config window hidden. I mean, it's technically a normal server in the background running, but I think, the user actually doesn't need to know this.

I would keep it this way, or maybe add some kind of config tool, where the user can manipulate the basic settings of the server or even add some basic config options directly into the games options menu.

Anyway, the host user (linked to 127.0.0.1 maybe) should be always admins, imho.
