### ISSUE TITLE
Darken hewed logs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3572]
Give them a stained look, so log cabins look like people are familiar with
![45785c40-e157-47bf-a78c-7fa16a380d42 c10](https://user-images.githubusercontent.com/3536496/35198050-c7bdedc0-fe9d-11e7-82f1-e43a65e8d3d6.jpg)

**Comment by MarjieAVolk** [comment]
Thought we were going to have a different stained version as a higher tier
