### ISSUE TITLE
Can't do a Teir 3 Building thanks to Tailoring Table

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#3573]
To make Bricklaying skill book you need Cloth.
To make Lumber skill book you need Cloth.

To use a Tailoring table, you need a t3 room. Which is either a Brick room or Lumber room.

Catch 22

**Comment by Huntermeign** [comment]
Work around until fix would be to use glass

**Comment by Felstein** [comment]
Also can not craft Large or Medium Rugs due to Tailoring being a specialisation now.
