### ISSUE TITLE
[Client Issue] Several Client crashes (Now with .dmp!)

### ISSUE THREAD

**Issue by Felstein** [StrangeLoopGames/EcoIssues#3578]
Hi devs, love your show. Long time listener and all that.

I have been experiencing many client crashes while playing on a 6.4.1 server. The 4 most recent crash.dmp files are attached. When playing on 6.4, the crashes would occur often when I would open a chest or stockpile, there would be a slight graphical lag and then it would crash and create a dump. Since 6.4.1, it has started crashing randomly, I'd just be running through a forest and it'd boot me, other times I'd moving through my house. It seems to be when I am navigating through areas, not when I'm standing still. Anyway, I have about 30 .dmp files from crashes since 6.4 was released if you want them all :)

[Crash_2018-01-21_112646.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1650777/Crash_2018-01-21_112646.zip)

**Comment by MarjieAVolk** [comment]
Hm, all of these seem to say something like 'Unhandled exception at 0x00007FFD69F0CB72 (UnityPlayer.dll) in crash.dmp: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.'  An internal Unity bug?

@Felstein What operating system are you on?

**Comment by Felstein** [comment]
Windows 10, latest updates installed too.

**Comment by Felstein** [comment]
Thanks for elevating the issue.

**Comment by dalekarran** [comment]
Hi, sorry if this is wrong place to post.
I too have had the same issues as described above preventing me from playing for any longer than 10 minutes (or less) at a time before my client just crashes.
Here are a few crash reports.
[crash reports.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1653887/crash.reports.zip)

**Comment by pamduncan** [comment]
We are getting many people coming to discord complaining of the client closing and disconnecting them from the server.  We have been asking each to post their experience (ie what they were doing when this happened) and to post errors or logs.  Most have refused to  - saying that commenting in chat is enough and that they don't want to provide logs (someone had the idea you could get personal info from this).  So all I an tell you is that it seems to be a very common issue and seems like many people are having it but no way to tell you how many people, what OS they are running on, or anything else as they are not willing to document.  They only thing I do know if this is does not seem associated with solo play as they are all saying they are connected to servers and it happens with any server they connect to.

**Comment by Felstein** [comment]
A further update to this. I have a fairly expensive rig with overclocks etc. I have removed the OCs on both CPU and GPU and am now playing the game at 1920x1080 and 'good' graphic settings and the crashes have stopped happening so often. Perhaps a graphical memory leak on high graphic options? Haven't tested all different graphic options to check theory.

**Comment by Felstein** [comment]
Can confirm I have had no crash since reducing my resolution and playing on 'good' instead of top graphic settings. Unfortunate as my computer should be able to eat a game like this. I've played about 14 hours now with zero crashes.

**Comment by metachronism** [comment]
disabled graphics jobs in an attempt to fix this
