### ISSUE TITLE
[Suggestion][Web server] Law title is too long

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3579]
![grafik](https://user-images.githubusercontent.com/1441097/35215894-03336a56-ff66-11e7-938c-cef2e6b4fa50.png)

I got an error message while proposing a new law.

I would suggest, that there should be any information, how long the title could be.
For example "The entered title is too long. (max. xxx characters)".

**Comment by rainfarmer** [comment]
added max characters
