### ISSUE TITLE
cannot login on Linux - double input

### ISSUE THREAD

**Issue by LiamDawe** [StrangeLoopGames/EcoIssues#3580]
In the latest Linux version, the login boxes take double input making it impossible to enter your username and password.

To be clear: you enter "username" and it comes up as "uusseerrnnaammee" - double input. Making it impossible to login.

**Comment by metachronism** [comment]
I'm guessing both text boxes taking input at the same time

**Comment by metachronism** [comment]
you could login on windows, and copy the cachedlogin file over as a workaround

**Comment by LiamDawe** [comment]
To be clear: you enter "username" and it comes up as "uusseerrnnaammee" - double input. Making it impossible to login.

And no, logging into Windows to copy a file for a Linux game is NOT a solution.

**Comment by metachronism** [comment]
well, not a solution, just a workaround :P

**Comment by pamduncan** [comment]
'double input' means, in this case, program sees 2 key presses/strokes for each one made so if you type "A" "AA" gets inserted.  This might be a Linux issue and not Eco.  I get this often on some versions of Linux and not on others.  I have a couple of servers running Windows OS that is  if I SSH to connect to to it I have to use the on screen keyboard which will see each key click as a single press but if I try to use the keyboard it sees every key press as too.   It also happens with remote desktop and with connecting to Linux apps I have native Linux using Linux clients and this happens with the physical keyboard and it also happens to users connecting to game servers on Linux or to the Linux server itself.   Just wanted to let you know that this behavior on Linux and I did not report it when Eco did its assuming it was Linux.  I just wanted to comment here to let you know this might totally be a Linux issue and not have anything to do with Eco at all.

**Comment by SeanAtr0n** [comment]
Doing a build that might fix this... one ridiculous way to get past login is to copy/paste your username/password (i got "SeanAtr0nSeanAtr0n") then highlight and double-backspace the extra part. (couldn't double-backspace my odd # name so I highlighted the 2nd "eanAtr0n" then hit backspace)

**Comment by SeanAtr0n** [comment]
This seems to be related to some steam code, for some reason after logging in with steam in the staging branch it always works for me even on builds where it used to do this.

Hopefully once you get your steam account linked it should work for you. (feb 6th, or try the latest staging build)

**Comment by SeanAtr0n** [comment]
We could probably setup steam linking early for you if you want to try the latest staging build

**Comment by Fank** [comment]
@pamduncan tried some onscreen keyboard, but still same behavouir.
I'm using ubuntu 17.10

**Comment by SeanAtr0n** [comment]
This is a bug due to steam code, works fine when logging in with steam

**Comment by Fank** [comment]
How can i login with steam?

**Comment by JonHoye** [comment]
Hm, I'm still getting this as of the latest patch, using steam.

**Comment by davegrix** [comment]
Any updates on this issue?

**Comment by johnfzc** [comment]
I discussed this issue with neX!Tem on the discord and was provided with a workaround. On Ubunto you can open Language Support and change the Keyboard Input Method System from Ibus to None. This will prevent the use of certain asian languages but does permit you to enter your password and connect to a server.

**Comment by Stechi** [comment]
I have the same problem.
It doesn't only apply to the login but to every text-related field.
So functions you can't use on Linux:
-login
-add server in the server list
-ingame chat
-naming things (carts, signs, ...)

Also I am trying to play via steam,
so the mentioned "workaround" doesn't work.

**Comment by MarjieAVolk** [comment]
"After searching through the internet, I found an issue in Unity that exactly behaves the same way: https://issuetracker.unity3d.com/issues/linux-keystrokes-recorded-twice

Their issue tracker says, that this issue is fixed in version 2018.1" -- @Epimetheus89

**Comment by Missou** [comment]
I'm also playing on steam and typing the command:
`ibus exit`
before launching steam prevent the game from taking the double input

**Comment by danielhodder** [comment]
Running `ibus exit` didn't help for me. Neither did uninstalling `ibus`.

**Comment by LiamDawe** [comment]
It's a Unity game engine issue, they need to update as far as I know that's currently the only way to actually solve it.

**Comment by Stechi** [comment]
@LiamDawe Are you sure? 
I am playing multiple Unity games on Linux and this one, is the first one, 
which has problems with the double registration of key presses.
Maybe it is specific for this specific version of Unity,
but maybe not.

**Comment by MarjieAVolk** [comment]
"All keys are in almost all circumstances doubly registered. This started in 0.7.2.5.
I can not type anything, because even backspace refuses to delete only one character.

Btw. I can also not walk staight forward. Lets say I walk 1 min forward, when I stop pressing the 'W' key, the character will proceed running for almost 10 seconds.

Sometimes my walking gets really slow, (really really slow), but I am not starving, seems related.

Generally everything, which has to do with input handling sucks since this release." -- @ruabmbua

"This issue also happens if you copy and paste text, like a server name or password." -- @danielhodder

**Comment by MarjieAVolk** [comment]
FYI guys, 7.3 will be on Unity 2017.4, which is the most recent non-beta Unity version.  So presumably this will not be fixed in Eco 7.3.  We will update to 2018 when it comes out of beta -- should be in the next month I believe.

**Comment by matias-b** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/3580#issuecomment-372886678

That workaround fixed the issue for me

**Comment by danielhodder** [comment]
I've noticed this working properly on the 7.3.1.beta version from steam. I had previously uninstalled ibus so that may also be a factor

**Comment by SeanAtr0n** [comment]
will be fixed in 7.7 if this is right https://issuetracker.unity3d.com/issues/linux-keystrokes-recorded-twice

**Comment by ObradovicNikola** [comment]
I started developing with Unity and I have the same issue with input field in 2019. For some weird reason this is only the case in editor, but when I build my game everything works fine. 
I'm using i3wm on ubuntu if that matters.
