### ISSUE TITLE
[Suggestion][Web server] Allow admins to configure the http server rudimentary

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3581]
I would like to see, that admins are able to change simple settings like: 
Header (i.e. clear the "Server"-Header), SSL Ciphers, HTTPS Support, Certificates

Currently I am dealing with this via reverse proxying, but not everyones having this option.
Hopefully, this is possible using the HTTP Server API.

Would say this has a low priority.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#308
