### ISSUE TITLE
Can't connect to my server.

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#3583]
Issues happening on GreenLeaf Main.

[ClientUpdateException TargetInvocationException 01220331.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1652857/ClientUpdateException.TargetInvocationException.01220331.zip)

Server is running 6.4.1 as well as the client, and I seem to be the only one having this issue on Phlo (account name).

On another note, I wanted to ask you if modders will get a "heads up" before Beta releases as the current update messed with all my models and nothing works. "Heads up" means a modkit that has been tested on the future update.

**Comment by Phlo123** [comment]
https://www.dropbox.com/s/6psbt5fcdrm5ihm/GreenLeaf-Game.eco?dl=0

**Comment by Phlo123** [comment]
After the issue is fixed I would like an explanation to what caused this in case it was one of my mods so I can learn and not do it again. thank you.

**Comment by MarjieAVolk** [comment]
Sure, will do

**Comment by MarjieAVolk** [comment]
So the crash had nothing to do with mods.  As for the mod object model problems, we are having other reports that as well, I don't know the cause yet - tracking that issue here for now: https://github.com/StrangeLoopGames/EcoIssues/issues/3543

**Comment by MarjieAVolk** [comment]
@Phlo123 The modkit bug has been closed - we believe the issue was that we updated our unity version, so modders will have to do the same.  The mod documentation has been updated.  Hope that helps

**Comment by Phlo123** [comment]
Thanks.
