### ISSUE TITLE
LiaungYip Typo Fixes

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#3585]
![image](https://user-images.githubusercontent.com/18184943/35239296-f29b2b6c-ff64-11e7-8012-eefc0b18be3f.png)

**Comment by LiaungYip** [comment]
Thanks for this. I'll file issues against this tracker (EcoIssues) as I find more of these.

I believe the upstream source for this is actually an Excel spreadsheet, so filing pull requests against the source code doesn't help you. :)
