### ISSUE TITLE
Admin command /fly seems to not be working

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3589]
**Version:** 0.6.4.1 alpha

![snap1285](https://user-images.githubusercontent.com/29383891/35252613-23b6746c-ffd9-11e7-8e06-0e409d550dd2.png)

As Admin i was hoping to see what my Pyramid and Emoji looked like from above not just from the Minimap, so tried /fly and nothing happens

**Comment by pamduncan** [comment]
/fly is not working on any of our worlds either

**Comment by SeanAtr0n** [comment]
think meta already has a fix for this
