### ISSUE TITLE
Deleting populations of trees in the world layer didnt delete them in the game

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3591]
![image](https://user-images.githubusercontent.com/3536496/35253973-17228c36-ff9d-11e7-88e8-2bbb78ebda18.png)
If the world layer has plants deleted, it should propagate to the world.

**Comment by MarjieAVolk** [comment]
This is a dev feature, right?

**Comment by knexer** [comment]
This is fixed
