### ISSUE TITLE
Unlearning Skills confirmation window should tell you how many points you'll lose.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3593]
![image](https://user-images.githubusercontent.com/3536496/35257033-e1054c92-ffab-11e7-83f9-1bc8bb811c27.png)
If the point loss is zero, it can do it without warning.

**Comment by MarjieAVolk** [comment]
Laziness on my part that it doesn't already do this >>

**Comment by D3nnis3n** [comment]
Refunding was removed.
