### ISSUE TITLE
Cannot make Fletchers Tool Shelf

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3594]
No longer linked to any recipe in game. Cannot make bows. Only those who are hunters get them now.

**Comment by craig-jong** [comment]
Are you on the latest hotfixed build?

Just making sure - this may still be an issue but we did hotfix a few module related bugs earlier (modules should have no objects that use them anymore).

**Comment by Huntermeign** [comment]
This was an issue of not doing a complete server install from 6.3 to 6.4. Doing the clean install after solved this.
