### ISSUE TITLE
audio issue in waterfall

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3598]
There is a very odd and loud squeal that happens, almost like a feedback, if you happen to fall in the waterfall at about the area where a lot of water is still flowing up.  Its very quick in passing.  The first time it happened I was recording an though it might be the recording software but I have been able to make it happen since when the software is not in use.

**Comment by Nanders** [comment]
Having a hard time reproducing this, can you tell me what version you were playing on @pamduncan?

**Comment by Nanders** [comment]
Fixed
