### ISSUE TITLE
Rolling Mill - Causing Permanent Kick from the Server.

### ISSUE THREAD

**Issue by MasterSloth** [StrangeLoopGames/EcoIssues#3599]
Placing a Rolling Mill down, will boot you from the server with an exception error, when you try to reconnect it will kick you over and over.
Restarting server = Does nothing

https://pastebin.com/YEubSV9j

**Comment by MasterSloth** [comment]
Update: the rolling mill has affected all players on the server, everyone gets kicked on trying to join.

[09:08] Caught update exception from Vantak!  Disconnecting...
[09:08] Disconnecting client [reason: Caught exception: Exception has been thrown by the target of an invocation.]...

**Comment by Huntermeign** [comment]
It seems to me that almost all the modules are busted. a hotfix would be nice.

**Comment by MarjieAVolk** [comment]
I tried placing down the the rolling mill, and haven't seen any problems yet.  Tried logging out and back in, tried restarting the server, and it looks fine.  Although it also looks like it doesn't really do anything.  @craig-jong it has a Crafting component but no recipes on it.

So for the original problem - could you send your save file?

**Comment by craig-jong** [comment]
Tables with no recipes used to cause the server to crash - this is no longer the case. That may or may not have been the issue here.

**Comment by metachronism** [comment]
already fixed

**Comment by N-Muller** [comment]
I have the exact same problem on my server (6.4.1, with the quickfix for mechanics-fishery mod installed (AFAIK, this mod does not have anything to do with the rolling mill)).
Nobody can join the server anymore (instant disconect on server join) and the server logs :
```
[46:02] Caught update exception from BelgaMul!  Disconnecting...
[46:02] Disconnecting client [reason: Caught exception: Exception has been throw
n by the target of an invocation.]...
[53:16] Caught update exception from Babar!  Disconnecting...
[53:16] Disconnecting client [reason: Caught exception: Exception has been throw
n by the target of an invocation.]...
```
