### ISSUE TITLE
Client Bug, OS X, eco alpha 0.2 : Can't move

### ISSUE THREAD

**Issue by mkarneim** [StrangeLoopGames/EcoIssues#36]
Bug appears on OS X 10.11.2

After successful login into a server, I can't move by using the WSAD keys.
Also I can not look around with the mouse.
This is true for windowed and fullscreen mode.

**Comment by metrotyranno** [comment]
Try pressing TAB to exit / enter the context menu.

**Comment by mkarneim** [comment]
Thanks, that solved it.
