### ISSUE TITLE
Tailoring Table hovering mouse over Leather hide in crafting window shows weird message

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3601]
Version: 0.6.4.1 alpha

![snap1286](https://user-images.githubusercontent.com/29383891/35283531-65fbc328-0050-11e8-852d-954d992d0937.png)
when Leather Hide is type in chat see normal Description
![snap1287](https://user-images.githubusercontent.com/29383891/35283591-92aaafba-0050-11e8-9379-6520290ce3a0.png)
This is on Greenleaf which was a 6.3.1 world converted to 6.4.1 not sure if any mods are aimed at this table

got another player to check this he is also seeing the weird message

**Comment by Conchipedia** [comment]
Just Checked on Marmot and it is showing normally

**Comment by MarjieAVolk** [comment]
Yeah it's working for me on master too.  So sounds like it's a mod problem?  Mods should be able to add tooltips to existing items, so I suppose that's probably what's going on.  My guess would be one of the mods has an extension method on LeatherHide (or on Item) that ha [Tooltip()] on it, but doesn't have the correct return type (return type should be string or TooltipSection)
