### ISSUE TITLE
USER ISSUE: Sawmill will not work

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#3606]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
Build a sawmill and place in world

**Expected behavior:**
Ability to make lumber without any requirements and unable to place through stuff

**Actual behavior:**
saws requires sawmill and can be placed through other objects

**Comment by MarjieAVolk** [comment]
This has been hotfixed already, update to 0.6.4.2 :) There are a number of other fixes as well, should be a much better experience
