### ISSUE TITLE
Admin powers

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3607]
Admins and mods need more power over servers. 

There is no way to easily remove unwanted/bugged out carts without having the deeds. (ie player banned for griefing left hundreds of carts on the server and cant remove them)

also a way to mass unclaim land

also with carts there is no way to claim ownership of a deed thats not yours.

**Comment by Nes112** [comment]
@stormoffires Getting rid of other players' carts is definitely something that we need. That is a bug that deserves its own report.

As for the mass unclaiming land, that seems more like a feature suggestion, and I have heard talk of a system for land claims to decay, sometime in the future. I think mass unclaim would be a good mod request!

**Comment by pamduncan** [comment]
You might want to talk with Pradoxzon - he just put in a whole Administration mod that gives admins access to many of the server UI commands as well as kick and ban from in game.  He is working on a /unclaim tool to add to that that will unclaim according to player's name so.  He might be willing/able to add a solution for your cart problem

**Comment by Nembience** [comment]
We're having an issue with carts at the moment too. I can't seem to do anything to get rid of an abandoned cart in someones base nor can we even see who owned it. 

Literally just stuck there a /delete would be fantastic or a /claim but a suggestion would be to see who owns a cart by hovering over too. Thanks!

**Comment by ecoemmeck** [comment]
has anyone found a workaround for the mean time so we as admins can deal with abandoned carts?

**Comment by Nembience** [comment]
You can try moving carts with soil, they bounce out the way, it's how I dealt with mine

**Comment by MarjieAVolk** [comment]
Seems the dev tool is able to remove carts belonging to others.

**Comment by ecoemmeck** [comment]
the devtool can only delete the cart if its unlocked or you are authorized on the deed

**Comment by Skjolbir** [comment]
This needs moving up to high priority. Duplicate carts on our server have been the cause of multiple crashes and we've had to wipe the save and start over twice.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#307
