### ISSUE TITLE
players can no longer learn from skill scrolls

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3608]
so far i have had 2 players who can no longer learn skills.

they can right click a scroll and are told they learned said skill (applies to ALL skill scrolls)

then they go to their skills and look at it says "you have not learned X skill"

no bugs or errors reporting that i can see

**Comment by Nes112** [comment]
@stormoffires What version did this happen under? I haven't heard of this bug.

**Comment by MarjieAVolk** [comment]
Wondering if this is a misunderstanding, as you have to both learn the skill with the scroll and then also pay for it in order to actually get it.

**Comment by stormoffires** [comment]
6.4.1 and 6.4.2 i have a player who just happened to.

the previous player i deleted his char and he rejoined with no more issues

**Comment by stormoffires** [comment]
https://drive.google.com/open?id=1N2RVaGFapFTFo7FFphZV9TJTim-Ak5Tx

thats our world file. maybe it can help?

**Comment by MarjieAVolk** [comment]
Thanks for the save file.  Which users were having this problem?

**Comment by stormoffires** [comment]
it was JaranMarcel, however in our current world (not the upload) he has been deleted from the world file and works again now.

**Comment by MarjieAVolk** [comment]
Great, so in the save you gave me JaranMarcel has the issue?

**Comment by MarjieAVolk** [comment]
Okay well still not seeing this issue when using skill scrolls as JaranMarcel in the save you gave me

**Comment by stormoffires** [comment]
yes that save file was while he had issues. Im sorry it isnt repeatable :/ maybe its a local client issue?

**Comment by MarjieAVolk** [comment]
Possibly the error was fixed by logging out and back in, rather than by deleting the user?

**Comment by elfl0rd** [comment]
looks is not reproducible

**Comment by MarjieAVolk** [comment]
Yeah, we haven't seen any more complaints of this as far as I know either.  Okay, closing for now.
