### ISSUE TITLE
USER ISSUE: Contract board and contract bug.

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3611]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
I created contract board, created a contract but then closed it out with out creaitng it,  then i deleted the contract board after words 30 mins latter three contracts in yellow poped up on side of my screen and i can not remove them.

**Expected behavior:**

**Actual behavior:**

**Comment by kkusch** [comment]
We are not able to create contracts either.
The Contract UI is opened but "Save Contract" and "Delete Contract" button do nothing.
Contract drafts will be in upper right corner and there is no way of removing them. They'll even stay if contract board was deconstructed.

**Comment by Plason** [comment]
I was clicking on som things, and got sent off the server with and exception.  now I got he same issue as above.  can not delete anything etc.

> Caught exception: Caught exception invoking RPC ViewRPC on Client!
> 
> Caught exception invoking RPC Delete on Contract!
> 
> Specified argument was out of the range of valid values.
> Parameter name: index
> 
> 
> Stack:
>    at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
>    at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
>    at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
>    at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
>    at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
>    at Eco.Core.Controller.RPCListExtensions.Delete(IContainsRPCList obj, Int32 iList, Int32 iEntry)
> 
> 
> 
> Stack:
>    at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
>    at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
>    at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by clairemarshal** [comment]
I don't have time to diagnose this for you, but its probably a related bug. Here is the crash log.

Feature Contracts
User action: Crash on set Contract agreement to "Custom"

Crash log.
------------------------------
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC ChangeClause on Contract!

Specified argument was out of the range of valid values.
Parameter name: index


Stack:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.RemoveAt(Int32 index)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Utils.ControllerList`1.<>c__DisplayClass12_0.<RemoveAt>b__0()
   at Eco.Core.Utils.ControllerList`1.ApplyChange(Action change)
   at Eco.Gameplay.Economy.Contracts.ClauseListExtensions.ChangeClause(IClauseList list, Int32 index, String newClauseType)



Stack:
   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by johnkslg** [comment]
Fixed!
