### ISSUE TITLE
USER ISSUE: Itemplacement menu not seeming to work ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3613]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
no one on my server including my self can get items to place for example we have hwen logs and or mortared stone but can not get menu sytem to work that allows us to build things like steps or roofs so forth. ?

we have the item in hand like the mortar stone  or the hwen house building logs.

we bring out the hammer

we left click, right click, press any number of keys on the keyboard, look at the control key binding setup.

there seems to be no way to place things like steps and or roofs any more i guess, we looked at news page says that in version 6 suppose to be able to do this but we cant figure it out or its broken  or its not implemented as stated on the news page.  ?

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
You have to hold down shift, and while shift is held down, use the mouse scroll wheel.

**Comment by MarjieAVolk** [comment]
We are talking about how to make this more clear, and as you mentioned we still need to add it into the controls configuration

**Comment by midn8t** [comment]
Thanks for info...
