### ISSUE TITLE
Suggestion water splash improvement

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#3615]
The waters splash should perhaps have 3 or 4 splash model's for the different heights the water is falling.
Something like 1-2 blocks of falling should be a small splash 3-5 blocks slightly larger splash 5-10 blocks larger splash and 10-20 blocks a really big splash.

Also I've noticed in the middle of a lake / ocean the water splashing when there is no drop off for the water to be splashing

**Comment by keegan-o** [comment]
can't be done with current builder system (they only see blocks immediately surrounding each-other), we definitely hope to improve water as a whole including effects more in the future.
