### ISSUE TITLE
/chattest locks Client UI

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3618]
Using the /chattest command locks up the client UI,.  Nothing is written to the chat window and the UI does not recover.  CTRL_ALT_DEL was only remedy.  Server did not seem to register the command, no dump file was produced.  Nothing was logged to client.  I suspect this command has not been used in ages and its certainly no make it or break it command - I only just caught it not functioning because I happened to need a bunch of chat spam to test a current project

**Comment by D3nnis3n** [comment]
Works for me and is a dev command anyway.
