### ISSUE TITLE
Main Menu: Continue doesn't refresh

### ISSUE THREAD

**Issue by ClayC90** [StrangeLoopGames/EcoIssues#3619]
Specifically the continue button,

Since on this screen there is only a single server to check, can this menu be checking the server every few seconds? 
More over, I would like it to display the current state of the server, whether online or offline, and if it's offline, I want to know if it has come back online, at the moment we have to close the game and re-open for it to refresh, or log out and back in.

**Comment by Nes112** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3616?

**Comment by MarjieAVolk** [comment]
Uh I am not sure what that bug is saying, so I'll leave both open :P

+1 Refreshing this would be really helpful, been bothering me too

**Comment by ClayC90** [comment]
@Nes112 yes this is like #3616 but it has added information / suggestions to it. :)

**Comment by MarjieAVolk** [comment]
:'(
