### ISSUE TITLE
Put cart on ground game crashed says this:

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#3620]
Caught exception: Sequence contains no matching element

**Comment by SeanAtr0n** [comment]
which cart? any special circumstances?

**Comment by cuda70** [comment]
Small cart i unloaded to my stockpile at home put cart away using hammer walked back to the stone i am mining placed cart on ground and POOF game crashed

**Comment by SeanAtr0n** [comment]
Haven't been able to reproduce so far... It kicked you off the server or it actually crashed the game? Could you send us your error log if it crashes again?
C:\Users\username\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by SeanAtr0n** [comment]
seems like this is related to property or linked inventories

**Comment by MarjieAVolk** [comment]
Ooh, think this is the same problem as this one, which I just marked as fixed: https://github.com/StrangeLoopGames/EcoIssues/issues/3908

(I say marked as fixed because I'm only like oh 80% sure that it's fixed, so do let me know if you see it again after the next hotfix)
