### ISSUE TITLE
USER ISSUE: No close Button top right on Government Window

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3622]
**Version:** 0.7.0.0 beta staging-b1111b5c

![snap1294](https://user-images.githubusercontent.com/29383891/35391568-fe4c98e6-01d6-11e8-97ac-2872defc34ee.png)
You have to Close it again by pressing L

**Comment by MarjieAVolk** [comment]
derp derp I saw this as I was working on it and forgot to fix it
