### ISSUE TITLE
Mechanics Components require the Mechanics skill

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#3624]
In 0.6.4.1 alpha,

Copper Wiring, Combustion Engine, Piston, etc. require the skill "Mechanics 2".

Since "Mechanics" is a specialisation, it's impossible to get more than one level of it.

Also, the skill "Mechanics Components" skill unlocks nothing except the "Mechanics Components Efficiency" skill.

I think it was intended that Copper Wiring etc. should require "Mechanics **Components** 2".

![image](https://user-images.githubusercontent.com/2173684/35395404-07e91118-0236-11e8-81f6-2c3f46bfa471.png)

![image](https://user-images.githubusercontent.com/2173684/35395589-82c5d362-0236-11e8-8b0b-af0a4d4d136a.png)

**Comment by MarjieAVolk** [comment]
This may have already been fixed.

@craig-jong Couldn't we add a check of some kind that would throw exceptions if something requires a skill that is higher than the max value of that skill?

**Comment by metachronism** [comment]
may need a hotfix for this

**Comment by LiaungYip** [comment]
Apparently there was a similar bug on the Fisheries skill tree.

http://ecoforum.strangeloopgames.com:4567/topic/3275/quick-fix-for-fishery-and-mechaics refers.
