### ISSUE TITLE
[Suggestion] Make construction with hammer more user-friendly

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#3627]
Having to click on the menu to select different block forms when using the hammer can make building a pain in the butt. There should be way to change the block form using the keyboard or mouse.

Perhaps Shift + scroll wheel or Ctrl + scroll wheel?

**Comment by MarjieAVolk** [comment]
Shift + scroll wheel already works for it ;)  I have just added a control indicator text on the form selector icon, and the option to configure it in the controls menu, so it should be more discoverable now.
