### ISSUE TITLE
Eco Staging beta 7.0.0 #b1111b5c

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3628]
I have try generated 4 worlds seems every time no animals generate into the world.  world size generation is 60 by 60 with 100 height not sure if that makes a diff, we are small community so we use little smaller world size.  

plants spawn fine for us unlike other ticket i just seen.

total time it took for world generation was about hour little over sometimes little less before it would be fully finished.

world seed that auto generated into the seed number would sometimes not work halt whole world generation system, by manual change this we could get different results sometimes it would Finnish sometimes it hang sometimes it hard crash the hardware rebooting whole server.

best world generation results we found by further testing was to use a manual seed with 100 by 100 with default height.

update - world size of 40 by 40 with 80 height causes hardware crash and system power off majority of the time or it would hang well  longer then hour during generation.

I am including the DxDiag for the server we use. it has no sound or video card just server.

TightVNC is used to access server.
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1665139/DxDiag.txt)

**Comment by metachronism** [comment]
this is known right now - world layers is getting a balancing pass.

closing this in favor of this other issue: #3630
