### ISSUE TITLE
World layers issues

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3630]
- [x] Initial tick of world layers on world gen is too long
- [x] Balance biomes such that each is roughly well represented (grassland, forest, desert, tundra, wetlands, underwater)
- [x] Trees spawn too close together
- [x] Overall too many plants, plant density is really high for some species
- [x] No animals spawned at all
- [ ] Missing Fir trees (exist in higher elevation forests)
- [ ] Missing Oak trees (should exist in grassland and low frequencies and far apart)
- [x] No underwater plants spawned
- [x] First tick after world gen, lots of plants die
- [x] Yield of plants is wrong
- [x] Range / render range of plants is all wrong, makes it hard to see the layer
- [x] Plant density is too high on migrated worlds

**Comment by knexer** [comment]
Added one more - plant yield is wrong

**Comment by knexer** [comment]
Can you elaborate on 'first tick after world gen, lots of plants die' ? I cannot reproduce it.

**Comment by MarjieAVolk** [comment]
plants are always all dead when I've been playing lately.  If that's not the case anymore then maybe it's fixed already

**Comment by knexer** [comment]
Migrated world or fresh?

**Comment by MarjieAVolk** [comment]
Think I was seeing it on fresh worlds before, but idk what the current state is

**Comment by knexer** [comment]
K checked it off then assuming it is fixed

**Comment by knexer** [comment]
Balanced the biomes themselves - some plants may still need tuning to end up in their intended biome though.

**Comment by knexer** [comment]
Also plant density should not be universally way too high any more - I went in and added configuration for all the shrubs so that they consume shrub space as intended.  Some individual species may be tuned too high or low still, but overall it's in a good place.

**Comment by knexer** [comment]
Plant yield is fixed with https://github.com/StrangeLoopGames/Eco/pull/2321.  It's pretty much there now, I think - just needs that last migration fix and we're down to just tweaking the config for each species :)

**Comment by knexer** [comment]
And, of course, optimization; can always use more of that

**Comment by knexer** [comment]
Fixed the plant density on migration

**Comment by knexer** [comment]
https://github.com/StrangeLoopGames/Eco/pull/2326 fixes trees spawning too close to one another

**Comment by Senlarus** [comment]
New world spawned with build **9488ed17**, simulation window showing lack of many plant resources.
Time passed: 8m 12s

Animals:
- Bison:          756 alive, 0 dead, 0 visible
- Fox:            617 alive, 0 dead, 0 visible
- Hare:           776 alive, 0 dead, 0 visible
- Salmon:         917 alive, 0 dead, 0 visible
- Trout:          913 alive, 0 dead, 0 visible
- Tuna:           913 alive, 0 dead, 0 visible
- Turkey:         821 alive, 0 dead, 0 visible

Plants:
 - Waterweed:     34,658
 - Urchin:        45,592
 - Kelp:          45,477
 - Clam:          45,474
 - CommonGrass:   106,286
 - Tomatoes:      950
 - Bunchgrass:    1,326
 - Salal:         5,288
 - Buttonbush:    93
 - Birch:         238
 - Fern:          637
 - AmanitaMushroom: 63
 - Fireweed:      1,569
 - Huckleberry:   85
 - Cedar:         267
 - PitcherPlant:  18
 - CriminiMushroom: 46
 - Beets:         2

**Comment by metachronism** [comment]
migrating remaining issues to a new issue
