### ISSUE TITLE
No blocks in Tier 0

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3631]
There's much less tier clutter now, which is nice :) :P

**Comment by craig-jong** [comment]
There are intentionally no T0 blocks now.

I did notice there are some tables that request them so I removed those restrictions.

They still have to be in an enclosed room, though.

**Comment by MarjieAVolk** [comment]
Well if tier 0 isn't a thing, then we need to remove the tooltip for it.
