### ISSUE TITLE
Spawn Building needs updating

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3635]
Just need to rename the strings:

     {
                default: constructionType = BlockManager.FromTypeName("HewnLogWallBlock"); roofType = BlockManager.FromTypeName("HewnLogRoofBlock"); windowType = BlockManager.FromTypeName("ModernWoodWindowBlock"); break;
                case 1: constructionType = BlockManager.FromTypeName("MortaredStoneBlock"); roofType = BlockManager.FromTypeName("MortaredStoneRoofBlock"); windowType = BlockManager.FromTypeName("ModernWoodWindowBlock"); break;
                case 2: constructionType = BlockManager.FromTypeName("LumberBlock"); roofType = BlockManager.FromTypeName("LumberRoofBlock"); windowType = BlockManager.FromTypeName("ModernWoodWindowBlock"); break;
                case 3: constructionType = BlockManager.FromTypeName("BrickBlock"); roofType = BlockManager.FromTypeName("BrickRoofBlock"); windowType = BlockManager.FromTypeName("ModernWoodWindowBlock"); break;
                case 4: constructionType = BlockManager.FromTypeName("CorrugatedSteelBlock"); roofType = BlockManager.FromTypeName("CorrugatedSteelRoofBlock"); windowType = BlockManager.FromTypeName("SteelWindowBlock"); break;
                case 5: constructionType = BlockManager.FromTypeName("ReinforcedConcreteBlock"); roofType = BlockManager.FromTypeName("ReinforcedConcreteRoofBlock"); windowType = BlockManager.FromTypeName("SteelWindowBlock"); break;

**Comment by metachronism** [comment]
move to mods and use the tiers to build buildings instead - no strings!

**Comment by craig-jong** [comment]
this was all consolidated. Closing this issue.
