### ISSUE TITLE
USER ISSUE: Shovel not working correctly

### ISSUE THREAD

**Issue by Fangspawn** [StrangeLoopGames/EcoIssues#3638]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Equip Shovel and use on dirt. Place dirt somewhere. Try to use shovel on different, or same, dirt and doesn't work.
Work around currently used: After placing dirt unequip and requip shovel and use for one more dirt block. Repeat as needed.

**Expected behavior:**
Shovel should work continuously, without needing to requip it each time.

**Actual behavior:**
Shovel has to be requipped after each use.

**Comment by SeanAtr0n** [comment]
Hmm, tried this on 6.4.2, haven't been able to reproduce so far

**Comment by Fangspawn** [comment]
It's a weird glitch for me. I haven't played the game since 5.4 or so and
there may have been an issue when I updated. I could try to do a recording
of it?

**Comment by SeanAtr0n** [comment]
Sure, that'd be helpful or your error log from
C:\Users\username\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by Fangspawn** [comment]
![eco folder](https://user-images.githubusercontent.com/35825331/35425332-b94d01f6-021f-11e8-80e4-605de79fe7f2.PNG)

**Comment by Fangspawn** [comment]
Would it be in this folder? Sorry, been trying to find the log.

**Comment by Fangspawn** [comment]
https://youtu.be/Kc8TN8GW5ms
This is a link to the video for the issue. It shows that I'm clicking and not it isn't working right :/

**Comment by SeanAtr0n** [comment]
Just to double check... it still doesn't work if you hold down the mouse button? (looks like you might be clicking really fast in that video)

I think if you cut and paste this into file explorer it'll take you to the dir we would need output_log.txt from
%APPDATA%\..\LocalLow\Strange Loop Games\ECO

**Comment by Fangspawn** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1669761/output_log.txt)

**Comment by Fangspawn** [comment]
Sorry to take so long to reply. That link worked great obviously for the output log, so thank you for that. It happens with holding down the mouse button too. Also, it happens with full durability as well so idk what's happening with it. Thanks for looking into it for me :)

**Comment by SeanAtr0n** [comment]
still can't reproduce this... did it happen on every server or just one in particular?

**Comment by Fangspawn** [comment]
I just updated to 7.0 and it still happens. The server I'm with changed to a new server that's updated and I still have the issue :/ Every time I dig I have to switch back and forth on my tools to dig again. Should I uninstall all the Eco files I have and reinstall just the 7.0 version? I have ones from 5.4, 5.5-alpha-staging-9d5ca29f, 6.4.2, and the new 7.0.0 ones.

**Comment by Fangspawn** [comment]
Also, just tried switching back and forth on shovels and that doesn't work. Like having one hotkeyed and a second one hotkeyed. I have to switch to a different type of tool.
