### ISSUE TITLE
Wood pulp applying impression on stone road

### ISSUE THREAD

**Issue by ReiRay** [StrangeLoopGames/EcoIssues#3642]
http://puu.sh/z9SPx/878053d852.jpg

//Reproduce
I cut a tree down, and some of the pulp generated on the stone road

//Expected Behavior
Wood pulp should lay on top of stone

//Actual behavior
Stone is pushed down by wood pulp

**Comment by Conchipedia** [comment]
i sure this also does the same on Dirt Road, as i think the Roads are an extra part of a block that Debris ignores and then just turns it into a normal block to sit on

**Comment by Huntermeign** [comment]
Hoping my issue, #3582, would solve this similarly to how debris slightly hovers above ramps, it could slightly hover above roads, rather then leave a pothole until the debris is gone.
