### ISSUE TITLE
Concrete recipe prerequisites

### ISSUE THREAD

**Issue by valheran** [StrangeLoopGames/EcoIssues#3643]
Version 6.4.1
The requirement of the Concrete recipe of Cement Construction 1 (in the Stone Construction Specialisation) appears out of keeping with other similar recipes (Bricks, Mortared Stone, Reinforced Concrete) which are unlocked in the same line as their production bonus
The current situation thus requires 2 specialisations to produce concrete efficiently

Suggest altering Concrete recipe prerequisite to Cement Production 1

**Comment by LiaungYip** [comment]
![image](https://user-images.githubusercontent.com/2173684/35465077-43a1f5ac-0345-11e8-8079-27c402e76b2f.png)

**Comment by craig-jong** [comment]
This should be fixed now.

All the stone-product construction skills are in the same specialization intentionally (at least for now) and they should all now actually let you build new forms.

Cement itself got a bit of a skill changeup which should have solved the issues.
