### ISSUE TITLE
USER ISSUE: No ESC menu to get out of Server list if a server is not there to choose

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3644]
0.7.0.0-beta-staging-e27abc9c

![snap1297](https://user-images.githubusercontent.com/29383891/35437659-5ae786a6-028b-11e8-9f1e-bef96bfba04f.png)

Tried logging into Hoary Marmot on latest Staging, No server found in the list, i can view incompatible servers, Configure, Add Server and Refresh but cannot get any menu by pressing ESC key. 
To exit this **only** thing i can do is Press ALT+F4 or End process to quit

**Comment by Conchipedia** [comment]
just checked this **was** working fine on 0.7.0.0-beta-staging-b1111b5c

**Comment by metachronism** [comment]
hmmm I can't repro this - could you give it another shot?

**Comment by Conchipedia** [comment]
whatever you had changed to make this happen you must have fixed in later versions as it seemed to have been a one off thing that happened in **ONLY** this Staging version
