### ISSUE TITLE
[Exception] EX during world loading if world layer cannot be divided evenly

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3645]
Imported an 6.4.2 world into 7.0.0-beta-staging-b1111b5c server.
[Crash AggregateException 01263110.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1667575/Crash.AggregateException.01263110.zip)

**Comment by jarckn** [comment]
Reproducable on #e27abc9c.

**Comment by knexer** [comment]
Right, this constraint should be enforced at worldgen time and not when loading an existing world.  Will fix.

**Comment by metachronism** [comment]
closing as wont fix, an error message is correctly displayed now though
