### ISSUE TITLE
Issue with Targeting and having things stacked picture display issue.

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3649]
tree fell on top of stock pile anytime  i try to chop tree it just targets the stock pile.

it is really hard to pin point target things u want to hit or pick up in this game so far so for now tree is permanent part of my stock pile - even if i remove the chest i can not push it or pull it or target it.

![20180126120500_1](https://user-images.githubusercontent.com/15990789/35453874-53397b8e-0291-11e8-8532-5888642809f1.jpg)

**Comment by Conchipedia** [comment]
filling a stock pile to max will normally Fling things off

**Comment by midn8t** [comment]
yah that did not happen all happen is that thing goes up and down with the stock pile. be nice to have a small target recital like dot or something as an option that can be enabled or disabled so can just pin point target stuff instead of just not being able to target what u want to target to pick up or move or work with.

**Comment by Conchipedia** [comment]
once a stockpile is full to the Max it acts like a floor and you can stand on it and target stuff that has fallen onto it, you only target the stockpile if you look directly down at it while standing on the top

**Comment by midn8t** [comment]
well after all this time screwing around with it i finally was able to target it and get it cut up

now there just a single log i cant see target and isntead of going up and down with pile it just decided to drop into the pile so yah.

![20180126135101_1](https://user-images.githubusercontent.com/15990789/35458174-fadc44a2-02a0-11e8-84f4-64b398404125.jpg)

**Comment by metachronism** [comment]
this is fixed in beta already actually
