### ISSUE TITLE
[Suggestion] Doing more with Glass (Keegan)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3650]
because we can make pyramids i remembered **Louvre Pyramid** from a film i was watching
![louvre_museum_wikimedia_commons](https://user-images.githubusercontent.com/29383891/35457353-84d60a6a-02d0-11e8-93c7-b677737810f0.jpg)
Glass Flooring (at the moment we can do floor but you cannot pull a cart over it as it is sunken)
![inside_brooklyn_museum_img_3839](https://user-images.githubusercontent.com/29383891/35457543-2cc7c3da-02d1-11e8-99e0-839b6d4e6438.JPG)
Even Stairs are possible with glass
![steel-spine-staircase](https://user-images.githubusercontent.com/29383891/35457630-79187ea0-02d1-11e8-8432-3764b8a96678.jpg)

Will leave the Fine Details up to you

**Comment by keegan-o** [comment]
Worry not my friend, Framed Glass is indeed planned and locked in-- For beta we may only get Walls and Floors for it, but stairs and slopes that allow the pyramid will 100% happen! :)

**Comment by MarjieAVolk** [comment]
Okay so I'm gonna close this bug, since we've got these features already tracked in the art spread sheet or whatever
