### ISSUE TITLE
Tutorials shouldn't give an item if you already have the better version from the specialty

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3651]
- chose logging as a specialty as per first tutorial
- it then started the logging tutorial, which gave me another axe
- new tutorial kept telling me to use the crappy axe

Not sure how you want to handle this but other feedback
- giving an iron axe for free at the start of the game seems overly generous
- tutorial should more generically refer to "Axe" instead of specifically "Stone Axe" to fix instances if user has 2+ axes

**Comment by Conchipedia** [comment]
i agree with **not** giving iron tools for two reasons

1: they last too long and don't force player to make others or repair it (see reason 2)
2: they cannot be repaired until Iron Ingots are being made
