### ISSUE TITLE
USER ISSUE: Webserver fails to start for solo game in 6.4.2

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3656]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Start any solo game with a pre existing game save

**Expected behavior:**
webserver should start so that a webpage will generate

**Actual behavior:**
webserver fails to initialize.  This error in console:  Failed to start Webserver: Exception has been thrown by the target of an invocation.

**Comment by metachronism** [comment]
this is the netsh http error.  new users shouldn't get into this state, you may need to netsh delete the urlacl
