### ISSUE TITLE
USER ISSUE: 7.0. Staging #E27abc9c Alpha Rewards

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3658]
I maybe a bit a head of you on this but should we get alpha rewards when joining a game in staging?  If so should that just be new worlds or worlds updated form 6.4.2 also?  Also I was able to locate the goggles and the shard but the Steampunk hat does not seem to be an item of clothing at this time.  I notice that goggles show on avatar in third person but the shard does not

**Comment by SeanAtr0n** [comment]
rewards are given when joining new worlds, the hat's name is alphahat, shard shows up after changing equipment
