### ISSUE TITLE
USER ISSUE: Another Players Boots Appear above their head

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3660]
**Version:** 0.7.0.0 beta staging-9488ed17

**Steps to Reproduce:**
Just look at another player then back away from them and their boots just rise up above their head

![snap1308](https://user-images.githubusercontent.com/29383891/35472763-42323966-036d-11e8-8e0e-12b234d4c9dc.png)
![snap1309](https://user-images.githubusercontent.com/29383891/35472768-609bc7be-036d-11e8-8ec9-2e7a84fe0e87.png)

and when they move away all you see is their boots running 😂

**Comment by SeanAtr0n** [comment]
fixed in next build
