### ISSUE TITLE
USER ISSUE: [Art] Nutrition Window not quite central

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3662]
**Version:** 0.7.0.0 beta staging-9488ed17

![snap1312](https://user-images.githubusercontent.com/29383891/35472872-1e5b5728-036f-11e8-9458-9dd21b28b821.png)
When it is full looks a bit untidy

**Comment by MarjieAVolk** [comment]
@MilenkoTunjic People have been noting that the nutrition pie looks asymmetrical.  The bit dark shadow around the top right side of the inner rim looks like it's part of the background while the pie is smaller than full, but of course looks like part of the foreground when the pie is full, so it's hard to get it to look good in both cases

**Comment by MarjieAVolk** [comment]
Fixed in next staging.  Hopefully.  I should get someone else to do this for me, I have a centering impairment.
