### ISSUE TITLE
USER ISSUE: Trees are growing too close together and growing through each other

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3664]
**Version:** 0.7.0.0 beta staging-9488ed17

![snap1315](https://user-images.githubusercontent.com/29383891/35473234-ae523630-0374-11e8-865a-2959969ad954.png)
![snap1316](https://user-images.githubusercontent.com/29383891/35473235-ae693d12-0374-11e8-9ee4-956294c7ff34.png)
![snap1317](https://user-images.githubusercontent.com/29383891/35473236-ae80ed04-0374-11e8-8c27-d8534e4b8e55.png)
![snap1318](https://user-images.githubusercontent.com/29383891/35473237-ae97b8a4-0374-11e8-8f9d-d7902b63e01c.png)
![snap1319](https://user-images.githubusercontent.com/29383891/35473272-af1b909c-0375-11e8-8400-5e4c0242a863.png)

this is **not** limited to same type of tree and can make harvesting the logs a bit more difficult than it needs to be

**Comment by MarjieAVolk** [comment]
This should be fixed in the next staging release
