### ISSUE TITLE
USER ISSUE: Tutorials Not closing when done also cannot close them manually

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3665]
**Version:** 0.7.0.0 beta staging-9488ed17

![snap1321](https://user-images.githubusercontent.com/29383891/35473373-8e446d1a-0377-11e8-899d-59451de7ae66.png)
![snap1322](https://user-images.githubusercontent.com/29383891/35473374-8e5e108a-0377-11e8-95d7-dba28bfc0cd1.png)
![snap1323](https://user-images.githubusercontent.com/29383891/35473375-8e7a8eae-0377-11e8-821d-a9a39a0a3e08.png)
![snap1324](https://user-images.githubusercontent.com/29383891/35473376-8e97c4c4-0377-11e8-96b9-dbfc8a9718e6.png)
![snap1325](https://user-images.githubusercontent.com/29383891/35473377-8eaf87da-0377-11e8-83b9-1971995e7eed.png)

Disconnecting **WILL** close the finished Tutorials as can be seen below the **only** ones open now are ones that are **not** completed yet.
![snap1326](https://user-images.githubusercontent.com/29383891/35473425-639ed54a-0378-11e8-88e4-6a4a7a9cae9d.png)

**Comment by johnkslg** [comment]
Could not repro in latest, reopen if still happening.
