### ISSUE TITLE
USER ISSUE: Hammer menu should be more in order of Skill required to make things clearer of what is needed to learn

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3666]
**Version:** 0.7.0.0 beta staging-9488ed17

![snap1327](https://user-images.githubusercontent.com/29383891/35473450-d9e722b6-0378-11e8-99c3-9b3b096e963e.png)
![snap1328](https://user-images.githubusercontent.com/29383891/35473451-da00fe20-0378-11e8-8a40-c236f6d9b837.png)
![snap1329](https://user-images.githubusercontent.com/29383891/35473452-da19ab32-0378-11e8-84b3-f1658abfa7fb.png)
![snap1330](https://user-images.githubusercontent.com/29383891/35473453-da31ef1c-0378-11e8-8553-49657fc77265.png)
![snap1331](https://user-images.githubusercontent.com/29383891/35473454-da49621e-0378-11e8-8d2c-b372342e667f.png)
maybe starting with the ones without needing a skill at the bottom so the further up the window you go the more skill is required

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#304
