### ISSUE TITLE
USER ISSUE: Chopping fallen trees into logs is getting more harder to do as the pieces seem to be getting thinner and thinner untill allowed to be picked up

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3667]
**Version:** 0.7.0.0 beta staging-9488ed17

![snap1332](https://user-images.githubusercontent.com/29383891/35473555-10c9dd40-037a-11e8-9af9-f85d50f1a469.png)
![snap1333](https://user-images.githubusercontent.com/29383891/35473556-10e4d8fc-037a-11e8-8576-d59fbaac8245.png)
![snap1334](https://user-images.githubusercontent.com/29383891/35473557-10fe115a-037a-11e8-9742-d775aaacf857.png)
this is 1 log
![snap1342](https://user-images.githubusercontent.com/29383891/35474317-78ec4656-0384-11e8-98d5-d2d9c29efb31.png)
this is 3 logs

**Comment by Conchipedia** [comment]
![snap1341](https://user-images.githubusercontent.com/29383891/35473934-f0a3d016-037e-11e8-8f13-561d114f2598.png)
i had to dig down a block **just** to be able to attempt to chop this into pieces as it was laying flat and was to thin to do on surface

**Comment by Conchipedia** [comment]
Quitting game and coming back seemed to make all the logs that needed to be cut thin turn into a size that could be picked up

**Comment by SeanAtr0n** [comment]
think this has to do w/ plant yield being messed up

**Comment by knexer** [comment]
This was resolved in https://github.com/StrangeLoopGames/Eco/pull/2336
