### ISSUE TITLE
USER ISSUE: all my chopped Trees are floating up in the air

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3668]
**Version:** 0.7.0.0 beta staging-9488ed17

Disconnected to try and fix a fallen tree not being able to be chopped that fell onto workbench now all my Chopped pieces are floating or rising into the air
![snap1335](https://user-images.githubusercontent.com/29383891/35473719-e1ae0c14-037b-11e8-9240-7b66150967a8.png)
![snap1336](https://user-images.githubusercontent.com/29383891/35473720-e1c5ed3e-037b-11e8-8716-eb8f7c8885ae.png)
![snap1337](https://user-images.githubusercontent.com/29383891/35473721-e1dca2fe-037b-11e8-9b5f-d7298631f256.png)
![snap1338](https://user-images.githubusercontent.com/29383891/35473722-e1f3c6b4-037b-11e8-8e83-1f0b2dd97a58.png)

did this after i had problems chopping trees smaller in
**USER ISSUE: Chopping fallen trees into logs is getting more harder to do as the pieces seem to be getting thinner and thinner until allowed to be picked up** #3667

i can also jump on the floating pieces

**Comment by Conchipedia** [comment]
going to link all my Tree stuff together as it all seems related somehow and i also saw this linked to a Tree that is full grown but only giving 1 log (that is also happening now occasionally)
World layers issues #3630
USER ISSUE: Chopping fallen trees into logs is getting more harder to do as the pieces seem to be getting thinner and thinner untill allowed to be picked up #3667

**Comment by Conchipedia** [comment]
on search for food the floating tree bits will fall back to earth when you come close to them

**Comment by Huntermeign** [comment]
This may or may not be related but on Facebook someone post this for 6.4.2

found a floating log but when i cut it it floated away XD, so i cut it again and my game crashed and i got this error
Caught exception: Caught exception invoking RPC PlayerInteract on Player!
Object reference not set to an instance of an object.
Stack:
at TreeEntity.PickupLog(Player player, Guid logID)
at TreeEntity.OnActInteract(InteractionContext context)
at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Comment by SeanAtr0n** [comment]
I still haven't been able to reproduce the flying trees... any clues on how to make it happen would be helpful.

**Comment by Huntermeign** [comment]
It happened in 6.2 as well for me and I noticed a couple things with trees which may be related to this. When leaving an area a far distance and returning later this would happen to a tree. Especially if something was built next to or above it. Sometimes chopping a tree but not splitting it, leave the area and then return, the tree would return to its stump and fall over again. Finally, if an admin flattened land after a tree was felled near/on the area, sometimes splitting the tree would cause a the client to leave the server with an error. Upon return, the tree would be split but for each cut the player would be forced out of the game back to the server list.

**Comment by MarjieAVolk** [comment]
FYI we got another report with that same stack trace and also flying logs, so seems likely they are related

**Comment by MarjieAVolk** [comment]
I had been assuming that the exception caused the floating logs, but I think it might be the other way around.  The logs are broken somehow, which causes them to float/drift and also causes the exception

**Comment by MarjieAVolk** [comment]
Another thing that seems to come up in a lot of reports of this issue, is that the logs were left lying around, perhaps across a server reload

**Comment by hannahbex** [comment]
This issue occurs again -> http://ecoforum.strangeloopgames.com/topic/3415/sent-back-to-main-menu-after-mining

**Comment by MarjieAVolk** [comment]
Another person suggested that when this happened to them, the log they were interacting with should not have been there.  That is, it was from a tree that they cut down earlier, and had already harvested all the logs from.

**Comment by MarjieAVolk** [comment]
Oh, since it isn't explicitly stated here, such floating logs throw on both TrySliceLog and PickupLog with null refs.

**Comment by Kastuk** [comment]
My lumber are flied away with low gravity ascending after cutting little piece of old log on the slope (edge of cliff). Slighty tilted before cut. Little part dropped back after ~30 m of flying. Other's just hovering and dropped after server restart.

**Comment by SeanAtr0n** [comment]
fixed 7.2
