### ISSUE TITLE
6.4.1 uses a lot more CPU then before and still having daily crashes

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3669]
Not sure how to help yall with this one, since i am not getting a lot of crash reports if any and its mostly just locking up the server. i can upload the whole server? 
![2018-01-27 2](https://user-images.githubusercontent.com/20627148/35474811-a92dfcbc-0350-11e8-8923-7f91aa727f2b.png)

![2018-01-27 1](https://user-images.githubusercontent.com/20627148/35474837-09b259e8-0351-11e8-9a18-ebb916d3fc3d.png)

**Comment by stormoffires** [comment]
3 crashes today alone and only 1 report

--BEGIN DUMP--
Dump Time
01/27/2018 10:45:22

Exception
System.Exception: Caught exception invoking RPC SendChat on ChatManager!

Object reference not set to an instance of an object.


Stack:
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, Int32 playerID)

   at Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   at Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   at Eco.Shared.Networking.RPCManager.HandleReceiveRPC(INetClient client, BSONObject bson)
   at Eco.Shared.Networking.NetPort.ProcessBuffer()
   at Eco.Shared.Networking.NetPort.Update()
   at Eco.Plugins.Networking.Clients.Client.<.ctor>b__50_0()

--END DUMP--

**Comment by stormoffires** [comment]
![2018-01-28 2](https://user-images.githubusercontent.com/20627148/35486847-3fea9800-0431-11e8-90ce-2e388ee19ed2.png)

another common crash, however when i click "close" the pop up window goes away and the server continues to workish... gets really laggy after that. If i restart the server the lag goes away. No dump or error reports i could find

**Comment by metachronism** [comment]
seen that EcoServer has stopped working issue too, I think its the webserver crashing since it doesnt take down the rest of the server with it.

**Comment by stormoffires** [comment]
![2018-01-31](https://user-images.githubusercontent.com/20627148/35621318-2dd973ea-0641-11e8-86ba-1ca733e560fb.png)

more crashing... is this the same thing meta?

**Comment by stormoffires** [comment]
seems adding more players as well to the server did not help, we hit almost 12 active at the same time... crashed the server and sucked up the CPU

![2018-01-31 4](https://user-images.githubusercontent.com/20627148/35660253-32364972-06c8-11e8-877e-a9dbced0d45f.png)

**Comment by metachronism** [comment]
most of this should be resolved with 7.0

**Comment by stormoffires** [comment]
not sure if you will see this i know its closed, but well done with 7.0.4 and 13 folks online its only at 88% (hopefully we keep it around that)

**Comment by MarjieAVolk** [comment]
We always see :P
