### ISSUE TITLE
USER ISSUE: Tutorial "Choose Roles" comes to early

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3672]
**Version:** 0.7.0.0 beta staging-9488ed17

movement comes up, then meteor, now it says choose role, but shouldn't the map, chopping trees, craft hewn logs, mining, eating and building house and making Research table etc. come way before what a player decides to do?
how will a player know what **ROLE** he wants until he has built a house, used an axe, mined some stone and dug some dirt, eaten and gotten a feel for the basic game?

I skipped this one so the others will appear

**Comment by johnkslg** [comment]
Thanks for the feedback, it's a good point. I'll look into it.
