### ISSUE TITLE
Deed Title

### ISSUE THREAD

**Issue by Bob-Clarke** [StrangeLoopGames/EcoIssues#3675]
I proposed a law referencing a deed/area. Afterward changing the deed title crashed the server ( 6.4.2 )

**Comment by MarjieAVolk** [comment]
I tested this out, and I'm not seeing a problem.  When I change my deed title, the law text updates everywhere as expected.

What did you change the deed title to?  This might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/2760

**Comment by MarjieAVolk** [comment]
Also a game save might help

**Comment by Bob-Clarke** [comment]
I had set the text to; <color=black>THe Forbidden Zone
I then changed it to ;<color=black>The Forbidden Zone
And I have been able to reproduce. 
With it crashing again, though this time I got to see the error; The '=' character, hexadecimal value 0x3D, cannot be included in a name. Line 1, position 96.
Do you still need the save?

**Comment by MarjieAVolk** [comment]
Ahaaaa using markup.  I haven't tried that yet.  One sec I will mess with it more, if that still doesn't work then the save will be the next thing I'll try

**Comment by MarjieAVolk** [comment]
Okay I've been able to get some error messages with the '=' in the name.  And I've been able to fix those. 
 Although I think they were all debug messages and shouldn't have caused the server to crash?  In which case I might not have solved the exact thing you were seeing.  What are you doing when the server crashes?

**Comment by Bob-Clarke** [comment]
I don't think there were any active projects or anything going on. So I'm not sure. I had just found a spot to put the tailings after much digging. I think I was only making this zone/law so it didn't get dug into
