### ISSUE TITLE
USER ISSUE: Quite a Few Menu Buttons are NOT working or are hidden

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3678]
**Version:** 0.7.0.0 beta staging-73643fd0

![snap1354](https://user-images.githubusercontent.com/29383891/35482371-f9987764-042b-11e8-8411-0ec3ecf8b2bb.png)

Using Quit ingame has the "Are you Sure you want to quit?" hidden behind the graphic sliders as seen above, but pressing Y or N **will** work.

![snap1355](https://user-images.githubusercontent.com/29383891/35482452-5aaf88e8-042d-11e8-929e-c2c19092ebf3.png)
![snap1356](https://user-images.githubusercontent.com/29383891/35482453-5ac7aaa4-042d-11e8-9a8d-d7cfc8f9cf12.png)

When Loading a created world the name(s) comes up but clicking mouse on (green) name will not load it but pressing return key will.

![snap1357](https://user-images.githubusercontent.com/29383891/35482459-7b3aa16a-042d-11e8-87a5-f0a50d1b2012.png)

Quit key on Main Menu not working with left mouse button but hitting Return **Twice** will quit game (no sub menu of "Are You Sure" is visible)
![snap1358](https://user-images.githubusercontent.com/29383891/35482467-9a1bd6c6-042d-11e8-8ee4-9491500e0fd5.png)

Confirm button hidden behind the Counter

linking this one as it is same problem
**USER ISSUE: Resolution window is not working properly #3661**

**Comment by metachronism** [comment]
fixed
