### ISSUE TITLE
USER ISSUE: Single Player World Watched All Plants Die

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3680]
**Version:** 0.7.0.0 beta staging-73643fd0

![snap1359](https://user-images.githubusercontent.com/29383891/35483184-137b970a-0437-11e8-8fac-2469ce01895b.png)

I started a Stopwatch when i logged in for the first time on a newly created World as was curious to When the Plants Will disappear (as i knew there was this bug)  but they actually die and it only took just under 10 Minutes (about 9 minutes 40 seconds give or take a few)

Would this be the First Tick of the World that is Mentioned in this (World layers issues #3630)?

**Comment by Conchipedia** [comment]
Managed to work out how to make myself Admin in Singleplayer as i wanted to try out some stuff, i managed to plant some stuff, but they all died withina few minutes of planting
![snap1375](https://user-images.githubusercontent.com/29383891/35485630-5c1e21e4-045a-11e8-8495-d1c75273f68d.png)

**Comment by Conchipedia** [comment]
tested Plants with Soil Sampler and noticed something i haven't seen before **Layer Value**
so took a few readings and quite a few a different
![snap1384](https://user-images.githubusercontent.com/29383891/35485821-cbab9684-045c-11e8-8639-5717daf19aba.png)
![snap1385](https://user-images.githubusercontent.com/29383891/35485822-cbc481da-045c-11e8-9b35-f34806a719fe.png)
![snap1386](https://user-images.githubusercontent.com/29383891/35485823-cbdd0e08-045c-11e8-95d2-e8efbcf180b9.png)
![snap1387](https://user-images.githubusercontent.com/29383891/35485824-cbf51fb6-045c-11e8-83d5-391282198f20.png)

**Comment by knexer** [comment]
I haven't been able to reproduce every plant dying on the first world layer tick.  Did you restart the server in between? There might still be some weirdness around how world layers save right after worldgen.

The second bug reported here (planted plants dying) is fixed with https://github.com/StrangeLoopGames/Eco/pull/2340

**Comment by Conchipedia** [comment]
this is on Marmot server in a created world prior to them reloading in the world we have now
