### ISSUE TITLE
[Staging-73643fd0] Waypoints not showing in world

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3683]
When dropping waypoint in the staging 73643fd0 build, they show up on the mini-map but do not show up in the world.
![eco 1_28_2018 9_37_50 am](https://user-images.githubusercontent.com/1503963/35484711-cd302c08-0421-11e8-8f6f-7da26f21198a.png)

**Comment by metachronism** [comment]
fixed
