### ISSUE TITLE
USER ISSUE: unlearn Window hidden behind Skill window

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3684]
**Version:** 0.7.0.0 beta staging-73643fd0

**Steps to Reproduce:**
just try and unlearn anything

**Expected behavior:**
window should appear in front of skill window

**Actual behavior:**
Unlearn window appears behind the skill window, which can be dragged to see the other one, but if you attempt to click on the other window both windows vanish.
![snap1390](https://user-images.githubusercontent.com/29383891/35486065-73abdbe8-0460-11e8-84c2-fba5fc81fd30.png)

if you type y for yes it will unlearn but also then open the Economy viewer

**Comment by metachronism** [comment]
fixed
