### ISSUE TITLE
USER ISSUE: Road Tool Requires Wood Construction 1 but wants stone for repair

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3685]
**Version:** 0.7.0.0 beta staging-73643fd0

![snap1391](https://user-images.githubusercontent.com/29383891/35486224-c3f54a6a-0462-11e8-8d78-d4543c13efc4.png)
![snap1392](https://user-images.githubusercontent.com/29383891/35486264-52778992-0463-11e8-994a-e841e67cf97b.png)
Seeing as this was made from 4 Boards why would we repair it with Stone??

**Comment by craig-jong** [comment]
Fixed by moving the road tool.
