### ISSUE TITLE
USER ISSUE: Hammer Hewn Logs Building blocks pointing at wrong skill

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3686]
**Version:** 0.7.0.0 beta staging-73643fd0
![snap1393](https://user-images.githubusercontent.com/29383891/35486376-09613904-0465-11e8-8985-9950d7bdc4b3.png)

When you click on **Hewn Log Construction** it highlights **Wood Construction** as can be seen above
![snap1394](https://user-images.githubusercontent.com/29383891/35486384-24d7e1ba-0465-11e8-9388-79421fa48954.png)
but it should be looking at this so (which if you learn actually adds stuff to the hammer)

So the Tooltip is correct also the skill to learn but the link is wrong

**Comment by MarjieAVolk** [comment]
????

**Comment by MarjieAVolk** [comment]
Oh, Hewn Log Construction is inside Wood Construction.  So it should highlight both.  So it's not so bad, haha.  Alright, I can repro this.  The highlight seems to work when I have not taken the specialty, but if I've taken it then it doesn't highlight.  Strange

**Comment by MarjieAVolk** [comment]
Oh no I am wrong.  It does not work if you had that same specialty already open in the skills window.  Otherwise it does work.  Straaaaange

**Comment by elfl0rd** [comment]
@D3nnis3n as i know - "construction" skills removed.

**Comment by D3nnis3n** [comment]
Indeed.
