### ISSUE TITLE
World layer issues

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3688]
- [x] Need Oak/Fir/Cactus
- [x] Planted plants should not die, only have terrible/low yields in non-ideal conditions
- [x] Tree debris is not preventing biome reclaimation
- [x] Need way to better balance species density in different biomes (less dense trees in grassland vs forest)
- [x] Tree yield shouldn't be a thing
- [x] Plant stats aren't being collected #3677

**Comment by knexer** [comment]
https://github.com/StrangeLoopGames/Eco/pull/2340 makes partial progress on ticks 2, 4, and 6.
- Plants still die (or migrate) too quickly in non-ideal conditions, but it's no longer instant.
- The sparsity floor is gone, so sparse trees in the grassland is a lot easier to achieve now.
- We are correctly calculating the value that should probably be recorded for the plant stat now (layer.ActualResolutionAdjustedTotal).

**Comment by knexer** [comment]
https://github.com/StrangeLoopGames/Eco/pull/2347 plant stats are fixed

**Comment by knexer** [comment]
https://github.com/StrangeLoopGames/Eco/pull/2348 addressed tick 2 - plants still die, but it's slow and it's intended

**Comment by knexer** [comment]
Tick 4 is addressed for purposes of beta, we may revisit it after beta

**Comment by knexer** [comment]
Oak/fir/cactus are all ingame, but have some issues being tracked separately - ticking off tick 1
