### ISSUE TITLE
[Staging-73643fd0] Chopping 3 logs from a tree allows you to pickup the rest of the tree

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3689]
1. Fell a tree
2. Chop 3 logs from tree trunk
3. Now you can pick up the rest of the tree without chopping, but you don't get any logs from it.

**Comment by MarjieAVolk** [comment]
I assume this is a yield problem, thus assigning to @knexer.  If that is not the case, assign it back to me

**Comment by knexer** [comment]
The yield issues have been resolved now - this should not be a problem any more (as of latest master).
