### ISSUE TITLE
ModKit and Global Illumitation

### ISSUE THREAD

**Issue by Phlo123** [StrangeLoopGames/EcoIssues#3690]
![gi_on](https://user-images.githubusercontent.com/17730996/35492955-7dbc2022-04b8-11e8-94b2-f47a8c004853.png)
![gi_off](https://user-images.githubusercontent.com/17730996/35492956-7ddac2c0-04b8-11e8-8a6f-899cbf10918a.png)
These are the same objects in-game, the difference is Global Illumination is enabled in the picture with the blue/purple colors. The burnt looking area is the emission texture of the material.

**Comment by metachronism** [comment]
@Phlo123 can you attach your models/textures to this bug?  (FBX ideally?)

**Comment by Phlo123** [comment]
[Neon.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1675419/Neon.zip)
fbx + albedo and emission .psd

**Comment by metachronism** [comment]
sean added support for this
