### ISSUE TITLE
Seasons? [Suggestion]

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3692]
Might be a bit of a stretch to suggest, but could seasons be a thing?

- Each day is a season so every 4 days is a full cycle
- Spring: More animal reproduction, tree leaves grow back, rain levels increase.
- Summer; Rain levels decrease, certain animals migrate to wooded areas to stay cool (could create use for the bucket?)
- Fall; Tree leaves different color, crops yield more.
- Winter: Grass blocks turn into snow blocks for the day, colder weather for crops, trees go barren.

Would promote:
- Planning ahead for agriculture (Some plants could die without being watered on summer days, or drown if watered on spring days)
- Planning ahead for future husbandry (higher chance to breed on spring days)
- Planning ahead for hunting (allow option for open or closed seasons in law based on seasonal days)
- Snow men decor that lasts for the day.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#303
