### ISSUE TITLE
Minimizing the game...

### ISSUE THREAD

**Issue by LucianoBradley** [StrangeLoopGames/EcoIssues#3693]
Minimizing the game causes this issue also I can only get around 25 fps even on low settings while in earlier versions I was around 55 fps.

Eco [version: Unity 2017.3.0f3 (a9f86dcd79df)]

d3d11.dll caused an Access Violation (0xc0000005)
  in module d3d11.dll at 0033:c8024964.

Error occurred at 2018-01-29_104124.
D:\Eco\Eco.exe, run by JohnS.
14% memory in use.
32707 MB physical memory [27955 MB free].
37571 MB paging file [30901 MB free].
134217728 MB user address space [134214445 MB free].
Read from location 00000109 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x0000001c  RAX:   0x0c6010b8
RBX:    0x4a0de380  RCX: 0x0c6010b8  RDX:   0x00000000
RIP:    0xc8024964  RBP: 0x64cfe889  SegCs: 0x00000033
EFlags: 0x00010202  RSP: 0x64cfe7d0  SegSs: 0x0000002b
R8:    0x00000000  R9: 0x00000004  R10:   0x0c6010c0
R11:    0x64cfe750  R12: 0x00000000  R13:   0x00000000
R14:    0x893685a0  R15: 0x89368590

Bytes at CS:EIP:
48 0f be 82 09 01 00 00 4c 8d 91 e8 fe ff ff 48 

Stack:
0x64cfe7d0: 4a0de380 00000289 c7edaf42 00007ffb ...J....B.......
0x64cfe7e0: 938f4d20 00007ffb 00000001 00000000  M..............
0x64cfe7f0: 00000003 00000000 0000d458 00000000 ........X.......
0x64cfe800: 00000000 00000000 00000000 00000000 ................
0x64cfe810: 00000000 00000000 931cd8ba 00007ffb ................
0x64cfe820: 00000000 00000000 cb103bdd 00007ffb .........;......
0x64cfe830: 64cfe889 0000008e 00000001 00000000 ...d............
0x64cfe840: 00000000 00000000 64cfe880 0000008e ...........d....
0x64cfe850: 00000540 00000002 00000008 00010000 @...............
0x64cfe860: 00000000 00000000 00000002 00000001 ................
0x64cfe870: 00000000 00000054 00000000 00000000 ....T...........
0x64cfe880: 00000000 00000000 ffffffff ffffffff ................
0x64cfe890: 85ebe808 00000289 92a12a72 00007ffb ........r*......
0x64cfe8a0: 0fbd9d50 00000289 00000000 00000000 P...............
0x64cfe8b0: 00000000 00000000 00000000 00000000 ................
0x64cfe8c0: 00000000 00000000 00000000 00000000 ................
0x64cfe8d0: 00000000 00000000 00000000 00000000 ................
0x64cfe8e0: 64cfea30 0000008e 931c8222 00007ffb 0..d....".......
0x64cfe8f0: 00000000 00000000 4a0de2c0 00000289 ...........J....
0x64cfe900: 0efd5d90 00000289 89368590 00000289 .]........6.....
0x64cfe910: 0fbd9d50 00000289 931e7409 00007ffb P........t......
0x64cfe920: 85eb5e60 00000289 0efd5d90 00000289 `^.......]......
0x64cfe930: 005f89d0 00007ffb 00800000 00000000 .._.............
0x64cfe940: 00000000 00000289 00000801 00000289 ................
0x64cfe950: 00000001 0000008e 00000083 00000289 ................
0x64cfe960: 00000001 0000008e 00000003 0000008e ................
0x64cfe970: 00000000 0000008e ffffffff 00000000 ................
0x64cfe980: 64cff510 0000008e 64cff4d0 0000008e ...d.......d....
0x64cfe990: 64cff770 0000008e 64cff730 0000008e p..d....0..d....
0x64cfe9a0: 64cffbf0 0000008e 00000000 00000000 ...d............
0x64cfe9b0: 005f897c 00000000 00000000 00000000 |._.............
0x64cfe9c0: 540aaa01 00000009 49fc1180 00000289 ...T.......I....
0x64cfe9d0: 00000000 00000000 00000000 00000000 ................
0x64cfe9e0: 00000001 00000000 005f80fc 00000000 .........._.....
0x64cfe9f0: 005eb37c 005eb360 005eaa50 005eaa4c |.^.`.^.P.^.L.^.
0x64cfea00: 005eaa58 005eaa54 005eafa0 005eaf9c X.^.T.^...^...^.
0x64cfea10: 005eac7c 005eac78 000cebe8 000cebe0 |.^.x.^.........
0x64cfea20: 004a1170 004a1168 0061a2e0 0061a2d8 p.J.h.J...a...a.
0x64cfea30: 00784ee8 00784ee0 005f8140 005f8138 .Nx..Nx.@._.8._.
0x64cfea40: 005f8150 005f8148 005f8170 005f8168 P._.H._.p._.h._.
0x64cfea50: 005f8174 005f8170 005f8160 005f8158 t._.p._.`._.X._.
0x64cfea60: 005f7f84 005f7f80 005f77a4 005f7764 .._..._..w_.dw_.
0x64cfea70: 005f7f7c 005f7f3c 005f7f38 005f7ef8 |._.<._.8._..~_.
0x64cfea80: 00000000 00000000 005eb234 005eb230 ........4.^.0.^.
0x64cfea90: 005eb238 005eb234 005eb278 005eb238 8.^.4.^.x.^.8.^.
0x64cfeaa0: 00000000 00000000 00000000 00000000 ................
0x64cfeab0: 00000000 00000000 00000000 00000000 ................
0x64cfeac0: 00000000 00000000 005eab58 005eab54 ........X.^.T.^.
0x64cfead0: 005f8584 005f8574 005de10c 005de0fc .._.t._...]...].
0x64cfeae0: be0001bf 00000000 0000001a 00000000 ................
0x64cfeaf0: 00000000 00000000 00000000 00000000 ................
0x64cfeb00: 005e9c6c 005e9c68 005e9c94 005e9c6c l.^.h.^...^.l.^.
0x64cfeb10: 005f7b40 005f7b38 005f7c0c 005f7b40 @{_.8{_..|_.@{_.
0x64cfeb20: 10806d90 00000289 ce886a99 00007ffb .m.......j......
0x64cfeb30: 005f8080 005f8020 005f80f8 005f8134 .._. ._..._.4._.
0x64cfeb40: 005f80fc 00000000 10670000 005e8d4c .._.......g.L.^.
0x64cfeb50: 005e8d48 005e8d58 005e8d50 005e8d60 H.^.X.^.P.^.`.^.
0x64cfeb60: 005e8d58 0049e350 0049e340 00000000 X.^.P.I.@.I.....
0x64cfeb70: 106703e0 00000289 64cfeb88 0000008e ..g........d....
0x64cfeb80: 00000000 00000000 00000003 00000000 ................
0x64cfeb90: 00000000 00000000 00000000 00000000 ................
0x64cfeba0: 00000000 00000000 0c56c320 00000289 ........ .V.....
0x64cfebb0: 00000000 005edfa0 005edf9c 005f8958 ......^...^.X._.
0x64cfebc0: 005f8950 005f895c 005f8958 005f8960 P._.\._.X._.`._.
0x64cfebd0: 005f8960 0000008e a23a4418 00007ffb `._......D:.....
0x64cfebe0: 10806da0 00000289 0c56c320 00000289 .m...... .V.....
0x64cfebf0: ce9cf3b0 00007ffb 64cffc90 0000008e ...........d....
0x64cfec00: 10806da0 00000289 a2241d6b 00007ffb .m......k.$.....
0x64cfec10: 88dd1d19 0000bd9b 00000190 00000000 ................
0x64cfec20: 0053b628 005f82c8 005f82c0 005cdf48 (.S..._..._.H.\.
0x64cfec30: 005cdf40 005eaac0 005eaab8 000000a0 @.\...^...^.....
0x64cfec40: 00000098 00030d60 00030d58 00030d64 ....`...X...d...
0x64cfec50: 00030d60 00030d80 00030d78 00030d84 `.......x.......
0x64cfec60: 00030d80 005eb348 005eb340 005eb34c ....H.^.@.^.L.^.
0x64cfec70: 005eb348 005eb358 005eb350 005eb35c H.^.X.^.P.^.\.^.
0x64cfec80: 005eb358 005e9c30 005e9c28 005e9c34 X.^.0.^.(.^.4.^.
0x64cfec90: 005e9c30 005e9c38 005e9c34 005e9c3c 0.^.8.^.4.^.<.^.
0x64cfeca0: 005e9c38 005e9c40 005e9c3c 005e9c50 8.^.@.^.<.^.P.^.
0x64cfecb0: 005e9c48 005e9c54 005e9c50 005e9c58 H.^.T.^.P.^.X.^.
0x64cfecc0: 005e9c54 005e9c5c 005e9c58 005e9c60 T.^.\.^.X.^.`.^.
0x64cfecd0: 005e9c5c 005e9c64 005e9c60 0000008e \.^.d.^.`.^.....
0x64cfece0: 00000000 00000000 64cfee00 0000008e ...........d....
0x64cfecf0: 64cfedc0 0000008e ce87d1d8 00007ffb ...d............
0x64cfed00: 00000000 001ddb28 001ddb20 00030d70 ....(... ...p...
0x64cfed10: 00030d68 00030d74 00030d70 00000000 h...t...p.......
0x64cfed20: 00000000 00000000 00000000 001ddb38 ............8...
0x64cfed30: 001ddb30 005e8488 005e8480 00000000 0.....^...^.....
0x64cfed40: 00000000 00000000 93c6c68c 00007ffb ................
0x64cfed50: 00000000 00000000 92740000 00007ffb ..........t.....
0x64cfed60: 64cffd50 0000008e 93a3592c 00007ffb P..d....,Y......
0x64cfed70: 64cffd50 0000008e 00000000 00000000 P..d............
0x64cfed80: 00000000 005f8570 005f8500 00000000 ....p._..._.....
0x64cfed90: 64cff2e0 0000008e 64cffc90 005e9bf0 ...d.......d..^.
0x64cfeda0: 005e9be0 0000008e 64cfe000 0000008e ..^........d....
0x64cfedb0: 64d00000 0000008e 00000000 005cdf00 ...d..........\.
0x64cfedc0: 005cdedc 00000a10 000009e8 00484b38 ..\.........8KH.
0x64cfedd0: 00484b18 00000abc 00000aa0 0046a708 .KH...........F.
0x64cfede0: 0046a6e8 00000968 00000940 0000008e ..F.h...@.......
0x64cfedf0: 93801fd4 00007ffb 93a3592c 00007ffb ........,Y......
0x64cfee00: 64cff2e0 0000008e 00000000 00000000 ...d............
0x64cfee10: 00000000 00000000 00000000 005f8184 .............._.
0x64cfee20: 005f8178 00000000 00000000 005ea034 x._.........4.^.
0x64cfee30: 005ea028 005ea024 005ea018 00000000 (.^.$.^...^.....
0x64cfee40: 0010000f 005e25d8 005e25cc 0000c39c .....%^..%^.....
0x64cfee50: 0000c38c 005e9fb4 005e9fac 00000000 ......^...^.....
0x64cfee60: 00000000 00000000 00000000 005e9128 ............(.^.
0x64cfee70: 005e9108 00000000 00000000 00000000 ..^.............
0x64cfee80: 00000000 00000000 406d1388 005eaa60 ..........m@`.^.
0x64cfee90: 005eaa5c 005eaa64 005eaa60 0000008e \.^.d.^.`.^.....
0x64cfeea0: 00000000 00000000 64cffd50 0000008e ........P..d....
0x64cfeeb0: 00000000 00000000 00000000 00000000 ................
0x64cfeec0: 0e0a73d0 00000289 63f45000 0000008e .s.......P.c....
0x64cfeed0: 64cfe578 0000008e 93a3592c 00007ffb x..d....,Y......
0x64cfeee0: 92740000 00007ffb 00000000 00000000 ..t.............
0x64cfeef0: 00000000 00000000 00000000 00000000 ................
0x64cfef00: 00000000 00000000 92c7b62a 00007ffb ........*.......
0x64cfef10: 0000027f 00000000 00000000 00000000 ................
0x64cfef20: 00000000 00000000 00001f80 0000ffff ................
0x64cfef30: 00000000 00000000 00000000 00000000 ................
0x64cfef40: 00000000 00000000 00000000 00000000 ................
0x64cfef50: 00000000 00000000 005e8224 005e8220 ........$.^. .^.
0x64cfef60: 005e8228 005e8224 00000000 00000000 (.^.$.^.........
0x64cfef70: 00000000 00000000 00499da0 00499d98 ..........I...I.
0x64cfef80: 00499da8 00499da0 00000000 00000000 ..I...I.........
0x64cfef90: 0049a450 0049a428 0049a458 0049a454 P.I.(.I.X.I.T.I.
0x64cfefa0: 0049a460 0049a458 00499aa8 00499aa4 `.I.X.I...I...I.
0x64cfefb0: 00499ab0 00499aa8 005ea358 005ea354 ..I...I.X.^.T.^.
0x64cfefc0: 005ea35c 005ea358 005ea368 005ea360 \.^.X.^.h.^.`.^.
0x64cfefd0: 005ea36c 005ea368 005ea370 005ea36c l.^.h.^.p.^.l.^.
0x64cfefe0: 005ea374 005ea370 005ea380 005ea378 t.^.p.^...^.x.^.
0x64cfeff0: 005ea350 005ea348 005ea39c 005ea398 P.^.H.^...^...^.
0x64cff000: 005ea3a0 005ea39c 005ea3a4 005ea3a0 ..^...^...^...^.
0x64cff010: 005ea3a8 005ea3a4 005ea3ac 005ea3a8 ..^...^...^...^.
0x64cff020: 005ea3b0 005ea3ac 005ea3b4 005ea3b0 ..^...^...^...^.
0x64cff030: 00000000 00000000 00000000 00000000 ................
0x64cff040: 00000000 00000000 005ea3b8 005ea3b4 ..........^...^.
0x64cff050: 005ea3bc 005ea3b8 005ea3c0 005ea3bc ..^...^...^...^.
0x64cff060: 005ea3c4 005ea3c0 005ea3c8 005ea3c4 ..^...^...^...^.
0x64cff070: 005ea3d0 005ea3c8 005ea3e0 005ea3d8 ..^...^...^...^.
0x64cff080: 005ea3e4 005ea3e0 005ea3e8 005ea3e4 ..^...^...^...^.
0x64cff090: 005ea3ec 005ea3e8 00000000 00000000 ..^...^.........
0x64cff0a0: 00000000 00000000 00000000 00000000 ................
0x64cff0b0: 005dfef8 005dfef4 00000000 00000000 ..]...].........
0x64cff0c0: 000003d7 00000289 17be0000 00000289 ................
0x64cff0d0: 000003d7 00000000 00000000 00000000 ................
0x64cff0e0: 11000011 00000000 00000000 00000000 ................
0x64cff0f0: 05010004 00000000 00000000 00000000 ................
0x64cff100: 64cff218 0000008e ce891644 00007ffb ...d....D.......
0x64cff110: 0c530000 00000289 17be0000 00000289 ..S.............
0x64cff120: 17d1dfd0 00000289 000002ac 00000000 ................
0x64cff130: 005f8970 005f8968 005f8974 005f8970 p._.h._.t._.p._.
0x64cff140: 005f8978 005f8974 00557bd8 00557bd0 x._.t._..{U..{U.
0x64cff150: 17d1d250 00000289 64cff1c0 0000008e P..........d....
0x64cff160: 005f7c38 005f7c10 005f7c48 005f7c38 8|_..|_.H|_.8|_.
0x64cff170: 005f7c68 005f7c48 17d20fc0 00000289 h|_.H|_.........
0x64cff180: 00000000 00000000 005eacb0 005eac80 ..........^...^.
0x64cff190: 005eaf98 005eaf68 005eaf98 005eaf98 ..^.h.^...^...^.
0x64cff1a0: 005f82d0 005f82cc 00000000 00000000 .._..._.........
0x64cff1b0: 005eaa40 005eaa38 00000000 00000000 @.^.8.^.........
0x64cff1c0: 0053c5c0 0053c5b8 000ae108 000ae100 ..S...S.........
0x64cff1d0: 005f8988 005f8980 005f8990 005f8988 .._..._..._..._.
0x64cff1e0: 005f8948 005f8910 0c530000 00000289 H._..._...S.....
0x64cff1f0: 0c530000 00000289 ce88b95f 00007ffb ..S....._.......
0x64cff200: 00002ac0 00000000 00002ab0 00000000 .*.......*......
0x64cff210: 0c530150 00000289 005f81a0 005f819c P.S......._..._.
0x64cff220: 005f81a4 005f81a0 005f81a8 005f81a4 .._..._..._..._.
0x64cff230: 0049b69c 0049b698 0049b6b0 0049b6a0 ..I...I...I...I.
0x64cff240: 0049b6b4 0049b6b0 00000001 00000000 ..I...I.........
0x64cff250: 00000000 00000000 17d1d260 00000289 ........`.......
0x64cff260: 000440c0 000440b8 000440d8 000440c0 .@...@...@...@..
0x64cff270: 00030dc8 00030db8 00030de0 00030dc8 ................
0x64cff280: 00557c10 00557c00 00557c20 00557c10 .|U..|U. |U..|U.
0x64cff290: 0049e2f8 0049e2e8 0049e30c 0049e2f8 ..I...I...I...I.
0x64cff2a0: 0049a400 0049a3f0 0049a420 0049a400 ..I...I. .I...I.
0x64cff2b0: 0000012b 00000000 64cff320 0000008e +....... ..d....
0x64cff2c0: 0c530000 00000289 ce891249 00007ffb ..S.....I.......
0x64cff2d0: 005f8978 00000000 17d1dfc0 00000289 x._.............
0x64cff2e0: 00000552 00000002 0001afe8 00000090 R...............
0x64cff2f0: 00000004 00000001 00000001 00007ffb ................
0x64cff300: 00000000 00007ffb 92740000 00007ffb ..........t.....
0x64cff310: 93c6c68c 00007ffb 00002749 00000000 ........I'......
0x64cff320: 00000014 00000002 00000004 00000000 ................
0x64cff330: 00000002 00000289 01831120 00000289 ........ .......
0x64cff340: 8aaae474 00000289 00000016 00000206 t...............
0x64cff350: 00000000 00000289 1086d110 00000289 ................
0x64cff360: 00000008 00000000 0000016c 0000037f ........l.......
0x64cff370: 00000000 00000289 1086d100 00000289 ................
0x64cff380: 1086d100 00000289 000003ff 00000000 ................
0x64cff390: 0e419dd0 00000289 00000b60 00000000 ..A.....`.......
0x64cff3a0: 000001bf 00000000 939c0cf0 00000289 ................
0x64cff3b0: 00000028 00007ffb 00000009 00000009 (...............
0x64cff3c0: 49fc0ba0 00000289 0e69e180 00000289 ...I......i.....
0x64cff3d0: 00000000 00000000 00000016 00000206 ................
0x64cff3e0: 00000000 00000289 00000000 00000000 ................
0x64cff3f0: 9384e548 00007ffb 00000001 00000001 H...............
0x64cff400: 00000000 00000001 00000004 00000004 ................
0x64cff410: 00000006 00000006 1175abd8 00000289 ..........u.....
0x64cff420: 00000001 0000008e 00000006 00000000 ................
0x64cff430: 00000006 80000000 1175abf0 00000289 ..........u.....
0x64cff440: 00000001 00000000 00000006 00000000 ................
0x64cff450: 00000006 80000000 1175ac08 00000289 ..........u.....
0x64cff460: 00000001 00000289 0000007c 00000000 ........|.......
0x64cff470: 0000007c 80000000 00000000 00000000 |...............
0x64cff480: 00000001 00000000 0000001f 80000000 ................
0x64cff490: 000001c8 00000000 00000000 00000000 ................
0x64cff4a0: 00000000 00000000 00000000 00000000 ................
0x64cff4b0: 00000000 00000000 00000000 00000000 ................
0x64cff4c0: 00000000 00000000 00000000 00000000 ................
0x64cff4d0: 000001ca 00000000 00000000 00000000 ................
0x64cff4e0: 00000000 00000000 00000000 00000000 ................
0x64cff4f0: 00000000 00000000 00000000 00000000 ................
0x64cff500: 00000000 00000000 00000000 00000000 ................
0x64cff510: 00000000 00000000 00000000 00000000 ................
0x64cff520: 00000000 00000000 00000000 00000000 ................
0x64cff530: 00000000 00000000 00000000 00000000 ................
0x64cff540: 00000000 00000000 00000000 00000000 ................
0x64cff550: 00000000 00000000 00000000 00000000 ................
0x64cff560: 00000000 00000000 00000000 00000000 ................
0x64cff570: 00000000 00000000 00000000 00000000 ................
0x64cff580: 00000000 00000000 00000000 00000000 ................
0x64cff590: 0e072ee0 00000289 0e072e70 00000289 ........p.......
0x64cff5a0: bd0d1780 00007ffb bd0d18bb 00007ffb ................
0x64cff5b0: 00000001 00000000 00000000 00000000 ................
0x64cff5c0: 2c370d38 00000289 17c33fe0 00000289 8.7,.....?......
0x64cff5d0: 00000001 00007ffb 64cff5c8 0000008e ...........d....
0x64cff5e0: 88dd0d29 0000bd9b 00000019 00000000 )...............
0x64cff5f0: 0e072ee0 00000289 00000000 00000000 ................
0x64cff600: 00000000 00000000 00000000 00000000 ................
0x64cff610: 00000000 00000000 00000000 00000000 ................
0x64cff620: 00000000 00000000 00000000 00000000 ................
0x64cff630: 0e072e70 00000289 00000001 00000000 p...............
0x64cff640: ffffffff 00000000 00000000 00000000 ................
0x64cff650: 00000000 00000000 00000000 00000000 ................
0x64cff660: 00000000 00000000 0e0ed050 00000289 ........P.......
0x64cff670: 0e0f3b90 00000289 00000000 00000000 .;..............
0x64cff680: 00000000 00000000 00000000 00000000 ................
0x64cff690: 00000000 00000000 25e87ca0 00000289 .........|.%....
0x64cff6a0: 25e88120 00000289 00000000 00000000  ..%............
0x64cff6b0: 00000000 00000000 00000000 00000000 ................
0x64cff6c0: 00000000 00000000 1175b104 00000289 ..........u.....
0x64cff6d0: 1175b17c 00000289 00000000 00000000 |.u.............
0x64cff6e0: 00000000 00000000 00000000 00000000 ................
0x64cff6f0: 00000010 00000000 64cffc70 0000008e ........p..d....
0x64cff700: 00000000 00000000 00000000 00000000 ................
0x64cff710: 0e0a73d0 00000289 ce871493 00007ffb .s..............
0x64cff720: bd0d0000 00007ffb 00000002 00000000 ................
0x64cff730: 80000000 00000000 00000000 00000000 ................
0x64cff740: 00000000 00000000 00000000 00000000 ................
0x64cff750: 00000000 00000000 cb103fb8 00007ffb .........?......
0x64cff760: 0000027f 00000000 00000000 00000000 ................
0x64cff770: 00000003 00007ffb 00001f80 0000008e ................
0x64cff780: bd0d1780 00007ffb ce86efee 00007ffb ................
0x64cff790: 0c5323a0 00000289 63f2a000 0000008e .#S........c....
0x64cff7a0: 63f2a000 0000008e bd0d1780 00007ffb ...c............
0x64cff7b0: 17c3d210 00000289 bd0d1780 00007ffb ................
0x64cff7c0: 00000048 00000000 00000001 00000000 H...............
0x64cff7d0: 00000000 00000000 00000000 00000000 ................
0x64cff7e0: 00000070 00000000 ffffffff ffffffff p...............
0x64cff7f0: 00550000 ffffffff ce86ef26 00007ffb ..U.....&.......
0x64cff800: 0000422b 00000289 17be0000 00000289 +B..............
0x64cff810: 0000422b 00000000 00000000 00000000 +B..............
0x64cff820: 11000011 00000000 00000000 00000000 ................
0x64cff830: ffff0000 00000000 00000000 00000000 ................
0x64cff840: 64cff958 0000008e ce891644 00007ffb X..d....D.......
0x64cff850: 0c530000 00000289 17be0000 00000289 ..S.............
0x64cff860: 00000000 00000000 00000000 00000000 ................
0x64cff870: 00000003 00000000 00000000 00000000 ................
0x64cff880: 00000000 00000000 00000000 00000000 ................
0x64cff890: 00000000 00000000 00000000 00000000 ................
0x64cff8a0: 00000000 00000000 00000000 00000000 ................
0x64cff8b0: 00000010 00000000 00000000 00000000 ................
0x64cff8c0: 00000000 00000000 00000000 00000000 ................
0x64cff8d0: 00000000 00000000 00000000 00000000 ................
0x64cff8e0: 00000000 00000000 00000000 00000000 ................
0x64cff8f0: 00000000 00000000 00000000 00000000 ................
0x64cff900: 00004002 00000000 0c530150 00000289 .@......P.S.....
0x64cff910: 0c530150 00000289 0c536680 00000289 P.S......fS.....
0x64cff920: 0000037f 00000000 0c530000 00000289 ..........S.....
0x64cff930: 00000000 00000289 ce88bafc 00007ffb ................
0x64cff940: 00040020 00000000 00040017 00000000  ...............
0x64cff950: 0c530150 00000289 0000422b 00000000 P.S.....+B......
0x64cff960: 000003ff 00000000 0000422b 00000000 ........+B......
0x64cff970: 00000000 00000000 00000000 00000000 ................
0x64cff980: 00000000 00000000 00000001 00000000 ................
0x64cff990: 00000000 00000000 17d1fd20 00000289 ........ .......
0x64cff9a0: 00000009 00000000 00000033 00000000 ........3.......
0x64cff9b0: 89369b30 00000289 00000044 00000289 0.6.....D.......
0x64cff9c0: 17d1fd10 00000289 00000000 00000000 ................
0x64cff9d0: 000003ff 00000000 00000000 00000000 ................
0x64cff9e0: 00000229 00000000 00000229 00000000 ).......).......
0x64cff9f0: 2c8ea120 00000289 00000000 00000000  ..,............
0x64cffa00: 00000000 00000000 00000000 00000000 ................
0x64cffa10: 00000000 00000000 00000000 00000000 ................
0x64cffa20: 00000000 00000000 00000000 00000000 ................
0x64cffa30: 00000000 00000000 00000000 00000000 ................
0x64cffa40: 00000000 00000000 00000000 00000000 ................
0x64cffa50: 00000000 00000000 00000000 00000000 ................
0x64cffa60: 00000000 00000000 00000000 00000000 ................
0x64cffa70: 2c8ea120 00000289 00000000 00000000  ..,............
0x64cffa80: 00000000 00000000 00000000 00000000 ................
0x64cffa90: 00000000 00000000 00000000 00000000 ................
0x64cffaa0: 00000000 00000000 00000000 00000000 ................
0x64cffab0: 00000000 00000000 00000000 00000000 ................
0x64cffac0: 00000000 00000000 00000000 00000000 ................
0x64cffad0: 00000000 00000000 00000000 00000000 ................
0x64cffae0: 00000000 00000000 00000000 00000000 ................
0x64cffaf0: 00000000 00000000 00000000 00000000 ................
0x64cffb00: 00000000 00000000 00000000 00000000 ................
0x64cffb10: 00000000 00000000 00000000 00000000 ................
0x64cffb20: 00000000 00000000 00000000 00000000 ................
0x64cffb30: 00000000 00000000 00000000 00000000 ................
0x64cffb40: 00000000 00000000 00000000 00000000 ................
0x64cffb50: 00000000 00000000 00000000 00000000 ................
0x64cffb60: 00000000 00000000 00000000 00000000 ................
0x64cffb70: 1e0469d0 00000289 00000000 00000000 .i..............
0x64cffb80: 00000000 00000000 00000000 00000000 ................
0x64cffb90: 00000000 00000000 00000000 00000000 ................
0x64cffba0: 00000000 00000000 00000000 00000000 ................
0x64cffbb0: 000003ff 00000000 00040020 00000000 ........ .......
0x64cffbc0: 0c530000 00000289 ce888e0b 00007ffb ..S.............
0x64cffbd0: 0c530000 00000289 00000002 00000000 ..S.............
0x64cffbe0: 00040017 00000000 00040020 00000000 ........ .......
0x64cffbf0: 00000000 00000001 64cffc08 0000008e ...........d....
0x64cffc00: 00000000 00000000 00000003 00000000 ................
0x64cffc10: 00000000 00000000 00000000 00000000 ................
0x64cffc20: 00000000 00000000 00000000 00000000 ................
0x64cffc30: 88dd0ed9 0000bd9b 00000000 00000000 ................
0x64cffc40: 00000000 00000000 00000000 00000000 ................
0x64cffc50: 00000000 00000000 00000000 00000000 ................
0x64cffc60: 00000000 00000000 cb103fb8 00007ffb .........?......
0x64cffc70: 00000000 00000000 00000000 00000000 ................
0x64cffc80: 00000000 00000000 0e0a73d0 00000289 .........s......
0x64cffc90: 406d1388 00000002 00000000 00000000 ..m@............
0x64cffca0: cb103fb8 00007ffb 00000003 00000000 .?..............
0x64cffcb0: 00001000 00000000 938fe0c0 00007ffb ................
0x64cffcc0: 000010f8 00000000 92a12c76 00007ffb ........v,......
0x64cffcd0: 00000000 00000000 00040000 00000000 ................
0x64cffce0: 00000000 00000000 92a14443 00007ffb ........CD......
0x64cffcf0: 00000000 00000000 00000000 00000000 ................
0x64cffd00: 00000000 00000000 00000000 00000000 ................
0x64cffd10: 64cfe8b0 0000008e 0000000f 00000000 ...d............
0x64cffd20: 00000000 00000000 11051a00 00000289 ................
0x64cffd30: 0efd5d90 00000289 931e847b 00007ffb .]......{.......
0x64cffd40: 0efd5d90 00000289 11051a00 00000289 .]..............
0x64cffd50: 85ebe7f0 00000289 00000000 00000000 ................
0x64cffd60: 00000000 00000000 931e853c 00007ffb ........<.......
0x64cffd70: 0efd5d90 00000289 00000000 00000000 .]..............
0x64cffd80: 00000000 00000000 0e0a73d0 00000289 .........s......
0x64cffd90: 00000000 00000000 92c7a8c8 00007ffb ................
0x64cffda0: 00000000 00000000 00000000 00000000 ................
0x64cffdb0: 00000000 00000000 00000000 00000000 ................
0x64cffdc0: 00000000 00000000 cdb61fe4 00007ffb ................
0x64cffdd0: 00000000 00000000 00000000 00000000 ................
0x64cffde0: 00000000 00000000 00000000 00000000 ................
0x64cffdf0: 00000000 00000000 ce8cefb1 00007ffb ................
0x64cffe00: 00000000 00000000 00000000 00000000 ................
0x64cffe10: 00000000 00000000 00000000 00000000 ................
0x64cffe20: 00000000 00000000 cb1d9360 00007ffb ........`.......
0x64cffe30: 64cfd8c0 0000008e 64cfd8c0 0000008e ...d.......d....
0x64cffe40: 00000000 00000000 00000000 00000000 ................
0x64cffe50: 00000000 00000000 00000000 00000000 ................
0x64cffe60: 00000000 00000000 00000000 00000000 ................
0x64cffe70: 00000000 00000000 00000000 00000000 ................
0x64cffe80: 00000000 00000000 00000000 00000000 ................
0x64cffe90: 00000000 00000000 00000000 00000000 ................
0x64cffea0: 00000000 00000000 00000000 00000000 ................
0x64cffeb0: 00000000 00000000 00000000 00000000 ................
0x64cffec0: 00000000 00000000 00000000 00000000 ................
0x64cffed0: 00000000 00000000 00000000 00000000 ................
0x64cffee0: 00000000 00000000 00000000 00000000 ................
0x64cffef0: 00000000 00000000 00000000 00000000 ................
0x64cfff00: 00000000 00000000 00000000 00000000 ................
0x64cfff10: 00000000 00000000 00000000 00000000 ................
0x64cfff20: 00000000 00000000 00000000 00000000 ................
0x64cfff30: 00000000 00000000 00000000 00000000 ................
0x64cfff40: 00000000 00000000 00000000 00000000 ................
0x64cfff50: 00000000 00000000 00000000 00000000 ................
0x64cfff60: 00000000 00000000 00000000 00000000 ................
0x64cfff70: 00000000 00000000 00000000 00000000 ................
0x64cfff80: 00000000 00000000 00000000 00000000 ................
0x64cfff90: 00000000 00000000 00000000 00000000 ................
0x64cfffa0: 00000000 00000000 00000000 00000000 ................
0x64cfffb0: 00000000 00000000 00000000 00000000 ................
0x64cfffc0: 00000000 00000000 00000000 00000000 ................
0x64cfffd0: 00000000 00000000 00000000 00000000 ................
0x64cfffe0: 00000000 00000000 00000000 00000000 ................
0x64cffff0: 00000000 00000000 00000000 00000000 ................

Module 1
C:\Windows\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_175422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
D:\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x50120000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-01-29_104020
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1

== [end of error.log] ==

**Comment by MarjieAVolk** [comment]
Assigning to @Nanders since I believe you just worked on fullscreen settings, which might be related?

**Comment by Nanders** [comment]
I cant repro this
