### ISSUE TITLE
USER ISSUE: Plants die as soon as planted

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3694]
**Version:** 0.7.0.0 beta staging-a5db4bb6

but looking at this snapshot not sure if they all died or graphics didn't update
![snap1403](https://user-images.githubusercontent.com/29383891/35521726-66f67e14-0512-11e8-84ef-7110f09e3e77.png)

Did Check with Disconnecting and Quitting (it all looks the same)
![snap1404](https://user-images.githubusercontent.com/29383891/35522185-8e25fa86-0513-11e8-8a7c-32a8e028359a.png)
![snap1405](https://user-images.githubusercontent.com/29383891/35522186-8e414480-0513-11e8-9577-03e9c7d09d55.png)

waited for awhile to test this and one plant is dead and one is alive.

This is getting a bit Confusing because why would planting not kill **ALL** plants??

**Comment by Huntermeign** [comment]
is this checked with a soil sampler?

**Comment by MarjieAVolk** [comment]
I think this might already be fixed on master?

**Comment by Conchipedia** [comment]
i didn't have access to soil sampler as i couldn't get my server to load, had to do this all physically

**Comment by Conchipedia** [comment]
![snap1406](https://user-images.githubusercontent.com/29383891/35532104-f1f54fcc-0530-11e8-909f-2d63ab3ff32d.png)
![snap1407](https://user-images.githubusercontent.com/29383891/35532105-f20f8248-0530-11e8-9b5c-805756cdec4f.png)
![snap1408](https://user-images.githubusercontent.com/29383891/35532106-f22d9918-0530-11e8-91f2-875886ef82dc.png)
This is doing the same on Marmot, and now i can read it with Soil Sampler, same as was happening before on other server, they die but not **ALL** of them

**Comment by knexer** [comment]
This is fixed in https://github.com/StrangeLoopGames/Eco/pull/2340
