### ISSUE TITLE
[Staging-a5db4bb6] Resolution confirmation button not clickable

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3696]
On settings menu, when you change resolutions, the countdown and text is over top of the confirm button and the button cannot be clicked on.
![image](https://user-images.githubusercontent.com/1503963/35531124-15d47a76-0504-11e8-9483-87db931f2f2a.png)

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3661
