### ISSUE TITLE
USER ISSUE: Trying to run for office gives error on webpage

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3699]
**Version:** 0.7.0.0 beta staging-a5db4bb6

![snap1409](https://user-images.githubusercontent.com/29383891/35537182-3eeb0e24-0541-11e8-9eb3-1f92634d3247.png)

first time i have ever had a problem loading from ingame (same PC same setting nothing changed my side)

**Comment by Conchipedia** [comment]
Double checked this and quit
![snap1410](https://user-images.githubusercontent.com/29383891/35537326-bb5c5bfc-0541-11e8-92c2-19293472bbcd.png)
 Marmot and loaded in 6.3.1 Greenleaf Prime and i see this

**Comment by MarjieAVolk** [comment]
Sounds like it might be the same as https://github.com/StrangeLoopGames/EcoIssues/issues/3656

**Comment by Conchipedia** [comment]
i never had this problem before until i tried in beta 7 staging

**Comment by rainfarmer** [comment]
@metachronism Does the web server work for v7 ?

**Comment by Conchipedia** [comment]
This is working now on **Version**: 0.7.0.0 beta staging-71fcbff4, but still have the same problem as a while ago that page has to be refreshed before it will let you click on anything.
Referencing this Github as this is what is still is doing for me
**[web] When going to web to run for leader speach window appears then goes, need to refresh to make it stay (Firefox) #2964**
version i am using is latest
![snap1477](https://user-images.githubusercontent.com/29383891/35652714-bfc1d78e-06dc-11e8-89cb-c1d23b5b876b.png)
not sure about other Browsers as i only use this one

**Comment by rainfarmer** [comment]
see answer on https://github.com/StrangeLoopGames/EcoIssues/issues/3656
