### ISSUE TITLE
USER ISSUE: Minimap Overlay Not working

### ISSUE THREAD

**Issue by Aldjeron** [StrangeLoopGames/EcoIssues#3700]
**Version:** 0.7.0.0 beta staging-a5db4bb6

**Steps to Reproduce:**
Standard game 7.0.0

**Expected behavior:**
Should be colored and showing the detailed info.

**Actual behavior:**
Plain bland hue of shade. Both on Minimap and In World.

**Comment by Aldjeron** [comment]
restarting my game did fix it

**Comment by elfl0rd** [comment]
looks not reproducible.
