### ISSUE TITLE
USER ISSUE: [Art] Reinforced Concrete Pillar not working the same as other Pillars

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3701]
**Version:** 0.7.0.0 beta staging-a5db4bb6

![snap1411](https://user-images.githubusercontent.com/29383891/35538509-1261c64a-0546-11e8-93da-7660f801a5fa.png)

**Comment by Conchipedia** [comment]
forgot to add lumber pillar , buts that is fine
![snap1412](https://user-images.githubusercontent.com/29383891/35538722-c83c3d60-0546-11e8-9d85-60b7532d3ba4.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#301
