### ISSUE TITLE
Message when trying to collect carryable items while your hands are full is unclear.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3703]
![image](https://user-images.githubusercontent.com/3536496/35542481-1f0c394c-0515-11e8-92e1-d6d1f057abe1.png)

It says 'Not enough room in inventory' but should say 'You must put down the logs you are carrying before you can do that.'

It's on the tutorial path, so will be an important one.

**Comment by MarjieAVolk** [comment]
These messages are coming from inside the inventory system, so it's pretty hard to put extra context like that on them.
