### ISSUE TITLE
Hammer form UI is messed up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3704]
![image](https://user-images.githubusercontent.com/3536496/35542561-71a9997e-0515-11e8-823d-72822fe4e57c.png)

- [x] Theres dangling 'shift' text
- [x] Clicking a form no longer closes the form window
- [x] There's a blacked out form.  It should show a lock if its locked (the form icon should be visible behind the lock)
- [x] Shift+scrolling doesnt scroll the selection past blacked out forms
- [x] It used to fade in quickly (.1 second) and fade out slowly if you didnt make a selection, and quickly if you did
- [ ] Forms I have access to are saying 'requires skill X' when I mouse over them.  I dont have that skill, so I shouldnt have that form.

**Comment by MarjieAVolk** [comment]
Just saw the shift text being messed up, it's that unity bug Nick was talking about this morning, pretty sure O.o

**Comment by MarjieAVolk** [comment]
"It used to fade in quickly (.1 second) and fade out slowly if you didnt make a selection, and quickly if you did"

I am not sure what you are asking for.  I did change the fading behavior, to make the window close in FPS mode when you release shift.  I will fix it closing when you select one with the cursor.  But this one I don't know what you want, not sure if you are talking about cursor mode or FPS mode, and both seem pretty good to me aside from the aforementioned issue.

**Comment by johnkslg** [comment]
The fade I'm referring to, when you click the form icon it used to fade it in over .1 seconds, its a lot slower now.  Just made it feel snappier. Same with when you selected a form, .1 seconds to fade out (or instaoff, I forget).

**Comment by MarjieAVolk** [comment]
Re "Shift+scrolling doesnt scroll the selection past blacked out forms" - what's actually happening is that the blacked out form and all below it cannot be used because you don't have the skill.  So the scrolling behavior is correct.
