### ISSUE TITLE
"The remote server returned an error: <500> Internal Server error."

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3705]
as title states, um what? 

attempting to restart now...
![2018-01-29](https://user-images.githubusercontent.com/20627148/35543193-01504d2e-0521-11e8-8e43-65df89b413ef.png)

**Comment by Huntermeign** [comment]
Eco is updating the servers apparently. Restart the client in a few minutes.

Same if you get

Connection Failed
Invalid login token.

**Comment by MarjieAVolk** [comment]
Yeah some web services went down, we are fixing them right now
