### ISSUE TITLE
Line up levels in this tooltip

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#371]
![image](https://cloud.githubusercontent.com/assets/3536496/16469623/ed2f1baa-3e06-11e6-841b-9446c2736916.png)
will reduce busy-ness a lot (theres a textmesh pro function for it, I think called 'pos')

**Comment by craig-jong** [comment]
duplicate https://github.com/StrangeLoopGames/EcoIssues/issues/374
