### ISSUE TITLE
[Suggestion] let Meteor Shard gives us light in normal view not just in 3rd person

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3714]
**Version:** 0.7.0.0 beta staging-7da08558

![snap1435](https://user-images.githubusercontent.com/29383891/35584256-617022d0-05ec-11e8-8e1b-faaa772caaa9.png)
![snap1436](https://user-images.githubusercontent.com/29383891/35584257-6191340c-05ec-11e8-9ac1-501fb3b3c44c.png)
also would it be possible to maybe have an extra part on the backpack pullout where we can wear this as an item? it is hanging off the backpack after all, then maybe people can maybe mod this slot to hang other stuff in
![snap1437](https://user-images.githubusercontent.com/29383891/35584383-c6e8727a-05ec-11e8-85e7-ba216da546b6.png)

**Comment by Conchipedia** [comment]
adding to this as sometimes if the meteor shard is placed in toolbar it doesn't always show up on third person view until you switch to another item then back again, if it was added to the avatar as a slot then it would be out the way and also maybe open up the possibilities to Modders adding items that can hang off the backpack as rewards or something or maybe even SLG adding something to Steam when unlocking something and this can be placed in this slot

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#300
