### ISSUE TITLE
Clean up the tech path from Tier 2 -> Tier 3

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3715]
"Right now, on the current 7.0 staging build, the only way to advance to Tier 3 materials is by building a room with 32 glass(Because its the only Tier 3 items that doesn't require another Tier 3 item for the bench to work) This seems very restrictive and really holds back smaller servers if no one is going make glass. This should be changed before the steam launch as it is really impacting." -- @Senlarus

**Comment by Senlarus** [comment]
Oh, sorry I didn't see this. In my ticket #3728 I included screenshots, not sure if that's helpful but I wanted to put some effort into creating the ticket. Thanks @MarjieAVolk for taking my feedback from Discord and creating this ticket.
