### ISSUE TITLE
USER ISSUE: Aqueduct is not in game

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3717]
**Version:** 0.7.0.0 beta staging-7da08558

it use to be under concrete with hammer, but now concrete can be stored in a backpack we have lost aqueduct, i checked under hewn log, reinforced concrete, mortared stone, lumber and Corrugated Steel, those i think are ALL the ones that use hammer and its nowhere to be found, and it wont come up in /give list

**Comment by MarjieAVolk** [comment]
This should not be a form if it's used for a different gameplay purpose and people will need to search for it

**Comment by Conchipedia** [comment]
i found this it was under brick but no Graphics for it

**Comment by johnkslg** [comment]
High priority, broken feature.
