### ISSUE TITLE
Professions and specialties need descriptions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3722]
![image](https://user-images.githubusercontent.com/3536496/35595144-7b07bf54-05ca-11e8-8cb8-a4cc766251a0.png)
Should have a description of what a profession/specialty is (profession: just a category of specialties, specialty: a collection of related skills), and flavor text describing the general idea of what that profession/specialty does.

Also, we could drive home the point that 'specialties' are part of each 'profession' by changing the title 'Specialties' in the UI to read 'Carpenter Specialties', etc, depending what you have selected.
![image](https://user-images.githubusercontent.com/3536496/35595220-c3ddcbce-05ca-11e8-9094-e40888072c06.png)

**Comment by WeaselDog** [comment]
This might be ready to close. Everything is here except the professions themselves don't have flavor text. The specialties all have flavor text.
![SpecialtyDescription](https://user-images.githubusercontent.com/47330823/71289398-da34ae80-2321-11ea-957b-e7ed5ed23b85.png)
