### ISSUE TITLE
USER ISSUE: Bullrush seed showing water when planted and then one died

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3724]
**Version:** 0.7.0.0 beta staging-7da08558

![snap1448](https://user-images.githubusercontent.com/29383891/35595713-87831482-060f-11e8-8ed7-4e385f656029.png)
![snap1449](https://user-images.githubusercontent.com/29383891/35595741-a6978592-060f-11e8-9860-f35c0413c2f2.png)
they still have 6.6 hours to grow to maturity, surely it shouldn't diie this early in its life?

**Comment by SeanAtr0n** [comment]
fixed a while back
