### ISSUE TITLE
[Staging Beta 7.0.0 #7da08558] Solo game is still not running/compiling

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3726]
Saw that the previous staging report of this was closed.  Tried latest staging and the same issue is still occiring - the solo game does not run from in the browser.  see #3726

**Comment by MarjieAVolk** [comment]
You've linked this bug to itself :P

**Comment by pamduncan** [comment]
Sorry should be linked to #3711

**Comment by pamduncan** [comment]
This is now resolved in today's staging
