### ISSUE TITLE
[Staging Beta 7.0.0 #7da08558] Frozen world UPDATE :  [Staging Beta 7.0.0 #71fcbff4is] better but still one main biome...

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3729]
Installed Staging Beta 7.0.0 #7da08558 with exitings world that had had a very varied number of biomes.  Now the entire world is locked in frozen winter.  I enjoy a winter wonderland just like anyone but this is more reminiscent of a nuclear winter...

[![Screenshot from Gyazo](https://gyazo.com/c51e576d79931b1963ab544262286a43/raw)](https://gyazo.com/c51e576d79931b1963ab544262286a43)

https://www.dropbox.com/s/jeyys4qa4b89xtx/pamelad_EcoGS_2018-01-30_17-41.zip?dl=0

**Comment by pamduncan** [comment]
UPDATE:  After about 45 minutes game play suddenly the world seemed to change to desert or at least arid biome, while the map still showed snow.  Prior to this I was running around in snow banks but there was a blik and now it looks like this although the map thinks snow is still there....  Is there a hope for this world?

[![Screenshot from Gyazo](https://gyazo.com/ae63072e39bdbc88ec6e6fb870d5fbfd/raw)](https://gyazo.com/ae63072e39bdbc88ec6e6fb870d5fbfd)

**Comment by knexer** [comment]
Hm, this issue was supposed to have been fixed in this build... soil moisture and nutrients are way out of whack.

**Comment by pamduncan** [comment]
Does it matter that this was a existing world that was upgraded from previous 7.0 stagings? (I did mention that).   I had not had any world layer issues until this build.  As I mentioned i had a very nice world with a  good range of biomes and well balanced plant life and animals etc. -  I did not see a lot of the other issues some had reported until this update.  The 'frozen' world appeared right after the staging update was installed and the world loaded and it was the same world as all our buildings were there still.  The turn to the tan like ground with the grass and plants showing and no longer snow covered happened as we were playing - it was just like when your TV screen blinks out for a second and then the next video frame is different and the snow covered trees and bushes and ground and then it looked like the above.  It was a very odd experience.  Never had a world change like that in the middle of playing.

**Comment by pamduncan** [comment]
Snow is gone but the world appears to still be mainly all one biome, not the diverse world it once was with a few of each biome.   This is an improvement over snow and then tan snow/dirt but missing biomes will cause an issue eventually as there are many things that are supposed to be biome specific i would need the biomes for?  I so seem to have all my animals and such... just missing some diversity

[![Screenshot from Gyazo](https://gyazo.com/6eed4147a88046ec2b181850bc7eb6e9/raw)](https://gyazo.com/6eed4147a88046ec2b181850bc7eb6e9)


https://www.dropbox.com/s/ah4510ckmcqr18m/pamelad_EcoGS_2018-01-30_23-49.zip?dl=0

**Comment by knexer** [comment]
So I believe this to be related to migrating an old 7.0 save to #7da08558, as you suggested - I've ticked a few worlds through several hundred ticks and haven't seen this happen.  I'm going to go ahead and resolve this, but if it does happen in a world that was generated on #7da08558 or later please don't hesitate to open a new bug or reopen this one!
