### ISSUE TITLE
Minimap tooltip should show all the trades available at a store

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#373]
Make a nice 'tostring' function on TradeOffer that colors them up all pretty. You can use the Inventory.ToString function too to make it easier, and then string.join to join them all together (linq it all up)

**Comment by metachronism** [comment]
isn't this going to be crazy verbose?  you might have 10s of 100s of tradeoffers in any given store, with multiple items per offer
