### ISSUE TITLE
Dead mushrooms don't really look dead

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3730]
![image](https://user-images.githubusercontent.com/23460210/35599682-d869d1c8-05de-11e8-9708-5761809eb1ce.png)

**Comment by keegan-o** [comment]
Added textures for dead mushrooms and urchins in master and tried them with the speed tree material but we will need a new standard (or just lambert is fine) pollutable shader that works for objects like this we want to pollute or to have healthy/dead textures.

**Comment by keegan-o** [comment]
Oh wait! May have figured it out, may be as simple as hitting rebuild on the plant script.

**Comment by keegan-o** [comment]
yep! fixed in master for next full build.
