### ISSUE TITLE
USER ISSUE: Under map

### ISSUE THREAD

**Issue by emead09** [StrangeLoopGames/EcoIssues#3731]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
I keep trying to leave my building but fall through the map over and over. 

**Expected behavior:**
I should be able to walk out the door and onto grass.

**Actual behavior:**
i fall through the map two or three times and land on my building.

**Comment by emead09** [comment]
Now before the server kicked everyone off. I was forever falling through the map and couldn't stop.

**Comment by emead09** [comment]
Right before I started to fall, i was placing mortared stone and fell

**Comment by stormoffires** [comment]
Server world file (Mediocre At Best 6.4.2)
https://drive.google.com/open?id=1_H2LONKB3AzLseflRAIGzogaqUD7bIKv

several other players now reporting the falling issue

**Comment by stormoffires** [comment]
![2018-01-31 2](https://user-images.githubusercontent.com/20627148/35654583-08f89b68-06ab-11e8-8759-cbc0612e2c2c.png)
player was attempting to build an island on hewn floors with mortared stone, hole is visible to all players however what he sees seems to be worse

**Comment by stormoffires** [comment]
Found a work around for the big hole issue seen by the player.
![](https://cdn.discordapp.com/attachments/332300540694364160/408380278109765653/20180131_165708.jpg)
(big hole view from Emead09)

used admin teleporttarget to move the player to another area. player relogged and the big hole went away. still have the above little hole in the water. 

![](https://cdn.discordapp.com/attachments/332300540694364160/408380278109765653/20180131_165708.jpg)
