### ISSUE TITLE
Suggestion: Allow logs to float down rivers

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3732]
Instead of felled trees sinking into water, they should float. Floating logs down a river was a form of log transportation for a long time.
https://en.wikipedia.org/wiki/Log_driving

**Comment by metachronism** [comment]
buoyancy is back on for logs, but they could use some kind of push force from rivers to move them along (if we can figure out a good way to do that)

**Comment by Senlarus** [comment]
If it's possible, maybe letting players push them would be a way to get them down a river or aqueduct?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#299
