### ISSUE TITLE
[Suggestion] Adding Chemistry

### ISSUE THREAD

**Issue by HerrGrinsel** [StrangeLoopGames/EcoIssues#3733]
Basic idea is to add new recipes that help:

- to grow plants (artificial fertilizer, keep pests etc away)
- create nutrition pills (substitute for plants/animals who might be endangered)
- maybe medicine (cure plant or animal diseases, maybe diseases of the player)
[example: flu - increases the loss of calories, small pox - reduces the the number of maximum items that can be carried...etc.]
- reduce CO2 by binding it or bind pollutants in the environment
- also create basic or advanced componentens like ammonia, hydrogen, alcohol, etc.

Starting with electrolysis of water (creates oxygen and hydrogen), using nitrogen from the air, or distilling fruits etc for alcohol.
Recipes also require a chemistry station and more complicated recipes an advanced version

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#298
