### ISSUE TITLE
[Staging Beta 7.0.0 #71fcbff4]  Logging Damage skill will not unlock even with max skill in logging efficiency

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3738]
Have Logging Skill and there is a new skill 'Logging Damage" which should have been unlocked by Logging Efficiency but even with max level in Logging Efficiency, Logging Damage will not unlock

[![Screenshot from Gyazo](https://gyazo.com/4938c9ba1688cdf5169eb440954122cf/raw)](https://gyazo.com/4938c9ba1688cdf5169eb440954122cf)

**Comment by craig-jong** [comment]
fixed in staging
