### ISSUE TITLE
[Suggestion] Allowing us to use a water block in Possibly The Unused Bucket for Designing water features

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3740]
As Admin you can give yourself a water block , which if you dig a hole will allow you to place this, its a bit weird when trying to place more than one together as water sometimes decides to let you place, but trying to get a pond or moat going is a bit awkward. (also splash effects seen off at times and hard to remove, this sometimes happens if you accidently dig under water and it starts flooding)

I know that when a player enters the water Eco detects that this is happening (on two blocks of water you go into swim mode) maybe bring the Bucket back and put in a detection that it will **only** fill one block of water source in it when standing in water (forcing player to make multiple trips) maybe add calorie consumption when using bucket (leaving the finer points and game mechanics to you guys as normal)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#297
