### ISSUE TITLE
[Feedback][Suggestions] (Beta Staging 71fcbff4)

### ISSUE THREAD

**Issue by NewtonGitHub** [StrangeLoopGames/EcoIssues#3746]
[F] The new calorie meter is inconvenient, it was better being able to see your exact remaining calories at a glance.

[F]- Current skill tree / scaling are still too restrictive, it will cause a lot of negative feedback on Steam if server populations don't climb drastically after steam launch. Server settings and effects of collaboration not clear enough for new players. Average server populations aren't enough to support the current system without many periods of time where the only person with a certain ability is offline.

[S]- Tidying up the tech tree a bit could solve this a little bit, theres currently no distinction between specialist skills like smelting and basic tools like using a shovel.
Single purpose specs like logging and digging that are actually just basic actions should be combined into a "manual labour" spec that increases eff for all tools or folded into related specs - example: logging and hewing combined into a "tree processing" spec.

[S]- Implement a discount for specs in the same profession and a bonus for having the majority of your specs in 1 profession. People who have already mastered 1 facet of a craft do not require the same amount of training to learn another as a complete beginner and the more facets they know the easier it is to learn a new one. 
       Depending on the number of specs within a profession you should implement a system something like this:
Our example profession called "Apple Bobber" has 4 specs inside it:
When you take your 2nd spec within the Apple Bobber profession you become a journeyman "AB"
When you take your 3rd spec you become an Expert AB
When you take a 4th you become a Master AB

      Perhaps the reward is an incremental boost to eff and speed across all skills in that profession. up to an extra 10% at master. so a master AB can get up to 90% reductions across AB recipes etc..

[F] Stack size differences among carried goods are still arbitrary.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#296
