### ISSUE TITLE
Dark shadows on logs

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3748]
![image](https://user-images.githubusercontent.com/6262198/35650418-dccdf322-0690-11e8-8fed-6abb91e4f7ca.png)

When looking at them at a steep angle

**Comment by metachronism** [comment]
the verts on the edge have smoothed normals @keegan-o

**Comment by elfl0rd** [comment]
Happens with 3 log in block.
![default](https://user-images.githubusercontent.com/4980243/49965097-4a4d6f00-ff2d-11e8-98ac-d134620a64f0.png)

**Comment by beastyn** [comment]
here #12839 #12839
