### ISSUE TITLE
Staging #71fcbff4 [Severe Bug] - If disconnected before character creation you can no longer play that server

### ISSUE THREAD

**Issue by NewtonGitHub** [StrangeLoopGames/EcoIssues#3750]
If you get disconnected before saving your initial character when first joining a server, when you reconnect you have no UI, and can't do anything except walk around and open the escape menu. Hotkeys do not work.

**Comment by MarjieAVolk** [comment]
Do you have any error logs from this happening?

**Comment by NewtonGitHub** [comment]
No it didn't return any errors, I can tell you it happened on one server
because I crashed during character creation. It happened on a second server
because I left intentionally during character creation. Same result on both
servers.

On Feb 2, 2018 9:58 AM, "MarjieAVolk" <notifications@github.com> wrote:

Do you have any error logs from this happening?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/StrangeLoopGames/EcoIssues/issues/3750#issuecomment-362441921>,
or mute the thread

**Comment by MarjieAVolk** [comment]
Okay I've been able to repro this.  As a workaround, I believe that restarting the game will make the problem go away.  I am working on a real fix now.
