### ISSUE TITLE
 [Art] Give priority over Building blocks that is next to a stockpile to stop windows turning

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3751]
**Version:** 0.7.0.0 beta staging-71fcbff4

![snap1476](https://user-images.githubusercontent.com/29383891/35651865-2210edca-06d9-11e8-8031-bb5133a4e43b.png)
As can be seen the Stockpile contents next to a building has priority over the building and often windows (also can effect other blocks) can interact with this first instead of the main building.

sometimes this can also happen if a building is placed against dirt, raw stone etc. (not sure how that bit can be overcome)

**Comment by keegan-o** [comment]
fixed in master for next full build
