### ISSUE TITLE
USER ISSUE: Cart Hauling Visual Bug

### ISSUE THREAD

**Issue by TopSecretPorkChop** [StrangeLoopGames/EcoIssues#3753]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Haul a cart (happens occasionally though maybe more frequently at certain spots)

**Expected behavior:**
Scene renders normally

**Actual behavior:**
Scene (world) disappears except for stars, moon, and asteroid.

**Comment by SlayksWood** [comment]
Seems fixed.
