### ISSUE TITLE
Suggestion private messages should not show any other text

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3758]
**Version:** 0.6.4.2 alpha

**Expected behavior:**
when i get a PM in game and i click on it, i should ONLY see my messages between me and that person	

**Actual behavior:**
when you click on the name you see all ticked messages (trading/crafting and so on)

**Comment by MarjieAVolk** [comment]
This is intended, to allow you to keep getting notifications as normal while in a pm channel.
