### ISSUE TITLE
Treasury Turned into a Currency Exchange when Placed.

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#3760]
Had someone else on the World make me a Treasury, and when I placed it, it popped up as a Currency Exchange.

**Comment by sirPattrick** [comment]
Its on Mediocre at Best Server,  Running version 6.4.2.  After Picking up the Treasury from the chest, I did  open a Currency exchange, I don't know if somehow when I opened the Currency exchange it changed the treasury into another Currency exchange, Just figured you would like to know.  When placing the Treasury, It didn't show the guide for where it was being placed.  I put it down and then it showed up as the Exchange.

**Comment by keegan-o** [comment]
Wasn't able to reproduce this. Might be related to the fact that the icons are the same?

**Comment by craig-jong** [comment]
Can't get this to reproduce, so if this problem persists in 7.0+, please reopen it.
