### ISSUE TITLE
[Perf] Introduce ArrayPooling for Array2D

### ISSUE THREAD

**Issue by ndrwrbgs** [StrangeLoopGames/EcoIssues#3761]
Found [here](https://www.nuget.org/packages/System.Buffers/), the ArrayPool class would greatly help remove allocations from Array2D which is created-thrown-away a lot during the game.

However, to do so properly would require making Array2D a leased-style-item, where folks should `Dispose` of it when they're done with it. Given the size of that change (and moreover, the fact that the team would need to make sure everyone is aware that Array2D should be properly `Dispose`d for full benefit), leaving this one to the team.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#295
