### ISSUE TITLE
PERF: ServerGC?

### ISSUE THREAD

**Issue by ndrwrbgs** [StrangeLoopGames/EcoIssues#3762]
Has anyone run a comparison of enabling [Server GC](https://blogs.msdn.microsoft.com/seteplia/2017/01/05/understanding-different-gc-modes-with-concurrency-visualizer/) for the server? It's not a silver bullet, but based on the patterns in the code can sometimes make a big difference if you're spending a lot of time in GC.

(but I think the GC woes were already fixed? If so, not worth looking into [right now])

**Comment by metachronism** [comment]
more concerned about GC on the client than the server, but the server certainly could do some profiling here to at least see where we are at and if there are any easy wins.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#294
