### ISSUE TITLE
[Suggestion] Thirdperson View have ability to Have a key programmable in Controls

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3763]
i like the third person view, but can get a bit annoying to have to open the backpack every time then tick or untick it, would be nice to have the ability to press a key to toggle this on/off.
Placing this in Controls then Players can Decide which key they want for this.

reason Asking for this because game is darker now i use my Meteor Shard that hangs off my backpack as a light source in third person

**[Suggestion] let Meteor Shard gives us light in normal view not just in 3rd person #3714**

 (brightness control is ok at night, but same setting is too bright during daytime)

**Comment by MarjieAVolk** [comment]
You can still use /thirdplayer.  Which admittedly is more than one key.

**Comment by Conchipedia** [comment]
and ONLY if admin

**Comment by MarjieAVolk** [comment]
what really?  Guess it should be made not admin in that case

**Comment by Conchipedia** [comment]
i just looked at /help list and it does seem to be in the user part, but still having it allowed to be set to a key would be nice, as i can see more players using it this way, because when i was watching the Video of  MJ interviewing Johnk she clicked on 3rdplayer and spent most time with it on (which is not useful for doing stuff as you don't get to see all the right messages) so a keypress to turn it off quick would have been easier than telling her to open backpack tick thirdperson on or off.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#293
