### ISSUE TITLE
checkmark or you already know this skill in research table [suggestion]

### ISSUE THREAD

**Issue by Arend90** [StrangeLoopGames/EcoIssues#3765]
![image](https://user-images.githubusercontent.com/31536813/35688336-402816ba-0771-11e8-9cc9-fa6fd3568278.png)

**Comment by Conchipedia** [comment]
We already have a on scrolls if we have learned them
![snap1480](https://user-images.githubusercontent.com/29383891/35688573-5e3e4b0e-0769-11e8-9243-4172d1800010.png)
maybe add this to a skillbook that we have crafted (something like you already crafted this) to save players accidently duplicating 
![snap1481](https://user-images.githubusercontent.com/29383891/35688618-7c3aa5ee-0769-11e8-944d-9892ff84b9d0.png)
or possibly add something to research table ?
![snap1483 edited](https://user-images.githubusercontent.com/29383891/35688951-4a4226b0-076a-11e8-94a6-4ba6165e2e5e.png)
green tick for example saying that this table has crafted this object

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/10 (And merging it with another suggestion)
