### ISSUE TITLE
In fullscreen, windows bar is on top of game

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3769]
This is current staging, on steam.

![image](https://user-images.githubusercontent.com/23460210/35706343-490e9522-075a-11e8-84a2-eca5a88044b1.png)

**Comment by Nanders** [comment]
This is a windows bug

**Comment by MarjieAVolk** [comment]
other games don't do it right soooo >>  Is there a workaround or anything?

**Comment by Conchipedia** [comment]
i think that only happens sometimes if you alt tab out or use a second monitor and it loses focus, i have only seen it once tonight rest of time is not a problem

**Comment by Nanders** [comment]
I have seen it in almost any game I have in my steam library. Windows key + click refocuses the window
