### ISSUE TITLE
Species population tooltips all say 0

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3771]

**Comment by Conchipedia** [comment]
this i got after a disconnect and restart
![snap1492](https://user-images.githubusercontent.com/29383891/35710481-9d06afd4-07af-11e8-8a72-04ad2eea4952.png)
 but i could see this 5 minutes before
![snap1489](https://user-images.githubusercontent.com/29383891/35710501-b729188e-07af-11e8-96e1-03873b0c4a76.png)

**Comment by MarjieAVolk** [comment]
@knexer I filed this because the tooltips were different from the welcome message, but I fixed that now, so now this bug is what conchita posted ^ lolol

**Comment by Conchipedia** [comment]
I logged in after not playing For over 12 hours and can see this
![snap1504](https://user-images.githubusercontent.com/29383891/35736534-49d9f6ec-0820-11e8-9d3f-a47253a990b6.png)
but i had to Disconnect for a graphic glitch and when i continued i now see this
![snap1505](https://user-images.githubusercontent.com/29383891/35736558-62326652-0820-11e8-89f7-d9fcd1c39383.png)

shouldn't this information never 0 when viewed again?
I keep trying to work out if it is after a period of time so i can reproduce this but can't manage that yet, the only consistent thing is seeing them all 0, its rare for me to see them with numbers

**Comment by MarjieAVolk** [comment]
Maybe you could compare this to the population graphs on the website?  I imagine you will see them spiking up and down like crazy

**Comment by Conchipedia** [comment]
will have a look next time i notice it going off (unless something fixed)

**Comment by thibaut-fagart** [comment]
I just discovered this dialog in the welcome message on login (single player server).
For me it shows everything at 0 too, and the website graphs shows all pops at 0 too.

Is there a way to trigger this  population census explicitly ?

**Comment by bootj93** [comment]
I am still having this problem, never seen any population in my graphs. Is there any update on this issue?

**Comment by Conchipedia** [comment]
i still get all 0's but i think it is because they disabled stats, hopefully it will come back in 7.2

**Comment by MarjieAVolk** [comment]
Yeah, stats have been disabled, so everything has been 0 for a while.  And yes, stats will be back in 7.2.  And also hopefully they perform well now :P

**Comment by MarjieAVolk** [comment]
But I believe this bug was filed when stats were still on.

**Comment by Conchipedia** [comment]
yes i believe it was, i seemed to be one of the only ones that couldn't get any numbers until i was online for quite a few hours, not sure if that bug disappeared before stats was turned off

**Comment by Conchipedia** [comment]
linking to this as it is about the Same Tooltip
[Suggestion] Making Ecosystem: tooltip easier to find like we have for Inventory #5453

**Comment by thibaut-fagart** [comment]
I confirm this works now as of 7.2

**Comment by MarjieAVolk** [comment]
Oh wait I was confused, okay still leaving this issue open because I believe it can still occasionally show this.
