### ISSUE TITLE
USER ISSUE: We can Swim on planted Bullrush

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3772]
**Version:** 0.7.0.0 beta staging-d2423858

![snap1493](https://user-images.githubusercontent.com/29383891/35709726-c3d0ae02-07ab-11e8-9941-cd4243b036d7.png)
![snap1494](https://user-images.githubusercontent.com/29383891/35709727-c3eb9af0-07ab-11e8-9c6b-68284cba8e22.png)
![snap1495](https://user-images.githubusercontent.com/29383891/35709728-c404d876-07ab-11e8-86a8-88037bc5a631.png)

**Comment by SeanAtr0n** [comment]
Fixed in svn
