### ISSUE TITLE
USER ISSUE: World Layers List has Double A to Z listing (confusing)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3773]
**Version:** 0.7.0.0 beta staging-d2423858

previously we had Everything in One A to Z list (at least it made sense even if we didnt know what they all were) now we are getting two of them with no visible gap
AirpollutionSpread  to Wolfcapacity
![snap1497](https://user-images.githubusercontent.com/29383891/35710377-fdac07c2-07ae-11e8-99ad-09683b3c8274.png)
![snap1498](https://user-images.githubusercontent.com/29383891/35710381-0532cd96-07af-11e8-9191-afb3170590fc.png)
and
AmanitaMushroomYieldPotential to WheatYieldPotential
![snap1499](https://user-images.githubusercontent.com/29383891/35710402-252afce0-07af-11e8-9ee0-4e9ac2965f88.png)

i think i can see why it was done, but having two alphabetical lists in one pulldown is so confusing, if you scroll down to fast you could be in second list and not even know you had ended the first one

**Comment by SeanAtr0n** [comment]
That sorting is intentional for now, should be cleaned up with
https://github.com/StrangeLoopGames/EcoIssues/issues/3371
