### ISSUE TITLE
[Suggestion]saving solo game saved worlds/persistent client solo game configuration information to appdata

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3774]
Suggestion:   If solo saved games were retained - saved to and loaded from appdata where other client persistent information is stored this would seem to solve the problem with accidental risk of loss of saved game when clean install is required for the client and or when the game files are deleted when opting in and out of Beta.  The game could be saved by name and even by version in specific directory so that the client would have accurate list of saved world to load depending on which version was currently installed.  We do this will a couple of games that have very busy beta options and users opting in and out of beta ona  regular bases and/or update through steam require file removal and clean install.  The saved games for local games run on the client saved in appdata give it a safe place to be without risking losing the saved game.  Unless the client is coded to specifically remove a saved game from appdata the only other way its going away is if the user goes into the appdata folder and deletes it entirely.  We have had many people that have 'accidently' deleted tehir solo game when doing a clean install to the same Eco folder when moving between stable and staging or doing a clean install to troubleshoot issues and to make sure they have all new files.  Unless they happen to remember to go into the storage folder for the solo server and make a backup they end up losing their game.

Also, there is configuration information that users often wish to save persistently from install to install of the client files and server configuration files are overwritten each time.  Configuration information such as the admin(s) permissions, difficulty settings, meteor settings, player's reputation, world dimensions and some EcoSIm settings (such as PlantDensity, SkillGainRate, BaseSkillGainRate, MaxHousingSkillRate, SkillDamageMultiplier) could be saved to a file in appdata and read and written back to the solo game configuration when being loaded so that the user would have settings persistent tha they have picked for the configuration of their solo game.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#292
