### ISSUE TITLE
[Art] Weird Graphic effect when deep underwater looking up and around

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3775]
**Version:** 0.7.0.0 beta staging-d2423858

![snap1515](https://user-images.githubusercontent.com/29383891/35742979-1718bb8a-0834-11e8-8373-78bc8b8b1c60.png)
![snap1516](https://user-images.githubusercontent.com/29383891/35742980-1735a27c-0834-11e8-9014-768deeec999b.png)
![snap1517](https://user-images.githubusercontent.com/29383891/35742981-17514dec-0834-11e8-9791-45adbcc8a7d3.png)
![snap1518](https://user-images.githubusercontent.com/29383891/35742982-176dd44e-0834-11e8-9699-2b988c1cf30c.png)
![snap1519](https://user-images.githubusercontent.com/29383891/35743083-53e31c2c-0834-11e8-9ea0-53091229dc04.png)

The last one took me time to do to prove its Not Meteor or the Sun , also on the sun you can see a sort of invisible Glitch as well.

looking at this invisible one, i think it might be the central point of the sky , but its only visible after you go down 20+ blocks or more

**Comment by metachronism** [comment]
no repro anymore
