### ISSUE TITLE
No Control Binding in Escape Menu for Swim Down

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3776]

**Comment by SeanAtr0n** [comment]
crouch == swim?

**Comment by MarjieAVolk** [comment]
crouch was removed

**Comment by Nanders** [comment]
Just needs to be added as Swim instead of crouch I think

**Comment by Nanders** [comment]
Just a UI bug

**Comment by SlayksWood** [comment]
As I understood it used to be Crouch, then it was removed, but we still have the ability to slowly walk on Ctrl.
You just rename it to swim, but Ctrl is not only swim. So it should be named like Dive/Sneak.

**Comment by WeaselDog** [comment]
Yes, can you change this to Dive / Sneak

**Comment by MrAnonymous110** [comment]
thanks, I will change
