### ISSUE TITLE
USER ISSUE: Room Volume Size = Volume Size of whole house. ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3777]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Make a room upstairs check size then make a room down stairs lead to by steps that is little bigger, check size of the volume of each room they will be same means the room volume size is size of the hole house we are on the Wisconsin server that's setup for single player and small groups. we checked all of our homes they all report room volume as the total volume of the whole house not sure if this was intended or not but if so then name of room volume should be changed to house volume. ?

**Comment by MarjieAVolk** [comment]
Are you sure your rooms aren't just joined?  Often if you have a staircase up to an upper room, those two rooms will be detected as one, because the staircase has to be somewhat open to get through

**Comment by midn8t** [comment]
yah it issue with stair case hole i am sure, which seems to be a common thing for all the houses on server ?

**Comment by MarjieAVolk** [comment]
Yeah stockpiles have a range in which you can reach them, if you are vertically outside that range you will not be able to reach them.  And while I wouldn't necessarily call it 'intended', currently staircases between rooms will typically cause them to be treated as the same room.
