### ISSUE TITLE
Third Person: mining/digging animations offset from block breaking

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3778]
The block will break, and then the character starts animating.

Also, it seems like the same animation is played for picking up & placing dirt?  Placing dirt animation looks strange at least.

**Comment by SeanAtr0n** [comment]
Changing this would require completely different timings for first person vs 3rd person actions

**Comment by MarjieAVolk** [comment]
I figured something like that would be the case

**Comment by SlayksWood** [comment]
Now the blocks don't break when animation start. It seems fixed.
