### ISSUE TITLE
Carrying slot label should be at bottom of frame, so as not to confuse it with control names. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3779]
![image](https://user-images.githubusercontent.com/6262198/35751974-1dc2b244-080f-11e8-98cb-5c6802df42a2.png)

**Comment by MarjieAVolk** [comment]
imo it should be under the icon and de-emphasized

**Comment by WeaselDog** [comment]
The UI has been readjusted so it is more clear now.
![CarryingUI](https://user-images.githubusercontent.com/47330823/71291472-a2306a00-2327-11ea-8bf6-bee0ab6198d1.png)
