### ISSUE TITLE
Campfire Power slot missing

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#378]
Nothing can be crafted

https://files.slack.com/files-pri/T09J4G2G7-F1MH47PT7/pasted_image_at_2016_06_29_03_03_pm.png

**Comment by craig-jong** [comment]
Also note that it says its powered, which is incorrect.

**Comment by craig-jong** [comment]
We should also remove the power grid option from things that do not use a power grid

**Comment by metachronism** [comment]
fixed
