### ISSUE TITLE
Skill window hotkey not shown

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3782]

**Comment by elfl0rd** [comment]
Yea, confusing.
![default](https://user-images.githubusercontent.com/4980243/49964993-f80c4e00-ff2c-11e8-9bb6-859d0cd3ed7e.png)

**Comment by johnkslg** [comment]
No room

**Comment by elfl0rd** [comment]
![unknown](https://user-images.githubusercontent.com/4980243/51371138-54552580-1b0a-11e9-8a9a-f7017624eb19.png)
