### ISSUE TITLE
USER ISSUE: Tree Growing in Waterfall

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3790]
**Version:** 0.7.0.0 beta staging-05b7abef

![snap1522](https://user-images.githubusercontent.com/29383891/35752964-cc442424-0855-11e8-9e1c-72958b2b9229.png)
![snap1523](https://user-images.githubusercontent.com/29383891/35752965-cc5ba0e0-0855-11e8-94e4-cc8ddd46366b.png)
![snap1524](https://user-images.githubusercontent.com/29383891/35752996-ee64f5e2-0855-11e8-9ae9-e9732f0a642c.png)

**Comment by MarjieAVolk** [comment]
This looks valid.  It's growing on solid land, just close to the water
