### ISSUE TITLE
USER ISSUE: Oak tree takes 20 hits to chop down and they refuse to fall over even after removing All branches and the top

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3791]
**Version:** 0.7.0.0 beta staging-05b7abef

they just sit there and creak
![snap1527](https://user-images.githubusercontent.com/29383891/35753511-03c75090-0858-11e8-8dfe-32ef98950486.png)
![snap1528](https://user-images.githubusercontent.com/29383891/35753512-03df82d2-0858-11e8-8e9e-608aa81ce755.png)

they only falll when after removing all the rest and hit the tree again

**Comment by Conchipedia** [comment]
Also when it falls over eventually NO DEBRIS

**Comment by SeanAtr0n** [comment]
looks like oak needs a higher spawn debris chance

**Comment by MarjieAVolk** [comment]
That's only one of the several issues reported here

**Comment by metachronism** [comment]
the trunk collider needs to be a capsule, otherwise the trunk balances perfectly

**Comment by Nanders** [comment]
Fixed
