### ISSUE TITLE
Mysterious error when trying to propose law

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3797]
Arend had a bunch of laws that he wasn't allowed to pass.  They look valid.  An error bar is shown with no message in it.

![image](https://user-images.githubusercontent.com/23460210/35754088-0e4abf5c-0817-11e8-9b0e-cffb7a9e389e.png)
![image](https://user-images.githubusercontent.com/23460210/35754102-16278f84-0817-11e8-88f9-7ee4b8076e80.png)

**Comment by CompactDisc** [comment]
I get these all the time as well.

**Comment by rainfarmer** [comment]
this has been fixed.
