### ISSUE TITLE
Mature huchleberries invisible in my garden

### ISSUE THREAD

**Issue by metrotyranno** [StrangeLoopGames/EcoIssues#38]
http://ecoforum.strangeloopgames.com/topic/430/mature-huchleberries-invisible-in-my-garden

Client : alpha 0.2 release 1b4cf1b7
server : Linux server.

I can see seeds I plant, the first step of the plant too. This morning all plants look mature but huchleberries have disappeared.
I can grab those invisible huckleberries.
Leaving the game and reconnecting did not change that.

**Comment by Egrof** [comment]
Had the same problem with a Windows server.
