### ISSUE TITLE
Chat feedback

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#380]
chat window is missing write cursor when hitting enter ( for user feedback)

**Comment by noblackthunder** [comment]
text cursor is there when i am in window mode

**Comment by noblackthunder** [comment]
cursor works for me in window mode but not fullscreen

**Comment by metachronism** [comment]
marjie can you take a look at this while you are in chatwindow land

**Comment by MarjieAVolk** [comment]
Sure
