### ISSUE TITLE
USER ISSUE: Can't put skill points in Specialties.

### ISSUE THREAD

**Issue by Kazefune** [StrangeLoopGames/EcoIssues#3806]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Learn Logging 
for example.
Then try to put Skill Points in Logging to get the other skills in the Logging Tree.

**Expected behavior:**
Be able to put points in Specialites	,

**Actual behavior:**
Can't but skills in Specialites and cant progress in the game because of it.

**Comment by Kazefune** [comment]
We have these mods on the server: 
http://ecoforum.strangeloopgames.com:4567/topic/3274/roadtool-fix
http://ecoforum.strangeloopgames.com:4567/topic/3275/quick-fix-for-fishery-and-mechaics
http://ecoforum.strangeloopgames.com:4567/topic/3252/mw-s-mods-6-4

**Comment by MarjieAVolk** [comment]
Specialties are working fine for me.  And logging specifically is also.

**Comment by MarjieAVolk** [comment]
What exactly are you seeing?  The plus button for eg. Logging Efficiency continues to be disabled after learning Logging?  Have you both used a skill scroll and learned the specialty?  (just gotta check)

**Comment by Kazefune** [comment]
https://gyazo.com/0eedb3ff2dc37d04b4b82a3e895cdf8b

It looks like this. On all specialties

**Comment by MarjieAVolk** [comment]
It looks like you've learned it, and maxed out all the skills?  Is that not the case?

**Comment by Kazefune** [comment]
Maybe Logging is a bad a bad example. With smelting it says I need Smelting 4 to learn alloy smelting. And I cant learn Smelting 4. Is it a skillbook I need to get Smelting 4?

**Comment by MarjieAVolk** [comment]
Ah, for Smelting I do see an issue.

**Comment by Kazefune** [comment]
Yeah and its like that for all the Specialties.

**Comment by Kazefune** [comment]
Hmm we are currently trying on a fresh server with no mods to see if we are just stupid or not :)

**Comment by Kazefune** [comment]
It did not work on the fresh server, so then I need to ask. Are you supposed to be able to put more skills in the specialties?

**Comment by Kazefune** [comment]
Smelting looks like this:
https://gyazo.com/633f1647d3da233c5fa6c65f111c339e
https://gyazo.com/6903c5744e43c8f4f66c553fe5664acb

Is it supposed to be like that and I need a book I don't about?

**Comment by MarjieAVolk** [comment]
No it is not supposed to be like that.  You should not be allowed to spend points in a specialty unless you have researched it, at which point it should be free game.

So did you max out those other skills, or they just say maxed out as soon as you take the specialty?  And does everyone on the server see this?

**Comment by MarjieAVolk** [comment]
I do notice that the skill branch that you show as not working (Alloy Smelting) has been moved to a different specialty in the current version.  Not sure if that is related

**Comment by Kazefune** [comment]
No I have maxed out the Smelting Tree my self. But the gray one says it needs Smelting 4 to be researched. And I don't see any way to get Smelting 4

**Comment by MarjieAVolk** [comment]
Okay, well in that case I am going to say this is probably fixed in the current staging build.  Because on my version I see that tree has been moved, and it currently is unlocked when I take the specialty.  I know we just did a bunch of tech tree fixes.  I might recommend updating to the staging version, if that is an option.  I think it is pretty solid.

**Comment by MarjieAVolk** [comment]
We are going to do a beta candidate release in the next day or two also, if you'd rather wait for that.

**Comment by Kazefune** [comment]
I think I will wait. I don't know how mods work with the staging build.

**Comment by MarjieAVolk** [comment]
Okay, sorry about this problem!

**Comment by Kazefune** [comment]
No problem its a game that is in alpha and we know it is so. That's why I sent the report. Thanks for the help :D
