### ISSUE TITLE
Deed ui layout for vehicles is odd

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3809]
![image](https://user-images.githubusercontent.com/23460210/35761762-2f72ef0e-0841-11e8-9e74-f06f69773f1a.png)

**Comment by elfl0rd** [comment]
@D3nnis3n deed UI changed
![default](https://user-images.githubusercontent.com/4980243/49964894-b7143980-ff2c-11e8-944f-a13783d1083b.png)
