### ISSUE TITLE
Going to website from game does not pass auth token

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#3814]
In game, use 'propose law' or 'run for office' or 'view law' buttons to go to webpage

sends to url http://74.85.92.174:30111/lawsadd.html?username=test&authtoken=

with no authtoken

**Comment by metachronism** [comment]
authtoken is null for steam clients, isnt it?

**Comment by rainfarmer** [comment]
oh you're right, I'll have to setup a special way to give steam only users, auth tokens

**Comment by johnkslg** [comment]
Fixed long ago.
