### ISSUE TITLE
USER ISSUE: You can't click waypoints on map

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#3816]
**Version:** 0.7.0.0 beta staging-4dbe06ca

**Steps to Reproduce:**
Put down a waypoint
Click it on the minimap

**Expected behavior:**
Let me delete it

**Actual behavior:**
Nothing

**Comment by craig-jong** [comment]
As a note, it makes the tutorial regarding these waypoints slightly confusing.

**Comment by GWraith1985** [comment]
This is fixed in last 3 staging builds.
