### ISSUE TITLE
World Object Status, Cancel Projects, Room Recognition seem to break sometimes

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#3817]
![image](https://user-images.githubusercontent.com/14983165/35763352-1cba04f6-085f-11e8-93c0-c6421add138a.png)

I was trying to get my laboratory to stop crafting, so I tried to cancel the project-- it's ingredients are ones that could easily be carried by me or there was room in the storage chest they came from-- but it failed with no error message.

I then ripped out half my wall, but all the world objects in my room still stay active. I had been having the reverse problem earlier where the room was not being recognized as a room despite in previous play sessions using the exact same room with no problem. Can't stop it by picking up and putting back down the world objects since it is busy crafting away.

**Comment by keegan-o** [comment]
Maybe this is two bugs-- not being able to cancel a project, and Rooms taking way longer to update than they should. After typing this all out, I went back to the game-- and everything was still broken, until I hit another wall piece with the hammer-- then the room finally recognized it was no longer a room and the crafting table stopped.

**Comment by keegan-o** [comment]
(Still can't cancel my project or remove the crafting table)

**Comment by metachronism** [comment]
this is a well known rooms plugin bug

**Comment by metachronism** [comment]
that I fixed
