### ISSUE TITLE
USER ISSUE: Continue doesn't refresh

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#3819]
**Version:** 0.7.0.0 beta staging-4dbe06ca

**Steps to Reproduce:**
Connect to a server
Server goes offline
Continue doesn't update

**Expected behavior:**
Updated to show online server when server is up

**Actual behavior:**
Nothing

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3619 - renamed that one to be more clear
