### ISSUE TITLE
USER ISSUE: Report bug tool bug.

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3821]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
1. Start in the main menu
2. Click options
3. Click Report Bug
4. <nothing happens>
5. Join a server
6. Report window pops up

**Expected behavior:**
The window should pop up when reporting from the main menu

**Actual behavior:**
Instead it pops up when you enter a game.

**Comment by MarjieAVolk** [comment]
sigh I've fixed this before

**Comment by MarjieAVolk** [comment]
Oh I didn't see this was on an older version.  Yeah this is fixed in staging.  Phew lol
