### ISSUE TITLE
Free stuff

### ISSUE THREAD

**Issue by gurbazsingh** [StrangeLoopGames/EcoIssues#3822]
hey guys 
i am v poor
i need stickers and shirts
thank yall

**Comment by Phlo123** [comment]
I think this can be solved with modding! @SeanAtr0n I got this if you don't mind.
@gurbazsingh if you could elaborate on the issue it would help a lot; I see the struggle is real with the poverty stuff as you had to cut back on the word "very" (75% discount)

**Comment by Conchipedia** [comment]
We need another Competition like the PAX one for the Poor Guys
![enamel pin](https://user-images.githubusercontent.com/29383891/35769101-ce68ec50-08fd-11e8-810d-a73376458149.jpg)

<img width="685" alt="t-shirt" src="https://user-images.githubusercontent.com/29383891/35769087-9b1f0b54-08fd-11e8-901e-7ebfa7de964a.png">

**Comment by MarjieAVolk** [comment]
omg this made my day

**Comment by johnkslg** [comment]
Perhaps someday we have a giveaway, until then closing the bug for now :/
