### ISSUE TITLE
USER ISSUE: Placing Dirt on edge of water level takes a while for Dirt to Physically drop down

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3823]
**Version:** 0.7.0.0 beta staging-dbf80025

**Steps to Reproduce:**
place dirt against the side of the edge of water

**Expected behavior:**
drop down to the lowest level straight away (like it does normally against a wall on land) and become a placed block

**Actual behavior:**
it sits at the top and takes ages to drop, sometime you can place quite a few that have gaps underneath before it will decide to drop
![snap1551](https://user-images.githubusercontent.com/29383891/35768560-7e3d5da4-08f5-11e8-93e1-b947faad2976.png)
![snap1552](https://user-images.githubusercontent.com/29383891/35768561-7e564256-08f5-11e8-93c6-396957d7c4d7.png)
![snap1553](https://user-images.githubusercontent.com/29383891/35768569-ab727f98-08f5-11e8-8e11-a41ed9f3b49d.png)
![snap1554](https://user-images.githubusercontent.com/29383891/35768570-ab8f790e-08f5-11e8-90a5-79716b1018b5.png)

It works ok underwater just only glitches above water as can be seen in this snapshot
![snap1555](https://user-images.githubusercontent.com/29383891/35768610-4e83db00-08f6-11e8-9dd8-91b1a597b89d.png)

the only way they will seem to drop is to dig another piece of dirt near them so it sort of updates the surrounding area (not sure exactly how to word this properly)

**Comment by Conchipedia** [comment]
this might have been due to the lag issue that was plaguing the game haven't been able to duplicate this in later versions so will close this

**Comment by SeanAtr0n** [comment]
fixed this a while back
