### ISSUE TITLE
USER ISSUE: unable to cancel a project until i had ingredient in inventory

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3824]
**Version:** 0.7.0.0 beta staging-dbf80025

**Steps to Reproduce:**
i ordered 100 Pitch on a campfire , which required 1000+ Wood pulp, i then decided to move campfire and so i cancelled the project, but it gave me this message
![snap1556](https://user-images.githubusercontent.com/29383891/35768913-d91490c6-08fa-11e8-81f0-ac489e1ac0f5.png)

i could ONLY cancel the project if i had some wood pulp in my inventory

**Comment by MarjieAVolk** [comment]
I can't repro this.  I created several different orders, including an order for 100 pitch on the campfire, and I was able to cancel each fine without ever having items needed by the order.  I also tried adding some ingredients to the project and then cancelling it, and this also worked for me.

Do you have any other details that might be related this issue?

**Comment by seccombew** [comment]
Closing to consolidate dupe #11235
