### ISSUE TITLE
[Art] Urchins and Clams some are dead, but no real change in what they look like

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3829]
**Version:** 0.7.0.0 beta staging-dbf80025

![snap1560](https://user-images.githubusercontent.com/29383891/35771132-a99d32b0-091f-11e8-941f-18dec9083c90.png)
![snap1561](https://user-images.githubusercontent.com/29383891/35771133-a9b659b6-091f-11e8-8fa6-8313b4c62a89.png)
i tried 2 different coloured ones (just in case one was dead and changed colour)   but they are both dead

**Comment by keegan-o** [comment]
fixed in master for next full build-- clams will still be tough to spot, but I'm calling that one a feature (they will totally be emptied out though when dead so if you look close you'll be able to tell)
