### ISSUE TITLE
USER ISSUE: Flat Steel Windows

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#3830]
**Version:** 0.7.0.0 beta staging-dbf80025

**Steps to Reproduce:**
Try to build a Flat Steel Windows, needs rank 5 of Steel Construction, which it only goes to Rank 4

**Expected behavior:**
Go up to rank 5

**Actual behavior:**
Can't go up to rank 5. Either lower this to Rank 4, or increase Max_Level of Steel Construction to 5

**Comment by MasterWhoMW** [comment]
Also, Framed Glass Windows says it needs rank 6(Max_Level is 4)

**Comment by MarjieAVolk** [comment]
@craig-jong we should be able to add a check for this, if something requires a skill that is higher than the max level of that skill it should throw an exception somewhere

**Comment by Senlarus** [comment]
Rugs are still this way.

Brandon
