### ISSUE TITLE
[Art] Saguaro Cactus showing no info when looking at with axe, also goes bright green

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3831]
**Version:** 0.7.0.0 beta staging-dbf80025

![snap1557](https://user-images.githubusercontent.com/29383891/35771398-00ea3b04-0924-11e8-9506-fbc8c033878c.png)
![snap1558](https://user-images.githubusercontent.com/29383891/35771399-0104dbbc-0924-11e8-90a8-a9f10c0cae03.png)

**Comment by MasterWhoMW** [comment]
You can cut it down, and when you do, chop again, and it splits in half. Each half will give you 10 logs, dunno if this is supposed to happen(Cactus logs? Maybe Plant Fibers...)

**Comment by Conchipedia** [comment]
it splits lengthways like slicing french stick, surely thats impossible with an axe? with a Machete maybe

**Comment by craig-jong** [comment]
Logs are intended currently. The internal structure of a cactus is kinda log-like so we're going with that for now. We will likely change it later.

**Comment by Nanders** [comment]
The specific issues described in this bug are resolved
