### ISSUE TITLE
USER ISSUE: Brightness is horrible on Raw Stone at Certain Distances (200% looks good at night but ends up too bright in the day)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3833]
**Version:** 0.7.0.0 beta staging-dbf80025

![snap1563](https://user-images.githubusercontent.com/29383891/35771431-9e223ed0-0924-11e8-82eb-b728b7bfae5e.png)
![snap1564](https://user-images.githubusercontent.com/29383891/35771432-9e3df828-0924-11e8-8c89-a089c9fc714c.png)
![snap1565](https://user-images.githubusercontent.com/29383891/35771433-9e575ba6-0924-11e8-8330-2602204a4884.png)

no settings changed just walking down steps

**Comment by Conchipedia** [comment]
i have been having a hard time with getting brightness right since the New slider was introduced, because its too dark at night its hard to distinguish some blocks, so i change it so i can just see a slight difference then when it comes to daylight it ends up too bright

**Comment by Conchipedia** [comment]
![snap1566](https://user-images.githubusercontent.com/29383891/35771519-d747bbda-0925-11e8-922c-06aa8125617b.png)
this is default setting in a mine, hard to distinguish the blocks, never had any problems before new slider came in

**Comment by Conchipedia** [comment]
![snap1594](https://user-images.githubusercontent.com/29383891/35827602-91e80f5a-0ab4-11e8-9295-785ac01d546c.png)
At 200% the brightness takes away the details of the moon and meteor, but just about bright enough to work at night, its still very difficult to get this balance in game

**Comment by keegan-o** [comment]
I think this is less an issue with the brightness slider than the balance of how dark it is at night. Unless the brightness slider actually breaks brightness when you adjust it and doesn't allow you to return to 100% properly...

**Comment by Conchipedia** [comment]
if i go higher than 100% at night i can see the blocks better but i lose the definition of the moon and meteor it just appears as a horrible bright white circle or white blon, the previous versions that didn't have the slider in was perfect, i could see at night, wasn't bright in the day and everything showed up lovely even the the sunrays and moonrays, now i cannot get a perfect balance as i have to keep changing it all the time 😭

**Comment by keegan-o** [comment]
There have been some good tweaks for this recently, closing this for now as hopefully now you won't have to crank up brightness at night anymore.

But I know we still need plenty of concentrated work on the lighting in the game-- it will continue to be improved.
