### ISSUE TITLE
USER ISSUE: Water no longer flows.

### ISSUE THREAD

**Issue by GWraith1985** [StrangeLoopGames/EcoIssues#3834]
**Version:** 0.7.0.0 beta staging-dbf80025

**Steps to Reproduce:**
Current staging build I can no longer channel water by digging stepped channels. I have also tried different materials and the water will not flow any further in this build.

**Expected behavior:**
Continue to flow as long as steps down were created to continue the flow.

**Actual behavior:**
Freezes in its block and only flows straight down instead of forward.

**Comment by GWraith1985** [comment]
![river broken](https://user-images.githubusercontent.com/36001726/35771817-bf1a72a2-0900-11e8-814c-1d914c4df6ef.jpg)

**Comment by GWraith1985** [comment]
![river broken beta](https://user-images.githubusercontent.com/36001726/35773820-01fa2476-092b-11e8-9d23-6d7527bc1843.jpg)

Water only travels 9 blocks from a source. No amount of digging will make it go further. Also verified this issue is in the Steam Release 7.0 Beta

**Comment by metachronism** [comment]
this is intended.  water will only travel farther when funneled with an aqueduct
