### ISSUE TITLE
USER ISSUE: Launching a multiplayer server via the game client woes

### ISSUE THREAD

**Issue by MagicBackPack** [StrangeLoopGames/EcoIssues#3842]
![20180203195952_1](https://user-images.githubusercontent.com/36118065/35773333-d04db522-091c-11e8-8381-454da8215b0f.jpg)
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
attempt to create new game with the checkmark for allow friends to join, create new game, game launches and local client can connect, attempt to make a new game with the same name and receive an error about there being an existing file, UI then doesn't allow you any option to dismiss or try a new name

**Expected behavior:**
report the preexisting filename conflict, then open the text box to allow the user to choose a different name for the instance or select a different option from the main menu

**Actual behavior:**
UI is locked on the copy to clipboard or report a bug options and has to be force closed to allow the user to try again.

I have attached a screenshot of the screen (escape does nothing to dismiss the screen)

**Comment by MagicBackPack** [comment]
Ah found that clicking outside the prompt dismisses it, adding an escape hotkey and an x would help the user experience.

**Comment by MarjieAVolk** [comment]
Ah I see the confusion.  Okay, will put escape and/or x on there at some point

**Comment by WeaselDog** [comment]
No longer an issue. There is a much cleaner error message now:
![SameNameError](https://user-images.githubusercontent.com/47330823/70869828-8735b280-1f41-11ea-8f54-fbd306a804a0.png)
