### ISSUE TITLE
Server crashes when user completes an action [7.0.0]

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3843]
This is on a migrated world.

User (Keegan) was playing as an unlinked Steam user.

**Comment by MarjieAVolk** [comment]
what kind of action?

**Comment by Nanders** [comment]
Crashes silently with no stacktrace, any server action. 
In this case it was trying to pick up tomatoes, or send a chat message. One of Keegan's saves

**Comment by GWraith1985** [comment]
We are finding that a lot of times migrating older worlds through different 7.0 staging build make somethings fail that would not if you started the server with a fresh wipe. Just some info for testing purposes.

**Comment by MarjieAVolk** [comment]
I don't even know where to start with this one, who do I assign it toooooo....

**Comment by MarjieAVolk** [comment]
Okay I'm going to close this as no repro, it seems likely this was a migration problem for an unsupported migration path, eg. migrating from a random staging build
