### ISSUE TITLE
[7.0.0 Beta][Steam] Whitelists, Blacklists, Adminlists etc linked to username

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3845]
Hey,

till now, the whitelist, blacklist and adminlist where filled with the Eco username, which worked fine. Now, as Eco (seems to) use the Steam name to identify the user ingame, whitelists, blacklists and adminlists can be easily tricked.

Would be cool, if this can be linked to the steamID64 (or the eco username).

Cheers,

Niklas

**Comment by sirPattrick** [comment]
How is this a Medium Priority?  This NEEDS to be fixed for the first hotfix.  Otherwise people can grief with full admin privileges.  
![image](https://user-images.githubusercontent.com/36024353/35774716-ca673b72-093c-11e8-8c95-eb5e86bba4c5.png)

**Comment by MarjieAVolk** [comment]
I believe this is only an issue if the admin in question has never logged in on the server before, thus the prioritization.  I can double check the behavior, but it should be the case that once you have logged in on a server, no one else can impersonate you.

**Comment by MarjieAVolk** [comment]
Hey, just found someone else has already fixed this, should be available in next hotfix

**Comment by sirPattrick** [comment]
This still isn't fixed.  Just so you know @MarjieAVolk.

**Comment by metachronism** [comment]
its using slgIDs and STEAMID64 now

**Comment by metachronism** [comment]
Steam only user -> uses STEAMID64
SLG, or SLG+Steam linked user -> uses SLG ID

**Comment by sirPattrick** [comment]
Thanks Meta, I only brought it up because I had someone else on my server mention that they crashed a server because they changed their steam Name to the Admins name.

**Comment by sirPattrick** [comment]
Would that be a completely separate issue then?

**Comment by craig-jong** [comment]
This shouldn't crash servers, but it is indeed a problem with some legacy username checks. Right now you can boot people from servers by logging in with the same name, but you will not actually inherit any of their admin privileges. 

We're hotfixing the above issue right now.

If a server did actually crash, that would be a different issue and a server crash dump would be useful in that case.
