### ISSUE TITLE
After chopping branch off tree, it turned white for a while before disappearing

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3847]

**Comment by Nanders** [comment]
What species?

**Comment by MarjieAVolk** [comment]
One of the old ones, cedar I guess?  Haven't checked the other trees, that's the one I saw it on

**Comment by MarjieAVolk** [comment]
Taylor says he thinks this is because of fog idk, so reassigning

**Comment by metachronism** [comment]
stone has the same issue, something wierd when going fullscreen or something

**Comment by MarjieAVolk** [comment]
Guess I will close this as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3871, since that one has photos
