### ISSUE TITLE
Campfire has public storage?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3848]
But you can't put anything in it, neither carried nor non carried.  And it is empty, but it has weight?

![image](https://user-images.githubusercontent.com/23460210/35773597-ebb18804-090b-11e8-9906-aa72800cc6d3.png)

**Comment by MarjieAVolk** [comment]
I believe this is actually the fuel supply showing here, but being displayed really strangely

**Comment by elfl0rd** [comment]
Looks fixed :P
