### ISSUE TITLE
USER ISSUE: Not receiving crafting bench on skill selection

### ISSUE THREAD

**Issue by MagicBackPack** [StrangeLoopGames/EcoIssues#3849]
![20180203211039_1](https://user-images.githubusercontent.com/36118065/35773685-fafd11be-0926-11e8-9a76-e1aed9847c62.jpg)
![20180203211043_1](https://user-images.githubusercontent.com/36118065/35773686-fb074e2c-0926-11e8-9665-cb54619cd8f3.jpg)
![20180203211137_1](https://user-images.githubusercontent.com/36118065/35773687-fb110f0c-0926-11e8-8341-925de153c0ff.jpg)

**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
when starting a new character on any server selecting basic crafting, survival, or mortaring does NOT give a crafting table

**Expected behavior:**
on selection of one of the aforementioned specialities a crafting table should be placed either in the hotbar or backpack for placement

**Actual behavior:**
no crafting table is given thus no crafting can be done attached are 3 screenshots taken from a fresh character on a local (via game client) server

**Comment by MarjieAVolk** [comment]
The workbench is now given through the tutorial.  If you don't want to do the tutorial, skip them all to get the items

**Comment by MagicBackPack** [comment]
got it thanks
