### ISSUE TITLE
USER ISSUE: Connection Error

### ISSUE THREAD

**Issue by R4RD0** [StrangeLoopGames/EcoIssues#3850]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
running own server, server is listed on the public listing and rumming server side fine. however when i attempt to connect (matching game - server version) i recive a "connection error" and sadly nothing more.

**Expected behavior:**
connected to the server

**Actual behavior:**
The following error message popped up:
"connection error"
Connection Failed
```

**Comment by MarjieAVolk** [comment]
I was just having a similar issue, which I got around by disabling NAT on my server.  Does that allow you to connect?

**Comment by metachronism** [comment]
connect likely failed due to accounts issues which should be resolved, reopen if not the case
