### ISSUE TITLE
USER ISSUE: Kicked out of game

### ISSUE THREAD

**Issue by Baldwolf63** [StrangeLoopGames/EcoIssues#3852]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
Broke a mortared stone roof piece moved away and had error message	

**Expected behavior:**
I was bumped out of the game. It was unexpected. :)	

**Actual behavior:**
Caught exception: Nullable object must have a value.

**Comment by Baldwolf63** [comment]
This was an updated to an established world. There could simply be a conflict between old world and new version.

**Comment by metachronism** [comment]
if you have the old save, can you link it here for download?

**Comment by Baldwolf63** [comment]
The server became so buggy that the admin put it up to a vote to restart
and we did. We now have a fresh start.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3891
