### ISSUE TITLE
Issue Converting 6.4.2 to 7.0.0

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#3853]
Getting the following error while trying to upgrade my server from 6.4.2 to 7.0.0

![screenshot_36](https://user-images.githubusercontent.com/36120114/35773832-a9c23f18-092b-11e8-826b-f93b4e118d30.png)

**Comment by metachronism** [comment]
can you attach the save file?

**Comment by metachronism** [comment]
that doesn't sound much better :P  If you send me the save, we can track down the issue more easily

**Comment by Sarongas1999** [comment]
https://drive.google.com/open?id=1qsB_jgsu9-xCzbkQgn8ATlc-MJjNP2mp

**Comment by Sarongas1999** [comment]
Its in 6.4.2 format since it would never convert.

**Comment by metachronism** [comment]
@knexer sounds like an issue with world layers killing everything?
