### ISSUE TITLE
7.0 NAT detection error?

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3854]
see the image.. its not stopping anything as of yet but this is new.
![2018-02-03](https://user-images.githubusercontent.com/20627148/35773899-7b06bb72-091c-11e8-8c6a-a5bc05463571.png)

**Comment by metachronism** [comment]
yes, some NATs will fail to detect.  I've also seen some NATs get stale after a bit and stop broadcasting on the UDP port for upnp access, resulting in them not being detected.

its always safest to manually forward the port if you know what you are doing, then you can disable the NAT entirely
