### ISSUE TITLE
USER ISSUE: 7.0 steel hammer still has no model

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3857]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
hold steel hammer in hand

**Expected behavior:**
see hammer

**Actual behavior:**
no hammer visible

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2478 (There's a bunch of tools that have no in hand art yet)
