### ISSUE TITLE
7.0 Can not build all items with hammer now

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3858]
locking windows/fences/and so on behind skill caps is counter productive. just cause you have someone on your server doesn't mean you trust them with full access to your land.... this move is not a good one. 

(example  - hammer and lumber in hand... can not build more then a floor or wall... you must have lumber 2+ to build windows, fences and so on.)

**Comment by craig-jong** [comment]
Contracts are intended to be the primary solution to this; we'll have to see how it plays out.

I think the main idea we're toying with would be letting people craft the advanced blocks for sale to other players.

**Comment by stormoffires** [comment]
that would be awesome to be able to build the advanced blocks again... contracts allow to much freedom on peoples property or to much complexity to just have someone put a roof on a house or add a few windows. especially when most folks playing are those that want to build/craft their own stuff... i find that contracts/trading is very difficult to encourage in game right now.

trust is a big issue in the game and with steam opening up today we will see more griefers on the server then ever.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#291
