### ISSUE TITLE
USER ISSUE: 7.0 Dev tool does not delete dirt blocks

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#3859]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
hold dev tool in hand	

**Expected behavior:**
delete dirt block when clicked on

**Actual behavior:**
does not delete dirt blocks anyone (can delete trees/plants)

**Comment by metachronism** [comment]
it will if you are carrying another block at the time (temp workaround)
