### ISSUE TITLE
7.0 Hole in world

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#3861]
![image](https://user-images.githubusercontent.com/36024353/35774100-8ef365a4-092b-11e8-9e3f-5bea5b541c2c.png)

We just converted to 7.0, And there is currently a hole in the world.  Stuff is falling through it.

World is Mediocre at best.

**Comment by stormoffires** [comment]
https://drive.google.com/open?id=1mF-SmXpxTFmhZR8yBtTExLvn49JEb50j

**Comment by metachronism** [comment]
closing as I'm pretty sure this is fixed in 7.2
