### ISSUE TITLE
Black screen on launch leading to crash

### ISSUE THREAD

**Issue by jcctigger** [StrangeLoopGames/EcoIssues#3865]
Launching game on steam yields a black screen in fullscreen. Will eventually crash due to an access issue. Output log is pasted here https://gist.github.com/anonymous/3627def8d4dea000cf804fc4fc1c587a

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3903 - I will copy your log over there, although I think it is about the same
