### ISSUE TITLE
Need error message for steam users who launch outside of steam

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3867]
Current case: 
If the loading of the SteamAPI fails, we assume that the user is a standalone user (someone who downloaded from SLG). This can happen if the user launches the game manually outside of steam.

Whether the SteamAPI fails to load determines whether the login bar shows up (if success -> they're a steam user, and if fail -> they're not)

This leads to confusion for players who are solely steam users, because they think they're getting prompted for their steam login info, which is false.

Either add an error message, or add a line underneath the login that says something like "Log in using steam"

Not sure on the best solution.

**Comment by MarjieAVolk** [comment]
How would you feel if we put a message on the login bar thing, like above it, that said something like 'Steam login failed.  Log in to your SLG account:'

**Comment by MarjieAVolk** [comment]
Fixed on release
