### ISSUE TITLE
USER ISSUE: Shovel wont open Door

### ISSUE THREAD

**Issue by TheLostOne21** [StrangeLoopGames/EcoIssues#3868]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Put  Wooden Shovel in Hand
Try to open door

**Expected behavior:**
Opened door

**Actual behavior:**
doesnt register

**Comment by g1franc** [comment]
Still in 0.7.3.2

**Comment by MarjieAVolk** [comment]
Just took a look at this - @SeanAtr0n the interact event isn't even getting sent to the server in this case.  And it does only happen with wooden shovel while not carrying anything, other shovels work.

**Comment by Ruthgar** [comment]
This happening with wooden shovel to me only when i use it to move dirt. 1 piece is enough. 
Take shovell, take\place dirt, try to open door - not working. Switch to other tool and back to shovel - all ok.

**Comment by torchdragon** [comment]
Still an issue on 7.7.2.

**Comment by GophTheGreat** [comment]
Seems to work now. Reopen if necessary.

**Comment by SlayksWood** [comment]
8.2.9 release-preview still an issue. Step to reproduce:
- spawn building with door.
- select shovel at toolbar. You can open door with RMB
- pick up Dirt, place Dirt. Try to open door (shovel still in hands). You can't open door

**Comment by SlayksWood** [comment]
0.9.0 staging-1299 still an issue

**Comment by TimoNuernberg** [comment]
9.1.9 problem still there, but it changed a bit.
after login, you can not open with an equipped shovel a door.
If you open the door without a shovel, then you can open/close (only this one) with an equipped shovel.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-192.

Appears to be fixed. Tested all commented scenarios where it triggers the issue but could not reproduce.

Closing.
