### ISSUE TITLE
Stray pixels on new UI

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3869]
![image](https://user-images.githubusercontent.com/6262198/35774667-f88888ba-092a-11e8-9e41-75092d290fe3.png)
![image](https://user-images.githubusercontent.com/6262198/35774673-135b6194-092b-11e8-9730-658fb69bd93f.png)

**Comment by MarjieAVolk** [comment]
Oh that's what these are.  I still don't see anything on the second one lol

**Comment by metachronism** [comment]
milenko fixed
