### ISSUE TITLE
Misaligned Icons

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3870]
![image](https://user-images.githubusercontent.com/6262198/35774718-13e23178-092c-11e8-8050-d413d58bdb87.png)

**Comment by Nanders** [comment]
![image](https://user-images.githubusercontent.com/6262198/35775045-ed6176da-0935-11e8-81f0-6334bfda5b10.png)

**Comment by MarjieAVolk** [comment]
Yep, it's a sprite asset problem.  Keegan tells me he's fixed it.  I'll confirm it in the release and then close

**Comment by MarjieAVolk** [comment]
Okay this is indeed fixed on release branch
