### ISSUE TITLE
Transparent shader missing sometimes in release

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3871]
![image](https://user-images.githubusercontent.com/6262198/35775094-15b723f4-0937-11e8-856d-60e16e63c515.png)
![image](https://user-images.githubusercontent.com/6262198/35775124-ac35ad6e-0937-11e8-8ebd-8b55115ae268.png)

**Comment by metachronism** [comment]
this isnt highlighters, this is the transparent shader

**Comment by SeanAtr0n** [comment]
Fixed in svn
