### ISSUE TITLE
Sometimes you will stop seeing your in-game chat, but other users will be able to see it. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3873]
After disconnecting and reconnecting to a server

**Comment by Nanders** [comment]
Typing commands will still show the response text for you, but only in the minimized chatlog.

Full chatlog shows neither your messages or command responses.

**Comment by Nanders** [comment]
Labeling as critical because I think this might be a symptom of a larger more serious issue.

**Comment by Nanders** [comment]
Switching to a different computer also does not solve issue

**Comment by MarjieAVolk** [comment]
???

**Comment by MarjieAVolk** [comment]
I have never seen anything like this, but I have gotten weird complaints about chat periodically.  So you get it as a specific person on a specific server?  What account/server?  Probably will want to debug as that person to get it to repro.

**Comment by Nanders** [comment]
Just tested a new server, works as intended. Problem server is still bugged for my account.

user is me as "That Wyoming Dude" On Marmot.

**Comment by Nanders** [comment]
Herp derp was clicked out of a chat channel

**Comment by Nanders** [comment]
Seems weird that you can post to channels you're not subscribed to, though. In my defense.

**Comment by MarjieAVolk** [comment]
yaaaaaay I really didn't want to debug that lolol

**Comment by MarjieAVolk** [comment]
Soooo okay this is how it should work.  There are notification channels (shown in green) which are read only, and regular channels (shown in blue) which are read/write (from the player's perspective that is).  You can have as many notification channels on at once as you want, but you always have exactly one regular channel on.  When you talk into a channel, it should switch you to that channel (disabling all other regular channels).

**Comment by Nanders** [comment]
It must not be, it was the cause of all of my confusion.

**Comment by MarjieAVolk** [comment]
Okay well I will reopen this on a lower priority
