### ISSUE TITLE
Plants that can be harvested by hand when alive should still be able to be harvested by hand when dead

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3879]

**Comment by pamduncan** [comment]
would we get rotten fruit or dried vegetation from it or something like that?  I always assumed like in my garden  - once a plant dies there is nothing there to harvest or if there is fruit left its dried or rotten and all you can do is pull it up and turn it into mulch for next year.  The one exception might be beans where if they dry on the vine you can then store them and use them as dried beans later on -  I like the idea that plants die and you then lose that yield - but if they remain harvestable for their product even though dead it seems like it defeats the purpose of running into shortages as the seasons progress.  I know there for some time we have ferns that died and it meant that we had to hurry and harvest when we found a bunch of them growing an mature knowing that once they turned brown we were out of luck.  We actually planned around that - it would seem to take something away if you could get from a fruit even once the plant died - making so growing season was less of an impact and that once it matured it would have food forever (until it was harvested) and you did not have to make sure you are paying attention to its cycle

**Comment by MagicBackPack** [comment]
I would say normally hand harvestable plants should be able to be removed by hand (or any dead plants for that matter except like trees) just to allow the player to clean up/replant especially oysters and such cause once it's there it's just kinda there till you forget about it and try to grab it again and it's still dead.

**Comment by Thyriel** [comment]
I agree that dead plants should be removeable by hand (or at least all with a scythe).
And as this is somewhat related to this: It doesn't make any sense to me that there are plants that need a shovel to be harvested (like Camas for example). It's lowering the usability of the farming:scythe efficiency skill and chances are good that you hit the ground by accident instead the plant. (Which means you losse the plant above it & have to use hoe again)
