### ISSUE TITLE
Strange lighting errors

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3881]
Noticed this was happening when inside a building. Seemed to only happen when looking a certain way, but would sometimes get stuck. 
![lighting error](https://user-images.githubusercontent.com/6262198/35775876-6c413638-0946-11e8-8f2d-cf6343266ed1.gif)

**Comment by MarjieAVolk** [comment]
I also noticed some serious god rays that would appear and disappear depending on which direction I was facing, while inside.  Might be related.
