### ISSUE TITLE
0.7.0.0 - no Wheat spawning into the world

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#3883]
On the 0.7.0.0 beta (stable), worlds appear to be generating without Wheat.

All locations where Wheat was expected (from the Wheat Expected Yield overlay) have no Wheat. These locations do have large amounts of Corn, which may be a co-incidence.

The server graphs show a 0 population count for Wheat. Other species show non-zero populations.

We've generated three worlds on a mono/Linux server and three worlds on a Windows server, and still can't find Wheat in the world.

We are experimenting with world generation settings to try and force Wheat to spawn, but haven't had any success with this yet.

**Comment by Amphysbaenas** [comment]
Same here on Ecotopia !

**Comment by pamduncan** [comment]
It appears that the world layer that spawns wheat is not being created even though designated in the world generator - and even if you increase the setting nothing happens.  WIthout that layer it seems that even increasing yield etc will not cause wheat to grow

**Comment by Bazzi89** [comment]
Same here! Generated maps with different generatorsettings and dimensions (72x72, 100x100, 140x140)

**Comment by MarjieAVolk** [comment]
Hotfixed

**Comment by LiaungYip** [comment]
Verified fixed.

Note - if you are keeping your world and configs between server upgrades:

1) The fix is contained in `Configs/EcoSim.eco` - you must use the new version of this config file.
2) The (new) admin command `/regenlayer` will fix the Wheat layer in existing worlds, provided that you have the new version of `Configs/EcoSim.eco`. Use it like this: `/regenlayer Wheat`, then `/regenlayer WheatYieldPotential`.
