### ISSUE TITLE
USER ISSUE: Tried to @Chat someone

### ISSUE THREAD

**Issue by Bjeaurn** [StrangeLoopGames/EcoIssues#3885]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
Find a player online
Type @PlayerName, press enter.
???
Crash.	

**Expected behavior:**
Tagged him in chat, so I can see his position when I hover over.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

startIndex cannot be larger than length of string.
Parameter name: startIndex


Stack:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

```

**Comment by MarjieAVolk** [comment]
Fixed, will be available in next hotfix (should be released today, possibly tomorrow)
