### ISSUE TITLE
admin=<name>  not passing player name to admin config

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#3889]
setting the command line for first start with -admin-<name> does not seem to write that name to the User.eco config.  It will make the person an admin but unless that command is used on all subsequent startups as its not saved in the users.eco the admin is not remembered.  This is a problem on at least hosted servers as the command line can be set to use this when the owner starts the server via a designated command line, however if the server crashes and auto starts it does not retriend that custom command line and as the admin was not written to the config file the admin is not set.

**Comment by metachronism** [comment]
the option was intentionally removed (it was originally for singleplayer/local servers only)
connecting to a server from the same box automatically gives you admin
