### ISSUE TITLE
Crash on picking up log

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#3893]
**Version:** 0.7.0.0 beta

**Steps to Reproduce:**
1)cut tree down
2)attempt to pick up log

**Expected behavior:**
It should have picked it up without crashing me...

**Actual behavior:**
Kicks from game with error in the dump file, upon re joining, the tree/logs will float up in the air until it disappears from view and any attempt to pick up the logs will crash you again with the same error. (it seems to only do it with one of the new tree types, but i could be wrong)
[ecodump.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1693213/ecodump.txt)

**Comment by MarjieAVolk** [comment]
Do you know which type of tree you were cutting down?  Was it one of the new tree species?

**Comment by Quicksilv3r710** [comment]
Yes it was one of the new species. I think it was a fir tree.

**Comment by craig-jong** [comment]
This looks like an old bug related to species not having the proper resource type. 

I'll double check, though.

**Comment by craig-jong** [comment]
This does not seem to be occurring on the current release branch.

I'm going to close this issue but I'll keep an eye on the new tree species.
