### ISSUE TITLE
Windows Detecting Tojan Virus in server download file

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3894]
![image](https://user-images.githubusercontent.com/1503963/35781364-353929f4-09b7-11e8-859d-b779802f76e6.png)

The following error occurred: Error code 0x80508023. The program could not find the malware and other potentially unwanted software on this computer. 

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\Users\Administrator\Downloads\EcoServer_v0.7.0.0-beta.zip
file:C:\Users\Administrator\Downloads\EcoServer_v0.7.0.0-beta.zip->WebClient/App/Scripts/app.js
webfile:C:\Users\Administrator\Downloads\EcoServer_v0.7.0.0-beta.zip|https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v0.7.0.0-beta.zip|iexplore.exe

**Comment by metachronism** [comment]
not seeing this locally - sounds like a false positive?
