### ISSUE TITLE
Unable to drop/stack carried items

### ISSUE THREAD

**Issue by LoyalExpert** [StrangeLoopGames/EcoIssues#3896]
Version: 0.7.0.0 beta

I am running in to an issue where i am harvesting a tree i chopped down. I was able to make a couple trips hauling logs, but then all of a sudden i can pick them up but they dont show a being carried, as in the picture isnt there. But i show i am carrying like 16 logs. when i get to where i want to stack them i am unable to drop them.
![20180204_131908](https://user-images.githubusercontent.com/36138208/35781969-3bee6786-09ae-11e8-9335-5149bbd26d3d.jpg)

**Comment by metachronism** [comment]
view errors, should be fixed now
