### ISSUE TITLE
Holes while digging dirt.

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#3897]
My map creates random holes while digging dirt:
![20180204153939_1](https://user-images.githubusercontent.com/13231573/35782635-0d537ca2-09fb-11e8-8b88-ec5c4db26b52.jpg)

after i jumped into the hole i was falling trought the world.

![20180204161509_1](https://user-images.githubusercontent.com/13231573/35782652-6d5d58ca-09fb-11e8-84b8-4d1265c4c1bb.jpg)

or random holes in the ground (left side of the pic) like this when i diggin dirt from other place above.

![20180204224501_1](https://user-images.githubusercontent.com/13231573/35782751-2d6f6238-09fd-11e8-9e11-14c904661835.jpg)

**Comment by MarjieAVolk** [comment]
@dealtime101 says when this happened to them, they were able to dig in the whole and continue getting dirt forever without changing the landscape.

**Comment by metachronism** [comment]
this should be fixed as of 7.3
