### ISSUE TITLE
USER ISSUE: Critical currency bug in stores

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3898]
**Version:** 0.7.0.0 beta

**Actual behavior:**
It seems like the currency option is broken bc when u choose one, the display shows and handles another currency....

**Comment by Conchipedia** [comment]
same as
Shop issue with user currency (beta 7.0) #3890
For now until you fix downloaded just choose the currency 1 below yours and it will be right

**Comment by MarjieAVolk** [comment]
Yes, this has already been hotfixed, if you update to the most recent release you should get the fix
