### ISSUE TITLE
Research Location stays on screen Beta 7.0

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#3899]
research location stays on screen even after the research is completed and has been learnt. disconnecting and reconnecting to the server also doesn't clear it

also starting a new research skill project doesnt replace the whats being researched it just stays saying the old skill that has already been researched

![image](https://user-images.githubusercontent.com/29722757/35783465-b0f340c6-0a5b-11e8-8d36-e411ef0ac650.png)

**Comment by MarjieAVolk** [comment]
Yeah that is a 'waypoint', so you have to remove it manually.  You can do so by showing your cursor, then clicking on the indicator on screen, and selecting remove on the popup that comes up

**Comment by ecoemmeck** [comment]
ahh ok thanks.
my suggestion then would be to have it clear the waypoint automatically either after the skillbook has been collected or skill has been learnt

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#289
