### ISSUE TITLE
Suggestions for a few small but (in my opinion) fairly important changes to skill selection

### ISSUE THREAD

**Issue by MagicBackPack** [StrangeLoopGames/EcoIssues#3901]
First: a screen listing precisely what each level up unlocks on the skill selection would be very needed (those 6 other items may be very important down the road and those that are newer to the game may have no idea they have those skills blueprints unlocked or what they entail) so an expanded skill explanation menu or some such would be a very good idea.
small edit: also the ability to review what previous skill level ups unlocked rather than having to browse through various crafting tables is very very much needed.

Second: instead of spending skill points immediately on the skills menu one should be able to invest points and then have it confirm before the skill points are spent (with the ability to remove skill points from the changes) since the cost per level up isn't listed until you go to invest in that specific level and it varies from skill to skill giving the player a confirmation/edit on the skill tree would help people visualize their builds and plan them accordingly as opposed to "okay get this to level four, and now five and now.......wait what do you mean that's 60 skill points I still needed to buy xyz that's alot cheaper, if I'd have known I'd have waited" should do alot to make the game more accessible especially as an educational tool.

**Comment by MarjieAVolk** [comment]
Re the first point, you can see this information in the skill's tooltip, which is accessible from the skills window and a number of other places.  Does this address your problem?

**Comment by MagicBackPack** [comment]
sorry about the late reply, from what i've seen it will show x amount but after so many unlocks it will say +6 others without listing what the 6 others are, trying to find the specific unlock for level ups that have numerous blueprint unlocks has been unsuccessful, even chat linked only shows so many, below is a couple of screenshots of what I'm talking about, I went with a learned skill, unlearned skill, and chat link, as you can see in the road construction via chat link it just says unlocks and the reduction benefits not the specific unlocks.  an extended skill tree (think like sid meier's civilization technology tree complete with lines leading from one tech to another or some such) would be helpful I think since sometimes finding the dependency or requirement for skills can be a bear, yes one can explore/look through various crafting tables and stations to find out what was unlocked and the tables having a specific function helps out immensely but I'm just more concerned for accessibility and not having to rack my brain of what all I unlocked so far :)

![20180206211312_1](https://user-images.githubusercontent.com/36118065/35894825-9c7a02e2-0b82-11e8-9acb-98d8ac20c5a5.jpg)
![20180206211435_1](https://user-images.githubusercontent.com/36118065/35894859-c9221b2c-0b82-11e8-8243-d6f2c91e5846.jpg)
![20180206211445_1](https://user-images.githubusercontent.com/36118065/35894861-cb0803e8-0b82-11e8-9cbe-f5707f9a86d0.jpg)

also as to the second suggestion, a prompt to confirm the skill selection before exiting the screen (should the planner option be implemented) would help so someone doesn't dump points but forget to confirm and not have their level ups.  just a quality of life thing

keep up the great work folks!

**Comment by MagicBackPack** [comment]
update I did find that hovering on the X number more does in fact expand it 😨  I feel silly now >.>

**Comment by MarjieAVolk** [comment]
lol good, was just going to let you know that.  Okay I will think about a confirm spending thing.  Thanks!

**Comment by MarjieAVolk** [comment]
I believe we concluded that the first point is already addressed.  Moving your second point to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/11
