### ISSUE TITLE
[Suggestion] have wild plants let us harvest them and stay like prickly pears

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3902]
for Example Corn should be harvested not ripped out the ground, same goes for tomatoes when those are harvested you don't pull the plant out the ground

**Comment by ecoemmeck** [comment]
I like this idea it could be set to grow the food item back in half the time it takes to grow from scratch like the huckleberrys work

**Comment by Conchipedia** [comment]
huckleberries we just use the berries anyway and corn you pull from the plant

**Comment by ecoemmeck** [comment]
It would only work on certain plants like corn tomatoes beans and such that don't need to be dug up.
To get the seeds either you use the food items in the farmers table or dig the plant up with seed yield

**Comment by metachronism** [comment]
Corn/Tomatoes/Beans maybe a few other plants should work this way

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#287
