### ISSUE TITLE
Phantom items in inventory

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3905]
IDK how to repro this, but it happened ~3 times while I was playtesting last night, and happened to Taylor also.  I placed a world object, but the object appeared to still be in my inventory.  The item in the inventory could not be placed and had no tooltip.  The only ways I found to make it go away were to drag something else on top of it, or to reconnect.

Sounds like it might be client side behavior related to me, but not sure.

**Comment by SeanAtr0n** [comment]
i suspect this is server side or some sort of bson glitch, we aren't predicting worldobject placements

**Comment by metachronism** [comment]
figure out this was likely caused with a similar issue to what craig saw, where some exceptions during object update or init would drop the view update packet
