### ISSUE TITLE
Contracts switching Currency selections

### ISSUE THREAD

**Issue by Matikari** [StrangeLoopGames/EcoIssues#3907]
This may be related to the other Currency bug https://github.com/StrangeLoopGames/EcoIssues/issues/3890
But is still behaving a bit differently.

It will change the selection at random times, It will change when a player accepts the contract, to get them to accept them have to select the second person below. And it will change yet again as player completes the contract, so I pay with a credit type I didn't want to pay with or invalidate the contract because I don't have any of the new contract, and forcing it marked as complete pays them with that credit anyway.

**Comment by Matikari** [comment]
And if I didn't mention before,  This is 7.0 beta

**Comment by metachronism** [comment]
fixed for 7.0.3
