### ISSUE TITLE
Add small detail rising bar on Skill point button

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#3909]
**Version:** 0.7.0.1 beta

Small Skill point button just shows you how many you got. I kinda miss the little bar that slowly grew full till you got a point.

What if we just add inside the button a little graph of it rising up until the point is given?

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3877
