### ISSUE TITLE
Wainwright table placement messed up/can't be interacted with 7.0.1

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#3911]
When placing a wainwright table, the projection of it isn't where you aim. Once placed it also cannot be interacted with. Image of me trying to place it linked. (notice its on the right almost off my screen even though I'm aiming at the block right in front of me.
![eco4](https://user-images.githubusercontent.com/32985820/35791390-a675b1a6-0a15-11e8-9c37-df533072ac00.png)

**Comment by Matikari** [comment]
I had the Wainwright Table placed in the 7.0.0 version and it was working then, now I can walk through the model and am unable to highlight it for interaction or pickup.
