### ISSUE TITLE
Transmission pole cannot be interacted with 7.0.1

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#3912]
After placing a transmission pole into the world, you can not highlight/interact with it.

**Comment by keegan-o** [comment]
Transmission poles extend the electric network but there's nothing to actually do on them, so nothing is broken, really-- a code/design thing anyways, rather than art bug.

**Comment by MarjieAVolk** [comment]
Can you pick it back up while holding a hammer though?  (I assigned it to you @keegan-o because I assumed it was a collider issue)
