### ISSUE TITLE
Store UI Dropdown menu selector "currency to use" picks the wrong menu item.

### ISSUE THREAD

**Issue by clairemarshal** [StrangeLoopGames/EcoIssues#3913]
version: 7.0.1
Expected: Drop down menu should select the correct menu pick.
Bug: The drop down menu selection is offset to the entry above. 

To reproduce: 
1. Have a store
2. put an item up for sale
3. goto the credits tab to change your "currency to use"
4. Make a selection: In this example I'm trying to switch to the store owner's currency: cmars
5. "You have # - cmars credit" is what should say to confirm the selection. Instead the menu picked the name from above. "Arend Credit" which is not the item it choose from the menu. Either the highlight is wrong or something else is misaligned.
6. verify selection in the economy viewer (type Y) - the wrong currency is choosen.
7. to select the currency you want you have to pick the menu item below your intended choice. I was able to select "cmars" currency by choosing "Conchita" instead. note the mismatch in the labels. "Currency to use" & "You Have" they should be the same after a user makes the selection.

![store_scroll_menu_bug_01](https://user-images.githubusercontent.com/35860809/35793170-5d210128-0a05-11e8-89d1-ec5b4ec2fe6c.png)
![store_scroll_menu_bug_02](https://user-images.githubusercontent.com/35860809/35793171-5d3929c4-0a05-11e8-8d94-9cba4c4d7b47.png)
![store_scroll_menu_bug_03](https://user-images.githubusercontent.com/35860809/35793172-5d4db4a2-0a05-11e8-963f-f8188a30b435.png)
![store_scroll_menu_bug_04](https://user-images.githubusercontent.com/35860809/35793178-5e10521e-0a05-11e8-8294-a2fbc1a85a6a.png)

**Comment by LiaungYip** [comment]
This appears to have regressed from 0.7.0.0 (a fix was committed in 0.7.0.1).

We have this behaviour occurring again on 0.7.0.2.

**Comment by Amphysbaenas** [comment]
Same here on Ecotopia Server!!!!
![capture](https://user-images.githubusercontent.com/29807119/35801700-9f07c28a-0a6d-11e8-9d87-59a06292475d.PNG)

**Comment by LiaungYip** [comment]
Not only does the currency dropdown assign the wrong type of currency, the type of currency used changes to random currencies at arbitrary times.

**Comment by GibsonSWE** [comment]
I can confirm this too

**Comment by Conchipedia** [comment]
i think it also changes when the store is accessed by other people as well

**Comment by Amphysbaenas** [comment]
I think it also changes when a new player connect to the server ....

**Comment by MarjieAVolk** [comment]
Hotfixed

**Comment by metachronism** [comment]
actually this is still broken - maybe the hotfix went to master?

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix.  For real this time.
