### ISSUE TITLE
Skipping Tutorials with a full inventory means you can never get the starting items

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#3915]
Even if you restart the tutorials and skip them or perform them, the items are not given to you.

**Comment by rrobinson** [comment]
Is there a way to get a workbench if you don't get one in the tutorial?  A workbench is required to craft a workbench...

**Comment by MarjieAVolk** [comment]
You (or your admin if you are not one) can enter '/give workbench' into chat

**Comment by knexer** [comment]
You can spawn one in if you're an admin.  /give workbench should do it.
