### ISSUE TITLE
latest server 7.0.1 and latest client 7.0.2?

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3918]
The server version seem to be one version behind the client atm?

**Comment by MightyPiggie** [comment]
You just have to wait until the server updates. Because these servers are not owned by the creators of the game. They are owned by people like you and me. Here is a link for 7.0.1 if you need it. https://s3-us-west-2.amazonaws.com/eco-releases/EcoPC_v0.7.0.1-beta.zip

**Comment by GibsonSWE** [comment]
I own the server....

**Comment by pamduncan** [comment]
If you are updating the server through steam there can be a delay.  You can get the server from the Eco website immediately and update it when you want to.  If you are using a host then its on them to provide the update in a  timely manner to you.  The 7.0.2 server was released when the client was and was immediately available on the website.  The server does not automatically update.  You do need to do that yourself.

**Comment by Nanders** [comment]
I just checked this. If you continue having problems, try logging out and logging back in.
