### ISSUE TITLE
USER ISSUE: Wainwright placement bug

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#3919]
**Version:** 0.7.0.2 beta

**Expected behavior:**
It should be placed where the ghost is displayed (which is displayed wierdly)

**Actual behavior:**
Instead it gets placed further away and becomes unusable and unclickable...

**Comment by Bazzi89** [comment]
Check, same here!

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3911
