### ISSUE TITLE
Client Memory Leak

### ISSUE THREAD

**Issue by Breitschwert** [StrangeLoopGames/EcoIssues#392]
Version: Alpha 04
Type: Client (local Server/Singleplayer and Online/other Server)
OS: Windows 7 64bit Home Premium
Detailed Description of Issue:
After running the game for a while, the memory usage becomes increasingly high, edging towards the maximum of the PC and causing Windows to throw error messages of no memory being available. It appears that there is a memory leak present in the client.

Reproducible? How difficult is it to reproduce?:
It always occurs, but takes quite some time to build up. Tried it three times with a local server as well as an online one.

Steps to reproduce bug/issue:
Run the game, check the memory usage after joining the server and play normally, as in craft, chop trees, gather fruits, etc. After a prolonged amount of time (1 hour), verify the memory usage by the client in Taskmanager. It should've significantly increased.

**Comment by noblackthunder** [comment]
how much ram are we talking about ? towards the end i mean in usage from the client?

**Comment by noblackthunder** [comment]
add coment / issue link. same cause ? https://github.com/StrangeLoopGames/EcoIssues/issues/261#issuecomment-226818689

**Comment by Breitschwert** [comment]
Around 4GB was used. It started at below 2GB.

**Comment by Breitschwert** [comment]
Disconnecting from a server, after the memory has been filled up, frees about 500MB worth of memory and then it stays there. Right now, I am sitting at 4.758.732K filled, while it was above 5.000.000 when on a server.

**Comment by keegan-o** [comment]
Happens for me too.

**Comment by Breitschwert** [comment]
Shoveling is the most affected by this issue or maybe even a cause. The longer the client runs, the longer of a pause happens, when you try to shovel up an item (stone, dirt). At the start, when the client just started, it is very responsive and works very well. There is no pause and shoveling works flawlessly. The longer you play, the more of a delay occurs between the animation of the shovel+shoveling sound and the item that should spawn into your inventory. The delay can grow up to several seconds, before the item becomes available and the client freezes completely meanwhile.
