### ISSUE TITLE
USER ISSUE: Swinging a pickaxe seems a lot slower now

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3920]
**Version:** 0.7.0.2 beta

was ok in 7.0.0 now just seems slower

**Comment by Senlarus** [comment]
I noticed this in 7.0.1 also

**Comment by keegan-o** [comment]
Was an intended change-- we may speed it up a touch again but it was a bit too fast. We will probably leave it slower though because players will also be getting more expedient ways to destroy rock.

**Comment by Conchipedia** [comment]
sadly its Horrible and a bit unfair to miners, shovel and axe swing twice as fast and when you have to mine like over 1000 stone we need the speed like the other players , also some players don't like using Excavator

**Comment by keegan-o** [comment]
Just loaded up all the FBXes to test and now the pickaxe matches the other tools-- Hammer, Axe, Hoe, and Shovel all have 30 frames of animation, and the interact event is right at about 20. This is what the Pickaxe is now set to-- only Scythes are a tiny bit faster with the hit event at about frame 17 or 18. Before the Pickaxe was at a total of 20 frames, the whole animation being a third shorter than any other tool, and the animation was so fast we couldn't sync it with third person animations. I'm looking forward to implementing some other tools as well beyond the excavator, heheh. At the very least we'll have a higher tier tool that is faster, but we're looking at other interesting options as well.

**Comment by Conchipedia** [comment]
ok thanks for looking into it for me ❤️  now to try it out when the lag will let me 😄

**Comment by keegan-o** [comment]
Ah, well brace yourself-- because I didn't change it from the slower-- I was explaining that the slower actually matches the other tools >.> 

We may tweak it to be a tiny bit (a couple frames) faster, but I do think where it's at now is in line with the rest of the tools.

**Comment by Conchipedia** [comment]
thats not a problem i trust you @keegan-o 😄
