### ISSUE TITLE
Stores Currency Selection switching on their own

### ISSUE THREAD

**Issue by Matikari** [StrangeLoopGames/EcoIssues#3921]
Its Version 7.0.2 and https://github.com/StrangeLoopGames/EcoIssues/issues/3890 still exists. As well as this may be related to my prior post about the Contracts doing a similar thing https://github.com/StrangeLoopGames/EcoIssues/issues/3907.

This problem is also mentioned later down the chats in https://github.com/StrangeLoopGames/EcoIssues/issues/3913

Our Currency selections are switching which ones are selected and random times. Some stores will keep the settings for awhile while others change several times until they are on the selection at the top of the list. I'm attaching 4 screenshots. Two of the same store in the finance window, one of the store owners last login time, and the last one will be a property view of each screenshot giving a timestamp of each to reference that the individual was not online to do anything, I'm the only person online to that server and I do not have the access to change his currency setting.

![finance check 2](https://user-images.githubusercontent.com/9065496/35818589-b9e80156-0a5d-11e8-97be-81a343289762.png)
![finance check 1](https://user-images.githubusercontent.com/9065496/35818587-b77e80e8-0a5d-11e8-8431-47553cef41ba.png)
![last login for grimkor](https://user-images.githubusercontent.com/9065496/35818683-ed97f4f2-0a5d-11e8-8333-6c3707ca1860.png)
![screenshot timestamps](https://user-images.githubusercontent.com/9065496/35818698-f48cd3f4-0a5d-11e8-8992-01b55dee8cfd.png)

Pam on discord has suggested that we provide the dump folder logs and a copy of the world. Grimkor is the server owner and I'll link him this report so that he'll be able to provide that stuff.

**Comment by Matikari** [comment]
You can see Poy's Store at the top of each Economy viewer and his didn't switch during the screenshots, but it will switch at some other interval of time. His location is rather far from our location and may not be getting loaded without anyone near it.

**Comment by GibsonSWE** [comment]
This bug is almost making the game unplayable.. :(

**Comment by grimkorlp** [comment]
Here is the game.eco.  The dump folder is empty

https://drive.google.com/open?id=1ezgaxGXC6vAYENqKxFIXPdevtzv8tbwU

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix

**Comment by GibsonSWE** [comment]
Sweet, thank you for your hard work!! When will it be pushed?

**Comment by MarjieAVolk** [comment]
Should be tomorrow at the latest, maybe today

**Comment by tehflambo** [comment]
A year later, on 8.0.x, I'm working on writing up an issue that's almost identical to this one happening on our server. Have there been any other reports of this happening again?
