### ISSUE TITLE
Server CPU Utilization much higher 7

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3922]
Prior to 7.0.0 beta, the 7.0.0 staging versions had a much lower average CPU utilization. Average CPU usage with 3-5 players was between 20 and 40%. The screenshot below is from 7.0.2 with only 1 player on.

![image](https://user-images.githubusercontent.com/1503963/35819153-e52f099c-0a6f-11e8-8f82-1717dc489cdf.png)

**Comment by metachronism** [comment]
fixed for 7.0.3, a plugin was draining at least one entire CPU for itself
