### ISSUE TITLE
USER ISSUE: Lag is getting bad

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3923]
**Version:** 0.7.0.2 beta

When mining The Stone disappears when hit, then comes back as a block then turns into rubble, at some points you can mine 20 blocks and they all disappear then they come back when they decide to.

seems to increase the more people join a server, which sadly means they lag so they disconnect and connect again thinking this will help

**Comment by Gjafar** [comment]
Can confirm that! In 7.0.2 the lag is real. At serverlist it shows me my ping around 30 wich is normal but when i join its 200-400 on the server itself.

**Comment by Nanders** [comment]
I noticed this as well when playtesting.

**Comment by craig-jong** [comment]
Was some threading issues - will be fixed in newest staging.

**Comment by Conchipedia** [comment]
still happening 7.0.4
