### ISSUE TITLE
USER ISSUE: Cart duplication

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#3924]
**Version:** 0.6.4.2 alpha

**Steps to Reproduce:**
Log off after having a powered cart

**Expected behavior:**
i should continue to have one cart where i last parked the cart

**Actual behavior:**
I somehow have two carts one parked in front of one claim with no fuel or deed and another where i last parked my cart

**Comment by SeanAtr0n** [comment]
fixed in next build
