### ISSUE TITLE
Minor issue with content fitting on contract UI

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3928]
![image](https://user-images.githubusercontent.com/6262198/35825279-2aded158-0a6a-11e8-9a9a-73a47a2445ae.png)

Also this is not very readable

**Comment by SlayksWood** [comment]
Seems fixed:
![image](https://user-images.githubusercontent.com/45708377/71354670-bb3a5480-258d-11ea-84b3-01fa23be92f8.png)
