### ISSUE TITLE
You can edit Contract to be invalid after posting it. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3929]
I don't have Arend credit, so I cant create a contract that pays it.

I can create a contract that pays with my credit, then change it afterwards to pay Arend credit, which I don't have.

**Comment by johnkslg** [comment]
By design, you will always be able to do this. IE, I can unclaim property I've specified in the contract, or move chests for delivery. The contract says its invalid and doesnt allow claiming.
