### ISSUE TITLE
Webpage failing with empty error messages

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3930]
Same old nondescript orange bar.

Maybe we should have a default that just says "There was an error processing this request" or just "Error"

**Comment by MarjieAVolk** [comment]
I was just seeing that too as I tried to fix the auth id stuff.

**Comment by MarjieAVolk** [comment]
I noticed that this happened while I was not logged in properly.  After I logged in successfully, it started working again.

**Comment by rainfarmer** [comment]
empty error messages fixed
