### ISSUE TITLE
Workorder complete dialog gives the wrong message if its outputting to a linked inventory

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3932]
![image](https://user-images.githubusercontent.com/6262198/35826733-7a1dad80-0a6e-11e8-951b-5c1ff5e4a538.png)

This workorder is actually connected to a nearby chest. Confusing for new players.

**Comment by metachronism** [comment]
you can still access the items from the workbench

**Comment by Nanders** [comment]
I still think this can be confusing, even so.
