### ISSUE TITLE
Worldmarkers perform strangely (not at world border)

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3935]
![cabinwierdness](https://user-images.githubusercontent.com/6262198/35828159-65f729bc-0a73-11e8-95c9-cc7f193694d8.gif)

Makes them useless for navigation

**Comment by Nanders** [comment]
Gif is cropped, the worldmarker is roughly center in my screen.

**Comment by johnkslg** [comment]
If you're super close to it, that can happen expectedly.  Was that the case?

**Comment by Nanders** [comment]
I was not, this worldmarker was across the map
