### ISSUE TITLE
Migrating from 6.4.x to 7.0.x: World Occupancy Autogen throws exception

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3943]
The first time I load the 6.4 save in 7.0, world occupancy autogen throws an exception saying it can't find some objects.  If I click through and try to load again, it works.  I'm guessing this is an order of operations problem between world occupancy autogen and the other autogen.

**Comment by Nanders** [comment]
This probably doesn't need to be supported anymore
