### ISSUE TITLE
7.0.2 No Admin Rights

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#3944]
Having an issue were no admins can be added to the game either through the interface or editing the users.eco file.  The file shows them as there but the game is not recognizing them as admins.  Can not open server up to people untill I can get admin rights set up.

**Comment by MarjieAVolk** [comment]
I believe admin list now has to use uesr id, rather than username.  Is this your issue?  You can use /whois to find the user id.  This change was necessary for steam integration.

**Comment by Sarongas1999** [comment]
I can not invoke whois.

Im using my steam name also under admin rights.

**Comment by Sarongas1999** [comment]
wait I can /whoami and see, let me check real fast!

**Comment by MarjieAVolk** [comment]
Yeah it won't be your name, it will be a number probably

**Comment by Sarongas1999** [comment]
MarjiAVolk,

That worked!!

Now I am having an issue that the DevTool is not interactic with stone untill I use a pick on it unlike in 6.4.2 where I could just delete the blocks.

**Comment by MarjieAVolk** [comment]
Great!

Let's create a different bug for the dev tool issue.

**Comment by MarjieAVolk** [comment]
Here it is: https://github.com/StrangeLoopGames/EcoIssues/issues/3945

FYI we probably won't prioritize fixing the dev tool for a while; at least until the beta release is in a better state
