### ISSUE TITLE
DevTool won't delete stone

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3945]
"Now I am having an issue that the DevTool is not interactic with stone untill I use a pick on it unlike in 6.4.2 where I could just delete the blocks." -- @Sarongas1999

**Comment by Sarongas1999** [comment]
It actually wont delete dirt either.

**Comment by stormoffires** [comment]
#3859

**Comment by MarjieAVolk** [comment]
Ah yes you are right, okay closing this one as a duplicate
