### ISSUE TITLE
7.0.2 User being kicked and not being able to reconnect.

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#3950]
![screenshot_44](https://user-images.githubusercontent.com/36120114/35837185-630e7a36-0ab2-11e8-8e74-ebad0b437949.png)

**Comment by MarjieAVolk** [comment]
Looks like this got marked as fixed earlier but is not actually fixed: https://github.com/StrangeLoopGames/EcoIssues/issues/3712

**Comment by craig-jong** [comment]
We need repo steps for this because it doesn't occur every time you try to do this. Or a save file with a busted log in it.

**Comment by craig-jong** [comment]
Bumping priority because there isn't a way to test for this - I'm not sure if its even still happening.

**Comment by craig-jong** [comment]
Close thing, please reopen it if it occurs again.
