### ISSUE TITLE
More Window Wierdness

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3951]
![image](https://user-images.githubusercontent.com/6262198/35834555-3132359c-0a8b-11e8-8861-e2f56baa79a8.png)

**Comment by keegan-o** [comment]
I can't really see what's goin' on here...

**Comment by MarjieAVolk** [comment]
Took me a while too, it's the player name text.  The window clips it

**Comment by keegan-o** [comment]
Aha

**Comment by keegan-o** [comment]
Other window rendering issues highlighted well in other bug so closing this one #4019
