### ISSUE TITLE
7.0.2 User Disconnecting

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#3952]
7.0.2 Users disconnect after picking up logs or stone.

**Comment by MarjieAVolk** [comment]
Sounds like the same thing as https://github.com/StrangeLoopGames/EcoIssues/issues/3950

**Comment by MarjieAVolk** [comment]
@Sarongas1999 if you have any additional information on how to reproduce this error, that would be super helpful
