### ISSUE TITLE
Workorder madness

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3953]
Sometimes the icons for needed resources do not properly display in workorders

**Comment by MarjieAVolk** [comment]
I've noticed this too, always in a corner of my eye sort of way.  It seems sometimes the needed resources thing doesn't update and is showing the needed resources for a different order on the same object

**Comment by MarjieAVolk** [comment]
Okay this was being much worse for me this time than previously

**Comment by Huntermeign** [comment]
Work around until the fix is to click on your project 2 or more times to see the correct ammount (last tested on 7.0.2)

**Comment by MarjieAVolk** [comment]
Fixed in next release
