### ISSUE TITLE
USER ISSUE: Floating Tools after removing backpack

### ISSUE THREAD

**Issue by zenwidjet** [StrangeLoopGames/EcoIssues#3954]
![floating](https://user-images.githubusercontent.com/35677805/35838854-98554cae-0aaa-11e8-9de7-199a254bdccd.png)
**Version:** 0.7.0.2 beta

**Steps to Reproduce:**
open the backpack
click third person checkbox
take backpack off backpack and place in backpack

**Expected behavior:**
I would think that at a minimum the backpack and the items displayed on it are removed, if the user is not prevented from taking off the backpack and placing it in itself.

**Actual behavior:**
tools displayed on the backpack are shown floating behind player.

**Comment by SlayksWood** [comment]
merged with #12382
