### ISSUE TITLE
USER ISSUE: Wainwright Table Not Interactable

### ISSUE THREAD

**Issue by Trug42** [StrangeLoopGames/EcoIssues#3956]
**Version:** 0.7.0.2 beta

**Steps to Reproduce:**
1. Place a wainwright table
2. Ghost image of table shows up far away from selected location, but once placed the table appears to be in the right place
3. However, table is not interactable, and you can walk right through it

**Expected behavior:**
Been interactable

**Actual behavior:**
Is a ghost, not interactable and not physically present, just an image

**Comment by MarjieAVolk** [comment]
This was fixed today, the fix will be available in the next hotfix, which should be released tonight (https://github.com/StrangeLoopGames/EcoIssues/issues/3939)
