### ISSUE TITLE
Admins list reset on server restart

### ISSUE THREAD

**Issue by jmalish** [StrangeLoopGames/EcoIssues#3959]
I'm unable to set myself as admin on my dedicated server since the list seems to be reset on server restart. Unsure if this affects Whitelist and Blacklist lists as I haven't had a reason to use them.

I add my username to the Admins list using the String Collections Editor, and on server reset the field is blank again.

I attempted to change the admins list 3 times total with no luck.

**Comment by metachronism** [comment]
after setting the list, if you are doing it from the server frontend, click file->save
