### ISSUE TITLE
Wood pulp creates have missing models (7.0.2)

### ISSUE THREAD

**Issue by HerrGrinsel** [StrangeLoopGames/EcoIssues#3960]
When crafted and placed they are transparent, only the outlines can be seen
![image 2018-02-06 at 4 06 38 am_kopie](https://user-images.githubusercontent.com/35983642/35840081-3d3a5284-0af4-11e8-9bd5-135557d52318.png)

**Comment by MasterWhoMW** [comment]
Wood Pulp Creates is not in vanilla, I think this is from Clay's Mod.

**Comment by MarjieAVolk** [comment]
Ohhhh I wondered what that object was lol, I was like who added this
