### ISSUE TITLE
Color picker was broken

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3962]
![image](https://user-images.githubusercontent.com/23460210/35841159-6c570912-0aaf-11e8-8732-e9b6e31b111f.png)

**Comment by MarjieAVolk** [comment]
edit, it just looks like that when it is white lol

**Comment by elfl0rd** [comment]
looks not reproducible.
![default](https://user-images.githubusercontent.com/4980243/41868461-d58e2b36-78be-11e8-9492-aaa9363c4a76.png)

**Comment by MarjieAVolk** [comment]
It's fixed in the avatar window, but not the color picker popup.

**Comment by elfl0rd** [comment]
Yea, i see.
![error](https://user-images.githubusercontent.com/4980243/41871570-04e4b950-78c8-11e8-8db3-02f00e72c8f6.gif)
And no way to close it without color change.

**Comment by MarjieAVolk** [comment]
Fixed in 7.6 (Not the release today, but the one after).  There will be a close button as well.

**Comment by elfl0rd** [comment]
Cool :O
