### ISSUE TITLE
Stand Alone Torches Broken

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#3963]
Not accepting fuel, Needs a change to the accepted fuel type.
![screenshot_47](https://user-images.githubusercontent.com/36120114/35841551-9b21c1e0-0aca-11e8-93bd-db1569b9fce2.png)

**Comment by MarjieAVolk** [comment]
Working as intended, the idea is that you are putting your torch in the stand, and it gets consumed while it is turned on
