### ISSUE TITLE
When I split a room in half, room detection was not happy

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3967]
I had a big room, then added a divider wall to divide it in two.  At this point, room detection did not seem to detect that there were now two rooms.  Then I placed a chair in one of the rooms, and this seemed to cause that half of the room to become the 'real' room, and the other half of the room disappeared and did not count as a room anymore.  Triggering a refresh on the other half of the room by placing and picking up a block in a window space over there fixed it again.

**Comment by WeaselDog** [comment]
Still an issue in 0.8.3, especially if "Empty Blocks Count As Windows" is enabled. Needs more information on how to reproduce this before it can be addressed.

**Comment by SlayksWood** [comment]
@WeaselDog 
It was recently fixed in #12892. So we can close this issue.
