### ISSUE TITLE
District editor needs to be set on server periodically

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3971]
Right now, every time you edit the logic draft, the district editor gets reset.  It also is not saved if you reload the page, while the rest of the draft is.  The district editor needs to get set via logicDraft/districts/set, periodically, and/or when you end your edit of the map, and/or right before you change something in the draft

**Comment by MarjieAVolk** [comment]
Also, this prevents you from using the districts you define within the same law.  Eg. if you set the district data on the server, within the same law you will be able to reference those districts in a prevent action clause

**Comment by rainfarmer** [comment]
laws moved to in-game
