### ISSUE TITLE
USER ISSUE: Change resulation

### ISSUE THREAD

**Issue by MightyPiggie** [StrangeLoopGames/EcoIssues#3972]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
1. go to settings -> advanced settings
2. change resolution, then it asks for confirm.
3. try to not confirm, its not possible.

**Expected behavior:**
Should have a option to not confirm

**Actual behavior:**
Only the option for confirm.

**Comment by Nanders** [comment]
Just have to wait for the timer to run out
