### ISSUE TITLE
Kitchen not visible/usable

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#3974]
<a href="https://ibb.co/kbFY5c"><img src="https://preview.ibb.co/cGSfkc/kitchen_bug.jpg" alt="kitchen_bug" border="0"></a>

Can place the kitchen, but than... nothing... but it has an influence on my housing score?!

Also some trees from world generated in 7.0.2 are invisible...

**Comment by keegan-o** [comment]
Kitchen was fine on release and master, so just must have not made it into the steam build.
