### ISSUE TITLE
Contract Board limited selections in 0.7.0.3

### ISSUE THREAD

**Issue by MillanAireson** [StrangeLoopGames/EcoIssues#3975]
It appears that in 0.7.0.3 the items that you can select have been limited/restricted.  Not sure if this was intentional or not.  However, I would like to provide an example where I think this should be reconsidered if it was intentional.

I had a contract up where I was requesting someone place a skill book or scroll for Basic Engineering into a particular chest.  This book has not yet been created on the server.  This was my way of asking someone who has Stone Construction (a requirement to make the book) to make it for me.  In previous versions you could do this.  However, now it appears that the only skill books/scrolls I can request via this method on the contract board are those that I can make myself.  Why would I request it if I can make it myself?  Skill books are not the only items that have been limited.  I changed the request to an Add/Remove blocks from a site and there are only 10 block types available in the pick list.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#285
