### ISSUE TITLE
Minor: mill don't have texture until placement (beta 7.0.x)

### ISSUE THREAD

**Issue by spriti** [StrangeLoopGames/EcoIssues#3976]
When placing a mill, it don't show any acutall fotprint /texture. You have to guess and try, rotating and moving for best placement. Has been like this for 7.0.0 - 7.0.3. See attached screenshot
![mill placement2](https://user-images.githubusercontent.com/4130458/35870269-93f08086-0b61-11e8-84be-87ab5c8b77f5.JPG)
![mill placement1](https://user-images.githubusercontent.com/4130458/35870270-940b57f8-0b61-11e8-8672-c337d6ac4428.JPG)

**Comment by keegan-o** [comment]
Can't fix this until rob updates the FBX unfortunately.
