### ISSUE TITLE
Steam server update overwrites existing configs

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3977]
Can we make it not somehow?

**Comment by duckman** [comment]
The first time I found out about this, it majorly messed with my users skillpoints. Now with little patches coming out frequently (love this btw), I need to make sure I'm backing configs up before updates. Just remove the config files from the repo. I bet the code is already there to rebuild them if they aren't present. Anyways love the game. Keep up the great work.

**Comment by MarjieAVolk** [comment]
Putting myself on this too, because this goes along with splitting up save-specific configs versus gameplay configs (eg. we probably do want to overwrite ecosim configs on update?)

**Comment by D3nnis3n** [comment]
This is fixed in 8.2 by using templates, correct, @mirasrael?

**Comment by mirasrael** [comment]
Yes
