### ISSUE TITLE
Black screen only

### ISSUE THREAD

**Issue by mam241** [StrangeLoopGames/EcoIssues#3978]
I have the identical system listed in this post: https://github.com/StrangeLoopGames/EcoIssues/issues/3903 
I turned all Anti Virus software off and re-downloaded and unzipped the game and still get the same result. A black scree, modified pointer and birds chirping but that's it.

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3903

**Comment by MarjieAVolk** [comment]
Closing as duplicate
