### ISSUE TITLE
New planted trees invisable

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#3979]
https://drive.google.com/open?id=1XkdzRFIaQIZ4KVxRvwRDTQRFgVbCHtgL

Planted a total of 10 trees. Only 2 are visible one was a birch, the other a cedar.  The other 8 others are all cedar and are invisible as shown in the screenshot.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/37224874-98cb44c0-2389-11e8-8aa4-f957ecd6aa92.png)
Wasn't able to repro in master, I think someone fixed this.
