### ISSUE TITLE
Eco Server on Steam not updated to 7.0.3?

### ISSUE THREAD

**Issue by jarckn** [StrangeLoopGames/EcoIssues#3980]
Hey,

it seems, that the Eco Server in Steam hasn't been updated to 7.0.3, am I right?
Tried to update mine and reinstalled it without beta branch, but still an 7.0.2 executable.

If I use the 7.0.3 beta branch on my normal steam client, its working.
Maybe It's my fault, but in the steamcmd, it's not working.
The command I used for installing: app_update 739590 -beta 7.0.3 validate

Cheers,

Niklas

**Comment by Nanders** [comment]
You might have to uninstall and reinstall again. I'm looking into what causes this.
