### ISSUE TITLE
Steam link error

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#3981]
After clicking the button next to the steam link option on the home page it now says that my steam account is linked, However the game is not in my Steam library. I also saw a brief message after I clicked the link that said something along the lines of the key already being registered. 

![image](https://user-images.githubusercontent.com/4082137/35876406-2c3cc1be-0b40-11e8-852f-e10ab21a4f0d.png)

**Comment by Nanders** [comment]
Contact support@strangeloopgames.com
