### ISSUE TITLE
USER ISSUE: Cant create a news world

### ISSUE THREAD

**Issue by RoyHolzem** [StrangeLoopGames/EcoIssues#3982]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
I create a new world then it sends me to the desktop and nothing happens

**Expected behavior:**
created a new world and make me able to play

**Actual behavior:**
nothing happens

**Comment by Litschi123** [comment]
Sounds like the same problem as https://github.com/StrangeLoopGames/EcoIssues/issues/3997

**Comment by MarjieAVolk** [comment]
This one is for creating a world, the other is for joining
