### ISSUE TITLE
Farmer's Table

### ISSUE THREAD

**Issue by MillanAireson** [StrangeLoopGames/EcoIssues#3983]
If you are standing in front of the farmer's table the left side and the back side can not go directly against a wall.  You can however turn it with the back facing out and place it against a wall just fine as long as the left side (again if you are standing in front of it) is not in a corner against the wall.  This is version 0.7.0.3

**Comment by MillanAireson** [comment]
Nanders/Keegan-o,

While I agree that this should be low priority, I don't consider it a suggestion.  It is like when the shape of the table changed, the collision box did not.  That is a bug and shouldn't be a suggestion.

Anyway, just a little more feedback.  You guys are doing a great job!  Love the game!

**Comment by keegan-o** [comment]
Could be an occupancy bug, will check it out.

**Comment by keegan-o** [comment]
It was indeed, and we fixed it in internal release
