### ISSUE TITLE
USER ISSUE: Carpentry Table bug.

### ISSUE THREAD

**Issue by Orusblack** [StrangeLoopGames/EcoIssues#3991]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
1. Carpentry table.
2.Added 4 logs to board project.
3.Started a wainwright table project
4.Cancel.

**Expected behavior:**
It should give me 4 logs back.

**Actual behavior:**
It sayd my inventory is full, but its empty.
And now i cant take up the table.

**Comment by MarjieAVolk** [comment]
Do you have a different type of item in your carried slot?  Since logs are carried and you have only one slot for carried items, it's quite possible your inventory could not hold logs, even if it were mostly empty.

**Comment by MarjieAVolk** [comment]
Since I haven't heard from you, I'm going to assume your carried slot was full.
