### ISSUE TITLE
USER ISSUE: cant connect to friends world with steam

### ISSUE THREAD

**Issue by R3dpolarbear** [StrangeLoopGames/EcoIssues#3992]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
when i do shift+tab and then show friends. I cant click join world. The options on the friends world are friends can join. But that doesn't work.

**Expected behavior:**
it should have connected trough Steam

**Actual behavior:**
I can't click the join game button in steam

**Comment by Nanders** [comment]
If your friends send you an invitation, does this work?

**Comment by R3dpolarbear** [comment]
i found the fix i made a server trough steam

**Comment by R3dpolarbear** [comment]
but when i send invite is does also not work

**Comment by MarjieAVolk** [comment]
Is your friend on the same network as you?

**Comment by R3dpolarbear** [comment]
no he is not on the same network.

**Comment by Nanders** [comment]
This should be much improved with the new networking changes
