### ISSUE TITLE
USER ISSUE: Hewn logs vanish when placing

### ISSUE THREAD

**Issue by MeatHex** [StrangeLoopGames/EcoIssues#3994]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
take logs from bench place on ground and they vanish

**Expected behavior:**
make walls

**Actual behavior:**
hewn logs vanish when placing

**Comment by MarjieAVolk** [comment]
Are you placing the logs with a hammer?  Also, shot in the dark, but are you placing the logs into a stockpile or something, where they might be taken by a nearby crafting table for a queued project?
