### ISSUE TITLE
Wheat Crops Dying Randomly in Perfect area

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3996]
**Version:** 0.7.0.3 beta

Steps to reproduce:
Use in game map overlay for Wheatpotentialyield
Hoe the land, with yellow color. Plant wheat seeds.
Check planted seed with Soil sampler.
resulting in +- 80-100% wheat match.
Wait 5-8hour wheat is 100% grown,
first 2 times resulting in 60-90% of the wheat being fully grown
and the rest dead.

After planting a few times more, checking with soil sampler every
time, and the map overlay conditions seem good.

but now all the wheat is all dead.
and after inspecting the rest of the world it seems 99% of
all wheat on the map died. 

we have no more wheat on our server now, and cant reproduce wheat
with the seeds we have as the died again all.

Expected Behavior:
Plant wheat at perfect conditions, wait till it grows, harvest.
expect some loss 5-25% depending on the conditions.

Actual Behavior:
All the wheat dies.

![deadwheat](https://user-images.githubusercontent.com/29383891/35884868-ecb06d4a-0b83-11e8-990a-965c69e0d886.jpg)
![last_seed](https://user-images.githubusercontent.com/29383891/35884869-ecca2136-0b83-11e8-856a-b1842cf2bcae.jpg)

Doing this for another Player

**Comment by Zaskersky** [comment]
Loged in on multiple other server to check if the have wheat or not, and found out that there other server with the same problem having 0 wheat left on the world, cause of wheat random dying.

**Comment by craig-jong** [comment]
this was fixed with tended, but that doesn't mean the ecosystem doesn't need (another) change.
