### ISSUE TITLE
USER ISSUE: Cannot Join Servers/Singleplayer

### ISSUE THREAD

**Issue by WalrusKnight** [StrangeLoopGames/EcoIssues#3997]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Launch ECO
Try and join server/singleplayer

**Expected behavior:**
Join server/singleplayer

**Actual behavior:**
Fail to join sever/singleplayer, no message, return to title screen

**Comment by Litschi123** [comment]
A reinstall with deleting the folder _AppData\LocalLow\Strange Loop Games\Eco_ solved it for me.

**Comment by SeanAtr0n** [comment]
Could you retry and then send us output_log.txt in
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO` (paste that into file explorer)

**Comment by WalrusKnight** [comment]
Issue fixed on last patch; was simply an account connectivity issue.
