### ISSUE TITLE
USER ISSUE: Disconnecting and Reconnecting Via Steam Gives me a NEW Conchita#2

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3998]
**Version:** 0.7.0.3 beta

Just had the same Problem with Steam logging in as Arend, got disconnected chose join then server (i dont get much luck with continue at times) when i got in i had a new Avatar window pop up and Player on Discord Microphone said i was Conchita#2, i did not go past That screen i just pressed ESC and quit Eco, Quit Steam, Downloaded from SLG and playing as Normal character

**Comment by Nanders** [comment]
Is your slg and steam account linked?

**Comment by Nanders** [comment]
try relinking through your slg account page.

**Comment by HunterAshh** [comment]
Following, as I have the same issue since linking to Steam

**Comment by HunterAshh** [comment]
Also i have linked through the SLG account page. Don't know if this helps but I'm the one running the server and it seems that everyone else can connect with Steam without creating a secondary avatar.

**Comment by Nanders** [comment]
Some things are getting refreshed on our end. If you run in to this problem, you should only need to relink your steam account on slg (even if you've done it before)

**Comment by MarjieAVolk** [comment]
I believe this has been fixed now.
