### ISSUE TITLE
USER ISSUE: Non-widecreen

### ISSUE THREAD

**Issue by ecofriendlyplastic** [StrangeLoopGames/EcoIssues#3999]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Launch the game.

**Expected behavior:**
Game to be propped for non-widescreen users.

**Actual behavior:**
Left & right of the screen being cut off.

**Comment by Nanders** [comment]
Is this resolved by applying resolution settings in the escape menu?

**Comment by Nanders** [comment]
Fixed
