### ISSUE TITLE
Cant insert materials into workbench with right click

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#4001]
http://steamcommunity.com/app/382310/discussions/0/1699415798780577571/

**Comment by MarjieAVolk** [comment]
1. Place the workbench somewhere
2. try to craft any reciep that requires more than 1 ressource

Trying to craft the scyphe requires 3 Wood + 8 Stone but i am not able to carry both resources at the same time and placing them into the workbench does not work. It says "put stone" with a reght click overlay but it actually does nothing.

**Comment by MarjieAVolk** [comment]
Closing this as a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4007
