### ISSUE TITLE
USER ISSUE: The crop grows by logging in

### ISSUE THREAD

**Issue by Sebischwarz** [StrangeLoopGames/EcoIssues#4003]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Basically, I had some crap that was not fully grown, when I log out and in again the crop were fully grown.
**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Sounds like this might have been a visual glitch; eg. the crops were actually already full grown but they weren't displaying correctly, and logging back in fixed it.  Does that seem possible?

Was this on a local server?  (That is to say, when you logged out and back in, were you also stopping and restarting the server?)

**Comment by Sebischwarz** [comment]
It's not a visual glitch because I planted the crop, then log off and log in again and they were fully grown one I can get the resources out of them so it's not a visual glitch and playing alone with no one.

**Comment by knexer** [comment]
I think that this is likely related to https://github.com/StrangeLoopGames/EcoIssues/issues/4382

**Comment by angelocheck** [comment]
I have the same problem with plants. Planted the seeds, rebooted the server, plants grown on 100 % (tested by the analyzer). This happens after the last two updates, before the updates everything was fine. And yet again there primary job.

**Comment by Thyriel** [comment]
We're having the same issue with every plant / tree since 7.2. (Server)
This definitly did not happen in 7.1 to us

**Comment by SeanAtr0n** [comment]
fixed 7.3.2
