### ISSUE TITLE
USER ISSUE: Loading World

### ISSUE THREAD

**Issue by Litschi123** [StrangeLoopGames/EcoIssues#4006]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Join Server or local world

**Expected behavior:**
join the server/world

**Actual behavior:**
get back to startscreen

**Comment by Litschi123** [comment]
Same https://github.com/StrangeLoopGames/EcoIssues/issues/3997

**Comment by MarjieAVolk** [comment]
Yes you are right, closing this one as duplicate.  Think we have a few reports of this
