### ISSUE TITLE
You cant right click to add resources to a repair station

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4007]
Also cant click and drag

**Comment by MarjieAVolk** [comment]
Oh I misunderstood what was going on here, oops.  Thought there was a problem adding things to crafting projects.  The repair station doesn't store items at all.

**Comment by MarjieAVolk** [comment]
I might actually close this.  Since that's not how the repair station works.  We have a couple of other bugs open that are related to the issue I thought this was, namely https://github.com/StrangeLoopGames/EcoIssues/issues/4631 and https://github.com/StrangeLoopGames/EcoIssues/issues/3010
