### ISSUE TITLE
USER ISSUE: Unable to create world

### ISSUE THREAD

**Issue by Slothski** [StrangeLoopGames/EcoIssues#4008]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
1. Click New
2. Create game, (Happened with both generating new and keeping default)
3. fin

**Expected behavior:**
it should have put me into a world...

**Actual behavior:**
tabbed me out, put me back to main menu. I clicked load the world and it repeated the same

**Comment by Litschi123** [comment]
Sounds like the same problem as https://github.com/StrangeLoopGames/EcoIssues/issues/3997

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3982
