### ISSUE TITLE
Wooden Cart moves at an angle

### ISSUE THREAD

**Issue by jmalish** [StrangeLoopGames/EcoIssues#4009]
Version: 0.7.0.3 beta

Steps to Reproduce:
Pull cart and walk.

Expected behavior:
Cart moves in direction player is looking.

Actual behavior:
https://media.giphy.com/media/l3diC0910uF2ymzFm/giphy.gif
In the above gif, I'm just holding W. I've tapped A to make sure it's not a stuck key or anything like that. A game restart does not fix the issue.

Others on the server do not have the issue, so I assume it's something with my client.

**Comment by SeanAtr0n** [comment]
Do you have a controller plugged in? Might help to unplug it, I'll check if those controls need to switch to the new input system.

**Comment by jmalish** [comment]
I had racing pedals plugged in in the back of the computer that I forget about all the time. Unplugged those and the issue is gone. Sorry for the report.

**Comment by SeanAtr0n** [comment]
No problem, thanks for reporting 👍 Looks like we had some code using the old input system, I fixed it so you should be able to leave those plugged in soon. (will be in the build after today's hotfix build)
