### ISSUE TITLE
Update whitelist/admin/etc commands to handle users not yet on the server

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#4012]
eg

/admin slg <slgid>
/admin steam <steamid>
/whitelist slg <slgid>
/whitelist steam <steamid>

**Comment by stormoffires** [comment]
will this allow for remote banning/whitelisting? i know yall said we can ban in game with a command but what if i need to ban and I am not online nor can i get their steamID or SLGID?

**Comment by Amphysbaenas** [comment]
+1 we need tools to manage users correctly
We need for exemple 3 columns in users tab with nickname/slgid/steamid on Eco server panel

**Comment by metachronism** [comment]
this is already added
