### ISSUE TITLE
USER ISSUE: Can't Rejoin Server

### ISSUE THREAD

**Issue by amboo515** [StrangeLoopGames/EcoIssues#4013]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. Could not produce anything in game so I quit and try to rejoin.

2.I click on continue/have my friend invite me to the server.

3. I get a window that says 'Connecting'

**Expected behavior:**
I connect to the server and play.

**Actual behavior:**
The connecting window closes without me connecting and I'm still in the main menu every single attempt.

**Comment by MarjieAVolk** [comment]
May be related to https://github.com/StrangeLoopGames/EcoIssues/issues/4056

**Comment by MarjieAVolk** [comment]
So a couple questions - one, we've released several fixes since this issue was reported.  Are you still having a problem?

Two, are you seeing this on every server, or just a specific one?

And three, do you get any error messages when you are sent back to the main menu?

**Comment by MarjieAVolk** [comment]
Okay, so it's been a little while, so if you were having a NAT problem, it may already be solved.  The problem might be the Continue button.  Try connecting to the server using some other method.  You might also try deleting the folder 'C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO'.
