### ISSUE TITLE
USER ISSUE: Kiln Not Recognizing Tier 2 Materials in Room

### ISSUE THREAD

**Issue by Trug42** [StrangeLoopGames/EcoIssues#4017]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. Placed kiln in room with at least 32 mortared stone walls
2. Kiln shows as 0/32 Tier 2+ materials in the room

**Expected behavior:**
Recognized the room quality

**Actual behavior:**
Did not recognize the room quality

**Comment by Trug42** [comment]
Alright, figured out the issue - mortared stone is no longer considered T2 in 7.0.4. Not sure if this is workign as intended, or a bug.

**Comment by Amphysbaenas** [comment]
I confirm the problem:
![kilnissue1](https://user-images.githubusercontent.com/29807119/35913757-17273ea0-0c01-11e8-8087-ad9f1fd6f9cd.png)
![kilnissue2](https://user-images.githubusercontent.com/29807119/35913805-3bf00208-0c01-11e8-9b8f-42f9d301351c.png)
Actually it's impossible to use Kiln.

**Comment by jw1986** [comment]
Experienced this as well.
Brick, Glass are made at a Kiln, that needs tier 2.  Lumber is at a sawmill, that's Tier 1, but the Sawmill is made at  an Anvil - that needs Tier 2.  There's a loop you can't get passed

**Comment by DrPeppiX** [comment]
Yep, same here.

**Comment by modmynitro** [comment]
Same here.

**Comment by MightyPiggie** [comment]
Same over here.

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4042

This will be fixed in the next hotfix
