### ISSUE TITLE
USER ISSUE: Cast Iron Stove exhaust pipe connection in wrong spot

### ISSUE THREAD

**Issue by FRodz80** [StrangeLoopGames/EcoIssues#4024]
<b>Version:</b> 7.0.4 beta

<b>Steps to reproduce:</b>
Place Cast Iron Stove

<b>Expected behavior:</b>
Exhaust pipe on model should match with the connector to add pipe

<b>Actual behavior:</b>
Exhaust pipe connector is on the opposite side of model floating above the kettle

![20180206235002_1](https://user-images.githubusercontent.com/28557630/35900212-1ddd00c2-0ba7-11e8-97ba-66e32b78d6b1.jpg)

**Comment by keegan-o** [comment]
fixed in master/release
