### ISSUE TITLE
Servers are showing in browser before being online/world craeted

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4025]
pre 7.04 behaviors was (unless you did an add server) that servers did not show in browser until they were fully online or is a new world the world was completely generated.

Now they are showing up as soon as you start the .exe

This means people immediately see their server and try and jump in and get kicked back out to the main menu.  They are interpreting this as a broken server but if they wait until world is generated or server loads the kicking/connection failed issue is resolved and then they can log in and play.

Its frustrating to the player who sees the server in the browser so assumes its up and taking connections.

Can we either go back to it not showing up until world is generated/game is loaded or can we add a message in browser that tells people the server is 'creating world' and/or 'loading up"

**Comment by MarjieAVolk** [comment]
Upping this priority - There's a reason generating servers were being hidden, this might be one of the main connection issues we are having

**Comment by metachronism** [comment]
verified this as not being the case.  server doesnt listen for connections till its booted up
