### ISSUE TITLE
Suggestion - Research Tables

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4026]
A way to Hide all known skill in the research table, similar to the Show All skills in the Skill Tree.

**Comment by midn8t** [comment]
that would be sweet or maybe just something says this was researched or just take it off the list automatically.

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/10
