### ISSUE TITLE
invailed user token ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4027]
sometimes it logs in and plays and sometimes i get invalided user tooken.  ?

only issue with steam version of game that is linked to my account on here.

sometimes it also log me off and say invalided user out of the blue.

and sense the 7.0.4 update it was working then it kicks me says the above, and menus disappear, then i have to delete whole thing reinstall it all, then its 50 50 shoot that work and no clue to length of it working before i get booted.

after more research in server log files.

every time user logs into server it gives error

the remote server returned an error 504 gateway timeout -

I am guessing this is a authentication system  -considering that the client side log code says invalided user token ?

I found few other tickets in support system that referencing same issues that i noticed this causes

I am going guess that the GUI disappearing main menu is a piracy protection if not authentication then gui for main menu disappears.. ?

**Comment by gravestristen** [comment]
I believe this might be an authentication problem seeing as people in the discord are claiming that the authentication servers are down.

**Comment by clairemarshal** [comment]
@gravestristen website auth is down as well. Steam Hug of Death?
![hugofdeath](https://user-images.githubusercontent.com/35860809/35902066-ac3c9d64-0b8e-11e8-94da-9c99b0158d0c.png)

**Comment by MarjieAVolk** [comment]
We are fairly sure this was due to our auth servers going down last night.  Let me know if you continue experiencing this problem
