### ISSUE TITLE
USER ISSUE: Blank main menu

### ISSUE THREAD

**Issue by stuvik** [StrangeLoopGames/EcoIssues#4029]
Loading the game up (latest Steam version as of 5pm Australian Eastern Standard Time; File version 2017.3.0.63597) I do not see any menu options to start/join a game or access settings.

![20180207165339_1](https://user-images.githubusercontent.com/4761378/35901020-db54ab60-0c28-11e8-8302-f701a9e969d8.jpg)

Uninstalling and reinstalling ECO had no effect.

**Comment by ashpwnall** [comment]
i am also having this problem, you are not alone

**Comment by 89yoyos** [comment]
Same, I and 2 of my friends are having this issue

**Comment by Fr3aKeD** [comment]
I'm only guessing but I think the eco server for login or something is down? Cause I don't have one either. even after checking integrity and even uninstall and installing.

**Comment by midn8t** [comment]
yah its log in issue this is what happens on server side and client side linking this ticket.
https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Comment by hcmicko** [comment]
Update on Steam

NoBlackThunder  Officer	6 minutes ago
Server issues

Howdy peeps!
I am sorry to say we having some server issues causing trouble playing eco right now.
We hope that the issue can be resolved fast so we can get everyone back into the game as fast as possible.
I hope most of you can have an understanding that a steam release can be a bit rocky some times like now and we are again very sorry for the inconvenience this is causing to our players.
-NBT

**Comment by stuvik** [comment]
Cheers midn8t
So what's the fix for now? Do we just try again periodically?

**Comment by gravestristen** [comment]
@stuvik This issue has been fixed, the authentication servers are back online now

**Comment by MarjieAVolk** [comment]
We are fairly sure this was due to our auth servers going down last night. Let me know if you continue experiencing this problem
