### ISSUE TITLE
Ramps not detected as roads for carts

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#403]

**Comment by Faithlok** [comment]
We tested ramps out on our server. It seems that you have to make the blocks below the ramps into roads then place the ramp on top to get any sort of stable bonus. Otherwise, the ramp just reads the speed as whatever ground is below it.

**Comment by metachronism** [comment]
fixed

**Comment by fillion07** [comment]
This bug still exists in 5.2
