### ISSUE TITLE
ecoauth login is down! nginx error! 

### ISSUE THREAD

**Issue by clairemarshal** [StrangeLoopGames/EcoIssues#4031]
Scaling pains from the steam launch?
The website auth appears to be down.
https://ecoauth.strangeloopgames.com/home

I'm getting various bad gateway 502 failed login errors attempts when attempting to join the game from v0.7.0.4

![hugofdeath](https://user-images.githubusercontent.com/35860809/35901364-1479c248-0b8b-11e8-9108-f009dac19aeb.png)

**Comment by midn8t** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/4027  adding ticket i made sense this confirms what i put in it.

**Comment by clairemarshal** [comment]
@midn8t yup, I just saw your ticket. Mine isn't using steam. I got the login from alpha.

**Comment by clairemarshal** [comment]
servers back up! thanks
