### ISSUE TITLE
USER ISSUE: Bug Menu no show

### ISSUE THREAD

**Issue by koondiwza2015** [StrangeLoopGames/EcoIssues#4032]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by midn8t** [comment]
its user tooken login issue 

https://github.com/StrangeLoopGames/EcoIssues/issues/4027

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4027
