### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by alexandrage** [StrangeLoopGames/EcoIssues#4034]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Connection Failed

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by clairemarshal** [comment]
should be fixed now. I just got in.

**Comment by alexandrage** [comment]
Ok

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

We have been getting many reports of connection problems; we are working to resolve these as quickly as we can.  Hopefully it will be hotfixed today.
