### ISSUE TITLE
Massive CPU usage for 10+ players 7.1.2

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4035]
looks like it didnt get better, this is 7.0.4
![2018-02-07](https://user-images.githubusercontent.com/20627148/35913983-dea31bae-0bbe-11e8-92ae-f0fc4e639545.png)

at 10 isnt terrible but that jump once 11th guy got on to the 18th put us up almost 300%

**Comment by stormoffires** [comment]
![2018-02-10 1](https://user-images.githubusercontent.com/20627148/36066668-2a736044-0e6b-11e8-8089-8938e89de3d2.png)

with 7.0.8 and average 30-40 players on a day now... >_< its barely playable even with 10 on..

**Comment by stormoffires** [comment]
update with 7.1.2

over 300% CPU with 20+ folks.. 

<img width="633" alt="to much cpu" src="https://user-images.githubusercontent.com/20627148/36293011-56e5091c-1293-11e8-919e-7f4e4496afb0.PNG">

**Comment by metachronism** [comment]
should be basically fixed as of 7.2+
