### ISSUE TITLE
USER ISSUE: Roof tile problem

### ISSUE THREAD

**Issue by Trilint** [StrangeLoopGames/EcoIssues#4037]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. Place hewn logs in a stair pattern upwards.
2. Place roof tiles on the hewn logs

**Expected behavior:**
The roof tiles should connect to eachother forming a smooth roof

**Actual behavior:**
The roof tiles do not connect to eachother, but on each level they form the tiles which go ontop of a single hewn log, the roof ridge tiles (?)

**Comment by Nanders** [comment]
A screenshot would be helpful in this case, if you have one.

**Comment by keegan-o** [comment]
This is less a bug and more just un-ideal builder behavior-- I will be looking to improve the roof builder for sure though.

**Comment by MarjieAVolk** [comment]
I believe what works with the roof now is to use the roof on the wall as well.  (Correct me if I'm wrong @keegan-o)  So if you put the roof form on top and partway down the wall, the roof will connect

**Comment by Trilint** [comment]
![image](https://user-images.githubusercontent.com/36234466/35940905-f5767636-0c50-11e8-9f09-b1f59549da60.png)

This is how it looks when it's all put down

**Comment by keegan-o** [comment]
Ah yes, I guess I could consider this more of a bug than the other things that are not great about the builder. At the moment you need roof blocks under the top roof blocks for them to connect properly. Will look into fixing this, but it may end up being more difficult than one would think. If I let them merge with any other block, problems may arise elsewhere. I would recommend just putting roof form blocks underneath them for now.

**Comment by Trilint** [comment]
Okay, I will try that. Hopefully it works :) Thanks!
