### ISSUE TITLE
** Notify when steam linking re-enabled

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4038]
Where is my STEAM key No email or any instructions on how to get my steam version as was promised when i paid for this

**Comment by Coldroth** [comment]
Try on their website.
There should be a button to link your steam account to.

**Comment by cuda70** [comment]
that button is gone was there yesterday but not active today it says insert your key

**Comment by cuda70** [comment]
Thanks  please update us when this  is fixed and can link to steam

**Comment by Nanders** [comment]
Steam linking for SLG users -> Steam accounts is back online.
