### ISSUE TITLE
[Critical] Kiln requires materials that can't be crafted without Kiln being used.

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#4042]
Kiln now requires tier 2 mats in the room which cannot be created without using the kiln.

Brick - Made from the kiln
Glass - Made from the kiln
Lumber - Requires iron ingots which is made from the bloomery which is created at the kiln.

![image](https://user-images.githubusercontent.com/4082137/35925821-af6921fe-0bf4-11e8-84f7-11c3f4ce7721.png)

![image](https://user-images.githubusercontent.com/4082137/35925841-b9ab1456-0bf4-11e8-92b6-4b2ec6c78809.png)

![image](https://user-images.githubusercontent.com/4082137/35925854-c04c2f20-0bf4-11e8-902a-7ed633843d29.png)

**Comment by Conchipedia** [comment]
was working okay in 7.0.3 as it required Mortared stone for room (i had crafted nearly 200 brick for a book and someone else recipe) but now in 7.0.4 my Placed Kiln will not craft as it needs brick in the room as stated above which is **crafted on a Kiln****

**Comment by craig-jong** [comment]
This bug will be fixed in the next release. Sorry for the inconvenience! ):
