### ISSUE TITLE
USER ISSUE: falling through earth

### ISSUE THREAD

**Issue by Spencer12219** [StrangeLoopGames/EcoIssues#4044]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Just walk and jump onto another section of dirt

**Expected behavior:**
Allowed me to stay on land

**Actual behavior:**
Made me fall through the earth

**Comment by Huntermeign** [comment]
This is a well known issue the devs know about. Photos and recreations f the even or even a world save would help them find ways to fix this.

**Comment by Nanders** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3995
