### ISSUE TITLE
Two Ingame Names appeared one for Steam and one for SLG

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4045]
I was on Steam, Got disconnected and Eco stopped responding, loaded it back up and went Continue, i Appeared in game as Conchita#2 i typed /whoami gave me a number id (this is on SLG Discord) now cannot play as Conchita Via Steam as it is classed as Another Player, When i load up with SLG Download i get in no problem as Conchita typing /whoami give me SLGID (This is on SLG Discord)

If i load via Steam i am Conchita#2 no skills as classed as another Player
If i load via SLG Download i am Conchita

below is CTK /online command showing that it is also seeing me as two people
![snap1596](https://user-images.githubusercontent.com/29383891/35926767-e51547b6-0c20-11e8-97ad-bab15d3fd603.png)

and this is the Objectives Window Showing TWO of me and also TWO of Arend (as he has same problem)
![snap1598 edited](https://user-images.githubusercontent.com/29383891/35928625-841a033e-0c25-11e8-8b3e-5fc4c1bf1092.png)

I think the only fix for me would be for maybe my Account to be unlinked from Steam and i Link it again and see if that helps (but seeing as Steam is seeing me as Conchita#2 and SLG seeing me as Conchita i am not sure), but as Normal i leave it up to you ❤️ 

Do the Extra Player names need to be Deleted from the Server as well?

**Comment by Nanders** [comment]
I believe this is because of steam account linking being temporarily disabled while we put out some fires.

**Comment by Conchipedia** [comment]
is there anyway to get rid of Conchita#2 on Servers if i login with Steam? or will they have to be physically removed server side

**Comment by Nanders** [comment]
Right now it will have to be manually removed.

**Comment by Conchipedia** [comment]
ok, so if i ask Admin to remove Conchita#2 can i just play on SLG Version or if i load Steam will this cause same problem again?

**Comment by MarjieAVolk** [comment]
This might also be because your steam and slg accounts were unlinked again, that's another thing to check.

**Comment by Conchipedia** [comment]
i have nothing in SLG i checked no Steam links to choose from as you can see from this Snapshot (obviously bits removed as this is a public github)
![snap1600 edited](https://user-images.githubusercontent.com/29383891/35937156-4d064444-0c3d-11e8-844b-8221ff692956.png)

**Comment by MarjieAVolk** [comment]
Oh, I think the steam linking button might actually be disabled right now because of other issues, forgot about that O.o

**Comment by Conchipedia** [comment]
no problem, it is day 2 of Steam after all ❤️

**Comment by Phlo123** [comment]
@Nanders about the issue with the duplicate user files there is only the normal user file (ex:) Conchita and no Conchita#2. 
There are a lot of these tho...
https://cdn.discordapp.com/attachments/327556173005848589/410879481318866945/unknown.png

**Comment by Conchipedia** [comment]
Phlo [ADMIN] - Today at 7:32 PM
@Conchita there are no #2 user names in the save they are encrypted
i can't know which file is whos
😦1

**Comment by MarjieAVolk** [comment]
That is odd.  Well Conchita#2 is probably one of those.  Those look like steam ids.  If you log in as Conchita#2 and check /whoami it should give you an id that matches one of those.

**Comment by Conchipedia** [comment]
i have two ids SLGnumber for Conchita and then just a long number for Conchita#2

**Comment by MarjieAVolk** [comment]
Yeah, the long number is the steam id, I believe that should match the user filename

**Comment by MarjieAVolk** [comment]
Oh, it should match the part of the filename before the underscore ('_')

**Comment by Conchipedia** [comment]
so in response to our private Chat @MarjieAVolk  i will **ONLY** use the SLG Download until i hear different from you guys and the Steam Link is back in SLG account (then i will try again)

**Comment by MarjieAVolk** [comment]
Oh this should be resolved now :D

**Comment by Conchipedia** [comment]
Once the Admin deleted my duplicate Conchita#2 from a server everything just runs great now, no more choosing who to play with when i log in, it even solved the issue i had with currency 👍
