### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by KilyLayz** [StrangeLoopGames/EcoIssues#4049]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. I started a new game.
2. The game sent an error message.

**Expected behavior:**
The game starts.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

We have been getting many reports of connection problems; we are working to resolve these as quickly as we can.  Hopefully it will be hotfixed today.
