### ISSUE TITLE
USER ISSUE: Connection to Single Player Failed

### ISSUE THREAD

**Issue by Radeon18** [StrangeLoopGames/EcoIssues#4050]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
please fix so i can play singel mod 

**Expected behavior:**
started up 

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4056

We have been getting many reports of connection problems; we are working to resolve these as quickly as we can.  Hopefully it will be hotfixed today.
