### ISSUE TITLE
GAME BREAKING USSER ISSUE:Eco Doesnt Load/Join Anything (Windows 10) (Steam) (7.0.4) (7.0.3) etc

### ISSUE THREAD

**Issue by nachoghost** [StrangeLoopGames/EcoIssues#4051]
I bought the game yesterday, and I got a huge dissapointment. The game wont create/load/join anything. I have updated everything, made everything on my power to fix it, but nothing happened. If someone had this issue and knows had to fix it please tell me! It happens everytime

**Comment by nachoghost** [comment]
Im uploading a video showcasing the error. I dont get neither of those, it just throws me back into the main menu.

**Comment by MarjieAVolk** [comment]
Sounds like the same as https://github.com/StrangeLoopGames/EcoIssues/issues/4056?

**Comment by SeanAtr0n** [comment]
Could you try connecting again and after it fails send us output_log.txt from:
%APPDATA%\..\LocalLow\Strange Loop Games\ECO
(paste that into file explorer)
