### ISSUE TITLE
USER ISSUE: Contract invalid, can't create new one

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#4052]
**Version:** 0.7.0.4 beta

Got an error when creating contract. After reloading and trying again I get this message (in chat):

![20180207185321_1](https://user-images.githubusercontent.com/33501602/35932612-667cd35c-0c38-11e8-8b7b-3c3785f57be7.jpg)

**Comment by Nanders** [comment]
Duplicate issue of https://github.com/StrangeLoopGames/EcoIssues/issues/3927
