### ISSUE TITLE
QA commands need to be Developer-level access only

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4053]

**Comment by BlazeGuy2** [comment]
Aight, i'll play around with it.

**Comment by Nanders** [comment]
Should just be making sure our QA commands that are around in the ChatCommand system are all Developer Level.

Would go well with a better QA tool refactor.

**Comment by BlazeGuy2** [comment]
Refactor is in the works, will aim to update it hopefully once automated testing is in.  I'll also need to add Gabeux to the admin level since he helps me with the QA passes.

**Comment by WeaselDog** [comment]
I do not agree. It is helpful is players can test things for mods and other purposes.

**Comment by D3nnis3n** [comment]
Dangerous testing commands were made developer-only afaik.
