### ISSUE TITLE
USER ISSUE: Skill Points Disapearing

### ISSUE THREAD

**Issue by ProFatBoi** [StrangeLoopGames/EcoIssues#4054]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
1. Load into the game
2. Game displays 19 skill points
3. SKill points then disapear

**Expected behavior:**
Kept 19 skill points to be used

**Actual behavior:**
Showed 19 skill points then they all disapeard and showed 0

**Comment by craig-jong** [comment]
This was a display bug and is now fixed.
