### ISSUE TITLE
[User Issue] 7.0.4 - Rear of Farmers Table Return False Blocked Errors

### ISSUE THREAD

**Issue by NewtonGitHub** [StrangeLoopGames/EcoIssues#4055]
The rear of the farmers table is registering "Cannot place, blocked" errors when you try to put it 1 block in front of a wall with a clear gap between it and the wall. It must be placed very awkwardly 2 blocks from the wall.

**Comment by keegan-o** [comment]
fixed in release with code (prefab was fine was just the occupancy code)
