### ISSUE TITLE
USER ISSUE: Cannot connect to my server.

### ISSUE THREAD

**Issue by zerocool42** [StrangeLoopGames/EcoIssues#4056]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Trying to connect to my server.

**Expected behavior:**
I should have been connected to my server

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by SeanAtr0n** [comment]
verified i get the same when downloading client/server from our website

**Comment by MarjieAVolk** [comment]
Well at least we can repro!

**Comment by MarjieAVolk** [comment]
@zerocool42 and anyone else seeing this issue - Are you running from steam, or downloading from our website?

**Comment by SeanAtr0n** [comment]
odd... after logging in with steam once i can connect with either client

**Comment by SeanAtr0n** [comment]
A couple things to check... 
Did a windows firewall popup show in the background? Did you allow it?
delete everything in `%APPDATA%\..\LocalLow\Strange Loop Games\ECO` (paste that into file explorer)
Try connecting w/ steam if you have only tried an slg-only account today

**Comment by zerocool42** [comment]
I found the issue, I did not forward ports until after I set up and ran the server, so the server used UPnP and bound a different port without me knowing. When I later forwarded the correct ports, the server would not let me connect until after I set "DetectNAT" to false. I had to do this even after deleting the network.eco file which I assume resets the network config.

**Comment by cr0ss0vr** [comment]
I havent attempted the suggested fix from the above issue, yet... Why would NAT be interfering with a localhost\local server?

**Comment by zerocool42** [comment]
@cr0ss0vr 
When i set this up initially i could see in the network > config page that 3000/3001 was configured, but when i looked in the network > display page I had two other random ports. I think this may have "confused" the server to which port should actually be used. 

Note that the web interface was working the entire time, but I could not connect with the game client.

**Comment by MarjieAVolk** [comment]
We have fixed the problem with NAT that you guys were seeing.
