### ISSUE TITLE
Need a tickable to hide password-protected servers on server browser

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4057]

**Comment by metachronism** [comment]
for consideration during server browser work

**Comment by MarjieAVolk** [comment]
Hiding password protected servers sounds good.  What does a tickable have to do with it?

**Comment by Nanders** [comment]
So you can elect to hide servers that are password protected?

**Comment by MarjieAVolk** [comment]
Oh like a checkbox, I see now.  Thought you meant like the Tickable class on the server.

**Comment by MarjieAVolk** [comment]
Implemented in 7.4
