### ISSUE TITLE
USER ISSUE: The decay rate is too high

### ISSUE THREAD

**Issue by AMeadon** [StrangeLoopGames/EcoIssues#4060]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
This is not a bug, it's an optimisation issue. The decay rate is too high in the game right now. I built a house in my claim area, logged off for 2 hours, and when I came back online most of the house was gone.

Also, the cliff sides erode much too quickly, leaving the terrain looking pock-marked.	

**Expected behavior:**
I should be able to log off for a few hours without my house decaying.		

**Actual behavior:**
Decays within a few hours.

**Comment by MarjieAVolk** [comment]
Blocks should not be disappearing O.o So that is a bug lol

**Comment by knexer** [comment]
Was this on a multiplayer server? Did you have your house claimed as property? Could it have been other players taking your stuff?

**Comment by AMeadon** [comment]
Hey, @knexer,

I was playing on a multiplayer server, with the house built inside my claim area and permissions locked to only me.

**Comment by craig-jong** [comment]
The terrain doesn't actually erode. I'm not quite sure what to make of this bug, but it honestly sounds like an admin came along and griefed you.

I'm going to close this bug, but if you have any additional information or this occurs in a version above 7.5, please reopen the report.
