### ISSUE TITLE
USER ISSUE: Kiln Bug

### ISSUE THREAD

**Issue by Estrogix** [StrangeLoopGames/EcoIssues#4061]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
I need 32 tier 2 materials for the kiln but all tier 2 materials i make in kiln but i cant us it

**Expected behavior:**

**Actual behavior:**

**Comment by Conchipedia** [comment]
duplicate of **[Critical] Kiln requires materials that can't be crafted without Kiln being used. #4042**

**Comment by craig-jong** [comment]
This bug will be fixed in the next release. Sorry for the inconvenience! ):
