### ISSUE TITLE
USER ISSUE: cant load saves

### ISSUE THREAD

**Issue by lord-of-medusa** [StrangeLoopGames/EcoIssues#4062]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
create new local game
save and exit
load the game
after the "loadbars" finish it returns to menu

**Expected behavior:**
open the preveous worl

**Actual behavior:**
returns to main menu

**Comment by SeanAtr0n** [comment]
Were you manually running EcoServer during this?

**Comment by lord-of-medusa** [comment]
it would seem the hotfix update has fixed the problem entirely i have one by one replaced the old appdata folder and returned the old folder in its entirety and it is working now
