### ISSUE TITLE
Land Claim trolling

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4067]
so there is still ability to troll players what is happening here is someone just marking trees them selfs but no other land so that these new people can not cut down the trees near them.

add screen shoot 

![20180207161245_1](https://user-images.githubusercontent.com/15990789/35944628-b4fdb67e-0c22-11e8-8f46-d30b532e34b9.jpg)

**Comment by MarjieAVolk** [comment]
Players have pretty limited numbers of property claims early on, and can't craft them anymore (only way to get them is through skill scrolls), so I don't think this is a huge issue.
