### ISSUE TITLE
Right clicking torch turns it on and off. Does not put fuel. 

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4068]
![image](https://user-images.githubusercontent.com/6262198/35945994-ff4b4f2c-0c16-11e8-93d8-15ac94f5e77e.png)

**Comment by Nanders** [comment]
(also take is invalid as well)

**Comment by MarjieAVolk** [comment]
Ah yeah, the OnOffComponent overrides the right click behavior.  This might be non-deterministic depending on what order the components get added in, so we should probably not have on off use those controls... idk how to resolve really

**Comment by WeaselDog** [comment]
This will be fixed by https://github.com/StrangeLoopGames/EcoIssues/issues/4068

**Comment by SlayksWood** [comment]
merged to ##12338
