### ISSUE TITLE
[0.7.0.4] Error message in Eco gameserver console Crash possible

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4070]
Players that want to use the Eco gameserver website and Are not connected to Gameserver with the ecoclient generate a large amount of error message and may cause server crash if they try to vote a law.

each clic on website generate an error in console

![image](https://user-images.githubusercontent.com/29807119/35946183-20dc3de4-0c63-11e8-8d9f-f2a6bd1c7b6a.png)

**Comment by MarjieAVolk** [comment]
Oh yes... right, we just realized you can't currently use the browser functionality unless you are logged in to the game.  Which is a problem.  It should not otherwise damage your server though.
