### ISSUE TITLE
Single Player Max Slots defaults to 1

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4072]
This prevents people from joining their game.

If the set-up indicates "allow friends to join" this should especially be greater than 1.

**Comment by MarjieAVolk** [comment]
'Allow friends to join' sets the value to infinite.  Turning it off sets it to 1.  We can have it checked by default though

**Comment by MarjieAVolk** [comment]
Do you think this is why people are having connection problems? O.o  I hope that gives a good error message

**Comment by Nanders** [comment]
It was the case with more than one of the people I was supporting

**Comment by Nanders** [comment]
This case gives error message "connection failed server is full"

**Comment by MarjieAVolk** [comment]
Oh okay, that is good.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4285
