### ISSUE TITLE
USER ISSUE: Carrying and Stacking Bug

### ISSUE THREAD

**Issue by MTown05** [StrangeLoopGames/EcoIssues#4076]
**Version:** 0.7.0.4 beta

**Steps to Reproduce:**
Stand on top of a stockpile of wood, rock, etc and drop more material onto stack. The stack noise will occur but the material wont appear in the stack. You can click multiple times and the noise will occur but the stack wont increase. Then if you go and try to pick something else up it won't let you even though it shows you aren't carrying anything. It you go back to the stack and pick something up it will show the carrying counter increasing but no picture will appear of that material. You also aren't able to drop any of the material.

**Expected behavior:**
The stack should of increased in size as more material was stacked onto it. 

**Actual behavior:**
The stack size did not increase but the sound for stacking material occured.

**Comment by craig-jong** [comment]
I believe this has been fixed in the current staging.

If this issue persists past 7.3, please reopen this issue.
