### ISSUE TITLE
Issue reloging into world

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4085]
so I been playing game on server, and then to deal with someone in game i added my user name as admin

now when ever i log in i get this error

![new bitmap image](https://user-images.githubusercontent.com/15990789/35952339-25b58884-0c45-11e8-9dd4-51ee63424a4f.jpg)

**Comment by midn8t** [comment]
reboot server fixed it, but it didnt just effect me it seemed to effect every one trying to log into server.

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/4083

**Comment by MarjieAVolk** [comment]
Okay so you think the admin list is what did it?  Seems plausible...

**Comment by MarjieAVolk** [comment]
Oh wait I think I know what is up with this.  That is, I know just where to add a null check :P Was just working on a fix for this code anyway, so that works out

**Comment by MarjieAVolk** [comment]
This should be resolved now ^
