### ISSUE TITLE
USER ISSUE: unknown kick

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4087]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
was just standing

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Gonna be pretty hard to do anything with this without a stack trace >>

Man @metachronism how do we get stack traces to display in the kick popups?  That would be so helpful
