### ISSUE TITLE
USER ISSUE: Stuck on entering world

### ISSUE THREAD

**Issue by cyberferret2** [StrangeLoopGames/EcoIssues#4091]
When I try to enter the world it goes to the entering world screen and spins the gear thing forever. I have waited several minute and nothing happens. If I press the Tab button it will enter me into the world with a blank screen where I can only see the UI. I can interact with the UI on the blank screen.

**Comment by cyberferret2** [comment]
Update I can connect to other worlds, just not the one I have been playing on.

**Comment by ashpwnall** [comment]
I'm having the same issue, i can't connect to servers, but i can connect to my solo world. (the start game option at main menu). but nothing else works

**Comment by SeanAtr0n** [comment]
The servers that hit this issue need to be restarted, hopefully you can contact their admins?

(which servers btw?)

**Comment by cyberferret2** [comment]
[US-East] Exogenz [ Fresh World 2/6 ] [Large 4 Km. World with 4X SkillRate!] [Https://discord.gg/a6eB4K3]
Ashpwnall is also from the same server.

**Comment by metachronism** [comment]
should be fixed in 7.2
