### ISSUE TITLE
USER ISSUE: Scroll of farming won't work

### ISSUE THREAD

**Issue by Pringie** [StrangeLoopGames/EcoIssues#4095]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
I click the scroll to consume it

**Expected behavior:**
The scroll getting consumed and learning farming

**Actual behavior:**
Doesn't work and the scroll is still in my inventory

**Comment by MarjieAVolk** [comment]
You need to show your cursor and right click on the scroll in order to use it.  Is that what you are doing?
