### ISSUE TITLE
Placing property claim causes lag for everyone on server

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4097]

**Comment by Amphysbaenas** [comment]
I can confirm That.
Every time a players place a new property flag, all players have a micro freeze 0.5-1second

**Comment by ecoemmeck** [comment]
I can also confirm this.
It's both when players are claiming and unclaiming land.
Thought it's only a short lag spike

**Comment by ChrisMayhew** [comment]
We also get this on our server.

**Comment by metachronism** [comment]
fixed!
