### ISSUE TITLE
High CPU usage even on idling servers

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4099]
I gotten quite a few complains of high cpu usage from server admins across the board since the installed 7.05.  Many are saying that there servers are using, consistently 80-100% CPU when idle and pegged at 100% when anyone is online.  They are experiencing lag.  Some reports put the CP usage that high associated with 20+ people online but they did not test to tell at how many are on when the CPU starts going up.  I have updated one test server and on that one servers their reports appear to be repro'ed

**Comment by MarjieAVolk** [comment]
I believe performance has been improved quite a bit since 7.0.5
