### ISSUE TITLE
USER ISSUE: Tried to Rejoin server after bad lag

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4101]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4144 . You can continue tracking the issue there.
