### ISSUE TITLE
Eco thinks its running all the time in Steam

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#4102]
I was not able to start the game in this state:

![image](https://user-images.githubusercontent.com/3536496/35957043-33aa4c64-0c4e-11e8-9734-0edae43a459d.png)

**Comment by johnkslg** [comment]
Looks like this only happens when emulating in Unity.

**Comment by Arend90** [comment]
happend to me a few time 2 few days ago

**Comment by Amphysbaenas** [comment]
+1 happend to me 1 hours ago had to restart computer

**Comment by Nanders** [comment]
This will always happen when emulating in Unity, there is no way around this. 

If you ever run with "Emulate as Steam Client" ticked that unity session will be tied to steam and will not release until closing Unity or steam entirely.
