### ISSUE TITLE
USER ISSUE: Catapaulting Carts

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4105]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Pick up the same peice of dirt and put it into a cart.

All other dirt works fine, just that one peice makes the cart flip out

**Expected behavior:**
cart should sit where it is placed

**Actual behavior:**
It flies into the air and lands elsewhere.

**Comment by sashakriv** [comment]
I've been having this issue. It's not all dirt, but there will be a piece here or there that flings my cart up in the air and about 50m away. I think I also saw it happen with coal.

**Comment by Zoratan** [comment]
My cart took me on a trip to space ( 300m, all dark) and landed in the ocean (containing Logs and Tailings)

**Comment by Zoratan** [comment]
seems to happen often, i cant even use the wood cart (didnt have any problem with the small one so far) as mining transporter. It also glitches through stones and dirt on its way up to the stars.

maybe we can use it to transport an explosive payload to the asteroid and dont have to research lasers :D

**Comment by Nanders** [comment]
This might be related to a world border problem. Getting reports of those on steam.

**Comment by SeanAtr0n** [comment]
Fixed 7.2
