### ISSUE TITLE
Not getting items from skills

### ISSUE THREAD

**Issue by LLIV** [StrangeLoopGames/EcoIssues#4106]
Fresh server on 10.0.5

Other players are fine.

I dont get the carftingtable from skills in the start. ID:  slg70042 my friend is playing from steam.
tryd "erasing me from the server" to restart and see if i get it ther. but still dont work,

no dump on the server.

**Comment by LLIV** [comment]
if i join other server still dont get the crafting table

**Comment by LLIV** [comment]
TBH i dont care eny more, the game did run smother back in 5.x might chek the game out when complited

**Comment by MarjieAVolk** [comment]
You no longer get the workbench from skills.  You get it from the tutorial.  If you don't want to complete the tutorial, you can skip it by hovering over it and clicking 'x'.  Skipping it will also give you the items
