### ISSUE TITLE
USER ISSUE: Flying Wood.

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4108]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Chop tree laying on ground.

**Expected behavior:**
Wood breaks into sections to pick up.

**Actual behavior:**
Tree trunk flew into air as if there was no gravity.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668.
