### ISSUE TITLE
USER ISSUE: Wood chart

### ISSUE THREAD

**Issue by theotheoderich** [StrangeLoopGames/EcoIssues#4110]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Build a wood chart
Try to take it

**Expected behavior:**
It should have moved

**Actual behavior:**
The following error message popped up:
Caught exception: Object reference not set to an instance of an object.
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Sorry for the delayed response.  When you say you 'built' a cart and then tried to 'take' it, do you mean you placed the cart and then tried to take the handles to pull it?  Or do you mean you crafted the cart and then tried to collect it from the crafting station?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
