### ISSUE TITLE
USER ISSUE: WainWright Table

### ISSUE THREAD

**Issue by Lakerace** [StrangeLoopGames/EcoIssues#4112]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
The WainWright Table will only accept 20 wood, it needs 40 but won't allow you to drag and drop 20 more wood to complete the Wainwright Table.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
There is definitely a problem with dragging and dropping things into crafting projects.  Try right clicking on the table while holding the wood, or putting the wood into a linked inventory.

**Comment by MarjieAVolk** [comment]
Closing due to no response.  We have some other bugs open about adding resources to projects (https://github.com/StrangeLoopGames/EcoIssues/issues/4631, https://github.com/StrangeLoopGames/EcoIssues/issues/4007, https://github.com/StrangeLoopGames/EcoIssues/issues/3010).
