### ISSUE TITLE
USER ISSUE: Getting stuck in stockpile

### ISSUE THREAD

**Issue by kristianstage** [StrangeLoopGames/EcoIssues#4113]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
stuck in stockpile
after putting down stones

**Expected behavior:**
just put down the stones	

**Actual behavior:**
now i cant move and it looks like i have to start the game all over again :(

**Comment by Nanders** [comment]
/unstuck will get you out.

Could do with better depenetration on the character controller, especially with how fast stockpile places blocks.

**Comment by MarjieAVolk** [comment]
The character controller used to pop out of things really well, and now it doesn't.  What changed?

**Comment by SeanAtr0n** [comment]
fixed 7.2
