### ISSUE TITLE
USER ISSUE: Problems connecting to the server

### ISSUE THREAD

**Issue by PASK2635** [StrangeLoopGames/EcoIssues#4114]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Click "Load" to connect to server
2. Connecting to server

**Expected behavior:**
It should have connected to the server

**Actual behavior:**
It's having trouble compiling mods.
Connection Failed.
```

**Comment by Huntermeign** [comment]
This seems like an issue with the server itself. Can you connect to other servers?

**Comment by MarjieAVolk** [comment]
You say it's having trouble compiling mods.  What makes you say that?  Does your game client have mods matching the server?

Unfortunately I can't necessarily help you with arbitrary mods - you might need to go to your server's admin or fellow players for advice
