### ISSUE TITLE
USER ISSUE: Open/close chest

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#4115]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Open Storage Chest
2. Close window
3. stuck in front of it
4. can't unstuck with /unstuck, cause can't open chat
5. using "report bug" unstucks you ;D 

**Expected behavior:**
can do my work after opened and closed a chest

**Actual behavior:**
stuck in front of chest

**Comment by MarjieAVolk** [comment]
O.o Man I don't know where to start on this one

Okay, so you say you were stuck - You couldn't walk around obviously.  Could you look around?  You say chat wouldn't come up - so hitting enter didn't do anything?  But you also say you were able to open the escape menu and click Report a Bug, so you were able to use your mouse?  Were you able to move things around in your inventory?

**Comment by Bazzi89** [comment]
Sorry for the late answer, I can use the mouse and turn around, can use "esc"... thats it! Friend of me has the "same" problem while moving things from stockpile to cart or stockpile to stockpile etc..

**Comment by MarjieAVolk** [comment]
O.o  So I'm just triple checking because this behavior sounds really strange.  You couldn't show your cursor in any way other than via escape?  None of the hot keys to open windows worked?  Hitting tab to show the cursor did not work?

**Comment by MarjieAVolk** [comment]
Do you have any client error logs?

**Comment by Bazzi89** [comment]
We have a new savegame with the same problem. Maybe I could make a short video... I can upload the savegame tomorrow.

**Comment by MarjieAVolk** [comment]
By the way, to all those who may be following this - When you get stuck like this, it seems that pressing Tab and/or Escape will often fix it.

**Comment by MarjieAVolk** [comment]
Alriiight, this will be fixed in the next staging build.
