### ISSUE TITLE
Admin tool issue

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4119]
We had issues with some trolling on server so we decided to use admin command repopulate to repopulate the world.

now it seems to be doing it every so many mins constantly none stop is there way to turn it off it just seems to be stuck in a loop we will dig an area, or cut down trees and few 30 mins or so pass and then stuff regenerate full size instantly.

**Comment by midn8t** [comment]
update to this i did /repopulate stop 

and now everything is just dieing around whole world. lol

**Comment by midn8t** [comment]
guess best way after words was just to in cress time multiplayer in tool set and let game take care of it self so far.

**Comment by Nanders** [comment]
Yeah, lots of those commands are less Admin commands and more Developer commands.

We need to build a better, more stable toolkit for admins, and remove or obfuscate unstable Dev commands.

**Comment by elfl0rd** [comment]
@D3nnis3n fixed

**Comment by SlayksWood** [comment]
This command isn't available now.
