### ISSUE TITLE
Lag returns?

### ISSUE THREAD

**Issue by Gjafar** [StrangeLoopGames/EcoIssues#4120]
Same lag is back on my server as 7.0.2 had. 
Can anybody confirm?

**Comment by ChrisMayhew** [comment]
People on my server are reporting issues with lag

**Comment by Gjafar** [comment]
I figured out another lag wich comes from, when someone claims something.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4097

We have had a couple reports of lag when claiming property
