### ISSUE TITLE
Acorns and Pinecones?

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#4121]
Not sure if its just our server or not but we have not been able to yield any seeds from Oak and Fir.

**Comment by Nanders** [comment]
You have to axe the leaf clumps to get seed drops and there is a fairly low drop chance.

Should maybe get seeds from picking up logs?

**Comment by Huntermeign** [comment]
I know how to get them and I am a forest forager. The leaves for firs don't seem to highlight when I am near them and I've yet to come across acrons, and people on the server haven't been able to get any either. I can ask again and maybe as another server but we had a clean sweep of the server for 7.0.4 and I was actively seeking it out since then.

**Comment by Huntermeign** [comment]
We are currently on 7.0.5

**Comment by Huntermeign** [comment]
Also, whenever I type in Pinecone or fir seed there is no link in the chat to the item (other than fir highlighitng)

**Comment by Huntermeign** [comment]
If we are turning this into a suggestion, maybe have the items drop similarly to how wood pulp drops and appear as they trample the ground.

**Comment by ecoemmeck** [comment]
I also haven't noticed seeds for the other new tree which name currently escapes me

**Comment by Bazzi89** [comment]
Whats the problem with the oak and fir seeds?
