### ISSUE TITLE
USER ISSUE: Tools becoming axes

### ISSUE THREAD

**Issue by MusicianPoodle** [StrangeLoopGames/EcoIssues#4122]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**
Exit game.  Attempt new game to try to resolve another issue posted elsewhere.  Re-enter this save game at a later time. 

**Expected behavior:**
Tools to save as created.  

**Actual behavior:**
Stone hammer pickaxe disappeared.  Should have 1 stone axe, 1 iron axe. Now have 2 and other items have vanished.

Must abandon this save - can't recreate hammer with no stone and no pickaxe to mine it!

**Comment by metachronism** [comment]
should be fixed in 7.2, view system error
