### ISSUE TITLE
New Server Console Error

### ISSUE THREAD

**Issue by ChrisMayhew** [StrangeLoopGames/EcoIssues#4124]
I’ve just updated to 0.7.0.5 and people are having issues logging in. In the console I’m now getting this error

“[05:12] Error when verifying login token: Could not convert string to boolean: Token is invalid.. Path 'status', line 1, position 29.”

Plus people who can get on are reporting lag.

**Comment by MarjieAVolk** [comment]
Sounds like there was a mistmatch between the auth server and the game server.  I believe yesterday there was a brief period where we launched a change to the auth server that broke things and then had to be rolled back.  @rainfarmer does this sound like it could be related?  If /response was returning something other than true or false for 'status' for example?

@ChrisMayhew I believe this has been permanently resolved already.  Are you still seeing the issue?

**Comment by ChrisMayhew** [comment]
@MarjieAVolk Yeah I have seen this in 0.7.0.6 tonight, same error.

**Comment by MarjieAVolk** [comment]
I see :/

Okay @rainfarmer that error message seems to be coming from /verifytokenv3 . The only bool in the response from that, on our side, is 'status'.  Is there a case where 'status' returns something other than true or false?

**Comment by ChrisMayhew** [comment]
It's still coming up on 0.7.0.8 too.

Also got this one today.

`Disconnecting client [reason: Caught exception: Caught exception invoking RPC GetTooltip on MinimapManager!

Object reference not set to an instance of an object


Stack:
  at Eco.Gameplay.Minimap.MinimapManager.GetTooltip (System.Int32 id, Eco.Gameplay.Players.Player player) [0x0000a] in <efc4801d57b44d24b4bfe33453fe2af2>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <997dde78663c4b4bbf4a1f2b8d296905>:0 
]...`

**Comment by Novae7** [comment]
Hi,

i have the same issue on a fresh installed Server (installed over SteamCMD) 0.7.0.8 beta

Everything works until i try to login on the website.
After click on login the server trows:
`Error when verifying login token: could not convert string to boolean: Tolen is invalid.. path 'status', line 1, position29.`
and the website is stuck at "loading"

i tried to run the server as admin but that didnt change anything.
with this the website features which requires a login are not useable.

The server is an windows 2012-R2 with an Public IP.
Firewall enabled but port 3000-3001 TCP are open.

br Novae

**Comment by MarjieAVolk** [comment]
Okay, we have fixed the 'status' conversion error.  For the record, this will just mean that you will get a different (hopefully better) error message when you are kicked with this issue.  It seems this message was popping up mostly for people whose login information was bad, but hopefully we'll get this out there and you will be able to see what the problem was in your cases.

**Comment by MarjieAVolk** [comment]
@ChrisMayhew I have filed a separate bug for your minimap tooltip exception: https://github.com/StrangeLoopGames/EcoIssues/issues/4419
