### ISSUE TITLE
USER ISSUE: Cannot see any multiplayer servers

### ISSUE THREAD

**Issue by ziedjebali** [StrangeLoopGames/EcoIssues#4128]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
I restarted my computer and relaunched eco mid making a server.

I relaunched the game and went into join, now there weren't any servers anymore.

I tried reinstalling but still the same behavior.	

**Expected behavior:**
Servers showing all the possible games to join.

**Actual behavior:**
No servers showing in server browser.

**Comment by metachronism** [comment]
this is an error that could occur when loading the favorites file in your user storage, should be fixed in 7.2
