### ISSUE TITLE
0.7.0.5: Contracts lose references to items types and counts after a server reboot.

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#4129]
Before server reset:

![image](https://user-images.githubusercontent.com/2173684/35994654-d7d84eda-0d5c-11e8-8d1a-72586b93d211.png)

After server reset:

![image](https://user-images.githubusercontent.com/2173684/35994622-bb1372a2-0d5c-11e8-8012-d738314be633.png)

Server is running on Eco Server 0.7.0.5, on Mono, on Linux.

**Comment by johnkslg** [comment]
Fixed! Thank you.

Fixed ‘Items In Container’ contracts not saving list of items.
Fixed inserting items via right-click not counting for contracts.
Fixed display of items left to place in world markers for contracts.
Fixed Contracts to properly handle temporary, limited authorization on objects (you can put bricks into a container you don’t own if you have a contract allowing it, but you can’t remove them).
