### ISSUE TITLE
USER ISSUE: players kicked

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4139]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
players get kicked out of server wheather they are on lan or ip after a few mins constantly

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
This sounds like it was due to our auth servers going down; They were down for just a few minutes earlier today, I believe it was around the time you posted this bug.  Are you still having the problem?

Closing for now, but if you have further issues, I will rexamine

**Comment by rsgodkilla** [comment]
no this has been happening since the 6th i know of a few people thats been having the problem
