### ISSUE TITLE
USER ISSUE: THE DOOR

### ISSUE THREAD

**Issue by BlueWolfITA** [StrangeLoopGames/EcoIssues#4140]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
I placed my door and when i opened it launched me on top of the door inside the the roof

**Expected behavior:**
to open and maybe push me a little bit away or go trough me

**Actual behavior:**
 it launched me on top of the door inside the the roof

**Comment by MarjieAVolk** [comment]
Doors generally push you very violently, if someone opens one into you

**Comment by BlueWolfITA** [comment]
Yea Buit dosnt put me on top of it

**Comment by BlueWolfITA** [comment]
But*

**Comment by MarjieAVolk** [comment]
> I can consistently reproduce getting stuck in the ceiling or making the game i'm falling great heights by running into an opening door from the right angle (jumping optional).
> 
> Quick video of it:
> https://youtu.be/7Nt-u__sYeM
-- @WhAtEvErYoUmEaN

**Comment by GophTheGreat** [comment]
Could not reproduce. Reopen if it occurs again.
