### ISSUE TITLE
USER ISSUE: Fell through world with cart

### ISSUE THREAD

**Issue by polarim** [StrangeLoopGames/EcoIssues#4142]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
I was going down a road ramp guy made, with cart, and fell through world endlessly. had to disconnect and reconnect to fix. Lost cart and stacks of wood.

**Expected behavior:**
It shouldn't have fallen through the world

**Actual behavior:**
Made me fall through the world and lose my stuff.

**Comment by SeanAtr0n** [comment]
Fixed 7.2
