### ISSUE TITLE
(Suggestion) housing refinement

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4143]
the washing board and washing machine should have there own category such as laundry or something along those lines
As currently it's in the bathroom category

**Comment by johnkslg** [comment]
Done!

**Comment by ecoemmeck** [comment]
theses are still considered as bathroom objects

![image](https://user-images.githubusercontent.com/29722757/38161548-a16042a8-351c-11e8-98e9-97029fbfe0bc.png)

![image](https://user-images.githubusercontent.com/29722757/38161552-bdfbd206-351c-11e8-8cc5-4a66e4616b47.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#283
