### ISSUE TITLE
USER ISSUE: Connection Error

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4144]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. The game will time out randomly without reason on the player and send him to the main screen. With the error message: "Inactivity."
2. The player tries to log back in to the server and is presented with another error message.

**Expected behavior:**
It should have allowed the player to log back in.

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Object reference not set to an instance of an object.
```

**Comment by metachronism** [comment]
fixed in 7.2, lots of optimizations
