### ISSUE TITLE
Suggestion Arrows

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4146]
now that you can see the arrows sticking in the animals, you should also recover about 25% of arrows back
especially with a high hunter level.  (that might be what the other levels of Hunting do)

**Comment by ecoemmeck** [comment]
I like this idea I had thought about modding it into the butchering recipes but wasn't sure how to fairly implement it

**Comment by Dr-Hardware** [comment]
I'd work it as an "on corpse pickup" personally.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#282
