### ISSUE TITLE
USER ISSUE: SpecialtyCostMultiplier

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4147]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
SpecialtyCostMultiplier
is set to 15.0 instead 0.15 when starting a singleplayer game with "no collab"

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
:O Just checking, you determined this is not an issue?

**Comment by ownyHD** [comment]
because i closed? for me its not, since i can change it easily in the difficulty.eco. just wanted to mention it.
