### ISSUE TITLE
USER ISSUE: Random wooden cart bug

### ISSUE THREAD

**Issue by Celticdragon** [StrangeLoopGames/EcoIssues#4149]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Randomly releasing a cart.

**Expected behavior:**
It should have stayed put.

**Actual behavior:**
Instead it went flying through the air.

**Comment by Zoratan** [comment]
already reported there: https://github.com/StrangeLoopGames/EcoIssues/issues/4105

**Comment by MarjieAVolk** [comment]
I will leave both open, as it seems one was triggered by picking up a block, and one was triggered by releasing the cart

**Comment by Zoratan** [comment]
okay, i also experienced the behavior when i dont do anything with it, when I take things out with tools equipped to move stuff to my stockpile or put something in. 
I am not sure but i have the feeling it happens more often when it stands on a dirt road, no difference if flat or on a ramp though.

**Comment by SeanAtr0n** [comment]
were you in third person at the time?

**Comment by SeanAtr0n** [comment]
fixed in 7.2
