### ISSUE TITLE
USER ISSUE: Misspelling

### ISSUE THREAD

**Issue by Redmonkey1313** [StrangeLoopGames/EcoIssues#4150]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Make charred corn.

**Expected behavior:**
It should say "butter to curb that burnt taste" in the item description

**Actual behavior:**
It says "butter to crub that burnt taste"

**Comment by craig-jong** [comment]
Welp, its been a while but I just fixed this.
