### ISSUE TITLE
Axe and Hammer turned into Pickaxes?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4151]
@MusicianPoodle says that their axe and hammer turned into pickaxes in their inventory (see https://github.com/StrangeLoopGames/EcoIssues/issues/4123)

I presume this was between saving and loading a world, but I am not sure

**Comment by MusicianPoodle** [comment]
Hi, yes it was.  I think that this is the closed thread, but maybe you’ll receive this.

Sent from Mail for Windows 10

From: MarjieAVolk
Sent: 09 February 2018 02:48
To: StrangeLoopGames/EcoIssues
Cc: MusicianPoodle; Mention
Subject: [StrangeLoopGames/EcoIssues] Axe and Hammer turned into Pickaxes?(#4151)

@MusicianPoodle says that their axe and hammer turned into pickaxes in their inventory (see #4123)
I presume this was between saving and loading a world, but I am not sure
