### ISSUE TITLE
Crash server + client side problem

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4152]
When a server crash and admin restart it,
all steam client need to be restarted or they wil not be able to connect to server generating this error message on server
![image](https://user-images.githubusercontent.com/29807119/36007850-9af8eef6-0d44-11e8-853f-5331f0440a92.png)
After a server crash, If people restart their Steam client, they will not have problem to connect server and will not generate red line on server console

**Comment by metachronism** [comment]
auth issues, fixed in 7.2 (and some in earlier hotfixes)
