### ISSUE TITLE
USER ISSUE: Screen resolution resets after using Alt-Tab.

### ISSUE THREAD

**Issue by AlanAu** [StrangeLoopGames/EcoIssues#4153]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Launch game. Set screen resolution to non-desktop resolution. Alt-tab to desktop. Return to game.

**Expected behavior:**
It should keep your selected resolution.

**Actual behavior:**
Instead, it resets to desktop resolution.

**Comment by Nanders** [comment]
This has been fixed
