### ISSUE TITLE
Suggestion aka feedback - or need of in Law Creation

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4154]
the new county/district is really great new feature, where having issues thought creating laws in general for example, we would like it so people who live in a certain District would have the ability to harvest and people who do not live in that area can not..

it be nice to be able to have system recognize where people have homes in and or also to allow us to name specific users on the server.

for example

prevent harvest All
condition where is usere is "namehere" then allow

we also like setup system of government where for example one person is leader and then people under him who are named could create laws and then very one elese would only have write to vote.

so

prevent propose vote 
condition where is user "namedhere" then allow

this give us ability to fine tune our own government systems

it also be neat to make it so named individual of said county's where only ones who could come up with laws in those county's or people living in those county's where only ones who could vote for laws effecting those county's.

I guess it just be  nice to be able to name more people then just admin or none admin , or the you or someone elese.

named individuals be a big help.

**Comment by MarjieAVolk** [comment]
Thanks for the suggestions.  I was unsure whether to add the ability to name individuals in laws, because I was wary of bullying, especially in a school setting.  But I think you make a good case for it.

I had not thought of creating a condition for whether you 'live' somewhere.  That could be rather complex.  I will think about it more.

**Comment by midn8t** [comment]
just so for your thoughts reason we like open system and naming and resident to for where they live be nice because it would allow users to create possible new and old forms of government..

there anther law we wanted to try to impose but could not figure out if it was possible a tax on resource where the resource they collect is what is taxed. 

so if you go into realm sector what ever, and chop down tree and get collect 30 logs the game would automatically take an amount out of there inventory that they pick up and place it in someone elese, inventory storage.

we wanted to test diff forms of government like feudal systems - or dictator style state. along with republic style and then of course true democracy where there is on leaders  law system could way it setup allow for this, but it just would need the support of naming users so we can grant titles along with a lot people to be residents of there sectors - county realms what ever.

what the rule in law you vs someone else means ?
we where not sure how that would be used in a rule, my only thought was maybe as a sum total

like 

if harvest by someone elese > total 12 then deny meaning it takes into account what every one on server killed ?

i guess we where not sure what how the term someone would be used in law system ?

**Comment by MarjieAVolk** [comment]
Per your question about 'someone else' - I didn't necessarily have specific uses in mind when I added it, haha.  Maybe you could have a law that rewards someone if they have done more of the action than everyone else on the server combined :P  Possibly it is not very useful.  I am thinking I want to revisit the 'performed by' query soon, since it is pretty important and a lot of people miss it.

**Comment by midn8t** [comment]
a name system sometype would work great latter on, with the crime and punishment systtem if still doing that, that way we could do more then just ban someone off the server we could evict there access to things.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#281
