### ISSUE TITLE
Missing Seed Recipes?

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#4155]
Currently there are a few Seed recipes missing at the Farmers Table. Not sure if that is intentional. If it is why?
Missing:
Tomato Seed Recipe
Fireweed Seed Recipe
Rice Seeds

![image](https://user-images.githubusercontent.com/29911902/36010094-bb38f29c-0da3-11e8-81ea-2943fab77c73.png)

![image](https://user-images.githubusercontent.com/29911902/36010157-19720e16-0da4-11e8-865f-74a0f692b08f.png)

**Comment by craig-jong** [comment]
Rice are seeds.

As for the others, I'll be adding them asap.
