### ISSUE TITLE
USER ISSUE: tree growth

### ISSUE THREAD

**Issue by king9533** [StrangeLoopGames/EcoIssues#4156]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Start a tree farm by planting seeds

**Expected behavior:**
Trees grow over time to produce wood.

**Actual behavior:**
Trees dont grow until the server restarts.

**Comment by knexer** [comment]
I think that this is likely related to https://github.com/StrangeLoopGames/EcoIssues/issues/4382

**Comment by craig-jong** [comment]
This bug should be fixed in 7.3.2
