### ISSUE TITLE
when ever i click my cursor comes up and i cant do anything

### ISSUE THREAD

**Issue by myklenon** [StrangeLoopGames/EcoIssues#4158]
when ever i left click my cursor comes up and it wont let me click any thing. my tab does not work and i cant click anything in any menu. i tried reinstalling the game and it didnt fix anything

**Comment by myklenon** [comment]
i think this bug started when i changed resolution but i cant change my resolution again because when ever i click in the menus they just close

**Comment by MarjieAVolk** [comment]
Haven't heard this one before O.o  Could you send me your error log file?  It is located at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by Nanders** [comment]
Cannot Repro
