### ISSUE TITLE
Can't write in chat

### ISSUE THREAD

**Issue by Darek63** [StrangeLoopGames/EcoIssues#4160]
Hello, when i write in chat , the message doesn t appear in console, just create an espace , so other player can't see it 
Please help me , sorry for bad english , beacause baguette
thanks
![sss](https://user-images.githubusercontent.com/36289307/36012359-ea977874-0d5d-11e8-921b-b5202975b142.jpg)

**Comment by KevCa** [comment]
i have the same problem are you also not shown in the online player list ?

**Comment by Darek63** [comment]
Solved for me , my pseudo steam contains no accept caracter like | or <3 
Delete them but the server must be wipe to talk or you can change of server

I hope you understand me and help you

**Comment by KevCa** [comment]
thank you  i got the <3 aswell and removed it but i can't wipe the server the other players will kill me for that -.- 
i think can't talk for now on

**Comment by Darek63** [comment]
Try to modify your pseudo if it’s possible in files of the server ?

**Comment by KevCa** [comment]
i don't find it have you a clue where i can find it ?

**Comment by Darek63** [comment]
Nope , i don’t know sorry :/

**Comment by Darek63** [comment]
Serv use sql ?

**Comment by KevCa** [comment]
ok thanks

**Comment by KevCa** [comment]
i dont know

**Comment by MarjieAVolk** [comment]
Hey guys - it sounds like you are saying you had special characters in your steam name, which was not supported in our game.  Is that the case?  So characters '|' and '<' were allowed in your steam names but did not work in Eco?

**Comment by KevCa** [comment]
Yes that was the case my steam name was KevCa<3

**Comment by MarjieAVolk** [comment]
![image](https://user-images.githubusercontent.com/23460210/36623130-e90d5b5e-18b6-11e8-8ebf-cb74b216401a.png)
