### ISSUE TITLE
USER ISSUE: Repeat contracts not saving item type (for item deposits)

### ISSUE THREAD

**Issue by Cyber-Wolf** [StrangeLoopGames/EcoIssues#4161]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Setup a contract for the following:
1a. Deposit Item
1b. Repeat (at least 2 times)
1c. choose an item and location to deposit
2. Have a person complete the contract

Observe the next time you try to do the repeat contract it items to deposit is empty, preventing people from accepting the contract.

**Expected behavior:**
It should save the previous item(s) to deposit from the contract

**Actual behavior:**
It loses any items you previously had selected for the contract.

**Comment by LiaungYip** [comment]
Possibly related to #4129 .

**Comment by johnkslg** [comment]
Fixed! Thanks for the report.
