### ISSUE TITLE
USER ISSUE: Fell off of the world?

### ISSUE THREAD

**Issue by AlanAu** [StrangeLoopGames/EcoIssues#4162]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
During exploration, managed to fall off of a cliffside into the fog and just kept falling.

**Expected behavior:**
Eventually I would expect to have stopped, ideally returned to ground level.

**Actual behavior:**
I'm still falling.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4167
