### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by lalasand** [StrangeLoopGames/EcoIssues#4163]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
stand in storage area place wood

**Expected behavior:**
be able to leave storage area

**Actual behavior:**
stuck have to restart game

**Comment by MarjieAVolk** [comment]
It is possible to place things inside yourself and get stuck.  When this happens, you can use /unstuck to get out (enter it into chat).  We will keep trying to improve our character controller in order to minimize this.
