### ISSUE TITLE
USER ISSUE: Why

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4165]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Tried to pick up fallen log and kicked from server with error.

**Expected behavior:**
picked up log,

**Actual behavior:**
kicked me from server....First login in maybe 6+ hours.

**Comment by jaredalwyn** [comment]
First log in maybe 6 hours...tried to pick up cut log and kicked from server with error message.

**Comment by MarjieAVolk** [comment]
This sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3668 

Is this the error you were seeing?  Also did you see any logs floating?
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!
Object reference not set to an instance of an object.
Stack:
at TreeEntity.PickupLog(Player player, Guid logID)
at TreeEntity.OnActInteract(InteractionContext context)
at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)
```

**Comment by MarjieAVolk** [comment]
Closing as duplicate of #3668
