### ISSUE TITLE
USER ISSUE: free falling

### ISSUE THREAD

**Issue by LoBlanc** [StrangeLoopGames/EcoIssues#4167]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. Enter a river
2. Find a broken map place
3. enter the hole

**Expected behavior:**
die after some time falling

**Actual behavior:**
I keep falling to infinite

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
