### ISSUE TITLE
USER ISSUE: still no tree seeds

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4169]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
not getting any treeseeds at all

**Comment by Huntermeign** [comment]
Repeat af #4121

**Comment by MarjieAVolk** [comment]
Is this for all trees, or just oak and fir?

Closing as duplicate of #4121

**Comment by ownyHD** [comment]
yes u're right its just oak and fir. but now i cant plant the seeds since they instantly die while match=83%
