### ISSUE TITLE
Character stuck walking - no way to stop

### ISSUE THREAD

**Issue by thomthom** [StrangeLoopGames/EcoIssues#417]
I finally got around to download Eco - 0.4.1. I joined the official EU server. When I joined the game my character is stuck in eternal walk-mode. Any idea what causes that? I'm not able to figure out how to stop.

Windows 10, 64bit.

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/426/moving-mode-always-strafing-left

**Comment by thomthom** [comment]
I changed both primary and secondary keys for forward and back to some random keys - then back again. Next time I started the game it worked.

The thread did mention a Space Mouse - I do have a SpaceNavigator: http://www.3dconnexion.eu/products/spacemouse/spacenavigator.html

However - I didn't touch it at all. And it have not caused any issues with other games/apps.

**Comment by noblackthunder** [comment]
mhh could you try to disconnect that space mouse? when you get the issue again to see if that resolves it there and then ?

**Comment by thomthom** [comment]
Yea - I can do that. Thought now it's working - so we'll have to see if it reappear. Maybe it's a new-system kind of thing... :/

**Comment by thomthom** [comment]
I started the game again today - same thing.
This time I exited and disconnected the SpaceMouse and Wacom tablet -restarted the game - still the issue of constant forward movement. Got nothing else to disconnect now - only have mouse and keyboard.

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/764/movement-bug-player-keeps-walking-very-slowly

**Comment by thomthom** [comment]
I tried to build Eco myself - see if I could step through the code. But I'm having issues getting things properly set up in Unity. (http://ecoforum.strangeloopgames.com/topic/72/dev-tutorial-how-run-eco/2)

**Comment by thomthom** [comment]
An update with on this:

With the help of the good guys on the Slack channel I managed to get the Client built and running. (it was just my inexperience with Unity).

There I was able to set a breakpoint and see that `Input.GetAxis` was getting some bogus values even if I wasn't touching the mouse, keyboard or anything.

I am able to reproduce this in a plain Unity project. Using the Roll a Ball tutorial (https://unity3d.com/learn/tutorials/projects/roll-ball-tutorial/moving-player?playlist=17141) I see that the moment the game starts the ball starts moving the moment I hit play. And setting a breakpoint also shows bogus input values.

I'm at a loss what causes this. I unplugged everything sans my keyboard and mouse. I don't experience this in any other app or game I got - which makes it stranger. I guess it could be a Unity bug... but I thought I had been playing games based on Unity. (I need to check that.)

One thing I observer is that if I touch the input settings the bogus values will stop - for a while. But eventually it'll resume.

**Comment by noblackthunder** [comment]
ok .. well since its not a game bug just with eco and outside factors i mark this as wont fix since they cant do anything with it.

**Comment by noblackthunder** [comment]
and thanks for the help ! .. it helps allot knowing that even tutorial projects have the same issue and it seems to come from somewhere else

**Comment by thomthom** [comment]
Yea, kind of bummed it wasn't a game bug - because then it would have been easier to fix. Now I'm at a loss. This has been preventing me from playing the game. Guess Unity bug report is the next step.

**Comment by thomthom** [comment]
hmmm....

I had set up logging of input like this:
![image](https://cloud.githubusercontent.com/assets/192418/17039206/9bee5ec8-4f99-11e6-88c4-874de1f9091a.png)

I noticed that I would get bogus value when I set focus to the Unity window. Then then I set focus elsewhere - it stopped updating but the last value was correct (0, 0, 0).

I then came across this SO issue which described what I observed: http://stackoverflow.com/a/35964194/486990

> I know this is super old question but the same issue faced me with Unity 5.3.3f1, just navigate to Edit -> Project Settings -> Inputs
>
> You'll find 4 (Array Element) for both "Vertical" & "Horizontal" 2 each, delete the duplicate ones and you're good to go.

I did have duplicate of Horizontal and Vertical axes - not sure if this is by design or not, but removing the second set did stop the bogus input.

![image](https://cloud.githubusercontent.com/assets/192418/17039300/0fc9c774-4f9a-11e6-81fb-338863aeb5c5.png)

**Comment by thomthom** [comment]
hm... looks like the two types of Vertical and Horizontal are different types of input (mouse/keyboard and joystick). *sigh*

**Comment by thomthom** [comment]
Another observation: when I change the Joy Num of the Vertical and Horizontal axes that are Joystick Axis types - then I only get bogus values from Joystick 1 (or when getting from All Joysticks).

Setting to any other value and it seem to be working ok. So that should let me test the game in the meanwhile.

Sorry for the noise here - but I figured I'd document my observation in case anyone else with similar issue stumble across this. (I notice a couple of threads in the forum.)

**Comment by metachronism** [comment]
We can take a look at this, we can try jumbling up the inputs and maybe that will magically work

**Comment by metachronism** [comment]
http://answers.unity3d.com/questions/265694/phantom-joystick-input.html

some things to try

**Comment by thomthom** [comment]
When I iterate over Input.GetJoystickNames() I get one item in the returned array - but the string appear to be empty.

However - that link said:

> After a period of investigation, it was being caused by my 3DConnection Space Navigator 3D mouse. Unplugging the mouse isn't good enough, _you need to stop the application and services._ I suspect it is acting as a joystick when working with Unity for some reason :(

(Emphasise mine)

I do have a Space Mouse. But I had excluded it as the problem persisted while it was disconnected (and I had rebooted). But seeing what this guy says - it appear that it keeps doing something.

So - the plot thickens. At least I now have something concrete to go by. It's either a Unity bug or Space Mouse bug. I will contact them both and see if they can come to a resolution for this. I really need the Space Mouse and I can't keep uninstalling it every time I want to play a Unity based game.

Thanks for your assistance guys. I'll report back when I have more information.

**Comment by thomthom** [comment]
For reference, I filed an issue with the Unity bug tracker: https://fogbugz.unity3d.com/default.asp?816707_qiv8kiq4506hbg2a

I also filed an issue with 3dconnexion - referencing the public Unity issue tracker.

I'll report back when they respond.

**Comment by thomthom** [comment]
Feedback from Unity Support:

> Hey,
> 
> Thank you for submitting a bug to Unity.
> 
> The bug has been reproduced and our developers have put it on our roadmap for a partial system rewrite. We can't say when this will be ready for release, so we have resolved this bug as postponed.
> 
> If you have further questions, feel free to contact us.
> 
> Regards,
> Lukas
> QA Team

**Comment by noblackthunder** [comment]
thanks ! .. i close this issue now since its an external Unity issue the devs here cant do anything about it at this time. Thank you allot for all you help on this issue!
