### ISSUE TITLE
USER ISSUE: Some iron tools have no skin (like the iron hoe)

### ISSUE THREAD

**Issue by Thengen** [StrangeLoopGames/EcoIssues#4172]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Equip and use an iron hoe.

**Expected behavior:**
We should be able to see the tool skin.

**Actual behavior:**
We don't. The tool itself works fine though.

**Comment by Conchipedia** [comment]
Iron hammer has no in hand model #2478

**Comment by keegan-o** [comment]
This will be fixed in 7.0.6
