### ISSUE TITLE
[Critical] Kiln Still Requires Tier 2 Materials after 7.0.5

### ISSUE THREAD

**Issue by RoyHolzem** [StrangeLoopGames/EcoIssues#4173]
Hotfix 7.0.5:
> Fixed that the Kiln required a Tier 2 room despite being required for all Tier 2 room materials

Actual Display on 7.0.5:
![image](https://user-images.githubusercontent.com/17780714/36025148-51cfb9a0-0d92-11e8-837c-c5b514026c6d.png)

We still have the same problematic then before the patch.

Proposed Solutions:

- revert Mortar to T2
- change Kiln to need T1

Every other change would be too much time consuming (changing where Iron Ingots are made from etc)

Without Admin you cant progress.

**Comment by ecoemmeck** [comment]
That's odd as I placed a kiln today and it only required T1 materials. I'm playing on 7.0.5 as well

**Comment by RoyHolzem** [comment]
We tried this now, still the same issue.

Question: Is the file that changes this in the folder /configs/ ?

**Comment by ecoemmeck** [comment]
No it will be in the Mods/AutoGen/Worldobjects kiln.cs

**Comment by RoyHolzem** [comment]
So I have a Live Server and a Test Server
Both Have in Kiln.cs:
`[RequireRoomMaterialTier(1, 32)] `

The test server is correct, the live server is not?
Both were wiped Yesterday at 18h00. The only thing I reclyced were the files in config
like network.eco or users.eco (after fresch install I copied old config files over).

**Comment by MarjieAVolk** [comment]
It's possible that existing kilns didn't migrate correctly with the update.  If you pick up and replace your kiln, does it change?

**Comment by MarjieAVolk** [comment]
We are pretty baffled by this.  One thing you might try is deleting the Eco.Mods.dll file.  This is where the Kiln class gets compiled to, and it might not have recompiled it correctly.
