### ISSUE TITLE
Trouble with the connection: Connection failed

### ISSUE THREAD

**Issue by pallyLunna** [StrangeLoopGames/EcoIssues#4174]
**Schemе:** 
https://i.imgur.com/mylJlvS.png
**Description:** 
My PC and the server is on LAN and others clients not in LAN. 
So there is two situations: 
1) NAT disabled = i can join my server and others cant. 
2) Enable NAT = i can't join my server and others can. 

Port forwarding is done correctly. 
Firewalls rules are done correctly too.

**Comment by metachronism** [comment]
this should be resolved in one of the hotfixes.  lan broadcasted servers use the local IP instead of the external one
