### ISSUE TITLE
Concrete in Storage Chest

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4175]
i dunno if it suppose to now be in a chest or still the stockpile. however ive started making concrete and its going into my chest and not stockpile

**Comment by Conchipedia** [comment]
Concrete is Now Stored in chests and is an ingredient, Reinforced Concrete is the only type of Concrete Building Block (loads of types on Hammer)

**Comment by MarjieAVolk** [comment]
Yes this is intended now.  Concrete is no longer a block.
