### ISSUE TITLE
Campfire Speed

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#4176]
talked to Pam on discord about this a little.
Here is a GIF on Charred Tomato
[![Screenshot from Gyazo](https://gyazo.com/d2d07c978be78877770001a47e871927/raw)](https://gyazo.com/d2d07c978be78877770001a47e871927)

The TimeMult is set to 1.0 and everything else is running fine in seconds but anything in CampFire was going pretty fast, half speed basically.

**Comment by craig-jong** [comment]
No longer the case
