### ISSUE TITLE
Logging lvl 1 requires 50 points

### ISSUE THREAD

**Issue by Fr3aKeD** [StrangeLoopGames/EcoIssues#4177]
[![Screenshot from Gyazo](https://gyazo.com/5d2668c3ad1ff3c751bac14b2d3dd12e/raw)](https://gyazo.com/5d2668c3ad1ff3c751bac14b2d3dd12e)

another member of the server already have level 1 and i was thinking maybe cause of that it's effecting how much it costs for me to get level one?

**Comment by Zoratan** [comment]
https://eco.gamepedia.com/Getting_Started#Skills
With each specialty you learn, it will increase the cost of learning further specialties exponentially.

**Comment by MarjieAVolk** [comment]
Yes, thank you.  Each specialty you unlock makes the next specialty more expensive.  If you abandon a specialty you have learned, you will be refunded some points and the cost will go back down.
