### ISSUE TITLE
USER ISSUE: Research Not Progressing

### ISSUE THREAD

**Issue by TenspeedGV** [StrangeLoopGames/EcoIssues#4181]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
I placed my research table and placed all of the items I need to research both Farming and Wood Construction in the table.

**Expected behavior:**
It should have researched wood construction and farming

**Actual behavior:**
Instead the progress bar for the research is stuck at 0% progress and 100% efficiency. It doesn't move. I've cancelled the jobs and restarted them many times, I've tried to organize jobs differently (in different orders) and still no progress is made. The Carpenter's Table has the same issue.

**Comment by TenspeedGV** [comment]
I had this problem last night and I quit because I had to sleep. I tried again in the morning and I'm still having the problem, so it does persist through a restart.

**Comment by Huntermeign** [comment]
Make sure the status tab has all requirements met.

**Comment by TenspeedGV** [comment]
Thank you, I'm dumb and I missed that. Problem solved.
