### ISSUE TITLE
USER ISSUE: Had 19 skill points, jumped down to 2

### ISSUE THREAD

**Issue by LemonMoo** [StrangeLoopGames/EcoIssues#4182]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Not sure how it happened exactly.

**Expected behavior:**
Kept my 19 skill points

**Actual behavior:**
Bumped my skill points down to 2

**Comment by MarjieAVolk** [comment]
I believe '19' is the default text that appears on the button if it has not yet been initialized, so it seems likely that you actually had 2 the whole time but the button was not initialized properly.  @craig-jong recently fixed the button initialization I believe, so this might be hotfixed today?

**Comment by craig-jong** [comment]
Yea, this will be fixed today. It's only a visual bug.

**Comment by craig-jong** [comment]
I'm going to close this. If the issue persists after the next hotfix, please reopen.

**Comment by LemonMoo** [comment]
Thanks so much guys! :)
