### ISSUE TITLE
USER ISSUE: Disappearing stone

### ISSUE THREAD

**Issue by AvarusX** [StrangeLoopGames/EcoIssues#4183]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Shared stockpile on claimed land.
When attempting to input stone to the stock via right click, it is deleted.

**Expected behavior:**
the stone disappears from carrying hand is transferred to the stockpile

**Actual behavior:**
the stone disappears from carrying hand and does not appear in the stockpile

**Comment by MarjieAVolk** [comment]
Do you have a crafting table with an active project on it?  Or does someone else nearby?  These may be automatically taking resources from the stockpile as you put them in.

If this is not the case, let me know and I will investigate further
