### ISSUE TITLE
Observation: Grass growing onto tilled soil

### ISSUE THREAD

**Issue by ivanhlb** [StrangeLoopGames/EcoIssues#4185]
Was trying to do some farming, left some empty tilled soil near grass.

Came back to see tilled soil having grass growing on it.
![image](https://user-images.githubusercontent.com/21984761/36038972-191fe8c2-0dfc-11e8-9e6e-1f917076e36f.png)

**Comment by Huntermeign** [comment]
![image](https://user-images.githubusercontent.com/4082137/36039729-5ff06c42-0d91-11e8-9a7b-437eeb7a3dbd.png)


sorry, I had to.

**Comment by MarjieAVolk** [comment]
I believe this is intended behavior now.  Tilled soil and planted crops can be overtaken by other plants.  But checking with @knexer to confirm

**Comment by LiaungYip** [comment]
The other aspect of this is that:

Once grass grows on a tilled soil tile, the grass can only be removed by:

* digging up the dirt with a shovel, 
* replacing the dirt, and
* tilling it again with a hoe.

**Comment by MarjieAVolk** [comment]
Ah yeah, that is pretty annoying.  Plants need to be more easily removable.  It's a problem with dead plants too

**Comment by LiaungYip** [comment]
Alternately, allow the Hoe to plow plants back into the ground, returning their nutrients to the soil.

**Comment by knexer** [comment]
I like @LiaungYip 's suggestion.  It'd be nice if a hoe used on a plant, or on the block beneath the plant, returned 100% of the resources to the environment, deleted the plant, and tilled the soil.

Probably that should happen only for grass and shrubs, not trees, though.

**Comment by craig-jong** [comment]
You can rehoe land now which will remove plants.
