### ISSUE TITLE
Observation: More than 1 Grass entity per tile

### ISSUE THREAD

**Issue by ivanhlb** [StrangeLoopGames/EcoIssues#4186]
![first](https://user-images.githubusercontent.com/21984761/36041513-bdc8ce5a-0e03-11e8-8b0a-6243d32d0468.png)
![second](https://user-images.githubusercontent.com/21984761/36041515-be012a02-0e03-11e8-9e3c-689aa24dc832.png)
Using the scythe to highlight the grass entity, I come to realize that there seemed to be more than 1 grass entity per tile.

**Comment by craig-jong** [comment]
This was an issue with plants that was resolved a while ago. Or at least it should have been - if you notice this behavior in a more recent build, please reopen the issue.
