### ISSUE TITLE
USER ISSUE:  just bought the game and every time i try to mine i get this error

### ISSUE THREAD

**Issue by ghost** [StrangeLoopGames/EcoIssues#4187]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Could not load type 'System.Numerics.Quaternion' from assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.


Stack:
   at Eco.Gameplay.Objects.RubbleObject.TrySpawnFromBlock(Type blockType, Vector3 position)
   at Eco.Mods.TechTree.PickaxeItem.OnActLeft(InteractionContext context)
   at Eco.Gameplay.Interactions.InteractionExtensions.<>c__DisplayClass0_1`1.<ExecuteUntilSuccess>b__1()
   at Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   at Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by LordHaze** [comment]
you've got till tomorrow, or i will ask for a refund, didnt just pay 30 US for a game with errors that throw me out of the game right off the bat after just purchasing

**Comment by Huntermeign** [comment]
Then why did you buy a game in Beta?

**Comment by knexer** [comment]
Looks like an issue with the server installation.  Is this a local server or a remote one? In either case, can you join and play on a different server?

**Comment by LordHaze** [comment]
Huntermeign- yea its in beta but the game has been out for awhile, hell before steam even picked it up, i expected errors(small ones as this is still new) but not an error right off the bat just after purchase that does NOT let me continue without it being fixed, so if you have anymore smart ass comments nows the time to let your ego fly.

Knexer-its local, and iv tried creating new ones but the same problem still occurs

**Comment by knexer** [comment]
Can you please try to connect to a public multiplayer server, just to see if mining works for you on there?  It should.  If so, @metachronism can help with the server installation, it sounds like some of the dependencies weren't installed correctly.

**Comment by Huntermeign** [comment]
Let me fix what you said.

"Huntermeign- yea its in beta..." Okay there. Thats all thats needed. It's not a matter of being a smart ass. It's beta. You are the one who was an ass acting like SLG Owed you anything,

**Comment by Huntermeign** [comment]
Oh, and the internet never forgets. Deleted comments don't always stay deleted

![image](https://user-images.githubusercontent.com/4082137/36114559-51ccdc26-0ffe-11e8-8dec-409342ab5443.png)

**Comment by metachronism** [comment]
This is likely because of out of date .net version, we've updated the install version to reflect this
