### ISSUE TITLE
Farming table renders as a chest

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#419]

**Comment by Breitschwert** [comment]
This is the same for the Saw Mill. Might be placeholder art.

**Comment by craig-jong** [comment]
It is indeed placeholder art for the farmer's table.. The farmer's table may be replaced in a future build so no art was created for it.

The sawmill, however, should have a mesh.

**Comment by noblackthunder** [comment]
more placeholders ..all of them should be removable at least=P
