### ISSUE TITLE
USER ISSUE: players kicked second time reporting!

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4191]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
players get randomly kicked out of the game after a few minutes ..

second time reporting this!

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Does this happen on ever server, or just a specific one?  Do players get any error messages when they are kicked?

**Comment by rsgodkilla** [comment]
when my brother and sister joins they get kicked this has happened on mutli servers when weve made them they are close to quitting and id like it fixed we had no problems on the game before it came on steam

**Comment by rsgodkilla** [comment]
there is no message its like if game crashed and sent them to main menu but it does`nt affect me juste any 1 that is joining a server that isnt admin

**Comment by MarjieAVolk** [comment]
So your brother and sister can connect and start playing in the world, but then later they are kicked out?

**Comment by rsgodkilla** [comment]
with in 10 mins of joining yes we have the same issue when we join eachothers servers through steam to

**Comment by rainfarmer** [comment]
what are your usernames? ill check your accounts for errors

**Comment by rsgodkilla** [comment]
rsgodkilla mr3g ladystorm

**Comment by MarjieAVolk** [comment]
I presume you are all playing on the same network?

**Comment by rsgodkilla** [comment]
no they connect to me through steam we live in different houses

**Comment by rsgodkilla** [comment]
and vice versa

**Comment by MarjieAVolk** [comment]
It does sound like some kind of auth problem.  We are just about to release a hotfix that changes how the auth checks work a bit, so it's possible that the hotfix will fix your issue, but I am not sure

**Comment by rsgodkilla** [comment]
i hope so its kind of annoying having to do everything in intervals

**Comment by MarjieAVolk** [comment]
Hotfix is live - want to give it a shot?

**Comment by rsgodkilla** [comment]
hello we just tested it and they still get kicked :(((((

**Comment by MarjieAVolk** [comment]
Okay, so what error messages do they see when they are kicked out?

**Comment by rsgodkilla** [comment]
there isnt a error message it just takes them back to the main menu screen

**Comment by Snufx** [comment]
Hello,
Same problem here, every players connected on my server are disconected at the same time every 10 mins.
This is not occuring on LAN clients.
The server is download from steam tools and launch from steam. I did try differents config of my router but seem default config work better.
Hope this help
