### ISSUE TITLE
USER ISSUE: Overlap on Tooltip on Store from Minimap

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4195]
**Version:** 0.7.0.5 beta

When hovering over a Store on the minimap the Item and price overlap making it a bit difficult to see, only a problem for things with Long names
![snap1610](https://user-images.githubusercontent.com/29383891/36051654-cd3c25b0-0de2-11e8-908b-3fea10b78744.png)

**Comment by beastyn** [comment]
Seems to be ok with 8.2
![bandicam 2019-06-26 20-36-44-472](https://user-images.githubusercontent.com/27898520/60194109-2bbc1f00-9852-11e9-9504-fdab0782e2cb.jpg)
