### ISSUE TITLE
Memory usage of the server is too high

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#42]
bug 1 - memory usage is 2X after world regenerate.  If you close and load that same world, memory usage is halved??  Something not letting itself be GC'd?

broader issue: Memory use is way to high in general

**Comment by metrotyranno** [comment]
Experienced 4X memory increase after world destruction event, but normal again after a restart.

**Comment by metachronism** [comment]
this should be much better after recent checkin, calling it good for now
