### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Deutscher999** [StrangeLoopGames/EcoIssues#4202]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Got kicked from a Server and can't reconnect.

**Expected behavior:**

**Actual behavior:**
Connection Failed

Caught exception: Could not finding matching RPC signature for method: Authorize.

**Comment by MarjieAVolk** [comment]
This message is due to a version mismatch between you and the server.  Check what version the server is on and make sure your version matches.  In a future release we will have a better error message for this
