### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by RoyHolzem** [StrangeLoopGames/EcoIssues#4203]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
Click on Continue

**Expected behavior:**
Login and play

**Actual behavior:**
The following error message popped up:
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.
```

**Comment by MarjieAVolk** [comment]
This sounds like a version mismatch problem. Try exiting the game and letting steam download all updates. Or contact your server admin to find what version they are on.

Another thing that can cause this is if your server has mods; in which case you can ask the server admin delete the Eco.Mods.dll file from the server installation.
