### ISSUE TITLE
USER ISSUE: Cannot login to server

### ISSUE THREAD

**Issue by beauchene** [StrangeLoopGames/EcoIssues#4204]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
1. On the home page click on continue for the (US) All welcome server

**Expected behavior:**
Server should load

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.
```

**Comment by MarjieAVolk** [comment]
This sounds like a version mismatch problem.  We had a number of reports of this because of releasing hotfixes rapidly.  Try exiting the game and letting steam download all updates.  Or contact your server admin to find what version they are on.

**Comment by MarjieAVolk** [comment]
Another thing that can cause this is if your server has mods; in which case you can ask the server admin delete the Eco.Mods.dll file from the server installation.
