### ISSUE TITLE
USER ISSUE: District Redfineing 

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4206]
**Version:** 0.7.0.6 beta

**Steps to Reproduce:**
made alot of Districts, we accidently gave two Districts same name.

now we can not pass law to rename them..

we also can not seem to redraw them or add new Districts onto the map.

we have no other laws in effect at all.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Fixed in 7.2
