### ISSUE TITLE
USER ISSUE: Logged In Elsewhere

### ISSUE THREAD

**Issue by ExpensiveKoala** [StrangeLoopGames/EcoIssues#4208]
**Version:** 0.7.0.6 beta

**Steps to Reproduce:**
1. Setup a server and join with a pc on a different account.

**Expected behavior:**
Join server on LAN with friends

**Actual behavior:**
Player currently in server gets kicked for "Logged in Elsewhere"

**Comment by MarjieAVolk** [comment]
This issue has actually already been fixed!  We rolled out a fix very shortly after the 7.0.6 patch.  Let me know if you still have the issue on 7.0.7
