### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Hizzolt** [StrangeLoopGames/EcoIssues#4209]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.
```

**Comment by MarjieAVolk** [comment]
This sounds like a version mismatch between you and the server.  Try exiting the game and letting steam download all updates.  Or contact your server admin to find out what version you should be on

**Comment by MarjieAVolk** [comment]
Another thing that can cause this is if your server has mods; in which case you can ask the server admin delete the Eco.Mods.dll file from the server installation.
