### ISSUE TITLE
USER ISSUE: Connection Failed 

### ISSUE THREAD

**Issue by FrostyPerra** [StrangeLoopGames/EcoIssues#4212]
**Version:** 0.7.0.6 beta

**Steps to Reproduce:**
Trying to start my own game with friends. Can only join online servers.

**Expected behavior:**
Start a game

**Actual behavior:**
It starts loading but the a window appear ''Connection Failed''
The following error message popped up:
```
Connection Failed
```

**Comment by metachronism** [comment]
when you say it starts loading, do you get any messages other than "Connecting..." before it fails?
You can also check the Server\Dump folder for any logs, there might be an issue with your specific user on that server.

**Comment by FrostyPerra** [comment]
I have a bunch of dumps, all with the same error it seems but i'm not to good at these kinda things, I can attach one of the files to you.


________________________________
Från: Eric Anderson <notifications@github.com>
Skickat: den 10 februari 2018 03:12
Till: StrangeLoopGames/EcoIssues
Kopia: FrostyPerra; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Connection Failed (#4212)


when you say it starts loading, do you get any messages other than "Connecting..." before it fails?
You can also check the Server\Dump folder for any logs, there might be an issue with your specific user on that server.

**Comment by MarjieAVolk** [comment]
We thought that we fixed this in 7.0.6, but this sounds similar to a NAT problem we saw earlier.  Can you connect to the server by going to Join and adding localhost:3001 as a server?

**Comment by FrostyPerra** [comment]
This was the day before 7.0.6, I didn't know about this patch until way after the update, I have not had a problem since this patch so far, thanks.

________________________________
Från: MarjieAVolk <notifications@github.com>
Skickat: den 12 februari 2018 22:30
Till: StrangeLoopGames/EcoIssues
Kopia: FrostyPerra; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Connection Failed (#4212)


We thought that we fixed this in 7.0.6, but this sounds similar to a NAT problem we saw earlier. Can you connect to the server by going to Join and adding localhost:3001 as a server?

**Comment by MarjieAVolk** [comment]
Great news.  Closing this in that case.
