### ISSUE TITLE
Plastic can't pickup once placed in world

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#4214]
We have placed a block of plastic in the world, we can pick up it but can't do anything with it... serveral seconds later it's placed on the same place.

Relogin and server-restart does nothing...

If needed, I can upload a picture later.

**Comment by Bazzi89** [comment]
Any solution?

**Comment by MarjieAVolk** [comment]
Oh I didn't see that you said you picked it up and then it disappeared after a few seconds.  You don't see any error messages pop up in chat when you do this, do you?

**Comment by Bazzi89** [comment]
Nope, no errors displayed (server&client side)

**Comment by craig-jong** [comment]
Plastic shouldn't even be a block. So this is def a pretty major bug.
