### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Deygus** [StrangeLoopGames/EcoIssues#4215]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**
lost connection to server.
tried to reconnect
got error 

**Expected behavior:**
Continued and connected me to server

**Actual behavior:**
Caught Exception: Could not finding match RPC signature for method: Authorize.

**Comment by Deygus** [comment]
<size=150%>Connection Failed</size>

Caught exception: Could not finding matching RPC signature for method: Authorize.

**Comment by MarjieAVolk** [comment]
It sounds like you may have a version mismatch between your client and the server.  If you exit the game and wait for steam to update it to the latest version, does that fix it?

**Comment by Deygus** [comment]
Let me try that and see what happens, what i originally did was update then i had to roll back cus the original server i was on wasnt updated yet. I'll try again.
On 2/9/2018 9:01:27 PM, MarjieAVolk <notifications@github.com> wrote:
It sounds like you may have a version mismatch between your client and the server. If you exit the game and wait for steam to update it to the latest version, does that fix it?

**Comment by Deygus** [comment]
Yeah, its working now. I uninstalled and reinstalled. I think the files were mismatched when I rolled back to connect again.
On 2/9/2018 9:01:27 PM, MarjieAVolk <notifications@github.com> wrote:
It sounds like you may have a version mismatch between your client and the server. If you exit the game and wait for steam to update it to the latest version, does that fix it?

**Comment by MarjieAVolk** [comment]
Great :)
