### ISSUE TITLE
USER ISSUE: cant connect to my server

### ISSUE THREAD

**Issue by lkkl7778** [StrangeLoopGames/EcoIssues#4219]
**Version:** 0.7.0.7 beta

**Steps to Reproduce:**
i try to connect to my server and the game freezes and it crashes it is only on my server that i rented through pingperfect. i can connect to other servers just fine it is only mine that crashes my game and the server works fine for my friends

**Expected behavior:**
connect to my server

**Actual behavior:**
game crashes

**Comment by MarjieAVolk** [comment]
So your client crashes right?  Not your server.  Do you have anything in C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt ?

**Comment by MarjieAVolk** [comment]
Closing due to no response
