### ISSUE TITLE
Suggestion - Can you add in Fir tree seeds and Oak tree seeds?

### ISSUE THREAD

**Issue by Khazul01** [StrangeLoopGames/EcoIssues#4223]
Can you add in Fir tree seeds and Oak tree seeds?

**Comment by LiaungYip** [comment]
Duplicate of #4121.

**Comment by MarjieAVolk** [comment]
Thank you.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4121.  You can track the issue progress there.
