### ISSUE TITLE
USER ISSUE: Water wheel won't place properly

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#4225]
**Version:** 0.7.0.7 beta

**Steps to Reproduce:**
Try to place a water wheel in water

**Expected behavior:**
should place and work in flowing water only

**Actual behavior:**
will not place in water only above the water and still produces power

**Comment by Spaceferret42** [comment]
was working fine post steam

**Comment by craig-jong** [comment]
This should be fixed now based on some occupancy changes - we'll look at it requiring water as well.
