### ISSUE TITLE
Abnormal Entering World... Times

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4229]
Ever since 7.0.5 I have experienced abnormal loading times for the "Entering World..." phase of the server login. This time was somewhat shortened on average during 7.0.7 but has resumed it's abnormality in 7.0.8.

**Comment by Blanclour** [comment]
Currently I am spending 30% of my elapsed game time on the "Entering World..." screen.

**Comment by MRROOKIExx** [comment]
Same, takes forever to ''Connect''...

**Comment by metachronism** [comment]
should be largely resolved as of 7.2+
