### ISSUE TITLE
Extremely low FPS in Server Browser (when certain servers are displayed?)

### ISSUE THREAD

**Issue by interfect** [StrangeLoopGames/EcoIssues#4230]
Game Version: 7.0.5
OS: Windows 7
GPU: AMD RX480
Driver: Radeon Software Version 17.7.2

When opening the server browser, the game runs fine for a few seconds. Then, at some point, sometimes (but not always), either when a certain server or a certain number of servers have loaded, performance slows to a crawl and I get about 2 FPS. This makes the server browser very difficult to use, because of the slow response time.

I think there's something wrong with the rendering of the text effects for a certain server; I have observed it running reasonably fast with many servers in the list, sometimes.

I don't know how you want to solve this (maybe by pagenating the list?). I will have to see if it recurs with 7.0.6 when I get a chance.

**Comment by MarjieAVolk** [comment]
In 7.4, the server browser list has a cap on the number of entries, with a 'Load More' button.  It also has much better filtering, sorting, and searching functionality, which should prevent players from needing to scroll through the complete list manually.  I have found this to improve performance quite a bit.
