### ISSUE TITLE
USER ISSUE: Cant join server ive played on

### ISSUE THREAD

**Issue by Cheezehead31** [StrangeLoopGames/EcoIssues#4232]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. clicked continue-to play on a server ive been playing on

**Expected behavior:**
Loaded the server

**Actual behavior:**
doesnt load and get error saying Failed connection incompatible version

**Comment by MarjieAVolk** [comment]
If it says you have an incompatible version, you probably have an incompatible version.  Check what version you are on (you can see this in the escape menu), and check what version the server is on.
