### ISSUE TITLE
USER ISSUE: Wooden Carts Bug

### ISSUE THREAD

**Issue by LordCereal** [StrangeLoopGames/EcoIssues#4236]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Park the Card.
2. Fill it with Items
3. Walk a couple of Steps away, than look at it and sometimes it disapears or it flys away, and you have to search it.

**Expected behavior:**
It should just stay where it was.

**Actual behavior:**
Instead it flys away or disapears.

**Comment by rsgodkilla** [comment]
i have same problem if u open the deed and click on the cart it shows u where it is but it is very annoying watching it fly away!

**Comment by Bazzi89** [comment]
sometimes at relog its glitched from the mineshaft to the overworld...

**Comment by Camouflage91** [comment]
Same problem here

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4105.  You can continue tracking the issue there.
