### ISSUE TITLE
USER ISSUE: On taking wood

### ISSUE THREAD

**Issue by kingwithou** [StrangeLoopGames/EcoIssues#4237]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Trying to take log

**Expected behavior:**
get it in my hand

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
This sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/3668.  Was this a log you had just chopped down, or one that you found on the ground?  Did you also see floating logs?

**Comment by MarjieAVolk** [comment]
Going to close this as a duplicate of #3668 until I learn differently :)
