### ISSUE TITLE
USER ISSUE: Open doors with shovel

### ISSUE THREAD

**Issue by Bazzi89** [StrangeLoopGames/EcoIssues#4239]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. use shovel to open a door

**Expected behavior:**
open the door	

**Actual behavior:**
not open the door

**Comment by Dr-Hardware** [comment]
ROFL, note its only with en EMPTY shovel

**Comment by Bazzi89** [comment]
check ;D

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868
