### ISSUE TITLE
Game Crash while searching for server by IP

### ISSUE THREAD

**Issue by Gorowynn** [StrangeLoopGames/EcoIssues#4241]
**Version:** 7.0.8 beta

**Steps to reproduce:**
- search for server by IP

**Expected behavior:**
Server gets shown on Favorites

**Actual behavior:**
Game crashes a soon as i click on Add. Somestimes without any error message, sometimes with this one:

> KERNELBASE.dll caused an Access Violation (0xc0000005)
>   in module KERNELBASE.dll at 0033:61aa3fb8. 

and crashfile
 https://pastebin.com/XyekLKLk

**Comment by fillion07** [comment]
Same here couple of seconds after I put the game resolution to 1920 x 1080.
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1718418/error.log)
