### ISSUE TITLE
Special character name spams chat and laws

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#4242]
Someone joined the server with a blank name or a name with some kind of special character and that person couldn't change his/her name so now the name spams in chat and laws. Every time someone types for example " ... " there's a bunch of player icons between the dots.

Before you couldn't use special characters but now with steam you can join with for example Å Ä Ö and that really messes things up. Maybe it's time to make all the special characters visable so for example ÅÄÖ doesn't translate into something else.

![65d1d11d0d7e6db567562b672547e25a](https://user-images.githubusercontent.com/36330679/36062115-087aef52-0e66-11e8-8cd3-e51ec785a2e1.png)

**Comment by MarjieAVolk** [comment]
:O lol oh man

**Comment by MarjieAVolk** [comment]
Okay, I've been looking into this on version 7.3.  So far it seems that special characters such as Ä in names work fine now - we've added support for a lot of them.  I tried logging in as a person just named " " and I did see some weird icons, similar to the screenshot although not nearly as bad.

I also tried logging in as "(?<=a)" - that is a lookbehind regex, wanted to see if the name would be treated as a regex.  But that seems not to be the case.  That name did not work well though, it had https://github.com/StrangeLoopGames/EcoIssues/issues/4160

**Comment by Nanders** [comment]
Its probably the autonaming/tooltip creator thing

somebody called themselves " " or something.

**Comment by MarjieAVolk** [comment]
Okay, decreasing priority on this, since I think it is much more of a special case than we initially thought.

**Comment by beastyn** [comment]
Can't make name with space only now.
Have separate issue for special characters #14132
