### ISSUE TITLE
Suggestion: Add WoodPulpItem as fuel to campfire/stone brazier

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4243]
pretty straight forward. most server already do this change for their people.

i have included the changed files as examples
[woodpulpfuel.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1713373/woodpulpfuel.zip)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#280
