### ISSUE TITLE
Suggestion: Repair needs to be decreased for iron and steel

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4247]
its drastically more cost effective to just create new ones then repair. consider re balancing to make it closer? or just flat decrease repair of iron and steel tools?

**Comment by ecoemmeck** [comment]
Yes I agree the repair costs should be scaled with the efficiency because as storm said it costs more to repair than it does to repair the tool than it costs to make new tools when you have level 5 efficiency

**Comment by LiaungYip** [comment]
This feature was hinted at  in a [blog post](https://www.strangeloopgames.com/eco-alpha-6-released/) (emphasis added):

> ## Tools Upgrade
>
> Tool now have durability, and can be repaired with the right skills in the repair station.
> 
> * Many items will degrade in effectiveness as they are used. Items that are more broken become more difficult to use, consuming your calories faster.
> 
> * Players can use repair stations to improve item durability. _Resourceful players may specialize in tool repair and buy and sell items to repair._
> 
> * Not all tools are created equal. Progressing through the game gives you access to better technology to craft superior tools. Better tools degrade slower and use less calories.

**Comment by th3t0mb0mb** [comment]
Iron tools last so long that I think the proposed solution of specialization is appropriate.

**Comment by Senlarus** [comment]
So my chests are full of broken tools now with no way to get rid of them. It is more cost effective to create new tools instead of repairing them once you get your efficiency up. Couldn't we make the cost of repairing the tool tied to the efficiency skill level so it would reduce the cost of repairing?
