### ISSUE TITLE
USER ISSUE: Missing Wood Cart

### ISSUE THREAD

**Issue by Adrac** [StrangeLoopGames/EcoIssues#4249]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
create a Wood Cart - place it anywhere in the world

**Expected behavior:**
to stay where it is

**Actual behavior:**
pings into the air and dissapears

**Comment by Blanclour** [comment]
I can confirm this, it is very annoying and makes people think twice before using one to begin with.

**Comment by SeanAtr0n** [comment]
haven't seen this lately... don't think it should be possible anymore
