### ISSUE TITLE
Using 7.05 problem skill points disappering 

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4250]
Started game had 19 skill points did nothing for about 30 seconds and POOF i had 0 skill points they just went away never to return CANT PLAY THIS WAY

**Comment by MarjieAVolk** [comment]
This sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/4182, which was a display bug (that is, you didn't actually have 19 points, it was displaying the wrong thing for a while), and also should be fixed in the current release.

**Comment by MarjieAVolk** [comment]
If you continue having this problem, you can just let me know on this bug and we will re-examine it.
