### ISSUE TITLE
Tutorial suggestion

### ISSUE THREAD

**Issue by Spacedestructor** [StrangeLoopGames/EcoIssues#4252]
A few days earlier after the Lirik stream that was posted on the Discord server because of streaming Eco, i got the idea that because much steam users don't like tutorials that it would maybe a good idea to be able to skip a tutorial without need to do it and without getting the tool, to say that you want to do the tutorial but want to get the stuff after it removed, getting the stuff without doo the tutorial or that guys that prefer to just try it out so that
1. there are just the needed tools and a farmer for example doesn´t have a pickaxe and situations like that.
2. everyone can play the game how they want and dont be forced to do the tutorial if the dont like tutorials.

**Comment by MarjieAVolk** [comment]
You can skip tutorials by showing your cursor, hovering over the tutorial item, and clicking the 'x'.  There is a checkbox in the confirm dialog to skip all tutorials.  This will also give you the items.

**Comment by Spacedestructor** [comment]
i know bit i meant it like be able to skip it without get the tool if the player don´t need it. sorry if i wasn´t clear enough

**Comment by MarjieAVolk** [comment]
Ah that's interesting.  Well, I think we are going to work on a way to get rid of items soon, which would also address that issue.

**Comment by Spacedestructor** [comment]
ok, thanks.
