### ISSUE TITLE
USER ISSUE: Visual bug with tailings

### ISSUE THREAD

**Issue by GibsonSWE** [StrangeLoopGames/EcoIssues#4253]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. place tailings in a 2x2 square.
2. 2 of the tailings blocks went invisible.
3. The next blocks placed adjacent to those ivisible blocks becoms "half invisible".

![20180210163337_1](https://user-images.githubusercontent.com/33501602/36063665-3219ec9a-0e80-11e8-80a1-29c646ee4c2e.jpg)

**Comment by MarjieAVolk** [comment]
I am not sure if this is all builders or not

**Comment by keegan-o** [comment]
It is not the builders, it's chunk building. Programmers are aware of it and will be trying to stop it from happening more and more as time goes on.
