### ISSUE TITLE
Ramps cannot be "edited" after placement

### ISSUE THREAD

**Issue by Pingperfect** [StrangeLoopGames/EcoIssues#426]
After placing a dirt ramp as far as I can work out you cannot do anything with it afterwards, shovel/hammer/pickaxe have no effect and it does not have a green outline around it when you look at it.

Need to be a way of moving them if you place it incorrectly or at least a way to destroy it.

**Comment by Breitschwert** [comment]
You need to use the hammer on it. To use it correctly, stand near the center of the ramp ontop of it, facing the upwards slope direction, then start hammering slightly over the highest slope point of the ramp. It should remove it after a hit or two (depends on the delay by the server).

Hitting it directly does not work and is counter-intuitive, but the hitbox for removal is something that needs to be looked at. For now, it does work though.

**Comment by Wazations** [comment]
If the above does not work I have found that if you use the hammer on a block near the ramp then look at the ramp it will remove the ramp. Be warned the Hammer will continue to activate even if you are not clicking it, to stop it just click as normal.

Hope that helps

**Comment by metachronism** [comment]
hammer can remove ramps now, and highlight correctly
