### ISSUE TITLE
USER ISSUE: Currency exchanges dont work

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4262]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
build exchange.. place and set up to exchange stormoffires credits to MAB bucks 1 to 1

**Expected behavior:**
swap 1 credit for 1 coin

**Actual behavior:**
says currency exchange is not exchanging that credit

**Comment by stormoffires** [comment]
so more to this... 7.1.2...

they work however if people have access to a deed that shares your currency you can not exchange on it. (so Rob has access to storms land and storm is trying to exchange his credits for currency, but rob can not do that)

also side now.. when player A is exchanging player Bs credits for currency, player B has "infinite" and can exchange as much as they want.

**Comment by Matikari** [comment]
![20180216194916_1](https://user-images.githubusercontent.com/9065496/36337402-d6993f56-1352-11e8-8a16-fe380feba3aa.jpg)

We are having issues too, this is the error we get when we try to exchange to Grimkor his credits for the created Jabroni currency.

**Comment by johnkslg** [comment]
- If you have access to the deed, you can't make trades on it, because you could set whatever exchange rate you want.  Disable their access and then they should be able to trade. 
- That error means the player has set a holding limit on how much currency they want.  
- Infinite credit is why there are holding limits

**Comment by johnkslg** [comment]
Testing it, I have a fixes I'll get in.

**Comment by johnkslg** [comment]
Fixed currency exchanges working despite bad room requirements.
Fixed currency exchanges failing if you try to use default currencies.
Fixed currency exchanges letting non-authed users mess with the lists.
