### ISSUE TITLE
Lag, Disconnects, High in game pings.

### ISSUE THREAD

**Issue by ChrisMayhew** [StrangeLoopGames/EcoIssues#4263]
Our server has become almost unplayable since the release of 0.7.0.8, We get constant in game high pings (2000ms+) but if you ping the server IP through terminal its a low ping so that makes no sense.

Inactivity kick is a joke, it kicks people who are playing and then sometimes they can't get back onto the server for a while.

It helps when the server software is rebooted for a bit but then it all comes back.

The load on the server is barely ever more than 50% and it has 32gb of RAM so I don't believe it's a server side issue.

I wish I had a log or an error file to show how bad it is at the moment.

**Comment by Blanclour** [comment]
I can confirm this, same bug as I reported a while back. Very detrimental to player experience.

**Comment by ChrisMayhew** [comment]
Absolutely, It's putting me off playing on my own server and I can't imagine how annoying it is for the people currently playing on it. 

0.7.0.7 seemed to be more stable.

**Comment by Quicksilv3r710** [comment]
Same issue here. Network and hardware has lots of headroom, but for some reason we keep getting lag spikes/high pings. The game is almost unplayable when it gets around 20 people or so logged in simultaneously. I can test my internet connection during spikes and the ping is fine, it seems like something is going on in the game itself.

**Comment by ChrisMayhew** [comment]
Can I ask, are you guys running windows or using Mono on Linux? @Blanclour @Quicksilv3r710

**Comment by Quicksilv3r710** [comment]
Windows 10

**Comment by Blanclour** [comment]
Client is windows 10, I'm not sure what the server uses.

**Comment by ChrisMayhew** [comment]
@Blanclour @Quicksilv3r710 Thanks, so its not just a Mono thing then!

**Comment by Blanclour** [comment]
I have noticed the game is relatively stable with 2 people online, but the instant that a third or more people log on, the server immediately starts to lag and kick people.

**Comment by th3t0mb0mb** [comment]
Can confirm this issue.

**Comment by DiploBlock** [comment]
Same, Has not been addressed by any update from 7.0.5 onward to 7.0.8 
#4218 #4213

**Comment by Blanclour** [comment]
Might have a correlation with queuing projects at various workbenches. Several instances were noted on my server where the lag started immediately after queuing a project.

**Comment by ChrisMayhew** [comment]
We decided to try the staging version on my server this morning and so far it's going well, We have 10+ people online with no reported lag yet. We have had the odd inactivity kick though.

**Comment by ecoemmeck** [comment]
this seems like its still a think with players ping jumping all over the play once 10+ players are online the players ping jumps around from under 30ms - 3000ms

**Comment by ChrisMayhew** [comment]
I've not been on since I put the live version of 7.1.0 on but we had the staging one on and it was fine with more than 10 people.

**Comment by metachronism** [comment]
should be fixed in 7.2
