### ISSUE TITLE
USER ISSUE: Workbench gone....

### ISSUE THREAD

**Issue by wotlight** [StrangeLoopGames/EcoIssues#4268]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Hit workbench with Stone hammer to pick it up
2. Workbench doesn't show in inventory
3. Use admin command /give workbench
4. Workbench still not in inventory

**Expected behavior:**
Workbench shouldn't disappear forever

**Actual behavior:**
Workbench disappears forever

**Comment by wotlight** [comment]
Solved by restarting the game

**Comment by MarjieAVolk** [comment]
When you restarted the game, did you have one workbench or two?

If you have client error logs (on windows these are at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt), this might be helpful for us to figure out the problem and prevent it in the future.
