### ISSUE TITLE
Black startup. 

### ISSUE THREAD

**Issue by MiLLHA** [StrangeLoopGames/EcoIssues#4271]
I can't seem to get into the game. As I start the game, a black window pops up and I see the ECO curser. But no sound og menu pops up. On a nvidia laptop GPU.

**Comment by MiLLHA** [comment]
Solution was to turn off the scaling option in either the nvidia control panel or in the Intel control panel. Works fine now. Seems to be a Unity thing.

**Comment by MarjieAVolk** [comment]
Thanks for sharing your solution.  I will share this with others if they see this issue
