### ISSUE TITLE
UnityPlayer.dll caused an Access Violation (0xc0000005)

### ISSUE THREAD

**Issue by DrPeppiX** [StrangeLoopGames/EcoIssues#4272]
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1713771/crash.zip)

**Comment by alecpura** [comment]
Saw one of these in a ticket from mihael.abramovic@vici.ch. No real details (yet), but here's the relevant portion of the error.log:

Eco [version: Unity 2017.3.0f3 (a9f86dcd79df)]

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:216e1ae8.

Error occurred at 2018-03-07_214746.
G:\Games\SteamLibrary\steamapps\common\Eco\Eco.exe, run by Miha.
8% memory in use.
65447 MB physical memory [59792 MB free].
75175 MB paging file [67602 MB free].
134217728 MB user address space [134213274 MB free].
Read from location ffffffff caused an access violation.

Context:
RDI:    0x08321ed0  RSI: 0x5334fcf0  RAX:   0x022c0820
RBX:    0xc546ea60  RCX: 0xe20be060  RDX:   0x00448f18
RIP:    0x216e1ae8  RBP: 0x00000000  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x404ff580  SegSs: 0x0000002b
R8:    0xd4e47000  R9: 0xe08be060  R10:   0xfffffb34
R11:    0x007ffff8  R12: 0xc546ea60  R13:   0x08320070
R14:    0x00000000  R15: 0x00005a00

**Comment by rainfarmer** [comment]
+1

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:28fe87a6.

Error occurred at 2018-02-28_162616.
C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco.exe, run by lordt.
46% memory in use.
16316 MB physical memory [8811 MB free].
32700 MB paging file [16839 MB free].
134217728 MB user address space [134208636 MB free].
Read from location ffffffff caused an access violation.

Module 1
C:\WINDOWS\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_185422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
C:\Program Files (x86)\Steam\tier0_s64.dll
Image Base: 0x50160000  Image Size: 0x00372000
File Size:  359712      File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 3
C:\Program Files (x86)\Steam\vstdlib_s64.dll
Image Base: 0x504e0000  Image Size: 0x0006b000
File Size:  348960      File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 4
C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x50550000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-02-12_202630
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1

Module 5
C:\Program Files (x86)\Steam\steamclient64.dll
Image Base: 0x77200000  Image Size: 0x00df6000
File Size:  14398016    File Time:  2017-12-15_195928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

**Comment by rainfarmer** [comment]
+1 

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:98b61781.

Error occurred at 2018-02-24_221304.
E:\SteamOnSSD\steamapps\common\Eco\Eco.exe, run by egond.
94% memory in use.
32679 MB physical memory [1782 MB free].
36775 MB paging file [0 MB free].
134217728 MB user address space [134213627 MB free].
Write to location 0000010e caused an access violation.

**Comment by rainfarmer** [comment]
+1 


UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:1e9287f5.

Error occurred at 2018-03-01_142740.
C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco.exe, run by lordt.
42% memory in use.
16316 MB physical memory [9375 MB free].
32700 MB paging file [18822 MB free].
134217728 MB user address space [134211019 MB free].
Write to location 00000018 caused an access violation.

**Comment by rainfarmer** [comment]
+1

Eco [version: Unity 2017.3.0f3 (a9f86dcd79df)]

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:e62ad738.

Error occurred at 2018-02-18_122940.
D:\SteamLibrary\steamapps\common\Eco\Eco.exe, run by isbol.
20% memory in use.
16327 MB physical memory [12941 MB free].
18759 MB paging file [14758 MB free].
134217728 MB user address space [134216662 MB free].
Read from location ffffffe8 caused an access violation.

**Comment by MarjieAVolk** [comment]
This is apparently a bug in Unity.  Some people have been able to resolve it by updating their drivers.  Googling the error might produce some other suggestions.
