### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by trigun1588** [StrangeLoopGames/EcoIssues#4273]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
When trying to connect threw steam,both friend and myself have the game threw steam, pops up with connection Failed you have been banned from this server. We where both playing just fine last night not sure if it was the 7.0.8 update so we tryed both 7.0.7 and 7.0.6 but the results where the same. Some times when i try to join him it says on his game that was logged in eleswhere. Not sure if that helps.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Are you sure that you have not actually been banned from the server?  Is it your own server?

**Comment by trigun1588** [comment]
I wasn't banned it was just me and a friend playing on his game, a day later he was also band from his on game, not a server. After both of us getting the "ban" he download a server and we where able to play on that.

**Comment by MarjieAVolk** [comment]
Okay.  So I think what's going on is that the empty string is getting added to the banned list, and that's making everybody get banned.  I will work on a fix for this.

In the mean time, if I am right, you should be able to solve this.  What you will need to do is find the Eco Server tool and run your saved game from that, as a standalone server.  When you do this, a server window will pop up that has lots of config for the server.  If you go to the User tab > Config tab > Blacklist you should be able to open up and edit the blacklist.  Just delete everything in the blacklist.  Let me know if that solves your problem!  (Or you can just wait for a fix)

**Comment by trigun1588** [comment]
ok ill let my friend know, i'm loving this game its been very fun i cant wait for any new content. (maybe a dumpster for the excavator =) lol) thanks for looking into this.

**Comment by MarjieAVolk** [comment]
I have added a fix for this, which will go out in the release today.  Let me know if you have the problem again!
