### ISSUE TITLE
USER ISSUE: Can't get fish out of traps when swimming below surface. 

### ISSUE THREAD

**Issue by solarsootysmudge** [StrangeLoopGames/EcoIssues#4275]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Place a fish trap below the surface.
When fish caught swim to trap
Open up trap screen using E

**Expected behavior:**
Swimmer should not move when trap inventory is open even if underwater. Movement should stop and allow trap inventory to be used.

**Actual behavior:**
Player automatically moves to surface too fast away from trap. Trap closed and no fish gained.

**Comment by MarjieAVolk** [comment]
Possibly related to https://github.com/StrangeLoopGames/EcoIssues/issues/4588

**Comment by craig-jong** [comment]
Super old, but this could be fixed by returning swimming to NOT shoot you upwards until you run out of calories.

**Comment by OtherMike** [comment]
This is also part of a wider issue, that opening any window underwater (soil sampler, map, backpack, any inventory, even just hitting TAB for the arrow cursor), acts as though you have released CTRL, and shoots you to the surface (and this behavior is still in 0.7.4.0)

**Comment by SeanAtr0n** [comment]
will be fixed 7.4.5
