### ISSUE TITLE
USER ISSUE: I CAN'T MAKE A WORLD!

### ISSUE THREAD

**Issue by emstah** [StrangeLoopGames/EcoIssues#4277]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
I simply click "New" and when i try to join i get tabbed out of the game and when i get back in it says "connection failed" please fix this

**Expected behavior:**
it should have loaded in, something it didn't do...

**Actual behavior:**
connection failed

**Comment by MarjieAVolk** [comment]
There are a couple of ongoing issues that could be causing this.

One thing you can try is, if you weren't before, check the box to generate a new world.  If that doesn't work for you, you can also try deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO.  Let me know if either one fixes the problem

**Comment by MarjieAVolk** [comment]
Oh, I also notice you were on 7.0.8 when you filed this.  In that version, there were some NAT problems for local games, which have since been fixed.  So possibly the issue will just go away for you on the most recent version of the game.

**Comment by MarjieAVolk** [comment]
Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about.  I can continue helping you debug whenever you have time.
