### ISSUE TITLE
USER ISSUE: Repairing Iron Tools

### ISSUE THREAD

**Issue by LordLump** [StrangeLoopGames/EcoIssues#4279]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1: Use iron tool
2: Durability lost
3:put in repair bench
4: Repair Cost = 8 Iron Ingots (even with metal working efficency)

**Expected behavior:**
Repaircost = 1 Iron ingot

**Actual behavior:**
Repaircost = 8 Iron Ingot 
(creating a new costs 2 iron ingots)

**Comment by ecoemmeck** [comment]
#4247

**Comment by MarjieAVolk** [comment]
Thanks, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4247 . You can track the issue progress there.
