### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by snow-frog** [StrangeLoopGames/EcoIssues#4282]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
try to connect to friend's game on same lan

**Expected behavior:**
connected

**Actual behavior:**
The following error message popped up:
```Connection Failed
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you connect to other servers?  Can you see servers listed in the 'Join' server list?

Since it looks like you were on 7.0.8, you may have been having NAT problems.  We recently released a fix for this, so it's possible if you both update the game that you may be able to connect now.

**Comment by MarjieAVolk** [comment]
Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about.  I can continue helping you debug whenever you have time.
