### ISSUE TITLE
USER ISSUE: Items not getting crafted, resources vanish

### ISSUE THREAD

**Issue by TheKvist** [StrangeLoopGames/EcoIssues#4284]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Craft an item on any crafting station, the resource cost is drawn from your storage/inventory
2. Wait for the crafting to finish

**Expected behavior:**
Should have added the crafted amount of items to your storage or have it ready for removal

**Actual behavior:**
Resources vanish, with not outputting any items at all. Happened with boards, recipes and various other items

**Comment by MarjieAVolk** [comment]
Is there a 'Collect' button on the crafting project, in the station's ui?  Sounds like maybe you have a linked stockpile, but not a linked chest (since boards cannot be put into a stockpile).

**Comment by TheKvist** [comment]
I checked, but I have a chest and a stockpile linked to the tables, but I think I might have an idea what happened. I had another project requiring boards running on another table and I think i just mistook the dependent table drawing the boards automatically for the resources disappearing.

I will keep an eye on this but I think this was just my bad. I'm sorry for that.

**Comment by MarjieAVolk** [comment]
Okay glad to hear it.  No problem, let me know if you have an issue again :)
