### ISSUE TITLE
Single player worlds with "allow friends to join" have maxslots set to 1

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#4285]
I think I may have caused this - will look into it.

**Comment by MarjieAVolk** [comment]
Is the setting backwards?

**Comment by MarjieAVolk** [comment]
Is this caused by https://github.com/StrangeLoopGames/EcoIssues/issues/3768 actually?

**Comment by craig-jong** [comment]
I checked this and it no longer happens, but it might be caused by settings overriding.
