### ISSUE TITLE
Face Remover Issues with Concave Voxel-Edge Builders

### ISSUE THREAD

**Issue by zenwidjet** [StrangeLoopGames/EcoIssues#4286]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Place the "pillar" Brick block next to dirt

**Expected behavior:**
expect to see the dirt next to the open space inthe pillar texture

**Actual behavior:**
the texture is broken and you can see through the terrain.

**Comment by zenwidjet** [comment]
![broken textures](https://user-images.githubusercontent.com/35677805/36068618-7f2ee2ae-0e96-11e8-9cf7-90f432c32bda.png)

**Comment by keegan-o** [comment]
Alright, I'm assigning you on this one @metachronism because I've run into more and more instances where I would have to really make lots of meshes gross and otherwise not match their neighbors in order to avoid this problem... I know it's not a simple fix but getting the face remover to either be more intelligent or just getting it to not do these particular cases even if it's at the cost of extra faces elsewhere is a decently high priority.

**Comment by MarjieAVolk** [comment]
I was given the impression earlier that you can fix things like this @keegan-o by like unchecking 'solid' for the brick block in this case, but that is hearsay.

**Comment by elfl0rd** [comment]
glass
![20180405233649_1](https://user-images.githubusercontent.com/4980243/38390591-6b6076de-392a-11e8-9969-ddf8ba8ab579.jpg)

metall
![20180405233704_1](https://user-images.githubusercontent.com/4980243/38390594-6dcd8218-392a-11e8-82a5-86da989d1d1b.jpg)

**Comment by elfl0rd** [comment]
Lumber
![20180701030648_1](https://user-images.githubusercontent.com/4980243/42129948-816d37d2-7cdc-11e8-9f0f-677f17fc2b92.jpg)

**Comment by metachronism** [comment]
This is a very trick issue to fix.

**Comment by metachronism** [comment]
new thoughts on how to fix:

determine sets of triangles contributing to each edge face polygon, instead of one list of all triangles
when removing faces, only remove them if all the vertices of the to-be-removed face lie within triangles in the same set

this *should* work.

**Comment by Solly-W** [comment]
This bug makes it very easy to find the ecko statue by just placing brick floor next to some dirt then looking through the gap. All space underground becomes visible

**Comment by SlayksWood** [comment]
merged with #11814
