### ISSUE TITLE
USER ISSUE: Store bug with quanity

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4287]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. I steup store to buy items max 50
2. friend sold me 60 of that item
3. friend got store credit
4. I never got the items.
5. items are not in his inventory nore are they any any of my storage chest
i have 5 storage chest setup to store i checked them all.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
I have not been able to repro this.  Did your friend sell all 60 in one interaction?  Sorry that it's a little late for this now, but do you have any server logs with error messages or anything?  Did your friend get kicked when they attempted this trade?

**Comment by MarjieAVolk** [comment]
Reducing priority since it doesn't seem to be very common

**Comment by midn8t** [comment]
I believe he sold all 60 at one time.  - now i am not sure if this is a lag issue or what.

maybe i set it on my side and it took while for server and his client update ?

**Comment by MarjieAVolk** [comment]
Aha, that might be related.  We also have some problems with stores not updating until you log out and back in (https://github.com/StrangeLoopGames/EcoIssues/issues/4347), which might be related in that case.

Still not sure how the items could just disappear though O.o

**Comment by johnkslg** [comment]
This was likely fixed when #4347 was fixed, no repro anymore.
