### ISSUE TITLE
USER ISSUE: Text gets smashed in contract creation

### ISSUE THREAD

**Issue by Gilgatex** [StrangeLoopGames/EcoIssues#4289]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Try to create a new contract
Select add/remove blocks
Select property

**Expected behavior:**
Continue with contract add

**Actual behavior:**
All the text gets smooshed to the left, making it difficult to complete filling it out.

**Comment by LiaungYip** [comment]
Duplicate of #3535.

**Comment by MarjieAVolk** [comment]
Yes thank you.  Closing as duplicate of #3535
