### ISSUE TITLE
USER ISSUE: Crafting tables breack down

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4290]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. make store in room
2. turn off the server
3. turn on the server
4. table or store no longer think it is in a room.
to fix hit a wall with hammer and put block back

**Expected behavior:**

**Actual behavior:**

**Comment by GophTheGreat** [comment]
Reopen if it occurs again.
