### ISSUE TITLE
Suggestion: New contract clause - require minimum skill level

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#4291]
It would be useful if the Principal could require the contractor to have a certain skill before accepting a Contract.

Example: Require the Contractor to have Forest Forager 5 in order to accept the Contract "Harvest Tomato Farm".

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#277
