### ISSUE TITLE
USER ISSUE: fertilizer does nothing

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4293]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
i put 20 fertilizer into a field but the minerals arent changing. field is almost empty

**Expected behavior:**

**Actual behavior:**

**Comment by LiaungYip** [comment]
Duplicate of #4125.

**Comment by ownyHD** [comment]
fixed with 7.1.0
