### ISSUE TITLE
USER ISSUE: Kicked for inactivity

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4295]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Join server.

**Expected behavior:**
Stay logged in.

**Actual behavior:**
Even with high activity, will recieve a kicked for inactivity error.

**Comment by MarjieAVolk** [comment]
Often players are incorrectly kicked for inactivity if the server is experiencing severe lag.  Since 7.0.8 we have release some performance improvements, which may help you with this problem.  We are continuing to work on improving the game's performance.
