### ISSUE TITLE
USER ISSUE: House detection problem

### ISSUE THREAD

**Issue by Minifets** [StrangeLoopGames/EcoIssues#4297]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
On our server, the problem with the algorithm for recognizing the house. If you leave the house window 1x1 or 2x1, then it ceases to be a house. Also, if you open the door, the algorithm stops seeing the house.

**Expected behavior:**

**Actual behavior:**

**Comment by Minifets** [comment]
Before open the door: https://imgur.com/BD5uurb
After: https://imgur.com/ZVBHYkI

**Comment by pamduncan** [comment]
windows can only be 1X1 opening (as long as the room.eco conf file allows a 1X1 opening to be a window)  if it does not allow an opening to be a window then you have to put a real window in it or close the hole so it will be a room

I bet the server is configures to need a real window

**Comment by ecoemmeck** [comment]
I'm pretty sure you can have windows 2x1 I've never had a problem with 2x1 windows it's pretty much just a door opening turned sideways

**Comment by Minifets** [comment]
Problem in "EmptyBlocksCountAsWindows": false property. 
The open door is recognized as a hole in the wall.

**Comment by MarjieAVolk** [comment]
Man if we allow disabling that, then we need to fix doors

**Comment by craig-jong** [comment]
Door are fixed, but also that wasn't intentionally disabled.
