### ISSUE TITLE
Client - Saw Mill nonfunctional

### ISSUE THREAD

**Issue by Breitschwert** [StrangeLoopGames/EcoIssues#430]
Version: Alpha 04.1
Type: Client
OS: Windows 7 64bit Home Premium
Detailed Description of Issue:
The Saw Mill does not work. It is neither accessible for its functions, nor can it be removed after placement. It has no inventory or GUI. Therefor the player is unable to progress past the area that requires lumber production.

Reproducible? How difficult is it to reproduce?:
It always occurs, both with the normally researched/built version as well as the spawned via give-command one. The issue is identical.

Steps to reproduce bug/issue:
Inside the game, spawn a Saw Mill and place it. After that, you will find it inaccessible to your interaction control option as well as being unable to remove it with any tool.

**Comment by craig-jong** [comment]
The sawmill is currently a module. 

I'll leave this open because the removal bug is not fixed and because modules should be more obvious.

**Comment by Breitschwert** [comment]
Sorry to ask, but what is a module in game terms and where is it explained how they are used? I found nothing on the wiki or official page with the alpha releases so far. Are they attachments to existing workstations?

**Comment by craig-jong** [comment]
Bugs in bugs! Yea, they most certainly need a better explanation.

I'll look into the sawmill -> carpentry thing.
