### ISSUE TITLE
USER ISSUE: Cant Connect to Server

### ISSUE THREAD

**Issue by Rambo99** [StrangeLoopGames/EcoIssues#4301]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Run game
2. Select Join
3. Select Server
4. Waiting to Connect
5. Error - Connect failed

**Expected behavior:**
Server protect on password.

**Actual behavior:**
Connection Failed.
Maibe error in the password protection on server.

**Comment by Rambo99** [comment]
After update 0.7.0.8 all return to normal state. Thanks.

**Comment by MarjieAVolk** [comment]
Okay glad to hear it :)
