### ISSUE TITLE
USER ISSUE: Can't start a new game [FIXED]

### ISSUE THREAD

**Issue by Eminenti** [StrangeLoopGames/EcoIssues#4305]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Clicking New
2. Clicking Start

Happens every time.

**Expected behavior:**
The game starting

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by Eminenti** [comment]
So I found a workaround. Started ecoserver.exe manually and waited for it to finish starting up the server. then I opened eco.exe, and started a new game there and it worked. After that I closed both eco.exe and ecoserver.exe, then started only eco.exe again. Now I can make new worlds without crashing. :)

**Comment by RackhamLeNoir** [comment]
I have the same issue, here is the dump:

https://pastebin.com/jpLQFKTk

Eminenti workaround is working for me as well.

**Comment by MarjieAVolk** [comment]
The stack says "The format of the input string is incorrect."
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Eco.Core.Serialization.EcoSerializer.Initialize()

Sounds like our default world is bad?  Were you guys generating a new world?  Or using the default world?

**Comment by RackhamLeNoir** [comment]
I generated a new world. 
As far as I understood, the server froze before the world was actually generated. Then when I started the server manually as suggested by Eminenti, the world was generated.

**Comment by Eminenti** [comment]
I tried both the default world and ticking the "Generate new world". They all failed.

The worlds were somewhat made though, because could find them again in the "Load" screen.

When trying to load them, the game would crash at the same place though, at the "Starting GameplayStatsPlugin... ". That's the same place the game would crash when trying to make a new world, both "default" and "Generate new world".

**Comment by MarjieAVolk** [comment]
Okay, update on this -

"To solve the first error you need to go on the Eco storage then open the Game.eco like a ZIP.
Then open the file named "version".
You should see something like "2.2" you need to replace it by "2,2"." -- @quequiere

Looks like this is a locale issue.

**Comment by RackhamLeNoir** [comment]
Thanks for the update. 
Speaking of locale issue, accents in the chat are messy. UTF-8 or at least ISO8859-1 should be supported.

**Comment by MarjieAVolk** [comment]
Yes, we are working on support for that.  Should be available I believe two updates from now.

**Comment by Eminenti** [comment]
Worked like a charm. Thanks! :)

**Comment by metachronism** [comment]
fixed this for now, no longer using system locale
