### ISSUE TITLE
CreosoteBush layer problem

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4306]
In the past we had a problem with the Wheat layer.
I think it's exactly the same with CreosoteBush layer:

![image](https://user-images.githubusercontent.com/29807119/36072040-ff280666-0f18-11e8-80aa-2babd4201d7c.png)
![image](https://user-images.githubusercontent.com/29807119/36072155-fb0fade8-0f1a-11e8-9efe-7ecb3fa6d19e.png)

If i am right can you fix it?

**Comment by Arend90** [comment]
![image](https://user-images.githubusercontent.com/31536813/36072234-7daa1d46-0f1c-11e8-8df6-9362b30a1f91.png)
have the same on GreenLeaf

**Comment by Amphysbaenas** [comment]
yup it's the same problem with Bullrush

**Comment by craig-jong** [comment]
We've patched in a fix for 0'd out populations on world generation.
