### ISSUE TITLE
USER ISSUE: Hewn Logs disappearing when stockpile is full

### ISSUE THREAD

**Issue by imthe666st** [StrangeLoopGames/EcoIssues#4309]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Build a stockpile and fill it with materials except for the last slot
2. Get 20 Hewn Logs in your hand and add it to the stockpile 
The stockpile should be full now and you have 5 Hewn Logs in your hand
3. Fill your hand with 20 Hewn Logs again
4. Right-click on the stockpile
5. You have 5 Hewn Logs in your hand and 15 disappeared.

**Expected behavior:**
the stockpile should have blocked my action and I should still have 20 Hewn Logs in my hand

**Actual behavior:**
Hewn Logs are nowhere to be found.

**Comment by imthe666st** [comment]
Addition: In my stockpile are 4 stacks of 15 Hewn Logs and the stockpile is full. When I right click with a stack of 7 hewn logs in my hand the first stack of Hewn Logs is overwritten with 7.

**Comment by imthe666st** [comment]
And it seems like it doesn't need to be a full stack. The stockpile has to be full and there has to be at least 1 stack of hewn logs. Right-clicking with Hewn Logs in my hand overwrites the first slot.

**Comment by MarjieAVolk** [comment]
Thanks for the detailed repro steps.  Will investigate.

**Comment by imthe666st** [comment]
Thank you for the reply. I tried to replicate my issue on the 0.7.10 patch and it seems like it was already fixed in that update. It could also be that it was a server-side problem as our server is setup on linux via mono.
