### ISSUE TITLE
USER ISSUE: skill points bar

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4311]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
it gets to the end of the bar and just stays there 
if i reboot it takes the bar half way back down

**Expected behavior:**
roll over bck to the start

**Actual behavior:**
sticks at the end giving me no skill point

**Comment by Zntrack** [comment]
Version 0.7.1

Had this issue as well on my server. Out of 8 players, 3 had this bug. I did not experience this bug personally.  There seems to be some kind of desync going on for specific players. One player was using steam and another was using the direct client.

Related Issues: #4233 and #4250
Solution : I restarted the server and it gave the players their retroactively owed skill points.

**Comment by MarjieAVolk** [comment]
This sounds like it might be related to #4182, which is fixed in the current release. Since I see this bug was filed on an older version, are you still having this issue?

**Comment by Zntrack** [comment]
Yes this bug is happening to two individuals on my server on the most up to date - current build.

**Comment by MarjieAVolk** [comment]
Hey guys, we just had someone else report that this was related to using the /repopulate command.  Did you guys use this on your server?  https://github.com/StrangeLoopGames/EcoIssues/issues/4519

**Comment by craig-jong** [comment]
I think I've noticed this bug as well. I'm going to take a look at it but even if the bar gets stuck it shouldn't stop you from getting skillpoints as the bar is only visual.

**Comment by MarjieAVolk** [comment]
@craig-jong if it is related to /repopulate, I think what's going on is that /repopulate sets the world time to 0, and then nothing ticks because they are waiting for the world time to be a specific time.

**Comment by craig-jong** [comment]
this is fixed on the latest staging
