### ISSUE TITLE
USER ISSUE: DISCONNECT WITH ERROR

### ISSUE THREAD

**Issue by pallyLunna** [StrangeLoopGames/EcoIssues#4313]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Ссылка на объект не указывает на экземпляр объекта.

Stack:
   в Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   в Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   в Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   в Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   в Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   в Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   в Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   в Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Caught exception invoking RPC PlayerInteract on Player!

Ссылка на объект не указывает на экземпляр объекта.


Stack:
   в Eco.Core.Controller.ControllerManager.PackageMethodResult(BSONObject bson, INetClient boundClient, IController controller, Tuple`2 method)
   в Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   в Eco.Core.Controller.ControllerManager.PackageValue(BSONObject bson, INetClient boundClient, Object value, Int32 nameID)
   в Eco.Core.Controller.ControllerManager.PackageController(IController controller, INetClient boundClient)
   в Eco.Gameplay.Objects.WorldObject.GetBSON(InteractionContext context)
   в Eco.Gameplay.Objects.WorldObject.OnActInteract(InteractionContext context)
   в Eco.Gameplay.Interactions.InteractionExtensions.ExecuteUntilSuccess(IEnumerable`1 results)
   в Eco.Gameplay.Players.Player.PlayerInteract(InteractionInfo info)

```

**Comment by MarjieAVolk** [comment]
Do you know what you were doing when this happened?  It will be hard to address without more details.

**Comment by MarjieAVolk** [comment]
Closing as duplciate of https://github.com/StrangeLoopGames/EcoIssues/issues/4222

I realized I was being a little silly, as I can see in the trace you were opening a crafting station window.  I have some leads on this now.
