### ISSUE TITLE
Washboard - No Texture when placed

### ISSUE THREAD

**Issue by MillanAireson** [StrangeLoopGames/EcoIssues#4318]
The washboard has no texture when placed in the word.

[http://steamcommunity.com/sharedfiles/filedetails/?id=1298351041](url)

**Comment by Blanclour** [comment]
I can confirm this.

**Comment by NytoO** [comment]
Bonjour

![image](https://user-images.githubusercontent.com/36629711/36786645-764692f0-1c87-11e8-974d-e8df4b40be09.png)

**Comment by MarjieAVolk** [comment]
Didn't realize it had no art.

**Comment by MarjieAVolk** [comment]
Well idk @keegan-o there's the fact that it doesn't have art, and there's also the fact that our placeholder seems to be a bit weird :P
