### ISSUE TITLE
Server crashed 7.0.8 

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4322]
![2018-02-11](https://user-images.githubusercontent.com/20627148/36074275-11669054-0efb-11e8-920a-01d1146c6776.png)

no dumpfile created

**Comment by MarjieAVolk** [comment]
This is most likely due to a problem on someone's slg account.  If you know who is generating these messages, send their username over to us.  We are working on outputting better error messages for these cases
