### ISSUE TITLE
Suggestion - Add recipe hewn logs to lumber

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4323]
as title states this would help folks out a lot in low wood/no wood areas in advancing their buildings. Can be a reduced rate due to the log already being hewn.

**Comment by MarjieAVolk** [comment]
So you want to be able to cannibalize your hewn log houses after upgrading them?  Haha

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#275
