### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by kristianstage** [StrangeLoopGames/EcoIssues#4324]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
cannot place research table
inside a room which is 25m2 or larger. 	

**Expected behavior:**
should be able to place research table

**Actual behavior:**
no matter where i try to place even i build a new house double size it say Cant place here, blocked

**Comment by MarjieAVolk** [comment]
The research table is deeper than most other tables - 2 blocks deep instead of 1.  Are you trying to place it too close to the wall?

@keegan-o Assigning to you because I think the research table's occupancy and positioning is odd, would be nice if it were only 1 deep.  But not a huge deal.

**Comment by kristianstage** [comment]
no. i even build a new large house double or triple size of the other and tried to place it in the middle of the room without anything else in there. was not possible :(

**Comment by MarjieAVolk** [comment]
Oh alright.  Hmmm.  Another possibility is that the ceiling is too low.  Can you place the research table outside?

If you can't do that either, then maybe the occupancy on the table is messed up.

**Comment by kristianstage** [comment]
i can place it outside.. ok maybe it could the ceiling.. ill try that out later.. Thank you
