### ISSUE TITLE
USER ISSUE: Map not showing players

### ISSUE THREAD

**Issue by Annoyed1** [StrangeLoopGames/EcoIssues#4327]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Not sure what caused it, was just using it	

**Expected behavior:**
Show players on the map

**Actual behavior:**
There are no players on the map

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3770 . You can track the issue progress there.
