### ISSUE TITLE
USER ISSUE: camas bulb don't disappear

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4328]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Sometimes when I digging camas bulb, I received goods but plant doesn't disappear. Still be on the ground.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
This sounds like an issue I filed earlier.  After you dug up the camas, were you able to target the one that was still on the ground?

**Comment by Arkadia3** [comment]
Hi. No, you can not interact with them. But for now everything is fine, bug didn't happen again

**Comment by Arkadia3** [comment]
but now I have the same issues with branches (when tree fall; wood pulp). Some of them don't disappear after harvesting
