### ISSUE TITLE
Way-point Accumulation

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4331]
Waypoints do not seem to reliably disappear, nor is there an option to delete them. They do not show up on the map, and when they do they are not clickable or delete-able. Here are some screenshots.
![20180211095640_1](https://user-images.githubusercontent.com/2582909/36075283-55e19690-0f12-11e8-8e4b-69427941fccb.jpg)
![20180211095822_1](https://user-images.githubusercontent.com/2582909/36075285-5e617e20-0f12-11e8-83be-f004f55fc1b9.jpg)

**Comment by ecoemmeck** [comment]
Right click on the market that in the world that say how many meters away and click remove

**Comment by Argetlam-Elda** [comment]
tab to move your mouse freely, then click the drop-down arrow below the waypoint. You can delete them there.

**Comment by Blanclour** [comment]
I have tried clicking the drop down arrow, but no menu or selection pops up.

**Comment by Blanclour** [comment]
Thank you, this worked. I did not realize that the arrows in the actual view were clickable opposed to the ones on the minimap.

**Comment by Conchipedia** [comment]
Should be in Tutorial that Waypoints Have to be clicked in Real World View by Pressing TAB to bring up the Pointer not on Minmap as this is not very clear how to do

**Comment by Dr-Hardware** [comment]
Regularly hidden by users having the map large and central on the screen during this phase of the tutorial.   Instructions need to be clearer

**Comment by MarjieAVolk** [comment]
I agree that this is confusing.  We hope to revisit the controls for this at some point.  Closing this bug as your immediate problem has been resolved.
