### ISSUE TITLE
USER ISSUE: rejoining

### ISSUE THREAD

**Issue by TimLevens** [StrangeLoopGames/EcoIssues#4333]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
rejoin server i was just in

**Expected behavior:**
join server

**Actual behavior:**
The following error message popped up:
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC Authorize on Client!

De objectverwijzing is niet op een exemplaar van een object ingesteld.

Stack:
   bij Eco.Plugins.Networking.Clients.Client.Authorize(LoginSession sessionInfo, String version)

<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC Authorize on Client!

De objectverwijzing is niet op een exemplaar van een object ingesteld.

Stack:
   bij Eco.Plugins.Networking.Clients.Client.Authorize(LoginSession sessionInfo, String version)

```

**Comment by MarjieAVolk** [comment]
This looks like a version mismatch problem.  Check the version number of the server (Did you just reconnect because they just updated to a new version?).  In a future version, we will have more clear error messages
