### ISSUE TITLE
USER ISSUE: NOTHING WORKS

### ISSUE THREAD

**Issue by MRROOKIExx** [StrangeLoopGames/EcoIssues#4335]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
NOTHING WORKS. NOT JOINING A SERVER. NOT CONNECTING TO MY OWN FUCKING SINGLEPLAYER GAME. WHY DOES NOTHING WORK??? CANT EVEN GET A REFUND BECAUSE OF PLAYTIME. CREATING MY OWN SERVER DOESNT WORK EITHER BECAUSE IT JUST SAYS EVERYTHING IS OFFLINE

**Expected behavior:**
IT SHOULD HAVE WORKED.

**Actual behavior:**
IT DOES NOT FUCKING WORK.

**Comment by MarjieAVolk** [comment]
Hey there - Sorry you have had such a hard time.  We recently rolled out a fix for connecting to single player worlds.  It's possible that that issue has already been fixed for you.

To debug your other problems, I will need more detailed information about what you are seeing.  You can't connect to any servers?  Do you get error messages when you try to connect?

**Comment by MarjieAVolk** [comment]
Closing due to no response
