### ISSUE TITLE
USER ISSUE: bug dans un mur

### ISSUE THREAD

**Issue by marc1772** [StrangeLoopGames/EcoIssues#4336]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1 placer un mur a c'est pied
2 replacer un mur sur ce mur

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Désolé pour l'auto traduit français!

Alors vous avez placé un bloc où vous étiez debout, ce qui vous a obligé à rester coincé dedans? Oui, cela arrive malheureusement maintenant. Vous pouvez utiliser /unstuck pour sortir. Nous espérons améliorer cela à l'avenir.
