### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by GamerDanil** [StrangeLoopGames/EcoIssues#4337]
**Version:** 0.7.0.5 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: D:/ECO v0.7.0.5/Eco_Data/Server/Storage\1.eco already exists
```

**Comment by MarjieAVolk** [comment]
You are trying to create a world with the same name as an existing world.  Try entering a different name for your new world.
