### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Litschi123** [StrangeLoopGames/EcoIssues#4339]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Connect to a server

**Expected behavior:**
Join the server

**Actual behavior:**
Won't connect to server and shows the following error message:
> Connection Failed
> Login info could not be verified. Our auth servers may be down.
> Unexpected character encountered while parsing value: <. Path ", line 0, position 0

**Comment by Litschi123** [comment]
Still the same on _0.7.1.0 beta_

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4426
