### ISSUE TITLE
Phantom blocks causing user disconnect because of exeption / corrupted world blocks.

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#434]
![disconnect when going around](https://cloud.githubusercontent.com/assets/1668416/16572369/3bfdec4c-4268-11e6-936d-961463cbbb79.png)
[Saves and dumbs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/347005/Saves.and.dumbs.zip)

Both me and other users report after 4.1 that invisible phantom blocks while passing over them causes disconnects with an exception . placement of them seems random but consistent all over the world. one example is this coordinates from the Eu server = 380, 28, 26. (Within around 2 to 3 blocks, pretty hard to get coordinates because of the bug.)

i attached disconnect message and save + dumbs from the server

**Comment by metachronism** [comment]
took a look at this, can't easily repro - any better steps?  Were you just walking around in those areas?

**Comment by noblackthunder** [comment]
i dont know how to cause them .. but i wonder if the recent update from 4 to 4.1 might have caused this maybe ? .. dont know if you can open the save and check those coordinates ? and see what is at those spots

**Comment by thirddegreeburn** [comment]
I can duplicate this disconnect and error message every time I press E on a tree stump, as if to attempt to pick it up.
