### ISSUE TITLE
USER ISSUE: Unable to craft Wooden Hoe

### ISSUE THREAD

**Issue by ashums** [StrangeLoopGames/EcoIssues#4345]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Create Order for Wooden Hoe in the Workbench
2. Add 8 wood to the Workbench
3. Wait until crafting completes

**Expected behavior:**
It should have crafted the wooden hoe.

**Actual behavior:**
The item just disappears. It doesn't show up in the workbench as collectable.

**Comment by MarjieAVolk** [comment]
Did the item get automatically put into nearby storage?  You can look at the Storage tab on the workbench to see with containers it could have been put into.

If that is not the case, you might be seeing this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3240

**Comment by MarjieAVolk** [comment]
Closing due to no response
