### ISSUE TITLE
Store wont show new items unless you re-log.

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#4347]
This has been around for a couple versions, but when a player puts something in their store, in order to see it, they have to re log to "refresh" the store. As an example, player A will put wood into their store, player B comes up 5 minutes later to buy wood, but player B does not see the wood until he/she re-logs. We are currently on the 7.1.0 staging version.

**Comment by yanphi** [comment]
I agree this is an annoying occurrence, another way of 'refreshing' the store without re-logging is to move the items up and down which also refreshes it.

**Comment by metachronism** [comment]
I believe this is fixed as of 7.3
