### ISSUE TITLE
[Art] Framed Glass wall blocks if one is placed above a doorway opening cannot go through opening

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4350]
**Version:** 0.7.0.8 beta

@keegan-o as can be seen below there is enough space for player to pass through but it is impossible
![snap1638](https://user-images.githubusercontent.com/29383891/36077156-e3e8e208-0f5e-11e8-8a53-f5a5125473f2.png)

but if it is any other type of framed glass block above doorway you can wall through the gap.
![snap1639](https://user-images.githubusercontent.com/29383891/36077228-d42a8df2-0f5f-11e8-9fbd-188bd1d4bb25.png)

At the moment only working Framed Glass is Stairs (love the look of these ❤️ ) and Wall Blocks (work great on corners) the rest are just solid Glass Cubes with Frames, except the window block which has no texture at all
![snap1640](https://user-images.githubusercontent.com/29383891/36077287-da66e0a2-0f60-11e8-8cc8-1a0073cdf31f.png)

using this Diagram to try and explain what am seeing Framed Glass Blocks as
![framed glass](https://user-images.githubusercontent.com/29383891/36077601-d5c6d7ce-0f64-11e8-8514-c7219025a021.png)
![snap1644](https://user-images.githubusercontent.com/29383891/36077605-ecd8fbfe-0f64-11e8-9dfd-8a41d24ccd48.png)
![snap1645](https://user-images.githubusercontent.com/29383891/36077781-db4c16da-0f66-11e8-81f8-cdbcd1a8a81b.png)

Other than this Loving the Framed Glass, Getting oh so close to the Pyramid ❤️

**Comment by keegan-o** [comment]
Framed Glass was the final builder on the list so it didn't quite get done, but I've already made a bunch of improvements for the next patch. And we shall have the slopes or roof form too, sometime soon-- for the sake of the Louvre!

**Comment by Conchipedia** [comment]
its getting closer, great work as always ❤️
