### ISSUE TITLE
USER ISSUE: Plant Fiber Harvest Fails

### ISSUE THREAD

**Issue by motzarellagaming** [StrangeLoopGames/EcoIssues#4353]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1. Equip Stone or Iron Scythe. 
2. Find Bunchgrass
3. Left click to Reap
4. Left Click for over 5 minutes
5. Collect nothing

**Expected behavior:**
I would figure it would have allowed me to harvest plant fiber and seeds if I understand the Wiki.

**Actual behavior:**
Lets me swing and swing and the bunchgrass remains unchanged.

**Comment by MarjieAVolk** [comment]
Were you clicking repeatedly, or holding down the mouse button?  I believe you do have to hold down the mouse button for a bit in order for the scythe to work.  This is how most tools work.

**Comment by motzarellagaming** [comment]
My apologies. I can't believe I didn't realize that.

Thanks! Works perfect.

Richard Mazzola
