### ISSUE TITLE
USER ISSUE: Workbench waypoint

### ISSUE THREAD

**Issue by RoboGenius** [StrangeLoopGames/EcoIssues#4355]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
1: create workbench and place
2: take workbench and place somewhere else

**Expected behavior:**
I feel the system-generated "Workbench" waypoint should move with the workbench automatically

**Actual behavior:**
system-generated "Workbench" waypoint stays where you first place the workbench.

**Comment by johnkslg** [comment]
You can manually remove the waypoint, its a different system and prefer not to tie them together for now.
