### ISSUE TITLE
Crash random every ~5 minutes

### ISSUE THREAD

**Issue by MightyPiggie** [StrangeLoopGames/EcoIssues#4357]
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1714843/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1714844/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1714845/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1714847/error.log)

**Comment by SeanAtr0n** [comment]
think this should be fixed, if not please send us your player.log file in 
`%APPDATA%\..\LocalLow\Strange Loop Games\ECO`
