### ISSUE TITLE
USER ISSUE: bush

### ISSUE THREAD

**Issue by Kjeinz** [StrangeLoopGames/EcoIssues#4361]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
it cant be removed it stuckt	

**Expected behavior:**
nothing happening

**Actual behavior:**
gone

**Comment by MarjieAVolk** [comment]
Sorry, I don't understand what the issue is.  There was a bush, and it disappeared?

**Comment by MarjieAVolk** [comment]
Closing due to no response
