### ISSUE TITLE
USER ISSUE: connection failed choosing server off server list. (adding to favs works)

### ISSUE THREAD

**Issue by ashleyc1123** [StrangeLoopGames/EcoIssues#4364]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Trying to connect to my server 185.44.76.102:3001 hosted by gtxgaming fails when trying from the server list, however a direct connect to the server works fine. All my friends have the same issue.	

**Expected behavior:**
Selecting it from the server list and connecting should work, this is preventing new players joining.

**Actual behavior:**
The following error message popped up:
```
connection failed.
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Does the server you are connecting to have NAT enabled in their server config?
