### ISSUE TITLE
[Suggestion] Sharing Newly Created Worlds For Singleplayer or Server Use

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4366]
would be nice to have a flat world or a world with large flat open areas that's been pre generated and can be copied into the Directory of either a open server or singleplayer server folder for Players to practice their  building ideas on, as try to work out how to /level ground (can be a bit confusing) and using devtool to flatten can take ages, obviously it shouldnt be used for playing eco on, that should still be randomly generated for variety

Maybe Take this Idea Further with Players Creating Worlds and sharing them, still not sure about that last bit as you cannot see what a world is like until you enter it and then it saves player data, its sort of based on the idea of minecraft players sharing **seeds** to generate worlds with a certain look

**Comment by Conchipedia** [comment]
might be impractical looking at this for a Flat world, as i can now do /level properly, but the idea of sharing Created Worlds still seems a valid one so going to change title, maybe something can be done via Steam for this sort of thing.

**Comment by Conchipedia** [comment]
maybe we can have Shared Worlds via Eco Steam Workshop?

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#274
