### ISSUE TITLE
USER ISSUE: Stockpile bug

### ISSUE THREAD

**Issue by ouellette17** [StrangeLoopGames/EcoIssues#4367]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Go to stockpile and stand within border
2. Put items in stockpile

**Expected behavior:**
neatly organized stockpile with new items

**Actual behavior:**
Puts items inside of character not allowing you to move.

**Comment by TheKvist** [comment]
What "border" are you referring to? The border of the stockpile building? If so, you're not really meant to stand on the stockpile itself, that is, do not stand within the "border".

If you do, the game might place the blocks on the same position in the stockpile as you're standing on, effectively locking you into place. This is the same behavior as when you're placing two blocks right on the position where you stand. The blocks will stack up without moving your avatar out of the way "capturing" it inside.

While not being locked into place is an issue that definitely has to be addressed, I don't think this has something to do with the stockpile specifically.

**Comment by MarjieAVolk** [comment]
Yes, this is often going to happen if you stand inside a stockpile while placing things into it.  You can use /unstuck to get out.  We hope to improve our character controller, which may reduce these issues in the future.
