### ISSUE TITLE
USER ISSUE: Odd format of room requiremetns

### ISSUE THREAD

**Issue by glenwinters** [StrangeLoopGames/EcoIssues#4369]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Open status page of Research Table in a room that's too small	

**Expected behavior:**
Show the room size requirement as `<amount you have> / <amount you need>`. In this case it'd be 12 m^3 / 25 m^3.

**Actual behavior:**
It shows 25 m^3 / 12 m^3, which is a confusing way to read it.

**Comment by Conchipedia** [comment]
it doesn't look that confusing it is saying that it is using this:
 table uses space/available space
if you have it the other way it would read
available space/table uses space

**Comment by glenwinters** [comment]
When you're looking at the table's status page, your main goal is to fulfill the requirements. If the required space is 25 m^2, I think it would be most intuitive for the possible values to be between 0 / 25 and 25 / 25. You're aiming for 100%. It would be red for anything less than 25. 

I find the <space used> / <space available> metric unclear because the fraction doesn't really represent anything useful. If you don't have enough space you get a weird fraction like 25 / 12. At a glance, it looks like something is double the requirement. If you have enough space, you can have all sorts of fractions like 25 / 75 or 25 / 150 that don't mean anything different from each other.

**Comment by D3nnis3n** [comment]
Fixed.
