### ISSUE TITLE
vampires have taken over campfires and made them to campvesire

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#437]
http://ecoforum.strangeloopgames.com/topic/676/minor-text-issue-campfire-roast

http://ecoforum.strangeloopgames.com/uploads/files/1467700569409-campfire-roast.jpg

**Comment by craig-jong** [comment]
Thanks pluralizer.

**Comment by MysteriaSpell** [comment]
Mufevsin's as well instead of muffins

![mufevsin](https://cloud.githubusercontent.com/assets/20351378/16709218/f18bad78-45cf-11e6-972e-45f6e5ec0bc9.jpg)

**Comment by jhadred** [comment]
Wild mixes comes up as wild mices
![image](https://cloud.githubusercontent.com/assets/20424793/17215801/1fcd138a-54ac-11e6-880f-23a9c5896e0f.png)

**Comment by pan7s** [comment]
Haha nice was going to report this.  Glad someone else did
