### ISSUE TITLE
failed login

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4372]
failed to log in from my pc on another account and if someone else tries to join

**Comment by MarjieAVolk** [comment]
Can you give me some more details about what happened?  Were you trying to log in to your slg account?  Or were you trying to connect to a server?  What error messages did you see?

**Comment by MarjieAVolk** [comment]
Closing due to no response.  We have since fixed several login problems, so it's possible your issue was addressed.
