### ISSUE TITLE
USER ISSUE: Unable to connect to friends world

### ISSUE THREAD

**Issue by Gugnit** [StrangeLoopGames/EcoIssues#4373]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Log into Steam
2. In main menu, have your friend send you invite via steam to join world.
3. Accept invite

**Expected behavior:**
Should connect to world

**Actual behavior:**
The following error message popped up:
Connection Failed

**Comment by MarjieAVolk** [comment]
Was your friend's computer on the same network as yours?

**Comment by Gugnit** [comment]
Yes, we were sitting maybe 4 feet apart.
 
 
  On Mon, Feb 12, 2018 at 7:57 PM, MarjieAVolk<notifications@github.com> wrote:   
Was your friend's computer on the same network as yours?

**Comment by metachronism** [comment]
if you are still having trouble with this:
try joining through the server browser, via the IP that shows up with LAN
