### ISSUE TITLE
iron pickaxe takes more calories to use than stone pickaxe

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#4376]

**Comment by Dr-Hardware** [comment]
From what I can see the Pickaxe base rates should be 20 for stone and 17 for iron.   Were they both fully repaired?   (Calorie use increases as durability decreases)

I started a fresh server to test and this came out correct -> .[http://prntscr.com/idhd9x](url)

Have you modified the Files perhaps?

**Comment by SeanAtr0n** [comment]
Ahh, the iron pickaxe was nearly broken... 
This damaged tool penalty seems weird and un-intuitive... the broken penalty is very noticeable and led me to believe that tools were either ok or broken. IMO we should get rid of the damage penalty or it should be explained somewhere

**Comment by MarjieAVolk** [comment]
Oh, I thought it only changed when it was broken too >>
