### ISSUE TITLE
USER ISSUE: Cant pull cart

### ISSUE THREAD

**Issue by Tyler-Spencer** [StrangeLoopGames/EcoIssues#4378]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
press E on cart handle in open area

**Expected behavior:**
pick up and pull cart

**Actual behavior:**
momentarily pulls cart for a split second before changing back to normal/not pulling cart

**Comment by SeanAtr0n** [comment]
you probably need to eat something

**Comment by SeanAtr0n** [comment]
closing, let me know if you still can't pull after eating... we will eventually add better indicators of starvation
