### ISSUE TITLE
Mesh issue [with video]

### ISSUE THREAD

**Issue by Mansitos** [StrangeLoopGames/EcoIssues#4383]
**Version: 0.7.1.0 beta**

**Steps to Reproduce:**
Blocks placed like in the video 👍 

_**Watch the video:**_
[https://www.youtube.com/watch?v=IIXl4f2_ldk&feature=youtu.be](url)

**Expected behavior:**

**Actual behavior:**

**Comment by Nanders** [comment]
Character controller is too tall. Although I think this is also a minor problem for artside as well.

**Comment by keegan-o** [comment]
Video is a 404 link for me so will not know what this is about until described. But if it's about Road blocks, workin' on it!

**Comment by Mansitos** [comment]
Sorry, try now:
(Yes is about that)

https://youtu.be/IIXl4f2_ldk

Il 13 feb 2018 10:46 PM, "keegan-o" <notifications@github.com> ha scritto:

**Comment by MarjieAVolk** [comment]
Ah if it's roads, then we've got another bug for that.  Thought it was to do with the glass walls.

Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3582
