### ISSUE TITLE
USER ISSUE: problem stuck connecting.....

### ISSUE THREAD

**Issue by bolapi1987** [StrangeLoopGames/EcoIssues#4384]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
i link account steam and cant connecting single player and multiplayer. even download exe form eco wesbite andlogin still got error authorise failed. sending failure. please help me this been 4 day

steam game
play as new game and stuck with connecting been 1 hours i go watch tv my fav channel and go to my pc still same with this
https://i.imgur.com/9dTpMjf.jpg

join the game dint any see server name anymore after 2 hours
https://i.imgur.com/9dTpMjf.jpg

login error
https://i.imgur.com/otObgAZ.jpg

**Expected behavior:**
it should easy play game on early access on steam and this what i get. 

**Actual behavior:**
hope can refund been 4 day cant do nothing much

**Comment by metachronism** [comment]
Sorry for the issues you were seeing!
We've fixed this for 7.2, looks like it was an error parsing the save files from before.
