### ISSUE TITLE
USER ISSUE: Can't start a game under Fedora

### ISSUE THREAD

**Issue by TheKvist** [StrangeLoopGames/EcoIssues#4385]
**Version:** 0.7.1.0 beta

**System information:**

OS: Fedora 26
Kernel: 4.14.11-200.fc26.x86_64

**Steps to Reproduce:**
1. Install the game through Steam on Fedora 26
2. Start the game, ignore the warnings about Eco not responding and wait until it starts
3. Click "New" and enter a name for your game
4. Click start

**Expected behavior:**
A new game is initialized, loaded and started.

**Actual behavior:**
The following error message popped up:

```
Could not create save file: /home/[user]/.local/share/Steam/steamapps/common/Eco/Eco_Data/Server/Storage/DefaultWorld does not exist
```

From the error message I could only guess that Eco is looking for some `DefaultWorld` file in the above-mentioned path from which a save file for a new world is created, but that file does not seem to get installed by Steam. In fact, the whole path below the `Eco_Data` directory does not exist.

**Comment by SeanAtr0n** [comment]
Automatic startup within game isn't supported on linux right now, here is a guide on setting up a local server you can connect to using Join:
http://ecoforum.strangeloopgames.com:4567/topic/2984/setting-up-a-eco-server-on-ubuntu-other-linux-is-probably-very-similar
