### ISSUE TITLE
using 7.1.0 beta   Not getting skill points

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4386]
Quit game  two days ago am well fed and had 3 skill points sign back two days later still have full food and 3 skill points Chat says i have logged back in BUT i have only been gone 33 seconds

**Comment by ecoemmeck** [comment]
Is this a multiplayer server or single player?
If single player was the server running while you weren't playing?

**Comment by cuda70** [comment]
Single player on steam no idea as it is not my server i just clicked play and created the world

**Comment by ecoemmeck** [comment]
Ahh yes the single player version of the game doesn't run while your not playing from what I understand and thus you won't be earning skill points while your not playing. However I do believe it's possible to increase your skill point gain while you are playing

**Comment by cuda70** [comment]
Well than it is useless to play as it will take forever to earn skill points so far the only way to get more points is by crafting BUT you only  get 0.32 skill point

**Comment by MarjieAVolk** [comment]
Hey - yes, when running a server yourself from in game, the server only runs while you are playing, so nothing changes while you are logged out.  This is why we have significantly lower skill point costs for local worlds, and as you mentioned the additional skill points for crafting things.  It is a new feature to be able to launch your own server from in game, so we are still working on balance.
