### ISSUE TITLE
USER ISSUE: /repopulate error

### ISSUE THREAD

**Issue by bfc1974** [StrangeLoopGames/EcoIssues#4391]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
typed in the above command to get creatures repopulated and got this error. Im thinking I may need to wipe the server and start again???

**Expected behavior:**
repopulate animals?

**Actual behavior:**
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by MarjieAVolk** [comment]
@Nanders I've been seeing this stack trace in a lot of places.  I was thinking maybe it's like a special characters problem or something, so assigning it to you in case the chat commands are returning some weird string.  But I really don't know

**Comment by cr0ss0vr** [comment]
"Value cannot be null" seems to indicate that there's no argument passed through to the actual command, e.g  "/repopulate fox"

**Comment by bfc1974** [comment]
Yes there was no argument.  Didn't assume a creature had to be added as the parameter


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: cr0ss0vr <notifications@github.com> Date: 13/02/2018  09:01  (GMT+00:00) To: StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com> Cc: bfc1974 <bfc1974@gmail.com>, Author <author@noreply.github.com> Subject: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: /repopulate error (#4391) 
"Value cannot be null" seems to indicate that there's no argument passed through to the actual command, e.g  "/repopulate fox"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/StrangeLoopGames/EcoIssues","title":"StrangeLoopGames/EcoIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/StrangeLoopGames/EcoIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cr0ss0vr in #4391: \"Value cannot be null\" seems to indicate that there's no argument passed through to the actual command, e.g  \"/repopulate fox\""}],"action":{"name":"View Issue","url":"https://github.com/StrangeLoopGames/EcoIssues/issues/4391#issuecomment-365193753"}}}

**Comment by MarjieAVolk** [comment]
Ah so it is a chat command problem; it should return a helpful error message in this case

**Comment by bfc1974** [comment]
Correct it was done in game as admin via the chat text box

**Comment by MarjieAVolk** [comment]
"Discovered issue: Somehow an old version of the AdminUtils Mod was installed on the server. The version installed was 7.0.8 while our server was 7.1.2. After installing the correct AdminUtils mod, the issue has corrected itself.

This may be noted for any others having this issue when running any command as an admin." -- @SiriusX

**Comment by MarjieAVolk** [comment]
@Nanders seems this also happens for /help when not passed any parameters, thus upping the priority.

**Comment by Nanders** [comment]
Just fixed this
