### ISSUE TITLE
USER ISSUE: Experiin Point earned by Crafting - ?

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4394]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. que up 40 stone , skil few other things then log off
2. log in seems like the crafting when logged off did not provide any experience for stuff crafted while logged off 

I increased amount that it should give by from .0003 to .001 so i think it should gave something ?

to test this i turned the rate mutiplter to 0 and the base to 0 i had about same amount as when i logged out.

my house base is .4

**Expected behavior:**

**Actual behavior:**

**Comment by craig-jong** [comment]
I just checked this and I get experience from crafting while offline.

A SkillGainMultiplier of 0 will give you no experience from anything including from skillpointspercrafttime since that number is scaled based on your skill gain.
