### ISSUE TITLE
USER ISSUE: fly tree

### ISSUE THREAD

**Issue by marc1772** [StrangeLoopGames/EcoIssues#4395]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**

**Expected behavior:**
on a cassez un arbre et au bout d'un moment il s'envole et si on essaye de le casser sa fait chrach le serveur

**Actual behavior:**

**Comment by SeanAtr0n** [comment]
Sorry if translation is bad, using google translate:
fermeture comme doublon de bug https://github.com/StrangeLoopGames/EcoIssues/issues/3668

Si vous pouvez reproduire de manière fiable le problème, cette information serait très utile.
