### ISSUE TITLE
USER ISSUE: Character controller gets stuck

### ISSUE THREAD

**Issue by kaupinkevin** [StrangeLoopGames/EcoIssues#4396]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
i dont know

**Expected behavior:**
i was making a tunnel

**Actual behavior:**
..

**Comment by kaupinkevin** [comment]
help me please i want to play

**Comment by Nanders** [comment]
If you ever get stuck, the command /unstuck will get you out. Improvements to the character controller are forthcoming.

**Comment by SeanAtr0n** [comment]
fixed 7.2
