### ISSUE TITLE
USER ISSUE: Suggestion - on exprince for crafting and actions

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4399]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
It would be really cool to help encourge people to advance there effeciny levels instead of skipping them and wasint resrouce if high skill level incress the Exp gain you get from preforming the action. encourging people to level up there job professions.

so like as u gain skill at crafint stone u prodce it faster which would give u less experince but do to having higher level in some other skill related to it you would gain more form each one you crafted.

other whys it seems people skipp alot of the skills in the job professions and waste alot of resrouces.

currently we are running

time gain 1
base skill 0

house base 60

action .002
crafting .0005

skill cost 2.5

we have 15 active users on server out of 30

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#273
