### ISSUE TITLE
USER ISSUE: Missing search filter on server list

### ISSUE THREAD

**Issue by joaompinto** [StrangeLoopGames/EcoIssues#4405]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Use "Join" to join a new server
2. The list is too long to find a server based on it's name or a specific string

**Expected behavior:**
There should be a field with text to show only server titles containting the string

**Actual behavior:**

**Comment by Conchipedia** [comment]
would be nice to have different options to sort Servers in, Alphabetical for one choice

**Comment by joaompinto** [comment]
I have noticed that this was implemented in one of the recent updates.
Thanks 👍
