### ISSUE TITLE
USER ISSUE: Crash while joining game via steam chat

### ISSUE THREAD

**Issue by Wubinator** [StrangeLoopGames/EcoIssues#4407]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Join a game via steam chat

**Expected behavior:**
Connected to my friends game

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Caught exception: Caught exception invoking RPC Authorize on Client!

De objectverwijzing is niet op een exemplaar van een object ingesteld.


Stack:
   bij Eco.Plugins.Networking.Clients.Client.Authorize(LoginSession sessionInfo, String version)

```

**Comment by MarjieAVolk** [comment]
This is a server version mismatch error.  Make sure you are on the same version as the server you are trying to join.  We will have better error messages for this in the future

**Comment by Wubinator** [comment]
Without updating either client I managed to connect the second time. So the version number wasn't the issue I think

**Comment by MarjieAVolk** [comment]
Oh you are right, I'm sorry.  I got this mixed up with a different common stack trace.

**Comment by elfl0rd** [comment]
@mirasrael can you look? Maube can be closed?
