### ISSUE TITLE
Can get items stuck in crafting benches and chests by placing too many in a room

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#441]
http://ecoforum.strangeloopgames.com/topic/673/client-bug-how-to-hammer-axe-without-hammer-axe

Current proposed solution: allow items to be REMOVED from disabled benches and chests.

**Comment by noblackthunder** [comment]
double post ! https://github.com/StrangeLoopGames/EcoIssues/issues/435

**Comment by craig-jong** [comment]
Yea, just noticed
