### ISSUE TITLE
USER ISSUE: Just had a huge wave of Death appear and i saw every plant just die

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4411]
**Version:** 0.7.1.0 beta

![snap1685](https://user-images.githubusercontent.com/29383891/36116869-b92ffdf4-102f-11e8-8d4a-3b0b77a52cb7.png)

Been Playing Singleplayer, this world is ONLY 8 hours 25 Minutes old and then suddenly i saw everything get updated on screen and everything just was Dead, the grass and the plants even had a look in the sea and those plants are dead as well, All i had done here was use /level 200,200,DirtBlock so i had somewhere to build (luckily this is not a world i was trying to live in) but i had never actually had seen this happen before, it was like a Mass update of everything visible

only other command i used was /repopulate PricklyPear  to see if i could get some appear in my empty desert

[TestWorld.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1717663/TestWorld.zip)

This is the World i am using, Ignore the Flat Area and Sphere 😄

**Comment by knexer** [comment]
/repopulate was used instead of /regenlayer
I guess lots of people are getting those confused - that's bad, /repopulate is a world breaker.  We should remove that command.

**Comment by Conchipedia** [comment]
maybe have more info about what the commands do might help use understand how good or bad they are and avoid breaking this to badly

**Comment by craig-jong** [comment]
Repopulate was removed entirely due to issues it had.
