### ISSUE TITLE
USER ISSUE: Cant detach Small Wooden Cart 

### ISSUE THREAD

**Issue by WinterCon** [StrangeLoopGames/EcoIssues#4412]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Pickup Small Wooden Cart with Deed or without
Can't detach Small Wooden Cart anymore
Disconnect from Server and Reconnect, Small Wooden Cart is then detached, rinse and repeat everytime

**Expected behavior:**
It should detach when I wanna pickup stuff and put it into the Wooden Cart

**Actual behavior:**
Doesn't detach at all.

**Comment by MarjieAVolk** [comment]
So when you say detach, you mean you are pulling the cart and can't let go of it?  The key to let go of a cart is 'E'.  Is that what you were trying?

**Comment by WinterCon** [comment]
Yes, I can't let go of it. Since I am left handed, I rearranged all my keys, so E would be K0 now, and that does not work for it. So I can pull it, drive around, disconnect and reconnect to the server and then the cart is disconnected from me. Once I am pulling it, I can press whatever I want, it doesn't work. Hope that helps ya.

**Comment by MarjieAVolk** [comment]
I'm guessing this is a controls rebinding problem in that case.  Why don't you try 'E' anyway?  Maybe that is not getting mapped

**Comment by WinterCon** [comment]
Yeah i put the Controls which was "E" back and it started to work, seems then it doesnt apply for re-mapping at all.

**Comment by MarjieAVolk** [comment]
Okay, yeah so if I understand correctly, you should be able to keep the controls mapped to K0 as you had it, and only have to use E to let go of the cart.  Hopefully that works as a workaround until we fix this.

**Comment by Dr-Hardware** [comment]
relates to #4479

**Comment by SeanAtr0n** [comment]
fixed 7.2
