### ISSUE TITLE
Aqueducts have no form icon or model

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4414]

**Comment by Conchipedia** [comment]
USER ISSUE: Aqueduct is not in game #3717 
i did mention it in this one but it got closed, maybe should have made a New one just for Aqueduct 😄

**Comment by MarjieAVolk** [comment]
Oh, I see that one got marked as fixed on master, so maybe it is already fixed.

**Comment by Conchipedia** [comment]
check with @keegan the Master of Blocks 😄

**Comment by UnknownViper** [comment]
I think it's worth noting that they don't actually functionally work presently either: https://i.imgur.com/eWFfdoL.jpg
The same water drop-off that happens in normal conditions also happens with the current aqueducts. I built the standard V shape version.
I'm greatly looking forward to aqueducts working (again, as they apparently did work at some point), as it'll be pretty nice to build that stuff and utilize water. :)

This was done in version 0.7.1.0.

**Comment by keegan-o** [comment]
fixed the blocks not appearing, also gave them their own builder/meshes to differentiate them from other bricks (but no longer use the ancient builder)

**Comment by MarjieAVolk** [comment]
@keegan-o will this make them function better also, by any chance?

**Comment by keegan-o** [comment]
No, that would be a very different bug for different people >.>

**Comment by MarjieAVolk** [comment]
Okay, I filed a new issue for verifying that aqueducts work gameplay wise: https://github.com/StrangeLoopGames/EcoIssues/issues/4478
