### ISSUE TITLE
USER ISSUE: Server Performance - Crashes every 5-30 min latency gos up to 5000ms

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4416]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
I doesnt know what it is but the Server crash on several times 
i have 13 Users but the users not the problem i think its "mining rock" but i doesnt know ...
hope you can fix this fast so ....

Server Performance is very good
24 Core
64 GB RAM
1000 GBit Network

**Expected behavior:**

**Actual behavior:**

**Comment by Geuthur** [comment]
![screenshot_12](https://user-images.githubusercontent.com/761682/36118880-bdd302de-103e-11e8-9057-2034a114ca5d.png)

That is when it crash

**Comment by MarjieAVolk** [comment]
The error shown in your screenshot will be fixed in the next release.  It shouldn't be related to performance problems.
