### ISSUE TITLE
USER ISSUE: Cant joing servers or play solo.

### ISSUE THREAD

**Issue by Ehrq** [StrangeLoopGames/EcoIssues#4423]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Load or start a new game. No servers avail in join list

**Expected behavior:**
It should have created a new world or opened a current one, or displayed available servers

**Actual behavior:**
The game tabs out and then displays error message "Connection Failed" And i see no servers in join menu.

**Comment by MarjieAVolk** [comment]
For your local game, can you attach your server's error log?  You should be able to find it in '[...]/steamapps/common/Eco Server'

**Comment by Ehrq** [comment]
Eco Log Session from 2018-02-12 00:17:08
Eco Server 0.7.1.0 beta
Server Initialization... 
Starting ModKitPlugin... 
Compiling mods... 
Initializing items... 
Initializing skills... 
Starting NetworkManager... 
Starting StorageManager... 
Starting WorldGeneratorPlugin... 
Starting GameplayStatsPlugin... 
Starting StatDatabase... 
Starting WorldPlugin... 
Initializing world... 
Starting TimePlugin... 
Starting ReputationPlugin... 
Starting PlayerHousingManager... 
Starting UserManager... 
Initializing inventories... 
Starting EcoObjectManager... 
Starting ControllerManager... 
Starting ChatServer... 
Starting WirePlugin... 
Starting DifficultySettings... 
Starting PropertyManager... 
Starting BackupPlugin... 
Starting DisasterPlugin... 
Starting EcoSim... 
Starting MinimapManager... 
Initializing plants... 
Starting RouteProbingPlugin... 
Starting WorldLayerManager... 
Starting EconomyTracker... 
Starting WorldObjectManager... 
Starting EconomyPlugin... 
Starting RoomPlugin... 
Starting ObjectivePlugin... 
Starting Legislation... 
Starting WebServerPlugin... 
Starting DiscordPlugin... 
Initializing WorldGeneratorPlugin... 
Generating world 0,52km²... 
Generating terrain... 
Generating plateaus... 
Carving rivers... 
Initializing world layers... 
Finding tailings... 
Ticking world layers... 
Ticking... 
Determining visibility... 
Compressing... 
Saving world... 
Generating world 0,52km² finished in 53 350,2ms
Initializing WorldObjectManager... 
Initializing RoomPlugin... 
Server Initialization finished in 62 085,6ms

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 00:01
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

For your local game, can you attach your server's error log? You should be able to find it in '[...]/steamapps/common/Eco Server'
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Hm, so looks like it started up fine.  So I guess it is actually a connection problem.

**Comment by Ehrq** [comment]
Alright, soo.. Its been like this since the day after launch, and i havnt seen anyone else complain on any forums or so. Which leads me to Think its an uncommon issue?

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 00:26
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Hm, so looks like it started up fine. So I guess it is actually a connection problem.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Since launch huh?  Sorry you haven't been able to play the whole time!

We have had a handful of people filing can't connect bugs, many of which were not confirmed as to what the actual issue was since people didn't respond.  We have also had I would say 2 or 3 people file bugs about the server list having nothing in it for them.  But we also have lots and lots of people playing the game without seeing this issue.

**Comment by Ehrq** [comment]
Unlucky then, ive gotten to play around 10 hours, love the game. Hopefully it will be resolved soon.

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 02:41
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Since launch huh? Sorry you haven't been able to play the whole time!
We have had a handful of people filing can't connect bugs, many of which were not confirmed as to what the actual issue was since people didn't respond. We have also had I would say 2 or 3 people file bugs about the server list having nothing in it for them. But we also have lots and lots of people playing the game without seeing this issue.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Do you have any error logs from your client actually?  Those should be in C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO, should be called output_log.txt

I haven't gone into debugging this much, but if you want to try like reinstalling the game, playing on a different computer, maybe downloading the game from our site instead of playing on steam... if you find anything that works, that might also help us solve the issue more quickly.

**Comment by Ehrq** [comment]
Yeah, ive done all those things, including verifying steam cache and so on. 

Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1b81)
    Vendor:   NVIDIA
    VRAM:     8088 MB
    Driver:   23.21.13.9077
Begin MonoManager ReloadAssembly
- Completed reload, in  0.057 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 6 worker threads for Enlighten.
  Thread -> id: 4514 -> priority: 1 
  Thread -> id: 3f60 -> priority: 1 
  Thread -> id: 45e4 -> priority: 1 
  Thread -> id: 2d30 -> priority: 1 
  Thread -> id: 393c -> priority: 1 
  Thread -> id: 4460 -> priority: 1 
UnloadTime: 3.417121 ms
JsonReaderException: Unexpected character encountered while parsing value: 
  at Newtonsoft.Json.JsonTextReader.ParseValue (Char currentChar) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, System.Type t, Newtonsoft.Json.JsonConverter propertyConverter) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[LastPlaySessionInfo] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[LastPlaySessionInfo] (System.String value) [0x00000] in <filename unknown>:0 
  at NetworkManager.LoadLastPlaySessionInfo () [0x00000] in <filename unknown>:0 
  at NetworkManager.Initialize () [0x00000] in <filename unknown>:0 
  at NetworkManager.Start () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)


Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 03:52
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Do you have any error logs from your client actually? Those should be in C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO, should be called output_log.txt
I haven't gone into debugging this much, but if you want to try like reinstalling the game, playing on a different computer, maybe downloading the game from our site instead of playing on steam... if you find anything that works, that might also help us solve the issue more quickly.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by Ehrq** [comment]
Alright, turns out deleting the folder in LocalLow solved the problem. Was not aware the game saved files in that particular folder. Thanks for the help!

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 03:52
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Do you have any error logs from your client actually? Those should be in C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO, should be called output_log.txt
I haven't gone into debugging this much, but if you want to try like reinstalling the game, playing on a different computer, maybe downloading the game from our site instead of playing on steam... if you find anything that works, that might also help us solve the issue more quickly.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Glad that worked!  Was just going to say, looks like your 'Continue' preferences were corrupted.  Wonder how that happened!  Was going to ask you to send that file over, so we could see what went wrong with it - if you still have it in your recycle bin.

**Comment by Ehrq** [comment]
Which file specifically?

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 04:34
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Glad that worked! Was just going to say, looks like your 'Continue' preferences were corrupted. Wonder how that happened! Was going to ask you to send that file over, so we could see what went wrong with it - if you still have it in your recycle bin.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Sorry, the file is called player.eco

**Comment by Ehrq** [comment]
There you go.

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 05:07
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Sorry, the file is called player.eco
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
I didn't see any attachments

**Comment by Ehrq** [comment]
Lets try it again then. 

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 05:11
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

I didn't see any attachments
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Hm I still don't see anything, either in the email or here.  I wonder if github is doing something strange because of the auto email to comment thing.  Maybe email me directly instead of in this thread?  Or maybe you could upload to a file sharing site and give the link?

**Comment by Ehrq** [comment]
https://expirebox.com/download/3e18c16878af13706abcab9b960118eb.html

Skickades från E-post för Windows 10

Från: MarjieAVolk
Skickat: den 13 februari 2018 06:09
Till: StrangeLoopGames/EcoIssues
Kopia: Ehrq; Author
Ämne: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Cant joing servers orplay solo. (#4423)

Hm I still don't see anything, either in the email or here. I wonder if github is doing something strange because of the auto email to comment thing. Maybe email me directly instead of in this thread? Or maybe you could upload to a file sharing site and give the link?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by MarjieAVolk** [comment]
Okay this time I got it.  Thank you!
