### ISSUE TITLE
[Suggestion] Aquariums or Fishtanks?

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4427]
![snap1691](https://user-images.githubusercontent.com/29383891/36125581-6b1a8d88-104c-11e8-9bee-f18c71316164.png)
![snap1690](https://user-images.githubusercontent.com/29383891/36125591-7e22f6cc-104c-11e8-9c41-b9a9b7dcc2a3.png)
created in Singleplayer game with dev commands and spawning, sadly disconnecting and connecting they disappear.

Fishtank better when @keegan the master of Blocks has finished with them 😄

**Comment by MarjieAVolk** [comment]
Sounds cool.  Also sounds similar to animal husbandry.  Which we want to have but haven't prioritized yet.

**Comment by Conchipedia** [comment]
this only started as i wanted to see an otter, i saw one in the game once and i ran out of calories trying to get a better view

**Comment by MarjieAVolk** [comment]
Man I don't think even I have seen one in game XD

**Comment by Conchipedia** [comment]
you have to be super lucky, i thought it was a swimming Hare at first 😂

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#271
