### ISSUE TITLE
[Suggestion] Dyable Blocks and Glass

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4428]
(Multiple recipes would be nice as we can either sell ingredients to craft or the Dyes themselves)
this will also give us a chance to use up plants and seeds

Order is main plant, then seeds, then dyes
Colour Dye = Ingredient + Ingredient (if a Second is needed)

White = Crimini Mushroom
White = Crimini Mushroom Spores
Orange = Tomato + Corn
Orange = Tomato Seed + Corn Seed
Orange = Red Dye + Yellow Dye
Magenta = Fireweed Shoots + Crimini Mushrooms
Magenta = Fireweed Seed + Crimini Mushroom Spores
Magenta = Purple Dye + White Dye
Light Blue = Huckleberries + Crimini Mushroom
Light Blue = Huckleberry Seed + Crimini Mushroom Spores
Light Blue = Blue Dye + White Dye
Yellow = Corn
Yellow = Corn Seed
Lime = Bunchgrass Seed + Crimini Mushrrom
Lime = Bunchgrass Seed + Crimini Mushroom Spores
Lime = Green Dye + White Dye
Pink = Tomato + Crimini Mushrooms
Pink = Tomato Seed + Crimini Mushroom Spores
Pink = Red Dye + white Dye
Gray = Coal + Crimini Mushrooms
Gray = Coal + Crimini Mushroom Spores
Gray = Black Dye + White Dye
Light Gray = Gray Dye + White Dye
Cyan = Huckleberry Seeds + Bunchgrass Seeds
Cyan = Huckleberries + Bunchgrass Seeds
Cyan = Blue Dye + Green Dye
Purple = Fireweed Shoots
Purple = Fireweed Seeds
Blue = Huckleberries
Blue = Huckleberry Seeds
Brown = Beans
Green = Bunchgrass Seed
Red = Tomato
Red = Tomato Seed
Black = Coal

note this is in the order i did these in was taken from this Snapshot (i used this as a base for Color)

![color chart](https://user-images.githubusercontent.com/29383891/36126010-79763ccc-104e-11e8-801c-ba147ef27514.png)

Obviously this is based on a certain game idea using wool (which would be stupid in Eco) so using real Blocks (block with not to much texture) and Glass

**Comment by Conchipedia** [comment]
![snap2037](https://user-images.githubusercontent.com/29383891/37555680-30641e06-29e3-11e8-887f-9e3d394c8753.png)

now with Solid color blocks this would look so much cooler 🐧

**Comment by Conchipedia** [comment]
thinking a bit more on this , maybe introduce a NEW block into the game  Clay (Tier 0) Dirt or sand that is mixed with water somehow and then we could maybe have like a paint brush or something that can dye this block

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#270
