### ISSUE TITLE
Fertilizer quantity not correct in stores

### ISSUE THREAD

**Issue by moonmoon255** [StrangeLoopGames/EcoIssues#4429]
![store1](https://user-images.githubusercontent.com/36427056/36126582-223b7584-1027-11e8-83ae-a8db577e7fe3.PNG)
![store2](https://user-images.githubusercontent.com/36427056/36126583-234ccb4e-1027-11e8-8556-8e9e584c2eeb.PNG)

**Comment by MarjieAVolk** [comment]
Oops, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3617
