### ISSUE TITLE
carts issue ( passing world border etc.)

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#443]
http://ecoforum.strangeloopgames.com/topic/663/wooden-cart-bugs-4-1

**Comment by noblackthunder** [comment]
have had a report on fb where the issue was even worse and over half of every recipe was a workbench

**Comment by goertzenator** [comment]
See also #408  and #425

**Comment by metachronism** [comment]
sean fixed this
