### ISSUE TITLE
USER ISSUE: Carpentry Table(just helping)

### ISSUE THREAD

**Issue by Shadowplayx1** [StrangeLoopGames/EcoIssues#4430]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. make a carpentry table
2. place it
3. make something with the material you have
4. says "time 0% Resources 100%"
5. nothing happens
6. stone hammer then place back down
7. attempt step 3 again
8. nothing again.
I tried to restart server and it did not work for me, i tried re-placing it nothing, i tried making a new one and it did nothing.

**Expected behavior:**
it should have made my material that im trying to make, a door, or a chair or anything in the carpentry table

**Actual behavior:**
instead... it just does not produce anything that i want ordered or anything in the table

**Comment by Conchipedia** [comment]
is it in a room that is correct for the table?

**Comment by Shadowplayx1** [comment]
yes i have done that as well :/

**Comment by Conchipedia** [comment]
try placing , then breaking the room and then fixing the room and see if that helps, ive had a table not recognise a room once before

**Comment by Shadowplayx1** [comment]
really? oh ok ill try that, and i will let you know if it works

**Comment by Shadowplayx1** [comment]
it did not work :(

**Comment by MarjieAVolk** [comment]
Can you look at the Status tab on your Carpentry Table, and see what if anything has a red x by it?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
