### ISSUE TITLE
Players having difficulty reading the location as it is very small

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4431]
![snap1696](https://user-images.githubusercontent.com/29383891/36128110-88b9e472-1058-11e8-891c-871c4df5b1db.png)

Any chance of making this bigger?

**Comment by johnkslg** [comment]
art bug!

**Comment by SlayksWood** [comment]
Became a bit more, but It isn't still enough. I will close this issue, because I opened another issue #12320 some time ago, because didn't find that.
