### ISSUE TITLE
USER ISSUE: Disappearing Logs

### ISSUE THREAD

**Issue by benevolio** [StrangeLoopGames/EcoIssues#4434]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Chop down a tree
2. Collect some wood
3. Return to workbench
4. Return to downed tree. All logs missing and an empty space where the tree fell remain.
5. If I logout and log back in right away, logs are magically back.
6. If I log out again then log back in the logs are gone permanently.

**Expected behavior:**
Logs should not disappear after walking away and coming right back

**Actual behavior:**
Logs disappear. Causes headaches. Take anger out on the buffalo.

**Comment by MarjieAVolk** [comment]
Poor buffalo!  Haha

**Comment by MarjieAVolk** [comment]
This might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/3668

**Comment by SeanAtr0n** [comment]
Looks like @Quadbro may have unintentionally fixed this w/ a recent change that prevents sending duplicate interactions
