### ISSUE TITLE
Excavator needs some breaks

### ISSUE THREAD

**Issue by Voidfish93** [StrangeLoopGames/EcoIssues#4436]
https://www.twitch.tv/videos/228423493

Also, it needs a much larger inventory or it creates too much debris when digging stone.

**Comment by MarjieAVolk** [comment]
What do you mean by 'needs some breaks'?

**Comment by craig-jong** [comment]
He wants to be able to stop it when its on a ramp

**Comment by MarjieAVolk** [comment]
ahhhhh

**Comment by SlayksWood** [comment]
Checked on 8.1. Wasn't able to reproduce, seems fixed.
