### ISSUE TITLE
Fishing bug where fish overwrite toolbar?

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#4437]
http://steamcommunity.com/app/382310/discussions/4/1699416432430619785/

**Comment by VAlex0** [comment]
hey craig, referenced all related issues to this one: #4588

have a good day! Alex

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
