### ISSUE TITLE
USER ISSUE: No option to turn off head bobbing

### ISSUE THREAD

**Issue by nzkfc** [StrangeLoopGames/EcoIssues#4439]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Play the game, head bobs on-screen, makes some people feel motion sickness

**Expected behavior:**
New option in settings "Enable Head-bob" and have a tick box.

**Actual behavior:**
Nothing :(

**Comment by elfl0rd** [comment]
Considering that the head bobbing effect was significantly enhanced in version 0.9, this fix should be at 0.9, not 0.9.1.
For example, I can't play 0.9 because of nausea after a couple of minutes of running.
