### ISSUE TITLE
Please add  Description to Network,eco

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4440]
"Description": "",

To Network,eco?  Many people want to know how to name their server and are unable to locate the information to add this.  Password and DetectNAT got added pretty quickly but the wait on Description has been very long

**Comment by MarjieAVolk** [comment]
You can already name your server on the Network tab, can't you?

**Comment by metachronism** [comment]
Description is intentionally left out so the server can autogenerate a name in that case as the default value
