### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Zarwen** [StrangeLoopGames/EcoIssues#4442]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Join one of my world
2. Waiting the Connection
3. At the end of the connection there is an error

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of ongoing issues that could be causing this. One thing you can try is deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO. Let me know if that fixes it.

If not, try sending me your server log files, which are in '[...]\steamapps\common\Eco Server'.

**Comment by MarjieAVolk** [comment]
Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about.  I can continue helping you debug whenever you have time.
