### ISSUE TITLE
USER ISSUE: cant enter server

### ISSUE THREAD

**Issue by thomas6y** [StrangeLoopGames/EcoIssues#4443]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
trying to create a new server or load one i've created gives me a connection error. it's never worked for me yet

**Expected behavior:**
should connect and enter server

**Actual behavior:**
connection failed

**Comment by MarjieAVolk** [comment]
There are a couple of ongoing issues that could be causing this. One thing you can try is deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO. Let me know if that fixes it.

If not, try sending me your server log files, which are in '[...]\steamapps\common\Eco Server'.

**Comment by MarjieAVolk** [comment]
Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about.  I can continue helping you debug whenever you have time.
