### ISSUE TITLE
USER ISSUE: Nolonger join server

### ISSUE THREAD

**Issue by mamu89** [StrangeLoopGames/EcoIssues#4445]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. friend got disconnected who was hosting
2. once he rehosted unable to join the server again although others that were playing with us are back on the server

**Expected behavior:**
allow me to join when server was rehosted

**Actual behavior:**
tells me that the server is offline and that friend is not playing on any servers when attempting to join from steam friends list

**Comment by MarjieAVolk** [comment]
Do you see your friend as playing Eco in the steam friends list?  Wondering if this is an Eco problem or a Steam problem

**Comment by mamu89** [comment]
yes I they were listed in the game, finally was able to connect after friend took down server and re upped it


________________________________

**Comment by MarjieAVolk** [comment]
What I was trying to get at was that it might have been an issue with using steam's join game feature, since it seems that's what you were doing.  Connecting directly to the server through Eco's 'join' window might have worked in that case.
