### ISSUE TITLE
GrondPollutionSpread Layer problem (color)

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4451]
As you can see on the images below, the color used for this layer is a problem to see in real time Ground pollution:
![01](https://user-images.githubusercontent.com/29807119/36154634-57d258a6-10d2-11e8-9f93-254b29e16b47.PNG)
![2](https://user-images.githubusercontent.com/29807119/36154637-59db2268-10d2-11e8-9f1d-52ab8c61871c.PNG)
Is it possible to have the same color (yellow to red as the other layers) to see the impact of ground pollution.
Currently we cannot monitor ground pollution like this

**Comment by MarjieAVolk** [comment]
I believe the coloring of the layer is the same.  For most layers, when they are 0 they look like this.  It is a bit confusing though.

**Comment by MarjieAVolk** [comment]
Oh maybe I am wrong, I see there's a weird spot that's barely visible hahaha
