### ISSUE TITLE
USER ISSUE: Not displaying correct item after item change.

### ISSUE THREAD

**Issue by Hazzatr0n** [StrangeLoopGames/EcoIssues#4452]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
You must be in 3rd person for this glitch to occur
If the user changes the item that they are holding but the animation cannot play (eg, the player is running at the time), the item gets changed but the "visual" item (item in the user's hand) is still the same.

**Expected behavior:**
The player pressed a button to change the item they are holding, and the item in the visual player's hand changes.

**Actual behavior:**
The item in the visual player's hand does not change, but the real item does.

**Comment by Hazzatr0n** [comment]
Also, I forgot to mention

**Comment by Hazzatr0n** [comment]
Sorry, just us being stupid. It isn't a bug because we placed it outside. However, it would be more clear if it told you, instead of the time just not going down.

**Comment by MarjieAVolk** [comment]
We have had a number of people not understand this, so we will consider how to make it more clear.

We do have a red light up in the upper left corner.  But perhaps that needs to be bigger and more flashy.
