### ISSUE TITLE
Hitting 1/2 block coal doesn't make a sound

### ISSUE THREAD

**Issue by astargg** [StrangeLoopGames/EcoIssues#4454]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Hit a coal block, and then when you hit the half coal block that sometimes appear, it doesn't play a sound.

**Expected behavior:**
Play a sound

**Actual behavior:**
Doesn't play a sound.

**Comment by Conchipedia** [comment]
![snap2360](https://user-images.githubusercontent.com/29383891/43864552-e562dfaa-9b57-11e8-8ab4-0769d380f4e1.png)

still no sound for this size Block of Coal Rubble in 0.7.6.3

**Comment by elfl0rd** [comment]
https://youtu.be/LZtfvxwMueU

**Comment by elfl0rd** [comment]
@beastyn @D3nnis3n can we got fix for that as part of sound updates?

**Comment by beastyn** [comment]
@elfl0rd I seems that we've lost tools sounds at all. I will make separate issue for that. Can merge it there though
