### ISSUE TITLE
Axe not working

### ISSUE THREAD

**Issue by redEO14** [StrangeLoopGames/EcoIssues#4455]
So I finally made the leap to buy this game today and I was super excited to play it, but when I tried to chop down a tree, I kept swinging the air and it wouldn't chop. I hit it about 15 time and then it chopped once but that's it. This makes the game unplayable and I hope that this can get fixed because I was really looking forward to playing this.

**Comment by redEO14** [comment]
Update: This is happening with the axe, pickaxe, and shovel in both single and multiplayer. I click and it does the animation but doesn't pick up or hit the block.

**Comment by ZeldoKavira** [comment]
You need to hold the button down.
