### ISSUE TITLE
USER ISSUE: tried to make 20 mortared stone

### ISSUE THREAD

**Issue by jwtc3** [StrangeLoopGames/EcoIssues#4458]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
queued up 20 mortared stone first.
inputed all stone to make mortared stone
queued up required amount of pitch (48)
inputed all sand to make pitch
stone halted production due to not enough pitch
pitch finished and i collect all of them
tried inputting pitch to finish stone, did not work

**Expected behavior:**
inputed pitch to finish stone

**Actual behavior:**
cannot input pitch to finish stone.
i tried relogging/restarting the game with no results. not enough room in inventory to hold all the stone

**Comment by MarjieAVolk** [comment]
How are you trying to add the pitch to the mortared stone project?  Are you putting the pitch into a connected chest?  Are you right clicking on the crafting station while holding the pitch?  Or are you opening up the crafting station window and dragging the pitch onto the project?

You say there's 'not enough room in inventory', so I imagine you are putting the pitch into a connected inventory, which is full.  Try putting the pitch directly into the crafting station by one of the other methods I listed.  Let me know if that solves your problem.

**Comment by MarjieAVolk** [comment]
Closing due to no response.  We do have some issues open for problems with inputting resources into projects (https://github.com/StrangeLoopGames/EcoIssues/issues/4631, https://github.com/StrangeLoopGames/EcoIssues/issues/4007, https://github.com/StrangeLoopGames/EcoIssues/issues/3010)
