### ISSUE TITLE
USER ISSUE: Carts Underground

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4461]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Use a cart underground where the ceiling is 4 high
2. mine a little, or look away, walk around, look back
3. Watch cart move around/wobble or listen to cart moving sounds. Cart sometimes disappears, moves to above ground.

**Expected behavior:**
- Cart sits nice and still where it was stopped

**Actual behavior:**
- Cart wobbles around, and teleports above ground.

**Comment by SeanAtr0n** [comment]
Fixed in 7.2
