### ISSUE TITLE
ECO crash right after start

### ISSUE THREAD

**Issue by Maxteric** [StrangeLoopGames/EcoIssues#4462]
Good evening!

Since 2 weeks now, I can not play ECO anymore. 
Right after I click on play in steam the game is in status "starting" and crahes instantly.
2 weeks ago everything was fine.

The newest net version is installed, I disabled firewall and antivirus and folder protection. 
I reinstalled the game multiple times with steam an with the version from the ECO website.

System:
Win 10
Geforce GTC 780 Ti
Octa Core Processor (8*3,4 Ghz)

Did anyone know what the problem could be?

Ps. Sorry for my bad english, please be patient :)

Greetings!

**Comment by MarjieAVolk** [comment]
Hi there - Sorry you have been unable to play!

So your game crashes right when you start running it, before you get to the main menu?  Could you attach your error log?  This is at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by Maxteric** [comment]
This reply was fast! Thanks for that!

It crashed everytime I click on play in Steam.
Play -> "Eco startin" ... 2 seconds and the game is closed  without even opening.

I would like to, but the in this folder is no output_log and the crashed folder is empty too.

Are they any other software prerequisites except Net.?

**Comment by MarjieAVolk** [comment]
Hmm okay.  I did have one person say they fixed some of their issues by updating Java.

**Comment by Maxteric** [comment]
Tried it and nothing happened. Thats kinda frustrating :D

**Comment by Maxteric** [comment]
Update:
Deinstalled Net and the last windows 10 update, restarted the pc and installed net. Restarted again. Looks like its working now! :)
