### ISSUE TITLE
USER ISSUE: Large Butchery Efficiency

### ISSUE THREAD

**Issue by Kyr0fr** [StrangeLoopGames/EcoIssues#4463]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Unlock Lage Butchery Efficiency LVL 5

**Expected behavior:**
0.2 Bison carcass for 20 meat and 3 leather

**Actual behavior:**
1 Bison carcass for 20 meat and 3 leather

**Comment by ecoemmeck** [comment]
Did you try making the order 5 as to get 100 raw meat?

**Comment by MarjieAVolk** [comment]
You won't actually see the benefit of the cost reduction until you order more than one at once.  If you increase the order size to 10 for example, then you should see it only costs you 2 bison.

**Comment by MarjieAVolk** [comment]
The way this works is weird particularly for butchery recipes.  We have this bug open to take a look at how to improve this: https://github.com/StrangeLoopGames/EcoIssues/issues/2294
