### ISSUE TITLE
Hello, Friend can't connect to server when He tries kicked to main menu after 30sec roughly

### ISSUE THREAD

**Issue by Malaras** [StrangeLoopGames/EcoIssues#4464]
Was told to come here by DrHardware in discord and report issue he/she also tried to connect to server with same result.

Also mentioned post logs/or dumps but they all from yesterday.

What i have done, Windows server forwarded ports through router and there firewall also windows defender is excluded from scanning my steam cmd games.

Get an inactivity message in console when ethier of them tried to log on.

I have no idea what else to do. Only my friend and DrHardware has tried to connect to my server.

Also friend stated that he can connect to other servers which is why i think it's on my end some where. i can connect to my own server just fine, thinking because it's on my network.

**Comment by metachronism** [comment]
Will need more info on this -
can you link the dumps from Server/Dump?
