### ISSUE TITLE
Make disabled objects more obvious

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4466]
A lot of people are confused by their objects not crafting because they are disabled.  Some ideas:

* Add a status indicator into the user status panel for the room
* Make world object ui status light bigger and flashier
* Add a disabled state to world object art in world (maybe just a flashing red overlay for now)
* Add a stronger title on the Status tab
* Open the status tab by default when disabled

**Comment by yanphi** [comment]
Adding a status indicator into the user panel would most definitely make more noticeable. Opening the status tab by default when disabled would also be nice. Another option is to have the crafting tab's page greyed out so that they can't be queued up until the fixed the problem.

**Comment by ecoemmeck** [comment]
(Suggestion) Make Status Tab open if table doesn't meet room requirements #4684

**Comment by MarjieAVolk** [comment]
Thanks, yes we have already implemented that actually.  Should be in the next release.

**Comment by MarjieAVolk** [comment]
Reducing priority actually, since that part is done.
