### ISSUE TITLE
USER ISSUE: Suggestion - for building

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4467]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
It be really cool if we could make the things we make and then make a blue print of them and then we could sell those blue prints to people, in game and they could lay out the template of that item on the ground and just fill in the blocks needed.  we could also then share our blueprints online maybe via workshop or something.

make it easier to remember how to remake things and share ideas for things we have made example
![20180213143310_1](https://user-images.githubusercontent.com/15990789/36172346-3089371c-10cb-11e8-89e5-593bb204ec10.jpg)

**Comment by MarjieAVolk** [comment]
That's a pretty cool idea.  It could also solve the complaints people have about having to unlock block forms and not being able to sell them, since you could sell them in the blueprint

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#269
