### ISSUE TITLE
USER ISSUE: Farmer's stand is not visible

### ISSUE THREAD

**Issue by kingwithou** [StrangeLoopGames/EcoIssues#4468]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Take the Farmer's stand in hand and place it somewhere

**Expected behavior:**
I should see the Farmer's stand

**Actual behavior:**
it is transparent when I try to place it, and once it's placed it is still transparent

**Comment by kingwithou** [comment]
I asked someone on the server to check and he couldn't see it either. But we can climb on it and we see the red or green authorization border

**Comment by ecoemmeck** [comment]
I'm pretty sure the farmers stand is part of clays toolkit. The issue is known and being worked on

**Comment by MarjieAVolk** [comment]
Ah thought you meant the farmer's table.  Since it's a mod item, then closing.
