### ISSUE TITLE
USER ISSUE: Mortared Stone

### ISSUE THREAD

**Issue by Underhandtrout** [StrangeLoopGames/EcoIssues#4472]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1 have stone in stockpile
2 have pitch made on fire
3 attemp to make mortared stone

**Expected behavior:**
it should have made mortared stone and placed it in the linked stockpiles

**Actual behavior:**
after the que was complete the mortared stone never appeared in any of the linked stockpiles or my inventory

*edit* 
here is a link to a gif of it happening
[https://i.imgur.com/JViJTBF](url)

for some reason the link wont work but you are able to copy and paste into the browser and it will take you there

**Comment by MarjieAVolk** [comment]
When you look at the project in the window, is there a 'Collect' button on the right side?

**Comment by Underhandtrout** [comment]
No not at all it has just disappeared entirely it finishes the que and is just gone

**Comment by Underhandtrout** [comment]
All resources have been used as well
