### ISSUE TITLE
Dedicated/Lan Server not Working Properly

### ISSUE THREAD

**Issue by BoneS38** [StrangeLoopGames/EcoIssues#4481]
I already have done everything on the internet that say something about ECO Server, how to create it, how to forward ports, find ip, manage it and etc.
My server doesn't appear on the server list (join), and when someone try to connect or via IP or Steam Join that happens at console (CMD server):
Error when verifying login token: Could not convert string to boolean: Invalid ticket. Path 'status', line 1, position 26

Not just one friend, but five.
Sorry about my bad english, i'm not a native speaker or even related to the language.

**Comment by MarjieAVolk** [comment]
Hey there - this error message often means that something is wrong with your steam or slg account.  Did you and your friends buy the game on steam, or from our site?

**Comment by BoneS38** [comment]
We've bought from Steam

**Comment by MarjieAVolk** [comment]
Okay - could you give me a steam id of someone who can't log in?

**Comment by BoneS38** [comment]
Ecoex,
steamID: STEAM_0:0:46841543
steamID3: U:1:93683086
steamID64: 76561198053948814

**Comment by MarjieAVolk** [comment]
Oh I should also ask, are any/all of you able to log in to other servers?  And what version of the game is your server running?  It does seem unlikely that all of you would have the same account problem.

**Comment by BoneS38** [comment]
Yes, we can log in to any other servers. That is something i don't know exactly, BUT, i have already created many server from Strange Loop website 7.1.1, and as many as on Steam, Eco Server tool.

**Comment by MarjieAVolk** [comment]
Okay so it seems it is not an account problem in that case.  Sorry about that.

So I've reviewed what else this error message can mean.  (We are working on outputting better error messages, which would help this get resolved a lot more easily).  Do you have Require Authentication turned on on your server?  We did have some weird problems reported from people who turned that off.

**Comment by BoneS38** [comment]
Require Authentication set as 'True'.
One more thing i saw, it still in Network tab since i created for the first time a server: NAT detect error: Failed to generate port mappings.
Already tried putting DetectNAT as 'False', and changed IP Adress from 'Any' to '>MYIP<:3000' and now its back to Any because when i launch the server, it says "Failed to parse IP adress for listen server. Using IPAdress.Any..."

**Comment by MarjieAVolk** [comment]
Aha, well that seems bad.  If this is an ip address problem, I'm going to hand you over to @metachronism

**Comment by BoneS38** [comment]
Ok, thank you for helping me till now!

**Comment by BoneS38** [comment]
Ok, "Failed to parse IP adress for listen server. Using IPAdress.Any..."" still happening, but when one of my friends tries to connect, doesn't appear a single error message at CMD, just appear "Connection Failed' to him

**Comment by MarjieAVolk** [comment]
That is a good thing to know.  Got so many different things that don't give a detailed message O.o

**Comment by BoneS38** [comment]
Yes, that kind weird. Do not even got a single log.txt too.

**Comment by BoneS38** [comment]
Aaaand, we've got another error, i'm laughing to not cry HUAHAUAUHAUHAUA.
Failed to post server listing to remote service: O servidor remoto retornou um erro: (502) Gateway incorreto.

**Comment by BoneS38** [comment]
Sorry about lest sentence. It is something like that: The remote server returned one error: (502) Gateway incorrect.

**Comment by BoneS38** [comment]
Another one for you boys.
Error when verifying login token: O tempo limite da operação foi atingindo. ('The maximum amount of time was reached', or something near that)

**Comment by MarjieAVolk** [comment]
I believe these error messages are due to a Steam outage which is going on right now.

**Comment by BoneS38** [comment]
Ok, seems to be that. Waiting for metachronism then, to see if he can resolve the first problem :/

**Comment by MarjieAVolk** [comment]
Hey, sorry you have been waiting for so long.  You are still having the problem you described at the beginning?  But only for one specific server?  It wasn't resolved after the steam outage got fixed?

**Comment by metachronism** [comment]
this should be resolved after all the auth fixes.  if that is not the case, please reopen
