### ISSUE TITLE
USER ISSUE: Lit Torch to Standing Torch Issue

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4482]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Place Standing Torch
2. Equip Torch on toolbar and in Hand so its lit
3. Drag lit torch to fuel place on Standing Torch

**Expected behavior:**
- Unlite torch, move it from toolbar to Standing Torch and light it.

**Actual behavior:**
- Tool bar torch no longer has graphic and cannot be used, hand cursor locked but can still be used. Item not moved. Standing torch not lit.

**Comment by MarjieAVolk** [comment]
I am not sure if I understand what happened.  So you had your lit torch on your hotbar, and you had the window for the Standing Torch open, on the fuel tab.  You dragged the torch from your hotbar into the Standing Torch's fuel supply.  But then something bad happened.

Was what you saw similar to this, where the torch icon got stuck on the screen?  https://github.com/StrangeLoopGames/EcoIssues/issues/3841

**Comment by wolfie359** [comment]
Nevermind... I just tried to reproduce this issue and it worked fine. If i can make it happen again ill repost. Thanks.
