### ISSUE TITLE
USER ISSUE: Open/Close Table Window Default Tab

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4483]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
1. Open Repair Table
2. Select Containers Tab
3. Close Window
4. Reopen Repair Table

**Expected behavior:**
- Open with Default "Repair" tab.

**Actual behavior:**
- Opens with last used tab.

**Comment by MarjieAVolk** [comment]
This is implemented now :)
