### ISSUE TITLE
"Inventory change". Bug report

### ISSUE THREAD

**Issue by MrSiB** [StrangeLoopGames/EcoIssues#4487]
After the update 7.1.1. our server crashes few seconds after startup.

Приложение: EcoServer.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.InvalidOperationException
   в Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean)
   в Eco.Gameplay.Items.Inventory.Modify(System.Action`1<Eco.Gameplay.Items.IInventoryChangeSet>, Eco.Gameplay.Players.User)
   в Eco.Gameplay.Components.StockpileComponent.TryUpdateInventoryFromWorld()
   в System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   в Eco.Gameplay.Objects.WorldObject.Tick()
   в Eco.Shared.Utils.EnumerableExtensions.ForEach[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   в Eco.Gameplay.Objects.WorldObjectManager.Run()
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4473
