### ISSUE TITLE
Typo in EcoTechTree.csv - Nucler Fuel (also hide it and remove from minting)

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#4488]
![image](https://user-images.githubusercontent.com/32424101/36185599-2c062f7e-118e-11e8-9f3a-742616f9cf22.png)

**Comment by craig-jong** [comment]
this is hidden now.

**Comment by elfl0rd** [comment]
not hidden as i see...
still available in stores list and mint as i see.
![20180901010647_1](https://user-images.githubusercontent.com/4980243/44937823-eb038e80-ad83-11e8-9fc3-5a521a794ab2.jpg)
![20180901010718_1](https://user-images.githubusercontent.com/4980243/44937824-eb038e80-ad83-11e8-91dd-45c28ac04cf3.jpg)

@craig-jong :P

**Comment by elfl0rd** [comment]
@craig-jong appears in 0.8 again.
In addition, you hide "StrangeFuel" but not "NuclearFuel" heh.
![default](https://user-images.githubusercontent.com/4980243/51989134-698d6500-24b7-11e9-981d-6242d1deee3e.png)
