### ISSUE TITLE
USER ISSUE: No Stove in search

### ISSUE THREAD

**Issue by Gilgatex** [StrangeLoopGames/EcoIssues#4495]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
When I search for an item in the store or contract board, I'm looking for the Stove (not cast iron stove). I search for 'stove'

**Expected behavior:**
Both should appear

**Actual behavior:**
Only the cast-iron stove appears.

**Comment by ecoemmeck** [comment]
this maybe because it hasnt been researched as yet. because i can see both on the store search on 7.1.1

**Comment by Gilgatex** [comment]
It was not researched, correct.  In that case this is a feature request more than a bug.

The situation is that I'm about to go to bed, a friend on the server is working on researching it.  I would like to buy it as soon as it's researched and completed, so I want to put it up as wanted in my shop for later, when I'm still offline.

As of right now, I can't.

**Comment by MarjieAVolk** [comment]
Yes, you can't search for things in the store etc until they have been researched in that world.  This is done to prevent an overwhelming list when opening the window for the first time.  But it does seem a lot of people are annoyed by this.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#268
