### ISSUE TITLE
Game won't let me host a server

### ISSUE THREAD

**Issue by McSnacks** [StrangeLoopGames/EcoIssues#4496]
I open the game and hit new, I checklist all three avaible server options and then name my server after which I hit start. Now from this point it always tabs me out and when I tab back in there's no server creation only a blank Eco screen as if I were in the main menu.
![ecofail](https://user-images.githubusercontent.com/36466838/36188834-ab351cdc-1103-11e8-9f37-27bde8fa8e24.png)

**Comment by MarjieAVolk** [comment]
Okay, you've got all those crash files - could you send a couple of those over?

**Comment by McSnacks** [comment]
Sure in the post or directly to you?

**Comment by MarjieAVolk** [comment]
Posting them here would be good, in case someone else works on the issue.

**Comment by McSnacks** [comment]
It's saying they don't support that file :/

**Comment by MarjieAVolk** [comment]
Could you zip them up into a zip file?  If github doesn't support it, you can upload it to a file sharing site such as google drive or drop box and share a link to it.

**Comment by McSnacks** [comment]
Here's a shareable link
https://drive.google.com/file/d/1gYKv_kn5V_q7y2p787KvyZdna3bZr8pZ/view?usp=sharing
https://drive.google.com/file/d/1dbnDMu7AQT2bCS9QxUyQXAq5pCMwc57f/view?usp=sharing
https://drive.google.com/file/d/18LICy9dcOu-5ALxfnnWtjTMLly3iTx6V/view?usp=sharing
https://drive.google.com/file/d/11esBDamaLfBPp_5Q57e4RFMqgja4LcD4/view?usp=sharing
https://drive.google.com/file/d/1Xv2dZP9nJLqNZ6-2k9VqzOnFiBdvxYSe/view?usp=sharing
https://drive.google.com/file/d/1YKycgV5rG0UbqM2WJ4kt5KGaclUX3Ul9/view?usp=sharing
https://drive.google.com/file/d/1lG7yFRynThSr_9cogC-vvmbIUjzAlT8u/view?usp=sharing
https://drive.google.com/file/d/125Dhw-V6oHoz8h0Ywjb-_csr-4hXW9ct/view?usp=sharing
https://drive.google.com/file/d/1QtNviJpMOaTRHYSQhbjoAoPruwVaYhhy/view?usp=sharing
https://drive.google.com/file/d/1VXfM5sOJp2YAgQ4uP-f7ZpfI38VieqN3/view?usp=sharing
https://drive.google.com/file/d/1lfww2xwqKd_KzdOU8jkirqLx2hmHWL0b/view?usp=sharing
https://drive.google.com/file/d/1CAf0pj2uA0pZpEUwA-v28rR9U23tUE9O/view?usp=sharing
https://drive.google.com/file/d/1yYOw9jDN4nebSSOdnm9lBuR_hIuZrBGj/view?usp=sharing
https://drive.google.com/file/d/1RdPd43CGRY2K7qJIjH-pwl-UQSbxumS0/view?usp=sharing
https://drive.google.com/file/d/1bWbpGLMbUgz0m2H8kUFGQsiOJ9tXZYTY/view?usp=sharing
https://drive.google.com/file/d/13MwlGEB_MGCbJyK25lGnEaEmApga1qrd/view?usp=sharing
https://drive.google.com/file/d/1hSAgMncMT1mKIyGVjcn1RD6kzd-egXfR/view?usp=sharing
https://drive.google.com/file/d/1QrGwKNv-lQpIwzXANWx9BuW4BY6hq8vc/view?usp=sharing
https://drive.google.com/file/d/1yjBgPDU5T3Y2wAq6XPjhR3RuuS8aL3pd/view?usp=sharing

**Comment by McSnacks** [comment]
There should be 19 now to choose from

**Comment by MarjieAVolk** [comment]
Thank you!

Looks like they all have the same message:
```
Exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Eco.Server.PluginManager..ctor()
   at Eco.Server.Startup.Start(String[] args)
   at Eco.Server.MainClass.Main(String[] args)
```

**Comment by MarjieAVolk** [comment]
I haven't seen this exact error before, but some people who were having trouble starting a new game found they were able to start a server with the Eco Server tool and connect to that without issue.  Want to try that while we figure out what is wrong?

**Comment by McSnacks** [comment]
Sure I'll try that

**Comment by McSnacks** [comment]
Okay yeah I just attempted to launch it and got the same error with the Tool.

**Comment by MarjieAVolk** [comment]
Okay I googled this... and internet suggests that you may need to update your .NET

**Comment by McSnacks** [comment]
hmm I might look into that

**Comment by McSnacks** [comment]
I do believe that worked

**Comment by McSnacks** [comment]
Yes just launched both successfully :)

**Comment by MarjieAVolk** [comment]
Awesome!

**Comment by McSnacks** [comment]
Thank you for all your help! :)

**Comment by MarjieAVolk** [comment]
No problem :)
