### ISSUE TITLE
USER ISSUE: Default Law breaks the vote

### ISSUE THREAD

**Issue by MasterJochen** [StrangeLoopGames/EcoIssues#4497]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
You cant vote cause by default you need to be a citisen. This system needs the tracking data that you have disabled ^^You cant become a citisin cause you need to be 2 hours online wich will never become true cause you cant track the user online time atm

**Expected behavior:**
Default law should work

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Yeah you are right, this is a big problem O.o  We are working to get stats re-enabled asap.  In the mean time, your admin can user /clearlaws to get rid of it.
