### ISSUE TITLE
USER ISSUE: Items get stuck on the middle of the screen

### ISSUE THREAD

**Issue by TestZombie** [StrangeLoopGames/EcoIssues#4498]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Atleast 1/5 times I drag an item from an inventory slot it closes the inventory & I cant access the item until I restart the game. Gets stuck in the middle of the screen	

**Expected behavior:**
Keep dragging

**Actual behavior:**
Stops dragging, cant access, stuck on screen for very annoying visual bug

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3841

People have reported that minimizing the game and bringing it back up will reset stuck icons.
