### ISSUE TITLE
USER ISSUE: Fell through map

### ISSUE THREAD

**Issue by MorosePeregrine** [StrangeLoopGames/EcoIssues#4499]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
*Random occurance*

**Expected behavior:**
It should have not falled through the map...

**Actual behavior:**
Instead it fell through the map

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4167
