### ISSUE TITLE
Freeze wall rotation

### ISSUE THREAD

**Issue by ciizel** [StrangeLoopGames/EcoIssues#4500]
![image](https://user-images.githubusercontent.com/1397782/36190685-ecf02e8e-119c-11e8-8414-13a40e1f5f83.png)

Please add option to force rotation

**Comment by ciizel** [comment]
![image](https://user-images.githubusercontent.com/1397782/36190796-8a9d3866-119d-11e8-81aa-2033bfc28a60.png)

**Comment by keegan-o** [comment]
This would be a new form with at least 2 new builders for every material to support it-- not prioritizing this for now but we will get there!

**Comment by MarjieAVolk** [comment]
Would it be possible to support this case in the current wall builder though?

**Comment by keegan-o** [comment]
It would be possible to make it so in the above image the walls match themselves a bit more (would mean adding several to lots of rules to the builder), but that's not what is being asked for here. Forcing rotation requires a unique block-type for each rotation.

**Comment by MarjieAVolk** [comment]
Yeah I know that was the suggestion, but the root problem is that the walls don't line up in those shots, so I think either solution would be fine.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#267
