### ISSUE TITLE
Fixed power cart tabs

### ISSUE THREAD

**Issue by ciizel** [StrangeLoopGames/EcoIssues#4501]
![powervart](https://user-images.githubusercontent.com/1397782/36191304-c1de4bce-119f-11e8-9944-b73627c655c6.gif)

Always stay in place even when moving up and down

**Comment by MarjieAVolk** [comment]
I believe this was fixed by the updates to linked inventories, which allows the normal inventory and the fuel supply to be treated completely independently.

**Comment by MarjieAVolk** [comment]
Oops, this fix is not released yet, it will be in 7.6
