### ISSUE TITLE
Stack Sizes Inconsistent 

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4504]
ive noticed stack sizes between stockpiles and carts can be inconsistent.
at the moment it almost makes more sense to mass build carts over stockpiles especially when carts can be modded and stockpiles cant. also carts take up less space

**Comment by metachronism** [comment]
this is intended with stockpiles, as the items in the slots take up physical space
we are looking at adding more methods to quickly transfer items though to help with the drag n drop annoyances
