### ISSUE TITLE
USER ISSUE: Keep beeing disconnected and server crash every 20 minutes or so

### ISSUE THREAD

**Issue by M1r077** [StrangeLoopGames/EcoIssues#4505]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. Build a world sized at 172x172
2. Seeing all player beeing disconnected every 7-10 Minutes
3. Once every few disconnections the server crash	and should be restarted

**Expected behavior:**
It shouldn't happen	

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you attach the logs for your server?  These should be located in '[...]\steamapps\common\Eco Server'

**Comment by MarjieAVolk** [comment]
Closing due to no response.
