### ISSUE TITLE
USER ISSUE: pls ae oe ue

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4507]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**

**Expected behavior:**
german letters pls

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2656

If you want to make a note of specific characters that you want, I can make sure those get added when we address that.
