### ISSUE TITLE
kicked from game while i was afk for 5 mins

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4510]
honestly no clue what caused it..
Caught exception: Collection was modified; enumeration operation may not execute.

**Comment by MarjieAVolk** [comment]
Hm, was there a longer error message, or was that really it?

**Comment by ecoemmeck** [comment]
That was all.
I hit the copy to clipboard and that's all was all it gave me.
I wish I had more info on it for you

**Comment by pamduncan** [comment]
@ecoemmeck look in the servers Dump folder - usually that message is also written out in there and it saves the whole message to a file - often what you see on the disconnect notice is not the full error

**Comment by MarjieAVolk** [comment]
Ya we really need to fix that.

Log files in '[...]\steamapps\common\Eco Server' might help too

**Comment by ecoemmeck** [comment]
i wont be able to give you a dump file as it seems the dump folder has been cleared recently it only goes back as far as 2 days ago. : -(

**Comment by MarjieAVolk** [comment]
Okay, well I'm gonna close this for now.  We are going to make sure to send better error messages in the next patch.
