### ISSUE TITLE
USER ISSUE: stuck between 2 hammer's block

### ISSUE THREAD

**Issue by Antoine115** [StrangeLoopGames/EcoIssues#4512]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1.put a stone block with a hammer 
2.next to him, put a log block with a hammer
3.walk between them

**Expected behavior:**
walk normaly

**Actual behavior:**
get stuck between the blocks

**Comment by Antoine115** [comment]
bonnus this is not my property

**Comment by rsgodkilla** [comment]
use /unstuck ?

**Comment by Antoine115** [comment]
yes but it change nothing :/

**Comment by Antoine115** [comment]
i think i will justt wait the owner of the property and ask him to free me

**Comment by MarjieAVolk** [comment]
/unstuck doesn't get you out?  Which blocks did you place specifically?  Hewn Log and Mortared Stone?  And which variants of them did you place?  Walls?  Or cubes?

**Comment by keegan-o** [comment]
This is asking to be able to walk between two parallel walls which we will probably never add support for-- the colliders already do match them so if there happened to be enough space it would be possible, but I think the intention is for it not to be.

**Comment by MarjieAVolk** [comment]
Oh I thought they were actually getting stuck.  But now I am not sure either.

**Comment by elfl0rd** [comment]
Looks fixed
![default](https://user-images.githubusercontent.com/4980243/41870301-5c1bda9a-78c4-11e8-8948-257a86f82a29.png)

**Comment by GophTheGreat** [comment]
Could not reproduce. Closing.
