### ISSUE TITLE
USER ISSUE: Glass panes not connecting to other building blocks

### ISSUE THREAD

**Issue by UnknownViper** [StrangeLoopGames/EcoIssues#4515]
Seeing as doors just got fixed to "connect" to walls, the problem still exists for glass panes, which don't connect to other types of building blocks, leaving gaps.

![eco_2018-02-14_14-21-05](https://user-images.githubusercontent.com/208539/36206475-c951b13c-1192-11e8-90cf-0edb1d23454e.jpg)

**Comment by ecoemmeck** [comment]
good point. hopefully the devs can fix them. I've noticed a few different block types don't connect properly

**Comment by keegan-o** [comment]
fixed in master
