### ISSUE TITLE
USER ISSUE: [SINGLE PLAYER] StandingTorchObject is not spawn correctly, placeholder shown

### ISSUE THREAD

**Issue by Frag2000** [StrangeLoopGames/EcoIssues#4518]
**Version:** 0.7.1.1 beta staging-12a42dd2

**Steps to Reproduce:**
Just create a StandingTorch object in SinglePlayer ... see screenshot!

![eco standing torch](https://user-images.githubusercontent.com/10600462/36207203-18f91b06-1163-11e8-95f2-69be9dff9860.jpg)

**Comment by MarjieAVolk** [comment]
That's weird, it has been working for me.

**Comment by Frag2000** [comment]
I will regenerate a fresh new world with the latest BETA tonight and will try it out again. I have no mods, simple install.

If I still have the issue I will give you exact repro steps as well as a screenshot of my setup configuration (in case that it would be related to configuration issue). Stay tuned.
