### ISSUE TITLE
World Map: Mac

### ISSUE THREAD

**Issue by GPRatcliffe** [StrangeLoopGames/EcoIssues#452]
Hi Guys,

Don't think anyone has mentioned it yet, but, playing on a Mac the World Map doesn't appear as the planet (simply hollow)
<img width="1296" alt="screen shot 2016-07-07 at 18 50 41" src="https://cloud.githubusercontent.com/assets/13458289/16663484/257750ae-4474-11e6-9e18-2adc901986c4.png">
This is the view of the map from my Mac. Conversely I have played from a PC and couldn't replicate the issue.

Thanks!

**Comment by samjudelson** [comment]
I have the same issue, using OSX 10.11

**Comment by chimericray** [comment]
I have the same issue, using OSX 10.11. Eco version Alpha 4.1

**Comment by GPRatcliffe** [comment]
Sorry, same here, OSX 10.11.5 Alpha 4.1

**Comment by metachronism** [comment]
looks like a geometry shaders issue
