### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by kinegame** [StrangeLoopGames/EcoIssues#4522]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1.777.1550

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of ongoing issues that could be causing this. One thing you can try is deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO. Let me know if that fixes it.

If not, try sending me your server log files, which are in '[...]\steamapps\common\Eco Server'.

Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about. I will still see messages you post here, and I can continue helping you debug if needed.
