### ISSUE TITLE
USER ISSUE: skill points

### ISSUE THREAD

**Issue by tome19188** [StrangeLoopGames/EcoIssues#4524]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**

**Expected behavior:**
logged out for 15h with +48 food and 12.2 House bonus. getting 37 skill points

**Actual behavior:**
logged out for 15h with +48 food and 12.2 House bonus. and just got 8 skill points

**Comment by MarjieAVolk** [comment]
Were you out of calories when you logged back in?

**Comment by tome19188** [comment]
no

**Comment by MarjieAVolk** [comment]
Okay sorry for the delay.  Another question - are you playing on a local server?  If so, the game will not change while you are offline.  You need to leave your server running in order for time on the server to pass.

**Comment by MarjieAVolk** [comment]
Closing as without further information, this is likely either a misunderstanding, or related to one of the other skill points problems we have open (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/4524)
