### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by beardedjon21** [StrangeLoopGames/EcoIssues#4525]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
i went fishing and never recieved a fish

**Expected behavior:**
give me fish	

**Actual behavior:**
didnt give me a fish

**Comment by VAlex0** [comment]
-> see #4588

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
