### ISSUE TITLE
USER ISSUE: Can't move or open items after storage rename

### ISSUE THREAD

**Issue by GitEd** [StrangeLoopGames/EcoIssues#4527]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Open chest, stockpile, fishtrap.  Click on pencil in title bar to change name.  Change name.  Press Return.  Name changes.  

**Expected behavior:**
Able to move and open inventories after changing item name.

**Actual behavior:**
Cannot use WASD to move.  Cannot use E to open item inventories.  Must disconnect and rejoin to be able to move. or

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115

Thanks for the additional example.  If you have any more information about when the issue happens or how to work around it, let me know!
