### ISSUE TITLE
USER ISSUE: Cannot play at all

### ISSUE THREAD

**Issue by De1m0s09** [StrangeLoopGames/EcoIssues#4532]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. Try to join any type of world, create one, or join a server

**Expected behavior:**
It should have given me the opportunity to play

**Actual behavior:**
First changes the main window, showing me Steam or my desk for example, then the following error message popped up when I went back to the game window :
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of ongoing issues that could be causing this. One thing you can try is deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO. Let me know if that fixes it.

If not, try sending me your server log files, which are in '[...]\steamapps\common\Eco Server'.

Going to close this for now, as this is likely related to one of the ongoing connection problems we already know about. I will still see messages you post here, and I can continue helping you debug if needed.

**Comment by De1m0s09** [comment]
Well...it now works normally, without doing anything...quite strange, but
awesome tho, I enjoyed my first hours.

**Comment by MarjieAVolk** [comment]
Huh strange... possibly there was an outage going on.  I believe that was the day of the steam outage >>
