### ISSUE TITLE
USER ISSUE: Not building materials

### ISSUE THREAD

**Issue by rudeirishknight** [StrangeLoopGames/EcoIssues#4536]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
stone, pitch in the intentroy and ordered masonary stone

**Expected behavior:**
process order	

**Actual behavior:**
does not process order

**Comment by MarjieAVolk** [comment]
Take a look at the Status tab on your crafting station.  Does it have a requirement that is not met?

**Comment by rudeirishknight** [comment]
yes all requirements met. the stations were working then all of a sudden stopped all together with exception to the camp fire and workstation outside of the house I buildt

**Comment by MarjieAVolk** [comment]
If they all stopped working at the same time, that really sounds like your room got broken.  You're sure the room still works, and has enough space in it for all the stations?

**Comment by rudeirishknight** [comment]
yes room is still in tack (https://www.twitch.tv/rudeirishknight) I even closed some windows up

**Comment by rudeirishknight** [comment]
nevermind I got it to work

**Comment by MarjieAVolk** [comment]
Okay.  What was the issue?

**Comment by rudeirishknight** [comment]
too many tables in room
