### ISSUE TITLE
Nothing happens when I start a world or load a game

### ISSUE THREAD

**Issue by Nolween** [StrangeLoopGames/EcoIssues#4537]
Hi, 

I succeded to créeate a 1st world, I played about 3 hours,  but when I wanted to load my world, nothing happen, and I can't even back to the main menu, it's stucked to the list of saved game. The only thing which is possible is to press alt + F4 to  close and launch again.
Whatever I do, it's impossible to start or load a game. 
The only thing possible is to join an opened world, but it's not what I want :(

Thanks you

**Comment by MarjieAVolk** [comment]
Could you attach your client error logs?  This should be at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by Nolween** [comment]
Oh yes, excuse me :)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1725530/output_log.txt)

**Comment by Nolween** [comment]
The last update solved my issue ! Thanks you !
