### ISSUE TITLE
USER ISSUE: Torch can't be placed

### ISSUE THREAD

**Issue by mansartesteban** [StrangeLoopGames/EcoIssues#4538]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Have torch in inventory
Try to put a torch on objet like desk/workbench ...	

**Expected behavior:**

**Actual behavior:**
The GUI says me to click "right click to put torches" but by right-clicking, left clicking, pressing "F" or "E" or shift. But nothing to do.

**Comment by MarjieAVolk** [comment]
Ah, yes the 'right click to put torches' indicator is supposed to mean that you can insert the torches into that object's storage.  Unfortunately this sometimes appears even when it is not possible to do that.  (See https://github.com/StrangeLoopGames/EcoIssues/issues/4047)

You can't actually place torches.  What you want is a "Standing Torch".  These can be placed in the world.
