### ISSUE TITLE
 [Suggestion] Carts have owners name not just unauthorised

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4541]
**Version:** 0.7.1.1 beta

Would be nice when coming across a cart that just says "you are not Authorised to use this" to have a players name, this way Carts that players find can then be returned to the Owner, or ask the owner to come and get it.  at the moment if a cart is left blocking somewhere players are stuck not being able to move it, i just had to dig out the road under one and drop it below it to get it around it.

**Comment by MarjieAVolk** [comment]
Oh that is a good idea

**Comment by Conchipedia** [comment]
the names or the burying lost carts? 😄

**Comment by MarjieAVolk** [comment]
The names was what I meant, I guess digging it into a pit is a clever idea too lol

**Comment by Conchipedia** [comment]
can we have a Default Setting of Name always appearing on Cart when it is created?
then we can just change the name afterwards to whatever we need it to be.

Maybe also have the text on carts/vehicles etc being tested against a profanity filter?
(this goes back to the PAX event where we had to tidy up the world and found a Cart with a rude word on it) 😄

**Comment by MarjieAVolk** [comment]
Not sure I understand.  Are you asking for a new name setting for the cart?

**Comment by Conchipedia** [comment]
when a Cart is created the back is blank
![snap2357](https://user-images.githubusercontent.com/29383891/43796429-3183bbe8-9a7c-11e8-8b7b-1639562c0c24.png)
i was thinking about just doing this automatically
![snap2358](https://user-images.githubusercontent.com/29383891/43796609-a4b3bc08-9a7c-11e8-9e34-eed1714b1354.png)

then we can edit the name, also gives rough idea whose it is

**Comment by MarjieAVolk** [comment]
Okay I get it.  Seems reasonable.

**Comment by MarjieAVolk** [comment]
Okay, I just checked and it looks like after the auth updates, the message when interacting with carts does now give the owner's name, as requested.

I am also going to add a profanity filter here.  I think I am going to leave the starting text blank for now, since putting default text on signs and things is kind of odd, and the original problem has already been addressed with the error message.

**Comment by Conchipedia** [comment]
all sounds good, leaving it up to you guys to work your magic ❤️
