### ISSUE TITLE
7.1.2 Severe Login Bug

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4543]
I just updated my server to 7.1.2. The control panel indicates that the server is operating normally, but whenever I try to log in it gives me this error screen:
"Connection Failed"
"Invalid login info."

I have not been able to log onto my server at all since updating to this version and no one else as well.
(I use a commercially hosted killservers.com server)

**Comment by MarjieAVolk** [comment]
Can you log in to other servers?

**Comment by Blanclour** [comment]
No all servers on server list show "0 players" online and I get same error on the other ones I try.

**Comment by en3rgy97** [comment]
[09:47] Invalid user trying to connect: Dummy
[09:47] Disconnecting client [reason: Invalid login info.]...

**Comment by Geuthur** [comment]
same cant login to my server..... :/

**Comment by o-be-one** [comment]
Same for us.

**Comment by MarjieAVolk** [comment]
Okay guys, it seems our auth servers are having trouble.  We are trying to get them back up asap, but in the mean time if you disable Require Authentication on your servers, that should allow you to play.  Let me know if that doesn't work.

**Comment by MarjieAVolk** [comment]
Okay another update - Looks like Steam is actually having an outage right now.  So this is out of our hands.  You all should be able to play with the build you can download from our website, until Steam goes back up.

**Comment by mrb25** [comment]
I just had a friend with the same issue. He uninstalled the game using revo uninstaller and reinstalled and its working fine now. Not sure if that's helpful.

**Comment by foleykt** [comment]
@mrb25 Did your friend have the game installed through Steam?

**Comment by mrb25** [comment]
@foleykt yes, he did

**Comment by foleykt** [comment]
So does that mean that linking a Steam account to a Strange Loop account is not necessary?

**Comment by foleykt** [comment]
I just bought the game today and I've been having this issue. Tried to connect my steam account and the feature is disabled on the website.

**Comment by mrb25** [comment]
Yeah, he was gifted the game through Steam, I believe he does not have a strangeloop account at all.

**Comment by foleykt** [comment]
Can you confirm that downloading revo is necessary to do an uninstall/reinstall? Or will doing it through the Steam app suffice?

**Comment by mrb25** [comment]
He did it with revo. I believe that its necessary to completely clean install it.

**Comment by foleykt** [comment]
Alright, I'll try with Steam first and post here if it works.

**Comment by MarjieAVolk** [comment]
Hey all - sorry, I didn't realize that we have disabled linking an existing steam purchase to an slg account.  This is because we had issues with people buying the game on steam, linking, and then refunding on steam, which let them get the game for free.  So the workaround I suggested earlier does not work

**Comment by MarjieAVolk** [comment]
Closing as this was due to an outage.
