### ISSUE TITLE
USER ISSUE: Server is full

### ISSUE THREAD

**Issue by Asherz0** [StrangeLoopGames/EcoIssues#4546]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Server created allowing friends to join with 1-3 players.

**Expected behavior:**
Allowed my friend to join

**Actual behavior:**
It said "server is full"

**Comment by MarjieAVolk** [comment]
Did you create another world where you did not allow friends to join, after creating this one?  You may be seeing this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3768

If that is the case, try creating another new world where you allow friends to join, and then quitting and reloading the old world.

**Comment by Asherz0** [comment]
Yeah, that did nothing. Still experiencing same issue.

**Comment by MarjieAVolk** [comment]
Sorry for the delay, I was out sick yesterday.

Well what you should be able to do is enter /openserverui, and take a look at the server browser that pops up.  Under the Users tab, select Config and there is a setting called MaxPlayers.  Set that to however many players you want, and then hit ctrl+s.

**Comment by rainfarmer** [comment]
user says:
try logging into my wife's game (we're on the same network) and when I see her server (or private game) i click on "connect" which just leaves me at an in-game error screen saying "Connection Failed server is full".  

Thing's I've tried:
Restarting my computer, restarting Eco, restarting the modem, verifying integrity of game files, and deleting and re-downloading Eco. I'm at a loss.

**Comment by MarjieAVolk** [comment]
Tell them to follow my instructions in the previous message
