### ISSUE TITLE
[Suggestion] Revoke land claims using laws

### ISSUE THREAD

**Issue by CompactDisc** [StrangeLoopGames/EcoIssues#4549]
We have serious issues on our server with people joining the game for an hour, claiming lots of plots and then leaving. There are no logs to see how long they have been inactive, nor are there ways to unclaim all their land at once.

I would propose adding an option to revoke land using laws. So people can automatically lose their land after a certain amount of inactivity.

**Comment by midn8t** [comment]
as a admin i use the admin command remove them, but if u dont have active admin then this is not easy thing deal with, they should add option in tool set to turn on so many days pass then user is deleted along with all items in game from save folder. users

it also be nice to have in tool set option to manually delete users.

https://github.com/StrangeLoopGames/EcoIssues/issues/4597

**Comment by MarjieAVolk** [comment]
You can reduce 'mob rule' with laws also :P  Prevent who can vote, etc.

 We do really need a nicer way of removing property.  The idea of a law for that sounds great to me.  That is something we might even want to include as a default law, eg. if you have played for less than 2 hours and you haven't logged on for 2 days, your property is removed.

**Comment by CompactDisc** [comment]
I would definitely be all for that!

**Comment by D3nnis3n** [comment]
Ah. Yeh, a law is an even better option then a config option.

**Comment by midn8t** [comment]
well with crime and punishment system laws are suppose to be break able latter on.

> You can reduce 'mob rule' with laws also :P Prevent who can vote, etc.

we cant name people yet unless that has changed all can do is say ether admins can vote or create laws or none admins.

**Comment by D3nnis3n** [comment]
I find it quite important to fully reset the Player, e.g. when he joins again he has Default skillpoints, no inventory and the ten 10 claims.

Gesendet von Mail für Windows 10

Von: Steven
Gesendet: Mittwoch, 28. Februar 2018 17:08
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Comment
Betreff: Re: [StrangeLoopGames/EcoIssues] [Suggestion] Revoke land claimsusing laws (#4549)

well with crime and punishment system laws are suppose to be break able latter on.
You can reduce 'mob rule' with laws also :P Prevent who can vote, etc.
we cant name people yet unless that has changed all can do is say ether admins can vote or create laws or none admins.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#265
