### ISSUE TITLE
USER ISSUE: Failure to join server

### ISSUE THREAD

**Issue by Pysk** [StrangeLoopGames/EcoIssues#4550]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Myself and a mate are both attempting to join my game with failure and also having failure with public servers. Nothing has changed in how we normally connect.	

**Expected behavior:**
Connection to server.	

**Actual behavior:**
Gives the error "Failed Login information"

**Comment by lilth21** [comment]
I have the same problem as you
\\ connection failed  invalid login info //
unable to connect to the server !

**Comment by MarjieAVolk** [comment]
I believe this was because of the steam outage that happened that day.  Are you guys still having problems?
