### ISSUE TITLE
(Suggestion) Set of 1 Wide Road Ramps

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4552]
I have noticed on my server and perhaps a few others that they utilize the claim system in designating where roads go. The problem is that claims are 5x5, and road ramps only come in even number denominations 2 wide and 4 wide(for asphalt). This means that road ramps can never be centered on claims and as a result produce asymmetric symmetry.

I suggest a ramp variant for roads that is 1 block wide so that roads can be centered in odd denominations.

**Comment by CompactDisc** [comment]
Yes please! Just have all ramps be 1x4 please =)

**Comment by MarjieAVolk** [comment]
We have been planning to do this, and also to change how ramps work in order to support blending with regular dirt and other terrain (not just roads)

**Comment by CompactDisc** [comment]
I'm glad to hear it :D

**Comment by Blanclour** [comment]
Thank you so much! :)

**Comment by craig-jong** [comment]
This is a suggestion (its in the wrong section atm) but also in our current bleeding edge we have this in. So yay! It need a lot of polish, though.
