### ISSUE TITLE
Doors knock you to space.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#4553]
8) Buggy doors. If you placed a door and someone tries to open it while you are near it, YOU WILL GO TO :hearts::hearts::hearts::hearts:ING SPACE, yep, thats right, you can be a tesla and fly to the space if a door is opened in your character hitbox, which anyway is pretty weird compared to the door itself. Maybe fix this issue?

**Comment by MarjieAVolk** [comment]
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4140
