### ISSUE TITLE
USER ISSUE: Work Order Doesn't finish when it dumps into stock pile

### ISSUE THREAD

**Issue by KylKlatt** [StrangeLoopGames/EcoIssues#4557]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stone Mason table near stock pile
Make Stone Mason Queue
Finishes Queue
Won't let you collect, need to cancel once it's done.

**Expected behavior:**
Queue Ends when Itts done

**Actual behavior:**
Stays at 100% and needs to be canceled to open the queue slot

**Comment by Quicksilv3r710** [comment]
I can confirm this, happens to me all of the time with the masonry table.

**Comment by WeaselDog** [comment]
This is no longer an issue with new crafting system.
