### ISSUE TITLE
[7.1.2] Eco game client on Linux hangs on startup, then fails

### ISSUE THREAD

**Issue by KitRedgrave** [StrangeLoopGames/EcoIssues#4558]
In this latest iteration of the game, when I try to start it up it just hangs not drawing anything to the screen for a good 15 seconds and then crashes to desktop.

The program had this to say out onto stdout/stderr:
```
Set current directory to /home/kit/.steam/steam/steamapps/common/Eco
Found path: /home/kit/.steam/steam/steamapps/common/Eco/Eco.x86_64
Mono path[0] = '/home/kit/.steam/steam/steamapps/common/Eco/Eco_Data/Managed'
Mono config path = '/home/kit/.steam/steam/steamapps/common/Eco/Eco_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libCSteamworks.so'
Preloaded 'libsteam_api.so'
Unable to preload the following plugins:
	ScreenSelector.so
	libCSteamworks.so
	libsteam_api.so
Logging to /home/kit/.config/unity3d/Strange Loop Games/Eco/Player.log
Assert( Assertion Failed: fatal stalled cross-thread pipe ):../common/pipes.cpp:770

assert_20180214222654_2.dmp[24377]: Uploading dump (out-of-process)
/tmp/dumps/assert_20180214222654_2.dmp
assert_20180214222654_2.dmp[24377]: Finished uploading minidump (out-of-process): success = no
assert_20180214222654_2.dmp[24377]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20180214222654_2.dmp[24377]: file ''/tmp/dumps/assert_20180214222654_2.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
```

I had a look at Player.log and there wasn't too much of interest there, but I can paste what I got in there if you need it.

Managed to recover the dump this was supposed to upload to you, and I'm attaching it to this issue.

[eco_dump.tar.gz](https://github.com/StrangeLoopGames/EcoIssues/files/1726419/eco_dump.tar.gz)

**Comment by KitRedgrave** [comment]
The darndest thing is I rebooted my computer, and now it works... so this must be one of those rare and hard-to-pin-down ones.

**Comment by Simonmicro** [comment]
I've got that error too. But before I was supposed to create amnually a stem_appid.txt file. Strange...

**Comment by rainfarmer** [comment]
+1

Im trying to run ECO on a Linux Arch 64bit system. Ich linked my strangeloopgames account to steam and running the game in console it gives following output:

Set current directory to /home/elias/Games/ECO
Found path: /home/elias/Games/ECO/Eco.x86
Mono path[0] = '/home/elias/Games/ECO/Eco_Data/Managed'
Mono config path = '/home/elias/Games/ECO/Eco_Data/Mono/etc'
Preloaded 'libCSteamworks.so'
Preloaded 'libsteam_api.so'
Unable to preload the following plugins:
    ScreenSelector.so
    ScreenSelector.so
    libCSteamworks.so
    libsteam_api.so
Logging to /home/elias/.config/unity3d/Strange Loop Games/Eco/Player.log
Setting breakpad minidump AppID = 382310
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198448902908 [API loaded no]

**Comment by Simonmicro** [comment]
-1
Well, the bug simply disappeared after several reboots, an kernel switch (to 4.10.XXX), a relogin with reinstallation of steam and some other things I've done in the last days. Very annoying. I don't know what you need to do to bring your game up running again.
See you,
Simonmicro

**Comment by SlayksWood** [comment]
Seems fixed.
