### ISSUE TITLE
Limiting Simultaneous Operation of Multiple (10+) Workstations

### ISSUE THREAD

**Issue by Cerzi** [StrangeLoopGames/EcoIssues#4560]
One person with maxed out relevant skills is able to set large work projects (eg >999) on workstations all across the world, which can then be used by other unskilled individuals by simply loading raw materials into the project, and claiming the output.  The skilled individual that began all of these projects can effectively leave the game afterwards, only to come back when a project needs changing (which should be rarely or never, if enough workstations are being utilzied with large enough projects)
An example would be a kitchen being set up in a baker's house, in which the baker doesn't have advanced cooking but needs yeast.  They get the one guy with advanced cooking to come set a project for 99999 yeast, and from that point onwards the baker has all the yeast he'll ever need, without any further interaction with the cook

To fix this I suggest either putting a hard cap on how many stations a single player can have active projects on OR more radically only allow workstations to actually work if the player is within a certain radius (remembering log off location).  This means a player who logs off in his house will still have all his workstations producing overnight, but can't have workstations all over town doing stuff.

**Comment by ecoemmeck** [comment]
there is a problem with your remembering area of log out idea.
what if say they have a blast furnace set far enough away to not be counted in the area but they also have projects going on in their home for things that dont pollute they could only have 1 area producing things

**Comment by MarjieAVolk** [comment]
I would suggest instead limiting the size of projects.  Maybe the cap should be 50 or 20 objects.

**Comment by MarjieAVolk** [comment]
Seems like there's a much higher cost to build another workbench than to queue up a bigger project.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#264
