### ISSUE TITLE
[Suggestion]More resource sinks

### ISSUE THREAD

**Issue by Cerzi** [StrangeLoopGames/EcoIssues#4561]
Currently there are two main resource sinks: food consumption & equipment repairing.  I'd like to suggest increasing the number of sinks in order to ensure more areas of the economy have continued purpose as the game progresses.

As it stands once everyone has +50 from housing, a lot of jobs basically die off.  Same with carts which only need replacing very rarely due to bug or "user error".  This also means resource consumption goes down for the associated materials.

What if buildings and furniture needed regular repairs/maintenance?  It would of course have to be carefully balanced to not become a)overly demanding or b)overly resource-draining, but it would be great to see some version of this implemented.  Especially if there was a skill for "efficient repairwork", allowing builders that spec into such a skill to offer their services as repairmen who consume less resources per task.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#263
