### ISSUE TITLE
USER ISSUE: borderless window mode pls

### ISSUE THREAD

**Issue by ownyHD** [StrangeLoopGames/EcoIssues#4562]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by UnknownViper** [comment]
I would very much like to see this as well. For Windows at least it's a pretty simple thing to remove the border and title bar, as well as have a focus handler that sets always on top appropriately.

**Comment by SeanAtr0n** [comment]
You can make glass out of sand, isn't that borderless?

**Comment by UnknownViper** [comment]
We're talking about running the game in windowed borderless mode, or fullscreen windowed as it's also called.

**Comment by MarjieAVolk** [comment]
I believe we already have that - we have a fullscreen option in the 'resolution' section of the escape menu.

**Comment by SeanAtr0n** [comment]
Ahh, yeah it'd be nice to have... borderless windowed is different than fullscreen or maximized window

**Comment by UnknownViper** [comment]
The current fullscreen implementation currently acts like exclusive fullscreen, meaning if you tab out of the game it disappears. It does so very quickly, so I'm not sure if it is actually exclusive fullscreen. The behaviour of the game going away when in fullscreen windowed mode is certainly not the norm, nor the wanted behaviour I believe most users are looking for. :)

**Comment by SeanAtr0n** [comment]
fixed in 7.4
