### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by ThEViLWoLF** [StrangeLoopGames/EcoIssues#4566]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
quand je fait sur new, je crais et ça me marque "connection failed"

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
