### ISSUE TITLE
USER ISSUE: Cant get cart up ramp

### ISSUE THREAD

**Issue by Tyler-Spencer** [StrangeLoopGames/EcoIssues#4567]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
Build a small wooden cart.

build dirt ramps.

cry, because you spent all that time and skills to get dirt ramps and they dont work

**Expected behavior:**
cart should be able to roll up ramp

**Actual behavior:**
cart gets stuck at the top/end of ramp.

**Comment by Thyriel** [comment]
you need roads at the end of a ramp to get carts up when pulling.
Otherwise you can pull them to get over the gap

**Comment by Tyler-Spencer** [comment]
Seems like poor design/a bug that textures with dirt don’t blend. Tossing some hewn logs in works.  But it isn’t intuitive.

**Comment by MarjieAVolk** [comment]
Yes, you need to make a road at the top of the ramp, this will solve the connecting issues.

We're aware this is clumsy right now, and we hope to improve it.  We may rework how ramps work soon, which would address this.
