### ISSUE TITLE
Update to 7.1.2 broke a stack of torches

### ISSUE THREAD

**Issue by Halostar529** [StrangeLoopGames/EcoIssues#4570]
My game updated from 7.1.1 to 7.1.2. I had a stack of torches when the game updated and now I cant move the stack around or out of my inventory nor can I split the stack.

**Comment by MarjieAVolk** [comment]
Hey, sorry we lost track of this for so long.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/6598 now, since that's the more recent version of this same issue.
