### ISSUE TITLE
USER ISSUE: carpentry table do dont produce anything

### ISSUE THREAD

**Issue by megs24** [StrangeLoopGames/EcoIssues#4572]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
set a alone party and get carpentry basic functions
put a carpentry table in place
try to make boards or anything
see the work in wait list but nothing gone

**Expected behavior:**
the table work perfectly and start to work when order ( have is forgot something ?)

**Actual behavior:**
the table produce nothing

**Comment by ecoemmeck** [comment]
Have you checked the stats tab on the table?

**Comment by MarjieAVolk** [comment]
I'm guessing that one of the requirements listed on the Status tab for the Carpentry Table is not met.  Closing for now.
