### ISSUE TITLE
Unstable ecosystem because of plant space requirements

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4577]
The "feature" that plants have space requirements bigger then the one block they are growing on is leading to some pretty big side effects.
Players should be the important impact on the ecosystem stability but that feature renders it instable on it's own. Plants spread out and go dead because of nearby plants. Without player interaction (digging the dead plants out to make new space) plants are killing each other in their natural territory. Animals eat the rest and after quite some time, without any player interaction, parts of the ecosystem begin to go extinct just by themself.
That doesn't make sense to me.

And as another sideeffect: It's pretty unrealistic that you need to leave huge empty spaces between plants on a field. Fields are typically very crowded in reality.

**Comment by midn8t** [comment]
u know me and my freind can not figure out space requirements for plants.

for example we cleared a 5x5 a 10x10 and a 20x20 area only had one plant in center, in all cases it said other plants where to close.

even plants in wild seem to have this issue.

**Comment by Thyriel** [comment]
Found a way to deactivate overcrowd:

In ecosim.eco config each plant has an entry like that:
"CapacityLayerName": "ShrubSpace",
                  "ConsumedCapacityPerPop": 4.0


change 4.0 (or whatever is in there) to 1.0 (not lower !) and they don't die of overcrowding (but the soil sampler still shows them as overcrowded).
If you want to reduce chance of plants die because of bad soil / temp / moisture reduce "MaxDeathRate" (must be bigger 0 or all will die)

For example how a field with >80% condition soil for wheat looks like on my server after ~14 hours (i too increased growing time to ~12 hours to balance it better with the deactivated overcrowd): http://steamcommunity.com/sharedfiles/filedetails/?id=1302883692
Only a couple plants died instead half the field

**Comment by Thyriel** [comment]
**Just an idea for a far better solution:**
- Change overcrowd effect from killing plants to reduce drops
- add a farmer skill to reduce overcrowd effect while planting, so a skilled farmer can make fields with plants on every field

This way overcrowd effect would still be in the game but wouldn't teach people that nature can't maintain itself without human interaction in an educational game.

**Comment by MarjieAVolk** [comment]
This is a new concept, and we are still adjusting it.  You are right that the ecosystem should not just die on its own.  But FYI plants require more space if they are in a subpar environment. If you adjust water levels to match what the plant likes, or find a space that is a closer temperature, then the plant will require less space.

**Comment by midn8t** [comment]
this could be a bug then cuz plants that are in prefect environment still say overcrowded all the time.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#262
