### ISSUE TITLE
Workbench - Disabled Message showing (minor)

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#458]
Alpha 4.1

Workbench - Disabled Message bug

Requirement/Reproduction:
Req: Disabled Workbench.

Actions: 
Open (E)
Hover over Workbench - Disabled until hover message appears (Building Requirements).
Tab
Turn away (don't move) Workbench Interface needs to stay open.
Tab
Close Workbench interface.

The Workbench disabled - Building Requirements Message will now be disabled like in image below and follow cursor.
Stage 2:
Press Tab and enjoy your detached message.

![image](https://cloud.githubusercontent.com/assets/10489431/16677628/c9928dbc-44a5-11e6-949f-4f202a4aacda.png)

**Comment by metachronism** [comment]
alpha 5 fixes this
