### ISSUE TITLE
USER ISSUE: Glitch

### ISSUE THREAD

**Issue by Jockel380** [StrangeLoopGames/EcoIssues#4580]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Floor / foundation of stone. Stone staircase connected. When the player enters the foundation / room, no problem. If the player wants to leave the foundation / space, the player falls into infinity
. If the player moves on (w a s d), after a short while he will be set to the point he wanted to reach

**Expected behavior:**
Player should be able to leave the foundation / room via the stone staircase.

**Actual behavior:**
The player falls into infinity

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4924

If you have some screenshots of the place where you fall through, that might be helpful.
