### ISSUE TITLE
(Bug) Wind Turbine

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4582]
the wind turbine has no texture
![image](https://user-images.githubusercontent.com/29722757/36256480-4c78b8d4-12a7-11e8-9fb1-07ef7c4037c4.png)

**Comment by keegan-o** [comment]
Not sure how to repro this. If anyone can let me know.

**Comment by MarjieAVolk** [comment]
In that case, @ecoemmeck does running validate game files via steam fix this issue?

**Comment by ecoemmeck** [comment]
ive just tested this on my private server and i can see the texture fine so it might have an error on a file on our main servers we run or it might have a conflict with a mod we are running

**Comment by SeanAtr0n** [comment]
sounds like it was a mod
