### ISSUE TITLE
housing items placement order matters, not remembered on server restart

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#4583]
The order in which different housing items are placed matters for diminishing returns. A medium rug placed before a small run is worth more than if placed in the opposite order. But on a server restart, it seems almost random how the placement order gets redetermined, forcing users to pick up and re-place every item in their house to re-achieve optimum skill gain bonus. This placement order should be remembered through a restart.

**Comment by Cerzi** [comment]
Yeah this is particularly annoying when you have 10+ rooms and a server restart shuffles the order of every room.  Takes a good 5 minutes picking things up and re-placing to get the order correct.

Honestly I think the order needs to just be established automatically, not based on sequence of placement.  Stuff worth the most goes at the top of the list for maximum value. 

The only reason I can think of for the player wanting control over this is to balance out values more, but it's an incredibly gamey way of doing things - instead the player should be encouraged to just add/remove other furniture across the building.

**Comment by egburr** [comment]
I agree. Automatic would be better than the player gaming it out by sequencing the placement.

**Comment by MarjieAVolk** [comment]
Ah yes, the order should be calculated to give you the maximum value probably.

**Comment by tlobig** [comment]
It's propably even more annoying when you play single player and restart the server with every session.

**Comment by thibaut-fagart** [comment]
I concurr with the above :) I have to relayout my rooms on every session (solo play)

**Comment by jhostmeyer** [comment]
Would love to see this bug fixed as well! Very frustrating to have to reset the whole house after the server restarts.

**Comment by johnkslg** [comment]
Order no longer matters, fixed.
