### ISSUE TITLE
[Suggestion] Adding VOIP

### ISSUE THREAD

**Issue by WildJester** [StrangeLoopGames/EcoIssues#4586]
Hello, I would like to suggest adding in the future the in-game voice chat (VOIP) feature. It can be easier to communicate with other players closer to you (an admin could set the range to hear someone talking). I mean, it can be more practical than using the text chat in some situations.

**Comment by ecoemmeck** [comment]
Thus would be nice. However most servers have discord for this function and the ability to have server info and be able to talk to each other while out of game

**Comment by WildJester** [comment]
True. Still should be a good feature, for whoever does not use Discord hehe :).

**Comment by MarjieAVolk** [comment]
I doubt we will support this, as there are lots of existing tools for this sort of thing.

**Comment by KPInc425** [comment]
Would love to see this Feature as I see massive RP potential in this game, and discord won't cut it for that. :)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#261
