### ISSUE TITLE
USER ISSUE: Fishing w. a Pole

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#4588]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
(in a shallow stream) Cast, Wait for bite, reel in... Disconnect, reconnect	

**Expected behavior:**
Fish appear in inventory	

**Actual behavior:**
Have to reconnect to recieve fish

**Comment by VAlex0** [comment]
@craig-jong the fish is kind of glitched in the inventory, when you drag e.g. a pickaxe over the fish, you get a fish with the hp-bar of the pickaxe. and a pickaxe with no hp-bar 😄

**Comment by craig-jong** [comment]
Fish is in the inventory on the server side but not in the client view.
Sleeping the server thread for 100 ms "fixes" it.

Client RPC calls "FinalizeCatch" @ line 149 in FishingController.cs
FinalizeCatch is on FishingPoleItem.cs in mods.

Can increase speed of catch by changing searchInterval in FishingController to some tiny number.

**Comment by craig-jong** [comment]
fixed in staging
