### ISSUE TITLE
Game client don't work on MacOS by steam

### ISSUE THREAD

**Issue by Zaazik** [StrangeLoopGames/EcoIssues#4589]
Hello guys.
My pc 
![screen shot 2018-02-13 at 5 05 42 pm](https://user-images.githubusercontent.com/17027851/36263335-b2e036c2-1272-11e8-90f3-877d30c281c2.png)
Im trying run ECO from steam on Mac 
And after installing and running game its not responding 
![screen shot 2018-02-15 at 4 53 58 pm](https://user-images.githubusercontent.com/17027851/36263386-cc8f4e96-1272-11e8-92f8-cd5ca3d71560.png)
Plz help me or fix that.

**Comment by SeanAtr0n** [comment]
could you send us your log file? ~/Library/Logs/Unity/Player.log

**Comment by shinaka** [comment]
I am having what I assume to be the same issue, although while grabbing my log just now, I left the game running in the background for the better part of 10 minutes and it actually did eventually unfreeze. I've included my Player.log below:

> Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
> GfxDevice: creating device client; threaded=1
> Renderer: AMD Radeon Pro 455 OpenGL Engine
> Vendor:   ATI Technologies Inc.
> Version:  4.1 ATI-1.58.32
> GLES:     0
>  GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable G
> L_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
> OPENGL LOG: Creating OpenGL 4.1 graphics device ; Context level  <OpenGL 4.1> ; Context handle 59907072
> Begin MonoManager ReloadAssembly
> - Completed reload, in  0.152 seconds
> WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.
> WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.
> The referenced script on this Behaviour (Game Object 'Contents') is missing!
>  
> (Filename:  Line: 1758)
> 
> WARNING: Shader Unsupported: 'Hidden/SEGI' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/SEGI' - Setting to default shader.
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDBACK' has no vertex shader
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARD' has no vertex shader
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
> WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - All passes removed
> WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Setting to default shader.
> WARNING: Shader Unsupported: 'Hidden/SEGIRenderSunDepth' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/Post FX/Temporal Anti-aliasing' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/Post FX/Depth Of Field' - Pass 'COC TEMPORAL FILTER' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Pass '' has no vertex shader
> WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Setting to default shader.
> Setting up 4 worker threads for Enlighten.
>   Thread -> id: 7000086cf000 -> priority: 1 
>   Thread -> id: 700008752000 -> priority: 1 
>   Thread -> id: 7000087d5000 -> priority: 1 
>   Thread -> id: 700008858000 -> priority: 1 
> UnloadTime: 4.111351 ms
> Setting breakpad minidump AppID = 382310
> Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197970325372 [API loaded no]
> RPC lookup took: 23563.462ms
>  
> (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 
> The given primitive topology does not match with the topology expected by the geometry shader
>  
> (Filename:  Line: 0)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)
> 
> -------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
> WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
> ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
> ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader
> 
> 
> 
>  
> (Filename:  Line: 668)
> 
> Note: Creation of internal variant of shader 'Curved/Minimap' failed.
> ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
>  
> (Filename:  Line: 438)

**Comment by JonLim** [comment]
Like @shinaka, I let the game hang for some minutes and it eventually got to the title screen and let me play the game for a bit.

Let me know if you'd like my `Player.log` entries as well.

Thanks!

**Comment by SeanAtr0n** [comment]
fixed a while back
