### ISSUE TITLE
USER ISSUE: Suggestion - live stock

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4590]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Animals like cows, horses  chickens

so can have plows - and get milk from cows and meat the animal manure could be used for fertilizer like in real life, and then could have crop of alf alfa that like in real life puts nitrogen in the soil grows almost anyways dost need as much water due to deep root system - turns into hay for live stock.

also then could hook up plows to the horses or machines to horses to save on cost of planting and harvest.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Assigning to @knexer for the suggestion about alfalfa

We are planning on adding animal husbandry before leaving early access :)

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/8
