### ISSUE TITLE
Getting rid of an item

### ISSUE THREAD

**Issue by Frag2000** [StrangeLoopGames/EcoIssues#4591]
Hi guys,

I am not sure if it was reported already but I did not find anything thru searches.

We need a little something to be able to get rid of unwanted items. It becomes a serious pain to manage unwanted items in storage boxes instead of simply getting rid of those.

That game is peaceful and so nice, but not being able to get rid of items is getting seriously annoying/time consumming ...and more and more over time as our inventory grows.

Please add a trash can object so we could drop the item in (like we do for table) ...or any other way.

_[Added]_

**Consider this case **... you are in a middle of a forest, far from your base camp and you end up with full inventory. You stumble on something that you REALLY want to collect, but you can't because your inventory is full. You could get rid of that broken wooden shovel to loot that freshly new killed buffalo ... but you can't. Your only option is to walk back to camp ...

This is a very basic feature and its impact is critical...

Thanks!

**Comment by Huntermeign** [comment]
Discraded trash is already being worked on afaik.

**Comment by Frag2000** [comment]
If it is the case, this is indeed an awesome news :)

**Comment by MarjieAVolk** [comment]
Yes, we are working on a trash feature now.  It will not be in the next release, but it may be in two releases from now.
