### ISSUE TITLE
USER ISSUE: Memory leak

### ISSUE THREAD

**Issue by Naheulf** [StrangeLoopGames/EcoIssues#4593]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1 Connect to a(nother) world
2 Move in this world
3 Disconnect and return to 1

**Expected behavior:**
On game home menu memory used sould be constant

**Actual behavior:**
After few connect/disconnect eco use lot of more memory than at his start (~3Go instead of ~600Mo)

**Comment by johnkslg** [comment]
Negative reviewing user:
HitoryLP: my ram was going up to 8 GB and the game startet to lag
HitoryLP: yeah I set everything as low as possible but still than frezzes

Raising this back to high priority.

**Comment by metachronism** [comment]
high memory usage doesnt affect performance of the client, but nevertheless, I've improved this with pending changes (will be in 8.0+)
