### ISSUE TITLE
USER ISSUE: Server folder missing

### ISSUE THREAD

**Issue by Ooks-kevinvan** [StrangeLoopGames/EcoIssues#4594]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
NEW
>select the options
>START

**Expected behavior:**
No server folder in Eco_Data folder

**Actual behavior:**
The following error message popped up:
``Could not create save file: /media/kevin/DD2/Steam/steamapps/common/Eco/Eco_Data/Server/Storage/DefaultWorld does not exist`
```

**Comment by MarjieAVolk** [comment]
It sounds like you have deleted your DefaultWorld file.  I would suggest reinstalling the game, or if you have it in your recycle bin maybe you can restore it.

If you don't want to use the default world, you can check 'Generate new world' while creating a new world, which should also get you around this error.

**Comment by Ooks-kevinvan** [comment]
I'm running under Linux Mint 18.1
I've install a wine version of the game and copy the windows Server folder to the Linux version.
But, I see the EcoServer.exe don't run on both (crash on wine, and do nothing on linux)
Did exist an EcoServer.exe for Linux?
Did you want to see the log of the wine crash?

**Comment by Ooks-kevinvan** [comment]
``Unhandled exception: page fault on read access to 0x00400000 in 64-bit code (0x0000000000400000).
Register dump:
 rip:0000000000400000 rsp:000000000023fdd8 rbp:000000000023ffd0 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000400000 rbx:0000000000000000 rcx:00007fffffeaf000 rdx:0000000000000000
 rsi:0000000000000000 rdi:000000000023fe40  r8:000000000023fd00  r9:0000000000000008 r10:0000000000000008
 r11:0000000000000246 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000000023fdd8:  000000007b47a4a8 0000000000000000
0x000000000023fde8:  0000000000000000 0000000000000000
0x000000000023fdf8:  0000000000000000 0000000000400000
0x000000000023fe08:  00007fffffeaf000 0000000000000000
0x000000000023fe18:  0000000000000000 ffffffffffffffff
0x000000000023fe28:  000000007b4a6f80 000000007b44c240
0x000000000023fe38:  0000000000000000 0000000000000000
0x000000000023fe48:  100f48bd28ce1f99 0000000000000000
0x000000000023fe58:  0000000000000000 0000000000000000
0x000000000023fe68:  0000000000000000 100f48bd2cae1f99
0x000000000023fe78:  100fbe759f1e1f99 0000000000000000
0x000000000023fe88:  0000000000000000 0000000000000000
Backtrace:
=>0 0x0000000000400000 EntryPoint() in ecoserver (0x000000000023ffd0)
  1 0x000000007b47a4a8 in kernel32 (+0x5a4a7) (0x000000000023ffd0)
0x0000000000400000 EntryPoint in ecoserver: popq	%r10
Modules:
Module	Address					Debug info	Name (18 modules)
PE	          400000-          7aa000	Export          ecoserver
ELF	        7b400000-        7b819000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b819000	\               kernel32
ELF	        7bc00000-        7bd1e000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd1e000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
ELF	    7fa021f93000-    7fa0221a5000	Deferred        libnss_files.so.2
ELF	    7fa0221ab000-    7fa0223b7000	Deferred        libnss_nis.so.2
ELF	    7fa0223bb000-    7fa0225d4000	Deferred        libnsl.so.1
ELF	    7fa0225db000-    7fa0227e4000	Deferred        libnss_compat.so.2
ELF	    7fa022ccb000-    7fa022ee1000	Deferred        libgcc_s.so.1
ELF	    7fa022ee3000-    7fa0231ec000	Deferred        libm.so.6
ELF	    7fa02321b000-    7fa02341f000	Deferred        libdl.so.2
ELF	    7fa023423000-    7fa0237ed000	Deferred        libc.so.6
ELF	    7fa0237f3000-    7fa023a10000	Deferred        libpthread.so.0
ELF	    7fa023a3b000-    7fa023de1000	Dwarf           libwine.so.1
ELF	    7fa023de3000-    7fa02400b000	Deferred        ld-linux-x86-64.so.2
ELF	    7ffd0c70e000-    7ffd0c70f000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000028    0
	00000023    0
	0000001e    0
	00000018    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001d    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	00000020    0
	0000001f    0
	0000001c    0
00000021 winedevice.exe
	0000002e    0
	00000025    0
	00000024    0
	00000022    0
00000026 explorer.exe
	0000002d    0
	0000002c    0
	0000002b    0
	00000027    0
0000002f Steam.exe
	00000087    0
	00000086    0
	0000007d    0
	0000007c    0
	0000007b    0
	0000007a    0
	00000079    0
	00000078    0
	00000077    0
	00000076    0
	00000075    0
	00000056    0
	00000053    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000042    1
	0000003f    0
	0000003d    0
	0000003c    0
	0000003b    0
	00000037    0
	00000036    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
00000034 steamwebhelper.exe
	00000072    0
	00000071    0
	00000070    0
	0000006e    0
	0000006c    0
	0000006b    0
	0000006a    0
	00000069   -2
	00000068    0
	00000067    0
	00000066    0
	00000065    0
	00000064    0
	00000063    0
	00000061    0
	00000060   -2
	0000005f   -2
	0000005e    0
	0000005d    0
	0000005c    0
	0000005b    0
	0000005a    0
	00000059    0
	00000058    0
	00000057    0
	00000052    0
	00000035    0
00000038 steamwebhelper.exe
	00000051    0
	00000050    0
	0000004e    0
	0000004d    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000039    0
00000095 (D) Z:\media\kevin\DD2\Steam\steamapps\common\Eco\Eco_Data\Server\EcoServer.exe
	00000096    0 <==
00000097 wineconsole.exe
	00000098    0
System information:
    Wine build: wine-3.0
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 4.13.0-32-generic

**Comment by MarjieAVolk** [comment]
Ah, the eco server does mostly/kind of work on linux, as I understand it, but I believe there is some special setup you have to do to get it to work.  Something about Mono?

**Comment by Ooks-kevinvan** [comment]
Now, I can connect correctly on another server under the linux version.
