### ISSUE TITLE
USER ISSUE: Can't Login

### ISSUE THREAD

**Issue by ImAHumanThing** [StrangeLoopGames/EcoIssues#4596]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Launched the game-
Entered my username and password-

**Expected behavior:**
Logged me in

**Actual behavior:**
"Invalid username or password"

**Comment by MarjieAVolk** [comment]
Are you entering your strange loop username and password?  If you aren't able to log in to your strange loop account, you should contact support@strangeloopgames.com.

If you are running the game through steam, and you see the login screen pop up, this means that something has gone wrong with your steam login.  In that case, you might want to try logging in and out of steam or restarting steam.

**Comment by MarjieAVolk** [comment]
Closing due to no response.
