### ISSUE TITLE
USER ISSUE: Question/Suggetion Dedicated Toolset Server

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4597]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Alot of users in game that do not play, 

I know about the /whois command to get ID and that I can find those users in the Storage game.eco zip users folder

there listed there I am wondering what would happen if i deleted those users from that file, would it have illeffect on the game world ? after words and or if there is better way to remove users other then unclaiming there plots.

so that if they rejoin game they have to start over agin..

is there admin command to delete there user file log from the world, along with all claims and items ?

I hate missing with the game.eco saved file outright cuz then i have to bring server up and down along with sometimes it created loading errors.

for example putting in a custom welcome message to display server rules.

which also be welcome addition to the dedicated tool set  - I have had to ban 4 people off of our server due to harassment and I like to put statement about that in the welcome message.

along with ability to remove un-active players from the game world completely with out banning.

**Expected behavior:**

**Actual behavior:**

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#259
