### ISSUE TITLE
missing tooltips description

### ISSUE THREAD

**Issue by Vinz7** [StrangeLoopGames/EcoIssues#4600]
Version: 0.7.1.2 beta
Dedicated server.
All the players on the server have the same missing tooltips in skills selection.
https://imgur.com/utmtjBX

Some items display error instead of description.
https://imgur.com/vFQNjRV

I tried to push server files from fresh download, but the problem is still here

**Comment by MarjieAVolk** [comment]
Are you on a linux server by chance?

**Comment by Vinz7** [comment]
I just got the information from our Host support.
The server is running on Linux CentOS 7.0

**Comment by LiaungYip** [comment]
If this is on a Linux server, this issue is a duplicate of #2084.

**Comment by MarjieAVolk** [comment]
Indeed, Linux has some trouble with tooltips.  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/2084
