### ISSUE TITLE
[Bug] Disable stairs block auto rotation

### ISSUE THREAD

**Issue by fenume** [StrangeLoopGames/EcoIssues#4603]
Trying to build 2x2 circular staircase to mine: setting stairs blocks each -1 level and 90% turn, most blocks appear as expected, but some change direction randomly. 
Build preview https://i.imgur.com/kTFBitB.jpg
Builded block https://i.imgur.com/Z9gmAnx.jpg

**Comment by UnknownViper** [comment]
For now you can work around this by placing a temporary block below when placing the stairs.

**Comment by keegan-o** [comment]
Un-assigned myself after double checking the builders-- they are one rule with no rotations checked.

**Comment by craig-jong** [comment]
I can't get this to reproduce at all. We've made some changes to how blocks are placed, so I'm going to close this.

If it occurs in a more recent version of the game, feel free to reopen it and I'll take another look.
