### ISSUE TITLE
suggestion: BOATS are required

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4606]
it would be nice if we could make boats for travelling items across oceans instead of making roads with carts or to do fishing further out as not many fish near the shores :( plus they would also cause pollution so it would show that water travel is also sometimes bad for environment.

**Comment by ecoemmeck** [comment]
As far as I'm aware the devs have boats on the road map for the games development.
There would need to be at least 2 types of boats. rowboats and engine powered boats the latter being faster and requiring minimal calorie usage

**Comment by MarjieAVolk** [comment]
Thanks for the suggestion!  Yes, we are already planning to add boats, just a matter of when we can sneak it in :P
