### ISSUE TITLE
USER ISSUE: Blast Furnace

### ISSUE THREAD

**Issue by polarim** [StrangeLoopGames/EcoIssues#4607]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Blast Furnace, Make ingots
2. Have no output for pollution under pipes
3. It'll max out at 100 and stop
4. Pick up hammer and break furnace
5. Place back down
6. Pollution stuff is gone

**Expected behavior:**
Not let me pick it up if there's pollution inside of it.

**Actual behavior:**
Let's me pick up the furnace and delete pollution, cheating the system.

**Comment by ecoemmeck** [comment]
To make the pollution flow out of the blast furnace you need to remove 1 block above the pipe going upwards on the blast furnace

**Comment by WeaselDog** [comment]
Thanks for your report. There is a new added check to see if the output is blocked to prevent this from happening.
![ExaustBlocked](https://user-images.githubusercontent.com/47330823/71548675-6b310880-2966-11ea-8152-119a3e346ec4.png)
