### ISSUE TITLE
USER ISSUE: Can't open door with shovel.

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4609]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Have shovel out, and try to open door. 

**Expected behavior:**
Door opens

**Actual behavior:**
Door does not open until you switch to another tool.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868
