### ISSUE TITLE
USER ISSUE: Trees are not growing.

### ISSUE THREAD

**Issue by jaredalwyn** [StrangeLoopGames/EcoIssues#4610]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Plant a tree and wait for it to grow. 

**Expected behavior:**
Tree will grow over several days.

**Actual behavior:**
Trees seem to stay stuck in their sapling stage.

**Comment by polarim** [comment]
It takes 5 days for a tree to mature fully.

**Comment by Huntermeign** [comment]
Use a soil sampler to check if the tree is dead. Trees take 120 irl hours to fully grow otherwise.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4156
