### ISSUE TITLE
USER ISSUE: skill points not regeneration

### ISSUE THREAD

**Issue by highballer1** [StrangeLoopGames/EcoIssues#4613]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**

**Comment by highballer1** [comment]
skill points do not regenerate, some skills are miss balanced. all skills from the research bench needs 500 pts start but the skills under it are only 1pt. blue bar fill up and does not refresh or issue skill points.
no skill points for housing even after a house is built.

**Comment by MarjieAVolk** [comment]
* Specialties are a special type of skill, and all specialties increase in cost each time you take a new specialty.  This is why you see some skills costing 500.  If you abandon some of your specialties, you will see the cost for others go back down.
* Building a house alone does not give you housing skill points.  Points come from decorative items placed in your house.

As for not getting skill points, that does sound like a problem.  Is this a display bug?  If you log out and back in, does the number of skill points get updated?  Do other players in this world have the same problem?

Could you attach your client log file?  It is at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by highballer1** [comment]
in reference to the skill points, yes we have to log out and restart the game. the blue bar does refreshes and then when it maxes out it locks, and we do not get any points after, and yes it affected both players on the game. we were playing co-op on lan

Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by MarjieAVolk** [comment]
Did you by any chance enable the 'UseWaste' setting on your server?

**Comment by highballer1** [comment]
I don't believe so.. in regard to waste, smelting does produce a lot of waste. Is there a use for it or is it just a pollutant? Any way to dispose of it. Also is there a way to locate ores on the map, I looked and cannot find a filter for any, it has one for oil ...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MarjieAVolk** [comment]
Tailings are a bad side effect of smelting.  You can bury them deep underground to prevent them from polluting.  As for locating ores on the map, there isn't really a way to do that right now.

**Comment by craig-jong** [comment]
skill bar fixed on the latest staging
