### ISSUE TITLE
USER ISSUE: Stuck inside a dirt block :/

### ISSUE THREAD

**Issue by TheCodedOne** [StrangeLoopGames/EcoIssues#4614]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place stone blocks where you're stood

**Expected behavior:**
not get stuck inside a block

**Actual behavior:**
get stuck inside block

**Comment by ecoemmeck** [comment]
Have you tried /unstuck

**Comment by MarjieAVolk** [comment]
Thanks.  /unstuck should get you out.  We will continue to improve our character controller, but for now if you place something inside yourself you will get stuck unfortunately.
