### ISSUE TITLE
USER ISSUE: Server 25km2 World Gen

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4615]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Install Eco Server Tool
2. Run Server
3. Set world gen size 500x500 (25km2)
4. Shut Down server
5. Delete world folder
6. Restart world to regenerate world

**Expected behavior:**
Regenerate world and start server.

**Actual behavior:**
Blows up server, must reconfig world gen file to smaller (original or 100x100) size and restart server, then increase. size.

**Comment by pamduncan** [comment]
500X500 is  a bit larger then is normally recommended.  You can build it but it's not always a great idea.  There are playability issues when you get that large and have to deal with people claiming all that lant.  also we have had a lot of issues with worlds over 200X200 getting tears in the world , having a lot of players falling through the world very often, and corruption of the game file during saves.

**Comment by Thyriel** [comment]
That worldsize can't really work. Even half the length (1/4th area) already needs up to 16GB RAM and skyrockets CPU usage.
Don't forget that each double length results in 4 times increased area and therefor 4 times increased RAM usage and CPU load.

I'm sure a setup like that would probably need something like 4 xeon processors and 64GB RAM.

**Comment by MarjieAVolk** [comment]
Gonna close this for now then, as that size is outside of the normal range of what we support.
