### ISSUE TITLE
Graphical Bug With Stockpile

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4616]
i think the pic speaks for itself.
where the pipe is next to the pipe the stockpile looks as though there is nothing there and can be walked in

![image](https://user-images.githubusercontent.com/29722757/36292358-63e8a1ea-1325-11e8-9628-142bf198d1fc.png)

![image](https://user-images.githubusercontent.com/29722757/36293989-9172f03c-1331-11e8-8e3f-40b5f2adff2b.png)

**Comment by ecoemmeck** [comment]
same thing kinda happens when next to glass

![image](https://user-images.githubusercontent.com/29722757/36339124-61cd78f2-1412-11e8-9589-8d7e7c005168.png)

**Comment by keegan-o** [comment]
fixing this is staging then master
