### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by SirVulture** [StrangeLoopGames/EcoIssues#4618]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Press Continue
2. Get Error

**Expected behavior:**
Started my saved world

**Actual behavior:**
The following error message popped up:
"Connection Failed"
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you connect to your world if you open it via 'Load' instead?  Deleting C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO might help.

**Comment by MarjieAVolk** [comment]
Closing due to no response
