### ISSUE TITLE
USER ISSUE: Flying away wood

### ISSUE THREAD

**Issue by Reelzerz** [StrangeLoopGames/EcoIssues#4621]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Cut tree down chop it up and close server and start it back up.

**Expected behavior:**
you should be able to collect it.

**Actual behavior:**
crash

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
