### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by Zetta269** [StrangeLoopGames/EcoIssues#4622]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Creating a new world (no 1-3 player)
2. Getting the "Connection failed" error when trying to generate the world

**Expected behavior:**
To generate the world and start playing ;)

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that might cause this.  One thing you can try is to delete C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO.  If that doesn't work, send me any log files you have in '[...]\steamapps\common\Eco Server'

**Comment by MarjieAVolk** [comment]
Closing due to no response
