### ISSUE TITLE
DEV readPLZ. From South Korea users.

### ISSUE THREAD

**Issue by kimdogul** [StrangeLoopGames/EcoIssues#4623]
Hello sir,

i am one of the player in South Korea, and i really really like to play ECO .
I just bought it right after it came up on steam.

the main reason i am posting this thread on ECO forum is to call for a help.
because we need a Korean Language Patch for this game.
though i have no 1% of error with playing this game within English but there are a lot of users who is not able to use English required to play this game.

beside that,

what we need now is

cold and hot circumstance affect on health
drop or abandon item from inventory
lay down or crouch
able of UNICODE in typing on chat . if this is available, we mihgt don't need a korean patch becuz i or someone who can use english well will
able to tell them what is what, and what works for what in korean typing.

thrid person mode in key binding. i know it is able to do it with PRESSING "B" and clicking it but, it is so annoying.
if you are not able to patch in korean language, tell me about the way to do this. i will make a korean patch team with in STEAM WORKSHOP.

i have posted this issue on
http://ecoforum.strangeloopgames.com:4567/topic/3592/dev-readplz-from-south-korea-users/2

**Comment by MarjieAVolk** [comment]
Hi there - thank you for writing.  We are aware a lot of non-English speakers are having trouble with the game, and we hope to improve this soon.  Adding support for unicode characters in chat is high on my task list right now: https://github.com/StrangeLoopGames/EcoIssues/issues/2656

We also have someone who is working on adding translation support, although that is a bigger task.

We are also aware dropping items is a big problem, and we have a 'trash' feature planned that will address this.  Hopefully that will be worked on within the next few months.

Closing, as we are already working on this :)

**Comment by kimdogul** [comment]
thx for replying back and  plus i don't know 1 bit about coding but if you need any translation in text file with korean, you can call for me. i am always ready to make a translation.

**Comment by MarjieAVolk** [comment]
Thank you!  If you are interested in contributing translations, the project is here: https://crowdin.com/project/eco-by-strange-loop-games

You can also join our Discord (https://discord.gg/n5FaJT) and go to the translation-team channel to talk with others about it.
