### ISSUE TITLE
USER ISSUE: Game does not Close 

### ISSUE THREAD

**Issue by MasterJochen** [StrangeLoopGames/EcoIssues#4624]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
In the Steam client click Quit Button.

**Expected behavior:**
Game Closes Complete with all tasks.

**Actual behavior:**
The Game window closes but if i try to restart it steam says game still running. I have to close steam tso steam ask me if i wanna force ECO to stop. Since i cant find the game Exe in Taskmanager i gues it must be a different process preventing it to re laungh.

**Comment by MarjieAVolk** [comment]
I wonder if this is the server still running?

**Comment by ShadowBlade72** [comment]
I have this same issue. Eco will close, but Steam still believes it's running. You must close Steam and relaunch it before you can relaunch Eco.

**Comment by sagg** [comment]
Ich habe das selbe Verhalten jedes mal, ist also reproduzierbar. Wie heißt der Prozess des Servers? Ich bin die Prozessliste gestern durchgegangen, konnte aber nichts finden, was ich spontan zu ECO zugeordnet hätte.

**Comment by sagg** [comment]
oh, i thought your german, cause i've seen a german post. but i think this was translated. :D

i have the same behavior every time, what's the name of the server process? yesterday i scrolled through the processlist and there was nothing which could be related to ECO i would say..but how i said, i dont know the name of the process, i could check this again if you want.

**Comment by metachronism** [comment]
7.3 should fix this
