### ISSUE TITLE
Icon Bug

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4628]
the Icon for the Modern Hammer isn't the same as the other modern tools
the others have an image of fiberglass or steel on them

![image](https://user-images.githubusercontent.com/29722757/36298274-631b0cd2-134b-11e8-8c41-2941199fae38.png)

**Comment by ecoemmeck** [comment]
just noticed the Modern Hoe is the also missing this
![image](https://user-images.githubusercontent.com/29722757/36342393-fc62cd56-1451-11e8-8dc4-50396f6263fc.png)

**Comment by ecoemmeck** [comment]
I was playing 7.2.5 recently as in a few hours ago and this isn't fixed unless it's in the staging build?

**Comment by MarjieAVolk** [comment]
Yeah this will be only in the staging build right now.
