### ISSUE TITLE
Game Crash when laucnhing from steam

### ISSUE THREAD

**Issue by Stressinout** [StrangeLoopGames/EcoIssues#4629]
Just started computer up and launched steam, clicked on the eco and got this crash error. Launched again and it worked fine, figured id pass this on. 

Eco [version: Unity 2017.3.0f3 (a9f86dcd79df)]

Unknown caused an Access Violation (0xc0000005)
  in module Unknown at 0033:d4b11dd3.

Error occurred at 2018-02-16_025206.
I:\SteamLibrary\steamapps\common\Eco\Eco.exe, run by stres.
16% memory in use.
32709 MB physical memory [27380 MB free].
65477 MB paging file [58118 MB free].
134217728 MB user address space [134215462 MB free].
Read from location 00000018 caused an access violation.

Context:
RDI:    0x9c1219c0  RSI: 0x9d8217c0  RAX:   0x00000000
RBX:    0x9cf3c630  RCX: 0x00000000  RDX:   0x9e803800
RIP:    0xd4b11dd3  RBP: 0x4615efd0  SegCs: 0x00000033
EFlags: 0x00010206  RSP: 0x4615ef98  SegSs: 0x0000002b
R8:    0x00000000  R9: 0x4615e930  R10:   0x00000000
R11:    0xd4b11dd0  R12: 0x4615f928  R13:   0xd4c64d48
R14:    0x00000000  R15: 0x9c1219c0

Bytes at CS:EIP:
48 8b 40 18 48 85 c0 74 01 c3 48 8b c9 e9 65 b5 

Stack:
0x4615ef98: d51e1505 000001af 9c1219c0 000001af ................
0x4615efa8: 00000000 00000000 d4b11f50 000001af ........P.......
0x4615efb8: 98dec978 000001af 9e803800 000001af x........8......
0x4615efc8: 00000000 00000000 4615f0b0 00000090 ...........F....
0x4615efd8: 87079bdb 000001af 00000000 00000000 ................
0x4615efe8: 00000000 00000000 00000000 00000000 ................
0x4615eff8: 00000000 00000000 00000000 00000000 ................
0x4615f008: 8bd85500 000001af 8bd23b60 000001af .U......`;......
0x4615f018: 9d8217c0 000001af 00000000 00000000 ................
0x4615f028: 9e5523f0 000001af 8bd85500 000001af .#U......U......
0x4615f038: 9be68d80 000001af 9c1219c0 000001af ................
0x4615f048: 00000009 00000000 00000000 00000000 ................
0x4615f058: dfc734a0 000001af 9c979da0 000001af .4..............
0x4615f068: 4615f928 00000090 d4c64d48 000001af (..F....HM......
0x4615f078: 00000000 00000000 9c1219c0 000001af ................
0x4615f088: 00000009 00000000 d4b11d10 000001af ................
0x4615f098: 99b9cf38 000001af 805e010b 000001af 8.........^.....
0x4615f0a8: 9e4f3850 000001af 4615f0f0 00000090 P8O........F....
0x4615f0b8: 870798b5 000001af 9c1219c0 000001af ................
0x4615f0c8: 00000009 00000000 87079880 000001af ................
0x4615f0d8: 9cd54718 000001af 805f752d 000001af .G......-u_.....
0x4615f0e8: 9be99dc0 000001af 4615f280 00000090 ...........F....
0x4615f0f8: 8707379b 000001af 9d38f818 000001af .7........8.....
0x4615f108: 870723cc 000001af 00000000 00000000 .#..............
0x4615f118: 4615f2d0 00000090 00000000 00000000 ...F............
0x4615f128: 9be99dc0 000001af 9dab79a0 000001af .........y......
0x4615f138: 9be2d680 000001af 9be68d80 000001af ................
0x4615f148: 9c1219c0 000001af 9be99dc0 000001af ................
0x4615f158: 9c1219c0 000001af 00000000 00000000 ................
0x4615f168: 00000000 00000000 00000000 00000000 ................
0x4615f178: 00000000 00000000 00000000 00000000 ................
0x4615f188: 00000000 00000000 00000000 00000000 ................
0x4615f198: 00000000 00000000 00000000 00000000 ................
0x4615f1a8: 00000000 00000000 00000000 00000000 ................
0x4615f1b8: 00000000 00000000 00000000 00000000 ................
0x4615f1c8: 00000000 00000000 00000000 00000000 ................
0x4615f1d8: 00000000 00000000 00000000 00000000 ................
0x4615f1e8: 9be99dc0 000001af 9e4f3850 000001af ........P8O.....
0x4615f1f8: 00000000 00000000 00000000 00000000 ................
0x4615f208: 00000000 00000000 d4c85970 000001af ........pY......
0x4615f218: 00000009 00000000 00000000 00000000 ................
0x4615f228: dfc734a0 000001af 870723f8 000001af .4.......#......
0x4615f238: 4615f928 00000090 d4c64d48 000001af (..F....HM......
0x4615f248: 00000000 00000000 9c1219c0 000001af ................
0x4615f258: 00000009 00000000 87072ee0 000001af ................
0x4615f268: 9d38f818 000001af 870723f8 000001af ..8......#......
0x4615f278: 87072ee0 000001af 4615f2d0 00000090 ...........F....
0x4615f288: 870723cc 000001af d4c64d48 000001af .#......HM......
0x4615f298: 00000000 00000000 8bd85a00 000001af .........Z......
0x4615f2a8: 00000009 00000000 87072340 000001af ........@#......
0x4615f2b8: 8bd85a00 000001af 9e4f9550 000001af .Z......P.O.....
0x4615f2c8: 8bd3cd80 000001af 4615f460 00000090 ........`..F....
0x4615f2d8: 8706b3a7 000001af 00000000 00000000 ................
0x4615f2e8: 8706a61b 000001af 9cf3c630 000001af ........0.......
0x4615f2f8: 4615f4f0 00000090 4615f470 00000090 ...F....p..F....
0x4615f308: 4615f928 00000090 d4c64d48 000001af (..F....HM......
0x4615f318: 00000000 00000000 00000000 00000000 ................
0x4615f328: 8bd85a00 000001af 8bd85500 000001af .Z.......U......
0x4615f338: 00000000 4099b800 00000000 00000000 .......@........
0x4615f348: 00000000 40808000 00000000 00000000 .......@........
0x4615f358: 00000000 00000000 8bd85a00 000001af .........Z......
0x4615f368: 00000000 00000000 00000000 00000000 ................
0x4615f378: 00000000 00000000 00000000 00000000 ................
0x4615f388: 8bd85500 000001af 00000000 00000000 .U..............
0x4615f398: 00000000 00000000 00000000 00000000 ................
0x4615f3a8: 00000000 00000000 00000000 0000009b ................
0x4615f3b8: 00000000 00000000 9e4f3700 00000233 .........7O.3...
0x4615f3c8: 9be99dc0 000001af 8bd85a00 000001af .........Z......
0x4615f3d8: 4615f1d0 00000090 4615f4f0 00000090 ...F.......F....
0x4615f3e8: 8bd3cd80 000001af 9c353ba0 000001af .........;5.....
0x4615f3f8: 00000000 00000000 00000000 00000000 ................
0x4615f408: d49e2880 000001af 9c979da0 000001af .(..............
0x4615f418: 4615f928 00000090 d4c64d48 000001af (..F....HM......
0x4615f428: 00000000 00000000 00000000 00000000 ................
0x4615f438: 00000000 00000000 d4b11f50 000001af ........P.......
0x4615f448: 00000000 00000000 9c353ba0 000001af .........;5.....
0x4615f458: 8bd3cd80 000001af 4615f4f0 00000090 ...........F....
0x4615f468: 8706a61b 000001af 4615f530 00000090 ........0..F....
0x4615f478: d5182900 000001af 8706a5b0 000001af .)..............
0x4615f488: 4615f928 00000090 8064b107 000001af (..F......d.....
0x4615f498: d49e2880 000001af 8706a33e 000001af .(......>.......
0x4615f4a8: 9c353ba0 000001af d4c64d48 000001af .;5.....HM......
0x4615f4b8: 4615f800 00000090 4615f480 00000090 ...F.......F....
0x4615f4c8: 00000000 00000000 4615f800 00000090 ...........F....
0x4615f4d8: 4615f928 00000090 99564390 000001af (..F.....CV.....
0x4615f4e8: d5182900 000001af 4615f530 00000090 .)......0..F....
0x4615f4f8: 8706a31a 000001af 00000000 00000000 ................
0x4615f508: 4615f928 00000090 d4b11d10 000001af (..F............
0x4615f518: 99b10ca0 000001af 8064b107 000001af ..........d.....
0x4615f528: 8bdd7660 000001af 4615f5c0 00000090 `v.........F....
0x4615f538: d518296b 000001af 00000018 00000000 k)..............
0x4615f548: ded0439f 00007fff 00000018 00000000 .C..............
0x4615f558: 00000018 00000000 9cf3c630 000001af ........0.......
0x4615f568: 8064b107 000001af 4615f928 00000090 ..d.....(..F....
0x4615f578: deba21d0 00007fff 9e5527e0 000001af .!.......'U.....
0x4615f588: 00000000 00000000 00000000 00000000 ................
0x4615f598: deba228b 00007fff 9cf3c630 000001af ."......0.......
0x4615f5a8: 99564390 000001af d5182900 000001af .CV......)......
0x4615f5b8: 4615f600 00000090 4615f600 00000090 ...F.......F....
0x4615f5c8: decc64af 00007fff 99564390 000001af .d.......CV.....
0x4615f5d8: 00000000 00000090 00000000 00000000 ................
0x4615f5e8: 99564390 000001af 00000040 00000200 .CV.....@.......
0x4615f5f8: 00000000 00000000 d4c64d48 000001af ........HM......
0x4615f608: e0ae1a50 000001af 00000000 00000000 P...............
0x4615f618: 9cf3c630 000001af d4cc04f0 000001af 0...............
0x4615f628: 9e5527e0 000001af 4615f928 00000090 .'U.....(..F....
0x4615f638: 4615f800 00000090 cf770000 000001af ...F......w.....
0x4615f648: 3c51e000 00000090 00000000 00000000 ..Q<............
0x4615f658: 00000000 00000000 00000000 00000000 ................
0x4615f668: 00000000 00000000 cf770000 000001af ..........w.....
0x4615f678: cf770cc0 000001af 00000000 00000000 ..w.............
0x4615f688: 4615f8a8 00000090 4615f8f8 00000090 ...F.......F....
0x4615f698: 4615f7f0 00000090 828f3780 000001af ...F.....7......
0x4615f6a8: 0441b541 00007ff8 ffffffff 00000000 A.A.............
0x4615f6b8: 08859804 00007ff8 9e54b020 000001af ........ .T.....
0x4615f6c8: 00000001 00000000 ffffffff 00000000 ................
0x4615f6d8: 0441b47e 00007ff8 828f3780 000001af ~.A......7......
0x4615f6e8: 00000001 00000000 d49e2880 000001af .........(......
0x4615f6f8: 00000000 00000000 d49e0000 000001af ................
0x4615f708: 9cec40d8 000001af 4615f7d8 00000090 .@.........F....
0x4615f718: 0441b41c 00007ff8 00000d28 00000000 ..A.....(.......
0x4615f728: 00000098 00000000 cf820000 000001af ................
0x4615f738: d49e0e10 000001af d66a696f 0000a7dc ........oij.....
0x4615f748: 00000020 00000000 00000098 00000000  ...............
0x4615f758: 4615f800 00000090 9dab2258 000001af ...F....X"......
0x4615f768: 9e5527e0 000001af 99564390 000001af .'U......CV.....
0x4615f778: 4615f928 00000090 4615f800 00000090 (..F.......F....
0x4615f788: 99564390 000001af 9e5527e0 000001af .CV......'U.....
0x4615f798: dec18a19 00007fff 00000040 00000000 ........@.......
0x4615f7a8: 00000000 00000000 d4d239c0 000001af .........9......
0x4615f7b8: 99b10bd0 000001af ded32d9d 00007fff .........-......
0x4615f7c8: dec1ef27 00007fff 4615f928 00000090 '.......(..F....
0x4615f7d8: 4615f800 00000090 dfe4bfb3 000001af ...F............
0x4615f7e8: 00000000 00000000 00000000 00000000 ................
0x4615f7f8: deba232d 00007fff 00000000 00000000 -#..............
0x4615f808: decf73b8 00007fff dfba2290 000001af .s......."......
0x4615f818: 4615f928 00000090 9e5527e0 000001af (..F.....'U.....
0x4615f828: 00000000 00000000 99564390 000001af .........CV.....
0x4615f838: d66a676f 0000a7dc 99564390 000001af ogj......CV.....
0x4615f848: 9be2d000 000001af 4615f928 00000090 ........(..F....
0x4615f858: 00000000 00000000 dfba2290 000001af ........."......
0x4615f868: dec1f1fc 00007fff 9e5527e0 000001af .........'U.....
0x4615f878: d4d239c0 000001af 00000000 00000000 .9..............
0x4615f888: d4d055c0 000001af d4c64d48 000001af .U......HM......
0x4615f898: 8c06ab70 000001af ffffffff 00000000 p...............
0x4615f8a8: 00000000 00000000 ded34580 00007fff .........E......
0x4615f8b8: dfc40b80 000001af 9be68f80 000001af ................
0x4615f8c8: 00000000 00000000 4615f908 00000090 ...........F....
0x4615f8d8: dec3f873 00007fff d4c64d48 000001af s.......HM......
0x4615f8e8: 9beb1e60 000001af d4c64d48 000001af `.......HM......
0x4615f8f8: 4615f930 00000090 ded34580 00007fff 0..F.....E......
0x4615f908: d4c64d48 000001af 9e2ab000 000001af HM........*.....
0x4615f918: dec407db 00007fff 9be68f80 000001af ................
0x4615f928: 00000000 00000000 9dab2140 000001af ........@!......
0x4615f938: 00000000 00000000 00000000 000001af ................
0x4615f948: 8bd3ce18 000001af 00000000 00000000 ................
0x4615f958: 00000000 00000000 00000001 00000000 ................
0x4615f968: dfc40b80 000001af 8bd3cd80 000001af ................
0x4615f978: dec44017 00007fff 9e2ab000 000001af .@........*.....
0x4615f988: dec40674 00007fff 00000000 00000000 t...............
0x4615f998: 00000000 00000000 d4c7b990 000001af ................
0x4615f9a8: decf987d 00007fff 00000000 00000000 }...............
0x4615f9b8: 00000000 00000000 00000000 00000000 ................
0x4615f9c8: 00000000 00000000 00000000 00000000 ................
0x4615f9d8: decf9eab 00007fff 00002870 00000000 ........p(......
0x4615f9e8: 00000000 00000000 d4c7b990 000001af ................
0x4615f9f8: 00000000 00000000 00000000 00000000 ................
0x4615fa08: 08711fe4 00007ff8 d4c7b990 000001af ..q.............
0x4615fa18: 00000000 00000000 00000000 00000000 ................
0x4615fa28: 00000000 00000000 00000000 00000000 ................
0x4615fa38: 0889efc1 00007ff8 00000000 00000000 ................
0x4615fa48: 00000000 00000000 00000000 00000000 ................
0x4615fa58: 00000000 00000000 00000000 00000000 ................
0x4615fa68: 05b593c0 00007ff8 4615e100 00000090 ...........F....
0x4615fa78: 4615e100 00000090 00000000 00000000 ...F............
0x4615fa88: 00000000 00000000 00000000 00000000 ................
0x4615fa98: 00000000 00000000 00000000 00000000 ................
0x4615faa8: 00000000 00000000 00000000 00000000 ................
0x4615fab8: 00000000 00000000 00000000 00000000 ................
0x4615fac8: 00000000 00000000 00000000 00000000 ................
0x4615fad8: 00000000 00000000 00000000 00000000 ................
0x4615fae8: 00000000 00000000 00000000 00000000 ................
0x4615faf8: 00000000 00000000 00000000 00000000 ................
0x4615fb08: 00000000 00000000 00000000 00000000 ................
0x4615fb18: 00000000 00000000 00000000 00000000 ................
0x4615fb28: 00000000 00000000 00000000 00000000 ................
0x4615fb38: 00000000 00000000 00000000 00000000 ................
0x4615fb48: 00000000 00000000 00000000 00000000 ................
0x4615fb58: 00000000 00000000 00000000 00000000 ................
0x4615fb68: 00000000 00000000 00000000 00000000 ................
0x4615fb78: 00000000 00000000 00000000 00000000 ................
0x4615fb88: 00000000 00000000 00000000 00000000 ................
0x4615fb98: 00000000 00000000 00000000 00000000 ................
0x4615fba8: 00000000 00000000 00000000 00000000 ................
0x4615fbb8: 00000000 00000000 00000000 00000000 ................
0x4615fbc8: 00000000 00000000 00000000 00000000 ................
0x4615fbd8: 00000000 00000000 00000000 00000000 ................
0x4615fbe8: 00000000 00000000 00000000 00000000 ................
0x4615fbf8: 00000000 00000000 00000000 00000000 ................
0x4615fc08: 00000000 00000000 00000000 00000000 ................
0x4615fc18: 00000000 00000000 00000000 00000000 ................
0x4615fc28: 00000000 00000000 00000000 00000000 ................
0x4615fc38: 00000000 00000000 00000000 00000000 ................
0x4615fc48: 00000000 00000000 00000000 00000000 ................
0x4615fc58: 00000000 00000000 00000000 00000000 ................
0x4615fc68: 00000000 00000000 00000000 00000000 ................
0x4615fc78: 00000000 00000000 00000000 00000000 ................
0x4615fc88: 00000000 00000000 00000000 00000000 ................
0x4615fc98: 00000000 00000000 00000000 00000000 ................
0x4615fca8: 00000000 00000000 00000000 00000000 ................
0x4615fcb8: 00000000 00000000 00000000 00000000 ................
0x4615fcc8: 00000000 00000000 00000000 00000000 ................
0x4615fcd8: 00000000 00000000 00000000 00000000 ................
0x4615fce8: 00000000 00000000 00000000 00000000 ................
0x4615fcf8: 00000000 00000000 00000000 00000000 ................
0x4615fd08: 00000000 00000000 00000000 00000000 ................
0x4615fd18: 00000000 00000000 00000000 00000000 ................
0x4615fd28: 00000000 00000000 00000000 00000000 ................
0x4615fd38: 00000000 00000000 00000000 00000000 ................
0x4615fd48: 00000000 00000000 00000000 00000000 ................
0x4615fd58: 00000000 00000000 00000000 00000000 ................
0x4615fd68: 00000000 00000000 00000000 00000000 ................
0x4615fd78: 00000000 00000000 00000000 00000000 ................
0x4615fd88: 00000000 00000000 00000000 00000000 ................
0x4615fd98: 00000000 00000000 00000000 00000000 ................
0x4615fda8: 00000000 00000000 00000000 00000000 ................
0x4615fdb8: 00000000 00000000 00000000 00000000 ................
0x4615fdc8: 00000000 00000000 00000000 00000000 ................
0x4615fdd8: 00000000 00000000 00000000 00000000 ................
0x4615fde8: 00000000 00000000 00000000 00000000 ................
0x4615fdf8: 00000000 00000000 00000000 00000000 ................
0x4615fe08: 00000000 00000000 00000000 00000000 ................
0x4615fe18: 00000000 00000000 00000000 00000000 ................
0x4615fe28: 00000000 00000000 00000000 00000000 ................
0x4615fe38: 00000000 00000000 00000000 00000000 ................
0x4615fe48: 00000000 00000000 00000000 00000000 ................
0x4615fe58: 00000000 00000000 00000000 00000000 ................
0x4615fe68: 00000000 00000000 00000000 00000000 ................
0x4615fe78: 00000000 00000000 00000000 00000000 ................
0x4615fe88: 00000000 00000000 00000000 00000000 ................
0x4615fe98: 00000000 00000000 00000000 00000000 ................
0x4615fea8: 00000000 00000000 00000000 00000000 ................
0x4615feb8: 00000000 00000000 00000000 00000000 ................
0x4615fec8: 00000000 00000000 00000000 00000000 ................
0x4615fed8: 00000000 00000000 00000000 00000000 ................
0x4615fee8: 00000000 00000000 00000000 00000000 ................
0x4615fef8: 00000000 00000000 00000000 00000000 ................
0x4615ff08: 00000000 00000000 00000000 00000000 ................
0x4615ff18: 00000000 00000000 00000000 00000000 ................
0x4615ff28: 00000000 00000000 00000000 00000000 ................
0x4615ff38: 00000000 00000000 00000000 00000000 ................
0x4615ff48: 00000000 00000000 00000000 00000000 ................
0x4615ff58: 00000000 00000000 00000000 00000000 ................
0x4615ff68: 00000000 00000000 00000000 00000000 ................
0x4615ff78: 00000000 00000000 00000000 00000000 ................
0x4615ff88: 00000000 00000000 00000000 00000000 ................
0x4615ff98: 00000000 00000000 00000000 00000000 ................
0x4615ffa8: 00000000 00000000 00000000 00000000 ................
0x4615ffb8: 00000000 00000000 00000000 00000000 ................
0x4615ffc8: 00000000 00000000 00000000 00000000 ................
0x4615ffd8: 00000000 00000000 00000000 00000000 ................
0x4615ffe8: 00000000 00000000 00000000 00000000 ................
0x4615fff8: 00000000 00000000                   ........

Module 1
C:\WINDOWS\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_195422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
H:\Steam\tier0_s64.dll
Image Base: 0x628e0000  Image Size: 0x00372000
File Size:  359712      File Time:  2017-12-15_135928
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 3
H:\Steam\steamclient64.dll
Image Base: 0x62c60000  Image Size: 0x00df6000
File Size:  14398016    File Time:  2017-12-15_135928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 4
H:\Steam\vstdlib_s64.dll
Image Base: 0x64e20000  Image Size: 0x0006b000
File Size:  348960      File Time:  2017-12-15_135928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 5
I:\SteamLibrary\steamapps\common\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x64e90000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-02-07_022918
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1

== [end of error.log] ==

**Comment by MarjieAVolk** [comment]
@metachronism I have never known what these are, do you know what these are?  Is there a different log that has a better error message, or is this it?

**Comment by Stressinout** [comment]
Unfortunately, this is the one and only time I've seen this happen, it just gave me a message that said there was an error and if you would like to get the error code to pass it on. figured it was worth passing on, and like I said this was the only time I've seen this happen. never from the website just from steam.

**Comment by MarjieAVolk** [comment]
I think that this is because of some contention over files; for example, something else is using the Eco files (eg. multiple copies of Eco running), or perhaps the operating system is not allowing the game access to some file (eg. the game needs to be run as an administrator or something).

**Comment by Stressinout** [comment]
![eco error pic](https://user-images.githubusercontent.com/36399021/36624411-71c9309a-18d4-11e8-98a1-36546897c9ad.jpg)
got it again, here is what it says for an error message. I did not try administrator on launch, and like I said this rarely happens. Most times it launches just fine with no issues and will launch fine after i close the error and try again.

**Comment by metachronism** [comment]
turned off some experimental unity settings to see if this fixes it

**Comment by metachronism** [comment]
7.3
