### ISSUE TITLE
USER ISSUE: Issues re-joining server

### ISSUE THREAD

**Issue by Philanthropy1** [StrangeLoopGames/EcoIssues#4632]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1730909/output_log.txt)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Was on a friend's server for approx 4 hours
2. Got disconnected with no error reports
3. When trying to rejoin, unable to, after several attempts
4 Have tried restarting steam, and can join other servers still. Know the server I want to join is running OK

**Expected behavior:**
Joined the server

**Actual behavior:**
No error message given, sometimes gets stuck on "Entering World" but normally just goes back to main menu.

**Comment by Philanthropy1** [comment]
I'm thinking this is most likely down to ping to the server, but not entirely sure. 

My internet can be unreliable at times, and know this is cross-continent (UK-US)

**Comment by MarjieAVolk** [comment]
Log has a bunch of 'Ping: Error performing ICMP transmission. Possibly because of a timeout'

It sounds like it's probably a bad connection.  But gonna send this over to @metachronism in case it might be something else.

**Comment by metachronism** [comment]
those ping errors are harmless, this was likely some other issue (such as server lag) that should be resolved now
