### ISSUE TITLE
USER ISSUE: Flying Cart

### ISSUE THREAD

**Issue by WolfLeader1** [StrangeLoopGames/EcoIssues#4634]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
Get a in a powered cart, upside down or type /unstuck

**Expected behavior:**
If upside down, should get out and flip over.
If /unstuck, should rotate and get unstuck

**Actual behavior:**
upside down, get out and flys
/unstuck, you and cart go flying

**Comment by ecoemmeck** [comment]
Lol typing /unstuck with any cart is good for a laugh

**Comment by CompactDisc** [comment]
Just adding this as a reference:
https://www.reddit.com/r/EcoGlobalSurvival/comments/7z2l8b/my_friends_and_i_discovered_a_bug/

**Comment by SeanAtr0n** [comment]
fixed
