### ISSUE TITLE
Adding in mod level perms

### ISSUE THREAD

**Issue by bfc1974** [StrangeLoopGames/EcoIssues#4636]
Game desperately needs mods level permissions to police the server when admin is off.

We have had 2 trolls on 2 occasions wreck the server by leaving wood pulp and stumps and fallen logs all over.

As admin the only thing you can do is roll back given the widespread devastation.

The game also needs a tool which admins and mods can use to select certain areas and restore that area to eco-friendly [plants and trees and ecosystem]

Minecraft has similar clean up tools.

We have also experienced being booted for trying to chop a log on the floor. You login back in and the same logs are now flying logs in the game!

The game surprisingly is in beta but seemed more stable in alpha. Needs a lot more work quickly before people lose their enthusiasm for it. Certainly, as a server admin I'm beginning to wonder how something thats a beta game has so many bugs in it - yes it's a beta but so many bugs???

**Comment by Huntermeign** [comment]
Kind of defeats the purpose of the game imo. Could have made laws to limit trees cut if played under a certain ammount of hours or not on owned property. This isn't Minecraft which focuses on creativity. This is Eco where the idea is to deal with situations like these using game features.

**Comment by MarjieAVolk** [comment]
Re the trees floating bug, there is a bug for that here: https://github.com/StrangeLoopGames/EcoIssues/issues/3668

Cleaning up debris and fixing the environment with an admin command is not in the spirit of the game; managing people and the consequences of their actions is intended to be part of the game.  As @Huntermeign suggested, the laws system is intended to solve these problems.  (Unfortunately, part of the laws system is broken right now, but will be fixed in the next release)

**Comment by bfc1974** [comment]
So trolls who do damage to the world as revenge for being booted is acceptable?  Sorry to me it's a big no.  I can understand the argument for rectifying issues and educating players but when a player logs in with the sole purpose of wrecking the server its not acceptable!!!

I know there is blacklisting but some how this player keeps logging in so yes there is a need for mods permissions which aren't at admin level as I can't sort on the server 24/7. 

Quite annoyed at this reaction to mods request.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#257
