### ISSUE TITLE
USER ISSUE: conection failed

### ISSUE THREAD

**Issue by jacktherippers** [StrangeLoopGames/EcoIssues#4638]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
when i want play i have a message tell me connection failed in the last maj

**Expected behavior:**
Connection Failed

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If running your own game, when starting a new world, select 'Generate new'
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
