### ISSUE TITLE
Virus Detector maybe detecting a Virus in Servers in Join Menu (or maybe its a false positive)

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4639]
Steps i did to have this appear (not sure if its repeatable)
Server Crashed (so it needed a Restart, nothing wrong with that)
Clicked Join, then Avast Popped up with this
![snap1724](https://user-images.githubusercontent.com/29383891/36316566-909e5b96-1332-11e8-83ba-2dbefdc0af52.png)
quick IP check showed this info
![snap1725](https://user-images.githubusercontent.com/29383891/36316592-9df30684-1332-11e8-9383-18d049469a1f.png)

Only thing i can come up with it detected something when the List of Available Servers was updating
so don't think its anything to do with ECO.EXE because if it was i wouldn't be able to run it.

maybe have in place a Server Detection System for Malware/Virus?

this is the Second time i have seen this last time was Tuesday about 6pm GMT

**Comment by BadKaiPanda** [comment]
I get this on both steam and slg accounts

**Comment by Conchipedia** [comment]
this i now get everytime i have the list of servers up, it has gotten so Annoying i have muted the Female Voice telling "threat detected"

**Comment by metachronism** [comment]
Hey Jeff, we need a way to blacklist IPs from the server listing service, ping me for more info

**Comment by BadKaiPanda** [comment]
his also happens on load up now, in 0.7.1.2 it happened on the server screen, the 0.7.2.5 version does it on the loading page, not sure if you have changed when you start polling the server list and if you did what a shitty and bad move but if not this IP is nothing to do with the server list.

**Comment by metachronism** [comment]
should be a non factor now since 7.4, as client no longer does http requests for server info
