### ISSUE TITLE
USER ISSUE: Admin Prompts on world launch

### ISSUE THREAD

**Issue by yukihyou** [StrangeLoopGames/EcoIssues#4640]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Run the game as a standard user without admin rights on Windows 10.
2. Start a new world.

**Expected behavior:**
Game is created and loaded.

**Actual behavior:**
Two consecutive UAC prompts are generated, for `netsh` commands.

**Comment by yukihyou** [comment]
So, after looking further, it seems this prevents the web server from starting up altogether.

- The first popup is redundant - there is no need to add a rule to my firewall for port 3001, it's already open to my network.
- The second shows in the logs as "failing to start WebServer" - I don't understand why the game needs admin rights to serve web pages on port 3001? Other apps can manage that just fine without admin.

**Comment by metachronism** [comment]
Yeah this is an annoying windows-only issue, windows by default will block (or reroute?) all HTTP traffic on any port, unless that is overridden with the netsh command.

Both of these should only occur once and never again - assuming you didnt change the port setting of the server.  Same deal for the firewall rule for the webserver (game port uses the standard method of letting the user allow it or not)

Neither of this should prevent you from playing singleplayer, but if you disallow them then other players won't be able to join you.
