### ISSUE TITLE
USER ISSUE: waste

### ISSUE THREAD

**Issue by rudeirishknight** [StrangeLoopGames/EcoIssues#4641]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
contained tailing in building

**Expected behavior:**
containment 

**Actual behavior:**
still effecting enviroment outside

**Comment by Huntermeign** [comment]
This is intended behavior afaik. Best way to combat tailings is to bury it way deep. At least 10 stone layers down.

**Comment by MarjieAVolk** [comment]
Closing as working as intended.  You need to bury the tailings deep underground in order to completely eliminate pollution.
