### ISSUE TITLE
USER ISSUE: Dig weed out. Exception.

### ISSUE THREAD

**Issue by Kastuk** [StrangeLoopGames/EcoIssues#4645]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Digging little grassweed out of the field. Got some big lags on the limit of RAM.

**Expected behavior:**
Diggin a hole

**Actual behavior:**
Caught exception: Object reference not set to an instance of an object.

**Comment by MarjieAVolk** [comment]
I'm sorry, but it will be basically impossible for us to fix this without more information.  I am going to change our error messages to give us more information to debug with, so in the next version we can start tracking down these problems.
