### ISSUE TITLE
USER ISSUE: Candles Descrease House value outside (and inside) of home

### ISSUE THREAD

**Issue by frogger35** [StrangeLoopGames/EcoIssues#4646]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place a candle down outside (or inside) your house and turn it on.

**Expected behavior:**
nothing should happen outside your house. I don't know what should happen inside but i don't think it should lower your house value

**Actual behavior:**
decreases house value inside and outside of the home when turned on.

**Comment by johnkslg** [comment]
Fixed
