### ISSUE TITLE
Crash Dump 7.1.2 Beta

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4647]
--BEGIN DUMP--
Dump Time
02/16/2018 18:39:12

Exception
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   bei System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   bei System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   bei Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   bei Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   bei Eco.Core.Controller.ControllerManager.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

Hope it Helps :)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4368
