### ISSUE TITLE
USER ISSUE: not loading

### ISSUE THREAD

**Issue by derek341434** [StrangeLoopGames/EcoIssues#4648]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1

**Expected behavior:**
2

**Actual behavior:**
3

**Comment by Huntermeign** [comment]
Yes

**Comment by MarjieAVolk** [comment]
Assuming this is a connection failed error, here are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If running your own game, when starting a new world, select 'Generate new'
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
