### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by flakmoppen** [StrangeLoopGames/EcoIssues#4649]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I clicked "New" from a freshly installed copy of the game.
2. I named my server "Lingonskogen" (though i tried a few different names with the same result), and hit "Start".
3. As soon as it's loading "GameplayStatsPlugin" it tabs out of the game.
4. When i tab back in again I see a window that says "Connection Failed".

**Expected behavior:**
It should have loaded up the game.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by flakmoppen** [comment]
I can join other servers, I just can't start my own.
(And I have tried to remove the "Eco" folder in "C:\Users\[username]\AppData\LocalLow\Strange Loop Games" but that does nothing. I can still join other servers and not my own.)
I don't know if that narrows it down for you. xD

**Comment by MarjieAVolk** [comment]
One thing you can try is to select 'Generate new' when creating your world.  Some people are having trouble loading the default world.

**Comment by MarjieAVolk** [comment]
Did that let you play your own game?  Could you send me any log files in '[...]\steamapps\common\Eco Server'?  It sounds like your problem is that your server won't start up.

**Comment by MarjieAVolk** [comment]
Closing due to no response.
