### ISSUE TITLE
USER ISSUE: Hunger Meter Goes from Full to Empty in 3 Axe Swings

### ISSUE THREAD

**Issue by emurday** [StrangeLoopGames/EcoIssues#4654]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Not sure.

**Expected behavior:**
Full stomach should last at least the duration of felling and chopping a tree.

**Actual behavior:**
Full stomach lasts from 3-12.

**Comment by MarjieAVolk** [comment]
Is your axe broken?  A broken axe will take significantly more calories to use.

**Comment by MarjieAVolk** [comment]
Closing due to no response
