### ISSUE TITLE
SERVER ISSUE: Crash server with /unstuck

### ISSUE THREAD

**Issue by B1sounours** [StrangeLoopGames/EcoIssues#4655]
Version: 0.7.1 beta

Steps to Reproduce:
Type /unstuck when you have control of a wood cart stuck in water 

Expected behavior:
Teleport on top of the current block

Actual behavior:
Crash server

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4634

**Comment by Spaceferret42** [comment]
Doesn't exactly crash server any more
