### ISSUE TITLE
USER ISSUE: Asphalt Roads are broke

### ISSUE THREAD

**Issue by Bugasu** [StrangeLoopGames/EcoIssues#4657]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Transition from asphalt road to dirt at any acute angle while using a cart

**Expected behavior:**
You roll freely over the difference between the road and dirt

**Actual behavior:**
Your cart gets stuck on the lip between the dirt and asphalt

**Comment by MarjieAVolk** [comment]
For now, you will need to make a road in order for your cart to roll over it well.  We are working on improving ramps to fix this problem.
