### ISSUE TITLE
USER ISSUE: Glass vs Lit Brazier

### ISSUE THREAD

**Issue by wolfie359** [StrangeLoopGames/EcoIssues#4658]
![screenshot 2018-02-16 14 44 39](https://user-images.githubusercontent.com/36454241/36328548-2343038a-1328-11e8-812d-3a6fbab45e59.png)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place partial wall of glass
2. Place Brazier (Stone)
3. Insert coal and light
4. Look at Lit Brazier through glass

**Expected behavior:**
See fire...

**Actual behavior:**
Don't see fire, but do see light...

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/3418
