### ISSUE TITLE
Reaping Dead Plants

### ISSUE THREAD

**Issue by Reelzerz** [StrangeLoopGames/EcoIssues#4660]
To Reproduce:
Go around the world and just reap dead plants

What should happen:
Plant disappears

What did happen:
Plant stayed and was not able to be highlighted or reaped.

**Comment by Thyriel** [comment]
Some dead plants like bushes need a shovel to be removed and dead trees (even saplings) need an axe

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3879
