### ISSUE TITLE
USER ISSUE: When server crash/reset weird things happen

### ISSUE THREAD

**Issue by MC2424** [StrangeLoopGames/EcoIssues#4661]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When a server reset/ crash

**Expected behavior:**
Nothing wrong should happen

**Actual behavior:**
1. Sometimes duplicate items spawning (a door spawning at an existing door). 2.Order of chest changes (e.g. I have a lot of chests and I store things with a particular order, and the order of the chests change at the storage window when the server crash)

**Comment by metachronism** [comment]
This is somewhat intended behavior, but we have built in better safeguards to save things on server shutdown to prevent it.  Crashes will always had leftover stuff on occasion
