### ISSUE TITLE
USER ISSUE: Crafting table and research table frozen 

### ISSUE THREAD

**Issue by jenfu** [StrangeLoopGames/EcoIssues#4662]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Put in materials in crafting table to make a door, put materials in research table to create woodcrafting research

**Expected behavior:**
Created both items

**Actual behavior:**
Timer does not tick down, frozen on 0% permanently despite server reset and moving/replacing tables.

**Comment by Thyriel** [comment]
Are you sure the tables are inside a house and have plenty of free space ?
Check the upper left corner of the table if there is a red (error) or a green dot. If red dot check the tables "status" site for further information on whats wrong
