### ISSUE TITLE
USER ISSUE: Powered Cart falling causes server crash

### ISSUE THREAD

**Issue by Justinc1998** [StrangeLoopGames/EcoIssues#4664]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
After server restart, a powered cart now spawns in the air when approached and loaded into the game.

**Expected behavior:**
Spawned in its original location on the ground.

**Actual behavior:**
Spawns in the air, and when it hits the ground, the server crashed and restarts.

**Comment by MarjieAVolk** [comment]
Could you share the save file where this happens?

**Comment by SeanAtr0n** [comment]
fixed 7.2
