### ISSUE TITLE
USER ISSUE: Sand not being produced 

### ISSUE THREAD

**Issue by TaylorACrock** [StrangeLoopGames/EcoIssues#4666]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I place all the ingredients (stone) on the masonry table to grind to sand and it says Ingredients 100%, Time 0%.

**Expected behavior:**
Produce sand

**Actual behavior:**
Nothing is made. Stuck at "Ingredients 100% Time 0%" perpetually

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4667
