### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by TaylorACrock** [StrangeLoopGames/EcoIssues#4667]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Crafting anything on workbench	

**Expected behavior:**
Create pitch from sand

**Actual behavior:**
Nothing "ingredients 100%, Time 0%"

**Comment by DingoX3** [comment]
The workbench doesnt make pitch from sand. That would be the mason table. It needs to be in a proper room to work or it will just show it has resources but cant craft them.

**Comment by MarjieAVolk** [comment]
Thanks.  Yes, check the Status tab on your crafting table.  Does the table have any unmet requirements?

This should be made less confusing in the next patch.
