### ISSUE TITLE
Exception: object reference. kicked from server

### ISSUE THREAD

**Issue by DingoX3** [StrangeLoopGames/EcoIssues#4668]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
pulling wood cart with dirt in it on dirt road path

**Expected behavior:**
to not be kicked from server

**Actual behavior:**
caught exception : object reference not set to an instance of an object

**Comment by MarjieAVolk** [comment]
I'm sorry, but it will be basically impossible for us to fix this without more information.  I am going to change our error messages to give us more information to debug with, so in the next version we can start tracking down these problems.
