### ISSUE TITLE
Steel Pickaxe missing from Mining Efficiency

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4671]
as seen in the pic steel pickaxe is missing from Mining Efficiency
![image](https://user-images.githubusercontent.com/29722757/36337539-c8ad7462-13ec-11e8-9094-066c8aebab4e.png)

**Comment by ecoemmeck** [comment]
the only pickaxe that seems to stay benefited is the stone. the other pickaxes come and go as a benefited item

![image](https://user-images.githubusercontent.com/29722757/36351744-7b612f0c-1502-11e8-9c51-a558a916feb7.png)

**Comment by MarjieAVolk** [comment]
O.o They come and go - is this during one play session?  Or is this between server restarts?

**Comment by MarjieAVolk** [comment]
As mentioned, this is affecting other tools as well in the same way, such as the pickaxe.

**Comment by ecoemmeck** [comment]
yes after server restarts and just relogging into the server sometimes also changes it

**Comment by craig-jong** [comment]
Seems fixed. Please reopen if it happens in a recent build of the game.
