### ISSUE TITLE
USER ISSUE: Duplicated Excavator!

### ISSUE THREAD

**Issue by Khazul01** [StrangeLoopGames/EcoIssues#4674]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Server was restarted and extra excavator was duplicated but owner did not receive a deed to remove it. The Server has multiple carts that have duplicated in same manner.

**Expected behavior:**
No duplication, or at least a way Admin can remove duplicated items. They cant without a deed.

**Actual behavior:**
Owner of Excavator pickup up item, server restarted and a duplicate excavator appeared in that location, The cart can't be removed as there is no deed. Admin has no rights to delete without the deed.

**Comment by ecoemmeck** [comment]
I know it's only a workaround but can the excavator be unlocked with the tick box at the bottom right when you have the excavator open. This should allow the admin to delete it

**Comment by Khazul01** [comment]
I will try that. Will have to wait till tomorrow for admin.
