### ISSUE TITLE
[SUGGESTION] Learning the Kiln before Bakery Oven and Bloomery

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#4676]
You need Stoneworking 4 to make a Kiln to craft Bricks which are needed to make a Bakery Oven that you learn at Stoneworking 2. Also, you need the Kiln to craft the Bloomery which is also unlocked at Stoneworking 2.

![image](https://user-images.githubusercontent.com/29911902/36337862-b1762d2c-13f4-11e8-816d-8b735a94f0df.png)

It seems that you would need to go to Stoneworking 4 before being able to actually make anything in this tree.

Also: 
Tallow lamp Stoneworking 1 needs a kiln and the planter pots at Stoneworking 3

![image](https://user-images.githubusercontent.com/29911902/36337904-c375824c-13f5-11e8-98c5-bec2e10f8518.png)

Suggestion: 
Moving Kiln and Tallow lamp to Stoneworking 2. 
Bloomery and Bakery Oven to Stoneworking 3.
Planter Pots Square and Round to Stoneworking 4.

**Comment by craig-jong** [comment]
Now you do indeed learn the kiln before the bakery oven.

Not sure when it happened, but I'll close this bug.
