### ISSUE TITLE
Server issue: Bakery oven crashes server

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#468]
Anybody else experienced the server actually going down when using the Bakery Oven? It has happened to me on a number of occasions, sometimes while placing orders. Had occurrences when trying to bake camas, or bake meat; usually when doing larger batches, and sometimes just when clicking around the top left of the window.

It isn't obvious what causes it, so not particularly repeatable. 

Alpha 4.1, Win 10, Chrome51.

**Comment by Breitschwert** [comment]
We had crashes as well, but they happened with the Masonry table, Campfire and the Bakery Oven so far. It wasn't reproducible reliably, so no idea on what to report. I thought it was related to the crafting station getting too full when crafting with items from the players inventory, therefor overloading the workbench inventory and causing an exception. 
I do not have the resources (ingame) to reproduce this however and spawning stuff in to test with /give does not work well, as it only gives single items and not stacks.

**Comment by noblackthunder** [comment]
are those server crashes? if so we need the server crashlog

**Comment by Breitschwert** [comment]
I have attached the dump files.

[Dump.zip](https://github.com/StrangeLoopGames/EcoIssues/files/356942/Dump.zip)

**Comment by newzealdan** [comment]
A bit more on this, it seems to occur when placing large orders on the workbenches (oven, carpentry, concrete etc). So, for example placing an order for a full stack of goods or something in the hundreds of units.

This doesn't happen when placing lots of small orders though.
