### ISSUE TITLE
USER ISSUE: Farming Weirdness

### ISSUE THREAD

**Issue by katabare** [StrangeLoopGames/EcoIssues#4680]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Check the soil of any area that is next to eachother.

**Expected behavior:**
Similar areas right next to each other should have similar moisture and temperature. Moisture should be higher as you check nearer to water.

**Actual behavior:**
The values for temperature and moisture are very random with no sense. Farming is thus harder than it should be.

**Comment by craig-jong** [comment]
This requires much a larger world gen changes to make "correct".

Since this bug was filed, we've increase the possible ranges for plants which should help alleviate this problem until we can get a more fully fleshed out release to fix it.
