### ISSUE TITLE
USER ISSUE: Falling out of the world

### ISSUE THREAD

**Issue by SerpentSunrise** [StrangeLoopGames/EcoIssues#4681]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When standing on a stockpile full of dirt, in a corner, if a shovel of dirt is placed in the same space as the player it pushes the player out of the world

**Expected behavior:**
Pushed the player to an empty space

**Actual behavior:**
Pushes the player into the wall

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
