### ISSUE TITLE
USER ISSUE: research

### ISSUE THREAD

**Issue by kdr264** [StrangeLoopGames/EcoIssues#4682]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Trying to research stoneworking, but when I load up the research bench, research doesn't start	

**Expected behavior:**
research

**Actual behavior:**
no research

**Comment by ecoemmeck** [comment]
Is the research table in a room?

**Comment by ecoemmeck** [comment]
#4123

**Comment by MarjieAVolk** [comment]
Take a look at the 'Status' tab on your research table window.  Are there any requirements for the table that are not met?
