### ISSUE TITLE
USER ISSUE: walking

### ISSUE THREAD

**Issue by kodyroy** [StrangeLoopGames/EcoIssues#4685]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. look up into sky
2. walk (it mostly happens when walking back or sideways)

**Expected behavior:**
the expected behaviour is that the character would walk as per usual

**Actual behavior:**
Instead of walking normally the character walks slow when the walk keys are tapped and "glues" to a "block" and if the walk keys are held down the character continues to walk when keys are released

**Comment by SeanAtr0n** [comment]
changed the char controller, now there are new problems >.>
