### ISSUE TITLE
USER ISSUE: Raining stone

### ISSUE THREAD

**Issue by ShhImBatman** [StrangeLoopGames/EcoIssues#4686]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Mine stone and/or minerals underwater.
2. Watch out.

**Expected behavior:**
Mined materials should drop to bottom of river to be picked up.

**Actual behavior:**
From my experience, the rocks begin to fall from the sky. Not every piece did this right away. But it slowly started falling. It then fell exponentially. My buildings, the land surrounding, and the river floor are now littered with massive amounts of stone, iron, copper, and coal.

**Comment by metachronism** [comment]
sean fixed or at least made this considerably better
