### ISSUE TITLE
Fertilizer not Restacking

### ISSUE THREAD

**Issue by Meronantes** [StrangeLoopGames/EcoIssues#4687]
**Version: 0.7.1.2 beta**

**Steps to Reproduce:**

Get two incomplete stacks of the same fertilizer or split a complete stack of one fertilizer into two stacks. Trying to combine them manually by dragging one stack onto the other will only switch their Slot location.

**Expected Behavior:**

The two incomplete stacks should combine into one stack or fill one stack to its cap of 50 while leaving the excess in another slot.

**Actual behavior:**
Instead of stacking to the Max of 50, they are treated as two different item stacks so they do not combine in anyway. This can be fixed by the Player by putting the two stacks in a Chest and breaking the chest. The two stacks will then combine into one stack if quantity does not exceed the max cap.

**Comment by craig-jong** [comment]
this should be fixed in the latest staging
