### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Blizzarddia** [StrangeLoopGames/EcoIssues#4690]
when i try to join a server a error appear : Connection failed, invalid login info

**Comment by Blizzarddia** [comment]
C: \ Users [username] \ AppData \ LocalLow \ Strange Loop Games \ ECO I tried to delete more still not resolved yet I am getting into server no

**Comment by MarjieAVolk** [comment]
Sounds like your account is broken.  What is your Strange Loop username?  We can look you up and fix your account in our database.

**Comment by rainfarmer** [comment]
@Blizzarddia This seems to have been resolved in support email?

It was a steam linking bug, that bug is fixed now if you want to relink your account to our website you can.
