### ISSUE TITLE
USER ISSUE: Workbench no longer visible

### ISSUE THREAD

**Issue by markjohnwiseman** [StrangeLoopGames/EcoIssues#4691]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I placed the wood workbench. make a bunch of logs and then logged off. I just got on again and although there is a marker in the air, the workbench itself is not rendered inworld.	

**Expected behavior:**
I expect to see the workbench where the marker is	

**Actual behavior:**
The workbench is not visible and no interactions are possible. Clicking the marker does show the details and workbench recipes

**Comment by MarjieAVolk** [comment]
Was this a local game?  That is to say, did the server get restarted between when you logged off and back on?

**Comment by metachronism** [comment]
should be resolved with saving on exit that was fixed earlier
