### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by scythe1990** [StrangeLoopGames/EcoIssues#4693]
I've dropped the required resources in to the research table to research wood construction skill book. Resources 100% time stuck on 0% and not progressing. Table is outside and not in a room.

**Comment by MarjieAVolk** [comment]
The research table requires being placed inside a valid room in order to operate.  Open up the Status tab on the research table window to see what requirements are missing.

In the next patch, we will open up the Status tab by default if something is broken, so this will be less confusing.
