### ISSUE TITLE
Bakery Oven hitbox larger than its Object Graphic

### ISSUE THREAD

**Issue by Breitschwert** [StrangeLoopGames/EcoIssues#470]
Version: Alpha 04.1
Type: Client
OS: Windows 7 64bit Home Premium
Detailed Description of Issue:
The Bakery oven has a larger hit box than the graphic would suggest. It needs more open room in the back than its graphic shows and that needs to be adjusted.

Reproducible? How difficult is it to reproduce?:
It always occurs.

Steps to reproduce bug/issue:
Inside the game, spawn a Bakery Oven and place it, then try to surround it by a wall.

**Comment by Mosseman** [comment]
Also spotted this issue. It be annoying me harties yoho!
