### ISSUE TITLE
USER ISSUE: Wood bug

### ISSUE THREAD

**Issue by NetZero** [StrangeLoopGames/EcoIssues#4701]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Chop some wood
2. When reducing wood to a fiver chunk, try to split the fiver chunck
3. Tadaa - 6 pieces of wood	

**Expected behavior:**
Fiver stack not splittable

**Actual behavior:**
Fiver stack is splittable and the number of wood magically gets higher

**Comment by metachronism** [comment]
want to say this is "creative use of game mechanics" but up to you craig

**Comment by MarjieAVolk** [comment]
I am still unsure why the tree chopping behavior I had written got changed.  It used to just chop at predefined placed basically, based on the yield.  This would not be a problem if it still worked like that.

**Comment by craig-jong** [comment]
Well I liked it back when you could chop them into ITTY BITTY pieces.

I'm closing this as not a bug, though.
