### ISSUE TITLE
USER ISSUE: stone multiplies

### ISSUE THREAD

**Issue by tiker14** [StrangeLoopGames/EcoIssues#4705]
**Version:** 0.7.1.0 beta staging-b9d4fcf5

**Steps to Reproduce:**
place the stone on the wall and below it is least 1 empty block

**Expected behavior:**
stone falls to the ground

**Actual behavior:**
orginal stone falls to the ground 
and the second appears in the place where the stone was placed 

same hapens with ores too

**Comment by tiker14** [comment]
only happens player made stuff but have only hew logs, mortared stone and bricks

**Comment by MarjieAVolk** [comment]
Confirmed this (or something similarly weird) happens pretty much every time, with stone rubble.  It seems to be a visual glitch only - if you log off and back on, there will be the correct # of stone.

**Comment by elfl0rd** [comment]
looks fixed.
