### ISSUE TITLE
USER ISSUE: Error when I load a game

### ISSUE THREAD

**Issue by Creefears** [StrangeLoopGames/EcoIssues#4706]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Open the game
2. Create/Load a game
3. Waiting in the loading
4. After the "Connection" box
5. "Connection Failed" 's box opens

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
