### ISSUE TITLE
USER ISSUE: Crash to title

### ISSUE THREAD

**Issue by SirKahvi** [StrangeLoopGames/EcoIssues#4707]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Gather logs while jumping

**Expected behavior:**
Crash to title

**Actual behavior:**
Crash to title

**Comment by MarjieAVolk** [comment]
Did you get any error messages when this happened?

**Comment by MarjieAVolk** [comment]
Closing due to not enough information.  Likely a duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
