### ISSUE TITLE
USER ISSUE: Cart disapears

### ISSUE THREAD

**Issue by JoeBlack67** [StrangeLoopGames/EcoIssues#4708]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Carts keeps disapearing

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4802 and/or https://github.com/StrangeLoopGames/EcoIssues/issues/4991
