### ISSUE TITLE
USER ISSUE: Cant right click deed

### ISSUE THREAD

**Issue by boots1892** [StrangeLoopGames/EcoIssues#4712]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Claim some land
2. Try to right click the deed.

**Expected behavior:**
It should open the menu.

**Actual behavior:**
Nothing happens.

**Comment by MarjieAVolk** [comment]
I presume you are right clicking while holding the deed?  Have you tried showing your cursor and right clicking on the deed?  Deeds currently don't support right click while holding (see https://github.com/StrangeLoopGames/EcoIssues/issues/2908)

**Comment by boots1892** [comment]
I actually realized I had to right click the item, like you said. I forgot to close this. Thanks anyways.
