### ISSUE TITLE
USER ISSUE: Suggestion or issue with buying selling deeds with land attached

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4714]
![20180217092606_1](https://user-images.githubusercontent.com/15990789/36342495-193af5f8-13c5-11e8-8997-c9c0d2cc732e.jpg)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
make section of some land on deed make a house try to sell it in store

also be nice to be able to come up with ability to create or give out more land claims to people so that we can build towns and sell off land and buildings in those towns.  - as of right now it require admin to gift landmarkers to for people be able to build on them and then sell them. due to lack of enough land claims.

**Expected behavior:**
for the deed with name show up as item that can be put in the store so that we can sell them and way for districts to section of land via claims to create towns that can be sold or gifted to certain professions or people who can afford them.

**Actual behavior:**
only option to sell is unmarked deeds that have no names.

**Comment by ecoemmeck** [comment]
The devs seem to have taken out the town hall which was used to make more claim flags.
However there is a workaround if your an admin you can spawn them and sell them.
The command is "/give claim,20" or however many you want

**Comment by midn8t** [comment]
yah that is what we are doing honestly.

**Comment by MarjieAVolk** [comment]
I agree it would be nice to add some features for buying & selling land.  I think we still plant to change up how deeds work (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/1159), so we could take this into account when we design that.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#256
