### ISSUE TITLE
USER ISSUE: Connection Failed whilst creating or loading a game.

### ISSUE THREAD

**Issue by oskargawl** [StrangeLoopGames/EcoIssues#4715]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Click New / Load
	1a. If New, call the world whatever (I called it just "Eco") 
	1b. If Load, select the world which was created after you
	selected New.
3. Give it a moment to do its thing.
4. Get thrown into desktop (Game minimizes) 
5. Get the game to maximize. 
6. It says: "Connection Failed"	

**Expected behavior:**
It should have probably got me loaded into the game.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Since the game is being minimized, is your firewall or anti virus software blocking the server from running?  (It might be popping up a confirmation dialog, which is causing the game to be minimized)

**Comment by MarjieAVolk** [comment]
Closing due to no response.
