### ISSUE TITLE
USER ISSUE: Server Web Login fails

### ISSUE THREAD

**Issue by VAlex0** [StrangeLoopGames/EcoIssues#4716]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. When playing press g to get to the web interface of the server. Then a login button will appear on the top right corner.
2. When clicking it and entering your credentials, the request goes to Failed to load https://ecoauth.testzone.strangeloopgames.com/game/responsev4?user=...

**Expected behavior:**
The XHR answer should include a CORS header allowing the response to be read from the "local" server webinterface

**Actual behavior:**
response gets dropped because no access-control-allow-origin header is present. please adjust your php/nginx settings ;)

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://123.123.123.123:4567' is therefore not allowed access.`

**Comment by VAlex0** [comment]
devs you do a nice job on the game! And when i see the amount of issues i can only say: good luck i wish you the best.

A potential new favourite game! Greetings, VAlex0

**Comment by VAlex0** [comment]
Update: i had this issue with Chrome 63.0.3239.132 

When i switched to Firefox as default browser it worked. To be precise: I directly got logged in with that token in the url and it showed the correct user. Then i could vote in the election without getting a `You are not logged in error`

**Comment by MarjieAVolk** [comment]
Setting to high priority, as it sounds like this is preventing people from using the server page on some browsers (?).

**Comment by VAlex0** [comment]
Hey Marjie, it definetely prevents me from e.g. voting on the server when using chrome.

How already mentioned:
On Chrome your token login doesn't work. As backup you could use the login button on the server page, but that does not work because of the CORS Error also mentioned above.

So this issues is like handling 2 bugs at once i guess

**Comment by rainfarmer** [comment]
the auth login you posted is not the correct login..
makes me think you were using a staging version of eco.
@VAlex0 can you check if the newest release is working for you on chrome now?
