### ISSUE TITLE
USER ISSUE: Camo Pants Gone

### ISSUE THREAD

**Issue by Swiddow** [StrangeLoopGames/EcoIssues#4717]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Wear Camo Pants
2. Edit Character Look
3. Change Pants Look
4. Save

**Expected behavior:**
Pants look different, but retain status of Camo Pants

**Actual behavior:**
Camo Pants were replaced with a different type of pants, and no going back, they are lost forever.

**Comment by MarjieAVolk** [comment]
@SeanAtr0n Probably we should disable the clothing cycling buttons any subsequent times the avatar ui is opened, in order to prevent people losing their clothes.

**Comment by SeanAtr0n** [comment]
Fixed 7.3.2
