### ISSUE TITLE
connetion failed = cannot play at all

### ISSUE THREAD

**Issue by KotaroInugamie** [StrangeLoopGames/EcoIssues#4719]
Version: 0.7.1.2 beta

Steps to Reproduce:

Try to join any type of world (public or LAN server), create one, or join a server 
Expected behavior:
It should have given me the opportunity to play

Actual behavior:
When I went connect  to game server (public, local or LAN) :
Connection Failed

Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO change nothing

**Comment by MarjieAVolk** [comment]
Is that the full message?  Do you also see 'invalid login info', for example?  Your SLG account may need to be fixed.

**Comment by KotaroInugamie** [comment]
cause by steam account linking is disable

**Comment by MarjieAVolk** [comment]
Yeah, we are no longer supporting linking from steam to an slg account, because this made it very easy for people to refund the game on steam afterwards and then have the game for free.

Did you close the bug because the problem was resolved?  Or was that an accident?

**Comment by KotaroInugamie** [comment]
the problem wasn't solve, just I found on steam forum that slg account is needeed for play.
True?
if it's true I think I'll be refunded the game on steam and take it directly on the eco website, otherwise it's a frankly annoying bug.

**Comment by MarjieAVolk** [comment]
No, you shouldn't need an slg account to play.

Another thing to look into is your firewall and anti virus software - You might try disabling those temporarily to see if they are blocking you.  Also, are you able to create your own server?  If you can't create a server via the 'New' option in game, can you run the Eco Server tool?

**Comment by KotaroInugamie** [comment]
I can create serv via 'New' option, with [...]\steamapps\common\Eco\Eco_Data\Server\EcoServer.exe
but when I  went connect to server I have Connection failed Error

**Comment by MarjieAVolk** [comment]
Yeah looks like you are having some kind of network problem.  I don't really know what to tell you.  For your LAN servers, you could try fiddling with the network settings by opening the server window (/openserverui on the machine running the server, if it is not already open), and going to Network>Config.  If possible, maybe try playing on a different network?

**Comment by MarjieAVolk** [comment]
Oh, another thing you can try is to connect to the server directly via ip address.

**Comment by KotaroInugamie** [comment]
I have this error in network>display on LAN server
NAT detect error: Une exception de type 'Open.Nat.NatDeviceNotFoundException' a été levée.

**Comment by KotaroInugamie** [comment]
I try on linux (ubuntu 16.04.4 LTS) but the game doesn't work propably because of a memory leak (see on ressource monitor)

**Comment by MarjieAVolk** [comment]
Ooh, that's good to note.  Could you send a screenshot of the network>display page?

**Comment by KotaroInugamie** [comment]
![image](https://user-images.githubusercontent.com/19982647/36934679-b8633dce-1eed-11e8-856a-657d7e3701b6.png)

**Comment by KotaroInugamie** [comment]
I try with 7.2.3 update and it work on singleplayer, and public server
Thanks
