### ISSUE TITLE
"/help" displays list of admin commands when you're not an admin

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#472]

**Comment by mariowenig** [comment]
You mean display available commands to user that aren't admins via /help?
I was also thinking it be nice to have a /help as args[1] for all admin commands.
Like:
/vomit /help displaying what action that will take
same as
/give /help -> /give <ItemName>, <Amount>
Both would be helpful for admins and users.

**Comment by metachronism** [comment]
this will be major overhauled soon
