### ISSUE TITLE
Suggestion: Laws: Clearing tree stumps

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#4722]
I'd like to make a law that:

1. taxes people $10 for cutting down a tree
2. allocates tax money to pick up tree debris,
3. allocates tax money to cut out tree stumps.

Currently, I think I can do 1) and 2). The below law should tax $10 per cut tree, and pay $0.50 per tree debris that's picked up.

![image](https://user-images.githubusercontent.com/2173684/36343623-38c3b154-145a-11e8-8e57-e122171ab4c0.png)

However, I don't think there's currently a way to do 3).

Item 3) to clear tree stumps can be done using Contracts (the "Clear Tree Debris and Stumps" contract clause). However that comes out of individual player funds. I'd like to incentivize this out of taxpayer funds.

**Comment by Thyriel** [comment]
Just curious as i like the basic idea of doing something like that with laws but wouldn't that law as you like to do it punish those players that do their best to prevent generating debris at all ? (clearing tree before chopping & using blocks to prevent falldamage)

**Comment by LiaungYip** [comment]
@Thyriel - correct. It's not perfect. There's not really a way to charge a tax per tree debris generated - as the amount of tree debris generated won't be known until the tree hits the ground.

**Comment by MarjieAVolk** [comment]
Fixed in 8.0 (fixed in this PR: https://github.com/StrangeLoopGames/Eco/pull/3199)
