### ISSUE TITLE
plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'plz help i buy this game today and i can join my own world when i trie  then is there a screen 'connection faild'USER ISSUE: 

### ISSUE THREAD

**Issue by arnoud17** [StrangeLoopGames/EcoIssues#4724]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
plz help i buy this game today and i can join my own world when i trie 
then is there a screen 'connection faild'

**Expected behavior:**

**Actual behavior:**

**Comment by Sirisma** [comment]
I almost don't want you to get help simply because you spamed the title section with a copy and past like 10 times.

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
