### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by Gasnir** [StrangeLoopGames/EcoIssues#4726]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
trying to log onto solo/mutliplayer the game gives me connection failed all the time.
firewall and antivirus are not blocking this game

**Expected behavior:**
launched me into game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Have you tried deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
