### ISSUE TITLE
USER ISSUE: World disapear

### ISSUE THREAD

**Issue by zeubkiller** [StrangeLoopGames/EcoIssues#4727]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
A played solo in a generated world
After 3h of play the world started to disappear around me
Currently I have only my house that is still there
Everytime I step outside I fall in the universe and keep failing until I disconect

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861

Does reconnecting help?

**Comment by zeubkiller** [comment]
Yes, It's working fine after I close and reopen the game thanks :)
