### ISSUE TITLE
USER ISSUE: Issue Glass blocks in stockpile = player stuck

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4729]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1 fill up the stock pile with glass blocks
2 player jumps on top of stockpile
3 player falls bettween blocks
4 player stuck cuz he or she cant remove all the blocks to get out.

**Expected behavior:**
player to not fall in bettween glass blocks

**Actual behavior:**
player gets trapped.

we provided a small test example to show what happened to a diff player who had stockpile loaded with glass. we did not load up stockpile with glass
![stevefish](https://user-images.githubusercontent.com/15990789/36344859-452c5960-13e6-11e8-9230-537a3b337ea9.png)

**Comment by Conchipedia** [comment]
use /unstuck and then move in a direction when it gets to the top (i have 9 Stockpile of Glass on my roof 
![snap1742](https://user-images.githubusercontent.com/29383891/36345019-772a73ae-141b-11e8-9076-31cedce1a1f3.png)
and i often fall in trying to finish the Roof 😄

**Comment by midn8t** [comment]
other option is just to, make it so glass blocks in stockpile are just cubes of glass lol.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4849?

**Comment by midn8t** [comment]
I think the thing that help with the stockpiles, with glass and possible other things could get stuck on would be to, represent the object in stockpile as in a wood crate.

so the wooden crate be labeled glass, pipes be labeled iron pipe for example

then you never get stuck when on top of a stockpile.

**Comment by keegan-o** [comment]
Added a unique stockpile/stacked builder for glass in master-- as we will hopefully do for most materials!
