### ISSUE TITLE
USER ISSUE: Suggestion - Large Signs or Billboards bring back

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4732]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
for our stores and contracts we need a large billboard to explain cost of why you selling stuff or what to do exmaple of what go on it 

Glass = cost 1 sand 1 sand = 1 stone  Glass sales = 2 credit 1 stone = 1 credit  so that people understand why we selling our buying things at what rates.
also we where using them to tell people where roads went to what stores locations where along the roads.

small signs do not have enough space for this information...

also diff colors be nice its hard to see the text when your color blind.

**Expected behavior:**

**Actual behavior:**

**Comment by DiploBlock** [comment]
large signs are still in game. they are made in the sawmill. billboards would be good to bring back though

**Comment by midn8t** [comment]
o so u dont make then at carpenter table any more.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#254
