### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by carlialex13** [StrangeLoopGames/EcoIssues#4734]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Caught exception: Object reference not set to an instance of an object.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
I'm sorry, but it will be basically impossible for us to fix this without more information.  I am going to change our error messages to give us more information to debug with, so in the next version we can start tracking down these problems.
