### ISSUE TITLE
USER ISSUE: Tutorial doesn't end

### ISSUE THREAD

**Issue by MrMagolor** [StrangeLoopGames/EcoIssues#4735]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Play through tutorial enough

2.Decide that you've done enough

3. Try to skip

4. Fail

**Expected behavior:**
Removed all the tutorial tabs and ended the tutorial

**Actual behavior:**
May have ended the tutorial, but the tabs were still open

**Comment by aphadeon** [comment]
I can confirm this issue.  Of three playthroughs, one of them left the tutorials incompletable and they would not go away even when I hit skip.  Restarting tutorial "fixed" it.

**Comment by MarjieAVolk** [comment]
The next time this happens, could you guys send your client output log?  It is at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

You could try sending it now, although I fear if you've played a couple times since seeing the error, it won't be there any more.

**Comment by johnkslg** [comment]
Should be fixed in master

**Comment by MarjieAVolk** [comment]
I believe that didn't make it in to the next release in that case.  So will be fixed in two releases.
