### ISSUE TITLE
USER ISSUE: "Wood Pulp" is not "Tree Debris"

### ISSUE THREAD

**Issue by Voelkerz** [StrangeLoopGames/EcoIssues#4737]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Pick up tree debris

**Expected behavior:**
You should pick up "Tree Debris"

**Actual behavior:**
You pick up "Wood Pulp", which is incorrect based on the two descriptions

**Comment by LiaungYip** [comment]
This does get a bit confusing when setting up a Store that buys and sells Wood Pulp. It's easy to confuse the icons and set up a store that buys and sells Tree Debris instead (which isn't an item, and can't be traded.)

**Comment by Thyriel** [comment]
Isn't the issue then that the shop lists non obtainable items at all ?

**Comment by Sirisma** [comment]
^ That was my point but evidently I upset some people
