### ISSUE TITLE
USER ISSUE: Corn fritters recipe

### ISSUE THREAD

**Issue by CauzYolo** [StrangeLoopGames/EcoIssues#4739]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I don't know if it's a bug or this recipe isn't yep implemented but I can't make it. It's not present on the Iron Stove. I don't learn Home Cooking. Should I ?

**Expected behavior:**
Corn fritters recipe should be on the Stove

**Actual behavior:**
Corn fritters recipe isn't on the Stove

**Comment by Lussian-A** [comment]
Corn Fritters is on the Stove, Just not the Cast Iron Stove. Two different stations... a bit confusing yes >.> but oh well.

**Comment by MarjieAVolk** [comment]
Ah yes, keeping this open to request that we change 'Stove' to something more descriptive

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#253
