### ISSUE TITLE
USER ISSUE: Shop Bug

### ISSUE THREAD

**Issue by Sirisma** [StrangeLoopGames/EcoIssues#4740]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open Shop GUI, click Add Entity, do not click on the Add Entity GUI, scroll mouse.

**Expected behavior:**
Scroll Add Entity GUI

**Actual behavior:**
Scroll both Add Entity menu and scroll through hotbar until you click on Add Entity GUI

**Comment by ecoemmeck** [comment]
This also happens when scrolling through tables

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3789
