### ISSUE TITLE
Breaking any cart while someone else is using it results in their model being pulled towards where their hands were connected to it.

### ISSUE THREAD

**Issue by slgbex** [StrangeLoopGames/EcoIssues#4743]
Breaking a lot of stone below a building seems to teleport it on top of the building

I had 1 case where i put a torch into a chest after repeatedly swapping between using and not using a cart with the torch in my hand, caused my teammates to see the fire on the end of the torch and the light it gives off, without it being in my inv or hand

I am the host to a new game, and on every second tree i cut (repeatedly sometimes first tree), as im chopping it up some remaining part of the tree disappeared, and within a few seconds of running around causes the world to stop loading. Only for me, my hostees didnt see the issue, restarting fixed, had to stop cutting trees.

@MarjieAVolk I tagged you in the ticket so you can see images.

**Comment by MarjieAVolk** [comment]
The stone issue already has its own bug.  I split the rest into the following bugs:
https://github.com/StrangeLoopGames/EcoIssues/issues/5004
https://github.com/StrangeLoopGames/EcoIssues/issues/5006
https://github.com/StrangeLoopGames/EcoIssues/issues/5005
