### ISSUE TITLE
USER ISSUE: Pressing 'E' on object sometimes doesn't work

### ISSUE THREAD

**Issue by Ardy-LvX** [StrangeLoopGames/EcoIssues#4744]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Press the 'E' key on a chest, workbench, or campfire.

**Expected behavior:**
Should open with one press.

**Actual behavior:**
It sometimes needs to be pressed or 'mashed' to open.

**Comment by ecoemmeck** [comment]
This maybe because of lag

**Comment by Ardy-LvX** [comment]
It's on my own world and servers.

**Comment by MarjieAVolk** [comment]
Oh, I just realized today, this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/4918  So closing as duplicate.

What I found was that you need to press E twice if you try to reopen a window that you just closed.
