### ISSUE TITLE
USER ISSUE: Road Construction Skill Max Lv 3

### ISSUE THREAD

**Issue by Brianqq3** [StrangeLoopGames/EcoIssues#4747]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Raise skill to max level

**Expected behavior:**
Max Level should be 5 for 80% time reduction for roads. Considering the number of needed to make decent length.	

**Actual behavior:**
Max Level is 3, resulting in only 50% time reduction and 1 minute per block. Not an issue for long servers but for shorter ones it's not helpful enough to make roads viable.

**Comment by Sirisma** [comment]
Roads are powerful and imho shouldn't take only 12 seconds to produce. It isn't like you can't use multiple benches anyway.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#252
