### ISSUE TITLE
USER ISSUE: 'Connection Failed' - Cannot play.

### ISSUE THREAD

**Issue by MrTypos** [StrangeLoopGames/EcoIssues#4748]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I try and create a world .... 'connection failed'

**Expected behavior:**
It should work.

**Actual behavior:**
connection failed

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
