### ISSUE TITLE
You can't move fuel from table inventory into fuel slot

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#475]
You need to drag it into your carry inventory first, switch tabs, then drag it back in.

**Comment by mariowenig** [comment]
Maybe: If its burnable have a button to allow direct transfer to fuel slow.
I.e: Putting wood in campfire, open inventory of campfire, little icon button on logs 'Use as fuel", click will transfer to internal fuel slot?

Or have burnable materials go into fuel slot when right clicking it into the campfire/kiln/etc directly. This would/should only work if the material is not used in any recipes by the device. I.e: Campfire + Coal, there are no recipes in the campfire for coal, therefore if coal is added, dump into fuel slot.

Just ideas.

**Comment by metachronism** [comment]
power has been tweaked, and this should no longer be an issue
