### ISSUE TITLE
You don't get your barrels back

### ISSUE THREAD

**Issue by slgbex** [StrangeLoopGames/EcoIssues#4750]
Just to let you know, when you use your barrels for gas or to make something. You don't get them back. This honestly doesn't follow logic since you use what is inside and not the barrels itself. So I figure I would let others know

EDIT on the post:
I just found another bug dealing with oil.

On my server, we have a line of about 10 pumps. After 4 pumps out, you can't q up anything beyond 1 oil. Like you can tell it you want 999, but it only adds 1 to the 1 q.

https://steamcommunity.com/app/382310/discussions/0/3377008022029944272/

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#251
