### ISSUE TITLE
Kitchen not showing up when selected, disappears when placed.

### ISSUE THREAD

**Issue by lordbane** [StrangeLoopGames/EcoIssues#4751]
I tried this twice. Made a Kitchen, made sure it was in a room that met requirements. Put in in my hotbar and selected it. It did not show up, and when I tried to place it, it disappeared completely. The Mill also does not show up when selected in the hotbar, but it will let me place it. The Modern Hammer and Modern Hoe also will not show up when selected, but otherwise works, Also, the upgraded backpacks don't seem to be working for me.

**Comment by ecoemmeck** [comment]
It might be worth validating your files as something seems amiss here.
Also I'm assuming this is on a single player or private server.

**Comment by lordbane** [comment]
I am playing single player on my own server, How do I validate the files?

**Comment by ecoemmeck** [comment]
if you are running this through steam right click on eco in your library list go to properties then click on local files and then in that tab click on verify integrity of games files

**Comment by lordbane** [comment]
Thanks. I'll give it a shot.

**Comment by MarjieAVolk** [comment]
Did this fix the problem?  I just checked real quick, and I could see the Kitchen as I was placing it.

**Comment by MarjieAVolk** [comment]
Closing due to no response.
