### ISSUE TITLE
Server Issue - Players Kicked Out of Server Every ~ 10min 

### ISSUE THREAD

**Issue by MelBeee** [StrangeLoopGames/EcoIssues#4752]
Hello, 

We encountered the following bug on our server. 

**What's Happening**
Every 10 minutes top chrono, everyone from the server except the owner is being kicked out. The owner plays locally on the same network. We can be doing anything in the game, we haven't found any events happening on the server that could kick us out. The server is up since yesterday (February 16th) and we haven't had any problems until tonight (February 17th) It has runned about 24hours without any problems. Just before it started crashing, there was a Windows update. And when we say every 10 minutes, it's really every 10 minutes. We just started noting down the time the server kicks out the players (23:29, 23:39, 23:49, 23:59, 00:09)

**Environnement**
The server is hosted on a dedicated server located in the owner's house. We are pretty sure it's not ISP or Hardware related. The server is hosted on Windows. (Hopefully we'll be able to host it on Linux soon enough) 

**What We Tried**
The owner has rebooted multiple time the server itself. 
The owner has rebooted multiple time the Eco server. 
The owner has rebooted his router. 

**Log Files**
The owner doesn't have any dump files anywhere. 
We looked in my rep : \AppData\LocalLow\Strange Loop Games\Eco\Crashes and there was nothing dated from today, so it's not related. 
We do have some error exceptions in this file : AppData\LocalLow\Strange Loop Games\Eco\output_log.txt which is here : 
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1734392/output_log.txt)

For more info, you can contact me on github or on discord. NaCMel#6927

If needed, we can do a discord session with the owner, myself and a dev/qa for more info. 

Thanks. 
MelBeee

**Comment by 1431095** [comment]
I'm having the same issue at the moment

**Comment by MarjieAVolk** [comment]
It sounds like there is something weird going on with auth.  Do you see any messages in the server console about disconnecting people?

**Comment by CauzYolo** [comment]
[EN] I had this kind of problem and I resolved it on disabling NAT detection on the Server Settings -> Network -> Config and uncheck DetectNat setting. However you must redirect manualy the desired ports in your gateway NAT settings. 
Sorry for my bad english. If you have some problems or if i'm not clear with my explications don't hesite to comment here.

[FR]
J'ai eu ce genre de problème et je l'ai résolu en désactivant la détection NAT sur les paramètres du serveur -> Réseau -> Config et décochez le paramètre DetectNat. Cependant, vous devez rediriger manuellement les ports désirés dans les paramètres NAT de votre passerelle.
Désolé pour mon mauvais anglais. Si vous avez des problèmes ou si je ne suis pas clair avec mes explications, n'hésitez pas à commenter ici.

**Comment by MarjieAVolk** [comment]
@metachronism Not sure if this problem has already been resolved or what

**Comment by rainfarmer** [comment]
user says 
"The problem is still present in version 7.1.2, there is always a random disconnection even if the time between two disconnections is a little longer."

**Comment by rainfarmer** [comment]
another user says:
I’d solved the problem, I’d just deactivated the « detect NAT » setting on the « network » setting and now it’s fine !
