### ISSUE TITLE
USER ISSUE: No candle light and no damage to bisons

### ISSUE THREAD

**Issue by Gerporgl** [StrangeLoopGames/EcoIssues#4753]
**Version:** 0.7.2.0 beta staging-f1d3308e

**Steps to Reproduce:**
Just reloaded after the update

**Expected behavior:**
Candle should make light when on
Bison should take damage

**Actual behavior:**
The new candles I have added after the update emit no light (previous ones are ok) Also bisons can't be killed

**Comment by MarjieAVolk** [comment]
Do your candles require fuel?  Are they turned off?  Does their 'Status' tab say they are missing any requirements?

As for bison, they do take multiple hits to kill.  Do you see a notification saying the bison took some damage in chat?  Do you see any of your arrows stuck in the bison?

**Comment by Gerporgl** [comment]
I was on the staging version on steam, as soon as opted out of beta it started working again.
Yes I know bisons take multiple hits but the damage would not even display on screen and they had no arrow in them.
The candles had fuel, it would even say turned on /off when I change the state but they would emit no light. Status was showing ok / green.
Anyway, I'll stay on the stable version I think going forward.

**Comment by MarjieAVolk** [comment]
Okay, since these are two separate issues, I'm splitting this into two bugs.  Thanks!
https://github.com/StrangeLoopGames/EcoIssues/issues/4913
https://github.com/StrangeLoopGames/EcoIssues/issues/4914
