### ISSUE TITLE
USER ISSUE: World ending bug

### ISSUE THREAD

**Issue by lightcat** [StrangeLoopGames/EcoIssues#4754]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Literally no idea I hope you have a log reporting system.

**Expected behavior:**
The world doesn't ends and you shouldn't be able to walk up to the edge of it.

**Actual behavior:**
Floating logs, falling great distances.

**Comment by ecoemmeck** [comment]
So it's a flat earth :-p jokes
Have you tried disconnecting and reconnecting

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
