### ISSUE TITLE
(Suggestion) click and drag building

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4756]
so i was playing empyrion awhile back and their building system makes things a little easier by being able to click and drag to build with blocks so that you could build a large structure in a short amount of time

**Comment by MarjieAVolk** [comment]
You mean like drag an item out of your stockpile straight into the world?

**Comment by ecoemmeck** [comment]
as in with the hammer in hand and carried items in the carry slot you click and drag to build a line of 10 or more depending on the block

**Comment by MarjieAVolk** [comment]
Oooohhhh I see now.  Yeah that sounds legit.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#250
