### ISSUE TITLE
USER ISSUE: Connection Failed when loading singel player

### ISSUE THREAD

**Issue by Ravnster** [StrangeLoopGames/EcoIssues#4757]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Loading singel player

**Expected behavior:**
Load the actual game

**Actual behavior:**
The following error message popped up: Connection Failed
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When generating a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
