### ISSUE TITLE
All Station are Offline after Server Crash

### ISSUE THREAD

**Issue by Geuthur** [StrangeLoopGames/EcoIssues#4760]
All Station working room are closed all fine

i go sleep, next day i will play this game and....
go online go in server cant build anything all rooms are closed and i cant do anything

i rebuild some blocks doesnt work nothing works now i cant build anymore
-.-

**Comment by craig-jong** [comment]
I'm not sure exactly what this means - if you could clarify this it would be great. Until then, I'm going to close the issue.
