### ISSUE TITLE
Negative Skillpoints after logging back in

### ISSUE THREAD

**Issue by VAlex0** [StrangeLoopGames/EcoIssues#4761]
Dear devs,
i recognized/had the feeling that my skill point progress did stop at 99% to evolving the next skill point. After some minutes crafting it still was at 99%. To "fix" it i tried to reconnect to the server. When i came back the progressbar was at only ~90% and it said: since you last logged in 9h ago (which by the way was not the time i logged in last time but the time before that one) you lost 88 calories and gained !!!! -1,9 skill points 😄 

![eco bug 1](https://user-images.githubusercontent.com/23259122/36351548-17e4a496-14ac-11e8-8b2d-6d46aa2e40f1.png)

WTF happend there? hahaha

Anyway, after 5 mins or less i had instantly 1 additional skillpoint + again 99% progress in evolviung the next one.
![eco bug 2](https://user-images.githubusercontent.com/23259122/36351549-1814374c-14ac-11e8-924c-5e64a7a9651e.png)

Then reconnected again and now this is the state:

![eco bug 3](https://user-images.githubusercontent.com/23259122/36351550-185de202-14ac-11e8-91fe-5cdd6cdfe9b6.png)

**Comment by VAlex0** [comment]
right now it looks like the progress is working again like it should

**Comment by MarjieAVolk** [comment]
Might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/4613 or https://github.com/StrangeLoopGames/EcoIssues/issues/4311, or might already be fixed depending on what version you are on.  Not sure what the state of this is right now.

**Comment by VAlex0** [comment]
My game version is the same as in #4613 ( 0.7.1.2 beta)

**Comment by craig-jong** [comment]
The bug where the skill point bar was stuck has been fixed, please reopen this if you encounter the bug past 7.3
