### ISSUE TITLE
Need to have a guide  about swimming

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4764]
No idea how to control swimming pushing space bar brings me up someone said "ctrl" makes you go down and it does but you just pop back up again you don't stay down very frustrating

**Comment by Sirisma** [comment]
Are you holding control or just pressing it? I have no problems sinking like a rock and staying at the bottom for extended periods (even though it's a bit silly)

**Comment by cuda70** [comment]
If i hold "clrl" i i sink If i touch anything i go up If i go down and release "ctrl" i go right up i cant stay down and work

**Comment by MarjieAVolk** [comment]
You need to hold ctrl in order to stay down.  You spend calories while under water, so we chose to have people bob back up so they won't lose all their calories if they afk, etc.

**Comment by cuda70** [comment]
I keep control pressed all the time BUT when i click my fish trap i go right to the surface while still holding down control no way i can take fish out of trap HAVE REPEATED THIS 20 TIMES it is not random

**Comment by Nanders** [comment]
this should be a tutorial

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#249
