### ISSUE TITLE
Why are all the plants DEAD

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4765]
They are all dead can run all over the world and only find 1 or 2 live tomatoes or corn lots of mushrooms are alive

**Comment by Sirisma** [comment]
More information is needed here as at face value it makes it sound like either,
A: You generated a new world that unfortunately has very few naturally occuring plants
B: You don't know how to use map layers to find naturally growing plants
C: They were killed through pollution

Plants are very finicky on what it is they need to grow properly.
Corn needs to have temperature from 14.7-15C, Moisture of 29-33% and can't grow with >50%
Tomatoes need temperatures between 13.5-13.7, Moisture of 43-45% and not <35%

Give us more info.

**Comment by cuda70** [comment]
(A) Not my server don't know 
(B) Map layers just darken and show nothing for any item selected
(C) No pollution showing

I kinda think it is related to answer (A)

Thanks

**Comment by MarjieAVolk** [comment]
If it's on a random server, there could be any number of reasons.  Perhaps if there are a lot of players all the live plants have already been harvested.  The server might have edited their plant config, or it might be migrated from an older version, that caused their plants to go odd.  Or it could be a bug, but it's impossible to tell.
