### ISSUE TITLE
USER ISSUE: Game lags out

### ISSUE THREAD

**Issue by DavidEzell** [StrangeLoopGames/EcoIssues#4766]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
After I'm playing for a while and use a bench, when i leave the workstation it lags out the game to 5fps.  I have a gtx 1080 type setup so shouldn't have any issues. Single player style game

**Expected behavior:**

**Actual behavior:**

**Comment by metachronism** [comment]
closing per 7.2 optimizations
