### ISSUE TITLE
USER ISSUE: Server crash when holding Clam property flag and dirt block

### ISSUE THREAD

**Issue by Zehir** [StrangeLoopGames/EcoIssues#4767]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1) Get one dirt block with a shovel
2) Select land plot item with mouse click on item bar of the bottom of the screen
3) drag and drop it to your inventory
4) you should crash the server

**Expected behavior:**
Dont let the user select a world plot with dirt in hand. We have an eroor message if we use a number key but not with the mouse	

**Actual behavior:**
the server crash

**Comment by MarjieAVolk** [comment]
Thanks for the detailed information

**Comment by MarjieAVolk** [comment]
I tried this out on the most recent version, and it doesn't seem to crash anymore.  You can still drag an item into your selected slot that you aren't supposed to be able to select, but it doesn't seem to result in anything terrible happening.

@metachronism If we do want to fix this, I think what we'll want is to expand on the InventoryRestriction class, to support restrictions for specific slots.  Think that is possible and worth it?

**Comment by D3nnis3n** [comment]
Claim Property Flags do no longer exist, moving any item to the shovels toolbar slot while holding dirt causes no issues (but you no longer hold the dirt in a shovel) and if a toolbar slot is free, the shovel will be moved there and selected again.
