### ISSUE TITLE
USER ISSUE: Create New Game

### ISSUE THREAD

**Issue by melges-morgen** [StrangeLoopGames/EcoIssues#4769]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Click New, Configure settings of the game, click Start, wait.

**Expected behavior:**
New Game Created.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Check the 'generate new' box when creating a new world
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
