### ISSUE TITLE
USER ISSUE: Research Table placement.

### ISSUE THREAD

**Issue by ShamblerDK** [StrangeLoopGames/EcoIssues#4770]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place a Research Table outside.

**Expected behavior:**
Just placed it down, making it usable.

**Actual behavior:**

Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
I'm sorry, but it will be basically impossible for us to fix this without more information.  I am going to change our error messages to give us more information to debug with, so in the next version we can start tracking down these problems.
