### ISSUE TITLE
Incorrect information show in map

### ISSUE THREAD

**Issue by Amphysbaenas** [StrangeLoopGames/EcoIssues#4771]
The image below show the problem.
Normaly it must be dirt road on map , but the map show a pile of dirt ... ?

![image](https://user-images.githubusercontent.com/29807119/36355810-462dfba8-14e9-11e8-97d9-bd7328c483c4.png)

**Comment by MarjieAVolk** [comment]
Just to double check - there is nothing on top of the road where you are standing?

**Comment by Amphysbaenas** [comment]
Problem desappear after multiple crash and restart.

As you can see we buid a road with a road tool but several hours after, minimap continu to show dirt and grass

**Comment by SeanAtr0n** [comment]
fixed
