### ISSUE TITLE
USER ISSUE: XRay

### ISSUE THREAD

**Issue by Naheulf** [StrangeLoopGames/EcoIssues#4772]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
See screen-shot

**Expected behavior:**
Sky should not be visible underground.

**Actual behavior:**
We can see void in this corner.

**Screen-shot:**
![image](https://user-images.githubusercontent.com/14990967/36355819-76a29898-14e9-11e8-8db2-8e04fb3934b2.png)

**Comment by keegan-o** [comment]
Probably a chunk builder error, if not it may be the old stone roads too, not sure...

**Comment by metachronism** [comment]
closing as dupe of face remover bugs
