### ISSUE TITLE
USER ISSUE: cannot create on steam

### ISSUE THREAD

**Issue by ascrounch** [StrangeLoopGames/EcoIssues#4773]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
start new game
launch without any parameters
wait...

canoot connect to server

---> i launched the game on steam

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
Temporarily disabling your firewall and/or antivirus software
If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
