### ISSUE TITLE
USER ISSUE: Fell off map

### ISSUE THREAD

**Issue by APinkGamer** [StrangeLoopGames/EcoIssues#4774]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Find a unloaded piece of the world.
2. Walk on it

**Expected behavior:**
Let me walk on it even though it didn't show up	

**Actual behavior:**
Made me fall through the map

**Comment by Naheulf** [comment]
And TP on top if it's only a partial block.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
