### ISSUE TITLE
USER ISSUE: can't pick up lumber..lumber floats

### ISSUE THREAD

**Issue by leodimilo** [StrangeLoopGames/EcoIssues#4776]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
1. Max level logging
2. chop wood into smaller pieces
	

**Expected behavior:**
pieces land in general vincinity and can be picked up	

**Actual behavior:**
pieces defy gravity and float in the air.  When you try to pick them up, an exception is triggered

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3668
