### ISSUE TITLE
USER ISSUE: fishing is very buggy caught fish dont appear in backpack, i didnt think i caught them until relogging

### ISSUE THREAD

**Issue by georgerussellpruitt** [StrangeLoopGames/EcoIssues#4778]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
catch a fish

**Expected behavior:**
an indicator its been caught probably, as well as it appearing in your inventory

**Actual behavior:**
no indicator, nothing in inventory, thought the fish had gotten away, after relogging the fish were in my inventory, otherwise I would have assumed I didn't have any.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
