### ISSUE TITLE
USER ISSUE: Can't connect

### ISSUE THREAD

**Issue by SteveHonel** [StrangeLoopGames/EcoIssues#4779]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When i try to connect to server, i have 'Connection failed, login info'

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Do you see a longer error message than that?

How are you running the game - from steam or from our site download?  Do you see the login bar  at the bottom when you open the game?

**Comment by MarjieAVolk** [comment]
You may want to just get in contact with support@strangeloopgames.com

**Comment by MarjieAVolk** [comment]
Okay, I am pretty sure that this is an error on your account.  So please contact support@strangeloopgames.com, tell them your strange loop username, and tell them you need your strange loop account fixed.
