### ISSUE TITLE
Server Enhancement - No separate inventories (as a private server setting)

### ISSUE THREAD

**Issue by Breitschwert** [StrangeLoopGames/EcoIssues#478]
Version: Alpha 04.1
Type: Client - Enhancement
OS: Windows 7 64bit Home Premium
Detailed Description of Issue:
I would like to request enhancement, where there is a server setting to remove the "per player workbench inventories" for a server, so we have an easier time on a private server with crafting and finding items. It would allow us to store things in the respective crafting tables, rather than having to make a chest for everything and making sure to always move stuff into them. It also would make a bit more sense, since it would be intuitive for a cooperative game, when being run non-public.

**Comment by metachronism** [comment]
most crafting tables now have public + private inventories to use however you wish
