### ISSUE TITLE
Chest & Fertilizer

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#4780]
Right Clicking on a chest with Fertilizer does not put it in the chest/

**Comment by MarjieAVolk** [comment]
What is the deal with fertilizer?  Possibly related to https://github.com/StrangeLoopGames/EcoIssues/issues/3617 and https://github.com/StrangeLoopGames/EcoIssues/issues/4687

**Comment by GophTheGreat** [comment]
Seems to work now.
