### ISSUE TITLE
USER ISSUE: Stockpile name softlock

### ISSUE THREAD

**Issue by aphadeon** [StrangeLoopGames/EcoIssues#4781]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
If you name a stockpile, and while naming press escape, your character becomes nonresponsive.

**Expected behavior:**
Closed the UI and allowed me to move.

**Actual behavior:**
Closes the UI and does not allow me to do anything afterwards until I relog.

**Comment by ecoemmeck** [comment]
From what I've read this seems like a common bug with naming anything then pressing escape instead of clucking on the x

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115
