### ISSUE TITLE
USER ISSUE: Resolution Scaling up on Currency-Screen

### ISSUE THREAD

**Issue by Sonic1305** [StrangeLoopGames/EcoIssues#4784]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Use a 4k-Monitor
2. Play on 1920x1080
3. Press Y for the Currency-Screen

**Expected behavior:**
It should normally do nothing

**Actual behavior:**
Instead it changes the resolution to 4k every time.

**Comment by Nanders** [comment]
Having trouble reproducing this, does this only happen with the currency screen?

**Comment by SlayksWood** [comment]
Can't reproduce for my resolution. I use 1680x1050, change it to 1280x800 and try to reproduce, but can't. We have some changes in 0.8.x version so it seems fixed.
