### ISSUE TITLE
User Issue: Game crash 

### ISSUE THREAD

**Issue by Chillnanigans** [StrangeLoopGames/EcoIssues#4785]
Server/Client
OS
Game crashes after 5-10 minutes every time.
Easy to reproduce basically just try to play the game.

Error: UnityPlayer.dll caused an Access Violation (0xc0000005) in module UnityPlayer.dll at 0033:83c5aa01.

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1735179/error.log)

can't actually attach the dump file here.

**Comment by MarjieAVolk** [comment]
Did you resolve this problem?  I'd like to know what the issue was, if so, so I can help others :)
