### ISSUE TITLE
USER ISSUE: Gold Back Currencies Duplicating

### ISSUE THREAD

**Issue by ShadowBlade72** [StrangeLoopGames/EcoIssues#4787]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
The steps to reproduce as not 100% clear. We suspect that because of a server crash, it's causing mint ID's to be reutilized, thus creating duplicate mints. When players put down a mint, it's causing their mint to show up as an already established gold backed currency.

**Expected behavior:**
Mints are unique to each user and can't be created by other users.

**Actual behavior:**
Each new user who puts down a mint is being linked to an already established gold backed currency.

**Comment by ShadowBlade72** [comment]
To add some additional information:
Users who have the "duplicate" mint have full control of the currency. They can rename it and perform any action that the actual mint owner can perform.

**Comment by SlayksWood** [comment]
Fixed in latest builds.
