### ISSUE TITLE
USER ISSUE: Game crashing when attempting to find/join a server

### ISSUE THREAD

**Issue by yanphi** [StrangeLoopGames/EcoIssues#4791]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Click Join

**Expected behavior:**
Server list should load and I should be able to select a server without the game crashing.

**Actual behavior:**
Would crash after loading a few servers, Sometimes it won't crash and will crash when you try to load into the servers.

**Comment by yanphi** [comment]
Currently I've been using the continue button to join the server I've previously joined in order to play the game, but If the server I'm on crashes and I try searching for it in the server list or when I start up the game and try searching for servers.

**Comment by yanphi** [comment]
I'm also launching the game directly from the .exe file instead of having it launched from steam. Currently my game on steam keeps showing up as "Still Playing" despite quitting out of the game. The way to fix this is to restart steam (There are no processes in task manager I could find) and also because I can't be bothered restarting steam constantly.

**Comment by yanphi** [comment]
These may also help:
![image](https://user-images.githubusercontent.com/5514140/36360313-a0079a00-1587-11e8-94d0-3e3d9c1a87ab.png)
![image](https://user-images.githubusercontent.com/5514140/36360322-b1f53b28-1587-11e8-9593-8af6b9c85f4b.png)

**Comment by metachronism** [comment]
should be fixed in 7.3
