### ISSUE TITLE
USER ISSUE: Mining

### ISSUE THREAD

**Issue by mandyrzlashes** [StrangeLoopGames/EcoIssues#4793]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Clicked on mining tutorial

**Expected behavior:**
should have received a pickaxe

**Actual behavior:**
did not receive a pickaxe - cannot move forward in world

**Comment by MarjieAVolk** [comment]
Had you just completed the mining tutorial?  Did you click on it because you were trying to get the pickaxe?

Do you have any error logs at C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt?

**Comment by mandyrzlashes** [comment]
I hadn't completed it yet for that session. Upon clicking the quest on the
interface to begin it didn't issue the pickaxe.

**Comment by MarjieAVolk** [comment]
Oh I see now.  Okay, well as a workaround, you should get the pickaxe if you skip that tutorial.

**Comment by johnkslg** [comment]
Fixed with new tut system, you now have items in your pack at start.
