### ISSUE TITLE
USER ISSUE: Kicked/Crashed

### ISSUE THREAD

**Issue by D3thM3tal** [StrangeLoopGames/EcoIssues#4796]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Was playing as normal, noticed a tree I cut down enver fell, but sounds were stuck

**Expected behavior:**
Should have just cut and fell over

**Actual behavior:**
Caught exception: Object reference not set to an instance of an object.

**Comment by MarjieAVolk** [comment]
So when did you get kicked?  While you were trying to cut the tree down?

**Comment by D3thM3tal** [comment]
Yeah - I was cutting it down, it was probably server side.
