### ISSUE TITLE
USER ISSUE: Door cant be open with shovel equipped

### ISSUE THREAD

**Issue by xhuy** [StrangeLoopGames/EcoIssues#4797]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Use shovel in Stockpile
2. Try to open door with shovel eqquiped
3. Door cant be open until the item on hand is changed

**Expected behavior:**
Door Open

**Actual behavior:**
Door cant be open

**Comment by fritzr** [comment]
Can confirm

**Comment by jw1986** [comment]
Yeah, I'm experiencing this too.  Just equip the shovel and no door will open.  Switch to an empty slot or another tool and the door opens like a good door should.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3868
