### ISSUE TITLE
Unable to make masonry pitch

### ISSUE THREAD

**Issue by mcneil-ryan-m** [StrangeLoopGames/EcoIssues#4798]
Version: 0.7.1.2 beta

Steps to Reproduce:

1. Place masonry workbench in building before having ability to make masonry pitch.
2. Gain ability to make masonry pitch.
3. Order and provide materials for masonry pitch.

Expected behavior: Workbench makes masonry pitch at a rate of one per twelve seconds.

Actual behavior: Resources is at 100%, time remains at 0% and twelve seconds.

Steps that resolved the behavior: Picking up and replacing the masonry workbench.

**Comment by ecoemmeck** [comment]
is the table in a room?
can you check the status tab of the table and see if its missing anything?

**Comment by mcneil-ryan-m** [comment]
Yes, the table was in a room. Nothing about the room was changed besides picking up and replacing the workbench in the same place.

**Comment by MarjieAVolk** [comment]
Did you check the 'Status' tab on the workbench?  Was there any requirement that was not met?

**Comment by MarjieAVolk** [comment]
Closing due to no response
