### ISSUE TITLE
Electronics skill bug

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#480]
The electronics skill tree has a bug in it, in that you can't up-skill to Level 2 to unlock copper wiring. If you view the image below you can see that I have electronics level 1, but you can see that it also says Max Level. 

![image](https://cloud.githubusercontent.com/assets/6193670/16761556/c1adc6e8-4874-11e6-8f49-b19c34fa6a63.png)

**Comment by craig-jong** [comment]
This is fixed for 4.2
