### ISSUE TITLE
USER ISSUE: Contract "Put items in Container" Bugged

### ISSUE THREAD

**Issue by yanphi** [StrangeLoopGames/EcoIssues#4800]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Create a contract that puts X into X stockpile. Select X items e.g. 200 Stone, Add Recieve Permissions Clause (Otherwise Contract won't auto resolve despite being able to access stockpile with or without clause), add Payment on Completion clause.

**Expected behavior:**
Contract should retain all information and should still be there even with a server crash/restart.

**Actual behavior:**
Contract loses "Items" requested in the clause during a server crash/restart rendering the contract invalid until until re-added back into the clause.

Also people are able to access the storage with or without the permissions clause if a clause specifies X item into X storage but It doesn't autocomplete unless you add the permissions clause.

**Comment by yanphi** [comment]
Update: When re-adding the items back to a contract that has lost the information, even with the permissions clause the contract does not recognise that the objective has been completed.

**Comment by johnkslg** [comment]
Fixed! Thanks for the detailed bug report.

Fixed ‘Items In Container’ contracts not saving list of items.
Fixed inserting items via right-click not counting for contracts.
Fixed display of items left to place in world markers for contracts.
Fixed Contracts to properly handle temporary, limited authorization on objects (you can put bricks into a container you don’t own if you have a contract allowing it, but you can’t remove them).
