### ISSUE TITLE
Teleporting Carts

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#4802]
Can't figure this one out. Main server is on day 12. Never had a problem with carts, but I have one in a mine and went there and it was gone. Not a big deal, as it may have pop up in the world. Found it,  picked it up, placed it back into the mine turn around broke 5 stone blocks got them all turn around and it was gone. Looked on the deed and it was on land about 138m away from me,  on a beach on someone's property. It was not even like a straight line or anything just looked like a random spot. Got it back, place it in the mine again, broke 5 more stone and turned around and cart was gone again. Somehow I think I drop the deed in the cart because the deed was not where I had it when I drop the cart back down so have no idea where it went. If it helps I think I was in the teens on the level.

**Comment by rsgodkilla** [comment]
we also have the same problem when putting carts in or near the mine

**Comment by MasterWhoMW** [comment]
Update. Made a new cart, took it back into the mine(Level 7) and turn around and watched as it just poof! Disappear. Clicked on the deed and saw it was not too far away, underwater, went there. Before I could pick it up again, it disappears again, this time, it when over 800m. Like a dummy, I walked all the way there and went I got there found my missing cart, as well as the one with the deed in it. Pick up both, and then noticed it was really like 10m from I was and I just walk around the world for nothing ;)

**Comment by SeanAtr0n** [comment]
fixed 7.2

**Comment by TapZap1** [comment]
We have still the problem with Version 7.2.3, the cart disapeared after rebooting the server.

**Comment by MarjieAVolk** [comment]
Did the server get explicitly saved before being restarted?  Wondering if the cart position wasn't saved recently or something.

But I believe there are still some cart problems that are ongoing also.

**Comment by TapZap1** [comment]
I explain briefly what I do. I use a Windows 2016 Vserver and start Eco in the task scheduler with the option -nogui. The shutdown.exe is executed twice a day in the Task Scheduler. I use the parameter / r / t 300.
Now the question arises for me, is it possible that the shutdown.exe eco prevents it from storing everything?

**Comment by MarjieAVolk** [comment]
Is shutdown.exe a script written by a third party?  I wouldn't really know what it is doing, if it's doing save things, sure it might be doing them wrong :P

**Comment by TapZap1** [comment]
No no I use the Default Microsoft shutdown.exe. You can find these at the following path: C:\Windows\system32\shutdown.exe

**Comment by MarjieAVolk** [comment]
Oh I see.  In that case, I don't imagine that it is stopping the game from saving.  But it also is probably not saving the game when it is shut down.  So it is possible the cart's position was out of date when you reloaded.  Did you eventually find the cart?  Was it in a reasonablish place?  You can see its position on the cart deed.

**Comment by TapZap1** [comment]
The cart was not from me, but from another player. He had had the cart in a mine. The position in the deed is not displayed. I try to add two screenshots. 
This is how it should be.
![20180314011913_1](https://user-images.githubusercontent.com/37314761/37376812-7a1ed01e-2726-11e8-83c7-b00d0e9d5102.jpg)
This is the Deed of the lost cart. (Look at Deed for. -> There is no Information, so you can not get the Position of the lost cart).
![20180314011830_1](https://user-images.githubusercontent.com/37314761/37376850-adb23790-2726-11e8-9860-e6af7fd354bb.jpg)

**Comment by MarjieAVolk** [comment]
OH the cart is actually gone then.  Could still be a save mismatch problem, eg. if they picked up the cart and the world got saved but their inventory didn't

**Comment by TapZap1** [comment]
So I was lucky and could interview the player. First of all, I have to correct myself, the cart was not in the mine, but exactly where now "Abras" cart is (see screenshot). The player had not had the cart in his inventory. The only thing he noticed was that he put iron in the cart before restarting the server and the iron was back in his hand after the restart. I hope the information can help you.
![20180314022727_1](https://user-images.githubusercontent.com/37314761/37379874-16bcf810-2736-11e8-8d50-b289a1487f4b.jpg)

**Comment by MarjieAVolk** [comment]
Yeah that is sounding like a save issue.  We need to have better support for save and quit.  Right now, you can enter 'exit' into the server console to save and quit.  But it might be annoying to do remotely.

**Comment by TapZap1** [comment]
The problem is, if you start Eco in Task Scheduler, this only worked for me with the option "-nogui", since no user is logged on to the server. Therefore, the console is missing in which one could enter an exit command. Of course, this is not an ideal solution, after all, the server should run as far as possible automatically. I am not an expert, but is there no event that can be intercepted when the Eco is terminated? Something like "On Exit ..". Anyway, I believe that it is a very important issue that the data is stored properly when the Eco task is finished. ECO is first and foremost a server-based game.

**Comment by MarjieAVolk** [comment]
Yes, I agree saving needs to be improved.  I filed this bug to remind myself to work on it: https://github.com/StrangeLoopGames/EcoIssues/issues/6120

If you have any other suggestions for saving features you would like, feel free to post there.
