### ISSUE TITLE
Option: Change  Metric/Imperial and  Celsius/Fahrenheit

### ISSUE THREAD

**Issue by MasterWhoMW** [StrangeLoopGames/EcoIssues#4804]
I Don't wanna be that guy, but a few players would like to see temperatures in Fahrenheit instead of Celsius, as well as meters to feet (kilograms to pounds etc)  So can we have an option to change this?

**Comment by MarjieAVolk** [comment]
Moving this to our new suggestion project: https://github.com/StrangeLoopGames/EcoSuggestions/issues/13
