### ISSUE TITLE
USER ISSUE: Not generating Skill points - Not consuming Calories

### ISSUE THREAD

**Issue by blingjug** [StrangeLoopGames/EcoIssues#4806]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Unknown...
Might have started for 2 of my users on dedicated server (steam based) after turning UseWaste on in the user settings - now turned off - only affecting 2 of 4 users

**Expected behavior:**
Should be generating skill points and consuming calories	

**Actual behavior:**
stomach remains full, and message shows under calories:
"Warning: Waste at maximum, food digestion stopped and no skill points being gained!"

**Comment by MarjieAVolk** [comment]
Yeah the waste feature is not finished, it shouldn't be available in the server options O.o

I believe the only thing these people can do is to use /vomit to clear their stomach.  This is an admin command, so you will need to temporarily make them an admin so they can do it.  Sorry about that!
