### ISSUE TITLE
USER ISSUE: Water physics

### ISSUE THREAD

**Issue by 2tbc1887** [StrangeLoopGames/EcoIssues#4807]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Find water source
2. Create a one high and wide tunnel away to fow it

**Expected behavior:**
Flowed down the path

**Actual behavior:**
Randomly stopped
https://imgur.com/a/QbJvh

**Comment by metachronism** [comment]
this is intended, you need aqueducts to transport water farther distances

**Comment by 2tbc1887** [comment]
https://eco.gamepedia.com/Aqueduct

Umm are they still a thing?
