### ISSUE TITLE
Can't dive anymore

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4808]
Diving / checking fish traps underwater could really need a bit of an overhaul.
I tried to check my fishtraps by holding CTRL to dive. Problem 1 is, as soon as you open them it switches to mousemode and so diving is disabled. No way to stay in range of the fish traps, being able to get something out and still control the character.

Problem 2 is a bit more strange: After i automatically went up because it switched to mousemode i can no longer dive at all. Not even restarting the client does help. I just can't get my head under water anymore

**Comment by Kayamarazaki** [comment]
If you get diving working again, I ude my hammer to pick up the traps then placing them down again. It's not a fix but at least you can retrieve the fishies with it ;)

**Comment by Thyriel** [comment]
A few hours later diving worked again (and the tip with the hammer too).

**Comment by cuda70** [comment]
I am having the same problem with diving i am going to ty the hammer tip though

**Comment by MarjieAVolk** [comment]
Problem 1 was reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/4275

**Comment by MarjieAVolk** [comment]
It's possible that you couldn't dive because you were out of calories.

**Comment by Thyriel** [comment]
I guess it could be possible but hard to say after a few days ^^

**Comment by MarjieAVolk** [comment]
Yeah, didn't think of it until now :P

**Comment by cuda70** [comment]
I am well fed if i HOLD DOWN control i stay down but IF I TOUCH MY FISH TRAP i GO RIGHT UP and i am STILL HOLDING CONTROL DOWN

**Comment by MarjieAVolk** [comment]
@cuda70 Yes, that issue is https://github.com/StrangeLoopGames/EcoIssues/issues/4275

**Comment by Thyriel** [comment]
As the other problem has it's own issue anyway feel free to close this one. If i can reproduce it somewhen and it's not a calorie problem i just report it again. Until then i guess by okhams razor it was missing calories ;)
