### ISSUE TITLE
USER ISSUE: Missing shadow

### ISSUE THREAD

**Issue by LetsDoughNut** [StrangeLoopGames/EcoIssues#4809]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Wait until sunny.

**Expected behavior:**
See your shadow

**Actual behavior:**
Not only see whatever you're holding.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/6280
