### ISSUE TITLE
Oil Refinery only displaying/allowing creation of Biodiesel

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#481]
When you first open the refinery it does briefly show Epoxy, Petroleum and Plastic then quickly disappears.
![image](https://cloud.githubusercontent.com/assets/20417839/16764023/f56bf6b6-487f-11e6-9850-dcb9eaade8ea.png)

![image](https://cloud.githubusercontent.com/assets/20417839/16763924/759e560e-487f-11e6-9fd2-b12f68813643.png)

**Comment by craig-jong** [comment]
This is actually intentional, though the display hiding them too slowly is not. They require a thermal cracking unit in order to be produced. I'm looking for a better way to show this.

Furthermore, much of the endgame tech is scrambled right now. Fixing that for 4.2.

**Comment by craig-jong** [comment]
Gasoline has been moved off of the module for now.
