### ISSUE TITLE
(New Feature) Advanced Crafting Mechanics

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4819]
the idea is this if you have the basic materials that need to be worked into higher materials before construction can begin on a project you can start the project and it will turn the basic materials in to the higher materials then start the construction on the project

so say your making a butchery table that requires logs and boards
as long as you have enough logs to make the required boards and still have the required logs on hand to make the table it will allow you to not have to start a board project it will do the project itself once you order the butchery table

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#248
