### ISSUE TITLE
Corrugated Steel (Pillar)

### ISSUE THREAD

**Issue by Jathor** [StrangeLoopGames/EcoIssues#4821]
The ends of the pillar looks reversed.
![image](https://user-images.githubusercontent.com/36626309/36376471-7fa0af68-1573-11e8-9cb2-738c8141add1.png)
V.7.1.2.

**Comment by keegan-o** [comment]
Agreed! It was an attempt to differentiate it from other columns, but it should match well with the floor block there which it doesn't, so I will flip it.

**Comment by Jathor** [comment]
Cool. While at it. Also noticed the smooth corrugateds texture looks very weird. Not sure it's supposed to be that way!

Den 20 feb. 2018 22:06 skrev keegan-o <notifications@github.com>:

Agreed! It was an attempt to differentiate it from other columns, but it should match well with the floor block there which it doesn't, so I will flip it.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#247
