### ISSUE TITLE
USER ISSUE: pêche

### ISSUE THREAD

**Issue by Banouille** [StrangeLoopGames/EcoIssues#4824]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Pêcher, rencontrer un poisson, le remonter

**Expected behavior:**
Je devrais avoir le poisson dans mon inventaire

**Actual behavior:**
Il n'apparait pas ou des fois aléatoirement dans un coffre. Je suis obligée de me reconnecter pour qu'il apparaisse

**Comment by CauzYolo** [comment]
Bonjour @Banouille , 
En effet j'ai déjç eût le problème et il me semble que le problème est déjà connu. Pour avoir les poissons il suffit de se déconnecter et reconnecter.

**Comment by MarjieAVolk** [comment]
@craig-jong They say when they catch a fish, they have to disconnect and reconnect in order to see it in their inventory.  I think they also say, sometimes the fish appears in a nearby chest instead of in their inventory?  But I am not sure about that.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
