### ISSUE TITLE
USER ISSUE: Desert Sand Block

### ISSUE THREAD

**Issue by Chax59** [StrangeLoopGames/EcoIssues#4826]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When i mine the DesertsandBlock, i got Dirt and not sand. That's not logical

**Expected behavior:**

**Actual behavior:**
When i mine the DesertsandBlock, i got Dirt and not sand. That's not logical

**Comment by MarjieAVolk** [comment]
All of the biome specific blocks get picked up as dirt right now.  It makes some sense, as desert sand can be turned into grass or something else if the climate changes, etc, so this way no matter what the climate is, it will stay as dirt.  At least that's the reasoning.

But I suppose it wouldn't hurt too much to have desert sand get picked up as sand.  Kind of a weird infinite source of sand, which traditionally has been harder to get.

**Comment by metachronism** [comment]
this is intended, all biome types give dirt, (desert dirt being more "dry" than other biomes of dirt)
