### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by NytoO** [StrangeLoopGames/EcoIssues#4827]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**
![first bug graphique](https://user-images.githubusercontent.com/36629711/36386905-ae68d806-1597-11e8-8510-3910bfe71c56.jpg)

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Can you give some more details about when and how this happened?  What is supposed to be in that space?

**Comment by NytoO** [comment]
I don t know, maybe a flying water... it was my first bug.

**Comment by NytoO** [comment]
i found it after few minutes when i create a new world.

**Comment by metachronism** [comment]
looks like an awesome chunk builder exception - closing as a dupe of those :P
