### ISSUE TITLE
USER ISSUE: cant connect on my friends Server

### ISSUE THREAD

**Issue by MPL420** [StrangeLoopGames/EcoIssues#4828]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
follow steam invite --> dont connect 

**Expected behavior:**
It should connect

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by Nomak417** [comment]
Hello, i got the same here with one ov my friend. i've setup a LAN serveur with the application Ecoserver.exe from Steam. forwarded my ports (router and firewall), i can connect on it with no problems, my mate can find it on the 'JOIN' section of the menu, but find it 'offline'. if i invit him via Steam, he got dat 'connection failed' issue with no more explaination on the message. (Same version 0.7.1.2 beta, Steam user (no SLG))

**Comment by MarjieAVolk** [comment]
@MPL420 There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'

**Comment by MarjieAVolk** [comment]
@Nomak417 Can your friend connect if they add your IP address and port as a server directly?  Other than that, I am not sure.  Assigning to @metachronism

**Comment by eliotcougar** [comment]
I've had a brief issue with the server today too... There is some issue with Server parameters naming...
We have the default:
GameServerPort 3000
WebServerPort 3001
and I told my friend to connect to [myIPaddress]:3000, and the connection failed... It took some time to figure out that you should connect to port 3001 instead... That was not obvious at all...

**Comment by Nomak417** [comment]
Heyo, thx for the reply, we've tried that yeah, a while ago, and it don't work too, but we managed to connect both of us with the 'detect NAT' on true (with the uPnP) 
but now, every 5 or 10 minutes, my mate got disconnected 'for 30s inactivity'.

 For my part, i have to launch my game 3 time in a row every time i wanna play, the first time i can connect, then it kick me on the menu with no error message, and the 2nd and 3rd time i got a 'ECO has stop working' message with my server shawn as 'offline' (but my server command is open and the GUI with no problem on the command).
Then i can play normaly, but solo.
Sad part we can play on dedicated servers with no problem, but its a noyce 10 or 15 euros a month ,D
i have litteraly stopped playing, just waiting for the update 7.2 on march 6th, hope it will fixe somethings ,D

**Comment by MarjieAVolk** [comment]
It sounds like you either have a bad connection, or your server doesn't have enough resources perhaps.  Are you also seeing bad performance on the server?  Is it using a lot of CPU/memory?

**Comment by metachronism** [comment]
fixed as of 7.4+
