### ISSUE TITLE
Help with server laws page

### ISSUE THREAD

**Issue by KillDevlicious** [StrangeLoopGames/EcoIssues#4829]
Server, Client or Website?
server DraconicNetwork|Friendly Players Only|No Meteor|Discord https://discord.gg/ZyeB8Gp
http://104.231.25.248:3001/lawsadd.html?
•OS/Web Browser?
windows 10 pro internet explore 

•Detailed Description of Issue:
so when I open the laws page it works but when I try to set make a law it give 404

•Reproducible? How difficult is it to reproduce?

•Steps to reproduce bug/issue:
join the game press l try to purpose a law and hit enter 
•Additional Comments:
my ports 3001 is open

•Client Version? [Alpha .01 for example
if you wanna speak directly to me my discord is https://discord.gg/ZyeB8Gp i'm Devlicious

**Comment by Kayamarazaki** [comment]
For me using the admin command /clearlaw fixes it. 
Basically with statistics being down it wont recognize your game time, as it requires you to play for 2 hours. When you clear the law it should let you use law again :)

**Comment by KillDevlicious** [comment]
Did not work :/

**Comment by KillDevlicious** [comment]
Apparently it kinda works for other people but not me?

**Comment by KillDevlicious** [comment]
Still gives a 404 tho but laws go through for them my page stays froze

**Comment by MarjieAVolk** [comment]
I've never heard of a 404 before.  Could you maybe paste in the link it sends you to when you get the 404?

**Comment by KillDevlicious** [comment]
this is what I get before I hit purpose https://gyazo.com/236ebc6486585a003f33c4690a87f1c3

this is after I hit purpose https://gyazo.com/223481bf60eac56704f9242b08e92ee8

**Comment by KillDevlicious** [comment]
like the page barely works for me and some players ... some have no issues

**Comment by KillDevlicious** [comment]
this is my latest dumps
Crash InvalidOperationException 02185121 https://pastebin.com/k8226aTH
ClientUpdateException InvalidOperationException 02203104  https://pastebin.com/5GGjVRmX
ClientNetworkException Exception 02181041 https://pastebin.com/0tdj0B33

**Comment by rainfarmer** [comment]
trouble shooted with Devlicious, 
Laws don't seem to work for Internet Explorer. 
Will patch soon

**Comment by KillDevlicious** [comment]
Thanks man now I can manage my server lol people taking over the goverment haha

**Comment by rainfarmer** [comment]
This is likely patched in our FireFox and Edge updates
