### ISSUE TITLE
SUGGESTION: Deactivate autolinking

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4831]
It would be really helpfull later if there would be a way to deactivate new chests etc. being automatically linked with everything when placed. (at best as an option at crafting stations etc.)
I have a lot of crafting stuff in my house that only have certain chests linked so the crafted stuff gets sorted automatically but it becomes really tedious that i have to deactivate the link for every new placed chest on 8+ crafting stations manually each time

**Comment by metachronism** [comment]
seems like most a UI design issue - I agree we need easier ways to manage the lists when it becomes larger

**Comment by Thyriel** [comment]
Being able to define a strict output chest/stockpile (multiple so things like lumber still work) would be great too btw ;)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#246
