### ISSUE TITLE
USER ISSUE: connection failed

### ISSUE THREAD

**Issue by bpstudio** [StrangeLoopGames/EcoIssues#4832]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. create a new game

**Expected behavior:**
have a playable game

**Actual behavior:**
The following error message popped up:
after creating gamestatsplugin, the game switch to the steam application, when I switch back to the game, I get the connection failed error. The same happens when I load a game. The game doesn't start at all.
``` connection failed
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Since the game is being minimized - Is your firewall or antivirus software blocking the game, or asking for permission to run the game?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
