### ISSUE TITLE
Toxin

### ISSUE THREAD

**Issue by Toxinn** [StrangeLoopGames/EcoIssues#4836]
**Version:** 0.7.1.0 beta staging-b9d4fcf5

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
Temporarily disabling your firewall and/or antivirus software
If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
