### ISSUE TITLE
SUGGESTION: Make a game setting or form of law that controls the number of disconnected plots a player can have.

### ISSUE THREAD

**Issue by bbaclig** [StrangeLoopGames/EcoIssues#4837]
This will encourage players to connect their property and allow land claims to look more uniform. This will also discourage land claim grieffing.

"Connected plots" should mean the plots are adjacent vertically or horizontally. Diagonal adjacent plots should not count as "connected" in my opinion.

**Comment by Thyriel** [comment]
Good idea :)
May i add here a related claim law suggestion: A law that automatically unclaims land when a player was not online for x days

**Comment by MarjieAVolk** [comment]
Interesting, I haven't thought about restricting connectedness of plots.  Seems like it might solve some problems.  Although we don't want it to be too annoying.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#245
