### ISSUE TITLE
USER ISSUE: In a wall 

### ISSUE THREAD

**Issue by RatNation2828** [StrangeLoopGames/EcoIssues#4838]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
was buildibg then somehow placed a block at my legs and i am now stook in a wall and have no energy to destroy the block 

**Expected behavior:**
pushed me out off wall for building

**Actual behavior:**
its kept me in the wall

**Comment by ecoemmeck** [comment]
Try /unstuck

**Comment by MarjieAVolk** [comment]
Yeah /unstuck is currently what you gotta do.  We are continuing to improve our controller.
