### ISSUE TITLE
Tallow production is reduced by cooking efficiency

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#484]
Creating tallow as a meat byproduct is reduced by cooking efficiency stating it is a cost.

To reproduce:
-Have cooking efficiency at level 1 or higher.
-Can view reduction in campfire and butcher's table, oven. (Have not gotten the stove yet).
-scale up any of the meats that would create tallow (campfire roast, charred meat/sausage, raw sausage, baked meat)
-Verify tallow count and the statement that "Cooking efficiency level y: reduces Tallow cost by x%"

**Comment by craig-jong** [comment]
This is due to tallow being handled the same way as tailings.
