### ISSUE TITLE
USER ISSUE: D/C Reconnect and saw myself and then crashed

### ISSUE THREAD

**Issue by devdanharris** [StrangeLoopGames/EcoIssues#4842]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Play connected to a host/friend
2. Lose connection and get booted to main menu
3. Reconnect immediately
4. Spawn in next to another instance of yourself
5. Bug occurs when attempting to move/do anything	

**Expected behavior:**
Should have removed player instance on d/c and check for duplicate instances before permitting a player to join.

**Actual behavior:**
The following error message popped up:
Caught exception: Object reference not set to an instance of an object
Caught exception: Object reference not set to an instance of an object.
```

**Comment by metachronism** [comment]
clones are fixed as of 7.6+
