### ISSUE TITLE
USER ISSUE: farming is bad currently

### ISSUE THREAD

**Issue by maxpiepenbrink** [StrangeLoopGames/EcoIssues#4844]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. i did some digging and have dug up posts at least a year old frustrated with how opaque and confusing the farming/irrigation system is. I was pretty stoked for this game on paper, my buddy and I broke out into two specialties and I was excited to get some farm stuff going and take over the nutrition side while he did building and stuff -- but i basically put my first 6 hours into this game on a server only to find out that the common advice is "dont bother with farming" after specializing in some farming paths.

2. I made a 9x9 lot on a "yellow" yield zone for my tomatoes, using a soil sampler i mapped out the best spots and tilled the area, planted my seeds and waited. When I came back to the lot they were at 0% ground moisture, but the surrounding ground was 45%, they flapped between 0% to suboptimal %'s, i found an old video with a hydrology meter, but there's not a good way for me to understand what i need to do here, this sucks lol.

**Expected behavior:**
farming should be worth doing, i'm not going to prescribe exactly what it should be, but not what it is now.

**Actual behavior:**
Farming is so poorly implemented right now that the common advice across a few servers I popped into is not to bother.

**Comment by MarjieAVolk** [comment]
Farming has been redone recently, so old tutorials will not be of much use.  Sorry you are having so much trouble.

**Comment by craig-jong** [comment]
We've made some minor tweaks to farming, but we're still looking at doing a more major overhaul. Still, with percentile gathering bonuses and tended plants not dying in alright conditions, I'm going to close this bug report.
