### ISSUE TITLE
USER ISSUE: cant join game

### ISSUE THREAD

**Issue by aceofgmz** [StrangeLoopGames/EcoIssues#4845]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
join a server from friend

**Expected behavior:**
wont connect

**Actual behavior:**
Connection Failed

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Trying to connect to the game via other methods; eg. in-game server list, adding the IP address directly, steam join friend options, etc
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
