### ISSUE TITLE
Hacks detected, teleportation and see-through-walls.

### ISSUE THREAD

**Issue by CompactDisc** [StrangeLoopGames/EcoIssues#4846]
I don't really know how to report on this properly, but someone should probably take a look at this issue.

**What happened**
A user named Carbonitex managed to hack into the server to teleport around and see through blocks.

We caught him red handed and he didn't even deny it. We couldn't film it unfortunately, but here is the conversation that followed after his ban:
![carbonitex 1](https://user-images.githubusercontent.com/6671829/36403837-bc223924-15e7-11e8-8a16-7fb81a541fae.png)
![carbonitex 2](https://user-images.githubusercontent.com/6671829/36403839-be44f9bc-15e7-11e8-903d-8c148ea8308f.png)
![carbonitex 3](https://user-images.githubusercontent.com/6671829/36403840-bf75426a-15e7-11e8-9a17-ae5beaad1024.png)

**Comment by ShinSpitfire** [comment]
In the server saw him zip around in the map.

**Comment by DocMotrin** [comment]
Took us a while to find him

**Comment by CompactDisc** [comment]
It might not be easy to fix, but I think it's worthwhile to do so. The fix you propose would already be a big improvement though, as long as admins are excluded from this check (teleport and fly commands). I can't really see preventing seeing through textures however, since that's easily modifiable client side.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#244
