### ISSUE TITLE
[Suggestion] Having the Option to Choose IN and OUT Storage for large autofilling orders

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#4847]
In the Server i am playing i made two public Crafting rooms on a deed that has everyone attached as Public Mine
1: Mortared Stone room crafts orders to six stockpiles but to fill this order with stone it either has to go into one of these stockpiles (which are full of mortared stone) or physically Right clicked on Masonry Table whilst carrying stone, but because i have the best efficiency i have ordered the extra orders, nobody else seems to be able to right click on the table to fill this, so they leave the stone in a powered cart and i have to manually take out this stone and right click the table, if we had the option to choose an OUT storage then all the mortared stone goes to the six stockpiles quite happily, and have an IN storage that people can fill themselves without the fear of the table deciding that a new Stockpile is there and autofilling this.

2: Brick room crafts to six stockpiles and on that one the only way i found a work around is to break the room when it has filled 5 stockpiles and let people fill the sixth (we are clearing a mine with excavator) if we try and link the excavator storage to the table instead of the table seeing the stone in it it auto fills it with stuff that is crafted.

It is  like the Store, if i link the Power tab of the tables and braziers, when they sell me coal it automatically goes into those free slots and i can add up the desired number to fill each to the maximum and only have that set as a limit for how many i will buy, but i cannot have players sell me stone (because its public i buy for FREE) when i am offline to auto fill the orders because as soon as i add another storage for this stone to go into and be added to the table order, it auto fills up with the crafting items.

So in summing up this argument it would be nice to have the option to choose IN, OUT or BOTH (if just one stockpile) it would be nice to be able to do something else while other players can fill the orders, at the moment when they take away the Mortared Stone it automatically replaces what they took with orders that are complete and just needs collecting which is perfect for OUT selection, and then have a Stockpile that i can choose for IN which will stay empty and the table only takes from this, so players can fill this us manually or via the store in selling.

**Comment by CompactDisc** [comment]
Definitely a big +1.

**Comment by MarjieAVolk** [comment]
I swear I already had a feature bug for this, but can't find it.  I do have this one, which I planned to fix by doing this basically: https://github.com/StrangeLoopGames/EcoIssues/issues/2190

**Comment by Conchipedia** [comment]
i added my Storage idea snapshots to #2190 seeing as you already linked to this one @MarjieAVolk  ❤️
