### ISSUE TITLE
V7.1.2  Glass wall Getting stuck

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4849]
People seemed to get stuck when they jumped on top of the Glass wall.  It happened to multiple people at multiple areas of the Bridge.  They tried using /unstuck, and it took them many times (Spamming the /unstuck command) to finally get freed.  I then took it upon myself to see how hard it was to get stuck, and I found that it only took about  time of jumping on and off the wall for myself to get in the same predicament.  

![image](https://user-images.githubusercontent.com/36024353/36405024-d635d84a-15b3-11e8-934b-f4b79d9fe81b.png)
![image](https://user-images.githubusercontent.com/36024353/36405030-e57a28f6-15b3-11e8-82ae-f98032481ce4.png)

**Comment by sirPattrick** [comment]
Sorry, it wasn't a glass wall, it was the Framed Glass.  Just to make you all aware.

**Comment by SeanAtr0n** [comment]
Fixed in 7.2
