### ISSUE TITLE
USER ISSUE: Cursor not working in game

### ISSUE THREAD

**Issue by KuroiRyuu8** [StrangeLoopGames/EcoIssues#4850]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Open options menu.
2. Click advanced.
3. Cursor no longer works and keeps centering in middle of screen.

**Expected behavior:**
Cursor should select whatever I am trying to select in menu.

**Actual behavior:**
Cursor centers on screen and doesn't select anything.

**Comment by KuroiRyuu8** [comment]
So I just deleted the strangeloopgames folder from %appdata% and now my cursor works again in game. Not sure what this is about but I will leave it open until a dev sees it.

**Comment by MarjieAVolk** [comment]
Sounds like a problem.

**Comment by KuroiRyuu8** [comment]
Just happened to my partner who also owns the game. I had her delete the same appdata folder and then it started working again.

**Comment by GophTheGreat** [comment]
+1 from the support queue, but just deleting inputManager.cfg in the appdata folder worked for them. No need to delete the whole folder.

**Comment by Nanders** [comment]
This might be fixed in my new changes then, will test.
