### ISSUE TITLE
USER ISSUE: Putting work boots in a store crashed me out of a game

### ISSUE THREAD

**Issue by Arti-llery** [StrangeLoopGames/EcoIssues#4852]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Opened store
2. tried to add work boots to store, didn't show up in store when I exited
3. re-entered store tried again, got booted when I clicked on the blank spot to double check the item.

**Expected behavior:**
put the boots into the store

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
I briefly checked out the store just now, and it seems okay.  We haven't gotten reports of this for a while, so I'm going to assume this has been fixed.
