### ISSUE TITLE
wind turbines are ridiculously cheap / easy to make

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#4853]
2 iron bars for a gigantic structure seems very odd, also it makes other power sources even less appealing... you should have to invest heavily for green power sources

**Comment by Conchipedia** [comment]
we surrounded the Lasers with Wind Turbines it didn't take long to charge up the lasers and save the World in **12 days**

**Comment by craig-jong** [comment]
should be fixed in 7.2 staging
