### ISSUE TITLE
USER ISSUE: cart bugged

### ISSUE THREAD

**Issue by alaskanranger** [StrangeLoopGames/EcoIssues#4855]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
tried to pick cart up after placing it then told me must have the deed in inventory got the deed then picked it up. placed it again now cant pull it took everything out and still not able to pull it. going to try to re-log to see if it helps

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Do you see a notification popping up in chat when you try to pull it?  You can't pull carts when out of calories, for example

**Comment by MarjieAVolk** [comment]
Closing due to no response.
