### ISSUE TITLE
USER ISSUE: fell off the world

### ISSUE THREAD

**Issue by alaskanranger** [StrangeLoopGames/EcoIssues#4856]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
world wasnt loaded in and walked off now crazy sound. lol going to try to re-log

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
