### ISSUE TITLE
USER ISSUE: Game Crash report

### ISSUE THREAD

**Issue by officialfarem** [StrangeLoopGames/EcoIssues#4857]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I was mining down at the bottom of the build height, was placing stashes for Smelting tailings. was getting ready to continue my tunnel when i recieved the exception.

**Expected behavior:**
allowed me to mine into stone. Wan't glitched into any walls, or having any issues up to that point.

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Hm, that error message is hard to work off of.  I am going to make sure we send the full stack trace in more cases... Not sure if this is necessarily even related to mining.  So not sure what we can do at present.

**Comment by officialfarem** [comment]
sorry for how vague it was. hahaha I was streaming on Twitch.tv I might be able to find the footage if you would like to take a look. I was hoping that it was sending the full stack exceptions, so I wasn't very detailed.... i'm sorry!!

If  you want a clip of the exception, just let me know! 

best, 
Alex

**Comment by MarjieAVolk** [comment]
If you can get the full stack trace for the exception that would be awesome.  If not, as I mentioned I am going to make sure to send the whole stack trace in the next version, so we can start tracking these down more easily.
