### ISSUE TITLE
USER ISSUE: Stuck in Hewn Log

### ISSUE THREAD

**Issue by Chalo2531** [StrangeLoopGames/EcoIssues#4858]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Be hungry so you can't work with your tools, place Hewn Log facing a wall at your foot level, now you're supposed to be stucked in.

**Expected behavior:**
It shouldn't place a block when your entity is in the space

**Actual behavior:**
Instead it blocked me and I can't break it because I'm hungry and I have no food

**Comment by ecoemmeck** [comment]
Try /unstuck it should get you loose from being trapped in the block

**Comment by Chalo2531** [comment]
[url=https://www.noelshack.com/2018-08-2-1519105651-capture.png][img]https://image.noelshack.com/minis/2018/08/2/1519105651-capture.png[/img][/url

**Comment by Chalo2531** [comment]
Good thing! /unstuck worked, but we can use it as a glitch or something because it pull us over the blocks

**Comment by MarjieAVolk** [comment]
Yeah, /unstuck is the official stance on this for now.  We are continuing to work on our character controller in order to prevent getting stuck.
