### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by duxter** [StrangeLoopGames/EcoIssues#4859]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Launch the game, try to join local server...but I can't

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
connection failed
'Connection Failed'
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'

**Comment by duxter** [comment]
Hello thank you for you answer but my problem is not the one describe, i can't create a local server and join it. My problems are with other online server. I made a very short vidéo to show you the problem you can see it herre : https://www.youtube.com/watch?v=lYJetjWI2es .

For you proposition I already do it: 
**1-** Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO **DONE**
**2-** Temporarily disabling your firewall and/or antivirus software **I DONT RUN FIREWALL ON MY COMPUTER**
**3-** When starting a new world, select 'Generate new' **THAT WORK AND I CAN CONNECT PROBLEM S NOT THAT**
**4-** If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' **I SEND YOU THE LOG FILE WITH ERROR AT THE END.**

[log_180221094929.log](https://github.com/StrangeLoopGames/EcoIssues/files/1743368/log_180221094929.log)

**Comment by MarjieAVolk** [comment]
Thank you for the video, I understand the problem now.  It seems there is something wrong with your account.  I have asked support to look at your account in our database, hopefully they will be able to fix it in a minute.  Will let you know.

**Comment by duxter** [comment]
Hello, ok thank you for the support I m waiting for playing online i can't
use the game at this time due to high collaboration requirment...


2018-02-21 22:56 GMT+01:00 MarjieAVolk <notifications@github.com>:

**Comment by MarjieAVolk** [comment]
Okay, your account has been fixed.  Let me know if that fixes your problems.

**Comment by duxter** [comment]
Hello thank you I'm very happy because you find me the solution!!! I really
love this game thank you for your work. Have a very nice day .

**Comment by MarjieAVolk** [comment]
Glad to hear it :D
