### ISSUE TITLE
If all candidates leave election, an empty election remains in query

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#486]
If all candidates leave election, an empty election remains in query

**Comment by mariowenig** [comment]
Quitters

**Comment by WeaselDog** [comment]
All elections starts with no candidates in 9.0 staging, so this can probably be closed.

**Comment by D3nnis3n** [comment]
Shouldnt have been an issue before either, empty election should just confirm status quo or in 9.0 probably with election days end with no leader, depending on constitution. But have to take a look how exactly it works now.

**Comment by beastyn** [comment]
Election will be empty and auto re,oved when active time is over. Seems fibe fine me.
