### ISSUE TITLE
USER ISSUE: join serveur

### ISSUE THREAD

**Issue by SouSSouS16** [StrangeLoopGames/EcoIssues#4861]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1 fois sur 2 le jeu crash lorsque que je recherche un serveur. Je clic sur Join, ça commence à chercher, et la freeze puis crash.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Sounds like the client is crashing while loading servers in the server browser.

**Comment by yanphi** [comment]
#4791

**Comment by MarjieAVolk** [comment]
Okay, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4791
