### ISSUE TITLE
USER ISSUE: Flickering Objects (MacOS)

### ISSUE THREAD

**Issue by eeoo** [StrangeLoopGames/EcoIssues#4868]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Looking around: 
See sometimes grass, but when i look around: disappearing.
Sometimes i can look through materials.
It is at the start screen the same. Sometimes i can see the objects sometimes they are disappearing,

And: I cannot see the map. Hollow with sometimes a layer is visible. 	

**Expected behavior:**
Can see everything like a normal game.

**Actual behavior:**
Looking around: 
See sometimes grass, but when i look around: disappearing.
Sometimes i can look through materials.
It is at the start screen the same. Sometimes i can see the objects sometimes they are disappearing,

And: I cannot see the map. Hollow with sometimes a layer is visible.

**Comment by eeoo** [comment]
My system: 
Mac mini,
Parallels 13
Windows 10

Graphics : Intel HD 4000
Chip: Intel i7
Working Cache: 16 GB

**Comment by SlayksWood** [comment]
I didn't have similar problems on Mac in latest release builds. People complained about absent greenery at 8.3.0. But this has been fixed for 8.3.1. Will be released in the coming days. If you still have problems, please reopen.
#13032
