### ISSUE TITLE
USER ISSUE: Game crashes to the desktop when I press join from the main menu

### ISSUE THREAD

**Issue by usmarine0622** [StrangeLoopGames/EcoIssues#4869]
When I go into the server browser the game crashed to the desktop. When I create a new local game it's fine. The crash only happens when I go to the server browser. This is a fresh install of Windows 10 Pro, with the latest Nvidia drivers installed. System specs are AMD A10-6800K with a  GTX 980 and 16GB of Ram. This is in windows event logs

Faulting application name: Eco.exe, version: 2017.3.0.63597, time stamp: 0x5a2fec8e
Faulting module name: ntdll.dll, version: 10.0.16299.64, time stamp: 0x493793ea
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process id: 0x12e8
Faulting application start time: 0x01d3aa6268904d21
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 5cf22b68-b916-426f-ab7f-12b27173a0a8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by metachronism** [comment]
should be fixed in 7.3
