### ISSUE TITLE
What fuel is used by

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#4871]
standing torch's ??? So far wont take WOOD-COAL-or TALLOW whats left

**Comment by sirPattrick** [comment]
Torches.  Talk to your Server Admin, they can add more items to that list, or change the time that the items will burn for.  IMO Stone Braziers seem to work much better than standing torches at this time.

**Comment by sirPattrick** [comment]
@MarjieAVolk I think this can be closed, not really a big, just a Support Question.

**Comment by MarjieAVolk** [comment]
The type of fuel that objects take are listed on the Power tab also.
