### ISSUE TITLE
feature request: provide upgrade option to electrically power coal units

### ISSUE THREAD

**Issue by egburr** [StrangeLoopGames/EcoIssues#4872]
Request: An option to "upgrade" units that are powered by coal to allow them to be powered by electricity. 

Benefit: More efficient use of resources. Possibly less pollution?

Units: oil refinery, blast furnace, kiln, stove! (why is this coal powered in the first place??), cement kiln, bakery oven. cast iron stove.

Phasing out the use of coal once electricity is available would be really nice!

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#243
