### ISSUE TITLE
USER ISSUE: Inventory

### ISSUE THREAD

**Issue by icegirl007** [StrangeLoopGames/EcoIssues#4878]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Inventory full of berrys and other fruits and seeds. No chance to drop something off. I cant get something out of the workbench like a chest. What can I do?	

**Expected behavior:**
It should have something to throw away or drop off.

**Actual behavior:**

**Comment by fenume** [comment]
For temp solution you can eat fruits and seeds.

**Comment by MarjieAVolk** [comment]
Yes, you will need to just eat something.  We are working on a trash system to improve this in a future version.
