### ISSUE TITLE
USER ISSUE: Can't connect to server on LAN, but can connect via WAN

### ISSUE THREAD

**Issue by demodude4u** [StrangeLoopGames/EcoIssues#4880]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Run eco server on LAN
2. Connect user A on PC A within LAN
3. Disconnect user A on PC A
4. Connect user B (different steam login) on PC A
5. Try to connect user A on PC B within LAN

**Expected behavior:**
Connected user A on PC B.  Other users on LAN currently on the server have no problems connecting or playing.

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by demodude4u** [comment]
Issue seems to be isolated to this laptop.  I will open up another ticket once I determine the root cause.

**Comment by MarjieAVolk** [comment]
Okay, glad to know you found a way to play.  Here's some things to look for to fix the offending laptop:

* Delete the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software

**Comment by demodude4u** [comment]
Hey @MarjieAVolk , unfortunately for me I still haven't found a permanent workaround/solution for my problem.

I have found out, however, I can connect to the server remotely, but cannot connect to the server within the LAN.  I have tested this by taking my laptop to another location, and also have tested this by using a VPN service.   I have no problems connecting and playing the game as long as I'm not on the LAN with the server.

**Comment by demodude4u** [comment]
I can confirm, both deleting the appdata eco folder and disabling the firewalls did not fix the issue.

**Comment by demodude4u** [comment]
I have discovered that I can connect via LAN, if I connect through my wired connection and not my wireless connection.  It doesn't appear to be an issue with my wireless, because a different laptop has also successfully connected over LAN via wireless.

The only thing that appears to be different is that now the eco server appears in a LAN category in the server browser, whereas over wifi it did not.

**Comment by demodude4u** [comment]
I found a workaround for this problem.  It turns out its something related to all of the additional virtual adapters I have installed on my system (due to vpn's, vm's, docker).  If I turn off all of my network adapters and leave on the one for my internet connection, it works fine.

**Comment by demodude4u** [comment]
![image](https://user-images.githubusercontent.com/2279262/36931467-14640578-1e84-11e8-8fe7-2a1c21461ba2.png)

**Comment by metachronism** [comment]
@demodude4u are you running the server with NAT detection enabled?  we have seen some issues where clients on a LAN can't join themselves via their external IP:PORT mapping generated with the NAT detection.  This might be happening for you.

eg, server running on machine A - detects NAT with external IP of XX.XX.XX.XX and port mapping of 51223->3001

accessing http://IP:51223 fails from within the network, but succeeds for anyone outside the network

**Comment by metachronism** [comment]
this should have been completely fixed as of 7.4+
