### ISSUE TITLE
Housing Algorithm broken for diminishing returns (multi-room)

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#4882]
![](https://cdn.discordapp.com/attachments/362959829641330689/415618893613236265/Screenshot_272.png)

![](https://cdn.discordapp.com/attachments/362959829641330689/415620079733047300/Screenshot_274.png)

**Comment by Nes112** [comment]
What is the intended behavior?

I have an idea, but I'm not sure what the dev intentions are. Here's what I thought it was supposed to be:

* No diminishing returns on furniture of different IDs (e.g. Chair and Table). This is **not** working as intended.
* Diminishing returns on furniture of same ID (e.g. 2 Chairs). This is working as intended.
* Diminishing returns on rooms of same type (e.g. 2nd Kitchen has 75% total value). This is working as intended.

^ Does this list look accurate?

**Comment by Dr-Hardware** [comment]
1. Different TYPES.   currently working, except the TYPE values have been removed from most items. Exceptions include bookshelves, 4 kitchen benches, and all lights.

2. Working

3.  Says its working but as per screenshots above,  is NOT.

**Comment by Nes112** [comment]
I see. Yeah, looks like we need Types brought back. And the extra room bonus fixed to what it should be.

**Comment by stoopiduk** [comment]
I'm having a broader issue of the order of items in the list shuffling between my logging out at night and logging back in the next day. Could there be an option to order furniture within a room for maximum score?

**Comment by Dr-Hardware** [comment]
#4986 relates.

**Comment by Dr-Hardware** [comment]
oh, and the feedback maths is also broken ;-)

![image](https://user-images.githubusercontent.com/32424101/36616642-a2e32532-1938-11e8-9165-79231d142371.png)

**Comment by Nes112** [comment]
@stoopiduk I agree that needs to be fixed, but furniture should not have to be placed in order at all. Sounds like silly micromanagement. Diminishing returns should be determined mathematically regardless of the order in which furniture was placed.

Seems we've identified a few issues with housing bonuses that need fixing.

**Comment by johnkslg** [comment]
Fixed all this stuff
- Order no longer matters
- Diminishing returns works better now
