### ISSUE TITLE
USER ISSUE: After Meteor Event

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4883]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Meteor hits  - all items magically disappear

**Expected behavior:**
metor hits stuff does not vanish unless hit or blows up that way we can keep playing after words, and rebuild

**Actual behavior:**
ahve to use admin to generate workbenchs for people

**Comment by sirPattrick** [comment]
Please elaborate more, every single man made item in the game disappeared?

**Comment by midn8t** [comment]
meteor hit and stuff made in game vanished,
ramps, - tables chest stockpiles, 

everything form one end of the world to other doors.

everything just disappeared, also during the event after the crash if you for example admin in a chest, and put it down it would disappear instantly.

**Comment by Amphysbaenas** [comment]
If the meteor hit your world ..... you just Fail ! Game over NO?

**Comment by midn8t** [comment]
no does not seem to be case

**Comment by MarjieAVolk** [comment]
Aw man, doomsday vault sounds awesome.  :'(

**Comment by johnkslg** [comment]
Fixed the world objects deleting!  And you should see more destruction from meteors now too.  Sorry about the seed vault that is pretty cool.
