### ISSUE TITLE
Set crafting stations on owned property to be Inherited or Whitelist auth by default

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#4884]
Right now, default authorization is Public, meaning anyone can come and queue up a project on an owned crafting station and "lock" the owner out of it. This is especially frustrating to new players who aren't aware of the mechanic.

Makes more sense to make either Inherited or Whitelist be the default authorization setting.

Ideally, this would be retroactive (i.e. an unowned crafting station becomes Inherited or Whitelist when the property it is on is claimed)

**Comment by MarjieAVolk** [comment]
The main reason we start crafting tables as public is to encourage people to charge fees on their tables.  Maybe we should start tables with a fee by default.  Would have the same effect as @Nes112 wants... if the table uses the player's credit and has a fee on it as a default, no one would have any of that player credit until that person also created a store typically.

**Comment by Nes112** [comment]
Part of it is just the annoyance of having to reset the crafting station to the desired auth state each time I pick it up and replace it, which can be quite often when dealing with storage radius.

Of course, everyone has their preferences for how they want their crafting tables set up, so changing the default state is just going to annoy others who want the default to be a certain way.

Making it easier to cancel other players' projects could also fix the issue of public crafting tables being locked up.

Charging fees by default could help, but it could also be frustrating for 2 people working together if crafting tables were all set to charge fees by default.  Then they have to disable the fee every time, or figure out how to use to /pay command, which is not obvious.

Inherited permissions by default just makes the most sense for crafting tables on claimed property. Too bad we can't have it both ways, with tables free to use for those authorized on the property, and fees charged to those who aren't authorized. That would be ideal default state, I think, but I guess the permissions don't work that way.

**Comment by MarjieAVolk** [comment]
Someone who is authorized on your property will not have to pay fees on your table, so it should handle that case too.

Another option might be to either save configuration on your table when you pick it up, or set your own default preferences somehow.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#242
