### ISSUE TITLE
Can't connect to anything

### ISSUE THREAD

**Issue by MRROOKIExx** [StrangeLoopGames/EcoIssues#4885]
Can't Connect to any servers or even singleplayer. Most disappointing game i've ever bought.

**Comment by MarjieAVolk** [comment]
Sorry you're having such a hard time.  What errors are you seeing?  Do you get a message 'Invalid login info' when trying to connect?

**Comment by MarjieAVolk** [comment]
Closing due to no response.  We are continuing to work on connection problems.
