### ISSUE TITLE
Tree Seeds: Get them more easily

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4886]
Maybe you could get them when you chop down the tree itself, instead of the leaves?  Or maybe you could get them from debris?  Or I guess there could be another debris-like drop that gives seeds or something, if art team wants to support that.

**Comment by Nes112** [comment]
Making them a low-% drop chance from Tree Debris would be the clear choice. It would eliminate some of the mystery around how to acquire tree seeds.

As someone who has spent a lot of time doing the "jump-and-chop" minigame trying to get tree seeds, I'll say the current mechanic is not very fun, and leaves trees looking ugly and bare.

**Comment by Thyriel** [comment]
I really like the idea of having to clear a tree before chopping it down so if that would be changed to just chop it down and get seeds from debris it would eliminate a nice feature.
The only problem with the current implementation is that it's hard to reach the leaves (and a bit hard targeting them as it's often a very small hitbox).

In my opinion a good solution would be:
- count chopping branches as if you would have chopped the leaves too (so you get seeds)
- increase seed chances (on my server i have set them to 0.9 chance / 1 min / 2 max which results in a fair amount with no skill and a good amount with forest forager 1-2)
- add a ladder to easily climb up trees so we don't need to play a jumping game or chop trees like in minecraft by place-jumping blocks

**Comment by Nes112** [comment]
It would also be nice to be able to harvest tree seeds without chopping down trees, so maybe a nice, more streamlined way of doing it would be to have tree branches generate a few tree debris on the ground when they are chopped off.

Targeting the leaves vs the branch is really annoying and finicky. Oftentimes it looks like you're targeting the leaves but are actually chopping the branch. Targeting any part of the leaves/branch should just start chopping the branch, imo. I would not miss leaf chopping if it were eliminated altogether.

**Comment by stoopiduk** [comment]
I quite enjoy the idea of harvesting seeds from the leaves, but the addition of a tree climbing perk would make this much more straight forward and enjoyable.
The issue we've found on our server is not one of acquiring seedlings, but of finding adequate soil to plant them in. Clearing a small area in the middle of a lush forest often shows the soil as an awful match, despite healthy trees all around (but not so close as to smother). This is a huge disincentive to reforesting, picking around with the sampler is dull work, and it's not always clear what specs you're looking for in a sample.

**Comment by SeanAtr0n** [comment]
this is fixed w/ 8.0
