### ISSUE TITLE
Can we visually communicate temperature/soil moisture information better?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4890]
Right now all we got is biomes, which help but are not very precise.  Other than that, there's just the Soil Sampler to tell what the temperature/moisture is.  I'm wondering if there's something we can do (that doesn't require tons and tons of art) to visually indicate those things.  For example, maybe we could have snowflakes falling if it is really cold, have more falling based on how cold it is... or have like a heat wave effect for really hot places.  Less sure about what soil moisture would look like.  But I think this would help to make farming more intuitive and speed up the turn around time for finding a good plot of land.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#240
