### ISSUE TITLE
Aqueducts are not discoverable

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4891]
Aqueducts being a form of brick is pretty odd in general, imo, but the biggest problem is that they are not discoverable.  You can't search for them or link to them; you don't see them in any recipe lists; etc.

**Comment by Conchipedia** [comment]
aqueducts are hiden in brick build which i think is wrong, they should have there own recipe like they always used to, seeing as they are really only square blocks that are made into a v or u shape to make water flow down the gap

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#239
