### ISSUE TITLE
Suggestion: Settings for housing SP/day

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4892]
Would be great to have a seperate setting (along the already existing MaxHousingSkillRate) to set a housing SP mulltiplier. Without such a setting housing becomes less and less worth it the higher the passive SP multiplier is set on a server.

**Comment by johnkslg** [comment]
Changed the way this works, theres no longer a max, but soft-caps which can be configured in the mods folder.
