### ISSUE TITLE
Plastic Texture

### ISSUE THREAD

**Issue by sirPattrick** [StrangeLoopGames/EcoIssues#4894]
I have no Idea if this is a known bug or not, but there is no Texture for Plastic in the Stockpile, i haven't placed it down to see if it has a texture on the ground.
![image](https://user-images.githubusercontent.com/36024353/36461029-166d36c4-1681-11e8-8efa-a675f01ce99a.png)

**Comment by ecoemmeck** [comment]
from what i've read plastic will be going into chests in the next update

**Comment by MarjieAVolk** [comment]
Yes, plastic should not be a block, so this was an error.  We already have a fix for this, which will be in the next release.
