### ISSUE TITLE
Can't log in on website [Website issue]

### ISSUE THREAD

**Issue by Dem9** [StrangeLoopGames/EcoIssues#4897]
Registred on eco website and get some error. Now i can't log in, reset password or something else
I get this error: 
![default](https://user-images.githubusercontent.com/24937149/36468362-33e94026-16f4-11e8-8cb0-2680efe8e32e.PNG)

**Comment by MarjieAVolk** [comment]
What is the username you registered with?  We probably will need to fix your account.

**Comment by rainfarmer** [comment]
you are logging into the forum.

Login or register here: https://ecoauth.strangeloopgames.com
