### ISSUE TITLE
Turning Whitelist "On"

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4900]
When passwords were introduced we were told that whitelists would still work but people seem unable to get whitelist to work since the 'use whitelist' was removed.

Admns have set whitelist with ids  and removed password and servers seems open to the public - anyone can get in.

Servers that were whitelisted prior to the change now find that their whitelist is not working and must set password.

Admins would like to know how to toggle whitelist back on so they can have access control via whitelist along or whitelist and password.

**Comment by MarjieAVolk** [comment]
I believe whitelist alone is not supported now.  You can only use whitelist in combination with password.

**Comment by pamduncan** [comment]
Oh that is too bad, it was a very favorite way to set up servers for many admins that did not want to keep changing passwords if people came and went.  Of course with the white they can secure the password and not have to worry about always change and giving out a new password but many complain that they don't want to use the password at all and that they are use to a whitelist being and alternative to passwords

**Comment by metachronism** [comment]
whitelisted users dont need to enter a password.  just set the password to literally anything, and put users on the whitelist.  they wont need to enter the password ever to join.
