### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by alchemican** [StrangeLoopGames/EcoIssues#4902]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. catching fish

**Expected behavior:**
fish is to find in Inventory

**Actual behavior:**
Fish did not appear. After server restart fish apears in inventory

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
