### ISSUE TITLE
(Suggestion) Weed Pulling

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4903]
Currently, in order to remove grass that has grown into my field, I have to dig the dirt up, place it back down, and then re-till it. Perhaps grass can be removed from fields using a tool without having to excavate the dirt that it's grown on.

**Comment by LiaungYip** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/4185#issuecomment-368166680

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#238
