### ISSUE TITLE
USER ISSUE: Fishing

### ISSUE THREAD

**Issue by pedroms00** [StrangeLoopGames/EcoIssues#4905]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Get a fishing rod
2. go fishing
3. reel the rod in
4. fish in inventory	

**Expected behavior:**
the fish should've been inside my inventory or hotkey bar

**Actual behavior:**
Nothing happens. You have to log out, log back in to see the fish in iventory or hotkey bar

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
