### ISSUE TITLE
Disable phone requirement in official Discord

### ISSUE THREAD

**Issue by fenume** [StrangeLoopGames/EcoIssues#4906]
I don't want give my personal info(phone number) to third party company for talk about game.
Confirmed e-mail must be more than enough.
[Screenshot](https://i.imgur.com/1yqxDYH.png)

**Comment by KillDevlicious** [comment]
It gets rid of spammers/trolls/bots etc thats why they did that I'm guessing

**Comment by MarjieAVolk** [comment]
Yes, we enabled this because mainly a specific individual was creating dozens of fake accounts to harass people.  We've gotten a lot of complaints about this choice, so we are discussing alternatives to keep everyone happy and also un-harassed.
