### ISSUE TITLE
USER ISSUE: MAJOR BUG

### ISSUE THREAD

**Issue by IVARDUBZ** [StrangeLoopGames/EcoIssues#4907]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Entered my house
2. Fell out of the world at a massive speed

**Expected behavior:**
Enter house

**Actual behavior:**
fall out of world

**Comment by MarjieAVolk** [comment]
Sounds like https://github.com/StrangeLoopGames/EcoIssues/issues/4924, or else maybe https://github.com/StrangeLoopGames/EcoIssues/issues/3861 or https://github.com/StrangeLoopGames/EcoIssues/issues/3897

If you have more details to add, here or in one of those, that might help.
