### ISSUE TITLE
Invisible oak tree stumps

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4908]
We have various invisible oak tree stumps on the server that vanished while trying to chop them.
They are still chopable but no calories are used up while chopping them and no matter how long you chop them they never go away.
Main problem is that now that you can't build on the block where they are and we have various streets going through them so carts have sometimes problems getting over them.

Any idea how to get rid of these now ?

Not sure if it's related to that but we have a law active (although i am admin and they vanished when i chopped them)
When attempting to harvest where species is Fir
or Harvest where species is Oak
If admin then allow
Otherwise prevent

**Comment by MarjieAVolk** [comment]
I does sound like the law is related.  But the stumps shouldn't be invisible in any case.  And you should get a message if the law is preventing you.

**Comment by Thyriel** [comment]
Basically the law does work as it should at least. Others get the message that they are not allowed to chop them and i as admin can chop them.
The invisible stumps also seem to have "reduced" collision detection: Building a dirt ramp over them (so they are under the ramp) is possible while putting dirt on them is not.

**Comment by Thyriel** [comment]
Did you add something that searches for this kind of invisible stumps and fixes them in 7.2 ? 
I had today a user reporting an invisible oak stump to me (no law in progress, fresh world generated in 7.2) but a few minutes later when i arrived it had vanished by itself

**Comment by SeanAtr0n** [comment]
looks like the heirarchy is different from cedar & the treewizard assigns the wrong collider as the tree root

**Comment by Nanders** [comment]
That cant be the case, the Hierarchy is exactly the same between Oak and Cedar

**Comment by SeanAtr0n** [comment]
iirc the order of hierarchy mattered for this

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/44122433-ba4ef36e-9fd8-11e8-89f5-3eb6450bad49.png)

**Comment by SeanAtr0n** [comment]
seems like the wizard was picking a collider within Oak_Root to use for the stump collider

**Comment by Nanders** [comment]
Yeah that was the small change I talked about above, even reordering the prefab to match identically doesnt fix the issue.

All of the tree controller classes on the prefab point to the right places too.

**Comment by Nanders** [comment]
Well now I just feel silly

Thanks, Fixed in SVN
