### ISSUE TITLE
7.2.0 feedback

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#4910]
Placement of Items by wire-frame needs improvement - VERY hard to tell what you're going to get, EG a chest - you REALLY need to know what it looks like and focus hard to get it the right way around 
![image](https://user-images.githubusercontent.com/32424101/36498987-1496a736-1794-11e8-9ea8-5f4e640e3636.png)

Signs seem broken.

![image](https://user-images.githubusercontent.com/32424101/36499043-37b70364-1794-11e8-9160-e2fd7c4326a6.png)

I like the center recital dot - and its actually a teardrop that looks a bit weird depending on the angle you're aiming.... and its not 100% accurate yet.

![image](https://user-images.githubusercontent.com/32424101/36499144-761b590c-1794-11e8-8d15-8decd8f29d03.png)

Tool-tip text far more readable - Congrats.  but still drop/disappear randomly and frustratingly when attempting to drill down between recipes.

**Comment by MarjieAVolk** [comment]
Thanks for the feedback.  I've filed these bugs based on what you said:
https://github.com/StrangeLoopGames/EcoIssues/issues/4970
https://github.com/StrangeLoopGames/EcoIssues/issues/4969

I believe we will keep fiddling with the reticle dot
