### ISSUE TITLE
Staging: New candles don't emit light

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4913]
Reported by @Gerporgl

**Comment by XecuteFire** [comment]
When updating my own server to staging, the Torch Lamps all disappeared from the game.
When I craft the new Torch Stand, and I place a torch inside it, this i what I get:
![image](https://user-images.githubusercontent.com/8505358/36506909-fd830b84-1725-11e8-9a4b-3fcf792d5ab6.png)
No lamp visual nor light particule.

**Comment by Thyriel** [comment]
Still bugged in 7.2 release :(

**Comment by keegan-o** [comment]
Not sure to what this refers anymore, standing torch is working in master (and thus should work in 7.3)
![image](https://user-images.githubusercontent.com/14983165/37234902-693ed32c-23af-11e8-887d-bc2ba9fdbacc.png)
