### ISSUE TITLE
Have to press E twice to re-open a world object ui you just closed

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4918]
This seems to be an error in PlayerHeldObject line ~255, something about the previous interaction object being the same.

**Comment by PacifyerGrey** [comment]
I have met the issue as well. I do not see this being connected to tabbing out but I generally need to hit E two times to interact with any object.

**Comment by SeanAtr0n** [comment]
has been fixed for a while 7.4. something

**Comment by seccombew** [comment]
Still happening in 8.1 staging.

**Comment by SeanAtr0n** [comment]
it was fixed, has been un-fixed
