### ISSUE TITLE
Election/ run for office issue affecting some people only /browsers

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#492]
@nappelinis has issues on the dev server running for office, he clicks on "Run for office" button and enters his speech and clicks save. his entry is not registered, what we tried : 
nappalinis : chrome = failed ( no error)
me : chrome = ok,
nappalinis : chrome = failed ( no error)
nappalinis : Edge = failed ( no error)
nappalinis : Firefox = ok.

its kind of hard to test.

i looked at his first attempt and it took a very long time ( over a minute before the site was done thinking)
while my did only take 10 seconds.
Edge was faster (also just 10 seconds bud still failed to register)
Firefox seemd to work.

he both tried to log in via the game and via the law page from the eco account page

**Comment by mariowenig** [comment]
I didn't actually submit via FF.
I logged into law page using FF and my Chrome or IE submittion showed up.
Either Chrome or IE picked it up, must have been delayed. Every time I got dropped back to the Run for Office screen. Until I used FF, which showed Update Speech, meaning it registered.

**Comment by mariowenig** [comment]
This is our first election, it shouldn't show a current leader since there isn't one.
Missing default no leader var/placeholder.
![image](https://cloud.githubusercontent.com/assets/10489431/16879150/49935b18-4a7d-11e6-87af-1622316e073b.png)

**Comment by rainfarmer** [comment]
@mariowenig can you explain this more?

> I logged into law page using FF and my Chrome or IE submition showed up.

**Comment by rainfarmer** [comment]
Also, incorrect world leader is being fixed.
