### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by chackl1990** [StrangeLoopGames/EcoIssues#4920]
**Version:** 0.7.2.0 beta staging-08551408

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Caught exception: The given key was not present in the dictionary.
```

**Comment by MarjieAVolk** [comment]
Were you hunting?  Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4951 under that presumption.
