### ISSUE TITLE
USER ISSUE: Fall through world

### ISSUE THREAD

**Issue by Boldee** [StrangeLoopGames/EcoIssues#4924]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Build a hewn log ground floor on to soil.
2. Edge with mortared stone floor.
3. Build mortared stone wall on top of mortared stone floor.
4. Build Hewn log ceiling.

**Expected behavior:**
Able to walk on top of interface between hewn log floor and mortared stone floor.

**Actual behavior:**
Falling through the world at certain interface positions.

**Comment by MarjieAVolk** [comment]
It would be helpful to attach a screenshot of this.  I am not sure whether this is an art problem or a technical problem, or both.

**Comment by Lagicrus** [comment]
Same issue
https://imgur.com/a/gNn5p screenshot proof @MarjieAVolk 
Got to 23k before I disconnected
Was walking around in the server, I saw grass in front of me, and fell through.

**Comment by Lagicrus** [comment]
Hm, true 
I have walked over that spot before and it has been fine
I THINK I was having connection issues at the same time
Unsure

**Comment by Boldee** [comment]
Sorry for the late reply, previously where highlighted there were two Hewn blocks that had to be replaced with the Stone blocks, only these two blocks caused the fall through world.
![20180305003019_1](https://user-images.githubusercontent.com/23031034/36952945-e3eae1a6-200d-11e8-8b2f-169a75b6639b.jpg)

**Comment by Lagicrus** [comment]
Oh realised I never said
I think I was walking over normal dirt/grass terrain at the time

**Comment by metachronism** [comment]
should be fixed in 7.3
