### ISSUE TITLE
USER ISSUE: Connection Failed to local server

### ISSUE THREAD

**Issue by RatNation2828** [StrangeLoopGames/EcoIssues#4926]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Locally saved game fails on start plugin, error message: Connection Failed. Game window minimizes on atempt to load game.

**Expected behavior:**
Load and play my locally saved game.

**Actual behavior:**
The following error message popped up: "Connection Failed"

**Comment by MarjieAVolk** [comment]
Since the game is minimizing - are you getting a notification from your firewall or antivirus?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
