### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Axpranax** [StrangeLoopGames/EcoIssues#4928]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Hello, i can't launch the game, any help would be welcome. Thanks

**Expected behavior:**

A connection to the game to play

**Actual behavior:**
The following error message popped up:
Connection failed

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
