### ISSUE TITLE
7.2.0 Staging Client Crash Dump attached.

### ISSUE THREAD

**Issue by tazuras** [StrangeLoopGames/EcoIssues#4931]
Had store open and attempted to open economy viewer.
[Crash_2018-02-21_223320.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1746573/Crash_2018-02-21_223320.zip)

**Comment by MarjieAVolk** [comment]
Hey there, sorry we lost track of this issue.

Looks like you've got KERNELBASE.dll caused an Access Violation -- Based on what I found via google, this seems to be a platform level error and not a problem in our code. Some suggestions I saw were (a) you ran out of RAM (sooo make sure nothing else is running I guess?), (b) restart your computer.
