### ISSUE TITLE
[solution found]USER ISSUE: can't launch new game

### ISSUE THREAD

**Issue by jadam11** [StrangeLoopGames/EcoIssues#4935]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
just buy the game, i would like to create and launch my first game.

**Expected behavior:**
nothing

**Actual behavior:**
Could not create save file: path of game.....\..<<name of the game>>.eco already exists
if i m going to my disk and create new game with a different name (to be sure it's not a bug of this files, the new files is create but after the step "servergamestat", game crash on Windows 7 x64.
--------report of Windows --------------------------
Signature du problème :
  Nom d’événement de problème:	CLR20r3
  Signature du problème 01:	EcoServer.exe
  Signature du problème 02:	1.0.0.0
  Signature du problème 03:	5a84a129
  Signature du problème 04:	mscorlib
  Signature du problème 05:	4.7.2117.0
  Signature du problème 06:	59cf513d
  Signature du problème 07:	1077
  Signature du problème 08:	8e
  Signature du problème 09:	System.AggregateException
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	b82e
  Information supplémentaire n° 2:	b82ecfa40b678ebbe9bf12b812067c8e
  Information supplémentaire n° 3:	2d8a
  Information supplémentaire n° 4:	2d8a0098d93e78ef925ab765a38bcc7c

------------------------------------------------------

If i m trying to force the code :
'System.AggregateException' s'est produite dans mscorlib.dll

**Comment by jadam11** [comment]
Resolved: for resolve this bug, you need to launch the game, 
select "new", 
check "generate new" and "start".

**Comment by MarjieAVolk** [comment]
So the default world didn't work, but generate new did?

**Comment by jadam11** [comment]
yes.

**Comment by MarjieAVolk** [comment]
@metachronism Several people have reported not being able to launch a new game with the default settings, but selecting 'generate new' and/or running the server tool works.

**Comment by metachronism** [comment]
im 90% sure this was a localization issue
