### ISSUE TITLE
7.2.0 Staging 08551408-Turning on/off braziers

### ISSUE THREAD

**Issue by Quicksilv3r710** [StrangeLoopGames/EcoIssues#4936]
When attempting to turn on/off a brazier, it does not have an effect on it until you re-log.

**Comment by Malaras** [comment]
Noticed with torch stand also.

**Comment by elfl0rd** [comment]
maybe refers to https://github.com/StrangeLoopGames/EcoIssues/issues/7240

**Comment by WeaselDog** [comment]
This is fixed in the latest version.
