### ISSUE TITLE
USER ISSUE: Don't connecting

### ISSUE THREAD

**Issue by Lukarioll** [StrangeLoopGames/EcoIssues#4937]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Reset the PC
2. Let's connecting...
3. Wait...
4. Wait...
5. Wait...
6. Understand that you will not be able to connect

**Expected behavior:**
I had to connect

**Actual behavior:**
Endless connection

**Comment by MarjieAVolk** [comment]
What were you trying to connect to?  Your own save, or a remote server?  Can you connect to other servers?

**Comment by Lukarioll** [comment]
I'll can't connect to eny servers, and server list is empty.

**Comment by MarjieAVolk** [comment]
In that case, try deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by Lukarioll** [comment]
It helped, but what was the problem? In the Discord could not solve this problem.

**Comment by MarjieAVolk** [comment]
I am not sure, but we have another bug open for this problem: https://github.com/StrangeLoopGames/EcoIssues/issues/4423

For now, anyone who has the problem will just need to delete the folder.
