### ISSUE TITLE
Feedback: Campfire cooking vs. Cooking vs. Advanced Cooking

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4940]
Being the main cook on my server and now that i finally reached Advanced cooking i want to give some feedback on that "profession". Overall it's a very nice profession and i really love how you managed to make food something very important by influencing the skillpoint gain.

First off: It should be explained that the amount of nutrients influence the max skillpoint gain. It took us nearly a week of playing understanding why the max. SP / day increased over time until we finally figured out that the better the food becomes the more nutrients you have the more SP / day you can get. (This becomes especially important later when you start to think if it's worth at all going from campfire food to cooking food)

Tier 1 (Campfire + Butchery):
Some nice selections here, you easily fill a whole chest with all different kind of foods. You always find something to eat when looking at your current nutrition that almost perfectly increases what you need. This tier seems pretty good balanced to me.

Tier 2 (Cooking, Mill, Baking):
There's some things i don't like here:
- Milling & Baking is totally not worth it untill you get advanced baking & adv. cooking. The best nutrition combo is eating Vegetable Stock + Crispy Bacon (and some Tallow to counter low fat). None of these requires anything from mill/baking.
- There is a ton of high vitamin food available, a good amount of other nutritions but NOT A SINGLE high fat food. This either forces you too keep Campfire cooking (Camas mesh) or to eat pure Tallow to counter that.
- Compared to tier 1 (campfire & butchery, all with efficiency 5) the amount of ingredients needed is very high for some recipes, especially the amount of animals needed increases a lot. In my opinion it should be vice versa: The better you get at cooking the less you should need, so avdancing from campfire cooking to real cooking should lower the amount (or at least be equal) of ingredients needed. (Or at least not force you to hunt 10 times more animals for the same amount of food).  With butchery & campfire i could easily make some hundred meals with only 2-3 bisons/elks. But when it comes to bacon (or later even turkey in tier 3) you need like 10-20 animals for the same amount of meals. That doesn't make sense.

Tier 3 (Adv. Cooking, Avd. Baking):
Compared to tier 2 (pure vegetable stock, Crispy Beacon, Tallow) the skillpoint increase with tier 3 food is a bit disappointing, considering that you need an incredible amount of steps to produce it and a lot more specializations then for tier 2 food.
Until tier 3 the increase was always like 20-25 SP / day more from eating gathered food > campfire food > cooking food (Server has x2 SP) but tier 2 food compared to tier 3 food the best i could achieve was like 5-8 more SP / day. (But maybe i didn't found the perfect food combination yet)

All in all it's the very best food system i've ever seen in a game yet but there is quite some more balancing needed. Tier 2 seems a bit odd that the food made without milling / bakery is better then what you can do with baking / milling.
I'm also not sure if it is intended that you unlearn campfire & adv. campfire once you have a good cooking skill. If it's not intended to be like that you should probably take some food from campfire and use it as base ingredients for cooking. (But i'm fine if it is intended that you don't need it anymore then)

And a question at the end: What's up with Cutting Edge Cooking ? Not that i would have unlocked it yet, but according to the tooltips it seems it's only producing stuff with 0 nutrients and 10 calories ???

**Comment by Thyriel** [comment]
Something i totally forgot to mention:
It would also be nice if better food would force you to use ingredients from other biomes then grassland & forest. You already seem to have the base for that in the game with the various salad recipes that require things like rice, prickly pear, mushrooms, firwood, etc. but as there is always a recipe for the same output that does not require these "exotic ingredients" there is currently no need at all to skill any gathering beside grassland & forest.

Imho it would be good to NEED wetlands OR desert at tier 2 and tier 3 would need ingredients from all 5 biomes.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#237
