### ISSUE TITLE
Fish Sync Issue

### ISSUE THREAD

**Issue by mcenderdragon** [StrangeLoopGames/EcoIssues#4941]
Task:
I fished using the Fishing Pole

Expected:
the fish gets into my Inventory

What happened:
The fish was just gone, but after I rejoined the server my inventory was full of fish. AFter further testing I noticed if I drag an Item to the first "empty" slot in my Inventory, so where the fish would be located the Inventory slots update and the fish is shown.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
