### ISSUE TITLE
Housing Permission glitch lets me steal from people sometimes.

### ISSUE THREAD

**Issue by Giggulgar** [StrangeLoopGames/EcoIssues#4942]
I can't open their boxes by opening the boxes... but, if I open their store, or their crafting table... I can hit the Storage tab and access their boxes, but not everyone...
I found it after one of my boxes that was set to Inherited with only me on the access list was empty so I tried to figure out how, but only 1 account and everyone is in bed atm...

**Comment by MarjieAVolk** [comment]
Do you have a save file where I can easily repro this?

**Comment by Baithoven** [comment]
Also when i put my cart near an stockpile or chest i can also accsess  we use 7.3.1 Version Server is 3 days old

**Comment by MarjieAVolk** [comment]
Okay I'm not seeing this happening right now, and auth got some big changes recently, so closing as no repro for now.
