### ISSUE TITLE
USER ISSUE: Error Mining

### ISSUE THREAD

**Issue by plohnes** [StrangeLoopGames/EcoIssues#4944]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Mine Coal

**Expected behavior:**

**Actual behavior:**
Caught exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

**Comment by MarjieAVolk** [comment]
I'm sorry, but this kind of exception is very hard to track down without a more detailed error message.  We will make sure to display a better message in the next version of the game, so we can start fixing these.
