### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by junanas** [StrangeLoopGames/EcoIssues#4945]
CTD while walking

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/1747775/error.log)

**Comment by MarjieAVolk** [comment]
Do you also have a crash dump file?  I can't do much with this file.

**Comment by junanas** [comment]
[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1753024/crash.zip)
here is the file. Had to zip it because github does not allow .dmp files

**Comment by MarjieAVolk** [comment]
I believe you might need to run as an administrator or something like that?  I am not sure though.

**Comment by junanas** [comment]
Yes, not sure. I think it could also be PC related because I got another crash with KERNELBASE.dll as a cause.

**Comment by rainfarmer** [comment]
+1 for error:
KERNELBASE.dll caused an Access Violation (0xc0000005)
  in module KERNELBASE.dll at 0033:1f7792fc.

Error occurred at 2018-02-24_001600.
D:\SteamLibrary\steamapps\common\Eco\Eco.exe, run by Tina.
42% memory in use.
16308 MB physical memory [9332 MB free].
18740 MB paging file [10525 MB free].
134217728 MB user address space [134215857 MB free].

Module 1
C:\Windows\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-05_025422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
C:\Program Files\Bonjour\mdnsNSP.dll
Image Base: 0x510f0000  Image Size: 0x00026000
File Size:  133392      File Time:  2015-08-12_150342
Version:
   Company:    Apple Inc.
   Product:    Bonjour
   FileDesc:   Bonjour Namespace Provider
   FileVer:    3.1.0.1
   ProdVer:    3.1.0.1

Module 3
C:\Program Files (x86)\Steam\tier0_s64.dll
Image Base: 0x6fe70000  Image Size: 0x00372000
File Size:  359712      File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 4
C:\Program Files (x86)\Steam\steamclient64.dll
Image Base: 0x701f0000  Image Size: 0x00df6000
File Size:  14398016    File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 5
C:\Program Files (x86)\Steam\vstdlib_s64.dll
Image Base: 0x71660000  Image Size: 0x0006b000
File Size:  348960      File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 6
D:\SteamLibrary\steamapps\common\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x75a40000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-02-23_184810
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1

**Comment by rainfarmer** [comment]
Another one:

KERNELBASE.dll caused an Access Violation (0xc0000005)
  in module KERNELBASE.dll at 0033:dede4008.

Error occurred at 2018-02-22_145034.
I:\SteamLibrary\steamapps\common\Eco\Eco.exe, run.
28% memory in use.
24505 MB physical memory [17643 MB free].
28089 MB paging file [16331 MB free].
134217728 MB user address space [134212922 MB free].

Module 1
C:\WINDOWS\SYSTEM32\xinput1_3.dll
Image Base: 0x00400000  Image Size: 0x0001e000
File Size:  107368      File Time:  2007-04-04_185422
Version:
   Company:    Microsoft Corporation
   Product:    Microsoft® DirectX for Windows®
   FileDesc:   Microsoft Common Controller API
   FileVer:    9.18.944.0
   ProdVer:    9.18.944.0

Module 2
F:\Program Files (x86)\Steam\tier0_s64.dll
Image Base: 0x616e0000  Image Size: 0x00372000
File Size:  359712      File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:     tier0_s Dynamic Link Library
   FileDesc:   tier0_s Dynamic Link Library
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 3
F:\Program Files (x86)\Steam\steamclient64.dll
Image Base: 0x61a60000  Image Size: 0x00df6000
File Size:  14398016    File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   Steamclient.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 4
F:\Program Files (x86)\Steam\vstdlib_s64.dll
Image Base: 0x63ea0000  Image Size: 0x0006b000
File Size:  348960      File Time:  2017-12-15_205928
Version:
   Company:    Valve Corporation
   Product:    Steam
   FileDesc:   vstdlib_ s.dll
   FileVer:    4.28.51.7
   ProdVer:    3.0.0.1

Module 5
I:\SteamLibrary\steamapps\common\Eco\Eco_Data\Plugins\steam_api64.dll
Image Base: 0x63f10000  Image Size: 0x00040000
File Size:  245536      File Time:  2018-02-07_191702
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    3.92.72.58
   ProdVer:    1.0.0.1
