### ISSUE TITLE
Suggestion: Farming spec and seed producion usability

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4947]
As you already get a lot of seeds with high gathering skills the seed production from farming spec becomes more and more useless. (And with gathering 4/5 you already get so much seeds that it's very annoying to eat them all so you get rid of them)

So my suggestion would be:
- Don't let any plant drop seeds with gathering
- Add a seed recipe for EVERY plant. (imho on max efficiency it should be something like 2 seeds for 1 crop)

This way we would have no seeds that we don't need, we can make all seeds we need, the farming spec would become usefull and farmers would even have something to sell

**Comment by Thyriel** [comment]
Little sidenote on that suggestion: 
I changed ecosim.eco for my 7.2 server (20-30 people actively playing atm) to have that feature and modded the farming skillbook recipe so it requires corn/wheat/tomatoes instead seeds to craft.
After nearly a week now i've got plenty of positive feedback from our farmers that they enjoy it quite a lot having to plan ahead their seed production and not to have a lot spare seeds all the time.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#236
