### ISSUE TITLE
USER ISSUE: Teleport Stones while Mining / Teleport Humans with Stockpiles on the Surface

### ISSUE THREAD

**Issue by Leviatay** [StrangeLoopGames/EcoIssues#4949]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Mine very much and don't take it in your Inventory (Stone pickaxe) ~around 100 blocks on a wall 2 or 3 blocks deep, so much till you can't reach any more blocks
2. (Optional i think) clean the space with your Hands
3. You will find mined blocks on the surface right on Top wehre you mine 
Simular things u can do with a stockpile.
1. Stand on it
2. Fill it with stuff
2.1 Fill it trough a other stockpile
2.2 An other one fills it while u stand on it 
3. U will be Teleport on the Surface (like /Unstuck)

**Expected behavior:**
Mined blocks dosen't Teleport up

**Actual behavior:**
They Teleport up on the Surface

**Comment by metachronism** [comment]
sean adjusted/fixed this
