### ISSUE TITLE
Able to move Fuel icons within the Power window of a workbench

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#495]
Its possible to grab the bottom left corner of the fuel icon and drag it across the window after which you get the icons glitching out a bit.

![image](https://cloud.githubusercontent.com/assets/20417839/16891067/e3ac3730-4b48-11e6-820f-337cf7d651f9.png)

I did this on the bloomery and blast furnace.

**Comment by mariowenig** [comment]
I can make both the icon panels move. and even drag it out of the window.

**Comment by metachronism** [comment]
new power UI should have this fixed
