### ISSUE TITLE
USER ISSUE: Fishing rod don't give fish

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4952]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When I catch a fish using a fishing rod, no fish appears in my inventory On single player everythings works fine, but here (Nitrado server) not.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
