### ISSUE TITLE
REQUEST FOR X3 RATE FOR ALL CRAFT ITEMS(MODS/AUTOGEN)

### ISSUE THREAD

**Issue by JuzuYT** [StrangeLoopGames/EcoIssues#4953]
Hello dear sup. Today I ran into the problem that I can not change the crafting criteria of items and recipes in one click, you need to change each file, but it's difficult for me. Could you make this configuration files and attach in the next message. With a reduced crafting time of recipes and things in x3 Rate. For example from 1 hour to 20 min. Thanks

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#235
