### ISSUE TITLE
When a local server won't start up, display a proper error message

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4956]

**Comment by metachronism** [comment]
have we fixed all of these cases?  I think this bug is too broad/generic and we should close it and add specific bugs for cases of it not doing so

**Comment by MarjieAVolk** [comment]
I think my title wasn't clear enough.  What I meant was specifically when the server crashes while starting up, display the crash message in the popup, instead of connection failed.  Could add it when the local server crashes while running too if possible.

I thought it would be easy, but I tried briefly and wasn't sure how to do it, so maybe it is not easy.
