### ISSUE TITLE
Steam linking doesn't work first try, works second

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#4959]
First try fails with no error message,

second succeeds with message

**Comment by anyweez** [comment]
Data point: just linked my accounts and it worked on the first try -- assuming here you're referring to linking Steam accounts to SLG accounts via strangeloopgames.com.

I bought through Steam, then created an SLG account, and then linked the two.

**Comment by rainfarmer** [comment]
steam linking issues are fixed. if you have issue email support@strangeloopgames.com
