### ISSUE TITLE
Stove recipes not finished or not defined properly

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#496]
This might be similar to #32 , but maybe not.

![image](https://cloud.githubusercontent.com/assets/6193670/16892177/ff1ddff8-4b5e-11e6-88ee-d1ed8c1892f4.png)

If you cook "Charred sausage recipe" at a campfire, you are given a charred sausage that has protein and fat content (and calories too).

![image](https://cloud.githubusercontent.com/assets/6193670/16892181/1f512cc6-4b5f-11e6-9daa-440c17266ecf.png)

If you cook "Sausage recipe" at a stove, you just get something with caloric value and no apparent protein or fat content. The same is true also for the "Preserved meat recipe" and "Seared meat recipe" from the stove. I've tried eating one of these but not conclusive as to whether they contribute to nutrients.

It makes me think these items are ingredients that are meant to be further cooked into a fancy dish at a high level cooking workbench, but haven't been able to develop Expert Research Skill book yet so not sure.

**Comment by mariowenig** [comment]
4.2 still the same post hotfix.
Code states: Carbs = 0, Fat = 0, Protein = 0, Vitamins = 0 for all three recipes in stove.
Stove food still BAD! :)

**Comment by metachronism** [comment]
tech tree getting adjusted heavily for alpha 5, should be addressed then
