### ISSUE TITLE
[Server] Server crash after world might be corrupted

### ISSUE THREAD

**Issue by AODeltaB** [StrangeLoopGames/EcoIssues#4962]
ECO version - 7.1.2
    Expected behavior - Last week, I played with my friends, at the end of the day, I have rebooted the server to make a modification, then I received an error and the server did not start.
    Steps to Reproduce - Load my Game.eco file (which might be corrupt). If i rename it, the new Game.eco load without issue.
This is the output : (I'm on debian 9) and bellow this, there is my core dump and error display on Win10
![screenshot_42](https://user-images.githubusercontent.com/18491516/36565357-7f91d40c-1820-11e8-8c0c-493f02038d3d.png)

![screenshot_41](https://user-images.githubusercontent.com/18491516/36565122-d0208590-181f-11e8-8fd9-18d241431598.png)

[Crash AggregateException 02222623.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1749647/Crash.AggregateException.02222623.zip)

**Comment by MarjieAVolk** [comment]
May be related to https://github.com/StrangeLoopGames/EcoIssues/issues/4305

It looks like you're already running the server as a standalone (rather than launching it through in-game 'Load' option), or I would suggest trying that.

**Comment by metachronism** [comment]
localization issue - should be fixed now (2.2 in US is 2,2 in france which caused issues)
