### ISSUE TITLE
USER ISSUE: holes in the Ground

### ISSUE THREAD

**Issue by dphotograph** [StrangeLoopGames/EcoIssues#4965]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
accedential stepping in an hole, an area on the map on there is no terrain generated

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897
