### ISSUE TITLE
USER ISSUE: Can't set non-integer prices in shop

### ISSUE THREAD

**Issue by WolleTD** [StrangeLoopGames/EcoIssues#4971]
**Version:** 0.7.1.2 beta Linux

**Steps to Reproduce:**
1. Add offer to shop
2. Set price to a decimal number like 1.3

**Expected behavior:**
Price should be set to 1.3

**Actual behavior:**
Price is set to 13

**Comment by MarjieAVolk** [comment]
I have been able to set my prices to a non-integer on all the recent versions.  Is it some peculiarity with how you are entering the number?

**Comment by WolleTD** [comment]
I'm using a german keyboard layout, so I can't use the keypad separator, as it maps to a comma.
There are other issues with character encoding in chat, but "regular ASCII" special characters all work as expected on my keyboard.

The input box also is perfectly fine with the period as input. In fact, the decimal point will stay in the shop UI some time, until it loads it's contents from the actual saved values i suppose.

For other players on the same server it works fine. The character I input, according to xev, is a regular `0x2e` dot.

**Comment by MarjieAVolk** [comment]
Oh, a Linux problem... and/or a German keyboard problem

**Comment by WolleTD** [comment]
Actually nailed it down!

The input box seems to only allow a dot as decimal separator. The conversion class however seems to be locale aware in Mono and wants to separate on a comma. When I launch the game with `LANG=en_US.utf8`, I am able to enter values with decimal point.

The same locale thing happens the other way round: In the economy overview, with my default `de_DE` system locale, decimal values are shown with a comma as separator. With `en_US`, they are dots.

**Comment by MarjieAVolk** [comment]
Awesome, thanks.  Handing it to localization person in that case.

**Comment by Missou** [comment]
Hi, I'm having the same problem but I'm a french linux user and my default LANG value is fr_FR.UTF-8.
export LANG=en_US.utf8 before launching steam did the trick.

**Comment by duxter** [comment]
I'm running a server on ubuntu with mono, all users on the server are using windows version of ECO and we also have the problem on the wole server.
I try to launch the server with: 
`#!/bin/bash
export LANG=en_US.utf8
mono EcoServer.exe -nogui`

But seem not work...

**Comment by ShaydenMac** [comment]
Via Forum: 

"Lubulu87 
I found out by chance that you can set the comma values ​​with the CTRL key. For example, if you type in the value 2 and then press the minus key while holding down the CTRL key, the value will be 1.9 and the value will be kept."

**Comment by johnkslg** [comment]
Fixed!
