### ISSUE TITLE
USER ISSUE: no night - only a day

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4972]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Well, it's no annoing bug, even I can said it's very usefull bug, but... still its a bug :) So on my server time has stop and the sun is still in one position (if I looked at the normal watch, the sun would be on 2 o'clock), but the music turns on from time to time, just like in the morning.

**Expected behavior:**

**Actual behavior:**

**Comment by pamduncan** [comment]
Any chance an admin accidentally type the /day command which sets the world to around noon and keeps the time there?  If this is the case the time timeofdayscale in EcoSim configuration would be at 0 or some other number than 48.  Setting it back to 48 should cure it

**Comment by Arkadia3** [comment]
yes, thank you pamduncan.
