### ISSUE TITLE
USER ISSUE: Plastic being placed on the groudn

### ISSUE THREAD

**Issue by DrBeardPhace** [StrangeLoopGames/EcoIssues#4975]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Had plastic in carrying, placed on groudn	

**Expected behavior:**
Been placed, and then be able to have been picked up again	

**Actual behavior:**
Plastic dissapears, and then appears later in the same spot. does not go into carrying

**Comment by Swiddow** [comment]
I also experienced this exact same issue.

**Comment by MarjieAVolk** [comment]
Plastic was not intended to be a block.  It will be fixed in the next release.
