### ISSUE TITLE
USER ISSUE: Brazier stuck

### ISSUE THREAD

**Issue by meerolz** [StrangeLoopGames/EcoIssues#4977]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place brazier
2. Find a place under brazier
3. Type "/unstuck"

**Expected behavior:**
You should be on top of Brazier

**Actual behavior:**
You stuck in it. The only way to escape, is to brake it with a Hammer. If you have it, of course

**Comment by elfl0rd** [comment]
@D3nnis3n cannot repeat, maybe fixed in unstuck changes.

**Comment by D3nnis3n** [comment]
Yep, i had that tested a while back, too and it did no longer occur. Reopen if it reoccurs.
