### ISSUE TITLE
USER ISSUE: Crafting System Timer

### ISSUE THREAD

**Issue by SilverProphet** [StrangeLoopGames/EcoIssues#4979]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place Items or Meterials into the required box an the Crafting Timer Dosen't Count Down

**Expected behavior:**
Crafting Time should have started to count down

**Actual behavior:**
nothing happens. the craft timer doesn't start
![eco](https://user-images.githubusercontent.com/36752719/36576687-06ea9e84-189e-11e8-8019-faff9396b53b.jpg)

**Comment by MarjieAVolk** [comment]
The status light for your table is red.  That means your table is missing some requirements and can't run. 
 Click on the light, or on the Status tab to see what it wrong.

In the next release, you will be opened to the Status tab automatically when something is wrong, so it should be much less confusing.
