### ISSUE TITLE
extinct animals popping back into existence

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#498]
we unfortunately killed all our hare (mostly due to the the unexplained deaths bug already reported), however the hare population has gone from 0 to +3??!

![image](https://cloud.githubusercontent.com/assets/20417839/16893185/d2375a30-4b83-11e6-8965-9384eb0bc4a5.png)

**Comment by newzealdan** [comment]
Don't worry, another unexplained die off event got the hares in the end

![image](https://cloud.githubusercontent.com/assets/6193670/16946076/eca44336-4dfb-11e6-9089-5ea866153cbc.png)


:(

**Comment by metachronism** [comment]
they hatched from eggs probably :)

this is reworked in alpha 5 and should no longer be possible
