### ISSUE TITLE
Unable to reset server settings

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#4982]
Deleting the config files Eco_Data/Server/Configs and then starting the server recreates these files but the server crashes then.
Comparing ecosim.eco i edited previously (tweaked some plant related stuff) with the newly created ecosim.eco it seems to me that the file created when starting a server is a very old version. It's missing a lot of things and is only about half the size of the original file.

**Comment by MarjieAVolk** [comment]
Yeah deleting the config won't recreate the correct config, you should not delete the config.  You may need to get a fresh installation of the game to recover the normal config.
