### ISSUE TITLE
USER ISSUE: excavator falls through the world

### ISSUE THREAD

**Issue by tacosx22** [StrangeLoopGames/EcoIssues#4989]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Get in the excavator on any type of road
Enable the arm
Use A or D to rotate

**Expected behavior:**
simply pivot the arm

**Actual behavior:**
Glitches out, freezes the game and disappears.
It's happened not once but three times.

**Comment by SeanAtr0n** [comment]
any more details on how this occurred? I haven't seen this yet
