### ISSUE TITLE
Loading chest with food gives free snack

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#499]
I was holding 12 huckleberry extracts, and the chest had 16 in it. Right clicking on the chest to dump the items in, provided the chest with a total of 28. In that same movement, my character ate 1 extract without deducting from the total available.

Alpha 4.1, easy to repeat

![image](https://cloud.githubusercontent.com/assets/6193670/16893343/eafc2618-4b88-11e6-9f3c-cb889a097366.png)

**Comment by mariowenig** [comment]
Reproduced and verified:
Initial:
![image](https://cloud.githubusercontent.com/assets/10489431/16903205/7e5a975c-4c45-11e6-8b3f-8ba00c4de3da.png)
Post Right click:
![image](https://cloud.githubusercontent.com/assets/10489431/16903211/9894e7e4-4c45-11e6-9bed-a299a36d4891.png)

Free food, solved world hunger.
