### ISSUE TITLE
USER ISSUE: Friend can`t join my Server anymore

### ISSUE THREAD

**Issue by Stuntstream** [StrangeLoopGames/EcoIssues#4990]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
If he wants to join my game his game says that the server is already full (I have a world for 1-3 Players) but I am the only one who is online. The last time he was online is 10 hours ago.

**Expected behavior:**
-

**Actual behavior:**
-

**Comment by MarjieAVolk** [comment]
I'm guessing you saw this happen: https://github.com/StrangeLoopGames/EcoIssues/issues/3768

That is, you created another world where you did not enable 'allow friends to join', and this overwrote your settings for this world.

You can fix this for now by opening up your world, entering /openserverui and going to Users > Config, and changing Max Slots to 2 (or however many you want).  Let me know if that works.
