### ISSUE TITLE
USER ISSUE: The vanish Wooden Cart

### ISSUE THREAD

**Issue by Leviatay** [StrangeLoopGames/EcoIssues#4991]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Drive your Wooden Cart or any other vehicle
2. Let it rest at this specific Point
3. look away, look back
4.(optional)  search for your cart

**Expected behavior:**
Is still there where i left it	

**Actual behavior:**
Vanish an appear somewhere near

**Comment by Thyriel** [comment]
We had same happen through the last 2-3 days with 2 carts. The carts are "technically" still there as their inventory is still accessable through linked inventories and the deed still points to the place where they where left but the carts are not there. (maybe bugged through ground ?)

But it seems only rarely to happen, we have at least 15+ carts around and in over a week this only happened to 2 carts.

**Comment by MarjieAVolk** [comment]
Since the inventory is still linked, is it possible the cart teleported on top of a building?

**Comment by Thyriel** [comment]
> Since the inventory is still linked, is it possible the cart teleported on top of a building?
Doesn't seem like it. I checked the whole area with /fly (even underground but not sure if i would see a cart being buried while flying underground)

**Comment by MarjieAVolk** [comment]
Had another person report a missing cart, and their deed told them it was at a large negative number for the y coordinate.  Do you guys also see this?

**Comment by Spaceferret42** [comment]
I did find the cart by going to the coordinates minus the y it was at the bottom of the ocean

**Comment by Thyriel** [comment]
The tip that there is an Y coordinate hidden on the deed was great :)
I found mine on top of another building that is 3 floors high (not easy to explain how it could have gotten there). And a newly missing powered cart has now been found in an old mine someone digged a while ago. Also here it's not easy to explain how that thing got in there considering the path leading down is only 2x2 blocks and the powered card way bigger then that ^^

**Comment by Spaceferret42** [comment]
How about a parking brake and fixing the space bar acts as break while moving not working

**Comment by SeanAtr0n** [comment]
fixed 7.2
