### ISSUE TITLE
USER ISSUE: Contracts Bug

### ISSUE THREAD

**Issue by jorfromscotia** [StrangeLoopGames/EcoIssues#4994]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Begin to create a contract
2. Change first clause to "place in chest", so now both clauses say "place in chest"
3. Press "escape" to close out of contract board (changed my mind on posting)

**Expected behavior:**
Be able to go and build a chest for my contract items, then return to the contract board and start a new posting.

**Actual behavior:**
It says: "Contract 'Unnamed Contract' is invalid, must fix or delete before posting another one." I can't see it on my contract list, though.

**Comment by bbaclig** [comment]
Do you see a contract icon on the top-right of your screen. That could be your open incomplete contract that either needs to be deleted or validly completed.

**Comment by jorfromscotia** [comment]
bbaclig's response "fixed" it. I'm new to the game and didn't notice the notification, as it was hidden underneath my map. Very sorry to waste the dev's time on this; I thought I had checked everything. <3 Maybe find a better location for notifications to appear, or for the map to pop up, so that UI items don't overlap? Or maybe have a tutorial-style announcement showing where notifications like this one will appear so that we know? 

Thanks for the hard work, guys!
