### ISSUE TITLE
USER ISSUE: loosing cart deed when steam token server restart

### ISSUE THREAD

**Issue by megs24** [StrangeLoopGames/EcoIssues#4998]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Spawn a cart
Share wright with another player to use cart
steam restart the other player token who is deconected
My deed disapear, and the cart remain in world with wright owner but without deed.

**Expected behavior:**
The cart deed does not disapear at all.

**Actual behavior:**
There is no deed to get cart in inventory for owner.

**Comment by MarjieAVolk** [comment]
Do you mean that your server crashed?  Sounds like you may just need to roll back to a backup save if possible, since the server crashing can leave the save in a bad state.

**Comment by MarjieAVolk** [comment]
Closing due to no response.  We will continue trying to reduce crashes and improve saving.
