### ISSUE TITLE
USER ISSUE: Endless Producing Killn

### ISSUE THREAD

**Issue by Leviatay** [StrangeLoopGames/EcoIssues#4999]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Creat a 1000 Brick task
2. Put some Ressources in 
3. As long as he has Stone and not enough Pitch, the time goes along
4. Put some Pitch in -> Result instant Bricks

**Expected behavior:**
Waited with the producing till he has enough Pitch

**Actual behavior:**
He "producde" the Bricks along but dosen't output it, Till you put Pitch in.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#234
