### ISSUE TITLE
Mac: Storing large quantities

### ISSUE THREAD

**Issue by GPRatcliffe** [StrangeLoopGames/EcoIssues#500]
<img width="1440" alt="screen shot 2016-07-16 at 14 59 25" src="https://cloud.githubusercontent.com/assets/13458289/16895198/2960eba0-4b66-11e6-8781-230f69e60edb.png">
This seems to work fine on PC but on my Mac it crashes the game, see screenshot. I've tried to move 100 Pitch into the masonry table but as soon as I try it the game freezes.

Current Mac software: OS X El Capitan V10.11.5
ECO V4.1

**Comment by noblackthunder** [comment]
could you please try to get the unity crash logs ? ( you can google where they get stored on your computer)

**Comment by GPRatcliffe** [comment]
Certainly, I'm afraid I closed the application before my system could report it, however I do have another hang log dating slightly further back but also stemming from the same issue.
[hang-time.txt](https://github.com/StrangeLoopGames/EcoIssues/files/367525/hang-time.txt)

**Comment by metachronism** [comment]
should be fixed now
