### ISSUE TITLE
USER ISSUE: none/invisible text

### ISSUE THREAD

**Issue by Linnux234** [StrangeLoopGames/EcoIssues#5001]
**Version:** 0.7.2.0 beta staging-08551408

**Steps to Reproduce:**
Join on a Server.

**Expected behavior:**
It should have readable text.

**Actual behavior:**
instead it have none or invisible text

**Comment by MarjieAVolk** [comment]
What exactly has invisible text?  The name of the server?  Or the chat log maybe?

**Comment by MarjieAVolk** [comment]
Closing due to not enough information.
