### ISSUE TITLE
USER ISSUE: Failed to connect on Singleplayer

### ISSUE THREAD

**Issue by HannesFrt** [StrangeLoopGames/EcoIssues#5007]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Create new Game
2. Join
3. Wait

**Expected behavior:**
joining a created (new)  game

**Actual behavior:**
It tabs out, then it says Connection Faild

**Comment by MarjieAVolk** [comment]
Since the game is being minimized, is your firewall or antivirus blocking the server?  It may be popping up a confirm dialog, which minimizes the game.

**Comment by HannesFrt** [comment]
Thanks for the super fast reply. Im not sure if the firewall is the problem, however ther is no pop-up on the desktop. For the time being i downloaded the eco server from Steam and connected via Localhost. Thats just working fine

**Comment by metachronism** [comment]
@HannesFrt is this still and issue for you, and are you per-chance in a different locale than en-US ?

**Comment by HannesFrt** [comment]
@metachronism it is yes. I am in a different local (Europe). Is this the problem?

**Comment by metachronism** [comment]
its likely crashing loading your gamesave, and not actually a connection failure (we have bad messaging)

is it possible for you to link the gamesave here?

**Comment by HannesFrt** [comment]
@metachronism  yes, where is it located?

**Comment by HannesFrt** [comment]
@metachronism No needs anymore. Now it is working after some updates of the game. Thank you very much. Keep on going I like this game 👍
