### ISSUE TITLE
USER ISSUE: Getting stuck

### ISSUE THREAD

**Issue by WolfChieftain** [StrangeLoopGames/EcoIssues#5009]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Stand really close to a storage chest/store open it up.

**Expected behavior:**
You open the store/inventory and can access it without problems

**Actual behavior:**
You get stuck, you are not be able to use the chat and type /unstuck. you need to disconnect and reconnect to play!
t

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115
