### ISSUE TITLE
Cart Names - renaming cart doesn't rename deed

### ISSUE THREAD

**Issue by Dr-Hardware** [StrangeLoopGames/EcoIssues#5010]
It looks and acts ok, but gets 2 different names - Deed Vs Cart interface.
![image](https://user-images.githubusercontent.com/32424101/36617260-d88c597c-193a-11e8-9f02-f4e9378bdf3d.png)

Probably one of us placed it and passed it to the other - a few days ago and I just noticed this today so thought i'd mention it as it became confusing when sorting though deeds.

**Comment by Dr-Hardware** [comment]
probably not an issue at all  as the deed recognizes the name of the cart, but has its own name as well....

**Comment by MarjieAVolk** [comment]
Yeah deeds and carts have separate names, kind of.  But it is a bit confusing.  I will take a look at how it works, would be nice if they would both sync.

**Comment by MarjieAVolk** [comment]
It will hopefully be more clear in 7.6 (not the release today, but the next major release after that).  Deeds will no longer be sort of named after vehicles like this.
