### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by BeefyGames** [StrangeLoopGames/EcoIssues#5011]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Press new.
2. select no colabiration
3. press Generate.. or the launch button.
4. if this does does not work its done correctly.
5. tryed selecting the generate new. (This was not working either.)

**Expected behavior:**
It should have launched a single player world... Since i am launching a new world...

**Actual behavior:**
The following error message popped up:
Connection Failed

Connection Failed
```

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
