### ISSUE TITLE
USER ISSUE: Elegant doors do not interact with <building> walls

### ISSUE THREAD

**Issue by AyeeAyeeRon** [StrangeLoopGames/EcoIssues#5012]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Place walls with hammer (2nd option)
Place Elegant Door next to said wall.

**Expected behavior:**
Aligned the wall with the door.

**Actual behavior:**
Does nothing.

**Comment by MarjieAVolk** [comment]
It would be nice if builders could detect doors somehow.  Like maybe they could put down different world object blocks than other world objects?  Like 'wall world object blocks' or something.

**Comment by keegan-o** [comment]
Yeah we already did this, tis on release. I think this is in reference to an actual mod item or something called 'Elegant Door', not officially supported doors.

**Comment by MarjieAVolk** [comment]
ooooh sweet
