### ISSUE TITLE
USER ISSUE: Crash!!

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5014]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
mining stone / ore 

mouse was held down for repetitive mining
"e" was held down for repetitive grabbing

**Expected behavior:**
not crashed

**Actual behavior:**
The following error message popped up:
```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by MarjieAVolk** [comment]
Hey, unfortunately this error message is not enough for me to work with.  If you can find any logs from the server that have a more complete error message, I might be able to look in to this.  If not - I am going to make sure these errors get better error messages, so we can debug these more easily in the future.
