### ISSUE TITLE
USER ISSUE: blast furnace

### ISSUE THREAD

**Issue by jessigaming** [StrangeLoopGames/EcoIssues#5015]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
build blast furnace

**Expected behavior:**
created and counted down 

**Actual behavior:**
didnt count down

**Comment by MarjieAVolk** [comment]
It sounds like you are saying your crafting table was not crafting?  Have you looked at the Status tab on your table?  Does it have any missing requirements?

**Comment by MarjieAVolk** [comment]
Closing due to no response
