### ISSUE TITLE
USER ISSUE: Cant Join A Friends Hosted game

### ISSUE THREAD

**Issue by malunusis** [StrangeLoopGames/EcoIssues#5022]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
try to join a friends game	

**Expected behavior:**
let me join his game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen

If those don't work, let me know.
