### ISSUE TITLE
USER ISSUE: "Connection Failed" 

### ISSUE THREAD

**Issue by Escavliar** [StrangeLoopGames/EcoIssues#5023]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I had to crash my computer because it froze, and it never freezes. (Probably due to this game) So I would assume don't force crash a PC while in a game of Eco.

**Expected behavior:**
Load the Local Save like normal...

**Actual behavior:**
Won't allow me to start my world back up again. Basically unplayable. (Spent 7 days, frustrating.)

**Comment by MarjieAVolk** [comment]
Can you load a backup of your save?  Often after a crash, the save file won't be in a good state.  You can also try deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by MarjieAVolk** [comment]
Closing due to no response
