### ISSUE TITLE
USER ISSUE: cant join friends game

### ISSUE THREAD

**Issue by Notapeoples** [StrangeLoopGames/EcoIssues#5027]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. try to join friends gane vie steam invite

**Expected behavior:**
joined friends game

**Actual behavior:**
Connection Failed

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
