### ISSUE TITLE
Logging out and logging back in doesnt change the user

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#5028]
(I disabled auth on the client and server for this bug, it may not be required though)
Log in as any valid user and connect to the game
Disconnect and logout
Login as a new user (I logged in as a non-existent user since auth was off)
Disconnect and logout
Log back in as that first user, you'll see you're still logged in as the second used

This is a frequent pattern for checking things that involve multiple users.

**Comment by MarjieAVolk** [comment]
Were you disabling auth and logging in as a fake person?  Not enough information to go on here.

**Comment by MarjieAVolk** [comment]
This was the PR where I fixed a similar issue: https://github.com/StrangeLoopGames/Eco/pull/2525

Looks like it went in to staging 1 week ago.  I have been testing it out locally on staging, and it seems to work.  So I'm going to close this as already fixed for now.  But let me know if you see it again.
