### ISSUE TITLE
USER ISSUE: Plastic blocks act as copper and cannot be removed

### ISSUE THREAD

**Issue by glenwinters** [StrangeLoopGames/EcoIssues#5029]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I placed several plastic blocks down, expecting to pick them up later. A bit later, I tried to pick them up.

**Expected behavior:**
The plastic should go into my inventory.

**Actual behavior:**
The block disappeared and I saw an image of copper flash briefly (visible for less than 1 second) in my carrying inventory and then disappear. Nothing appeared in my inventory. Moments later, the plastic blocks re-appeared. I had another player come look at the blocks while I tried to remove them again and they said they were not disappearing. When the other players tried to remove the blocks, I saw similar behavior.

After many tries, I was able to get a screenshot with the copper showing:
![20180223205919_1](https://user-images.githubusercontent.com/435066/36626183-c818bbb0-18e2-11e8-8170-bb4022339ef8.jpg)

**Comment by MarjieAVolk** [comment]
Plastic was not meant to be a block.  It will be fixed in the next release.
