### ISSUE TITLE
Modern wood window appears twice in carpentry workbench

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#503]
Have learnt all the skills up to but not including everything from the expert research skill book.
Modern wood window appears twice in carpentry workbench, perhaps since learning glass making skill.

Alpha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16899486/df8eacac-4c59-11e6-8e3f-82c0fa538271.png)

**Comment by mariowenig** [comment]
duplicate #218

**Comment by craig-jong** [comment]
This is fixed in the coming patch.
