### ISSUE TITLE
[Suggestion] Skill books/scrolls should contain tutorials

### ISSUE THREAD

**Issue by CompactDisc** [StrangeLoopGames/EcoIssues#5030]
A user on our server came up with a brilliant idea:
Whenever you learn a skill scroll, it would be nice if you got a basic tutorial on the career path you just chose. Which you can skip of course.

Have the scrolls or books stored in their own inventory ('tutorial book'), which you can look into and find all tutorials in.

Example:
Farming skill scroll should include all specific requirements for each plant type.
Fertilizer should show you how to optimize ground nutrition for each plant type.
Etc.

After learning these books, you can take a look in your 'tutorial book' and get an overview of each of your chosen professions.

**Comment by Thyriel** [comment]
I like that idea. But it should pop up when you learn the specialization and not when you read the scroll as you learn all scrolls because of the deeds given.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#233
