### ISSUE TITLE
USER ISSUE: Item Collection from Crafting stations

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5033]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Begin crafting multiple of one item.
Upgrade your skill points for that item during the project.
When it completes it will not clear from the que.

**Expected behavior:**
Item clear from que and skill points awarded (enabled on this server)	

**Actual behavior:**
Must cancel each recipe that says "completed"

**Comment by MarjieAVolk** [comment]
Aha, I hadn't thought that the projects not completing might be related to skill points given on project completed.  Think there might be a duplicate bug for this somewhere.

**Comment by WeaselDog** [comment]
This behavior has changed and is no longer an issue with new skill system and dynamic ingredient requirements when leveling up.

**Comment by SlayksWood** [comment]
We haven't dynamic update time and ingredients for order yet.
![image](https://user-images.githubusercontent.com/45708377/71156311-ce2cec00-2250-11ea-819d-f5c35d1f60fe.png)
