### ISSUE TITLE
USER ISSUE: Glitching Log - fall through world.

### ISSUE THREAD

**Issue by Loivado** [StrangeLoopGames/EcoIssues#5034]
**Version:** 0.7.1.2 beta

(Happened only once yet.)
**Steps to Reproduce:**
0. Start a "solo" game.
1. Have a Wall with a Door.
2. Open the Door.
3. Cut a tree. 
4. Cut the Tree in pieces while it falls. 
5. Some parts of the tree fall through the floor. 
6. Walk against the door. 

**Expected behavior:**
Objects don't pass through the floor.
Characters don't pass through the floor. 

**Actual behavior:**
Half of the tree is falling through the floor. 
When I walked against the open door I felt through the floor,  
When reconnecting I spawned where I cut the affected tree. The missing (previously glitching part of the tree) is levitating above the floor, can be pushed into the sky. 

**Aditional Info:**
I'm not sure if repro steps 5 and 6 are neccessary for a reproduction. 
I assume the glitching tree made the player figure fall through the floor aswell. 
I saw it often that a falling tree is twitching when he falls on the floor against a tree.

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/3668

If you could share some screenshots of the place where the tree fell through the floor, that might be useful.  I'm not sure if this is related to the specific blocks that were there or not.

**Comment by SeanAtr0n** [comment]
fixed a while back
