### ISSUE TITLE
USER ISSUE: Character Stuck

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5035]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open storage chest (unsure other objects)
Change the name
Close the window	

**Expected behavior:**
Be able to move beacuse the cursor is inactive	

**Actual behavior:**
Character seemingly stuck. Must "click" to move again.

**Comment by mreil617** [comment]
Seems to only happen if esc is used to close the inventory menu

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115
