### ISSUE TITLE
Clientside desync when harvesting/planting

### ISSUE THREAD

**Issue by Thyriel** [StrangeLoopGames/EcoIssues#5036]
When you harvest/plant a lot plants in a short amount of time often there seems to be some kind of desync with the server to happen.
Steps to reproduce:
- Harvest a big field as fast as you can do OR plant a big field as fast as you can do
- Often it takes up to 10-20 seconds until the plants vanish / seedlings appear. When they "update" they all do at the same time

Basically this sounds like the client isn't getting an update from the server in time and then somewhen it get's a blockupdate and updates all blocks in an area around the player.
BUT: As the client correctly recognizes that a plant is already harvested (you can plant a new one after harvesting even if the plant is still rendered) or that you already planted a plant on a field (gives an error that the space is already occupied even if the seedling isn't rendered yet) i think it's a pure client issue. Somehow the client is knowing the correct block state but isn't rendering it correctly for a while.

Additionally it rarely happens that this "desync" stays and you need to relog to force it being rendered correctly.

**Comment by metachronism** [comment]
fixed in 7.7+
