### ISSUE TITLE
USER ISSUE: Crash if I want to repair a shove

### ISSUE THREAD

**Issue by TomberWolf** [StrangeLoopGames/EcoIssues#5037]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Put the shovel into the repair station
2. Click on "Repair"

**Expected behavior:**

**Actual behavior:**
Caught exception: Caught exception invoking RPC ViewRPC on Client!

Caught exception invoking RPC Repair on RepairComponent!

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Stack:
   bei Eco.Gameplay.Items.Inventory.TryRemoveItems(ItemStack stack, User user)
   bei Eco.Gameplay.Components.RepairComponent.Repair(Player player)

Stack:
   bei Eco.Shared.Networking.RPCManager.TryInvoke(Object controller, String methodname, BSONObject bsonArgs, Object& result)
   bei Eco.Shared.Networking.RPCManager.InvokeOn(BSONObject bson, Object controller, String methodname)
   bei Eco.Plugins.Networking.Clients.Client.ViewRPC(Guid guid, String methodname, BSONObject bson)

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4358
