### ISSUE TITLE
USER ISSUE: Cant Connect

### ISSUE THREAD

**Issue by maginator** [StrangeLoopGames/EcoIssues#5038]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Yesterday it works fine to day it dosent work anymore. I cant connect to my friends Server now.

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Connecting to the server directly via IP address

If those don't work, let me know.
