### ISSUE TITLE
USER ISSUE: Hang ofter rename storage

### ISSUE THREAD

**Issue by devantheone** [StrangeLoopGames/EcoIssues#5039]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I build a new storage
2. I fill it with wood
3. I name this storage "Holz"

**Expected behavior:**
It should be rename and I can move or do anything else	

**Actual behavior:**
But I was locked to the position and can´t move or interacte with anything but the game is still running and I see runing the anlymal

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4115
