### ISSUE TITLE
Work bench has multiple of the same item to craft and others missing.

### ISSUE THREAD

**Issue by PhosphorDragon** [StrangeLoopGames/EcoIssues#504]
I created and two storey room and then went to my work bench to create and door and noticed that there was two or more of some items. I tried moving the work bench and creating a new one and the problem persists. I've also disconnected and re connected and still the same problem. 
![eco work bench bug 1](https://cloud.githubusercontent.com/assets/20499560/16899716/f320faee-4c05-11e6-8b79-27ceb2477049.jpg)
![work bench bug 2](https://cloud.githubusercontent.com/assets/20499560/16899719/057d5e26-4c06-11e6-81bf-3d971173d47f.jpg)
![work bench bug 3](https://cloud.githubusercontent.com/assets/20499560/16899720/0e20214e-4c06-11e6-87cd-da46ecc215c7.jpg)

**Comment by mariowenig** [comment]
duplicate #218

**Comment by craig-jong** [comment]
I'm going to leave this one open until the fix is pushed into release. But the bug is fixed in the coming patch.
