### ISSUE TITLE
Failed to parse IP Address for listen server

### ISSUE THREAD

**Issue by SandrikLP** [StrangeLoopGames/EcoIssues#5040]
Hi,

yesterday it worked fine, but as we try to start the Server today, it doesn´t. We try everything, but nothing helped. The Problem starts with the today update (2018-02-24 11:xx)
I set the IPAddress to my Ext.IP from today.

The Server Settings are:
Public TRUE
IPAdresse "87.xxx.xxx.xxx"
GameServerPort 3000
Web ServerPort 3001
DetectNAT TRUE
Rate 10

I set Portforwarding for TCO & UDP on Ports 3000 to 3001

My friends can see i´m in the Game, but they can´t join or connect per invitation.

What can we do?

**Comment by MarjieAVolk** [comment]
Are you trying to join via the steam invitations / join button?  Have you tried connecting directly, via IP address?

**Comment by MarjieAVolk** [comment]
Closing due to no response
