### ISSUE TITLE
USER ISSUE: Cant join my world

### ISSUE THREAD

**Issue by Destroyer-EnSk** [StrangeLoopGames/EcoIssues#5042]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If running your own game, when starting a new world, select 'Generate new'
* If running your own game, run the server via the EcoServer tool
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
