### ISSUE TITLE
USER ISSUE: Can't move after renaming something with Enter / Return key

### ISSUE THREAD

**Issue by StuartWebster** [StrangeLoopGames/EcoIssues#5045]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Start renaming a container (e.g. box, stockpile)
2. Press the Enter / Return key to confirm the new name
3. Rename succeeds
4. Press ESC to close the container's menu
5. Player can't move
6. Click on the left mouse button and now the player can move again.

**Expected behavior:**
It should have returned the controls to the player after pressing Enter / Return.

**Actual behavior:**
Instead the player gets stuck and they are required to click on the left mouse button to regain control or press ESC and disconnect or quit. This bug does not happen if I click to confirm the new name; it only happens when pressing the Enter / Return key.

**Comment by StuartWebster** [comment]
Issue also happens when following the same repro steps but when entering in the quantity of items to craft

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4115

**Comment by MarjieAVolk** [comment]
Oh, this is the same thing as #4115 after all I think, should be fixed now.
