### ISSUE TITLE
USER ISSUE: cant connect after creat  new game

### ISSUE THREAD

**Issue by louisdeluche** [StrangeLoopGames/EcoIssues#5046]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
new check everything but not generate new world

**Expected behavior:**
it should have launch the game

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the EcoServer tool
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
