### ISSUE TITLE
Continue loses info in the connection fails

### ISSUE THREAD

**Issue by pczealot** [StrangeLoopGames/EcoIssues#5049]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Load game and click Continue to connect to previous dedicated server. Times out and won't connect.

**Expected behavior:**
Connected to my previous server.

**Actual behavior:**
Times out and pops up Connection Failed. Can only connect again by going back to Join (which is extremely choppy and/or laggy).

**Comment by metachronism** [comment]
should keep the last continue info even if the connect fails

**Comment by metachronism** [comment]
fixed a while back
