### ISSUE TITLE
USER ISSUE: Trying to join server via steam

### ISSUE THREAD

**Issue by MrDaem0n** [StrangeLoopGames/EcoIssues#5050]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. create a new server
2. launch
3. invite friend via steam invite
4. Server failed at friends end

**Expected behavior:**
Server connection failure

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by citizen-blueraven** [comment]
I have been searching to fix the same problem firewall is open on eco and eco server , port are forwarded correctly and I am running the server as an administrator . In steam server list can't even see my server as active with internal ip as a localhost or with my web address but I can access my server in-game but my friends cannot . tried to link my steam account on eco server but the link is not working for now.
please help fix this !

**Comment by MarjieAVolk** [comment]
@MrDaem0n Has your friend tried connecting directly via ip address?

@citizen-blueraven I saw your other bug.  It's unclear whether these are the same issue or not.

**Comment by citizen-blueraven** [comment]
My friend tried every way possible to connect and failed

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MarjieAVolk** [comment]
Closing due to no response.  @citizen-blueraven you have already filed another bug for your issue https://github.com/StrangeLoopGames/EcoIssues/issues/5085
