### ISSUE TITLE
How to use private server browser service

### ISSUE THREAD

**Issue by norfair00** [StrangeLoopGames/EcoIssues#5058]
![image](https://user-images.githubusercontent.com/1060346/36635004-16973a7a-19ae-11e8-8d32-ddd06a292465.png)

**Comment by MarjieAVolk** [comment]
This tool is to add another endpoint for server listings.  As a normal player, you won't need to use it.  To use it, you will need to create a web server, which can return a list of servers - similar to 'https://ecoauth.strangeloopgames.com/game/serverlist'.  Then you can enter the URL for your web query in the 'service address' box.

**Comment by norfair00** [comment]
Nice thanks
