### ISSUE TITLE
USER ISSUE: Server is full

### ISSUE THREAD

**Issue by Despote00** [StrangeLoopGames/EcoIssues#5060]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
We created a singleplayer world set to 1-3 players couple days ago.(before the last update- 24 febuary) 
Everything was working just fine, but now my girlfriend can't connect anymore.
World is in LAN.

EDIT: Going into steamapps\common\Eco\Eco_Data\Server\Configs and then Users.eco. 
You simply change the MaxSlots from 1 to -1.
Get sometime resets during update.
Works just fine now.

**Expected behavior:**
Connect without problem.

**Actual behavior:**
Can't log in.

**Comment by MarjieAVolk** [comment]
Glad you found out what to do.  You may have been experiencing this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/3768
