### ISSUE TITLE
USER ISSUE: stuck in others trap

### ISSUE THREAD

**Issue by Aromaze** [StrangeLoopGames/EcoIssues#5061]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
someone has a territory, and does a hole of 3 meters.
Someone that can't modify the territory falls into the hole. He is stucked.

**Expected behavior:**
It should be possible to go out of this trap.

**Actual behavior:**
Stucked in the hole.

**Comment by LiaungYip** [comment]
All players can use the `/unstuck` command to teleport yourself to the surface. Logging out, and logging back in, will have the same effect.

**Comment by Aromaze** [comment]
please unsubscribe me thanks



_Jérémy Rio_

________________________________
De : Dennis Scholz <notifications@github.com>
Envoyé : mercredi 13 novembre 2019 15:33
À : StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com>
Cc : Aromaze <too_short_time@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [StrangeLoopGames/EcoIssues] USER ISSUE: stuck in others trap (#5061)


Closed #5061<https://github.com/StrangeLoopGames/EcoIssues/issues/5061>.
