### ISSUE TITLE
Server browser shows very high ping to server

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5063]
I run a Eco server on my home internet connection.
Ports 3000 and 3001 are forwarded through my router and Eco's NAT/uPNP feature is turned off.

In the server browser, it takes 30-60 seconds for my server to come up in the list.
When the server does appear in the list, the quoted ping can be anywhere from 5ms to 5,000ms, as in the screenshot below.

![image](https://user-images.githubusercontent.com/2173684/36637698-61ea70a8-1a2d-11e8-8db8-a1987b921d22.png)

The server browser sorts by ping, so this puts my server at the bottom of the server browser. This means that it's effectively impossible to attract new players.

It also apparently makes it hard or impossible for existing players to find and join the server, even if the server is in their favourites. The server simply doesn't show up in the favourites list. One player I, who I was able to contact out of game, thought my server had been completely offline for the last 7 days. ( See https://github.com/StrangeLoopGames/EcoIssues/issues/1612 - `Never hide a favorite entry. If the favorite is being pinged for a response, show some sort of spinning icon denoting that.`)

In reality, my network ping is 50ms - 100ms, and players have no noticeable latency once they're in game.

Speed test results - plenty of bandwidth available, and 30ms outbound ping to the closest capital city.

![image](https://user-images.githubusercontent.com/2173684/36637593-0cb19c94-1a2b-11e8-97c1-0bbea968151b.png)

Ping results from someone on the other side of the country, who wouldn't have had my DNS in cache:

    --- lwslwslws.dyndns-at-home.com ping statistics ---
    30 packets transmitted, 30 received, 0% packet loss, time 29033ms
    rtt min/avg/max/mdev = 107.030/107.933/113.043/1.220 ms

`Configs/Network.eco` as per following:

    game_servers@gumption:/bulk/game_servers/eco/Eco_0.7.1.2/Configs$ cat Network.eco
    {
      "PublicServer": true,
      "Password": "",
      "IPAddress": "Any",
      "Description": "#Camelot - Australia - see penwatch.net/camelot for rules and Discord",
      "GameServerPort": 3000,
      "WebServerPort": 3001,
      "DetectNAT": false,
      "Rate": 10,
      "ServerBrowserService": "https://ecoauth.strangeloopgames.com/game"
    }

**Comment by MarjieAVolk** [comment]
In 7.4, we are using a different method to get server ping.  Hopefully you will see more accurate results.  If not, let me know.

**Comment by LiaungYip** [comment]
Confirmed fixed in 7.4 series.

**Comment by MarjieAVolk** [comment]
Awesome, thanks
