### ISSUE TITLE
USER ISSUE: Invalid login

### ISSUE THREAD

**Issue by emead09** [StrangeLoopGames/EcoIssues#5064]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Kept trying to login with my username and pass. Even was able to login on the website but couldnt on the game.

**Expected behavior:**
Login into game	

**Actual behavior:**
Invalid username/password

**Comment by MarjieAVolk** [comment]
You may need your account fixed.  What is your strange loop username?

**Comment by rainfarmer** [comment]
sent user troubleshooting info by email.
will update solution here.

**Comment by elfl0rd** [comment]
This issue looks too old... Maybe fixed? @rainfarmer 
Or close as not answered.
