### ISSUE TITLE
USER ISSUE: Fell through the earth

### ISSUE THREAD

**Issue by kdr264** [StrangeLoopGames/EcoIssues#5066]
[**Version:**](http://steamcommunity.com/sharedfiles/filedetails/?id=1312795619) 0.7.1.2 beta

**Steps to Reproduce:**
I have no idea, I thought the game didn't render, so I kept walking (i was dragging a cart), and instead of loading, I just fell through the earth

**Expected behavior:**
Shouldn't fall through the earth

**Actual behavior:**
fell through the earth lol

**Comment by digitinator** [comment]
LOL the same thing happened to me while I was walking around, but the space in front of me was loaded

**Comment by kdr264** [comment]
haha interesting. I closed and reloaded the game and it resolved itself. Thankfully haha

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3861
