### ISSUE TITLE
USER ISSUE: Destroying cart while other player holds it is amazing

### ISSUE THREAD

**Issue by monkeyonstrike** [StrangeLoopGames/EcoIssues#5068]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Player 2 pushes cart owned by player 1
2. player 1 destroys cart and puts it back in inventory
3. player 2 becomes sideways ballerina dancing across the stars.
4. profit

**Expected behavior:**
It should do exactly what it is doing.

**Actual behavior:**
You'll see.

**Comment by monkeyonstrike** [comment]
![eco](https://user-images.githubusercontent.com/15221284/36638935-9a7573dc-19b5-11e8-9d6a-aca927f7de06.png)

**Comment by SeanAtr0n** [comment]
fixed march 5th
