### ISSUE TITLE
Description for Seed Yield Skill has "harvest" instead of "harvesting".  Included: excess descriptions.  Unknown affect on cedar seed.

### ISSUE THREAD

**Issue by jhadred** [StrangeLoopGames/EcoIssues#507]
Description currently is:  Increases the yield of seeds when harvest any plants.

Probably should be:  Increases the yield of seeds when harvesting any plants.

WIll include screenshot if needed once I'm at a computer that can do so.

Also, it includes descriptions for sugar beets, sugar cane, and cedar seeds.  The first two are not yet in game unless berries are the intended sugar source .(http://ecoforum.strangeloopgames.com/topic/677/farming-weird-issue/4)  So may need to be removed or hidden.

This may need to be a separate issue:
Cedar seeds do not seem to be affected by this skill.   In fact, there is currently no announcement on cedar seed gain, or bonus.

**Comment by darkensign** [comment]
Can confirm that cedar seeds are currently untouched by the seed yield skill and no system announcement is made when finding cedar seeds.

**Comment by craig-jong** [comment]
Descriptions have been changed - if this is still an issue, please reopen it.
