### ISSUE TITLE
USER ISSUE: Fishing glitch

### ISSUE THREAD

**Issue by CherryyColaa** [StrangeLoopGames/EcoIssues#5077]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
get yourself an Fishing rod on an Online server and try to get fishes

**Expected behavior:**
the fish wont appear to your inventory until you reconnect

**Actual behavior:**
read above nothing else to say

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4588
