### ISSUE TITLE
COMMAND ISSUE / SUGGESTION: Cannot spawn Fir

### ISSUE THREAD

**Issue by ZeelNightwolf** [StrangeLoopGames/EcoIssues#5078]
/spawnspecies Fir actually spawns in a Fireweed Plant. 

In the current source code Fir is listed after Fireweed. If this feature searches through the dictionary in sequence looking for match it will only ever find fireweed.
Adjusting the sequence may fix this issue.

**Comment by ZeelNightwolf** [comment]
Still cannot spawn Fir in 7.3.3

**Comment by ZeelNightwolf** [comment]
You can spawn Fir in 7.5.0

**Comment by D3nnis3n** [comment]
Fixed.
