### ISSUE TITLE
USER ISSUE: Oak Log Breakdown

### ISSUE THREAD

**Issue by szflow** [StrangeLoopGames/EcoIssues#5079]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1.Chop down oak tree
2.Break down large logs

**Expected behavior:**
Split the logs into smaller sections

**Actual behavior:**
Will not split and does not consume calories even though the rest of the log broke down fine

**Comment by MarjieAVolk** [comment]
Are they small enough to pick up?  Right now, trees with lower yield will have a larger min size for their logs, since it is based on number of logs given rather than size.

**Comment by szflow** [comment]
Since it was an oak tree, the pieces are thin discs. This has happened on 3 different trees within the same area, different portions of the log though. They appear to be small enough to pick up, but yet they are still highlighted yellow and they still give the message about them being too large to pick up. No matter how many times I attempt to chop them, they will not decrease in size. It makes the sound effect for the axe chopping/striking wood, but it doesn't consume calories (which usually indicates that your action had an effect) nor does it make them any smaller.

**Comment by MarjieAVolk** [comment]
Aha.  I think it is pretty hard to target the edges of those thin disks.

**Comment by SeanAtr0n** [comment]
Fixed a while back
