### ISSUE TITLE
USER ISSUE: glitched through the ground

### ISSUE THREAD

**Issue by lalawunderland** [StrangeLoopGames/EcoIssues#5080]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
walked around the world and fell through the ground

**Expected behavior:**
-.- should be clear

**Actual behavior:**

**Comment by Mahsaap** [comment]
Note : If your using a custom size world that is not in the recommended list. The world can have tears.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4574
