### ISSUE TITLE
Contracts: Build Road of Width 4 actually requires a road of width 5

### ISSUE THREAD

**Issue by LiaungYip** [StrangeLoopGames/EcoIssues#5082]
I made a contract to build a length of road, specifying the material to be Stone and the Width to be 4.

![image](https://user-images.githubusercontent.com/2173684/36642319-95015234-1a89-11e8-8603-f77635416ca2.png)

To fulfil this contract, the contractor had to build a road of width 5.

![image](https://user-images.githubusercontent.com/2173684/36642301-64ff0afe-1a89-11e8-9196-65d7bb578ea4.png)

This may be an off-by-one error.

Apparently the message the contractor gets for this isn't very informative - it doesn't tell you that the problem is "the road isn't wide enough".

**Comment by johnkslg** [comment]
Fixed! You're right, off-by-one error. Thanks a ton.
