### ISSUE TITLE
Dedicated steam eco server not showing in list

### ISSUE THREAD

**Issue by citizen-blueraven** [StrangeLoopGames/EcoIssues#5085]
I have been searching to fix the same problem firewall is open on eco and eco server , port are forwarded correctly and I am running the server as an administrator . In steam server list can't even see my server as active with internal ip as a localhost or with my web address but I can access my server in-game but my friends cannot . tried to link my steam account on eco server but the link is not working for now.
please help fix this !

**Comment by MarjieAVolk** [comment]
Might be related to https://github.com/StrangeLoopGames/EcoIssues/issues/5414

**Comment by metachronism** [comment]
closing, should be fixed with 7.4 networking rewrite
