### ISSUE TITLE
USER ISSUE: Cannot move powered cart inventory

### ISSUE THREAD

**Issue by mreil617** [StrangeLoopGames/EcoIssues#5087]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try to drag the powered cart inventory 	

**Expected behavior:**
it moves (fuel prob blocking)

**Actual behavior:**
nothing

**Comment by MarjieAVolk** [comment]
Do you mean you are dragging it to reorder it in the inventory list?  Or are you pulling the cart?

**Comment by mreil617** [comment]
@MarjieAVolk reordering the inventory list.

**Comment by MarjieAVolk** [comment]
Okay.  So when you drag it, it doesn't move from its original space at all?  Or it doesn't get reordered when you release it?

Do you see this consistently, or is it off and on?

**Comment by mreil617** [comment]
Must of missed the email. When you drag the powered vehicle's inventory from another inventory (stockpile) it drags with the mouse then on release it will snap back to its original location. This happens with a green or yellow line appearing. Im not sure about frequency dont have powered vesicles on the new map. Think it's every time though.

**Comment by MarjieAVolk** [comment]
The next time you see this, could you send me your log file? "C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt"

**Comment by mreil617** [comment]
were close to powered objects in the new map. i dont have the old save. any chance you could give me web api docs in exchange?

**Comment by MarjieAVolk** [comment]
You can see & play with the web api for your server at http://localhost:3001/swagger/ui/index  (or the ip address of the server instead of localhost)

**Comment by Scheigy** [comment]
Got the same issue. Here's the file.

https://drive.google.com/file/d/1lVW8xIxCbI9ipuazhrF9EIDuAo5zwQlZ/view?usp=sharing

**Comment by elfl0rd** [comment]
I have video in https://github.com/StrangeLoopGames/EcoIssues/issues/5087

**Comment by MarjieAVolk** [comment]
I believe this was fixed by the updates to linked inventories, which allows the normal inventory and the fuel supply to be treated completely independently.

**Comment by MarjieAVolk** [comment]
Oops, this fix is not released yet, it will be in 7.6
