### ISSUE TITLE
USER ISSUE: Joining a Friend

### ISSUE THREAD

**Issue by julianistcool** [StrangeLoopGames/EcoIssues#5089]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. I want to join a friend via steam and this doesnt work, becaus of the message "connection fail"

**Expected behavior:**
I should have join the Server

**Actual behavior:**
The following error message popped up:
```Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen

If those don't work, let me know.
