### ISSUE TITLE
Materials required to develop Expert Research Skill Book not attainable

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#509]
According to the electronics skill tree, with the electronics skill you can make Fibreglass, Epoxy and Substrate. To make substrate requires fibreglass and epoxy. However you cannot make either of these at the electronics chest (workbench). For a split-second I can actually see fibreglass when I open the electronics bench, and epoxy at the refinery but they disappear fast.
Substrate is a material required to make circuits, and circuits is a required material to research the Expert Research Skillbook and Computer Lab.

This may be a duplicate of #497 and #481 but I'm not sure. Thought I would check anyway.
Alpha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16910157/369c2af2-4d2b-11e6-911e-6c026d43ace3.png)

**Comment by craig-jong** [comment]
This is fixed in the coming patch.

**Comment by stormoffires** [comment]
Was this suppose to be fixed in 4.2? still a pretty game breaking issues when no admin avaliable to cheat it in. 
![um](https://cloud.githubusercontent.com/assets/20627148/17084926/958b7844-517f-11e6-94c5-6055a734ef8e.png)

**Comment by mariowenig** [comment]
Hey Storm

Not quiet as advanced and not sure if the 4.2 hotfix made changes to allow for this, but I can tell for sure that the Pumpjack is available within ADV Research. 
Petroleum from Pumpjack (machine shop) with Barrel (Coopers Tool Shelf [Carpentry])

Will keep this updated with more info, once we progress to Expert Research.

**Comment by stormoffires** [comment]
It appears the hotfix is good to go. Both industrial and refining books have moved to Advance which would allow for circuits to be made and advancing to expert research. thanks guys!
