### ISSUE TITLE
USER ISSUE: Things duplicating after crashes

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#5090]
**Version**: 0.7.1.2 beta

when the server crashes and comes back we are getting duplicated items (all sorts from tools in inventory and chest to Powered Carts with No deeds), the one that is good but shouldn't happen is some Stockpiles appear overlapped (this is normally like a rollback effect if you have place one then removed and decided to place near but not same place), this will just duplicate items placed in it for as long as you keep moving them back and forth between the Overlapping Stockpiles

**Comment by Conchipedia** [comment]
Will release 7.2 Fix the Duplication Problem we are having?
If so how might this go about doing this, as we have loads of things duplicated, will this delete Both items that are duplicated? if so how can it tell what two items they are? for example an Excavator is duplicated but only one has a deed (is it possible to know which Item has a deed or not?)
if two stockpiles are duplicated and they take up the same space which one will be deleted or will both be removed?

**Comment by Amphysbaenas** [comment]
Same here: Crash / restart and Magic:
![image](https://user-images.githubusercontent.com/29807119/37001682-97238bec-20c7-11e8-8d2f-10d8c5f2abc4.png)

**Comment by Therandus93** [comment]
There is an issue with stockpiles duplicating in particular. When a stockpile is duplicated it also duplicated the items. If you move items from that stockpile via the storage menu it will multiply the items and crashes the server.

**Comment by metachronism** [comment]
this should be fixed now, actually
