### ISSUE TITLE
Username Incorrect

### ISSUE THREAD

**Issue by futuretman** [StrangeLoopGames/EcoIssues#5091]
I set up my eco account with a jimthecat user name as I didn't want my real name to be shown in game, but when I play it identifies me as Dan Pidcock

Can you change my displayed name to jimthecat please?
My user ID is  slg86075

Thanks,

Dan

**Comment by MarjieAVolk** [comment]
Is your strange loop account linked to your steam account?  It might be using your steam nickname rather than your strange loop username.

**Comment by MarjieAVolk** [comment]
Closing due to no response
