### ISSUE TITLE
USER ISSUE: Beans vanished when collected

### ISSUE THREAD

**Issue by Cassram** [StrangeLoopGames/EcoIssues#5093]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Beans into the Campfire, making "Campfire Beans"
2. Beans were finished
3. It says "You collected "Campfire Beans"", but they didn't add in my inventory or a near storage.

**Expected behavior:**
It should have add to my inventory, but it hadn't

**Actual behavior:**
Instead it just vanished.

**Comment by MarjieAVolk** [comment]
Just to be extra sure - they didn't go into your backpack, did they?

Do you happen to have skill points on crafting turned on?

**Comment by MarjieAVolk** [comment]
Closing due to no response.
