### ISSUE TITLE
USER ISSUE: Connection Failed

### ISSUE THREAD

**Issue by oleJ94** [StrangeLoopGames/EcoIssues#5095]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
i cant join any server just getting this up evry time Connection Failed what can i do to fix it??

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
If connecting doesn't work for any server, either local or remote, you can try these as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen

If that doesn't work, let me know.  Also, if you could send your client log file (C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt), that might be helpful.
