### ISSUE TITLE
USER ISSUE: Server not working

### ISSUE THREAD

**Issue by Tembii** [StrangeLoopGames/EcoIssues#5099]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Open steam overlay
join my friend
error: connection failed or server is full

**Expected behavior:**
I should have joined the server

**Actual behavior:**
connection failed or server is full

**Comment by MarjieAVolk** [comment]
If the message says server is full, your friend needs to change the configuration on their server to allow you to join.  (Possibly they did not check 'allow friends to join' when creating their server, or possibly they are encountering this bug https://github.com/StrangeLoopGames/EcoIssues/issues/3768)

In order to change this on an existing world, they will have to type '/openservierui'.  In the window that opens, go to Users>Config and change Max Slots to 2 (or however many people they want to let join).

**Comment by Tembii** [comment]
Thanks for the quick answer, as you said it was the bug #3768. After changing what you said it worked.


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: MarjieAVolk <notifications@github.com> Datum: 26.02.18  20:55  (GMT+01:00) An: StrangeLoopGames/EcoIssues <EcoIssues@noreply.github.com> Cc: Tembii <pilipplange@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [StrangeLoopGames/EcoIssues] USER ISSUE: Server not working (#5099) 
If the message says server is full, your friend needs to change the configuration on their server to allow you to join.  (Possibly they did not check 'allow friends to join' when creating their server, or possibly they are encountering this bug #3768)
In order to change this on an existing world, they will have to type '/openservierui'.  In the window that opens, go to Users>Config and change Max Slots to 2 (or however many people they want to let join).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/StrangeLoopGames/EcoIssues","title":"StrangeLoopGames/EcoIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/StrangeLoopGames/EcoIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MarjieAVolk in #5099: If the message says server is full, your friend needs to change the configuration on their server to allow you to join.  (Possibly they did not check 'allow friends to join' when creating their server, or possibly they are encountering this bug https://github.com/StrangeLoopGames/EcoIssues/issues/3768)\r\n\r\nIn order to change this on an existing world, they will have to type '/openservierui'.  In the window that opens, go to Users\u003eConfig and change Max Slots to 2 (or however many people they want to let join)."}],"action":{"name":"View Issue","url":"https://github.com/StrangeLoopGames/EcoIssues/issues/5099#issuecomment-368627314"}}}
