### ISSUE TITLE
Legs underground while using cart

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#510]
Sometimes when using a cart, your legs fall below the surface of the ground, at least up to your knees.

Not sure how to repeat this, but this happened to me when I was trying to get a cart unstuck after it turned perpendicular to a skinny section of dirt road. Worst case of parking ever. Karellen said it just happens sometimes when using cart.

Alpha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16910644/ea079656-4d2d-11e6-9035-01ed1440f529.png)

![image](https://cloud.githubusercontent.com/assets/6193670/16910681/29e5b1cc-4d2e-11e6-9fa4-8c53afaa7520.png)

**Comment by metachronism** [comment]
will be addessed with better art later, closing for now
