### ISSUE TITLE
USER ISSUE: Grass block turning into dirt

### ISSUE THREAD

**Issue by dutchtard** [StrangeLoopGames/EcoIssues#5101]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
It seems a lot of grass in the town is turning into dirt. People think this occurs if you mine below it but it is not everywhere above our mining place. I would like to know if it is supposed to act like this and how exactly or that this will get fixed. It might be caused when the layer between the hole below and the surface above is too thin.

**Expected behavior:**
Should be grass or turn into grass after placing dirt.

**Actual behavior:**
It turns into dirt and stays for that forever.

**Comment by MarjieAVolk** [comment]
Is it because of pollution?

If it is due to digging a mine below the ground... It might be because of the trampling feature.  If a bunch of people walk over things, it can trample the grass and make it die.  But I think it doesn't respect height.

**Comment by dutchtard** [comment]
It is not of pollution. As trampling was one of the possible reasons this seem to only happen above self mined tunnels or holes under the ground.

**Comment by Chi-Yu** [comment]
This one really turns the world ugly.

**Comment by craig-jong** [comment]
This is not a bug, but people might not be happy with it. World layers are 2d and so is trampled.

We'll look into changing how it works, but its currently working as intended.
