### ISSUE TITLE
USER ISSUE: Bookshelf doesn't work

### ISSUE THREAD

**Issue by Skelun** [StrangeLoopGames/EcoIssues#5103]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Pick a lot of materials
2. Do a lot of researchs
3. Pick even more materials
4. Make the bookshelf
5. Try to store your books in it

**Expected behavior:**
You storing your books

**Actual behavior:**
Just paperweight

**Comment by MarjieAVolk** [comment]
Yeah the book shelf does not store books.  It does increase your skill point gain if you have it in your house though.

**Comment by Skelun** [comment]
It is so incredibly frustrating I decided to make the issue on the bug session.

**Comment by Thyriel** [comment]
I agree that the bookshelf should be able to store ALL skillbooks at once. Additionally it would be great too to use it to store scrolls generated with skillbooks and deeds.

**Comment by MarjieAVolk** [comment]
That does sound pretty nice

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#232
