### ISSUE TITLE
Critical Server Crash

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5105]
After crafting of a powered Cart and having a server restart, going near the area where the cart is, gives the following crash, reproducable:

Unbehandelte Ausnahme: System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Eco.Gameplay.LegislationSystem.Districts.GetDistrictAt(WorldPosition3i position)
   bei Eco.Gameplay.Stats.PlayerActionExtensions.SetPosition(IHasPositionContext action, WorldPosition3i position)
   bei Eco.Gameplay.Stats.PlayerActionExtensions.SetWorldObjectAndPosition(IHasWorldObjectContext action, WorldObject worldObject)
   bei Eco.Gameplay.Stats.ConcretePlayerActions.PolluteAirPlayerActionManager.CreateAction(User user, AirPollutionComponent obj, Single value)
   bei Eco.Gameplay.Components.AirPollutionComponent.Tick()
   bei System.Collections.Generic.List1.ForEach(Action1 action)
   bei Eco.Gameplay.Objects.WorldObject.Tick()
   bei Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action1 action)
   bei Eco.Gameplay.Objects.WorldObjectManager.Run()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart(Object obj)
Can someone forward this to the right person?
Can't play anymore on my server until this is fixed :frowning:

Several server restarts tried. Every time i come to the area or anyone else - this crash.

**Comment by MarjieAVolk** [comment]
So it looks like the map that districts has is a smaller size than the actual world, perhaps.  What are your coordinates when this happens?  And how big is the world?

**Comment by D3nnis3n** [comment]
The world is 100x100.  Coordinates were 280,443. We got one District, that does indeed start about 20 blocks away from that coordinates. I did not quite get what you meant with "smaller" size, but the district is definatley smaller then the world.

**Comment by MarjieAVolk** [comment]
I meant that the districts system's map of districts is perhaps missing part of the world.  Which is very weird.  I had been wondering whether you were seeing this near the 0 border, on the high end, but it doesn't seem so.  Would you be able to send me your save file?

**Comment by D3nnis3n** [comment]
Unfortunatley i do not seem to have the corrupted save anymore - shame on me.
I only got the one we backupped from, and the later one when we had played a while further but i did not build the powered cart there and the issue didn't happen. Maybe this helps you nevertheless. I'm sorry. After that crash we set backups to hourly.

https://www.godsofwar.de/Eco.rar

(Please give me a headsup when you downloaded the file, so i can remove it again)

**Comment by MarjieAVolk** [comment]
Oh you know what - I just realized, probably the cart's position is not set correctly.  That makes more sense.

**Comment by MarjieAVolk** [comment]
I downloaded the save, just in case, but if it doesn't repro the issue it probably won't be too useful.

**Comment by D3nnis3n** [comment]
Well i just crafted the powered cart, tried to drive it, it was awful to drive on 4 wide roads, hit things quite often, got stuck quite often and somehow managed to drive it into a little flat niche. There it was stuck. Maybe this was the problem.

**Comment by Ekkelus** [comment]
I just got the same error:

`--BEGIN DUMP--
Dump Time
03/11/2018 21:53:54

Exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Gameplay.LegislationSystem.Districts.GetDistrictAt(WorldPosition3i position)
   at Eco.Gameplay.Stats.PlayerActionExtensions.SetPosition(IHasPositionContext action, WorldPosition3i position)
   at Eco.Gameplay.Stats.PlayerActionManager`1.CreateTypedDefaultAction(User user)
   at Eco.Gameplay.Stats.ConcretePlayerActions.PolluteAirPlayerActionManager.CreateAction(User user, AirPollutionComponent obj, Single value)
   at Eco.Gameplay.Components.AirPollutionComponent.Tick()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick()
   at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--`

**Comment by MarjieAVolk** [comment]
Oh good :P  Do you see it consistently?  Can you send us a save file?

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix.

**Comment by ljej1989** [comment]
No



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by ljej1989** [comment]
A
rrows on Swanson



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by ljej1989** [comment]
Sent from my Samsung Galaxy smartphone.
