### ISSUE TITLE
Admins do not get saved.

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5106]
Admins do vanish from the list after server restart.

**Comment by pamduncan** [comment]
When you add a admin via the server UI always do a File > Save and make sure the UI saves the admin to the Users.eco  You can double check that it was saved correctly and will load next time by checking the Users,eco config file (with notepad or notepad++) in the steamlibrary common/Eco/Eco_data/Server/Config if using the client or steamlibrary common/EcoServer/Config if running dedi through steam or just in the server installs <root>/Config if using the SLG dedi Server install

**Comment by D3nnis3n** [comment]
File -> Save does indeed work, but all the other values get automatically written into the files, despite the admin list. This should be changed, at least. Thanks for your help!

**Comment by Thyriel** [comment]
I had so far several config files being reset randomly on server restarts. Until a day or two ago i thought it where game patches resetting them, but seems they just randomly reset (although i have to add here that i use a hosted server and not one i run myself)
Files affected so far: difficulty.eco, network.eco, users.eco, ecosim.eco (basically all files i edited so far except discord.eco)

**Comment by D3nnis3n** [comment]
This does not happen to me - but all configs get reset when i update the server through steam. This should possibly not happen. Config files are not meant to be overwritten by updates ...

**Comment by Thyriel** [comment]
> This does not happen to me - but all configs get reset when i update the server through steam. This should possibly not happen. Config files are not meant to be overwritten by updates ... No other game does this.

The problem i see here is that ECO currently mixes configs with essential values. For example people may often want to adjust plant drop amounts or growing times, but unless they write a mod they won't want to change what item a wheat drops or what seeds it gives. But as all of these settings are currently in a single big file (ecosim.eco) i don't see how the need to overwrite cerrtain configs with new default files during a patch could be prevented.
For example when they add oak seeds the item must be configured in ecosim.eco or it won't drop.

Another problem is, especially through steam, that the default config files are just files delivered with the game instead generated files on game launch. So steam will always update them as it doesn't know that it's configs and not gamefiles you modified (or that got corrupted)

It won't be an easy task, but the only real solution i could think of with such "enormous" config files that literally define the whole game world is copying Minecraft Forge's config mechanic for mods. It's basically doing exactly what we would need here: Updating config files to newer versions but keeping single lines that where changed by the user (=not the config file's default value for the stored version number)

**Comment by D3nnis3n** [comment]
Afaik, ecosim.eco does not contain any of the values that can be changes in the server ui. So i propose to only overwrite ecosim.co and keep the other configs. Maybe also the profanity filter, but as we disabled it, we would be happy if it wouldn't get overwritten, too.

**Comment by Thyriel** [comment]
> Afaik, ecosim.eco does not contain any of the values that can be changes in the server ui. So i propose to only overwrite ecosim.co and keep the other configs. Maybe also the profanity filter, but as we disabled it, we would be happy if it wouldn't get overwritten, too.

That was just an example as it's the biggest config file. And it can be completely edited in the server UI. Go to "Simulation" tab > Config and then for example Species > click the collection button on the right

**Comment by D3nnis3n** [comment]
Uh, you are right. That is quite awesome.

**Comment by MarjieAVolk** [comment]
I think what we need to do first is separate out 'config' that is associated with the save file, such as admin lists and difficulty settings, and move that elsewhere, perhaps into the save file, so that it is per save and also won't be overridden.

**Comment by D3nnis3n** [comment]
Anything making my life easier when updating is much appreciated. I just wrote a batch script to overwrite the files after update for now.

**Comment by Thyriel** [comment]
I'm not sure if saving admin lists / difficulty settings into the savegame itself would be a good idea.
How would i become admin then if no admin has been set on world geeration ? How would i be able to change spec costs / crafting xp later ?

**Comment by D3nnis3n** [comment]
Ecxactly the same as now. Just with it being saved in the savegame instead of another file.

**Comment by Thyriel** [comment]
@D3nnis3n Now i can edit users.eco on a server to become admin but you can't edit a 200MB non-textfile...

**Comment by D3nnis3n** [comment]
Rite. Didn't think about that. I use the UI.

**Comment by MarjieAVolk** [comment]
Yeah we have recently changed save data to be a whole folder rather than a single file, so I would probably just move the config files into the save folder, and leave all the server window as is.

**Comment by Thyriel** [comment]
Btw i just noticed too that the problem of steam replacing files on update / error-checking is not only applying to config files, it's too overwriting changed files in /mods (=removing all mods)

**Comment by D3nnis3n** [comment]
That's ouchy.

Am 27.02.2018 20:38 schrieb "Thyriel" <notifications@github.com>:

**Comment by D3nnis3n** [comment]
Fixed via template-files a while ago.
