### ISSUE TITLE
Taking a cart with hammer and placing it down on the street lets the cart vanish

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5107]
I took a cart with a hammer, placed it down on a dirt road and the cart vanished. Even after several server restarts the Deed for the cart says "Missing Location" and points to 0,0,0 - the cart vanished.

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4899

**Comment by MarjieAVolk** [comment]
Reopening as not actually a duplicate of #4899

**Comment by MarjieAVolk** [comment]
"I also do not have that deed view. My deed view is normal and shows name of the cart and it's position. But it's Missing Position with Marker on 0,0,"

**Comment by SeanAtr0n** [comment]
fixed 7.2
