### ISSUE TITLE
USER ISSUE: Hole in world 

### ISSUE THREAD

**Issue by Isaaclele** [StrangeLoopGames/EcoIssues#5115]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Place stack of wood by work bench, three long and 2 high
2. start storing dirt behind wood and work bench
3 mine dirt to move it to stockpile

**Expected behavior:**
Allowed me to transfer dirt without creating a whole in the world

**Actual behavior:**
created hole in world by moving dirt

**Comment by MarjieAVolk** [comment]
Closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/3897
