### ISSUE TITLE
Partly Invisible Tree / Logs

### ISSUE THREAD

**Issue by SmattyCore** [StrangeLoopGames/EcoIssues#5116]
**Version:** Latest Stable Version from Steam
Complete New World
Connected to a Game inside my LAN

**Problem:**
If I chop down a tree it falls totally normal. If I want to chop the tree into smaller pieces then, I don't see these smaller pieces. It consumes energy and I need to press "E" after some seconds to try if there are already small pieces. Either I'm getting "log too big" or I pick up 5 pieces directly with one press. 
After that, there is still some tree laying around but I can't see it, although a hitbox is there, because I can't walk through it. 
Sometimes I get a "Chop" on this tree laying around but I can do it infinite (and not using calories), nothing happens. I can't pick up more pieces and other players are annoyed of trees laying all around that I can't see. 

Restarting the notebook + game has not solved this issue.

**Hardware/Software:**
CPU: Intel i5 Quad Core CPU with 2,50 GHz and up to 3.xx GHz boost
RAM: 8 GB
OS: Latest Windows 10 Version

**Comment by Nanders** [comment]
duplicate issue of https://github.com/StrangeLoopGames/EcoIssues/issues/4908
