### ISSUE TITLE
Pink box appeared

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#512]
Harvesting hundreds of ferns. This one turned into a pink box.
Haven't seen this before.
Alpha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16911269/a18a8d9e-4d31-11e6-97bd-f7e50b866bdb.png)

**Comment by mariowenig** [comment]
I've notices pink boxes when a material or thing is being placed where a plant used to be. I.e: if the space was previously occupied.

**Comment by noblackthunder** [comment]
is it there also after a relog? 
is it easily reproduced?

**Comment by metachronism** [comment]
this should now be fixed, was a builder issue
