### ISSUE TITLE
USER ISSUE: build a room

### ISSUE THREAD

**Issue by Inkraja** [StrangeLoopGames/EcoIssues#5120]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
in Single player, you are stuck in the begining, to build a room. I need roof and floor, both require the research table. but the research table needs o room

**Expected behavior:**
researchtable dont need a room for basic scrolls. only for higher tiers

**Actual behavior:**

**Comment by mreil617** [comment]
@Inkraja Single player is about being 100% efficient. It's a really long grind to the end by yourself. There are skills u can buy at the beginning that enable you to make a house for research. (Hewn Logs)

**Comment by MarjieAVolk** [comment]
You will have to build your first house using just the 'block' construct.  Later you can unlock the prettier constructs like roof.
