### ISSUE TITLE
USER ISSUE: Stockpile Trap

### ISSUE THREAD

**Issue by heimskringla** [StrangeLoopGames/EcoIssues#5122]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
drop items on non-empty stockpile while standing in the bottom left corner of it

**Expected behavior:**
dropped items where I wasn't standing

**Actual behavior:**
dropped them on me immobilising me. When I picked up the items, other items in the stockpile were dropped on me.

**Comment by fame1991** [comment]
Have the same problem

**Comment by MarjieAVolk** [comment]
For now, you will just need to use /unstuck to get out.

**Comment by MarjieAVolk** [comment]
Actually, closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4113
