### ISSUE TITLE
USER ISSUE: picking up/placing logs

### ISSUE THREAD

**Issue by mdbaal** [StrangeLoopGames/EcoIssues#5123]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
when I press E on logs really fast they don't disappear and when I place them into a stockpile, only the outline shows

**Expected behavior:**
should have rendered the logs mesh.

**Actual behavior:**
only created the collider and outlines

**Comment by mdbaal** [comment]
Disconnecting and re-connecting fixes it for that moment.

**Comment by SeanAtr0n** [comment]
Fixed a while back
