### ISSUE TITLE
USER ISSUE: No connection to server possible, first time accessing the server

### ISSUE THREAD

**Issue by fox19** [StrangeLoopGames/EcoIssues#5127]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. "Join"
2. Server chossen and having clicked on connect
3. Connection failure	

**Expected behavior:**
Connect to server and create a new character

**Actual behavior:**
The following error message popped up:
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Can you connect to other servers?  Can you connect to your own local games?

We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* Try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
