### ISSUE TITLE
No weight/carry limits when gathering food

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#513]
No weight/carry limits when gathering food, able to exceed 20kg in inventory.
With this it could be possible to harvest all available food on a small world.
Apha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16911313/d9e0cbb8-4d31-11e6-868f-6d2b98edd683.png)

**Comment by craig-jong** [comment]
That's a ton of ferns...
