### ISSUE TITLE
USER ISSUE: connectio failed

### ISSUE THREAD

**Issue by liloso** [StrangeLoopGames/EcoIssues#5131]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
join a friend on steam 
ps same happens to my friend if he joins me

**Expected behavior:**
joining my friend and have a nice day playing with him

**Actual behavior:**
connection failed

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When running your own game, run the server via the EcoServer tool
* When connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
