### ISSUE TITLE
USER ISSUE: WebSitePlugin Failure

### ISSUE THREAD

**Issue by Nariluna** [StrangeLoopGames/EcoIssues#5133]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Everytime i wanted to start a new world 

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the EcoServer tool
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by Nariluna** [comment]
Can you tell me where I can find this folder ?The other methods doesn't work. 
At the same part, when it says "Starting WebServerPlugin..." the game doesn't run further. 

    MarjieAVolk <notifications@github.com> schrieb am 0:07 Dienstag, 27.Februar 2018:
 

 We are working on a number of connection problems. There are a couple of things you can try as a workaround:   
   - Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
   - Temporarily disabling your firewall and/or antivirus software
   - When starting a new world, select 'Generate new'
   - Run the server via the EcoServer tool
   - If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

**Comment by MarjieAVolk** [comment]
Are you on a windows computer?  The file path I gave you for the client logs is an exact file path, you just have to insert your windows username: 'C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

This one is based on where you have steam installed: '[...]\steamapps\common\Eco Server'  Usually it will be in 'C:\Program Files\Steam\steamapps\common\Eco Server'

**Comment by Nariluna** [comment]
I'm really sorry. My english isn't that good. I'm really glad you want to help me, but I don't understand that.  I haven't much computer knowlegdes. Maybe, and if I'm in the position to asked that, you tell it me again.. but in a simple way?
Thank you really much for your help! 

    MarjieAVolk <notifications@github.com> schrieb am 1:36 Dienstag, 27.Februar 2018:
 

 Are you on a windows computer? The file path I gave you for the client logs is an exact file path, you just have to insert your windows username: 'C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'This one is based on where you have steam installed: '[...]\steamapps\common\Eco Server' Usually it will be in 'C:\Program Files\Steam\steamapps\common\Eco Server'—

**Comment by Nariluna** [comment]
Where at my PC should i search this file? I speak german 
Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Feb. 28, 2018 at 19:35 schrieb MarjieAVolk<notifications@github.com>:   
I don't know how to say it differently. I am just asking you to look up a file on your computer. What language do you speak?

**Comment by MarjieAVolk** [comment]
'C:\Users\[Ihr Windows-Benutzername]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

und Protokolldateien in diesem Ordner:
'[Überall, wo Steam installiert ist]\steamapps\common\Eco Server'

**Comment by Nariluna** [comment]
And where do I have to put these file in? and maybe i have an idee. I saw that I can't on the official website from Strange Loop Games linking my steam account to this site... Maybe is this the problem? Because the systems says.. connetion Failure.. so i though. What do you mean?

    MarjieAVolk <notifications@github.com> schrieb am 19:51 Mittwoch, 28.Februar 2018:
 

 'C:\Users[Ihr Windows-Benutzername]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'und Protokolldateien in diesem Ordner:
'[Überall, wo Steam installiert ist]\steamapps\common\Eco Server'—

**Comment by MarjieAVolk** [comment]
I want you to share the files with me.  Either upload and attach them, or you can paste their contents in here.

It is okay that your account isn't linked, we are not allowing that anymore because of some scams.

**Comment by Nariluna** [comment]
i hope i don't misunderstand something.. also you want a copy of the complete folder from the game on my pc ?I'm really sorry to make you such trouble ... I really didn't mean so. 

    MarjieAVolk <notifications@github.com> schrieb am 0:06 Donnerstag, 1.März 2018:
 

 I want you to share the files with me. Either upload and attach them, or you can paste their contents in here.It is okay that your account isn't linked, we are not allowing that anymore because of some scams.—

**Comment by MarjieAVolk** [comment]
Inside the folder '[Überall, wo Steam installiert ist]\steamapps\common\Eco Server', look for files named 'log' or 'crashdump', and copy those here.

**Comment by Nariluna** [comment]
I really really hope these are the right files. Sorry to make it that hard to explain it for me . 

    MarjieAVolk <notifications@github.com> schrieb am 0:14 Donnerstag, 1.März 2018:
 

 Inside the folder '[Überall, wo Steam installiert ist]\steamapps\common\Eco Server', look for files named 'log' or 'crashdump', and copy those here.—

**Comment by MarjieAVolk** [comment]
Hey, sorry I don't see any attachments.  If you are attaching from the email, that might not work.  Better to attach on Github, or paste in the contents.

**Comment by Nariluna** [comment]
I cant .copy those file at github, because they didn't support these typs of files. What can i do now ? 

    Julia Becke <julia.becke@yahoo.de> schrieb am 0:21 Donnerstag, 1.März 2018:
 

 I really really hope these are the right files. Sorry to make it that hard to explain it for me . 

    MarjieAVolk <notifications@github.com> schrieb am 0:14 Donnerstag, 1.März 2018:
 

 Inside the folder '[Überall, wo Steam installiert ist]\steamapps\common\Eco Server', look for files named 'log' or 'crashdump', and copy those here.—

**Comment by MarjieAVolk** [comment]
Either paste their contents in here, or upload them to a file sharing site such as Dropbox or Google Drive.
