### ISSUE TITLE
USER ISSUE: No space found to save files

### ISSUE THREAD

**Issue by menoudste** [StrangeLoopGames/EcoIssues#5134]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Launch a game
2. --> error message

**Expected behavior:**
Should launch a new game

**Actual behavior:**
The following error message popped up:
```
Could not create save file: Destination directory not found: E:/SteamLibrary/steamapps/common/Eco/Eco_Data/Server/Storage\TEST 
Could not create save file: Destination directory not found: E:/SteamLibrary/steamapps/common/Eco/Eco_Data/Server/Storage\TEST 
```

**Comment by MarjieAVolk** [comment]
That is odd.  Assuming the rest of the path is correct, you can work around this for now by creating the folder listed there.  Go into your eco installation, go to the Server folder, and create an empty folder named 'Storage' there.

If the rest of the path given there is not correct, let me know

**Comment by WeaselDog** [comment]
This was fixed with changes to how multiple saves are handled in the client.
