### ISSUE TITLE
USER ISSUE: Can´t connect to Lan server

### ISSUE THREAD

**Issue by Steffilli** [StrangeLoopGames/EcoIssues#5135]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
When I click under the Join button on connect it always says Connection failed. Server is full.
But i played yesterday with my friend on this server, and now i can´t connect to it again.

**Expected behavior:**
It should connect to the server without problems

**Actual behavior:**
Instead it says Server is full or under the continue button in the mainmenu it says offline.

**Comment by MarjieAVolk** [comment]
'Server is full' means there are too many people online right now.  Try to connect later, or ask the server admin to increase the cap on how many people can be online at once.

If your friend is running the server (I wasn't sure from your description) - they can change the cap in the server window (they can open this via /openserverui if they don't already have it open).  Under Users>Config set MaxSlots to however many you want.  Or set it to -1 for no cap.
