### ISSUE TITLE
USER ISSUE: Connection failed when creating a new game

### ISSUE THREAD

**Issue by menoudste** [StrangeLoopGames/EcoIssues#5136]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Create a new game
2. Launch it
3. --> Error message

**Expected behavior:**
Launch the game without losing connection

**Actual behavior:**
The following error message popped up:
```
Connection Failed
Connection Failed
```

**Comment by MarjieAVolk** [comment]
We are working on a number of connection problems.  There are a couple of things you can try as a workaround:

* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* When starting a new world, select 'Generate new'
* Run the server via the EcoServer tool
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server' and 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'
