### ISSUE TITLE
Treasury can't allocate all funds

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5140]
Hello, it's impossible to allocate all currency to someone.
E.g. you have 47,87 Dollars - you can only give 47,86 Dollars to people. If you put in 47,87 Dollars it says there is not enough currency to distribute, despite there is.

**Comment by LiaungYip** [comment]
Is it possible that the player actually has (for example) 12.345 Dollars, and the game is rounding this up to 12.35 for display?

**Comment by D3nnis3n** [comment]
We did only with denominations up to x.xx, so no, in our case this should not be the case.

Gesendet von Mail für Windows 10

Von: Li-aung Yip
Gesendet: Donnerstag, 1. März 2018 19:12
An: StrangeLoopGames/EcoIssues
Cc: D3nnis3n; Author
Betreff: Re: [StrangeLoopGames/EcoIssues] Treasury can't allocate all funds(#5140)

Is it possible that the player actually has (for example) 12.345 Dollars, and the game is rounding this up to 12.35 for display?

**Comment by D3nnis3n** [comment]
After trying again, it's most probably because of the rounding. Maybe the treasury should then just allocate all funds available or at least show the exact value.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/11561
