### ISSUE TITLE
USER ISSUE: Floating Washing Machine

### ISSUE THREAD

**Issue by Lagicrus** [StrangeLoopGames/EcoIssues#5141]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Put down a washing machine
(Currently a broken object)
2. Walk a distance away
3. Look back
4. Its floating in a point in space

**Expected behavior:**
It should have not floated

**Actual behavior:**
Instead it floated

**Comment by MarjieAVolk** [comment]
@keegan-o Sounds like it doesn't have the curved shader on it or something.

**Comment by Lagicrus** [comment]
https://imgur.com/a/5tbWN Here are some images as proof from varying distances

**Comment by MarjieAVolk** [comment]
Oh it doesn't even have art, I see.
