### ISSUE TITLE
USER ISSUE: cant restart tutorial

### ISSUE THREAD

**Issue by CakeSama** [StrangeLoopGames/EcoIssues#5142]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
click restart tutorial button 

**Expected behavior:**
nothing happens

**Actual behavior:**
something normali happen

**Comment by MarjieAVolk** [comment]
Could you attach your log file?  C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt

**Comment by CakeSama** [comment]
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1760850/output_log.txt)

**Comment by johnkslg** [comment]
Fixed in staging
